### ISSUE TITLE
Support reverse proxy headers from in the Blazor Dev Server

### ISSUE THREAD

**Issue by Swellenator** [dotnet/aspnetcore#10136]
I'm trying to use browser-sync to automatically reload the browser page when code changes. My setup is:

`browser-sync start --proxy http://localhost:4698/ --ws --serveStatic "./wwwroot/css/" -w --files "./wwwroot/, bin"`

It says:

`Browsersync Proxying: http://localhost:4698
Browsersync Access URLs:
 ------------------------------------
       Local: http://localhost:3001
    External: http://10.22.6.126:3001
 ------------------------------------
          UI: http://localhost:3003
 UI External: http://localhost:3003
 ------------------------------------
Browsersync Watching files...`

Then for dotnet I do
`dotnet.exe watch run`

Which says

` Now listening on: http://localhost:4698`

When I load the index page at `http://localhost:3001` the console log says

`[2019-05-10T06:07:43.164Z] Information: Normalizing '_blazor' to 'http://localhost:3001/_blazor'.
[2019-05-10T06:07:43.390Z] Information: WebSocket connected to ws://localhost:3001/_blazor?id=MKHYicnWXPAYfZr1Wk7aLg.`

Which is good, but then clicking on any link, eg. `<NavLink href="login">Login</NavLink>` I go nowhere and get the following error in the console:

`blazor.server.js:8 Uncaught (in promise) Error: System.ArgumentException: The URI 'http://localhost:3001/login' is not contained by the base URI 'http://localhost:4698/'.
   at Microsoft.AspNetCore.Components.UriHelperBase.ToBaseRelativePath(String baseUri, String locationAbsolute)
   at Microsoft.AspNetCore.Components.Routing.Router.Refresh()
   at Microsoft.AspNetCore.Components.Routing.Router.OnLocationChanged(Object sender, String newAbsoluteUri)
   at Microsoft.AspNetCore.Components.UriHelperBase.TriggerOnLocationChanged()
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteUriHelper.NotifyLocationChanged(String uriAbsolute)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.JSInterop.DotNetDispatcher.InvokeSynchronously(String assemblyName, String methodIdentifier, Object targetInstance, String argsJson)
   at Microsoft.JSInterop.DotNetDispatcher.BeginInvoke(String callId, String assemblyName, String methodIdentifier, Int64 dotNetObjectId, String argsJson)
    at endInvokeDotNetFromJS (http://localhost:3001/_framework/blazor.server.js:8:21783)
    at http://localhost:3001/_framework/blazor.server.js:8:21434
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (http://localhost:3001/_framework/blazor.server.js:8:21403)
    at http://localhost:3001/_framework/blazor.server.js:1:16653
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (http://localhost:3001/_framework/blazor.server.js:1:16624)
    at e.processIncomingData (http://localhost:3001/_framework/blazor.server.js:1:14624)
    at e.connection.onreceive (http://localhost:3001/_framework/blazor.server.js:1:11165)
    at WebSocket.i.onmessage (http://localhost:3001/_framework/blazor.server.js:1:30454)`

It seems that somehow blazor/aspnet knows about the 4698 port and isn't allowing the proxy properly. 

Does anyone have any ideas?

Thanks

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Swellenator.
Assuming you're passing all the headers through the reverse proxy, we'll need to do some work on the dev server to honor those headers.
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
