### ISSUE TITLE
BadHttpRequestException: Invalid request line: '\x0D\x0A', only on Kestrel, works with IISExpres/IIS

### ISSUE THREAD

**Issue by MattiaDurli** [dotnet/aspnetcore#10326]
I have an IOT device (black box, can't reprogram it) that sends http POST requests (136 bytes of JSON, a string) to my .NET core 2.2 very simple server console application (created with webapi console template). 
I added the following lines and just output the string to the console.

```
public class RootObject
    {
        public string prt { get; set; }
    }    
    [HttpPost]
    public void Post([FromBody] RootObject root)
    {
        string adv = root.prt;
        Console.WriteLine(adv);
    }
```

The strings gets always printed but to the first request I get a 200 and no exceptions, to the following I get a 400 and an exception, and it goes on like this 200, 400, 200, 400...

```
dbug: Microsoft.AspNetCore.Server.Kestrel[1]
      Connection id "0HLMQL2QCEH73" started.
dbug: Microsoft.AspNetCore.Server.Kestrel.Core.Adapter.Internal.LoggingConnectionAdapter[0]
      ReadAsync[240] 50 4F 53 54 20 2F 61 70 69 2F 76 61 6C 75 65 73 20 48 54 54 50 2F 31 2E 31 0D 0A 48 4F 53 54 3A 20 31 39 32 2E 31 36 38 2E 30 2E 39 32 0D 0A 43 6F 6E 74 65 6E 74 2D 54 79 70 65 3A 20 61 70 70 6C 69 63 61 74 69 6F 6E 2F 6A 73 6F 6E 0D 0A 43 6F 6E 74 65 6E 74 2D 4C 65 6E 67 74 68 3A 20 31 33 36 0D 0A 0D 0A 7B 22 70 72 74 22 3A 22 30 32 30 30 33 46 30 30 32 32 39 33 38 33 31 30 30 30 30 31 30 30 33 33 46 46 30 30 30 36 45 46 41 41 32 35 36 42 36 44 31 41 30 30 31 45 30 31 30 32 30 31 30 36 31 41 46 46 34 43 30 30 30 32 31 35 34 37 36 43 36 46 36 32 36 31 36 43 32 44 35 34 36 31 36 37 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 43 44 30 31 30 31 44 36 30 30 30 31 46 46 30 30 46 37 33 34 22 7D 0D 0A
      POST /api/values HTTP/1.1
      HOST: 192.168.0.92
      Content-Type: application/json
      Content-Length: 136

      {"prt":"02003F002293831000010033FF0006EFAA256B6D1A001E010201061AFF4C000215476C6F62616C2D54616700000000000000000000CD0101D60001FF00F734"}

info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://192.168.0.92/api/values application/json 136
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1001]
      2 candidate(s) found for the request path '/api/values'
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005]
      Endpoint 'BluepycWeb.Controllers.ValuesController.Post (BluepycWeb)' with route pattern 'api/Values' is valid for the request path '/api/values'
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005]
      Endpoint 'BluepycWeb.Controllers.ValuesController.HEX2ASCII (BluepycWeb)' with route pattern 'api/Values' is valid for the request path '/api/values'
dbug: Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware[1]
      Request matched endpoint 'BluepycWeb.Controllers.ValuesController.Post (BluepycWeb)'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'BluepycWeb.Controllers.ValuesController.Post (BluepycWeb)'
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Route matched with {action = "Post", controller = "Values"}. Executing action BluepycWeb.Controllers.ValuesController.Post (BluepycWeb)
dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Execution plan of authorization filters (in the following order): None
dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter
dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000), Microsoft.AspNetCore.Mvc.Infrastructure.ModelStateInvalidFilter (Order: -2000)
dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Execution plan of exception filters (in the following order): None
dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.SaveTempDataFilter, Microsoft.AspNetCore.Mvc.Infrastructure.ClientErrorResultFilter (Order: -2000)
dbug: Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder[22]
      Attempting to bind parameter 'root' of type 'BluepycWeb.Controllers.RootObject' ...
dbug: Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder[44]
      Attempting to bind parameter 'root' of type 'BluepycWeb.Controllers.RootObject' using the name '' in request data ...
dbug: Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder[2]
      Rejected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonPatchInputFormatter' for content type 'application/json'.
dbug: Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder[1]
      Selected input formatter 'Microsoft.AspNetCore.Mvc.Formatters.JsonInputFormatter' for content type 'application/json'.
dbug: Microsoft.AspNetCore.Server.Kestrel[25]
      Connection id "0HLMQL2QCEH73", Request id "0HLMQL2QCEH73:00000001": started reading request body.
dbug: Microsoft.AspNetCore.Server.Kestrel[26]
      Connection id "0HLMQL2QCEH73", Request id "0HLMQL2QCEH73:00000001": done reading request body.
dbug: Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder[45]
      Done attempting to bind parameter 'root' of type 'BluepycWeb.Controllers.RootObject'.
dbug: Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder[23]
      Done attempting to bind parameter 'root' of type 'BluepycWeb.Controllers.RootObject'.
dbug: Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder[26]
      Attempting to validate the bound parameter 'root' of type 'BluepycWeb.Controllers.RootObject' ...
dbug: Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder[27]
      Done attempting to validate the bound parameter 'root' of type 'BluepycWeb.Controllers.RootObject'.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method BluepycWeb.Controllers.ValuesController.Post (BluepycWeb) with arguments (BluepycWeb.Controllers.RootObject) - Validation state: Valid
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action method BluepycWeb.Controllers.ValuesController.Post (BluepycWeb), returned result Microsoft.AspNetCore.Mvc.EmptyResult in 0.0045ms.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action BluepycWeb.Controllers.ValuesController.Post (BluepycWeb) in 30.0316ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'BluepycWeb.Controllers.ValuesController.Post (BluepycWeb)'
dbug: Microsoft.AspNetCore.Server.Kestrel.Core.Adapter.Internal.LoggingConnectionAdapter[0]
      WriteAsync[92] 48 54 54 50 2F 31 2E 31 20 32 30 30 20 4F 4B 0D 0A 44 61 74 65 3A 20 46 72 69 2C 20 31 37 20 4D 61 79 20 32 30 31 39 20 30 39 3A 31 39 3A 31 37 20 47 4D 54 0D 0A 53 65 72 76 65 72 3A 20 4B 65 73 74 72 65 6C 0D 0A 43 6F 6E 74 65 6E 74 2D 4C 65 6E 67 74 68 3A 20 30 0D 0A 0D 0A
      HTTP/1.1 200 OK
      Date: Fri, 17 May 2019 09:19:17 GMT
      Server: Kestrel
      Content-Length: 0


dbug: Microsoft.AspNetCore.Server.Kestrel[9]
      Connection id "0HLMQL2QCEH73" completed keep alive response.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 79.2784ms 200
info: Microsoft.AspNetCore.Server.Kestrel[17]
      Connection id "0HLMQL2QCEH73" bad request data: "Invalid request line: '\x0D\x0A'"
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Invalid request line: '\x0D\x0A'
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.RejectRequestLine(Byte* requestLine, Int32 length)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.GetUnknownMethod(Byte* data, Int32 length, Int32& methodLength)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseRequestLine(TRequestHandler handler, Byte* data, Int32 length)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseRequestLine(TRequestHandler handler, ReadOnlySequence`1& buffer, SequencePosition& consumed, SequencePosition& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.IHttpParser<TRequestHandler>.ParseRequestLine(TRequestHandler handler, ReadOnlySequence`1& buffer, SequencePosition& consumed, SequencePosition& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TakeStartLine(ReadOnlySequence`1 buffer, SequencePosition& consumed, SequencePosition& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.ParseRequest(ReadOnlySequence`1 buffer, SequencePosition& consumed, SequencePosition& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TryParseRequest(ReadResult result, Boolean& endConnection)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
dbug: Microsoft.AspNetCore.Server.Kestrel.Core.Adapter.Internal.LoggingConnectionAdapter[0]
      WriteAsync[120] 48 54 54 50 2F 31 2E 31 20 34 30 30 20 42 61 64 20 52 65 71 75 65 73 74 0D 0A 43 6F 6E 6E 65 63 74 69 6F 6E 3A 20 63 6C 6F 73 65 0D 0A 44 61 74 65 3A 20 46 72 69 2C 20 31 37 20 4D 61 79 20 32 30 31 39 20 30 39 3A 31 39 3A 31 37 20 47 4D 54 0D 0A 53 65 72 76 65 72 3A 20 4B 65 73 74 72 65 6C 0D 0A 43 6F 6E 74 65 6E 74 2D 4C 65 6E 67 74 68 3A 20 30 0D 0A 0D 0A
      HTTP/1.1 400 Bad Request
      Connection: close
      Date: Fri, 17 May 2019 09:19:17 GMT
      Server: Kestrel
      Content-Length: 0


dbug: Microsoft.AspNetCore.Server.Kestrel[10]
      Connection id "0HLMQL2QCEH73" disconnecting.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
      Connection id "0HLMQL2QCEH73" sending FIN because: "The Socket transport's send loop completed gracefully."
dbug: Microsoft.AspNetCore.Server.Kestrel[2]
      Connection id "0HLMQL2QCEH73" stopped.
```

This happens if I selfhost Kestrel with the console app.
If I host the same app in IISExpress or IIS, no exception and always returns 200.
If I use Fiddler as reverse proxy, forwarding to my selfhosted Kestrel, no exception and always returns 200.

The IOT device sends approx 10 req per second.
When I host with IISExpress (for example) it processes all the requests.
When I selfhost, and get the exception, it processes 1 or 2 requests per second.

I understand that it may be the IOT device that behaves incorrectly (altough I don't know how) but why the problem arises only with selfhosted Kestrel? 

dotnet --info

```
.NET Core SDK (che rispecchia un qualsiasi file global.json):
 Version:   2.2.100
 Commit:    b9f2fa0ca8

Ambiente di runtime:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.100\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed
```

**Comment by Tratcher** [comment]
Yes, the request is invalid. It specifies `Content-Length: 136`, sends the 136 byte body, and then includes `0D 0A` (CRLF) at the end. That extra CRLF exceeds the content-length. Some servers are tolerant of extra CRLFs but Kestrel is not.

Can the IOT device send Chunked requests instead?

**Comment by anurse** [comment]
It looks like there isn't actionable work for Kestrel here, since the request is invalid (as @Tratcher indicated). Moving this to discussions so that conversation can continue. If something actionable does come up, we can re-evaluate then.

**Comment by MattiaDurli** [comment]
Thanks, I'll contact the manufacturer of the device and ask to correct the error or if is possible to configure it for Chunked requests.
In the meantime, isn't there a way to preprocess the raw httprequest before it gets processed by Kestrel?
I mean, in my selfhosted app, not using IIS or a proxy.

Thanks

**Comment by Tratcher** [comment]
It's possible but not easy. I see you're already using the LoggingConnectionAdapter to debug this. You can take that as a template for making your own connection adapter that pre-parses requests and filters out the bad CRLF.
https://github.com/aspnet/AspNetCore/blob/master/src/Servers/Kestrel/Core/src/Adapter/Internal/LoggingConnectionAdapter.cs
https://github.com/aspnet/AspNetCore/blob/a3c8bd16f7c0eaa473364460e0354b2b0cc7fdad/src/Servers/Kestrel/Core/src/Adapter/Internal/LoggingStream.cs#L102-L104
