### ISSUE TITLE
Windows unix domain sockets don't work with binding syntax

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#10782]
This works:

```C#
public static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
        .ConfigureWebHostDefaults(webBuilder =>
        {
            webBuilder.UseStartup<Startup>()
                      .UseKestrel(o =>
                      {
                          o.ListenUnixSocket(@"C:\Users\david\source\repos\WebApplication270\WebApplication270\pipe.socket");
                      });
        });
```

This does not work:

```C#
public static IHostBuilder CreateHostBuilder(string[] args) =>
    Host.CreateDefaultBuilder(args)
        .ConfigureWebHostDefaults(webBuilder =>
        {
            webBuilder.UseStartup<Startup>()
                      .UseUrls(@"http://unix://C:\Users\david\source\repos\WebApplication270\WebApplication270\pipe.socket");
        });
```

```
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.InvalidOperationException: A path base can only be configured using IApplicationBuilder.UsePathBase().
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.ParseAddress(String address, Boolean& https)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)

Unhandled Exception: System.InvalidOperationException: A path base can only be configured using IApplicationBuilder.UsePathBase().
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.ParseAddress(String address, Boolean& https)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.Internal.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at WebApplication270.Program.Main(String[] args) in C:\Users\david\source\repos\WebApplication270\WebApplication270\Program.cs:line 16
````

**Comment by mjohn** [comment]
Is there any specific format for Unix Socket URLs? I looked at other libraries, [request](https://github.com/request/request) uses `http://unix:SOCKET:PATH` as pattern.

- Example for Unix that perfectly matches with pattern:
 Url: `http://unix:/tmp/kestrel-test.sock`
Socket: `/tmp/kestrel-test.sock`
Path: ``

Above pattern is not going to work as expected in windows because absolute path needs a drive letter + colon like `C:`
Assume that we found a good way to parse that absolute path, can this sample url mislead us in a way?
- Example for Windows
Url: `http://unix://C:\Users\david\source\repos\WebApplication270\WebApplication270\pipe.socket`
Socket `//C:\Users\david\source\repos\WebApplication270\WebApplication270\pipe.socket`

This socket path doesn't look right. Are two slashes after unix scheme invalid or should it be better to ignore them when we are parsing the url?

**Comment by davidfowl** [comment]
Maybe something like this:
```
http://unix:/C:/Users/david/source/repos/WebApplication270/WebApplication270/pipe.socket
```
Maybe a bit unnatural as a windows user but easier for parsing?

**Comment by mjohn** [comment]
agree, it's much easier, because UnixPipeHostPrefix has `/` at the end. It won't need to be edited.

https://github.com/aspnet/AspNetCore/blob/4ef204e13b88c0734e0e94a1cc4c0ef05f40849e/src/Http/Http/src/BindingAddress.cs#L11

Thank you.

**Comment by davidfowl** [comment]
@halter73 we fixed this right?
