### ISSUE TITLE
Net core exception handler lambda creates duplicates

### ISSUE THREAD

**Issue by Pilchie** [dotnet/aspnetcore#10993]
_From @micgruber on Friday, May 3, 2019 12:58:55 PM_

I'm using a lambda function for the UseExceptionHandler method and .net core 2.2 with windows 10:

```c#
public static class ExceptionMiddlewareExtensions
{
    public static void ConfigureExceptionHandler(this IApplicationBuilder app, ILogger logger)
    {
        app.UseExceptionHandler(builder =>
        {
            builder.Run(async context =>
            {
                context.Response.ContentType = "application/json";
                var feature = context.Features.Get<IExceptionHandlerPathFeature>();
                var exception = feature.Error;

                var contextFeature = context.Features.Get<IExceptionHandlerFeature>();
                if (contextFeature != null)
                {
                    LogError(contextFeature, logger);
                    await ForwardError(context, exception);
                }
            });
        });
    }

    private static void LogError(IExceptionHandlerFeature contextFeature, ILogger logger)
    {
        logger.LogError($"{contextFeature.Error}");
    }

    private static async Task ForwardError(HttpContext context, Exception exception)
    {
        var httpStatusCodeException = exception as HttpException;
        if (exception is HttpException)
        {
            context.Response.StatusCode = (int)httpStatusCodeException.StatusCode;
            await context.Response.WriteAsync(new ErrorDetails()
            {
                Date = DateTime.UtcNow,
                Version = "v1",
                Code = httpStatusCodeException.Code,
                Type = httpStatusCodeException.Type.ToString(),
                Message = httpStatusCodeException.Message
            }.ToString());
        }
        else
        {
            context.Response.StatusCode = (int)HttpStatusCode.InternalServerError;
            await context.Response.WriteAsync(new ErrorDetails()
            {
                Date = DateTime.UtcNow,
                Version = "v1",
                Code = Code.InternalServerError,
                Type = Exceptions.Type.InvalidParameter.ToString(),
                Message = "Internal Server Error."
            }.ToString());
        }
    }
}
```
Now, I register the exception handler in the startup.cs

```c#
public class Startup
{
    private ILogger logger;

    public Startup(ILogger<Startup> logger)
    {
        this.logger = logger;
    }

    public void ConfigureServices(IServiceCollection services)
    {
    }

    public void Configure(IApplicationBuilder app, IHostingEnvironment env)
    {
        if (env.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }

        app.UseStatusCodePages();
        app.ConfigureExceptionHandler(logger);
        app.UseMiddleware<ProxyMiddleware>();
    }
}
```

Now, if throw a exception in the proxymiddleware in the invoke method the exception gets logged twice, what I'm doing wrong? I only want to log the exception once.

ProxyMiddleware:

```c#
public class ProxyMiddleware
{
    private readonly RequestDelegate next;

    public ProxyMiddleware(RequestDelegate next)
    {
        if (next == null)
        {
            throw new ArgumentNullException(nameof(next));
        }

        this.next = next;
    }

    public Task Invoke(HttpContext context)
    {
        if (context == null)
        {
            throw new ArgumentNullException(nameof(context));
        }

        throw new ArgumentNullException("Test");
    }
}
```

These are the exceptions logs from the console, which I get from the middleware:

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://127.0.0.1:4000/test
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.ArgumentNullException: Value cannot be null.
Parameter name: Test
   at TestProject.ProxyMiddleware.Invoke(HttpContext context) in C:\TestProject\ProxyMiddleware.cs:line 29
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
fail: TestProject.Startup[0]
      System.ArgumentNullException: Value cannot be null.
      Parameter name: Test
         at TestProject.ProxyMiddleware.Invoke(HttpContext context) in C:\TestProject\ProxyMiddleware.cs:line 29
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 4681.7259ms 500 application/json
```

It seems like I get the exception two times from the standard exception middleware Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1] and from the custom UseExceptionHandler. Is this the standard behaviour or am I doing something wrong?

I created a test project: https://github.com/micgruber/ExceptionMiddleware.

_Copied from original issue: dotnet/core#2674_

**Comment by Tratcher** [comment]
The middleware always logs the exception before it invokes your lambda:
https://github.com/aspnet/AspNetCore/blob/1b5db12d3f849fed5195007e8eae1ebee80f0542/src/Middleware/Diagnostics/src/ExceptionHandler/ExceptionHandlerMiddleware.cs#L92
You can remove your log to avoid duplicates.

**Comment by andyvig** [comment]
This is really unfortunate.  If we wire up Serilog's UseSerilogRequestLogging we get a double log.  My team has another use case also but it's more obscure.  
It would be great if this was more configurable.
