### ISSUE TITLE
[SignalR] Disgraceful disconnects result in failure logs

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#11335]
```
System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport.StartReceiving(WebSocket socket)
dbug: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[4]
      Waiting for the application to finish sending data.
fail: Microsoft.AspNetCore.SignalR.HubConnectionContext[5]
      Failed connection handshake.
```

There's not much a server could do if a client doesn't want to be friends. It should be logged as a debug or at best an info message, but not a error.

**Comment by pranavkm** [comment]
cc @anurse

**Comment by anurse** [comment]
Hrm, this is actually a little different than I thought when we first talked. The actual error being reported is `Failed connection handshake`. There are definitely cases where we do want to log this. We'll have to inspect the exception to determine that this is an unexpected close.

**Comment by blowdart** [comment]
This could be indicative of naughtiness, so now, disgraceful might be the correct term. Not logging this might mean hiding fingerprints of an attack.

**Comment by anurse** [comment]
We definitely will continue to log, this is about what level we do so at.

This feels like it will take more investigation than we can do in preview 7, and is a bit too user-facing for preview 8 IMO. Putting on the backlog for now. I feel OK over-reporting this error. We have users asking about it sometimes, so we could make this better in 3.1.

**Comment by davidfowl** [comment]
We should clean up our logs.

**Comment by BrennanConroy** [comment]
I don't think there is anything to do here. Pranav conveniently didn't include the log message that went with that exception, but if you look at it, it's a debug log.
https://github.com/dotnet/aspnetcore/blob/4d695c3f667886a71933046034c81994e7ee70df/src/SignalR/common/Http.Connections/src/Internal/Transports/WebSocketsServerTransport.Log.cs#L53

The only error here, is the handshake failure which I think is fine to log as error.
