### ISSUE TITLE
Blazor: Exception 'RemoteUriHelper' has not been initialized when using AuthenticationStateProvider server-side

### ISSUE THREAD

**Issue by sbwalker** [dotnet/aspnetcore#11867]
### Describe the bug
After declaring the AuthenticationStateProvider in Startup.cs in a server-side Blazor project which registers HttpClient in the recommended manner, an exception is thrown "System.InvalidOperationException: 'RemoteUriHelper' has not been initialized."

### To Reproduce
ASP.NET Core 3 Preview 6

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddRazorPages();
            services.AddServerSideBlazor();

            // server-side Blazor does not register HttpClient by default
            if (!services.Any(x => x.ServiceType == typeof(HttpClient)))
            {
                // setup HttpClient for server side in a client side compatible fashion
                services.AddScoped<HttpClient>(s =>
                {
                    // creating the URI helper needs to wait until the JS Runtime is initialized, so defer it.
                    var uriHelper = s.GetRequiredService<IUriHelper>();
                    return new HttpClient
                    {
                        BaseAddress = new Uri(uriHelper.GetBaseUri())
                    };
                });
            }

             // register auth services
            services.AddAuthorizationCore();
            services.AddScoped<AuthenticationStateProvider, ServerAuthenticationStateProvider>();

Build and run application... exception thrown:

System.InvalidOperationException: 'RemoteUriHelper' has not been initialized.
   at Microsoft.AspNetCore.Components.UriHelperBase.AssertInitialized()
   at Microsoft.AspNetCore.Components.UriHelperBase.GetBaseUri()
   at Oqtane.Server.Startup.<>c.<ConfigureServices>b__4_0(IServiceProvider s) in C:\Siliqon\Oqtane\sbwalker.oqtane.framework\Oqtane.Server\Startup.cs:line 57
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Components.Server.Circuits.DefaultCircuitFactory.CreateCircuitHost(HttpContext httpContext, CircuitClientProxy client, String uriAbsolute, String baseUriAbsolute)
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitPrerenderer.GetOrCreateCircuitHost(HttpContext context, CircuitNavigationStatus navigationStatus)
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitPrerenderer.PrerenderComponentAsync(ComponentPrerenderingContext prerenderingContext)
   at Microsoft.AspNetCore.Mvc.Rendering.HtmlHelperComponentPrerenderingExtensions.RenderComponentAsync[TComponent](IHtmlHelper htmlHelper, Object parameters)
   at Oqtane.Pages.Pages__Host.<ExecuteAsync>b__10_1() in C:\Siliqon\Oqtane\sbwalker.oqtane.framework\Oqtane.Server\Pages\_Host.cshtml:line 17
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
   at Oqtane.Pages.Pages__Host.ExecuteAsync()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|21_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()

### Expected behavior
Application should run without exception

**Comment by SteveSandersonMS** [comment]
This happens because `DefaultCircuitFactory` first gets the `AuthenticationStateProvider` and initializes it, then it gets the `IUriHelper` and initializes it. If we did that in the opposite order, this would work OK.

However, doing it in the opposite order would then lead to an opposite problem, which is that if someone configures a custom `IUriHelper` whose service provider works by fetching an `AuthenticationStateProvider` which it relies upon to be initialized already, then that would fail in the same way.

Basically, one of them has to go first, and that one can't depend on the other one already being initialized.

Possible ways we could avoid this ordering dependency:

 * We could put all the "initializable" state on some internal framework service "X" that `DefaultCircuitFactory` always initializes before fetching any publicly-configurable services. Then our default implementations of those publicly-configurable services rely on X.
 * We could try to avoid the whole `service.Initialize(...)` pattern in `DefaultCircuitFactory` entirely. Instead, `DefaultCircuitFactory` could attach whatever information will be needed to the scope as a custom options provider, and our services would get that information from there.

Come to think of it, the second option there is basically just a restatement of the first option. Regardless of the implementation details, we should do something like this, but I don't think it's urgent.

@sbwalker As a workaround for now, in your `ServerAuthenticationStateProvider`, don't depend directly on `HttpClient` but instead just take in an `IServiceProvider`. Then obtain the `HttpClient` lazily at the time you want to use it, instead of during the constructor (and optionally cache it at that point).

**Comment by rynowak** [comment]
> However, doing it in the opposite order would then lead to an opposite problem, which is that if someone configures a custom IUriHelper

Is this something that's actually important that we account for? 

It's valuable to build good abstractions and code our components to those abstractions. But, I don't put a lot of stock in making primitives like this replaceable *within* a hosting model.

**Comment by sbwalker** [comment]
I was able to modify the code as Steve suggested and it works:

       public override async Task<AuthenticationState> GetAuthenticationStateAsync()
        {
            // hack: create a new HttpClient rather than relying on the registered service as the AuthenticationStateProvider is initialized prior to IUriHelper ( https://github.com/aspnet/AspNetCore/issues/11867 )
            HttpClient http = new HttpClient();
            Uri uri = new Uri(urihelper.GetAbsoluteUri());
            string apiurl = uri.Scheme + "://" + uri.Authority + "/~/api/User/authenticate";
            User user = await http.GetJsonAsync<User>(apiurl);
            var identity = user.IsAuthenticated
                ? new ClaimsIdentity(new[] { new Claim(ClaimTypes.Name, user.Username) }, "serverauth")
                : new ClaimsIdentity();
            return new AuthenticationState(new ClaimsPrincipal(identity));
        }

**Comment by jan-johansson-mr** [comment]
I just run into the same issue, where I want HttpClient and NavigationManager at the same time (scope). I guess I need some solution. I'll think about the suggestion by @SteveSandersonMS in this thread. As a side note, the working solution by @sbwalker unfortunately leaks resources into system space. The whole idea of HttpClientFactory is to do [housekeeping](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests) of tcp/ip resources to avoid running out of the said resources at high loads.

**Comment by sbwalker** [comment]
@jan-johansson-mr good point! I had been meaning to revisit this item as the approach I took at the time was a quick workaround so that I could continue with development of my app. The lazy instantiation approach using IServiceProvider suggested by @SteveSandersonMS would be the better option until a better solution materializes in Blazor - not sure if I understand the scenario of someone overriding IUrlHelper (now INavigationManager).

**Comment by sbwalker** [comment]
@jan-johansson-mr couldn't the resource leak be simply resolved by adding a using statement for the HttpClient so that it is disposed properly?

        public override async Task<AuthenticationState> GetAuthenticationStateAsync()
        {
            using (var http = new HttpClient())
            {
                Uri uri = new Uri(urihelper.GetAbsoluteUri());
                string apiurl = uri.Scheme + "://" + uri.Authority + "/~/api/User/authenticate";
                User user = await http.GetJsonAsync<User>(apiurl);
                var identity = user.IsAuthenticated
                    ? new ClaimsIdentity(new[] { new Claim(ClaimTypes.Name, user.Username) }, "serverauth")
                    : new ClaimsIdentity();
                return new AuthenticationState(new ClaimsPrincipal(identity));
            }
        }

**Comment by jan-johansson-mr** [comment]
It may appear to fix the issue, but please have a look at this very nice [article](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong) giving some insight to what is going on under the hood (this time around, how TCP/IP layer was implemented way back in time, and still very relevant today) :-)

**Comment by sbwalker** [comment]
Ahh yes... thank you for the reminder about the behavior of HttpClient. Using IServiceProvider does seem to work and should not suffer from the limitations of the other solutions in this thread.

    public override async Task<AuthenticationState> GetAuthenticationStateAsync()
    {
            var http = provider.GetRequiredService<HttpClient>();
            Uri uri = new Uri(urihelper.GetAbsoluteUri());
            string apiurl = uri.Scheme + "://" + uri.Authority + "/~/api/User/authenticate";
            User user = await http.GetJsonAsync<User>(apiurl);
            var identity = user.IsAuthenticated
                ? new ClaimsIdentity(new[] { new Claim(ClaimTypes.Name, user.Username) }, "serverauth")
                : new ClaimsIdentity();
            return new AuthenticationState(new ClaimsPrincipal(identity));
    }

**Comment by jan-johansson-mr** [comment]
Like so :-)

What do you think about the following? I have a choice to make, either go Fort Knox with authentication by affine authentication tied to the blazor circuit and if page is refreshed (the circuit breaks) then have the user login again. Or go feature wise and create an affine session with secured cookie and then let the auth flow between circuits. Or the third choice, go affine with an already out-of-the-box auth flow available (see below).

I'm on the fence on this one, I know that users want easy and secure, but it's hard to do both!

What I like about the Fort Know model is that circuit is pin downed to one environment (even to one browser tab).

But if I flip the coin and go for convenience and that (in this case) I've integrated with [IdentityServer](https://identityserver.io/) 4, I also know that IdentityServer already have an affine auth flow available via secure cookie, e.g. if a new round trip to IdentityServer is forced and the user has a grant, it simply returns whatever is needed to proceed with the signin flow anyway, resulting in new Id and Access tokens without a login prompt. Or with less words, the user would still have a nice experience if circuit breaks, but with the cost of an additional round trip. The other cost is that now the auth is browser wide (e.g. if I duplicate tab, then the same auth is on the second tab). However, and this is fun, if I break the user login on the IdentityServer side, and the user refresh the browser, then the access has been revoked (but on the refreshed tab though)! This is a nice feature, I think :-)

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
