### ISSUE TITLE
[SignalR] Cannot access a disposed object.  Object name: 'SocketsHttpHandler'.

### ISSUE THREAD

**Issue by captmomo** [dotnet/aspnetcore#12080]
### Describe the bug

I am trying to implement an auto-reconnect for a SignalR client.

Here is my code

Method to construct the connection:
```
        private void ConstructConnection()
        {
            _logger.LogInformation("Constructing Hub connection.");
 
            HttpClientHandler handler = new HttpClientHandler
            {
                ClientCertificateOptions = ClientCertificateOption.Manual,
                ServerCertificateCustomValidationCallback = (httpRequestMessage, cert, cetChain, policyErrors) => { return true; }
            };

            _connection = new HubConnectionBuilder()
                .WithUrl(_hubRoot, options =>
                {
                    options.HttpMessageHandlerFactory = _ => handler;
                    options.WebSocketConfiguration = sockets =>
                    {
                        sockets.RemoteCertificateValidationCallback = new RemoteCertificateValidationCallback((sender, certificate, chain, policyErrors) => { return true; });
                    };
                })
                .Build();
            _connection.KeepAliveInterval = new TimeSpan(1);
            _connection.ServerTimeout = new TimeSpan(1, 0, 0);
            _connection.On(Strings.ReaderEvents.CheckConnection, () => _ = CheckConnection());
            _connection.On(Strings.ReaderEvents.Scan, () => _ = ScanTagAsync());
        }

```        

```
public async Task StartHubConnection(CancellationToken cancellationToken)
        {
            int currentRetry = 0;
            ConstructConnection();

            while (!HubConnected)
            {
                try
                {
                    await _connection.StartAsync(cancellationToken);
                    _connection.Closed += _connection_Closed;
                    _logger.LogInformation($"{_machineName} connected to Hub.");
                    _connection.InvokeAsync("JoinGroup", _machineName);
                    await CheckConnection();
                    
                    HubConnected = true;
                }
                catch (Exception ex)
                {
                    _logger.LogCritical($"There was an error starting the connection:{ex.InnerException.ToString()}");

                    await Task.Delay(delay * currentRetry);
                    currentRetry++;
                    if (currentRetry > this.retryCount)
                    {
                        _logger.LogCritical("Max reconnect attempts reached. Shutting down");
                        StopClientAsync();
                        break;
                    }
                }
            }
        }

```
My method to reconnect

```
        private async Task _connection_Closed(Exception arg)
        {
            if (arg != null)
            {
                _logger.LogCritical($"Hub connection lost. Exception: {arg.Message}");
            }
            HubConnected = false;

            _connection.Closed -= _connection_Closed;
            //remove handlers in case this is due to reconnection
            _connection.Remove(Strings.ReaderEvents.CheckConnection);
            _connection.Remove(Strings.ReaderEvents.Scan);
            await _connection.StopAsync().ConfigureAwait(false);
            await _connection.DisposeAysnc();


            using (CancellationTokenSource cts = new CancellationTokenSource())
            {
                _logger.LogInformation($"Trying re-establish Hub Connection.");
                await StartHubConnection(cts.Token).ConfigureAwait(false);
            }


        }
```
Sometimes I get the following exception when attempting to reconnect:

```
 There was an error opening the connection:System.ObjectDisposedException: Cannot access a disposed object.
      Object name: 'SocketsHttpHandler'.
         at System.Net.Http.SocketsHttpHandler.CheckDisposed()
         at System.Net.Http.SocketsHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Http.Connections.Client.Internal.AccessTokenHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Http.Connections.Client.Internal.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
         at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync(Uri url, HttpClient httpClient, ILogger logger)
         at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.GetNegotiationResponseAsync(Uri uri)
         at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat)
         at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat)
         at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.SignalR.Client.HttpConnectionFactory.ConnectAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.SignalR.Client.HttpConnectionFactory.ConnectAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
         at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
```

### Expected behavior
The reconnection works most of the time, however I get the above exception sometimes. Any idea what I am doing wrong?

I've tried this without calling DisposeAysnc and still get the same exception.

**Comment by BrennanConroy** [comment]
I'm not exactly sure how you're getting that error but it might be a good idea to clean up your reconnection logic which might make the problem go away.

You only need to use the builder once unless you want to change options on the connection every retry. The connection is reusable provided you don't dispose it. You also shouldn't need to remove the handlers.

A semi-simplified retry logic would look like:
```csharp
// called once
void CreateConnection()
{
    _connection = new HubConnectionBuilder()
                .WithUrl(_hubRoot, options =>
                {
                    // stuff
                });
}

async Task StartHubConnection(CancellationToken cancellationToken)
{
    while (!HubConnected)
    {
        try
        {
            await _connection.StartAsync(cancellationToken);
        }
        catch (Exception ex)
        {
            // todo: delay logic
            continue;
        }

        _connection.Closed += _connection_Closed;
        _logger.LogInformation($"{_machineName} connected to Hub.");
        try
        {
            _connection.InvokeAsync("JoinGroup", _machineName);
            await CheckConnection();
            HubConnected = true;
        }
        catch (Exception ex)
        {
            // close callback will invoke this method again, so we don't want to have multiple loops running at the same time
            return;
        }
    }
}

async Task _connection_Closed(Exception arg)
{
    HubConnected = false;

    _connection.Closed -= _connection_Closed;

    using (CancellationTokenSource cts = new CancellationTokenSource())
    {
        await StartHubConnection(cts.Token).ConfigureAwait(false);
    }
}
```

And if possible you should try out the new automatic reconnect added in 3.0! https://docs.microsoft.com/aspnet/core/signalr/dotnet-client?view=aspnetcore-3.0#automatically-reconnect

**Comment by captmomo** [comment]
Hi

Thanks,

I’ve tried removing the multiple calls to the builder but still get the
same error.

I’ll try not removing the handlers.

Thank you for your help.

**Comment by captmomo** [comment]
```
      public async Task StartHubConnection(CancellationToken cancellationToken)
        {
            int currentRetry = 0;


            while (!HubConnected)
            {
                try
                {
                    await _connection.StartAsync(cancellationToken);
                }
                catch (Exception ex)
                {
                    _logger.LogCritical($"There was an error starting the connection:{ex.StackTrace}");
                    _logger.LogError($"{ex.GetBaseException().Message}");
                    HubConnected = false;
                    await Task.Delay(delay);
                    _logger.LogInformation($"Current retry count: {currentRetry}");
                    currentRetry++;
                    if (currentRetry > this.retryCount)
                    {
                        _logger.LogCritical("Max reconnect attempts reached. Shutting down");
                        StopClientAsync();
                        break;
                    }
                    continue;
                }
                _connection.Closed += _connection_Closed;
                _logger.LogInformation($"{_machineName} connected to Hub.");
                try
                {
                 
                    _connection.InvokeAsync("JoinGroup", _machineName);
                    await CheckConnection();
                    
                    HubConnected = true;
                }
                catch (Exception ex)
                {
                    return;
                }
            }
        }
```

**Comment by BrennanConroy** [comment]
Ah, that makes sense. I didn't notice the handler not being updated :D
Good catch
