### ISSUE TITLE
CI Error StreamBackedTestConnection Kestrel/test/InMemory.FunctionalTests/ResponseTests 

### ISSUE THREAD

**Issue by benaadams** [dotnet/aspnetcore#12401]
```
Error message
Assert.Equal() Failure
↓ (pos 0)
Expected: 
Actual: HTTP/1.1 200 OK\r\nDate: Fri, 23 Oct 1553 1···
↑ (pos 0)
```
```
Stack trace
   at Microsoft.AspNetCore.Testing.StreamBackedTestConnection.ReceiveEnd(String[] lines) in /_/src/Servers/Kestrel/shared/test/StreamBackedTestConnection.cs:line 134
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.ResponseTests.AppAbortViaIConnectionLifetimeFeatureIsLogged() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/ResponseTests.cs:line 2569
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.ResponseTests.AppAbortViaIConnectionLifetimeFeatureIsLogged() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/ResponseTests.cs:line 2570
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by davidfowl** [comment]
This test seems to be racy since my bedrock changes. Originally it relied on inline scheduling but now it's a bit more tricky to ensure that the abort has been observed before the response gets sent.

**Comment by BrennanConroy** [comment]
Test marked flaky https://github.com/aspnet/AspNetCore/blob/4a7bf75e89e3dfe7264a641ed041f50788d28d20/src/Servers/Kestrel/test/InMemory.FunctionalTests/ResponseTests.cs#L2544

**Comment by anurse** [comment]
Unquarantining due to long passing interval.
