### ISSUE TITLE
w3wp process terminated due to an unhandled exception in crypt32.dll

### ISSUE THREAD

**Issue by Jens-G** [dotnet/aspnetcore#13706]
### Describe the bug
```
Application: w3wp.exe
CoreCLR Version: 4.6.27521.2
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FFCFD002179
Stack:
```

followed by:

```
Name der fehlerhaften Anwendung: w3wp.exe, Version: 8.5.9600.16384, Zeitstempel: 0x5215df96
Name des fehlerhaften Moduls: CRYPT32.dll, Version: 6.3.9600.18653, Zeitstempel: 0x58de62bb
Ausnahmecode: 0xc0000005
Fehleroffset: 0x0000000000062179
ID des fehlerhaften Prozesses: 0x9d8
Startzeit der fehlerhaften Anwendung: 0x01d562f085ccbf8f
Pfad der fehlerhaften Anwendung: c:\windows\system32\inetsrv\w3wp.exe
Pfad des fehlerhaften Moduls: C:\Windows\system32\CRYPT32.dll
Berichtskennung: 4123f755-cef1-11e9-816a-005056936920
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 

```

### To Reproduce
Run ASP.NET core application and do web requests against it. Unfortunately we have no further information how and why this happened. 

### Expected behavior
It should not crash.

### Screenshots
none

### Additional context
Stack trace we extracted from the minidump file:

```
crypt32.dll!CryptMsgClose()
crypt32.dll!FreeCtlElement()
crypt32.dll!FreeContextElement()
crypt32.dll!ReleaseContextElement()
crypt32.dll!CertFreeCRLContext()
crypt32.dll!CCertChainEngine::Resync()
crypt32.dll!CCertChainEngine::CreateChainContextFromPathGraph()
crypt32.dll!CCertChainEngine::GetChainContext()
crypt32.dll!CertGetCertificateChain()
webio.dll!WapSslVerifyServerCert()
webio.dll!WapSslVerifyNewServerCert()
webio.dll!WxSaveExceptionFilter(struct _EXCEPTION_POINTERS const *)
webio.dll!WapSslQueryAndVerifySslConnectionInfo()
webio.dll!WapSslPerformHandshake()
webio.dll!WapSslProcessReceiverData()
webio.dll!WaSslProcessReceiver()
webio.dll!WapSslReceiveCompletionCallback()
webio.dll!WapTcpReceiveCompletionRoutine()
webio.dll!WapTcpThreadPoolCompletionRoutine()
webio.dll!WapTpIoCompletionRoutine()
KERNELBASE.dll!BasepTpIoCallback()
ntdll.dll!TppIopExecuteCallback()
ntdll.dll!TppWorkerThread()
kernel32.dll!BaseThreadInitThunk()
ntdll.dll!RtlUserThreadStart()

```

**Comment by shirhatti** [comment]
@Jens-G Do you have any additional information in the event log?

@bariscaglar Any ideas what's happening here?

**Comment by bariscaglar** [comment]
I don't know but I can see no IIS binaries on the stack. Ivan might have an idea what might be causing this.

**Comment by Jens-G** [comment]
I could provide the dump files, etc:

- memory.hdmp
- minidump.mdmp
- Report.wer
- WER9917.tmp.appcompat.txt
- WER9A41.tmp.WERInternalMetadata.xml

**Comment by Jens-G** [comment]
It may not be ASP, I really can't tell that. I can only tell it happened in that context. And it is not application code either. There are not many moving parts left besides NETCore itself. How do we proceeed? Can I help somehow?

**Comment by bariscaglar** [comment]
@shirhatti please see my comment above.

**Comment by diakopter** [comment]
informal pingback from https://krebsonsecurity.com/2020/01/cryptic-rumblings-ahead-of-first-2020-patch-tuesday/ referencing crypt32.dll vulnerability

**Comment by mniak** [comment]
Hi, I also found the same behavior but with another exception.

```
Application: w3wp.exe
CoreCLR Version: 4.6.27317.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Data.SqlClient.SqlException: Violation of PRIMARY KEY constraint 'PK_Table'. Cannot insert duplicate key in object 'dbo.Table'. The duplicate key value is (*******).
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
```
