### ISSUE TITLE
SignalR return HttpResponseMessage from SignalR hub to invokecoreasync call from signalr client

### ISSUE THREAD

**Issue by sylvainb31** [dotnet/aspnetcore#14363]
### Describe the bug
When trying to return a HttpResponseMessage from SignalR hub to invokecoreasync call from signalr client, the invokecoreasync method throws an exception : 

`{System.IO.InvalidDataException: Connection terminated while reading a message.
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.ReceiveLoop(ConnectionState connectionState)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.InvokeCoreAsync[TResult](HubConnection hubConnection, String methodName, Object[] args, CancellationToken cancellationToken)
   at SecretariatMedical.Services.WebService.LogInAndGetToken(LoginViewModel loginViewModel) in C:\Users\SylvainB\Desktop\aspnetcore\Projet Clinique Charles\SecretariatMedical\SecretariatMedical\Services\WebService.cs:line 106}`

Here is the connection build : 

`connection = new HubConnectionBuilder()
            .WithUrl("https://localhost:44380/testHub")
            .Build();`

Here is the signalr client call :

`await connection.StartAsync();
                    
HttpResponseMessage responseSignalR = await connection.InvokeCoreAsync<HttpResponseMessage>("LogInAndGetToken", new object[] { loginViewModel });`

Here is the code on the signalr Hub :

`string apiUrl = "api/authenticationapi/gettoken";
HttpResponseMessage response;
using (HttpClient client = new HttpClient())
{
    client.BaseAddress = new Uri("https://localhost:44379");
    client.DefaultRequestHeaders.Accept.Clear();
    client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
    response = await client.PostAsJsonAsync(apiUrl, loginViewModel);
}
return response;`

### To Reproduce
1. Using Asp.Net Core 2.2
2. Either on the same or on two different web app, call a method on the signalr hub using InvokeCoreAsync and wait for a HttpResponseMessage result to arrive.
3. On the signalr hub, return a HttpResponseMessage with a Content not null
4. The following errors appears depending on the HttpResponseMessage configuration :
a) 
```
{System.IO.InvalidDataException: Connection terminated while reading a message.
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.ReceiveLoop(ConnectionState connectionState)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.InvokeCoreAsync[TResult](HubConnection hubConnection, String methodName, Object[] args, CancellationToken cancellationToken)
   at SecretariatMedical.Services.WebService.LogInAndGetToken(LoginViewModel loginViewModel) in C:\Users\SylvainB\Desktop\aspnetcore\Projet Clinique Charles\SecretariatMedical\SecretariatMedical\Services\WebService.cs:line 106}
```
b)
```
Microsoft.AspNetCore.SignalR.HubConnectionContext:Error: Failed writing message. Aborting connection.

Newtonsoft.Json.JsonSerializationException: Error getting value from 'Preamble' on 'System.Text.UTF8Encoding'. ---> System.InvalidProgramException: Cannot create boxed ByRef-like values.
   at System.Runtime.CompilerServices.RuntimeHelpers._CompileMethod(IRuntimeMethodInfo method)
   at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType, Object target)
   at System.Linq.Expressions.Compiler.LambdaCompiler.CreateDelegate()
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
   at System.Linq.Expressions.LambdaExpression.Compile()
   at Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateGet[T](PropertyInfo propertyInfo)
   at Newtonsoft.Json.Utilities.ReflectionDelegateFactory.CreateGet[T](MemberInfo memberInfo)
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteCompletionMessage(CompletionMessage message, JsonTextWriter writer)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteMessageCore(HubMessage message, IBufferWriter`1 stream)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteMessage(HubMessage message, IBufferWriter`1 output)
   at Microsoft.AspNetCore.SignalR.HubConnectionContext.WriteCore(HubMessage message)`
```

### Expected behavior
The expected behavior would be to be able to return a HttpResponseMessage with a Content set to the InvokeCoreAsync call without any exception.

### Additional context
The problem seems to be coming from the "Content" property of the HttpResponseMessage.
As this property is an interface, SignalR seems to have difficulties transporting it.

**Comment by davidfowl** [comment]
You can't return an `HttpResponseMessage` from a Hub method. You can return a serializable POCO object though.

**Comment by sylvainb31** [comment]
Don't you think it's possible to return it by specifying a custom JsonConverter to make sure the deserialization works ? Like making sure that the HttpContent is instantiated with the correct class during deserialization ?

**Comment by BrennanConroy** [comment]
You can try that if you'd like. We allow you to provide custom JsonConverters. However, it sounds like a very bad idea to try this, `HttpResponseMessage` is a very hefty object with many properties that aren't needed by the client. You should instead pull out the bits you want and send those to the client.

By default SignalR does not support returning an `HttpResponseMessage`.

**Comment by davidfowl** [comment]
> Don't you think it's possible to return it by specifying a custom JsonConverter to make sure the deserialization works ? Like making sure that the HttpContent is instantiated with the correct class during deserialization ?

No it's actually quite strange to serialize the `HttpResponseMessage` over the websocket channel. If you want to do HTTP then you should use an HTTP pipeline.
