### ISSUE TITLE
ASP.NET Core 3.0: NullReferenceException in HttpContext.RequestAborted

### ISSUE THREAD

**Issue by sepehr1014** [dotnet/aspnetcore#17085]
We have a middleware that accepts WebSocket requests and receives messages while `(!context.RequestAborted.IsCancellationRequested && (socket.State == WebSocketState.Open || socket.State == WebSocketState.Connecting))`. After migrating from 2.2 to 3.0 we're getting the exception below.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_RequestAborted()
   at Pasaj.MessagingMiddleware.Receive(WebSocket socket, HttpContext context, String sessionId, Int32 clientVersion) in C:\Web\Patogh\Patogh\Hubs\MessagingMiddleware.cs:line 103
   at Pasaj.MessagingMiddleware.InvokeAsync(HttpContext context) in C:\Web\Patogh\Patogh\Hubs\MessagingMiddleware.cs:line 96
   at Pasaj.MessagingMiddleware.InvokeAsync(HttpContext context) in C:\Web\Patogh\Patogh\Hubs\MessagingMiddleware.cs:line 96
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Pasaj.HttpExceptionMiddleware.Invoke(HttpContext context) in C:\Web\Patogh\Patogh\Helpers\HttpExceptionMiddleware.cs:line 31
   at CoreProfiler.Web.CoreProfilerMiddleware.Invoke(HttpContext context)
   at AspNetCoreRateLimit.RateLimitMiddleware`1.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

This doesn't happen every time, maybe 1 in 10,000. But since we're dealing with hundreds of messages a second, we get this exception every other minute or so.

### Further technical details
- ASP.NET Core 3.0
- IIS on Windows Server 2016

**Comment by javiercn** [comment]
@sepehr1014 thanks for contacting us.

@Tratcher can you take a look? Not sure if this is hosting or middleware, re-label it as you see fit.

**Comment by Tratcher** [comment]
The most common cause for issues like this is concurrently accessing the HttpContext on multiple threads. Do you do any multi-threading per request?

Unrelated question: Why do you have two StatusCodePagesMiddleware middleware? And two MessagingMiddleware?

**Comment by davidfowl** [comment]
Can you show the websocket accept loop

**Comment by sepehr1014** [comment]
@Tratcher Yes. We're passing the context to the send thread which is checking its cancellation token.

There shouldn't be two instances of those middlewares. I thought that's just a bug in the creation of the stacktrace. We're adding our middleware only once in Startup Configure using `app.UseMiddleware<MessagingMiddleware>();` and we're definitely not adding StatusCodePagesMiddleware manually.

**Comment by Tratcher** [comment]
> @Tratcher Yes. We're passing the context to the send thread which is checking its cancellation token.

Please show how this is used. HttpContext is not designed to be accessed on multiple threads concurrently.

**Comment by sepehr1014** [comment]
@davidfowl Yes, we're passing it to another thread which is responsible for sending messages to the client. After sending is complete it may call `context.Abort();` but I don't see why reading HttpContext.RequestAborted should throw an exception in this scenario.
Here's the reading loop:

```
public async Task InvokeAsync(HttpContext context)
{
    if (!context.WebSockets.IsWebSocketRequest) { await _next.Invoke(context); return; }
    if (!context.User.Identity.IsAuthenticated) { context.Response.StatusCode = 401; return; }

    var clientVersion = Int32.Parse(context.Request.Headers.First(h => h.Key.ToLower() == "x-client-version").Value.First());
    if (clientVersion < 270)
    {
        context.Response.StatusCode = 400;
        return;
    }

    var currentId = IdentityHelper.GetUserId(context.User);
    var clientId = context.Request.Query["clientid"].Single();
    var requestId = context.Request.Query["rid"].Single();
    var cleanStart = context.Request.Query["cs"].SingleOrDefault() == "1";
    var sessionId = $"{currentId}:{clientId}";

    var socket = await context.WebSockets.AcceptWebSocketAsync();

    WSSessionRep currentSession = null;
    try
    {
        currentSession = await WSMan.ConnectSession(currentId, clientId, requestId, socket, clientVersion, cleanStart, _logger);
    }
    catch (KeyNotFoundException) // Deleted user
    {
        return;
    }

    var taskRequests = Task.Factory.StartNew(async () => await currentSession.SendWhileConnected(socket, _logger, context),
        TaskCreationOptions.LongRunning);

    try
    {
        await Receive(socket, context, sessionId, clientVersion);
    }
    finally
    {
        await WSMan.DisconnectSession(currentSession, socket, _logger);
    }
        }

        private async Task Receive(WebSocket socket, HttpContext context, string sessionId, int clientVersion)
        {
    var fullResult = new byte[0];
    var buffer = new byte[1024 * 16];

    while (/*!context.RequestAborted.IsCancellationRequested && */(socket.State == WebSocketState.Open || socket.State == WebSocketState.Connecting))
    {
        try
        {
            if (context.RequestAborted.IsCancellationRequested)
        break;
        }
        catch (NullReferenceException) // .NET Core Bug
        {
            break;
        }

        ValueWebSocketReceiveResult result;
        try
        {
            result = await socket.ReceiveAsync(new Memory<byte>(buffer), context.RequestAborted);
        }
        catch (OperationCanceledException)
        {
            break;
        }
        catch (WebSocketException ex) when (ex.WebSocketErrorCode == WebSocketError.ConnectionClosedPrematurely)
        {
            break;
        }
        if (result.MessageType == WebSocketMessageType.Close)
            break;

        var temp = fullResult;
        fullResult = new byte[fullResult.Length + result.Count];
        Buffer.BlockCopy(temp, 0, fullResult, 0, temp.Length);
        Buffer.BlockCopy(buffer, 0, fullResult, temp.Length, result.Count);

        if (result.EndOfMessage)
        {
            long requestId = 0;
            MessagingReturnModel req = null;
            try
            {
        var json = Encoding.UTF8.GetString(fullResult);

        req = JsonConvert.DeserializeObject<MessagingReturnModel>(json);
        requestId = req.Id;

        await ProcessMessage(context, _env, httpClientFactory, _logger, sessionId, req);
            }
            catch (KeyNotFoundException) // Deleted session
            {
        var err = new MessagingErrorObject { Parameters = new ErrorObject { ErrorCode = HttpStatusCode.Unauthorized } };
        await WSSessionRep.SendAsync(socket, err.ToJSON(), _logger, context.RequestAborted);
            }
            catch (Exception ex)
            {
        //_logger.LogError ...
        var err = new MessagingErrorObject
        {
            Id = requestId,
            Parameters = new ErrorObject { ErrorCode = HttpStatusCode.InternalServerError, Message = "خطا در سرور" }
        };
        await WSMan.GetSession(sessionId).EnqueueMessage(null, err, false, WSHelper.EXPIRY_DIRECT_RESPONSE);
            }
            finally
            {
        fullResult = new byte[0];
            }
        }

        var tokenExpiry = IdentityHelper.GetTokenExpiry(context.User);
        if (tokenExpiry < DateTime.Now.AddMinutes(-5))
        {
            await socket.CloseAsync(WebSocketCloseStatus.PolicyViolation, "token_expired", new CancellationTokenSource(TimeSpan.FromSeconds(5)).Token);
            break;
        }
        else if (tokenExpiry < DateTime.Now && clientVersion > 301)
        {
            var err = new MessagingErrorObject { Parameters = new ErrorObject { ErrorCode = HttpStatusCode.Unauthorized } };
            await WSMan.GetSession(sessionId).EnqueueMessage(null, err, false, WSHelper.EXPIRY_DIRECT_RESPONSE);
        }
    }

    context.Abort();
        }
```

**Comment by sepehr1014** [comment]
@Tratcher Here's our sending procedure:

```
public async Task SendWhileConnected(WebSocket inputSocket, ILogger logger, HttpContext context)
        {
            var retries = 20;
            while (!context.RequestAborted.IsCancellationRequested && Socket == inputSocket && (Socket.State == WebSocketState.Open || Socket.State == WebSocketState.Connecting))
            {
                WSMessageRep message = null;
                try
                {
                    await CheckUpdateFinished();

					// message = ...
                }
                catch (InvalidOperationException ex) when (ex.Message.Contains("Collection was modified; enumeration operation may not execute"))
                {
                    // Try again in loop
                    continue;
                }
                catch (Exception ex)
                {
                    logger.LogError(ex, null);
                    continue;
                }

                if (message != null)
                {
                    try
                    {
                        try
                        {
                            if (message.ExpirationDate == null || message.ExpirationDate > DateTime.Now)
                                await SendAsync(Socket, message.PayloadString, logger, context.RequestAborted);
                        }
                        catch (Exception ex)
                        {
                            if (retries-- < 1 && !ex.Message.Contains("The remote party closed the WebSocket connection without completing the close handshake"))
                                logger.LogError(ex, null);

                            if (message.TrackingCode != 0)
                            {
                                // Just save possibly-modified payload
                                await semaphorePersistentMessages.WaitAsync();
                                try
                                {
                                    // ...
                                }
                                finally
                                {
                                    semaphorePersistentMessages.Release();
                                }
                            }

                            // Retry sending after a short delay
                            await Task.Delay(100);
                            continue;
                        }

                        if (message.TrackingCode != 0)
                            await SaveMessageRetry(message);
                        else
                            lock (lockTransientMessages)
                                TransientMessages.Remove(message);

                        retries = 20;
                    }
                    catch (Exception ex)
                    {
                        logger.LogError(ex, null);
                    }
                }
                else
                    await Task.Delay(20);
            }

            context.Abort();
        }
```

**Comment by Tratcher** [comment]
> but I don't see why reading HttpContext.RequestAborted should throw an exception in this scenario.

I know it's not intuitive, but even property getters are not thread safe. RequestAborted has lazy side effects to create the cancellation token. Read the RequestAborted property before the threads fork and don't even pass HttpContext into those methods.

**Comment by davidfowl** [comment]
> I know it's not intuitive, but even property getters are not thread safe. RequestAborted has lazy side effects to create the cancellation token. Read the RequestAborted property before the threads fork and don't even pass HttpContext into those methods so you're not tempted to use it again.

You don't need to look at `HttpContext.RequestAborted` at all but it shouldn't null ref here, that seems like a bug on our part. I would follow @Tratcher 's advice here and not pass the HttpContext to multiple threads. Get the data you need from the HttpContext before starting the websocket loop.

PS: This code has lots of other bugs and issues that should be fixed. I can help with that but I don't want to deter from the original issue.

**Comment by sepehr1014** [comment]
@Tratcher I will fix that.

**Comment by sepehr1014** [comment]
@davidfowl I would love your input. You could contact me via sepehr1014 at gmail.com.

**Comment by anurse** [comment]
It seems reasonable to avoid the nullref if possible.

**Comment by davidfowl** [comment]
I'm pretty sure I understand why null refs happen now when the HttpContext is accessed concurrently. It comes down to the internal struct we use to store common feature references being cleared out when the feature collection changes. This happens here https://github.com/dotnet/aspnetcore/blob/b806844373440a538192181652d466b621a14494/src/Extensions/Features/src/FeatureReferences.cs#L117.

**Comment by davidfowl** [comment]
@sepehr1014 if you can still reproduce the issue, see if this guide helps capture a process dump https://github.com/microsoft/ApplicationInsights-dotnet/issues/1524#issuecomment-1146848272

**Comment by sepehr1014** [comment]
@davidfowl Thank you for following up on this issue. But we haven't had this problem since upgrading to .NET 5.0 and we're currently using 6.0.
