### ISSUE TITLE
Multiple model binders depending on the content type

### ISSUE THREAD

**Issue by marcuslindblom** [dotnet/aspnetcore#17303]
is it possible to do like this. The goal here is to be able to use the same `PUT` endpoint for `JSON` data and adding a file. Maybe this is an anti pattern, if so please say so :)

Thanks

```c#
[Consumes("application/json", "multipart/form-data")]
public async Task<IActionResult> Put(string id, [FromForm] IFormFile icon, [FromBody] UpdateWorkspaceRequest request) {
}
```

Sending two different content types like this:

```js
    fetch('/my-endpoint', {
      method: 'PUT',
      body: JSON.stringify({ name: payload.name }),
      credentials: 'include',
      headers: {
        accept: 'application/json',
        'content-type': 'application/json'
      }
    })
```

and:

```js
    const formData = new FormData();
    formData.append('icon', e.target.files[0]);
    fetch('/my-endpoint', {
      method: 'PUT',
      body: formData,
      credentials: 'include',
      headers: {
        accept: 'application/json'        
      }
    })
```

**Comment by rynowak** [comment]
I think you'll be a lot more successful just making this two action methods. You're not ever going to have a single request send *both* a JSON body and file right?

They can have the same routing info - `[Consumes(...)]` will select between them.

**Comment by marcuslindblom** [comment]
@rynowak Ok, I see. If I add a second action like this.

```c#
[HttpPut("{id}")]
[Consumes("multipart/form-data")]
public async Task<IActionResult> Put(string id, [FromForm] IFormFile icon)
{ }
```
And a second one like this:

```c#
[HttpPut("{id}")]
[Consumes("application/json")]
public async Task<IActionResult> Put(string id, [FromBody] UpdateWorkspaceRequest request)
{ }
```
The code compiles but  I get the following error.

```
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches: 

Brickpile.Api.Controllers.WorkspaceController.Put (Brickpile.Api)
Brickpile.Api.Controllers.WorkspaceController.Put (Brickpile.Api)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.SelectAsync(HttpContext httpContext, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Connection: keep-alive
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,sv;q=0.8
Host: localhost:5001
Referer: https://localhost:5003/settings/general
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
DNT: 1
Origin: https://localhost:5003
Access-Control-Request-Method: PUT
Access-Control-Request-Headers: content-type
sec-ch-ua: Google Chrome 78
Sec-Fetch-Dest: empty
Sec-Fetch-Site: same-site
Sec-Fetch-Mode: cors
```

Isn't it possible to have the same routing info?

**Comment by rynowak** [comment]
I tried adding your two methods to a new project it worked for me.

What does your HTTP request look like?
Do you have a more complete sample that I can try running?

**Comment by marcuslindblom** [comment]
@rynowak This is how my file upload request look look like:
```
curl 'https://localhost:5001/workspaces/1' -X OPTIONS -H 'Connection: keep-alive' -H 'sec-ch-ua: Google Chrome 78' -H 'Access-Control-Request-Method: PUT' -H 'Origin: https://localhost:5003' -H 'Sec-Fetch-Dest: empty' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36' -H 'DNT: 1' -H 'Accept: */*' -H 'Sec-Fetch-Site: same-site' -H 'Sec-Fetch-Mode: cors' -H 'Referer: https://localhost:5003/settings/general' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9,sv;q=0.8' --compressed```

and this is how my json request look like:

```
curl 'https://localhost:5001/workspaces/1' -X OPTIONS -H 'Connection: keep-alive' -H 'sec-ch-ua: Google Chrome 78' -H 'Access-Control-Request-Method: PUT' -H 'Origin: https://localhost:5003' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36' -H 'Sec-Fetch-Dest: empty' -H 'DNT: 1' -H 'Access-Control-Request-Headers: content-type' -H 'Accept: */*' -H 'Sec-Fetch-Site: same-site' -H 'Sec-Fetch-Mode: cors' -H 'Referer: https://localhost:5003/settings/general' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9,sv;q=0.8' --compressed
```

**Comment by rynowak** [comment]
AH, this is CORS, ok that makes a little bit more sense.

**Comment by rynowak** [comment]
This may be a bug.

**Comment by marcuslindblom** [comment]
Ok, let me know what you find out if you investigate.

**Comment by rynowak** [comment]
BTW if you need a workaround to get past this, it will probably start working if you add `[EnableCors]` to each of these action methods. I don't expect that to be required after we fix the bug.

**Comment by marcuslindblom** [comment]
@rynowak I have already added `EnableCors` at the controller level

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Given that this has not been a common feedback from the community we're closing it.
