### ISSUE TITLE
Assigning an object with implicit operator (cast to string) to Blazor component's parameter causes InvalidCastException

### ISSUE THREAD

**Issue by Oblomoff** [dotnet/aspnetcore#18042]
Object

```C#
namespace BlazorBug
{
    public class Tag
    {
        public Tag(string value) => Value = value;

        public string Value { get; }

        /*
         * BUG!
         * 
         * This implicit operator causes InvalidCastException:
         * Unable to cast object of type 'System.String' to type 'BlazorBug.Tag'.
         * 
         * Comment the code below to avoid the exception.
         */
        public static implicit operator string(Tag tag) => tag.Value;
    }
}
```

Component

```Razor
<h3>Tag Editor</h3>

<p>@Tag</p>

@code {
    [Parameter]
    public Tag Tag { get; set; }
}
```
Assignment

```Razor
@page "/"

<TagEditor Tag="Tag" />

@code {
    public Tag Tag { get; } = new Tag("My Tag");
}
```

Exception
```C#

InvalidCastException: Unable to cast object of type 'System.String'
to type 'BlazorBug.Tag'.

InvalidOperationException: Unable to set property 'Tag' on object of type
'BlazorBug.Shared.TagEditor'. The error was: Unable to cast object of type
'System.String' to type 'BlazorBug.Tag'.
```

Sample project

[BlazorBug.zip](https://github.com/aspnet/AspNetCore/files/4002980/BlazorBug.zip)

**Comment by TLabWest** [comment]
This issue just killed our localization framework... Any updates on this one?

**Comment by GordonRudman** [comment]
I just came across this bug, which is preventing me from binding non-primitive objects (like Value Objects) to components that designed to only accept those types of objects.
I see that this bug is about 2 years old already, so is it on any road map to get fixed in the near future?

**Comment by kieronlanning** [comment]
I've just wasted a morning tracking this down, any movement... updates? ...anything?

**Comment by genyx** [comment]
I came across by another way. I was assigning a string value to a Parameter, which is a reference type (like Tag in example above). The compiler says it's fine, but it breaks when running it, since "SetParameters" works internally with reflection.

```
Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer: [12:30:33.8354]WARN ::RemoteRenderer.HandleException: Unhandled exception rendering component: Unable to set property 'Tag' on object of type 'TagComponent'. The error was: Unable to cast object of type 'System.String' to type 'Tag'. System.InvalidOperationException: Unable to set property 'Tag' on object of type 'TagComponent'. The error was: Unable to cast object of type 'System.String' to type 'Tag'.
 ---> System.InvalidCastException: Unable to cast object of type 'System.String' to type 'Tag'.
   at Microsoft.AspNetCore.Components.Reflection.PropertySetter.CallPropertySetter[TTarget,TValue](Action`2 setter, Object target, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|2_0(Object target, PropertySetter writer, String parameterName, Object value)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|2_0(Object target, PropertySetter writer, String parameterName, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)
   at Microsoft.AspNetCore.Components.ParameterView.SetParameterProperties(Object target)
   at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

```

it seems like it ignores implicit operators at all.

**Comment by rmihael** [comment]
I also stumbled on it. I had something similar to the original problem, but with feature flags instead of tags.
Exception trace is not very helpful, so I spent more time on it than expected.

**Comment by glenn-kallidus** [comment]
Any update on this?

**Comment by FreekSchoenmakersBuckaroo** [comment]
Looks like https://github.com/dotnet/aspnetcore/issues/28949 should be able to solve this issue? It would be great if this gets fixed, would make a lot of things a lot easier to do.

**Comment by gldraphael** [comment]
Thanks for your response @MackinnonBuck 

It's nice that this is going to be addressed in some form.

The real reason this bug/feature-gap is a pain is that the error message is unhelpful and we end up spending hours trying to find why a [smart enum](https://github.com/ardalis/SmartEnum) or another class that worked everywhere else wouldnt work in a blazor component. Often times, the person writing the component is simply using a core DDD class written earlier, and might not necessarily be aware of the operator overload under the hood.

If source generation will automagically solve this such that we will not have to worry about this ever again -- excellent!

But if that is not the case, the minimum bar (in my humble opinion) to call this bug addressed would be to throw an unambiguous error at build time (using a Roslyn analyser for e.g.) that specifically states that the code wont work because (a) class X overloads the implicit conversion operator and that (b) this is not supported.
