### ISSUE TITLE
CopyTo fails to Advance PipeReader on exception

### ISSUE THREAD

**Issue by yshahin** [dotnet/aspnetcore#18138]
### Describe the bug

Using CopyTo to copy the request body stream, a slow connection would trigger 'Reading the request body timed out due to data arriving too slowly. See MinRequestBodyDataRate'

The stream is not cleaned correctly and a write on the response body with 400 results in IO concurrent issue.

### To Reproduce
I have not tested this sample, but you need to trigger the MinRequestBodyDataRate
``` C#
app.Use(async (context, next) =>
{
    try
    {
        using(var stream = new MemoryStream())
        {
            context.Request.body.CopyTo(stream);
        }
    }
    catch (Exception ex)
    {
        context.Response.StatusCode = (int)HttpStatusCode.BadRequest;
        await context.Response.WriteAsync("BadRequest").ConfigureAwait(false);
    }
});
```

Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Reading the request body timed out due to data arriving too slowly. See MinRequestBodyDataRate.
at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
at System.IO.Pipelines.PipeReader.CopyToAsyncCore[TStream](TStream destination, Func4 writeAsync, CancellationToken cancellationToken) at SpeakerRecognition.Common.Utilities.ControllerExtensions.CopyAudioToAsync(HttpRequest request, MemoryStream audioStream) in D:\a\1\s\private\SpeakerRecognition.Hosts.Service\Extensions\ControllerExtensions.cs:line 177 at SpeakerRecognition.Hosts.Controllers.IdentificationController.IdentifyAsync(String identificationProfileIds, Boolean shortAudio) in D:\a\1\s\private\SpeakerRecognition.Hosts.Service\Controllers\IdentificationController.cs:line 108 at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask1 actionResultValueTask)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

### Further technical details
- ASP.NET Core version 3.0

**Comment by Tratcher** [comment]
Notes for triage: This is a similar issue to https://github.com/aspnet/AspNetCore/issues/17723, but in a different location. CopyTo fails to call Advance on the pipe when an exception is thrown so it causes the secondary exception like the one in #17723 "The stream does not support concurrent IO read or write operations.".

That said, MinDataRate exceptions close the connection so draining the request body is unnecessary. Nor is it possible to produce a 400 response like the sample above attempts. This is largely an exercise in exception hygiene and not logging redundant or misleading errors.

**Comment by yshahin** [comment]
@Tratcher, @halter73 any work around in the mean time?
I tried calling Close and cancelPendingRead but they don't help.
I don't know where to get the AdvanceTo parameter from.

**Comment by Tratcher** [comment]
@yshahin not really. However, the only impact should be log noise, there should be no functional impact to the app.

**Comment by anurse** [comment]
@halter73 thinks this may have been fixed (somewhat unintentionally) in 3.1. He'll investigate.

If not, we should get a fix for this, sounds like it's simple enough.

**Comment by halter73** [comment]
This is fixed by https://github.com/dotnet/runtime/issues/1436

**Comment by yshahin** [comment]
@halter73 when will this be released? I have 3.1.100 and it is still there.

**Comment by Tratcher** [comment]
@yshahin this was only fixed in the runtime 5.0 branch so far. Follow up on https://github.com/dotnet/runtime/issues/1436 about patching 3.1.

**Comment by yshahin** [comment]
@Tratcher , that is great thanks. Any chance #17723 would be fixed as well?

**Comment by Tratcher** [comment]
@yshahin yes we plan to address it for 5.0 as well. Or were you asking about 3.1? Let's take that discussion over to #17723, but in general to qualify for a patch the issue must be high impact and difficult to work around.
