### ISSUE TITLE
The request matched multiple endpoints after upgrading to 3.0

### ISSUE THREAD

**Issue by eddyzhu1980** [dotnet/aspnetcore#18221]
After I upgrading to 3.0 from 2.2, I got following error on one function.
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[3]
      An exception was thrown attempting to execute the error handler.
System.InvalidOperationException: Invalid non-ASCII or control character in header: 0x000D
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowInvalidHeaderCharacter(Char ch)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ValidateHeaderValueCharacters(StringValues headerValues)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseHeaders.AddValueFast(String key, StringValues value)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.System.Collections.Generic.IDictionary<System.String,Microsoft.Extensions.Primitives.StringValues>.Add(String key, StringValues value)
   at DatingApp.API.Helpers.Extensions.AddApplicationError(HttpResponse response, String message) in C:\Projects\ECommerceApp\ECommerceApp_API\Helpers\Extensions.cs:line 12
   at DatingApp.API.Startup.<>c.<<Configure>b__5_3>d.MoveNext() in C:\Projects\ECommerceApp\ECommerceApp_API\Startup.cs:line 190
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLSKKJVDVABJ", Request id "0HLSKKJVDVABJ:00000006": An unhandled exception was thrown by the application.
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches:

ECommerce.API.Controllers.OrderShippingOrdersController.CreateShippingLabelPDFForThermal (DatingApp.API)
ECommerce.API.Controllers.OrderShippingOrdersController.CreateShippingLabelPDFForDotPrint (DatingApp.API)
ECommerce.API.Controllers.OrderShippingOrdersController.CreatePDF (DatingApp.API)
ECommerce.API.Controllers.OrderShippingOrdersController.CreateShippingLabelPDF (DatingApp.API)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

### **Front end API Call url:**
http://localhost:5000/api/shops/2/orders/9231/shippingorders

### **My relevant api code:**

 ```
  [Authorize]
    [Route("/api/shops/{shopId}/orders")]
    public class OrdersController: Controller
    {
        [HttpPost]
        public async Task<IActionResult> CreateOrder([FromBody] SaveOrderResource saveOrderResource)
        {
        }
    } 

   [Authorize]
    [Route("/api/shops/{shopId}/orders/{orderId}/shippingorders")]
    public class OrderShippingOrdersController: Controller
    {
       [HttpPost]
        public async Task<IEnumerable<OrderShippingOrderResource>> CreateShippingOrders(int orderId,[FromBody] SaveOrderShippingOrderResource[] shippingOrdersResource)
        {
        ...
        }

       [HttpPost("{id}/GenerateShippingLabelForThermalPrint")]
        public async Task<IActionResult> GenerateShippingLabelForThermalPrint(int orderId,int id,[FromBody] AueUrlResource aueUrlResource) {

       ...
       }
  }

```

Can you please advise what is the issue and how to fix it?

**Comment by javiercn** [comment]
@eddyzhu1980 thanks for contacting us.

@rynowak do you have any thoughts?

**Comment by clockwiseq** [comment]
Not sure if it's the same issue, but I am disambiguating actions in a controller and one is HttpPost, yet the "best possible match" is the HttpPost action whenever an achor is clicked.  Example:

```c#
[Route("Manage/Insurance/Details/{id}")]
public IActionResult Details(Guid id)
{
    var entity = _service.GetInsurance(id);
    
    return View(entity);
}

[HttpPost, Route("Manage/Insurance/Details/{id}")]
public IActionResult Details(Insurance ins)
{
    _service.UpdateInsurance(ins);
    
    return RedirectToAction("Index");
}
```

Now, I have an anchor tag on my view like so:

```asp
<a asp-area="" 
     asp-controller="Insurance" 
     asp-action="Details" 
     asp-route-id="@parent.Insurance.Id">View Details</a>
```

Whenever I click the hyperlink, it hits the HttpPost action.  Is this the same issue or should I create a new one?

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
