### ISSUE TITLE
migration from netcore2.2 to netcore3.0 problems

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#18238]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/878473/migration-from-netcore22-to-netcore30-problems.html)._

---
<p>Hi, I follow the guide on line for migration of project in netcore2.2 to netcore3.3</p><p>I have IdentityServer too.</p><p>but I have different problems so I put my startup.cs</p><p>I have this project, in web is my web application that doesn't use razor. AppDB is class DB  in AuthProvider there is IdentityServer</p><p>Startup.cs of web is </p>

```csharp
using Microsoft.AspNetCore.Builder;

using Microsoft.AspNetCore.Hosting;

using Microsoft.EntityFrameworkCore;

using Microsoft.Extensions.Configuration;

using Microsoft.Extensions.DependencyInjection;

using System.IO;

using Microsoft.IdentityModel.Tokens;

using Microsoft.AspNetCore.Authorization;

using Newtonsoft.Json;

using KSM.Database.AppDB.Models;

using KSM.IdentityProvider.Interface;

using KSM.IdentityProvider;

using Microsoft.AspNetCore.Mvc.Authorization;

using KSM.Web.Helpers;

using System.Security.Claims;

using Microsoft.AspNetCore.Http.Features;

using System;

using KSM.AuditProvider;

using Microsoft.Extensions.FileProviders;

using Microsoft.AspNetCore.Http;

using Microsoft.AspNetCore.Mvc;

using Microsoft.Extensions.Logging;

using KSM.AuthProvider;

using Microsoft.Extensions.Hosting;

namespace KSM.Web

{

public class Startup

{

//startup

public Startup(IConfiguration configuration)

{

Configuration = configuration;

}

public IConfiguration Configuration { get; }

public void ConfigureServices(IServiceCollection services)

{

services.AddControllersWithViews();

services.Configure<CookiePolicyOptions>(options =>

{

// This lambda determines whether user consent for non-essential cookies is needed for a given request.

options.CheckConsentNeeded = context => true;

options.MinimumSameSitePolicy = SameSiteMode.None;

});

//services.AddMvc()

// .SetCompatibilityVersion(CompatibilityVersion.Version_3_0);

services.Configure<KSMConfiguration>(Configuration.GetSection("Configuration"));

services.AddTransient<IKSMIdentityProvider, KSMIdentityProvider>();

services.AddTransient<KSMAuditProvider>();

//***************************************************************************************************

//ADDED ALX

services.AddCors(options =>

{

options.AddPolicy("AllowAll", p =>

{

p.AllowAnyOrigin()

.AllowAnyMethod()

.AllowAnyHeader();

});

});

services.AddMvc(options => options.Filters.Add(new AuthorizeFilter(new AuthorizationPolicyBuilder().RequireAuthenticatedUser().Build())))

.AddJsonOptions(options =>

{

//// options.JsonSerializerOptions.DefaultBufferSize = default;

//// options.JsonSerializerOptions.ReadCommentHandling = System.Text.Json.JsonCommentHandling.Allow;

options.JsonSerializerOptions.IgnoreNullValues = true;

//options.SerializerSettings.DefaultValueHandling = DefaultValueHandling.Include;

//options.SerializerSettings.NullValueHandling = NullValueHandling.Ignore;

});

services.AddAuthorization(options =>

{

options.AddPolicy("SINGLESESSION", policy =>

{

policy.Requirements.Add(new SingleSessionRequirement());

});

options.AddPolicy("CORPORATE", policyBuilder =>

{

policyBuilder.RequireAuthenticatedUser()

.RequireAssertion(context => context.User.HasClaim(ClaimTypes.Role, "CORPORATE"))

.Build();

});

options.AddPolicy("INSTALLER", policyBuilder =>

{

policyBuilder.RequireAuthenticatedUser()

.RequireAssertion(context => context.User.HasClaim(ClaimTypes.Role, "INSTALLER"))

.Build();

});

options.AddPolicy("OPERATOR", policyBuilder =>

{

policyBuilder.RequireAuthenticatedUser()

.RequireAssertion(context => context.User.HasClaim(ClaimTypes.Role, "OPERATOR"))

.Build();

});

options.AddPolicy("SYSTEMUSER", policyBuilder =>

{

policyBuilder.RequireAuthenticatedUser()

.RequireAssertion(context => context.User.HasClaim(ClaimTypes.Role, "SYSTEMUSER"))

.Build();

});

options.AddPolicy("SUPERUSER", policyBuilder =>

{

policyBuilder.RequireAuthenticatedUser()

.RequireAssertion(context => context.User.HasClaim(ClaimTypes.Role, "SUPERUSER"))

.Build();

});

});

KSMConfiguration configuration = new KSMConfiguration();

Configuration.GetSection("Configuration").Bind(configuration);

services.Configure<FormOptions>(options =>

{

options.MemoryBufferThreshold = Int32.MaxValue;

options.MultipartBodyLengthLimit = Int32.MaxValue;

});

string connectionString = Configuration.GetConnectionString("DefaultConnection");

//services.AddDbContext<DBPLATFORMContext>(options => options.UseSqlServer(connectionString));

services.AddDbContext<DBPLATFORMContext>(options =>

{

options.UseSqlServer(connectionString,

sqlServerOptionsAction: sqlOptions =>

{

sqlOptions.EnableRetryOnFailure(maxRetryCount: 5,

maxRetryDelay: TimeSpan.FromSeconds(30),

errorNumbersToAdd: null);

});

});

services.AddAuthentication(KSMAuthenticationHelper.CookieSchema)

.AddCookie(KSMAuthenticationHelper.CookieSchema, options =>

{

options.AccessDeniedPath = "/Login";

options.SlidingExpiration = true;

options.LoginPath = "/Login";

})

.AddJwtBearer("KSMApi", options =>

{

options.Authority = configuration.AuthorityHostURL;

options.Audience = "KSMApi";

options.RequireHttpsMetadata = true;

//options.RequireHttpsMetadata = false;

//options.SaveToken = true;

options.TokenValidationParameters = new TokenValidationParameters

{

ValidateIssuer = true,

ValidateAudience = true,

ValidAudience = "KSMApi"

};

options.BackchannelHttpHandler = new KSMHttpClientHandler(configuration.ProxyActive, configuration.ProxyHost, configuration.ProxyPort, configuration.ProxyUsername, configuration.ProxyPassword);

});

services.AddSingleton<IAuthorizationHandler, SingleSessionHandler>();

services.AddLogging(builder => builder.AddConsole());

}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)

{

app.UseBrowserLink();

app.UseDeveloperExceptionPage();

app.UseDatabaseErrorPage();

app.UseRouting();

app.UseDefaultFiles();

app.UseAuthentication();

app.UseStaticFiles();

app.UseEndpoints(endpoints =>

{

endpoints.MapControllerRoute(

name: "default",

pattern: "api/{controller}/{action}"

);

});

app.Use(async (context, next) => {

await next();

if (context.Response.StatusCode == 404 &&

!Path.HasExtension(context.Request.Path.Value) &&

!context.Request.Path.Value.StartsWith("/api/"))

{

context.Request.Path = "/index.html";

await next();

}

});

//************************

app.UseHsts();

app.UseHttpsRedirection();

app.UseCookiePolicy();

//********************************

app.UseCors("AllowAll");

// app.UseMvcWithDefaultRoute();

}

}

}
```

<p>and when I lunch program from visual studio with F12 I read this error:
</p><ol>
<li>ERROR Error: Uncaught (in promise): Error Error at KSMHttpClient.prototype.onCatch (http://localhost:49658/main.js:16022:9) at CatchSubscriber.prototype.error (http://localhost:49658/vendor.js:222859:17) at Subscriber.prototype._error (http://localhost:49658/vendor.js:218920:9) at Subscriber.prototype.error (http://localhost:49658/vendor.js:218900:13) at onLoad (http://localhost:49658/vendor.js:85664:17) at ZoneDelegate.prototype.invokeTask (http://localhost:49658/polyfills.js:9854:13) at onInvokeTask (http://localhost:49658/vendor.js:63437:17) at ZoneDelegate.prototype.invokeTask (http://localhost:49658/polyfills.js:9854:13) at Zone.prototype.runTask (http://localhost:49658/polyfills.js:9623:21) at ZoneTask.invokeTask (http://localhost:49658/polyfills.js:9931:17)
</li>
<li>HTTP500: ERRORE DEL SERVER - Il server ha rilevato una condizione imprevista che ha impedito l'esecuzione della richiesta. (XHR)GET - http://localhost:49658/api/identity/isloggedin </li></ol>

---
#### Visual Studio Feedback System on 1/8/2020, 07:25 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
