### ISSUE TITLE
Blazor WASM. Can not change BaseIntermediateOutputPath to a higher directory

### ISSUE THREAD

**Issue by MarkusRodler** [dotnet/aspnetcore#18288]
### Describe the bug
I have created an Blazor WASM app and tried to update from netstandard2.0 to netstandard2.1. 
This fails because I changed the BaseIntermediateOutputPath to a higher directory.
With netstandard2.0 everything works as expected.

### To Reproduce
Follow the official guidelines to create a new project: https://docs.microsoft.com/de-de/aspnet/core/blazor/get-started?view=aspnetcore-3.1&tabs=visual-studio-code

1. Create a new Blazor Webassembly project.
2. Create a `Directory.Build.props` file with this content: 
```xml
<Project>
  <PropertyGroup>
    <BaseOutputPath>$(MSBuildThisFileDirectory)\..\build\bin\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)\..\build\obj\</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>
```
3. This error occoures on dotnet build:

``` C#
dotnet build
Microsoft (R)-Build-Engine, Version 16.4.0+e901037fe für .NET Core
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

  Wiederherstellung in "524,13 ms" für "C:\Users\Markus\OneDrive\Workspace\test\App\Dark.csproj" abgeschlossen.
  Dark -> C:\Users\Markus\OneDrive\Workspace\test\build\bin\Debug\netstandard2.1\Dark.dll
  Fatal error in Mono CIL Linker
C:\Users\Markus\.nuget\packages\microsoft.aspnetcore.blazor.build\3.1.0-preview4.19579.2\targets\Blazor.MonoRuntime.targets(204,5): error : 
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Markus\OneDrive\Workspace\test\App\build\obj\Debug\netstandard2.1\blazor\linker.descriptor.xml'. [C:\Users\Markus\OneDrive\Workspace\test\App\Dark.csproj]
     at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
     at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
     at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
     at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
     at System.Xml.XmlTextReaderImpl.OpenUrl()
     at System.Xml.XmlTextReaderImpl.Read()
     at System.Xml.XPath.XPathDocument.LoadFromReader(XmlReader reader, XmlSpace space)
     at System.Xml.XPath.XPathDocument..ctor(String uri, XmlSpace space)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
C:\Users\Markus\.nuget\packages\microsoft.aspnetcore.blazor.build\3.1.0-preview4.19579.2\targets\Blazor.MonoRuntime.targets(204,5): error : 
ILLink failed with exited code -532462766. [C:\Users\Markus\OneDrive\Workspace\test\App\Dark.csproj]

Fehler beim Buildvorgang.

C:\Users\Markus\.nuget\packages\microsoft.aspnetcore.blazor.build\3.1.0-preview4.19579.2\targets\Blazor.MonoRuntime.targets(204,5): error : 
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Markus\OneDrive\Workspace\test\App\build\obj\Debug\netstandard2.1\blazor\linker.descriptor.xml'. [C:\Users\Markus\OneDrive\Workspace\test\App\Dark.csproj]
C:\Users\Markus\.nuget\packages\microsoft.aspnetcore.blazor.build\3.1.0-preview4.19579.2\targets\Blazor.MonoRuntime.targets(204,5): error : 
ILLink failed with exited code -532462766. [C:\Users\Markus\OneDrive\Workspace\test\App\Dark.csproj]
    0 Warnung(en)
    2 Fehler

Verstrichene Zeit 00:00:07.61
```

With `<TargetFramework>netstandard2.0</TargetFramework>` everything works as expected.
With `<TargetFramework>netstandard2.1</TargetFramework>` it doesn't work.
With `<BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)\build\obj\</BaseIntermediateOutputPath>` it can be "fixed".

### Further technical details
- ASP.NET Core version: 3.1
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: VS Code
- Include the output of `dotnet --info`
```cli
dotnet --info
.NET Core SDK (gemäß "global.json"):
 Version:   3.1.100
 Commit:    cd82f021f4

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by javiercn** [comment]
@MarkusRodler thanks for contacting us.

Can you tell us what Blazor version are you using? 

Have you cleaned the bin, obj folders completely before building after changing the path?

**Comment by MarkusRodler** [comment]
I am using the current version bundled with ASP.NET Core 3.1 => 3.1.0-preview4.19579.2
And yes I have cleaned the folders completeley after changing the path.

**Comment by pranavkm** [comment]
As noted in https://github.com/dotnet/aspnetcore/commit/6833facda457847e30dba441bd1a0e14fb025047, the linker has been addressed. blazor dev-server has an issue, so running `dotnet run` was affected. The linked PR should address this.
