### ISSUE TITLE
.Net Core 3.1 problem when call Rest methods

### ISSUE THREAD

**Issue by martinsubash** [dotnet/aspnetcore#18480]
# Issue Title

**.Net Core 3.1 problem when call Rest endpoints- System.InvalidOperationException: No service for type 'Microsoft.Extensions.Logging.ILoggerFactory' has been registered.**

# General
 I have updating net core 2.2 to 3.1. The service started and can able to hit the /api end point.
but hit the API by order like e.g 1) /api/users/{id} then 2) /api/users/1/settings. Here the first request returns response but the second failed, after that the first request also failed. 

The observation is only one endpoint works well if hit another end point then both failed. And the error returned is like below.

```
System.InvalidOperationException: No service for type 'Microsoft.Extensions.Logging.ILoggerFactory' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FloatingPointTypeModelBinderProvider.GetBinder(ModelBinderProviderContext context)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinderCoreUncached(DefaultModelBinderProviderContext providerContext, Object token)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory.CreateBinder(ModelBinderFactoryContext context)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.GetParameterBindingInfo(IModelBinderFactory modelBinderFactory, IModelMetadataProvider modelMetadataProvider, ControllerActionDescriptor actionDescriptor, MvcOptions mvcOptions)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.CreateBinderDelegate(ParameterBinder parameterBinder, IModelBinderFactory modelBinderFactory, IModelMetadataProvider modelMetadataProvider, ControllerActionDescriptor actionDescriptor, MvcOptions mvcOptions)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvokerCache.GetCachedResult(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvokerProvider.OnProvidersExecuting(ActionInvokerProviderContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionInvokerFactory.CreateInvoker(ActionContext actionContext)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointFactory.<>c__DisplayClass7_0.<CreateRequestDelegate>b__0(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Core.Microservice.Infrastructure.HttpExceptionMiddleware.Invoke(HttpContext context) in D:\Source\sisuite-dashboard-new\projects\backend\src\Core.Microservice\Infrastructure\HttpExceptionMiddleware.cs:line 49
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```

My code snippet:

 ```
public HttpExceptionMiddleware(RequestDelegate next, ILoggerFactory loggerFactory)
        {
            _next = next;
            _logger = loggerFactory?.CreateLogger<HttpStatusCodeExceptionMiddleware>();
        }
 public async Task Invoke(HttpContext context)
        {
            try
            {
                await _next(context);
            }
            catch (HttpException ex)
            {
                if (context.Response.HasStarted)
                {
                    _logger.LogWarning("The response has already started, the http status code middleware will not be executed.");
                    throw;
                }

                context.Response.StatusCode = (int)ex.HttpStatus;
                context.Response.ContentType = ex.ContentType;

                await context.Response.WriteAsync(ex.Message);

                return;
            }
        }
    }
```

**Comment by pranavkm** [comment]
Could you share your `Program.cs`  and `Startup.cs`? /cc @Tratcher

**Comment by martinsubash** [comment]
@Tratcher I have shared via email.

**Comment by martinsubash** [comment]
Below are the code:

 

```
public class Program
    {
        public static void Main(string[] args)
        {
            Directory.SetCurrentDirectory(AppDomain.CurrentDomain.BaseDirectory);
            var isService = !(Debugger.IsAttached || args.Contains("--console"));
            var seedData = args.Contains("--seed");
            if (seedData == true)
            {
                DashboardSeedConfig.IntialStartUp().Execute();
            }
            SiShellMicroServiceHost host = new SiShellMicroServiceHost();
            host.Start(isService, seedData);
        }
    }
```

```
using System;
using System.IdentityModel.Tokens.Jwt;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Hosting.Server.Features;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Authorization;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.FileProviders;
using Microsoft.Extensions.Logging;
using Microsoft.IdentityModel.Tokens;
using Core.Microservice.Infrastructure;
using Core.Microservice.Interfaces;
using MultiTenancy.AspNetCore;
using Unity;

public class Startup
    {
        private ILoggerFactory _loggerFactory;
        private DBInitializer _dbInitializer;
        private LoggingProvider _loggingProvider;
        private TenantIssuerValidator _issuerValidator;
        private string _hostUrl;
       
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public void ConfigureContainer(IUnityContainer container)
        {
              _loggingProvider = container.Resolve(typeof(LoggingProvider)) as LoggingProvider;
         }

        public IConfiguration Configuration { get; }
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddTenantContext();
            AddAuthenticationToServices(services);
            services.AddCors(options => options.AddPolicy("CorsPolicy",
                builder =>
               {
                    builder
                    .AllowAnyMethod()
                    .AllowAnyHeader()
                    .AllowAnyOrigin();
                }));
            services
                .AddMvcCore(options =>
                {
                    options.Filters.Add(new AuthorizeFilter(new AuthorizationPolicyBuilder().RequireAuthenticatedUser().Build()));
                })
                .AddAuthorization()
                .AddFormatterMappings()
                .AddNewtonsoftJson()
                .AddFormatterMappings()
                .AddApiExplorer();
            //.SetCompatibilityVersion(CompatibilityVersion.Version_2_1);           

             AddAuthenticationHandler(services);
            services.AddControllers();
            services.AddLogging(builder =>
            {
                //to disable default aspnet core logging on http requests
                builder.AddFilter("Microsoft", LogLevel.Warning);
            });
        }

        public void Configure(IApplicationBuilder app, Microsoft.Extensions.Hosting.IHostEnvironment env, ILoggerFactory loggerFactory, Microsoft.Extensions.Hosting.IHostApplicationLifetime applicationLifetime)
        {
            _loggerFactory = loggerFactory;
            _issuerValidator = new TenantIssuerValidator(_loggerFactory);
            _hostUrl = app.ServerFeatures.Get<IServerAddressesFeature>().Addresses.First();
            GetCustomServices(app);
            _loggerFactory.AddLog4Net(_loggingProvider.LogConfigPath, true);
            if (env.IsDevelopment())
            {
               app.UseDeveloperExceptionPage();
               app.UseHttpExceptionMiddleware();
            }
            else
            {
                app.UseHttpExceptionMiddleware();
            }
            //app.UseHttpsRedirection();
            applicationLifetime.ApplicationStarted.Register(OnStarted);
            app.UseCors("CorsPolicy");
            ConfigureStaticFileHosting(app);
            app.UseRouting();
            app.UseAuthentication();
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }

        private void AddAuthenticationHandler(IServiceCollection services)
        {
            services.AddAuthentication(x =>
            {
                x.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                x.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            })
             });

            services.AddAuthorization(options =>
            {
                ervices.AddSingleton<IAuthorizationHandler, HasScopeHandler>();
           }

        private static void AddAuthenticationToServices(IServiceCollection services)
        {
            // Add authentication
          }

        private static void ConfigureStaticFileHosting(IApplicationBuilder app)
        {
            var fileOptions = new StaticFileOptions
            {
                ServeUnknownFileTypes = true,
                DefaultContentType = "application/json"
            };
             app.UseStaticFiles(fileOptions);
        }

        private void GetCustomServices(IApplicationBuilder app)
        {
            _dbInitializer = app.ApplicationServices.GetService<DBInitializer>();
        }

        private void OnStarted()
        {
            var log = _loggerFactory.CreateLogger("StartupLogger");
            if (!JwtSecurityKeyLoader.CheckSigningKeyStatus())
            {
                log.Log(LogLevel.Error);
            }

            log.Log(LogLevel.Information, "Server is listening to : " + _hostUrl + "api");
            log.Log(LogLevel.Information, Environment.NewLine + Environment.NewLine + "Press CTRL+C to stop server");
        }
    }
}

 
```

**Comment by Tratcher** [comment]
It’s interesting ILoggerFactory works in Startup but not in MVC. Maybe there’s something wrong with how your container (Unity?) manages per-request scopes? ILoggerFactory isn’t scoped, but it would be resolved within the context of one. Does it work with the built in container?

What is SiShellMicroServiceHost?

**Comment by Tratcher** [comment]
Looks like Unity didn't support ASP.NET Core 3.0 until at least 5.11.2. What version are you using?
https://github.com/unitycontainer/microsoft-dependency-injection/issues/57#issuecomment-562995553

**Comment by martinsubash** [comment]
Yes you are correct. After upgraded [Unity.Microsoft.DependencyInjection 5.11.5](https://www.nuget.org/packages/Unity.Microsoft.DependencyInjection/5.11.5)   and [Unity.Configuration 5.11.1](https://www.nuget.org/packages/Unity.Configuration/5.11.1) its working.

Thank you for the support @Tratcher and @pranavkm.
