### ISSUE TITLE
Test Failure: Publish_CopiesStaticWebAssetsToDestinationFolder_PublishSingleFile

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#18543]
This test has like a 50% failure rate. I'll be marking it as flaky shortly.

Example failure output:
```
System.TimeoutException : command '$F:\workspace\_work\1\s\.dotnet\dotnet.exe msbuild /nr:false /bl /p:RunningAsTest=true /p:MicrosoftNETCoreApp50PackageVersion=5.0.0-alpha.1.20071.7 /p:MicrosoftNetCompilersToolsetPackageVersion=3.5.0-beta1-19606-04 /p:RuntimeAdditionalRestoreSources=F:\workspace\_work\1\s\src\Razor\test\Microsoft.NET.Sdk.Razor.Test\..\testapps\TestPackageRestoreSource /p:_RazorBuildServerPipeName="f9292464-5957-40ca-ba62-8186e187db34" /t:Publish /p:Configuration=Release /restore /p:PublishSingleFile=true /p:ReferenceLocallyBuiltPackages=true' timed out after 00:05:00. Output: Microsoft (R) Build Engine version 16.5.0-preview-20059-02+ab9b2f36a for .NET Core\r\nCopyright (C) Microsoft Corporation. All rights reserved.\r\n\r\nF:\workspace\_work\1\s\.dotnet\sdk\5.0.100-alpha.1.20063.3\MSBuild.dll -maxcpucount -verbosity:m /bl /nr:false /p:RunningAsTest=true /p:MicrosoftNETCoreApp50PackageVersion=5.0.0-alpha.1.20071.7 /p:MicrosoftNetCompilersToolsetPackageVersion=3.5.0-beta1-19606-04 /p:RuntimeAdditionalRestoreSources=F:\workspace\_work\1\s\src\Razor\test\Microsoft.NET.Sdk.Razor.Test\..\testapps\TestPackageRestoreSource /p:_RazorBuildServerPipeName=f9292464-5957-40ca-ba62-8186e187db34 /p:Configuration=Release /p:PublishSingleFile=true /p:ReferenceLocallyBuiltPackages=true /restore /t:Publish .\AppWithPackageAndP2PReferenceAndRID.csproj\r\n Restore completed in 17.87 sec for C:\Users\vsagent\AppData\Local\Temp\Razor\eoz20w2x.ykw\ClassLibrary2\ClassLibrary2.csproj.\r\n Restore completed in 18.02 sec for C:\Users\vsagent\AppData\Local\Temp\Razor\eoz20w2x.ykw\ClassLibrary\ClassLibrary.csproj.\r\n Restore completed in 27.62 sec for C:\Users\vsagent\AppData\Local\Temp\Razor\eoz20w2x.ykw\AppWithPackageAndP2PReferenceAndRID\AppWithPackageAndP2PReferenceAndRID.csproj.\r\n You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview\r\n You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview\r\n ClassLibrary -> C:\Users\vsagent\AppData\Local\Temp\Razor\eoz20w2x.ykw\ClassLibrary\bin\Release\netcoreapp5.0\ClassLibrary.dll\r\n ClassLibrary -> C:\Users\vsagent\AppData\Local\Temp\Razor\eoz20w2x.ykw\ClassLibrary\bin\Release\netcoreapp5.0\ClassLibrary.Views.dll\r\n ClassLibrary2 -> C:\Users\vsagent\AppData\Local\Temp\Razor\eoz20w2x.ykw\ClassLibrary2\bin\Release\netcoreapp5.0\ClassLibrary2.dll\r\n ClassLibrary2 -> C:\Users\vsagent\AppData\Local\Temp\Razor\eoz20w2x.ykw\ClassLibrary2\bin\Release\netcoreapp5.0\ClassLibrary2.Views.dll\r\n
```

Stack trace
```
at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.<>c__DisplayClass1_0.<<RunProcessCoreAsync>g__GetTimeoutForProcess|3>d.MoveNext() in /_/src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildProcessManager.cs:line 145
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.RunProcessAsync(ProjectDirectory project, String arguments, Nullable`1 timeout, MSBuildProcessKind msBuildProcessKind, String localPackageCache) in /_/src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildProcessManager.cs:line 62
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.StaticWebAssetsIntegrationTest.Publish_CopiesStaticWebAssetsToDestinationFolder_PublishSingleFile() in /_/src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/StaticWebAssetsIntegrationTest.cs:line 92
--- End of stack trace from previous location ---
```

Build failure: https://dev.azure.com/dnceng/public/_build/results?buildId=492987&view=ms.vss-test-web.build-test-results-tab&runId=15695606&resultId=100201&paneView=debug

Note about the above build failure, I hit retry to get a PR in so not sure if it'll maintain the build error after retry.

@javiercn assigning to you since this is your baby. Wasn't sure what other labels to assign here.

**Comment by javiercn** [comment]
Did improvements as part of https://github.com/dotnet/aspnetcore-tooling/commit/0d03b576172b447b356c9559073b6f3911717520

**Comment by halter73** [comment]
New failure:

```
System.TimeoutException : command '$F:\workspace\_work\1\s\.dotnet\dotnet.exe msbuild /nr:false /bl /p:RunningAsTest=true /p:MicrosoftNETCoreApp31PackageVersion=3.1.6 /p:MicrosoftNetCompilersToolsetPackageVersion=3.4.1-beta4-20127-10 /p:RuntimeAdditionalRestoreSources=F:\workspace\_work\1\s\src\Razor\test\Microsoft.NET.Sdk.Razor.Test\..\testapps\TestPackageRestoreSource /p:_RazorBuildServerPipeName="0040ec47-4a94-4313-8a10-7f2fc1099bbb" /t:Publish /p:Configuration=Debug /restore /p:PublishSingleFile=true /p:ReferenceLocallyBuiltPackages=true' timed out after 00:05:00. Output: Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core\r\nCopyright (C) Microsoft Corporation. All rights reserved.\r\n\r\nF:\workspace\_work\1\s\.dotnet\sdk\3.1.100\MSBuild.dll -maxcpucount -verbosity:m /bl /nr:false /p:RunningAsTest=true /p:MicrosoftNETCoreApp31PackageVersion=3.1.6 /p:MicrosoftNetCompilersToolsetPackageVersion=3.4.1-beta4-20127-10 /p:RuntimeAdditionalRestoreSources=F:\workspace\_work\1\s\src\Razor\test\Microsoft.NET.Sdk.Razor.Test\..\testapps\TestPackageRestoreSource /p:_RazorBuildServerPipeName=0040ec47-4a94-4313-8a10-7f2fc1099bbb /p:Configuration=Debug /p:PublishSingleFile=true /p:ReferenceLocallyBuiltPackages=true /restore /t:Publish .\AppWithPackageAndP2PReferenceAndRID.csproj\r\n  Restore completed in 8.76 sec for F:\h\w\AE0509A3\t\Razor\hn0m0gap.1dp\ClassLibrary\ClassLibrary.csproj.\r\n  Restore completed in 9.04 sec for F:\h\w\AE0509A3\t\Razor\hn0m0gap.1dp\ClassLibrary2\ClassLibrary2.csproj.\r\n  Restore completed in 16.47 sec for F:\h\w\AE0509A3\t\Razor\hn0m0gap.1dp\AppWithPackageAndP2PReferenceAndRID\AppWithPackageAndP2PReferenceAndRID.csproj.\r\n  ClassLibrary -> F:\h\w\AE0509A3\t\Razor\hn0m0gap.1dp\ClassLibrary\bin\Debug\netcoreapp3.1\ClassLibrary.dll\r\n  ClassLibrary -> F:\h\w\AE0509A3\t\Razor\hn0m0gap.1dp\ClassLibrary\bin\Debug\netcoreapp3.1\ClassLibrary.Views.dll\r\n
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.<>c__DisplayClass1_0.<<RunProcessCoreAsync>g__GetTimeoutForProcess|3>d.MoveNext() in /_/src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildProcessManager.cs:line 160
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.RunProcessAsync(ProjectDirectory project, String arguments, Nullable`1 timeout, MSBuildProcessKind msBuildProcessKind, String localPackageCache) in /_/src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildProcessManager.cs:line 59
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.StaticWebAssetsIntegrationTest.Publish_CopiesStaticWebAssetsToDestinationFolder_PublishSingleFile() in /_/src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/StaticWebAssetsIntegrationTest.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
```

https://dev.azure.com/dnceng/public/_build/results?buildId=729862&view=ms.vss-test-web.build-test-results-tab&runId=22577032&resultId=100204&paneView=debug

**Comment by pranavkm** [comment]
These tests have been moved to the SDK repo. It has since had one failure in the last 30 days from a feed related issue that's part of an ongoing effort to mitigate and isn't specific to this test.

Resolving this as addressed since any solution to the feed isn't going to be handled by us separately from the SDK's larger effort to stabilize restores in their tests.
