### ISSUE TITLE
Test Failure: Publish_NoBuild_CopiesStaticWebAssetsToDestinationFolder

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#18561]
This test has like a pretty high failure rate. I'll be marking it as flaky shortly.

Example failure output:
```
System.TimeoutException : command '$F:\workspace\_work\1\s\.dotnet\dotnet.exe msbuild /nr:false /bl /p:RunningAsTest=true /p:MicrosoftNETCoreApp50PackageVersion=5.0.0-alpha.1.20072.3 /p:MicrosoftNetCompilersToolsetPackageVersion=3.5.0-beta1-19606-04 /p:RuntimeAdditionalRestoreSources=F:\workspace\_work\1\s\src\Razor\test\Microsoft.NET.Sdk.Razor.Test\..\testapps\TestPackageRestoreSource /p:_RazorBuildServerPipeName="a1288401-1ab5-47f1-8adf-67d7426c1d72" /t:Build /p:Configuration=Debug /restore' timed out after 00:05:00. Output: Microsoft (R) Build Engine version 16.5.0-preview-20059-02+ab9b2f36a for .NET Core\r\nCopyright (C) Microsoft Corporation. All rights reserved.\r\n\r\nF:\workspace\_work\1\s\.dotnet\sdk\5.0.100-alpha.1.20063.3\MSBuild.dll -maxcpucount -verbosity:m /bl /nr:false /p:RunningAsTest=true /p:MicrosoftNETCoreApp50PackageVersion=5.0.0-alpha.1.20072.3 /p:MicrosoftNetCompilersToolsetPackageVersion=3.5.0-beta1-19606-04 /p:RuntimeAdditionalRestoreSources=F:\workspace\_work\1\s\src\Razor\test\Microsoft.NET.Sdk.Razor.Test\..\testapps\TestPackageRestoreSource /p:_RazorBuildServerPipeName=a1288401-1ab5-47f1-8adf-67d7426c1d72 /p:Configuration=Debug /restore /t:Build .\AppWithPackageAndP2PReference.csproj\r\n Restore completed in 10.54 sec for C:\Users\vsagent\AppData\Local\Temp\Razor\c0kr20n2.be0\ClassLibrary\ClassLibrary.csproj.\r\n Restore completed in 10.54 sec for C:\Users\vsagent\AppData\Local\Temp\Razor\c0kr20n2.be0\ClassLibrary2\ClassLibrary2.csproj.\r\n Restore completed in 10.53 sec for C:\Users\vsagent\AppData\Local\Temp\Razor\c0kr20n2.be0\AppWithPackageAndP2PReference\AppWithPackageAndP2PReference.csproj.\r\n You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview\r\n You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview\r\n ClassLibrary -> C:\Users\vsagent\AppData\Local\Temp\Razor\c0kr20n2.be0\ClassLibrary\bin\Debug\netcoreapp5.0\ClassLibrary.dll\r\n ClassLibrary -> C:\Users\vsagent\AppData\Local\Temp\Razor\c0kr20n2.be0\ClassLibrary\bin\Debug\netcoreapp5.0\ClassLibrary.Views.dll\r\n
```

Stack trace
```
at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.<>c__DisplayClass1_0.<<RunProcessCoreAsync>g__GetTimeoutForProcess|3>d.MoveNext() in /_/src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildProcessManager.cs:line 160
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.RunProcessAsync(ProjectDirectory project, String arguments, Nullable`1 timeout, MSBuildProcessKind msBuildProcessKind, String localPackageCache) in /_/src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildProcessManager.cs:line 59
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.StaticWebAssetsIntegrationTest.Publish_NoBuild_CopiesStaticWebAssetsToDestinationFolder() in /_/src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/StaticWebAssetsIntegrationTest.cs:line 137
--- End of stack trace from previous location ---
```

Build failure: https://dev.azure.com/dnceng/public/_build/results?buildId=495506&view=ms.vss-test-web.build-test-results-tab

@javiercn assigning to you since this is your baby. Wasn't sure what other labels to assign here.

**Comment by javiercn** [comment]
Did improvements as part of https://github.com/dotnet/aspnetcore-tooling/commit/0d03b576172b447b356c9559073b6f3911717520 closing for now.
