### ISSUE TITLE
System.Text.Json: The collection type 'Microsoft.AspNetCore.Http.IQueryCollection' on 'Microsoft.AspNetCore.Http.HttpRequest.Query' is not supported

### ISSUE THREAD

**Issue by tmeschede** [dotnet/aspnetcore#18652]
Writing some middle ware where I am capturing the request and response of customers interaction with our web site.  I am trying to log the request object as JSON, but I am getting the error message below: 

The collection type 'Microsoft.AspNetCore.Http.IQueryCollection' on 'Microsoft.AspNetCore.Http.HttpRequest.Query' is not supported.
```
at System.Text.Json.JsonClassInfo.GetElementType(Type propertyType, Type parentType, MemberInfo memberInfo, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.CreateProperty(Type declaredPropertyType, Type runtimePropertyType, Type implementedPropertyType, PropertyInfo propertyInfo, Type parentClassType, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.AddProperty(Type propertyType, PropertyInfo propertyInfo, Type classType, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type classType)
   at System.Text.Json.WriteStackFrame.Initialize(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCore(Utf8JsonWriter writer, Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCore(PooledByteBufferWriter output, Object value, Type ty
pe, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCoreString(Object value, Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at FormTest.Middleware.Capture_Middleware.LogRequestAsync(HttpContext context, IBrowserDetector bd) in C:\\TEM\\source\\FormTest_Solution\\FormTest\\Middleware\\Capture_Middleware.cs:line 396
```
Below is the I am using:
```
        try
        {
          var options = new System.Text.Json.JsonSerializerOptions
          {
            WriteIndented = true
          };

          var jsonRequest = System.Text.Json.JsonSerializer.Serialize(request, options);
          Console.WriteLine(jsonRequest);
        }
        catch (Exception ex)
        {
          var message = ex.Message;
        }
```
Just curious if there is a bug in the System.Text.Json library or something I am doing wrong.

Thanks in advance,

Tom

**Comment by pranavkm** [comment]
Looks like a dup of https://github.com/dotnet/corefx/issues/42084. @layomia, what do you recommend we do this issue?

**Comment by layomia** [comment]
@pranavkm I say close as dup of dotnet/corefx#42084.

**Comment by pranavkm** [comment]
Thanks. @tmeschede, we'll use the linked issue to track further work here.
