### ISSUE TITLE
Unauthorised connection disconnects instead of receiving 401 when run without IIS

### ISSUE THREAD

**Issue by MhAllan** [dotnet/aspnetcore#18682]
### Describe the bug
Authorised action causes the HttpClient connection to disconnect instead of returning unauthorised status code when you run asp.net core without IIS.

Output:
**No connection could be made because the target machine actively refused it.**

   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)

### To Reproduce
Controller like this 
``` C#
[Authorize]
    [Route("home")]
    public class HomeController : Controller
    {
        [HttpGet]
        public IActionResult Get()
        {
            return Ok("Ready");
        }
    }
```
And client using HttpClient
``` C#
await (new HttpClient()).GetAsync(url);
```
**If run the service using IIS Express, the client will get Unauthorised which is correct, If you run it without IIS the connection will disconnect and you will get the output above.**

**Comment by Tratcher** [comment]
`No connection could be made because the target machine actively refused it.`

That's not an authorization error, that's a TCP error saying you tried to connect to an address/port that the server was not listening on. When you start the app using Kestrel it uses different ports than IIS Express does. It should say in the console or launchsettings.json which port it used.
