### ISSUE TITLE
Test Failure: Publish_WithBuildReferencesDisabled_CopiesStaticWebAssetsToDestinationFolder

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#18707]
This test has a pretty high failure rate. Going to mark this as flaky.

Example failure output:
```
System.TimeoutException : command '$F:\workspace\_work\1\s\.dotnet\dotnet.exe msbuild /nr:false /bl /p:RunningAsTest=true /p:MicrosoftNETCoreApp50PackageVersion=5.0.0-alpha.1.20078.2 /p:MicrosoftNetCompilersToolsetPackageVersion=3.5.0-beta2-20074-05 /p:RuntimeAdditionalRestoreSources=F:\workspace\_work\1\s\src\Razor\test\Microsoft.NET.Sdk.Razor.Test\..\testapps\TestPackageRestoreSource /p:_RazorBuildServerPipeName="e56034c3-0981-4d8f-8c2a-1710cde6f2e4" /t:Build /p:Configuration=Release /restore' timed out after 00:05:00. Output: Microsoft (R) Build Engine version 16.5.0-preview-20059-02+ab9b2f36a for .NET Core\r\nCopyright (C) Microsoft Corporation. All rights reserved.\r\n\r\nF:\workspace\_work\1\s\.dotnet\sdk\5.0.100-alpha.1.20063.3\MSBuild.dll -maxcpucount -verbosity:m /bl /nr:false /p:RunningAsTest=true /p:MicrosoftNETCoreApp50PackageVersion=5.0.0-alpha.1.20078.2 /p:MicrosoftNetCompilersToolsetPackageVersion=3.5.0-beta2-20074-05 /p:RuntimeAdditionalRestoreSources=F:\workspace\_work\1\s\src\Razor\test\Microsoft.NET.Sdk.Razor.Test\..\testapps\TestPackageRestoreSource /p:_RazorBuildServerPipeName=e56034c3-0981-4d8f-8c2a-1710cde6f2e4 /p:Configuration=Release /restore /t:Build .\AppWithPackageAndP2PReference.csproj\r\n Restore completed in 7.94 sec for F:\workspace\_work\1\s\artifacts\tmp\Release\Razor\o4o5jb20.l3y\ClassLibrary2\ClassLibrary2.csproj.\r\n Restore completed in 7.97 sec for F:\workspace\_work\1\s\artifacts\tmp\Release\Razor\o4o5jb20.l3y\AppWithPackageAndP2PReference\AppWithPackageAndP2PReference.csproj.\r\n Restore completed in 7.94 sec for F:\workspace\_work\1\s\artifacts\tmp\Release\Razor\o4o5jb20.l3y\ClassLibrary\ClassLibrary.csproj.\r\n You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview\r\n You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview\r\n ClassLibrary -> F:\workspace\_work\1\s\artifacts\tmp\Release\Razor\o4o5jb20.l3y\ClassLibrary\bin\Release\netcoreapp5.0\ClassLibrary.dll\r\n ClassLibrary -> F:\workspace\_work\1\s\artifacts\tmp\Release\Razor\o4o5jb20.l3y\ClassLibrary\bin\Release\netcoreapp5.0\ClassLibrary.Views.dll\r\n ClassLibrary2 -> F:\workspace\_work\1\s\artifacts\tmp\Release\Razor\o4o5jb20.l3y\ClassLibrary2\bin\Release\netcoreapp5.0\ClassLibrary2.dll\r\n ClassLibrary2 -> F:\workspace\_work\1\s\artifacts\tmp\Release\Razor\o4o5jb20.l3y\ClassLibrary2\bin\Release\netcoreapp5.0\ClassLibrary2.Views.dll\r\n AppWithPackageAndP2PReference -> F:\workspace\_work\1\s\artifacts\tmp\Release\Razor\o4o5jb20.l3y\AppWithPackageAndP2PReference\bin\Release\netcoreapp5.0\AppWithPackageAndP2PReference.dll\r\n
```

Stack trace
```
 at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.<>c__DisplayClass1_0.<<RunProcessCoreAsync>g__GetTimeoutForProcess|3>d.MoveNext() in /_/src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildProcessManager.cs:line 145
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.RunProcessAsync(ProjectDirectory project, String arguments, Nullable`1 timeout, MSBuildProcessKind msBuildProcessKind, String localPackageCache) in /_/src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildProcessManager.cs:line 62
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.StaticWebAssetsIntegrationTest.Publish_WithBuildReferencesDisabled_CopiesStaticWebAssetsToDestinationFolder() in /_/src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/StaticWebAssetsIntegrationTest.cs:line 116
--- End of stack trace from previous location ---
```

Here is one failing build https://dev.azure.com/dnceng/public/_build/results?buildId=502524&view=ms.vss-test-web.build-test-results-tab&runId=15959088&resultId=100015&paneView=debug

@javiercn, assigning this to you as this probably has the root cause as other failures you are looking at like #18561

**Comment by javiercn** [comment]
Did some improvements in this area as part of https://github.com/dotnet/aspnetcore-tooling/commit/0d03b576172b447b356c9559073b6f3911717520 closing for now.
