### ISSUE TITLE
Synchronous call inside XDocument.LoadAsync causes --> System.InvalidOperationException: Synchronous operations are disallowed

### ISSUE THREAD

**Issue by mayur-rao** [dotnet/aspnetcore#18723]
### Synchronous operations are disallowed (kestrel) when calling XDocument.LoadAsync
When a .net core 3.1 ASP.Net WebApi receives an xml input and tries to load that into an Xdoc using the XDocument.LoadAsync method, the web api throws Synchronous operations are disallowed error and the stack trace points to a synchronous call from inside XDocument.LoadAsync method. 

Notice in the stack trace 4 calls down from System.Xml.Linq.XDocument.LoadAsync there is a System.Xml.Linq.XContainer.ContentReader.ReadContentFrom which inturn makes calls to ystem.Xml.XmlTextReaderImpl.ReadData(). Due to this, the web server throws ystem.InvalidOperationException: Synchronous operations are disallowed. 

### To Reproduce
1. Clone the linked GitHub repo --> [NetCoreUpgrade](https://github.com/mayur-rao/NetCoreUpgrade.git)
2. docker-compose up -d to launch the web api with docker.
3. Open the solution with Visual Studio 2019.
4. Set start up project to WebApiHitter
5. Launch the netcore app. 
6. After processing few requests, the web api will throw an error : 

Link to github repo [here](https://github.com/mayur-rao/NetCoreUpgrade)

``` C#
			var xmlRequest = context.HttpContext.Request;
			using (var xmlStream = new StreamReader(xmlRequest.Body))
			{
				var xmlDoc = await XDocument.LoadAsync(xmlStream, LoadOptions.None, CancellationToken.None);
				return await InputFormatterResult.SuccessAsync(xmlDoc);
```
above file available [here](https://github.com/mayur-rao/NetCoreUpgrade/blob/master/XmlBasedWebApp/Formatter/XmlInputFormatter.cs)

```An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer(Span`1 userBuffer, Boolean& readToUserBuffer)
   at System.IO.StreamReader.ReadSpan(Span`1 buffer)
   at System.IO.StreamReader.Read(Char[] buffer, Int32 index, Int32 count)
   at System.Xml.XmlTextReaderImpl.ReadData()
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.FinishPartialValue()
   at System.Xml.XmlTextReaderImpl.get_Value()
   at System.Xml.Linq.XContainer.ContentReader.ReadContentFrom(XContainer rootContainer, XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFromAsync(XmlReader r, CancellationToken cancellationToken)
   at System.Xml.Linq.XContainer.ReadContentFromAsync(XmlReader r, LoadOptions o, CancellationToken cancellationToken)
   at System.Xml.Linq.XDocument.LoadAsyncInternal(XmlReader reader, LoadOptions options, CancellationToken cancellationToken)
   at System.Xml.Linq.XDocument.LoadAsync(TextReader textReader, LoadOptions options, CancellationToken cancellationToken)
   at XmlBasedWebApp.Formatter.XmlInputFormatter.ReadRequestBodyAsync(InputFormatterContext context) in /src/XmlBasedWebApp/Formatter/XmlInputFormatter.cs:line 23
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Further technical details
- ASP.NET Core version is 3.1.1
```dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c
```
- I have run this project on VS 2019 - Version 16.4.4

**Comment by pranavkm** [comment]
See the announcement here: https://github.com/aspnet/Announcements/issues/342. Also listed as part of the migration guide: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#allowsynchronousio-disabled.

Is there a reason you're rolling a custom Xml formatter as opposed to using the ones MVC provides by default - https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-3.1#add-xml-format-support?

**Comment by mayur-rao** [comment]
@pranavkm : 1. I am aware of the option to set syncIO=true while running the app. But wouldn't that affect performance? The reason Microsoft provides is they are turned off by default (from .netcoreapp3.1) to prevent starvation or app hangs. 
2. Is it ok for Linq to make a synchronous call inside an Async method? (Xdocument.LoadAsync()). 
Because it is like, although I as a developer am placing a call to Xdocument.LoadAsync(), I have to turn on syncIO=true just because internally there is a sync call happening. Isn't that a bug?

**Comment by pranavkm** [comment]
@mayur-rao sorry I missed that you're performing an async read. It does look like `XDocument` performs sync reads when you call LoadAsync. I'd recommend filing an issue in https://github.com/dotnet/runtime here to see if they could address it.

To answer your previous question, setting SyncIO = true, your app shouldn't perform any worse than what it was prior to an upgrade from 2.2. However, if you absolutely needed to avoid sync io, you could buffer the contents in memory. Starting in 3.0, MVC's XML and JSON formatters do this by default: https://github.com/dotnet/aspnetcore/blob/master/src/Mvc/Mvc.Formatters.Xml/src/XmlSerializerInputFormatter.cs#L111-L112
