### ISSUE TITLE
Deserialization issue in Microsoft.AspNetCore.Mvc.NewtonsoftJson

### ISSUE THREAD

**Issue by alexbezugliy** [dotnet/aspnetcore#18780]
### Describe the bug
When i was using Microsoft.AspNetCore.Mvc.NewtonsoftJson in my app i switched to newtonsoft json instead of using System.Text.Json which is coming by default. However i had a test which were testing rest api with various validational cases. On of the cases was when we use wrong json which can’t be properly deserialized to an appropriate DTO and be passed to a controller POST method as a request body.
This json properly result in invalid model state behaviour - however the internal error handling shows weird error messages to me stating that i have problems in array items by non-existing indexes. I debugged the problem a bit but the only thing i get is that the problem is somewhere inside JsonSerializerInternalReader.Deserialize method which catches the error for me which i posted down bellow. In this exception we can see a path recoveryGroups[2] - which is not existing cause i have only 1 recovery group in my json array. It works correctly if i’m using System.Text.Json by default. It works as expected also if i try to deserialize with Newtonsoft.Json version 12 like this:
JsonConvert.DeserializeObject<RunbookDto>(json);

### To Reproduce
In order to reproduce this issue you need to a simple rest api with post method and use json like this as a request body(lmk if you need a class structure also):
{
"name": "runBookName1",
"platformType": 0,
"timeCreated": "2019-09-09T11:36:38.236Z",
"timeUpdated": "2019-09-09T11:36:38.236Z",
"updatedByUserName": "string ByUserName",
"recoveryGroups": [
{
"identifier": "string identifier",
"name": [],
"description": "string name",
"vms": [
{
"identifier": "string vms identifier",
"name": "string vms name",
"vmPath": "string VmPath",
"powerOn": true,
"vcenter": "string VmsVcenter",
"storage": "string VmsStorage",
"vmxLun": "string vmxLun",
"resourcePool": "string resourcePool",
"diskMap": {
"additionalProp1": {
"datastoreId": "string DiskMapDatastoreId",
"copy": "string copy",
"vmotion": "string vmotion"
},
"additionalProp2": {
"datastoreId": "string DiskMapDatastoreId",
"copy": "string copy",
"vmotion": "string vmotion"
},
"additionalProp3": {
"datastoreId": "string DiskMapDatastoreId",
"copy": "string copy",
"vmotion": "string vmotion"
}
},
"networkMap": {
"additionalProp1": "string additionalProp1",
"additionalProp2": "string additionalProp2",
"additionalProp3": "string additionalProp23"
},
"recoveryStatus": 0
}
],
"timeStarted": "2019-09-09T11:36:38.236Z",
"timeCompleted": "2019-09-09T11:36:38.236Z"
}
]
}
Inside this json i used
"name": [],
however name is a string field in my dto object i’m trying to deserialize to.
This is my validational case to return invalid model state in case of invalid json. As a result i also see
Infinite loop detected from error handling.
inside inner exceptions which should not be the case. The result should be a different exception like wrong symbol detected for path recoveryGroups[0].name and that’s it.

Newtonsoft.Json.JsonSerializationException: Error converting value "description" to type ‘Faction.Hdraas.RestApi.v1.Controllers.Dto.RunbookDto’. Path ‘recoveryGroups[2]’, line 11, position 19.
---> System.ArgumentException: Could not cast or convert from System.String to Faction.Hdraas.RestApi.v1.Controllers.Dto.RunbookDto.
at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
--- End of inner exception stack trace ---
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)

### Further technical details
- ASP.NET Core version 3.1.1
- output of `dotnet --info`:
.NET Core SDK (reflecting any global.json):
Version:   3.1.101
Commit:    b377529961

Runtime Environment:
OS Name:     Mac OS X
OS Version:  10.13
OS Platform: Darwin
RID:         osx.10.13-x64
Base Path:   /usr/local/share/dotnet/sdk/3.1.101/

Host (useful for support):
Version: 3.1.1
Commit:  a1388f194c

.NET Core SDKs installed:
2.1.502 [/usr/local/share/dotnet/sdk]
2.2.103 [/usr/local/share/dotnet/sdk]
2.2.402 [/usr/local/share/dotnet/sdk]
3.0.101 [/usr/local/share/dotnet/sdk]
3.1.100 [/usr/local/share/dotnet/sdk]
3.1.101 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
Microsoft.AspNetCore.All 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 2.2.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
- IDE is JetBrains Rider 2019.3.1

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by alexbezugliy** [comment]
Sure, but please give me some time cause i have other work to do atm too. Cause this one requires a bit of effort to correctly slice the right middle-ware stack in one peace. Currently i reproduced it within our product environment middle-ware stack based on chassis pattern. I'll update with simplified repo due to next Monday. Hopefully it will work as expected though - so i get the wrong shot to you guys. Will this work for you?

**Comment by pranavkm** [comment]
Sure, that sounds fine. I'll keep this open until you can get back next week.

**Comment by alexbezugliy** [comment]
Hi guys - here is the repo https://github.com/alexbezugliy/deserialization-issue
please take a look.
There is a test with TODO inside that should pass - which depicts the problem. Please let me know if this is enough and make sense for you guys.

**Comment by pranavkm** [comment]
Thanks for the repro app @alexbezugliy. MVC reports errors from Newtonsoft.Json as-is and I'm able to reproduce this without MVC involved. I've filed https://github.com/JamesNK/Newtonsoft.Json/issues/2273 to figure out how to approach this.

**Comment by pranavkm** [comment]
Parking this in the backlog in case there's additional work to be done.
