### ISSUE TITLE
VS 2019 Angular template throws "Unable to load shared library 'System.Security.Cryptography.Native.OpenSsl'" in Docker

### ISSUE THREAD

**Issue by Dawsain** [dotnet/aspnetcore#18923]
### Describe the bug
I create a new ASP.Net Core Web Application (C#) Angular application from the template provided in Visual Studio 2019. I then dockerize it. The application runs in the container but Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider throws an exception on startup.

### To Reproduce

1. Open VS 2019
2. Create a new project of type ASP.Net Core Web Application (.Core version 3.1) and name it DataProtectionDockerTest2.
3. Choose project type "Angular"
4. Check "Configure for https" box
5. Create a file named Dockerfile (no extension) in the solution folder:

```
FROM mcr.microsoft.com/dotnet/core/runtime:3.1
WORKDIR /app
COPY Output/ .
ENTRYPOINT ["dotnet", "DataProtectionDockerTest2.dll"]
```

Run the following commands in the solution folder:

```
dotnet publish DataProtectionDockerTest2/DataProtectionDockerTest2.csproj --configuration=Release --output=Output --runtime=rhel.6-x64
docker build -t dataprtdocktest -f Dockerfile .
docker run -it --rm -p 5000:80 -e LD_DEBUG='libs' --name dataprtdocktest_container dataprtdocktest
```

The app runs in the container but throws an exception on startup:

```
fail: Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider[48]
 An error occurred while reading the key ring.
System.TypeInitializationException: The type initializer for 'Crypto' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'System.Security.Cryptography.Native.OpenSsl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libSystem.Security.Cryptography.Native.OpenSsl: cannot open shared object file: No such file or directory
 at Interop.Crypto.GetMaxMdSize()
 at Interop.Crypto..cctor()
 --- End of inner exception stack trace ---
 at System.Security.Cryptography.RandomNumberGeneratorImplementation.GetBytes(Span`1 data)
 at System.Security.Cryptography.RandomNumberGeneratorImplementation.GetBytes(Byte[] data)
 at Microsoft.AspNetCore.DataProtection.Secret.Random(Int32 numBytes)
 at Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorConfiguration.CreateNewDescriptor()
 at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.CreateNewKey(Guid keyId, DateTimeOffset creationDate, DateTimeOffset activationDate, DateTimeOffset expirationDate)
 at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.CreateNewKey(DateTimeOffset activationDate, DateTimeOffset expirationDate)
 at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
 at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now)
 at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow, Boolean forceRefresh)
```

LD_DEBUG variable shows that the following attempts to load the library are made:

```
 1: find library=System.Security.Cryptography.Native.OpenSsl.so [0]; searching
 1: search cache=/etc/ld.so.cache
 1: search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib (system search path)
 1: trying file=/lib/x86_64-linux-gnu/System.Security.Cryptography.Native.OpenSsl.so
 1: trying file=/usr/lib/x86_64-linux-gnu/System.Security.Cryptography.Native.OpenSsl.so
 1: trying file=/lib/System.Security.Cryptography.Native.OpenSsl.so
 1: trying file=/usr/lib/System.Security.Cryptography.Native.OpenSsl.so
 1: 
 1: find library=libSystem.Security.Cryptography.Native.OpenSsl.so [0]; searching
 1: search cache=/etc/ld.so.cache
 1: search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib (system search path)
 1: trying file=/lib/x86_64-linux-gnu/libSystem.Security.Cryptography.Native.OpenSsl.so
 1: trying file=/usr/lib/x86_64-linux-gnu/libSystem.Security.Cryptography.Native.OpenSsl.so
 1: trying file=/lib/libSystem.Security.Cryptography.Native.OpenSsl.so
 1: trying file=/usr/lib/libSystem.Security.Cryptography.Native.OpenSsl.so
 1: 
 1: find library=System.Security.Cryptography.Native.OpenSsl [0]; searching
 1: search cache=/etc/ld.so.cache
 1: search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib (system search path)
 1: trying file=/lib/x86_64-linux-gnu/System.Security.Cryptography.Native.OpenSsl
 1: trying file=/usr/lib/x86_64-linux-gnu/System.Security.Cryptography.Native.OpenSsl
 1: trying file=/lib/System.Security.Cryptography.Native.OpenSsl
 1: trying file=/usr/lib/System.Security.Cryptography.Native.OpenSsl
 1: 
 1: find library=libSystem.Security.Cryptography.Native.OpenSsl [0]; searching
 1: search cache=/etc/ld.so.cache
 1: search path=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib (system search path)
 1: trying file=/lib/x86_64-linux-gnu/libSystem.Security.Cryptography.Native.OpenSsl
 1: trying file=/usr/lib/x86_64-linux-gnu/libSystem.Security.Cryptography.Native.OpenSsl
 1: trying file=/lib/libSystem.Security.Cryptography.Native.OpenSsl
 1: trying file=/usr/lib/libSystem.Security.Cryptography.Native.OpenSsl
```

### Further technical details

- ASP.NET Core version = 3.1
- Using Visual Studio 2019 v.16.4.4
- dotnet --info

```
.NET Core SDK (reflecting any global.json):
 Version: 3.1.101
 Commit: b377529961
Runtime Environment:
 OS Name: rhel
 OS Version: 7
 OS Platform: Linux
 RID: rhel.7-x64
 Base Path: /opt/rh/rh-dotnet31/root/usr/lib64/dotnet/sdk/3.1.101/
Host (useful for support):
 Version: 3.1.1
 Commit: a1388f194c
.NET Core SDKs installed:
 3.1.101 [/opt/rh/rh-dotnet31/root/usr/lib64/dotnet/sdk]
.NET Core runtimes installed:
 Microsoft.AspNetCore.App 3.1.1 [/opt/rh/rh-dotnet31/root/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
 Microsoft.NETCore.App 3.1.1 [/opt/rh/rh-dotnet31/root/usr/lib64/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@blowdart can you please have a look at this? Thanks!

**Comment by blowdart** [comment]
Not me. Would be a .NET Core issue for @bartonjs probably.

**Comment by bartonjs** [comment]
You're running on rhel.7, but you built for rhel.6.  The way we built for RHEL 6 and RHEL 7+ is very different; perhaps changing the `--runtime` in your publish command will help.

It should look for, and find, the library in/under /opt/rh/rh-dotnet31/root/usr/lib64/dotnet/shared/Microsoft.NETCore.App/

**Comment by Dawsain** [comment]
@bartonjs , thanks for your advise. I tried publishing with --runtime=rhel.7-x64. The exception stopped happening. I was looking for available runtimes at https://docs.microsoft.com/en-us/dotnet/core/rid-catalog#linux-rids and didn't realize there's a much more extensive list at https://github.com/dotnet/runtime/blob/master/src/libraries/pkg/Microsoft.NETCore.Platforms/runtime.json.
