### ISSUE TITLE
Signal R Core Java Client Crashing

### ISSUE THREAD

**Issue by lukasroberts** [dotnet/aspnetcore#18925]
### Describe the bug
When using the Java client SDK for Signal R Core, it crashes intermittently when the socket is closed. Have been observing my logs through Firebase and this issue does occur randomly.

### To Reproduce
Follow the client sample project and ensure you are connecting to a SignalR instance that is hosted in a docker container with both sockets and long polling enabled. Leave the app open for a long period of time, typically greater then 5 minutes. For some reason the app will crash with the following stack trace:

`Fatal Exception: java.lang.RuntimeException
java.net.SocketException: Socket closed`

`com.microsoft.signalr.OkHttpWebSocketWrapper$SignalRWebSocketListener.onFailure (OkHttpWebSocketWrapper.java:97)
okhttp3.internal.ws.RealWebSocket.failWebSocket (RealWebSocket.java:570)
okhttp3.internal.ws.RealWebSocket$1.onResponse (RealWebSocket.java:211)
okhttp3.RealCall$AsyncCall.execute (RealCall.java:174)
okhttp3.internal.NamedRunnable.run (NamedRunnable.java:32)`

I've tracked this down and it looks like the `CompletableSubject` is not having it's error handled correctly, so `closeSubject.onError(new RuntimeException(t));` will just crash the app.

The above is an assumption, but perhaps I'm not setting up an RXJava error handler correctly? If I'm meant to it's not documented clearly as to how this works, or it's intended usage for a project using the library.

### Further technical details
- Client library version: 3.1.0

**Comment by anurse** [comment]
That doesn't seem like intended behavior. @lukasroberts would you be interested in contributing a PR to fix this? (We can take it on from here if not, but if you're interested we'd be happy to take a look!)

> I've tracked this down and it looks like the `CompletableSubject` is not having it's error handled correctly, so `closeSubject.onError(new RuntimeException(t));` will just crash the app.

It seems very odd to me that RxJava would crash the entire process because of an unobserved exception, but to be fair so did .NET Framework (.NET Core no longer does this ;)).

**Comment by anurse** [comment]
@lukasroberts can you provide a runnable sample application that reproduces the problem? We're not confident this is expected behavior and would like to take a deeper look at the code that's triggering it to see if something else may be going on.

**Comment by lukasroberts** [comment]
`import android.content.Context;
import android.content.Intent;
import android.util.Log;

import androidx.localbroadcastmanager.content.LocalBroadcastManager;

import com.microsoft.signalr.HubConnection;
import com.microsoft.signalr.HubConnectionBuilder;

import io.reactivex.Single;
import io.reactivex.internal.functions.Functions;
import io.reactivex.observers.DisposableCompletableObserver;
import io.reactivex.plugins.RxJavaPlugins;

public class ChatSocketService implements IChatSocketService {

    private final IUserService _userService;
    private HubConnection _hubConnection;
    private final Context _context;
    private static final String Path = "api/feed/hubs/feed";

    private static final int HandshakeResponseTimeout = 30 * 1000;

    private static final String TAG = "ChatSocketService";

    private static ChatSocketService _instance;
    public static ChatSocketService getInstance(IUserService userService,
                                                IStringService stringService,
                                                ITimeService timeService,
                                                Context context)
    {
        if(_instance == null)
        {
            _instance = new ChatSocketService(userService, stringService, timeService, context);
        }

        return _instance;
    }

    /**
     * Should not be used - use singleton getInstance()
     */
    private ChatSocketService()
    {
        _userService = null;
        _hubConnection = null;
        _context = null;
    }

    private ChatSocketService(IUserService userService,
                             Context context)
    {
        _context = context;

        if(currentUser != null)
        {
           setupHub(currentUser);
        }
    }

    @Override
    public void connect() {
        User primaryUserAccount = _userService.getPrimaryUserAccount();

        if(primaryUserAccount != null && !primaryUserAccount.refreshTokenExpired && !primaryUserAccount.isLoggedOut()
                && _hubConnection != null)
        {
            _hubConnection.start().subscribe(new DisposableCompletableObserver()
            {
                @Override
                public void onComplete()
                {

                }

                @Override
                public void onError(Throwable e)
                {
                    Log.e(TAG, "onError: " + e.getMessage());
                }
            });
        }
    }

    public void disconnect() {
        if(_hubConnection != null)
        {
            _hubConnection.stop().blockingAwait();
        }
    }

    private void setupHub(User currentUser)
    {
        if(_hubConnection != null)
        {
            _hubConnection.stop().blockingAwait();
        }

        String host = String.format("%s%s", currentUser.domainName, Path);

        _hubConnection = HubConnectionBuilder.create(host)
                .shouldSkipNegotiate(true)
                .withHandshakeResponseTimeout(HandshakeResponseTimeout)
                .withAccessTokenProvider(Single.defer(() -> {
                    String currentAccessToken =_userService.getPrimaryUserAccount().accessToken;
                    return Single.just(currentAccessToken);
                }))
                .build();
        // hub connection code here (on)

        RxJavaPlugins.setErrorHandler(Functions.<Throwable>emptyConsumer());
    }
}`

The above is my code for creating the hub connection on the Java client, the `ChatSocketService` is being created during the initialization of the app with Dagger via dependency injection. Perhaps I need to do the start and stop calls within an `AsyncTask`?

Additionally I stop the hub connection when I background the app and start the hub connection when the app is brought back into the foreground.

Server side we use sticky sessions to maintain the SignalR sessions, and there are load balancers setup in front on the API

**Comment by BrennanConroy** [comment]
@lukasroberts could you provide a **runnable** sample application. The `closeSubject.onError` does look suspicious, unfortunately we are unable to repro the issue so can't investigate possible fixes.

**Comment by lukasroberts** [comment]
@BrennanConroy What sort of things will you be needing? I can give you a sample android project with pretty much the code I showed you above. It'll be impossible for me to link you to the server component that exists. I can however give you a preview of the server side code that we use to set everything up, which is pretty much out of the box.

**Comment by BrennanConroy** [comment]
> I can give you a sample android project with pretty much the code I showed you above

Yes please, we should be able to host a simple server with a mostly empty hub to test the client.

**Comment by lukasroberts** [comment]
@BrennanConroy how would you like me to get this sample repository to you, Pull request?

**Comment by BrennanConroy** [comment]
If you could make a github repository that would be good :)

**Comment by BrennanConroy** [comment]
@lukasroberts have you been able to create a repro app for this issue?

**Comment by jaragones** [comment]
I'm getting a "similar issue" reported to firebase. Android app is using signalR 5.0.0-preview (installed using gradle: implementation 'com.microsoft.signalr:signalr:+'). I couldn't reproduce this issue on my own.

On the library, is there a way to detect broken pipe or when a connection had dropped? 

Error's stack is:

```
Fatal Exception: io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.RuntimeException: javax.net.ssl.SSLException: Write error: ssl=0x765d82cf08: I/O error during system call, Broken pipe
       at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
       at io.reactivex.subjects.CompletableSubject.onError(CompletableSubject.java:131)
       at com.microsoft.signalr.OkHttpWebSocketWrapper$SignalRWebSocketListener.onFailure(OkHttpWebSocketWrapper.java:97)
       at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:570)
       at okhttp3.internal.ws.RealWebSocket.lambda$new$0$RealWebSocket(RealWebSocket.java:161)
       at okhttp3.internal.ws.-$$Lambda$RealWebSocket$vImgSP5IPT4ir3b3bHxPQ53ps8k.run(:2)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

```
Caused by java.lang.RuntimeException: javax.net.ssl.SSLException: Write error: ssl=0x765d82cf08: I/O error during system call, Broken pipe
       at com.microsoft.signalr.OkHttpWebSocketWrapper$SignalRWebSocketListener.onFailure(OkHttpWebSocketWrapper.java:97)
       at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:570)
       at okhttp3.internal.ws.RealWebSocket.lambda$new$0$RealWebSocket(RealWebSocket.java:161)
       at okhttp3.internal.ws.-$$Lambda$RealWebSocket$vImgSP5IPT4ir3b3bHxPQ53ps8k.run(:2)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

```
Caused by javax.net.ssl.SSLException: Write error: ssl=0x765d82cf08: I/O error during system call, Broken pipe
       at com.android.org.conscrypt.NativeCrypto.SSL_write(NativeCrypto.java)
       at com.android.org.conscrypt.NativeSsl.write(NativeSsl.java:426)
       at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLOutputStream.write(ConscryptFileDescriptorSocket.java:660)
       at okio.Okio$1.write(Okio.java:79)
       at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
       at okio.RealBufferedSink.emit(RealBufferedSink.java:186)
       at okhttp3.internal.ws.WebSocketWriter.writeMessageFrame(WebSocketWriter.java:212)
       at okhttp3.internal.ws.WebSocketWriter$FrameSink.close(WebSocketWriter.java:252)
       at okio.RealBufferedSink.close(RealBufferedSink.java:248)
       at okhttp3.internal.ws.RealWebSocket.writeOneFrame(RealWebSocket.java:500)
       at okhttp3.internal.ws.RealWebSocket.lambda$new$0$RealWebSocket(RealWebSocket.java:158)
       at okhttp3.internal.ws.-$$Lambda$RealWebSocket$vImgSP5IPT4ir3b3bHxPQ53ps8k.run(:2)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by lukasroberts** [comment]
@BrennanConroy sorry for the late response.

This issue for me has now been solved, the main problem was that I was creating my SignalR hub on the main thread, as opposed to a background thread.

If anyone has this issue, it's worth ensuring that when you start and stop your hub, it's done on a background thread.

@jaragones your issue looks to be something different, and I'd recommend opening a separate issue for it.

**Comment by lukasroberts** [comment]
Additionally @jaragones there is a way to detect the connection has dropped via `addOnClosedListener `for the hub object itself
