### ISSUE TITLE
Microsoft.AspNetCore.Authentication.AzureAD.UI 3.1.1 causes System.IO.FileNotFoundException: Could not load file or assembly Microsoft.AspNetCore.Razor.Runtime

### ISSUE THREAD

**Issue by yahorsi** [dotnet/aspnetcore#18998]
Hi Guys,

We're developing new SPA using latest .NET Core, today, according to the sample article https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-aspnet-core-webapp we add Microsoft.AspNetCore.Authentication.AzureAD.UI.

And app started crashing on the call to
```C#
services.AddControllers();
```

with exception
```
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Razor.Runtime, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.AspNetCore.Razor.Runtime, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken caCtorToken, MetadataImport& scope, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1& derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   at System.Reflection.RuntimeAssembly.GetCustomAttributes(Type attributeType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType, Boolean inherit)
   at System.Attribute.GetCustomAttribute(Assembly element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](Assembly element)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartFactory.GetApplicationPartFactory(Assembly assembly)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateDefaultParts(String entryAssemblyName)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.GetApplicationPartManager(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddControllersCore(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddControllers(IServiceCollection services)
   at ABB.TeamGate.WebApi.Startup.ConfigureServices(IServiceCollection services) in C:\Dev\1stquad\abb.globalteamgate\Source\ABB.TeamGate.WebApi\Startup.cs:line 53
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at ABB.TeamGate.WebApi.Program.Main(String[] args) in C:\Dev\1stquad\abb.globalteamgate\Source\ABB.TeamGate.WebApi\Program.cs:line 24
```

NOTE: App starts crashing right after adding new package, even if we won't use it anywhere.

Any ideas what we're doing wrong, or that is a bug?

**Comment by yahorsi** [comment]
Linking corresponding forum thread where people got into the same problem

https://forums.asp.net/t/2163206.aspx?Could+not+load+file+or+assembly+Microsoft+AspNetCore+Razor+Runtime+Version+3+1+1+0

**Comment by javiercn** [comment]
@yahorsi thanks for contacting us.

Pranav, do you have any idea of why is this? I would have imagined all these things get compiled coherently, so this should never happen. Am I missing something here?

**Comment by yahorsi** [comment]
The issue got solved after installing the latest .NET Core SDK's, but it frustrates a bit. So far I understand that I do not understand what comes from the SDK and what comes from the NuGet and why I didn't get a compile-time error.

**Comment by javiercn** [comment]
@yahorsi dlls that are part of the shared framework come from the SDK. (The asp.net core FrameworkReference that gets included as part of the SDK). You can look inside your sdk installation under `shared\Microsoft.AspNetCore.App\3.1.1\` to see the list of assemblies. Everything else is a package and you will likely have a package reference on your project file.

I think what happened here is that you updated the package without updating the SDK (which caused the issue).

I'm closing this issue for now, but I'll follow up offline to see what we can do to improve the situation.

**Comment by yahorsi** [comment]
@javiercn thanks for the comments. It would be really helpful in such cases to get some support from the compiler - compile-time error.

btw, what is the right way to install **latest** SDK on Linux? We're using Bitbucket and our own docker image to build the app on the Linux box and so we seem to need to have latest SDK installed.
