### ISSUE TITLE
Kestrel throws Win32Exception: ASN1 bad tag value met when loading a PFX file containing an elliptic curve certificate

### ISSUE THREAD

**Issue by borland** [dotnet/aspnetcore#19091]
### Describe the bug

When I configure Kestrel to use an x509 certificate with an elliptic curve key pair, it fails with the exception `System.ComponentModel.Win32Exception (0x8009310B): ASN1 bad tag value met.`

I am hopeful that this is just a configuration issue and not a bug that requires code changes?

I am launching Kestrel in HTTPS mode, and using a PFX file to specify the certificate+private key that it should use.

My config code is as follows:
```csharp
var host = WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .UseKestrel(options => ConfigureSsl(options, config))
                .Build();
```
```csharp
private static void ConfigureSsl(KestrelServerOptions options, IConfiguration config)
{
    var certificatePath = "orion-prime256v1.pfx";
    var certificatePassword = "secret";

    var httpsOpts = new HttpsConnectionAdapterOptions
    {
        ClientCertificateMode = ClientCertificateMode.AllowCertificate,
        ServerCertificate = new X509Certificate2(certificatePath, certificatePassword),
    };

    ...
    options.Listen(IPAddress.Any, port, listenOptions => {
        listenOptions.UseHttps(httpsOpts);
    });
}
```

Thus far everything had been working perfectly, using a certificate with an RSA2048 keypair.

We're now trying a certificate with an elliptic curve keypair, and kestrel is failing to process requests with the following stacktrace

```
System.ComponentModel.Win32Exception (0x8009310B): ASN1 bad tag value met.
   at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface secModule, String package, CredentialUse intent, SCHANNEL_CRED scc)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCHANNEL_CRED secureCredential)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
   at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint, Byte[] clientHello)
   at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
   at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessAuthentication(LazyAsyncResult lazyResult, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.BeginAuthenticateAsServer(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__69_0(SslServerAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
   at System.Net.Security.SslStream.AuthenticateAsServerAsync(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection.ExecuteAsync()
```

Note: The cert was created using openssl as follows
```
openssl ecparam -name prime256v1 -genkey -param_enc explicit -out private-key.pem
openssl req -new -x509 -key private-key.pem -out server.pem -days 365
openssl pkcs12 -inkey private-key.pem -in server.pem -export -out orion-prime256v1.pfx
```

I am able to load this certificate into the windows certificate store and it appears to be all good and work correctly if I configure it for some other purpose (e.g. IIS), however kestrel doesn't like the PFX file for some reason.

### To Reproduce

Configure kestrel to use HTTPS as above.

Load attached PFX file using password of "secret"
[orion-prime256v1.zip](https://github.com/dotnet/aspnetcore/files/4211991/orion-prime256v1.zip)

### Further technical details
Windows 10 pro version 1909
Visual Studio 2019 pro version 16.4.4
Dotnet core SDK version 3.1.101

CSProj indicates netcoreapp3.1

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
```

Aside: We also have another project which uses aspnetcore2.1 on net472. This experiences the exact same problem when I load that elliptic curve cert, although the kestrel stacktrace is (understandably) different

```
System.ComponentModel.Win32Exception (0x80004005): ASN1 bad tag value met
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter.<InnerOnConnectionAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection.<ApplyConnectionAdaptersAsync>d__56.MoveNext()Microsoft.AspNetCore.Server.Kestrel: Error: Uncaught exception from the OnConnectionAsync method of an IConnectionAdapter.
 @```

**Comment by borland** [comment]
Note: Just for kicks I tried to run this exact same thing on WSL (ubuntu 16.04 with dotnet sdk 3.1.1) using a VSCode WSL launch config:

I get this stacktrace/error in the debugger:

```
Exception thrown: 'Interop.OpenSsl.SslException' in System.Net.Security.dll
Exception thrown: 'System.Security.Authentication.AuthenticationException' in System.Private.CoreLib.dll
Exception thrown: 'System.Security.Authentication.AuthenticationException' in System.Net.Security.dll
Exception thrown: 'System.Security.Authentication.AuthenticationException' in System.Net.Security.dll
Exception thrown: 'System.Security.Authentication.AuthenticationException' in System.Private.CoreLib.dll
Exception thrown: 'System.ObjectDisposedException' in System.Net.Sockets.dll
Exception thrown: 'System.ObjectDisposedException' in System.Private.CoreLib.dll
Exception thrown: 'Interop.OpenSsl.SslException' in System.Net.Security.dll
Exception thrown: 'System.Security.Authentication.AuthenticationException' in System.Private.CoreLib.dll
Exception thrown: 'System.Security.Authentication.AuthenticationException' in System.Net.Security.dll
Exception thrown: 'System.Security.Authentication.AuthenticationException' in System.Net.Security.dll
Exception thrown: 'System.Security.Authentication.AuthenticationException' in System.Private.CoreLib.dll
Exception thrown: 'System.ObjectDisposedException' in System.Net.Sockets.dll
Exception thrown: 'System.ObjectDisposedException' in System.Private.CoreLib.dll
```

```json
{
            "name": ".NET Core WSL Launch",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "publish",
            "program": "/mnt/c/Dev/path/to/myproj/bin/Debug/netcoreapp3.1/myproject.dll",
            "args": [],
            "cwd": "/mnt/c/Dev/path/to/myproj",
            "stopAtEntry": false,
            "console": "internalConsole",
            "justMyCode":false,
            "pipeTransport": {
                "pipeCwd": "${workspaceRoot}",
                "pipeProgram": "bash.exe",
                "pipeArgs": [ "-c" ],
                "debuggerPath": "~/vsdbg/vsdbg"
            }
        }
```
Ref https://stackoverflow.com/questions/53790697/how-can-i-configure-visual-studio-code-to-run-debug-net-dotnet-core-from-the

**Comment by borland** [comment]
Ok, turns out my certificate/pfx was screwed up.

Correct sequence of openssl commands which generates a PFX file which functions correctly is as follows:

```
openssl ecparam -genkey -name prime256v1 -out key.pem
openssl req -new -sha256 -key key.pem -out csr.csr
<enter stuff>
openssl req -x509 -sha256 -days 365 -key key.pem -in csr.csr -out certificate.pem
openssl pkcs12 -export -out ec2.pfx -inkey key.pem -in certificate.pem
```

This EC certificate also works fine on aspnetcore2.1 running on net472

I'll close this ticket but leave it hanging around for search engine juice for future travelers. Sorry for wasting anyone's time
