### ISSUE TITLE
Refactoring in razor file constantly breaks and throws exceptions

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#19158]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/919502/refactoring-in-razor-file-constantly-breaks-and-th.html)._

---
First, the exception:

```
System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.CodeAnalysis.Editor.Implementation.InlineRename.InlineRenameSession.OpenTextBufferManager.OnTextBufferChanged(Object sender, TextContentChangedEventArgs args)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

Gets thrown when I try to rename a property inside @code section of a razor file.

Refactoring in Blazor projects almost doesn't work at all.

To reproduce open a Blazor project, open a razor file and try to rename a property in @code section using F2 shortcut. In my case, the property name is highlighted for a couple of seconds, then the highlighting and refactoring mode is gone suddenly. The interruptions are random and sometimes when I type very very fast I'm actualy able to make the refactoring. To workaround that problem I must either use Replace editor function or use Visual Studio Code to do the refactoring.

Note that the occurance of described problem is random, sometimes it's hard to reproduce shortly after the project file is opened. Sometimes the refactoring seem to work correctly, then it stops working and / or throws exceptions.

I believe the problem is not caused by an extension, because I disabled all code analysis extensions and the problem keeps occuring.

---
#### Visual Studio Feedback System on 2/17/2020, 02:50 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 2/17/2020, 09:47 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We've undertaken a huge effort to improve Razor in general in VS, which will be done by .NET 5.0 release. This will be fixed as part of that effort. Unfortunately, there is no more-granular issue tracking this specific aspect to point you to.
