### ISSUE TITLE
blazor System.ArgumentException: The path must be absolute.  when published with PublishSingleFile

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#19178]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/923443/blazor-systemargumentexception-the-path-must-be-ab.html)._

---
When publishing a blazor web assembly app and asp.net.core and the publishing with PublishSingleFile enabled the following occures on Linux-x64

Steps to repro:
1) Create a new Blazor web assembly hosted by asp.net.core.
2) File Publish and deploy the app to linux x64 (do not check the SingleFilePublish bit)
3) start the app on linux. App runs without problems
4) File publish and deploy the app with the SingleFilePublish bit set
5) start the app on linux. App fails during configuration with the following stack trace.

System.ArgumentException: The path must be absolute. (Parameter 'root')
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.. ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.. ctor(String root)
   at Microsoft.AspNetCore.Builder.BlazorHostingEndpointRouteBuilderExtensions.MapFallbackToClientSideBlazor(IEndpointRouteBuilder endpoints, String clientAssemblyFilePath, String pattern, String filePath)
   at Microsoft.AspNetCore.Builder.BlazorHostingEndpointRouteBuilderExtensions.MapFallbackToClientSideBlazor[TClientApp](IEndpointRouteBuilder endpoints, String filePath)
   at cas. Server.Startup.<>c.<Configure>b__3_0(IEndpointRouteBuilder endpoints)
   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
   at cas. Server.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0. <Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0. <Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0. <Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
Unhandled exception. System.ArgumentException: The path must be absolute. (Parameter 'root')
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.. ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.. ctor(String root)
   at Microsoft.AspNetCore.Builder.BlazorHostingEndpointRouteBuilderExtensions.MapFallbackToClientSideBlazor(IEndpointRouteBuilder endpoints, String clientAssemblyFilePath, String pattern, String filePath)
   at Microsoft.AspNetCore.Builder.BlazorHostingEndpointRouteBuilderExtensions.MapFallbackToClientSideBlazor[TClientApp](IEndpointRouteBuilder endpoints, String filePath)
   at cas. Server.Startup.<>c.<Configure>b__3_0(IEndpointRouteBuilder endpoints)
   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
   at cas. Server.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0. <Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0. <Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0. <Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at cas. Server.Program.Main(String[] args)

---
#### Visual Studio Feedback System on 2/19/2020, 03:54 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

I believe this is one of the issues we've fixed with the release 3.1.102 of the SDK. Update to that version and tell us if it still doesn't work.

**Comment by MagoDopado** [comment]
I have the exact same problem with dotnet 3.1.102 publishing the example app with
`dotnet publish -c Release --self-contained -r linux-x64 /p:PublishSingleFile=true -o ./app/publish/`

```
Application startup exception: System.ArgumentException: The path must be absolute. (Parameter 'root')
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.AspNetCore.Builder.BlazorHostingEndpointRouteBuilderExtensions.MapFallbackToClientSideBlazor(IEndpointRouteBuilder endpoints, String clientAssemblyFilePath, String pattern, String filePath)
   at Microsoft.AspNetCore.Builder.BlazorHostingEndpointRouteBuilderExtensions.MapFallbackToClientSideBlazor[TClientApp](IEndpointRouteBuilder endpoints, String filePath)
   at WasmExample.Server.Startup.<>c.<Configure>b__1_0(IEndpointRouteBuilder endpoints)
   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
   at WasmExample.Server.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.WebHost[6]
      Application startup exception
System.ArgumentException: The path must be absolute. (Parameter 'root')
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.AspNetCore.Builder.BlazorHostingEndpointRouteBuilderExtensions.MapFallbackToClientSideBlazor(IEndpointRouteBuilder endpoints, String clientAssemblyFilePath, String pattern, String filePath)
   at Microsoft.AspNetCore.Builder.BlazorHostingEndpointRouteBuilderExtensions.MapFallbackToClientSideBlazor[TClientApp](IEndpointRouteBuilder endpoints, String filePath)
   at WasmExample.Server.Startup.<>c.<Configure>b__1_0(IEndpointRouteBuilder endpoints)
   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
   at WasmExample.Server.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
Unhandled exception. System.ArgumentException: The path must be absolute. (Parameter 'root')
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.AspNetCore.Builder.BlazorHostingEndpointRouteBuilderExtensions.MapFallbackToClientSideBlazor(IEndpointRouteBuilder endpoints, String clientAssemblyFilePath, String pattern, String filePath)
   at Microsoft.AspNetCore.Builder.BlazorHostingEndpointRouteBuilderExtensions.MapFallbackToClientSideBlazor[TClientApp](IEndpointRouteBuilder endpoints, String filePath)
   at WasmExample.Server.Startup.<>c.<Configure>b__1_0(IEndpointRouteBuilder endpoints)
   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
   at WasmExample.Server.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at WasmExample.Server.Program.Main(String[] args)
Aborted (core dumped)
```

Publish folder tree
```
.
├── WasmExample.Client
│   └── dist
│       ├── css
│       │   ├── bootstrap
│       │   │   ├── bootstrap.min.css
│       │   │   └── bootstrap.min.css.map
│       │   ├── open-iconic
│       │   │   ├── font
│       │   │   │   ├── css
│       │   │   │   │   └── open-iconic-bootstrap.min.css
│       │   │   │   └── fonts
│       │   │   │       ├── open-iconic.eot
│       │   │   │       ├── open-iconic.otf
│       │   │   │       ├── open-iconic.svg
│       │   │   │       ├── open-iconic.ttf
│       │   │   │       └── open-iconic.woff
│       │   │   ├── FONT-LICENSE
│       │   │   ├── ICON-LICENSE
│       │   │   └── README.md
│       │   └── site.css
│       └── index.html
├── WasmExample.Server
├── WasmExample.Server.pdb
└── web.config
```` 

Is there something else needed to fix this problem?

**Comment by javiercn** [comment]
Hi. 
 
**It looks like you are posting on a closed issue!**

We're very likely to lose track of your bug/feedback/question unless you: 
1. Open a new issue 
2. Explain very clearly what you need help with 
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem
