### ISSUE TITLE
Share authentication cookie between two sites produces exception caused by ISecurityStampValidator is missing

### ISSUE THREAD

**Issue by marcuslindblom** [dotnet/aspnetcore#19290]
I have one API and one frontend app where I share the data protection keys using the file system. This is how my apps is configured.

**Frontend**:

```c#
public void ConfigureServices(IServiceCollection services)
{
services
    .AddDataProtection()
        .SetApplicationName("SharedCookieApp")
        .PersistKeysToFileSystem(new DirectoryInfo("/dataprotection"));

services
    .AddAuthentication(options =>
    {
        options.DefaultScheme = IdentityConstants.ApplicationScheme;
        options.DefaultSignInScheme = IdentityConstants.ExternalScheme;
    })
    .AddOAuth("GitHub", "GitHub", o => { ... })
    .AddIdentityCookies(options =>
    {
        options.ApplicationCookie.Configure(o =>
        {
            o.Cookie.Name = ".AspNet.SharedCookie";
            o.Cookie.Domain = ".example.app";
            o.LoginPath = new PathString("/Account/Login/");
            o.AccessDeniedPath = new PathString("/Account/Forbidden/");
        });
    });
services.AddIdentityCore<User>(options =>
{
  options.Password.RequireDigit = true;
  options.Password.RequiredLength = 8;
  options.Password.RequireNonAlphanumeric = false;
  options.Password.RequireUppercase = true;
  options.Password.RequireLowercase = true;
})
.AddRoles<Raven.Identity.IdentityRole>()
.AddRoleStore<RoleStore<Raven.Identity.IdentityRole>>()
.AddUserStore<UserStore<User, Raven.Identity.IdentityRole>>()
.AddSignInManager();
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
      if (env.IsDevelopment())
      {
        app.UseDeveloperExceptionPage();
      }

      app.UseForwardedHeaders();

      app.UseRouting();

      app.UseCookiePolicy();

      app.UseAuthentication();

      app.UseAuthorization();

    ...
}
```

And from the API I need to use the authorize attribute to make sure that the user is authenticated when making a request.

**API**:

```c#
    public void ConfigureServices(IServiceCollection services)
    {
      services.AddDataProtection()
          .SetApplicationName("SharedCookieApp")
          .PersistKeysToFileSystem(new DirectoryInfo("/dataprotection"));

      services.AddAuthentication(options =>
      {
        options.DefaultScheme = IdentityConstants.ApplicationScheme;
      })
      .AddIdentityCookies(options =>
      {
        options.ApplicationCookie.Configure(a =>
        {
          a.Cookie.Name = ".AspNet.SharedCookie";
          a.Cookie.Domain = ".example.app";
        });
      });

      services.AddControllers();
    }

    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
    {
      if (env.IsDevelopment())
      {
        app.UseDeveloperExceptionPage();
      }

      app.UseHttpsRedirection();

      app.UseCookiePolicy();

      app.UseAuthentication();

      app.UseRouting();

      app.UseAuthorization();

      app.UseEndpoints(endpoints =>
      {
        endpoints.MapControllers();
      });
    }
```

The authentication works correct but when I try to access the api I get the following exception.

```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLTP6L6AV4FV", Request id "0HLTP6L6AV4FV:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: No service for type 'Microsoft.AspNetCore.Identity.ISecurityStampValidator' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Identity.SecurityStampValidator.ValidateAsync[TValidator](CookieValidatePrincipalContext context)
   at Microsoft.AspNetCore.Identity.SecurityStampValidator.ValidatePrincipalAsync(CookieValidatePrincipalContext context)
   at Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationEvents.ValidatePrincipal(CookieValidatePrincipalContext context)
   at Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

I can't figure out what the problem is so I appreciate all the help I can get.

**Comment by blowdart** [comment]
You're not adding identity to your api app, only the cookie parts. So when it goes to validate the security stamp none of the things it needs are registered. So copy the 

```
services.AddIdentityCore<User>(options =>
{
  options.Password.RequireDigit = true;
  options.Password.RequiredLength = 8;
  options.Password.RequireNonAlphanumeric = false;
  options.Password.RequireUppercase = true;
  options.Password.RequireLowercase = true;
})
.AddRoles<Raven.Identity.IdentityRole>()
.AddRoleStore<RoleStore<Raven.Identity.IdentityRole>>()
.AddUserStore<UserStore<User, Raven.Identity.IdentityRole>>()
.AddSignInManager();
```

into your api, or better yet consider options other than cookie authentication to apis, such as jwt via identity server.

**Comment by marcuslindblom** [comment]
I actually found something like this to play nice with my needs. I agree about the jwt option and I actually implementing this as well.

```
services.AddDataProtection()
    .PersistKeysToFileSystem("{PATH TO COMMON KEY RING FOLDER}")
    .SetApplicationName("SharedCookieApp");

services.AddAuthentication("Identity.Application")
    .AddCookie("Identity.Application", options =>
    {
        options.Cookie.Name = ".AspNet.SharedCookie";
    });
```

**Comment by blowdart** [comment]
That works too :) But it's limited somewhat in that the cookie will never get refreshed in your api, so if the security stamp rolls because user details changed your api wouldn't invalidate it. This prohably isn't a big concern because JWT would have the same behaviour.

**Comment by marcuslindblom** [comment]
Ok, thanks for all the help! 🙏
