### ISSUE TITLE
Microsoft.AspNetCore.Razor.Runtime Not Found

### ISSUE THREAD

**Issue by quantumandcode** [dotnet/aspnetcore#19341]
Microsoft.AspNetCore.Razor.Runtime

# General

Deploying to Azure Web App for Linux, using a dotnet core mvc 3.1 app with individual auth. I get this error when I 'deploy to web app' using the vs code azure web app extension. 

I am currently working on Ubuntu 18.04

I also have the problem with Microsoft.AspNetCore.Razor.Runtime Not Found when I run 'dotnet add package' as it installs version 2.2, if I declare version 3.1 then it cannot find it. I found in the docs for migration that this package is now on Microsoft.AspNetCore.Mvc.Razor (https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#update-the-project-file)

Below is the stack trace from https://***.scm.azurewebsites.net/api/logstream

2020-02-16T21:50:44.064993315Z Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Razor.Runtime, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
2020-02-16T21:50:44.065040415Z 
2020-02-16T21:50:44.065045615Z File name: 'Microsoft.AspNetCore.Razor.Runtime, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
2020-02-16T21:50:44.065050115Z    at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
2020-02-16T21:50:44.065054615Z    at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
2020-02-16T21:50:44.065059415Z    at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken caCtorToken, MetadataImport& scope, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1& derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
2020-02-16T21:50:44.065066415Z    at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
2020-02-16T21:50:44.065077015Z    at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType)
2020-02-16T21:50:44.065081415Z    at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
2020-02-16T21:50:44.065085615Z    at System.Reflection.RuntimeAssembly.GetCustomAttributes(Type attributeType, Boolean inherit)
2020-02-16T21:50:44.065089615Z    at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType, Boolean inherit)
2020-02-16T21:50:44.065093715Z    at System.Attribute.GetCustomAttribute(Assembly element, Type attributeType, Boolean inherit)
2020-02-16T21:50:44.065097715Z    at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](Assembly element)
2020-02-16T21:50:44.065101815Z    at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartFactory.GetApplicationPartFactory(Assembly assembly)
2020-02-16T21:50:44.065106515Z    at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateDefaultParts(String entryAssemblyName)
2020-02-16T21:50:44.065110815Z    at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.GetApplicationPartManager(IServiceCollection services)
2020-02-16T21:50:44.065114815Z    at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection services)
2020-02-16T21:50:44.065118915Z    at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddControllersCore(IServiceCollection services)
2020-02-16T21:50:44.065123115Z    at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddControllersWithViewsCore(IServiceCollection services)
2020-02-16T21:50:44.065127115Z    at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddControllersWithViews(IServiceCollection services)
2020-02-16T21:50:44.065131115Z    at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services)
2020-02-16T21:50:44.065135115Z    at Microsoft.AspNetCore.Identity.IdentityBuilderUIExtensions.AddRelatedParts(IdentityBuilder builder)
2020-02-16T21:50:44.065139115Z    at Microsoft.AspNetCore.Identity.IdentityBuilderUIExtensions.AddDefaultUI(IdentityBuilder builder)
2020-02-16T21:50:44.065143115Z    at Microsoft.Extensions.DependencyInjection.IdentityServiceCollectionUIExtensions.AddDefaultIdentity[TUser](IServiceCollection services, Action`1 configureOptions)
2020-02-16T21:50:44.065147515Z    at BlogSite.Startup.ConfigureServices(IServiceCollection services) in /home/jonathan/Documents/QuantumAndCode/BlogSite/Startup.cs:line 45
2020-02-16T21:50:44.065152715Z    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
2020-02-16T21:50:44.065156815Z    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2020-02-16T21:50:44.065163316Z    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
2020-02-16T21:50:44.065167416Z    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
2020-02-16T21:50:44.065171816Z    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
2020-02-16T21:50:44.065176116Z    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
2020-02-16T21:50:44.065180416Z    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
2020-02-16T21:50:44.065184516Z    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
2020-02-16T21:50:44.065188716Z    at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
2020-02-16T21:50:44.065192816Z    at Microsoft.Extensions.Hosting.HostBuilder.Build()
2020-02-16T21:50:44.065196716Z    at BlogSite.Program.Main(String[] args) in /home/jonathan/Documents/QuantumAndCode/BlogSite/Program.cs:line 16
2020-02-16T21:50:44.065200716Z 
2020-02-16T21:50:44.072061650Z 
2020-02-16T21:50:44.085294515Z ptrace(ATTACH, 29) FAILED Operation not permitted
2020-02-16T21:50:44.091847848Z Writing minidump with heap to file /home/logs/dumps/coredump.ac8e0a6c0676.29.1581889841
2020-02-16T21:50:44.454752750Z /opt/startup/startup.sh: line 12:    29 Aborted                 (core dumped) dotnet "BlogSite.dll"

**Comment by mkArtakMSFT** [comment]
As per @benaadams 's suggestion, that's the issue you're facing.
