### ISSUE TITLE
Flaky test: Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.InteropReliabilityTests.ContinuesWorkingAfterInvalidAsyncReturnCallback

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#19410]
```
Microsoft.AspNetCore.SignalR.HubException : Unable to complete handshake with the server due to an error: Handshake was canceled.
Stack trace
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.HandshakeAsync(ConnectionState startingConnectionState, CancellationToken cancellationToken) in /_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:line 1057
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken) in /_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:line 433
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken) in /_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:line 441
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken) in /_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:line 255
   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult() in /_/src/SignalR/common/Shared/ForceAsyncAwaiter.cs:line 40
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken) in /_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:line 232
   at Ignitor.BlazorClient.ConnectAsync(Uri uri, Boolean connectAutomatically) in /_/src/Components/Ignitor/src/BlazorClient.cs:line 359
   at Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.InteropReliabilityTests.InitializeAsync() in /_/src/Components/test/E2ETest/ServerExecutionTests/InteropReliabilityTests.cs:line 31
   at Microsoft.AspNetCore.Components.IgnitorTest`1.Xunit.IAsyncLifetime.InitializeAsync() in /_/src/Components/test/E2ETest/ServerExecutionTests/IgnitorTest.cs:line 73
```

Console logs:
```
| [2020-02-24T17:43:55] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Registering handler for client method 'JS.AttachComponent'.
| [2020-02-24T17:43:55] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Registering handler for client method 'JS.BeginInvokeJS'.
| [2020-02-24T17:43:55] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Registering handler for client method 'JS.EndInvokeDotNet'.
| [2020-02-24T17:43:55] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Registering handler for client method 'JS.RenderBatch'.
| [2020-02-24T17:43:55] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Registering handler for client method 'JS.Error'.
| [2020-02-24T17:43:55] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Waiting on Connection Lock in StartAsyncInner (/_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:238).
| [2020-02-24T17:43:55] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: The HubConnection is attempting to transition from the Disconnected state to the Connecting state.
| [2020-02-24T17:43:55] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Starting HubConnection.
| [2020-02-24T17:43:55] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Starting HttpConnection.
| [2020-02-24T17:43:55] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Establishing connection with server at 'http://127.0.0.1:52366/subdir/_blazor'.
| [2020-02-24T17:43:55] Microsoft.AspNetCore.Http.Connections.Client.Internal.LoggingHttpMessageHandler Trace: Sending HTTP request POST 'http://127.0.0.1:52366/subdir/_blazor/negotiate?negotiateVersion=1'.
Information: RequestStarting Request starting HTTP/1.1 POST http://127.0.0.1:52366/subdir/_blazor/negotiate?negotiateVersion=1 - 0
Information: ExecutingEndpoint Executing endpoint '/_blazor/negotiate'
Information: ExecutedEndpoint Executed endpoint '/_blazor/negotiate'
Information: RequestFinished Request finished HTTP/1.1 POST http://127.0.0.1:52366/subdir/_blazor/negotiate?negotiateVersion=1 - 0 - 200 316 application/json 0.2046ms
| [2020-02-24T17:43:58] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Established connection 'LP_xJ-3Y_BGMYYaCYlLQjQ' with the server.
| [2020-02-24T17:43:58] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Starting transport 'WebSockets' with Url: http://127.0.0.1:52366/subdir/_blazor.
| [2020-02-24T17:43:58] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Information: Starting transport. Transfer mode: Binary. Url: 'ws://127.0.0.1:52366/subdir/_blazor?id=jUfv1H8E9AY60uKMvoSWMA'.
Information: RequestStarting Request starting HTTP/1.1 GET http://127.0.0.1:52366/subdir/_blazor?id=jUfv1H8E9AY60uKMvoSWMA - -
Information: ExecutingEndpoint Executing endpoint '/_blazor'
| [2020-02-24T17:44:00] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Started transport.
| [2020-02-24T17:44:00] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Transport 'WebSockets' started.
| [2020-02-24T17:44:00] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: HttpConnection Started.
| [2020-02-24T17:44:15] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: Using HubProtocol 'blazorpack v1'.
| [2020-02-24T17:44:15] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending Hub Handshake.
| [2020-02-24T17:44:15] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Received message from application. Payload size: 38.
Information: ExecutedEndpoint Executed endpoint '/_blazor'
Information: RequestFinished Request finished HTTP/1.1 GET http://127.0.0.1:52366/subdir/_blazor?id=jUfv1H8E9AY60uKMvoSWMA - - - 101 - - 17410.2028ms
| [2020-02-24T17:44:15] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Message received. Type: Text, size: 36, EndOfMessage: True.
| [2020-02-24T17:44:15] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Information: WebSocket closed by the server. Close status NormalClosure.
| [2020-02-24T17:44:15] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Receive loop stopped.
| [2020-02-24T17:44:15] Microsoft.AspNetCore.SignalR.Client.HubConnection Error: Server returned handshake error: Handshake was canceled.
| [2020-02-24T17:44:15] Microsoft.AspNetCore.SignalR.Client.HubConnection Error: Error starting connection.
| Microsoft.AspNetCore.SignalR.HubException: Unable to complete handshake with the server due to an error: Handshake was canceled.
|    at Microsoft.AspNetCore.SignalR.Client.HubConnection.HandshakeAsync(ConnectionState startingConnectionState, CancellationToken cancellationToken) in /_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:line 1057
|    at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken) in /_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:line 433
| [2020-02-24T17:44:15] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Disposing HttpConnection.
| [2020-02-24T17:44:15] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Information: Transport is stopping.
| [2020-02-24T17:44:15] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Send loop stopped.
| [2020-02-24T17:44:21] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Transport stopped.
| [2020-02-24T17:44:21] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: HttpConnection Disposed.
| [2020-02-24T17:44:21] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: The HubConnection is attempting to transition from the Connecting state to the Disconnected state.
| [2020-02-24T17:44:21] Microsoft.AspNetCore.SignalR.Client.HubConnection Trace: Releasing Connection Lock in StartAsyncInner (/_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:271).
Showing filters 1 
```

**Comment by Pilchie** [comment]
Starting with Blazor, since that was the test is. Could also be SignalR...

**Comment by pranavkm** [comment]
@javiercn did a bunch of work in improving the reliability of the SignalR-specific tests as part of https://github.com/dotnet/aspnetcore/commit/a9d702624a02ad4ebf593d9bf9c1c69f5702a6f5. The tests are still quarantined, we'll rely on the regular DOI process to unquarantine it.
