### ISSUE TITLE
[Flaky test] Microsoft.AspNetCore.Components.E2ETest.Tests.ServerComponentRenderingTest.CanDispatchAsyncWorkToSyncContext

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#19413]
```
OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: First Second Third Fourth Fifth
Actual: First Third Second Fourth Fifth
 at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer1 comparer) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\EqualityAsserts.cs:line 40
 at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 74
 at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass16_01.<WaitAssertCore>b__0(IWebDriver ) in //src/Shared/E2ETesting/WaitAssert.cs:line 100
Screen shot captured at 'F:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.AspNetCore.Components.E2ETests\ffc965db3a5543769a0d18c0fc6979a5.png'
Encountered browser errors
[2020-02-24T18:55:43Z] [Info] http://127.0.0.1:53627/subdir/_framework/blazor.server.js 0:5359 "[2020-02-24T18:55:43.182Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:53627/subdir/_blazor'."
[2020-02-24T18:55:43Z] [Info] http://127.0.0.1:53627/subdir 40:16 "Blazor server-side"
[2020-02-24T18:55:43Z] [Info] http://127.0.0.1:53627/subdir/_framework/blazor.server.js 0:5359 "[2020-02-24T18:55:43.213Z] Information: WebSocket connected to ws://127.0.0.1:53627/subdir/_blazor?id=Ry9n2ACm2uMoxx1gpL9GKw."
[2020-02-24T18:56:34Z] [Info] http://127.0.0.1:53627/subdir/_framework/blazor.server.js 0:5359 "[2020-02-24T18:56:34.626Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:53627/subdir/_blazor'."
[2020-02-24T18:56:34Z] [Info] http://127.0.0.1:53627/subdir 40:16 "Blazor server-side"
[2020-02-24T18:56:34Z] [Info] http://127.0.0.1:53627/subdir/_framework/blazor.server.js 0:5359 "[2020-02-24T18:56:34.654Z] Information: WebSocket connected to ws://127.0.0.1:53627/subdir/_blazor?id=PET4EBDBBhrHEMRGjB0kiQ."
[2020-02-24T18:56:48Z] [Info] http://127.0.0.1:53627/subdir/_framework/blazor.server.js 0:5359 "[2020-02-24T18:56:48.254Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:53627/subdir/_blazor'."
[2020-02-24T18:56:48Z] [Info] http://127.0.0.1:53627/subdir 40:16 "Blazor server-side"
[2020-02-24T18:56:48Z] [Info] http://127.0.0.1:53627/subdir/_framework/blazor.server.js 0:5359 "[2020-02-24T18:56:48.265Z] Information: WebSocket connected to ws://127.0.0.1:53627/subdir/_blazor?id=d65jH65Sn0IFiEq46GfW1w."
[2020-02-24T18:57:00Z] [Info] http://127.0.0.1:53627/subdir/_framework/blazor.server.js 0:5359 "[2020-02-24T18:57:00.170Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:53627/subdir/_blazor'."
[2020-02-24T18:57:00Z] [Info] http://127.0.0.1:53627/subdir 40:16 "Blazor server-side"
[2020-02-24T18:57:00Z] [Info] http://127.0.0.1:53627/subdir/_framework/blazor.server.js 0:5359 "[2020-02-24T18:57:00.180Z] Information: WebSocket connected to ws://127.0.0.1:53627/subdir/_blazor?id=vTsyJjvIft0oTdf4_tmxEQ."
[2020-02-24T18:57:09Z] [Info] http://127.0.0.1:53627/subdir/_framework/blazor.server.js 0:5359 "[2020-02-24T18:57:09.872Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:53627/subdir/_blazor'."
[2020-02-24T18:57:09Z] [Info] http://127.0.0.1:53627/subdir 40:16 "Blazor server-side"
[2020-02-24T18:57:09Z] [Info] http://127.0.0.1:53627/subdir/_framework/blazor.server.js 0:5359 "[2020-02-24T18:57:09.884Z] Information: WebSocket connected to ws://127.0.0.1:53627/subdir/_blazor?id=GGGDWY1bGOM_hXxWaDf3IA."
[2020-02-24T18:57:17Z] [Info] http://127.0.0.1:53627/subdir/_framework/blazor.server.js 0:5359 "[2020-02-24T18:57:17.044Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:53627/subdir/_blazor'."
[2020-02-24T18:57:17Z] [Info] http://127.0.0.1:53627/subdir 40:16 "Blazor server-side"
[2020-02-24T18:57:17Z] [Info] http://127.0.0.1:53627/subdir/_framework/blazor.server.js 0:5359 "[2020-02-24T18:57:17.057Z] Information: WebSocket connected to ws://127.0.0.1:53627/subdir/_blazor?id=
```

**Comment by pranavkm** [comment]
We'll need to instrument the dispatcher to figure out what's going on here. The test assumes no other work is queued to the dispatcher as part of running the test which might not be always true.

**Comment by BrennanConroy** [comment]
Still flaky
```
OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: First Second Third Fourth Fifth
Actual:   First Third Second Fourth Fifth
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer1 comparer) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\EqualityAsserts.cs:line 40
 at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 83
 at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_01.<WaitAssertCore>b__0(IWebDriver ) in //src/Shared/E2ETesting/WaitAssert.cs:line 109
Screen shot captured at 'D:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.AspNetCore.Components.E2ETests\24525eb4da9a4fa39ab4a6b4b176b92e.png'
Encountered browser errors
[2021-05-21T13:22:00Z] [Info] http://127.0.0.1:51588/subdir/_framework/blazor.server.js 0:31762 "[2021-05-21T13:22:00.001Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:51588/subdir/_blazor'."
[2021-05-21T13:22:00Z] [Info] http://127.0.0.1:51588/subdir 45:16 "Blazor server-side"
[2021-05-21T13:22:00Z] [Info] http://127.0.0.1:51588/subdir/_framework/blazor.server.js 0:31762 "[2021-05-21T13:22:00.086Z] Information: WebSocket connected to ws://127.0.0.1:51588/subdir/_blazor?id=f58GTJE48IqyCgJlYUjafQ."Page content:
<head>
    <meta charset="utf-8">
    <title>Basic test app</title>
    <base href="/subdir/">
    <link href="style.css" rel="stylesheet">
    <link rel="icon" href="data:,">

    
    <link href="_content/TestContentPackage/styles.css" rel="stylesheet">
    <link href="Components.TestServer.styles.css" rel="stylesheet">
</head>
<body>
    <root><div id="test-selector">
    Select test:
    <select id="test-selector-select"><option value="none">Choose...
        <option value="BasicTestApp.AfterRenderInteropComponent">After-render interop component
        <option value="BasicTestApp.AuthTest.AuthRouter">Auth cases
        <option value="BasicTestApp.BindCasesComponent">bind cases
        <option value="BasicTestApp.ComponentRefComponent">Component ref component
        <option value="BasicTestApp.ConfigurationComponent">Configuration
        <option value="BasicTestApp.CounterComponent">Counter
        <option value="BasicTestApp.CounterComponentWrapper">Counter wrapped in parent
```

https://dev.azure.com/dnceng/public/_build/results?buildId=1149900&view=ms.vss-test-web.build-test-results-tab&runId=34782128&paneView=debug&resultId=100061
