### ISSUE TITLE
ASP.NET Core 2.2 can resolve registered partially-closed generic types, but ASP.NET Core 3.1 throws System.ArgumentException

### ISSUE THREAD

**Issue by Jalalx** [dotnet/aspnetcore#19507]
ASP.NET Core 2.2 can resolve registered partially-closed generic types, but ASP.NET Core 3.1 will throw `System.ArgumentException` exception.

Sample Repo: https://github.com/Jalalx/ServiceProviderClosedPartialTypeSupport

### To Reproduce
``` C#
class Program
    {
        static void Main(string[] args)
        {
            var provider = new ServiceCollection()
                .AddSingleton(typeof(Service<>), typeof(Service2<>))
                .BuildServiceProvider();

            // This will throw ArgumentException in Microsoft.Extensions.DependencyInjection 
            // version 3.1.2 but works fine in version 2.2
            var service2 = provider.GetService(typeof(Service<Status>));

            Console.WriteLine("Hello World!");
        }
    }

    public enum Status { Pending, Done }

    public class Service<TEnum> where TEnum : Enum
    {
        public TEnum Status { get; set; }
    }

    public class Service2<TEnum> where TEnum : Enum
    {
        public TEnum Status { get; set; }
    }
```

Exception details:
```
System.ArgumentException
  HResult=0x80070057
  Message=Implementation type 'ServiceResolveSample2._2.Service2`1[ServiceResolveSample2._2.Status]' can't be converted to service type 'ServiceResolveSample2._2.Service`1[ServiceResolveSample2._2.Status]'
  Source=Microsoft.Extensions.DependencyInjection
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite..ctor(ResultCache cache, Type serviceType, ConstructorInfo constructorInfo, ServiceCallSite[] parameterCallSites)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateOpenGeneric(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateOpenGeneric(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.<>c__DisplayClass7_0.<GetCallSite>b__0(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at ServiceResolveSample2._2.Program.Main(String[] args) in C:\Projects\AspNetCoreClosedPartialTypeSupport\ServiceResolveSample3.1\Program.cs:line 14
```

### Expectation:
Works as before like ASP.NET 2.2

### Further technical details
```ps
PS C:\> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.102\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by Jalalx** [comment]
Oops! I think this should be moved to [dotnet/extensions](https://github.com/dotnet/extensions/issues) 😜

**Comment by Jalalx** [comment]
Moved here: https://github.com/dotnet/extensions/issues/3048
