### ISSUE TITLE
Bug: AddCommandLine(args, switchMappings) System.FormatException: The short switch '-k1=value1' is not defined in the switch mappings.

### ISSUE THREAD

**Issue by Rick-Anderson** [dotnet/aspnetcore#19537]
Code from [CommandLineConfigurationExtensions.AddCommandLine Method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.commandlineconfigurationextensions.addcommandline?view=dotnet-plat-ext-3.1)

```
dotnet --version
3.1.101
```

To repo:

```
dotnet new web -o swithMap
cd swithMap
// Replace main with the following code from the doc page
public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args)
        {
            var switchMappings = new Dictionary<string, string>()
             {
                 { "-k1", "key1" },
                 { "-k2", "key2" },
                 { "--alt3", "key3" },
                 { "--alt4", "key4" },
                 { "--alt5", "key5" },
                 { "--alt6", "key6" },
             };

            return Host.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration((hostingContext, config) =>
                {
                    config.AddCommandLine(args, switchMappings);
                })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
        }
    }
/// End of code
// Per the doc page, run the following command
dotnet run -k1=value1 -k2 value2 --alt3=value2 /alt4=value3 --alt5 value5 /alt6 value6

Unhandled exception. System.FormatException: The short switch '-k1=value1' is not defined in the switch mappings.
   at Microsoft.Extensions.Configuration.CommandLine.CommandLineConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildHostConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at swithMap.Program.Main(String[] args) in C:\tmp\swithMap\Program.cs:line 16

/// = works with --
// The following command works
dotnet run -k1 value1 -k2 value2 --alt3=value2 /alt4=value3 --alt5 value5 /alt6 value6
```

**Comment by javiercn** [comment]
Thanks @Rick-Anderson.

@anurse who's the right person to look at this? (Is platform the right place to put it?)

**Comment by anurse** [comment]
This is in Configuration, should be in dotnet/extensions. Transferring now.
