### ISSUE TITLE
Problem with AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler in signin-oidc in ubuntu 18

### ISSUE THREAD

**Issue by xrkolovos** [dotnet/aspnetcore#19700]
There are 2 apps in asp.net core 3.1.1, running in Ubuntu 18.04, behind nginx.

### Describe the bug
Calling signin-oidc fails(504 Gateway Time-out) the first time. And works the second time that try again to login (The second time we are logged in). This url is called after redirect to an asp.net core mvc website (App1) from an Identity Server website(App2) for OpenId login purposes.

Logs
 ```
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
Mar 09 13:07:21 egritoslinux dotnet-app[41176]:  ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
Mar 09 13:07:21 applinux dotnet-app[41176]:  ---> System.Net.Sockets.SocketException (125): Operation canceled
Mar 09 13:07:21 applinux dotnet-app[41176]:    --- End of inner exception stack trace ---
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.HttpConnection.FillAsync()
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
Mar 09 13:07:21 applinux dotnet-app[41176]:    --- End of inner exception stack trace ---
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RedeemAuthorizationCodeAsync(OpenIdConnectMessage tokenEndpointRequest)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
Mar 09 13:07:21 applinux dotnet-app[41176]: 13:07:21 Error | Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler | 0HLU44L6UB6V1:00000001 - Exception occurred while processing message.
Mar 09 13:07:21 applinux dotnet-app[41176]: System.Threading.Tasks.TaskCanceledException: The operation was canceled.
Mar 09 13:07:21 applinux dotnet-app[41176]:  ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
Mar 09 13:07:21 applinux dotnet-app[41176]:  ---> System.Net.Sockets.SocketException (125): Operation canceled
Mar 09 13:07:21 applinux dotnet-app[41176]:    --- End of inner exception stack trace ---
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.HttpConnection.FillAsync()
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
Mar 09 13:07:21 applinux dotnet-app[41176]:    --- End of inner exception stack trace ---
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RedeemAuthorizationCodeAsync(OpenIdConnectMessage tokenEndpointRequest)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
Mar 09 13:07:21 applinux dotnet-app[41176]: fail: OurApp.WebMvcUICore.Middlewares.ErrorWrappingMiddleware[0]
Mar 09 13:07:21 applinux dotnet-app[41176]:       An error was encountered while handling the remote login.The operation was canceled.Unable to read data from the transport connection: Operation canceled.Operation canceled
Mar 09 13:07:21 applinux dotnet-app[41176]: System.Exception: An error was encountered while handling the remote login.
Mar 09 13:07:21 applinux dotnet-app[41176]:  ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
Mar 09 13:07:21 applinux dotnet-app[41176]:  ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
Mar 09 13:07:21 applinux dotnet-app[41176]:  ---> System.Net.Sockets.SocketException (125): Operation canceled
Mar 09 13:07:21 applinux dotnet-app[41176]:    --- End of inner exception stack trace ---
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.HttpConnection.FillAsync()
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
Mar 09 13:07:21 applinux dotnet-app[41176]:    --- End of inner exception stack trace ---
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RedeemAuthorizationCodeAsync(OpenIdConnectMessage tokenEndpointRequest)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
Mar 09 13:07:21 applinux dotnet-app[41176]:    --- End of inner exception stack trace ---
Mar 09 13:07:21 applinux dotnet-app[41176]:    at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
Mar 09 13:07:21 applinux dotnet-app[41176]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at OurApp.WebMvcUICore.Middlewares.ErrorWrappingMiddleware.Invoke(HttpContext context) in C:\agent\_work\594\s\src\OurApp.WebMvcUICore\Middlewares\ErrorWrappingMiddleware.cs:line 50
Mar 09 13:07:21 applinux dotnet-app[41176]: 13:07:21 Error | OurApp.WebMvcUICore.Middlewares.ErrorWrappingMiddleware | 0HLU44L6UB6V1:00000001 - An error was encountered while handling the remote login.The operation was canceled.Unable to read data from the transport connection: Operation canceled.Operation canceled
Mar 09 13:07:21 applinux dotnet-app[41176]: System.Exception: An error was encountered while handling the remote login.
Mar 09 13:07:21 applinux dotnet-app[41176]:  ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
Mar 09 13:07:21 applinux dotnet-app[41176]:  ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
Mar 09 13:07:21 applinux dotnet-app[41176]:  ---> System.Net.Sockets.SocketException (125): Operation canceled
Mar 09 13:07:21 applinux dotnet-app[41176]:    --- End of inner exception stack trace ---
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.HttpConnection.FillAsync()
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
Mar 09 13:07:21 applinux dotnet-app[41176]:    --- End of inner exception stack trace ---
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RedeemAuthorizationCodeAsync(OpenIdConnectMessage tokenEndpointRequest)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
Mar 09 13:07:21 applinux dotnet-app[41176]:    --- End of inner exception stack trace ---
Mar 09 13:07:21 applinux dotnet-app[41176]:    at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
Mar 09 13:07:21 applinux dotnet-app[41176]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Mar 09 13:07:21 applinux dotnet-app[41176]:    at OurApp.WebMvcUICore.Middlewares.ErrorWrappingMiddleware.Invoke(HttpContext context) in C:\agent\_work\594\s\src\OurApp.WebMvcUICore\Mid
```

### nginx configuration 

server {
```
    listen 80;
    root /var/aspnetcore/app1.gr;
    index index.php index.html index.htm;

    server_name app1.gr;

    error_log /var/aspnetcore/app1.gr/logs/error.log error;
    access_log /var/aspnetcore/app1.gr/logs/access.log;

    location / {
        proxy_pass http://localhost:5566;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }

    #location ~*  \.(jpg|jpeg|png|gif|ico|css|js)$ {
    #    expires 365d;
    #}
}
```

### Further technical details
- ASP.NET Core version 3.1.1
- Include the output of `dotnet --info`
```
Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26
```
Ubuntu 18.04
nginx 1.14.0

**Comment by xrkolovos** [comment]
If I can help you with anything else, please inform me.

**Comment by xrkolovos** [comment]
More info on this one.

It doesn't work the second time. I get this error multiple times. Its random when it will work. After 2-7 refresh on the page it will login.

**Comment by blowdart** [comment]
What are you attempting to login to and how is your odic handler configured?

**Comment by Tratcher** [comment]
The web app cannot contact the identity provider via http/s, it's timing out. Does this app need a proxy configured to access the internet?
