### ISSUE TITLE
Blazor WebAssembly v3.2.0-Preview2 exception at runtime

### ISSUE THREAD

**Issue by BrunoBlanes** [dotnet/aspnetcore#19763]
### The bug
The bug is a System.InvalidOperationException that pops up when trying to run the application in either release or debug mode.

### To Reproduce
Followed the [blog post](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-2-release-now-available/) on how to upgrade an existing project from Preview 1 to Preview 2.

### Startup.cs
```
public class Startup
{
	private readonly IConfiguration configuration;

	public Startup(IConfiguration configuration)
	{
		this.configuration = configuration;
	}

	public void ConfigureServices(IServiceCollection services)
	{
		services.AddDbContext<AppDbContext>(options => options.UseSqlServer(configuration.GetConnectionString("DefaultConnection")));

		services.AddDefaultIdentity<ApplicationUser>(options =>
		{
			[...]
		}).AddEntityFrameworkStores<AppDbContext>();

		services.AddIdentityServer().AddApiAuthorization<ApplicationUser, AppDbContext>();
		services.AddAuthentication().AddIdentityServerJwt();

		services.AddMvc().AddJsonOptions(options =>
		{
			[...]
		});

		services.AddApiVersioning(options =>
		{
			[...]
		});

		services.AddHsts(options =>
		{
			options.Preload = true;
			options.IncludeSubDomains = true;
			options.MaxAge = TimeSpan.FromDays(60);
		});

		services.AddHttpsRedirection(options =>
		{
			options.RedirectStatusCode = StatusCodes.Status307TemporaryRedirect;
			options.HttpsPort = 5001;
		});

		services.AddControllersWithViews();
		services.AddRazorPages();
	}

	public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
	{
		app.UseResponseCompression();

		if (env.IsDevelopment())
		{
			app.UseDeveloperExceptionPage();
			app.UseDatabaseErrorPage();
			app.UseWebAssemblyDebugging();
		}

		else
		{
			app.UseExceptionHandler("/Error");
			app.UseHttpsRedirection();
			app.UseHsts();
		}

		app.UseStaticFiles();
		app.UseBlazorFrameworkFiles();

		app.UseRouting();

		app.UseAuthentication();
		app.UseIdentityServer();
		app.UseAuthorization();

		app.UseEndpoints(endpoints =>
		{
			endpoints.MapRazorPages();
			endpoints.MapControllers();
			endpoints.MapFallbackToFile("index.html");
		});
	}
}
```

### Program.cs
```
public class Program
{
	public static void Main(string[] args)
	{
		CreateHostBuilder(args).Build().Run();
	}

	public static IHostBuilder CreateHostBuilder(string[] args)
	{
		return Host.CreateDefaultBuilder(args).ConfigureWebHostDefaults(webBuilder => webBuilder.UseStartup<Startup>());
	}
}
```

### Exceptions
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.ResponseCompression.IResponseCompressionProvider' while attempting to activate 'Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware'.

#### Stack Trace:
  at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass4_0.<UseMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__31.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at CRM.Server.Program.Main(String[] args) in C:\Users\bruno\source\repos\BrunoBlanes\CRM\Server\Program.cs:line 13

### Further technical details
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200-preview-015002
 Commit:    b3dae24c3b

#### Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19555
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.200-preview-015002\

#### Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

#### .NET Core SDKs installed:
  3.1.200-preview-015002 [C:\Program Files\dotnet\sdk]

#### .NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

#### IDE:
Microsoft Visual Studio Community 2019 Preview
Version 16.5.0 Preview 5.0

**Comment by zbecknell** [comment]
Remove `app.UseResponseCompression()` -- this is now handled by Blazor automatically.

**Comment by BrunoBlanes** [comment]
Oh, sorry. I removed the call from the `ConfigureServices `method and forgot about the `Configure`. Thanks though.
