### ISSUE TITLE
Error: System.ArgumentException: There is no renderer with ID 0. Blazor webassembly

### ISSUE THREAD

**Issue by julitogtu** [dotnet/aspnetcore#19814]
I just update my app to Blazor WebAssembly preview 2, but now I'm getting the following error:
```
blazor.webassembly.js:1 Uncaught (in promise) Error: System.ArgumentException: There is no renderer with ID 0.
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x2bc9d80 + 0x000ce> in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---

  at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously (Microsoft.JSInterop.JSRuntime jsRuntime, Microsoft.JSInterop.Infrastructure.DotNetInvocationInfo& callInfo, Microsoft.JSInterop.Infrastructure.IDotNetObjectReference objectReference, System.String argsJson) <0x338f568 + 0x00172> in <filename unknown>:0 
  at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet (Microsoft.JSInterop.JSRuntime jsRuntime, Microsoft.JSInterop.Infrastructure.DotNetInvocationInfo invocationInfo, System.String argsJson) <0x338f0b0 + 0x00092> in <filename unknown>:0 
    at Object.endInvokeDotNetFromJS (https://localhost:44336/_framework/blazor.webassembly.js:1:9979)
    at Object.invokeJSFromDotNet (https://localhost:44336/_framework/blazor.webassembly.js:1:9605)
    at _mono_wasm_invoke_js_marshalled (https://localhost:44336/_framework/wasm/dotnet.3.2.0-preview2.20159.2.js:1:163081)
    at do_icall (<anonymous>:wasm-function[6008]:0x10e0aa)
    at do_icall_wrapper (<anonymous>:wasm-function[1886]:0x51cc2)
    at interp_exec_method (<anonymous>:wasm-function[1114]:0x2572f)
    at interp_runtime_invoke (<anonymous>:wasm-function[5617]:0xf6a13)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[5067]:0xdd20a)
    at do_runtime_invoke (<anonymous>:wasm-function[1400]:0x3ca7c)
    at mono_runtime_try_invoke (<anonymous>:wasm-function[428]:0xd58c)
```

I do not have any real logic there, no call to IJSruntime, this is a basic form with two fields or any other javascript code, no custom code on init methods.

BTW, with previous version (blazor preview 1) it was working good.

### Further technical details
- Net core version: 3.1.200-preview-015002
- VS 2019 v16.5.0 preview 5

**Comment by javiercn** [comment]
@julitogtu thanks for contacting us.

It looks like you might have some out of date bits. I recommend you add a global.json to the root of your solution and try again.

You can do this with `dotnet new globaljson --sdk-version 3.1.102` and close and open visual studio. If after that you still run into issues, then make sure you clean your bin and obj folders and rebuild again.

**Comment by julitogtu** [comment]
@javiercn thank you, I did those steps (+ restart windows) but the error continues.

**Comment by julitogtu** [comment]
@javiercn  BTW. I just create a new blazor project, copy all files and nuget references and it works, so something strange happen with the old project. I'm gonna copy all the rest of the pages and components that I have and I'll update this thread and close the issue if all works.

**Comment by julitogtu** [comment]
I'm closing this issue, i just add a new blazor project to the project and copy and paste all pages and code, and simply it works.
