### ISSUE TITLE
CorsPolicyBuilder.GetNormalizedOrigin NullReferenceException

### ISSUE THREAD

**Issue by chrispickford** [dotnet/aspnetcore#19830]
Making a call to `CorsPolicyBuilder.WithOrigins` with an array that contains a null string will cause a `NullReferenceException` to be thrown rather than throwing against the argument. This was noticed when a configuration file failed to read.

### To Reproduce
```
app.UseCors(builder => builder.WithOrigins(null));

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsPolicyBuilder.GetNormalizedOrigin(String origin)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsPolicyBuilder.WithOrigins(String[] origins)
   at ###.Startup.<Configure>b__11_0(CorsPolicyBuilder builder) in ###\Startup.cs:line 95
   at Microsoft.AspNetCore.Builder.CorsMiddlewareExtensions.UseCors(IApplicationBuilder app, Action`1 configurePolicy)
   at ###.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in ###\Startup.cs:line 94
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

It would be beneficial if an `ArgumentNullException` was thrown instead.

**Comment by mkArtakMSFT** [comment]
Thanks for reporting this and submitting the PR, @chrispickford.
We will review the PR and get back to you next week.

**Comment by pranavkm** [comment]
Resolved as part of https://github.com/dotnet/aspnetcore/pull/19831.
