### ISSUE TITLE
Stack trace occuring with a crawler or hacker

### ISSUE THREAD

**Issue by MCFHTAGENTS** [dotnet/aspnetcore#19862]
I am seeing the following stack trace in my log on a site running 3.1.2  - I think because either a crawler or would be hacker is trying to access the site with bad paths rather than any proper use of the site.

Please can it be handled better.

```
2020-03-14 22:20:23.415 +00:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The path contains null characters.
   at Microsoft.AspNetCore.Internal.UrlDecoder.DecodeCore(Int32& sourceIndex, Int32& destinationIndex, Span`1 buffer, Boolean isFormEncoding)
   at Microsoft.AspNetCore.Internal.UrlDecoder.DecodeInPlace(Span`1 buffer, Boolean isFormEncoding)
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.GetDecodedString(ReadOnlySpan`1 readOnlySpan)
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ParseFormValuesFast(ReadOnlySpan`1 span, KeyValueAccumulator& accumulator, Boolean isFinalBlock, Int32& consumed)
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ParseFormValues(ReadOnlySequence`1& buffer, KeyValueAccumulator& accumulator, Boolean isFinalBlock)
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenStore.GetRequestTokensAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.ValidateAntiforgeryTokenAuthorizationFilter.OnAuthorizationAsync(AuthorizationFilterContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Joonasw.AspNetCore.SecurityHeaders.Csp.CspMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

```

**Comment by blowdart** [comment]
What would you expect to happen here? An exception isn't harmful, it isn't bringing your site down.

**Comment by MCFHTAGENTS** [comment]
It results in the log files becoming very large with the stack traces especially as it looks like some form of automated process is hitting the site - so some form of information to allow me to block it if malevolent or at least an expected error that doesn’t need a stack trace would be helpful

**Comment by blowdart** [comment]
That's fair, at least lack of stack trace anyway.

**Comment by davidfowl** [comment]
I'm not sure what it would do instead.

**Comment by MCFHTAGENTS** [comment]
I think just trap the exception - generate a error message without the stack trace and ideally tell us something about the bad request so we can block it or feedback the fault

**Comment by davidfowl** [comment]
Your code can do that. Today the exception handler middleware is logging the exception, you can disable that with the following logger configuration:

{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information",
      "Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware": "None"
    }
  },
  "AllowedHosts": "*"
}

**Comment by MCFHTAGENTS** [comment]
Thank you for that - this looks like it will block any logging from the ExceptionHandlerMiddleware component which feels a bit broadbrush to me in that it would stop any errors from this component and there may be others generated that are of value to me.

I also think it useful to know someone is up to something on the site - and as this is an expected exception think it probably should be handled.

**Comment by davidfowl** [comment]
So to be extremely specific. If this component cannot read the form for some reason it should log a different error and swallow this exception? That’s what you want ?

**Comment by MCFHTAGENTS** [comment]
David, Thansk I have changed one word on your summary: 

> If this component cannot read the form for some reason it should log an error and swallow this exception?

**Comment by Tratcher** [comment]
This falls into the class of things that the caller (MVC/Antiforgery) should be handling and generating a 400 response. It already does this for other types of AntiForgery errors in this callstack. @pranavkm 
https://github.com/dotnet/aspnetcore/blob/715ed24382b7f9621bc0b48a8202705c5cf8870d/src/Mvc/Mvc.ViewFeatures/src/Filters/ValidateAntiforgeryTokenAuthorizationFilter.cs#L45-L50

**Comment by pranavkm** [comment]
Catching an opaque `InvalidOperationException` and generating a validation failed result feels a little iffy.

**Comment by davidfowl** [comment]
I'd suggest 2 things:
-  @Tratcher  We should change InvalidOperationException to InvalidDataException for this kind of failure.

@pranavkm Swallow the InvalidDataException, return a 400 and log the error as debug. That way we can still debug what the actual error was with the stack trace if the logging verbosity is turned up.

**Comment by Tratcher** [comment]
> * We should change InvalidOperationException to InvalidDataException for this kind of failure.

We'd likely need to wrap it, that's coming from a deeper shared library.

**Comment by davidfowl** [comment]
@Tratcher makes sense, lets do that.

**Comment by Tratcher** [comment]
Ok, I've split out the InvalidOperaitonException as its own issue.
https://github.com/dotnet/aspnetcore/issues/19962

**Comment by Marusyk** [comment]
Seems, it's not blocked anymore.  I'll try to prepare a PR

**Comment by JoseOchoaITH** [comment]
I'm having the same issue and I'm trying to catch that exception with as an InvalidDataException and I'm not able to handle it.
I am missing something? The InvalidDataException should not catch InvalidOperationException?

Because, as someone said previously, catching an opaque InvalidOperationException and generating a validation failed result feels a little iffy. Or doing something like ´´´when (invalidOperationException.Message == "The path contains null characters.")´´´ looks pretty bad.

**Comment by madrianr** [comment]
I'm having the same issue after Upgrading from .NET Core 2.2 to .NET Core 3.1 
if I send formdata like this

Info_Gewerbeinhaber_Geburtsort: Mun. Re?i?a Jud. Cara?-Severin

I get this error The path contains null characters." - why this?

what's wrong with this form data?

robert

**Comment by Tratcher** [comment]
@madrianr a url decoder is used when un-escaping fields in the form because it's mostly the same encoding, that's why you get an error message about paths. It looks like your data is sent using an unrecognized encoding. Can you capture and share the full request using a tool like Fiddler or Wireshark?

**Comment by madrianr** [comment]
[3_Full.txt](https://github.com/dotnet/aspnetcore/files/5552268/3_Full.txt)

attached you find the request from fiddler - it seems the problem is located here: "Gewerbeinhaber_Geburtsort=test%00" 

this is no problem in .NET Core 2.2

robert

**Comment by Tratcher** [comment]
%00 un-escapes to a null character which the decoder rejects. C# strings shouldn't normally contain null characters. What was the result before?

This seems to be generated test input. Is there a real need to support nulls?

**Comment by madrianr** [comment]
Hmmm, we have some situations (Unicode conversion to varchar() results in such nulls) and with 2.2 it works...
robert
