### ISSUE TITLE
DbContext is disposed when using async task

### ISSUE THREAD

**Issue by zandiarash** [dotnet/aspnetcore#19894]
### Describe the bug
DbContext is disposed when using async task

I'm working on a project with **RazorPages**
Please look at the code below
### To Reproduce
```
public async void OnGetAsync()
{
    var currUser = await _UserManager.GetUserAsync(User);
    var ImDev = await _UserManager.IsInRoleAsync(currUser, Roles.Developer.ToString());
    var myOffice = _ApplicationDbContext.Tbl_UserOfficeMap.Where(x => ImDev ||  x.IdUser == currUser.Id)
        .Join(_ApplicationDbContext.Tbl_Offices, uom => uom.IdOffice, o => o.Id, (uom, o) => new { uom, o })
        .Select(x => x.o).FirstOrDefault();

    //Here error accures
    List<SelectListItem> Offices = _ApplicationDbContext.Tbl_Offices
        .Where(x => (ImDev || x.IdProvince == myOffice.IdProvince))
        .Select(x => new SelectListItem
        {
            Value = x.Id.ToString(),
            Text = x.Name,
        }).ToList();
    ...
}
```

This Error accures
```
Exception has occurred: CLR/System.ObjectDisposedException
An exception of type 'System.ObjectDisposedException' occurred in Microsoft.EntityFrameworkCore.dll but was not handled in user code: 'Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.'
   at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_ChangeTracker()
   at Microsoft.EntityFrameworkCore.Query.CompiledQueryCacheKeyGenerator.GenerateCacheKeyCore(Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.RelationalCompiledQueryCacheKeyGenerator.GenerateCacheKeyCore(Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerCompiledQueryCacheKeyGenerator.GenerateCacheKey(Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Sabtahval.Areas.Admin.Pages.UsersModel.<OnGetAsync>d__13.MoveNext() in C:\OtherFiles\WorkSpace\Sabtahval\SabtahvalMVCRazor\Areas\Admin\Pages\Users.cs:line 70
```

But if I change it to the code below, no error happens and everything works as expected
```
public void OnGet()
{
    var currUser =  _UserManager.GetUserAsync(User).Result;
    var ImDev =  _UserManager.IsInRoleAsync(currUser, Roles.Developer.ToString()).Result;
    var myOffice = _ApplicationDbContext.Tbl_UserOfficeMap.Where(x => ImDev ||  x.IdUser == currUser.Id)
        .Join(_ApplicationDbContext.Tbl_Offices, uom => uom.IdOffice, o => o.Id, (uom, o) => new { uom, o })
        .Select(x => x.o).FirstOrDefault();

    //Here error accures
    List<SelectListItem> Offices = _ApplicationDbContext.Tbl_Offices
        .Where(x => (ImDev || x.IdProvince == myOffice.IdProvince))
        .Select(x => new SelectListItem
        {
            Value = x.Id.ToString(),
            Text = x.Name,
        }).ToList();
    ...
}
```

It possible that this line 

> await _UserManager.IsInRoleAsync(currUser, Roles.Developer.ToString());

Disposes the **ApplicationDbContext**
But this line :

>  _UserManager.IsInRoleAsync(currUser, Roles.Developer.ToString()).Result;

Does not ?
I'm sure that never I disposed **ApplicationDbContext**.
What Is my mistake when using **async** and **await** ?
Am I doing something wrong ? 

### Further technical details
- ASP.NET Core version 3.1.1
- The IDE (VS Code : 1.43.0)
- The Omnisharp 1.21.13

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
The issue you're facing is because your handler is `void`. Consider changing it to return `Task` as follows:

```csharp
public async Task OnGetAsync()
```

**Comment by davidfowl** [comment]
Shameless plug https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#async-void

**Comment by zandiarash** [comment]
Thanks @mkArtakMSFT 
You solved my problem.
Actually It was not a bug, that was because I have less knowledge about programming 🙈 
Seriously I advice beginners (like myself) to read The article from @davidfowl.

**Comment by javiercn** [comment]
Closing this issue as there's no further action from us here.
