### ISSUE TITLE
Error in VS Code Extension

### ISSUE THREAD

**Issue by Stanzilla** [dotnet/aspnetcore#19912]
### Describe the bug
Just opened a project in VSCode and the Language Server crashed

### To Reproduce

```
--------------------------------------------------------------------------------
Razor.VSCode version 1.0.0-alpha3-5.0.0-preview.2.20156.4
--------------------------------------------------------------------------------
Razor's trace level is currently set to 'Off'
 - To change Razor's trace level set 'razor.trace' to 'Off', 'Messages' or 'Verbose' and then restart VSCode.
 - To report issues invoke the 'Report a Razor issue' command via the command palette.
-----------------------------------------------------------------------------------------------------------------------------

Unhandled exception. Newtonsoft.Json.JsonSerializationException: Error setting value to 'RootPath' on 'OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeParams'.
 ---> System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeParams.set_RootPath(String value)
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.FindDescriptor(String method, JToken params)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.FindDescriptor(IMethodWithParams instance)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.GetDescriptor(Request request)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.OmniSharp.Extensions.JsonRpc.IRequestRouter<OmniSharp.Extensions.JsonRpc.IHandlerDescriptor>.GetDescriptor(Request request)
   at OmniSharp.Extensions.JsonRpc.InputHandler.HandleRequest(String request)
   at OmniSharp.Extensions.JsonRpc.InputHandler.ProcessInputStream()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
[Info  - 02:57:51] Connection to server got closed. Server will restart.
Unhandled exception. Newtonsoft.Json.JsonSerializationException: Error setting value to 'RootPath' on 'OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeParams'.
 ---> System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeParams.set_RootPath(String value)
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.FindDescriptor(String method, JToken params)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.FindDescriptor(IMethodWithParams instance)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.GetDescriptor(Request request)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.OmniSharp.Extensions.JsonRpc.IRequestRouter<OmniSharp.Extensions.JsonRpc.IHandlerDescriptor>.GetDescriptor(Request request)
   at OmniSharp.Extensions.JsonRpc.InputHandler.HandleRequest(String request)
   at OmniSharp.Extensions.JsonRpc.InputHandler.ProcessInputStream()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
[Info  - 02:57:51] Connection to server got closed. Server will restart.
Unhandled exception. Newtonsoft.Json.JsonSerializationException: Error setting value to 'RootPath' on 'OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeParams'.
 ---> System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeParams.set_RootPath(String value)
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.FindDescriptor(String method, JToken params)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.FindDescriptor(IMethodWithParams instance)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.GetDescriptor(Request request)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.OmniSharp.Extensions.JsonRpc.IRequestRouter<OmniSharp.Extensions.JsonRpc.IHandlerDescriptor>.GetDescriptor(Request request)
   at OmniSharp.Extensions.JsonRpc.InputHandler.HandleRequest(String request)
   at OmniSharp.Extensions.JsonRpc.InputHandler.ProcessInputStream()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
[Info  - 02:57:52] Connection to server got closed. Server will restart.
Unhandled exception. Newtonsoft.Json.JsonSerializationException: Error setting value to 'RootPath' on 'OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeParams'.
 ---> System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeParams.set_RootPath(String value)
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.FindDescriptor(String method, JToken params)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.FindDescriptor(IMethodWithParams instance)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.GetDescriptor(Request request)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.OmniSharp.Extensions.JsonRpc.IRequestRouter<OmniSharp.Extensions.JsonRpc.IHandlerDescriptor>.GetDescriptor(Request request)
   at OmniSharp.Extensions.JsonRpc.InputHandler.HandleRequest(String request)
   at OmniSharp.Extensions.JsonRpc.InputHandler.ProcessInputStream()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
[Info  - 02:57:52] Connection to server got closed. Server will restart.
Unhandled exception. Newtonsoft.Json.JsonSerializationException: Error setting value to 'RootPath' on 'OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeParams'.
 ---> System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeParams.set_RootPath(String value)
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.FindDescriptor(String method, JToken params)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.FindDescriptor(IMethodWithParams instance)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.GetDescriptor(Request request)
   at OmniSharp.Extensions.LanguageServer.Server.LspRequestRouter.OmniSharp.Extensions.JsonRpc.IRequestRouter<OmniSharp.Extensions.JsonRpc.IHandlerDescriptor>.GetDescriptor(Request request)
   at OmniSharp.Extensions.JsonRpc.InputHandler.HandleRequest(String request)
   at OmniSharp.Extensions.JsonRpc.InputHandler.ProcessInputStream()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
[Error - 02:57:52] Connection to server got closed. Server will not be restarted.
[Client - 02:57:52] (Error) Failed when activating Razor VSCode.
undefined
Stack Trace:
undefined
```

### Further technical details
- ASP.NET Core version: not installed
- Include the output of `dotnet --info`: dotnet not installed
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: VS Code 1.43

**Comment by javiercn** [comment]
@Stanzilla thanks for contacting us.

@NTaylorMullen @TanayParikh @ryanbrandenburg @ajaybhargavb thoughts?

**Comment by NTaylorMullen** [comment]
@Stanzilla would you mind sharing the folder path of the project you were attempting to open?

**Comment by Stanzilla** [comment]
`\\wsl$\Ubuntu\home\stan\projects\work\backend\xxx\`

**Comment by NTaylorMullen** [comment]
@ajaybhargavb Did your changes to enable opening projects from a network share change how we deserialize those paths at all on the language server side?
