### ISSUE TITLE
Integration testing app using NTLM authentication and Kestrel with WebApplicationFactory (from Microsoft.AspNetCore.Mvc.Testing)

### ISSUE THREAD

**Issue by hosseinnassiri** [dotnet/aspnetcore#19933]
### Describe the bug
Using WebApplicationFactory<TStartup> for integration testing a asp.net core api (version 3.1) that uses NTLM authentication and running with Kestrel not IIS.

### To Reproduce
Startup.cs of the Web API to configure NTLM authentication with Kestrel:
``` C#
services.AddAuthentication(NegotiateDefaults.AuthenticationScheme)
            .AddNegotiate(NegotiateDefaults.AuthenticationScheme, options => { });
```
Integration test custom web app factory:
``` C#
public class CustomWebApplicationFactory<TStartup> : WebApplicationFactory<TStartup> where TStartup : class
    {
        protected override void ConfigureWebHost(IWebHostBuilder builder)
        {
            builder.ConfigureTestServices(services =>
            {
                services.AddSingleton<ILoggerFactory, LoggerFactory>();
                services.AddAuthentication("Test")
                        .AddScheme<AuthenticationSchemeOptions, TestAuthHandler>(
                            "Test", options => { });
            });
        }
    }
```

Integration test:
``` C#
[TestClass]
public class UnitTest1
{
    private CustomWebApplicationFactory<Startup> _factory;
    private HttpClient _httpClient;

    [TestInitialize]
    public void Init()
    {
        _factory = new CustomWebApplicationFactory<Startup>();
        _httpClient = _factory.CreateClient();
        _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Test");
    }

    [TestMethod]
    public async Task TestMethod1()
    {
        var response = await _httpClient.GetAsync("/weatherforecast").ConfigureAwait(false);

        response.EnsureSuccessStatusCode();
        var stringResponse = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
    }
}
```

### Exception
Negotiate authentication requires a server that supports IConnectionItemsFeature like Kestrel.
Stack trace:
   at Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.GetConnectionItems()
   at Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.<HandleRequestAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.<HandleRequestAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at WindowsAuthenticationSample.ExceptionMiddleware.<InvokeAsync>d__3.MoveNext() in C:\Source\WindowsAuthenticationSample\WindowsAuthenticationSample\Startup.cs:line 70

**Comment by hosseinnassiri** [comment]
@mkArtakMSFT Any idea why this is happening?

**Comment by Tratcher** [comment]
WebApplicationFactory doesn't use kestrel, it uses the in-memory TestServer and in-memory HttpClient. Neither of those support the features needed for Negotiate auth.

**Comment by hosseinnassiri** [comment]
> WebApplicationFactory doesn't use kestrel, it uses the in-memory TestServer and in-memory HttpClient. Neither of those support the features needed for Negotiate auth.
Is there a way to write api tests when using KEstrel and Negotiate auth?

**Comment by Tratcher** [comment]
You can write tests that use Kestrel + Negotiate, but you can't write tests that use WebApplicationFactory/TestServer + Negotiate.
https://github.com/dotnet/aspnetcore/blob/4191eb5c7629ddbf88168ac45cffb7bea3b7e956/src/Security/Authentication/Negotiate/test/Negotiate.FunctionalTest/NegotiateHandlerFunctionalTests.cs#L40-L50

**Comment by javiercn** [comment]
@Tratcher is correct.

The goal of WAF is to facilitate testing MVC applications in memory, the recommended pattern to follow here is to mock your auth or write a proper E2E test with a real server.
