### ISSUE TITLE
Have the form reader convert InvalidOperationException to InvalidDataException

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#19962]
### Describe the bug
https://github.com/dotnet/aspnetcore/issues/19862  The form reader can throw InvalidOperationException when it hits some types of bad data. This is inconsistent with the InvalidDataException it throw 

```
2020-03-14 22:20:23.415 +00:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The path contains null characters.
   at Microsoft.AspNetCore.Internal.UrlDecoder.DecodeCore(Int32& sourceIndex, Int32& destinationIndex, Span`1 buffer, Boolean isFormEncoding)
   at Microsoft.AspNetCore.Internal.UrlDecoder.DecodeInPlace(Span`1 buffer, Boolean isFormEncoding)
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.GetDecodedString(ReadOnlySpan`1 readOnlySpan)
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ParseFormValuesFast(ReadOnlySpan`1 span, KeyValueAccumulator& accumulator, Boolean isFinalBlock, Int32& consumed)
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ParseFormValues(ReadOnlySequence`1& buffer, KeyValueAccumulator& accumulator, Boolean isFinalBlock)
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenStore.GetRequestTokensAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.ValidateAntiforgeryTokenAuthorizationFilter.OnAuthorizationAsync(AuthorizationFilterContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Joonasw.AspNetCore.SecurityHeaders.Csp.CspMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

### To Reproduce
POST a form with null characters.

### Proposal:
Wrap the InvalidOperationException in an InvalidDataException, that will make it easier to handle up stack.

**Comment by arunprasathv** [comment]
@davidfowl trying to build the asp.net core project to fix this bug, but getting this error  - error MSB4019. 


C:\aspnet\aspnetcore\src\Servers\IIS\AspNetCoreModuleV2\AspNetCore\AspNetCore.vcxproj(31,3): error MSB4019: The importe
d project "C:\aspnet\aspnetcore\.tools\msbuild\16.3.0-alpha\tools\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props
" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
C:\aspnet\aspnetcore\src\Servers\IIS\AspNetCoreModuleV2\CommonLib\CommonLib.vcxproj(28,3): error MSB4019: The imported
project "C:\aspnet\aspnetcore\.tools\msbuild\16.3.0-alpha\tools\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props"
was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
C:\aspnet\aspnetcore\src\Servers\IIS\AspNetCoreModuleV2\IISLib\IISLib.vcxproj(28,3): error MSB4019: The imported projec
t "C:\aspnet\aspnetcore\.tools\msbuild\16.3.0-alpha\tools\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props" was no
t found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
C:\aspnet\aspnetcore\src\Servers\IIS\AspNetCoreModuleV2\gtest\gtest.vcxproj(31,3): error MSB4019: The imported project
"C:\aspnet\aspnetcore\.tools\msbuild\16.3.0-alpha\tools\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Defaul

**Comment by Tratcher** [comment]
Make sure you've installed the prereqs. https://github.com/dotnet/aspnetcore/blob/master/docs/BuildFromSource.md#install-pre-requisites

**Comment by arunprasathv** [comment]
I have everything other than JDK. Is it mandatory to install it?

**Comment by Tratcher** [comment]
This error means that your missing the c++ tools installed with Visual Studio. Try the script from the instructions to install additional VS components.

**Comment by Marusyk** [comment]
@Tratcher Do you mean catch `InvalidOperationException` in 
https://github.com/dotnet/aspnetcore/blob/715ed24382b7f9621bc0b48a8202705c5cf8870d/src/Mvc/Mvc.ViewFeatures/src/Filters/ValidateAntiforgeryTokenAuthorizationFilter.cs#L45-L50

and rethrow `InvalidDataException`?

**Comment by Tratcher** [comment]
No, lower. Somewhere around Microsoft.AspNetCore.WebUtilities.FormPipeReader.GetDecodedString.

**Comment by davidfowl** [comment]
I don't believe this issue is complete. The original request was to go to the places that throw today and return a 400 instead.

**Comment by Tratcher** [comment]
@davidfowl #19862 covers catching InvalidDataException at higher layers and turning it into a 400 response.
