### ISSUE TITLE
 An attempt was made to access a socket in a way forbidden by its access   permissions.

### ISSUE THREAD

**Issue by rgulamali** [dotnet/aspnetcore#20010]
blazor.server.js:1 [2020-03-18T18:33:18.362Z] Information: Normalizing '_blazor' to 'https://blazoremployeeefcoreazure1.azurewebsites.net/_blazor'.
blazor.server.js:1 

[2020-03-18T18:33:18.444Z] Information: WebSocket connected to wss://blazoremployeeefcoreazure1.azurewebsites.net/_blazor?id=AJlbqxHFO6H2rput0F1ByQ.
blazor.server.js:15 [2020-03-18T18:33:21.232Z] Error: System.Net.Http.HttpRequestException: An attempt was made to access a socket in a way forbidden by its access 

permissions.
 ---> System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at BlazorEmployeeEFCore.Data.CustomHttpClient.GetJsonAsync[T](String requestUri) in C:\Downloads\BlazorEntityFrameworkExample\BlazorEmployeeEFCore

\BlazorEmployeeEFCore\Data\CustomHttpClient.cs:line 13
   at BlazorEmployeeEFCore.Pages.ListEmployees.OnInitializedAsync() in C:\Downloads\BlazorEntityFrameworkExample\BlazorEmployeeEFCore\BlazorEmployeeEFCore\Pages

\ListEmployees.razor:line 112
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
e.log @ blazor.server.js:15
blazor.server.js:1 [2020-03-

18T18:33:21.234Z] Information: Connection disconnected.

**Comment by javiercn** [comment]
@rgulamali thanks for contacting us.

We don't seem to have enough information to help you here. From what we can tell you are trying to send an outgoing HTTP request and failing to do so. There's nothing Blazor specific about it.
