### ISSUE TITLE
Getting 403 (Forbidden) when create a Twitter challenge

### ISSUE THREAD

**Issue by ThomasArdal** [dotnet/aspnetcore#20049]
I have implemented Twitter login on my ASP.NET Core site and it works. I have also configured Microsoft.Extensions.Logging. I'm seeing occasional errors in the log like this one:

```csharp
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.AspNetCore.Authentication.Twitter.TwitterHandler.ObtainRequestTokenAsync(String callBackUri, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.Twitter.TwitterHandler.HandleChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Mvc.ChallengeResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|27_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at MyCode.Startup.<>c.<<Configure>b__9_1>d.MoveNext()
```

I'm not using Identity but the `Microsoft.AspNetCore.Authentication.Twitter` package directly by implementing an action for twitter login looking like this:

```csharp
public ActionResult LoginTwitter(string returnUrl)
{
    return Challenge(TwitterDefaults.AuthenticationScheme, returnUrl);
}
```

As mentioned, the code seems to work in most cases, but still logs the error from time to time.

What could be the reason for the 403 here?

**Comment by blowdart** [comment]
Are you sure this login actually completed? Did someone cancel or otherwise get their twitter login incorrect?

**Comment by ThomasArdal** [comment]
I cannot see what happened since this happens while other users try to log into the site. I was thinking that it could be caused by the user not approving the sign in on Twitter. But when looking at the error I see in the log, the current URL is `/account/logintwitter`. That's my own URL that does nothing else than return the Twitter challenge (code pasted).

When looking through the code in `TwitterHandler` it looks like this:

```csharp
private async Task<RequestToken> ObtainRequestTokenAsync(string callBackUri, AuthenticationProperties properties)
{
    Logger.ObtainRequestToken();

    var response = await ExecuteRequestAsync(TwitterDefaults.RequestTokenEndpoint, HttpMethod.Post, extraOAuthPairs: new Dictionary<string, string>() { { "oauth_callback", callBackUri } });
    response.EnsureSuccessStatusCode();
    var responseText = await response.Content.ReadAsStringAsync();
    ...
}
```

I believe the error I am seeing is caused by the `EnsureSuccessStatusCode` method. So, the post to `https://api.twitter.com/oauth/request_token` returns the 403.

**Comment by Tratcher** [comment]
Your best bet is to hook the Bachchannel property on the options and log the full response from Twitter.
