### ISSUE TITLE
[TEST KO] Cannot make RedisEndToEnd pass locally on master branch

### ISSUE THREAD

**Issue by tebeco** [dotnet/aspnetcore#20040]
### Describe the bug
As i was trying to do PR #20031 i saw that lots of `Redis` test were not passing 

### To Reproduce
Clone the branch from #20031, run `docker for windows`
and run all tests from `RedisEndToEnd.cs`

### Further technical details
- ASP.NET Core version : 5.0.x (`master` branch
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
  Happen on both `build.cmd -test` and `Vs 16.6 Preview1`

### More details :
I can't make pass all the `RedisEndToEnd` tests from both `build.cmd -test` and `VS2019 16.6 Preview1` :(

I even updates locally `ServiceStack.Redis` to `2.1.0` that was release yesterday as it contains lots of error message enhancement/fix, still the same result.
Can someone reproduce or make them pass ?

Here is what i see :
I had to put a break point on the failing line : https://github.com/dotnet/aspnetcore/blob/master/src/SignalR/server/StackExchangeRedis/test/RedisEndToEnd.cs#L111
![image](https://user-images.githubusercontent.com/2266487/77208797-e38a0e80-6afc-11ea-8496-d07282893799.png)

(Even using `docker logs --follow <name>` does no see anymore activity, until the container is destroy because it's starterd with `--rm`)

One example of error :
```
 Message: 
    Microsoft.AspNetCore.SignalR.HubException : An unexpected error occurred invoking 'EchoUser' on the server. RedisConnectionException: No connection is available to service this operation: PUBLISH Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.EchoHub:user:userA; UnableToConnect on 172.17.0.2:6379/Interactive, Initializing/NotStarted, last: NONE, origin: BeginConnectAsync, outstanding: 0, last-read: 37s ago, last-write: 37s ago, keep-alive: 60s, state: Connecting, mgr: 10 of 10 available, last-heartbeat: never, global: 0s ago, v: 2.0.593.37019; IOCP: (Busy=0,Free=1000,Min=16,Max=1000), WORKER: (Busy=5,Free=32762,Min=16,Max=32767), Local-CPU: n/a
  Stack Trace: 
    HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken) line 776
    ForceAsyncAwaiter`1.GetResult() line 64
    HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken) line 390
    TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) line 45
    RedisEndToEndTests.CanSendAndReceiveUserMessagesFromMultipleConnectionsWithSameUser(HttpTransportType transportType, String protocolName) line 111
    --- End of stack trace from previous location ---
```

**Comment by eerhardt** [comment]
This test failed again on my PR: #47450

https://dev.azure.com/dnceng-public/public/_build/results?buildId=220405&view=ms.vss-test-web.build-test-results-tab&runId=4127442&resultId=122066&paneView=debug

https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-pull-47450-merge-0e57b67cf6174d519f/Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests--net8.0/1/console.408f0c34.log?helixlogtype=result

```
2023-03-28T21:49:03.9723220Z   Failed Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.RedisEndToEndTests.CanSendAndReceiveUserMessagesFromMultipleConnectionsWithSameUser(transportType: WebSockets, protocolName: "json") [30 s]
2023-03-28T21:49:03.9723288Z   Error Message:
2023-03-28T21:49:03.9723320Z    System.TimeoutException : The operation has timed out.
2023-03-28T21:49:03.9723348Z   Stack Trace:
2023-03-28T21:49:03.9723375Z      at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber)
2023-03-28T21:49:03.9723409Z    at Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.RedisEndToEndTests.CanSendAndReceiveUserMessagesFromMultipleConnectionsWithSameUser(HttpTransportType transportType, String protocolName) in /_/src/SignalR/server/StackExchangeRedis/test/RedisEndToEnd.cs:line 111
2023-03-28T21:49:03.9723527Z --- End of stack trace from previous location ---
2023-03-28T21:49:03.9723559Z   Standard Output Messages:
2023-03-28T21:49:03.9723589Z  | [0.001s] TestLifetime Information: Starting test CanSendAndReceiveUserMessagesFromMultipleConnectionsWithSameUser-WebSockets-json at 2023-03-28T21:48:33
2023-03-28T21:49:03.9723755Z  | [0.002s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Registering handler for client method 'Echo'.
2023-03-28T21:49:03.9723793Z  | [0.003s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Registering handler for client method 'Echo'.
2023-03-28T21:49:03.9723818Z  | [0.003s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Starting HubConnection.
2023-03-28T21:49:03.9723842Z  | [0.003s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Starting HttpConnection.
2023-03-28T21:49:03.9723866Z  | [0.003s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Establishing connection with server at 'http://127.0.0.1:36685/echo'.
2023-03-28T21:49:03.9723890Z  | [0.005s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Established connection 'PELRLEGdVFdrQXbsd5qPZg' with the server.
2023-03-28T21:49:03.9723946Z  | [0.005s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Starting transport 'WebSockets' with Url: http://127.0.0.1:36685/echo.
2023-03-28T21:49:03.9723969Z  | [0.005s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Information: Starting transport. Transfer mode: Text. Url: 'ws://127.0.0.1:36685/echo?id=6zuVA1Wv8jcgfFoCPAOSaw'.
2023-03-28T21:49:03.9724112Z  | [0.006s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Started transport.
2023-03-28T21:49:03.9724148Z  | [0.006s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Transport 'WebSockets' started.
2023-03-28T21:49:03.9724177Z  | [0.007s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: HttpConnection Started.
2023-03-28T21:49:03.9724205Z  | [0.007s] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: Using HubProtocol 'json v1'.
2023-03-28T21:49:03.9724234Z  | [0.007s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending Hub Handshake.
2023-03-28T21:49:03.9724262Z  | [0.007s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Received message from application. Payload size: 32.
2023-03-28T21:49:03.9724415Z  | [0.007s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Message received. Type: Text, size: 3, EndOfMessage: True.
2023-03-28T21:49:03.9724438Z  | [0.007s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Handshake with server complete.
2023-03-28T21:49:03.9724459Z  | [0.007s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending PingMessage message.
2023-03-28T21:49:03.9724594Z  | [0.007s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending PingMessage message completed.
2023-03-28T21:49:03.9724628Z  | [0.008s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Receive loop starting.
2023-03-28T21:49:03.9724714Z  | [0.008s] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: HubConnection started.
2023-03-28T21:49:03.9724739Z  | [0.008s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Starting HubConnection.
2023-03-28T21:49:03.9724766Z  | [0.008s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Received message from application. Payload size: 11.
2023-03-28T21:49:03.9724794Z  | [0.008s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Starting HttpConnection.
2023-03-28T21:49:03.9724864Z  | [0.008s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Establishing connection with server at 'http://127.0.0.1:43153/echo'.
2023-03-28T21:49:03.9724886Z  | [0.009s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Established connection 'GZQaFT9Oo30R1QUKasixsg' with the server.
2023-03-28T21:49:03.9725028Z  | [0.009s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Starting transport 'WebSockets' with Url: http://127.0.0.1:43153/echo.
2023-03-28T21:49:03.9725069Z  | [0.009s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Information: Starting transport. Transfer mode: Text. Url: 'ws://127.0.0.1:43153/echo?id=W4o5Xc5G8ax2IW10iIOg-w'.
2023-03-28T21:49:03.9725098Z  | [0.010s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Started transport.
2023-03-28T21:49:03.9725124Z  | [0.010s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Debug: Transport 'WebSockets' started.
2023-03-28T21:49:03.9725151Z  | [0.010s] Microsoft.AspNetCore.Http.Connections.Client.HttpConnection Information: HttpConnection Started.
2023-03-28T21:49:03.9725176Z  | [0.010s] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: Using HubProtocol 'json v1'.
2023-03-28T21:49:03.9725254Z  | [0.010s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending Hub Handshake.
2023-03-28T21:49:03.9725281Z  | [0.010s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Received message from application. Payload size: 32.
2023-03-28T21:49:03.9725401Z  | [0.011s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Message received. Type: Text, size: 3, EndOfMessage: True.
2023-03-28T21:49:03.9725434Z  | [0.011s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Handshake with server complete.
2023-03-28T21:49:03.9725461Z  | [0.011s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending PingMessage message.
2023-03-28T21:49:03.9725486Z  | [0.011s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending PingMessage message completed.
2023-03-28T21:49:03.9725511Z  | [0.011s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Receive loop starting.
2023-03-28T21:49:03.9725534Z  | [0.011s] Microsoft.AspNetCore.SignalR.Client.HubConnection Information: HubConnection started.
2023-03-28T21:49:03.9725556Z  | [0.011s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Registering Invocation ID '1' for tracking.
2023-03-28T21:49:03.9725577Z  | [0.011s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending InvocationMessage message '1'.
2023-03-28T21:49:03.9725598Z  | [0.011s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending InvocationMessage message '1' completed.
2023-03-28T21:49:03.9725622Z  | [0.011s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Received message from application. Payload size: 99.
2023-03-28T21:49:03.9725780Z  | [0.013s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Message received. Type: Text, size: 101, EndOfMessage: True.
2023-03-28T21:49:03.9725818Z  | [0.013s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Processing 101 byte message from server.
2023-03-28T21:49:03.9725840Z  | [15.010s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending PingMessage message.
2023-03-28T21:49:03.9725862Z  | [15.010s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending PingMessage message completed.
2023-03-28T21:49:03.9725923Z  | [15.010s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Received message from application. Payload size: 11.
2023-03-28T21:49:03.9725948Z  | [15.706s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Message received. Type: Text, size: 11, EndOfMessage: True.
2023-03-28T21:49:03.9725976Z  | [15.706s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Processing 11 byte message from server.
2023-03-28T21:49:03.9726006Z  | [15.902s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Message received. Type: Text, size: 11, EndOfMessage: True.
2023-03-28T21:49:03.9726128Z  | [15.902s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Processing 11 byte message from server.
2023-03-28T21:49:03.9726157Z  | [16.010s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending PingMessage message.
2023-03-28T21:49:03.9726179Z  | [16.010s] Microsoft.AspNetCore.SignalR.Client.HubConnection Debug: Sending PingMessage message completed.
2023-03-28T21:49:03.9726201Z  | [16.010s] Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport Debug: Received message from application. Payload size: 11.
2023-03-28T21:49:03.9726266Z  | [30.015s] Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.RedisEndToEndTests Error: Test threw an exception.
2023-03-28T21:49:03.9726292Z  | System.TimeoutException: The operation has timed out.
2023-03-28T21:49:03.9726321Z  |    at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber)
2023-03-28T21:49:03.9726433Z  |    at Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.RedisEndToEndTests.CanSendAndReceiveUserMessagesFromMultipleConnectionsWithSameUser(HttpTransportType transportType, String protocolName) in /_/src/SignalR/server/StackExchangeRedis/test/RedisEndToEnd.cs:line 111
2023-03-28T21:49:03.9726486Z  |    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 264
2023-03-28T21:49:03.9726511Z  | --- End of stack trace from previous location ---
2023-03-28T21:49:03.9726539Z  |    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
2023-03-28T21:49:03.9726561Z  |    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
2023-03-28T21:49:03.9726584Z  | [30.016s] TestLifetime Information: Finished test CanSendAndReceiveUserMessagesFromMultipleConnectionsWithSameUser-WebSockets-json in 30.015068s
2023-03-28T21:49:03.9726608Z 
```

**Comment by tebeco** [comment]
@eerhardt 
should i close it at this point ?

**Comment by tebeco** [comment]
should this be closed ?

**Comment by tebeco** [comment]
closing as "Not Planned" because i don't feel like it's prioritized (not me to judge that)

feel free to re-open
