### ISSUE TITLE
Test failure: BlazorServerTemplateWorks_NoAuth

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#20172]
https://dev.azure.com/dnceng/public/_build/results?buildId=573684&view=ms.vss-test-web.build-test-results-tab&runId=17989716&resultId=100011&paneView=debug

<details>
<summary>Error</summary>

```
OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: Current count: 1
Actual: Current count: 0
 at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer1 comparer) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\EqualityAsserts.cs:line 40
 at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 74
 at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass16_01.<WaitAssertCore>b__0(IWebDriver ) in //src/Shared/E2ETesting/WaitAssert.cs:line 100
Screen shot captured at 'F:\workspace\_work\1\s\artifacts\TestResults\Release\ProjectTemplates.Tests\8d6ea42696df493da5a51bef15956f3a.png'
Encountered browser errors
[2020-03-25T23:29:57Z] [Info] https://localhost:50863/_framework/blazor.server.js 0:5359 "[2020-03-25T23:29:57.084Z] Information: Normalizing '_blazor' to 'https://localhost:50863/_blazor'."
[2020-03-25T23:30:02Z] [Info] https://localhost:50863/_framework/blazor.server.js 0:5359 "[2020-03-25T23:29:57.505Z] Information: WebSocket connected to wss://localhost:50863/_blazor?id=wXSTzHmh9YZV4R9olS75zQ."
[2020-03-25T23:30:06Z] [Severe] https://localhost:50863/_framework/blazor.server.js 0:5162 "[2020-03-25T23:30:03.278Z] Error: Connection disconnected with error 'Error: WebSocket closed with status code: 1006 ().'."
[2020-03-25T23:30:06Z] [Info] https://localhost:50863/_framework/blazor.server.js 0:5359 "[2020-03-25T23:30:06.282Z] Information: Normalizing '_blazor' to 'https://localhost:50863/_blazor'."
[2020-03-25T23:30:06Z] [Warning] https://localhost:50863/_framework/blazor.server.js 0:5259 "[2020-03-25T23:30:06.963Z] Warning: Error from HTTP request. TypeError: Failed to fetch."
[2020-03-25T23:30:06Z] [Severe] https://localhost:50863/_framework/blazor.server.js 0:5162 "[2020-03-25T23:30:06.964Z] Error: Failed to complete negotiation with the server: TypeError: Failed to fetch"
[2020-03-25T23:30:06Z] [Severe] https://localhost:50863/_framework/blazor.server.js 0:5162 "[2020-03-25T23:30:06.965Z] Error: Failed to start the connection: TypeError: Failed to fetch"
[2020-03-25T23:30:06Z] [Severe] https://localhost:50863/_framework/blazor.server.js 14:27306 "[2020-03-25T23:30:06.966Z] Error: TypeError: Failed to fetch"
[2020-03-25T23:30:06Z] [Severe] https://localhost:50863/_framework/blazor.server.js 14:27306 "[2020-03-25T23:30:06.968Z] Error: Error: Cannot send data if the connection is not in the 'Connected' State."
[2020-03-25T23:30:07Z] [Info] https://localhost:50909/_framework/blazor.server.js 0:5359 "[2020-03-25T23:30:07.063Z] Information: Normalizing '_blazor' to 'https://localhost:50909/_blazor'."
[2020-03-25T23:30:12Z] [Info] https://localhost:50909/_framework/blazor.server.js 0:5359 "[2020-03-25T23:30:07.420Z] Information: WebSocket connected to wss://localhost:50909/_blazor?id=QgbEYgBcbuSBSI-4cRrJEQ."
[2020-03-25T23:34:46Z] [Severe] https://localhost:50909/_framework/blazor.server.js 0:5162 "[2020-03-25T23:30:13.205Z] Error: Connection disconnected with error 'Error: WebSocket closed with status code: 1006 ().'."
[2020-03-25T23:34:46Z] [Info] https://localhost:50909/_framework/blazor.server.js 0:5359 "[2020-03-25T23:30:16.212Z] Information: Normalizing '_blazor' to 'https://localhost:50909/_blazor'."
[2020-03-25T23:34:46Z] [Severe] https://localhost:50909/_blazor/negotiate?negotiateVersion=1 - Failed to load resource: net::ERR_CONNECTION_REFUSED
[2020-03-25T23:34:46Z] [Warning] https://localhost:50909/_framework/blazor.server.js 0:5259 "[2020-03-25T23:30:18.244Z] Warning: Error from HTTP request. TypeError: Failed to fetch."
[2020-03-25T23:34:46Z] [Severe] https://localhost:50909/_framework/blazor.server.js 0:5162 "[2020-03-25T23:30:18.245Z] Error: Failed to complete negotiation with the server: TypeError: Failed to fetch"
[2020-03-25T23:34:46Z] [Sev






```

</details>

<details>
<summary>Stacktrace</summary>

```
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 120
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore(IWebDriver driver, Action assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 75
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.Equal[T](IWebDriver driver, T expected, Func`1 actual) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 24
   at Templates.Test.BlazorServerTemplateTest.TestBasicNavigation() in /_/src/ProjectTemplates/test/BlazorServerTemplateTest.cs:line 158
   at Templates.Test.BlazorServerTemplateTest.BlazorServerTemplateWorks_NoAuth() in /_/src/ProjectTemplates/test/BlazorServerTemplateTest.cs:line 74
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 74
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass16_0`1.<WaitAssertCore>b__0(IWebDriver _) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 100
```

</details>

**Comment by ajaybhargavb** [comment]
@pranavkm @SteveSandersonMS @javiercn can you take a look?

**Comment by pranavkm** [comment]
The test has been unskipped. In addtion, I've added some retries to see if that help. Unfortunately the lack of any logs makes it difficult to understand why this failed in the first place: https://github.com/dotnet/aspnetcore/pull/21711

**Comment by HaoK** [comment]
Note: this test is still quarantined (and fails still: https://dev.azure.com/dnceng/public/_build/results?buildId=841815&view=ms.vss-test-web.build-test-results-tab&runId=26815232&resultId=100001&paneView=debug) https://github.com/dotnet/aspnetcore/blob/master/src/ProjectTemplates/BlazorTemplates.Tests/BlazorServerTemplateTest.cs#L30

**Comment by HaoK** [comment]
Same issue appears to be tracking BlazorServerTemplateWorks_[IndividualAuth/NoAuth], altho those fail with a different error: 

```
OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.ContainsException: Assert.Contains() Failure\r\nNot found: Information: WebSocket connected to\r\nIn value:  \r\n   at ```

**Comment by HaoK** [comment]
Will track as part of https://github.com/dotnet/aspnetcore/issues/25826
