### ISSUE TITLE
Signal R Core Java Client Crashing

### ISSUE THREAD

**Issue by jaragones** [dotnet/aspnetcore#20187]
**Describe the bug**
When using the Java client SDK for Signal R Core, it crashes  when the socket pipe had broken. I attach a log through Firebase and this issue couldn't been reproduce on my own device.

**To Reproduce**
I couldn't reproduce/replicate this issue. Only information available is stack trace.

**Stack trace is...**

```
Fatal Exception: io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.RuntimeException: javax.net.ssl.SSLException: Write error: ssl=0x765d82cf08: I/O error during system call, Broken pipe
       at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
       at io.reactivex.subjects.CompletableSubject.onError(CompletableSubject.java:131)
       at com.microsoft.signalr.OkHttpWebSocketWrapper$SignalRWebSocketListener.onFailure(OkHttpWebSocketWrapper.java:97)
       at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:570)
       at okhttp3.internal.ws.RealWebSocket.lambda$new$0$RealWebSocket(RealWebSocket.java:161)
       at okhttp3.internal.ws.-$$Lambda$RealWebSocket$vImgSP5IPT4ir3b3bHxPQ53ps8k.run(:2)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

```
Caused by java.lang.RuntimeException: javax.net.ssl.SSLException: Write error: ssl=0x765d82cf08: I/O error during system call, Broken pipe
       at com.microsoft.signalr.OkHttpWebSocketWrapper$SignalRWebSocketListener.onFailure(OkHttpWebSocketWrapper.java:97)
       at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:570)
       at okhttp3.internal.ws.RealWebSocket.lambda$new$0$RealWebSocket(RealWebSocket.java:161)
       at okhttp3.internal.ws.-$$Lambda$RealWebSocket$vImgSP5IPT4ir3b3bHxPQ53ps8k.run(:2)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

```
Caused by javax.net.ssl.SSLException: Write error: ssl=0x765d82cf08: I/O error during system call, Broken pipe
       at com.android.org.conscrypt.NativeCrypto.SSL_write(NativeCrypto.java)
       at com.android.org.conscrypt.NativeSsl.write(NativeSsl.java:426)
       at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLOutputStream.write(ConscryptFileDescriptorSocket.java:660)
       at okio.Okio$1.write(Okio.java:79)
       at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
       at okio.RealBufferedSink.emit(RealBufferedSink.java:186)
       at okhttp3.internal.ws.WebSocketWriter.writeMessageFrame(WebSocketWriter.java:212)
       at okhttp3.internal.ws.WebSocketWriter$FrameSink.close(WebSocketWriter.java:252)
       at okio.RealBufferedSink.close(RealBufferedSink.java:248)
       at okhttp3.internal.ws.RealWebSocket.writeOneFrame(RealWebSocket.java:500)
       at okhttp3.internal.ws.RealWebSocket.lambda$new$0$RealWebSocket(RealWebSocket.java:158)
       at okhttp3.internal.ws.-$$Lambda$RealWebSocket$vImgSP5IPT4ir3b3bHxPQ53ps8k.run(:2)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

**Further technical details**
+ signalR 5.0.0-preview (installed using gradle: implementation 'com.microsoft.signalr:signalr:+')

**Comment by BrennanConroy** [comment]
Do you have a java app that you're willing to share that the issue has happened in?

**Comment by jaragones** [comment]
For contract, I cannot share app, there is something that you are specifically interested with? I tried to debug it and reproduce the issue for few days, and I couldn't reproduce it.

**Comment by BrennanConroy** [comment]
We've been unable to repro the problem in a simple Java app, so any info you can give about an app that has this issue would be helpful.

**Comment by anurse** [comment]
The crash generally occurs if you have not registered an `onError` callback on any of the Rx primitives returned by SignalR's async operations (like `.start`, `.invoke`, etc.). As a first step, it would be good to review your usage of those and make sure you've registered `onError` callbacks (using either `.subscribe` or something like [`.doOnError`](https://javadoc.io/doc/io.reactivex/rxjava/1.2.1/rx/Completable.html#doOnError(rx.functions.Action1))).

That would also allow you to better detect these places where you are getting broken pipe errors.

If you can share code from around the places you call SignalR (i.e. where and how do you call `.start`, `.stop`, `.on`, `.invoke`, etc.) that would be useful.

**Comment by anurse** [comment]
Triage Notes: While the information requested by the above comment is still useful, we do think there's one place we might have a missing `onError` callback in our own code which we'll take a look at.

**Comment by jaragones** [comment]
At the moment of the crash, I didn't have any implementation "hubConnection.onClosed", now I added:

```
        hubConnection.onClosed(new OnClosedCallback() {
            @Override
            public void invoke(Exception exception) {
                if (exception != null) {
                    reconnecting = true;
                    new Handler(Looper.getMainLooper()).post(new Runnable() {
                        @Override
                        public void run() {
                            reconnectionAfterInternetDown(context, connectionType, listener, retry);
                        }
                    });
                }
            }
        });

```

@anurse, you meant this call, right?

**Comment by BrennanConroy** [comment]
I'd love to know the structure of the app, specifically around threading and what environment it runs in.

Also, we think we know what a fix would look like, but since we don't have any app that repros the issue, would you be willing to test a custom jar for us? Or build the repo yourself with the small change?

**Comment by jaragones** [comment]
Main issue, is that I only saw this crash reported on firebase once and I couldn't reproduce it, but it wouldn't be a big issue if you need to test your fix. Is there a way to contact you directly to share some code?

**Comment by BrennanConroy** [comment]
Yeah, feel free to email me: brecon at microsoft.com

**Comment by BrennanConroy** [comment]
Haven't heard back from you, if you're interested, could you check out https://github.com/dotnet/aspnetcore/tree/brecon/javaerror and go to the "src/SignalR/clients/java/signalr" folder and run `gradlew createPackage`. Then try out your scenario with the jar created.

One way that might help to reproduce the issue is to pull the ethernet cord from the computer the client is on when connected to a remote server, or to kill the server process (hard kill like kill -9 on linux, or end task on windows).

**Comment by jaragones** [comment]
Hey, I was working in another task, I will be back to this issue next days.

**Comment by jaragones** [comment]
@BrennanConroy , I just sent you an email.
