### ISSUE TITLE
Exit code 139 as part of RunTests.TestRunner.InstallAspNetAppIfNeededAsync

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#20219]
```
'/home/helixbot/work/A22508F7/w/BE2309D4/e/.dotnet18061/dotnet nuget list source' completed with exit code '139'
Exception in InstallAspNetAppIfNeeded: System.InvalidOperationException: Command /home/helixbot/work/A22508F7/w/BE2309D4/e/.dotnet18061/dotnet nuget list source returned exit code 139 output: 
   at RunTests.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, CancellationToken cancellationToken) in /home/helixbot/work/A22508F7/w/BE2309D4/e/RunTests/ProcessUtil.cs:line 144
   at RunTests.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, CancellationToken cancellationToken) in /home/helixbot/work/A22508F7/w/BE2309D4/e/RunTests/ProcessUtil.cs:line 144
   at RunTests.TestRunner.InstallAspNetAppIfNeededAsync() in /home/helixbot/work/A22508F7/w/BE2309D4/e/RunTests/TestRunner.cs:line 134
```

---------------------------------
There test `Template_Produces_The_Right_Set_Of_FilesAsync(arguments: "new mvc -au MultiOrg --aad-instance https://login."..., expectedFiles: ["appsettings.Dev)` failed due to a 139 exit code.

https://dev.azure.com/dnceng/internal/_build/results?buildId=574320&view=ms.vss-test-web.build-test-results-tab&runId=18013826&resultId=120446&paneView=debug

Need to investigate and quarantine it if necessary.

**Comment by BrennanConroy** [comment]
Core dump available at https://dev.azure.com/dnceng/internal/_build/results?buildId=574320&view=ms.vss-test-web.build-test-results-tab&runId=18013826&resultId=120463&paneView=attachments

Also, a previous failure of the same type: https://github.com/dotnet/aspnetcore/pull/19976

**Comment by BrennanConroy** [comment]
Yet another one https://dev.azure.com/dnceng/public/_build/results?buildId=577215&view=ms.vss-test-web.build-test-results-tab&runId=18127966&resultId=120453&paneView=debug

**Comment by BrennanConroy** [comment]
Was bored (nerd sniped?) and filed https://github.com/dotnet/runtime/issues/34231 for this.

**Comment by pranavkm** [comment]
Thanks for the investigation @BrennanConroy. Marking this as blocked until we can get a resolution from runtime.

**Comment by pranavkm** [comment]
@HaoK assigning to you - looks like https://github.com/dotnet/aspnetcore/pull/21639 covers this.

**Comment by BrennanConroy** [comment]
This is a runtime bug and not limited to `InstallAspNetAppIfNeededAsync`, it's mostly just tracking the issue so build ops folks who see the problem have an issue to link to.

**Comment by BrennanConroy** [comment]
Fix merged into runtime and now consumed by aspnet
