### ISSUE TITLE
Copying exceptions from the browser console is hard

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#20280]
If an unhandled exception occurs in a Blazor WebAssembly app it shows up in the browser console:

![image](https://user-images.githubusercontent.com/1874516/77837051-5a389480-7119-11ea-9699-fe3bc5d69b08.png)

But copying this error information is pretty messy. If I try to just select and do a copy & paste I get something like this:

```
Failed to load resource: the server responded with a status of 500 ()
blazor.webassembly.js:1 ﻿crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1       Unhandled exception rendering component: Could not load settings from '_configuration/Microsoft.AspNetCore.Components.WebAssembly.Authentication'
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1       Error: Could not load settings from '_configuration/Microsoft.AspNetCore.Components.WebAssembly.Authentication'
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1           at Function.createUserManager (https://localhost:44381/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js:1:4664)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1           at async Function.init (https://localhost:44381/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js:1:4124)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 Microsoft.JSInterop.JSException: Could not load settings from '_configuration/Microsoft.AspNetCore.Components.WebAssembly.Authentication'
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 Error: Could not load settings from '_configuration/Microsoft.AspNetCore.Components.WebAssembly.Authentication'
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1     at Function.createUserManager (https://localhost:44381/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js:1:4664)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1     at async Function.init (https://localhost:44381/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js:1:4124)
p.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1   at System.Threading.Tasks.ValueTask`1[TResult].get_Result () <0x2dbdc40 + 0x0002c> in <filename unknown>:0 
...
```

Is there anyway we can make it easier and cleaner to report this error information?

**Comment by captainsafia** [comment]
Closing and marking as done since this bug fix has been merged.
