### ISSUE TITLE
System.Net.Security not found as system-account

### ISSUE THREAD

**Issue by thepill** [dotnet/aspnetcore#20350]
### Describe the bug
We are running a windows service using dotnet core 3.1 and kestrel. Sometimes we encounter TLS-errors on specific systems which we can not recover from. The service is deployed as self-contained on windows server 2012-2019. The error occurs from time to time on a small number of systems (2-3 of about 800, not always the same systems)

```
 An unhandled exception occurred while processing the request.
 IOException: Authentication failed because the remote party has closed the transport stream. 
```

We tracked the error down to something strange
If the app/service is running as an `adminstrator-account` it works as usually.

If the app/service is running as the `system-account` the following exception occurs on every connect:

```
fail: Microsoft.AspNetCore.Server.Kestrel[0]
      Unhandled exception while processing 0HLUL8TM12DH8.
System.IO.FileNotFoundException:
File name: 'System.Net.Security, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.<>c__DisplayClass7_0.<OnConnectionAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection.ExecuteAsync()
```

### Further technical details

```csharp
.UseKestrel(options =>
                {
                    options.ConfigureHttpsDefaults(c =>
                    {
                        c.SslProtocols = System.Security.Authentication.SslProtocols.Tls12;
                    });
                    options.ListenAnyIP(1010, listenOptions =>
                    {
                        if (hostingEnvironment.IsDevelopment())
                        {
                            listenOptions.UseHttps();
                        }
                        else
                        {
                            listenOptions.UseHttps(@"C:\bla.pfx", "<secret>");
                        }
                    });
                });
```

publish profile:
```xml
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <WebPublishMethod>FileSystem</WebPublishMethod>
    <PublishProvider>FileSystem</PublishProvider>
    <LastUsedBuildConfiguration>Release</LastUsedBuildConfiguration>
    <LastUsedPlatform>Any CPU</LastUsedPlatform>
    <SiteUrlToLaunchAfterPublish />
    <LaunchSiteAfterPublish>True</LaunchSiteAfterPublish>
    <ExcludeApp_Data>False</ExcludeApp_Data>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>True</PublishSingleFile>
    <ProjectGuid>7a2bf81b-e7ac-4d4a-8918-bb3ca08fcd0a</ProjectGuid>
    <SelfContained>true</SelfContained>
    <publishUrl>publish</publishUrl>
    <DeleteExistingFiles>False</DeleteExistingFiles>
  </PropertyGroup>
</Project>
```

Dependencies
```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Hosting.WindowsServices" Version="3.1.0" />
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="3.1.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="3.2.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
    <PackageReference Include="Serilog.Sinks.RollingFile" Version="3.3.0" />
  </ItemGroup>
```

**Comment by thepill** [comment]
Minor Update:

It also seems to work (on a not working system) if `NT Authority\NetworkService` is used instead of `System`

**Comment by anurse** [comment]
@bartonjs does this error seem familiar to you? Looks like an error loading System.Net.Security but only when running in a certain user account.

@thepill to confirm: this only happens when running as `System`?

**Comment by thepill** [comment]
@anurse yes - until now the error only happens when ran as the user `system` - the strange thing is, that the error will eventually go away if i redeploy the app several times - until the next system fails after some period of time

**Comment by anurse** [comment]
Moving this to runtime for now to help investigate a load issue with a runtime assembly (System.Net.Security).
