### ISSUE TITLE
[Blazor Wasm] Use of roles or policies for authorization

### ISSUE THREAD

**Issue by mihaimyh** [dotnet/aspnetcore#20436]
I am trying to figure out how to secure pages in Blazor Wasm using roles or policies but I am not sure what I am missing.

What I have done is to add in `Startup.cs` of the server project the following code to map claims and roles from database:

```
           services.AddIdentityServer()
                .AddApiAuthorization<IdentityUser, ApplicationDbContext>()
                .AddProfileService<ProfileService>();
```

    public class ProfileService : IProfileService
    {
        protected UserManager<ApplicationUser> _userManager;
        private readonly IUserClaimsPrincipalFactory<ApplicationUser> _claimsFactory;

        public ProfileService(UserManager<ApplicationUser> userManager, IUserClaimsPrincipalFactory<ApplicationUser> claimsFactory)
        {
            _userManager = userManager;
            _claimsFactory = claimsFactory;
        }

        public async Task GetProfileDataAsync(ProfileDataRequestContext context)
        {
            var sub = context.Subject.GetSubjectId();
            var user = await _userManager.FindByIdAsync(sub);
            var principal = await _claimsFactory.CreateAsync(user);

            var claims = principal.Claims.ToList();

            var claimsInDb = await _userManager.GetClaimsAsync(user);

            var mappedClaims = new List<Claim>();
            foreach (var claim in claimsInDb)
            {
                if (claim.Type == ClaimTypes.Role)
                {
                    mappedClaims.Add(new Claim(JwtClaimTypes.Role, claim.Value));
                }
                else
                {
                    mappedClaims.Add(claim);
                }
            }

            claims.AddRange(mappedClaims);

            context.IssuedClaims = claims;

        }

        public async Task IsActiveAsync(IsActiveContext context)
        {
            var sub = context.Subject.GetSubjectId();
            var user = await _userManager.FindByIdAsync(sub);
            context.IsActive = user != null;
        }
    }

This also adds `role: "Admin"` to the access token.

![image](https://user-images.githubusercontent.com/549272/78196928-a7579600-748c-11ea-8b0a-eeae4b5b03f0.png)

I am still getting unauthorized when applying `@attribute [Authorize(Roles = "Admin")]` to FetchData page.

Furthermore, on the server side I've created a policy which requires admin role:

            services.AddAuthorization(authorizationOptions =>
            {
                authorizationOptions.AddPolicy("IsAdmin", policyBuilder =>
                {
                    policyBuilder.RequireRole("Admin");

                });
            });

and I've applied this policy to a controller, but I am still getting `403 (Forbidden)` when calling that endpoint:

    [Route("[controller]")]
    [ApiController]
    [Authorize(Policy = "IsAdmin")]
    public class UsersController : ControllerBase
    {
        private readonly ILogger<UsersController> _logger;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UsersController(ILogger<UsersController> logger, UserManager<ApplicationUser> userManager,
                               RoleManager<IdentityRole> roleManager)
        {
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
            _userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
            _roleManager = roleManager ?? throw new ArgumentNullException(nameof(roleManager));
        }

        [HttpGet()]
        public IActionResult GetUsers() => Ok(_userManager.Users);

    }

What should I do more?

**Comment by javiercn** [comment]
* Configure Identity to use roles by calling AddRoles
  ```csharp
  services.AddDefaultIdentity<ApplicationUser>(options => options.SignIn.RequireConfirmedAccount = true)
      .AddRoles<IdentityRole>()
      .AddEntityFrameworkStores<ApplicationDbContext>();
  ```
* Configure identity server to put the role claim into the id token and the access token and prevent the default mapping for roles in the JwtSecurityTokenHandler.
  ```csharp
  services.AddIdentityServer()
      .AddApiAuthorization<ApplicationUser, ApplicationDbContext>(options => {
          options.IdentityResources["openid"].UserClaims.Add("role");
          options.ApiResources.Single().UserClaims.Add("role");
      });
  
  // Need to do this as it maps "role" to ClaimTypes.Role and causes issues
  JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Remove("role");
  ```
* On your blazor application use `[Authorize(Roles = "admin")]` or any other role your app defines.
* On your protected resource APIs use `[Authorize(Roles = "admin")]` or any other role your app defines.

You can then create your own policies as normal.

**Comment by mihaimyh** [comment]
@javiercn Thanks for guiding, I will try it and revert, can you also, please, let me know, where in Blazor Wasm can I create a policy?

**Comment by mihaimyh** [comment]
@javiercn I followed your guide but I am still having issues on the client side. 

Using `@attribute [Authorize(Roles="Admin")]` I am still getting Access denied.

Calling the API endpoint works though.

**Comment by mihaimyh** [comment]
@javiercn @SteveSandersonMS @danroth27 

I don't know if this is the correct way of creating a policy in Wasm but I've added the following in `Program.cs`:

            builder.Services.AddApiAuthorization();
            builder.Services.AddAuthorizationCore(config =>
            {
                config.AddPolicy("IsAdmin", policyBuilder =>
                {
                    policyBuilder.RequireRole("Admin");

                });
            });

And on `FetchData` component `@attribute [Authorize(Policy = "IsAdmin")]` and I am still getting `Access Denied`.

Should a claim named `role` be in `id_token`? Currently it isn't, see the token below.

`eyJhbGciOiJSUzI1NiIsImtpZCI6IkRldmVsb3BtZW50IiwidHlwIjoiSldUIn0.eyJuYmYiOjE1ODU5Njk3MTMsImV4cCI6MTU4NTk3MDAxMywiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NTAwMSIsImF1ZCI6Ik1vdmluZ1BpY3R1cmVzRXZlbnRzLldlYi5DbGllbnQiLCJpYXQiOjE1ODU5Njk3MTMsImF0X2hhc2giOiI3c3A3MmxfR281NWtyanZSeGEzSE93Iiwic19oYXNoIjoiazhvN1RfYnhBX0g1RlJTUjg0cW95dyIsInNpZCI6IkQ5VHpMRlhyVHE3dHlBWGtMcDMwbFEiLCJzdWIiOiI2ZTM5YWY3ZC1jNjYzLTQ4ZWEtYWIwMi0xZWYxYzk4ZWViOWMiLCJhdXRoX3RpbWUiOjE1ODU5Njk3MTIsImlkcCI6ImxvY2FsIiwiYW1yIjpbInB3ZCJdfQ.ZT8C-HASht3Mz-WeDOkd_DHrQgTuaSgMDLyzxgavbZZ03auHvc3yvtHj-NVlB4WltGfLRr4M24WThRcDsWSdT116DddFXn6ArbChCRlMcClb7yxU7CB5Zer5MgSXPF8bkcATksdyJLpE9i1PMeSlF7t_eKTzpdiKzPUBEIIGHpxky5d6sXl0CL2TZYEoWL0uKtwr_09Z7Fu7P7Xw5vSCM88JSoUPYp0ioUsNoPbniQAGzq8iK-Um4MtER2SoKreupQEFJyM2gUlXTsZqDdWEKZyFa4HeXqTibFCztcJ5ImyiiU6DaKUTm-kSKIuhar5OtGRc-GafTMzrNJdzjyVuyA`

Any help will be highly appreciated.

**Comment by mihaimyh** [comment]
So it seems I was not building the policy properly on the client side. I should be using `RequireClaim` instead of `RequireRole`:

            builder.Services.AddAuthorizationCore(config =>
            {
                config.AddPolicy("IsAdmin", policyBuilder =>
                {
                    policyBuilder.RequireClaim("role","Admin");

                });
            });

**Comment by boukenka** [comment]
If this helps, you can read great Chris Sainty's articles (4) on "_Securing your Blazor applications_" from here: https://chrissainty.com/securing-your-blazor-apps-introduction-to-authentication-with-blazor/. The last 2 posts are about roles and policy.

**Comment by javiercn** [comment]
@mihaimyh It is likely that the role claim in `RemoteAuthenticationOptions.UserOptions.RoleClaim` is not configured. If you set that to "role" you should be able to use RequireRole.

**Comment by mihaimyh** [comment]
> @mihaimyh It is likely that the role claim in `RemoteAuthenticationOptions.UserOptions.RoleClaim` is not configured. If you set that to "role" you should be able to use RequireRole. We did a fix for this, but it has not been released yet I think.

@javiercn I've tried your suggestion by adding in Blazor Client on `Program.cs` the following:

` builder.Services.AddApiAuthorization(opt => opt.UserOptions.RoleClaim = "role");
`

and to create the claim:

        public static AuthorizationPolicy IsAdminPolicy()
        {
            return new AuthorizationPolicyBuilder().RequireAuthenticatedUser()
                                                   .RequireRole("Admin")
                                                   .Build();
        }

but when I run the app I am getting the following exception in the console:

```
[00:11:02 Error] Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware
An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Client 'Microsoft.AspNetCore.Components.WebAssembly.Authentication' not found.
   at Microsoft.AspNetCore.ApiAuthorization.IdentityServer.ClientCollection.get_Item(String key)
   at Microsoft.AspNetCore.ApiAuthorization.IdentityServer.DefaultClientRequestParametersProvider.GetClientParameters(HttpContext context, String clientId)
   at MovingPicturesEvents.Web.Server.Controllers.OidcConfigurationController.GetClientRequestParameters(String clientId) in G:\Users\mdumi\GitRepos\LaurKyt\src\Server\Controllers\OidcConfigurationController.cs:line 22
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
   at IdentityServer4.Hosting.MutualTlsTokenEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by javiercn** [comment]
@mihaimyh that looks like a completely unrelated problem.

The value being sent to the OidcConfigurationController (in your project template) doesn't match the value in the clients section of appsettings.json. Not sure why that's the reason in your case.

**Comment by Thoorium** [comment]
Good news! With Blazor WebAssembly 3.2.0 Preview 4 the issue seems to be _partially_ fixed but with the modifications from @javiercn it now works. https://github.com/dotnet/aspnetcore/issues/20436#issuecomment-607718936 

One thing, I didn't include the following lines and it seems to work just fine. Am I missing something or this was also fixed?
```c#
// Need to do this as it maps "role" to ClaimTypes.Role and causes issues
JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Remove("role");
```

Anyway, cheers!
