### ISSUE TITLE
Unhandled exception rendering component: Microsoft.JSInterop.JSException: Cannot read property 'ownerDocument' of null

### ISSUE THREAD

**Issue by gustavnavar** [dotnet/aspnetcore#20448]
I posted a comment in the issue [#19647](https://github.com/dotnet/aspnetcore/issues/19647#issuecomment-606732583), but it's a closed one. So I open a new issue.

I think I have the same issue than @AlexCorona55.

I work with the [GridBlazor](https://github.com/gustavnavar/Grid.Blazor) component. The WA demo project [GridBlazorClientSide.Client](https://github.com/gustavnavar/Grid.Blazor/tree/master/GridBlazorClientSide.Client) is the one getting these exceptions.

The project was working with no exceptions with  3.2.0-preview2 (commit https://github.com/gustavnavar/Grid.Blazor/commit/e1aa226db0f7befa0108aa5e47143c799aac90b7)

As soon as I upgraded to 3.2.0-preview3 the code started throwing the following exception when rendering this component [ButtonCellEdit](https://github.com/gustavnavar/Grid.Blazor/blob/master/GridBlazorClientSide.Client/Pages/ButtonCellEdit.razor) and it's locked after opening it:

```
﻿crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot read property 'ownerDocument' of null
      TypeError: Cannot read property 'ownerDocument' of null
          at e.updateComponent (https://localhost:44377/_framework/blazor.webassembly.js:1:12763)
          at Object.t.renderBatch (https://localhost:44377/_framework/blazor.webassembly.js:1:1704)
          at Object.window.Blazor._internal.renderBatch (https://localhost:44377/_framework/blazor.webassembly.js:1:33252)
          at _mono_wasm_invoke_js_unmarshalled (https://localhost:44377/_framework/wasm/dotnet.3.2.0-preview3.20168.1.js:1:162187)
          at wasm_invoke_iiiiii (wasm-function[3152]:0x9d1fe)
          at icall_trampoline_dispatch (wasm-function[5757]:0xfed16)
          at mono_wasm_interp_to_native_trampoline (wasm-function[4591]:0xcc134)
          at ves_pinvoke_method (wasm-function[3201]:0x9ebfa)
          at interp_exec_method (wasm-function[1115]:0x2564d)
          at interp_runtime_invoke (wasm-function[5637]:0xf8709)
Microsoft.JSInterop.JSException: Cannot read property 'ownerDocument' of null
```

I used the [workaround](https://github.com/dotnet/aspnetcore/issues/19647#issuecomment-601321626) mentioned by @AlexCorona55, and the app gets no lock anymore, but exceptions continue appearing on the debug console.

I can not find the source of the problem in my code. I think it comes from the Blazor WA packages, but I'm not sure.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We don't look into complete projects as that involves too many moving parts. Can you please provide a minimal repro project for us to investigate?

On a side note, this particular component seems to be doing something weird. We haven't modified the code related to this for quite a while now. We recommend bringing this up with the component owners as a starting point.

**Comment by gustavnavar** [comment]
I found the error. It was a silly one, but I took me a lot of time debugging.

During the upgrade process I duplicated this line in ```Program.cs``` file of the client app:
```
    builder.RootComponents.Add<App>("app");
```

Thanks for your help
