### ISSUE TITLE
Removing Microsoft.AspNetCore.Blazor.HttpClient package causes fatal error in Mono IL Linker

### ISSUE THREAD

**Issue by NikolayIT** [dotnet/aspnetcore#20552]
### Describe the bug

I am writing a demo project using _Blazor WebAssembly 3.2.0 Preview 3_ (The source code is located on https://github.com/NikolayIT/MusicX)

When I remove the `Microsoft.AspNetCore.Blazor.HttpClient` reference from my Blazor WebAssembly project and try to **publish** I get the following error (when I build and run locally the application everything is OK):

```
2>Fatal error in Mono IL Linker
2>C:\Users\Nikolay\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview3.20168.3\targets\Blazor.MonoRuntime.targets(247,5): error : Unhandled exception. Mono.Linker.Steps.XmlResolutionException: Failed to process XML description: <unspecified>
2> ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.AspNetCore.Blazor.HttpClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
2> ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.AspNetCore.Blazor.HttpClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
2>   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
2>   at Mono.Linker.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
2>   at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
2>   at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
2>   at Mono.Linker.Steps.ResolveFromXmlStep.ProcessAssemblies(LinkContext context, XPathNodeIterator iterator)
2>   at Mono.Linker.Steps.ResolveFromXmlStep.Process()
2>   --- End of inner exception stack trace ---
2>   at Mono.Linker.Steps.ResolveFromXmlStep.Process()
2>   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
2>   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
2>   at Mono.Linker.Pipeline.Process(LinkContext context)
2>   at Mono.Linker.Driver.Run(ILogger customLogger)
2>   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
2>   at Mono.Linker.Driver.Main(String[] args)
2>C:\Users\Nikolay\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview3.20168.3\targets\Blazor.MonoRuntime.targets(247,5): error : ILLink failed with exit code -532462766.
```

### Further technical details
- ASP.NET Core version 3.1.3
- Blazor WebAssembly 3.2.0 Preview 3
- Microsoft Visual Studio Enterprise 2019 Version 16.5.2
- Include the output of `dotnet --info`:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by NikolayIT** [comment]
Updating to Blazor WebAssembly 3.2.0 Preview 4 fixes this issue.
I suppose you can close it.
