### ISSUE TITLE
[blazor-server] JsonException in custom JsonConverter fatal to circuit even if handled

### ISSUE THREAD

**Issue by MichelJansson** [dotnet/aspnetcore#20581]
### Describe the bug
Throwing a `System.Text.Json.JsonException` inside a custom `JsonConverter<T>` as described in [the docs](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to?view=netcore-3.1#error-handling), breaks the circuit with the below browser error, even though the exception was catched by the method calling `JSRuntime.InvokeAsync<T>`, that caused the deserialization, as per [the docs](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to?view=netcore-3.1#error-handling)

```
Error: System.Text.Json.JsonException: Invalid JSON
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.EndInvokeJS(JSRuntime jsRuntime, String arguments)
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.<>c__DisplayClass43_0.<EndInvokeJSFromDotNet>b__0()
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<InvokeAsync>b__8_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.EndInvokeJSFromDotNet(Int64 asyncCall, Boolean succeded, String arguments)
e.log @ blazor.server.js:15
C @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:1
e.invokeClientMethod @ blazor.server.js:1
e.processIncomingData @ blazor.server.js:1
connection.onreceive @ blazor.server.js:1
i.onmessage @ blazor.server.js:1

```

### To Reproduce
- Create custom JsonConverter for `MyModel` that throws a `JsonException`
- Decorate `MyModel` class with this custom converter `[JsonConverter(typeof(MyCustomConveter))]`
- Call js method that returns object to deserialize using IJSRuntime
``` C#
private async Task GetJsObj() {
    try {
        var response = await jsRuntime.InvokeAsync<MyModel>(eval, "({myProp: 'myValue'})");
    }
    catch (Exception e) {
        // The exception is catched here...
    }
}
// ...But the circuit will break here with the above browser error
```

**Doing the exact same thing, but throwing an `System.Exception` instead, it all works as expected.**

### Further technical details
- ASP.NET Core version: **3.1**
```
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This is not something we plan to do in the near future. You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
