### ISSUE TITLE
Nuget update of several packages from 3.1.2 to 3.1.3 causes failure running ASP.NET MVC Core Self Contained on IIS

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#20625]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/978138/nuget-update-of-several-packages-from-312-to-313-c.html)._

---
Did an update of seven packages in NuGet and the site no longer functioned.

Reverted back to 3.1.2 and the problem went away.

---
#### Visual Studio Feedback System on 4/7/2020, 00:53 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Pilchie** [comment]
Tagging @wtgodbe and @joperezr.

**Comment by wtgodbe** [comment]
From the VS issue:

>Exception Info: System.AccessViolationException
   at System.Reflection.Metadata.Ecma335.CustomAttributeTableReader.GetConstructor(System.Reflection.Metadata.CustomAttributeHandle)
   at Microsoft.CodeAnalysis.PEModule.GetTypeAndConstructor(System.Reflection.Metadata.MetadataReader, System.Reflection.Metadata.CustomAttributeHandle, System.Reflection.Metadata.EntityHandle ByRef, System.Reflection.Metadata.EntityHandle ByRef)
   at Microsoft.CodeAnalysis.PEModule.IsTargetAttribute(System.Reflection.Metadata.MetadataReader, System.Reflection.Metadata.CustomAttributeHandle, System.String, System.String, System.Reflection.Metadata.EntityHandle ByRef, Boolean)
   at Microsoft.CodeAnalysis.PEModule.GetTargetAttributeSignatureIndex(System.Reflection.Metadata.MetadataReader, System.Reflection.Metadata.CustomAttributeHandle, Microsoft.CodeAnalysis.AttributeDescription)
   at Microsoft.CodeAnalysis.MetadataDecoder`5[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetTargetAttributeSignatureIndex(System.Reflection.Metadata.CustomAttributeHandle, Microsoft.CodeAnalysis.AttributeDescription)
   at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PEAttributeData.GetTargetAttributeSignatureIndex(Microsoft.CodeAnalysis.CSharp.Symbol, Microsoft.CodeAnalysis.AttributeDescription)

...

> at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Start[[Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<TryProcessEventCoreAsync>d__106, Microsoft.CodeAnalysis, Version=3.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]](<TryProcessEventCoreAsync>d__106 ByRef)

...

>    at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

May be related to https://github.com/dotnet/corefx/pull/42859, but not much evidence for that yet. A repro or info on the project file would be very useful

**Comment by Pilchie** [comment]
Closing as stale.
