### ISSUE TITLE
Test failures in OpenAPI

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#20628]
The following tests have failed: Microsoft.DotNet.OpenApi.Add.Tests.OpenApiAddURLTests.OpenApi_Add_URL_ActualResponse() in this build: https://dev.azure.com/dnceng/public/_build/results?buildId=586021&view=results

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg can you please take care of this? This one failed again 5 days ago.

Here are some more details:

### Error message

Threw error: The given url returned 'InternalServerError', indicating failure. The url might be wrong, or there might be a networking issue.

Expected: True

Actual: False


### Stack trace
   at Microsoft.DotNet.OpenApi.Tests.OpenApiTestBase.AssertNoErrors(Int32 appExitCode) in /_/src/Tools/Microsoft.dotnet-openapi/test/OpenApiTestBase.cs:line 116
   at Microsoft.DotNet.OpenApi.Add.Tests.OpenApiAddURLTests.OpenApi_Add_URL_ActualResponse() in /_/src/Tools/Microsoft.dotnet-openapi/test/OpenApiAddURLTests.cs:line 459

**Comment by ryanbrandenburg** [comment]
That test has been removed entirely: https://github.com/dotnet/aspnetcore/commit/cb523d73e27ce68113eeb26fd1c8b0cd5cc0c21c

**Comment by ryanbrandenburg** [comment]
The failure was on master, so this must just predate the change. Closing.
