### ISSUE TITLE
SignalR (Websockets) with azure linux app service .NET 3.1

### ISSUE THREAD

**Issue by AzizAK** [dotnet/aspnetcore#20636]
### Describe the bug
I'm using .NET 3.1 with SignalR (Websockets) working locally is fine on my Mac, but when I deployed to azure linux it stopped working for websockets. long-polling still working. but websockets return with ( failed to start connection error there was an error with transport) from the client.

I already turned on websockets from app service configuration. 

### To Reproduce
``` C#
services.AddSignalR();

... removed brevity 

app.UseEndpoints(endpoints =>
{
                endpoints.MapHub<GameHub>("/gamehub");
                endpoints.MapRazorPages();
                endpoints.MapControllerRoute(
                    name: "api",
                    pattern: "api/{controller=Home}/{action=Index}/{id?}");
            });
```

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.100/

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.0.3 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.2.101 [/usr/local/share/dotnet/sdk]
  3.1.100 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

- Rider 2019

**Comment by BrennanConroy** [comment]
Can you look at the server side logs to see if it's receiving the websockets request?
https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-3.1#server-side-logging

**Comment by AzizAK** [comment]
Hello Bennan, Thanks for the fast response.
When i try to connect from the client using web socket as transport with skipping negotiation. nothing logs comes to the server. (locally works fine)
```javascript
    var object = new signalR.HubConnectionBuilder()
      .withUrl(GAME_HUB_URL, {
        skipNegotiation: true,
        transport: signalR.HttpTransportType.WebSockets,
        accessTokenFactory: () => state.userReducer.user.token,
      })
      .configureLogging(signalR.LogLevel.Debug)
      .build();
```

but when switching to long polling here is the logs:

Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[1]
2020-04-08T10:59:47.723953947Z       Received hub invocation: InvocationMessage { InvocationId: "0", Target: "CreateRoom", Arguments: [  ], StreamIds: [  ] }.
2020-04-08T10:59:47.723957947Z [40m[37mdbug[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
2020-04-08T10:59:47.723961747Z       Connection id "0HLURL9P5UERJ" sending FIN because: "The Socket transport's send loop completed gracefully."
2020-04-08T10:59:47.731693492Z [40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
2020-04-08T10:59:47.731710192Z       Executed endpoint '/gamehub'
2020-04-08T10:59:47.732333896Z [40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Diagnostics[2]
2020-04-08T10:59:47.732347596Z       Request finished in 57.8195ms 200 application/octet-stream
2020-04-08T10:59:47.732352596Z [40m[37mdbug[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[10]
2020-04-08T10:59:47.732356896Z       Connection id "0HLURL9P5UERI" disconnecting.
2020-04-08T10:59:47.732361096Z [40m[37mdbug[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[2]
2020-04-08T10:59:47.732365596Z       Connection id "0HLURL9P5UERI" stopped.
2020-04-08T10:59:47.732369596Z [40m[37mdbug[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
2020-04-08T10:59:47.732373696Z       Connection id "0HLURL9P5UERI" sending FIN because: "The Socket transport's send loop completed gracefully."
2020-04-08T10:59:47.961300124Z [40m[37mdbug[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[39]
2020-04-08T10:59:47.961326024Z       Connection id "0HLURL9P5UERK" accepted.
2020-04-08T10:59:47.961709726Z [40m[37mdbug[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[1]
2020-04-08T10:59:47.961720526Z       Connection id "0HLURL9P5UERK" started.
2020-04-08T10:59:47.963107534Z OnTokenValidated: {"alg":"HS256","typ":"JWT"}.--------
2020-04-08T10:59:47.969689372Z [40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Hosting.Diagnostics[1]
2020-04-08T10:59:47.969724173Z       Request starting HTTP/1.1 GET http://dev-appname.azurewebsites.net/gamehub?id=vmLFXg_SngrgUrTIhL98Lw&_=1586343650750 text/plain; charset=UTF-8 0
2020-04-08T10:59:47.970415177Z [40m[37mdbug[39m[22m[49m: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[4]
2020-04-08T10:59:47.970427677Z       The request path /gamehub does not match a supported file type
2020-04-08T10:59:47.970432377Z [40m[37mdbug[39m[22m[49m: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1001]
2020-04-08T10:59:47.970436277Z       1 candidate(s) found for the request path '/gamehub'
2020-04-08T10:59:47.970439877Z [40m[37mdbug[39m[22m[49m: Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware[1]
2020-04-08T10:59:47.970443777Z       Request matched endpoint '/gamehub'
2020-04-08T10:59:47.970447177Z [40m[37mdbug[39m[22m[49m: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[9]
2020-04-08T10:59:47.970450877Z       AuthenticationScheme: Identity.Application was not authenticated.
2020-04-08T10:59:47.970454177Z [40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[2]
2020-04-08T10:59:47.970457877Z       Successfully validated the token.
2020-04-08T10:59:47.972257387Z [40m[37mdbug[39m[22m[49m: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[8]
2020-04-08T10:59:47.972269887Z       AuthenticationScheme: Bearer was successfully authenticated.
2020-04-08T10:59:47.972792490Z [40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
2020-04-08T10:59:47.972804590Z       Authorization was successful.
2020-04-08T10:59:47.972808890Z [40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
2020-04-08T10:59:47.972812791Z       Executing endpoint '/gamehub'
2020-04-08T10:59:47.978918726Z [40m[37mdbug[39m[22m[49m: Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher[5]
2020-04-08T10:59:47.978941526Z       Resuming existing connection.

**Comment by BrennanConroy** [comment]
If you aren't getting any logs when trying to connect with WebSockets, that likely means there is a proxy in the way preventing the WebSockets connection from getting to your app.

Are you on a corporate network?
How exactly are you hosting your app?
Can you go to https://breconwebsocket.azurewebsites.net/ and see if you connect with websockets there?

**Comment by BrennanConroy** [comment]
Do you happen to be hosting on a free plan?
Looks like WebSockets is not supported for free plans currently.
https://docs.microsoft.com/en-us/azure/app-service/containers/app-service-linux-faq#web-sockets

**Comment by AzizAK** [comment]
Yes im using free plan. i will try to switch to B1,

https://breconwebsocket.azurewebsites.net/ , is here a hub i can connect to?

**Comment by BrennanConroy** [comment]
The javascript will connect to the hub automatically when you go to the site.

**Comment by AzizAK** [comment]
Yes the site is working correctly (Signalr Connected). Also switch to B1 still same issue, maybe it take time to switch?

**Comment by AzizAK** [comment]
I tried to connect to Azure Signalr Service. still facing the same issue also.

**Comment by BrennanConroy** [comment]
What do the browser logs say? And what does the network tab show for the websocket request?

**Comment by AzizAK** [comment]
No the network tab does not show anything. only show on console error says (Error: Failed to start the connection: Error: There an error with the transport

**Comment by BrennanConroy** [comment]
There's not really much info here to go off of.

Can you collect a [network trace](https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-3.1#network-traces) and share it? If you don't want to share it publicly you can email me at 'brecon at microsoft.com'

**Comment by AzizAK** [comment]
When using Websockets i don't receive anything at fiddler :\, But this is the full error im getting

er:testingsignalr er$ node app.js
[2020-04-08T17:58:40.741Z] Debug: Starting HubConnection.
[2020-04-08T17:58:40.743Z] Debug: Starting connection with transfer format 'Text'.
Server running at http://127.0.0.1:3000/
[2020-04-08T17:58:41.877Z] Error: Failed to start the connection: Error: There was an error with the transport.
[2020-04-08T17:58:41.877Z] Debug: HubConnection failed to start successfully because of error 'Error: There was an error with the transport.'.
(node:28617) UnhandledPromiseRejectionWarning: Error: There was an error with the transport.
    at WebSocket.webSocket.onerror (/Users/rt/node_modules/@microsoft/signalr/dist/cjs/WebSocketTransport.js:107:45)
    at WebSocket.onError (/Users/er/node_modules/ws/lib/event-target.js:128:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at abortHandshake (/Users/er/node_modules/ws/lib/websocket.js:718:15)
    at ClientRequest.req.on (/Users/er/node_modules/ws/lib/websocket.js:595:7)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:552:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
(node:28617) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:28617) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by BrennanConroy** [comment]
Fiddler doesn't capture WebSockets traffic without you doing some work to enable it (I don't know how).

Wireshark should capture WebSockets though

**Comment by AzizAK** [comment]
Thank you Brennan for your time. I really appreciate it. 
i turned skip negotiation to false. then its working using azure signalr service I really don't know what is the issue. but now its fine by me. if you want to dig more see find the issue let me know.

**Comment by BrennanConroy** [comment]
> i turned skip negotiation to false. then its working using azure signalr service

That makes sense. I think it's in the Azure SignalR Service docs somewhere.

I'm still concerned about why your original scenario wasn't connecting with WebSockets. Since the request wasn't making it into the Apps logs, that means something before the App was stopping the WebSocket. Which usually means a proxy, either on your side or Azure's side.

**Comment by AzizAK** [comment]
Okay,
I will check if there is WebSockets traffic using Wireshark and get back with the details
