### ISSUE TITLE
OpenIdConnectHandler using unsecure cookies, and fix throws exception

### ISSUE THREAD

**Issue by dluc** [dotnet/aspnetcore#20670]
### Describe the bug

I'm running my service through a security review and I noticed that the cookies generated by ASP.NET are not safe, e.g. the `Secure` cookie flag is `false`.

I've been trying to force cookies to have the `Secure` flag turned on, but when I add the following code to the `Configure` method in Startup.cs, before `app.UseAuthentication()`:

```
app.UseCookiePolicy(new CookiePolicyOptions
            {
                Secure = CookieSecurePolicy.SameAsRequest
            });
```

my web application fails just after the AAD authentication process, with the following error:

```
Now listening on: https://localhost:5001
Application started. Press Ctrl+C to shut down.
warn: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[15]
      '.AspNetCore.Correlation.AzureADOpenID.4NRNDzirfnLbVZkQTaCQSV9WN0PLEiqzvemHD89THcE' cookie not found.
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.Exception: An error was encountered while handling the remote login. ---> System.Exception: Correlation failed.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### To Reproduce

My Startup.cs (.NET Core 2.2.8)

```
namespace WebApplication
{
    public class Startup
    {
        // [...]

        public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services
                .AddAuthentication(AzureADDefaults.AuthenticationScheme)
                .AddAzureAD(options =>
                {
                    this.Configuration.Bind("AzureAd", options);
                    options.ClientId = config.AADClientId;
                });
            services.AddHsts(options =>
            {
                options.IncludeSubDomains = true;
                options.MaxAge = TimeSpan.FromDays(180);
            });
            services.AddHttpsRedirection(options =>
            {
                options.RedirectStatusCode = StatusCodes.Status308PermanentRedirect;
                options.HttpsPort = 443;
            });
            services
                .AddMvc(
                    options =>
                    {
                        var policy = new AuthorizationPolicyBuilder()
                            .RequireAuthenticatedUser()
                            .Build();
                        options.Filters.Add(new AuthorizeFilter(policy));
                    })
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
            var serviceProvider = new AutofacServiceProvider(this.ApplicationContainer);
            return serviceProvider;
        }

        public void Configure(IApplicationBuilder app, IApplicationLifetime appLifetime)
        {
            app.UseDeveloperExceptionPage();
            app.UseStaticFiles();
            app.UseCookiePolicy(new CookiePolicyOptions
            {
                Secure = CookieSecurePolicy.SameAsRequest
                //MinimumSameSitePolicy = SameSiteMode.Strict,
                //HttpOnly = HttpOnlyPolicy.Always,
            });
            app.UseAuthentication();
            app.UseHttpsRedirection();
            app.UseHsts();
            app.UseMvc();
        }
    }
}
```

### Further technical details

Project
```
<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>netcoreapp2.2</TargetFramework>
        <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
    </PropertyGroup>
```

Dependencies
```
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.App" Version="2.2.8" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.AzureAD.UI" Version="2.2.0" />
        <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
        <PackageReference Include="Autofac" Version="5.1.2" />
        <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="6.0.0" />
        <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
    </ItemGroup>
```

dotnet info

```
# dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200
 Commit:    c5123d973b

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.200/

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  2.2.106 [/usr/local/share/dotnet/sdk]
  2.2.207 [/usr/local/share/dotnet/sdk]
  2.2.401 [/usr/local/share/dotnet/sdk]
  3.1.200 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by blowdart** [comment]
This is more than security, its also the same site cookie changes google made to the standard.

Please see https://aka.ms/samesitecore

**Comment by Tratcher** [comment]
Note: 2.2 is out of support, please update to 3.1.

The best tool to diagnose issues like this is Fiddler. Please capture and share a decrypted trace.

**Comment by Tratcher** [comment]
These should be placed before UseCookiePolicy.
```
            app.UseHttpsRedirection();
            app.UseHsts();
```
