### ISSUE TITLE
Blazor SignalR  issue

### ISSUE THREAD

**Issue by yongwangy91** [dotnet/aspnetcore#21053]
### Describe the bug
run the Blazor SignalR APP, I encounter the following problem. Obviously I follow all the steps listed in MS docs: 

dotnet run
crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
      Application startup exception
System.IO.FileNotFoundException: Could not find file 'C:\Users\Administrator\source\repos\BlazorSignalRApp\Server\bin\Debug\netcoreapp3.1\BlazorSignalRApp.Client.blazor.config'.
File name: 'C:\Users\Administrator\source\repos\BlazorSignalRApp\Server\bin\Debug\netcoreapp3.1\BlazorSignalRApp.Client.blazor.config'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.ReadLines(String path)
   at Microsoft.AspNetCore.Blazor.Server.BlazorConfig..ctor(String assemblyPath)
   at Microsoft.AspNetCore.Blazor.Server.BlazorConfig.Read(String assemblyPath)
   at Microsoft.AspNetCore.Builder.BlazorHostingEndpointRouteBuilderExtensions.MapFallbackToClientSideBlazor(IEndpointRouteBuilder endpoints, String clientAssemblyFilePath, String pattern, String filePath)
   at Microsoft.AspNetCore.Builder.BlazorHostingEndpointRouteBuilderExtensions.MapFallbackToClientSideBlazor[TClientApp](IEndpointRouteBuilder endpoints, String filePath)
   at BlazorSignalRApp.Server.Startup.<>c.<Configure>b__5_0(IEndpointRouteBuilder endpoints) in C:\Users\Administrator\source\repos\BlazorSignalRApp\Server\Startup.cs:line 56
   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
   at BlazorSignalRApp.Server.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in C:\Users\Administrator\source\repos\BlazorSignalRApp\Server\Startup.cs:line 52
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
Unhandled exception. System.IO.FileNotFoundException: Could not find file 'C:\Users\Administrator\source\repos\BlazorSignalRApp\Server\bin\Debug\netcoreapp3.1\BlazorSignalRApp.Client.blazor.config'.
File name: 'C:\Users\Administrator\source\repos\BlazorSignalRApp\Server\bin\Debug\netcoreapp3.1\BlazorSignalRApp.Client.blazor.config'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.ReadLines(String path)
   at Microsoft.AspNetCore.Blazor.Server.BlazorConfig..ctor(String assemblyPath)
   at Microsoft.AspNetCore.Blazor.Server.BlazorConfig.Read(String assemblyPath)
   at Microsoft.AspNetCore.Builder.BlazorHostingEndpointRouteBuilderExtensions.MapFallbackToClientSideBlazor(IEndpointRouteBuilder endpoints, String clientAssemblyFilePath, String pattern, String filePath)
   at Microsoft.AspNetCore.Builder.BlazorHostingEndpointRouteBuilderExtensions.MapFallbackToClientSideBlazor[TClientApp](IEndpointRouteBuilder endpoints, String filePath)
   at BlazorSignalRApp.Server.Startup.<>c.<Configure>b__5_0(IEndpointRouteBuilder endpoints) in C:\Users\Administrator\source\repos\BlazorSignalRApp\Server\Startup.cs:line 56
   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
   at BlazorSignalRApp.Server.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in C:\Users\Administrator\source\repos\BlazorSignalRApp\Server\Startup.cs:line 52
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at BlazorSignalRApp.Server.Program.Main(String[] args) in C:\Users\Administrator\source\repos\BlazorSignalRApp\Server\Program.cs:line 16

### To Reproduce

https://docs.microsoft.com/zh-cn/aspnet/core/tutorials/signalr-blazor-webassembly?view=aspnetcore-3.1&tabs=visual-studio

### Further technical details
- ASP.NET Core version : 
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
.NET Core SDK（反映任何 global.json）:
 Version:   3.1.201
 Commit:    b1768b4ae7

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by javiercn** [comment]
@yongwangy91 thanks for contacting us.

@guardrex is this some sort of sample that we have in the docs repo?

**Comment by guardrex** [comment]
It is ...

https://github.com/dotnet/AspNetCore.Docs/tree/master/aspnetcore/tutorials/signalr-blazor-webassembly/samples/3.x/BlazorSignalRApp

... and there was a report on it, but what that turned out to be is **_how the sample is run_**, not a problem with the sample itself. I only intend thus far to change the text to say that the sample can be run from VS/VSC with or without debugging now.

**Comment by javiercn** [comment]
@guardrex so not a product issue but a sample issue? Can we close this?

**Comment by guardrex** [comment]
Yes, as far as I know. The dev on the docs issue was able to get it running by following the guidance in the doc, so I think the framework aspects are good.

I'm already working on the PR now to upgrade it to Preview 4, and I'll take the updates live immediately after confirming that it runs ok.
