### ISSUE TITLE
Show "A path base can only be configured using IApplicationBuilder.UsePathBase()."

### ISSUE THREAD

**Issue by FalconWu2017** [dotnet/aspnetcore#21081]
An error occurred because of URL settings. If remove urls setting in appsettings.json the app will be OK. But how to set listening address?
This is my *.csproj:
~~~
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp3.1</TargetFrameworks>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Falcon.Extend" Version="1.2.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.Redis" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="3.1.3" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="3.1.3" />
    <PackageReference Include="NLog" Version="4.7.0" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="4.9.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.3.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.3" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FAuth.Database\FAuth.DataBase.csproj" />
  </ItemGroup>

</Project>
~~~      
appsettings.json   
~~~
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*",
  "ConnectionStrings": {
    "FAuthDb": "Server=.\\SQLSERVER2008R2;Database=FAuth;User ID=sa;Password=111"
  },
  "Redis": {
    "InstanceName": "",
    "Configuration": "127.0.0.1:7001,password=123654"
  },
  "UserTicketDecryptorOption": {
    "Key": "abcd"
  },
  "urls": "http://*:9000,https://*:9001"
}

~~~  
This is error log:
~~~
2020-04-22 09:55:13.2083||FATAL|Microsoft.AspNetCore.Server.Kestrel|Unable to start Kestrel. System.InvalidOperationException: A path base can only be configured using IApplicationBuilder.UsePathBase().
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.ParseAddress(String address, Boolean& https)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)   
~~~

**Comment by FalconWu2017** [comment]
Close because the address format is wrong.
