### ISSUE TITLE
Blazor: support linked `.razor` files from different path

### ISSUE THREAD

**Issue by chucker** [dotnet/aspnetcore#21090]
### Is your feature request related to a problem? Please describe.
I have a rather large Blazor solution. For performance and reliability reasons, I'm trying to create a smaller VS solution with its own Blazor project that only links _some_ of the `.razor` files.

I.e., the `.csproj` contains something like this:

```xml
  <ItemGroup>
    <None Include="..\MyLargerProject.Client\Pages\Sample.razor"
          Link="Pages\Sample.razor" />
  </ItemGroup>
```

From a general VS perspective, this is a supported scenario (in Solution Explorer, right-click on a folder, click **Add**, **Existing Item…**, pick a file, and then instead of Add, click **Add As Link** from the drop-down). But it seems unsupported in Razor.

When opening the file, Razor throws an exception, which can be seen in `ActivityLog.xml`, and looks something like:

```
System.InvalidOperationException: The file 'MyLargerProject.Client/Pages/Sample.razor' is not a descendent of the base path 'MySmallerProject.Client'.
at Microsoft.AspNetCore.Razor.Language.DefaultRazorProjectFileSystem.GetItem(String path, String fileKind)
at Microsoft.VisualStudio.Editor.Razor.DefaultImportDocumentManager.GetImportItems(VisualStudioDocumentTracker tracker)
at Microsoft.VisualStudio.Editor.Razor.DefaultImportDocumentManager.OnSubscribed(VisualStudioDocumentTracker tracker)
at Microsoft.VisualStudio.Editor.Razor.DefaultVisualStudioDocumentTracker.Subscribe()
at Microsoft.VisualStudio.Editor.Razor.DefaultRazorDocumentManager.OnTextViewOpened(ITextView textView, IEnumerable`1 subjectBuffers)
at Microsoft.VisualStudio.Editor.Razor.RazorTextViewConnectionListener.SubjectBuffersConnected(ITextView textView, ConnectionReason reason, IReadOnlyCollection`1 subjectBuffers)
at Microsoft.VisualStudio.Text.Editor.Implementation.ConnectionManager.NonWpfListener.SubjectBuffersConnected(IWpfTextView textView, ConnectionReason reason, Collection`1 subjectBuffers)
at Microsoft.VisualStudio.Text.Editor.Implementation.ConnectionManager.<>c__DisplayClass7_3.<.ctor>b__3()
at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

### Describe the solution you'd like
The exception is correct in that the `.razor` file is, indeed, not a descendant of my project. But it shouldn't have to be; `.cs` files don't need to be either.

(And if this isn't supposed to be a supported scenario at all, VS needs to prevent adding linked `.razor` files.)

### Additional context
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.6.0 Preview 3.0

dotnet --info:

<details>
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300-preview-015095
 Commit:    85c45057dc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300-preview-015095\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26
</details>

Blazor 3.2.0 Preview 4

**Comment by mkArtakMSFT** [comment]
We've moved this issue to the Backlog milestone. This means that it is not going to happen for the coming release. We will reassess the backlog following the current release and consider this item at that time. However, keep in mind that there are many other high priority features with which it will be competing for resources.

**Comment by allisonchou** [comment]
Tooling-side issue: https://github.com/dotnet/aspnetcore-tooling/issues/4653

**Comment by pranavkm** [comment]
@allisonchou feel free to reopen if there's specific work for us to do in the compiler to support this. Building an app with linked files works today so I imagine it's primarily an issue with the the way the project engine is configured in tooling.
