### ISSUE TITLE
SignInManager MissingMethodException 

### ISSUE THREAD

**Issue by devna13** [dotnet/aspnetcore#21164]
upgrading from asp net core 2.2 to 3.1; 
when web application lunches I'm getting this runtime error;

**System.MissingMethodException: Method not found: 'Void Microsoft.AspNetCore.Identity.SignInManager`1..ctor(Microsoft.AspNetCore.Identity.UserManager`1<!0>, Microsoft.AspNetCore.Http.IHttpContextAccessor, Microsoft.AspNetCore.Identity.IUserClaimsPrincipalFactory`1<!0>, Microsoft.Extensions.Options.IOptions`1<Microsoft.AspNetCore.Identity.IdentityOptions>, Microsoft.Extensions.Logging.ILogger`1<Microsoft.AspNetCore.Identity.SignInManager`1<!0>>, Microsoft.AspNetCore.Authentication.IAuthenticationSchemeProvider)'.**

I've tried few suggestions from [https://github.com/dotnet/aspnetcore/issues/12536](https://github.com/dotnet/aspnetcore/issues/12536) but no luck so far.

Full log: 

```
Executed action "XYZ.IdentityServer.Controllers.Api.AccountController.Authenticate (XYZ.IdentityServer)" in 48.9886ms
===> [2020-04-23 16:25:40.674] [Information] Executed endpoint '"XYZ.IdentityServer.Controllers.Api.AccountController.Authenticate (XYZ.IdentityServer)"'
===> [2020-04-23 16:25:40.826] [Error] An unhandled exception has occurred while executing the request.
System.MissingMethodException: Method not found: 'Void Microsoft.AspNetCore.Identity.SignInManager`1..ctor(Microsoft.AspNetCore.Identity.UserManager`1<!0>, Microsoft.AspNetCore.Http.IHttpContextAccessor, Microsoft.AspNetCore.Identity.IUserClaimsPrincipalFactory`1<!0>, Microsoft.Extensions.Options.IOptions`1<Microsoft.AspNetCore.Identity.IdentityOptions>, Microsoft.Extensions.Logging.ILogger`1<Microsoft.AspNetCore.Identity.SignInManager`1<!0>>, Microsoft.AspNetCore.Authentication.IAuthenticationSchemeProvider)'.
   at XYZ.Identity.Data.Services.XYZSignInManager..ctor(UserManager`1 userManager, IHttpContextAccessor contextAccessor, IUserClaimsPrincipalFactory`1 claimsFactory, IOptions`1 optionsAccessor, ILogger`1 logger, IAuthenticationSchemeProvider schemes, IUserConfirmation`1 confirmation)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at XYZ.IdentityServer.Middleware.ContentSecurityPolicyMiddleware.Invoke(HttpContext context) in C:\Workspaces\Git\identity-server\Src\XYZ.IdentityServer\Middleware\ContentSecurityPolicyMiddleware.cs:line 33
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
   at IdentityServer4.Hosting.MutualTlsTokenEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
 

```

The web app is referencing this class lib;
```

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>  
  ....
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.1.3" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="3.1.3" />	
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="3.1.3" />
	....
  </ItemGroup> 
...
</Project>

```

```

public class XYZSignInManager : SignInManager<ApplicationUser>
{
	public XYZSignInManager(
            UserManager<ApplicationUser> userManager, 
            IHttpContextAccessor contextAccessor, 
            IUserClaimsPrincipalFactory<ApplicationUser> claimsFactory, 
            IOptions<IdentityOptions> optionsAccessor, 
            ILogger<SignInManager<ApplicationUser>> logger, 
            IAuthenticationSchemeProvider schemes) 
            : base(userManager, contextAccessor, claimsFactory, optionsAccessor, logger, schemes)
        { }

```

Thanks

**Comment by blowdart** [comment]
This generally happens when you mix 3.x and 2.x packages and dependencies.

Can you share your csproj file?

**Comment by mkArtakMSFT** [comment]
The classlib your web app is referencing uses Microsoft.AspNetCore.Identity v2.2.0 package. Based on the following announcement there was a [breaking change](https://github.com/dotnet/docs/issues/14828) in SignInManager type in 3.0, which seems to impact you here.

**Comment by devna13** [comment]
@mkArtakMSFT thanks for the link, I'm using latest package and solution builds successfully 
<PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />

plus ctor doesn't take any other parameter !? what I'm missing here?

![image](https://user-images.githubusercontent.com/4080343/80221730-8d782180-85fa-11ea-88fc-d63e42689bda.png)

![image](https://user-images.githubusercontent.com/4080343/80222059-1a22df80-85fb-11ea-9e54-e45557856287.png)


If it's breaking change, shouldn't be in the migration docs from[ 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio) or 3.0 to 3.1 ?


---------------------------------------------------------------------------------------------------

@blowdart  
I've updated all the projects to latest (stable) packages. Web project is core 3.1 and is referencing standard 2.1 projects. XYZ.Identity.Data.csproj is using SignInManager:

Web project csproj file:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
    <IsPackable>false</IsPackable>
    <SpaRoot>ClientApp\</SpaRoot>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(SpaRoot)node_modules\**</DefaultItemExcludes>
    <!-- Set this to true if you enable server-side prerendering -->
    <BuildServerSideRenderer>false</BuildServerSideRenderer>
    <Configurations>Debug;Release;Staging</Configurations>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <GenerateSerializationAssemblies>Auto</GenerateSerializationAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <!-- Don't publish tXYZ SPA source files, but do show tXYZm in tXYZ project files list. -->
    <Compile Remove="publish\**" />
    <Content Remove="$(SpaRoot)**" />
    <Content Remove="publish\**" />
    <EmbeddedResource Remove="publish\**" />
    <None Remove="$(SpaRoot)**" />
    <None Remove="publish\**" />
    <None Include="$(SpaRoot)**" Exclude="$(SpaRoot)node_modules\**" />
  </ItemGroup>

  <ItemGroup>          
    <PackageReference Include="IdentityServer4" Version="3.1.2" />
    <PackageReference Include="IdentityServer4.AccessTokenValidation" Version="3.0.1" />
    <PackageReference Include="IdentityServer4.AspNetIdentity" Version="3.1.2" />
    <PackageReference Include="IdentityServer4.EntityFramework" Version="3.1.2" />

    <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.2.0" />
    
    <PackageReference Include="Microsoft.AspNetCore.SpaServices" Version="3.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="3.1.3" />
    
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.2.0" />
    
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="3.1.3" />
    
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="3.1.3" />
    <PackageReference Include="Microsoft.jQuery.Unobtrusive.Ajax" Version="3.2.6" />
    <PackageReference Include="Microsoft.jQuery.Unobtrusive.Validation" Version="3.2.11" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.2" />
    <PackageReference Include="Serilog.AspNetCore" Version="3.2.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="3.1.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="4.1.0" />
	
	<PackageReference Include="XYZ.Framework.Standard.Common" Version="2.0.0" />
    <PackageReference Include="XYZ.Framework.Standard.Data.Sql" Version="2.0.0" />
    <PackageReference Include="XYZ.Framework.Standard.Formatters" Version="2.0.0" />
    <PackageReference Include="XYZ.Framework.Standard.IO" Version="2.0.0" />
    <PackageReference Include="XYZ.Framework.Standard.PhoneNumbers" Version="2.0.0" />
    <PackageReference Include="XYZ.Framework.Standard.Security.Claims" Version="2.1.0" />
    <PackageReference Include="XYZ.Framework.Standard.UnitOfWork.EntityFramework" Version="2.0.0" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\XYZ.Identity.Data\XYZ.Identity.Data.csproj" />
    <ProjectReference Include="..\XYZ.Identity.Ip.AdminV3\XYZ.Identity.Ip.AdminV3.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="Views\Email\ResetPasswordEmailTemplate.cshtml">
      <Pack>$(IncludeRazorContentInPack)</Pack>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <!-- Runs 'npm install' if building in debug mode AND if tXYZre is no node_modules directory. -->
  <Target Name="DebugEnsureNodeEnv" BeforeTargets="Build" Condition=" '$(Configuration)' == 'Debug' And !Exists('$(SpaRoot)node_modules') ">
    <!-- Ensure Node.js is installed -->
    <Exec Command="node --version" ContinueOnError="true">
      <Output TaskParameter="ExitCode" PropertyName="ErrorCode" />
    </Exec>
    <Error Condition="'$(ErrorCode)' != '0'" Text="Node.js is required to build and run this project. To continue, please install Node.js from https://nodejs.org/, and tXYZn restart your command prompt or IDE." />
    <Message Importance="high" Text="Restoring dependencies using 'npm'. This may take several minutes..." />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
  </Target>

  <!-- PublisXYZs tXYZ angular client app after tXYZ asp.net app is publisXYZd.  -->
  <Target Name="PublishRunWebpack" AfterTargets="ComputeFilesToPublish">
    <!-- As part of publishing, ensure tXYZ JS resources are freshly built in production mode -->
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm install" />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build -- --configuration=staging" Condition=" '$(Configuration)' == 'Staging' " />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build:ssr -- --configuration=staging" Condition=" '$(Configuration)' == 'Staging' AND '$(BuildServerSideRenderer)' == 'true' " />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build -- --prod" Condition=" '$(Configuration)' == 'Release' " />
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm run build:ssr -- --prod" Condition=" '$(Configuration)' == 'Release' AND '$(BuildServerSideRenderer)' == 'true' " />

    <!-- Include tXYZ newly-built files in tXYZ publish output -->
    <ItemGroup>
      <DistFiles Include="$(SpaRoot)dist\**; $(SpaRoot)dist-server\**" />
      <DistFiles Include="$(SpaRoot)node_modules\**" Condition="'$(BuildServerSideRenderer)' == 'true'" />
      <ResolvedFileToPublish Include="@(DistFiles->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
        <RelativePath>%(DistFiles.Identity)</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </ResolvedFileToPublish>
    </ItemGroup>
  </Target>
</Project>


```

  
XYZ.Identity.Data.csproj: 
  
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>   
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />    
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.1.3" />
    
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="3.1.3" />
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="3.1.3" />
    
    <PackageReference Include="System.Drawing.Common" Version="4.7.0" />
	
	<PackageReference Include="Dapper" Version="2.0.35" />
    <PackageReference Include="XYZi.Framework.Standard.Common" Version="2.0.0" />
    <PackageReference Include="XYZi.Framework.Standard.Data.Common" Version="2.0.0" />
    <PackageReference Include="XYZi.Framework.Standard.Formatters" Version="2.0.0" />
    <PackageReference Include="XYZi.Framework.Standard.IO" Version="2.0.0" />
    <PackageReference Include="XYZi.Framework.Standard.PhoneNumbers" Version="2.0.0" />
    <PackageReference Include="XYZi.Framework.Standard.Security.Claims" Version="2.1.0" />
    <PackageReference Include="XYZi.Framework.Standard.UnitOfWork.EntityFramework" Version="2.0.0" />
  </ItemGroup>
 
  <ItemGroup>
    <ProjectReference Include="..\XYZi.Identity.Core\XYZi.Identity.Core.csproj" />
  </ItemGroup>

</Project>

```

**Comment by blowdart** [comment]
You're definitely mixing things; 

For example in your web project

```
    <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.2.0" />
    
    <PackageReference Include="Microsoft.AspNetCore.SpaServices" Version="3.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="3.1.3" />
    
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.2.0" />
```

There's 2.x packages and 3.x packages

And your Identity.Data package is mixing 

```
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />    
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.1.3" />
```

**Comment by mkArtakMSFT** [comment]
@devna13 the breaking-change I referred to was about the `SignInManager<T>` type constructor, rather than the `UserManager<T>` which you're looking at. Anyway, look above at what @blowdart points too, what you have there is the most probably cause.

**Comment by devna13** [comment]
Sorry I took a wrong screenshot from UserManager de-compile.
You can see this is the latest package from nuget and it doesn't take any other param
![image](https://user-images.githubusercontent.com/4080343/80232481-d71c3880-8609-11ea-82ff-a0d20e5909d9.png)

![image](https://user-images.githubusercontent.com/4080343/80232325-92909d00-8609-11ea-9dd9-11b1eb81922d.png)


these are the latest versions of the packages and they are not compatible !?

```
<PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />    
<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.1.3" />

```

**Comment by devna13** [comment]
it turned out this [https://github.com/dotnet/aspnetcore/issues/14388](https://github.com/dotnet/aspnetcore/issues/14388) is the main issue and not the package mix cause there is NO "Microsoft.AspNetCore.Identity"  PACKAGE ANYMORE !!!

**Comment by Alimardan** [comment]
I had same problem afater update from 2.2 to 3.1
this is useful [https://developercommunity.visualstudio.com/content/problem/959669/dot-net-core-upgrade-v22-to-v31-issue-with-sign-in.html](url)
