### ISSUE TITLE
XmlSerializerOutputFormatterDoesntFlushOutputStream Flaky

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#21259]
https://helix.dot.net/api/2019-06-17/jobs/738a4beb-b7cc-4cb4-9f9a-2ddf8f336f53/workitems/Microsoft.AspNetCore.Mvc.Formatters.Xml.Test--netcoreapp5.0/console
```
[xUnit.net 00:00:01.97]       System.InvalidOperationException : FlushAsync should not have been called.
[xUnit.net 00:00:01.97]       Stack Trace:
[xUnit.net 00:00:01.97]         /_/src/Mvc/Mvc.Formatters.Xml/test/FlushReportingStream.cs(28,0): at Microsoft.AspNetCore.Mvc.FlushReportingStream.NonFlushingStream.FlushAsync(CancellationToken cancellationToken)
[xUnit.net 00:00:01.97]            at System.IO.Pipelines.StreamPipeWriter.FlushAsyncInternal(Boolean writeToStream, CancellationToken cancellationToken)
[xUnit.net 00:00:01.97]         /_/src/Http/WebUtilities/src/PagedByteBuffer.cs(99,0): at Microsoft.AspNetCore.WebUtilities.PagedByteBuffer.MoveToAsync(PipeWriter writer, CancellationToken cancellationToken)
[xUnit.net 00:00:01.97]         /_/src/Http/WebUtilities/src/FileBufferingWriteStream.cs(218,0): at Microsoft.AspNetCore.WebUtilities.FileBufferingWriteStream.DrainBufferAsync(PipeWriter destination, CancellationToken cancellationToken)
[xUnit.net 00:00:01.98]         /_/src/Mvc/Mvc.Formatters.Xml/src/XmlSerializerOutputFormatter.cs(264,0): at Microsoft.AspNetCore.Mvc.Formatters.XmlSerializerOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
[xUnit.net 00:00:01.98]         /_/src/Mvc/Mvc.Formatters.Xml/src/XmlSerializerOutputFormatter.cs(271,0): at Microsoft.AspNetCore.Mvc.Formatters.XmlSerializerOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
[xUnit.net 00:00:01.98]         /_/src/Mvc/Mvc.Formatters.Xml/test/XmlSerializerOutputFormatterTest.cs(417,0): at Microsoft.AspNetCore.Mvc.Formatters.Xml.XmlSerializerOutputFormatterTest.XmlSerializerOutputFormatterDoesntFlushOutputStream()
```

https://dev.azure.com/dnceng/public/_build/results?buildId=618468&view=logs&j=3f6d4e0f-1b71-56b5-361e-d95b6e6da15a&t=d5bf30bc-9e5a-596c-d1c8-39e2dfa42d49&l=799

**Comment by pranavkm** [comment]
This appears to be the result of @davidfowl trying to change the implementation of the buffering. The test failure is in the PR build so the error is expected. Please don't quarantine this.

**Comment by ryanbrandenburg** [comment]
You are correct @pranavkm. I apparently missed checked PR builds as well, which I should not have. Closing.
