### ISSUE TITLE
Could not load settings from '_configuration/BlazorApp1.Client'

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#21327]
Repro steps:

- Create a Blazor WebAssembly app that is ASP.NET Core hosted and with auth
- Set the *Client* project as the startup project (yes, I know this isn't the normal thing to do, but the failure case looks weird)
- Run the app

Actual result:

```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not load settings from '_configuration/BlazorApp7.Client'
      Error: Could not load settings from '_configuration/BlazorApp7.Client'
          at Function.createUserManager (https://localhost:44337/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js:1:5893)
          at async Function.initializeCore (https://localhost:44337/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js:1:5027)
Microsoft.JSInterop.JSException: Could not load settings from '_configuration/BlazorApp7.Client'
Error: Could not load settings from '_configuration/BlazorApp7.Client'
    at Function.createUserManager (https://localhost:44337/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js:1:5893)
    at async Function.initializeCore (https://localhost:44337/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js:1:5027)
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () <0x2ea2640 + 0x00034> in <filename unknown>:0 
  at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync (Microsoft.JSInterop.IJSRuntime jsRuntime, System.String identifier, System.Object[] args) <0x2c93998 + 0x000e4> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`3[TRemoteAuthenticationState,TAccount,TProviderOptions].EnsureAuthService () <0x2c92f90 + 0x000fc> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`3[TRemoteAuthenticationState,TAccount,TProviderOptions].GetAuthenticatedUser () <0x2c926d8 + 0x000d2> in <filename unknown>:0 
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () <0x2ea6660 + 0x00034> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`3[TRemoteAuthenticationState,TAccount,TProviderOptions].GetUser (System.Boolean useCache) <0x2c482e0 + 0x00138> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`3[TRemoteAuthenticationState,TAccount,TProviderOptions].GetAuthenticationStateAsync () <0x2c471a0 + 0x000b6> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.OnParametersSetAsync () <0x2df1450 + 0x00126> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion (System.Threading.Tasks.Task task) <0x2df2038 + 0x000da> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync () <0x2bd8fb0 + 0x001d8> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask (System.Threading.Tasks.Task taskToHandle) <0x2df4bb0 + 0x000b6> in <filename unknown>:0 
```

**Comment by javiercn** [comment]
@danroth27 ¯\_(ツ)_/¯

**Comment by abbatepabloo** [comment]
In my case the error showed up even when I started the server project. My Identity Server is not installed on the same server where my app is located.

So, I made some changes in Program.cs (client):
```
public static async Task Main(string[] args)
{
    var builder = WebAssemblyHostBuilder.CreateDefault(args);
    builder.RootComponents.Add<App>("app");

    builder.Services.AddHttpClient("BlazorApp1.ServerAPI", client => client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress))
        .AddHttpMessageHandler<BaseAddressAuthorizationMessageHandler>();
    builder.Services.AddTransient(sp => sp.GetRequiredService<IHttpClientFactory>().CreateClient("BlazorApp1.ServerAPI"));

    // The following line has been disabled
    //builder.Services.AddApiAuthorization();

    //In order to authenticate to IS4:
    builder.Services.AddOidcAuthentication(options =>
    {
        builder.Configuration.Bind("Local", options.ProviderOptions);
    });

    await builder.Build().RunAsync();
}
```
Also I configure the OpenId settings in appsettings.json with Authority and ClientId.
After this changes, the error disappeared. 

Not sure if it's the solution to this error.

**Comment by javiercn** [comment]
API authorization is only for when Identity Server and the app reside on the same origin/host. Otherwise you are expected to use `AddOidc` and so on.

**Comment by abbatepabloo** [comment]
In the scenario @danroth27  commented, the proposed changes seem to make the error goes away.
When **AddApiAuthorization** is used, the function **createUserManager** (AuthenticationService.js) is receiving a configurationEndpoint and trying to fecht it. This endpoint is pointing to a server's url wich is not available (server is not running). And that produces the error.
Thanks @javiercn for the clarification!!

**Comment by javiercn** [comment]
@abbatepabloo that is expected. The server is not available, so an error is produced, the error is legitimate and can't go away.
