### ISSUE TITLE
[Helix] Unable to find Node.js in PATH (OSX.1014.Amd64.Open)

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#21350]
```
System.InvalidOperationException : Failed to start Node process. To resolve this:.

[1] Ensure that Node.js is installed and can be found in one of the PATH directories.

Current PATH enviroment variable is: /private/tmp/helix/working/A9F708E3/w/BE6B0A36/e/.dotnet26281:/usr/bin:/bin:/usr/sbin:/sbin:/private/tmp/helix/working/A9F708E3/w/BE6B0A36/e/node/bin

Make sure the Node executable is in one of those directories, or update your PATH.

[2] See the InnerException for further details of the cause.

---- System.ComponentModel.Win32Exception : No such file or directory
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.LaunchNodeProcess(ProcessStartInfo startInfo) in /_/src/Middleware/NodeServices/src/HostingModels/OutOfProcessNodeInstance.cs:line 347
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance..ctor(String entryPointScript, String projectPath, String[] watchFileExtensions, String commandLineArguments, CancellationToken applicationStoppingToken, ILogger nodeOutputLogger, IDictionary`2 environmentVars, Int32 invocationTimeoutMilliseconds, Boolean launchWithDebugging, Int32 debuggingPort) in /_/src/Middleware/NodeServices/src/HostingModels/OutOfProcessNodeInstance.cs:line 82
   at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance..ctor(NodeServicesOptions options, Int32 port) in /_/src/Middleware/NodeServices/src/HostingModels/HttpNodeInstance.cs:line 42
   at Microsoft.AspNetCore.NodeServices.HostingModels.NodeServicesOptionsExtensions.<>c__DisplayClass0_0.<UseHttpHosting>b__0() in /_/src/Middleware/NodeServices/src/HostingModels/NodeServicesOptionsExtensions.cs:line 21
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.CreateNewNodeInstance() in /_/src/Middleware/NodeServices/src/NodeServicesImpl.cs:line 166
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.GetOrCreateCurrentNodeInstance() in /_/src/Middleware/NodeServices/src/NodeServicesImpl.cs:line 156
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.InvokeExportWithPossibleRetryAsync[T](String moduleName, String exportedFunctionName, Object[] args, Boolean allowRetry, CancellationToken cancellationToken) in /_/src/Middleware/NodeServices/src/NodeServicesImpl.cs:line 60
   at Microsoft.AspNetCore.NodeServices.NodeServicesTest.CanPassParameters() in /_/src/Middleware/NodeServices/test/NodeServicesTest.cs:line 70
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
```

https://dev.azure.com/dnceng/public/_build/results?buildId=623874&view=ms.vss-test-web.build-test-results-tab&runId=19502522&paneView=debug&resultId=107607

**Comment by Tratcher** [comment]
Note the root error is a download issue:
```
Executed on dci-mac-build-105.local
+ ./installnode.sh 10.15.3 x64
PlatformArch: darwin-x64
Downloading from: http://nodejs.org/dist/v10.15.3/node-v10.15.3-darwin-x64.tar.gz
Failed to install node with exit code: 22
```

**Comment by Tratcher** [comment]
We had a bunch of these a week or two ago. Some were caused by the node CDN (though I can access that URL), and some were caused by the mac agents having poor connectivity.

**Comment by dougbu** [comment]
Resolved a while back
