### ISSUE TITLE
An error occurred while writing to logger(s). (Could not find 'dotNetCriticalError' in 'window.Blazor._internal'.

### ISSUE THREAD

**Issue by jasjae** [dotnet/aspnetcore#21388]
**Version:**
Blazor WebAssembly 3.2.0 Release Candidate

**Notes:**
Unsure what is causing this exception, debugger does not step into exception.

**Stack trace:**
Uncaught (in promise) Error: Microsoft.AspNetCore.Components.LocationChangeException: An exception occurred while dispatching a location changed event. ---> System.AggregateException: An error occurred while writing to logger(s). (Could not find 'dotNetCriticalError' in 'window.Blazor._internal'.
Error: Could not find 'dotNetCriticalError' in 'window.Blazor._internal'.
    at http://localhost:50985/nmp2b/_framework/blazor.webassembly.js:1:9135
    at Array.forEach (<anonymous>)
    at Object.p [as findJSFunction] (http://localhost:50985/nmp2b/_framework/blazor.webassembly.js:1:9096)
    at _mono_wasm_invoke_js_unmarshalled (http://localhost:50985/nmp2b/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js:1:172098)
    at do_icall (wasm-function[6049]:0x1119e9)
    at do_icall_wrapper (wasm-function[1896]:0x52c3e)
    at interp_exec_method (wasm-function[1120]:0x25a03)
    at interp_runtime_invoke (wasm-function[5654]:0xf944e)
    at mono_jit_runtime_invoke (wasm-function[5108]:0xdfbfa)
    at do_runtime_invoke (wasm-function[1410]:0x3db59)) ---> Microsoft.JSInterop.JSException: Could not find 'dotNetCriticalError' in 'window.Blazor._internal'.
Error: Could not find 'dotNetCriticalError' in 'window.Blazor._internal'.
    at http://localhost:50985/nmp2b/_framework/blazor.webassembly.js:1:9135
    at Array.forEach (<anonymous>)
    at Object.p [as findJSFunction] (http://localhost:50985/nmp2b/_framework/blazor.webassembly.js:1:9096)
    at _mono_wasm_invoke_js_unmarshalled (http://localhost:50985/nmp2b/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js:1:172098)
    at do_icall (wasm-function[6049]:0x1119e9)
    at do_icall_wrapper (wasm-function[1896]:0x52c3e)
    at interp_exec_method (wasm-function[1120]:0x25a03)
    at interp_runtime_invoke (wasm-function[5654]:0xf944e)
    at mono_jit_runtime_invoke (wasm-function[5108]:0xdfbfa)
    at do_runtime_invoke (wasm-function[1410]:0x3db59)
  at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[T0,T1,T2,TResult] (System.String identifier, T0 arg0, T1 arg1, T2 arg2) <0x9170fe0 + 0x0003a> in <filename unknown>:0 
  at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[T0,TResult] (System.String identifier, T0 arg0) <0x9170f10 + 0x0000e> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.WebAssembly.Services.WebAssemblyConsoleLogger`1[T].WriteMessage (Microsoft.Extensions.Logging.LogLevel logLevel, System.String logName, System.Int32 eventId, System.String message, System.Exception exception) <0x9169488 + 0x00126> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.WebAssembly.Services.WebAssemblyConsoleLogger`1[T].Log[TState] (Microsoft.Extensions.Logging.LogLevel logLevel, Microsoft.Extensions.Logging.EventId eventId, TState state, System.Exception exception, System.Func`3[T1,T2,TResult] formatter) <0x9168ab8 + 0x00082> in <filename unknown>:0 
  at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|12_0[TState] (Microsoft.Extensions.Logging.LogLevel logLevel, Microsoft.Extensions.Logging.EventId eventId, Microsoft.Extensions.Logging.ILogger logger, System.Exception exception, System.Func`3[T1,T2,TResult] formatter, System.Collections.Generic.List`1[System.Exception]& exceptions, TState& state) <0x9168828 + 0x00026> in <filename unknown>:0 
   --- End of inner exception stack trace ---
  at Microsoft.Extensions.Logging.Logger.ThrowLoggingError (System.Collections.Generic.List`1[T] exceptions) <0x9171480 + 0x00010> in <filename unknown>:0 
  at Microsoft.Extensions.Logging.Logger.Log[TState] (Microsoft.Extensions.Logging.LogLevel logLevel, Microsoft.Extensions.Logging.EventId eventId, TState state, System.Exception exception, System.Func`3[T1,T2,TResult] formatter) <0x9168728 + 0x000ba> in <filename unknown>:0 
  at Microsoft.Extensions.Logging.Logger`1[T].Microsoft.Extensions.Logging.ILogger.Log[TState] (Microsoft.Extensions.Logging.LogLevel logLevel, Microsoft.Extensions.Logging.EventId eventId, TState state, System.Exception exception, System.Func`3[T1,T2,TResult] formatter) <0x9168590 + 0x00026> in <filename unknown>:0 
  at Microsoft.Extensions.Logging.LoggerMessage+<>c__DisplayClass5_0`1[T1].<Define>g__Log|0 (Microsoft.Extensions.Logging.ILogger logger, T1 arg1, System.Exception exception) <0x9167c48 + 0x0003c> in <filename unknown>:0 
  at Microsoft.Extensions.Logging.LoggerMessage+<>c__DisplayClass5_0`1[T1].<Define>b__1 (Microsoft.Extensions.Logging.ILogger logger, T1 arg1, System.Exception exception) <0x7cc2fc8 + 0x00026> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer+Log.UnhandledExceptionRenderingComponent (Microsoft.Extensions.Logging.ILogger logger, System.Exception exception) <0x915f5a8 + 0x00020> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer.HandleException (System.Exception exception) <0x915ef50 + 0x0005c> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue () <0x7a68e98 + 0x00136> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessPendingRender () <0x7a68868 + 0x0001e> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue (System.Int32 componentId, Microsoft.AspNetCore.Components.RenderFragment renderFragment) <0x7a67c50 + 0x0007c> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.RenderHandle.Render (Microsoft.AspNetCore.Components.RenderFragment renderFragment) <0x7a67918 + 0x00024> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.Routing.Router.Refresh (System.Boolean isNavigationIntercepted) <0x7b9c548 + 0x0016e> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.Routing.Router.OnLocationChanged (System.Object sender, Microsoft.AspNetCore.Components.Routing.LocationChangedEventArgs args) <0x931b068 + 0x00040> in <filename unknown>:0 
  at (wrapper delegate-invoke) System.EventHandler`1[Microsoft.AspNetCore.Components.Routing.LocationChangedEventArgs].invoke_void_object_TEventArgs(object,Microsoft.AspNetCore.Components.Routing.LocationChangedEventArgs)
  at Microsoft.AspNetCore.Components.NavigationManager.NotifyLocationChanged (System.Boolean isInterceptedLink) <0x931abe0 + 0x0002c> in <filename unknown>:0 
   --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x2c0c870 + 0x000ce> in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---

  at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously (Microsoft.JSInterop.JSRuntime jsRuntime, Microsoft.JSInterop.Infrastructure.DotNetInvocationInfo& callInfo, Microsoft.JSInterop.Infrastructure.IDotNetObjectReference objectReference, System.String argsJson) <0x90309d8 + 0x0017a> in <filename unknown>:0 
  at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet (Microsoft.JSInterop.JSRuntime jsRuntime, Microsoft.JSInterop.Infrastructure.DotNetInvocationInfo invocationInfo, System.String argsJson) <0x9030380 + 0x0009e> in <filename unknown>:0 
    at Object.endInvokeDotNetFromJS (http://localhost:50985/nmp2b/_framework/blazor.webassembly.js:1:10047)
    at Object.invokeJSFromDotNet (http://localhost:50985/nmp2b/_framework/blazor.webassembly.js:1:9673)
    at _mono_wasm_invoke_js_marshalled (http://localhost:50985/nmp2b/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js:1:171485)
    at do_icall (wasm-function[6049]:0x111976)
    at do_icall_wrapper (wasm-function[1896]:0x52c3e)
    at interp_exec_method (wasm-function[1120]:0x25a03)
    at interp_runtime_invoke (wasm-function[5654]:0xf944e)
    at mono_jit_runtime_invoke (wasm-function[5108]:0xdfbfa)
    at do_runtime_invoke (wasm-function[1410]:0x3db59)
    at mono_runtime_try_invoke (wasm-function[418]:0xcfd4)

**Comment by pranavkm** [comment]
FYI @SteveSandersonMS

**Comment by SteveSandersonMS** [comment]
@jasjae My best guess is that you're running mismatched versions of the library. Is it possible that you have got the RC version of the .NET libraries, but are still serving an older version of `blazor.webassembly.js`? Perhaps it's cached in your browser.

Could you please try:

 * Clearing your browser storage for the site concerned
 * Making sure you're not doing anything that loads an older version of `blazor.webassembly.js`

If neither of these helps, could you please provide repro steps for us? Thanks!

**Comment by jasjae** [comment]
Works, followed steps above. Thanks. Closing ticket.
