### ISSUE TITLE
Kestrel ListenAnyIP error

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#21423]
Potentially a bug introduced by https://github.com/dotnet/aspnetcore/pull/21072

https://dev.azure.com/dnceng/internal/_build/results?buildId=626982&view=logs&j=ab336984-fd17-5476-0984-4a0b5ed8658e&t=89066a81-cbc6-5313-1cbd-e2259a0b7533

Error:
```
[STDERR] Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
[STDERR]    at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.ApplyConfigurationDefaults(ListenOptions listenOptions)
[STDERR]    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.ApplyEndpointDefaults(ListenOptions listenOptions)
[STDERR]    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.ListenAnyIP(Int32 port, Action`1 configure)
[STDERR]    at GrpcAspNetCoreServer.Program.<>c__DisplayClass1_0.<CreateHostBuilder>b__3(WebHostBuilderContext context, KestrelServerOptions options) in C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-5140\etf3ezdi.lfc\grpc-dotnet\perf\benchmarkapps\GrpcAspNetCoreServer\Program.cs:line 68
[STDERR]    at Microsoft.AspNetCore.Hosting.WebHostBuilderKestrelExtensions.<>c__DisplayClass4_1.<ConfigureKestrel>b__1(KestrelServerOptions options)
[STDERR]    at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
[STDERR]    at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
[STDERR]    at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
[STDERR]    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
[STDERR]    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
[STDERR]    at System.Lazy`1.CreateValue()
[STDERR]    at System.Lazy`1.get_Value()
[STDERR]    at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
[STDERR]    at Microsoft.Extensions.Options.OptionsManager`1.Get(String name)
[STDERR]    at Microsoft.Extensions.Options.OptionsManager`1.get_Value()
[STDERR]    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.CreateServiceContext(IOptions`1 options, ILoggerFactory loggerFactory)
[STDERR]    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer..ctor(IOptions`1 options, IEnumerable`1 transportFactories, IEnumerable`1 multiplexedFactories, ILoggerFactory loggerFactory)
```

Usage:
https://github.com/grpc/grpc-dotnet/blob/54add4f70f9154024573c1bb99c8450f5ee2a132/perf/benchmarkapps/GrpcAspNetCoreServer/Program.cs#L68

@halter73 @sebastienros

**Comment by halter73** [comment]
Yikes. Definitely a regression caused by #21072.

Looking at the usage, I'm wondering how KestrelServerOptions.ConfigurationLoader is getting set. I think there needs to be a call to [KSO.Configure](https://github.com/dotnet/aspnetcore/blob/36fb1134f5c9c6f53e9ef5b7db2ab0efda2f4592/src/Servers/Kestrel/Core/src/KestrelServerOptions.cs#L230) somewhere, but I don't see it.

Regardless, this NullReferenceException could happen if KSO.Configure() is called and then KSO.Listen\*() without a call to KestrelConfigurationLoader.Load() in between. This, of course, shouldn't happen.
