### ISSUE TITLE
Microsoft.AspNetCore.Http.HeaderSegmentCollection.Enumerator.get_Current throws exception

### ISSUE THREAD

**Issue by pedramrezaei** [dotnet/aspnetcore#21556]
Create an intance of HeaderSegmentCollection with a header value that has a trailing space throws an exception:

``` C#
var headers = new HeaderDictionary
{
    { HeaderNames.Via, "value " },
};

headers.GetCommaSeparatedValues(HeaderNames.Via);
```
### Exception
System.ArgumentOutOfRangeException: 'Specified argument was out of the range of valid values. (Parameter 'offset')'

### Stack Trace: 
   at Microsoft.Extensions.Primitives.StringSegment.ThrowInvalidArguments(String buffer, Int32 offset, Int32 length)
   at Microsoft.Extensions.Primitives.StringSegment..ctor(String buffer, Int32 offset, Int32 length)
   at Microsoft.AspNetCore.Http.HeaderSegmentCollection.Enumerator.get_Current()
   at Microsoft.AspNetCore.Http.ParsingHelpers.GetHeaderSplit(IHeaderDictionary headers, String key)
   at Microsoft.AspNetCore.Http.HeaderDictionaryExtensions.GetCommaSeparatedValues(IHeaderDictionary headers, String key)
   at \

### Further technical details
- ASP.NET Core version: 3.1.3
- Include the output of `dotnet --info`
- The IDE:  VS 2019

**Comment by Tratcher** [comment]
That's problematic. Have you noticed this affecting any other code paths?

**Comment by BrennanConroy** [comment]
Putting in next sprint, @Tratcher if you think this is important or needs backporting let us know.

(Kestrel trims header values FYI)

**Comment by Tratcher** [comment]
@pedramrezaei did you encounter this in a real app or only in a test environment?

**Comment by fstaffa** [comment]
I would like to look into this. Is this issue available for taking?

**Comment by Tratcher** [comment]
@fstaffa yes, go ahead.
