### ISSUE TITLE
AzureAD authentication does not work with Safari 13.1

### ISSUE THREAD

**Issue by akorchev** [dotnet/aspnetcore#21579]
### Describe the bug
The default Blazor template that uses AzureAD authentication does not work in Safari. Works as expected in Google Chrome running on the same machine.

### To Reproduce

1. Create a new blazor server application with AzureAD security enabled: `dotnet new blazorserver --auth SingleOrg`
1. Configure your AzureAD settings in appsettings.json
1. Try to login with Safari. End up with this screen:<img width="1447" alt="image" src="https://user-images.githubusercontent.com/454726/81315696-475b9d00-9093-11ea-8f29-aab5affef94c.png">
1. Try to login with Chrome. Works as expected:
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/454726/81315528-15e2d180-9093-11ea-9812-8478165d2c61.png">

The exception that is logged when using Safari is:

```
warn: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[15]
      '.AspNetCore.Correlation.AzureADOpenID.XHHji_MPJDw_KBqFAddnmbKy6jyp3x7MV-N3DProS1Q' cookie not found.
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: Correlation failed.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
warn: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[15]
      '.AspNetCore.Correlation.AzureADOpenID.Ch2wv3DluybRtINsU3_ZCGT09aMctwm59qe-EKAMm_s' cookie not found.
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: Correlation failed.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Further technical details
- ASP.NET Core version 3.1
- Include the output of `dotnet --info`

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.102
 Commit:    573d158fea

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.102/

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  2.1.2 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.1.400 [/usr/local/share/dotnet/sdk]
  2.1.403 [/usr/local/share/dotnet/sdk]
  2.1.500 [/usr/local/share/dotnet/sdk]
  2.2.105 [/usr/local/share/dotnet/sdk]
  3.1.101 [/usr/local/share/dotnet/sdk]
  3.1.102 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by javiercn** [comment]
@akorchev thanks for contacting us.

Are you using server-side Blazor, is that correct?

@blowdart can this be caused by any recent cookie changes?

**Comment by akorchev** [comment]
@javiercn yes, using server-side Blazor. I found issues about handling same origin cookies and Safari. Tried all workarounds mentioned but nothing makes it work in Safari. The application I am testing with is the default one generated by running `dotnet new blazorserver --auth SingleOrg`

**Comment by javiercn** [comment]
@akorchev thanks for the details.

I'm moving this to security since the issue is happening outside Blazor. They'll be able to give you a better answer.

**Comment by akorchev** [comment]
@javiercn I imagined Blazor wasn't related but I happened to use it at the moment :) Found a few closed issues about AzureAD, same origin cookies and Safari - issue should be addressed in .NET Core 3.1 but sadly I couldn't make it work.

**Comment by blowdart** [comment]
Yea, Safari seems to be determined to break SPAs, so it's possible.

**Comment by anurse** [comment]
@akaroml can you provide us the exact Safari version you are using and collect a network trace (the browser dev tools should have a way for you to do this). It's likely that Safari is the one blocking the cookie and we may be stuck here.

**Comment by akorchev** [comment]
I tested on another mac and it worked! Seems to be something related to the macOS version. The original mac I tested on had a pending autoupdate. Once I installed it it started working too. The issue was probably caused by an older macOS version.
