### ISSUE TITLE
:Method not found: 'Void Microsoft.AspNetCore.Identity.SignInManager

### ISSUE THREAD

**Issue by wangyimingok** [dotnet/aspnetcore#21612]
Error Info Comment:

```
错误消息:Method not found: 'Void Microsoft.AspNetCore.Identity.SignInManager`1..ctor(Microsoft.AspNetCore.Identity.UserManager`1<!0>, Microsoft.AspNetCore.Http.IHttpContextAccessor, Microsoft.AspNetCore.Identity.IUserClaimsPrincipalFactory`1<!0>, Microsoft.Extensions.Options.IOptions`1<Microsoft.AspNetCore.Identity.IdentityOptions>, Microsoft.Extensions.Logging.ILogger`1<Microsoft.AspNetCore.Identity.SignInManager`1<!0>>, Microsoft.AspNetCore.Authentication.IAuthenticationSchemeProvider)'.
错误追踪:   at AspNetCoreIdentity.Chloe.AspIdentityExtensions.CustomizeSignInManager..ctor(CustomizeUserManager userManager, IHttpContextAccessor contextAccessor, IUserClaimsPrincipalFactory`1 claimsFactory, IAuthenticationSchemeProvider schemes, IOptions`1 optionsAccessor, ILogger`1 logger)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Identity.SecurityStampValidator.ValidateAsync[TValidator](CookieValidatePrincipalContext context)
   at Microsoft.AspNetCore.Identity.SecurityStampValidator.ValidatePrincipalAsync(CookieValidatePrincipalContext context)
   at Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationEvents.ValidatePrincipal(CookieValidatePrincipalContext context)
   at Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
```
Code :

```C#
public class CustomizeSignInManager : SignInManager<UserInfo>
    {
        public CustomizeSignInManager(UserManager<UserInfo> userManager,
            IHttpContextAccessor contextAccessor,
            IUserClaimsPrincipalFactory<UserInfo> claimsFactory,
            IAuthenticationSchemeProvider schemes,
            IOptions<IdentityOptions> optionsAccessor,
            ILogger<CustomizeSignInManager> logger)
            : base(userManager, contextAccessor, claimsFactory, optionsAccessor, logger, schemes)
        {
        }

        public override Task<SignInResult> PasswordSignInAsync(UserInfo user, string password, bool isPersistent, bool lockoutOnFailure)
        {
            return base.PasswordSignInAsync(user, password, isPersistent, lockoutOnFailure);
        }

        public override Task<SignInResult> PasswordSignInAsync(string userName, string password, bool isPersistent, bool lockoutOnFailure)
        {
            return base.PasswordSignInAsync(userName, password, isPersistent, lockoutOnFailure);
        }

        public override Task<ClaimsPrincipal> CreateUserPrincipalAsync(UserInfo user)
        {
            return base.CreateUserPrincipalAsync(user);
        }

        protected override Task<bool> IsLockedOut(UserInfo user)
        {
            return base.IsLockedOut(user);
        }

        protected override Task<SignInResult> LockedOut(UserInfo user)
        {
            return base.LockedOut(user);
        }

        protected override Task<SignInResult> PreSignInCheck(UserInfo user)
        {
            return base.PreSignInCheck(user);
        }

        protected override Task ResetLockout(UserInfo user)
        {
            return base.ResetLockout(user);
        }

        protected override Task<SignInResult> SignInOrTwoFactorAsync(UserInfo user, bool isPersistent, string loginProvider = null, bool bypassTwoFactor = false)
        {
            return base.SignInOrTwoFactorAsync(user, isPersistent, loginProvider, bypassTwoFactor);
        }

     
    }
```

**Comment by wangyimingok** [comment]
This problem occurred when I rewritten the Microsoft.AspNetCore.Identity SignInManager class.

**Comment by wangyimingok** [comment]
> _No description provided._

**Comment by javiercn** [comment]
@wangyimingok thanks for contacting us.

It is likely you have dependency version issues.

Can you tell us more about what versions are you using and what what dependencies are part of your app?

I would also suggest you check the migration guide [here](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio) if you are updating to a newer ASP.NET Core version.

**Comment by wangyimingok** [comment]
I am using .NET Core 3.1.3, the class library in question is .NET standard2.0. It depends on ASP.NET Core Identity, and IdentityServer4 Version 3.1.2

**Comment by blowdart** [comment]
Can you please post your project dependencies

**Comment by davidfowl** [comment]
@HaoK did we remove a public constructor in 3.x?

**Comment by davidfowl** [comment]
Looks like we did ugh:

https://github.com/dotnet/core/blob/master/release-notes/3.0/api-diff/Asp.Net/3.0.0_Microsoft.AspNetCore.Identity.md

@wangyimingok You're going to have to move that project to .NET Core 3.1 instead of making it target .NET Standard. Or make it multi-target both and handle the breaking change.

We have to be more careful here to not break public constructors of types people derived from. We need to deprecate then remove.

**Comment by wangyimingok** [comment]
@davidfowl   Thanks  I think i know what to do。Thank you for helping me get rid of the confusion

**Comment by HaoK** [comment]
Yeah we had an announcement for this breaking change https://github.com/aspnet/Announcements/issues/374
