### ISSUE TITLE
Project Template test failure during aspnetcore runtime installation on Helix

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#21635]
It looks like we have a test failure on Helix caused by an exception during runtime installation. The build to investigate is https://dev.azure.com/dnceng/internal/_build/results?buildId=636258&view=ms.vss-test-web.build-test-results-tab&runId=19797422&resultId=120552&paneView=debug

The failure message I see in the logs is:
```
Adding current directory to nuget sources: /home/helixbot/work/B10D09D2/w/9E9F0905/e
Running '/home/helixbot/work/B10D09D2/w/9E9F0905/e/.dotnet2871/dotnet nuget add source /home/helixbot/work/B10D09D2/w/9E9F0905/e --configfile NuGet.config'
Package source with Name: Package source 1 added successfully.
'/home/helixbot/work/B10D09D2/w/9E9F0905/e/.dotnet2871/dotnet nuget add source /home/helixbot/work/B10D09D2/w/9E9F0905/e --configfile NuGet.config' completed with exit code '139'
Exception in InstallAspNetAppIfNeeded: System.InvalidOperationException: Command /home/helixbot/work/B10D09D2/w/9E9F0905/e/.dotnet2871/dotnet nuget add source /home/helixbot/work/B10D09D2/w/9E9F0905/e --configfile NuGet.config returned exit code 139 output: 
   at RunTests.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, CancellationToken cancellationToken) in /home/helixbot/work/B10D09D2/w/9E9F0905/e/RunTests/ProcessUtil.cs:line 144
   at RunTests.ProcessUtil.RunAsync(String filename, String arguments, String workingDirectory, Boolean throwOnError, IDictionary`2 environmentVariables, Action`1 outputDataReceived, Action`1 errorDataReceived, Action`1 onStart, CancellationToken cancellationToken) in /home/helixbot/work/B10D09D2/w/9E9F0905/e/RunTests/ProcessUtil.cs:line 144
   at RunTests.TestRunner.InstallAspNetAppIfNeededAsync() in /home/helixbot/work/B10D09D2/w/9E9F0905/e/RunTests/TestRunner.cs:line 121
```

So it seems the issue is caused by https://github.com/dotnet/aspnetcore/blob/master/eng/helix/content/RunTests/TestRunner.cs#L121-L125.

@HaoK  can you take a look?

**Comment by HaoK** [comment]
This is tracked by https://github.com/dotnet/aspnetcore/issues/20219
