### ISSUE TITLE
App Service KeyVault Integration With VNet Integration- Exception Database lookup error

### ISSUE THREAD

**Issue by pradeepjaladi** [dotnet/aspnetcore#21709]
### Describe the bug
Getting System.Net.Http.HttpRequestException: A non-recoverable error occurred during a database lookup exception when starting the App Service with VNET Integration. 

### To Reproduce

- Create a VNet with 2 subnets.

- One subnet for creating KeyVault ( Service Endpoints are Microsoft.KeyVault, Microsoft.Storage)

- One subnet for creating App Service (Service Endpoints are Microsoft.KeyVault, Microsoft.Storage, Microsoft.Web)
- Create an App Service. Do the VNET integration. Add KeyVault name as the configuration property.

``` C#

In **Program.cs** included the below code.

 public static IHostBuilder CreateHostBuilder(string[] args) =>
         Host.CreateDefaultBuilder(args)
             .ConfigureAppConfiguration((context, config) =>
             {
                 var keyVaultEndpoint = GetKeyVaultEndpoint();
                 if (!string.IsNullOrEmpty(keyVaultEndpoint))
                 {
                     var azureServiceTokenProvider = new AzureServiceTokenProvider();
                     var keyVaultClient = new KeyVaultClient(
                         new KeyVaultClient.AuthenticationCallback(
                             azureServiceTokenProvider.KeyVaultTokenCallback));
                     config.AddAzureKeyVault(keyVaultEndpoint, keyVaultClient, new DefaultKeyVaultSecretManager());
                 }
             })
             .ConfigureWebHostDefaults(webBuilder =>
             {
                 webBuilder.UseStartup<Startup>();
             });
     private static string GetKeyVaultEndpoint() => "https://<YourKeyVaultName>.vault.azure.net";

```

Exceptions:- 
Application: w3wp.exe
CoreCLR Version: 4.700.20.6603
.NET Core Version: 3.0.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.Http.HttpRequestException: A non-recoverable error occurred during a database lookup.
 ---> System.Net.Sockets.SocketException (11003): A non-recoverable error occurred during a database lookup.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Rest.RetryDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.KeyVault.KeyVaultCredential.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.KeyVault.KeyVaultClient.GetSecretsWithHttpMessagesAsync(String vaultBaseUrl, Nullable`1 maxresults, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.GetSecretsAsync(IKeyVaultClient operations, String vaultBaseUrl, Nullable`1 maxresults, CancellationToken cancellationToken)
   at Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationProvider.LoadAsync()
   at Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at UnityABC.WebApi.Program.Main(String[] args) in D:\a\1\s\src\***********\Program.cs:line 15

### Further technical details
- ASP.NET Core 3.1

**The same code is working fine without the VNet integration.**

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@Tratcher can you please assign the correct area-label to this. Not sure whether this should stay in this repo, move to the `extensions` repo or somewhere else.

**Comment by pradeepjaladi** [comment]
did anyone get a chance to look into it?

**Comment by Tratcher** [comment]
Sorry for the delay, those packages moved here: https://github.com/Azure/azure-sdk-for-net
https://github.com/aspnet/Announcements/issues/408

Please follow up with the SDK team.
