### ISSUE TITLE
Server-side Blazor: Frequent short WebSocket disconnects

### ISSUE THREAD

**Issue by belenos12345** [dotnet/aspnetcore#21881]
Hi,

I'm working on a server-side Blazor application. Running this application I get disconnects frequently. This happens during debugging on localhost as well as using the application on our test server.
Furthermore a problem of this is that all auth cookies are removed due to the disconnect. So the user gets logged out.
Unfortunately there isn't a particular action/click/page call which forces this behavior. So I can't say how to reproduce this.
But I hope there might be other people out there who have already experienced same issue and could help with this.

I've logged one case on localhost within the console:

```
Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher: Debug: Received hub invocation: InvocationMessage { InvocationId: "", Target: "EndInvokeJSFromDotNet", Arguments: [ 1230, True, [1230,true,null] ], StreamIds: [  ] }.
Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher: Trace: InvocationId (null): Sending result of type 'System.Void'.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Sending payload: 2919 bytes.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Sending payload: 2919 bytes.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Sending payload: 23565 bytes.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Sending payload: 238 bytes.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Sending payload: 196 bytes.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Sending payload: 178 bytes.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Sending payload: 279 bytes.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Sending payload: 279 bytes.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Sending payload: 279 bytes.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Sending payload: 279 bytes.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Sending payload: 174 bytes.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Sending payload: 543 bytes.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Sending payload: 174 bytes.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Sending payload: 543 bytes.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Sending payload: 174 bytes.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Sending payload: 543 bytes.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Sending payload: 543 bytes.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Sending payload: 104 bytes.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Sending payload: 104 bytes.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Sending payload: 104 bytes.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Sending payload: 104 bytes.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Sending payload: 104 bytes.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Sending payload: 104 bytes.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Sending payload: 104 bytes.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Sending payload: 104 bytes.
Exception thrown: 'Microsoft.AspNetCore.Connections.ConnectionResetException' in Microsoft.AspNetCore.Server.IIS.dll
Exception thrown: 'Microsoft.AspNetCore.Connections.ConnectionResetException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.AspNetCore.Connections.ConnectionResetException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.AspNetCore.Connections.ConnectionResetException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.AspNetCore.Connections.ConnectionResetException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Net.WebSockets.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Private.CoreLib.dll
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.3\System.Diagnostics.StackTrace.dll'. 
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.3\System.Reflection.Metadata.dll'. 
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Debug: Socket connection closed prematurely.

System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> Microsoft.AspNetCore.Connections.ConnectionResetException: The client has disconnected
 ---> System.Runtime.InteropServices.COMException (0x800704CD): Es wurde versucht, auf eine nicht vorhandene Netzwerkverbindung zuzugreifen. (0x800704CD)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.IIS.Core.IO.AsyncIOOperation.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadBody()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadAsync(Memory`1 memory, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IIS.Core.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsServerTransport.StartReceiving(WebSocket socket)
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Debug: Waiting for the application to finish sending data.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Debug: Socket closed.
Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext: Trace: Disposing connection 8FE-SmJEB1D0RUWx8dXjLA.
Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext: Trace: Waiting for application to complete.
Microsoft.AspNetCore.SignalR.HubConnectionHandler: Debug: OnConnectedAsync ending.
Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext: Trace: Application complete.
Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager: Debug: Removing connection qSMJEL5tNU3rTLk5nrX_xw from the list of connections.
Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager: Debug: New connection es3QXXbAgihjUVXi211hVw created.
Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher: Debug: Sending negotiation response.
Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher: Debug: Establishing new connection.
Microsoft.AspNetCore.SignalR.HubConnectionHandler: Debug: OnConnectedAsync started.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Debug: Socket opened using Sub-Protocol: '(null)'.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Message received. Type: Text, size: 38, EndOfMessage: True.
Microsoft.AspNetCore.SignalR.Internal.DefaultHubProtocolResolver: Debug: Found protocol implementation for requested protocol: blazorpack.
Microsoft.AspNetCore.SignalR.HubConnectionContext: Debug: Completed connection handshake. Using HubProtocol 'blazorpack'.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Sending payload: 3 bytes.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Message received. Type: Binary, size: 245, EndOfMessage: True.
Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher: Debug: Received hub invocation: InvocationMessage { InvocationId: "0", Target: "ConnectCircuit", Arguments: [ CfDJ8Hy6nGrT4bRAtvHZDDv3QE4idYpgvocWjooUF0ypIU4d2QFQXnLVnBfBIzseKV-LRhC60wxVjdqZkcUdFGKUASZUiIU4a5mWs2TYam17ichgx6gxoM5ueM7_v9JuiXbr91zEbuiw0MHdHeCb6U_QPCA_36siQCR0h3BfgEwTdqEjdB0PwG7CROaiqdapc-obGR9-vIeRtB0GjsLrNSJy2N0 ], StreamIds: [  ] }.
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Sending payload: 18869 bytes.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Sending payload: 2919 bytes.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Trace: Sending payload: 48272 bytes.
Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher: Trace: InvocationId 0: Sending result of type 'System.Boolean'.
```

Any ideas on this?

### Further technical details
- ASP.NET Core version: 3.1

```
.NET Core SDK (gemäß "global.json"):
 Version:   3.1.201
 Commit:    b1768b4ae7

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

I use VS 2019 Version 16.5.4

**Comment by BrennanConroy** [comment]
Are you only seeing this with IIS?

Can you grab the client logs?
Add this to your _Host.cshtml

    <script src="_framework/blazor.server.js" autostart="false"></script>
    <script>
        (function start() {
            Blazor.start({
                logLevel: 1, // LogLevel.Debug
                configureSignalR: builder => builder.configureLogging("debug") // LogLevel.Debug
            });
        })()
    </script>

**Comment by belenos12345** [comment]
> Are you only seeing this with IIS?
> 
> Can you grab the client logs?
> Add this to your _Host.cshtml
> 
> ```
> <script src="_framework/blazor.server.js" autostart="false"></script>
> <script>
>     (function start() {
>         Blazor.start({
>             logLevel: 1, // LogLevel.Debug
>             configureSignalR: builder => builder.configureLogging("debug") // LogLevel.Debug
>         });
>     })()
> </script>
> ```

Silly question... can I get this client log from VS output console if I use your provided script? Or where can I get it from?

**Comment by BrennanConroy** [comment]
You can view the client side logs from the browser console logs.

**Comment by belenos12345** [comment]
> You can view the client side logs from the browser console logs.

Ah, ok... sure:
```

[2020-05-15T21:15:49.066Z] Debug: Received render batch with id 503 and 48 bytes.
blazor.server.js:15 [2020-05-15T21:15:49.066Z] Debug: Applying batch 503.
blazor.server.js:15 [2020-05-15T21:15:49.645Z] Debug: Received render batch with id 504 and 59878 bytes.
blazor.server.js:15 [2020-05-15T21:15:49.645Z] Debug: Applying batch 504.
blazor.server.js:15 [2020-05-15T21:15:51.416Z] Debug: Received render batch with id 505 and 385199 bytes.
blazor.server.js:15 [2020-05-15T21:15:51.419Z] Debug: Applying batch 505.
blazor.server.js:15 [2020-05-15T21:15:53.046Z] Debug: Received render batch with id 506 and 1404 bytes.
blazor.server.js:15 [2020-05-15T21:15:53.046Z] Debug: Applying batch 506.
blazor.server.js:15 [2020-05-15T21:15:53.137Z] Debug: Received render batch with id 507 and 1404 bytes.
blazor.server.js:15 [2020-05-15T21:15:53.137Z] Debug: Applying batch 507.
blazor.server.js:15 [2020-05-15T21:15:53.139Z] Debug: Received render batch with id 508 and 1404 bytes.
blazor.server.js:15 [2020-05-15T21:15:53.139Z] Debug: Applying batch 508.
blazor.server.js:15 [2020-05-15T21:15:53.212Z] Debug: Received render batch with id 509 and 1519414 bytes.
blazor.server.js:15 [2020-05-15T21:15:53.222Z] Debug: Applying batch 509.
blazor.server.js:15 [2020-05-15T21:16:07.189Z] Debug: Received render batch with id 510 and 97631 bytes.
blazor.server.js:15 [2020-05-15T21:16:07.191Z] Debug: Applying batch 510.
blazor.server.js:15 [2020-05-15T21:16:07.235Z] Debug: Received render batch with id 511 and 48 bytes.
blazor.server.js:15 [2020-05-15T21:16:07.235Z] Debug: Applying batch 511.
blazor.server.js:1 WebSocket connection to 'wss://localhost:44384/_blazor?id=9FyV-f49QOrQAJZbQagITg' failed: Unknown reason
blazor.server.js:1 [2020-05-15T21:16:07.353Z] Debug: HttpConnection.stopConnection(Error: WebSocket closed with status code: 1006 ().) called while in state Connected.
blazor.server.js:1 [2020-05-15T21:16:07.353Z] Error: Connection disconnected with error 'Error: WebSocket closed with status code: 1006 ().'.
blazor.server.js:1 [2020-05-15T21:16:07.354Z] Debug: HubConnection.connectionClosed(Error: WebSocket closed with status code: 1006 ().) called while in state Connected.
blazor.server.js:1 [2020-05-15T21:16:10.362Z] Information: Normalizing '_blazor' to 'https://localhost:44384/_blazor'.
blazor.server.js:1 [2020-05-15T21:16:10.365Z] Debug: Starting HubConnection.
blazor.server.js:1 [2020-05-15T21:16:10.367Z] Debug: Starting connection with transfer format 'Binary'.
blazor.server.js:1 [2020-05-15T21:16:10.369Z] Debug: Sending negotiation request: https://localhost:44384/_blazor/negotiate?negotiateVersion=1.
blazor.server.js:1 [2020-05-15T21:16:10.484Z] Debug: Selecting transport 'WebSockets'.
blazor.server.js:1 [2020-05-15T21:16:10.550Z] Information: WebSocket connected to wss://localhost:44384/_blazor?id=oEUAbX_BN92EcxBZ3usF1Q.
blazor.server.js:1 [2020-05-15T21:16:10.550Z] Debug: The HttpConnection connected successfully.
blazor.server.js:1 [2020-05-15T21:16:10.551Z] Debug: Sending handshake request.
blazor.server.js:1 [2020-05-15T21:16:10.552Z] Information: Using HubProtocol 'blazorpack'.
blazor.server.js:1 [2020-05-15T21:16:10.570Z] Debug: Server handshake complete.
blazor.server.js:1 [2020-05-15T21:16:10.571Z] Debug: HubConnection connected successfully.
blazor.server.js:15 [2020-05-15T21:16:12.858Z] Debug: Received render batch with id 513 and 374732 bytes.
blazor.server.js:15 [2020-05-15T21:16:12.861Z] Debug: Waiting for batch 512. Batch 513 not processed.
blazor.server.js:15 [2020-05-15T21:16:12.863Z] Debug: Received render batch with id 510 and 97631 bytes.
blazor.server.js:15 [2020-05-15T21:16:12.864Z] Debug: Batch 510 already processed. Waiting for batch 512.
blazor.server.js:15 [2020-05-15T21:16:12.864Z] Debug: Received render batch with id 511 and 48 bytes.
blazor.server.js:15 [2020-05-15T21:16:12.865Z] Debug: Batch 511 already processed. Waiting for batch 512.
blazor.server.js:15 [2020-05-15T21:16:12.869Z] Debug: Received render batch with id 512 and 97224 bytes.
blazor.server.js:15 [2020-05-15T21:16:12.871Z] Debug: Applying batch 512.
blazor.server.js:15 [2020-05-15T21:16:12.909Z] Debug: Received render batch with id 513 and 374732 bytes.
```

**Comment by mkArtakMSFT** [comment]
@BrennanConroy can you please follow up ? Thanks!

**Comment by BrennanConroy** [comment]
This is a strange one. From the logs, both sides of the connection closed unexpectedly which implies something in the middle disrupted the connection.

Could you describe your environment. Is the client connecting directly to the server, or is it going through a proxy? What browser(s) are you using? What OS(s) are you using?

Do you have an app you can put on GitHub that we can try out?

Can you try running without IIS and see if the issue still happens?

**Comment by belenos12345** [comment]
We develope our apps using VS2019 on Win10 Pro.
For tests and debugging we use Chrome and/or Firefox.
Debugging is done on localhost. So I would say this is a direct connection.
Our Dev and Test servers are reached via ZScaler Private Access. But it doesn't matter whether we use these servers or debug locally... the issue is the same on both.

I've tried "dotnet run" to test without IIS... same behavior.
My current test process is just to switch quickly between the app pages. So there is a good chance to force the behavior.

Unfortunately I don't have a prepared app which I could share at the moment. But I'm working on it.

**Comment by BrennanConroy** [comment]
Could you give a brief overview of what you're doing in your app. I'd love to be able to repro this, but I can't with the default Blazor template.

**Comment by belenos12345** [comment]
It is an app to upload Excel sheets into a grid (Telerik Grid), edit the data of the grid by using edit forms and export the data to Excel again. This is done on the "main working page". It contains the Telerik grid and some funtionality to edit/import/export data.
Around this core funtionality there are some pages to administrate clients, suppliers, users and layout of the data grid.

We use MS SQL Server 2016 as DB.
For some UI elements we use Telerik components.
Furthermore we use Dapper for most of data access.

User authentication/authorization is done by the default Identity logic + roles.
Additional to that there is a second option to login with AzureAD authentication. The Azure principal is then mapped to an Identity user who will be logged in.

**Comment by BrennanConroy** [comment]
> Unfortunately I don't have a prepared app which I could share at the moment. But I'm working on it.

Sadly we can't repro this and don't know why it is happening. Having a repro app would significantly help here :)

**Comment by fabiano-ferreira** [comment]
Hello @BrennanConroy !

I have a scenario very similar to @belenos12345 . And unfortunatelly I'm having  constant Websock disconnections...

The issue happens excactly when we don't have user activity for at last 2 minutes, then when I try to access a page that does not exist, I have the default response: "Sorry, page not found."

Then, when I click on the browser Back button it generates the following browser log:

blazor.server.js:15 [2020-06-01T22:21:14.780Z] Information: Starting up blazor server-side application.
blazor.server.js:1 [2020-06-01T22:21:14.782Z] Information: Normalizing '_blazor' to '<server>/_blazor'.
blazor.server.js:1 [2020-06-01T22:21:14.783Z] Debug: Starting HubConnection.
blazor.server.js:1 [2020-06-01T22:21:14.784Z] Debug: Starting connection with transfer format 'Binary'.
blazor.server.js:1 [2020-06-01T22:21:14.785Z] Debug: Sending negotiation request: <server>/_blazor/negotiate?negotiateVersion=1.
blazor.server.js:1 [2020-06-01T22:21:14.820Z] Debug: Skipping transport 'ServerSentEvents' because it does not support the requested transfer format 'Binary'.
blazor.server.js:1 [2020-06-01T22:21:14.820Z] Debug: Selecting transport 'LongPolling'.
blazor.server.js:1 [2020-06-01T22:21:14.841Z] Debug: The HttpConnection connected successfully.
blazor.server.js:1 [2020-06-01T22:21:14.841Z] Debug: Sending handshake request.
blazor.server.js:1 [2020-06-01T22:21:14.849Z] Debug: Server handshake complete.
blazor.server.js:1 [2020-06-01T22:21:14.927Z] Information: Using HubProtocol 'blazorpack'.
blazor.server.js:1 [2020-06-01T22:21:14.927Z] Debug: HubConnection connected successfully.
blazor.server.js:15 [2020-06-01T22:21:14.941Z] Error: The list of component records is not valid.
e.log @ blazor.server.js:15
C @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:1
e.invokeClientMethod @ blazor.server.js:1
e.processIncomingData @ blazor.server.js:1
connection.onreceive @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
a @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
a @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
a @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
a @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
k @ blazor.server.js:1
e.poll @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
a @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
a @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
k @ blazor.server.js:1
e.connect @ blazor.server.js:1
e.startTransport @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
B @ blazor.server.js:1
e.createTransport @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
a @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
B @ blazor.server.js:1
e.startInternal @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
B @ blazor.server.js:1
e.start @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
v @ blazor.server.js:1
e.startInternal @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
v @ blazor.server.js:1
e.startWithStateTransitions @ blazor.server.js:1
e.start @ blazor.server.js:1
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
r @ blazor.server.js:8
S @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
r @ blazor.server.js:8
E @ blazor.server.js:8
start @ RegionCluster:144
(anonymous) @ RegionCluster:148
Show 37 more frames
blazor.server.js:1 [2020-06-01T22:21:14.942Z] Debug: Stopping HubConnection.
blazor.server.js:1 [2020-06-01T22:21:14.950Z] Debug: HttpConnection.stopConnection(undefined) called while in state Disconnecting.
blazor.server.js:1 [2020-06-01T22:21:14.950Z] Information: Connection disconnected.
blazor.server.js:1 [2020-06-01T22:21:14.951Z] Debug: HubConnection.connectionClosed(undefined) called while in state Disconnecting.
blazor.server.js:1 [2020-06-01T22:21:14.951Z] Error: HttpConnection.transport.stop() threw error 'Error: Not Found'.
e.log @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
s @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
a @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
a @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
B @ blazor.server.js:1
e.stopInternal @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
B @ blazor.server.js:1
e.stop @ blazor.server.js:1
e.stopInternal @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
v @ blazor.server.js:1
e.stop @ blazor.server.js:1
C @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:1
e.invokeClientMethod @ blazor.server.js:1
e.processIncomingData @ blazor.server.js:1
connection.onreceive @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
a @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
a @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
a @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
a @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
k @ blazor.server.js:1
e.poll @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
a @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
a @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
k @ blazor.server.js:1
e.connect @ blazor.server.js:1
e.startTransport @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
B @ blazor.server.js:1
e.createTransport @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
a @ blazor.server.js:1
Promise.then (async)
c @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
B @ blazor.server.js:1
e.startInternal @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
B @ blazor.server.js:1
e.start @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
v @ blazor.server.js:1
e.startInternal @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
(anonymous) @ blazor.server.js:1
v @ blazor.server.js:1
e.startWithStateTransitions @ blazor.server.js:1
e.start @ blazor.server.js:1
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
r @ blazor.server.js:8
S @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
r @ blazor.server.js:8
E @ blazor.server.js:8
start @ RegionCluster:144
(anonymous) @ RegionCluster:148
Show 37 more frames
blazor.server.js:1 [2020-06-01T22:21:14.951Z] Debug: HttpConnection.stopConnection(undefined) called while in state Disconnected.
blazor.server.js:1 [2020-06-01T22:21:14.951Z] Debug: Call to HttpConnection.stopConnection(undefined) was ignored because the connection is already in the disconnected state.

**Comment by fabiano-ferreira** [comment]
> Error: The list of component records is not valid.

I juste tested with pages completely blank (without database objects or Telerik components) and I still have the same error if I follow the same test scenario:

- Open a page and wait for 2/4 minutes with no activity
- Try to access an invalid link in my application (redirected to default not found content);
- Click on browser back button

Same error occurs:

Error: The list of component records is not valid.

**Comment by BrennanConroy** [comment]
@fabiano-ferreira You are having a different problem please file a new issue.

Also note that you're not using WebSockets
> blazor.server.js:1 [2020-06-01T22:21:14.820Z] Debug: Selecting transport 'LongPolling'.

**Comment by fabiano-ferreira** [comment]
Hi @BrennanConroy ! Sorry! I meant LongPolling. Should I open a new thread in this case?
