### ISSUE TITLE
WebAssemblyRenderer crash

### ISSUE THREAD

**Issue by hultqvist** [dotnet/aspnetcore#21936]
### Steps to reproduce

1. Click the checkbox
2. Click the button (checkbox is still checked)
3. Click the checkbox (crash logged in console)

```C#
@code
{
    public bool Show { get; set; }
}

<label>
    <input type="checkbox" @bind-value="Show"> Show
</label>

<button @onclick="()=>Show = false">Hide</button>
```

Error message in this code

```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot read property 'parentNode' of undefined
      TypeError: Cannot read property 'parentNode' of undefined
          at Object.e [as removeLogicalChild] (https://localhost:44321/_framework/blazor.webassembly.js:1:6975)
          at e.applyEdits (https://localhost:44321/_framework/blazor.webassembly.js:1:13717)
          at e.updateComponent (https://localhost:44321/_framework/blazor.webassembly.js:1:12948)
          at Object.t.renderBatch (https://localhost:44321/_framework/blazor.webassembly.js:1:1704)
          at Object.window.Blazor._internal.renderBatch (https://localhost:44321/_framework/blazor.webassembly.js:1:34848)
          at _mono_wasm_invoke_js_unmarshalled (https://localhost:44321/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js:1:172151)
          at wasm_invoke_iiiiii (wasm-function[3160]:0x9d403)
          at icall_trampoline_dispatch (wasm-function[5776]:0x1007ce)
          at mono_wasm_interp_to_native_trampoline (wasm-function[4606]:0xcc8da)
          at ves_pinvoke_method (wasm-function[3209]:0x9ee05)
Microsoft.JSInterop.JSException: Cannot read property 'parentNode' of undefined
TypeError: Cannot read property 'parentNode' of undefined
    at Object.e [as removeLogicalChild] (https://localhost:44321/_framework/blazor.webassembly.js:1:6975)
    at e.applyEdits (https://localhost:44321/_framework/blazor.webassembly.js:1:13717)
    at e.updateComponent (https://localhost:44321/_framework/blazor.webassembly.js:1:12948)
    at Object.t.renderBatch (https://localhost:44321/_framework/blazor.webassembly.js:1:1704)
    at Object.window.Blazor._internal.renderBatch (https://localhost:44321/_framework/blazor.webassembly.js:1:34848)
    at _mono_wasm_invoke_js_unmarshalled (https://localhost:44321/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js:1:172151)
    at wasm_invoke_iiiiii (wasm-function[3160]:0x9d403)
    at icall_trampoline_dispatch (wasm-function[5776]:0x1007ce)
    at mono_wasm_interp_to_native_trampoline (wasm-function[4606]:0xcc8da)
    at ves_pinvoke_method (wasm-function[3209]:0x9ee05)
  at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[T0,T1,T2,TResult] (System.String identifier, T0 arg0, T1 arg1, T2 arg2) <0x2cb0a58 + 0x00046> in <filename unknown>:0 
  at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[T0,T1,TResult] (System.String identifier, T0 arg0, T1 arg1) <0x2cb0978 + 0x00014> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer.UpdateDisplayAsync (Microsoft.AspNetCore.Components.RenderTree.RenderBatch& batch) <0x2cb0880 + 0x0001e> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue () <0x2b64c98 + 0x000f2> in <filename unknown>:0 
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Consider using `@bind` instead of `@bind-value`. That should fix it. 

As for improving the error, we'll handle it as part of https://github.com/dotnet/aspnetcore/issues/21950
