### ISSUE TITLE
QUESTION: How to specify a resource as required for booting in blazor wasm

### ISSUE THREAD

**Issue by msschl** [dotnet/aspnetcore#22023]
First of all blazor wasm is awesome ❤. Thanks for your hard work!

### Describe the bug
I happend to have a Razor components class library that is required before blazor wasm boots, as it sets a property on the window. Unfortunately this library is about 1MB in size (I don't quite understand why, but this is a separate issue).
When the app loads and the network is slow e.g. Slow 3G this resource needs about 6s to load. Meanwhile other resources like `blazor.webassembly.js` are about 60kB and only need about 1s to load. As a result, when blazor boots and the first page tries to render it fails with the following message:
```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find 'BlazorLeaflet' in 'window'.
      Error: Could not find 'BlazorLeaflet' in 'window'.
          at https://localhost:5001/_framework/blazor.webassembly.js:1:9198
          at Array.forEach (<anonymous>)
          at p (https://localhost:5001/_framework/blazor.webassembly.js:1:9158)
          at https://localhost:5001/_framework/blazor.webassembly.js:1:9868
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.webassembly.js:1:9841)
          at _mono_wasm_invoke_js_marshalled (https://localhost:5001/_framework/wasm/dotnet.3.2.0.js:1:171294)
          at do_icall (wasm-function[6049]:0x10f8b1)
          at do_icall_wrapper (wasm-function[1896]:0x50b6a)
          at interp_exec_method (wasm-function[1120]:0x2588e)
Microsoft.JSInterop.JSException: Could not find 'BlazorLeaflet' in 'window'.
Error: Could not find 'BlazorLeaflet' in 'window'.
    at https://localhost:5001/_framework/blazor.webassembly.js:1:9198
    at Array.forEach (<anonymous>)
    at p (https://localhost:5001/_framework/blazor.webassembly.js:1:9158)
    at https://localhost:5001/_framework/blazor.webassembly.js:1:9868
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.webassembly.js:1:9841)
    at _mono_wasm_invoke_js_marshalled (https://localhost:5001/_framework/wasm/dotnet.3.2.0.js:1:171294)
    at do_icall (wasm-function[6049]:0x10f8b1)
    at do_icall_wrapper (wasm-function[1896]:0x50b6a)
    at interp_exec_method (wasm-function[1120]:0x2588e)
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () <0x237d738 + 0x0002c> in <filename unknown>:0 
  at Blazor.Leaflet.BlazorLeafletInterop.GetVersions () <0x23970a8 + 0x000d0> in <filename unknown>:0 
  at Company.XYZ.Service.Map.Client.Pages.Index.OnAfterRenderAsync (System.Boolean firstRender) <0x23891b8 + 0x00100> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask (System.Threading.Tasks.Task taskToHandle) <0x2230958 + 0x000ca> in <filename unknown>:0 
```

How can I specify a resource as required for booting, before the page gets first rendered?

### Further technical details
- ASP.NET Core version 3.1.4
- Blazor wasm v3.2.0
```
dotnet --info
.NET Core SDK (gemäß "global.json"):
 Version:   3.1.202
 Commit:    6ea70c8dca

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.202\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6
```

**Comment by javiercn** [comment]
@msschl thanks for contacting us.

The recommended way to do this is that you put you load your library script before loading the blazor script or turn off autostart on blazor and call start manually.

**Comment by msschl** [comment]
Thanks @javiercn

Switching the order fix it 👍 
```html
<app>
   ...
</app>

<script src="_content/Blazor.Leaflet/blazor.leaflet.js"></script>
<script src="_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js"></script>
<script src="_framework/blazor.webassembly.js"></script>
```
