### ISSUE TITLE
QuarantinedTest: Microsoft.AspNetCore.Components.E2ETest.Tests.KeyTest.CanDeleteUnkeyed

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#22034]
https://dev.azure.com/dnceng/internal/_build/results?buildId=652943&view=ms.vss-test-web.build-test-results-tab&runId=20267676&paneView=debug&resultId=100000

```
OpenQA.Selenium.StaleElementReferenceException : stale element reference: element is not attached to the page document\n (Session info: headless chrome=83.0.4103.61)\n (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17763 x86_64)
```

```
Stack trace
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.Remote.RemoteWebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.Remote.RemoteWebElement.Execute(String commandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.Remote.RemoteWebElement.FindElement(String mechanism, String value)
at OpenQA.Selenium.Remote.RemoteWebElement.FindElementByClassName(String className)
at OpenQA.Selenium.By.<>c__DisplayClass20_0.<ClassName>b__0(ISearchContext context)
at OpenQA.Selenium.By.FindElement(ISearchContext context)
at OpenQA.Selenium.Remote.RemoteWebElement.FindElement(By by)
at Microsoft.AspNetCore.Components.E2ETest.Tests.KeyTest.ReadNodeFromDOM(IWebElement nodeElem) in /_/src/Components/test/E2ETest/Tests/KeyTest.cs:line 319
at System.Linq.Enumerable.SelectIListIterator`2.ToArray()
at Microsoft.AspNetCore.Components.E2ETest.Tests.KeyTest.ReadNodeFromDOM(IWebElement nodeElem) in /_/src/Components/test/E2ETest/Tests/KeyTest.cs:line 322
at System.Linq.Enumerable.SelectIListIterator`2.ToArray()
at Microsoft.AspNetCore.Components.E2ETest.Tests.KeyTest.ReadNodeFromDOM(IWebElement nodeElem) in /_/src/Components/test/E2ETest/Tests/KeyTest.cs:line 322
at Microsoft.AspNetCore.Components.E2ETest.Tests.KeyTest.ValidateRenderedOutput(IWebElement appElem, Node expectedRootNode, Boolean validatePreservation) in /_/src/Components/test/E2ETest/Tests/KeyTest.cs:line 298
at Microsoft.AspNetCore.Components.E2ETest.Tests.KeyTest.PerformTest(Node[] before, Node[] after) in /_/src/Components/test/E2ETest/Tests/KeyTest.cs:line 288
at Microsoft.AspNetCore.Components.E2ETest.Tests.KeyTest.CanDeleteUnkeyed() in /_/src/Components/test/E2ETest/Tests/KeyTest.cs:line 96
```

**Comment by mkArtakMSFT** [comment]
@javiercn can you please handle this? Thanks!
