### ISSUE TITLE
Skipped test: Microsoft.AspNetCore.Razor.Design.IntegrationTests.StaticWebAssetsIntegrationTest.Rebuild_Success_RecreatesManifestAndCache

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#22049]
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=653921&view=ms.vss-test-web.build-test-results-tab&runId=20296874&resultId=100112&paneView=debug

```
System.TimeoutException : command '$F:\workspace\_work\1\s\.dotnet\dotnet.exe msbuild /nr:false /bl /p:RunningAsTest=true /p:MicrosoftNETCoreApp50PackageVersion=5.0.0-preview.6.20264.1 /p:MicrosoftNetCompilersToolsetPackageVersion=3.7.0-2.20267.1 /p:_RazorBuildServerPipeName="e8b09955-1b9b-4211-b8d2-52ecd69ad7d8" /t:Build /p:Configuration=Debug ' timed out after 00:05:00. Output: Microsoft (R) Build Engine version 16.7.0-preview-20257-02+b861333fc for .NET\r\nCopyright (C) Microsoft Corporation. All rights reserved.\r\n\r\nF:\workspace\_work\1\s\.dotnet\sdk\5.0.100-preview.5.20258.4\MSBuild.dll -maxcpucount -verbosity:m /bl /nr:false /p:RunningAsTest=true /p:MicrosoftNETCoreApp50PackageVersion=5.0.0-preview.6.20264.1 /p:MicrosoftNetCompilersToolsetPackageVersion=3.7.0-2.20267.1 /p:_RazorBuildServerPipeName=e8b09955-1b9b-4211-b8d2-52ecd69ad7d8 /p:Configuration=Debug /t:Build .\AppWithPackageAndP2PReference.csproj\r\n You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview\r\n You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview\r\n ClassLibrary -> C:\Users\vsagent\AppData\Local\Temp\Razor\xlekvqrk.euk\ClassLibrary\bin\Debug\net5.0\ClassLibrary.dll\r\n ClassLibrary -> C:\Users\vsagent\AppData\Local\Temp\Razor\xlekvqrk.euk\ClassLibrary\bin\Debug\net5.0\ClassLibrary.Views.dll\r\n
```

Stack trace
```
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.<>c__DisplayClass1_0.<<RunProcessCoreAsync>g__GetTimeoutForProcess|3>d.MoveNext() in /_/src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildProcessManager.cs:line 154
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.RunProcessAsync(ProjectDirectory project, String arguments, Nullable`1 timeout, MSBuildProcessKind msBuildProcessKind) in /_/src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildProcessManager.cs:line 53
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.StaticWebAssetsIntegrationTest.Rebuild_Success_RecreatesManifestAndCache() in /_/src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/StaticWebAssetsIntegrationTest.cs:line 191
--- End of stack trace from previous location ---
```

**Comment by pranavkm** [comment]
Also skipped Microsoft.AspNetCore.Razor.Design.IntegrationTests.StaticWebAssetsIntegrationTest.Build_GeneratesStaticWebAssetsManifest_Success_CreatesManifest which failed in a very similar way:

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=654186&view=ms.vss-test-web.build-test-results-tab&runId=20303614&resultId=100122&paneView=debug

```
System.TimeoutException : command '$F:\workspace\_work\1\s\.dotnet\dotnet.exe msbuild /nr:false /bl /p:RunningAsTest=true /p:MicrosoftNETCoreApp50PackageVersion=5.0.0-preview.6.20264.1 /p:MicrosoftNetCompilersToolsetPackageVersion=3.7.0-2.20267.1 /p:_RazorBuildServerPipeName="66e9fab6-ab60-4dd7-9212-9b42be544fc2" /t:Build /p:Configuration=Debug ' timed out after 00:05:00. Output: Microsoft (R) Build Engine version 16.7.0-preview-20257-02+b861333fc for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

F:\workspace\_work\1\s\.dotnet\sdk\5.0.100-preview.5.20258.4\MSBuild.dll -maxcpucount -verbosity:m /bl /nr:false /p:RunningAsTest=true /p:MicrosoftNETCoreApp50PackageVersion=5.0.0-preview.6.20264.1 /p:MicrosoftNetCompilersToolsetPackageVersion=3.7.0-2.20267.1 /p:_RazorBuildServerPipeName=66e9fab6-ab60-4dd7-9212-9b42be544fc2 /p:Configuration=Debug /t:Build .\AppWithPackageAndP2PReference.csproj
 You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
 You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
```


Stack trace
```
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.<>c__DisplayClass1_0.<<RunProcessCoreAsync>g__GetTimeoutForProcess|3>d.MoveNext() in /_/src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildProcessManager.cs:line 154
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.RunProcessAsync(ProjectDirectory project, String arguments, Nullable`1 timeout, MSBuildProcessKind msBuildProcessKind) in /_/src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildProcessManager.cs:line 53
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.StaticWebAssetsIntegrationTest.Build_GeneratesStaticWebAssetsManifest_Success_CreatesManifest() in /_/src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/StaticWebAssetsIntegrationTest.cs:line 35
--- End of stack trace from previous location ---
```
