### ISSUE TITLE
JSonPatch doesn't work 

### ISSUE THREAD

**Issue by erwan-joly** [dotnet/aspnetcore#22216]
### Describe the bug
When trying to use a JsonPatchDocument i get error trying to deserialize an interface.
https://github.com/dotnet/aspnetcore/blob/master/src/Features/JsonPatch/src/JsonPatchDocument.cs#L24
https://github.com/dotnet/aspnetcore/blob/master/src/Features/JsonPatch/src/JsonPatchDocumentOfT.cs
This seems to be because it's still using Newtonsoft instead of the new JSon.Net
```
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
```
my understanding is that it should be 
```
using System.Text.Json;
using System.Text.Json.Serialization;
```

### To Reproduce
``` 
[HttpPatch]
public HttpStatusCode Test([FromBody] JsonPatchDocument data)
```
This will error on binding.

```
System.NotSupportedException: Deserialization of interface types is not supported. Type 'Newtonsoft.Json.Serialization.IContractResolver' Path: $.ContractResolver | LineNumber: 0 | BytePositionInLine: 140.
 ---> System.NotSupportedException: Deserialization of interface types is not supported. Type 'Newtonsoft.Json.Serialization.IContractResolver'
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_DeserializeNoDeserializationConstructor(Type invalidType)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(ReadStack& state, Utf8JsonReader& reader, NotSupportedException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### Further technical details
- ASP.NET Core 3.1
- Windows
- Visual Studio 2019

**Comment by pranavkm** [comment]
JsonPatch requires using Newtonsoft.Json in the app. https://docs.microsoft.com/en-us/aspnet/core/web-api/jsonpatch has some suggestions on configuring the application to use `Newtonsoft.Json` specifically for JsonPatch while using S.T.Json for the remainder of JSON serialization.

**Comment by erwan-joly** [comment]
@pranavkm is the second method still working ?
if i use that it works perfectly (my understanding is that it use newtonsoftjson for everything)
```
            services
                .AddControllers()
                .AddNewtonsoftJson()
               .AddControllersAsServices();
```

but when i use this
```
            services
                  .AddControllers(options =>
                 {
                      options.InputFormatters.Insert(0, GetJsonPatchInputFormatter());
                 })
                .AddControllersAsServices();
```
json patch is deserialized as null.

i did a quick repo to reproduce:

https://github.com/erwan-joly/jsonpatchbugexample/blob/master/JSonPatchExample/Program.cs#L58

**Comment by pranavkm** [comment]
The media type in your application isn't configured correctly: https://github.com/erwan-joly/jsonpatchbugexample/blob/master/JSonPatchExample/Program.cs#L77. It needs to be `application/json-patch+json`: https://tools.ietf.org/html/rfc6902#section-1.

**Comment by erwan-joly** [comment]
Thanks @pranavkm it definitely was the issue.
got it wrong as AddNewtonsoftJson make it works with just application/json and i was not aware of the other mime type.
