### ISSUE TITLE
Razor tooling move breaks helix runs

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#22282]
https://dev.azure.com/dnceng/public/_build/results?buildId=661189&view=logs&j=3f6d4e0f-1b71-56b5-361e-d95b6e6da15a&t=9605d305-57d3-55b8-ba79-e50442d32137&l=1838

```
 Exception performing Extension dependency check:
  System.IO.DirectoryNotFoundException: Could not find a part of the path 'F:\workspace\_work\1\s\artifacts\bin\Microsoft.NET.Sdk.Razor\Release\sdk-output\extensions\mvc-3-0\Microsoft.AspNetCore.Mvc.Razor.Extensions.dll'.
     at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
     at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
     at Microsoft.AspNetCore.Razor.Tools.DefaultExtensionDependencyChecker.ExtensionVerificationItem.Create(String filePath) in /_/src/Razor/Microsoft.AspNetCore.Razor.Tools/src/DefaultExtensionDependencyChecker.cs:line 128
     at Microsoft.AspNetCore.Razor.Tools.DefaultExtensionDependencyChecker.<>c.<CheckCore>b__7_0(String a) in /_/src/Razor/Microsoft.AspNetCore.Razor.Tools/src/DefaultExtensionDependencyChecker.cs:line 60
     at System.Linq.Enumerable.SelectListIterator`2.ToArray()
     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
     at Microsoft.AspNetCore.Razor.Tools.DefaultExtensionDependencyChecker.CheckCore(IEnumerable`1 assemblyFilePaths) in /_/src/Razor/Microsoft.AspNetCore.Razor.Tools/src/DefaultExtensionDependencyChecker.cs:line 60
     at Microsoft.AspNetCore.Razor.Tools.DefaultExtensionDependencyChecker.Check(IEnumerable`1 assmblyFilePaths) in /_/src/Razor/Microsoft.AspNetCore.Razor.Tools/src/DefaultExtensionDependencyChecker.cs:line 48
  Extenions could not be loaded. See output for details.

```

**Comment by JunTaoLuo** [comment]
This seems to have been fixed by https://github.com/dotnet/aspnetcore/commit/297c82f7a428816dc5529e3802e231765d60c7e2. I haven't see a failure of this type since that change has been merged.
