### ISSUE TITLE
Test Failure: Publish_WithBuildReferencesDisabled_CopiesStaticWebAssetsToDestinationFolder

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#22333]
https://dev.azure.com/dnceng/public/_build/results?buildId=662226&view=ms.vss-test-web.build-test-results-tab&runId=20531226&resultId=100126&paneView=debug

<details>
<summary>Error</summary>

```
System.TimeoutException : command '$F:\workspace\_work\1\s\.dotnet\dotnet.exe msbuild /nr:false /bl /p:RunningAsTest=true /p:MicrosoftNETCoreApp50PackageVersion=5.0.0-preview.6.20271.10 /p:MicrosoftNetCompilersToolsetPackageVersion=3.7.0-3.20271.4 /p:_RazorBuildServerPipeName="0523e1aa-6609-4862-8761-b91777db50cb" /t:Build /p:Configuration=Release ' timed out after 00:05:00. Output: Microsoft (R) Build Engine version 16.7.0-preview-20257-02+b861333fc for .NET\r\nCopyright (C) Microsoft Corporation. All rights reserved.\r\n\r\nF:\workspace\_work\1\s\.dotnet\sdk\5.0.100-preview.5.20258.4\MSBuild.dll -maxcpucount -verbosity:m /bl /nr:false /p:RunningAsTest=true /p:MicrosoftNETCoreApp50PackageVersion=5.0.0-preview.6.20271.10 /p:MicrosoftNetCompilersToolsetPackageVersion=3.7.0-3.20271.4 /p:_RazorBuildServerPipeName=0523e1aa-6609-4862-8761-b91777db50cb /p:Configuration=Release /t:Build .\AppWithPackageAndP2PReference.csproj\r\n You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview\r\n You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview\r\n
```
</details>

<details>
<summary>Stacktrace</summary>

```
  at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.<>c__DisplayClass1_0.<<RunProcessCoreAsync>g__GetTimeoutForProcess|3>d.MoveNext() in /_/src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildProcessManager.cs:line 154
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.RunProcessAsync(ProjectDirectory project, String arguments, Nullable`1 timeout, MSBuildProcessKind msBuildProcessKind) in /_/src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/MSBuildProcessManager.cs:line 56
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.StaticWebAssetsIntegrationTest.Publish_WithBuildReferencesDisabled_CopiesStaticWebAssetsToDestinationFolder() in /_/src/Razor/test/Microsoft.NET.Sdk.Razor.Test/IntegrationTests/StaticWebAssetsIntegrationTest.cs:line 111
--- End of stack trace from previous location ---
```
</details>

Also of note here is that the test grouping seems to be broken since it reports that test as belonging to `$(AgentOsName)-$(BuildConfiguration)-xunit_17`

Assigning to @NTaylorMullen just to triage.

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg did you intend to quarantine this test instead?

**Comment by ryanbrandenburg** [comment]
For whatever reason the Quarantine attribute is not available in any of the tooling projects as far as I I tell. Quarantine would certainly have been preferable if available.

**Comment by NTaylorMullen** [comment]
This test now exists in aspnetcore actually 😄 

/cc @javiercn

**Comment by javiercn** [comment]
I don't think this applies anymore
