### ISSUE TITLE
[2.1] Publish failure in React-based templates on macOS

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#22374]
**Steps to reproduce**

1. Checkout and build `release/2.1`
2. Create a new React template: `dotnet new react -o TestReact`
3. `dotnet run` should work.
4. `dotnet publish` fails with the following stacktrace.

<details>
 <summary>Expand for stack trace</summary>
<pre>
 node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@14.3.0 (node-v83 ABI) (falling back to source compile with node-gyp) 
    SOLINK_MODULE(target) Release/.node
    SOLINK_MODULE(target) Release/.node
    CXX(target) Release/obj.target/fse/fsevents.o
    CXX(target) Release/obj.target/fse/fsevents.o
../fsevents.cc(50,32): error G2827E621: no template named 'Handle' in namespace 'v8' [/Users/captainsafia/test-react/test-react.csproj]
  Failed to execute '/usr/local/Cellar/node/14.3.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/captainsafia/test-react/ClientApp/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64/fse.node --module_name=fse --module_path=/Users/captainsafia/test-react/ClientApp/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64' (1)
      static void Initialize(v8::Handle<v8::Object> exports);
                             ~~~~^
  In file included from ../fsevents.cc:84:
../src/constants.cc(89,11): error GBDC4327C: no matching member function for call to 'Set' [/Users/captainsafia/test-react/test-react.csproj]
    object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagNone").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagNone));
    ~~~~~~~~^~~
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3639:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                      ^
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3642:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                      ^
  In file included from ../fsevents.cc:84:
../src/constants.cc(90,11): error GBDC4327C: no matching member function for call to 'Set' [/Users/captainsafia/test-react/test-react.csproj]
    object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagMustScanSubDirs").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagMustScanSubDirs));
    ~~~~~~~~^~~
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3639:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                      ^
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3642:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                      ^
  In file included from ../fsevents.cc:84:
../src/constants.cc(91,11): error GBDC4327C: no matching member function for call to 'Set' [/Users/captainsafia/test-react/test-react.csproj]
    object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagUserDropped").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagUserDropped));
    ~~~~~~~~^~~
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3639:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                      ^
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3642:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                      ^
  In file included from ../fsevents.cc:84:
../src/constants.cc(92,11): error GBDC4327C: no matching member function for call to 'Set' [/Users/captainsafia/test-react/test-react.csproj]
    object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagKernelDropped").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagKernelDropped));
    ~~~~~~~~^~~
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3639:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                      ^
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3642:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                      ^
  In file included from ../fsevents.cc:84:
../src/constants.cc(93,11): error GBDC4327C: no matching member function for call to 'Set' [/Users/captainsafia/test-react/test-react.csproj]
    object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagEventIdsWrapped").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagEventIdsWrapped));
    ~~~~~~~~^~~
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3639:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                      ^
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3642:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                      ^
  In file included from ../fsevents.cc:84:
../src/constants.cc(94,11): error GBDC4327C: no matching member function for call to 'Set' [/Users/captainsafia/test-react/test-react.csproj]
    object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagHistoryDone").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagHistoryDone));
    ~~~~~~~~^~~
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3639:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                      ^
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3642:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                      ^
  In file included from ../fsevents.cc:84:
../src/constants.cc(95,11): error GBDC4327C: no matching member function for call to 'Set' [/Users/captainsafia/test-react/test-react.csproj]
    object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagRootChanged").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagRootChanged));
    ~~~~~~~~^~~
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3639:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                      ^
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3642:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                      ^
  In file included from ../fsevents.cc:84:
../src/constants.cc(96,11): error GBDC4327C: no matching member function for call to 'Set' [/Users/captainsafia/test-react/test-react.csproj]
    object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagMount").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagMount));
    ~~~~~~~~^~~
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3639:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                      ^
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3642:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                      ^
  In file included from ../fsevents.cc:84:
../src/constants.cc(97,11): error GBDC4327C: no matching member function for call to 'Set' [/Users/captainsafia/test-react/test-react.csproj]
    object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagUnmount").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagUnmount));
    ~~~~~~~~^~~
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3639:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                      ^
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3642:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                      ^
  In file included from ../fsevents.cc:84:
../src/constants.cc(98,11): error GBDC4327C: no matching member function for call to 'Set' [/Users/captainsafia/test-react/test-react.csproj]
    object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemCreated").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagItemCreated));
    ~~~~~~~~^~~
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3639:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                      ^
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3642:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                      ^
  In file included from ../fsevents.cc:84:
../src/constants.cc(99,11): error GBDC4327C: no matching member function for call to 'Set' [/Users/captainsafia/test-react/test-react.csproj]
    object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemRemoved").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagItemRemoved));
    ~~~~~~~~^~~
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3639:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                      ^
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3642:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                      ^
  In file included from ../fsevents.cc:84:
../src/constants.cc(100,11): error GBDC4327C: no matching member function for call to 'Set' [/Users/captainsafia/test-react/test-react.csproj]
    object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemInodeMetaMod").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagItemInodeMetaMod));
    ~~~~~~~~^~~
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3639:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                      ^
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3642:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                      ^
  In file included from ../fsevents.cc:84:
../src/constants.cc(101,11): error GBDC4327C: no matching member function for call to 'Set' [/Users/captainsafia/test-react/test-react.csproj]
    object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemRenamed").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagItemRenamed));
    ~~~~~~~~^~~
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3639:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                      ^
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3642:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                      ^
  In file included from ../fsevents.cc:84:
../src/constants.cc(102,11): error GBDC4327C: no matching member function for call to 'Set' [/Users/captainsafia/test-react/test-react.csproj]
    object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemModified").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagItemModified));
    ~~~~~~~~^~~
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3639:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                      ^
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3642:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                      ^
  In file included from ../fsevents.cc:84:
../src/constants.cc(103,11): error GBDC4327C: no matching member function for call to 'Set' [/Users/captainsafia/test-react/test-react.csproj]
    object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemFinderInfoMod").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagItemFinderInfoMod));
    ~~~~~~~~^~~
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3639:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                      ^
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3642:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                      ^
  In file included from ../fsevents.cc:84:
../src/constants.cc(104,11): error GBDC4327C: no matching member function for call to 'Set' [/Users/captainsafia/test-react/test-react.csproj]
    object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemChangeOwner").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagItemChangeOwner));
    ~~~~~~~~^~~
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3639:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                      ^
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3642:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                      ^
  In file included from ../fsevents.cc:84:
../src/constants.cc(105,11): error GBDC4327C: no matching member function for call to 'Set' [/Users/captainsafia/test-react/test-react.csproj]
    object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemXattrMod").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagItemXattrMod));
    ~~~~~~~~^~~
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3639:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                      ^
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3642:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                      ^
  In file included from ../fsevents.cc:84:
../src/constants.cc(106,11): error GBDC4327C: no matching member function for call to 'Set' [/Users/captainsafia/test-react/test-react.csproj]
    object->Set(Nan::New<v8::String>("kFSEventStreamEventFlagItemIsFile").ToLocalChecked(), Nan::New<v8::Integer>(kFSEventStreamEventFlagItemIsFile));
    ~~~~~~~~^~~
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3639:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                      ^
  /Users/captainsafia/Library/Caches/node-gyp/14.3.0/include/node/v8.h:3642:37: note: candidate function not viable: requires 3 arguments, but 2 were provided
    V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                      ^
EXEC : fatal error : too many errors emitted, stopping now [-ferror-limit=] [/Users/captainsafia/test-react/test-react.csproj]
  20 errors generated.
  make: *** [Release/obj.target/fse/fsevents.o] Error 1
  gyp ERR! build error 
EXEC : gyp ERR! stack error : `make` failed with exit code: 2 [/Users/captainsafia/test-react/test-react.csproj]
  gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
  gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
  gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
  gyp ERR! System Darwin 19.4.0
  gyp ERR! command "/usr/local/Cellar/node/14.3.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/captainsafia/test-react/ClientApp/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/captainsafia/test-react/ClientApp/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64"
  gyp ERR! cwd /Users/captainsafia/test-react/ClientApp/node_modules/fsevents
  gyp ERR! node -v v14.3.0
  gyp ERR! node-gyp -v v5.1.0
  gyp ERR! not ok 
  node-pre-gyp ERR! build error 
EXEC : node-pre-gyp ERR! stack error : Failed to execute '/usr/local/Cellar/node/14.3.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/captainsafia/test-react/ClientApp/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64/fse.node --module_name=fse --module_path=/Users/captainsafia/test-react/ClientApp/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64' (1) [/Users/captainsafia/test-react/test-react.csproj]
  node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/captainsafia/test-react/ClientApp/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
  node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
  node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
  node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
  node-pre-gyp ERR! System Darwin 19.4.0
  node-pre-gyp ERR! command "/usr/local/Cellar/node/14.3.0/bin/node" "/Users/captainsafia/test-react/ClientApp/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
  node-pre-gyp ERR! cwd /Users/captainsafia/test-react/ClientApp/node_modules/fsevents
  node-pre-gyp ERR! node -v v14.3.0
  node-pre-gyp ERR! node-pre-gyp -v v0.6.36
  node-pre-gyp ERR! not ok 
  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 install: `node install`
  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
  
  audited 1293 packages in 10.005s
  ../fsevents.cc:15:10: fatal error: 'src/storage.cc' file not found
  #include "src/storage.cc"
           ^~~~~~~~~~~~~~~~
  1 error generated.
  make: *** [Release/obj.target/fse/fsevents.o] Error 1
  gyp ERR! build error 
EXEC : gyp ERR! stack error : `make` failed with exit code: 2 [/Users/captainsafia/test-react/test-react.csproj]
  gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
  gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
  gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
  gyp ERR! System Darwin 19.4.0
  gyp ERR! command "/usr/local/Cellar/node/14.3.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/captainsafia/test-react/ClientApp/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/captainsafia/test-react/ClientApp/node_modules/fsevents/lib/binding/Release/node-v83-darwin-x64"
  gyp ERR! cwd /Users/captainsafia/test-react/ClientApp/node_modules/fsevents
  gyp ERR! node -v v14.3.0
  gyp ERR! node-gyp -v v5.1.0
  gyp ERR! not ok 
  found 1063 vulnerabilities (411 low, 43 moderate, 607 high, 2 critical)
    run `npm audit fix` to fix them, or `npm audit` for details
/Users/captainsafia/test-react/test-react.csproj(36,5): error MSB3073: The command "npm install" exited with code -1.
</pre>
</details>

Some important things to note: it appears that this issue is particular to running the publish step on a machine with Node v12.

The templates use an older version of a dependency which relies on some APIs in Node that are now deprecated ([ref](https://github.com/fsevents/fsevents/issues/278)).

```
❯ npm ls fsevents
test_react@0.1.0 /Users/captainsafia/test-react/ClientApp
└─┬ react-scripts@1.0.17
  ├── UNMET OPTIONAL DEPENDENCY fsevents@1.1.2 
  └─┬ webpack-dev-server@2.9.4
    └─┬ chokidar@1.7.0
      └── UNMET OPTIONAL DEPENDENCY fsevents@1.1.2 
```

Considering this and some of the outdated dependencies in the template, it might make sense to go ahead and update react-scripts in our templates. The current version of react-scripts is 3.4.1 and our template is on 1.0.17 (see above), which is introduced lots of outdated and insecure dependencies.

**Comment by mkArtakMSFT** [comment]
Is Node 10 what the 2.1 SPA templates work on now?

**Comment by captainsafia** [comment]
Yep. `dotnet publish` works fine on Node v10.20.0.

**Comment by mkArtakMSFT** [comment]
Ok, that's it then. In 2.1 we did support only Node 10. Given the major version bump we never upgrade down-level templates, as that's a riskier change. So it looks like nothing has actually changed here and the templates are in fine state.
This conversation has came up multiple times. And every time we concluded that we will keep things as is. @danroth27 can you please confirm that we should keep things as is (2.1 SPA project templates support now unsupported version of Node only)?

**Comment by captainsafia** [comment]
That makes sense. According to the Node docs, Node v10 is currently under "Maintenance LTS" through April 2021 ([ref](https://nodejs.org/en/about/releases/)), so there's some runaway on this.

**Comment by mkArtakMSFT** [comment]
Sounds like we have no issues here then 👍 Thanks For double-checking, @captainsafia!
Please follow up with the CTI folks to make sure they use the correct version of Node during validation.

**Comment by mkArtakMSFT** [comment]
And close this issue as an `ACK` that you're following up with them, please.

**Comment by captainsafia** [comment]
Done!
