### ISSUE TITLE
WebApplicationFactory and TransactionScopes upgrading to distributed transaction.

### ISSUE THREAD

**Issue by lucasmpr** [dotnet/aspnetcore#22408]
I'm having a totaly weird interaction in WebApplicationFactory and TransactionScopes while doing integration testing and entity framework.  I'm not sure if I should report here or in EntityFrameworkCore repo.

The idea was simple: 

Create a new WebApplicationFactory -> CreateDatabase -> Run Test -> Delete Database

I've done that 200 times, one by one.  But when running two http calls that have TransactionScopes inside them at the same time.  If you run each Test by themselves, they work just fine.

But when they run at the same time,
The longer running one will always throw System.PlatformNotSupportedException: This platform does not support distributed transactions.

After much testing, I've found that the cause was context.Database.EnsureDeleted(). It somehow disconnects every other connection even if its from another WebApplicationFactory Instance and even another database, and when you try to fetch more data, they will try to initiate a Distributed Transaction.

### Describe the bug

context.Database.EnsureDeleted() seems to cause "System.PlatformNotSupportedException: This platform does not support distributed transactions" when running two transactionscopes from two separated instances of WebApplicationFactory. 

I'm not sure if its a TransactionScope bug, an WebApplicationFactory one or a EnsureDeleted one. Or if its the normal behaviour.

### To Reproduce

I've made a minimal repository to illustrate the problem. It will connect to SqlServer create the database, run two http calls and it will fail every time.

Change the ConnectionString in ApiFactory.cs and then run dotnet test or use VS unit test runner.

https://github.com/lucasmpr/TransactionScopeWebApplicationFactory

The full stack is the following:

System.PlatformNotSupportedException: This platform does not support distributed transactions.
   at System.Transactions.Distributed.DistributedTransactionManager.GetDistributedTransactionFromTransmitterPropagationToken(Byte[] propagationToken)
   at System.Transactions.TransactionInterop.GetDistributedTransactionFromTransmitterPropagationToken(Byte[] propagationToken)
   at System.Transactions.TransactionStatePSPEOperation.PSPEPromote(InternalTransaction tx)
   at System.Transactions.TransactionStateDelegatedBase.EnterState(InternalTransaction tx)
   at System.Transactions.EnlistableStates.Promote(InternalTransaction tx)
   at System.Transactions.Transaction.Promote()
   at System.Transactions.TransactionInterop.ConvertToDistributedTransaction(Transaction transaction)
   at System.Transactions.TransactionInterop.GetExportCookie(Transaction transaction, Byte[] whereabouts)
   at Microsoft.Data.SqlClient.SqlInternalConnection.GetTransactionCookie(Transaction transaction, Byte[] whereAbouts)
   at Microsoft.Data.SqlClient.SqlInternalConnection.EnlistNonNull(Transaction tx)
   at Microsoft.Data.SqlClient.SqlInternalConnection.Enlist(Transaction tx)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.Activate(Transaction transaction)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.ActivateConnection(Transaction transaction)
   at Microsoft.Data.ProviderBase.DbConnectionPool.PrepareConnection(DbConnection owningObject, DbConnectionInternal obj, Transaction transaction)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at DB.PostsRepository.Get(Int32 id) in C:\Users\lucas\OneDrive\Documentos\TransactionScopeWebApplicationFactory\DB\PostsRepository.cs:line 27
   at Api.NotHome.dostuff() in C:\Users\lucas\OneDrive\Documentos\TransactionScopeWebApplicationFactory\Api\Controllers\Home.cs:line 80
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

### Further technical details

- ASP.NET Core version -> 3.1

- Include the output of `dotnet --info`

SDK do .NET Core (refletindo qualquer global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Ambiente de runtime:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

I'm using Rider 2020.1 but the problem is reproductible here with dotnet test too.

**Comment by SayusiAndo** [comment]
Just to see if the database itself the problem I'd like to suggest that try out with SQLite or Postgres.

**Comment by lucasmpr** [comment]
I've just tested Postgres without error.

SQLite doesn't support TransactionScope, so I dont think the test is relevant.

I've created a workaround for my use case by dropping the database with DROP DATABASE. No errors then.

**Comment by javiercn** [comment]
@lucasmpr thanks for contacting us.

I think this is an issue with the way you are writing the test in the context of the database. I'm not sure what EF does internally, but I would suggest that if you want to create/delete the database on a per test basis, use different databases all-together.

For the specific mechanics you'll have to ask the Entity Framework team, but I imagine their guidance would be to not drop the database after every test and just cleanup at the end of the test run, and likely to use an in-memory version for database tests.

**Comment by lucasmpr** [comment]
@javiercn Thanks for the response.

For my real use case I'm not dropping the database for every test. I have a ClassFixture that after all tests run drops the database so I dont have to keep cleaning them manually. Every test class with multiple tests creates a WebApplicationFactory and a database.

The objective here is really to test the database calls, so I dont think I can change the database and still get the same confidence level.

Seems like EnsureDeleted Clears the pool of connections and that's the problem. It might be spanning between two WebApplications. As It seems to be an EntityFramework problem I'll report there.

Thank you.

Lucas
