### ISSUE TITLE
Auto generate data protection keys and persist to redis

### ISSUE THREAD

**Issue by fatagun** [dotnet/aspnetcore#22554]
I have the following code that I expect it to generate data protection keys and persist to redis. 
```
            services.AddDataProtection().AddKeyManagementOptions(options => {
                options.AutoGenerateKeys = true;
            })
            .SetApplicationName("My")
            .PersistKeysToStackExchangeRedis(() =>
                    {
                        var redisdatabase = Resolve<IRedisDatabaseProvider>();
                        return redisdatabase.GetDatabase();
                    }, "My.DataProtectionKeys");

```

It does not generate and persist keys into redis. 

However, when I manually insert keys to redis, it does read from it and works well.

This code comes before `services.AddMvc()`.

Any ideas? why it is not persisting keys to redis list?

**Comment by blowdart** [comment]
When are you expecting the keys to be generated?

By default it should create them the first time data protection is needed, and that's not the first request, it will be the first request which loads a page with a form than has a CSRF token in it, or if a cookie authenticated request comes along.

You shouldn't need to set key management options at all.

**Comment by fatagun** [comment]
Thanks for your response. 
It does not generate and persist to redis when I browse to a page that has a form with CSRF token. 

below is the exception :

```
2020-06-05 17:26:52.909 +03:00 [EROR] [Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware] (Cnd.Sandbox.Mvc.Playground) | (Firats-MacBook-Pro) | (84347) | (22) | An unhandled exception has occurred while executing the request. | System.Security.Cryptography.CryptographicException: An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 's')
   at System.IO.StringReader..ctor(String s)
   at System.Xml.Linq.XElement.Parse(String text, LoadOptions options)
   at Microsoft.AspNetCore.DataProtection.StackExchangeRedis.RedisXmlRepository.GetAllElementsCore()+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.DataProtection.StackExchangeRedis.RedisXmlRepository.GetAllElements()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow, Boolean forceRefresh)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRing()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Serialize(AntiforgeryToken token)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.Serialize(IAntiforgeryFeature antiforgeryFeature)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetAndStoreTokens(HttpContext httpContext)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.AntiforgeryExtensions.GetHtml(IAntiforgery antiforgery, HttpContext httpContext)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.DefaultHtmlGenerator.GenerateAntiforgery(ViewContext viewContext)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.AntiForgeryToken()
   at AspNetCore.Views_Home_EditWithEvents.<ExecuteAsync>b__11_1() in /Users/firat/Projects/cnd/sandbox/mvc/Cnd.Sandbox.Mvc.Playground/Views/Home/EditWithEvents.cshtml:line 6
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.GetChildContentAsync(Boolean useCachedResult, HtmlEncoder encoder)
   at Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at AspNetCore.Views_Home_EditWithEvents.ExecuteAsync() in /Users/firat/Projects/cnd/sandbox/mvc/Cnd.Sandbox.Mvc.Playground/Views/Home/EditWithEvents.cshtml:line 3
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.CspMiddleware.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at App.Metrics.AspNetCore.Tracking.Middleware.ApdexMiddleware.Invoke(HttpContext context)
   at App.Metrics.AspNetCore.Tracking.Middleware.PerRequestTimerMiddleware.Invoke(HttpContext context)
   at App.Metrics.AspNetCore.Tracking.Middleware.RequestTimerMiddleware.Invoke(HttpContext context)
   at App.Metrics.AspNetCore.Tracking.Middleware.ErrorRequestMeterMiddleware.Invoke(HttpContext context)
   at App.Metrics.AspNetCore.Tracking.Middleware.ActiveRequestCounterEndpointMiddleware.Invoke(HttpContext context)
   at Cnd.Web.Common.HostingInformationMiddleware.Invoke(HttpContext context, IHostEnvironment hostingEnvironment) in /Users/firat/Projects/cnd/src/web/common/Cnd.Web.Common/Middlewares/HostInformationMiddleware.cs:line 32
   at Cnd.Web.Common.CorrelationIdMiddleware.Invoke(HttpContext context, ICorrelationIdAccessor correlationIdAccessor) in /Users/firat/Projects/cnd/src/web/common/Cnd.Web.Common/Middlewares/CorrelationIdMiddleware.cs:line 31
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
 | {"EventId": {"Id": 1, "Name": "UnhandledException"}, "RequestId": "0HM09BHPKUFJA:00000008", "RequestPath": "/Home/EditWithEvents", "SpanId": "|18ee42ab-40efb2accb880281.", "TraceId": "18ee42ab-40efb2accb880281", "ParentId": "", "ConnectionId": "0HM09BHPKUFJA", "ExceptionDetail": {"Type": "System.Security.Cryptography.CryptographicException", "HResult": -2146233087, "Message": "An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information.", "Source": "Microsoft.AspNetCore.DataProtection", "InnerException": {"Type": "System.ArgumentNullException", "HResult": -2147467261, "Message": "Value cannot be null. (Parameter 's')", "Source": "System.Runtime.Extensions", "ParamName": "s"}}} 
2020-06-05 17:26:52.920 +03:00 [INFO] [Sentry.ISentryClient] (Cnd.Sandbox.Mvc.Playground) | (Firats-MacBook-Pro) | (84347) | (22) | Capturing event. |  | {"RequestId": "0HM09BHPKUFJA:00000008", "RequestPath": "/Home/EditWithEvents", "SpanId": "|18ee42ab-40efb2accb880281.", "TraceId": "18ee42ab-40efb2accb880281", "ParentId": "", "ConnectionId": "0HM09BHPKUFJA"} 

```

**Comment by blowdart** [comment]
I agree, it should do. @BrennanConroy you touched it last :)

**Comment by BrennanConroy** [comment]
Before storing a key in Redis it will try to find existing keys in Redis. That part is failing with the `ArgumentNullException`.

Do you already have data stored in Redis under your key?

Or maybe we have an issue with that logic where it gets empty strings and we need to protect against that.

**Comment by fatagun** [comment]
Here is what I tried. 

If I store key and value (XML definition) in redis, it works properly.

If I create just the keys but not the XML values, ie: empty redis list. It doesn't work. Like you mentioned, XML parser fails. 

If I don't store anything, it fails.

I would expect it create to the values of corresponding key and append it to redis list.

Am I expecting wrong behaviour?

**Comment by BrennanConroy** [comment]
> If I create just the keys but not the XML values, ie: empty redis list. It doesn't work. Like you mentioned, XML parser fails.

I can sort of repro this one, where if you put "" or nil for a value in the key it will fail.

> If I don't store anything, it fails.

This is the really odd one though and I can't repro it. What are you using for your Redis server and what is `Resolve<IRedisDatabaseProvider>();`?

**Comment by fatagun** [comment]
`Resolve<IRedisDatabaseProvider>();` this is just the way I get redis connection. and that works. Cause I am able to read it once the keys are in place. It is connection multiplexor for redis, just the way i wire it. I might need to look into this one, if it is using `list` functionality, i will need to add it to this wrapper.

**Comment by BrennanConroy** [comment]
🤷 I have no idea how you're getting the `ArgumentNullException`.

@blowdart Should we consider ignoring null or empty strings from Redis?

**Comment by amcasey** [comment]
I'm going to close this issue.  Please post additional feedback in #36157 so we can track it centrally and don't drop any.
