### ISSUE TITLE
Skipped Flaky Test Microsoft.VisualStudio.LiveShare.Razor.Guest.RazorGuestInitializationServiceTest.CreateServiceAsync_SessionDispose_CancelsListRootsToken

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#23118]
Build: https://github.com/dotnet/aspnetcore-tooling/pull/2066/checks?check_run_id=786121831

```
 at Microsoft.VisualStudio.LiveShare.Razor.Guest.RazorGuestInitializationServiceTest.<>c__DisplayClass5_1.<CreateServiceAsync_SessionDispose_CancelsListRootsToken>b__2() in /_/src/Razor/test/Microsoft.VisualStudio.LiveShare.Razor.Test/Guest/RazorGuestInitializationServiceTest.cs:line 56
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LiveShare.Razor.Guest.RazorGuestInitializationService.<EnsureViewImportsCopiedAsync>d__5.MoveNext() in /_/src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Guest/RazorGuestInitializationService.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LiveShare.Razor.Guest.RazorGuestInitializationServiceTest.<CreateServiceAsync_SessionDispose_CancelsListRootsToken>d__5.MoveNext() in /_/src/Razor/test/Microsoft.VisualStudio.LiveShare.Razor.Test/Guest/RazorGuestInitializationServiceTest.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by mkArtakMSFT** [comment]
Given that the code will be removed soon - we should simply remove the test.

**Comment by TanayParikh** [comment]
> Given that the code will be removed soon - we should simply remove the test.

A re-run of failed tasks resolved the issue, and the test hasn't failed since. Closing out this issue, but will be sure to remove should it fail again.
