### ISSUE TITLE
Could not install any package from here in dot net core 5.0

### ISSUE THREAD

**Issue by HalfLegend** [dotnet/aspnetcore#23251]
<DefaultNetCoreTargetFramework>net5.0</DefaultNetCoreTargetFramework>

### Describe the bug
Could not install any package from here in dot net core 5.0

### To Reproduce
Just start a new asp.net app using dot net core v5.0.0
and install nuget package.  microsoft.aspnetcore.spaservices.extensions 

Error:
```
Package Microsoft.AspNetCore.SpaServices.Extensions 5.0.0-preview.5.20279.2 is not compatible with netcoreapp5.0 (.NETCoreApp,Version=v5.0). Package Microsoft.AspNetCore.SpaServices.Extensions 5.0.0-preview.5.20279.2 supports: net50 (.NETFramework,Version=v5.0)
Package restore failed. Rolling back package changes for 'NetCoreServer'.
Package Microsoft.AspNetCore.SpaServices.Extensions 5.0.0-preview.5.20279.2 is not compatible with netcoreapp5.0 (.NETCoreApp,Version=v5.0). Package Microsoft.AspNetCore.SpaServices.Extensions 5.0.0-preview.5.20279.2 supports: net50 (.NETFramework,Version=v5.0)

NuGet.PackageManagement.PackageReferenceRollbackException: Package restore failed. Rolling back package changes for 'NetCoreServer'.
   at NuGet.PackageManagement.NuGetPackageManager.ExecuteBuildIntegratedProjectActionsAsync(BuildIntegratedNuGetProject buildIntegratedProject, IEnumerable`1 nuGetProjectActions, INuGetProjectContext nuGetProjectContext, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.ExecuteNuGetProjectActionsAsync(NuGetProject nuGetProject, IEnumerable`1 nuGetProjectActions, INuGetProjectContext nuGetProjectContext, PackageDownloadContext downloadContext, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.InstallPackageAsync(NuGetProject nuGetProject, PackageIdentity packageIdentity, ResolutionContext resolutionContext, INuGetProjectContext nuGetProjectContext, PackageDownloadContext downloadContext, IEnumerable`1 primarySources, IEnumerable`1 secondarySources, CancellationToken token)
   at NuGet.PackageManagement.NuGetPackageManager.InstallPackageAsync(NuGetProject nuGetProject, PackageIdentity packageIdentity, ResolutionContext resolutionContext, INuGetProjectContext nuGetProjectContext, IEnumerable`1 primarySources, IEnumerable`1 secondarySources, CancellationToken token)
   at JetBrains.ProjectModel.NuGet.Operations.NuGetInstallOperation.<>c__DisplayClass5_0.<<InstallAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at JetBrains.ProjectModel.NuGet.Operations.NuGetInstallOperation.InstallInternal(IProject project, String packageId, String packgeUserStr, NuGetFeedContext feedContext, Int32 nestedLevel, NuGetNotificationMode mode, NuGetOperationReporter reporter, Func`3 nativeInstall, NuGetProject givenNuGetProject)

Package Microsoft.AspNetCore.SpaServices.Extensions 5.0.0-preview.5.20279.2 is not compatible with netcoreapp5.0 (.NETCoreApp,Version=v5.0). Package Microsoft.AspNetCore.SpaServices.Extensions 5.0.0-preview.5.20279.2 supports: net50 (.NETFramework,Version=v5.0)
@ Installing Microsoft.AspNetCore.SpaServices.Extensions in NetCoreServer finished (9.386 sec)
[Notification][Install] Install failed (project: NetCoreServer, package: Microsoft.AspNetCore.SpaServices.Extensions v5.0.0-preview.5.20279.2)
Package restore failed. Rolling back package changes for 'NetCoreServer'.
Package Microsoft.AspNetCore.SpaServices.Extensions 5.0.0-preview.5.20279.2 is not compatible with netcoreapp5.0 (.NETCoreApp,Version=v5.0). Package Microsoft.AspNetCore.SpaServices.Extensions 5.0.0-preview.5.20279.2 supports: net50 (.NETFramework,Version=v5.0)
```

I am using netcoreapp5.0 (.NETCoreApp,Version=v5.0)
And why  net50 (.NETFramework,Version=v5.0) ?

I also tried other packages from here, they all could not be installed correctly.
Other packages could be installed correctly.
For example: microsoft.entityframeworkcore.sqlite: 5.0.0-preview.5.20278.2

### Cause
In nuget package
microsoft.aspnetcore.spaservices.extensions.nuspec
```
    <dependencies>
      <group targetFramework=".NETCoreApp5.0">
        <dependency id="Microsoft.AspNetCore.SpaServices" version="5.0.0-preview.5.20279.2" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Extensions.FileProviders.Physical" version="5.0.0-preview.5.20278.1" exclude="Build,Analyzers" />
      </group>
    </dependencies>
    <frameworkReferences>
      <group targetFramework=".NETFramework5.0">
        <frameworkReference name="Microsoft.AspNetCore.App" />
      </group>
    </frameworkReferences>
```
The dependencies are right: .NETCoreApp5.0
But why ".NETFramework5.0" in frameworkReferences?

I changed ".NETFramework5.0" to  .NETCoreApp5.0.  and it works fine immediatelly.

### Exceptions (if any)
In
https://github.com/dotnet/aspnetcore/blob/master/Directory.Build.props

```
    <DefaultNetCoreTargetFramework>net5.0</DefaultNetCoreTargetFramework>
```
is wrong.

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.5.20279.10
 Commit:    8139f1b74e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.100-preview.5.20279.10/

Host (useful for support):
  Version: 5.0.0-preview.5.20278.1
  Commit:  4ae4e2fe08

IDE: not important.  I could reproduce the problem without an IDE.
The OS matters.

**Comment by pranavkm** [comment]
The TFM was changed to net5.0 in an earlier release: https://devblogs.microsoft.com/dotnet/announcing-net-5-preview-4-and-our-journey-to-one-net/#net-50-target-framework.
