### ISSUE TITLE
Error with external login with OpenId

### ISSUE THREAD

**Issue by PauloSRH** [dotnet/aspnetcore#23292]
**Describe the bug**
When using OpenId connect to login through the Azure AD for Office 365, OpenIdConnectAuthenticationHandler throws an exception that the message.State is null or empty.

I tried several solutions online such as [#18528](https://github.com/dotnet/aspnetcore/issues/18528#issuecomment-577901525) but none fixed the exception.

I have a separate module for authentication with the following startup.
**Startup.cs**
``` c#
public void ConfigureServices(IServiceCollection services)
        {
            services.AddMediatR(typeof(Startup).Assembly);
            services.Configure<CookiePolicyOptions>(options =>
            {
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
            })
                .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme, options => options.LoginPath = "/Auth/Account/ExternalLogin")
                .AddOpenIdConnect(OpenIdConnectDefaults.AuthenticationScheme, "Microsoft O365", options =>
                 {
                     options.ClientId = "clientId";
                     options.Authority = "https://login.microsoftonline.com/common";
                     options.Scope.Clear();
                     options.Scope.Add("openid");
                     options.Scope.Add("profile");
                     options.TokenValidationParameters = new TokenValidationParameters
                     {
                         ValidateIssuer = false
                     };
                     options.CallbackPath = new PathString("/Auth/Account/ExternalLoginCallback");
                     options.ClientSecret = "clientSecret";
                     options.ResponseType = OpenIdConnectResponseType.Code;
                     options.Events = new OpenIdConnectEvents()
                     {
                         OnRedirectToIdentityProvider = OnRedirectToIdentityProviderAsync,
                         OnTokenValidated = OnTokenValidatedAsync,
                         OnRemoteFailure = OnRemoteFailureAsync,
                     };
                 });
            services.AddAuthorization();
        }
```

**Exception**
``` c#
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: OpenIdConnectAuthenticationHandler: message.State is null or empty.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at OrchardCore.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext() in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Diagnostics\DiagnosticsStartupFilter.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantRouterMiddleware.cs:line 63
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 206
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs:line 59
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**AccountController.cs**
``` c#
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult ExternalLogin(string provider, string returnUrl = null)
        {
            // Request a redirect to the external login provider.
            var redirectUrl = Url.Action(nameof(ExternalLoginCallback), "Account", new { returnUrl });
            var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl);
            return Challenge(properties, provider);
        }


        [AllowAnonymous]
        public ActionResult ExternalLoginCallback(string returnUrl = "/")
        {
            return RedirectToLocal(returnUrl);
        }
```

After executing all the openId Events, OnRemoteFailure is called with the exception message.State is null. OnRedirectToIdentityProviderAsync and OnTokenValidatedAsync are executed sucessfully.

If anyone has implemented this in .net core, and could provide a example functional code, I would appreciated. If some more code is need, I can provided it. I recently just started with .net core, thanks for the help and comprehension.

**Further technical details**
- ASP.NET Core version 3.1

**Comment by blowdart** [comment]
What browser is this happening in? It's likely a same site attribute problem.

Also is there a reason you want to go the raw oauth route and not the AAD specific helpers?

**Comment by PauloSRH** [comment]
I am using Chrome.
I'm using the raw oath, because besides this module, I am using Orchard Core framework, which uses AddAzureAD, for another feature causing a problem.

I'm still new in .net core and orchard Core. If I misunderstood your question please let me know. Thank you.

**Comment by blowdart** [comment]
No you understood :) If it works in IE, it's probably SameSite.

I'd like you to go through adding the [SameSite](http://aka.ms/samesitecore) updates if you can, just to rule that out, and also prepare yourself for older browsers anyway.

**Comment by blowdart** [comment]
Also you cannot have the callback path pointing to a controller; it must be a unique path which is then handled by the controller.

So either remove the options.CallbackPath set or try something like

`options.CallbackPath = new PathString("/Signin-OIDC");`

**Comment by PauloSRH** [comment]
> Also you cannot have the callback path pointing to a controller; it must be a unique path which is then handled by the controller.
> 
> So either remove the options.CallbackPath set or try something like
> 
> `options.CallbackPath = new PathString("/Signin-OIDC");`

This works! Using this callback, or just leaving the default callback "/signin-oid", is the solution.
