### ISSUE TITLE
Token lifetime validation doesn´t print System.DateTime to Log

### ISSUE THREAD

**Issue by MarcoK80** [dotnet/aspnetcore#23302]
Token lifetime validation doesn´t print System.DateTime to Log

Used framework: AspnetCore 3.1

Expected: The ValidTo and Current time are properly filled.

Current: Only System.DateTime is printed out

info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[1]
      Failed to validate the token.
Microsoft.IdentityModel.Tokens.SecurityTokenExpiredException: IDX10223: Lifetime validation failed. The token is expired. ValidTo: 'System.DateTime', Current time: 'System.DateTime'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateLifetime(Nullable`1 notBefore, Nullable`1 expires, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateLifetime(Nullable`1 notBefore, Nullable`1 expires, JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()

![image](https://user-images.githubusercontent.com/43368445/85580404-fcdeb180-b63b-11ea-8430-55091bfa7af3.png)

**Comment by blowdart** [comment]
That message isn't coming from us, but the library we use. 

Please file an issue over at https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet
