### ISSUE TITLE
Investigate Templates.Test.MvcTemplateTest.MvcTemplate_NoAuthFSharp malloc failure

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#23392]
This is more for tracking reasons, but there was a failure on Fedora28 where running this template test hit a malloc_consolidate error. This seems more likely like a runtime issue. More info [here](https://dev.azure.com/dnceng/public/_build/results?buildId=706037&view=ms.vss-test-web.build-test-results-tab&runId=21867228&resultId=121642&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab) and [here](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-heads-master-a556c3983ca341fd9a/ProjectTemplates.Tests--net5.0/console.1702c104.log?sv=2019-02-02&se=2020-07-16T12%3A53%3A08Z&sr=c&sp=rl&sig=fLIBw1PBfLPcNzEikmqYhayo3DQTmEX5Gj0aynszNTA%3D)

```
 X Templates.Test.MvcTemplateTest.MvcTemplate_NoAuthFSharp [17s 213ms]
  Error Message:
   Process exited with code 134
StdErr: malloc_consolidate(): invalid chunk size

StdOut: Templates                                         Short Name         Language          Tags                  
--------------------------------------------      -------------      ------------      ----------------------
Console Application                               console            [C#], F#, VB      Common/Console        
Class library                                     classlib           [C#], F#, VB      Common/Library        
Worker Service                                    worker             [C#]              Common/Worker/Web     
Unit Test Project                                 mstest             [C#], F#, VB      Test/MSTest           
NUnit 3 Test Project                              nunit              [C#], F#, VB      Test/NUnit            
NUnit 3 Test Item                                 nunit-test         [C#], F#, VB      Test/NUnit            
xUnit Test Project                                xunit              [C#], F#, VB      Test/xUnit            
Blazor Server App                                 blazorserver       [C#]              Web/Blazor            
Blazor WebAssembly App                            blazorwasm         [C#]              Web/Blazor/WebAssembly
ASP.NET Core Empty                                web                [C#], F#          Web/Empty             
ASP.NET Core Web App (Model-View-Controller)      mvc                [C#], F#          Web/MVC               
ASP.NET Core Web App                              webapp             [C#]              Web/MVC/Razor Pages   
Razor Class Library                               razorclasslib      [C#]              Web/Razor/Library     
ASP.NET Core Web API                              webapi             [C#], F#          Web/WebAPI            
ASP.NET Core gRPC Service                         grpc               [C#]              Web/gRPC              
TypeScript file                                   tsfile                               Web/Script            
LESS Style Sheet                                  less                                 Web/Style             
SCSS Style Sheet (SASS)                           scss                                 Web/Style             

Examples:
    dotnet new mvc --auth Individual
    dotnet new --help

Expected: True
Actual:   False
  Stack Trace:
     at Templates.Test.Helpers.TemplatePackageInstaller.InstallTemplatePackages(ITestOutputHelper output) in /_/src/ProjectTemplates/Shared/TemplatePackageInstaller.cs:line 149
   at Templates.Test.Helpers.TemplatePackageInstaller.EnsureTemplatingEngineInitializedAsync(ITestOutputHelper output) in /_/src/ProjectTemplates/Shared/TemplatePackageInstaller.cs:line 61
   at Templates.Test.Helpers.ProjectFactoryFixture.GetOrCreateProject(String projectKey, ITestOutputHelper output) in /_/src/ProjectTemplates/Shared/ProjectFactoryFixture.cs:line 36
   at Templates.Test.MvcTemplateTest.MvcTemplateCore(String languageOverride) in /_/src/ProjectTemplates/test/MvcTemplateTest.cs:line 37
   at Templates.Test.MvcTemplateTest.MvcTemplate_NoAuthFSharp() in /_/src/ProjectTemplates/test/MvcTemplateTest.cs:line 29
--- End of stack trace from previous location ---
  Standard Output Messages:
 ==> /root/helix/work/workitem/.dotnet28079/dotnet new --uninstall --help --debug:custom-hive "Hives/.templateEngine" [/root/helix/work/workitem/]
 Getting ready...
 Template Instantiation Commands for .NET Core CLI
 
 Currently installed items:
   Microsoft.DotNet.Web.ProjectTemplates.5.0
     Details:
       NuGetPackageId: Microsoft.DotNet.Web.ProjectTemplates.5.0
       Version: 5.0.0-preview.6.20309.8
       Author: Microsoft
     Templates:
       Blazor Server App (blazorserver) C#
       Blazor WebAssembly App (blazorwasm) C#
       ASP.NET Core Empty (web) C#
       ASP.NET Core Empty (web) F#
       ASP.NET Core gRPC Service (grpc) C#
       Razor Class Library (razorclasslib) C#
       ASP.NET Core Web App (webapp) C#
       ASP.NET Core Web App (Model-View-Controller) (mvc) C#
       ASP.NET Core Web App (Model-View-Controller) (mvc) F#
       ASP.NET Core Web API (webapi) C#
       ASP.NET Core Web API (webapi) F#
       Worker Service (worker) C#
     Uninstall Command:
       dotnet new -u Microsoft.DotNet.Web.ProjectTemplates.5.0
 
   NUnit3.DotNetNew.Template
     Details:
       NuGetPackageId: NUnit3.DotNetNew.Template
       Version: 1.8.1
       Author: akharlov
     Templates:
       NUnit 3 Test Project (nunit) C#
       NUnit 3 Test Item (nunit-test) C#
       NUnit 3 Test Project (nunit) F#
       NUnit 3 Test Item (nunit-test) F#
       NUnit 3 Test Project (nunit) VB
       NUnit 3 Test Item (nunit-test) VB
     Uninstall Command:
       dotnet new -u NUnit3.DotNetNew.Template
 
   Microsoft.DotNet.Common.ItemTemplates
     Details:
       NuGetPackageId: Microsoft.DotNet.Common.ItemTemplates
       Version: 5.0.0-preview.6.20309.2
       Author: Microsoft
     Templates:
       dotnet gitignore file (gitignore)
       global.json file (globaljson)
       NuGet Config (nugetconfig)
       Solution File (sln)
       Dotnet local tool manifest file (tool-manifest)
       Web Config (webconfig)
     Uninstall Command:
       dotnet new -u Microsoft.DotNet.Common.ItemTemplates
 
   Microsoft.DotNet.Test.ProjectTemplates.5.0
     Details:
       NuGetPackageId: Microsoft.DotNet.Test.ProjectTemplates.5.0
       Version: 1.0.2-beta4.20303.2
       Author: Microsoft
     Templates:
       Unit Test Project (mstest) C#
       Unit Test Project (mstest) F#
       Unit Test Project (mstest) VB
       xUnit Test Project (xunit) C#
       xUnit Test Project (xunit) F#
       xUnit Test Project (xunit) VB
     Uninstall Command:
       dotnet new -u Microsoft.DotNet.Test.ProjectTemplates.5.0
 
   Microsoft.DotNet.Common.ProjectTemplates.5.0
     Details:
       NuGetPackageId: Microsoft.DotNet.Common.ProjectTemplates.5.0
       Version: 5.0.0-preview.6.20309.2
       Author: Microsoft
     Templates:
       Class library (classlib) C#
       Class library (classlib) F#
       Class library (classlib) VB
       Console Application (console) C#
       Console Application (console) F#
       Console Application (console) VB
     Uninstall Command:
       dotnet new -u Microsoft.DotNet.Common.ProjectTemplates.5.0
 
   Microsoft.DotNet.Web.ItemTemplates
     Details:
       NuGetPackageId: Microsoft.DotNet.Web.ItemTemplates
       Version: 5.0.0-preview.6.20309.8
       Author: Microsoft
     Templates:
       Protocol Buffer File (proto) 
       Razor Component (razorcomponent) C#
       Razor Page (page) C#
       MVC ViewImports (viewimports) C#
       MVC ViewStart (viewstart) C#
     Uninstall Command:
       dotnet new -u Microsoft.DotNet.Web.ItemTemplates
 
   Microsoft.DotNet.Web.Spa.ProjectTemplates.5.0
     Details:
       NuGetPackageId: Microsoft.DotNet.Web.Spa.ProjectTemplates.5.0
       Version: 5.0.0-preview.6.20309.8
       Author: Microsoft
     Templates:
       ASP.NET Core with Angular (angular) C#
       ASP.NET Core with React.js (react) C#
       ASP.NET Core with React.js and Redux (reactredux) C#
     Uninstall Command:
       dotnet new -u Microsoft.DotNet.Web.Spa.ProjectTemplates.5.0
```

**Comment by javiercn** [comment]
This feels like the templating engine crashing, I'm not sure if they are using some unsafe code or if it is the .NET Core runtime crashing.

@mkArtakMSFT can you route this to the appropriate folks? (this would be an issue in dotnet new)
