### ISSUE TITLE
Investigate dotnet-watch failures

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#23394]
https://dev.azure.com/dnceng/public/_build/results?buildId=706059&view=ms.vss-test-web.build-test-results-tab&runId=21867388&resultId=121648&paneView=debug

```
System.TimeoutException : The operation at /_/src/Tools/dotnet-watch/test/ProgramTests.cs:43 timed out after reaching the limit of 30000ms.

   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Testing/src/TaskExtensions.cs:line 33
   at Microsoft.DotNet.Watcher.Tools.Tests.ProgramTests.ConsoleCancelKey() in /_/src/Tools/dotnet-watch/test/ProgramTests.cs:line 43
--- End of stack trace from previous location ---
```

**Comment by BrennanConroy** [comment]
There is a core dump file for this failure. I'm assuming it is for the process launched by dotnet-watch.

The dump file doesn't show any obvious reason for a crash, all threads show stop reason as "SIGSTOP" which is generally graceful.

**Comment by pranavkm** [comment]
We haven't noticed these failures since migrating dotnet-watch to the SDK.

**Comment by MiYanni** [comment]
CC @mkArtakMSFT for visibility
