### ISSUE TITLE
Flaky test: Publish_HostedApp_VisualStudio_WithSatelliteAssemblies and Publish_UpdatesFilesWhenSourcesChange

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#23397]
https://dev.azure.com/dnceng/public/_build/results?buildId=706059&view=results

Lots of dotnet dumps in the artifacts.

Publish_HostedApp_VisualStudio_WithSatelliteAssemblies
```
Publish_HostedApp_VisualStudio_WithSatelliteAssemblies [FAIL]
      System.TimeoutException : command '$F:\workspace\_work\1\s\.dotnet\dotnet.exe msbuild /nr:false /bl /p:RunningAsTest=true /p:MicrosoftNETCoreAppRuntimeVersion=5.0.0-preview.8.20325.1 /p:MicrosoftNetCompilersToolsetPackageVersion=3.7.0-4.20319.6 /p:RazorSdkDirectoryRoot=F:\workspace\_work\1\s\artifacts\bin\Microsoft.NET.Sdk.Razor\Release\sdk-output\ /p:RepoRoot=F:\workspace\_work\1\s\ /p:Configuration=Release /t:Build /restore' timed out after 00:05:00. Output: Microsoft (R) Build Engine version 16.7.0-preview-20309-02+d6862eb21 for .NET
      Copyright (C) Microsoft Corporation. All rights reserved.
      
      F:\workspace\_work\1\s\.dotnet\sdk\5.0.100-preview.6.20310.4\MSBuild.dll -maxcpucount -verbosity:m /bl /nr:false /p:RunningAsTest=true /p:MicrosoftNETCoreAppRuntimeVersion=5.0.0-preview.8.20325.1 /p:MicrosoftNetCompilersToolsetPackageVersion=3.7.0-4.20319.6 /p:RazorSdkDirectoryRoot=F:\workspace\_work\1\s\artifacts\bin\Microsoft.NET.Sdk.Razor\Release\sdk-output\ /p:RepoRoot=F:\workspace\_work\1\s\ /p:Configuration=Release /restore /t:Build .\blazorhosted.csproj
        Determining projects to restore...
        Restored F:\h\w\A443092A\t\Razor\qlat2ahv.bes\razorclasslibrary\RazorClassLibrary.csproj (in 435 ms).
        Restored F:\h\w\A443092A\t\Razor\qlat2ahv.bes\blazorhosted\blazorhosted.csproj (in 436 ms).
        Restored F:\h\w\A443092A\t\Razor\qlat2ahv.bes\blazorwasm\blazorwasm.csproj (in 348 ms).
        Restored F:\h\w\A443092A\t\Razor\qlat2ahv.bes\classlibrarywithsatelliteassemblies\classlibrarywithsatelliteassemblies.csproj (in 426 ms).
        You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
        You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
        You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
        classlibrarywithsatelliteassemblies -> F:\h\w\A443092A\t\Razor\qlat2ahv.bes\classlibrarywithsatelliteassemblies\bin\Release\netstandard2.1\classlibrarywithsatelliteassemblies.dll
        RazorClassLibrary -> F:\h\w\A443092A\t\Razor\qlat2ahv.bes\razorclasslibrary\bin\Release\netstandard2.1\RazorClassLibrary.dll
      
      Stack Trace:
        /_/src/Razor/Microsoft.NET.Sdk.Razor/integrationtests/MSBuildProcessManager.cs(220,0): at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.<>c__DisplayClass2_0.<<RunProcessCoreAsync>g__GetTimeoutForProcess|3>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/Razor/Microsoft.NET.Sdk.Razor/integrationtests/MSBuildProcessManager.cs(122,0): at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.RunProcessAsync(ProjectDirectory project, String arguments, Nullable`1 timeout, MSBuildProcessKind msBuildProcessKind)
        /_/src/Razor/Microsoft.NET.Sdk.Razor/integrationtests/Wasm/WasmPublishIntegrationTest.cs(557,0): at Microsoft.AspNetCore.Razor.Design.IntegrationTests.WasmPublishIntegrationTest.Publish_HostedApp_VisualStudio_WithSatelliteAssemblies()
        --- End of stack trace from previous location ---
```

Publish_UpdatesFilesWhenSourcesChange
```
Publish_UpdatesFilesWhenSourcesChange [FAIL]
      System.TimeoutException : command '$F:\workspace\_work\1\s\.dotnet\dotnet.exe msbuild /nr:false /bl /p:RunningAsTest=true /p:MicrosoftNETCoreAppRuntimeVersion=5.0.0-preview.8.20323.9 /p:MicrosoftNetCompilersToolsetPackageVersion=3.7.0-4.20319.6 /p:RazorSdkDirectoryRoot=F:\workspace\_work\1\s\artifacts\bin\Microsoft.NET.Sdk.Razor\Release\sdk-output\ /p:RepoRoot=F:\workspace\_work\1\s\ /p:Configuration=Release /t:publish ' timed out after 00:05:00. Output: Microsoft (R) Build Engine version 16.7.0-preview-20309-02+d6862eb21 for .NET
      Copyright (C) Microsoft Corporation. All rights reserved.
      
      F:\workspace\_work\1\s\.dotnet\sdk\5.0.100-preview.6.20310.4\MSBuild.dll -maxcpucount -verbosity:m /bl /nr:false /p:RunningAsTest=true /p:MicrosoftNETCoreAppRuntimeVersion=5.0.0-preview.8.20323.9 /p:MicrosoftNetCompilersToolsetPackageVersion=3.7.0-4.20319.6 /p:RazorSdkDirectoryRoot=F:\workspace\_work\1\s\artifacts\bin\Microsoft.NET.Sdk.Razor\Release\sdk-output\ /p:RepoRoot=F:\workspace\_work\1\s\ /p:Configuration=Release /t:publish .\blazorhosted.csproj
        You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
        You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
        RazorClassLibrary -> F:\h\w\AA640945\t\Razor\t0l5z3gt.ixm\razorclasslibrary\bin\Release\netstandard2.1\RazorClassLibrary.dll
        blazorwasm -> F:\h\w\AA640945\t\Razor\t0l5z3gt.ixm\blazorwasm\bin\Release\net5.0\blazorwasm.dll
        blazorwasm (Blazor output) -> F:\h\w\AA640945\t\Razor\t0l5z3gt.ixm\blazorwasm\bin\Release\net5.0\wwwroot
        blazorhosted -> F:\h\w\AA640945\t\Razor\t0l5z3gt.ixm\blazorhosted\bin\Release\net5.0\blazorhosted.dll
        Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
        Compressing Blazor WebAssembly publish artifacts. This may take a while...
        blazorhosted -> F:\h\w\AA640945\t\Razor\t0l5z3gt.ixm\blazorhosted\bin\Release\net5.0\publish\
      
      Stack Trace:
        /_/src/Razor/Microsoft.NET.Sdk.Razor/integrationtests/MSBuildProcessManager.cs(220,0): at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.<>c__DisplayClass2_0.<<RunProcessCoreAsync>g__GetTimeoutForProcess|3>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/Razor/Microsoft.NET.Sdk.Razor/integrationtests/MSBuildProcessManager.cs(122,0): at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.RunProcessAsync(ProjectDirectory project, String arguments, Nullable`1 timeout, MSBuildProcessKind msBuildProcessKind)
        /_/src/Razor/Microsoft.NET.Sdk.Razor/integrationtests/Wasm/WasmCompressionTests.cs(37,0): at Microsoft.AspNetCore.Razor.Design.IntegrationTests.WasmCompressionTests.Publish_UpdatesFilesWhenSourcesChange()
        --- End of stack trace from previous location ---
```

**Comment by Tratcher** [comment]
Adding a similar failure for Publish_HostedApp_WithSatelliteAssemblies

```
System.TimeoutException : command '$F:\workspace\_work\1\s\.dotnet\dotnet.exe msbuild /nr:false /bl /p:RunningAsTest=true /p:MicrosoftNETCoreAppRuntimeVersion=5.0.0-preview.8.20326.2 /p:MicrosoftNetCompilersToolsetPackageVersion=3.7.0-4.20319.6 /p:RazorSdkDirectoryRoot=F:\workspace\_work\1\s\artifacts\bin\Microsoft.NET.Sdk.Razor\Release\sdk-output\ /p:RepoRoot=F:\workspace\_work\1\s\ /p:Configuration=Release /t:Publish /restore' timed out after 00:05:00. Output: Microsoft (R) Build Engine version 16.7.0-preview-20309-02+d6862eb21 for .NET\r\nCopyright (C) Microsoft Corporation. All rights reserved.\r\n\r\nF:\workspace\_work\1\s\.dotnet\sdk\5.0.100-preview.6.20310.4\MSBuild.dll -maxcpucount -verbosity:m /bl /nr:false /p:RunningAsTest=true /p:MicrosoftNETCoreAppRuntimeVersion=5.0.0-preview.8.20326.2 /p:MicrosoftNetCompilersToolsetPackageVersion=3.7.0-4.20319.6 /p:RazorSdkDirectoryRoot=F:\workspace\_work\1\s\artifacts\bin\Microsoft.NET.Sdk.Razor\Release\sdk-output\ /p:RepoRoot=F:\workspace\_work\1\s\ /p:Configuration=Release /restore /t:Publish .\blazorhosted.csproj\r\n Determining projects to restore...\r\n Restored F:\h\w\9E0508F5\t\Razor\askipdkc.uya\blazorhosted\blazorhosted.csproj (in 670 ms).\r\n Restored F:\h\w\9E0508F5\t\Razor\askipdkc.uya\blazorwasm\blazorwasm.csproj (in 665 ms).\r\n Restored F:\h\w\9E0508F5\t\Razor\askipdkc.uya\classlibrarywithsatelliteassemblies\classlibrarywithsatelliteassemblies.csproj (in 668 ms).\r\n Restored F:\h\w\9E0508F5\t\Razor\askipdkc.uya\razorclasslibrary\RazorClassLibrary.csproj (in 762 ms).\r\n You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview\r\n You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview\r\n You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview\r\n RazorClassLibrary -> F:\h\w\9E0508F5\t\Razor\askipdkc.uya\razorclasslibrary\bin\Release\netstandard2.1\RazorClassLibrary.dll\r\n classlibrarywithsatelliteassemblies -> F:\h\w\9E0508F5\t\Razor\askipdkc.uya\classlibrarywithsatelliteassemblies\bin\Release\netstandard2.1\classlibrarywithsatelliteassemblies.dll\r\n blazorwasm -> F:\h\w\9E0508F5\t\Razor\askipdkc.uya\blazorwasm\bin\Release\net5.0\blazorwasm.dll\r\n blazorwasm (Blazor output) -> F:\h\w\9E0508F5\t\Razor\askipdkc.uya\blazorwasm\bin\Release\net5.0\wwwroot\r\n blazorhosted -> F:\h\w\9E0508F5\t\Razor\askipdkc.uya\blazorhosted\bin\Release\net5.0\blazorhosted.dll\r\n Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink\r\n
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.<>c__DisplayClass2_0.<<RunProcessCoreAsync>g__GetTimeoutForProcess|3>d.MoveNext() in /_/src/Razor/Microsoft.NET.Sdk.Razor/integrationtests/MSBuildProcessManager.cs:line 220
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.RunProcessAsync(ProjectDirectory project, String arguments, Nullable`1 timeout, MSBuildProcessKind msBuildProcessKind) in /_/src/Razor/Microsoft.NET.Sdk.Razor/integrationtests/MSBuildProcessManager.cs:line 122
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.WasmPublishIntegrationTest.Publish_HostedApp_WithSatelliteAssemblies() in /_/src/Razor/Microsoft.NET.Sdk.Razor/integrationtests/Wasm/WasmPublishIntegrationTest.cs:line 364
--- End of stack trace from previous location ---

**Comment by BrennanConroy** [comment]
Similarly Publish_WithoutLinkerAndCompression_UpdatesFilesWhenSourcesChange:
```
System.TimeoutException : command '$F:\workspace\_work\1\s\.dotnet\dotnet.exe msbuild /nr:false /bl /p:RunningAsTest=true /p:MicrosoftNETCoreAppRuntimeVersion=5.0.0-preview.8.20357.14 /p:MicrosoftNetCompilersToolsetPackageVersion=3.8.0-1.20353.1 /p:RazorSdkDirectoryRoot=F:\workspace\_work\1\s\artifacts\bin\Microsoft.NET.Sdk.Razor\Release\sdk-output\ /p:RepoRoot=F:\workspace\_work\1\s\ /p:Configuration=Release /t:publish /p:BlazorWebAssemblyEnableLinking=false' timed out after 00:05:00. Output: Microsoft (R) Build Engine version 16.7.0-preview-20330-02+1eab2845b for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

F:\workspace\_work\1\s\.dotnet\sdk\5.0.100-preview.7.20330.3\MSBuild.dll -maxcpucount -verbosity:m /bl /nr:false /p:RunningAsTest=true /p:MicrosoftNETCoreAppRuntimeVersion=5.0.0-preview.8.20357.14 /p:MicrosoftNetCompilersToolsetPackageVersion=3.8.0-1.20353.1 /p:RazorSdkDirectoryRoot=F:\workspace\_work\1\s\artifacts\bin\Microsoft.NET.Sdk.Razor\Release\sdk-output\ /p:RepoRoot=F:\workspace\_work\1\s\ /p:Configuration=Release /p:BlazorWebAssemblyEnableLinking=false /t:publish .\blazorhosted.csproj
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  RazorClassLibrary -> F:\h\w\BC0A09E7\t\Razor\pwvcqboc.1c1\razorclasslibrary\bin\Release\netstandard2.1\RazorClassLibrary.dll
  blazorwasm -> F:\h\w\BC0A09E7\t\Razor\pwvcqboc.1c1\blazorwasm\bin\Release\net5.0\blazorwasm.dll
  blazorwasm (Blazor output) -> F:\h\w\BC0A09E7\t\Razor\pwvcqboc.1c1\blazorwasm\bin\Release\net5.0\wwwroot
  blazorhosted -> F:\h\w\BC0A09E7\t\Razor\pwvcqboc.1c1\blazorhosted\bin\Release\net5.0\blazorhosted.dll
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
  Compressing Blazor WebAssembly publish artifacts. This may take a while...
```

**Comment by pranavkm** [comment]
These tests were re-enabled after observing they haven' been failing for > 1 month. The tests now use `dotnet test` hang features to detect hangs and capture crash dumps.
