### ISSUE TITLE
Investigate DoesNotThrowObjectDisposedExceptionFromWriteAsyncAfterConnectionIsAborted failures on Win7 and Win8

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#23405]
https://helix.dot.net/api/2019-06-17/jobs/233e8b0b-f611-4e00-b69a-bfcb9cfc5763/workitems/InMemory.FunctionalTests--net5.0/files/console.9beac6c0.log
```
[xUnit.net 00:00:35.51]       System.TimeoutException : The operation at /_/src/Servers/Kestrel/shared/test/TaskTimeoutExtensions.cs:27 timed out after reaching the limit of 30000ms.
[xUnit.net 00:00:35.51]       Stack Trace:
[xUnit.net 00:00:35.51]         /_/src/Testing/src/TaskExtensions.cs(57,0): at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber)
[xUnit.net 00:00:35.51]         /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/HttpsTests.cs(261,0): at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.HttpsTests.DoesNotThrowObjectDisposedExceptionFromWriteAsyncAfterConnectionIsAborted()
[xUnit.net 00:00:35.51]         /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/HttpsTests.cs(261,0): at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.HttpsTests.DoesNotThrowObjectDisposedExceptionFromWriteAsyncAfterConnectionIsAborted()
[xUnit.net 00:00:35.51]         --- End of stack trace from previous location ---
  X DoesNotThrowObjectDisposedExceptionFromWriteAsyncAfterConnectionIsAborted [30s 531ms]
  Error Message:
   System.TimeoutException : The operation at /_/src/Servers/Kestrel/shared/test/TaskTimeoutExtensions.cs:27 timed out after reaching the limit of 30000ms.
  Stack Trace:
     at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Testing/src/TaskExtensions.cs:line 57
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.HttpsTests.DoesNotThrowObjectDisposedExceptionFromWriteAsyncAfterConnectionIsAborted() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/HttpsTests.cs:line 261
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.HttpsTests.DoesNotThrowObjectDisposedExceptionFromWriteAsyncAfterConnectionIsAborted() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/HttpsTests.cs:line 261
--- End of stack trace from previous location ---
```

**Comment by halter73** [comment]
Where do I find the `HttpsTests_DoesNotThrowObjectDisposedExceptionFromWriteAsyncAfterConnectionIsAborted.log`? It looks like the script that normally lists the URLs crashed 😢 

```
Found log 'C:\h\w\AF5B09CE\w\A2750986\e\..\BadHttpRequestTests_BadRequestLogsAreNotHigherThanDebug.log'
Uri 'https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-heads-master-233e8b0bf6114e00b6/InMemory.FunctionalTests--net5.0/BadHttpRequestTests_BadRequestLogsAreNotHigherThanDebug.log?sv=2019-02-02&se=2020-07-16T12%3A53%3A00Z&sr=c&sp=rl&sig=SVZJcGz%2F9Ku8esr4mtmBBAIcJa3V0DQcnvz%2BSsvqy1o%3D'
Traceback (most recent call last):
  File "C:\h\w\AF5B09CE\p\reporter\run.py", line 110, in <module>
    main()
  File "C:\h\w\AF5B09CE\p\reporter\run.py", line 100, in main
    for b in batches:
  File "C:\h\w\AF5B09CE\p\reporter\helpers.py", line 13, in batch
    for item in iterable:
  File "C:\h\w\AF5B09CE\p\reporter\test_results_reader\__init__.py", line 81, in read_results
    log_files = list(get_log_files(os.path.join(get_env("HELIX_WORKITEM_ROOT"), "..")))
  File "C:\h\w\AF5B09CE\p\reporter\test_results_reader\__init__.py", line 50, in get_log_files
    print("Found log '{}'".format(path))
  File "C:\Users\runner\.azdo-env\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\x80' in position 131: character maps to <undefined>
 Fri 06/26/2020-13:17:30.71
2020-06-26T13:17:31.235Z	INFO   	xunit-reporter.py	xunit-reporter(93)	main	Uploading results from C:\h\w\AF5B09CE\w\A2750986\e\testResults.xml
```

**Comment by Tratcher** [comment]
Check the Helix Test Logs (Beta) tab:
https://dev.azure.com/dnceng/public/_build/results?buildId=708777&view=ms.vss-test-web.build-test-results-tab&runId=21952028&resultId=121752&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab
```
[0.002s] [TestLifetime] [Information] Starting test DoesNotThrowObjectDisposedExceptionFromWriteAsyncAfterConnectionIsAborted at 2020-06-29T00:58:34
[0.005s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Debug] Hosting starting
[0.022s] [Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware] [Information] HTTP/2 over TLS is not supported on Windows versions older than Windows 10 and Windows Server 2016 due to incompatible ciphers or missing ALPN support. Falling back to HTTP/1.1 instead.
[0.023s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Debug] Hosting started
[0.023s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Debug] Loaded hosting startup assembly testhost
[0.158s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "0HM0ROU5TTJQL" accepted.
[0.233s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "0HM0ROU5TTJQL" started.
[0.406s] [Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware] [Debug] Connection "0HM0ROU5TTJQL" established using the following protocol: Tls12
[0.408s] [Microsoft.AspNetCore.Server.Kestrel] [Error] Unhandled exception while processing 0HM0ROU5TTJQL.
System.AggregateException: An error occurred while writing to logger(s). (An attempt was made to transition a task to a final state when it had already completed.)
 ---> System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
   at System.Threading.Tasks.TaskCompletionSource.SetResult()
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.HttpsTests.HttpsConnectionFilterLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/HttpsTests.cs:line 498
   at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|12_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.ThrowLoggingError(List`1 exceptions)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger`1.Microsoft.Extensions.Logging.ILogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass6_0`2.<Define>g__Log|0(ILogger logger, T1 arg1, T2 arg2, Exception exception)
   at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass6_0`2.<Define>b__1(ILogger logger, T1 arg1, T2 arg2, Exception exception)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddlewareLoggerExtensions.HttpsConnectionEstablished(ILogger logger, String connectionId, SslProtocols sslProtocol) in /_/src/Servers/Kestrel/Core/src/Middleware/HttpsConnectionMiddleware.cs:line 356
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context) in /_/src/Servers/Kestrel/Core/src/Middleware/HttpsConnectionMiddleware.cs:line 261
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1.ExecuteAsync() in /_/src/Servers/Kestrel/Core/src/Internal/Infrastructure/KestrelConnectionOfT.cs:line 52
[0.408s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "0HM0ROU5TTJQL" stopped.
[30.456s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Debug] Hosting shutdown
[30.458s] [TestLifetime] [Information] Finished test DoesNotThrowObjectDisposedExceptionFromWriteAsyncAfterConnectionIsAborted in 30.4561508s
```

**Comment by Tratcher** [comment]
Haha, maybe this is the new auto-downgrade log.
https://github.com/dotnet/aspnetcore/pull/22859/files#diff-c0da093ed9fbe9cede84fceac9ee5405R64

**Comment by halter73** [comment]
It's definitely the new auto-downgrade log. The question is, is it related? I doubt it since the test always make an HTTP/1.1 request.

**Comment by Tratcher** [comment]
Http1AndHttp2 are enabled by default though. That extra log is just warning you that HTTP/2 isn't supported and is being turned off. The test wasn't expecting an extra log and throws.

**Comment by halter73** [comment]
> The test wasn't expecting an extra log and throws.

Ahhh. That's definitely it. Looks HandshakeErrorLoggerProvider expects there to always be exactly one log from HttpsConnectionMiddleware per test. That's obviously not the case anymore.

https://github.com/dotnet/aspnetcore/blob/b724aa62bf4f055092e951e331c22b9c14088db2/src/Servers/Kestrel/test/InMemory.FunctionalTests/HttpsTests.cs#L466-L510

The best/easiest fix is probably to add a ctor to HttpsConnectionFilterLogger that takes in the expected eventId and ignores all other logs from HttpsConnectionMiddleware.

**Comment by Tratcher** [comment]
This test is still regularly timing out on Win7 & 8. It currently has the 5th highest failure rate, please priortize.

**Comment by Tratcher** [comment]
This is now the second most flaky test we haven't addressed with 56 failures out of 373 runs. The failures are still consistently on Win7 and Win8.
