### ISSUE TITLE
.NET 4.6 AspNetCore 2.2 From file razor compilation error

### ISSUE THREAD

**Issue by GAMP** [dotnet/aspnetcore#23459]
We have an .net 4.6.1 application using MVC Core 2.2, for some reason when view is rendered from file the compilation fails.
The precompiled views are working without any problems but once a file view is to be rendered an **Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException** is thrown.

```
Microsoft.AspNetCore.Mvc.Razor.Compilation.CompilationFailedException
  HResult=0x80131500
  Message=One or more compilation failures occurred:
z5cxuc24.r3i(4,55): error CS0731: The type forwarder for type 'System.Attribute' in assembly 'mscorlib' causes a cycle
z5cxuc24.r3i(5,62): error CS0731: The type forwarder for type 'System.Attribute' in assembly 'mscorlib' causes a cycle
z5cxuc24.r3i(4,82): error CS0518: Predefined type 'System.Type' is not defined or imported
z5cxuc24.r3i(4,119): error CS0518: Predefined type 'System.String' is not defined or imported
z5cxuc24.r3i(4,136): error CS0518: Predefined type 'System.String' is not defined or imported
z5cxuc24.r3i(4,12): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(5,81): error CS0518: Predefined type 'System.String' is not defined or imported
z5cxuc24.r3i(5,110): error CS0518: Predefined type 'System.Type' is not defined or imported
z5cxuc24.r3i(5,11): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(16,49): error CS0731: The type forwarder for type 'System.Attribute' in assembly 'mscorlib' causes a cycle
z5cxuc24.r3i(16,78): error CS0518: Predefined type 'System.String' is not defined or imported
z5cxuc24.r3i(16,87): error CS0518: Predefined type 'System.String' is not defined or imported
z5cxuc24.r3i(16,132): error CS0518: Predefined type 'System.String' is not defined or imported
z5cxuc24.r3i(16,6): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(17,37): error CS0731: The type forwarder for type 'System.Object' in assembly 'netstandard' causes a cycle
z5cxuc24.r3i(20,62): error CS1069: The type name 'Task' could not be found in the namespace 'System.Threading.Tasks'. This type has been forwarded to assembly 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.
z5cxuc24.r3i(124,118): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(126,71): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(128,87): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(130,83): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(132,71): error CS0731: The type forwarder for type 'System.Object' in assembly 'netstandard' causes a cycle
z5cxuc24.r3i(132,71): error CS0518: Predefined type 'System.Object' is not defined or imported
z5cxuc24.r3i(132,129): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(123,58): error CS0731: The type forwarder for type 'System.Attribute' in assembly 'mscorlib' causes a cycle
z5cxuc24.r3i(123,10): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(125,58): error CS0731: The type forwarder for type 'System.Attribute' in assembly 'mscorlib' causes a cycle
z5cxuc24.r3i(125,10): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(127,58): error CS0731: The type forwarder for type 'System.Attribute' in assembly 'mscorlib' causes a cycle
z5cxuc24.r3i(127,10): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(129,58): error CS0731: The type forwarder for type 'System.Attribute' in assembly 'mscorlib' causes a cycle
z5cxuc24.r3i(129,10): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(131,58): error CS0731: The type forwarder for type 'System.Attribute' in assembly 'mscorlib' causes a cycle
z5cxuc24.r3i(131,10): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(22,13): error CS0731: The type forwarder for type 'System.Object' in assembly 'netstandard' causes a cycle
z5cxuc24.r3i(22,13): error CS0518: Predefined type 'System.Object' is not defined or imported
z5cxuc24.r3i(22,26): error CS0518: Predefined type 'System.Int32' is not defined or imported
z5cxuc24.r3i(22,30): error CS0518: Predefined type 'System.Int32' is not defined or imported
z5cxuc24.r3i(22,36): error CS0518: Predefined type 'System.Boolean' is not defined or imported
z5cxuc24.r3i(22,13): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(23,13): error CS0731: The type forwarder for type 'System.Object' in assembly 'netstandard' causes a cycle
z5cxuc24.r3i(23,13): error CS0518: Predefined type 'System.Object' is not defined or imported
z5cxuc24.r3i(23,26): error CS0518: Predefined type 'System.String' is not defined or imported
z5cxuc24.r3i(23,13): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(48,13): error CS0731: The type forwarder for type 'System.Object' in assembly 'netstandard' causes a cycle
z5cxuc24.r3i(48,13): error CS0518: Predefined type 'System.Object' is not defined or imported
z5cxuc24.r3i(48,26): error CS0518: Predefined type 'System.String' is not defined or imported
z5cxuc24.r3i(48,13): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(49,13): error CS0731: The type forwarder for type 'System.Object' in assembly 'netstandard' causes a cycle
z5cxuc24.r3i(49,13): error CS0518: Predefined type 'System.Object' is not defined or imported
z5cxuc24.r3i(49,13): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(50,13): error CS0731: The type forwarder for type 'System.Object' in assembly 'netstandard' causes a cycle
z5cxuc24.r3i(50,13): error CS0518: Predefined type 'System.Object' is not defined or imported
z5cxuc24.r3i(50,26): error CS0518: Predefined type 'System.Int32' is not defined or imported
z5cxuc24.r3i(50,32): error CS0518: Predefined type 'System.Int32' is not defined or imported
z5cxuc24.r3i(50,37): error CS0518: Predefined type 'System.Boolean' is not defined or imported
z5cxuc24.r3i(50,13): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(56,13): error CS0731: The type forwarder for type 'System.Object' in assembly 'netstandard' causes a cycle
z5cxuc24.r3i(56,13): error CS0518: Predefined type 'System.Object' is not defined or imported
z5cxuc24.r3i(56,13): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(57,13): error CS0731: The type forwarder for type 'System.Object' in assembly 'netstandard' causes a cycle
z5cxuc24.r3i(57,13): error CS0518: Predefined type 'System.Object' is not defined or imported
z5cxuc24.r3i(57,26): error CS0518: Predefined type 'System.Int32' is not defined or imported
z5cxuc24.r3i(57,32): error CS0518: Predefined type 'System.Int32' is not defined or imported
z5cxuc24.r3i(57,37): error CS0518: Predefined type 'System.Boolean' is not defined or imported
z5cxuc24.r3i(57,13): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(58,13): error CS0731: The type forwarder for type 'System.Object' in assembly 'netstandard' causes a cycle
z5cxuc24.r3i(58,13): error CS0518: Predefined type 'System.Object' is not defined or imported
z5cxuc24.r3i(58,26): error CS0518: Predefined type 'System.String' is not defined or imported
z5cxuc24.r3i(58,13): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(69,13): error CS0731: The type forwarder for type 'System.Object' in assembly 'netstandard' causes a cycle
z5cxuc24.r3i(69,13): error CS0518: Predefined type 'System.Object' is not defined or imported
z5cxuc24.r3i(69,13): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(70,13): error CS0731: The type forwarder for type 'System.Object' in assembly 'netstandard' causes a cycle
z5cxuc24.r3i(70,13): error CS0518: Predefined type 'System.Object' is not defined or imported
z5cxuc24.r3i(70,26): error CS0518: Predefined type 'System.Int32' is not defined or imported
z5cxuc24.r3i(70,32): error CS0518: Predefined type 'System.Int32' is not defined or imported
z5cxuc24.r3i(70,37): error CS0518: Predefined type 'System.Boolean' is not defined or imported
z5cxuc24.r3i(70,13): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(76,13): error CS0731: The type forwarder for type 'System.Object' in assembly 'netstandard' causes a cycle
z5cxuc24.r3i(76,13): error CS0518: Predefined type 'System.Object' is not defined or imported
z5cxuc24.r3i(76,13): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(77,13): error CS0731: The type forwarder for type 'System.Object' in assembly 'netstandard' causes a cycle
z5cxuc24.r3i(77,13): error CS0518: Predefined type 'System.Object' is not defined or imported
z5cxuc24.r3i(77,26): error CS0518: Predefined type 'System.Int32' is not defined or imported
z5cxuc24.r3i(77,32): error CS0518: Predefined type 'System.Int32' is not defined or imported
z5cxuc24.r3i(77,36): error CS0518: Predefined type 'System.Boolean' is not defined or imported
z5cxuc24.r3i(77,13): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(78,13): error CS0731: The type forwarder for type 'System.Object' in assembly 'netstandard' causes a cycle
z5cxuc24.r3i(78,13): error CS0518: Predefined type 'System.Object' is not defined or imported
z5cxuc24.r3i(78,26): error CS0518: Predefined type 'System.String' is not defined or imported
z5cxuc24.r3i(78,13): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(79,13): error CS0731: The type forwarder for type 'System.Object' in assembly 'netstandard' causes a cycle
z5cxuc24.r3i(79,13): error CS0518: Predefined type 'System.Object' is not defined or imported
z5cxuc24.r3i(79,13): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(86,13): error CS0731: The type forwarder for type 'System.Object' in assembly 'netstandard' causes a cycle
z5cxuc24.r3i(86,13): error CS0518: Predefined type 'System.Object' is not defined or imported
z5cxuc24.r3i(86,26): error CS0518: Predefined type 'System.Int32' is not defined or imported
z5cxuc24.r3i(86,32): error CS0518: Predefined type 'System.Int32' is not defined or imported
z5cxuc24.r3i(86,37): error CS0518: Predefined type 'System.Boolean' is not defined or imported
z5cxuc24.r3i(86,13): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(87,13): error CS0731: The type forwarder for type 'System.Object' in assembly 'netstandard' causes a cycle
z5cxuc24.r3i(87,13): error CS0518: Predefined type 'System.Object' is not defined or imported
z5cxuc24.r3i(87,26): error CS0518: Predefined type 'System.String' is not defined or imported
z5cxuc24.r3i(87,13): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(88,13): error CS0731: The type forwarder for type 'System.Object' in assembly 'netstandard' causes a cycle
z5cxuc24.r3i(88,13): error CS0518: Predefined type 'System.Object' is not defined or imported
z5cxuc24.r3i(88,13): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(89,13): error CS0731: The type forwarder for type 'System.Object' in assembly 'netstandard' causes a cycle
z5cxuc24.r3i(89,13): error CS0518: Predefined type 'System.Object' is not defined or imported
z5cxuc24.r3i(89,26): error CS0518: Predefined type 'System.Int32' is not defined or imported
z5cxuc24.r3i(89,32): error CS0518: Predefined type 'System.Int32' is not defined or imported
z5cxuc24.r3i(89,36): error CS0518: Predefined type 'System.Boolean' is not defined or imported
z5cxuc24.r3i(89,13): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(95,13): error CS0731: The type forwarder for type 'System.Object' in assembly 'netstandard' causes a cycle
z5cxuc24.r3i(95,13): error CS0518: Predefined type 'System.Object' is not defined or imported
z5cxuc24.r3i(95,13): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(96,13): error CS0731: The type forwarder for type 'System.Object' in assembly 'netstandard' causes a cycle
z5cxuc24.r3i(96,13): error CS0518: Predefined type 'System.Object' is not defined or imported
z5cxuc24.r3i(96,26): error CS0518: Predefined type 'System.Int32' is not defined or imported
z5cxuc24.r3i(96,32): error CS0518: Predefined type 'System.Int32' is not defined or imported
z5cxuc24.r3i(96,37): error CS0518: Predefined type 'System.Boolean' is not defined or imported
z5cxuc24.r3i(96,13): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(97,13): error CS0731: The type forwarder for type 'System.Object' in assembly 'netstandard' causes a cycle
z5cxuc24.r3i(97,13): error CS0518: Predefined type 'System.Object' is not defined or imported
z5cxuc24.r3i(97,26): error CS0518: Predefined type 'System.String' is not defined or imported
z5cxuc24.r3i(97,13): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(103,13): error CS0731: The type forwarder for type 'System.Object' in assembly 'netstandard' causes a cycle
z5cxuc24.r3i(103,13): error CS0518: Predefined type 'System.Object' is not defined or imported
z5cxuc24.r3i(103,13): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(110,13): error CS0731: The type forwarder for type 'System.Object' in assembly 'netstandard' causes a cycle
z5cxuc24.r3i(110,13): error CS0518: Predefined type 'System.Object' is not defined or imported
z5cxuc24.r3i(110,26): error CS0518: Predefined type 'System.Int32' is not defined or imported
z5cxuc24.r3i(110,32): error CS0518: Predefined type 'System.Int32' is not defined or imported
z5cxuc24.r3i(110,37): error CS0518: Predefined type 'System.Boolean' is not defined or imported
z5cxuc24.r3i(110,13): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(111,13): error CS0731: The type forwarder for type 'System.Object' in assembly 'netstandard' causes a cycle
z5cxuc24.r3i(111,13): error CS0518: Predefined type 'System.Object' is not defined or imported
z5cxuc24.r3i(111,26): error CS0518: Predefined type 'System.String' is not defined or imported
z5cxuc24.r3i(111,13): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(120,13): error CS0731: The type forwarder for type 'System.Object' in assembly 'netstandard' causes a cycle
z5cxuc24.r3i(120,13): error CS0518: Predefined type 'System.Object' is not defined or imported
z5cxuc24.r3i(120,13): error CS0518: Predefined type 'System.Void' is not defined or imported
z5cxuc24.r3i(20,67): error CS0161: 'Views_Auth_Index.ExecuteAsync()': not all code paths return a value
z5cxuc24.r3i(17,18): error CS0518: Predefined type 'System.Void' is not defined or imported
error CS1705: Assembly 'Microsoft.AspNetCore.Mvc.Razor' with identity 'Microsoft.AspNetCore.Mvc.Razor, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' uses 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
D:\My Documents\Visual Studio 2015\Projects\Gizmo\GizmoService\GizmoService\bin\debug\WebRoot\Views\Auth\Index.cshtml(28,16): error CS0731: The type forwarder for type 'System.Object' in assembly 'netstandard' causes a cycle
D:\My Documents\Visual Studio 2015\Projects\Gizmo\GizmoService\GizmoService\bin\debug\WebRoot\Views\Auth\Index.cshtml(28,16): error CS0518: Predefined type 'System.Object' is not defined or imported
D:\My Documents\Visual Studio 2015\Projects\Gizmo\GizmoService\GizmoService\bin\debug\WebRoot\Views\Auth\Index.cshtml(28,68): error CS0518: Predefined type 'System.String' is not defined or imported
D:\My Documents\Visual Studio 2015\Projects\Gizmo\GizmoService\GizmoService\bin\debug\WebRoot\Views\Auth\Index.cshtml(28,92): error CS0518: Predefined type 'System.String' is not defined or imported
D:\My Documents\Visual Studio 2015\Projects\Gizmo\GizmoService\GizmoService\bin\debug\WebRoot\Views\Auth\Index.cshtml(28,112): error CS0518: Predefined type 'System.String' is not defined or imported
D:\My Documents\Visual Studio 2015\Projects\Gizmo\GizmoService\GizmoService\bin\debug\WebRoot\Views\Auth\Index.cshtml(28,133): error CS0518: Predefined type 'System.String' is not defined or imported
D:\My Documents\Visual Studio 2015\Projects\Gizmo\GizmoService\GizmoService\bin\debug\WebRoot\Views\Auth\Index.cshtml(28,154): error CS0518: Predefined type 'System.String' is not defined or imported
D:\My Documents\Visual Studio 2015\Projects\Gizmo\GizmoService\GizmoService\bin\debug\WebRoot\Views\Auth\Index.cshtml(28,22): error CS0731: The type forwarder for type 'System.Linq.Expressions.Expression`1' in assembly 'System.Core' causes a cycle
D:\My Documents\Visual Studio 2015\Projects\Gizmo\GizmoService\GizmoService\bin\debug\WebRoot\Views\Auth\Index.cshtml(28,16): error CS0518: Predefined type 'System.Void' is not defined or imported
D:\My Documents\Visual Studio 2015\Projects\Gizmo\GizmoService\GizmoService\bin\debug\WebRoot\Views\Auth\Index.cshtml(38,16): error CS0731: The type forwarder for type 'System.Object' in assembly 'netstandard' causes a cycle
D:\My Documents\Visual Studio 2015\Projects\Gizmo\GizmoService\GizmoService\bin\debug\WebRoot\Views\Auth\Index.cshtml(38,16): error CS0518: Predefined type 'System.Object' is not defined or imported
D:\My Documents\Visual Studio 2015\Projects\Gizmo\GizmoService\GizmoService\bin\debug\WebRoot\Views\Auth\Index.cshtml(38,68): error CS0518: Predefined type 'System.String' is not defined or imported
D:\My Documents\Visual Studio 2015\Projects\Gizmo\GizmoService\GizmoService\bin\debug\WebRoot\Views\Auth\Index.cshtml(38,86): error CS0518: Predefined type 'System.String' is not defined or imported
D:\My Documents\Visual Studio 2015\Projects\Gizmo\GizmoService\GizmoService\bin\debug\WebRoot\Views\Auth\Index.cshtml(38,112): error CS0518: Predefined type 'System.String' is not defined or imported
D:\My Documents\Visual Studio 2015\Projects\Gizmo\GizmoService\GizmoService\bin\debug\WebRoot\Views\Auth\Index.cshtml(38,133): error CS0518: Predefined type 'System.String' is not defined or imported
D:\My Documents\Visual Studio 2015\Projects\Gizmo\GizmoService\GizmoService\bin\debug\WebRoot\Views\Auth\Index.cshtml(38,154): error CS0518: Predefined type 'System.String' is not defined or imported
D:\My Documents\Visual Studio 2015\Projects\Gizmo\GizmoService\GizmoService\bin\debug\WebRoot\Views\Auth\Index.cshtml(38,22): error CS0731: The type forwarder for type 'System.Linq.Expressions.Expression`1' in assembly 'System.Core' causes a cycle
D:\My Documents\Visual Studio 2015\Projects\Gizmo\GizmoService\GizmoService\bin\debug\WebRoot\Views\Auth\Index.cshtml(38,16): error CS0518: Predefined type 'System.Void' is not defined or imported
D:\My Documents\Visual Studio 2015\Projects\Gizmo\GizmoService\GizmoService\bin\debug\WebRoot\Views\Auth\Index.cshtml(42,46): error CS0518: Predefined type 'System.Boolean' is not defined or imported
D:\My Documents\Visual Studio 2015\Projects\Gizmo\GizmoService\GizmoService\bin\debug\WebRoot\Views\Auth\Index.cshtml(42,24): error CS0518: Predefined type 'System.Boolean' is not defined or imported
D:\My Documents\Visual Studio 2015\Projects\Gizmo\GizmoService\GizmoService\bin\debug\WebRoot\Views\Auth\Index.cshtml(45,24): error CS0731: The type forwarder for type 'System.Object' in assembly 'netstandard' causes a cycle
D:\My Documents\Visual Studio 2015\Projects\Gizmo\GizmoService\GizmoService\bin\debug\WebRoot\Views\Auth\Index.cshtml(45,24): error CS0518: Predefined type 'System.Object' is not defined or imported
D:\My Documents\Visual Studio 2015\Projects\Gizmo\GizmoService\GizmoService\bin\debug\WebRoot\Views\Auth\Index.cshtml(45,53): error CS0518: Predefined type 'System.Boolean' is not defined or imported
D:\My Documents\Visual Studio 2015\Projects\Gizmo\GizmoService\GizmoService\bin\debug\WebRoot\Views\Auth\Index.cshtml(45,60): error CS0518: Predefined type 'System.String' is not defined or imported
D:\My Documents\Visual Studio 2015\Projects\Gizmo\GizmoService\GizmoService\bin\debug\WebRoot\Views\Auth\Index.cshtml(45,30): error CS0518: Predefined type 'System.Boolean' is not defined or imported
D:\My Documents\Visual Studio 2015\Projects\Gizmo\GizmoService\GizmoService\bin\debug\WebRoot\Views\Auth\Index.cshtml(45,24): error CS0518: Predefined type 'System.Void' is not defined or imported
  Source=Microsoft.AspNetCore.Mvc.Razor
  StackTrace:
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(RazorCodeDocument codeDocument, String generatedCode)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.CompileAndEmit(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorViewCompiler.OnCacheMiss(String normalizedPath)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.<ExecuteAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__20.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__28`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultFilters>d__26.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__23.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.<Invoke>d__7.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.<Invoke>d__7.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.<Invoke>d__7.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.<Invoke>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ServerService.Web.Api.GlobalExceptionMiddleWare.<Invoke>d__2.MoveNext() in D:\My Documents\Visual Studio 2015\Projects\Gizmo\GizmoService\GizmoService\Web\Middleware\GlobalExceptionMiddleWare.cs:line 29

  This exception was originally thrown at this call stack:
    [External Code]
    ServerService.Web.Api.GlobalExceptionMiddleWare.Invoke(Microsoft.AspNetCore.Http.HttpContext) in GlobalExceptionMiddleWare.cs
```

The weird part is this 

**Assembly 'Microsoft.AspNetCore.Mvc.Razor' with identity 'Microsoft.AspNetCore.Mvc.Razor, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' uses 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'**

There is no reference to Microsoft.AspNetCore.Mvc.Razor 3.1 or at least i cant find one.
Perhaps its some package trying to resolve a newer version of Mvc.Razor ?

I should also note that i am using latest Visual Studio 2019.

**Comment by GAMP** [comment]
Regenerating binding redirects resolves the problem.
