### ISSUE TITLE
okhttp dispatcher

### ISSUE THREAD

**Issue by Elswah** [dotnet/aspnetcore#23456]
06-29 08:42:09.004 20424-21027/com.tatweer.vehicledashboardapp.dev D/crash: crash happen
    java.lang.RuntimeException: java.net.ConnectException: failed to connect to /192.168.9.21 (port 80) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
        at com.tatweer.vehicledashboardapp.common.infrastructure.signalr.SdtSignalR$HubConnectionTask.doInBackground(SdtSignalR.kt:230)
        at com.tatweer.vehicledashboardapp.common.infrastructure.signalr.SdtSignalR$HubConnectionTask.doInBackground(SdtSignalR.kt:213)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.net.ConnectException: failed to connect to /192.168.9.21 (port 80) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
        at libcore.io.IoBridge.isConnected(IoBridge.java:234)
        at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
        at libcore.io.IoBridge.connect(IoBridge.java:122)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
        at java.net.Socket.connect(Socket.java:884)
        at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:73)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:245)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:165)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
        at libcore.io.IoBridge.isConnected(IoBridge.java:223)
        at libcore.io.IoBridge.connectErrno(IoBridge.java:171) 
        at libcore.io.IoBridge.connect(IoBridge.java:122) 
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183) 
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452) 
        at java.net.Socket.connect(Socket.java:884) 
        at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:73) 
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:245) 
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:165) 
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257) 
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135) 
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114) 
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) 
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147) 
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818)

**Comment by Elswah** [comment]
this happen after make (iisreset) from server client should reconect again 
some time get this error kHttp Dispatcher  java.lang.StackOverflowError: stack size 1038KB

**Comment by Elswah** [comment]
https://github.com/dotnet/aspnetcore/issues/22989 continu to this 
@BrennanConroy

**Comment by Elswah** [comment]
http://52.240.141.101/swagger/index.html
this is server link @davidfowl  @mkArtakMSFT

**Comment by Elswah** [comment]
if there are any way to reconnect automatically if connection down sample

**Comment by Elswah** [comment]
we use windows server 2006 you can connect this code sample i put in github i give  to @BrennanConroy 
please help me on this now its about two week on this bug

**Comment by BrennanConroy** [comment]
Can you explain how to run the app and start the signalr logic? Last time I tried your app there was just a empty page with what looked like no signalr running.

**Comment by Elswah** [comment]
@BrennanConroy  first time it connect fine and get connectionid there are health check service to check this connection is latest id
the problem happen when reset iis from server it crash inside library and get okhttp dispacher stackoverflow error that mentioned
you can connect this code to any server ( iis ) microsoft server is 2016

**Comment by BrennanConroy** [comment]
You haven't provided the server code for us to run so we can't try to repro this by causing an IIS reset.

**Comment by Elswah** [comment]
@BrennanConroy  please give me your email, to send the credential to access server

**Comment by BrennanConroy** [comment]
Can you contact support to investigate this issue please?
https://support.microsoft.com/en-us/supportforbusiness/productselection?sapId=bec2bc54-b200-6962-301f-f098532f27b2
