### ISSUE TITLE
The ResolveBlazorRuntimeDependencies task failed unexpectedly

### ISSUE THREAD

**Issue by KarloX2** [dotnet/aspnetcore#23471]
Hi!
Today I updated my VS2019 to Version 16.7.0 Preview 3.1 and I installed the .NET Core SDK 5.0.100-preview.6.
Then I tried to create a project from the Blazor App template, targeting .NET5 and choosing the WASM variant. 
Then when I rebuild the solution I run into an error saying this...

```
"Error	MSB4018	The "ResolveBlazorRuntimeDependencies" task failed unexpectedly."
System.IO.FileNotFoundException: Could not load file or assembly 'BlazorAppWasmTest.dll' or one of its dependencies. The system cannot find the file specified.
File name: 'BlazorAppWasmTest.dll' ---> System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at System.Reflection.AssemblyName.nGetFileInformation(String s)
   at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
   at Microsoft.AspNetCore.Components.WebAssembly.Build.ResolveBlazorRuntimeDependencies.ResolveRuntimeDependenciesCore(String entryPoint, IEnumerable`1 applicationDependencies, IEnumerable`1 monoBclAssemblies)
   at Microsoft.AspNetCore.Components.WebAssembly.Build.ResolveBlazorRuntimeDependencies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

	BlazorAppWasmTest	C:\Users\myname\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\5.0.0-preview.6.20312.15\targets\Blazor.MonoRuntime.targets	376	
```

What can I do?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
This will be resolved in preview 7.
