### ISSUE TITLE
VS downloads old version of AuthenticationService.js for AAD integration

### ISSUE THREAD

**Issue by vibhubanga** [dotnet/aspnetcore#23533]
I created a Blazor web assembly project (.net core 3.1) using VS2019 wizard instead of CLI and then tried following step by step guide to integrate with AAD. However to my surprise upon debugging i found that the AuthenticationService.js which is referred in the index.html file is an old version and not the latest one which gets created if you create a blazorwasm project protected using AAD via dotnet CLI. The CLI version of the JS file works fine as per article https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-azure-active-directory?view=aspnetcore-3.1 but using VS2019 enterprise edition it throws an error -> 

blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot read property 'join' of undefined
      TypeError: Cannot read property 'join' of undefined
          at Function.createUserManager (https://localhost:44397/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js:1:6020)
          at Function.initializeCore (https://localhost:44397/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js:1:5035)
          at Function.init (https://localhost:44397/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js:1:4575)
          at https://localhost:44397/_framework/blazor.webassembly.js:1:9873
          at new Promise (<anonymous>)
          at Object.beginInvokeJSFromDotNet (https://localhost:44397/_framework/blazor.webassembly.js:1:9841)
          at _mono_wasm_invoke_js_marshalled (https://localhost:44397/_framework/wasm/dotnet.3.2.0.js:1:171294)
          at do_icall (https://localhost:44397/_framework/wasm/dotnet.wasm:wasm-function[6049]:0x10f8b1)
          at do_icall_wrapper (https://localhost:44397/_framework/wasm/dotnet.wasm:wasm-function[1896]:0x50b6a)
          at interp_exec_method (https://localhost:44397/_framework/wasm/dotnet.wasm:wasm-function[1120]:0x2588e)
Microsoft.JSInterop.JSException: Cannot read property 'join' of undefined
TypeError: Cannot read property 'join' of undefined
    at Function.createUserManager (https://localhost:44397/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js:1:6020)
    at Function.initializeCore (https://localhost:44397/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js:1:5035)
    at Function.init (https://localhost:44397/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js:1:4575)
    at https://localhost:44397/_framework/blazor.webassembly.js:1:9873
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://localhost:44397/_framework/blazor.webassembly.js:1:9841)
    at _mono_wasm_invoke_js_marshalled (https://localhost:44397/_framework/wasm/dotnet.3.2.0.js:1:171294)
    at do_icall (https://localhost:44397/_framework/wasm/dotnet.wasm:wasm-function[6049]:0x10f8b1)
    at do_icall_wrapper (https://localhost:44397/_framework/wasm/dotnet.wasm:wasm-function[1896]:0x50b6a)
    at interp_exec_method (https://localhost:44397/_framework/wasm/dotnet.wasm:wasm-function[1120]:0x2588e)
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () <0x2fb4618 + 0x00034> in <filename unknown>:0 
  at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync (Microsoft.JSInterop.IJSRuntime jsRuntime, System.String identifier, System.Object[] args) <0x2db4430 + 0x000e4> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`3[TRemoteAuthenticationState,TAccount,TProviderOptions].EnsureAuthService () <0x2db3a28 + 0x000fc> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`3[TRemoteAuthenticationState,TAccount,TProviderOptions].GetAuthenticatedUser () <0x2db3170 + 0x000d2> in <filename unknown>:0 
  at System.Threading.Tasks.ValueTask`1[TResult].get_Result () <0x2fbe678 + 0x00034> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`3[TRemoteAuthenticationState,TAccount,TProviderOptions].GetUser (System.Boolean useCache) <0x2d94400 + 0x00138> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`3[TRemoteAuthenticationState,TAccount,TProviderOptions].GetAuthenticationStateAsync () <0x2d896f0 + 0x000b6> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.OnParametersSetAsync () <0x2f21070 + 0x00126> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion (System.Threading.Tasks.Task task) <0x2f25b70 + 0x000da> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync () <0x2c75ed0 + 0x001d8> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask (System.Threading.Tasks.Task taskToHandle) <0x2f266b8 + 0x000b6> in <filename unknown>:0

**Comment by javiercn** [comment]
@vibhubanga thanks for contacting us.

Does clearing your browser cache fix the issue?

**Comment by vibhubanga** [comment]
Yeah i tried doing it and tried debugging it using the In-Private Window of Edge too but nothing worked.

**Comment by javiercn** [comment]
@vibhubanga can you check the package version to make sure it is the latest version?

**Comment by vibhubanga** [comment]
The MSAL package was 3.2. This problem only happens with the template being created from VS as below.

![image](https://user-images.githubusercontent.com/5541351/86230968-71bb6980-bbaf-11ea-8d2f-bfa6a9065f52.png)

**Comment by vibhubanga** [comment]
Although after creating the project i removed custom SQL and added MSAL authentication for AAD.

**Comment by javiercn** [comment]
@vibhubanga The option you are selecting is for configuring the application to use Identity Server. For AAD you need to use the command-line.

**Comment by vibhubanga** [comment]
Sure but i removed all the references of Identity Server when i created the project as per the above screenshot. The reason why i did that way was to deploy it as PWA protected by AAD.

**Comment by javiercn** [comment]
@vibhubanga It doesn't matter that you remove the references to Identity Server, the package on the Blazor WebAssembly app that we use for authentication is different than the one we use when we use Identity Server.

**Comment by vibhubanga** [comment]
Ok thanks so in that case what would be the best way to ensure that the command line project is PWA supported because I couldn't find any flag in command line

**Comment by javiercn** [comment]
There is a -pwa flag on the template

**Comment by vibhubanga** [comment]
Thanks!
