### ISSUE TITLE
Can't build asp.net core within WSL

### ISSUE THREAD

**Issue by javiercn** [dotnet/aspnetcore#23565]
I'm trying to try a feature that is specific to WSL and I'm not able to build the repository to test it.

Running ./restore.sh gives this error

```console
warning: Building of C# project is enabled and has dependencies on NodeJS projects. Building of NodeJS projects is enabled since node is detected on PATH.
  Determining projects to restore...
/home/jacalvar/.nuget/packages/microsoft.dotnet.arcade.sdk/5.0.0-beta.20316.1/tools/Tools.proj(43,5): error MSB6003: The specified task executable "sh" could not be run. System.IO.IOException: The operation is not allowed on non-connected sockets.
/home/jacalvar/.nuget/packages/microsoft.dotnet.arcade.sdk/5.0.0-beta.20316.1/tools/Tools.proj(43,5): error MSB6003:    at System.Net.Sockets.NetworkStream..ctor(Socket socket, FileAccess access, Boolean ownsSocket)
/home/jacalvar/.nuget/packages/microsoft.dotnet.arcade.sdk/5.0.0-beta.20316.1/tools/Tools.proj(43,5): error MSB6003:    at System.Diagnostics.Process.OpenStream(Int32 fd, FileAccess access)
/home/jacalvar/.nuget/packages/microsoft.dotnet.arcade.sdk/5.0.0-beta.20316.1/tools/Tools.proj(43,5): error MSB6003:    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
/home/jacalvar/.nuget/packages/microsoft.dotnet.arcade.sdk/5.0.0-beta.20316.1/tools/Tools.proj(43,5): error MSB6003:    at System.Diagnostics.Process.Start()
/home/jacalvar/.nuget/packages/microsoft.dotnet.arcade.sdk/5.0.0-beta.20316.1/tools/Tools.proj(43,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
/home/jacalvar/.nuget/packages/microsoft.dotnet.arcade.sdk/5.0.0-beta.20316.1/tools/Tools.proj(43,5): error MSB6003:    at Microsoft.Build.Tasks.Exec.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
/home/jacalvar/.nuget/packages/microsoft.dotnet.arcade.sdk/5.0.0-beta.20316.1/tools/Tools.proj(43,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.Execute()
Build failed (exit code '1').
```

**Comment by dougbu** [comment]
This sounds like a problem (that I can't find ☹️) reported recently in another repo. IIRC this output follows the real error which is likely a problem downloading the `dotnet-install.sh` script. I suspect the Linux installation you're using under WSL is missing a prerequisite. For example, make sure you've got `openssl` 1.1.1 if using the current `curl` package on Ubuntu 18.04. (Warnings about missing `zlib` are expected and can be safely ignored.)

/fyi I can build  from root under WSL2 / Ubuntu 18.04 with only a couple of issues that may indicate I'm missing something NodeJS-specific.

**Comment by slorello89** [comment]
+1 for @dougbu's point I had the same issue on WSL 1, after upgrading to WSL 2 the build worked for me.

**Comment by javiercn** [comment]
Seems like this was an issue with WSL1. I had to manually run a command to get it updated to WSL2, even though that's what I installed on my box. After a bit of fiddling later, I think I'm able to build
