### ISSUE TITLE
MSB4018	The "ResolveBlazorRuntimeDependencies" task failed unexpectedly"  Blazor.Mono.Runtime.targets line 376

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#23586]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1089367/msb4018-the-resolveblazorruntimedependencies-task.html)._

---
Windows 10 Microsoft Visual Studio Community 2019 Preview Version 16.7.0 Preview 3.0
To duplicate this error:
Select "Create a new project", select "Blazor App", select Blazor WebAssembly App.
Build the App, Clean the App, Pack the App which will produce the following error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "ResolveBlazorRuntimeDependencies" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'BlazorApp1.dll' or one of its dependencies. The system cannot find the file specified.
File name: 'BlazorApp1.dll' ---> System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at System.Reflection.AssemblyName.nGetFileInformation(String s)
   at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
   at Microsoft.AspNetCore.Components.WebAssembly.Build.ResolveBlazorRuntimeDependencies.ResolveRuntimeDependenciesCore(String entryPoint, IEnumerable`1 applicationDependencies, IEnumerable`1 monoBclAssemblies)
   at Microsoft.AspNetCore.Components.WebAssembly.Build.ResolveBlazorRuntimeDependencies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder. <ExecuteInstantiatedTask>d__26.MoveNext()

BlazorApp1	C:\Users\livin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0\targets\Blazor.MonoRuntime.targets	376

---
#### Visual Studio Feedback System on 6/24/2020, 00:03 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by pranavkm** [comment]
Thank you for your feedback. In 3.2, packing a Blazor WebAssembly is unsupported. If you intend to pack a project containing components, we recommend using a Razor Class Library project instead.
