### ISSUE TITLE
ServerRoutingTest.PreventDefault_CanBlockNavigation test quarantined

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#23596]
https://dev.azure.com/dnceng/public/_build/results?buildId=714006&view=ms.vss-test-web.build-test-results-tab&runId=22134430&resultId=100072&paneView=debug

## ShowsErrorNotification_OnError_Reload

```
OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.NotEmptyException: Assert.NotEmpty() Failure
 at Xunit.Assert.NotEmpty(IEnumerable collection) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 331
 at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<Exists>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 69
 at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver ) in //src/Shared/E2ETesting/WaitAssert.cs:line 106
Screen shot captured at 'F:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.AspNetCore.Components.E2ETests\8725fcffabc6408b98d1d8990fab974a.png'
Encountered browser errors
[2020-07-02T02:02:11Z] [Debug] http://127.0.0.1:64204/subdir/_framework/dotnet.5.0.0-preview.6.20305.6.js 0:124605 "mono_wasm_runtime_ready" "fe00e07a-5519-4dfe-b35a-f867dbaf2e28"Page content:
<head>
 <meta charset="utf-8">
 <title>Basic test app</title>
 <base href="/subdir/">
 <link href="style.css" rel="stylesheet">

 
 <link href="_content/TestContentPackage/styles.css" rel="stylesheet">
</head>

<body>
 <root><div id="test-selector">
 Select test:
 <select id="test-selector-select">
 <option value="none">Choose...
 <option value="BasicTestApp.AfterRenderInteropComponent">After-render interop component
 <option value="BasicTestApp.AuthTest.AuthRouter">Auth cases
 <option value="BasicTestApp.BindCasesComponent">bind cases
 <option value="BasicTestApp.ComponentRefComponent">Component ref component
 <option value="BasicTestApp.ConfigurationComponent">Configuration
 <option value="BasicTestApp.CounterComponentUsingChild">Counter using child component
 <option value="BasicTestApp.CulturePicker">Culture Picker
 <option value="BasicTestApp.DispatchingComponent">Dispatching to sync context
 <option value="BasicTestApp.ElementFocusComponent">Element focus component
 <option value="BasicTestApp.ErrorComponent">Error throwing
 <option value="BasicTestApp.EventCallbackTest.EventCallbackCases">EventCallback
 <option value="BasicTestApp.EventDisablingComponent">Event disabling
```

## Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.ServerRoutingTest.PreventDefault_CanBlockNavigation(navigationType: \"internal\", whereToPreventDefault: \"target\")

```
OpenQA.Selenium.StaleElementReferenceException : stale element reference: element is not attached to the page document\n (Session info: headless chrome=83.0.4103.116)\n (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17763 x86_64)
```

## CanBindTextboxNullableDouble

```
OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: -3.14159265359
Actual: 65359
 at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer1 comparer) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\EqualityAsserts.cs:line 40
 at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 80
 at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_01.<WaitAssertCore>b__0(IWebDriver ) in //src/Shared/E2ETesting/WaitAssert.cs:line 106
Screen shot captured at 'F:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.AspNetCore.Components.E2ETests\ff84efe0a706475f801d208c47715456.png'
Encountered browser errors
[2020-07-02T01:58:55Z] [Info] http://127.0.0.1:54318/subdir/_framework/blazor.server.js 0:5679 "[2020-07-02T01:58:55.682Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:54318/subdir/_blazor'."
[2020-07-02T01:58:55Z] [Info] http://127.0.0.1:54318/subdir 40:16 "Blazor server-side"
[2020-07-02T01:58:55Z] [Info] http://127.0.0.1:54318/subdir/_framework/blazor.server.js 0:5679 "[2020-07-02T01:58:55.716Z] Information: WebSocket connected to ws://127.0.0.1:54318/subdir/_blazor?id=NOYiYsi3OGU7-JK4E5ODLA."
[2020-07-02T01:58:56Z] [Info] http://127.0.0.1:54318/subdir/_framework/blazor.server.js 0:5679 "[2020-07-02T01:58:56.275Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:54318/subdir/_blazor'."
[2020-07-02T01:58:56Z] [Info] http://127.0.0.1:54318/subdir 40:16 "Blazor server-side"
[2020-07-02T01:58:56Z] [Info] http://127.0.0.1:54318/subdir/_framework/blazor.server.js 0:5679 "[2020-07-02T01:58:56.297Z] Information: WebSocket connected to ws://127.0.0.1:54318/subdir/_blazor?id=Qu-yiRlzdjo5dRHiPZ3Qxg."
[2020-07-02T01:58:57Z] [Info] http://127.0.0.1:54318/subdir/_framework/blazor.server.js 0:5679 "[2020-07-02T01:58:57.041Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:54318/subdir/_blazor'."
[2020-07-02T01:58:57Z] [Info] http://127.0.0.1:54318/subdir 40:16 "Blazor server-side"
[2020-07-02T01:58:57Z] [Info] http://127.0.0.1:54318/subdir/_framework/blazor.server.js 0:5679 "[2020-07-02T01:58:57.052Z] Information: WebSocket connected to ws://127.0.0.1:54318/subdir/_blazor?id=bg6-ZPmoFIC9w0VTfVNwbA."
[2020-07-02T01:58:57Z] [Info] http://127.0.0.1:54318/subdir/_framework/blazor.server.js 0:5679 "[2020-07-02T01:58:57.616Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:54318/subdir/_blazor'."
[2020-07-02T01:58:57Z] [Info] http://127.0.0.1:54318/subdir 40:16 "Blazor server-side"
[2020-07-02T01:58:57Z] [Info] http://127.0.0.1:54318/subdir/_framework/blazor.server.js 0:5679 "[2020-07-02T01:58:57.642Z] Information: WebSocket connected to ws://127.0.0.1:54318/subdir/_blazor?id=uznrxk0qCHyhhkGm4B0OWg."
[2020-07-02T01:58:59Z] [Info] http://127.0.0.1:54318/subdir/_framework/blazor.server.js 0:5679 "[2020-07-02T01:58:59.350Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:54318/subdir/_blazor'."
[2020-07-02T01:58:59Z] [Info] http://127.0.0.1:54318/subdir 40:16 "Blazor server-side"
[2020-07-02T01:58:59Z] [Info] http://127.0.0.1:54318/subdir/_framework/blazor.server.js 0:5679 "[2020-07-02T01:58:59.376Z] Information: WebSocket connected to ws://127.0.0.1:54318/subdir/_blazor?id=_r5iNIPPc4lQ_kcO_ugYCQ."
[2020-07-02T01:59:01Z] [Info] http://127.0.0.1:54318/subdir/_framework/blazor.server.js 0:5679 "[2020-07-02T01:59:01.148Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:54318/subdir/_blazor'."
[2020-07-02T01:59:01Z] [Info] http://127.0.0.1:54318/subdir 40:16 "Blazor server-side"
[2020-07-02T01:59:01Z] [Info] http://127.0.0.1:54318/subdir/_framework/blazor.server.js 0:5679 "[2020-07-02T01:59:01.165Z] Information: WebSocket connected to ws://127.0.0.1:54318/subdir/_blazor?id=X-Xw3AZWjVlnnhcklqYqtA."
[2020-07-02T01


```

**Comment by HaoK** [comment]
Textbox issue tracked via https://github.com/dotnet/aspnetcore/issues/26285

**Comment by HaoK** [comment]
ShowsErrorNotification_OnError_Reload tracked via https://github.com/dotnet/aspnetcore/issues/26333

**Comment by HaoK** [comment]
CanBlockNavigation test appears to be failing during in Initialize WaitUntilTestSelectorReady in this line:

https://github.com/dotnet/aspnetcore/blob/adddd970f4ab26d79c792ad692db598158660555/src/Components/test/E2ETest/Infrastructure/WebDriverExtensions/BasicTestAppWebDriverExtensions.cs#L21

**Comment by HaoK** [comment]
Tracking this as part of https://github.com/dotnet/aspnetcore/issues/29698
