### ISSUE TITLE
FlakyTest: ContentLengthReadAsyncSingleBytesAtATime

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#23628]
```
[0.002s] [TestLifetime] [Information] Starting test ContentLengthReadAsyncSingleBytesAtATime at 2020-06-30T22:20:39
[0.005s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Debug] Hosting starting
[0.006s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Debug] Hosting started
[0.006s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Debug] Loaded hosting startup assembly testhost
[0.006s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "0HM0T8F5LIPBL" accepted.
[0.006s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "0HM0T8F5LIPBL" started.
[0.007s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request starting HTTP/1.0 POST http:/// - 5
[0.010s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "0HM0T8F5LIPBL", Request id "0HM0T8F5LIPBL:00000002": started reading request body.
[0.012s] [Microsoft.AspNetCore.Server.Kestrel] [Error] Connection id "0HM0T8F5LIPBL", Request id "0HM0T8F5LIPBL:00000002": An unhandled exception was thrown by the application.
Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 3
Actual:   1
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\EqualityAsserts.cs:line 40
   at Xunit.Assert.Equal[T](T expected, T actual) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\EqualityAsserts.cs:line 24
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.RequestTests.<>c__DisplayClass26_0.<<ContentLengthReadAsyncSingleBytesAtATime>b__0>d.MoveNext() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/RequestTests.cs:line 1059
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequest[TContext](IHttpApplication`1 application) in /_/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs:line 659
[0.013s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request finished HTTP/1.0 POST http:/// - 5 - 500 0 - 5.3132ms
[0.013s] [Microsoft.AspNetCore.Server.Kestrel] [Error] Connection id "0HM0T8F5LIPBL", Request id "0HM0T8F5LIPBL:00000002": An unhandled exception was thrown by the application.
Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was aborted by the application.
 ---> System.InvalidOperationException: Reading is already in progress.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.TryReadInternal(ReadResult& readResult) in /_/src/Servers/Kestrel/Core/src/Internal/Http/Http1ContentLengthMessageBody.cs:line 129
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.OnConsumeAsync() in /_/src/Servers/Kestrel/Core/src/Internal/Http/Http1MessageBody.cs:line 47
   --- End of inner exception stack trace ---
[0.013s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "0HM0T8F5LIPBL", Request id "0HM0T8F5LIPBL:00000002": done reading request body.
[0.013s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "0HM0T8F5LIPBL" disconnecting.
[0.013s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "0HM0T8F5LIPBL" stopped.
[30.019s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Debug] Hosting shutdown
[30.022s] [TestLifetime] [Information] Finished test ContentLengthReadAsyncSingleBytesAtATime in 30.0199414s
```

**Comment by BrennanConroy** [comment]
Closed via https://github.com/dotnet/aspnetcore/pull/23641
