### ISSUE TITLE
QuarantinedTest: BlazorWasmStandaloneTemplate_IndividualAuth_Works

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#23639]
https://dev.azure.com/dnceng/public/_build/results?buildId=714955&view=ms.vss-test-web.build-test-results-tab&runId=22159654&resultId=100007&paneView=debug

```
OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.NotEmptyException: Assert.NotEmpty() Failure
   at Xunit.Assert.NotEmpty(IEnumerable collection) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\CollectionAsserts.cs:line 331
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<Exists>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 69
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 106
Screen shot captured at 'F:\\workspace\\_work\\1\\s\\artifacts\\TestResults\\Release\\BlazorTemplates.Tests\\4d4d483d61f44d5f86142ca3643447bf.png'
Encountered browser errors
[2020-07-02T20:51:44Z] [Debug] http://localhost:52317/_framework/dotnet.5.0.0-preview.7.20326.1.js 0:124605 \"mono_wasm_runtime_ready\" \"fe00e07a-5519-4dfe-b35a-f867dbaf2e28\"
[2020-07-02T20:51:44Z] [Info] https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=sample-client-id&redirect_uri=http%3A%2F%2Flocalhost%3A52317%2Fauthentication%2Flogin-callback&response_type=id_token&scope=openid%20profile&state=3a7e6662ac4e478e8ad7ed5d0b16258d&nonce=469d5890dd3845eeaf900ac8988ecd95&prompt=none 73:13657 \"BSSO Telemetry: {\\\"result\\\":\\\"Error\\\",\\\"error\\\":\\\"NoExtension\\\",\\\"type\\\":\\\"ChromeSsoTelemetry\\\",\\\"data\\\":{},\\\"traces\\\":[\\\"BrowserSSO Initialized\\\",\\\"Creating ChromeBrowserCore provider\\\",\\\"Sending message for method CreateProviderAsync\\\",\\\"Received message for method CreateProviderAsync\\\",\\\"Error: ChromeBrowserCore error NoExtension: Extension is not installed.\\\"]}\"
[2020-07-02T20:51:44Z] [Severe] https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=sample-client-id&redirect_uri=http%3A%2F%2Flocalhost%3A52317%2Fauthentication%2Flogin-callback&response_type=id_token&scope=openid%20profile&state=3a7e6662ac4e478e8ad7ed5d0b16258d&nonce=469d5890dd3845eeaf900ac8988ecd95&prompt=none&sso_reload=true 137 Unsafe JavaScript attempt to initiate navigation for frame with URL 'http://localhost:52317/' from frame with URL 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=sample-client-id&redirect_uri=http%3A%2F%2Flocalhost%3A52317%2Fauthentication%2Flogin-callback&response_type=id_token&scope=openid%20profile&state=3a7e6662ac4e478e8ad7ed5d0b16258d&nonce=469d5890dd3845eeaf900ac8988ecd95&prompt=none&sso_reload=true'. The frame attempting navigation is targeting its top-level window, but is neither same-origin with its target nor has it received a user gesture. See https://www.chromestatus.com/features/5851021045661696.

[2020-07-02T20:51:44Z] [Severe] https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=sample-client-id&redirect_uri=http%3A%2F%2Flocalhost%3A52317%2Fauthentication%2Flogin-callback&response_type=id_token&scope=openid%20profile&state=3a7e6662ac4e478e8ad7ed5d0b16258d&nonce=469d5890dd3845eeaf900ac8988ecd95&prompt=none&sso_reload=true 137:325 Uncaught DOMException: Failed to set the 'href' property on 'Location': T…request-id=5f269ce9-80c8-4cde-87a3-745d3ef76000'.
[2020-07-02T20:51:53Z] [Info] http://localhost:52317/_framework/blazor.webassembly.js 0:2753 \"info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]\
      Authorization failed. These requirements were not met:\
      DenyAnonymousAuthorizationRequirement: Requires an authenticated user.\"
[2020-07-02T20:52:00Z] [Debug] https://localhost:52368/_framework/dotnet.5.0.0-preview.7.20326.1.js 0:124605 \"mono_wasm_runtime_ready\" \"fe00e07a-5519-4dfe-b35a-f867dbaf2e28\"
[2020-07-02T20:52:00Z] [Severe] https://localhost:52368/_framework/blazor.webassembly.js 0:40764 RangeError: Maximum call stack size exceeded
    at mono_class_get_first_method_idx (https://localhost:52368/_framework/dotnet.wasm:wasm-function[603]:0x12964)
    at mono_find_method_in_metadata (https://localhost:52368/_framework/dotnet.wasm:wasm-function[2286]:0x605f2)
    at mono_class_get_method_from_name_checked (https://localhost:52368/_framework/dotnet.wasm:wasm-function[198]:0x50bd)
    at mono_class_get_cctor (https://localhost:52368/_framework/dotnet.wasm:wasm-function[1566]:0x42b21)
    at mono_runtime_class_init_full (https://localhost:52368/_framework/dotnet.wasm:wasm-function[233]:0x5c71)
    at mono_interp_transform_method (https://localhost:52368/_framework/dotnet.wasm:wasm-function[1144]:0x24a96)
    at do_transform_method (https://localhost:52368/_framework/dotnet.wasm:wasm-function[2694]:0x7e075)
    at interp_exec_method (https://localhost:52368/_framework/dotnet.wasm:wasm-function[1224]:0x353df)
    at interp_runtime_invoke (https://localhost:52368/_framework/dotnet.wasm:wasm-function[4966]:0xceb93)
    at mono_jit_runtime_invoke (https://localhost:52368/_framework/dotnet.wasm:wasm-function[4466]:0xb8932)

Page content:
<head>
    <meta charset=\"utf-8\">
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">
    <title>AspNet.offwtaofawy</title>
    <base href=\"/\">
    <link href=\"css/bootstrap/bootstrap.min.css\" rel=\"stylesheet\">
    <link href=\"css/app.css\" rel=\"stylesheet\">
</head>

<body>
    <app>Loading...</app>

    <div id=\"blazor-error-ui\" style=\"display: block;\">
        An unhandled error has occurred.
        <a href=\"\" class=\"reload\">Reload</a>
        <a class=\"dismiss\">??</a>
    </div>
    <script src=\"_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js\"></script>
    <script src=\"_framework/blazor.webassembly.js\"></script>



<script type=\"text/javascript\">var Module; window.__wasmmodulecallback__(); delete window.__wasmmodulecallback__;</script><script src=\"_framework/dotnet.5.0.0-preview.7.20326.1.js\" defer=\"\" integrity=\"sha256-NInsB2Gm0V2B80TQrCgo8y9wzIddZvMysAFwSpIaejo=\" crossorigin=\"anonymous\"></script></body>

---- Assert.NotEmpty() Failure
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 126
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.Exists(IWebDriver driver, By finder, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 64
   a
```

**Comment by pranavkm** [comment]
@lewing should I file an issue for this:

```
 at mono_find_method_in_metadata (https://localhost:52368/_framework/dotnet.wasm:wasm-function[2286]:0x605f2)
    at mono_class_get_method_from_name_checked (https://localhost:52368/_framework/dotnet.wasm:wasm-function[198]:0x50bd)
    at mono_class_get_cctor (https://localhost:52368/_framework/dotnet.wasm:wasm-function[1566]:0x42b21)
    at mono_runtime_class_init_full (https://localhost:52368/_framework/dotnet.wasm:wasm-function[233]:0x5c71)
    at mono_interp_transform_method (https://localhost:52368/_framework/dotnet.wasm:wasm-function[1144]:0x24a96)
    at do_transform_method (https://localhost:52368/_framework/dotnet.wasm:wasm-function[2694]:0x7e075)
    at interp_exec_method (https://localhost:52368/_framework/dotnet.wasm:wasm-function[1224]:0x353df)
    at interp_runtime_invoke (https://localhost:52368/_framework/dotnet.wasm:wasm-function[4966]:0xceb93)
    at mono_jit_runtime_invoke (https://localhost:52368/_framework/dotnet.wasm:wasm-function[4466]:0xb8932)

**Comment by lewing** [comment]
cc @vargaz

**Comment by HaoK** [comment]
Fixed by https://github.com/dotnet/aspnetcore/pull/27948
