### ISSUE TITLE
Quarantined test: BuildingProject_CopyToOutputDirectoryFiles

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#23635]
```
System.TimeoutException : command '$/Users/runner/runners/2.171.1/work/1/s/.dotnet/dotnet msbuild /nr:false /bl /p:RunningAsTest=true /p:MicrosoftNETCoreAppRuntimeVersion=5.0.0-preview.8.20351.9 /p:MicrosoftNetCompilersToolsetPackageVersion=3.7.0-4.20319.6 /p:RazorSdkDirectoryRoot=/Users/runner/runners/2.171.1/work/1/s/artifacts/bin/Microsoft.NET.Sdk.Razor/Release/sdk-output/ /p:RepoRoot=/Users/runner/runners/2.171.1/work/1/s/ /p:_RazorBuildServerPipeName="64f550ae-2cad-4ffc-b256-f8656dc29246" /t:Build /p:Configuration=Release ' timed out after 00:05:00. Output: Microsoft (R) Build Engine version 16.7.0-preview-20309-02+d6862eb21 for .NET\nCopyright (C) Microsoft Corporation. All rights reserved.\n\n/Users/runner/runners/2.171.1/work/1/s/.dotnet/sdk/5.0.100-preview.6.20310.4/MSBuild.dll -maxcpucount -verbosity:m /bl /nr:false /p:RunningAsTest=true /p:MicrosoftNETCoreAppRuntimeVersion=5.0.0-preview.8.20351.9 /p:MicrosoftNetCompilersToolsetPackageVersion=3.7.0-4.20319.6 /p:RazorSdkDirectoryRoot=/Users/runner/runners/2.171.1/work/1/s/artifacts/bin/Microsoft.NET.Sdk.Razor/Release/sdk-output/ /p:RepoRoot=/Users/runner/runners/2.171.1/work/1/s/ /p:_RazorBuildServerPipeName=64f550ae-2cad-4ffc-b256-f8656dc29246 /p:Configuration=Release /t:Build ./SimpleMvc21.csproj\n You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview\n
```

```
  at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.<>c__DisplayClass2_0.<<RunProcessCoreAsync>g__GetTimeoutForProcess|3>d.MoveNext() in /_/src/Razor/Microsoft.NET.Sdk.Razor/integrationtests/MSBuildProcessManager.cs:line 220
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.RunProcessAsync(ProjectDirectory project, String arguments, Nullable`1 timeout, MSBuildProcessKind msBuildProcessKind) in /_/src/Razor/Microsoft.NET.Sdk.Razor/integrationtests/MSBuildProcessManager.cs:line 122
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MvcBuildIntegrationTestLegacy.BuildingProject_CopyToOutputDirectoryFiles() in /_/src/Razor/Microsoft.NET.Sdk.Razor/integrationtests/MvcBuildIntegrationTestLegacy.cs:line 64
--- End of stack trace from previous location ---
```

**Comment by HaoK** [comment]
This was already fixed as part of https://github.com/dotnet/aspnetcore/issues/23756
