### ISSUE TITLE
Investigate Microsoft.AspNetCore.Razor.Design.IntegrationTests test failures

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#23756]
E.g. for `Publish_WithLinkerAndCompression_IsIncremental` in https://dev.azure.com/dnceng/public/_build/results?buildId=716889:
``` text
Error message
System.TimeoutException : command '$/Users/runner/runners/2.171.1/work/1/s/.dotnet/dotnet msbuild /nr:false /bl /p:RunningAsTest=true /p:MicrosoftNETCoreAppRuntimeVersion=5.0.0-preview.8.20352.6 /p:MicrosoftNetCompilersToolsetPackageVersion=3.7.0-4.20319.6 /p:RazorSdkDirectoryRoot=/Users/runner/runners/2.171.1/work/1/s/artifacts/bin/Microsoft.NET.Sdk.Razor/Release/sdk-output/ /p:RepoRoot=/Users/runner/runners/2.171.1/work/1/s/ /p:Configuration=Release /t:publish ' timed out after 00:05:00. Output: Microsoft (R) Build Engine version 16.7.0-preview-20330-02+1eab2845b for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

/Users/runner/runners/2.171.1/work/1/s/.dotnet/sdk/5.0.100-preview.7.20330.3/MSBuild.dll -maxcpucount -verbosity:m /bl /nr:false /p:RunningAsTest=true /p:MicrosoftNETCoreAppRuntimeVersion=5.0.0-preview.8.20352.6 /p:MicrosoftNetCompilersToolsetPackageVersion=3.7.0-4.20319.6 /p:RazorSdkDirectoryRoot=/Users/runner/runners/2.171.1/work/1/s/artifacts/bin/Microsoft.NET.Sdk.Razor/Release/sdk-output/ /p:RepoRoot=/Users/runner/runners/2.171.1/work/1/s/ /p:Configuration=Release /t:publish ./blazorhosted.csproj
 You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
 You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
 RazorClassLibrary -> /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Razor/5r30lmox.cy2/razorclasslibrary/bin/Release/netstandard2.1/RazorClassLibrary.dll
 blazorwasm -> /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Razor/5r30lmox.cy2/blazorwasm/bin/Release/net5.0/blazorwasm.dll
 blazorwasm (Blazor output) -> /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Razor/5r30lmox.cy2/blazorwasm/bin/Release/net5.0/wwwroot
 blazorhosted -> /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Razor/5r30lmox.cy2/blazorhosted/bin/Release/net5.0/blazorhosted.dll
 Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
 Compressing Blazor WebAssembly publish artifacts. This may take a while...
 blazorhosted -> /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Razor/5r30lmox.cy2/blazorhosted/bin/Release/net5.0/publish/


Stack trace
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.<>c__DisplayClass2_0.<<RunProcessCoreAsync>g__GetTimeoutForProcess|3>d.MoveNext() in /_/src/Razor/Microsoft.NET.Sdk.Razor/integrationtests/MSBuildProcessManager.cs:line 220
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.RunProcessAsync(ProjectDirectory project, String arguments, Nullable`1 timeout, MSBuildProcessKind msBuildProcessKind) in /_/src/Razor/Microsoft.NET.Sdk.Razor/integrationtests/MSBuildProcessManager.cs:line 122
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.WasmCompressionTests.Publish_WithLinkerAndCompression_IsIncremental() in /_/src/Razor/Microsoft.NET.Sdk.Razor/integrationtests/Wasm/WasmCompressionTests.cs:line 88
--- End of stack trace from previous location ---
```

Failed on macOS.

**Comment by dougbu** [comment]
Other tests failed with similar errors:
- `PublishHostedWithPWA_ProducesAssets`
- `Publish_HostedApp_ProducesBootJsonDataWithExpectedContent`
- `Clean_Success_RemovesManifestAndCache`
- `BuildingProject_CopyToOutputDirectoryFiles`
- `Publish_IncludesRefAssemblies_WhenCopyRefAssembliesToPublishDirectoryIsSet`
- `Publish_SatelliteAssemblies_AreCopiedToBuildOutput`

**Comment by dougbu** [comment]
Additional timeouts of these tests in other recent builds, also on macOS:
- `BuildingProject_CopyToOutputDirectoryFiles` in https://dev.azure.com/dnceng/public/_build/results?buildId=717119
- `Publish_IncludesRefAssemblies_WhenCopyRefAssembliesToPublishDirectoryIsSet` in https://dev.azure.com/dnceng/public/_build/results?buildId=717756

**Comment by dougbu** [comment]
Likely related to #23635 because @pranavkm quarantined `BuildingProject_CopyToOutputDirectoryFiles` in #23636. Showed up here because that PR wasn't merged 'til yesterday.

**Comment by BrennanConroy** [comment]
More in https://dev.azure.com/dnceng/public/_build/results?buildId=777340&view=ms.vss-test-web.build-test-results-tab&runId=24327666&paneView=debug&resultId=100014
`Publish_LazyLoadExplicitAssembly_Debug_Works`
`Publish_InRelease_Works`
`Publish_WithoutLinkerAndCompression_IsIncremental`

**Comment by pranavkm** [comment]
These tests were re-enabled after observing they haven' been failing for > 1 month. The tests now use `dotnet test` hang features to detect hangs and capture crash dumps.
