### ISSUE TITLE
Investigate E2ETesting test failures

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#23757]
Selenium test `PreventDefaultCanBlockKeystrokes` failed in https://dev.azure.com/dnceng/public/_build/results?buildId=716988 in Windows test job:
``` text
OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: a
Actual: ab
 at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer1 comparer) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\EqualityAsserts.cs:line 40
 at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 80
 at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_01.<WaitAssertCore>b__0(IWebDriver ) in //src/Shared/E2ETesting/WaitAssert.cs:line 106
Screen shot captured at 'F:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.AspNetCore.Components.E2ETests\249a4f68d9fa4ac885df063867501d7b.png'
Encountered browser errors
[2020-07-06T05:46:42Z] [Info] http://127.0.0.1:52111/subdir/_framework/blazor.server.js 0:5679 "[2020-07-06T05:46:42.455Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:52111/subdir/_blazor'."
[2020-07-06T05:46:42Z] [Info] http://127.0.0.1:52111/subdir 40:16 "Blazor server-side"
[2020-07-06T05:46:42Z] [Info] http://127.0.0.1:52111/subdir/_framework/blazor.server.js 0:5679 "[2020-07-06T05:46:42.608Z] Information: WebSocket connected to ws://127.0.0.1:52111/subdir/_blazor?id=Y3QCD6AxlUihPRQXli8JkA."
[2020-07-06T05:46:44Z] [Info] http://127.0.0.1:52111/subdir/_framework/blazor.server.js 0:5679 "[2020-07-06T05:46:44.072Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:52111/subdir/_blazor'."
[2020-07-06T05:46:44Z] [Info] http://127.0.0.1:52111/subdir 40:16 "Blazor server-side"
[2020-07-06T05:46:44Z] [Info] http://127.0.0.1:52111/subdir/_framework/blazor.server.js 0:5679 "[2020-07-06T05:46:44.093Z] Information: WebSocket connected to ws://127.0.0.1:52111/subdir/_blazor?id=Un1GLOykYkQbjoQXFHIYYw."Page content:
<head>
 <meta charset="utf-8">
 <title>Basic test app</title>
 <base href="/subdir/">
 <link href="style.css" rel="stylesheet">
 <link href="_content/TestContentPackage/styles.css" rel="stylesheet">
</head>
<body>
 <root><div id="test-selector">
 Select test:
 <select id="test-selector-select"><option value="none">Choose...
 <option value="BasicTestApp.AfterRenderInteropComponent">After-render interop component
 <option value="BasicTestApp.AuthTest.AuthRouter">Auth cases
 <option value="BasicTestApp.BindCasesComponent">bind cases
 <option value="BasicTestApp.ComponentRefComponent">Component ref component
 <option value="BasicTestApp.ConfigurationComponent">Configuration
 <option value="

Stack trace
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 126
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore(IWebDriver driver, Action assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 80
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.Equal[T](IWebDriver driver, T expected, Func`1 actual) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 24
   at Microsoft.AspNetCore.Components.E2ETest.Tests.EventBubblingTest.PreventDefaultCanBlockKeystrokes() in /_/src/Components/test/E2ETest/Tests/EventBubblingTest.cs:line 182
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 80
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 106
```

And, `InputEvent_RespondsOnKeystrokes_EvenIfUpdatesAreLaggy` failed in https://dev.azure.com/dnceng/public/_build/results?buildId=718345:
``` text
OpenQA.Selenium.StaleElementReferenceException : stale element reference: element is not attached to the page document
 (Session info: headless chrome=83.0.4103.116)
 (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17763 x86_64)

Stack trace
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.Execute(String commandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.SendKeys(String text)
   at Microsoft.AspNetCore.Components.E2ETest.Tests.EventTest.SendKeysSequentially(IWebElement target, String text) in /_/src/Components/test/E2ETest/Tests/EventTest.cs:line 247
   at Microsoft.AspNetCore.Components.E2ETest.Tests.EventTest.InputEvent_RespondsOnKeystrokes_EvenIfUpdatesAreLaggy() in /_/src/Components/test/E2ETest/Tests/EventTest.cs:line 203
```

**Comment by mkArtakMSFT** [comment]
Let's bump up the timeout values for these tests as these are failing due to timeouts. And without changing in code these started to fail on their own.
