### ISSUE TITLE
Flaky test RunsWithNoRestoreOnOrdinaryFileChanges and RunsWithRestoreIfCsprojChanges

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#23854]
Added an additional wait in both tests to possibly fix the flakiness, but still quarantining them.

```
[xUnit.net 00:06:07.17]     Microsoft.DotNet.Watcher.Tools.FunctionalTests.DotNetWatcherTests.RunsWithRestoreIfCsprojChanges [FAIL]
[xUnit.net 00:06:07.17]       System.Threading.Tasks.TaskCanceledException : A task was canceled.
[xUnit.net 00:06:07.17]       Stack Trace:
[xUnit.net 00:06:07.17]         /_/src/Tools/dotnet-watch/test/AwaitableProcess.cs(103,0): at Microsoft.DotNet.Watcher.Tools.FunctionalTests.AwaitableProcess.GetOutputLineAsync(String predicateName, Predicate`1 predicate, CancellationToken cancellationToken)
[xUnit.net 00:06:07.17]         /_/src/Tools/dotnet-watch/test/AwaitableProcess.cs(96,0): at Microsoft.DotNet.Watcher.Tools.FunctionalTests.AwaitableProcess.GetOutputLineStartsWithAsync(String message, TimeSpan timeout)
[xUnit.net 00:06:07.17]         /_/src/Tools/dotnet-watch/test/DotNetWatcherTests.cs(90,0): at Microsoft.DotNet.Watcher.Tools.FunctionalTests.DotNetWatcherTests.RunsWithRestoreIfCsprojChanges()
[xUnit.net 00:06:07.17]         --- End of stack trace from previous location ---
[xUnit.net 00:06:07.17]       Output:
[xUnit.net 00:06:07.17]         The temporary test folder is /root/helix/work/workitem/tmp/l52tmyyt.hws
[xUnit.net 00:06:07.17]         Copying project /root/helix/work/workitem/TestProjects/KitchenSink to /root/helix/work/workitem/tmp/l52tmyyt.hws/KitchenSink
[xUnit.net 00:06:07.17]         Restoring msbuild project in KitchenSink
[xUnit.net 00:06:07.17]         Project directory: '/root/helix/work/workitem/tmp/l52tmyyt.hws/KitchenSink'
[xUnit.net 00:06:07.17]         Started process 2084: /root/helix/work/workitem/.dotnet29020/dotnet restore --ignore-failed-sources
[xUnit.net 00:06:07.17]           Determining projects to restore...
[xUnit.net 00:06:07.17]           Restored /root/helix/work/workitem/tmp/l52tmyyt.hws/KitchenSink/KitchenSink.csproj (in 278 ms).
[xUnit.net 00:06:07.17]         
[xUnit.net 00:06:07.17]         
[xUnit.net 00:06:07.17]         Process exited 2084
[xUnit.net 00:06:07.17]         Process exited 2084 with code 0
[xUnit.net 00:06:07.17]         Building KitchenSink
[xUnit.net 00:06:07.17]         Project directory: '/root/helix/work/workitem/tmp/l52tmyyt.hws/KitchenSink'
[xUnit.net 00:06:07.17]         Started process 2131: /root/helix/work/workitem/.dotnet29020/dotnet build
[xUnit.net 00:06:07.17]         Microsoft (R) Build Engine version 16.7.0-preview-20330-02+1eab2845b for .NET
[xUnit.net 00:06:07.17]         Copyright (C) Microsoft Corporation. All rights reserved.
[xUnit.net 00:06:07.17]         
[xUnit.net 00:06:07.17]           Determining projects to restore...
[xUnit.net 00:06:07.17]           All projects are up-to-date for restore.
[xUnit.net 00:06:07.17]           You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
[xUnit.net 00:06:07.17]           KitchenSink -> /root/helix/work/workitem/tmp/l52tmyyt.hws/KitchenSink/.net/bin/Debug/net5.0/KitchenSink.dll
[xUnit.net 00:06:07.17]         
[xUnit.net 00:06:07.17]         Build succeeded.
[xUnit.net 00:06:07.17]             0 Warning(s)
[xUnit.net 00:06:07.17]             0 Error(s)
[xUnit.net 00:06:07.17]         
[xUnit.net 00:06:07.17]         Time Elapsed 00:00:03.85
[xUnit.net 00:06:07.17]         
[xUnit.net 00:06:07.17]         
[xUnit.net 00:06:07.17]         Process exited 2131
[xUnit.net 00:06:07.18]         Process exited 2131 with code 0
[xUnit.net 00:06:07.18]         7/10/2020 12:39:51 PM: starting process: 'dotnet /root/helix/work/workitem/tool/dotnet-watch.dll --verbose run -- wait'
[xUnit.net 00:06:07.18]         7/10/2020 12:39:51 PM: process started: 'dotnet /root/helix/work/workitem/tool/dotnet-watch.dll --verbose run -- wait'
[xUnit.net 00:06:07.18]         Waiting for output line [msg == 'Started']. Will wait for 120 sec.
[xUnit.net 00:06:07.18]         7/10/2020 12:39:51 PM: post: 'watch : Evaluating dotnet-watch file set.'
[xUnit.net 00:06:07.18]         7/10/2020 12:39:51 PM: recv: 'watch : Evaluating dotnet-watch file set.'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:06:07.18]         7/10/2020 12:39:51 PM: post: 'watch : Running MSBuild target 'GenerateWatchList' on '/root/helix/work/workitem/tmp/l52tmyyt.hws/KitchenSink/KitchenSink.csproj''
[xUnit.net 00:06:07.18]         7/10/2020 12:39:51 PM: recv: 'watch : Running MSBuild target 'GenerateWatchList' on '/root/helix/work/workitem/tmp/l52tmyyt.hws/KitchenSink/KitchenSink.csproj''. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:06:07.18]         7/10/2020 12:39:51 PM: post: 'watch : Started '/root/helix/work/workitem/.dotnet29020/dotnet' with process id 2197'
[xUnit.net 00:06:07.18]         7/10/2020 12:39:51 PM: recv: 'watch : Started '/root/helix/work/workitem/.dotnet29020/dotnet' with process id 2197'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:06:07.18]         7/10/2020 12:39:53 PM: post: 'watch : Process id 2197 ran for 1884ms'
[xUnit.net 00:06:07.18]         7/10/2020 12:39:53 PM: recv: 'watch : Process id 2197 ran for 1884ms'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:06:07.18]         7/10/2020 12:39:53 PM: post: 'watch : Watching 2 file(s) for changes'
[xUnit.net 00:06:07.18]         7/10/2020 12:39:53 PM: recv: 'watch : Watching 2 file(s) for changes'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:06:07.18]         7/10/2020 12:39:53 PM: post: 'watch : Watch command can be configured to use --no-restore.'
[xUnit.net 00:06:07.18]         7/10/2020 12:39:53 PM: recv: 'watch : Watch command can be configured to use --no-restore.'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:06:07.18]         7/10/2020 12:39:53 PM: post: 'watch : No restore arguments: run --no-restore -- wait'
[xUnit.net 00:06:07.18]         7/10/2020 12:39:53 PM: recv: 'watch : No restore arguments: run --no-restore -- wait'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:06:07.18]         7/10/2020 12:39:53 PM: post: 'watch : Started '/root/helix/work/workitem/.dotnet29020/dotnet' with process id 2242'
[xUnit.net 00:06:07.18]         7/10/2020 12:39:53 PM: recv: 'watch : Started '/root/helix/work/workitem/.dotnet29020/dotnet' with process id 2242'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:06:07.18]         7/10/2020 12:39:53 PM: post: 'watch : Running dotnet with the following arguments: run -- wait'
[xUnit.net 00:06:07.18]         7/10/2020 12:39:53 PM: recv: 'watch : Running dotnet with the following arguments: run -- wait'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:06:07.18]         7/10/2020 12:39:53 PM: post: 'watch : Started'
[xUnit.net 00:06:07.18]         7/10/2020 12:39:53 PM: recv: 'watch : Started'. Does not match condition '[msg == 'Started']'.
[xUnit.net 00:06:07.18]         7/10/2020 12:39:58 PM: post: 'Started'
[xUnit.net 00:06:07.18]         7/10/2020 12:39:58 PM: recv: 'Started'. Matches condition '[msg == 'Started']'.
[xUnit.net 00:06:07.18]         Waiting for output line [msg.StartsWith('watch : Running dotnet with the following arguments: run')]. Will wait for 120 sec.
[xUnit.net 00:06:07.18]         7/10/2020 12:39:58 PM: post: 'watch : Killing process 2242'
[xUnit.net 00:06:07.18]         7/10/2020 12:39:58 PM: recv: 'watch : Killing process 2242'. Does not match condition '[msg.StartsWith('watch : Running dotnet with the following arguments: run')]'.
[xUnit.net 00:06:07.18]         7/10/2020 12:39:58 PM: post: 'Process identifier = 2290, 12:39:58.15'
[xUnit.net 00:06:07.18]         7/10/2020 12:39:58 PM: post: 'DOTNET_WATCH = 1'
[xUnit.net 00:06:07.18]         7/10/2020 12:39:58 PM: post: 'DOTNET_WATCH_ITERATION = 1'
[xUnit.net 00:06:07.18]         7/10/2020 12:39:58 PM: post: 'Waiting for process to be terminated.'
[xUnit.net 00:06:07.18]         7/10/2020 12:39:58 PM: recv: 'Process identifier = 2290, 12:39:58.15'. Does not match condition '[msg.StartsWith('watch : Running dotnet with the following arguments: run')]'.
[xUnit.net 00:06:07.18]         7/10/2020 12:39:58 PM: recv: 'DOTNET_WATCH = 1'. Does not match condition '[msg.StartsWith('watch : Running dotnet with the following arguments: run')]'.
[xUnit.net 00:06:07.18]         7/10/2020 12:39:58 PM: recv: 'DOTNET_WATCH_ITERATION = 1'. Does not match condition '[msg.StartsWith('watch : Running dotnet with the following arguments: run')]'.
[xUnit.net 00:06:07.18]         7/10/2020 12:39:58 PM: recv: 'Waiting for process to be terminated.'. Does not match condition '[msg.StartsWith('watch : Running dotnet with the following arguments: run')]'.
[xUnit.net 00:06:07.18]         Disposing WatchableApp
```

**Comment by mkArtakMSFT** [comment]
Closed as this test has been moved to the SDK repo.
