### ISSUE TITLE
websocket server, the stress test throws this exception!

### ISSUE THREAD

**Issue by xlievo** [dotnet/aspnetcore#23865]
asp.net core 3.1
concurrent test of 1000000 send & response

[02:16:36 FTL] System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync(MessageOpcode opcode, Boolean endOfMessage, ReadOnlyMemory`1 payloadBuffer, CancellationToken cancellationToken)

**Comment by BrennanConroy** [comment]
Can you share your test code both client and server?

**Comment by xlievo** [comment]
sorry to reply so late!
My use cases are part of a large framework that is difficult to break down.

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at System.Net.WebSockets.ManagedWebSocket.SendFrameLockAcquiredNonCancelableAsync(MessageOpcode opcode, Boolean endOfMessage, ReadOnlyMemory`1 payloadBuffer)

The good news is that if you put concurrent data into the queue and call SendAsync, it won't fail in a few hours.
This seems to be inconsistent with the following description

https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs
/// Thread-safety:
/// - It's acceptable to call ReceiveAsync and SendAsync in parallel.  One of each may run concurrently.
internal sealed partial class ManagedWebSocket { }

finally, I will continue to decompose the exception use cases, hope to be able to do it!

**Comment by davidfowl** [comment]
cc @stephentoub
