### ISSUE TITLE
 System.ArgumentNullException: Value cannot be null. Parameter name: routeData    at Microsoft.AspNetCore.Mvc.ActionContext..ctor(HttpContext httpContext, RouteData routeData, ActionDescriptor actionDescriptor, ModelStateDictionary modelState)    at Microsoft.AspNetCore.Mvc.Internal.MvcEndpointDataSource.<>c__DisplayClass21_0.<CreateEndpoint>b__0(HttpContext context)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>d__3.MoveNext()

### ISSUE THREAD

**Issue by pranem** [dotnet/aspnetcore#23940]
### Describe the bug
every so often on our production code we see the below error - and requests fail with 500 - do you know why it might be?

Unknown error occured.

System.ArgumentNullException: Value cannot be null.
Parameter name: routeData
   at Microsoft.AspNetCore.Mvc.ActionContext..ctor(HttpContext httpContext, RouteData routeData, ActionDescriptor actionDescriptor, ModelStateDictionary modelState)
   at Microsoft.AspNetCore.Mvc.Internal.MvcEndpointDataSource.<>c__DisplayClass21_0.<CreateEndpoint>b__0(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.AppConfiguration.AspNetCore.AzureAppConfigurationRefreshMiddleware.<InvokeAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AIBuilder.Platform.Proxy.Middlewares.CognitiveExceptionHanlder.<Invoke>d__3.MoveNext() in C:\source\src\AIBuilder.Platform.Proxy\Middlewares\CognitiveExceptionHanlder.cs:line 42
   
   -------------------------------------------------------------------

### To Reproduce
dont have a repro as cant tell what causes this to happen 

### Exceptions (if any)
System.ArgumentNullException: Value cannot be null.
Parameter name: routeData
   at Microsoft.AspNetCore.Mvc.ActionContext..ctor(HttpContext httpContext, RouteData routeData, ActionDescriptor actionDescriptor, ModelStateDictionary modelState)
   at Microsoft.AspNetCore.Mvc.Internal.MvcEndpointDataSource.<>c__DisplayClass21_0.<CreateEndpoint>b__0(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>d__3.MoveNext()

### Further technical details
- ASP.NET Core version 2.2 
- Include the output of `dotnet --info` - cant run this on our production server. 
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by Rick-Anderson** [comment]
Can you set the logging level of `Microsoft.AspNetCore.Routing` to `TRACE` and check the logs when that happens? 2.2 is out of support, do you plan to migrate to 3.1?

**Comment by javiercn** [comment]
@pranem thanks for contacting us.

As @Rick-Anderson commented, asp.net core 2.2 is out of support, so we suggest you either move to a update your app to a supported version.

I would suggest you update to 3.1 and let us know if you still have this issue.

**Comment by mkArtakMSFT** [comment]
It looks like the version of the framework you're using is outdated and is not supported any more.
Consider upgrading to a newer supported version of the framework to make sure it's secure and you get all the new features.
You can learn more about the .NET Core support policy at https://dotnet.microsoft.com/platform/support/policy/dotnet-core
