### ISSUE TITLE
Hanging tests MvcTemplate_RazorRuntimeCompilation_BuildsAndPublishes and Template_Produces_The_Right_Set_Of_FilesAsync

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#23993]
```
[xUnit.net 00:15:55.56] ProjectTemplates.Tests: [Long Running Test] 'Templates.Test.BaselineTest.Template_Produces_The_Right_Set_Of_FilesAsync(arguments: "new razor -au Individual", expectedFiles: ["app.db", "appsettings.Development.json", "appsettings.json", "Program.cs", "Startup.cs", ...])', Elapsed: 00:12:13
[Long Running Test] 'Templates.Test.MvcTemplateTest.MvcTemplate_RazorRuntimeCompilation_BuildsAndPublishes', Elapsed: 00:12:01
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.AggregateException: One or more errors occurred. (Cannot process request because the process (14604) has exited.)
 ---> System.InvalidOperationException: Cannot process request because the process (14604) has exited.
   at System.Diagnostics.Process.ThrowIfExited(Boolean refresh)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ProcessName()
   at Microsoft.AspNetCore.Internal.ProcessEx.<>c__DisplayClass13_0.<.ctor>b__0() in /_/src/Shared/Process/ProcessEx.cs:line 55
   at System.Threading.CancellationToken.<>c.<.cctor>b__26_0(Object obj)
   at System.Threading.CancellationTokenSource.CallbackNode.<>c.<ExecuteCallback>b__9_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
Unhandled exception. System.AggregateException: One or more errors occurred. (Cannot process request because the process (14910) has exited.)
 ---> System.InvalidOperationException: Cannot process request because the process (14910) has exited.
   at System.Diagnostics.Process.ThrowIfExited(Boolean refresh)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ProcessName()
   at Microsoft.AspNetCore.Internal.ProcessEx.<>c__DisplayClass13_0.<.ctor>b__0() in /_/src/Shared/Process/ProcessEx.cs:line 55
   at System.Threading.CancellationToken.<>c.<.cctor>b__26_0(Object obj)
   at System.Threading.CancellationTokenSource.CallbackNode.<>c.<ExecuteCallback>b__9_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   --- End of inner exception stack trace ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

https://dev.azure.com/dnceng/public/_build/results?buildId=730760&view=ms.vss-test-web.build-test-results-tab&runId=22604528&resultId=121668&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by Tratcher** [comment]
Note this is currently the flakiest test. It's failed on master for 100% of 132 runs in the last 14 days. Prioritize accordingly.

**Comment by Tratcher** [comment]
Actually, the failure is different now.
```
[xUnit.net 00:02:40.23]     Templates.Test.BaselineTest.Template_Produces_The_Right_Set_Of_FilesAsync(arguments: "new blazorserver -au Windows", expectedFiles: ["App.razor", "appsettings.Development.json", "appsettings.json", "Program.cs", "Startup.cs", ...]) [FAIL]
[xUnit.net 00:02:40.23]       Assert.Contains() Failure
[xUnit.net 00:02:40.23]       Not found: Pages/Error.cshtml.cs
[xUnit.net 00:02:40.23]       In value:  String[] ["App.razor", "appsettings.Development.json", "appsettings.json", "Program.cs", "Startup.cs", ...]
[xUnit.net 00:02:40.23]       Stack Trace:
[xUnit.net 00:02:40.23]         /_/src/ProjectTemplates/test/BaselineTest.cs(105,0): at Templates.Test.BaselineTest.Template_Produces_The_Right_Set_Of_FilesAsync(String arguments, String[] expectedFiles)
```
