### ISSUE TITLE
Flaky tests in BlazorWasmTemplateTest

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#23992]
####  Templates.Test.BlazorWasmTemplateTest.BlazorWasmHostedPwaTemplate_Works 

```
      OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL http://localhost:50945/wd/hub/session/c6a977b01d306caa0c61117a51f361e9/url timed out after 60 seconds.
      ---- System.Net.WebException : The operation has timed out.
      Stack Trace:
           at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
           at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
           at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
           at OpenQA.Selenium.Remote.RemoteWebDriver.set_Url(String value)
           at OpenQA.Selenium.Remote.RemoteNavigator.GoToUrl(Uri url)
        /_/src/ProjectTemplates/Shared/AspNetProcess.cs(87,0): at Templates.Test.Helpers.AspNetProcess.VisitInBrowser(IWebDriver driver)
        /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorWasmTemplateTest.cs(463,0): at Templates.Test.BlazorWasmTemplateTest.BuildAndRunTest(String appName, Project project, Boolean usesAuth)
        /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorWasmTemplateTest.cs(189,0): at Templates.Test.BlazorWasmTemplateTest.BlazorWasmHostedPwaTemplate_Works()
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace -----
           at System.Net.HttpWebRequest.GetResponse()
           at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)

```

#### Templates.Test.BlazorWasmTemplateTest.BlazorWasmHostedTemplate_IndividualAuth_Works_WithLocalDB 

```
      OpenQA.Selenium.NoSuchElementException : no such element: Unable to locate element: {"method":"partial link text","selector":"Fetch data"}
  (Session info: headless chrome=84.0.4147.89)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17763 x86_64)
      Stack Trace:
           at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
           at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
           at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
           at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByPartialLinkText(String partialLinkText)
           at OpenQA.Selenium.By.<>c__DisplayClass21_0.<PartialLinkText>b__0(ISearchContext context)
        /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorWasmTemplateTest.cs(541,0): at Templates.Test.BlazorWasmTemplateTest.TestBasicNavigation(String appName, Boolean usesAuth, Boolean skipFetchData)
        /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorWasmTemplateTest.cs(464,0): at Templates.Test.BlazorWasmTemplateTest.BuildAndRunTest(String appName, Project project, Boolean usesAuth)
        /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorWasmTemplateTest.cs(309,0): at Templates.Test.BlazorWasmTemplateTest.BlazorWasmHostedTemplate_IndividualAuth_Works(Boolean useLocalDb)
        --- End of stack trace from previous location ---
```

#### Templates.Test.BlazorWasmTemplateTest.BlazorWasmHostedTemplate_IndividualAuth_Works_WithOutLocalDB

```
      OpenQA.Selenium.NoSuchElementException : no such element: Unable to locate element: {"method":"partial link text","selector":"Fetch data"}
  (Session info: headless chrome=84.0.4147.89)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17763 x86_64)
      Stack Trace:
           at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
           at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
           at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
           at OpenQA.Selenium.Remote.RemoteWebDriver.FindElementByPartialLinkText(String partialLinkText)
           at OpenQA.Selenium.By.<>c__DisplayClass21_0.<PartialLinkText>b__0(ISearchContext context)
        /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorWasmTemplateTest.cs(541,0): at Templates.Test.BlazorWasmTemplateTest.TestBasicNavigation(String appName, Boolean usesAuth, Boolean skipFetchData)
        /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorWasmTemplateTest.cs(464,0): at Templates.Test.BlazorWasmTemplateTest.BuildAndRunTest(String appName, Project project, Boolean usesAuth)
        /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorWasmTemplateTest.cs(309,0): at Templates.Test.BlazorWasmTemplateTest.BlazorWasmHostedTemplate_IndividualAuth_Works(Boolean useLocalDb)
        --- End of stack trace from previous location ---
```

All of these failures have massive logs associated with them. You can find them in the artifacts of https://dev.azure.com/dnceng/public/_build/results?buildId=731663&view=results

These failures were all in a single run that also demonstrated a bug in the shared ProcessEx class (see #23990), so we might want to take these failures with a grain of salt.

**Comment by HaoK** [comment]
Tracking with https://github.com/dotnet/aspnetcore/issues/25826 since these are all failing with the same root cause (dev cert issues)
