### ISSUE TITLE
Flaky Test AppWithDepsTests.ChangeFileInDependency

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#23994]
```
System.TimeoutException : Process timed out after 120 seconds
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.ProjectToolScenario.ExecuteCommandAsync(String project, TimeSpan timeout, String[] arguments) in /_/src/Tools/dotnet-watch/test/Scenario/ProjectToolScenario.cs:line 142
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.WatchableApp.PrepareAsync() in /_/src/Tools/dotnet-watch/test/Scenario/WatchableApp.cs:line 75
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.WatchableApp.StartWatcherAsync(String[] arguments, String name) in /_/src/Tools/dotnet-watch/test/Scenario/WatchableApp.cs:line 130
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.AppWithDepsTests.ChangeFileInDependency() in /_/src/Tools/dotnet-watch/test/AppWithDepsTests.cs:line 26
--- End of stack trace from previous location ---
```

https://dev.azure.com/dnceng/public/_build/results?buildId=729963

**Comment by pranavkm** [comment]
This has been migrated to the SDK repo and we haven't seen these failures appear there.
