### ISSUE TITLE
Getting Socket Exception, high response time and Http 500 when performance testing using JMeter

### ISSUE THREAD

**Issue by vahida** [dotnet/aspnetcore#24041]
Hi, We are currently running performance testing using JMeter (results attached) by sending concurrent requests to our API.
Getting high response time and HTTP 500 and netstat result showing lots of Time_Wait.

ASP .NET Core v3.1.0
IIS In-Process Hosting Model
Windows Server 2016 8 Core

We also built a bared bones api in order to exclude our custom middlewares, handlers including logging. However, still getting the same result:
- Used named HttpClient and typed client registered in DI and IHttpClientFactory to inject it through constructor. 
- There is no async blocker in the code path and only one HTTP Get call to an external API deployed in different machine and same domain.
- We didn't change any of HttpClient handler settings. Everything is by default.
- We don't dispose HttpClient instance created by HttpClientFactory !
- We also excluded load balancer in the middle and trying to hit external API directly.

Appreciate your assist and let me know if we need to update any configuration setting at application or OS level.
Thanks.

Stack trace:
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at ....FetchClientByNumber(Int32 memberNumber) in D:\TFS\....
   at ....MembersController.GetMemberByMemberNumber(GetMemberByMemberNumberRequest memberNumberRequest) in D:\TFS\....
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

![PT_01](https://user-images.githubusercontent.com/6835254/87737242-c1d83400-c81d-11ea-982d-01897bdb0cfa.JPG)
![PT_02](https://user-images.githubusercontent.com/6835254/87737248-c6045180-c81d-11ea-9f1d-9e80562ba734.JPG)

**Comment by Tratcher** [comment]
Please share the repro code, preferably as a github repo so we can see everything in context.

**Comment by vahida** [comment]
HI @Tratcher, I updated with source code location on Git.

**Comment by BrennanConroy** [comment]
@Pilchie Who triages HttpClientFactory?

**Comment by BrennanConroy** [comment]
Oh, actually this is in Runtime now, moving the issue.
