### ISSUE TITLE
Allow generation of MVC ActionLinks in a SignalR hub context for URL generation

### ISSUE THREAD

**Issue by DMW007** [dotnet/aspnetcore#24088]
### Is your feature request related to a problem? Please describe.

I'm using SignalR as modern alternative to Ajax for fetching some data. Often, those data contains an url. For example, I use SignalR to display a _newest content_ box. Each row contains metadata (title, author, time and so on) together with an URL, where the user can access the specified content. To generate those MVC urls, it's required to inject `IUrlHelper`.

Example:

```csharp
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using System;

public class MyHub : Hub {
    readonly IUrlHelper urlHelper;
    public MyHub(IUrlHelper urlHelper) {
        this.urlHelper = urlHelper;
    }

    public ThreadModel FetchThread(int id) {
        var threadModel = new ThreadModel() {
            Id = id
        };
        // Some logic to fetch the data from a database and map it to our DTO goes here
        // ...
        threadModel.Url = urlHelper.Action("View", "Thread", new { id = threadModel.Id });
        return threadModel;
    }
}

public class ThreadModel {
    public int Id { get; set; }
    public string Title { get; set; }
    public string Text { get; set; }
    public DateTime CreatedTime { get; set; }
    public string Url { get; set; }
}
```
Sadly this is not possible, which an [SO post also indicates](https://stackoverflow.com/questions/50905672/how-to-access-iurlhelper-from-signalr-hub):

```
fail: Microsoft.AspNetCore.SignalR.HubConnectionHandler[1]
      Error when dispatching 'OnConnectedAsync' on hub.
System.ArgumentNullException: Value cannot be null.
Parameter name: actionContext
   at Microsoft.AspNetCore.Mvc.Routing.UrlHelper..ctor(ActionContext actionContext)
   at MyProject.Startup.<>c.<ConfigureServices>b__4_1(IServiceProvider factory) in C:\Dev/MyProject/MyProject\Startup.cs:line 78
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubActivator`1.Create()
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnConnectedAsync(HubConnectionContext connection)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.RunHubAsync(HubConnectionContext connection)
```
Tested with the current LTS release 2.1. 

### Describe the solution you'd like
I'd like the ability to generate MVC actionlinks in a SignalR hub, like the urlhelper already does in controllers. According to my reserachs, there is currently **no way** to generate an actionlink in SignalR. So when generating a link in SignalR is required, there seems just the following two workarounds:

 1. Use a MVC controller action instead and call them by ajax (here we could inject `IUrlHelper`)
2. Generate some static helper class, which generates the required links manually

Number 1 seems the best possible workaround, because we can use the same logic for generation. But it's only suitable when no realtime functionality is required. I have workloads requiring realtime functionality, so number 2 is the only possible workaround here. It's worth nothing that this is bad from a design perspective, because we have two redundant logics of URL generation (MVC routes and the manual ones).

Altough the SO answer indicates that SignalR misses information about the request pipeline, this should be possible using the routes specified in `Startup.cs` and the controller attributes.

### Additional context
I'm wondering that there seems still no real solution for this issue expect the two workarounds with their drawbags. It was asked on SO two years ago. Building an MVC url seems no unusual task when using SignalR. It's required for every _newest content_ usage, where SignalR delivers the data instead of ajax.

**Comment by BrennanConroy** [comment]
You should use the [LinkGenerator](https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.routing.linkgenerator?view=aspnetcore-3.1) class for this.

**Comment by halter73** [comment]
```
   at MyProject.Startup.<>c.<ConfigureServices>b__4_1(IServiceProvider factory) in C:\Dev/MyProject/MyProject\Startup.cs:line 78
```

If LinkGenerator doesn't work for you, can you provide the code from your Startup class?

**Comment by DMW007** [comment]
@BrennanConroy The LinkGenerator only applies to 3.1 3.0 2.2, but not for the 2.1 LTS release.

**Comment by BrennanConroy** [comment]
Ah, that's unfortunate. The LinkGenerator was created to help resolve this, but of course it was added after 2.1.

You'll have to write something custom if you want to do this in 2.1. You could try taking a look at this blog post https://codeopinion.com/generating-links-with-urlhelper-outside-of-asp-net-core/
