### ISSUE TITLE
Flaky test: ClearsResponseBuffer_BeforeRequestIsReexecuted

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#24146]
```
[xUnit.net 00:00:02.82]     Microsoft.AspNetCore.Diagnostics.ExceptionHandlerTest.ClearsResponseBuffer_BeforeRequestIsReexecuted [FAIL]
[xUnit.net 00:00:02.83]       System.Net.Http.HttpRequestException : Error while copying content to a stream.
[xUnit.net 00:00:02.83]       ---- System.IO.IOException : 
[xUnit.net 00:00:02.83]       -------- System.IO.IOException : The request was aborted or the pipeline has finished.
[xUnit.net 00:00:02.83]       Stack Trace:
[xUnit.net 00:00:02.83]            at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
[xUnit.net 00:00:02.83]            at System.Net.Http.HttpClient.FinishSendAsync(ValueTask`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts, Boolean buffered, Boolean async, CancellationToken callerToken, Int64 timeoutTime)
[xUnit.net 00:00:02.83]         /_/src/Middleware/Diagnostics/test/UnitTests/ExceptionHandlerTest.cs(185,0): at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerTest.ClearsResponseBuffer_BeforeRequestIsReexecuted()
[xUnit.net 00:00:02.83]         --- End of stack trace from previous location ---
[xUnit.net 00:00:02.83]         ----- Inner Stack Trace -----
[xUnit.net 00:00:02.83]         /_/src/Hosting/TestHost/src/ResponseBodyReaderStream.cs(144,0): at Microsoft.AspNetCore.TestHost.ResponseBodyReaderStream.CheckAborted()
[xUnit.net 00:00:02.83]         /_/src/Hosting/TestHost/src/ResponseBodyReaderStream.cs(74,0): at Microsoft.AspNetCore.TestHost.ResponseBodyReaderStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
[xUnit.net 00:00:02.83]            at System.IO.Stream.CopyToAsyncInternal(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
[xUnit.net 00:00:02.83]            at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
[xUnit.net 00:00:02.83]         ----- Inner Stack Trace -----
[xUnit.net 00:00:02.83]         /_/src/Hosting/TestHost/src/ResponseBodyPipeWriter.cs(70,0): at Microsoft.AspNetCore.TestHost.ResponseBodyPipeWriter.CheckNotComplete()
[xUnit.net 00:00:02.83]         /_/src/Hosting/TestHost/src/ResponseBodyPipeWriter.cs(31,0): at Microsoft.AspNetCore.TestHost.ResponseBodyPipeWriter.FlushAsync(CancellationToken cancellationToken)
[xUnit.net 00:00:02.83]         /_/src/Hosting/TestHost/src/ResponseBodyWriterStream.cs(59,0): at Microsoft.AspNetCore.TestHost.ResponseBodyWriterStream.FlushAsync(CancellationToken cancellationToken)
[xUnit.net 00:00:02.83]         /_/src/Http/Http/src/StreamResponseBodyFeature.cs(133,0): at Microsoft.AspNetCore.Http.StreamResponseBodyFeature.CompleteAsync()
[xUnit.net 00:00:02.83]         /_/src/Hosting/TestHost/src/ResponseFeature.cs(100,0): at Microsoft.AspNetCore.TestHost.ResponseFeature.<>c__DisplayClass34_0.<<OnCompleted>b__0>d.MoveNext()
[xUnit.net 00:00:02.83]         --- End of stack trace from previous location ---
[xUnit.net 00:00:02.83]         /_/src/Hosting/TestHost/src/ResponseFeature.cs(104,0): at Microsoft.AspNetCore.TestHost.ResponseFeature.<>c__DisplayClass34_0.<<OnCompleted>b__0>d.MoveNext()
[xUnit.net 00:00:02.83]         --- End of stack trace from previous location ---
[xUnit.net 00:00:02.84]         /_/src/Hosting/TestHost/src/HttpContextBuilder.cs(200,0): at Microsoft.AspNetCore.TestHost.HttpContextBuilder.CompleteResponseAsync()
[xUnit.net 00:00:02.84]         /_/src/Hosting/TestHost/src/HttpContextBuilder.cs(125,0): at Microsoft.AspNetCore.TestHost.HttpContextBuilder.<>c__DisplayClass23_0.<<SendAsync>g__RunRequestAsync|0>d.MoveNext()
```

Failing build: https://dev.azure.com/dnceng/public/_build/results?buildId=738667&view=results
Console logs: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-heads-master-fa4fdc47cd844c5095/Microsoft.AspNetCore.Diagnostics.Tests--net5.0/console.4429d75a.log?sv=2019-02-02&se=2020-08-10T01%3A01%3A11Z&sr=c&sp=rl&sig=dCN%2BLVPc5j3bZ9miFA5E%2F5jso6CueSyncGCv%2BGWc4Dg%3D

**Comment by Pilchie** [comment]
It's not clear to me that this is actually flaky, as opposed to broken everywhere.  Should someone take a look and see if a regression of some kind slipped through?

**Comment by ryanbrandenburg** [comment]
Yeah, this failed 93/93 times run with
```
System.Net.Http.HttpRequestException : Error while copying content to a stream.
---- System.IO.IOException : 
-------- System.IO.IOException : The request was aborted or the pipeline has finished.
```
On every instance I looked at, so it doesn't seem like flakiness so much as just broken.

**Comment by Tratcher** [comment]
Update: The test history shows this has been passing since it was fixed 21 days ago, it can be unquarantined soon.
