### ISSUE TITLE
AddControllersAsServices + ServiceProviderOptions.ValidateOnBuild causes exception but still works

### ISSUE THREAD

**Issue by serpent5** [dotnet/aspnetcore#24149]
In the following example, I expect the custom registration of `ExampleController` to be used when the controller gets activated:

```csharp
serviceCollection.AddControllers()
    .AddControllersAsServices();

serviceCollection.AddTransient(sp => new ExampleController(new ExampleService { ... }));
```

```csharp
public ExampleController(ExampleService exampleService)
{
    this.exampleService = exampleService;
}
```

In a 2.1 version of the preceding code, this works without issue. However, in 3.1, this causes an exception when running with `ASPNETCORE_ENVIRONMENT` set to `Development` (exception details below). This is because DI service-descriptors are validated on-build (`o.ValidateOnBuild` = `true`) when running in this environment.

When using the preceding code in the `Production` environment, there is no exception. Of course, this is expected, because the validation isn't performed. However, the application _works_, because the controller activation succeeds, in spite of the validation process thinking it wouldn't.

### To Reproduce

1. Run the repro project [here](https://github.com/serpent5/Serpent5.ControllersAsServices), using `dotnet run`.
1. Observe the following exception in the console output:

   > Unable to resolve service for type 'Serpent5.ControllersAsServices.Services.ExampleService' while attempting to activate 'Serpent5.ControllersAsServices.Controllers.ExampleController'.)

1. Choose either of the following approaches:

   1. Use `dotnet run --no-launch-profile` to default the Environment to `Production`.

   1. In [Program.cs](https://github.com/serpent5/Serpent5.ControllersAsServices/blob/master/Program.cs#L15), uncomment the following line:

      >     // .UseDefaultServiceProvider(o => o.ValidateOnBuild = false)

1. Re-run the project and navigate to https://localhost:5001.
1. Observe the following response in the browser:

   > If you see this, it works.

### Exception

> Unhandled exception. System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Serpent5.ControllersAsServices.Controllers.ExampleController Lifetime: Transient ImplementationType: Serpent5.ControllersAsServices.Controllers.ExampleController': Unable to resolve service for type 'Serpent5.ControllersAsServices.Services.ExampleService' while attempting to activate 'Serpent5.ControllersAsServices.Controllers.ExampleController'.)
 ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Serpent5.ControllersAsServices.Controllers.ExampleController Lifetime: Transient ImplementationType: Serpent5.ControllersAsServices.Controllers.ExampleController': Unable to resolve service for type 'Serpent5.ControllersAsServices.Services.ExampleService' while attempting to activate 'Serpent5.ControllersAsServices.Controllers.ExampleController'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'Serpent5.ControllersAsServices.Services.ExampleService' while attempting to activate 'Serpent5.ControllersAsServices.Controllers.ExampleController'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable\`1 serviceDescriptors, ServiceProviderOptions options)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable\`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Serpent5.ControllersAsServices.Program.Main(String[] args) in E:\Source\GitHub\serpent5\Serpent5.ControllersAsServices\Program.cs:line 9

### Further technical details

```
dotnet --info
```

> .NET Core SDK (reflecting any global.json):
>  Version:   3.1.302     
>  Commit:    41faccf259  
> 
> Runtime Environment:    
>  OS Name:     Windows   
>  OS Version:  10.0.19041
>  OS Platform: Windows   
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\3.1.302\
> 
> Host (useful for support):
>   Version: 3.1.6
>   Commit:  3acd9b0cd1
> 
> .NET Core SDKs installed:
>   2.1.807 [C:\Program Files\dotnet\sdk]
>   3.1.300 [C:\Program Files\dotnet\sdk]
>   3.1.301 [C:\Program Files\dotnet\sdk]
>   3.1.302 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App] 
>   Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App] 
>   Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]        
>   Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by serpent5** [comment]
Never mind. I've figured out what's going wrong here...

1. The call to `AddControllersAsServices` adds a `ServiceDescriptor` (SD) for `ExampleController`.
1. The explicit call to `AddTransient` adds _another_ SD for `ExampleController`.
1. During the validation process, _all_ SDs are validated. The first SD can't be resolved because it doesn't know how to create the `ExampleService`.
1. When the controller is activated at runtime, the last-wins process means the SD registered via `AddTransient` is used. This is set up with its `ExampleService` dependency, so it works as it should.

There are two solutions:

1. Replace the existing SD descriptor, instead of adding a new one with `AddTransient`.
1. Register the controller with `AddTransient` _before_ calling `AddControllersAsServices`. This means `AddControllersAsServices` doesn't add its own SD, because it uses `TryAddTransient`.
