### ISSUE TITLE
Blazor WebAssembly HttpClientHandler "Supports*" properties regressions in 5.0.0-preview.7.20365.19

### ISSUE THREAD

**Issue by campersau** [dotnet/aspnetcore#24173]
### Describe the bug
Before upgrading to `5.0.0-preview.7.20365.19` the following `HttpClientHandler` properties returned `false` as they are not supported on wasm:
- `SupportsAutomaticDecompression`
- `SupportsProxy`
- `SupportsRedirectConfiguration`

which was useful to feature detect and avoid `PlatformNotSupportedException`s thrown by their corresponding properties:
- `AutomaticDecompression`
- `UseProxy`, `Proxy`

https://github.com/mono/mono/blob/a2fcf072e8ab42b121fbc81509c9793875846c12/mcs/class/System.Net.Http/System.Net.Http/HttpClientHandler.wasm.cs#L34-L38

But now they always return `true` which means that feature detection won't work:

https://github.com/dotnet/runtime/blob/7adab7c8114286539eed57781e7057eca13a566a/src/libraries/System.Net.Http/src/System/Net/Http/HttpClientHandler.cs#L51-L53

### To Reproduce
The following code throws now in blazor wasm:
```c#
var clientHandler = new HttpClientHandler();
if (clientHandler.SupportsAutomaticDecompression) { // returns always true now ...
    clientHandler.AutomaticDecompression = DecompressionMethods.GZip; // and thereby this will throw a PlatformNotSupportedException
}
```

### Exceptions (if any)
```
Operation is not supported on this platform.
   at System.Net.Http.BrowserHttpHandler.set_AutomaticDecompression(DecompressionMethods value)
   at System.Net.Http.HttpClientHandler.set_AutomaticDecompression(DecompressionMethods value)
```

### Further technical details
- ASP.NET Core version 5.0.0-preview.7.20365.19
- Visual Studio Version 16.7.0 Preview 5.0

Since this is likely a bug for dotnet/runtime feel free to move it there.

**Comment by campersau** [comment]
As a workaround it is possible to subclass `HttpClientHandler` and override these properties manually:

```c#
class Net50WorkaroundHttpClientHandler : HttpClientHandler
{
    public override bool SupportsAutomaticDecompression => false;
    public override bool SupportsProxy => false;
    public override bool SupportsRedirectConfiguration => false;
}
```
