### ISSUE TITLE
Grpc Interop tests assembly load failure on Helix

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#24182]
The gRPC interop tests are currently disabled.

We saw failures after the latest dependency updates brought breaking Logging changes in the runtime: https://dev.azure.com/dnceng/public/_build/results?buildId=739743&view=results

The error suggests that the wrong version of the M.E.Logging.Console is being loaded at runtime:
```
[ERROR] Unhandled exception. System.TypeLoadException: Could not load type 'Microsoft.Extensions.Logging.Console.SimpleConsoleFormatterOptions' from assembly 'Microsoft.Extensions.Logging.Console, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
[ERROR]    at InteropTestsWebsite.Program.<>c.<CreateHostBuilder>b__1_0(ILoggingBuilder builder)
[ERROR]    at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c__DisplayClass5_0.<ConfigureLogging>b__1(ILoggingBuilder builder)
[ERROR]    at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection services, Action`1 configure)
[ERROR]    at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c__DisplayClass5_0.<ConfigureLogging>b__0(HostBuilderContext context, IServiceCollection collection)
[ERROR]    at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
[ERROR]    at Microsoft.Extensions.Hosting.HostBuilder.Build()
[ERROR]    at InteropTestsWebsite.Program.Main(String[] args) in F:\workspace\_work\1\s\src\Grpc\test\testassets\InteropWebsite\Program.cs:line 33
Writing minidump to file /home/helixbot/dotnetbuild/dumps/dotnet.31827.dmp
Written 93696000 bytes (22875 pages) to core file
Dump successfully written
```

I suspect that the helix environment didn't install the correct aspnetcore runtime and therefore the M.E.Logging.Console binary that was loaded is old.

**Comment by dougbu** [comment]
Could this be related to the `...AddConsole(...)` -> `...AddSimpleConsole(...)` changes made in #23978, specifically files src/Grpc/test/testassets/InteropClient/InteropClient.cs and src/Grpc/test/testassets/InteropClient/InteropClient.cs❔ That was done prior to disabling these tests.
