### ISSUE TITLE
Flaky test: CanDeleteUnkeyed

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#24190]
Error:
```
OpenQA.Selenium.StaleElementReferenceException : stale element reference: element is not attached to the page document\n  (Session info: headless chrome=84.0.4147.89)\n  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17763 x86_64)
```
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=740313&view=results

**Comment by pranavkm** [comment]
Also, `KeyTest.CanReorder`:

```C#
  at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.FindElement(String mechanism, String value)
   at Microsoft.AspNetCore.Components.E2ETest.Tests.KeyTest.ReadNodeFromDOM(IWebElement nodeElem) in /_/src/Components/test/E2ETest/Tests/KeyTest.cs:line 324
   at System.Linq.Enumerable.SelectIListIterator`2.ToArray()
   at Microsoft.AspNetCore.Components.E2ETest.Tests.KeyTest.ReadNodeFromDOM(IWebElement nodeElem) in /_/src/Components/test/E2ETest/Tests/KeyTest.cs:line 324
   at Microsoft.AspNetCore.Components.E2ETest.Tests.KeyTest.ValidateRenderedOutput(IWebElement appElem, Node expectedRootNode, Boolean validatePreservation) in /_/src/Components/test/E2ETest/Tests/KeyTest.cs:line 300
   at Microsoft.AspNetCore.Components.E2ETest.Tests.KeyTest.PerformTest(Node[] before, Node[] after) in /_/src/Components/test/E2ETest/Tests/KeyTest.cs:line 290
   at Microsoft.AspNetCore.Components.E2ETest.Tests.KeyTest.CanReorder() in /_/src/Components/test/E2ETest/Tests/KeyTest.cs:line 117
```

Failure in: https://dev.azure.com/dnceng/public/_build/results?buildId=763884&view=ms.vss-test-web.build-test-results-tab&runId=23734504&resultId=100446&paneView=debug

**Comment by HaoK** [comment]
Fixed as part of https://github.com/dotnet/aspnetcore/pull/26286
