### ISSUE TITLE
Microsoft.AspNetCore.Components.WebAssembly.Server 3.2.1 Regex

### ISSUE THREAD

**Issue by hardkorehak** [dotnet/aspnetcore#24247]
Updated NuGet stuff today, and when I updated WASM Server to 3.2.1, I receive the below error

System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null. (Parameter 'input')
  Source=System.Text.RegularExpressions
  StackTrace:
   at System.Text.RegularExpressions.Regex.IsMatch(String input)
   at Microsoft.AspNetCore.Builder.DebugProxyLauncher.<>c__DisplayClass10_0.<CompleteTaskWhenServerIsReady>g__OnOutputDataReceived|0(Object sender, DataReceivedEventArgs eventArgs)
   at System.Diagnostics.Process.OutputReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__18_0(Object edi)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

  This exception was originally thrown at this call stack:
   [External Code]

**Comment by pranavkm** [comment]
This could be a patch candidate.

**Comment by dme-development** [comment]
Had the same problem with VS 2019 16.6.3. After upgrading to 16.6.5 it is working fine.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. @hardkorehak can you please confirm that by updating the runtime (which you can also get through VS update) fixes the issue?

**Comment by hardkorehak** [comment]
Yes, just now had the opportunity to test after all updates. It is working now. Thank you.
