### ISSUE TITLE
JavaScript interop calls cannot be issued at this time

### ISSUE THREAD

**Issue by barahonajm** [dotnet/aspnetcore#24320]
This code which is in a shared component library

```razor
@code {
    private WeatherForecast[] forecasts;

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        try
        {
            forecasts = await Http.GetFromJsonAsync<WeatherForecast[]>("WeatherForecast");
        }
        catch (AccessTokenNotAvailableException exception)
        {
            exception.Redirect();
        }
    }
}

```

is causing 

```
System.InvalidOperationException: JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`3.EnsureAuthService()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`3.RequestAccessToken()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.AuthorizationMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts, CancellationToken callerToken, Int64 timeoutTime)
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at FastPOS.Components.Pages.FetchData.LoadData() in H:\Projects\FastPOS\FastPOS.Components\Pages\FetchData.razor:line 50
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Error: Unhandled exception in circuit '2VyNH42RzzyOWhCYqYPi1IaPI8WXWy7UBdPay-qDSOI'.

System.InvalidOperationException: JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`3.EnsureAuthService()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`3.RequestAccessToken()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.AuthorizationMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts, CancellationToken callerToken, Int64 timeoutTime)
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at FastPOS.Components.Pages.FetchData.LoadData() in H:\Projects\FastPOS\FastPOS.Components\Pages\FetchData.razor:line 50
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

### Scenario
I have created a project where blazor server side and blazor wasm are sharing a single component base library (I want them the evolve thogheter), there is also a server that handles authorization and authentication which is a separated project (Created from the blazor wasm with individuatl aunthetication template)

Now after some modification almost everything from the default template with individual authentication is working in both server side and wasm: login, register account, pages with @attribute [Authorize] but they are sharing code from a single component library and they are working with the same authorization and authentication server

The problem is the Fetchdata example which is only working on wasm due the error mentioned above **even after I put the code on** `OnAfterRenderAsync`

**Comment by javiercn** [comment]
@barahonajm thanks for contacting us.

It looks like you are trying to prerender the application. Prerendering authorized pages is not supported. See [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-3.1#support-prerendering-with-authentication) for details

**Comment by barahonajm** [comment]
@javiercn Thanks for your answer

Unfortunately no, my render configuration is on `server` (Blazor server side), and my pages with [Authorize] are working fine, only this `Http.GetFromJsonAsync<WeatherForecast[]>("WeatherForecast");` call is making the app crash even though that call is on `OnAfterRenderAsync`

```razor
<body>
    <app>
        <component type="typeof(App)" render-mode="Server" />
    </app>

    <div id="blazor-error-ui">
        <environment include="Staging,Production">
            An error has occurred. This application may no longer respond until reloaded.
        </environment>
        <environment include="Development">
            An unhandled exception has occurred. See browser dev tools for details.
        </environment>
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>

    <script src="_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js"></script>
    <script src="_framework/blazor.server.js"></script>
</body>
```

**Comment by javiercn** [comment]
`icrosoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`3.RequestAccessToken()` this in your callstack is Blazor WebAssembly code.

If you are using the authentication support in webassembly within server-side Blazor, that's not supported.

Are we missing something here?

**Comment by barahonajm** [comment]
> If you are using the authentication support in webassembly within server-side Blazor, that's not supported.

I see, I wanted to use RemoteAuthenticatorView on blazor server side too just like webassembly does, little question **are you planning to support that kind of authentication on blazor server side?** I think most of the work is done since my blazor server side is almost working, [Authorize] attribute works fine as well as the login, register, logout, all those actions are correctly talking with an authentication server which is another server separated from blazor server side

For now I think I will need to write another IRemoteAuthenticationService that does not use javascript if I want to continue using RemoteAuthenticatorView right?

**Comment by javiercn** [comment]
Authentication for SPAs (Blazor webassembly) is fundamentally different from authentication for web applications (Blazor server).

I wouldn't recommend you try to use the auth support for Blazor webassembly in server-side Blazor. It's not targeted for it and it is not a good fit.

You can experiment at your own risk, but you might find more blockers along the way.

**Comment by barahonajm** [comment]
> Authentication for SPAs (Blazor webassembly) is fundamentally different from authentication for web applications (Blazor server).

Ok, I would need to explore more about this topic, my very quick thinking lead me to believe I can use a blazor server side as a SPA but you are right I might not get any advantage doing that.

Thanks for the answers.
