### ISSUE TITLE
Publishing Hosted WebAssembly to Azure App Service Broken for .NET 5.0?

### ISSUE THREAD

**Issue by ericpincus** [dotnet/aspnetcore#24388]
I have a Hosted WebAssembly solution with three projects (client, server, shared).

I have followed the instructions as detailed in the article to set the solution to .NET 5.0 : ( [ASP.NET Core Updates in .NET 5 Preview 7 ](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-5-preview-7/)) which includes the settings:

`<TargetFramework>net5.0</TargetFramework>`
`<RuntimeIdentifier>browser-wasm</RuntimeIdentifier>`
`<UseBlazorWebAssembly>true</UseBlazorWebAssembly>`

Note that there I have no build errors locally, the solution runs as expected. The issue I've come across is on the publish attempt.

I have a publish profile, previously working, that applies to the server app, publishing to the Azure App Service. That is now failing.

To check if the issue was specific to my existing setup, I started a new solution from scratch, only to face the same issue.

Upon attempting to publish in the new, scaffolded solution, I get the error "Metadata file 'c:\[PATH]\win-x86\\[AppName].Client.dll' could not be found. I expect that's because the target framework of the client app is now publishing to a folder "browser-wasm," no longer win-x86.

Under the publish settings, I have the following:

Target Framework: net5.0
Deployment Mode: Self-Contained
Target Runtime: win-x86

There is no choice for "browser-wasm."

If I build the publish profile for just the client project, I can choose browser-wasm, but then it doesn't also publish the server project, which is obviously required for execution. My understanding is the publish needs to be from the server project.

Again, I have the issue on my developed solution, but also the same issue on a newly created solution from the framework without any added code.

Over the course of playing with my developed solution (not the new scaffolded solution), the error message eventually became: "Assets file 'C:\\[PATH]\Client\obj\project.assets.json' doesn't have the target for '.NETCoreApp,Version=v5.0/browser-wasm'. Ensure that restore has run and that you have included 'net5.0' in the TargetFrameworks for your project. You may also need to include 'browser-wasm' in your projects' RuntimeIdentifiers."

(Not entirely sure why that's detailed as "TargetFrameworks" plural when my entry in the proj file is singular "TargetFramework.")

If I add the runtime identifier of browser-wasm to the server project to get the error - which was a reach to work - "There was no runtime pack for Microsoft.AspNetCore.App available for the specified RuntimeIdentifier 'browser-wasm'.

Also, any direct manipulation of the project.assets.json file is overwritten on publishing, so that wasn't a workaround.

Please advise ASAP as I am unable to publish any changes and the site is non-functional via the Azure App Service.

Thank you...

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is a known issue which is being fixed in 5.0 RC1 release. We track the work as part of #23477 
@pranavkm do you have any suggestions how this can be worked around for now?

**Comment by ericpincus** [comment]
Thank you, unless RC1 is coming out this week, a workaround is crucial. The site is down and can't be re-published to...

**Comment by ericpincus** [comment]
Note: in the absence of a workaround, I rolled back to the previous preview version.

**Comment by LaughingJohn** [comment]
I has a similar issue on an upgraded solution. I have asp.net hosted wasm as per the OP and do a framework dependent publish. I've upgraded the framework in Azure and managed to publish by removing the following lines from the publish profile (based on comparison to a publish profile created from a brand new .Net 5.0 project):

<TargetFramework>netcoreapp3.1</TargetFramework>
<SelfContained>false</SelfContained>
<RuntimeIdentifier>win-x64</RuntimeIdentifier>

This seemed to choose "portable" as the target framework. However the website now hangs and eventually returns a 503 so something has gone belly up!

I'm sure you're aware, but just thought I'd mention it as I came across this post in my hunt for a solution..

**Comment by stbsolutions** [comment]
I have an Azure hosted Blazor Server app and having the same issue when moved from .Net 5 Preview 6 to .Net 5 Preview 7.
Since Preview 8 should be coming soon do we expect this to be fixed then or do we have to wait until RC1?
I would really hate to switch back to Preview 6 since every preview I'm keeping up with the code changes to make sure I can go to production with the app as soon as Microsoft makes production support available in RC1 but how can we be sure this will work in an Azure production environment if we are only 1 preview away from that and it doesn't work.

**Comment by pranavkm** [comment]
@stbsolutions unfortunately a fix for this did not land in preview8. However there is a fairly small workaround for this which is pretty close to what the actual fix looks like:

https://github.com/dotnet/aspnetcore/issues/23477#issuecomment-668642745

**Comment by stbsolutions** [comment]
Applied and redeployed but now it just takes about 2 minutes for the page to load and still get the same error message
**Service Unavailable
HTTP Error 503. The service is unavailable.**

Is this workaround supposed to work in Preview 7 or will it work in Preview 8? (If so, when will Preview 8 be out).

Thanks

**Comment by stbsolutions** [comment]
Note I'm using Blazor Server (not Blazor Webassembly)

**Comment by ericpincus** [comment]
Note: I tried the suggestion and while I was able to get a publish, I wasn't able to get the Azure site running. I've gone back to the v3.1.6 builds in the meantime to keep the site running.

The error I got was HTTP Error 500.30 - ASP.NET Core app failed to start error. 

Looking in the application event logs:

Application: w3wp.exe
CoreCLR Version: 5.0.20.36411
.NET Version: 5.0.0-preview.7.20364.11
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Authentication.AzureAD.UI, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.AspNetCore.Authentication.AzureAD.UI, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at eCapHolds.Server.Startup.ConfigureServices(IServiceCollection services)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at eCapHolds.Server.Program.Main(String[] args) in C:\Data\Code\ecapholds\Server\Program.cs:line 16

**Comment by stbsolutions** [comment]
Eric, I get the same exact error with Preview 7 (self-contained deployment).
However, with Preview 6 (also self-contained deployment), I don't get the error and the app works fine in Azure (It's a Blazor Server app). 

I'm not sure if the issue when deploying to Azure might be that Blazor (both WebAssembly and Server) starting on .Net 5 Preview 7 now target ".Net 5" and Azure can't yet handle that (instead of targeting netcoreapp5.0 or netstandard2.1 in .Net 5 preview 6 and prior).

**Comment by ericpincus** [comment]
Thanks for the suggestion - just tried it. Unfortunately for me, I'm unable to get it to work on Preview 6.

Now getting almost the same message:

Application: w3wp.exe
CoreCLR Version: 5.0.20.36411
.NET Version: 5.0.0-preview.7.20364.11
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Authentication.AzureAD.UI, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.AspNetCore.Authentication.AzureAD.UI, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at eCapHolds.Server.Startup.ConfigureServices(IServiceCollection services)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at eCapHolds.Server.Program.Main(String[] args) in C:\Data\Code\eCapHolds\Server\Program.cs:line 16

**Comment by ericpincus** [comment]
That was a lot of work - to downgrade the SDK and get the project to accept the change. I still have a yellow triangle under packages on the server node.

All that and the publish generates the error:

Application: w3wp.exe
CoreCLR Version: 5.0.20.30506
.NET Version: 5.0.0-preview.6.20305.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Authentication.AzureAD.UI, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.AspNetCore.Authentication.AzureAD.UI, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at eCapHolds.Server.Startup.ConfigureServices(IServiceCollection services)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at eCapHolds.Server.Program.Main(String[] args) in C:\Data\Code\ecapholds\Server\Program.cs:line 16
