### ISSUE TITLE
[Blazor Server] Razor Component (Radzen) with a syntax issue causes circuit exception without any means of debugging or any useful stack trace

### ISSUE THREAD

**Issue by scscgit** [dotnet/aspnetcore#24518]
### Describe the bug

When adding an incorrect character to a Razor Tag of a Radzen component, for example `*` or `)` like this `<RadzenButton */>` (I haven't verified if this applies to other pre-compiled libraries, but I assume it does), the IDE doesn't report any vital error/warning, and the code gets compiled successfully, but it throws an unhandled runtime exception when the component attempts to render.

However, in the error message **there is no hint** as to which component caused this issue, it's not reported on which line of code this occurred, and there's literally no way to debug this issue, even if you go through the stack trace and inspect the exceptions manually. This means any large project can suddenly start executing a different path based on database content, and it breaks down without any means of debugging, except trial-and-error and bisection where you remove components one by one. This is too dangerous for a production usage, and similar third party libraries shouldn't be even able to throw such sneaky exceptions, due to the fact that they're being caught by `RenderTree.Renderer` and not the library itself. Alternatively, there should be at least some warning via IDE static analysis, because this kind of syntax is obviously wrong. But also in general, when it comes to circuit exceptions, I was unable to find any advices regarding how to debug them (and find a source of exception), as it's always too late when they their exception gets logged; the only relevant article seems to be [Handle Errors (in Blazor Fundamentals)](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-3.1).

### To Reproduce

1. Use any existing project, or generate one using Template - ASP.NET Core Web Application - Blazor Server App - 3.1.302
2. Install [<ins>Radzen</ins>](https://blazor.radzen.com/get-started) and use any component with an incorrect syntax. Minimal steps follow:

**Index.razor**
```razor
@using Radzen.Blazor
@page "/"
<RadzenButton Text="test")/>
```

**WebApplication.csproj**
```
<ItemGroup>
  <PackageReference Include="Radzen.Blazor" Version="2.11.3" />
</ItemGroup>
```

**_Host.cshtml**
`<link rel="stylesheet" href="_content/Radzen.Blazor/css/default-base.css">` above `bootstrap.min.css`
`<script src="_content/Radzen.Blazor/Radzen.Blazor.js"></script>` above `blazor.server.js`

### Exceptions (if any)
`Output` from `WebApplication - ASP.NET Core Web Server` (or `Debug`) prints
```
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: InvalidCharacterError: String contains an invalid character
System.InvalidOperationException: InvalidCharacterError: String contains an invalid character
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'IXcFZr1oksMclKACCRmuXNvZPZwv3Zfz0jlYZmySVYc'.
System.AggregateException: One or more errors occurred. (InvalidCharacterError: String contains an invalid character)
 ---> System.InvalidOperationException: InvalidCharacterError: String contains an invalid character
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)
   --- End of inner exception stack trace ---
```
Also together with the lower half (with InvalidCharacterError), the JavaScript console displays:
```
[2020-08-02T20:38:34.789Z] Error: There was an error applying batch 4. blazor.server.js:19:23164
Uncaught (in promise) DOMException: String contains an invalid character blazor.server.js:8
```

### Further technical details
- ASP.NET Core 3.1.302
- Microsoft Visual Studio Community 2019 Version 16.6.5

**Comment by scscgit** [comment]
hi @pranavkm, what do you mean by there not being community involvement? Is this vital issue not reproducible, or is it just that Blazor doesn't have any active community that cares about bugs?

**Comment by Bouke** [comment]
I just ran into this exception as well. There was no information on what was wrong in my template and how to resolve it. I had to perform a binary search on my Razor file to figure out what component was causing this issue. -1 would not recommend.
