### ISSUE TITLE
Blazor Wasm: published app broken

### ISSUE THREAD

**Issue by MarkStega** [dotnet/aspnetcore#24565]
### Describe the bug
A Blazor wasm application that is published fails with an exception in a page that works when the application is run locally.

### To Reproduce

The repository for this project is located at [https://github.com/BlazorMdc/BlazorMdcWebsite](https://github.com/BlazorMdc/BlazorMdcWebsite)

The broken published site is at [https://blazormdc.com/](https://blazormdc.com/) (navigate to "text field - special" in the menu
### Exceptions (if any)
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Method overrides a class or interface that is not extended or implemented by this type
System.TypeLoadException: Method overrides a class or interface that is not extended or implemented by this type
   at System.Text.RegularExpressions.RegexRunner.InitializeForGo()
   at System.Text.RegularExpressions.RegexRunner.Scan(Regex regex, String text, Int32 textbeg, Int32 textend, Int32 textstart, Int32 prevlen, Boolean quick, TimeSpan timeout)
   at System.Text.RegularExpressions.Regex.Run(Boolean quick, Int32 prevlen, String input, Int32 beginning, Int32 length, Int32 startat)
   at System.Text.RegularExpressions.MatchCollection.GetMatch(Int32 i)
   at System.Text.RegularExpressions.MatchCollection.EnsureInitialized()
   at System.Text.RegularExpressions.MatchCollection.get_Count()
   at BlazorMdc.MTAutocomplete.<>c__DisplayClass83_0.<BuildSelectList>b__0(SelectionItem f)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2[[BlazorMdc.MTAutocomplete.SelectionItem, BlazorMdc, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ToArray()
   at System.Linq.Enumerable.ToArray[String](IEnumerable`1 source)
   at BlazorMdc.MTAutocomplete.BuildSelectList(String fieldText)
   at BlazorMdc.MTAutocomplete.SetParameters()
   at BlazorMdc.MTAutocomplete.OnParametersSet()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at BlazorMdc.Internal.InputComponentFoundation`1.<SetParametersAsync>d__62[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext() 3 blazor.webassembly.js:1:38193
```

### Further technical details

The example shows an application published on github pages. The same issue exists if I publish the app locally and host it in a static IIS website.

The offending error is occurring in a .Net Standard 2.1 library.
```
C:\Solutions\OHI\BlazorMdcWebsite>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.7.20366.6
 Commit:    0684df3a5b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.7.20366.6\

Host (useful for support):
  Version: 5.0.0-preview.7.20364.11
  Commit:  53976d38b1

.NET SDKs installed:
  3.1.302 [C:\Program Files\dotnet\sdk]
  3.1.400-preview-015203 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.7.20366.6 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.7.20365.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.7.20364.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.7.20366.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by simonziegler** [comment]
I'm also experiencing this (on the same project)

**Comment by pranavkm** [comment]
This issue was moved to mono/linker#1408
