### ISSUE TITLE
Flaky test: LinkedApplicationWorks

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#24594]
https://dev.azure.com/dnceng/public/_build/results?buildId=758198&view=ms.vss-test-web.build-test-results-tab&runId=23539956&resultId=100000&paneView=debug

@davidfowl 

```
System.Net.Http.HttpRequestException : Received an invalid status line: '405\0\0\0\0\0\x0f200 OK'.

Stack trace
   at System.Net.Http.HttpConnection.ParseStatusLine(Span`1 line, HttpResponseMessage response)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IntegrationTesting.LoggingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/Hosting/Server.IntegrationTesting/src/Common/LoggingHandler.cs:line 23
   at System.Net.Http.HttpClient.FinishSendAsync(ValueTask`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts, Boolean buffered, Boolean async, CancellationToken callerToken, Int64 timeoutTime)
   at Microsoft.AspNetCore.Server.IntegrationTesting.RetryHelper.RetryRequest(Func`1 retryBlock, ILogger logger, CancellationToken cancellationToken, Int32 retryCount) in /_/src/Hosting/Server.IntegrationTesting/src/Common/RetryHelper.cs:line 39
   at Microsoft.AspNetCore.Server.IntegrationTesting.RetryHelper.RetryRequest(Func`1 retryBlock, ILogger logger, CancellationToken cancellationToken, Int32 retryCount) in /_/src/Hosting/Server.IntegrationTesting/src/Common/RetryHelper.cs:line 55
   at Microsoft.AspNetCore.Hosting.FunctionalTests.LinkedApplicationTests.LinkedApplicationWorks() in /_/src/Hosting/test/FunctionalTests/LinkedApplicationTests.cs:line 51
--- End of stack trace from previous location ---
```

**Comment by Tratcher** [comment]
That smells like connection draining corruption. @scalablecory

**Comment by scalablecory** [comment]
Can you please verify that Kestrel is sending correct bytes?

**Comment by davidfowl** [comment]
I added more logs

**Comment by jkotalik** [comment]
Gonna close in the mean time until we get logs.
