### ISSUE TITLE
Flaky test: CanInfluenceHeadDuringPrerender 

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#24602]
https://dev.azure.com/dnceng/public/_build/results?buildId=758508&view=ms.vss-test-web.build-test-results-tab&runId=23551644&resultId=100319&paneView=debug

```
Windows_Test-xunit_1
Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.PrerenderingTest.CanInfluenceHeadDuringPrerender
Duration0:02:01.764
Failing build20200805.35

Error message
OpenQA.Selenium.BrowserAssertFailedException : OpenQA.Selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document
  (Session info: headless chrome=84.0.4147.105)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17763 x86_64)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.GetAttribute(String attributeName)
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass3_01.<Equal>b__0() in //src/Shared/E2ETesting/WaitAssert.cs:line 24
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_0.<WaitAssertCore>b__0() in //src/Shared/E2ETesting/WaitAssert.cs:line 80
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver ) in //src/Shared/E2ETesting/WaitAssert.cs:line 106
Screen shot captured at 'F:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.AspNetCore.Components.E2ETests\4e9493872c554a0788c111cf04491ddf.png'
Encountered browser errors
[2020-08-05T22:02:33Z] [Info] http://127.0.0.1:64422/prerendered/_framework/blazor.server.js 18:23362 "[2020-08-05T22:02:32.997Z] Information: Starting up blazor server-side application."
[2020-08-05T22:02:33Z] [Info] http://127.0.0.1:64422/prerendered/_framework/blazor.server.js 0:5679 "[2020-08-05T22:02:33.006Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:64422/prerendered/_blazor'."
[2020-08-05T22:02:33Z] [Info] http://127.0.0.1:64422/prerendered/_framework/blazor.server.js 0:5679 "[2020-08-05T22:02:33.067Z] Information: WebSocket connected to ws://127.0.0.1:64422/prerendered/_blazor?id=_GXKN-JM0DPSt3RGUYwBsw."
[2020-08-05T22:02:33Z] [Info] http://127.0.0.1:64422/prerendered/_framework/blazor.server.js 18:23445 "[2020-08-05T22:02:33.128Z] Debug: Received render batch with id 2 and 1679 bytes."
[2020-08-05T22:02:33Z] [Info] http://127.0.0.1:64422/prerendered/_framework/blazor.server.js 18:23445 "[2020-08-05T22:02:33.133Z] Debug: Applying batch 2."
[2020-08-05T22:02:33Z] [Info] http://127.0.0.1:64422/prerendered/_framework/blazor.server.js 18:23362 "[2020-08-05T22:02:33.152Z] Information: Blazor server-side application started."
[2020-08-05T22:02:33Z] [Info] http://127.0.0.1:64422/prerendered/_framework/blazor.server.js 18:23445 "[2020-08-05T22:02:33.173Z] Debug: Received render batch with id 3 and 176 bytes."
[2020-08-05T22:02:33Z] [Info] http://127.0.0.1:64422/prerendered/_framework/blazor.server.js 18:23445 "[2020-08-05T22:02:33.173Z] Debug: Applying batch 3."
[2020-08-05T22:02:48Z] [Info] http://127.0.0.1:64422/prerendered/_framework/blazor.server.js 18:23362 "[2020-08-05T22:02:48.196Z] Information: Starting up blazor server-side application."
[2020-08-05T22:02:48Z] [Info] http://127.0.0.1:64422/prerendered/_framework/blazor.server.js 0:5679 "[2020-08-05T22:02:48.198Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:64422/prerendered/_blazor'."
[2020-08-05T22:02:48Z] [Info] http://127.0.0.1:64422/prerendered/_framework/blazor.server.js 0:5679 "[2020-08-05T22:02:48.211Z] Information: WebSocket connected to ws://127.0.0.1:64422/prerendered/_blazor?id=_EjsUC_yRkuK9WP2g7TrfQ."
[2020-08-05T22:02:48Z] [Info] http://127.0.0.1:64422/prerendered/_framework/blazor.server.js 18:23445 "[2020-08-05T22:02:48.222Z] Debug: Received render batch with id 2 and 2438 bytes."
[2020-08-05T22:02:48Z] [Info] http://127.0.0.1:64422/prerendered/_framework/blazor.server.js 18:23445 "[2020-08-05T22:02:48.223Z] Debug: Applying batch 2."
[2020-08-05T22:02:48Z] [Info] http://127.0.0.1:64422/prerendered/_framework/blazor.server.js 18:23362 "[2020-08-05T22:02:48.229Z] Information: Blazor server-side application start


Stack trace
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 126
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore(IWebDriver driver, Action assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 81
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.Equal[T](IWebDriver driver, T expected, Func`1 actual) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 24
   at Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.PrerenderingTest.CanInfluenceHeadDuringPrerender() in /_/src/Components/test/E2ETest/ServerExecutionTests/PrerenderingTest.cs:line 117
----- Inner Stack Trace -----
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.GetAttribute(String attributeName)
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass3_0`1.<Equal>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 24
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 80
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__
```

**Comment by HaoK** [comment]
Looks like this was fixed in https://github.com/dotnet/aspnetcore/pull/24624
