### ISSUE TITLE
Support two-way biding for 'value' property for custom elements

### ISSUE THREAD

**Issue by uabarahona** [dotnet/aspnetcore#24628]
### Description
Right now, is not possible to add a two-way biding to the property 'value' of a custom element, you can do a two-way biding to the attribute value, but attribute value and property value are not the same:

![image](https://user-images.githubusercontent.com/15148088/89569525-d5f6cc00-d7f2-11ea-9bf5-c0ee331a146b.png)

When you try to bind to the property value an exception is displayed: 

```
Uncaught (in promise) DOMException: Failed to execute 'setAttribute' on 'Element': '@bind' is not a valid attribute name.
    at e.applyAttribute (https://localhost:44395/_framework/blazor.server.js:8:37951)
    at e.insertElement (https://localhost:44395/_framework/blazor.server.js:8:37062)
    at e.insertFrame (https://localhost:44395/_framework/blazor.server.js:8:35939)
    at e.insertFrameRange (https://localhost:44395/_framework/blazor.server.js:8:39834)
    at e.insertElement (https://localhost:44395/_framework/blazor.server.js:8:37019)
    at e.insertFrame (https://localhost:44395/_framework/blazor.server.js:8:35939)
    at e.applyEdits (https://localhost:44395/_framework/blazor.server.js:8:34325)
    at e.updateComponent (https://localhost:44395/_framework/blazor.server.js:8:33641)
    at Object.t.renderBatch (https://localhost:44395/_framework/blazor.server.js:1:70742)
    at e.<anonymous> (https://localhost:44395/_framework/blazor.server.js:19:18070)
```

**Comment by pranavkm** [comment]
This should be possible, although we need to document it. Parking this as a doc item.

**Comment by pranavkm** [comment]
After further discussion, this might need some design work to implement.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
