### ISSUE TITLE
Blazor Influence HTML head “Could not find '_blazorHeadManager' in 'window'.”

### ISSUE THREAD

**Issue by hueifeng** [dotnet/aspnetcore#24661]
### Describe the bug

In the blazor server I use the `Title` in ` Microsoft.AspNetCore.Components.Web.Extensions` but the error content is as follows:

```
blazor.server.js:19 [2020-08-07T16:31:50.477Z] Error: Microsoft.JSInterop.JSException: Could not find '_blazorHeadManager' in 'window'.
Error: Could not find '_blazorHeadManager' in 'window'.
    at https://localhost:5001/_framework/blazor.server.js:1:68326
    at Array.forEach (<anonymous>)
    at p (https://localhost:5001/_framework/blazor.server.js:1:68286)
    at https://localhost:5001/_framework/blazor.server.js:1:68996
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.server.js:1:68969)
    at https://localhost:5001/_framework/blazor.server.js:1:26303
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:5001/_framework/blazor.server.js:1:26273)
    at e.processIncomingData (https://localhost:5001/_framework/blazor.server.js:1:24211)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Microsoft.AspNetCore.Components.Web.Extensions.Head.Title.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

### To Reproduce

```
  <ItemGroup> 
    <PackageReference Include="Microsoft.AspNetCore.Components.Web.Extensions" Version="5.0.0-rc.1.20404.11"/>
  </ItemGroup>
```
code:

```
@using Microsoft.AspNetCore.Components.Web.Extensions.Head
```

### Versions
- 5.0.100-rc.1.20405.3 sdk

**Comment by pranavkm** [comment]
@hueifeng the extension package requires a JS file to be included. We'll document this as part of the RC1 release. @MackinnonBuck can you share what this script looks like?

**Comment by MackinnonBuck** [comment]
@hueifeng Add this to the `<body>` of your `_Host.cshtml`:

```cshtml
<script src="_content/Microsoft.AspNetCore.Components.Web.Extensions/headManager.js"></script>
```

In the future, this might not be necessary with the introduction of `JSObjectReference`.

**Comment by hueifeng** [comment]
OK, thank you.
