### ISSUE TITLE
SignalR - The remote party closed the WebSocket connection without completing the close handshake

### ISSUE THREAD

**Issue by mawaru29** [dotnet/aspnetcore#24689]
Hey Guys,

I've seen this error mentioned but I'm not clear what the resolution is. Here's my setup:
- JavaScript Client - "@aspnet/signalr": "^1.1.4",
- Server .NET Core 3.1
- nginx proxy

```
      Socket connection closed prematurely.
System.Net.WebSockets.WebSocketException (2): The remote party closed the WebSocket connection without completing the close handshake. ---> System.Net.WebSockets.WebSocketException (2): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure) in /_/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs:line 1235
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure) in /_/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs:line 1213
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter) in /_/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs:line 656
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter) in /_/src/Common/src/System/Net/WebSockets/ManagedWebSocket.cs:line 771
   at Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsServerTransport.StartReceiving(WebSocket socket)
```

The client has logic to make a call hubconnection.Stop() that is triggered frequently based on a user click action. Server-side there is a call to broadcast to all the clients: 
await _hubContext.Clients.All.SendAsync("updateStatus", msg);

What I suspect is that the server doesn't handle the close correctly hence the error. So either the client shouldn't stop the connection in this manner (and only stop the connection when a disconnection is needed) or is should the client disconnection be handled different server-side where I would remove the connection from a group. Then only broadcast to this updated group?

Thanks,
Roland

**Comment by BrennanConroy** [comment]
> hence the error

This is a debug log and sort of expected if the WebSocket is closed while you're reading from it.

If the WebSocket close is unexpected you should take a look at either why the client is closing the connection or if nginx is terminating the WebSocket.
