### ISSUE TITLE
Quarantine ServerExecutionTests.ServerGlobalizationTest.CanSetCultureAndParseCultureSensitiveNumbersAndDates

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#24692]
```
---- Assert.Equal() Failure
Expected: 9000
Actual:   0
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 126
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore(IWebDriver driver, Action assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 80
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.Equal[T](IWebDriver driver, T expected, Func`1 actual) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 24
   at Microsoft.AspNetCore.Components.E2ETests.Tests.GlobalizationTest`1.CanSetCultureAndParseCultureSensitiveNumbersAndDates(String culture) in /_/src/Components/test/E2ETest/Tests/GlobalizationTest.cs:line 42
```

Build failure in https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=762041&view=logs&jobId=6c33d704-163a-5170-38fa-caa7bc99f17c

**Comment by HaoK** [comment]
Tracking via https://github.com/dotnet/aspnetcore/issues/26285
