### ISSUE TITLE
Quarantined test: LinkedApplicationTests.LinkedApplicationWorks

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#24755]
Build failure: https://dev.azure.com/dnceng/public/_build/results?buildId=763379&view=ms.vss-test-web.build-test-results-tab&runId=23716264&resultId=100000&paneView=debug

```C#
 at System.Net.Http.HttpConnection.ParseStatusLine(Span`1 line, HttpResponseMessage response)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IntegrationTesting.LoggingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/Hosting/Server.IntegrationTesting/src/Common/LoggingHandler.cs:line 23
   at System.Net.Http.HttpClient.FinishSendAsync(ValueTask`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts, Boolean buffered, Boolean async, CancellationToken callerToken, Int64 timeoutTime)
   at Microsoft.AspNetCore.Server.IntegrationTesting.RetryHelper.RetryRequest(Func`1 retryBlock, ILogger logger, CancellationToken cancellationToken, Int32 retryCount) in /_/src/Hosting/Server.IntegrationTesting/src/Common/RetryHelper.cs:line 39
   at Microsoft.AspNetCore.Server.IntegrationTesting.RetryHelper.RetryRequest(Func`1 retryBlock, ILogger logger, CancellationToken cancellationToken, Int32 retryCount) in /_/src/Hosting/Server.IntegrationTesting/src/Common/RetryHelper.cs:line 55
   at Microsoft.AspNetCore.Hosting.FunctionalTests.LinkedApplicationTests.LinkedApplicationWorks() in /_/src/Hosting/test/FunctionalTests/LinkedApplicationTests.cs:line 51
--- End of stack trace from previous location ---
```

**Comment by davidfowl** [comment]
Turns out the failed run has no logs because they weren't captured....

**Comment by dougbu** [comment]
The history of this test is horribad. Why wasn't it skipped❔ We want the quarantined runs to at least have a chance of being clean.

Runs in main haven't passed since the 18th:
![image](https://user-images.githubusercontent.com/6431421/112519215-615ba800-8d57-11eb-96ba-c014746793a8.png)

**Comment by davidfowl** [comment]
I wonder if its just broken at this point.

**Comment by dougbu** [comment]
Looks that way

**Comment by pranavkm** [comment]
Yup. I think it broke almost immediately after this was checked in and I never followed up on it. Happy to skip it. We do have CTI validating this, but we should make this work.
