### ISSUE TITLE
Investigate `CanUseViewportAsContainer` test failure

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#24922]
Test failed in https://dev.azure.com/dnceng/public/_build/results?buildId=770042 with the following details:
``` text
OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.NotEqualException: Assert.NotEqual() Failure
Expected: Not "height: 0px;"
Actual:   "height: 0px;"
 at Xunit.Assert.NotEqual[T](T expected, T actual, IEqualityComparer1 comparer) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\EqualityAsserts.cs:line 143
 at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 80
 at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_01.<WaitAssertCore>b__0(IWebDriver ) in //src/Shared/E2ETesting/WaitAssert.cs:line 106
Screen shot captured at 'F:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.AspNetCore.Components.E2ETests\9bf01489259c44e79bc88ed4bba1080a.png'
Encountered browser errors
[2020-08-14T00:13:18Z] [Debug] http://127.0.0.1:60011/subdir/_framework/dotnet.5.0.0-rc.1.20371.13.js 0:126676 "mono_wasm_runtime_ready" "fe00e07a-5519-4dfe-b35a-f867dbaf2e28"Page content:
<head>
    <meta charset="utf-8">
    <title>Basic test app</title>
    <base href="/subdir/">
    <link href="style.css" rel="stylesheet">

    
    <link href="_content/TestContentPackage/styles.css" rel="stylesheet">
</head>

<body>
    <root><div id="test-selector">
    Select test:
    <select id="test-selector-select"><option value="none">Choose...
        <option value="BasicTestApp.AfterRenderInteropComponent">After-render interop component
        <option value="BasicTestApp.AuthTest.AuthRouter">Auth cases
        <option value="BasicTestApp.BindCasesComponent">bind cases
        <option value="BasicTestApp.ComponentRefComponent">Component ref component
        <option value="BasicTestApp.ConfigurationComponent">Configuration
        <option value="BasicTestApp.CounterComponentUsingChild">Counter using child component
        <option value="BasicTestApp.CulturePicker">Culture Picker
        <option value="BasicTestApp.DispatchingComponent">Dispatching to sync context
        <option value="BasicTestApp.ElementFocusComponent">Element focus component
        <option value="BasicTestApp.ErrorComponent">Error throwing
        <option value="BasicTestApp.EventCallbackTest.EventCallbackCases">EventCallback
        <option value="BasicTestApp.EventDisablingComponent">Event disabling

Stack trace
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 126
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore(IWebDriver driver, Action assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 81
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.NotEqual[T](IWebDriver driver, T expected, Func`1 actual) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 27
   at Microsoft.AspNetCore.Components.E2ETests.Tests.VirtualizationTest.CanUseViewportAsContainer() in /_/src/Components/test/E2ETest/Tests/VirtualizationTest.cs:line 204
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 80
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 106
```
![9bf01489259c44e79bc88ed4bba1080a](https://user-images.githubusercontent.com/6431421/90299576-62386d00-de4b-11ea-85b3-b4ec2d08c985.png)

**Comment by dougbu** [comment]
Test will be quarantined in dotnet/aspnetcore#24924

**Comment by dougbu** [comment]
Test _was_ quarantined in 0f3c52e84c4c

**Comment by HaoK** [comment]
Note: this doesn't repro locally (on VS runs)

**Comment by captainsafia** [comment]
This is resolved now.

**Comment by HaoK** [comment]
Reopening and splitting from the mega tracking issue for individual tracking as this failed recently 3/17

**Comment by captainsafia** [comment]
@HaoK Do you recall what the failure was that occurred on 3/17?

I checked the data over the past 30 days and it looks like it failed due to:

```
Couldn't create a Selenium remote driver client. The server is irresponsive\r\n---- System.InvalidOperationException : session not created: This version of ChromeDriver only supports Chrome version 87\nCurrent browser version is 90.0.4430.93 with binary path C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe\nBuild info: version: '3.141.5', revision: 'd54ebd709a', time: '2018-11-06T11:58:47'\nSystem info: host: 'a000ABY', ip: '10.0.0.6', os.name: 'Windows Server 2016', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.3'\nDriver info: driver.version: unknown\nremote stacktrace: Backtrace:\n\tOrdinal0 [0x0056ECE3+3337443]\n\tOrdinal0 [0x0044F041+2158657]\n\tOrdinal0 [0x002D6FA8+618408]\n\tOrdinal0 [0x00251D52+73042]\n\tOrdinal0 [0x0024E0D8+57560]\n\tOrdinal0 [0x0024C38A+50058]\n\tOrdinal0 [0x00275E8E+220814]\n\tOrdinal0 [0x00275BFC+220156]\n\tOrdinal0 [0x0027181B+202779]\n\tOrdinal0 [0x00253D74+81268]\n\tOrdinal0 [0x00254D6E+85358]\n\tOrdinal0 [0x00254CF9+85241]\n\tOrdinal0 [0x00466F2C+2256684]\n\tGetHandleVerifier [0x006F2FAC+1478332]\n\tGetHandleVerifier [0x006F2AFD+1477133]\n\tGetHandleVerifier [0x006FAAD8+1509864]\n\tGetHandleVerifier [0x006F369E+1480110]\n\tOrdinal0 [0x0045D6BD+2217661]\n\tOrdinal0 [0x004689AB+2263467]\n\tOrdinal0 [0x00468AEF+2263791]\n\tOrdinal0 [0x0047D363+2347875]\n\tBaseThreadInitThunk [0x767E0419+25]\n\tRtlGetAppContainerNamedObjectPath [0x772272AD+237]\n\tRtlGetAppContainerNamedObjectPath [0x7722727D+189]\n (SessionNotCreated)
```

Seems like something that would be solved by our recent Selenium upgrade in https://github.com/dotnet/aspnetcore/commit/eaf763996a447a5671b679e8e6edeb90d1578918.

**Comment by HaoK** [comment]
Yeah I don't remember anymore, if that's the only failure seems safe to give it another chance
