### ISSUE TITLE
SignalR WebSocket exception when upgrading to latest System.Collections.Immutable library

### ISSUE THREAD

**Issue by jc1001** [dotnet/aspnetcore#24998]
### Describe the bug
I have a .NET Core 2 application that is targeting the full .NET Framework (v4.8).  
It hosts a web server (using HttpSys) that exposes a SignalR hub.
I can make a successful call from a client (in this case a .NET console application) to the SignalR hub.

When I upgrade the [System.Collections.Immutable](https://www.nuget.org/packages/System.Collections.Immutable/1.7.1) library on the server to v1.7.1, the connection call from the client application to the SignalR hub on the server fails with a WebSocketException. 

### To Reproduce
I have attached a sample solution that reproduces the problem.
[SignalRBug.zip](https://github.com/dotnet/aspnetcore/files/5090112/SignalRBug.zip)

The solution contains 2 projects: "Client" and "Server".
An instance of "Server" must be running (hosting on http://localhost:8080) before you can execute "Client".
The example (as attached) will run without any errors.

When you edit the Server.csproj file to include the latest version of the System.Collections.Immutable library, the client application will fail as described above.

### Exceptions (if any)
WebSocketException
![WebSocketException](https://user-images.githubusercontent.com/15125812/90509103-18a49680-e159-11ea-93ed-6d39beb70a70.png)

Message: The remote party closed the WebSocket connection without completing the close handshake.
Stack trace:
```
   at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__19.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__45.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.<StartReceiving>d__19.MoveNext()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<HandshakeAsync>d__61.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsyncCore>d__47.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsyncCore>d__47.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<StartAsync>d__39.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Client.Program.<Main>d__0.MoveNext() in D:\Temp\SignalRBug\Client\Program.cs:line 17
```

### Further technical details
- .NET Framework 4.8
- Microsoft Visual Studio Enterprise 2019, Version 16.7.1
- Windows 10, version 2004 (Build: 19041.450)

**Comment by jc1001** [comment]
Thank you for the feedback.

I had a look at the fusion log viewer and can see that the server is trying to load both version 4.1.4 and version 4.1.3 of the System.Numerics.Vectors dll.  

![Fusion log viewer](https://user-images.githubusercontent.com/15125812/91056692-915a9580-e626-11ea-9dc1-76fa7f2e83d5.png)

The output directory of the server does contain version 4.1.4 of this dll, so that one loads successfully.  4.1.3 fails because there does not seem to be a binding redirect in the config file.

I did confirm that manually adding a binding redirect solves the problem, but I would have expected this to be done by the compiler (like it does for all the other required binding redirects)?

![Binding redirect](https://user-images.githubusercontent.com/15125812/91057777-f5ca2480-e627-11ea-8de1-c91227e7f0fd.png)

**Comment by BrennanConroy** [comment]
Glad you got it working. I don't think there is anything we can do on our side here.

You might want to try asking in the NuGet repo: https://github.com/NuGet/NuGet.Client

**Comment by jc1001** [comment]
@BrennanConroy, I've raised this issue on the runtime project (https://github.com/dotnet/runtime/issues/41597).  Seems that it is caused by an older version of the `System.Net.WebSockets.WebSocketProtocol` library (v4.5.1).  The latest version of the library (v4.7.1) does fix this issue.  They provided a workaround (adding a reference to the latest library).  

I'm not sure if it would be possible to update the relevant NuGet packages to reference the newer libraries to prevent other people from running into the same error?  If not, I can always stick with the workaround.
