### ISSUE TITLE
The SSL connection could not be established, see inner exception. Authentication failed, see inner exception.

### ISSUE THREAD

**Issue by ToMyAF** [dotnet/aspnetcore#25032]
![image](https://user-images.githubusercontent.com/36257915/90585264-05500480-e207-11ea-8925-5f3549569409.png)
I don't do certificate validation, but it always prompts for this exception

**Comment by quan0zhou** [comment]
ServicePointManager.ServerCertificateValidationCallback += (object sender, X509Certificate cer, X509Chain chain, SslPolicyErrors sslPolicyErrors) =>
            {
                return true;
            };
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;

**Comment by ToMyAF** [comment]
![image](https://user-images.githubusercontent.com/36257915/90595433-756a8480-e21f-11ea-81f5-b3d651165c6e.png)
Do you try? Is it OK?

**Comment by ToMyAF** [comment]
![image](https://user-images.githubusercontent.com/36257915/90595906-689a6080-e220-11ea-9b3e-b2a89f0ccc8d.png)
Have you tried? Is it OK?

**Comment by Tratcher** [comment]
What's the full exception and stack?

ServicePointManager doesn't apply.

That's too many SslProtocols. Set that to None and it will use the system default.

**Comment by ToMyAF** [comment]
The SSL connection could not be established, see inner exception. Authentication failed, see inner exception.

This is ok ?

**Comment by ToMyAF** [comment]
This is detail.

System.AggregateException: One or more errors occurred. (An error occurred while sending the request.)
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.Net.Http.CurlException: SSL connect error
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at ERP.Facade.JhCCBQrPayCore.Interface.DefaultHttpCoreClient.DoPost[T](T netParam)
   at ERP.Facade.JhCCBQrPayCore.Interface.DefaultClient.Excute[T](CCBRequest`1 req)
   at ERP.Facade.JhCCBQrPayCore.Facade.CCBQrPay(Hashtable ht)InnnerException:System.AggregateException: One or more errors occurred. (An error occurred while sending the request.)
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.Net.Http.CurlException: SSL connect error
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at ERP.Facade.JhCCBQrPayCore.Interface.DefaultHttpCoreClient.DoPost[T](T netParam)
   at ERP.Facade.JhCCBQrPayCore.Interface.DefaultClient.Excute[T](CCBRequest`1 req)
   at ERP.Facade.JhCCBQrPayCore.Facade.CCBQrPay(Hashtable ht)
