### ISSUE TITLE
Flaky Test Building_WorksWhenMultipleRazorConfigurationsArePresent

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#25042]
https://dev.azure.com/dnceng/public/_build/results?buildId=777340&view=ms.vss-test-web.build-test-results-tab&runId=24327670&paneView=debug&resultId=100170

```
Building_WorksWhenMultipleRazorConfigurationsArePresent [FAIL]
System.TimeoutException : command '$/Users/runner/work/1/s/.dotnet/dotnet msbuild /nr:false /bl /p:RunningAsTest=true /p:MicrosoftNETCoreAppRuntimeVersion=5.0.0-rc.1.20417.14 /p:MicrosoftNetCompilersToolsetPackageVersion=3.8.0-2.20407.3 /p:RazorSdkDirectoryRoot=/Users/runner/work/1/s/artifacts/bin/Microsoft.NET.Sdk.Razor/Release/sdk-output/ /p:RepoRoot=/Users/runner/work/1/s/ /p:_RazorBuildServerPipeName="696de9f1-a757-4ccb-9310-aff33879b26e" /t:Build /p:Configuration=Release ' timed out after 00:08:00. Output: Microsoft (R) Build Engine version 16.8.0-preview-20379-02+8343d638e for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
      
/Users/runner/work/1/s/.dotnet/sdk/5.0.100-rc.1.20379.10/MSBuild.dll -maxcpucount -verbosity:m /bl /nr:false /p:RunningAsTest=true /p:MicrosoftNETCoreAppRuntimeVersion=5.0.0-rc.1.20417.14 /p:MicrosoftNetCompilersToolsetPackageVersion=3.8.0-2.20407.3 /p:RazorSdkDirectoryRoot=/Users/runner/work/1/s/artifacts/bin/Microsoft.NET.Sdk.Razor/Release/sdk-output/ /p:RepoRoot=/Users/runner/work/1/s/ /p:_RazorBuildServerPipeName=696de9f1-a757-4ccb-9310-aff33879b26e /p:Configuration=Release /t:Build ./SimpleMvc21.csproj
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
      
Stack Trace:
  /_/src/Shared/MSBuild.Testing/MSBuildProcessManager.cs(221,0): at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.<>c__DisplayClass2_0.<<RunProcessCoreAsync>g__GetTimeoutForProcess|3>d.MoveNext()
  --- End of stack trace from previous location ---
  /_/src/Shared/MSBuild.Testing/MSBuildProcessManager.cs(123,0): at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.RunProcessAsync(ProjectDirectory project, String arguments, Nullable`1 timeout, MSBuildProcessKind msBuildProcessKind)
  /_/src/Razor/Microsoft.NET.Sdk.Razor/integrationtests/MvcBuildIntegrationTest21.cs(33,0): at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MvcBuildIntegrationTest21.Building_WorksWhenMultipleRazorConfigurationsArePresent()
  --- End of stack trace from previous location ---
```

cc @pranavkm Since you touched some code around this area 2 days ago.

**Comment by HaoK** [comment]
@pranavkm FYI this test has also behaved well in quarantine recently 789/789 100% last 30 days

**Comment by HaoK** [comment]
Any concerns with reenabling?

**Comment by pranavkm** [comment]
I think there's currently an issue with diagnostic dumps produced by the SDK tests not being captured as part of AzDo. We've seen evidence in the past of hangs in other parts of the build infrastructure (CLI \ msbuild), In the absence of these dumps, it feels problematic to re-enable these tests since we wouldn't have learnt any more information about why these are hanging.

We could dupe this as part of #22552 if you'd like.

**Comment by HaoK** [comment]
Yup, dupe is good, I'm just trying to clean up/consolidate some of these issues
