### ISSUE TITLE
Unable to run IIS Express tests locally

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#25107]
This is blocking IIS feature work.

Repro steps:
Non-admin cmd
git clean -xdf
build.cmd at the root
build.cmd -Test in `src\Servers\IIS\`

The tests take almost two hours to fail, and produce a variety of errors. They don't work in VS either.

```
Time Elapsed 01:59:02.27
XUnit : error : Tests failed: D:\github\AspNetCore\artifacts\TestResults\Debug\IISExpress.FunctionalTests_net5.0_x64.html [net5.0|x64] [d:\github\AspNetCore\src\Servers\IIS\IIS\test\IISExpress.FunctionalTests\IISExpress.FunctionalTests.csproj]
```

Tests run: 324 — Failures: 97, Skipped: 29, Run time: 7111.325s, Finished: 08/20/2020 14:44:27

Most failures are shutdown failures, each taking 60 seconds to time out.
```
Microsoft.AspNetCore.Server.IIS.FunctionalTests.ClientDisconnectStressTests.ClientDisconnectStress(hostingModel: InProcess)
System.InvalidOperationException : iisexpress Process 14416 failed to gracefully shutdown.
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer.GracefullyShutdownProcess(Process hostProcess) in D:\github\AspNetCore\src\Servers\IIS\IntegrationTesting.IIS\src\IISExpressDeployer.cs:line 537
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer.Dispose(Boolean gracefulShutdown) in D:\github\AspNetCore\src\Servers\IIS\IntegrationTesting.IIS\src\IISExpressDeployer.cs:line 407
   at Microsoft.AspNetCore.Server.IntegrationTesting.FunctionalTestsBase.StopServer(Boolean gracefulShutdown) in d:\github\AspNetCore\src\Servers\IIS\IIS\test\Common.FunctionalTests\Utilities\FunctionalTestsBase.cs:line 62
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.ClientDisconnectStressTests.ClientDisconnectStress(HostingModel hostingModel) in d:\github\AspNetCore\src\Servers\IIS\IIS\test\Common.FunctionalTests\ClientDisconnectStress.cs:line 62
--- End of stack trace from previous location ---
```

This test seems to be broken, notice the casing difference.
```
 Microsoft.AspNetCore.Server.IIS.FunctionalTests.HttpsTests.ServerAddressesIncludesBaseAddress
Assert.Equal() Failure
                                 ↓ (pos 25)
Expected: ···://localhost:44300/МоёПриложение
Actual:   ···://localhost:44300/МОЁПРИЛОЖЕНИЕ
                                 ↑ (pos 25)
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.HttpsTests.ServerAddressesIncludesBaseAddress() in d:\github\AspNetCore\src\Servers\IIS\IIS\test\Common.FunctionalTests\HttpsTests.cs:line 93
--- End of stack trace from previous location ---
```

Permissions or file in use?
```
 Microsoft.AspNetCore.Server.IIS.FunctionalTests.OutOfProcess.GlobalVersionTests.GlobalVersion_EnvironmentVariableWorks
System.UnauthorizedAccessException : Access to the path 'C:\\Users\\chrross\\AppData\\Local\\Temp\\tmpB17F.tmp' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.OutOfProcess.GlobalVersionTests.GlobalVersion_EnvironmentVariableWorks() in d:\github\AspNetCore\src\Servers\IIS\IIS\test\Common.FunctionalTests\OutOfProcess\GlobalVersionTests.cs:line 69
--- End of stack trace from previous location ---
```

I've tried this on stable Win10 19041.450 as well as Windows Insiders Dev.

cc @jkotalik

**Comment by jkotalik** [comment]
I pinged the windows team over the shutdown issues all tests are having locally; my gut says it's potentially an issue with HTTP.SYS.

**Comment by jkotalik** [comment]
ServerAddressesIncludesBaseAddress also is failing due to the timeout issue.

**Comment by Tratcher** [comment]
We're moving the main test queue from 20h1 to 20h2 and we're going to loose a lot of IIS test coverage since the affected tests are skipped after 20h1.

Wasn't one of the main questions here about when the regression happened in Windows? All the tests indicate it regressed in 20h2.

**Comment by jkotalik** [comment]
I think this gives us another datapoint for us to go to the IIS/HTTP.SYS team. We should probably reach out again.

**Comment by jkotalik** [comment]
Note: this is currently only an issue on IISExpress for me locally. It isn't affecting 20H2 either now.

**Comment by HaoK** [comment]
This no longer seems to be an issue on Windows 11 21H2 (OS Build 22000.493), will remove all of the SkipOnNonHelix as part of ANCM work

**Comment by HaoK** [comment]
Most tests have been reenabled as of https://github.com/dotnet/aspnetcore/pull/39810

**Comment by Tratcher** [comment]
A partner team found a similar regression with Asp.Net 4.x when migrating from Server 2016 to 2022 back in June. They tracked it down to a handle duplication regression in IIS that should be patched soon.
