### ISSUE TITLE
Asp.net core 3.1 JWT Audience Validation failed. Works on windows but not on linux.

### ISSUE THREAD

**Issue by md-hashmi** [dotnet/aspnetcore#25173]
### Describe the bug

I have an aspnet core 3.1 API that uses JWT authentication. Tokens are provided from 3rd party. Token validation seems to fail due to 

```
Failed to validate the token.
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. 
Audiences: 'dbbec85987d64bb095ec142ba3368272'. Did not match: validationParameters.ValidAudience: 'dbbec85987d64bb095ec142ba3368272' 
or validationParameters.ValidAudiences: 'null'.
```

The expected and actual values do match exactly in the server debug logs with PII display enabled. They also match exactly the aud value in the jwt token as decoded on jwt.io. 

### Note: Additionally, the authentication works just fine with the exact same code and config/env vars running on a windows host but fails on a linux host. 

Startup.cs is setup as follows
```
public void ConfigureServices(IServiceCollection services) {
...
   services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            .AddJwtBearer(options =>
            {
                options.Authority = Configuration["Auth:Issuer"];
                options.Audience = Configuration["Auth:Aud"]; //set to the apps client id as shown in 3rd parties oauth config
            });
...
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env) {
...
            app.UseAuthentication();
            app.UseAuthorization();
...
}
```

### Exceptions (if any)
```
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[1]
      Failed to validate the token.
Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: 'dbbec85987d64bb095ec142ba3368272'. Did not match: validationParameters.ValidAudience: 'dbbec85987d64bb095ec142ba3368272' or validationParameters.ValidAudiences: 'null'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateAudience(IEnumerable`1 audiences, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateAudience(IEnumerable`1 audiences, JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[7]
      Bearer was not authenticated. Failure message: IDX10214: Audience validation failed. Audiences: 'dbbec85987d64bb095ec142ba3368272'. Did not match: validationParameters.ValidAudience: 'dbbec85987d64bb095ec142ba3368272' or validationParameters.ValidAudiences: 'null'.
```
### Further technical details
Using Microsoft.AspNetCore.Authentication.JwtBearer v 3.1.0

- Works on windows host with dotnet core 3.1.6
- Does not work on mcr.microsoft.com/dotnet/core/sdk:3.1 image

**Comment by md-hashmi** [comment]
On further investigation, it was a newline issue only manifesting on the linux system. Was a bit hard to see in the logs but with the newline character removed from the Aud value, this is now working fine.
