### ISSUE TITLE
Test  HtmlGenerationWebSite_GeneratesExpectedResults fails

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#25206]
> System.OperationCanceledException : The operation was canceled.
>    at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
   at System.Net.Http.HttpClient.FinishSendAsync(ValueTask`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts, Boolean buffered, Boolean async, CancellationToken callerToken, Int64 timeoutTime)
   at Microsoft.AspNetCore.Mvc.FunctionalTests.HtmlGenerationTest.HtmlGenerationWebSite_GeneratesExpectedResults(String action, String antiforgeryPath) in /_/src/Mvc/test/Mvc.FunctionalTests/HtmlGenerationTest.cs:line 111
--- End of stack trace from previous location ---

https://dev.azure.com/dnceng/public/_build/results?buildId=784906&view=ms.vss-test-web.build-test-results-tab&runId=24707436&resultId=101347&paneView=debug

**Comment by dougbu** [comment]
Please link to the failing build.

**Comment by wtgodbe** [comment]
Another failure here

**Comment by captainsafia** [comment]
It looks like it's failing with a different stack trace now.

```
Manifest resource 'Microsoft.AspNetCore.Mvc.FunctionalTests.compiler.resources.HtmlGenerationWebSite.HtmlGeneration_Home.image.html' not found.\r\nExpected: True\r\nActual:   False
   at Microsoft.AspNetCore.Mvc.ResourceFile.GetResourceStream(Assembly assembly, String resourceName, Boolean sourceFile) in /_/src/Mvc/test/Mvc.FunctionalTests/Infrastructure/ResourceFile.cs:line 59
   at Microsoft.AspNetCore.Mvc.ResourceFile.ReadResourceAsync(Assembly assembly, String resourceName, Boolean sourceFile) in /_/src/Mvc/test/Mvc.FunctionalTests/Infrastructure/ResourceFile.cs:line 111
   at Microsoft.AspNetCore.Mvc.FunctionalTests.HtmlGenerationTest.HtmlGenerationWebSite_GeneratesExpectedResults(String action, String antiforgeryPath) in /_/src/Mvc/test/Mvc.FunctionalTests/HtmlGenerationTest.cs:line 105
   at Microsoft.AspNetCore.Mvc.FunctionalTests.HtmlGenerationTest.HtmlGenerationWebSite_GeneratesExpectedResults_WithImageData() in /_/src/Mvc/test/Mvc.FunctionalTests/HtmlGenerationTest.cs:line 144
```

https://dev.azure.com/dnceng/public/_build/results?buildId=787197&view=results

**Comment by pranavkm** [comment]
Resolved as part of https://github.com/dotnet/aspnetcore/pull/26834
