### ISSUE TITLE
[Blazor] ResolveBlazorRuntimeDependencies fails when creating a new Project

### ISSUE THREAD

**Issue by NBprojekt** [dotnet/aspnetcore#25234]
### Describe the bug
After creating a now Blazor WebAssembly App I get the Error `MSB4018	The "ResolveBlazorRuntimeDependencies" task failed unexpectedly.`

<details>
  <summary> Full error message </summary>
  
  ```
Error	MSB4018	The "ResolveBlazorRuntimeDependencies" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly 'Blazor-GithubPages.dll' or one of its dependencies. The system can not find the stated file.
File name: 'Blazor-GithubPages.dll' ---> System.IO.FileNotFoundException: The system can not find the stated file. (Exception from HRESULT: 0x80070002)
   at System.Reflection.AssemblyName.nGetFileInformation(String s)
   at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
   at Microsoft.AspNetCore.Components.WebAssembly.Build.ResolveBlazorRuntimeDependencies.ResolveRuntimeDependenciesCore(String entryPoint, IEnumerable`1 applicationDependencies, IEnumerable`1 monoBclAssemblies)
   at Microsoft.AspNetCore.Components.WebAssembly.Build.ResolveBlazorRuntimeDependencies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

	Blazor-GithubPages	
~\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview3.20168.3\targets\Blazor.MonoRuntime.targets	288	
  ```
</details>

I also tried to use [this workaround][workaround] but it did not work.

### To Reproduce

- Open visual studio
- Create new project -> Blazor App (Dont change anything just hit _Create_)
- When project load up hit <kbd>Ctrl</kbd> + <kbd>F5</kbd>

### Further technical details
- ASP.NET Core 3.1.2
- Include the output of `dotnet --info` (expand below)
- IDE: VisualStudio 2019 and VisualStudio 2019 Preview

<details>
  <summary>`dotnet --info`</summary>
  
  ```bash
$ dotnet --info
.NET Core SDK (gem▒▒ "global.json"):
 Version:   3.1.300-preview-015048
 Commit:    13f19b4682

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300-preview-015048\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015048 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
  ```
</details>

[workaround]: https://github.com/dotnet/aspnetcore/issues/17644#issuecomment-563355603

**Comment by pranavkm** [comment]
>~\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0-preview3.20168.3

@NBprojekt that looks like a really old version of the package. Can you follow the preview release notes (e.g. https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-4-release-now-available/) to upgrade to an RTM version? If you continue seeing it once you upgrade to the RTM package, please file a new issue and we'll investigate.

**Comment by NBprojekt** [comment]
@pranavkm Thanks  for the quick response.

Just [updating my templates][updateTemplates] didn't to the job.  
I also had to update my _Visual Studio 2019 Preview_ to get it working again.


[updateTemplates]: https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-4-release-now-available/
