### ISSUE TITLE
Memory Cache Concurrency Error [TagHelperDescriptorJsonConverter]

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#25358]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1163909/unfortunatly-a-process-used-by-visual-has-encounte.html)._

---
[severity:I'm somewhat annoyed. A fix would be nice] [regression] [worked-in:VS2019 Pro 16.7.2]
Yellow bar error on solution first load.

Exact source for colution loaded is available here
<https://github.com/SimonGeering/AdminAssistant/commit/f2bab8d3417745befa699d41f108347d37841038>

Stack Trace Below:
```
System.ArgumentException : The index is equal to or greater than the length of the array, or the number of elements in the dictionary is greater than the available space from index to the end of the destination array.
   at System.Collections.Concurrent.ConcurrentDictionary`2.System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<TKey,TValue>>. CopyTo(KeyValuePair`2[] array,Int32 index)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1. <GetEnumerator>d__1.MoveNext()
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source,Int32 index)
   at Microsoft.CodeAnalysis.Razor.MemoryCache`2.Compact()
   at Microsoft.CodeAnalysis.Razor.MemoryCache`2.Set(TKey key,TValue value)
   at Microsoft.CodeAnalysis.Razor.Serialization.TagHelperDescriptorJsonConverter.ReadJson(JsonReader reader,Type objectType,Object existingValue,JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter,JsonReader reader,Type objectType,Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list,JsonReader reader,JsonArrayContract contract,JsonProperty containerProperty,String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader,Type objectType,JsonContract contract,JsonProperty member,Object existingValue,String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader,Type objectType,JsonContract contract,JsonProperty member,JsonContainerContract containerContract,JsonProperty containerMember,Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader,Type objectType,Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader,Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Microsoft.CodeAnalysis.Razor.Serialization.TagHelperResolutionResultJsonConverter.<>c__DisplayClass4_0. <ReadJson>b__0(String propertyName)
   at Microsoft.CodeAnalysis.Razor.Serialization.JsonReaderExtensions.ReadProperties(JsonReader reader,Action`1 onProperty)
   at Microsoft.CodeAnalysis.Razor.Serialization.TagHelperResolutionResultJsonConverter.ReadJson(JsonReader reader,Type objectType,Object existingValue,JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter,JsonReader reader,Type objectType,Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader,Type objectType,Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader,Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType,JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at StreamJsonRpc.JsonMessageFormatter.JsonRpcResult.GetResult[T]()
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Remote.RemoteEndPoint.InvokeAsync[T](<Unknown Parameters>)
```

---
#### Feedback Bot on 8/27/2020, 02:02 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Another VSTS issue of it: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1180064

**Comment by NTaylorMullen** [comment]
Another VSTS issue: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1179991

We may need to fix this in Preview3

**Comment by NTaylorMullen** [comment]
Another VSTS issue: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1179892

Ya we do. moving to Previwe3. @TanayParikh I know that your plate is full unassigning

**Comment by TanayParikh** [comment]
Just renaming for clarity.
