### ISSUE TITLE
Flaky test: Libuv.BindTests ListenAnyIP_IPv6_Success

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#25403]
Failure: https://dev.azure.com/dnceng/public/_build/results?buildId=792496&view=results
Logs:
```
System.IO.InvalidDataException : No StatusCode found in ''
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStatus(String response) in /_/src/Testing/src/HttpClientSlim.cs:line 139
   at Microsoft.AspNetCore.Testing.HttpClientSlim.ReadResponse(Stream stream) in /_/src/Testing/src/HttpClientSlim.cs:line 94
   at Microsoft.AspNetCore.Testing.HttpClientSlim.<>c__DisplayClass1_0.<<GetStringAsync>b__0>d.MoveNext() in /_/src/Testing/src/HttpClientSlim.cs:line 39
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Testing.HttpClientSlim.RetryRequest(Func`1 retryBlock) in /_/src/Testing/src/HttpClientSlim.cs:line 116
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(Uri requestUri, Boolean validateCertificate) in /_/src/Testing/src/HttpClientSlim.cs:line 28
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(String requestUri, Boolean validateCertificate) in /_/src/Testing/src/HttpClientSlim.cs:line 24
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.ListenAnyIP_Success(String[] testUrls, Int32 testPort) in /_/src/Servers/Kestrel/test/BindTests/AddressRegistrationTests.cs:line 393
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.ListenAnyIP_IPv6_Success() in /_/src/Servers/Kestrel/test/BindTests/AddressRegistrationTests.cs:line 361
--- End of stack trace from previous location ---
```

**Comment by BrennanConroy** [comment]
Triage: We believe this is a Mac only issue, and since the Libuv transport is obsolete now we're lowering the priority.
