### ISSUE TITLE
Error unprotecting the session  cookie.ryptographicException: The key {} was not found in the key ring.

### ISSUE THREAD

**Issue by duoenet** [dotnet/aspnetcore#25438]
Category: Microsoft.AspNetCore.Session.SessionMiddleware
EventId: 7
RequestId: 80012351-1400-3600-b63f-84710c7967bb
RequestPath: /usercenter/
SpanId: |36aeaa33-4f04d19787ec7705.
TraceId: 36aeaa33-4f04d19787ec7705
ParentId: 

Error unprotecting the session cookie.

Exception: 
System.Security.Cryptography.CryptographicException: The key {9ef64254-84d8-4b40-a526-49d99d5d7d12} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Session.CookieProtection.Unprotect(IDataProtector protector, String protectedText, ILogger logger)

**Comment by Tratcher** [comment]
Are you running more than one instance of the server?
See https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/web-farm?view=aspnetcore-3.1#dependent-components
