### ISSUE TITLE
error MSB6006: "yarn" exited with code 1.

### ISSUE THREAD

**Issue by sunny868** [dotnet/aspnetcore#25607]
### Describe the bug
Environment: x86_64 ubuntu-16.04
aspnetcore commit:  1bf292d47ac2a0ebda07d8a3f00355dd01915ad5

After I git clone the aspnetcore,then check branch release/3.1 tag3.1.7 , I build by run:
` ./build.sh --configuration Debug /p:DisableCrossgen=true /p:PortableBuild=true /p:SkipTests=true`
Then error occur:

`/nuget-caches/.nuget/packages/microsoft.build.tasks.git/1.0.0-beta2-19367-01/build/Microsoft.Build.Tasks.Git.targets(24,5): warning : Access to the path '/aspnetcore/src/submodules/MessagePack-CSharp/.git' is denied. The source code won't be available via Source Link. [/aspnetcore/src/Identity/test/Identity.FunctionalTests/Microsoft.AspNetCore.Identity.FunctionalTests.csproj]`

  SyntaxError: Unexpected token {
      at exports.runInThisContext (vm.js:53:16)
      at Module._compile (module.js:374:25)
      at Object.Module._extensions..js (module.js:417:10)
      at Module.load (module.js:344:32)
      at Function.Module._load (module.js:301:12)
      at Module.require (module.js:354:17)
      at require (internal/module.js:12:17)
      at Object.<anonymous> (/nuget-caches/.nuget/packages/yarn.msbuild/1.15.2/dist/bin/yarn.js:24:13)
      at Module._compile (module.js:410:26)
      at Object.Module._extensions..js (module.js:417:10)

`/aspnetcore/eng/targets/Npm.Common.targets(60,5): error MSB6006: "yarn" exited with code 1. [/aspnetcore/src/SignalR/clients/ts/signalr/signalr.npmproj]`
`/aspnetcore/src/Components/WebAssembly/WebAssembly.Authentication/src/Microsoft.AspNetCore.Components.WebAssembly.Authentication.csproj(62,5): error MSB6006: "yarn" exited with code 1.`

I don`t know why?

**Comment by sunny868** [comment]
I have known this problem is caused by the low version of nodejs v4.2.6， When I upate nodejs to v8.10.0 , it works normally.
thanks.
