### ISSUE TITLE
Returning Action result with no content gives 500 response error

### ISSUE THREAD

**Issue by CutieDaisy** [dotnet/aspnetcore#25673]
### Describe the bug
After updating to ASP.NET Core version 5.0.0-preview 8, 
when an action result with no content is returned I get a 500 response error

### To Reproduce
`  [HttpGet]
        public IActionResult Get()
        {
            return Ok(); // with no object returned;
           // return NoContent();
        }`

### Exceptions (if any)
Browser Response : Status Code: 500 Internal 

### Further technical details
- ASP.NET Core version 5.0.0-preview.8
- Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 
- Microsoft Visual Studio Enterprise 2019 Preview
   Version 16.8.0 Preview 2.1

**Comment by Tratcher** [comment]
Please share the server logs, a 500 usually indicates an exception was thrown.

**Comment by CutieDaisy** [comment]
Thanks for the quick response

Server Log : 
Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer[2]
      Connection ID "18230571301796315327", Request ID "800000c2-0002-fd00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IResettableService.ResetStateAsync(CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Internal.DbContextPool`1.ReturnAsync(IDbContextPoolable context, CancellationToken cancellationToken)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.<DisposeAsync>g__Await|15_0(Int32 i, ValueTask vt, List`1 toDispose)
         at Microsoft.AspNetCore.Http.Features.RequestServicesFeature.<DisposeAsync>g__Awaited|9_0(RequestServicesFeature servicesFeature, ValueTask vt)
         at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.FireOnCompleted()
