### ISSUE TITLE
.net 5 preview.8 publish asp.net  single file can not found view

### ISSUE THREAD

**Issue by azraelrabbit** [dotnet/aspnetcore#25688]
### Describe the bug
when publish an asp.net core project by .net 5.0.100-preview.8.20417.9  ,
i use blow command to publish an single file .
 ` dotnet publish -c Debug -r linux-x64 /p:PublishSingleFile=true`
then deploy to ubuntu 18.04 x64 environment, and run as service.
when i access the web application, there is an error : The view 'Login' was not found.
 
### Exceptions (if any)
```
System.InvalidOperationException: The view 'Login' was not found. The following locations were searched:
/Views/Account/Login.en-US.cshtml
/Views/Account/Login.en.cshtml
/Views/Account/Login.cshtml
/Views/Shared/Login.en-US.cshtml
/Views/Shared/Login.en.cshtml
/Views/Shared/Login.cshtml
/Pages/Shared/Login.en-US.cshtml
/Pages/Shared/Login.en.cshtml
/Pages/Shared/Login.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Further technical details
- ASP.NET Core version :  .net  5.0.100-preview.8.20417.9 
 
- The IDE (VS / VS Code/ VS4Mac) you're running on: visual studio 2019  16.8.0 Preview 2.1

**Comment by javiercn** [comment]
@azraelrabbit thanks for contacting us.

I believe we have addressed this in a later preview. @pranavkm can confirm here.

**Comment by azraelrabbit** [comment]
@javiercn  thanks for reply.
i got it. i'll waiting for new version  .
