### ISSUE TITLE
Ambiguous routes logged incorrectly

### ISSUE THREAD

**Issue by davidni** [dotnet/aspnetcore#25694]
### Describe the bug

[`DefaultEndpointSelector.ReportAmbiguity`](https://github.com/dotnet/aspnetcore/blob/3d042ac9aaf6df4cfd1d2bd4a984a86a45629285/src/Http/Routing/src/Matching/DefaultEndpointSelector.cs#L125-L128) outputs **all** valid candidates in the resulting set, not just the ones with conflicting highest scores. Therefore, a wrong list of routes is claimed as ambiguous, whereas ambiguity was only among a subset of the printed routes.

### To Reproduce

1. Create conflicting routes such as:

  * `/a` with `Order=1`
  * `/a` with `Order=1`
  * `/{**catchall}` with `Order=1`

2. Issue a request against `/a`. Observe an `AmbiguousMatchException` is produced listing all 3 routes, but really there was only ambiguity among the first 2. The catch-all applies at a lower specificity, and hence is not ambiguous.

### Exceptions (if any)

```
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches: 

route1
route2
route3
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.SelectAsync(HttpContext httpContext, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
```

### Further technical details
- ASP.NET Core version 3.1.6 (issue still present on 5.0 by code inspection)

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
