### ISSUE TITLE
[release/3.1] Investigate flaky UserManagerSpecificationTests.CanChangeEmailOnlyIfEmailSame

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#25716]
```
System.Security.Cryptography.CryptographicException : An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information.\r\n---- System.IO.IOException : The process cannot access the file 'C:\Users\vsagent\AppData\Local\ASP.NET\DataProtection-Keys\key-70c4f01d-8a2b-4d38-ba84-6b9b8c19fac4.xml' because it is being used by another process.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext) in /_/src/DataProtection/DataProtection/src/KeyManagement/KeyRingBasedDataProtector.cs:line 141
   at Microsoft.AspNetCore.Identity.DataProtectorTokenProvider`1.GenerateAsync(String purpose, UserManager`1 manager, TUser user) in /_/src/Identity/Core/src/DataProtectorTokenProvider.cs:line 102
   at Microsoft.AspNetCore.Identity.Test.UserManagerSpecificationTestBase`2.CanChangeEmailOnlyIfEmailSame() in /_/src/Identity/Specification.Tests/src/UserManagerSpecificationTests.cs:line 1529
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenRead(String path)
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.ReadElementFromFile(String fullPath) in /_/src/DataProtection/DataProtection/src/Repositories/FileSystemXmlRepository.cs:line 102
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElementsCore()+MoveNext() in /_/src/DataProtection/DataProtection/src/Repositories/FileSystemXmlRepository.cs:line 83
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElements() in /_/src/DataProtection/DataProtection/src/Repositories/FileSystemXmlRepository.cs:line 68
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys() in /_/src/DataProtection/DataProtection/src/KeyManagement/XmlKeyManager.cs:line 152
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded) in /_/src/DataProtection/DataProtection/src/KeyManagement/KeyRingProvider.cs:line 64
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now) in /_/src/DataProtection/DataProtection/src/KeyManagement/KeyRingProvider.cs:line 273
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow, Boolean forceRefresh) in /_/src/DataProtection/DataProtection/src/KeyManagement/KeyRingProvider.cs:line 205
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRing() in /_/src/DataProtection/DataProtection/src/KeyManagement/KeyRingProvider.cs:line 149
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext) in /_/src/DataProtection/DataProtection/src/KeyManagement/KeyRingBasedDataProtector.cs:line 102
```

https://dev.azure.com/dnceng/public/_build/results?buildId=806301&view=ms.vss-test-web.build-test-results-tab&runId=25550926&resultId=105181&paneView=debug

This happened during the "Test: Windows Server 2016 x64" PR check for https://github.com/dotnet/aspnetcore/pull/25712

**Comment by halter73** [comment]
Possibly related: https://github.com/dotnet/aspnetcore-internal/issues/1974

**Comment by halter73** [comment]
Definitely related: https://github.com/dotnet/aspnetcore-internal/issues/1766

**Comment by pranavkm** [comment]
We should update these tests to use an ephemeral keyring (not the file based ones). This should avoid these sort of concurrency issues.
