### ISSUE TITLE
Investigate flaky "can stream from client to server with rxjs" test timeout in SignalR's HubConnectionTests.ts

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#25715]
```
        *** JASMINE SUITE FINISHED ***
  
    ● hubConnection › using json over ServerSentEvents transport › can stream from client to server with rxjs
  
      Timeout - Async callback was not invoked within the 40000ms timeout specified by jest.setTimeout.Error: 
  
        471 |             });
        472 | 
      > 473 |             it("can stream from client to server with rxjs", async (done) => {
            |             ^
        474 |                 const hubConnection = getConnectionBuilder(transportType, undefined, { httpClient })
        475 |                     .withHubProtocol(protocol)
        476 |                     .build();
  
        at new Spec (../common/node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
        at Suite.<anonymous> (ts/HubConnectionTests.ts:473:13)
  
  Test Suites: 1 failed, 3 passed, 4 total
  Tests:       1 failed, 135 passed, 136 total
  Snapshots:   0 total
  Time:        109.152s
  Ran all test suites.
```

https://dev.azure.com/dnceng/public/_build/results?buildId=805662&view=logs&jobId=4977e2d0-f668-5acb-fb34-578865fa48fa&j=4977e2d0-f668-5acb-fb34-578865fa48fa&t=16eb36ed-a441-537e-ddb3-2cbef63ce3d4

This happened during the "Test: macOS 10.14" PR check for #25639

@BrennanConroy @wtgodbe Should we delete or disable the test?

**Comment by BrennanConroy** [comment]
Logs are long gone, don't see an obvious reason this would fail. Closing.
