### ISSUE TITLE
RedirectToActionPermanentPreserveMethod/RedirectToActionPreserveMethod throws System.NullReferenceException

### ISSUE THREAD

**Issue by SpiritBob** [dotnet/aspnetcore#25761]
This happens when you invoke the method without supplying the optional parameter `routeValues` a reference to a non-null object.

If an argument is optional, it's expected that the method works with the argument's default assigned value (which in this case is `null`). This isn't the case with these two methods, i.e it's signature provides an invalid state of work, yielding

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.String.Concat(String str0, String str1)
   at Microsoft.AspNetCore.Mvc.Routing.EndpointRoutingUrlHelper.Action(UrlActionContext urlActionContext)
   at Microsoft.AspNetCore.Mvc.UrlHelperExtensions.Action(IUrlHelper helper, String action, String controller, Object values, String protocol, String host, String fragment)
   at Microsoft.AspNetCore.Mvc.Infrastructure.RedirectToActionResultExecutor.ExecuteAsync(ActionContext context, RedirectToActionResult result)
   at Microsoft.AspNetCore.Mvc.RedirectToActionResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|21_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatcher|8_0(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task`1 matcherTask)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Why is that? Is this intentional? 

Using latest ASP NET Core version (preview)

**Comment by SpiritBob** [comment]
I found out what's causing this, which is super bizarre.

Fully reproducible example:

Create the following endpoint:


```
[AllowAnonymous]
        [HttpGet]
        [Route("hello")]
        public async Task<IActionResult> Hello(Hello model)
        { //  <- Insert break-point here 
            var result = await someInjectedService.HelloAsync(model, HttpContext.Request);

            return RedirectToActionPermanentPreserveMethod("TestRedirect");
        }
```

Redirect endpoint (same controller):

```
        [AllowAnonymous]
        [HttpGet]
        [Route("hello_redirect")]
        public IActionResult TestRedirect(Hello model)
        {
            return Ok();
        }
```

HelloAsync method:

```
public async Task<Hello> HelloAsync(Hello model, HttpRequest httpRequest)
{
      return await Task.Run(async () => { await Task.Delay(1000); return new Hello(); });
 }
```

Run the project, hit the endpoint with route "hello". When break-point is hit, move thread down to the return statement. Exception is thrown.

If you don't move the thread with the help of the break-point, you shouldn't see the above exception.

**Comment by pranavkm** [comment]
@SpiritBob it looks like you have to modify the control flow to trigger this exception. I was unable to see this invoking these methods and letting it execute normally. Closing this since this is not something developers would be affected by in ordinary apps.

**Comment by SpiritBob** [comment]
@pranavkm Isn't an exception caused by changing control flow still a valid cause for fixing? What if someone had the exact same scenario, decides to skip 30 lines of code because they don't really need to go through all that, and gets thrown the exception I was having? Wouldn't that lead them down a false rabbit hole in search of something that innately is caused by the debugger they're using?
