### ISSUE TITLE
crit: Microsoft.AspNetCore.Server.Kestrel[0] Unable to start Kestrel

### ISSUE THREAD

**Issue by bilalmalik777** [dotnet/aspnetcore#25760]
I developed my asp.net core application in windows, and move to a container where it is working perfectly in my local environment with https. But now i want to run my application with https in Ubuntu 18.04, but i am getting error, i am providing our own certificate but it is not working. The error is given below. I am running applications via docker-compose. Docker-compose and other required files are also given below. Please help me to solve this issue
```
> WebPortal      | Unhandled Exception: Interop+Crypto+OpenSslCryptographicException: error:2006D080:BIO routines:BIO_new_file:no such file
WebPortal      |    at Interop.Crypto.CheckValidOpenSslHandle(SafeHandle handle)
WebPortal      |    at Internal.Cryptography.Pal.CertificatePal.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
WebPortal      |    at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
WebPortal      |    at TT.Core.Web.Program.<>c__DisplayClass1_0.<CreateWebHostBuilder>b__1(ListenOptions listenOptions) in /src/TT.Core.Web/Program.cs:line 56
WebPortal      |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.Listen(IPEndPoint endPoint, Action`1 configure)
WebPortal      |    at TT.Core.Web.Program.<>c.<CreateWebHostBuilder>b__1_0(KestrelServerOptions options) in /src/TT.Core.Web/Program.cs:line 68
WebPortal      |    at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
WebPortal      |    at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
WebPortal      |    at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
WebPortal      |    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
WebPortal      |    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
WebPortal      |    at System.Lazy`1.CreateValue()
WebPortal      |    at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
WebPortal      |    at Microsoft.Extensions.Options.OptionsManager`1.Get(String name)
WebPortal      |    at Microsoft.Extensions.Options.OptionsManager`1.get_Value()
WebPortal      |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.CreateServiceContext(IOptions`1 options, ILoggerFactory loggerFactory)
WebPortal      |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer..ctor(IOptions`1 options, ITransportFactory transportFactory, ILoggerFactory loggerFactory)
WebPortal      | --- End of stack trace from previous location where exception was thrown ---
WebPortal      |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
WebPortal      |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
WebPortal      |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
WebPortal      |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton(SingletonCallSite singletonCallSite, ServiceProviderEngineScope scope)
WebPortal      |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
WebPortal      |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
WebPortal      |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
WebPortal      |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
WebPortal      |    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
WebPortal      |    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
WebPortal      |    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
WebPortal      |    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureServer()
WebPortal      |    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
WebPortal      |    at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
WebPortal      |    at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
WebPortal      |    at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
WebPortal      |    at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
WebPortal      |    at TT.Core.Web.Program.Main(String[] args) in /src/TT.Core.Web/Program.cs:line 32
WebPortal exited with code 139


```
--------------------------------------
Docker-compose.yml
-------------------------------------
version: '3.4'

services:

  tt.core.web:

    image: thingtraxcontainerregistry.azurecr.io/ttcoreweb

    container_name: WebPortal

    environment:

      CORE_ENVIRONMENT: ${env}

      ASPNETCORE_ENVIRONMENT: ${env}

      IsDockerDeployment: ${isDockerDeployment}

    restart: always

    networks:

     - app-network

networks:

  app-network:

    ipam:

      driver: default

      config:

        - subnet: 172.24.0.0/16

---------------------------------
docker-compose.override.yml
--------------------------------
version: '3.4'

services:

  tt.core.web:

    environment:

      - ASPNETCORE_ENVIRONMENT=${env}

      - IsDockerDeployment=${isDockerDeployment}

      - ASPNETCORE_URLS=https://+:443;http://+:80

      - ASPNETCORE_HTTPS_PORT=443

      - KestrelPath=${appCertificate}

      - KestrelPassword=${appCertificatepassword}

      - ASPNETCORE_Kestrel__Certificates__Default__Password=doaminnamepassword

      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/_.domainname.com_private_key.pfx

    ports:

      - "80:80"

      - "443:443"

    volumes:

      - /home/thingtrax/Downloads/DockerComposelinux/DockerCompose/config:/root/.aspnet/https:ro

      - /home/thingtrax/Downloads/DockerComposelinux/DockerCompose/config:/root/.microsoft/usersecrets:ro

 -----------------------------
.env file
--------------------------------
env=devdocker
isDockerDeployment=true
appCertificate=/root/.aspnet/https/_.domainname.com_private_key.pfx
appCertificatepassword=doaminnamepassword.123!

```

**Comment by Tratcher** [comment]
It can't find the certificate?

How was the docker compose file generated?

@javiercn ?

**Comment by javiercn** [comment]
@bilalmalik777 thanks for contacting us.

As @Tratcher points out, the issue is that your app is failing to find the certificate. I think the issue is that you are missing a mapping or something like that.

I would recommend connecting to the running container with `docker exec -it /bin/bash and checking to make sure that the files are in the right place`. You might not have exported the certificate.

Also note that the locations you are using are the ones that our "tooling" uses and that if you are driving things from the command-line it might be simpler for you to simply export the cert to somewhere more convenient and pass in the file path and the password. There is no need for you to map the user secrets folder unless you are using it for something else.

**Comment by bilalmalik777** [comment]
thanks, @Tratcher and @javiercn, I really appreciate for your quick response
the certificate is getting loaded at the correct place as you can see in the attached image
i think there is something other problem, i have also posted the code snippet of program.cs where i am loaded certificate
```
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseApplicationInsights()
                 .UseKestrel(options =>
                 {
                     bool.TryParse(Environment.GetEnvironmentVariable("IsDockerDeployment"), out bool isDockerDeployment);
                     if (isDockerDeployment)
                     {
                         options.Listen(new IPEndPoint(IPAddress.Any, 443), listenOptions =>
                         {
                             var configuration = (IConfiguration)options.ApplicationServices.GetService(typeof(IConfiguration));
                             var certPassword = Environment.GetEnvironmentVariable("KestrelPassword");
                             var certPath = Environment.GetEnvironmentVariable("KestrelPath");

                             var certificate = new X509Certificate2(certPath, certPassword);
                             Console.WriteLine("Certificate provided");
                             var httpsConnectionAdapterOptions = new HttpsConnectionAdapterOptions()
                             {
                                 ClientCertificateMode = ClientCertificateMode.NoCertificate,
                                 SslProtocols = System.Security.Authentication.SslProtocols.Tls,
                                 ServerCertificate = certificate,
                             };

                             Console.WriteLine("Certificate validated");
                             listenOptions.UseHttps(httpsConnectionAdapterOptions);
                         });
                     }
                 })
                 .UseStartup<Startup>();
    }
```
i am using dotnet core 2.2

![image](https://user-images.githubusercontent.com/23011613/92732915-99287280-f366-11ea-8c4d-6f2a02a4a6b2.png)

**Comment by javiercn** [comment]
@bilalmalik777 thanks for the additional details.

I think your .env file looks wrong? I can't tell for sure, but you have `doaminnamepassword` above and `doaminnamepassword.123!` not sure if that matters.

I'm not a docker compose expert, but that feels like an issue.

You can try modifying your app to make sure that you can get the config keys and that the file exists when you run docker compose, just to discard a config issue.

It might also be good if you check the pfx password is correct

**Comment by bilalmalik777** [comment]
doaminnamepassword  & doaminnamepassword.123!, these are dummy name and nothing else. .env file is good because i have used the same file structure to deploy over windows and it worked but it is doing pain in the case of Linux. same certificate and password is used in case of windows server everything works aimlessly
i have also verified the password with OpenSSL it looks good. 
we are deploying over Ubuntu 18.04.5 LTS

**Comment by bilalmalik777** [comment]
@javiercn & @Tratcher  i am waiting for your response

**Comment by halter73** [comment]
Is the error still contain `no such file`? If so, can you output the `certPath` in your `.Listen(` callback and verify it's really `/root/.aspnet/https/_.<redacted>.com_private_key.pfx`?

If everything still looks right, could you then confirm that you can `File.Open(certPath, FileMode.Open)` it in the same place it's currently throwing (i.e. where you're currently calling `new X509Certificate2(certPath, certPassword);`? If that works, we could probably transfer this issue to dotnet/runtime since that would indicate that the X509Certificate2 ctor is giving an unhelpful error.

**Comment by Tratcher** [comment]
> i am using dotnet core 2.2

Note 2.2 is out of support, please move to 3.1.

**Comment by bilalmalik777** [comment]
@halter73, it is throwing no error at `File.Open(certPath, FileMode.Open)`.
@Tratcher  also i updated from 2.2 to 3.1 it is throwing the same error
one more point today i tried to deploy over the windows and counter the same error which was previously over ubuntu
even my local machine is windows 10 over which it is working perfecly

**Comment by bilalmalik777** [comment]
without https over http it is throwing the same error

**Comment by bilalmalik777** [comment]
@halter73 @Tratcher guys i am waiting for your response
I am stuck totally, half and a year ago whole solution was working perfectly in windows and linux
Please help me to sotrt out this problem

**Comment by halter73** [comment]
> `System.IO.IOException: Read-only file system`

It should probably be `File.Open(certPath, FileMode.Open, FileAccess.Read)` instead of `File.Open(certPath, FileMode.Open)` then.

**Comment by bilalmalik777** [comment]
@halter73 I have made changes as you recommended still getting the following error, also posted the code and logs of the container.

**ERROR**
`Unable to start Kestrel.
WebPortal      | Interop+Crypto+OpenSslCryptographicException: error:2006D080:BIO routines:BIO_new_file:no such file
WebPortal      |    at Interop.Crypto.CheckValidOpenSslHandle(SafeHandle handle)`

**code of CreateWebHostBuilder method**

``` public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseApplicationInsights()
                   .UseKestrel(options =>
                   {
                       bool.TryParse(Environment.GetEnvironmentVariable("IsDockerDeployment"), out bool isDockerDeployment);
                       if (isDockerDeployment)
                       {
                           options.Listen(new IPEndPoint(IPAddress.Any, 443), listenOptions =>
                           {
                               var configuration = (IConfiguration)options.ApplicationServices.GetService(typeof(IConfiguration));
                               var certPassword = Environment.GetEnvironmentVariable("KestrelPassword");
                               var certPath = Environment.GetEnvironmentVariable("KestrelPath");
                               Console.WriteLine(certPassword);
                               Console.WriteLine(certPath);

                               var certificate = new X509Certificate2(certPath, certPassword);
                               Console.WriteLine("Certificate provided");

                               Console.WriteLine("File Open started");
                               Console.WriteLine("File.Open(certPath, FileMode.Open, FileAccess.Read)");

                               File.Open(certPath, FileMode.Open, FileAccess.Read);

                               Console.WriteLine("File.Open(certPath, FileMode.Open, FileAccess.Read)");
                               Console.WriteLine("File Open completed");

                               var httpsConnectionAdapterOptions = new HttpsConnectionAdapterOptions()
                               {
                                   ClientCertificateMode = ClientCertificateMode.NoCertificate,
                                   SslProtocols = System.Security.Authentication.SslProtocols.Tls,
                                   ServerCertificate = certificate,
                               };
                               listenOptions.UseHttps(httpsConnectionAdapterOptions);
                           });
                       }
                   })
                 .UseStartup<Startup>();
```

**logs of container**
```thingtrax@thingtrax-NUCPK:~/Downloads/DockerCompose$ sudo docker-compose up
Creating network "dockercompose_app-network" with the default driver
Creating WebPortal ... done
Attaching to WebPortal
WebPortal      | Memeory Cache
WebPortal      | add logging
WebPortal      | isAnonymousUser
WebPortal      | ClientVersion
WebPortal      | Complete ConfigureServices
WebPortal      | password.123!
WebPortal      | /home/https/_.passworddomain.com_private_key.pfx
WebPortal      | Certificate provided
WebPortal      | File Open started
WebPortal      | File.Open(certPath, FileMode.Open, FileAccess.Read)
WebPortal      | File.Open(certPath, FileMode.Open, FileAccess.Read)
WebPortal      | File Open completed
WebPortal      | info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
WebPortal      |       User profile is available. Using '/root/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
WebPortal      | info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[58]
WebPortal      |       Creating key {edcf40ec-cc33-40cb-8a72-6f11f521fc63} with creation date 2020-09-15 07:26:28Z, activation date 2020-09-15 07:26:28Z, and expiration date 2020-12-14 07:26:28Z.
WebPortal      | warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
WebPortal      |       No XML encryptor configured. Key {edcf40ec-cc33-40cb-8a72-6f11f521fc63} may be persisted to storage in unencrypted form.
WebPortal      | info: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[39]
WebPortal      |       Writing data to file '/root/.aspnet/DataProtection-Keys/key-edcf40ec-cc33-40cb-8a72-6f11f521fc63.xml'.
WebPortal      | start configure
WebPortal      | exception
WebPortal      | serilog
WebPortal      | static
WebPortal      | session
WebPortal      | middle ware added
WebPortal      | 172.24.0.6:443
WebPortal      | Complete Configure
WebPortal      | crit: Microsoft.AspNetCore.Server.Kestrel[0]
WebPortal      |       Unable to start Kestrel.
WebPortal      | Interop+Crypto+OpenSslCryptographicException: error:2006D080:BIO routines:BIO_new_file:no such file
WebPortal      |    at Interop.Crypto.CheckValidOpenSslHandle(SafeHandle handle)
WebPortal      |    at Internal.Cryptography.Pal.CertificatePal.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
WebPortal      |    at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
WebPortal      |    at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password)
WebPortal      |    at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.LoadCertificate(CertificateConfig certInfo, String endpointName)
WebPortal      |    at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.LoadDefaultCert(ConfigurationReader configReader)
WebPortal      |    at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.Load()
WebPortal      |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.ValidateOptions()
WebPortal      |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
WebPortal      | 
WebPortal      | Unhandled Exception: Interop+Crypto+OpenSslCryptographicException: error:2006D080:BIO routines:BIO_new_file:no such file
WebPortal      |    at Interop.Crypto.CheckValidOpenSslHandle(SafeHandle handle)
WebPortal      |    at Internal.Cryptography.Pal.CertificatePal.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
WebPortal      |    at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
WebPortal      |    at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password)
WebPortal      |    at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.LoadCertificate(CertificateConfig certInfo, String endpointName)
WebPortal      |    at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.LoadDefaultCert(ConfigurationReader configReader)
WebPortal      |    at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.Load()
WebPortal      |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.ValidateOptions()
WebPortal      |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
WebPortal      |    at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
WebPortal      |    at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
WebPortal      |    at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
WebPortal      |    at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
WebPortal      |    at TT.Core.Web.Program.Main(String[] args) in /src/TT.Core.Web/Program.cs:line 34
```

**Comment by halter73** [comment]
```
Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.LoadDefaultCert(ConfigurationReader configReader)
```

This last stack trace is subtly different than the original. The exception is no longer being thrown from inside your KestrelServerOptions.Listen callback and is instead being throw when Kestrel is loading config.

Do you have a section like the following in your configuration defining a default certificate? And if so, does it specify the path to a valid certificate in your docker container? Even if the certificate is not actually used, Kestrel will try to load it.

```json
{
  "Kestrel": {
    "Certificates": {
      "Default": {
        "Path": "<path to .pfx file>",
        "Password": "<certificate password>"
      }
    }
  }
}
```

**Comment by bilalmalik777** [comment]
@halter73 are you talking about lauchsetting.json?

**Comment by halter73** [comment]
It's wherever your configuration is defined. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1

CreateDefaultBuilder will load config from appsettings.json and appsettings.{Environment}.json by default.

**Comment by bilalmalik777** [comment]
The problem has been resolved by following your last recommendation regarding app-settings
@Tratcher  @halter73 I am grateful for your support.
