### ISSUE TITLE
dotnet 5 blazor template update from preview 7 to previpreview 8 : ICU error with Blazor WASM

### ISSUE THREAD

**Issue by yostane** [dotnet/aspnetcore#25794]
### To Reproduce

- Install dotnet 5 preview 7
- - Create blazor wasm template `dotnet new blazorWasm -o HelloBlazor`
- Install dotnet 5.0.100-preview.8.20417.9
- Run the project: `cd HelloBlazor && dotnet run`
- Open https://localhost:5001/ using Chrome
- The page fails to load `ICU call ulocdata_getCLDRVersion failed with error #2 'U_MISSING_RESOURCE_ERROR'.`

```log
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
polyfill.js:128 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    at polyfill.js:128
blazor.webassembly.js:1 Debugging hotkey: Shift+Alt+D (when application has focus)
blazor.webassembly.js:1 blazor Loaded 9.43 MB resourcesThis application was built with linking (tree shaking) disabled. Published applications will be significantly smaller.
blazor.webassembly.js:1 Loaded 9.43 MB resources from cache
blazor.webassembly.js:1 ICU call ulocdata_getCLDRVersion failed with error #2 'U_MISSING_RESOURCE_ERROR'.
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 L: CLR: Managed code called FailFast, saying "Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support."
blazor.webassembly.js:1 undefined
blazor.webassembly.js:1 undefined
d.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
    at abort (https://localhost:5001/_framework/dotnet.5.0.0-preview.8.20407.11.js:1:14793)
    at _abort (https://localhost:5001/_framework/dotnet.5.0.0-preview.8.20407.11.js:1:103229)
    at ves_icall_System_Environment_FailFast (<anonymous>:wasm-function[6289]:0xf0b87)
    at ves_icall_System_Environment_FailFast_raw (<anonymous>:wasm-function[6288]:0xf0b1f)
    at do_icall (<anonymous>:wasm-function[11036]:0x1a3f77)
    at do_icall_wrapper (<anonymous>:wasm-function[3422]:0x7c61d)
    at interp_exec_method (<anonymous>:wasm-function[2198]:0x4661c)
    at interp_runtime_invoke (<anonymous>:wasm-function[8187]:0x13ac9b)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[7650]:0x123beb)
    at do_runtime_invoke (<anonymous>:wasm-function[3421]:0x7c566)
```

### Further technical details
- dotnet 5.0.100-preview.8.20417.9
- Include the output of `dotnet --info`

```log
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.8.20417.9
 Commit:    fc62663a35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\

Host (useful for support):
  Version: 5.0.0-preview.8.20407.11
  Commit:  bf456654f9

.NET SDKs installed:
  5.0.100-preview.7.20366.6 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.8.20417.9 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.7.20365.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.8.20414.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.7.20364.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.8.20407.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.7.20366.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.8.20411.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: VSCode and Visual Studio 2019 preview

**Comment by yostane** [comment]
Hello,

I have more details: the bug happens when I create a blazor project using dotnet 5 preview 7 and the run it after installing preview 8.

Best regards,

**Comment by pranavkm** [comment]
@yostane I just tried this in a vanilla blazor wasm app and I do not see this error. Looking at the stack trace, I suspect your app has been modified in some way:

> polyfill.js:128 Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    at polyfill.js:128

Do you also see the same issue in a project created from a template?

**Comment by yostane** [comment]
@pranavkm , I reproduce it when I create the project with preview 7 and then use preview 8 to build and run. Here is a csproj file that causes the problem.

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
    <UseBlazorWebAssembly>true</UseBlazorWebAssembly>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="5.0.0-preview.7.20365.19" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="5.0.0-preview.7.20365.19" PrivateAssets="all" />
    <PackageReference Include="System.Net.Http.Json" Version="5.0.0-preview.7.20364.11" />
  </ItemGroup>

</Project>
```

Updating the versions in the csproj to preview 8 fixes my problem.

Maybe we can close the ticket in that case ?

**Comment by mkArtakMSFT** [comment]
Thanks @yostane
