### ISSUE TITLE
Test failure: BlazorWasmStandaloneTemplate_Works

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#25826]
Failure: https://dev.azure.com/dnceng/public/_build/results?buildId=810710&view=results

Logs:
```
OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.NotEmptyException: Assert.NotEmpty() Failure\r\n   at Xunit.Assert.NotEmpty(IEnumerable collection) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 325\r\n   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<Exists>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 67\r\n   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver ) in //src/Shared/E2ETesting/WaitAssert.cs:line 106\r\nScreen shot captured at 'F:\workspace\_work\1\s\artifacts\TestResults\Release\BlazorTemplates.Tests\7e285b7762434abfa03aa78a1f7626ec.png'\r\nPage content:\r\n<head></head><body></body>\r\n\r\n---- Assert.NotEmpty() Failure
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 126
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.Exists(IWebDriver driver, By finder, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 64
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.Exists(IWebDriver driver, By finder) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 51
   at Templates.Test.BlazorWasmTemplateTest.TestBasicNavigation(String appName, Boolean usesAuth, Boolean skipFetchData) in /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorWasmTemplateTest.cs:line 525
   at Templates.Test.BlazorWasmTemplateTest.BlazorWasmStandaloneTemplate_Works() in /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorWasmTemplateTest.cs:line 73
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<Exists>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 67
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 106
```

@pranavkm and I investigated it a little locally and we were able to see the following screenshot of a failed run when trying to run the published template:
![image](https://user-images.githubusercontent.com/2030323/92973084-3b645b00-f438-11ea-9373-dfcee7aa1bf2.png)

It looks like there are problems with the generated cert: https://github.com/dotnet/aspnetcore/blob/8f6e83ada47cfa8fa3bde094ad336f4b5b650815/src/ProjectTemplates/BlazorTemplates.Tests/BlazorWasmTemplateTest.cs#L643

**Comment by pranavkm** [comment]
@HaoK were you already looking at this?

**Comment by HaoK** [comment]
Note: this also affects:
Templates.Test.BlazorWasmTemplateTest.BlazorWasmHostedPwaTemplate_Works
Templates.Test.BlazorWasmTemplateTest.BlazorWasmHostedTemplate_IndividualAuth_Works_WithLocalDB
Templates.Test.BlazorWasmTemplateTest.BlazorWasmHostedTemplate_IndividualAuth_Works_WithOutLocalDB

**Comment by HaoK** [comment]
Note all of these tests seem to pass/fail together where roughly 2/3 of the time they pass and then the 3rd time they will fail.  Every 3rd build... @javiercn can you think of any reasons why the dev cert code would fail in this pattern?

```
 var developmentCertificate = DevelopmentCertificate.Create(project.TemplateOutputDir); 
```

**Comment by HaoK** [comment]
Fixed by https://github.com/dotnet/aspnetcore/pull/27948
