### ISSUE TITLE
Blazor WebAssembly: Port 9300 already in use

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#25887]
Reported by @helios2052 https://github.com/dotnet/core/issues/5200#issuecomment-692321191

I noticed that in both my upgraded app and in the sample RC1 blazor-wasm hosted template (w/auth), it will startup and run ok the first time, but throws an exception on the next and subsequent startups w/debugging.

It seems like possibly this error only happens if you stop the app/browser by pressing "stop debugging" in visual studio and then re-launch. If you close the browser directly, visual studio then stops debugging as usual and you can restart the app with no issues. I have to go into task manager and clear out any stuck ".NET HOST" processes and then relaunch each time.

![error](https://user-images.githubusercontent.com/291534/93139318-84254980-f6ae-11ea-8f16-05227e4496dd.JPG)

<pre>
Unhandled exception. System.IO.IOException: Failed to bind to address http://127.0.0.1:9300: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Only one usage of each socket address (protocol/network address/port) is normally permitted.
 ---> System.Net.Sockets.SocketException (10048): Only one usage of each socket address (protocol/network address/port) is normally permitted.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.<Bind>g__BindSocket|13_0(<>c__DisplayClass13_0& )
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.<Bind>g__BindSocket|13_0(<>c__DisplayClass13_0& )
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass29_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at Microsoft.WebAssembly.Diagnostics.Program.Main(String[] args)

fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: No output has been recevied from the application.
         at Microsoft.AspNetCore.Builder.DebugProxyLauncher.LaunchAndGetUrl(IServiceProvider serviceProvider, String devToolsHost)
         at Microsoft.AspNetCore.Builder.WebAssemblyNetDebugProxyAppBuilderExtensions.<>c.<<UseWebAssemblyDebugging>b__0_1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
         at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
<pre/>

**Comment by Pilchie** [comment]
Pretty sure we recently fixed this?  @mkArtakMSFT or @lewing @captainsafia ?

**Comment by captainsafia** [comment]
Yep, we did. Unfortunately, it didn't make the cut-off for RC1 so we shipped it with RC2.

I've responded to the user [here](https://github.com/dotnet/core/issues/5200#issuecomment-692361736).

**Comment by helios2052** [comment]
Just to be more specific, I've been using preview 8 and hadn't encountered this issue (at least not exactly as it's happening here). Others on the blazor gitter have described this same issue today only once updating to rc1.

On preview 8, there was a similar issue where it was necessary to ensure or manually close the browser window before re-launching the app. Now it seems I need to do that and also kill the .net host service in task manager.

**Comment by mkArtakMSFT** [comment]
Closing this as this is now fixed in RC2.

**Comment by jckgore** [comment]
I got bit by this today after upgrading a project. How soon until RC2 is released?

**Comment by tossnet** [comment]
ok but this solution to clear out any process ".NET Host" only works once.  Then, if we modify our code, this process is no longer in the tasks manager and the error come back

**Comment by Postlagerkarte** [comment]
This works for me while waiting for the fix:

`npm install --global kill-port`

and add to your .csproj

```
<PropertyGroup>
    <DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
</PropertyGroup> 
<PropertyGroup>
    <PreBuildEvent>kill-port 9300</PreBuildEvent>
</PropertyGroup>

```
