### ISSUE TITLE
[Blazor] Null reference exception when running app with Chrome

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/aspnetcore#25916]
### Describe the bug
This is going to be a tough one. If I run my PWA app in the latest RC1 framework + VS 16.8.0 Preview 3.0 and have it launch Chrome (85.0.4183.102 64 bit) then I get a NullReferenceException in the Blazor framework.

If I get it to launch Firefox it works fine.
If I get a friend to run the app it works fine in all of his browsers.

Here is a video demonstrating the problem
https://www.youtube.com/watch?v=BpfGLVOFROk

### To Reproduce
Not sure if you can or if it is going to be specific to my laptop, but download https://github.com/mrpmorris/the-periodic-table-of-elements-game - set it to launch Chrome, and then press F5 in VS.

#### Exception box
```
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null. Arg_ParamName_Name
  Source=System.Text.RegularExpressions
  StackTrace:
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at System.Text.RegularExpressions.Regex.IsMatch(String input)
   at Microsoft.AspNetCore.Builder.DebugProxyLauncher.<>c__DisplayClass10_0.<CompleteTaskWhenServerIsReady>g__OnOutputDataReceived|0(Object sender, DataReceivedEventArgs eventArgs)
   at System.Diagnostics.Process.OutputReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__18_0(Object edi)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

  This exception was originally thrown at this call stack:
    [External Code]
```

#### Output window
```
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

System.InvalidOperationException: No output has been recevied from the application.
   at Microsoft.AspNetCore.Builder.DebugProxyLauncher.LaunchAndGetUrl(IServiceProvider serviceProvider, String devToolsHost)
   at Microsoft.AspNetCore.Builder.WebAssemblyNetDebugProxyAppBuilderExtensions.<>c.<<UseWebAssemblyDebugging>b__0_1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Further technical details
- ASP.NET version 5 RC1

**Comment by campersau** [comment]
See https://github.com/dotnet/aspnetcore/issues/25897
