### ISSUE TITLE
Flaky CancelsOutdatedRefreshes_Async + CanUploadAndConvertImageFile 

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#25929]
There was a test run which had 4 different Components tests fail: https://dev.azure.com/dnceng/public/_build/results?buildId=815782&view=ms.vss-test-web.build-test-results-tab&runId=25967884&resultId=100327&paneView=debug.

```
Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.ServerVirtualizationTest.CancelsOutdatedRefreshes_Async


OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.EqualException: Assert.Equal() Failure\r\nExpected: 1\r\nActual:   0\r\n   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer1 comparer) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\EqualityAsserts.cs:line 40\r\n at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 80\r\n at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_01.<WaitAssertCore>b__0(IWebDriver ) in //src/Shared/E2ETesting/WaitAssert.cs:line 106\r\nScreen shot captured at 'F:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.AspNetCore.Components.E2ETests\fee203da44124d94bdebe979fd05b725.png'\r\nPage content:\r\n<head>\r\n    <meta charset="utf-8">\r\n    <title>Basic test app</title>\r\n    <base href="/subdir/">\r\n    <link href="style.css" rel="stylesheet">\r\n    <link rel="icon" href="data:,">\r\n\r\n    \r\n    <link href="_content/TestContentPackage/styles.css" rel="stylesheet">\r\n    <link href="Components.TestServer.styles.css" rel="stylesheet">\r\n</head>\r\n<body>\r\n    <root><div id="test-selector">\r\n    Select test:\r\n    <select id="test-selector-select"><option value="none">Choose...\r\n        <option value="BasicTestApp.AfterRenderInteropComponent">After-render interop component\r\n        <option value="BasicTestApp.AuthTest.AuthRouter">Auth cases\r\n        <option value="BasicTestApp.BindCasesComponent">bind cases\r\n        <option value="BasicTestApp.ComponentRefComponent">Component ref component\r\n        <option value="BasicTestApp.ConfigurationComponent">Configuration\r\n        <option value="BasicTestApp.CounterComponentUsingChild">Counter using child component\r\n        <option value="BasicTestApp.CulturePicker">Culture Picker\r\n        <option value="BasicTestApp.DispatchingComponent">Dispatching to sync context\r\n        <option value="BasicTestApp.ElementFocusComponent">Element focus component\r\n        <option value="BasicTestApp.ErrorComponent">Error throwing

  at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 126
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore(IWebDriver driver, Action assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 80
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.Equal[T](IWebDriver driver, T expected, Func`1 actual) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 24
   at Microsoft.AspNetCore.Components.E2ETest.Tests.VirtualizationTest.CancelsOutdatedRefreshes_Async() in /_/src/Components/test/E2ETest/Tests/VirtualizationTest.cs:line 183
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 80
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 106
```

```
Microsoft.AspNetCore.Components.E2ETest.Tests.InputFileTest.CanUploadAndConvertImageFile

OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.NotEmptyException: Assert.NotEmpty() Failure\r\n   at Xunit.Assert.NotEmpty(IEnumerable collection) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 331\r\n   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<Exists>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 69\r\n   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver ) in //src/Shared/E2ETesting/WaitAssert.cs:line 106\r\nScreen shot captured at 'F:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.AspNetCore.Components.E2ETests\45125e71d7434d7ea9404236a45a3fbc.png'\r\nPage content:\r\n<head>\r\n    <meta charset="utf-8">\r\n    <title>Basic test app</title>\r\n    <base href="/subdir/">\r\n    <link href="style.css" rel="stylesheet">\r\n    <link rel="icon" href="data:,">\r\n\r\n    \r\n    <link href="_content/TestContentPackage/styles.css" rel="stylesheet">\r\n\r\n    \r\n    <link href="BasicTestApp.styles.css" rel="stylesheet">\r\n</head>\r\n\r\n<body>\r\n    <root><div id="test-selector">\r\n    Select test:\r\n    <select id="test-selector-select"><option value="none">Choose...\r\n        <option value="BasicTestApp.AfterRenderInteropComponent">After-render interop component\r\n        <option value="BasicTestApp.AuthTest.AuthRouter">Auth cases\r\n        <option value="BasicTestApp.BindCasesComponent">bind cases\r\n        <option value="BasicTestApp.ComponentRefComponent">Component ref component\r\n        <option value="BasicTestApp.ConfigurationComponent">Configuration\r\n        <option value="BasicTestApp.CounterComponentUsingChild">Counter using child component\r\n        <option value="BasicTestApp.CulturePicker">Culture Picker\r\n        <option value="BasicTestApp.DispatchingComponent">Dispatching to sync context\r\n        <option value="BasicTestApp.ElementFocusComponent">Element focus component\r\n        <option value="BasicTestApp.ErrorComponent">Error throwing\r\n        <option value="BasicTestApp.EventCallbackTest.EventCallbackCases">EventCallback\r\n        <option value="BasicTestApp.EventDisablingComponent">Event disabling

 at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 126
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.Exists(IWebDriver driver, By finder, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 64
   at Microsoft.AspNetCore.Components.E2ETest.BasicTestAppWebDriverExtensions.WaitUntilTestSelectorReady(IWebDriver browser) in /_/src/Components/test/E2ETest/Infrastructure/WebDriverExtensions/BasicTestAppWebDriverExtensions.cs:line 24
   at Microsoft.AspNetCore.Components.E2ETest.BasicTestAppWebDriverExtensions.MountTestComponent[TComponent](IWebDriver browser) in /_/src/Components/test/E2ETest/Infrastructure/WebDriverExtensions/BasicTestAppWebDriverExtensions.cs:line 18
   at Microsoft.AspNetCore.Components.E2ETest.Tests.InputFileTest.InitializeAsyncCore() in /_/src/Components/test/E2ETest/Tests/InputFileTest.cs:line 38
   at Microsoft.AspNetCore.E2ETesting.BrowserTestBase.InitializeAsync(String isolationContext) in /_/src/Shared/E2ETesting/BrowserTestBase.cs:line 71
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<Exists>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 69
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 106
```

```
PreventDefault_DotNotApplyByDefault

OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.NotEmptyException: Assert.NotEmpty() Failure\r\n   at Xunit.Assert.NotEmpty(IEnumerable collection) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 331\r\n   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<Exists>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 69\r\n   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver ) in //src/Shared/E2ETesting/WaitAssert.cs:line 106\r\nScreen shot captured at 'F:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.AspNetCore.Components.E2ETests\ff196531a999403eabe3e664fe246b25.png'\r\nPage content:\r\n<head>\r\n    <meta charset="utf-8">\r\n    <title>Basic test app</title>\r\n    <base href="/subdir/">\r\n    <link href="style.css" rel="stylesheet">\r\n    <link rel="icon" href="data:,">\r\n\r\n    \r\n    <link href="_content/TestContentPackage/styles.css" rel="stylesheet">\r\n\r\n    \r\n    <link href="BasicTestApp.styles.css" rel="stylesheet">\r\n</head>\r\n\r\n<body>\r\n    <root>Loading...</root>\r\n\r\n    \r\n    <div id="blazor-error-ui" style="display: none;">\r\n        An unhandled error has occurred.\r\n        <a href="" class="reload">Reload

\r\n        <a class="dismiss" style="cursor: pointer;">🗙\r\n    
\r\n\r\n    \r\n    <script src="js/jsinteroptests.js">\r\n    <script src="js/webComponentPerformingJsInterop.js">\r\n    <script src="_framework/blazor.webassembly.js">\r\n\r\n    \r\n    <script src="_content/TestContentPackage/prompt.js"><script src="_framework/dotnet.5.0.0-rc.1.20371.13.js" defer="" integrity="sha256-6Eg8a80upMLXjN4uGdB7+SEaKZXiizSASf7Blx8KCFQ=" crossorigin="anonymous">

Stack trace

   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 126
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.Exists(IWebDriver driver, By finder, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 64
   at Microsoft.AspNetCore.Components.E2ETest.BasicTestAppWebDriverExtensions.WaitUntilTestSelectorReady(IWebDriver browser) in /_/src/Components/test/E2ETest/Infrastructure/WebDriverExtensions/BasicTestAppWebDriverExtensions.cs:line 24
   at Microsoft.AspNetCore.Components.E2ETest.BasicTestAppWebDriverExtensions.MountTestComponent[TComponent](IWebDriver browser) in /_/src/Components/test/E2ETest/Infrastructure/WebDriverExtensions/BasicTestAppWebDriverExtensions.cs:line 18
   at Microsoft.AspNetCore.Components.E2ETest.Tests.EventTest.InitializeAsyncCore() in /_/src/Components/test/E2ETest/Tests/EventTest.cs:line 29
   at Microsoft.AspNetCore.E2ETesting.BrowserTestBase.InitializeAsync(String isolationContext) in /_/src/Shared/E2ETesting/BrowserTestBase.cs:line 71
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<Exists>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 69
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 106
```

```
Microsoft.AspNetCore.Components.E2ETest.Tests.WebAssemblyConfigurationTest.WebAssemblyConfiguration_Works

OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.NotEmptyException: Assert.NotEmpty() Failure\r\n   at Xunit.Assert.NotEmpty(IEnumerable collection) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 331\r\n   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<Exists>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 69\r\n   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver ) in //src/Shared/E2ETesting/WaitAssert.cs:line 106\r\nScreen shot captured at 'F:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.AspNetCore.Components.E2ETests\a279f57be24f45c38d700a2f2b7838d7.png'\r\nPage content:\r\n<head>\r\n    <meta charset="utf-8">\r\n    <title>Basic test app</title>\r\n    <base href="/subdir/">\r\n    <link href="style.css" rel="stylesheet">\r\n    <link rel="icon" href="data:,">\r\n\r\n    \r\n    <link href="_content/TestContentPackage/styles.css" rel="stylesheet">\r\n\r\n    \r\n    <link href="BasicTestApp.styles.css" rel="stylesheet">\r\n</head>\r\n\r\n<body>\r\n    <root><div id="test-selector">\r\n    Select test:\r\n    <select id="test-selector-select"><option value="none">Choose...\r\n        <option value="BasicTestApp.AfterRenderInteropComponent">After-render interop component\r\n        <option value="BasicTestApp.AuthTest.AuthRouter">Auth cases\r\n        <option value="BasicTestApp.BindCasesComponent">bind cases\r\n        <option value="BasicTestApp.ComponentRefComponent">Component ref component\r\n        <option value="BasicTestApp.ConfigurationComponent">Configuration\r\n        <option value="BasicTestApp.CounterComponentUsingChild">Counter using child component\r\n        <option value="BasicTestApp.CulturePicker">Culture Picker\r\n        <option value="BasicTestApp.DispatchingComponent">Dispatching to sync context\r\n        <option value="BasicTestApp.ElementFocusComponent">Element focus component\r\n        <option value="BasicTestApp.ErrorComponent">Error throwing\r\n        <option value="BasicTestApp.EventCallbackTest.EventCallbackCases">EventCallback\r\n        <option value="BasicTestApp.EventDisablingComponent">Event disabling


Stack trace
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 126
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.Exists(IWebDriver driver, By finder, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 64
   at Microsoft.AspNetCore.Components.E2ETest.BasicTestAppWebDriverExtensions.WaitUntilTestSelectorReady(IWebDriver browser) in /_/src/Components/test/E2ETest/Infrastructure/WebDriverExtensions/BasicTestAppWebDriverExtensions.cs:line 24
   at Microsoft.AspNetCore.Components.E2ETest.BasicTestAppWebDriverExtensions.MountTestComponent[TComponent](IWebDriver browser) in /_/src/Components/test/E2ETest/Infrastructure/WebDriverExtensions/BasicTestAppWebDriverExtensions.cs:line 18
   at Microsoft.AspNetCore.Components.E2ETest.Tests.WebAssemblyConfigurationTest.InitializeAsyncCore() in /_/src/Components/test/E2ETest/Tests/WebAssemblyConfigurationTest.cs:line 34
   at Microsoft.AspNetCore.E2ETesting.BrowserTestBase.InitializeAsync(String isolationContext) in /_/src/Shared/E2ETesting/BrowserTestBase.cs:line 71
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<Exists>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 69
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 106
```

**Comment by HaoK** [comment]
CancelsOutdatedRefreshes_Async and CanUploadAndConvertImageFile are still flaky

**Comment by SteveSandersonMS** [comment]
Hopefully addressed in https://github.com/dotnet/aspnetcore/pull/32870 and https://github.com/dotnet/aspnetcore/pull/32998
