### ISSUE TITLE
Flaky Test: Publish_Project

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#25931]
https://dev.azure.com/dnceng/public/_build/results?buildId=815998&view=ms.vss-test-web.build-test-results-tab&runId=25977388&resultId=100159&paneView=debug

```
System.TimeoutException : command '$/Users/runner/work/1/s/.dotnet/dotnet msbuild /nr:false /bl /p:RunningAsTest=true /p:MicrosoftNETCoreAppRuntimeVersion=6.0.0-alpha.1.20464.10 /p:MicrosoftNetCompilersToolsetPackageVersion=3.8.0-3.20458.6 /p:RazorSdkDirectoryRoot=/Users/runner/work/1/s/artifacts/bin/Microsoft.NET.Sdk.Razor/Release/sdk-output/ /p:RepoRoot=/Users/runner/work/1/s/ /p:_RazorBuildServerPipeName="e7466400-43f3-4267-bfcd-c428af5f4392" /t:Publish /p:Configuration=Release ' timed out after 00:08:00. Output: Microsoft (R) Build Engine version 16.8.0-preview-20379-02+8343d638e for .NET\nCopyright (C) Microsoft Corporation. All rights reserved.\n\n/Users/runner/work/1/s/.dotnet/sdk/5.0.100-rc.1.20379.10/MSBuild.dll -maxcpucount -verbosity:m /bl /nr:false /p:RunningAsTest=true /p:MicrosoftNETCoreAppRuntimeVersion=6.0.0-alpha.1.20464.10 /p:MicrosoftNetCompilersToolsetPackageVersion=3.8.0-3.20458.6 /p:RazorSdkDirectoryRoot=/Users/runner/work/1/s/artifacts/bin/Microsoft.NET.Sdk.Razor/Release/sdk-output/ /p:RepoRoot=/Users/runner/work/1/s/ /p:_RazorBuildServerPipeName=e7466400-43f3-4267-bfcd-c428af5f4392 /p:Configuration=Release /t:Publish ./SimpleMvc21.csproj\n  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview\n


Stack trace
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.<>c__DisplayClass2_0.<<RunProcessCoreAsync>g__GetTimeoutForProcess|3>d.MoveNext() in /_/src/Shared/MSBuild.Testing/MSBuildProcessManager.cs:line 221
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MSBuildProcessManager.RunProcessAsync(ProjectDirectory project, String arguments, Nullable`1 timeout, MSBuildProcessKind msBuildProcessKind) in /_/src/Shared/MSBuild.Testing/MSBuildProcessManager.cs:line 123
   at Microsoft.AspNetCore.Razor.Design.IntegrationTests.MvcBuildIntegrationTestLegacy.Publish_Project() in /_/src/Razor/Microsoft.NET.Sdk.Razor/integrationtests/MvcBuildIntegrationTestLegacy.cs:line 81
--- End of stack trace from previous location ---
```

**Comment by pranavkm** [comment]
These tests were re-enabled after observing they haven' been failing for > 1 month. The tests now use `dotnet test` hang features to detect hangs and capture crash dumps.
