### ISSUE TITLE
.NET5 RC1 Blazor WebAssembly App cannot be started (F5) from Visual Studio 2019 Version 16.8.0 Preview 3.0

### ISSUE THREAD

**Issue by majorimi** [dotnet/aspnetcore#25944]
I'm trying to migrate my Balzor projects to the recently released .NET5 RC1. Done all the migration steps however WebAssembly Hosted App model is not able to start (F5) from VS 2019. Previous version .NET5 Preview8 was working perfectly! 
**I have even created a new Blazor WebAssembly App in a new solution and it does not start as well.** Cannot be started using IIS Express nor running the App in Console hosed mode. I'm facing this issue on multiple computers even with newly created projects.

I'm getting these errors:
![image](https://user-images.githubusercontent.com/7632824/93306540-4d5f4880-f800-11ea-8770-cc2378e01a51.png)
![image](https://user-images.githubusercontent.com/7632824/93306991-d4142580-f800-11ea-9ef7-ff2dd1b36491.png)

**By running the App (console hosted) I got this in the console. As I undertood probably multiple processes want to use 1 websocket/port.**
```
Content root path: C:\Users\xsimreto\source\repos\BlazorApp2\BlazorApp2
Unhandled exception. System.IO.IOException: **Failed to bind to address http://127.0.0.1:9300: address already in use.**
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Only one usage of each socket address (protocol/network address/port) is normally permitted.
 ---> System.Net.Sockets.SocketException (10048): Only one usage of each socket address (protocol/network address/port) is normally permitted.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.<Bind>g__BindSocket|13_0(<>c__DisplayClass13_0& )
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.<Bind>g__BindSocket|13_0(<>c__DisplayClass13_0& )
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass29_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at Microsoft.WebAssembly.Diagnostics.Program.Main(String[] args)
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.TimeoutException: Failed to start the debug proxy within the timeout period of 10 seconds.
         at Microsoft.AspNetCore.Builder.DebugProxyLauncher.LaunchAndGetUrl(IServiceProvider serviceProvider, String devToolsHost)
         at Microsoft.AspNetCore.Builder.WebAssemblyNetDebugProxyAppBuilderExtensions.<>c.<<UseWebAssemblyDebugging>b__0_1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Checked the port is used by dotnet:
```
PS C:\Users\xsimreto> Get-Process -Id (Get-NetTCPConnection -LocalPort 9300).OwningProcess

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    396      47    73900      26484       1.38  27532   1 dotnet
```

And actually "**dotnet watch run**" is working with Blazor WebAssembly app. Also Blazor Server App can be started from VS 2019 as before.

**Comment by tossnet** [comment]
Same problem on a **new** projet and my old projet.

**Comment by campersau** [comment]
These might help: https://github.com/dotnet/aspnetcore/issues/25887, https://github.com/dotnet/aspnetcore/issues/25897

**Comment by majorimi** [comment]
Great so Preview versions were more reliable than Release Candidates... Sounds good. Hope they fix it soon...
For all who has the same issue you can run "**dotnet watch run**" command. It was working for me.
