### ISSUE TITLE
Blazor WebAssembly JSException: blazorExports._internal.invokeJSFromDotNet is not a function

### ISSUE THREAD

**Issue by Forestbrook** [dotnet/aspnetcore#26005]
After upgrading to .NET 5 RC1 my Blazor WebAssembly app does not load anymore.

After loading _framework/blazor.boot.json the following exception is shown:

Microsoft.JSInterop.JSException: blazorExports._internal.invokeJSFromDotNet is not a function
TypeError: blazorExports._internal.invokeJSFromDotNet is not a function
    at _mono_wasm_invoke_js_blazor (https://localhost:44305/_framework/dotnet.5.0.0-rc.1.20451.14.js:1:183003)
    at do_icall (<anonymous>:wasm-function[10583]:0x1944fd)
    at do_icall_wrapper (<anonymous>:wasm-function[3296]:0x79894)
    at interp_exec_method (<anonymous>:wasm-function[2147]:0x4442c)
    at interp_runtime_invoke (<anonymous>:wasm-function[7851]:0x12e8ab)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[7334]:0x118342)
    at do_runtime_invoke (<anonymous>:wasm-function[3295]:0x797dd)
    at mono_runtime_invoke_checked (<anonymous>:wasm-function[521]:0xfee2)
    at mono_runtime_try_invoke_array (<anonymous>:wasm-function[7101]:0x10dd31)
    at ves_icall_InternalInvoke (<anonymous>:wasm-function[6217]:0xecc38)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.Microsoft.JSInterop.IJSUnmarshalledRuntime.InvokeUnmarshalled[Object,Object,Object,String](String identifier, Object arg0, Object arg1, Object arg2)
   at Microsoft.AspNetCore.Components.WebAssembly.Services.WebAssemblyJSRuntimeInvoker.InvokeUnmarshalled[Object,Object,Object,String](String identifier, Object arg0, Object arg1, Object arg2)
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHostBuilder.InitializeNavigationManager(WebAssemblyJSRuntimeInvoker jsRuntimeInvoker)
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHostBuilder..ctor(WebAssemblyJSRuntimeInvoker jsRuntimeInvoker)
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHostBuilder.CreateDefault(String[] args)
   at TopRooster.Client.WebApp.Program.Main(String[] args) in C:\Work\Oploma\Repos\TopRoosterApp\TopRooster\Client\WebApp\Program.cs:line 30
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.EntrypointInvoker.InvokeEntrypoint(String assemblyName, String[] args)

**Comment by Forestbrook** [comment]
Could this be connected to this change: [Unify Blazor WebAssembly JS interop implementation](https://github.com/dotnet/aspnetcore/issues/24648)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
We think you're still using the old version of the blazor.webassembly.js or blazor.server.js files.
If you think that's not the case please share a fully functional minimal project so that we can investigate this further.

**Comment by Forestbrook** [comment]
You are right. The browser was caching the old version. Even the index.html in the browser turned out to be an old version!
Thanks!
