### ISSUE TITLE
Quarantined test: Http2_MethodsRequestWithoutData_Success

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#26060]
## Error message
```
System.AggregateException : One or more hosted services failed to stop. (The operation at //src/Shared/Http2cat/TaskTimeoutExtensions.cs:25 timed out after reaching the limit of 5000ms.)
---- System.TimeoutException : The operation at //src/Shared/Http2cat/TaskTimeoutExtensions.cs:25 timed out after reaching the limit of 5000ms.
```

## Stack trace
```
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.WaitForShutdownAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.InProcess.Http2Tests.Http2_MethodsRequestWithoutData_Success(String method) in /_/src/Servers/IIS/IIS/test/Common.FunctionalTests/Inprocess/Http2Tests.cs:line 58
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/Http2cat/TaskTimeoutExtensions.cs:line 54
   at Microsoft.AspNetCore.Http2Cat.Http2Utilities.ReceiveFrameAsync(UInt32 maxFrameSize) in /_/src/Shared/Http2cat/Http2Utilities.cs:line 887
   at Microsoft.AspNetCore.Http2Cat.Http2Utilities.ReceiveHeadersAsync(Int32 expectedStreamId, Boolean endStream, Action`1 verifyHeaders) in /_/src/Shared/Http2cat/Http2Utilities.cs:line 950
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.InProcess.Http2Tests.<>c__DisplayClass3_0.<<Http2_MethodsRequestWithoutData_Success>b__0>d.MoveNext() in /_/src/Servers/IIS/IIS/test/Common.FunctionalTests/Inprocess/Http2Tests.cs:line 75
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Http2Cat.Http2CatHostedService.RunAsync() in /_/src/Shared/Http2cat/Http2CatHostedService.cs:line 105
   at Microsoft.AspNetCore.Http2Cat.Http2CatHostedService.RunAsync() in /_/src/Shared/Http2cat/Http2CatHostedService.cs:line 119
   at Microsoft.AspNetCore.Http2Cat.Http2CatHostedService.RunAsync() in /_/src/Shared/Http2cat/Http2CatHostedService.cs:line 119
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
```

See https://dev.azure.com/dnceng/public/_build/results?buildId=820179&view=ms.vss-test-web.build-test-results-tab&runId=26101574&paneView=debug&resultId=123459

**Comment by Tratcher** [comment]
Build link? It's important to know what queue/OS version this was on.
