### ISSUE TITLE
Unable to use XmlWriter asynchronously

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/aspnetcore#26116]
### Problem

I'm using the asynchronous methods of XmlWriter but I'm still getting an exception that says synchronous operations are not allowed.

> System.InvalidOperationException: 'Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.'

### More Information

I'm trying to implement my own `IActionResult` class, and it needs to override `ExecuteResultAsync()` to write some XML to the result. `ExecuteResultAsync()` seems very picky about using only asynchronous code so I reworked my code to use the asynchronous methods of `XmlWriter`.

```cs
public async Task ExecuteResultAsync(ActionContext context)
{
    context.HttpContext.Response.ContentType = "application/rss+xml";

    using XmlWriter writer = XmlWriter.Create(context.HttpContext.Response.Body, new XmlWriterSettings { Encoding = Encoding.UTF8, Async = true, Indent = true });

    await writer.WriteStartElementAsync(null, RssElementNames.Rss, null);
    await writer.WriteAttributeStringAsync(null, RssElementNames.Version, null, "2.0");

    // Channel info
    await writer.WriteStartElementAsync(null, RssElementNames.Channel, null);
    await writer.WriteElementStringAsync(null, RssElementNames.Title, null, Title ?? string.Empty);

    // Etc...

    // Channel
    await writer.WriteEndElementAsync();

    // Rss
    await writer.WriteEndElementAsync();

    await writer.FlushAsync();
}
```

But this code *still* gets the exact same error at the very last line (`FlushAsync()` call).

*Note: I really don't understand why the `XmlWriter` asynchronous methods need to have different parameters than the synchronous versions. So I just set all those extra parameters to `null`.*

I know I can set `AllowSynchronousIO` to `true` and the errors go away. I'm trying to play nice with ASP.NET Core, and if that means writing less performant asynchronous code, then I'm willing to do that. But it appears that `XmlWriter` is still using synchronous code internally or something.

### Further technical details
- ASP.NET Core Razor Pages
- ASP.NET Core version 3.1
- VS2019 16.7.3

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.402\

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  3.1.401 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by Tratcher** [comment]
What's the full exception call stack?

**Comment by SoftCircuits** [comment]
> What's the full exception call stack?

```
   at Microsoft.AspNetCore.Server.IIS.Core.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.AspNetCore.Server.IIS.Core.WrappingStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.Xml.XmlUtf8RawTextWriter.FlushBuffer()
   at System.Xml.XmlUtf8RawTextWriter.Flush()
   at System.Xml.XmlWellFormedWriter.Close()
   at System.Xml.XmlWriter.Dispose(Boolean disposing)
   at System.Xml.XmlAsyncCheckWriter.Dispose(Boolean disposing)
   at System.Xml.XmlWriter.Dispose()
   at SoftCircuits.WebHelpers.Syndication.SyndicationResult.<ExecuteResultAsync>d__32.MoveNext() in D:\Users\jwood\source\repos\InsiderArticles\SoftCircuits.WebHelpers\Syndication\SyndicationResult.cs:line 157
```

**Comment by Tratcher** [comment]
Ah. In 5.0 XmlWriter added DisposeAsync. https://github.com/dotnet/runtime/blob/9c472545df220d7ae26329e1649f880c4ee127e8/src/libraries/System.Private.Xml/src/System/Xml/Core/XmlWriterAsync.cs#L601

Someone would have to dig into XmlWriter to see if there's a way to pre-flush the content to avoid the sync flush on dispose.
