### ISSUE TITLE
TlsHandshakeRejectsTlsLessThan12

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#26154]
Fails consistently on Debian.9.Arm64.Open Ubuntu.1804
```
System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.
---- Interop+OpenSsl+SslException : SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
-------- Interop+Crypto+OpenSslCryptographicException : error:141640B5:SSL routines:tls_construct_client_hello:no ciphers available
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.Http2.TlsTests.TlsHandshakeRejectsTlsLessThan12() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/TlsTests.cs:line 57
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.Http2.TlsTests.TlsHandshakeRejectsTlsLessThan12() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/TlsTests.cs:line 68
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
----- Inner Stack Trace -----
```

This test currently has the 3rd highest failure rate, please prioritize.

**Comment by Tratcher** [comment]
This is now the highest un-addressed flaky test with 112 failures out of 373 runs.
The same error is reported on:
- Ubuntu.1804
- Debian.9
- Fedora.28
- Debian.9 ARM

**Comment by Tratcher** [comment]
@wfurt Is this error a side-effect of your changes in https://github.com/dotnet/runtime/pull/40746?

The test is a client intentionally trying to connect with TLS 1.1.
https://github.com/dotnet/aspnetcore/blob/ed4069c2634ce787025f2781e99328a48dd92802/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/TlsTests.cs#L62

**Comment by wfurt** [comment]
Most likely. Documented as [breaking](https://github.com/dotnet/docs/issues/20842) change. TLS1.1/0 still should be possible either be modifying system defaults or using CipherSuitePolicy.

cc: @bartonjs
