### ISSUE TITLE
dotnet-watch test continues to fail on OSX with ITestOutHelper error

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#26197]
I made some changes to address this but it appears it wasn't sufficient.

```
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.InvalidOperationException: There is no currently active test.
   at Xunit.Sdk.TestOutputHelper.GuardInitialized() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\TestOutputHelper.cs:line 51
   at Xunit.Sdk.TestOutputHelper.QueueTestOutput(String output) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\TestOutputHelper.cs:line 66
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.AwaitableProcess.WriteTestOutput(String text) in /_/src/Tools/dotnet-watch/test/AwaitableProcess.cs:line 154
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.AwaitableProcess.OnData(Object sender, DataReceivedEventArgs args) in /_/src/Tools/dotnet-watch/test/AwaitableProcess.cs:line 143
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
--- End of stack trace from previous location ---
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__18_0(Object edi)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

Failing test: https://dev.azure.com/dnceng/public/_build/results?buildId=824404&view=ms.vss-test-web.build-test-results-tab&runId=26296438&resultId=122315&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by pranavkm** [comment]
Should be fixed by https://github.com/dotnet/aspnetcore/pull/26159/commits/23d0d8fa0b2058bf162065ad5255718fd5f50dcb
