### ISSUE TITLE
Backgroundservice throws System.Threading.ThreadStateException: Thread is running or terminated; it cannot restart. 

### ISSUE THREAD

**Issue by shahinjabbar** [dotnet/aspnetcore#26211]
I wrote backgroundservice in asp.net core which starts a new thread inside StartAsync

**Comment by mkArtakMSFT** [comment]
@Tratcher I'm not sure I've got the label right - where in general should the `workerservice` related issues go?

@shirhatti please have a look at this. Thanks!

**Comment by Tratcher** [comment]
@mkArtakMSFT Hosting, though this will likely be transferred to the runtime.

@shahinjabbar can you provide a complete code sample and the stack trace for the error.

**Comment by shahinjabbar** [comment]
System.Threading.ThreadStateException: Thread is running or terminated; it cannot restart.
   at System.Threading.Thread.StartupSetApartmentStateInternal()
   at System.Threading.Thread.Start()
   at MyTestService.BackgroundServices.TestService.ExecuteAsync(CancellationToken stoppingToken) in E:\git projects\integration\MyTestService\BackgroundServices\TestService.cs:line 137

**Comment by shahinjabbar** [comment]
`using IPSPaymentService.Domain.DAL;
using IPSPaymentService.Services;
using Microsoft.Extensions.Hosting;
using Serilog;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace MyTestService.BackgroundServices
{
    public class MyTestService : BackgroundService
    {
        private Thread HBThread;
        private SemaphoreSlim semaphoreSlim = new SemaphoreSlim(1, 1);
        public MyTestService()
        {
            HBThread = new Thread(RunHeartBeat);
        }

        private async void RunHB()
        {
            while (true)
            {
                try
                {
                    //some logic
                }
                catch (Exception ex)
                {
                    Log.Error(ex, "HB error.");
                }
                finally
                {
                    await Task.Delay(10000);
                }
            }
        }

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            if (await semaphoreSlim.WaitAsync(0))
            {
                Log.Information("****** START");
                while (!stoppingToken.IsCancellationRequested)
                {
                    try
                    {
						        //some logic
                                if (!HBThread.IsAlive)
                                {
                                    HBThread.Start();
                                }
                    }
                    catch (Exception ex)
                    {
                        Log.Error(ex, "START ERROR");   
                    }
                    finally
                    {
                        await Task.Delay(1000);
                    }
                }
                semaphoreSlim.Release();
            }
        }
    }
}
`

**Comment by shahinjabbar** [comment]
`
using Microsoft.Extensions.Hosting;
using Serilog;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace MyTestService.BackgroundServices
{
    public class MyTestService : BackgroundService
    {
        private Thread HBThread;
        private SemaphoreSlim semaphoreSlim = new SemaphoreSlim(1, 1);
        public MyTestService()
        {
            HBThread = new Thread(RunHeartBeat);
        }

        private async void RunHB()
        {
            while (true)
            {
                try
                {
                    //some logic
                }
                catch (Exception ex)
                {
                    Log.Error(ex, "HB error.");
                }
                finally
                {
                    await Task.Delay(10000);
                }
            }
        }

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            if (await semaphoreSlim.WaitAsync(0))
            {
                Log.Information("****** START");
                while (!stoppingToken.IsCancellationRequested)
                {
                    try
                    {
						        //some logic
                                if (!HBThread.IsAlive)
                                {
                                    HBThread.Start();
                                }
                    }
                    catch (Exception ex)
                    {
                        Log.Error(ex, "START ERROR");   
                    }
                    finally
                    {
                        await Task.Delay(1000);
                    }
                }
                semaphoreSlim.Release();
            }
        }
    }
}

`
