### ISSUE TITLE
connectionState.getNextInvocationId() NullPointerException

### ISSUE THREAD

**Issue by dsuresh-ap** [dotnet/aspnetcore#26235]
### Describe the bug
The app crashes if `minify` is enabled and we try to invoke after connecting. Related to https://github.com/dotnet/aspnetcore/issues/11995.

### To Reproduce

1. Connect using a build that has minify enabled. 
2. `start()` will complete and when we perform `invoke()`, the app will crash on `String id = connectionState.getNextInvocationId();`

### Fix

Adding the following to proguard rules prevents the crash. Not sure which class is getting stripped out. The library should provide the proguard rules needed or should state in the readme to add these proguard rules.

```
-keep class com.microsoft.signalr.** { *; }
-keep interface com.microsoft.signalr.** { *; }
```

### Exceptions (if any)
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.microsoft.signalr.u0$c.f()' on a null object reference
       at com.microsoft.signalr.HubConnection.invoke(HubConnection.java:631)
       at com.uipath.websockets.connection.core.SignalRCoreWebsocketConnection.subscribeToPermissionsAndLicense(SignalRCoreWebsocketConnection.java:96)
       at com.uipath.websockets.connection.core.SignalRCoreWebsocketConnection.access$getDataProvider$p(SignalRCoreWebsocketConnection.java:26)
       at com.uipath.websockets.connection.core.SignalRCoreWebsocketConnection$connect$$inlined$apply$lambda$1.run(SignalRCoreWebsocketConnection.java:58)
       at io.reactivex.internal.observers.CallbackCompletableObserver.onComplete(CallbackCompletableObserver.java:53)
       at io.reactivex.subjects.CompletableSubject.onComplete(CompletableSubject.java:139)
       at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onComplete(SingleFlatMapCompletable.java:102)
       at io.reactivex.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.next(CompletableConcatArray.java:85)
       at io.reactivex.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.onComplete(CompletableConcatArray.java:65)
       at io.reactivex.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.next(CompletableConcatArray.java:85)
       at io.reactivex.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.onComplete(CompletableConcatArray.java:65)
       at io.reactivex.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.next(CompletableConcatArray.java:85)
       at io.reactivex.internal.operators.completable.CompletableConcatArray$ConcatInnerObserver.onComplete(CompletableConcatArray.java:65)
       at io.reactivex.subjects.CompletableSubject.onComplete(CompletableSubject.java:139)
       at com.microsoft.signalr.HubConnection.stopConnection(HubConnection.java:522)
       at com.microsoft.signalr.HubConnection.lambda$start$6(HubConnection.java:366)
       at com.microsoft.signalr.-$$Lambda$HubConnection$plWe2n559m5117SGBt0gopoPs3g.invoke(-.java:2)
       at com.microsoft.signalr.WebSocketTransport.onClose(WebSocketTransport.java:94)
       at com.microsoft.signalr.WebSocketTransport.lambda$start$1(WebSocketTransport.java:54)
       at com.microsoft.signalr.-$$Lambda$WebSocketTransport$vlt_DXG3u2t5OJvAYlxBdjX-Br4.invoke(-.java:2)
       at com.microsoft.signalr.OkHttpWebSocketWrapper$SignalRWebSocketListener.onClosing(OkHttpWebSocketWrapper.java:91)
       at okhttp3.internal.ws.RealWebSocket.onReadClose(RealWebSocket.java:361)
       at okhttp3.internal.ws.WebSocketReader.readControlFrame(WebSocketReader.java:202)
       at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:103)
       at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273)
       at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:209)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```
### Further technical details
- Java 3.1.8
- Include the output of `dotnet --info` ?
- Android Studio 4.0.1

**Comment by dsuresh-ap** [comment]
This crash still happened in production even with the Proguard rules so not sure if its Proguard. I think its more related to:
https://github.com/dotnet/aspnetcore/issues/14025
and
https://github.com/dotnet/aspnetcore/issues/11995

**Comment by BrennanConroy** [comment]
Have you tried using the 5.0 preview/rc of the java package?

**Comment by dsuresh-ap** [comment]
@BrennanConroy I wasn't able to reproduce this crash and we did not want to push a preview/RC lib to production. Is there an expected timeline for 5.0?

**Comment by BrennanConroy** [comment]
https://devblogs.microsoft.com/dotnet/introducing-net-5/ November

**Comment by dsuresh-ap** [comment]
@BrennanConroy Will this 5.0 be backwards compatible without making any server side changes?

**Comment by BrennanConroy** [comment]
Yes

**Comment by BrennanConroy** [comment]
My understanding of the above conversation is that this isn't an issue in 5.0.
