### ISSUE TITLE
The global exception handler is rethrowing the BadHttpRequestException: Unexpected end of request content as unhandled exception

### ISSUE THREAD

**Issue by Jothinimal** [dotnet/aspnetcore#26276]
My ASP .NET Core WebAPI application is getting some unidentified requests resulting in the below error.

**Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.**

This error is getting logged only at the kestrel (stdout_logfile) and not in the application's error log. Seems like the global exception handler is rethrowing the exception as unhandled exception.

As the request keeps coming, the application becomes slow and gets crashed, ended up in restarting the supervisor to bring up the application.

### Error log:

```
^[[41m^[[30mfail^[[39m^[[22m^[[49m: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.DrainAsync(Stream stream, ArrayPool`1 bytePool, Nullable`1 limit, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

### Code
**Exception Filtering code:**

```
public void ConfigureServices(IServiceCollection services)
{
    ...
    ...

    services.AddControllers()
            .ConfigureApiBehaviorOptions(options =>
            {
                options.SuppressConsumesConstraintForFormFileParameters = true;
                options.SuppressInferBindingSourcesForParameters = true;
                options.SuppressModelStateInvalidFilter = true;
                options.SuppressMapClientErrors = true;
                options.ClientErrorMapping[StatusCodes.Status404NotFound].Link =
                    "https://httpstatuses.com/404";

                options.InvalidModelStateResponseFactory = context =>
                {
                    var result = new BadRequestObjectResult(context.ModelState);

                    // TODO: add `using System.Net.Mime;` to resolve MediaTypeNames
                    result.ContentTypes.Add(MediaTypeNames.Application.Json);
                    result.ContentTypes.Add(MediaTypeNames.Application.Xml);

                    return result;
                };
            });

        services.AddControllers(options =>
            options.Filters.Add(new HttpResponseExceptionFilter())
        );
        
    ...
    ...
}
```
**Exception handler code:**

```
public void OnActionExecuted(ActionExecutedContext context)
{
    if (context.Exception is HttpResponseException exception)
    {
        logger.Error(context.Exception);

        context.Result = new ObjectResult(exception.Value)
        {
            StatusCode = exception.Status,
        };

        context.ExceptionHandled = true;
    }

    else if (context.Exception is BadHttpRequestException badException)
    {
        logger.Error(context.Exception);

        context.Result = new ObjectResult(badException.Data.Values)
        {
            StatusCode = badException.StatusCode,
        };

        context.ExceptionHandled = true;
    }

    else if (context.Exception is Exception otherException)
    {
        logger.Error(context.Exception);

        context.Result = new ObjectResult(otherException.Data.Values)
        {
            StatusCode = otherException.HResult,
        };

        context.ExceptionHandled = true;
    }
}
```

### Issue
Why is error not caught at the below global handler, or why is the error getting rethrown as unhandled exception. What am I doing wrong here?

**Comment by pranavkm** [comment]
Exception filters are executed after resource and auth filters (https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-3.1#implementation). This would explain why it cannot handle this exception. Consider using the exception middleware instead. For 6.0, we're using https://github.com/dotnet/aspnetcore/issues/13333 to modify MVC to return 4xx HTTP response codes rather than present these as 500 errors.

**Comment by Jothinimal** [comment]
I tried using an exception middleware, but still the same issue persits. The middleware is as below

**At Startup.Configure**
```
public void Configure(IApplicationBuilder app, IWebHostEnvironment env, IEmailService _emailSender)
{
	hostEnv = env;
	emailSender = _emailSender;

	if (env.IsDevelopment())
	{
		//app.UseExceptionHandler("/error-local-development");
		app.UseDeveloperExceptionPage();
	}
	else
	{
		//app.UseExceptionHandler("/error");
		app.UseHsts();
	}

	app.ConfigureExceptionHandler();
	app.UseCors("EdsCorsPolicy");

	app.UseForwardedHeaders(new ForwardedHeadersOptions
	{
		ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
	});

	app.UseHttpsRedirection();
	app.UseStaticFiles();

	app.UseRouting();

	app.UseAuthentication();
	app.UseAuthorization();

	app.UseEndpoints(endpoints =>
	{
		endpoints.MapControllers();
	});

	//app.UseMvc();
}
```

**The middleware**
```
public static class ExceptionMiddlewareExtensions
{
	public static void ConfigureExceptionHandler(this IApplicationBuilder app)
	{
		app.UseExceptionHandler(appError =>
		{
			appError.Run(async context =>
			{
				context.Response.StatusCode = (int)HttpStatusCode.InternalServerError;
				context.Response.ContentType = "application/json";

				var contextFeature = context.Features.Get<IExceptionHandlerFeature>();

				if (contextFeature != null)
				{
					await context.Response.WriteAsync(new ErrorDetails(contextFeature.Error, context.Response.StatusCode)
					{
						StatusCode = context.Response.StatusCode,
						Message = "Internal Server Error."
					}.ToString());
				}
			});
		});
	}
}

public class ErrorDetails
{
	private Logger logger;

	public int StatusCode { get; set; } = 500;
	public string Message { get; set; }
	public string Type { get; set; }
	public string StackTrace { get; set; }

	public override string ToString()
	{
		return JsonConvert.SerializeObject(this);
	}

	public ErrorDetails(Exception ex, int StatusCode)
	{
		logger = NLogBuilder.ConfigureNLog("nlog.config").GetLogger(this.GetType().Name);

		this.StatusCode = StatusCode;
		Message = ex.Message;
		Type = ex.GetType().Name;
		StackTrace = ex.ToString();
		
		logger.Error(ex);
	}
}
```

**Comment by Jothinimal** [comment]
I tried using an exception middleware, but still the same issue persits. The middleware is as below

**At Startup.Configure**
```
public void Configure(IApplicationBuilder app, IWebHostEnvironment env, IEmailService _emailSender)
{
	hostEnv = env;
	emailSender = _emailSender;

	if (env.IsDevelopment())
	{
		//app.UseExceptionHandler("/error-local-development");
		app.UseDeveloperExceptionPage();
	}
	else
	{
		//app.UseExceptionHandler("/error");
		app.UseHsts();
	}

	app.ConfigureExceptionHandler();
	app.UseCors("MyPolicy");

	app.UseForwardedHeaders(new ForwardedHeadersOptions
	{
		ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
	});

	app.UseHttpsRedirection();
	app.UseStaticFiles();

	app.UseRouting();

	app.UseAuthentication();
	app.UseAuthorization();

	app.UseEndpoints(endpoints =>
	{
		endpoints.MapControllers();
	});

	//app.UseMvc();
}
```

**The middleware**
```
public static class ExceptionMiddlewareExtensions
{
	public static void ConfigureExceptionHandler(this IApplicationBuilder app)
	{
		app.UseExceptionHandler(appError =>
		{
			appError.Run(async context =>
			{
				context.Response.StatusCode = (int)HttpStatusCode.InternalServerError;
				context.Response.ContentType = "application/json";

				var contextFeature = context.Features.Get<IExceptionHandlerFeature>();

				if (contextFeature != null)
				{
					await context.Response.WriteAsync(new ErrorDetails(contextFeature.Error, context.Response.StatusCode)
					{
						StatusCode = context.Response.StatusCode,
						Message = "Internal Server Error."
					}.ToString());
				}
			});
		});
	}
}

public class ErrorDetails
{
	private Logger logger;

	public int StatusCode { get; set; } = 500;
	public string Message { get; set; }
	public string Type { get; set; }
	public string StackTrace { get; set; }

	public override string ToString()
	{
		return JsonConvert.SerializeObject(this);
	}

	public ErrorDetails(Exception ex, int StatusCode)
	{
		logger = NLogBuilder.ConfigureNLog("nlog.config").GetLogger(this.GetType().Name);

		this.StatusCode = StatusCode;
		Message = ex.Message;
		Type = ex.GetType().Name;
		StackTrace = ex.ToString();
		
		logger.Error(ex);
	}
}
```

**Comment by brunolins16** [comment]
@Jothinimal are you still getting the issue? I am trying to repro your scenario and the exception message is logged by the  `Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware` https://github.com/dotnet/aspnetcore/blob/a450cb69b5e4549f5515cdb057a68771f56cefd7/src/Middleware/Diagnostics/src/ExceptionHandler/ExceptionHandlerMiddleware.cs#L106 but it is handled by the custom Exception Middleware (same code provided by you).

Based on the `ExceptionHandlerMiddleware `code there are only two scenarios that could end up rethrowing the exceptions:

1 - The response was already started when the Exception is handled
2 - Your custom middleware is failing

In both scenarios you should see additional logs.

Can you share additional repro scenario information?
