### ISSUE TITLE
Correct `CanInvokeDotNetMethods` test

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#26288]
### Describe the bug
Test repeatedly timed out in #26188 e.g. https://dev.azure.com/dnceng/public/_build/results?buildId=829494&view=ms.vss-test-web.build-test-results-tab&runId=26446588&resultId=100237&paneView=debug Likely failed elsewhere too.

### To Reproduce
Rerun tests at a commit without quarantining.

### Exceptions (if any)
``` text
OpenQA.Selenium.WebDriverTimeoutException : Timed out after 10 seconds
---- OpenQA.Selenium.NoSuchElementException : no such element: Unable to locate element: {"method":"css selector","selector":"#done\-with\-interop"}
  (Session info: headless chrome=85.0.4183.121)

Stack trace
   at OpenQA.Selenium.Support.UI.DefaultWait`1.ThrowTimeoutException(String exceptionMessage, Exception lastException)
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)
   at Microsoft.AspNetCore.Components.E2ETest.Tests.InteropTest.CanInvokeDotNetMethods() in /_/src/Components/test/E2ETest/Tests/InteropTest.cs:line 138
----- Inner Stack Trace -----
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at OpenQA.Selenium.By.<>c__DisplayClass22_0.<Id>b__0(ISearchContext context)
   at OpenQA.Selenium.By.FindElement(ISearchContext context)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(By by)
   at Microsoft.AspNetCore.Components.E2ETest.Tests.InteropTest.<>c.<CanInvokeDotNetMethods>b__2_0(IWebDriver d) in /_/src/Components/test/E2ETest/Tests/InteropTest.cs:line 139
   at OpenQA.Selenium.Support.UI.DefaultWait`1.Until[TResult](Func`2 condition)
Showing filters 1 through 4
```

### Further technical details
Failed in CI validation with latest runtime bits

**Comment by pranavkm** [comment]
This should have been resolved as a result of the changes made in https://github.com/dotnet/aspnetcore/pull/26289. Leaving this in quarantine until we can verify the changes work as expected.

**Comment by dougbu** [comment]
Given our un-quarantining methods involve checking for fixes of related issues, probably better to mark this as Done and close it. Then the ops-on-call person should un-quarantine it in a while.
