### ISSUE TITLE
Flaky test "CanUploadSingleLargeFile"

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#26331]
```
OpenQA.Selenium.NoSuchElementException : no such element: Unable to locate element: {"method":"css selector","selector":"#file\-a1872fb4d95d45c8ba48ec172a01f8dd\.txt"}\n  (Session info: headless chrome=85.0.4183.121)
```

```
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
at OpenQA.Selenium.By.<>c__DisplayClass22_0.<Id>b__0(ISearchContext context)
at OpenQA.Selenium.By.FindElement(ISearchContext context)
at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(By by)
at Microsoft.AspNetCore.Components.E2ETest.Tests.InputFileTest.CanUploadSingleLargeFile() in /_/src/Components/test/E2ETest/Tests/InputFileTest.cs:line 79
```

https://dev.azure.com/dnceng/public/_build/results?buildId=830370&view=ms.vss-test-web.build-test-results-tab&runId=26468894&resultId=100017&paneView=debug

**Comment by pranavkm** [comment]
We made some improvements to tests durations as part of https://github.com/dotnet/aspnetcore/pull/26519. This should likely address the test and make it eligible to be unquarantined after 11/2.

**Comment by HaoK** [comment]
Reactivating as its still failing sporadically 3-14 3-17, removing it from the mega tracking list since this is a single test

**Comment by TanayParikh** [comment]
This should now be resolved via https://github.com/dotnet/aspnetcore/pull/33015.

**Comment by TanayParikh** [comment]
We had 1 failure in 323 runs in the past month in quarantine. Thus, this test isn't eligible to be unquarantined yet. 

![image](https://user-images.githubusercontent.com/14852843/124824534-56eca500-df27-11eb-991f-1d000b2c04f0.png)


Error: 
```
OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.NotEmptyException: Assert.NotEmpty() Failure\r\n   at Xunit.Assert.NotEmpty(IEnumerable collection) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\CollectionAsserts.cs:line 331\r\n   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<Exists>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 72\r\n   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 109\r\nScreen shot captured at 'D:\\workspace\\_work\\1\\s\\artifacts\\TestResults\\Release\\Microsoft.AspNetCore.Components.E2ETests\\3a887a71ecd9436a993acc1504bbca45.png'\r\nPage content:\r\n<head></head><body></body>\r\n\r\n---- Assert.NotEmpty() Failure
```

Stack Trace:
```
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 129
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.Exists(IWebDriver driver, By finder, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 67
   at Microsoft.AspNetCore.Components.E2ETest.BasicTestAppWebDriverExtensions.WaitUntilTestSelectorReady(IWebDriver browser) in /_/src/Components/test/E2ETest/Infrastructure/WebDriverExtensions/BasicTestAppWebDriverExtensions.cs:line 24
   at Microsoft.AspNetCore.Components.E2ETest.BasicTestAppWebDriverExtensions.MountTestComponent[TComponent](IWebDriver browser) in /_/src/Components/test/E2ETest/Infrastructure/WebDriverExtensions/BasicTestAppWebDriverExtensions.cs:line 15
   at Microsoft.AspNetCore.Components.E2ETest.Tests.InputFileTest.InitializeAsyncCore() in /_/src/Components/test/E2ETest/Tests/InputFileTest.cs:line 41
   at Microsoft.AspNetCore.E2ETesting.BrowserTestBase.InitializeAsync(String isolationContext) in /_/src/Shared/E2ETesting/BrowserTestBase.cs:line 71
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<Exists>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 72
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 109

```
