### ISSUE TITLE
.Net Core3.1 The client has disconnected

### ISSUE THREAD

**Issue by 630383257** [dotnet/aspnetcore#26356]
After the program has been running for 5 or 6 days, this exception occurs during Put and Delete requests, which lasts for more than a day and then recovers on its own. I saw err_connection_reset in the browser developer tool and found that it is not the browser side that caused this problem, because I used the PostMan tool to call the interface without any response and saw the 504 status code in the fiddler, this situation occurs after two deployments, I have no idea about this, and I am looking for help.
```


      The client has disconnected

Microsoft.AspNetCore.Connections.ConnectionResetException: The client has disconnected

 ---> System.Runtime.InteropServices.COMException (0x80070040): 指定的网络名不再可用。 (0x80070040)

   --- End of inner exception stack trace ---

   at Microsoft.AspNetCore.Server.IIS.Core.IO.AsyncIOOperation.GetResult(Int16 token)

   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadBody()

   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()

   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)

   at System.IO.Pipelines.Pipe.GetReadAsyncResult()

   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)

   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadAsync(Memory`1 memory, CancellationToken cancellationToken)

   at Microsoft.AspNetCore.Server.IIS.Core.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)

   at System.IO.Pipelines.StreamPipeReader.ReadAsync(CancellationToken cancellationToken)

   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ReadFormAsync(CancellationToken cancellationToken)

   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)

   at Microsoft.AspNetCore.Mvc.ModelBinding.FormValueProviderFactory.AddValueProviderAsync(ValueProviderFactoryContext context)

   at Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider.CreateAsync(ActionContext actionContext, IList`1 factories)

   at Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider.TryCreateAsync(ActionContext actionContext, IList`1 factories)

   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

**Comment by BrennanConroy** [comment]
Can you grab ANCM logs? https://docs.microsoft.com/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-3.1#aspnet-core-module-debug-log-iis
And event logs https://docs.microsoft.com/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-3.1#application-event-log-iis

**Comment by 630383257** [comment]
Checked event logs, no useful information, then added ANCM logs configuration, do I have to wait until next time the problem recurs to look for ANCM logs?

**Comment by BrennanConroy** [comment]
> do I have to wait until next time the problem recurs to look for ANCM logs?

Yes
