### ISSUE TITLE
[Bug] FieldIdentifier only supports simple member accessors (fields, properties) of an object.

### ISSUE THREAD

**Issue by sion-corn** [dotnet/aspnetcore#26538]
I am trying to bind [BlazoredTypeahead](https://github.com/Blazored/Typeahead) to a list item, but I am getting the following error:

```
Error: System.ArgumentException: The provided expression contains a InstanceMethodCallExpression1 which is not supported. FieldIdentifier only supports simple member accessors (fields, properties) of an object.
   at Microsoft.AspNetCore.Components.Forms.FieldIdentifier.ParseAccessor[T](Expression`1 accessor, Object& model, String& fieldName)
   at Microsoft.AspNetCore.Components.Forms.FieldIdentifier.Create[TField](Expression`1 accessor)
   at Blazored.Typeahead.BlazoredTypeahead`2.OnInitialized()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

My code:

```
<div id="divItems">
    @for (int i = 0; i < Model.Items.Count; i++)
    {
        var iCopy = i; //see https://stackoverflow.com/a/56426146/323447
        <div class="row g-3 mb-2">
            <div class="col-12" style="display:flex;">
                <div class="input-group mr-2">
                    <BlazoredTypeahead SearchMethod="@SearchItemName"
                                       @bind-Value="@Model.Items[iCopy]"
                                       Placeholder="Start typing to check if item already exists..."
                                       class="form-control text-truncate"
                                       Debounce="500">
                        <SelectedTemplate Context="item">
                            @item.Name
                        </SelectedTemplate>
                        <ResultTemplate Context="item">
                            @item.Name
                        </ResultTemplate>
                    </BlazoredTypeahead>
                </div>
                <button type="button" class="btn btn-outline-danger" @onclick="(() => RemoveItem(iCopy))"><span class="material-icons">clear</span></button>
            </div>
        </div>
    }
    <div class="row g-3">
        <div class="col-12">
            <button type="button" class="btn btn-outline-success" title="Add another" @onclick="AddItem" disabled="@addItemButtonDisabled"><span class="material-icons">playlist_add</span></button>
        </div>
    </div>
</div>
```
It seems [this is an aspnetcore framework limitation instead of a component limitation](https://github.com/Blazored/Typeahead/issues/170). Is there a way to bind to a list item instead of an object?

**Comment by nikonthethird** [comment]
Is there a specific reason you are using a `for` loop instead of something like:

```
@foreach (var (item, index) in Model.Items.Select((x, i) => (x, i)) {
    <div @key="index" ...>
        <BlazoredTypeahead @bind-Value="item" ...>...</BlazoredTypeahead>
    </div>
}
```

This way you can still get the index and can refer to the item by variable, which is supported by the `FieldIdentifier`.

**Comment by pranavkm** [comment]
Closing per the previous response.
