### ISSUE TITLE
Java MessagePack protocol fails on Android 9 or earlier

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#26552]
https://github.com/dotnet/aspnetcore/blob/336e05577cd8bec2000ffcada926189199e4cef0/src/SignalR/clients/java/signalr/messagepack/src/main/java/com/microsoft/signalr/messagepack/MessagePackHubProtocol.java#L130

>java.lang.NoSuchMethodError: No virtual method position(I)Ljava/nio/ByteBuffer; in class Ljava/nio/ByteBuffer; or its super classes (declaration of 'java.nio.ByteBuffer' appears in /system/framework/core-oj.jar)
    at com.microsoft.signalr.messagepack.MessagePackHubProtocol.parseMessages(MessagePackHubProtocol.java:130)
    at com.microsoft.signalr.HubConnection.lambda$new$0$HubConnection(HubConnection.java:211)
    at com.microsoft.signalr.-$$Lambda$HubConnection$Y2FeeXVZ0Dop-l_VQCQzjKuw-gU.invoke(Unknown Source:4)
    at com.microsoft.signalr.WebSocketTransport.onReceive(WebSocketTransport.java:75)
    at com.microsoft.signalr.WebSocketTransport.lambda$start$0$WebSocketTransport(WebSocketTransport.java:52)
    at com.microsoft.signalr.-$$Lambda$WebSocketTransport$Lf4Ni2E6owp2KCdVH9tQSssSKcU.invoke(Unknown Source:2)
    at com.microsoft.signalr.OkHttpWebSocketWrapper$SignalRWebSocketListener.onMessage(OkHttpWebSocketWrapper.java:95)
    at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.kt:338)
    at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.kt:247)
    at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:106)
    at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
    at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
    at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:764)

`ByteBuffer.position()` isn't supported on Android 9 or earlier, we should find an alternative. Here's a similar issue in the msgpack library that we use: https://github.com/msgpack/msgpack-java/issues/516

Thanks @aaronoe for reporting this

**Comment by wtgodbe** [comment]
Resolved by https://github.com/dotnet/aspnetcore/pull/26614
