### ISSUE TITLE
Could not find 'VirtualizedComponent' in 'window'.

### ISSUE THREAD

**Issue by ngpns** [dotnet/aspnetcore#26585]
Hi there,
I'm trying to implement Blazor virtualization component on my project (ASP.NET Core 3.1 webassembly). But I faced the following bug.
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
Unhandled exception rendering component: Could not find 'VirtualizedComponent' in 'window'.
Error: Could not find 'VirtualizedComponent' in 'window'.
at https://localhost:4001/_framework/blazor.webassembly.js:1:9130
at Array.forEach ()
at p (https://localhost:4001/_framework/blazor.webassembly.js:1:9090)
at https://localhost:4001/_framework/blazor.webassembly.js:1:9800
at new Promise ()
at Object.beginInvokeJSFromDotNet (https://localhost:4001/_framework/blazor.webassembly.js:1:9773)
at _mono_wasm_invoke_js_marshalled (https://localhost:4001/_framework/wasm/dotnet.3.2.0.js:1:171294)
at do_icall (:wasm-function[6049]:0x10f8b1)
at do_icall_wrapper (:wasm-function[1896]:0x50b6a)
at interp_exec_method (:wasm-function[1120]:0x2588e)
Microsoft.JSInterop.JSException: Could not find 'VirtualizedComponent' in 'window'.
Error: Could not find 'VirtualizedComponent' in 'window'.
at https://localhost:4001/_framework/blazor.webassembly.js:1:9130
at Array.forEach ()
at p (https://localhost:4001/_framework/blazor.webassembly.js:1:9090)
at https://localhost:4001/_framework/blazor.webassembly.js:1:9800
at new Promise ()
at Object.beginInvokeJSFromDotNet (https://localhost:4001/_framework/blazor.webassembly.js:1:9773)
at _mono_wasm_invoke_js_marshalled (https://localhost:4001/_framework/wasm/dotnet.3.2.0.js:1:171294)
at do_icall (:wasm-function[6049]:0x10f8b1)
at do_icall_wrapper (:wasm-function[1896]:0x50b6a)
at interp_exec_method (:wasm-function[1120]:0x2588e)
at System.Threading.Tasks.ValueTask1[TResult].get_Result () <0x31826e0 + 0x00034> in <filename unknown>:0 at Ng.eCommerce.AdminPanel.Pages.Tapan1[TItem].OnAfterRenderAsync (System.Boolean firstRender) [0x00071] in C:\Users\tpn\source\repos\NG.eCommerce\ng.ecommerce.adminpanel\Pages\Tapan.cs:77
at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask (System.Threading.Tasks.Task taskToHandle) <0x2e588c8 + 0x000b6> in :0

//Component code link : 
[https://docs.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-3.1](url)

**Comment by javiercn** [comment]
@ngpns thanks for contacting us.

I don't believe the virtualization component will work in 3.1. It's a new 5.0 feature

**Comment by AnteUp** [comment]
I hit the same problem but the documentation implied that it was available in 3.1 (but not 3.0)
https://docs.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-3.1
