### ISSUE TITLE
UseRequestLocalization middleware throws System.InvalidOperationException on runtime for DbContext

### ISSUE THREAD

**Issue by gmarokov** [dotnet/aspnetcore#26596]
### Description
Hello folks. I've been investigating this for a few days now and came to an dead end. Any help on further investigation would be more than welcome. 
I have a ASP.NET Core WebApi project targeting .NET Core 2.1  developing on Fedora 32/Ubuntu 20.04. Deploying the app to Ubuntu server 20.04 and that's where the issue lies. Once I add 
```
app.UseRequestLocalization()
```
every request involving Identity objects (UserManager, SignInManager) results in 
```
System.InvalidOperationException: Cannot create a DbSet for 'ApplicationUser' because this type is not included in the model for the context.
```
I cannot reproduce this on my dev machines. The issue is only on the Ubuntu 20.04 server which is hosting the app behind Nginx proxy. What I have tried so far:
1. Checked more than once my ApplicationUser and DefaultDbContext models. 
2. Copied the build dlls from the server and ran them locally without an issue. 
3. Ran the app without proxy.
4. Made sure that I have the same runtimes locally and on the server. 

### To Reproduce
1. Registering Localization services:
```
 services.AddLocalization(options => options.ResourcesPath = "Resources");
      services.Configure<RequestLocalizationOptions>(options =>
      {
           var supportedCultures = new[]
           {
                new CultureInfo("en"),
                new CultureInfo("bg")
           };

           options.DefaultRequestCulture = new RequestCulture(culture: "en", uiCulture: "en");
           options.SupportedCultures = supportedCultures;
           options.SupportedUICultures = supportedCultures;
     });
```
2. Registering my request pipeline:
```
 app
      .UseAuthentication()
      .UseRequestLocalization(app.ApplicationServices.GetRequiredService<IOptions<RequestLocalizationOptions>>().Value)
      .UseMvc()
      .UseDefaultFiles()
      .UseStaticFiles()
      .UseHangfire();
```
_The only way that pipeline works is when I put RequestLocalization after Mvc in the pipeline_

3. I also add DataAnnatations localization:
```
 services.AddMvc()
       .AddDataAnnotationsLocalization(o =>
       {
             o.DataAnnotationLocalizerProvider = (type, factory) =>
             {
                  return factory.Create(typeof(Resources));
             };
       });
``` 
4. In addition I have shared resource file as class suggested by the docs:
```
namespace api
{
    /// <summary>
    /// Empty class representing reusable resources files for localization
    /// </summary>
    public class Resources
    {
        
    }
}
```

### Exceptions
```
System.InvalidOperationException: Cannot create a DbSet for 'ApplicationUser' because this type is not included in the model for the context.
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, LambdaExpression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync[TSource](IQueryable`1 source, Expression`1 predicate, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.FindByEmailAsync(String normalizedEmail, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByEmailAsync(String email)
   at api.Services.Implementations.UserService.FindByEmailAsync(String email) in /home/georgi/Projects/autohub-web/api/Services/Implementations/UserService.cs:line 69
   at api.Controllers.Public.AuthController.Login(LoginUserRequest model) in /home/georgi/Projects/autohub-web/api/Controllers/Public/AuthController.cs:line 34
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at api.SpaFallbackMiddleware.Invoke(HttpContext context) in /home/georgi/Projects/autohub-web/api/Middleware/SpaFallbackMiddleware.cs:line 56
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### Further technical details
- ASP.NET Core version: 2.1.2
- Local Fedora 32 env
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.810
 Commit:    d23842afc1

Runtime Environment:
 OS Name:     fedora
 OS Version:  32
 OS Platform: Linux
 RID:         fedora.32-x64
 Base Path:   /home/georgi/dotnet/sdk/2.1.810/

Host (useful for support):
  Version: 2.1.22
  Commit:  23677d3ee7

.NET Core SDKs installed:
  2.1.810 [/home/georgi/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.22 [/home/georgi/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.22 [/home/georgi/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.22 [/home/georgi/dotnet/shared/Microsoft.NETCore.App]

```

- Local Ubuntu 20.04 env
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.402/

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  2.1.810 [/usr/share/dotnet/sdk]
  3.1.402 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.22 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.22 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.22 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

- Server Ubuntu 20.04 env
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.810
 Commit:    d23842afc1

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.810/

Host (useful for support):
  Version: 2.1.22
  Commit:  23677d3ee7

.NET Core SDKs installed:
  2.1.810 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.22 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.22 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.22 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by davidfowl** [comment]
@gmarokov just FYI this isn’t a bug in the localization middleware. Your code is here:

at api.Services.Implementations.UserService.FindByEmailAsync(String email) in /home/georgi/Projects/autohub-web/api/Services/Implementations/UserService.cs:line 69
   at api.Controllers.Public.AuthController.Login(LoginUserRequest model)

The exception is a above that. The stack looks this way because the middleware is nested.

**Comment by gmarokov** [comment]
@davidfowl yes indeed. My code just wraps UserManager.FindByEmailAsync like this:
```
public async Task<ApplicationUser> FindByEmailAsync(string email) =>
            await this._userManager.FindByEmailAsync(email);```
Should `UseRequestLocalization` middleware be before `UseAuthentication` in that case?

**Comment by davidfowl** [comment]
I don't think that matters for this error I just wanted you to know that the localization middleware isn't in the picture with respect to this error.

**Comment by gmarokov** [comment]
That's interesting because if I turnoff localization middleware everything works like a charm..

**Comment by davidfowl** [comment]
I don't see how from that error. Can you provide a runnable sample? 

Also, your call to UseRequestLocalization doesn't need any arguments, the options will be resolved from the DI container automatically

**Comment by gmarokov** [comment]
Thanks for the info. Made a little progress by not creating `RequestLocalizationOptions` which works but once I add a supported language again the error prompts. I'm really struggling to create a runnable sample. Just don't understand how running same build on same runtime on almost identical operating systems produces different output.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by gmarokov** [comment]
Thanks for your feedback guys. Honestly I cannot reproduce this so I will close it. I will resolve it by rolling my own UseLocalization middleware.
