### ISSUE TITLE
Quarantined test: RegisterIPEndPoint_DynamicPort_Success

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#26626]
Failure in: https://dev.azure.com/dnceng/public/_build/results?buildId=842139&view=ms.vss-test-web.build-test-results-tab&runId=26819778&resultId=110048&paneView=debug

```
System.IO.InvalidDataException : No StatusCode found in ''

at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStatus(String response) in /_/src/Testing/src/HttpClientSlim.cs:line 144
   at Microsoft.AspNetCore.Testing.HttpClientSlim.ReadResponse(Stream stream) in /_/src/Testing/src/HttpClientSlim.cs:line 99
   at Microsoft.AspNetCore.Testing.HttpClientSlim.<>c__DisplayClass1_0.<<GetStringAsync>b__0>d.MoveNext() in /_/src/Testing/src/HttpClientSlim.cs:line 42
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Testing.HttpClientSlim.RetryRequest(Func`1 retryBlock) in /_/src/Testing/src/HttpClientSlim.cs:line 121
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(Uri requestUri, Boolean validateCertificate) in /_/src/Testing/src/HttpClientSlim.cs:line 31
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(String requestUri, Boolean validateCertificate) in /_/src/Testing/src/HttpClientSlim.cs:line 26
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterIPEndPoint_Success(IPEndPoint endPoint, String testUrl, Int32 testPort) in /_/src/Servers/Kestrel/test/BindTests/AddressRegistrationTests.cs:line 338
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterIPEndPoint_DynamicPort_Success(IPEndPoint endPoint, String testUrl) in /_/src/Servers/Kestrel/test/BindTests/AddressRegistrationTests.cs:line 108
--- End of stack trace from previous location ---
```

**Comment by Tratcher** [comment]
Queue: OSX.1014.Amd64.Open
Project: Libuv.BindTests--net5.0

**Comment by BrennanConroy** [comment]
There are now 3 issues with this error:
`No StatusCode found in ''`

https://github.com/dotnet/aspnetcore/issues/21118
https://github.com/dotnet/aspnetcore/issues/25403

**Comment by Tratcher** [comment]
This test uses complex MemberData so we don't even know which variant failed.



> There are now 3 issues with this error:
> `No StatusCode found in ''`

It just means the client wasn't able to get a response from the server. We need to see the full test logs to figure out why.

**Comment by pranavkm** [comment]
> This test uses complex MemberData so we don't even know which variant failed.

One of my favorite reasons to avoid MemberData (especially if the scenarios are different from each other).

**Comment by BrennanConroy** [comment]
Fixed it for you

**Comment by BrennanConroy** [comment]
Server logs has no requests

```
[0.001s] [TestLifetime] [Information] Starting test RegisterIPEndPoint_DynamicPort_Success-[_]_0-http_127.0.0.1 at 2020-10-05T22:16:02
[0.002s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting starting
[0.003s] [Microsoft.Hosting.Lifetime] [Information] Now listening on: http://[::]:63264
[0.004s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Debug] Loaded hosting startup assembly Libuv.BindTests
[0.004s] [Microsoft.Hosting.Lifetime] [Information] Application started. Press Ctrl+C to shut down.
[0.004s] [Microsoft.Hosting.Lifetime] [Information] Hosting environment: Production
[0.004s] [Microsoft.Hosting.Lifetime] [Information] Content root path: /private/tmp/helix/working/A7430954/w/ADBD091F/e/
[0.004s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting started
[0.311s] [TestLifetime] [Information] Finished test RegisterIPEndPoint_DynamicPort_Success-[_]_0-http_127.0.0.1 in 0.3094977s
```

**Comment by dougbu** [comment]
This test has been running at 💯% for at least the past 30 days as far as I can see. But, it's difficult to tell if _all_ quarantined variants are fine and whether any work has been done since the last failures. Recommendations @BrennanConroy @pranavkm @Tratcher❔

**Comment by BrennanConroy** [comment]
No work has been done to fix it, so let's leave it quarantined.
