### ISSUE TITLE
Blazor WebAssembly: Value cannot be null. (Parameter 'input')

### ISSUE THREAD

**Issue by aybe** [dotnet/aspnetcore#26783]
### Describe the bug

The project can be debugged only once, after you always get `Value cannot be null. (Parameter 'input')`.

Narrowed down the problem,

This is the faulty process preventing debugging, previous one never closes, a second one starts and then the exception:

> dotnet.exe

> "dotnet" exec "C:\Users\Aybe\.nuget\packages\microsoft.aspnetcore.components.webassembly.devserver\5.0.0-rc.1.20451.17\tools\BlazorDebugProxy\BrowserDebugHost.dll" --owner-pid 20816 --DevToolsUrl http://localhost:52067

So as a quick-fix, add this as post-build event:

> taskkill /im dotnet.exe /f

But now you have a problem, you must rebuild every time...

Add a text file to `wwwroot` and set to Copy Always, it'll always rebuild when you go <kbd>F5</kbd>.

Until there's a proper fix, this allows to debug as usual!

### Exceptions

```
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null. (Parameter 'input')
  Source=System.Text.RegularExpressions
  StackTrace:
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at System.Text.RegularExpressions.Regex.IsMatch(String input)
   at Microsoft.AspNetCore.Builder.DebugProxyLauncher.<>c__DisplayClass10_0.<CompleteTaskWhenServerIsReady>g__OnOutputDataReceived|0(Object sender, DataReceivedEventArgs eventArgs)
   at System.Diagnostics.Process.OutputReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__18_0(Object edi)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

  This exception was originally thrown at this call stack:
    [External Code]
```
### Further technical details

VS 16.8.0 Preview 3.2

```
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.1.20452.10
 Commit:    473d1b592e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\

Host (useful for support):
  Version: 5.0.0-rc.1.20451.14
  Commit:  38017c3935

.NET SDKs installed:
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. I believe we've fixed this for RC2 release.
@captainsafia is this the issue which fixed this: https://github.com/dotnet/aspnetcore/issues/25991

**Comment by aybe** [comment]
Alright, thanks!
