### ISSUE TITLE
IIS ClientDisconnectStress throws NullReferenceException on Windows 7

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#26839]
Microsoft.AspNetCore.Server.IIS.FunctionalTests.RequestResponseTests.ClientDisconnectStress consistently fails after throwing a NullReferenceException on the the Windows.7.Amd64.Open Helix queue. 

```
System.NullReferenceException : Object reference not set to an instance of an object.

Stack trace
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.IISTestSiteFixture.get_Client() in /_/src/Servers/IIS/IIS/test/Common.FunctionalTests/Infrastructure/IISTestSiteFixture.cs:line 51
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.IISTestSiteFixture.CreateTestConnection() in /_/src/Servers/IIS/IIS/test/Common.FunctionalTests/Infrastructure/IISTestSiteFixture.cs:line 63
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.RequestResponseTests.<>c__DisplayClass49_0.<<ClientDisconnectStress>g__RunRequests|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.RequestResponseTests.ClientDisconnectStress() in /_/src/Servers/IIS/IIS/test/Common.FunctionalTests/RequestResponseTests.cs:line 701
--- End of stack trace from previous location ---
```

https://dev.azure.com/dnceng/public/_build/results?buildId=846785&view=ms.vss-test-web.build-test-results-tab&runId=26968776&resultId=123967&paneView=debug

**Comment by adityamandaleeka** [comment]
Yea, sounds good.
