### ISSUE TITLE
SemanticRange Debug.Assert failure when typing in the LSP editor

### ISSUE THREAD

**Issue by ajaybhargavb** [dotnet/aspnetcore#26833]
I don't have a consistent repro but it happened when I was typing something like below,
```razor
<InputSelect @bind-value="">
  @foreach|
</InputSelect>
```

![image](https://user-images.githubusercontent.com/1579269/95799192-c4291d80-0ca8-11eb-9951-c0f54bd24f59.png)

Note, this doesn't happen when the debugger is attached. Discussed with @ryanbrandenburg and his theory is that it might have something to do with synchronization.

**Comment by ryanbrandenburg** [comment]
Specifically I think that the C# and Razor LSP's may not be referring to the same document version when combining their results.

**Comment by ajaybhargavb** [comment]
Consistent minimal-ish repro:

1. Create a new .razor file with the following content,
```razor
<div @onclick="() =>{}" @key="new object()">
    @if (true)
    {
        <div></div>
    }
</div>
<div>
    @if (true)
    {<p></p>
    }
</div>

<InputSelect @bind-Value="Prop">
    @foreach (var item in SomeList)
    {
        <Counter></Counter>
    }
</InputSelect>

@code{
    public string Prop { get; set; }

    public string[] SomeList { get; set; }
}
```
2. Close and re-open VS and open the file you created
3. Paste(Don't type) the following content on line 7
```razor
<div>
    @if (true)
    {<p></p>
    }
</div>
```
4. You should see a debug assert failure now. Click ignore 20 or so times
5. Now the document will look like this (Notice the odd coloring in the `@code` block),
![image](https://user-images.githubusercontent.com/1579269/96798944-dac12a00-13b6-11eb-93f3-f40834d07705.png)

**Comment by TanayParikh** [comment]
> Click ignore 20 or so times

😆

**Comment by TanayParikh** [comment]
![image](https://user-images.githubusercontent.com/14852843/97054592-ea1cb080-1539-11eb-9ba9-48bb8a52a0c8.png)

Add `SomeOtherComponent.razor`
```
@namespace OtherNamespace
```

Return to `Counter.razor` and paste in:
```
@page "/counter"
<h1>Counter</h1>

<p>Current count: @currentCount @@ @ip</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

<SomeOtherComponent></SomeOtherComponent>
<DiagnosticsComponent>
@code {
    private int currentCount = 0;
    private string ip = string.Empty;

    private async void IncrementCount()
    {
        currentCount++;
        ip = await GetIP();

        Debugger.Launch();
    }
}

<NewComponent>

```

Restart VS. Invoke code action `@using OtherNamespace`, on `<SomeOtherComponent>` on line 10.

**Comment by ryanbrandenburg** [comment]
@TanayParikh I yellow-bar when trying that and it seems to stop the CodeAction from executing:
```
StreamJsonRpc.RemoteInvocationException: Internal Error - System.InvalidCastException: Unable to cast object of type 'Microsoft.AspNetCore.Razor.LanguageServer.CodeActions.CodeActionResolutionEndpoint' to type 'MediatR.IRequestHandler`2[Microsoft.AspNetCore.Razor.LanguageServer.CodeActions.Models.RazorCodeAction,OmniSharp.Extensions.LanguageServer.Protocol.Models.CodeAction]'.
   at OmniSharp.Extensions.JsonRpc.JsonRpcServerServiceCollectionExtensions.RequestHandlerDecorator`2.Handle(T request, CancellationToken cancellationToken)
   at MediatR.Internal.RequestHandlerWrapperImpl`2.<>c__DisplayClass1_0.<Handle>g__Handler\|0()
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.<Handle>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.<Handle>d__3.MoveNext() --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.<Handle>d__2.MoveNext() --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.<Handle>d__2.MoveNext() --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.<Handle>d__2.MoveNext() --- End of stack trace from previous location where exception was thrown ---
    at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.<Handle>d__2.MoveNext() --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.<Handle>d__2.MoveNext() --- End of stack trace from previous location where exception was thrown ---
    at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.<Handle>d__2.MoveNext() --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<<RouteRequest>g__InnerRoute\|5_0>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OmniSharp.Extensions.JsonRpc.InputHandler.<>c__DisplayClass38_0.<<RouteRequest>b__5>d.MoveNext()
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__137`1.MoveNext() --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServer.Client.JsonRpcExtensionMethods.<SendMethodRequestAsync>d__1`2.MoveNext() --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.ThreadingTools.<WithCancellationSlow>d__8`1.MoveNext() --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServer.Client.SynchronizationManager.<QueueRequestTaskAsync>d__6`1.MoveNext() --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServer.Client.CodeActionCommandWrapper.<ResolveCodeActionAsync>d__31.MoveNext() --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServer.Client.CodeActionCommandWrapper.<>c__DisplayClass29_0.<<Invoke>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.LanguageServer.Client.CodeActionCommandWrapper.Invoke(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbSession.<>c__DisplayClass46_1.<InvokeAction>b__3()
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call, Predicate`1 exceptionFilter) --- End of stack trace from previous location where exception was thrown ---
    at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
--
```

**Comment by TanayParikh** [comment]
> @TanayParikh I yellow-bar when trying that and it seems to stop the CodeAction from executing:

Ah yeah that makes sense. https://github.com/dotnet/aspnetcore-tooling/pull/2669 would address that yellow bar.

**Comment by TanayParikh** [comment]
This should be repro-able now.

Note, leads to this colorization:
![image](https://user-images.githubusercontent.com/14852843/98030741-531be800-1dc6-11eb-974f-83409329561f.png)

**Comment by TanayParikh** [comment]
🎉 👏

**Comment by ryanbrandenburg** [comment]
![imgpsh_mobile_save](https://user-images.githubusercontent.com/14987221/100151429-fc9a4a80-2e55-11eb-82f4-ba2897760274.jpg)

@TanayParikh reports that this is not yet completely fixed.

**Comment by ryanbrandenburg** [comment]
Neither of the above scenarios reproduce the issue for me.

**Comment by NTaylorMullen** [comment]
Is this worth closing out then?
