### ISSUE TITLE
Enable "IsWindowsOnlyTest"s on the Windows.10.Arm64.Open Helix queue

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#26872]
https://github.com/dotnet/aspnetcore/pull/26840 (re)disabled "IsWindowsOnlyTest"s on the Windows.10.Arm64.Open Helix queue because a bunch of work items failed without explicit test failures. At least some of these work item failures were caused by an error in TestMatrix.cs during theory discovery.

```
[xUnit.net 00:00:01.16] IIS.NewShim.FunctionalTests: Exception thrown during theory discovery on 'Microsoft.AspNetCore.Server.IIS.FunctionalTests.StartupTests.HelloWorld'; falling back to single test case.
System.ArgumentException: Arm64
   at Microsoft.AspNetCore.Server.IntegrationTesting.TestMatrix.ResolveDefaultArchitecture() in /_/src/Hosting/Server.IntegrationTesting/src/TestMatrix.cs:line 134
   at Microsoft.AspNetCore.Server.IntegrationTesting.TestMatrix.Build() in /_/src/Hosting/Server.IntegrationTesting/src/TestMatrix.cs:line 101
   at Microsoft.AspNetCore.Server.IntegrationTesting.TestMatrix.GetEnumerator()+MoveNext() in /_/src/Hosting/Server.IntegrationTesting/src/TestMatrix.cs:line 327
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
```

We should properly enable these skipped tests on the Windows.10.Arm64.Open Helix queue. We could do this incrementally by removing the `$(IsWindowsOnlyTest)' != 'true'` check https://github.com/dotnet/aspnetcore/pull/26840/files#diff-fecf6f98b5c2a5cc5c66f045a93d30421b7fedcbdd4cacefc2605cd61a9b89afR46 and then putting `<SkipHelixArm>true</SkipHelixArm>` in the still-failing test projects.

**Comment by Tratcher** [comment]
This initial error is just because of a missing case in a switch:
https://github.com/dotnet/aspnetcore/blob/fab9e877f1ff8452bae2a5611c21f371b29f7768/src/Hosting/Server.IntegrationTesting/src/TestMatrix.cs#L127-L134

No telling what we'll hit after fixing this though.
