### ISSUE TITLE
OpenIdConnectAuthenticationHandler: message.State is null or empty

### ISSUE THREAD

**Issue by xamadev** [dotnet/aspnetcore#26932]
### Describe the bug

I 'm trying to migrate an ASP.NET Core 2.2 application to ASP.NET Core 3.1. I use OpenIDConnect authentication there and it worked fine with version 2.2. I get the follwing exception with version 3.1:

```
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: OpenIdConnectAuthenticationHandler: message.State is null or empty.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### To Reproduce

Here's my configuration:

```
public void ConfigureServices(IServiceCollection services)
{

    services.Configure<CookiePolicyOptions>(options =>
    {
        // This lambda determines whether user consent for non-essential cookies is needed for a given request.
        options.CheckConsentNeeded = context => true;
        options.MinimumSameSitePolicy = SameSiteMode.None;
    });

    services.AddAuthentication(options =>
        {
            options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
        })
        .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme, options =>
        {
            options.AccessDeniedPath = "/Authorization/AccessDenied";
        })
        .AddOpenIdConnect(OpenIdConnectDefaults.AuthenticationScheme, options =>
        {
            options.Authority = "https://xxxxxxxxx:443";

            options.ClientId = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
            options.ClientSecret = "xxxxxxxxxxxxxxxxxxxx";

            options.ResponseType = "code";
            options.SaveTokens = true;
            options.RequireHttpsMetadata = false;
            options.CallbackPath = new PathString("/Login");
            options.SignedOutRedirectUri = "https://xxxxxxxxxxxxxxxx";
        });

    services.AddRazorPages();
}
```

### Further technical details
- ASP.NET Core 3.1
- Microsoft.AspNetCore.Authentication.OpenIdConnect 3.1.9

**Comment by blowdart** [comment]
What browser or browsers is this happening in? Are there any errors in the browser console?

Presumably the metadata endpoint on the authority exists, if nothing else changed in configuration when updating to 3.1?

**Comment by xamadev** [comment]
Thanks @blowdart and @Tratcher, the CallbackPath was the problem. "/Login" is pointing to a content page, so leaving the CallbackPath at its default value solved the issue. Don't know why it worked before with that configuration in ASP.NET Core 2.2.
