### ISSUE TITLE
Make IViewComponentHelper easier to use

### ISSUE THREAD

**Issue by snebjorn** [dotnet/aspnetcore#27078]
### Is your feature request related to a problem? Please describe.
I want to render a ViewCompoent as an HTML string. The Razor template engine is pretty powerful and awesome! So I want to leverage that power to generate a HTML string instead of doing

```cs
// no formatting, no syntax highlighting
var html = @"<table>
<tr><td>
THIS SUCKS!
               </td>
        </tr>
   </table>
";
```

Using `return ViewComponent(...)` inside a controller is pretty simple. However if you want to move the logic to a service things get weird.

### Describe the solution you'd like
[IViewComponentHelper](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.iviewcomponenthelper?view=aspnetcore-3.1) already exists and appears to solve the problem
> Supports the rendering of view components in a view.

But it's not as simple as calling `InvokeAsync<TComponent>()`. **So that's my feature request 😸**

Okay a bit more context.
I managed to get it working (see [Current solution](#current-solution))

Issues:
1. I had to create a fake ViewContext see `GetFakeViewContext`. I see why providing a ViewContext can make sense. But why doesn't `DefaultViewComponentHelper` come with a context ready to go?
2. This call is just bizarre `(_viewComponentHelper as IViewContextAware).Contextualize(viewContext);`
I don't even remember in what dark corner of the internet I found out I had to do that.
3. I had to create a `NullView` because the `NullView` included in ASP.NET Core was made `internal` :/
4. My solution isn't thread-safe 😢, but I'm probably doing something wrong. See [exception](#threading-exception)

So a thread-safe `IViewComponentHelper` where we can just call `InvokeAsync<TComponent>()` would be really neat. 
Thank you

#### Current solution

```cs
public class RenderViewComponentService
{
    private readonly IServiceProvider _serviceProvider;
    private readonly ITempDataProvider _tempDataProvider;
    private readonly IViewComponentHelper _viewComponentHelper;

    public RenderViewComponentService(
        IServiceProvider serviceProvider,
        ITempDataProvider tempDataProvider,
        IViewComponentHelper viewComponentHelper
    )
    {
        _serviceProvider = serviceProvider;
        _tempDataProvider = tempDataProvider;
        _viewComponentHelper = viewComponentHelper;
    }

    public async Task<string> RenderViewComponentAsStringAsync<TViewComponent>(object args)
        where TViewComponent : ViewComponent
    {
        var viewContext = GetFakeViewContext();
        (_viewComponentHelper as IViewContextAware).Contextualize(viewContext);

        // this appears to call InvokeAsync in TViewComponent, but it'll also call Invoke (synchronously) if it's implemented
        // see https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-components?view=aspnetcore-3.1#perform-synchronous-work
        var htmlContent = await _viewComponentHelper.InvokeAsync<TViewComponent>(args);
        using var stringWriter = new StringWriter();
        htmlContent.WriteTo(stringWriter, HtmlEncoder.Default);
        var html = stringWriter.ToString();

        return html;
    }

    private ViewContext GetFakeViewContext(ActionContext actionContext = null, TextWriter writer = null)
    {
        actionContext ??= GetFakeActionContext();
        var viewData = new ViewDataDictionary(new EmptyModelMetadataProvider(), new ModelStateDictionary());
        var tempData = new TempDataDictionary(actionContext.HttpContext, _tempDataProvider);

        var viewContext = new ViewContext(
            actionContext,
            NullView.Instance,
            viewData,
            tempData,
            writer ?? TextWriter.Null,
            new HtmlHelperOptions());

        return viewContext;
    }

    private ActionContext GetFakeActionContext()
    {
        var httpContext = new DefaultHttpContext
        {
            RequestServices = _serviceProvider,
        };

        var routeData = new RouteData();
        var actionDescriptor = new ActionDescriptor();

        return new ActionContext(httpContext, routeData, actionDescriptor);
    }

    private class NullView : IView
    {
        public static readonly NullView Instance = new NullView();
        public string Path => string.Empty;
        public Task RenderAsync(ViewContext context)
        {
            if (context == null) { throw new ArgumentNullException(nameof(context)); }
            return Task.CompletedTask;
        }
    }
}
```

#### Threading exception

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Items()
   at Microsoft.AspNetCore.Mvc.Routing.UrlHelperFactory.GetUrlHelper(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorPageActivator.<>c__DisplayClass4_0.<.ctor>b__0(ViewContext context)
   at Microsoft.Extensions.Internal.PropertyActivator`1.Activate(Object instance, TContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorPagePropertyActivator.Activate(Object page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorPageActivator.Activate(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)        
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.ViewViewComponentResult.ExecuteAsync(ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsync(ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeCoreAsync(ViewComponentDescriptor descriptor, Object arguments)
   at MyNamespace.Services.RenderViewComponentService.RenderViewComponentAsStringAsync[TViewComponent](Object args)
```

**Comment by snebjorn** [comment]
If anyone have some insight into what's going on with the multithread issue, then I'm all ears :)
https://stackoverflow.com/questions/64465484/threading-issue-when-using-iviewcomponenthelper-to-convert-viewcomponent-to-html

**Comment by snebjorn** [comment]
I haven't seen the NullReferenceException since. So I think it can be ignored.

**Comment by mkArtakMSFT** [comment]
Thanks @snebjorn.
This is not a mainline scenario for us to document. StackOverflow would be a good choice indeed.
