### ISSUE TITLE
.Net 5 RC2 Blazor Webassembly: Getting exception in console when hard-refreshing browser (Ctrl + F5)

### ISSUE THREAD

**Issue by bancroftway** [dotnet/aspnetcore#27122]
Prior to .Net 5 RC2, I was able to make a change to my components in Visual Studio, save and **in the browser**, hit Ctrl+F5 to force a hard refresh to cause a rebuild and see my changes in the browser. 

However, after .Net 5 RC2 upgrade, when I make a change in Visual Studio (and sometimes even without making a change) and then I hit Ctrl+F5, I get 2 separate exceptions in developer console, which I am noting below. 

A youtube video demostrating the issue is here: https://www.youtube.com/watch?v=oysurnesaek

Exception:
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at DPlan.Client.Pages.Forecast.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

d.printErr | @ | blazor.webassembly.js:1
-- | -- | --
  | d.preRun.push.window.Blazor._internal.dotNetCriticalError | @ | blazor.webassembly.js:1
  | w | @ | blazor.webassembly.js:1
  | _mono_wasm_invoke_js_blazor | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | do_icall | @ | 00ab9d9a:0x194db2
  | do_icall_wrapper | @ | 00ab9d9a:0x79dee
  | interp_exec_method | @ | 00ab9d9a:0x44ac8
  | interp_runtime_invoke | @ | 00ab9d9a:0x12ef59
  | mono_jit_runtime_invoke | @ | 00ab9d9a:0x118db9
  | do_runtime_invoke | @ | 00ab9d9a:0x79d37
  | mono_runtime_try_invoke | @ | 00ab9d9a:0x12977
  | mono_runtime_invoke | @ | 00ab9d9a:0x10eb85
  | mono_wasm_invoke_method | @ | 00ab9d9a:0x108e03
  | Module._mono_wasm_invoke_method | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | call_method | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | (anonymous) | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | endInvokeJSFromDotNet | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | Promise.then (async) |   |  
  | beginInvokeJSFromDotNet | @ | blazor.webassembly.js:1
  | w | @ | blazor.webassembly.js:1
  | _mono_wasm_invoke_js_blazor | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | do_icall | @ | 00ab9d9a:0x194db2
  | do_icall_wrapper | @ | 00ab9d9a:0x79dee
  | interp_exec_method | @ | 00ab9d9a:0x44ac8
  | interp_runtime_invoke | @ | 00ab9d9a:0x12ef59
  | mono_jit_runtime_invoke | @ | 00ab9d9a:0x118db9
  | do_runtime_invoke | @ | 00ab9d9a:0x79d37
  | mono_runtime_try_invoke | @ | 00ab9d9a:0x12977
  | mono_runtime_invoke | @ | 00ab9d9a:0x10eb85
  | mono_wasm_invoke_method | @ | 00ab9d9a:0x108e03
  | Module._mono_wasm_invoke_method | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | call_method | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | (anonymous) | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | endInvokeJSFromDotNet | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | Promise.then (async) |   |  
  | beginInvokeJSFromDotNet | @ | blazor.webassembly.js:1
  | w | @ | blazor.webassembly.js:1
  | _mono_wasm_invoke_js_blazor | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | do_icall | @ | 00ab9d9a:0x194db2
  | do_icall_wrapper | @ | 00ab9d9a:0x79dee
  | interp_exec_method | @ | 00ab9d9a:0x44ac8
  | interp_runtime_invoke | @ | 00ab9d9a:0x12ef59
  | mono_jit_runtime_invoke | @ | 00ab9d9a:0x118db9
  | do_runtime_invoke | @ | 00ab9d9a:0x79d37
  | mono_runtime_try_invoke | @ | 00ab9d9a:0x12977
  | mono_runtime_invoke | @ | 00ab9d9a:0x10eb85
  | mono_wasm_invoke_method | @ | 00ab9d9a:0x108e03
  | Module._mono_wasm_invoke_method | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | call_method | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | set_task_result | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | (anonymous) | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | Promise.then (async) |   |  
  | js_to_mono_obj | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | d.preRun.push.window.Blazor._internal.getSatelliteAssemblies | @ | blazor.webassembly.js:1
  | w | @ | blazor.webassembly.js:1
  | _mono_wasm_invoke_js_blazor | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | do_icall | @ | 00ab9d9a:0x194db2
  | do_icall_wrapper | @ | 00ab9d9a:0x79dee
  | interp_exec_method | @ | 00ab9d9a:0x44ac8
  | interp_runtime_invoke | @ | 00ab9d9a:0x12ef59
  | mono_jit_runtime_invoke | @ | 00ab9d9a:0x118db9
  | do_runtime_invoke | @ | 00ab9d9a:0x79d37
  | mono_runtime_invoke_checked | @ | 00ab9d9a:0xf652
  | mono_runtime_try_invoke_array | @ | 00ab9d9a:0x10e78b
  | ves_icall_InternalInvoke | @ | 00ab9d9a:0xed487
  | ves_icall_InternalInvoke_raw | @ | 00ab9d9a:0xecf4c
  | do_icall | @ | 00ab9d9a:0x194d3f
  | do_icall_wrapper | @ | 00ab9d9a:0x79dee
  | interp_exec_method | @ | 00ab9d9a:0x44ac8
  | interp_runtime_invoke | @ | 00ab9d9a:0x12ef59
  | mono_jit_runtime_invoke | @ | 00ab9d9a:0x118db9
  | do_runtime_invoke | @ | 00ab9d9a:0x79d37
  | mono_runtime_try_invoke | @ | 00ab9d9a:0x12977
  | mono_runtime_invoke | @ | 00ab9d9a:0x10eb85
  | mono_wasm_invoke_method | @ | 00ab9d9a:0x108e03
  | Module._mono_wasm_invoke_method | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | call_method | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | (anonymous) | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | callEntryPoint | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | a | @ | blazor.webassembly.js:1
  | Promise.then (async) |   |  
  | u | @ | blazor.webassembly.js:1
  | a | @ | blazor.webassembly.js:1
  | Promise.then (async) |   |  
  | u | @ | blazor.webassembly.js:1
  | a | @ | blazor.webassembly.js:1
  | Promise.then (async) |   |  
  | u | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | r | @ | blazor.webassembly.js:1
  | g | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | n | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
```

Exception 2:
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.UpdateRetainedChildComponent(DiffContext& diffContext, Int32 oldComponentIndex, Int32 newComponentIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

d.printErr | @ | blazor.webassembly.js:1
-- | -- | --
  | d.preRun.push.window.Blazor._internal.dotNetCriticalError | @ | blazor.webassembly.js:1
  | w | @ | blazor.webassembly.js:1
  | _mono_wasm_invoke_js_blazor | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | do_icall | @ | 00ab9d9a:0x194db2
  | do_icall_wrapper | @ | 00ab9d9a:0x79dee
  | interp_exec_method | @ | 00ab9d9a:0x44ac8
  | interp_runtime_invoke | @ | 00ab9d9a:0x12ef59
  | mono_jit_runtime_invoke | @ | 00ab9d9a:0x118db9
  | do_runtime_invoke | @ | 00ab9d9a:0x79d37
  | mono_runtime_try_invoke | @ | 00ab9d9a:0x12977
  | mono_runtime_invoke | @ | 00ab9d9a:0x10eb85
  | mono_wasm_invoke_method | @ | 00ab9d9a:0x108e03
  | Module._mono_wasm_invoke_method | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | call_method | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | set_task_result | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | (anonymous) | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | Promise.then (async) |   |  
  | js_to_mono_obj | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | mono_wasm_convert_return_value | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | _mono_wasm_invoke_js_with_args | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | do_icall | @ | 00ab9d9a:0x194d3f
  | do_icall_wrapper | @ | 00ab9d9a:0x79dee
  | interp_exec_method | @ | 00ab9d9a:0x44ac8
  | interp_runtime_invoke | @ | 00ab9d9a:0x12ef59
  | mono_jit_runtime_invoke | @ | 00ab9d9a:0x118db9
  | do_runtime_invoke | @ | 00ab9d9a:0x79d37
  | mono_runtime_try_invoke | @ | 00ab9d9a:0x12977
  | mono_runtime_invoke | @ | 00ab9d9a:0x10eb85
  | mono_wasm_invoke_method | @ | 00ab9d9a:0x108e03
  | Module._mono_wasm_invoke_method | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | call_method | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | set_task_result | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | (anonymous) | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | Promise.then (async) |   |  
  | js_to_mono_obj | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | mono_wasm_convert_return_value | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | _mono_wasm_invoke_js_with_args | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | do_icall | @ | 00ab9d9a:0x194d3f
  | do_icall_wrapper | @ | 00ab9d9a:0x79dee
  | interp_exec_method | @ | 00ab9d9a:0x44ac8
  | interp_runtime_invoke | @ | 00ab9d9a:0x12ef59
  | mono_jit_runtime_invoke | @ | 00ab9d9a:0x118db9
  | do_runtime_invoke | @ | 00ab9d9a:0x79d37
  | mono_runtime_try_invoke | @ | 00ab9d9a:0x12977
  | mono_runtime_invoke | @ | 00ab9d9a:0x10eb85
  | mono_wasm_invoke_method | @ | 00ab9d9a:0x108e03
  | Module._mono_wasm_invoke_method | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | call_method | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | set_task_result | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | (anonymous) | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | Promise.then (async) |   |  
  | js_to_mono_obj | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | d.preRun.push.window.Blazor._internal.getSatelliteAssemblies | @ | blazor.webassembly.js:1
  | w | @ | blazor.webassembly.js:1
  | _mono_wasm_invoke_js_blazor | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | do_icall | @ | 00ab9d9a:0x194db2
  | do_icall_wrapper | @ | 00ab9d9a:0x79dee
  | interp_exec_method | @ | 00ab9d9a:0x44ac8
  | interp_runtime_invoke | @ | 00ab9d9a:0x12ef59
  | mono_jit_runtime_invoke | @ | 00ab9d9a:0x118db9
  | do_runtime_invoke | @ | 00ab9d9a:0x79d37
  | mono_runtime_invoke_checked | @ | 00ab9d9a:0xf652
  | mono_runtime_try_invoke_array | @ | 00ab9d9a:0x10e78b
  | ves_icall_InternalInvoke | @ | 00ab9d9a:0xed487
  | ves_icall_InternalInvoke_raw | @ | 00ab9d9a:0xecf4c
  | do_icall | @ | 00ab9d9a:0x194d3f
  | do_icall_wrapper | @ | 00ab9d9a:0x79dee
  | interp_exec_method | @ | 00ab9d9a:0x44ac8
  | interp_runtime_invoke | @ | 00ab9d9a:0x12ef59
  | mono_jit_runtime_invoke | @ | 00ab9d9a:0x118db9
  | do_runtime_invoke | @ | 00ab9d9a:0x79d37
  | mono_runtime_try_invoke | @ | 00ab9d9a:0x12977
  | mono_runtime_invoke | @ | 00ab9d9a:0x10eb85
  | mono_wasm_invoke_method | @ | 00ab9d9a:0x108e03
  | Module._mono_wasm_invoke_method | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | call_method | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | (anonymous) | @ | dotnet.5.0.0-rc.2.20475.5.js:1
  | callEntryPoint | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | a | @ | blazor.webassembly.js:1
  | Promise.then (async) |   |  
  | u | @ | blazor.webassembly.js:1
  | a | @ | blazor.webassembly.js:1
  | Promise.then (async) |   |  
  | u | @ | blazor.webassembly.js:1
  | a | @ | blazor.webassembly.js:1
  | Promise.then (async) |   |  
  | u | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | r | @ | blazor.webassembly.js:1
  | g | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | n | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
  | (anonymous) | @ | blazor.webassembly.js:1
```

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
