### ISSUE TITLE
TaghelperSemanticRangeVisitor occasionally finds unknown SyntaxKinds

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/aspnetcore#27120]
Repro:
1. In a new Page write
```razor
@page "/"
<h1>Hello, world!</h1>
Welcome to your new app.
<SurveyPrompt Title="How is Blazor working for you?" />
```
1. Type "nonsense" like `<foo foo foo`, `<input test="foo"` and `@code{`
1. If you're (un)lucky you'll see a yellow-bar which leads to a log such as:
```
Internal Error - System.NotImplementedException: The method or operation is not implemented.
 at Microsoft.AspNetCore.Razor.LanguageServer.Semantic.TagHelperSemanticRangeVisitor.AddSemanticRange(SyntaxNode node, Nullable`1 kind)
 at Microsoft.AspNetCore.Razor.LanguageServer.Semantic.TagHelperSemanticRangeVisitor.VisitMarkupMinimizedAttributeBlock(MarkupMinimizedAttributeBlockSyntax node)
 at Microsoft.AspNetCore.Razor.Language.Syntax.MarkupMinimizedAttributeBlockSyntax.Accept(SyntaxVisitor visitor)
 at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxWalker.Visit(SyntaxNode node)
 at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxWalker.DefaultVisit(SyntaxNode node)
 at Microsoft.AspNetCore.Razor.LanguageServer.Semantic.TagHelperSemanticRangeVisitor.VisitMarkupStartTag(MarkupStartTagSyntax node) at Microsoft.AspNetCore.Razor.Language.Syntax.MarkupStartTagSyntax.Accept(SyntaxVisitor visitor)
 at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxWalker.Visit(SyntaxNode node) at ...
--
```

This exception means that the Visitor encountered a SyntaxType that it should not have. I sent a PR to prevent scenarios like this from throwing exceptions in production (https://github.com/dotnet/aspnetcore-tooling/pull/2664) but we need to find the real root-cause that's sending us off the rails.

**Comment by NTaylorMullen** [comment]
@ryanbrandenburg is this still true?

**Comment by ryanbrandenburg** [comment]
Seems like no, closing.
