### ISSUE TITLE
Flaky test: DefaultTagHelperOptimizationPass_Execute_ReplacesChildren

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#27154]
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=862695&view=results

Error:
```
System.NullReferenceException : Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.SyntaxTokenCache.GetCachedToken(SyntaxKind kind, String content) in /_/src/Razor/Microsoft.AspNetCore.Razor.Language/src/Syntax/InternalSyntax/SyntaxTokenCache.cs:line 61
   at Microsoft.AspNetCore.Razor.Language.Legacy.Tokenizer.EndToken(SyntaxKind type) in /_/src/Razor/Microsoft.AspNetCore.Razor.Language/src/Legacy/Tokenizer.cs:line 215
   at Microsoft.AspNetCore.Razor.Language.Legacy.HtmlTokenizer.Data() in /_/src/Razor/Microsoft.AspNetCore.Razor.Language/src/Legacy/HtmlTokenizer.cs:line 128
   at Microsoft.AspNetCore.Razor.Language.Legacy.HtmlTokenizer.Dispatch() in /_/src/Razor/Microsoft.AspNetCore.Razor.Language/src/Legacy/HtmlTokenizer.cs:line 50
   at Microsoft.AspNetCore.Razor.Language.Legacy.Tokenizer.Turn() in /_/src/Razor/Microsoft.AspNetCore.Razor.Language/src/Legacy/Tokenizer.cs:line 104
   at Microsoft.AspNetCore.Razor.Language.Legacy.Tokenizer.NextToken() in /_/src/Razor/Microsoft.AspNetCore.Razor.Language/src/Legacy/Tokenizer.cs:line 86
   at Microsoft.AspNetCore.Razor.Language.Legacy.TokenizerView`1.Next() in /_/src/Razor/Microsoft.AspNetCore.Razor.Language/src/Legacy/TokenizerView.cs:line 27
   at Microsoft.AspNetCore.Razor.Language.Legacy.HtmlMarkupParser.ParseDocument() in /_/src/Razor/Microsoft.AspNetCore.Razor.Language/src/Legacy/HtmlMarkupParser.cs:line 55
   at Microsoft.AspNetCore.Razor.Language.Legacy.RazorParser.Parse(RazorSourceDocument source) in /_/src/Razor/Microsoft.AspNetCore.Razor.Language/src/Legacy/RazorParser.cs:line 44
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorParsingPhase.ExecuteCore(RazorCodeDocument codeDocument) in /_/src/Razor/Microsoft.AspNetCore.Razor.Language/src/DefaultRazorParsingPhase.cs:line 18
   at Microsoft.AspNetCore.Razor.Language.Extensions.DefaultTagHelperOptimizationPassTest.CreateIRDocument(RazorEngine engine, RazorCodeDocument codeDocument) in /_/src/Razor/Microsoft.AspNetCore.Razor.Language/test/Extensions/DefaultTagHelperOptimizationPassTest.cs:line 100
   at Microsoft.AspNetCore.Razor.Language.Extensions.DefaultTagHelperOptimizationPassTest.DefaultTagHelperOptimizationPass_Execute_ReplacesChildren() in /_/src/Razor/Microsoft.AspNetCore.Razor.Language/test/Extensions/DefaultTagHelperOptimizationPassTest.cs:line 33
```

cc @NTaylorMullen @ajaybhargavb

**Comment by ajaybhargavb** [comment]
@ToddGrun, do you by any chance have an idea why this could happen?

**Comment by ToddGrun** [comment]
> @ToddGrun, do you by any chance have an idea why this could happen?

Trying to shake the dust off my memory here. Is it possible that it's passed in a null content? However, I doubt that's the issue as it's complaining about line 61 in the callstack above, which is code that uses s_cache (a static that is initialized during static initialization and is never deleted).

**Comment by m0sa** [comment]
We're seeing this quite regularly in our builds after switching to the .NET 5 SDK, too. Is there any chance for a fix for this to make it into the 5.* SDK instead of 6?

**Comment by NickCraver** [comment]
@clairernovotny Is there any chance of this being fixed in a 5.x release, since it is a bug? @m0sa can help provide information as much as we're able.

**Comment by mkArtakMSFT** [comment]
Thanks for sharing additional details, folks. We're going to investigate this soon and will make decision after we will better understand what causes this.

**Comment by ericstj** [comment]
https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Razor/Microsoft.AspNetCore.Razor.Language/src/Syntax/InternalSyntax/SyntaxTokenCache.cs#L63

Missing a null check here.  Perhaps Hash happens to match default value and token is null.  That would explain flakiness.

**Comment by ericstj** [comment]
@ToddGrun looks like this was dropped in your change: https://github.com/dotnet/aspnetcore/commit/837c6390411ba4f1770f858fff6555290006c288#diff-bc98d2b27d101f590cb98d27b5f8a7e68e5dc16b165e84b95989ebee3e022ecdL35

**Comment by ToddGrun** [comment]
That does look suspicious, I don't remember intentionally dropping the null check there

**Comment by pranavkm** [comment]
We'll use https://github.com/dotnet/aspnetcore/issues/30979 to port this to 5.0.
