### ISSUE TITLE
Flaky test: "SignalRClientWorksWithLongPolling"

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#27156]
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=863182&view=results

Error:
```
OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.NotEmptyException: Assert.NotEmpty() Failure
   at Xunit.Assert.NotEmpty(IEnumerable collection) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 331
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<Exists>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 72
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver ) in //src/Shared/E2ETesting/WaitAssert.cs:line 109
   Screen shot captured at 'F:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.AspNetCore.Components.E2ETests\f163ef951f0844d0adfd41460fe0a86b.png'
Page content:
<head>
    <meta charset="utf-8">
    <title>Basic test app</title>
    <base href="/subdir/">
    <link href="style.css" rel="stylesheet">
    <link rel="icon" href="data:,">
    
    
    <link href="_content/TestContentPackage/styles.css" rel="stylesheet">
    
    
    <link href="BasicTestApp.styles.css" rel="stylesheet">
    </head>

<body>
    <root><div id="test-selector">
    Select test:
    <select id="test-selector-select"><option value="none">Choose...
        <option value="BasicTestApp.AfterRenderInteropComponent">After-render interop component
        <option value="BasicTestApp.AuthTest.AuthRouter">Auth cases
        <option value="BasicTestApp.BindCasesComponent">bind cases
        <option value="BasicTestApp.ComponentRefComponent">Component ref component
        <option value="BasicTestApp.ConfigurationComponent">Configuration
        <option value="BasicTestApp.CounterComponent">Counter
        <option value="BasicTestApp.CounterComponentWrapper">Counter wrapped in parent
        <option value="BasicTestApp.DataDashComponent">data-* attribute rendering
        <option value="BasicTestApp.DuplicateAttributesComponent">Duplicate attributes
        <option value="BasicTestApp.ElementRefComponent">Element ref component
        <option value="BasicTestApp.EventBubblingComponent">Event bubbling
        <option value="BasicTestApp.EventCasesComponent">Event cases<!--!
at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 139
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.Exists(IWebDriver driver, By finder, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 67
   at Microsoft.AspNetCore.Components.E2ETest.BasicTestAppWebDriverExtensions.WaitUntilTestSelectorReady(IWebDriver browser) in /_/src/Components/test/E2ETest/Infrastructure/WebDriverExtensions/BasicTestAppWebDriverExtensions.cs:line 24
   at Microsoft.AspNetCore.Components.E2ETest.BasicTestAppWebDriverExtensions.MountTestComponent[TComponent](IWebDriver browser) in /_/src/Components/test/E2ETest/Infrastructure/WebDriverExtensions/BasicTestAppWebDriverExtensions.cs:line 18
   at Microsoft.AspNetCore.Components.E2ETest.Tests.SignalRClientTest.InitializeAsyncCore() in /_/src/Components/test/E2ETest/Tests/SignalRClientTest.cs:line 38
   at Microsoft.AspNetCore.E2ETesting.BrowserTestBase.InitializeAsync(String isolationContext) in /_/src/Shared/E2ETesting/BrowserTestBase.cs:line 71
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<Exists>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 72
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 109
```

**Comment by TanayParikh** [comment]
30 day review is scheduled for 7/2/2021.

**Comment by JunTaoLuo** [comment]
This test doesn't show up in the pipeline https://dev.azure.com/dnceng/public/_test/analytics?definitionId=331 I don't think it's running there. I was able to find the test running in the pipeline https://dev.azure.com/dnceng/public/_test/analytics?definitionId=869 though. And there I saw a failure, https://dev.azure.com/dnceng/public/_build/results?buildId=1192755&view=results
```
OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: SignalR Client: Echo LongPolling
Actual:   (null)
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer1 comparer) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\EqualityAsserts.cs:line 40
 at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 83
 at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_01.<WaitAssertCore>b__0(IWebDriver ) in //src/Shared/E2ETesting/WaitAssert.cs:line 109
Screen shot captured at 'D:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.AspNetCore.Components.E2ETests\f6cc3cb5aadb45ab8f889f06a1a65b2b.png'
Encountered browser errors
[2021-06-17T19:23:47Z] [Debug] http://127.0.0.1:1039/subdir/_framework/dotnet.6.0.0-preview.6.21306.1.js 0:137664 "mono_wasm_runtime_ready" "fe00e07a-5519-4dfe-b35a-f867dbaf2e28"
[2021-06-17T19:23:49Z] [Severe] http://127.0.0.1:1066/subdir/chathub?id=WX0e9o-DIaNSQGsrEI41XA - Failed to load resource: net::ERR_ADDRESS_IN_USE
[2021-06-17T19:23:49Z] [Severe] http://127.0.0.1:1039/subdir/_framework/blazor.webassembly.js 0:27658 "crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: TypeError: Failed to fetch
System.Net.Http.HttpRequestException: TypeError: Failed to fetch
   at System.Net.Http.BrowserHttpHandler.SendAsync(HttpRequestMessage , CancellationToken )
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.AccessTokenHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.\u003CSendAsync>g__Core|83_0(HttpRequestMessage , HttpCompletionOption , CancellationTokenSource , Boolean , CancellationTokenSource , CancellationToken )
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.SendUtils.SendMessages(Uri sendUrl, IDuplexPipe application, HttpClient httpClient, ILogger logger, CancellationToken cancellationToken)
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& )
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 )
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.HandshakeAsync(ConnectionState startingConnectionState, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
   at BasicTestApp.SignalRClientComponent.Connect()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task )
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )"
[2021-06-17T19:23:49Z] [Severe] http://127.0.0.1:1039/subdir/_framework/blazor.webassembly.js 0:27658 "crit: [100]
      [Custom logger] Unhandled exception rendering component: TypeError: Failed to fetch
System.Net.Http.HttpRequestException: TypeError: Failed to fetch
   at System.Net.Http.BrowserHttpHandler.SendAsync(HttpRequestMessage , CancellationToken )
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.AccessTokenHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client
```

**Comment by TanayParikh** [comment]
Hmm, this seems to be a new failure (unrelated to original failure from the issue). 

```
[2021-06-17T19:23:49Z] [Severe] http://127.0.0.1:1066/subdir/chathub?id=WX0e9o-DIaNSQGsrEI41XA - Failed to load resource: net::ERR_ADDRESS_IN_USE
```

Seems to indicate failure [here](https://github.com/dotnet/aspnetcore/blob/b444d8eb1547cff83420f63562d2e1c79991755e/src/Components/test/E2ETest/Tests/SignalRClientTest.cs#L50-L51), as opposed to [here](https://github.com/dotnet/aspnetcore/blob/b444d8eb1547cff83420f63562d2e1c79991755e/src/Components/test/E2ETest/Tests/SignalRClientTest.cs#L54) in the original issue.

@captainsafia @HaoK any ideas what could be causing `Failed to load resource: net::ERR_ADDRESS_IN_USE`?

**Comment by HaoK** [comment]
We started doing retry = 3 could that be a symptom of that change where maybe its running into issues with old instances staying alive so the retry fails in a different way?

**Comment by TanayParikh** [comment]
Hmm that seems like a reasonable possibility. What would be a good way to test that hypothesis? Selectively disable retry for the test?

**Comment by HaoK** [comment]
Yeah, you might have to add a special -1 to disable retries to the xunit attribute I added, since today I think it defaults to 3 for anything less than 1.  Perhaps add a special -1 value to turn off retries to opt out

**Comment by TanayParikh** [comment]
My concern is though, there's nothing inherently special about this test case which could cause the old instances to stay alive a bit longer than usual. That is to say, even if we disable retry on this, I believe we'll run into this issue on other test cases.

**Comment by HaoK** [comment]
Yeah, its possible there needs to be more work done for selenium based test retries to work well (maybe we need to stop running them all in parallel?)

**Comment by TanayParikh** [comment]
> Yeah, its possible there needs to be more work done for selenium based test retries to work well (maybe we need to stop running them all in parallel?)

@javiercn thoughts? Should we discuss this in DOI?

**Comment by HaoK** [comment]
This is specific to blazor I think since its doing some text fixture setup, @SteveSandersonMS also ran into this so I think https://github.com/dotnet/aspnetcore/issues/34424 is good to track this issue separately

**Comment by TanayParikh** [comment]
> This is specific to blazor I think since its doing some text fixture setup, @SteveSandersonMS also ran into this so I think #34424 is good to track this issue separately

Thanks Hao, that makes sense. I'm going to consider this **resolved** however will keep the issue open (and tag with `test-fixed once https://github.com/dotnet/aspnetcore/pull/34526 is merged) in accordance with the un-quarantining procedures.

**Comment by TanayParikh** [comment]
Seeing a consistent 30 day pass rate (with the exception of one unrelated infra failure:

![image](https://user-images.githubusercontent.com/14852843/126517234-cc7ca83a-52fb-44b8-9228-1a836acee7b0.png)


One unrelated infra failure:
<details>
```
System.Net.Http.HttpRequestException : No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:51361 (localhost:51361)\r\n---- System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : No connection could be made because the target machine actively refused it. [::ffff:127.0.0.1]:51361
```

```
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) in System.Net.Http.dll:token 0x6000755+0x28c
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in System.Net.Http.dll:token 0x6000754+0xf2
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in System.Net.Http.dll:token 0x6000756+0x8f
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request) in System.Net.Http.dll:token 0x600073b+0xb7
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) in System.Net.Http.dll:token 0x60000ae+0xa4
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in System.Net.Http.dll:token 0x600073d+0x1c1
   at System.Net.Http.HttpConnectionPool.SendUsingHttp11Async(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in System.Net.Http.dll:token 0x6000745+0x8f
   at System.Net.Http.HttpConnectionPool.DetermineVersionAndSendAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in System.Net.Http.dll:token 0x6000746+0x224
   at System.Net.Http.HttpConnectionPool.SendAndProcessAltSvcAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in System.Net.Http.dll:token 0x6000747+0x8e
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in System.Net.Http.dll:token 0x6000748+0x99
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in System.Net.Http.dll:token 0x60007f7+0x94
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in System.Net.Http.dll:token 0x6000264+0xae
   at Microsoft.AspNetCore.E2ETesting.SeleniumStandaloneServer.InitializeInstance(ITestOutputHelper output) in /_/src/Shared/E2ETesting/SeleniumStandaloneServer.cs:line 181
   at Microsoft.AspNetCore.E2ETesting.SeleniumStandaloneServer.GetInstanceAsync(ITestOutputHelper output) in /_/src/Shared/E2ETesting/SeleniumStandaloneServer.cs:line 74
   at Microsoft.AspNetCore.E2ETesting.BrowserFixture.CreateBrowserAsync(String context, ITestOutputHelper output) in /_/src/Shared/E2ETesting/BrowserFixture.cs:line 177
   at Microsoft.AspNetCore.E2ETesting.BrowserTestBase.InitializeBrowser(String isolationContext) in /_/src/Shared/E2ETesting/BrowserTestBase.cs:line 81
   at Microsoft.AspNetCore.E2ETesting.BrowserTestBase.InitializeAsync(String isolationContext) in /_/src/Shared/E2ETesting/BrowserTestBase.cs:line 68
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress) in System.Net.Sockets.dll:token 0x6000217+0xa0
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP) in System.Net.Sockets.dll:token 0x600019a+0xdb
   at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port) in System.Net.Sockets.dll:token 0x600019d+0x8e
--- End of stack trace from previous location ---
   at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port) in System.Net.Sockets.dll:token 0x600019d+0xcc
   at System.Net.Sockets.Socket.Connect(String host, Int32 port) in System.Net.Sockets.dll:token 0x600019c+0x5f
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP) in System.Net.Socke
```
</details>

**Comment by TanayParikh** [comment]
Unquarantined: https://github.com/dotnet/aspnetcore/pull/34622
