### ISSUE TITLE
Flaky test "CreateServiceAsync_SessionDispose_CancelsListRootsToken"

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#27159]
Looks like this is flaky since it's passing on other similar branches but could be a issue with the release/vscode16.8-preview3V2 branch specifically.

Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=862410&view=results

Error:
```
Assert.True() Failure\r\nExpected: True\r\nActual:   False
at Microsoft.VisualStudio.LiveShare.Razor.Guest.RazorGuestInitializationServiceTest.<>c__DisplayClass5_1.<CreateServiceAsync_SessionDispose_CancelsListRootsToken>b__2() in /_/src/Razor/test/Microsoft.VisualStudio.LiveShare.Razor.Test/Guest/RazorGuestInitializationServiceTest.cs:line 56
at System.Threading.Tasks.Task`1.InnerInvoke()
at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.LiveShare.Razor.Guest.RazorGuestInitializationService.<EnsureViewImportsCopiedAsync>d__5.MoveNext() in /_/src/Razor/src/Microsoft.VisualStudio.LiveShare.Razor/Guest/RazorGuestInitializationService.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.LiveShare.Razor.Guest.RazorGuestInitializationServiceTest.<CreateServiceAsync_SessionDispose_CancelsListRootsToken>d__5.MoveNext() in /_/src/Razor/test/Microsoft.VisualStudio.LiveShare.Razor.Test/Guest/RazorGuestInitializationServiceTest.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

cc @NTaylorMullen @ajaybhargavb

**Comment by JunTaoLuo** [comment]
Hmm I can't seem to find the branch. I'll let you folks quarantine it then.
