### ISSUE TITLE
Razor Code Actions Not Working

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#27162]
Looks like code actions stopped working after [latest O# update](https://github.com/dotnet/aspnetcore-tooling/pull/2663). This PR removes the use of `RazorCodeAction` in it's entirety as O# `CodeAction` has [added the `Data` field](https://github.com/OmniSharp/csharp-language-server-protocol/blame/master/src/Protocol/Models/CodeAction.cs#L83).

```
Internal Error - System.InvalidCastException: Unable to cast object of type 'Microsoft.AspNetCore.Razor.LanguageServer.CodeActions.CodeActionResolutionEndpoint' to type 'MediatR.IRequestHandler`2[Microsoft.AspNetCore.Razor.LanguageServer.CodeActions.Models.RazorCodeAction,OmniSharp.Extensions.LanguageServer.Protocol.Models.CodeAction]'.
   at OmniSharp.Extensions.JsonRpc.JsonRpcServerServiceCollectionExtensions.RequestHandlerDecorator`2.Handle(T request, CancellationToken cancellationToken)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|5_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.InputHandler.<>c__DisplayClass38_0.<<RouteRequest>b__5>d.MoveNext()
```

**Comment by TanayParikh** [comment]
Validation:
Razor
1. Razor create component from tag -> go to new component, add `@namespace SomeNamespace`
2. Razor fully qualify -> return to where you typed the component, you should get code action to fully qualify
3. Same as 2, but for add `@using`

C#
1. Add using `Debugger.Launch();`
2. Same as 1 but fully qualify
