### ISSUE TITLE
Default MVC template not working on Docker on Linux: The view 'Index' was not found

### ISSUE THREAD

**Issue by HerrKauwer** [dotnet/aspnetcore#27232]
### Describe the bug
I found this when trying to run Identity Server on Kubernetes. Turns out it also fails with the default MVC template when running in docker on Linux. When opening the website in a browser I get a 500 and the logs will output
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor[3]
      The view 'Index' was not found. Searched locations: /Views/Home/Index.cshtml, /Views/Shared/Index.cshtml

### To Reproduce
Prepare a Linux machine with docker installed. I used Ubuntu Server 20.04
You can checkout https://github.com/HerrKauwer/viewnotfoundrepro and skip to the docker build step or you can create the repro project yourself.

mkdir WebApp
cd WebApp
dotnet new mvc --no-restore

Create Dockerfile with contents:
```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app

COPY ./*.csproj ./
WORKDIR /app
RUN dotnet restore

WORKDIR /app
COPY ./* ./
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "WebApp.dll"]
```

docker build -t webapp .
docker run --rm -it -p 5000:80 webapp:latest

Open a browser to your machine at http://ip_or_hostname:5000 and you will see the 500 error. In the logs you can find the exceptions, which I have posted below.

I get the same result with Azure container instances. Public image: https://hub.docker.com/repository/docker/marvinrgbplus/test

It works when I run it outside of docker with `dotnet run` or with `dotnet WebApp.dll` in out after running `dotnet publish -c Release -o out`

### Exceptions (if any)
```
$ docker run --rm -it -p 5000:80 webapp:latest
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {75441328-e7e1-41e4-a795-da39aa698f9b} may be persisted to storage in unencrypted form.
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:80
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
fail: Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor[3]
      The view 'Index' was not found. Searched locations: /Views/Home/Index.cshtml, /Views/Shared/Index.cshtml
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The view 'Index' was not found. The following locations were searched:
/Views/Home/Index.cshtml
/Views/Shared/Index.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
fail: Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor[3]
      The view 'Error' was not found. Searched locations: /Views/Home/Error.cshtml, /Views/Shared/Error.cshtml
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[3]
      An exception was thrown attempting to execute the error handler.
System.InvalidOperationException: The view 'Error' was not found. The following locations were searched:
/Views/Home/Error.cshtml
/Views/Shared/Error.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM3PSUSC97PN", Request id "0HM3PSUSC97PN:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: The view 'Index' was not found. The following locations were searched:
/Views/Home/Index.cshtml
/Views/Shared/Index.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```
### Further technical details
- ASP.NET Core version
3.1
- Include the output of `dotnet --info`
.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.402/

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  3.1.402 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
n/a

**Comment by ikkentim** [comment]
Views appear to be compiled with paths such as `/Home/Index.cshtml` while location `/Views/Home/Index.cshtml` is searched. When I run this app locally on Windows (build using `dotnet publish`), the views are compiled to path `/Views/Home/Index.cshtml`.

Logs in docker
```
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1],
      Executing controller factory for controller WebApp.Controllers.HomeController (WebApp),
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2],
      Executed controller factory for controller WebApp.Controllers.HomeController (WebApp),
dbug: Microsoft.AspNetCore.Mvc.Razor.Compilation.DefaultViewCompiler[3],
      Initializing Razor view compiler with compiled view: '/Home/Index.cshtml'.,
dbug: Microsoft.AspNetCore.Mvc.Razor.Compilation.DefaultViewCompiler[3],
      Initializing Razor view compiler with compiled view: '/Home/Privacy.cshtml'.,
dbug: Microsoft.AspNetCore.Mvc.Razor.Compilation.DefaultViewCompiler[3],
      Initializing Razor view compiler with compiled view: '/Shared/Error.cshtml'.,
dbug: Microsoft.AspNetCore.Mvc.Razor.Compilation.DefaultViewCompiler[3],
      Initializing Razor view compiler with compiled view: '/Shared/_Layout.cshtml'.,
dbug: Microsoft.AspNetCore.Mvc.Razor.Compilation.DefaultViewCompiler[3],
      Initializing Razor view compiler with compiled view: '/Shared/_ValidationScriptsPartial.cshtml'.,
dbug: Microsoft.AspNetCore.Mvc.Razor.Compilation.DefaultViewCompiler[3],
      Initializing Razor view compiler with compiled view: '/_ViewImports.cshtml'.,
dbug: Microsoft.AspNetCore.Mvc.Razor.Compilation.DefaultViewCompiler[3],
      Initializing Razor view compiler with compiled view: '/_ViewStart.cshtml'.,
dbug: Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine[1],
      View lookup cache miss for view 'Index' in controller 'Home'.,
info: Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor[1],
      Executing ViewResult, running view Index.,
fail: Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor[3],
      The view 'Index' was not found. Searched locations: /Views/Home/Index.cshtml, /Views/Shared/Index.cshtml,
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2],
      Executed action WebApp.Controllers.HomeController.Index (WebApp) in 20.7902ms,
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1],
      Executed endpoint 'WebApp.Controllers.HomeController.Index (WebApp)',
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1],
      An unhandled exception has occurred while executing the request.,
System.InvalidOperationException: The view 'Index' was not found. The following locations were searched:,
/Views/Home/Index.cshtml,
/Views/Shared/Index.cshtml,
```

Logs local
```
bug: Microsoft.AspNetCore.Mvc.Razor.Compilation.DefaultViewCompiler[3]
      Initializing Razor view compiler with compiled view: '/Views/Home/Index.cshtml'.
dbug: Microsoft.AspNetCore.Mvc.Razor.Compilation.DefaultViewCompiler[3]
      Initializing Razor view compiler with compiled view: '/Views/Home/Privacy.cshtml'.
dbug: Microsoft.AspNetCore.Mvc.Razor.Compilation.DefaultViewCompiler[3]
      Initializing Razor view compiler with compiled view: '/Views/Shared/Error.cshtml'.
dbug: Microsoft.AspNetCore.Mvc.Razor.Compilation.DefaultViewCompiler[3]
      Initializing Razor view compiler with compiled view: '/Views/Shared/_Layout.cshtml'.
dbug: Microsoft.AspNetCore.Mvc.Razor.Compilation.DefaultViewCompiler[3]
      Initializing Razor view compiler with compiled view: '/Views/Shared/_ValidationScriptsPartial.cshtml'.
dbug: Microsoft.AspNetCore.Mvc.Razor.Compilation.DefaultViewCompiler[3]
      Initializing Razor view compiler with compiled view: '/Views/_ViewImports.cshtml'.
dbug: Microsoft.AspNetCore.Mvc.Razor.Compilation.DefaultViewCompiler[3]
      Initializing Razor view compiler with compiled view: '/Views/_ViewStart.cshtml'.
```

Local version

```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.402\

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  3.1.300 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by Alex2357** [comment]
I'm having this problem. Any workaround for this?
I'm using 
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
and 
FROM mcr.microsoft.com/dotnet/aspnet:3.1

**Comment by HerrKauwer** [comment]
Hi @Alex2357,

I found out that it works if you build your project outside Docker and then copy your output to your image. Based on my previous steps to reproduce:

mkdir WebApp
cd WebApp
dotnet new mvc --no-restore

Create Dockerfile with contents:
```
FROM mcr.microsoft.com/dotnet/aspnet:3.1
WORKDIR /app
COPY ./out .
ENTRYPOINT ["dotnet", "WebApp.dll"]
```

docker build -t webapp .
docker run --rm -it -p 5000:80 webapp:latest

**Comment by e-davidson** [comment]
@HerrKauwer 

I don't believe this is an aspnet issue.

The issue is in your docker file.

The line `COPY ./*  ./` isn't copying over the directories themselves in the root of the project. Instead the contents of the directories are getting copied into /app. Therefor the `View` folder does not exist. Hence the name of the View class is Home_Index instead of Views_Home_Index.

If you'd change it to `COPY . .` instead it'll work as expected.

**Comment by e-davidson** [comment]
Another solution, you can add the view paths manually

```
services.AddControllersWithViews()
   .AddRazorOptions( options => {
       options.ViewLocationFormats.Add("/{1}/{0}.cshtml");
       options.ViewLocationFormats.Add("/Shared/{0}.cshtml");
});
```

**Comment by HerrKauwer** [comment]
@e-davidson 
Thank you for your answer, that was exactly the problem! I tried your solution and it works fine now.
