### ISSUE TITLE
Fix flakiness of SignalRClientTest.SignalRClientWorksWithLongPolling

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#27317]
### Describe the bug
This test brought down https://dev.azure.com/dnceng/public/_build/results?buildId=863182, a rolling (public) build of our master branch. Not sure if an underlying Selenium infrastructure or SignalR problem contributed to the failure. Hopefully this is just a problem with the test's resiliency.

### To Reproduce

I don't know. Run the test a 💯 times❔

### Exceptions (if any)

``` text
OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.NotEmptyException: Assert.NotEmpty() Failure
   at Xunit.Assert.NotEmpty(IEnumerable collection) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 331
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<Exists>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 72
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver ) in //src/Shared/E2ETesting/WaitAssert.cs:line 109
Screen shot captured at 'F:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.AspNetCore.Components.E2ETests\f163ef951f0844d0adfd41460fe0a86b.png'
Page content:
<head>
    <meta charset="utf-8">
    <title>Basic test app</title>
    <base href="/subdir/">
    <link href="style.css" rel="stylesheet">
    <link rel="icon" href="data:,">

    
    <link href="_content/TestContentPackage/styles.css" rel="stylesheet">

    
    <link href="BasicTestApp.styles.css" rel="stylesheet">
</head>

<body>
    <root><div id="test-selector">
    Select test:
    <select id="test-selector-select"><option value="none">Choose...
        <option value="BasicTestApp.AfterRenderInteropComponent">After-render interop component
        <option value="BasicTestApp.AuthTest.AuthRouter">Auth cases
        <option value="BasicTestApp.BindCasesComponent">bind cases
        <option value="BasicTestApp.ComponentRefComponent">Component ref component
        <option value="BasicTestApp.ConfigurationComponent">Configuration
        <option value="BasicTestApp.CounterComponent">Counter
        <option value="BasicTestApp.CounterComponentWrapper">Counter wrapped in parent
        <option value="BasicTestApp.DataDashComponent">data-* attribute rendering
        <option value="BasicTestApp.DuplicateAttributesComponent">Duplicate attributes
        <option value="BasicTestApp.ElementRefComponent">Element ref component
        <option value="BasicTestApp.EventBubblingComponent">Event bubbling
        <option value="BasicTestApp.EventCasesComponent">Event cases<!--!
```

**Comment by dougbu** [comment]
https://dev.azure.com/dnceng/_apis/resources/Containers/5391553/Windows_Test_Logs?itemPath=Windows_Test_Logs%2FRelease%2FMicrosoft.AspNetCore.Components.E2ETests_net5.0_x64.log (also attached) may contain additional detail.
[Uploading Microsoft.AspNetCore.Components.E2ETests_net5.0_x64.log…]()

**Comment by BrennanConroy** [comment]
Dupe of https://github.com/dotnet/aspnetcore/issues/27156

**Comment by dougbu** [comment]
Could you or @JunTaoLuo please explain why the test hasn't yet been quarantined❔ I'll reference the older bug when I do that but would appreciate knowing the history.

**Comment by BrennanConroy** [comment]
https://github.com/dotnet/aspnetcore/blob/79298120e22c3178236a2698ad08703bfd99bc20/src/Components/test/E2ETest/Tests/SignalRClientTest.cs#L44

**Comment by dougbu** [comment]
Oops, my master branch was out-of-date. Sorry.
