### ISSUE TITLE
ListenAnyIP_HostName_Success and RegisterAddresses_HostName_Success test failure

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#27377]
Failures I saw were all on OSX and these two tests fail together. Likely need to update the `HostNameIsReachableAttribute`.

```
System.Net.Sockets.SocketException : nodename nor servname provided, or not known
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetSocket(Uri requestUri) in /_/src/Testing/src/HttpClientSlim.cs:line 189
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStream(Uri requestUri, Boolean validateCertificate) in /_/src/Testing/src/HttpClientSlim.cs:line 152
   at Microsoft.AspNetCore.Testing.HttpClientSlim.<>c__DisplayClass1_0.<<GetStringAsync>b__0>d.MoveNext() in /_/src/Testing/src/HttpClientSlim.cs:line 33
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Testing.HttpClientSlim.RetryRequest(Func`1 retryBlock) in /_/src/Testing/src/HttpClientSlim.cs:line 121
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(Uri requestUri, Boolean validateCertificate) in /_/src/Testing/src/HttpClientSlim.cs:line 31
   at Microsoft.AspNetCore.Testing.HttpClientSlim.GetStringAsync(String requestUri, Boolean validateCertificate) in /_/src/Testing/src/HttpClientSlim.cs:line 26
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterAddresses_Success(String addressInput, String[] testUrls, Int32 testPort) in /_/src/Servers/Kestrel/test/BindTests/AddressRegistrationTests.cs:line 212
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterAddresses_HostName_Success() in /_/src/Servers/Kestrel/test/BindTests/AddressRegistrationTests.cs:line 42
--- End of stack trace from previous location ---
```

**Comment by jkotalik** [comment]
I believe this isn't an issue with the HostNameIsReachableAttribute, rather the hosting being unavailable after the check for HostNameIsReachableAttribute. I'm looking at the [test history](https://dev.azure.com/dnceng/public/_test/analytics?definitionId=331&contextType=build) for these and the failures "Name does not resolve" (SocketError.NetworkUnreachable) and "nodename nor servname provided, or not known" (SocketError.HostNotFound) are already check for by HostNameIsReachableAttribute. It looks like the check is catching some of the failures (some tests are skipped), but it's a point in time failure so sometimes it will fail.

Few proposals:
1. Skip these entirely on macOS.
2. Add retries via a bool to HttpClientSlim (opt in)

**Comment by jkotalik** [comment]
And we already do do retries on macOS...

https://github.com/dotnet/aspnetcore/blame/main/src/Testing/src/HttpClientSlim.cs#L111

**Comment by halter73** [comment]
Transient failures and we're already retyring up to 3 times on macOS. I vote skip.

**Comment by amcasey** [comment]
Still flaky.

**Comment by amcasey** [comment]
Most recent [failure](https://dev.azure.com/dnceng-public/public/_build/results?buildId=792023) was on Alpine.

```
System.Net.Sockets.SocketException : Name does not resolve

   at Microsoft.AspNetCore.InternalTesting.HttpClientSlim.GetSocket(Uri requestUri) in /_/src/Testing/src/HttpClientSlim.cs:line 193
   at Microsoft.AspNetCore.InternalTesting.HttpClientSlim.GetStream(Uri requestUri, Boolean validateCertificate) in /_/src/Testing/src/HttpClientSlim.cs:line 156
   at Microsoft.AspNetCore.InternalTesting.HttpClientSlim.<>c__DisplayClass1_0.<<GetStringAsync>b__0>d.MoveNext() in /_/src/Testing/src/HttpClientSlim.cs:line 33
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.InternalTesting.HttpClientSlim.RetryRequest(Func`1 retryBlock) in /_/src/Testing/src/HttpClientSlim.cs:line 121
   at Microsoft.AspNetCore.InternalTesting.HttpClientSlim.GetStringAsync(Uri requestUri, Boolean validateCertificate) in /_/src/Testing/src/HttpClientSlim.cs:line 31
   at Microsoft.AspNetCore.InternalTesting.HttpClientSlim.GetStringAsync(String requestUri, Boolean validateCertificate) in /_/src/Testing/src/HttpClientSlim.cs:line 26
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterAddresses_Success(String addressInput, String[] testUrls, Int32 testPort) in /_/src/Servers/Kestrel/test/BindTests/AddressRegistrationTests.cs:line 205
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterAddresses_HostName_Success() in /_/src/Servers/Kestrel/test/BindTests/AddressRegistrationTests.cs:line 42
--- End of stack trace from previous location ---
```

**Comment by amcasey** [comment]
```
Starting:    Sockets.BindTests (parallel test collections = on [unlimited threads], stop on fail = off)
  Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterAddresses_HostName_Success [FAIL]
    System.Net.Sockets.SocketException : Name does not resolve
    Stack Trace:
      /_/src/Testing/src/HttpClientSlim.cs(193,0): at Microsoft.AspNetCore.InternalTesting.HttpClientSlim.GetSocket(Uri requestUri)
      /_/src/Testing/src/HttpClientSlim.cs(156,0): at Microsoft.AspNetCore.InternalTesting.HttpClientSlim.GetStream(Uri requestUri, Boolean validateCertificate)
      /_/src/Testing/src/HttpClientSlim.cs(33,0): at Microsoft.AspNetCore.InternalTesting.HttpClientSlim.<>c__DisplayClass1_0.<<GetStringAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
      /_/src/Testing/src/HttpClientSlim.cs(121,0): at Microsoft.AspNetCore.InternalTesting.HttpClientSlim.RetryRequest(Func`1 retryBlock)
      /_/src/Testing/src/HttpClientSlim.cs(31,0): at Microsoft.AspNetCore.InternalTesting.HttpClientSlim.GetStringAsync(Uri requestUri, Boolean validateCertificate)
      /_/src/Testing/src/HttpClientSlim.cs(26,0): at Microsoft.AspNetCore.InternalTesting.HttpClientSlim.GetStringAsync(String requestUri, Boolean validateCertificate)
      /_/src/Servers/Kestrel/test/BindTests/AddressRegistrationTests.cs(205,0): at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterAddresses_Success(String addressInput, String[] testUrls, Int32 testPort)
      /_/src/Servers/Kestrel/test/BindTests/AddressRegistrationTests.cs(42,0): at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterAddresses_HostName_Success()
      --- End of stack trace from previous location ---
    Output:
      | [0.010s] TestLifetime Information: Starting test RegisterAddresses_HostName_Success at 2024-08-29T07:00:26
      | [0.124s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting starting
      | [0.183s] Microsoft.Hosting.Lifetime Information: Now listening on: http://[::]:37673
      | [0.186s] Microsoft.AspNetCore.Hosting.Diagnostics Debug: Loaded hosting startup assembly Sockets.BindTests
      | [0.186s] Microsoft.Hosting.Lifetime Information: Application started. Press Ctrl+C to shut down.
      | [0.186s] Microsoft.Hosting.Lifetime Information: Hosting environment: Production
      | [0.186s] Microsoft.Hosting.Lifetime Information: Content root path: /root/helix/work/workitem/e/
      | [0.187s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting started
      | [1.304s] Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests Error: Test threw an exception.
      | System.Net.Sockets.SocketException (0xFFFDFFFF): Name does not resolve
      |    at Microsoft.AspNetCore.InternalTesting.HttpClientSlim.GetSocket(Uri requestUri) in /_/src/Testing/src/HttpClientSlim.cs:line 193
      |    at Microsoft.AspNetCore.InternalTesting.HttpClientSlim.GetStream(Uri requestUri, Boolean validateCertificate) in /_/src/Testing/src/HttpClientSlim.cs:line 156
      |    at Microsoft.AspNetCore.InternalTesting.HttpClientSlim.<>c__DisplayClass1_0.<<GetStringAsync>b__0>d.MoveNext() in /_/src/Testing/src/HttpClientSlim.cs:line 33
      | --- End of stack trace from previous location ---
      |    at Microsoft.AspNetCore.InternalTesting.HttpClientSlim.RetryRequest(Func`1 retryBlock) in /_/src/Testing/src/HttpClientSlim.cs:line 121
      |    at Microsoft.AspNetCore.InternalTesting.HttpClientSlim.GetStringAsync(Uri requestUri, Boolean validateCertificate) in /_/src/Testing/src/HttpClientSlim.cs:line 31
      |    at Microsoft.AspNetCore.InternalTesting.HttpClientSlim.GetStringAsync(String requestUri, Boolean validateCertificate) in /_/src/Testing/src/HttpClientSlim.cs:line 26
      |    at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterAddresses_Success(String addressInput, String[] testUrls, Int32 testPort) in /_/src/Servers/Kestrel/test/BindTests/AddressRegistrationTests.cs:line 205
      |    at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.RegisterAddresses_HostName_Success() in /_/src/Servers/Kestrel/test/BindTests/AddressRegistrationTests.cs:line 42
      |    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 253
      | --- End of stack trace from previous location ---
      |    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
      |    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
      | [1.315s] TestLifetime Information: Finished test RegisterAddresses_HostName_Success in 1.307886s
  Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.ListenAnyIP_HostName_Success [FAIL]
    System.Net.Sockets.SocketException : Name does not resolve
    Stack Trace:
      /_/src/Testing/src/HttpClientSlim.cs(193,0): at Microsoft.AspNetCore.InternalTesting.HttpClientSlim.GetSocket(Uri requestUri)
      /_/src/Testing/src/HttpClientSlim.cs(156,0): at Microsoft.AspNetCore.InternalTesting.HttpClientSlim.GetStream(Uri requestUri, Boolean validateCertificate)
      /_/src/Testing/src/HttpClientSlim.cs(33,0): at Microsoft.AspNetCore.InternalTesting.HttpClientSlim.<>c__DisplayClass1_0.<<GetStringAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
      /_/src/Testing/src/HttpClientSlim.cs(121,0): at Microsoft.AspNetCore.InternalTesting.HttpClientSlim.RetryRequest(Func`1 retryBlock)
      /_/src/Testing/src/HttpClientSlim.cs(31,0): at Microsoft.AspNetCore.InternalTesting.HttpClientSlim.GetStringAsync(Uri requestUri, Boolean validateCertificate)
      /_/src/Testing/src/HttpClientSlim.cs(26,0): at Microsoft.AspNetCore.InternalTesting.HttpClientSlim.GetStringAsync(String requestUri, Boolean validateCertificate)
      /_/src/Servers/Kestrel/test/BindTests/AddressRegistrationTests.cs(388,0): at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.ListenAnyIP_Success(String[] testUrls, Int32 testPort)
      /_/src/Servers/Kestrel/test/BindTests/AddressRegistrationTests.cs(365,0): at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.ListenAnyIP_HostName_Success()
      --- End of stack trace from previous location ---
    Output:
      | [0.001s] TestLifetime Information: Starting test ListenAnyIP_HostName_Success at 2024-08-29T07:00:28
      | [0.008s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting starting
      | [0.030s] Microsoft.Hosting.Lifetime Information: Now listening on: http://[::]:34759
      | [0.030s] Microsoft.AspNetCore.Hosting.Diagnostics Debug: Loaded hosting startup assembly Sockets.BindTests
      | [0.030s] Microsoft.Hosting.Lifetime Information: Application started. Press Ctrl+C to shut down.
      | [0.030s] Microsoft.Hosting.Lifetime Information: Hosting environment: Production
      | [0.031s] Microsoft.Hosting.Lifetime Information: Content root path: /root/helix/work/workitem/e/
      | [0.031s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting started
      | [0.070s] Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests Error: Test threw an exception.
      | System.Net.Sockets.SocketException (0xFFFDFFFF): Name does not resolve
      |    at Microsoft.AspNetCore.InternalTesting.HttpClientSlim.GetSocket(Uri requestUri) in /_/src/Testing/src/HttpClientSlim.cs:line 193
      |    at Microsoft.AspNetCore.InternalTesting.HttpClientSlim.GetStream(Uri requestUri, Boolean validateCertificate) in /_/src/Testing/src/HttpClientSlim.cs:line 156
      |    at Microsoft.AspNetCore.InternalTesting.HttpClientSlim.<>c__DisplayClass1_0.<<GetStringAsync>b__0>d.MoveNext() in /_/src/Testing/src/HttpClientSlim.cs:line 33
      | --- End of stack trace from previous location ---
      |    at Microsoft.AspNetCore.InternalTesting.HttpClientSlim.RetryRequest(Func`1 retryBlock) in /_/src/Testing/src/HttpClientSlim.cs:line 121
      |    at Microsoft.AspNetCore.InternalTesting.HttpClientSlim.GetStringAsync(Uri requestUri, Boolean validateCertificate) in /_/src/Testing/src/HttpClientSlim.cs:line 31
      |    at Microsoft.AspNetCore.InternalTesting.HttpClientSlim.GetStringAsync(String requestUri, Boolean validateCertificate) in /_/src/Testing/src/HttpClientSlim.cs:line 26
      |    at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.ListenAnyIP_Success(String[] testUrls, Int32 testPort) in /_/src/Servers/Kestrel/test/BindTests/AddressRegistrationTests.cs:line 388
      |    at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.AddressRegistrationTests.ListenAnyIP_HostName_Success() in /_/src/Servers/Kestrel/test/BindTests/AddressRegistrationTests.cs:line 365
      |    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 253
      | --- End of stack trace from previous location ---
      |    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
      |    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
      | [0.077s] TestLifetime Information: Finished test ListenAnyIP_HostName_Success in 0.076552s
Finished:    Sockets.BindTests
```

**Comment by amcasey** [comment]
Test run was at https://github.com/dotnet/aspnetcore/commit/258f8baa683db26ea46a00618a8b9b4d8db764b4

**Comment by amcasey** [comment]
I'm having trouble confirming that this error is exclusive to name resolution (as the text suggests), but I am seeing a different message when the port is wrong: `Connection refused`.  Since Kestrel doesn't control name resolution, it seems like this has to be flakiness.  My two foremost hypotheses are

1. Maybe parsing of the request URL back into host and port fails for some lab machine names and the name really doesn't resolve.  It's not clear how `HostNameIsReachableAttribute` could be letting the test run in that case, but it's not perfectly analogous to the real code path.
2. Maybe DNS lookup is flaky on posix (seems like this would be well-known?).

**Comment by amcasey** [comment]
The error appears to be [Error_EHOSTNOTFOUND](https://github.com/dotnet/runtime/blob/9eef7761e814895fa87c66eed1f364d7f11fe987/src/native/libs/Common/pal_error_common.h#L120).
