### ISSUE TITLE
CachesResourcesAfterFirstLoad test failure

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#27374]
```
Microsoft.AspNetCore.Components.E2ETest.Tests.BootResourceCachingTest.CachesResourcesAfterFirstLoad [FAIL]
      OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.NotEmptyException: Assert.NotEmpty() Failure
         at Xunit.Assert.NotEmpty(IEnumerable collection) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 331
         at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<Exists>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 72
         at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 109
      Screen shot captured at 'F:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.AspNetCore.Components.E2ETests\c557b8bab2944b9686fd5820662d0cc0.png'
      Page content:
      <head>
          <meta charset="utf-8">
          <title>Sample Blazor app</title>
      </head>
      <body>
          <app>Loading...</app>
          <script src="customJsFileForTests.js"></script>
          <script src="_framework/blazor.webassembly.js" autostart="false"></script>
      
          <!--
              To show we can customize the boot resource loading process, the server looks for these
              flags when collecting logs, and E2E tests check the right entries were seen.
           -->
          <script>
              Blazor.start({
                  loadBootResource: function (type, name, defaultUri, integrity) {
                      return type === 'dotnetjs'
                          ? `${defaultUri}?customizedbootresource=true`
                          : fetch(defaultUri, { integrity: integrity, cache: 'no-cache', headers: { 'customizedbootresource': 'true' } });
                  }
              });
          </script>
      
      
      <script type="text/javascript">var Module; window.__wasmmodulecallback__(); delete window.__wasmmodulecallback__;</script><script src="http://127.0.0.1:53305/_framework/dotnet.6.0.0-alpha.1.20513.9.js?customizedbootresource=true" defer="" integrity="sha256-yAadXUWmiL5QveCjn/zwyiGKbQEbhFrWfJ5FYfDuVZc=" crossorigin="anonymous"></script></body>
      
      ---- Assert.NotEmpty() Failure
      Stack Trace:
        /_/src/Shared/E2ETesting/WaitAssert.cs(129,0): at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout)
        /_/src/Shared/E2ETesting/WaitAssert.cs(67,0): at Microsoft.AspNetCore.E2ETesting.WaitAssert.Exists(IWebDriver driver, By finder, TimeSpan timeout)
        /_/src/Components/test/E2ETest/Tests/BootResourceCachingTest.cs(151,0): at Microsoft.AspNetCore.Components.E2ETest.Tests.BootResourceCachingTest.WaitUntilLoaded()
        /_/src/Components/test/E2ETest/Tests/BootResourceCachingTest.cs(47,0): at Microsoft.AspNetCore.Components.E2ETest.Tests.BootResourceCachingTest.CachesResourcesAfterFirstLoad()
        ----- Inner Stack Trace -----
        /_/src/Shared/E2ETesting/WaitAssert.cs(72,0): at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<Exists>b__0()
        /_/src/Shared/E2ETesting/WaitAssert.cs(109,0): at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _)
```

**Comment by SteveSandersonMS** [comment]
Have made yet another attempt to fix this (https://github.com/dotnet/aspnetcore/pull/30395), so bumping it forwards to preview 3 for verification and possible unquarantining then.

**Comment by SteveSandersonMS** [comment]
@mkArtakMSFT Hopefully will be closed with https://github.com/dotnet/aspnetcore/pull/31154

**Comment by SteveSandersonMS** [comment]
Unquarantined in https://github.com/dotnet/aspnetcore/pull/31154
