### ISSUE TITLE
ShutdownTestWaitForShutdown test failure

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#27371]
Linux only test

```
Assert.Equal() Failure\nExpected: 0\nActual:   143
   at Microsoft.AspNetCore.Hosting.FunctionalTests.ShutdownTests.WaitForExitOrKill(Process process) in /_/src/Hosting/test/FunctionalTests/ShutdownTests.cs:line 149
   at Microsoft.AspNetCore.Hosting.FunctionalTests.ShutdownTests.ExecuteShutdownTest(String testName, String shutdownMechanic) in /_/src/Hosting/test/FunctionalTests/ShutdownTests.cs:line 109
   at Microsoft.AspNetCore.Hosting.FunctionalTests.ShutdownTests.ShutdownTestWaitForShutdown() in /_/src/Hosting/test/FunctionalTests/ShutdownTests.cs:line 43
--- End of stack trace from previous location ---
```

**Comment by HaoK** [comment]
Note: this test isn't running on helix so we have no way to track failure rate

**Comment by BrennanConroy** [comment]
We upload test results from non-helix tests to AzDo same as Helix so the test pass rate is tracked in the same location as Helix tests
![image](https://user-images.githubusercontent.com/7574801/150402728-0ccf2ca4-dc98-4b23-aa27-2df9403aa3ec.png)

**Comment by HaoK** [comment]
Ah okay, its just not grouped the same way so it is hard to find

**Comment by amcasey** [comment]
I'm not sure where to see results for this particular test, but `Microsoft.AspNetCore.Hosting.Tests--net9.0 Work Item` has been passing for 30 days.

**Comment by amcasey** [comment]
Found it.  Hasn't failed in 30 days:
![image](https://github.com/user-attachments/assets/fc67f329-3618-424b-a315-ef05b4982abe)
