### ISSUE TITLE
RequestBody_SyncReadDisabledByDefault_WorksWhenEnabled test failure

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#27399]
```
[xUnit.net 00:00:11.91]     Microsoft.AspNetCore.Server.HttpSys.Listener.RequestBodyTests.RequestBody_SyncReadDisabledByDefault_WorksWhenEnabled [FAIL]
[xUnit.net 00:00:11.91]       System.Threading.Tasks.TaskCanceledException : The request was canceled due to the configured HttpClient.Timeout of 10 seconds elapsing.
[xUnit.net 00:00:11.91]       ---- System.TimeoutException : A task was canceled.
[xUnit.net 00:00:11.91]       -------- System.Threading.Tasks.TaskCanceledException : A task was canceled.
[xUnit.net 00:00:11.91]       Stack Trace:
[xUnit.net 00:00:11.92]            at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, Int64 timeoutTime)
[xUnit.net 00:00:11.92]            at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, CancellationTokenSource cts, Boolean disposeCts, Int64 timeoutTime, CancellationToken originalCancellationToken)
[xUnit.net 00:00:11.92]         /_/src/Servers/HttpSys/test/FunctionalTests/Listener/RequestBodyTests.cs(207,0): at Microsoft.AspNetCore.Server.HttpSys.Listener.RequestBodyTests.SendRequestAsync(String uri, HttpContent content)
[xUnit.net 00:00:11.92]         /_/src/Servers/HttpSys/test/FunctionalTests/Listener/Utilities.cs(141,0): at Microsoft.AspNetCore.Server.HttpSys.Listener.Utilities.Before[T](Task`1 acceptTask, Task`1 responseTask)
[xUnit.net 00:00:11.92]         /_/src/Servers/HttpSys/test/FunctionalTests/Listener/RequestBodyTests.cs(30,0): at Microsoft.AspNetCore.Server.HttpSys.Listener.RequestBodyTests.RequestBody_SyncReadDisabledByDefault_WorksWhenEnabled()
[xUnit.net 00:00:11.92]         --- End of stack trace from previous location ---
[xUnit.net 00:00:11.92]         ----- Inner Stack Trace -----
[xUnit.net 00:00:11.92]         
[xUnit.net 00:00:11.92]         ----- Inner Stack Trace -----
[xUnit.net 00:00:11.92]            at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[xUnit.net 00:00:11.92]            at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
[xUnit.net 00:00:11.92]            at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[xUnit.net 00:00:11.92]            at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, CancellationTokenSource cts, Boolean disposeCts, Int64 timeoutTime, CancellationToken originalCancellationToken)
```

**Comment by HaoK** [comment]
https://github.com/dotnet/aspnetcore/pull/39659
