### ISSUE TITLE
InputEvent_RespondsOnKeystrokes test failure

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#27397]
```
Microsoft.AspNetCore.Components.E2ETest.Tests.EventTest.InputEvent_RespondsOnKeystrokes [FAIL]
      OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.NotEmptyException: Assert.NotEmpty() Failure
         at Xunit.Assert.NotEmpty(IEnumerable collection) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 331
         at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<Exists>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 72
         at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 109
      Screen shot captured at 'F:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.AspNetCore.Components.E2ETests\3685e73c9df9487a99364936cb6df36f.png'
      Page content:
      <head>
          <meta charset="utf-8">
          <title>Basic test app</title>
          <base href="/subdir/">
          <link href="style.css" rel="stylesheet">
          <link rel="icon" href="data:,">
      
          <!-- Used by ExternalContentPackage -->
          <link href="_content/TestContentPackage/styles.css" rel="stylesheet">
      
          <!-- App bundle that contains a reference to the scoped css bundle created by TestContentPackage -->
          <link href="BasicTestApp.styles.css" rel="stylesheet">
      </head>
      
      <body>
          <root>Loading...</root>
      
          <!-- Explicit display:none required so StartupErrorNotificationTest can observe it change -->
          <div id="blazor-error-ui" style="display: none;">
              An unhandled error has occurred.
              <a href="" class="reload">Reload</a>
              <a class="dismiss" style="cursor: pointer;">??</a>
          </div>
      
          <!-- Used for specific test cases -->
          <script src="js/seleniumworkaround.js"></script>
          <script src="js/jsinteroptests.js"></script>
          <script src="js/renderattributestest.js"></script>
          <script src="js/webComponentPerformingJsInterop.js"></script>
      
          <script>
              // Used by ElementRefComponent
              function setElementValue(element, newValue) {
                  element.value = newValue;
                  return element.value;
              }
      
              function navigationManagerNavigate() {
                  Blazor.navigateTo('/subdir/some-path');
              }
      
              function getCurrentUrl() {
                  return location.href;
              }
          </script>
          <script src="_framework/blazor.webassembly.js"></script>
      
          <script src="_content/Microsoft.AspNetCore.Components.Web.Extensions/headManager.js"></script>
      
          <!-- Used by ExternalContentPackage -->
          <script src="_content/TestContentPackage/prompt.js"></script>
      
      
      
      <script type="text/javascript">var Module; window.__wasmmodulecallback__(); delete window.__wasmmodulecallback__;</script><script src="_framework/dotnet.6.0.0-alpha.1.20468.7.js" defer="" integrity="sha256-VXwIh6nczBDI+UPb+gdp64GkUP5qSz86FUs8Xhsc92E=" crossorigin="anonymous"></script></body>
      
      ---- Assert.NotEmpty() Failure
      Stack Trace:
        /_/src/Shared/E2ETesting/WaitAssert.cs(139,0): at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout)
        /_/src/Shared/E2ETesting/WaitAssert.cs(67,0): at Microsoft.AspNetCore.E2ETesting.WaitAssert.Exists(IWebDriver driver, By finder, TimeSpan timeout)
        /_/src/Components/test/E2ETest/Infrastructure/WebDriverExtensions/BasicTestAppWebDriverExtensions.cs(24,0): at Microsoft.AspNetCore.Components.E2ETest.BasicTestAppWebDriverExtensions.WaitUntilTestSelectorReady(IWebDriver browser)
        /_/src/Components/test/E2ETest/Infrastructure/WebDriverExtensions/BasicTestAppWebDriverExtensions.cs(18,0): at Microsoft.AspNetCore.Components.E2ETest.BasicTestAppWebDriverExtensions.MountTestComponent[TComponent](IWebDriver browser)
        /_/src/Components/test/E2ETest/Tests/EventTest.cs(29,0): at Microsoft.AspNetCore.Components.E2ETest.Tests.EventTest.InitializeAsyncCore()
        /_/src/Shared/E2ETesting/BrowserTestBase.cs(71,0): at Microsoft.AspNetCore.E2ETesting.BrowserTestBase.InitializeAsync(String isolationContext)
        ----- Inner Stack Trace -----
        /_/src/Shared/E2ETesting/WaitAssert.cs(72,0): at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<Exists>b__0()
        /_/src/Shared/E2ETesting/WaitAssert.cs(109,0): at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _)
```

**Comment by pranavkm** [comment]
Closing in favor of https://github.com/dotnet/aspnetcore/issues/31195.
