### ISSUE TITLE
ReaderThrowsResetExceptionOnInvalidBody test failure

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#27400]
There was a failure on 10/2 but logs are gone now, managed to get the error though. We also might want to look at how we make sure this is running. There was a gap from 10/10 - 10/26 where this wasn't running.

```
System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
---- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Testing/src/TaskExtensions.cs:line 31
   at Microsoft.AspNetCore.Server.IntegrationTesting.TestConnection.Receive(Int32 length) in F:\workspace\_work\1\s\src\Servers\IIS\IIS\test\testassets\IIS.Common.TestLib\TestConnections.cs:line 136
   at Microsoft.AspNetCore.Server.IntegrationTesting.TestConnection.Receive(String[] lines) in F:\workspace\_work\1\s\src\Servers\IIS\IIS\test\testassets\IIS.Common.TestLib\TestConnections.cs:line 117
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.ClientDisconnectTests.ReaderThrowsResetExceptionOnInvalidBody() in /_/src/Servers/IIS/IIS/test/IIS.Tests/ClientDisconnectTests.cs:line 266
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
```

**Comment by adityamandaleeka** [comment]
@BrennanConroy/@HaoK I think this test is running fine as far back as the history goes. Should it be unquarantined?

**Comment by BrennanConroy** [comment]
I see a failure on 7/30 https://dev.azure.com/dnceng/public/_build/results?buildId=1269091&view=ms.vss-test-web.build-test-results-tab&runId=37557220&paneView=debug&resultId=100059
But at least now we have logs:

<details>
<summary>Logs</summary>

```
[0.022s] [TestLifetime] [Information] Starting test ReaderThrowsResetExceptionOnInvalidBody at 2021-07-30T20:37:12
[2.866s] [Microsoft.AspNetCore.Server.IIS.FunctionalTests.TestServer] [Debug] Method: GET, RequestUri: 'http://localhost:60220/start', Version: 1.1, Content: <null>, Headers:
{
}
[2.872s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting starting
[2.873s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Debug] Loaded hosting startup assembly IIS.Tests
[2.873s] [Microsoft.Hosting.Lifetime] [Information] Application started. Press Ctrl+C to shut down.
[2.873s] [Microsoft.Hosting.Lifetime] [Information] Hosting environment: Production
[2.873s] [Microsoft.Hosting.Lifetime] [Information] Content root path: C:\h\w\AE94094C\w\A73E091C\e\.
[2.873s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting started
[2.873s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request starting HTTP/1.1 GET http://localhost:60220/start - -
[2.874s] [Microsoft.AspNetCore.Server.IIS.FunctionalTests.TestServer] [Debug] StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Transfer-Encoding: chunked
  Server: Microsoft-IIS/10.0
  Date: Fri, 30 Jul 2021 20:37:15 GMT
}
[2.885s] [Microsoft.AspNetCore.Server.IIS.FunctionalTests.TestServer] [Debug] Done
[2.887s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request finished HTTP/1.1 GET http://localhost:60220/start - - - 200 - - 11.7330ms
[2.899s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request starting HTTP/1.1 POST http://localhost/ - -
[2.913s] [Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer] [Debug] Connection ID "18158513699168452618" disconnecting.
[2.913s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request finished HTTP/1.1 POST http://localhost/ - - - 0 - - 14.1206ms
[3.024s] [Microsoft.Hosting.Lifetime] [Information] Application is shutting down...
[5.287s] [Microsoft.AspNetCore.Server.IIS.FunctionalTests.ClientDisconnectTests] [Error] Test threw an exception.
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) in System.Net.Sockets.dll:token 0x6000294+0x10
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token) in System.Net.Sockets.dll:token 0x600028d+0x2d
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state) in System.Private.CoreLib.dll:token 0x600349d+0x23
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 90
   at Microsoft.AspNetCore.Server.IntegrationTesting.TestConnection.Receive(Int32 length) in D:\workspace\_work\1\s\src\Servers\IIS\IIS\test\testassets\IIS.Common.TestLib\TestConnections.cs:line 137
   at Microsoft.AspNetCore.Server.IntegrationTesting.TestConnection.Receive(String[] lines) in D:\workspace\_work\1\s\src\Servers\IIS\IIS\test\testassets\IIS.Common.TestLib\TestConnections.cs:line 118
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.ClientDisconnectTests.ReaderThrowsResetExceptionOnInvalidBody() in /_/src/Servers/IIS/IIS/test/IIS.Tests/ClientDisconnectTests.cs:line 265
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
[5.289s] [TestLifetime] [Information] Finished test ReaderThrowsResetExceptionOnInvalidBody in 5.2814322s
```

</details>

**Comment by HaoK** [comment]
Yeah I just saw that too

![image](https://user-images.githubusercontent.com/6537861/128962837-a650559d-9d90-4d86-aeb5-343d1d4d0e46.png)

**Comment by adityamandaleeka** [comment]
heh, I was looking at aspnetcore-quarantined-tests instead of aspnetcore-quarantined-pr.

**Comment by HaoK** [comment]
This one seems like a decent one to consider unquarantinine tho: https://github.com/dotnet/aspnetcore/issues/25542 as its passed 1000+ times in a month and it was disabled almost a year ago

![image](https://user-images.githubusercontent.com/6537861/128982371-4c077132-50cd-42be-807b-3dbbb48c1674.png)

**Comment by HaoK** [comment]
Note: this is 30 days clean again, maybe we should just add it to the retry list

**Comment by HaoK** [comment]
https://github.com/dotnet/aspnetcore/pull/39659
