### ISSUE TITLE
Signalr - Runtime Exception : The HubConnection failed to transition from the 'CONNECTED' state to the 'DISCONNECTED' state because it was actually in the 'CONNECTING' state.

### ISSUE THREAD

**Issue by hakansuluoglu** [dotnet/aspnetcore#27438]
Hi,

I'm using signalr java client for an android project. 
I get the following error in the crashlytics logs. I cannot reproduce this issue :( 

I try to start HubConnection in every activity onStart (Code is below). If Hub connection is connected or connecting state I do not start connection again. 

There is only one way to get this error.

- At the end of the HubConnection.stopConnection, changeState() is called; 
`this.state.changeState(HubConnectionState.CONNECTED, HubConnectionState.DISCONNECTED);`
- And changeState() throws RuntimeException because the previously unfinished process' state is Connecting. 

I'm new to signalr and I did not understand the problem. If this exception expected, How can I prevent the application from crashing?

### Exception
```
Fatal Exception: java.lang.RuntimeException: The HubConnection failed to transition from the 'CONNECTED' state to the 'DISCONNECTED' state because it was actually in the 'CONNECTING' state.
       at com.microsoft.signalr.HubConnection$ReconnectingConnectionState.changeState(HubConnection.java:1512)
       at com.microsoft.signalr.HubConnection.stopConnection(HubConnection.java:538)
       at com.microsoft.signalr.HubConnection.lambda$start$6(HubConnection.java:279). 
       at com.microsoft.signalr.-$$Lambda$HubConnection$plWe2n559m5117SGBt0gopoPs3g.invoke(-.java:2)
       at com.microsoft.signalr.WebSocketTransport.onClose(WebSocketTransport.java:92)
       at com.microsoft.signalr.WebSocketTransport.lambda$start$1(WebSocketTransport.java:55)
       at com.microsoft.signalr.-$$Lambda$WebSocketTransport$vlt_DXG3u2t5OJvAYlxBdjX-Br4.invoke(-.java:2)
       at com.microsoft.signalr.OkHttpWebSocketWrapper$SignalRWebSocketListener.onFailure(OkHttpWebSocketWrapper.java:124)
       at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:592)
       at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.java:174)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java:519)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:784)
```

### start()
```
public void start() {
    if (hubConnection != null &&
            (hubConnection.getConnectionState() == HubConnectionState.CONNECTED || 
                    hubConnection.getConnectionState() == HubConnectionState.CONNECTING)) {
        return;
    }

    hubConnection = HubConnectionBuilder.create(WEB_SOCKET_URL)
            .withTransport(TransportEnum.WEBSOCKETS)
            .withHandshakeResponseTimeout(10000)
            .withAccessTokenProvider(Single.defer(() -> Single.just(token))).build();

    hubConnection.setServerTimeout(10000);

    hubConnection.onClosed(exception -> Log.w("Socket" , "Connection Closed: "));

    hubConnection.start()
            .subscribeOn(Schedulers.io())
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe(new DisposableCompletableObserver() {
                @Override
                public void onComplete() {
                    Log.i("Socket" , "Connection Started");
                }

                @Override
                public void onError(Throwable e) {
                    Log.w("Socket" , "Connection Start Error");
                }
            });
}
```

- **library : com.microsoft.signalr:signalr:5.0.0-rc.2.20475.17**

**Comment by dsuresh-ap** [comment]
I was able to reproduce this as well by setting up a breakpoint in Charles Proxy and aborting the WSS connection. The app later crashes.

**Comment by BrennanConroy** [comment]
Done via https://github.com/dotnet/aspnetcore/pull/28004
