### ISSUE TITLE
Blazor Web Assembly call Azure Function crashes .Net 5.0 rc2

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#27496]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Blazor-Web-Assembly-call-Azure-Function-/1232255?preview=true)._

---
[severity:I'm unable to use this version of Visual Studio] [regression] [worked-in:.Net 5.0 rc2]
I recreated this in a very simple pair of projects.  Project 1 is a Blazor WebAssembly project.  Project 2 is an Azure Function project.  Only change to Blazor project was to setup CORS and add code to all Azure Function.  Just go to the Fetch data page and the error will happen.  The Browser window will crash in the Web Assembly code.  Look at the F12 debugger on the console.  See BlazorCrash.zip for project files.  This seems to happen all calling to Functions.  This used to work at I am blocked from using rc2 because of this.

Uncaught (in promise) RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
    at abort (https://localhost:44358/_framework/dotnet.5.0.0-rc.2.20475.5.js:1:14903)
    at _abort (https://localhost:44358/_framework/dotnet.5.0.0-rc.2.20475.5.js:1:105666)
    at stub_debugger_agent_user_break (<anonymous>:wasm-function[6500]:0xf94a6)
    at do_debugger_tramp (<anonymous>:wasm-function[3306]:0x79e23)
    at interp_exec_method (<anonymous>:wasm-function[2155]:0x442e1)
    at interp_runtime_invoke (<anonymous>:wasm-function[7859]:0x12ef59)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[7344]:0x118db9)
    at do_runtime_invoke (<anonymous>:wasm-function[3304]:0x79d37)
    at mono_runtime_try_invoke (<anonymous>:wasm-function[629]:0x12977)
    at mono_runtime_invoke (<anonymous>:wasm-function[7115]:0x10eb85)
abort @ dotnet.5.0.0-rc.2.20475.5.js:1
_abort @ dotnet.5.0.0-rc.2.20475.5.js:1
stub_debugger_agent_user_break @ 00ab9d9a:0xf94a6
do_debugger_tramp @ 00ab9d9a:0x79e23
interp_exec_method @ 00ab9d9a:0x442e1
interp_runtime_invoke @ 00ab9d9a:0x12ef59
mono_jit_runtime_invoke @ 00ab9d9a:0x118db9
do_runtime_invoke @ 00ab9d9a:0x79d37
mono_runtime_try_invoke @ 00ab9d9a:0x12977
mono_runtime_invoke @ 00ab9d9a:0x10eb85
mono_wasm_invoke_method @ 00ab9d9a:0x108e03
Module._mono_wasm_invoke_method @ dotnet.5.0.0-rc.2.20475.5.js:1
call_method @ dotnet.5.0.0-rc.2.20475.5.js:1
set_task_result @ dotnet.5.0.0-rc.2.20475.5.js:1
(anonymous) @ dotnet.5.0.0-rc.2.20475.5.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.5.0.0-rc.2.20475.5.js:1
mono_wasm_convert_return_value @ dotnet.5.0.0-rc.2.20475.5.js:1
_mono_wasm_invoke_js_with_args @ dotnet.5.0.0-rc.2.20475.5.js:1
do_icall @ 00ab9d9a:0x194d3f
do_icall_wrapper @ 00ab9d9a:0x79dee
interp_exec_method @ 00ab9d9a:0x44ac8
interp_runtime_invoke @ 00ab9d9a:0x12ef59
mono_jit_runtime_invoke @ 00ab9d9a:0x118db9
do_runtime_invoke @ 00ab9d9a:0x79d37
mono_runtime_try_invoke @ 00ab9d9a:0x12977
mono_runtime_invoke @ 00ab9d9a:0x10eb85
mono_wasm_invoke_method @ 00ab9d9a:0x108e03
Module._mono_wasm_invoke_method @ dotnet.5.0.0-rc.2.20475.5.js:1
call_method @ dotnet.5.0.0-rc.2.20475.5.js:1
set_task_result @ dotnet.5.0.0-rc.2.20475.5.js:1
(anonymous) @ dotnet.5.0.0-rc.2.20475.5.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.5.0.0-rc.2.20475.5.js:1
mono_wasm_convert_return_value @ dotnet.5.0.0-rc.2.20475.5.js:1
_mono_wasm_invoke_js_with_args @ dotnet.5.0.0-rc.2.20475.5.js:1
do_icall @ 00ab9d9a:0x194d3f
do_icall_wrapper @ 00ab9d9a:0x79dee
interp_exec_method @ 00ab9d9a:0x44ac8
interp_runtime_invoke @ 00ab9d9a:0x12ef59
mono_jit_runtime_invoke @ 00ab9d9a:0x118db9
do_runtime_invoke @ 00ab9d9a:0x79d37
mono_runtime_try_invoke @ 00ab9d9a:0x12977
mono_runtime_invoke @ 00ab9d9a:0x10eb85
mono_wasm_invoke_method @ 00ab9d9a:0x108e03
Module._mono_wasm_invoke_method @ dotnet.5.0.0-rc.2.20475.5.js:1
call_method @ dotnet.5.0.0-rc.2.20475.5.js:1
set_task_result @ dotnet.5.0.0-rc.2.20475.5.js:1
(anonymous) @ dotnet.5.0.0-rc.2.20475.5.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.5.0.0-rc.2.20475.5.js:1
mono_wasm_convert_return_value @ dotnet.5.0.0-rc.2.20475.5.js:1
_mono_wasm_invoke_js_with_args @ dotnet.5.0.0-rc.2.20475.5.js:1
do_icall @ 00ab9d9a:0x194d3f
do_icall_wrapper @ 00ab9d9a:0x79dee
interp_exec_method @ 00ab9d9a:0x44ac8
interp_runtime_invoke @ 00ab9d9a:0x12ef59
mono_jit_runtime_invoke @ 00ab9d9a:0x118db9
do_runtime_invoke @ 00ab9d9a:0x79d37
mono_runtime_try_invoke @ 00ab9d9a:0x12977
mono_runtime_invoke @ 00ab9d9a:0x10eb85
mono_wasm_invoke_method @ 00ab9d9a:0x108e03
Module._mono_wasm_invoke_method @ dotnet.5.0.0-rc.2.20475.5.js:1
call_method @ dotnet.5.0.0-rc.2.20475.5.js:1
set_task_result @ dotnet.5.0.0-rc.2.20475.5.js:1
(anonymous) @ dotnet.5.0.0-rc.2.20475.5.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.5.0.0-rc.2.20475.5.js:1
mono_wasm_convert_return_value @ dotnet.5.0.0-rc.2.20475.5.js:1
_mono_wasm_invoke_js_with_args @ dotnet.5.0.0-rc.2.20475.5.js:1
do_icall @ 00ab9d9a:0x194d3f
do_icall_wrapper @ 00ab9d9a:0x79dee
interp_exec_method @ 00ab9d9a:0x44ac8
interp_runtime_invoke @ 00ab9d9a:0x12ef59
mono_jit_runtime_invoke @ 00ab9d9a:0x118db9
do_runtime_invoke @ 00ab9d9a:0x79d37
mono_runtime_invoke_checked @ 00ab9d9a:0xf652
mono_runtime_try_invoke_array @ 00ab9d9a:0x10e78b
ves_icall_InternalInvoke @ 00ab9d9a:0xed487
ves_icall_InternalInvoke_raw @ 00ab9d9a:0xecf4c
do_icall @ 00ab9d9a:0x194d3f
do_icall_wrapper @ 00ab9d9a:0x79dee
interp_exec_method @ 00ab9d9a:0x44ac8
interp_runtime_invoke @ 00ab9d9a:0x12ef59
mono_jit_runtime_invoke @ 00ab9d9a:0x118db9
do_runtime_invoke @ 00ab9d9a:0x79d37
mono_runtime_try_invoke @ 00ab9d9a:0x12977
mono_runtime_invoke @ 00ab9d9a:0x10eb85
mono_wasm_invoke_method @ 00ab9d9a:0x108e03
Module._mono_wasm_invoke_method @ dotnet.5.0.0-rc.2.20475.5.js:1
call_method @ dotnet.5.0.0-rc.2.20475.5.js:1
(anonymous) @ dotnet.5.0.0-rc.2.20475.5.js:1
beginInvokeDotNetFromJS @ blazor.webassembly.js:1
h @ blazor.webassembly.js:1
e.invokeMethodAsync @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
r @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
r @ blazor.webassembly.js:1
d @ blazor.webassembly.js:1
f @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
e.onGlobalEvent @ blazor.webassembly.js:1
Show 44 more frames

---
#### Feedback Bot on 10/25/2020, 09:14 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Brett McDonald on 10/27/2020, 08:10 AM: 

<p>Is there any word on this?  This is a showstopper for me.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
I confirmed this to be an issue in 5.0.0.

I believe this affects CORS in general, and that the underlying cause is in the mono runtime. No matter whether the request mode was set to CORS on the request or not before being sent.

**Comment by mkArtakMSFT** [comment]
@javiercn should we move this to the `runtime` repo then? What's pending for that?

**Comment by javiercn** [comment]
Request and responses look fine

![image](https://user-images.githubusercontent.com/6995051/98023512-e996dc00-1dbb-11eb-8186-4f75b41998e7.png)

**Comment by javiercn** [comment]
There is a repro project in the associated feedback ticket
