### ISSUE TITLE
Windows 10 2016, LTSB support in .net core

### ISSUE THREAD

**Issue by MMWPF** [dotnet/aspnetcore#27536]
# Does .net core runtime supported in win 10 2016, LTSB?

I am trying to run aspnetcore grpc service and got IO exception. I was wondering if there is a limit on .net core os, windows 10 build number ?

**Comment by javiercn** [comment]
@MMWPF thanks for contacting us.

@JamesNK do you have thoughts here since this is "gRPC" based? I imagine there needs to be OS support for HTTP/2 if you are not self-hosting? (Kestrel)

**Comment by BrennanConroy** [comment]
How are you hosting? What errors are you getting? Can you share a repro?

**Comment by MMWPF** [comment]
> How are you hosting? What errors are you getting? Can you share a repro?

I am running it inside the console application.

I would like to state that I already know about possible problems with TLS and ALPN so I disable the TLS on the client-side and on the server-side.

This is the error that I am getting:

Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: An error occurred while sending the request. IOException: The response ended prematurely.", DebugException="System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> **System.IO.IOException: The response ended prematurely.**
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
   at ProtoBuf.Grpc.Internal.Reshape.UnaryTaskAsyncImpl[TRequest,TResponse](AsyncUnaryCall`1 call, MetadataContext metadata, CancellationToken cancellationToken) in /_/src/protobuf-net.Grpc/Internal/Reshape.cs:line 289
   at Camtek.RMS.Proxy.Clients.ToolsProxy.UpsertTool(MsgToolRequest request) in D:\VSTS\RMS-Dev\Camtek.RMS.Proxy\Clients\ToolsProxy.cs:line 22
   at Camtek.Rms.Service4Tool.RmsRegistrarService.StartAsync(CancellationToken cancellationToken) in D:\VSTS\RMS-Dev\Camtek.RMS.Service4Tool\Services\RmsRegistrarService.cs:line 63

**Comment by BrennanConroy** [comment]
Is the server running IIS or Kestrel?
Can you share your debug server logs?
Can you provide a repro app?

**Comment by MMWPF** [comment]
We downgrade the protocol to HTTP 1.1 and now it is working also in windows 10 2016 LTSB.
Enable in kestrel Http1Http2 instead of just Http2.

It seems that even though windows 10 2016 LTSB version number is 1607 (which should be enough according to documentation) it can't work with HTTP 2.
This is true for the enable & disable of authentication inside the protocol.

My recommendation is to add this limitation as part of the documentation if anyone else will try he will found out regarding this limitation.

Thanks for the help!
