### ISSUE TITLE
Unhandled exception after editing renamed Razor file

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#27620]
### Describe the bug
An unexpected error occurs after starting to type in a Razor page created after renaming a cshtml file.

### To Reproduce

1. Right-click and create a new *.cshtml in Visual Studio.
2. Rename the file to a `*.razor` extension.
3. Open the `*.razor` file.
4. Start typing some content and notice that you get a gold bar.

### Logs & Exceptions

Activity Log: https://gist.github.com/captainsafia/0946ba9998c417a7984903b5cfc165f4

### Further technical details
- VS version: Version 16.9.0 Preview 2.0 [30706.124.main]
- Scenario: Local

**Comment by NTaylorMullen** [comment]
The work here for 16.9-P3 is to talk to the CoreEditor team and notify them of the potential exception and work with them for a fix.

**Comment by NTaylorMullen** [comment]
Still happens. Latest debug assert I just captured (looks like semantic tokens):
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Failed to apply edit due to exception: Internal Error - System.ArgumentNullException: Value cannot be null.

Parameter name: documentSnapshot

   at Microsoft.AspNetCore.Razor.LanguageServer.DefaultDocumentVersionCache.TryGetDocumentVersion(DocumentSnapshot documentSnapshot, Nullable`1& version)

   at Microsoft.AspNetCore.Razor.LanguageServer.Semantic.DefaultRazorSemanticTokensInfoService.<>c__DisplayClass18_0.<TryGetDocumentInfoAsync>b__0()

   at System.Threading.Tasks.Task`1.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

   at Microsoft.AspNetCore.Razor.LanguageServer.Semantic.DefaultRazorSemanticTokensInfoService.<TryGetDocumentInfoAsync>d__18.MoveNext()

--- End of st......

<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by NTaylorMullen** [comment]
This ended up being external. Filed an issue on the language server platform: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1265759

**Comment by NTaylorMullen** [comment]
Platform fixed.
