### ISSUE TITLE
.NET FW 4.8 DataProtection ProtectKeysWithCertificate with a certificate not stored in the certificate store

### ISSUE THREAD

**Issue by archimed7592** [dotnet/aspnetcore#27690]
### Describe the bug
According to https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/compatibility/replacing-machinekey?view=aspnetcore-5.0 it is possible to use DataProtection in .NET FW projects.

Fix described in https://github.com/dotnet/aspnetcore/issues/2321 works for .NET Core applications, but won't work for .NET FW.

### To Reproduce

Create two console projects, one for .NET FW, one for .NET Core
Add NuGet reference to Microsoft.AspNetCore.DataProtection.Extensions
Place this code in Program.cs:
```
using System;
using System.IO;
using System.Security.Cryptography.X509Certificates;
using Microsoft.AspNetCore.DataProtection;

namespace ConsoleApp9
{
    class Program
    {
        static void Main(string[] args)
        {
            var dpp =
                DataProtectionProvider.Create(
                    keyDirectory:
                        new DirectoryInfo(
                            @"C:\tmp\DataProtectionTestKeyStore"),
                    setupAction:
                        cfg =>
                        {
                            cfg.ProtectKeysWithCertificate(
                                new X509Certificate2(
                                    fileName: @"C:\tmp\key.pfx",
                                    password: @"super-secret-password"));
                        });

            var dp = dpp.CreateProtector("test purpose");
            var secret = dp.Protect("test secret");
            Console.WriteLine(secret);
        }
    }
}
```

### Exceptions (if any)

```
Unhandled Exception: System.Security.Cryptography.CryptographicException: Unable to retrieve the decryption key.
   at System.Security.Cryptography.Xml.EncryptedXml.DecryptDocument()
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.EncryptedXmlDecryptor.Decrypt(XElement encryptedElement)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.XmlEncryptionExtensions.DecryptElement(XElement element, IActivator activator)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.DeserializeDescriptorFromKeyElement(XElement keyElement)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.DeferredKey.<>c__DisplayClass1_0.<GetLazyDescriptorDelegate>b__0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyBase.get_Descriptor()
   at Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.CngGcmAuthenticatedEncryptorFactory.CreateEncryptorInstance(IKey key)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyBase.CreateEncryptor()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRing.KeyHolder.GetEncryptorInstance(Boolean& isRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRing.get_DefaultAuthenticatedEncryptor()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Protect(IDataProtector protector, String plaintext)
   at ConsoleApp9.Program.Main(String[] args)
```

.NET Core App will print out protected secret, .NET FW App will throw an exception

### Further technical details
- ASP.NET Core version: tested in .NET Core 3.1 and 5.0 versus .NET FW 4.8

**Comment by blowdart** [comment]
You're not using the compat shim in your sample (and the compat shim is very limited anyway)

@bartonjs Any idea why the behaviour? It's all XML Encryption all the way down

**Comment by bartonjs** [comment]
Nope, as far as I know the two EncryptedXml classes should behave the same... we haven't taken any changes unique to System.Security.Cryptography.Xml since we introduced ported it in .NET Core 2.0 (there were global changes like using `nameof` for ArgumentException parameter name expressions), other than porting changes from .NET Framework (like adding some new consts for algorithm identifiers).

**Comment by archimed7592** [comment]
I've tried to debug this issue, but no luck.
Take a look at https://github.com/archimed7592/aspnetcore/commit/bbd9e92b81d663e23c30792b166013fd82e22013#r44094999
In current implementation .NET FW ConsoleApp3 won't event go into the DecryptEncryptedKey override.
I've copied GetDecryptionKey using Reflector and suddenly it goes into the original DecryptEncryptedKey override and works on .NET FW.
I've tried make dummy override of DecryptEncryptedKey redirecting to base DecryptEncryptedKey - same problem, it goes into dummy override, it won't go into DecryptEncryptedKey and throws.
I have no clue how can it be.

**Comment by archimed7592** [comment]
I've changed the implementation of GetDecryptionKey to the one from https://referencesource.microsoft.com/#System.Security/system/security/cryptography/xml/encryptedxml.cs,335 and behavior is the same, so we can rule out Reflector problems.

Is it possible that the problem is roslyn-shim-etc related?
I really have no idea how the same method can behave differently when it is overridden with exactly the same implementation as in the base class.

**Comment by archimed7592** [comment]
I figured it out... it was [CryptoPro.NET](https://www.cryptopro.ru/products/net) (Russian GOST crypto library). I think they somehow inject their code into .NET FW libraries.
I've uninstalled CryptoPro.NET and now it works both on .NET Core and .NET FW.
I'm closing this issue. For those who will bump into same problem, here is an issue on CryptoPro forum: [Модифицированный EncryptedXml - не корректно работает AspNetCore.DataProtection](https://www.cryptopro.ru/forum2/default.aspx?g=posts&m=120446)
