### ISSUE TITLE
HttpTransportType.WebSockets doesn't allow to send objects with SignalR with a size more than ~3 kilobytes

### ISSUE THREAD

**Issue by Antonystar** [dotnet/aspnetcore#27732]
This bug appeared after migrating to ASP.NET Core 5.0.
I guess it is connected only with SignalR Core functionality. I use SignalR Core in a Blazor WebAssembly App with an ASP.NET Core backend.
After trying to send a file (array of bytes) with a size exceeding ~3 kilobytes from a client HubConnection to a server HubConnection it shows next error at the serverside:

```
System.IO.InvalidDataException: Unexpected JSON Token Type 'String'. Expected a JSON Object.
   at Microsoft.AspNetCore.Internal.SystemTextJsonExtensions.EnsureObjectStart(Utf8JsonReader& reader)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.ParseMessage(ReadOnlySequence`1 input, IInvocationBinder binder)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.TryParseMessage(ReadOnlySequence`1& input, IInvocationBinder binder, HubMessage& message)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.DispatchMessagesAsync(HubConnectionContext connection)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.RunHubAsync(HubConnectionContext connection)
```

I resolved that changing client transport type to LongPolling solves the issue:
```
localHub = new HubConnectionBuilder()
        .WithUrl(NavigationManager.ToAbsoluteUri(Constants.MAIN_HUB_PATH), options => {
            options.Transports = HttpTransportType.LongPolling;
        })
```

**So I guess that currently HttpTransportType.WebSockets doesn't allow to send objects with SignalR with a size more than ~3 kilobytes**. It worked fine (ASP.NET Core 3.1) before migrating to 5.0.

I use ASP.NET core 5.0 and Visual Studio 19.

**Comment by BrennanConroy** [comment]
This will be tracked by https://github.com/dotnet/runtime/issues/44551
