### ISSUE TITLE
Blazor console error for published app refers to development file path

### ISSUE THREAD

**Issue by mrlife** [dotnet/aspnetcore#27748]
### Describe the bug
An exception in an app published to a test environment refers to a file location on my local development machine.

```
[Error] [2020-11-11T22:28:17.471Z] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at MyProject.Components.MyComponent.MyFunction() in /Users/mrlife/Documents/MyProject/Components/MyComponent.razor:line 102
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[T](MulticastDelegate delegate, T arg)
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
   at Microsoft.AspNetCore.Components.Forms.EditForm.HandleSubmitAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

### Further technical details
- ASP.NET Core version: 5.0
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version: VS Mac

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Can you share more about how you publish the app?
Please share a repro project with detailed steps we can investigate this further.

**Comment by mrlife** [comment]
@mkArtakMSFT Thank you. I do a FileSystem publish in Visual Studio for Mac to a Windows server.

Here is a project that has the issue. There is a publish profile that can be modified as needed. The published project runs as a Windows service. I'm sure you have your own way of publishing these repro projects....

To see the issue in the console, click the "Click me" button.

https://github.com/mrlife/ConsoleErrorTest

**Comment by mkArtakMSFT** [comment]
Thanks @mrlife.
In ASP.NET Core apps we publish PDB files too, which include paths. If you would like to disable PDB publishing add the following property in the project file:

```
<CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
```

Given that these errors show up on server, nobody should be able to see these. So it's up to you to decide whether you really want to disable it or not.

**Comment by mrlife** [comment]
@mkArtakMSFT Is there any reason to include PDB files in a published app?

> Given that these errors show up on server, nobody should be able to see these.

I'm seeing the error in the browser console, so not sure what you mean.
