### ISSUE TITLE
[Blazor WASM] System.IO.DirectoryNotFoundException Error

### ISSUE THREAD

**Issue by daniel-p-tech** [dotnet/aspnetcore#27823]
Hi,

I have just created a new .NET 5.0 Blazor project using default template in VS 16.8.1 - so everything is up-to-date.

The name of the project file is something like ``Company.Product.WebApp.csproj`` and the default namespace is ``Company.Product.WebApp``. 

However, I renamed the project folder hosting the Blazor app to ``WebApp`` in order to stay consistent with our company's naming conventions for large scale projects. This how the  folder structure looks like:

![image](https://user-images.githubusercontent.com/29497049/99106737-56735880-25aa-11eb-9578-f0dcd006945d.png)

When I run the project, I receive the exception listed below on the startup. How can I tell the framework to replace ``C:\Projects\XYZ\Product\Company.Product.WebApp\bin\Debug\net5.0\wwwroot\`` to ``C:\Projects\XYZ\Product\WebApp\bin\Debug\net5.0\wwwroot\`` ?

Thank you.

_System.IO.DirectoryNotFoundException
  HResult=0x80070003
  Message=C:\Projects\XYZ\Product\Company.Product.WebApp\bin\Debug\net5.0\wwwroot\
  Source=Microsoft.Extensions.FileProviders.Physical
  StackTrace:
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsFileProvider..ctor(String pathPrefix, String contentRoot)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.<>c.<UseStaticWebAssetsCore>b__2_0(ContentRootMapping cr)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<OfTypeIterator>d__62`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssetsCore(IWebHostEnvironment environment, Stream manifest)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssets(IWebHostEnvironment environment, IConfiguration configuration)
   at Microsoft.AspNetCore.WebHost.<>c.<ConfigureWebDefaults>b__9_0(WebHostBuilderContext ctx, IConfigurationBuilder cb)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass9_0.<ConfigureAppConfiguration>b__0(HostBuilderContext context, IConfigurationBuilder builder)
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.AspNetCore.Components.WebAssembly.DevServer.Server.Program.BuildWebHost(String[] args)
   at Microsoft.AspNetCore.Components.Web.DevServer.Commands.ServeCommand.Execute()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.AspNetCore.Components.WebAssembly.DevServer.Program.Main(String[] args)_

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Can you try to remove your `bin` and `obj` directories and rebuild again?

**Comment by daniel-p-tech** [comment]
That was it, thanks for your help!
