### ISSUE TITLE
Some problems about the new SocketConnection.

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/aspnetcore#27857]
1、The following problems occur when I use SocketConnection, in concurrency scenarios:
Code like this:
```C#
for()
{
  tasks[i] = Task.Run(async () =>{
     await _connection.Transport.Output.WriteAsync(bytes);
  });
}
Task.WaitAll(tasks);
```
``` Text  

Unhandled exception. System.AggregateException: One or more errors occurred.    
(Concurrent reads or writes are not supported.)   
(Concurrent reads or writes are not supported.)  
(Concurrent reads or writes are not supported.)   
(Concurrent reads or writes are not supported.)   
(Concurrent reads or writes are not supported.)  
(Concurrent reads or writes are not supported.)   
(Concurrent reads or writes are not supported.)   
(Concurrent reads or writes are not supported.)   
(Concurrent reads or writes are not supported.)  
(Concurrent reads or writes are not supported.)
 ---> System.InvalidOperationException: Concurrent reads or writes are not supported.
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetFlushResult(FlushResult& result)
   at System.IO.Pipelines.Pipe.GetFlushAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeWriter.GetResult(Int16 token)
   at console_netcore31_newsocket.Program.<>c__DisplayClass18_0.<<SendFromNewSocketRedis>b__0>d.MoveNext() in I:\OpenSource\xxx\examples\console_netcore31_newsocket\Program.cs:line 306
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at console_netcore31_newsocket.Program.SendFromNewSocketRedis(NewRedisClient client, IDatabase sedb) in I:\OpenSource\xxx\examples\console_netcore31_newsocket\Program.cs:line 313
   at console_netcore31_newsocket.Program.Main(String[] args) in I:\OpenSource\xxx\examples\console_netcore31_newsocket\Program.cs:line 59

```
2、 I received unexpected bytes which be written by last sending:

``` Text
Server: Start Accept!
Server: Accept One!
Run Receiver!
Run Sender!

==============
Send: 123456789

Receive : 123456789
==============
==============
Send: a

Receive : a23456789
==============
```  

How can I avoid these problems? are they BUG??

**Comment by davidfowl** [comment]
You can't read from or write concurrently. It's not supported. What exactly are you trying to do?

**Comment by NMSAzulX** [comment]
@davidfowl  I am trying to be a Single Link Client, and this client needs to support multiple users to use one single link. Something like RedisClient....

**Comment by davidfowl** [comment]
Well you need to synchronize access to the write calls.

**Comment by NMSAzulX** [comment]
Thank you! Do you have a solution to the second question? (a23456789)

Other:
> The performance of this SocketConnection is very good. My friends and I will always follow this technology, it is very cool.

**Comment by davidfowl** [comment]
Check out these docs https://docs.microsoft.com/en-us/dotnet/standard/io/pipelines, they might help with the reading side of things.

> The performance of this SocketConnection is very good. My friends and I will always follow this technology, it is very cool.

Thanks!

**Comment by NMSAzulX** [comment]
> Check out these docs https://docs.microsoft.com/en-us/dotnet/standard/io/pipelines, they might help with the reading side of things.

OK! Love you ~
