### ISSUE TITLE
Flaky test: "ChangeCompiledFile"

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#27856]
Error:
```
System.Threading.Tasks.TaskCanceledException : A task was canceled.
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.AwaitableProcess.GetOutputLineAsync(String predicateName, Predicate`1 predicate, CancellationToken cancellationToken) in /_/src/Tools/dotnet-watch/test/AwaitableProcess.cs:line 106
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.AwaitableProcess.GetOutputLineAsync(String message, TimeSpan timeout) in /_/src/Tools/dotnet-watch/test/AwaitableProcess.cs:line 91
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Testing/src/TaskExtensions.cs:line 56
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.GlobbingAppTests.ChangeCompiledFile(Boolean usePollingWatcher) in /_/src/Tools/dotnet-watch/test/GlobbingAppTests.cs:line 44
--- End of stack trace from previous location ---
```

Logs:
```
The temporary test folder is /home/helixbot/work/B2BF09E2/w/A6880941/e/tmp/uxr5ue3y.5ol
Copying project /home/helixbot/work/B2BF09E2/w/A6880941/e/TestProjects/GlobbingApp to /home/helixbot/work/B2BF09E2/w/A6880941/e/tmp/uxr5ue3y.5ol/GlobbingApp
Restoring msbuild project in GlobbingApp
Project directory: '/home/helixbot/work/B2BF09E2/w/A6880941/e/tmp/uxr5ue3y.5ol/GlobbingApp'
Started process 32021: /home/helixbot/work/B2BF09E2/w/A6880941/e/.dotnet11612/dotnet restore --ignore-failed-sources
  Determining projects to restore...
  Restored /home/helixbot/work/B2BF09E2/w/A6880941/e/tmp/uxr5ue3y.5ol/GlobbingApp/GlobbingApp.csproj (in 71 ms).


Process exited 32021
Process exited 32021 with code 0
Building GlobbingApp
Project directory: '/home/helixbot/work/B2BF09E2/w/A6880941/e/tmp/uxr5ue3y.5ol/GlobbingApp'
Started process 32066: /home/helixbot/work/B2BF09E2/w/A6880941/e/.dotnet11612/dotnet build
Microsoft (R) Build Engine version 16.9.0-preview-20513-07+c10f34c4e for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  GlobbingApp -> /home/helixbot/work/B2BF09E2/w/A6880941/e/tmp/uxr5ue3y.5ol/GlobbingApp/bin/Debug/net6.0/GlobbingApp.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.21


Process exited 32066
Process exited 32066 with code 0
11/15/2020 1:15:52 AM: starting process: 'dotnet /home/helixbot/work/B2BF09E2/w/A6880941/e/tool/dotnet-watch.dll run --'
11/15/2020 1:15:52 AM: process started: 'dotnet /home/helixbot/work/B2BF09E2/w/A6880941/e/tool/dotnet-watch.dll run --'
Waiting for output line [msg == 'Started']. Will wait for 120 sec.
11/15/2020 1:15:53 AM: post: 'watch : Started'
11/15/2020 1:15:53 AM: recv: 'watch : Started'. Does not match condition '[msg == 'Started']'.
11/15/2020 1:15:55 AM: post: 'Started'
11/15/2020 1:15:55 AM: recv: 'Started'. Matches condition '[msg == 'Started']'.
Waiting for output line [msg.StartsWith('Defined types = ')]. Will wait for 30 sec.
11/15/2020 1:15:55 AM: post: 'Process identifier = 32201, 01:15:54.72'
11/15/2020 1:15:55 AM: recv: 'Process identifier = 32201, 01:15:54.72'. Does not match condition '[msg.StartsWith('Defined types = ')]'.
11/15/2020 1:15:55 AM: post: 'Defined types = 2'
11/15/2020 1:15:55 AM: recv: 'Defined types = 2'. Matches condition '[msg.StartsWith('Defined types = ')]'.
Waiting for output line [msg == 'Started']. Will wait for 30 sec.
11/15/2020 1:15:55 AM: post: 'Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.'
11/15/2020 1:15:55 AM: post: '   at Microsoft.DotNet.Cli.Utils.ProcessReaper.HandleProcessExit(Object sender, EventArgs args)'
11/15/2020 1:15:55 AM: post: '   at System.AppContext.OnProcessExit()'
11/15/2020 1:15:55 AM: recv: 'Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.'. Does not match condition '[msg == 'Started']'.
11/15/2020 1:15:55 AM: recv: '   at Microsoft.DotNet.Cli.Utils.ProcessReaper.HandleProcessExit(Object sender, EventArgs args)'. Does not match condition '[msg == 'Started']'.
11/15/2020 1:15:55 AM: recv: '   at System.AppContext.OnProcessExit()'. Does not match condition '[msg == 'Started']'.
11/15/2020 1:16:02 AM: post: 'Gathering state for process 32159 dotnet'
11/15/2020 1:16:02 AM: post: 'Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/dotnet.32159.dmp'
11/15/2020 1:16:02 AM: post: 'Written 181317632 bytes (44267 pages) to core file'
11/15/2020 1:16:02 AM: post: 'Dump successfully written'
11/15/2020 1:16:02 AM: recv: 'Gathering state for process 32159 dotnet'. Does not match condition '[msg == 'Started']'.
11/15/2020 1:16:02 AM: recv: 'Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/dotnet.32159.dmp'. Does not match condition '[msg == 'Started']'.
11/15/2020 1:16:02 AM: recv: 'Written 181317632 bytes (44267 pages) to core file'. Does not match condition '[msg == 'Started']'.
11/15/2020 1:16:02 AM: recv: 'Dump successfully written'. Does not match condition '[msg == 'Started']'.
11/15/2020 1:16:02 AM: post: 'watch : Exited'
11/15/2020 1:16:02 AM: post: 'watch : File changed: /home/helixbot/work/B2BF09E2/w/A6880941/e/tmp/uxr5ue3y.5ol/GlobbingApp/include/Foo.cs'
11/15/2020 1:16:02 AM: recv: 'watch : Exited'. Does not match condition '[msg == 'Started']'.
11/15/2020 1:16:02 AM: recv: 'watch : File changed: /home/helixbot/work/B2BF09E2/w/A6880941/e/tmp/uxr5ue3y.5ol/GlobbingApp/include/Foo.cs'. Does not match condition '[msg == 'Started']'.
11/15/2020 1:16:02 AM: post: 'watch : Started'
11/15/2020 1:16:02 AM: recv: 'watch : Started'. Does not match condition '[msg == 'Started']'.
Disposing WatchableApp
```

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=886877&view=results

**Comment by pranavkm** [comment]
The underlying CLI issue was resolved and the test has been unskipped as part of SDK migration.
