### ISSUE TITLE
Bug with xmlserializer when deployed to IIS

### ISSUE THREAD

**Issue by kostasxagoraris** [dotnet/aspnetcore#27953]
I have a project that was created originally with blazor web assembly 3.2. 
It used some more .net standard 2.0 projects to serialize a few classes from and to xml (also under .net standard 2.0).
I recently upgraded the blazor web app to .net 5.0 . (the project under .net standard 2.0 remained as they were)
While everything on my development machines run smoothly when i deploy to iis I cant instantiate the xml serializer

 [NotSupportedException] : "Parent does not have a default constructor. The default constructor must be explicitly defined."  

The stack trace
at System.Reflection.Emit.TypeBuilder.DefineDefaultConstructor(MethodAttributes attributes)
blazor.webassembly.js:1    at System.Xml.Serialization.XmlSerializationILGen.GenerateBaseSerializer(String baseSerializer, String readerClass, String writerClass, CodeIdentifiers classes)
blazor.webassembly.js:1    at System.Xml.Serialization.TempAssembly.GenerateRefEmitAssembly(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace)
blazor.webassembly.js:1    at System.Xml.Serialization.TempAssembly..ctor(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, String location)
blazor.webassembly.js:1    at System.Xml.Serialization.XmlSerializer.GenerateTempAssembly(XmlMapping xmlMapping, Type type, String defaultNamespace, String location)
blazor.webassembly.js:1    at System.Xml.Serialization.XmlSerializer.GenerateTempAssembly(XmlMapping xmlMapping, Type type, String defaultNamespace)
blazor.webassembly.js:1    at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
blazor.webassembly.js:1    at System.Xml.Serialization.XmlSerializer..ctor(Type type)
blazor.webassembly.js:1    at PanasoftUtilities.XMLStatic.Create_ClassObject_From_XMLDeserialization[AADEBooksParam](String xml, String& Errormessage, Type[] ExtraTypes)

Source: System.Private.CoreLib

TargetSite: DefineDefaultConstructor

Of course there is no lack of default constructor anywhere. And anyways it works when running the site on visual studio and it work fine under blazor 3.2 .net core 3.1.

I tried publishing the site using different combinations of x64 x86 and target runtime. 
I ve being struggling with the issue for 2 days. I don't know what else to do.

Do you need me to upload the published artifacts so that you have a look?

Thanks for your advice.

**Comment by javiercn** [comment]
@kostasxagoraris thanks for contacting us.

This is likely caused by the linker being more agressive in 5.0, you can customize the linker following the steps [here](https://devblogs.microsoft.com/dotnet/customizing-trimming-in-net-core-5/)

**Comment by gonsalvg** [comment]
I was having the same issue, though on an asp.net hosted setup. Following @javiercn 's link I just decided to temporarily disable the crazy trimming via <PublishTrimmed>false</PublishTrimmed> in my client project's propertygroup, which fixed this. Obviously hope to re-enable the feature soon as it seems nice :)

**Comment by kostasxagoraris** [comment]
I tried different but i still havent resolved the issue (disabling trimming all the way ) I will try again tomorrow. I m sure i m doing something wrong because the error insists

**Comment by kostasxagoraris** [comment]
I have disable trimming completely in my blazor webassembly client project and in the server  project 
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <PublishTrimmed>false</PublishTrimmed>
    <BlazorCacheBootResources>false</BlazorCacheBootResources>
  </PropertyGroup>

  <ItemGroup>....

like this i still get the same issue.

**Comment by kostasxagoraris** [comment]
I also used this command

dotnet publish Panasoft.Web.MyData.Server.csproj -p:PublishTrimmed=false --self-contained --runtime win-x64 -c release
and the problem is still there. Very persistent!!

I m a bit frustrated What else can I do?
