### ISSUE TITLE
Slightly flaky test: `UnixDomainSocketsTest.TestUnixDomainSocketWithUrl()`

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#28067]
Test failed just once over thirty days according to the test failure report (<https://dev.azure.com/dnceng/public/_test/analytics?definitionId=837&contextType=build>) filtered for `TestUnixDomainSocketWithUrl` but not branch. It hasn't failed at all in aspnetcore-ci except as a result of other test issues e.g. dotnet installation failures on Helix agents.

- [Build log](https://dev.azure.com/dnceng/public/_build/results?buildId=888925)
- [Helix console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-heads-master-1f9bba12b03c469690/Libuv.FunctionalTests--net6.0/console.58ac5a42.log?sv=2019-07-07)
- [UnixDomainSocketsTest_TestUnixDomainSocketWithUrl.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-heads-master-1f9bba12b03c469690/Libuv.FunctionalTests--net6.0/UnixDomainSocketsTest_TestUnixDomainSocketWithUrl.log?sv=2019-07-07)

Failure:
``` text
[xUnit.net 00:00:02.87]     TestUnixDomainSocketWithUrl [FAIL]
[xUnit.net 00:00:02.87]       System.ArgumentOutOfRangeException : Length cannot be less than zero. (Parameter 'length')
[xUnit.net 00:00:02.87]       Stack Trace:
[xUnit.net 00:00:02.87]            at System.String.Substring(Int32 startIndex, Int32 length)
[xUnit.net 00:00:02.87]         /_/src/Servers/Kestrel/test/FunctionalTests/UnixDomainSocketsTests.cs(191,0): at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.UnixDomainSocketsTest.TestUnixDomainSocketWithUrl()
[xUnit.net 00:00:02.87]         --- End of stack trace from previous location ---
```
Seems like the `httpResponse` string didn't contain the expected two spaces. Unfortunately, the actual string is not logged.

Nothing obvious in UnixDomainSocketsTest_TestUnixDomainSocketWithUrl.log:
``` text
[0.002s] [TestLifetime] [Information] Starting test TestUnixDomainSocketWithUrl at 2020-11-17T12:52:29
[0.022s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting starting
[0.041s] [Microsoft.Hosting.Lifetime] [Information] Now listening on: http://unix://var/folders/dq/brw46d8x763fv_mtdxg2_f2w0000gs/T/tmpZ1y7z8.tmp
[0.041s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Debug] Loaded hosting startup assembly Libuv.FunctionalTests
[0.041s] [Microsoft.Hosting.Lifetime] [Information] Application started. Press Ctrl+C to shut down.
[0.041s] [Microsoft.Hosting.Lifetime] [Information] Hosting environment: Production
[0.042s] [Microsoft.Hosting.Lifetime] [Information] Content root path: /private/tmp/helix/working/AFE4095E/w/BE2F0A15/e/
[0.042s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting started
[0.045s] [Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv] [Debug] Connection id "0HM4AUUI4FEE0" received FIN.
[0.045s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "0HM4AUUI4FEE0" accepted.
[0.045s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "0HM4AUUI4FEE0" started.
[0.046s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "0HM4AUUI4FEE0" disconnecting.
[0.046s] [Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv] [Debug] Connection id "0HM4AUUI4FEE0" sending FIN because: "The client closed the connection."
[0.046s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "0HM4AUUI4FEE0" stopped.
[0.051s] [TestLifetime] [Information] Finished test TestUnixDomainSocketWithUrl in 0.0484749s
```

**Comment by dougbu** [comment]
Not sure it's relevant but failure was on an OSX.1100.Amd64.Open agent.

**Comment by BrennanConroy** [comment]
@halter73 mentioned today that this might be caused by the file limit being hit on Mac and when a file is opened if it hits the limit it is closed immediately which causes the read result to be empty.

**Comment by jkotalik** [comment]
Triage: the quarantine is only for libuv, so once we remove libuv in 6.0, we can unquarantined it.
