### ISSUE TITLE
Adding Microsoft.AspNetCore.SignalR.Protocols.Message package crashes connection

### ISSUE THREAD

**Issue by shersh** [dotnet/aspnetcore#28354]
### Describe the bug
After adding installing nuget package Microsoft.AspNetCore.SignalR.Protocols.Message (without any additional steps) to server any connection to websocket will be refused with error InternalServerError

### To Reproduce
Just add packet to server Microsoft.AspNetCore.SignalR.Protocols.Message 

Example of code: 
https://github.com/shersh/signalr_error

### Exceptions (if any)
System.InvalidOperationException: Websocket closed with error: InternalServerError.
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartReceiving(WebSocket socket)
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.HandshakeAsync(ConnectionState startingConnectionState, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
   at ConsoleApp1.Program.Main(String[] args) in ..\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 27

### Further technical details
- ASP.NET Core version 5.0.0
- Include the output of `dotnet --info`
 Version:   5.0.100
 Commit:    5044b93829

Среда выполнения:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jkotalik** [comment]
Are you looking for Microsoft.AspNetCore.SignalR.Protocols.MessagePack instead of Message?

**Comment by jkotalik** [comment]
Nvrm, looked at your sample now and see that it is MessagePack on the server.

@BrennanConroy do you also need include MessagePack on the client as well? Maybe try including that package and see if it works.

**Comment by shersh** [comment]
@jkotalik you can find in example source code that I don't use messagePack at all, just add nuget reference and that cause a problems with connection. 
Maybe this nuget package has invalid another references that cause issues?

**Comment by BrennanConroy** [comment]
Looks like another case of https://github.com/dotnet/runtime/issues/45560
You can workaround the issue by any of the following:
* Including a reference to `System.Text.Encodings.Web` 5.0.0
* Updating your app to net5.0
* Downgrading your SignalR.MessagePack reference to 3.1
