### ISSUE TITLE
Get the redis tests working on the CI server

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#28381]
We use a custom xunit test framework with the TestFramework attribute to launch a redis server for the tests to hit. This works fine locally, but doesn't work on the CI server for unknown reasons. The tests have been temporarily disabled until we can work this out.

```
[Test collection for Microsoft.Framework.Cache.Redis.RedisCacheSetAndRemoveTests] Microsoft.Framework.Cache.Redis.RedisCacheSetAndRemoveTests.SetAlwaysOverwrites (2s)
[Microsoft.Framework.Cache.Redis.RedisCacheSetAndRemoveTests.GetOrSetDoesNotOverwrite] 
StackExchange.Redis.RedisConnectionException : It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING
   at StackExchange.Redis.ConnectionMultiplexer.Connect(String configuration, TextWriter log) in c:\TeamCity\buildAgent\work\58bc9a6df18a3782\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 738
   at Microsoft.Framework.Cache.Redis.RedisCache.Connect() in C:\BuildAgent\work\bc13a11492fdf8a8\src\Microsoft.Framework.Cache.Redis\RedisCache.cs:line 48
   at Microsoft.Framework.Cache.Redis.RedisCache.Set(String key, Object state, Action`1 create) in C:\BuildAgent\work\bc13a11492fdf8a8\src\Microsoft.Framework.Cache.Redis\RedisCache.cs:line 55
   at Microsoft.Framework.Cache.Distributed.CacheExtensions.Set(IDistributedCache cache, String key, Byte[] value) in C:\BuildAgent\work\bc13a11492fdf8a8\src\Microsoft.Framework.Cache.Distributed\CacheExtensions.cs:line 40
   at Microsoft.Framework.Cache.Redis.RedisCacheSetAndRemoveTests.GetOrSetDoesNotOverwrite() in C:\BuildAgent\work\bc13a11492fdf8a8\test\Microsoft.Framework.Cache.Redis.Tests\RedisCacheSetAndRemoveTests.cs:line 66

```

**Comment by BrennanConroy** [comment]
Not high priority and has been open for 6 years.

**Comment by wtgodbe** [comment]
> We use a custom xunit test framework with the TestFramework attribute to launch a redis server for the tests to hit. This works fine locally, but doesn't work on the CI server for unknown reasons. The tests have been temporarily disabled until we can work this out.
> 
> ```
> [Test collection for Microsoft.Framework.Cache.Redis.RedisCacheSetAndRemoveTests] Microsoft.Framework.Cache.Redis.RedisCacheSetAndRemoveTests.SetAlwaysOverwrites (2s)
> [Microsoft.Framework.Cache.Redis.RedisCacheSetAndRemoveTests.GetOrSetDoesNotOverwrite] 
> StackExchange.Redis.RedisConnectionException : It was not possible to connect to the redis server(s); to create a disconnected multiplexer, disable AbortOnConnectFail. SocketFailure on PING
>    at StackExchange.Redis.ConnectionMultiplexer.Connect(String configuration, TextWriter log) in c:\TeamCity\buildAgent\work\58bc9a6df18a3782\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 738
>    at Microsoft.Framework.Cache.Redis.RedisCache.Connect() in C:\BuildAgent\work\bc13a11492fdf8a8\src\Microsoft.Framework.Cache.Redis\RedisCache.cs:line 48
>    at Microsoft.Framework.Cache.Redis.RedisCache.Set(String key, Object state, Action`1 create) in C:\BuildAgent\work\bc13a11492fdf8a8\src\Microsoft.Framework.Cache.Redis\RedisCache.cs:line 55
>    at Microsoft.Framework.Cache.Distributed.CacheExtensions.Set(IDistributedCache cache, String key, Byte[] value) in C:\BuildAgent\work\bc13a11492fdf8a8\src\Microsoft.Framework.Cache.Distributed\CacheExtensions.cs:line 40
>    at Microsoft.Framework.Cache.Redis.RedisCacheSetAndRemoveTests.GetOrSetDoesNotOverwrite() in C:\BuildAgent\work\bc13a11492fdf8a8\test\Microsoft.Framework.Cache.Redis.Tests\RedisCacheSetAndRemoveTests.cs:line 66
> ```
