### ISSUE TITLE
SignalR .NET Core: Failed writing message. Aborting connection. Value cannot be null. (Parameter 'inputType')

### ISSUE THREAD

**Issue by jclaessens97** [dotnet/aspnetcore#28411]
### Describe the bug
I use SignalR to connect my javascript client to my hub and send some data. I can connect successfully with wss and jwt authentication. But somehow when I call invoke on the connection it disconnects. It took me a long time to find how to get more information about it, but now it seems that there is an exception thrown when invoking a method on the hub. If I put breakpoints in it everything seems normal though, but when enabling the debug logging for signalR I get the following exceptions (see below). 

After that he automatically reconnects until I invoke that method or another method again...

Hub:
```
    [Authorize]
    public class ProgressHub : Hub<IProgressHub>
    {
        public Task WatchSimulations(List<Guid> simulationUids)
        {
            var tasks = new List<Task>();
            simulationUids.ForEach(id =>
            {
                tasks.Add(
                    Groups.AddToGroupAsync(Context.ConnectionId, id.ToString())
                );
            });
            return Task.WhenAll(tasks);
        }
    }
```

JS Client connect & invoke:
```
  const connection = new HubConnectionBuilder()
    .withUrl(`${hubUrl}/progress-hub`, { accessTokenFactory: () => token })
    .withAutomaticReconnect()
    .configureLogging(logLevel)
    .build();

  await connection.start();
  connection.invoke('WatchSimulations', this.simulations.map((s) => s.simulationUid));
```

### Exceptions (if any)
Serverside:
```
dbug: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[1]
      Received hub invocation: InvocationMessage { InvocationId: "0", Target: "WatchSimulations", Arguments: [ System.Collections.Generic.List`1[System.Guid] ], StreamIds: [  ] }.
Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher: Debug: Received hub invocation: InvocationMessage { InvocationId: "0", Target: "WatchSimulations", Arguments: [ System.Collections.Generic.List`1[System.Guid] ], StreamIds: [  ] }.
dbug: Microsoft.AspNetCore.SignalR.HubConnectionContext[6]
Microsoft.AspNetCore.SignalR.HubConnectionContext: Debug: Failed writing message. Aborting connection.

System.ArgumentNullException: Value cannot be null. (Parameter 'inputType')
   at System.Text.Json.JsonSerializer.Serialize(Utf8JsonWriter writer, Object value, Type inputType, JsonSerializerOptions options)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteCompletionMessage(CompletionMessage message, Utf8JsonWriter writer)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteMessageCore(HubMessage message, IBufferWriter`1 stream)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteMessage(HubMessage message, IBufferWriter`1 output)
   at Microsoft.AspNetCore.SignalR.HubConnectionContext.WriteCore(HubMessage message, CancellationToken cancellationToken)
      Failed writing message. Aborting connection.
Microsoft.AspNetCore.SignalR.HubConnectionHandler: Debug: OnConnectedAsync ending.
      System.ArgumentNullException: Value cannot be null. (Parameter 'inputType')
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Debug: Waiting for the client to close the socket.
         at System.Text.Json.JsonSerializer.Serialize(Utf8JsonWriter writer, Object value, Type inputType, JsonSerializerOptions options)
         at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteCompletionMessage(CompletionMessage message, Utf8JsonWriter writer)
         at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteMessageCore(HubMessage message, IBufferWriter`1 stream)
         at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.WriteMessage(HubMessage message, IBufferWriter`1 output)
         at Microsoft.AspNetCore.SignalR.HubConnectionContext.WriteCore(HubMessage message, CancellationToken cancellationToken)
dbug: Microsoft.AspNetCore.SignalR.HubConnectionHandler[6]
      OnConnectedAsync ending.
dbug: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[7]
      Waiting for the client to close the socket.
dbug: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[2]
      Socket closed.
Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport: Debug: Socket closed.
```

client side:
```
[2020-12-04T13:17:52.436Z] Debug: The HttpConnection connected successfully.
Utils.js?7ed1:228 [2020-12-04T13:17:52.436Z] Debug: Sending handshake request.
Utils.js?7ed1:224 [2020-12-04T13:17:52.437Z] Information: Using HubProtocol 'json'.
Utils.js?7ed1:228 [2020-12-04T13:17:52.448Z] Debug: Server handshake complete.
Utils.js?7ed1:228 [2020-12-04T13:17:52.449Z] Debug: HubConnection connected successfully.
ProgressCaseStudies.vue?51c3:197 HubConnection {…}
Utils.js?7ed1:228 [2020-12-04T13:17:58.957Z] Debug: HttpConnection.stopConnection(undefined) called while in state Connected.
Utils.js?7ed1:224 [2020-12-04T13:17:58.957Z] Information: Connection disconnected.
Utils.js?7ed1:228 [2020-12-04T13:17:58.957Z] Debug: HubConnection.connectionClosed(undefined) called while in state Connected.
Utils.js?7ed1:224 [2020-12-04T13:17:58.958Z] Information: Connection reconnecting.
Utils.js?7ed1:224 [2020-12-04T13:17:58.958Z] Information: Reconnect attempt number 1 will start in 0 ms.
HubConnection.js?98b8:650 Uncaught (in promise) Error: Invocation canceled due to the underlying connection being closed.
    at HubConnection.connectionClosed (HubConnection.js?98b8:650)
    at HttpConnection.HubConnection.connection.onclose (HubConnection.js?98b8:74)
    at HttpConnection.stopConnection (HttpConnection.js?da58:559)
    at WebSocketTransport.transport.onclose (HttpConnection.js?da58:479)
    at WebSocketTransport.close (WebSocketTransport.js?eb1a:192)
    at WebSocket.webSocket.onclose (WebSocketTransport.js?eb1a:138)
HubConnection.connectionClosed @ HubConnection.js?98b8:650
HubConnection.connection.onclose @ HubConnection.js?98b8:74
HttpConnection.stopConnection @ HttpConnection.js?da58:559
transport.onclose @ HttpConnection.js?da58:479
WebSocketTransport.close @ WebSocketTransport.js?eb1a:192
webSocket.onclose @ WebSocketTransport.js?eb1a:138
Utils.js?7ed1:228 [2020-12-04T13:17:58.959Z] Debug: Starting connection with transfer format 'Text'.
Utils.js?7ed1:228 [2020-12-04T13:17:58.960Z] Debug: Sending negotiation request: https://localhost:5001/progress-hub/negotiate?negotiateVersion=1.
Utils.js?7ed1:228 [2020-12-04T13:17:58.971Z] Debug: Selecting transport 'WebSockets'.
Utils.js?7ed1:224 [2020-12-04T13:17:58.997Z] Information: WebSocket connected to wss://localhost:5001/progress-hub?id=lRdo0ulJe2g0VuuVXyBKwQ&access_token=<token>.
Utils.js?7ed1:228 [2020-12-04T13:17:58.997Z] Debug: The HttpConnection connected successfully.
Utils.js?7ed1:228 [2020-12-04T13:17:58.997Z] Debug: Sending handshake request.
Utils.js?7ed1:224 [2020-12-04T13:17:58.998Z] Information: Using HubProtocol 'json'.
Utils.js?7ed1:228 [2020-12-04T13:17:59.009Z] Debug: Server handshake complete.
Utils.js?7ed1:224 [2020-12-04T13:17:59.009Z] Information: HubConnection reconnected successfully.
```

### Further technical details
- .NET Core version: **3.1**
```
❯ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.100/

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.1.101 [/usr/local/share/dotnet/sdk]
  3.1.300 [/usr/local/share/dotnet/sdk]
  3.1.302 [/usr/local/share/dotnet/sdk]
  3.1.401 [/usr/local/share/dotnet/sdk]
  3.1.402 [/usr/local/share/dotnet/sdk]
  3.1.403 [/usr/local/share/dotnet/sdk]
  5.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.20 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.21 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.22 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
Visual Studio Code for Mac 
<img width="512" alt="image" src="https://user-images.githubusercontent.com/10177148/101167791-21a37000-3643-11eb-8dc2-d2904b2e1fe6.png">

**Comment by jclaessens97** [comment]
According to the comment from a SignalR dev on my S/O comment, it will be fixed in 3.1.11. For now switching to Newtonsoft.Json worked.
