### ISSUE TITLE
When creating an OpenAPI client with a space in the project name, then NSWAG fails.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#28441]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/When-creating-an-OpenAPI-client-with-a-s/1275819)._

---
[severity:I'm unable to use this version]
If I:

1. Create a new .net core console project and name it like  NoSpaceInProjectName 
2. Set the framework to 5.0
3. Add conencted services - > OpenAPI -> 
4. Point to any OpenAPI/Swagger document, like http://demo.edument.se/Content/swagger.json
5. Namespace for the generated code, testtest
6. All well, now rebuild the project! all fine!

If I do the same above, but with a project named "ProjectName WithSpace", then the build fails with

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command ""C:\Users\Tore\.nuget\packages\nswag.msbuild\13.0.5\build\.. /tools/Win/NSwag.exe" openapi2csclient /className:swaggerClient /namespace:testtest /input:C:\Users\Tore\source\repos\ConsoleApp20\ProjectName WithSpace\OpenAPIs\swagger.json /output:obj\swaggerClient.cs " exited with code -1.	ProjectName WithSpace	C:\Users\Tore\.nuget\packages\nswag.apidescription.client\13.0.5\build\NSwag.ApiDescription.Client.targets	28	

If I ran the same from VS developer command promt, I get this error:

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>"C:\Users\Tore\.nuget\packages\nswag.msbuild\13.0.5\build\.. /tools/Win/NSwag.exe" openapi2csclient /className:swaggerClient /namespace:recipedb /input:C:\Code\Console Application\OpenAPIClient\OpenAPIClient\OpenAPIs\swagger.json /output:obj\swaggerClient.cs " exited with code -1.OpenAPIClientC:\Users\Tore\.nuget\packages\nswag.apidescription.client\13.0.5\build\NSwag.ApiDescription.Client.targets
NSwag command line tool for .NET 4.6.1+ WinX64, toolchain v13.0.5.0 (NJsonSchema v10.0.22.0 (Newtonsoft.Json v11.0.0.0))
Visit http://NSwag.org for more information.
NSwag bin directory: C:\Users\Tore\.nuget\packages\nswag.msbuild\13.0.5\tools\Win
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not find file 'C:\Code\Console'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream.. ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader.. ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at NJsonSchema.Infrastructure.DynamicApis.FileReadAllText(String filePath)
   at NSwag.OpenApiDocument. <FromFileAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.OutputCommandBase. <ReadSwaggerDocumentAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.InputOutputCommandBase. <GetInputSwaggerDocument>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.CodeGeneration.SwaggerToCSharpClientCommand. <<RunAsync>b__83_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.CodeGeneration.SwaggerToCSharpClientCommand. <RunAsync>d__83.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NSwag.Commands.CodeGeneration.SwaggerToCSharpClientCommand. <RunAsync>d__82.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor. <ProcessSingleAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NConsole.CommandLineProcessor. <ProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args)
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>Common7

---
#### Feedback Bot on 12/2/2020, 10:44 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jkone27** [comment]
This is still happening and it's February 2021, any updates on this one ? happened the same to me when migrating to net5.0 :/

**Comment by icnocop** [comment]
This is already fixed in a newer version of NSwag.ApiDescription.Client.
See https://github.com/RicoSuter/NSwag/pull/2504

**Comment by Vulisha** [comment]
I just had this issue on old version 13.0, and it is working after update to latest stable. I believe it can be closed.
