### ISSUE TITLE
ApiAuthorization does not work after upgrading to .NET 5

### ISSUE THREAD

**Issue by muqeet-ftg** [dotnet/aspnetcore#28456]
### Describe the bug
I am using .NET Core API Authorization since 3.1 which was working fine until I upgraded my project to .NET 5. After updating, I have been getting _NullReferenceException_

### To Reproduce
**ConfigureServices** method from _Startup.cs_
```csharp
services.AddDbContext<ApplicationDbContext>(options =>
                    options.UseInMemoryDatabase("Databaase"));

services.AddDefaultIdentity<ApplicationUser>()
                .AddEntityFrameworkStores<ApplicationDbContext>();

services.AddIdentityServer()
                .AddApiAuthorization<ApplicationUser, ApplicationDbContext>();

services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddJwtBearer(options =>
                {
                    options.RequireHttpsMetadata = false;
                    options.SaveToken = true;
                    options.TokenValidationParameters = new TokenValidationParameters
                    {
                        ValidateIssuer = true,
                        ValidateIssuerSigningKey = true,
                        ValidIssuer = configuration["Jwt:Issuer"],
                        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(configuration["Jwt:SecretKey"])),
                        ValidAudience = configuration["Jwt:Audience"],
                        ValidateAudience = true,
                        ValidateLifetime = true,
                        ClockSkew = TimeSpan.Zero // Override the default clock skew of 5 mins
                    };
                    //services.AddCors();
                });
```
**Configure** method from _Startup.cs_

```csharp
app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();
```

**DbContext**
public class ApplicationDbContext : ApiAuthorizationDbContext<ApplicationUser>

DbContext Constructor
public ApplicationDbContext(DbContextOptions options, IOptions<OperationalStoreOptions> operationalStoreOptions, ICurrentUserService currentUserService, IDateTime dateTime) : base(options, operationalStoreOptions)
        {
            _currentUserService = currentUserService;
            _dateTime = dateTime;
        }

### Exceptions
 **NullReferenceException** as:
Object reference not set to an instance of an object.
Microsoft.Extensions.DependencyInjection.ConfigureApiResources.GetApiResources()+MoveNext()
Microsoft.Extensions.DependencyInjection.ConfigureApiResources.Configure(ApiAuthorizationOptions options)

### Further technical details
- ASP.NET version 5.0.0
- Visual Studio 2019 (16.8.2) on Windows 10 OS
[dotnet-info.txt](https://github.com/dotnet/aspnetcore/files/5648525/dotnet-info.txt)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@HaoK can you please look into this? Thanks!

**Comment by HaoK** [comment]
Hi @muqeet-ftg can you upload your repro project to a git repo so I can take a look?

**Comment by Frisch12** [comment]
We have the same problem. I've created a small example for it: https://gist.github.com/0c061fc14d5fd38b123f1ba3db92d367

I use Rider 2020.3 EAP 10 with .NET 5.0.

**Comment by muqeet-ft** [comment]
Hi @HaoK thank you for your concern, 

Here is the link to git repo https://github.com/futuretech-group/JWTAuthorization

**Comment by muqeet-ftg** [comment]
Hi @HaoK thank you for your concern,

Here is the link to git repo https://github.com/futuretech-group/JWTAuthorization

**Comment by HaoK** [comment]
What am I supposed to do to demonstrate the issue?  The app starts up fine and swagger exercising the endpoints seems fine

**Comment by muqeet-ftg** [comment]
Go to swagger

**POST /api/Account**, try logging in with username as _test@gmail.com_ and password as _Test@123_, then it gives this exception

**Comment by HaoK** [comment]
Thanks, looks like that null ref is due to AddIdentityServerJwt not being called which is responsible for registering a service that some of the infrastructure expects.  Can you also include a 3.1 repro app that works for comparison.

**Comment by muqeet-ftg** [comment]
Within the same repository (https://github.com/futuretech-group/JWTAuthorization), if I downgrade nuget package **Microsoft.AspNetCore.ApiAuthorization.IdentityServer** to **3.1.10** it works. We are using this as a workaround currently. 

I have created a repo for you at https://github.com/futuretech-group/JWTAuthorization_3, please check.

**Comment by panosru** [comment]
I also face the exact same issue as @muqeet-ftg describes, in my case I have `AddIdentityServerJwt()` method properly set and accessed. When I downgrade to v3.1.10, as mentioned above, then my endpoints work again, but with v5.0.1 I'm getting the following exception:

```
An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Extensions.DependencyInjection.IdentityServerBuilderConfigurationExtensions.<>c.<AddSigningCredentials>b__10_2(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Authentication.AuthenticationHttpContextExtensions.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

if I comment out `AddApiAuthorization` method, the endpoints are processed, but of course, that is not the solution.

**Comment by HaoK** [comment]
The biggest difference between 5.0 and 3.1 is that it upgrades from IdentityServer4 3.0 to 4.0, I wonder if that is causing some of these issues, @javiercn do you know if there are any major semantic breaking changes that would surface going from the ApiAuthorization 3.1 to 5.0?

**Comment by panosru** [comment]
@HaoK I run some tests to make sure when exactly the issue appeared:

From v.3.1.10 up to 5.0.0-preview.3.20215.14 and v5.0.0-preview.8.20414.8, I'm not getting any issues.

From v5.0.0-preview.4.20257.10 to 5.0.0-preview.7.20365.19, I was getting the following exception

```
Unhandled exception. System.MissingMethodException: Method not found: 'Microsoft.AspNetCore.Authentication.AuthenticationBuilder Microsoft.AspNetCore.Authentication.AuthenticationBuilder.AddScheme(System.String, System.String, System.Action`2<System.__Canon,!!2>)'.
   at Microsoft.Extensions.DependencyInjection.JwtBearerExtensions.AddJwtBearer[TService](AuthenticationBuilder builder, String authenticationScheme, String displayName, Action`2 configureOptions)
   at Microsoft.Extensions.DependencyInjection.JwtBearerExtensions.AddJwtBearer(AuthenticationBuilder builder, String authenticationScheme, String displayName, Action`1 configureOptions)
   at Microsoft.AspNetCore.Authentication.AuthenticationBuilderExtensions.AddIdentityServerJwt(AuthenticationBuilder builder)
   at CleanDDDArchitecture.Domains.Account.CrossCutting.AccountDependencyInjectionRegistry.AddAccountDomain(IServiceCollection services) in /Volumes/Projects/RND/VisualStudio/CleanDDDArchitecture/Domains/Account/CrossCutting/AccountDependencyInjectionRegistry.cs:line 93
   at CleanDDDArchitecture.Hosts.RestApi.Application.Startup.ConfigureServices(IServiceCollection services) in /Volumes/Projects/RND/VisualStudio/CleanDDDArchitecture/Hosts/RestApi/Application/Startup.cs:line 146
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at CleanDDDArchitecture.Hosts.RestApi.Application.Program.Main(String[] args) in /Volumes/Projects/RND/VisualStudio/CleanDDDArchitecture/Hosts/RestApi/Application/Program.cs:line 35
   at CleanDDDArchitecture.Hosts.RestApi.Application.Program.<Main>(String[] args)
```

from v5.0.0-rc.1.20451.17 up to 5.0.1, I'm getting the `System.NullReferenceException` I posted previously.

I hope it helps somehow on the debugging process.

**Comment by panosru** [comment]
Merry Christmas to all! I was wondering if we will have any update on the matter in near future... thanks!

**Comment by colinasquith** [comment]
I had not been able to upgrade several projects to .NET 5 because of the same error, following @musqeet-ftg and downgrading Microsoft.AspNetCore.ApiAuthorization.IdentityServer to 3.1.10 is a workaround.

**Comment by javiercn** [comment]
@haok there shouldn't be any major changes impacting it.

**Comment by javiercn** [comment]
The issue is that there is no key specified in the config file from what I can tell.

**Comment by panosru** [comment]
@javiercn like this _(I use YAML for my configs)_?

```yaml
IdentityServer:
  Key:
    Type: Store
    StoreName: My
    StoreLocation: CurrentUser
    Name: CN=MyApplication
```

Even with that, I'm still getting the `System.NullReferenceException`

**Comment by javiercn** [comment]
@panosru I would suggest you first try to hardcode it in config and make sure it works locally, then move it to your desired config system.

**Comment by panosru** [comment]
@javiercn thanks! It was as you mentioned, the Key was missing from the configuration, not that it is in place everything went back to normal!

**Comment by HaoK** [comment]
@javiercn do you think there's anything we can/should do to improve the situation when the key is missing?

**Comment by panosru** [comment]
@HaoK maybe a more specific exception? (just throwing an idea)

**Comment by muqeet-ftg** [comment]
For some reason, even after adding the specified **Key** as follows, it did not work for me.

```
"IdentityServer": {
    "Key": {
      "Type": "Development"
    }
  }
```

I have updated the github repo  https://github.com/futuretech-group/JWTAuthorization with the same (for reference). If I try to revert **Microsoft.AspNetCore.ApiAuthorization.IdentityServer** to **3.1.11** it works, when I update this package to **5.0.2** it breaks.

**Comment by colinasquith** [comment]
@muqeet-ftg I think you're missing .AddIdentityServerJwt() on the  services.AddAuthentication call in Startup.cs

I updated and add this and it fixed the main first error I was seeing, although now the Bearer Token stuff I had working no longer works as I get a 401, but I think maybe there's just some change in the way things are handled.

**Comment by muqeet-ftg** [comment]
As correctly pointed by @colinasquith, it works when I added `.AddIdentityServerJwt()` on the `services.AddAuthentication` call in `Startup.cs`. 

Thank you so much

**Comment by HaoK** [comment]
Cool, so everyone is good here now and I can close?  I mentioned that to you earlier https://github.com/dotnet/aspnetcore/issues/28456#issuecomment-742685671 @muqeet-ftg but glad you have resolved it out now :)

**Comment by muqeet-ftg** [comment]
@HaoK it did not work earlier, so I didn't take that into consideration. Now adding both `Key` and `.AddIdentityServerJwt() ` worked for me. Apologies :) ... I am really thankful to you and everyone else here who helped me resolving the issue.

I am cool, you can close the issue.

**Comment by colinasquith** [comment]
I agree with @panosru - it would be great if there was some kind of Exception that gave you a clue to what you need to change
