### ISSUE TITLE
Health Checks - Exception on client premature disconnect

### ISSUE THREAD

**Issue by fogzot** [dotnet/aspnetcore#28568]
### Describe the bug
After implementing health checks our logs started showing un-catched "operation was canceled" exceptions (see below). This happens when the client disconnect before the request has been completely processed and is caused by the `HttpContext.RequestAborted` cancellation token. In particular `HealthCheckMiddleware.InvokeAsync` calls `_healthCheckService.CheckHealthAsync` outside of any `try/catch` block and the default healt service throws if the cancellation token passed as argument has been canceled. IMHO, this is a bug because no other part of aspnetcore throws a "top level" excepion on premature client disconnect and also because such uncatched exception show as spurious errors on many log analyzers.

### To Reproduce
Take any example project that uses health checks and rapidly (very rapidly) hit the reload button in the browser while accessing the health page.

### Exceptions (if any)
```
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService.CheckHealthAsync(Func`2 predicate, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Diagnostics.HealthChecks.HealthCheckMiddleware.InvokeAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### Further technical details
- ASP.NET Core version 3.1 and 5.0
```
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     debian
 OS Version:  
 OS Platform: Linux
 RID:         debian-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.101/

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  2.1.811 [/usr/share/dotnet/sdk]
  2.2.402 [/usr/share/dotnet/sdk]
  3.0.103 [/usr/share/dotnet/sdk]
  3.1.404 [/usr/share/dotnet/sdk]
  5.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We're closing this issue as there was no community involvement here for quite a while now.

You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.

**Comment by agehrke** [comment]
For reference, this is how I suppressed those cancellations:

```csharp
private static IEndpointConventionBuilder MapHealthChecksWithCancellationSuppression(IEndpointRouteBuilder endpoints, string pattern, HealthCheckOptions options)
{
    // This is more or less a copy of HealthCheckEndpointRouteBuilderExtensions.MapHealthChecksCore - source: https://source.dot.net/#Microsoft.AspNetCore.Diagnostics.HealthChecks/Builder/HealthCheckEndpointRouteBuilderExtensions.cs,12465841a38c75e2,references

    // HealthCheckMiddleware uses HttpContext.RequestAborted as CancellationToken when calling HealthCheckService.
    // If client making the HTTP request to a HealthCheck endpoint cancels request before receiving a response, a TaskCanceledException will propagate through middlewares
    // and eventually be logged by Microsoft.AspNetCore.Server.Kestrel as an ERROR.   

    var args = options != null ? new[] { Microsoft.Extensions.Options.Options.Create(options) } : Array.Empty<object>();

    var pipeline = endpoints.CreateApplicationBuilder()
        .UseMiddleware<CancellationSuppressionMiddleware>() // We have added this to suppress cancellations coming from HealthCheckMiddleware
        .UseMiddleware<HealthCheckMiddleware>(args)
        .Build();

    return endpoints.Map(pattern, pipeline).WithDisplayName("Health checks");
}


/// <summary>
/// This middleware will catch any cancellation exceptions (OperationCanceledException or TaskCanceledException), and return 204 No Content.
/// </summary>
internal class CancellationSuppressionMiddleware
{
    private readonly RequestDelegate _next;

    public CancellationSuppressionMiddleware(RequestDelegate next)
    {
        _next = next;
    }

    public async Task InvokeAsync(HttpContext httpContext)
    {
        try
        {
            // Forward to next middleware
            await _next(httpContext);
        }
        catch (OperationCanceledException)
        {
            if (httpContext.Response.HasStarted) return;

            // Set a status code. Response will likely not be seen by client as we expect all cancellations to come from httpContext.RequestAborted
            // Why 204 No Content? I could not find any other appropriate status code.
            httpContext.Response.StatusCode = StatusCodes.Status204NoContent;
        }
    }
}
````

**Comment by fogzot** [comment]
@agehrke thank you very much. After this issue was closed I put this on my to do list and ... tah-dah! you did it instead. :)
