### ISSUE TITLE
IJSInProcessRuntime.InvokeVoid causes runtime JS error when return is circular

### ISSUE THREAD

**Issue by AlexAtNet** [dotnet/aspnetcore#28748]
### Describe the bug

IJSInProcessRuntime.InvokeVoid causes runtime JS error when the return value is a javascript object with circular references.

### To Reproduce

1) Create new Blazor WebAssembly project.
2) Add this code on the page:

        @inject IJSRuntime JS
        @{((IJSInProcessRuntime)JS).InvokeVoid("eval", "const q = {}; q.q = q; q;");}

3) Open the page in a browser

### Exceptions (if any)

In the browser console:

    Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
          Unhandled exception rendering component: Converting circular structure to JSON
              --> starting at object with constructor 'Object'
              --- property 'q' closes the circle
          TypeError: Converting circular structure to JSON
              --> starting at object with constructor 'Object'
              --- property 'q' closes the circle
              at JSON.stringify (<anonymous>)
              at Object.invokeJSFromDotNet (https://localhost:5001/_framework/blazor.webassembly.js:1:3842)
              at Object.w [as invokeJSFromDotNet] (https://localhost:5001/_framework/blazor.webassembly.js:1:64287)
              at _mono_wasm_invoke_js_blazor (https://localhost:5001/_framework/dotnet.5.0.1.js:1:190800)
              at do_icall (<anonymous>:wasm-function[10596]:0x194e58)
              at do_icall_wrapper (<anonymous>:wasm-function[3305]:0x79df9)
              at interp_exec_method (<anonymous>:wasm-function[2155]:0x44ad3)
              at interp_runtime_invoke (<anonymous>:wasm-function[7862]:0x12efff)
              at mono_jit_runtime_invoke (<anonymous>:wasm-function[7347]:0x118e5f)
              at do_runtime_invoke (<anonymous>:wasm-function[3304]:0x79d42)
    Microsoft.JSInterop.JSException: Converting circular structure to JSON
        --> starting at object with constructor 'Object'
        --- property 'q' closes the circle
    TypeError: Converting circular structure to JSON
        --> starting at object with constructor 'Object'
        --- property 'q' closes the circle
        at JSON.stringify (<anonymous>)
        at Object.invokeJSFromDotNet (https://localhost:5001/_framework/blazor.webassembly.js:1:3842)
        at Object.w [as invokeJSFromDotNet] (https://localhost:5001/_framework/blazor.webassembly.js:1:64287)
        at _mono_wasm_invoke_js_blazor (https://localhost:5001/_framework/dotnet.5.0.1.js:1:190800)
        at do_icall (<anonymous>:wasm-function[10596]:0x194e58)
        at do_icall_wrapper (<anonymous>:wasm-function[3305]:0x79df9)
        at interp_exec_method (<anonymous>:wasm-function[2155]:0x44ad3)
        at interp_runtime_invoke (<anonymous>:wasm-function[7862]:0x12efff)
        at mono_jit_runtime_invoke (<anonymous>:wasm-function[7347]:0x118e5f)
        at do_runtime_invoke (<anonymous>:wasm-function[3304]:0x79d42)
      at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeJS(String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
      at Microsoft.JSInterop.JSInProcessRuntime.Invoke[Object](String identifier, Int64 targetInstanceId, Object[] args)
      at Microsoft.JSInterop.JSInProcessRuntime.Invoke[Object](String identifier, Object[] args)
      at Microsoft.JSInterop.JSInProcessRuntimeExtensions.InvokeVoid(IJSInProcessRuntime jsRuntime, String identifier, Object[] args)
      at temp.Pages.Index.BuildRenderTree(RenderTreeBuilder __builder) in C:\Users\Alex\Projects\temp\Pages\Index.razor:line 4
      at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
      at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
      at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
      at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

### Possible cause

The exception happens because `InvokeVoid` is in fact `Invoke<object>`. `object` implies deserialisation so when the return object is anything more complex than JSON it will most likely fail. The workaround is to use `Invoke<IJSInProcessReference>(...).Dispose()`.

### Further technical details

    .NET SDK (reflecting any global.json):
    Version:   5.0.101
    Commit:    d05174dc5a

    Runtime Environment:
    OS Name:     Windows
    OS Version:  10.0.18363
    OS Platform: Windows
    RID:         win10-x64
    Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

    Host (useful for support):
      Version: 5.0.1
      Commit:  b02e13abab

    .NET SDKs installed:
      3.0.100 [C:\Program Files\dotnet\sdk]
      3.1.402 [C:\Program Files\dotnet\sdk]
      5.0.100 [C:\Program Files\dotnet\sdk]
      5.0.101 [C:\Program Files\dotnet\sdk]

    .NET runtimes installed:
      Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App

**Comment by mrpmorris** [comment]
It would be bettef for performance if void invokes didn't serialize the function result at all.

**Comment by javiercn** [comment]
@AlexAtNet thanks for contacting us.

While we could improve the handling on `InvokeVoid` methods (which I believe there is a separate issue for) by avoiding serialization of the result all-together, circular references are not supported for JS interop.

**Comment by AlexAtNet** [comment]
@javiercn thank you for your answer.

I honestly believed that I've posted a bug report, not a question. At least I cannot see what the question here might be. Are you sure you tagged it right?
