### ISSUE TITLE
HttpClient fails on integration tests when exception handler returns NotFound

### ISSUE THREAD

**Issue by oyse** [dotnet/aspnetcore#28799]
### Description

When using the exception handler together with the WebApplicationFactory for integration testing the http client fails with an exception on .net 5 when the exception handler sets the status code NotFound. It works fine for other status codes like BadRequest.

This worked fine on .Net 3.1.

Looking at the response from the service it looks fine and as expected in for instance with Swagger so the problem seems to have to do with the WebApplicationFactory and the client it creates.

### Steps to reproduce

Create a minimal Asp.Net Core project on .net5 with an integration test project. A full example solution is found here: https://github.com/oyse/aspnetcore_test_httpclient_error

Sample code below.

Exception handler looks like this
```csharp
[Route("HandleError")]
public IActionResult HandleError()
{
    
    var context = HttpContext.Features.Get<IExceptionHandlerFeature>();
    var exception = context?.Error; 
    var code = HttpStatusCode.InternalServerError; 

    var message = "Internal Server Error";

    switch (exception)
    {
        case MyNotFoundException _:
            code = HttpStatusCode.NotFound;
            message = exception.Message;
            break;
        
        case MyBadRequestException _:
            code = HttpStatusCode.BadRequest;
            message = exception.Message;
            break;                
    }

    Response.StatusCode = (int) code;

    return Problem(detail: message, statusCode: (int) code);
    
}
```

Unit test looks like this

```csharp
[Fact]
public async Task TestNotFound()
{
    var client = _factory.CreateClient();

    var response = await client.GetAsync("TestError/NotFound");
    
    Assert.Equal(response.StatusCode, HttpStatusCode.NotFound);
}
```

### Exception

When running the test I get the following exception.

```
System.Net.Http.HttpRequestException: Error while copying content to a stream.

System.Net.Http.HttpRequestException
Error while copying content to a stream.
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at TestNotFoundClientIssuesTest.TestClientReturns.TestNotFound() in C:\projects\dev-random\TestNotFoundClientIssue\TestNotFoundClientIssuesTest\TestClientReturns.cs:line 25
```

### Further technical details

- net 5.0
- dotnet --info output

```
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.105 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

- Tested the problem in Rider and using dotnet test

**Comment by Tratcher** [comment]
This was an intentional change to mitigate the frequent issue of missing error pages. See https://github.com/aspnet/Announcements/issues/434

**Comment by oyse** [comment]
Changing to 

```app.UseExceptionHandler(new ExceptionHandlerOptions { ExceptionHandlingPath = new PathString("/HandleError"), AllowStatusCode404Response = true,  });```

did the trick.

I looked over the upgrade notes, but not the breaking changes so I missed it.

I am still unsure why it behaves like I expected when using the REST API from a browser, but not when using it from the integration tests, but not big issue for me as long as I can get the previous behaviour.

**Comment by Tratcher** [comment]
> I am still unsure why it behaves like I expected when using the REST API from a browser, but not when using it from the integration tests, but not big issue for me as long as I can get the previous behaviour.

Probably because in the browser scenario a body is provided on the 404 page? The exception handler can't modify the response if the body has already been sent.
