### ISSUE TITLE
Azure SignalR in Java Android Studio 4 not working show this error on hitting signalRController.sendMessage(new ChatMessage("Shivani", "Hello Sir Testing testing 123...."));

### ISSUE THREAD

**Issue by ShivaniChandel** [dotnet/aspnetcore#28841]
--------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.azureservices, PID: 31843
    java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar!classes4.dex)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:151)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.getSocketFactory(SSLConnectionSocketFactory.java:194)
        at kong.unirest.apache.SecurityConfig.createDefaultRegistry(SecurityConfig.java:83)
        at kong.unirest.apache.SecurityConfig.buildSocketFactory(SecurityConfig.java:73)
        at kong.unirest.apache.SecurityConfig.createManager(SecurityConfig.java:57)
        at kong.unirest.apache.ApacheClient.<init>(ApacheClient.java:53)
        at kong.unirest.-$$Lambda$LzMzt6m8SiUmve_yOIZRwHx_kH8.apply(Unknown Source:4)
        at kong.unirest.Config.buildClient(Config.java:586)
        at kong.unirest.Config.getClient(Config.java:579)
        at kong.unirest.BaseRequest.asEmpty(BaseRequest.java:163)
        at com.example.azureservices.SignalRController.sendMessage(SignalRController.java:49)
        at com.example.azureservices.MainActivity$1.onClick(MainActivity.java:69)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process: Sending signal. PID: 31843 SIG: 9

**Comment by BrennanConroy** [comment]
Are you using the SignalR java client? I don't evidence of it in the stack trace.
