### ISSUE TITLE
Blazor.Extensions.Canvas.WebGL.WebGLContext.CreateBuffer throws Unhandled exception rendering component: Cannot wait on monitors on this runtime.

### ISSUE THREAD

**Issue by Alois-xx** [dotnet/aspnetcore#28970]
### Describe the bug
I am told that I cannot wait on a tasks result. I have tried to create a Blazor WebGL application with a simple WebGL canvas.
I cannot get past to create an OpenGL buffer. Is this by design? 

### To Reproduce
```
@page "/SlowMenu"
@using BlazorApp1.Shared
@using Blazor.Extensions.Canvas.Canvas2D; 
@using Blazor.Extensions.Canvas.WebGL;
@using Blazor.Extensions.Canvas; 
@using Blazor.Extensions; 
@using System.Threading;
@inject HttpClient Http

<h1>Slow Weather tm</h1>

<p>This component demonstrates fetching data from the server.</p>
<BECanvas Width="300" Height="400" @ref="_webGLCanvas"></BECanvas>

@code {


    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        _glContext = await _webGLCanvas.CreateWebGLAsync();
        var buffer = _glContext.CreateBuffer();
   }
}
```

### Exceptions (if any)
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot wait on monitors on this runtime.
System.PlatformNotSupportedException: Cannot wait on monitors on this runtime.
   at System.Threading.Monitor.ObjWait(Boolean exitContext, Int32 millisecondsTimeout, Object obj)
   at System.Threading.Monitor.Wait(Object obj, Int32 millisecondsTimeout, Boolean exitContext)
   at System.Threading.Monitor.Wait(Object obj, Int32 millisecondsTimeout)
   at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.SpinThenBlockingWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.InternalWaitCore(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.InternalWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Blazor.Extensions.RenderingContext.CallMethod[WebGLBuffer](String method)
   at Blazor.Extensions.Canvas.WebGL.WebGLContext.CreateBuffer()
   at BlazorApp1.Client.Pages.WebGL.InitBuffers()

### Further technical details
I am using 
Blazor.Extensions.Canvas
.NET 5.0
VS 16.8.0

**Update ** 

After switching to the fully async version it seems to work. But then I get other issues with the library itself. But this exception is at least gone.

**Comment by pranavkm** [comment]
Making a blocking call (`Task.Wait` or `Task.Result` on an uncompleted task) is not supported in .NET WebAssembly. The error message you're seeing here is expected. 

> But then I get other issues with the library itself.

I suggest following up with the library authors for further help.
