### ISSUE TITLE
Flaky Test: UseDefaultAddress_WhenNoServerAddressAndNoDirectConfiguration

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#28993]
Is this port conflicts again?

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=936254&view=results
Error: 
```
  Failed Microsoft.AspNetCore.Server.HttpSys.MessagePumpTests.UseDefaultAddress_WhenNoServerAddressAndNoDirectConfiguration [2 ms]
  Error Message:
   Microsoft.AspNetCore.Server.HttpSys.HttpSysException : The process cannot access the file because it is being used by another process.
  Stack Trace:
     at Microsoft.AspNetCore.Server.HttpSys.UrlGroup.RegisterPrefix(String uriPrefix, Int32 contextId) in /_/src/Servers/HttpSys/src/NativeInterop/UrlGroup.cs:line 129
   at Microsoft.AspNetCore.Server.HttpSys.UrlPrefixCollection.RegisterAllPrefixes(UrlGroup urlGroup) in /_/src/Servers/HttpSys/src/UrlPrefixCollection.cs:line 214
   at Microsoft.AspNetCore.Server.HttpSys.HttpSysListener.Start() in /_/src/Servers/HttpSys/src/HttpSysListener.cs:line 163
   at Microsoft.AspNetCore.Server.HttpSys.MessagePump.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken) in /_/src/Servers/HttpSys/src/MessagePump.cs:line 126
   at Microsoft.AspNetCore.Server.HttpSys.MessagePumpTests.UseDefaultAddress_WhenNoServerAddressAndNoDirectConfiguration() in /_/src/Servers/HttpSys/test/FunctionalTests/MessagePumpTests.cs:line 115
```

**Comment by Tratcher** [comment]
Wow, how did it last this long? The default address tests in Kestrel have been quarantined indefinitely.

**Comment by BrennanConroy** [comment]
This test will likely be permanently quarantined due to inherent flakiness with port binding.
