### ISSUE TITLE
Flaky test: ServerShutsDownWhenMainExitsStress

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#28994]
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=936254&view=results
Error:
```
  Failed Microsoft.AspNetCore.Server.IIS.FunctionalTests.IISExpressShutdownTests.ServerShutsDownWhenMainExitsStress [1 m 45 s]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
---- System.TimeoutException : The operation was canceled.
-------- System.Threading.Tasks.TaskCanceledException : The operation was canceled.
------------ System.IO.IOException : Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
---------------- System.Net.Sockets.SocketException : The I/O operation has been aborted because of either a thread exit or an application request.
  Stack Trace:
     at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.Helpers.<>c__DisplayClass4_0.<<StressLoad>g__RunRequests|0>d.MoveNext() in /_/src/Servers/IIS/IIS/test/Common.FunctionalTests/Infrastructure/Helpers.cs:line 47
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.Helpers.StressLoad(HttpClient httpClient, String path, Action`1 action) in /_/src/Servers/IIS/IIS/test/Common.FunctionalTests/Infrastructure/Helpers.cs:line 58
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.IISExpressShutdownTests.ServerShutsDownWhenMainExitsStress() in /_/src/Servers/IIS/IIS/test/IISExpress.FunctionalTests/InProcess/IISExpressShutdownTests.cs:line 57
--- End of stack trace from previous location ---
----- Inner Stack Trace -----

----- Inner Stack Trace -----
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
----- Inner Stack Trace -----
```
Logs: 
[IISExpressShutdownTests_ServerShutsDownWhenMainExitsStress.log](https://github.com/dotnet/aspnetcore/files/5763228/IISExpressShutdownTests_ServerShutsDownWhenMainExitsStress.log)

**Comment by Tratcher** [comment]
Is that the right linked build? I don't see a test failure reported for IIS Express there.

**Comment by Tratcher** [comment]
Likely related to https://github.com/dotnet/aspnetcore/issues/25107

**Comment by JunTaoLuo** [comment]
Oops, updated the build link.

**Comment by HaoK** [comment]
Clean 30 day run, candidate for unquarantine 

![image](https://user-images.githubusercontent.com/6537861/137997124-5a44ff65-8237-489a-89df-902cc91244f9.png)
