### ISSUE TITLE
[HTTP/3] Fix graceful shutdown for connection for sending goaway.

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#29034]
Right now, graceful server shutdown will throw an exception due to the control stream always trying to write a goaway to the client. This doesn't block shutdown, but should be fixed.

Repro steps:
1. Have connection started between client and server
2. Server shutdown starts
3. Server tries to close connection, which at the moment doesn't wait for all streams to finish gracefully
4. Goaway is written on the control stream after an attempt of graceful shutdown, causing an exception on write.

The main fix is probably going to be in runtime/msquic to figure out if we can start a graceful shutdown which waits for all streams to be finished on a connection before shutting down the connection, which would cause the goaway not to throw.

**Comment by JamesNK** [comment]
I noticed the connection exception below in Kestrel logs.

> Microsoft.AspNetCore.Server.Kestrel.Transport.MsQuic - Debug: Stream id "0HM5M1GTIK41F:0" shutting down writes, exception: "The Quic transport's send loop completed gracefully."

Is the exception related to this issue?

**Comment by JamesNK** [comment]
Exception happens when request ends on the server.

Full logs:
```
 0.000s GrpcTestContext - Information: Starting ConnectionTests.Http3_Grpc
 0.024s Grpc.Net.Client.Internal.GrpcCall - Debug: Starting gRPC call. Method type: 'Unary', URI: 'https://localhost:50010/greet.Greeter/SayHello'.
 0.036s SERVER Microsoft.AspNetCore.Server.Kestrel.Transport.MsQuic - Debug: Connection id "0HM5M1MLM5J5K" accepted.
 0.037s SERVER Microsoft.AspNetCore.Server.Kestrel - Debug: Connection id "0HM5M1MLM5J5K" accepted.
 0.037s SERVER Microsoft.AspNetCore.Server.Kestrel - Debug: Connection id "0HM5M1MLM5J5K" started.
 0.039s SERVER Microsoft.AspNetCore.Server.Kestrel - Trace: Connection id "0HM5M1MLM5J5K:2" received Settings frame for stream ID 2 with length 5.
 0.045s Grpc.Net.Client.Internal.GrpcCall - Debug: Sending message.
 0.053s Grpc.Net.Client.Internal.GrpcCall - Trace: Serialized 'Greet.HelloRequest' to 6 byte message.
 0.058s SERVER Microsoft.AspNetCore.Server.Kestrel - Trace: Connection id "0HM5M1MLM5J5K:0" received Headers frame for stream ID 0 with length 231.
 0.058s SERVER Microsoft.AspNetCore.Server.Kestrel - Trace: Connection id "0HM5M1MLM5J5K:0" received Data frame for stream ID 0 with length 11.
 0.059s SERVER Microsoft.AspNetCore.Hosting.Diagnostics - Information: Request starting HTTP/3 POST https://localhost:50010/greet.Greeter/SayHello application/grpc -
 0.060s Grpc.Net.Client.Internal.GrpcCall - Trace: Message sent.
 0.062s SERVER Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware - Debug: Request matched endpoint 'gRPC - /greet.Greeter/SayHello'
 0.062s SERVER Microsoft.AspNetCore.Routing.EndpointMiddleware - Information: Executing endpoint 'gRPC - /greet.Greeter/SayHello'
 0.070s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Debug: Reading message.
 0.070s SERVER Microsoft.AspNetCore.Server.Kestrel - Debug: Connection id "0HM5M1MLM5J5K:0", Request id "0HM5M1MLM5J5K:0": started reading request body.
 0.070s SERVER Microsoft.AspNetCore.Server.Kestrel - Debug: Connection id "0HM5M1MLM5J5K:0", Request id "0HM5M1MLM5J5K:0": done reading request body.
 0.073s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Trace: Deserializing 6 byte message to 'Greet.HelloRequest'.
 0.079s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Trace: Received message.
 0.082s SERVER FunctionalTestsWebsite.Services.GreeterService - Information: Sending hello to John
 0.083s SERVER Microsoft.AspNetCore.Server.Kestrel - Trace: Connection id "0HM5M1MLM5J5K:0" sending Headers frame for stream ID 0 with length 84.
 0.083s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Debug: Sending message.
 0.086s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Trace: Serialized 'Greet.HelloReply' to 12 byte message.
 0.086s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Trace: Message sent.
 0.088s SERVER Microsoft.AspNetCore.Routing.EndpointMiddleware - Information: Executed endpoint 'gRPC - /greet.Greeter/SayHello'
 0.088s SERVER Microsoft.AspNetCore.Server.Kestrel - Trace: Connection id "0HM5M1MLM5J5K:0" sending Data frame for stream ID 0 with length 17.
 0.089s SERVER Microsoft.AspNetCore.Server.Kestrel - Trace: Connection id "0HM5M1MLM5J5K:0" sending Headers frame for stream ID 0 with length 17.
 0.089s SERVER Microsoft.AspNetCore.Hosting.Diagnostics - Information: Request finished HTTP/3 POST https://localhost:50010/greet.Greeter/SayHello application/grpc - - 200 - application/grpc 30.1936ms
 0.089s SERVER Microsoft.AspNetCore.Server.Kestrel.Transport.MsQuic - Debug: Stream id "0HM5M1MLM5J5K:0" shutting down writes, exception: "The Quic transport's send loop completed gracefully.".
 Microsoft.AspNetCore.Connections.ConnectionAbortedException: The Quic transport's send loop completed gracefully.
 0.090s Grpc.Net.Client.Internal.GrpcCall - Trace: Response headers received.
 0.096s Grpc.Net.Client.Internal.GrpcCall - Debug: Reading message.
 0.099s Grpc.Net.Client.Internal.GrpcCall - Trace: Deserializing 12 byte message to 'Greet.HelloReply'.
 0.100s Grpc.Net.Client.Internal.GrpcCall - Trace: Received message.
 0.103s Grpc.Net.Client.Internal.GrpcCall - Debug: Finished gRPC call.
 0.126s GrpcTestContext - Information: Finishing ConnectionTests.Http3_Grpc
```

**Comment by jkotalik** [comment]
I don't believe it's the same exception. We always write that (https://github.com/dotnet/aspnetcore/blob/master/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicStreamContext.cs#L329) when writes are done for a stream.

The log that this issue is for:
```
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.MsQuic[7]
      Stream id "0HM5MANOQV052:3" shutting down writes, exception: "Could not send data to peer. Error Code: INVALID_STATE".
      Microsoft.AspNetCore.Connections.ConnectionResetException: Could not send data to peer. Error Code: INVALID_STATE
       ---> System.Net.Quic.QuicException: Could not send data to peer. Error Code: INVALID_STATE
         at System.Net.Quic.Implementations.MsQuic.Internal.QuicExceptionHelpers.ThrowIfFailed(UInt32 status, String message, Exception innerException)
         at System.Net.Quic.Implementations.MsQuic.MsQuicStream.SendReadOnlySequenceAsync(ReadOnlySequence`1 buffers, QUIC_SEND_FLAG flags)
         at System.Net.Quic.Implementations.MsQuic.MsQuicStream.WriteAsync(ReadOnlySequence`1 buffers, Boolean endStream, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Experimental.Quic.Internal.QuicStreamContext.ProcessSends() in C:\Users\jukotali\code\aspnetcore2\src\Servers\Kestrel\Transport.Quic\src\Internal\QuicStreamContext.cs:line 285
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Experimental.Quic.Internal.QuicStreamContext.DoSend() in C:\Users\jukotali\code\aspnetcore2\src\Servers\Kestrel\Transport.Quic\src\Internal\QuicStreamContext.cs:line 242
         --- End of inner exception stack trace ---
dbug: Microsoft.AspNetCore.Server.Kestrel[2]
```

**Comment by JamesNK** [comment]
Runtime issue - https://github.com/dotnet/runtime/issues/46542

**Comment by Tratcher** [comment]
Similar trace:
```
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Quic[1]
      Connection id "0HMA8KUTMNP7H" accepted.
dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[39]
      Connection id "0HMA8KUTMNP7H" accepted.
dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[1]
      Connection id "0HMA8KUTMNP7H" started.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Quic[3]
      Stream id "0HMA8KUTMNP7H:3" type Unidirectional connected.
dbug: Microsoft.AspNetCore.Server.Kestrel.Core.Internal.LoggingConnectionMiddleware[0]
      WriteAsync[1]
      00                                                 .
dbug: Microsoft.AspNetCore.Server.Kestrel.Core.Internal.LoggingConnectionMiddleware[0]
      WriteAsync[7]
      04 05 06 80 00 80 00                               .......
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Quic[2]
      Stream id "0HMA8KUTMNP7H:2" type Unidirectional accepted.
dbug: Microsoft.AspNetCore.Server.Kestrel.Core.Internal.LoggingConnectionMiddleware[0]
      ReadAsync[8]
      00 04 05 06 80 01 00 00                            ........
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Quic[2]
      Stream id "0HMA8KUTMNP7H:0" type Bidirectional accepted.
trce: Microsoft.AspNetCore.Server.Kestrel.Http3[46]
      Connection id "0HMA8KUTMNP7H:2" received SETTINGS frame for stream ID 2 with length 5.
dbug: Microsoft.AspNetCore.Server.Kestrel.Core.Internal.LoggingConnectionMiddleware[0]
      ReadAsync[48]
      01 2E 00 00 D1 D7 50 0E  6C 6F 63 61 6C 68 6F 73   ....ÑxP. localhos
      74 3A 35 35 35 37 C1 37  01 61 6C 74 2D 75 73 65   t:5557A7 .alt-use
      64 0E 6C 6F 63 61 6C 68  6F 73 74 3A 35 35 35 37   d.localh ost:5557
trce: Microsoft.AspNetCore.Server.Kestrel.Http3[46]
      Connection id "0HMA8KUTMNP7H:0" received HEADERS frame for stream ID 0 with length 46.
dbug: Microsoft.AspNetCore.Server.Kestrel.Core.Internal.LoggingConnectionMiddleware[0]
      ReadAsync[0]
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/3 GET https://localhost:5557/ - -
dbug: Microsoft.AspNetCore.Server.Kestrel[25]
      Connection id "0HMA8KUTMNP7H:0", Request id "0HMA8KUTMNP7H:0": started reading request body.
dbug: Microsoft.AspNetCore.Server.Kestrel[26]
      Connection id "0HMA8KUTMNP7H:0", Request id "0HMA8KUTMNP7H:0": done reading request body.
trce: Microsoft.AspNetCore.Server.Kestrel.Http3[47]
      Connection id "0HMA8KUTMNP7H:0" sending HEADERS frame for stream ID 0 with length 62.
trce: Microsoft.AspNetCore.Server.Kestrel.Http3[47]
      Connection id "0HMA8KUTMNP7H:0" sending DATA frame for stream ID 0 with length 19.
dbug: Microsoft.AspNetCore.Server.Kestrel.Core.Internal.LoggingConnectionMiddleware[0]
      WriteAsync[85]
      01 3E 00 00 D9 34 64 61  74 65 1D 46 72 69 2C 20   .>..U4da te.Fri,
      31 36 20 4A 75 6C 20 32  30 32 31 20 32 32 3A 31   16 Jul 2 021 22:1
      39 3A 30 38 20 47 4D 54  36 73 65 72 76 65 72 07   9:08 GMT 6server.
      4B 65 73 74 72 65 6C 34  74 65 73 74 03 66 6F 6F   Kestrel4 test.foo
      00 13 48 65 6C 6C 6F 20  57 6F 72 6C 64 21 20 48   ..Hello  World! H
      54 54 50 2F 33                                     TTP/3
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/3 GET https://localhost:5557/ - - - 200 - - 33.8975ms
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Quic[10]
      Stream id "0HMA8KUTMNP7H:0" shutting down writes because: "The QUIC transport's send loop completed gracefully.".
dbug: Microsoft.AspNetCore.Server.Kestrel.Http3[44]
      Connection id "0HMA8KUTMNP7H" is closed. The last processed stream ID was 0.
trce: Microsoft.AspNetCore.Server.Kestrel.Http3[47]
      Connection id "(null)" sending GO_AWAY frame for stream ID 3 with length 1.
dbug: Microsoft.AspNetCore.Server.Kestrel.Core.Internal.LoggingConnectionMiddleware[0]
      WriteAsync[3]
      07 01 00                                           ...
dbug: Microsoft.AspNetCore.Server.Kestrel.Http3[45]
      Trace id "0HMA8KUTMNP7H:2": HTTP/3 stream error "0". An abort is being sent to the stream.
      Microsoft.AspNetCore.Connections.ConnectionAbortedException: The HTTP/3 connection faulted.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Quic[12]
      Stream id "0HMA8KUTMNP7H:2" aborted by application because: "The HTTP/3 connection faulted.".
dbug: Microsoft.AspNetCore.Server.Kestrel.Http3[45]
      Trace id "(null)": HTTP/3 stream error "0". An abort is being sent to the stream.
      Microsoft.AspNetCore.Connections.ConnectionAbortedException: The HTTP/3 connection faulted.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Quic[12]
      Stream id "0HMA8KUTMNP7H:3" aborted by application because: "The HTTP/3 connection faulted.".
dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[2]
      Connection id "0HMA8KUTMNP7H" stopped.
```
