### ISSUE TITLE
DpapiXmlDecryptor - An exception occurred while trying to decrypt the element.

### ISSUE THREAD

**Issue by vkirienko** [dotnet/aspnetcore#29128]
### Describe the bug
We have a pretty much the same issue as described in https://github.com/dotnet/aspnetcore/issues/9447. Two of our .NET Core 3.1.1 applications running in IIS with hostingModel="InProcess" started to throw errors below when app pool gets recycled and application restarts.

It looks like it started to happen right after the following patches were installed on our production server. Unfortunately problem show up only in our production environments even if all environments are kept the same in terms or patches.

-----------

Category: Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor
EventId: 43

An exception occurred while trying to decrypt the element.

Exception: 
System.Security.Cryptography.CryptographicException: Error occurred during a cryptographic operation.
   at Microsoft.AspNetCore.DataProtection.Cng.DpapiSecretSerializerHelper.UnprotectWithDpapiCore(Byte* pbProtectedData, UInt32 cbProtectedData, Byte* pbOptionalEntropy, UInt32 cbOptionalEntropy)
   at Microsoft.AspNetCore.DataProtection.Cng.DpapiSecretSerializerHelper.UnprotectWithDpapi(Byte[] protectedSecret)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor.Decrypt(XElement encryptedElement)

-----------

Category: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager
EventId: 24

An exception occurred while processing the key element '<key id="9e609506-dcbd-4191-a937-bc514cf9f564" version="1" />'.

Exception: 
System.Security.Cryptography.CryptographicException: Error occurred during a cryptographic operation.
   at Microsoft.AspNetCore.DataProtection.Cng.DpapiSecretSerializerHelper.UnprotectWithDpapiCore(Byte* pbProtectedData, UInt32 cbProtectedData, Byte* pbOptionalEntropy, UInt32 cbOptionalEntropy)
   at Microsoft.AspNetCore.DataProtection.Cng.DpapiSecretSerializerHelper.UnprotectWithDpapi(Byte[] protectedSecret)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor.Decrypt(XElement encryptedElement)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.XmlEncryptionExtensions.DecryptElement(XElement element, IActivator activator)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.DeserializeDescriptorFromKeyElement(XElement keyElement)

----------

Category: Microsoft.AspNetCore.DataProtection.KeyManagement.DefaultKeyResolver
EventId: 12

Key {9e609506-dcbd-4191-a937-bc514cf9f564} is ineligible to be the default key because its CreateEncryptor method failed.

Exception:
System.Security.Cryptography.CryptographicException: Error occurred during a cryptographic operation.
   at Microsoft.AspNetCore.DataProtection.Cng.DpapiSecretSerializerHelper.UnprotectWithDpapiCore(Byte* pbProtectedData, UInt32 cbProtectedData, Byte* pbOptionalEntropy, UInt32 cbOptionalEntropy)
   at Microsoft.AspNetCore.DataProtection.Cng.DpapiSecretSerializerHelper.UnprotectWithDpapi(Byte[] protectedSecret)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor.Decrypt(XElement encryptedElement)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.XmlEncryptionExtensions.DecryptElement(XElement element, IActivator activator)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.DeserializeDescriptorFromKeyElement(XElement keyElement)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.DeferredKey.<>c__DisplayClass1_0.<GetLazyDescriptorDelegate>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyBase.get_Descriptor()
   at Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.CngGcmAuthenticatedEncryptorFactory.CreateEncryptorInstance(IKey key)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyBase.CreateEncryptor()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.DefaultKeyResolver.CanCreateAuthenticatedEncryptor(IKey key)

------------

.NET 3.5
https://support.microsoft.com/en-us/help/4578981/kb4578981 - Security Only Update for .NET Framework 3.5 for Windows 8.1 and Windows Server 2012 R2 (KB4578981)
https://support.microsoft.com/en-us/help/4569737/kb4569737 - Security Only Update for .NET Framework 3.5 for Windows 8.1 and Windows Server 2012 R2 (KB4569737)
https://support.microsoft.com/en-us/help/4565580/kb4565580 - Security Only Update for .NET Framework 3.5 for Windows 8.1 and Windows Server 2012 R2 (KB4565580)
https://support.microsoft.com/en-us/help/4578953/kb4578953 - Security and Quality Rollup for .NET Framework 3.5 for Windows 8.1, RT 8.1, and Windows Server 2012 R2 (KB4578953)

.NET 4.8
https://support.microsoft.com/en-us/help/4576489/kb4576489 - Security Only Update for .NET Framework 4.8 for Windows 8.1 and Windows Server 2012 R2 (KB4576489)
https://support.microsoft.com/en-us/help/4565588/kb4565588 - Security Only Update for .NET Framework 4.8 for Windows 8.1 and Windows Server 2012 R2 (KB4565588)
https://support.microsoft.com/en-us/help/4569732/kb4569732 - Security Only Update for .NET Framework 4.8 for Windows 8.1 and Windows Server 2012 R2 (KB4569732)
https://support.microsoft.com/en-us/help/4578989/kb4578989 - Security Only Update for .NET Framework 4.8 for Windows 8.1 and Windows Server 2012 R2 (KB4578989)
https://support.microsoft.com/en-us/help/4578976/kb4578976 - Security and Quality Rollup for .NET Framework 4.8 for Windows 8.1, RT 8.1, and Windows Server 2012 R2 (KB4578976)

### Further technical details
- ASP.NET Core version 

3.1.1

- Include the output of `dotnet --info`

It was not possible to find any installed .NET Core SDKs
Did you mean to run .NET Core SDK commands? Install a .NET Core SDK from:
      https://aka.ms/dotnet-download

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by blowdart** [comment]
@GrabYourPitchforks any ideas what might be going on?

**Comment by vkirienko** [comment]
What's interesting that there is no pattern related to number of errors per app pool recycle or what keys have problem.

![image](https://user-images.githubusercontent.com/12551258/103965323-79923280-512b-11eb-9134-0f2d5bbb801a.png)

**Comment by mkArtakMSFT** [comment]
Ping @GrabYourPitchforks

**Comment by GrabYourPitchforks** [comment]
These errors are coming from the Win32 API `CryptUnprotectData`. I wonder if the IIS application pool worker identity has been reset or if the application pool is now configured _not_ to load the user profile? (If there's no user profile, there's no place for DPAPI to store the key material.)

For historical context, in a traditional Full Framework ASPNET app, the expectation is that the IIS worker process does not load the user profile. Instead, the IIS orchestration service detects that the app pool is configured to load aspnet, it carves out a special section of the registry to allow aspnet to hold its key material, and System.Web uses that registry key instead of the user profile to store the auto-generated `<machineKey>` element.

**Comment by vkirienko** [comment]
You guess is correct - application pool is configured not to load the user profile. But it strange that these errors showed up just recently.

**Comment by GrabYourPitchforks** [comment]
@vkirienko Did the identity of the application pool change recently? For instance, switching from NETWORK SERVICE to APP POOL IDENTITY (or vice versa)? If the app pool user account is set to "app pool identity", the identity is based on the name of the application pool. In that case, if the name of the app pool changes, the provisioning script will need to be rerun.

**Comment by vkirienko** [comment]
No, it did not change recently. It was our application service account from day one. Application pool name did not change as well.

**Comment by GrabYourPitchforks** [comment]
The DataProtection startup routine attempts to detect capabilities of the current hosting environment at startup ([see code](https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/DataProtection/DataProtection/src/KeyManagement/XmlKeyManager.cs#L490)) and will choose an appropriate encryption mechanism based on that. It will log something like "Using the user profile with DPAPI", "Using the user profile without DPAPI", or "Using registry path \[blah\] for key storage".

Can you let us know which of these it's writing to the log? You may have to turn on informational or verbose logging to see these messages.

**Comment by vkirienko** [comment]
```
Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: 2021-01-25 15:59:40.3371 INFO User profile is available. Using 'C:\Windows\system32\config\systemprofile\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository: 2021-01-25 15:59:40.3464 DEBUG Reading data from file 'C:\Windows\system32\config\systemprofile\AppData\Local\ASP.NET\DataProtection-Keys\key-0d8f0300-c301-48a7-bf94-b97d44f653d7.xml'.
... skip 50 similar lines
Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: 2021-01-25 15:59:40.3795 DEBUG Found key {0d8f0300-c301-48a7-bf94-b97d44f653d7}.
... skip 50 similar lines
Microsoft.AspNetCore.DataProtection.KeyManagement.DefaultKeyResolver: 2021-01-25 15:59:40.4092 DEBUG Considering key {8bc09e78-829b-4211-a4ed-e00d04e9469b} with expiration date 2021-04-25 20:58:35Z as default key.
Microsoft.AspNetCore.DataProtection.TypeForwardingActivator: 2021-01-25 15:59:40.4092 DEBUG Forwarded activator type request from Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor, Microsoft.AspNetCore.DataProtection, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 to Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor, Microsoft.AspNetCore.DataProtection, Culture=neutral, PublicKeyToken=adb9793829ddae60
Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor: 2021-01-25 15:59:40.4092 DEBUG Decrypting secret element using Windows DPAPI.
Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor: 2021-01-25 15:59:40.4424 ERROR An exception occurred while trying to decrypt the element.
Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: 2021-01-25 15:59:40.6070 ERROR An exception occurred while processing the key element '<key id="8bc09e78-829b-4211-a4ed-e00d04e9469b" version="1" />'.
Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: 2021-01-25 15:59:40.6176 TRACE An exception occurred while processing the key element '<key id="8bc09e78-829b-4211-a4ed-e00d04e9469b" version="1">
  <creationDate>2021-01-25T20:58:35.9194222Z</creationDate>
  <activationDate>2021-01-25T20:58:35.6384352Z</activationDate>
  <expirationDate>2021-04-25T20:58:35.6384352Z</expirationDate>
  <descriptor deserializerType="Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60">
    <descriptor>
      <encryption algorithm="AES_256_CBC" />
      <validation algorithm="HMACSHA256" />
      <encryptedSecret decryptorType="Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor, Microsoft.AspNetCore.DataProtection, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" xmlns="http://schemas.asp.net/2015/03/dataProtection">
        <encryptedKey xmlns="">
          <!-- This key is encrypted with Windows DPAPI. -->
          <value>...del...</value>
        </encryptedKey>
      </encryptedSecret>
    </descriptor>
  </descriptor>
</key>'.
Microsoft.AspNetCore.DataProtection.KeyManagement.DefaultKeyResolver: 2021-01-25 15:59:40.6176 WARN Key {8bc09e78-829b-4211-a4ed-e00d04e9469b} is ineligible to be the default key because its CreateEncryptor method failed.


```

**Comment by GrabYourPitchforks** [comment]
Is your app pool configured to run as SYSTEM? And was this intentional? I don't see why aspnet would be trying to load the `%SYSTEM32%\config\systemprofile\` directory otherwise.

**Comment by vkirienko** [comment]
App pools configured under service accounts.

![image](https://user-images.githubusercontent.com/12551258/105792238-37ebef00-5f55-11eb-96bc-1253797a64c8.png)

**Comment by SatishPasunuti** [comment]
Hello, I have the same issue for couple of our applications. When can we expect a fix for it?.

**Comment by Henadz** [comment]
Hello
We also have the same issue with our applications. Unfortunately, the issue reproduced only on the customer side and we have not full access to the environment. One application is hosted behind IIS, second is a self-hosted application.

**Comment by vkirienko** [comment]
**Update**

Issue is still reproducible after we migrated all apps to .NET Core 5. Good news it is now reproducible on our DEV box so it will be much easier to debug.

**Short Investigation Results**

There are no files matching **MKID** in these folders:

    C:\Windows\System32\Microsoft\Protect
    C:\Users\VKYRYYENKO\appdata\roaming\microsoft\protect

**Long Investigation Results**

1. Stopped IIS
2. Deleted all files from 
    C:\Windows\System32\config\systemprofile\AppData\Local\ASP.NET\DataProtection-Keys
3. Started IIS
4. Got three XML files generated. 
Two of them had same MKID:
![image](https://user-images.githubusercontent.com/12551258/121368015-c2335f00-c908-11eb-96c7-14344d4d9a25.png)
One had different:
![image](https://user-images.githubusercontent.com/12551258/121368122-d5dec580-c908-11eb-92c0-3784f2eac324.png)
5. Here are the attrib results:
![image](https://user-images.githubusercontent.com/12551258/121368392-0aeb1800-c909-11eb-8adb-996310093828.png)
![image](https://user-images.githubusercontent.com/12551258/121368526-222a0580-c909-11eb-8617-da51fdce80ec.png)

**Comment by omxitllc** [comment]
Did we arrive at any fix or still investigating?

**Comment by vruss** [comment]
Is there a known workaround for this? I'm also having the same issue.

**Comment by JoelLeach** [comment]
I was able to reproduce on my production server as follows:

- Two IIS App Pools, each setup to use a different user account.
- Load User Profile is false. As indicated in the log, this causes keys for both apps to be written to C:\Windows\system32\config\systemprofile\AppData\Local\ASP.NET\DataProtection-Keys.
- Recycle App Pool 1 and restart the app.  An error may or may not occur in the log.
- Recycle/restart App Pool 2.  An error now appears in the log.  It attempted to use the same key that was created by App Pool 1, but the decryption fails. I think this is because the key was created under a different user account.  App Pool 2 will create a new key due to the failure.
- Recycle/restart App Pool 1 again.  Error occurs because it now attempts to load the key created by App Pool 2, which again was encrypted under a different user account.
- The error appears intermittently depending on which account created the last key.

Either of these solutions work for me:

- Set Load User Profile to true.  This will cause the keys to be created in each user's profile folder rather than in the Windows folder.
- Set both App Pools to use the same user account.  The error may occur one more time after doing this depending on which user account created the last key.

**Comment by johanlab** [comment]
Are there any other workarounds for this issue?

Unfortunately cannot use workarounds mentioned by @JoelLeach above

- We cannot load the user account as it messes with the server locales and time zones - can't change it as it gets reapplied via enterprise GPO from different domain (trust relationship)
- We have to have 2 different accounts launching the app pools as access needs to be controlled separately

**Comment by olivier-voutat** [comment]
I have a similar problem. I create a little console application to encrypt and store the information in the environment variables.

My web api is supposed to read it and unprotect to use it.

Locally, no problem.

Deployed, exception on unproctect process...

**Comment by olivier-voutat** [comment]
Ok, found out. I need to run my console app as admin in the server (in fact I was doing this already in local, because it refused to do it with normal account) AND restart the server.
