### ISSUE TITLE
Sign in with Twitter - add an error message containing the error details from Twitter

### ISSUE THREAD

**Issue by Hona** [dotnet/aspnetcore#29136]
### Is your feature request related to a problem? Please describe.

I am trying to use the Microsoft.AspNetCore.Authentication.Twitter package to allow login via Twitter on my site. However I am getting an error 403 forbidden. Specifically [this code block](https://github.com/dotnet/aspnetcore/blob/c3f9b9e1e88467e96fdcb715345cd6b5cc62f0b7/src/Security/Authentication/Twitter/src/TwitterHandler.cs#L256-L269)

### Describe the solution you'd like
The logs are not detailed on what the error is, so an additional exception message containing twitters error response would be great. Twitter provides documentation of an example error response [here](https://developer.twitter.com/en/docs/apps/callback-urls) under the `Error Example` header. 

### Additional context
The error message I get is:
```
[03:09:01 ERR] Connection id "0HM5IN6A9OIUT", Request id "0HM5IN6A9OIUT:00000002": An unhandled exception was thrown by the application.
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.AspNetCore.Authentication.Twitter.TwitterHandler.ObtainRequestTokenAsync(String callBackUri, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.Twitter.TwitterHandler.HandleChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Mvc.ChallengeResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|27_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

This makes it really hard to figure out the issue - have I not setup the callback URL correctly? Is my forwarded HTTPS protocol not working and it detects it as HTTP?

**Comment by Hona** [comment]
Even though this is not triaged, is it fine for me to submit a PR for this?

**Comment by Tratcher** [comment]
@Hona sure, go ahead.

**Comment by blowdart** [comment]
Oh yes, please, go for it. Me putting into Next Sprint Planning is really saying "We ought to do this"
