### ISSUE TITLE
Injecting IJSRuntime into RCL class results in a null

### ISSUE THREAD

**Issue by ScottKane** [dotnet/aspnetcore#29154]
This is using Blazor WASM.

Injecting `IJSRuntime` into RCL class results in a null even though it exists in the service collection and works if I use `@inject IJSRuntime _js` from a razor file.

The following class exists in the RCL:
```c#
public class JsInterop
{
    private static IJSRuntime _js;
    public JsInterop(IJSRuntime js) => _js = js;

    public static async ValueTask SetGridDataAsync(string id, object data)
    {
        await _js.InvokeVoidAsync(
            "jsInterop.setGridData",
            id,
            JsonSerializer.Serialize(data));
    }
}
```
It is registered on the Client and Server via an extension method:
```c#
services.AddSingleton<JsInterop>();
```

It is called from a component that also exists in the RCL:
```razor
@typeparam TItem

<h1>Data Grid</h1>

<fast-data-grid id="@_id"></fast-data-grid>

@code {
    [Parameter] public IList<TItem> Items { get; set; }

    private string _id;

    protected override async Task OnInitializedAsync()
    {
        _id = $"{Items.FirstOrDefault().GetType().Name.ToLower()}s";
        await JsInterop.SetGridDataAsync(_id, Items);
    }
}
```

I get the following in the browser console:
```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Value cannot be null. (Parameter 'jsRuntime')
System.ArgumentNullException: Value cannot be null. (Parameter 'jsRuntime')
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Project.Components.JsInterop.SetGridDataAsync(String id, Object data) in D:\Project\Project.Components\JsInterop.cs:line 24
   at Project.Components.FastTable`1.<OnInitializedAsync>d__6[[Project.Client.Order, Project.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext() in D:\Project\Project.Components\FastTable.razor:line 15
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

If I change to the following, it works however I don't want to have to provide the IJSRuntime from every interop calling component:
```c#
public class JsInterop
{
    public static async ValueTask SetGridDataAsync(IJSRuntime js, string id, object data)
    {
        await js.InvokeVoidAsync(
            "jsInterop.setGridData",
            id,
            JsonSerializer.Serialize(data));
    }
}
```

```razor
@typeparam TItem
@inject IJSRuntime _js

<h1>Data Grid</h1>

<fast-data-grid id="@_id"></fast-data-grid>

@code {
    [Parameter] public IList<TItem> Items { get; set; }

    private string _id;

    protected override async Task OnInitializedAsync()
    {
        _id = $"{Items.FirstOrDefault().GetType().Name.ToLower()}s";
        await JsInterop.SetGridDataAsync(_js, _id, Items);
    }
}
```

- ASP.NET Core version: 5.0.100
```
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version :  VS 2019 Community 16.8.1

**Comment by ScottKane** [comment]
I think the issue is that the lifetime of my JsInterop class is singleton and IJSRuntime is scoped. How else am I supposed to have a singleton with static methods I can call without having to pass a scoped IJSRuntime from the calling component? Because even if I make my JsInterop Transient/Scoped, I don't want to have to DI it into everything just to create a scope on the runtime.

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.
