### ISSUE TITLE
 visual studio 2019 16.8.3 crash and close when i open a asp.net core  cshtml view 

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#29165]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/visual-studio-2019-1683-crash-and-clos/1286013)._

---
[severity:It's more difficult to complete my work]
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Resources.ResourceReader.LoadString(Int32)
   at System.Resources.RuntimeResourceSet.GetObject(System.String, Boolean, Boolean)
   at System.Resources.RuntimeResourceSet.GetString(System.String, Boolean)
   at System.Resources.ResourceManager.GetString(System.String, System.Globalization.CultureInfo)
   at Microsoft.AspNetCore.Razor.Language.Legacy.CSharpCodeParser+<>c.<.cctor>b__100_0(Microsoft.AspNetCore.Razor.Language.IDirectiveDescriptorBuilder)
   at Microsoft.AspNetCore.Razor.Language.DirectiveDescriptor.CreateDirective(System.String, Microsoft.AspNetCore.Razor.Language.DirectiveKind, System.Action`1<Microsoft.AspNetCore.Razor.Language.IDirectiveDescriptorBuilder>)
   at Microsoft.AspNetCore.Razor.Language.Legacy.CSharpCodeParser.. cctor()

Exception Info: System.TypeInitializationException
   at Microsoft.AspNetCore.Razor.Language.Legacy.CSharpCodeParser.. ctor(System.Collections.Generic.IEnumerable`1<Microsoft.AspNetCore.Razor.Language.DirectiveDescriptor>, Microsoft.AspNetCore.Razor.Language.Legacy.ParserContext)
   at Microsoft.AspNetCore.Razor.Language.Legacy.RazorParser.Parse(Microsoft.AspNetCore.Razor.Language.RazorSourceDocument)
   at Microsoft.AspNetCore.Razor.Language.RazorSyntaxTree.Parse(Microsoft.AspNetCore.Razor.Language.RazorSourceDocument, Microsoft.AspNetCore.Razor.Language.RazorParserOptions)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorParsingPhase.ExecuteCore(Microsoft.AspNetCore.Razor.Language.RazorCodeDocument)
   at Microsoft.AspNetCore.Razor.Language.RazorEnginePhaseBase.Execute(Microsoft.AspNetCore.Razor.Language.RazorCodeDocument)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorEngine.Process(Microsoft.AspNetCore.Razor.Language.RazorCodeDocument)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorProjectEngine.ProcessCore(Microsoft.AspNetCore.Razor.Language.RazorCodeDocument)
   at Microsoft.AspNetCore.Razor.Language.RazorProjectEngine.ProcessDesignTime(Microsoft.AspNetCore.Razor.Language.RazorProjectItem)
   at Microsoft.VisualStudio.Editor.Razor.BackgroundParser+BackgroundThread.WorkerLoop()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

---
#### Feedback Bot on 12/13/2020, 06:18 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
