### ISSUE TITLE
Blazor WebAssembly template project throws errors after publishing to Azure

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#29162]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Blazor-WebAssembly-template-project-thro/1296737)._

---
<p>I created a Blazor WebAssembly solution from the template (VS 2019, target framework is .Net 5.0) and without any changes tried to run it. Locally it works perfectly: service worker is registered, &quot;fetchdata&quot; page is shown.</p> <p>But when I publish this solution to Azure app service from Visual Studio, in any browser service worker is not registered</p><pre>Uncaught TypeError: navigator.serviceWorker is undefined
</pre><p> and &quot;fetchdata&quot; page doesn't work:</p><pre>crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: ExpectedStartOfValueNotFound, &lt; Path: $ | LineNumber: 0 | BytePositionInLine: 0.
System.Text.Json.JsonException: ExpectedStartOfValueNotFound, &lt; Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---&gt; System.Text.Json.JsonReaderException: ExpectedStartOfValueNotFound, &lt; LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader&amp; json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1[[BlazorPWATest.Shared.WeatherForecast[], BlazorPWATest.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]. ReadCore(Utf8JsonReader&amp; reader, JsonSerializerOptions options, ReadStack&amp; state)
   Exception_EndOfInnerExceptionStack
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack&amp; state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1[[BlazorPWATest.Shared.WeatherForecast[], BlazorPWATest.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]. ReadCore(Utf8JsonReader&amp; reader, JsonSerializerOptions options, ReadStack&amp; state)
   at System.Text.Json.JsonSerializer.ReadCore[WeatherForecast[]](JsonConverter jsonConverter, Utf8JsonReader&amp; reader, JsonSerializerOptions options, ReadStack&amp; state)
   at System.Text.Json.JsonSerializer.ReadCore[WeatherForecast[]](JsonReaderState&amp; readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack&amp; state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.&lt;ReadAsync&gt;d__20`1[[BlazorPWATest.Shared.WeatherForecast[], BlazorPWATest.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]. MoveNext()
   at System.Net.Http.Json.HttpContentJsonExtensions.&lt;ReadFromJsonAsyncCore&gt;d__3`1[[BlazorPWATest.Shared.WeatherForecast[], BlazorPWATest.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]. MoveNext()
   at System.Net.Http.Json.HttpClientJsonExtensions.&lt;GetFromJsonAsyncCore&gt;d__9`1[[BlazorPWATest.Shared.WeatherForecast[], BlazorPWATest.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]. MoveNext()
   at BlazorPWATest.Client.Pages.FetchData.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
</pre>

---
#### Feedback Bot on 12/27/2020, 10:45 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
Thanks for contacting us.

This can be because you might be accessing the page over an insecure channel (HTTP) and service workers are not enabled in that context.
