### ISSUE TITLE
After i used AssemblyLoadContext.Resolving to load libraries,I got System.IO.FileLoadException: Could not load file or assembly with System.ArgumentException: The path is empty

### ISSUE THREAD

**Issue by 835718973** [dotnet/aspnetcore#29172]
```
AssemblyLoadContext.Default.Resolving += LibResolving;
 private static Assembly LibResolving(AssemblyLoadContext context, AssemblyName assemblyName)
        {
            Assembly result = null;
            var path = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "libs", $"{assemblyName.Name}.dll");
            if (File.Exists(path))
            {
                using (var fs = File.OpenRead(path))
                {
                    result = context.LoadFromStream(fs);
                }
            }
            return result;
        }
```

For Most Dll it works good,but for some like Microsoft.AspNetCore.Http.Features,it failed and I don't know what to continue.

Unhandled exception. System.AggregateException: One or more errors occurred. (Could not load file or assembly 'Microsoft.AspNetCore.Http.Features, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (0x80131621))
 ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNetCore.Http.Features, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (0x80131621)
File name: 'Microsoft.AspNetCore.Http.Features, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at System.Reflection.Assembly.get_ExportedTypes()
   at Emacro.Web.Startup.<>c__DisplayClass19_0.<ConfigureContainer>b__1(Assembly assembly) in D:\WorkSpace\VS工作区\鸿盈\EmacroWeb\EmacroWeb\Commons\Emacro.Web\Startup.cs:line 444
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()

**Comment by pranavkm** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. We recommend posting your questions to StackOverflow using the asp.net-core tag to reach a wider audience.
