### ISSUE TITLE
HTTP/3: Frame logging, stream ID is sometimes 0

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#29204]
Frame logging added with https://github.com/dotnet/aspnetcore/pull/29083

I noticed that stream ID is sometimes 0.

Worked:
> Microsoft.AspNetCore.Server.Kestrel - Trace: Connection id "0HM5M1MLM5J5K:2" received Settings frame for stream ID 2 with length 5.

Failed:
> Microsoft.AspNetCore.Server.Kestrel - Trace: Connection id "0HM5M1MLM5J5K:0" received Headers frame for stream ID 0 with length 231.

`IStreamIdFeature` is being used. Does it only work when reading with the control stream? How do you get the stream ID for request streams?
```
 0.000s GrpcTestContext - Information: Starting ConnectionTests.Http3_Grpc
 0.024s Grpc.Net.Client.Internal.GrpcCall - Debug: Starting gRPC call. Method type: 'Unary', URI: 'https://localhost:50010/greet.Greeter/SayHello'.
 0.036s SERVER Microsoft.AspNetCore.Server.Kestrel.Transport.MsQuic - Debug: Connection id "0HM5M1MLM5J5K" accepted.
 0.037s SERVER Microsoft.AspNetCore.Server.Kestrel - Debug: Connection id "0HM5M1MLM5J5K" accepted.
 0.037s SERVER Microsoft.AspNetCore.Server.Kestrel - Debug: Connection id "0HM5M1MLM5J5K" started.
 0.039s SERVER Microsoft.AspNetCore.Server.Kestrel - Trace: Connection id "0HM5M1MLM5J5K:2" received Settings frame for stream ID 2 with length 5.
 0.045s Grpc.Net.Client.Internal.GrpcCall - Debug: Sending message.
 0.053s Grpc.Net.Client.Internal.GrpcCall - Trace: Serialized 'Greet.HelloRequest' to 6 byte message.
 0.058s SERVER Microsoft.AspNetCore.Server.Kestrel - Trace: Connection id "0HM5M1MLM5J5K:0" received Headers frame for stream ID 0 with length 231.
 0.058s SERVER Microsoft.AspNetCore.Server.Kestrel - Trace: Connection id "0HM5M1MLM5J5K:0" received Data frame for stream ID 0 with length 11.
 0.059s SERVER Microsoft.AspNetCore.Hosting.Diagnostics - Information: Request starting HTTP/3 POST https://localhost:50010/greet.Greeter/SayHello application/grpc -
 0.060s Grpc.Net.Client.Internal.GrpcCall - Trace: Message sent.
 0.062s SERVER Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware - Debug: Request matched endpoint 'gRPC - /greet.Greeter/SayHello'
 0.062s SERVER Microsoft.AspNetCore.Routing.EndpointMiddleware - Information: Executing endpoint 'gRPC - /greet.Greeter/SayHello'
 0.070s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Debug: Reading message.
 0.070s SERVER Microsoft.AspNetCore.Server.Kestrel - Debug: Connection id "0HM5M1MLM5J5K:0", Request id "0HM5M1MLM5J5K:0": started reading request body.
 0.070s SERVER Microsoft.AspNetCore.Server.Kestrel - Debug: Connection id "0HM5M1MLM5J5K:0", Request id "0HM5M1MLM5J5K:0": done reading request body.
 0.073s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Trace: Deserializing 6 byte message to 'Greet.HelloRequest'.
 0.079s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Trace: Received message.
 0.082s SERVER FunctionalTestsWebsite.Services.GreeterService - Information: Sending hello to John
 0.083s SERVER Microsoft.AspNetCore.Server.Kestrel - Trace: Connection id "0HM5M1MLM5J5K:0" sending Headers frame for stream ID 0 with length 84.
 0.083s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Debug: Sending message.
 0.086s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Trace: Serialized 'Greet.HelloReply' to 12 byte message.
 0.086s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Trace: Message sent.
 0.088s SERVER Microsoft.AspNetCore.Routing.EndpointMiddleware - Information: Executed endpoint 'gRPC - /greet.Greeter/SayHello'
 0.088s SERVER Microsoft.AspNetCore.Server.Kestrel - Trace: Connection id "0HM5M1MLM5J5K:0" sending Data frame for stream ID 0 with length 17.
 0.089s SERVER Microsoft.AspNetCore.Server.Kestrel - Trace: Connection id "0HM5M1MLM5J5K:0" sending Headers frame for stream ID 0 with length 17.
 0.089s SERVER Microsoft.AspNetCore.Hosting.Diagnostics - Information: Request finished HTTP/3 POST https://localhost:50010/greet.Greeter/SayHello application/grpc - - 200 - application/grpc 30.1936ms
 0.089s SERVER Microsoft.AspNetCore.Server.Kestrel.Transport.MsQuic - Debug: Stream id "0HM5M1MLM5J5K:0" shutting down writes, exception: "The Quic transport's send loop completed gracefully.".
 Microsoft.AspNetCore.Connections.ConnectionAbortedException: The Quic transport's send loop completed gracefully.
 0.090s Grpc.Net.Client.Internal.GrpcCall - Trace: Response headers received.
 0.096s Grpc.Net.Client.Internal.GrpcCall - Debug: Reading message.
 0.099s Grpc.Net.Client.Internal.GrpcCall - Trace: Deserializing 12 byte message to 'Greet.HelloReply'.
 0.100s Grpc.Net.Client.Internal.GrpcCall - Trace: Received message.
 0.103s Grpc.Net.Client.Internal.GrpcCall - Debug: Finished gRPC call.
 0.126s GrpcTestContext - Information: Finishing ConnectionTests.Http3_Grpc
```

**Comment by JamesNK** [comment]
Spec says ID can start at zero - https://tools.ietf.org/id/draft-ietf-quic-transport-24.html#rfc.section.2.1

Also, parallel requests from a client cause the ID to report non-zero values.

```
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.MsQuic[4]
      Connection id "0HM5MFAIRC3UN" accepted.
dbug: Microsoft.AspNetCore.Server.Kestrel[39]
      Connection id "0HM5MFAIRC3UN" accepted.
dbug: Microsoft.AspNetCore.Server.Kestrel[1]
      Connection id "0HM5MFAIRC3UN" started.
trce: Microsoft.AspNetCore.Server.Kestrel[46]
      Connection id "0HM5MFAIRC3UN:2" received Settings frame for stream ID 2 with length 5.
trce: Microsoft.AspNetCore.Server.Kestrel[46]
      Connection id "0HM5MFAIRC3UN:0" received Headers frame for stream ID 0 with length 46.
trce: Microsoft.AspNetCore.Server.Kestrel[46]
      Connection id "0HM5MFAIRC3UN:4" received Headers frame for stream ID 4 with length 46.
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/3 GET https://localhost:5557/ - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/3 GET https://localhost:5557/ - -
dbug: Microsoft.AspNetCore.Server.Kestrel[25]
      Connection id "0HM5MFAIRC3UN:0", Request id "0HM5MFAIRC3UN:0": started reading request body.
dbug: Microsoft.AspNetCore.Server.Kestrel[25]
      Connection id "0HM5MFAIRC3UN:4", Request id "0HM5MFAIRC3UN:4": started reading request body.
dbug: Microsoft.AspNetCore.Server.Kestrel[26]
      Connection id "0HM5MFAIRC3UN:0", Request id "0HM5MFAIRC3UN:0": done reading request body.
dbug: Microsoft.AspNetCore.Server.Kestrel[26]
      Connection id "0HM5MFAIRC3UN:4", Request id "0HM5MFAIRC3UN:4": done reading request body.
trce: Microsoft.AspNetCore.Server.Kestrel[47]
      Connection id "0HM5MFAIRC3UN:4" sending Headers frame for stream ID 4 with length 62.
trce: Microsoft.AspNetCore.Server.Kestrel[47]
      Connection id "0HM5MFAIRC3UN:0" sending Headers frame for stream ID 0 with length 62.
trce: Microsoft.AspNetCore.Server.Kestrel[47]
      Connection id "0HM5MFAIRC3UN:0" sending Data frame for stream ID 0 with length 19.
trce: Microsoft.AspNetCore.Server.Kestrel[47]
      Connection id "0HM5MFAIRC3UN:4" sending Data frame for stream ID 4 with length 19.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.MsQuic[7]
      Stream id "0HM5MFAIRC3UN:0" shutting down writes, exception: "The Quic transport's send loop completed gracefully.".
      Microsoft.AspNetCore.Connections.ConnectionAbortedException: The Quic transport's send loop completed gracefully.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.MsQuic[7]
      Stream id "0HM5MFAIRC3UN:4" shutting down writes, exception: "The Quic transport's send loop completed gracefully.".
      Microsoft.AspNetCore.Connections.ConnectionAbortedException: The Quic transport's send loop completed gracefully.
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/3 GET https://localhost:5557/ - - - 200 - - 1082.8675ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/3 GET https://localhost:5557/ - - - 200 - - 1082.8715ms
dbug: Microsoft.AspNetCore.Server.Kestrel[44]
      Connection id "0HM5MFAIRC3UN" is closed. The last processed stream ID was 4.
trce: Microsoft.AspNetCore.Server.Kestrel[47]
      Connection id "(null)" sending GoAway frame for stream ID 3 with length 1.
dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.MsQuic[7]
      Stream id "0HM5MFAIRC3UN:3" shutting down writes, exception: "Could not send data to peer. Error Code: INVALID_STATE".
      Microsoft.AspNetCore.Connections.ConnectionResetException: Could not send data to peer. Error Code: INVALID_STATE
       ---> System.Net.Quic.QuicException: Could not send data to peer. Error Code: INVALID_STATE
         at System.Net.Quic.Implementations.MsQuic.Internal.QuicExceptionHelpers.ThrowIfFailed(UInt32 status, String message, Exception innerException)
         at System.Net.Quic.Implementations.MsQuic.MsQuicStream.SendReadOnlySequenceAsync(ReadOnlySequence`1 buffers, QUIC_SEND_FLAG flags)
         at System.Net.Quic.Implementations.MsQuic.MsQuicStream.WriteAsync(ReadOnlySequence`1 buffers, Boolean endStream, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Experimental.Quic.Internal.QuicStreamContext.ProcessSends() in C:\Development\Source\AspNetCore\src\Servers\Kestrel\Transport.Quic\src\Internal\QuicStreamContext.cs:line 285
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Experimental.Quic.Internal.QuicStreamContext.DoSend() in C:\Development\Source\AspNetCore\src\Servers\Kestrel\Transport.Quic\src\Internal\QuicStreamContext.cs:line 242
         --- End of inner exception stack trace ---
dbug: Microsoft.AspNetCore.Server.Kestrel[2]
      Connection id "0HM5MFAIRC3UN" stopped.
```
