### ISSUE TITLE
Encode cookies when setting RequestCookiesFeature.Cookie collection

### ISSUE THREAD

**Issue by MokhamedDakhraui** [dotnet/aspnetcore#29304]
### Describe the bug
Considering [IRequestCookiesFeature](https://github.com/dotnet/aspnetcore/blob/master/src/Http/Http.Features/src/IRequestCookiesFeature.cs#L14) signature I suppose it should be allowed to set cookie collection, however when I'd tried to assign `IRequestCookieCollection` to `RequestCookiesFeature.Cookie` exception was fired.

In the property getter values (and sometimes) keys of cookies is being decoded with [RequestCookieCollection.Parse](https://github.com/dotnet/aspnetcore/blob/master/src/Http/Http/src/Features/RequestCookiesFeature.cs#L78), but in the setter values added to cookie header [as is](https://github.com/dotnet/aspnetcore/blob/master/src/Http/Http/src/Features/RequestCookiesFeature.cs#L98) (also name of variable `_parsedValues` suggests that data isn't encoded).

I attempted to encode cookies values in my `IRequestCookieCollection` implementation. Predictably, unfortunate side effect was that cookies in context became encoded.

### To Reproduce
- Make sure to have cookie with special symbols (used cookie with value `{"}`)
- Run:
  ```csharp
  HttpContext.Request.Cookies = HttpContext.Request.Cookies;
  ```

### Exceptions
```
System.ArgumentException: Invalid cookie value: {"} (Parameter 'value')
   at Microsoft.Net.Http.Headers.CookieHeaderValue.CheckValueFormat(StringSegment value, String parameterName)
   at Microsoft.Net.Http.Headers.CookieHeaderValue..ctor(StringSegment name, StringSegment value)
   at Microsoft.AspNetCore.Http.Features.RequestCookiesFeature.set_Cookies(IRequestCookieCollection value)
   at Microsoft.AspNetCore.Http.DefaultHttpRequest.set_Cookies(IRequestCookieCollection value)
   at WidgetSite.Filters.CookielessAntiforgeryFilter.InternalCookielessAntiforgeryFilter.OnAuthorizationAsync(AuthorizationFilterContext context) in C:\Projects\MTS.Money.Git\MTS.Money\WidgetSite\Helpers\CookielessAntiforgeryFilter.cs:line 35
```

### Further technical details
- ASP.NET Core version 3.1.10
- `dotnet --info` output:
    ```
    .NET SDK (reflecting any global.json):
     Version:   5.0.101
     Commit:    d05174dc5a
    
    Runtime Environment:
     OS Name:     Windows
     OS Version:  10.0.19042
     OS Platform: Windows
     RID:         win10-x64
     Base Path:   C:\Program Files\dotnet\sdk\5.0.101\
    
    Host (useful for support):
      Version: 5.0.1
      Commit:  b02e13abab
    
    .NET SDKs installed:
      3.1.200 [C:\Program Files\dotnet\sdk]
      3.1.401 [C:\Program Files\dotnet\sdk]
      5.0.100 [C:\Program Files\dotnet\sdk]
      5.0.101 [C:\Program Files\dotnet\sdk]
    
    .NET runtimes installed:
      Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
      Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    
    To install additional .NET runtimes or SDKs:
      https://aka.ms/dotnet-download
    ```
- IDE: VS 2019 v16.8.3

**Comment by blowdart** [comment]
Cookie names should not need to be encoded to if you conform to the cookie name rules (and there is no real standard for endowing illegal names). 

What is your business reason for wanting a cookie with illegal characters in it?

**Comment by MokhamedDakhraui** [comment]
Looking at implementation cookies always decoded ([Uri.UnescapeDataString](https://github.com/dotnet/aspnetcore/blob/4e439cadc59785d8dde083b04ca23a2ad3ea04d3/src/Http/Http/src/Internal/RequestCookieCollection.cs#L82)) from `Cookie` header. I'm not questioning this part. Rather it's setter looks inconsistent to me, since it doesn't make header the way it was (supposedly escaped or invalid).

In my case I tried to adjust request cookie dynamically in middleware (due to the browser is blocking some of them)

**Comment by Tratcher** [comment]
> due to the browser is blocking some of them

Can you expand on that? It's pretty uncommon to modify the cookies on the request, they represent client state.

You're right that the setter is inconsistent here.

Request Get:
https://github.com/dotnet/aspnetcore/blob/d459b4672dbc27aef75df68170907d1d95eac44d/src/Http/Http/src/Internal/RequestCookieCollection.cs#L81-L82
Request Set:
https://github.com/dotnet/aspnetcore/blob/d459b4672dbc27aef75df68170907d1d95eac44d/src/Http/Http/src/Features/RequestCookiesFeature.cs#L98
Response Append:
https://github.com/dotnet/aspnetcore/blob/d459b4672dbc27aef75df68170907d1d95eac44d/src/Http/Http/src/Internal/ResponseCookies.cs#L73-L75

RequestHeaders.Cookie and ResponseHeaders.SetCookie are also inconsistent in that they don't deal with escaping:
https://github.com/dotnet/aspnetcore/blob/d459b4672dbc27aef75df68170907d1d95eac44d/src/Http/Http.Extensions/src/RequestHeaders.cs#L173-L183
https://github.com/dotnet/aspnetcore/blob/d459b4672dbc27aef75df68170907d1d95eac44d/src/Http/Http.Extensions/src/ResponseHeaders.cs#L192-L202

**Comment by blowdart** [comment]
Request.Set probably should throw after parsing if possible, otherwise we're back to the mistakes we made in classic ASP.

**Comment by MokhamedDakhraui** [comment]
> Can you expand on that? It's pretty uncommon to modify the cookies on the request, they represent client state.

In case if origin of issue still relevant there it is.
After firefox enabled tracking protection cookies have been blocked for the site embeded in iframe. I tried to seamlessly restore several essential ones by setting them in middleware as a temporary solution.

**Comment by joshbouganim** [comment]
To add another use case, I am unit testing a middleware that reads a cookie that contains JSON.  In my unit test i mock the cookies using RequestCookiesFeature but this fails when i test the golden path where the cookie data contains a JSON structure.  i've tried pre-URL encoding the cookie text but it still fails.

i use this method to create the fake cookies. https://stackoverflow.com/a/63132794/411094

**Comment by Tratcher** [comment]
JSON uses multiple syntax characters that are invalid in cookie values.

**Comment by joshbouganim** [comment]
> JSON uses multiple syntax characters that are invalid in cookie values.

which is why i said i tried pre-url encoding them but that also fails.

`"{"TestKey":"TestValue"}" => "%7B%22TestKey%22%3A%22TestValue%22%7D"`

**Comment by strandman** [comment]
This bug is stopping me from using OData Batching:
https://github.com/OData/WebApi/blob/af2f67215eee1b5ac124c34394b8bf1dfb5ea1fb/src/Microsoft.AspNetCore.OData/Batch/ODataBatchReaderExtensions.cs#L267
