### ISSUE TITLE
Pressing A Key Within .razor File Pegs CPU 15-25% for ~20-25 Seconds

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#29500]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Pressing-A-Key-Within-razor-File-Pegs-C/1300669)._

---
[severity:It bothers me. A fix would be nice]
I've attached a recording for this.  This may be related to this issue:
https://developercommunity.visualstudio.com/content/problem/1270404/encountering-performance-issue-high-memory-utiliza.html

Which was dismissed due to JetBrains, but this does not seem to be the case.  I have captured a timeline of this in dotTrace, and it seems to be occuring in the `Microsoft.CodeAnalysis.Razor` namespace:

![OshY8Ih[1].png](https://aka.ms/dc/image?name=B783ff09f84134a118f64a4fe326fe9c1637453689366632072_OshY8Ih%5B1%5D.png&tid=783ff09f84134a118f64a4fe326fe9c1637453689366632072)

Additionally, worth noting that ReSharper is reporting 1.2-15GB of (managed) memory usage, while Task Manager is reporting 4-6GB of usage for the Visual Studio process.

---
#### DragonSpark on 1/4/2021, 09:52 AM: 

<p>I can confirm this occurs when R# is disabled.  I have encountered a more stringent example of this occurring here:<br>
<a target='_blank' href="https://developercommunity2.visualstudio.com/t/Pressing-Key-in-cs-File-Pegs-CPU-50-80/1300768">https://developercommunity2.visualstudio.com/t/Pressing-Key-in-cs-File-Pegs-CPU-50-80/1300768</a></p>

#### Feedback Bot on 1/4/2021, 11:17 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### DragonSpark on 1/14/2021, 07:12 AM: 

<p>FWIW I am pretty sure this issue is responsible for crashing my Visual Studio IDE environment at least 2-3 times a day while working in `.razor` files.  `OutOfMemoryException`s galore.</p>

#### DragonSpark on 1/16/2021, 00:00 AM: 

<p>Seeing a lot of this before my IDE crashes.</p><pre>Newtonsoft.Json.JsonSerializationException : Error writing JSON RPC Message: OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown. ---&gt; System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
   at Newtonsoft.Json.Linq.JTokenWriter.WriteValue(Boolean value)
   at Newtonsoft.Json.Linq.JValue.WriteTo(JsonWriter writer,JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JProperty.WriteTo(JsonWriter writer,JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JObject.WriteTo(JsonWriter writer,JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JArray.WriteTo(JsonWriter writer,JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JProperty.WriteTo(JsonWriter writer,JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JObject.WriteTo(JsonWriter writer,JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JArray.WriteTo(JsonWriter writer,JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JProperty.WriteTo(JsonWriter writer,JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JObject.WriteTo(JsonWriter writer,JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JProperty.WriteTo(JsonWriter writer,JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JObject.WriteTo(JsonWriter writer,JsonConverter[] converters)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer,Object value,JsonContract valueContract,JsonProperty member,JsonContainerContract containerContract,JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer,IEnumerable values,JsonArrayContract contract,JsonProperty member,JsonContainerContract collectionContract,JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer,Object value,JsonContract valueContract,JsonProperty member,JsonContainerContract containerContract,JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer,Object value,JsonObjectContract contract,JsonProperty member,JsonContainerContract collectionContract,JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer,Object value,JsonContract valueContract,JsonProperty member,JsonContainerContract containerContract,JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter,Object value,Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter,Object value,Type objectType)
   at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o,JsonSerializer jsonSerializer)
   at StreamJsonRpc.JsonMessageFormatter.Serialize(JsonRpcMessage message)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of inner exception stack trace ---
   at StreamJsonRpc.JsonMessageFormatter.Serialize(JsonRpcMessage message)
   at StreamJsonRpc.JsonMessageFormatter.Serialize(IBufferWriter`1 contentBuffer,JsonRpcMessage message)
   at StreamJsonRpc.HeaderDelimitedMessageHandler.Write(JsonRpcMessage content,CancellationToken cancellationToken)
   at StreamJsonRpc.PipeMessageHandler.WriteCoreAsync(JsonRpcMessage content,CancellationToken cancellationToken)
   at async StreamJsonRpc.MessageHandlerBase.WriteAsync(&lt;Unknown Parameters&gt;)
   at async StreamJsonRpc.JsonRpc.TransmitAsync(&lt;Unknown Parameters&gt;)
   at System.Threading.Tasks.ValueTask.ThrowIfCompletedUnsuccessfully()
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync(&lt;Unknown Parameters&gt;)
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Remote.RemoteEndPoint.InvokeAsync[T](&lt;Unknown Parameters&gt;)
<br></pre>

#### DragonSpark on 1/16/2021, 11:00 PM: 

<p>Another one but different.</p><pre>StreamJsonRpc.RemoteInvocationException: Unexpected false
   at StreamJsonRpc.JsonRpc.&lt;InvokeCoreAsync&gt;d__133`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.Remote.RemoteEndPoint.&lt;InvokeAsync&gt;d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
RPC server exception:
System.InvalidOperationException: Unexpected false
      at Roslyn.Utilities.Contract.Fail(String message)
      at Roslyn.Utilities.Contract.ThrowIfFalse(Boolean condition)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.&lt;UpdateDocumentInfoAsync&gt;d__14.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.&lt;UpdateDocumentAsync&gt;d__13.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.&lt;UpdateDocumentsAsync&gt;d__12.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.&lt;UpdateProjectAsync&gt;d__10.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.&lt;UpdateProjectsAsync&gt;d__8.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.&lt;UpdateProjectsAsync&gt;d__7.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.SolutionCreator.&lt;CreateSolutionAsync&gt;d__6.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.&lt;CreateSolution_NoLockAsync&gt;d__10.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteWorkspace.&lt;GetSolutionAsync&gt;d__12.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.CodeAnalysisService.&lt;&gt;c__DisplayClass29_0.&lt;&lt;RenameSymbolAsync&gt;b__0&gt;d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.ServiceBase.&lt;RunServiceAsync&gt;d__16`1.MoveNext()<br></pre>
</pre>

#### DragonSpark on 1/18/2021, 07:13 AM: 

<p>Another, but different</p><pre>Newtonsoft.Json.JsonSerializationException : Deserializing JSON-RPC result to type TagHelperResolutionResult failed with OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at StreamJsonRpc.JsonMessageFormatter.JsonRpcResult.GetResult[T]()
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Remote.RemoteEndPoint.InvokeAsync[T](&lt;Unknown Parameters&gt;)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
<br></pre>

#### DragonSpark on 1/18/2021, 11:25 PM: 

<p>Another, but different.</p><pre>StreamJsonRpc.ConnectionLostException : The JSON-RPC connection with the remote party was lost before the request could complete.
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync(&lt;Unknown Parameters&gt;)
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Remote.RemoteEndPoint.InvokeAsync[T](&lt;Unknown Parameters&gt;)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
<br></pre>

#### DragonSpark on 1/20/2021, 05:38 AM: 

<p>Another one.  Looks/feels like 5-6 times a day now that my IDE crashes and restarts.  Is there a way to get these metrics to you?  I am not sure how to use the feedback tool in this regard.</p><pre>StreamJsonRpc.ConnectionLostException : The JSON-RPC connection with the remote party was lost before the request could complete.
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync(&lt;Unknown Parameters&gt;)
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Remote.RemoteEndPoint.InvokeAsync[T](&lt;Unknown Parameters&gt;)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)<br></pre>

#### DragonSpark on 1/20/2021, 09:23 PM: 

<p>Another, but different.</p><pre>System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Buffers.DefaultArrayPool`1.Rent(Int32 minimumLength)
   at Nerdbank.Streams.Sequence`1.GetSegment(Int32 sizeHint)
   at Nerdbank.Streams.Sequence`1.GetMemory(Int32 sizeHint)
   at Nerdbank.Streams.BufferTextWriter.EncodeCharacters(Boolean flushEncoder)
   at Nerdbank.Streams.BufferTextWriter.Write(Char value)
   at Newtonsoft.Json.JsonTextWriter.WriteValueDelimiter()
   at Newtonsoft.Json.JsonWriter.AutoComplete(JsonToken tokenBeingWritten)
   at Newtonsoft.Json.JsonTextWriter.WritePropertyName(String name)
   at Newtonsoft.Json.Linq.JProperty.WriteTo(JsonWriter writer,JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JObject.WriteTo(JsonWriter writer,JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JArray.WriteTo(JsonWriter writer,JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JProperty.WriteTo(JsonWriter writer,JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JObject.WriteTo(JsonWriter writer,JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JArray.WriteTo(JsonWriter writer,JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JProperty.WriteTo(JsonWriter writer,JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JObject.WriteTo(JsonWriter writer,JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JProperty.WriteTo(JsonWriter writer,JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JObject.WriteTo(JsonWriter writer,JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JArray.WriteTo(JsonWriter writer,JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JProperty.WriteTo(JsonWriter writer,JsonConverter[] converters)
   at Newtonsoft.Json.Linq.JObject.WriteTo(JsonWriter writer,JsonConverter[] converters)
   at StreamJsonRpc.JsonMessageFormatter.WriteJToken(IBufferWriter`1 contentBuffer,JToken json)
   at StreamJsonRpc.JsonMessageFormatter.Serialize(IBufferWriter`1 contentBuffer,JsonRpcMessage message)
   at StreamJsonRpc.HeaderDelimitedMessageHandler.Write(JsonRpcMessage content,CancellationToken cancellationToken)
   at StreamJsonRpc.PipeMessageHandler.WriteCoreAsync(JsonRpcMessage content,CancellationToken cancellationToken)
   at async StreamJsonRpc.MessageHandlerBase.WriteAsync(&lt;Unknown Parameters&gt;)
   at async StreamJsonRpc.JsonRpc.TransmitAsync(&lt;Unknown Parameters&gt;)
   at System.Threading.Tasks.ValueTask.ThrowIfCompletedUnsuccessfully()
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync(&lt;Unknown Parameters&gt;)
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Remote.RemoteEndPoint.InvokeAsync[T](&lt;Unknown Parameters&gt;)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
<br></pre>

#### DragonSpark on 1/20/2021, 09:51 PM: 

<p>Yep, another but different.  On a roll here.</p><pre>Newtonsoft.Json.JsonSerializationException : Error writing JSON RPC Message: OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown. ---&gt; System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
   at Newtonsoft.Json.Linq.JPropertyKeyedCollection.EnsureDictionary()
   at Newtonsoft.Json.Linq.JPropertyKeyedCollection.InsertItem(Int32 index,JToken item)
   at System.Collections.ObjectModel.Collection`1.Insert(Int32 index,T item)
   at Newtonsoft.Json.Linq.JContainer.InsertItem(Int32 index,JToken item,Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JObject.InsertItem(Int32 index,JToken item,Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index,Object content,Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.AddAndSkipParentCheck(JToken token)
   at Newtonsoft.Json.Linq.JTokenWriter.AddParent(JContainer container)
   at Newtonsoft.Json.Linq.JTokenWriter.WritePropertyName(String name)
   at Newtonsoft.Json.JsonWriter.WritePropertyName(String name,Boolean escape)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(JsonWriter writer,IDictionary values,JsonDictionaryContract contract,JsonProperty member,JsonContainerContract collectionContract,JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer,Object value,JsonContract valueContract,JsonProperty member,JsonContainerContract containerContract,JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer,Object value,JsonObjectContract contract,JsonProperty member,JsonContainerContract collectionContract,JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer,Object value,JsonContract valueContract,JsonProperty member,JsonContainerContract containerContract,JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer,IEnumerable values,JsonArrayContract contract,JsonProperty member,JsonContainerContract collectionContract,JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer,Object value,JsonContract valueContract,JsonProperty member,JsonContainerContract containerContract,JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer,Object value,JsonObjectContract contract,JsonProperty member,JsonContainerContract collectionContract,JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer,Object value,JsonContract valueContract,JsonProperty member,JsonContainerContract containerContract,JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter,Object value,Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.SerializeInternal(JsonWriter jsonWriter,Object value,Type rootType)
   at Microsoft.CodeAnalysis.Razor.Workspaces.Serialization.FullProjectSnapshotHandleJsonConverter.WriteJson(JsonWriter writer,Object value,JsonSerializer serializer)
   at Microsoft.CodeAnalysis.Razor.Workspaces.Serialization.ProjectSnapshotJsonConverter.WriteJson(JsonWriter writer,Object value,JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer,JsonConverter converter,Object value,JsonContract contract,JsonContainerContract collectionContract,JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer,Object value,JsonContract valueContract,JsonProperty member,JsonContainerContract containerContract,JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter,Object value,Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter,Object value,Type objectType)
   at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o,JsonSerializer jsonSerializer)
   at StreamJsonRpc.JsonMessageFormatter.TokenizeUserData(Type declaredType,Object value)
   at StreamJsonRpc.JsonMessageFormatter.TokenizeUserData(JsonRpcMessage jsonRpcMessage)
   at StreamJsonRpc.JsonMessageFormatter.Serialize(JsonRpcMessage message)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of inner exception stack trace ---
   at StreamJsonRpc.JsonMessageFormatter.Serialize(JsonRpcMessage message)
   at StreamJsonRpc.JsonMessageFormatter.Serialize(IBufferWriter`1 contentBuffer,JsonRpcMessage message)
   at StreamJsonRpc.HeaderDelimitedMessageHandler.Write(JsonRpcMessage content,CancellationToken cancellationToken)
   at StreamJsonRpc.PipeMessageHandler.WriteCoreAsync(JsonRpcMessage content,CancellationToken cancellationToken)
   at async StreamJsonRpc.MessageHandlerBase.WriteAsync(&lt;Unknown Parameters&gt;)
   at async StreamJsonRpc.JsonRpc.TransmitAsync(&lt;Unknown Parameters&gt;)
   at System.Threading.Tasks.ValueTask.ThrowIfCompletedUnsuccessfully()
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync(&lt;Unknown Parameters&gt;)
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](&lt;Unknown Parameters&gt;)
   at async Microsoft.CodeAnalysis.Remote.RemoteEndPoint.InvokeAsync[T](&lt;Unknown Parameters&gt;)
<br></pre>

#### Feedback Bot on 1/20/2021, 11:42 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

---
#### DragonSpark solved on 1/20/2021, 09:50 PM, 0 votes: 

<p>Sigh... why can't we delete these?</p>

**Comment by Mike-E-angelo** [comment]
I am pretty sure this is the same issue as #27662 but I have been able to reproduce it without R#.  This has been making my development life pretty miserable as of late so any consideration towards this would be super-duper greatly appreciated. 🙏

**Comment by Mike-E-angelo** [comment]
Am I to understand correctly that this is part of 16.9 preview?  If so, I might switch over ASAP as currently, my environment is basically unusable ATM when doing any sort of Razor development.  

I am also thinking there is a factor at play here with the more .razor files in a solution, the bigger this problem presents itself.  I don't seem to recall the amount of shutdowns being anywhere near as bad as it is now vs. when I reported it, for example.

**Comment by Mike-E-angelo** [comment]
Wow even with `16.9-preview3` things seem to be way better.  IDE is responsive and there doesn't seem to be The Churn of Death as experienced in `16.8.x`.  I should have thought of switching to preview sooner. 😁  

So, looks like I have an environment again. 😌  And, if I am not mistaken, the compilation time is better, too?  Seems like I am able to edit-re-F5 and it launches faster than before.

I am very appreciative of all your efforts out there, in any case. 🙏

**Comment by NTaylorMullen** [comment]
> Wow even with `16.9-preview3` things seem to be way better. IDE is responsive and there doesn't seem to be The Churn of Death as experienced in `16.8.x`. I should have thought of switching to preview sooner. 😁
> 
> So, looks like I have an environment again. 😌 And, if I am not mistaken, the compilation time is better, too? Seems like I am able to edit-re-F5 and it launches faster than before.
> 
> I am very appreciative of all your efforts out there, in any case. 🙏

Hah ya we're constantly pushing new updates and 16.9-Preview4 will actually be the moment when the performance fix specifically for this issue is resolved (not yet released). That being said 16.9-Preview3 does indeed have loads of goodies.

Really happy it's working out for you!
