### ISSUE TITLE
Impersonation cause FileLoadException 

### ISSUE THREAD

**Issue by Der-Kraken** [dotnet/aspnetcore#29527]
We build an intranet app with Asp.Net-Core and IIS. We are using ActiveDirectory. Our SQL-Server needs end-user access (impersonation by asp).
Only in production there occurrs sometimes the error "FileLoadException - Access Denied". That happens by dot.Net when binaries are loaded while running impersonated.

Because the real project is too complex I created a small one withoutdb access:

https://github.com/Der-Kraken/Kraken.Bugreport.FileLoadException.Asp

# Details
The demo project is a small project to reproduce an error which occurrs in our production one. 
The project targets __asp.net-core 3.1__ but the error occurrs in __dot.Net 5__ too.

## Explanation of Production Project

In our real project there is a database which requires access with an impersonated end-user (ActiveDirectory).
So before accessing the database (with EntityFrameworkCore) the context is impersonated with 
```System.Security.Principal.WindowsIdentity.RunImpersonated(winIdent.AccessToken, delegateAccessingDatabase)```.

Sometimes the webserver crashes with an FileLoadException 'AccessDenied' for the assembly System.Reflection.Extension.

## Explanation of Demo Project

In this demo project there is no database access in order to reduce complexitiy. 
Instead there is used a nuget called Flee (we using that nuget in the real project too and there is happening the same error but with another assembly).

## Explanation of the Problem

The error reason is because the webfolder on wwwroot is readable only for the apppool user. When IIS starts the app then dot.Net loads some binaries but not all (just in time). 
If the code which runs impersonated try to load an binary (because it is the first who access is) then dot.Net will throw an FileLoadException because reading the binaries is not allowed for common end users.

Our workaround is to allow end users acessing wwwroot. But that is a security problem.

# How to reproduce

The error happens only in production after the project has been published to IIS. In order you can impersonate you will need AD-Users (I think).

1. Setup
   - Setup an IIS-WebSite with its own AppPool (see see screens below for configuration)
   - Run publish on VisualStudio with the profile **FolderProfile.pubxml**
   - Copy the compiled 'publish'-binaries to the websites folder in wwwroot
   - Allow the IISuser permission on the binaries
   - Allow one ActiveDirectory user (we call it **UserA**) reading+executing the binaries
   - Disalow another ActiveDirectory user (we call it **UserB**) permissions for the binaries
2. App test without problems
   - Browse the website with **UserA**
   - Click on the first link (you will see the number 6)
   - Browse back and click the second link
   - Check if first line prints ```The code has been run: I have Impersonated``` if not then impersonation has not worked and AD or something was configured wrong
   - Change user and browse the website again with **UserB**
   - Do the same things as before. All should work the same (because the DLL's are already loaded)
3. App test with problems
   - Restart the AppPool or wait until the website goes to sleep
   - Browse the webiste with **UserB**
   - **Important** click on the second link first (with impersonation)
   - You will see the 'FileLoadException' because **UserB** has no native permission to read binaries
   - Note that if you had clicked the first link before the second one then has no problem because the DLL has already been loaded

# Attachements

## StackTrace

```
System.IO.FileLoadException: 
File name: 'Flee.NetStandard20, Version=1.0.0.0, Culture=neutral, PublicKeyToken=85238e57c1c34b81'
   at Kraken.Bugreport.FileLoadException.Asp.FleeAdapter.Calculate(String formula, Dictionary`2 parameter)
   at Kraken.Bugreport.FileLoadException.Core.BusinessLogicHandler.Handle(String formula, Dictionary`2 parameter) in D:\_src\temp\Kraken.Bugreport.FileLoadException.Asp\Kraken.Bugreport.FileLoadException.Core\BusinessLogicHandler.cs:line 18
   at Kraken.Bugreport.FileLoadException.Asp.Controllers.ImpersonateDemoController.<>c__DisplayClass4_0.<UseImpersonation>b__0() in D:\_src\temp\Kraken.Bugreport.FileLoadException.Asp\Kraken.Bugreport.FileLoadException.Asp\Controllers\ImpersonateDemoController.cs:line 46
   at System.Security.Principal.WindowsIdentity.<>c__DisplayClass67_0.<RunImpersonatedInternal>b__0(Object <p0>)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Security.Principal.WindowsIdentity.RunImpersonatedInternal(SafeAccessTokenHandle token, Action action)
   at System.Security.Principal.WindowsIdentity.RunImpersonated(SafeAccessTokenHandle safeAccessTokenHandle, Action action)
   at Kraken.Bugreport.FileLoadException.Asp.Controllers.ImpersonateDemoController.RunImpersonatedIfRequired(Action action) in D:\_src\temp\Kraken.Bugreport.FileLoadException.Asp\Kraken.Bugreport.FileLoadException.Asp\Controllers\ImpersonateDemoController.cs:line 66
   at Kraken.Bugreport.FileLoadException.Asp.Controllers.ImpersonateDemoController.UseImpersonation() in D:\_src\temp\Kraken.Bugreport.FileLoadException.Asp\Kraken.Bugreport.FileLoadException.Asp\Controllers\ImpersonateDemoController.cs:line 43
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

## Configuration on IIS

![iisconfig](https://github.com/Der-Kraken/Kraken.Bugreport.FileLoadException.Asp/blob/master/blob/apppoolconfig.png?raw=true)

**Comment by Pilchie** [comment]
@Tratcher any thoughts here?

**Comment by Tratcher** [comment]
Your explanation of the problem seems completely accurate, I'm not quite sure what more you're looking for from us? 

Yes, dotnet lazily loads assemblies when they're first used, and yes if you impersonate a user then that users permissions are used when trying to load the assembly. 

> Our workaround is to allow end users acessing wwwroot. But that is a security problem.

If it's read-only access then what are the risks?

The only alternative I can suggest is to add a warm-up step in Program.Main where you intentionally touch types from the relevant assemblies to force them to load before the server starts.

```
        public static void Main(string[] args)
        {
            var host = CreateHostBuilder(args).Build()
            // TODO: Touch all the assemblies so they load before the server starts.
            host.Run();
        }
```

**Comment by Der-Kraken** [comment]
@Tratcher Thank you for your fast response. See below my ansers:

> I'm not quite sure what more you're looking for from us?

For me it seems like an unexpected behaviour for developers. Loading libraries belongs to framework and not to end user. The Impersonation-Feature belongs to framework too.
So for me the framework has to ensure that the libraries are loaded correctly. 
In consequence it would mean that the developer has to check manually in domain code if system libraries are loaded and if not then load it. That should not be the way to go.

In old world there was the Impersonation-Feature on IIS level (my colleague told me). There was never such problems.

By the way. With the FileLoad-Problem it happens sometimes (in the production project) that we broke the whole WebApp. If it was broken each api call returned 200 OK without http-body even though the server should return 400 result (hard coded on controller side).
Sadly reproduction of that error was not reliable. I was not able to reproduce in the demo project. Only a restart of AppPool worked in that case.

> If it's read-only access then what are the risks?

In the webfolder are nested some config files (like app.config). The end user should never see that content.
It seems wrong to me allow the end user access to server-only source code. 

> The only alternative I can suggest is to add a warm-up step in Program.Main where you intentionally touch types from the relevant assemblies to force them to load before the server starts.

That could be a solution. Do you know if dot.net unloads dll at runtime?

**@msftbot:** I was at weekend. So answering was was not possible, please undo the closed state.

**Comment by Pilchie** [comment]
Sorry - @msftbot doesn't handle weekends very well sometimes.

**Comment by Tratcher** [comment]
> Do you know if dot.net unloads dll at runtime?

No, .NET does not unload dlls once they've been loaded for you.

I'm going to transfer this issue to the runtime repo, they own both impersonation and dll loading. If you also want help with the error handling issues please open a sperate aspnetcore issue.
