### ISSUE TITLE
SpaServicesExtensionsTests UseSpa_KillsRds_WhenAppIsStopped and UseSpa_KillsAngularCli_WhenAppIsStopped fail

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#29549]
```
Microsoft.AspNetCore.SpaServices.Extensions.Tests.SpaServicesExtensionsTests.UseSpa_KillsRds_WhenAppIsStopped

Assert.False() Failure
Expected: False
Actual:   True

   at Microsoft.AspNetCore.SpaServices.Extensions.Tests.SpaServicesExtensionsTests.Assert_NpmKilled_WhenAppIsStopped(IHostApplicationLifetime applicationLifetime, NpmStartedDiagnosticListener listener) in /_/src/Middleware/SpaServices.Extensions/test/SpaServicesExtensionsTests.cs:line 91
   at Microsoft.AspNetCore.SpaServices.Extensions.Tests.SpaServicesExtensionsTests.UseSpa_KillsRds_WhenAppIsStopped() in /_/src/Middleware/SpaServices.Extensions/test/SpaServicesExtensionsTests.cs:line 58
--- End of stack trace from previous location ---
```

https://dev.azure.com/dnceng/public/_build/results?buildId=962239&view=ms.vss-test-web.build-test-results-tab

The UseSpa_KillsAngularCli_WhenAppIsStopped failure is the same.

**Comment by JunTaoLuo** [comment]
I'm seeing it fail on Windows as well: https://dev.azure.com/dnceng/public/_build/results?buildId=977996&view=results

**Comment by javiercn** [comment]
@mkArtakMSFT we can probably get rid of these tests since they are part of the old infrastructure.
