### ISSUE TITLE
[SignalR] Frequent WS Disconnect (1006)

### ISSUE THREAD

**Issue by SonoranBrian** [dotnet/aspnetcore#29563]
I'm running a .Net 5 application using SignalR for websockets with a Vue JS app.

Recently, my client seems to continually disconnect randomly. I am able to reproduce the issue more consistently by opening another browser/device and establishing a new WSS connection.

Below is an example of one of these events:

**Server SignalR Debug**
```
2021-01-23T04:51:39.122251204Z dbug: Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager[1]
2021-01-23T04:51:39.122285493Z       New connection SBCK7IOpjJgPDcCq7n8zEQ created.
2021-01-23T04:51:39.122289621Z dbug: Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher[10]
2021-01-23T04:51:39.122293416Z       Sending negotiation response.
2021-01-23T04:51:39.328029116Z dbug: Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher[4]
2021-01-23T04:51:39.328054094Z       Establishing new connection.
2021-01-23T04:51:39.328067732Z dbug: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[1]
2021-01-23T04:51:39.328071260Z       Socket opened using Sub-Protocol: '(null)'.
2021-01-23T04:51:39.328074252Z dbug: Microsoft.AspNetCore.SignalR.HubConnectionHandler[5]
2021-01-23T04:51:39.328077311Z       OnConnectedAsync started.
2021-01-23T04:51:39.385290276Z dbug: Microsoft.AspNetCore.SignalR.Internal.DefaultHubProtocolResolver[2]
2021-01-23T04:51:39.385315351Z       Found protocol implementation for requested protocol: json.
2021-01-23T04:51:39.385319091Z dbug: Microsoft.AspNetCore.SignalR.HubConnectionContext[1]
2021-01-23T04:51:39.385336045Z       Completed connection handshake. Using HubProtocol 'json'.
```
then shortly after...
```
2021-01-23T04:51:40.028338267Z dbug: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[14]
2021-01-23T04:51:40.028355133Z       Socket connection closed prematurely.
2021-01-23T04:51:40.028358571Z       System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
2021-01-23T04:51:40.028363128Z          at System.Net.WebSockets.ManagedWebSocket.ThrowIfEOFUnexpected(Boolean throwOnPrematureClosure)
2021-01-23T04:51:40.028368417Z          at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
2021-01-23T04:51:40.028373089Z          at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
2021-01-23T04:51:40.028377818Z          at Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsServerTransport.StartReceiving(WebSocket socket)
2021-01-23T04:51:40.028382630Z dbug: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[4]
2021-01-23T04:51:40.028387671Z       Waiting for the application to finish sending data.
2021-01-23T04:51:40.028391779Z dbug: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[2]
2021-01-23T04:51:40.028408655Z       Socket closed.
2021-01-23T04:51:40.028413197Z dbug: Microsoft.AspNetCore.SignalR.HubConnectionHandler[6]
2021-01-23T04:51:40.028416471Z       OnConnectedAsync ending.
```

**Client WS Traffic**
1. Last WS traffic at `51:39.929` (Type 6/KeepAlive)
![image](https://user-images.githubusercontent.com/56844125/105569118-412e4f00-5cfc-11eb-870a-e41344bb1a49.png)
2. Client SignalR Logs (Debug) at `51:39.999Z`
![image](https://user-images.githubusercontent.com/56844125/105569143-818dcd00-5cfc-11eb-8cbe-ea59664e1f76.png)

I'm unable to reproduce this issue at all locally with multiple browsers. This only seems to happen on production: docker, HAProxy, and NGINX.

I've also seen it happen where the moment the client sends a keepalive/type:6 over WSS, it creates an entirely new connection...

There's no errors or exceptions being logged or seen on connection or disconnection events in the C# code. What can I use to try and debug deeper? Is this more likely an issue with our load balancer, server network, etc?

Here's additional Chrome logs of when these new connections are made, there's no consistent time interval:
![image](https://user-images.githubusercontent.com/56844125/105573183-02f35880-5d19-11eb-848e-c17ece2c6d94.png)

**Comment by davidfowl** [comment]
Sounds like something in the infrastructure might be killing the websocket. Are you using https?  Can you describe the infrastructure where this is all running.

**Comment by SonoranBrian** [comment]
> Sounds like something in the infrastructure might be killing the websocket. Are you using https? Can you describe the infrastructure where this is all running.

The .Net app is running in a docker container. HAProxy forwards all requests to this docker container.
The VueJS app is running on NGINX in a docker container.

If it was a keepalive/timeout with HAProxy, I would assume these disconnects would be at a consistent interval. There is rate-limiting with HAProxy, but the client networking area would show some 429 related errors.

I've enabled trace logging for SignalR, "detailed error messages", etc.

All requests are over HTTPS/WSS.

**Comment by SonoranBrian** [comment]
I've also disabled all firewalls/anti-virus, and the issue persists across multiple devices.

However, when using mobile data on another device the issue does not seem to persist there. So this could be a networking issue or some sort of rate-limiting with my home IP specifically?

**Comment by BrennanConroy** [comment]
Sounds like an issue with a proxy or intermediary. Closing as there is nothing actionable we can do here. If you find an issue due to how proxies handle websockets that would be doc worthy, feel free to post it here!
