### ISSUE TITLE
Microsoft.NET.Sdk.Razor GeneratePackageOnBuild creating folders for random static web assets

### ISSUE THREAD

**Issue by groogiam** [dotnet/aspnetcore#29561]
### Describe the bug
When generating a nuget package for a blazor class library random files are created as directories. See attached repro.

### To Reproduce

1. Open the attached repro [Blazor5ClassLib.zip](https://github.com/dotnet/aspnetcore/files/5859604/Blazor5ClassLib.zip)
2. Build the project
3. Navigate to bin\Debug\
4. Extract the contents of Blazor5ClassLib.1.0.0.nupkg 
5. Navigate to Blazor5ClassLib.1.0.0\staticwebassets\css\open-iconic
6. The FONT-LICENSE and ICON-LICENSE files have been packaged as a directory rather than the static file in the project. This causes blazor wasm publishes which reference this package to fail with an error similar to https://github.com/dotnet/aspnetcore/issues/29529

```
staticwebassets\css\open-iconic\ICON-LICENSE' is denied.
            at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
            at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
            at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
            at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
            at System.IO.File.OpenRead(String path)
            at Microsoft.NET.Sdk.BlazorWebAssembly.Tools.BrotliCompressCommand.<ExecuteCoreAsync>b__16_0(Int32 i)
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
         --- End of stack trace from previous location ---
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
            at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
            at System.Threading.Tasks.TaskReplicator.Replica.Execute()
```

Static assets should be packaged as they are in the project.

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
- Visual Studio 16.8.4

**Comment by groogiam** [comment]
I have done some more experimentation and the issue seems to persist if I rename the two license files to have a .txt suffix. If I delete them both or combine them into a single text file with a different name the publish seems to work. The behavior is extremely strange.

**Comment by javiercn** [comment]
It's somewhat of a fuzzy area where the bug can be attributed to Nuget. We are specifying the path in the package and nuget is deciding to create the additional folder.

That said, it's not clear to me if PackagePath is meant to represent the file path, the folder path, or potentially both, so we can fix it on our end by adjusting the PackagePath
