### ISSUE TITLE
Empty OpenIDConnect metadata configuration reply is cached for hours

### ISSUE THREAD

**Issue by drauch** [dotnet/aspnetcore#29759]
### Describe the bug
If an OpenIDConnect metadata configuration endpoint temporarily returns an empty JSON for some reason (we observed that using Microsoft Azure ADB2C as OpenIDConnect provider) all the configuration URLs are set to null and instead of re-obtaining the JSON file it is cached for hours and no login attempt succeeds anymore. We had to reset all our IIS instances to clear the cache.

### To Reproduce
Create a fake metadata configuration endpoint (e.g., we used https://webhook.site/) to return 200 OK with an empty JSON response, attempt a login and fail (of course). Then change the endpoint to return the proper JSON again, attempt another login, unfortunately it still fails because the JSON is cached for hours.

### Exceptions (if any)
```
System.InvalidOperationException: Cannot redirect to the authorization endpoint, the configuration may be missing or invalid.
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.<HandleChallengeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.<ChallengeAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.<ChallengeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ChallengeResult.<ExecuteResultAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeResultAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAlwaysRunResultFilters>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System
```

### Further technical details
- ASP.NET Core version 2.1.highest on .NET Framework 4.8
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS 2019

**Comment by Tratcher** [comment]
Awkward.

That error is thrown from here:
https://github.com/dotnet/aspnetcore/blob/5d42ed05b670528da3d18ee881b2d2e8339bd5a0/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L452-L456

Workaround:

Hook into the RedirectToIdentityProvider event and check for the missing issuer:
https://github.com/dotnet/aspnetcore/blob/5d42ed05b670528da3d18ee881b2d2e8339bd5a0/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L433

Then request a refresh:
https://github.com/dotnet/aspnetcore/blob/5d42ed05b670528da3d18ee881b2d2e8339bd5a0/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L770

It won't salvage the current request, but it should help recover for the next one.

That's probably the same fix we'd implement.

**Comment by blowdart** [comment]
@drauch Did you try Chris's work around? The thing is we don't expect a meta data endpoint to be empty, that's a big error out of our control. We believe we're doing the right thing here.

**Comment by drauch** [comment]
To be honest, we haven't gotten around to implement it yet.

**Comment by blowdart** [comment]
If you can try it and let us know how it worked for you that'd be great. As it's not a situation we'd expect we probably won't fix the code if the work around works, because you have a way to handle it yourself.
