### ISSUE TITLE
Kestrel throwing: The WriteAsync method cannot be called when another write operation is pending.

### ISSUE THREAD

**Issue by csname1910** [dotnet/aspnetcore#29806]
### I keep getting this exception:
`
System.NotSupportedException:  
The WriteAsync method cannot be called when another write operation is pending.
   at System.Net.Security.SslStream.WriteAsyncInternal[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory``1 buffer)
   at System.IO.Pipelines.StreamPipeWriter.FlushAsyncInternal(Boolean writeToStream, CancellationToken cancellationToken)
   at System.IO.Pipelines.StreamPipeWriter.CompleteAsync(Exception exception)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.DuplexPipeStreamAdapter``1.DisposeAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection``1.ExecuteAsync()`

### Further technical details
ASP.NET Core Runtime 5.0.2

**Comment by Tratcher** [comment]
Can you share repro steps, code, and/or server logs?

**Comment by csname1910** [comment]
The program is too complex to show it here.
The exceptions occurs only infrequently, so I can’t tell repro steps.
I see I every few days in the Windows events.
The event consists only of the exception.

But I suppose the problem is Kestrel and not my code, because there is none of my code in the call stack of the exception.

**Comment by BrennanConroy** [comment]
Are you calling Task.Run() in the middleware pipeline, writing to the response, and not awaiting the task?

Triage: Lets take a look at the stack and see if there is anything obvious there, or if we can be more defensive.

**Comment by davidfowl** [comment]
@csname1910 any updates?

**Comment by csname1910** [comment]
@BrennanConroy i am calling Task.Run only in OnConnectedAsync of my SignalrR-Hub. 

The exception keeps occuring every few days,

**Comment by davidfowl** [comment]
Can you share your application or something that replicates the problem? Can you also try turning on verbose logs? We need more information to investigate.

**Comment by csname1910** [comment]
Sorry, I cannot share the source code. Even if I could you would have to run the server serveral days with users accessing it to see the exception. I will try turning on verbose logs.

**Comment by davidfowl** [comment]
Any updates?
