### ISSUE TITLE
[.NET 6] [Runtime Compat Failure] ABP Framework template (3.1) fails to launch when target to 6

### ISSUE THREAD

**Issue by jiangzeng01** [dotnet/aspnetcore#29815]
**Application Name:**  ABP Framework app
**OS:** Windows 10 RS5
**CPU:** X64
**.NET Build Number:** 6.0.100-preview.1.21080.2 

**Verify Scenarios:**
1)Target to NET6 with NET Core SDK build 6.0.100-preview.1.21075.3: Fail
2)Default NETCORE(3.1) with SDK build 6.0.100-preview.1.21075.3:  Pass

**Repro steps to build and run**
1) Source Code at [https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1272735](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1272735)
2) Goto src\MyTestProject.Web  (MyTestProject.Web.csproj is set to 6.0)
3) dotnet publish
4) Go to publish folder, created at : src\MyTestProject.Web\bin\Debug\net6.0\publish
5) Run MyTestProject.Web.exe
6) In Browser, go to :http://localhost:5000

**Expected Result:**
Page should load

**Actual Result:**
Page doesn't load

**Findings:**
When we target this app to 6.0 and run, we get this error :
```
2021-02-01 08:41:24.362 +00:00 [FTL] Application startup exception
System.InvalidOperationException: A descriptor for '/Pages/AbpPermissionManagement/PermissionManagementModal.cshtml' was not found.
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.CompiledPageActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.UpdateCollection()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.Initialize()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.GetChangeToken()
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.<>c__DisplayClass11_0.<Subscribe>b__0()
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.Subscribe()
   at Microsoft.AspNetCore.Mvc.Routing.ControllerActionEndpointDataSource..ctor(ControllerActionEndpointDataSourceIdProvider dataSourceIdProvider, IActionDescriptorCollectionProvider actions, ActionEndpointFactory endpointFactory, OrderedEndpointsSequenceProvider orderSequence)
   at Microsoft.AspNetCore.Builder.ControllerEndpointRouteBuilderExtensions.GetOrCreateDataSource(IEndpointRouteBuilder endpoints)
   at Microsoft.AspNetCore.Builder.ControllerEndpointRouteBuilderExtensions.MapControllerRoute(IEndpointRouteBuilder endpoints, String name, String pattern, Object defaults, Object constraints, Object dataTokens)
   at Microsoft.AspNetCore.Builder.AbpAspNetCoreMvcApplicationBuilderExtensions.<>c__DisplayClass0_0.<UseMvcWithDefaultRouteAndArea>b__0(IEndpointRouteBuilder endpoints)
   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
   at Microsoft.AspNetCore.Builder.AbpAspNetCoreMvcApplicationBuilderExtensions.UseMvcWithDefaultRouteAndArea(IApplicationBuilder app, Action`1 additionalConfigurationAction)
   at MyTestProject.Web.MyTestProjectWebModule.OnApplicationInitialization(ApplicationInitializationContext context) in C:\Users\valtunc\Desktop\Sources\Abp_MyTestProject\src\MyTestProject.Web\MyTestProjectWebModule.cs:line 210
   at Volo.Abp.Modularity.OnApplicationInitializationModuleLifecycleContributor.Initialize(ApplicationInitializationContext context, IAbpModule module)
   at Volo.Abp.Modularity.ModuleManager.InitializeModules(ApplicationInitializationContext context)
   at Volo.Abp.AbpApplicationBase.InitializeModules()
   at Volo.Abp.AbpApplicationWithExternalServiceProvider.Initialize(IServiceProvider serviceProvider)
   at Microsoft.AspNetCore.Builder.AbpApplicationBuilderExtensions.InitializeApplication(IApplicationBuilder app)
   at MyTestProject.Web.Startup.Configure(IApplicationBuilder app) in C:\Users\valtunc\Desktop\Sources\Abp_MyTestProject\src\MyTestProject.Web\Startup.cs:line 15
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

This app is failing to launch with .NET 5, but failed with another known issue: https://github.com/dotnet/aspnetcore/issues/19432
For retargeting 6, the app failed with a new issue.

@dotnet-actwx-bot @dotnet/compat

**Comment by davidfowl** [comment]
This is a new change that @pranavkm made recently. I guess it means these views aren't precompiled?

**Comment by pranavkm** [comment]
The app references a 6.0 runtime and a 3.1 version of Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation (transitively via https://www.nuget.org/packages/Volo.Abp.AspNetCore.Mvc/1.1.2). We recently made a behavior change to Mvc which requires a compatible (6.0 versioned) runtime compilation when that feature is used. Adding a package reference to the 6.0 version gets you past that issue.

```xml
<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="6.0.0-preview.2.21101.10" />
```

Mixing package versions (using 3.x or 5.x versioned package with the 6.0 runtime) isn't necessarily always going to work. We anticipate users to update their packages as part of the migration. I can run this by more people in the dev team, but it's unlikely that we will do any additional work here.

**Comment by PriyaPurkayastha** [comment]
Thanks @pranavkm. Is there a breaking change announcement for this behavior change? 
_We recently made a behavior change to Mvc which requires a compatible (6.0 versioned) runtime compilation when that feature is used._

**Comment by pranavkm** [comment]
@PriyaPurkayastha our migration guide include a section telling users to update their package references as part of updating their apps. It would be unusual to have a breaking change announcement that restates this.

**Comment by jiangzeng01** [comment]
@pranavkm  We got another app failed with the same error in our .NET 6 daily build testing
**App:** webvella (.NET 5.0 App)
**Test scenarios:**
1. App default target 5.0 + Runtime: dotnet-sdk-6.0.100-preview.1.21081.5 - Fail
2. App default target 5.0 + Runtime: .NET 5, 5.0.102 - Pass

**Error message:**
```
Application startup exception: System.InvalidOperationException: A descriptor for '/Pages/debug.cshtml' was not found.
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.CompiledPageActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.UpdateCollection()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.Initialize()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.GetChangeToken()
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.<>c__DisplayClass11_0.<Subscribe>b__0()
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.Subscribe()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionEndpointDataSource..ctor(PageActionEndpointDataSourceIdProvider dataSourceIdProvider, IActionDescriptorCollectionProvider actions, ActionEndpointFactory endpointFactory, OrderedEndpointsSequenceProvider orderedEndpoints)
   at Microsoft.AspNetCore.Builder.RazorPagesEndpointRouteBuilderExtensions.GetOrCreateDataSource(IEndpointRouteBuilder endpoints)
   at Microsoft.AspNetCore.Builder.RazorPagesEndpointRouteBuilderExtensions.MapRazorPages(IEndpointRouteBuilder endpoints)
   at WebVella.Erp.Site.Startup.<>c.<Configure>b__7_0(IEndpointRouteBuilder endpoints) in C:\Users\valtunc\Desktop\AppSources\WebVella-ERP\WebVella.Erp.Site\Startup.cs:line 147
   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
   at WebVella.Erp.Site.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in C:\Users\valtunc\Desktop\AppSources\WebVella-ERP\WebVella.Erp.Site\Startup.cs:line 145
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.WebHost[6]
```

**Findings:**
This 5.0 app is referring 5.0 version of package "Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation", when the app run against 6.0 runtime, it failed. We tried to upgrade the app to .NET 6.0 & update the version of the package to 6.0, then it works fine but the app will be a 6.0 app not 5.0 app. So we think it is the same with this ticket.

**Questions:**
1. if a 3.x or 5.0 app has dependency "Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation", does this mean it will fail to run again 6.0 runtime? And only way to fix is to upgrade to RuntimeCompilation compilation to v6, but this requires app to be upgraded to 6 as well.
2. Do you have a list of packages that need to update to 6.0 to work against 6.0 runtime?

**Comment by mkArtakMSFT** [comment]
@jiangzeng01 this behavior is by design. If customers want to use 6.0 runtime, they will have to reference 6.0 packages.
As for your other question `Do you have a list of packages that need to update to 6.0 to work against 6.0 runtime?` we will expect customers to update all their packages to 6.0.

Going forward we will start putting more thoughts into backward / forward compatibility in an effort to mitigate similar issues in the future.

**Comment by jiangzeng01** [comment]
@mkArtakMSFT Thanks! Is there a breaking change announcement for this behavior change?

**Comment by PriyaPurkayastha** [comment]
@jiangzeng01 Pranav mentioned earlier that the migration guide contains guidance for all package dependencies to be updated. I was able to find this https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-5.0&tabs=visual-studio#update-package-references and it calls out "update each Microsoft.AspNetCore.*". I think this should be sufficient but I also see your point that our testing specifically identified that the package reference for "Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" should be changed to .NET 6. I will leave it to @mkArtakMSFT and @pranavkm if they want to update the migration guide at the link above to call this package out as one of the examples but from our end, no further follow-up is needed.

**Comment by jiangzeng01** [comment]
@PriyaPurkayastha Noted. Thanks for update
