### ISSUE TITLE
Broken WebSockets with Hosting 5.0.0 when using console apps

### ISSUE THREAD

**Issue by yasserjarouf** [dotnet/aspnetcore#29884]
# Issue Title

WebSockets fail to connect `context.WebSockets.AcceptWebSocketAsync().Result` with the recent **Microsoft.Extensions.Hosting release 5.0.0** on console apps

# General

To build a basic WebSockets server I used to build with a WebHostBuilder with to UseKestrel() and UseUrls().

It was working if used:
`<PackageReference Include="Microsoft.Extensions.Hosting" Version="3.1.5" />`
`<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="3.1.5" />`
`<PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="3.1.5" />`

But not with this:
`<PackageReference Include="Microsoft.Extensions.Hosting" Version="5.0.0" />`
`<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="5.0.0" />`
`<PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="5.0.0" />`

-------------------------------------------
It's throwing an aggregate exception as:

**Message:**
Object reference not set to an instance of an object.
**Source:**
Microsoft.AspNetCore.Server.Kestrel.Core
**Trace:**
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.CreateResponseHeader(Boolean appCompleted)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProduceStart(Boolean appCompleted)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.InitializeResponseAsync(Int32 firstWriteByteCount)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.FlushAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<Microsoft-AspNetCore-Http-Features-IHttpUpgradeFeature-UpgradeAsync>d__303.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.WebSockets.WebSocketMiddleware.UpgradeHandshake.<AcceptAsync>d__7.MoveNext()

**Comment by BrennanConroy** [comment]
Can you provide a simple repro app?

**Comment by halter73** [comment]
My guess is there's some mismatched dependencies. This can happen because our packages don't specify maximum versions for dependency. I'm definitely interested in a repro app in case there's a way we can provide a clearer/earlier error.

If you're just interested in fixing your app, rather than using PackageReferences, I recommend targeting the [ASP.NET Core Web SDK](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/web-sdk?view=aspnetcore-5.0).
