### ISSUE TITLE
AppendTargetFrameworkToOutputPath=false leads to an error in BlazorWebAssembly

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#29939]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/AppendTargetFrameworkToOutputPathfalse-/1329250)._

---
[severity:It bothers me. A fix would be nice]
When I add `<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>` to my project file (default Blazor Web Assembly Project, with HTTPS and PWA checked) it leads to an error if the `obj` folder and `bin` folder were deleted before (.NET 5).

The `Microsoft.NET.Sdk.BlazorWebAssembly.ServiceWorkerAssetsManifest.targets` file from the sdk 5.0.102 seems to have a problem when the target framework folder is missing.

Error Message:
``` shell
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "GenerateServiceWorkerAssetsManifest" task failed unexpectedly.
System.IO.DirectoryNotFoundException: Could not find a part of the path '<ProjectFolder>\obj\Debug\net5.0\service-worker-assets.js'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream.. ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at Microsoft.NET.Sdk.BlazorWebAssembly.GenerateServiceWorkerAssetsManifest.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder. <ExecuteInstantiatedTask>d__26.MoveNext()	Clairvoyant.Application	C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.ServiceWorkerAssetsManifest.targets	68	
```

The "problem" task:
``` xml
<GenerateServiceWorkerAssetsManifest
      Version="$(ServiceWorkerAssetsManifestVersion)"
      Assets="@(_ServiceWorkItem)"
      OutputPath="$(_ServiceWorkerAssetsManifestIntermediateOutputPath)">
      <Output TaskParameter="CalculatedVersion" PropertyName="_ServiceWorkerAssetsManifestVersion" />
    </GenerateServiceWorkerAssetsManifest>
```

Greetings
Felix

---
#### Feedback Bot on 2/3/2021, 07:15 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by SimonCropp** [comment]
in `Microsoft.NET.Sdk.BlazorWebAssembly.ServiceWorkerAssetsManifest` there is:

```
   <PropertyGroup>
      <_ServiceWorkerAssetsManifestIntermediateOutputPath Condition="'$([System.IO.Path]::IsPathRooted($(BaseIntermediateOutputPath)))' == 'true'">obj\$(Configuration)\$(TargetFramework)\$(ServiceWorkerAssetsManifest)</_ServiceWorkerAssetsManifestIntermediateOutputPath>
      <_ServiceWorkerAssetsManifestIntermediateOutputPath Condition="'$([System.IO.Path]::IsPathRooted($(BaseIntermediateOutputPath)))' != 'true'">$(IntermediateOutputPath)$(ServiceWorkerAssetsManifest)</_ServiceWorkerAssetsManifestIntermediateOutputPath>
      <_ServiceWorkerAssetsManifestFullPath>$([System.IO.Path]::GetFullPath('$(MSBuildProjectDirectory)/$(_ServiceWorkerAssetsManifestIntermediateOutputPath)'))</_ServiceWorkerAssetsManifestFullPath>
    </PropertyGroup>
```

the `obj\$(Configuration)\$(TargetFramework)\` is incorrect. i would assume it should make use of `$(TargetDir)` instead?

**Comment by SimonCropp** [comment]
FYI also occurs in net6

**Comment by SimonCropp** [comment]
i would assume it also breaks for `<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>`

**Comment by SteveSandersonMS** [comment]
We think this is actually the same issue as https://github.com/dotnet/aspnetcore/issues/29893, so closing in favour of that.
