### ISSUE TITLE
Problems with running app on Azure App Services

### ISSUE THREAD

**Issue by qfyra** [dotnet/aspnetcore#30017]
I'm here to tell you that deploying the latest Visual Studio 2019 version of the .NET Core 3.1 web API template to a brand new basic instance in Azure does not work, and neither does deploying the template to a previously known working instance, nor does deploying existing previously working code to an existing previously working instance. 

And to be clear, my main issue is that my custom code doesn't work anymore in Azure because reasons that are still unknown to me. The template code issues I don't really care about, it was just something I noticed while troubleshooting my own issues. 

---

Several months back my .NET Core 3.1 API hosted on the Free/Shared tier in Azure stopped working. It had worked before for several months, but for some reason it stopped working. I didn't have time to troubleshoot it back then and I didn't save any error messages. My bad for not taking the issue serious back then of course, but I've learned to not expect any sort of meaningful uptime nor long-term feature correctness using Azure. Things just seem to stop being supported, seemingly willy nilly and without any notice. I guess we've all agreed to this in a some EULA somewhere. I figured since the code still wasn't anywhere near ready for production and this was a Free tiered test server/service instance I might as well just continue to develop and run things locally. 

Yesterday, it was time to deliver all my locally working code to this test server/service instance. Again, it was previously working, it stopped working a few months back, and when deploying my new code I got exceptions in the logs:

```
System.TypeInitializationException: The type initializer for 'Microsoft.Data.SqlClient.SqlAuthenticationProviderManager' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.21.1.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'. The system cannot find the file specified.
File name: 'Microsoft.Identity.Client, Version=4.21.1.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'
   at Microsoft.Data.SqlClient.ActiveDirectoryAuthenticationProvider..ctor(String applicationClientId)
   at Microsoft.Data.SqlClient.SqlAuthenticationProviderManager..cctor()

--- End of inner exception stack trace ---
   at Microsoft.Data.ProviderBase.DbConnectionPool.CheckPoolBlockingPeriod(Exception e)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at XXXXXXX.Data.Sinks.LegDb.DataAccess.SqlRetryPolicyService.<>c__DisplayClass13_0`1.<<WithRetry>b__0>d.MoveNext() in C:\Users\UUUUUUU\Source\Repos\qfyra\XXXXXXX\XXXXXXX\Data\Sinks\LegDb\DataAccess\SqlRetryPolicyService.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at XXXXXXX.Data.Sinks.LegDb.DataAccess.SqlRetryPolicyService.WithRetry[T](SqlConnection con, Func`2 process) in C:\Users\UUUUUUU\Source\Repos\qfyra\XXXXXXX\XXXXXXX\Data\Sinks\LegDb\DataAccess\SqlRetryPolicyService.cs:line 102
   at XXXXXXX.Data.Sinks.LegDb.DataAccess.LegDbDataAccess.SelectCustomerIsRegisteredInKontakt(Int32 id) in C:\Users\UUUUUUU\Source\Repos\qfyra\XXXXXXX\XXXXXXX\Data\Sinks\LegDb\DataAccess\LegDbDataAccess.cs:line 488
   at XXXXXXX.Data.Sinks.LegDb.Services.LegacySyncService.GetCustomerIsRegisteredInKontakt(Int32 id) in C:\Users\UUUUUUU\Source\Repos\qfyra\XXXXXXX\XXXXXXX\Data\Sinks\LegDb\Services\LegacySyncService.cs:line 36
   at XXXXXXX.Api.LegacySyncController.GetCustomerIsRegisteredInKontakt(Int32 id) in C:\Users\UUUUUUU\Source\Repos\qfyra\XXXXXXX\XXXXXXX\Api\LegacySyncController.cs:line 62
```

Again, the app is a .NET Core 3.1 web API. It doesn't use any of the authentication endpoints in Azure so I was surprised to see issues pointing to authentication and Microsoft.Identity.Client. I'm using Polly btw. The real Polly. Not the Microsoft.Extensions.Http.Polly. In fact, I'll give you the full list of packages:

```
	<ItemGroup>
		<PackageReference Include="CompareNETObjects" Version="4.71.0" />
		<PackageReference Include="Dapper" Version="2.0.78" />
		<PackageReference Include="Microsoft.ApplicationInsights" Version="2.16.0" />
		<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.16.0" />
		<PackageReference Include="Microsoft.Azure.EventGrid" Version="3.2.0" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="2.1.1" />
		<PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
		<PackageReference Include="Polly" Version="7.2.1" />
		<PackageReference Include="Polly.Extensions.Http" Version="3.0.0" />
	</ItemGroup>
```

So yeah, pretty basic stuff. The app obviously fails trying to connect to the database, but only when running in Azure. Locally it connects fine. Going to Kudu/SCM console: 

```
D:\home\site\wwwroot>dotnet XXXXXXXX.exe
F
ailed to load the dll from [D:\home\site\wwwroot\hostpolicy.dll], HRESULT: 0x800700C1
An error occurred while loading required library hostpolicy.dll from [D:\home\site\wwwroot\]

D:\home\site\wwwroot>dotnet XXXXXXXX.dll
F
ailed to load the dll from [D:\home\site\wwwroot\hostpolicy.dll], HRESULT: 0x800700C1
An error occurred while loading required library hostpolicy.dll from [D:\home\site\wwwroot\]
D:\home\site\wwwroot> 
```

No help there... and yes, it puts an F on a single row like that. I have no idea why. I stopped questioning these things a long time ago. 

So I figure, since it works locally but not in Azure, it's an Azure runtime issue. I've seen it many times before: some portions of the Azure runtime is no longer supported, and without notifying the people that deployed their own code in Azure that depends on these runtime portions, someone at Microsoft just decide to jank the support. It happened multiple times during 2020, and it cost us hundreds of thousands. I get it, you need to move your product ever forward because reasons, and the rest of us just have to keep up. It's cheaper than notifying us, and we agreed to it when we signed up for Azure. 

Since it's an Azure runtime issue, I gathered I should upgrade the SKU from Free to Basic. After all, I want to run this in x64 because the future production environment will be x64, might as well be as similar as possible. So I upgrade. And I think that was a huge mistake, given the amount of time I've had to troubleshoot since.

First of all, the API became extremely sluggish. Not only the response time to even get to the API but the Azure portal too. Trying to see the log stream easily took some 30 seconds to a minute, it's usually delivered inside of 5 seconds.

Second, I just keep getting 503 service unavailable. So instead of a responsive but crashy API, I get a non-reachable API. Switching back to the Free tier didn't help, still 503 rather than the SQL/authentication related error I got above. Here's a small list of other stuff that also didn't help:

- self-contained vs framework-dependent
- produce single file vs not doing that
- enable readytorun compilation vs not doing that

Log stream keep spewing out nonsense about sandboxprox.exe, same thing over and over with 10 second interval. 

```
2021-02-02T11:07:25 env XPROC_TYPENAME=Microsoft.Web.Hosting.Transformers.ApplicationHost.SiteExtensionHelper, Microsoft.Web.Hosting, Version=7.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
2021-02-02T11:07:25 env XPROC_METHODNAME=Transform
2021-02-02T11:07:26 Start 'Microsoft.AspNetCore.AzureAppServices.SiteExtension' site extension transform
2021-02-02T11:07:26 StartSection Executing InsertIfMissing (transform line 7, 23)
2021-02-02T11:07:26 on /configuration/system.webServer
2021-02-02T11:07:26 Applying to 'configuration' element (no source line info)
2021-02-02T11:07:26 EndSection Done executing InsertIfMissing
2021-02-02T11:07:26 StartSection Executing InsertIfMissing (transform line 8, 16)
2021-02-02T11:07:26 on /configuration/system.webServer/runtime
2021-02-02T11:07:26 Applying to 'system.webServer' element (no source line info)
2021-02-02T11:07:26 EndSection Done executing InsertIfMissing
2021-02-02T11:07:26 StartSection Executing InsertIfMissing (transform line 9, 31)
2021-02-02T11:07:26 on /configuration/system.webServer/runtime/environmentVariables
2021-02-02T11:07:26 Applying to 'runtime' element (no source line info)
2021-02-02T11:07:26 EndSection Done executing InsertIfMissing
2021-02-02T11:07:26 StartSection Executing InsertOrAppendAttribute (transform line 10, 406)
2021-02-02T11:07:26 on /configuration/system.webServer/runtime/environmentVariables/add[@name='DOTNET_ADDITIONAL_DEPS']
2021-02-02T11:07:26 Applying to 'environmentVariables' element (no source line info)
2021-02-02T11:07:26 EndSection Done executing InsertOrAppendAttribute
2021-02-02T11:07:26 StartSection Executing InsertOrAppendAttribute (transform line 11, 158)
2021-02-02T11:07:26 on /configuration/system.webServer/runtime/environmentVariables/add[@name='DOTNET_SHARED_STORE']
2021-02-02T11:07:26 Applying to 'environmentVariables' element (no source line info)
2021-02-02T11:07:26 EndSection Done executing InsertOrAppendAttribute
2021-02-02T11:07:26 StartSection Executing InsertOrAppendAttribute (transform line 12, 146)
2021-02-02T11:07:26 on /configuration/system.webServer/runtime/environmentVariables/add[@name='ASPNETCORE_HOSTINGSTARTUPASSEMBLIES']
2021-02-02T11:07:26 Applying to 'environmentVariables' element (no source line info)
2021-02-02T11:07:26 EndSection Done executing InsertOrAppendAttribute
2021-02-02T11:07:26 Successful 'D:\home\SiteExtensions\Microsoft.AspNetCore.AzureAppServices.SiteExtension\applicationHost.xdt' site extension transform
2021-02-02T11:07:26 sandboxproc.exe complete successfully. Elapsed = 649.00 ms
```

Makes absolutely no sense to me. Web service logs were non exsistent. Literally nothing. Restarting the service didn't help. Logs queries doesn't work because diagnostic settings (preview) doesn't consume logs even when configured to consume all the logs, so there's no data to analyze. The Availability and Performance provides no useful information at all, just stuff that I already know, like you're getting 503, yeah duh, I know. 

What possible conclusions can one draw from this? Well, obviously there's something wrong with my code. So I'll just go ahead and create a new API from scratch using the Visual Studio template. Here's what I did in detail: 

1. select the ASP.NET Core Web Application template.
2. create a .NET Core 3.1 API with no authentication, configured for HTTPS
3. set platform target to x64 for all build configurations
4. run the API locally and get a browser pointing to https://localhost:44359/weatherforecast which deliveres the expected template results
5. create a publish profile pointing to the previously working target/app service instance
6. set target runtime to x64

But again, regardless of trying all these settings: 
- self-contained vs framework-dependent
- produce single file vs not doing that
- enable readytorun compilation vs not doing that

... I just get the same 503 Service Unavailable. Web server log stream says nothing. Application log stream keeps doling out nonsense about sandboxproc.exe every ten seconds. Restarting doesn't help. Logs queries doesn't work. The Availability and Performance provides no useful information at all. 

Conclusion: Something is wrong with the App Service in Azure. So I deploy to a brand new Basic Tier target. Same issue, 503. 

Maybe it's the x64 that cases issues? I created a new API from scratch, didn't touch anything in the publish profile, just deployed. 

Finally getting something else, 500.30 ANCM In-Process Start Failure. Going to Kudu/SCM:

```
D:\home\site\wwwroot>dotnet TestApi02.dll
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'D:\home\site\wwwroot\TestApi02.dll'. An attempt was made to load a program with an incorrect format.
File name: 'D:\home\site\wwwroot\TestApi02.dll'

D:\home\site\wwwroot>dotnet TestApi02.exe
Error:
  An assembly specified in the application dependencies manifest (TestApi02.deps.json) has already been found but with a different file extension:
    package: 'TestApi02', version: '1.0.0'
    path: 'TestApi02.dll'
    previously found assembly: 'D:\home\site\wwwroot\TestApi02.exe'
```

No idea what that means, pretty incomprehensible errors if you ask me. So, researching 500.30 ANCM In-Process Whatever, turns out you can change hosting model to "out of proces"s in the debug section of the project (shoutout to random guy on Stackoverflow because that's how we develop code these days, by going to Stackoverflow). I have no idea what it means, and I have no idea why I have to do it to get template code working on a brand new host, but doing so actually works. Again: brand new API with template code from the lastest Visual Studio 2019, deployed to a brand new Basic instance without touching any of the publication settings, yields a 500.30 ANCM Whatever error until you switch hosting hosting model to out of process. And switching back to In-Process again it still works, even though In Process didn't work moments earlier. 

Fingers crossed, I do this on my existing project code on the existing App Service target. Neither out of process nor in process works. Still getting 503 Service Unavailable. 

These are my questions in order of priority:

1. How do I solve this problem for my existing instance? (Again, I don't care about the templates, I care about my code. If you fix the templates, fine, but I want to fix my code. That's the main issue here, not the templates.)
2. Why exactly is this happening all of a sudden to previously good configurations?
3. Explain in detail why you are not performing regression testing of your template code. I mean this is bad. Knowing that Microsoft doesn't do regression testing is bad for business, yours and mine. 
4. Obviously, something that was previously working isn't working anymore, and obviously it's because you discontinued something without notification. Tell me, what exactly I am supposed to subscribe to in order to get notified about stuff that you discontinue well before you actually discontinue them? I want concrete examples of what to subscribe to that curates the information down to only the stuff I use. I don't care if you discontinue something in F# or even .Net Framework. If my runtime is specifically .NET Core 3.1 and is using e.g. Polly, which you can determine programmatically, I only want to see stuff that relates to specifically .NET Core 3.1 and Polly. Computing is deterministic. The issues I describe above can be derived to an earlier event in Azure. That particular event, whatever it may be, must have been documented somewhere well before it actually happened, no? I want to see that piece of information. I want to see the time and date it was published, to determine if we were actually warned beforehand. Why do I want this? Because I'm a contractor, and I still have a modicum of vocational pride, and I want to leave things in order. Once I leave this assignment, the stuff I'm developing needs to be able to run uninterrupted for years (you know just like it did back when we used to host on our own hardware). What direction should I give to the next poor sod that have to deal with this? "If something breaks you'll hear about it from your end users" is not a very good SLA.

**Comment by jkotalik** [comment]
> How do I solve this problem for my existing instance? (Again, I don't care about the templates, I care about my code. If you fix the templates, fine, but I want to fix my code. That's the main issue here, not the templates.)

I don't know if there is much we can do to directly investigate this; Azure support is probably a better channel to go through here. From a high level glance, the error you were getting seems to potentially be an issue with the installation of .NET on the Azure Site. It seems like that error could also be due to a bitness mismatch as well. Logs may help diagnose what's going on https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/logging-and-diagnostics?view=aspnetcore-5.0.

We do testing everyday to make sure deployment to azure with our templates work, so I'm more inclined to believe this is an issue on App Services/ the dotnet installation on app services.

Going to close for now, again I'd recommend going through azure support for this.
