### ISSUE TITLE
options.EnableLdap throws DirectoryOperationException: An operation error occurred

### ISSUE THREAD

**Issue by freerider7777** [dotnet/aspnetcore#30032]
### Describe the bug

(crosslink to Documentation https://github.com/dotnet/AspNetCore.Docs/issues/21491)

Following the docs on windows authentication, I've come to the point of adding roles to User (options.EnableLdap) on Linux
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-5.0&tabs=visual-studio

### To Reproduce
Just the domains and the code like in the link above. I'm building self contained application an running on Linux.

Exception while processing incoming request:

fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
An unhandled exception has occurred while executing the request.
System.DirectoryServices.Protocols.DirectoryOperationException: An operation error occurred.
at System.DirectoryServices.Protocols.LdapConnection.EndSendRequest(IAsyncResult asyncResult)
at System.Threading.Tasks.TaskFactory1.FromAsyncCoreLogic(IAsyncResult iar, Func2 endFunction, Action1 endAction, Task1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Authentication.Negotiate.LdapAdapter.RetrieveClaimsAsync(LdapSettings settings, ClaimsIdentity identity, ILogger logger)
at Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.HandleAuthenticateAsync()
at Microsoft.AspNetCore.Authentication.AuthenticationHandler1.AuthenticateAsync() at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme) at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task) dbug: Microsoft.AspNetCore.HttpsPolicy.HstsMiddleware[1] The request is insecure. Skipping HSTS header. dbug: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[4] The request path /Home/Error does not match a supported file type dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1001] 1 candidate(s) found for the request path '/Home/Error' dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005] Endpoint 'TestAD2.Controllers.HomeController.Error (TestAD2)' with route pattern '{controller=Home}/{action=Index}/{id?}' is valid for the request path '/Home/Error' dbug: Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware[1] Request matched endpoint 'TestAD2.Controllers.HomeController.Error (TestAD2)' fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[3] An exception was thrown attempting to execute the error handler. System.DirectoryServices.Protocols.DirectoryOperationException: An operation error occurred. at System.DirectoryServices.Protocols.LdapConnection.EndSendRequest(IAsyncResult asyncResult) at System.Threading.Tasks.TaskFactory1.FromAsyncCoreLogic(IAsyncResult iar, Func2 endFunction, Action1 endAction, Task1 promise, Boolean requiresSynchronization) --- End of stack trace from previous location --- at Microsoft.AspNetCore.Authentication.Negotiate.LdapAdapter.RetrieveClaimsAsync(LdapSettings settings, ClaimsIdentity identity, ILogger logger) at Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.HandleAuthenticateAsync() at Microsoft.AspNetCore.Authentication.AuthenticationHandler1.AuthenticateAsync()
at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
fail: Microsoft.AspNetCore.Server.Kestrel[13]
Connection id "0HM6CV9DFB5D7", Request id "0HM6CV9DFB5D7:00000003": An unhandled exception was thrown by the application.
System.DirectoryServices.Protocols.DirectoryOperationException: An operation error occurred.
at System.DirectoryServices.Protocols.LdapConnection.EndSendRequest(IAsyncResult asyncResult)
at System.Threading.Tasks.TaskFactory1.FromAsyncCoreLogic(IAsyncResult iar, Func2 endFunction, Action1 endAction, Task1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Authentication.Negotiate.LdapAdapter.RetrieveClaimsAsync(LdapSettings settings, ClaimsIdentity identity, ILogger logger)
at Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.HandleAuthenticateAsync()
at Microsoft.AspNetCore.Authentication.AuthenticationHandler1.AuthenticateAsync() at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme) at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task) at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi) at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task) at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication1 application)

### Further technical details
- ASP.NET Core version 5.0 
- RHEL 8.2 (Azure)

**Comment by freerider7777** [comment]
ldapwhoami -h mydomain.ru 
gives the same exception, seems like some steps are needed in instruction to adding linux to domain

**Comment by recalde** [comment]
What are the linux pre-requisits other than apt-get libldap-2.4-2?

Do we need an ldap.config? Any additional env exports? Do we **need** to install realmd and join to the controller?  Is there an easy way for more detailed error messages?

**Comment by recalde** [comment]
ldap-utils doesn't require etc/ldap/ldap.config as long as you pass the host and machine account dn and pw so I am going forward with the assumption that the dotnet libraries would not either since these are direct inputs to the configuration.

**Comment by recalde** [comment]
@freerider7777 have you tried setting your machine account as fqdn instead of just account name?  I haven't finished testing the auth middleware but that's one difference between windows and linux worked on a manual bind and search.

CN=SVC_ACCOUNT_123,OU=ServiceAccounts,DC=domain,DC=company,DC=com

**Comment by freerider7777** [comment]
@recalde I've followed the documentation
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-5.0&tabs=visual-studio
with only difference that my machine's name is "linux"
Authorization works fine, but ldap doesn't...
ktpass -princ HTTP/mywebservice.mydomain.com@MYDOMAIN.COM -pass myKeyTabFilePassword -mapuser MYDOMAIN\mymachine$ -pType KRB5_NT_PRINCIPAL -out c:\temp\mymachine.HTTP.keytab -crypto AES256-SHA1

**Comment by JunTaoLuo** [comment]
FYI, there are two ways of configuring LDAP for aspnetcore:
1. Directly specify `Domain`, `MachineAccountName`, and `MachineAccountPassword`
2. For domain joined machines, specify the `Domain` and the default machine credentials will be used

The exception from `System.DirectoryServices` isn't very informative but maybe @joperezr could help debug further.

**Comment by recalde** [comment]
> FYI, there are two ways of configuring LDAP for aspnetcore:
> 1. Directly specify `Domain`, `MachineAccountName`, and `MachineAccountPassword`
> 2. For domain joined machines, specify the `Domain` and the default machine credentials will be used
> 
> The exception from `System.DirectoryServices` isn't very informative but maybe @joperezr could help debug further.

I was able to get my connection working by specifying the LdapConnection because the Machine account/Domain method doesn't allow you to specify an ldapUrl however it only works for ~45 minutes before the LdapServer disconnects.  If we just had host on the LdapSettings we could avoid joining domain.

I haven't found any docs on how to join the domain do you use realmd?

**Comment by freerider7777** [comment]
@recalde If the question is how to join the domain, there is a link from this doc:
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-5.0&tabs=visual-studio
search for "Instructions for joining a Linux or macOS machine to a Windows domain" and you get here:
https://docs.microsoft.com/en-us/sql/azure-data-studio/enable-kerberos?view=sql-server-2017#join-your-os-to-the-active-directory-domain-controller

**Comment by assafSabag** [comment]
Hi There,
I'm experiencing the same issue as well, but i'm not interested in joining the machine to the domain (it will eventually run on a Docker container).

Authentication works perfect, only authorization based on groups membership is failing.
same error as above.

I have tries the MachineAccountName and MachineAccountPassword but not sure i did it properly (is there a guide for that? https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-5.0&tabs=visual-studio#kerberos-authentication-and-role-based-access-control-rbac refers to it as just do it)

Any tips?

Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.DirectoryServices.Protocols.DirectoryOperationException: An operation error occurred.
         at System.DirectoryServices.Protocols.LdapConnection.EndSendRequest(IAsyncResult asyncResult)
         at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Authentication.Negotiate.LdapAdapter.RetrieveClaimsAsync(LdapSettings settings, ClaimsIdentity identity, ILogger logger)
         at Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.HandleAuthenticateAsync()
         at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
         at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by JunTaoLuo** [comment]
Given that the LDAP settings `MachineAccountName` and `MachineAccountPassword` are just strings so I don't think it'd be hard to configure. The error looks like something that @joperezr might be able to help with.

**Comment by assafSabag** [comment]
@joperezr  So do you think it is possible to use Kerberos authentication and role-based access control without join the machine to the domain?

**Comment by JunTaoLuo** [comment]
Oops, I meant to respond earlier but I spoke with @joperezr and it turns out there are [improvements](https://github.com/dotnet/runtime/pull/47703) made to the error messages that will be available in the upcoming 6.0-preview3 release. Upgrading to the preview release when it is available should help shed more light on the underlying problem.
