### ISSUE TITLE
BlazorSignalRApp sample app throws an error when running from Visual Studio Code

### ISSUE THREAD

**Issue by nosnetrom** [dotnet/aspnetcore#30048]
cc: @guardrex 

I ran the sample app (https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor-webassembly) in VS2019 with no problems, but Visual Studio Code threw the following error:

`crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Response status code does not indicate success: 404 (Not Found).
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync(Uri url, HttpClient httpClient, ILogger logger, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.GetNegotiationResponseAsync(Uri uri, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat, CancellationToken cancellationToken)
   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
   at BlazorSignalRApp.Client.Pages.Index.OnInitializedAsync() in C:\Users\jmortenson\BlazorSignalRApp\Client\Pages\Index.razor:line 48
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)`

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by guardrex** [comment]
Doc cross-reference: https://docs.microsoft.com/en-us/aspnet/core/tutorials/signalr-blazor?view=aspnetcore-5.0&tabs=visual-studio&pivots=webassembly

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.

@guardrex can you repro this? If yes, please work with @BrennanConroy to diagnose and find out what's the culprit here. Let's get the sample fixed.

**Comment by guardrex** [comment]
I didn't repro the last time that I tested, but I usually perform testing in VS and CLI. I'll take a look first thing Thursday morning.

@nosnetrom ... Can you put your entire solution up in a GH repo, including the **Server** app's `.vscode` folder with the `launch.json` and `tasks.json` files?

**Comment by nosnetrom** [comment]
@guardrex — I’ve posted it at GitHub.com/nosnetrom/blazorsignalrsampleapp.

**Comment by guardrex** [comment]
Thanks ... I'll take a look :eyes: first thing tomorrow morning.

**Comment by guardrex** [comment]
@nosnetrom ... The solution is configured to run from the **Client** project, but all hosted solutions should be run from the **Server** project. I opened (and you can see the issue for guidance on fixing it) ...

https://github.com/dotnet/AspNetCore.Docs/issues/21524

This issue can be closed.
