### ISSUE TITLE
Virtualize: A task was canceled

### ISSUE THREAD

**Issue by NHodgesVFX** [dotnet/aspnetcore#30086]
### Describe the bug
When using a virtualize component the error below gets printed some times when scrolling, about 1 minute after the user closes the page or sometimes when force closing with control + c. I could be wrong but it appears this prevents memory from being freed. Appears to be the same or similar to https://github.com/dotnet/aspnetcore/issues/28280

### To Reproduce

https://github.com/NHodgesVFX/BlazorVirtualizationError

1.  Run the app
2. Scroll through the list of guids for a moment or 2
3. close the page
4. wait about a minute the error will appear.

The error will also sometimes appear during scrolling or closing with control +c

### Exceptions (if any)

```
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'ogKHvaqZGOoxGf8bEI329nJxrVCmnwIoVjTacnZb_Dc'.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at Microsoft.AspNetCore.Components.Web.Virtualization.VirtualizeJsInterop.DisposeAsync()
         at Microsoft.AspNetCore.Components.Web.Virtualization.Virtualize`1.DisposeAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<Dispose>g__HandleAsyncExceptions|52_0(List`1 tasks)
```

### Further technical details
- ASP.NET Core version 5.0.0
- The IDE VSCode 1.53.1

dotnet --info

```
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

```

**Comment by Liero** [comment]
It seems to be reproducible a problem also when there is a Task.Delay in the ItemsProvider callback:

   private async ValueTask<ItemsProviderResult<Item>> ProvideItems(ItemsProviderRequest request)
   {

          using var db = _dbContextFactory.CreateDbContext();
          await Task.Delay(200, request.CancellationToken);
          var items = await db.Items.Skip(request.StartIndex)
                .Take(request.Count)
                .ToArrayAsync(request.CancellationToken);
          return new ItemsProviderResult<Item>(items,  await db.Items.CountAsync());
   }
   
   shouldn't be the TaskCancelledExpception handled by the Virtualize component itself?

**Comment by mikes-gh** [comment]
Is it here?
https://github.com/dotnet/aspnetcore/blob/5577c0d128fd30d800f434e6a629978916f7d64e/src/Components/Web/src/Virtualization/VirtualizeJsInterop.cs#L47
Doesn't seem to handle Task Cancelled

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is already fixed as part of #32808
