### ISSUE TITLE
Blazor WASM Fails to build in Azure Pipelines

### ISSUE THREAD

**Issue by dansiegel** [dotnet/aspnetcore#30200]
### Describe the bug

Using a standard Build task for all of my ASP.NET Core projects as shown below, the build will fail when building a Blazor WASM Project

```yaml
- task: VSBuild@1
  inputs:
    solution: ${{ parameters.project }}
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(Build.ArtifactStagingDirectory)\$(Build.BuildId).zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
```

### To Reproduce

- Create a Blazor WASM project with .NET 5
- Use the build snippet from above
- Let Azure Pipelines build

### Exceptions (if any)

```
CopyFilesToOutputDirectory:
  Copying file from "D:\a\1\s\src\SponsorConnect.Client\obj\Any CPU\Release\net5.0\SponsorConnect.Client.dll" to "D:\a\1\s\src\SponsorConnect.Client\bin\Any CPU\Release\net5.0\SponsorConnect.Client.dll".
  SponsorConnect.Client -> D:\a\1\s\src\SponsorConnect.Client\bin\Any CPU\Release\net5.0\SponsorConnect.Client.dll
  Copying file from "D:\a\1\s\src\SponsorConnect.Client\obj\Any CPU\Release\net5.0\SponsorConnect.Client.pdb" to "D:\a\1\s\src\SponsorConnect.Client\bin\Any CPU\Release\net5.0\SponsorConnect.Client.pdb".
##[error]C:\Program Files\dotnet\sdk\5.0.103\Sdks\Microsoft.NET.Sdk.BlazorWebAssembly\targets\Microsoft.NET.Sdk.BlazorWebAssembly.ServiceWorkerAssetsManifest.targets(68,5): Error MSB4018: The "GenerateServiceWorkerAssetsManifest" task failed unexpectedly.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\a\1\s\src\SponsorConnect.Client\obj\Release\net5.0\service-worker-assets.js'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at Microsoft.NET.Sdk.BlazorWebAssembly.GenerateServiceWorkerAssetsManifest.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

```

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We will address this as part of investigation we'll do for #29626
