### ISSUE TITLE
[Flaky test] Microsoft.NET.Sdk.Razor.Tests.StaticWebAssetsIntegrationTest.Publish_WithBuildReferencesDisabled_CopiesStaticWebAssetsToDestinationFolder

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#30245]
Failing build: https://dev.azure.com/dnceng/public/_build/results?buildId=998044&view=ms.vss-test-web.build-test-results-tab&runId=31231730&resultId=100410&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

```
Output:
> /tmp/helix/working/AEF70952/p/d/dotnet msbuild /t:Build /private/tmp/helix/working/AEF70952/w/AB2509D1/e/testExecutionDirectory/Publish_WithB---ECC36767/AppWithPackageAndP2PReference/AppWithPackageAndP2PReference.csproj /restore

Welcome to .NET 6.0!
---------------------
SDK Version: 6.0.100-ci

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
Microsoft (R) Build Engine version 16.10.0-preview-21112-04+f0eebf287 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Determining projects to restore...
Exit Code: 139
```

**Comment by pranavkm** [comment]
139 is a segfault but there aren't any dumps to go with the failing test. There isn't a specific problem with the test itself, but we can use this as a way to drive getting diagnostics plugged in.

**Comment by BrennanConroy** [comment]
You missed the stderr output:
```
StdErr:
[m[37m      
[m[37m      
[m[30;1m      Stack Trace:
[m[37m           at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
[m[37m           at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
[m[37m           at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
[m[37m           at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
[m[37m        /_/src/Tests/Microsoft.NET.TestFramework/Assertions/CommandResultAssertions.cs(32,0): at Microsoft.NET.TestFramework.Assertions.CommandResultAssertions.Pass()
[m[37m        /_/src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsIntegrationTest.cs(127,0): at Microsoft.NET.Sdk.Razor.Tests.StaticWebAssetsIntegrationTest.Publish_WithBuildReferencesDisabled_CopiesStaticWebAssetsToDestinationFolder()
```

Also, there is a `core.<process id>` file for the crash.

**Comment by captainsafia** [comment]
This test has been moved to the SDK repo but it is still skipped:

https://github.com/dotnet/sdk/blob/a30e465a2e2ea4e2550f319a2dc088daaafe5649/src/Tests/Microsoft.NET.Sdk.Razor.Tests/StaticWebAssetsIntegrationTest.cs#L120-L121

When I last tinkered with this (during the SDK migration) it was failing pretty consistently so I'm thinking there might be a logic bug in this.

**Comment by javiercn** [comment]
We don't have this test anymore
