### ISSUE TITLE
jsRuntime.InvokeAsync can't return null as Nullable<Guid>

### ISSUE THREAD

**Issue by Regenhardt** [dotnet/aspnetcore#30366]
### Describe the bug

Looks very similar to !10565 :

I'm trying to read a Guid from local storage, so I go `return jsRuntime.InvokeAsync<Guid?>("localStorage.getItem", key);`.
When there is a guid, this works fine. 
But if there isn't a guid, I get this exception:
`System.InvalidCastException: Null object cannot be converted to a value type.`

Am I supposed to box my guid or what?

### To Reproduce

Make a Blazor WASM project. 
Add `jsRuntime.InvokeAsync<Guid?>("localStorage.getItem", key);` somewhere. init of Index.razor should be fine (in my project it happens somewhere 3 levels down asynchronously).
Execute.

### Exceptions (if any)

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: An exception occurred executing JS interop: Null object cannot be converted to a value type.. See InnerException for more details.
Microsoft.JSInterop.JSException: An exception occurred executing JS interop: Null object cannot be converted to a value type.. See InnerException for more details.
 ---> System.InvalidCastException: Null object cannot be converted to a value type.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType)
   at Microsoft.JSInterop.Infrastructure.TaskGenericsUtil.TcsResultSetter`1[[System.Nullable`1[[System.Guid, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetResult(Object tcs, Object result)
   at Microsoft.JSInterop.Infrastructure.TaskGenericsUtil.SetTaskCompletionSourceResult(Object taskCompletionSource, Object result)
   at Microsoft.JSInterop.JSRuntime.EndInvokeJS(Int64 taskId, Boolean succeeded, Utf8JsonReader& jsonReader)
   --- End of inner exception stack trace ---
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__15`1[[System.Nullable`1[[System.Guid, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at TeamBuilder_Website.Services.LocalStorage.<Get>d__3`1[[System.Nullable`1[[System.Guid, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at TeamBuilder_Website.Services.AppState.RetrieveStoredToken()
   at TeamBuilder_Website.Services.AppState.<.ctor>b__13_0()
   at TeamBuilder_Website.Services.AppState.WaitForInit()
   at TeamBuilder_Website.Services.AccountService.TryLoginFromStoredToken()
   at TeamBuilder_Website.Services.AccountService.IsAuthorized(Guid loginToken)
   at TeamBuilder_Website.Pages.Index.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```
### Further technical details
- SDK: Microsoft.NET.Sdk.BlazorWebAssembly
- Target framework: net5.0
- Include the output of `dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS2019 Version 16.8.4

**Comment by TanayParikh** [comment]
This should be closely related to / encountered within https://github.com/dotnet/aspnetcore/issues/25677.

**Comment by Regenhardt** [comment]
I think this issue could be solved by changing [this line](https://github.com/dotnet/aspnetcore/blob/23ea496cee168bdd8f7ed3c6d85ec78dbecc99f4/src/JSInterop/Microsoft.JSInterop/src/Infrastructure/TaskGenericsUtil.cs#L90) to use a safe cast instead of pattern matching, which seems to properly handle the conversion to a nullable value type:

![image](https://user-images.githubusercontent.com/10476293/192146567-49ed0567-6e82-4f0c-9e09-50e77e1e9479.png)

Should I create a pull request to change it to

`var typedResult = result as T 
    ??  (T)Convert.ChangeType(result, typeof(T), CultureInfo.InvariantCulture)!;`

?

**Comment by Regenhardt** [comment]
@mkArtakMSFT absolutely, I made a PR. I did realize on the way that my initial idea wouldn't work either because `Convert.ChangeType` would of course be called on `null ??`. I do wonder if this should be a change in `Convert.ChangeType` instead though.
