### ISSUE TITLE
VSCode: CodeLens references numbers did not load and the output window contain error "Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object." when doing the Razor refactoring

### ISSUE THREAD

**Issue by NTaylorMullen** [dotnet/aspnetcore#30554]
**Azure DevOps work item:** https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1284417

**Testcases Affected**

[[6.0] SimpleWebAppRazorEditingWithVSCode](https://github.com/aspnet/Tooling-ManualTests/blob/rel/16.8/E2EWalkthroughs/VS/AspNetCore30/30_SimpleWebAppRazorEditingWithVSCode.md)
[[6.0] SimpleBlazorRazorEditingWithVSCode](https://github.com/aspnet/Tooling-ManualTests/blob/rel/16.8/E2EWalkthroughs/VS/AspNetCore30/30_SimpleBlazorRazorEditingWithVSCode.md)

**Platform**
- [x] Windows
- [x] macOS
- [ ] Linux

**Repro Steps**
1. Create an MVC project and open via VS Code:
```
md MVC
cd MVC
dotnet new mvc
code .
```
2. Go to https://github.com/OmniSharp/omnisharp-vscode/releasesinstall the latest csharp-1.23.10-lsp-beta.vsix.
3. Open Pages/Shared/_Layout.cshtml
4. Type "@add" and verify the intellisense list. Select "addTagHelper", then type "*, Microsoft.AspNetCore.Mvc.TagsHelpers" following it. Save the change.
5. In VS Code, using CTRL + ~ to open up TERMINAL window, type the following code.
```       
'namespace MVC // Or Razor
{
    public class CustomTagHelper
    {
    }
}' | Out-File CustomTagHelper.cs
```
   6. In CustomTagHelper.cs, type ": TagHelper" following the class. And then select "using Microsoft.AspNetCore.Razor.TagHelpers" through the Quick Actions
   7. In _Layout.cshtml, type "@addTagHelper *, MVC
   8. Open Program.cs, then enter the code: `public interface ICheese {}` above public class Program and save
   9. Edit Index.cshtml to include the following at the bottom:
```
@{ var x = typeof(Program); }
@functions {
 public class Cheddar : ICheese {}
}
```
11. Save and close Index.cshtml
12. Close all instances of VSCode and re-open this project.
13. go to the program.cs file

**Note:** 
1. It works well on 5.0 Project
2. It works well on 6.0 Preview 1

**Actual Result**

CodeLens references numbers did not load and the output window contain error "Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object."
![image](https://user-images.githubusercontent.com/55483444/109145575-9c40df00-779d-11eb-927c-db1e47e8ad97.png)

**Error Log**

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.

   at OmniSharp.Helpers.LocationExtensions.<>c__DisplayClass0_0.<GetQuickFix>b__3(Document d) in D:\a\1\s\src\OmniSharp.Roslyn.CSharp\Helpers\LocationExtensions.cs:line 45

   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)

   at OmniSharp.Helpers.LocationExtensions.<GetQuickFix>g__GetSourceText|0_0(Location location, IEnumerable`1 documents, Boolean hasMappedPath) in D:\a\1\s\src\OmniSharp.Roslyn.CSharp\Helpers\LocationExtensions.cs:line 45

   at OmniSharp.Helpers.LocationExtensions.GetQuickFix(Location location, OmniSharpWorkspace workspace) in D:\a\1\s\src\OmniSharp.Roslyn.CSharp\Helpers\LocationExtensions.cs:line 19

   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()

   at System.Linq.Enumerable.<DistinctIterator>d__64`1.MoveNext()

   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)

   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()

   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)

   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)

   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)

   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)

   at OmniSharp.Protocol.Packet.ToString() in D:\a\1\s\src\OmniSharp.Host\Protocol\Packet.cs:line 22

   at System.IO.TextWriter.WriteLine(Object value)

   at System.IO.TextWriter.SyncTextWriter.WriteLine(Object value)

   at OmniSharp.Services.SharedTextWriter.ProcessWriteQueue() in D:\a\1\s\src\OmniSharp.Host\Services\SharedTextWriter.cs:line 48

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Threading.ThreadHelper.ThreadStart()

**Comment by Yuyue960724** [comment]
We ran into this issue on Mac/Linux with latest .NET 6.0 Preview 3 build and there are some fail logs as following and check "https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1284417" for more details
![image](https://user-images.githubusercontent.com/66415233/112965339-c1998200-917b-11eb-88a2-9834680e791d.png)

**Comment by EmilyFeng97** [comment]
We ran into this issue in the latest .NET 6.0 Preview 3 build when opening the Program.cs file or reopening the project. And there are some logs as following and check "https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1284417" for more details.
![image](https://user-images.githubusercontent.com/66412474/114372715-6ff9ea00-9bb4-11eb-853c-5fd865f793e5.png)

**Comment by NTaylorMullen** [comment]
@captainsafia @pranavkm I imagine the source generator bit failing in O# is expected?

**Comment by captainsafia** [comment]
Nope -- I haven't seen this before. The only O# related issues we're tracking at the moment occur after the source generators are loaded.

I'm not familiar with how O#'s semantics for loading generators/analyzers differ from VS or the compiling on the CLI so I don't have any hypothesis to this end.

**Comment by jinzhao1127** [comment]
This issue still repro on the latest  csharp-1.23.11.vsix, and there appears a "MISSING command" , when click it , says "command missing not found"
![image](https://user-images.githubusercontent.com/55483444/114506859-ece49c80-9c64-11eb-9b6b-ade7be92b6df.png)

**Comment by pranavkm** [comment]
The source generator error might suggest that it's because the Razor one is referencing too new a source generator version. By too new, it's the same version as the compiler in the SDK, but O# hasn't picked it up. 

Perhaps we should consider pinning this version here: https://github.com/dotnet/sdk/blob/main/src/RazorSdk/SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.csproj#L15 rather than have it float.

**Comment by captainsafia** [comment]
@pranavkm Hmmm. Is there a way for us to know what is considered "too new" my O#?

I'm thinking about scenarios where we want to pick up the most recent version to get a bug fix (like the issues with special characters in filenames) or if we're consuming a new API. It seems a little weird to downgrade for the sake of O# in those scenarios.

**Comment by pranavkm** [comment]
The version of the compiler that is referenced by the source generator shouldn't generally matter since you ultimately get the version that it's loaded in. We can target a minimum version that supports all the features we need (for e.g. when we get incremental source generators we can update). 

That said it's possible that the reported issue is a point in time issue that goes away once O# is updated. Maybe @JoeRobich might be able to help us understand this better?

**Comment by captainsafia** [comment]
> That said it's possible that the reported issue is a point in time issue that goes away once O# is updated. Maybe @JoeRobich might be able to help us understand this better?

Agreed. I haven't seen this pop up in a project I'm working on with the latest C# extension.

```
Starting OmniSharp server at 4/13/2021, 8:10:34 PM
    Target: /Users/captainsafia/Verifications/RerenderExplorations

OmniSharp server started.
    Path: /Users/captainsafia/.vscode/extensions/ms-dotnettools.csharp-1.23.11/.omnisharp/1.37.8/run
    PID: 66842

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on MacOS 11.2.3 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 1 MSBuild instance(s)
            1: StandAlone 16.9.0 - "/Users/captainsafia/.vscode/extensions/ms-dotnettools.csharp-1.23.11/.omnisharp/1.37.8/omnisharp/.msbuild/Current/Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        MSBUILD_EXE_PATH environment variable set to '/Users/captainsafia/.vscode/extensions/ms-dotnettools.csharp-1.23.11/.omnisharp/1.37.8/omnisharp/.msbuild/Current/Bin/MSBuild.exe'
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: StandAlone 16.9.0 - "/Users/captainsafia/.vscode/extensions/ms-dotnettools.csharp-1.23.11/.omnisharp/1.37.8/omnisharp/.msbuild/Current/Bin"
            CscToolExe = csc.exe
            MSBuildToolsPath = /Users/captainsafia/.vscode/extensions/ms-dotnettools.csharp-1.23.11/.omnisharp/1.37.8/omnisharp/.msbuild/Current/Bin
            CscToolPath = /Users/captainsafia/.vscode/extensions/ms-dotnettools.csharp-1.23.11/.omnisharp/1.37.8/omnisharp/.msbuild/Current/Bin/Roslyn
            BypassFrameworkInstallChecks = true
            MSBuildExtensionsPath = /Users/captainsafia/.vscode/extensions/ms-dotnettools.csharp-1.23.11/.omnisharp/1.37.8/omnisharp/.msbuild
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.Completion.CompletionOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in '/Users/captainsafia/Verifications/RerenderExplorations'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        Skip loading projects listed in solution file or under target directory because MsBuild:LoadProjectsOnDemand is true.
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in '/Users/captainsafia/Verifications/RerenderExplorations'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Could not find any CSX files
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location '/Users/captainsafia/Verifications/RerenderExplorations' on host 66764.
[info]: OmniSharp.OmniSharpWorkspace
        Miscellaneous file: /Users/captainsafia/Verifications/RerenderExplorations/Shared/MainLayout.razor__virtual.cs added to workspace
[info]: OmniSharp.MSBuild.ProjectManager
        Queue project update for '/Users/captainsafia/Verifications/RerenderExplorations/RerenderExplorations.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Loading project: /Users/captainsafia/Verifications/RerenderExplorations/RerenderExplorations.csproj
[info]: OmniSharp.MSBuild.ProjectManager
        Successfully loaded project file '/Users/captainsafia/Verifications/RerenderExplorations/RerenderExplorations.csproj'.
[info]: OmniSharp.MSBuild.ProjectManager
        Adding project '/Users/captainsafia/Verifications/RerenderExplorations/RerenderExplorations.csproj'
[info]: OmniSharp.MSBuild.ProjectManager
        Update project: RerenderExplorations
[info]: OmniSharp.Roslyn.CSharp.Services.Diagnostics.CSharpDiagnosticWorkerWithAnalyzers
        Solution initialized -> queue all documents for code analysis. Initial document count: 10.
```

**Comment by JoeRobich** [comment]
> The version of the compiler that is referenced by the source generator shouldn't generally matter since you ultimately get the version that it's loaded in. We can target a minimum version that supports all the features we need (for e.g. when we get incremental source generators we can update).
> 
> That said it's possible that the reported issue is a point in time issue that goes away once O# is updated. Maybe @JoeRobich might be able to help us understand this better?

Our current release moved us from using Roslyn 3.9 to 3.10, which is why the error went away.

The NRE from this issue seems to be the same as https://github.com/OmniSharp/omnisharp-roslyn/issues/2125

**Comment by v-Lily** [comment]
I have tried this issue in the latest .Net 6.0(Its specific version information is [here](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1284417)),
and it still reproduces.This is the latest error log as following:
![image](https://user-images.githubusercontent.com/83056958/123940897-3757f880-d9cc-11eb-886f-bc66e8de21d3.png)

**Error Log**

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at OmniSharp.Helpers.LocationExtensions+<>c.<GetQuickFix>b__0_2 (Microsoft.CodeAnalysis.Document document) [0x00000] in <bc5c5e63ae9045e8b984912c04310227>:0 
  at System.Linq.Utilities+<>c__DisplayClass2_0`3[TSource,TMiddle,TResult].<CombineSelectors>b__0 (TSource x) [0x00012] in <17e8581c65f940ca8137dd67206f5dbd>:0 
  at System.Linq.Enumerable+SelectArrayIterator`2[TSource,TResult].ToArray () [0x00012] in <17e8581c65f940ca8137dd67206f5dbd>:0 
  at System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0001f] in <17e8581c65f940ca8137dd67206f5dbd>:0 
  at OmniSharp.Helpers.LocationExtensions.GetQuickFix (Microsoft.CodeAnalysis.Location location, OmniSharp.OmniSharpWorkspace workspace) [0x00128] in <bc5c5e63ae9045e8b984912c04310227>:0 
  at OmniSharp.Roslyn.CSharp.Services.Navigation.FindUsagesService+<>c__DisplayClass3_0.<Handle>b__2 (Microsoft.CodeAnalysis.Location l) [0x00000] in <bc5c5e63ae9045e8b984912c04310227>:0 
  at System.Linq.Enumerable+SelectEnumerableIterator`2[TSource,TResult].MoveNext () [0x00048] in <17e8581c65f940ca8137dd67206f5dbd>:0 
  at System.Linq.Set`1[TElement].UnionWith (System.Collections.Generic.IEnumerable`1[T] other) [0x00018] in <17e8581c65f940ca8137dd67206f5dbd>:0 
  at System.Linq.Enumerable+DistinctIterator`1[TSource].FillSet () [0x0000b] in <17e8581c65f940ca8137dd67206f5dbd>:0 
  at System.Linq.Enumerable+DistinctIterator`1[TSource].ToArray () [0x00000] in <17e8581c65f940ca8137dd67206f5dbd>:0 
  at System.Linq.Buffer`1[TElement]..ctor (System.Collections.Generic.IEnumerable`1[T] source) [0x0000a] in <17e8581c65f940ca8137dd67206f5dbd>:0 
  at System.Linq.OrderedEnumerable`1+<GetEnumerator>d__3[TElement].MoveNext () [0x0001e] in <17e8581c65f940ca8137dd67206f5dbd>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList (Newtonsoft.Json.JsonWriter writer, System.Collections.IEnumerable values, Newtonsoft.Json.Serialization.JsonArrayContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000e1] in <2676a2da6edc420e890ed28aa4572ee5>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000d6] in <2676a2da6edc420e890ed28aa4572ee5>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008d] in <2676a2da6edc420e890ed28aa4572ee5>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000b2] in <2676a2da6edc420e890ed28aa4572ee5>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008d] in <2676a2da6edc420e890ed28aa4572ee5>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000b2] in <2676a2da6edc420e890ed28aa4572ee5>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00079] in <2676a2da6edc420e890ed28aa4572ee5>:0 
  at Newtonsoft.Json.JsonSerializer.SerializeInternal (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x0023a] in <2676a2da6edc420e890ed28aa4572ee5>:0 
  at Newtonsoft.Json.JsonSerializer.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00000] in <2676a2da6edc420e890ed28aa4572ee5>:0 
  at Newtonsoft.Json.JsonConvert.SerializeObjectInternal (System.Object value, System.Type type, Newtonsoft.Json.JsonSerializer jsonSerializer) [0x00028] in <2676a2da6edc420e890ed28aa4572ee5>:0 
  at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x00007] in <2676a2da6edc420e890ed28aa4572ee5>:0 
  at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value) [0x00000] in <2676a2da6edc420e890ed28aa4572ee5>:0 
  at OmniSharp.Protocol.Packet.ToString () [0x00000] in <8b570aa16fd64ee18069d430196dac2b>:0 
  at System.IO.TextWriter.WriteLine (System.Object value) [0x00028] in <b18e5763ec3f41e68a8fe16d7f5e0bee>:0 
  at System.IO.TextWriter+SyncTextWriter.WriteLine (System.Object value) [0x00000] in <b18e5763ec3f41e68a8fe16d7f5e0bee>:0 
  at (wrapper synchronized) System.IO.TextWriter+SyncTextWriter.WriteLine(object)
  at OmniSharp.Services.SharedTextWriter.ProcessWriteQueue () [0x0001d] in <8b570aa16fd64ee18069d430196dac2b>:0 
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00014] in <b18e5763ec3f41e68a8fe16d7f5e0bee>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <b18e5763ec3f41e68a8fe16d7f5e0bee>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <b18e5763ec3f41e68a8fe16d7f5e0bee>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in <b18e5763ec3f41e68a8fe16d7f5e0bee>:0 
  at System.Threading.ThreadHelper.ThreadStart () [0x00008] in <b18e5763ec3f41e68a8fe16d7f5e0bee>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at OmniSharp.Helpers.LocationExtensions+<>c.<GetQuickFix>b__0_2 (Microsoft.CodeAnalysis.Document document) [0x00000] in <bc5c5e63ae9045e8b984912c04310227>:0 
  at System.Linq.Utilities+<>c__DisplayClass2_0`3[TSource,TMiddle,TResult].<CombineSelectors>b__0 (TSource x) [0x00012] in <17e8581c65f940ca8137dd67206f5dbd>:0 
  at System.Linq.Enumerable+SelectArrayIterator`2[TSource,TResult].ToArray () [0x00012] in <17e8581c65f940ca8137dd67206f5dbd>:0 
  at System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0001f] in <17e8581c65f940ca8137dd67206f5dbd>:0 
  at OmniSharp.Helpers.LocationExtensions.GetQuickFix (Microsoft.CodeAnalysis.Location location, OmniSharp.OmniSharpWorkspace workspace) [0x00128] in <bc5c5e63ae9045e8b984912c04310227>:0 
  at OmniSharp.Roslyn.CSharp.Services.Navigation.FindUsagesService+<>c__DisplayClass3_0.<Handle>b__2 (Microsoft.CodeAnalysis.Location l) [0x00000] in <bc5c5e63ae9045e8b984912c04310227>:0 
  at System.Linq.Enumerable+SelectEnumerableIterator`2[TSource,TResult].MoveNext () [0x00048] in <17e8581c65f940ca8137dd67206f5dbd>:0 
  at System.Linq.Set`1[TElement].UnionWith (System.Collections.Generic.IEnumerable`1[T] other) [0x00018] in <17e8581c65f940ca8137dd67206f5dbd>:0 
  at System.Linq.Enumerable+DistinctIterator`1[TSource].FillSet () [0x0000b] in <17e8581c65f940ca8137dd67206f5dbd>:0 
  at System.Linq.Enumerable+DistinctIterator`1[TSource].ToArray () [0x00000] in <17e8581c65f940ca8137dd67206f5dbd>:0 
  at System.Linq.Buffer`1[TElement]..ctor (System.Collections.Generic.IEnumerable`1[T] source) [0x0000a] in <17e8581c65f940ca8137dd67206f5dbd>:0 
  at System.Linq.OrderedEnumerable`1+<GetEnumerator>d__3[TElement].MoveNext () [0x0001e] in <17e8581c65f940ca8137dd67206f5dbd>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList (Newtonsoft.Json.JsonWriter writer, System.Collections.IEnumerable values, Newtonsoft.Json.Serialization.JsonArrayContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000e1] in <2676a2da6edc420e890ed28aa4572ee5>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000d6] in <2676a2da6edc420e890ed28aa4572ee5>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008d] in <2676a2da6edc420e890ed28aa4572ee5>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000b2] in <2676a2da6edc420e890ed28aa4572ee5>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract collectionContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x0008d] in <2676a2da6edc420e890ed28aa4572ee5>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue (Newtonsoft.Json.JsonWriter writer, System.Object value, Newtonsoft.Json.Serialization.JsonContract valueContract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty) [0x000b2] in <2676a2da6edc420e890ed28aa4572ee5>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00079] in <2676a2da6edc420e890ed28aa4572ee5>:0 
  at Newtonsoft.Json.JsonSerializer.SerializeInternal (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x0023a] in <2676a2da6edc420e890ed28aa4572ee5>:0 
  at Newtonsoft.Json.JsonSerializer.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00000] in <2676a2da6edc420e890ed28aa4572ee5>:0 
  at Newtonsoft.Json.JsonConvert.SerializeObjectInternal (System.Object value, System.Type type, Newtonsoft.Json.JsonSerializer jsonSerializer) [0x00028] in <2676a2da6edc420e890ed28aa4572ee5>:0 
  at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x00007] in <2676a2da6edc420e890ed28aa4572ee5>:0 
  at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value) [0x00000] in <2676a2da6edc420e890ed28aa4572ee5>:0 
  at OmniSharp.Protocol.Packet.ToString () [0x00000] in <8b570aa16fd64ee18069d430196dac2b>:0 
  at System.IO.TextWriter.WriteLine (System.Object value) [0x00028] in <b18e5763ec3f41e68a8fe16d7f5e0bee>:0 
  at System.IO.TextWriter+SyncTextWriter.WriteLine (System.Object value) [0x00000] in <b18e5763ec3f41e68a8fe16d7f5e0bee>:0 
  at (wrapper synchronized) System.IO.TextWriter+SyncTextWriter.WriteLine(object)
  at OmniSharp.Services.SharedTextWriter.ProcessWriteQueue () [0x0001d] in <8b570aa16fd64ee18069d430196dac2b>:0 
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00014] in <b18e5763ec3f41e68a8fe16d7f5e0bee>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <b18e5763ec3f41e68a8fe16d7f5e0bee>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <b18e5763ec3f41e68a8fe16d7f5e0bee>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in <b18e5763ec3f41e68a8fe16d7f5e0bee>:0 
  at System.Threading.ThreadHelper.ThreadStart () [0x00008] in <b18e5763ec3f41e68a8fe16d7f5e0bee>:0
