### ISSUE TITLE
Blazor Virtualize `ArgumentOutOfRangeException`

### ISSUE THREAD

**Issue by vflame** [dotnet/aspnetcore#30677]
I am seeing the following in my error logs when using `Virtualize`

```
2021-03-04 20:25:12.566 -05:00 [ERR] [Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost] Unhandled exception in circuit '4-9GFouNg5KSLv84JoOfcth5Tbp5Tgy3qAcqIgVQRnA'.
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Microsoft.AspNetCore.Components.Web.Virtualization.Virtualize`1.BuildRenderTree(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

It happens intermittently with no real pattern and I am unable to determine exactly why this occurs My guess is that I have multiple updates to the Virtualize triggered by events and `RefreshData/InvokeAsync(StateHasChanged)` are called frequently...is Virtualize thread-safe or do I have to wrap the refresh + statehaschanged in a lock?

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Virtualize is not thread-safe so if your code tries to mutate a common state, you should definitely have some preventative mechanism in-place. Try to use the `InvokeAsync` to queue up all the state-mutating actions internally and there will be no issues with concurrency any more.

**Comment by mkArtakMSFT** [comment]
If you believe this is not what you're facing and there is a different reason, we will need to have a repro app to be able to investigate this further.

**Comment by vflame** [comment]
Thanks for the feedback
