### ISSUE TITLE
Test Failure: BlazorWasmHostedTemplate_IndividualAuth_Works_WithLocalDB

### ISSUE THREAD

**Issue by sebastienros** [dotnet/aspnetcore#30700]
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1024047&view=results

```
  Stack Trace:
     at PlaywrightSharp.Transport.Connection.SendMessageToServerAsync[T](String guid, String method, Object args, Boolean ignoreNullValues, JsonSerializerOptions serializerOptions, Boolean treatErrorPropertyAsError) in /Users/neo/Documents/Coding/Personal/playwright-sharp/src/PlaywrightSharp/Transport/Connection.cs:line 163
   at PlaywrightSharp.Frame.WaitForSelectorAsync(Boolean isPageCall, String selector, Nullable`1 state, Nullable`1 timeout) in /Users/neo/Documents/Coding/Personal/playwright-sharp/src/PlaywrightSharp/Frame.cs:line 645
   at Templates.Test.BlazorWasmTemplateTest.TestBasicNavigation(String appName, IPage page, Boolean usesAuth, Boolean skipFetchData) in /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorWasmTemplateTest.cs:line 601
   at Templates.Test.BlazorWasmTemplateTest.BuildAndRunTest(String appName, Project project, BrowserKind browserKind, Boolean usesAuth) in /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorWasmTemplateTest.cs:line 518
   at Templates.Test.BlazorWasmTemplateTest.BuildAndRunTest(String appName, Project project, BrowserKind browserKind, Boolean usesAuth) in /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorWasmTemplateTest.cs:line 519
   at Templates.Test.BlazorWasmTemplateTest.BlazorWasmHostedTemplate_IndividualAuth_Works(BrowserKind browserKind, Boolean useLocalDb) in /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorWasmTemplateTest.cs:line 340
--- End of stack trace from previous location ---
```

**Comment by HaoK** [comment]
Picking this up now as part of investigating logging and other stuff

**Comment by HaoK** [comment]
Track as part of https://github.com/dotnet/aspnetcore/issues/30882
