### ISSUE TITLE
Test Failure: BlazorServerTemplateWorks_NoAuth

### ISSUE THREAD

**Issue by sebastienros** [dotnet/aspnetcore#30761]
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1027022&view=logs&j=8c9dd6ae-5017-5a70-997c-c2386fed4e85&t=67839355-6a03-55d6-fbd7-5d56c2fd9ea1

```
  Failed Templates.Test.BlazorServerTemplateTest.BlazorServerTemplateWorks_NoAuth(browserKind: Chromium) [2 m 50 s]
  Error Message:
   System.TimeoutException : Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "h1+p >> text=Current count: 1" to be visible
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
  Stack Trace:
     at PlaywrightSharp.Transport.Connection.SendMessageToServerAsync[T](String guid, String method, Object args, Boolean ignoreNullValues, JsonSerializerOptions serializerOptions, Boolean treatErrorPropertyAsError) in /Users/neo/Documents/Coding/Personal/playwright-sharp/src/PlaywrightSharp/Transport/Connection.cs:line 163
   at PlaywrightSharp.Frame.WaitForSelectorAsync(Boolean isPageCall, String selector, Nullable`1 state, Nullable`1 timeout) in /Users/neo/Documents/Coding/Personal/playwright-sharp/src/PlaywrightSharp/Frame.cs:line 645
   at Templates.Test.BlazorServerTemplateTest.TestBasicNavigation(IPage page) in /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorServerTemplateTest.cs:line 200
   at Templates.Test.BlazorServerTemplateTest.BlazorServerTemplateWorks_NoAuth(BrowserKind browserKind) in /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorServerTemplateTest.cs:line 74
   at Templates.Test.BlazorServerTemplateTest.BlazorServerTemplateWorks_NoAuth(BrowserKind browserKind) in /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorServerTemplateTest.cs:line 101
```

**Comment by javiercn** [comment]
This is failing to wait for the navigation to be intercepted.
