### ISSUE TITLE
Flaky BlazorServerTemplateWorks_IndividualAuth test

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#30807]
`Templates.Test.BlazorServerTemplateTest.BlazorServerTemplateWorks_IndividualAuth(browserKind: Chromium, useLocalDB: False)` is failing with a timeout.

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1030870&view=ms.vss-test-web.build-test-results-tab&runId=31993420&resultId=125304&paneView=debug

**Error message**
```
System.TimeoutException : Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "h1+p >> text=Current count: 1" to be visible
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
```

**Stack trace**
```
   at PlaywrightSharp.Transport.Connection.SendMessageToServerAsync[T](String guid, String method, Object args, Boolean ignoreNullValues, JsonSerializerOptions serializerOptions, Boolean treatErrorPropertyAsError) in /Users/neo/Documents/Coding/Personal/playwright-sharp/src/PlaywrightSharp/Transport/Connection.cs:line 163
   at PlaywrightSharp.Frame.WaitForSelectorAsync(Boolean isPageCall, String selector, Nullable`1 state, Nullable`1 timeout) in /Users/neo/Documents/Coding/Personal/playwright-sharp/src/PlaywrightSharp/Frame.cs:line 645
   at Templates.Test.BlazorServerTemplateTest.TestBasicNavigation(IPage page) in /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorServerTemplateTest.cs:line 210
   at Templates.Test.BlazorServerTemplateTest.BlazorServerTemplateWorks_IndividualAuth(BrowserKind browserKind, Boolean useLocalDB) in /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorServerTemplateTest.cs:line 145
--- End of stack trace from previous location ---
```

**Comment by HaoK** [comment]
Possibly related to https://github.com/dotnet/aspnetcore/issues/30825 which is what errors showed up on osx for this test

**Comment by HaoK** [comment]
Tracked as part of https://github.com/dotnet/aspnetcore/issues/30882
