### ISSUE TITLE
Flaky BlazorWasmHostedTemplate_IndividualAuth_Works_WithOutLocalDB test

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#30820]
**Failing build**
https://dev.azure.com/dnceng/public/_build/results?buildId=1030279&view=logs&j=3f6d4e0f-1b71-56b5-361e-d95b6e6da15a&t=d5bf30bc-9e5a-596c-d1c8-39e2dfa42d49&l=696

**Stacktrace**

```
[xUnit.net 00:13:13.45] BlazorTemplates.Tests: pw:channel:response {"id":80}
[xUnit.net 00:13:14.33]       System.TimeoutException : Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "ul" to be visible
  selector resolved to visible <ul b-bdkz6fwuc1="" class="nav flex-column">.</ul>
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
[xUnit.net 00:13:14.33]       Stack Trace:
[xUnit.net 00:13:14.33]         /Users/neo/Documents/Coding/Personal/playwright-sharp/src/PlaywrightSharp/Transport/Connection.cs(163,0): at PlaywrightSharp.Transport.Connection.SendMessageToServerAsync[T](String guid, String method, Object args, Boolean ignoreNullValues, JsonSerializerOptions serializerOptions, Boolean treatErrorPropertyAsError)
[xUnit.net 00:13:14.33]         /Users/neo/Documents/Coding/Personal/playwright-sharp/src/PlaywrightSharp/Frame.cs(645,0): at PlaywrightSharp.Frame.WaitForSelectorAsync(Boolean isPageCall, String selector, Nullable`1 state, Nullable`1 timeout)
[xUnit.net 00:13:14.33]         /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorWasmTemplateTest.cs(530,0): at Templates.Test.BlazorWasmTemplateTest.TestBasicNavigation(String appName, IPage page, Boolean usesAuth, Boolean skipFetchData)
[xUnit.net 00:13:14.33]         /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorWasmTemplateTest.cs(519,0): at Templates.Test.BlazorWasmTemplateTest.BuildAndRunTest(String appName, Project project, BrowserKind browserKind, Boolean usesAuth)
[xUnit.net 00:13:14.33]         /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorWasmTemplateTest.cs(520,0): at Templates.Test.BlazorWasmTemplateTest.BuildAndRunTest(String appName, Project project, BrowserKind browserKind, Boolean usesAuth)
[xUnit.net 00:13:14.33]         /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorWasmTemplateTest.cs(341,0): at Templates.Test.BlazorWasmTemplateTest.BlazorWasmHostedTemplate_IndividualAuth_Works(BrowserKind browserKind, Boolean useLocalDb)
[xUnit.net 00:13:14.33]         --- End of stack trace from previous location ---
[xUnit.net 00:13:14.33]       Output:
[xUnit.net 00:13:14.33]         Acquired DotNetNewLock
[xUnit.net 00:13:14.33]         Released DotNetNewLock
[xUnit.net 00:13:14.33]         Acquired DotNetNewLock
[xUnit.net 00:13:14.33]         ==> dotnet new blazorwasm --debug:custom-hive "Hives\.templateEngine" --hosted -au Individual  -o C:\h\w\99D6094B\w\B4500992\e\Templates\BaseFolder\AspNet.joesrgoohf1 [C:\h\w\99D6094B\w\B4500992\e\]
[xUnit.net 00:13:14.33]         The template "Blazor WebAssembly App" was created successfully.
[xUnit.net 00:13:14.33]         This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore/6.0-third-party-notices for details.
[xUnit.net 00:13:14.33]         
[xUnit.net 00:13:14.33]         Processing post-creation actions...
[xUnit.net 00:13:14.33]         Running 'dotnet restore' on C:\h\w\99D6094B\w\B4500992\e\Templates\BaseFolder\AspNet.joesrgoohf1\AspNet.joesrgoohf1.sln...
[xUnit.net 00:13:14.33]           Determining projects to restore...
[xUnit.net 00:13:14.33]           Restored C:\h\w\99D6094B\w\B4500992\e\Templates\BaseFolder\AspNet.joesrgoohf1\Shared\AspNet.joesrgoohf1.Shared.csproj (in 335 ms).
[xUnit.net 00:13:14.32]     Templates.Test.BlazorWasmTemplateTest.BlazorWasmHostedTemplate_IndividualAuth_Works_WithOutLocalDB(browserKind: Chromium) [FAIL]
[xUnit.net 00:13:14.33]           Restored C:\h\w\99D6094B\w\B4500992\e\Templates\BaseFolder\AspNet.joesrgoohf1\Client\AspNet.joesrgoohf1.Client.csproj (in 2.39 sec).
[xUnit.net 00:13:14.33]           Restored C:\h\w\99D6094B\w\B4500992\e\Templates\BaseFolder\AspNet.joesrgoohf1\Server\AspNet.joesrgoohf1.Server.csproj (in 13.39 sec).
[xUnit.net 00:13:14.33]         Restore succeeded.
```

**Comment by HaoK** [comment]
Track as part of https://github.com/dotnet/aspnetcore/issues/30882
