### ISSUE TITLE
Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson throws excepition

### ISSUE THREAD

**Issue by pfaustinopt** [dotnet/aspnetcore#30837]
### Describe the bug
According to Microsoft [documentation](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-5.0&tabs=visual-studio#newtonsoftjson-jsonnet-support) all it is required to use NewtonsoftJson in ASP.NET Core is to install the ` Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson` and configure both the client and server with `.AddNewtonsoftJsonProtocol()` (**Note:** the tutorial points to ASP.NET Core 3.0 but I'm using ASP.NET Core 3.1).

I've followed the required steps but once I try to connect my client to the hub, an exception is thrown.

### To Reproduce
[Repository](https://github.com/pfaustinopt/SignalRNewtonsoftJson)

### Exceptions (if any)
**Client side**
```
dbug: Microsoft.AspNetCore.SignalR.Client.HubConnection[41]
      Starting HubConnection.
dbug: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[1]
      Starting HttpConnection.
dbug: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[8]
      Establishing connection with server at 'http://localhost:5000/test'.
dbug: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[9]
      Established connection 'sZ6FFbO_fTf7e7aSsA9hCw' with the server.
dbug: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[7]
      Starting transport 'WebSockets' with Url: http://localhost:5000/test.
info: Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport[1]
      Starting transport. Transfer mode: Text. Url: 'ws://localhost:5000/test?id=8LNjAbua5xJtM2i0DPGLEA'.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport[19]
      Started transport.
dbug: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[18]
      Transport 'WebSockets' started.
info: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[3]
      HttpConnection Started.
info: Microsoft.AspNetCore.SignalR.Client.HubConnection[24]
      Using HubProtocol 'json v1'.
dbug: Microsoft.AspNetCore.SignalR.Client.HubConnection[28]
      Sending Hub Handshake.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport[13]
      Received message from application. Payload size: 32.
info: Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport[11]
      WebSocket closed by the server. Close status InternalServerError.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport[4]
      Receive loop stopped.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport[8]
      Send loop stopped.
fail: Microsoft.AspNetCore.SignalR.Client.HubConnection[35]
      The underlying connection closed while processing the handshake response. See exception for details.
      System.InvalidOperationException: Websocket closed with error: InternalServerError.
         at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartReceiving(WebSocket socket)
         at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
         at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
         at System.IO.Pipelines.Pipe.GetReadAsyncResult()
         at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
         at Microsoft.AspNetCore.SignalR.Client.HubConnection.HandshakeAsync(ConnectionState startingConnectionState, CancellationToken cancellationToken)
fail: Microsoft.AspNetCore.SignalR.Client.HubConnection[43]
      Error starting connection.
      System.InvalidOperationException: Websocket closed with error: InternalServerError.
         at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartReceiving(WebSocket socket)
         at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
         at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
         at System.IO.Pipelines.Pipe.GetReadAsyncResult()
         at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
         at Microsoft.AspNetCore.SignalR.Client.HubConnection.HandshakeAsync(ConnectionState startingConnectionState, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
dbug: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[4]
      Disposing HttpConnection.
info: Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport[6]
      Transport is stopping.
dbug: Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport[2]
      Transport stopped.
info: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[6]
      HttpConnection Disposed.
Unhandled exception. System.AggregateException: One or more errors occurred. (Websocket closed with error: InternalServerError.)
 ---> System.InvalidOperationException: Websocket closed with error: InternalServerError.
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartReceiving(WebSocket socket)
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.HandshakeAsync(ConnectionState startingConnectionState, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Client.Program.Main(String[] args) in C:\Git\SignalRNewtonsoftJson\Client\Program.cs:line 24
```

**Server side** 
```
Exception thrown: 'System.IO.FileNotFoundException' in Microsoft.AspNetCore.SignalR.Common.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.AspNetCore.SignalR.Common.dll
Exception thrown: 'System.TypeInitializationException' in Microsoft.AspNetCore.SignalR.Common.dll
Exception thrown: 'System.TypeInitializationException' in System.Private.CoreLib.dll
Exception thrown: 'System.TypeInitializationException' in System.Private.CoreLib.dll
Exception thrown: 'System.TypeInitializationException' in System.Private.CoreLib.dll
Exception thrown: 'System.TypeInitializationException' in System.Private.CoreLib.dll
```

### Further technical details
- ASP.NET Core version: 3.1
```
.NET SDK (reflecting any global.json):
 Version:   5.0.104
 Commit:    ca6b6acadb

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.104\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  3.1.302 [C:\Program Files\dotnet\sdk]
  3.1.403 [C:\Program Files\dotnet\sdk]
  3.1.407 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- IDE: Microsoft Visual Studio Enterprise 2019, Version 16.8.6 (Windows version)

**Comment by BrennanConroy** [comment]
You're probably hitting issue https://github.com/dotnet/runtime/issues/45560

Downgrade your Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson reference to 3.1 or upgrade your app to 5.0 to fix the issue.

**Comment by pfaustinopt** [comment]
Just like you said, after downgrading to 3.1 everything worked fine.

Thanks!
