### ISSUE TITLE
Resolve failure to resolve types with RSG

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#30851]
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1034221&view=logs&j=80f594f0-dab9-53e4-691e-a6c036ec4279&t=04eab92f-dbd1-567e-0acd-be26c7e1c779&l=2426

```
##[error]D:\workspace\_work\1\s\src\Components\WebView\Samples\BlazorWpfApp\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\_Pages_Index.razor.cs(126,75): error CS0246: (NETCORE_ENGINEERING_TELEMETRY=Build) The type or namespace name 'AppState' could not be found (are you missing a using directive or an assembly reference?)

```

**Comment by Eilon** [comment]
I chatted with @captainsafia yesterday and I saw this happen once on my machine, which I erroneously assumed was bad luck. After I ran "Clean" on the project, the ever never showed up again. I hit it while adding/editing files to the Blazor WebView WPF sample. I am using VS2019 16.9.0 Preview 5 (public Preview channel).

**Comment by Eilon** [comment]
BTW I _think_ that a workaround is to fully-qualify the namespace of the `AppState` type, that is, `BlazorWpfSample.AppState` or similar. Perhaps the `_Imports.razor` is not getting picked up?

**Comment by Eilon** [comment]
And indeed I applied the workaround to my PR and that made it pass on CI. So I'm guessing it's an issue with not seeing the `@using`'s in the `_Imports.razor` file in some circumstances. (And clearly it's not VS-specific or VS Code-specific because it happened on CI.)

**Comment by Tratcher** [comment]
BlazorWasmHostedTemplate_AzureActiveDirectoryTemplate_Works has had a spike in failures since 6/26, the pass rate is down to 34%. Here's the most common one:

```
System.AggregateException : One or more errors occurred. (The file '/root/helix/work/workitem/uploads/AspNet.rndbabxhhx0.binlog' already exists.) (Object reference not set to an instance of an object.)
---- System.IO.IOException : The file '/root/helix/work/workitem/uploads/AspNet.rndbabxhhx0.binlog' already exists.
---- System.NullReferenceException : Object reference not set to an instance of an object.
----- Inner Stack Trace #1 (System.IO.IOException) -----
   at System.IO.FileSystem.LinkOrCopyFile(String sourceFullPath, String destFullPath) in System.Private.CoreLib.dll:token 0x6005b7b+0xa7
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath, Boolean overwrite) in System.Private.CoreLib.dll:token 0x6005b7d+0x92
   at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite) in System.Private.CoreLib.dll:token 0x60057fb+0x83
   at System.IO.File.Move(String sourceFileName, String destFileName) in System.Private.CoreLib.dll:token 0x60057fa+0x0
   at Templates.Test.Helpers.Project.CaptureBinLogOnFailure(ProcessEx result) in /_/src/ProjectTemplates/Shared/Project.cs:line 446
   at Templates.Test.Helpers.Project.RunDotNetPublishAsync(IDictionary`2 packageOptions, String additionalArgs, Boolean noRestore) in /_/src/ProjectTemplates/Shared/Project.cs:line 136
   at Templates.Test.BlazorTemplateTest.CreateBuildPublishAsync(String projectName, String auth, String[] args, String targetFramework, Boolean serverProject, Boolean onlyCreate) in /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorTemplateTest.cs:line 125
--- End of stack trace from previous location ---
----- Inner Stack Trace #2 (System.NullReferenceException) -----
   at Templates.Test.BlazorTemplateTest.DisposeAsync() in /_/src/ProjectTemplates/BlazorTemplates.Tests/BlazorTemplateTest.cs:line 60
```

**Comment by captainsafia** [comment]
These looks like issues with the test as opposed to issue with the source generator. Typically, issues with the source generator will surface out of the `CSC` process.

@HaoK Any thoughts on the issues above? Perhaps something addressed in your recent Blazor template tests PR?

**Comment by HaoK** [comment]
So the real error is in the logs higher up, there's a bug in the retry that will always surface the bin log error in subsequent tries, my PR shouldn't affect anything functionally, but the blazor templates were all broken until today, so we should expect full red for the past few days

**Comment by HaoK** [comment]
This PR should add back coverage on PRs so we can catch these regressions going forward https://github.com/dotnet/aspnetcore/pull/34275

**Comment by mkArtakMSFT** [comment]
We believe this has been resolved already. Unfortunately, there is no clear link to actual change which may have resolved this.
Moving this to 6.0 to unquarantine the old flaky test.

**Comment by TanayParikh** [comment]
Test needing to be unquarantined: https://github.com/dotnet/aspnetcore/blob/c1d16e3ccd2df6a3ff06b7e0233ad96fe6113d5b/src/ProjectTemplates/BlazorTemplates.Tests/BlazorWasmTemplateTest.cs#L393

Not yet eligible for unquarantining by our "30 day rule"
![image](https://user-images.githubusercontent.com/14852843/133702027-a6d8c53f-bd81-43cd-8e2f-b509a63b5876.png)

Marking this as `test-fixed` per the above discussion.

**Comment by TanayParikh** [comment]
This test hasn't run since 9/20. 

![image](https://user-images.githubusercontent.com/14852843/136104648-c23f649c-01a2-465f-8a3e-539f52a36970.png)

Is this expected?

**Comment by TanayParikh** [comment]
Ah okay, I see it now, thanks! Un-quarantining...
