### ISSUE TITLE
Renaming Injected Service Leads to Error

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#30949]
1. `dotnet new blazorserver`
2. Create a new service `SomeService`
3. `@inject SomeService` into `Counter.razor`
4. Rename `SomeService` to `SomeService2` in the VS Solution Explorer

Getting the following yellow bar & error:
![image](https://user-images.githubusercontent.com/14852843/111222154-abdf6680-8598-11eb-8690-d839affc69d3.png)

```
=====================
3/15/2021 2:11:41 PM
Recoverable
System.AggregateException: One or more errors occurred. ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: lineNumber
   at Microsoft.VisualStudio.Text.Implementation.BinaryStringRebuilder.GetLineFromLineNumber(Int32 lineNumber, Span& extent, Int32& lineBreakLength)
   at Microsoft.VisualStudio.Text.Implementation.CachingTextImage.GetLineFromLineNumber(Int32 lineNumber)
   at Microsoft.CodeAnalysis.Text.Extensions.SnapshotSourceText.LineInfo.get_Item(Int32 index)
   at Microsoft.VisualStudio.LanguageServerClient.Razor.VSLSPRangeExtensions.AsTextSpan(Range range, SourceText sourceText)
   at Microsoft.VisualStudio.LanguageServerClient.Razor.CSharpSpanMappingService.<MapSpansAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServerClient.Razor.CSharpSpanMappingService.<MapSpansAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.ExternalAccess.Razor.RazorSpanMappingServiceWrapper.<MapSpansAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.<<ApplyMappedFileChanges>g__GetMappedTextChanges|82_1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyMappedFileChanges(SolutionChanges solutionChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution, IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution, IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution)
   at Microsoft.VisualStudio.ProjectSystem.VS.RoslynServices.ApplyChangesToSolution(Workspace ws, Solution renamedSolution)
   at Microsoft.VisualStudio.ProjectSystem.VS.Rename.RenamerProjectTreeActionHandler.<>c__DisplayClass14_0.<<RenameAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.<>c__DisplayClass31_0.<<Fork>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>g__Action|0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: lineNumber
   at Microsoft.VisualStudio.Text.Implementation.BinaryStringRebuilder.GetLineFromLineNumber(Int32 lineNumber, Span& extent, Int32& lineBreakLength)
   at Microsoft.VisualStudio.Text.Implementation.CachingTextImage.GetLineFromLineNumber(Int32 lineNumber)
   at Microsoft.CodeAnalysis.Text.Extensions.SnapshotSourceText.LineInfo.get_Item(Int32 index)
   at Microsoft.VisualStudio.LanguageServerClient.Razor.VSLSPRangeExtensions.AsTextSpan(Range range, SourceText sourceText)
   at Microsoft.VisualStudio.LanguageServerClient.Razor.CSharpSpanMappingService.<MapSpansAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServerClient.Razor.CSharpSpanMappingService.<MapSpansAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.ExternalAccess.Razor.RazorSpanMappingServiceWrapper.<MapSpansAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.<<ApplyMappedFileChanges>g__GetMappedTextChanges|82_1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyMappedFileChanges(SolutionChanges solutionChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution, IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution, IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution)
   at Microsoft.VisualStudio.ProjectSystem.VS.RoslynServices.ApplyChangesToSolution(Workspace ws, Solution renamedSolution)
   at Microsoft.VisualStudio.ProjectSystem.VS.Rename.RenamerProjectTreeActionHandler.<>c__DisplayClass14_0.<<RenameAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.<>c__DisplayClass31_0.<<Fork>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>g__Action|0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )<---

===================
```

**Comment by allisonchou** [comment]
This should be fixed by https://github.com/dotnet/aspnetcore-tooling/pull/3594.
