### ISSUE TITLE
StreamJsonRpc.RemoteInvocationException: Specified argument was out of the range of valid values. Parameter name: lineNumber

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#30951]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/StreamJsonRpcRemoteInvocationException:/1364994)._

---
Finding all references to a Blazor component from the code behind file, the following exception is generated:

StreamJsonRpc.RemoteInvocationException: Specified argument was out of the range of valid values.
Parameter name: lineNumber
   at StreamJsonRpc.JsonRpc. <InvokeCoreAsync>d__139`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1. <TryInvokeAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
RPC server exception:
StreamJsonRpc.RemoteInvocationException: Specified argument was out of the range of valid values.
Parameter name: lineNumber
      at StreamJsonRpc.JsonRpc. <InvokeCoreAsync>d__139`1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at Microsoft.CodeAnalysis.Remote.RemoteCallback`1. <InvokeAsync>d__2.MoveNext()

---
#### Feedback Bot on 3/10/2021, 11:42 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by NTaylorMullen** [comment]
Hello, does this occur for you when trying to reference a specific portion of the Blazor component from a code behind file?
