### ISSUE TITLE
Add `.cshtml.css` styles in default project templates

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#31030]
This will help with adoption of CSS Isolation.

**Comment by captainsafia** [comment]
I took a stab at doing this when I was fixing an scoped CSS issue in #31257 but it induced a ton of flakiness in the build.

In particular, our template tests do a validation where they check to see if the static assets requested by an app are received. For some reason, the generated CSS file from the scoped CSS throws a 404 sometimes.

```
Expected /AspNet._1rfblykoltv.styles.css to have status 'OK' but it was 'NotFound'.
Expected: True
Actual:   False
```
```
at Templates.Test.Helpers.AspNetProcess.AssertStatusCode(String requestUrl, HttpStatusCode statusCode, String acceptContentType) in /_/src/ProjectTemplates/Shared/AspNetProcess.cs:line 256
   at Templates.Test.Helpers.AspNetProcess.ContainsLinks(Page page) in /_/src/ProjectTemplates/Shared/AspNetProcess.cs:line 138
   at Templates.Test.Helpers.AspNetProcess.AssertPagesOk(IEnumerable`1 pages) in /_/src/ProjectTemplates/Shared/AspNetProcess.cs:line 117
   at Templates.Test.MvcTemplateTest.MvcTemplateCore(String languageOverride) in /_/src/ProjectTemplates/test/MvcTemplateTest.cs:line 108
   at Templates.Test.MvcTemplateTest.MvcTemplate_NoAuthCSharp() in /_/src/ProjectTemplates/test/MvcTemplateTest.cs:line 44
--- End of stack trace from previous location ---
```

https://dev.azure.com/dnceng/public/_build/results?buildId=1064596&view=ms.vss-test-web.build-test-results-tab&runId=32774366&resultId=123661

If we pursue this work, we'll probably need to get to the bottom of this.

As a sidenote: while working on the scoped CSS issue I was able to verify that it generally works as expected.

**Comment by javiercn** [comment]
@captainsafia I suspect this is because the check `/AspNet._1rfblykoltv.styles.css` might not match the actual file scoped CSS generates. I think it is fine to skip this file if you want on the test to avoid the flakyness.

**Comment by captainsafia** [comment]
Ah I see. I guess we'll have to add a way to exempt that particular file here:

https://github.com/dotnet/aspnetcore/blob/a67c2cf7ad135ff8ba359cc87528645c94124614/src/ProjectTemplates/Shared/AspNetProcess.cs#L135

**Comment by mkArtakMSFT** [comment]
@captainsafia I assume this is now done, isn't it?

**Comment by captainsafia** [comment]
Yep! Not sure why it didn't close when I merged the PR.
