### ISSUE TITLE
fwlink URLs in error messages are broken.

### ISSUE THREAD

**Issue by Spongman** [dotnet/aspnetcore#31215]
for example:

```
      System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
      To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
      For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
         at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
         at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)
```

that URL ( '[https://go.microsoft.com/fwlink/?linkid=848054.](https://go.microsoft.com/fwlink/?linkid=848054.)' ) is broken - it just goes to an ad for surface laptops. i mean, are you rying to suggest my code would work if only if forked out a grand for a new machine?

**Comment by blowdart** [comment]
[Fixed](https://go.microsoft.com/fwlink/?linkid=84805). 

I believe this means you should buy _me_ a new laptop though.
