### ISSUE TITLE
Razor VS Code tooling path too long error on startup

### ISSUE THREAD

**Issue by jeffpapp** [dotnet/aspnetcore#31237]
### Visual Studio Code

Select the `Razor: Report a Razor Issue` command in [VSCode Command Palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette) and follow the instructions to gather information necessary for us to investigate. Paste below:

---

Using the `Razor: Report a Razor Issue` resulted in an error in VS Code.  

![image](https://user-images.githubusercontent.com/1260960/112490114-b641f300-8d44-11eb-83c6-1d461e3de9b3.png)

Here's some info about my VS Code setup

```
Version: 1.54.3 (user setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

C# Extension: 1.23.9
```

I'm getting the following when opening a folder in VS Code with a large number of various kinds of projects.  It seems to be getting stuck in a loop on a node_modules folder.  I also notice the rzls process takes up quite a bit of CPU for a while before it throws this error.

```
[Error - 8:28:06 AM] Server initialization failed.
  Message: Internal Error - System.IO.PathTooLongException: The path 'c:\Projects\<PROJECT>\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\json-parse-even-better-errors' is too long, or a component of the specified path is too long.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateRelativeDirectoryHandle(ReadOnlySpan`1 relativePath, String fullPath)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at Microsoft.AspNetCore.Razor.LanguageServer.ProjectConfigurationFileChangeDetector.GetExistingConfigurationFiles(String workspaceDirectory) in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationFileChangeDetector.cs:line 119
   at Microsoft.AspNetCore.Razor.LanguageServer.ProjectConfigurationFileChangeDetector.StartAsync(String workspaceDirectory, CancellationToken cancellationToken) in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationFileChangeDetector.cs:line 56
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorFileChangeDetectorManager.InitializedAsync() in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorFileChangeDetectorManager.cs:line 46
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorLanguageServer.<>c__DisplayClass9_0.<<CreateAsync>b__2>d.MoveNext() in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs:line 99
--- End of stack trace from previous location ---
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.MediatR.IRequestHandler<OmniSharp.Extensions.LanguageServer.Protocol.Models.InternalInitializeParams,OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeResult>.Handle(InternalInitializeParams request, CancellationToken token)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|5_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.InputHandler.<>c__DisplayClass38_0.<<RouteRequest>b__5>d.MoveNext()
  Code: -32603 
```

---

**Comment by ryanbrandenburg** [comment]
Before I go into the changes being considered to Razor Tooling I would recommend anyone who's running into this because of nested `node_modules` to upgrade to the latest version of NPM which don't nest as deeply (I think anything after NPM3 should be good) or otherwise avoid the deep nesting situation on windows. If you've considered this and are staying with it for whatever reason continue below.

Our options in this area while respecting Windows limitations are limited. I see them as the following:
1. Exclude node_modules from search paths. This means we'll have to write our own directory search (the `Directory` APIs don't support this), but has the benefit that we can be a bit smarter and avoid traversing directories like `node_modules` that we know aren't going to contain the project.razor.json (I assume that was what was causing so much rzls cpu-time). We can further protect ourselves by limiting recursion depth, but that may cause problems for people with complicated IntermediateBinDirectory locations.
2. Find our list of project.razor.json files more intelligently. I don't know of any way of accomplishing this with the info available when it needs to happen, but if anyone can come up with a way that would be ideal.
3. Use `Directory.GetFiles(string, string, new EnumerationOptions{ IgnoreInaccessible})`. This doesn't save us from spending time on the recursion, and I'm not 100% certain it works for PathTooLongException, but if it does it keeps us from needing to maintain a whole new class. Does require Microsoft.AspNetCore.Razor.LanguageServer to move from `netstandard2.0` to `netstandard2.1`, which might be a deal-breaker also.
4. Leave things as-is. Certainly the worst user experience, but to a certain degree we've lost control of the situation once the path length restrictions have been violated. For example, [we also do this to find Razor files](https://github.com/dotnet/aspnetcore-tooling/blob/main/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorFileChangeDetector.cs#L155) and if your project directory was deeply nested or just had very long names you're run into a similar issue, and I can't come up with a way around that.

I my vote is for number 3 if it works, otherwise 1. We can at least mitigate this specific scenario to improve the experience, but I'm definitely cautious to get into the area of rolling our own directory searches and all its complications (SymLinks? Sparse files? Shortcuts?) so I'm curious to hear what others think.

Whatever we do in this instance we should probably also do for the other 2 uses of `Directory.GetFiles(..., SearchOptions.AllDirectories)` in RazorTooling.

**Comment by jeffpapp** [comment]
So a little more background on the issue we were running into on this.  

We have a folder called `deploy` under our root repo folder that contains a bunch of different Pulumi projects written in node which each contain their own node_modules folder since they are independent apps.  In the same repo folder we also have a few solution files at the root and then a `src` folder which contains all of our .NET projects that we'd like Omnisharp and the Razor tooling to pickup.  

For whatever reason the Razor tooling was getting stuck in all of these `deploy` folders which don't really have anything to do with any of our .NET code and then it would bomb out before getting to the .NET code which left the C# tooling in a bad state.  If I remember correctly this wasn't even a nested node_modules issue, it was creating super strange paths because it was finding multiple node_modules folders within the `deploy` folder structure

If there was some kind of configuration file that we could check into our repo that specified which folders we wanted the C# and Razor language service to crawl that would be ideal for us since we have a complicated repo structure and we wouldn't mind having a little more control of what the extension is trying to find.  Is that something that already exists?

**Comment by ryanbrandenburg** [comment]
I think I understand you until you say the `node_modules` aren't nested. From your exception message we see: `c:\Projects\<PROJECT>\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\node_modules\<project_folder>\...` which looks pretty nested to me. I had assumed you redacted the "<project_folder>" part but that it was otherwise verbatim, are you saying that no folder `C:\Projects\<Project>\<project_folder>\node_modules\<project_folder>` exists on the offending computer?

The way the section of code referenced in the exception method works is that given a folder (in this case `c:\projects\<Project>\`) and a searchPattern (project.razor.json) it recurses over the entire folder searching for matching files. So it would only be that deep in the node_modules if A) they actually existed B) there's a resursive SymLink or something similar.

A configuration file for this kind of thing is not in the cards. There's just a couple areas that run into this and it's much more easily managed by increasing resilience and avoiding trouble-spots than by having configuration files that have to be maintained by all repo owners.

See https://github.com/dotnet/aspnetcore-tooling/pull/3941 for the fix I had for this before your latest message. I'll hold off merging it until I understand your scenario better, but my current belief is that it would solve this for you.

**Comment by jeffpapp** [comment]
Yeah there are no nested node_module folders in this scenario.  If I remember correctly it was like it was getting stuck in a loop trying to build a path to the same folder.  So if I had the folder structure of
- root
  - deploy
    - pulumi
      - node_modules 
It was trying to build a path of c:\Projects\<root folder>\deploy\pulumi\node_modules\pulumi\node_modules\pulumi\node_modules\pulumi\node_modules\pulumi\node_modules\  with the node_modules repeated over and over again.

And now when I load the same project in VS Code using C# extension version 1.23.12 which has Razor.VSCode version 6.0.0-preview.5.21271.1 I'm not getting any errors so maybe this issue has already been fixed in a previous update to the extension.

I'd say if you have a good path too long fix to merge that up since that will probably help someone along the way and we can close this issue for now.  If I run into this again I can hopefully provide more detailed info to help track this down.

Thanks for looking into this!
