### ISSUE TITLE
SignalR core JWT Bearer authentication with C# client

### ISSUE THREAD

**Issue by engineering87** [dotnet/aspnetcore#31537]
Hello,
I have a Web API project with .NET 5.0 which also creates a SignalR server. The APIs work fine but when I try to connect to a C # client, again with .NET 5.0, trying to authenticate via JWT Bearer I get an unauthorized exception. I have read and tried several suggested workarounds but unfortunately I can't solve. By eliminating authentication, the connection is successful.
I tried to apply the changes described in the old issue [https://github.com/aspnet/SignalR/issues/888](url)

Could anyone help me figure out if this is a bug or is there some problem in my code? 

Thanks

### To Reproduce
**Server**
```cs
        public void ConfigureServices(IServiceCollection services)
        {
                services.AddAuthentication(options =>
                {
                    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
                })
                .AddJwtBearer(options =>
                {
                    options.IncludeErrorDetails = true;
                    options.Events = new JwtBearerEvents
                    {
                        OnMessageReceived = context =>
                        {
                            var accessToken = context.Request.Query["access_token"];
                            var path = context.HttpContext.Request.Path;
                            // TODO just test empty token
                            if (!string.IsNullOrEmpty(accessToken))
                            {
                                context.Token = accessToken;
                            }

                            return Task.CompletedTask;
                        }
                    };
                });
                services.AddSignalR(options =>
                {
                    options.EnableDetailedErrors = true;
                });
               services.AddControllers();
               services.AddSwaggerGen(c =>
               {
                  c.SwaggerDoc("v1", new OpenApiInfo { Title = "ApiTest", Version = "v1" });
               });
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");

                app.UseHsts();
            }
            app.UseSwagger();
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "WART-Api");
            });
            app.UseRouting();
            app.UseAuthentication();
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapHub<TestHub>("/testhub");
            });
        }

    [Authorize(AuthenticationSchemes = JwtBearerDefaults.AuthenticationScheme)]
    public class TestHub : Hub
    {
        private readonly ILogger<TestHub> _logger;

        public TestHub(ILogger<TestHub> logger)
        {
            this._logger = logger;
        }

        public override Task OnConnectedAsync()
        {
            _logger?.LogInformation($"OnConnect {Context.ConnectionId}");

            return base.OnConnectedAsync();
        }

        public override Task OnDisconnectedAsync(Exception exception)
        {
            _logger?.LogInformation($"OnDisconnect {Context.ConnectionId}");

            return base.OnDisconnectedAsync(exception);
        }
    }
```

**Client**
```cs
                var hubConnection = new HubConnectionBuilder()
                    .WithUrl("http://localhost:51392/testhub?access_token=test", options =>
                    {
                        options.SkipNegotiation = true;
                        options.Transports = HttpTransportType.WebSockets;
                        options.AccessTokenProvider = () => Task.FromResult("test");
                    })
                    .WithAutomaticReconnect()
                    .Build();
```

### Exception
```
System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartAsync(Uri url, TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartTransport(Uri connectUrl, HttpTransportType transportType, TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat, CancellationToken cancellationToken)
   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
```

### Technical details
- .NET Core 5.0

**Comment by BrennanConroy** [comment]
Remove `?access_token=test` from your URL.

**Comment by engineering87** [comment]
Already tried, same exception unfortunately.

**Comment by BrennanConroy** [comment]
`options.AccessTokenProvider = () => Task.FromResult("test");`
You need to pass in an actual token.

**Comment by engineering87** [comment]
Tried this but same exception:

```cs
                var securityKey = new Microsoft
                    .IdentityModel.Tokens.SymmetricSecurityKey(Encoding.UTF8.GetBytes("test"));
                var credentials = new Microsoft.IdentityModel.Tokens.SigningCredentials
                    (securityKey, SecurityAlgorithms.HmacSha256Signature);

                var header = new JwtHeader(credentials);
                var payload = new JwtPayload
                {
                    // empty payload for testing
                };
                var secToken = new JwtSecurityToken(header, payload);
                var handler = new JwtSecurityTokenHandler();
                var tokenString = handler.WriteToken(secToken);

                var hubConnection = new HubConnectionBuilder()
                    .WithUrl("http://localhost:51392/testhub", options =>
                    {
                        options.SkipNegotiation = true;
                        options.Transports = HttpTransportType.WebSockets;
                        options.AccessTokenProvider = () => Task.FromResult(tokenString);
                    })
                    .WithAutomaticReconnect()
                    .Build();
```

**Comment by BrennanConroy** [comment]
And have you set the `IssuerSigningKey` to the same key on the server side?

**Comment by engineering87** [comment]
Just for test reasons, the code I reported simply tests that the token is valued, whatever it is. 
I always get the following exception:
`System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '401' when status code '101' was expected.`

**Comment by BrennanConroy** [comment]
> the code I reported simply tests that the token is not empty

That is not what your code is doing. By using the `AddJwtBearer` method, you are wiring up the Jwt middleware which will try to authenticate the token passed in. Because your token is not valid, you are getting a 401.

Take a look at https://github.com/dotnet/aspnetcore/tree/main/src/SignalR/samples/JwtSample for a more flushed out example of using Jwt and SignalR.
