### ISSUE TITLE
RazorPagesTemplate_IdentityWeb_BuildsAndPublishes template test flakiness

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#31729]
```
[xUnit.net 00:00:15.84]     Templates.Test.RazorPagesTemplateTest.RazorPagesTemplate_IdentityWeb_BuildsAndPublishes(auth: "SingleOrg", args: ["--calls-graph"]) [FAIL]
[xUnit.net 00:00:15.84]       Process exited with code 134
[xUnit.net 00:00:15.84]       StdErr: malloc_consolidate(): invalid chunk size
[xUnit.net 00:00:15.84]       
[xUnit.net 00:00:15.84]       StdOut: Template Name                         Short Name      Language    Tags          
[xUnit.net 00:00:15.84]       ------------------------------------  --------------  ----------  --------------
[xUnit.net 00:00:15.84]       Console Application                   console         [C#],F#,VB  Common/Console
[xUnit.net 00:00:15.84]       Class library                         classlib        [C#],F#,VB  Common/Library
[xUnit.net 00:00:15.84]       MSTest Test Project                   mstest          [C#],F#,VB  Test/MSTest   
[xUnit.net 00:00:15.84]       NUnit 3 Test Item                     nunit-test      [C#],F#,VB  Test/NUnit    
[xUnit.net 00:00:15.84]       NUnit 3 Test Project                  nunit           [C#],F#,VB  Test/NUnit    
[xUnit.net 00:00:15.84]       xUnit Test Project                    xunit           [C#],F#,VB  Test/xUnit    
[xUnit.net 00:00:15.84]       Razor Component                       razorcomponent  [C#]        Web/ASP.NET   
[xUnit.net 00:00:15.84]       Razor Page                            page            [C#]        Web/ASP.NET   
[xUnit.net 00:00:15.84]       MVC ViewImports                       viewimports     [C#]        Web/ASP.NET   
[xUnit.net 00:00:15.84]       MVC ViewStart                         viewstart       [C#]        Web/ASP.NET   
[xUnit.net 00:00:15.84]       ASP.NET Core with Angular             angular         [C#]        Web/MVC/SPA   
[xUnit.net 00:00:15.84]       ASP.NET Core with React.js            react           [C#]        Web/MVC/SPA   
[xUnit.net 00:00:15.84]       ASP.NET Core with React.js and Redux  reactredux      [C#]        Web/MVC/SPA   
[xUnit.net 00:00:15.84]       TypeScript file                       tsfile                      Web/Script    
[xUnit.net 00:00:15.84]       LESS Style Sheet                      less                        Web/Style     
[xUnit.net 00:00:15.84]       SCSS Style Sheet (SASS)               scss                        Web/Style     
[xUnit.net 00:00:15.84]       Protocol Buffer File                  proto                       Web/gRPC      
[xUnit.net 00:00:15.84]       
[xUnit.net 00:00:15.84]       Examples:
[xUnit.net 00:00:15.84]           dotnet new nunit 
[xUnit.net 00:00:15.84]           dotnet new react --auth Individual
[xUnit.net 00:00:15.84]           dotnet new --help
[xUnit.net 00:00:15.85]           dotnet new proto --help
[xUnit.net 00:00:15.85]       
[xUnit.net 00:00:15.85]       Expected: True
[xUnit.net 00:00:15.85]       Actual:   False
[xUnit.net 00:00:15.85]       Stack Trace:
[xUnit.net 00:00:15.85]         /_/src/ProjectTemplates/Shared/TemplatePackageInstaller.cs(153,0): at Templates.Test.Helpers.TemplatePackageInstaller.InstallTemplatePackages(ITestOutputHelper output)
[xUnit.net 00:00:15.85]         /_/src/ProjectTemplates/Shared/TemplatePackageInstaller.cs(64,0): at Templates.Test.Helpers.TemplatePackageInstaller.EnsureTemplatingEngineInitializedAsync(ITestOutputHelper output)
[xUnit.net 00:00:15.85]         /_/src/ProjectTemplates/Shared/ProjectFactoryFixture.cs(28,0): at Templates.Test.Helpers.ProjectFactoryFixture.GetOrCreateProject(String projectKey, ITestOutputHelper output)
[xUnit.net 00:00:15.85]         /_/src/ProjectTemplates/test/RazorPagesTemplateTest.cs(250,0): at Templates.Test.RazorPagesTemplateTest.BuildAndPublishRazorPagesTemplate(String auth, String[] args)
[xUnit.net 00:00:15.85]         --- End of stack trace from previous location ---
  Failed Templates.Test.RazorPagesTemplateTest.RazorPagesTemplate_IdentityWeb_BuildsAndPublishes(auth: "SingleOrg", args: ["--calls-graph"]) [14 s]
  Error Message:
   Process exited with code 134
StdErr: malloc_consolidate(): invalid chunk size
```

https://dev.azure.com/dnceng/public/_build/results?buildId=1083545&view=logs&j=3f6d4e0f-1b71-56b5-361e-d95b6e6da15a&t=d5bf30bc-9e5a-596c-d1c8-39e2dfa42d49

**Comment by BrennanConroy** [comment]
https://github.com/dotnet/runtime/issues/38626

If you'd like to try to get someone to look at this please do!
