### ISSUE TITLE
After migrate to .NET 5 from .NET Core 2.1 occasionally Request.Form is empty

### ISSUE THREAD

**Issue by xaker1267** [dotnet/aspnetcore#31733]
After migrate to .NET 5, the following problem appeared:
999 of 1000 request come with:
httpContext.Request.Form filled with values 
Content-Length: 34
context.Request.Body.Length: 34

But 1 of 1000 request comes with such parameters:
httpContext.Request.Form is empty 
Content-Length: 34
context.Request.Body.Length: 0

This affects completely random requests.

Maybe the error is related to
context.Request.EnableBuffering();

Error next: System.NullReferenceException: Object reference not set to an instance of an object.
The parameters seem not to be read.

In Startup.cs add next code:
services.Configure<KestrelServerOptions>(options =>
{
        options.AllowSynchronousIO = true;
});
services.Configure<IISServerOptions>(options =>
{
       options.AllowSynchronousIO = true;
 });

app.Use((context, next) =>
{
    context.Request.EnableBuffering();
    return next();
});

What could be the problem?

**Comment by davidfowl** [comment]
How consistently can you reproduce this m?

**Comment by xaker1267** [comment]
We tried to upgrade to .NET Core 3.1, the error is different, but it seems that the same.

Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: **Unexpected end of request content.**
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Features.FormFeature.ReadForm()
   at NLog.Web.LayoutRenderers.AspNetRequestFormLayoutRenderer.DoAppend(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)

**Comment by xaker1267** [comment]
> 
> 
> How consistently can you reproduce this? Also do you have a full call stack for the null reference exception?
> 
> It would be great if you could provide an application that reproduces the problem

**Comment by xaker1267** [comment]
We tried to upgrade to .NET Core 3.1, the error is different, but it seems that the same.

Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Unexpected end of request content.
at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
at Microsoft.AspNetCore.WebUtilities.FormPipeReader.ReadFormAsync(CancellationToken cancellationToken)
at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
at Microsoft.AspNetCore.Http.Features.FormFeature.ReadForm()
at NLog.Web.LayoutRenderers.AspNetRequestFormLayoutRenderer.DoAppend(StringBuilder builder, LogEventInfo logEvent)
at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)

**Comment by davidfowl** [comment]
That error happens when the client disconnects before the entire body is received

**Comment by xaker1267** [comment]
Why was this not the case with net 2.1? How to solve this problem?

**Comment by davidfowl** [comment]
In 2.1 it was the case but the exception is probably different. The behavior is by design and the exception needs to be handled by the caller (whoever the caller is)
