### ISSUE TITLE
Error acquiring .NET runtime - VSCode Ubuntu 20.10

### ISSUE THREAD

**Issue by mrcteacher** [dotnet/aspnetcore#31757]
**Repro steps:**

1. Dotnet 5.0
2. Run `dotnet new blazorwasm -p`
3. Open VSCode
4. Click [Yes] on the message that includes additional assets
5. Start debug [Launch and Debug Standalone Blazor WebAssembly App]

```
 Error!
The "args" argument must be of type object. Received type string ('--info')
```

There's a red status button - `Error acquiring .NET runtimes!`

**Extension Version:** 1.0.0
**Error Message:** The "args" argument must be of type object. Received type string ('--info')
**Error Stack:** TypeError [ERR_INVALID_ARG_TYPE]: The "args" argument must be of type object. Received type string ('--info')
	at normalizeSpawnArguments (child_process.js:425:11)
	at Object.spawnSync (child_process.js:575:16)
	at Object.<anonymous> (/home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:157:67942)
	at Generator.next (<anonymous>)
	at /home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:157:64437
	at new Promise (<anonymous>)
	at n (/home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:157:64211)
	at /home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:157:67865
	at Object.<anonymous> (/home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:1:195071)
	at Generator.next (<anonymous>)
	at /home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:1:193638
	at new Promise (<anonymous>)
	at n (/home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:1:193412)
	at Object.t.callWithErrorHandling (/home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:1:195019)
	at Object.<anonymous> (/home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:157:67839)
	at Generator.next (<anonymous>)
	at /home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:157:64437
	at new Promise (<anonymous>)
	at n (/home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:157:64211)
	at /home/anonymous/.vscode/extensions/ms-dotnettools.vscode-dotnet-runtime-1.0.0/dist/extension.js:157:67797
	at S._executeContributedCommand (/snap/code/60/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:106770)
	at S._doExecuteCommand (/snap/code/60/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:105915)
	at S.executeCommand (/snap/code/60/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:105821)
	at Object.executeCommand (/snap/code/60/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:21932)
	at Object.<anonymous> (/home/anonymous/.vscode/extensions/ms-dotnettools.blazorwasm-companion-1.0.0/dist/acquireDotnetInstall.js:29:35)
	at Generator.next (<anonymous>)
	at fulfilled (/home/anonymous/.vscode/extensions/ms-dotnettools.blazorwasm-companion-1.0.0/dist/acquireDotnetInstall.js:9:58)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by kattunga** [comment]
Is there any known workarround?
By the moment the only solution that I found is to use a combination of code-insiders with a previous c# extension (version 1.23.9)

**Comment by captainsafia** [comment]
@kattunga We'll have a fix for this out soon!
