### ISSUE TITLE
Editing Property Ends In Yellow Bar Of Death BlazorWasm Hot Reload

### ISSUE THREAD

**Issue by khalidabuhakmeh** [dotnet/aspnetcore#31846]
### Describe the bug

When working with the sample BlazorWASM application, I expect a change to a read-only to work. It currently throws the following exception to the client.

![image](https://user-images.githubusercontent.com/228256/114925955-bf7f2680-9dfd-11eb-8e1d-8d0a709f6ed7.png)

### To Reproduce

1. Create a new BlazorWASM project (I'm currently on macOS .NET 6 preview 3).
2. Navigate to `/fetchdata` for the weather forecast sample
3. modify the getter property for `TemperatureF` in `WeatherForecast`.
4. App chokes with different results: sometimes it crashes the host, sometimes it returns this stack trace.

```c#
@code {
    private WeatherForecast[] forecasts;

    protected override async Task OnInitializedAsync()
    {
        forecasts = await Http.GetFromJsonAsync<WeatherForecast[]>("sample-data/weather.json");
    }

    public class WeatherForecast
    {
        public DateTime Date { get; set; }

        public int TemperatureC { get; set; }

        public string Summary { get; set; }

        // change 32 to 42, app explodes
        public int TemperatureF => 32 + (int) (TemperatureC / 0.5556);
    }

}
```

From the exception, it seems to have to do with the `table` and its rendering.

#### From Google Chrome

```console
Uncaught Error: System.TypeLoadException: EnC: we do not support patching of existing table cols. token=0x17000007
   at System.Reflection.Metadata.AssemblyExtensions.ApplyUpdate(Assembly assembly, ReadOnlySpan`1 metadataDelta, ReadOnlySpan`1 ilDelta, ReadOnlySpan`1 pdbDelta)
   at Microsoft.AspNetCore.Components.WebAssembly.Infrastructure.JSInteropMethods.ApplyHotReloadDelta(String moduleId, Byte[] metadataDelta, Byte[] ilDeta)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
--- End of stack trace from previous location ---
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.Invoke(JSRuntime jsRuntime, DotNetInvocationInfo& invocationInfo, String argsJson)
   at Microsoft.AspNetCore.Components.WebAssembly.Services.DefaultWebAssemblyJSRuntime.InvokeDotNet(String assemblyName, String methodIdentifier, String dotNetObjectId, String argsJson)
    at Object._convert_exception_for_method_call (https://localhost:5001/_framework/dotnet.6.0.0-preview.3.21201.4.js:1:194923)
    at Object._handle_exception_for_call (https://localhost:5001/_framework/dotnet.6.0.0-preview.3.21201.4.js:1:196892)
    at managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_InvokeDotNet (https://mono-wasm.invalid/managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_InvokeDotNet:20:21)
    at Object.invokeDotNetFromJS (https://localhost:5001/_framework/blazor.webassembly.js:1:33466)
    at m (https://localhost:5001/_framework/blazor.webassembly.js:1:1068)
    at Object.e.invokeMethod (https://localhost:5001/_framework/blazor.webassembly.js:1:2130)
    at Object.he._internal.applyHotReload (https://localhost:5001/_framework/blazor.webassembly.js:1:49030)
    at https://localhost:5001/_framework/aspnetcore-browser-refresh.js:101:49
    at Array.forEach (<anonymous>)
    at applyBlazorDeltas (https://localhost:5001/_framework/aspnetcore-browser-refresh.js:101:12)
```

#### From Inside of JetBrains Rider

```
Uncaught Error: System.TypeLoadException: EnC: we do not support patching of existing table cols. token=0x17000007
   at System.Reflection.Metadata.AssemblyExtensions.ApplyUpdate(Assembly assembly, ReadOnlySpan`1 metadataDelta, ReadOnlySpan`1 ilDelta, ReadOnlySpan`1 pdbDelta)
   at Microsoft.AspNetCore.Components.WebAssembly.Infrastructure.JSInteropMethods.ApplyHotReloadDelta(String moduleId, Byte[] metadataDelta, Byte[] ilDeta)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
--- End of stack trace from previous location ---
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.Invoke(JSRuntime jsRuntime, DotNetInvocationInfo& invocationInfo, String argsJson)
   at Microsoft.AspNetCore.Components.WebAssembly.Services.DefaultWebAssemblyJSRuntime.InvokeDotNet(String assemblyName, String methodIdentifier, String dotNetObjectId, String argsJson)
    at Object._convert_exception_for_method_call (https://localhost:5001/_framework/dotnet.6.0.0-preview.3.21201.4.js:1:194923)
    at Object._handle_exception_for_call (https://localhost:5001/_framework/dotnet.6.0.0-preview.3.21201.4.js:1:196892)
    at managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_InvokeDotNet (https://mono-wasm.invalid/managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_InvokeDotNet:20:21)
    at Object.invokeDotNetFromJS (https://localhost:5001/_framework/blazor.webassembly.js:1:33466)
    at m (https://localhost:5001/_framework/blazor.webassembly.js:1:1068)
    at Object.e.invokeMethod (https://localhost:5001/_framework/blazor.webassembly.js:1:2130)
    at Object.he._internal.applyHotReload (https://localhost:5001/_framework/blazor.webassembly.js:1:49030)
    at https://localhost:5001/_framework/aspnetcore-browser-refresh.js:101:49
    at Array.forEach (<anonymous>)
    at applyBlazorDeltas (https://localhost:5001/_framework/aspnetcore-browser-refresh.js:101:12)
```

### Further technical details

```console
➜ dotnet --version
6.0.100-preview.3.21202.5
```

IDE is JetBrains Rider on macOS.

### Related Issue

Might be related to https://github.com/dotnet/aspnetcore/issues/31776

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this.

I tried it with preview 4 bits, and it no longer seems to repro. It appears that this edit now takes place correctly.

So, I'll close this. If you're still encountering this after updating to preview 4 (when it ships) please let us know!
