### ISSUE TITLE
Flaky test: RendersAuthorizingUntilAuthorizationCompletedAsync

### ISSUE THREAD

**Issue by jkotalik** [dotnet/aspnetcore#31854]
https://dev.azure.com/dnceng/public/_build/results?buildId=1091141&view=ms.vss-test-web.build-test-results-tab&runId=33438548&resultId=121892&paneView=debug
```
System.InvalidOperationException : Sequence contains more than one element

 at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.Components.Authorization.AuthorizeViewTest.RendersAuthorizingUntilAuthorizationCompletedAsync() in /_/src/Components/Authorization/test/AuthorizeViewTest.cs:line 318
```

**Comment by BrennanConroy** [comment]
Keep the issue open to track un-quarantining the test
