### ISSUE TITLE
Windows Preview caching test failures in HttpSys

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#31887]
Testing locally on Windows Preview build 21354.1 I'm seeing failures in the following caching tests. I think this is all of the cache hit tests that are now reporting cache misses. I've asked @jkotalik to verify on his machine. We have a CI for preview builds, but it's not updated as frequently, it's running 21327 (from 3/4).
```
Assemblies Run
Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.dll
Summary
Tests run: 471 — Failures: 9, Skipped: 7, Run time: 30.594s, Finished: 04/16/2021 14:58:47

Failed tests
0.0255715s✘ Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.ResponseCachingTests.Caching_Expires_Cached
Assert.Equal() Failure\r\n          ↓ (pos 0)\r\nExpected: 1\r\nActual:   2\r\n          ↑ (pos 0)
   at Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.ResponseCachingTests.Caching_Expires_Cached() in D:\github\AspNetCore\src\Servers\HttpSys\test\FunctionalTests\ResponseCachingTests.cs:line 231
--- End of stack trace from previous location ---
0.0652446s✘ Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.ResponseCachingTests.Caching_MaxAge_Cached
Assert.Equal() Failure\r\n          ↓ (pos 0)\r\nExpected: 1\r\nActual:   2\r\n          ↑ (pos 0)
   at Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.ResponseCachingTests.Caching_MaxAge_Cached() in D:\github\AspNetCore\src\Servers\HttpSys\test\FunctionalTests\ResponseCachingTests.cs:line 150
--- End of stack trace from previous location ---
0.0194943s✘ Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.ResponseCachingTests.Caching_MaxAgeAndExpires_MaxAgePreferred
Assert.Equal() Failure\r\n          ↓ (pos 0)\r\nExpected: 1\r\nActual:   2\r\n          ↑ (pos 0)
   at Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.ResponseCachingTests.Caching_MaxAgeAndExpires_MaxAgePreferred() in D:\github\AspNetCore\src\Servers\HttpSys\test\FunctionalTests\ResponseCachingTests.cs:line 319
--- End of stack trace from previous location ---
0.0346782s✘ Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.ResponseCachingTests.Caching_MaxAgeHuge_Cached
Assert.Equal() Failure\r\n          ↓ (pos 0)\r\nExpected: 1\r\nActual:   2\r\n          ↑ (pos 0)
   at Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.ResponseCachingTests.Caching_MaxAgeHuge_Cached() in D:\github\AspNetCore\src\Servers\HttpSys\test\FunctionalTests\ResponseCachingTests.cs:line 170
--- End of stack trace from previous location ---
0.0497963s✘ Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.ResponseCachingTests.Caching_SendFileWithFullContentLength_Cached
Assert.Equal() Failure\r\n          ↓ (pos 0)\r\nExpected: 1\r\nActual:   2\r\n          ↑ (pos 0)
   at Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.ResponseCachingTests.Caching_SendFileWithFullContentLength_Cached() in D:\github\AspNetCore\src\Servers\HttpSys\test\FunctionalTests\ResponseCachingTests.cs:line 401
--- End of stack trace from previous location ---
0.039836s✘ Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.ResponseCachingTests.Caching_SMaxAge_Cached
Assert.Equal() Failure\r\n          ↓ (pos 0)\r\nExpected: 1\r\nActual:   2\r\n          ↑ (pos 0)
   at Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.ResponseCachingTests.Caching_SMaxAge_Cached() in D:\github\AspNetCore\src\Servers\HttpSys\test\FunctionalTests\ResponseCachingTests.cs:line 190
--- End of stack trace from previous location ---
0.0240587s✘ Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.ResponseCachingTests.Caching_SMaxAgeAndMaxAge_SMaxAgePreferredCached
Assert.Equal() Failure\r\n          ↓ (pos 0)\r\nExpected: 1\r\nActual:   2\r\n          ↑ (pos 0)
   at Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.ResponseCachingTests.Caching_SMaxAgeAndMaxAge_SMaxAgePreferredCached() in D:\github\AspNetCore\src\Servers\HttpSys\test\FunctionalTests\ResponseCachingTests.cs:line 210
--- End of stack trace from previous location ---
0.0180905s✘ Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.ResponseCachingTests.Caching_VariousStatusCodes_Cached
System.Exception : Failed to get second response for 200\r\n---- Assert.Equal() Failure\r\n          ↓ (pos 0)\r\nExpected: 1\r\nActual:   2\r\n          ↑ (pos 0)
   at Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.ResponseCachingTests.Caching_VariousStatusCodes_Cached() in D:\github\AspNetCore\src\Servers\HttpSys\test\FunctionalTests\ResponseCachingTests.cs:line 447
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.ResponseCachingTests.Caching_VariousStatusCodes_Cached() in D:\github\AspNetCore\src\Servers\HttpSys\test\FunctionalTests\ResponseCachingTests.cs:line 443
0.0253806s✘ Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.ResponseCachingTests.Caching_WriteFullContentLength_Cached
Assert.Equal() Failure\r\n          ↓ (pos 0)\r\nExpected: 1\r\nActual:   2\r\n          ↑ (pos 0)
   at Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.ResponseCachingTests.Caching_WriteFullContentLength_Cached() in D:\github\AspNetCore\src\Servers\HttpSys\test\FunctionalTests\ResponseCachingTests.cs:line 362
--- End of stack trace from previous location ---

```

**Comment by jkotalik** [comment]
I'm not seeing this repro locally, winver 21364.1000.

**Comment by Tratcher** [comment]
Confirmed, it no longer repros for me on 21364.1000 or 21364.1011. Thanks for checking.
