### ISSUE TITLE
Flaky test ComponentWithConstrainedTypeParameters

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#32193]
https://dev.azure.com/dnceng/public/_build/results?buildId=1107818&view=ms.vss-test-web.build-test-results-tab&runId=33812670&resultId=100474&paneView=debug

```
System.InvalidOperationException : Aborting compilation to assembly because RazorCompiler returned nonempty diagnostics: x:\dir\subdir\Test\TestComponent.cshtml(2,19): Error RZ1017: Unexpected literal following the 'typeparam' directive. Expected 'line break'.\nx:\dir\subdir\Test\TestComponent.cshtml(3,19): Error RZ1017: Unexpected literal following the 'typeparam' directive. Expected 'line break'.
   at Microsoft.AspNetCore.Razor.Language.IntegrationTests.RazorIntegrationTestBase.CompileToAssembly(CompileToCSharpResult cSharpResult, Boolean throwOnFailure) in /_/src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Language/IntegrationTests/RazorIntegrationTestBase.cs:line 289
   at Microsoft.AspNetCore.Razor.Language.IntegrationTests.RazorIntegrationTestBase.CompileToCSharp(String cshtmlRelativePath, String cshtmlContent, Boolean throwOnFailure, String fileKind, String cssScope) in /_/src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Language/IntegrationTests/RazorIntegrationTestBase.cs:line 217
   at Microsoft.AspNetCore.Razor.Language.IntegrationTests.RazorIntegrationTestBase.CompileToCSharp(String cshtmlContent, Boolean throwOnFailure, String cssScope) in /_/src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Language/IntegrationTests/RazorIntegrationTestBase.cs:line 173
   at Microsoft.AspNetCore.Razor.Language.IntegrationTests.ComponentCodeGenerationTestBase.ComponentWithConstrainedTypeParameters() in /_/src/Razor/Microsoft.AspNetCore.Razor.Language/test/IntegrationTests/ComponentCodeGenerationTestBase.cs:line 239
```

Test was added on 4/19, but first failures I can see start on 4/22.

Also, would appreciate it if people didn't just retry the failing leg without filing an issue at a minimum

**Comment by pranavkm** [comment]
Would this explain the build failures we are seeing? This is pretty close to the scenario we're seeing with the build flakiness. 

FYI @javiercn / @captainsafia

**Comment by captainsafia** [comment]
I think there's some general spookiness that is happening as a result of the generic parameters change. The error above seems to indicate that some faulty code is being generated?

**Comment by javiercn** [comment]
I would not expect flakyness in this type of test. 

That might point out a larger issue within the compiler. Did we update the razor SDK to something recent? (I did the change where its only enabled in 6.0, so I'm wondering if somehow its receiving the wrong razorlanguageversion)

**Comment by captainsafia** [comment]
Just saw this happen locally while doing some work locally on the Razor compiler.

```
   System.InvalidOperationException : Aborting compilation to assembly because RazorCompiler returned nonempty diagnostics: x:\dir\subdir\Test\TestComponent.cshtml(2,19): Error RZ1017: Unexpected literal following the 'typeparam' directive. Expected 'line break'.
x:\dir\subdir\Test\TestComponent.cshtml(3,19): Error RZ1017: Unexpected literal following the 'typeparam' directive. Expected 'line break'.
  Stack Trace:
     at Microsoft.AspNetCore.Razor.Language.IntegrationTests.RazorIntegrationTestBase.CompileToAssembly(CompileToCSharpResult cSharpResult, Boolean throwOnFailure) in /Users/captainsafia/github.com/dotnet/aspnetcore/src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Language/IntegrationTests/RazorIntegrationTestBase.cs:line 289
   at Microsoft.AspNetCore.Razor.Language.IntegrationTests.RazorIntegrationTestBase.CompileToCSharp(String cshtmlRelativePath, String cshtmlContent, Boolean throwOnFailure, String fileKind, String cssScope) in /Users/captainsafia/github.com/dotnet/aspnetcore/src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Language/IntegrationTests/RazorIntegrationTestBase.cs:line 217
   at Microsoft.AspNetCore.Razor.Language.IntegrationTests.RazorIntegrationTestBase.CompileToCSharp(String cshtmlContent, Boolean throwOnFailure, String cssScope) in /Users/captainsafia/github.com/dotnet/aspnetcore/src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Language/IntegrationTests/RazorIntegrationTestBase.cs:line 173
   at Microsoft.AspNetCore.Razor.Language.IntegrationTests.ComponentCodeGenerationTestBase.ComponentWithConstrainedTypeParameters() in /Users/captainsafia/github.com/dotnet/aspnetcore/src/Razor/Microsoft.AspNetCore.Razor.Language/test/IntegrationTests/ComponentCodeGenerationTestBase.cs:line 241
```

The exception is coming from [here](https://github.com/dotnet/aspnetcore/blob/a76109b8dbb6c8dddef04a02e47284d26c9cdbb9/src/Razor/test/Microsoft.AspNetCore.Razor.Test.Common/Language/IntegrationTests/RazorIntegrationTestBase.cs#L217). The value of `declaration.Code` when the exception arises is:

```csharp
// <auto-generated/>
#pragma warning disable 1591
#pragma warning disable 0414
#pragma warning disable 0649
#pragma warning disable 0169

namespace Test
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
#nullable restore
#line 1 "x:\dir\subdir\Test\TestComponent.cshtml"
using Microsoft.AspNetCore.Components;

#line default
#line hidden
#nullable disable
    public partial class TestComponent : Microsoft.AspNetCore.Components.ComponentBase
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
        }
        #pragma warning restore 1998
#nullable restore
#line 12 "x:\dir\subdir\Test\TestComponent.cshtml"
       
    [Parameter] public TItem1 Item1 { get; set; }
    [Parameter] public List<TItem2> Items2 { get; set; }
    [Parameter] public RenderFragment<TItem2> ChildContent { get; set; }

#line default
#line hidden
#nullable disable
    }
}
#pragma warning restore 1591
```

**Comment by BrennanConroy** [comment]
Passed 30 days after being fixed 😃 
https://github.com/dotnet/aspnetcore/pull/34385
