### ISSUE TITLE
Flaky  test class WebSocketMiddlewareTests

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#32297]
`SendShortData_Success`

## Error Message

Microsoft.AspNetCore.Connections.ConnectionAbortedException : The connection was aborted because the server is shutting down and request processing didn't complete within the time specified by HostOptions.ShutdownTimeout.

## Stacktrace

   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult&amp; result) in System.IO.Pipelines.dll:token 0x6000073+0x0
   at System.IO.Pipelines.Pipe.GetReadAsyncResult() in System.IO.Pipelines.dll:token 0x6000072+0x42
   at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token) in System.IO.Pipelines.dll:token 0x6000175+0x0
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1UpgradeMessageBody.ReadAsyncInternalAwaited(ValueTask`1 readTask, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/Http/Http1UpgradeMessageBody.cs:line 102
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 destination, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/Http/HttpRequestStream.cs:line 118
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure) in System.Net.WebSockets.dll:token 0x60000d0+0xff
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken) in System.Net.WebSockets.dll:token 0x60000c5+0x111
   at Microsoft.AspNetCore.WebSockets.Test.WebSocketMiddlewareTests.&lt;&gt;c__DisplayClass3_0.&lt;&lt;SendShortData_Success&gt;b__0&gt;d.MoveNext() in /_/src/Middleware/WebSockets/test/UnitTests/WebSocketMiddlewareTests.cs:line 97
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.WebSockets.Test.KestrelWebSocketHelpers.&lt;&gt;c__DisplayClass0_0.&lt;&lt;CreateServer&gt;b__5&gt;d.MoveNext() in /_/src/Middleware/WebSockets/test/UnitTests/KestrelWebSocketHelpers.cs:line 32
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.WebSockets.Test.KestrelWebSocketHelpers.&lt;&gt;c__DisplayClass0_0.&lt;&lt;CreateServer&gt;b__5&gt;d.MoveNext() in /_/src/Middleware/WebSockets/test/UnitTests/KestrelWebSocketHelpers.cs:line 40
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application) in /_/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs:line 666
   at Microsoft.AspNetCore.WebSockets.Test.KestrelWebSocketHelpers.&lt;&gt;c__DisplayClass0_0.&lt;CreateServer&gt;b__4() in /_/src/Middleware/WebSockets/test/UnitTests/KestrelWebSocketHelpers.cs:line 84
   at Microsoft.AspNetCore.WebSockets.Test.KestrelWebSocketHelpers.Disposable.Dispose() in /_/src/Middleware/WebSockets/test/UnitTests/KestrelWebSocketHelpers.cs:line 100
   at Microsoft.AspNetCore.WebSockets.Test.WebSocketMiddlewareTests.SendShortData_Success() in /_/src/Middleware/WebSockets/test/UnitTests/WebSocketMiddlewareTests.cs:line 109
--- End of stack trace from previous location ---

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1115720&view=results

**Comment by wtgodbe** [comment]
Quarantining the whole class for now since all tests in it are subject to the same flakiness: https://github.com/dotnet/aspnetcore/pull/32294
