### ISSUE TITLE
Getting 502 Bad Gateway : Deployed on ubuntu 18.04 + NGINX + Asp.net core API 3.1 + PostgreSQLDB 

### ISSUE THREAD

**Issue by vikeshkataria** [dotnet/aspnetcore#32308]
I am getting 502 Bad gateway reverse proxy server , when i am accessing API. 

Configured krestel service port  on 5001 and  defined into appsetting.json

I performed these steps 
1. Publish code through command for Linux :
      dotnet publish --self-contained -c Release -r linux-x64
2. Copied published data on var/www/API folder
3. Created krestel service with below configuration
              [Unit]
              Description=WebAPIApp
              [Service]
              WorkingDirectory=/var/www/API
              ExecStart=/usr/bin/dotnet /var/www/API/WebAPI.dll
              Restart=always
              # Restart service after 10 seconds if the dotnet service crashes:
              RestartSec=10
              KillSignal=SIGINT
              SyslogIdentifier=dotnet-example
              User=www-data
              Environment=ASPNETCORE_ENVIRONMENT=Production
              
              Environment=DOTNET_PRINT_TELEMETRY_MESSAGE=false
              
              [Install]
              WantedBy=multi-user.target
4.  tested krestel service and its working without any error.
5. Now, I created site on nginx with below configuration
              server {
              listen        4001;
              location / {
                  proxy_pass         http://MachineNamewithDomain:5001;
                  proxy_http_version 1.1;
                  proxy_set_header   Upgrade $http_upgrade;
                  proxy_set_header   Connection keep-alive;
                  proxy_set_header   Host $host;
                  proxy_cache_bypass $http_upgrade;
                  proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header   X-Forwarded-Proto $scheme;
              }
          }
6.   enabled site in sites-enabled directory..
7.  allowed or open 4001 ,5001 port on network.
8.  i made entry on /etc/hosts as well  defined URL 
     10.10.10.10 API
9.  reboot of machine.
10.  After reboot,  I checked service is Up and running on port number 4001 .. I tried to access swagger and it is also working but
      when i am executing API its execute only once after that it is giving 502 bad gateway error.. I checked the logs there was  nothing.
11 then i tried to access krestel service , its also running and up.. I tried to access swagger , it is also working and able to access all API without any error.

12.  I configured krestel service URL (port number 5001)  with Angular UI.. Application is working now but i observed two challanges there
    1. sometimes it is not responding and response is coming blank.. I check on browser network HTTPstatuscode 200
    2.  Paralle request genrating from UI ( 20 requests of same single API ) in that case it is taking time and few requests converting into CORS error and  getting response of some request..  i checked the log  i am getting socket exception error
2021-04-26 06:10:52,700 [139] ERROR System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)

Problem :  Reverse proxy server is not working.. I tried to configure UI with krestel service url in that case some of requests are getting failed giving error socket exception 125...

Please assist me on this problem..

**Comment by BrennanConroy** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com/) using the asp.net-core tag.

**Comment by vikeshkataria** [comment]
@BrennanConroy Why i am getting System.Net.Sockets.SocketException (125): Operation canceled.. most of the request... Same code i deploed on IIS server .. it is working fine... But with Ubuntu , i am getting error..

Am not able to get reason for that..
