### ISSUE TITLE
Application startup exception

### ISSUE THREAD

**Issue by Manmohabe** [dotnet/aspnetcore#32339]
Am trying to host asp.net core 5 with identity server as windows service. But the application seems not to find the self signed certificate when its started by the service. Clicking on the published application .exe seems to work fine without any issue. This is my first time using identity server.

My appsettings.json configuration
```
  "IdentityServer": {
    "Clients": {
      "AisUI": {
        "Profile": "IdentityServerSPA"
      }
    },
    "Key": {
      "Type": "Store",
      "StoreName": "My",
      "StoreLocation": "CurrentUser",
      "Name": "CN=Sparkhub"
    }
  },
```

Exception: 
System.InvalidOperationException: Couldn't find a valid certificate with subject 'CN=Sparkhub' on the 'CurrentUser\My'
   at Microsoft.AspNetCore.ApiAuthorization.IdentityServer.SigningKeysLoader.LoadFromStoreCert(String subject, String storeName, StoreLocation storeLocation, DateTimeOffset currentTime)
   at Microsoft.AspNetCore.ApiAuthorization.IdentityServer.ConfigureSigningCredentials.LoadKey()
   at Microsoft.AspNetCore.ApiAuthorization.IdentityServer.ConfigureSigningCredentials.Configure(ApiAuthorizationOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsManager`1.Get(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.get_Value()
   at Microsoft.Extensions.DependencyInjection.IdentityServerBuilderConfigurationExtensions.<>c.<AddClients>b__8_1(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.AspNetCore.Builder.IdentityServerApplicationBuilderExtensions.TestService(IServiceProvider serviceProvider, Type service, ILogger logger, String message, Boolean doThrow)
   at Microsoft.AspNetCore.Builder.IdentityServerApplicationBuilderExtensions.Validate(IApplicationBuilder app)
   at Microsoft.AspNetCore.Builder.IdentityServerApplicationBuilderExtensions.UseIdentityServer(IApplicationBuilder app, IdentityServerMiddlewareOptions options)
   at AisUI.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in D:\ntera\FASCompany\SparkhubSoftware\AisUI\Startup.cs:line 118
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)

**Comment by javiercn** [comment]
@Manmohabe thanks for contacting us.

Is your certificate self-signed? 
Is it trusted by the machine you are deploying? 
Does it have valid experiation dates?
Can you validate that your process is able to load the certificate manually with C#? (use the code below as reference)

```csharp
using (var store = new X509Store(storeName, storeLocation))
{
    X509Certificate2Collection storeCertificates = null;
    X509Certificate2 foundCertificate = null;

    try
    {
        store.Open(OpenFlags.ReadOnly);
        storeCertificates = store.Certificates;
        var foundCertificates = storeCertificates
            .Find(X509FindType.FindBySubjectDistinguishedName, subject, validOnly: false);

        foundCertificate = foundCertificates
            .OfType<X509Certificate2>()
            .Where(certificate => certificate.NotBefore <= currentTime && certificate.NotAfter > currentTime)
            .OrderBy(certificate => certificate.NotAfter)
            .FirstOrDefault();

        if (foundCertificate == null)
        {
            throw new InvalidOperationException("Couldn't find a valid certificate with " +
                $"subject '{subject}' on the '{storeLocation}\\{storeName}'");
        }

        return foundCertificate;
    }
    finally
    {
        DisposeCertificates(storeCertificates, except: foundCertificate);
    }
}
```

**Comment by Manmohabe** [comment]
@javiercn Thanks for your reply.
Using your code as shown above, am able to see the certificate in the 
`storeCertificates = store.Certificates;` please the attached screenshot.
![certificate](https://user-images.githubusercontent.com/42378971/116968622-867bf880-acbd-11eb-94c4-07edab4d9b87.PNG)
although the following code gives me null (I think am wrong in the FindValue object, which value do we find by??)
```
 var foundCertificates = storeCertificates
                        .Find(X509FindType.FindBySubjectDistinguishedName, "Sparkhub", validOnly: false);

   foundCertificate = foundCertificates
            .OfType<X509Certificate2>()
     .Where(certificate => certificate.NotBefore <= currentTime && certificate.NotAfter > currentTime)
          .OrderBy(certificate => certificate.NotAfter)
          .FirstOrDefault();
```
I have used the following in powershell to generate the certificate
```
New-SelfsignedCertificate -KeyExportPolicy Exportable -Subject "CN=Sparkhub" -KeySpec Signature
-KeyAlgorithm RSA -KeyLength 2048 -HashAlgorithm SHA256 -CertStoreLocation "cert:\CurrentUser\My" -NotAfter (Get-Date).A
ddYears(5)
```
Please help am stuck for 3 days now. 
Clicking on the published application .exe seems to get the certificate and therefore works as expected but when the .exe is configured to be started by windows service (hosting asp.net core as a windows serfvice) the above error seems to occur.

**Comment by javiercn** [comment]
@Manmohabe the issue is likely happening because you are trying to run the app as a service and the service doesn't have access to the certificate. We suggest you load the certificate from a file or from a certificate store your service account has access to. That likely means installing it on the machine store, not the user store.

**Comment by Manmohabe** [comment]
@javiercn Thanks for your prompt reply, please if you don't mind refer me to any documentation where i can follow. Being a starter on configuring certificates i don't understand what you mean by the machine store and the user store unless you guide me further. I think that might help someone in future too.
