### ISSUE TITLE
crit: Microsoft.AspNetCore.Server.Kestrel[0]       Unable to start Kestrel. System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.

### ISSUE THREAD

**Issue by Marcavax** [dotnet/aspnetcore#32444]
I don't know how to get rid of this error. I tried "dotnet dev-certs https --trust" and also deleting it from certmgr.msc > Personal > Certificates which seemed to help for this guy (https://github.com/dotnet/aspnetcore/issues/28399). 

This is the whole cmd log

C:\Users\marcu\Desktop\OpenWorldStarterPlugin\OWSInstanceLauncher>dotnet owsinstancelauncher.dll
Server Health Monitoring is checking for broken Zone Server Instances...
info: System.Net.Http.HttpClient.OWSInstanceManagement.LogicalHandler[100]
      Start processing HTTP request GET http://owsinstancemanagement.sabredartstudios.com/api/Instance/StartInstanceLauncher
info: System.Net.Http.HttpClient.OWSInstanceManagement.ClientHandler[100]
      Sending HTTP request GET http://owsinstancemanagement.sabredartstudios.com/api/Instance/StartInstanceLauncher
info: System.Net.Http.HttpClient.OWSInstanceManagement.LogicalHandler[100]
      Start processing HTTP request POST http://owsinstancemanagement.sabredartstudios.com/api/Instance/GetZoneInstancesForWorldServer
info: System.Net.Http.HttpClient.OWSInstanceManagement.ClientHandler[100]
      Sending HTTP request POST http://owsinstancemanagement.sabredartstudios.com/api/Instance/GetZoneInstancesForWorldServer
info: System.Net.Http.HttpClient.OWSInstanceManagement.ClientHandler[101]
      Received HTTP response headers after 303.2394ms - 200
info: System.Net.Http.HttpClient.OWSInstanceManagement.LogicalHandler[101]
      End processing HTTP request after 318.5398ms - 200
info: System.Net.Http.HttpClient.OWSInstanceManagement.ClientHandler[101]
      Received HTTP response headers after 245.1988ms - 200
info: System.Net.Http.HttpClient.OWSInstanceManagement.LogicalHandler[101]
      End processing HTTP request after 245.2927ms - 200
Attempting to Register OWS Instance Launcher with RabbitMQ ServerSpinUp Queue...
Registered OWS Instance Launcher with RabbitMQ ServerSpinUp Queue Success!
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
Shutting Down OWS Server Health Monitoring...
Shutting Down OWS Instance Launcher...
info: System.Net.Http.HttpClient.OWSInstanceManagement.LogicalHandler[100]
      Start processing HTTP request POST http://owsinstancemanagement.sabredartstudios.com/api/Instance/ShutDownInstanceLauncher
info: System.Net.Http.HttpClient.OWSInstanceManagement.ClientHandler[100]
      Sending HTTP request POST http://owsinstancemanagement.sabredartstudios.com/api/Instance/ShutDownInstanceLauncher
info: System.Net.Http.HttpClient.OWSInstanceManagement.ClientHandler[101]
      Received HTTP response headers after 117.2334ms - 200
info: System.Net.Http.HttpClient.OWSInstanceManagement.LogicalHandler[101]
      End processing HTTP request after 117.3608ms - 200
Shutting down all Server Instances...
Done!
Unhandled exception. System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at OWSInstanceLauncher.Program.Main(String[] args) in C:\Users\eric\source\repos\OWS\OWSInstanceLauncher\Program.cs:line 19

C:\Users\marcu\Desktop\OpenWorldStarterPlugin\OWSInstanceLauncher>dotnet dev-certs https --trust
Trusting the HTTPS development certificate was requested. A confirmation prompt will be displayed if the certificate was not previously trusted. Click yes on the prompt to trust the certificate.
The HTTPS developer certificate was generated successfully.

C:\Users\marcu\Desktop\OpenWorldStarterPlugin\OWSInstanceLauncher>dotnet owsinstancelauncher.dll
Server Health Monitoring is checking for broken Zone Server Instances...
info: System.Net.Http.HttpClient.OWSInstanceManagement.LogicalHandler[100]
      Start processing HTTP request GET http://owsinstancemanagement.sabredartstudios.com/api/Instance/StartInstanceLauncher
info: System.Net.Http.HttpClient.OWSInstanceManagement.ClientHandler[100]
      Sending HTTP request GET http://owsinstancemanagement.sabredartstudios.com/api/Instance/StartInstanceLauncher
info: System.Net.Http.HttpClient.OWSInstanceManagement.LogicalHandler[100]
      Start processing HTTP request POST http://owsinstancemanagement.sabredartstudios.com/api/Instance/GetZoneInstancesForWorldServer
info: System.Net.Http.HttpClient.OWSInstanceManagement.ClientHandler[100]
      Sending HTTP request POST http://owsinstancemanagement.sabredartstudios.com/api/Instance/GetZoneInstancesForWorldServer
info: System.Net.Http.HttpClient.OWSInstanceManagement.ClientHandler[101]
      Received HTTP response headers after 294.2322ms - 200
info: System.Net.Http.HttpClient.OWSInstanceManagement.LogicalHandler[101]
      End processing HTTP request after 311.0295ms - 200
Attempting to Register OWS Instance Launcher with RabbitMQ ServerSpinUp Queue...
info: System.Net.Http.HttpClient.OWSInstanceManagement.ClientHandler[101]
      Received HTTP response headers after 245.4378ms - 200
info: System.Net.Http.HttpClient.OWSInstanceManagement.LogicalHandler[101]
      End processing HTTP request after 245.5212ms - 200
Registered OWS Instance Launcher with RabbitMQ ServerSpinUp Queue Success!
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
Shutting Down OWS Server Health Monitoring...
Shutting Down OWS Instance Launcher...
info: System.Net.Http.HttpClient.OWSInstanceManagement.LogicalHandler[100]
      Start processing HTTP request POST http://owsinstancemanagement.sabredartstudios.com/api/Instance/ShutDownInstanceLauncher
info: System.Net.Http.HttpClient.OWSInstanceManagement.ClientHandler[100]
      Sending HTTP request POST http://owsinstancemanagement.sabredartstudios.com/api/Instance/ShutDownInstanceLauncher
info: System.Net.Http.HttpClient.OWSInstanceManagement.ClientHandler[101]
      Received HTTP response headers after 137.2992ms - 200
info: System.Net.Http.HttpClient.OWSInstanceManagement.LogicalHandler[101]
      End processing HTTP request after 137.4892ms - 200
Shutting down all Server Instances...
Done!
Unhandled exception. System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at OWSInstanceLauncher.Program.Main(String[] args) in C:\Users\eric\source\repos\OWS\OWSInstanceLauncher\Program.cs:line 19

**Comment by Tratcher** [comment]
@javiercn @halter73

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
What device are you running on? Is this a MacOS and which version?
Also, can you share the output from the `dotnet --info` ?
