### ISSUE TITLE
Resolve issues with dotnet-openapi tests in latest SDK

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#32686]
Following the latest SDK bump in https://github.com/dotnet/aspnetcore/pull/32581, the dotnet-openapi tests are failing due to some issues with the new workload resolution flag.

```
  Error Message:
   Threw error: The SDK 'Microsoft.NET.SDK.WorkloadAutoImportPropsLocator' specified could not be found.  /Users/captainsafia/github.com/dotnet/aspnetcore/.dotnet/sdk/6.0.100-preview.5.21264.3/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.props

Expected: True
Actual:   False
  Stack Trace:
     at Microsoft.DotNet.OpenApi.Tests.OpenApiTestBase.AssertNoErrors(Int32 appExitCode) in /Users/captainsafia/github.com/dotnet/aspnetcore/src/Tools/Microsoft.dotnet-openapi/test/OpenApiTestBase.cs:line 116
   at Microsoft.DotNet.OpenApi.Add.Tests.OpenApiAddURLTests.OpenApi_Add_Url() in /Users/captainsafia/github.com/dotnet/aspnetcore/src/Tools/Microsoft.dotnet-openapi/test/OpenApiAddURLTests.cs:line 158
--- End of stack trace from previous location ---
```

And when run locally:

```
❯ ~/github.com/dotnet/aspnetcore/.dotnet/dotnet ~/github.com/dotnet/aspnetcore/artifacts/bin/Microsoft.dotnet-openapi/Debug/net6.0/dotnet-openapi.dll add url "https://google.com"
Downloading to '/Users/captainsafia/github.com/dotnet/aspnetcore/src/Tools/Microsoft.dotnet-openapi/test/google.json'.

The SDK 'Microsoft.DotNet.Arcade.Sdk' specified could not be found.  /Users/captainsafia/github.com/dotnet/aspnetcore/Directory.Build.props
```

Skipping the tests for now to unblock our build issues but we'll need to follow-up on this once we have a resolution in the SDK.

Ref: https://github.com/dotnet/sdk/issues/17461

**Comment by dougbu** [comment]
I'm pretty sure there's nothing to "resolve" here. Testing in #36171

**Comment by captainsafia** [comment]
@dougbu A subsequent SDK update probably resolved the issue. As I recall, this particular stacktrace was tracked down to an external issue.

**Comment by dougbu** [comment]
@captainsafia please review #36171. Then we can close this 😀

**Comment by dougbu** [comment]
Issue is not mentioned in release/3.1 or release/5.0.

- [x] #36171
- [x] #36355
