### ISSUE TITLE
Specified argument was out of the range of valid values. (Parameter 'start')

### ISSUE THREAD

**Issue by vukasinpetrovic** [dotnet/aspnetcore#32784]
### Describe the bug
When I upgraded the projects target framework to net5.0 I got a runtime exception that stated "Specified argument was out of the range of valid values. (Parameter 'start')". I could not find out why was it happening, other than it occurs on post methods.

### To Reproduce
On mac osx upgrade projects target framework from 3.1 to 5.0

### Exceptions (if any)
Specified argument was out of the range of valid values. (Parameter 'start')

### Further technical details
- ASP.NET Core version : 5.0.6
- Include the output of `dotnet --info`
.NET SDK (reflecting any global.json):
 Version:   5.0.203
 Commit:    383637d63f

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.203/

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  3.1.406 [/usr/local/share/dotnet/sdk]
  3.1.407 [/usr/local/share/dotnet/sdk]
  3.1.408 [/usr/local/share/dotnet/sdk]
  3.1.409 [/usr/local/share/dotnet/sdk]
  5.0.103 [/usr/local/share/dotnet/sdk]
  5.0.201 [/usr/local/share/dotnet/sdk]
  5.0.202 [/usr/local/share/dotnet/sdk]
  5.0.203 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: jetbrains rider 2021.1.2 and VS 8.9.9

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by davidfowl** [comment]
@vukasinpetrovic  do you have a callstack?

**Comment by vukasinpetrovic** [comment]
@davidfowl I was able to get this stack trace. I forgot to mention one thing in the main issue description, this only happens on mac os, on windows I works without problems.


``
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'start')
   at System.Buffers.ReadOnlySequence`1.TryGet(SequencePosition& position, ReadOnlyMemory`1& memory, Boolean advance)
   at System.IO.Pipelines.PipeReader.CopyToAsyncCore[TStream](TStream destination, Func`4 writeAsync, CancellationToken cancellationToken)
   at Audit.WebApi.AuditApiHelper.GetRequestBody(HttpContext httpContext)
   at Audit.WebApi.AuditApiAdapter.CreateOrUpdateAction(ActionExecutingContext actionContext, Boolean includeHeaders, Boolean includeRequestBody, Boolean serializeParams, String eventTypeName)
   at Audit.WebApi.AuditApiAdapter.BeforeExecutingAsync(ActionExecutingContext actionContext, Boolean includeHeaders, Boolean includeRequestBody, Boolean serializeParams, String eventTypeName)
   at Audit.WebApi.AuditApiGlobalFilter.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
``

**Comment by davidfowl** [comment]
Can you share the code inside of `GetRequestBody`?

**Comment by davidfowl** [comment]
> this only happens on mac os, on windows it works without problems.

On Windows are you using IIS? (or IIS Express?)

**Comment by vukasinpetrovic** [comment]
@davidfowl On windows we are using IIS Express. I don't have any function named GetRequestBody in my project, maybe it is related to Audit.NET library. I wrote them issue also, maybe they know what's the problem, because I saw it in stacktrace.

**Comment by davidfowl** [comment]
So it's probably not windows specific, but it might be Kestrel specific. Can you reproduce this at will?

**Comment by vukasinpetrovic** [comment]
@davidfowl Yes, I can reproduce it constantly by switching between target framework from 3.1 to 5. When on 3.1 everything is ok, when I switch to 5 that exception occurs. Should I maybe remove all versions of .net sdk and runtime from mac and reinstall them?

**Comment by davidfowl** [comment]
Nooo, I just want you to help me debug since you have the repro 😄 . [This is the code](https://github.com/thepirat000/Audit.NET/blob/8d410cb919f09d0c35f7c622d2e21913bcc46c59/src/Audit.WebApi/AuditApiHelper.cs#L90) that's failing. Can you disable Audit.NET and write the equivalent code in your controller action? I want to narrow it down.

**Comment by vukasinpetrovic** [comment]
@davidfowl When I removed this config below, it started working. I don't know how to fix that. Your suggestion to write equivalent code would work if I could control what that library calls.

![image](https://user-images.githubusercontent.com/23005422/118632989-447ca780-b7d1-11eb-837a-3b60a09ccb71.png)

**Comment by vukasinpetrovic** [comment]
Problem was with my implementation of Audit.Net library. This is the issue connected with that https://github.com/thepirat000/Audit.NET/issues/404

Thank you guys for quick replies and help!
