### ISSUE TITLE
Transient failure to refresh a key ring produces a 500 response

### ISSUE THREAD

**Issue by mdomashchenko** [dotnet/aspnetcore#33116]
Here's how it happens:

1. A request comes in, with a cookie. Cookie handler needs to decrypt the cookie, this ultimately results in a call to `KeyRingBasedDataProtector.UnprotectCore()`
1. `UnprotectCore` calls `KeyRingProvider.GetCurrentKeyRingCore` to get keys. The latter determines that it needs to refresh the key ring from the repository.
1. The repository experiences some transient failure and throws an exception. At this time the `KeyRingProvider` does have the key ring available, so it extends its lifetime for 2 minutes and reports that from here https://github.com/dotnet/aspnetcore/blob/3341e46cb7198c0b5dab7cb0bf5893fee8da2c46/src/DataProtection/DataProtection/src/KeyManagement/KeyRingProvider.cs#L211
1. Now, instead of just returning the old key ring with freshly extended lifetime, `KeyRingProvider` re-throws the exception. Rationale for that is described here https://github.com/dotnet/aspnetcore/blob/3341e46cb7198c0b5dab7cb0bf5893fee8da2c46/src/DataProtection/DataProtection/src/KeyManagement/KeyRingProvider.cs#L229-L231
2. The problem is, `KeyRingBasedDataProtector.UnprotectCore` does not retry. If it did, it would get the key ring, because it's lifetime was just extended. But it just doesn't make that second call to `GetCurrentKeyRing` https://github.com/dotnet/aspnetcore/blob/3341e46cb7198c0b5dab7cb0bf5893fee8da2c46/src/DataProtection/DataProtection/src/KeyManagement/KeyRingBasedDataProtector.cs#L239
3. So, the cookie is not decrypted, authentication handler fails and the error leaks to the caller as a 500 response, which is completely preventable.

Here's a stack trace for your reference

> at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys()
> at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
> at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now)
> at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow, Boolean forceRefresh)
> at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)

**Comment by HaoK** [comment]
Tracked as part of https://github.com/dotnet/aspnetcore/issues/33116

**Comment by amcasey** [comment]
This is definitely worth fixing and we're planning to prioritize it in 9.0, but I don't think this particular issue adds new details to the general understanding of the key creation/synchronization race.  Tracked in https://github.com/dotnet/aspnetcore/issues/36157 and elsewhere.
