### ISSUE TITLE
VSCode - Razon extension crashes when directory contains plus sign

### ISSUE THREAD

**Issue by Ark-kun** [dotnet/aspnetcore#33144]
My workplace directory is `A:\<path>\SchemaStore+schemastore`. Note the plus character in the dir name.

I see the following error in the "Razor  Log" output window:
```
--------------------------------------------------------------------------------
Razor.VSCode version 6.0.0-preview.5.21271.1
--------------------------------------------------------------------------------
Razor's trace level is currently set to 'Off'
 - To change Razor's trace level set 'razor.trace' to 'Off', 'Messages' or 'Verbose' and then restart VSCode.
 - To report issues invoke the 'Report a Razor issue' command via the command palette.
-----------------------------------------------------------------------------------------------------------------------------

[Error - 18:51:23] Server initialization failed.
  Message: Internal Error - System.IO.DirectoryNotFoundException: Could not find a part of the path 'a:\<path>\SchemaStore schemastore'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound) in System.IO.FileSystem.dll:token 0x6000214+0x46
   at System.IO.Enumeration.FileSystemEnumerator`1.Init() in System.IO.FileSystem.dll:token 0x6000212+0x0
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options) in System.IO.FileSystem.dll:token 0x6000203+0x61
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized) in System.IO.FileSystem.dll:token 0x60001d2+0x42
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options) in System.IO.FileSystem.dll:token 0x60001e7+0x14
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options) in System.IO.FileSystem.dll:token 0x600009d+0x2c
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption) in System.IO.FileSystem.dll:token 0x6000093+0x0
   at Microsoft.AspNetCore.Razor.LanguageServer.ProjectConfigurationFileChangeDetector.GetExistingConfigurationFiles(String workspaceDirectory) in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationFileChangeDetector.cs:line 119
   at Microsoft.AspNetCore.Razor.LanguageServer.ProjectConfigurationFileChangeDetector.StartAsync(String workspaceDirectory, CancellationToken cancellationToken) in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/ProjectConfigurationFileChangeDetector.cs:line 56
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorFileChangeDetectorManager.InitializedAsync() in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorFileChangeDetectorManager.cs:line 46
   at Microsoft.AspNetCore.Razor.LanguageServer.RazorLanguageServer.<>c__DisplayClass9_0.<<CreateAsync>b__2>d.MoveNext() in /_/src/Razor/src/Microsoft.AspNetCore.Razor.LanguageServer/RazorLanguageServer.cs:line 100
--- End of stack trace from previous location ---
   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.MediatR.IRequestHandler<OmniSharp.Extensions.LanguageServer.Protocol.Models.InternalInitializeParams,OmniSharp.Extensions.LanguageServer.Protocol.Models.InitializeResult>.Handle(InternalInitializeParams request, CancellationToken token) in OmniSharp.Extensions.LanguageServer.dll:token 0x6000032+0x96d
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in OmniSharp.Extensions.LanguageServer.dll:token 0x60000a0+0x2a6
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in OmniSharp.Extensions.LanguageServer.dll:token 0x600009f+0x0
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in MediatR.dll:token 0x6000058+0x0
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in MediatR.dll:token 0x6000056+0x0
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in MediatR.dll:token 0x6000053+0x0
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in MediatR.dll:token 0x6000053+0x25c
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in MediatR.dll:token 0x600004a+0x0
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next) in MediatR.dll:token 0x600004a+0x1cd
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|5_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger) in OmniSharp.Extensions.JsonRpc.dll:token 0x600022a+0xfc
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token) in OmniSharp.Extensions.JsonRpc.dll:token 0x6000221+0x622
   at OmniSharp.Extensions.JsonRpc.InputHandler.<>c__DisplayClass38_0.<<RouteRequest>b__5>d.MoveNext() in OmniSharp.Extensions.JsonRpc.dll:token 0x6001089+0xf2
  Code: -32603 
```
Note the lack of plus character in the dir name.

VSCode version: 
```
Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.18363
```

C# extension version: `v1.23.12`

**Comment by ryanbrandenburg** [comment]
I think I have this so that it doesn't crash (we were double-encoding the `+`, turning it into a ` ` and causing the files/directories being looked for to not be found), but now we're not getting a C# experience in those files, so more investigation needed.
