### ISSUE TITLE
Custom launchSettings.json profile causes "Unable to configure HTTPS endpoint. No server certificate was specified"

### ISSUE THREAD

**Issue by Kla3mus** [dotnet/aspnetcore#33220]
### Description

When creating a new standard blazor serverside (with docker) project, and adding the following to launchSettings.json:

```
"DockerTest": {
      "commandName": "Docker",
      "launchBrowser": true,
      "launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}",
      "publishAllPorts": true,
      "useSSL": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "TEST"
      }
    }
```

I basically copied the entry for Docker, renamed Docker to DockerTest and added the environmentVariables

Then selecting that particular profile and run it, I get the following exception:
![image](https://user-images.githubusercontent.com/6784123/120466492-6ebc9080-c39f-11eb-8c1c-9e163eebe91d.png)

Happens both in Chrome and Firefox

App runs fine if I use the default Docker profile.

I tried to do what the exception said; and this is what the developer console spit out:
![image](https://user-images.githubusercontent.com/6784123/120467222-3b2e3600-c3a0-11eb-8d71-8188022e65c1.png)

### Configuration

I'm running .net 5.0.300 on windows 10, 20H2 build 19042.985
Visual Studio 2019 - 16,10,0

System.InvalidOperationException
  HResult=0x80131509
  Message=Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
  Source=Microsoft.AspNetCore.Server.Kestrel.Core
  StackTrace:
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.<BindAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.<BindAsync>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<BindAsync>d__32.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<StartAsync>d__29`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__31.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Admin.Program.Main(String[] args) in C:\Devops\ST-Test\Admin\Program.cs:line 16

  This exception was originally thrown at this call stack:
    Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions, System.Action<Microsoft.AspNetCore.Server.Kestrel.Https.HttpsConnectionAdapterOptions>)
    Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions)
    Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBindContext)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
    Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(System.Collections.Generic.IEnumerable<Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions>, Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBindContext)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    ...
    [Call Stack Truncated]

**Comment by Tratcher** [comment]
@javiercn where's the logic that checks for `Development` in this situation?

**Comment by Kla3mus** [comment]
> I did some experimenting and since you're switching the environment to one that is not from the predefined 3: Development, Staging, Production; it's somehow not able to pick up the trusted cert. I assume there's some piece of configuration that needs to be done for the new environment.
> 
> Is using your custom environment something that's necessary for you? I assume that if you switch back to "Development" it will work.
> 
> @Pilchie My knowledge here is lacking. Is this something unsupported? Or is there anything the customer can do to make it work?

This is indeed needed. I have an application with setups for multiple clients, which requires multiple configurations. It loads various modules for various clients, and various connectionstrings for these various clients.

**Comment by Kla3mus** [comment]
> @Pilchie It's a combo between the custom environment and Docker.
> 
> The way docker works from VS requires the environment to be `Development`. Otherwise we don't try to probe the filesystem for the developer certificate (for security reasons).
> 
> When you use a custom environment you need to setup the certificate explicitly via config.
> 
> We have docs [here](https://docs.microsoft.com/en-us/aspnet/core/security/docker-https?view=aspnetcore-5.0) and [here](https://docs.microsoft.com/en-us/aspnet/core/security/docker-compose-https?view=aspnetcore-5.0) on how to do this setup.

Thanks! I'll take a look at the documentation. Does this mean that this lack of feature is intentional, and that it won't be implemented?

**Comment by javiercn** [comment]
@Kla3mus If you have that type of advanced setup, we recommend you explicitly use your own certificate with it instead of relying on dev-certs.

Kestrel will only load the development certificate when it finds it on the certificate store (which indicates the SDK is installed on the machine) or when the app is running under `Development` and we find the certificate file with a specific naming convention in the right folder as well as the associated password for the cert in the config.

Docker tooling across IDEs (VS, VS 4 Mac, VS Code) will export the certificate into a path that they then map on the docker container being run, which is why this works when running from an IDE without you having to do anything.

The recommendation if you have a custom environment is that you setup the `Default` https certificate in your `docker-compose.overrides.yml` or similar.
* Export the cert to a folder.
* Map the folder as a volume on the container.
* Setup the password in user secrets under Kestrel -> Certificates -> Default.
* Setup the path to the certificate on appSettings.myEnvironment.json

**Comment by Kla3mus** [comment]
Hmm...

How are the profiles supposed to be used, if my case is considered an "advanced setup"? The way I understand it is that it cannot be used at all with docker?
