### ISSUE TITLE
[.NET 5.0 / Blazor server] Error: WebSocket closed with status code: 1006 on intensive treatment

### ISSUE THREAD

**Issue by julienGrd** [dotnet/aspnetcore#33330]
Hello guys, on my blazor server app I fall on js error while i make some intensive treatment on complex views.
The error is  on the browser console is
````
HttpConnection.stopConnection(Error: WebSocket closed with status code: 1006 ().) called while in state Connected.
Error: Connection disconnected with error 'Error: WebSocket closed with status code: 1006 ().'.
````
The app is not able to reconnect after that

I activate the signalr logging both on server and client side to understand whats happen
- on client side i don't have more information
- on server side i retrieve this error
````
2021-06-07 08:42:17.631 +02:00 [DBG] Received hub invocation: InvocationMessage { InvocationId: "", Target: "OnRenderCompleted", Arguments: [ 85,  ], StreamIds: [  ] }.
2021-06-07 08:42:31.954 +02:00 [DBG] Error writing frame.
System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived'
   at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
   at System.Net.WebSockets.ManagedWebSocket.SendPrivateAsync(ReadOnlyMemory`1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at System.Net.WebSockets.WebSocketExtensions.SendMultiSegmentAsync(WebSocket webSocket, ReadOnlySequence`1 buffer, WebSocketMessageType webSocketMessageType, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsServerTransport.StartSending(WebSocket socket)
2021-06-07 08:42:32.000 +02:00 [DBG] Waiting for the client to close the socket.
2021-06-07 08:42:32.634 +02:00 [DBG] Socket closed.
2021-06-07 08:42:32.637 +02:00 [DBG] Error when processing requests.
System.Net.WebSockets.WebSocketException (0x80004005): The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseSent'
   at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsync(Memory`1 buffer, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsServerTransport.StartReceiving(WebSocket socket)
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.DispatchMessagesAsync(HubConnectionContext connection)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.RunHubAsync(HubConnectionContext connection)
2021-06-07 08:42:32.687 +02:00 [DBG] OnConnectedAsync ending.
2021-06-07 08:42:32.690 +02:00 [DBG] Removing connection -iv9wQOHUKT03j-Auh-DPw from the list of connections.
2021-06-07 08:42:35.909 +02:00 [DBG] New connection H7eY0qRW77e4vjLmn0YxSw created.
2021-06-07 08:42:35.909 +02:00 [DBG] Sending negotiation response.
2021-06-07 08:42:36.493 +02:00 [DBG] Establishing new connection.
2021-06-07 08:42:36.494 +02:00 [DBG] Socket opened using Sub-Protocol: 'null'.
````

I precise this error only happened on deployed app (host on IIS on a windows server), it never happen on development server with visual studio.

I check the pool of my app on IIS, everything seem OK, the memory is at 0 which seem to indicate unlimited memory for the app.

I dont know what to do now...

thanks for your help !

**Comment by mkArtakMSFT** [comment]
@BrennanConroy  FYI, in case you've seen something similar and know what may cause this

**Comment by tracsorenson** [comment]
I am seeing something similar, with unexpected WebSocket closures and continuous Attempt to reconnects in UI.

<table>
<tr><td><b>Request Path</b></td><td><b>Event</b></td></tr>

<tr><td>/_blazor/negotiate</td> 	<td>New connection aXrl8B6U-aITWjbkz0SxOA created.</td></tr>
<tr><td>/_blazor/negotiate</td>	<td>Sending negotiation response.</td></tr>
<tr><td>/_blazor</td>		<td>Establishing new connection.</td></tr>	
<tr><td>/_blazor</td>			<td>OnConnectedAsync started.</td></tr>
<tr><td>/_blazorSocket</td> 	<td>Opened using Sub-Protocol: 'null'.</td></tr>
<tr><td>/_blazor</td>			<td>Found protocol implementation for requested protocol: blazorpack.</td></tr>
<tr><td>/_blazor</td>			<td>Completed connection handshake. Using HubProtocol 'blazorpack'.</td></tr>
<tr><td>/_blazor</td>			<td>Received hub invocation: InvocationMessage { InvocationId: "0", Target: "StartCircuit", Arguments: [ https://xxx.y.com/, https://xxx.y.com/, [{"type":"server","sequence":0,"descriptor":"CfDJ8Is+MQizzaNDrBSFLA9+tJ4YnIcs+txUsFQ+L/12vFZDLYiSA6rQEI3UZMazqaF4kqibRmmMBVrjklBBy181jCFZT6xHI6PWPGYBCXKKUooVszTss8HlVQjCbDVEg3S0O5DJNju1Fm3NlecApkras2YGqOKCG7bNtGWi8JkNHfVs3fTSqbDOZIIbgLJ5nZm0dgC6NW93+60dbLug0BZH7uyvuIhwB+sIDetL/kr9fgWrWeFdODI3wa1baaJMfWGJrJvyVjmze/0URp9XiUaQq8gwbICvkGxQZTN79NufFN/8pTIEzHO42/N8HnHwryZprDXKyqSMHd9lhiobQLFhMpdKrISco5Er813L5oh4Jk4csThVMFwwKUq+lvoqQTP5Mt4SKc6EMXogGUMKaVLMPW4="}] ], StreamIds: [ ] }.</td></tr>
<tr><td>/_blazor</td>			<td>Received hub invocation: InvocationMessage { InvocationId: "", Target: "OnRenderCompleted", Arguments: [ 2, ], StreamIds: [ ] }.</td></tr>
<tr><td>/_blazor</td>			<td>User xxx has been authenticated</td></tr>
<tr><td>/_blazor</td>			<td>Received hub invocation: InvocationMessage { InvocationId: "", Target: "DispatchBrowserEvent", Arguments: [ {"browserRendererId":0,"eventHandlerId":3,"eventArgsType":"mouse","eventFieldInfo":null}, {"type":"click","detail":1,"screenX":1958,"screenY":107,"clientX":38,"clientY":36,"offsetX":14,"offsetY":16,"button":0,"buttons":0,"ctrlKey":false,"shiftKey":false,"altKey":false,"metaKey":false} ], StreamIds: [ ] }.</td></tr>
<tr><td>/_blazor</td>			<td style="color:#ff0000">***Error writing frame.</td></tr>
<tr><td>/_blazor</td>  			<td>OnConnectedAsync ending.</td></tr>
<tr><td>/_blazor</td>			<td>Socket closed.</td></tr>
<tr><td>/_blazor</td>			<td>Waiting for the client to close the socket.</td></tr>
</table>

<p style="color:#ff0000">***System.Threading.Tasks.TaskCanceledException: A task was canceled.<br />
at System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync(MessageOpcode opcode, Boolean endOfMessage, ReadOnlyMemory`1 payloadBuffer, CancellationToken cancellationToken)<br />
at System.Net.WebSockets.WebSocketExtensions.SendMultiSegmentAsync(WebSocket webSocket, ReadOnlySequence`1 buffer, WebSocketMessageType webSocketMessageType, CancellationToken cancellationToken)<br />
at Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsServerTransport.StartSending(WebSocket socket)</p>

**Comment by javiercn** [comment]
@julienGrd thanks for contacting us.

It seems that this issue fell through the cracks. The report is for a very old Blazor version, so it is likely many things have changed. Are you still running into this issue with any modern Blazor version?

**Comment by julienGrd** [comment]
@javiercn no its very old issue, i don't met this case anymore, i don't remember whats what causing that. Im closing this issue
