### ISSUE TITLE
Quarantine BootResourceCachingTest.IncrementallyUpdatesCache

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#33371]
https://dev.azure.com/dnceng/public/_build/results?buildId=1175993&view=ms.vss-test-web.build-test-results-tab&runId=35398694&resultId=100584&paneView=debug

**Comment by pranavkm** [comment]
```
 http://127.0.0.1:1036/_framework/Microsoft.Extensions.DependencyInjection.Abstractions.dll - Failed to load resource: net::ERR_ADDRESS_IN_USE\r\n[2021-06-08T05:42:33Z] [Severe] http://127.0.0.1:1036/_framework/Microsoft.Extensions.FileProviders.Abstractions.dll - Failed to load resource: net::ERR_ADDRESS_IN_USE\r\n[2021-06-08T05:42:33Z] [Severe] http://127.0.0.1:1036/_framework/blazor.webassembly.js 0:41268 Uncaught TypeError: Failed to fetch\r\n[2021-06-08T05:42:33Z] [Severe] http://127.0.0.1:1036/_framework/blazor.webassembly.js 0:41268 Uncaught TypeError: Failed to fetch\r\n[2021-06-08T05:42:33Z] [Severe] 
```

That would suggest some sort of contention setting up the server. Not particularly specific to this test, no?

**Comment by TanayParikh** [comment]
Hmm that's a good point, may be related to https://github.com/dotnet/aspnetcore/issues/32219. Closing this PR out, and adding more details to the issue.

**Comment by TanayParikh** [comment]
Thanks!

**Comment by TanayParikh** [comment]
As Pranav pointed out in https://github.com/dotnet/aspnetcore/pull/33372, looks to be a resource contention issue. Possibly related to https://github.com/dotnet/aspnetcore/issues/32219?

```
OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.NotEmptyException: Assert.NotEmpty() Failure\r\n   at Xunit.Assert.NotEmpty(IEnumerable collection) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 331\r\n   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<Exists>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 72\r\n   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_01.<WaitAssertCore>b__0(IWebDriver _) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 109\r\nScreen shot captured at 'D:\\workspace\\_work\\1\\s\\artifacts\\TestResults\\Release\\Microsoft.AspNetCore.Components.E2ETests\\b9e9c0eaff904908a9da1ad35e1788e9.png'\r\nEncountered browser errors\r\n[2021-06-08T05:42:33Z] [Severe] http://127.0.0.1:1036/_framework/Microsoft.Extensions.DependencyInjection.Abstractions.dll - Failed to load resource: net::ERR_ADDRESS_IN_USE\r\n[2021-06-08T05:42:33Z] [Severe] http://127.0.0.1:1036/_framework/Microsoft.Extensions.FileProviders.Abstractions.dll - Failed to load resource: net::ERR_ADDRESS_IN_USE\r\n[2021-06-08T05:42:33Z] [Severe] http://127.0.0.1:1036/_framework/blazor.webassembly.js 0:41268 Uncaught TypeError: Failed to fetch\r\n[2021-06-08T05:42:33Z] [Severe] http://127.0.0.1:1036/_framework/blazor.webassembly.js 0:41268 Uncaught TypeError: Failed to fetch\r\n[2021-06-08T05:42:33Z] [Severe] http://127.0.0.1:1036/_framework/Microsoft.Extensions.FileProviders.Physical.dll - Failed to load resource: net::ERR_ADDRESS_IN_USE\r\n[2021-06-08T05:42:33Z] [Severe] http://127.0.0.1:1036/_framework/blazor.webassembly.js 0:41268 Uncaught TypeError: Failed to fetch\r\n[2021-06-08T05:42:34Z] [Severe] http://127.0.0.1:1036/_framework/blazor.webassembly.js 0:52205 Uncaught Error: Failed to start platform. Reason: TypeError: Failed to fetchPage content:\r\n<head>\r\n <meta charset=\"utf-8\">\r\n <title>Sample Blazor app</title>\r\n</head>\r\n<body>\r\n <app>Loading...</app>\r\n <script src=\"customJsFileForTests.js\"></script>\r\n <script src=\"_framework/blazor.webassembly.js\" autostart=\"false\"></script>\r\n\r\n <!--\r\n To show we can customize the boot resource loading process, the server looks for these\r\n flags when collecting logs, and E2E tests check the right entries were seen.\r\n -->\r\n <script>\r\n Blazor.start({\r\n loadBootResource: function (type, name, defaultUri, integrity) {\r\n return type === 'dotnetjs'\r\n ?${defaultUri}?customizedbootresource=true`\r\n                    : fetch(defaultUri, { integrity: integrity, cache: 'no-cache', headers: { 'customizedbootresource': 'true' } });\r\n            }\r\n        });\r\n    <script src="http://127.0.0.1:1036/_framework/dotnet.6.0.0-preview.5.21263.1.js?customizedbootresource=true" defer="" integrity="sha256-84C1l+/6CY0gFlKJdZvbsR0e7NbXxc9SNXwPdx38Zm8=" crossorigin="anonymous">
```

Stack Trace:
```
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 129
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.Exists(IWebDriver driver, By finder, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 67
   at Microsoft.AspNetCore.Components.E2ETest.Tests.BootResourceCachingTest.WaitUntilLoaded() in /_/src/Components/test/E2ETest/Tests/BootResourceCachingTest.cs:line 154
   at Microsoft.AspNetCore.Components.E2ETest.Tests.BootResourceCachingTest.IncrementallyUpdatesCache() in /_/src/Components/test/E2ETest/Tests/BootResourceCachingTest.cs:line 74
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<Exists>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 72
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 109
```

**Comment by TanayParikh** [comment]
May be able to leverage https://github.com/rainersigwald/ParallelBuildDebuggingLogger to help diagnose the resource contention.

**Comment by dougbu** [comment]
Seems like `area-blazor` is sufficient for this. Why did you add it to `area-infrastructure` @TanayParikh❔ This isn't something the build team will triage and we triage all `area-infrastructure` issues.

**Comment by TanayParikh** [comment]
Thanks for clarifying!
