### ISSUE TITLE
Quarantine Http2StreamTests .ContentLength_Received_MultipleDataFramesOverSize_Reset

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#33373]
https://dev.azure.com/dnceng/public/_build/results?buildId=1176635&view=ms.vss-test-web.build-test-results-tab&runId=35414634&resultId=106018&paneView=debug

**Comment by Tratcher** [comment]
Please copy the test failure details into this issue, the build results aren't saved very long.

**Comment by TanayParikh** [comment]
Comments
```
{ "HelixJobId": "1a46d24e-1dfa-4684-9303-ab6c169d3661", "HelixWorkItemName": "InMemory.FunctionalTests--net6.0" }
```

Error message
```
Assert.NotNull() Failure
```

Stack trace
   at 
```
Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2StreamTests.ContentLength_Received_MultipleDataFramesOverSize_Reset() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2StreamTests.cs:line 1049
--- End of stack trace from previous location ---
```

**Comment by Tratcher** [comment]
And the logs please 😁

**Comment by TanayParikh** [comment]
I assume you're referring to the test log there, in that case:

```
[0.000s] [TestLifetime] [Information] Starting test ContentLength_Received_MultipleDataFramesOverSize_Reset at 2021-06-08T16:57:22
[0.002s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "TestConnectionId" sending SETTINGS frame for stream ID 0 with length 18 and flags NONE.
[0.002s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "TestConnectionId" sending WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0.
[0.002s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "TestConnectionId" received SETTINGS frame for stream ID 0 with length 0 and flags NONE.
[0.002s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "TestConnectionId" sending SETTINGS frame for stream ID 0 with length 0 and flags ACK.
[0.002s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "TestConnectionId" received HEADERS frame for stream ID 1 with length 56 and flags END_HEADERS.
[0.002s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "TestConnectionId" received DATA frame for stream ID 1 with length 1 and flags NONE.
[0.002s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "TestConnectionId" received DATA frame for stream ID 1 with length 2 and flags NONE.
[0.002s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "TestConnectionId" received DATA frame for stream ID 1 with length 10 and flags NONE.
[0.003s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Debug] Connection id "TestConnectionId": HTTP/2 stream error.
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2StreamErrorException: HTTP/2 stream ID 1 error (PROTOCOL_ERROR): More data received than specified in the Content-Length header.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Stream.OnDataAsync(Http2Frame dataFrame, ReadOnlySequence`1& payload) in /_/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Stream.cs:line 439
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessDataFrameAsync(ReadOnlySequence`1& payload) in /_/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs:line 528
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessFrameAsync[TContext](IHttpApplication`1 application, ReadOnlySequence`1& payload) in /_/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs:line 475
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessRequestsAsync[TContext](IHttpApplication`1 application) in Microsoft.AspNetCore.Server.Kestrel.Core.dll:token 0x6000cf8+0x0
[0.006s] [Microsoft.AspNetCore.Server.Kestrel] [Error] Connection id "TestConnectionId", Request id "TestConnectionId:00000001": An unhandled exception was thrown by the application.
Xunit.Sdk.ThrowsException: Assert.Throws() Failure
Expected: typeof(System.IO.IOException)
Actual:   typeof(System.Threading.Tasks.TaskCanceledException): A task was canceled.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestPipeReader.<ValidateState>g__ThrowTaskCanceledException|14_1() in /_/src/Servers/Kestrel/Core/src/Internal/Http/HttpRequestPipeReader.cs:line 135
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 destination, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/Http/HttpRequestStream.cs:line 118
   at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2StreamTests.<>c__DisplayClass32_1.<<ContentLength_Received_MultipleDataFramesOverSize_Reset>b__1>d.MoveNext() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2StreamTests.cs:line 1035
--- End of stack trace from previous location ---
   at Xunit.Assert.RecordExceptionAsync(Func`1 testCode) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\Record.cs:line 81
[0.006s] [Microsoft.AspNetCore.Server.Kestrel] [Information] Connection id "TestConnectionId", Request id "TestConnectionId:00000001": the application completed without reading the entire request body.
[0.007s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "TestConnectionId" sending RST_STREAM frame for stream ID 1 with length 4 and flags 0x0.
[0.008s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Debug] Connection id "TestConnectionId" is closed. The last processed stream ID was 1.
[0.008s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "TestConnectionId" sending GOAWAY frame for stream ID 0 with length 8 and flags 0x0.
[0.008s] [Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2StreamTests] [Information] Waiting for Connection task
[0.008s] [Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2StreamTests] [Information] Stopping Connection From ConnectionErrorAsync
[0.010s] [Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2StreamTests] [Error] Test threw an exception.
Xunit.Sdk.NotNullException: Assert.NotNull() Failure
   at Xunit.Assert.NotNull(Object object) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\NullAsserts.cs:line 20
   at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2StreamTests.ContentLength_Received_MultipleDataFramesOverSize_Reset() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2StreamTests.cs:line 1049
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
[0.010s] [TestLifetime] [Information] Finished test ContentLength_Received_MultipleDataFramesOverSize_Reset in 0.0100116s
```

Console Output:
```
| [0.000s] TestLifetime Information: Starting test ContentLength_Received_MultipleDataFramesOverSize_Reset at 2021-06-08T16:57:22
| [0.002s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "TestConnectionId" sending SETTINGS frame for stream ID 0 with length 18 and flags NONE.
| [0.002s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "TestConnectionId" sending WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0.
| [0.002s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "TestConnectionId" received SETTINGS frame for stream ID 0 with length 0 and flags NONE.
| [0.002s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "TestConnectionId" sending SETTINGS frame for stream ID 0 with length 0 and flags ACK.
| [0.002s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "TestConnectionId" received HEADERS frame for stream ID 1 with length 56 and flags END_HEADERS.
| [0.002s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "TestConnectionId" received DATA frame for stream ID 1 with length 1 and flags NONE.
| [0.002s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "TestConnectionId" received DATA frame for stream ID 1 with length 2 and flags NONE.
| [0.002s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "TestConnectionId" received DATA frame for stream ID 1 with length 10 and flags NONE.
| [0.002s] Microsoft.AspNetCore.Server.Kestrel.Http2 Debug: Connection id "TestConnectionId": HTTP/2 stream error.
| Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2StreamErrorException: HTTP/2 stream ID 1 error (PROTOCOL_ERROR): More data received than specified in the Content-Length header.
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Stream.OnDataAsync(Http2Frame dataFrame, ReadOnlySequence`1& payload) in /_/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Stream.cs:line 439
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessDataFrameAsync(ReadOnlySequence`1& payload) in /_/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs:line 528
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessFrameAsync[TContext](IHttpApplication`1 application, ReadOnlySequence`1& payload) in /_/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Connection.cs:line 475
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessRequestsAsync[TContext](IHttpApplication`1 application) in Microsoft.AspNetCore.Server.Kestrel.Core.dll:token 0x6000cf8+0x0
| [0.006s] Microsoft.AspNetCore.Server.Kestrel Error: Connection id "TestConnectionId", Request id "TestConnectionId:00000001": An unhandled exception was thrown by the application.
| Xunit.Sdk.ThrowsException: Assert.Throws() Failure
| Expected: typeof(System.IO.IOException)
| Actual:   typeof(System.Threading.Tasks.TaskCanceledException): A task was canceled.
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestPipeReader.<ValidateState>g__ThrowTaskCanceledException|14_1() in /_/src/Servers/Kestrel/Core/src/Internal/Http/HttpRequestPipeReader.cs:line 135
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 destination, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/Http/HttpRequestStream.cs:line 118
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2StreamTests.<>c__DisplayClass32_1.<<ContentLength_Received_MultipleDataFramesOverSize_Reset>b__1>d.MoveNext() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2StreamTests.cs:line 1035
| --- End of stack trace from previous location ---
|    at Xunit.Assert.RecordExceptionAsync(Func`1 testCode) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\Record.cs:line 81
| [0.006s] Microsoft.AspNetCore.Server.Kestrel Information: Connection id "TestConnectionId", Request id "TestConnectionId:00000001": the application completed without reading the entire request body.
| [0.007s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "TestConnectionId" sending RST_STREAM frame for stream ID 1 with length 4 and flags 0x0.
| [0.008s] Microsoft.AspNetCore.Server.Kestrel.Http2 Debug: Connection id "TestConnectionId" is closed. The last processed stream ID was 1.
| [0.008s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "TestConnectionId" sending GOAWAY frame for stream ID 0 with length 8 and flags 0x0.
| [0.008s] Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2StreamTests Information: Waiting for Connection task
| [0.008s] Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2StreamTests Information: Stopping Connection From ConnectionErrorAsync
| [0.008s] Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2StreamTests Error: Test threw an exception.
| Xunit.Sdk.NotNullException: Assert.NotNull() Failure
|    at Xunit.Assert.NotNull(Object object) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\NullAsserts.cs:line 20
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2StreamTests.ContentLength_Received_MultipleDataFramesOverSize_Reset() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2StreamTests.cs:line 1049
|    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
| --- End of stack trace from previous location ---
|    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
|    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
| [0.010s] TestLifetime Information: Finished test ContentLength_Received_MultipleDataFramesOverSize_Reset in 0.0100116s
```

**Comment by BrennanConroy** [comment]
Related issue #17840 we believe

**Comment by halter73** [comment]
I think we're observing `_state` change before `_error` causing the [TaskCanceledException](https://github.com/dotnet/aspnetcore/blob/0ecf4c1bd9526c36356a0f259d90aafdf0756fcd/src/Servers/Kestrel/Core/src/Internal/Http/HttpRequestPipeReader.cs#L130) to be thrown instead of `_error` which would be the expected `IOException`.

**Comment by halter73** [comment]
@BrennanConroy I think it's probably not related to this either now 😆

**Comment by dougbu** [comment]
This was fixed more than a month ago and has been running at 100% since. Will un-quarantine today.

**Comment by JunTaoLuo** [comment]
This has been unquarantined.
