### ISSUE TITLE
Unit tests error on ubuntu for simple dotnet 5 web api tests application

### ISSUE THREAD

**Issue by SemShekhovtsovIntellias** [dotnet/aspnetcore#33427]
### Describe the bug
When executing unit tests for web API project on ubuntu 20.04 (latest) it throws exception that the solution root could not be located using application root.

If the same published unit tests project run on the windows platform, then all tests pass without any error. It works as expected.

### To Reproduce

Sample project on GitHub: https://github.com/SamShekhovtsov/webapitests
1) Create simple Web API project and Unit Tests project that test the web API.
2) Publish unit tests project to a folder.
3) create a simple docker container using latest ubuntu image and copy publish folder content into container app directory
4) install power shell and dotnet 5 on the ubuntu:latest container 
5) run unit tests using power shell: dotnet test WebAPIProject1.Tests.dll

### Exceptions (if any)

2021-06-08T16:37:11.1642123Z   Failed testname [269 ms]
2021-06-08T16:37:11.1646886Z   Error Message:
2021-06-08T16:37:11.1653209Z    Unable to create instance of class Path.to.class. Error: System.InvalidOperationException: Solution root could not be located using application root long/path/to/publish/..
2021-06-08T16:37:11.1658519Z   Stack Trace:
2021-06-08T16:37:11.1693810Z       at Microsoft.AspNetCore.TestHost.WebHostBuilderExtensions.UseSolutionRelativeContentRoot(IWebHostBuilder builder, String solutionRelativePath, String applicationBasePath, String solutionName)
2021-06-08T16:37:11.1698072Z    at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.SetContentRoot(IWebHostBuilder builder)
2021-06-08T16:37:11.1701361Z    at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.<EnsureServer>b__20_0(IWebHostBuilder webHostBuilder)
2021-06-08T16:37:11.1705047Z    at Microsoft.Extensions.Hosting.GenericHostWebHostBuilderExtensions.ConfigureWebHost(IHostBuilder builder, Action`1 configure, Action`1 configureWebHostBuilder)
2021-06-08T16:37:11.1709799Z    at Microsoft.Extensions.Hosting.GenericHostWebHostBuilderExtensions.ConfigureWebHost(IHostBuilder builder, Action`1 configure)
2021-06-08T16:37:11.1712749Z    at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.EnsureServer()
2021-06-08T16:37:11.1714990Z    at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(DelegatingHandler[] handlers)
2021-06-08T16:37:11.1717851Z    at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(Uri baseAddress, DelegatingHandler[] handlers)
2021-06-08T16:37:11.1720757Z    at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient(WebApplicationFactoryClientOptions options)
2021-06-08T16:37:11.1723155Z    at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient()

### Further technical details
PS /app> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.301
 Commit:    cc8c0abb32

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.301/

Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964

.NET SDKs installed:
  5.0.301 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
PS /app>
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by mkArtakMSFT** [comment]
@javiercn what do you think we should do here?
