### ISSUE TITLE
Feature "Navigation bar" is currently unavailable due to an internal error VS 2019 version 16.10.0

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#33437]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Feature-Navigation-bar-is-currently-un/1442097)._

---
[regression]
System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.Resize()
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.CreateEntry(TKey key,TValue value)
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.Add(TKey key,TValue value)
   at Microsoft.AspNetCore.Razor.Language.Syntax.GreenNode.. ctor(SyntaxKind kind,Int32 fullWidth,RazorDiagnostic[] diagnostics,SyntaxAnnotation[] annotations)
   at Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.MarkupStartTagSyntax.. ctor(SyntaxKind kind,SyntaxToken openAngle,SyntaxToken bang,SyntaxToken name,GreenNode attributes,SyntaxToken forwardSlash,SyntaxToken closeAngle,RazorDiagnostic[] diagnostics,SyntaxAnnotation[] annotations)
   at Microsoft.AspNetCore.Razor.Language.Syntax.InternalSyntax.MarkupStartTagSyntax.SetAnnotations(SyntaxAnnotation[] annotations)
   at Microsoft.AspNetCore.Razor.Language.Legacy.TokenizerBackedParser`1.GetNodeWithSpanContext[TNode](TNode node)
   at Microsoft.AspNetCore.Razor.Language.Legacy.HtmlMarkupParser.ParseStartTag(ParseMode mode,SourceLocation tagStartLocation,String& tagName,MarkupTagMode& tagMode,Boolean& isWellFormed)
   at Microsoft.AspNetCore.Razor.Language.Legacy.HtmlMarkupParser.ParseMarkupElement(SyntaxListBuilder`1& builder,ParseMode mode)
   at Microsoft.AspNetCore.Razor.Language.Legacy.HtmlMarkupParser.ParseMarkupNode(SyntaxListBuilder`1& builder,ParseMode mode)
   at Microsoft.AspNetCore.Razor.Language.Legacy.HtmlMarkupParser.ParseMarkupNodes(SyntaxListBuilder`1& builder,ParseMode mode,Func`2 stopCondition)
   at Microsoft.AspNetCore.Razor.Language.Legacy.HtmlMarkupParser.ParseDocument()
   at Microsoft.AspNetCore.Razor.Language.Legacy.RazorParser.Parse(RazorSourceDocument source)
   at Microsoft.AspNetCore.Razor.Language.RazorSyntaxTree.Parse(RazorSourceDocument source,RazorParserOptions options)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorParsingPhase.ExecuteCore(RazorCodeDocument codeDocument)
   at Microsoft.AspNetCore.Razor.Language.RazorEnginePhaseBase.Execute(RazorCodeDocument codeDocument)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorEngine.Process(RazorCodeDocument document)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorProjectEngine.ProcessCore(RazorCodeDocument codeDocument)
   at Microsoft.AspNetCore.Razor.Language.DefaultRazorProjectEngine.ProcessDesignTime(RazorSourceDocument source,String fileKind,IReadOnlyList`1 importSources,IReadOnlyList`1 tagHelpers)
   at async Microsoft.CodeAnalysis.Razor.ProjectSystem.DocumentState.ComputedStateTracker.GetGeneratedOutputAndVersionCoreAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Razor.ProjectSystem.DefaultDocumentSnapshot.GetGeneratedOutputAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Razor.ProjectSystem.GeneratedDocumentTextLoader.LoadTextAndVersionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.TextLoader.LoadTextAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.RecoverableTextAndVersion.GetValueAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.TextDocumentState.GetTextAndVersionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.TextDocumentState.GetTextAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Serialization.SerializableSourceText.FromTextDocumentStateAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.TextDocumentState.ComputeChecksumsAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   at async Microsoft.CodeAnalysis.TextDocumentState.GetChecksumAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ProjectState.ComputeChecksumsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ProjectState.GetChecksumAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.SolutionState.ComputeChecksumsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.SolutionState.GetChecksumAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.SolutionState.GetChecksumAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.SolutionState.GetChecksumAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.SolutionState.GetChecksumAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Remote.SolutionAssetStorage.StoreAssetsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Remote.SolutionAssetStorage.StoreAssetsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Remote.SolutionAssetStorage.StoreAssetsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.SolutionState.GetChecksumAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.SolutionState.GetChecksumAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Remote.SolutionAssetStorage.StoreAssetsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Remote.SolutionAssetStorage.StoreAssetsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.TryInvokeAsync[TService,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.TryInvokeAsync[TService,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.TryInvokeAsync[TService,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.TryInvokeAsync[TService,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.TryInvokeAsync[TService,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.TryInvokeAsync[TService,TResult](<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.TryInvokeAsync[TService,TResult](<Unknown Parameters>)

---
#### Feedback Bot on 6/6/2021, 10:56 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
