### ISSUE TITLE
I can't show the information from the databases into the Telerik Grid Component

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#33441]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/I-cant-show-the-information-from-the-da/1387095)._

---
**Swagger Ui runs normally, on all endpoints, but the problem lies when runs Blazor project**

global.js?_v=637453952867128601:790 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not found remote action for method: System.Threading.Tasks.Task`1[Volo.Abp.Application.Dtos.PagedResultDto`1[Asn.Tsm.TypeServices.TypeServiceDto]] GetListAsync(Volo.Abp.Application.Dtos.PagedAndSortedResultRequestDto) on the URL: https://localhost:44375
Volo.Abp.AbpException: Could not found remote action for method: System.Threading.Tasks.Task`1[Volo.Abp.Application.Dtos.PagedResultDto`1[Asn.Tsm.TypeServices.TypeServiceDto]] GetListAsync(Volo.Abp.Application.Dtos.PagedAndSortedResultRequestDto) on the URL: https://localhost:44375
   at Volo.Abp.Http.Client.DynamicProxying.ApiDescriptionFinder.FindActionAsync(HttpClient client, String baseUrl, Type serviceType, MethodInfo method)
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1. <MakeRequestAsync>d__42[[Asn.Tsm.TypeServices.ITypeServiceAppService, Asn.Tsm.Application.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]. MoveNext()
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1. <MakeRequestAndGetResultAsync>d__41`1[[Asn.Tsm.TypeServices.ITypeServiceAppService, Asn.Tsm.Application.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Volo.Abp.Application.Dtos.PagedResultDto`1[[Asn.Tsm.TypeServices.TypeServiceDto, Asn.Tsm.Application.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Volo.Abp.Ddd.Application.Contracts, Version=4.2.2.0, Culture=neutral, PublicKeyToken=null]]. MoveNext()
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1. <GetResultAsync>d__40[[Asn.Tsm.TypeServices.ITypeServiceAppService, Asn.Tsm.Application.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]. MoveNext()
   at Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1. <InterceptAsync>d__39[[Asn.Tsm.TypeServices.ITypeServiceAppService, Asn.Tsm.Application.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]. MoveNext()
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1. <InterceptAsync>d__3`1[[Volo.Abp.Http.Client.DynamicProxying.DynamicHttpProxyInterceptor`1[[Asn.Tsm.TypeServices.ITypeServiceAppService, Asn.Tsm.Application.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Volo.Abp.Http.Client, Version=4.2.2.0, Culture=neutral, PublicKeyToken=null],[Volo.Abp.Application.Dtos.PagedResultDto`1[[Asn.Tsm.TypeServices.TypeServiceDto, Asn.Tsm.Application.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Volo.Abp.Ddd.Application.Contracts, Version=4.2.2.0, Culture=neutral, PublicKeyToken=null]]. MoveNext()
   at Castle.DynamicProxy.AsyncInterceptorBase. <ProceedAsynchronous>d__14`1[[Volo.Abp.Application.Dtos.PagedResultDto`1[[Asn.Tsm.TypeServices.TypeServiceDto, Asn.Tsm.Application.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Volo.Abp.Ddd.Application.Contracts, Version=4.2.2.0, Culture=neutral, PublicKeyToken=null]]. MoveNext()
   at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapterWithReturnValue`1. <ProceedAsync>d__7[[Volo.Abp.Application.Dtos.PagedResultDto`1[[Asn.Tsm.TypeServices.TypeServiceDto, Asn.Tsm.Application.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Volo.Abp.Ddd.Application.Contracts, Version=4.2.2.0, Culture=neutral, PublicKeyToken=null]]. MoveNext()
   at Volo.Abp.Validation.ValidationInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
   at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1. <InterceptAsync>d__3`1[[Volo.Abp.Validation.ValidationInterceptor, Volo.Abp.Validation, Version=4.2.2.0, Culture=neutral, PublicKeyToken=null],[Volo.Abp.Application.Dtos.PagedResultDto`1[[Asn.Tsm.TypeServices.TypeServiceDto, Asn.Tsm.Application.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Volo.Abp.Ddd.Application.Contracts, Version=4.2.2.0, Culture=neutral, PublicKeyToken=null]]. MoveNext()
   at Asn.Tsm.Blazor.Pages.Index.OnInitializedAsync() in C:\Users\JFalq\Source\Repos\asn.tsm\src\Asn.Tsm.Blazor\Pages\Index.razor:line 68
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
d.printErr @ global.js?_v=637453952867128601:790

! [image.png] (https://aka.ms/dc/image?name=B321831da57f4482e8413aabb826b3e9d637528246575859549_20210331-165736-image.png&tid=321831da57f4482e8413aabb826b3e9d637528246575859549)

! [Screenshot_1.png] (https://aka.ms/dc/image?name=B389dd107ed8a48508dd52cd4e9bdcb64637528245733283408_Screenshot_1.png&tid=389dd107ed8a48508dd52cd4e9bdcb64637528245733283408)

---
#### Feedback Bot on 4/1/2021, 00:20 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. It is not clear what's the issue here that's related to the framework. If you believe there is a framework issue here, please share more details about what your scenario is, what you expect to work and what isn't working. Also, please provide a minimal repro project so that we can investigate it then.
