### ISSUE TITLE
Test failure in WritingToConnectionAfterUnobservedCloseTriggersRequestAbortedToken

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#33455]
## Error Message

```
System.TimeoutException : The operation has timed out.
```

## Stacktrace

```
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 143
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.WritingToConnectionAfterUnobservedCloseTriggersRequestAbortedToken(ListenOptions listenOptions) in /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs:line 335
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.WritingToConnectionAfterUnobservedCloseTriggersRequestAbortedToken(ListenOptions listenOptions) in /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs:line 340
--- End of stack trace from previous location ---
```

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1173129&view=results

**Comment by BrennanConroy** [comment]
Logs
```
[0.002s] [TestLifetime] [Information] Starting test WritingToConnectionAfterUnobservedCloseTriggersRequestAbortedToken-http_127.0.0.1_0 at 2021-06-05T15:51:43
[0.004s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting starting
[0.007s] [Microsoft.Hosting.Lifetime] [Information] Now listening on: http://127.0.0.1:63028
[0.007s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Debug] Loaded hosting startup assembly Libuv.FunctionalTests
[0.007s] [Microsoft.Hosting.Lifetime] [Information] Application started. Press Ctrl+C to shut down.
[0.007s] [Microsoft.Hosting.Lifetime] [Information] Hosting environment: Production
[0.007s] [Microsoft.Hosting.Lifetime] [Information] Content root path: /private/tmp/helix/working/B4FD096D/w/A251098A/e/
[0.007s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting started
[0.007s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] TestServer is listening on port 63028
[0.008s] [Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv] [Debug] Connection id "0HM98778HJL19" received FIN.
[0.009s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HM98778HJL19" accepted.
[0.009s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HM98778HJL19" started.
[0.010s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HM98778HJL19" disconnecting.
[0.010s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HM98778HJL19" stopped.
[0.010s] [Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv] [Debug] Connection id "0HM98778HJL19" sending FIN because: "The client closed the connection."
[30.107s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting stopping
[30.107s] [Microsoft.Hosting.Lifetime] [Information] Application is shutting down...
[30.108s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting stopped
[30.109s] [Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests] [Error] Test threw an exception.
System.TimeoutException: The operation has timed out.
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 143
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.WritingToConnectionAfterUnobservedCloseTriggersRequestAbortedToken(ListenOptions listenOptions) in /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs:line 335
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.WritingToConnectionAfterUnobservedCloseTriggersRequestAbortedToken(ListenOptions listenOptions) in /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs:line 340
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 273
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 54
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 96
[30.110s] [TestLifetime] [Information] Finished test WritingToConnectionAfterUnobservedCloseTriggersRequestAbortedToken-http_127.0.0.1_0 in 30.107344s
```

**Comment by Tratcher** [comment]
This failure was libuv specific and libuv has been removed by #38005. Ready for unquarantine.
