### ISSUE TITLE
SimpleWithWebApplicationBuilderTests.HelloWorld

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#33494]
## Error Message

```
System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'IServiceProvider'.
```

## Stacktrace

```
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException() in Microsoft.Extensions.DependencyInjection.dll:token 0x600011e+0xa
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope) in Microsoft.Extensions.DependencyInjection.dll:token 0x6000067+0x8
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType) in Microsoft.Extensions.DependencyInjection.dll:token 0x6000062+0x0
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType) in Microsoft.Extensions.DependencyInjection.Abstractions.dll:token 0x6000094+0x34
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider) in Microsoft.Extensions.DependencyInjection.Abstractions.dll:token 0x6000095+0xe
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.ConfigureHostBuilder(IHostBuilder hostBuilder) in /_/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs:line 202
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.EnsureServer() in /_/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs:line 172
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(DelegatingHandler[] handlers) in /_/src/Mvc/Mvc.Testing/src/WebApplicationFactory.cs:line 462
   at Microsoft.AspNetCore.Mvc.FunctionalTests.SimpleWithWebApplicationBuilderTests..ctor(MvcTestFixture`1 fixture) in /_/src/Mvc/test/Mvc.FunctionalTests/SimpleWithWebApplicationBuilderTests.cs:line 16
```

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1183988&view=ms.vss-test-web.build-test-results-tab&runId=35603264&resultId=118571&paneView=debug

@davidfowl I'm concerned this happened on the first official build with your changes to WebApplicationFactory https://github.com/dotnet/aspnetcore/pull/33462/.

**Comment by davidfowl** [comment]
Oh snap! Very nice

**Comment by davidfowl** [comment]
OK so psychic debugging tells me a couple of things:
- OSX only? Weird
- I would expect this to happen everytime if it was a problem not sometimes. It looks like it keeps failing on OSX.
- StartAsync triggered the IHostApplicationLifetime since StartAsync completed.
- WaitForShutdownAsync might be throwing and causing it to finish early, causing it to be disposed.

**Comment by davidfowl** [comment]
I know why this happens. These tests run in parallel and this event is global. I'll need some time to re-think this a little 😄

**Comment by davidfowl** [comment]
OK https://github.com/dotnet/runtime/pull/54090 should resolve this.

**Comment by davidfowl** [comment]
Waiting until that change propagates

**Comment by davidfowl** [comment]
Should be fixed by https://github.com/dotnet/aspnetcore/pull/33479
