### ISSUE TITLE
Selenium ERR_ADDRESS_IN_USE

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#33526]
## Error Message

OpenQA.Selenium.WebDriverException : unknown error: net::ERR_ADDRESS_IN_USE\n  (Session info: headless chrome=91.0.4472.101)

## Stacktrace
```
 at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse) in WebDriver.dll:token 0x600053b+0x12e
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters) in WebDriver.dll:token 0x6000535+0x4a
   at OpenQA.Selenium.Remote.RemoteWebDriver.set_Url(String value) in WebDriver.dll:token 0x60004fb+0x2d
   at OpenQA.Selenium.Remote.RemoteNavigator.GoToUrl(Uri url) in WebDriver.dll:token 0x60004c4+0x29
   at Microsoft.AspNetCore.Components.E2ETest.BasicTestAppAuthenticationWebDriverExtensions.SignInAs(IWebDriver browser, Uri baseUri, String usernameOrNull, String rolesOrNull, Boolean useSeparateTab) in /_/src/Components/test/E2ETest/Infrastructure/WebDriverExtensions/BasicTestAppAuthenticationWebDriverExtensions.cs:line 33
   at Microsoft.AspNetCore.Components.E2ETest.Tests.AuthTest.SignInAs(String userName, String roles, Boolean useSeparateTab) in /_/src/Components/test/E2ETest/Tests/AuthTest.cs:line 239
   at Microsoft.AspNetCore.Components.E2ETest.Tests.AuthTest.AuthorizeViewCases_RequirePolicy_Authorized() in /_/src/Components/test/E2ETest/Tests/AuthTest.cs:line 127
```
## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1185035&view=ms.vss-test-web.build-test-results-tab&runId=35625478&resultId=100415&paneView=debug

I'm not quarantining this specific test since this seems to be an infrastructure issue.

**Comment by SteveSandersonMS** [comment]
Closing because since all the work to make E2E tests more reliable, they are now extremely reliable (100% pass rate as far back as the stats go, and yes [they are still able to report failures](https://github.com/dotnet/aspnetcore/pull/38115)).
