### ISSUE TITLE
Blazor: FieldIdentifier only supports simple member accessors (fields, properties) of an object.

### ISSUE THREAD

**Issue by fireloudapp** [dotnet/aspnetcore#33546]
Framework .NET 5.0
Web Applicaiton: Blazor Client Project using WebAsm.

When I run the application using Debug mode it woks without any error. But after hosting the same in  IIS (either in release/debug mode) Issue occurred.
I have used IIS 10.0 version.

**Code snapshot:**
```
<EditForm Model="@_model" OnValidSubmit="OnValidSubmit">
            <DataAnnotationsValidator />
            <MudGrid>
                <MudItem xs="12" sm="12" md="12">
                    <MudDivider />
                </MudItem>
                <MudItem xs="4" sm="4" md="4">
                    <MudTextField T="string" Label="Short Name" 
                                  @attributes="_modelInputValidation.ShotNameValidation"
                                  @bind-Value="@_model.ShortName" 
                                  For="@(() => _model.ShortName)" 
                                  Immediate="true" 
                                   />
                </MudItem>
                
                <MudItem xs="6" sm="6" md="6">
                    <MudTextField T="string" Label="Full Name" @bind-Value="@_model.FullName"
                                  @attributes="_modelInputValidation.FullNameValidation"
                                  For="@(() => _model.FullName)"  Immediate="true" />
                </MudItem>
                
                <MudItem xs="12" sm="12" md="12" Class="d-flex flex-row-reverse py-2 px-1">
                    <MudButton ButtonType="ButtonType.Submit" Variant="Variant.Filled" Color="Color.Primary">Save</MudButton>
                </MudItem>

            </MudGrid>

        </EditForm>
```

**Error Details:**

crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The provided expression contains a PropertyExpression which is not supported. FieldIdentifier only supports simple member accessors (fields, properties) of an object.
System.ArgumentException: The provided expression contains a PropertyExpression which is not supported. FieldIdentifier only supports simple member accessors (fields, properties) of an object.
   at Microsoft.AspNetCore.Components.Forms.FieldIdentifier.ParseAccessor[String](Expression`1 accessor, Object& model, String& fieldName)
   at Microsoft.AspNetCore.Components.Forms.FieldIdentifier.Create[String](Expression`1 accessor)
   at MudBlazor.MudFormComponent`2[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnParametersSet()
   at MudBlazor.MudBaseInput`1[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnParametersSet()
   at MudBlazor.MudDebouncedInput`1[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnParametersSet()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at MudBlazor.MudBaseInput`1.<SetParametersAsync>d__146[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We will need to have a minimalistic repro app, which doesn't involve any third party components and is based off of a new project template + minimal set of changes to reproduce the behavior. Please provide it so that we can investigate this.
