### ISSUE TITLE
With .NET 6.0 installed, publish .NET Framework 2.1 fails to error "HTTP Error 502.5 - Process Failure".

### ISSUE THREAD

**Issue by v-elenafeng** [dotnet/aspnetcore#33635]
**Testcases Affected**
Publish ASP.NET Core 2.1 (.NET Framework)

**Repro Steps**
1. With .NET 6.0 Preview 6 installed, open VS and sign in with account
2. File > New project > ASP.NET Core Empty > .NET Core 2.1 > Check "Run on .NET Framework"
3. Right-click on the project > Publish to App service (Windows)

It shows "HTTP Error 502.5 - Process Failure" on the published website.

**Actual Result**
![image](https://user-images.githubusercontent.com/78580199/122534458-1d75f780-d055-11eb-8f51-1496a0b890a0.png)

**Comment by BrennanConroy** [comment]
Can you please take a look at the docs (which should be linked from the error page you posted) and see if you can get diagnostics for the issue.
https://docs.microsoft.com/aspnet/core/test/troubleshoot-azure-iis?view=aspnetcore-5.0#5025-process-failure

**Comment by v-elenafeng** [comment]
I will try to get the diagnostics next week, thanks!

**Comment by v-elenafeng** [comment]
I cannot get the information from the Application Event Log and the ASP.NET Core Module stdout log.
The versions of the ASP.NET Core shared framework: 
![image](https://user-images.githubusercontent.com/78580199/123622973-815fa380-d83f-11eb-83c7-4710217b13eb.png)
Could you provide me with more guidance？

**Comment by mkArtakMSFT** [comment]
@BrennanConroy I assume this is not a blocker for preview6?

**Comment by BrennanConroy** [comment]
> I cannot get the information from the Application Event Log and the ASP.NET Core Module stdout log.

Can you clarify? Why can't you get the info?

**Comment by v-elenafeng** [comment]
Application Event Log

Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at Microsoft.Extensions.Logging.Console.ConsoleLogger..ctor(System.String, System.Func`3&lt;System.String,Microsoft.Extensions.Logging.LogLevel,Boolean&gt;, Microsoft.Extensions.Logging.IExternalScopeProvider, Microsoft.Extensions.Logging.Console.Internal.ConsoleLoggerProcessor)
   at Microsoft.Extensions.Logging.Console.ConsoleLoggerProvider.CreateLoggerImplementation(System.String)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetOrAdd(System.__Canon, System.Func`2&lt;System.__Canon,System.__Canon&gt;)
   at Microsoft.Extensions.Logging.LoggerFactory.CreateLoggers(System.String)
   at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(System.String)
   at Microsoft.Extensions.Logging.Logger`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(Microsoft.Extensions.Logging.ILoggerFactory)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine+&lt;&gt;c__DisplayClass1_0.&lt;RealizeService&gt;b__0(Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(System.IServiceProvider, System.Type)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.IServiceProvider)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at WebApplication4.Program.Main(System.String[])

</Data>
        </EventData>
    </Event>
    <Event>
        <System>
            <Provider Name="IIS AspNetCore Module"/>
            <EventID>1000</EventID>
            <Level>1</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2021-06-30T02:45:42Z"/>
            <EventRecordID>553661843</EventRecordID>
            <Channel>Application</Channel>
            <Computer>RD0003FF2AD9DD</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>Application 'MACHINE/WEBROOT/APPHOST/WEBAPPLICATION420210629194332' with physical root 'D:\home\site\wwwroot\' failed to start process with commandline 'D:\home\site\wwwroot\WebApplication4.exe ', ErrorCode = '0x80004005' : e0434352.</Data>
        </EventData>
    </Event>
    <Event>
        <System>
            <Provider Name=".NET Runtime"/>
            <EventID>1026</EventID>
            <Level>1</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2021-06-30T02:45:45Z"/>
            <EventRecordID>553665015</EventRecordID>
            <Channel>Application</Channel>
            <Computer>RD0003FF2AD9DD</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>Application: WebApplication4.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException

Exception Info: System.IO.FileNotFoundException
   at Microsoft.Extensions.Logging.Console.ConsoleLogger..ctor(System.String, System.Func`3&lt;System.String,Microsoft.Extensions.Logging.LogLevel,Boolean&gt;, Microsoft.Extensions.Logging.IExternalScopeProvider, Microsoft.Extensions.Logging.Console.Internal.ConsoleLoggerProcessor)
   at Microsoft.Extensions.Logging.Console.ConsoleLoggerProvider.CreateLoggerImplementation(System.String)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetOrAdd(System.__Canon, System.Func`2&lt;System.__Canon,System.__Canon&gt;)
   at Microsoft.Extensions.Logging.LoggerFactory.CreateLoggers(System.String)
   at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(System.String)
   at Microsoft.Extensions.Logging.Logger`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(Microsoft.Extensions.Logging.ILoggerFactory)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine+&lt;&gt;c__DisplayClass1_0.&lt;RealizeService&gt;b__0(Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(System.IServiceProvider, System.Type)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.IServiceProvider)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at WebApplication4.Program.Main(System.String[])

</Data>
        </EventData>
    </Event>
    <Event>
        <System>
            <Provider Name="IIS AspNetCore Module"/>
            <EventID>1000</EventID>
            <Level>1</Level>
            <Task>0</Task>
            <Keywords>Keywords</Keywords>
            <TimeCreated SystemTime="2021-06-30T02:45:45Z"/>
            <EventRecordID>553665171</EventRecordID>
            <Channel>Application</Channel>
            <Computer>RD0003FF2AD9DD</Computer>
            <Security/>
        </System>
        <EventData>
            <Data>Application 'MACHINE/WEBROOT/APPHOST/WEBAPPLICATION420210629194332' with physical root 'D:\home\site\wwwroot\' failed to start process with commandline 'D:\home\site\wwwroot\WebApplication4.exe ', ErrorCode = '0x80004005' : e0434352.</Data>
        </EventData>
    </Event>
</Events>
