### ISSUE TITLE
AuthTest.AuthorizeViewCases_RequirePolicy_Authorized()

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#33657]
## Error Message

``` text
OpenQA.Selenium.WebDriverException : unknown error: net::ERR_ADDRESS_IN_USE\n  (Session info: headless chrome=91.0.4472.101)
```
then with a newer Chrome
``` text
OpenQA.Selenium.WebDriverException : unknown error: net::ERR_ADDRESS_IN_USE\n  (Session info: headless chrome=91.0.4472.106)
```

## Stacktrace

``` text
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse) in WebDriver.dll:token 0x600053b+0x12e
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters) in WebDriver.dll:token 0x6000535+0x4a
   at OpenQA.Selenium.Remote.RemoteWebDriver.set_Url(String value) in WebDriver.dll:token 0x60004fb+0x2d
   at OpenQA.Selenium.Remote.RemoteNavigator.GoToUrl(Uri url) in WebDriver.dll:token 0x60004c4+0x29
   at Microsoft.AspNetCore.Components.E2ETest.BasicTestAppAuthenticationWebDriverExtensions.SignInAs(IWebDriver browser, Uri baseUri, String usernameOrNull, String rolesOrNull, Boolean useSeparateTab) in /_/src/Components/test/E2ETest/Infrastructure/WebDriverExtensions/BasicTestAppAuthenticationWebDriverExtensions.cs:line 33
   at Microsoft.AspNetCore.Components.E2ETest.Tests.AuthTest.SignInAs(String userName, String roles, Boolean useSeparateTab) in /_/src/Components/test/E2ETest/Tests/AuthTest.cs:line 239
   at Microsoft.AspNetCore.Components.E2ETest.Tests.AuthTest.AuthorizeViewCases_RequirePolicy_Authorized() in /_/src/Components/test/E2ETest/Tests/AuthTest.cs:line 127
```

## Build

Test failed in aspnetcore-ci builds of our main branch:
- https://dev.azure.com/dnceng/public/_build/results?buildId=1185035&view=results
- https://dev.azure.com/dnceng/public/_build/results?buildId=1189302&view=results

Both failures were in our Windows non-Helix test jobs.

**Comment by javiercn** [comment]
@dougbu thanks for bringing this up.

This seems like some Selenium related instability.

**Comment by pranavkm** [comment]
@BrennanConroy our suspicion is that this might be related to the most recent Selenium update. Could you try reverting the most recent update to see if it fixes the issue? Thanks!

https://github.com/dotnet/aspnetcore/commit/dfe8bd2b1ab1a8583b8a94f7858e2c129f3356f9#diff-1ea18ff65faa2ae6fed570b83747086d0317f5e4bc325064f6c14319a9c4ff67

**Comment by BrennanConroy** [comment]
You realize there is no difference between those two versions right?
https://github.com/jsakamoto/nupkg-selenium-webdriver-chromedriver/compare/v.91.0.4472.1900...v.91.0.4472.1900-beta

**Comment by dougbu** [comment]
Look instead at the analytics of the pipeline where the test _does_ run. Suggest also putting up a PR to mention the components pipeline as part of the 30 day confirmation. https://dev.azure.com/dnceng/public/_build/results?buildId=1432637&view=ms.vss-test-web.build-test-results-tab&runId=41386142&resultId=100725&paneView=history shows this tests has been fairly successful but I didn't check a full 30 days worth.
