### ISSUE TITLE
trying to configure nginx in front of asp.net core which isn't directly related.

### ISSUE THREAD

**Issue by EvgenyPrikhodko** [dotnet/aspnetcore#33679]
_Originally posted by @davidfowl in https://github.com/dotnet/aspnetcore/issues/32328#issuecomment-835622121_

Hi
There is nginx there are 2 servers there is an asp core there is a Validation token
How to properly configure 2 hosts so that requests between them go through correctly?

**Comment by BrennanConroy** [comment]
Here are the docs for nginx
https://docs.microsoft.com/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-5.0#configure-nginx

**Comment by EvgenyPrikhodko** [comment]
![image](https://user-images.githubusercontent.com/25795145/122825520-b8d3ca80-d2ea-11eb-91bf-8152e96a4c4d.png)


probably I'm not asking the right question.
For example, there is a solution for the hub it is a redis

**Comment by BrennanConroy** [comment]
That sounds like you have questions about how to setup nginx in front of multiple servers, this isn't a .NET specific issue, I recommend asking on stackoverflow or nginx forums.

**Comment by EvgenyPrikhodko** [comment]
Not. I know how to configure nginx.
The question is how hosts will exchange information, for example JWT, AntiForgeryToken, etc.

**Comment by EvgenyPrikhodko** [comment]
UP 

for example. host 1 is accepting connections. the load balancer has passed traffic to host 2.

```
 An exception was thrown while deserializing the token. (348bf365)
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
 ---> System.Security.Cryptography.CryptographicException: The key {ef991836-017b-496b-a2fc-469f2e666716} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)

```

**Comment by BrennanConroy** [comment]
Take a look at the docs for using keys that all apps can share
https://docs.microsoft.com/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-5.0
