### ISSUE TITLE
CanRenderComponentDynamically test failure

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#33733]
## Error Message

```
OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 2
Actual:   3\r\n 
```

<details>

```
OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 2
Actual:   3
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer1 comparer) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\EqualityAsserts.cs:line 40
 at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 83
 at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_01.<WaitAssertCore>b__0(IWebDriver ) in //src/Shared/E2ETesting/WaitAssert.cs:line 109
Screen shot captured at 'D:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.AspNetCore.Components.E2ETests\3106d8d7df3f477c932f638a8dee731a.png'
Encountered browser errors
[2021-06-21T23:08:10Z] [Info] http://127.0.0.1:31320/subdir/_framework/blazor.server.js 0:32150 "[2021-06-21T23:08:10.600Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:31320/subdir/_blazor'."
[2021-06-21T23:08:10Z] [Info] http://127.0.0.1:31320/subdir 45:16 "Blazor server-side"
[2021-06-21T23:08:10Z] [Info] http://127.0.0.1:31320/subdir/_framework/blazor.server.js 0:32150 "[2021-06-21T23:08:10.718Z] Information: WebSocket connected to ws://127.0.0.1:31320/subdir/_blazor?id=C1MrsfBjkarOfN4qQuXk6A."Page content:
<head>
    <meta charset="utf-8">
    <title>Basic test app</title>
    <base href="/subdir/">
    <link href="style.css" rel="stylesheet">
    <link rel="icon" href="data:,">

    
    <link href="_content/TestContentPackage/styles.css" rel="stylesheet">
    <link href="Components.TestServer.styles.css" rel="stylesheet">
</head>
<body>
    <root><div id="test-selector">
    Select test:
    <select id="test-selector-select"><option value="none">Choose...
        <option value="BasicTestApp.AfterRenderInteropComponent">After-render interop component
        <option value="BasicTestApp.AuthTest.AuthRouter">Auth cases
        <option value="BasicTestApp.BindCasesComponent">bind cases
        <option value="BasicTestApp.ComponentRefComponent">Component ref component
        <option value="BasicTestApp.ConfigurationComponent">Configuration
        <option value="BasicTestApp.CounterComponent">Counter
        <option value="BasicTestApp.CounterComponentWrapper">Counter wrapped in parent
        <option value="BasicTestApp.DataDashComponent">data-* attribute render
```

</details>

## Stacktrace

```
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 129
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore(IWebDriver driver, Action assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 83
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.Equal[T](IWebDriver driver, T expected, Func`1 actual) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 27
   at Microsoft.AspNetCore.Components.E2ETest.Tests.DynamicComponentRenderingTest.CanRenderComponentDynamically() in /_/src/Components/test/E2ETest/Tests/DynamicComponentRenderingTest.cs:line 43
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 83
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 109
```

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1198242&view=ms.vss-test-web.build-test-results-tab&runMicrosoft.AspNetCore.Components.E2ETest.ServerExecutionTests.ServerDynamicComponentRenderingTest.CanRenderComponentDynamicallyId=35918552&resultId=100224&paneView=debug

**Comment by SteveSandersonMS** [comment]
Closing because since all the work to make E2E tests more reliable, they are now extremely reliable (100% pass rate as far back as the stats go, and yes [they are still able to report failures](https://github.com/dotnet/aspnetcore/pull/38115)).

I verified that this specific test is running and part of that pass rate.
