### ISSUE TITLE
Test failure: Http3StreamTests.ContentLength_Received_NoDataFrames_Reset 

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#33760]
## Error Message

```
Assert.Equal() Failure
Expected: ProtocolError
Actual:   0
```

## Logs

```
[0.001s] [TestLifetime] [Information] Starting test ContentLength_Received_NoDataFrames_Reset at 2021-06-22T02:12:25
[0.015s] [Microsoft.AspNetCore.Server.Kestrel.Http3] [Verbose] Connection id "null" sending HEADERS frame for stream ID 8 with length 56.
[0.015s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "null", Request id "null": started reading request body.
[0.015s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "null", Request id "null": done reading request body.
[0.016s] [Microsoft.AspNetCore.Server.Kestrel] [Information] Connection id "null", Request id "null": the application completed without reading the entire request body.
[0.016s] [Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http3StreamTests] [Verbose] Input is completed
[0.018s] [Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http3StreamTests] [Error] Test threw an exception.
Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: ProtocolError
Actual:   0
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\EqualityAsserts.cs:line 40
   at Xunit.Assert.Equal[T](T expected, T actual) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\EqualityAsserts.cs:line 24
   at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http3TestBase.Http3StreamBase.WaitForStreamErrorAsync(Http3ErrorCode protocolError, String expectedErrorMessage) in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http3/Http3TestBase.cs:line 544
   at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http3StreamTests.ContentLength_Received_NoDataFrames_Reset() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http3/Http3StreamTests.cs:line 657
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 273
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 54
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 96
[0.018s] [TestLifetime] [Information] Finished test ContentLength_Received_NoDataFrames_Reset in 0.0178951s

```

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1198547&view=ms.vss-test-web.build-test-results-tab&runId=35924052&resultId=107477&paneView=debug

**Comment by BrennanConroy** [comment]
Keep test failure issues open and apply the test-fixed label to them.
