### ISSUE TITLE
Blazor RemoteRender issue

### ISSUE THREAD

**Issue by thavasnippets** [dotnet/aspnetcore#33892]
Source code:[https://github.com/thavasnippets/SPA/tree/main/Blazor/Shopping-cart](https://github.com/thavasnippets/SPA/tree/main/Blazor/Shopping-cart)

State management issue

warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state.
      System.InvalidOperationException: The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution 
to the Dispatcher when triggering rendering or component state.
         at Microsoft.AspNetCore.Components.Dispatcher.AssertAccess()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)      
         at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
         at Shopping_cart.State.CartState.NotifyStateChanged() in C:\Thava\Blazor\Shopping-cart\State\CartState.cs:line 21
         at Shopping_cart.State.CartState.SetCart(Boolean state) in C:\Thava\Blazor\Shopping-cart\State\CartState.cs:line 15
         at Shopping_cart.ProductItem.HandleAddToCart() in C:\Thava\Blazor\Shopping-cart\Pages\Components\shopping-cart\product-list\product-item\ProductItem.razor:line 53
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'rdLhrHujNzHQ1fpF8OiRXL9EAkmclKhc6wkDEDxCn3M'.
      System.InvalidOperationException: The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution 
to the Dispatcher when triggering rendering or component state.
         at Microsoft.AspNetCore.Components.Dispatcher.AssertAccess()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)      
         at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
         at Shopping_cart.State.CartState.NotifyStateChanged() in C:\Thava\Blazor\Shopping-cart\State\CartState.cs:line 21
         at Shopping_cart.State.CartState.SetCart(Boolean state) in C:\Thava\Blazor\Shopping-cart\State\CartState.cs:line 15
         at Shopping_cart.ProductItem.HandleAddToCart() in C:\Thava\Blazor\Shopping-cart\Pages\Components\shopping-cart\product-list\product-item\ProductItem.razor:line 53
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
Shoppingcart Component

**Comment by javiercn** [comment]
@thavasnippets thanks for contacting us.

Can you clarify what issue you are running into? The current exception seems correct and by design, and points out to an issue your app where you are trying to call `StateHasChanged` outside of the Blazor synchronization context, and the exception is telling you that you can't do that.

Likely on ProductItem:53 you need to do InvokeAsync(() => { /* Your code StateHasChanged(); */}) to update the component state
