### ISSUE TITLE
Renaming a class crashes the editor

### ISSUE THREAD

**Issue by mayur-ekbote** [dotnet/aspnetcore#33914]
Sometimes when a class is renamed through intellisense, the editor crashes. Following is the stack trace (VS Community 16.10.2):

System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
Parameter name: lineNumber
   at Microsoft.VisualStudio.Text.Implementation.UnaryStringRebuilder.GetLineFromLineNumber(Int32 lineNumber,Span& extent,Int32& lineBreakLength)
   at Microsoft.VisualStudio.Text.Implementation.CachingTextImage.GetLineFromLineNumber(Int32 lineNumber)
   at Microsoft.CodeAnalysis.Text.Extensions.SnapshotSourceText.LineInfo.get_Item(Int32 index)
   at Microsoft.VisualStudio.LanguageServerClient.Razor.VSLSPRangeExtensions.AsTextSpan(Range range,SourceText sourceText)
   at async Microsoft.VisualStudio.LanguageServerClient.Razor.CSharpSpanMappingService.MapSpansAsync(<Unknown Parameters>)
   at async Microsoft.VisualStudio.LanguageServerClient.Razor.CSharpSpanMappingService.MapSpansAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.ExternalAccess.Razor.RazorSpanMappingServiceWrapper.MapSpansAsync(<Unknown Parameters>)
   at async Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.<ApplyMappedFileChanges>g__GetMappedTextChanges|82_1(<Unknown Parameters>)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyMappedFileChanges(SolutionChanges solutionChanges)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.TryApplyChanges(Solution newSolution,IProgressTracker progressTracker)
   at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.UpdateWorkspaceForGlobalIdentifierRename(Workspace workspace,Solution newSolution,String undoName,IEnumerable`1 changedDocuments,ISymbol symbol,String newName,Int32 trackingSessionId)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.ApplyChangesToWorkspace(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCommitter.Commit(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.RenameTracking.RenameTrackingTaggerProvider.RenameTrackingCodeAction.RenameTrackingCommitterOperation.Apply(Workspace workspace,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.CodeActionOperation.TryApply(Workspace workspace,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.ProcessOperations(Workspace workspace,ImmutableArray`1 operations,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.CodeActions.CodeActionEditHandlerService.Apply(Workspace workspace,Document fromDocument,ImmutableArray`1 operations,String title,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass22_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by allisonchou** [comment]
This should be addressed by https://github.com/dotnet/aspnetcore-tooling/pull/3594.
@mayur-ekbote If you're still seeing this in the latest VS 2022 preview version, please let us know and we will re-open the issue. Thanks!
