### ISSUE TITLE
The dotnetsdk container dev-certs appear broken, (5.0-windowsservercore-ltsc2019)

### ISSUE THREAD

**Issue by erinlah-ms** [dotnet/aspnetcore#33972]
The dev-certs in the "mcr.microsoft.com/dotnet/sdk:5.0-windowsservercore-ltsc2019" container image appear to be "damaged" in the sense that 

1. unit test that rely on that dev cert fail
2. `dotnet dev-certs https --clean` doesn't actually remove the damaged cert

### Steps to Reproduce

Both repros were tests with container `mcr.microsoft.com/dotnet/sdk:5.0-windowsservercore-ltsc2019` with image id `f0899d235b9c`

Repro steps (1) unable to remove damaged cert:

```
aaronla@aaronla-x:dev1$ docker run --mount type=bind,source=d:\repos,target=c:\repos --name inst-dev-2 -it mcr.microsoft.com/dotnet/sdk:5.0-windowsservercore-ltsc2019
Microsoft Windows [Version 10.0.17763.1935]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\>powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\> dir Cert:\CurrentUser\My\ | fl


Subject      : CN=localhost
Issuer       : CN=localhost
Thumbprint   : 8249B46C6BC1C7CE30BF7A51DC0DB8C1E6C5BDB2
FriendlyName : ASP.NET Core HTTPS development certificate
NotBefore    : 5/25/2021 8:38:32 AM
NotAfter     : 5/25/2022 8:38:32 AM
Extensions   : {System.Security.Cryptography.Oid, System.Security.Cryptography.Oid, System.Security.Cryptography.Oid,
               System.Security.Cryptography.Oid...}



PS C:\> dotnet dev-certs https --clean
Cleaning HTTPS development certificates from the machine. A prompt might get displayed to confirm the removal of some of the
 certificates.
HTTPS development certificates successfully removed from the machine.
PS C:\> dir Cert:\CurrentUser\My\ | fl


Subject      : CN=localhost
Issuer       : CN=localhost
Thumbprint   : 8249B46C6BC1C7CE30BF7A51DC0DB8C1E6C5BDB2
FriendlyName : ASP.NET Core HTTPS development certificate
NotBefore    : 5/25/2021 8:38:32 AM
NotAfter     : 5/25/2022 8:38:32 AM
Extensions   : {System.Security.Cryptography.Oid, System.Security.Cryptography.Oid, System.Security.Cryptography.Oid,
               System.Security.Cryptography.Oid...}
```

[expected]
Cert removed by the --clean step.

[actual]
As seen above, cert still present.

Repro steps (2) tests failing due to bad cert:

(reference repo, MSFT FTE only: https://msazure.visualstudio.com/One/_git/PowerApps-CoreServicesGateway?path=%2F&version=GBdev%2Faaronla%2Fnew-image&_a=contents )
```
C:\repos\PowerApps-CoreServicesGateway\test\PPApiGatewayApp\PPApiGateway.Tests>dotnet test --no-build --filter IntegrationTe
sts.HealthApi_ShouldReturn200
Test run for C:\repos\PowerApps-CoreServicesGateway\out\testbin\Debug-x64\Microsoft.PowerPlatform.CoreServices.PPApiGateway.
Tests\Microsoft.PowerPlatform.CoreServices.PPApiGateway.Tests.dll (.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.10.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:01.40]     Microsoft.PowerPlatform.CoreServices.PPApiGateway.Tests.IntegrationTests.HealthApi_ShouldReturn2
00 [FAIL]
  Failed Microsoft.PowerPlatform.CoreServices.PPApiGateway.Tests.IntegrationTests.HealthApi_ShouldReturn200 [156 ms]
  Error Message:
   System.InvalidOperationException : Unable to configure HTTPS endpoint. No server certificate was specified, and the defau
lt developer certificate could not be found or is out of date.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dot
net dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
  Stack Trace:
     at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOp
tions)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context
)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelSe
rverOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, Cancellati
onToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.Start()
   at Microsoft.PowerPlatform.CoreServices.PPApiGateway.Tests.IntegrationTests.TestSetup.RunTestEchoServiceServer() in C:\re
pos\PowerApps-CoreServicesGateway\test\PPApiGatewayApp\PPApiGateway.Tests\IntegrationTests.cs:line 182
   at Microsoft.PowerPlatform.CoreServices.PPApiGateway.Tests.IntegrationTests.TestSetup.Run(String host, Func`2 func) in C:
\repos\PowerApps-CoreServicesGateway\test\PPApiGatewayApp\PPApiGateway.Tests\IntegrationTests.cs:line 165
   at Microsoft.PowerPlatform.CoreServices.PPApiGateway.Tests.IntegrationTests.HealthApi_ShouldReturn200() in C:\repos\Power
Apps-CoreServicesGateway\test\PPApiGatewayApp\PPApiGateway.Tests\IntegrationTests.cs:line 40
--- End of stack trace from previous location where exception was thrown ---

Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: < 1 ms - Microsoft.PowerPlatform.CoreServic
es.PPApiGateway.Tests.dll (netcoreapp3.1)

C:\repos\PowerApps-CoreServicesGateway\test\PPApiGatewayApp\PPApiGateway.Tests>dotnet dev-certs https
The HTTPS developer certificate was generated successfully.

C:\repos\PowerApps-CoreServicesGateway\test\PPApiGatewayApp\PPApiGateway.Tests>dotnet test --no-build --filter IntegrationTe
sts.HealthApi_ShouldReturn200
Test run for C:\repos\PowerApps-CoreServicesGateway\out\testbin\Debug-x64\Microsoft.PowerPlatform.CoreServices.PPApiGateway.
Tests\Microsoft.PowerPlatform.CoreServices.PPApiGateway.Tests.dll (.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.10.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:01.40]     Microsoft.PowerPlatform.CoreServices.PPApiGateway.Tests.IntegrationTests.HealthApi_ShouldReturn2
00 [FAIL]
  Failed Microsoft.PowerPlatform.CoreServices.PPApiGateway.Tests.IntegrationTests.HealthApi_ShouldReturn200 [160 ms]
  Error Message:
   System.InvalidOperationException : Unable to configure HTTPS endpoint. No server certificate was specified, and the defau
lt developer certificate could not be found or is out of date.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dot
net dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
  Stack Trace:
     at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOp
tions)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context
)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelSe
rverOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, Cancellati
onToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.Start()
   at Microsoft.PowerPlatform.CoreServices.PPApiGateway.Tests.IntegrationTests.TestSetup.RunTestEchoServiceServer() in C:\re
pos\PowerApps-CoreServicesGateway\test\PPApiGatewayApp\PPApiGateway.Tests\IntegrationTests.cs:line 182
   at Microsoft.PowerPlatform.CoreServices.PPApiGateway.Tests.IntegrationTests.TestSetup.Run(String host, Func`2 func) in C:
\repos\PowerApps-CoreServicesGateway\test\PPApiGatewayApp\PPApiGateway.Tests\IntegrationTests.cs:line 165
   at Microsoft.PowerPlatform.CoreServices.PPApiGateway.Tests.IntegrationTests.HealthApi_ShouldReturn200() in C:\repos\Power
Apps-CoreServicesGateway\test\PPApiGatewayApp\PPApiGateway.Tests\IntegrationTests.cs:line 40
--- End of stack trace from previous location where exception was thrown ---

Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: < 1 ms - Microsoft.PowerPlatform.CoreServic
es.PPApiGateway.Tests.dll (netcoreapp3.1)

C:\repos\PowerApps-CoreServicesGateway\test\PPApiGatewayApp\PPApiGateway.Tests>powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\repos\PowerApps-CoreServicesGateway\test\PPApiGatewayApp\PPApiGateway.Tests> ls Cert:\CurrentUser\My\


   PSParentPath: Microsoft.PowerShell.Security\Certificate::CurrentUser\My

Thumbprint                                Subject
----------                                -------
CFCFF10B7247EAF1993909FD73E893939AD4E8F5  CN=localhost
8249B46C6BC1C7CE30BF7A51DC0DB8C1E6C5BDB2  CN=localhost


PS C:\repos\PowerApps-CoreServicesGateway\test\PPApiGatewayApp\PPApiGateway.Tests> rm Cert:\CurrentUser\My\8249B46C6BC1C7CE3
0BF7A51DC0DB8C1E6C5BDB2
PS C:\repos\PowerApps-CoreServicesGateway\test\PPApiGatewayApp\PPApiGateway.Tests> exit

C:\repos\PowerApps-CoreServicesGateway\test\PPApiGatewayApp\PPApiGateway.Tests>dotnet test --no-build --filter IntegrationTe
sts.HealthApi_ShouldReturn200
Test run for C:\repos\PowerApps-CoreServicesGateway\out\testbin\Debug-x64\Microsoft.PowerPlatform.CoreServices.PPApiGateway.
Tests\Microsoft.PowerPlatform.CoreServices.PPApiGateway.Tests.dll (.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 16.10.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: < 1 ms - Microsoft.PowerPlatform.CoreServic
es.PPApiGateway.Tests.dll (netcoreapp3.1)
```

[expected]
test passes first time, using the preconfigured dev-certs

[actual]
test fails until the preconfigured dev-cert is removed, and a new (functioning) cert added.

NOTE: the test in question is on netcoreapp3.1, built using net50 sdk.

### Output of `docker version`

```
$ docker --version
Docker version 20.10.6, build 370c289
```

### Output of `docker info`

```
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 21
 Server Version: 20.10.6
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 19043 (19041.1.amd64fre.vb_release.191206-1406)
 Operating System: Windows 10 Pro Version 2009 (OS Build 19043.985)
 OSType: windows
 Architecture: x86_64
 CPUs: 6
 Total Memory: 31.92GiB
 Name: aaronla-xyz
 ID: UGKB:MTXE:D2VT:7P5E:5SDX:5S26:ET6R:NC65:JSXP:XHFS:3BGB:QTO2
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by javiercn** [comment]
@mthalman I haven't looked at it in quite a while, but we essentially emit ETW logs, so you should be able to collect a trace with `dotnet trace`

**Comment by javiercn** [comment]
The bug here is that the container should not have the certificate installed, I think this is a bug in the container setup steps. 

The certificate should be generated as part of the first run experience.

If the SDK needs to run other parts of the first run experience during the image build process, that's fine, but the cert needs to be created when the user uses the container or disabled all-together. There is a specific flag `DOTNET_GENERATE_ASPNET_CERTIFICATE` that can be use to avoid this specific part of the first run experience.

**Comment by javiercn** [comment]
@MichaelSimons @mthalman 

I've suggested the path forward [here](https://github.com/dotnet/aspnetcore/issues/33972#issuecomment-871658495) but I don't seem to be able to transfer the issue back.

Could you take a look at my suggestion on your side? Since the image shouldn't have a built-in certificate in the first place.

/cc: @Pilchie

**Comment by alfredmyers** [comment]
> The bug here is that the container should not have the certificate installed, I think this is a bug in the container setup steps.
> 
> The certificate should be generated as part of the first run experience.
> 
> If the SDK needs to run other parts of the first run experience during the image build process, that's fine, but the cert needs to be created when the user uses the container or disabled all-together. There is a specific flag `DOTNET_GENERATE_ASPNET_CERTIFICATE` that can be use to avoid this specific part of the first run experience.

Given the [security implications of the current default](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-6.0&tabs=visual-studio#trust-the-aspnet-core-https-development-certificate-on-windows-and-macos), wouldn't it be the case to change the default behavior to not create the ASP.NET Core HTTPS Development Certificate automatically and instead instruct the user to do so on first use?
