### ISSUE TITLE
Refactor Reset_PriorOSVersions_NotSupported

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#34003]
Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.Http2Tests.Reset_PriorOSVersions_NotSupported

The machines we test on may have been updated, test needs to be refactored.

<details>
<summary>Logs</summary>

```
[0.001s] [TestLifetime] [Information] Starting test Reset_PriorOSVersions_NotSupported at 2021-07-01T17:00:32
[0.033s] [Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.Http2Tests] [Error] Test threw an exception.
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode() in System.Net.Http.dll:token 0x6000376+0x39
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in System.Net.Http.dll:token 0x6000222+0xf8
   at Microsoft.AspNetCore.Server.HttpSys.FunctionalTests.Http2Tests.Reset_PriorOSVersions_NotSupported() in /_/src/Servers/HttpSys/test/FunctionalTests/Http2Tests.cs:line 644
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 273
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 54
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 96
[0.034s] [TestLifetime] [Information] Finished test Reset_PriorOSVersions_NotSupported in 0.0330937s
```

</details>

https://dev.azure.com/dnceng/public/_build/results?buildId=1214747&view=ms.vss-test-web.build-test-results-tab&runId=36288708&resultId=106211&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by Tratcher** [comment]
Logs and build links please

**Comment by mkArtakMSFT** [comment]
Here are the failure logs (from another PR): https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-pull-33998-merge-d47ef1bb65714191bb/Microsoft.AspNetCore.Server.HttpSys.FunctionalTests--net6.0/console.124e3acc.log?sv=2019-07-07&se=2021-07-21T17%3A10%3A07Z&sr=c&sp=rl&sig=pgvzAZ2zx%2FYw2n2LJy%2FcPsjbHIfCpnFb6F9EMd23U0s%3D

**Comment by Tratcher** [comment]
Fixed by agent updates on 7/28 and passing 100% since, this can be unquarantined.
