### ISSUE TITLE
Flaky test: IHttpActivityFeatureIsNotPopulatedWithoutAListener

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#34072]
## Failing Test(s)

Microsoft.AspNetCore.Hosting.Tests.HostingApplicationTests.IHttpActivityFeatureIsNotPopulatedWithoutAListener

## Error Message

```text
Assert.Null() Failure
Expected: (null)
Actual:   Activity { ActivityTraceFlags = None, Baggage = [], Context = System.Diagnostics.ActivityContext, DisplayName = "Microsoft.AspNetCore.Hosting.HttpRequestIn", Duration = 00:00:00, ... }
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.Hosting.Tests.HostingApplicationTests.IHttpActivityFeatureIsNotPopulatedWithoutAListener() in /_/src/Hosting/Hosting/test/HostingApplicationTests.cs:line 174
```
</details>

## Logs

<details>

```text
[xUnit.net 00:00:02.44]     Microsoft.AspNetCore.Hosting.Tests.HostingApplicationTests.IHttpActivityFeatureIsNotPopulatedWithoutAListener [FAIL]
[xUnit.net 00:00:02.45]       Assert.Null() Failure
[xUnit.net 00:00:02.45]       Expected: (null)
[xUnit.net 00:00:02.45]       Actual:   Activity { ActivityTraceFlags = None, Baggage = [], Context = System.Diagnostics.ActivityContext, DisplayName = "Microsoft.AspNetCore.Hosting.HttpRequestIn", Duration = 00:00:00, ... }
[xUnit.net 00:00:02.45]       Stack Trace:
[xUnit.net 00:00:02.45]         /_/src/Hosting/Hosting/test/HostingApplicationTests.cs(174,0): at Microsoft.AspNetCore.Hosting.Tests.HostingApplicationTests.IHttpActivityFeatureIsNotPopulatedWithoutAListener()
```
</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1219377&view=results

**Comment by BrennanConroy** [comment]
I believe this test failed because another test running in parallel was listening to all activities. https://github.com/dotnet/aspnetcore/pull/36908 changed the test to listen to a specific activity so it wont interfere with other tests.
Marking as `test-fixed`
