### ISSUE TITLE
CreatedAtAction Not working with method ending on "Async"

### ISSUE THREAD

**Issue by JeffIsLife** [dotnet/aspnetcore#34110]
### Describe the bug
When:
1. Your GET endpoint ends on 'Async'  
2. You execute a post request in an Dotnet Core Web API and return a value via the 'CreatedAtAction' method you receive an error similar to: 

> System.InvalidOperationException: No route matches the supplied values.
   at Microsoft.AspNetCore.Mvc.CreatedAtActionResult.OnFormatting(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncCore(ActionContext context, ObjectResult result, Type objectType, Object value)

-> using the guideline by calling the 'nameof()' the GET method also doesn't work. Except when ofcourse it doesn't end on 'Async'.

### To Reproduce
To reproduce this issue you have to create a similar controller as below and try to execute a post request:
`[Route("api/[controller]")]
	[ApiController]
	public class DemoController : ControllerBase
	{
		// GET api/<DemoController>/5
		[HttpGet]
		[Route("{id}")]
		public ActionResult<string> GetAsync([FromRoute] long id)
		{
			return "value";
		}

		// POST api/<DemoController>
		[HttpPost]
		public ActionResult<string> Post([FromBody] string value)
		{
			return CreatedAtAction("GetAsync", new { id = 0 }, value);
		}
	}`

### Exceptions (if any)
System.InvalidOperationException: No route matches the supplied values.
   at Microsoft.AspNetCore.Mvc.CreatedAtActionResult.OnFormatting(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncCore(ActionContext context, ObjectResult result, Type objectType, Object value)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsync(ActionContext context, ObjectResult result)
   at Microsoft.AspNetCore.Mvc.ObjectResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

### Further technical details
- .NET 5.0
- The IDE is VS Community Edition 2019. Version 16.8.6.

**Comment by pranavkm** [comment]
You're very likely running in to this: https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-5.0&tabs=visual-studio#async-suffix-removal-from-controller-action-names. Does the suppression listed in the notes help?

**Comment by JeffIsLife** [comment]
Injecting SuppressAsyncSuffixInActionNames = false to the 'AddMvc' fixed the issue! Issue can be closed!
Thanks!

Conclussion:
Update
services.AddMvc(); 
To
services.AddMvc(options =>
    options.SuppressAsyncSuffixInActionNames = false);
