### ISSUE TITLE
Unable to login into facebook, google etc using Identity Authentication in Live Production Mode?

### ISSUE THREAD

**Issue by aloksharma1** [dotnet/aspnetcore#34381]
### Describe the bug
My Social Login Example is following the standard microsoft examples of social logins as well as this repo [here](https://github.com/NeelBhatt/FacebookLoginNetCore) And its working seemlessly in my local development enviornment. But when i put my code on production website, it gets stuck at /signin-facebook (or google or whatever is supported) this part.

### To Reproduce

To reproduce you can use the repo provided above and make a facebook login app & generate key/secret to see it in action.

here is my startup.cs code for identity if that helps:

```
public static void AddIdentityService(this IServiceCollection services, IConfiguration configuration)
        {
            if (configuration.GetValue<bool>("UseInMemoryDatabase"))
            {
                //services.AddDbContext<IdentityContext>(options =>
                //    options.UseInMemoryDatabase("IdentityDb"));
            }
            else
            {
                services.AddDbContext<IdentityContext>(options =>
                options.UseSqlServer(
                    configuration.GetSection("DBProviders:0:ConnectionString").Value,
                    b => b.MigrationsAssembly(typeof(IdentityContext).Assembly.FullName)));
            }
            services.AddIdentity<ApplicationUser, ApplicationRoles>().AddEntityFrameworkStores<IdentityContext>()
                .AddDefaultTokenProviders();
            #region Services
            //services.AddTransient<IAccountService, AccountService>();
            #endregion
            services.Configure<JWTSettings>(configuration.GetSection("JWTSettings"));
            services.Configure<ForwardedHeadersOptions>(options =>
            {
                options.ForwardedHeaders =
                    ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
            });
            services.AddAuthentication(options =>
              {
                  //options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                  //options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
                  //options.a
                  
              })
                  .AddJwtBearer(o =>
                  {
                      o.RequireHttpsMetadata = false;
                      o.SaveToken = false;
                      o.TokenValidationParameters = new TokenValidationParameters
                      {
                          ValidateIssuerSigningKey = true,
                          ValidateIssuer = true,
                          ValidateAudience = true,
                          ValidateLifetime = true,
                          ClockSkew = TimeSpan.Zero,
                          ValidIssuer = configuration["JWTSettings:Issuer"],
                          ValidAudience = configuration["JWTSettings:Audience"],
                          IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(configuration["JWTSettings:Key"]))
                      };
                      o.Events = new JwtBearerEvents()
                      {
                          OnAuthenticationFailed = c =>
                          {
                              c.NoResult();
                              c.Response.StatusCode = 500;
                              c.Response.ContentType = "text/plain";
                              return c.Response.WriteAsync(c.Exception.ToString());
                          },
                          OnChallenge = context =>
                          {
                              context.HandleResponse();
                              context.Response.StatusCode = 401;
                              context.Response.ContentType = "application/json";
                              var result = JsonConvert.SerializeObject(new Response<string>("You are not Authorized"));
                              return context.Response.WriteAsync(result);
                          },
                          OnForbidden = context =>
                          {
                              context.Response.StatusCode = 403;
                              context.Response.ContentType = "application/json";
                              var result = JsonConvert.SerializeObject(new Response<string>("You are not authorized to access this resource"));
                              return context.Response.WriteAsync(result);
                          },
                      };
                  })
                  .AddFacebook("Facebook", facebookOptions =>
                   {
                       facebookOptions.AppId = "0";
                       facebookOptions.AppSecret = "0";                       
                   }).AddGoogle("Google", googleOptions =>
                   {
                       googleOptions.ClientId = "0";
                       googleOptions.ClientSecret = "0";
                   }).AddCookie(options => {
                       options.ExpireTimeSpan = TimeSpan.FromDays(3);
                       options.Cookie.SameSite = SameSiteMode.None;
                   })
                  ;
            services.Configure<IdentityOptions>(options =>
            {
                // Password settings
                options.Password.RequireDigit = true;
                options.Password.RequiredLength = 8;
                options.Password.RequireNonAlphanumeric = false;
                options.Password.RequireUppercase = true;
                options.Password.RequireLowercase = false;
                options.Password.RequiredUniqueChars = 6;

                // Lockout settings
                options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(30);
                options.Lockout.MaxFailedAccessAttempts = 10;
                options.Lockout.AllowedForNewUsers = true;

                // User settings
                options.User.RequireUniqueEmail = true;                
            });
            services.ConfigureApplicationCookie(options =>
            {
                // Cookie settings
                options.Cookie.HttpOnly = true;
                options.Cookie.SameSite = SameSiteMode.None;
                options.ExpireTimeSpan = TimeSpan.FromDays(365);
                options.LoginPath = "/Account/Login"; // If the LoginPath is not set here, ASP.NET Core will default to /Account/Login
                options.LogoutPath = "/Account/Logout"; // If the LogoutPath is not set here, ASP.NET Core will default to /Account/Logout
                options.AccessDeniedPath = "/Account/AccessDenied"; // If the AccessDeniedPath is not set here, ASP.NET Core will default to /Account/AccessDenied
                options.SlidingExpiration = true;
            });
        }

```
### Exceptions (if any)

Nothing no exception just infinite wait for /signin-facebook method to move to /externallogincallback function on production enviornment.
### Further technical details
- ASP.NET Core version 5
- Include the output of `dotnet --info` none
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version use any you like
- Hosted in IIS 10 windows 2019 datacenter server

**Comment by Tratcher** [comment]
Can you share the server logs?
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0#configure-logging

**Comment by aloksharma1** [comment]
@Tratcher below are the logs from iis, event viewer gives no error, let me know if i need to do any log settings related changes.

awaiting your reply


[u_ex210715.log](https://github.com/dotnet/aspnetcore/files/6827230/u_ex210715.log)
[u_ex210715 (1).log](https://github.com/dotnet/aspnetcore/files/6827231/u_ex210715.1.log)

[httperr1.log](https://github.com/dotnet/aspnetcore/files/6827229/httperr1.log)

**Comment by Tratcher** [comment]
You're getting an error message back from Facebook:
```
/signin-facebook error_code=1349048&error_message=Can%27t+load+URL%3A+The+domain+of+this+URL+isn%27t+included+in+the+app%27s+domains.+To+be+able+to+load+this+URL%2C+add+all+domains+and+sub-domains+of+your+app+to+the+App+Domains+field+in+your+app+settings.
```

This causes a 500 response from your application.

**Comment by aloksharma1** [comment]
@Tratcher that is an old event when i was configuring testing app url to live mode, as you can see in logs its event time is older all my social logins have same issue on production server.

**Comment by Tratcher** [comment]
The last response from facebook was:
```
2021-07-15 16:19:36 172.31.16.76 GET /signin-facebook error_code=1340031&error_message=Unable+to+Log+In%3A+There+is+a+60-minute+delay+before+new+accounts+can+log+in+to+any+applications.+Please+try+again+in+an+hour. 443 - 3.141.20.39 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/91.0.4472.106+Safari/537.36 https://www.facebook.com/ 200 0 64 1946
```

**Comment by aloksharma1** [comment]
@Tratcher this was when i was trying using a new account last night, anyways i have integrated serilog for more verbose logging inside application and here is what i got.. the endpoint is hitting but after that application starts DbContext and then nothing here is the log:
```
Executing endpoint '"Ultra.LoginModule.Controllers.SocialController.ExternalLogin (Ultra.LoginModule)"'
Route matched with "{action = \"ExternalLogin\", controller = \"Social\", area = \"\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.IActionResult ExternalLogin(System.String, System.String)" on controller "Ultra.LoginModule.Controllers.SocialController" ("Ultra.LoginModule").
Executing ChallengeResult with authentication schemes (["Facebook"]).
AuthenticationScheme: "Facebook" was challenged.
Executed action "Ultra.LoginModule.Controllers.SocialController.ExternalLogin (Ultra.LoginModule)" in 18.4382ms
Executed endpoint '"Ultra.LoginModule.Controllers.SocialController.ExternalLogin (Ultra.LoginModule)"'
HTTP "POST" "/Social/ExternalLogin" responded 302 in 22.1197 ms
Request finished HTTP/2 POST https://saralitr.com/Social/ExternalLogin?returnurl=%2FHome application/x-www-form-urlencoded 200 - 302 - - 43.5917ms
Request starting HTTP/2 GET https://saralitr.com/signin-facebook?code=AQCAp5u436YJJb-Iq_jZHImoWuPPR2R-ZOTrVLrc5C9km6RSUhGOiS06XUofeirmUUDzjMkRkeMrivQSznFLyt7FFgSsbN42EAZTdHIqjZpBxnRw3iXTlHDmIR54rmyCndEZbKn2p8n178JFN5igfrHZq8mHN6uGu2JWByiEWaArF62uYFLaVtHmtmDPmXKh2rW1DwGTXCM0qPoRQhXsTzz0uQLF8V0h6H2LDtTn6XfVxBRxYAE51VEggFcgSo9kpdKByCAPiWwKsWGYKhWWSZ41kdo7SIFhfGy7xLgQwQVhTH-tpBTFXYDQr5HatKdsJWA&state=CfDJ8LeKq2QzootKvnjh7Bs-lHnQFzI6RtHwapaX7BUC3hH7BUG-q_fGbZCkFE_gQPxHSNqFP6O1emlnwcXDnbIXC9SpFiNZoRVEaFcypUkLmMbKPEMmQ6CYxcNXbUlvwWEyVG6-wDgg_Ez-WLyw8HlnMg3y8qCRbJO3a1eeq4Y1MFvyLjsFF-0JZg8fix0x-v2bfgPrA-Thd8OlncG2IWQHAeBVRZD0lfXkvsOiq5Tr3r4QOSep01vPRr1NTa8v5EoIWgc2z6Qr6Kyl0mvOO8InxBNqyQr2NF3JH-jCSIOTUeWs - -
Entity Framework Core "5.0.5" initialized '"UltraDbContext"' using provider '"Microsoft.EntityFrameworkCore.SqlServer"' with options: "MigrationsAssembly=Ultra.Persistence, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null "
Entity Framework Core "5.0.5" initialized '"IdentityContext"' using provider '"Microsoft.EntityFrameworkCore.SqlServer"' with options: "MigrationsAssembly=Ultra.Persistence, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null "
```

my application db context is initiliazed at startup and working ok everywhere so its getting stuck at db context initialization after the roundtrip is very weird.

**Comment by aloksharma1** [comment]
ok, after a long wait of half an hour from last request i got this exception in my logs:

```
System.Exception: An error was encountered while handling the remote login.
 ---> System.Exception: Correlation failed.
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Ultra.Services.Middleware.ActiveSitesMiddleWare.InvokeAsync(HttpContext httpContext, ActiveSites ActiveSitesMap, IHttpContextAccessor httpContextAccessor) in D:\Projects\Web\dotnet\UltraWeb\Net5\Ultra.WebHost\Ultra.Services\Middleware\ActiveSitesMiddleWare.cs:line 55
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
```

**Comment by Tratcher** [comment]
What's in the ActiveSitesMiddleWare? It's not in your linked repo sample.

**Comment by aloksharma1** [comment]
thats just a middleware to make a singleton dictionary unrelated to this code. i am sure its just showing because all middlewares are executed with requests.

**Comment by aloksharma1** [comment]
ok i fixed the issue, there are a few changes i did with my code related to cookies permissions (dont know why that was needed) & had to reboot my server instance too, here is the updated code for anyone else who gets into similar ruckus (i had to waste 30 hours non stop on this) : 

```
public static void AddIdentityService(this IServiceCollection services, IConfiguration configuration)
        {
            if (configuration.GetValue<bool>("UseInMemoryDatabase"))
            {
                //services.AddDbContext<IdentityContext>(options =>
                //    options.UseInMemoryDatabase("IdentityDb"));
            }
            else
            {
                services.AddDbContext<IdentityContext>(options =>
                options.UseSqlServer(
                    configuration.GetSection("DBProviders:0:ConnectionString").Value,
                    b => b.MigrationsAssembly(typeof(IdentityContext).Assembly.FullName)));
            }
            services.AddIdentity<ApplicationUser, ApplicationRoles>().AddEntityFrameworkStores<IdentityContext>()
                .AddDefaultTokenProviders();
            #region Services
            //services.AddTransient<IAccountService, AccountService>();
            #endregion
            services.Configure<JWTSettings>(configuration.GetSection("JWTSettings"));
            services.Configure<ForwardedHeadersOptions>(options =>
            {
                options.ForwardedHeaders =
                    ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
            });
            services.AddAuthentication(options =>
              {
                  //options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                  //options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
                  //options.a
                  
              })
                  .AddJwtBearer(o =>
                  {
                      o.RequireHttpsMetadata = false;
                      o.SaveToken = false;
                      o.TokenValidationParameters = new TokenValidationParameters
                      {
                          ValidateIssuerSigningKey = true,
                          ValidateIssuer = true,
                          ValidateAudience = true,
                          ValidateLifetime = true,
                          ClockSkew = TimeSpan.Zero,
                          ValidIssuer = configuration["JWTSettings:Issuer"],
                          ValidAudience = configuration["JWTSettings:Audience"],
                          IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(configuration["JWTSettings:Key"]))
                      };
                      o.Events = new JwtBearerEvents()
                      {
                          OnAuthenticationFailed = c =>
                          {
                              c.NoResult();
                              c.Response.StatusCode = 500;
                              c.Response.ContentType = "text/plain";
                              return c.Response.WriteAsync(c.Exception.ToString());
                          },
                          OnChallenge = context =>
                          {
                              context.HandleResponse();
                              context.Response.StatusCode = 401;
                              context.Response.ContentType = "application/json";
                              var result = JsonConvert.SerializeObject(new Response<string>("You are not Authorized"));
                              return context.Response.WriteAsync(result);
                          },
                          OnForbidden = context =>
                          {
                              context.Response.StatusCode = 403;
                              context.Response.ContentType = "application/json";
                              var result = JsonConvert.SerializeObject(new Response<string>("You are not authorized to access this resource"));
                              return context.Response.WriteAsync(result);
                          },
                      };
                  })
                  .AddFacebook("Facebook", facebookOptions =>
                   {
                       facebookOptions.AppId = "0";
                       facebookOptions.AppSecret = "0";
                       facebookOptions.SaveTokens = true;
                   }).AddGoogle("Google", googleOptions =>
                   {
                       googleOptions.ClientId = "0";
                       googleOptions.ClientSecret = "0";
                       googleOptions.SaveTokens = true;
                       googleOptions.AuthorizationEndpoint += "?prompt=consent";
                   })
                   //.AddCookie(options => {
                   //    options.Cookie.HttpOnly = true;
                   //    //options.Cookie.SameSite = SameSiteMode.Strict;
                   //    options.ExpireTimeSpan = TimeSpan.FromDays(365);
                   //    options.LoginPath = "/Account/Login"; // If the LoginPath is not set here, ASP.NET Core will default to /Account/Login
                   //    options.LogoutPath = "/Account/Logout"; // If the LogoutPath is not set here, ASP.NET Core will default to /Account/Logout
                   //    options.AccessDeniedPath = "/Account/AccessDenied"; // If the AccessDeniedPath is not set here, ASP.NET Core will default to /Account/AccessDenied
                   //    options.SlidingExpiration = true;
                   //    //options.Cookie.SecurePolicy = CookieSecurePolicy.Always;
                   //})
                  ;
            services.Configure<IdentityOptions>(options =>
            {
                // Password settings
                options.Password.RequireDigit = true;
                options.Password.RequiredLength = 8;
                options.Password.RequireNonAlphanumeric = false;
                options.Password.RequireUppercase = true;
                options.Password.RequireLowercase = false;
                options.Password.RequiredUniqueChars = 6;

                // Lockout settings
                options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(30);
                options.Lockout.MaxFailedAccessAttempts = 10;
                options.Lockout.AllowedForNewUsers = true;

                // User settings
                options.User.RequireUniqueEmail = true;                
            });
            services.ConfigureApplicationCookie(options =>
            {
                // Cookie settings
                options.Cookie.HttpOnly = true;
                options.ExpireTimeSpan = TimeSpan.FromDays(365);
                options.LoginPath = "/Account/Login"; // If the LoginPath is not set here, ASP.NET Core will default to /Account/Login
                options.LogoutPath = "/Account/Logout"; // If the LogoutPath is not set here, ASP.NET Core will default to /Account/Logout
                options.AccessDeniedPath = "/Account/AccessDenied"; // If the AccessDeniedPath is not set here, ASP.NET Core will default to /Account/AccessDenied
                options.SlidingExpiration = true;
                options.Cookie.IsEssential = true;              
            });
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });
        }
```

wish this can help someone else in future.
