### ISSUE TITLE
Quarantined test:  Microsoft.AspNetCore.SignalR.Client.Tests.HubConnectionTests+ConnectionLifecycle.ClientTimesoutWhenHandshakeResponseTakesTooLong

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#34393]
https://dev.azure.com/dnceng/public/_build/results?buildId=1240522&view=ms.vss-test-web.build-test-results-tab&runId=36892672&resultId=117946&paneView=debug

```
Assert.Throws() Failure
Expected: typeof(System.OperationCanceledException)
Actual:   typeof(System.Threading.Tasks.TaskCanceledException): A task was canceled.
---- System.Threading.Tasks.TaskCanceledException : A task was canceled.

  at Microsoft.AspNetCore.SignalR.Client.HubConnection.HandshakeAsync(ConnectionState startingConnectionState, CancellationToken cancellationToken) in /_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:line 1071
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken) in /_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:line 442
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken) in /_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:line 450
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken) in /_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:line 264
   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult() in /_/src/SignalR/common/Shared/ForceAsyncAwaiter.cs:line 40
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken) in /_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:line 241
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.HandshakeAsync(ConnectionState startingConnectionState, CancellationToken cancellationToken) in /_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:line 1071
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken) in /_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:line 442
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken) in /_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:line 450
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken) in /_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:line 264
   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult() in /_/src/SignalR/common/Shared/ForceAsyncAwaiter.cs:line 40
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken) in /_/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs:line 241
```

**Comment by BrennanConroy** [comment]
Being fixed in https://github.com/dotnet/aspnetcore/pull/34394

**Comment by BrennanConroy** [comment]
Fixed in https://github.com/dotnet/aspnetcore/pull/34394
