### ISSUE TITLE
HTTP1 not trimming trailing CRLF's in final header

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#34402]
Running the `Http1ConnectionParsingOverheadBenchmark` benchmark in Kestrel (https://github.com/dotnet/aspnetcore/blob/main/src/Servers/Kestrel/perf/Microbenchmarks/Http1ConnectionParsingOverheadBenchmark.cs), the value returned by https://github.com/dotnet/aspnetcore/blob/0f37ede529d5b16aec856039ce18568d15d223e2/src/Servers/Kestrel/Core/src/Internal/Infrastructure/HttpUtilities.cs#L111-L138 will end with `CR LF CR LF` for the final header sent:

> at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.HttpUtilities.GetRequestHeaderString(ReadOnlySpan`1 span, String name, Func`2 encodingSelector) in C:\code\aspnet\aspnetcore\src\Servers\Kestrel\Core\src\Internal\Infrastructure\HttpUtilities.cs:line 151
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestHeaders.Append(ReadOnlySpan`1 name, ReadOnlySpan`1 value) in C:\code\aspnet\aspnetcore\src\Servers\Kestrel\Core\src\Internal\Http\HttpHeaders.Generated.cs:line 7433
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.OnHeader(ReadOnlySpan`1 name, ReadOnlySpan`1 value) in C:\code\aspnet\aspnetcore\src\Servers\Kestrel\Core\src\Internal\Http\HttpProtocol.cs:line 524
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ParsingHandler.OnHeader(ReadOnlySpan`1 name, ReadOnlySpan`1 value) in C:\code\aspnet\aspnetcore\src\Servers\Kestrel\Core\src\Internal\Http\Http1ParsingHandler.cs:line 34
   at Microsoft.AspNetCore.Server.Kestrel.Microbenchmarks.NullParser`1.ParseHeaders(TRequestHandler handler, SequenceReader`1& reader) in C:\code\aspnet\aspnetcore\src\Servers\Kestrel\perf\Microbenchmarks\Mocks\NullParser.cs:line 27
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TakeMessageHeaders(SequenceReader`1& reader, Boolean trailers) in C:\code\aspnet\aspnetcore\src\Servers\Kestrel\Core\src\Internal\Http\Http1Connection.cs:line 221
   at Microsoft.AspNetCore.Server.Kestrel.Microbenchmarks.Http1ConnectionParsingOverheadBenchmark.ParseRequest() in C:\code\aspnet\aspnetcore\src\Servers\Kestrel\perf\Microbenchmarks\Http1ConnectionParsingOverheadBenchmark.cs:line 86
   at Microsoft.AspNetCore.Server.Kestrel.Microbenchmarks.Http1ConnectionParsingOverheadBenchmark.Http1ConnectionOverheadTotal() in C:\code\aspnet\aspnetcore\src\Servers\Kestrel\perf\Microbenchmarks\Http1ConnectionParsingOverheadBenchmark.cs:line 54

Specifically, the string returned is `text/plain,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7\r\n\r\n`, from here: https://github.com/dotnet/aspnetcore/blob/main/src/Servers/Kestrel/perf/Microbenchmarks/RequestParsingData.cs

HTTP1 should trim these control characters before calling the method.

CC @Tratcher @halter73 @BrennanConroy @JamesNK

**Comment by Tratcher** [comment]
Looks like a weird benchmark issue:
https://github.com/dotnet/aspnetcore/blob/57f828e2fe86bd37716924aedffc7d52fd80aab5/src/Servers/Kestrel/perf/Microbenchmarks/Mocks/NullParser.cs#L18
