### ISSUE TITLE
blazor server signalr JsonReaderException

### ISSUE THREAD

**Issue by csandoy** [dotnet/aspnetcore#34419]
.net core 6 preview 6
Blazor server with Azure AD 
all this works fine
after adding SignalR to the project I get an  error when I start SignalR

hubConnectionBruger = new HubConnectionBuilder()
            .WithUrl(navManager.ToAbsoluteUri("/hubs/useractivity"))
            .WithAutomaticReconnect()
            .Build();

            hubConnectionBruger.On<int>("showUsersOnLine", (antal) =>
            {
                AntalBrugere = antal;
                StateHasChanged();
            });

            await hubConnectionBruger.StartAsync();

error:
JsonReaderException: '<' is an invalid start of a value

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by BrennanConroy** [comment]
Is your hub configured to be at the "/hubs/useractivity" endpoint? I'm guessing the '<' is the start of an html page which likely means you're not hitting a hub endpoint.

**Comment by csandoy** [comment]
app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapBlazorHub();
                endpoints.MapHub<NotifyHub>("/hubs/notify");
                endpoints.MapHub<UserActivityHub>("/hubs/useractivity");
                endpoints.MapFallbackToPage("/_Host");
            });

**Comment by mkArtakMSFT** [comment]
@BrennanConroy do we need any other information here?

**Comment by csandoy** [comment]
log from error screen
System.IO.InvalidDataException: Invalid negotiation response received.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 2 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes) in System.Text.Json.dll:token 0x60000da+0x0
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker) in System.Text.Json.dll:token 0x60002fd+0x154
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first) in System.Text.Json.dll:token 0x60002fb+0x107
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment() in System.Text.Json.dll:token 0x60002f8+0x134
   at System.Text.Json.Utf8JsonReader.Read() in System.Text.Json.dll:token 0x60002e4+0x8
   at Microsoft.AspNetCore.Internal.SystemTextJsonExtensions.CheckRead(Utf8JsonReader& reader) in Microsoft.AspNetCore.Http.Connections.Common.dll:token 0x6000016+0x0
   at Microsoft.AspNetCore.Http.Connections.NegotiateProtocol.ParseResponse(ReadOnlySpan`1 content) in Microsoft.AspNetCore.Http.Connections.Common.dll:token 0x600002a+0x0
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Http.Connections.NegotiateProtocol.ParseResponse(ReadOnlySpan`1 content) in Microsoft.AspNetCore.Http.Connections.Common.dll:token 0x600002a+0x26c
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync(Uri url, HttpClient httpClient, ILogger logger, CancellationToken cancellationToken) in Microsoft.AspNetCore.Http.Connections.Client.dll:token 0x6000048+0x1ca
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.GetNegotiationResponseAsync(Uri uri, CancellationToken cancellationToken) in Microsoft.AspNetCore.Http.Connections.Client.dll:token 0x600004f+0x80
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat, CancellationToken cancellationToken) in Microsoft.AspNetCore.Http.Connections.Client.dll:token 0x6000047+0x17b
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat, CancellationToken cancellationToken) in Microsoft.AspNetCore.Http.Connections.Client.dll:token 0x6000044+0x127
   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult() in Microsoft.AspNetCore.Http.Connections.Client.dll:token 0x600002b+0xc
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken) in Microsoft.AspNetCore.Http.Connections.Client.dll:token 0x6000043+0x91
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken) in Microsoft.AspNetCore.Http.Connections.Client.dll:token 0x6000052+0x114
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken) in Microsoft.AspNetCore.Http.Connections.Client.dll:token 0x6000052+0x1a5
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken) in Microsoft.AspNetCore.SignalR.Client.Core.dll:token 0x6000054+0xa5
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken) in Microsoft.AspNetCore.SignalR.Client.Core.dll:token 0x600004c+0x14d
   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult() in Microsoft.AspNetCore.SignalR.Client.Core.dll:token 0x600001c+0xc
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken) in Microsoft.AspNetCore.SignalR.Client.Core.dll:token 0x600004b+0x91
   at Intranet.Blazor6.Shared.MainLayout.OnInitializedAsync() in C:\Projektor\Intranet.Blazor6\Intranet.Blazor6\Shared\MainLayout.razor.cs:line 64
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync() in Microsoft.AspNetCore.Components.dll:token 0x60000a0+0xa7
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState) in Microsoft.AspNetCore.Components.dll:token 0x600023e+0x65
   at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.HandleException(Exception exception) in Microsoft.AspNetCore.Mvc.ViewFeatures.dll:token 0x6000070+0x0
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.HandleExceptionViaErrorBoundary(Exception error, ComponentState errorSourceOrNull) in Microsoft.AspNetCore.Components.dll:token 0x6000240+0x67
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState) in Microsoft.AspNetCore.Components.dll:token 0x600023e+0x7c
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessAsynchronousWork() in Microsoft.AspNetCore.Components.dll:token 0x6000229+0x76
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderRootComponentAsync(Int32 componentId, ParameterView initialParameters) in Microsoft.AspNetCore.Components.dll:token 0x6000227+0xd3
   at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.CreateInitialRenderAsync(Type componentType, ParameterView initialParameters) in Microsoft.AspNetCore.Mvc.ViewFeatures.dll:token 0x6000077+0x8b
   at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.RenderComponentAsync(Type componentType, ParameterView initialParameters) in Microsoft.AspNetCore.Mvc.ViewFeatures.dll:token 0x600006e+0x74
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c__11`1.<<InvokeAsync>b__11_0>d.MoveNext() in Microsoft.AspNetCore.Components.dll:token 0x60003f6+0x7d
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.ViewFeatures.StaticComponentRenderer.PrerenderComponentAsync(ParameterView parameters, HttpContext httpContext, Type componentType) in Microsoft.AspNetCore.Mvc.ViewFeatures.dll:token 0x60004d0+0x13c
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentRenderer.PrerenderedServerComponentAsync(HttpContext context, ServerComponentInvocationSequence invocationId, Type type, ParameterView parametersCollection) in Microsoft.AspNetCore.Mvc.ViewFeatures.dll:token 0x60004c3+0xd7
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentRenderer.RenderComponentAsync(ViewContext viewContext, Type componentType, RenderMode renderMode, Object parameters) in Microsoft.AspNetCore.Mvc.ViewFeatures.dll:token 0x60004be+0x16c
   at Microsoft.AspNetCore.Mvc.TagHelpers.ComponentTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output) in Microsoft.AspNetCore.Mvc.TagHelpers.dll:token 0x6000055+0xdf
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count) in Microsoft.AspNetCore.Razor.Runtime.dll:token 0x600004a+0x65
   at Intranet.Blazor6.Pages.Pages__Host.<ExecuteAsync>b__14_1() in c:\Projektor\Intranet.Blazor6\Intranet.Blazor6\Pages\_Host.cshtml:line 22
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync() in Microsoft.AspNetCore.Razor.Runtime.dll:token 0x6000046+0x84
   at Intranet.Blazor6.Pages.Pages__Host.ExecuteAsync() in c:\Projektor\Intranet.Blazor6\Intranet.Blazor6\Pages\_Host.cshtml:line 5
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context) in Microsoft.AspNetCore.Mvc.Razor.dll:token 0x60000c0+0xc7
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts) in Microsoft.AspNetCore.Mvc.Razor.dll:token 0x60000bf+0x1db
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context) in Microsoft.AspNetCore.Mvc.Razor.dll:token 0x60000be+0xa7
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode) in Microsoft.AspNetCore.Mvc.ViewFeatures.dll:token 0x6000583+0x16d
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode) in Microsoft.AspNetCore.Mvc.ViewFeatures.dll:token 0x6000583+0x275
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|22_0(ResourceInvoker invoker, IActionResult result) in Microsoft.AspNetCore.Mvc.Core.dll:token 0x6000a8d+0xb0
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) in Microsoft.AspNetCore.Mvc.Core.dll:token 0x6000a94+0x6a
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context) in Microsoft.AspNetCore.Mvc.Core.dll:token 0x6000a87+0x15
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted) in Microsoft.AspNetCore.Mvc.Core.dll:token 0x6000a82+0x3dc
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) in Microsoft.AspNetCore.Mvc.Core.dll:token 0x6000a93+0x6e
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) in Microsoft.AspNetCore.Mvc.Core.dll:token 0x6000a90+0x6a
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context) in Microsoft.AspNetCore.Mvc.Core.dll:token 0x6000a85+0x15
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) in Microsoft.AspNetCore.Mvc.Core.dll:token 0x6000a7c+0x835
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) in Microsoft.AspNetCore.Mvc.Core.dll:token 0x6000a8c+0x6e
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker) in Microsoft.AspNetCore.Mvc.Core.dll:token 0x6000a89+0x172
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker) in Microsoft.AspNetCore.Mvc.Core.dll:token 0x6000a89+0x21d
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger) in Microsoft.AspNetCore.Routing.dll:token 0x60000ab+0x5e
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult) in Microsoft.AspNetCore.Authorization.Policy.dll:token 0x600000e+0x303
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) in Microsoft.AspNetCore.Authorization.Policy.dll:token 0x600000b+0x392
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) in Microsoft.AspNetCore.Authentication.dll:token 0x6000044+0x384
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context) in Microsoft.AspNetCore.Diagnostics.dll:token 0x60000aa+0x82

**Comment by BrennanConroy** [comment]
Those are not the logs, please share the logs.
They will look similar to:
```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:5001/ - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:5001/ - - - 200 - - 86.6800ms
```

**Comment by csandoy** [comment]
Microsoft.Hosting.Lifetime: Information: Now listening on: https://localhost:5001
Microsoft.Hosting.Lifetime: Information: Now listening on: http://localhost:5000
Microsoft.Hosting.Lifetime: Information: Application started. Press Ctrl+C to shut down.
Microsoft.Hosting.Lifetime: Information: Hosting environment: Development
Microsoft.Hosting.Lifetime: Information: Content root path: C:\Projektor\Intranet.Blazor6\Intranet.Blazor6
Microsoft.AspNetCore.SignalR.Client.HubConnection: Debug: Registering handler for client method 'showUsersOnLine'.
Microsoft.AspNetCore.SignalR.Client.HubConnection: Debug: Starting HubConnection.
Microsoft.AspNetCore.Http.Connections.Client.HttpConnection: Debug: Starting HttpConnection.
Microsoft.AspNetCore.Http.Connections.Client.HttpConnection: Debug: Establishing connection with server at 'https://localhost:5001/hubs/useractivity'.
Microsoft.AspNetCore.Http.Connections.Client.HttpConnection: Error: Failed to start connection. Error getting negotiation response from 'https://localhost:5001/hubs/useractivity'.

System.IO.InvalidDataException: Invalid negotiation response received.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 2 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes) in System.Text.Json.dll:token 0x60000da+0x0
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker) in System.Text.Json.dll:token 0x60002fd+0x154
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first) in System.Text.Json.dll:token 0x60002fb+0x107
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment() in System.Text.Json.dll:token 0x60002f8+0x134
   at System.Text.Json.Utf8JsonReader.Read() in System.Text.Json.dll:token 0x60002e4+0x8
   at Microsoft.AspNetCore.Internal.SystemTextJsonExtensions.CheckRead(Utf8JsonReader& reader) in Microsoft.AspNetCore.Http.Connections.Common.dll:token 0x6000016+0x0
   at Microsoft.AspNetCore.Http.Connections.NegotiateProtocol.ParseResponse(ReadOnlySpan`1 content) in Microsoft.AspNetCore.Http.Connections.Common.dll:token 0x600002a+0x0
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Http.Connections.NegotiateProtocol.ParseResponse(ReadOnlySpan`1 content) in Microsoft.AspNetCore.Http.Connections.Common.dll:token 0x600002a+0x26c
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync(Uri url, HttpClient httpClient, ILogger logger, CancellationToken cancellationToken) in Microsoft.AspNetCore.Http.Connections.Client.dll:token 0x6000048+0x1ca
Microsoft.AspNetCore.Http.Connections.Client.HttpConnection: Debug: Skipping dispose, connection is already disposed.

**Comment by BrennanConroy** [comment]
It looks like you are filtering out a bunch of logs, either intentionally or because your appsettings.json is set to Warning for most logs.

I'm looking for very specific logs like where your request is being routed to and the response.

It might be easier if you put a simple repro app as a GitHub repo so we can take a look.

**Comment by csandoy** [comment]
I hade contact with Cristos Matkas from Microsoft regarding this problem, this is what he said
It turns out that there is a known issue breaking SignalR Hubs with Blazor Server and Microsoft Identity. The main issue is that you have 2 SignalR connections and this doesn't work well at the moment. 

My recommendation (and that of the SignalR team) would be to split out the SignalR Hub on a separate API. That way, you'll have separation of concerns and will allow youto do proper authentication and authorization on both ends. This will also unblock you from the current issue you're facing.

**Comment by adityamandaleeka** [comment]
@cmatskas can you please explain the breaking issue?

**Comment by harris-boyce** [comment]
I was experiencing the same issue:

- Server Side blazor
- Microsoft Identity Web (MSAL) for Authentication
- Adding a second hub for communication between MVC auxiliary requests and Blazor app to update application/user state
- Negotiation exception was thrown when connecting to the second hub

I was able to work around this by adding the following code:
```
hubConnection = new HubConnectionBuilder().WithUrl($"{navManager.BaseUri.TrimEnd('/')}{HubUrl}", options =>
{
    var container = new System.Net.CookieContainer();
    foreach (var item in context.HttpContext.Request.Cookies)
    {
        container.Add(new System.Net.Cookie(item.Key, item.Value) { Domain = context.HttpContext.Request.Host.Host, HttpOnly = true });
    }
    options.Cookies = container;
}).Build();
```

I believe this is because of forcing every request to be authenticated and since this is server-side Blazor, the cookie isn't being sent on the WebSocket/SignalR connection and it is being challenged (which is why markup is received in the stream).

This feels...yucky...to say the least.

Any ideas on improving this are greatly appreciated.

**Comment by BrennanConroy** [comment]
> It turns out that there is a known issue breaking SignalR Hubs with Blazor Server and Microsoft Identity.

Ah, so your original exception was likely because you were hitting an authorized endpoint with an unauthorized connection so it was sending you some html for either the login page or an error page.

There are some docs covering getting your auth token(s) in the component so that you can make an authorized request from an Http client or SignalR client from inside the component. https://docs.microsoft.com/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-5.0#pass-tokens-to-a-blazor-server-app

I'll defer to the blazor team for ideas on how to make this cleaner or if there are already issues for this.

**Comment by mkArtakMSFT** [comment]
Thanks @BrennanConroy.
At this point we don't plan to make improvements in this area given that we haven't seen many customers hitting it. If we see more people running into this, we will reconsider.

**Comment by harris-boyce** [comment]
@mkArtakMSFT, @BrennanConroy  what is the typical pattern seen here? Would the SignalR Hub run in a separate app, secured via JWTs or otherwise and the Blazor client acquire an access token to the Hub? I'm trying to balance my understanding of the pieces because it gets more complex and "interesting" when things require Authentication -- and even more interesting when your app(s) are multi-tenant and require consent, etc.  If I wasn't concerned with who a user is and what they're trying to do, I'd just throw apps and services around like confetti but in these scenarios, confetti is reserved for when you ship 😉 

Appreciate the thoughts
