### ISSUE TITLE
Accessing Local Storage inside `DelegatingHandler` in Blazor Server and .NET MAUI Blazor

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/aspnetcore#34421]
We need to access local storage to get the access token stored in local storage and bind it to the HTTP request but currently accessing local storage inside `DelegatingHandler` does not work in **Blazor Server** and **.NET MAUI Blazor**.

Here is the DelegatingHandler:

```C#
public class AuthorizationDelegatingHandler : DelegatingHandler
{
    private readonly ILocalStorageService _localStorage;

    public AuthorizationDelegatingHandler(ILocalStorageService localStorage)
    {
        _localStorage = localStorage;
    }

    protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        if (request == null)
        {
            throw new ArgumentNullException(nameof(request));
        }

        try
        {
           // Here exception is thrown.
            LoggedInUserInfo loggedInUserInfo = await _localStorage.GetItemAsync<LoggedInUserInfo>(LocalStorageKey.LoggedInUserInfo);

            if (loggedInUserInfo != null)
            {
                request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", loggedInUserInfo.AccessToken);
            }
        }
        catch (Exception exception)
        {
            Console.WriteLine("LocalStorageSerivce throws exception.");
            Console.WriteLine(exception);
        }

        HttpResponseMessage httpResponseMessage = await base.SendAsync(request, cancellationToken);

        return httpResponseMessage;
    }
}
```

It throws the following exception for **Blazor Server:**

```C#
System.InvalidOperationException: JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId) in Microsoft.AspNetCore.Components.Server.dll:token 0x60002a4+0x25
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args) in Microsoft.JSInterop.dll:token 0x600003a+0xda
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](String identifier, CancellationToken cancellationToken, Object[] args) in Microsoft.JSInterop.dll:token 0x6000038+0x0
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeAsync[TValue](IJSRuntime jsRuntime, String identifier, CancellationToken cancellationToken, Object[] args) in Microsoft.JSInterop.dll:token 0x6000048+0xe
   at Blazored.LocalStorage.BrowserStorageProvider.GetItemAsync(String key, Nullable`1 cancellationToken) in D:\GitHub\LocalStorage\src\Blazored.LocalStorage\BrowserStorageProvider.cs:line 23
   at Blazored.LocalStorage.LocalStorageService.GetItemAsync[T](String key, Nullable`1 cancellationToken) in D:\GitHub\LocalStorage\src\Blazored.LocalStorage\LocalStorageService.cs:line 59
   at MauiBlazor.Shared.Common.AuthorizationDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\GitHub\LocalStorage\samples\MauiBlazor.Shared\Common\AuthorizationDelegatingHandler.cs:line 31
```
and trows following exception for **.NET MAUI Blazor:**

```C#
System.NullReferenceException: Object reference not set to an instance of an object.
[DOTNET]    at Microsoft.AspNetCore.Components.WebView.Services.WebViewJSRuntime.BeginInvokeJS(Int64 taskId, String identifier, String argsJson, JSCallResultType resultType, Int64 
[DOTNET] targetInstanceId) in Microsoft.AspNetCore.Components.WebView.dll:token 0x6000113+0x0
[DOTNET]    at Microsoft.JSInterop.JSRuntime.InvokeAsync[String](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args) in Microsoft.JSInter
[DOTNET] op.dll:token 0x600003a+0x10a
[DOTNET]    at Microsoft.JSInterop.JSRuntime.InvokeAsync[String](String identifier, CancellationToken cancellationToken, Object[] args) in Microsoft.JSInterop.dll:token 0x6000038+0x0
[DOTNET]    at Microsoft.JSInterop.JSRuntimeExtensions.InvokeA
[DOTNET] sync[String](IJSRuntime jsRuntime, String identifier, CancellationToken cancellationToken, Object[] args) in Microsoft.JSInterop.dll:token 0x6000048+0xe
[DOTNET]    at Microsoft.JSInterop.JSRuntimeExtens07-16 00:29:47.884 I/DOTNET  (24839):    at Blazored.LocalStorage.BrowserStorageProvider.GetItemAsync(String key, Nullable`1 cancellationToke
[DOTNET] n) in Blazored.LocalStorage.dll:token 0x6000005+0x24
[DOTNET]    at Blazored.LocalStorage.LocalStorageService.<GetItemAsync>d__5`1[[MauiBlazor.Shared.Models.IdentityModels.LoggedInUserInfo, MauiBlazor.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].
[DOTNET] MoveNext() in Blazored.LocalStorage.dll:token 0x6000082+0x29
[DOTNET]    at MauiBlazor.Shared.Extensions.LocalStorageServiceExtensions.GetUserInfoAsync(ILocalStorageService localStorage) in D:\GitHub\CleanArchitecture\src\ClientApps\MauiBlazor.Shared\Extensions\Loc
[DOTNET] alStorageServiceExtensions.cs:line 19
[DOTNET]    at MauiBlazor.Shared.Common.AuthorizationDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\GitHub\CleanArchitecture\src\ClientApps\MauiBlazor.Shared\Common\Authorizat
[DOTNET] ionDelegatingHandler.cs:line 30
[DOTNET]    at System.Net.Http.Ht
[DOTNET] tpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in System.Net.Http
[DOTNET]    at MauiBlazor.Shared.Services.UserService.LoginAsync(LoginModel loginModel) in D:\GitHub\CleanArchitecture\src\ClientApps\MauiBlazor.Shared\Services\UserService.cs:line 128
[DOTNET]    at MauiBlazorApp.Components.IdentityComponents.Log
[DOTNET] inComponent.HandleValidSubmitAsync() in D:\GitHub\CleanArchitecture\src\ClientApps\MauiBlazorApp\MauiBlazorApp\Components\IdentityComponents\LoginComponent.razor.cs:line 51
```
**Is there any workaround so that we can access local storage inside `DelegatingHandler`?**

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Please share a minimalistic repro project hosted in GitHub, which demonstrates the problem. That will help us investigate this further.

**Comment by TanvirArjel** [comment]
@mkArtakMSFT Here is the repository: https://github.com/TanvirArjel/CleanArchitecture . Please run the `MauiBlazorApp` project, submit the login form and inspect the Deletegating Handler.

**Comment by mkArtakMSFT** [comment]
Thanks @TanvirArjel. We don't look at customer projects, rather are interested in a project based on a new project and with minimal set of changes on top of it which are required to mimic the behavior in question. Please provide such a repro so that we can investigate further.

**Comment by TanvirArjel** [comment]
@mkArtakMSFT Okay! I shall provide you a minimal repo soon.

**Comment by TanvirArjel** [comment]
@mkArtakMSFT I am somewhat busy these days that's why it is being delayed. I shall provide the minimal app to reproduce the issue soon.

**Comment by TanvirArjel** [comment]
@mkArtakMSFT Thank you for your patience. Here is the Minimal Repo (https://github.com/TanvirArjel/LocalStorageInsideDL). To reproduce the error, just run the app and click on the `Products` menu.

**Comment by 3DSX** [comment]
Isn't local storage just available for browsers?

**Comment by TanvirArjel** [comment]
@3DSX MAUI blazor runs on web view.

**Comment by enetstudio** [comment]
@TanvirArjel, I think the error message is clear, and incidentally, it has got nothing to do with MAUI... How can you resolve this issue? The following code snippet describes one way to do that:

AuthorizationDelegatingHandler
------------------------------------
    public class AuthorizationDelegatingHandler : DelegatingHandler
    {
        //private readonly ILocalStorageService _localStorage;

        //public AuthorizationDelegatingHandler(ILocalStorageService localStorage)
        //{
        //    _localStorage = localStorage;
        //}

        public AuthorizationDelegatingHandler()
        {
            
        }


        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            if (request == null)
            {
                throw new ArgumentNullException(nameof(request));
            }

            //string jwtKey = "UserJwt";

            // This line thrown exception in Blazor Server and MAUI Blazor
            // Exception is: JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered.
            // When prerendering is enabled, JavaScript interop calls can only be performed during the 
            //string jwt = await _localStorage.GetItemAsync<string>(jwtKey);

            //if (!string.IsNullOrWhiteSpace(jwt))
            //{
            //    request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", jwt);
            //}

            HttpResponseMessage httpResponseMessage = await base.SendAsync(request, cancellationToken);

            return httpResponseMessage;
        }
     }

ProductsComponent
-----------------------

    public partial class ProductsComponent
    {
        [Inject]
        private TestProductService TestLoginService { get; set; }

        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                List<ProductModel> productModels = await TestLoginService.GetListAsync();
            }
        }
     }

TestProductService
---------------------

      public class TestProductService
    {
        private readonly HttpClient _httpClient;
        private readonly ILocalStorageService _localStorage;
        public TestProductService(IHttpClientFactory httpClientFactory, ILocalStorageService localStorage)
        {
            _httpClient = httpClientFactory.CreateClient("TestApi");
            _localStorage = localStorage;
        }

        public async Task<List<ProductModel>> GetListAsync()
        {
            string jwtKey = "UserJwt";

            string jwt = await _localStorage.GetItemAsync<string>(jwtKey);

            if (!string.IsNullOrWhiteSpace(jwt))
            {
               _httpClient.DefaultRequestHeaders.Add("Bearer", jwt);
            }

            List<ProductModel> productModels = await _httpClient.GetFromJsonAsync<List<ProductModel>>("api/products");
            return productModels;
        }
    }

As you can see. I add the Jwt token via the HttpClient. I use JSInterop after the app was rendered, when JSRuntime is available. Incidentally, it seems to me to be a good pattern (that's the way Steve Sanderson does in his samples) to provide the Jwt token immediately before you perform the HTTP call.  

Note that you'll get a new error (500) relating to the lack of a Web Api end point (Your code is partial: https://github.com/dotnet/aspnetcore/issues/34421#issuecomment-890006549). However, this is not relevant to the current issue. 

Note: I'm not a developer, so you should look for blessing from the Blazor team.
