### ISSUE TITLE
HttpHeaderParser can't parse Content-Type if boundary contains = character without double quotes

### ISSUE THREAD

**Issue by magicxor** [dotnet/aspnetcore#34454]
### Describe the bug
`multipart/form-data` binding doesn't work if `boundary` contains `=` without double quotes, e.g. `Content-Type: multipart/form-data; boundary=--===1626454906178===`

### To Reproduce

Create an API project, add the following controller

```csharp
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace WebApp2
{
    public class ApiController : Controller
    {
        [HttpPost]
        public IActionResult Upload(string someId, IFormFile someFile)
        {
            if (someId == null && someFile == null)
            {
                return BadRequest(@$"¯\_(ツ)_/¯");
            }
            else
            {
                return Ok($"someId={someId}, someFile={someFile}");
            }
        }
    }
}
```
and send the following HTTP request using Jetbrains Rider:
```
POST /Api/Upload HTTP/1.1
Host: localhost:80
User-Agent: PostmanRuntime/7.28.1
Accept: */*
Cache-Control: no-cache
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Type: multipart/form-data; boundary=--===1626454906178===

----===1626454906178===
Content-Disposition: form-data; name="someFile"; filename="someFile.xml"
Content-Type: application/xml

<xml/>
----===1626454906178===
Content-Disposition: form-data; name="someId"

235891193
----===1626454906178===--

```
Actual result:
```
¯\_(ツ)_/¯

Response code: 400 (Bad Request)
```
Expected result:
```
someId=235891193, someFile=Microsoft.AspNetCore.Http.FormFile

Response code: 200 (OK)
```

### Exceptions (if any)

```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMA8TK97UQL5", Request id "0HMA8TK97UQL5:00000002": An unhandled exception was thrown by the application.
      System.FormatException: The header contains invalid values at index 0: 'multipart/form-data; boundary=--=1626454906178'
         at Microsoft.Net.Http.Headers.HttpHeaderParser`1.ParseValue(StringSegment value, Int32& index)
         at Microsoft.Net.Http.Headers.MediaTypeHeaderValue.Parse(StringSegment input)
         at WebApp2.ApiController.Upload(String someId, IFormFile someFile) in /src/ApiController.cs:line 12
         at lambda_method1(Closure , Object , Object[] )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### Further technical details
- ASP.NET Core version: 
`3.1, 5.0, 6.0`
- Include the output of `dotnet --info`
```
root@c01f8a8b2585:/app# dotnet --info

Host (useful for support):
  Version: 5.0.8
  Commit:  35964c9215

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by Tratcher** [comment]
It is invalid.
https://datatracker.ietf.org/doc/html/rfc7231#section-3.1.1.1

media-type = type "/" subtype *( OWS ";" OWS parameter )
     type       = token
     subtype    = token

   The type/subtype MAY be followed by parameters in the form of
   name=value pairs.

     parameter      = token "=" ( token / quoted-string )

https://datatracker.ietf.org/doc/html/rfc7230#section-3.2.6

Delimiters are chosen
   from the set of US-ASCII visual characters not allowed in a token
   (DQUOTE and "(),/:;<=>?@[\]{}").

     token          = 1*tchar

     tchar          = "!" / "#" / "$" / "%" / "&" / "'" / "*"
                    / "+" / "-" / "." / "^" / "_" / "`" / "|" / "~"
                    / DIGIT / ALPHA
                    ; any VCHAR, except delimiters

**Comment by magicxor** [comment]
Thank you for your response. This RFC document was not clear enough for me. And such headers worked in ASP.NET MVC 5, which made me have doubts.
