### ISSUE TITLE
using ProtectKeysWithDpapiNG with certificate fails after creating new key storage

### ISSUE THREAD

**Issue by NtFreX** [dotnet/aspnetcore#3449]
When I configure data protection with `ProtectKeysWithDpapiNG` and use an certificate I get an exception.

    System.Security.Cryptography.CryptographicException: Encryption failed.
       at Microsoft.AspNetCore.Cryptography.UnsafeNativeMethods.ThrowExceptionForNCryptStatusImpl(Int32 ntstatus)
       at Microsoft.AspNetCore.DataProtection.Cng.DpapiSecretSerializerHelper.ProtectWithDpapiNGCore(NCryptDescriptorHandle protectionDescriptorHandle, Byte* pbData, UInt32 cbData)
       at Microsoft.AspNetCore.DataProtection.Cng.DpapiSecretSerializerHelper.ProtectWithDpapiNG(ISecret secret, NCryptDescriptorHandle protectionDescriptorHandle)
       at Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiNGXmlEncryptor.Encrypt(XElement plaintextElement)
       at Microsoft.AspNetCore.DataProtection.XmlEncryption.XmlEncryptionExtensions.EncryptIfNecessary(IXmlEncryptor encryptor, XElement element)
       at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.CreateNewKey(Guid keyId, DateTimeOffset creationDate, DateTimeOffset activationDate, DateTimeOffset expirationDate)
       at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.CreateNewKey(DateTimeOffset activationDate, DateTimeOffset expirationDate)
       at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
       at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now)
       at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow)
       at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
       at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Protect(IDataProtector protector, String plaintext)
       at NtFreX.Samples.DataProtection.Program.Reproducable() in C:\Users\ftr\Documents\Visual Studio 2017\Projects\NtFreX.Samples\NtFreX.Samples.DataProtection\Program.cs:line 38

I have created the certificate with powershell.

```powershell
New-SelfSignedCertificate -DnsName "ntfrex.samples" -CertStoreLocation "cert:\LocalMachine\My"
       PSParentPath: Microsoft.PowerShell.Security\Certificate::LocalMachine\My

Thumbprint                                Subject
----------                                -------
05871CD628D1D7917E2D8ED76056ACC5829D43A1  CN=ntfrex.samples
```

I can reproduce this behaivor with the following code.

```c#
// creating a new directory is important to ensure nothing is saved somewhere allready
var directory = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
Directory.CreateDirectory(directory);

const string certificateThumbprint = "05871CD628D1D7917E2D8ED76056ACC5829D43A1";

var serviceCollection = new ServiceCollection();

serviceCollection
    .AddDataProtection()
    .SetApplicationName(typeof(Program).FullName)
    .PersistKeysToFileSystem(new DirectoryInfo(directory))
    .ProtectKeysWithDpapiNG($"CERTIFICATE=HashId:{certificateThumbprint.ToUpper()}", DpapiNGProtectionDescriptorFlags.None);

var serviceProvider = serviceCollection.BuildServiceProvider();

var data = "TestData";
var dataProtector = serviceProvider.GetDataProtector("TestDataProtector");
var protectedData = dataProtector.Protect(data);
var unprotectedData = dataProtector.Unprotect(protectedData);

Debug.Assert(data == unprotectedData);
```

I'm using the following nuget packages.

 - Microsoft.AspNetCore.DataProtection v2.1.1
 - Microsoft.Extensions.DependencyInjection v2.1.1

And I target `netcoreapp2.1`

The funny thing is I can get it to work with the following hack. All Debug.Assert's are passing.

```c#
// creating a new directory is important to ensure nothing is saved somewhere allready
var directory = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
Directory.CreateDirectory(directory);

{
    var serviceCollection = new ServiceCollection();

    serviceCollection
        .AddDataProtection()
        .SetApplicationName(typeof(Program).FullName)
        .PersistKeysToFileSystem(new DirectoryInfo(directory))
        .ProtectKeysWithDpapiNG();

    var serviceProvider = serviceCollection.BuildServiceProvider();

    var data = "TestData";
    var dataProtector = serviceProvider.GetDataProtector("TestDataProtector");
    var protectedData = dataProtector.Protect(data);
    var unprotectedData = dataProtector.Unprotect(protectedData);

    Debug.Assert(data == unprotectedData);
}

{
    const string certificateThumbprint = "05871CD628D1D7917E2D8ED76056ACC5829D43A1";

    var serviceCollection = new ServiceCollection();

    serviceCollection
        .AddDataProtection()
        .SetApplicationName(typeof(Program).FullName)
        .PersistKeysToFileSystem(new DirectoryInfo(directory))
        .ProtectKeysWithDpapiNG($"CERTIFICATE=HashId:{certificateThumbprint.ToUpper()}", DpapiNGProtectionDescriptorFlags.None);

    var serviceProvider = serviceCollection.BuildServiceProvider();

    var data = "TestData";
    var dataProtector = serviceProvider.GetDataProtector("TestDataProtector");
    var protectedData = dataProtector.Protect(data);
    var unprotectedData = dataProtector.Unprotect(protectedData);

    Debug.Assert(data == unprotectedData);
}
```

I can reproduce this problem when I configure the data protection to use ProtectKeysWithDpapiNG with an certificate and the key storage has not been setup by ProtectKeysWithDpapiNG with an user before. I can reproduce this when using other key storages.

Is this an bug in the framework?

**Comment by blowdart** [comment]
@GrabYourPitchforks any ideas? You wrote this and it's never changed.

**Comment by EhAron** [comment]
Was this ever solved? Have exact same issue except I created the certificate with OpenSSL per this thread: [https://github.com/aspnet/DataProtection/issues/215#issuecomment-297221456]
Added Cert to Trusted Root and Personal.

**Comment by HaoK** [comment]
@blowdart so I tried this repro out and I consistently get the native encrypt failure regardless of the workaround or not.

**Comment by HaoK** [comment]
Oh this sounds like a dupe of https://github.com/dotnet/aspnetcore/issues/12068 where self signed certs aren't able to be found

**Comment by blowdart** [comment]
OK closing as dupe then

**Comment by alentor** [comment]
Reopening the issue, as I think issue isn't related to #12068.
I have a cert thumbprint that works with 

`ProtectKeysWithCertificate("thumbprint")`, 

when I try to use the same thumbprint with 

`ProtectKeysWithDpapiNG("CERTIFICATE=HashId:thumbprint", DpapiNGProtectionDescriptorFlags.None)` 

I get generic error `Encryption failed.`

```
System.Security.Cryptography.CryptographicException: Encryption failed.
   at Microsoft.AspNetCore.Cryptography.UnsafeNativeMethods.ThrowExceptionForNCryptStatusImpl(Int32 ntstatus)
   at Microsoft.AspNetCore.DataProtection.Cng.DpapiSecretSerializerHelper.ProtectWithDpapiNGCore(NCryptDescriptorHandle protectionDescriptorHandle, Byte* pbData, UInt32 cbData)
   at Microsoft.AspNetCore.DataProtection.Cng.DpapiSecretSerializerHelper.ProtectWithDpapiNG(ISecret secret, NCryptDescriptorHandle protectionDescriptorHandle)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiNGXmlEncryptor.Encrypt(XElement plaintextElement)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.XmlEncryptionExtensions.EncryptIfNecessary(IXmlEncryptor encryptor, XElement element)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.CreateNewKey(Guid keyId, DateTimeOffset creationDate, DateTimeOffset activationDate, DateTimeOffset expirationDate)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.CreateNewKey(DateTimeOffset activationDate, DateTimeOffset expirationDate)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow, Boolean forceRefresh)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRing()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Protect(IDataProtector protector, String plaintext)
   at DataProtection.Helpers.ReceiptsHelper.ProtectReceipts(Dictionary`2& receipts) in D:\src\DataProtection\Helpers\ReceiptsHelper.cs:line 57
```

**Comment by alentor** [comment]
Think issue isn't related to #12068.

I have a cert thumbprint that works with
`
services.AddDataProtection().ProtectKeysWithCertificate("thumbprint")
.PersistKeysToFileSystem(new DirectoryInfo(Path.Combine(Environment.CurrentDirectory, "Keys")));
`,

when I try to use the same thumbprint with 
`
services.AddDataProtection().ProtectKeysWithDpapiNG("CERTIFICATE=HashId:thumbprint",DpapiNGProtectionDescriptorFlags.None)
.PersistKeysToFileSystem(new DirectoryInfo(Path.Combine(Environment.CurrentDirectory, "Keys")));
` 

I get generic error `Encryption failed.`

One more crucial thing to note, **no key is created locally when using** `ProtectKeysWithDpapiNG`

In my opinion the probelm 

```
System.Security.Cryptography.CryptographicException: Encryption failed.
   at Microsoft.AspNetCore.Cryptography.UnsafeNativeMethods.ThrowExceptionForNCryptStatusImpl(Int32 ntstatus)
   at Microsoft.AspNetCore.DataProtection.Cng.DpapiSecretSerializerHelper.ProtectWithDpapiNGCore(NCryptDescriptorHandle protectionDescriptorHandle, Byte* pbData, UInt32 cbData)
   at Microsoft.AspNetCore.DataProtection.Cng.DpapiSecretSerializerHelper.ProtectWithDpapiNG(ISecret secret, NCryptDescriptorHandle protectionDescriptorHandle)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiNGXmlEncryptor.Encrypt(XElement plaintextElement)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.XmlEncryptionExtensions.EncryptIfNecessary(IXmlEncryptor encryptor, XElement element)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.CreateNewKey(Guid keyId, DateTimeOffset creationDate, DateTimeOffset activationDate, DateTimeOffset expirationDate)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.CreateNewKey(DateTimeOffset activationDate, DateTimeOffset expirationDate)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.ICacheableKeyRingProvider.GetCacheableKeyRing(DateTimeOffset now)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRingCore(DateTime utcNow, Boolean forceRefresh)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.GetCurrentKeyRing()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[] plaintext)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Protect(IDataProtector protector, String plaintext)
   at DataProtection.Helpers.ReceiptsHelper.ProtectReceipts(Dictionary`2& receipts) in D:\src\DataProtection\Helpers\ReceiptsHelper.cs:line 57
```
