### ISSUE TITLE
BadHttpRequestException: Reading the request body timed out due to data arriving too slowly

### ISSUE THREAD

**Issue by jrichardsz** [dotnet/aspnetcore#34516]
### Describe the bug
Netcore rest api shows this error when the service is stress tested: **Reading the request body timed out due to data arriving too slowly. See MinRequestBodyDataRate**

### To Reproduce
- Stress the http resource using tools like jmeter or soap-ui

### Exceptions (if any)

``` 
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Reading the request body timed out due to data arriving too slowly. See MinRequestBodyDataRate.
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### Further technical details
- ASP.NET Core version 3.1
- Docker
```
FROM mcr.microsoft.com/dotnet/aspnet:3.1 AS base
FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build
```

### Precedents

There are two equal issues which were closed :(

- https://github.com/dotnet/aspnetcore/issues/4707
- https://github.com/dotnet/aspnetcore/issues/16861

**Comment by BrennanConroy** [comment]
This is an expected error if you're doing stress testing that sends data to the server very slowly.
Or if you open too many new connections and overload the server so it can't process them all in time.

This error can be a symptom of thread pool starvation.

**Comment by shirhatti** [comment]
Can you try running your app with [dotnet counters](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-counters) and collecting event counters? That'll help validate our hypotheses on starvation.

The simplest thing to try is: `dotnet-counters collect --format json --counters System.Runtime,Microsoft.AspNetCore.Hosting -- dotnet myapp.dll`

**Comment by jrichardsz** [comment]
> This is an expected error if you're doing stress testing that sends data to the server very slowly.
> Or if you open too many new connections and overload the server so it can't process them all in time.
> 
> This error can be a symptom of thread pool starvation.

**"stress testing that sends data to the server very slowly"...** that is not my case. My rest endpoint supports 500 invocations in a **sequence** mode with an average response time  of **1500** milliseconds. But if I try the **same endpoint** but in **parallel** mode, does not support even 20 users. More than 20 users, the indicated error begins to appear

If my goal is **Set up my c# rest api with optimal parameters to support high user concurrency**  how Can I increase the thread pool to prevent **starvation**?

**Comment by jrichardsz** [comment]
> Can you try running your app with [dotnet counters](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-counters) and collecting event counters? That'll help validate our hypotheses on starvation.
> 
> The simplest thing to try is: `dotnet-counters collect --format json --counters System.Runtime,Microsoft.AspNetCore.Hosting -- dotnet myapp.dll`

I will configure this on my dockerfile. Does this create a file called counter.json?

Thanks for your time

**Comment by BrennanConroy** [comment]
> Does this create a file called counter.json?

Yep, looking forward to the results!
