### ISSUE TITLE
`LoggingConnectionMiddlewareCanBeAddedBeforeAndAfterHttps()` is flaky

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#34561]
## Failing Test(s)

- `LoggingConnectionMiddlewareCanBeAddedBeforeAndAfterHttps()`

## Error Message

```text
System.IO.IOException :  Received an unexpected EOF or 0 bytes from the transport stream.
```

## Stacktrace

<details>

```text
     at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|187_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize) in System.Net.Security.dll:token 0x600030d+0x8b
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter) in System.Net.Security.dll:token 0x60002f1+0x8c
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm) in System.Net.Security.dll:token 0x60002f0+0x299
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.TestTransport.InMemoryHttpClientSlim.GetStream(Stream rawStream, Uri requestUri, Boolean validateCertificate) in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/TestTransport/InMemoryHttpClientSlim.cs:line 127
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.TestTransport.InMemoryHttpClientSlim.GetStringAsync(Uri requestUri, Boolean validateCertificate) in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/TestTransport/InMemoryHttpClientSlim.cs:line 35
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.TestTransport.InMemoryHttpClientSlim.GetStringAsync(String requestUri, Boolean validateCertificate) in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/TestTransport/InMemoryHttpClientSlim.cs:line 30
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 90
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.LoggingConnectionMiddlewareTests.LoggingConnectionMiddlewareCanBeAddedBeforeAndAfterHttps() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/LoggingConnectionMiddlewareTests.cs:line 33
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.LoggingConnectionMiddlewareTests.LoggingConnectionMiddlewareCanBeAddedBeforeAndAfterHttps() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/LoggingConnectionMiddlewareTests.cs:line 35
--- End of stack trace from previous location ---
```
</details>

## Logs

See https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-heads-main-cecc8bbbfe7d4877b4/InMemory.FunctionalTests--net6.0/console.1372964f.log?sv=2019-07-07 if more context is needed.

<details>

```text
 | [0.003s] TestLifetime Information: Starting test LoggingConnectionMiddlewareCanBeAddedBeforeAndAfterHttps at 2021-07-20T00:23:12
 | [0.007s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting starting
 | [2.050s] Microsoft.Hosting.Lifetime Information: Now listening on: https://127.0.0.1:0
 | [2.050s] Microsoft.AspNetCore.Hosting.Diagnostics Debug: Loaded hosting startup assembly InMemory.FunctionalTests
 | [2.050s] Microsoft.Hosting.Lifetime Information: Application started. Press Ctrl+C to shut down.
 | [2.050s] Microsoft.Hosting.Lifetime Information: Hosting environment: Production
 | [2.050s] Microsoft.Hosting.Lifetime Information: Content root path: /private/tmp/helix/working/C8A20A4C/w/B1560994/e/
 | [2.050s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting started
 | [6.375s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMAB2I8425HF" accepted.
 | [10.059s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMAB2I8425HF" started.
 | [10.342s] Microsoft.AspNetCore.Server.Kestrel.Core.Internal.LoggingConnectionMiddleware Debug: ReadAsync[169]
 |                                                                                                16 03 01 00 A4 01 00 00  A0 03 03 60 F6 17 72 E6   ....Â¤... Â ..`Ã¶.rÃ¦
 |                                                                                                BA 0B D4 DE 65 26 E4 33  10 81 06 EC 46 4E 2E 03   Âº.Ã”Ãže&Ã¤3 ...Ã¬FN..
 |                                                                                                AB 36 59 00 EC E1 C2 65  58 0A A2 00 00 2C 00 FF   Â«6Y.Ã¬Ã¡Ã‚e X.Â¢..,.Ã¿
 |                                                                                                C0 2C C0 2B C0 24 C0 23  C0 0A C0 09 C0 08 C0 30   Ã€,Ã€+Ã€$Ã€# Ã€.Ã€.Ã€.Ã€0
 |                                                                                                C0 2F C0 28 C0 27 C0 14  C0 13 C0 12 00 9D 00 9C   Ã€/Ã€(Ã€'Ã€. Ã€.Ã€.....
 |                                                                                                00 3D 00 3C 00 35 00 2F  00 0A 01 00 00 4B 00 00   .=.<.5./ .....K..
 |                                                                                                00 0E 00 0C 00 00 09 6C  6F 63 61 6C 68 6F 73 74   .......l ocalhost
 |                                                                                                00 0A 00 08 00 06 00 17  00 18 00 19 00 0B 00 02   ........ ........
 |                                                                                                01 00 00 0D 00 12 00 10  04 01 02 01 05 01 06 01   ........ ........
 |                                                                                                04 03 02 03 05 03 06 03  00 05 00 05 01 00 00 00   ........ ........
 |                                                                                                00 00 12 00 00 00 17 00  00                        ........ .
 | [17.933s] Microsoft.AspNetCore.Server.Kestrel.Core.Internal.LoggingConnectionMiddleware Debug: WriteAsync[1242]
 |                                                                                                16 03 03 00 59 02 00 00  55 03 03 60 F6 17 7E 4E   ....Y... U..`Ã¶.~N
 |                                                                                                E1 12 DC 6D 40 4A 7C C6  02 01 16 4A B8 B2 30 AD   Ã¡.Ãœm@J|Ã† ...JÂ¸Â²0Â­
 |                                                                                                01 A2 0F 77 91 DD C1 33  C1 89 2F 20 07 03 83 BC   .Â¢.w.ÃÃ3 Ã./ ...Â¼
 |                                                                                                11 38 0D BA 24 4C ED C5  FF 30 EB 00 9A A8 E6 F1   .8.Âº$LÃ­Ã… Ã¿0Ã«..Â¨Ã¦Ã±
 |                                                                                                6C B8 6D 7C F4 D1 FC 92  C6 07 D3 5E C0 30 00 00   lÂ¸m|Ã´Ã‘Ã¼. Ã†.Ã“^Ã€0..
 |                                                                                                0D 00 00 00 00 FF 01 00  01 00 00 17 00 00 16 03   .....Ã¿.. ........
 |                                                                                                03 03 1C 0B 00 03 18 00  03 15 00 03 12 30 82 03   ........ .....0..
 |                                                                                                0E 30 82 01 F6 A0 03 02  01 02 02 10 34 02 16 F3   .0..Ã¶Â .. ....4..Ã³
 |                                                                                                98 53 2E AE 4F 57 F5 F4  4C 6F D0 9F 30 0D 06 09   .S.Â®OWÃµÃ´ LoÃ.0...
 |                                                                                                2A 86 48 86 F7 0D 01 01  0B 05 00 30 14 31 12 30   *.H.Ã·... ...0.1.0
 |                                                                                                10 06 03 55 04 03 0C 09  6C 6F 63 61 6C 68 6F 73   ...U.... localhos
 |                                                                                                74 30 1E 17 0D 32 30 30  32 32 31 31 39 30 31 33   t0...200 22119013
 |                                                                                                37 5A 17 0D 32 35 30 32  32 31 31 39 30 31 33 37   7Z..2502 21190137
 |                                                                                                5A 30 14 31 12 30 10 06  03 55 04 03 0C 09 6C 6F   Z0.1.0.. .U....lo
 |                                                                                                63 61 6C 68 6F 73 74 30  82 01 22 30 0D 06 09 2A   calhost0 .."0...*
 |                                                                                                86 48 86 F7 0D 01 01 01  05 00 03 82 01 0F 00 30   .H.Ã·.... .......0
 |                                                                                                82 01 0A 02 82 01 01 00  E5 95 2B 82 12 F1 D2 5A   ........ Ã¥.+..Ã±Ã’Z
 |                                                                                                64 04 AD DA 2B D9 11 81  09 B7 05 82 F9 53 07 83   d.Â­Ãš+Ã™.. .Â·..Ã¹S..
 |                                                                                                61 18 C0 28 53 11 C7 6C  29 88 B6 92 DC 62 BE 4C   a.Ã€(S.Ã‡l ).Â¶.ÃœbÂ¾L
 |                                                                                                7E 3A 15 5D AE 4E DD 2E  34 F7 6B B6 F9 BA ED 72   ~:.]Â®NÃ. 4Ã·kÂ¶Ã¹ÂºÃ­r
 |                                                                                                9C 99 39 F0 B3 C2 83 8F  83 16 59 EC B7 AC 4B D9   ..9Ã°Â³Ã‚.. ..YÃ¬Â·Â¬KÃ™
 |                                                                                                E7 46 D3 50 69 52 A2 38  67 03 5C 5A 41 14 96 99   Ã§FÃ“PiRÂ¢8 g.\ZA...
 |                                                                                                7B CD 41 BA 20 49 81 B0  B7 4C AD 98 87 7B 82 04   {ÃAÂº I.Â° Â·LÂ­..{..
 |                                                                                                F2 CE CD 60 2C 28 B7 F9  42 5A DF 74 66 4F 30 D7   Ã²ÃŽÃ`,(Â·Ã¹ BZÃŸtfO0Ã—
 |                                                                                                17 1B 04 41 4C 67 5B CE  EC 7D 32 64 BB E7 74 D6   ...ALg[ÃŽ Ã¬}2dÂ»Ã§tÃ–
 |                                                                                                BB F3 06 11 6C 34 35 3C  75 1C 9A 94 59 A5 02 D0   Â»Ã³..l45< u...YÂ¥.Ã
 |                                                                                                52 AF 39 E2 6C A3 7C F7  CA 8B 6C A7 14 39 05 80   RÂ¯9Ã¢lÂ£|Ã· ÃŠ.lÂ§.9..
 |                                                                                                5F 85 7E 15 29 79 A0 F3  8B EE 72 BD D1 90 CF FF   _.~.)yÂ Ã³ .Ã®rÂ½Ã‘.ÃÃ¿
 |                                                                                                C4 F5 D6 16 04 0E 38 69  B0 25 F0 10 2C 5C 11 0D   Ã„ÃµÃ–...8i Â°%Ã°.,\..
 |                                                                                                69 C5 50 E3 24 A6 E7 50  9A DE 7F E4 4A 8E 18 97   iÃ…PÃ£$Â¦Ã§P .Ãž.Ã¤J...
 |                                                                                                A9 E1 BA 77 80 4B 8C 84  2C 28 E3 F1 B5 56 D7 05   Â©Ã¡Âºw.K.. ,(Ã£Ã±ÂµVÃ—.
 |                                                                                                A5 94 B0 79 60 8E 72 D6  59 8B 00 F7 A6 CD 5E 38   Â¥.Â°y`.rÃ– Y..Ã·Â¦Ã^8
 |                                                                                                D8 94 A9 47 19 88 76 A9  02 03 01 00 01 A3 5C 30   Ã˜.Â©G..vÂ© .....Â£\0
 |                                                                                                5A 30 0E 06 03 55 1D 0F  01 01 FF 04 04 03 02 04   Z0...U.. ..Ã¿.....
 |                                                                                                B0 30 14 06 03 55 1D 11  04 0D 30 0B 82 09 6C 6F   Â°0...U.. ..0...lo
 |                                                                                                63 61 6C 68 6F 73 74 30  13 06 03 55 1D 25 04 0C   calhost0 ...U.%..
 |                                                                                                30 0A 06 08 2B 06 01 05  05 07 03 01 30 1D 06 03   0...+... ....0...
 |                                                                                                55 1D 0E 04 16 04 14 63  D2 2C A8 20 CD 65 F1 AC   U......c Ã’,Â¨ ÃeÃ±Â¬
 |                                                                                                02 E2 A1 7E 22 0F DE 8A  80 57 BE 30 0D 06 09 2A   .Ã¢Â¡~".Ãž. .WÂ¾0...*
 |                                                                                                86 48 86 F7 0D 01 01 0B  05 00 03 82 01 01 00 A6   .H.Ã·.... .......Â¦
 |                                                                                                D1 73 CA A3 2F 77 78 A4  69 BB C7 81 7F 2D 22 2D   Ã‘sÃŠÂ£/wxÂ¤ iÂ»Ã‡..-"-
 |                                                                                                46 8E 0D 2F C3 D2 48 3F  45 93 55 61 FB 6E 7E 9D   F../ÃƒÃ’H? E.UaÃ»n~.
 |                                                                                                1C 56 5A 9A E9 CD D3 DD  AD 7E AB 6C C5 36 78 85   .VZ.Ã©ÃÃ“Ã Â­~Â«lÃ…6x.
 |                                                                                                B0 97 F2 01 B4 44 AF E6  3C C0 67 A4 D8 35 50 76   Â°.Ã².Â´DÂ¯Ã¦ <Ã€gÂ¤Ã˜5Pv
 |                                                                                                DD E5 13 6B BB DA 93 F2  E9 DB EE D7 4C 73 EA 3A   ÃÃ¥.kÂ»Ãš.Ã² Ã©Ã›Ã®Ã—LsÃª:
 |                                                                                                66 D7 DC 2A 9D 70 F1 00  6B 2B 92 F3 9E 57 36 E6   fÃ—Ãœ*.pÃ±. k+.Ã³.W6Ã¦
 |                                                                                                2C AF 7A 99 2A 71 1F F3  1B CF 2E A5 66 E8 1B 27   ,Â¯z.*q.Ã³ .Ã.Â¥fÃ¨.'
 |                                                                                                BD 97 D5 5C E3 95 22 C5  EF 58 8C 62 C7 94 73 E3   Â½.Ã•\Ã£."Ã… Ã¯X.bÃ‡.sÃ£
 |                                                                                                4E 22 BE DE F1 81 1E CF  14 45 9E B5 B1 0F B9 92   N"Â¾ÃžÃ±..Ã .E.ÂµÂ±.Â¹.
 |                                                                                                E0 46 DE 9C A5 DF 3B B0  1A A8 2F 1E E7 D1 CF EC   Ã FÃž.Â¥ÃŸ;Â° .Â¨/.Ã§Ã‘ÃÃ¬
 |                                                                                                FD A8 50 91 99 37 8E 58  6D BB 06 1F BE 26 FA D1   Ã½Â¨P..7.X mÂ»..Â¾&ÃºÃ‘
 |                                                                                                7A 84 49 7F E1 0C 98 1A  58 08 01 33 C9 2E C8 0A   z.I.Ã¡... X..3Ã‰.Ãˆ.
 |                                                                                                57 82 06 E4 AC C6 E9 A4  04 F5 2B 2D 63 A4 D3 40   W..Ã¤Â¬Ã†Ã©Â¤ .Ãµ+-cÂ¤Ã“@
 |                                                                                                76 09 94 C2 BB DC 1F AE  CD 2D 7B 26 87 A9 C1 76   v..Ã‚Â»Ãœ.Â® Ã-{&.Â©Ãv
 |                                                                                                0B E8 C2 3C B0 7B 9C BD  9D 18 BC 12 67 10 CA A0   .Ã¨Ã‚<Â°{.Â½ ..Â¼.g.ÃŠÂ 
 |                                                                                                AD 85 7C 01 96 3F E2 93  B4 6D 57 6A 5D B7 72 16   Â­.|..?Ã¢. Â´mWj]Â·r.
 |                                                                                                03 03 01 4D 0C 00 01 49  03 00 17 41 04 38 C0 4F   ...M...I ...A.8Ã€O
 |                                                                                                0D 6B 50 23 9E 12 50 37  29 6F AD 4D 4A 8E EB D9   .kP#..P7 )oÂ­MJ.Ã«Ã™
 |                                                                                                5A 58 F8 C7 AE 32 9E 03  0B A3 03 51 51 F2 B7 39   ZXÃ¸Ã‡Â®2.. .Â£.QQÃ²Â·9
 |                                                                                                52 A0 F1 73 D6 2D 33 E9  60 1A 48 6F D2 E6 02 57   RÂ Ã±sÃ–-3Ã© `.HoÃ’Ã¦.W
 |                                                                                                D9 58 F0 73 E1 5F 23 5C  0B CD 9E 06 DC 04 01 01   Ã™XÃ°sÃ¡_#\ .Ã..Ãœ...
 |                                                                                                00 B0 27 52 11 A6 5E 7A  8D 55 EE 6E AE 0C 7D D9   .Â°'R.Â¦^z .UÃ®nÂ®.}Ã™
 |                                                                                                09 FF 64 A1 8B 27 23 EE  BA 9F 48 0B 3B 71 A1 82   .Ã¿dÂ¡.'#Ã® Âº.H.;qÂ¡.
 |                                                                                                BE 5A C2 2A 2B 25 60 84  40 B7 E3 39 C1 C0 73 94   Â¾ZÃ‚*+%`. @Â·Ã£9ÃÃ€s.
 |                                                                                                E8 8A 71 FD C2 07 41 5D  50 5F 66 6D 17 CB 03 66   Ã¨.qÃ½Ã‚.A] P_fm.Ã‹.f
 |                                                                                                56 68 66 7E DE 14 0F 3A  BA 23 CA 81 47 6C B8 AB   Vhf~Ãž..: Âº#ÃŠ.GlÂ¸Â«
 |                                                                                                28 9A 2D 38 35 E5 D7 BC  A4 AF ED D2 C5 7F 7E 2E   (.-85Ã¥Ã—Â¼ Â¤Â¯Ã­Ã’Ã….~.
 |                                                                                                9B FB 5D 6B F7 CB 6A 3E  C4 23 E5 12 04 7F B7 90   .Ã»]kÃ·Ã‹j> Ã„#Ã¥...Â·.
 |                                                                                                95 6A 4B D7 F6 AE E1 11  FB 1D BE 1F 1E 73 97 1B   .jKÃ—Ã¶Â®Ã¡. Ã».Â¾..s..
 |                                                                                                02 91 6D 8F EB F8 11 56  4F 0A 3D 7C AC DF CC B3   ..m.Ã«Ã¸.V O.=|Â¬ÃŸÃŒÂ³
 |                                                                                                1E B6 85 0E 2E D4 DB BA  06 33 BA 41 76 A5 C8 85   .Â¶...Ã”Ã›Âº .3ÂºAvÂ¥Ãˆ.
 |                                                                                                A5 06 6E 76 D4 61 9F 66  4F 0D 56 4A 93 F2 09 4A   Â¥.nvÃ”a.f O.VJ.Ã².J
 |                                                                                                86 D4 9F AB 3A 50 52 59  BF 5B 25 9F 7C F9 79 8C   .Ã”.Â«:PRY Â¿[%.|Ã¹y.
 |                                                                                                5A FD F8 39 8E 99 CB 59  B9 2E 26 EA B3 98 86 D4   ZÃ½Ã¸9..Ã‹Y Â¹.&ÃªÂ³..Ã”
 |                                                                                                E8 1C A7 DF 98 8F 11 2B  A2 14 C3 6C 35 E6 8E 74   Ã¨.Â§ÃŸ...+ Â¢.Ãƒl5Ã¦.t
 |                                                                                                30 D9 50 B1 8F A2 80 ED  5F 70 6C 3F 0E F7 27 59   0Ã™PÂ±.Â¢.Ã­ _pl?.Ã·'Y
 |                                                                                                6D E6 29 BF 0E DD 01 4C  93 92 96 E1 1B F0 93 92   mÃ¦)Â¿.Ã.L ...Ã¡.Ã°..
 |                                                                                                8F 16 03 03 00 04 0E 00  00 00                     ........ ..
 | [20.479s] Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware Debug: Authentication of the HTTPS connection timed out.
 | [20.535s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMAB2I8425HF" stopped.
 | [21.117s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting stopping
 | [21.233s] Microsoft.Hosting.Lifetime Information: Application is shutting down...
 | [21.943s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting stopped
 | [22.080s] Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.LoggingConnectionMiddlewareTests Error: Test threw an exception.
 | System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
 |    at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|187_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize) in System.Net.Security.dll:token 0x600030d+0x8b
 |    at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter) in System.Net.Security.dll:token 0x60002f1+0x8c
 |    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm) in System.Net.Security.dll:token 0x60002f0+0x299
 |    at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.TestTransport.InMemoryHttpClientSlim.GetStream(Stream rawStream, Uri requestUri, Boolean validateCertificate) in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/TestTransport/InMemoryHttpClientSlim.cs:line 127
 |    at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.TestTransport.InMemoryHttpClientSlim.GetStringAsync(Uri requestUri, Boolean validateCertificate) in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/TestTransport/InMemoryHttpClientSlim.cs:line 35
 |    at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.TestTransport.InMemoryHttpClientSlim.GetStringAsync(String requestUri, Boolean validateCertificate) in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/TestTransport/InMemoryHttpClientSlim.cs:line 30
 |    at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 90
 |    at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.LoggingConnectionMiddlewareTests.LoggingConnectionMiddlewareCanBeAddedBeforeAndAfterHttps() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/LoggingConnectionMiddlewareTests.cs:line 33
 |    at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.LoggingConnectionMiddlewareTests.LoggingConnectionMiddlewareCanBeAddedBeforeAndAfterHttps() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/LoggingConnectionMiddlewareTests.cs:line 35
 |    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
 | --- End of stack trace from previous location ---
 |    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
 |    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 96
 | [24.078s] TestLifetime Information: Finished test LoggingConnectionMiddlewareCanBeAddedBeforeAndAfterHttps in 23.1967983s
```
</details>

## Build

- https://dev.azure.com/dnceng/public/_build/results?buildId=1247229&view=results

**Comment by halter73** [comment]
> | [6.375s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMAB2I8425HF" accepted.
> | [10.059s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMAB2I8425HF" started.

> [20.479s] Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware Debug: Authentication of the HTTPS connection timed out.

It looks like there might have been some serious threadpool starvation for the "accepted" and "started" logs to be ~4 seconds apart. The only thing between those two logs is a threadpool dispatch. I think that's what caused the handshake timeout and failed test.

**Comment by HaoK** [comment]
Per discussion with @adityamandaleeka we are going to unquarantine this since its been well behaved and there isn't much actionable as the failure looks due to external issues like threadpool starvation
