### ISSUE TITLE
Test failure: StreamPool_MultipleStreamsInSequence_PooledStreamReused

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#34685]
## Failing Test(s)

Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http3ConnectionTests.StreamPool_MultipleStreamsInSequence_PooledStreamReused

## Error Message

```text
Assert.False() Failure
Expected: False
Actual:   True
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http3ConnectionTests.StreamPool_MultipleStreamsInSequence_PooledStreamReused() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http3/Http3ConnectionTests.cs:line 247
--- End of stack trace from previous location ---
```
</details>

## Logs

<details>

```text
| [0.000s] TestLifetime Information: Starting test StreamPool_MultipleStreamsInSequence_PooledStreamReused at 2021-07-24T13:12:39
| [0.087s] Microsoft.AspNetCore.Server.Kestrel.Http3 Trace: Connection id "(null)" received HEADERS frame for stream ID 4 with length 65.
| [0.087s] Microsoft.AspNetCore.Server.Kestrel.Http3 Trace: Connection id "(null)" received DATA frame for stream ID 4 with length 13.
| [0.117s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "(null)", Request id "(null)": started reading request body.
| [0.117s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "(null)", Request id "(null)": done reading request body.
| [0.117s] Microsoft.AspNetCore.Server.Kestrel.Http3 Trace: Connection id "(null)" sending HEADERS frame for stream ID 4 with length 38.
| [0.117s] Microsoft.AspNetCore.Server.Kestrel.Http3 Trace: Connection id "(null)" sending DATA frame for stream ID 4 with length 13.
| [0.289s] Microsoft.AspNetCore.Server.Kestrel.Http3 Trace: Connection id "(null)" received HEADERS frame for stream ID 8 with length 65.
| [0.289s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "(null)", Request id "(null)": started reading request body.
| [0.290s] Microsoft.AspNetCore.Server.Kestrel.Http3 Trace: Connection id "(null)" received DATA frame for stream ID 8 with length 13.
| [0.290s] Microsoft.AspNetCore.Server.Kestrel.Http3 Trace: Connection id "(null)" sending HEADERS frame for stream ID 8 with length 38.
| [0.290s] Microsoft.AspNetCore.Server.Kestrel.Http3 Trace: Connection id "(null)" sending DATA frame for stream ID 8 with length 13.
| [0.290s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "(null)", Request id "(null)": done reading request body.
| [0.563s] Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http3ConnectionTests Error: Test threw an exception.
| Xunit.Sdk.FalseException: Assert.False() Failure
| Expected: False
| Actual:   True
|    at Xunit.Assert.False(Nullable`1 condition, String userMessage) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\BooleanAsserts.cs:line 52
|    at Xunit.Assert.False(Boolean condition) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\BooleanAsserts.cs:line 19
|    at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http3ConnectionTests.StreamPool_MultipleStreamsInSequence_PooledStreamReused() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http3/Http3ConnectionTests.cs:line 247
|    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 273
| --- End of stack trace from previous location ---
|    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 54
|    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 96
| [0.566s] TestLifetime Information: Finished test StreamPool_MultipleStreamsInSequence_PooledStreamReused in 0.5656032s
```
</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1256978&view=ms.vss-test-web.build-test-results-tab&runId=37284574&resultId=106365&paneView=debug

**Comment by Tratcher** [comment]
Different errors:
```
[0.111s] [Microsoft.AspNetCore.Testing.Http3InMemory] [Information] Disposing stream 400
[0.142s] [Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http3ConnectionTests] [Error] Test threw an exception.
Xunit.Sdk.SameException: Assert.Same() Failure
Expected: TestStreamContext { AbortReadException = null, AbortWriteException = null, CanRead = True, CanWrite = True, ConnectionClosed = System.Threading.CancellationToken, ... }
Actual:   TestStreamContext { AbortReadException = null, AbortWriteException = null, CanRead = True, CanWrite = True, ConnectionClosed = System.Threading.CancellationToken, ... }
   at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http3ConnectionTests.StreamPool_VariableMultipleStreamsInSequence_PooledStreamReused(Int32 count) in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http3/Http3ConnectionTests.cs:line 258
```
```
 | [1.581s] Microsoft.AspNetCore.Testing.Http3InMemory Information: Disposing stream 4000
 | [1.589s] Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http3ConnectionTests Error: Test threw an exception.
 | Xunit.Sdk.SameException: Assert.Same() Failure
 | Expected: TestStreamContext { CanRead = True, CanWrite = True, ConnectionClosed = System.Threading.CancellationToken, ConnectionId = "TEST:3996", Disposed = True, ... }
 | Actual:   TestStreamContext { CanRead = True, CanWrite = True, ConnectionClosed = System.Threading.CancellationToken, ConnectionId = "TEST:4000", Disposed = True, ... }
 |    at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http3ConnectionTests.StreamPool_VariableMultipleStreamsInSequence_PooledStreamReused(Int32 count) in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http3/Http3ConnectionTests.cs:line 256
```
