### ISSUE TITLE
VS2022 Preview unexpected error on load !

### ISSUE THREAD

**Issue by ameyasubhedar** [dotnet/aspnetcore#34722]
I keep getting the following error on the VS2022 Preview. Not getting on VS2019 and I am not sure what needs to be done to get rid of it !

![image](https://user-images.githubusercontent.com/13166236/127023592-dbe08aff-e935-4ec0-a932-0d6408dd8f51.png)

```
=====================
7/26/2021 9:14:53 AM
LimitedFunctionality
System.InvalidOperationException: Unexpected true - line 232
   at Roslyn.Utilities.Contract.Fail(String message, Int32 lineNumber)
   at Roslyn.Utilities.Contract.ThrowIfTrue(Boolean condition, Int32 lineNumber)
   at Microsoft.VisualStudio.LanguageServices.Implementation.Options.LanguageSettingsPersister.TryFetch(OptionKey optionKey, Object& value)
   at Microsoft.CodeAnalysis.Options.GlobalOptionService.LoadOptionFromSerializerOrGetDefault(OptionKey optionKey)
   at Microsoft.CodeAnalysis.Options.GlobalOptionService.GetOption_NoLock(OptionKey optionKey)
   at Microsoft.CodeAnalysis.Options.GlobalOptionService.GetSerializableOptionValues(ImmutableHashSet`1 optionKeys, ImmutableHashSet`1 languages)
   at Microsoft.CodeAnalysis.Options.GlobalOptionService.GetSerializableOptionsSnapshot(ImmutableHashSet`1 languages, IOptionService optionService)
   at Microsoft.CodeAnalysis.Workspace.CreateSolution(SolutionInfo solutionInfo)
   at Microsoft.CodeAnalysis.Workspace.OnSolutionAdded(SolutionInfo solutionInfo)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProjectFactory.<>c__DisplayClass9_0.<CreateAndAddToWorkspaceAsync>b__0(Workspace w)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioWorkspaceImpl.ApplyChangeToWorkspace(Action`1 action)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.VisualStudioProjectFactory.<CreateAndAddToWorkspaceAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSProjectFactory.<CreateProjectContextAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.CPS.CPSProjectFactory.Microsoft.VisualStudio.LanguageServices.ProjectSystem.IWorkspaceProjectContextFactory.CreateProjectContext(String languageName, String projectUniqueName, String projectFilePath, Guid projectGuid, Object hierarchy, String binOutputPath, String assemblyName)
   at Microsoft.VisualStudio.ProjectSystem.LanguageServices.WorkspaceProjectContextProvider.<CreateProjectContextHandlingFaultAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>g__Action|0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
===================
```

**Comment by Pilchie** [comment]
This is a Visual Studio issue - can you please report using the Send Feedback option inside Visual Studio?  If you want to share the link here, I can help ensure it's routed to the right area.

**Comment by gpshonik** [comment]
@Pilchie Not the OP - but would appreciate it if you can help route to the right area. 

https://developercommunity.visualstudio.com/t/Intermittent-Error-Opening-Projects---Vi/1477686

**Comment by Pilchie** [comment]
Moved, also tagging @jasonmalinowski
