### ISSUE TITLE
CannotAddMultipleRootComponentsToTheSameElementAtTheSameTime failure

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#34743]
## Failing Test(s)

- CannotAddMultipleRootComponentsToTheSameElementAtTheSameTime

## Error Message

```text
Assert.Equal() Failure\r\n          ↓ (pos 0)\r\nExpected: block\r\nActual:   none\r\n          ↑ (pos 0)

```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.Components.E2ETest.Tests.JSRootComponentsTest.AssertGlobalErrorState(Boolean hasGlobalError) in /_/src/Components/test/E2ETest/Tests/JSRootComponentsTest.cs:line 193
   at Microsoft.AspNetCore.Components.E2ETest.Tests.JSRootComponentsTest.CannotAddMultipleRootComponentsToTheSameElementAtTheSameTime() in /_/src/Components/test/E2ETest/Tests/JSRootComponentsTest.cs:line 87
```
</details>

## Logs

<details>

```text

```
</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1259700&view=results

**Comment by SteveSandersonMS** [comment]
There's a definite and clear bug in this test which I'm fixing in https://github.com/dotnet/aspnetcore/pull/34803. Will unquarantine as part of that, since it's an unambiguous fix.
