### ISSUE TITLE
"Handle is already used by another Socket." causing 502 errors (NET Core 2.2., NET 5.0, Kestrel, CentOS, Nginx)

### ISSUE THREAD

**Issue by afigelj** [dotnet/aspnetcore#34761]
We encountered random 502 errors with Net Core 2.2. web application running on CentOS behind Nginx.
Thinking the issue is related to version 2.2., we upgraded the application to NET 5.0. The errors still happen random, just in more irregular intervals.

Suggested solutions on the web for 502 errors also suggested, the error could be related to longer loading times of data from database. We optimized all queries in the API using the analysis of execution plans. The errors keep appearing.
While examining the Access and Kestrel logs, we found one irregularity.
Below are the Kestrel logs of two identical web page requests less than 2 minutes apart. First request returned status 200, second 502. The difference is after the line **xxx.DfaMatcher[1005]**. The 1st log shows the line **Endpoint … is valid for the request path**, but the second log is missing this entry.

As the second log shows, there were 14 seconds where Kestrel didn’t process anything (despite the user did reload the web page 4 times). The first entry is **Starting HttpMessageHandler cleanup cycle**. After that, the 4 web page requests produced 502, which Kestrel shows as: **Connection id "xxx" communication error**.

We were also surprised to see the API log, where the 4 subsequent requests from the web page (producing 502) were processed by the API with status 200.
As a side note: we never encountered any similar issue on the development computer (Win 10 LTSB, Visual Studio 2019 Pro, using IIS) for the past two years.

**Access.log:**
**Response 200**
213.157.249.198 - - [16/Jun/2021:08:17:18 +0200] "GET /Admin/Measurement/Detail/5aa3ce5c-612b-4202-896a-f03d20af7d62 HTTP/1.1" 200 8025 "https://my-domain.com/Admin/Measurement" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36"

**Response 502**
213.157.249.198 - - [16/Jun/2021:08:18:55 +0200] "GET /Admin/Measurement/Detail/5aa3ce5c-612b-4202-896a-f03d20af7d62 HTTP/1.1" 502 552 "https://my-domain.com/Admin/Measurement" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36"

**Kestrel log:
Response 200**
Jun 16 08:17:18 .NET Core (dotnet)[551]: dbug: Microsoft.AspNetCore.Server.Kestrel[39]
Jun 16 08:17:18 .NET Core (dotnet)[551]: Connection id "0HM9GAMVBTK15" accepted.
Jun 16 08:17:18 .NET Core (dotnet)[551]: dbug: Microsoft.AspNetCore.Server.Kestrel[1]
Jun 16 08:17:18 .NET Core (dotnet)[551]: Connection id "0HM9GAMVBTK15" started.
Jun 16 08:17:18 .NET Core (dotnet)[551]: dbug: Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware[3]
Jun 16 08:17:18 .NET Core (dotnet)[551]: Connection "0HM9GAMVBTK15" established using the following protocol: Tls12
Jun 16 08:17:18 .NET Core (dotnet)[551]: info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
Jun 16 08:17:18 .NET Core (dotnet)[551]: Request starting HTTP/1.1 GET https://my-domain.com/Admin/Measurement/Detail/5aa3ce5c-612b-4202-896a-f03d20af7d62 - -
Jun 16 08:17:18 .NET Core (dotnet)[551]: dbug: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[4]
Jun 16 08:17:18 .NET Core (dotnet)[551]: The request path /Admin/Measurement/Detail/5aa3ce5c-612b-4202-896a-f03d20af7d62 does not match a supported file type
Jun 16 08:17:18 .NET Core (dotnet)[551]: dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1001]
Jun 16 08:17:18 .NET Core (dotnet)[551]: 1 candidate(s) found for the request path '/Admin/Measurement/Detail/5aa3ce5c-612b-4202-896a-f03d20af7d62'
Jun 16 08:17:18 .NET Core (dotnet)[551]: dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005]
**Jun 16 08:17:18 .NET Core (dotnet)[551]: Endpoint 'Page: /Measurement/Detail' with route pattern 'Admin/Measurement/Detail/{id:Guid?}/{handler?}' is valid for the request path '/Admin/Measurement/Detail/5aa3ce5c-612b-4202-896a-f03d20af7d62'**

**Response 502**
Jun 16 08:18:55 .NET Core (dotnet)[551]: dbug: Microsoft.AspNetCore.Server.Kestrel[39]
Jun 16 08:18:55 .NET Core (dotnet)[551]: Connection id "0HM9GAMVBTK1R" accepted.
Jun 16 08:18:55 .NET Core (dotnet)[551]: dbug: Microsoft.AspNetCore.Server.Kestrel[1]
Jun 16 08:18:55 .NET Core (dotnet)[551]: Connection id "0HM9GAMVBTK1R" started.
Jun 16 08:18:55 .NET Core (dotnet)[551]: dbug: Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware[3]
Jun 16 08:18:55 .NET Core (dotnet)[551]: Connection "0HM9GAMVBTK1R" established using the following protocol: Tls12
Jun 16 08:18:55 .NET Core (dotnet)[551]: info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
Jun 16 08:18:55 .NET Core (dotnet)[551]: Request starting HTTP/1.1 GET https://my-domain.com/Admin/Measurement/Detail/5aa3ce5c-612b-4202-896a-f03d20af7d62 - -
Jun 16 08:18:55 .NET Core (dotnet)[551]: dbug: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[4]
Jun 16 08:18:55 .NET Core (dotnet)[551]: The request path /Admin/Measurement/Detail/5aa3ce5c-612b-4202-896a-f03d20af7d62 does not match a supported file type
Jun 16 08:18:55 .NET Core (dotnet)[551]: dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1001]
Jun 16 08:18:55 .NET Core (dotnet)[551]: 1 candidate(s) found for the request path '/Admin/Measurement/Detail/5aa3ce5c-612b-4202-896a-f03d20af7d62'
Jun 16 08:18:55 .NET Core (dotnet)[551]: dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005]
**- Missing line: Endpoint 'xxx' is valid for the request path**
Jun 16 08:19:09 .NET Core (dotnet)[551]: dbug: Microsoft.Extensions.Http.DefaultHttpClientFactory[100]
Jun 16 08:19:09 .NET Core (dotnet)[551]: Starting HttpMessageHandler cleanup cycle with 7 items
Jun 16 08:19:09 .NET Core (dotnet)[551]: dbug: Microsoft.Extensions.Http.DefaultHttpClientFactory[101]
Jun 16 08:19:09 .NET Core (dotnet)[551]: Ending HttpMessageHandler cleanup cycle after 0.0043ms - processed: 0 items - remaining: 7 items
Jun 16 08:19:09 .NET Core (dotnet)[551]: dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[14]
Jun 16 08:19:09 .NET Core (dotnet)[551]: Connection id "0HM9GAMVBTK1T" communication error.
Jun 16 08:19:09 .NET Core (dotnet)[551]: System.InvalidOperationException: Handle is already used by another Socket.
Jun 16 08:19:09 .NET Core (dotnet)[551]: at System.Net.Sockets.SocketAsyncEngine.RegisterCore(IntPtr socketHandle, SocketAsyncContext context)
Jun 16 08:19:09 .NET Core (dotnet)[551]: at System.Net.Sockets.SocketAsyncEngine.RegisterSocket(IntPtr socketHandle, SocketAsyncContext context)
Jun 16 08:19:09 .NET Core (dotnet)[551]: at System.Net.Sockets.SocketAsyncContext.Register()
Jun 16 08:19:09 .NET Core (dotnet)[551]: at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.StartAsyncOperation(SocketAsyncContext context, TOperation operation, Int32 observedSequenceNumber, CancellationToken cancellationToken)
Jun 16 08:19:09 .NET Core (dotnet)[551]: at System.Net.Sockets.SocketAsyncContext.ReceiveAsync(Memory`1 buffer, SocketFlags flags, Int32& bytesReceived, Action`5 callback, CancellationToken cancellationToken)
Jun 16 08:19:09 .NET Core (dotnet)[551]: at System.Net.Sockets.SocketAsyncEventArgs.DoOperationReceive(SafeSocketHandle handle, CancellationToken cancellationToken)
Jun 16 08:19:09 .NET Core (dotnet)[551]: at System.Net.Sockets.Socket.ReceiveAsync(SocketAsyncEventArgs e, CancellationToken cancellationToken)
Jun 16 08:19:09 .NET Core (dotnet)[551]: at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketReceiver.WaitForDataAsync()
Jun 16 08:19:09 .NET Core (dotnet)[551]: at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.ProcessReceives()
Jun 16 08:19:09 .NET Core (dotnet)[551]: at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive()
Jun 16 08:19:09 .NET Core (dotnet)[551]: dbug: Microsoft.AspNetCore.Server.Kestrel[39]
Jun 16 08:19:09 .NET Core (dotnet)[551]: Connection id "0HM9GAMVBTK1T" accepted.
Jun 16 08:19:09 .NET Core (dotnet)[551]: dbug: Microsoft.AspNetCore.Server.Kestrel[1]
Jun 16 08:19:09 .NET Core (dotnet)[551]: Connection id "0HM9GAMVBTK1T" started.
Jun 16 08:19:09 .NET Core (dotnet)[551]: fail: Microsoft.AspNetCore.Server.Kestrel[0]
Jun 16 08:19:09 .NET Core (dotnet)[551]: Unhandled exception while processing 0HM9GAMVBTK1T.
Jun 16 08:19:09 .NET Core (dotnet)[551]: System.InvalidOperationException: Handle is already used by another Socket.
Jun 16 08:19:09 .NET Core (dotnet)[551]: at System.Net.Sockets.SocketAsyncEngine.RegisterCore(IntPtr socketHandle, SocketAsyncContext context)
Jun 16 08:19:09 .NET Core (dotnet)[551]: at System.Net.Sockets.SocketAsyncEngine.RegisterSocket(IntPtr socketHandle, SocketAsyncContext context)
Jun 16 08:19:09 .NET Core (dotnet)[551]: at System.Net.Sockets.SocketAsyncContext.Register()
Jun 16 08:19:09 .NET Core (dotnet)[551]: at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.StartAsyncOperation(SocketAsyncContext context, TOperation operation, Int32 observedSequenceNumber, CancellationToken cancellationToken)
Jun 16 08:19:09 .NET Core (dotnet)[551]: at System.Net.Sockets.SocketAsyncContext.ReceiveAsync(Memory`1 buffer, SocketFlags flags, Int32& bytesReceived, Action`5 callback, CancellationToken cancellationToken)
Jun 16 08:19:09 .NET Core (dotnet)[551]: at System.Net.Sockets.SocketAsyncEventArgs.DoOperationReceive(SafeSocketHandle handle, CancellationToken cancellationToken)
Jun 16 08:19:09 .NET Core (dotnet)[551]: at System.Net.Sockets.Socket.ReceiveAsync(SocketAsyncEventArgs e, CancellationToken cancellationToken)
Jun 16 08:19:09 .NET Core (dotnet)[551]: at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketReceiver.WaitForDataAsync()
Jun 16 08:19:09 .NET Core (dotnet)[551]: at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.ProcessReceives()
Jun 16 08:19:09 .NET Core (dotnet)[551]: at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection.DoReceive()
Jun 16 08:19:09 .NET Core (dotnet)[551]: at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
Jun 16 08:19:09 .NET Core (dotnet)[551]: at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
Jun 16 08:19:09 .NET Core (dotnet)[551]: at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
Jun 16 08:19:09 .NET Core (dotnet)[551]: at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
Jun 16 08:19:09 .NET Core (dotnet)[551]: at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.DuplexPipeStream.ReadAsyncInternal(Memory`1 destination, CancellationToken cancellationToken)
Jun 16 08:19:09 .NET Core (dotnet)[551]: at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|182_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
Jun 16 08:19:09 .NET Core (dotnet)[551]: at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
Jun 16 08:19:09 .NET Core (dotnet)[551]: at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
Jun 16 08:19:09 .NET Core (dotnet)[551]: at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context)
Jun 16 08:19:09 .NET Core (dotnet)[551]: at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1.ExecuteAsync()
Jun 16 08:19:09 .NET Core (dotnet)[551]: dbug: Microsoft.AspNetCore.Server.Kestrel[2]
Jun 16 08:19:09 .NET Core (dotnet)[551]: Connection id "0HM9GAMVBTK1T" stopped.
Jun 16 08:19:09 .NET Core (dotnet)[551]: dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets[7]
Jun 16 08:19:09 .NET Core (dotnet)[551]: Connection id "0HM9GAMVBTK1T" sending FIN because: "The Socket transport's send loop completed gracefully."

**Nginx error log:**
2021/06/16 08:18:55 [error] 1883#0: *3243 upstream prematurely closed connection while reading response header from upstream, client: 213.157.249.198, server: my-domain.com, request: "GET /Admin/Measurement/Detail/5aa3ce5c-612b-4202-896a-f03d20af7d62 HTTP/1.1", upstream: "https://[::1]:6000/Admin/Measurement/Detail/5aa3ce5c-612b-4202-896a-f03d20af7d62", host: "my-domain.com", referrer: "https://my-domain.com/Admin/Measurement/Email/5aa3ce5c-612b-4202-896a-f03d20af7d62"

2021/06/16 08:18:55 [error] 1883#0: *3243 SSL_do_handshake() failed (SSL: error:140940F5:SSL routines:ssl3_read_bytes:unexpected record) while SSL handshaking to upstream, client: 213.157.249.198, server: my-domain.com, request: "GET /Admin/Measurement/Detail/5aa3ce5c-612b-4202-896a-f03d20af7d62 HTTP/1.1", upstream: "https://127.0.0.1:6000/Admin/Measurement/Detail/5aa3ce5c-612b-4202-896a-f03d20af7d62", host: "my-domain.com", referrer: "https://my-domain.com/Admin/Measurement/Email/5aa3ce5c-612b-4202-896a-f03d20af7d62"

Any ideas where to look for the cause of the issue would be appreciated.

**Comment by adityamandaleeka** [comment]
@dotnet/http Could this be a bug in Sockets?

**Comment by karelz** [comment]
Exception comes from here:
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEngine.Unix.cs#L116
or the 5.0 version:
https://github.com/dotnet/runtime/blob/release/5.0/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEngine.Unix.cs#L115

```c#
                // Using public SafeSocketHandle(IntPtr) a user can add the same handle
                // from a different Socket instance.
```

Is it something ASP.NET might use?
@antonfirsov @geoffkizer any further thoughts?

**Comment by stephentoub** [comment]
> Is it something ASP.NET might use?

https://github.com/dotnet/aspnetcore/blob/18a926850f7374248e687ee64390e7f10514403f/src/Servers/Kestrel/Transport.Sockets/src/SocketTransportOptions.cs#L110

**Comment by stephentoub** [comment]
As an aside, I don't understand the explanation here:
https://github.com/dotnet/aspnetcore/blob/18a926850f7374248e687ee64390e7f10514403f/src/Servers/Kestrel/Transport.Sockets/src/SocketTransportOptions.cs#L100-L108
How is this not setting up a potential double-free handle/fd problem?

**Comment by halter73** [comment]
> Is it something ASP.NET might use?

We use it for the listen socket to support systemd listen sockets. @afigelj Are you calling `.UseSystemd()` or `.ListenHandle()` anywhere? I'm guessing not. In any case, that should only affect the listen socket, right? This is an accepted socket.

> How is this not setting up a potential double-free handle/fd problem?

This does seem like a problem. Even for the systemd socket activation, the manpage specifically says 

> It should not invoke shutdown(2) on sockets it got with Accept=no,

https://www.freedesktop.org/software/systemd/man/systemd.socket.html#Accept=

`Accept=no` is the only scenario we support 😢. In context, it might only be for AF_UNIX sockets (Unix domain sockets) which aren't super common even in systemd socket activation scenarios. So maybe that's why we haven't had problems reported related to this. There's also the possibility of people calling KestrelServerOptions.ListenHandle() directly and don't expect us to take close the socket on shutdown.

[I didn't like this the last time it was touched either](https://github.com/dotnet/aspnetcore/pull/32827#discussion_r636454643), but we'd need to work our [accept loop logic](https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/Servers/Kestrel/Core/src/Internal/ConnectionDispatcher.cs#L46-L64) or transports themselves to use CancellationTokens to stop the loop rather than relying on closing the listen socket to do so. This is probably something we should do anyway, but I'm not aware of anyone filing issues related to this, so for now it's mostly a code correctness thing.

**Comment by afigelj** [comment]
> We use it only for the listen socket to support systemd socket activation. @afigelj Are you calling `.UseSystemd()` or `.ListenHandle()` anywhere? I'm guessing not. In any case, that should only affect the listen socket, right? This is an accepted socket.
> 
No, we're not using any of this methods. Simply service/API/repository calls from the web page.

**Comment by antonfirsov** [comment]
I'm not super-familiar with memory models, but shouldn't be the read of `_asyncEngine` volatile here to ensure it's always happening after the lock is taken:

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs#L1235-L1239

**Comment by stephentoub** [comment]
> shouldn't be the read of _asyncEngine volatile here to ensure it's always happening after the lock is taken?

Entering the lock has read-acquire semantics.  No reads from inside the lock can move to be before the lock.

**Comment by antonfirsov** [comment]
Other (weird...) cases where people seem to hit this:

https://stackoverflow.com/questions/67912596/warn-microsoft-aspnetcore-server-kestrel0-connection-processing-ended-abnorma
https://zblesk.net/blog/aspnetcore-identity-litedb-breaks-on-ubuntu/

**Comment by halter73** [comment]
@antonfirsov @stephentoub Are you both okay with transferring this to the runtime repo since there doesn't appear to be any usage of `SafeSocketHandle(IntPtr)` in the app?
