### ISSUE TITLE
Repo doesn't build without python installed

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/aspnetcore#34830]
If I run build.cmd on a machine without python installed, I get a very obscure build failure:

```
C:\AspNetCore-Tooling\eng\targets\Npm.Common.targets(48,5): error MSB6006: "yarn" exited with code 1. [C:\AspNetCore-To
oling\src\Razor\test\Microsoft.AspNetCore.Razor.VSCode.Grammar.Test\Microsoft.AspNetCore.Razor.VSCode.Grammar.Test.npmp
roj]
C:\Users\kirillo\.nuget\packages\microsoft.dotnet.arcade.sdk\6.0.0-beta.21311.3\tools\Build.proj(254,5): error MSB4181:
 The "MSBuild" task returned false but did not log an error.
```

Turns out if I run the yarn command manually:
```
C:\Users\kirill\.nuget\packages\yarn.msbuild\1.22.10\dist\bin\yarn.cmd install --mutex network  --ignore-engines
```

in the oniguruma directory, it gives a more verbose output:
```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.10.0 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\AspNetCore-Tooling\src\Razor\test\Microsoft.AspNetCore.Razor.VSCode.Grammar.Test\node_modules\oniguruma
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

We should probably detect whether python is installed and maybe just skip yarn if it's not installed. The tests aren't always necessary for just building the repo.

**Comment by davidfowl** [comment]
cc @dougbu

**Comment by dougbu** [comment]
We no longer own the aspnetcore-tooling repo @davidfowl. /cc @NTaylorMullen @jinujoseph
