### ISSUE TITLE
Logging site extension should use startup hooks (instead of additional deps)

### ISSUE THREAD

**Issue by shirhatti** [dotnet/aspnetcore#34864]
The AzureAppServiceLoggingSiteExtension relies on the `DOTNET_ADDITIONAL_DEPS` feature in the host. This results in an error-prone process where we forget to add a new runtime store directory for older tfms when we update the repo's default tfm.

Given that 2.1 will go out of support soon, we will no longer need to support a version of .NET that doesn't have startup hooks. This will allow us to switch to a version agnostic implementation using startup hooks that will no longer require us to update the SiteExtension every time we add a tfm.

**Comment by adityamandaleeka** [comment]
Triage: we should do this in 7.

**Comment by LukeBolly** [comment]
This still causes our app to crash periodically. Last night a new version of the logging extension somehow installed itself and brought our website down again, same issue as this: https://github.com/dotnet/aspnetcore/issues/34840

**Comment by twoelfer** [comment]
So any news regarding this? I still see the same issue with net core 6.

**Comment by miloszes** [comment]
Hi, any updates on this issue?

**Comment by lownlazy** [comment]
Hi, is there any progress to report on this?

**Comment by kizilsum** [comment]
Hi, any update on this? Recently, I've upgraded an azure app service to dotnet 6 and seen this issue in the application insights

**Comment by LukeBolly** [comment]
Is there possibly a regression? We experienced it for the first time in a while a couple of days ago as well.

**Comment by itamarbareket** [comment]
We got to experience it for the first time a few days ago and it seems to be ongoing.

**Comment by koryphaee** [comment]
I am experiencing the same issue and was able to avoid the exception with some configuration:
```
var options = new WebApplicationOptions
{
	Args = args.Append("PreventHostingStartup=true").ToArray(),
	ApplicationName = "Subjective"
};
WebApplicationBuilder builder = WebApplication.CreateBuilder(options);
```
Setting "PreventHostingStartup" in AppSettings.json does not work.

**Comment by VictorioBerra** [comment]
Getting this in .NET 8, non-SelfContained. Hosting on Azure App Services.

```
System.InvalidOperationException: Startup assembly Microsoft.AspNetCore.AzureAppServices.HostingStartup failed to execute. See the inner exception for more details.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.AzureAppServices.HostingStartup, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Microsoft.AspNetCore.AzureAppServices.HostingStartup, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.ExecuteHostingStartups()
   --- End of inner exception stack trace ---
```

**Comment by ChrisBase** [comment]
Got the same exceptions like [VictorioBerra](https://github.com/VictorioBerra) with the same environment (.NET 8, non-SelfContained, hosting on Azure App Services).  
Settings **WebHostDefaults.PreventHostingStartupKey** to **"true"** stopped it from occuring.
```c#
public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    // After adding the following line, the exception no longer occurred
                    webBuilder.UseSetting(WebHostDefaults.PreventHostingStartupKey, "true");

                    webBuilder.UseStartup<Startup>();
                })
```

**Comment by twoelfer** [comment]
Did what koryphaee did and this seems to work. (net 6, running on azure)

**Comment by zwcloud** [comment]
> I am experiencing the same issue and was able to avoid the exception with some configuration:
> 
> ```
> var options = new WebApplicationOptions
> {
> 	Args = args.Append("PreventHostingStartup=true").ToArray(),
> 	ApplicationName = "Subjective"
> };
> WebApplicationBuilder builder = WebApplication.CreateBuilder(options);
> ```
> 
> Setting "PreventHostingStartup" in AppSettings.json does not work.

This works on net8.

**Comment by zwcloud** [comment]
> Did what koryphaee did and this does not seem to work for me. (net 6, running on azure)

@twoelfer I had fixed the issue by referencing the dll `Microsoft.WebTools.ApiEndpointDiscovery`.
