### ISSUE TITLE
Flaky test: CanHandleErrorsInlineInErrorBoundaryContent

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/aspnetcore#34870]
## Failing Test(s)

- CanHandleErrorsInlineInErrorBoundaryContent

## Error Message

```text
OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.NotEmptyException: Assert.NotEmpty() Failure\r\n   at Xunit.Assert.NotEmpty(IEnumerable collection) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 331\r\n   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<Exists>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 72\r\n   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver ) in //src/Shared/E2ETesting/WaitAssert.cs:line 109\r\nScreen shot captured at 'D:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.AspNetCore.Components.E2ETests\c68204eee9eb43bebea74a21e8bfa206.png'\r\nEncountered browser errors\r\n[2021-07-29T22:45:23Z] [Info] http://127.0.0.1:1073/subdir/_framework/blazor.server.js 0:37412 "[2021-07-29T22:45:23.934Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:1073/subdir/_blazor'."\r\n[2021-07-29T22:45:23Z] [Info] http://127.0.0.1:1073/subdir 47:16 "Blazor server-side"\r\n[2021-07-29T22:45:23Z] [Severe] http://127.0.0.1:1073/subdir/_framework/blazor.server.js 0 WebSocket connection to 'ws://127.0.0.1:1073/subdir/_blazor?id=ravJIEqx9eFMXu0cBCIMKQ' failed: Error in connection establishment: net::ERR_ADDRESS_IN_USE\r\n[2021-07-29T22:45:23Z] [Info] http://127.0.0.1:1073/subdir/_framework/blazor.server.js 0:37412 "[2021-07-29T22:45:23.960Z] Information: (WebSockets transport) There was an error with the transport."\r\n[2021-07-29T22:45:23Z] [Severe] http://127.0.0.1:1073/subdir/_framework/blazor.server.js 0:37329 "[2021-07-29T22:45:23.961Z] Error: Failed to start the transport 'WebSockets': Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled."\r\n[2021-07-29T22:45:23Z] [Severe] http://127.0.0.1:1073/subdir/_framework/blazor.server.js 0:37329 "[2021-07-29T22:45:23.961Z] Error: Failed to start the connection: Error: Unable to connect to the server with any of the available transports. Error: WebSockets failed: Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled."\r\n[2021-07-29T22:45:23Z] [Severe] http://127.0.0.1:1073/subdir/_framework/blazor.server.js 0:112352 "[2021-07-29T22:45:23.961Z] Error: Error: Unable to connect to the server with any of the available transports. Error: WebSockets failed: Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled."\r\n[2021-07-29T22:45:23Z] [Severe] http://127.0.0.1:1073/subdir/_framework/blazor.server.js 0:112352 "[2021-07-29T22:45:23.962Z] Error: Failed to start the circuit."Page content:\r\n<head>\r\n    <meta charset="utf-8">\r\n    <title>Basic test app</title>\r\n    <base href="/subdir/">\r\n    <link href="style.css" rel="stylesheet">\r\n    <link rel="icon" href="data:,">\r\n\r\n    \r\n    <link href="_content/TestContentPackage/styles.css" rel="stylesheet">\r\n    <link href="Components.TestServer.styles.css" rel="stylesheet">\r\n</head>\r\n<body>\r\n    <root><!--Blazor:{"sequence":0,"type":"server","descriptor":"CfDJ8AAAAAAAAAAAAAAAAAAAAACWd5uY49J3CEM9BtIYzUOx3362fHP1Qc0rME2azjXz89CJhq0jtYwZibUYYSzF2sXCBW7E7oIhl3ZWOYXlGjzg1MshtM6ibfBNmiP9PldA4exaSPYqtpoSua29La1cwgdAegLiCQpnVLaCRAe8x09rlbxAg9tg5ZkNJzS3jAWMGzSUNQien5vDggzdTddANKSScykLxfSyxI1UbpEh5p
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 129
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.Exists(IWebDriver driver, By finder, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 67
   at Microsoft.AspNetCore.Components.E2ETest.BasicTestAppWebDriverExtensions.WaitUntilTestSelectorReady(IWebDriver browser) in /_/src/Components/test/E2ETest/Infrastructure/WebDriverExtensions/BasicTestAppWebDriverExtensions.cs:line 27
   at Microsoft.AspNetCore.Components.E2ETest.BasicTestAppWebDriverExtensions.MountTestComponent[TComponent](IWebDriver browser) in /_/src/Components/test/E2ETest/Infrastructure/WebDriverExtensions/BasicTestAppWebDriverExtensions.cs:line 21
   at Microsoft.AspNetCore.Components.E2ETest.Tests.ErrorBoundaryTest.InitializeAsyncCore() in /_/src/Components/test/E2ETest/Tests/ErrorBoundaryTest.cs:line 29
   at Microsoft.AspNetCore.E2ETesting.BrowserTestBase.InitializeAsync(String isolationContext) in /_/src/Shared/E2ETesting/BrowserTestBase.cs:line 71
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<Exists>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 72
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 109
```
</details>

## Logs

<details>

```text

```
</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1267188&view=results

**Comment by dougbu** [comment]
The new error is expected when the Chrome version installed for these tests (which moves forward pretty quickly) gets ahead of the driver version. @wtgodbe are the driver versions up-to-date❔

**Comment by TanayParikh** [comment]
> There is a beta 95 version on nuget.org: https://www.nuget.org/packages/Selenium.WebDriver.ChromeDriver/. We could update to that

Thanks. Put up a PR: https://github.com/dotnet/aspnetcore/pull/37726

**Comment by dougbu** [comment]
> > when the Chrome version installed for these tests (which moves forward pretty quickly) gets ahead of the driver version

> Is there any way for us to "lock-in" the chrome version. 

> Then we'd update the chrome & driver versions simultaneously. Do we have this level of granularity in control of the CI machines?

Short answer: **No**. 

Longer answer: The installer for Chrome is downloaded from a single non-version-specific location. We don't control when that installer is updated. We _could_ do something fairly complicated with cached installers but made the decision long ago to instead keep the driver versions up-to-date.
