### ISSUE TITLE
Plea for what i'm missing.. - IServer 

### ISSUE THREAD

**Issue by dazinator** [dotnet/aspnetcore#34978]
I wanted to have an out of the box kestrel based `IHost` receive a request, flow it through the standard middleware pipeline, but then I wanted my own custom middleware sitting in that pipeline to be able forward the http request to a completely seperate IHost within my application, that was setup with its own custom `IServer `implementation that simply takes the HttpContext its given, creates a new custom `ChildHttpContext`, and processes the request in its own isolated pipeline. The reason for this is this then allows me to divide my application up into different logical child IHosts and route requests into different ones - for example for the different modules of the platform etc.

I have lots of tests passing now, showing this working nicely in a number of key scenarios, like child IHosts get their own DI scopes, can serve a static file, can be created and destroyed at runtime etc etc.
However today I tried serving up a SPA from within the child host and I found some exceptions that seem related to HTTP/2 but i'm stabbing in the dark.. The issue occurs when the web browser tries to load a lot of the blazor framework files over http/2 GET requests. Here are the top level logs that lead to the exception:

```
Request finished HTTP/2 GET https://localhost:5001/Setup/_framework/SetupApp.Client.dll - - - 200 16896 application/octet-stream 3035.1227ms
03 Aug 2021 13:07:39.209
 Connection id "0HMAMET2FGNOV", Request id "0HMAMET2FGNOV:00000011": An unhandled exception was thrown by the application.
03 Aug 2021 13:07:39.209
 The response has already started, the error page middleware will not be executed.
03 Aug 2021 13:07:39.208
 An unhandled exception has occurred while executing the request.
03 Aug 2021 13:07:36.187
 Request finished HTTP/2 GET https://localhost:5001/Setup/_framework/SetupApp.Shared.dll - - - 200 0 - 12.8872ms
03 Aug 2021 13:07:36.180
 Request finished HTTP/2 GET https://localhost:5001/Setup/_framework/SetupApp.Client.pdb - - - 200 14044 application/octet-stream 3.7599ms
03 Aug 2021 13:07:36.179
 Request finished HTTP/2 GET https://localhost:5001/Setup/_framework/SetupApp.Shared.pdb - - - 200 9844 application/octet-stream 4.2453ms
03 Aug 2021 13:07:36.176
 Request starting HTTP/2 GET https://localhost:5001/Setup/_framework/SetupApp.Client.pdb - -
03 Aug 2021 13:07:36.175
 Request starting HTTP/2 GET https://localhost:5001/Setup/_framework/SetupApp.Shared.pdb - -
03 Aug 2021 13:07:36.174
 Request starting HTTP/2 GET https://localhost:5001/Setup/_framework/SetupApp.Client.dll - -
03 Aug 2021 13:07:36.174
 Request starting HTTP/2 GET https://localhost:5001/Setup/_framework/SetupApp.Shared.dll - -
03 Aug 2021 13:07:36.161
 Request finished HTTP/2 GET https://localhost:5001/Setup/_framework/dotnet.5.0.7.js - - - 200 63134 application/javascript 27.4474ms
03 Aug 2021 13:07:36.134
 Request starting HTTP/2 GET https://localhost:5001/Setup/_framework/dotnet.5.0.7.js - -
03 Aug 2021 13:07:36.061
 Request finished HTTP/2 GET https://localhost:5001/Setup/_framework/blazor.boot.json - - - 200 19434 application/json 15.3488ms
03 Aug 2021 13:07:36.045
 Request starting HTTP/2 GET https://localhost:5001/Setup/_framework/blazor.boot.json - -
03 Aug 2021 13:07:36.035
 Request finished HTTP/2 GET https://localhost:5001/Setup/css/bootstrap/bootstrap.min.css - - - 500 - text/plain 3054.3472ms
03 Aug 2021 13:07:36.013
 Request finished HTTP/2 GET https://localhost:5001/Setup/_framework/blazor.webassembly.js - - - 304 - application/javascript 2935.7167ms
03 Aug 2021 13:07:36.010
 Request finished HTTP/2 GET https://localhost:5001/Setup/SetupApp.Client.styles.css - - - 200 2810 text/css 3028.3546ms

```

And here is a more detailed stacktrace at the point the error occurs:

```
ConnectionId
0HMAMET2FGNOV
EventId
{Id: 1, Name: 'UnhandledException'}
RequestId
0HMAMET2FGNOV:00000011
RequestPath
/Setup/_framework/SetupApp.Client.dll
SourceContext
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware
System.InvalidOperationException: Response Content-Length mismatch: too many bytes written (32768 of 16896).
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowTooManyBytesWritten(Int32 count)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.VerifyAndUpdateWrite(Int32 count)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.FirstWriteAsyncInternal(ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.FirstWriteAsync(ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.WritePipeAsync(ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.StreamCopyOperationInternal.CopyToAsync(Stream source, Stream destination, Nullable`1 count, Int32 bufferSize, CancellationToken cancel)
   at Microsoft.AspNetCore.Http.SendFileFallback.SendFileAsync(Stream destination, String filePath, Int64 offset, Nullable`1 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.SendFileResponseExtensions.SendFileAsyncCore(HttpResponse response, String fileName, Int64 offset, Nullable`1 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.SendFileResponseExtensions.SendFileAsyncCore(HttpResponse response, IFileInfo file, Int64 offset, Nullable`1 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.StaticFiles.StaticFileContext.SendAsync()
   at Microsoft.AspNetCore.StaticFiles.StaticFileContext.ServeStaticFile(HttpContext context, RequestDelegate next)
   at BlazorAppBuilderExtensions.<>c__DisplayClass4_0.<<MapBlazorSpaFrameworkFiles>b__2>d.MoveNext() in C:\Users\DarrellTunnell\source\repos\HostsPoc\HostsPoc\BlazorSpaWebHost\BlazorAppBuilderExtensions.cs:line 125
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at HostsPoc.ChildHostServer.<>c__DisplayClass8_0`1.<<StartAsync>b__0>d.MoveNext() in C:\Users\DarrellTunnell\source\repos\HostsPoc\HostsPoc\HostsPoc\Server\ChildHostServer.cs:line 63
--- End of stack trace from previous location ---
   at HostsPoc.UseChildHostMiddleware.Invoke(HttpContext httpContext) in C:\Users\DarrellTunnell\source\repos\HostsPoc\HostsPoc\HostsPoc\Middleware\UseChildHostMiddleware.cs:line 43
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```

The stack trace shows my custom `UseChildHostMiddleware` running in the parent IHost pipeline (kestrel), then passing the its HttpContext to the `ChildHostServer` IServer instance in the child IHost, which constructs its own `ChildHttpContext` to serve the request, re-using all of the same `Features` from the parent `HttpContext`, except overriding the `RequestServicesFeature` with its own - essentially so that it gets it's own isolated DI scope. I think I need to re-use all the same Features from the parent HttpContext so that the child middleware pipeline can still have middleware that does fancy stuff leveraging the capabilities of kestrel top level server. Here is what my ChildHttpContext looks like:

```csharp
          public class ChildHttpContext : HttpContext
    {
        //private readonly HttpContext _parentContext;
        //private readonly Func<Task> _parentNext;

        // private readonly IServiceProvider _childContextServiceProvider;
        private FeatureReferences<FeatureInterfaces> _features;
        private IFeatureCollection _featureCollection;

        private IChildHttpContextFeature _childHttpContextFeature;

        private readonly static Func<ChildHttpContext, IServiceProvidersFeature> _newServiceProvidersFeature = context => new RequestServicesFeature(context, context.ServiceScopeFactory);

        //private readonly static Func<ChildHttpContext, IChildHttpContextFeature> _newChildHttpContextFeature = context => new ChildHttpContextFeature(context._parentContext, context._parentNext);


        private IServiceProvidersFeature ServiceProvidersFeature
        {
            get
            {
                var result = _features.Fetch<IServiceProvidersFeature, ChildHttpContext>(ref _features.Cache.ServiceProviders, this, _newServiceProvidersFeature);
                return result;
            }
        }

        private IChildHttpContextFeature ChildHttpContextFeature
        {
            get
            {
                return _childHttpContextFeature;
                //var result = _features.Fetch<IChildHttpContextFeature, ChildHttpContext>(ref _features.Cache.ChildHttpContext, this, _newChildHttpContextFeature);
                //return result;
            }
        }      

        public ChildHttpContext(IServiceScopeFactory scopeFactory,
            IChildHttpContextFeature feature)
        {         

            _childHttpContextFeature = feature;
            _featureCollection = new FeatureCollection(ParentContext.Features);

            ServiceScopeFactory = scopeFactory;
            // Override parent service provider feature so we create DI scopes from child context rather than parent.
            var serviceProviderFeature = _newServiceProvidersFeature(this);
            Features.Set<IServiceProvidersFeature>(serviceProviderFeature);
            // Include child http context feature in feature set inherited from parent, so middleware can access it from child pipelines.        
            Features.Set<IChildHttpContextFeature>(feature);
            _features.Initalize(Features);
        }

        public override IFeatureCollection Features { get { return _featureCollection; } }
        public override HttpRequest Request { get { return ParentContext.Request; } }
        public override HttpResponse Response { get { return ParentContext.Response; } }
        public override ConnectionInfo Connection { get { return ParentContext.Connection; } }
        public override WebSocketManager WebSockets { get { return ParentContext.WebSockets; } }
        public override ClaimsPrincipal User
        {
            get { return ParentContext.User; }
            set { ParentContext.User = value; }
        }
        public override IDictionary<object, object> Items
        {
            get { return ParentContext.Items; }
            set { ParentContext.Items = value; }
        }

        public override IServiceProvider RequestServices
        {
            get { return ServiceProvidersFeature.RequestServices; }
            set { ServiceProvidersFeature.RequestServices = value; }
        }

        public override CancellationToken RequestAborted
        {
            get { return ParentContext.RequestAborted; }
            set
            {
                ParentContext.RequestAborted = value;
            }
        }

        ///// <summary>
        ///// Reinitialize  the current instant of the class with features passed in.
        ///// </summary>
        ///// <remarks>
        ///// This method allows the consumer to re-use the <see cref="ChildHttpContext" /> for another request, rather than having to allocate a new instance.
        ///// </remarks>
        ///// <param name="features">The new set of features for the <see cref="ChildHttpContext" />.</param>
        //public void Initialize(IFeatureCollection features)
        //{
        //    var revision = features.Revision;
        //    _features.Initalize(features, revision);
        //}

        internal void Uninitialize()
        {
            _features = default;
        }

        public override string TraceIdentifier
        {
            get { return ParentContext.TraceIdentifier; }
            set { ParentContext.TraceIdentifier = value; }
        }
        public override ISession Session
        {
            get { return ParentContext.Session; }
            set { ParentContext.Session = value; }
        }

        internal IServiceScopeFactory ServiceScopeFactory { get; set; }

        public HttpContext ParentContext
        {
            get
            {
                return ChildHttpContextFeature.ParentContext;

            }
        }

        public Func<Task> ParentNext
        {
            get
            {
              // the next middleware delegate in the parents pipeline, passed from the middleware in the parent pipeline.
             // middleware in the child pipeline can access this and chose to "rejoin" the parent pipeline.
                return ChildHttpContextFeature.ParentNext;

            }
        }

        public override void Abort()
        {
            ParentContext.Abort();
        }

        struct FeatureInterfaces
        {         
            public IServiceProvidersFeature ServiceProviders;          
        }

    }

```

I was just exploring this as an idea, but its clear to me I am not understanding something at this point specifically with static files and http/2 it seems. I was very much hoping someone with familiarity in this area might be able to deduce where I am going wrong, why I might be seeing this stack trace given the approach I've taken!  My intention, if I can pull this off, is to migrate this to a new open source project, similar to test server, but more for production usage where teams might want to split monolith apps within the same process, as a preceding step on the journey to microservices.

**Comment by dazinator** [comment]
Ok I didn't get to the root cause but I've managed to eliminate the error by:
1. Don't create a seperate `HttpContext` in the child IHost that shares the `DefaultHttpContext`'s features.. Instead pass through the the existing `DefaultHttpContext` instance itself, and have the `IServer` in the child `IHost` re-use it, setting some additional features temporarily like for RequestServices. This seems to have solved all my http2 issues.
