### ISSUE TITLE
Publish WebAssembly project with library which uses static assets failed

### ISSUE THREAD

**Issue by Morasiu** [dotnet/aspnetcore#34989]
Hello!

I've written [BlazorTimeline ](https://github.com/Morasiu/BlazorTimeline) library which is using static asset icons.

I am using that library[ in my portfolio project](https://github.com/Morasiu/Portfolio). When I am trying to publish it I get error:

Command used:
```
dotnet publish -v d
```

```
       Could not find file 'C:\Users\Morasiu\.nuget\packages\blazortimeline\1.3.1\staticwebassets\.gitkeep'.
            at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
            at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
            at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
            at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
            at System.IO.File.OpenRead(String path)
            at Microsoft.NET.Sdk.BlazorWebAssembly.Tools.BrotliCompressCommand.<ExecuteCoreAsync>b__16_0(Int32 i)
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
         --- End of stack trace from previous location ---
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
            at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
            at System.Threading.Tasks.TaskReplicator.Replica.Execute
```

```
C:\Program Files\dotnet" exited with code 1.
```

Dotnet version: 5.0.302

> Note: It works on `5.0.104`

**Comment by Morasiu** [comment]
UPDATE

It works if I manually add `.gitkeep` file and

```
    <PropertyGroup>
        <NoDefaultExcludes>true</NoDefaultExcludes>
    </PropertyGroup>
```

to my library csproj file.
