### ISSUE TITLE
Quarantine in `WebAssemblyAuthenticationTests`

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#34995]
## Failing Test(s)

-Microsoft.AspNetCore.Components.E2ETest.Tests.WebAssemblyAuthenticationTests.AuthenticatedUser_ProfileIncludesDetails_And_AccessToken

## Error Message

```text
OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.NotEmptyException: Assert.NotEmpty() Failure\r\n   at Xunit.Assert.NotEmpty(IEnumerable collection) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 331\r\n   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<Exists>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 72\r\n   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver ) in //src/Shared/E2ETesting/WaitAssert.cs:line 109\r\nScreen shot captured at 'D:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.AspNetCore.Components.E2ETests\defda19acb674f788574d7bbedcc29dc.png'\r\nEncountered browser errors\r\n[2021-08-03T15:41:20Z] [Debug] http://127.0.0.1:1075/_framework/dotnet.6.0.0-rc.1.21401.1.js 0:129635 "mono_wasm_runtime_ready" "fe00e07a-5519-4dfe-b35a-f867dbaf2e28"Page content:\r\n<head>\r\n    <meta charset="utf-8">\r\n    <meta name="viewport" content="width=device-width">\r\n    <title>Wasm.Authentication.Client</title>\r\n    <base href="/">\r\n    <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet">\r\n    <link href="css/app.css" rel="stylesheet">\r\n</head>\r\n\r\n<body>\r\n    <app><div class="sidebar"><div class="top-row pl-4 navbar navbar-dark"><a class="navbar-brand" href="">Wasm.Authentication.Client

\r\n    <button class="navbar-toggler"><span class="navbar-toggler-icon"></button>
\r\n\r\n<div class="collapse"><ul class="nav flex-column"><li class="nav-item px-3"><a href="" class="nav-link active"><span class="oi oi-home" aria-hidden="true"> Home\r\n            
\r\n        <li class="nav-item px-3"><a href="counter" class="nav-link"><span class="oi oi-plus" aria-hidden="true"> Counter\r\n            \r\n        <li class="nav-item px-3"><a href="fetchdata" class="nav-link"><span class="oi oi-list-rich" aria-hidden="true"> Fetch data\r\n            \r\n        <li class="nav-item px-3"><a href="user" class="nav-link"><span class="oi oi-list-rich" aria-hidden="true"> User\r\n            \r\n        <li class="nav-item px-3"><a href="new-admin" class="nav-link"><span class="oi oi-list-rich" aria-hidden="true"> Make admin\r\n            \r\n        <li class="nav-item px-3"><a href="admin-settings" class="nav-link"><span class="oi oi-list-rich" aria-hidden="true"> Settings\r\n            
\r\n\r\n<div class="main"><div class="top-row px-4 auth">\r\n        <a href="https://docs.microsoft.com/aspnet/" target="_blank">About
\r\n\r\n    <div class="content px-4">Authorizing...
</app>\r\n\r\n    <div id="blazor-error-ui">\r\n        An unhandled error has occurred.\r\n        <a href="" class="reload">Reload\r\n        <a class="dismiss">🗙\r\n    
\r\n\r\n    <script src="_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js">\r\n\r\n\r\n<script src="_framework/dotnet.6.0.0-rc.1.21401.1.js" defer="" integrity="sha256-bqMijSwHUQtnL8n/JrZoGIpyEF3lEQz1vF+fODnU3gw=" crossorigin="anonymous">
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 129
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.Exists(IWebDriver driver, By finder, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 67
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.Exists(IWebDriver driver, By finder) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 54
   at Microsoft.AspNetCore.Components.E2ETest.Tests.WebAssemblyAuthenticationTests.WaitUntilLoaded(Boolean skipHeader) in /_/src/Components/test/E2ETest/Tests/WebAssemblyAuthenticationTests.cs:line 422
   at Microsoft.AspNetCore.Components.E2ETest.Tests.WebAssemblyAuthenticationTests.InitializeAsyncCore() in /_/src/Components/test/E2ETest/Tests/WebAssemblyAuthenticationTests.cs:line 66
   at Microsoft.AspNetCore.E2ETesting.BrowserTestBase.InitializeAsync(String isolationContext) in /_/src/Shared/E2ETesting/BrowserTestBase.cs:line 71
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<Exists>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 72
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 109

```
</details>

## Logs

<details>

```text

```
</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1273293&view=ms.vss-test-web.build-test-results-tab&runId=37651364&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab&resultId=100653

**Comment by TanayParikh** [comment]
Microsoft.AspNetCore.Components.E2ETest.Tests.WebAssemblyAuthenticationTests.CanPreserveApplicationState_DuringLogIn

Log:
```
OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.NotEmptyException: Assert.NotEmpty() Failure\r\n   at Xunit.Assert.NotEmpty(IEnumerable collection) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 331\r\n   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<Exists>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 72\r\n   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver ) in //src/Shared/E2ETesting/WaitAssert.cs:line 109\r\nScreen shot captured at 'D:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.AspNetCore.Components.E2ETests\209100c2aa3349529db425fe914ed416.png'\r\nEncountered browser errors\r\n[2021-08-06T03:23:01Z] [Debug] http://127.0.0.1:26877/_framework/dotnet.6.0.0-rc.1.21401.1.js 0:129635 "mono_wasm_runtime_ready" "fe00e07a-5519-4dfe-b35a-f867dbaf2e28"Page content:\r\n<head>\r\n    <meta charset="utf-8">\r\n    <meta name="viewport" content="width=device-width">\r\n    <title>Wasm.Authentication.Client</title>\r\n    <base href="/">\r\n    <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet">\r\n    <link href="css/app.css" rel="stylesheet">\r\n</head>\r\n\r\n<body>\r\n    <app><div class="sidebar"><div class="top-row pl-4 navbar navbar-dark"><a class="navbar-brand" href="">Wasm.Authentication.Client

\r\n    <button class="navbar-toggler"><span class="navbar-toggler-icon"></button>
\r\n\r\n<div class="collapse"><ul class="nav flex-column"><li class="nav-item px-3"><a href="" class="nav-link active"><span class="oi oi-home" aria-hidden="true"> Home\r\n            
\r\n        <li class="nav-item px-3"><a href="counter" class="nav-link"><span class="oi oi-plus" aria-hidden="true"> Counter\r\n            \r\n        <li class="nav-item px-3"><a href="fetchdata" class="nav-link"><span class="oi oi-list-rich" aria-hidden="true"> Fetch data\r\n            \r\n        <li class="nav-item px-3"><a href="user" class="nav-link"><span class="oi oi-list-rich" aria-hidden="true"> User\r\n            \r\n        <li class="nav-item px-3"><a href="new-admin" class="nav-link"><span class="oi oi-list-rich" aria-hidden="true"> Make admin\r\n            \r\n        <li class="nav-item px-3"><a href="admin-settings" class="nav-link"><span class="oi oi-list-rich" aria-hidden="true"> Settings\r\n            
\r\n\r\n<div class="main"><div class="top-row px-4 auth">\r\n        <a href="https://docs.microsoft.com/aspnet/" target="_blank">About
\r\n\r\n    <div class="content px-4">Authorizing...
</app>\r\n\r\n    <div id="blazor-error-ui">\r\n        An unhandled error has occurred.\r\n        <a href="" class="reload">Reload\r\n        <a class="dismiss">🗙\r\n    
\r\n\r\n    <script src="_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js">\r\n\r\n\r\n<script src="_framework/dotnet.6.0.0-rc.1.21401.1.js" defer="" integrity="sha256-HVnOj1C3vHkQ2OsMR/WOgUYQMjftasIJJyFBpGrwjiE=" crossorigin="anonymous">

```

Stack:
```
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 129
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.Exists(IWebDriver driver, By finder, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 67
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.Exists(IWebDriver driver, By finder) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 54
   at Microsoft.AspNetCore.Components.E2ETest.Tests.WebAssemblyAuthenticationTests.WaitUntilLoaded(Boolean skipHeader) in /_/src/Components/test/E2ETest/Tests/WebAssemblyAuthenticationTests.cs:line 423
   at Microsoft.AspNetCore.Components.E2ETest.Tests.WebAssemblyAuthenticationTests.InitializeAsyncCore() in /_/src/Components/test/E2ETest/Tests/WebAssemblyAuthenticationTests.cs:line 66
   at Microsoft.AspNetCore.E2ETesting.BrowserTestBase.InitializeAsync(String isolationContext) in /_/src/Shared/E2ETesting/BrowserTestBase.cs:line 71
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<Exists>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 72
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 109

```

https://dev.azure.com/dnceng/public/_build/results?buildId=1279568&view=ms.vss-test-web.build-test-results-tab&runId=37823380&resultId=100658&paneView=debug
