### ISSUE TITLE
Quarantine Failing Linux Tests 

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#34992]
## Failing Test(s)

- Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.RequestTests.Http10KeepAliveNotHonoredIfResponseContentLengthNotSet

## Error Message

```text
Assert.Equal() Failure
↓ (pos 75)
Expected: ···807 11:57:47 GMT

Goodbye
Actual:   ···807 11:57:47 GMT

e������
↑ (pos 75)
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.Testing.StreamBackedTestConnection.Receive(String[] lines) in /_/src/Servers/Kestrel/shared/test/StreamBackedTestConnection.cs:line 125
   at Microsoft.AspNetCore.Testing.StreamBackedTestConnection.ReceiveEnd(String[] lines) in /_/src/Servers/Kestrel/shared/test/StreamBackedTestConnection.cs:line 130
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.RequestTests.Http10KeepAliveNotHonoredIfResponseContentLengthNotSet() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/RequestTests.cs:line 751
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.RequestTests.Http10KeepAliveNotHonoredIfResponseContentLengthNotSet() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/RequestTests.cs:line 757
--- End of stack trace from previous location ---
```
</details>

## Logs

<details>

```text
[0.000s] [TestLifetime] [Information] Starting test Http10KeepAliveNotHonoredIfResponseContentLengthNotSet at 2021-08-03T12:51:57
[0.002s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting starting
[0.002s] [Microsoft.Hosting.Lifetime] [Information] Now listening on: http://127.0.0.1:0
[0.002s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Debug] Loaded hosting startup assembly InMemory.FunctionalTests
[0.002s] [Microsoft.Hosting.Lifetime] [Information] Application started. Press Ctrl+C to shut down.
[0.002s] [Microsoft.Hosting.Lifetime] [Information] Hosting environment: Production
[0.002s] [Microsoft.Hosting.Lifetime] [Information] Content root path: /root/helix/work/workitem/
[0.002s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting started
[0.003s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMAMFLPJRFGN" accepted.
[0.003s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMAMFLPJRFGN" started.
[0.003s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request starting HTTP/1.0 GET http:/// - -
[0.003s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMAMFLPJRFGN" completed keep alive response.
[0.003s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request finished HTTP/1.0 GET http:/// - - - 200 0 - 0.1069ms
[0.035s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request starting HTTP/1.0 POST http:/// - 7
[0.035s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "0HMAMFLPJRFGN", Request id "0HMAMFLPJRFGN:00000003": started reading request body.
[0.037s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] Connection id "0HMAMFLPJRFGN", Request id "0HMAMFLPJRFGN:00000003": done reading request body.
[0.038s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request finished HTTP/1.0 POST http:/// - 7 - 200 - - 3.0973ms
[0.038s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMAMFLPJRFGN" disconnecting.
[0.038s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMAMFLPJRFGN" stopped.
[0.038s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting stopping
[0.038s] [Microsoft.Hosting.Lifetime] [Information] Application is shutting down...
[0.039s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting stopped
[0.116s] [Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.RequestTests] [Error] Test threw an exception.
Xunit.Sdk.EqualException: Assert.Equal() Failure
                                     ↓ (pos 75)
Expected: ···807 11:57:47 GMT\r\n\r\nGoodbye
Actual:   ···807 11:57:47 GMT\r\n\r\ne\0\0\0\0\0\0
                                     ↑ (pos 75)
   at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\StringAsserts.cs:line 244
   at Microsoft.AspNetCore.Testing.StreamBackedTestConnection.Receive(String[] lines) in /_/src/Servers/Kestrel/shared/test/StreamBackedTestConnection.cs:line 125
   at Microsoft.AspNetCore.Testing.StreamBackedTestConnection.ReceiveEnd(String[] lines) in /_/src/Servers/Kestrel/shared/test/StreamBackedTestConnection.cs:line 130
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.RequestTests.Http10KeepAliveNotHonoredIfResponseContentLengthNotSet() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/RequestTests.cs:line 751
   at Microsoft.AspNetCore.Server.Kestrel.InMemory.FunctionalTests.RequestTests.Http10KeepAliveNotHonoredIfResponseContentLengthNotSet() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/RequestTests.cs:line 757
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 273
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 54
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 96
[0.117s] [TestLifetime] [Information] Finished test Http10KeepAliveNotHonoredIfResponseContentLengthNotSet in 0.1162396s
```
</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1272938&view=ms.vss-test-web.build-test-results-tab&runId=37646266&resultId=107222&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by Tratcher** [comment]
@halter73 looks similar to #34947?

**Comment by TanayParikh** [comment]
> @halter73 looks similar to #34947?

There's also several failures on `RedHat`: https://dev.azure.com/dnceng/public/_build/results?buildId=1272938&view=ms.vss-test-web.build-test-results-tab&runId=37646264&resultId=108405&paneView=debug

**Comment by Tratcher** [comment]
@TanayParikh that looks related to my last PR: https://github.com/dotnet/aspnetcore/pull/34853. I'll revert it.

**Comment by halter73** [comment]
Thanks @BrennanConroy. Should have stuck with "Addresses" 😆
