### ISSUE TITLE
Quarantining `InputDateInteractsWithEditContext_TimeInput`

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#35018]
## Failing Test(s)

- Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.ServerFormsTest.InputDateInteractsWithEditContext_TimeInput

## Error Message

```text
OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: String[] ["The DepartureTime field must be a time."]
Actual:   String[] ["The DepartureTime field must be a time.", "The VisitMonth field must be a year and month."]
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer1 comparer) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\EqualityAsserts.cs:line 40
 at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 83
 at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_01.<WaitAssertCore>b__0(IWebDriver ) in //src/Shared/E2ETesting/WaitAssert.cs:line 109
Screen shot captured at 'D:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.AspNetCore.Components.E2ETests\7792430a5d3e4494baadcc7f13ed0f09.png'
Encountered browser errors
[2021-08-03T18:04:34Z] [Info] http://127.0.0.1:1081/subdir/_framework/blazor.server.js 0:37412 "[2021-08-03T18:04:34.075Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:1081/subdir/_blazor'."
[2021-08-03T18:04:34Z] [Info] http://127.0.0.1:1081/subdir 47:16 "Blazor server-side"
[2021-08-03T18:04:34Z] [Info] http://127.0.0.1:1081/subdir/_framework/blazor.server.js 0:37412 "[2021-08-03T18:04:34.117Z] Information: WebSocket connected to ws://127.0.0.1:1081/subdir/_blazor?id=vAqLkXaAw7XCETOZaJCYkg."
[2021-08-03T18:04:54Z] [Info] http://127.0.0.1:1081/subdir/_framework/blazor.server.js 0:37412 "[2021-08-03T18:04:54.335Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:1081/subdir/_blazor'."
[2021-08-03T18:04:54Z] [Info] http://127.0.0.1:1081/subdir 47:16 "Blazor server-side"
[2021-08-03T18:04:54Z] [Info] http://127.0.0.1:1081/subdir/_framework/blazor.server.js 0:37412 "[2021-08-03T18:04:54.358Z] Information: WebSocket connected to ws://127.0.0.1:1081/subdir/_blazor?id=my9_k6eZtC37ZZuJhzduxA."
[2021-08-03T18:04:56Z] [Info] http://127.0.0.1:1081/subdir/_framework/blazor.server.js 0:37412 "[2021-08-03T18:04:56.926Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:1081/subdir/_blazor'."
[2021-08-03T18:04:56Z] [Info] http://127.0.0.1:1081/subdir 47:16 "Blazor server-side"
[2021-08-03T18:04:56Z] [Info] http://127.0.0.1:1081/subdir/_framework/blazor.server.js 0:37412 "[2021-08-03T18:04:56.932Z] Information: WebSocket connected to ws://127.0.0.1:1081/subdir/_blazor?id=UeevRbfFHmSO3XWu2cAjng."
[2021-08-03T18:04:57Z] [Info] http://127.0.0.1:1081/subdir/_framework/blazor.server.js 0:37412 "[2021-08-03T18:04:57.481Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:1081/subdir/_blazor'."
[2021-08-03T18:04:57Z] [Info] http://127.0.0.1:1081/subdir 47:16 "Blazor server-side"
[2021-08-03T18:04:57Z] [Info] http://127.0.0.1:1081/subdir/_framework/blazor.server.js 0:37412 "[2021-08-03T18:04:57.487Z] Information: WebSocket connected to ws://127.0.0.1:1081/subdir/_blazor?id=fYi2IgiRg7sUTYTxjNzQXA."
[2021-08-03T18:04:57Z] [Info] http://127.0.0.1:1081/subdir/_framework/blazor.server.js 0:37412 "[2021-08-03T18:04:57.887Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:1081/subdir/_blazor'."
[2021-08-03T18:04:57Z] [Info] http://127.0.0.1:1081/subdir 47:16 "Blazor server-side"
[2021-08-03T18:04:57Z] [Info] http://127.0.0.1:1081/subdir/_framework/blazor.server.js 0:37412 "[2021-08-03T18:04:57.893Z] Information: WebSocket connected to ws://127.0.0.1:1081/subdir/_blazor?id=eWoyZ0KVXxAUeArMtCIuWA."
[2021-08-03T18:04:59Z] [Info] http://127.0.0.1:1081/subdir/_framework/blazor.server.js 0:37412 "[2021-08-03T18:04:59.537Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:1081/subdir/_blazor'."
[2021-08-03T18:04:59Z] [Info] http://127.0.0.1:1081/subdir 47:16 "Blazor server-side"
[2021-08-03T18:04:59Z] [Info] http://127.0.0.1:1081/subdir/_framework/blazor.server.js 0:37412 "[2021-08-03T18:04:59.
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 129
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore(IWebDriver driver, Action assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 84
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.Equal[T](IWebDriver driver, T expected, Func`1 actual) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 27
   at Microsoft.AspNetCore.Components.E2ETest.Tests.FormsTest.InputDateInteractsWithEditContext_TimeInput() in /_/src/Components/test/E2ETest/Tests/FormsTest.cs:line 272
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 83
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 109

```
</details>

## Logs

<details>

```text

```
</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1273293&view=ms.vss-test-web.build-test-results-tab&runId=37656758&resultId=100181&paneView=debug

**Comment by TanayParikh** [comment]
Also:

InputDateInteractsWithEditContext_NonNullableDateTime

Error:
```
OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.EqualException: Assert.Equal() Failure\r\nExpected: modified valid\r\nActual:   modified invalid\r\n   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer1 comparer) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\EqualityAsserts.cs:line 40\r\n at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 83\r\n at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_01.<WaitAssertCore>b__0(IWebDriver ) in //src/Shared/E2ETesting/WaitAssert.cs:line 109\r\nScreen shot captured at 'D:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.AspNetCore.Components.E2ETests\ed757d44539647f38e717af3bb457a22.png'\r\nEncountered browser errors\r\n[2021-08-04T18:03:27Z] [Info] http://127.0.0.1:13072/subdir/_framework/blazor.server.js 0:37412 "[2021-08-04T18:03:27.323Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:13072/subdir/_blazor'."\r\n[2021-08-04T18:03:27Z] [Info] http://127.0.0.1:13072/subdir 47:16 "Blazor server-side"\r\n[2021-08-04T18:03:27Z] [Info] http://127.0.0.1:13072/subdir/_framework/blazor.server.js 0:37412 "[2021-08-04T18:03:27.360Z] Information: WebSocket connected to ws://127.0.0.1:13072/subdir/_blazor?id=roRpKGUuzLpKI6deSriQuw."\r\n[2021-08-04T18:03:52Z] [Info] http://127.0.0.1:13072/subdir/_framework/blazor.server.js 0:37412 "[2021-08-04T18:03:52.543Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:13072/subdir/_blazor'."\r\n[2021-08-04T18:03:52Z] [Info] http://127.0.0.1:13072/subdir 47:16 "Blazor server-side"\r\n[2021-08-04T18:03:52Z] [Info] http://127.0.0.1:13072/subdir/_framework/blazor.server.js 0:37412 "[2021-08-04T18:03:52.583Z] Information: WebSocket connected to ws://127.0.0.1:13072/subdir/_blazor?id=pECPLYI0-NiqWCHSWiI5lQ."\r\n[2021-08-04T18:03:54Z] [Info] http://127.0.0.1:13072/subdir/_framework/blazor.server.js 0:37412 "[2021-08-04T18:03:54.755Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:13072/subdir/_blazor'."\r\n[2021-08-04T18:03:54Z] [Info] http://127.0.0.1:13072/subdir 47:16 "Blazor server-side"\r\n[2021-08-04T18:03:54Z] [Info] http://127.0.0.1:13072/subdir/_framework/blazor.server.js 0:37412 "[2021-08-04T18:03:54.762Z] Information: WebSocket connected to ws://127.0.0.1:13072/subdir/_blazor?id=y-xbiH_TUbtgTn0XhJRo2w."\r\n[2021-08-04T18:03:56Z] [Info] http://127.0.0.1:13072/subdir/_framework/blazor.server.js 0:37412 "[2021-08-04T18:03:56.613Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:13072/subdir/_blazor'."\r\n[2021-08-04T18:03:56Z] [Info] http://127.0.0.1:13072/subdir 47:16 "Blazor server-side"\r\n[2021-08-04T18:03:56Z] [Info] http://127.0.0.1:13072/subdir/_framework/blazor.server.js 0:37412 "[2021-08-04T18:03:56.621Z] Information: WebSocket connected to ws://127.0.0.1:13072/subdir/_blazor?id=Q1kceISlEbooYKsGvvG9vw."\r\n[2021-08-04T18:03:57Z] [Info] http://127.0.0.1:13072/subdir/_framework/blazor.server.js 0:37412 "[2021-08-04T18:03:57.018Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:13072/subdir/_blazor'."\r\n[2021-08-04T18:03:57Z] [Info] http://127.0.0.1:13072/subdir 47:16 "Blazor server-side"\r\n[2021-08-04T18:03:57Z] [Info] http://127.0.0.1:13072/subdir/_framework/blazor.server.js 0:37412 "[2021-08-04T18:03:57.025Z] Information: WebSocket connected to ws://127.0.0.1:13072/subdir/_blazor?id=iV86B-yR86ou_fh4h4Z25Q."\r\n[2021-08-04T18:03:58Z] [Info] http://127.0.0.1:13072/subdir/_framework/blazor.server.js 0:37412 "[2021-08-04T18:03:58.458Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:13072/subdir/_blazor'."\r\n[2021-08-04T18:03:58Z] [Info] http://127.0.0.1:13072/subdir 47:16 "Blazor server-side"\r\n[2021-08-04T18:03:58Z] [Info] http://127.0.0.1:13072/subdir/_framework/blazor.server.js 0:37412 "[2021-08-04T18:03:58.463Z] Information: WebSocket connected to ws://127.0.0.1:13072/subdir/_blazor?id=PNMPIfdS98kQ8n6rjGNx
```

Stack:
```
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 129
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore(IWebDriver driver, Action assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 84
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.Equal[T](IWebDriver driver, T expected, Func`1 actual) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 27
   at Microsoft.AspNetCore.Components.E2ETest.Tests.FormsTest.InputDateInteractsWithEditContext_NonNullableDateTime() in /_/src/Components/test/E2ETest/Tests/FormsTest.cs:line 211
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 83
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 109
```

Build:
https://dev.azure.com/dnceng/public/_build/results?buildId=1276154&view=ms.vss-test-web.build-test-results-tab&runId=37746470&resultId=100511&paneView=debug

**Comment by pranavkm** [comment]
It works on my machine. Are you sure this test failure is legit?

**Comment by rokonec** [comment]
Reopening: the `FormsInputDateTest` family (including this test) is flaky again in the `aspnetcore-components-e2e` pipeline and is being re-quarantined on the servicing branches release/8.0 (#67157) and release/9.0 (#67156) so unrelated backports are not blocked.

Observed CI failure in a sibling test of the same class (`InputDateInteractsWithEditContext_NonNullableDateTime`, tracked in #31734):

```text
OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: modified valid
Actual:   modified invalid
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer)
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /home/vsts/work/1/s/src/Shared/E2ETesting/WaitAssert.cs:line 101
```

Same `SendKeys` keyboard-input timing flakiness previously tracked here.

**Comment by Youssef1313** [comment]
Removing milestone so that it doesn't get lost and gets re-triaged as appropriate.

**Comment by Youssef1313** [comment]
@rokonec Was it only flaky on the release branches? Or is this affecting main as well?

**Comment by ilonatommy** [comment]
Only net9.0 and net8.0

https://github.com/dotnet/aspnetcore/blob/74cec083dfb129b922ca07460df34962fc6b9eed/src/Components/test/E2ETest/Tests/FormsInputDateTest.cs#L94

https://github.com/dotnet/aspnetcore/blob/948ce52375047cf8af8ab5dbbf198b70b046bd09/src/Components/test/E2ETest/Tests/FormsInputDateTest.cs#L94

Similar to https://github.com/dotnet/aspnetcore/issues/31734#issuecomment-5105858694.

**Comment by ilonatommy** [comment]
Being addressed by https://github.com/dotnet/aspnetcore/pull/68126 and https://github.com/dotnet/aspnetcore/pull/68125

**Comment by ilonatommy** [comment]
No failures on net8, net9 in the last 30 days.
