### ISSUE TITLE
Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.ServerJSRootComponentsTest.CannotAddMultipleRootComponentsToTheSameElementAtTheSameTime

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#35106]
## Failing Test(s)

- Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.ServerJSRootComponentsTest.CannotAddMultipleRootComponentsToTheSameElementAtTheSameTime

## Error Message

```text
OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.EqualException: Assert.Equal() Failure\r\nExpected: block\r\nActual:   none\r\n   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer1 comparer) in C:\\Dev\\xunit\\xunit\\src\\xunit.assert\\Asserts\\EqualityAsserts.cs:line 40\r\n at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 83\r\n at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_01.<WaitAssertCore>b__0(IWebDriver ) in //src/Shared/E2ETesting/WaitAssert.cs:line 109\r\nScreen shot captured at 'D:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.AspNetCore.Components.E2ETests\50de5613c35842a4af75b4451250b1fa.png'\r\nEncountered browser errors\r\n[2021-08-06T11:42:58Z] [Info] http://127.0.0.1:1112/subdir/_framework/blazor.server.js 0:37623 "[2021-08-06T11:42:58.746Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:1112/subdir/_blazor'."\r\n[2021-08-06T11:42:58Z] [Info] http://127.0.0.1:1112/subdir 47:16 "Blazor server-side"\r\n[2021-08-06T11:42:58Z] [Info] http://127.0.0.1:1112/subdir/_framework/blazor.server.js 0:37623 "[2021-08-06T11:42:58.768Z] Information: WebSocket connected to ws://127.0.0.1:1112/subdir/_blazor?id=r6DyZFs84c0EAohu0Yf_RA."\r\n[2021-08-06T11:42:58Z] [Info] http://127.0.0.1:1112/subdir/_framework/blazor.server.js 0:37623 "[2021-08-06T11:42:58.971Z] Information: Normalizing '_blazor' to 'http://127.0.0.1:1112/subdir/_blazor'."\r\n[2021-08-06T11:42:58Z] [Info] http://127.0.0.1:1112/subdir 47:16 "Blazor server-side"\r\n[2021-08-06T11:42:58Z] [Info] http://127.0.0.1:1112/subdir/_framework/blazor.server.js 0:37623 "[2021-08-06T11:42:58.977Z] Information: WebSocket connected to ws://127.0.0.1:1112/subdir/_blazor?id=_RZjxq93Hi19rdn4mS-GZQ."Page content:\r\n<head>\r\n    <meta charset="utf-8">\r\n    <title>Basic test app</title>\r\n    <base href="/subdir/">\r\n    <link href="style.css" rel="stylesheet">\r\n    <link rel="icon" href="data:,">\r\n\r\n    \r\n    <link href="_content/TestContentPackage/styles.css" rel="stylesheet">\r\n    <link href="Components.TestServer.styles.css" rel="stylesheet">\r\n</head>\r\n<body>\r\n    <root><div id="test-selector">\r\n    Select test:\r\n    <select id="test-selector-select"><option value="none">Choose...\r\n        <option value="BasicTestApp.AfterRenderInteropComponent">After-render interop component\r\n        <option value="BasicTestApp.AuthTest.AuthRouter">Auth cases\r\n        <option value="BasicTestApp.BindCasesComponent">bind cases\r\n        <option value="BasicTestApp.ComponentRefComponent">Component ref component\r\n        <option value="BasicTestApp.ConfigurationComponent">Configuration
```

## Stacktrace

<details>

```text
at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 129
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore(IWebDriver driver, Action assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 84
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.Equal[T](IWebDriver driver, T expected, Func`1 actual) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 27
   at Microsoft.AspNetCore.Components.E2ETest.Tests.JSRootComponentsTest.AssertGlobalErrorState(Boolean hasGlobalError) in /_/src/Components/test/E2ETest/Tests/JSRootComponentsTest.cs:line 233
   at Microsoft.AspNetCore.Components.E2ETest.Tests.JSRootComponentsTest.CannotAddMultipleRootComponentsToTheSameElementAtTheSameTime() in /_/src/Components/test/E2ETest/Tests/JSRootComponentsTest.cs:line 98
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_0.<WaitAssertCore>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 83
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 109
```
</details>

## Logs

<details>

```text

```
</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1279940&view=ms.vss-test-web.build-test-results-tab&runId=37831626&resultId=100583&paneView=debug

**Comment by SteveSandersonMS** [comment]
Closing because since all the work to make E2E tests more reliable, they are now extremely reliable (100% pass rate as far back as the stats go, and yes [they are still able to report failures](https://github.com/dotnet/aspnetcore/pull/38115)).

I verified that this specific test is running and part of that pass rate.
