### ISSUE TITLE
Microsoft.AspNetCore.Components.E2ETest.Tests.WebAssemblyAuthenticationTests.CanPreserveApplicationState_DuringLogIn

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#35108]
## Failing Test(s)

- Microsoft.AspNetCore.Components.E2ETest.Tests.WebAssemblyAuthenticationTests.CanPreserveApplicationState_DuringLogIn

## Error Message

```text
OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.NotEmptyException: Assert.NotEmpty() Failure
   at Xunit.Assert.NotEmpty(IEnumerable collection) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\CollectionAsserts.cs:line 331
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<Exists>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 72
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver ) in //src/Shared/E2ETesting/WaitAssert.cs:line 109
Screen shot captured at 'D:\workspace\_work\1\s\artifacts\TestResults\Release\Microsoft.AspNetCore.Components.E2ETests\14b229fda1fa463d94a9676847d24e3c.png'
Encountered browser errors
[2021-08-06T13:42:05Z] [Debug] http://127.0.0.1:7464/_framework/dotnet.6.0.0-rc.1.21401.1.js 0:129635 "mono_wasm_runtime_ready" "fe00e07a-5519-4dfe-b35a-f867dbaf2e28"Page content:
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>Wasm.Authentication.Client</title>
    <base href="/">
    <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet">
    <link href="css/app.css" rel="stylesheet">
</head>

<body>
    <app><div class="sidebar"><div class="top-row pl-4 navbar navbar-dark"><a class="navbar-brand" href="">Wasm.Authentication.Client
```

## Stacktrace

<details>
```text
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 129
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.Exists(IWebDriver driver, By finder, TimeSpan timeout) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 67
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.Exists(IWebDriver driver, By finder) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 54
   at Microsoft.AspNetCore.Components.E2ETest.Tests.WebAssemblyAuthenticationTests.WaitUntilLoaded(Boolean skipHeader) in /_/src/Components/test/E2ETest/Tests/WebAssemblyAuthenticationTests.cs:line 423
   at Microsoft.AspNetCore.Components.E2ETest.Tests.WebAssemblyAuthenticationTests.InitializeAsyncCore() in /_/src/Components/test/E2ETest/Tests/WebAssemblyAuthenticationTests.cs:line 66
   at Microsoft.AspNetCore.E2ETesting.BrowserTestBase.InitializeAsync(String isolationContext) in /_/src/Shared/E2ETesting/BrowserTestBase.cs:line 71
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass15_0.<Exists>b__0() in /_/src/Shared/E2ETesting/WaitAssert.cs:line 72
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /_/src/Shared/E2ETesting/WaitAssert.cs:line 109
```
</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1279887&view=ms.vss-test-web.build-test-results-tab&runId=37835026&resultId=100641&paneView=debug

**Comment by javiercn** [comment]
The tests is unskipped now since we added retries.
