### ISSUE TITLE
Microsoft.AspNetCore.Hosting.Tests.HostingApplicationTests.IHttpActivityFeatureIsPopulated

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#35142]
## Failing Test(s)

- Microsoft.AspNetCore.Hosting.Tests.HostingApplicationTests.IHttpActivityFeatureIsPopulated

## Error Message

```text
Assert.NotEqual() Failure
Expected: Not Activity { ActivityTraceFlags = None, Baggage = [], Context = System.Diagnostics.ActivityContext, DisplayName = "Microsoft.AspNetCore.Hosting.HttpRequestIn", Duration = 00:00:00, ... }
Actual:   Activity { ActivityTraceFlags = None, Baggage = [], Context = System.Diagnostics.ActivityContext, DisplayName = "Microsoft.AspNetCore.Hosting.HttpRequestIn", Duration = 00:00:00, ... }
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.Hosting.Tests.HostingApplicationTests.IHttpActivityFeatureIsPopulated() in /_/src/Hosting/Hosting/test/HostingApplicationTests.cs:line 122
```
</details>

## Logs

<details>

```text
[xUnit.net 00:00:01.21]     Microsoft.AspNetCore.Hosting.Tests.HostingApplicationTests.IHttpActivityFeatureIsPopulated [FAIL]
[xUnit.net 00:00:01.21]       Assert.NotEqual() Failure
[xUnit.net 00:00:01.21]       Expected: Not Activity { ActivityTraceFlags = None, Baggage = [], Context = System.Diagnostics.ActivityContext, DisplayName = "Microsoft.AspNetCore.Hosting.HttpRequestIn", Duration = 00:00:00, ... }
[xUnit.net 00:00:01.21]       Actual:   Activity { ActivityTraceFlags = None, Baggage = [], Context = System.Diagnostics.ActivityContext, DisplayName = "Microsoft.AspNetCore.Hosting.HttpRequestIn", Duration = 00:00:00, ... }
[xUnit.net 00:00:01.21]       Stack Trace:
[xUnit.net 00:00:01.21]         /_/src/Hosting/Hosting/test/HostingApplicationTests.cs(122,0): at Microsoft.AspNetCore.Hosting.Tests.HostingApplicationTests.IHttpActivityFeatureIsPopulated()
```
</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1280595&view=ms.vss-test-web.build-test-results-tab&runId=37844528&resultId=103322&paneView=debug

**Comment by shirhatti** [comment]
The only theory I could come up with any credence is that there is another test running concurrently that changes the `ActivityIdFormat` and hence I'll also need to specify a `SampleUsingParentId` delegate.

That said I can't find any test changing the `ActivityIdFormat`

**Comment by adityamandaleeka** [comment]
Closing until this happens again...

**Comment by JamesNK** [comment]
Hasn't failed lately. Added some extra asserts in https://github.com/dotnet/aspnetcore/pull/47679

If it fails again - my theory is `CreateActivity` to create the nested activity is returning null - then there should be some more info.
