### ISSUE TITLE
Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http3ConnectionTests.GOAWAY_GracefulServerShutdown_SendsGoAway(connectionRequests: 512, expectedStreamId: 2048)

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#35149]
## Failing Test(s)

- Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http3ConnectionTests.GOAWAY_GracefulServerShutdown_SendsGoAway(connectionRequests: 512, expectedStreamId: 2048)

## Error Message

```text
System.InvalidOperationException : Expected stream ID 2048, got 4611686018427387903.
```

## Stacktrace

<details>

```text
  at Microsoft.AspNetCore.Testing.Http3InMemory.VerifyGoAway(Http3FrameWithPayload frame, Int64 expectedLastStreamId) in /_/src/Servers/Kestrel/shared/test/Http3/Http3InMemory.cs:line 197
   at Microsoft.AspNetCore.Testing.Http3InMemory.WaitForGoAwayAsync(Boolean ignoreNonGoAwayFrames, Nullable`1 expectedLastStreamId) in /_/src/Servers/Kestrel/shared/test/Http3/Http3InMemory.cs:line 172
   at Microsoft.AspNetCore.Testing.Http3InMemory.WaitForConnectionErrorAsync[TException](Boolean ignoreNonGoAwayFrames, Nullable`1 expectedLastStreamId, Http3ErrorCode expectedErrorCode, Action`2 matchExpectedErrorMessage, String[] expectedErrorMessage) in /_/src/Servers/Kestrel/shared/test/Http3/Http3InMemory.cs:line 143
   at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http3ConnectionTests.GOAWAY_GracefulServerShutdown_SendsGoAway(Int32 connectionRequests, Int32 expectedStreamId) in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http3/Http3ConnectionTests.cs:line 100
--- End of stack trace from previous location ---
```
</details>

## Logs

<details>

```text

```
</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1282189&view=ms.vss-test-web.build-test-results-tab&runId=37877462&resultId=109138&paneView=debug

**Comment by HaoK** [comment]
Looks like a fix was made and this test was never quarantined, so can resolve
