### ISSUE TITLE
NET 6.0 React SPA template - consider adding an onError handler to setupProxy.js to prevent websocket connection crashes

### ISSUE THREAD

**Issue by JakeYal** [dotnet/aspnetcore#35155]
### The problem

The new NET 6.0 React SPA template uses the http-proxy-middleware package to proxy http requests from the React dev server to ASP Net Core.

If a project uses websockets, these need to be proxied in a specific way:

```javascript
// ./src/setupProxy.js 

const myWebsocketProxy = createProxyMiddleware("/hub", {
    ws: true,
    //... other settings
});
```

Unfortunately, whenever the backend webserver is restarted, it causes the react dev server to crash due to the websocket connection no longer being available and throwing an error:

```
[HPM] Error occurred while proxying request localhost:5002/hub/myhub to undefined [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
Emitted 'error' event on TLSSocket instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
error Command failed with exit code 1.
```

Which means you now need to recompile your entire front-end application whenever you restart the backend webserver. This is quite slow and effects the inner-loop significantly, especially for larger apps.

### Proposed solution

Checking the documentation for http-proxy-middleware, we can pass an `onError` handler to it to handle any exceptions:
```javascript
// ./src/setupProxy.js 

const onError = (err, req, resp, target) => {
    console.log(`${err.message}`);
};

const myWebsocketProxy = createProxyMiddleware("/hub", {
    ws: true,
    //handle errors produced by http-proxy-middleware to prevent the react dev server from completing crashing
    onError: onError 
    //... other settings
});
```

This stops the dev server from crashing outright:

```
connect ECONNREFUSED 127.0.0.1:5001
[HPM] Error occurred while proxying request localhost:5002/hub/myhub to undefined [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

I propose adding this error handler to the proxy defined in ./src/setupProxy.js by default, to improve the inner-loop for new developers. 

This file is already something that may need to edited manually by developers as they add new API endpoints, so adding an error handler that may also want to modify isn't a huge leap.

**Comment by javiercn** [comment]
@JakeYallop thanks for contacting us.

Your suggestion sounds appropriate. Is there a way to add the error handling globally or does it have to be within an endpoint?

Also, we would gladly accept a PR for this if you are willing to contribute it. We've moved the spa templates to [here](https://github.com/dotnet/spa-templates)

**Comment by JakeYallop** [comment]
There isn't really a way to set global options - all we're really doing when we call `createProxyMiddleware` is to create a piece of middleware that the express server created by React dev tools then uses. We can pass more than one endpoint (and this is what the template already does, I just simplified my example above).

**Comment by javiercn** [comment]
@JakeYallop I apologize, I didn't express myself correctly. I meant if we can do it [here](https://github.com/dotnet/spa-templates/blob/main/src/content/React-CSharp/ClientApp/src/setupProxy.js#L18-L22) as a one time thing, or if we need to do it on a per endpoint basis.

At least the function to handle the errors should be defined in one place, that's all I'm asking for.

**Comment by JakeYallop** [comment]
Ah - yep, that's totally possible - we don't need to add error handling per endpoint.
