### ISSUE TITLE
HTTP/3 for non-IPEndPoint's

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#35200]
QuicListener explicitly requries an IPEndPoint.
https://github.com/dotnet/aspnetcore/blob/83927d9c988b88a8d1c29c324a4a62231a7f8c05/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicConnectionListener.cs#L39
https://github.com/dotnet/runtime/blob/2be518a33f71867e90557c92770e37d956174ffd/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicListenerOptions.cs#L21

ListenOptions also supports UnixDomainSocketEndPoint, FileHandleEndPoint, and custom endpoints. There isn't any check for these in the HTTP/3 code path right now except that soft-cast to an IPEndPoint which will produce a hard to decipher error.

```C#
                        options.ListenUnixSocket("/foo", listenOptions =>
                        {
                            listenOptions.Protocols = HttpProtocols.Http1AndHttp2AndHttp3;
                            listenOptions.UseHttps();
                        });
                        // Or
                        options.ListenHandle(0u, listenOptions =>
                        {
                            listenOptions.Protocols = HttpProtocols.Http3;
                            listenOptions.UseHttps();
                        });
```

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.Quic.Implementations.MsQuic.Internal.MsQuicAddressHelpers.IPEndPointToINet(IPEndPoint endpoint)
   at System.Net.Quic.Implementations.MsQuic.MsQuicListener.Start(QuicListenerOptions options)
   at System.Net.Quic.Implementations.MsQuic.MsQuicListener..ctor(QuicListenerOptions options)
   at System.Net.Quic.Implementations.MsQuic.MsQuicImplementationProvider.CreateListener(QuicListenerOptions options)
   at System.Net.Quic.QuicListener..ctor(QuicListenerOptions options)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionListener..ctor(QuicTransportOptions options, IQuicTrace log, EndPoint endpoint, SslServerAuthenticationOptions sslServerAuthenticationOptions) in D:\github\aspnetcore\src\Servers\Kestrel\Transport.Quic\src\Internal\QuicConnectionListener.cs:line 44
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.QuicTransportFactory.BindAsync(EndPoint endpoint, IFeatureCollection features, CancellationToken cancellationToken) in D:\github\aspnetcore\src\Servers\Kestrel\Transport.Quic\src\QuicTransportFactory.cs:line 63
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, MultiplexedConnectionDelegate multiplexedConnectionDelegate, ListenOptions listenOptions, CancellationToken cancellationToken) in D:\github\aspnetcore\src\Servers\Kestrel\Core\src\Internal\Infrastructure\TransportManager.cs:line 72
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass29_0`1.<<StartAsync>g__OnBind|0>d.MoveNext() in D:\github\aspnetcore\src\Servers\Kestrel\Core\src\Internal\KestrelServerImpl.cs:line 222
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken) in D:\github\aspnetcore\src\Servers\Kestrel\Core\src\Internal\AddressBinder.cs:line 94
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken) in D:\github\aspnetcore\src\Servers\Kestrel\Core\src\ListenOptions.cs:line 195
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken) in D:\github\aspnetcore\src\Servers\Kestrel\Core\src\Internal\AddressBinder.cs:line 225
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken) in D:\github\aspnetcore\src\Servers\Kestrel\Core\src\Internal\AddressBinder.cs:line 36
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken) in D:\github\aspnetcore\src\Servers\Kestrel\Core\src\Internal\KestrelServerImpl.cs:line 308
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken) in D:\github\aspnetcore\src\Servers\Kestrel\Core\src\Internal\KestrelServerImpl.cs:line 228
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken) in D:\github\aspnetcore\src\Hosting\Hosting\src\GenericHost\GenericWebHostedService.cs:line 123
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Http3SampleApp.Program.Main(String[] args) in D:\github\aspnetcore\src\Servers\Kestrel\samples\Http3SampleApp\Program.cs:line 89
```

For 6.0 consider at least adding a more explicit error.

**Comment by JamesNK** [comment]
Error messages are good for .NET 6.

For .NET 7, can HTTP/3 happen over different endpoints? I'm guessing it can't. It's not like HTTP/1.1 and HTTP/2 where we just need a stream of bytes. HTTP/3 requires a multiplexed transport.

**Comment by Tratcher** [comment]
I doubt this would ever actually be supported.

**Comment by adityamandaleeka** [comment]
OK, let's just add a more explicit error when this is encountered.
