### ISSUE TITLE
Generic startup issue

### ISSUE THREAD

**Issue by Andrey26** [dotnet/aspnetcore#35256]
**Issue:**
When attempting to execute `dotnet swagger tofile` on `dll` with generic `Startup` class if fails to locate it.
I do not think that It is Swashbuckle library issue because .NET code fails to locate `dll`.

**Reproduction scenario:**
1. From VS create a new _ASP.NET Core Web Application_. You can select ASP.NET Core Web API to have request and working API.
![image](https://user-images.githubusercontent.com/7716864/128931065-111f45b2-7794-4823-bf43-3e3d8e7aed94.png)
2. In `Startup.cs`, rewrite `Startup` to `Startup<T>`. Therefore in `Program.cs`, rewrite
```
webBuilder.UseStartup();
```
to (for example)
```
webBuilder.UseStartup<Startup<int>>();
```
3. From cmd execute `dotnet new tool-manifest` in root folder of the project
4. From cmd execute `dotnet tool install --local --version ${​​​​swaggerVersion}​​​​ Swashbuckle.AspNetCore.Cli`
where `${​​​​swaggerVersion}`​​​​ - is a version of `Swashbuckle.AspNetCore.Swagger.dll` located together with `.dll`
5. From cmd execute `dotnet tool restore`
6. From cmd execute `dotnet swagger tofile --output <json documentation file name to generate> <full path to .dll> <version of Web Service API>`

**Result:**
```
Unhandled exception. System.InvalidOperationException: A type named 'StartupProduction' or 'Startup' could not be found in assembly 'WebApplication1'.
   at Microsoft.AspNetCore.Hosting.StartupLoader.FindStartupType(String startupAssemblyName, String environmentName)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.<>c__DisplayClass14_2.<BuildCommonServices>b__2(IServiceProvider _)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureStartup()
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()

```

**Expected:**
`Swagger JSON/YAML succesfully written to <file path>`

**Assumption:**
Called code only checks with `Startup` name and name of generic class will be different.
https://github.com/dotnet/aspnetcore/blob/371a26f07b23ad77c636332c2dfc0cbd1d8137ba/src/Hosting/Hosting/src/Internal/StartupLoader.cs#L243
https://github.com/dotnet/aspnetcore/blob/371a26f07b23ad77c636332c2dfc0cbd1d8137ba/src/Hosting/Hosting/src/Internal/StartupLoader.cs#L269

**Comment by Tratcher** [comment]
Does `dotnet run` work with a generic startup?

**Comment by SviatoslavVilkovych** [comment]
> Does `dotnet run` work with a generic startup?
Yes, without any problems.

**Comment by Tratcher** [comment]
Is there any more to that stack trace? Who's calling WebHostBuilder.Build in this tool?

I ask because the templates haven't used WebHostBuilder since 2.2, it was replaced by HostBuilder.
https://github.com/dotnet/aspnetcore/blob/139bd5c3444473c1621ef6cc7ef88912d00f1578/src/ProjectTemplates/Web.ProjectTemplates/content/WebApi-CSharp/Program.cs#L20-L21

**Comment by Tratcher** [comment]
Ah:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/cc13950b6bdba54c233851a26a42153f7f89e9ee/src/Swashbuckle.AspNetCore.Cli/Program.cs#L143-L144

**Comment by adityamandaleeka** [comment]
Triage: this particular issue with Swashbuckle will likely go away now that  https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2147/ is done which updates Swashbuckle to use the new host.

**Comment by adityamandaleeka** [comment]
As a workaround, you could add a class that derives from Startup, or use `SwaggerHostFactory` as described here: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/README.md#swashbuckleaspnetcorecli.

Closing the issue.
