### ISSUE TITLE
Blazor WASM Dotnet6-Preview7, InvalidOperationException 'There was an error parsing the event arguments' when attaching a click handler to a button.

### ISSUE THREAD

**Issue by MaxxDelusional** [dotnet/aspnetcore#35280]
### Describe the bug

I am unable to attach a callback method to the onclick event of a button. When the button is clicked an InvalidOperationException is logged in the console. 

### To Reproduce

Simple page component.

```
@page "/test"

<h3>Test Page</h3>

<button @onclick="TestClick">Test</button>

<div>@Data</div>

@code {

	protected string Data { get; set; }

	public void TestClick(MouseEventArgs args)
	{
		Data = "You clicked it";
	}
}
```

The content of the div tag is never updated.

The event is failing for any method signature.
- `public void TestClick(MouseEventArgs args)`
- `public void TestClick()`
- `public Task TestClick(MouseEventArgs args)`
- `public Task TestClick()`
- `protected void TestClick(MouseEventArgs args)`
- `private void TestClick(MouseEventArgs args)`

It also fails if I include the '@' character in front of the method name

`<button @onclick="@TestClick">Test</button>`

Using a lamba does not work

`<button @onclick="@(e => TestClick())">Test</button>`

Clean, Rebuild, Restart, etc, failed to fix the problem.

### Exceptions (if any)
```
blazor.webassembly.js:1 Uncaught (in promise) Error: System.InvalidOperationException: There was an error parsing the event arguments. EventId: '2'.
 ---> System.MissingMethodException: Method not found: System.Text.Json.Serialization.Metadata.JsonPropertyInfo System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<!0>(System.Text.Json.JsonSerializerOptions,bool,System.Type,System.Text.Json.Serialization.Metadata.JsonTypeInfo,System.Text.Json.Serialization.JsonConverter`1<!!0>,System.Func`2<object, !!0>,System.Action`2<object, !!0>,System.Text.Json.Serialization.JsonIgnoreCondition,System.Text.Json.Serialization.JsonNumberHandling,string,string)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.InitializePropCache() in System.Text.Json.dll:token 0x60008f4+0x21
   at System.Text.Json.Serialization.Converters.JsonMetadataServicesConverter`1[[Microsoft.AspNetCore.Components.Web.MouseEventArgs, Microsoft.AspNetCore.Components.Web, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, MouseEventArgs& value) in System.Text.Json.dll:token 0x600094d+0x1e
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.Web.MouseEventArgs, Microsoft.AspNetCore.Components.Web, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, MouseEventArgs& value) in System.Text.Json.dll:token 0x600078d+0x197
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.Web.MouseEventArgs, Microsoft.AspNetCore.Components.Web, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) in System.Text.Json.dll:token 0x6000779+0xbf
   at System.Text.Json.JsonSerializer.ReadCore[MouseEventArgs](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) in System.Text.Json.dll:token 0x6000395+0xa
   at System.Text.Json.JsonSerializer.ReadUsingMetadata[MouseEventArgs](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount) in System.Text.Json.dll:token 0x6000396+0x2f
   at System.Text.Json.JsonSerializer.ReadUsingMetadata[MouseEventArgs](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo) in System.Text.Json.dll:token 0x60003b7+0x4c
   at System.Text.Json.JsonSerializer.Deserialize[MouseEventArgs](String json, JsonTypeInfo`1 jsonTypeInfo) in System.Text.Json.dll:token 0x60003b2+0x1c
   at Microsoft.AspNetCore.Components.Web.WebEventData.Deserialize[MouseEventArgs](String json, JsonTypeInfo`1 jsonTypeInfo) in Microsoft.AspNetCore.Components.WebAssembly.dll:token 0x6000059+0x0
   at Microsoft.AspNetCore.Components.Web.WebEventData.TryDeserializeStandardWebEventArgs(String eventName, String eventArgsJson, WebEventJsonContext jsonSerializerContext, EventArgs& eventArgs) in Microsoft.AspNetCore.Components.WebAssembly.dll:token 0x6000057+0x7fe
   at Microsoft.AspNetCore.Components.Web.WebEventData.ParseEventArgsJson(Renderer renderer, WebEventJsonContext jsonSerializerContext, UInt64 eventHandlerId, String eventName, String eventArgsJson) in Microsoft.AspNetCore.Components.WebAssembly.dll:token 0x6000056+0x0
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Components.Web.WebEventData.ParseEventArgsJson(Renderer renderer, WebEventJsonContext jsonSerializerContext, UInt64 eventHandlerId, String eventName, String eventArgsJson) in Microsoft.AspNetCore.Components.WebAssembly.dll:token 0x6000056+0x30
   at Microsoft.AspNetCore.Components.Web.WebEventData.Parse(Renderer renderer, WebEventJsonContext jsonSerializerContext, WebEventDescriptor eventDescriptor, String eventArgsJson) in Microsoft.AspNetCore.Components.WebAssembly.dll:token 0x6000050+0x0
   at Microsoft.AspNetCore.Components.WebAssembly.Infrastructure.JSInteropMethods.DispatchEvent(WebEventDescriptor eventDescriptor, String eventArgsJson) in Microsoft.AspNetCore.Components.WebAssembly.dll:token 0x60000da+0x0
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in System.Private.CoreLib.dll:token 0x6004e25+0x6a
--- End of stack trace from previous location ---
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson) in Microsoft.JSInterop.dll:token 0x6000056+0x9d
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet(JSRuntime jsRuntime, DotNetInvocationInfo invocationInfo, String argsJson) in Microsoft.JSInterop.dll:token 0x6000054+0x4c
    at Object.endInvokeDotNetFromJS (https://localhost:5001/_framework/blazor.webassembly.js:1:2868)
    at Object.dt [as endInvokeDotNetFromJS] (https://localhost:5001/_framework/blazor.webassembly.js:1:53294)
    at Object.ut [as invokeJSFromDotNet] (https://localhost:5001/_framework/blazor.webassembly.js:1:52968)
    at _mono_wasm_invoke_js_blazor (https://localhost:5001/_framework/dotnet.6.0.0-preview.7.21377.19.js:1:191287)
    at <anonymous>:wasm-function[2545]:0x7e724
    at <anonymous>:wasm-function[2270]:0x66a5e
    at <anonymous>:wasm-function[6847]:0x168e10
    at <anonymous>:wasm-function[6664]:0x160079
    at <anonymous>:wasm-function[3456]:0xaca88
    at <anonymous>:wasm-function[666]:0x1595d
```

### Further technical details

ASP.Net Core .Net 6.0 Preview 7

Visual Studio 2022 (17.0.0 Preview 3.0)

#### Donet --info

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.7.21379.14
 Commit:    22d70b47bc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\

Host (useful for support):
  Version: 6.0.0-preview.7.21377.19
  Commit:  91ba01788d

.NET SDKs installed:
  5.0.200-preview.20614.14 [C:\Program Files\dotnet\sdk]
  5.0.302 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.1.21103.13 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.4.21255.9 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.6.21355.2 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.6.21355.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.6.21352.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.6.21353.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  ```

**Comment by MaxxDelusional** [comment]
Here is how I fixed it.

I decided to run my app with `dotnet watch run`, and in doing so, I noticed the following error in the terminal.

```
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '6.0.0-preview.7.21377.19' was not found.
  - The following frameworks were found:
      6.0.0-preview.6.21352.12 at [C:\Program Files\Microsoft Visual Studio\2022\Preview\dotnet\runtime\shared\Microsoft.NETCore.App]
```
I thought that was weird, because I know that I had installed Preview 7 earlier today. 

Typing `dotnet --version``, I can see that Preview7 is installed.

```
dotnet --version
6.0.100-preview.7.21379.14
```

I double checked to see that I had updated all of my nuget packages in my solution. I right-clicked on my solution node, and chose "Manage Nuget Packages for Solution".

The package manager did not show any available updates. I ensured that I had the "Include prerelease" checkbox checked.

On a whim, I decided to right-click on my server project, and chose "Manage Nuget Packages". Now the package manager showed me that I had 8 updates available!

I proceeded to update each of the packages in my server app (6.0.0-preview.6.213552 to 6.0.0-preview.7.21378.6).

I then repeated the same process for my Client project, but this time, Nuget still showed no updates available.

I decided to jump into my Client csproj, and there I could see that I was still referencing Preview6 packages.

```
<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="6.0.0-preview.7.21378.6" />
```

I went to check nuget.org to see if newer version were available. (https://www.nuget.org/packages/Microsoft.AspNetCore.Components.WebAssembly/6.0.0-preview.7.21378.6). Here I could see that there was a Preview7 version of the package that was uploaded yesterday. I also noticed that the package had 0 downloads, (this could be a caching thing, but it seems like Nuget is unable to see these packages).

I went through each of the PackageReferences in my client app, found the latest version on nuget.org, and then manually modified my Client app to look like this.

```
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="6.0.0-preview.7.21378.6" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="6.0.0-preview.7.21378.6" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Authentication.WebAssembly.Msal" Version="6.0.0-preview.7.21378.6" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="6.0.0-preview.7.21377.19" />
  </ItemGroup>
```

After making this change, my even handlers started to work again!

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us and sharing details on how you've resolved your issue.
This seems to be a NuGet issue. @dotnet/aspnet-build team, do you know where this should go or whether there was some known issue which may have caused this?

**Comment by CopperBeardy** [comment]
ran in to the same issue and manual changing of the version sorted it out

**Comment by danroth27** [comment]
The original reported issue appears to be resolved here: The Microsoft.AspNetCore.Components.WebAssembly.* packages needed to be updated to match the framework version.

The "The framework 'Microsoft.NETCore.App', version '6.0.0-preview.7.21377.19' was not found." message can happen when using the terminal in VS: https://developercommunity.visualstudio.com/t/Running-a-NET-6-Preview-7-ASPNET-Core/1502210. @MaxxDelusional Are you by chance using the VS dev terminal?

**Comment by MaxxDelusional** [comment]
@danroth27 yes, I was using the dev terminal when I got that error.

I don't that error was related to my original issue, I just mentioned it because it lead me down the path towards fixing the button problem.

**Comment by SteveSandersonMS** [comment]
Closing as it seems to be fixed when the preview framework is updated. We recommend doing a `git clean -xdf` on your project when upgrading between preview versions to avoid issues like these.

**Comment by MaxxDelusional** [comment]
@SteveSandersonMS I think this is okay to close now, but just a comment on your `git clean -xdf` suggestion. This was the out-of-box experience for me when using Preview7. I wasn't updating an existing project from Preview6.
