### ISSUE TITLE
Can't run blank, newly created Blazor WASM app with ASP.Net Hosting and Individual Authentication

### ISSUE THREAD

**Issue by Cmohan** [dotnet/aspnetcore#35337]
### Describe the bug
I have created multiple Blazor WASM apps with ASP.NET hosting and Individual Authentication from the base template, but none of them run upon initial creation. I always get the following error:

![image](https://user-images.githubusercontent.com/2027643/129405871-e7ce6421-c701-46b5-a4dc-04f98e31b002.png)

It doesn't happen with Standalone Blazor WASM apps with Individual Authentication and it doesn't happen with Blazor WASM apps with ASP.NET Hosting and NO authentication. Just when both are used.

The Client project is created fine and exists in the solution. I don't know why the Server project can't find it.

### To Reproduce
1. Open Visual Studio 2019 and select Create New Project.
2. Select Blazor WebAssembly App project Template.
3. Enter a name for the project.
4. Check the ASP.Net Hosted option box.
5. Select Individual Authentication for the Authentication type.
6. Create Project.
7. Wait for Solution to load then run Server project.
8. Browser opens and shows a partial Blazor page then the Exception is hit.

### Exceptions (if any)
System.InvalidOperationException: Client 'Blazor-WASM-Hosted-Auth-Demo.Client not found

### Further technical details
- ASP.NET Core version 5.0
- - Visual Studio 2019 16.11.0
- Output of `dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   5.0.400
 Commit:    d61950f9bf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.400\

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  3.1.412 [C:\Program Files\dotnet\sdk]
  5.0.302 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

cc: @guardrex

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Please also share the full exception stack trace.

**Comment by Cmohan** [comment]
Here's the full stack trace of the error

```
   at Microsoft.AspNetCore.ApiAuthorization.IdentityServer.ClientCollection.get_Item(String key)
   at Microsoft.AspNetCore.ApiAuthorization.IdentityServer.DefaultClientRequestParametersProvider.GetClientParameters(HttpContext context, String clientId)
   at Blazor_WASM_Hosted_Auth_Demo.Server.Controllers.OidcConfigurationController.GetClientRequestParameters(String clientId) in C:\Users\catherine.mohan\Code\Projects\Blazor-WASM-Hosted-Auth-Demo\Blazor-WASM-Hosted-Auth-Demo\Server\Controllers\OidcConfigurationController.cs:line 22
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
```

**Comment by pranavkm** [comment]
Our templates mangle the project name to produce a valid identifier. It's likely that the dashes in your file name interfere with this. Could you try picking a different name to see if it resolves it?

**Comment by Cmohan** [comment]
I tried both `BlazorWasmHostedAuthDemo` and `Blazor_Wasm_Hosted_Auth_Demo` as project names and those both worked fine. It definitely doesn't like the dashes then.

**Comment by guardrex** [comment]
I've made a note for this for coverage in the docs on my UE passes for the Blazor security node. Due to high priority work for 6.0, it's likely that it will be addressed early in 2022.

**Comment by Cmohan** [comment]
Sounds good to me. Thanks for the help!

**Comment by guardrex** [comment]
@pranavkm ... I'm placing NOTEs to warn off of dashes in project names (filenames) at solution creation in the hosted WASM security topics. This PU issue is marked "Resolved" **_but isn't closed_**. Will this issue be addressed with a framework update such that dashes will be permitted at some point in the future? If so, I'll open a docs tracking issue to check back here later and see if/when I can remove the NOTEs. If not, I won't open such a docs issue, and the NOTEs will remain a permanent feature of the doc content.
