### ISSUE TITLE
Blazor wasm: Uncaught (in promise) Error: System.InvalidOperationException: There was an error parsing the event arguments. EventId: '13'.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#35348]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-wasm:-Uncaught-in-promise-Error/1501082)._

---
[regression] [worked-in:17 preview2]
I have a blazor webassembly project that works fine in VS 2022 preview 2 but does not work in preview 3. I can build and start the application fine however any interaction causes the following error (with different event ID's)

"Uncaught (in promise) Error: System.InvalidOperationException: There was an error parsing the event arguments. EventId: '13'.
 ---> System.MissingMethodException: Method not found: System.Text.Json.Serialization.Metadata.JsonPropertyInfo System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<!0>(System.Text.Json.JsonSerializerOptions,bool,System.Type,System.Text.Json.Serialization.Metadata.JsonTypeInfo,System.Text.Json.Serialization.JsonConverter`1<!!0>,System.Func`2<object, !!0>,System.Action`2<object, !!0>,System.Text.Json.Serialization.JsonIgnoreCondition,System.Text.Json.Serialization.JsonNumberHandling,string,string)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.InitializePropCache() in System.Text.Json.dll:token 0x60008f4+0x21
   at System.Text.Json.Serialization.Converters.JsonMetadataServicesConverter`1[[Microsoft.AspNetCore.Components.Web.KeyboardEventArgs, Microsoft.AspNetCore.Components.Web, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]]. OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, KeyboardEventArgs& value) in System.Text.Json.dll:token 0x600094d+0x1e
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.Web.KeyboardEventArgs, Microsoft.AspNetCore.Components.Web, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]]. TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, KeyboardEventArgs& value) in System.Text.Json.dll:token 0x600078d+0x197
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.Web.KeyboardEventArgs, Microsoft.AspNetCore.Components.Web, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]]. ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) in System.Text.Json.dll:token 0x6000779+0xbf
   at System.Text.Json.JsonSerializer.ReadCore[KeyboardEventArgs](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) in System.Text.Json.dll:token 0x6000395+0xa
   at System.Text.Json.JsonSerializer.ReadUsingMetadata[KeyboardEventArgs](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount) in System.Text.Json.dll:token 0x6000396+0x2f
   at System.Text.Json.JsonSerializer.ReadUsingMetadata[KeyboardEventArgs](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo) in System.Text.Json.dll:token 0x60003b7+0x4c
   at System.Text.Json.JsonSerializer.Deserialize[KeyboardEventArgs](String json, JsonTypeInfo`1 jsonTypeInfo) in System.Text.Json.dll:token 0x60003b2+0x1c
   at Microsoft.AspNetCore.Components.Web.WebEventData.Deserialize[KeyboardEventArgs](String json, JsonTypeInfo`1 jsonTypeInfo) in Microsoft.AspNetCore.Components.WebAssembly.dll:token 0x6000059+0x0
   at Microsoft.AspNetCore.Components.Web.WebEventData.TryDeserializeStandardWebEventArgs(String eventName, String eventArgsJson, WebEventJsonContext jsonSerializerContext, EventArgs& eventArgs) in Microsoft.AspNetCore.Components.WebAssembly.dll:token 0x6000057+0x7ee
   at Microsoft.AspNetCore.Components.Web.WebEventData.ParseEventArgsJson(Renderer renderer, WebEventJsonContext jsonSerializerContext, UInt64 eventHandlerId, String eventName, String eventArgsJson) in Microsoft.AspNetCore.Components.WebAssembly.dll:token 0x6000056+0x0
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Components.Web.WebEventData.ParseEventArgsJson(Renderer renderer, WebEventJsonContext jsonSerializerContext, UInt64 eventHandlerId, String eventName, String eventArgsJson) in Microsoft.AspNetCore.Components.WebAssembly.dll:token 0x6000056+0x30
   at Microsoft.AspNetCore.Components.Web.WebEventData.Parse(Renderer renderer, WebEventJsonContext jsonSerializerContext, WebEventDescriptor eventDescriptor, String eventArgsJson) in Microsoft.AspNetCore.Components.WebAssembly.dll:token 0x6000050+0x0
   at Microsoft.AspNetCore.Components.WebAssembly.Infrastructure.JSInteropMethods.DispatchEvent(WebEventDescriptor eventDescriptor, String eventArgsJson) in Microsoft.AspNetCore.Components.WebAssembly.dll:token 0x60000da+0x0
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in System.Private.CoreLib.dll:token 0x6004e25+0x6a
--- End of stack trace from previous location ---
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson) in Microsoft.JSInterop.dll:token 0x6000056+0x9d
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet(JSRuntime jsRuntime, DotNetInvocationInfo invocationInfo, String argsJson) in Microsoft.JSInterop.dll:token 0x6000054+0x4c
    at Object.endInvokeDotNetFromJS (https://localhost:5001/_framework/blazor.webassembly.js:1:2868)
    at Object.dt [as endInvokeDotNetFromJS] (https://localhost:5001/_framework/blazor.webassembly.js:1:53294)
    at Object.ut [as invokeJSFromDotNet] (https://localhost:5001/_framework/blazor.webassembly.js:1:52968)
    at _mono_wasm_invoke_js_blazor (https://localhost:5001/_framework/dotnet.6.0.0-preview.7.21377.19.js:1:191287)
    at <anonymous>:wasm-function[2545]:0x7e724
    at <anonymous>:wasm-function[2270]:0x66a5e
    at <anonymous>:wasm-function[6847]:0x168e10
    at <anonymous>:wasm-function[6664]:0x160079
    at <anonymous>:wasm-function[3456]:0xaca88
    at <anonymous>:wasm-function[666]:0x1595d"

---
#### Feedback Bot on 8/12/2021, 02:13 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
#### Dale Woolley solved on 8/12/2021, 08:15 AM, 0 votes: 

<p>I installed .Net preview 7 (6.0.0-preview.7.21378.6) and now everything works again.</p>

**Comment by jvossers** [comment]
I had the exact same issue. I managed to resolve it by upgrading the **Microsoft.AspNetCore.Components.WebAssembly** nuget package reference on my WebAssembly project from version **6.0.0-preview.6.21355.2** to version **6.0.0-preview.7.21378.6**

**Comment by SteveSandersonMS** [comment]
We believe this is not an issue if you're on the latest preview packages, as mentioned by @jvossers. If anyone can reproduce this while being on the latest packages, please let us know!

**Comment by kamalraturi** [comment]
> I had the exact same issue. I managed to resolve it by upgrading the **Microsoft.AspNetCore.Components.WebAssembly** nuget package reference on my WebAssembly project from version **6.0.0-preview.6.21355.2** to version **6.0.0-preview.7.21378.6**

I also faced this issue. I Updated the project as you said. It is working locally in the dev machine now, but not on the IIS Production server. Even the demo counter button not working.

**Comment by pranavkm** [comment]
@kamalraturi could you file a separate issue with a minimal app that reproduces the problem? @jvossers seemed to have resolved this issue by updating their app.
