### ISSUE TITLE
App service down: Microsoft.Data.SqlClient.SNI.TdsParserStateObjectManaged.WriteAsyncCallback(SNIPacket packet, UInt32 sniError)

### ISSUE THREAD

**Issue by deivyd321** [dotnet/aspnetcore#35382]
After deployment app service was completely down but after making restart it started working again. Though this startup issue costs a lot and we don't know what may cause the issue.

Here is _2021_08_16_pl0mdlwk00000L_default_docker.log_ the only place we found any relatable logs.

```
  _____                               
  /  _  \ __________ _________   ____  
 /  /_\  \___   /  |  \_  __ \_/ __ \ 
/    |    \/    /|  |  /|  | \/\  ___/ 
\____|__  /_____ \____/ |__|    \___  >
        \/      \/                  \/ 
A P P   S E R V I C E   O N   L I N U X

Documentation: http://aka.ms/webapp-linux
Dotnet quickstart: https://aka.ms/dotnet-qs
ASP .NETCore Version: 5.0.5
Note: Any data outside '/home' is not persisted
Running oryx create-script -appPath /home/site/wwwroot -output /opt/startup/startup.sh -defaultAppFilePath /defaulthome/hostingstart/hostingstart.dll     -bindPort 8080 -userStartupCommand '' 
Cound not find build manifest file at '/home/site/wwwroot/oryx-manifest.toml'
Could not find operation ID in manifest. Generating an operation id...
Build Operation ID: eca99fad-1e03-4eb5-9af4-4d574cec3a49
Writing output script to '/opt/startup/startup.sh'
Trying to find the startup DLL name...
Found the startup D name: Bonanza.Api.dll
Running the command: dotnet "Bonanza.Api.dll"
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Data.SqlClient.SNI.TdsParserStateObjectManaged.WriteAsyncCallback(SNIPacket packet, UInt32 sniError)
   at Microsoft.Data.SqlClient.SNI.SNIPacket.WriteToStreamAsync(Stream stream, SNIAsyncCallback callback, SNIProviders provider)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
Could not open output /home/logs/dumps/coredump.787653051a83.28.1629112327: 2 No such file or directory
Gathering state for process 28 dotnet
Writing minidump with heap to file /home/logs/dumps/coredump.787653051a83.28.1629112327
/opt/startup/startup.sh: line 12:    28 Aborted                 (core dumped) dotnet "Bonanza.Api.dll"
```

ASP.NET Core 5
App Service Linux
EF Core 5
SqlAzure database

**Comment by davidfowl** [comment]
cc @ajcvickers
