### ISSUE TITLE
Windows test job failure due to BasicTestApp publish

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#35429]
Even though E2e test app is disabled, it still sometimes fails the build, see https://dev.azure.com/dnceng/public/_build/results?buildId=1299611&view=logs&jobId=6c33d704-163a-5170-38fa-caa7bc99f17c&j=6c33d704-163a-5170-38fa-caa7bc99f17c&t=4a2ac175-72f0-54eb-c8b6-eb1e5d86c7d5 cc @SteveSandersonMS 

```
ILLink : error IL1012: IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues [D:\workspace\_work\1\s\src\Components\test\testassets\BasicTestApp\BasicTestApp.csproj]
##[error]ILLink(0,0): error IL1012: (NETCORE_ENGINEERING_TELEMETRY=Build) IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues
  Fatal error in IL Linker
  Unhandled exception. Mono.Linker.InternalErrorException: Step 'OutputStep' failed when processing assembly 'System.Private.Xml, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   ---> Mono.Linker.LinkerFatalErrorException: ILLink: error IL1011: Failed to write 'D:\workspace\_work\1\s\artifacts\obj\BasicTestApp\Release\net6.0\linked\System.Private.Xml.dll
   ---> System.IO.IOException: The process cannot access the file 'D:\workspace\_work\1\s\artifacts\obj\BasicTestApp\Release\net6.0\linked\System.Private.Xml.dll' because it is being used by another process.
     at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
     at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
     at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
     at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
     at Mono.Cecil.ModuleDefinition.GetFileStream(String fileName, FileMode mode, FileAccess access, FileShare share)
     at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
     at Mono.Cecil.AssemblyDefinition.Write(String fileName, WriterParameters parameters)
     at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
     --- End of inner exception stack trace ---
     at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
     at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory)
     at Mono.Linker.Steps.OutputStep.OutputAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.OutputStep.ProcessAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
     --- End of inner exception stack trace ---
     at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
  Compressing Blazor WebAssembly publish artifacts. This may take a while...
  BasicTestApp -> D:\workspace\_work\1\s\artifacts\bin\Microsoft.AspNetCore.Components.Migration.E2ETests\Release\net6.0\trimmed\BasicTestApp\
  Microsoft.AspNetCore.Mvc.FunctionalTests -> D:\workspace\_work\1\s\artifacts\bin\Microsoft.AspNetCore.Mvc.FunctionalTests\Release\net6.0\Microsoft.AspNetCore.Mvc.FunctionalTests.dll
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
D:\workspace\_work\1\s\.dotnet\sdk\6.0.100-rc.1.21415.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ILLink.targets(108,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [D:\workspace\_work\1\s\src\Components\test\testassets\BasicTestApp\BasicTestApp.csproj]
##[error].dotnet\sdk\6.0.100-rc.1.21415.3\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ILLink.targets(108,5): error NETSDK1144: (NETCORE_ENGINEERING_TELEMETRY=Build) Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false.

```

**Comment by SteveSandersonMS** [comment]
This looks like a real defect in the linker, the SDK, or our build system. I don’t think we should suppress this kind of issue just because of which project it happened on.

**Comment by javiercn** [comment]
@lewing is there a way we can capture more information here?

**Comment by lewing** [comment]
cc @agocke @vitek-karas

**Comment by lewing** [comment]
wait I should have read closer, looks build related, cc @radical

**Comment by adityamandaleeka** [comment]
This just happened again on one of my PRs: https://dev.azure.com/dnceng/public/_build/results?buildId=1356324&view=logs&j=3f6d4e0f-1b71-56b5-361e-d95b6e6da15a&t=9605d305-57d3-55b8-ba79-e50442d32137&l=2296
