### ISSUE TITLE
Exceptions when serializing log events events in the background

### ISSUE THREAD

**Issue by JakenVeina** [dotnet/aspnetcore#35443]
### Describe the bug
I'm encountering exceptions when trying to serialize log event state objects to JSON, for the Microsoft.AspNetCore.Hosting.Diagnostics events RequestStarting and ReqeustFinished.

![Exception image](https://cdn.discordapp.com/attachments/536023005164470303/877407874601603092/unknown.png)

![Exception image](https://cdn.discordapp.com/attachments/536023005164470303/877408229955608596/unknown.png)

The issue is that I am using an `ILoggerProvider` that marshals log event data to a background process, and performs serialization there, instead of doing it immediately in the foreground. This results in the background process attempting to access `HttpRequestMessage` and `HttpResponseMessage` objects that have been disposed, since the state objects for these log events simply wrap these Http objects.

The source of these exceptions can be seen [here](https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/Hosting/Hosting/src/Internal/HostingRequestStartingLog.cs#L28) and [here](https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/Hosting/Hosting/src/Internal/HostingRequestFinishedLog.cs#L37).

By my reckoning, the easy fix here is to adjust the state objects to materialize the desired values, rather than retrieve them on-demand, from objects that are not guaranteed to be valid forever. I'd be happy to submit a PR to this effect, if the change is acceptable.

### To Reproduce
[Minimal reproduction scenario](https://github.com/JakenVeina/AspNetCoreRequestLogExceptions)

### Exceptions
```
System.ObjectDisposedException: IFeatureCollection has been disposed.
Object name: 'Collection'.
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.ThrowContextDisposed() in Microsoft.Extensions.Features.dll:token 0x6000021+0xf
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.ContextDisposed() in Microsoft.Extensions.Features.dll:token 0x6000020+0x0
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.Fetch[TFeature](TFeature& cached, Func`2 factory) in Microsoft.Extensions.Features.dll:token 0x600001f+0x0
   at Microsoft.AspNetCore.Http.DefaultHttpRequest.get_Protocol() in Microsoft.AspNetCore.Http.dll:token 0x6000124+0x0
   at Microsoft.AspNetCore.Hosting.HostingRequestStartingLog.ToString() in Microsoft.AspNetCore.Hosting.dll:token 0x600012c+0x29
   at Microsoft.AspNetCore.Hosting.HostingRequestStartingLog.<>c.<.cctor>b__16_0(Object state, Exception exception) in Microsoft.AspNetCore.Hosting.dll:token 0x6000264+0x0
   at AspNetCoreRequestLogExceptions.LogEvent`1.Serialize() in D:\Projects\AspNetCoreRequestLogExceptions\AspNetCoreRequestLogExceptions\LogEvent.cs:line 67
```

```
System.ObjectDisposedException: IFeatureCollection has been disposed.
Object name: 'Collection'.
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.ThrowContextDisposed() in Microsoft.Extensions.Features.dll:token 0x6000021+0xf
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.ContextDisposed() in Microsoft.Extensions.Features.dll:token 0x6000020+0x0
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.Fetch[TFeature](TFeature& cached, Func`2 factory) in Microsoft.Extensions.Features.dll:token 0x600001f+0x0
   at Microsoft.AspNetCore.Http.DefaultHttpRequest.get_Protocol() in Microsoft.AspNetCore.Http.dll:token 0x6000124+0x0
   at Microsoft.AspNetCore.Hosting.HostingRequestStartingLog.get_Item(Int32 index) in Microsoft.AspNetCore.Hosting.dll:token 0x600012a+0x2f
   at Microsoft.AspNetCore.Hosting.HostingRequestStartingLog.GetEnumerator()+MoveNext() in Microsoft.AspNetCore.Hosting.dll:token 0x600012d+0x27
   at AspNetCoreRequestLogExceptions.LogEvent`1.Serialize() in D:\Projects\AspNetCoreRequestLogExceptions\AspNetCoreRequestLogExceptions\LogEvent.cs:line 80
```

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Hosting.HostingRequestFinishedLog.ToString() in Microsoft.AspNetCore.Hosting.dll:token 0x6000125+0x33
   at Microsoft.AspNetCore.Hosting.HostingRequestFinishedLog.<>c.<.cctor>b__14_0(Object state, Exception exception) in Microsoft.AspNetCore.Hosting.dll:token 0x600025b+0x0
   at AspNetCoreRequestLogExceptions.LogEvent`1.Serialize() in D:\Projects\AspNetCoreRequestLogExceptions\AspNetCoreRequestLogExceptions\LogEvent.cs:line 67
```

```
System.ObjectDisposedException: IFeatureCollection has been disposed.
Object name: 'Collection'.
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.ThrowContextDisposed() in Microsoft.Extensions.Features.dll:token 0x6000021+0xf
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.ContextDisposed() in Microsoft.Extensions.Features.dll:token 0x6000020+0x0
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.Fetch[TFeature](TFeature& cached, Func`2 factory) in Microsoft.Extensions.Features.dll:token 0x600001f+0x0
   at Microsoft.AspNetCore.Http.DefaultHttpResponse.get_StatusCode() in Microsoft.AspNetCore.Http.dll:token 0x600013b+0x0
   at Microsoft.AspNetCore.Hosting.HostingRequestFinishedLog.get_Item(Int32 index) in Microsoft.AspNetCore.Hosting.dll:token 0x6000123+0x7c
   at Microsoft.AspNetCore.Hosting.HostingRequestFinishedLog.GetEnumerator()+MoveNext() in Microsoft.AspNetCore.Hosting.dll:token 0x6000126+0x27
   at AspNetCoreRequestLogExceptions.LogEvent`1.Serialize() in D:\Projects\AspNetCoreRequestLogExceptions\AspNetCoreRequestLogExceptions\LogEvent.cs:line 80
```

### Further technical details
- ASP.NET Core 6.0.0-preview.7.20365.19
- `dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.7.21379.14
 Commit:    22d70b47bc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\

Host (useful for support):
  Version: 6.0.0-preview.7.21377.19
  Commit:  91ba01788d

.NET SDKs installed:
  1.0.0-rc4-004771 [C:\Program Files\dotnet\sdk]
  1.0.0 [C:\Program Files\dotnet\sdk]
  1.0.2 [C:\Program Files\dotnet\sdk]
  1.0.3 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.525 [C:\Program Files\dotnet\sdk]
  2.1.600-preview-009426 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.105 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.409 [C:\Program Files\dotnet\sdk]
  3.1.412 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.7.20366.6 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]
  5.0.200-preview.20614.14 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]
  5.0.206 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.7.20365.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.7.20364.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.7.20366.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
- Visual Studio 2019 Preview (16.11.1 Preview 1.0)

**Comment by davidfowl** [comment]
It's not valid to store logged objects outside of the synchronous call to log. You need to serialize the data and push that to the background.

**Comment by JakenVeina** [comment]
I don't suppose there's any documentation for that design intent, in the Logging framework?

**Comment by davidfowl** [comment]
We can certainly improve the documentation, but that's how the system works.

cc @IEvangelist

**Comment by JakenVeina** [comment]
You can ALWAYS improve the documentation ;)

Yeah, I think that'd be a fair thing to clarify somewhere. Nothing about the framework REQUIRES that loggers do processing in the foreground, so I think it's a pretty reasonable trap to fall into, if your writing a logger with a goal of adding minimal overhead to business code.

Thanks for all your time.

**Comment by davidfowl** [comment]
It's not about processing in the foreground, it's about serialization. You have no idea what the lifetime of the objects are that are being logged. This should be explicitly documented (in the doc comments too).

cc @shirhatti @maryamariyan

**Comment by JakenVeina** [comment]
Agreed, I'm using the term "foreground" a little loosely.

So, maybe something in `<remarks>` on the `ILogger.Log<TState>()` method, along the lines of...

"No requirements are placed upon the lifetimes of `TState` values, except that they must remain valid for the duration of the `.Log<TState>()` call. Whatever processing the logger needs to do upon `TState` values, including calling the `formatter` delegate, should be done immediately in the method. Capturing `TState` values for later processing, as these values are not guaranteed to remain valid once the method returns."

**Comment by davidfowl** [comment]
@JakenVeina would you like to send a pull request? I'm going to move this to the right place.
