### ISSUE TITLE
ConnectionState.getNextInvocationId() on a null object reference

### ISSUE THREAD

**Issue by Norbert-akra** [dotnet/aspnetcore#35444]
###Exception
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.microsoft.signalr.HubConnection$ConnectionState.getNextInvocationId()' on a null object reference
       at com.microsoft.signalr.HubConnection.invoke(HubConnection.java:631)
       at com.ddm.diabetes.gro.services.hub.Hub.invoke(Hub.java:273)
       at com.ddm.diabetes.gro.ui.chat.viewmodels.ChatVMImpl.onStopTyping(ChatVMImpl.java:279)
       at com.ddm.diabetes.gro.ui.chat.fragments.ChatFragment$setupViewObservers$1.invoke(ChatFragment.java:168)
       at com.ddm.diabetes.gro.ui.chat.fragments.ChatFragment$setupViewObservers$1.invoke(ChatFragment.java:62)
       at com.ddm.diabetes.gro.utils.EndTypingWatcher$finishCheckerRunnable$1.run(EndTypingWatcher.java:16)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

### Describe the bug
I noticed the crash in crashlytics on the production build. The client version is 3.1.18.

**Comment by BrennanConroy** [comment]
Can you try the 5.0.x version of the client?
