### ISSUE TITLE
View not found running on .Net6 rc1

### ISSUE THREAD

**Issue by En3Tho** [dotnet/aspnetcore#35452]
### Describe the bug
After upgrading to .Net 6 rc1 a "View not found exception started to appear"

3.1.406 (Microsoft.AspNetCore.App 3.1.18) -> ok
5.0.400 (Microsoft.AspNetCore.App 5.0.9) -> ok
6.0.100-preview.7.21379.14 (Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6) -> ok
6.0.100-rc.1.21417.9 (Microsoft.NETCore.App 6.0.0-rc.1.21415.6) -> exception

It's an F# project with razor views. Views are each set to "Content", do not copy.

I heard there were changes to Razor compiler.
Do I need to fix something in my project files or maybe in Sdk.Razor.CurrentVersion.props?

Exception text:

Caught exception in ExceptionHandlerMiddleware System.AggregateException: Oneor more errors occurred. (One or more errors occurred. (The view '~/Views/Login.cshtml' was not found. The following locations were searched:~/Views/Login.cshtml))
 ---> System.AggregateException: One or more errors occurred. (The view '~/Views/Login.cshtml' was not found. The following locations were searched:~/Views/Login.cshtml)
 ---> System.InvalidOperationException: The view '~/Views/Login.cshtml' was not found. The following locations were searched: ~/Views/Login.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|22_0(ResourceInvoker invoker, ActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilter
s()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceEx
ecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next,Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---.

**Comment by En3Tho** [comment]
https://github.com/dotnet/aspnetcore/pull/35137 maybe this is somehow connected?

**Comment by En3Tho** [comment]
One more thing: 
Views folder is in fsproj root.
Before compiling with Net6 I had compiled my app with .Net 5
Running from bin/net5.0/... produces the same result now (View not found)
To make app run normal again it requires full recompilation on .Net5

**Comment by pranavkm** [comment]
@En3Tho I just tried this using a build of the RC1 SDK and don't see an issue building 5.0 or 6.0 apps. Here's where you could grab one of these if you'd like to try it out  - https://github.com/dotnet/installer#installers-and-binaries.

If you continue seeing the issue after you update, I'd be happy to investigate further. To do so, please share a minimal app, preferably as a GitHub repo, that reproduces the problem.

**Comment by En3Tho** [comment]
Hi. Issue is not with building the app. It build and runs (SignaR Hubs start, Controllers work etc). The only thing that fails is views. I will try to make a repo project. C# has supported Razor views static compilation for a long time, F# did not. I guess now that you've disabled static compilation in .Net6 F# simply fails to build views dynamically because there is no such option anymore. Am I somewhat right in this?

**Comment by En3Tho** [comment]
Thanks. I think it might be worthwhile discussing internally, even a little. Net 6 is lts and I personally expect more people trying to use new runtime compared to non lts Net 5. This might be a problem for them. But I don't know if C# is affected too. If it is, then maybe some kind of survey or analysis would help (like how many of devs are using this kind of dynamic compilation).
In our case there is a problem with upgrading packages because there are some dependencies we can't really change in near future and that's quite sad. I don't think we are only ones in this situation.
Anyway, I can only recommend checking if C# projects are affected or not.
Thanks.

**Comment by En3Tho** [comment]
@pranavkm And no, I did not use 3.1 compilation package (if I understand correctly, you mean "3.1 build" here). Basically we have Razor.RuntimeComilation nuget with version 3.1 or something like that. When we migrated to Net 5 we did not upgrade it. We switched targets, did a rebuild and voila - it works. Now with Net 6 we do the same thing - switch target, rebuild and boom - every service is ok exception this one because there is some breaking change which (seems to me) makes every old Razor.RuntimeCompilation package (older than 6.rc1) invalid.

**Comment by davidfowl** [comment]
Typically, you need to update all of the packages to the 6.0 version as part of the upgrade. Often times you'll see customers on issues in partially upgraded states complaining that something got broken, this is one of those things. It's expected that you need to upgrade every dependency to .NET 6. Sometimes you can get lucky and things might work, but we don't test or expect customers to live in a torn state.

**Comment by En3Tho** [comment]
Well, I guess that is logical. But sadly not always easy. Thanks @pranavkm @davidfowl . At least now I can prepare myself for some pain.

**Comment by lucianparvu** [comment]
Hello,

I have the same issue in RC2 I don't understand how to solve it. I don't have Runtime Compilation and i don't have global.json.

An unhandled exception occurred while processing the request.
InvalidOperationException: The view '_Host' was not found. The following locations were searched:
/Views/Host/_Host.cshtml
/Views/Shared/_Host.cshtml
/Pages/Shared/_Host.cshtml

Thank's
