### ISSUE TITLE
[HTTP/3] Kestrel closes connection too soon

### ISSUE THREAD

**Issue by ManickaP** [dotnet/aspnetcore#35470]
In case of an error (e.g.: https://github.com/dotnet/runtime/issues/57647), Kestrel sends GOAWAY and immediately closes the connection. At the client side, the request with the highest allowed stream id by GOAWAY fails due to the connection being closed too soon.

Kestrel logs (GO AWAY for 596):  
```
2021-08-18 21:08:26.759 +02:00 [DBG] Connection id "0HMB2FE527AVT": GOAWAY stream ID 596.
2021-08-18 21:08:26.759 +02:00 [DBG] Trace id "0HMB2FE527AVT": HTTP/3 stream error "0". An abort is being sent to the stream.
Microsoft.AspNetCore.Connections.ConnectionAbortedException: The HTTP/3 connection faulted.
 ---> System.InvalidOperationException: Both reader and writer has to be completed to be able to reset the pipe.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_ResetIncompleteReaderWriter()
   at System.IO.Pipelines.Pipe.Reset()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http3.Http3OutputProducer.StreamReset()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http3.Http3Stream.Initialize(Http3StreamContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http3.Http3Connection.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
   --- End of inner exception stack trace ---
2021-08-18 21:08:26.760 +02:00 [DBG] Stream id "0HMB2FE527AVT:00000002" aborted by application with error code 0 because: "The HTTP/3 connection faulted.".
2021-08-18 21:08:26.762 +02:00 [DBG] Connection id "0HMB2FE527AVT" aborted by application with error code 0 because: "The HTTP/3 connection faulted.".
2021-08-18 21:08:26.762 +02:00 [DBG] Connection id "0HMB2FE527AVT" is closed. The last processed stream ID was 592.
2021-08-18 21:08:26.762 +02:00 [DBG] Connection id "0HMB2FE527AVT" stopped.
```

Client logs (stream id 592):
```
19:08:26.7617044[HandlerMessage] poolId: 9490272, workerId: 39785641, requestId: 0, memberName: OnServerGoAway, message: HTTP/3 server sent GOAWAY with stream ID 596
...
19:08:26.7652025[Info] thisOrContextObject: State#30247713, memberName: HandleEvent, message: [strm][0x7FCADC012530][ID+592] Stream received event SHUTDOWN_COMPLETE
19:08:26.7652067[Info] thisOrContextObject: State#30247713, memberName: HandleEventConnectionClose, message: [strm][0x7FCADC012530][ID+592] Stream handling connection [conn][0x5570842B2E00] close with code 0
19:08:26.7657564[Info] thisOrContextObject: State#18303590, memberName: NativeCallbackHandler, message: [conn][0x5570842B2E00] Connection received event SHUTDOWN_COMPLETE
19:08:26.7662780[HandlerMessage] poolId: 9490272, workerId: 39785641, requestId: 0, memberName: Abort, message: abortException==System.Net.Quic.QuicConnectionAbortedException: Connection aborted by peer (0).
   at System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventConnectionClose(State state) in /home/manicka/repositories/runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicStream.cs:line 1398
   at System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventShutdownComplete(State state, StreamEvent& evt) in /home/manicka/repositories/runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicStream.cs:line 1024
   at System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEvent(State state, StreamEvent& evt) in /home/manicka/repositories/runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicStream.cs:line 860
   at System.Net.Quic.Implementations.MsQuic.MsQuicStream.NativeCallbackHandler(IntPtr stream, IntPtr context, StreamEvent& streamEvent) in /home/manicka/repositories/runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicStream.cs:line 824
--- End of stack trace from previous location ---
   at System.Net.Quic.Implementations.MsQuic.Internal.ResettableCompletionSource`1.GetResult(Int16 token) in /home/manicka/repositories/runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/Internal/ResettableCompletionSource.cs:line 57
   at System.Net.Http.Http3Connection.<>c__DisplayClass43_0.<<ProcessServerControlStreamAsync>g__ReadFrameEnvelopeAsync|0>d.MoveNext() in /home/manicka/repositories/runtime/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3Connection.cs:line 618
--- End of stack trace from previous location ---
   at System.Net.Http.Http3Connection.ProcessServerControlStreamAsync(QuicStream stream, ArrayBuffer buffer) in /home/manicka/repositories/runtime/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3Connection.cs:line 569
   at System.Net.Http.Http3Connection.ProcessServerStreamAsync(QuicStream stream) in /home/manicka/repositories/runtime/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3Connection.cs:line 471
   at System.Net.Http.Http3Connection.ProcessServerStreamAsync(QuicStream stream) in /home/manicka/repositories/runtime/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3Connection.cs:line 526
19:08:26.7662790[HandlerMessage] poolId: 9490272, workerId: 39785641, requestId: 0, memberName: Abort, message: abortException==System.Net.Quic.QuicConnectionAbortedException: Connection aborted by peer (0).
   at System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventConnectionClose(State state) in /home/manicka/repositories/runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicStream.cs:line 1398
   at System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEventShutdownComplete(State state, StreamEvent& evt) in /home/manicka/repositories/runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicStream.cs:line 1024
   at System.Net.Quic.Implementations.MsQuic.MsQuicStream.HandleEvent(State state, StreamEvent& evt) in /home/manicka/repositories/runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicStream.cs:line 860
   at System.Net.Quic.Implementations.MsQuic.MsQuicStream.NativeCallbackHandler(IntPtr stream, IntPtr context, StreamEvent& streamEvent) in /home/manicka/repositories/runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicStream.cs:line 824
--- End of stack trace from previous location ---
   at System.Net.Quic.Implementations.MsQuic.Internal.ResettableCompletionSource`1.GetResult(Int16 token) in /home/manicka/repositories/runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/Internal/ResettableCompletionSource.cs:line 57
   at System.Net.Http.Http3RequestStream.ReadFrameEnvelopeAsync(CancellationToken cancellationToken) in /home/manicka/repositories/runtime/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs:line 736
   at System.Net.Http.Http3RequestStream.ReadResponseAsync(CancellationToken cancellationToken) in /home/manicka/repositories/runtime/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs:line 310
   at System.Net.Http.Http3RequestStream.SendAsync(CancellationToken cancellationToken) in /home/manicka/repositories/runtime/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs:line 196
19:08:26.7664795[Info] thisOrContextObject: State#30247713, memberName: Dispose, message: [strm][0x7FCADC012530][ID+592] Stream disposing True
19:08:26.7664955[Info] thisOrContextObject: State#30247713, memberName: Cleanup, message: [strm][0x7FCADC012530][ID+592] releasing handles.
19:08:26.7665195[Info] thisOrContextObject: State#30247713, memberName: Dispose, message: [strm][0x7FCADC012530][ID+592] Stream disposed
19:08:26.7669510[Info] thisOrContextObject: State#18303590, memberName: Dispose, message: [conn][0x5570842B2E00] Connection disposing True
```

As a result, previous error affects the subsequent request on the client side.

**Comment by JamesNK** [comment]
I don't believe this is a bug.

Here is the section on connection shutdown: https://quicwg.org/base-drafts/draft-ietf-quic-http.html#section-5.2

> The information in the GOAWAY frame enables a client and server to agree on which requests or pushes were accepted prior to the shutdown of the HTTP/3 connection. Upon sending a GOAWAY frame, the endpoint SHOULD explicitly cancel (see Section 4.1.2 and Section 7.2.3) any requests or pushes that have identifiers greater than or equal to that indicated, in order to clean up transport state for the affected streams. The endpoint SHOULD continue to do so as more requests or pushes arrive.

The GOAWAY value indicates the requests that the server has accepted and started processing.

In the case of an immediate shutdown of the connection or server, that doesn't mean the requests with IDs less than the GOAWAY value will have all succeeded. They could be halfway through processing at the time the connection is killed, in which case they will be aborted and will generate an error to the caller.

If Kestrel is gracefully shutting down then it will send a GOAWAY then wait 5 seconds for requests that have been accepted to complete. New requests during this time are aborted with H3_REQUEST_REJECTED. At the end of 5 seconds any connections that are still active, and there requests, are aborted.

**Comment by ManickaP** [comment]
Then how would you suggest we should approach this problem? 
- We send one request that fails
- We start sending another on the same connection since we haven't received GoAway yet
- We receive GoAway, but it says that the inflight request is safe to finish because its stream id is smaller
- The connection is abruptly closed

We cannot know how far the processing went on the server, so we cannot safely retry on a new connection. User will get also exception `HttpRequestException` with `QuicConnectionAbortedException` so they cannot know either.

Specs also says:
> The endpoint SHOULD continue to do so as more requests or pushes arrive.

We're not sending/processing requests with >= id than in GoAway, we just want to finish one that has smaller id.

Do you know how HTTP/2 server behaves in such situations?

**Comment by JamesNK** [comment]
> We're not sending/processing requests with >= id than in GoAway

I think a client should stop sending any new requests on a connection once it gets a GOAWAY. A server can send a GOAWAY with ID = max value as a general indication to the client that it is shutting down. I haven't looked super closely at the client focused areas of the spec, so please double check.

> we just want to finish one that has smaller id.

I think the only thing you can do for in-progress requests with a stream ID that is smaller than the GOAWAY ID, and the connection aborts, is throw `HttpRequestException` using the aborted exception.

https://quicwg.org/base-drafts/draft-ietf-quic-http.html#section-5.2-4

> * Upon receipt of a GOAWAY frame, if the client has already sent requests with a Stream ID greater than or equal to the identifier contained in the GOAWAY frame, those requests will not be processed. Clients can safely retry unprocessed requests on a different HTTP connection. A client that is unable to retry requests loses all requests that are in flight when the server closes the connection.
>
> * Requests on Stream IDs less than the Stream ID in a GOAWAY frame from the server might have been processed; their status cannot be known until a response is received, the stream is reset individually, another GOAWAY is received with a lower Stream ID than that of the request in question, or the connection terminates.

Requests with IDs equal or greater than the GOAWAY can be safely retried on a new connection.

cc @geoffkizer 

> Do you know how HTTP/2 server behaves in such situations?

I don't know off the top of my head. I haven't touched HTTP/2 GOAWAY.

**Comment by ManickaP** [comment]
> A client should stop sending any new requests on a connection once it gets a GOAWAY. 

We do stop sending any new requests, but we received GoAway after we started the one request that gets aborted, so we had no chance to prevent starting it. Note that there's a difference from H/2 since GoAway is sent on a control stream. It's processed independently from request processing, so there's an inherent race here.

**Comment by JamesNK** [comment]
That's fine. Kestrel will abort any inflight requests that arrive after it has sent GOAWAY with `H3_REQUEST_REJECTED`.

One situation you should be aware of is the GOAWAY and `H3_REJECTED_REQUEST` aborts arriving out of order.

For example:
* The server aborts the connection, sends GOAWAY ID = 0, and then rejects an incoming stream with ID = 0 with `H3_REJECTED_REQUEST`.
* The client receives notifications out of order. It gets `H3_REQUEST_REJECTED` abort for stream ID = 0 first, then it receives GOAWAY ID = 0.

If HttpClient adds support for retrying requests after GOAWAY then that will be a situation you'll need to handle.

**Comment by ManickaP** [comment]
We do support retrying after GoAway/`H3_REQUEST_REJECTED`. Problem is with request that's not `H3_REQUEST_REJECTED` nor rejected via GoAway stream ID.

**Comment by CarnaViire** [comment]
What worries me here is that the error codes sent to Stream and Connection are both 0 (can be seen in Kestrel logs). 0 is not an H/3 error code -- did something go wrong? Should it be H3_INTERNAL_ERROR instead?

**Comment by JamesNK** [comment]
That's a bug. See https://github.com/dotnet/runtime/issues/57647#issuecomment-901373338

**Comment by adityamandaleeka** [comment]
@ManickaP Closing this since we don't believe this is an issue at the moment (per above discussion). The second issue that @JamesNK linked to has been addressed now. 

Please re-open if needed.
