### ISSUE TITLE
Subclassing Startup from StartupBase throws NotSupportedException

### ISSUE THREAD

**Issue by fredrikhr** [dotnet/aspnetcore#35502]
### Describe the bug

When subclassing the `Startup`-class in a standard ASP.NET Core application from the abstract `StartupBase` type, the call to `UseStartup` (in `Program.CreateHostBuilder`) fails and throws a `NotSupportedException`.

There is no mention of `StartupBase` being deprecated or unusable. Documentation does not state anything about the usage not being supported.

#### `Program.cs`

```c#
partial class Program
{
    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureWebHostDefaults(webBuilder =>
            {
                webBuilder.UseStartup<Startup>();
                // Alternatively
                // webBuilder.UseStartup(ctx => new Startup(ctx));
            });
}
```

ref.: https://gist.github.com/fredrikhr/407e30bc766f8046d7035bb3152c7203#file-program-cs

#### `Startup.cs`

```c#
public class Startup : StartupBase
{
    private readonly WebHostBuilderContext context;

    public Startup(WebHostBuilderContext context)
    {
        this.context = context;
    }

    public override void ConfigureServices(IServiceCollection services)
    {
        base.ConfigureServices(services);
    }

    public override void Configure(IApplicationBuilder app)
    {
    }
}
```

ref.: https://gist.github.com/fredrikhr/407e30bc766f8046d7035bb3152c7203#file-startup-cs

#### Clone

```
https://gist.github.com/407e30bc766f8046d7035bb3152c7203.git
```

### Exceptions (if any)

```
System.NotSupportedException
  HResult=0x80131515
  Message=Microsoft.AspNetCore.Hosting.IStartup isn't supported
  Source=Microsoft.AspNetCore.Hosting
  StackTrace:
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at FredrikHr.GistIssues.AspnetCoreIStartup.Program.Main(String[] args)
```

#### `csproj`

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
</Project>
```

#### `dotnet --info`

```
.NET SDK (reflecting any global.json):
 Version:   5.0.400
 Commit:    d61950f9bf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.400\

Host (useful for support):
  Version: 5.0.9
  Commit:  208e377a53

.NET SDKs installed:
  5.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

#### Docker image

`mcr.microsoft.com/dotnet/sdk:5.0.400`

**Comment by davidfowl** [comment]
> There is no mention of StartupBase being deprecated or unusable. Documentation does not state anything about the usage not being supported.

We need to update the documentation. `IStartup` (and StartupBase by extension) is dead outside of the WebHost.

cc @Tratcher

**Comment by fredrikhr** [comment]
@davidfowl so in this particular example, instead do: (for strongly-typed vs. convention-based startup)

```c#
public class Startup // no base class
{
    public void ConfigureServices(WebHostBuilderContext context,
        IServiceCollection services)
    {
        services.AddSingleton(this);
        // extra stuff here...
    }

    public void Configure(WebHostBuilderContext context,
        IApplicationBuilder app)
    {
        var env = context.HostingEnvironment;
        // extra stuff here...
    }
}

partial class Program
{
    public static IHostBuilder CreateHostBuilder(string[]? args) =>
        Host.CreateDefaultBuilder(args ?? Array.Empty<string>())
            .ConfigureWebHostDefaults(wb =>
            {
                Startup st = new();
                wb.ConfigureServices(st.ConfigureServices);
                wb.Configure(st.Configure);
            });
}

**Comment by davidfowl** [comment]
@fredrikhr Sure, what do you gain?

**Comment by fredrikhr** [comment]
@davidfowl true enough, you don't gain anything by that... Except that you get a strongly-typed `ConfigureServices` and `Configure`, but that does not really do much as the usual `Startup` class doesn't get much injected anyways.

**Comment by davidfowl** [comment]
I'm not saying it's bad I just wanted to understand why you felt the need to do it.

**Comment by adityamandaleeka** [comment]
> > There is no mention of StartupBase being deprecated or unusable. Documentation does not state anything about the usage not being supported.
> 
> We need to update the documentation. `IStartup` (and StartupBase by extension) is dead outside of the WebHost.
> 
> cc @Tratcher

@Tratcher looks like you unassigned yourself. Do you think the docs should be updated with that? ^

**Comment by Tratcher** [comment]
Yes.
