### ISSUE TITLE
.Net 6 p7 Wasm publised throws Blazor detected a change in the application's culture that is not supported with the current project configuration

### ISSUE THREAD

**Issue by Guru-Soft** [dotnet/aspnetcore#35550]
### Describe the bug
.NET 6 p7 Blazor Wasm project throws below error after published (release mode) when culture is applied
"Blazor detected a change in the application's culture that is not supported with the current project configuration"

### To Reproduce
1.  .NET 6 p7 Blazor Wasm project
2. In the client project BlazorWebAssemblyLoadAllGlobalizationData true
3. Add nuget Microsoft.AspNetCore.Localization v2.2.0
4. Add nuget Microsoft.Extensions.Localization v5.0.9
5. Set CultureInfo.DefaultThreadCurrentCulture and CultureInfo.DefaultThreadCurrentUICulture to any thing (nl-NL) other than en-US to observe the error 

client project file
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
	 <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
  </PropertyGroup>
....

### Exceptions (if any)
System.AggregateException: AggregateException_ctor_DefaultMessage (Blazor detected a change in the application's culture that is not supported with the current project configuration. To change culture dynamically during startup, set <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData> in the application's project file.)
 ---> System.InvalidOperationException: Blazor detected a change in the application's culture that is not supported with the current project configuration. To change culture dynamically during startup, set <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData> in the application's project file.
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyCultureProvider.ThrowIfCultureChangeIsUnsupported()
   at Microsoft.AspNetCore.Components.WebAssembly.Hosting.WebAssemblyHost.RunAsyncCore(CancellationToken , WebAssemblyCultureProvider )
   at Bbaas.Biddo.BlazorApp.Client.Program.Main(String[] args)
   Exception_EndOfInnerExceptionStack
callEntryPoint @ blazor.webassembly.js:1

### Further technical details
- .NET 6 p7
- Include the output of `dotnet --info`
- dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.7.21379.14
 Commit:    22d70b47bc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\

Host (useful for support):
  Version: 6.0.0-preview.7.21377.19
  Commit:  91ba01788d

.NET SDKs installed:
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
Visual Studio 2022, Windows Dev
Microsoft Edge
Version 92.0.902.73 (Official build) (64-bit)

**Comment by Stamo-Gochev** [comment]
@pranavkm Will the fix be ported to earlier releases like RC1? This is blocking until then. Is there a workaround?

**Comment by Keerthi-Mettu** [comment]
Hello @pranavkm, is this a duplicate of another issue? Seems you marked it as a dupe to itself. 

Also installing RC1 or RC2 hasn't resolved the problem. Can you please elaborate on the workaround or pls let us know what we are missing!!
![image](https://user-images.githubusercontent.com/79932039/132377429-771b59a1-a0ad-4ae0-96f2-c5d2923abe70.png)

**Comment by Stamo-Gochev** [comment]
@pranavkm The issue is still reproducible with the latest .NET RC1. Can you provide a workaround?

**Comment by ThaRaven403** [comment]
I'd also like to know @pranavkm if there is a workaround for this. 
I'm currently having the same issue with RC1, but only when deployed on Azure (it doesn't give me any error locally).

I can try installing a nightly build if there's one that solves the issue, but if there's a workaround I'd rather use this.

@Stamo-Gochev have you found a way around this on your end?

**Comment by Keerthi-Mettu** [comment]
I did have the same problem until I was publishing the server project and hosting it in the server IIS (mine is an asp.net Core hosted Blazor web assembly). When I overwrite this published build from the server project with the client project, it actually worked for me. Usually, if we are publishing to a target folder, to overwrite the server build, add this server build path as a new target location on the client. 
This is my non-standard workaround temporarily to fix this problem.

**Comment by ThaRaven403** [comment]
@Keerthi-Mettu Not sure to understand what you mean by "overwrite this published build from the server project with the client project". On my end the deployment is managed through a DevOps pipeline (Azure App Service deploy task) so it's basically sending the zip file over and letting Azure handle the rest. Also had to make the build as self-contained since RC1 is currently not available for Azure AppService

**Comment by pantoast** [comment]
Having the same problem on .NET 6 RC1 here. Blazor WebAssembly project hosted on an Azure VM in IIS.
