### ISSUE TITLE
[.Net 6.0 Preview 7] Microsoft.NET.Sdk.Razor.StaticWebAssets.targets DirectoryNotFoundException

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#35561]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Net-60-Preview-7-MicrosoftNETSdkR/1508969)._

---
When building a c# project on the .NET 6.0 Preview 7 SDK, if my .csproj file has "AppendTargetFrameworkToOutputPath" set to false, I get a DirectoryNotFound exception. Note the "net6.0" in the path that cannot be found.

```
42>C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(425,5): error : System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Repos\PangaeaAppliance\src\Service\<myproject>\obj\Debug\net6.0\StaticWebAssets.build.json'.
42>C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(425,5): error :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
42>C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(425,5): error :    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
42>C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(425,5): error :    at System.IO.FileStream.. ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
42>C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(425,5): error :    at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
42>C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(425,5): error :    at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
42>C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(425,5): error :    at Microsoft.AspNetCore.Razor.Tasks.GenerateStaticWebAssetsManifest.PersistManifest(StaticWebAssetsManifest manifest)
42>C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(425,5): error :    at Microsoft.AspNetCore.Razor.Tasks.GenerateStaticWebAssetsManifest.Execute()
42>C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.StaticWebAssets.targets(425,5): error : Could not find a part of the path 'C:\Repos\PangaeaAppliance\src\Service\<myproject>\obj\Debug\net6.0\StaticWebAssets.build.json'.
```

---
#### Feedback Bot on 8/20/2021, 02:18 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 8/20/2021, 03:49 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

---
### Original Solutions
(no solutions)

**Comment by XtremeOwnageDotCom** [comment]
Can also confirm this issue, which popped up with preview 7.

**Comment by FahaoTang** [comment]
I can also confirm this issue when using CLI to create the project and build.
