### ISSUE TITLE
SignalR client callback not firing in Blazor WebAssembly client ONLY if client was published and ONLY for some callback parameter types

### ISSUE THREAD

**Issue by jvossers** [dotnet/aspnetcore#35598]
In a nutshell, I am not getting any error, but my SignalR callback in my Blazor WebAssembly client is not firing when it should be. The thing is that it works fine when I run everything in Visual Studio - it only breaks if I publish the client and run that. Additionally, it also depends on the type of the parameter for the callback.

I have created a repo containing code to reproduce the issue along with further info at https://github.com/jvossers/Vossers.BlazorWasmSignalrIssue

I am using VS 2022 Preview 3.1 and targeting .NET 6 preview.

`dotnet --info` output:

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.7.21379.14
 Commit:    22d70b47bc

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\

Host (useful for support):
  Version: 6.0.0-preview.7.21377.19
  Commit:  91ba01788d

.NET SDKs installed:
  5.0.103 [C:\Program Files\dotnet\sdk]
  5.0.300 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by BrennanConroy** [comment]
This isn't a signalr specific issue, if you change your components code to:
```csharp
var immutableList = ImmutableList<string>.Empty.Add("One").Add("Two").Add("Three");
var s = System.Text.Json.JsonSerializer.Serialize(immutableList);
var list2 = System.Text.Json.JsonSerializer.Deserialize<ImmutableList<string>>(s);
Console.WriteLine($"{immutableList}, {s}, {list2}");
```

You'll see the published project fail with
```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: SerializationNotSupportedType, System.Collections.Immutable.ImmutableList`1[System.String]
System.NotSupportedException: SerializationNotSupportedType, System.Collections.Immutable.ImmutableList`1[System.String]
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_SerializationNotSupported(Type ) in System.Text.Json.dll:token 0x60000e2+0xb
   at System.Text.Json.Serialization.IEnumerableConverterFactoryHelpers.GetImmutableEnumerableCreateRangeMethod(Type , Type ) in System.Text.Json.dll:token 0x600059c+0x72
   at System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreateImmutableEnumerableCreateRangeDelegate(Type , Type , Type ) in System.Text.Json.dll:token 0x6000708+0x0
   at System.Text.Json.Serialization.Metadata.ReflectionEmitMemberAccessor.CreateImmutableEnumerableCreateRangeDelegate[ImmutableList`1,String]() in System.Text.Json.dll:token 0x6000707+0x0
   at System.Text.Json.Serialization.Converters.ImmutableEnumerableOfTConverter`2[[System.Collections.Immutable.ImmutableList`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Collections.Immutable, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Initialize(JsonSerializerOptions , JsonTypeInfo ) in System.Text.Json.dll:token 0x60007a9+0x0
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo..ctor(Type , JsonConverter , Type , JsonSerializerOptions ) in System.Text.Json.dll:token 0x60006c6+0x27a
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo..ctor(Type , JsonSerializerOptions ) in System.Text.Json.dll:token 0x60006c5+0x0
   at System.Text.Json.JsonSerializerOptions.<RootBuiltInConvertersAndTypeInfoCreator>g__CreateJsonTypeInfo|107_0(Type , JsonSerializerOptions ) in System.Text.Json.dll:token 0x600039d+0x0
   at System.Text.Json.JsonSerializerOptions.GetClassFromContextOrCreate(Type ) in System.Text.Json.dll:token 0x6000393+0x29
   at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type ) in System.Text.Json.dll:token 0x6000392+0x17
   at System.Text.Json.JsonSerializerOptions.GetOrAddClassForRootType(Type ) in System.Text.Json.dll:token 0x6000394+0x1b
   at System.Text.Json.JsonSerializer.GetTypeInfo(Type , JsonSerializerOptions ) in System.Text.Json.dll:token 0x6000337+0x10
   at System.Text.Json.JsonSerializer.Write[ImmutableList`1](ImmutableList`1& , Type , JsonSerializerOptions ) in System.Text.Json.dll:token 0x6000359+0x0
   at System.Text.Json.JsonSerializer.Serialize[ImmutableList`1](ImmutableList`1 , JsonSerializerOptions ) in System.Text.Json.dll:token 0x6000358+0x0
   at Vossers.BlazorWasmSignalrIssue.WebAssemblyClient.Pages.Index.OnInitializedAsync() in Vossers.BlazorWasmSignalrIssue.WebAssemblyClient.dll:token 0x600001f+0x5a
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync() in Microsoft.AspNetCore.Components.dll:token 0x600002f+0xbe
```

The reason it only fails when published is because trimming happens on publish, you can see that the published project works if you add `<PublishTrimmed>false</PublishTrimmed>` to your client csproj.

@pranavkm Are there docs for this sort of thing?

**Comment by jvossers** [comment]
@BrennanConroy thanks, that is very insightful.

After a bit more digging I found a bit more detail as to why it is failing exactly, and I agree that trimming is part of the problem.

[Here](https://github.com/dotnet/runtime/blob/331cfe33e187a6234aa2c2447f91793f154bd322/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Collection/IEnumerableConverterFactoryHelpers.cs#L29) you can see how some of the code in System.Text.Json is using reflection to find the ImmutableList.CreateRange<T>(IEnumerable<T>) method so it can invoke it, but because the trimming did not find any uses of this method in my code it ended up trimming it. As a result, the code below never enters the `if` statement in the `foreach` loop and ultimately it leads to [an exception being thrown on line 39](https://github.com/dotnet/runtime/blob/331cfe33e187a6234aa2c2447f91793f154bd322/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Collection/IEnumerableConverterFactoryHelpers.cs#L39)

    [RequiresUnreferencedCode(ImmutableConvertersUnreferencedCodeMessage)]
    public static MethodInfo GetImmutableEnumerableCreateRangeMethod(this Type type, Type elementType)
    {
        Type? constructingType = GetImmutableEnumerableConstructingType(type);
        if (constructingType != null)
        {
            MethodInfo[] constructingTypeMethods = constructingType.GetMethods();
            foreach (MethodInfo method in constructingTypeMethods)
            {
                if (method.Name == ReflectionExtensions.CreateRangeMethodName &&
                    method.GetParameters().Length == 1 &&
                    method.IsGenericMethod &&
                    method.GetGenericArguments().Length == 1)
                {
                    return method.MakeGenericMethod(elementType);
                }
            }
        }
  
        ThrowHelper.ThrowNotSupportedException_SerializationNotSupported(type);
        return null!;
    }

This can be verified by adding the following line anywhere in the sample Blazor application I linked to in the original issue, and it will work after publishing still, because making use of that method in my code prevents it from getting trimmed. 

`ImmutableList.CreateRange(new List<string> { "Please dont trim me." });`

Now obviously this is not a solution, but perhaps this insight might lead to a proper solution. Perhaps something in System.Text.Json.Serialization could make use of [DynamicDependencyAttribute](https://github.com/dotnet/runtime/blob/331cfe33e187a6234aa2c2447f91793f154bd322/src/libraries/System.Private.CoreLib/src/System/Diagnostics/CodeAnalysis/DynamicDependencyAttribute.cs#L23) to express its dependency on ImmutableList.CreateRange? Could that work? Or maybe some other way to prevent that method from being trimmed?

**Comment by pranavkm** [comment]
AFAIK, the way they made it trimmer safe is by using the source generator which will root the reflection based code that was previously being trimmed. https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-source-generator/ has more details about this.

**Comment by jvossers** [comment]
I don't think this issue should be closed until someone I (or someone else) is able to turn my sample project into a working solution which meets the following criteria:

- WebAssembly project published
- trimming enabled
- use of `ImmutableList<T>` in SignalR callback parameter
- SignalR callback fires when it should

What I understand from the comments provided so far is that it should be possible by making use of the System.Text.Json source generator. I have tried to implement this, but so far I have been unsucessful. Below is a description of what is currently blocking me.

I tried adding a class that derives from `JsonSerializerContext` to my sample project after adding a nuget package reference to the latest version of System.Text.Json (`6.0.0-preview.7.21377.19`) in an attempt to verify that the problem goes away when I follow the approach described [here](https://devblogs.microsoft.com/dotnet/try-the-new-system-text-json-source-generator/), as suggested by @pranavkm. However, as soon as I add a class file with the following code to my WebAssembly project several things in VS start to crash and it is preventing me from building the project. I have pushed this [change](https://github.com/jvossers/Vossers.BlazorWasmSignalrIssue/commit/f6ca57c143369ebb0a130fae62c5095172a15c9b#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26) to a branch [here](https://github.com/jvossers/Vossers.BlazorWasmSignalrIssue/tree/source-generator-issue).

    using System.Text.Json.Serialization;
    using Vossers.BlazorWasmSignalrIssue.Shared;
    
    namespace Vossers.BlazorWasmSignalrIssue.WebAssemblyClient
    {
    
        [JsonSerializable(typeof(ImmutableViewModel))]
        internal partial class MyJsonContext : JsonSerializerContext
        {
    
        }
    }

![image](https://user-images.githubusercontent.com/12950029/131216562-01d45b7e-a71e-421f-a6e0-0065292a3ae2.png)

![image](https://user-images.githubusercontent.com/12950029/131217070-a8364519-7b36-4a3c-ae30-5b67516f8d36.png)


stacktraces:

![image](https://user-images.githubusercontent.com/12950029/131216673-5c75357d-973e-4886-9dc8-95a892518613.png)


    StreamJsonRpc.RemoteInvocationException: An element with the same key but a different value already exists. Key: '(DocumentId, #b920999b-70a0-9fac-c5ca-35bea3834f34 - MyJsonContext.String.g.cs)'
       at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Threading.Tasks.ValueTask`1.get_Result()
       at Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__17`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
    RPC server exception:
    System.ArgumentException: An element with the same key but a different value already exists. Key: '(DocumentId, #b920999b-70a0-9fac-c5ca-35bea3834f34 - MyJsonContext.String.g.cs)'
          at System.Collections.Immutable.ImmutableSortedDictionary`2.FillFromEmpty(IEnumerable`1 items, Boolean overwriteOnCollision)
          at System.Collections.Immutable.ImmutableSortedDictionary`2.AddRange(IEnumerable`1 items, Boolean overwriteOnCollision, Boolean avoidToSortedMap)
          at System.Collections.Immutable.ImmutableSortedDictionary.ToImmutableSortedDictionary[TSource,TKey,TValue](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IComparer`1 keyComparer)
          at Microsoft.CodeAnalysis.TextDocumentStates`1..ctor(IEnumerable`1 states)
          at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<FinalizeCompilationAsync>d__30.MoveNext()
       --- End of stack trace from previous location where exception was thrown ---
          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
          at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
       --- End of stack trace from previous location where exception was thrown ---
          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetOrBuildCompilationInfoAsync>d__22.MoveNext()
       --- End of stack trace from previous location where exception was thrown ---
          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetCompilationSlowAsync>d__20.MoveNext()
       --- End of stack trace from previous location where exception was thrown ---
          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          at Microsoft.CodeAnalysis.Document.<GetSemanticModelAsync>d__23.MoveNext()
       --- End of stack trace from previous location where exception was thrown ---
          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          at Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions.<GetRequiredSemanticModelAsync>d__7.MoveNext()
       --- End of stack trace from previous location where exception was thrown ---
          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          at Microsoft.CodeAnalysis.Classification.AbstractSyntaxClassificationService.<AddSemanticClassificationsAsync>d__5.MoveNext()
       --- End of stack trace from previous location where exception was thrown ---
          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          at Microsoft.CodeAnalysis.Classification.AbstractClassificationService.<AddSemanticClassificationsInCurrentProcessAsync>d__3.MoveNext()
       --- End of stack trace from previous location where exception was thrown ---
          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          at Microsoft.CodeAnalysis.Remote.RemoteSemanticClassificationService.<>c__DisplayClass2_0.<<GetSemanticClassificationsAsync>b__0>d.MoveNext()
       --- End of stack trace from previous location where exception was thrown ---
          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          at System.Threading.Tasks.ValueTask`1.get_Result()
          at Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__12`1.MoveNext()

![image](https://user-images.githubusercontent.com/12950029/131216680-9cf0b94d-89fc-4564-a4d7-ac4347d5eafa.png)


    System.ArgumentException : An element with the same key but a different value already exists. Key: '(DocumentId, #b920999b-70a0-9fac-c5ca-35bea3834f34 - MyJsonContext.String.g.cs)'
       at System.Collections.Immutable.ImmutableSortedDictionary`2.FillFromEmpty(IEnumerable`1 items,Boolean overwriteOnCollision)
       at System.Collections.Immutable.ImmutableSortedDictionary`2.AddRange(IEnumerable`1 items,Boolean overwriteOnCollision,Boolean avoidToSortedMap)
       at System.Collections.Immutable.ImmutableSortedDictionary.ToImmutableSortedDictionary[TSource,TKey,TValue](IEnumerable`1 source,Func`2 keySelector,Func`2 elementSelector,IComparer`1 keyComparer)
       at Microsoft.CodeAnalysis.TextDocumentStates`1..ctor(IEnumerable`1 states)
       at async Microsoft.CodeAnalysis.SolutionState.CompilationTracker.FinalizeCompilationAsync(<Unknown Parameters>)
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at async Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetOrBuildCompilationInfoAsync(<Unknown Parameters>)
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at async Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetCompilationSlowAsync(<Unknown Parameters>)
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at async Microsoft.CodeAnalysis.Document.GetSemanticModelAsync(<Unknown Parameters>)
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at async Microsoft.CodeAnalysis.SemanticDocument.CreateAsync(<Unknown Parameters>)
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at async Microsoft.CodeAnalysis.IntroduceVariable.AbstractIntroduceVariableService`6.IntroduceVariableAsync[TService,TExpressionSyntax,TTypeSyntax,TTypeDeclarationSyntax,TQueryExpressionSyntax,TNameSyntax](<Unknown Parameters>)
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at async Microsoft.CodeAnalysis.IntroduceVariable.IntroduceVariableCodeRefactoringProvider.ComputeRefactoringsAsync(<Unknown Parameters>)
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)

![image](https://user-images.githubusercontent.com/12950029/131216682-8c2f2fa2-689a-4e6d-a7f6-fecef56edafa.png)


    System.ArgumentException : An element with the same key but a different value already exists. Key: '(DocumentId, #b920999b-70a0-9fac-c5ca-35bea3834f34 - MyJsonContext.String.g.cs)'
       at System.Collections.Immutable.ImmutableSortedDictionary`2.FillFromEmpty(IEnumerable`1 items,Boolean overwriteOnCollision)
       at System.Collections.Immutable.ImmutableSortedDictionary`2.AddRange(IEnumerable`1 items,Boolean overwriteOnCollision,Boolean avoidToSortedMap)
       at System.Collections.Immutable.ImmutableSortedDictionary.ToImmutableSortedDictionary[TSource,TKey,TValue](IEnumerable`1 source,Func`2 keySelector,Func`2 elementSelector,IComparer`1 keyComparer)
       at Microsoft.CodeAnalysis.TextDocumentStates`1..ctor(IEnumerable`1 states)
       at async Microsoft.CodeAnalysis.SolutionState.CompilationTracker.FinalizeCompilationAsync(<Unknown Parameters>)
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at async Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetOrBuildCompilationInfoAsync(<Unknown Parameters>)
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at async Microsoft.CodeAnalysis.SolutionState.CompilationTracker.GetCompilationSlowAsync(<Unknown Parameters>)
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at async Microsoft.CodeAnalysis.Document.GetSemanticModelAsync(<Unknown Parameters>)
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at async Microsoft.CodeAnalysis.Shared.Extensions.DocumentExtensions.GetRequiredSemanticModelAsync(<Unknown Parameters>)
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at async Microsoft.CodeAnalysis.ConvertToInterpolatedString.AbstractConvertConcatenationToInterpolatedStringRefactoringProvider`1.ComputeRefactoringsAsync[TExpressionSyntax](<Unknown Parameters>)
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at async Microsoft.CodeAnalysis.CodeRefactorings.CodeRefactoringService.GetRefactoringFromProviderAsync(<Unknown Parameters>)
