### ISSUE TITLE
In most cases, the site can be started up during production. Occasionally, an error of 500.30 will be reported when the site is started up

### ISSUE THREAD

**Issue by citystory** [dotnet/aspnetcore#35647]
Our application pool is recycled once a day. In most cases, the site can be started up during production. Occasionally, an error of 500.30 will be reported when the site is started up.  It's happened several times in the last month.  

Web Host terminated unexpectedly
System.TypeInitializationException: The type initializer for 'Microsoft.AspNetCore.Cryptography.Cng.OSVersionUtil' threw an exception.
 ---> System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Microsoft.AspNetCore.Cryptography.SafeHandles.SafeLibraryHandle.UnsafeNativeMethods.GetProcAddress(SafeLibraryHandle hModule, String lpProcName)
   at Microsoft.AspNetCore.Cryptography.Cng.OSVersionUtil.GetOSVersion()
   at Microsoft.AspNetCore.Cryptography.Cng.OSVersionUtil..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Cryptography.Cng.OSVersionUtil.IsWindows()
   at Microsoft.Extensions.DependencyInjection.DataProtectionServiceCollectionExtensions.AddDataProtectionServices(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.DataProtectionServiceCollectionExtensions.AddDataProtection(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcViewFeaturesMvcCoreBuilderExtensions.AddViewServices(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcViewFeaturesMvcCoreBuilderExtensions.AddViews(IMvcCoreBuilder builder)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddControllersWithViewsCore(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddControllersWithViews(IServiceCollection services)
   at PcWeb.Startup.ConfigureServices(IServiceCollection services) in Startup.cs:line 51
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at PcWeb.Program.Main(String[] args) in Program.cs:line 45

**Comment by davidfowl** [comment]
cc @GrabYourPitchforks

**Comment by GrabYourPitchforks** [comment]
@citystory What OS and .NET version are you running?

@jkoritzinsky Any thoughts on this? Looks like it's coming from the p/invoke layer. The interop method signature is linked below. I've never seen the interop component produce this error before.

https://github.com/dotnet/aspnetcore/blob/8dd8359c536d9a203fae329fe6e147b2035b52d1/src/Servers/HttpSys/src/NativeInterop/SafeLibraryHandle.cs#L83-L87

@blowdart @HaoK I wonder if going forward we can use the new `NativeLibrary` and `OperatingSystem` APIs in the runtime to avoid having our own _GetProcAddress_ bindings. Don't know if it would help this case because I don't know what the underlying problem is, but it's always good to reuse components where possible.

**Comment by davidfowl** [comment]
>  Don't know if it would help this case because I don't know what the underlying problem is, but it's always good to reuse components where possible.

Yes please. I was going to suggest this but it does look like some form of corruption. Whatever we do here, should be backported.

@citystory What version of .NET are you running.

**Comment by citystory** [comment]
> @citystory What OS and .NET version are you running?
> **Windows Server 2016 Datacenter，net core 3.1.13 - Windows Server Hosting**
> @jkoritzinsky Any thoughts on this? Looks like it's coming from the p/invoke layer. The interop method signature is linked below. I've never seen the interop component produce this error before.
> 
> https://github.com/dotnet/aspnetcore/blob/8dd8359c536d9a203fae329fe6e147b2035b52d1/src/Servers/HttpSys/src/NativeInterop/SafeLibraryHandle.cs#L83-L87
> 
> @blowdart @HaoK I wonder if going forward we can use the new `NativeLibrary` and `OperatingSystem` APIs in the runtime to avoid having our own _GetProcAddress_ bindings. Don't know if it would help this case because I don't know what the underlying problem is, but it's always good to reuse components where possible.

Sometimes also reported the following error

Web Host terminated unexpectedly
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Interop.crypt32.PFXImportCertStore(CRYPTOAPI_BLOB& pPFX, SafePasswordHandle password, PfxCertStoreFlags dwFlags)
   at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(Byte[] rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags)
   at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password)
   at AuthServer.Startup.ConfigureServices(IServiceCollection services) in Startup.cs:line 113
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at AuthServer.Program.Main(String[] args) in Program.cs:line 45

**Comment by citystory** [comment]
The following is also an occasional boot error.  OS:Windows Server 2016 Datacenter，.NET version：net core 3.1.18 - Windows Server Hosting

**Comment by jkoritzinsky** [comment]
I have no idea how this would fail non-deterministically at the P/Invoke layer in this manner. Failures like this are usually due to bad IL, and the interop layer emits the same IL every time.

Maybe this is related to https://github.com/mono/linker/pull/2212/files?

**Comment by GrabYourPitchforks** [comment]
@jkoritzinsky This is 3.1, so not sure how much the Mono linker is involved. Could it be a race condition in the interop or JIT? (Though given the original stack trace, this is called within a cctor, so there shouldn't be a race for this particular method.)

I can transfer to dotnet/runtime if needed for further investigation. Alternatively, could we give OP a way to collect logs or dumps that might help track down the problem? Keep in mind these dumps would contain sensitive data like cryptographic key material.

**Comment by jkoritzinsky** [comment]
I did not realize that this was 3.1.

I guess it could be a race condition, but I'm not sure. I have one idea for log collection that wouldn't capture sensitive data.

If the OP can collect a trace of the ILStubGenerated events (described in [this doc](https://docs.microsoft.com/en-us/dotnet/framework/performance/interop-etw-events)) from the process with ETW or EventTrace, then in combination with the failing stack trace, we should be able to figure out which IL stub the JIT threw an exception on.
