### ISSUE TITLE
Test failure: `StatusCode204StopsLongPollingTriggersOnClosed`

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#35684]
## Failing Test(s)

- `com.microsoft.signalr.LongPollingTransportTest.StatusCode204StopsLongPollingTriggersOnClosed()`

## Error Message

```text
expected: <true> but was: <false>
```

## Stacktrace

<details>

```text
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:35)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:137)
	at com.microsoft.signalr.LongPollingTransportTest.StatusCode204StopsLongPollingTriggersOnClosed(LongPollingTransportTest.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:515)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:171)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:105)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:110)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:110)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:71)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.junit.platform.console.tasks.ConsoleTestExecutor.executeTests(ConsoleTestExecutor.java:65)
	at org.junit.platform.console.tasks.ConsoleTestExecutor.lambda$execute
```
</details>

## Logs

More logs available at https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-heads-main-ca9f0edc7b0b4c52aa/signalr.client.java.Tests--/1/console.37f0f844.log?sv=2019-07-07 but it's unclear what's relevant. @BrennanConroy❔

<details>

```text
Failures (1):
  JUnit Jupiter:LongPollingTransportTest:StatusCode204StopsLongPollingTriggersOnClosed()
    MethodSource [className = 'com.microsoft.signalr.LongPollingTransportTest', methodName = 'StatusCode204StopsLongPollingTriggersOnClosed', methodParameterTypes = '']
    => org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
```
</details>

## Build

[Pipelines - Run 20210823.15 (azure.com)](https://dev.azure.com/dnceng/public/_build/results?buildId=1312055&view=results)

**Comment by BrennanConroy** [comment]
I think we need to up the timeout from 1 second, we moved a bunch of tests to 30 second timeouts at one point, but missed a few spots, this is one of them
https://github.com/dotnet/aspnetcore/blob/8b30d862de6c9146f466061d51aa3f1414ee2337/src/SignalR/clients/java/signalr/test/src/main/java/com/microsoft/signalr/LongPollingTransportTest.java#L74

**Comment by BrennanConroy** [comment]
https://github.com/dotnet/aspnetcore/pull/35687

**Comment by dougbu** [comment]
To confirm: #35690 will quarantine the test about the same time you fix this issue in #35687 i.e. this issue will be `test-fixed` almost immediately❔

**Comment by BrennanConroy** [comment]
There is no flaky process for non c# tests really, so it's either skipped or fixed.

**Comment by Tratcher** [comment]
This failed again in release/6.0, should the fix be backported?
https://dev.azure.com/dnceng/public/_build/results?buildId=1515635&view=ms.vss-test-web.build-test-results-tab&runId=43127808&resultId=118716&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab
```
Failures (1):
  JUnit Jupiter:LongPollingTransportTest:StatusCode204StopsLongPollingTriggersOnClosed()
    MethodSource [className = 'com.microsoft.signalr.LongPollingTransportTest', methodName = 'StatusCode204StopsLongPollingTriggersOnClosed', methodParameterTypes = '']
    => org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
```

**Comment by BrennanConroy** [comment]
> should the fix be backported?

Sure, very easy and low risk.

**Comment by BrennanConroy** [comment]
Issue was reopened to track fixing 6.0 which was done in https://github.com/dotnet/aspnetcore/pull/39290, closing again.
