### ISSUE TITLE
Test Failure: `ConnectionClosedTokenFiresOnServerAbort`

### ISSUE THREAD

**Issue by dougbu** [dotnet/aspnetcore#35686]
## Failing Test(s)

- `Microsoft.AspNetCore.Server.Kestrel.Libuv.FunctionalTests.RequestTests.ConnectionClosedTokenFiresOnServerAbort(listenOptionsName: "PassThrough")`

## Error Message

```text
System.TimeoutException : The operation has timed out.
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 143
   at Microsoft.AspNetCore.Server.Kestrel.Libuv.FunctionalTests.RequestTests.ConnectionClosedTokenFiresOnServerAbort(String listenOptionsName) in /_/src/Servers/Kestrel/test/FunctionalTests/RequestTests.cs:line 627
   at Microsoft.AspNetCore.Server.Kestrel.Libuv.FunctionalTests.RequestTests.ConnectionClosedTokenFiresOnServerAbort(String listenOptionsName) in /_/src/Servers/Kestrel/test/FunctionalTests/RequestTests.cs:line 639
```
</details>

## Logs

<details>

```text
  Standard Output Messages:
 | [0.002s] TestLifetime Information: Starting test ConnectionClosedTokenFiresOnServerAbort-PassThrough at 2021-08-24T18:06:10
 | [0.003s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting starting
 | [0.005s] Microsoft.Hosting.Lifetime Information: Now listening on: http://127.0.0.1:59550
 | [0.006s] Microsoft.AspNetCore.Hosting.Diagnostics Debug: Loaded hosting startup assembly Libuv.FunctionalTests
 | [0.006s] Microsoft.Hosting.Lifetime Information: Application started. Press Ctrl+C to shut down.
 | [0.006s] Microsoft.Hosting.Lifetime Information: Hosting environment: Production
 | [0.006s] Microsoft.Hosting.Lifetime Information: Content root path: /private/tmp/helix/working/AE250975/w/AA00095B/e/
 | [0.006s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting started
 | [0.006s] Microsoft.AspNetCore.Server.Kestrel Debug: TestServer is listening on port 59550
 | [0.007s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMB757CJKH2M" accepted.
 | [0.007s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HMB757CJKH2M" received FIN.
 | [0.007s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMB757CJKH2M" started.
 | [0.007s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMB757CJKH2M" disconnecting.
 | [0.007s] Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv Debug: Connection id "0HMB757CJKH2M" sending FIN because: "The client closed the connection."
 | [0.007s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMB757CJKH2M" stopped.
 | [30.010s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting stopping
 | [30.011s] Microsoft.Hosting.Lifetime Information: Application is shutting down...
 | [30.012s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting stopped
 | [30.013s] Microsoft.AspNetCore.Server.Kestrel.Libuv.FunctionalTests.RequestTests Error: Test threw an exception.
 | System.TimeoutException: The operation has timed out.
 |    at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 143
 |    at Microsoft.AspNetCore.Server.Kestrel.Libuv.FunctionalTests.RequestTests.ConnectionClosedTokenFiresOnServerAbort(String listenOptionsName) in /_/src/Servers/Kestrel/test/FunctionalTests/RequestTests.cs:line 627
 |    at Microsoft.AspNetCore.Server.Kestrel.Libuv.FunctionalTests.RequestTests.ConnectionClosedTokenFiresOnServerAbort(String listenOptionsName) in /_/src/Servers/Kestrel/test/FunctionalTests/RequestTests.cs:line 639
 |    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 273
 | --- End of stack trace from previous location ---
 |    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 54
 |    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 96
 | [30.016s] TestLifetime Information: Finished test ConnectionClosedTokenFiresOnServerAbort-PassThrough in 30.0134132s
```
</details>

/fyi [Console log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-heads-main-72ee1352ed8844f4bf/Libuv.FunctionalTests--net6.0/1/console.c8828bd6.log?sv=2019-07-07) may still be present.

## Build

[Pipelines - Run 20210824.22 (azure.com)](https://dev.azure.com/dnceng/public/_build/results?buildId=1314749&view=results)

**Comment by dougbu** [comment]
May be related to #23043 and general macOS agent slowness

**Comment by Tratcher** [comment]
This appears to be libuv specific and libuv has now been removed. Ready for unquarantine.
