### ISSUE TITLE
The error message for when calling UseStartup isn't correct

### ISSUE THREAD

**Issue by davidfowl** [dotnet/aspnetcore#35830]
The error message when calling the following code is supposed to say that startup isn't supported, but instead, it says that changing the application name isn't supported.  

```C#
var builder = WebApplication.CreateBuilder(args);

builder.WebHost.UseStartup<Startup>();
```

```
Unhandled exception. System.NotSupportedException: The application name changed. Changing the host configuration is not supported.
   at Microsoft.AspNetCore.Builder.ConfigureWebHostBuilder.UseSetting(String key, String value)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.UseStartup(IWebHostBuilder hostBuilder, Type startupType)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.UseStartup[TStartup](IWebHostBuilder hostBuilder)
   at Program.<Main>$(String[] args) in C:\Users\david\source\repos\WebApplication530\WebApplication530\Program.cs:line 
```

This is because the extension method sets the application name before delegating to the underlying call. I think we should delegate to the ISupportsStartup interface without setting the application name.

**Comment by davidfowl** [comment]
It turns out fixing this required one new API:

```diff
public interface ISupportsStartup
{
+    public void Configure(Action<IApplicationBuilder> configure);
}
````
