### ISSUE TITLE
Java SignalR: App is crashed if AccessTokenProvider Single emits an Error

### ISSUE THREAD

**Issue by A8K4** [dotnet/aspnetcore#35968]
I faced the same problem that already described here (https://github.com/dotnet/aspnetcore/issues/23820). This thread is closed, but I don't see any solutions. it refers to the version com.microsoft.signalr:signalr:5.0.9. 

I cannot catch the exception thrown in the AccessTokenProvider.

Here is my code: 

```
    hubConnection = HubConnectionBuilder
        .create(serverUrl)
        .withAccessTokenProvider(Single.defer(() -> Single.just(tokenService.fetchToken())))
        .build();
      hubConnection.on("Error", () -> {
        Logger.info("hubConnection.on Error.");
      })

    hubConnection
        .start()
        .doOnComplete(() -> {
          ...
        })
       .doOnError(error -> {
            Logger.error("error", error);
           handleError(error);
            retry();
      })
        .blockingAwait();
```

So if an exception occurs in **tokenService.fetchToken()** I can't handle it anywhere. 

If the exception not handled the app is crashed:

W/System.err: io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method

**Comment by BrennanConroy** [comment]
What version of the client are you using? And can you provide the full stack trace of the error?

**Comment by A8K4** [comment]
I'm using java client version 5.0.9 (com.microsoft.signalr:signalr:5.0.9). 

Here the full stack: 

````
io.reactivex.exceptions.OnErrorNotImplementedException:` The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | com.siemens.notification.token.TokenServiceException: Error while loading new token
2021-08-31 09:16:35.165 10836-11407/com.notification W/System.err:     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
2021-08-31 09:16:35.165 10836-11407/com.siemens.ebrcloud.execution W/System.err:     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
2021-08-31 09:16:35.165 10836-11407/com.notification W/System.err:     at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:46)
2021-08-31 09:16:35.165 10836-11407/com.notification W/System.err:     at io.reactivex.internal.disposables.EmptyDisposable.error(EmptyDisposable.java:78)
2021-08-31 09:16:35.166 10836-11407/com.notification W/System.err:     at io.reactivex.internal.operators.single.SingleError.subscribeActual(SingleError.java:42)
2021-08-31 09:16:35.166 10836-11407/com.notification W/System.err:     at io.reactivex.Single.subscribe(Single.java:3438)
2021-08-31 09:16:35.166 10836-11407/com.notification W/System.err:     at io.reactivex.internal.operators.single.SingleDefer.subscribeActual(SingleDefer.java:43)
2021-08-31 09:16:35.166 10836-11407/com.notification W/System.err:     at io.reactivex.Single.subscribe(Single.java:3438)
2021-08-31 09:16:35.166 10836-11407/com.notification W/System.err:     at io.reactivex.Single.subscribe(Single.java:3424)
2021-08-31 09:16:35.166 10836-11407/com.notification W/System.err:     at io.reactivex.Single.subscribe(Single.java:3395)
2021-08-31 09:16:35.166 10836-11407/com.notification W/System.err:     at com.microsoft.signalr.HubConnection.start(HubConnection.java:335)
2021-08-31 09:16:35.166 10836-11407/com.notification W/System.err:     at com.notification.LnsConnection.start(LnsConnection.java:34)
2021-08-31 09:16:35.166 10836-11407/com.notification W/System.err:     at com.notification.ForegroundNotificationService.connect(ForegroundNotificationService.java:64)
2021-08-31 09:16:35.167 10836-11407/com.notification W/System.err:     at com.notification.LocalNotificationCordovaPlugin.lambda$execute$0(LocalNotificationCordovaPlugin.java:58)
2021-08-31 09:16:35.167 10836-11407/com.notification W/System.err:     at com.notification.-$$Lambda$LocalNotificationCordovaPlugin$cTYOsgWEfoN7y7xg2BwGL1rWfLg.run(Unknown Source:4)
2021-08-31 09:16:35.167 10836-11407/com.notification W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2021-08-31 09:16:35.167 10836-11407/com.notification W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2021-08-31 09:16:35.167 10836-11407/com.notification W/System.err:     at java.lang.Thread.run(Thread.java:764)
2021-08-31 09:16:35.168 10836-11407/com.notification W/System.err: Caused by: com.notification.token.TokenServiceException: Error while loading new token
2021-08-31 09:16:35.168 10836-11407/com.notification W/System.err:     at com.notification.token.impl.JavaNativeHttpRequestTokenHandler.fetchNewToken(JavaNativeHttpRequestTokenHandler.java:97)
2021-08-31 09:16:35.168 10836-11407/com.notification W/System.err:     at com.notification.token.TokenService.validateAndUpdateToken(TokenService.java:18)
2021-08-31 09:16:35.168 10836-11407/com.notification W/System.err:     at com.notification.LnsConnection.lambda$createHubConnection$5(LnsConnection.java:81)
2021-08-31 09:16:35.168 10836-11407/com.notification W/System.err:     at com.notification.-$$Lambda$LnsConnection$SIhjbios4Pcvcs2imvkrJA_JeSs.call(Unknown Source:2)
2021-08-31 09:16:35.169 10836-11407/com.notification W/System.err:     at io.reactivex.internal.operators.single.SingleDefer.subscribeActual(SingleDefer.java:36)
2021-08-31 09:16:35.169 10836-11407/com.notification W/System.err: 	... 11 more
```

**Comment by A8K4** [comment]
Hallo @BrennanConroy do you have any updates for me? Is this bug in the library or in my implementation/usage of it?

**Comment by BrennanConroy** [comment]
I reviewed the code and don't see how this can be an issue anymore in 5.0 or 6.0. We subscribe to complete and error for all access token provider usages and have tests to verify we behave properly when it throws.

I did go back in time to the 3.1 package and see that the line number in your exception stack trace lines up with the access token provider subscribe that didn't observe the error correctly https://github.com/dotnet/aspnetcore/blob/v3.1.18/src/SignalR/clients/java/signalr/src/main/java/com/microsoft/signalr/HubConnection.java#L335

Please double check that you are using the correct package because I don't think it's an issue anymore.

**Comment by A8K4** [comment]
Hello Brennant, 

I checked the version and the same exception still occures. 

This line ` at com.microsoft.signalr.HubConnection.start(HubConnection.java:335)` in stack trace matches the following code in version 5.0.9:

https://github.com/dotnet/aspnetcore/blob/c663adee8e64ba5d379fa0edfb8201984a7df7d0/src/SignalR/clients/java/signalr/core/src/main/java/com/microsoft/signalr/HubConnection.java#L335
