### ISSUE TITLE
Implement HTTP/3 100 Continue

### ISSUE THREAD

**Issue by Tratcher** [dotnet/aspnetcore#35974]
6.0 candidate, this is a significant missing feature with no server side workaround.

https://github.com/dotnet/runtime/pull/58110#issuecomment-909338565
https://github.com/dotnet/aspnetcore/blob/05303c7571a0654b82797c78ccb8e4b9cc81020f/src/Servers/Kestrel/Core/src/Internal/Http3/Http3OutputProducer.cs#L255-L258
```
2021-08-31 17:19:56.766 +02:00 [ERR] Connection id "0HMBCIB56DQAE", Request id "0HMBCIB56DQAE:00000018": An unhandled exception was thrown by the application.
System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http3.Http3OutputProducer.Write100ContinueAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProduceContinueAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.TryProduceContinueAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.StartTimingReadAsync(ValueTask`1 readAwaitable, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http3.Http3MessageBody.ReadAsync(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.IO.Pipelines.PipeReader.CopyToAsyncCore[TStream](TStream destination, Func`4 writeAsync, CancellationToken cancellationToken)
   at HttpStress.StressServer.<>c.<<MapRoutes>b__6_6>d.MoveNext() in /home/manicka/repositories/runtime/src/libraries/System.Net.Http/tests/StressTests/HttpStress/StressServer.cs:line 249
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

```

Compare to HTTP/2:
https://github.com/dotnet/aspnetcore/blob/05303c7571a0654b82797c78ccb8e4b9cc81020f/src/Servers/Kestrel/Core/src/Internal/Http2/Http2OutputProducer.cs#L169-L182

**Comment by adityamandaleeka** [comment]
This was done for 6.0 RC2: https://github.com/dotnet/aspnetcore/pull/36395
