### ISSUE TITLE
[dotnet-sdk-6.0.100-rc.1.21424.13] SCF Failed to launch after retargetting to .NET 6.0

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/aspnetcore#35985]
**Application Name**: SCF
**OS**: Windows 10 RS5
**CPU**: X64
**.NET Build Number**: dotnet-sdk-6.0.100-rc.1.21424.13

**Verify Scenarios:**
1) Windows 10 RS5 X64 + dotnet-sdk-6.0.100-rc.1.21410.9: Pass
2) Windows 10 RS5 X64 + dotnet-sdk-6.0.100-rc.1.21424.13: Fail
3) Windows 10 RS5 X64 + dotnet-sdk-6.0.100-rc.1.21430.18: Fail

**App Source checking at** :https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1389640 

**Repro steps:**
This is a .netcore 3.1 app, issue occurs when re-targeting it to .NET 6.0 rc1 build. And this app only can be built successful with Visual Studio.

1) Copy app source to machine 
2) Open the SCF-master\src\SCF.sln in Visual Studio 2019 Preview.
3) Build the solution.
4) Copy node_modules folder from SCF-master\src\Senparc.Web\ to SCF-master\src\Senparc.Web\bin\Debug\net6.0\
5) Press F5 to launch the application.

**Expected Result:**
SCF application can be launched successful.

**Actual Result:**
We get this error message when launching the app:
A descriptor for '/Pages/Docs/Index.cshtml' was not found.

**Findings :**
StackTace in Visual Studio is:
```
 at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.CompiledPageActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)

   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.UpdateCollection()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.Initialize()
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.<>c__DisplayClass11_0.<Subscribe>b__0()
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.Subscribe()
   at Microsoft.AspNetCore.Builder.RazorPagesEndpointRouteBuilderExtensions.GetOrCreateDataSource(IEndpointRouteBuilder endpoints)
   at Microsoft.AspNetCore.Builder.RazorPagesEndpointRouteBuilderExtensions.MapRazorPages(IEndpointRouteBuilder endpoints)
   at Senparc.Web.Startup.<>c.<Configure>b__8_0(IEndpointRouteBuilder endpoints) in C:\Retarget\SCF-master\src\Senparc.Web\Startup.cs:line 67
```

**Because of this issue:**

[.NET 6] [Runtime Compat Failure] ABP Framework template (3.1) fails to launch when target to 6 · Issue dotnet/runtime#29815 · dotnet/aspnetcore (github.com)
We update the Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation package and its dependencies to latest 6.0.0-preview.7.21378.6 version. 
Now, when we launch the app in Visual Studio, we get this error in browser:
```
ArgumentNullException: Value cannot be null. (Parameter 'type')
System.Reflection.IntrospectionExtensions.GetTypeInfo(Type type)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.CompiledPageActionDescriptorFactory.CreateCompiledDescriptor(PageActionDescriptor actionDescriptor, CompiledViewDescriptor viewDescriptor)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.DefaultPageLoader.LoadAsyncCore(PageActionDescriptor actionDescriptor, EndpointMetadataCollection endpointMetadata)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageLoaderMatcherPolicy.ApplyAsyncAwaited(CandidateSet candidates, Task<CompiledPageActionDescriptor> actionDescriptorTask, int index)
Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

@dotnet-actwx-bot @dotnet/compat

**Comment by mkArtakMSFT** [comment]
@pranavkm can you please look into this? Thanks!

**Comment by pranavkm** [comment]
This was resolved in the VS issue. The app was being built using VS 2019 which does not support Razor.

**Comment by Junjun-zhao** [comment]
Thanks @pranavkm . Closing it as app can be launched well when retargeting with VS 2022.
