### ISSUE TITLE
"'WebViewNavigationManager' has not been initialized" when using BaseAddressAuthorizationMessageHandler

### ISSUE THREAD

**Issue by LordBenjamin** [dotnet/aspnetcore#36892]
### Describe the bug
Unable to use `BaseAddressAuthorizationMessageHandler` within MAUI WPF BlazorWebView. Adding this handler causes an exception to be thrown - "'WebViewNavigationManager' has not been initialized."

The same code is working in a browser-based Blazor WebAssembly application.

N.B. This is a simplified reproduction that still exhibits the same exception.

Appreciate that the answer may be Microsoft.AspNetCore.Components.*WebAssembly*.Authentication isn't supported within Blazor WebView - if this is the case, is there a preferred way to obtain an MSAL token inside a Blazor WebView app?

### To Reproduce
```c#
using Microsoft.AspNetCore.Components.WebAssembly.Authentication;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Net.Http;
using System.Threading.Tasks;

namespace ClientApp
{
    public static class Program {

        public static void Main(string[] args) {
            var services = new ServiceCollection();

            services
                .AddBlazorWebView();

            services.AddSingleton<IAccessTokenProvider>(new FakeAccessTokenProvider());

            services.AddScoped<BaseAddressAuthorizationMessageHandler>();

            services
                .AddHttpClient("WithBaseAddress", client => client.BaseAddress = new Uri("http://example.com/"))
                .AddHttpMessageHandler<BaseAddressAuthorizationMessageHandler>();

            var serviceProvider = services.BuildServiceProvider();

            // Succeeds
            serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient();

            // Throws
            serviceProvider.GetRequiredService<IHttpClientFactory>().CreateClient("WithBaseAddress");
        }

        private class FakeAccessTokenProvider : IAccessTokenProvider
        {
            public ValueTask<AccessTokenResult> RequestAccessToken()
            {
                return RequestAccessToken(null);
            }

            public ValueTask<AccessTokenResult> RequestAccessToken(AccessTokenRequestOptions options)
            {
                return ValueTask.FromResult(new AccessTokenResult(AccessTokenResultStatus.Success, new AccessToken(), "http://example.com"));
            }
        }
    }
}

```

### Exceptions (if any)
```text
'WebViewNavigationManager' has not been initialized.
   at Microsoft.AspNetCore.Components.NavigationManager.AssertInitialized()
   at Microsoft.AspNetCore.Components.NavigationManager.get_BaseUri()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.BaseAddressAuthorizationMessageHandler..ctor(IAccessTokenProvider provider, NavigationManager navigationManager)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.<>c__4`1.<AddHttpMessageHandler>b__4_1(HttpMessageHandlerBuilder b)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.<>c__DisplayClass17_0.<CreateHandlerEntry>g__Configure|0(HttpMessageHandlerBuilder b)
   at Microsoft.Extensions.Http.LoggingHttpMessageHandlerBuilderFilter.<>c__DisplayClass3_0.<Configure>b__0(HttpMessageHandlerBuilder builder)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandlerEntry(String name)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.<>c__DisplayClass14_0.<.ctor>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandler(String name)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateClient(String name)
   at ClientApp.Program.Main(String[] args) in C:\Users\ben.owen\Source\Repos\Solution1\ClientApp\Program.cs:line 31
```

### Further technical details
- **ASP.NET Core version**
Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15
- **Include the output of `dotnet --info`**
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21458.32
 Commit:    d7c22323c4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.1.21458.32\

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

.NET SDKs installed:
  3.1.413 [C:\Program Files\dotnet\sdk]
  5.0.207 [C:\Program Files\dotnet\sdk]
  5.0.300 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21458.32 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- **The IDE (VS / VS Code/ VS4Mac) you're running on, and its version**
VS 2022 Preview 4

**Comment by javiercn** [comment]
@LordBenjamin thanks for contacting us.

That component is for use with webassembly, we don't guarantee it works outside of it. In general, you shouldn't be using this package to do auth in Blazor desktop and instead you should leverage the existing platform auth libraries for it.

**Comment by LordBenjamin** [comment]
Thanks for the quick reply - much appreciated!

My understanding of the WPF MSAL package is that the API surface is quite different to the WASM package. We're aiming to target browser and desktop with as little code difference as possible. Is there any plan to unify the authentication experience? Or at least some of the API primitives etc?

**Comment by gdar91** [comment]
Try registering the IAccessTokenProvider as a scoped dependency.

**Comment by LordBenjamin** [comment]
@gdar91 you mean like this?

```c#
services.AddScoped<IAccessTokenProvider>(sp => new FakeAccessTokenProvider());
```

I have tried this and it doesn't seem to make any difference. Am I missing something?

**Comment by gdar91** [comment]
@LordBenjamin Normally the razor rendering engine should initialize the WebViewNavigationManager. If I remember correctly, I also had to go to the main App.razor file, add an inject statement for the WebViewNavigationManager and make sure to start using this dependency only after the App.razor is done with initialization steps.

**Comment by LordBenjamin** [comment]
@gdar91 - Thanks for the suggestion. I have also tested delaying the instantiation of the `HttpClient` by moving it to a button click event handler - this is only possible to click once the WebView is visible and displaying content. This still throws the same exception.

```c#
private void Button_Click(object sender, RoutedEventArgs e) {
    ((ServiceProvider)Resources["services"]).GetRequiredService<IHttpClientFactory>().CreateClient("HttpClient");
}
```

I believe it may be _possible_ to make this work as-is, but it feels like it will always be a bit of a brittle solution (sensitive to order of operations) and @javiercn's previous comment makes it clear that the Blazor team do not currently support this approach - as such, hacking it to work is a risk that I am not willing to take.
