### ISSUE TITLE
SignalR tests fail against OpenSSL 3.0

### ISSUE THREAD

**Issue by omajid** [dotnet/aspnetcore#36921]
### Describe the bug

I am trying to build and run ASP.NET Core tests with OpenSSL 3.0. The test fail with OpenSSL errors.

This is https://github.com/dotnet/aspnetcore sha 277e42f4dcf1ee41c8a1b61a6aaa3e17ef15a1d9.

```
$ eng/build.sh --arch x64 --test
...
...
  $ node ../common/node_modules/typescript/bin/tsc --project ./tsconfig.json --module commonjs --outDir ./dist/cjs
  $ node ../common/node_modules/webpack-cli/bin/cli.js
  /home/tester/aspnetcore/src/SignalR/clients/ts/common/node_modules/loader-runner/lib/LoaderRunner.js:146
  		if(isError) throw e;
  		            ^
  
Error : error : 0308010C:digital envelope routines::unsupported [/home/tester/aspnetcore/src/SignalR/clients/ts/signalr/signalr.npmproj]
      at new Hash (node:internal/crypto/hash:67:19)
      at Object.createHash (node:crypto:130:10)
      at BulkUpdateDecorator.hashFactory (/home/tester/aspnetcore/src/SignalR/clients/ts/common/node_modules/webpack/lib/util/createHash.js:144:18)
      at BulkUpdateDecorator.update (/home/tester/aspnetcore/src/SignalR/clients/ts/common/node_modules/webpack/lib/util/createHash.js:46:50)
      at SourceMapSource.updateHash (/home/tester/aspnetcore/src/SignalR/clients/ts/common/node_modules/webpack-sources/lib/SourceMapSource.js:233:8)
      at NormalModule._initBuildHash (/home/tester/aspnetcore/src/SignalR/clients/ts/common/node_modules/webpack/lib/NormalModule.js:853:17)
      at handleParseResult (/home/tester/aspnetcore/src/SignalR/clients/ts/common/node_modules/webpack/lib/NormalModule.js:918:10)
      at /home/tester/aspnetcore/src/SignalR/clients/ts/common/node_modules/webpack/lib/NormalModule.js:1009:4
      at processResult (/home/tester/aspnetcore/src/SignalR/clients/ts/common/node_modules/webpack/lib/NormalModule.js:732:11)
      at /home/tester/aspnetcore/src/SignalR/clients/ts/common/node_modules/webpack/lib/NormalModule.js:792:5 {
    opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
    library: 'digital envelope routines',
    reason: 'unsupported',
    code: 'ERR_OSSL_EVP_UNSUPPORTED'
  }

```

Is this a bug in nodejs, in an (external) node module or in SignalR itself? this a known issue? Is OpenSSL 3.0 supported?

### To Reproduce

Here's a Dockerfile to reproduce the issue:

```Dockerfile
FROM quay.io/centos/centos:stream9-development

RUN cat /etc/os-release && \
    dnf install -y dnf-plugins-core && \
    dnf repolist --all && \
    dnf config-manager --set-enabled crb && \
    dnf install -y findutils git glibc-langpack-en libicu nodejs

CMD git clone https://github.com/dotnet/aspnetcore && \
    cd aspnetcore && \
    git submodule update --init && \
    ./eng/build.sh --arch x64 --test
```

FWIW, CentOS Stream 9 is the in-development version of RHEL 9. RHEL 9 will have OpenSSL 3.0 as the default version of OpenSSL.

**Comment by BrennanConroy** [comment]
Looks like a webpack issue https://github.com/webpack/webpack/issues/13572#issuecomment-923653464

**Comment by adityamandaleeka** [comment]
Thanks for reporting this.

cc: @karelz

**Comment by AraHaan** [comment]
They have fixed webpack, any ETA on when this will be fixed?

**Comment by AraHaan** [comment]
I think the fix for this is to update webpack on this repository.

**Comment by BrennanConroy** [comment]
Can you try updating WebPack and seeing if the issue goes away? I don't know of a good way to repro the issue.

**Comment by halter73** [comment]
Another workaround is:

```sh
export NODE_OPTIONS=--openssl-legacy-provider
```

https://github.com/webpack/webpack/issues/14532#issuecomment-947012063

But that can cause other issues like https://github.com/microsoft/vscode/issues/136599. We're updating our dependencies so this won't be necessary.
