### ISSUE TITLE
Flaky test - WriteAfterConnectionCloseNoops-http_127.0.0.1_0

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#36931]
## Failing Test(s)

- Microsoft.AspNetCore.Server.Kestrel.Libuv.FunctionalTests.ResponseTests.WriteAfterConnectionCloseNoops

## Error Message

```text
System.TimeoutException : The operation has timed out.
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 143
   at Microsoft.AspNetCore.Server.Kestrel.Libuv.FunctionalTests.ResponseTests.WriteAfterConnectionCloseNoops(ListenOptions listenOptions) in /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs:line 186
   at Microsoft.AspNetCore.Server.Kestrel.Libuv.FunctionalTests.ResponseTests.WriteAfterConnectionCloseNoops(ListenOptions listenOptions) in /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs:line 193
--- End of stack trace from previous location ---
```
</details>

## Logs

<details>

```text
[0.002s] [TestLifetime] [Information] Starting test WriteAfterConnectionCloseNoops-http_127.0.0.1_0 at 2021-09-24T12:54:51
[0.004s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting starting
[0.006s] [Microsoft.Hosting.Lifetime] [Information] Now listening on: http://127.0.0.1:64434
[0.006s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Debug] Loaded hosting startup assembly Libuv.FunctionalTests
[0.007s] [Microsoft.Hosting.Lifetime] [Information] Application started. Press Ctrl+C to shut down.
[0.007s] [Microsoft.Hosting.Lifetime] [Information] Hosting environment: Production
[0.007s] [Microsoft.Hosting.Lifetime] [Information] Content root path: /private/tmp/helix/working/9BD208CB/w/A936094C/e/
[0.007s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting started
[0.007s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] TestServer is listening on port 64434
[0.009s] [Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv] [Debug] Connection id "0HMBVB9VLT33O" received FIN.
[0.010s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMBVB9VLT33O" accepted.
[0.010s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMBVB9VLT33O" started.
[0.010s] [Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv] [Debug] Connection id "0HMBVB9VLT33O" sending FIN because: "The client closed the connection."
[0.010s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMBVB9VLT33O" disconnecting.
[0.010s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMBVB9VLT33O" stopped.
[30.154s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting stopping
[30.154s] [Microsoft.Hosting.Lifetime] [Information] Application is shutting down...
[30.155s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting stopped
[30.208s] [Microsoft.AspNetCore.Server.Kestrel.Libuv.FunctionalTests.ResponseTests] [Error] Test threw an exception.
System.TimeoutException: The operation has timed out.
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 143
   at Microsoft.AspNetCore.Server.Kestrel.Libuv.FunctionalTests.ResponseTests.WriteAfterConnectionCloseNoops(ListenOptions listenOptions) in /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs:line 186
   at Microsoft.AspNetCore.Server.Kestrel.Libuv.FunctionalTests.ResponseTests.WriteAfterConnectionCloseNoops(ListenOptions listenOptions) in /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs:line 193
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 273
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 54
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 96
[30.208s] [TestLifetime] [Information] Finished test WriteAfterConnectionCloseNoops-http_127.0.0.1_0 in 30.2052938s
```
</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1383371&view=ms.vss-test-web.build-test-results-tab&runId=40310620&resultId=119125&paneView=debug

**Comment by adityamandaleeka** [comment]
Triage: we can disable the libuv testing (since the transport has been deprecated since .NET 5) on macOS, where it's flaky.
