### ISSUE TITLE
dotnet watch: Ctrl-C doesn't reset the terminal echo on Mac

### ISSUE THREAD

**Issue by lambdageek** [dotnet/aspnetcore#37047]
### Describe the bug

Hitting ctrl-C to quit a `dotnet watch` session leaves the terminal echo off if `watch` is waiting for the browser to report back the ApplyUpdate capabilities

### To Reproduce

1. Install .NET 6 RC 2
1. Open an iterm2 terminal or a Terminal.app terminal.
1. `dotnet new blazorwasm`
2. `dotnet watch run` and wait for browser to open; (optional) interact with the app 
3. Hit Ctrl-C in the terminal window
4. type "echo Hello" or anything else at the terminal prompt

Expected result:
Terminal displays the characters that you type as you type them

Actual result:

Terminal doesn't echo what you type.
If you hit return, the command still runs.

type `reset` and hit Enter to reset the terminal and get normal behavior.

### Exception

```
$ dotnet watch run
watch : Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload. Press "Ctrl + R" to restart.
watch : Building...
  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  blazor-dynamicmethod -> /Users/alklig/work/blazor-dynamicmethod/bin/Debug/net6.0/blazor-dynamicmethod.dll
  blazor-dynamicmethod (Blazor output) -> /Users/alklig/work/blazor-dynamicmethod/bin/Debug/net6.0/wwwroot
watch : Started
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:7081
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5198
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/alklig/work/blazor-dynamicmethod
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
watch : Shutdown requested. Press Ctrl+C again to force exit.
Unhandled exception. System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.DotNet.Watcher.Tools.BrowserRefreshServer.WaitForClientConnectionAsync(CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.Tools.BlazorWebAssemblyDeltaApplier.<>c__DisplayClass6_0.<<GetApplyUpdateCapabilitiesAsync>g__GetApplyUpdateCapabilitiesCoreAsync|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Watcher.Tools.CompilationWorkspaceProvider.CreateProject(TaskCompletionSource`1 taskCompletionSource, Task`1 hotReloadCapabilitiesTask, String projectPath, IReporter reporter, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__127_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

### Further technical details

```
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.2.21474.31
 Commit:    c760c779e4

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.6
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100-rc.2.21474.31/

Host (useful for support):
  Version: 6.0.0-rc.2.21470.23
  Commit:  826f81a11a

.NET SDKs installed:
  5.0.401 [/usr/local/share/dotnet/sdk]
  6.0.100-rc.1.21463.6 [/usr/local/share/dotnet/sdk]
  6.0.100-rc.2.21474.31 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21470.37 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21470.23 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by lambdageek** [comment]
This might be related to something going on with Chrome and the ASP.NET Core dev certificate.  If I open the http watch URL instead of https, `dotnet watch` doesn't hit that exception.

**Comment by TanayParikh** [comment]
Getting this on linux / github codespaces as well.
