### ISSUE TITLE
Using Speech with Blazor Wasm hosted App (.NET 6 RC1)

### ISSUE THREAD

**Issue by nssidhu** [dotnet/aspnetcore#37063]
```
 var config = SpeechConfig.FromSubscription("XXXXXXXXXXXXXXXXXX", "eastus");
            config.SpeechSynthesisVoiceName = "en-US-ChristopherNeural";
            using var synthesizer = new SpeechSynthesizer(config);
            await synthesizer.SpeakTextAsync("Synthesizing directly to speaker output.");
```

The code above works in .NET 6 RC1 console app, but does not work in Blazor Wasm.
Is Azure Speech supported in Blazor Wasm ?

```
GetInLineV6New.Client.Pages.Org.ManageOrgLocationTerminals[0]
      Error : System.DllNotFoundException: Microsoft.CognitiveServices.Speech.core.dll
         at Microsoft.CognitiveServices.Speech.SpeechConfig.FromSubscription(String subscriptionKey, String region)
         at GetInLineV6New.Client.Pages.Org.ManageOrgLocationTerminals.SayText() in C:\Users\admin\source\repos\GetInLineV6New\GetInLineV6New\Client\Pages\Org\ManageOrgLocationTerminals.razor.cs:line 75
         at GetInLineV6New.Client.Pages.Org.ManageOrgLocationTerminals.GetOrgLocationTerminals() in C:\Users\admin\source\repos\GetInLineV6New\GetInLineV6New\Client\Pages\Org\ManageOrgLocationTerminals.razor.cs:line 398
         at GetInLineV6New.Client.Pages.Org.ManageOrgLocationTerminals.OnInitializedAsync() in C:\Users\admin\source\repos\GetInLineV6New\GetInLineV6New\Client\Pages\Org\ManageOrgLocationTerminals.razor.cs:line 147
```

**Comment by javiercn** [comment]
@nssidhu thanks for contacting us.

It's not clear what's going on here. Maybe file an issue in the azure sdk repo as they might be able to provide an answer faster? I suspect that if what you are trying to accomplish is for audio to play, it is unlikely that the .NET SDK will work in Blazor webassembly since it's very probable that it uses native APIs to accomplish that which are not available in the browser.

I would check if there is a browser based SDK to accomplish what you are trying to achieve, and use that via JS interop instead.
