### ISSUE TITLE
Blazor WebAssembly SPA unauthorized when sending request to API which is hosted on http.sys with windows authentication

### ISSUE THREAD

**Issue by AB017JH** [dotnet/aspnetcore#37093]
Hello,

I am struggling to get this working. After I switched Blazor wasm hosted from IIS to http.sys windows authentication broke. Now blazor and server (http.sys) runs on different ports. When Blazor tries to consume authorized endpoint from the server it results in 
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Response status code does not indicate success: 401 (Unauthorized).
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized) with exception
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync(Uri url, HttpClient httpClient, ILogger logger, CancellationToken cancellationToken)
```
when the same URL endpoint of API is called from browser i.e running _http://localhost:44302/api/sth_ it behaves as expected and a popup for input credentials is shown.

**Comment by AB017JH** [comment]
Ok.. I dig around the issues here and found this https://github.com/dotnet/aspnetcore/issues/25231 when I use it for API calls it works, but if I would want to use the SignalR HubConnection a call Authorized Hub, where do I set the HttpRequest. This behavior feels odd to me, that I need to specify in the request everytime I call API which uses windows authentication.

**Comment by AB017JH** [comment]
Found solution for the SignalR connection here: https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-5.0&pivots=webassembly

**Comment by AB017JH** [comment]
and solution for HttClient is basically the same as for SignalR -> add the HttpHandler to it
Closing it.
