### ISSUE TITLE
JSON/Blazor regression on deserializing IJSInProcessObjectReference with a constructor

### ISSUE THREAD

**Issue by user72356** [dotnet/aspnetcore#37149]
### Describe the bug

This is in a Blazor Webassembly project. Regression in .Net 6 when trying to deserialize a IJSInProcessObjectReference parameter in a valid JSON constructor. Receiving a "System.InvalidCastException: Specified cast is not valid."

It works just fine in .Net 5.

Additionally:

- If I remove the parameterized constructor the deserialization works fine.
- No problems at all with a IJSObjectReference instead of a IJSInProcessObjectReference.

### To Reproduce

Here is a repo that contains 2 Blazor wasm projects, one is .Net 5 (it works as expected) and the other .Net 6 (producing the error above): 

https://github.com/user72356/public

### Exceptions (if any)

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: System.InvalidCastException: Specified cast is not valid.
         at System.Text.Json.Serialization.Converters.SmallObjectWithParameterizedConstructorConverter`5[[TestSerializerDotNet6.Pages.Index.HelloObjectWrapper, TestSerializerDotNet6, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.JSInterop.IJSInProcessObjectReference, Microsoft.JSInterop, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InitializeConstructorArgumentCaches(ReadStack& state, JsonSerializerOptions options)
         at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1[[TestSerializerDotNet6.Pages.Index.HelloObjectWrapper, TestSerializerDotNet6, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, HelloObjectWrapper& value)
         at System.Text.Json.Serialization.JsonConverter`1[[TestSerializerDotNet6.Pages.Index.HelloObjectWrapper, TestSerializerDotNet6, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, HelloObjectWrapper& value)
         at System.Text.Json.Serialization.JsonConverter`1[[TestSerializerDotNet6.Pages.Index.HelloObjectWrapper, TestSerializerDotNet6, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.Serialization.JsonConverter`1[[TestSerializerDotNet6.Pages.Index.HelloObjectWrapper, TestSerializerDotNet6, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadCore[Object](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.JsonSerializer.Read[Object](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
         at System.Text.Json.JsonSerializer.Deserialize(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
         at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.ParseArguments(JSRuntime jsRuntime, String methodIdentifier, String arguments, Type[] parameterTypes)
         at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
         at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.Invoke(JSRuntime jsRuntime, DotNetInvocationInfo& invocationInfo, String argsJson)
         at Microsoft.AspNetCore.Components.WebAssembly.Services.DefaultWebAssemblyJSRuntime.InvokeDotNet(String assemblyName, String methodIdentifier, String dotNetObjectId, String argsJson)
      Error: System.InvalidCastException: Specified cast is not valid.
         at System.Text.Json.Serialization.Converters.SmallObjectWithParameterizedConstructorConverter`5[[TestSerializerDotNet6.Pages.Index.HelloObjectWrapper, TestSerializerDotNet6, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.JSInterop.IJSInProcessObjectReference, Microsoft.JSInterop, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InitializeConstructorArgumentCaches(ReadStack& state, JsonSerializerOptions options)
         at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1[[TestSerializerDotNet6.Pages.Index.HelloObjectWrapper, TestSerializerDotNet6, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, HelloObjectWrapper& value)
         at System.Text.Json.Serialization.JsonConverter`1[[TestSerializerDotNet6.Pages.Index.HelloObjectWrapper, TestSerializerDotNet6, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, HelloObjectWrapper& value)
         at System.Text.Json.Serialization.JsonConverter`1[[TestSerializerDotNet6.Pages.Index.HelloObjectWrapper, TestSerializerDotNet6, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.Serialization.JsonConverter`1[[TestSerializerDotNet6.Pages.Index.HelloObjectWrapper, TestSerializerDotNet6, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadCore[Object](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.JsonSerializer.Read[Object](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
         at System.Text.Json.JsonSerializer.Deserialize(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
         at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.ParseArguments(JSRuntime jsRuntime, String methodIdentifier, String arguments, Type[] parameterTypes)
         at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
         at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.Invoke(JSRuntime jsRuntime, DotNetInvocationInfo& invocationInfo, String argsJson)
         at Microsoft.AspNetCore.Components.WebAssembly.Services.DefaultWebAssemblyJSRuntime.InvokeDotNet(String assemblyName, String methodIdentifier, String dotNetObjectId, String argsJson)
          at Object._convert_exception_for_method_call (http://localhost:5290/_framework/dotnet.6.0.0-rc.1.21451.13.js:1:178682)
          at Object._handle_exception_for_call (http://localhost:5290/_framework/dotnet.6.0.0-rc.1.21451.13.js:1:180651)
          at managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_InvokeDotNet (https://mono-wasm.invalid/managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_InvokeDotNet:20:21)
          at Object.invokeDotNetFromJS (http://localhost:5290/_framework/blazor.webassembly.js:1:41033)
          at g (http://localhost:5290/_framework/blazor.webassembly.js:1:1618)
          at Object.e.invokeMethod (http://localhost:5290/_framework/blazor.webassembly.js:1:2665)
          at window.callDotNet (http://localhost:5290/index.js:7:12)
          at Object.invokeJSFromDotNet (http://localhost:5290/_framework/blazor.webassembly.js:1:3179)
          at Object.At [as invokeJSFromDotNet] (http://localhost:5290/_framework/blazor.webassembly.js:1:58414)
          at _mono_wasm_invoke_js_blazor (http://localhost:5290/_framework/dotnet.6.0.0-rc.1.21451.13.js:1:193753)
Microsoft.JSInterop.JSException: System.InvalidCastException: Specified cast is not valid.
   at System.Text.Json.Serialization.Converters.SmallObjectWithParameterizedConstructorConverter`5[[TestSerializerDotNet6.Pages.Index.HelloObjectWrapper, TestSerializerDotNet6, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.JSInterop.IJSInProcessObjectReference, Microsoft.JSInterop, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InitializeConstructorArgumentCaches(ReadStack& state, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1[[TestSerializerDotNet6.Pages.Index.HelloObjectWrapper, TestSerializerDotNet6, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, HelloObjectWrapper& value)
   at System.Text.Json.Serialization.JsonConverter`1[[TestSerializerDotNet6.Pages.Index.HelloObjectWrapper, TestSerializerDotNet6, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, HelloObjectWrapper& value)
   at System.Text.Json.Serialization.JsonConverter`1[[TestSerializerDotNet6.Pages.Index.HelloObjectWrapper, TestSerializerDotNet6, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1[[TestSerializerDotNet6.Pages.Index.HelloObjectWrapper, TestSerializerDotNet6, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[Object](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.Read[Object](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.ParseArguments(JSRuntime jsRuntime, String methodIdentifier, String arguments, Type[] parameterTypes)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.Invoke(JSRuntime jsRuntime, DotNetInvocationInfo& invocationInfo, String argsJson)
   at Microsoft.AspNetCore.Components.WebAssembly.Services.DefaultWebAssemblyJSRuntime.InvokeDotNet(String assemblyName, String methodIdentifier, String dotNetObjectId, String argsJson)
Error: System.InvalidCastException: Specified cast is not valid.
   at System.Text.Json.Serialization.Converters.SmallObjectWithParameterizedConstructorConverter`5[[TestSerializerDotNet6.Pages.Index.HelloObjectWrapper, TestSerializerDotNet6, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.JSInterop.IJSInProcessObjectReference, Microsoft.JSInterop, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InitializeConstructorArgumentCaches(ReadStack& state, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1[[TestSerializerDotNet6.Pages.Index.HelloObjectWrapper, TestSerializerDotNet6, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, HelloObjectWrapper& value)
   at System.Text.Json.Serialization.JsonConverter`1[[TestSerializerDotNet6.Pages.Index.HelloObjectWrapper, TestSerializerDotNet6, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, HelloObjectWrapper& value)
   at System.Text.Json.Serialization.JsonConverter`1[[TestSerializerDotNet6.Pages.Index.HelloObjectWrapper, TestSerializerDotNet6, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1[[TestSerializerDotNet6.Pages.Index.HelloObjectWrapper, TestSerializerDotNet6, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[Object](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.Read[Object](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.ParseArguments(JSRuntime jsRuntime, String methodIdentifier, String arguments, Type[] parameterTypes)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.Invoke(JSRuntime jsRuntime, DotNetInvocationInfo& invocationInfo, String argsJson)
   at Microsoft.AspNetCore.Components.WebAssembly.Services.DefaultWebAssemblyJSRuntime.InvokeDotNet(String assemblyName, String methodIdentifier, String dotNetObjectId, String argsJson)
    at Object._convert_exception_for_method_call (http://localhost:5290/_framework/dotnet.6.0.0-rc.1.21451.13.js:1:178682)
    at Object._handle_exception_for_call (http://localhost:5290/_framework/dotnet.6.0.0-rc.1.21451.13.js:1:180651)
    at managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_InvokeDotNet (https://mono-wasm.invalid/managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_InvokeDotNet:20:21)
    at Object.invokeDotNetFromJS (http://localhost:5290/_framework/blazor.webassembly.js:1:41033)
    at g (http://localhost:5290/_framework/blazor.webassembly.js:1:1618)
    at Object.e.invokeMethod (http://localhost:5290/_framework/blazor.webassembly.js:1:2665)
    at window.callDotNet (http://localhost:5290/index.js:7:12)
    at Object.invokeJSFromDotNet (http://localhost:5290/_framework/blazor.webassembly.js:1:3179)
    at Object.At [as invokeJSFromDotNet] (http://localhost:5290/_framework/blazor.webassembly.js:1:58414)
    at _mono_wasm_invoke_js_blazor (http://localhost:5290/_framework/dotnet.6.0.0-rc.1.21451.13.js:1:193753)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeJS(String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSInProcessRuntime.Invoke[Object](String identifier, Int64 targetInstanceId, Object[] args)
   at Microsoft.JSInterop.JSInProcessRuntime.Invoke[Object](String identifier, Object[] args)
   at Microsoft.JSInterop.JSInProcessRuntimeExtensions.InvokeVoid(IJSInProcessRuntime jsRuntime, String identifier, Object[] args)
   at TestSerializerDotNet6.Pages.Index.OnInitialized() in c:\Users\Ni\source\public\TestSerializerDotNet6\TestSerializerDotNet6\Pages\Index.razor:line 46
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

### Further technical details
- ASP.NET Core version: .Net 6.0 RC1
- Include the output of `dotnet --info`

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21463.6
 Commit:    e627d556a1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.1.21463.6\

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

.NET SDKs installed:
  3.1.402 [C:\Program Files\dotnet\sdk]
  3.1.413 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21463.6 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Microsoft Visual Studio Community 2022 Preview, Version 17.0.0 Preview 4.1

**Comment by mkArtakMSFT** [comment]
Moving this to .NET 7 planning to evaluate the impact. At this point it's not clear how impactful the scenario is.

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
