### ISSUE TITLE
Shrink blazor.*.js file size, SignalR Minification

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#37260]
@BrennanConroy mentioned:

> SignalR mangles properties with the _ prefix so the compiler can reduce property names to single or double characters in the output, but it looks like blazor consumes SignalR from source, or from a non-mangled build. Also, blazor could add the _prefix and convert any private properties to get some savings. You can do that by adding this to the optimization section of webpack.config.js https://github.com/dotnet/aspnetcore/blob/711bdcf96afbbbe122a302ddc641accea0768431/src/SignalR/clients/ts/webpack.config.base.js#L96

This issue tracks this effort to ensure we're minifying the SignalR bits. Not sure if we'll be able to take this for 6.0 given the current stage of the release, but will dig into it once I have some time available.

**Comment by TanayParikh** [comment]
Tried this out via https://github.com/dotnet/aspnetcore/pull/42268, this doesn't seem to be immediately feasible just by mangling alone as it causes issues with `Blazor._internal` which is an `internal` type for Blazor, but we cannot let it get mangled as it's called into from .NET via JS interop. 

This issue breaks down into two parts. Mangling the blazor source code, and ensuring the SignalR code we take is/becomes mangled.

The former will likely be a larger undertaking and with fairly low benefit. For instance take a look at the WASM/WebView size improvements below.

|File|Current Size|Optimized Size|
|---|---|---|
|blazor.server.js|130 kb|122 kb|
|blazor.webassembly.js|60 kb|59 kb|
|blazor.webview.js|40.5 kb|39.8 kb|

The `blazor.server.js` improvement is relatively larger than WASM/WebView, on account of mangling the SignalR code. 

Next steps for this issue would likely in that case be to figure out how we can either take the existing mangled SignalR code instead of the source code we're taking now, or how we can mangle _just_ the SignalR code without touching the Blazor code. I'm pushing this back into backlog at this point in time.

**Comment by BrennanConroy** [comment]
If `_internal` is the only thing that shouldn't be mangled, you can exclude it https://github.com/terser/terser#cli-mangle-options

**Comment by TanayParikh** [comment]
<img width="578" alt="image" src="https://user-images.githubusercontent.com/14852843/174410820-d5d32f86-8833-449b-b2e3-c6124a789cba.png">

Not seeing any other `Blazor._*` usage other than `Blazor._internal`.

So tried that out, but still ran into other issues:


<div tabindex="-1" class="console-message-wrapper console-error-level console-selected" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; display: flex; border-top-width: ; border-top-style: ; border-top-color: var(--override-error-border-color); border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: var(--override-focused-message-border-color); --console-color-black: #000; --console-color-red: rgb(237 78 76); --console-color-green: rgb(1 200 1); --console-color-yellow: rgb(210 192 87); --console-color-blue: rgb(39 116 240); --console-color-magenta: rgb(161 66 244); --console-color-cyan: rgb(18 181 203); --console-color-gray: rgb(207 208 208); --console-color-darkgray: rgb(137 137 137); --console-color-lightred: rgb(242 139 130); --console-color-lightgreen: rgb(161 247 181); --console-color-lightyellow: rgb(221 251 85); --console-color-lightblue: rgb(102 157 246); --console-color-ightmagenta: #f5f; --console-color-lightcyan: rgb(132 240 255); --console-color-white: #fff; background-color: var(--override-focused-message-background-color); --console-color-lightmagenta: rgb(214 112 214); --override-error-text-color: hsl(0deg 100% 75%);"><div class="console-message" style="box-sizing: border-box; min-width: 0px; min-height: 17px; clear: right; position: relative; padding: 3px 22px 1px 0px; margin-left: 24px; flex: 1 1 auto; display: flex;"><div class="console-message-stack-trace-toggle" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: row; align-items: flex-start;"><div class="console-message-stack-trace-wrapper" aria-label="Microsoft.JSInterop.js:319  Uncaught (in promise) Error: System.ArgumentException: Property 'AssemblyName' cannot be null, empty, or whitespace. (Parameter 'assemblyKey')
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.GetCachedMethodInfo(/AssemblyKey assembl…ng methodIdentifier) in /workspaces/aspnetcore/src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetDispatcher.cs:line 355
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(/JSRuntime jsRuntime…ce, String argsJson) in /workspaces/aspnetcore/src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetDispatcher.cs:line 167
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet(/JSRuntime jsRuntime…fo, String argsJson) in /workspaces/aspnetcore/src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetDispatcher.cs:line 97
    at Te.endInvokeDotNetFromJS (Microsoft.JSInterop.js:319:19)
    at Te.be (HubConnection.js:542:31)
    at Te.Wt (HubConnection.js:407:30)
    at Te.connection.onreceive (HubConnection.js:42:52)
    at s.onmessage (WebSocketTransport.js:81:30) Stack table expanded" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: column; align-items: stretch;"><div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color)  !important;">Uncaught (in promise) <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">Error: System.ArgumentException: Property 'AssemblyName' cannot be null, empty, or whitespace. (Parameter 'assemblyKey')
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.GetCachedMethodInfo(<span class="devtools-link" title="https://tanayparikh-dotnet-aspnetcore-w9r77xj5h6p6-5001.githubpreview.dev/AssemblyKey assemblyKey, String methodIdentifier" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; cursor: pointer; word-break: break-all;">/AssemblyKey assembl<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>ng methodIdentifier</span>) in /workspaces/aspnetcore/src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetDispatcher.cs:line 355
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(<span class="devtools-link" title="https://tanayparikh-dotnet-aspnetcore-w9r77xj5h6p6-5001.githubpreview.dev/JSRuntime jsRuntime, DotNetInvocationInfo&amp; callInfo, IDotNetObjectReference objectReference, String argsJson" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; cursor: pointer; word-break: break-all;">/JSRuntime jsRuntime<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>ce, String argsJson</span>) in /workspaces/aspnetcore/src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetDispatcher.cs:line 167
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet(<span class="devtools-link" title="https://tanayparikh-dotnet-aspnetcore-w9r77xj5h6p6-5001.githubpreview.dev/JSRuntime jsRuntime, DotNetInvocationInfo invocationInfo, String argsJson" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; cursor: pointer; word-break: break-all;">/JSRuntime jsRuntime<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>fo, String argsJson</span>) in /workspaces/aspnetcore/src/JSInterop/Microsoft.JSInterop/src/Infrastructure/DotNetDispatcher.cs:line 97
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Te.endInvokeDotNetFromJS (<span class="devtools-link" role="link" tabindex="-1" title="webpack:///JSInterop/Microsoft.JSInterop.JS/src/dist/Microsoft.JSInterop.js:319:19" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; cursor: pointer; word-break: break-all;">Microsoft.JSInterop.js:319:19</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Te.be (<span class="devtools-link" role="link" tabindex="-1" title="webpack:///SignalR/clients/ts/signalr/dist/esm/HubConnection.js:542:31" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; cursor: pointer; word-break: break-all;">HubConnection.js:542:31</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Te.Wt (<span class="devtools-link" role="link" tabindex="-1" title="webpack:///SignalR/clients/ts/signalr/dist/esm/HubConnection.js:407:30" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; cursor: pointer; word-break: break-all;">HubConnection.js:407:30</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at Te.connection.onreceive (<span class="devtools-link" role="link" tabindex="-1" title="webpack:///SignalR/clients/ts/signalr/dist/esm/HubConnection.js:42:52" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; cursor: pointer; word-break: break-all;">HubConnection.js:42:52</span>)
</span><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at s.onmessage (<span class="devtools-link" role="link" tabindex="-1" title="webpack:///SignalR/clients/ts/signalr/dist/esm/WebSocketTransport.js:81:30" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; cursor: pointer; word-break: break-all;">WebSocketTransport.js:81:30</span>)</span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span class="monospace" style="display: inline-block; --monospace-font-size: 11px; --monospace-font-family: menlo, monospace; --source-code-font-size: 11px; --source-code-font-family: menlo, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size)  !important;">

  | endInvokeDotNetFromJS | @ | Microsoft.JSInterop.js:319
-- | -- | -- | --
  | be | @ | HubConnection.js:542
  | Wt | @ | HubConnection.js:407
  | Te.connection.onreceive | @ | HubConnection.js:42
  | s.onmessage | @ | WebSocketTransport.js:81

</span></div></div></div></div></div><div tabindex="-1" class="console-message-wrapper console-from-api console-info-level" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; border-top-width: ; border-top-style: ; border-top-color: transparent; border-bottom: 1px solid transparent; --console-color-black: #000; --console-color-red: rgb(237 78 76); --console-color-green: rgb(1 200 1); --console-color-yellow: rgb(210 192 87); --console-color-blue: rgb(39 116 240); --console-color-magenta: rgb(161 66 244); --console-color-cyan: rgb(18 181 203); --console-color-gray: rgb(207 208 208); --console-color-darkgray: rgb(137 137 137); --console-color-lightred: rgb(242 139 130); --console-color-lightgreen: rgb(161 247 181); --console-color-lightyellow: rgb(221 251 85); --console-color-lightblue: rgb(102 157 246); --console-color-ightmagenta: #f5f; --console-color-lightcyan: rgb(132 240 255); --console-color-white: #fff; --console-color-lightmagenta: rgb(214 112 214);"><div class="console-message" style="box-sizing: border-box; min-width: 0px; min-height: 17px; clear: right; position: relative; padding: 3px 22px 1px 0px; margin-left: 24px; flex: 1 1 auto; display: flex;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; flex: 1 1 auto; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px; color: rgb(255, 255, 255); font-family: menlo, monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: pre-wrap; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(36, 36, 36); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="devtools-link" role="link" tabindex="-1" title="webpack:///Platform/Logging/Loggers.ts:38" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;">Loggers.ts:38</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(255, 255, 255); font-family: menlo, monospace; font-size: 11px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre-wrap; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(36, 36, 36); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br class="Apple-interchange-newline">


---

asset blazor.server.js 122 KiB [emitted] [minimized] [big] (name: blazor.server)
asset blazor.webassembly.js 59.2 KiB [emitted] [minimized] (name: blazor.webassembly)
asset blazor.webview.js 39.8 KiB [emitted] [minimized] (name: blazor.webview)
orphan modules 452 KiB [orphan] 93 modules
runtime modules 221 bytes 1 module
cacheable modules 736 KiB
  ./Boot.Server.ts + 72 modules 390 KiB [built] [code generated]
  ./Boot.WebAssembly.ts + 31 modules 200 KiB [built] [code generated]
  ./Boot.WebView.ts + 28 modules 146 KiB [built] [code generated]


With further tweaking, improvements in this area should definitely be possible, but based on the preliminary numbers, I don't think they are high enough relative to the overall download size to make a substantial difference in load times. We can likely revisit this later as time permits.

**Comment by javiercn** [comment]
Closing this issue since it is no longer relevant.

Our focus is on `blazor.web.js` where in 10.0 are serving the files as SWA, which makes the use of minification inconsequential. 

There is a separate workitem tracking the breakdown of `blazor.web.js` into multiple files per render mode to address further size improvements.
