### ISSUE TITLE
'400 Bad Request' when connect some domains that contains '-' 

### ISSUE THREAD

**Issue by xljiulang** [dotnet/aspnetcore#37421]
### Describe the bug
Request
```
CONNECT user-images.githubusercontent.com:443 HTTP/1.1
Host: user-images.githubusercontent.com:443
Proxy-Connection: keep-alive
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36 Edg/94.0.992.38
```

Response
```
HTTP/1.1 400 Bad Request
Connection: close
Date: Sat, 09 Oct 2021 06:03:47 GMT
Server: Kestrel
Content-Length: 0
```

If the domain without '-', eg 'userimages.githubusercontent.com'，it will OK.

### Further technical details
- ASP.NET Core version:  Microsoft.NETCore.App 5.0.6
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: window 10 and 11
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```

```

</details>

**Comment by Tratcher** [comment]
What do the server logs say if you turn them up to Debug?

**Comment by xljiulang** [comment]
@Tratcher 
```
Microsoft.AspNetCore.Server.Kestrel
Connection id "0HMCBHKF0TMTP" bad request data: "Invalid request target: 'user-images.githubusercontent.com:443'"
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Invalid request target: 'user-images.githubusercontent.com:443'
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowRequestTargetRejected(Span`1 target)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.OnAuthorityFormTarget(HttpMethod method, Span`1 target)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.OnStartLine(HttpVersionAndMethod versionAndMethod, TargetOffsetPathLength targetPath, Span`1 startLine)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseRequestLine(TRequestHandler handler, ReadOnlySpan`1 requestLine)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpParser`1.ParseRequestLine(TRequestHandler handler, SequenceReader`1& reader)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TakeStartLine(SequenceReader`1& reader)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.ParseRequest(SequenceReader`1& reader)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TryParseRequest(ReadResult result, Boolean& endConnection)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
```

**Comment by xljiulang** [comment]
HttpCharacters.cs，Missing domain name separator `-`
```
        private static bool[] InitializeAuthority()
        {
            // Authority https://tools.ietf.org/html/rfc3986#section-3.2
            // Examples:
            // microsoft.com
            // hostname:8080
            // [::]:8080
            // [fe80::]
            // 127.0.0.1
            // user@host.com
            // user:password@host.com
            var authority = new bool[_tableSize];
            Array.Copy(_alphaNumeric, authority, _tableSize);
            authority[':'] = true;
            authority['.'] = true;
            authority['['] = true;
            authority[']'] = true;
            authority['@'] = true;
            return authority;
        }
```

**Comment by Tratcher** [comment]
Agreed. Do you want to submit a fix?

**Comment by xljiulang** [comment]
@Tratcher No, thank you
