### ISSUE TITLE
Data protection stack: SetApplicationName is not enough to share payload between two apps

### ISSUE THREAD

**Issue by bugproof** [dotnet/aspnetcore#3773]
Original issue: https://github.com/aspnet/Docs/issues/9354

I've set the same value in two apps and I can't decrypt it in the other app:

```
Unhandled Exception: System.Security.Cryptography.CryptographicException: The provided payload cannot be decrypted because it was not protected with this protection provider.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
```

I suspect it's because maybe I have a different version of a NuGet package but I don't know the exact details and documentation doesn't tell anything about that.

Console app:

```csharp
services.AddDataProtection()
    .SetApplicationName("test")
    .PersistKeysToFileSystem(new DirectoryInfo(@"c:\keys"));
```

Web app:

```csharp
services.AddDataProtection()
    .SetApplicationName("test")
    .PersistKeysToFileSystem(new DirectoryInfo(@"c:\keys"));
```

The name of the purpose is the same.

**Comment by blowdart** [comment]
You're probably right. newer versions of the package will understand older versions, but not vice versa. What versions are you using, and which is throwing the error?

**Comment by Sigvaard** [comment]
Console project:
![image](https://user-images.githubusercontent.com/3116731/47790465-85963480-dd17-11e8-95de-a8579e118303.png)

ASP.NET Core project:
![image](https://user-images.githubusercontent.com/3116731/47790509-a8284d80-dd17-11e8-8b7f-d704d6e81219.png)

I'm not sure if the ASP.NET core project pulls the same version though.

**Comment by blowdart** [comment]
It looks like it's pulling in 2.1.1 in both, so it *should* work.

**Comment by blowdart** [comment]
OK, I've tried this, and as trite and unhelpful as it is, works on my machine. I used an MVC app to protect, and the command line to unprotect.

In the asp.net startup I have

```
services.AddDataProtection()
    .PersistKeysToFileSystem(new DirectoryInfo(@"c:\keys"))
    .SetApplicationName("staticAppName");
```

The controller pieces are like this,

```
    public class HomeController : Controller
    {
        IDataProtector _dataProtector;

        public HomeController(IDataProtectionProvider provider)
        {
            _dataProtector = provider.CreateProtector("IHaveNoRealPurposeInLife");
        }

        public IActionResult Index()
        {
            return View(new HomeViewModel());
        }

        [HttpPost]
        public IActionResult Index(HomeViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            model.ProtectedData = _dataProtector.Protect(model.Input);
            return View(model);
        }
```

Then the command line;

```
using System;
using System.IO;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.Extensions.DependencyInjection;

namespace UnprotectCommandLine
{
    class Program
    {
        static void Main(string[] args)
        {
            var serviceCollection = new ServiceCollection();
            serviceCollection.AddDataProtection()
                .PersistKeysToFileSystem(new DirectoryInfo(@"c:\keys"))
                .SetApplicationName("staticAppName");

            var services = serviceCollection.BuildServiceProvider();


            Console.Write("Enter cipher text: ");
            string input = Console.ReadLine();

            var instance = ActivatorUtilities.CreateInstance<DIWrapper>(services);
            string plainText = instance.Unprotect(input);

            Console.WriteLine($"Unprotect returned: {plainText}");

            Console.ReadLine();
        }

        public class DIWrapper
        {
            IDataProtector _protector;

            // the 'provider' parameter is provided by DI
            public DIWrapper(IDataProtectionProvider provider)
            {
                _protector = provider.CreateProtector("IHaveNoRealPurposeInLife");
            }

            public string Unprotect(string cipherText)
            {
                // protect the payload
                string plainText = _protector.Unprotect(cipherText);
                return plainText;
            }
        }
    }
}
```

So, what's different here from what you have?

**Comment by HaoK** [comment]
@blowdart this is really old, safe to close out?

**Comment by blowdart** [comment]
Closing as no repo
