### ISSUE TITLE
Flaky Test: Timeout for RequestTests.ConnectionClosedTokenFiresOnServerFIN(listenOptionsName: "Loopback")

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#37750]
## Failing Test(s)

- Microsoft.AspNetCore.Server.Kestrel.Libuv.FunctionalTests.RequestTests.ConnectionClosedTokenFiresOnServerFIN(listenOptionsName: "Loopback")

## Error Message

```text
System.TimeoutException : The operation has timed out.
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 143
   at Microsoft.AspNetCore.Server.Kestrel.Libuv.FunctionalTests.RequestTests.ConnectionClosedTokenFiresOnServerFIN(String listenOptionsName) in /_/src/Servers/Kestrel/test/FunctionalTests/RequestTests.cs:line 590
   at Microsoft.AspNetCore.Server.Kestrel.Libuv.FunctionalTests.RequestTests.ConnectionClosedTokenFiresOnServerFIN(String listenOptionsName) in /_/src/Servers/Kestrel/test/FunctionalTests/RequestTests.cs:line 598
--- End of stack trace from previous location ---

```
</details>

## Logs

<details>

[RequestTests_ConnectionClosedTokenFiresOnServerFIN-Loopback.log](https://github.com/dotnet/aspnetcore/files/7392236/RequestTests_ConnectionClosedTokenFiresOnServerFIN-Loopback.log)

</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1434585&view=ms.vss-test-web.build-test-results-tab&runId=41430686&resultId=117917&paneView=debug

**Comment by Tratcher** [comment]
This appears to be libuv specific and libuv has now been removed. Ready for unquarantine.
