### ISSUE TITLE
System.NullReferenceException while HttpContextAccessor.HttpContext?.TraceIdentifier

### ISSUE THREAD

**Issue by lindexi** [dotnet/aspnetcore#37921]
### Describe the bug

I'm logging message with the trace identifier which from `HttpContextAccessor.HttpContext.TraceIdentifier` 

But the `HttpContextAccessor.HttpContext.TraceIdentifier` throw System.NullReferenceException with the StackTrace.

```
   at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.UpdateCached[TFeature,TState](TFeature& cached, TState state, Func`2 factory, Int32 revision, Boolean flush)
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_TraceIdentifier()
```

### Exceptions (if any)

```
System.NullReferenceException

Message: Object reference not set to an instance of an object.

StackTrace:    at Microsoft.AspNetCore.Http.Features.FeatureReferences`1.UpdateCached[TFeature,TState](TFeature& cached, TState state, Func`2 factory, Int32 revision, Boolean flush)
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_TraceIdentifier()
```

### Further technical details
- ASP.NET Core version: 3.1
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version:
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (反映任何 global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 6.0.0-preview.1.21102.12
  Commit:  9b2776d481

.NET SDKs installed:
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.1.21103.13 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.1.21103.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.1.21102.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.1.21103.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

</details>

**Comment by lindexi** [comment]
Thank you, @davidfowl  

What logging framework are you using? No.

**Comment by adityamandaleeka** [comment]
@lindexi This doc may be helpful to you: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0#automatically-log-scope-with-spanid-traceid-and-parentid

**Comment by adityamandaleeka** [comment]
@lindexi is your question answered?

**Comment by lindexi** [comment]
> @lindexi is your question answered?

Thank you, and I do not think it should throw the NullReferenceException.

**Comment by davidfowl** [comment]
> Thank you, and I do not think it should throw the NullReferenceException.

It's throwing because of misuse. Of course it shouldn't throw a null reference but we can't pin point the issue without a better stack trace.
