### ISSUE TITLE
BrowserRefreshServer.WaitForClientConnectionAsync

### ISSUE THREAD

**Issue by qcjxberin** [dotnet/aspnetcore#37974]
I use 6.0 rc2.

Unhandled exception. System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.DotNet.Watcher.Tools.BrowserRefreshServer.WaitForClientConnectionAsync(CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.Tools.BlazorWebAssemblyDeltaApplier.<>c__DisplayClass6_0.<<GetApplyUpdateCapabilitiesAsync>g__GetApplyUpdateCapabilitiesCoreAsync|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Watcher.Tools.BlazorWebAssemblyHostedDeltaApplier.GetApplyUpdateCapabilitiesAsync(DotNetWatchContext context, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.Tools.CompilationWorkspaceProvider.CreateProject(TaskCompletionSource`1 taskCompletionSource, Task`1 hotReloadCapabilitiesTask, String projectPath, IReporter reporter, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__127_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

**Comment by TanayParikh** [comment]
Hello @qcjxberin, could you please provide a minimal public GitHub repro project to allow us to investigate this issue further?

**Comment by qcjxberin** [comment]
Because the current project involves many unopened content, it cannot be minimized, but it has been tested many times before, sometimes it is necessary to clean up the project, sometimes it is necessary to regenerate the reference, etc., so there is no such error message, but as the following The project is getting bigger and bigger, and this error message always exists.

**Comment by qcjxberin** [comment]
The current latest is to display File Changed, and then it has been stuck without hot update.

**Comment by qcjxberin** [comment]
Is it related to the use of SignalR in the system, is there a conflict, or is it the use of Kestrel?

**Comment by qcjxberin** [comment]
StreamJsonRpc.RemoteInvocationException: 解决方案不包含指定的文档。
   在 StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__139`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Threading.Tasks.ValueTask`1.get_Result()
   在 Microsoft.CodeAnalysis.Remote.BrokeredServiceConnection`1.<TryInvokeAsync>d__20`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
RPC server exception:
System.InvalidOperationException: 解决方案不包含指定的文档。
      在 Microsoft.CodeAnalysis.Shared.Extensions.ISolutionExtensions.<GetRequiredDocumentAsync>d__9.MoveNext()
   --- 引发异常的上一位置中堆栈跟踪的末尾 ---
      在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      在 Microsoft.CodeAnalysis.EditAndContinue.RemoteEditAndContinueService.<>c__DisplayClass9_0.<<GetDocumentDiagnosticsAsync>b__0>d.MoveNext()
   --- 引发异常的上一位置中堆栈跟踪的末尾 ---
      在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      在 System.Threading.Tasks.ValueTask`1.get_Result()
      在 Microsoft.CodeAnalysis.Remote.BrokeredServiceBase.<RunServiceImplAsync>d__13`1.MoveNext()
   --- 引发异常的上一位置中堆栈跟踪的末尾 ---
      在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
      在 Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by qcjxberin** [comment]
The current test may be related to ResponseCompression   @TanayParikh

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not part of the runtime feature-set. Please use the [VS Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019) to report this issue, so the team who owns the area can track the ask.

**Comment by rblanca** [comment]
I confirmed this bug on VS 2022 - Net 6.0 release .... also if you disable response compression works as intended.

To Reproduce:

1) Create a Blazor WASM - Netcore Hosted project
2) Add response compression to your project
3) run with dotnet watch
4) Modifie some page on the blazor wasm project and save it to trigger the hot reload
6) You will see that it doesn't refresh anything and when you press Ctrl+C you will have


`Shutdown requested. Press Ctrl+C again to force exit.
Unhandled exception. System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.DotNet.Watcher.Tools.BrowserRefreshServer.WaitForClientConnectionAsync(CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.Tools.BlazorWebAssemblyDeltaApplier.<>c__DisplayClass6_0.<<GetApplyUpdateCapabilitiesAsync>g__GetApplyUpdateCapabilitiesCoreAsync|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Watcher.Tools.BlazorWebAssemblyHostedDeltaApplier.GetApplyUpdateCapabilitiesAsync(DotNetWatchContext context, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.Tools.CompilationWorkspaceProvider.CreateProject(TaskCompletionSource`1 taskCompletionSource, Task`1 hotReloadCapabilitiesTask, String projectPath, IReporter reporter, CancellationToken cancellationToken)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()`
