### ISSUE TITLE
POST_ClientCancellationBidirectional_RequestAbortRaised(protocol: Http2) test failure

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#38008]
## Failing Test(s)

Interop.FunctionalTests.Http3.Http3RequestTests.POST_ClientCancellationBidirectional_RequestAbortRaised(protocol: Http2)

## Error Message

```text
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.IO.IOException : The request was aborted.
-------- System.IO.IOException : The decryption operation failed, see inner exception.
------------ System.ComponentModel.Win32Exception : The specified data could not be decrypted.
```

## Stacktrace

<details>

```text
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 90
   at Interop.FunctionalTests.Http3.Http3RequestTests.POST_ClientCancellationBidirectional_RequestAbortRaised(HttpProtocols protocol) in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/Http3/Http3RequestTests.cs:line 698
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders()
   at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
----- Inner Stack Trace -----
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
----- Inner Stack Trace -----
```
</details>

## Logs

[Http3RequestTests_POST_ClientCancellationBidirectional_RequestAbortRaised-Http2.log](https://github.com/dotnet/aspnetcore/files/7457210/Http3RequestTests_POST_ClientCancellationBidirectional_RequestAbortRaised-Http2.log)

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1449703&view=ms.vss-test-web.build-test-results-tab&runId=41737516&resultId=106591&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by Tratcher** [comment]
@BrennanConroy @halter73 this seems similar to #37943, where the client is getting corrupted or truncated data but this time at the TLS layer.

**Comment by halter73** [comment]
This also looks identical to #37913 from six days ago.

**Comment by amcasey** [comment]
#37913 was dup'd against https://github.com/dotnet/aspnetcore/issues/35070.

**Comment by amcasey** [comment]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=818974
