### ISSUE TITLE
Not posible to get RequestTimedOut from Kestrel middleware.

### ISSUE THREAD

**Issue by mishasiv** [dotnet/aspnetcore#38053]
Kestrel web server has configurable option MinRequestBodyDataRate which is defaults to 240 bytes/seconds and 5 second grace period. 
In our project we used Kestrel and the next is Ocelot middleware. We faced a problem of  getting "404" Not found error to the attempt to upload image with our POST /api/v1/camera/upload-images. We have found that speed connection is very low and Kestrel detects it and generates BadHttpRequestException with:
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Reading the request body timed out due to data arriving too slowly. See MinRequestBodyDataRate.
That is Ok. When that condition is detected Kestrel set inernal RequestTimedOut from Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection  to true.
Incoming http request is then passed to the next Ocelot middleware. Exception is triggered when tried to parsing body request at Ocelot middleware.
Here are full trace log:
```
<html>
<body>
<!--StartFragment-->

2021-09-27 12:34:09.5966\|DEBUG\|Microsoft.AspNetCore.Server.Kestrel\|Connection id "0HMBTLQQ3QO93" completed keep alive response.
--
2021-09-27 15:34:09 | at Ocelot.Request.Mapper.RequestMapper.Map(HttpRequest request) errors found in ResponderMiddleware. Setting error response for request path:/api/v1/camera/upload-images, request method: POST
2021-09-27 15:34:09 | at Ocelot.Request.Mapper.RequestMapper.MapContent(HttpRequest request)
2021-09-27 15:34:09 | at Ocelot.Request.Mapper.RequestMapper.ToByteArray(Stream stream)
2021-09-27 15:34:09 | at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.CopyToAsyncInternal(Stream destination, CancellationToken cancellationToken)
2021-09-27 15:34:09 | at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
2021-09-27 15:34:09 | at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
2021-09-27 15:34:09 | 2021-09-27 12:34:09.5933\|WARN\|Ocelot.Responder.Middleware.ResponderMiddleware\|requestId: 0HMBTLQQ3QO93:00000001, previousRequestId: no previous request id, message: Error Code: UnmappableRequestError Message: Error when parsing incoming request, exception: Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Reading the request body timed out due to data arriving too slowly. See MinRequestBodyDataRate.
2021-09-27 15:34:09 | at Ocelot.Request.Mapper.RequestMapper.Map(HttpRequest request)
2021-09-27 15:34:09 | at Ocelot.Request.Mapper.RequestMapper.MapContent(HttpRequest request)
2021-09-27 15:34:09 | at Ocelot.Request.Mapper.RequestMapper.ToByteArray(Stream stream)
2021-09-27 15:34:09 | at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.CopyToAsyncInternal(Stream destination, CancellationToken cancellationToken)
2021-09-27 15:34:09 | at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.ReadAsyncInternal(CancellationToken cancellationToken)
2021-09-27 15:34:09 | at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
2021-09-27 15:34:09 | 2021-09-27 12:34:09.5933\|WARN\|Ocelot.Request.Middleware.DownstreamRequestInitialiserMiddleware\|requestId: 0HMBTLQQ3QO93:00000001, previousRequestId: no previous request id, message: Error when parsing incoming request, exception: Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Reading the request body timed out due to data arriving too slowly. See MinRequestBodyDataRate.
2021-09-27 15:34:09 | 2021-09-27 12:34:09.5933\|DEBUG\|Microsoft.AspNetCore.Server.Kestrel\|Connection id "0HMBTLQQ3QO93", Request id "0HMBTLQQ3QO93:00000001": the request timed out because it was not sent by the client at a minimum of 240 bytes/second.

<!--EndFragment-->
</body>
</html>
 ```
The problem is Kestrel doesn't provide open interface to RequestTimedOut flag to avidently get information about requestBody Timeout problem it`s detected. Ocelot gets exception only when try to read request body stream, instead of better way to just read RequestTimedOut flag from Kestrel middleware.
The proper way for pipeline processing is as soon as Kestrel detects the MinRequestBodyDataRate problem to break pipeline handle and return to user "408" Request Timeout error. We tried to add new middleware works after Kestrel and before Ocelot, in order to catch MinRequestBodyDataRate problem, but again go to the problem that we need to read Request body stream to get exception, but if no exception is thrown, request is passed to next Ocelot middleware where request body needs to be read again which goes to double read stream data and it is forbidden( finally failed with second read with {"errors":[{"code":"InvalidValue","message":"A non-empty request body is required."}]} ).

Our suggestion: Kestrel should provide open interface RequestTimedOut  for the next middleware to avidently detect  MinRequestBodyDataRate problem without reading request body stream.

**Comment by Tratcher** [comment]
> Incoming http request is then passed to the next Ocelot middleware. 

What component reads the request body and catches the exception? That component shouldn't call next if the request has already failed.

**Comment by mishasiv** [comment]
Hi Tratcher,

Please see my answer for your questions
> What component reads the request body and catches the exception? That component shouldn't call next if the request has already  failed
The problem is that when Kestrel detects MinRequestBodyDataRate condition it doesn't interrupt pipeline processing and return to the user. Instead of it, next middkeware which is Ocelot is invoked. Ocelot starts processing of request body stream and execption is thrown.
Code at Ocelot is src/Ocelot/request/Mapper/RequestMapper.cs function public async Task<Response<HttpRequestMessage>> Map(HttpRequest request, DownstreamRoute downstreamRoute) at  class RequestMapper.  There is try/catch block and UnmappableRequestError error is generated by the Ocelot. It is by default "404" error.
Exact line of the Ocelot code where crash is happens is line
await stream.CopyToAsync(memStream);
 at function private async Task<byte[]> ToByteArray(Stream stream)




>The one reading the request body is the one that needs to handle the exception and set the status code, or it should re-throw the exception and let the server handle it.
The one reading of request body needs to check/detect MinRequestBodyDataRate problem. It can be done either in the seperate moddleware between Kestrel and Ocelot or with PreErrorResponderMiddleware Ocelot option which allow make the same check/detect of MinRequestBodyDataRate. But then if no problem is detected Ocelot pipeline processing demands the second tim of request body reading which is not possible( leads to "A non-empty request body is required. as mentioned above")


>What error response does Ocelot set? It seems strange that it would set a 404 on catching an exception
Just to repeat that Ocelot setups 404 error status code( for UnmappableRequestError )  whicn is return to the user of the request.

The problem is easily reproduced and faulty scenario can be reproduced. I can provide some log data if needed. But at Ocelot level there is no any possibilities to get knowledge about MinRequestBodyDataRate except reading request body stream.

**Comment by mishasiv** [comment]
About mentioned StatusCode of aspnetcore/src/Http/Http.Abstractions/src/BadHttpRequestException.cs
I am not sure that it can be used in Ocelot middleware, at this level there is only Ocelot.Middleware.DownStreamContext is available which contains Microsoft.AspNetCore.Http.HttpRequest.
Maybe I don't understand on how to get StatusCode  of BadHttpRequestException at Ocelot middleware? If it is possible please give me hint how to extarct it and I will check what value contains StatusCode.

**Comment by mishasiv** [comment]
My aim is: to get MinRequestBodyDataRate problem as sonn as possible and return to user 408 error code.
possible solutions:
1) Kestrel does it itself( not in a real)
2) write a seperate middleware after Kestrel which will check/catch for MinRequestBodyDataRate  problem and return 408 to user without invoking next Ocelot and other middlewares.

**Comment by Tratcher** [comment]
There is no way to get the BadHttpRequestException without reading the request body and there are no plans to change that.

The consumer of the request body is the one that needs to handle any related exceptions. This should be raised with Ocelot. Do you have a reference for where in their code they consume the body?

**Comment by mishasiv** [comment]
Ocelot handle it, yes, but I would be more gracefull to have some flag in kestrel middlware which is available for read and telling true if MinRequestBodyDataRate was detected instead of getting exception on handling on other level. Problem can be becaus of very big size of reguest body size which will take much time and resouces for processing. Better to interrupt processing and return to user as soon as possible.
I know it is decision on Kestrel to have or not possibility to have flag, but it will be more powerful solution.

**Comment by Tratcher** [comment]
A large request body should not cause this error, only a slow one. Ocelot will fail as soon as kestrel detects the condition, there's nothing that would make that faster.

**Comment by impulsgraw** [comment]
@Tratcher , fairly that doesn't look feasible. Kestrel puts responsibility on dispatching a low-level exception onto *any* middleware working next to it.
Ocelot is not the only possible candidate for such middleware, and there is no appropriate warning/limitation in Kestrel docs for developers to mind handling such case in their code.
Moreover, this means the exception should be expected/caught *everywhere* in the app - we may just have our web-application code throwing in random places.

What is the purpose of passing the unfulfilled request to the next middleware? In case if the request body is no longer accepted on side of server, it's clearly cannot be correctly dispatched any further - we will never be able to handle the request without having it's full body, if we expect it.
Even if the endpoint dispatcher doesn't expect the body (GET), then that's the problem of the client, - the low rate interruption still takes place and I don't see any reason to hide this problem until someone demands the body explicitly.

**Comment by davidfowl** [comment]
Kestrel cannot read the entire body before your application runs (nor should it). Code reading the body needs to handle exceptions that can occur when reading the body, this is one of them.

**Comment by impulsgraw** [comment]
Okay, but the error is already detected before the body is being read and before the flow passes to the next middleware, isn't it? - Please correct me if I'm wrong.

**Comment by davidfowl** [comment]
The application is the one reading the body. The act of your calling ReadAsync is what triggers this
