### ISSUE TITLE
NullReferenceException coming from Razor compiler after upgrade of .NET SDK (without any change to .NET 5 project).

### ISSUE THREAD

**Issue by rwasef1830** [dotnet/aspnetcore#38194]
```
Object reference not set to an instance of an object.
     at Microsoft.AspNetCore.Razor.Language.TagHelperMatchingConventions.SatisfiesBoundAttributeName(StringSegment name, BoundAttributeDescriptor descriptor)
     at Microsoft.AspNetCore.Razor.Language.TagHelperMatchingConventions.CanSatisfyBoundAttribute(String name, BoundAttributeDescriptor descriptor)
     at Microsoft.AspNetCore.Razor.Language.TagHelperMatchingConventions.TryGetFirstBoundAttributeMatch(String name, TagHelperDescriptor descriptor, BoundAttributeDescriptor& boundAttribute, Boolean& indexerMatch, Boolean& parameterMatch, BoundAttributeParameterDescriptor& boundAttributeParameter)
     at Microsoft.AspNetCore.Razor.Language.Legacy.TagHelperBlockRewriter.CreateTryParseResult(String name, IEnumerable`1 descriptors, HashSet`1 processedBoundAttributeNames)
     at Microsoft.AspNetCore.Razor.Language.Legacy.TagHelperBlockRewriter.TryParseAttribute(String tagName, MarkupAttributeBlockSyntax attributeBlock, IEnumerable`1 descriptors, ErrorSink errorSink, HashSet`1 processedBoundAttributeNames)
     at Microsoft.AspNetCore.Razor.Language.Legacy.TagHelperBlockRewriter.Rewrite(String tagName, RazorParserFeatureFlags featureFlags, MarkupStartTagSyntax startTag, TagHelperBinding bindingResult, ErrorSink errorSink, RazorSourceDocument source)
     at Microsoft.AspNetCore.Razor.Language.Legacy.TagHelperParseTreeRewriter.Rewriter.TryRewriteTagHelperStart(MarkupStartTagSyntax startTag, MarkupEndTagSyntax endTag, MarkupTagHelperStartTagSyntax& rewritten, TagHelperInfo& tagHelperInfo)
     at Microsoft.AspNetCore.Razor.Language.Legacy.TagHelperParseTreeRewriter.Rewriter.VisitMarkupElement(MarkupElementSyntax node)
     at Microsoft.AspNetCore.Razor.Language.Syntax.MarkupElementSyntax.Accept[TResult](SyntaxVisitor`1 visitor)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.Visit(SyntaxNode node)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitListElement[TNode](TNode node)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitList[TNode](SyntaxList`1 list)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitMarkupBlock(MarkupBlockSyntax node)
     at Microsoft.AspNetCore.Razor.Language.Syntax.MarkupBlockSyntax.Accept[TResult](SyntaxVisitor`1 visitor)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.Visit(SyntaxNode node)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.VisitRazorDocument(RazorDocumentSyntax node)
     at Microsoft.AspNetCore.Razor.Language.Syntax.RazorDocumentSyntax.Accept[TResult](SyntaxVisitor`1 visitor)
     at Microsoft.AspNetCore.Razor.Language.Syntax.SyntaxRewriter.Visit(SyntaxNode node)
     at Microsoft.AspNetCore.Razor.Language.Legacy.TagHelperParseTreeRewriter.Rewrite(RazorSyntaxTree syntaxTree, String tagHelperPrefix, IEnumerable`1 descriptors)
     at Microsoft.AspNetCore.Razor.Language.DefaultRazorTagHelperBinderPhase.ExecuteCore(RazorCodeDocument codeDocument)
     at Microsoft.AspNetCore.Razor.Language.RazorEnginePhaseBase.Execute(RazorCodeDocument codeDocument)
     at Microsoft.AspNetCore.Razor.Language.DefaultRazorEngine.Process(RazorCodeDocument document)
     at Microsoft.AspNetCore.Razor.Language.DefaultRazorProjectEngine.ProcessCore(RazorCodeDocument codeDocument)
     at Microsoft.AspNetCore.Razor.Language.RazorProjectEngine.Process(RazorProjectItem projectItem)
     at Microsoft.NET.Sdk.Razor.Tool.GenerateCommand.<>c__DisplayClass55_0.<GenerateCode>b__0(Int32 i)
     at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
  --- End of stack trace from previous location ---
     at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
     at System.Threading.Tasks.TaskReplicator.Replica.Execute()
C:\Program Files\dotnet\sdk\6.0.100\Sdks\Microsoft.NET.Sdk.Razor\targets\Microsoft.NET.Sdk.Razor.CodeGeneration.targets(150,5): error : rzc generate exited with code 1.
```

I will try to make a minimal repro, but this is a large project with many tag helpers. I hope the stack trace is enough to provide any clues until I can make the repro project.

**Comment by TanayParikh** [comment]
Looks like a bull BoundAttributeDescriptor. I believe this is an issue we may have seen before (cc/ @pranavkm). 

Code is here:
https://github.com/dotnet/aspnetcore/blob/main/src/Razor/Microsoft.AspNetCore.Razor.Language/src/TagHelperMatchingConventions.cs#L221-L224

**Comment by rwasef1830** [comment]
@TanayParikh here is a minimized repro

```cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.TagHelpers;
using Microsoft.AspNetCore.Razor.TagHelpers;

namespace Is.There.Any.Regression.Testing
{
    [HtmlTargetElement("field")]
    public class FieldTagHelper : TagHelper
    {
        public IDictionary<string, object>? FieldAttributes { get; }
    }
    
    // Commenting out this class will allow compilation to work.
    [HtmlTargetElement("display")]
    public class DisplayTagHelper : FieldTagHelper
    {
    }
}
```

**Comment by rwasef1830** [comment]
Is there any workaround other than modifying my code ?

**Comment by pranavkm** [comment]
@rwasef1830 a workaround until we resolve this issue would be to use a [global.json file to pin to a 5.0 SDK](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json). 

e.g.

```json
{
  "sdk": {
    "version": "5.0.12" // Change this to a 5.0 SDK that you have installed.
  }
}
```
