### ISSUE TITLE
Net Core 6.0  ERR Error running script

### ISSUE THREAD

**Issue by YongChingShieh** [dotnet/aspnetcore#38254]
### Describe the bug
StackExchange.Redis.RedisServerException: ERR Error running script (call to f_3915ee22fda531a1d5661f2523d0443fd35ff0a4):  

### To Reproduce
```
 builder.Services.AddStackExchangeRedisCache(options =>
{
//options.ProfilingSession = () => new ProfilingSession();
options.Configuration = RedisConn;
options.InstanceName = "SampleInstance";// InstanceName;
});
public LoginController(IDistributedCache distributedCache)
{
Cache = distributedCache;

}
public void Test()
{
Cache.SetString(Key, "123");
}
```

### Exceptions (if any)
 
StackExchange.Redis.RedisServerException: ERR Error running script (call to f_3915ee22fda531a1d5661f2523d0443fd35ff0a4): @user_script:2: @user_script: 2: Wrong number of args calling Redis command From Lua script
at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2815 at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor1 processor, ServerEndPoint server) in //src/StackExchange.Redis/RedisBase.cs:line 54
at StackExchange.Redis.RedisDatabase.ScriptEvaluate(String script, RedisKey[] keys, RedisValue[] values, CommandFlags flags) in //src/StackExchange.Redis/RedisDatabase.cs:line 1189
at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.Set(String key, Byte[] value, DistributedCacheEntryOptions options)
at Microsoft.Extensions.Caching.Distributed.DistributedCacheExtensions.SetString(IDistributedCache cache, String key, String value, DistributedCacheEntryOptions options)
at Microsoft.Extensions.Caching.Distributed.DistributedCacheExtensions.SetString(IDistributedCache cache, String key, String value)
 

### Further technical details
- ASP.NET Core version:6.0.0
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version:
- Include the output of `dotnet --info`:

<details>
  .NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  5.0.301 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

```

```

</details>

**Comment by osisdie** [comment]
Same here after upgrading to 6.0.0 package
```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="6.0.0" />
  </ItemGroup>
```

Sample code
```cs
await _cache.SetStringAsync(realKey, stringValue, new DistributedCacheEntryOptions
{
    AbsoluteExpiration = DateTime.UtcNow.AddSeconds(5)
});
```

Exceptions
$exception.Message
```
The absolute expiration value must be in the future. (Parameter 'AbsoluteExpiration')
Actual value was 11/10/2021 5:31:35 PM +00:00.
```

$exception.StackTrace
```
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.GetAbsoluteExpiration(DateTimeOffset creationTime, DistributedCacheEntryOptions options)
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.<SetAsync>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
```

**Comment by adityamandaleeka** [comment]
@osisdie Can you please file a new issue for yours? It seems to be a different problem than the original issue reported here.

@YongChingShieh Can you share what Redis version you're using? Sounds like there might be some incompatibility.

**Comment by grace18168** [comment]
@**adityamandaleeka**  I am also having the same Redis ERR Error running script problem. The Redis version I'm using right now is **3.2.100** from microsoftarchive/redis/releases.

**Comment by grace18168** [comment]
@**adityamandaleeka** After upgrading from Redis 3.2.100 to 5.0.14(tporadowski/redis/releases) the issue was resolved. It was a compatibility issue with Redis. Thanks for your answer.

**Comment by YongChingShieh** [comment]
> @osisdie Can you please file a new issue for yours? It seems to be a different problem than the original issue reported here.
> 
> @YongChingShieh Can you share what Redis version you're using? Sounds like there might be some incompatibility.

upgrading from Redis   5.0.14(tporadowski/redis/releases) the issue was resolved. Thanks

**Comment by osisdie** [comment]
> @osisdie Can you please file a new issue for yours? It seems to be a different problem than the original issue reported here.
> 
> @YongChingShieh Can you share what Redis version you're using? Sounds like there might be some incompatibility.

@adityamandaleeka Please just reference the error message from @YongChingShieh , I actually got the same as his, just curious what extra info could see and got mine by VS Debug mode. Again, they're actually the same no matter runs by a netcore application or an xunit testcase.

Btw, downgrade will work as the other authors mentioned.
