### ISSUE TITLE
Quarantine StartupTests.ExpandEnvironmentVariableInWebConfig

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#38260]
## Failing Test(s)

- Microsoft.AspNetCore.Server.IIS.NewHandler.FunctionalTests.StartupTests.ExpandEnvironmentVariableInWebConfig

## Error Message

```text
System.Threading.Tasks.TaskCanceledException : The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
---- System.TimeoutException : The operation was canceled.
-------- System.Threading.Tasks.TaskCanceledException : The operation was canceled.
------------ System.IO.IOException : Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
---------------- System.Net.Sockets.SocketException : The I/O operation has been aborted because of either a thread exit or an application request.
```

## Stacktrace

<details>

```text
at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.Helpers.AssertStarts(IISDeploymentResult deploymentResult, String path) in /_/src/Servers/IIS/IIS/test/Common.FunctionalTests/Infrastructure/Helpers.cs:line 32
   at Microsoft.AspNetCore.Server.IntegrationTesting.FunctionalTestsBase.StartAsync(IISDeploymentParameters parameters) in /_/src/Servers/IIS/IIS/test/Common.FunctionalTests/Infrastructure/FunctionalTestsBase.cs:line 45
   at Microsoft.AspNetCore.Server.IIS.NewHandler.FunctionalTests.StartupTests.ExpandEnvironmentVariableInWebConfig() in /_/src/Servers/IIS/IIS/test/Common.FunctionalTests/StartupTests.cs:line 58
--- End of stack trace from previous location ---
----- Inner Stack Trace -----

----- Inner Stack Trace -----
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.LoggingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/LoggingHandler.cs:line 33
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
----- Inner Stack Trace -----
```
</details>

## Logs

<details>

[StartupTests_ExpandEnvironmentVariableInWebConfig.log](https://github.com/dotnet/aspnetcore/files/7514319/StartupTests_ExpandEnvironmentVariableInWebConfig.log)

</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1462207&view=ms.vss-test-web.build-test-results-tab&runId=42012950&resultId=121854&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by HaoK** [comment]
https://github.com/dotnet/aspnetcore/pull/40884 ups the timeouts for a lot of these kinds of timeouts
