### ISSUE TITLE
Component E2E test failure in Ubuntu

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#38613]
Tests:
- Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.ServerJSRootComponentsTest.CanAddAndDisposeRootComponents
- Microsoft.AspNetCore.Components.E2ETest.Tests.JSRootComponentsTest.CanAddAndDisposeRootComponents

https://dev.azure.com/dnceng/public/_build/results?buildId=1487604&view=ms.vss-test-web.build-test-results-tab&runId=42535622&resultId=100740&paneView=debug

System.InvalidCastException : Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]' to type 'OpenQA.Selenium.IWebElement'.

```C#
Stack trace
   at Microsoft.AspNetCore.Components.E2ETest.Tests.JSRootComponentsTest.GetShadowRoot(IWebElement element) in /home/vsts/work/1/s/src/Components/test/E2ETest/Tests/JSRootComponentsTest.cs:line 281
   at Microsoft.AspNetCore.Components.E2ETest.Tests.JSRootComponentsTest.CanAddAndDisposeRootComponents(Boolean intoBlazorUi, Boolean attachShadowRoot) in /home/vsts/work/1/s/src/Components/test/E2ETest/Tests/JSRootComponentsTest.cs:line 57
```

Failing build: https://dev.azure.com/dnceng/public/_build/results?buildId=1482803&view=results

**Comment by TanayParikh** [comment]
Noooooo, there goes the 100% pass rate! 😄

**Comment by SteveSandersonMS** [comment]
> Noooooo, there goes the 100% pass rate! 😄

Just to make us feel better, this failure appears to be due to a breaking API change in Selenium, not due to our production or test code being flaky. Working on fixing it now.
