### ISSUE TITLE
Dotnet watch throws exception

### ISSUE THREAD

**Issue by JohanPetersson** [dotnet/aspnetcore#38719]
Not sure this is the the right place for this issue. Please let me know if I should create this issue elsewhere.

### Describe the Bug

When using `dotnet watch` the file polling throws following exception:

```
watch : Polling file watcher is enabled
watch : Started
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: /src/Startup.cs
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Microsoft.DotNet.Watcher.Internal.PollingFileWatcher.<CheckForChangedFiles>b__23_0(FileSystemInfo f)
   at Microsoft.DotNet.Watcher.Internal.PollingFileWatcher.ForeachEntityInDirectory(DirectoryInfo dirInfo, Action`1 fileAction)
   at Microsoft.DotNet.Watcher.Internal.PollingFileWatcher.CheckForChangedFiles()
   at Microsoft.DotNet.Watcher.Internal.PollingFileWatcher.PollingLoop()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

### Steps to Reproduce

```bash
dotnet new web -f net5.0
```

Add [Directory.Build.props](https://github.com/dotnet/dotnet-docker/blob/main/samples/Directory.Build.props) to move `bin` and `obj`. The bug is however reproducible without this.

Make sure bin and obj are empty.

(on Windows)
```bash
docker run --rm -it -p 5000:80 -v ${pwd}:/src -w /src -e ASPNETCORE_URLS=http://+:80 -e ASPNETCORE_ENVIRONMENT=Development mcr.microsoft.com/dotnet/sdk:5.0 dotnet watch run --no-launch-profile
```

### Other Information

This only happens when the project hasn't been built yet. If I start the container with just `dotnet run` once, shut down the container, and then change back to `dotnet watch run` as entrypoint, it works.

This is not reproducible with .NET 6, but I'm not able to upgrade yet, so wondering if there is a workaround to get this to work until then.  Edit: I re-tested with .NET 6 and now I'm getting the same issue, so I probably missed clearing bin and obj last time I tested.

### Output of `docker version`

20.10.10, build b485636

### Output of `docker info`
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.3)
  compose: Docker Compose (Docker Inc., v2.1.1)
  scan: Docker Scan (Docker Inc., 0.9.0)

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 15
 Server Version: 20.10.10
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.60.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 12.42GiB
 Name: docker-desktop
 ID: IJEP:3W6Y:PWQF:KZOW:UBLU:PCJG:WOQ4:P2NB:B2ZP:TPMR:4PTD:BERP
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by mthalman** [comment]
Transferred to aspnetcore which owns `dotnet-watch`.

**Comment by JohanPetersson** [comment]
Any updates on this issue?

**Comment by Jawz84** [comment]
I have issues with this as well. When using a development container, I can't use `dotnet watch` reliably. 
Related: https://github.com/docker/for-win/issues/8749

**Comment by DianaKoenraadt** [comment]
Same problem here. Intermittently, I get the "An item with the same key has already been added" error. This would not be so bad if only I knew what it requires of me to fix it.

**Comment by mkArtakMSFT** [comment]
@tmat could you please look into this? Thanks!

**Comment by tmat** [comment]
I can't reproduce it but I see a couple potential issues with the current implementation. Fixing in https://github.com/dotnet/sdk/pull/35712

**Comment by Volkmire** [comment]
@tmat I have similar issue
```
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: /src/solution/sharedLibrary/obj/rider.project.restore.info
at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
at Microsoft.DotNet.Watcher.Internal.PollingFileWatcher.<CheckForChangedFiles>b__23_0(FileSystemInfo f)
at Microsoft.DotNet.Watcher.Internal.PollingFileWatcher.ForeachEntityInDirectory(DirectoryInfo dirInfo, Action`1 fileAction)
at Microsoft.DotNet.Watcher.Internal.PollingFileWatcher.ForeachEntityInDirectory(DirectoryInfo dirInfo, Action`1 fileAction)
at Microsoft.DotNet.Watcher.Internal.PollingFileWatcher.CheckForChangedFiles()
at Microsoft.DotNet.Watcher.Internal.PollingFileWatcher.PollingLoop()
```

I'm using a docker compose where service is defined something like this:
``` yaml
settings-api:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    working_dir: /src/path/to/project
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "dotnet watch run --packages /src/.packages/ --urls http://+:80"
    ports:
      - "10101:80"
    environment: []
    volumes:
      - ${PWD}:/src
    depends_on:
      rabbitmq:
        condition: service_healthy
```

Note that I mount my whole repository as a volume and exception seems to be triggered by shared dependency.
I've also tried to change entrypoint script to `dotnet build .... && dotnet watch run ...`, thinking to walk around of what @JohanPetersson mentioned about having empty /bin /obj directories. This did not run either.

The only setup that did run was `dotnet build && dotnet watch run --no-build --no-restore ...`, but it is obviously pointless, since watch does not rebuild sources on change. But it also probably means that the issue is somehow related to the build phase in dotnet watch command.

**Comment by Davane** [comment]
@Volkmire I had a similar issue and I found this article https://medium.com/@saadjaved120/hot-reload-dotnet-application-in-docker-using-dotnet-watch-c41662c73104. I hope this can help you and others. 

Based on the article, I think you might need to update your volumes and add these (Just replace the `ProjectName` with yours):

```yml
...
volumes:
      - ./:/app
      # After adding the below lines the problem went away for me
      - /app/obj/ # <- directory won't be mounted
      - /app/bin/ # <- directory won't be mounted
      - /app/ProjectName.API/obj/ # <- directory won't be mounted
      - /app/ProjectName.API/bin/ # <- directory won't be mounted
```

**Comment by timdinh-grex** [comment]
We get the same exception **without** using docker container, however, we noticed that we get this exception when we ran 2 instances of dotnet watch on our solution. i.e we do `dotnet watch api` and another `dotnet watch web`

If we ran `dotnet watch api` first then `dotnet watch web`, the api will get an error message `dotnet watch ⌚ [Ais.Api (net9.0)] Exited`

If we ran `dotnet watch web` follow by `dotnet watch api`, the web will get an error message `dotnet watch ⌚ [Ais.Api (net9.0)] Exited`

Once the **Exited** message is received, it will refused to receive any more changes and if you press CTRL+C to exit, you will see the error
```
dotnet watch ❌ System.ArgumentException: An item with the same key has already been added. Key: /Users/timdinh/Projects/abc/api/api.csproj
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Microsoft.DotNet.Watch.IncrementalMSBuildWorkspace.UpdateProjectConeAsync(String rootProjectPath, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watch.HotReloadDotNetWatcher.<>c__DisplayClass5_2.<<WatchAsync>g__CaptureChangedFilesSnapshot|7>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Watch.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watch.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watch.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watch.Program.RunAsync()
```

Our environment are: dotnet 9 sdk, macOS 15.2
