### ISSUE TITLE
Quarantine LogsStartupExceptionExitError

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#38732]
## Failing Test(s)

- Microsoft.AspNetCore.Server.IIS.NewShim.FunctionalTests.StartupTests.LogsStartupExceptionExitError

## Error Message

```text
System.AggregateException : Operation did not succeed after 15 retries (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet) (WorkerProcess not stopped yet)
---- System.InvalidOperationException : WorkerProcess not stopped yet
---- System.InvalidOperationException : WorkerProcess not stopped yet
---- System.InvalidOperationException : WorkerProcess not stopped yet
---- System.InvalidOperationException : WorkerProcess not stopped yet
---- System.InvalidOperationException : WorkerProcess not stopped yet
---- System.InvalidOperationException : WorkerProcess not stopped yet
---- System.InvalidOperationException : WorkerProcess not stopped yet
---- System.InvalidOperationException : WorkerProcess not stopped yet
---- System.InvalidOperationException : WorkerProcess not stopped yet
---- System.InvalidOperationException : WorkerProcess not stopped yet
---- System.InvalidOperationException : WorkerProcess not stopped yet
---- System.InvalidOperationException : WorkerProcess not stopped yet
---- System.InvalidOperationException : WorkerProcess not stopped yet
---- System.InvalidOperationException : WorkerProcess not stopped yet
---- System.InvalidOperationException : WorkerProcess not stopped yet
```

## Stacktrace

<details>

```text
 at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 482
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.Stop() in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 447
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.Dispose(Boolean gracefulShutdown) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 72
   at Microsoft.AspNetCore.Server.IntegrationTesting.FunctionalTestsBase.StopServer(Boolean gracefulShutdown) in /_/src/Servers/IIS/IIS/test/Common.FunctionalTests/Infrastructure/FunctionalTestsBase.cs:line 64
   at Microsoft.AspNetCore.Server.IIS.NewShim.FunctionalTests.StartupTests.LogsStartupExceptionExitError() in /_/src/Servers/IIS/IIS/test/Common.LongTests/StartupTests.cs:line 258
--- End of stack trace from previous location ---
----- Inner Stack Trace #1 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<Stop>b__25_0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 428
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 462
----- Inner Stack Trace #2 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<Stop>b__25_0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 428
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 462
----- Inner Stack Trace #3 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<Stop>b__25_0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 428
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 462
----- Inner Stack Trace #4 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<Stop>b__25_0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 428
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 462
----- Inner Stack Trace #5 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<Stop>b__25_0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 428
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 462
----- Inner Stack Trace #6 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<Stop>b__25_0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 428
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 462
----- Inner Stack Trace #7 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<Stop>b__25_0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 428
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:li
```
</details>

## Logs

<details>

[StartupTests_LogsStartupExceptionExitError.log](https://github.com/dotnet/aspnetcore/files/7628934/StartupTests_LogsStartupExceptionExitError.log)

</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1490937&view=ms.vss-test-web.build-test-results-tab&runId=42609950&resultId=122159&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by HaoK** [comment]
https://github.com/dotnet/aspnetcore/pull/40884 ups the timeouts for a lot of these kinds of timeouts
