### ISSUE TITLE
InputCheckbox generates "IndexOutOfRangeException" exceptions when bound to an array element in a for loop

### ISSUE THREAD

**Issue by Dargazo** [dotnet/aspnetcore#38750]
### Describe the bug
In Blazor WebAssembly:
InputCheckbox generates "IndexOutOfRangeException" exceptions when bound to an array element in a for loop.

This does not happen if a foreach loop is used, or the elements are referenced 'manually' by hard-coding the indices

"Unhandled exception rendering component: Index was outside the bounds of the array.
System.IndexOutOfRangeException: Index was outside the bounds of the array."

### To Reproduce
Create a new Blazor WASM project (hosting model does not matter)
Replace the in the Index.razor file code with:

```razor
@page "/"

<PageTitle>Index</PageTitle>

<h1>Hello, world!</h1>

Welcome to your new app.

<SurveyPrompt Title="How is Blazor working for you?" />

<EditForm Model=MyArray>
    @if(MyArray is not null)
    {
    @*    <p> For each loop </p>
        <p>
        
            @foreach (var item in MyArray)
            {
               <InputCheckbox @bind-Value=item.Value /> @(MyIndex++.ToString("D2"))
            }
        </p>*@

        <p> For loop </p>
        <p>@for (var i = 0; i < MyArray.Length ; i++)
            {
                <InputCheckbox @bind-Value=MyArray[i].Value /> @(i.ToString("D2"))
            }
        </p>

        
@*        <p> Manual </p>
        <p>
            <InputCheckbox @bind-Value=MyArray[0].Value /> @(0.ToString("D2"))
            <InputCheckbox @bind-Value=MyArray[1].Value /> @(1.ToString("D2"))
        </p>*@
    }
</EditForm>

@code {
    private BindingWrapper<bool>[] MyArray { get; set; } = new BindingWrapper<bool>[] { new(true), new(false) };
    int MyIndex { get; set; } = 0;

    private class BindingWrapper<T>
    {
        public BindingWrapper(T a_Val)
        {
            Value = a_Val;
        }

        public T Value { get; set; }
    }
}
```

And Run/ Debug the application.

### Exceptions (if any)

The following exception is logged `MyArray.Length` times in the Browser console (Edge) 
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Index was outside the bounds of the array.
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.AspNetCore.Components.Forms.FieldIdentifier.ParseAccessor[Boolean](Expression`1 accessor, Object& model, String& fieldName)
   at Microsoft.AspNetCore.Components.Forms.FieldIdentifier.Create[Boolean](Expression`1 accessor)
   at Microsoft.AspNetCore.Components.Forms.InputBase`1[[System.Boolean, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
```
### Screenshots 
Using the code posted above
![image](https://user-images.githubusercontent.com/20795309/144220872-c0c1b98b-6027-43c1-bcf7-fee6ac8696bd.png)
Commenting out the for(var ...) loop, and uncommenting the "Manual", and "For each loop" parts works as expected:
![image](https://user-images.githubusercontent.com/20795309/144221097-27990ce3-816e-4bad-8135-f50c6cd53eff.png)

### Further technical details
Running Visual Studio 2022 Version 17.0.1

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  5.0.403 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

```

</details>

**Comment by MariovanZeist** [comment]
This is a known issue when using a ``for`` loop in Blazor. 
The problem is not a Blazor specific problem, but generally known as the _"loop-variable-closure problem"_

You can fix it by introducing a local variable, like this
```CS
  <p>@for (var i = 0; i < MyArray.Length ; i++)
      {
          var x = i;      //Add variable here
          <InputCheckbox @bind-Value=MyArray[x].Value /> @(x.ToString("D2"))
      }
  </p>
```

**Comment by Dargazo** [comment]
> This is a known issue when using a `for` loop in Blazor. The problem is not a Blazor specific problem, but generally known as the _"loop-variable-closure problem"_
> 
> You can fix it by introducing a local variable, like this
> 
> ```cs
>   <p>@for (var i = 0; i < MyArray.Length ; i++)
>       {
>           var x = i;      //Add variable here
>           <InputCheckbox @bind-Value=MyArray[x].Value /> @(x.ToString("D2"))
>       }
>   </p>
> ```

Hi @MariovanZeist , thank you for your explanation and fix. The fix works.

I am trying to wrap my head around the root cause.

My understanding is that all InputCheckBox are effectively bound to MyArray[2] (The value of the i variable i = 2 at the end of the for loop, as MyArray.Length = 2) in the original code I posted, because of the loop-variable-closure problem.
This, to me, definitely explains, the exceptions thrown, and the amount of them. However, if we replace the MyArray initialization with:
`private BindingWrapper<bool>[] MyArray { get; set; } = new BindingWrapper<bool>[] { new(true), new(false), new(true), new(false), new(true), new(false) };`
Thus the array is a bit larger (6 elements in total), and the values alternate between true and false.

Now If we change the bound in the for loop to be: 
`for (var i = 0; i < MyArray.Length -1 ; i++) // notice the - 1`, 

I would expect 5 unchecked checkboxes (as MyArray[5].Value is false).
However, in this case The resulting 5 checkboxes are checked alternatingly. Sugesting ther are bound correctly.
![image](https://user-images.githubusercontent.com/20795309/144238106-6a3ad006-fed1-4e11-afc2-a6500e0a64cc.png)

So I think I am missing something here, but can't quite put my finger on it.

Though on the other hand, checking and unchecking the checkboxes only alters the last element value of the array (and does not update the checkbox layout...), which would make sense if they are bound to MyArray[5].Value, but the why am I seeing the checked/unchecked checkboxes?

**Comment by MariovanZeist** [comment]
It's because what goes on behind the scene when you use ``@Bind-Value``, and has to do with delegates and closures

```CS
  <InputCheckbox @bind-Value=MyArray[x].Value />
```

If you use ``@Bind-Value``, Blazor will generate code to set 3 parameters on the component (``InputCheckbox`` in your case)

1.  The ``Value`` property.
This ends up as a simple assignment so in your case the value of ``MyArray[x].Value``. (and why you see initially correct values)
2. The ``ValueExpression`` property.
 
3. And the ``ValueChanged`` property.
This creates a delegate with a closure, and this is what makes it crash.
 
Maybe it's clearer when I create a little demo program.

```CS
var CrazyStuff = new List<Func<int>>();

for (int i = 0; i < 3; i++)
{
    //Here we create a delegate
    //This will create a closure which will have a reference to the i variable (So not the actual value, but a reference)
    CrazyStuff.Add( () => i);
}

//The closures generated in the previous loop, now all have a reference to the i variable, which at this point equals 3
//So if we print all the delegates we created, they will result in 3. Not the value it was when the delegate was created.
//when we would have accessed an array here, we would try to access the first item after the array, which is invalid and creates the error you see.

foreach (var item in CrazyStuff)
{
    Console.WriteLine(item());
}
```

And why does it work when we add the local variable?
Well simply because now every loop this variable is created, so the reference will not change.

If you want to know more about closures, there are some references available. And I think it's fascinating stuff, and good knowledge to have in your backpack.
https://ericlippert.com/2009/11/12/closing-over-the-loop-variable-considered-harmful-part-one/
