### ISSUE TITLE
Interop.Functional tests failing on Debian 11 arm

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#38794]
Debian 11 isn't a recognized OS it looks like which the test discoverer can't handle

Here's the fallthrough exception:

https://github.com/dotnet/aspnetcore/blob/a32dde1438404a98ec437e249f43666cd4001170/src/Servers/Kestrel/test/Interop.FunctionalTests/H2SpecCommands.cs#L65

## Failing Test(s)

- Interop.FunctionalTests

## Error Message

```text
[xUnit.net 00:00:02.40] Interop.FunctionalTests: Exception thrown during theory discovery on 'Interop.FunctionalTests.H2SpecTests.RunIndividualTestCase'; falling back to single test case.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: Invalid OS
   at Interop.FunctionalTests.H2SpecCommands.GetToolLocation() in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/H2SpecCommands.cs:line 65
   at Interop.FunctionalTests.H2SpecCommands.EnumerateTestCases() in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/H2SpecCommands.cs:line 71
   at Interop.FunctionalTests.H2SpecTests.get_H2SpecTestCases() in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/H2SpecTests.cs:line 64
```

## Stacktrace

<details>

```text
[xUnit.net 00:00:02.40] Interop.FunctionalTests: Exception thrown during theory discovery on 'Interop.FunctionalTests.H2SpecTests.RunIndividualTestCase'; falling back to single test case.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: Invalid OS
   at Interop.FunctionalTests.H2SpecCommands.GetToolLocation() in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/H2SpecCommands.cs:line 65
   at Interop.FunctionalTests.H2SpecCommands.EnumerateTestCases() in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/H2SpecCommands.cs:line 71
   at Interop.FunctionalTests.H2SpecTests.get_H2SpecTestCases() in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/H2SpecTests.cs:line 64
```
</details>

## Logs

<details>

[xUnit.net 00:00:02.40] Interop.FunctionalTests: Exception thrown during theory discovery on 'Interop.FunctionalTests.H2SpecTests.RunIndividualTestCase'; falling back to single test case.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotImplementedException: Invalid OS

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-heads-main-80d93324627e4f1ea9/Interop.FunctionalTests--net7.0/1/console.11ec61c9.log?sv=2019-07-07&se=2021-12-22T13%3A00%3A08Z&sr=c&sp=rl&sig=Dkh%2F8MeAYRycAp%2FJeFwwgi4YTOspIani5DX8s6NtBO0%3D

</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1493839&view=ms.vss-test-web.build-test-results-tab&runId=42666076&resultId=119419&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by HaoK** [comment]
@Tratcher this is causing the helix-matrix to fail, whos' the best person to fix this?

**Comment by HaoK** [comment]
Note this is the debian arm queue which is probably why its failing through the linux case
