### ISSUE TITLE
Blazor: Refreshing page throws error when using JavaScript modules

### ISSUE THREAD

**Issue by JohnyL** [dotnet/aspnetcore#38822]
I have created simple JavaScript module and use it within Blazor component:

## Component:
```csharp
@inject IJSRuntime JS
@implements IAsyncDisposable

@code {
  private IJSObjectReference module = null;

  protected override async Task OnAfterRenderAsync(bool firstRender)
  {
    if (firstRender)
    {
      module = await JS.InvokeAsync<IJSObjectReference>("import", "./js/index.js");
    }
  }

  private async Task GetMessage()
  {
    var number = await module.InvokeAsync<int>("getNumber");
  }

  async ValueTask IAsyncDisposable.DisposeAsync()
  {
    if (module is not null)
    {
      await module.DisposeAsync();
    }
  }

}
```

## index.js
```javascript
export function getNumber() {
  return 5;
}
```
The code works fine. However, if I refresh the page, I get the following error:
<pre>
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
      Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at Microsoft.JSInterop.Implementation.JSObjectReference.DisposeAsync()
         at BonusWebApp.Pages.Counter2.System.IAsyncDisposable.DisposeAsync() in E:\Projects\BonusWebApp\BonusWebApp\Pages\Counter2.razor:line 93
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass69_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'zMwc290OOmKoYxIb3nr2K87ENe_BYFcbe8XS4PXux6Q'.
      Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at Microsoft.JSInterop.Implementation.JSObjectReference.DisposeAsync()
         at BonusWebApp.Pages.Counter2.System.IAsyncDisposable.DisposeAsync() in E:\Projects\WebApp\WebApp\Pages\Counter2.razor:line 93
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass69_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()
</pre>

When I go to another page, the `DisposeAsync` gets called and no error appears. However, refreshing the page generates error.

### Further technical details
- ASP.NET Core version: 6.0
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: Visual Studio 2022 17.1.0 Preview 1.1

**Comment by SteveSandersonMS** [comment]
This is as designed. The exception here is `JSDisconnectedException`, indicating that the JS interop call cannot be issued because there's no active connection.  In this case you probably want to ignore such exceptions, so you should use a `try`/`catch` for that specific exception type in this place.
