### ISSUE TITLE
.NET 6 - Blazor Server Side: RemoteJSDataStream NullReferenceException BUG

### ISSUE THREAD

**Issue by abberdeen** [dotnet/aspnetcore#38854]
### Describe the bug
I get an error while uploading files as StreamContent in parallel from .NET 6 / Blazor Server-Side to API via HttpClient. Here is the stripped down code and the full text of the error:

**P.S.** The RemoteJSRuntime that is passed to Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSDataStream.ReceiveData by the framework is NULL, so an error is thrown. However, I don't understand why NULL is passed. I cannot catch it, extinguish it, somehow influence it.

**P.S.S.** It is not related to ApiClient, it works fine. The error only occurs when start after the first page load, oddly enough, after reloading the page and starting again, somehow works.

**P.S.S.S.** The same code runs without any changes on .NET 5.

**P.S.S.S.S.**  The project uses two packages related to this task. Rolling them back to version 5.0.12 did not help.
 
However, rolling them back together .NET solves the problem. That is up to .NET 5 and libraries up to 5.0.12.
```
<PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="6.0.0" />
<PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="6.0.0" />
```

**NOTE:**  There are no similar posts on StackOverflow, or no one knows the answer to this question.

### To Reproduce
I could only give partial code:
```
void StartUploadTask(List<IBrowserFile> files)
{
    foreach (var item in files)
    {
        Task t = taskFactory.StartNew(async () =>
        {
            await semaphoreSlim.WaitAsync();
            try
            {
                // .... prepare url, formData

                await httpClient.PostAsync(url, formData, cancellationToken); // Here is main place
            }
            finally
            {
                semaphoreSlim.Release();
            }
        });

        tasks.Add(t);
    }
}
```
**HttpClient parameters:**
```
           var authHttpClientHandler = new AuthHttpClientHandler(httpContextAccessor);
            httpProgressHandler = new ProgressMessageHandler(authHttpClientHandler);

            httpClient = new HttpClient(httpProgressHandler);
            httpClient.BaseAddress = new Uri(configuration["ApiUrl"]);
 
            httpClient.Timeout = TimeSpan.FromMinutes(60);
```
### Exceptions (if any)
```
blazor.server.js:1 [2021-12-06T19:07:53.123Z] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSDataStream.ReceiveData(RemoteJSRuntime runtime, Int64 streamId, Int64 chunkId, Byte[] chunk, String error)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c__11`1.<<InvokeAsync>b__11_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.ReceiveJSDataChunk(Int64 streamId, Int64 chunkId, Byte[] chunk, String error)
```
**Also after this, WebSocket Connection is disconnecting and this error is shown:** 
```
Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
    at _t.send (blazor.server.js:1)
    at Tt._sendMessage (blazor.server.js:1)
    at Tt._sendWithProtocol (blazor.server.js:1)
    at Tt.send (blazor.server.js:1)
    at blazor.server.js:1
```
**Errors in the output window:**
```
System.TimeoutException: Did not receive any data in the allotted time.
         at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
         at System.IO.Pipelines.Pipe.GetReadAsyncResult()
         at System.IO.Pipelines.PipeReaderStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSDataStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Components.Forms.BrowserFileStream.CopyFileDataIntoBuffer(Int64 sourceOffset, Memory`1 destination, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Components.Forms.BrowserFileStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
         at System.IO.Stream.<CopyToAsync>g__Core|29_0(Stream source, Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
         at System.Net.Http.StreamToStreamCopy.<CopyAsync>g__DisposeSourceAsync|1_0(Task copyTask, Stream source)
         at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
         at System.Net.Http.MultipartContent.SerializeToStreamAsyncCore(Stream stream, TransportContext context, CancellationToken cancellationToken)
         at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
         at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
         at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at ~~~~~BlazorApp.Services.AuthHttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in ~~~~~BlazorApp\Services\AuthHttpClientHandler.cs:line 27
         at System.Net.Http.Handlers.ProgressMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         at ~~~~~BlazorApp.Services.FileUploadApiService.PostAndReportProgress(String url, MultipartFormDataContent formData, String guid, EventHandler`1 progressHandler, CancellationToken cancellationToken) in ~~~~~BlazorApp\Services\FileUploadApiService.cs:line 106
         --- End of inner exception stack trace ---
         at ~~~~~BlazorApp.Services.FileUploadApiService.PostAndReportProgress(String url, MultipartFormDataContent formData, String guid, EventHandler`1 progressHandler, CancellationToken cancellationToken) in ~~~~~BlazorApp\Services\FileUploadApiService.cs:line 122
         at ~~~~~BlazorApp.Services.FileUploadApiService.ChatUploadFileAsync(StreamContent file, Int32 chatId, String guid, EventHandler`1 progressHandler, CancellationToken cancellationToken) in ~~~~~BlazorApp\Services\FileUploadApiService.cs:line 59
         at ~~~~~BlazorApp.Services.FileUploadManager.UploadFileAsync(FileUploadDto item) in ~~~~~BlazorApp\Services\FileUploadManager.cs:line 171
         at ~~~~~BlazorApp.Services.FileUploadManager.<StartUploadTask>b__18_0() in ~~~~~BlazorApp\Services\FileUploadManager.cs:line 108 
```
### Further technical details
- ASP.NET Core version: **.NET 6**
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: **Window 10 VS 2022 64-bit Version 17.0.1**
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
Пакет SDK для .NET (отражающий любой global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Среда выполнения:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  5.0.403 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

</details>

**Comment by TanayParikh** [comment]
I'm not sure I entirely follow your example. The `try` block contains all the thread specific logic and the entire critical section within the thread. In this case, would you be able to just perform this sequentially instead of spawning multiple new threads for the task or run the logic on a single thread.

```csharp
    Task t = taskFactory.StartNew(async () =>
    {
        foreach (var item in files)
        {
            // .... prepare url, formData
            await httpClient.PostAsync(url, formData, cancellationToken); // Here is main place
        }
    });

    tasks.Add(t);
```

Also, it's not entirely clear where the actual `RemoteJSDataStream` is being used in your example. Perhaps that was truncated somewhere?

> The RemoteJSRuntime that is passed to Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSDataStream.ReceiveData by the framework is NULL, so an error is thrown. However, I don't understand why NULL is passed. I cannot catch it, extinguish it, somehow influence it.

This should never happen. This call is made here, and we've asserted initialization (and not disposed):

https://github.com/dotnet/aspnetcore/blob/2d98236cfaad6b5b33e6760c8f64f022fca8ee74/src/Components/Server/src/Circuits/CircuitHost.cs#L428

If you're still experiencing this issue, could you please provide a **minimal** public github repro project to allow us to investigate further.

**Comment by abberdeen** [comment]
Hi @TanayParikh. 

Thanks for your interest in the issue. I tried in different ways and sometimes the error disappeared intermittently.
 
Does not work:
1. I ran the same code without `try`, but together with `SemaphoreSlim` in parallel.
2. I launched without `try `and `SemaphoreSlim`, in an unlimited number of tasks at same time in parallel.

Works:
1. When I run one at a time (like your example), not in parallel.
2. Launched on .NET 5, strange.
3. More or less works after reloading the page after the first load.

Created a minimal public github repo project as similar as possible to the code I'm working with, could you please take a look:
https://github.com/abberdeen/BlazorServer.ParallelFileUpload

**Comment by TanayParikh** [comment]
> When I run one at a time (like your example), not in parallel.

If I'm understanding your initial example correctly, I believe the alternate example I provided should be the same heuristically. In both examples the core logic is executed in a separate thread. Given the semaphores in your original example, the core logic shares the same [_critical section_](https://en.wikipedia.org/wiki/Critical_section) and hence the behavior is as if the code is run serially (not in parallel).

> Created a minimal public github repo project as similar as possible to the code I'm working with, could you please take a look:
> https://github.com/abberdeen/BlazorServer.ParallelFileUpload

Thanks for the repro app. Please note, for us to investigate issues, we need a **__minimal__** repro app (as close to the base blazor template as possible). This still has a lot of application specific logic that we aren't able to help debug. While we do our best to look through all the issues filed here, we are not a general-purpose forum. To get a faster response we suggest posting your questions to StackOverflow using the blazor tag.

**Comment by abberdeen** [comment]
I was surprised by the fact that the application ran on .NET 5 and decided that it was a bug.

I understood your thought about critical sections. I will further deal with this issue myself.

Your answers helped me a lot and thank you for that.
