### ISSUE TITLE
NET 6 - Minimal APIs Docker Error M1 Macbook Pro

### ISSUE THREAD

**Issue by mumby0168** [dotnet/aspnetcore#38876]
### Is your feature request related to a problem? Please describe.
I am running a new M1 MacBook pro and a docker image, it does not play with the system file watcher see the error below

```
➜  ~ docker run --platform linux/amd64 ghcr.io/mumby0168/to-be-done/work-service -p 8080:80 -e ASPNETCORE_ENVIRONMENT=Prod
Unhandled exception. System.IO.IOException: Function not implemented
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationExtensions.Add[TSource](IConfigurationBuilder builder, Action`1 configureSource)
   at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder builder, IFileProvider provider, String path, Boolean optional, Boolean reloadOnChange)
   at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder builder, String path, Boolean optional, Boolean reloadOnChange)
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.<>c__DisplayClass11_0.<ConfigureDefaults>b__1(HostBuilderContext hostingContext, IConfigurationBuilder config)
   at Microsoft.AspNetCore.Hosting.BootstrapHostBuilder.RunDefaultCallbacks(ConfigurationManager configuration, HostBuilder innerBuilder)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(WebApplicationOptions options, Action`1 configureDefaults)
   at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder(String[] args)
   at Program.<Main>$(String[] args) in /src/src/ToBeDone.Services.Work/Program.cs:line 1
qemu: uncaught target signal 6 (Aborted) - core dumped
```

### Describe the solution you'd like
A way in a net6 minimal API to disable the file watcher on the `appsettings.json` file.

I do not think this is an issue with net6 more an issue with the emulator for docker the m1 MacBook pro.

### Additional context
The program I am trying to run is here

I have the GitHub repo which contains the action to build the docker image here

https://github.com/mumby0168/todo-azure-containers-apps

```csharp
var builder = WebApplication.CreateBuilder(args);

var app = builder.Build();

app.MapGet("/", () => "ToBeDone.Services.Work");

app.Run();
```

**Comment by martincostello** [comment]
Looks like it's coming from here: https://github.com/dotnet/runtime/blob/6cf785d9fb0ad90816c0a0f76c8d999ea9901bfd/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Linux.cs#L50

**Comment by mumby0168** [comment]
> Looks like it's coming from here: https://github.com/dotnet/runtime/blob/6cf785d9fb0ad90816c0a0f76c8d999ea9901bfd/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Linux.cs#L50

Yeah I've read in a few places the emulation for the M1 mac isn't quite 100% yet, just wanted to turn this off for now. The file watching of the JSON files that is.

**Comment by captainsafia** [comment]
@mumby0168 Any lock with [setting the `reloadConfigOnChange` flag](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-6.0#disable-app-configuration-reload-on-change) in your appsettings file?

**Comment by mumby0168** [comment]
> @mumby0168 Any lock with [setting the `reloadConfigOnChange` flag](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-6.0#disable-app-configuration-reload-on-change) in your appsettings file?

I'm sure that will do the trick thanks, since this I have built and pushed images for M1 native using docker buildx happy to close this now thanks @captainsafia 😃
