### ISSUE TITLE
Quarantine ShutdownTests

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#38951]
## Failing Test(s)

 
- Microsoft.AspNetCore.Server.IIS.NewShim.FunctionalTests.ShutdownTests.GracefulShutdownWorksWithMultipleRequestsInFlight_InProcess

## Error Message

```text
No entries matched by 'Application 'MACHINE/WEBROOT/APPHOST/.*?' has shutdown.'
Expected: True
Actual:   False
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.EventLogHelpers.AssertEntry(String regexString, IEnumerable`1 entries, Boolean allowMultiple) in /_/src/Servers/IIS/IIS/test/Common.FunctionalTests/Infrastructure/EventLogHelpers.cs:line 72
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.EventLogHelpers.VerifyEventLogEvent(IISDeploymentResult deploymentResult, String expectedRegexMatchString, ILogger logger, Boolean allowMultiple) in /_/src/Servers/IIS/IIS/test/Common.FunctionalTests/Infrastructure/EventLogHelpers.cs:line 25
   at Microsoft.AspNetCore.Server.IIS.NewShim.FunctionalTests.ShutdownTests.GracefulShutdownWorksWithMultipleRequestsInFlight_InProcess() in /_/src/Servers/IIS/IIS/test/Common.LongTests/ShutdownTests.cs:line 265
--- End of stack trace from previous location ---
```
</details>

## Logs

<details>

[ShutdownTests_GracefulShutdownWorksWithMultipleRequestsInFlight_InProcess.log](https://github.com/dotnet/aspnetcore/files/7695261/ShutdownTests_GracefulShutdownWorksWithMultipleRequestsInFlight_InProcess.log)
</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1506583&view=ms.vss-test-web.build-test-results-tab&runId=42925498&resultId=120014&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by TanayParikh** [comment]
Microsoft.AspNetCore.Server.IIS.NewHandler.FunctionalTests.ShutdownTests.ConfigurationTouchedStress_InProcess

Status code was 500
Expected: True
Actual:   False


   at Microsoft.AspNetCore.Server.IIS.NewHandler.FunctionalTests.ShutdownTests.<>c.<ConfigurationTouchedStress>b__25_0(HttpResponseMessage response) in /_/src/Servers/IIS/IIS/test/Common.LongTests/ShutdownTests.cs:line 506
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.Helpers.<>c__DisplayClass4_0.<<StressLoad>g__RunRequests|0>d.MoveNext() in /_/src/Servers/IIS/IIS/test/Common.FunctionalTests/Infrastructure/Helpers.cs:line 48
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.Helpers.StressLoad(HttpClient httpClient, String path, Action`1 action) in /_/src/Servers/IIS/IIS/test/Common.FunctionalTests/Infrastructure/Helpers.cs:line 58
   at Microsoft.AspNetCore.Server.IIS.NewHandler.FunctionalTests.ShutdownTests.ConfigurationTouchedStress(HostingModel hostingModel) in /_/src/Servers/IIS/IIS/test/Common.LongTests/ShutdownTests.cs:line 521
   at Microsoft.AspNetCore.Server.IIS.NewHandler.FunctionalTests.ShutdownTests.ConfigurationTouchedStress_InProcess() in /_/src/Servers/IIS/IIS/test/Common.LongTests/ShutdownTests.cs:line 495
--- End of stack trace from previous location ---

[ShutdownTests_ConfigurationTouchedStress_InProcess.log](https://github.com/dotnet/aspnetcore/files/7695271/ShutdownTests_ConfigurationTouchedStress_InProcess.log)

**Comment by Tratcher** [comment]
> No entries matched by 'Application 'MACHINE/WEBROOT/APPHOST/.*?' has shutdown.'

`Event Log: 'Application 'MACHINE/WEBROOT/APPHOST/DEFAULT WEB SITE' has shutdown.' `

hmmm

**Comment by HaoK** [comment]
Duping against https://github.com/dotnet/aspnetcore/issues/41264 and unquarantining this test in https://github.com/dotnet/aspnetcore/pull/42932 since its been passing for 30 days and its a general infrastructure issue

**Comment by HaoK** [comment]
Retries should have minimized this as well, as local retries should work
