### ISSUE TITLE
Quarantine WebHostTests.UseUrls_HelloWorld_ClientSuccess

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#38954]
## Failing Test(s)

- Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Tests.WebHostTests.UseUrls_HelloWorld_ClientSuccess

## Error Message

```text
System.Net.Http.HttpRequestException : Connection has been shutdown by transport. Error Code: CONNECTION_REFUSED (127.0.0.1:50426)
---- System.Net.Quic.QuicException : Connection has been shutdown by transport. Error Code: CONNECTION_REFUSED
```

## Stacktrace

<details>

```text
at System.Net.Http.ConnectHelper.ConnectQuicAsync(HttpRequestMessage request, QuicImplementationProvider quicImplementationProvider, DnsEndPoint endPoint, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp3ConnectionAsync(HttpRequestMessage request, HttpAuthority authority, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Tests.WebHostTests.UseUrls_HelloWorld_ClientSuccess() in /_/src/Servers/Kestrel/Transport.Quic/test/WebHostTests.cs:line 55
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventShutdownInitiatedByTransport(State state, ConnectionEvent& connectionEvent)
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.NativeCallbackHandler(IntPtr connection, IntPtr context, ConnectionEvent& connectionEvent)
--- End of stack trace from previous location ---
   at System.Net.Http.ConnectHelper.ConnectQuicAsync(HttpRequestMessage request, QuicImplementationProvider quicImplementationProvider, DnsEndPoint endPoint, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken)
```
</details>

## Logs

<details>

```
[0.001s] [TestLifetime] [Information] Starting test UseUrls_HelloWorld_ClientSuccess at 2021-12-10T21:10:42
[0.048s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting starting
[0.111s] [Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer] [Debug] Using development certificate: CN=localhost (Thumbprint: 3A0E813A32FF3D485961C3645581983F2862E566)
[0.128s] [Microsoft.Hosting.Lifetime] [Information] Now listening on: https://127.0.0.1:50426
[0.129s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Debug] Loaded hosting startup assembly Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Tests
[0.129s] [Microsoft.Hosting.Lifetime] [Information] Application started. Press Ctrl+C to shut down.
[0.129s] [Microsoft.Hosting.Lifetime] [Information] Hosting environment: Production
[0.129s] [Microsoft.Hosting.Lifetime] [Information] Content root path: C:\h\w\B39109B3\w\ADF00A01\e\
[0.130s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting started
[1.609s] [Microsoft.AspNetCore.Server.Kestrel.Transport.Quic] [Debug] Listener has aborted with exception: Operation aborted.
[1.686s] [Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Tests.WebHostTests] [Error] Test threw an exception.
System.Net.Http.HttpRequestException: Connection has been shutdown by transport. Error Code: CONNECTION_REFUSED (127.0.0.1:50426)
 ---> System.Net.Quic.QuicException: Connection has been shutdown by transport. Error Code: CONNECTION_REFUSED
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventShutdownInitiatedByTransport(State state, ConnectionEvent& connectionEvent)
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.NativeCallbackHandler(IntPtr connection, IntPtr context, ConnectionEvent& connectionEvent)
--- End of stack trace from previous location ---
   at System.Net.Http.ConnectHelper.ConnectQuicAsync(HttpRequestMessage request, QuicImplementationProvider quicImplementationProvider, DnsEndPoint endPoint, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectQuicAsync(HttpRequestMessage request, QuicImplementationProvider quicImplementationProvider, DnsEndPoint endPoint, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp3ConnectionAsync(HttpRequestMessage request, HttpAuthority authority, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Tests.WebHostTests.UseUrls_HelloWorld_ClientSuccess() in /_/src/Servers/Kestrel/Transport.Quic/test/WebHostTests.cs:line 55
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
[1.687s] [TestLifetime] [Information] Finished test UseUrls_HelloWorld_ClientSuccess in 1.6858936s
```

</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1505506&view=ms.vss-test-web.build-test-results-tab&runId=42939082&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab&resultId=106869

**Comment by Tratcher** [comment]
Related? https://github.com/dotnet/runtime/issues/55979

MsQuic refuses new connections when the CPU is maxxed out. Could we isolate these tests to avoid that?
