### ISSUE TITLE
Unable to configure OpenIdConnectOptions for authenitcation

### ISSUE THREAD

**Issue by koshdim** [dotnet/aspnetcore#38992]
### Describe the bug
When I try to use Dependency Injection to load settings for Open ID Connect from database, whole registration stops working.
This works:

```
...
.AddOpenIdConnect("oidc", options => 
{
    options.ClientId = signicat.ClientId;
    ...
 });
```
this doesn't:

```
...
 .AddOpenIdConnect("oidc", options => { });

services
.AddOptions<OpenIdConnectOptions>("oidc")
.Configure<IServiceProvider>(async (options, sp) => 
{
    options.ClientId = signicat.ClientId;
    ...
});
```

### To Reproduce

In Startup.cs OpenIdConnect is configured like this:
```
services
                .AddAuthentication(options =>
                {
                    options.DefaultScheme = "Cookies";
                    options.DefaultChallengeScheme = "oidc";
                })
                .AddCookie("Cookies")
                .AddOpenIdConnect("oidc", options => { });

            services.AddOptions<OpenIdConnectOptions>("oidc")
                .Configure<IServiceProvider>(async (options, sp) =>
                {
                    using var scope = sp.CreateScope();
                    var dbContext = scope.ServiceProvider.GetRequiredService<DbContext>();
                    var openIdSettings = (await dbContext.Settings.FirstOrDefaultAsync()) ?? throw new InvalidOperationException("Failed to load settings");

                    options.Events.OnAuthorizationCodeReceived = RedeemAuthorizationCodeAsync;
                    options.ClientId = openIdSettings.ClientId;
                    options.ClientSecret = openIdSettings.Password;
                    options.CallbackPath = openIdSettings.CallbackPath;
                    options.Authority = openIdSettings.BaseUrl;
                    options.ResponseType = "code";
                    options.Scope.Add("openid");
                    options.Scope.Add("profile");
                    options.GetClaimsFromUserInfoEndpoint = true;
                    options.SaveTokens = true;
                });
            services.AddAuthorization();
```
Note that in AddOpenIdConnect() options are not configured, client secret and the rest is configured in Configure() method.

Achieved: When application starts exception is thrown, AddOpenIdConnect doesn't pick up options configured outside of its callback.
Expected: Open Id Connect works using options set with AddOptions<>().Configure<>()

### Exceptions (if any)
System.ArgumentException: Options.ClientId must be provided (Parameter 'ClientId')
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectOptions.Validate()
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationOptions.Validate(String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationBuilder.<>c__DisplayClass4_0`2.<AddSchemeHelper>b__1(TOptions o)
   at Microsoft.Extensions.Options.ValidateOptions`1.Validate(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsMonitor`1.<>c__DisplayClass11_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

### Further technical details
- ASP.NET Core version: netcoreapp3.1
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS 2022
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  5.0.403 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

</details>

**Comment by koshdim** [comment]
the problem was with async Action in configure (:
