### ISSUE TITLE
Quarantine ShutdownTimeoutIsApplied

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#38995]
## Failing Test(s)

- Microsoft.AspNetCore.Server.IIS.NewHandler.FunctionalTests.ShutdownTests.ShutdownTimeoutIsApplied

## Error Message

```text
No entries matched by 'Application 'C:\h\w\A26808F4\t\6b2f1e1a99dd4b1ea3f823e23b4bee62' started successfully.'
Expected: True
Actual:   False
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.EventLogHelpers.AssertEntry(String regexString, IEnumerable`1 entries, Boolean allowMultiple) in /_/src/Servers/IIS/IIS/test/Common.FunctionalTests/Infrastructure/EventLogHelpers.cs:line 72
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.EventLogHelpers.VerifyEventLogEvents(IISDeploymentResult deploymentResult, String[] expectedRegexMatchString) in /_/src/Servers/IIS/IIS/test/Common.FunctionalTests/Infrastructure/EventLogHelpers.cs:line 44
   at Microsoft.AspNetCore.Server.IIS.NewHandler.FunctionalTests.ShutdownTests.ShutdownTimeoutIsApplied() in /_/src/Servers/IIS/IIS/test/Common.LongTests/ShutdownTests.cs:line 57
--- End of stack trace from previous location ---
```
</details>

## Logs

<details>

[ShutdownTests_ShutdownTimeoutIsApplied.log](https://github.com/dotnet/aspnetcore/files/7705386/ShutdownTests_ShutdownTimeoutIsApplied.log)

</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1509431&view=ms.vss-test-web.build-test-results-tab&runId=42984652&resultId=121314&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by TanayParikh** [comment]
Possibly related to https://github.com/dotnet/aspnetcore/issues/38951?

**Comment by Tratcher** [comment]
The log does contain `Event Log: 'Application 'C:\h\w\A26808F4\t\6b2f1e1a99dd4b1ea3f823e23b4bee62\' started successfully.' `

Note the extra trailing slash.

`'Application 'C:\h\w\A26808F4\t\6b2f1e1a99dd4b1ea3f823e23b4bee62\' started successfully.' `
`'Application 'C:\h\w\A26808F4\t\6b2f1e1a99dd4b1ea3f823e23b4bee62' started successfully.'`

**Comment by HaoK** [comment]
Could be the trailing slash for sure with content root behavior changing again in 7, we have some logic around this

https://github.com/dotnet/aspnetcore/blob/0f61a3df907178ad5f8bac41fad715839ee6daae/src/Servers/IIS/IIS/test/Common.FunctionalTests/Infrastructure/EventLogHelpers.cs#L320

**Comment by HaoK** [comment]
Duping against https://github.com/dotnet/aspnetcore/issues/41264 and unquarantining this test in https://github.com/dotnet/aspnetcore/pull/42932 since its been passing for 30 days and its a general infrastructure issue
