### ISSUE TITLE
GitHub Codespaces `dotnet run` produces `Failed to authenticate HTTPS connection` Exception

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#39074]
```
dbug: Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware[1]
      Failed to authenticate HTTPS connection.
      System.IO.IOException: Cannot determine the frame size or a corrupted frame was received.
         at System.Net.Security.SslStream.GetFrameSize(ReadOnlySpan`1 buffer)
         at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
         at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context) in /workspaces/aspnetcore/src/Servers/Kestrel/Core/src/Middleware/HttpsConnectionMiddleware.cs:line 163
```

**Comment by TanayParikh** [comment]
dev certs were installed immediately before.

**Comment by Tratcher** [comment]
Any more details on your setup? That error sounds like you're sending HTTP traffic to an HTTPS endpoint.

**Comment by adityamandaleeka** [comment]
@TanayParikh @captainsafia What should we do with this issue?

**Comment by TanayParikh** [comment]
This feels more like a codespaces config issue for our repo's container, rather than a product issue.

**Comment by captainsafia** [comment]
@TanayParikh Are you still able to repro this? I haven't been able to repro it when I run the `MinimalSample` in the repo.

**Comment by TanayParikh** [comment]
Yes with a new Blazor Server app.
