### ISSUE TITLE
Blazor cannot serialize number to string

### ISSUE THREAD

**Issue by wnvko** [dotnet/aspnetcore#39080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a project where I am receiving a data as JSON. There are several fields in the data which may come as strings or as numbers, like this:
`[
  {
    "postaCode": 12209
  },
  {
    "postaCode": "WA1 1DP"
  },
  {
    "postaCode": 5021
  }
]`

In my model I am describing all these field like nullable strings like this:

`public class MyClass
{
  public string? PostalCode { get; set; }
}`

When trying to fetch the data I am getting this error:
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The JSON value could not be converted to System.String.

### Expected Behavior

Converting a number to string should not be an issue. Actually most of the types should be allowed to be converted to string.

### Steps To Reproduce

Here is a GitHub repo with a sample reproducing the issue
[Sample](https://github.com/wnvko/number-to-string-issue)

### Exceptions (if any)

blazor.webassembly.js:1 
        
       crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The JSON value could not be converted to System.String. Path: $[0].PostalCode | LineNumber: 6 | BytePositionInLine: 23.
System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $[0].PostalCode | LineNumber: 6 | BytePositionInLine: 23.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'Number' as a string.
   at System.Text.Json.Utf8JsonReader.GetString()
   at System.Text.Json.Serialization.Converters.StringConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[SerializeNumberToStringIssue.Data.Customer, SerializeNumberToStringIssue, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, Customer& value)
   at System.Text.Json.Serialization.JsonConverter`1[[SerializeNumberToStringIssue.Data.Customer, SerializeNumberToStringIssue, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, Customer& value)
   at System.Text.Json.Serialization.JsonCollectionConverter`2[[SerializeNumberToStringIssue.Data.Customer[], SerializeNumberToStringIssue, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[SerializeNumberToStringIssue.Data.Customer, SerializeNumberToStringIssue, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, Customer[]& value)
   at System.Text.Json.Serialization.JsonConverter`1[[SerializeNumberToStringIssue.Data.Customer[], SerializeNumberToStringIssue, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, Customer[]& value)
   at System.Text.Json.Serialization.JsonConverter`1[[SerializeNumberToStringIssue.Data.Customer[], SerializeNumberToStringIssue, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1[[SerializeNumberToStringIssue.Data.Customer[], SerializeNumberToStringIssue, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[Customer[]](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[Customer[]](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[Customer[]](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.<ReadAllAsync>d__65`1[[SerializeNumberToStringIssue.Data.Customer[], SerializeNumberToStringIssue, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Net.Http.Json.HttpContentJsonExtensions.<ReadFromJsonAsyncCore>d__4`1[[SerializeNumberToStringIssue.Data.Customer[], SerializeNumberToStringIssue, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Net.Http.Json.HttpClientJsonExtensions.<GetFromJsonAsyncCore>d__13`1[[SerializeNumberToStringIssue.Data.Customer[], SerializeNumberToStringIssue, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at SerializeNumberToStringIssue.Pages.MasterView.OnInitializedAsync() in D:\test\SerializeNumberToStringIssue\SerializeNumberToStringIssue\Pages\MasterView.razor:line 30
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

### .NET Version

6.0.101

**Comment by pranavkm** [comment]
> Converting a number to string should not be an issue. Actually most of the types should be allowed to be converted to string.

Blazor uses System.Text.Json for it's serialization which conforms to the [JSON specification](https://www.json.org/json-en.html). Strings are expected to be quoted and numbers do not transform to strings by default. You could consider annotating your properties with a [JsonConverterAttribute](https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-converters-how-to?pivots=dotnet-6-0#registration-sample---jsonconverter-on-a-property) in case you'd like to take over how the deserialization works for a property.
