### ISSUE TITLE
Error unprotecting the session cookie.

### ISSUE THREAD

**Issue by bbhxwl** [dotnet/aspnetcore#39091]
When I visit any of my web pages, as long as there is no session, he will prompt this. I don't know how to cancel?

**Comment by bbhxwl** [comment]
Microsoft.AspNetCore.Session.SessionMiddleware[7]
      Error unprotecting the session cookie.
System.Security.Cryptography.CryptographicException: The key {5564d4c5-567c-452a-b474-9689060415fe} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Session.CookieProtection.Unprotect(IDataProtector protector, String protectedText, ILogger logger)

**Comment by blowdart** [comment]
When you say "prompt this" what do you mean? It appears in the console log?

Where is your app hosted? Are there other data protection messages in the logs, especially around app startup time?

**Comment by blowdart** [comment]
I really need log files and your hosting details to be of any help. It sounds like your data protection key ring is not persisted anywhere, so when an app restarts the key ring starts afresh and any existing cookies become invalid.

**Comment by Tratcher** [comment]
If the app was redeployed and generated new encryption keys then it won't be able to decrypt old cookies. Those cookies will eventually be cleaned up by the client.

See these docs for saving the encryption keys across deployments.
https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-6.0
