### ISSUE TITLE
Microsoft.AspNetCore.Http.Results.File() fails to determine the correct file size of symlinks

### ISSUE THREAD

**Issue by anorm** [dotnet/aspnetcore#39170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If a filename given to `Microsoft.AspNetCore.Http.Results.File()` is a symlink, the size retrieved for the `Content-Length` header is wrong.

### Expected Behavior

`Results.File()` should follow the symlink to the real file and determine the actual file size.

### Steps To Reproduce

Example
```
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

app.MapGet("/foo", () => { return Results.File("/foo", "application/octet-strean", "foo"); });

app.Run();
```

Run the above with a symlink named `/foo` in the filesystem, pointing to a real file. When requesting the path, the following exception is produced.

```
InvalidOperationException: Response Content-Length mismatch: too many bytes written (558 of 13).
```

### Exceptions (if any)

```
System.InvalidOperationException: Response Content-Length mismatch: too many bytes written (558 of 13).
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.VerifyAndUpdateWrite(Int32 count)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.FirstWriteAsyncInternal(ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.WritePipeAsync(ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.WriteAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.StreamCopyOperationInternal.CopyToAsync(Stream source, Stream destination, Nullable`1 count, Int32 bufferSize, CancellationToken cancel)
   at Microsoft.AspNetCore.Http.SendFileFallback.SendFileAsync(Stream destination, String filePath, Int64 offset, Nullable`1 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.SendFileResponseExtensions.SendFileAsyncCore(HttpResponse response, String fileName, Int64 offset, Nullable`1 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteResultWriteResponse(IResult result, HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### .NET Version

6.0.101

### Anything else?

Marry Christmas 🎄

**Comment by brunolins16** [comment]
@anorm thanks for the bug report and indeed it is failing. The error is happening because when the `FileInfo` is captured the link target is not getting checked.

https://github.com/dotnet/aspnetcore/blob/dae7ed1acd94708626f35ba4b97b38330d1369f4/src/Http/Http.Results/src/VirtualFileResult.cs#L109

https://github.com/dotnet/aspnetcore/blob/dae7ed1acd94708626f35ba4b97b38330d1369f4/src/Http/Http.Results/src/PhysicalFileResult.cs#L107

I think we could fix it using the [FileSystemInfo Symbolic Link API](https://docs.microsoft.com/en-us/dotnet/api/system.io.filesysteminfo.resolvelinktarget?view=net-6.0) to check if the file is a symlink and get the final target info instead.

**Comment by brunolins16** [comment]
@anorm what you can do right now, while the fix is not available, is use one of the other Results.File overloads that calculates the file size using different approaches.

[File(Stream, String, String, Nullable<DateTimeOffset>, EntityTagHeaderValue, Boolean)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.results.file?view=aspnetcore-6.0#Microsoft_AspNetCore_Http_Results_File_System_IO_Stream_System_String_System_String_System_Nullable_System_DateTimeOffset__Microsoft_Net_Http_Headers_EntityTagHeaderValue_System_Boolean_)

[File(Byte[], String, String, Boolean, Nullable<DateTimeOffset>, EntityTagHeaderValue)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.results.file?view=aspnetcore-6.0#Microsoft_AspNetCore_Http_Results_File_System_Byte___System_String_System_String_System_Boolean_System_Nullable_System_DateTimeOffset__Microsoft_Net_Http_Headers_EntityTagHeaderValue_)

**Comment by brunolins16** [comment]
@anorm we just committed a fix to this issue when using Physical Files paths and we have another issue opened that will handle the issue for Virtual File paths dotnet/runtime#63424

**Comment by anorm** [comment]
Perfect :+1:
