### ISSUE TITLE
Warnings when running a .NET 7 Blazor app

### ISSUE THREAD

**Issue by pranavkm** [dotnet/aspnetcore#39283]
```
global cwrap is obsolete, please use Module.cwrap instead     at https://localhost:5001/_framework/blazor.webassembly.js:1:37123
    at callRuntimeCallbacks (https://localhost:5001/_framework/dotnet.7.0.0-alpha.1.21624.1.ayco8hdvqv.js:13:17660)
    at preRun (https://localhost:5001/_framework/dotnet.7.0.0-alpha.1.21624.1.ayco8hdvqv.js:13:12976)
    at run (https://localhost:5001/_framework/dotnet.7.0.0-alpha.1.21624.1.ayco8hdvqv.js:13:147975)
    at runCaller (https://localhost:5001/_framework/dotnet.7.0.0-alpha.1.21624.1.ayco8hdvqv.js:13:147852)
    at removeRunDependency (https://localhost:5001/_framework/dotnet.7.0.0-alpha.1.21624.1.ayco8hdvqv.js:13:14220)
    at receiveInstance (https://localhost:5001/_framework/dotnet.7.0.0-alpha.1.21624.1.ayco8hdvqv.js:13:16056)
    at https://localhost:5001/_framework/blazor.webassembly.js:1:36991
get @ dotnet.7.0.0-alpha.1.21624.1.ayco8hdvqv.js:3
dotnet.7.0.0-alpha.1.21624.1.ayco8hdvqv.js:3 
        
       global addRunDependency is obsolete, please use Module.addRunDependency instead     at https://localhost:5001/_framework/blazor.webassembly.js:1:37264
    at https://localhost:5001/_framework/blazor.webassembly.js:1:37566
    at callRuntimeCallbacks (https://localhost:5001/_framework/dotnet.7.0.0-alpha.1.21624.1.ayco8hdvqv.js:13:17660)
    at preRun (https://localhost:5001/_framework/dotnet.7.0.0-alpha.1.21624.1.ayco8hdvqv.js:13:12976)
    at run (https://localhost:5001/_framework/dotnet.7.0.0-alpha.1.21624.1.ayco8hdvqv.js:13:147975)
    at runCaller (https://localhost:5001/_framework/dotnet.7.0.0-alpha.1.21624.1.ayco8hdvqv.js:13:147852)
    at removeRunDependency (https://localhost:5001/_framework/dotnet.7.0.0-alpha.1.21624.1.ayco8hdvqv.js:13:14220)
    at receiveInstance (https://localhost:5001/_framework/dotnet.7.0.0-alpha.1.21624.1.ayco8hdvqv.js:13:16056)
    at https://localhost:5001/_framework/blazor.webassembly.js:1:36991
get @ dotnet.7.0.0-alpha.1.21624.1.ayco8hdvqv.js:3
dotnet.7.0.0-alpha.1.21624.1.ayco8hdvqv.js:3 
        
       global removeRunDependency is obsolete, please use Module.removeRunDependency instead     at https://localhost:5001/_framework/blazor.webassembly.js:1:37473
```

**Comment by pranavkm** [comment]
@pavelsavara does your PR help address these warnings?

**Comment by pavelsavara** [comment]
> @pavelsavara does your PR help address these warnings?

Yes it does.

**Comment by SteveSandersonMS** [comment]
Thanks for confirming, @pavelsavara! I'll reassign to you if that's OK, otherwise it'll be confusing about who's taking action here.
