### ISSUE TITLE
JsonSerializerOptions.GetConverter Returns ObjectDefaultConverter, Insted of Expected Null

### ISSUE THREAD

**Issue by DerekJi** [dotnet/aspnetcore#39345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

[Here's a sample project](https://github.com/DerekJi/JsonGetConverterDemo), which used to work very well.

In this project (see [CustomBase64Converter.cs](https://github.com/DerekJi/JsonGetConverterDemo/blob/master/JsonGetConverterDemo/CustomBase64Converter.cs)), I need to check if there's any available converter. 
```c#
    public T? Deserialize(ref Utf8JsonReader reader, JsonSerializerOptions options)
    {
        var converter = (JsonConverter<T>?)options.GetConverter(_valueType);

        if (converter != null)
        {
            return converter.Read(ref reader, _valueType, options);
        }
        else
        {
            return JsonSerializer.Deserialize<T>(ref reader, options);
        }
    }
```

It works perfectly before, with dotnet core 3.1. However, after upgraded to .net 6, it fails with exceptions like
![image](https://user-images.githubusercontent.com/33775203/148382751-b0ef1f24-b107-4b24-9f43-edd039df007a.png)

### Expected Behavior

The given string `encoded` can be deserialized correctly by `CustomBase64Converter` without exceptions.

```c#
    var encoded =
        "{\"StatusCode\":202,\"Description\":\"Testing\",\"AddressJson\":\"eyJTdHJlZXRObyI6IjVBIiwiU3RyZWV0IjoiU2FtcGxlIFN0cmVldCIsIlN1YnVyYiI6bnVsbCwiU3RhdGUiOiJTb3V0aCBBdXN0cmFsaWEiLCJDb3VudHJ5IjoiQXVzdHJhbGlhIn0=\"}";

    var options = new JsonSerializerOptions
    {
        PropertyNameCaseInsensitive = true,
    };

    var decoded = JsonSerializer.Deserialize<SampleResponse>(encoded, options);
```

## Reproduce the issue
1. Clone the sample project: https://github.com/DerekJi/JsonGetConverterDemo
2. Build and run in Visual Studio 2022. Or, run the commands in console
```bash
dotnet run
```
You'll get the exception

## Downgrade to dotnetcore3.1 and the issue is gone
1. update the project file to change `targetframework` as
```xml
<TargetFramework>netcoreapp3.1</TargetFramework>
```
2. rebuild and run the project, everything runs well.

### Exceptions (if any)

Unhandled exception. System.Text.Json.JsonException: The JSON value could not be converted to JsonGetConverterDemo.Address. Path: $.AddressJson | LineNumber: 0 | BytePositionInLine: 198.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)   
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonResumableConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at JsonGetConverterDemo.CustomBase64Converter`1.Deserialize(Utf8JsonReader& reader, JsonSerializerOptions options) in D:\Github\dotnet-core\JsonGetConverterDemo\JsonGetConverterDemo\CustomBase64Converter.cs:line 16
   at JsonGetConverterDemo.CustomBase64Converter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) in D:\Github\dotnet-core\JsonGetConverterDemo\JsonGetConverterDemo\CustomBase64Converter.cs:line 41
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)   
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Program.<<Main>$>g__Demo|0_0() in D:\Github\dotnet-core\JsonGetConverterDemo\JsonGetConverterDemo\Program.cs:line 35
   at Program.<Main>$(String[] args) in D:\Github\dotnet-core\JsonGetConverterDemo\JsonGetConverterDemo\Program.cs:line 7

### .NET Version

6.0.100

### Anything else?

The document (https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.getconverter?view=net-6.0) says:
![image](https://user-images.githubusercontent.com/33775203/148385421-54be088d-dd47-403d-945c-44ba3c7d6a66.png)

Without any specified converters, I expect `options.GetConverter(_valueType)` returns null, just as described above. However, with .net 6, it returns `ObjectDefaultConverter` unexpectedly.

**Comment by DerekJi** [comment]
From the source code, it seems trying to be smarter. Saying, if no converter is found, it still makes more tries in different ways (priority 3 & priority 4). 

HOWEVER, this is not documented at all: https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.getconverter?view=net-6.0

![image](https://user-images.githubusercontent.com/33775203/148386019-a37bfe5e-6e5c-4c55-b765-5d2caf5cc56e.png)
