### ISSUE TITLE
Quarantine AcceptNewStreamsDuringClosingConnection

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#39479]
## Failing Test(s)

- Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2ConnectionTests.AcceptNewStreamsDuringClosingConnection

## Error Message

```text
System.TimeoutException : The operation has timed out.
```

## Stacktrace

<details>

```text
at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 108
   at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2TestBase.ReceiveFrameAsync(UInt32 maxFrameSize) in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2TestBase.cs:line 1139
   at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2TestBase.WaitForConnectionErrorAsyncDoNotCloseTransport[TException](Boolean ignoreNonGoAwayFrames, Int32 expectedLastStreamId, Http2ErrorCode expectedErrorCode, String[] expectedErrorMessage) in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2TestBase.cs:line 1217
   at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2TestBase.WaitForConnectionErrorAsync[TException](Boolean ignoreNonGoAwayFrames, Int32 expectedLastStreamId, Http2ErrorCode expectedErrorCode, String[] expectedErrorMessage) in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2TestBase.cs:line 1212
   at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2ConnectionTests.AcceptNewStreamsDuringClosingConnection() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2ConnectionTests.cs:line 4698
--- End of stack trace from previous location ---
```
</details>

## Logs

<details>

[Http2ConnectionTests_AcceptNewStreamsDuringClosingConnection.log](https://github.com/dotnet/aspnetcore/files/7859496/Http2ConnectionTests_AcceptNewStreamsDuringClosingConnection.log)

</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1549949&view=ms.vss-test-web.build-test-results-tab&runId=43758218&resultId=109022&paneView=debug

**Comment by TanayParikh** [comment]
I believe we'd like to keep these issues open to ensure the `QuarantinedTest` attribute is removed after 30 days.
