### ISSUE TITLE
Initializing a new HubConnectionContext for unit tests results in System.NullReferenceException

### ISSUE THREAD

**Issue by Roy19** [dotnet/aspnetcore#39484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We are migrating our product from .NET Core 3.1 to .NET 6.0. While migrating, we noticed some of our unit tests which requires instantiating a new `HubConnectionContext` (a mock one) are failing. The error being thrown is:
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.AspNetCore.SignalR.Core
  StackTrace:
   at Microsoft.AspNetCore.SignalR.HubConnectionContext..ctor(ConnectionContext connectionContext, HubConnectionContextOptions contextOptions, ILoggerFactory loggerFactory)
   at TestProject1.UnitTest1..ctor() in C:\Users\asurroy\source\repos\TestProject1\TestProject1\UnitTest1.cs:line 20
```
The sample project being used in this example is this: https://github.com/Roy19/TestProject

### Expected Behavior

A new `HubConnectionContext` must be created as it was in .NET Core 3.1.

### Steps To Reproduce

- Clone this repo: https://github.com/Roy19/TestProject
- Using Visual Studio 2022 try to run `Test1` in Debug mode.
- You'll see line 20 of `UnitTest1` constructor throwing and error with the message: `Object reference not set to an instance of an object.`

### .NET Version

6.0

### Anything else?

- .NET Sdk: 6.0.101
- OS: Windows 10
- OS Version: 10.0.18363
- IDE: Visual Studio 2022

**Comment by BrennanConroy** [comment]
One issue with Mocks is that they don't honor nullability of properties. Specifically, your mock `ConnectionContext` has a null `Features` property which `HubConnectionContext` tries to access (because it's never null in a real application).

**Comment by Roy19** [comment]
Got it. Changing `ConnectionContext` to a concrete implementation like `DefaultConnectionContext` worked. My guess as to why this worked in .NET Core 3.1 and not in .NET 6.0 was because `ConnectionContext` was not deriving `BaseConnectionContext` in .NET Core 3.1, the later of which has the `Features` property which `HubConnectionContext` tries to access.
Thanks for the help @BrennanConroy.
