### ISSUE TITLE
gRPC H3 benchmarks broken

### ISSUE THREAD

**Issue by sebastienros** [dotnet/aspnetcore#39549]
```
ASP.NET Core gRPC Benchmarks
----------------------------
Args: --LogLevel None --enableCertAuth false --protocol h3
Current directory: /tmp/benchmarks-agent/benchmarks-server-1/ss5jzn2p.l0q/grpc-dotnet/perf/benchmarkapps/GrpcAspNetCoreServer/published
WebHostBuilder loading from: /tmp/benchmarks-agent/benchmarks-server-1/ss5jzn2p.l0q/grpc-dotnet/perf/benchmarkapps/GrpcAspNetCoreServer/published/Microsoft.AspNetCore.Hosting.dll
Address: 127.0.0.1:5000, Protocol: h3
Certificate authentication: False
[STDERR] Unhandled exception. System.InvalidOperationException: Unexpected protocol: h3
[STDERR]    at GrpcAspNetCoreServer.Program.ConfigureListenOptions(ListenOptions listenOptions, IConfigurationRoot config, IPEndPoint endPoint) in /tmp/benchmarks-agent/benchmarks-server-1/ss5jzn2p.l0q/grpc-dotnet/perf/benchmarkapps/GrpcAspNetCoreServer/Program.cs:line 166
[STDERR]    at GrpcAspNetCoreServer.Program.<>c__DisplayClass1_1.<CreateHostBuilder>b__4(ListenOptions listenOptions) in /tmp/benchmarks-agent/benchmarks-server-1/ss5jzn2p.l0q/grpc-dotnet/perf/benchmarkapps/GrpcAspNetCoreServer/Program.cs:line 67
[STDERR]    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.ListenAnyIP(Int32 port, Action`1 configure)
[STDERR]    at GrpcAspNetCoreServer.Program.<>c__DisplayClass1_0.<CreateHostBuilder>b__3(WebHostBuilderContext context, KestrelServerOptions options) in /tmp/benchmarks-agent/benchmarks-server-1/ss5jzn2p.l0q/grpc-dotnet/perf/benchmarkapps/GrpcAspNetCoreServer/Program.cs:line 65
[STDERR]    at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
[STDERR]    at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
[STDERR]    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.CreateServiceContext(IOptions`1 options, ILoggerFactory loggerFactory, DiagnosticSource diagnosticSource)
[STDERR]    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl..ctor(IOptions`1 options, IEnumerable`1 transportFactories, IEnumerable`1 multiplexedFactories, ILoggerFactory loggerFactory, DiagnosticSource diagnosticSource)
[STDERR]    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
[STDERR]    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[STDERR]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
[STDERR]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
[STDERR]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
[STDERR]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
[STDERR]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
[STDERR]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
[STDERR]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
[STDERR]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
[STDERR]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
[STDERR]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
[STDERR]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
[STDERR]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
[STDERR]    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
[STDERR]    at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
[STDERR]    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
[STDERR]    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
[STDERR]    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
[STDERR]    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
[STDERR]    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
[STDERR]    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
[STDERR]    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
[STDERR]    at GrpcAspNetCoreServer.Program.Main(String[] args) in /tmp/benchmarks-agent/benchmarks-server-1/ss5jzn2p.l0q/grpc-dotnet/perf/benchmarkapps/GrpcAspNetCoreServer/Program.cs:line 30

```

**Comment by adityamandaleeka** [comment]
Should be fixed now, PTAL
