### ISSUE TITLE
Blazor component errors are not informative

### ISSUE THREAD

**Issue by brud** [dotnet/aspnetcore#39580]
## Summary

I have a very uninformative error. It doesn't tell me about file or component it's in:
```
Uncaught (in promise) Error: Found malformed component comment at Blazor:{"sequence":0,"type":"server","prerenderId":"dda49ec4a12548b4b3d7e4ada4850ebb","descriptor":"CfDJ8LkkoHhStMpJrzKtdnnAN6DmLH3J1PFx7\u002BPnAfrV9ik0AMp7XkuK9yAK4R43EGMZ626SxCkYWtmg6ASGOaayQR7Ll0YBpgnfIrnSO3KmcftYj32RN/U3LEH7RYpQ0UMAr9d5ih8wpjVFz2abQsM8Q9hcZjp/KaA8G71GbEOyyuy6ucRPhTCQWd3\u002Ba7EcP05NUSLSR9fIDEtyb3DUCBSjawd7VIEbrS4rlMTGAFRGtp4l3uZ4F6MpTzzfixciRvJ6CiLqaPbylaSuZpQG/DFJvgm3Q4R2fjzBV/ZrATW9Noi/cQ5Gw73oq9WtlFTQtc4hhTMPmmKaPVtyiASlrJjvbTGmLCNNT6x0yHhLiwxJxX/D"}
    at jn (blazor.server.js:1:124629)
    at Fn (blazor.server.js:1:122852)
    at Fn (blazor.server.js:1:122888)
    at Fn (blazor.server.js:1:122888)
    at blazor.server.js:1:127422
    at blazor.server.js:1:127594
    at Gn (blazor.server.js:1:127598)
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not expected to happen in customer apps.
The fact that you get such an error indicates that you have some logic which manipulates the HTML DOM (not through Blazor).
Unfortunately, there is not much we can do either without a repro. So if you are convinced that this is not due to that and you can get us a minimal repro we will investigate.

**Comment by SteveSandersonMS** [comment]
The `\u002B` in your error is suspicious. It looks as if something is manipulating the HTML and replacing a `+` character with its unicode equivalent. Since this is inside an HTML comment, that breaks the validity of the document. I'd recommend checking if there is some kind of filtering proxy that's interfering with your responses.
