### ISSUE TITLE
SDK Blazor Hot Reload Test Failure `Run_WithHotReloadEnabled_ReadsLaunchSettings_WhenUsingProjectOption`

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#39657]
Run_WithHotReloadEnabled_ReadsLaunchSettings_WhenUsingProjectOption

`System.Threading.Tasks.TaskCanceledException : A task was canceled.`

```
   at Microsoft.DotNet.Watcher.Tools.AwaitableProcess.GetOutputLineAsync(String predicateName, Predicate`1 predicate, CancellationToken cancellationToken) in /_/src/Tests/dotnet-watch.Tests/Utilities/AwaitableProcess.cs:line 94
   at Microsoft.DotNet.Watcher.Tools.AwaitableProcess.GetOutputLineAsync(String message, TimeSpan timeout) in /_/src/Tests/dotnet-watch.Tests/Utilities/AwaitableProcess.cs:line 79
   at Microsoft.DotNet.Watcher.Tools.DotNetWatcherTests.Run_WithHotReloadEnabled_ReadsLaunchSettings_WhenUsingProjectOption() in /_/src/Tests/dotnet-watch.Tests/DotNetWatcherTests.cs:line 169
--- End of stack trace from previous location ---
```

https://dev.azure.com/dnceng/public/_build/results?buildId=1562638&view=ms.vss-test-web.build-test-results-tab&runId=43985498&resultId=100184&paneView=debug

**Comment by TanayParikh** [comment]
There's a race condition in the test (logs being logged in a slightly different order occasionally than expected). I don't believe this is symptomatic of an underlying issue. I'm skipping the test for now.


Race condition between `Started` and `Environment: Development`.

```
1/20/2022 12:29:35 PM: post: 'watch : Running WatchAppWithLaunchSettings with the following arguments: run'
        1/20/2022 12:29:35 PM: recv: 'watch : Running WatchAppWithLaunchSettings with the following arguments: run'. Does not match condition '[msg == 'Started']'.
        1/20/2022 12:29:35 PM: post: 'watch : Started'
        1/20/2022 12:29:35 PM: post: 'Environment: Development'
        1/20/2022 12:29:35 PM: recv: 'watch : Started'. Does not match condition '[msg == 'Started']'.
        1/20/2022 12:29:35 PM: recv: 'Environment: Development'. Does not match condition '[msg == 'Started']'.
        1/20/2022 12:29:35 PM: post: 'Started'
        1/20/2022 12:29:35 PM: recv: 'Started'. Matches condition '[msg == 'Started']'.
        Waiting for output line [msg == 'Environment: Development']. Will wait for 10 sec.
        1/20/2022 12:29:35 PM: post: 'watch : Process id 1404 ran for 168ms'
        1/20/2022 12:29:35 PM: recv: 'watch : Process id 1404 ran for 168ms'. Does not match condition '[msg == 'Environment: Development']'.
        1/20/2022 12:29:35 PM: post: 'watch : Exited'
        1/20/2022 12:29:35 PM: recv: 'watch : Exited'. Does not match condition '[msg == 'Environment: Development']'.
```

**Comment by TanayParikh** [comment]
@pranavkm any objection of just storing all the logged lines and searching history?

**Comment by pranavkm** [comment]
> any objection with just storing all the logged lines in a list and searching history

Go for it.
