### ISSUE TITLE
WebApplicationFactory<T>.CreateClient() fails when using app.Urls.Add() in minimal api.

### ISSUE THREAD

**Issue by drch-** [dotnet/aspnetcore#39777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A minimal api that uses `app.Urls.Add()` throws an exception when under test with a WebApplicationFactory<T>.  The following example shows a minimal repro.

Removing the `app.Urls.Add()` works fine and the test passes.

```csharp
// Program.cs
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

var port = Environment.GetEnvironmentVariable("PORT") ?? "8080";
app.Urls.Add($"http://0.0.0.0:{port}");

app.MapGet("/", () => "hello world");
app.Run();

public partial class Program { }
```

```csharp
// UnitTest1.cs xunit v2.4.1
[Fact]
public async Task TestAppRunning()
{
    var app = new WebApplicationFactory<Program>();
    var client = app.CreateClient(); // throws InvalidOperationException
    var response = await client.GetAsync("/");
    Assert.Equal(HttpStatusCode.OK, response.StatusCode);
}
```

### Exceptions (if any)

```text
[xUnit.net 00:00:01.02]     test.UnitTest1.TestAppRunning [FAIL]
  Failed test.UnitTest1.TestAppRunning [94 ms]
  Error Message:
   System.InvalidOperationException : IServerAddressesFeature could not be found.
  Stack Trace:
     at Microsoft.AspNetCore.Builder.WebApplication.get_Urls()
   at Program.<Main>$(String[] args) in Program.cs:line 5
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Testing.DeferredHostBuilder.DeferredHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Start(IHost host)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateHost(IHostBuilder builder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.ConfigureHostBuilder(IHostBuilder hostBuilder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.EnsureServer()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(DelegatingHandler[] handlers)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(Uri baseAddress, DelegatingHandler[] handlers)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient(WebApplicationFactoryClientOptions options)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient()
   at test.UnitTest1.TestAppRunning() in UnitTest1.cs:line 23
--- End of stack trace from previous location ---
```

### .NET Version

6.0.101

### Anything else?

.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     debian
 OS Platform: Linux
 RID:         linux-x64

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  6.0.101

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1
  Microsoft.NETCore.App 6.0.1

**Comment by Caleb9** [comment]
Customizing the application URL via `WebApplication.RunAsync(string? url)` does not work either:

`System.InvalidOperationException: Changing the URL is not supported because no valid IServerAddressesFeature was found.`

Seems related?

**Comment by halter73** [comment]
@Caleb9 I think you're right. I think the easiest and best fix will be to add a mock `IServerAddressesFeature` to [TestServer.Features](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.testhost.testserver.features?view=aspnetcore-6.0). It would probably no-op, but it would prevent the `InvalidOperationException` in `WebApplication.Urls`. I'd accept a PR doing that with some basic tests if someone would like to help.
