### ISSUE TITLE
Error unprotecting the session cookie

### ISSUE THREAD

**Issue by bbhxwl** [dotnet/aspnetcore#39807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

How can I avoid restarting the program? Old users always prompt this error when visiting the website?

[40m[1m[33mwarn[39m[22m[49m: Microsoft.AspNetCore.Session.SessionMiddleware[7]
      Error unprotecting the session cookie.
System.Security.Cryptography.CryptographicException: The key {5a28e1bf-f23b-40a4-a491-946d30aada50} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Session.CookieProtection.Unprotect(IDataProtector protector, String protectedText, ILogger logger)

**Comment by blowdart** [comment]
Please share your startup.cs - this generally happens if you're not setting up data protection to save the keys

**Comment by Tratcher** [comment]
https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-6.0

**Comment by bbhxwl** [comment]
> Please share your startup.cs - this generally happens if you're not setting up data protection to save the keys

```
using InnoADLMedicalWeb.Areas.KePuBox.Controllers;
using InnoADLMedicalWeb.Areas.SportsDoctorAPI.Controllers;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.HttpOverrides;
using Microsoft.AspNetCore.StaticFiles;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Encodings.Web;
using System.Text.Unicode;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using Microsoft.OpenApi.Models;
using System.Reflection;
using System.IO;
using InnoADLMedicalWeb.Code.Hub;

namespace InnoADLMedicalWeb
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddSignalR();
            services.AddSession((options) =>
            {
                // 设置 Session 过期时间
                options.IdleTimeout = TimeSpan.FromHours(24);
            });
            services.AddHttpContextAccessor();
            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
            services.AddCors(op =>
            {
                op.AddPolicy("AllowAll", builder =>
                {
                    builder.SetIsOriginAllowed(_ => true).AllowAnyMethod().AllowAnyHeader().AllowCredentials();
                });
            });

            //services.AddCors(c =>

            //  c.AddPolicy("AllowAll", p =>
            //  {
            //      p.AllowAnyOrigin();
            //      p.AllowAnyMethod();
            //      p.AllowAnyHeader();
            //  })
            //  );

            // 添加Swagger
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo
                {
                    Title = "API",
                    Version = "v1",
                    Contact = new OpenApiContact()
                    {
                        Name = "binbin",
                        Email = "admin@bbhxwl.com"
                    }
                });
                c.SwaggerDoc("unity", new OpenApiInfo
                {
                    Title = "API",
                    Version = "v1",
                });
                try
                {
                    // 获取xml文件名
                    var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
                    // 获取xml文件路径
                    var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
                    // 添加控制器层注释，true表示显示控制器注释
                    c.IncludeXmlComments(xmlPath, true);
                }
                catch (Exception)
                {

                }
            });
            services.AddControllersWithViews().AddNewtonsoftJson(options =>
            {

                options.SerializerSettings.ContractResolver = new DefaultContractResolver();
                options.SerializerSettings.DateTimeZoneHandling = DateTimeZoneHandling.Utc;  // 设置时区为 UTC)
                options.SerializerSettings.DateFormatString = "yyyy-MM-dd HH:mm:ss";
            }).AddJsonOptions(config =>
            {
                config.JsonSerializerOptions.PropertyNamingPolicy = null;
            });

            services.AddRazorPages().AddRazorRuntimeCompilation();

        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            //app.UseWebSockets();
            app.UseCors("AllowAll");
            app.UseStaticFiles();
            app.UseForwardedHeaders(new ForwardedHeadersOptions
            {
                ForwardedHeaders = ForwardedHeaders.XForwardedFor |
            ForwardedHeaders.XForwardedProto
            });
            app.UseRouting();
            app.UseSession();
            app.UseAuthorization();
           
            // Enable middleware to serve generated Swagger as a JSON endpoint.
            app.UseSwagger();
            app.UseSwaggerUI(c =>
            {
                if (!env.IsDevelopment())
                {
                    c.InjectStylesheet("/css/swaggercustom.css");
                }
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "EnterpriseAPI");
                c.SwaggerEndpoint("/swagger/unity/swagger.json", "unity");
            });
           
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapAreaControllerRoute("areas", "AgentManage", "{area:exists}/{controller=Login}/{action=Index}/{id?}");
                endpoints.MapAreaControllerRoute("areas", "KePuBox", "{area:exists}/{controller=Login}/{action=Index}/{id?}");
                endpoints.MapAreaControllerRoute("areas", "SportsDoctorAPI", "{area:exists}/{controller=Home}/{action=Index}/{id?}");
                endpoints.MapAreaControllerRoute("areas", "ResourceCenter", "{area:exists}/{controller=ResourceList}/{action=Index}/{id?}");
                endpoints.MapAreaControllerRoute("areas", "api", "{area:exists}/{controller=Home}/{action=Index}/{id?}");
                endpoints.MapAreaControllerRoute("areas", "EnterpriseAPI", "{area:exists}/{controller=Home}/{action=Index}/{id?}");

                endpoints.MapHub<TongXunHub>("/TongXunHub");
                endpoints.MapHub<ForwardMessageHub>("/ForwardMessageHub");
                endpoints.MapHub<KePuBoxOnlineUser>("/KePuBoxOnlineUser");
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=chart}/{action=Index}/{id?}");
            });
        }
    }
}

```

**Comment by Tratcher** [comment]
Please follow the instructions from https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-6.0 to save your encryption keys somewhere stable so they'll be available when the app reboots.

**Comment by bbhxwl** [comment]
> Please follow the instructions from https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-6.0 to save your encryption keys somewhere stable so they'll be available when the app reboots.

I've seen it. I'm not sure which line of code works.

services.AddDataProtection().ProtectKeysWithCertificate("123");    ？
Or another way of thinking, how can I ignore these error messages? Don't let him output

**Comment by Tratcher** [comment]
You need the PersistKeysTo* APIs to store the keys somewhere stable.

**Comment by bbhxwl** [comment]
![image](https://user-images.githubusercontent.com/26525599/153800682-546d9911-4aef-48e3-8d86-b2718824be13.png)
Or how can I cancel this error output? I have too many log files. This error. How do I cancel?
