### ISSUE TITLE
Error "Server timeout elapsed without receiving a message" while calling the invoke method of signalr hubconnection

### ISSUE THREAD

**Issue by ZhibingGe** [dotnet/aspnetcore#39811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If I open the devtools of browser, the invoke method of signalr connection will always throw the timeout error. 
If I don't open the devtools, the invoke method can receive response message.
C# code about hub:

```
public class SettingHub : Hub
{
    public string GetData()
    {
        return "hello world";
    }
}
```

Typescript code:
```
import { Injectable } from '@angular/core';
import * as signalR from '@microsoft/signalr';
@Injectable({
  providedIn: 'root'
})
export class SignalrService {
  private hubConnection: signalR.HubConnection;
  constructor() { 
    this.hubConnection = new signalR.HubConnectionBuilder()
      .withUrl("http://localhost:5000/hub/setting")
      .configureLogging(signalR.LogLevel.Trace)
      .build();
    this.hubConnection.start().then(()=>{
      setInterval(()=>{
        this.getData();
      },6000)
    })
  }

  getData(){
    console.error("get data");
    this.hubConnection.invoke("getData").then(data=>{
      console.error(data);
    }).catch(err=>console.error(err));
  }
}
```

### Expected Behavior

The invoke method can get response message.

### Steps To Reproduce

- Run client with browser, and open devtools of browser
- Run signarl server 
- Refresh the browser to build hubconnection

### Exceptions (if any)

 [2022-01-27T08:51:13.283Z] Error: Connection disconnected with error 'Error: Server timeout elapsed without receiving a message from the server.'.
![image](https://user-images.githubusercontent.com/20542751/151326688-05b7aeea-0c9b-44a9-8d12-e6dcc8a76b75.png)

### .NET Version

6.0.200

### Anything else?

![image](https://user-images.githubusercontent.com/20542751/151326633-521a2e6e-4479-4fc0-94a1-bddc8a892f00.png)

**Comment by ZhibingGe** [comment]
Use chrome, it is ok
The bug occurred when using microsoft.edge

**Comment by BrennanConroy** [comment]
Does this happen all the time?
Are you running the server under a debugger?
Can you share Trace level server logs that show the SignalR connection? https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-6.0#server-side-logging

**Comment by dani2221** [comment]
Can you check if maybe you have set network throttling and that's why it doesn't work when you open dev tools? I have the same issue with throttled connections. Related: #39885

**Comment by nrmtmt** [comment]
I have same issues, server seems work correctly:
   ```
   SPA proxy is ready. Redirecting to https://localhost:44440.
dbug: Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager[1]
      New connection ctA6QHwS4fvVGcufYvtlAA created.
dbug: Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher[10]
      Sending negotiation response.
dbug: Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher[4]
      Establishing new connection.
dbug: Microsoft.AspNetCore.SignalR.HubConnectionHandler[5]
      OnConnectedAsync started.
dbug: Microsoft.AspNetCore.SignalR.Internal.DefaultHubProtocolResolver[2]
      Found protocol implementation for requested protocol: json.
dbug: Microsoft.AspNetCore.SignalR.HubConnectionContext[1]
      Completed connection handshake. Using HubProtocol 'json'.
connected!! ctA6QHwS4fvVGcufYvtlAA
```

and here are logs from js client:
```
Utils.ts:194 [2022-02-03T18:40:17.568Z] Debug: Starting HubConnection.
Utils.ts:194 [2022-02-03T18:40:17.568Z] Debug: Starting connection with transfer format 'Text'.
Utils.ts:194 [2022-02-03T18:40:17.576Z] Debug: Sending negotiation request: https://localhost:44440/hubs/order/negotiate?negotiateVersion=1.
Utils.ts:194 [2022-02-03T18:40:21.741Z] Debug: Skipping transport 'WebSockets' because it was disabled by the client.
Utils.ts:194 [2022-02-03T18:40:21.742Z] Debug: Selecting transport 'ServerSentEvents'.
Utils.ts:194 [2022-02-03T18:40:21.742Z] Trace: (SSE transport) Connecting.
Utils.ts:190 [2022-02-03T18:40:25.857Z] Information: SSE connected to https://localhost:44440/hubs/order?id=fxqgKpJnF5Dq5MX-RCfXcg
Utils.ts:194 [2022-02-03T18:40:25.857Z] Debug: The HttpConnection connected successfully.
Utils.ts:194 [2022-02-03T18:40:25.857Z] Debug: Sending handshake request.
Utils.ts:194 [2022-02-03T18:40:25.858Z] Trace: (SSE transport) sending data. String data of length 32.
Utils.ts:194 [2022-02-03T18:40:29.969Z] Trace: (SSE transport) request complete. Response status: 200.
Utils.ts:190 [2022-02-03T18:40:29.978Z] Information: Using HubProtocol 'json'.
Utils.ts:194 [2022-02-03T18:40:59.997Z] Debug: HttpConnection.stopConnection(undefined) called while in state Disconnecting.
index.js:1 [2022-02-03T18:40:59.997Z] Error: Connection disconnected with error 'Error: Server timeout elapsed without receiving a message from the server.'.
console.<computed> @ index.js:1
Utils.ts:194 [2022-02-03T18:40:59.997Z] Debug: HubConnection.connectionClosed(Error: Server timeout elapsed without receiving a message from the server.) called while in state Connecting.
Utils.ts:194 [2022-02-03T18:40:59.997Z] Debug: Hub handshake failed with error 'Error: Server timeout elapsed without receiving a message from the server.' during start(). Stopping HubConnection.
Utils.ts:194 [2022-02-03T18:40:59.997Z] Debug: Call to HttpConnection.stop(Error: Server timeout elapsed without receiving a message from the server.) ignored because the connection is already in the disconnected state.
Utils.ts:194 [2022-02-03T18:40:59.997Z] Debug: HubConnection failed to start successfully because of error 'Error: Server timeout elapsed without receiving a message from the server.'.
```

here is stackoverflow post with more details:
https://stackoverflow.com/questions/70976850/signalr-js-client-is-not-able-to-start-connection-even-if-logs-are-showing-that

**Comment by BrennanConroy** [comment]
SSE often has issues when you host your app behind a proxy that buffers responses. You should check your proxies config to see if it's doing that.

> Skipping transport 'WebSockets' because it was disabled by the client.

It also looks like you're explicitly not using WebSockets which is a bit odd, you should try using WebSockets or LongPolling and see if those work for you.

**Comment by ZhibingGe** [comment]
> Does this happen all the time? Are you running the server under a debugger? Can you share Trace level server logs that show the SignalR connection? https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-6.0#server-side-logging

When using Microsoft Edge browser, it happens all the time.  And the log from server side seems ok, In debug mode, the server has executed invoked method and return related info. The trace please see @nrmtmt comments.

**Comment by BrennanConroy** [comment]
Provide a minimal app as a GitHub repo that reproduces the issue and share the version of Edge you see the problem in.

**Comment by ZhibingGe** [comment]
Works on the latest MicrosoftEdge version(V98.0.1108.50)

**Comment by enricop** [comment]
Hi all.
We have a similar issue with "@microsoft/signalr" version 6.0.2.

With Firefox everything is working fine.

The client connection to the server hub is _pending_ and does not complete using Chrome/Edge. The `onConnectedAsync()` hub side method is never called with Chrome/Edge.

After several seconds with Chrome/Edge we have these errors:

```
[2022-02-24T11:24:02.198Z] Information: (WebSockets transport) There was an error with the transport.
Utils.ts:203 [2022-02-24T11:24:02.200Z] Debug: Selecting transport 'ServerSentEvents'.
Utils.ts:203 [2022-02-24T11:24:02.200Z] Debug: Sending negotiation request: http://localhost:3000/hubs/ServerMain/negotiate?negotiateVersion=1.
Utils.ts:199 [2022-02-24T11:24:02.765Z] Information: SSE connected to http://localhost:3000/hubs/ServerMain?id=qEUAL9udTL6xBi58yBS2Bg
Utils.ts:203 [2022-02-24T11:24:02.766Z] Debug: The HttpConnection connected successfully.
Utils.ts:203 [2022-02-24T11:24:02.766Z] Debug: Sending handshake request.
Utils.ts:199 [2022-02-24T11:24:02.855Z] Information: Using HubProtocol 'json'.
Utils.ts:203 [2022-02-24T11:24:33.271Z] Debug: HttpConnection.stopConnection(undefined) called while in state Disconnecting.
Utils.ts:203 [2022-02-24T11:24:33.272Z] Debug: HubConnection.connectionClosed(Error: Server timeout elapsed without receiving a message from the server.) called while in state Connecting.
Utils.ts:203 [2022-02-24T11:24:33.272Z] Debug: Hub handshake failed with error 'Error: Server timeout elapsed without receiving a message from the server.' during start(). Stopping HubConnection.
Utils.ts:203 [2022-02-24T11:24:33.272Z] Debug: Call to HttpConnection.stop(Error: Server timeout elapsed without receiving a message from the server.) ignored because the connection is already in the disconnected state.
Utils.ts:203 [2022-02-24T11:24:33.273Z] Debug: HubConnection failed to start successfully because of error 'Error: Server timeout elapsed without receiving a message from the server.'.
useServerMainHub.tsx:29 errore Error: Server timeout elapsed without receiving a message from the server.
    at HubConnection.serverTimeout (HubConnection.ts:671:1)
    at HubConnection.ts:640:1
```

Any ideas?
Thanks for your support

**Comment by NinjaCross** [comment]
I can confirm this behaviour impact also Chrome, in applications compiled for NET 5.0, running on a machine having both NET 5.0 and NET 6.0 installed.

These are the versions of SignalR JS client where we are experiencing the problem:

- "@aspnet/signalr": "1.1.4"
- "@aspnet/signalr": "1.0.27"

There are the installed frameworks

![image](https://user-images.githubusercontent.com/5829421/158606117-d00edaee-c671-483a-93f8-c19b5c76bc0d.png)

Our application is using these NuGet packages (i took out from the list the non-relevant ones):

```
   [net5.0]: 
   Top-level Package                                            Requested        Resolved     
   > Microsoft.AspNet.WebApi.Client                             5.2.7            5.2.7         
   > Microsoft.AspNetCore.Authentication.JwtBearer              5.*              5.0.15        
   > Microsoft.AspNetCore.Identity                              2.2.0            2.2.0         
   > Microsoft.AspNetCore.Mvc.NewtonsoftJson                    5.*              5.0.15        
   > Microsoft.AspNetCore.OData                                 7.5.0            7.5.0         
   > Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson      5.*              5.0.15        
   > Microsoft.Bcl.AsyncInterfaces                              5.*              5.0.0         
   > Microsoft.CodeAnalysis.FxCopAnalyzers                      3.3.1            3.3.1         
   > Microsoft.Extensions.Caching.Memory                        5.*              5.0.0         
   > Microsoft.Extensions.DependencyInjection.Abstractions      5.*              5.0.0         
   > Microsoft.Extensions.Hosting.WindowsServices               5.*              5.0.1         
   > Microsoft.Extensions.Logging                               5.*              5.0.0         
   > Microsoft.Extensions.Logging.Log4Net.AspNetCore            5.*              5.0.4         
   > Microsoft.IdentityModel.Tokens                             6.*              6.16.0        
   > Microsoft.OData.Core                                       7.9.0            7.9.0         
   > Microsoft.OData.Edm                                        7.9.0            7.9.0         
   > Microsoft.VisualStudio.Threading.Analyzers                 16.*             16.10.56      
  
   Transitive Package                                                                   Resolved  
   > AspNetCore.HealthChecks.SqlServer                                                  3.2.0     
   > AspNetCore.HealthChecks.UI                                                         3.1.3     
   > AspNetCore.HealthChecks.UI.Client                                                  3.1.2     
   > AspNetCore.HealthChecks.UI.Core                                                    3.1.3     
   > AspNetCore.HealthChecks.UI.SqlServer.Storage                                       3.1.2     
   > Microsoft.AspNetCore.Authentication                                                2.2.0     
   > Microsoft.AspNetCore.Authentication.Abstractions                                   2.2.0     
   > Microsoft.AspNetCore.Authentication.Cookies                                        2.2.0     
   > Microsoft.AspNetCore.Authentication.Core                                           2.2.0     
   > Microsoft.AspNetCore.Authorization                                                 2.2.0     
   > Microsoft.AspNetCore.Connections.Abstractions                                      5.0.15    
   > Microsoft.AspNetCore.Cryptography.Internal                                         2.2.0     
   > Microsoft.AspNetCore.Cryptography.KeyDerivation                                    2.2.0     
   > Microsoft.AspNetCore.DataProtection                                                2.2.0     
   > Microsoft.AspNetCore.DataProtection.Abstractions                                   2.2.0     
   > Microsoft.AspNetCore.Hosting.Abstractions                                          2.2.0     
   > Microsoft.AspNetCore.Hosting.Server.Abstractions                                   2.2.0     
   > Microsoft.AspNetCore.Http                                                          2.2.0     
   > Microsoft.AspNetCore.Http.Abstractions                                             2.2.0     
   > Microsoft.AspNetCore.Http.Connections.Client                                       5.0.15    
   > Microsoft.AspNetCore.Http.Connections.Common                                       5.0.15    
   > Microsoft.AspNetCore.Http.Extensions                                               2.2.0     
   > Microsoft.AspNetCore.Http.Features                                                 5.0.15    
   > Microsoft.AspNetCore.HttpsPolicy                                                   2.2.0     
   > Microsoft.AspNetCore.JsonPatch                                                     5.0.15    
   > Microsoft.AspNetCore.SignalR.Client                                                5.0.15    
   > Microsoft.AspNetCore.SignalR.Client.Core                                           5.0.15    
   > Microsoft.AspNetCore.SignalR.Common                                                5.0.15    
   > Microsoft.AspNetCore.SignalR.Core                                                  1.1.0     
   > Microsoft.AspNetCore.SignalR.Protocols.Json                                        5.0.15    
   > Microsoft.AspNetCore.WebUtilities                                                  2.2.0     
   > Microsoft.Extensions.Caching.Abstractions                                          5.0.0     
   > Microsoft.Extensions.Configuration                                                 5.0.0     
   > Microsoft.Extensions.Configuration.Abstractions                                    5.0.0     
   > Microsoft.Extensions.Configuration.Binder                                          5.0.0     
   > Microsoft.Extensions.Configuration.CommandLine                                     5.0.0     
   > Microsoft.Extensions.Configuration.EnvironmentVariables                            5.0.0     
   > Microsoft.Extensions.Configuration.FileExtensions                                  5.0.0     
   > Microsoft.Extensions.Configuration.Json                                            5.0.0     
   > Microsoft.Extensions.Configuration.UserSecrets                                     5.0.0     
   > Microsoft.Extensions.DependencyInjection                                           5.0.2     
   > Microsoft.Extensions.DependencyModel                                               3.1.3     
   > Microsoft.Extensions.Diagnostics.HealthChecks                                      3.1.12    
   > Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions                         5.0.15    
   > Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore                  3.1.12    
   > Microsoft.Extensions.FileProviders.Abstractions                                    5.0.0     
   > Microsoft.Extensions.FileProviders.Physical                                        5.0.0     
   > Microsoft.Extensions.FileSystemGlobbing                                            5.0.0     
   > Microsoft.Extensions.Hosting                                                       5.0.0     
   > Microsoft.Extensions.Hosting.Abstractions                                          5.0.0     
   > Microsoft.Extensions.Http                                                          5.0.0     
   > Microsoft.Extensions.Http.Polly                                                    5.0.1     
   > Microsoft.Extensions.Identity.Core                                                 2.2.0     
   > Microsoft.Extensions.Logging.Abstractions                                          5.0.0     
   > Microsoft.Extensions.Logging.Configuration                                         5.0.0     
   > Microsoft.Extensions.Logging.Console                                               5.0.0     
   > Microsoft.Extensions.Logging.Debug                                                 5.0.0     
   > Microsoft.Extensions.Logging.EventLog                                              5.0.0     
   > Microsoft.Extensions.Logging.EventSource                                           5.0.0     
   > Microsoft.Extensions.ObjectPool                                                    5.0.10    
   > Microsoft.Extensions.Options                                                       5.0.0     
   > Microsoft.Extensions.Options.ConfigurationExtensions                               5.0.0     
   > Microsoft.Extensions.Primitives                                                    5.0.1     
   > Microsoft.Extensions.WebEncoders                                                   2.2.0     
   > Microsoft.Identity.Client                                                          4.14.0    
   > Microsoft.IdentityModel.JsonWebTokens                                              6.7.1     
   > Microsoft.IdentityModel.Logging                                                    6.16.0    
   > Microsoft.IdentityModel.Protocols                                                  6.7.1     
   > Microsoft.IdentityModel.Protocols.OpenIdConnect                                    6.7.1    
   > Microsoft.OpenApi                                                                  1.2.3     
   > Microsoft.Rest.ClientRuntime                                                       2.3.10    
   > Microsoft.Spatial                                                                  7.9.0     
   > Microsoft.TestPlatform.ObjectModel                                                 16.11.0   
   > Microsoft.TestPlatform.TestHost                                                    16.11.0   
   > Microsoft.Win32.Primitives                                                         4.0.1     
   > Microsoft.Win32.Registry                                                           5.0.0     
   > Microsoft.Win32.SystemEvents                                                       5.0.0     
   > NETStandard.Library                                                                2.0.0    
   > System.Buffers                                                                     4.5.0     
   > System.CodeDom                                                                     4.7.0     
   > System.Collections                                                                 4.3.0     
   > System.Collections.Concurrent                                                      4.3.0     
   > System.Collections.Immutable                                                       5.0.0     
   > System.Collections.NonGeneric                                                      4.3.0     
   > System.Collections.Specialized                                                     4.3.0     
   > System.ComponentModel                                                              4.3.0     
   > System.ComponentModel.Annotations                                                  5.0.0     
   > System.ComponentModel.Primitives                                                   4.3.0     
   > System.ComponentModel.TypeConverter                                                4.3.0     
   > System.Data.OleDb                                                                  5.0.0     
   > System.Data.SqlClient                                                              4.8.2     
   > System.Diagnostics.Debug                                                           4.3.0     
   > System.Diagnostics.DiagnosticSource                                                5.0.1     
   > System.Diagnostics.EventLog                                                        5.0.0     
   > System.Diagnostics.PerformanceCounter                                              5.0.0     
   > System.Diagnostics.Tools                                                           4.3.0     
   > System.Diagnostics.TraceSource                                                     4.0.0     
   > System.Diagnostics.Tracing                                                         4.3.0     
   > System.DirectoryServices                                                           5.0.0     
   > System.DirectoryServices.Protocols                                                 5.0.1     
   > System.Drawing.Common                                                              5.0.0     
   > System.Dynamic.Runtime                                                             4.3.0     
   > System.Formats.Asn1                                                                5.0.0     
   > System.Globalization                                                               4.3.0     
   > System.Globalization.Calendars                                                     4.3.0     
   > System.Globalization.Extensions                                                    4.3.0     
   > System.IdentityModel.Tokens.Jwt                                                    6.7.1     
   > System.IO                                                                          4.3.0     
   > System.IO.FileSystem                                                               4.3.0     
   > System.IO.FileSystem.AccessControl                                                 5.0.0     
   > System.IO.FileSystem.Primitives                                                    4.3.0     
   > System.IO.Pipelines                                                                5.0.2     
   > System.Linq                                                                        4.3.0     
   > System.Linq.Expressions                                                            4.3.0     
   > System.Memory                                                                      4.5.3     
   > System.Net.Http                                                                    4.3.4     
   > System.Net.NameResolution                                                          4.3.0     
   > System.Net.Primitives                                                              4.3.0     
   > System.Numerics.Vectors                                                            4.5.0     
   > System.ObjectModel                                                                 4.3.0     
   > System.Private.DataContractSerialization                                           4.3.0     
   > System.Private.ServiceModel                                                        4.9.0     
   > System.Private.Uri                                                                 4.3.2     
   > System.Reflection                                                                  4.3.0     
   > System.Reflection.DispatchProxy                                                    4.7.1     
   > System.Reflection.Emit                                                             4.7.0     
   > System.Reflection.Emit.ILGeneration                                                4.3.0     
   > System.Reflection.Emit.Lightweight                                                 4.3.0     
   > System.Reflection.Extensions                                                       4.3.0     
   > System.Reflection.Metadata                                                         1.6.0     
   > System.Reflection.Primitives                                                       4.3.0     
   > System.Reflection.TypeExtensions                                                   4.3.0     
   > System.Resources.ResourceManager                                                   4.3.0     
   > System.Runtime                                                                     4.3.0     
   > System.Runtime.Caching                                                             4.7.0     
   > System.Runtime.CompilerServices.Unsafe                                             4.6.0     
   > System.Runtime.Extensions                                                          4.3.0     
   > System.Runtime.Handles                                                             4.3.0     
   > System.Runtime.InteropServices                                                     4.3.0     
   > System.Runtime.Loader                                                              4.3.0     
   > System.Runtime.Numerics                                                            4.3.0     
   > System.Runtime.Serialization.Formatters                                            4.3.0     
   > System.Runtime.Serialization.Json                                                  4.3.0     
   > System.Runtime.Serialization.Primitives                                            4.3.0     
   > System.Security.AccessControl                                                      5.0.0     
   > System.Security.Cryptography.Algorithms                                            4.3.0     
   > System.Security.Cryptography.Cng                                                   5.0.0     
   > System.Security.Cryptography.Csp                                                   4.3.0     
   > System.Security.Cryptography.Encoding                                              4.3.0     
   > System.Security.Cryptography.OpenSsl                                               4.3.0     
   > System.Security.Cryptography.Pkcs                                                  5.0.0     
   > System.Security.Cryptography.Primitives                                            4.3.0     
   > System.Security.Cryptography.ProtectedData                                         5.0.0     
   > System.Security.Cryptography.X509Certificates                                      4.3.0     
   > System.Security.Cryptography.Xml                                                   5.0.0     
   > System.Security.Permissions                                                        5.0.0     
   > System.Security.Principal.Windows                                                  5.0.0     
   > System.Security.SecureString                                                       4.3.0     
   > System.ServiceModel.Primitives                                                     4.9.0     
   > System.ServiceProcess.ServiceController                                            5.0.0     
   > System.Text.Encoding                                                               4.3.0     
   > System.Text.Encoding.CodePages                                                     4.7.0     
   > System.Text.Encoding.Extensions                                                    4.3.0     
   > System.Text.Encodings.Web                                                          4.6.0     
   > System.Text.Json                                                                   4.7.2     
   > System.Text.RegularExpressions                                                     4.3.0     
   > System.Threading                                                                   4.3.0     
   > System.Threading.Channels                                                          5.0.0     
   > System.Threading.Tasks                                                             4.3.0     
   > System.Threading.Tasks.Extensions                                                  4.3.0     
   > System.Threading.Thread                                                            4.0.0     
   > System.ValueTuple                                                                  4.5.0     
   > System.Windows.Extensions                                                          5.0.0     
   > System.Xml.ReaderWriter                                                            4.3.0     
   > System.Xml.XDocument                                                               4.3.0     
   > System.Xml.XmlDocument                                                             4.3.0     
   > System.Xml.XmlSerializer                                                           4.3.0     
```
