### ISSUE TITLE
Unexpected exception using WsFederation authentication with React SPA template

### ISSUE THREAD

**Issue by summitabrown** [dotnet/aspnetcore#39896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am receiving the attached exception while using the below snippet of code from the following guide [https://docs.microsoft.com/en-us/aspnet/core/security/authentication/ws-federation?view=aspnetcore-6.0](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/ws-federation?view=aspnetcore-6.0)

I am using the react SPA project template and added in this authentication logic. The goal is to use ADFS authentication with a react .net core app.

The exception occurs only if I try to add authorization to the app. Commenting out the following line makes the error go away. I have custom authorization that I have built out using a custom authorization requirements and a custom policy builder. The goal is to be able to use claims that come back from the ADFS call to apply Authorization to endpoints, etc..

`app.UseAuthorization();`

Here is the snippet from Program.cs file.
```
builder.Services.AddAuthentication(sharedOptions =>
{
    sharedOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
    sharedOptions.DefaultChallengeScheme = WsFederationDefaults.AuthenticationScheme;
})
.AddWsFederation(options =>
{
    // MetadataAddress represents the Active Directory instance used to authenticate users.
    options.MetadataAddress = "https://{{company domain}}/adfs/ls/";

    // Wtrealm is the app's identifier in the Active Directory instance.
    // For ADFS, use the relying party's identifier, its WS-Federation Passive protocol URL:
    options.Wtrealm = "https://localhost:7092";

    // For AAD, use the Application ID URI from the app registration's Overview blade:
    //options.Wtrealm = "api://bbd35166-7c13-49f3-8041-9551f2847b69";
})
.AddCookie();
```

### Expected Behavior

I expect the web api to not exception on every request.

### Steps To Reproduce

Use react SPA Microsoft project template and add in WsFederation snippet.

### Exceptions (if any)

`System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'System.String'.
   at Microsoft.IdentityModel.Protocols.ConfigurationManager 1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.AspNetCore.Authentication.WsFederation.WsFederationHandler.HandleChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler 1.ChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

### .NET Version

6

**Comment by Tratcher** [comment]
"https://{{company domain}}/adfs/ls/";` isn't accessible from your machine. Have you debugged to make sure it resolves to a valid value? Can you navigate there in a browser? Is there a proxy between the server that machine?

**Comment by summitabrown** [comment]
> "https://{{company domain}}/adfs/ls/";` isn't accessible from your machine. Have you debugged to make sure it resolves to a valid value? Can you navigate there in a browser? Is there a proxy between the server that machine?

Sorry, I just have mentioned it. I just redacted my company adfs url and put in that placeholder for obvious reasons. The authentication works fine without `app.UseAuthorization();` so I know that URL is good.

**Comment by Tratcher** [comment]
That InvalidOperationException says it can't contact your metadata server.

> The authentication works fine without `app.UseAuthorization();` so it is valid

How can you tell? Without UseAuthorization Authentication is unlikely to trigger.
