### ISSUE TITLE
Connecting a Blazor Client app to an Azure Service Bus?

### ISSUE THREAD

**Issue by dkboon01** [dotnet/aspnetcore#39908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I try to create a client to azure service bus message queue, I get this error crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: System.Security.Cryptography.Algorithms is not supported on this platform.
System.PlatformNotSupportedException: System.Security.Cryptography.Algorithms is not supported on this platform.
   at System.Security.Cryptography.HMACSHA256..ctor(Byte[] key)
   at Azure.Messaging.ServiceBus.Authorization.SharedAccessSignature.BuildSignature(String audience, String sharedAccessKeyName, String sharedAccessKey, DateTimeOffset expirationTime)
   at Azure.Messaging.ServiceBus.Authorization.SharedAccessSignature..ctor(String serviceBusResource, String sharedAccessKeyName, String sharedAccessKey, Nullable`1 signatureValidityDuration)
   at Azure.Messaging.ServiceBus.ServiceBusConnection..ctor(String connectionString, ServiceBusClientOptions options)
   at Azure.Messaging.ServiceBus.ServiceBusClient..ctor(String connectionString, ServiceBusClientOptions options)
   at Azure.Messaging.ServiceBus.ServiceBusClient..ctor(String connectionString)
   at ABCBlazor.ServiceBusReceiver.SBReceiverConnect() in C:\Users\dboone\source\repos\ABCApps\ABCBlazor\ServiceBusReceiver.cs:line 16
   at ABCBlazor.Pages.Test.ReadServiceBus() in C:\Users\dboone\source\repos\ABCApps\ABCBlazor\Pages\Test.razor:line 11
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

### Expected Behavior

Is there another security package besides System.Security.Cryptography.Algorithms that I can use to make this connection or a different work around to get messages from the Azure Service Bus?

### .NET Version

6.0.101

**Comment by javiercn** [comment]
@dkboon01 thanks for contacting us.

It seems that you are trying to use an API that likely involves credentials, so I would first point out that using credentials on the browser is normally not ok, unless those credentials have been acquired by the browser (for example, an access token). If you are using some sort of API key or similar to connect to the service, you shouldn't be doing that in the first place as you are disclosing that secret to anyone with access to the app (and you should instead do it through a server).

That said, the error that you are seeing is caused by the library making use of an unsupported cryptographic API on the wasm version of the runtime. I'm transferring this to the runtime repo so that they can further help you.
