### ISSUE TITLE
OutOfMemoryException caused by user-code in ASP.NET Core runtime

### ISSUE THREAD

**Issue by dave-yotta** [dotnet/aspnetcore#39913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There appears to be a global try/catch in some places inside ASP.NET Core.  When allocating too much ram such that the CLR throws OutOfMemoryException, this can strike inside the ASP runtime code.  Such errors are not passed to error filters, so I am unable to decide to dump and terminate the process for example, as I would if chance would have it raised in the offending endpoint user code instead.

### Expected Behavior

It should be possible for the user to handle such exceptions, and for example to not leave the application in a dangerous state.

### Steps To Reproduce

Write a endpoint that allocates a lot of static memory and call it a few times.

### .NET Version

3.1.416

**Comment by javiercn** [comment]
@dave-yotta thanks for contacting us.

OutOfMemoryExceptions can't be caught by the runtime. As you point out, this happens in user code, and its the developer responsibility to make sure that it doesn't happen in their code.

**Comment by dave-yotta** [comment]
@javiercn OOM is being caused by user code by allocating near the GC heap limits, but the OOM is being **thrown** inside the asp.net runtime.  OOM errors are like this as I'm sure you're aware, when you get close to the GC heap limit, any allocation on any thread is liable to throw OOM - including ASP runtime methods disconnected from user code.  

I can run again and get you some examples,  but what I saw in the logs was something like "Unexpected error in pipeline\nSystem.OutOfMemoryException...".  This is of course raised in random parts of the code, sometimes user, sometimes runtime. 

It was displayed in the logs, not raised or handled by user code, and the process did not exit - hence my report that the runtime must be catching and ignoring these.

**Comment by dave-yotta** [comment]
> its the developer responsibility to make sure that it doesn't happen in their code
Also, sadly we're not this perfect :D  What we need for example is for the application to terminate so we can get a crash report and fix it :)

**Comment by javiercn** [comment]
@dave-yotta unfortunately, by the time an OOM exception is thrown it's too late to do anything. There are certain exceptions that user code can't catch, like OutOfMemory, StackOverflow and I believe TypeLoadException. 

You might be able to capture a dump at the OOM occurrence with ProcDump (as it can be set to capture a dump under certain conditions). I think something like this might work ` procdump -ma -e 1 -f OutOfMemoryException -g ...` (You need to pass in the PID of the process or the process name)

You could use code like the following to detect when you are approaching an OOM condition and take some action in your app
```csharp
internal enum MemoryPressure
{
    Low,
    Medium,
    High
}


internal static MemoryPressure GetMemoryPressure()
{
    const double HighPressureThreshold = .90;       // Percent of GC memory pressure threshold we consider "high"
    const double MediumPressureThreshold = .70;     // Percent of GC memory pressure threshold we consider "medium"


    GCMemoryInfo memoryInfo = GC.GetGCMemoryInfo();


    if (memoryInfo.MemoryLoadBytes >= memoryInfo.HighMemoryLoadThresholdBytes * HighPressureThreshold)
    {
        return MemoryPressure.High;
    }


    if (memoryInfo.MemoryLoadBytes >= memoryInfo.HighMemoryLoadThresholdBytes * MediumPressureThreshold)
    {
        return MemoryPressure.Medium;
    }


    return MemoryPressure.Low;
}
```

**Comment by dave-yotta** [comment]
@javiercn I think there's a misunderstanding.  I want the process to terminate when there is an OOM, but ASP.NET core is catching the exception and the process does not terminate.

**Comment by javiercn** [comment]
@dave-yotta sorry for the confusion and thanks for the clarification.

Do you have any call stack indicating where the exception is being captured?

**Comment by dave-yotta** [comment]
@javiercn I did, and I was going to post it here, but it left my clipboard long ago :)  I'll re run some tests tonight and get some examples here for you

**Comment by dave-yotta** [comment]
Here's one example, code is here, use run.ps1: https://github.com/dave-yotta/asp-oom-repro.  I've just called the /allocate endpoint a few times here as you can see in the logs.

In this example we get a few unhandled OOM in user code first, then some in the runtime as further requests are made and the GC is getting very dry.  This time it's actually left in a hung state.

```
[15:17:39] info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:80
[15:17:39] info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
[15:17:39] info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
[15:17:39] info: Microsoft.Hosting.Lifetime[0]
      Content root path: /App
[15:23:18]:  Allocate Called
GC Heap Limit = 48mb
Allocated 40.837890625mb[15:23:18] fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMF6BVO9NN92", Request id "0HMF6BVO9NN92:00000001": An unhandled exception was thrown by the application.
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Linq.Enumerable.RepeatIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at OOMRepro.Startup.<Configure>g__Alloc|2_0() in /build/Startup.cs:line 50
   at OOMRepro.Startup.<>c.<<Configure>b__2_2>d.MoveNext() in /build/Startup.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[15:23:20]:  Allocate Called
GC Heap Limit = 48mb
Allocated 42.7109375mb[15:23:20] fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMF6BVO9NN93", Request id "0HMF6BVO9NN93:00000001": An unhandled exception was thrown by the application.
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Linq.Enumerable.RepeatIterator`1.ToArray()
   at OOMRepro.Startup.<Configure>g__Alloc|2_0() in /build/Startup.cs:line 50
   at OOMRepro.Startup.<>c.<<Configure>b__2_2>d.MoveNext() in /build/Startup.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[15:23:20]:  Allocate Called
GC Heap Limit = 48mb
Allocated 43.2578125mb[15:23:20] fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMF6BVO9NN94", Request id "0HMF6BVO9NN94:00000001": An unhandled exception was thrown by the application.
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Linq.Enumerable.RepeatIterator`1.ToArray()
   at OOMRepro.Startup.<Configure>g__Alloc|2_0() in /build/Startup.cs:line 50
   at OOMRepro.Startup.<>c.<<Configure>b__2_2>d.MoveNext() in /build/Startup.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[15:23:21]:  Allocate Called
GC Heap Limit = 48mb
Allocated 44.3046875mb[15:23:21] fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMF6BVO9NN95", Request id "0HMF6BVO9NN95:00000001": An unhandled exception was thrown by the application.
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Linq.Enumerable.RepeatIterator`1.ToArray()
   at OOMRepro.Startup.<Configure>g__Alloc|2_0() in /build/Startup.cs:line 50
   at OOMRepro.Startup.<>c.<<Configure>b__2_2>d.MoveNext() in /build/Startup.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[15:23:21]:  Allocate Called
GC Heap Limit = 48mb
Allocated 44.3564453125mb[15:23:21] fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMF6BVO9NN96", Request id "0HMF6BVO9NN96:00000001": An unhandled exception was thrown by the application.
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Linq.Enumerable.RepeatIterator`1.ToArray()
   at OOMRepro.Startup.<Configure>g__Alloc|2_0() in /build/Startup.cs:line 50
   at OOMRepro.Startup.<>c.<<Configure>b__2_2>d.MoveNext() in /build/Startup.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[15:23:22]:  Allocate Called
GC Heap Limit = 48mb
Allocated 44.630859375mb[15:23:25]:  Allocate Called
GC Heap Limit = 48mb
Allocated 44.8701171875mb[15:23:22] fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMF6BVO9NN97", Request id "0HMF6BVO9NN97:00000001": An unhandled exception was thrown by the application.
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Linq.Enumerable.RepeatIterator`1.ToArray()
   at OOMRepro.Startup.<Configure>g__Alloc|2_0() in /build/Startup.cs:line 50
   at OOMRepro.Startup.<>c.<<Configure>b__2_2>d.MoveNext() in /build/Startup.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[15:23:25] warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally.
System.AggregateException: An error occurred while writing to logger(s). (Exception of type 'System.OutOfMemoryException' was thrown.)
 ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Array.Resize[T](T[]& array, Int32 newSize)
   at System.RuntimeType.ListBuilder`1.ToArray()
   at System.RuntimeType.RuntimeTypeCache.MemberInfoCache`1.PopulateMethods(Filter filter)
   at System.RuntimeType.RuntimeTypeCache.MemberInfoCache`1.GetListByName(Char* pName, Int32 cNameLen, Byte* pUtf8Name, Int32 cUtf8Name, MemberListType listType, CacheType cacheType)
   at System.RuntimeType.RuntimeTypeCache.MemberInfoCache`1.Populate(String name, MemberListType listType, CacheType cacheType)
   at System.RuntimeType.RuntimeTypeCache.MemberInfoCache`1.GetMemberList(MemberListType listType, String name, CacheType cacheType)
   at System.RuntimeType.GetMethodCandidates
   at System.RuntimeType.GetMethods(BindingFlags bindingAttr)
   at System.Diagnostics.StackTrace.TryResolveStateMachineMethod(MethodBase& method, Type& declaringType)
   at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat)
   at System.Exception.get_StackTrace()
   at System.Exception.ToString()
   at Microsoft.Extensions.Logging.Console.ConsoleLogger.CreateDefaultLogMessage
   at Microsoft.Extensions.Logging.Console.ConsoleLogger.WriteMessage(LogLevel logLevel, String logName, Int32 eventId, String message, Exception exception)
   at Microsoft.Extensions.Logging.Console.ConsoleLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|12_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.ThrowLoggingError(List`1 exceptions)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass6_0`2.<Define>g__Log|0(ILogger logger, T1 arg1, T2 arg2, Exception exception)
   at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass6_0`2.<Define>b__1(ILogger logger, T1 arg1, T2 arg2, Exception exception)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelTrace.ApplicationError(String connectionId, String traceIdentifier, Exception ex)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ReportApplicationError(Exception ex)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
[15:23:28] crit: Microsoft.AspNetCore.Server.Kestrel[0]
      The connection listener failed to accept any new connections.
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection..ctor(Socket socket, MemoryPool`1 memoryPool, PipeScheduler scheduler, ISocketsTrace trace, Nullable`1 maxReadBufferSize, Nullable`1 maxWriteBufferSize)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.AcceptAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.ConnectionDispatcher.<>c__DisplayClass8_0.<<StartAcceptingConnectionsCore>g__AcceptConnectionsAsync|0>d.MoveNext()
```

**Comment by dave-yotta** [comment]
Here is an example from the `allocate-safe` which is what I would call something like the expected behaviour - at least ASP.NET should not be catching these OOM exceptions which would also result in termination.  I've just used `ENV COMPlus_DbgEnableMiniDump 1` here to get a dump but that's not really relevant.

```
[15:33:57] info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:80
[15:33:57] info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
[15:33:57] info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
[15:33:57] info: Microsoft.Hosting.Lifetime[0]
      Content root path: /App
[15:34:09]:  Allocate With Catch Called
GC Heap Limit = 48mb
Allocated 37.7412109375mbProcess terminated. System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Linq.Enumerable.RepeatIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at OOMRepro.Startup.<Configure>g__Alloc|2_0() in /build/Startup.cs:line 50
   at OOMRepro.Startup.<>c.<<Configure>b__2_3>d.MoveNext() in /build/Startup.cs:line 66
   at System.Environment.FailFast(System.String)
   at OOMRepro.Startup+<>c+<<Configure>b__2_3>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[OOMRepro.Startup+<>c+<<Configure>b__2_3>d, OOMRepro, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<<Configure>b__2_3>d ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[OOMRepro.Startup+<>c+<<Configure>b__2_3>d, OOMRepro, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<<Configure>b__2_3>d ByRef)
   at OOMRepro.Startup+<>c.<Configure>b__2_3(Microsoft.AspNetCore.Http.HttpContext)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.SetRoutingAndContinue(Microsoft.AspNetCore.Http.HttpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext)
   at Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext)
   at Microsoft.AspNetCore.Hosting.HostingApplication.ProcessRequestAsync(Context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol+<ProcessRequests>d__214`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol+<ProcessRequests>d__214`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Microsoft.AspNetCore.Server.Kestrel.Core, Version=3.1.22.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<ProcessRequests>d__214`1<System.__Canon> ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol+<ProcessRequests>d__214`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Microsoft.AspNetCore.Server.Kestrel.Core, Version=3.1.22.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<ProcessRequests>d__214`1<System.__Canon> ByRef)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Microsoft.AspNetCore.Hosting.Server.IHttpApplication`1<System.__Canon>)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol+<ProcessRequestsAsync>d__213`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()     
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol+<ProcessRequestsAsync>d__213`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Microsoft.AspNetCore.Server.Kestrel.Core, Version=3.1.22.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<ProcessRequestsAsync>d__213`1<System.__Canon> ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol+<ProcessRequestsAsync>d__213`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Microsoft.AspNetCore.Server.Kestrel.Core, Version=3.1.22.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<ProcessRequestsAsync>d__213`1<System.__Canon> ByRef)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Microsoft.AspNetCore.Hosting.Server.IHttpApplication`1<System.__Canon>)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection+<ProcessRequestsAsync>d__12`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection+<ProcessRequestsAsync>d__12`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Microsoft.AspNetCore.Server.Kestrel.Core, Version=3.1.22.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<ProcessRequestsAsync>d__12`1<System.__Canon> ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection+<ProcessRequestsAsync>d__12`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Microsoft.AspNetCore.Server.Kestrel.Core, Version=3.1.22.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<ProcessRequestsAsync>d__12`1<System.__Canon> ByRef)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection.ProcessRequestsAsync[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Microsoft.AspNetCore.Hosting.Server.IHttpApplication`1<System.__Canon>)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnectionMiddleware`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnConnectionAsync(Microsoft.AspNetCore.Connections.ConnectionContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection+<ExecuteAsync>d__32.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection+<ExecuteAsync>d__32, Microsoft.AspNetCore.Server.Kestrel.Core, Version=3.1.22.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<ExecuteAsync>d__32 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection+<ExecuteAsync>d__32, Microsoft.AspNetCore.Server.Kestrel.Core, Version=3.1.22.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<ExecuteAsync>d__32 ByRef)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection.ExecuteAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
Writing minidump to file /OOMRepro.<pid>.dmp
```

**Comment by halter73** [comment]
Did you try adding middleware? For example:

```C#
app.Use(next =>
{
	return async httpContext =>
    {
        try
        {
            await next(httpContext);
        }
        catch(OutOfMemoryException m)
        {
            Environment.FailFast(m.ToString());
        }
    };
});
```

You could put this at the start of `Startup.Configure()` to put it at the beginning of the pipeline. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-6.0

**Comment by dave-yotta** [comment]
@halter73 of course. this is a basic example. that will not catch anything raised within the asp.net runtime, middlewares only wrap user code.

**Comment by dave-yotta** [comment]
Another issue with the runtime catching out of memory is that it forces the user to call Environment.FailFast to have a hope of getting a dump.  But this destroys the trace because it has been caught and discarded.  We would want to check these locals to determine the cause of the OOM - but we may end up releasing them in the action of terminating the process.

The normal behaviour for a .NET application is for unhandled exceptions to be left alone until the .NET runtime itself terminates the application.  A dump taken at this exit will contain all the threads involved in raising the OOM, including their locals to be investigated.

In ASP.NET Core, if we leave an exception unhandled, it is simply caught by ASP framework and discarded (even if it's a corrupted state exception like OOM as we've been discussing).  So such a dump cannot be taken at all and we are left with the only chance of getting one containing incomplete information anyway.

**Comment by halter73** [comment]
> It should be possible to terminate (and e.g. dump) on the first instance of OOM, regardless of where it is raised. The framework is preventing this from being possible, making it difficult to debug such issues.

One option is to watch the heap size out of process and collect a dump and restart the process manually when you observe the GC heap size exceeding a certain limit using tools like `dotnet-counters` and `dotnet-dump`. This is better than FailFast because you can attempt to gracefully shutdown the server and drain request before you actually run out of memory while still collecting a dump.

Having a way of making certain OOMs fail fast would be a runtime decision, so I'm going to transfer the issue.
