### ISSUE TITLE
Kestrel will only bind to an IPEndPoint not an EndPoint

### ISSUE THREAD

**Issue by Ninds** [dotnet/aspnetcore#39955]
Kestrel will only bind to an IPEndPoint not an EndPoint
Reproducer can be found here :
[KestrelwithArbitraryEndPoint.cs](https://gist.github.com/Ninds/d37715b67f20d993ab41451fa4b4ac45)
There is a runtime exception.

It appears it should have been fixed here [Add support for listening to arbitrary endpoints](https://github.com/dotnet/aspnetcore/pull/20892).

OR .. perhaps I am doing something wrong. 

The environment is .NET6

[Kestrel with MemoryTransport](https://github.com/davidfowl/BedrockFramework/issues/65)
[Consider adding an overload of Listen that takes an EndPoint](https://github.com/dotnet/aspnetcore/issues/12428)

**Comment by davidfowl** [comment]
Here's the exception:

```
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Overriding address(es) 'https://localhost:7051, http://localhost:5051'. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.
Unhandled exception. System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.GetDisplayName()
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at KestrelTransportDemo.Program.Main(String[] args) in C:\Users\david\source\repos\WebApplication9\WebApplication9\Program.cs:line 53
   at KestrelTransportDemo.Program.<Main>(String[] args)
```

It's coming from here https://github.com/dotnet/aspnetcore/blob/f9de7e4b9d4816c26db0652c4b7c99f321a16b44/src/Servers/Kestrel/Core/src/ListenOptions.cs#L127. Clearly these tests were inadequate 😞 because it doesn't work end to end.

**Comment by halter73** [comment]
I opened https://github.com/dotnet/aspnetcore/pull/40003 to fix this. Hopefully we can get it backported to .NET 6 too. It looks like this has been a problem since .NET 5.

Another possible workaround other than doing `public class MemoryEndPoint_WithWorkaround : IPEndPoint` is to have the `MemoryConnectionListener.EndPoint` return a `IPEndPoint` , `UnixDomainSocketEndPoint` or `FileHandleEndPoint`. The `IConnectionListener.EndPoint` property is only used to populate the `IServerAddressesFeature` which is generally only used to display the listening address.
