### ISSUE TITLE
RenderTreeBuilder cannot wire up EventCallback via reflection

### ISSUE THREAD

**Issue by groogiam** [dotnet/aspnetcore#40008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The following does not seem to work.

```csharp
        var evtCallbackType = typeof(EventCallback<>).MakeGenericType(refComponentType);
        Func<IDataEntityViewModelInstance, Task> changedFunc = OnSelectedEntityChanged;
        var evtCallback = Activator.CreateInstance(evtCallbackType, this, changedFunc);
        builder.AddAttribute(10, nameof(EntityReferenceComponent<EntityStage>.SelectedEntityChanged), evtCallback);
```

```csharp
private async Task OnSelectedEntityChanged(IDataEntityViewModelInstance arg)
{
 //...
}
```

Throws 

```csharp
Unhandled exception rendering component: Unable to set property 'SelectedEntityChanged' on object of type 'Web.Ui.Shared.EntityEditor.EntityReferenceComponent`1[[Bd.Vm.Asset, Bd.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]'. The error was: Specified cast is not valid.
System.InvalidOperationException: Unable to set property 'SelectedEntityChanged' on object of type '.Web.Ui.Shared.EntityEditor.EntityReferenceComponent`1[[Bd.Vm.Asset, Bd.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]'. The error was: Specified cast is not valid.
 ---> System.InvalidCastException: Specified cast is not valid.
   at Microsoft.AspNetCore.Components.Reflection.PropertySetter.CallPropertySetter[EntityReferenceComponent`1,EventCallback`1](Action`2 setter, Object target, Object value)
   at Microsoft.AspNetCore.Components.Reflection.PropertySetter.SetValue(Object target, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|3_0(Object target, PropertySetter writer, String parameterName, Object value)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|3_0(Object target, PropertySetter writer, String parameterName, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)
   at Microsoft.AspNetCore.Components.ParameterView.SetParameterProperties(Object target)
   at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
   at Web.Ui.Shared.EntityEditor.EntityReferenceComponent`1[[Bd.Vm.Asset, Bd.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<>n__0(ParameterView parameters)
   at Web.Ui.Shared.EntityEditor.EntityReferenceComponent`1.<SetParametersAsync>d__53[[Bd.Vm.Asset, Bd.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext() in 
```

However this seems to work just fine. Unless I'm mistaken these two sets of code should be semantically the same.
```csharp
 //this works without issue
        var designTimeCallback = new EventCallback<Asset>(this, OnSelectedEntityChanged) as object;
        builder.AddAttribute(10, nameof(EntityReferenceComponent<EntityStage>.SelectedEntityChanged), designTimeCallback);
```

### Expected Behavior

The EventCallback via reflection work as a design time event callback.

### Steps To Reproduce

Working on a simple repro. Will post shortly.

### Exceptions (if any)

Unhandled exception rendering component: Unable to set property 'SelectedEntityChanged' on object of type 'Web.Ui.Shared.EntityEditor.EntityReferenceComponent`1[[Bd.Vm.Asset, Bd.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]'. The error was: Specified cast is not valid.
System.InvalidOperationException: Unable to set property 'SelectedEntityChanged' on object of type '.Web.Ui.Shared.EntityEditor.EntityReferenceComponent`1[[Bd.Vm.Asset, Bd.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]'. The error was: Specified cast is not valid.
 ---> System.InvalidCastException: Specified cast is not valid.
   at Microsoft.AspNetCore.Components.Reflection.PropertySetter.CallPropertySetter[EntityReferenceComponent`1,EventCallback`1](Action`2 setter, Object target, Object value)
   at Microsoft.AspNetCore.Components.Reflection.PropertySetter.SetValue(Object target, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|3_0(Object target, PropertySetter writer, String parameterName, Object value)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|3_0(Object target, PropertySetter writer, String parameterName, Object value)
   at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)
   at Microsoft.AspNetCore.Components.ParameterView.SetParameterProperties(Object target)
   at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
   at Web.Ui.Shared.EntityEditor.EntityReferenceComponent`1[[Bd.Vm.Asset, Bd.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<>n__0(ParameterView parameters)
   at Web.Ui.Shared.EntityEditor.EntityReferenceComponent`1.<SetParametersAsync>d__53[[Bd.Vm.Asset, Bd.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext() in 

### .NET Version

6.0.101

**Comment by groogiam** [comment]
In the process of creating the repro project I uncovered a logic issue in my code which explains the issue. I was passing the wrong type to the EventCallback<>. This works as expected.
