### ISSUE TITLE
Method not found error. Project in net core 6.0. I use Microsoft.AspNetCore.Identity 2.2.0

### ISSUE THREAD

**Issue by tanumilian72** [dotnet/aspnetcore#40068]
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Versacom.Icev.Web.Api.Core.Enum;
using Versacom.Icev.Web.Api.Model.AuthenticationService;

namespace Versacom.Icev.Web.Api.BusinessLogic.Business.AuthenticationService.Ldap;

/// <summary>
/// This class implements the logic to signin a user within active directory.
/// </summary>
public class LdapSignInManager : SignInManager<UserIdentity> 
{
    #region Private fields

    private readonly ILogger<LdapSignInManager> _logger;

    #endregion

    #region Constructors

    /// <summary>
    /// Builds an Ldap SignInManager instance.
    /// </summary>
    /// <param name="userManager">The ldap user manager instance object.</param>
    /// <param name="contextAccessor">The context accessor object.</param>
    /// <param name="claimsFactory">The claims factory object.</param>
    /// <param name="optionsAccessor">The options accessor object.</param>
    /// <param name="logger">The instance's logger.</param>
    /// <param name="schemes">The schema provider.</param>
    public LdapSignInManager(LdapUserManager userManager,
        IHttpContextAccessor contextAccessor,
        IUserClaimsPrincipalFactory<UserIdentity> claimsFactory,
        IOptions<IdentityOptions> optionsAccessor,
        ILogger<LdapSignInManager> logger,
        IAuthenticationSchemeProvider schemes)
        : base(userManager, contextAccessor, claimsFactory, optionsAccessor, logger, schemes)
    {
        _logger = logger;
    }

    #endregion

    #region Public methods 

    /// <summary>
    /// Validates the user's password.
    /// </summary>
    /// <param name="user">The user's identity object.</param>
    /// <param name="password">The user's password.</param>
    /// <param name="rememberMe">Indicates whether to remember the user credentials or not.</param>
    /// <returns>A signin result object.</returns>
    public async Task<SignInResult> PasswordSignInAsync(UserIdentity user, string password, bool rememberMe)
    {
        try
        {
            // Validates UserManager object
            LdapUserManager? ldapUserManager = null;
            if (UserManager is LdapUserManager)
            {
                ldapUserManager = UserManager as LdapUserManager;
                if (ldapUserManager is null)
                {
                    _logger.LogError("LdapSignInManager - An error occured while signing the user to active directory.");
                    return SignInResult.Failed;
                }
            }
            else
            {
                _logger.LogError("LdapSignInManager - An error occured while signing the user to active directory.");
                return SignInResult.Failed;
            }

            // Validates Ldap account signin password
            ldapUserManager.AuthenticationType = AuthenticationType.Ldap;
            var ldapUser = await ldapUserManager.FindAsync(user, password);
            if (ldapUser is null)
            {
                _logger.LogError("LdapSignInManager - An error occured while signing the user to active directory.");
                return SignInResult.Failed;
            }

            // Validates user password
            return await base.PasswordSignInAsync(ldapUser, password, rememberMe, user.LockoutEnabled);
        }
        catch (Exception ex)
        {
            _logger.LogError("LdapSignInManager - An error occured while signing the user to active directory.\n\n{ex.Message}\n\n{ex.StackTrace}\n\n", ex.Message, ex.StackTrace);
            return SignInResult.Failed;
        }
    }

    #endregion
}

/* STARTUP CLASS */
        // Configure identities
        var lockoutSettings = Configuration.GetSection("LockoutSettings").Get<LockoutSettings>();
        services.AddIdentity<UserIdentity, IdentityRole<int>>()
            .AddEntityFrameworkStores<AuthenticationServiceContext>()
            .AddUserManager<LdapUserManager>()
            .AddSignInManager<LdapSignInManager>()
            .AddDefaultTokenProviders();
        services.Configure<IdentityOptions>(
            options =>
            {
                options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(lockoutSettings.DefaultLockoutTimeInMinutes);
                options.Lockout.MaxFailedAccessAttempts = lockoutSettings.MaxFailedAccessAttempts;
                options.Lockout.AllowedForNewUsers = lockoutSettings.AllowedForNewUsers;
            });

/*  LDAPUserMANAGER */

using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Versacom.Icev.Web.Api.BusinessLogic.Business.AuthenticationService.Interface;
using Versacom.Icev.Web.Api.Core.Enum;
using Versacom.Icev.Web.Api.Model.AuthenticationService;

namespace Versacom.Icev.Web.Api.BusinessLogic.Business.AuthenticationService.Ldap;

/// <summary>
/// This class implements the logic to manage an identity.
/// </summary>
public class LdapUserManager : UserManager<UserIdentity>
{
    #region Private fields

    private readonly ILogger<LdapUserManager> _logger;
    private readonly ILdapAuthenticationService _ldapAuthenticationService;

    #endregion

    #region Public properties

    /// <summary>
    /// The type of authentication.
    /// </summary>
    /// <example>NONE, LDAP, IDENTITY</example>
    public AuthenticationType AuthenticationType { get; set; }

    #endregion

    #region Constructors

    /// <summary>
    /// Constructs a new instance of <see cref="LdapUserManager"/>.
    /// </summary>
    /// <param name="ldapAuthenticationService">The ldap authentication service.</param>
    /// <param name="store">The persistence store the manager will operate over.</param>
    /// <param name="optionsAccessor">The accessor used to access the <see cref="IdentityOptions"/>.</param>
    /// <param name="passwordHasher">The password hashing implementation to use when saving passwords.</param>
    /// <param name="userValidators">A collection of <see cref="IUserValidator{TUser}"/> to validate users against.</param>
    /// <param name="passwordValidators">A collection of <see cref="IPasswordValidator{TUser}"/> to validate passwords against.</param>
    /// <param name="keyNormalizer">The <see cref="ILookupNormalizer"/> to use when generating index keys for users.</param>
    /// <param name="errors">The <see cref="IdentityErrorDescriber"/> used to provider error messages.</param>
    /// <param name="services">The <see cref="IServiceProvider"/> used to resolve services.</param>
    /// <param name="logger">The logger used to log messages, warnings and errors.</param>
    public LdapUserManager(
        ILdapAuthenticationService ldapAuthenticationService,
        IUserStore<UserIdentity> store,
        IOptions<IdentityOptions> optionsAccessor,
        IPasswordHasher<UserIdentity> passwordHasher,
        IEnumerable<IUserValidator<UserIdentity>> userValidators,
        IEnumerable<IPasswordValidator<UserIdentity>> passwordValidators,
        ILookupNormalizer keyNormalizer,
        IdentityErrorDescriber errors,
        IServiceProvider services,
        ILogger<LdapUserManager> logger)
        : base(store, optionsAccessor, passwordHasher, userValidators, passwordValidators, keyNormalizer, errors, services, logger)
    {
        _logger = logger;
        _ldapAuthenticationService = ldapAuthenticationService;
    }

    #endregion

    #region Public methods

    /// <summary>
    /// Retieves a user identity from active directory by its name.
    /// </summary>
    /// <param name="user">The user's identity object.</param>
    /// <param name="password">The user's password.</param>
    /// <returns>The user's identity object.</returns>
    public async Task<UserIdentity> FindAsync(UserIdentity user, string password)
    {
        if (AuthenticationType == AuthenticationType.Identity)
        {
            return await base.FindByNameAsync(user.UserName);
        }
        else
        {
            return await Task.FromResult(_ldapAuthenticationService.GetUser(user, password));
        }
    }

    #endregion
}

/*  PROJECT FILE */
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Business\NewFolder\**" />
    <Compile Remove="Extensions\**" />
    <EmbeddedResource Remove="Business\NewFolder\**" />
    <EmbeddedResource Remove="Extensions\**" />
    <None Remove="Business\NewFolder\**" />
    <None Remove="Extensions\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="6.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Novell.Directory.Ldap.NETStandard" Version="3.6.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.15.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Versacom.Icev.Web.Api.Core\Versacom.Icev.Web.Api.Core.csproj" />
    <ProjectReference Include="..\Versacom.Icev.Web.Api.DataAccessLayer\Versacom.Icev.Web.Api.DataAccessLayer.csproj" />
    <ProjectReference Include="..\Versacom.Icev.Web.Api.Model\Versacom.Icev.Web.Api.Model.csproj" />
  </ItemGroup>

</Project>

I got this error:

System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Void Microsoft.AspNetCore.Identity.SignInManager`1..ctor(Microsoft.AspNetCore.Identity.UserManager`1<!0>, Microsoft.AspNetCore.Http.IHttpContextAccessor, Microsoft.AspNetCore.Identity.IUserClaimsPrincipalFactory`1<!0>, Microsoft.Extensions.Options.IOptions`1<Microsoft.AspNetCore.Identity.IdentityOptions>, Microsoft.Extensions.Logging.ILogger`1<Microsoft.AspNetCore.Identity.SignInManager`1<!0>>, Microsoft.AspNetCore.Authentication.IAuthenticationSchemeProvider)'.
  Source=Versacom.Icev.Web.Api.BusinessLogic
  StackTrace:
   at Versacom.Icev.Web.Api.BusinessLogic.Business.AuthenticationService.Ldap.LdapSignInManager..ctor(LdapUserManager userManager, IHttpContextAccessor contextAccessor, IUserClaimsPrincipalFactory`1 claimsFactory, IOptions`1 optionsAccessor, ILogger`1 logger, ILogger`1 logger2, IAuthenticationSchemeProvider schemes) in C:\dev\VersacomRDProjects\ICEV-V2\Versacom.Icev.Web.Api.BusinessLogic\Business\AuthenticationService\Manager\LdapSignInManager.cs:line 43
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.AspNetCore.Identity.IdentityBuilderExtensions.<>c__DisplayClass3_0`1.<AddSignInManager>b__0(IServiceProvider services)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Versacom.Icev.Web.Api.BusinessLogic.Business.AuthenticationService.Service.AuthenticationServiceFactory.GetHostAuthenticationService() in C:\dev\VersacomRDProjects\ICEV-V2\Versacom.Icev.Web.Api.BusinessLogic\Business\AuthenticationService\Service\AuthenticationServiceFactory.cs:line 82
   at Versacom.Icev.Web.Api.BusinessLogic.Business.AuthenticationService.AuthenticationBusiness..ctor(AuthenticationServiceFactory authenticationServiceFactory) in C:\dev\VersacomRDProjects\ICEV-V2\Versacom.Icev.Web.Api.BusinessLogic\Business\AuthenticationService\AuthenticationBusiness.cs:line 27
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass7_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()

**Comment by davidfowl** [comment]
Don't use `Microsoft.AspNetCore.Identity 2.2.0` in a .NET 6.0 project, there were lots of breaking changes between those versions.

**Comment by tanumilian72** [comment]
Is there an updated package or an alternate solution to Microsoft.AspNetCore.Identity 2.2.0?

**Comment by ekomsctr** [comment]
I have the same problem, there are no other versions available on NuGet. This only happens if i try to extend SignInManager<TUser> and .AddSignInManager<TSignInManager>() it.

**Comment by ekomsctr** [comment]
Found the trick: for some reason, Visual Studio was using the packages in the NugetFallbackFolder, which contained the Microsoft.AspNetCore.Identity library with the 6 parameters SignInManager constructor.

Closing Visual Studio, deleting the NugetFallbackFolder contents (only the content, the actual folder is required to be existing) and then rebuilding the project restores the correct version of the package with the 7 parameters constructor of SignInManager. 

Honestly dunno if this is intended to work like this or there is some problem.
