### ISSUE TITLE
Blazor PWA WebAssembly.instantiate(): Out of memory: wasm memory

### ISSUE THREAD

**Issue by Edivad99** [dotnet/aspnetcore#40092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I developed my own PWA application using Blazor. The app works normally on my computer and phone. But on my second phone the application doesn't have time to load and an error appears.
I connected my phone to the pc and through the chrome devtools I went to see the log on the console and I found the following errors.
`Streaming compilation failed. Falling back to ArrayBuffer instantiation.  RangeError: WebAssembly.instantiate(): Out of memory: wasm memory

blazor.webassembly.js:1 TypeError: Failed to execute 'arrayBuffer' on 'Response': body stream already read
(anonymous)	@	blazor.webassembly.js:1
(anonymous)	@	blazor.webassembly.js:1
await in (anonymous) (async)		
(anonymous)	@	blazor.webassembly.js:1
createWasm	@	dotnet.6.0.2.hy3rmx5lfa.js:1
(anonymous)	@	dotnet.6.0.2.hy3rmx5lfa.js:1

blazor.webassembly.js:1 Uncaught (in promise) TypeError: Failed to execute 'arrayBuffer' on 'Response': body stream already read
    at blazor.webassembly.js:1:36928
    at async blazor.webassembly.js:1:36900
    at async blazor.webassembly.js:1:36636
(anonymous)	@	blazor.webassembly.js:1
await in (anonymous) (async)		
(anonymous)	@	blazor.webassembly.js:1
createWasm	@	dotnet.6.0.2.hy3rmx5lfa.js:1
(anonymous)	@	dotnet.6.0.2.hy3rmx5lfa.js:1`

The PWA is distributed as AzureStaticApps.
Some specifics about the phone having these problems:
- Phone model: Samsung Galaxy J5 (2016)
- Android version: 7.1.1
- Chrome version: 98.0.3758.87
- Edge version: 97.0.1702.78

I attach some photos of the console and network traffic

![Schermata 2022-02-09 alle 11 09 33](https://user-images.githubusercontent.com/25778604/153178212-a0997725-76e2-421a-b2cb-73ad04f42b57.png)
![Schermata 2022-02-09 alle 11 09 53](https://user-images.githubusercontent.com/25778604/153178219-e515b52d-be84-4c6a-b404-1f969100d14c.png)
![Schermata 2022-02-09 alle 11 10 04](https://user-images.githubusercontent.com/25778604/153178226-5643e5ee-6227-4929-ba16-d24ffa275f18.png)
![Schermata 2022-02-09 alle 11 16 02](https://user-images.githubusercontent.com/25778604/153178231-9fc35341-7833-4973-9da9-954328c1ca1f.png)

### Expected Behavior

The PWA should work just as well as it does on the PC and other phones

### Steps To Reproduce

Simply, create a PWA project and try it out on low-end phones.

### .NET Version

6.0.102

**Comment by javiercn** [comment]
@Edivad99 thanks for contacting us.

I'm not sure what might be going on there, since the Android version is old there might be some compatibility issues even though the browser version is recent. Folks from the runtime team might have more ideas on what's going on here
