### ISSUE TITLE
Bug 1487866: [dotnet-sdk-7.0.100-preview.3.22118.7] blazorboilerplate "Todo list" page load with System.InvalidOperationException

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/aspnetcore#40368]
### Description

When running the app "blazorboilerplate" with .NET 7.0 Preivew 3 Runtime, failed to load the ToDo list page with an error message "an unhandled exception has occurred" 

### Reproduction Steps

**Repro steps for App**:
**This is .Net 5.0 app, but we are running it on 7.0, machine only have 7.0 installed, and DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX=2, so it runs on 7.0**

**Getting the file and password from:**https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1487866

1. Restore database to local db from file
2. Launch cmd window.  
3. Input "set ASPNETCORE_ENVIRONMENT=Development", press "Enter".
4. Navigate to blazorboilerplate folder.
5. Input "dotnet BlazorBoilerplate.Server.dll", press "Enter".  
6. Open edge with "https://localhost:5001/" or "http://localhost:5000".
7. Click "Login" button.
8. Input "user" into User Name textbox.
9. Input password into Password textbox. 
10. Click "LOGIN" button.
11. Click "Todo List" item.

**Minimal Repro Steps:**
**The machine must have dotnet-sdk-7.0.100-preview.3.22122.1 SDK installed. Demo source code attached 
[Demo (1).zip](https://github.com/dotnet/runtime/files/8123283/Demo.1.zip)
(Published folder contains the demo app, Demo folder contains the source code).**
1.Create a .NET 5.0 ASP.NET Core project with default Blazor Server App project template.
2.Add a Counter.cs file for default Counter component in project with following code:
```
using Microsoft.AspNetCore.Components;
namespace Demo.Pages
{
    public partial class Counter : ComponentBase
    {
        public Counter()
        {

        }
        public Counter(string title)
        {
           
        }
    }
}
```
3. Publish the app and change the runtime.json file to use 7.0.0-preview.3.22117.6 for Microsoft.AspNetCore.App under publish folder.
```
{
  "runtimeOptions": {
    "tfm": "net5.0",
    "framework": {
      "name": "Microsoft.AspNetCore.App",
      "version": "7.0.0-preview.3.22117.6"
    },
    "configProperties": {
      "System.GC.Server": true,
      "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization": false
    }
  }
}
```
4. Launch the Demo.exe and access http://localhost:5000/
5. Click Counter menu.

### Expected behavior

**Expected Result for App:**
The "Todo List" page will display.

**Expected Result for the minimal demo** :
The Counter page will display normally.

### Actual behavior

**Actual Result for App:**
Fail to load the ToDo List page with error "An handled exception has occurred."

**Actual Result for the minimal Demo:**

The page will display a message about there is an exception and the page need to be reload. And the command prompt, we will see this error:
```
 Unhandled exception rendering component: Multiple constructors accepting all given argument types have been found in type 'Demo.Pages.Counter'. There should only be one applicable constructor.
      System.InvalidOperationException: Multiple constructors accepting all given argument types have been found in type 'Demo.Pages.Counter'. There should only be one applicable constructor.
         at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.TryFindMatchingConstructor(Type instanceType, Type[] argumentTypes, ConstructorInfo& matchingConstructor, Nullable`1[]& parameterMap)
         at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.FindApplicableConstructor(Type instanceType, Type[] argumentTypes, ConstructorInfo& matchingConstructor, Nullable`1[]& matchingParameterMap)
         at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateFactory(Type instanceType, Type[] argumentTypes)
         at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateDefault(IServiceProvider serviceProvider, Type componentType)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

### Regression?

Yes

1). Windows 10 RS5 x64 + dotnet-sdk-7.0.100-preview.3.22122.1: Fail
2). Windows10 RS5 x64+dotnet-sdk-7.0.100-preview.3.22118.7: Fail
3). Windows10 RS5 x64+dotnet-sdk-5.0.211-win-x64: Pass
4). Windows10 RS5 x64+dotnet-sdk-7.0.100-preview.2.22114.1: Pass

### Configuration

**Application Name**: blazorboilerplate
**OS**: Windows 10 RS5
**CPU**: X64
**.NET Build Number**: dotnet-sdk-7.0.100-preview.3.22118.7
**Github Source Link**:  https://github.com/enkodellc/blazorboilerplate

**App & AppSource Checking at**: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1487866

### Other information

**Findings:**

According to the error message, we tried remove the empty non-parameter constructor, to leave only one constructor. But we get another error:

```
System.MissingMethodException: No parameterless constructor defined for type 'Demo.Pages.Counter'.
         at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
         at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
         at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
         at System.Activator.CreateInstance(Type type)
         at Microsoft.AspNetCore.Components.DefaultComponentActivator.CreateInstance(Type componentType)
         at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

```
@dotnet-actwx-bot @dotnet/compat

**Comment by Pilchie** [comment]
Starting with Razor Compiler in case it's causing an extra constructor to be generated.

**Comment by pranavkm** [comment]
This is related to a recent change where we started type activating Blazor Components by default. The repro app has types with multiple constructors and in the absence of any specific hints, type activator picks a constructor at random and attempts to resolve all of it's parameters from the DI container.

**Comment by Pilchie** [comment]
So this is an expected breaking change?  Is it documented yet?

**Comment by pranavkm** [comment]
I hadn't documented it as yet because I hadn't thought this would be a breaking change. I'll bring this up with the team to see if we should roll back the change, make it opt-in, or resolve this as a breaking change followed by an announcement.

**Comment by pranavkm** [comment]
@Junjun-zhao thanks for the issue report. We've decided to document this as a [breaking change](https://github.com/aspnet/Announcements/issues/482) for now to determine how widely it affects users to determine if we need to take further actions (such as rolling back the change or providing a switch). The announcement offers a couple of workarounds you could try to unblock yourself.

**Comment by Junjun-zhao** [comment]
Closing the issue for now as it has been document as breaking change, will reopen it if it is needed that affect users and need to take further actions.
