### ISSUE TITLE
`UseWindowsService` does not work with `WebApplicationBuilder`

### ISSUE THREAD

**Issue by OronDF343** [dotnet/aspnetcore#40445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In ASP.NET Core 6, it is not possible to call `UseWindowsService()` when using `WebApplicationBuilder`. Doing so results in an exception.
This affects any new projects created using the default template for ASP.NET Core 6.

### Expected Behavior

The default template for ASP.NET Core 6 should be possible to host in a Windows Service.

### Steps To Reproduce

Minimal repro with template:
1. `dotnet new webapi -n winsvctest`
2. `dotnet add package Microsoft.Extensions.Hosting.WindowsServices`
3. Edit `Program.cs`, add this at line 2: `builder.Host.UseWindowsService();`
4. `dotnet publish -c Release`
5. `sc create winsvctest start=auto DisplayName="winsvctest" binPath="...\winsvctest.exe"` (enter the absolute path)
6. `sc start winsvctest`
7. Check the Event Viewer to see the exception

ASP.NET Core 6 Program.cs (not working):
```
var builder = WebApplication.CreateBuilder(args);
builder.Host.UseWindowsService();

// Add services to the container.

builder.Services.AddControllers();
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();
```

ASP.NET Core 3.1 Program.cs (working):
```
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;

namespace MyService
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .UseSerilog()
                .UseWindowsService()
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
}

```

### Exceptions (if any)

```
System.NotSupportedException: The content root changed from "C:\Windows\system32\" to "D:\MyService\". Changing the host configuration using WebApplicationBuilder.Host is not supported. Use WebApplication.CreateBuilder(WebApplicationOptions) instead.
   at Microsoft.AspNetCore.Builder.ConfigureHostBuilder.ConfigureHostConfiguration(Action`1 configureDelegate)
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.UseContentRoot(IHostBuilder hostBuilder, String contentRoot)
   at Microsoft.Extensions.Hosting.WindowsServiceLifetimeHostBuilderExtensions.UseWindowsService(IHostBuilder hostBuilder, Action`1 configure)
   at Microsoft.Extensions.Hosting.WindowsServiceLifetimeHostBuilderExtensions.UseWindowsService(IHostBuilder hostBuilder)
   at Program.<Main>$(String[] args) in C:\Dev\Test\Program.cs:line 2
```

### .NET Version

6.0.200

### Anything else?

The documentation does not address this issue, at: https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-6.0&tabs=visual-studio

**Comment by Tratcher** [comment]
Related: https://github.com/dotnet/aspnetcore/issues/37464

**Comment by adityamandaleeka** [comment]
Triage: we could improve the message here to be more detailed about what specific option you'd need to set.
