### ISSUE TITLE
Blazor Webassembly - Debugger crashes app

### ISSUE THREAD

**Issue by softwaretirol** [dotnet/aspnetcore#40497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If we start to debug our webassembly project, the app is crashing (With IIS Express or even without..).
The app works perfect if we dont attach the debugger, or if we remove the inspectUri from the launchSettings.json.

Any hints how we can diagnose this problem?

![image](https://user-images.githubusercontent.com/7993272/156348708-ccad1782-95d0-4825-8431-7974eb10e400.png)

`fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] DevToolsProxy::Run: Exception System.AggregateException: One or more errors occurred. (Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index'))  ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')    at System.Collections.Generic.List`1.get_Item(Int32 index)    at Newtonsoft.Json.Linq.JContainer.GetItem(Int32 index)    at Newtonsoft.Json.Linq.JArray.get_Item(Object key)    at Microsoft.WebAssembly.Diagnostics.MonoProxy.AcceptEvent(SessionId sessionId, String method, JObject args, CancellationToken token)    at Microsoft.WebAssembly.Diagnostics.DevToolsProxy.OnEvent(SessionId sessionId, String method, JObject args, CancellationToken token)    --- End of inner exception stack trace ---    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)    at System.Threading.Tasks.Task`1.get_Result()    at Microsoft.WebAssembly.Diagnostics.DevToolsProxy.Run(Uri browserUri, WebSocket ideSocket)
`

### Expected Behavior

Debugger works like expected :-).

### Exceptions (if any)

Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] DevToolsProxy::Run: Exception System.AggregateException: One or more errors occurred. (Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index'))  ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')    at System.Collections.Generic.List`1.get_Item(Int32 index)    at Newtonsoft.Json.Linq.JContainer.GetItem(Int32 index)    at Newtonsoft.Json.Linq.JArray.get_Item(Object key)    at Microsoft.WebAssembly.Diagnostics.MonoProxy.AcceptEvent(SessionId sessionId, String method, JObject args, CancellationToken token)    at Microsoft.WebAssembly.Diagnostics.DevToolsProxy.OnEvent(SessionId sessionId, String method, JObject args, CancellationToken token)    --- End of inner exception stack trace ---    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)    at System.Threading.Tasks.Task`1.get_Result()    at Microsoft.WebAssembly.Diagnostics.DevToolsProxy.Run(Uri browserUri, WebSocket ideSocket)

### .NET Version

6.0.2

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
