### ISSUE TITLE
Can't get RazorPageOptions from DI with version 6.0.3 of Mvc.Razor.RuntimeCompilation

### ISSUE THREAD

**Issue by LionelVallet** [dotnet/aspnetcore#40609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Getting `RazorPageOptions` from dependency injection with `AddRazorRuntimeCompilation()` called on `ServiceCollection` throws an exception preventing the application to start because the `Conventions` property is null. When using `MapControllerRoute()` for example.

This issue came up with the version 6.0.3 of Mvc.Razor.RuntimeCompilation. This [commit](https://github.com/dotnet/aspnetcore/commit/207f2c39ee1eccbc339450570fe6297026ea549c) could be responsible for this bug.

### Expected Behavior

The service provider should build a `RazorPageOptions` as expected when using razor runtime compilation.

### Steps To Reproduce

If using `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation` in version **6.0.3** (6.0.2 works as expected)

``` csharp
public void ConfigureServices(IServiceCollection services)
{
    services
        .AddControllersWithViews()
        .AddRazorRuntimeCompilation();
}

public void Configure(IApplicationBuilder app)
{
    app.UseEndpoints(endpoints => endpoints.MapControllerRoute("default", "{controller}/{action}/{id?}")); // Throws ArgumentNullException
}
```

### Exceptions (if any)

**Value cannot be null. (Parameter 'source')**
 

  ```
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)

   at System.Linq.Enumerable.OfType[TResult](IEnumerable source)

   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionDescriptorProvider..ctor(IEnumerable``1 pageRouteModelProviders, IOptions``1 mvcOptionsAccessor, IOptions``1 pagesOptionsAccessor)

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span``1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)

   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)

...

   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)

   at Microsoft.AspNetCore.Builder.ControllerEndpointRouteBuilderExtensions.GetOrCreateDataSource(IEndpointRouteBuilder endpoints)

   at Microsoft.AspNetCore.Builder.ControllerEndpointRouteBuilderExtensions.MapControllerRoute(IEndpointRouteBuilder endpoints, String name, String pattern, Object defaults, Object constraints, Object dataTokens)`
```

### .NET Version

6.0.200

**Comment by pranavkm** [comment]
Do you have the 6.0.201 SDK / 6.0.3 Microsoft.AspNetCore.App runtime installed? Patch builds of packages typically require a corresponding version of the runtime to be installed.

**Comment by LionelVallet** [comment]
The 6.0.201 SDK seems to fix the issue.

**Comment by alexandrejobin** [comment]
I confirm that updating the SDK from 6.0.200 to 6.0.201 fixed the issue. I guest we will also have to update the ASP.NET Core Runtime to v6.0.3 on the servers.

**Comment by khallouf** [comment]
I can confirm that 6.0.201 SDK fixes the issue, but it seems that They didn't update to this SDK on Azure yet, so what does that mean? shouldn't they be up to date ?

**Comment by IssaSaman** [comment]
It's the same issue for me also.
the last update has too many issues !!! 

`services.AddRazorPages().AddRazorRuntimeCompilation();`

this line will solve the issue until Microsoft fix this
