### ISSUE TITLE
Quarantine StaticFiles.DefaultFilesMiddlewareTests.*

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#40642]
Note; these tests were quarantined as they were blocking an SDK insertion and subsequent efcore/runtime ingestion. 

Relevant links:
- https://github.com/dotnet/aspnetcore/pull/40353#issuecomment-1064372054
- https://github.com/dotnet/runtime/issues/65750

## Failing Test(s)

Note the tests are all xUnit `Theory`s'. One failing theory/test is included below, each test has multiple failing theories.

- Microsoft.AspNetCore.StaticFiles.DefaultFilesMiddlewareTests.NearMatch_RedirectAddSlash_All(baseUrl: "", baseDir: "./SubFolder", requestUrl: "/你好/世界", queryString: "?a=b")
- Microsoft.AspNetCore.StaticFiles.DefaultFilesMiddlewareTests.FoundDirectoryWithDefaultFile_PathModified_All(baseUrl: "", baseDir: "./SubFolder", requestUrl: "/你好/世界/", appendTrailingSlash: True)
- Microsoft.AspNetCore.StaticFiles.DefaultFilesMiddlewareTests.FoundDirectoryWithDefaultFile_PathModified_Windows(baseUrl: "", baseDir: ".\\SubFolder", requestUrl: "/你好/", appendTrailingSlash: True)
- Microsoft.AspNetCore.StaticFiles.DefaultFilesMiddlewareTests.NearMatch_RedirectAddSlash_Windows(baseUrl: "", baseDir: ".\\SubFolder", requestUrl: "/你好", queryString: "?a=b")

## Error Message

NearMatch_RedirectAddSlash_All(baseUrl: "", baseDir: "./SubFolder", requestUrl: "/你好/世界", queryString: "?a=b")

```text
Assert.Equal() Failure
Expected: Moved
Actual:   NotFound
```

Microsoft.AspNetCore.StaticFiles.DefaultFilesMiddlewareTests.FoundDirectoryWithDefaultFile_PathModified_All(baseUrl: "", baseDir: "./SubFolder", requestUrl: "/你好/世界/", appendTrailingSlash: True)

```
Assert.Equal() Failure
↓ (pos 7)
Expected: /你好/世界/default.html
Actual:   /你好/世界/
↑ (pos 7)
```

## Stacktrace

<details>

NearMatch_RedirectAddSlash_All(baseUrl: "", baseDir: "./SubFolder", requestUrl: "/你好/世界", queryString: "?a=b")

```text
   at Microsoft.AspNetCore.StaticFiles.DefaultFilesMiddlewareTests.NearMatch_RedirectAddSlash(String baseUrl, String baseDir, String requestUrl, String queryString) in /_/src/Middleware/StaticFiles/test/UnitTests/DefaultFilesMiddlewareTests.cs:line 220
   at Microsoft.AspNetCore.StaticFiles.DefaultFilesMiddlewareTests.NearMatch_RedirectAddSlash_All(String baseUrl, String baseDir, String requestUrl, String queryString) in /_/src/Middleware/StaticFiles/test/UnitTests/DefaultFilesMiddlewareTests.cs:line 193

```

Microsoft.AspNetCore.StaticFiles.DefaultFilesMiddlewareTests.FoundDirectoryWithDefaultFile_PathModified_All(baseUrl: "", baseDir: "./SubFolder", requestUrl: "/你好/世界/", appendTrailingSlash: True)

```
   at Microsoft.AspNetCore.StaticFiles.DefaultFilesMiddlewareTests.FoundDirectoryWithDefaultFile_PathModified(String baseUrl, String baseDir, String requestUrl, Boolean appendTrailingSlash) in /_/src/Middleware/StaticFiles/test/UnitTests/DefaultFilesMiddlewareTests.cs:line 181
   at Microsoft.AspNetCore.StaticFiles.DefaultFilesMiddlewareTests.FoundDirectoryWithDefaultFile_PathModified_All(String baseUrl, String baseDir, String requestUrl, Boolean appendTrailingSlash) in /_/src/Middleware/StaticFiles/test/UnitTests/DefaultFilesMiddlewareTests.cs:line 138
--- End of stack trace from previous location ---
```

</details>

## Logs

<details>

General:

[console.d87243c1.txt](https://github.com/dotnet/aspnetcore/files/8226188/console.d87243c1.txt)

Microsoft.AspNetCore.StaticFiles.DefaultFilesMiddlewareTests.FoundDirectoryWithDefaultFile_PathModified_All(baseUrl: "", baseDir: "./SubFolder", requestUrl: "/你好/世界/", appendTrailingSlash: True)

[vstest.log](https://github.com/dotnet/aspnetcore/files/8226189/vstest.log)

NearMatch_RedirectAddSlash_All(baseUrl: "", baseDir: "./SubFolder", requestUrl: "/你好/世界", queryString: "?a=b")

[vstest (1).log](https://github.com/dotnet/aspnetcore/files/8226190/vstest.1.log)

Windows Artifacts:
[vstest (2).log](https://github.com/dotnet/aspnetcore/files/8226208/vstest.2.log)
[console.5f095ce7.txt](https://github.com/dotnet/aspnetcore/files/8226209/console.5f095ce7.txt)

</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1655573&view=ms.vss-test-web.build-test-results-tab&runId=45630598&resultId=117013&paneView=debug

**Comment by TanayParikh** [comment]
May not need quarantining depending on https://github.com/dotnet/aspnetcore/pull/40353#issuecomment-1064387591. TBD...

**Comment by wtgodbe** [comment]
Our SDK doesn't have a version of runtime w/ the zipfile fix, we should try updating it once https://github.com/dotnet/installer/pull/13376 is in & un-quarantining the tests
