### ISSUE TITLE
Quarantine ReadAsync_WithAllowInputFormatterExceptionMessages_RegistersJsonInputExceptionsAsInputFormatterException

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#40661]
# Investigation

Cause: Previously the STJ exception message referred to the specific property that couldn't be converted (i.e., the JSON could not be converted to `System.DateTime`) whereas now it refers to the enclosing type (i.e., saying we can't convert the JSON to `Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatterTest+User`).

This failure starts to happen if we update to the latest runtime, so is very likely due to a change of runtime behavior. I did a bit of digging and it looks pretty likely that the underlying cause is this PR: https://github.com/dotnet/runtime/pull/66169 which was merged last week.

It looks like the same thing on the grounds that in that PR, they also had to change their tests to stop asserting that the message refers to a property type, and start asserting that it refers to the enclosing type instead: https://github.com/dotnet/runtime/pull/66169#discussion_r819134061

To me, the new STJ behavior looks less desirable than the old STJ behavior, since previously it was telling you which specific property type wasn't convertible, whereas now it just generically tells you about the parent object type. So this might turn out to be a STJ regression that should be fixed. However, the comment from @eiriktsarpalis specifically says that the old behavior was incorrect and the new behavior is correct, so I can't assume this is a regression.

@Tratcher @halter73 I'm not certain who owns this part of the product (CODEOWNERS claims it's @dotnet/aspnet-blazor-eng, which doesn't seem right). Could the owner of this test please figure out whether we should change the test, or whether to report this as a regression to the STJ runtime team?

In the meantime I'll make a quarantining PR but we might want to halt that process if we decide it's a runtime regression.

## Failing Test(s)

Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatterTest.ReadAsync_WithAllowInputFormatterExceptionMessages_RegistersJsonInputExceptionsAsInputFormatterException

## Error Message

```text
Assert.Equal() Failure
|                                  ↓ (pos 41)
| Expected: ···not be converted to System.Decimal. Path: $.age | LineNumber:···
| Actual:   ···not be converted to Microsoft.AspNetCore.Mvc.Formatters.Syste···
```

## Stacktrace

<details>

```text
|                                  ↑ (pos 41)
|    at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\StringAsserts.cs:line 244
|    at Xunit.Assert.Equal(String expected, String actual) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\StringAsserts.cs:line 174
|    at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatterTest.ReadAsync_WithAllowInputFormatterExceptionMessages_RegistersJsonInputExceptionsAsInputFormatterException(String content, String modelStateKey, String expectedMessage) in /_/src/Mvc/Mvc.Core/test/Formatters/SystemTextJsonInputFormatterTest.cs:line 157
|    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
| --- End of stack trace from previous location ---
|    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
|    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
| [0.019s] TestLifetime Information: Finished test ReadAsync_WithAllowInputFormatterExceptionMessages_RegistersJsonInputExceptionsAsInputFormatterException-{_age_x_}-$.age-The_JSON_value_could_not_be_converted_to_System.Decimal._Path_$.age_LineNumber_0_BytePositionInLine_10. in 0.0175193s


```
</details>

## Logs

<details>

```text
| [0.001s] TestLifetime Information: Starting test ReadAsync_WithAllowInputFormatterExceptionMessages_RegistersJsonInputExceptionsAsInputFormatterException-{_age_x_}-$.age-The_JSON_value_could_not_be_converted_to_System.Decimal._Path_$.age_LineNumber_0_BytePositionInLine_10. at 2022-03-11T01:58:18
| [0.002s] Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter Debug: JSON input formatter threw an exception: The JSON value could not be converted to Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatterTest+User. Path: $.age | LineNumber: 0 | BytePositionInLine: 10.
| [0.004s] Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatterTest Error: Test threw an exception.
| Xunit.Sdk.EqualException: Assert.Equal() Failure
|                                  ↓ (pos 41)
| Expected: ···not be converted to System.Decimal. Path: $.age | LineNumber:···
| Actual:   ···not be converted to Microsoft.AspNetCore.Mvc.Formatters.Syste···
|                                  ↑ (pos 41)
|    at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\StringAsserts.cs:line 244
|    at Xunit.Assert.Equal(String expected, String actual) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\StringAsserts.cs:line 174
|    at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatterTest.ReadAsync_WithAllowInputFormatterExceptionMessages_RegistersJsonInputExceptionsAsInputFormatterException(String content, String modelStateKey, String expectedMessage) in /_/src/Mvc/Mvc.Core/test/Formatters/SystemTextJsonInputFormatterTest.cs:line 157
|    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
| --- End of stack trace from previous location ---
|    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
|    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
| [0.019s] TestLifetime Information: Finished test ReadAsync_WithAllowInputFormatterExceptionMessages_RegistersJsonInputExceptionsAsInputFormatterException-{_age_x_}-$.age-The_JSON_value_could_not_be_converted_to_System.Decimal._Path_$.age_LineNumber_0_BytePositionInLine_10. in 0.0175193s

```
</details>

## Build

[](https://dev.azure.com/dnceng/public/_build/results?buildId=1657756&view=ms.vss-test-web.build-test-results-tab&runId=45670040&resultId=111711&paneView=attachments)

**Comment by javiercn** [comment]
@rafikiassumani-msft would be the owner of this area, since its web API

**Comment by SteveSandersonMS** [comment]
@javiercn Good point - submitted https://github.com/dotnet/aspnetcore/pull/40664 too.

**Comment by eiriktsarpalis** [comment]
The change came about during essential infrastructural refactoring of STJ internals. The exception surfaces from the converter factory for the parent type and as such it made sense to me at the time to report the parent type itself rather than the property type that is being processed (note: this is doing reflection-based metadata processing rather than performing deserialization at that particular stage).

This might have made sense given [STJ's own test coverage](https://github.com/dotnet/runtime/pull/66169#r819134061) but might be less so in other scenaria. Could you share a link to the failing unit test as well as the full expected and actual error message strings? Thanks.

**Comment by SteveSandersonMS** [comment]
Sure. The failing test is [Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatterTest.ReadAsync_WithAllowInputFormatterExceptionMessages_RegistersJsonInputExceptionsAsInputFormatterException](https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/test/Formatters/SystemTextJsonInputFormatterTest.cs#L133), specifically the case for "age" where it's trying to parse as System.Decimal.

Expected error: `The JSON value could not be converted to System.Decimal`
Actual error: `The JSON value could not be converted to Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatterTest+User`.

**Comment by eiriktsarpalis** [comment]
Thanks, I'll take a look.
