### ISSUE TITLE
MacOs generating https keys

### ISSUE THREAD

**Issue by more-pepsi** [dotnet/aspnetcore#40680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

```
dotnet dev-certs https --trust
Trusting the HTTPS development certificate was requested. If the certificate is not already trusted we will run the following command:
'sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain <<certificate>>'
This command might prompt you for your password to install the certificate on the system keychain.
There was an error saving the HTTPS developer certificate to the current user personal certificate store.

```
```

dotnet dev-certs https -v
[1] Listing certificates from CurrentUser\My
[2] Found certificates: no certificates
[3] Checking certificates validity
[4] Valid certificates: no certificates
[5] Invalid certificates: no certificates
[6] Finished listing certificates.
[1] Listing certificates from CurrentUser\My
[2] Found certificates: no certificates
[3] Checking certificates validity
[4] Valid certificates: no certificates
[5] Invalid certificates: no certificates
[6] Finished listing certificates.
[1] Listing certificates from LocalMachine\My
[2] Found certificates: no certificates
[3] Checking certificates validity
[4] Valid certificates: no certificates
[5] Invalid certificates: no certificates
[6] Finished listing certificates.
[8] Filtered certificates: no certificates
[9] Excluded certificates: no certificates
[0] Event 16 was called with 1 argument(s), but it is defined with 0 parameter(s).
[16]
[17] Generating HTTPS development certificate.
[18] Finished generating HTTPS development certificate.
[20] Saving certificate '94308BD1369DCA4E1C374DCDFF4447C2E030E0B8 - CN=localhost - Valid from 2022-03-13 07:17:41Z to 2023-03-13 07:17:41Z - IsHttpsDevelopmentCertificate: true - IsExportable: true' to store CurrentUser\My.
[54] Importing the certificate 94308BD1369DCA4E1C374DCDFF4447C2E030E0B8 - CN=localhost - Valid from 2022-03-13 07:17:41Z to 2023-03-13 07:17:41Z - IsHttpsDevelopmentCertificate: true - IsExportable: true to the keychain '/Users/bill/Library/Keychains/login.keychain-db'.
[56] An error has occurred while importing the certificate to the keychain: 1.
[22] An error has occurred saving the certificate: System.InvalidOperationException: There was an error importing the certificate into the user key chain '94308BD1369DCA4E1C374DCDFF4447C2E030E0B8'.

security: SecKeychainItemImport: User interaction is not allowed.

   at Microsoft.AspNetCore.Certificates.Generation.MacOSCertificateManager.SaveCertificateCore(X509Certificate2 certificate, StoreName storeName, StoreLocation storeLocation)
   at Microsoft.AspNetCore.Certificates.Generation.CertificateManager.SaveCertificate(X509Certificate2 certificate)
   at Microsoft.AspNetCore.Certificates.Generation.CertificateManager.EnsureAspNetCoreHttpsDevelopmentCertificate(DateTimeOffset notBefore, DateTimeOffset notAfter, String path, Boolean trust, Boolean includePrivateKey, String password, CertificateKeyExportFormat keyExportFormat, Boolean isInteractive).
There was an error saving the HTTPS developer certificate to the current user personal certificate store.

### Expected Behavior

I expect a certificate to be generated.

### Steps To Reproduce

Macos 12.2.1

```
brew install dotnet-sdk
dotnet dev-certs

 https -v
```

### Exceptions (if any)


   at Microsoft.AspNetCore.Certificates.Generation.MacOSCertificateManager.SaveCertificateCore(X509Certificate2 certificate, StoreName storeName, StoreLocation storeLocation)
   at Microsoft.AspNetCore.Certificates.Generation.CertificateManager.SaveCertificate(X509Certificate2 certificate)
   at Microsoft.AspNetCore.Certificates.Generation.CertificateManager.EnsureAspNetCoreHttpsDevelopmentCertificate(DateTimeOffset notBefore, DateTimeOffset notAfter, String path, Boolean trust, Boolean includePrivateKey, String password, CertificateKeyExportFormat keyExportFormat, Boolean isInteractive).
There was an error saving the HTTPS developer certificate to the current user personal certificate store.

### .NET Version

6.0.201

### Anything else?

.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.2
 OS Platform: Darwin
 RID:         osx.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.201/

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  6.0.201 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by adityamandaleeka** [comment]
@more-pepsi Based on the error message "User interaction is not allowed", are you running this over an SSH session or something where it's not able to display a UI for keychain?

**Comment by more-pepsi** [comment]
Yes, you where right. Thanks. It worked when using the GUI terminal. But not ssh
