### ISSUE TITLE
IHostBuilder.Build() times out after 5 seconds when running integration tests with WebApplicationFactory<T> on slow machines

### ISSUE THREAD

**Issue by jlorek** [dotnet/aspnetcore#40715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using the `WebApplicationFactory<T>` for integration tests, the tests fail on slow machines due to the default 5 seconds timeout already mentioned in #33886:
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Microsoft.Extensions.HostFactoryResolver/src/HostFactoryResolver.cs#L48
The `IHost` will fail to build and thow an `InvalidOperationException` with the message Unable to build `IHost`.

### Expected Behavior

A possibility to override the arbitrary 5 second timeout to account for longer startup times.

### Steps To Reproduce

Described in #33886.

### Exceptions (if any)

[03/15/2022 11:47:36 | INF | 93] IHostEnvironment.EnvironmentName: Integration
  Failed RandomIntegrationTest [5 s]
  Error Message:
   System.InvalidOperationException : Unable to build IHost
  Stack Trace:
     at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.CreateHost()
   at Microsoft.Extensions.Hosting.HostFactoryResolver.<>c__DisplayClass8_0.<ResolveHostFactory>b__0(String[] args)
   at Microsoft.AspNetCore.Mvc.Testing.DeferredHostBuilder.Build()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateHost(IHostBuilder builder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.ConfigureHostBuilder(IHostBuilder hostBuilder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.EnsureServer()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(DelegatingHandler[] handlers)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(Uri baseAddress, DelegatingHandler[] handlers)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient(WebApplicationFactoryClientOptions options)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient()

### .NET Version

6.0.101

### Anything else?

ASP.NET Core Version: 6.0.0

**Comment by rafikiassumani-msft** [comment]
@jlorek You can override the timeout value using the following env variable: `DOTNET_HOST_FACTORY_RESOLVER_DEFAULT_TIMEOUT_IN_SECONDS`. You will need to get the 6.0.1 patch.

**Comment by jlorek** [comment]
Thank you ✌️
