### ISSUE TITLE
Microsoft.JSInterop.JSException: Could not find 'blazorExtensions.WriteCookie' ('blazorExtensions' was undefined).

### ISSUE THREAD

**Issue by Alerinos** [dotnet/aspnetcore#40744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The error appeared when upgrading from .net 7 preview 1 to preview 2

How can I fix this error? I checked the devlog and can't see any intentional changes.

### Steps To Reproduce

```[23:19:14 ERR] Unhandled exception in circuit '-fon3C8ojCCadCdqf38gmVYVBWSH7aDjkJNincJUBRI'.
Microsoft.JSInterop.JSException: Could not find 'blazorExtensions.WriteCookie' ('blazorExtensions' was undefined).
Error: Could not find 'blazorExtensions.WriteCookie' ('blazorExtensions' was undefined).
    at https://localhost:5001/_framework/blazor.server.js:1:497
    at Array.forEach (<anonymous>)
    at i.findFunction (https://localhost:5001/_framework/blazor.server.js:1:465)
    at E (https://localhost:5001/_framework/blazor.server.js:1:2608)
    at https://localhost:5001/_framework/blazor.server.js:1:3496
    at new Promise (<anonymous>)
    at Ct.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.server.js:1:3477)
    at https://localhost:5001/_framework/blazor.server.js:1:71954
    at Array.forEach (<anonymous>)
    at Ct._invokeClientMethod (https://localhost:5001/_framework/blazor.server.js:1:71940)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Website.AppState.SetCookie(String key, String value, Int32 days) in C:\Git\Stand\Website\AppState.cs:line 73
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteSynchronously(TaskCompletionSource`1 completion, SendOrPostCallback d, Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteBackground(WorkItem item)
```

```cs
        public async void SetCookie(string key, string value, int days = 12 * 30)
        {
            if(this.Cookie.Any(x => x.Name == key))
                this.Cookie.RemoveAll(x => x.Name == key);

            this.Cookie.Add(new AppState.Cookies
            {
                Name = key,
                Value = value
            });
            
//AppState.cs:line 73
            await _runtime.InvokeAsync<string>("blazorExtensions.WriteCookie", key, value, days);

            //StateChanged();
        }
```

```js
    window.blazorExtensions = {
        WriteCookie: function (name, value, days) {

            var expires;
            if (days) {
                var date = new Date();
                date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
                expires = "; expires=" + date.toGMTString();
            }
            else {
                expires = "";
            }
            document.cookie = name + "=" + value + expires + "; path=/";
        }
    }
```

![image](https://user-images.githubusercontent.com/42449535/158702955-50321037-d36c-4725-a2d3-ee60c93525af.png)
```[2022-03-16T22:38:50.341Z] Error: Microsoft.JSInterop.JSException: Could not find 'blazorExtensions.WriteCookie' ('blazorExtensions' was undefined).
Error: Could not find 'blazorExtensions.WriteCookie' ('blazorExtensions' was undefined).
    at https://localhost:5001/_framework/blazor.server.js:1:497
    at Array.forEach (<anonymous>)
    at i.findFunction (https://localhost:5001/_framework/blazor.server.js:1:465)
    at E (https://localhost:5001/_framework/blazor.server.js:1:2608)
    at https://localhost:5001/_framework/blazor.server.js:1:3496
    at new Promise (<anonymous>)
    at Ct.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.server.js:1:3477)
    at https://localhost:5001/_framework/blazor.server.js:1:71954
    at Array.forEach (<anonymous>)
    at Ct._invokeClientMethod (https://localhost:5001/_framework/blazor.server.js:1:71940)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Website.AppState.SetCookie(String key, String value, Int32 days) in C:\Git\Stand\Website\AppState.cs:line 73
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteSynchronously(TaskCompletionSource`1 completion, SendOrPostCallback d, Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.ExecuteBackground(WorkItem item)
```

### .NET Version

.net core 7 preview 2

**Comment by TanayParikh** [comment]
Based on your error messages, this looks like a Content Security Policy (CSP) issue. The CSP is blocking inline JS scripts. Is the `window.blazorExtensions` within a `<script>` tag within your `.cshtml`? If so, please try putting it in a separate `.js` file. 

On the framework end, I'm not aware of any Preview 1 -> Preview 2 CSP related changes. I wonder what may be causing this... Is your environment and everything else the same?
