### ISSUE TITLE
Blazor - Ambiguous/Duplicate routes for _Host when updating Razor.RuntimeCompilation package to v6.0.3

### ISSUE THREAD

**Issue by SakuraIsayeki** [dotnet/aspnetcore#40742]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Upon upgrading the Microsoft.AspnetCore.Mvc.Razor.RuntimeCompilation package to 6.0.3, my Blazor app was struck by an exception, occuring on each page load. Alledgedly two routes exist for `/_Host`, which causes an exception each time a page other than index is loaded.

This is isolated to v6.0.3 of the package, as it works fine under v6.0.2, and this behaviour has proved consistent after numerous up/downgrades back and forth to isolate this issue.

### Expected Behavior

The page loads, after resolving the one and only route to `/_Host`.

### Steps To Reproduce

This occurs on a Blazor project, with the issue easily reproductible on Debug, with this project, on commit https://github.com/SakuraIsayeki/WOWS-Karma/commit/fb7cb8f3056f406b5d579bb5ee71a7f91fd37b95.

The root cause is as of yet still unknown, as other Blazor projects I've tried to reproduce on don't seem to be affected with this issue. Also, the issue does not strike on Release, as the main website associated with the above project works fine. Safe to assume this is related to Debug-only, which if so, still makes it a pain to debug anything...

### Exceptions (if any)

[20:00:25 ERR] An unhandled exception has occurred while executing the request.
```
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches: 

/_Host
/_Host
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.SelectAsync(HttpContext httpContext, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
```

### .NET Version

6.0.200

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.

**Comment by mkArtakMSFT** [comment]
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project (ideally a GitHub repo) that illustrates the problem.
