### ISSUE TITLE
Blazor <InputFile> component throws Uncaught (in promise) Error

### ISSUE THREAD

**Issue by IvensaMDH** [dotnet/aspnetcore#40772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When uploading a file from Blazor Server (using the progress example from [here](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-6.0&pivots=server#upload-files-with-progress) a JS exception is thrown:

```
Uncaught (in promise) Error: Cannot create a JSStreamReference from the value '[object File]'.
    at g (blazor.server.js:1:1555)
    at T (blazor.server.js:1:5223)
    at blazor.server.js:1:3575
```
Implementation:

```
@using System.IO
@using Microsoft.AspNetCore.Hosting
@inject IWebHostEnvironment env

@if (isLoading)
{
    <p>Progress: @string.Format("{0:P0}", progressPercent)</p>
}
else
{
    <InputFile id="upload" OnChange="OnSubmit" />
}

@code {
    private bool isLoading;
    private decimal progressPercent;

    private async void OnSubmit(InputFileChangeEventArgs e)
    {        
        isLoading = true;

        var path = $"{env.WebRootPath}\\{e.File.Name}";

        await using var fs = new FileStream(path, FileMode.Create);
        using var readStream = e.File.OpenReadStream();
        var bytesRead = 0;
        var totalRead = 0;
        var buffer = new byte[1024 * 10];

        while ((bytesRead = await readStream.ReadAsync(buffer)) > 0)
        {
            totalRead += bytesRead;
            await fs.WriteAsync(buffer, 0, bytesRead);
            progressPercent = Decimal.Divide(totalRead, e.File.Size);
            StateHasChanged();
        }

        isLoading = false;
    }
}
```

Exception is thrown regardless of file type, size or or platform (IIS, WSL, etc..)

### Exceptions (if any)

```
Uncaught (in promise) Error: Cannot create a JSStreamReference from the value '[object File]'.
    at g (blazor.server.js:1:1555)
    at T (blazor.server.js:1:5223)
    at blazor.server.js:1:3575
```

### .NET Version

6.0.201

**Comment by TanayParikh** [comment]
Hello @IvensaMDH, I tried repro'ing the issue with the provided code snippet, however I'm not seeing any errors.

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/14852843/159036776-3316bbb3-b953-4c1d-82f1-8585f3846e8c.png">

Could you please provide a minimal, public, github repository which reproduces this issue?
