### ISSUE TITLE
System.Text.Json NotSupportedException

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/aspnetcore#40799]
Exception message:

```
System.NotSupportedException: Serialization and deserialization of 'System.IntPtr' instances are not supported. Path: $.Data.Exception.TargetSite.MethodHandle.Value.
       ---> System.NotSupportedException: Serialization and deserialization of 'System.IntPtr' instances are not supported.
         at System.Text.Json.Serialization.Converters.UnsupportedTypeConverter`1.Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
         at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
         at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
         at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
         at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state
```

**Comment by danmoseley** [comment]
aspnet folks, could you please help figure out how a JWT token is being passed by aspnet into serialization, other than as a string?

**Comment by BrennanConroy** [comment]
It looks like you're returning an `IActionResult` wrapping a `TokenValidationResult`. `TokenValidationResult` contains `ClaimsIdentity` which is not a serializer friendly type. Even if it was, the `TokenValidationResult` contains multiple dictionaries and lists of claims etc. which you likely don't want your API returning.

**Comment by WeihanLi** [comment]
@BrennanConroy thanks for your reply, yeah, it's returning a `TokenValidationResult` and it's a sample API just for test.
When I use a valid token it would return as expected, only had exception with an invalid token

![image](https://user-images.githubusercontent.com/7604648/159459188-cf0f50dc-4d42-459c-81f2-724dc273b6c1.png)

Feel free to close it if you think it's not a problem, thanks again.

**Comment by BrennanConroy** [comment]
> Feel free to close it if you think it's not a problem, thanks again.

Yeah, I don't think this is an issue in the framework code. If you're curious what's causing the issue you could try to view the exception being thrown from your API and see what types are on it that aren't serializer friendly.

**Comment by shamsullahfayzi** [comment]
get sdf d sd c
[_89d92b03-5475-4bd9-910e-3027f3755eb6__2022-20-27_f3b60c6e-7c34-4502-9d7e-65a4572a3a71Rev MCU Debit Card 22 MAR 22 (1).xls](https://github.com/dotnet/aspnetcore/files/8357315/_89d92b03-5475-4bd9-910e-3027f3755eb6__2022-20-27_f3b60c6e-7c34-4502-9d7e-65a4572a3a71Rev.MCU.Debit.Card.22.MAR.22.1.xls)
