### ISSUE TITLE
Can't established SignalR connection as negotiate results in 404

### ISSUE THREAD

**Issue by AritraSurRoy** [dotnet/aspnetcore#40870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We have 2 applications, one SignalR Server and another SignalR client written in C#. The application works fine for most of our environments but in some cases it is seen that the C# client fails to  establish a connection to the SignalR server. The error message that we get is: **Response status code does not indicate success: 404**. What's more interesting is that for other users on the same machine the client is able to establish a connection with the server but for other users it is unable to do so. Here's the stack trace for the client:
```
 at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync(Uri url, HttpClient httpClient, ILogger logger, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.GetNegotiationResponseAsync(Uri uri, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat, CancellationToken cancellationToken)
   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
```
If we try to skip the negotiate call to the SignalR server from the SignalR client then this results in the error with message: **The server returned status code '404' when status code '101' was expected** and with the following stack trace:
```
at System.Net.WebSockets.WebSocketHandle.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
 at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartAsync(Uri url, TransferFormat transferFormat, CancellationToken cancellationToken)
 at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartTransport(Uri connectUrl, HttpTransportType transportType, TransferFormat transferFormat, CancellationToken cancellationToken)
 at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat, CancellationToken cancellationToken)
 at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat, CancellationToken cancellationToken)
 at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()
 at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
 at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)\r\n at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
 at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
 at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
 at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()
 at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
```
**Note**: I tried to create a POST request to the negotiate endpoint using an HTTP client like Postman and this returns fine with various options for communication with status code 200.

### Expected Behavior

The C# SignalR client must be able to establish a connection with SignalR server.

### Steps To Reproduce

* Create a simple ASP.NET Core app as a SignalR server.
* Create a simple ASP.NET Core app as a SignalR client.

### .NET Version

3.1.0

### Anything else?

OS: Windows Server 2016 Data Center Edition

**Comment by BrennanConroy** [comment]
The fact that you're getting a real response (404) implies that you're hitting the server, so we can temporarily rule out proxies or firewalls. Additionally, if you still get 404's when skipping negotiate, that implies you're either not using multiple servers, or have sticky sessions enabled correctly.

The final reason I can think of that you would get a 404 is that you're hitting the wrong endpoint. Collect Debug or Trace level logs on your server and see what is happening for the failed connections.
https://docs.microsoft.com/aspnet/core/signalr/troubleshoot?view=aspnetcore-6.0#response-code-404

https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-6.0#server-side-logging

**Comment by Roy19** [comment]
But if I was hitting the wrong endpoint then why would the same server and client be working for a different user on the same machine?

**Comment by Roy19** [comment]
I might not be hitting the wrong endpoint as the same server and client works for a different user on the same machine. Might need to enable more logging on the server to pinpoint the error. Thanks.

**Comment by rafikiassumani-msft** [comment]
@Roy19 Have you been able to figure out the issue by looking at your logs?
