### ISSUE TITLE
Unexpected behavior when using Results method as delegate

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/aspnetcore#41082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

``` c#
app.MapGet("/api/HealthCheck", Results.Ok);
```

When I try to access this API, I would get an exception, the exception message likes follows:

### Expected Behavior

Return Ok result

### Steps To Reproduce

``` c#
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();
app.MapGet("/api/HealthCheck", Results.Ok);
app.Run();
```

### Exceptions (if any)

```
Unhandled exception. System.InvalidOperationException: Body was inferred but the method does not allow inferred body parameters.
Below is the list of parameters that we found:

Parameter           | Source
---------------------------------------------------------------------------------
value               | Body (Inferred)


Did you mean to register the "Body (Inferred)" parameter(s) as a Service or apply the [FromService] or [FromBody] attribute?


   at Microsoft.AspNetCore.Http.RequestDelegateFactory.CreateArguments(ParameterInfo[] parameters, FactoryContext factoryContext)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.CreateTargetableRequestDelegate(MethodInfo methodInfo, Expression targetExpression, FactoryContext factoryContext)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.Create(Delegate handler, RequestDelegateFactoryOptions options)
   at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.Map(IEndpointRouteBuilder endpoints, RoutePattern pattern, Delegate handler, Boolean disableInferBodyFromParameters)
   at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapMethods(IEndpointRouteBuilder endpoints, String pattern, IEnumerable`1 httpMethods, Delegate handler)
   at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.MapGet(IEndpointRouteBuilder endpoints, String pattern, Delegate handler)
```

### .NET Version

6.0.200

### Anything else?

ASP.NET Core 6.0

It's Ok to use `app.MapGet("/api/HealthCheck", () => Results.Ok());`

**Comment by halter73** [comment]
The problem is that [Results.Ok](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.results.ok?view=aspnetcore-6.0) is effectively a `Func<object, IResult>` but the `object` is inferred to be a `[FromBody]` parameter to be deserialized as JSON. If it was just a `Func<IResult>`, it probably would have worked. The idiomatic way to right this would be to write a lambda that really is a `Func<IResult>`.

```csharp
app.MapGet("/api/HealthCheck", () => Results.Ok());
```

If you really want to avoid the lambda, you could probably get away with the following which is effective a `RequestDelegate`/`Func<HttpContext, Task>`. I don't really recommend this though.

```csharp
app.MapGet("/api/HealthCheck", Results.Ok().ExecuteAsync);
```

**Comment by WeihanLi** [comment]
@halter73 thanks for your reply, it's ok for me to use `() => Results.Ok()`
