### ISSUE TITLE
Quarantine ClientCertificate_NoOrDelayed_Available_Ignored

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#41131]
## Failing Test(s)

- Interop.FunctionalTests.Http3.Http3TlsTests.ClientCertificate_NoOrDelayed_Available_Ignored(mode: NoCertificate)
- Interop.FunctionalTests.Http3.Http3TlsTests.ClientCertificate_NoOrDelayed_Available_Ignored(mode: DelayCertificate)

## Error Message

```text
System.Net.Http.HttpRequestException: Connection has been shutdown by transport. Error Code: ALPN_NEG_FAILURE (127.0.0.1:61509)
```

## Stacktrace

<details>

```text
System.Net.Http.HttpRequestException : Connection has been shutdown by transport. Error Code: ALPN_NEG_FAILURE (127.0.0.1:61509)
[xUnit.net 00:00:04.71]       ---- System.Net.Quic.QuicException : Connection has been shutdown by transport. Error Code: ALPN_NEG_FAILURE
[xUnit.net 00:00:04.71]       Stack Trace:
[xUnit.net 00:00:04.71]            at System.Net.Http.ConnectHelper.ConnectQuicAsync(HttpRequestMessage request, QuicImplementationProvider quicImplementationProvider, DnsEndPoint endPoint, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken)
[xUnit.net 00:00:04.71]            at System.Net.Http.HttpConnectionPool.GetHttp3ConnectionAsync(HttpRequestMessage request, HttpAuthority authority, CancellationToken cancellationToken)
[xUnit.net 00:00:04.71]            at System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async(HttpRequestMessage request, CancellationToken cancellationToken)
[xUnit.net 00:00:04.71]            at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
[xUnit.net 00:00:04.71]            at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[xUnit.net 00:00:04.71]         /_/src/Shared/TaskExtensions.cs(88,0): at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber)
[xUnit.net 00:00:04.71]         /_/src/Servers/Kestrel/test/Interop.FunctionalTests/Http3/Http3TlsTests.cs(144,0): at Interop.FunctionalTests.Http3.Http3TlsTests.ClientCertificate_NoOrDelayed_Available_Ignored(ClientCertificateMode mode)
[xUnit.net 00:00:04.71]         --- End of stack trace from previous location ---
[xUnit.net 00:00:04.72]         ----- Inner Stack Trace -----
[xUnit.net 00:00:04.72]            at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventShutdownInitiatedByTransport(State state, ConnectionEvent& connectionEvent)
[xUnit.net 00:00:04.72]            at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.NativeCallbackHandler(IntPtr connection, IntPtr context, ConnectionEvent* connectionEvent)
[xUnit.net 00:00:04.72]         --- End of stack trace from previous location ---
[xUnit.net 00:00:04.72]            at System.Net.Http.ConnectHelper.ConnectQuicAsync(HttpRequestMessage request, QuicImplementationProvider quicImplementationProvider, DnsEndPoint endPoint, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken)
```
</details>

## Logs

<details>

```text
Output:
[xUnit.net 00:00:04.72]         | [0.001s] TestLifetime Information: Starting test ClientCertificate_NoOrDelayed_Available_Ignored-DelayCertificate at 2022-04-09T13:09:07
[xUnit.net 00:00:04.72]         | [0.014s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting starting
[xUnit.net 00:00:04.72]         | [0.045s] Microsoft.Hosting.Lifetime Information: Now listening on: https://[::]:61509
[xUnit.net 00:00:04.72]         | [0.046s] Microsoft.AspNetCore.Hosting.Diagnostics Debug: Loaded hosting startup assembly Interop.FunctionalTests
[xUnit.net 00:00:04.72]         | [0.046s] Microsoft.Hosting.Lifetime Information: Application started. Press Ctrl+C to shut down.
[xUnit.net 00:00:04.72]         | [0.046s] Microsoft.Hosting.Lifetime Information: Hosting environment: Production
[xUnit.net 00:00:04.72]         | [0.046s] Microsoft.Hosting.Lifetime Information: Content root path: C:\h\w\A92E0903\w\C0460A5A\e\
[xUnit.net 00:00:04.72]         | [0.046s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting started
[xUnit.net 00:00:04.72]         | [0.890s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Listener has aborted with exception: Operation aborted.
[xUnit.net 00:00:04.72]         | [0.901s] Interop.FunctionalTests.Http3.Http3TlsTests Error: Test threw an exception.
[xUnit.net 00:00:04.72]         | System.Net.Http.HttpRequestException: Connection has been shutdown by transport. Error Code: ALPN_NEG_FAILURE (127.0.0.1:61509)
[xUnit.net 00:00:04.72]         |  ---> System.Net.Quic.QuicException: Connection has been shutdown by transport. Error Code: ALPN_NEG_FAILURE
[xUnit.net 00:00:04.72]         |    at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventShutdownInitiatedByTransport(State state, ConnectionEvent& connectionEvent)
[xUnit.net 00:00:04.72]         |    at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.NativeCallbackHandler(IntPtr connection, IntPtr context, ConnectionEvent* connectionEvent)
[xUnit.net 00:00:04.72]         | --- End of stack trace from previous location ---
[xUnit.net 00:00:04.72]         |    at System.Net.Http.ConnectHelper.ConnectQuicAsync(HttpRequestMessage request, QuicImplementationProvider quicImplementationProvider, DnsEndPoint endPoint, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken)
[xUnit.net 00:00:04.72]         |    --- End of inner exception stack trace ---
[xUnit.net 00:00:04.72]         |    at System.Net.Http.ConnectHelper.ConnectQuicAsync(HttpRequestMessage request, QuicImplementationProvider quicImplementationProvider, DnsEndPoint endPoint, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken)
[xUnit.net 00:00:04.72]         |    at System.Net.Http.HttpConnectionPool.GetHttp3ConnectionAsync(HttpRequestMessage request, HttpAuthority authority, CancellationToken cancellationToken)
[xUnit.net 00:00:04.72]         |    at System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async(HttpRequestMessage request, CancellationToken cancellationToken)
[xUnit.net 00:00:04.72]         |    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
[xUnit.net 00:00:04.72]         |    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[xUnit.net 00:00:04.72]         |    at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 88
[xUnit.net 00:00:04.72]         |    at Interop.FunctionalTests.Http3.Http3TlsTests.ClientCertificate_NoOrDelayed_Available_Ignored(ClientCertificateMode mode) in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/Http3/Http3TlsTests.cs:line 144
[xUnit.net 00:00:04.72]         |    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
[xUnit.net 00:00:04.72]         | --- End of stack trace from previous location ---
[xUnit.net 00:00:04.72]         |    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
[xUnit.net 00:00:04.72]         |    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 96
[xUnit.net 00:00:04.72]         | [0.903s] TestLifetime Information: Finished test ClientCertificate_NoOrDelayed_Available_Ignored-DelayCertificate in 0.9016049s
  Passed Interop.FunctionalTests.Http2.Http2RequestTests.GET_RequestReturnsLargeData_GracefulShutdownDuringRequest_RequestGracefullyCompletes(hasTrailers: True) [1 s]
  Failed Interop.FunctionalTests.Http3.Http3TlsTests.ClientCertificate_NoOrDelayed_Available_Ignored(mode: NoCertificate) [243 ms]
  Error Message:
   System.Net.Http.HttpRequestException : Connection has been shutdown by transport. Error Code: ALPN_NEG_FAILURE (127.0.0.1:61505)
---- System.Net.Quic.QuicException : Connection has been shutdown by transport. Error Code: ALPN_NEG_FAILURE
  Stack Trace:
     at System.Net.Http.ConnectHelper.ConnectQuicAsync(HttpRequestMessage request, QuicImplementationProvider quicImplementationProvider, DnsEndPoint endPoint, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp3ConnectionAsync(HttpRequestMessage request, HttpAuthority authority, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 88
   at Interop.FunctionalTests.Http3.Http3TlsTests.ClientCertificate_NoOrDelayed_Available_Ignored(ClientCertificateMode mode) in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/Http3/Http3TlsTests.cs:line 144
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventShutdownInitiatedByTransport(State state, ConnectionEvent& connectionEvent)
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.NativeCallbackHandler(IntPtr connection, IntPtr context, ConnectionEvent* connectionEvent)
--- End of stack trace from previous location ---
   at System.Net.Http.ConnectHelper.ConnectQuicAsync(HttpRequestMessage request, QuicImplementationProvider quicImplementationProvider, DnsEndPoint endPoint, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken)
```
</details>

## Build

- https://dev.azure.com/dnceng/public/_build/results?buildId=1708846&view=logs&jobId=3f6d4e0f-1b71-56b5-361e-d95b6e6da15a&j=3f6d4e0f-1b71-56b5-361e-d95b6e6da15a&t=e4ee6667-9b0a-5a6e-4e24-bcba939f2af2

**Comment by Tratcher** [comment]
This is a product bug / feature gap. Tracked by https://github.com/dotnet/runtime/issues/57308.
