### ISSUE TITLE
Breaking Change in .Net 6 - WebApplicationFactory Bug with MVC

### ISSUE THREAD

**Issue by srpeirce** [dotnet/aspnetcore#41195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is a bug when running WebApplicationFactory tests that it looks for the `wwwroot` directory in the directory where the application was built.

This means that tests pass when running via an IDE.

## Why is this a problem?

We have some tests which run against Azure resources. The tests are copied into a container, meaning we can set `Managed Identities` to the pod (as opposed to giving excessive permissions to pipeline).

The tests running inside the pod are looking for the build directory, which does not exist.

> This is a breaking change since upgrading from .Net 5 to .Net 6.

### Expected Behavior

The tests should pass and should not be dependent on the original source directory being present.

### Steps To Reproduce

We can recreate the problem more simply without needing to use Docker.

1. Clone this repo: https://github.com/srpeirce/Net6WebApplicationFactoryBug
2. Build the solution. 
```
dotnet build -c Release
```
3. Copy files from `.\Net6WebApplicationFactoryBug\SteveTest.Web.IntegrationTests\bin\Release\net6.0\` to a new directory, for example `c:\_temp\WafTest`
4. Navigate to new directory in terminal `cd C:\_Temp\WafTest\`
5. Run the Tests, and it will PASS
```
dotnet test .\SteveTest.Web.IntegrationTests.dll
```
6. Now rename the original source directory so that the path is different, e.g. renaming `.\Net6WebApplicationFactoryBug` to `.\Net6WebApplicationFactoryBug2`
7. Navigate to new directory in terminal `cd C:\_Temp\WafTest\`
8. Run the Tests, and it will FAIL
```
dotnet test .\SteveTest.Web.IntegrationTests.dll
```

### Exceptions (if any)

```
PS C:\_Temp\WafTest> dotnet test .\SteveTest.Web.IntegrationTests.dll
Microsoft (R) Test Execution Command Line Tool Version 17.1.0
Copyright (c) Microsoft Corporation.  All rights reserved.
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:02.10]     SteveTest.Web.IntegrationTests.UnitTest1.Test1 [FAIL]
  Failed SteveTest.Web.IntegrationTests.UnitTest1.Test1 [1 ms]
  Error Message:
   System.IO.DirectoryNotFoundException : C:\Code\Net6WebApplicationFactoryBug\SteveTest.Web\wwwroot\
  Stack Trace:
     at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.<>c.<UseStaticWebAssetsCore>b__1_0(String contentRoot)
   at Microsoft.AspNetCore.StaticWebAssets.ManifestStaticWebAssetFileProvider..ctor(StaticWebAssetManifest manifest, Func`2 fileProviderFactory)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssetsCore(IWebHostEnvironment environment, Stream manifest)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssets(IWebHostEnvironment environment, IConfiguration configuration)
   at Microsoft.AspNetCore.WebHost.<>c.<ConfigureWebDefaults>b__9_0(WebHostBuilderContext ctx, IConfigurationBuilder cb)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass9_0.<ConfigureAppConfiguration>b__0(HostBuilderContext context, IConfigurationBuilder builder)
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Program.<Main>$(String[] args) in C:\Code\Net6WebApplicationFactoryBug\SteveTest.Web\Program.cs:line 1
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.CreateHost()
   at Microsoft.Extensions.Hosting.HostFactoryResolver.<>c__DisplayClass10_0.<ResolveHostFactory>b__0(String[] args)
   at Microsoft.AspNetCore.Mvc.Testing.DeferredHostBuilder.Build()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateHost(IHostBuilder builder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.ConfigureHostBuilder(IHostBuilder hostBuilder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.EnsureServer()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.get_Server()
   at SteveTest.Web.IntegrationTests.UnitTest1..ctor(WebApplicationFactory`1 factory) in C:\Code\Net6WebApplicationFactoryBug\SteveTest.Web.IntegrationTests\UnitTest1.cs:line 15

Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: < 1 ms - SteveTest.Web.IntegrationTests.dll (net6.0)
```

### .NET Version

6.0.202

### Anything else?

```
PS C:\_Temp\WafTest> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.202\

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  5.0.407 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by srpeirce** [comment]
Additionally, here is simple .Net5 repo showing that it works in Net5.
[https://github.com/srpeirce/Net6_Net5WebApplicationFactoryBug](https://github.com/srpeirce/Net6_Net5WebApplicationFactoryBug)

## Steps to show .Net 5 works

1. Clone this repo: [https://github.com/srpeirce/Net6_Net5WebApplicationFactoryBug](https://github.com/srpeirce/Net6_Net5WebApplicationFactoryBug)
2. Build the solution.
```
dotnet build -c Release
```
3a. Copy files from .\Net5WebApplicationFactory\SteveTest.Web.IntegrationTests\bin\Release\net6.0\ to a new directory, for example c:\_temp\Waf5
3b. [Additional Step compared to .Net6] - Copy the `Net5WebApplicationFactory.sln` and `Mvc5.Web` into c:\_temp\Waf5 as well.

4. Navigate to new directory in terminal cd C:\_Temp\Waf5\
5. Run the Tests, and it will PASS
```
PS C:\_Temp\Waf5> dotnet test .\Mvc5.Web.IntegrationTests.dll
```
6. Now rename the original source directory so that the path is different, e.g. renaming `.\Net5WebApplicationFactory` to `.\Net5WebApplicationFactory2`
7. Navigate to new directory in terminal cd C:\_Temp\Waf5\
8. Run the Tests, and it will [still] PASS

```
PS C:\_Temp\Waf5> dotnet test .\Mvc5.Web.IntegrationTests.dll
```

**Comment by halter73** [comment]
@javiercn Do you have any idea what's going on here? It has a good repro, and I notice that in net6.0 `SteveTest.Web.staticwebassets.runtime.json` shows up in the `SteveTest.Web.IntegrationTests` bin folder when it didn't in net5.0. I haven't dug into why yet, but I figured you might know.

**Comment by javiercn** [comment]
@halter73 I suspect that what's happening here is that the files are being copied to a separate machine/box where they are being run. If they don't have web content for their tests they can disable static web assets using `<StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>`. If they do have web content in their app there are two things they can do:
* Publish the app and use the published output results (this doesn't really work with WebApplicationFactory).
* Update the paths in `.staticwebassets.runtime.json` to match the expected paths on the VM.

In essence, what is happening here is that moving the outputs from the build to a separate machine and running them is not something supported by static web assets. Since their V1 we hardcode full paths on the file because we want to avoid any situation that could result in an ambiguity or in serving an unexpected file (we essentially only serve files from a set of well-known paths on the machine known at build time).

What the docker tooling for VS does in this situation is create their own file (you can pass in an alternative file via a config key) that contains a set of equivalent paths on the container and then they map those paths to the host machine.

**Comment by halter73** [comment]
@javiercn Do you have any idea what changed between the .NET 5 and .NET 6 SDKs that prevented the `staticwebassets.runtime.json` file from being generated before or is causing it to be generated now? Is this something that might be fixed by https://github.com/dotnet/sdk/pull/25011?

Like I said, the repro is very easy to try for yourself. I could debug it, but I'm trying to avoid debugging msbuild tasks where I don't really even know what the expected behavior is. Would it make more sense to reassign this issue to you?

**Comment by javiercn** [comment]
@halter73 I don't think there is anything for us to do here. The scenario mentioned is not supported and never has been, it wouldn't have worked in 5.0 either because the paths that we've burnt to disk have always been absolute.

The other PR referenced is completely irrelevant to this. The options are as I mentioned above:
* Disable static web assets if they are not using them.
* Update the paths after publish manually to match the expected paths on the container.

If you still have questions, feel free to ping me on Teams and we can chat.

**Comment by captainsafia** [comment]
@srpeirce The WebApplicationFactory has different rules of precedence the content root to use when testing. The precedence in .NET 5 was as follows:

- Evaluate the `ASPNETCORE_TEST_CONTENTROOT_APPNAME` environment variable
- Evaluate the content root embedded in the assembly metadata of the app under test
- Sets the content root relative to the solution file it finds in the execution directory (which explains your workaround above)

The precedence in .NET 6 is as follows:

- Evaluate the `ASPNETCORE_TEST_CONTENTROOT_APPNAME` environment variable
- Evaluate the content root stored in the new `MvcTestingAppManifest.json` file (**new**)
- Evaluate the content root embedded in the assembly metadata of the app under test
- Sets the content root relative to the solution file it finds in the execution directory

I believe the difference you are seeing is a result of the change in precedence above. Can you try setting the environment variable above and see if that resolves the issue?
