### ISSUE TITLE
Route handler filters don't handle all return types

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#41213]
Filters currently wrap the user delegate in a `ValueTask<object?>` before handing off the function to the normal route handling logic. This causes issues with any non object returning methods like `void`, `Task`, `Task<T>`, etc. returning methods.

### Void returning method with no-op filter:
```csharp
void Method() { }
app.MapGet("/method", Method).AddFilter((c, n) => n(c));
```
Output:
> ArgumentException: Expression of type 'System.Void' cannot be used for parameter of type 'System.Object' of method 'System.Threading.Tasks.ValueTask`1[System.Object] WrapObjectAsValueTask(System.Object)' (Parameter 'arg0')

### Task returning method with no-op filter:
```csharp
Task Method() => Task.CompletedTask;
app.MapGet("/method", Method).AddFilter((c, n) => n(c));
```
Output:
> {"result":{},"id":54,"exception":null,"status":5,"isCanceled":false,"isCompleted":true,"isCompletedSuccessfully":true,"creationOptions":0,"asyncState":null,"isFaulted":false}

**Comment by lohithgn** [comment]
@BrennanConroy @danroth27 
I cant event compile the code snippet provided in Preview 3 blog post:
```
app.MapGet("/hello/{name}", (string name) => $"Hello, {name}!")
    .AddFilter((context, next) =>
    {
        var name = (string) context.Parameters[0];
        if (name == "Bob")
        {
            return Result.Problem("No Bob's allowed");
        }
        return next(context);
    });
```
It throws up error: cannot convert type IResult to ValueTask<Object?>
![image](https://user-images.githubusercontent.com/2450336/163663307-f9d5aff2-7b51-4e2b-acf2-43fd3a2cc2a0.png)

I found @captainsafia example here: https://github.com/captainsafia/MinimalFiltersExample/blob/main/Program.cs

Code compiles but i have a run time exception for next delegate:
![image](https://user-images.githubusercontent.com/2450336/163663363-2c57fbee-c67b-4b7e-aca6-7b830799e6d4.png)

Stack trace:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method2(Closure, RouteHandlerInvocationContext)
   at Program.<>c__DisplayClass0_0.<<<Main>$>b__3>d.MoveNext() in C:\w\aspnet\WebApplication1\Program.cs:line 13
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteObjectReturn(Object obj, HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
How do we get this to work ?

**Comment by BrennanConroy** [comment]
The null ref is issue https://github.com/dotnet/aspnetcore/issues/41188, you can workaround it by using a method instead of an inline delegate.
