### ISSUE TITLE
[dotnet-sdk-7.0.100-preview.4.22218.29] grpc-dotnet-2.40.0 Functional Test failed with System.Net.Http.HttpRequestException

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/aspnetcore#41297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

grpc-dotnet-2.40.0 Functional Test failed with System.Net.Http.HttpRequestException when running it with .NET 7 Preview 4 build.

**Application Name**:  grpc-dotnet-2.40.0
**OS**: Windows 10 RS5
**CPU**: X64
**.NET Build Number**: 7.0.100-preview.4.22218.29

App and App Source checking at: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1527243 

 **Verify Scenarios:**
1). Windows10 RS5 x64+dotnet-sdk-7.0.100-preview.4.22218.29 Fail
2). Windows10 RS5 x64+dotnet-sdk-7.0.100-preview.4.22215.7: Pass
3). Windows10 RS5 x64+6.0.202: Pass

**Failed Test Name** : 
UnaryMethod_DeadlineExceededCall_PollingCountersUpdatedCorrectly

### Expected Behavior

Test should be passed

### Steps To Reproduce

**This is .net6.0 tests, but we are running it on 7.0, machine only have 7.0 installed, and DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX=2, so it runs on 7.0**

Execute test by : 
```
dotnet vstest Grpc.AspNetCore.FunctionalTests.dll /tests:UnaryMethod_DeadlineExceededCall_PollingCountersUpdatedCorrectly

```

### Exceptions (if any)

**Actual Result**:
  Failed UnaryMethod_DeadlineExceededCall_PollingCountersUpdatedCorrectly [872 ms]
  Error Message:
```
     Expected: DeadlineExceeded
  But was:  Unavailable

  Stack Trace:
     at Grpc.AspNetCore.FunctionalTests.Client.EventSourceTests.UnaryMethod_DeadlineExceededCall_PollingCountersUpdatedCorrectly() in C:\source code\grpc-dotnet\test\FunctionalTests\Client\EventSourceTests.cs:line 238
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: 872 ms -

```
**Findings :**

We think fail is related to Microsoft.AspNetCore.Server.Kestrel.Core.dll
When we replace working dll from 7.0.100-preview.4.22215.7, test will PASS

This error not repro on later versions of grpc-dotnet

```
Test Detail Summary :
 UnaryMethod_DeadlineExceededCall_PollingCountersUpdatedCorrectly
   Source: EventSourceTests.cs line 177
   Duration: 847 ms

  Message: 
  Expected: DeadlineExceeded
  But was:  Unavailable

  Stack Trace: 
EventSourceTests.UnaryMethod_DeadlineExceededCall_PollingCountersUpdatedCorrectly() line 239
GenericAdapter`1.BlockUntilCompleted()
NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
AsyncToSyncAdapter.Await(Func`1 invoke)
TestMethodCommand.RunTestMethod(TestExecutionContext context)
TestMethodCommand.Execute(TestExecutionContext context)
<>c__DisplayClass1_0.<Execute>b__0()
BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

  Standard Output: 
0.003s GrpcTestContext - Information: Starting EventSourceTests.UnaryMethod_DeadlineExceededCall_PollingCountersUpdatedCorrectly
0.012s GrpcTestContext - Information: Iteration 1
0.030s SERVER Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder - Trace: Discovering gRPC methods for FunctionalTestsWebsite.Infrastructure.DynamicService.
0.031s SERVER Grpc.AspNetCore.Server.Model.Internal.BinderServiceMethodProvider - Debug: Could not find bind method for FunctionalTestsWebsite.Infrastructure.DynamicService.
0.032s SERVER Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder - Trace: Added gRPC method '36490b0a-dc53-4b64-ae97-d6d08bea967c' to service 'DynamicService'. Method type: 'Unary', route pattern: '/DynamicService/36490b0a-dc53-4b64-ae97-d6d08bea967c'.
0.064s Grpc.Net.Client.Internal.GrpcCall - Debug: Starting gRPC call. Method type: 'Unary', URI: 'http://127.0.0.1:50050/DynamicService/36490b0a-dc53-4b64-ae97-d6d08bea967c'.
0.112s GrpcTestContext - Information: Asserting 'Server call in progress'. Expected values: calls-failed: 0, calls-deadline-exceeded: 0
0.120s Grpc.AspNetCore.FunctionalTests.Infrastructure.TestEventListener - Debug: Check 1: calls-failed current value 0 matched expected 0.
0.121s Grpc.AspNetCore.FunctionalTests.Infrastructure.TestEventListener - Debug: Check 1: calls-deadline-exceeded current value 0 matched expected 0.
0.121s SERVER Microsoft.AspNetCore.Server.Kestrel.Connections - Debug: Connection id "0HMH3CHUD7F55" accepted.
0.124s GrpcTestContext - Information: Matched 'Server call in progress'. Expected values: calls-failed: 0, calls-deadline-exceeded: 0
0.124s GrpcTestContext - Information: Asserting 'Client call in progress'. Expected values: calls-failed: 0, calls-deadline-exceeded: 0
0.125s SERVER Microsoft.AspNetCore.Server.Kestrel.Connections - Debug: Connection id "0HMH3CHUD7F55" started.
0.129s Grpc.Net.Client.Internal.GrpcCall - Debug: Sending message.
0.133s Grpc.Net.Client.Internal.GrpcCall - Trace: Serialized 'Greet.HelloRequest' to 0 byte message.
0.136s Grpc.AspNetCore.FunctionalTests.Infrastructure.TestEventListener - Debug: Check 1: calls-failed current value 0 matched expected 0.
0.136s Grpc.AspNetCore.FunctionalTests.Infrastructure.TestEventListener - Debug: Check 1: calls-deadline-exceeded current value 0 matched expected 0.
0.143s GrpcTestContext - Information: Matched 'Client call in progress'. Expected values: calls-failed: 0, calls-deadline-exceeded: 0
0.144s Grpc.Net.Client.Internal.GrpcCall - Trace: Message sent.
0.149s SERVER Microsoft.AspNetCore.Server.Kestrel.Http2 - Trace: Connection id "0HMH3CHUD7F55" sending SETTINGS frame for stream ID 0 with length 18 and flags NONE.
0.150s SERVER Microsoft.AspNetCore.Server.Kestrel.Http2 - Trace: Connection id "0HMH3CHUD7F55" sending WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0.
0.150s SERVER Microsoft.AspNetCore.Server.Kestrel.Http2 - Trace: Connection id "0HMH3CHUD7F55" received SETTINGS frame for stream ID 0 with length 12 and flags NONE.
0.151s SERVER Microsoft.AspNetCore.Server.Kestrel.Http2 - Trace: Connection id "0HMH3CHUD7F55" sending SETTINGS frame for stream ID 0 with length 0 and flags ACK.
0.151s SERVER Microsoft.AspNetCore.Server.Kestrel.Http2 - Trace: Connection id "0HMH3CHUD7F55" received WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0.
0.151s SERVER Microsoft.AspNetCore.Server.Kestrel.Http2 - Trace: Connection id "0HMH3CHUD7F55" received HEADERS frame for stream ID 1 with length 252 and flags END_HEADERS.
0.169s SERVER Microsoft.AspNetCore.Server.Kestrel.Http2 - Trace: Connection id "0HMH3CHUD7F55" received DATA frame for stream ID 1 with length 5 and flags NONE.
0.170s SERVER Microsoft.AspNetCore.Server.Kestrel.Http2 - Trace: Connection id "0HMH3CHUD7F55" received DATA frame for stream ID 1 with length 0 and flags END_STREAM.
0.170s SERVER Microsoft.AspNetCore.Server.Kestrel.Http2 - Trace: Connection id "0HMH3CHUD7F55" received SETTINGS frame for stream ID 0 with length 0 and flags ACK.
0.174s SERVER Microsoft.AspNetCore.Hosting.Diagnostics - Information: Request starting HTTP/2 POST http://127.0.0.1:50050/DynamicService/36490b0a-dc53-4b64-ae97-d6d08bea967c application/grpc -
0.194s SERVER Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware - Debug: Request matched endpoint 'gRPC - /DynamicService/36490b0a-dc53-4b64-ae97-d6d08bea967c'
0.202s SERVER Microsoft.AspNetCore.Routing.EndpointMiddleware - Information: Executing endpoint 'gRPC - /DynamicService/36490b0a-dc53-4b64-ae97-d6d08bea967c'
0.209s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Trace: Request deadline timeout of 00:00:00.5000000 started.
0.212s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Debug: Reading message.
0.213s SERVER Microsoft.AspNetCore.Server.Kestrel - Debug: Connection id "0HMH3CHUD7F55", Request id "0HMH3CHUD7F55:00000001": started reading request body.
0.213s SERVER Microsoft.AspNetCore.Server.Kestrel - Debug: Connection id "0HMH3CHUD7F55", Request id "0HMH3CHUD7F55:00000001": done reading request body.
0.215s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Trace: Deserializing 0 byte message to 'Greet.HelloRequest'.
0.218s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Trace: Received message.
0.220s GrpcTestContext - Information: On server.
0.732s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Debug: Request with timeout of 00:00:00.5000000 has exceeded its deadline.
0.736s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Debug: Resetting response stream with error code 0.
0.738s SERVER Microsoft.AspNetCore.Server.Kestrel.Http2 - Debug: Trace id "0HMH3CHUD7F55:00000001": HTTP/2 stream error "NO_ERROR". A Reset is being sent to the stream.
Microsoft.AspNetCore.Connections.ConnectionAbortedException: The HTTP/2 stream was reset by the application with error code NO_ERROR.
0.739s SERVER Microsoft.AspNetCore.Server.Kestrel.Http2 - Trace: Connection id "0HMH3CHUD7F55" sending HEADERS frame for stream ID 1 with length 110 and flags END_HEADERS.
0.740s SERVER Microsoft.AspNetCore.Server.Kestrel.Http2 - Trace: Connection id "0HMH3CHUD7F55" sending RST_STREAM frame for stream ID 1 with length 4 and flags 0x0.
0.746s Grpc.Net.Client.Internal.GrpcCall - Error: Error starting gRPC call.
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The request was aborted.
 ---> System.Net.Http.Http2StreamException: The HTTP/2 server reset the stream. HTTP/2 error code 'NO_ERROR' (0x0).
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders()
   at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout) in F:\Unitest\grpc-dotnet\src\Grpc.Net.Client\Internal\GrpcCall.cs:line 443
0.771s Grpc.Net.Client.Internal.GrpcCall - Information: Call failed with gRPC error status. Status code: 'Unavailable', Message: 'Error starting gRPC call. HttpRequestException: An error occurred while sending the request. IOException: The request was aborted. Http2StreamException: The HTTP/2 server reset the stream. HTTP/2 error code 'NO_ERROR' (0x0).'.
0.771s Grpc.Net.Client.Internal.GrpcCall - Debug: Finished gRPC call.
0.772s Grpc.Net.Client.Internal.GrpcCall - Debug: gRPC call canceled.
0.773s SERVER Microsoft.AspNetCore.Server.Kestrel.Http2 - Trace: Connection id "0HMH3CHUD7F55" received PING frame for stream ID 0 with length 8 and flags NONE.
0.774s SERVER Microsoft.AspNetCore.Server.Kestrel.Http2 - Trace: Connection id "0HMH3CHUD7F55" sending PING frame for stream ID 0 with length 8 and flags ACK.
0.840s SERVER Grpc.AspNetCore.Server.ServerCallHandler - Trace: Request deadline stopped.
0.841s GrpcTestContext - Information: Finishing EventSourceTests.UnaryMethod_DeadlineExceededCall_PollingCountersUpdatedCorrectly

```

### .NET Version

7.0.100-preview.4.22218.29

### Anything else?

```
.NET SDK:
Version: 7.0.100-preview.4.22218.29
Commit: 789db9e502

Runtime Environment:
OS Name: Windows
OS Version: 10.0.19044
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\7.0.100-preview.4.22218.29\

global.json file:
Not found

Host:
Version: 7.0.0-preview.4.22217.5
Architecture: x64
Commit: 74e1d4df57

.NET SDKs installed:
7.0.100-preview.4.22218.29 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
Microsoft.AspNetCore.App 7.0.0-preview.4.22218.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 7.0.0-preview.4.22217.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 7.0.0-preview.4.22217.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
https://aka.ms/dotnet/runtimes-sdk-info
```

@dotnet-actwx-bot @dotnet/compat

**Comment by JamesNK** [comment]
The server has changed the timing of how it writes frames. I think this has exposed a race in the client - https://github.com/dotnet/runtime/issues/68373

**Comment by adityamandaleeka** [comment]
Closing since it's being tracked in https://github.com/dotnet/runtime/issues/68373
