### ISSUE TITLE
Caching StackExchangeRedis throws exception when using Twemproxy

### ISSUE THREAD

**Issue by sgtfrankieboy** [dotnet/aspnetcore#41320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Starting from version 6.0.2 of Microsoft.Extensions.Caching.StackExchangeRedis there is a breaking bug which causes the exception mentioned below to occur when using Redis behind a proxy like Twemproxy.

The bug is caused by commit https://github.com/dotnet/aspnetcore/commit/85a090053585a76203eb6ffcdcd6d95d55fba847. 

Specifically the `_connection.GetServer(endPoint)` call in `ValidateServerFeatures()`. This is call is unsupported when using the build in proxy functionality of StackExchangeRedis, as they have a limited feature set.

The exception is being thrown here: https://github.com/StackExchange/StackExchange.Redis/blob/f0fa79c59700a58a1cb848175c544e82ff0d2180/src/StackExchange.Redis/ConnectionMultiplexer.cs#L1021

### Expected Behavior

I expect `IDistributedCache` to keep working when using Redis behind Twemproxy like it did in version 6.0.0 

### Steps To Reproduce

Make use of `IDistributedCache` using Redis behind Twemproxy. No easy way to make a repro project of this.

### Exceptions (if any)

```
System.NotSupportedException: The server API is not available via twemproxy
   at StackExchange.Redis.ConnectionMultiplexer.GetServer(EndPoint endpoint, object asyncState) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1504
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.ValidateServerFeatures()
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache+<ConnectAsync>d__22.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache+<SetAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FooBar.FooCache+<SetDistributed>d__22<TItem>.MoveNext() in FooBar/FooCache.cs:line 319
```

### .NET Version

6.0.100

### Anything else?

N/A

**Comment by Tratcher** [comment]
That change https://github.com/dotnet/aspnetcore/issues/38715 fixed a regression from 5.0 where Caching.StackExchangeRedis no longer worked with older versions of Redis. If Twemproxy dose not support this call then it did not work prior to .NET 6, and also wouldn't work with older versions of Redis.

For Triage: We can't have it both ways unless we introduce a new option.

**Comment by sgtfrankieboy** [comment]
We were using Twemproxy with StackExchangeRedis and IDistributedCache just fine in .NET Core 3.1 

Can't you detect if a proxy is being used in StackExchangeRedis and skip that check? This change blocks us from upgrading the package as its breaking.

**Comment by bladefist** [comment]
The StackExchange `ConfigurationOptions` provide for defining if it's a proxy for this purpose.  It allows for a reduced featureset.

**Comment by adityamandaleeka** [comment]
Triage: we should check if the first invocation of `GetServer` throws and then just use the old set script. It would be nice to log when this happens if that's possible.

Another fix would be to detect if there's a proxy and avoid calling it in the first place.
