### ISSUE TITLE
Generic host/kestrel known cases proper error handling

### ISSUE THREAD

**Issue by maxcherednik** [dotnet/aspnetcore#41328]
Re-creating #29801, only one issue was addressed there.

**Summary**

I would like to provide a better operations experience and reduce the maintenance burden.

What we have right now:

```C#
public class Program
    {
        public static async Task<int> Main(string[] args)
        {
            await CreateHostBuilder(args).Build().RunAsync();

            return 0;
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder => { webBuilder.UseStartup<Startup>(); });
    }
```

If someone from the ops team, happened to install our application on a server where there is something already running on port 443, then they will receive and ugly stack trace:

```
Unhandled exception. System.IO.IOException: Failed to bind to address https://127.0.0.1:7004: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
 ---> System.Net.Sockets.SocketException (48): Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass30_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.LocalhostListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Microsoft.AspNetCore.Builder.WebApplication.Run(String url)
   at Program.<Main>$(String[] args) in /Users/maximcherednik/Projects/WebApplication1/WebApplication1/Program.cs:line 25
```

In this stack trace there is only one line of useful information, the rest is just noise, which is not need for an ops person.
Would not it be better to log something like this:

It seems that there is another application running on port (port number here)
My general judgment around the stack traces in the log file is pretty simple: **you see a stack trace - it a bug!**

@Tratcher says https://github.com/dotnet/aspnetcore/issues/5920#issuecomment-453149464 that failing to bind is fatal. Yes it is for the kestrel, but it is a known case.

The case is just a misconfiguration of the environment where an ops person picked either the wrong port or picked the wrong machine to install the application. If we look at this problem from such perspective, it does not deserve a huge noisy stack trace in the log file.

There is another use case of misconfiguration which happens to us like every day.
An ops person installs the application with https and somehow forgets/misconfigures the certificates. Again, there is no need to scary an ops person with an ugly stack trace. Taking into account the fact that not all the ops guys are equally experienced, they often just come back to the developers and ask: _what does this stack trace mean?_

**Work around example**
This is what I have to do now.

```C#
public class Program
    {
        public static async Task<int> Main(string[] args)
        {

            var host = CreateHostBuilder(args).Build();
            
            try
            {
                await host.RunAsync();
            }
            //catch(AnotherException e) // related to a fact that the application was configured to run with https, but administrator forgot/misconfigured ssl certificates  
            //{
                // var logger = host.Services.GetRequiredService<ILogger<Program>>();
                //
                // logger.LogError("The application was configured to run with https, but no certificates found...");
                //     
                // return -100; // return known error code
            //}
            catch (IOException e) when (e.InnerException is AddressInUseException)
            {
                var logger = host.Services.GetRequiredService<ILogger<Program>>();
                
                // it would be cool to speak in a human language without any stack traces
                logger.LogError("It seems that there is another application running on port (80)");
                
                return -1; // return known error code 
            }

            return 0;
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder => { webBuilder.UseStartup<Startup>(); });
    }
```

Obviously there are multiple things wrong here:

- I am catching exceptions which are not officially described on the generic host level
- The logger is not available anymore, cause everything is disposed already.

**Design proposition**
It is difficult to propose something specific, cause I don't have the full picture.

**Requirements:**

Possibility to control the exit code to be non-zero.
Possibility to control the message written to the log file

**Comment by Tratcher** [comment]
A few points:
- Yes, this isn't a very graceful shutdown experience.
- The Host API doesn't directly control the process lifetime or the exit code, those are fully in your control.
- Changing this behavior would be breaking for people that already check for this exception and use that to control process lifetime.
- This isn't something we've had sufficient feedback about to warrant a breaking change. If we get more feedback and requirements around this we might reconsider.
- It is possible to use the logger in your approach by replacing RunAsync with StartAsync as shown here:
https://github.com/dotnet/runtime/blob/2be87c9c976c0cd21b66ea12ae406a559aacaac0/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/HostingAbstractionsHostExtensions.cs#L60-L79

**Comment by maxcherednik** [comment]
> The Host API doesn't directly control the process lifetime or the exit code, those are fully in your control.

Yeah, that is clear. If there is an exception, I can convert it to whatever error code.

> Changing this behavior would be breaking for people that already check for this exception and use that to control process lifetime.
This isn't something we've had sufficient feedback about to warrant a breaking change. If we get more feedback and requirements around this we might reconsider.

Yeah, that is a classic problem I guess - people starting to rely on the side effects and then putting it back on the proper track considered a breaking change. Especially for such a popular framework.

> It is possible to use the logger in your approach by replacing RunAsync with StartAsync as shown here:
https://github.com/dotnet/runtime/blob/2be87c9c976c0cd21b66ea12ae406a559aacaac0/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/HostingAbstractionsHostExtensions.cs#L60-L79

Thank you for the hint. Will try that.
