### ISSUE TITLE
Quarantine Interop.FunctionalTests.HttpClientHttp2InteropTests.Settings_MaxFrameSize_Larger_Server

### ISSUE THREAD

**Issue by sebastienros** [dotnet/aspnetcore#41363]
## Failing Test(s)

- Interop.FunctionalTests.HttpClientHttp2InteropTests.Settings_MaxFrameSize_Larger_Server

## Error Message

```text
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.IO.IOException : The request was aborted.
-------- System.IO.IOException : The decryption operation failed, see inner exception.
------------ System.ComponentModel.Win32Exception : The specified data could not be decrypted.
```

## Stacktrace

<details>

```text
  at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 106
   at Interop.FunctionalTests.HttpClientHttp2InteropTests.Settings_MaxFrameSize_Larger_Server(String scheme) in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/HttpClientHttp2InteropTests.cs:line 1332
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders()
   at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
----- Inner Stack Trace -----
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
----- Inner Stack Trace -----
```
</details>

## Logs

<details>

[console.81d8b6d0.txt](https://github.com/dotnet/aspnetcore/files/8556931/console.81d8b6d0.txt)

</details>

<details>

```
[xUnit.net 00:00:05.92]         | [0.001s] TestLifetime Information: Starting test Settings_MaxFrameSize_Larger_Server-https at 2022-04-25T16:07:46
[xUnit.net 00:00:05.92]         | [0.004s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting starting
[xUnit.net 00:00:05.92]         | [0.022s] Microsoft.Hosting.Lifetime Information: Now listening on: https://127.0.0.1:49526
[xUnit.net 00:00:05.92]         | [0.022s] Microsoft.AspNetCore.Hosting.Diagnostics Debug: Loaded hosting startup assembly Interop.FunctionalTests
[xUnit.net 00:00:05.92]         | [0.023s] Microsoft.Hosting.Lifetime Information: Application started. Press Ctrl+C to shut down.
[xUnit.net 00:00:05.92]         | [0.023s] Microsoft.Hosting.Lifetime Information: Hosting environment: Production
[xUnit.net 00:00:05.92]         | [0.023s] Microsoft.Hosting.Lifetime Information: Content root path: C:\h\w\B80109DC\w\A9FA0985\e\
[xUnit.net 00:00:05.92]         | [0.023s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting started
[xUnit.net 00:00:05.92]         | [0.028s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMH6QMTDL8OD" accepted.
[xUnit.net 00:00:05.92]         | [0.028s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMH6QMTDL8OD" started.
[xUnit.net 00:00:05.92]         | [0.031s] Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware Debug: Connection 0HMH6QMTDL8OD established using the following protocol: Tls13
[xUnit.net 00:00:05.92]         | [0.031s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMH6QMTDL8OD" sending SETTINGS frame for stream ID 0 with length 24 and flags NONE.
[xUnit.net 00:00:05.92]         | [0.031s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMH6QMTDL8OD" sending WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0.
[xUnit.net 00:00:05.92]         | [0.031s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMH6QMTDL8OD" received SETTINGS frame for stream ID 0 with length 12 and flags NONE.
[xUnit.net 00:00:05.92]         | [0.031s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMH6QMTDL8OD" sending SETTINGS frame for stream ID 0 with length 0 and flags ACK.
[xUnit.net 00:00:05.92]         | [0.031s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMH6QMTDL8OD" received WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0.
[xUnit.net 00:00:05.92]         | [0.031s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMH6QMTDL8OD" received HEADERS frame for stream ID 1 with length 20 and flags END_STREAM, END_HEADERS.
[xUnit.net 00:00:05.92]         | [0.031s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMH6QMTDL8OD" received SETTINGS frame for stream ID 0 with length 0 and flags ACK.
[xUnit.net 00:00:05.92]         | [0.031s] Microsoft.AspNetCore.Hosting.Diagnostics Information: Request starting HTTP/2 GET https://127.0.0.1:49526/ - -
[xUnit.net 00:00:05.92]         | [0.032s] Microsoft.AspNetCore.Hosting.Diagnostics Information: Request finished HTTP/2 GET https://127.0.0.1:49526/ - - - 200 - - 0.1817ms
[xUnit.net 00:00:05.92]         | [0.032s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMH6QMTDL8OD" sending HEADERS frame for stream ID 1 with length 41 and flags END_HEADERS.
[xUnit.net 00:00:05.92]         | [0.032s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMH6QMTDL8OD" sending DATA frame for stream ID 1 with length 11 and flags END_STREAM.
[xUnit.net 00:00:05.92]         | [0.034s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMH6QMTDL8OD" received PING frame for stream ID 0 with length 8 and flags NONE.
[xUnit.net 00:00:05.92]         | [0.034s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMH6QMTDL8OD" sending PING frame for stream ID 0 with length 8 and flags ACK.
[xUnit.net 00:00:05.92]         | [0.035s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMH6QMTDL8OD" received HEADERS frame for stream ID 3 with length 28 and flags END_HEADERS.
[xUnit.net 00:00:05.92]         | [0.035s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMH6QMTDL8OD" received DATA frame for stream ID 3 with length 16384 and flags NONE.
[xUnit.net 00:00:05.92]         | [0.036s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMH6QMTDL8OD" received DATA frame for stream ID 3 with length 2048 and flags NONE.
[xUnit.net 00:00:05.92]         | [0.036s] Microsoft.AspNetCore.Hosting.Diagnostics Information: Request starting HTTP/2 POST https://127.0.0.1:49526/ - 18432
[xUnit.net 00:00:05.92]         | [0.036s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMH6QMTDL8OD" received DATA frame for stream ID 3 with length 0 and flags END_STREAM.
[xUnit.net 00:00:05.92]         | [0.036s] Microsoft.AspNetCore.Hosting.Diagnostics Information: Request finished HTTP/2 POST https://127.0.0.1:49526/ - 18432 - 200 - - 0.1001ms
[xUnit.net 00:00:05.92]         | [0.036s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMH6QMTDL8OD" sending HEADERS frame for stream ID 3 with length 3 and flags END_HEADERS.
[xUnit.net 00:00:05.92]         | [0.036s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HMH6QMTDL8OD", Request id "0HMH6QMTDL8OD:00000003": started reading request body.
[xUnit.net 00:00:05.92]         | [0.036s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HMH6QMTDL8OD", Request id "0HMH6QMTDL8OD:00000003": done reading request body.
[xUnit.net 00:00:05.92]         | [0.036s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMH6QMTDL8OD" sending DATA frame for stream ID 3 with length 11 and flags END_STREAM.
[xUnit.net 00:00:05.92]         | [0.066s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Some connections failed to close gracefully during server shutdown.
[xUnit.net 00:00:05.92]         | [0.066s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HMH6QMTDL8OD" sending FIN because: "The connection was aborted because the server is shutting down and request processing didn't complete within the time specified by HostOptions.ShutdownTimeout."
[xUnit.net 00:00:05.92]         | [0.067s] Microsoft.AspNetCore.Server.Kestrel.Http2 Debug: Connection id "0HMH6QMTDL8OD" is closing.
[xUnit.net 00:00:05.92]         | [0.067s] Microsoft.AspNetCore.Server.Kestrel.Http2 Debug: Connection id "0HMH6QMTDL8OD" is closed. The last processed stream ID was 3.
[xUnit.net 00:00:05.92]         | [0.067s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMH6QMTDL8OD" sending GOAWAY frame for stream ID 0 with length 8 and flags 0x0.
[xUnit.net 00:00:05.92]         | [0.067s] Microsoft.AspNetCore.Server.Kestrel.Http2 Debug: The connection queue processing loop for 0HMH6QMTDL8OD completed.
[xUnit.net 00:00:05.92]         | [0.067s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMH6QMTDL8OD" stopped.
[xUnit.net 00:00:05.92]         | [0.099s] Interop.FunctionalTests.HttpClientHttp2InteropTests Error: Test threw an exception.
[xUnit.net 00:00:05.92]         | System.Net.Http.HttpRequestException: An error occurred while sending the request.
[xUnit.net 00:00:05.92]         |  ---> System.IO.IOException: The request was aborted.
[xUnit.net 00:00:05.92]         |  ---> System.IO.IOException: The decryption operation failed, see inner exception.
[xUnit.net 00:00:05.92]         |  ---> System.ComponentModel.Win32Exception (0x80090330): The specified data could not be decrypted.
[xUnit.net 00:00:05.92]         |    --- End of inner exception stack trace ---
[xUnit.net 00:00:05.92]         |    at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
[xUnit.net 00:00:05.92]         |    at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
[xUnit.net 00:00:05.92]         |    --- End of inner exception stack trace ---
[xUnit.net 00:00:05.92]         |    at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
[xUnit.net 00:00:05.92]         |    at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
[xUnit.net 00:00:05.92]         |    at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders()
[xUnit.net 00:00:05.92]         |    at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationToken cancellationToken)
[xUnit.net 00:00:05.92]         |    at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[xUnit.net 00:00:05.92]         |    --- End of inner exception stack trace ---
[xUnit.net 00:00:05.92]         |    at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[xUnit.net 00:00:05.92]         |    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
[xUnit.net 00:00:05.92]         |    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[xUnit.net 00:00:05.92]         |    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
[xUnit.net 00:00:05.92]         |    at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 106
[xUnit.net 00:00:05.92]         |    at Interop.FunctionalTests.HttpClientHttp2InteropTests.Settings_MaxFrameSize_Larger_Server(String scheme) in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/HttpClientHttp2InteropTests.cs:line 1332
[xUnit.net 00:00:05.92]         |    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
[xUnit.net 00:00:05.92]         | --- End of stack trace from previous location ---
[xUnit.net 00:00:05.92]         |    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
[xUnit.net 00:00:05.92]         |    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 96
[xUnit.net 00:00:05.92]         | [0.103s] TestLifetime Information: Finished test Settings_MaxFrameSize_Larger_Server-https in 0.1018345s
```

</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1736533&view=ms.vss-test-web.build-test-results-tab&runId=46995274&resultId=108594&paneView=debug

**Comment by sebastienros** [comment]
Not sure the process is to open this issue, I might be wrong
