### ISSUE TITLE
.Net 6 In Web API project adding MVC  view was not found

### ISSUE THREAD

**Issue by ArjunVachhani** [dotnet/aspnetcore#41364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have one Web API project, After some time I need some MVC controller and Views, I added controller and views and modified startup to use `AddControllersWithViews` instead of `AddControllers`.  I am gettting Views was not found.

I also noticed that <proj>.views.dll is not generated on build/publish.
If I use runtime view compilation then I am not getting that error.

### Expected Behavior

It should load appropriate view and render it.

### Steps To Reproduce

Steps to reproduce,
1) Create a new ASP.Net 6 Web Api project
2) Add MVC controller and Views,
3) Navigate to controller action path.

### Exceptions (if any)

System.InvalidOperationException: The view 'Index' was not found. The following locations were searched:
/Views/Foobar/Index.cshtml
/Views/Shared/Index.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

### .NET Version

6

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Do you have the `builder.Services.AddRazorPages();` in the Program.cs file?

**Comment by mkArtakMSFT** [comment]
Below is the unique code in MVC WebApp project (highlighted in yellow):

<img width="565" alt="image" src="https://user-images.githubusercontent.com/34246760/165181784-7e601b48-8563-40ef-9a4b-539749fee049.png">
```

**Comment by ArjunVachhani** [comment]
@mkArtakMSFT Thanks for your quick reply.
> Do you have the builder.Services.AddRazorPages(); in the Program.cs file?

No, I do not have `builder.Services.AddRazorPages();` in Program.cs. I have tried adding that as well. still getting same issue. If I add `AddRazorPages` it searches for view in one more location, but still getting same error.

```
System.InvalidOperationException: The view 'Index' was not found. The following locations were searched:
/Views/Foobar/Index.cshtml
/Views/Shared/Index.cshtml
/Pages/Shared/Index.cshtml
```

Regarding unique code in MVC, I see that Web API project has few difference compared to MVC, I have also tried replacing `builder.Services.AddControllers();` with `builder.Services.AddControllersWithViews();` and `app.MapControllers();` with `app.MapControllerRoute(/*default args*/);` and added `app.UseStaticFiles();` but that did not help. 

I have checked properties of view file. in both project `Build Action` is set to `Content` and `Copy to Output Directory` is set to `Do not copy`

I have also compared *.csproj of both projects, the only difference it has is `Swashbuckle.AspNetCore` nuget package.

```
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
  </ItemGroup>
```

launchSettings.json is also similar. 

I am wondering how the dotnet knows when to pre compile views and when to not.

**Comment by ArjunVachhani** [comment]
@mkArtakMSFT I noticed that it is not specific to Web API project, same happen with ASP.NET Core Empty  project template.

FYI I am using 

Microsoft Visual Studio Professional 2022
Version 17.0.5
VisualStudio.17.Release.LTSC.17.0/17.0.5+32112.339
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Professional

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ASP.NET and Web Tools 2019   17.0.795.42246
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   17.0.795.42246
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   17.0.795.42246
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.0.795.42246
Azure Functions and Web Jobs Tools

C# Tools   4.0.1-1.21568.1+6ab6601178d9fba8c680b56934cd1742e0816bff
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

CreateUnitTestBoilerplateCommand Extension   1.0
CreateUnitTestBoilerplateCommand Visual Studio Extension Detailed Info

Fine Code Coverage   fcc-f339fe606-9d51-4fca-895c-d50375137b62
Visualize unit test code coverage easily for free in Visual Studio Community Edition (and other editions too)

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.134+45632ee938.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

NuGet Package Manager   6.0.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   17.0.0.2156603+e9cd763349a080127b6519ffbec0123949a4c385
Provides languages services for ASP.NET Core Razor.

SonarLint for Visual Studio   6.1.0.45943
SonarLint is an extension to your favorite IDE that provides on-the-fly feedback to developers on new bugs and quality issues injected into their code.

SQL Server Data Tools   17.0.62110.20190
Microsoft SQL Server Data Tools

TypeScript Tools   17.0.1001.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.0.1-1.21568.1+6ab6601178d9fba8c680b56934cd1742e0816bff
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.0.0-beta.21522.2+6d626ff0752a77d339f609b4d361787dc9ca93a5
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

**Comment by ArjunVachhani** [comment]
@mkArtakMSFT Even new ASP.NET Core (MVC) project template is giving same error, I checked on other system but there I am not getting similar error. I have tried updating VS to latest version, I am now on latest version of VS(Microsoft Visual Studio Professional 2022 (64-bit) - LTSC 17.0, Version 17.0.9)

**Comment by ArjunVachhani** [comment]
@mkArtakMSFT with Visual Studio Code it works. Could you guide me what could be wrong.

**Comment by mkArtakMSFT** [comment]
Thanks for all the details, @ArjunVachhani.
It looks like you're facing some weird misconfiguration on that machine. 

What's the output of `dotnet --info` when run from the project folder? Is it the same as the output you get when run the same command in the Terminal window of VS ? Should be the same, but worth confirming.
Also, share the `dotnet --info` output.

**Comment by ArjunVachhani** [comment]
@mkArtakMSFT I compared output of running dotnet --info it is same in VS terminal and command prompt, below is what I get from running the command.

```
PS {{PROJECT_PATH}}> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.202\

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  3.1.416 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.404 [C:\Program Files\dotnet\sdk]
  6.0.104 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by mkArtak** [comment]
Thanks for additional details. It looks like when you run the project from VS the Razor Source Generator isn't being run, thus resulting in views.dll assembly not being generated.

Can you please double-check that creating a new Web App (dotnet new webapp) project builds and runs successfully from VS?

**Comment by ArjunVachhani** [comment]
@mkArtakMSFT I have tried creating new project using dotnet cli, I am able to run successfully. even existing project works fine with dotnet cli. It seems Visual studio has some issue.

**Comment by stantoxt** [comment]
I can not change default route swagger ,even if i have set app.MapDefaultControllerRoute().

**Comment by ArjunVachhani** [comment]
@javiercn one warning on build standout to me

> CSC : warning CS8032: An instance of analyzer Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator cannot be created from C:\Program Files\dotnet\sdk\6.0.202\Sdks\Microsoft.NET.Sdk.Razor\source-generators\Microsoft.NET.Sdk.Razor.SourceGenerators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..

**Comment by javiercn** [comment]
@ArjunVachhani thanks for the details.

This is very likely a dupe of an existing razor compiler issue we recently addressed.

@jaredpar do you have the details about this one?
