### ISSUE TITLE
Invalid form key returns internal server error

### ISSUE THREAD

**Issue by Sanjidhalim** [dotnet/aspnetcore#41407]
When sending a request with content type `application/x-www-form-urlencoded` and a malformed key in the request body (e.g. `[spc=123`) ASP NET Core throws an Internal Server Error with the following stack trace:

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.ArgumentException: The key '[spc' is invalid JQuery syntax because it is missing a closing bracket. (Parameter 'key')
         at Microsoft.AspNetCore.Mvc.ModelBinding.JQueryKeyValuePairNormalizer.NormalizeJQueryToMvc(StringBuilder builder, String key)
         at Microsoft.AspNetCore.Mvc.ModelBinding.JQueryKeyValuePairNormalizer.GetValues(IEnumerable`1 originalValues, Int32 valueCount)
         at Microsoft.AspNetCore.Mvc.ModelBinding.JQueryFormValueProviderFactory.AddValueProviderAsync(ValueProviderFactoryContext context)
         at Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider.CreateAsync(ActionContext actionContext, IList`1 factories)
         at Microsoft.AspNetCore.Mvc.ModelBinding.CompositeValueProvider.TryCreateAsync(ActionContext actionContext, IList`1 factories)
         at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Bad user input should return a Bad Request response instead.

## Repro steps

* Create a new ASP.NET Core Web API project (.NET 6) using the project template
* Modify the `WeatherForecastController` to Get method to:
```
        [HttpPost(Name = "GetWeatherForecast")]
        public IEnumerable<WeatherForecast> Get([FromForm] string spc)
        {
            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = Random.Shared.Next(-20, 55),
                Summary = Summaries[Random.Shared.Next(Summaries.Length)]
            })
            .ToArray();
        }
``` 
* Send the following HTTP request:
```
POST https://localhost:7040/WeatherForecast HTTP/1.1
User-Agent: Fiddler
Content-Type: application/x-www-form-urlencoded
Host: localhost:7040
Content-Length: 8

[spc=123
```

**Comment by captainsafia** [comment]
Triage: Duping this to https://github.com/dotnet/aspnetcore/issues/37857.

We're considering not registering the JQuery form validator by default in MVC applications. In the meantime, you can deregister it yourself by modifying the service collection when initializing MVC in your application.

**Comment by captainsafia** [comment]
Triage: cc: @brunolins16 for his interest in the area

**Comment by brunolins16** [comment]
While we still working on the consideration described here #37857. you could remove the JQueryFormValueProviderFactory  in your application if the JQuery support is not needed.

``` c#
builder.Services.Configure<MvcOptions>(options => { 
    options.ValueProviderFactories.RemoveType<JQueryFormValueProviderFactory>();
});
```

That will produce the expected result:

``` json
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "00-577f8b3ea47d08e2cd4f44f33043be22-9be5d970557866de-00",
    "errors": {
        "spc": [
            "The spc field is required."
        ]
    }
}
```
