### ISSUE TITLE
Blazor Server Windows Authentication : Trust Relationship between this workstation and the primary domain failed.

### ISSUE THREAD

**Issue by Programmer04515** [dotnet/aspnetcore#41512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

.NET Blazor Server Windows Authentication error when trying to using Policy with the AuthorizedView component.

For example,
```
<AuthorizeView>
    Hello, @context.User.Identity?.Name.Split('\\')[1]!
</AuthorizeView>
```

***(above) works just fine until you include the Policy

```
<AuthorizeView Policy="IT_ADMIN_ONLY"> 
    Hello, @context.User.Identity?.Name.Split('\\')[1]!
</AuthorizeView>
```

***The above policy declaration causes the following error: 
----The trust relationship between this workstation and the primary domain failed.
However, when I deploy this to the development server it works as expected, 
This error only occurs when I am running the Blazor Server app within Visual Studios 2022 on my domain connected computer through a VPN. 

I use the same setup with .NET Core 2.1 MVC apps and do not have this issue when defining policy based authorization through the domain connected computer through a VPN.

### Expected Behavior

It is expected the 
```
<AuthorizeView>
    <p> Logged-in user is in HR Role (using Policy)</p>
</AuthorizeView>
```

AND THE 

```
<AuthorizeView Policy="IT_ADMIN_ONLY"> 
    Hello, @context.User.Identity?.Name.Split('\\')[1]!
</AuthorizeView>
```

both work when you are connected to a domain via VPN connection.

### Steps To Reproduce

Connect to a domain network via VPN.

Create a Blazor Server .NET 6.0 app with Windows Authentication.

In the Program.cs file add the following:

```
builder.Services.AddAuthorization(options =>
{
    // By default, all incoming requests will be authorized according to the default policy.
    options.FallbackPolicy = options.DefaultPolicy;
    options.AddPolicy("NON_IT_TEST", policy => policy.RequireRole("MYDOMAIN\\NON_IT_USERS"));
});

```
Then on the home page include the following:

```
<AuthorizeView Policy="NON_IT_TEST">
    <p> Logged-in user is in NON_IT_USER Role (using Policy)</p>
</AuthorizeView> 
```

This will throw the error as is, however by removing the Policy declaration it will work as expected.

Another fix is to not be connected to the domain via a VPN or deploy to a server that is within the domain and not connected through a VPN.

### Exceptions (if any)

blazor.server.js:1 
        
       [2022-05-04T16:53:14.405Z] Error: System.ComponentModel.Win32Exception (1789): The trust relationship between this workstation and the primary domain failed.
   at System.Security.Principal.NTAccount.TranslateToSids(IdentityReferenceCollection sourceAccounts, Boolean& someFailed)
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean& someFailed)
   at System.Security.Principal.NTAccount.Translate(IdentityReferenceCollection sourceAccounts, Type targetType, Boolean forceSuccess)
   at System.Security.Principal.WindowsPrincipal.IsInRole(String role)
   at Microsoft.AspNetCore.Authorization.Infrastructure.RolesAuthorizationRequirement.<>c__DisplayClass4_0.<HandleRequirementAsync>b__0(String r)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.AspNetCore.Authorization.Infrastructure.RolesAuthorizationRequirement.HandleRequirementAsync(AuthorizationHandlerContext context, RolesAuthorizationRequirement requirement)
   at Microsoft.AspNetCore.Authorization.AuthorizationHandler`1.HandleAsync(AuthorizationHandlerContext context)
   at Microsoft.AspNetCore.Authorization.Infrastructure.PassThroughAuthorizationHandler.HandleAsync(AuthorizationHandlerContext context)
   at Microsoft.AspNetCore.Authorization.DefaultAuthorizationService.AuthorizeAsync(ClaimsPrincipal user, Object resource, IEnumerable`1 requirements)
   at Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.IsAuthorizedAsync(ClaimsPrincipal user)
   at Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.OnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

### .NET Version

6.0.200

### Anything else?

Visual Studio 2022 Professional
Blazor Server .NET 6.0
Windows Authentication Policy

**Comment by javiercn** [comment]
@Programmer04515 thanks for contacting us.

If you do the same thing on an MVC page, do you run into the same error?

**Comment by Programmer04515** [comment]
@javiercn No the error is not present when using a .NET 5.0 ASP.NET Core MVC project.

**Comment by javiercn** [comment]
@adityamandaleeka I don't see how this can be something specific to Blazor. We don't deal with the underlying websocket nor the underlying windows authentication. Could you folks take a first crack at figuring out what might be going on here?
