### ISSUE TITLE
Problem with new solutions in NET 6+ templates

### ISSUE THREAD

**Issue by Timka654** [dotnet/aspnetcore#41569]
After asp.net framework dotnet community nice works done for create asp.net core, and long time asp.net and other components have nice functional for easy creating application small or large - any, but now(NET 6.0+) i'm see how asp.net core evolutions to asp.net framework back - you must have 3s doctor steps for normal configure and release "hello world" application and you must have days for search solution if you have problems

Problem how i'm see
1 - you remove Startup class - okay, 20% questions on stackoverflow(and another resources) haved soluted - not actual and not worked(for middle level+ this not problem, but for new - its critical if errors exists)
2 - you remove Program(namespace, class, all class structure) - welcome to new Powershell(may-be create new launguage PS#? for why this in C#?)
3 - HTTPS(SSL) - yout cannot change configuration for exists application, for remove this in you application - you must 3 days read stackoverflow and other resources for find solution(98% not have effects or not for you situation)

My latest situation
- have application
-- contains one test page, no auth, no external services
-- "UseHttpsRedirection - remove" (after google search help)
-- "UseUrls("http://0.0.0.0:80")" (after google search help)
- have docker on linux
- have nginx (with ssl and domain)
- pull changes from repository
- docker-compose up and..... finish

To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at webrtc_dotnetcore.Program.Main(String[] args) in /src/webrtc-dotnetcore/Program.cs:line 17

For why and for what? On search by tags "asp.net core" "disable ssl" "disable https" "remove ssh" "remove https" "To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'. linux" "docker" and other..... i'm returned solutions
- UseHttpsRedirection = remove
- UseUrls
- change launchSettings.json
- right click on project
- how to enable ssl
- and other

But after 4h search i'm dont have answer for my question and this not first case
I'm need release the test solution, for other developer see it, but i'm cannot release application have written in 20 minutes because you think about - https required need in asp.net in 100% cases. And you not provide in documentation  - how disable this. How about scenarios not need this? nginx ssl host, cloudflare ssl  and another

You create new mechanisms for easy integrate new developers or developers from another launguages in dotnet - nice, but this changes destroy exist solution database, please stop integrate new solutions in default template... Add custom templates, or append configuration window for setup or templates configuration code files(Add/New Items menu).. default template must create default configured web application - contains minimal code for working, splited in required sections for navigate(i'm think .NET 5.0 and less - have optimal code)

After changes .NET 6, my command think choosing another frameworks, launguages, instruments for continue development. Writed solutions setted default as NET 5.0 for all time. And for create next solutions we dont thin .NET 6+ and new default templates

**Comment by davidfowl** [comment]
1. and 2. have been consistent feedback since the 6.0 changes but I don't know how 3 is related or maybe you were saying it was always hard?

**Comment by Timka654** [comment]
> 1. and 2. have been consistent feedback since the 6.0 changes but I don't know how 3 is related or maybe you were saying it was always hard?

Sorry, 3 - default docker-compose.override.yml file have binding 443 and i'm returned ssl error message on start in docker. i'm do not had see this on start, this only my problem

**Comment by davidfowl** [comment]
For 2. We're adding a "give me back my program main" flag to the new templates 😄
