### ISSUE TITLE
Invoking a Minimal Web API in .NET 6 via dotnet throws an exception but runs fine as .exe

### ISSUE THREAD

**Issue by NimaAra** [dotnet/aspnetcore#41578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A minimal web API in .NET 6 throws the following exception when invoked as `dotnet MyApp.dll`

```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'dotnet, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'dotnet, Culture=neutral, PublicKeyToken=null'
```

However the same application runs without any errors when run directly from _Visual Studio_ or invoked as _MyApp.exe_

### Expected Behavior

The application should start successfully regardless of how it is started.

### Steps To Reproduce

1. Clone the following repo: https://github.com/NimaAra/WhereIsTheTruck
2. Publish the web API project via:
`dotnet publish WhereIsTheTruck.Web.App\WhereIsTheTruck.Web.App.csproj -c Release -o dist`
3. Set the required env variables:
    ```
    set WhereIsTheTruck:TruckApiEndpoint=http://data.sfgov.org/resource/rqzj-sfat.json
    set WhereIsTheTruck:TruckApiRefreshInterval=1:0:0
    ```
4. Run the application:
`dotnet .\dist\WhereIsTheTruck.Web.App.dll`

### Exceptions (if any)

```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'dotnet, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'dotnet, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.GetApplicationPartAssemblies(String entryAssemblyName)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateDefaultParts(String entryAssemblyName)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.GetApplicationPartManager(IServiceCollection services, IWebHostEnvironment environment)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddControllersCore(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddControllers(IServiceCollection services)
   at Program.<<Main>$>g__AddServices|0_3(AppConfig config, <>c__DisplayClass0_0& ) in D:\My-Code\GitHub\WhereIsTheTruck\WhereIsTheTruck.Web.App\Program.cs:line 84
   at Program.<<Main>$>g__BuildWebApp|0_0(String[] args) in D:\My-Code\GitHub\WhereIsTheTruck\WhereIsTheTruck.Web.App\Program.cs:line 43
   at Program.<Main>$(String[] args) in D:\My-Code\GitHub\WhereIsTheTruck\WhereIsTheTruck.Web.App\Program.cs:line 10
```

### .NET Version

6.0.202

**Comment by BrennanConroy** [comment]
The issue is that you're setting the application name to the process name (which is dotnet if you run with `dotnet ...`)
https://github.com/NimaAra/WhereIsTheTruck/blob/1e2eae059e59d9618578496f3d529c8e34ddd853/WhereIsTheTruck.Web.App/Program.cs#L36

Triage: We probably want to have different behavior than relying on `environment.ApplicationName` when loading the entry assembly.

**Comment by hitman9** [comment]
Me also facing similar issues for one of the .net 6 api project, any solution fix for this.

**Comment by NimaAra** [comment]
In my case, [THIS](https://github.com/NimaAra/WhereIsTheTruck/issues/1) fixed it.

**Comment by hitman9** [comment]
@NimaAra, The link is not accessible, how you fixed it.

**Comment by hitman9** [comment]
I haven't added that, i suspecting the application name to process name setting problem might caused it.

**Comment by NimaAra** [comment]
Hey @VladBullet,

I had to unset the `ApplicationName` and that fixed it for me: 
![image](https://github.com/dotnet/aspnetcore/assets/16215744/61db4c4e-b7a5-4033-b0b1-237810149bd1)

**Comment by VladBullet** [comment]
I wasn't expecting anybody to answer on this issue.😅 
Thanks for the quick reply.😍 
I'll try your solution.

Happy coding!

**Comment by NimaAra** [comment]
No problem, good luck and pass it on :-)

**Comment by da1ight** [comment]
Thank you! you save my time)
