### ISSUE TITLE
Blazor Server Windows Authentication + SignalR Hub on Windows Server 2019/ IIS 10.0

### ISSUE THREAD

**Issue by blindmeis** [dotnet/aspnetcore#41661]
Hi, i created a Blazor Server App (VS2022 .Net6.0) with Windows Authentication and added a simple Hub. It works locally and on a Windows Server 2012 R2/ IIS 8.5 but not on Windows Server 2019/ IIS 10.

Here is my Hub and changes to the classes:

TestHub.cs

```
using Microsoft.AspNetCore.SignalR;

namespace BlazorServerTestHub.Hubs
{
    public class TestHub :Hub
    {
        public async Task SendSomeMessage(int currentCount, string someMessage)
        {
            await Clients.Others.SendAsync("OnSendMyMessage", currentCount, someMessage);
        }
    }
}
```

Programm.cs

```
using BlazorServerTestHub.Data;
using BlazorServerTestHub.Hubs;
using Microsoft.AspNetCore.Authentication.Negotiate;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddAuthentication(NegotiateDefaults.AuthenticationScheme)
   .AddNegotiate();

builder.Services.AddAuthorization(options =>
{
    // By default, all incoming requests will be authorized according to the default policy.
    options.FallbackPolicy = options.DefaultPolicy;
});

builder.Services.AddRazorPages();
builder.Services.AddServerSideBlazor(options =>
{
    options.DetailedErrors = true;
    options.DisconnectedCircuitMaxRetained = 100;
    options.DisconnectedCircuitRetentionPeriod = TimeSpan.FromMinutes(3);
    options.JSInteropDefaultCallTimeout = TimeSpan.FromMinutes(1);
    options.MaxBufferedUnacknowledgedRenderBatches = 10;
}).AddHubOptions(options =>
{
    //https://docs.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-6.0&tabs=dotnet#configure-server-options-1
    options.EnableDetailedErrors = true;
    options.ClientTimeoutInterval = TimeSpan.FromSeconds(60);
    options.HandshakeTimeout = TimeSpan.FromSeconds(15);
    options.KeepAliveInterval = TimeSpan.FromSeconds(15);
    options.MaximumParallelInvocationsPerClient = 1;
    options.MaximumReceiveMessageSize = 32 * 1024;
    options.StreamBufferCapacity = 10;
});
builder.Services.AddSingleton<WeatherForecastService>();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseRouting();
app.UseWebSockets();
app.UseAuthentication();
app.UseAuthorization();


app.MapBlazorHub();
app.MapHub<TestHub>("/mytesthub");
app.MapFallbackToPage("/_Host");

app.Run();
```

Counter.razor

```
@page "/counter"
@using Microsoft.AspNetCore.SignalR.Client

@inject NavigationManager navigationManager;

@implements IAsyncDisposable;

<PageTitle>Counter</PageTitle>

<h1>Counter</h1>

<p role="status">Current count: @currentCount</p>
<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

<p>@MyMessage</p>


@code {
    private int currentCount = 0;
    private HubConnection hubConnection = null!;
    public string MyMessage { get; set; } = null!;

    private async void IncrementCount()
    {
        currentCount++;

        await hubConnection.SendAsync("SendSomeMessage", currentCount, DateTime.Now.ToLongTimeString());
    }

    protected override async Task OnInitializedAsync()
    {
        var hubUrl = navigationManager.BaseUri + "mytesthub";


        hubConnection = new HubConnectionBuilder()
          .WithUrl(hubUrl, options =>
          {
              options.UseDefaultCredentials = true;
              options.SkipNegotiation = true;
              options.Transports = Microsoft.AspNetCore.Http.Connections.HttpTransportType.WebSockets;
          })
          .WithAutomaticReconnect()
          .Build();

        hubConnection.On<int, string>("OnSendMyMessage", async (counter, msg) =>
        {
            MyMessage = $"Counter: {counter}! {msg}";
            await InvokeAsync(StateHasChanged);
        });

        await hubConnection.StartAsync();


    }

    public async ValueTask DisposeAsync()
    {
        if (hubConnection is not null)
        {
            await hubConnection.DisposeAsync().ConfigureAwait(false);
        }
        hubConnection = null!;
    }
}
```

as far as i open the counter page on hosted on Windows 2019 i got:

The server returned status code '401' when status code '101' was expected

Any suggestions?

**Comment by javiercn** [comment]
@blindmeis thanks for contacting us.

Blazor doesn't do handle anything with regards to authentication. I would check that your authentication system is correctly configured in the deployment server (maybe add an endpoint to test the user identity) and when the SignalR connection is initially established.

I would defer to the folks on the security triage to help you further as they know best.

**Comment by blindmeis** [comment]
> 



> @blindmeis thanks for contacting us.
> 
> Blazor doesn't do handle anything with regards to authentication. I would check that your authentication system is correctly configured in the deployment server (maybe add an endpoint to test the user identity) and when the SignalR connection is initially established.
> 
> I would defer to the folks on the security triage to help you further as they know better and might offer you more pointed guidance.

Hi, it is my first Web Project... but as far as i understand Blazor Server works with SignalR Hub internal. And the normal Blazor Server pages stuff works on all Servers. I created a simple console app too and magically its working.

```
using Microsoft.AspNetCore.SignalR.Client;

Console.WriteLine("Hello, World!");

var hubUrl = "https://testwebapp.de/blazorservertesthub/mytesthub";


var hubConnection = new HubConnectionBuilder()
  .WithUrl(hubUrl, options =>
  {
      options.UseDefaultCredentials = true;
      options.SkipNegotiation = true;
      options.Transports = Microsoft.AspNetCore.Http.Connections.HttpTransportType.WebSockets;
  })
  .WithAutomaticReconnect()
  .Build();

hubConnection.On<int, string>("OnSendMyMessage", (counter, msg) =>
{
    Console.WriteLine($"From Blazor Server TestHub: {counter}! {msg}");
});

await hubConnection.StartAsync();

var input = Console.ReadLine();

if(input=="Start")
{
    await hubConnection.SendAsync("SendSomeMessage", 47, "Hello From Console");
}

Console.ReadKey();
```

this is what i did not understand. why is the console app working and within the blazor server app its not? the only difference is of course the url.

**Comment by BrennanConroy** [comment]
By default your HTTP connections will use HTTP/2 on windows server 2019. Windows Auth does not work with HTTP/2 so this is likely why your app isn't working as expected. The reason your console app is working is because you explicitly specified WebSockets and skip negotiate, and since WebSockets doesn't work with HTTP/2 (yet) you're using HTTP/1.1 which works with Windows Auth.

You can change the underlying Blazor connection to use WebSockets and skip negotiate by configuring the SignalR options with https://docs.microsoft.com/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-6.0#configure-signalr-client-logging-blazor-server which would force HTTP/1.1 
```javascript
Blazor.start({
    configureSignalR: function (builder) {
        builder.configureLogging("information");
        builder.withUrl("_blazor", { transport: 1, skipNegotiation: true });
    }
});
```

**Comment by blindmeis** [comment]
Hi, i tried your suggestion. But no success.

```
@using Microsoft.AspNetCore.Components.Web
@namespace BlazorServerTestHub.Pages
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <base href="~/" />
    <link rel="stylesheet" href="css/bootstrap/bootstrap.min.css" />
    <link href="css/site.css" rel="stylesheet" />
    <link href="BlazorServerTestHub.styles.css" rel="stylesheet" />
    <component type="typeof(HeadOutlet)" render-mode="ServerPrerendered" />
</head>
<body>
    @RenderBody()

    <div id="blazor-error-ui">
        <environment include="Staging,Production">
            An error has occurred. This application may no longer respond until reloaded.
        </environment>
        <environment include="Development">
            An unhandled exception has occurred. See browser dev tools for details.
        </environment>
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>

    <script src="_framework/blazor.server.js" autostart="false"></script>
    <script>
        Blazor.start({
            configureSignalR: function (builder) {
                builder.configureLogging("debug");
                builder.withUrl("_blazor", { transport: 1, skipNegotiation: true });
            }
        });
    </script>
</body>
</html>
```

I set up a second Windows 2019 Server IIS 10. 
If i change my internal hubpath to connect to the first windows 2019 server it works....

`var hubUrl = navigationManager.BaseUri + "mytesthub";`

changed to 

`var hubUrl = "https://testwebapp.de/blazorservertesthub/mytesthub";
`

so to summarize all

**working on Windows 2019**:

- blazor server app pages with Websockets and Windows Authentication
- my custom hub: app.MapHub<TestHub>("/mytesthub");
- my HubConnectionBuilder connection as far as i connect to the other Windows 2019 Server

**NOT working on Windows 2019**
- my HubConnectionBuilder connection as far as i connect to myself: var hubUrl = navigationManager.BaseUri + "mytesthub";


i dont get it... its my first webproject so maybe i miss something simple?

```
[2022-05-16T07:48:49.566Z] Information: Normalizing '_blazor' to 'https://testwebapp.de/blazorservertesthub/_blazor'.
blazor.server.js:1 [2022-05-16T07:48:49.567Z] Debug: Starting HubConnection.
blazor.server.js:1 [2022-05-16T07:48:49.567Z] Debug: Starting connection with transfer format 'Binary'.
blazor.server.js:1 [2022-05-16T07:48:49.805Z] Information: WebSocket connected to wss://testwebapp.de/blazorservertesthub/_blazor.
blazor.server.js:1 [2022-05-16T07:48:49.805Z] Debug: The HttpConnection connected successfully.
blazor.server.js:1 [2022-05-16T07:48:49.805Z] Debug: Sending handshake request.
blazor.server.js:1 [2022-05-16T07:48:49.806Z] Information: Using HubProtocol 'blazorpack'.
blazor.server.js:1 [2022-05-16T07:48:49.853Z] Debug: Server handshake complete.
blazor.server.js:1 [2022-05-16T07:48:49.853Z] Debug: HubConnection connected successfully.
blazor.server.js:1 
        
       [2022-05-16T07:50:38.034Z] Error: System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '401' when status code '101' was expected.
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.DefaultWebSocketFactory(WebSocketConnectionContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartAsync(Uri url, TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartTransport(Uri connectUrl, HttpTransportType transportType, TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat, CancellationToken cancellationToken)
   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
   at BlazorServerTestHub.Pages.Counter.OnInitializedAsync() in C:\Users\bereuter\source\repos\BlazorServerTestHub\BlazorServerTestHub\Pages\Counter.razor:line 55
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
log @ blazor.server.js:1
blazor.server.js:1 [2022-05-16T07:50:38.034Z] Debug: Stopping HubConnection.
blazor.server.js:1 [2022-05-16T07:50:38.036Z] Debug: HttpConnection.stopConnection(undefined) called while in state Disconnecting.
blazor.server.js:1 [2022-05-16T07:50:38.036Z] Information: Connection disconnected.
blazor.server.js:1 [2022-05-16T07:50:38.036Z] Debug: HubConnection.connectionClosed(undefined) called while in state Disconnecting.
```

**Comment by blindmeis** [comment]
UPDATE 2 - BUG in Windows 2019??

if i set the following registry KEY on the Windows 2019 Server: **Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\DisableLoopbackCheck = 1**

then my app is working like expected. But is this really the way to go? It would be nice to get an answer.

**Comment by Tratcher** [comment]
Ah, that makes more sense. Making two hops requires impersonation and delegation. Delegation requires Kerberos. On localhost windows auth falls back to NTLM instead of Kerberos and thus no delegation.

I wasn't aware of that reg key override, but I suspect it weakens the security model.

Ultimately windows auth is not well suited for these scenarios, you'd be better off using something like JwtBearer.

**Comment by blindmeis** [comment]
> Ultimately windows auth is not well suited for these scenarios, you'd be better off using something like JwtBearer.

Windows auth is not recommend for an intranet application? i not really aggree with this. But nevertheless i found out that there is a recommended way to handle this loopbackcheck. You can set the following Key in the registry: 

**Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0\BackConnectionHostNames**

to: testwebapp.de

i take this for now.
