### ISSUE TITLE
Signlar 1006 error on win 2016 server when message size incresed

### ISSUE THREAD

**Issue by pranayrana** [dotnet/aspnetcore#41675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Singlar implemented with .net core + angular working fine on Win 10 machine with big message size. 
But its not working on win 2016 server when message size get increased , it gives 1006 error.

tried below , but none  of below is working 

services.AddSignalR(o => {
    o.EnableDetailedErrors = true;
    o.MaximumReceiveMessageSize = null;
  });

and 
 set 
   ApplicationMaxBufferSize=0
  TransportMaxBufferSize =0 

can anyone help with it, and want to know , can this issue of message size limit cause by server ?

### Expected Behavior

Singlar should send message of any size without giving 1006 error on server as it working on dev machine.

### Steps To Reproduce

Increase size of message sent over signlar on win 2016 server.

### Exceptions (if any)

_1006 error on message size increase_

### .NET Version

.net core - 5

**Comment by davidfowl** [comment]
What is big? What are the exceptions that you are seeing? Can you debug it? Is there a stack trace?

**Comment by pranayrana** [comment]
Hi davidfowl,

Big means size of message over signalr, so I can send around  8000 objects in one message to client in my local dev environment 

But on server i can only able to send 100 objects.

**Comment by davidfowl** [comment]
This needs more information before we can make any progress.

**Comment by halter73** [comment]
We really need to see more details about the exception message and stack trace (assuming there is one) or some more details about the error. It looks like this might be some sort of connection error with the WebSocket, but we can't really tell.

**Comment by pranayrana** [comment]
Hi,
I am doing following 

From Hub I am sending message to my angular client as below 
`public async Task SendMessageToClient(List<ChartModel> message)
        {
            _logger.Info("MEssage sent to all client");
            await Clients.All.SendMessageToClient(message);
        }`

Object 
`  public class ChartModel
    {
        public List<int> Data { get; set; }
        public string Label { get; set; }

        public ChartModel()
        {
            Data = new List<int>();
        }
    }`

Messsage sent 
`   return new List<ChartModel>()
        {
                new ChartModel { Data = new List<int> { r.Next(1, 40) }, Label = "Data1" },
               ...repeted this around 7000 times same line 
       }`

when I send there is no error in .net code , I receive 1006 error in my browser.

And as i mentioned this error is coming when I deploy and run my code from win 2016  server , on my local machine all works fine without any issue.

**Comment by davidfowl** [comment]
@pranayrana right but we don't have access to the environment nor the source, so we need as much information as possible to help you diagnose the issue. Can you check if there are any server side exceptions? Check the event log etc?

**Comment by pranayrana** [comment]
I checked event logs only thing i receive is "disconnect" event at server side when it unable to send message.

**Comment by davidfowl** [comment]
Sorry I mean the event log on windows using the windows event viewer.

**Comment by davidfowl** [comment]
@pranayrana can you provide logs as @BrennanConroy described here https://github.com/dotnet/aspnetcore/issues/41675#issuecomment-1132032965

**Comment by pranayrana** [comment]
Hi,

There is no log generated in trace i see connection and disconnection only , but log is not providing any information about why it get disconnected.
Pleaser find attached file of code.

[angular client.txt](https://github.com/dotnet/aspnetcore/files/8893330/angular.client.txt)
[asp.net hub.txt](https://github.com/dotnet/aspnetcore/files/8893331/asp.net.hub.txt)

**Comment by davidfowl** [comment]
Can you provide the log anyways?

**Comment by pranayrana** [comment]
> Can you provide the log anyways?

Log on Server 


2022-06-22 05:41:33.3662 INFO Received HTTP response headers after 484.1071ms - 200
2022-06-22 05:41:33.3662 INFO End processing HTTP request after 486.79ms - 200
2022-06-22 05:43:46.0894 ERROR Error when dispatching 'OnDisconnectedAsync' on hub.
2022-06-22 05:43:46.1087 ERROR Failed disposing connection Ry8KeQ4o4wenIJkvTVzxTA.


Console on client side 
Utils.js:159 [2022-06-22T09:43:17.797Z] Debug: Starting HubConnection.
Utils.js:159 [2022-06-22T09:43:17.797Z] Debug: Starting connection with transfer format 'Text'.
Utils.js:159 [2022-06-22T09:43:17.798Z] Trace: (WebSockets transport) Connecting.
core.js:26833 Angular is running in development mode. Call enableProdMode() to enable production mode.
zone-evergreen.js:2845 XHR finished loading: GET "http://localhost:4200/sockjs-node/info?t=1655890997914".
scheduleTask @ zone-evergreen.js:2845
scheduleTask @ zone-evergreen.js:385
scheduleTask @ zone-evergreen.js:210
scheduleMacroTask @ zone-evergreen.js:233
scheduleMacroTaskWithCurrentZone @ zone-evergreen.js:1134
(anonymous) @ zone-evergreen.js:2878
proto.<computed> @ zone-evergreen.js:1449
AbstractXHRObject._start @ sockjs.js:1606
(anonymous) @ sockjs.js:1495
invokeTask @ zone-evergreen.js:399
runTask @ zone-evergreen.js:167
invokeTask @ zone-evergreen.js:480
ZoneTask.invoke @ zone-evergreen.js:469
timer @ zone-evergreen.js:2552
setTimeout (async)
scheduleTask @ zone-evergreen.js:2573
scheduleTask @ zone-evergreen.js:385
scheduleTask @ zone-evergreen.js:210
scheduleMacroTask @ zone-evergreen.js:233
scheduleMacroTaskWithCurrentZone @ zone-evergreen.js:1134
(anonymous) @ zone-evergreen.js:2586
proto.<computed> @ zone-evergreen.js:1449
AbstractXHRObject @ sockjs.js:1494
XHRLocalObject @ sockjs.js:2915
InfoAjax @ sockjs.js:356
InfoReceiver._getReceiver @ sockjs.js:536
InfoReceiver.doXhr @ sockjs.js:556
(anonymous) @ sockjs.js:525
invokeTask @ zone-evergreen.js:399
runTask @ zone-evergreen.js:167
invokeTask @ zone-evergreen.js:480
ZoneTask.invoke @ zone-evergreen.js:469
timer @ zone-evergreen.js:2552
setTimeout (async)
scheduleTask @ zone-evergreen.js:2573
scheduleTask @ zone-evergreen.js:385
scheduleTask @ zone-evergreen.js:210
scheduleMacroTask @ zone-evergreen.js:233
scheduleMacroTaskWithCurrentZone @ zone-evergreen.js:1134
(anonymous) @ zone-evergreen.js:2586
proto.<computed> @ zone-evergreen.js:1449
InfoReceiver @ sockjs.js:524
SockJS @ sockjs.js:731
SockJSClient @ SockJSClient.js:43
initSocket @ socket.js:20
(anonymous) @ client:176
./node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:0/sockjs-node&sockPath=/sockjs-node @ vendor.js:144112
__webpack_require__ @ bootstrap:79
0 @ main.ts:12
__webpack_require__ @ bootstrap:79
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
client:52 [WDS] Live Reloading enabled.
Utils.js:155 [2022-06-22T09:43:34.784Z] Information: WebSocket connected to wss://message.
Utils.js:159 [2022-06-22T09:43:34.785Z] Debug: The HttpConnection connected successfully.
Utils.js:159 [2022-06-22T09:43:34.785Z] Debug: Sending handshake request.
Utils.js:159 [2022-06-22T09:43:34.786Z] Trace: (WebSockets transport) sending data. String data of length 32.
Utils.js:155 [2022-06-22T09:43:34.786Z] Information: Using HubProtocol 'json'.
app.component.ts:52 {Message: 'Request Completed'}
zone-evergreen.js:2845 XHR finished loading: GET "WeatherForecast/chart".
scheduleTask @ zone-evergreen.js:2845
scheduleTask @ zone-evergreen.js:385
onScheduleTask @ zone-evergreen.js:272
scheduleTask @ zone-evergreen.js:378
scheduleTask @ zone-evergreen.js:210
scheduleMacroTask @ zone-evergreen.js:233
scheduleMacroTaskWithCurrentZone @ zone-evergreen.js:1134
(anonymous) @ zone-evergreen.js:2878
proto.<computed> @ zone-evergreen.js:1449
(anonymous) @ http.js:1776
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
subscribeToResult @ subscribeToResult.js:9
_innerSub @ mergeMap.js:59
_tryNext @ mergeMap.js:53
_next @ mergeMap.js:36
next @ Subscriber.js:49
(anonymous) @ subscribeToArray.js:3
_trySubscribe @ Observable.js:42
subscribe @ Observable.js:28
call @ mergeMap.js:21
subscribe @ Observable.js:23
call @ filter.js:13
subscribe @ Observable.js:23
call @ map.js:16
subscribe @ Observable.js:23
startHttpRequest @ app.component.ts:51
ngOnInit @ app.component.ts:46
callHook @ core.js:3038
callHooks @ core.js:3008
executeInitAndCheckHooks @ core.js:2960
refreshView @ core.js:7187
renderComponentOrTemplate @ core.js:7286
tickRootContext @ core.js:8498
detectChangesInRootView @ core.js:8523
detectChanges @ core.js:9899
tick @ core.js:28351
_loadComponent @ core.js:28387
bootstrap @ core.js:28328
(anonymous) @ core.js:28030
_moduleDoBootstrap @ core.js:28030
(anonymous) @ core.js:28000
invoke @ zone-evergreen.js:364
onInvoke @ core.js:27437
invoke @ zone-evergreen.js:363
run @ zone-evergreen.js:123
(anonymous) @ zone-evergreen.js:857
invokeTask @ zone-evergreen.js:399
onInvokeTask @ core.js:27425
invokeTask @ zone-evergreen.js:398
runTask @ zone-evergreen.js:167
drainMicroTaskQueue @ zone-evergreen.js:569
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:552
scheduleTask @ zone-evergreen.js:388
scheduleTask @ zone-evergreen.js:210
scheduleMicroTask @ zone-evergreen.js:230
scheduleResolveOrReject @ zone-evergreen.js:847
then @ zone-evergreen.js:979
bootstrapModule @ core.js:28025
./src/main.ts @ main.ts:11
__webpack_require__ @ bootstrap:79
0 @ main.ts:12
__webpack_require__ @ bootstrap:79
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
Show 22 more frames
Utils.js:159 [2022-06-22T09:43:35.056Z] Trace: (WebSockets transport) data received. String data of length 3.
Utils.js:159 [2022-06-22T09:43:35.057Z] Debug: Server handshake complete.
Utils.js:159 [2022-06-22T09:43:35.058Z] Debug: HubConnection connected successfully.
signal-r.service.ts:29 Connection started
Utils.js:159 [2022-06-22T09:43:46.217Z] Trace: (WebSockets transport) socket closed.
Utils.js:159 [2022-06-22T09:43:46.217Z] Debug: HttpConnection.stopConnection(Error: WebSocket closed with status code: 1006 (no reason given).) called while in state Connected.
Utils.js:149 [2022-06-22T09:43:46.217Z] Error: Connection disconnected with error 'Error: WebSocket closed with status code: 1006 (no reason given).'.
log @ Utils.js:149
_stopConnection @ HttpConnection.js:398
transport.onclose @ HttpConnection.js:336
_close @ WebSocketTransport.js:135
webSocket.onclose @ WebSocketTransport.js:87
wrapFn @ zone-evergreen.js:1218
invokeTask @ zone-evergreen.js:399
onInvokeTask @ core.js:27425
invokeTask @ zone-evergreen.js:398
runTask @ zone-evergreen.js:167
invokeTask @ zone-evergreen.js:480
invokeTask @ zone-evergreen.js:1621
globalZoneAwareCallback @ zone-evergreen.js:1647
Utils.js:159 [2022-06-22T09:43:46.218Z] Debug: HubConnection.connectionClosed(Error: WebSocket closed with status code: 1006 (no reason given).) called while in state Connected.
signal-r.service.ts:32 Error: WebSocket closed with status code: 1006 (no reason given).
    at WebSocketTransport._close (WebSocketTransport.js:135:1)
    at WebSocket.webSocket.onclose (WebSocketTransport.js:87:1)
    at WebSocket.wrapFn (zone-evergreen.js:1218:1)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399:1)
    at Object.onInvokeTask (core.js:27425:1)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398:1)
    at Zone.runTask (zone-evergreen.js:167:1)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:480:1)
    at invokeTask (zone-evergreen.js:1621:1)
    at WebSocket.globalZoneAwareCallback (zone-evergreen.js:1647:1)

**Comment by pranayrana** [comment]
> > Utils.js:159 [2022-06-22T09:43:35.056Z] Trace: (WebSockets transport) data received. String data of length 3.
> > Utils.js:159 [2022-06-22T09:43:35.057Z] Debug: Server handshake complete.
> > Utils.js:159 [2022-06-22T09:43:35.058Z] Debug: HubConnection connected successfully.
> > signal-r.service.ts:29 Connection started
> > Utils.js:159 [2022-06-22T09:43:46.217Z] Trace: (WebSockets transport) socket closed.
> > Utils.js:159 [2022-06-22T09:43:46.217Z] Debug: HttpConnection.stopConnection(Error: WebSocket closed with status code: 1006 (no reason given).) called while in state Connected.
> 
> Well at least now we know the client isn't do anything.
> 
> Your server logs are still lacking though, you haven't included the beginning and middle of the logs, there aren't any debug logs, and whatever logger you are using doesn't include exceptions. Please take a look at the doc we've linked to configure logging, and preferably use the console logger as it includes exception info as well as logging categories. https://docs.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-6.0#server-side-logging


Server log

2022-06-23 02:42:52.8941 INFO Executing endpoint '/message'
2022-06-23 02:42:52.9062 DEBUG New connection kgrsiqmBqgRph1KFTrYPJQ created.
2022-06-23 02:42:52.9062 DEBUG Establishing new connection.
2022-06-23 02:42:52.9062 DEBUG OnConnectedAsync started.
2022-06-23 02:42:52.9342 DEBUG Socket opened using Sub-Protocol: '(null)'.
2022-06-23 02:42:52.9678 INFO CORS policy execution successful.
2022-06-23 02:42:53.1961 DEBUG Found protocol implementation for requested protocol: json.
2022-06-23 02:42:53.2015 DEBUG Completed connection handshake. Using HubProtocol 'json'.
2022-06-23 02:43:04.7844 INFO Application started. Hosting environment: Production; Content root path: C:\Service\
2022-06-23 02:43:05.7941 DEBUG Waiting for the application to finish sending data.
2022-06-23 02:43:05.7976 DEBUG Error writing frame.
2022-06-23 02:43:05.7976 DEBUG Socket closed.
2022-06-23 02:43:05.7976 ERROR Error when dispatching 'OnDisconnectedAsync' on hub.
2022-06-23 02:43:05.8122 DEBUG OnConnectedAsync ending.
2022-06-23 02:43:05.8122 ERROR Failed disposing connection kgrsiqmBqgRph1KFTrYPJQ.
2022-06-23 02:43:05.8122 DEBUG Removing connection kgrsiqmBqgRph1KFTrYPJQ from the list of connections.
2022-06-23 02:43:05.8300 INFO Executed endpoint '/message'
2022-06-23 02:43:05.8500 INFO Request finished HTTP/1.1 GET https://***/message - - - 101 0 - 13874.0700ms


Note:
This code is working bfine on windows 2010 but getting error on windows server 2016

**Comment by BrennanConroy** [comment]
> 2022-06-23 02:42:53.2015 DEBUG Completed connection handshake. Using HubProtocol 'json'.
2022-06-23 02:43:04.7844 INFO Application started. Hosting environment: Production; Content root path: C:\Service
2022-06-23 02:43:05.7941 DEBUG Waiting for the application to finish sending data.

This is kind of interesting, it looks like the log from starting a Windows Service is in the middle of your logs. Why is this starting so late?
Also, what if anything are you doing on the server side with the SignalR connection?

Finally, there is very likely an exception or 2 that's missing from your logs because you aren't using a logger that shows exceptions. It might be very helpful to see the exception in the logs to help narrow down things.

The built-in console logger will display exceptions and can be added via:
```csharp
var builder = WebApplication.CreateBuilder();
builder.Host.ConfigureLogging(logging =>
{
    logging.AddConsole();
});
```

**Comment by pranayrana** [comment]
> > 2022-06-23 02:42:53.2015 DEBUG Completed connection handshake. Using HubProtocol 'json'.
> > 2022-06-23 02:43:04.7844 INFO Application started. Hosting environment: Production; Content root path: C:\Service
> > 2022-06-23 02:43:05.7941 DEBUG Waiting for the application to finish sending data.
> 
> This is kind of interesting, it looks like the log from starting a Windows Service is in the middle of your logs. Why is this starting so late? Also, what if anything are you doing on the server side with the SignalR connection?
> 
> Finally, there is very likely an exception or 2 that's missing from your logs because you aren't using a logger that shows exceptions. It might be very helpful to see the exception in the logs to help narrow down things.
> 
> The built-in console logger will display exceptions and can be added via:
> 
> ```cs
> var builder = WebApplication.CreateBuilder();
> builder.Logging.AddConsole();
> ```


Full log , i hope I get some conclution 

dbug: Microsoft.AspNetCore.SignalR.Internal.DefaultHubProtocolResolver[1]
      Registered SignalR Protocol: json, implemented by Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.
2022-06-24 01:00:20.9566 DEBUG Registered SignalR Protocol: json, implemented by Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.
trce: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[9]
      'OscarHub' hub method 'StartSubscription' is bound.
2022-06-24 01:00:21.0213 TRACE 'OscarHub' hub method 'StartSubscription' is bound.
trce: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[9]
      'OscarHub' hub method 'StopSubscription' is bound.
2022-06-24 01:00:21.0265 TRACE 'OscarHub' hub method 'StopSubscription' is bound.
2022-06-24 01:00:21.0265 TRACE 'OscarHub' hub method 'TriggerDataFetch' is bound.
trce: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[9]
      'OscarHub' hub method 'TriggerDataFetch' is bound.
trce: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[9]
      'MessageHub' hub method 'SendMessageToClient' is bound.
2022-06-24 01:00:21.0539 TRACE 'MessageHub' hub method 'SendMessageToClient' is bound.
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://*:**/**/
2022-06-24 01:00:21.0953 INFO Now listening on: https://*:**/**/
trce: Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager[9]
      Starting connection heartbeat.
2022-06-24 01:00:22.3074 TRACE Starting connection heartbeat.
info2022-06-24 01:00:22.3104 INFO Application started. Press Ctrl+C to shut down.
: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
2022-06-24 01:00:22.3104 INFO Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info2022-06-24 01:00:22.3104 INFO Content root path: C:\*.Service
: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\.Service
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET https://**/message - -
info2022-06-24 01:01:15.8407 INFO Request starting HTTP/1.1 GET https://**/WeatherForecast/chart - -
: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET https://**/WeatherForecast/chart - -
2022-06-24 01:01:15.8407 INFO Request starting HTTP/1.1 GET https://**/message - -
info2022-06-24 01:01:16.8257 INFO CORS policy execution successful.
: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
      CORS policy execution successful.
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint '/message'
2022-06-24 01:01:16.8342 INFO Executing endpoint '/message'
dbug2022-06-24 01:01:16.8342 DEBUG New connection ngrDmR4RE7nzCqCOn0J9Sg created.
: Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager[1]
      New connection ngrDmR4RE7nzCqCOn0J9Sg created.
dbug2022-06-24 01:01:16.8497 DEBUG Establishing new connection.
: Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher[4]
      Establishing new connection.
2022-06-24 01:01:16.8497 DEBUG OnConnectedAsync started.
dbug: Microsoft.AspNetCore.SignalR.HubConnectionHandler[5]
      OnConnectedAsync started.
2022-06-24 01:01:16.8648 DEBUG Socket opened using Sub-Protocol: '(null)'.
dbug: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[1]
      Socket opened using Sub-Protocol: '(null)'.
info2022-06-24 01:01:16.9082 INFO CORS policy execution successful.
: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
      CORS policy execution successful.
info2022-06-24 01:01:16.9082 INFO Executing endpoint '_netcore.Controllers.WeatherForecastController.GetChartData (OscarCore.WebApiUtilsNetCore)'
: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint '_netcore.Controllers.WeatherForecastController.GetChartData (OscarCore.WebApiUtilsNetCore)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "GetChartData", controller = "WeatherForecast"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult GetChartData() on controller _netcore.Controllers.WeatherForecastController (OscarCore.WebApiUtilsNetCore).
2022-06-24 01:01:16.9322 INFO Route matched with {action = "GetChartData", controller = "WeatherForecast"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult GetChartData() on controller _netcore.Controllers.WeatherForecastController (OscarCore.WebApiUtilsNetCore).
info2022-06-24 01:01:16.9433 INFO Executing OkObjectResult, writing value of type '<>f__AnonymousType1`1[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
      Executing OkObjectResult, writing value of type '<>f__AnonymousType1`1[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action _netcore.Controllers.WeatherForecastController.GetChartData (OscarCore.WebApiUtilsNetCore) in 28.7598ms
2022-06-24 01:01:16.9692 INFO Executed action _netcore.Controllers.WeatherForecastController.GetChartData (OscarCore.WebApiUtilsNetCore) in 28.7598ms
info2022-06-24 01:01:16.9692 INFO Executed endpoint '_netcore.Controllers.WeatherForecastController.GetChartData (OscarCore.WebApiUtilsNetCore)'
: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint '_netcore.Controllers.WeatherForecastController.GetChartData (OscarCore.WebApiUtilsNetCore)'
info2022-06-24 01:01:16.9692 INFO Request finished HTTP/1.1 GET https://**/WeatherForecast/chart - - - 200 - application/json;+charset=utf-8 1137.8272ms
: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET https://**/WeatherForecast/chart - - - 200 - application/json;+charset=utf-8 1137.8272ms
trce: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[9]
      Message received. Type: Text, size: 32, EndOfMessage: True.
2022-06-24 01:01:17.1425 TRACE Message received. Type: Text, size: 32, EndOfMessage: True.


**dbug2022-06-24 01:01:17.1425 DEBUG Found protocol implementation for requested protocol: json.
: Microsoft.AspNetCore.SignalR.Internal.DefaultHubProtocolResolver[2]
      Found protocol implementation for requested protocol: json.
2022-06-24 01:01:17.1589 DEBUG Completed connection handshake. Using HubProtocol 'json'.
dbug: Microsoft.AspNetCore.SignalR.HubConnectionContext[1]
      Completed connection handshake. Using HubProtocol 'json'.
trce: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[11]
      Sending payload: 3 bytes.
2022-06-24 01:01:17.1589 TRACE Sending payload: 3 bytes.
trce2022-06-24 01:01:18.0421 TRACE Sending payload: 1488535 bytes.
: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[11]
      Sending payload: 1488535 bytes.
dbug2022-06-24 01:01:28.4094 DEBUG Waiting for the application to finish sending data.
: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[4]
      Waiting for the application to finish sending data.
dbug2022-06-24 01:01:28.4094 DEBUG Error writing frame.
: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[12]
      Error writing frame.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync(MessageOpcode opcode, Boolean endOfMessage, ReadOnlyMemory`1 payloadBuffer, CancellationToken cancellationToken)
         at System.Net.WebSockets.WebSocketExtensions.SendMultiSegmentAsync(WebSocket webSocket, ReadOnlySequence`1 buffer, WebSocketMessageType webSocketMessageType, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsServerTransport.StartSending(WebSocket socket)
dbug2022-06-24 01:01:28.4094 DEBUG Socket closed.
: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[2]
      Socket closed.
trce2022-06-24 01:01:28.4094 TRACE Disposing connection ngrDmR4RE7nzCqCOn0J9Sg.
: Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext[1]
      Disposing connection ngrDmR4RE7nzCqCOn0J9Sg.
2022-06-24 01:01:28.4094 TRACE Waiting for application to complete.**


trce: Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext[2]
      Waiting for application to complete.
fail: Microsoft.AspNetCore.SignalR.HubConnectionHandler[1]
      Error when dispatching 'OnDisconnectedAsync' on hub.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Oscar.Common.Utils.Log.Write(LogLevel logLevel, Exception ex)
         at OscarCore.Common.DefaultLogger.Error(Exception ex) in C:\*.cs:line 34
         at OscarCore.WebSocketUtilsNetCore.Hubs.MessageHub.OnDisconnectedAsync(Exception exception) in C:\*\Hubs\TestMessageHub.cs:line 50
         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnDisconnectedAsync(HubConnectionContext connection, Exception exception)
         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnDisconnectedAsync(HubConnectionContext connection, Exception exception)
         at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.HubOnDisconnectedAsync(HubConnectionContext connection, Exception exception)
2022-06-24 01:01:28.4313 ERROR Error when dispatching 'OnDisconnectedAsync' on hub.
2022-06-24 01:01:28.4313 DEBUG OnConnectedAsync ending.
dbug: Microsoft.AspNetCore.SignalR.HubConnectionHandler[6]
      OnConnectedAsync ending.
trce: Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext[3]
      Application complete.
2022-06-24 01:01:28.4313 TRACE Application complete.
fail: Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager[3]
      Failed disposing connection ngrDmR4RE7nzCqCOn0J9Sg.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Oscar.Common.Utils.Log.Write(LogLevel logLevel, Exception ex)
         at OscarCore.Common.DefaultLogger.Error(Exception ex) in C:\*.cs:line 34
         at OscarCore.WebSocketUtilsNetCore.Hubs.MessageHub.OnDisconnectedAsync(Exception exception) in C:\*\Hubs\TestMessageHub.cs:line 50
         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnDisconnectedAsync(HubConnectionContext connection, Exception exception)
         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnDisconnectedAsync(HubConnectionContext connection, Exception exception)
         at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.HubOnDisconnectedAsync(HubConnectionContext connection, Exception exception)
         at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.RunHubAsync(HubConnectionContext connection)
         at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.OnConnectedAsync(ConnectionContext connection)
         at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.OnConnectedAsync(ConnectionContext connection)
         at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext.ExecuteApplication(ConnectionDelegate connectionDelegate)
         at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext.WaitOnTasks(Task applicationTask, Task transportTask, Boolean closeGracefully)
         at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionContext.DisposeAsync(Boolean closeGracefully)
         at Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager.DisposeAndRemoveAsync(HttpConnectionContext connection, Boolean closeGracefully)
2022-06-24 01:01:28.4466 ERROR Failed disposing connection ngrDmR4RE7nzCqCOn0J9Sg.
2022-06-24 01:01:28.4565 DEBUG Removing connection ngrDmR4RE7nzCqCOn0J9Sg from the list of connections.
dbug: Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager[2]
      Removing connection ngrDmR4RE7nzCqCOn0J9Sg from the list of connections.
info2022-06-24 01:01:28.4565 INFO Executed endpoint '/message'
: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint '/message'
info2022-06-24 01:01:28.4565 INFO Request finished HTTP/1.1 GET https://**/message - - - 101 - - 12627.7625ms
: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET https://**/message - - - 101 - - 12627.7625ms

**Comment by BrennanConroy** [comment]
> trce2022-06-24 01:01:18.0421 TRACE Sending payload: 1488535 bytes.
: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[11]
Sending payload: 1488535 bytes.
dbug2022-06-24 01:01:28.4094 DEBUG Waiting for the application to finish sending data.
: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[4]
Waiting for the application to finish sending data.
dbug2022-06-24 01:01:28.4094 DEBUG Error writing frame.
: Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsTransport[12]
Error writing frame.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
at System.Net.WebSockets.ManagedWebSocket.SendFrameFallbackAsync(MessageOpcode opcode, Boolean endOfMessage, ReadOnlyMemory1 payloadBuffer, CancellationToken cancellationToken) at System.Net.WebSockets.WebSocketExtensions.SendMultiSegmentAsync(WebSocket webSocket, ReadOnlySequence1 buffer, WebSocketMessageType webSocketMessageType, CancellationToken cancellationToken)
at Microsoft.AspNetCore.Http.Connections.Internal.Transports.WebSocketsServerTransport.StartSending(WebSocket socket)

Alright, so what's happening is that SignalR has a 10 second timeout for sends and for some reason it is taking more than 10 seconds to send `1488535 bytes` in your setup. The main reason I can think of that this would happen is that the client is reading really slowly or not at all, and this is a defense mechanism on the server side to avoid malicious or misbehaving clients.

There are a couple things you can try to see if you can narrow down the issue. One is to test with a larger [MaxResponseBufferSize](https://docs.microsoft.com/dotnet/api/microsoft.aspnetcore.server.kestrel.core.kestrelserverlimits.maxresponsebuffersize?view=aspnetcore-6.0#microsoft-aspnetcore-server-kestrel-core-kestrelserverlimits-maxresponsebuffersize), if you set this to a high value like 2,000,000 and wait to see if the client receives the message then we know the client is at least reading from the server.

You should also update your server to .NET 6, both because .NET 5 is out of support but also because in .NET 6 you can set TransportSendTimeout to change the ten second timeout you're observing, and we're constantly making improvements so maybe you'll see better behavior from some change we made between 5 and 6.
```csharp
endpoints.MapHub<ChatHub>("/chathub", options =>
{
    options.TransportSendTimeout = TimeSpan.FromSeconds(...);
});
```

Next I would test with different clients if possible, such as a non-angular browser client or the .NET client and see if similar issues can be observed (without setting the MaxResponseBufferSize limit).

Also, try testing the original client on the server machine, if it doesn't have issues it might just be the network latency between your server machine and client are too high and you need to use smaller messages.

**Comment by pranayrana** [comment]
> What do the logs say?

The issue cause by ServerTimeout and KeepAliveInterval property of hubconnection at client side. It started working after i removed both of this property.
