### ISSUE TITLE
System.IO.DirectoryInfo doesn't work properly in client-side Blazor WebAssembly 

### ISSUE THREAD

**Issue by lb-chc** [dotnet/aspnetcore#41706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not find a part of the path '/wwwroot'.
System.IO.DirectoryNotFoundException: Could not find a part of the path '/wwwroot'.
   at System.IO.Enumeration.FileSystemEnumerator`1[[System.IO.FileInfo, System.IO.FileSystem, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1[[System.IO.FileInfo, System.IO.FileSystem, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].Init()
   at System.IO.Enumeration.FileSystemEnumerator`1[[System.IO.FileInfo, System.IO.FileSystem, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]]..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1.DelegateEnumerator[[System.IO.FileInfo, System.IO.FileSystem, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]]..ctor(FileSystemEnumerable`1 enumerable, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerable`1[[System.IO.FileInfo, System.IO.FileSystem, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]]..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.FileInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.DirectoryInfo.GetFiles(String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.DirectoryInfo.GetFiles(String searchPattern)
   at BiliBili_WebSpider_Processing.IOManager.CollectionAid(String path) in /Users/polaris/My/BiliBili_WebSpider/Project/2/BiliBili_WebSpider_Processing/BiliBili_WebSpider_Processing/wwwroot/lib/mainCoed/IOManager.cs:line 318
   at BiliBili_WebSpider_Processing.CLI_IO.MainCLI(String path, String aid) in /Users/polaris/My/BiliBili_WebSpider/Project/2/BiliBili_WebSpider_Processing/BiliBili_WebSpider_Processing/wwwroot/lib/mainCoed/CLI_IO.cs:line 22
   at BiliBili_WebSpider_Processing.Parser.Main(String path, String aid) in /Users/polaris/My/BiliBili_WebSpider/Project/2/BiliBili_WebSpider_Processing/BiliBili_WebSpider_Processing/wwwroot/lib/mainCoed/Parser.cs:line 28
   at BiliBili_WebSpider_Processing.Pages.Test_1.<BuildRenderTree>b__0_0() in /Users/polaris/My/BiliBili_WebSpider/Project/2/BiliBili_WebSpider_Processing/BiliBili_WebSpider_Processing/Pages/Test_1.razor:line 5
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[Object](MulticastDelegate delegate, Object arg)
   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync(Object arg)
   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
   at Microsoft.AspNetCore.Components.EventCallback.InvokeAsync(Object arg)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs)
d.printErr @ blazor.webassembly.js:1
d.preRun.push.window.Blazor._internal.dotNetCriticalError @ blazor.webassembly.js:1
w @ blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor @ dotnet.5.0.16.js:1
$do_icall @ dotnet.wasm:0x194e4e
$do_icall_wrapper @ dotnet.wasm:0x79df9
$interp_exec_method @ dotnet.wasm:0x44ad3
$interp_runtime_invoke @ dotnet.wasm:0x12efff
$mono_jit_runtime_invoke @ dotnet.wasm:0x118e5f
$do_runtime_invoke @ dotnet.wasm:0x79d42
$mono_runtime_invoke_checked @ dotnet.wasm:0xf65d
$mono_runtime_try_invoke_array @ dotnet.wasm:0x10e831
$ves_icall_InternalInvoke @ dotnet.wasm:0xed492
$ves_icall_InternalInvoke_raw @ dotnet.wasm:0xecf57
$do_icall @ dotnet.wasm:0x194ddb
$do_icall_wrapper @ dotnet.wasm:0x79df9
$interp_exec_method @ dotnet.wasm:0x44ad3
$interp_runtime_invoke @ dotnet.wasm:0x12efff
$mono_jit_runtime_invoke @ dotnet.wasm:0x118e5f
$do_runtime_invoke @ dotnet.wasm:0x79d42
$mono_runtime_try_invoke @ dotnet.wasm:0x12982
$mono_runtime_invoke @ dotnet.wasm:0x10ec2b
$mono_wasm_invoke_method @ dotnet.wasm:0x108e48
Module._mono_wasm_invoke_method @ dotnet.5.0.16.js:1
call_method @ dotnet.5.0.16.js:1
(anonymous) @ dotnet.5.0.16.js:1
beginInvokeDotNetFromJS @ blazor.webassembly.js:1
h @ blazor.webassembly.js:1
e.invokeMethodAsync @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
invokeWhenHeapUnlocked @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
t.dispatchEvent @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
e.onGlobalEvent @ blazor.webassembly.js:1
Show 6 more frames

### Expected Behavior

Access a local file and get a list of file names

### Steps To Reproduce

DirectoryInfo folder = new DirectoryInfo(pathString);
System.IO.FileInfo[] fileInfo = folder.GetFiles("Data_Info_*_*_*_*" + "?.json");

I am trying to read client file by above code but it is giving error

### .NET Version

5.0.15 vs for mac 2019

### Anything else?

Dear developer

I know Blazor WebAssembly shouldn't have direct access to client local disk

But I'm developing a local program and don't need a server (if the architecture has it, they end up in a folder as well and run on a physical machine), I just want c# and html to work together, it's for data visualization

I ran into these issues after copying a program written in a c# console app template to a Blazor WebAssembly template, I really needed a statement like "Data_Info_*_*_*_*" + "?.json" to filter the folders All the required files in the , then sort and read them.

I can understand that the security sandbox prevents me from reading the client's local files, but can I bypass this restriction without separating the client and server?, or can I read files in wwwroot/ in the program directory? No With http? Since I need to read the whole folder at once, going through an upload process is a bit redundant...

Actually what I want is very similar to MAUI, but it is not mature and I am not sure if XAML can use components in HTML WORLD for data visualization

grateful

**Comment by javiercn** [comment]
@lb-chc thanks for contacting us.

The filesystem in Blazor Webassembly doesn't work in the way that you expect. There is a virtual file system provided by emscripten, however developers don't have access to it (we don't expose it) and it only contains the files that you bootstrap the runtime with.

In short, as you pointed out, you can't access the local file system in Blazor Webassembly (in general, you can't do anything that a webpage can't do). For your use case, I think you'll be better off using Blazor Hybrid, which creates a native app that you can host a Blazor app inside via a native webview.

It should give you all the capabilities of a native app, while being able to render the content in HTML.

**Comment by lb-chc** [comment]
your reply is very timely

That being the case, I'm willing to take a detour from the existing foundation... Is there such a syntax?

string forecasts = await Http.xxxxxxxxxx("sample-data/weather.json");
//forecasts =
[
  {
    "date": "2018-05-06",
    "temperatureC": 1,
    "summary": "Freezing"
  },
  {
    "date": "2018-05-07",
    "temperatureC": 14,
    "summary": "Bracing"
  },
......
]


I also know that web security guidelines prohibit me from scanning folders, so, based on this, if blazor webassembly has the concept of a server, I let the server generate a list of file names before each access file: List

List contents are:
[
{
name:"weather_1.json"
},
{
name:"weather_2.json"
},
......
]


The corresponding files in wwwroot are:
-wwwroot/List
-wwwroot/weather_1.json
-wwwroot/weather_2.json
......


Did I achieve my goal?

**Comment by javiercn** [comment]
@lb-chc What you could do is generate a file that contains the list of all the files you care about and request/read that from the server you are hosting the app.

**Comment by lb-chc** [comment]
I changed the project template to blazor server to solve this problem
