### ISSUE TITLE
Blazor Server execption on publish after updating to .net 7

### ISSUE THREAD

**Issue by HeroinGyrl** [dotnet/aspnetcore#41712]
I updated my projects to .net 7 and now I'm getting these errors.

```cs
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.Security.Cryptography.CryptographicException: An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information. For more information go to http://aka.ms/dataprotectionwarning
       ---> System.MissingMethodException: Cannot dynamically create an instance of type 'Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer'. Reason: No parameterless constructor defined.
         at System.RuntimeType.ActivatorCache..ctor(RuntimeType)
         at System.RuntimeType.CreateInstanceDefaultCtor(Boolean, Boolean)
         at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
         at System.Activator.CreateInstance(Type type, Boolean nonPublic)
         at System.Activator.CreateInstance(Type type)
         at Microsoft.AspNetCore.DataProtection.SimpleActivator.CreateInstance(Type, String)
         at Microsoft.AspNetCore.DataProtection.TypeForwardingActivator.CreateInstance(Type, String, Boolean& )
         at Microsoft.AspNetCore.DataProtection.TypeForwardingActivator.CreateInstance(Type, String)
         at Microsoft.AspNetCore.DataProtection.ActivatorExtensions.CreateInstance[T](IActivator, String)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.DeserializeDescriptorFromKeyElement(XElement)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.DeferredKey.<>c__DisplayClass1_0.<GetLazyDescriptorDelegate>g__GetLazyDescriptorDelegate|0()
         at System.Lazy`1.ViaFactory(LazyThreadSafetyMode)
      --- End of stack trace from previous location ---
         at System.LazyHelper.ThrowException()
         at System.Lazy`1.CreateValue()
         at System.Lazy`1.get_Value()
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyBase.get_Descriptor()
         at Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.CngGcmAuthenticatedEncryptorFactory.CreateEncryptorInstance(IKey)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyBase.CreateEncryptor()
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRing.KeyHolder.GetEncryptorInstance(Boolean& )
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRing.get_DefaultAuthenticatedEncryptor()
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[])
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Protect(Byte[])
         at Microsoft.AspNetCore.DataProtection.TimeLimitedDataProtector.Protect(Byte[], DateTimeOffset)
         at Microsoft.AspNetCore.DataProtection.DataProtectionAdvancedExtensions.Protect(ITimeLimitedDataProtector, Byte[], TimeSpan)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.ServerComponentSerializer.CreateSerializedServerComponent(ServerComponentInvocationSequence invocationId, Type rootComponent, ParameterView parameters)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentRenderer.PrerenderedServerComponentAsync(HttpContext context, ServerComponentInvocationSequence invocationId, Type type, ParameterView parametersCollection)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.ComponentRenderer.RenderComponentAsync(ViewContext viewContext, Type componentType, RenderMode renderMode, Object parameters)
         at Microsoft.AspNetCore.Mvc.TagHelpers.ComponentTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
         at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)

         at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
         at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
         at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
         at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint, Task, ILogger)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

running this on local works but after publishing it gives these errors.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. Looks like trimming related issue.
Can you try to disable trimming for your project and see whether that resolves the issue.  Here are the docs on the topic: https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/configure-trimmer?view=aspnetcore-6.0

**Comment by mkArtakMSFT** [comment]
Thanks for confirming, @HeroinGyrl.
Moving over to the data-protection folks to have a look and fix the issue on their end.

**Comment by adityamandaleeka** [comment]
@JamesNK @HaoK

**Comment by JamesNK** [comment]
What version of .NET 7 are you using?

I think the changes recently made to DataProtection should fix this issue - https://github.com/dotnet/aspnetcore/pull/41650
It forces this type's public constructors to be preserved.

Reference all known built-in deserializer types: https://github.com/dotnet/aspnetcore/pull/41650/files#diff-5f1ce9e83d0e8a5bf58227e78bf732ccbf49d7a215550dc4eb14bd421cda4785R468-R494

Annotate CreateInstance to preserve constructors of referenced types: https://github.com/dotnet/aspnetcore/pull/41650/files#diff-afb60fbed504e9bf00c2b71e3ee90662a5ea5a127550b5a30ac254550067589eR21

Those changes will be in .NET 7 preview 5.

I suggest you leave trimming disabled for now, and try enabling it again once preview 5 is publically available.
