### ISSUE TITLE
Quarantine ReaderThrowsResetExceptionOnInvalidBody

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#41812]
We've had about 4 failures for this test in the last month.

## Failing Test(s)

Microsoft.AspNetCore.Server.IIS.FunctionalTests.ClientDisconnectTests.ReaderThrowsResetExceptionOnInvalidBody

## Error Message

```text
System.AggregateException : One or more errors occurred. (Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..) (Unexpected log: Error Microsoft.AspNetCore.Server.IIS.FunctionalTests.ClientDisconnectTests: Test threw an exception.)
```

## Stacktrace

<details>

```text
---- System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
-------- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host.
---- Unexpected log: Error Microsoft.AspNetCore.Server.IIS.FunctionalTests.ClientDisconnectTests: Test threw an exception.
----- Inner Stack Trace #1 (System.IO.IOException) -----
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 106
   at Microsoft.AspNetCore.Server.IntegrationTesting.TestConnection.Receive(Int32 length) in D:\a\_work\1\s\src\Servers\IIS\IIS\test\testassets\IIS.Common.TestLib\TestConnections.cs:line 156
   at Microsoft.AspNetCore.Server.IntegrationTesting.TestConnection.Receive(String[] lines) in D:\a\_work\1\s\src\Servers\IIS\IIS\test\testassets\IIS.Common.TestLib\TestConnections.cs:line 121
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.ClientDisconnectTests.ReaderThrowsResetExceptionOnInvalidBody() in /_/src/Servers/IIS/IIS/test/IIS.Tests/ClientDisconnectTests.cs:line 264
--- End of stack trace from previous location ---
----- Inner Stack Trace -----

----- Inner Stack Trace #2 (Xunit.Sdk.XunitException) -----
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.StrictTestServerTests.Dispose() in /_/src/Servers/IIS/IIS/test/IIS.Tests/StrictTestServerTests.cs:line 22
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\Dev\xunit\xunit\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 79
```
</details>

## Logs

<details>

```text
| [0.001s] TestLifetime Information: Starting test ReaderThrowsResetExceptionOnInvalidBody at 2022-05-23T22:08:47
| [0.026s] Microsoft.AspNetCore.Server.IIS.FunctionalTests.TestServer Debug: Method: GET, RequestUri: 'http://localhost:50854/start', Version: 1.1, Content: <null>, Headers:
|                                                                            {
|                                                                            }
| [0.032s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting starting
| [0.033s] Microsoft.AspNetCore.Hosting.Diagnostics Debug: Loaded hosting startup assembly IIS.Tests
| [0.033s] Microsoft.Hosting.Lifetime Information: Application started. Press Ctrl+C to shut down.
| [0.033s] Microsoft.AspNetCore.Hosting.Diagnostics Information: Request starting HTTP/1.1 GET http://localhost:50854/start - -
| [0.033s] Microsoft.Hosting.Lifetime Information: Hosting environment: Production
| [0.033s] Microsoft.Hosting.Lifetime Information: Content root path: C:\h\w\AE5C0955\w\B65A0A02\e\.
| [0.033s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting started
| [0.034s] Microsoft.AspNetCore.Hosting.Diagnostics Information: Request finished HTTP/1.1 GET http://localhost:50854/start - - - 200 - - 0.3381ms
| [0.034s] Microsoft.AspNetCore.Server.IIS.FunctionalTests.TestServer Debug: StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
|                                                                            {
|                                                                              Transfer-Encoding: chunked
|                                                                              Server: Microsoft-IIS/10.0
|                                                                              Date: Mon, 23 May 2022 22:08:47 GMT
|                                                                            }
| [0.034s] Microsoft.AspNetCore.Server.IIS.FunctionalTests.TestServer Debug: Done
| [0.035s] Microsoft.AspNetCore.Hosting.Diagnostics Information: Request starting HTTP/1.1 POST http://localhost/ - -
| [0.036s] Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer Debug: Connection ID "18374686484771897400" disconnecting.
| [0.037s] Microsoft.AspNetCore.Hosting.Diagnostics Information: Request finished HTTP/1.1 POST http://localhost/ - - - 0 - - 1.3010ms
| [0.161s] Microsoft.Hosting.Lifetime Information: Application is shutting down...
| [2.391s] Microsoft.AspNetCore.Server.IIS.FunctionalTests.ClientDisconnectTests Error: Test threw an exception.
| System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
|  ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
|    --- End of inner exception stack trace ---
|    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
|    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
|    at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
| --- End of stack trace from previous location ---
|    at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 106
|    at Microsoft.AspNetCore.Server.IntegrationTesting.TestConnection.Receive(Int32 length) in D:\a\_work\1\s\src\Servers\IIS\IIS\test\testassets\IIS.Common.TestLib\TestConnections.cs:line 156
|    at Microsoft.AspNetCore.Server.IntegrationTesting.TestConnection.Receive(String[] lines) in D:\a\_work\1\s\src\Servers\IIS\IIS\test\testassets\IIS.Common.TestLib\TestConnections.cs:line 121
|    at Microsoft.AspNetCore.Server.IIS.FunctionalTests.ClientDisconnectTests.ReaderThrowsResetExceptionOnInvalidBody() in /_/src/Servers/IIS/IIS/test/IIS.Tests/ClientDisconnectTests.cs:line 264
|    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 273
| --- End of stack trace from previous location ---
|    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 54
|    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 96
| [2.393s] TestLifetime Information: Finished test ReaderThrowsResetExceptionOnInvalidBody in 2.3920249s


```
</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1785419&view=ms.vss-test-web.build-test-results-tab&runId=47803008&resultId=110391&paneView=attachments

**Comment by HaoK** [comment]
Test is behaving with retries in quarantine, going to unquarantine in https://github.com/dotnet/aspnetcore/pull/42932 as local retries should have helped  with this test as well
