### ISSUE TITLE
Quarantine ServerReset_AfterEndStream_NoError

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#41843]
## Failing Test(s)

- Interop.FunctionalTests.HttpClientHttp2InteropTests.ServerReset_AfterEndStream_NoError(scheme: "http")

## Error Message

```text
System.Net.Http.HttpRequestException : Error while copying content to a stream.
---- System.IO.IOException : The request was aborted.
-------- System.Net.Http.Http2StreamException : The HTTP/2 server reset the stream. HTTP/2 error code 'CANCEL' (0x8).
```

## Stacktrace

<details>

```text
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpContent.WaitAndReturnAsync[TState,TResult](Task waitTask, TState state, Func`2 returnFunc)
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 106
   at Interop.FunctionalTests.HttpClientHttp2InteropTests.ServerReset_AfterEndStream_NoError(String scheme) in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/HttpClientHttp2InteropTests.cs:line 658
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryReadFromBuffer(Span`1 buffer, Boolean partOfSyncRead)
   at System.Net.Http.Http2Connection.Http2Stream.CopyToAsync(HttpResponseMessage responseMessage, Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionResponseContent.<SerializeToStreamAsync>g__Impl|6_0(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
----- Inner Stack Trace -----
```
</details>

## Logs

<details>

[HttpClientHttp2InteropTests_ServerReset_AfterEndStream_NoError-https.log](https://github.com/dotnet/aspnetcore/files/8773503/HttpClientHttp2InteropTests_ServerReset_AfterEndStream_NoError-https.log)

[HttpClientHttp2InteropTests_ServerReset_AfterEndStream_NoError-http.log](https://github.com/dotnet/aspnetcore/files/8773505/HttpClientHttp2InteropTests_ServerReset_AfterEndStream_NoError-http.log)

</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1786361&view=ms.vss-test-web.build-test-results-tab&runId=47815376&resultId=108661&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by adityamandaleeka** [comment]
This one may be related to the recent changes in HTTP/2. It's happened twice in the past week. We should investigate to see if there's a race condition somewhere.

cc: @davidfowl

**Comment by halter73** [comment]
In the passing test log, a `RST_STREAM` frame is sent to the client after the last data frame with the `END_STREAM` flag.

In the failing test log, a `RST_STREAM` frame is sent to the client and Kestrel never sends the final data frame or `END_STREAM` at all. `await context.Response.CompleteAsync()` completes before the `Http2OutputProducer` is able to observe the completion (because of the buffering we do for perf reasons) and therefore the subsequent call to `context.Features.Get<IHttpResetFeature>().Reset(8)` skips the line so-to-speak.

I talked to @JamesNK about how this affects gRPC, because in my mind if `CompleteAsync()` completes successfully it would cause a mismatch between what the server logs and what the client sees, but that shouldn't be a huge deal. The server can never be sure whether the client has gotten a full response without an application-level ACK anyway. James pointed out that this test could also be caused by a race condition in HttpClient at https://github.com/dotnet/runtime/issues/68373. But at least in the case of this failing test log, Kestrel never sends an `END_STREAM` flag at all.

I think we can fix the issue with the `context.Features.Get<IHttpResetFeature>().Reset(8)` skipping the line and workaround the HttpClient race condition all at the same time. We could make `Http2Stream.ApplicationAbort(ConnectionAbortedException abortReason, Http2ErrorCode error)` queue its call to `_frameWriter.WriteRstStreamAsync(StreamId, error)`  to the `Http2FrameWriter.WriteToOutputPipe()` loop instead of calling it inline even if `_completeScheduled` hasn't been set yet. This way the `RST_STREAM` frame can never skip the line, and we just wouldn't write the `RST_STREAM` at all after the `END_STREAM` flag in `WriteToOutputPipe()`.

It's to important to note that `ApplicationAbort()` is only called via `HttpContext.Abort()`, `IHttpResetFeature.Reset(int errorCode)` and `CompleteAsync(Exception)`. These are all only called by the application and shouldn't be expected to do anything after the response completes. Our own internal logic to send `RST_STREAM` for things like the client uploading after the stream completed would continue to use `_frameWriter.WriteRstStreamAsync(StreamId, error)` directly.
