### ISSUE TITLE
Quarantine ClientDisconnectsWithoutCompletingClientResultOnSecondServer

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#41858]
## Failing Test(s)

- Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.RedisHubLifetimeManagerTests.ClientDisconnectsWithoutCompletingClientResultOnSecondServer

## Error Message

```text
Assert.Throws() Failure
Expected: typeof(System.Exception)
Actual:   typeof(System.InvalidOperationException): Collection was modified; enumeration operation may not execute.
---- System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
```

## Stacktrace

<details>

```text
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at Microsoft.AspNetCore.SignalR.Tests.TestRedisServer.Publish(RedisChannel channel, RedisValue message, CommandFlags flags) in /_/src/SignalR/server/StackExchangeRedis/test/TestConnectionMultiplexer.cs:line 235
   at Microsoft.AspNetCore.SignalR.Tests.TestSubscriber.Publish(RedisChannel channel, RedisValue message, CommandFlags flags) in /_/src/SignalR/server/StackExchangeRedis/test/TestConnectionMultiplexer.cs:line 313
   at Microsoft.AspNetCore.SignalR.Tests.TestSubscriber.PublishAsync(RedisChannel channel, RedisValue message, CommandFlags flags) in /_/src/SignalR/server/StackExchangeRedis/test/TestConnectionMultiplexer.cs:line 319
   at Microsoft.AspNetCore.SignalR.StackExchangeRedis.RedisHubLifetimeManager`1.PublishAsync(String channel, Byte[] payload) in /_/src/SignalR/server/StackExchangeRedis/src/RedisHubLifetimeManager.cs:line 320
   at Microsoft.AspNetCore.SignalR.StackExchangeRedis.RedisHubLifetimeManager`1.InvokeConnectionAsync[T](String connectionId, String methodName, Object[] args, CancellationToken cancellationToken) in /_/src/SignalR/server/StackExchangeRedis/src/RedisHubLifetimeManager.cs:line 422
----- Inner Stack Trace -----
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at Microsoft.AspNetCore.SignalR.Tests.TestRedisServer.Publish(RedisChannel channel, RedisValue message, CommandFlags flags) in /_/src/SignalR/server/StackExchangeRedis/test/TestConnectionMultiplexer.cs:line 235
   at Microsoft.AspNetCore.SignalR.Tests.TestSubscriber.Publish(RedisChannel channel, RedisValue message, CommandFlags flags) in /_/src/SignalR/server/StackExchangeRedis/test/TestConnectionMultiplexer.cs:line 313
   at Microsoft.AspNetCore.SignalR.Tests.TestSubscriber.PublishAsync(RedisChannel channel, RedisValue message, CommandFlags flags) in /_/src/SignalR/server/StackExchangeRedis/test/TestConnectionMultiplexer.cs:line 319
   at Microsoft.AspNetCore.SignalR.StackExchangeRedis.RedisHubLifetimeManager`1.PublishAsync(String channel, Byte[] payload) in /_/src/SignalR/server/StackExchangeRedis/src/RedisHubLifetimeManager.cs:line 320
   at Microsoft.AspNetCore.SignalR.StackExchangeRedis.RedisHubLifetimeManager`1.InvokeConnectionAsync[T](String connectionId, String methodName, Object[] args, CancellationToken cancellationToken) in /_/src/SignalR/server/StackExchangeRedis/src/RedisHubLifetimeManager.cs:line 422

```
</details>

## Logs

<details>

[vstest.log](https://github.com/dotnet/aspnetcore/files/8774970/vstest.log)

</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1781369&view=ms.vss-test-web.build-test-results-tab&runId=47743102&resultId=120362&paneView=debug

**Comment by BrennanConroy** [comment]
Has this failed since https://github.com/dotnet/aspnetcore/pull/41564 was merged?

**Comment by TanayParikh** [comment]
Nope. I'll close this out and keep an eye out for a newer failure.
