### ISSUE TITLE
Quarantine ClientAbortingConnectionImmediatelyIsNotLoggedHigherThanDebug

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#41850]
## Failing Test(s)

- Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests.ClientAbortingConnectionImmediatelyIsNotLoggedHigherThanDebug

## Error Message

```text
System.AggregateException : One or more hosted services failed to stop. (An error occurred while writing to logger(s). (Shutdown failure. Log Debug[NotAllConnectionsClosedGracefully]: Some connections failed to close gracefully during server shutdown. ))
---- System.AggregateException : An error occurred while writing to logger(s). (Shutdown failure. Log Debug[NotAllConnectionsClosedGracefully]: Some connections failed to close gracefully during server shutdown. )
-------- System.Exception : Shutdown failure. Log Debug[NotAllConnectionsClosedGracefully]: Some connections failed to close gracefully during server shutdown.



```

## Stacktrace

<details>

```text
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.TestServer.DisposeAsync() in /_/src/Servers/Kestrel/shared/test/TransportTestHelpers/TestServer.cs:line 148
   at Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests.ClientAbortingConnectionImmediatelyIsNotLoggedHigherThanDebug(ListenOptions listenOptions) in /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs:line 430
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at Microsoft.Extensions.Logging.Logger.ThrowLoggingError(List`1 exceptions)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerMessage.<>c__DisplayClass8_0.<Define>g__Log|0(ILogger logger, Exception exception)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelTrace.ConnectionsLog.NotAllConnectionsClosedGracefully(ILogger logger) in /_/src/Servers/Kestrel/Core/src/Microsoft.Extensions.Logging.Generators/Microsoft.Extensions.Logging.Generators.LoggerMessageGenerator/LoggerMessage.g.cs:line 157
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.<>c__DisplayClass14_0.<<StopTransportsAsync>g__StopTransportConnection|0>d.MoveNext() in /_/src/Servers/Kestrel/Core/src/Internal/Infrastructure/TransportManager.cs:line 110
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.StopTransportsAsync(List`1 transportsToStop, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/Infrastructure/TransportManager.cs:line 130
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StopAsync(CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs:line 281
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StopAsync(CancellationToken cancellationToken) in /_/src/Hosting/Hosting/src/GenericHost/GenericWebHostService.cs:line 175
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.Testing.TestApplicationErrorLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /_/src/Servers/Kestrel/shared/test/TestApplicationErrorLogger.cs:line 86
   at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|13_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)

```
</details>

## Logs

<details>

[ResponseTests_ClientAbortingConnectionImmediatelyIsNotLoggedHigherThanDebug-http_127.0.0.1_0.log](https://github.com/dotnet/aspnetcore/files/8774477/ResponseTests_ClientAbortingConnectionImmediatelyIsNotLoggedHigherThanDebug-http_127.0.0.1_0.log)
[ResponseTests_ClientAbortingConnectionImmediatelyIsNotLoggedHigherThanDebug-http_127.0.0.1_0.0.log](https://github.com/dotnet/aspnetcore/files/8774478/ResponseTests_ClientAbortingConnectionImmediatelyIsNotLoggedHigherThanDebug-http_127.0.0.1_0.0.log)

</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1789306&view=ms.vss-test-web.build-test-results-tab&runId=47864982&resultId=120859&paneView=debug

**Comment by adityamandaleeka** [comment]
Looks like this happened on another run a week ago with the same issue (also macOS). This is similar to other flakiness we've seen on socket tests on macOS. Let's add retries to this one.

**Comment by HaoK** [comment]
Added to retry in https://github.com/dotnet/aspnetcore/pull/42935

**Comment by HaoK** [comment]
Oops need to keep this open to track unquarantining after 30 days in retry

**Comment by HaoK** [comment]
Fixed by https://github.com/dotnet/aspnetcore/pull/43717
