### ISSUE TITLE
[.NET 7] Blazor debug host does fails to start

### ISSUE THREAD

**Issue by mrward** [dotnet/aspnetcore#41927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Unable to debug a Blazor Web Assembly project in VS Mac with .NET 7 installed.

Tried .NET 7 preview 4 and .NET 7 preview 6 (dotnet/installer).

With .NET 7 preview 4 the application output shows:

```
You must install or update .NET to run this application.

App: ~/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/7.0.0-preview.4.22251.1/tools/BlazorDebugProxy/BrowserDebugHost.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
.NET location: /usr/local/share/dotnet/

The following frameworks were found:
  7.0.0-preview.4.22229.4 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

```

Then this error repeated

```
[41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: No output has been recevied from the application.
         at Microsoft.AspNetCore.Builder.DebugProxyLauncher.LaunchAndGetUrl(IServiceProvider serviceProvider, String devToolsHost)
         at Microsoft.AspNetCore.Builder.WebAssemblyNetDebugProxyAppBuilderExtensions.<>c.<<UseWebAssemblyDebugging>b__0_1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

System.InvalidOperationException: No output has been recevied from the application.
   at Microsoft.AspNetCore.Builder.DebugProxyLauncher.LaunchAndGetUrl(IServiceProvider serviceProvider, String devToolsHost)
   at Microsoft.AspNetCore.Builder.WebAssemblyNetDebugProxyAppBuilderExtensions.<>c.<<UseWebAssemblyDebugging>b__0_1>d.MoveNext()

```

Workaround for .NET 7 preview 4 is to install a .NET 6 runtime.

With .NET 7 preview 6 (7.0.100-preview.6.22277.6 - taken from dotnet/installer), the BrowserDebugHost.dll now targets .NET 7 but fails to load when debugging in VS Mac with this error:

```
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.5.22272.3/System.IO.Pipes.dll'. Cannot find or open the PDB file.
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Serilog.Extensions.Logging.File, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'. The system cannot find the file specified.

   at Microsoft.WebAssembly.Diagnostics.Program.<>c__DisplayClass0_0.<Main>b__0(ILoggingBuilder builder)
File name: 'Serilog.Extensions.Logging.File, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'
   at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection services, Action`1 configure)
   at Microsoft.Extensions.Logging.LoggerFactory.Create(Action`1 configure)
   at Microsoft.WebAssembly.Diagnostics.Program.Main(String[] args)
   at Microsoft.WebAssembly.Diagnostics.Program.<Main>(String[] args)

Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.5.22272.3/System.Diagnostics.StackTrace.dll'. Cannot find or open the PDB file.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.5.22272.3/System.Reflection.Metadata.dll'. Cannot find or open the PDB file.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.0-preview.5.22272.3/System.Collections.Immutable.dll'. Cannot find or open the PDB file.
[41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      System.InvalidOperationException: No output has been recevied from the application.
         at Microsoft.AspNetCore.Builder.DebugProxyLauncher.LaunchAndGetUrl(IServiceProvider serviceProvider, String devToolsHost)
      An unhandled exception has occurred while executing the request.
         at Microsoft.AspNetCore.Builder.WebAssemblyNetDebugProxyAppBuilderExtensions.<>c.<<UseWebAssemblyDebugging>b__0_1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

System.InvalidOperationException: No output has been recevied from the application.
   at Microsoft.AspNetCore.Builder.DebugProxyLauncher.LaunchAndGetUrl(IServiceProvider serviceProvider, String devToolsHost)
   at Microsoft.AspNetCore.Builder.WebAssemblyNetDebugProxyAppBuilderExtensions.<>c.<<UseWebAssemblyDebugging>b__0_1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Same error `Could not load file or assembly 'Serilog.Extensions.Logging.File, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'.` can be reproduced by directly running the blazor debug host.

```
 dotnet ~/.nuget/packages/microsoft.aspnetcore.components.webassembly.devserver/7.0.0-preview.5.22273.7/tools/BlazorDebugProxy/BrowserDebugHost.dll
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Serilog.Extensions.Logging.File, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'. The system cannot find the file specified.

File name: 'Serilog.Extensions.Logging.File, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'
   at Microsoft.WebAssembly.Diagnostics.Program.<>c__DisplayClass0_0.<Main>b__0(ILoggingBuilder builder)
   at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection services, Action`1 configure)
   at Microsoft.Extensions.Logging.LoggerFactory.Create(Action`1 configure)
   at Microsoft.WebAssembly.Diagnostics.Program.Main(String[] args)
   at Microsoft.WebAssembly.Diagnostics.Program.<Main>(String[] args)
```

### Expected Behavior

Can debug Blazor Web Assembly projects in Visual Studio for Mac 17.3

### Steps To Reproduce

- Create a new Blazor Web Assembly project in VS Mac 17.3
- Select Chrome as the browser
- Debug - Start Debugging
- Application does not load in the browser
- Errors reported in Applicatin output

### Exceptions (if any)

```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Serilog.Extensions.Logging.File, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'. The system cannot find the file specified.

   at Microsoft.WebAssembly.Diagnostics.Program.<>c__DisplayClass0_0.<Main>b__0(ILoggingBuilder builder)
File name: 'Serilog.Extensions.Logging.File, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'
   at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection services, Action`1 configure)
   at Microsoft.Extensions.Logging.LoggerFactory.Create(Action`1 configure)
   at Microsoft.WebAssembly.Diagnostics.Program.Main(String[] args)
   at Microsoft.WebAssembly.Diagnostics.Program.<Main>(String[] args)
```

### .NET Version

7.0.100-preview.6.22277.6

### Anything else?

VS Mac 17.3.0.765

dotnet --info
```
.NET SDK:
 Version:   7.0.100-preview.6.22277.6
 Commit:    750e9fe9ec

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.6
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.100-preview.6.22277.6/

global.json file:
  Not found

Host:
  Version:      7.0.0-preview.5.22272.3
  Architecture: x64
  Commit:       0864cc5539

.NET SDKs installed:
  7.0.100-preview.6.22277.6 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0-preview.5.22273.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0-preview.5.22272.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by javiercn** [comment]
@mrward thanks for reporting this.

@mkArtakMSFT can you get someone to take a quick look at this?

**Comment by TanayParikh** [comment]
Thanks for the report @mrward. Could you please confirm whether you're facing this issue with VSCode for Mac as well? If not, that may be a workaround this issue in the interim.

**Comment by mrward** [comment]
@TanayParikh I work on the VS Mac team which is why I reported this :) As far as I am aware VS Code uses the same debugger that VS Mac does, at least it did when Blazor debugger was implemented.

I gave VS Code a quick try but I could not get a new Blazor WASM app to start with .NET 7 p4 or .NET 7 p5, no useful output from VS Code that I could see and I cannot remember how to enable debugger logging.

**Comment by mrward** [comment]
@javiercn I believe this has been fixed in .NET 7 preview 5. There is this runtime bug which is should fix the serilog assembly being used - https://github.com/dotnet/runtime/pull/70383/

**Comment by TanayParikh** [comment]
Thanks for the update @mrward. I'm going to close out this issue in that case, feel free to re-open if necessary.

**Comment by attilavlacsil** [comment]
@mrward Unfortunately [#70383](https://github.com/dotnet/runtime/pull/70383) didn't get into the [.NET 7.0 Preview 5](https://github.com/dotnet/runtime/releases/tag/v7.0.0-preview.5.22301.12) release, making the vanilla blazorwasm project broke.

**Comment by mrward** [comment]
@attilavlacsil Yes, unfortunately the change was too late to be included in .NET 7 preview 5. No workaround available currently apart from using .NET 7 preview 6.

**Comment by mrward** [comment]
@attilavlacsil There is a workaround documented in the [known issues for .NET 7](https://github.com/dotnet/core/blob/ab88f76baefeb635719967d85ccc8de709e2ef07/release-notes/7.0/known-issues.md#unable-to-debug-a-blazor-webassembly-app)
