### ISSUE TITLE
At random intervals the application fails to set RouteValues

### ISSUE THREAD

**Issue by okolvik-avento** [dotnet/aspnetcore#41924]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

At random intervals (6-24 hours) the application fails to set RouteValues, which raises an exception.
Parallel or subsequent requests completes successfully, it only happens once in a blue moon.

Technical details:
.NET 6.0.5
Windows Server 2019, IIS 10
YARP (Reverse Proxy) 1.1.0
Application Insights 2.20.0

The bug happened with Ocelot as well as YARP, so i don't think either of them is the reason. 

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Http.DefaultHttpRequest.set_RouteValues(RouteValueDictionary value)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
```

appsettings.json
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Warning",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Warning"
    }
  },
  "Serilog": {
    "Using": [ "Serilog.Sinks.File", "Serilog.Sinks.ApplicationInsights" ],
    "MinimumLevel": "Warning",
    "WriteTo": [
      {
        "Name": "Async",
        "Args": {
          "configure": [
            {
              "Name": "File",
              "Args": {
                "path": "Logs/serilog.txt",
                "rollingInterval": "Day",
                "rollOnFileSizeLimit": true,
                "retainedFileCountLimit": 20,
                "fileSizeLimitBytes": 104857600
              }
            }
          ]
        }
      },
      {
        "Name": "ApplicationInsights",
        "Args": {
          "InstrumentationKey": "xxx",
          "restrictedToMinimumLevel": "Information",
          "telemetryConverter": "Serilog.Sinks.ApplicationInsights.Sinks.ApplicationInsights.TelemetryConverters.TraceTelemetryConverter, Serilog.Sinks.ApplicationInsights"
        }
      }
    ],
    "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ]
  },
  "AllowedHosts": "*",
  "ConnectionStrings": {
    "CmsAdmin": "Data Source=xxx;User ID=xxx;Password=xxx;Initial Catalog=xxx;MultipleActiveResultSets=True"
  },
  "InternalIPWhiteList": [
    "10.0.0.0/8",
    "172.16.0.0/12",
    "192.168.0.0/16",
    "::1",
    "127.0.0.1"
  ],
  "ApplicationInsights": {
    "ConnectionString": "xxx",
    "DeveloperMode": false,
    "EnableRequestTrackingTelemetryModule": true,
    "EnableAdaptiveSampling": true,
    "EnableActiveTelemetryConfigurationSetup": true
  },
  "ReverseProxy": {
    "Routes": {
      "route1": {
        "ClusterId": "cluster1",
        "AuthorizationPolicy": "default",
        "Match": {
          "Path": "{**catch-all}"
        },
        "AllowAnonymous": false
      }
    },
    "Clusters": {
      "cluster1": {
        "Destinations": {
          "destination1": {
            "Address": "http://192.168.197.13"
          },
          "destination2": {
            "Address": "http://192.168.197.14"
          }
        }
      }
    },
    "LoadBalancingPolicy": "PowerOfTwoChoices"
  }
}
```

Startup.cs
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using xx.Api.Gateway.Services;
using xx.Api.Handlers;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.HttpOverrides;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Hosting.Internal;
using Microsoft.Extensions.Logging;
using Serilog;
using Yarp.ReverseProxy.Transforms;

namespace xx.Api.Gateway
{
    public class Startup
    {
        public Startup(IConfiguration configuration, IWebHostEnvironment env)
        {
            Configuration = configuration;
            _env = env;
        }

        public IConfiguration Configuration { get; }

        private readonly IWebHostEnvironment _env;

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddCors();
            services.AddOptions();
            services.AddMemoryCache();
            services.AddHttpContextAccessor();
            
            // configure basic authentication 
            services.AddAuthentication("BasicAuthentication")
                .AddScheme<AuthenticationSchemeOptions, BasicAuthenticationHandler>("BasicAuthentication", null);

            // configure DI for application services
            services.AddScoped<IAccountService, AccountService>();
            services.AddApplicationInsightsTelemetry();
            services.AddSingleton<IPService>();

            var proxyBuilder = services.AddReverseProxy();
            // Initialize the reverse proxy from the "ReverseProxy" section of configuration
            proxyBuilder.LoadFromConfig(Configuration.GetSection("ReverseProxy"));
            proxyBuilder.AddTransforms(builderContext =>
            {
                // Conditionally add a transform for routes that require auth.
                if (!string.IsNullOrEmpty(builderContext.Route.AuthorizationPolicy))
                {
                    builderContext.AddRequestTransform(transformContext =>
                    {
                        var user = transformContext.HttpContext.User;
                        var version = user.Claims.FirstOrDefault(x => x.Type.Equals("ApiVersion"))?.Value;
                        var hostname = user.Claims.FirstOrDefault(x => x.Type.Equals("ApiHostname"))?.Value;
                        var urlVersion = user.Claims.FirstOrDefault(x => x.Type.Equals("ApiUrlVersion"))?.Value;

                        var environment = _env.EnvironmentName == "Production" ? "" : "-development";
                        if (!string.IsNullOrEmpty(version) && !string.IsNullOrEmpty(hostname) && !string.IsNullOrEmpty(urlVersion))
                        {
                            transformContext.ProxyRequest.Headers.Remove("X-Api-Version");
                            transformContext.ProxyRequest.Headers.Remove("X-Api-Hostname");
                            transformContext.ProxyRequest.Headers.Add("X-Api-Version", version);
                            transformContext.ProxyRequest.Headers.Add("X-Api-Hostname", hostname);
                            transformContext.Path = string.Format("/v{0}{1}{2}", urlVersion, environment, transformContext.Path);
                        }

                        return default;
                    });
                }
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            // global cors policy
            app.UseCors(x => x
                .AllowAnyOrigin()
                .AllowAnyMethod()
                .AllowAnyHeader());

            //app.UseHttpsRedirection();

            app.UseAuthentication();         
            app.UseRouting();
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapReverseProxy();
            });

        }
    }
}

```
BasicAuthenticationHandler:

```
using System;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.Extensions.Options;
using xx.Api.Gateway.Entities;
using xx.Api.Gateway.Services;
using Microsoft.AspNetCore.HttpOverrides;
using Microsoft.Extensions.Logging;
using Microsoft.ApplicationInsights;

namespace xx.Api.Handlers
{
    public class BasicAuthenticationHandler : AuthenticationHandler<AuthenticationSchemeOptions>
    {
        private readonly IAccountService _userService;
        private readonly IPService _ipService;
        private readonly TelemetryClient _telemetry;

        public BasicAuthenticationHandler(
            IOptionsMonitor<AuthenticationSchemeOptions> options,
            ILoggerFactory logger,
            UrlEncoder encoder,
            ISystemClock clock,
            IAccountService userService,
            IPService ipService,
            TelemetryClient telemetry)
            : base(options, logger, encoder, clock)
        {
            _userService = userService;
            _ipService = ipService;
            _telemetry = telemetry;
        }

        protected override async Task<AuthenticateResult> HandleAuthenticateAsync()
        {
            var remoteIp = Request.HttpContext.Connection.RemoteIpAddress;
            Logger.LogInformation(remoteIp != null ? "Remote ip is: " + remoteIp.ToString() : "Remote ip is null");

            if (Request.Headers.ContainsKey("Authorization"))
            {
                Logger.LogDebug("Logging in with autorization");
                return await AuthenticateWithAuthorization();
            }
            
            if(remoteIp != null && _ipService.IsIPWhiteListed(remoteIp))
            {
                Logger.LogDebug("Logging in with hostname");
                return await AuthenticateWithApiHost();
            }

            return AuthenticateResult.Fail("Unknown authentication method.");
        }

        private async Task<AuthenticateResult> AuthenticateWithApiHost()
        {
            Account account = null;
            try
            {
                string apiHost;

                if(Request.Headers.ContainsKey("X-Api-Hostname"))
                {
                    apiHost = Request.Headers["X-Api-Hostname"];
                    Logger.LogInformation("X-Api-Hostname " + apiHost);
                }
                else
                {
                    var hosts = Request.Host.Host.Split(".");
                    if (hosts.Length < 3)
                    {
                        return AuthenticateResult.Fail("No hostname");
                    }

                    apiHost = hosts[0];
                    Logger.LogInformation("Parsed hostname " + apiHost);
                }

                account = await _userService.AuthenticateHost(apiHost);
            }
            catch(Exception ex)
            {
                _telemetry.TrackException(ex);
                return AuthenticateResult.Fail("Invalid hostname");
            }

            if (account == null)
                return AuthenticateResult.Fail("Invalid hostname");

            return CreateTicket(account);
        }

        protected async Task<AuthenticateResult> AuthenticateWithAuthorization()
        {
            Account account = null;
            try
            {
                var authHeader = AuthenticationHeaderValue.Parse(Request.Headers["Authorization"]);
                var credentialBytes = Convert.FromBase64String(authHeader.Parameter);
                var credentials = Encoding.UTF8.GetString(credentialBytes).Split(new[] { ':' }, 2);
                var username = credentials[0];
                var password = credentials[1];
                if(Request.Headers.ContainsKey("X-Api-Verify-Token"))
                {
                    account = await _userService.AuthenticateAccessToken(username, password);
                }
                else
                {
                    account = await _userService.Authenticate(username, password);
                }
                
            }
            catch(Exception ex)
            {
                _telemetry.TrackException(ex);
                return AuthenticateResult.Fail("Invalid Authorization Header");
            }

            if (account == null)
                return AuthenticateResult.Fail("Invalid Username or Password");

            return CreateTicket(account);
        }

        protected AuthenticateResult CreateTicket(Account account)
        {
            Version apiVersion = new Version(1,0);
            int urlVersion = 2;
            if(Request.Headers.ContainsKey("X-Api-Version"))
            {
                Version v;
                if(Version.TryParse(Request.Headers["X-Api-Version"].ToString(), out v))
                {
                    urlVersion = v.Major > 1 ? v.Major : 2;
                    apiVersion = v;
                }
            }
            Logger.LogInformation(string.Format("Api hostname: {0}, Api version: {1}, Url version: {2}", account.ApiHost, apiVersion, urlVersion));

            var name = string.IsNullOrEmpty(account.Username) ? account.ApiHost : account.Username;

            var claims = new[] {
                new Claim(ClaimTypes.NameIdentifier, account.Id.ToString()),
                new Claim(ClaimTypes.Name, name),
                new Claim("ApiHostname", account.ApiHost),
                new Claim("ApiUrlVersion", urlVersion.ToString()),
                new Claim("ApiVersion", apiVersion.ToString())
            };
            var identity = new ClaimsIdentity(claims, Scheme.Name);
            var principal = new ClaimsPrincipal(identity);
            var ticket = new AuthenticationTicket(principal, Scheme.Name);

            return AuthenticateResult.Success(ticket);
        }
    }
}
```

### Expected Behavior

No exception

### Steps To Reproduce

Sadly i can't reproduce it, since i don't know what's actually wrong.

### Exceptions (if any)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Http.DefaultHttpRequest.set_RouteValues(RouteValueDictionary value)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()

### .NET Version

6.0.5

### Anything else?

.NET 6.0.5
Windows Server 2019, IIS 10
YARP (Reverse Proxy) 1.1.0
Application Insights 2.20.0

**Comment by javiercn** [comment]
@Tratcher My understanding is that DefaultHttpRequest.RouteValues is failing (somehow). Do you know what can be the case for that?

**Comment by okolvik-avento** [comment]
@javiercn I should note that i have yet to get the error in local development with IIS Express. I've only ever seen it on IIS.

**Comment by okolvik-avento** [comment]
@javiercn Just noticed that i had not set the application pool to "No Managed Code", maybe that is the issue? I will see if it fixes the problem

**Comment by davidfowl** [comment]
Issues like these are always hard to track down. Does it repro if you remove application insights (I assume you're using it)?

**Comment by okolvik-avento** [comment]
@davidfowl Yeah i use Application Insights. I've removed service.AddApplicationInsightsTelemetry() now and removed all traces of the telemetry client. Lets see how it goes

**Comment by okolvik-avento** [comment]
@davidfowl No errors after i removed it. So it seems Application Insights is the issue here. I think this is related [1524](https://github.com/nreco/logging/issues/25)

**Comment by davidfowl** [comment]
Hmmm, I expected this but the callstack does look different. I would be great a capture a process dump when this happens...

**Comment by okolvik-avento** [comment]
@davidfowl Here is the full callstack:
I have a minidump also if you have a place i can send it
```
Microsoft.AspNetCore.Http.DefaultHttpRequest.set_RouteValues(Microsoft.AspNetCore.Routing.RouteValueDictionary)+97 
Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync()+810 
Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke()+a4 
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+d__6.MoveNext()+6a6 
System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)+77 
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+d__6, Microsoft.AspNetCore.Authentication]].MoveNext(System.Threading.Thread)+cd 
System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)+f4 
System.Threading.Tasks.Task.RunContinuations(System.Object)+7c 
System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib]].TrySetResult(System.__Canon)+81 
Microsoft.AspNetCore.Authentication.AuthenticationService+d__14.MoveNext()+59d 
System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)+77 
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib],[Microsoft.AspNetCore.Authentication.AuthenticationService+d__14, Microsoft.AspNetCore.Authentication.Core]].MoveNext(System.Threading.Thread)+f4 
System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)+f4 
System.Threading.Tasks.Task.RunContinuations(System.Object)+7c 
System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib]].TrySetResult(System.__Canon)+81 
Microsoft.AspNetCore.Authentication.AuthenticationHandler`1+d__48[[System.__Canon, System.Private.CoreLib]].MoveNext()+307 
System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)+77 
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib],[Microsoft.AspNetCore.Authentication.AuthenticationHandler`1+d__48[[System.__Canon, System.Private.CoreLib]], Microsoft.AspNetCore.Authentication]].MoveNext(System.Threading.Thread)+119 
System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)+f4 
System.Threading.Tasks.Task.RunContinuations(System.Object)+7c 
System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib]].TrySetResult(System.__Canon)+81 
Atom.Api.Handlers.BasicAuthenticationHandler+d__3.MoveNext()+411 
System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)+77 
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib],[Atom.Api.Handlers.BasicAuthenticationHandler+d__3, Atom.Api.Gateway]].MoveNext(System.Threading.Thread)+f4 
System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)+f4 
System.Threading.Tasks.Task.RunContinuations(System.Object)+7c 
System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib]].TrySetResult(System.__Canon)+81 
Atom.Api.Handlers.BasicAuthenticationHandler+d__4.MoveNext()+431 
System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)+77 
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib],[Atom.Api.Handlers.BasicAuthenticationHandler+d__4, Atom.Api.Gateway]].MoveNext(System.Threading.Thread)+f4 
System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)+f4 
System.Threading.Tasks.Task.RunContinuations(System.Object)+7c 
System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib]].TrySetResult(System.__Canon)+81 
Atom.Api.Gateway.Services.AccountService+d__5.MoveNext()+207 
System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)+77 
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib],[Atom.Api.Gateway.Services.AccountService+d__5, Atom.Api.Gateway]].MoveNext(System.Threading.Thread)+f4 
System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)+f4 
System.Threading.Tasks.Task.RunContinuations(System.Object)+7c 
System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib]].TrySetResult(System.__Canon)+81 
Atom.Api.Gateway.Services.AccountService+d__7.MoveNext()+3e3 
System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)+77 
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib],[Atom.Api.Gateway.Services.AccountService+d__7, Atom.Api.Gateway]].MoveNext(System.Threading.Thread)+f4 
System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)+f4 
System.Threading.Tasks.Task.RunContinuations(System.Object)+7c 
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib]].SetExistingTaskResult(System.Threading.Tasks.Task`1, System.__Canon)+a3 
Dapper.SqlMapper+d__34`1[[System.__Canon, System.Private.CoreLib]].MoveNext()+c98 
System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)+77 
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.__Canon, System.Private.CoreLib],[Dapper.SqlMapper+d__34`1[[System.__Canon, System.Private.CoreLib]], Dapper]].MoveNext(System.Threading.Thread)+119 
System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Runtime.CompilerServices.IAsyncStateMachineBox, Boolean)+f4 
System.Threading.Tasks.Task.RunContinuations(System.Object)+7c 
System.Threading.Tasks.Task.FinishSlow(Boolean)+27 
System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)+13d 
System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(System.Threading.Tasks.Task, Boolean)+8c 
System.Threading.Tasks.TaskContinuation.InlineIfPossibleOrElseQueue(System.Threading.Tasks.Task, Boolean)+a3 
System.Threading.Tasks.ContinueWithTaskContinuation.Run(System.Threading.Tasks.Task, Boolean)+e8 
System.Threading.Tasks.Task.RunContinuations(System.Object)+36c 
System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib]].TrySetResult(System.__Canon)+81 
System.Threading.Tasks.UnwrapPromise`1[[System.__Canon, System.Private.CoreLib]].TrySetFromTask(System.Threading.Tasks.Task, Boolean)+c5 
System.Threading.Tasks.UnwrapPromise`1[[System.__Canon, System.Private.CoreLib]].ProcessInnerTask(System.Threading.Tasks.Task)+2a 
System.Threading.Tasks.Task.RunContinuations(System.Object)+352 
System.Threading.Tasks.Task.FinishSlow(Boolean)+27 
System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)+13d 
System.Threading.ThreadPoolWorkQueue.Dispatch()+1fa 
System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()+1f2 
[[DebuggerU2MCatchHandlerFrame]] 

```

**Comment by okolvik-avento** [comment]
@davidfowl And one for get_Cookies

```
Microsoft.AspNetCore.Http.DefaultHttpRequest.get_Cookies()+8f 
Microsoft.ApplicationInsights.AspNetCore.TelemetryInitializers.WebSessionTelemetryInitializer.UpdateRequestTelemetryFromPlatformContext(Microsoft.ApplicationInsights.DataContracts.RequestTelemetry, Microsoft.AspNetCore.Http.HttpContext)+3c 
Microsoft.ApplicationInsights.AspNetCore.TelemetryInitializers.WebSessionTelemetryInitializer.OnInitializeTelemetry(Microsoft.AspNetCore.Http.HttpContext, Microsoft.ApplicationInsights.DataContracts.RequestTelemetry, Microsoft.ApplicationInsights.Channel.ITelemetry)+c4 
Microsoft.ApplicationInsights.AspNetCore.TelemetryInitializers.TelemetryInitializerBase.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)+fa 
Microsoft.ApplicationInsights.TelemetryClient.Initialize(Microsoft.ApplicationInsights.Channel.ITelemetry)+2f9 
Microsoft.ApplicationInsights.TelemetryClient.Track(Microsoft.ApplicationInsights.Channel.ITelemetry)+35 
Microsoft.ApplicationInsights.DependencyCollector.Implementation.SqlClientDiagnostics.SqlClientDiagnosticSourceListener.AfterExecuteHelper(System.Collections.Generic.KeyValuePair`2, Microsoft.ApplicationInsights.Common.PropertyFetcher, Microsoft.ApplicationInsights.Common.PropertyFetcher, Microsoft.ApplicationInsights.Common.PropertyFetcher)+18b 
Microsoft.ApplicationInsights.DependencyCollector.Implementation.SqlClientDiagnostics.SqlClientDiagnosticSourceListener.System.IObserver>.OnNext(System.Collections.Generic.KeyValuePair`2)+48f 
System.Diagnostics.DiagnosticListener.Write(System.String, System.Object)+45 
System.Data.SqlClient.SqlClientDiagnosticListenerExtensions.WriteCommandAfter(System.Diagnostics.DiagnosticListener, System.Guid, System.Data.SqlClient.SqlCommand, System.String)+1fc 
System.Data.SqlClient.SqlCommand+<>c__DisplayClass130_0.b__2(System.Threading.Tasks.Task`1)+2fc 
System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)+4b 
System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)+b6 
System.Threading.ThreadPoolWorkQueue.Dispatch()+1fa 
System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()+1f2 

```

**Comment by davidfowl** [comment]
[This stack](https://github.com/dotnet/aspnetcore/issues/41924#issuecomment-1142595606) is the app insights ones that I would expect to fail.

**Comment by okolvik-avento** [comment]
> [This stack](https://github.com/dotnet/aspnetcore/issues/41924#issuecomment-1142595606) is the app insights ones that I would expect to fail.

Ok, i'll keep monitoring the exceptions. Tell me if you want a minidump

**Comment by davidfowl** [comment]
Did you capture one?

**Comment by okolvik-avento** [comment]
> Did you capture one?

Yeah i'm running the debug diagnostic tool on the application pool

**Comment by okolvik-avento** [comment]
Note that the set_RouteValues one also only happens with AI activated

**Comment by okolvik-avento** [comment]
@davidfowl https://avento365-my.sharepoint.com/:f:/g/personal/ole_kolvik_avento_no/EnPB1kXz48RJjju2c45gqQwB-gpS6lyIKiYu3JsaG7v5_A?e=HeWMXw

1 for get_Cookies and 1 for set_RouteValues.
I can see that Application Insights is running in another thread on the set_RouteValues one, it might access HttpContext causing the issue?

Btw, the pbd for Application Insights isn't on the microsoft symbol servers or on the nuget ones. Had to grab it manually.

**Comment by okolvik-avento** [comment]
I do have full userdumps as well, but i'm not sharing them publicly

**Comment by okolvik-avento** [comment]
None of these errors happen on Debug builds, could it be something wrong with optimization for Release builds?

**Comment by okolvik-avento** [comment]
Release without services.AddApplicationInsightsTelemetry();
```
PS C:\Users\ole.kolvik\Downloads\apache-jmeter-5.4.3\bin> .\jmeter.bat -n -t .\gateway-dev.test
Creating summariser <summary>
Created the tree successfully using .\gateway-dev.test
Starting standalone test @ Wed Jun 01 17:50:55 CEST 2022 (1654098655542)
Waiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445
summary +    180 in 00:00:04 =   42.5/s Avg:    15 Min:    11 Max:    68 Err:     0 (0.00%) Active: 6 Started: 6 Finished: 0
summary +   1417 in 00:00:30 =   47.3/s Avg:    17 Min:    11 Max:    99 Err:     0 (0.00%) Active: 6 Started: 6 Finished: 0
summary =   1597 in 00:00:34 =   46.7/s Avg:    17 Min:    11 Max:    99 Err:     0 (0.00%)
summary +   1432 in 00:00:30 =   47.6/s Avg:    16 Min:    11 Max:   110 Err:     0 (0.00%) Active: 6 Started: 6 Finished: 0
summary =   3029 in 00:01:04 =   47.1/s Avg:    16 Min:    11 Max:   110 Err:     0 (0.00%)
summary +   1419 in 00:00:30 =   47.4/s Avg:    17 Min:    11 Max:    78 Err:     0 (0.00%) Active: 6 Started: 6 Finished: 0
summary =   4448 in 00:01:34 =   47.2/s Avg:    17 Min:    11 Max:   110 Err:     0 (0.00%)
summary +   1408 in 00:00:30 =   46.9/s Avg:    17 Min:    11 Max:   628 Err:     0 (0.00%) Active: 6 Started: 6 Finished: 0
summary =   5856 in 00:02:04 =   47.1/s Avg:    17 Min:    11 Max:   628 Err:     0 (0.00%)
summary +   1427 in 00:00:30 =   47.6/s Avg:    17 Min:    11 Max:   128 Err:     0 (0.00%) Active: 6 Started: 6 Finished: 0
summary =   7283 in 00:02:34 =   47.2/s Avg:    17 Min:    11 Max:   628 Err:     0 (0.00%)
summary +   1438 in 00:00:30 =   47.9/s Avg:    15 Min:    10 Max:   208 Err:     0 (0.00%) Active: 6 Started: 6 Finished: 0
summary =   8721 in 00:03:04 =   47.3/s Avg:    16 Min:    10 Max:   628 Err:     0 (0.00%)
Terminate batch job (Y/N)? y
PS C:\Users\ole.kolvik\Downloads\apache-jmeter-5.4.3\bin>
```

**Comment by davidfowl** [comment]
@okolvik-avento can you get me access to the dump. My email is david.fowler at microsoft

**Comment by okolvik-avento** [comment]
@davidfowl sent you an invite to a onedrive folder

**Comment by davidfowl** [comment]
My current theory is that there's concurrent access to the HttpContext causing this corruption.

**Comment by okolvik-avento** [comment]
@davidfowl i suspect it's the BasicAuthenticationHandler. It seems to be accessing a lot of headers in various async functions. That might be it? I'll try moving every header in the initial authentication function

**Comment by Tratcher** [comment]
BasicAuthenticationHandler looks fine. Async functions are ok so long as you `await` them so the flow stays linear.

**Comment by davidfowl** [comment]
I see why it happens now. It's because the basic auth middleware calls into the telemetry client. That's why it fails at routing. I'm going to see if we can improve these issues but one short term fix would be to remove the telemetry initializer that read the http context.

**Comment by okolvik-avento** [comment]
@davidfowl in the updated code that the dumps are from there is no telemetry in BasicAuth (remember i removed everything about the telemetry client https://github.com/dotnet/aspnetcore/issues/41924#issuecomment-1141487956)everything to use _logger.LogError where _logger is Microsoft.Extensions.Logging.ILoggerFactory from which is the standard logger in AuthenticationHandler

**Comment by davidfowl** [comment]
Are you saying it still happens when you remove application insights?

**Comment by davidfowl** [comment]
Thanks to these dumps I can visually see the race condition 😄:

<img width="977" alt="hang" src="https://user-images.githubusercontent.com/95136/171988908-fa87c843-0338-400f-bb7e-6ccd58224442.png">

When the exception happens for cookies, there's an async Task continuation that is running and writing to app insights (where the null ref happens). Concurrently the auth middleware is currently running. Where are your SQL queries? In the user service?

**Comment by okolvik-avento** [comment]
@davidfowl No, that's not what i mean. It only happens when i have services.AddApplicationInsightsTelemetry(), even when i don't actually use the telemetry client anywhere.

This goes for both the get_Cookies and set_RouteValues

I'm sending you an invite to the repo with the code that created the dumps.

**Comment by davidfowl** [comment]
Got it, yea it seems like something is making SQL queries on another thread that is running concurrently with the request causing the race.

**Comment by davidfowl** [comment]
I didn't even realize the problem was right in front of my eyes. @okolvik-avento Thanks for the dumps, the issue in the in SqlCommand implementation [here](https://github.com/dotnet/SqlClient/blob/2cfac4d415990e8618b0c3e26d426ce9fe4665dc/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlCommand.cs#L2566)

When you run an async sql command, even when you await it properly, the implementation fires the diagnostics listener callback after running the user's continuation. This allows the telemetry initializers in app insights to run concurrently with the request, causing this chaos. 

This isn't an app insights issue (this time 😄), it turns out.

**Comment by okolvik-avento** [comment]
@davidfowl I'm replacing System.Data.SqlClient with Microsoft.Data.SqlClient for more testing.
I don't see SqlClient in the stack trace for set_RouteValues (the original exception)

**Comment by okolvik-avento** [comment]
First thing i see is a huge performance increase. While tests with System.Data.SqlClient had 20ms responsetime with dips up to 100ms, i now see sub 5ms responsetimes with dips up to 20ms

**Comment by okolvik-avento** [comment]
@davidfowl Sadly i'm still seeing the get_Cookies exception

**Comment by davidfowl** [comment]
Yes, the problematic code exists in both implementations 😄, see https://github.com/dotnet/SqlClient/issues/1634

**Comment by ajcvickers** [comment]
@David-Engel owns SqlClient.

**Comment by davidfowl** [comment]
PR open here https://github.com/dotnet/SqlClient/pull/1637

**Comment by davidfowl** [comment]
This is fixed!

**Comment by okolvik-avento** [comment]
Thank you for the quick response @davidfowl!

**Comment by davidfowl** [comment]
Thanks for the great debugging and dumps @okolvik-avento !
