### ISSUE TITLE
QUESTION:  Error: Connection disconnected with error 'Error: WebSocket closed with status code: 1005 (no reason given).'

### ISSUE THREAD

**Issue by gtejeda** [dotnet/aspnetcore#41947]
I've been trying to overcome this issue for the past few months with several degrees of failure/success, but it keeps on giving me a headache and my users are increasingly reporting the application "stops working".

These are the errors:

Error: Connection disconnected with error 'Error: WebSocket closed with status code: 1005 (no reason given).'

Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
    at bt.send (blazor.server.js:1:51876)
    at kt._sendMessage (blazor.server.js:1:68532)
    at kt._sendWithProtocol (blazor.server.js:1:68573)
    at kt.send (blazor.server.js:1:68681)
    at Object.beginInvokeDotNetFromJS (blazor.server.js:1:131175)
    at w (blazor.server.js:1:2164)
    at C.invokeMethodAsync (blazor.server.js:1:4014)
    at TChecker (dashboard:395:32)

I don't know, and can't figure out why the websockets die, at random times, however for now It would be okay for me to simply reload the page when it's detected:

I implemented many possible reloads, like:
    //var webSocket = new WebSocket("wss:// URL here/_blazor");
      //webSocket.onclose = function (event) {
      //    if (event.code == 1005 || event.code == 1006)
      //    {
      //        async function waitAndReload() {
      //            await fetch('');
      //            location.reload(true);
      //        }
      //        waitAndReload();
      //    }
      //};

**Comment by gtejeda** [comment]
Also subscribing to the closed event:
_hubConnection = new HubConnectionBuilder().WithUrl($"{nav.BaseUri}messageshub").WithAutomaticReconnect().Build();
_hubConnection.Closed += _hubConnection_Closed;

but in this case the handler is never called

**Comment by gtejeda** [comment]
Can anybody recommend a sure way to reload the page on errors 1005 or 1006?
thanks in advance

**Comment by javiercn** [comment]
@gtejeda particularly 

```html
<body>
    ...

    <script src="_framework/blazor.server.js" autostart="false"></script>
    <script>
      Blazor.start({
        reconnectionHandler: {
          onConnectionDown: (options, error) => console.error(error),
          onConnectionUp: () => console.log("Up, up, and away!")
        }
      });
    </script>
</body>
```

Should give you a way to get a notification on when the connection is down/up. If an exception occurs, you could setup a promise and await it to retry after the connection is up.

**Comment by gtejeda** [comment]
WOW @javiercn, thanks for your suggestions will try it right away

**Comment by gtejeda** [comment]
@javiercn It appears that that I can't subscribe like this because Blazor already had started at that moment. :(

<img width="339" alt="image" src="https://user-images.githubusercontent.com/199282/171424326-3c125768-c46f-4040-9bf4-f9126aea1c2e.png">

**Comment by javiercn** [comment]
@gtejeda you need to set `autostart=false` in the script above

**Comment by gtejeda** [comment]
Oops, 
IT WORKS @javiercn, you're a life saver, thanks!!!
