### ISSUE TITLE
Blazor Server Side: Implement a simple way to dispose of components

### ISSUE THREAD

**Issue by TheRealRolandDeschain** [dotnet/aspnetcore#42015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

This issue/request is basically a follow-up on https://github.com/dotnet/aspnetcore/issues/29886. 

I have a page in my component, which has a file drop area, implemented in javascript. Interaction is done via `JSRuntime`,  here are the relevant functions: 

```
        private IJSObjectReference _jsFileDropperObject;

        ...
        
        [Inject]
        protected IJSRuntime JSRuntime { get; private set; }

        ...
        
        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (firstRender)
            {
                var authState = await AuthenticationStateTask;
                var user = authState.User;

                if (user.Identity.IsAuthenticated)
                {
                    if (await ViewModel.LoadSelectedDatabase(DatasetID))
                    {
                        _jsFileDropperObject = await JSRuntime.InvokeAsync<IJSObjectReference>("import", "./js/FileDropper.js");
                        await InitializeDropZone();
                    }
                    else
                    {
                        await JSRuntime.InvokeVoidAsync("alert", "The selected Dataset does not exist!");
                        NavigationManager.NavigateTo($"datasets");
                    }
                }
            }

            await base.OnAfterRenderAsync(firstRender);

            return;
        }

        ...

        public async ValueTask DisposeAsync()
        {
            ViewModel.PropertyChanged -= OnPropertyChangedHandler;
            GC.SuppressFinalize(this);

            if(_jsFileDropperObject is not null)
            {
                await DeInitializeDropZone();
                await _jsFileDropperObject.DisposeAsync();
            }
        }
```

Basically `initializeDropZone()` adds a bunch of event listener (dragover, dragenter, drop,...) and  `deInitializeDropZone()` will remove them in the JS file. As as I know, one should take care and remove all the added listeners to avoid memory leaks. 

However, `DisposeAsync()` as implemented above will cause the following exceptions either on page refresh (F5) or tab close in the browser:

```
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
      Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
         at WebApplication.Pages.DatasetManager.DeInitializeDropZone() in C:\Users\jzellinger\Documents\source\VisualStudio\VisionLearningWebService\WebApplication\Pages\DatasetManager.razor.cs:line 261
         at WebApplication.Pages.DatasetManager.DisposeAsync() in C:\Users\jzellinger\Documents\source\VisualStudio\VisionLearningWebService\WebApplication\Pages\DatasetManager.razor.cs:line 379
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass69_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'JsDdt68uNIfa3s-CypD539SCRmHDt_FwoOkQs_kdNEk'.
      Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSObjectReferenceExtensions.InvokeVoidAsync(IJSObjectReference jsObjectReference, String identifier, Object[] args)
         at WebApplication.Pages.DatasetManager.DeInitializeDropZone() in C:\Users\jzellinger\Documents\source\VisualStudio\VisionLearningWebService\WebApplication\Pages\DatasetManager.razor.cs:line 261
         at WebApplication.Pages.DatasetManager.DisposeAsync() in C:\Users\jzellinger\Documents\source\VisualStudio\VisionLearningWebService\WebApplication\Pages\DatasetManager.razor.cs:line 379
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass69_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()
```

### Describe the solution you'd like

According to the answer in the issue linked above from @javiercn (at least if I understand it correctly), in case of a "full navigation" there is no need to clean up stuff.  

However, if that is the case, it would be nice to either

- Get some information during `DisposeAsync()` whether disposing is caused by "full navigation" or not
- Let the dispose function take care of JS invocations, if the circuit is already disconnected. 

I know this is a somewhat ambiguous request, but I spent quite some time with the above error and I'm still not sure ho to go about it. :)

**Comment by javiercn** [comment]
@TheRealRolandDeschain thanks for contacting us.

The best way to tackle this is to wrap your JS interop calls in a try..catch statement within the `DisposeAsync` method in your component. 

> Get some information during DisposeAsync() whether disposing is caused by "full navigation" or not

The server has no way to know that your user pressed F5 or that typed a different URL in the browser bar. At that point, the page in the browser is gone, so there are no "leaked" resources in the browser.

The best you can do is know if the component is being disposed while the circuit is connected and conditionally issue the JS interop calls in that scenario only. On the server, the circuit is disconnected, which you can get info about by authoring a [circuit handler](https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-6.0#blazor-server-circuit-handler) and reflect it in a scoped service that your component can consume.

> Let the dispose function take care of JS invocations, if the circuit is already disconnected.

We don't plan to build any smarts in on how JS interop is handled because that would be hard to explain and would create hard to debug situations. You should only issue JS interop calls when the circuit is connected, and if you happen to issue a JS interop call when the circuit is disconnected, you'll get an exception. Keep in mind that the circuit can be disconnected at any point within the call. It can already be disconnected when you try to make the call or it can disconnect after the call has been sent but before the response has arrived.
