### ISSUE TITLE
disable FileWatching for FileVersionProvider/Default IFileProvider

### ISSUE THREAD

**Issue by schmitch** [dotnet/aspnetcore#42070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

currently when running production under docker or under kubernetes we sometimes run into:

```
System.IO.IOException: The configured user limit (128) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.
    at System.IO.FileSystemWatcher.StartRaisingEvents()
    at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
    at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
    at Microsoft.AspNetCore.Mvc.Razor.Infrastructure.DefaultFileVersionProvider.AddFileVersionToPath(PathString requestPathBase, String path)
```

the problem is that we use `asp-append-version` which actually triggers a file watcher, since it calls `FileProvider.Watch`. 

### Describe the solution you'd like

However in production this is not really that cool, since it can quickly exhaust all inodes. Thus it would be great if it would be possible to disable the file watching in production completly, the same thing that can be done for configuration files via the following: https://docs.microsoft.com/de-de/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-6.0#disable-app-configuration-reload-on-change

**Comment by schmitch** [comment]
btw. at the Moment we basically use the following to remove the FileWatcher:

```
            if (CurrentEnvironment.IsProduction())
            {
                CurrentEnvironment.WebRootFileProvider = new EvFileProvider(CurrentEnvironment.WebRootFileProvider);
            }
            
            // file provider, that delegates to IFileProvider from WebRootFileProvider, except the Watch method:
    public IChangeToken Watch(string filter)
    {
        // we do not want to poll for files in production...
        // never ever!!
        return NullChangeToken.Singleton;
    }
```

thus it will disable the FileWatching completly, however there is no settings key to manually disable it, which is a little bit strange, since that can be a little bit wierd when running on k8s where the node does not have a high user limit.

**Comment by javiercn** [comment]
@schmitch thanks for contacting us.

We will move this issue to the backlog and consider it for a future release if we see more feedback in this area.

**Comment by mjrousos** [comment]
+1. I'm working with a customer who ran into this in a scenario where, in an AKS environment, they had a large blob storage container volume mounted under wwwroot and this behavior causes use of "asp-append-version" to result in a large performance degradation while the File System Watcher walks the mounted blob storage container.

In this case, the file watching is fine, the issue is that there's no way to disable watching **subdirectories** (which don't need watched to know if a css in the root is changed). Would be great to update this behavior to be more scoped.

**Comment by isaevdan** [comment]
Another scenario where option to disable watch would be helpful is when you mount static folder to Azure Files in AppService and you end up in large amounts of transactions billed to your Storage account.

I will have to use some workaround for this case right now

**Comment by ryno1234** [comment]
I have a SaaS product where each of our clients can have, easily, a few hundred custom assets that can be updated by the client at any point in time. We have many clients. That adds up to thousands of watchers easily. As we grow this will only compound.

I haven't actually implemented the `asp-append-version` across the board but, as we're migrating to utilizing Cloudflare which is caching our assets, we've found it necessary to have more significant cache busting beyond just the cache headers so we're looking at `asp-append-version`.

My concern is investing time into utilizing `asp-append-version` and then hitting performance issues. How would this perform with 10,000 file watchers? 100,000? etc. (For context, I'm specifically referring to a Linux environment)

If this isn't a technique that can be used at scale, in my opinion that should be documented somewhere.

Any insight you have would be appreciated
