### ISSUE TITLE
Intermittent `NullReferenceException` from `DefaultHttpRequest.Form`

### ISSUE THREAD

**Issue by SimonCropp** [dotnet/aspnetcore#42100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In Sentry, when an exception occurs, we try to log certain parts of the request. For one consumer they are getting an intermittent NullReferenceException when sentry is trying to access `DefaultHttpRequest.Form` https://github.com/getsentry/sentry-dotnet/issues/1701

On the sentry side we need to handle this in a more graceful way, however the stack trace would seem to point to a potential bug in aspnet core.

Inside `DefaultHttpRequest` we have BodyReader:

https://github.com/dotnet/aspnetcore/blob/main/src/Http/Http/src/Internal/DefaultHttpRequest.cs#L172-L175
```
public override PipeReader BodyReader
{
    get { return RequestBodyPipeFeature.Reader; }
}
```

Which uses `RequestBodyPipeFeature`:
https://github.com/dotnet/aspnetcore/blob/main/src/Http/Http/src/Internal/DefaultHttpRequest.cs#L64-L65

```
private IRequestBodyPipeFeature RequestBodyPipeFeature =>
        _features.Fetch(ref _features.Cache.BodyPipe, this.HttpContext, _newRequestBodyPipeFeature)!;
```

so it looks like the `_features.Fetch` is returning null, and the `!` suppression is wrong since it can return null at runtime. 

### Expected Behavior

no `NullReferenceException`

### Exceptions (if any)

```
   at Microsoft.AspNetCore.Http.DefaultHttpRequest.get_BodyReader()
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Features.FormFeature.ReadForm()
   at Microsoft.AspNetCore.Http.DefaultHttpRequest.get_Form()
```

### .NET Version

6.0.201

**Comment by davidfowl** [comment]
See https://github.com/dotnet/aspnetcore/issues/42040

**Comment by SimonCropp** [comment]
@davidfowl thanks. so is this similar to https://github.com/dotnet/aspnetcore/issues/25454#issuecomment-684955126  ?

**Comment by davidfowl** [comment]
That's my guess.

**Comment by SimonCropp** [comment]
@davidfowl ok cool. In that case, happy to have this closed given it is tracked by a larger issue
