### ISSUE TITLE
Quarantine ClientCertificate_Allow_NotAvailable_Optional

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#42388]
## Failing Test(s)

- Interop.FunctionalTests.Http3.Http3TlsTests.ClientCertificate_Allow_NotAvailable_Optional

## Error Message

```text
System.Net.Http.HttpRequestException : Connection has been shutdown by transport: QUIC_STATUS_CONNECTION_REFUSED (127.0.0.1:60515)
---- Microsoft.Quic.MsQuicException : Connection has been shutdown by transport: QUIC_STATUS_CONNECTION_REFUSED
```

## Stacktrace

<details>

```text
   at System.Net.Http.ConnectHelper.ConnectQuicAsync(HttpRequestMessage request, DnsEndPoint endPoint, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp3ConnectionAsync(HttpRequestMessage request, HttpAuthority authority, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 83
   at Interop.FunctionalTests.Http3.Http3TlsTests.ClientCertificate_Allow_NotAvailable_Optional() in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/Http3/Http3TlsTests.cs:line 246
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventShutdownInitiatedByTransport(State state, QUIC_CONNECTION_EVENT& connectionEvent)
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)
--- End of stack trace from previous location ---
   at System.Net.Http.ConnectHelper.ConnectQuicAsync(HttpRequestMessage request, DnsEndPoint endPoint, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken)
```
</details>

## Logs

<details>

```text
[0.004s] [TestLifetime] [Information] Starting test ClientCertificate_Allow_NotAvailable_Optional at 2022-06-23T01:10:13
[0.006s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting starting
[0.027s] [Microsoft.Hosting.Lifetime] [Information] Now listening on: https://[::]:60515
[0.027s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Debug] Loaded hosting startup assembly Interop.FunctionalTests
[0.027s] [Microsoft.Hosting.Lifetime] [Information] Application started. Press Ctrl+C to shut down.
[0.027s] [Microsoft.Hosting.Lifetime] [Information] Hosting environment: Production
[0.031s] [Microsoft.Hosting.Lifetime] [Information] Content root path: C:\h\w\B0F509E6\w\A32E08E9\e\
[0.031s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting started
[0.037s] [Microsoft.AspNetCore.Server.Kestrel] [Fatal] The connection listener failed to accept any new connections.
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MsQuicStream'.
   at System.Net.Quic.Implementations.MsQuic.MsQuicListener.ThrowIfDisposed()
   at System.Net.Quic.Implementations.MsQuic.MsQuicListener.AcceptConnectionAsync(CancellationToken cancellationToken)
   at System.Net.Quic.QuicListener.AcceptConnectionAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionListener.AcceptAsync(IFeatureCollection features, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicConnectionListener.cs:line 71
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.ConnectionDispatcher`1.<>c__DisplayClass8_0.<<StartAcceptingConnectionsCore>g__AcceptConnectionsAsync|0>d.MoveNext() in /_/src/Servers/Kestrel/Core/src/Internal/ConnectionDispatcher.cs:line 43
[0.040s] [Interop.FunctionalTests.Http3.Http3TlsTests] [Error] Test threw an exception.
System.Net.Http.HttpRequestException: Connection has been shutdown by transport: QUIC_STATUS_CONNECTION_REFUSED (127.0.0.1:60515)
 ---> Microsoft.Quic.MsQuicException: Connection has been shutdown by transport: QUIC_STATUS_CONNECTION_REFUSED
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventShutdownInitiatedByTransport(State state, QUIC_CONNECTION_EVENT& connectionEvent)
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)
--- End of stack trace from previous location ---
   at System.Net.Http.ConnectHelper.ConnectQuicAsync(HttpRequestMessage request, DnsEndPoint endPoint, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectQuicAsync(HttpRequestMessage request, DnsEndPoint endPoint, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp3ConnectionAsync(HttpRequestMessage request, HttpAuthority authority, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 83
   at Interop.FunctionalTests.Http3.Http3TlsTests.ClientCertificate_Allow_NotAvailable_Optional() in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/Http3/Http3TlsTests.cs:line 246
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
[0.040s] [TestLifetime] [Information] Finished test ClientCertificate_Allow_NotAvailable_Optional in 0.0363751s
```
</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1840428&view=ms.vss-test-web.build-test-results-tab&runId=48600542&paneView=debug&resultId=109494

**Comment by Tratcher** [comment]
#42389 also failed on this build.

Both failed on Windows.10.Amd64.Server20H2.Open and Windows.Amd64.Server2022.Open, but why are they even running on 20H2? They should require 2022. Other H3 tests are passing on both platforms.

**Comment by Tratcher** [comment]
Possibly related: https://github.com/dotnet/runtime/issues/55979
