### ISSUE TITLE
Quarantine ClientCertificate_Required_NotSent_AcceptedViaCallback

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#42389]
## Failing Test(s)

- Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Tests.QuicConnectionListenerTests.ClientCertificate_Required_NotSent_AcceptedViaCallback

## Error Message

```text
Microsoft.Quic.MsQuicException : Connection has been shutdown by transport: QUIC_STATUS_CONNECTION_REFUSED
```

## Stacktrace

<details>

```text
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventShutdownInitiatedByTransport(State state, QUIC_CONNECTION_EVENT& connectionEvent)
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 117
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Tests.QuicConnectionListenerTests.ClientCertificate_Required_NotSent_AcceptedViaCallback() in /_/src/Servers/Kestrel/Transport.Quic/test/QuicConnectionListenerTests.cs:line 112
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Tests.QuicConnectionListenerTests.ClientCertificate_Required_NotSent_AcceptedViaCallback() in /_/src/Servers/Kestrel/Transport.Quic/test/QuicConnectionListenerTests.cs:line 113
--- End of stack trace from previous location ---
```
</details>

## Logs

<details>

```text
[0.004s] [TestLifetime] [Information] Starting test ClientCertificate_Required_NotSent_AcceptedViaCallback at 2022-06-23T01:10:50
[0.025s] [Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Tests.QuicConnectionListenerTests] [Error] Test threw an exception.
Microsoft.Quic.MsQuicException: Connection has been shutdown by transport: QUIC_STATUS_CONNECTION_REFUSED
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventShutdownInitiatedByTransport(State state, QUIC_CONNECTION_EVENT& connectionEvent)
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 117
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Tests.QuicConnectionListenerTests.ClientCertificate_Required_NotSent_AcceptedViaCallback() in /_/src/Servers/Kestrel/Transport.Quic/test/QuicConnectionListenerTests.cs:line 112
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Tests.QuicConnectionListenerTests.ClientCertificate_Required_NotSent_AcceptedViaCallback() in /_/src/Servers/Kestrel/Transport.Quic/test/QuicConnectionListenerTests.cs:line 113
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
[0.044s] [TestLifetime] [Information] Finished test ClientCertificate_Required_NotSent_AcceptedViaCallback in 0.036089s
```
</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1840428&view=ms.vss-test-web.build-test-results-tab&runId=48600542&paneView=debug&resultId=108693

**Comment by Tratcher** [comment]
Possibly related: https://github.com/dotnet/runtime/issues/55979
