### ISSUE TITLE
CryptographicException on ProtectedBrowserStorage.GetAsync

### ISSUE THREAD

**Issue by jaydgus** [dotnet/aspnetcore#42418]
Hello,

We are getting the following error below when trying to use ProtectedBrowserStorage with blazor on .NET 6.0 (and 5.0) on IIS 10.  I've tried making 'load profile' = true in the app pool settings, but no luck. 

Error: System.Security.Cryptography.CryptographicException: The key {#redacted#} was not found in the key ring. For more information go to http://aka.ms/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.Unprotect[TValue](String purpose, String protectedJson)
   at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.GetAsync[TValue](String purpose, String key)

Thank you,
J

**Comment by javiercn** [comment]
@jaydgus thanks for contacting us.

that likely means you have an issue with your data protection configuration.

we would suggest that you check the data protection configuration in your deployment as a starting point.

**Comment by javiercn** [comment]
Check out https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-6.0 for details.

**Comment by jaydgus** [comment]
I'm thinking that I had an old value in my browser that encountered the error after changes were made to the server.  I was able to resolve the issue by deleting the value on error and then the next write fixed it:

```
try
{
    var result = await BrowserStorage.GetAsync<string>(StoredValueKey);
    StoredValue = result.Success ? result.Value ?? "0" : "0";
}
catch(Exception ex)
{
    //log
    Log.Error(ex, "Browser storage error");
    await jsRuntime.InvokeVoidAsync("console.log", $"Browser storage Get error: {ex.Message}");
    try
    {
        await BrowserStorage.DeleteAsync(StoredValueKey);
    }
    catch(Exception iex)
    {
        await jsRuntime.InvokeVoidAsync("console.log", $"Browser storage Delete error: {iex.Message}");
    }
    StoredValue = "0";
}
```

Thanks,
J

**Comment by javiercn** [comment]
@jaydgus thanks for the additional details.

That explains it.
