### ISSUE TITLE
How to set SignInScheme in an application using Microsoft.AspNetCore.Authentication.OpenIdConnect on multiple IDPs

### ISSUE THREAD

**Issue by WenningQiu** [dotnet/aspnetcore#42493]
My application uses Microsoft.AspNetCore.Authentication.OpenIdConnect  (version 6.0.6) to work with multiple Identity providers. It is getting "System.InvalidOperationException: The SignInScheme for a remote authentication handler cannot be set to itself.". How should the SignInScheme be properly set in this situation to avoid the error? (not setting SignInScheme in my code gives me the same error)

```
            foreach (var section in _configuration.GetChildren())
            {
                var options = new MicrosoftIdentityOptions();
                section.Bind(options);

                if (options.ClientId.IsNullOrEmpty())
                    continue; // Skip sections that are not for OpenID Connect.

                var scheme = section.Key;

                services.AddAuthentication(scheme)
                        .AddOpenIdConnect(scheme, openIdConnectOptions =>
                        {
                            openIdConnectOptions.ClientId = options.ClientId;
                            openIdConnectOptions.ClientSecret = options.ClientSecret;
                            openIdConnectOptions.Authority = options.Authority;
                            openIdConnectOptions.ResponseType = OpenIdConnectResponseType.Code;
                            openIdConnectOptions.GetClaimsFromUserInfoEndpoint = true;
                            openIdConnectOptions.SignInScheme = scheme;
                        });
            }
```

```
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: The SignInScheme for a remote authentication handler cannot be set to itself.  If it was not explicitly set, the AuthenticationOptions.DefaultSignInScheme or DefaultScheme is used.
         at Microsoft.AspNetCore.Authentication.RemoteAuthenticationOptions.Validate(String scheme)
         at Microsoft.AspNetCore.Authentication.AuthenticationBuilder.<>c__DisplayClass4_0`2.<AddSchemeHelper>b__1(TOptions o)
         at Microsoft.Extensions.Options.ValidateOptions`1.Validate(String name, TOptions options)
         at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
         at Microsoft.Extensions.Options.OptionsMonitor`1.<>c__DisplayClass10_0.<Get>b__0()
         at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
         at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
         at System.Lazy`1.CreateValue()
         at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
```

**Comment by HaoK** [comment]
SignInScheme needs to be set to a cookie authentication if you are setting this property.  You don't need to set this property if you don't have any cookies you want to persist the claims identity to.

**Comment by HaoK** [comment]
What are you trying to do in terms of your auth setup, ideally for SignInScheme, you would configure all of your remoteAuthentication schemes to have the same SignInScheme which would be a cookie, so your app would just check if the cookie exists, if so, the app is authenticated, and the cookie is just the persisted state/claims from whichever remote OIDC the user authenticated with.  Does that make sense?

**Comment by WenningQiu** [comment]
Thanks @HaoK. 

So I was able to get past the error by adding Cookie Authentication as below. But I have to explicitly set SignInScheme, otherwise I would get the same error. Does that look right?


```
            foreach (var section in _configuration.GetChildren())
            {
                var options = new MicrosoftIdentityOptions();
                section.Bind(options);

                if (options.ClientId.IsNullOrEmpty())
                    continue; // Skip sections that are not for OpenID Connect.

                var scheme = section.Key;
                var cookieScheme = $"{scheme}Cookie";

                services.AddAuthentication()
                        .AddCookie(cookieScheme)
                        .AddOpenIdConnect(scheme, openIdConnectOptions =>
                        {
                            openIdConnectOptions.ClientId = options.ClientId;
                            openIdConnectOptions.ClientSecret = options.ClientSecret;
                            openIdConnectOptions.Authority = options.Authority;
                            openIdConnectOptions.ResponseType = OpenIdConnectResponseType.Code;
                            openIdConnectOptions.GetClaimsFromUserInfoEndpoint = true;
                            openIdConnectOptions.SignInScheme = cookieScheme;
                        });
            }
```

**Comment by HaoK** [comment]
Yep that looks fine, you can also just set DefaultSignInScheme on authenticationOptions once to cookieScheme as a small cleanup
