### ISSUE TITLE
dotnet watch does not work in eng\dogfood.cmd environment

### ISSUE THREAD

**Issue by tmat** [dotnet/aspnetcore#42509]
First, had to add `https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json`, otherwise the app can't be restored:

```
Running 'dotnet restore' on D:\Temp\BW\BW.csproj...
  Determining projects to restore...
D:\Temp\BW\BW.csproj : warning NU1603: BW depends on Microsoft.AspNetCore.Components.WebAssembly (>= 7.0.0-preview.3.22157.6) but Microsoft.AspNetCore.Components.WebA
ssembly 7.0.0-preview.3.22157.6 was not found. An approximate best match of Microsoft.AspNetCore.Components.WebAssembly 7.0.0-preview.3.22178.4 was resolved.
```

Then I'm seeing:

System.TypeLoadException: Could not load type 'System.Net.Quic.QuicImplementationProviders'

```
PS D:\sdk\eng> dotnet --version
7.0.100-dev
PS D:\Temp\BW> dotnet nuget list source
Registered Sources:
  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
  2.  Microsoft Visual Studio Offline Packages [Enabled]
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
  3.  Package source 1 [Enabled]
      https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json
PS D:\sdk\eng> mkdir D:\Temp\BW


    Directory: D:\Temp


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         6/30/2022   1:46 PM                BW


PS D:\sdk\eng> cd D:\Temp\BW
PS D:\Temp\BW> dotnet new blazorwasm
The template "Blazor WebAssembly App" was created successfully.
This template contains technologies from parties other than Microsoft, see https://aka.ms/aspnetcore/7.0-third-party-notices for details.

Processing post-creation actions...
Running 'dotnet restore' on D:\Temp\BW\BW.csproj...
  Determining projects to restore...
  Restored D:\Temp\BW\BW.csproj (in 374 ms).
Restore succeeded.

PS D:\Temp\BW> dotnet watch
dotnet watch 🔥 Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload.
  💡 Press "Ctrl + R" to restart.
dotnet watch 🔧 Building...
  Determining projects to restore...
  All projects are up-to-date for restore.
D:\sdk\artifacts\bin\redist\Debug\dotnet\sdk\7.0.100-dev\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(219,5): message NETSDK1057: You are
 using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [D:\Temp\BW\BW.csproj]
  BW -> D:\Temp\BW\bin\Debug\net7.0\BW.dll
  BW (Blazor output) -> D:\Temp\BW\bin\Debug\net7.0\wwwroot
dotnet watch ❌ System.TypeLoadException: Could not load type 'System.Net.Quic.QuicImplementationProviders' from assembly 'System.Net.Quic, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Microsoft.AspNetCore.Hosting.WebHostBuilderQuicExtensions.IsQuicSupported()
   at Microsoft.AspNetCore.Hosting.WebHostBuilderQuicExtensions.UseQuic(IWebHostBuilder hostBuilder)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderKestrelExtensions.UseKestrel(IWebHostBuilder hostBuilder)
   at Microsoft.DotNet.Watcher.Tools.BrowserRefreshServer.<>c__DisplayClass12_0.<StartAsync>b__0(IWebHostBuilder builder) in D:\sdk\src\BuiltInTools\dotnet-watch\Filters\BrowserRefreshServer.cs:line 59
   at Microsoft.Extensions.Hosting.GenericHostWebHostBuilderExtensions.ConfigureWebHost(IHostBuilder builder, Action`1 configure, Action`1 configureWebHostBuilder)
   at Microsoft.DotNet.Watcher.Tools.BrowserRefreshServer.StartAsync(CancellationToken cancellationToken) in D:\sdk\src\BuiltInTools\dotnet-watch\Filters\BrowserRefreshServer.cs:line 56
   at Microsoft.DotNet.Watcher.Tools.BrowserRefreshFilter.ProcessAsync(DotNetWatchContext context, CancellationToken cancellationToken) in D:\sdk\src\BuiltInTools\dotnet-watch\Filters\BrowserRefreshFilter.cs:line 54
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(DotNetWatchContext context, CancellationToken cancellationToken) in D:\sdk\src\BuiltInTools\dotnet-watch\HotReloadDotNetWatcher.cs:line 88
   at Microsoft.DotNet.Watcher.Program.MainInternalAsync(CommandLineOptions options, CancellationToken cancellationToken) in D:\sdk\src\BuiltInTools\dotnet-watch\Program.cs:line 293
   at Microsoft.DotNet.Watcher.Program.MainInternalAsync(CommandLineOptions options, CancellationToken cancellationToken) in D:\sdk\src\BuiltInTools\dotnet-watch\Program.cs:line 293
   at Microsoft.DotNet.Watcher.Program.HandleWatch(CommandLineOptions options) in D:\sdk\src\BuiltInTools\dotnet-watch\Program.cs:line 191
dotnet watch ❌ An unexpected error occurred
PS D:\Temp\BW>
```

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS, @javiercn do you guys know what may be causing this?

**Comment by SteveSandersonMS** [comment]
I don’t know for sure, but it appears to be some kind of version mismatch. The type QuicImplementationProviders (or code that calls it) was added in 7.0 preview 4 if I recall correctly. 

If something is still using an older SDK than that, this is the sort of error I’d expect.

**Comment by SteveSandersonMS** [comment]
Actually I see a reference to preview 3 in the error message above, so that looks very likely to be the problem.

**Comment by tmat** [comment]
Is `dotnet new blazorwasm` using the wrong version for `PackageReferences`?

**Comment by SteveSandersonMS** [comment]
Maybe! In general it uses versions matching whatever version of the SDK you're using. However I see your dotnet version is `7.0.100-dev`, so I really don't know what package versions it's going to use.

Could you post whatever csproj was generated by `dotnet new blazorwasm` so we can see what package versions it's actually using?

I'm not very familiar with the `eng/dogfood.cmd` environment so am not sure how it knows what package versions to use, or whether they are expected to be correct.

**Comment by tmat** [comment]
```
<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="7.0.0-preview.3.22157.6" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="7.0.0-preview.3.22157.6" PrivateAssets="all" />
  </ItemGroup>

</Project>
```

**Comment by mkArtakMSFT** [comment]
@tmat it's not clear where from you've got the preview3 version? The latest is preview5 and preview6 has already locked down. Can you try one of these and see if that solves your problem?
Note, that for a not-yet-shipped SDK you will need to configure custom NuGet feeds.

**Comment by tmat** [comment]
@javiercn The preview3 version is referenced from global.json in the sdk repo:
https://github.com/dotnet/sdk/blob/main/global.json#L3

Shouldn't that be updated then if it doesn't work?

**Comment by javiercn** [comment]
@tmat I normally don't use the `eng\dogfood.cmd` command when working on this repo. It might be that updating that works, but I am not sure what other effects it might have.

**Comment by tmat** [comment]
@javiercn Using dogfood.cmd is recommended in https://github.com/dotnet/aspnetcore-internal/wiki/How-to-investigate-dotnet-watch-issues#if-you-need-to-debug-the-watch-tool

If this is not working then it should be either fixed or replaced with something that works.

I tried updating the references to `7.0.0-preview.7.22354.2` and still get

```
System.TypeLoadException: Could not load type 'System.Net.Quic.QuicImplementationProviders' from assembly 'System.Net.Quic, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

 :(

**Comment by javiercn** [comment]
@tmat I think I wrote that guidance the last time I had to do stuff with it😄.

I think those debug instructions are biased towards investigating issues reported on RTM versions. 

Still the guidance doesn't say anything about using the `eng\dogfood.cmd` SDK to create the project, it only refers to use that for running the `dotnet watch` tool.

I still think that the easiest way would be to create the project with a regular SDK and use the SDK from `eng\dogfood.cmd` afterwards.

**Comment by tmat** [comment]
> I still think that the easiest way would be to create the project with a regular SDK and use the SDK from eng\dogfood.cmd afterwards.

I just did that. It doesn't work.

**Comment by SteveSandersonMS** [comment]
> I just did that. It doesn't work.

Could you clarify what happens when you try? Are you saying you're still getting projects with the Preview3 package references? If so that sounds like you need to update your local SDK.

**Comment by tmat** [comment]
```
PS D:\temp\bw> dotnet watch
dotnet watch 🔥 Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload.
  💡 Press "Ctrl + R" to restart.
dotnet watch 🔧 Building...
  Determining projects to restore...
  Restored D:\temp\bw\BW.csproj (in 355 ms).
D:\sdk\artifacts\bin\redist\Debug\dotnet\sdk\7.0.100-dev\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifier
Inference.targets(219,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-suppo
rt-policy [D:\temp\bw\BW.csproj]
  BW -> D:\temp\bw\bin\Debug\net7.0\BW.dll
  BW (Blazor output) -> D:\temp\bw\bin\Debug\net7.0\wwwroot
dotnet watch ❌ System.TypeLoadException: Could not load type 'System.Net.Quic.QuicImplementationProviders' from assembly 'System.Net.Quic, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Microsoft.AspNetCore.Hosting.WebHostBuilderQuicExtensions.IsQuicSupported()
   at Microsoft.AspNetCore.Hosting.WebHostBuilderQuicExtensions.UseQuic(IWebHostBuilder hostBuilder)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderKestrelExtensions.UseKestrel(IWebHostBuilder hostBuilder)
   at Microsoft.DotNet.Watcher.Tools.BrowserRefreshServer.<>c__DisplayClass12_0.<StartAsync>b__0(IWebHostBuilder builder) in D:\sdk\src\BuiltInTools\dotnet-watch\Filters\BrowserRefreshServer.cs:line 59
   at Microsoft.Extensions.Hosting.GenericHostWebHostBuilderExtensions.ConfigureWebHost(IHostBuilder builder, Action`1 configure, Action`1 configureWebHostBuilder)
   at Microsoft.DotNet.Watcher.Tools.BrowserRefreshServer.StartAsync(CancellationToken cancellationToken) in D:\sdk\src\BuiltInTools\dotnet-watch\Filters\BrowserRefreshServer.cs:line 56
   at Microsoft.DotNet.Watcher.Tools.BrowserRefreshFilter.ProcessAsync(DotNetWatchContext context, CancellationToken cancellationToken) in D:\sdk\src\BuiltInTools\dotnet-watch\Filters\BrowserRefreshFilter.cs:line 54
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(DotNetWatchContext context, CancellationToken cancellationToken) in D:\sdk\src\BuiltInTools\dotnet-watch\HotReloadDotNetWatcher.cs:line 88
   at Microsoft.DotNet.Watcher.Program.MainInternalAsync(CommandLineOptions options, CancellationToken cancellationToken) in D:\sdk\src\BuiltInTools\dotnet-watch\Program.cs:line 293
   at Microsoft.DotNet.Watcher.Program.MainInternalAsync(CommandLineOptions options, CancellationToken cancellationToken) in D:\sdk\src\BuiltInTools\dotnet-watch\Program.cs:line 293
   at Microsoft.DotNet.Watcher.Program.HandleWatch(CommandLineOptions options) in D:\sdk\src\BuiltInTools\dotnet-watch\Program.cs:line 191
dotnet watch ❌ An unexpected error occurred
PS D:\temp\bw> dotnet --version
7.0.100-dev
```

**Comment by SteveSandersonMS** [comment]
Interesting. Could you try setting the package versions to `7.0.0-preview.5.22303.8`?

Just trying to narrow this down! If preview 5 doesn't work, that suggests a more serious problem than simply version mismatches.

**Comment by tmat** [comment]
> Could you try setting the package versions to 7.0.0-preview.5.22303.8?

Of course. Updated the package references but still the same exception.

**Comment by TanayParikh** [comment]
@tmat are you still blocked on this issue?

**Comment by tmat** [comment]
This is now fixed.
