### ISSUE TITLE
Intermittent ObjectDisposedException in SPA Hosting

### ISSUE THREAD

**Issue by Sayan751** [dotnet/aspnetcore#42608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a small aspnetcore service to host/serve a SPA. Only intermittently, I am getting the following error in the event log.

```
Category: Microsoft.AspNetCore.Server.HttpSys.HttpSysListener
EventId: 6
SpanId: 9e2d8fa91d335924
TraceId: 9590e80341d42cca7b750ac04d095314
ParentId: 0000000000000000
RequestId: 4000002b-0005-ed00-b63f-84710c7967bb
RequestPath: /app/path/to/a/static/file.ext

ProcessRequestAsync

Exception: 
System.ObjectDisposedException: ObjectDisposed_Generic
ObjectDisposed_ObjectName_Name, Microsoft.AspNetCore.Server.HttpSys.ResponseBody
   at Microsoft.AspNetCore.Server.HttpSys.ResponseBody.CheckDisposed()
   at Microsoft.AspNetCore.Server.HttpSys.ResponseBody.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.HttpSys.ResponseStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.IO.Pipelines.StreamPipeWriter.FlushAsyncInternal(Boolean writeToStream, ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at System.IO.Pipelines.StreamPipeWriter.CompleteAsync(Exception exception)
   at Microsoft.AspNetCore.Server.HttpSys.RequestContext.CompleteAsync()
   at Microsoft.AspNetCore.Server.HttpSys.RequestContext`1.ExecuteAsync()
   at Microsoft.AspNetCore.Server.HttpSys.RequestContext`1.ExecuteAsync()
```

However, the app runs in the browser without any issue. This problem is more prominent when running the automated e2e tests (using Playwright).

This is how I am configuring the SPA static files.

```csharp
public class Startup
{
  public void ConfigureServices(IServiceCollection services)
  {
    services.AddSpaStaticFiles(opt =>
    {
      opt.RootPath = _Configuration.GetValue("Webroot", "./Content");
    });
  }

  public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ILogger<Startup> logger, IConfiguration config)
  {
    app.UseSpaStaticFiles(new StaticFileOptions
    {
      OnPrepareResponse = context =>
      {
        if (context.Context.Response.HasStarted || context.Context.Response.StatusCode != (int)HttpStatusCode.OK) return;
        context.Context.Response.Headers["Cache-Control"] = "public, max-age=1000";
        context.Context.Response.Headers["Vary"] = "Accept-Encoding";
      }
    });
  }
}
```

### Expected Behavior

The superfluous (as there is no error at the client/browser) error log should be avoided.

### .NET Version

6.0.301

**Comment by Sayan751** [comment]
@javiercn Additional info: just in case, it was not clear from my last comment, the physical directory structure is as follows:

```
ConfiguredWebroot
+
+--+App1
|   +
|   +-+index.html
|   |
|   +-+other.static.resourc.es
|
+--+App2
    +
    +-+index.html
    |
    +-+other.static.resourc.es
```

**Comment by Sayan751** [comment]
Sorry if I am spamming. Here is some more info on this. In my attempt to isolate the issue, I tried the following instead of the `.UseSpa`.

```csharp
c.Use((context, next) =>
{
  var ep = context.GetEndpoint();
  if (ep == null)
  {
    context.Request.Path = "/index.html";
  }
  return next(context);
});
c.UseStaticFiles(new StaticFileOptions
{
  FileProvider = new PhysicalFileProvider(sourcePath)
});
```

But that didn't help and the issue can still be reproduced.

**Comment by mkArtakMSFT** [comment]
@Tratcher, @halter73 is that expected to receive such a low-level exception? Maybe you see something suspicious in the call stack that should be investigated?

**Comment by Tratcher** [comment]
This appears similar to https://github.com/dotnet/aspnetcore/pull/35401, caused by client disconnects, but that should have been fixed in 6.0.

**Comment by mkArtakMSFT** [comment]
Moving over to the `runtime` area path, @Tratcher

**Comment by Sayan751** [comment]
@adityamandaleeka Tad bit late, but here is the reproduction of the issue: https://github.com/Sayan751/netcore-httpsys-object-disposed-repro

It seems that the issue is reproducible with `https` hosting, and when the log level is set to `Information`. Funnily enough, when the log level is set to `Trace`, it seems that the `fail` log is changed to a `dbg` log. Although the log for these two cases are quite different, but I suspect that it comes from the same root cause. 

Although I am not 100% sure, but it seems to me the failure occurs when the browser disconnects during the phase when the server is attempting to transmit some file or is scheduled to transmit some file. Which can be easily, frequently, and more or less effortlessly manufactured by running some e2e tests (the actual nature/assertions in those tests are somewhat irrelevant, as the error occurs while downloading the static files from the hosting-service).

**Comment by Sayan751** [comment]
@adityamandaleeka @Tratcher @mkArtakMSFT @javiercn please consider reopening this.
