### ISSUE TITLE
dotnet 6 angular template does not work out of the box

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#42632]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/dotnet-6-angular-template-does-not-work-/10086199)._

---
[severity:It's more difficult to complete my work]
I've been attempting to create a ASP.NET + Angular project using the supplied asp.net hosted angular template that comes with dotnet 6.
Without any modification I cannot get the angular side to build and run. Below I will supply current software versions as well as the errors I'm receiving. I've tried creating the project using ``` dotnet new angular -o my-project ``` as well as using the ui inside visual studio 2022.

dotnet --list-runtimes

```
Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

dotnet --list-sdks

```
5.0.403 [C:\Program Files\dotnet\sdk]
6.0.200 [C:\Program Files\dotnet\sdk]
```

node -v

```
v16.15.1
```

npm -v

```
8.13.2
```

ng version

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 13.2.5
Node: 16.15.1
Package Manager: npm 8.13.2
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1302.5 (cli-only)
@angular-devkit/core         13.2.5 (cli-only)
@angular-devkit/schematics   13.2.5 (cli-only)
@schematics/angular          13.2.5 (cli-only)
```

---

## Errors

```
../../../../../c#/clarity-lead/code/ClarityLead.WebApp/ClientApp/src/main.ts - Error: Module build failed (from ../../../../../c#/clarity-lead/code/ClarityLead.WebApp/ClientApp/node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
Error: Cannot find module 'C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\build-angular\src\babel\webpack-loader.js'
Require stack:
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\loader-runner\lib\loadLoader.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\loader-runner\lib\LoaderRunner.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\NormalModuleFactory.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\Compiler.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\ProgressPlugin.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\SourceMapDevToolPlugin.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\build-webpack\src\webpack\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\build-webpack\src\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\build-angular\src\builders\dev-server\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\architect\node\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular\cli\models\architect-command.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular\cli\commands\serve-impl.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular\cli\utilities\json-schema.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular\cli\models\command-runner.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular\cli\lib\cli\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular\cli\lib\init.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadLoader (C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\loader-runner\lib\loadLoader.js:19:17)
    at iteratePitchingLoaders (C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\loader-runner\lib\LoaderRunner.js:182:2)
    at runLoaders (C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\loader-runner\lib\LoaderRunner.js:397:2)
    at NormalModule._doBuild (C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\NormalModule.js:809:3)
    at NormalModule.build (C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\NormalModule.js:953:15)
    at C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\Compilation.js:1361:12

../../../../../c#/clarity-lead/code/ClarityLead.WebApp/ClientApp/src/polyfills.ts - Error: Module build failed (from ../../../../../c#/clarity-lead/code/ClarityLead.WebApp/ClientApp/node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
Error: Cannot find module 'C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\build-angular\src\babel\webpack-loader.js'
Require stack:
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\loader-runner\lib\loadLoader.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\loader-runner\lib\LoaderRunner.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\NormalModuleFactory.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\Compiler.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\ProgressPlugin.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\SourceMapDevToolPlugin.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\build-webpack\src\webpack\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\build-webpack\src\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\build-angular\src\builders\dev-server\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\architect\node\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular\cli\models\architect-command.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular\cli\commands\serve-impl.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular\cli\utilities\json-schema.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular\cli\models\command-runner.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular\cli\lib\cli\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular\cli\lib\init.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadLoader (C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\loader-runner\lib\loadLoader.js:19:17)
    at iteratePitchingLoaders (C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\loader-runner\lib\LoaderRunner.js:182:2)
    at runLoaders (C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\loader-runner\lib\LoaderRunner.js:397:2)
    at NormalModule._doBuild (C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\NormalModule.js:809:3)
    at NormalModule.build (C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\NormalModule.js:953:15)
    at C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\Compilation.js:1361:12

../../../../../c#/clarity-lead/code/ClarityLead.WebApp/ClientApp/node_modules/bootstrap/dist/css/bootstrap.min.css - Error: Module build failed (from ../../../../../c#/clarity-lead/code/ClarityLead.WebApp/ClientApp/node_modules/mini-css-extract-plugin/dist/loader.js):
Error: Cannot find module 'C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\mini-css-extract-plugin\dist\loader.js'
Require stack:
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\loader-runner\lib\loadLoader.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\loader-runner\lib\LoaderRunner.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\NormalModuleFactory.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\Compiler.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\ProgressPlugin.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\SourceMapDevToolPlugin.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\build-webpack\src\webpack\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\build-webpack\src\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\build-angular\src\builders\dev-server\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\architect\node\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular\cli\models\architect-command.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular\cli\commands\serve-impl.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular\cli\utilities\json-schema.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular\cli\models\command-runner.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular\cli\lib\cli\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular\cli\lib\init.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadLoader (C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\loader-runner\lib\loadLoader.js:19:17)
    at iteratePitchingLoaders (C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\loader-runner\lib\LoaderRunner.js:182:2)
    at runLoaders (C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\loader-runner\lib\LoaderRunner.js:397:2)
    at NormalModule._doBuild (C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\NormalModule.js:809:3)
    at NormalModule.build (C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\NormalModule.js:953:15)
    at C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\Compilation.js:1361:12

../../../../../c#/clarity-lead/code/ClarityLead.WebApp/ClientApp/src/styles.css - Error: Module build failed (from ../../../../../c#/clarity-lead/code/ClarityLead.WebApp/ClientApp/node_modules/mini-css-extract-plugin/dist/loader.js):
Error: Cannot find module 'C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\mini-css-extract-plugin\dist\loader.js'
Require stack:
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\loader-runner\lib\loadLoader.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\loader-runner\lib\LoaderRunner.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\NormalModuleFactory.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\Compiler.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\ProgressPlugin.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\SourceMapDevToolPlugin.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\build-webpack\src\webpack\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\build-webpack\src\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\build-angular\src\builders\dev-server\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\architect\node\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular\cli\models\architect-command.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular\cli\commands\serve-impl.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular\cli\utilities\json-schema.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular\cli\models\command-runner.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular\cli\lib\cli\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular\cli\lib\init.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadLoader (C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\loader-runner\lib\loadLoader.js:19:17)
    at iteratePitchingLoaders (C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\loader-runner\lib\LoaderRunner.js:182:2)
    at runLoaders (C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\loader-runner\lib\LoaderRunner.js:397:2)
    at NormalModule._doBuild (C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\NormalModule.js:809:3)
    at NormalModule.build (C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\NormalModule.js:953:15)
    at C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\Compilation.js:1361:12

../../../../../c#/clarity-lead/code/ClarityLead.WebApp/ClientApp/src/app/nav-menu/nav-menu.component.css - Error: Module build failed (from ../../../../../c#/clarity-lead/code/ClarityLead.WebApp/ClientApp/node_modules/postcss-loader/dist/cjs.js):
Error: Cannot find module 'C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\postcss-loader\dist\cjs.js'
Require stack:
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\loader-runner\lib\loadLoader.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\loader-runner\lib\LoaderRunner.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\NormalModuleFactory.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\Compiler.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\ProgressPlugin.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\SourceMapDevToolPlugin.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\build-webpack\src\webpack\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\build-webpack\src\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\build-angular\src\builders\dev-server\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\architect\node\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular\cli\models\architect-command.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular\cli\commands\serve-impl.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular\cli\utilities\json-schema.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular\cli\models\command-runner.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular\cli\lib\cli\index.js
- C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\@angular\cli\lib\init.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadLoader (C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\loader-runner\lib\loadLoader.js:19:17)
    at iteratePitchingLoaders (C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\loader-runner\lib\LoaderRunner.js:182:2)
    at runLoaders (C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\loader-runner\lib\LoaderRunner.js:397:2)
    at NormalModule._doBuild (C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\NormalModule.js:809:3)
    at NormalModule.build (C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\NormalModule.js:953:15)
    at C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack\lib\Compilation.js:1361:12

Error: Module not found: Error: Can't resolve 'C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp\node_modules\webpack-dev-server\client\index.js?protocol=auto%3A&username=&password=&hostname=0.0.0.0&port=0&pathname=%2fws&logging=info&reconnect=10' in 'C:\Dev\c#\clarity-lead\code\ClarityLead.WebApp\ClientApp'



** Angular Live Development Server is listening on localhost:44432, open your browser on https://localhost:44432/ **


× Failed to compile.
```

I've tried updating various angular packages and versions but with no success. Any help / direction would be apperciated.

---
#### Feedback Bot on 7/3/2022, 08:08 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by javiercn** [comment]
@MackinnonBuck can you take a look?

**Comment by MackinnonBuck** [comment]
Can't seem to reproduce locally - a few things they could try:
* Creating the project from a simpler folder path (`C:\TestProject\`)
* Building the project using `dotnet build` in a terminal running as administrator
* Clearing the global npm cache
* Trying a more up-do-date .NET SDK version

**Comment by javiercn** [comment]
Could you provide a minimal repro project that illustrates the issue? The issue might have to do with something related to your environment. You might also want to check if this happens with a template created with `ng new`.
