### ISSUE TITLE
aspnetcore Abnormal prompt during operation 

### ISSUE THREAD

**Issue by cwsheng** [dotnet/aspnetcore#42647]
**Environment**
System：Win Server 2016 
dotnet : dotnet3.1.100

**Log details：**

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Administrator\AppData\Local\Temp\3\ASPNETCORE_bbebd031-ff9a-425c-bfe6-c7388344320c.tmp'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Microsoft.AspNetCore.WebUtilities.FileBufferingWriteStream.EnsureFileStream()
   at Microsoft.AspNetCore.WebUtilities.FileBufferingWriteStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.AspNetCore.WebUtilities.HttpResponseStreamWriter.Write(Char[] values, Int32 index, Int32 count)
   at Newtonsoft.Json.Utilities.JavaScriptUtils.WriteEscapedJavaScriptString(TextWriter writer, String s, Char delimiter, Boolean appendDelimiters, Boolean[] charEscapeFlags, StringEscapeHandling stringEscapeHandling, IArrayPool`1 bufferPool, Char[]& writeBuffer)
   at Newtonsoft.Json.JsonTextWriter.WriteEscapedString(String value, Boolean quote)
   at Newtonsoft.Json.JsonWriter.WriteValue(JsonWriter writer, PrimitiveTypeCode typeCode, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at ZLSoft.Rpts.Web.Startup.<>c.<<Configure>b__15_4>d.MoveNext() in D:\software\Jenkins\Jenkins.jenkins\workspace\报表服务安装包\server\srccore\ZLSoft.Rpts.Web\Startup.cs:line 325
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Troubleshooting steps**
1. check C:\Users\Administrator\AppData\Local\Temp\3\ path not find.

**Comment by javiercn** [comment]
@cwsheng thanks for contacting us.

I believe this is related to the fact that newtonsoft.json will buffer large responses to disk, but I'll let other folks chime in.

**Comment by Tratcher** [comment]
Does this happen on every JSON response, or is it sporadic?

**Comment by cwsheng** [comment]
High frequency of occurrence

**Comment by feiyun0112** [comment]
@cwsheng 
Create environment variable ASPNETCORE_TEMP for a exists folder
![image](https://user-images.githubusercontent.com/10190938/178430586-c180300f-40e7-4fb6-9544-b0c8b464c497.png)

**Comment by cwsheng** [comment]
@feiyun0112 
This is bypassing the solution and not really solving the problem

**Comment by adityamandaleeka** [comment]
@cwsheng Can you check if `C:\Users\Administrator\AppData\Local\Temp\3\` exists?

It would be interesting to understand where the `\3` is coming from. This is how we retrieve the temp directory: 

https://github.com/dotnet/aspnetcore/blob/6d59f225e132d17cd683259159367ad307dbebaa/src/Http/WebUtilities/src/AspNetCoreTempDirectory.cs#L16-L27

**Comment by feiyun0112** [comment]
@adityamandaleeka 


`3` is terminal session id

@cwsheng 

you can see this url about [temp path](https://docs.microsoft.com/en-us/troubleshoot/windows-server/shell-experience/temp-folder-with-logon-session-id-deleted)

**Comment by adityamandaleeka** [comment]
Ah, thanks @feiyun0112, yea you're right. Apparently this is meant to allow concurrent logins to shared accounts without temp file contention.

**Comment by cwsheng** [comment]
> @cwsheng你能检查是否`C:\Users\Administrator\AppData\Local\Temp\3\`存在吗？
> 
> 了解它的`\3`来源会很有趣。这是我们检索临时目录的方式：
> 
> https://github.com/dotnet/aspnetcore/blob/6d59f225e132d17cd683259159367ad307dbebaa/src/Http/WebUtilities/src/AspNetCoreTempDirectory.cs#L16-L27

When an error is reported, check that the directory no longer exists; It may be caused by the system cleaning up temporary files

**Comment by cwsheng** [comment]
> 



> 

Yes, the system environment is window server, allowing multi account login

**Comment by cwsheng** [comment]
> @adityamandaleeka
> 
> `3` is terminal session id
> 
> @cwsheng
> 
> you can see this url about [temp path](https://docs.microsoft.com/en-us/troubleshoot/windows-server/shell-experience/temp-folder-with-logon-session-id-deleted)

Is this the only way to deal with this problem?

There will be additional operations

**Comment by cwsheng** [comment]
> Ah, thanks @feiyun0112, yea you're right. Apparently this is meant to allow concurrent logins to shared accounts without temp file contention.

Should the framework handle this situation compatibly?

**Comment by adityamandaleeka** [comment]
@cwsheng There's not much we can do in the framework unfortunately. The %TEMP% environment variable doesn't get updated after a process is launched, so if the directory just gets deleted under us we can't do much about it. See [this link](https://docs.microsoft.com/en-us/troubleshoot/windows-server/shell-experience/temp-folder-with-logon-session-id-deleted) for more information.

As @feiyun0112 suggested, setting `ASPNETCORE_TEMP` to a directory that exists (and has the right permissions) is probably the best option.

**Comment by cwsheng** [comment]
I have two more questions:
1. Under what circumstances will temporary files be created to this directory?
2. Why can't I create this directory in the framework?

**Comment by cwsheng** [comment]
> @cwsheng There's not much we can do in the framework unfortunately. The %TEMP% environment variable doesn't get updated after a process is launched, so if the directory just gets deleted under us we can't do much about it. See [this link](https://docs.microsoft.com/en-us/troubleshoot/windows-server/shell-experience/temp-folder-with-logon-session-id-deleted) for more information.
> 
> As @feiyun0112 suggested, setting `ASPNETCORE_TEMP` to a directory that exists (and has the right permissions) is probably the best option.

I have two more questions:
1. Under what circumstances will temporary files be created to this directory?
2. Why can't I create this directory in the framework?

**Comment by adityamandaleeka** [comment]
> Under what circumstances will temporary files be created to this directory?

I'm not sure what you mean here, but the %TEMP% variable is system-wide, and any application might use it as the destination anytime it needs to create a temporary file. In the specific case you posted above, the JSON serializer is writing to a [FileBufferingWriteStream](https://github.com/dotnet/aspnetcore/blob/main/src/Http/WebUtilities/src/FileBufferingWriteStream.cs), and since the size of the JSON data exceeds the memory threshold, it's being written to disk.

> Why can't I create this directory in the framework?

You could create this directory in your own code if you wanted to, though you'd be responsible for ensuring that your creation process doesn't run into any other interactions with how Windows creates/assigns session IDs and creates directories.

**Comment by halter73** [comment]
@adityamandaleeka removing the tag since you reopened this. I assume you don't want it auto-closed again. What is our follow up here?

**Comment by adityamandaleeka** [comment]
I don't think there's any more follow-up... I reopened it just to let the issue remain open for a few days after my answer. Reapplying the tag.
