### ISSUE TITLE
[7.0.100-rc.1.22365.7] Behavior difference when add Authentication in web applications

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/aspnetcore#42808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When testing the 3rd party nopcommerce app with .NET 7 latest build, web page failed to load with exception when passing the empty string for authentication. 

**Application Name** :  nopCommerceNetCore
**OS:** Windows 10 RS5
**CPU:** X64
**.NET Build Number:** dotnet-sdk-7.0.100-rc.1.22365.7

Devdiv Bug checking at:  https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1578709

**Verify Scenarios:**
1). Windows rs5 x64 + dotnet-sdk-7.0.100-rc.1.22365.7: Fail
2). Windows10 RS5 x64+dotnet-sdk-6.0.302-win-x64:Pass
). Windows10 RS5 x64+dotnet-sdk-7.0.100-preview.7.22362.1:Pass

### Expected Behavior

Page will load

### Steps To Reproduce

**Repro steps:**

1) Create Asp.net core web app
2) Add authentication in program.cs

```
builder.Services.AddAuthentication().AddOAuth("oauth", o =>
{

});

```
3) Build and run the app
4) Go to https://localhost:5001/

### Exceptions (if any)

**Actual Result:**
Page does not load with 7.0.100-rc.1.22365.7

**Exception** :
```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMJ9BIT33IRM", Request id "0HMJ9BIT33IRM:00000001": An unhandled exception was thrown by the application.
      System.ArgumentException: The 'CallbackPath' option must be provided. (Parameter 'CallbackPath')
         at Microsoft.AspNetCore.Authentication.RemoteAuthenticationOptions.Validate()
         at Microsoft.AspNetCore.Authentication.OAuth.OAuthOptions.Validate()
         at Microsoft.AspNetCore.Authentication.RemoteAuthenticationOptions.Validate(String scheme)
         at Microsoft.AspNetCore.Authentication.AuthenticationBuilder.<>c__DisplayClass4_0`2.<AddSchemeHelper>b__1(TOptions o)
         at Microsoft.Extensions.Options.ValidateOptions`1.Validate(String name, TOptions options)
         at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
         at Microsoft.Extensions.Options.OptionsCache`1.<>c__3`1.<GetOrAdd>b__3_0(String name, ValueTuple`2 arg)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
         at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd[TArg](String name, Func`3 createOptions, TArg factoryArgument)
         at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
         at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### .NET Version

7.0.100-rc.1.22365.7

### Anything else?

**Findings:**

This code will run fine against .net6 and 7.0.100-preview.7.22362.1, this change in behavior broke nopcommerce app in our lab because we pass empty string for facebook credentials since we don't login with Facebook account.

1) Create Asp.net core web app
2) Install   ```  <PackageReference Include="Microsoft.AspNetCore.Authentication.Facebook" Version="6.0.7" />```
3) In program.cs, add : 
```
builder.Services.AddAuthentication().AddFacebook(facebookOptions =>
{
    facebookOptions.AppId = "";
});
```
4) Build and run the app
5) Go to https://localhost:5001/

**.NET6**

Page will load successfully

**.NET 7.0.100-rc.1.22365.7**

```
      System.ArgumentException: The 'AppId' option must be provided. (Parameter 'AppId')
         at Microsoft.AspNetCore.Authentication.Facebook.FacebookOptions.Validate()
         at Microsoft.AspNetCore.Authentication.RemoteAuthenticationOptions.Validate(String scheme)
         at Microsoft.AspNetCore.Authentication.AuthenticationBuilder.<>c__DisplayClass4_0`2.<AddSchemeHelper>b__1(TOptions o)
         at Microsoft.Extensions.Options.ValidateOptions`1.Validate(String name, TOptions options)
         at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
         at Microsoft.Extensions.Options.OptionsCache`1.<>c__3`1.<GetOrAdd>b__3_0(String name, ValueTuple`2 arg)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
         at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd[TArg](String name, Func`3 createOptions, TArg factoryArgument)
         at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
         at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**dotnet --info**
```
.NET SDK:
Version:   7.0.100-rc.1.22365.7
Commit:    43f10a2ade

Runtime Environment:
OS Name:     Windows
OS Version:  10.0.19043
OS Platform: Windows
RID:         win10-x64
Base Path:   C:\Program Files\dotnet\sdk\7.0.100-rc.1.22365.7\

Host:
  Version:      7.0.0-preview.7.22362.12
  Architecture: x64
  Commit:       b7fca07f47

.NET SDKs installed:
  7.0.100-rc.1.22365.7 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0-rc.1.22364.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0-preview.7.22362.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 7.0.0-rc.1.22363.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

@dotnet-actwx-bot @dotnet/compat

**Comment by Junjun-zhao** [comment]
Yes. It passed on preview 7 build before dotnet-sdk-7.0.100-preview.7.22362.1
dotnet-sdk-7.0.100-preview.7.22358.13： Pass    
dotnet-sdk-7.0.100-preview.7.22362.1: Pass
dotnet-sdk-7.0.100-rc.1.22365.7: Fail
dotnet-sdk-7.0.100-preview.7.22369.2: Fail



> @Junjun-zhao Thanks for reporting this issue! Are you experiencing the same behavior with preview7 by any chance?
> 
> EDIT: At least from what I can tell, this is expected behavior. The required fields that are part of the `RemoteAuthenticationOptions` are not provided in the configureOptions call. Did this work in previous versions?
> 
> It seems strange that it would...

 Yes. It passed on preview 7 build before dotnet-sdk-7.0.100-preview.7.22362.1. Here is the scenario we verified:
dotnet-sdk-7.0.100-preview.7.22358.13: Pass    
dotnet-sdk-7.0.100-preview.7.22362.1: Pass
dotnet-sdk-7.0.100-preview.7.22369.2: Fail
dotnet-sdk-7.0.100-rc.1.22365.7: Fail

**Comment by captainsafia** [comment]
@Junjun-zhao This is an expected breaking change that we have documented in https://github.com/aspnet/Announcements/issues/490.

Moving forward, you'll want to make sure that you actually set options in the callback to `AddFacebook` or `AddOAuth` to avoid these exceptions. 

> this change in behavior broke nopcommerce app in our lab because we pass empty string for facebook credentials since we don't login with Facebook account.

You can disable this behavior by setting the `SuppressAutoDefaultScheme` app context switch if you need to. 

```csharp
AppContext.SetSwitch("Microsoft.AspNetCore.Authentication.SuppressAutoDefaultScheme", false);
```

Closing as we've documented this breaking change now.
