### ISSUE TITLE
error while saving the HTTPS developer certificate (M1 Mac)- security: SecKeychainItemImport: Unknown format in import.

### ISSUE THREAD

**Issue by msteerOC** [dotnet/aspnetcore#42887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Getting an error when running the command:  dotnet dev-certs https  on my M1 Mac.

dotnet dev-certs https -v
[1] Listing certificates from CurrentUser\My
[2] Found certificates: no certificates
[3] Checking certificates validity
[4] Valid certificates: no certificates
[5] Invalid certificates: no certificates
[6] Finished listing certificates.
[1] Listing certificates from CurrentUser\My
[2] Found certificates: no certificates
[3] Checking certificates validity
[4] Valid certificates: no certificates
[5] Invalid certificates: no certificates
[6] Finished listing certificates.
[1] Listing certificates from LocalMachine\My
[2] Found certificates: no certificates
[3] Checking certificates validity
[4] Valid certificates: no certificates
[5] Invalid certificates: no certificates
[6] Finished listing certificates.
[8] Filtered certificates: no certificates
[9] Excluded certificates: no certificates
[0] Event 16 was called with 1 argument(s), but it is defined with 0 parameter(s).
[16] 
[17] Generating HTTPS development certificate.
[18] Finished generating HTTPS development certificate.
[20] Saving certificate '800F5B05A0A6E0C5D42DEB550F166D56C4F7F2BE - CN=localhost - Valid from 2022-07-24 17:34:51Z to 2023-07-24 17:34:51Z - IsHttpsDevelopmentCertificate: true - IsExportable: true' to store CurrentUser\My.
[54] Importing the certificate 800F5B05A0A6E0C5D42DEB550F166D56C4F7F2BE - CN=localhost - Valid from 2022-07-24 17:34:51Z to 2023-07-24 17:34:51Z - IsHttpsDevelopmentCertificate: true - IsExportable: true to the keychain '/Volumes/Crucial 2TB/martinsteer/Library/Keychains/login.keychain-db'.
[56] An error has occurred while importing the certificate to the keychain: 1.
[22] An error has occurred saving the certificate: System.InvalidOperationException: There was an error importing the certificate into the user key chain '800F5B05A0A6E0C5D42DEB550F166D56C4F7F2BE'.

security: SecKeychainItemImport: Unknown format in import.

   at Microsoft.AspNetCore.Certificates.Generation.MacOSCertificateManager.SaveCertificateCore(X509Certificate2 certificate, StoreName storeName, StoreLocation storeLocation)
   at Microsoft.AspNetCore.Certificates.Generation.CertificateManager.SaveCertificate(X509Certificate2 certificate)
   at Microsoft.AspNetCore.Certificates.Generation.CertificateManager.EnsureAspNetCoreHttpsDevelopmentCertificate(DateTimeOffset notBefore, DateTimeOffset notAfter, String path, Boolean trust, Boolean includePrivateKey, String password, CertificateKeyExportFormat keyExportFormat, Boolean isInteractive).

### Expected Behavior

Expected the certificate to be created.

### Steps To Reproduce

1. Install .Net 6 on macOS Monterey 12.4, Apple M1
2. run command, dotnet dev-certs https -v

### Exceptions (if any)

As shown in the bug description

### .NET Version

6.0.302

### Anything else?

dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.302
 Commit:    c857713418

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.4
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.302/

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: arm64
  Commit:       0ec02c8c96

.NET SDKs installed:
  6.0.302 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by adityamandaleeka** [comment]
@msteerOC Does this happen every time for you?

I don't know why it would complain about unknown format.

It looks like you're using a nonstandard HOME directory. One thing that might be worth checking is whether your login keychain is indeed at the path mentioned in the log: '/Volumes/Crucial 2TB/martinsteer/Library/Keychains/login.keychain-db'.

**Comment by msteerOC** [comment]
Yes it's happening every time with the dotnet dev-certs https command, the keystore itself seems to be working fine for other day to day things on the Mac.  You are right that my home directory is in a non standard location (I moved it onto a larger disk when I was migrating to my new M1 Mac), but the keychain file really is at the location mentioned in the log.   I did also try installing Visual Studio 2022 for Mac and created a simple API project, when it runs it notices the certificates are missing and tries to add them, but displays the exact same error I was getting on the command line in my original example.

**Comment by adityamandaleeka** [comment]
I see. It makes sense that VS for Mac hits the same issue since it's doing the same thing under the hood.

Unfortunately, since we can't reproduce this issue on our end yet, the next step I'd do here is to run the tool under a debugger. To reduce the complexity of setting that up with the right symbols and such, I've created a repro project you can use that simulates the same behavior the dev-certs tool does. You can find that here: https://github.com/adityamandaleeka/debug_macos_cert_gen

When run, `debug_macos_cert_gen` should create a certificate, export it to a temp path on disk (and print the path), and finally print a `security import` command for you to run manually.

I suspect that when you run that `security import` command, you will hit the same `security: SecKeychainItemImport: Unknown format in import` error that you see now. If so, we can then use the debugger to investigate where the issue is and narrow it down further.

**Comment by msteerOC** [comment]
Hey @adityamandaleeka, that repo helped solve the problem :).  When I ran it it gave me the following command to run:

`Certificate Path: /var/folders/ck/75zlpl615xz7bbr494ht3ry80000gs/T/tmpjS9MfP.tmp
Run this command to add the certificate to your user keychain. Don't forget to delete it afterwards.` 

`
security import /var/folders/ck/75zlpl615xz7bbr494ht3ry80000gs/T/tmpjS9MfP.tmp -k /Volumes/Crucial 2TB/martinsteer/Library/Keychains/login.keychain-db -t cert -f pkcs12 -P V9tsaShWBy6Kx+AEc8wFDoJcR71mXNtK1mjbHo6rKezt8JQA -A
`

When i tried this, i received the same error that I was getting previously.  But when I put the keychain path in quotes, it went through fine.   So it looks like it was that space in my non-standard home path that was causing the problem.

`security import /var/folders/ck/75zlpl615xz7bbr494ht3ry80000gs/T/tmpjS9MfP.tmp -k "/Volumes/Crucial 2TB/martinsteer/Library/Keychains/login.keychain-db" -t cert -f pkcs12 -P V9tsaShWBy6Kx+AEc8wFDoJcR71mXNtK1mjbHo6rKezt8JQA -A`

`1 identity imported.`   <<<< Success!

I went back to the project where I originally was getting blocked because the certificates couldn't be set, and now it works.  So thank you very much.  

I think this helps identify where the bug is (i.e. the command needs to be formed with quotes around the path if it contains a space), but given that we used the workaround, is there anything else I need to be concerned with in the meantime, or now that the certificate is in place will it be a non-issue for me going forwards?

**Comment by adityamandaleeka** [comment]
@msteerOC That's great to hear, I'm glad you figured it out. I think we should update the dev-certs tool to add quotes around that path. I'll try to get that change in for .NET 7 and backported to 6.

You _should_ be okay for now (the certificate the repro app created is valid for one year from creation) but obviously as soon as you're able to get a fixed version of the tool, I'd clean and re-add the certificate just so you have no state left from a standalone repro app.

**Comment by adityamandaleeka** [comment]
https://github.com/dotnet/aspnetcore/pull/43120 addresses this issue for .NET 7.

**Comment by msteerOC** [comment]
Thanks again @adityamandaleeka, should I close the issue now, or just leave it while the fix is being worked on?

**Comment by adityamandaleeka** [comment]
Leave it open please, we'll use it to track the 6.0 backport as well.

**Comment by danmoseley** [comment]
this can be closed now I guess?

**Comment by adityamandaleeka** [comment]
Yup, thanks @danmoseley
