### ISSUE TITLE
Quarantine EnableCoreHostTraceLogging_PipeCaptureNativeLogs

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#42913]
## Failing Test(s)

- Microsoft.AspNetCore.Server.IIS.FunctionalTests.StdOutRedirectionTests.EnableCoreHostTraceLogging_PipeCaptureNativeLogs(path: "CheckOversizedStdErrWrites")

## Error Message

```text
System.AggregateException : Operation did not succeed after 15 retries (Site is started but no worker process found) (Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot)
---- System.InvalidOperationException : Site is started but no worker process found
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot

```

## Stacktrace

<details>

```text
System.AggregateException : Operation did not succeed after 15 retries (Site is started but no worker process found) (Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot) (Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot)
---- System.InvalidOperationException : Site is started but no worker process found
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot
---- System.InvalidOperationException : Wrong physical path. Expected: C:hwAA5E093D	9dedc03f174249daa3e27243fd0e73e9 Actual: %SystemDrive%inetpubwwwroot


Stack trace
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.WaitUntilSiteStarted(String contentRoot) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 281
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.StartIIS(Uri uri, String contentRoot) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 220
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.DeployAsync() in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 120
   at Microsoft.AspNetCore.Server.IntegrationTesting.FunctionalTestsBase.DeployAsync(IISDeploymentParameters parameters) in /_/src/Servers/IIS/IIS/test/Common.FunctionalTests/Infrastructure/FunctionalTestsBase.cs:line 48
   at Microsoft.AspNetCore.Server.IntegrationTesting.FunctionalTestsBase.RunTest(IISDeploymentParameters deploymentParameters, Action`1 testCode) in /_/src/Servers/IIS/IIS/test/Common.FunctionalTests/Infrastructure/FunctionalTestsBase.cs:line 42
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.StdOutRedirectionTests.EnableCoreHostTraceLogging_PipeCaptureNativeLogs(String path) in /_/src/Servers/IIS/IIS/test/IIS.Shared.FunctionalTests/StdOutRedirectionTests.cs:line 121
--- End of stack trace from previous location ---
----- Inner Stack Trace #1 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<>c__DisplayClass22_0.<WaitUntilSiteStarted>b__0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 244
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
----- Inner Stack Trace #2 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<>c__DisplayClass22_0.<WaitUntilSiteStarted>b__0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 244
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
----- Inner Stack Trace #3 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<>c__DisplayClass22_0.<WaitUntilSiteStarted>b__0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 244
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
----- Inner Stack Trace #4 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<>c__DisplayClass22_0.<WaitUntilSiteStarted>b__0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 244
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
----- Inner Stack Trace #5 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<>c__DisplayClass22_0.<WaitUntilSiteStarted>b__0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 244
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
----- Inner Stack Trace #6 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<>c__DisplayClass22_0.<WaitUntilSiteStarted>b__0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 244
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
----- Inner Stack Trace #7 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<>c__DisplayClass22_0.<WaitUntilSiteStarted>b__0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 244
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
----- Inner Stack Trace #8 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<>c__DisplayClass22_0.<WaitUntilSiteStarted>b__0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 244
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
----- Inner Stack Trace #9 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<>c__DisplayClass22_0.<WaitUntilSiteStarted>b__0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 244
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
----- Inner Stack Trace #10 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<>c__DisplayClass22_0.<WaitUntilSiteStarted>b__0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 244
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
----- Inner Stack Trace #11 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<>c__DisplayClass22_0.<WaitUntilSiteStarted>b__0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 244
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
----- Inner Stack Trace #12 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<>c__DisplayClass22_0.<WaitUntilSiteStarted>b__0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 244
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
----- Inner Stack Trace #13 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<>c__DisplayClass22_0.<WaitUntilSiteStarted>b__0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 244
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
----- Inner Stack Trace #14 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<>c__DisplayClass22_0.<WaitUntilSiteStarted>b__0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 244
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
----- Inner Stack Trace #15 (System.InvalidOperationException) -----
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.<>c__DisplayClass22_0.<WaitUntilSiteStarted>b__0(ServerManager serverManager) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 244
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISDeployer.RetryServerManagerAction(Action`1 action) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/IISDeployer.cs:line 477
```
</details>

## Logs

[StdOutRedirectionTests_EnableCoreHostTraceLogging_PipeCaptureNativeLogs-CheckOversizedStdErrWrites.log](https://github.com/dotnet/aspnetcore/files/9187733/StdOutRedirectionTests_EnableCoreHostTraceLogging_PipeCaptureNativeLogs-CheckOversizedStdErrWrites.log)

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1903233&view=results

**Comment by JamesNK** [comment]
Looks same as https://github.com/dotnet/aspnetcore/issues/42820

**Comment by adityamandaleeka** [comment]
Related: https://github.com/dotnet/aspnetcore/issues/42934
