### ISSUE TITLE
Blazor JSDisconnectedException on page refresh

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#42990]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blazor-JSDisconnectedException-on-page-r/10103391)._

---
[severity:It's more difficult to complete my work]
I have started receiving a JSDisconnectedException on any page reload attempt in a Blazor app.  This occurs from pages with zero JSInterop use - a simple page with just a <p> tag on it will throw this error so I've got nothing to wrap in a try / catch.

I can only see a trace of it while debugging - I can't see any unhandled exceptions in the event log in production and the site refreshes fine.  In debug, it throws multiple times before I can 'continue' the debug session.  The full trace is below but it provides no help in identifying what's causing it.  I've updated all NuGet packages.

Research seems to indicate this is a possible result of another exception that's causing the connection to terminate however I can attempt to refresh a page with nothing on it and it'll happen so there is no user written code that's throwing the exception on the component itself.
   
   
```
at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId) in /_/src/Components/Server/src/Circuits/RemoteJSRuntime.cs:line 122
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args) in /_/src/JSInterop/Microsoft.JSInterop/src/JSRuntime.cs:line 132
   at Microsoft.JSInterop.JSRuntime.d__16`1.MoveNext() in /_/src/JSInterop/Microsoft.JSInterop/src/JSRuntime.cs:line 91
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 56
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 181
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 149
   at System.Threading.Tasks.ValueTask`1.get_Result() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/ValueTask.cs:line 785
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/ValueTaskAwaiter.cs:line 126
   at Microsoft.JSInterop.JSObjectReferenceExtensions.d__0.MoveNext() in /_/src/JSInterop/Microsoft.JSInterop/src/JSObjectReferenceExtensions.cs:line 32
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 56
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 181
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/TaskAwaiter.cs:line 149
   at System.Runtime.CompilerServices.ValueTaskAwaiter.GetResult() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/ValueTaskAwaiter.cs:line 44
   at Blazorise.Modules.JSButtonModule.d__2.MoveNext()
```

---
#### Feedback Bot on 7/25/2022, 07:50 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. It feels like you've configured the debugger to break on a specific type of exception, which Blazor does indeed throw internally, but it also catches it (as it's expected). As a result, your application runs just fine but when debugging, it breaks on these intermittent exceptions.

**Comment by javiercn** [comment]
This seems to be a problem inside Blazorize that doesn't account for Server scenarios where the connection gets disconnected.
