### ISSUE TITLE
Conditionally add web host

### ISSUE THREAD

**Issue by dferretti** [dotnet/aspnetcore#43008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to ConfigureWebHost, but only if the host's app config indicates it should do so. However, ConfigureWebHost must be called earlier in the setup process, before any app configuration is available.

I found this locked issue from a few years ago: https://github.com/dotnet/aspnetcore/issues/22079

### Describe the solution you'd like

Like the linked issue asks, making `GenericWebHostService` public could help, but it still needs configuration.

I would like to be able to do something like this:
```c#
Host.CreateDefaultBuilder()
    .ConfigureServices((ctx, services) =>
    {
        if (ctx.Configuration ... some condition)
            services.AddWebHost(webHostBuilder => ...);
    });
```

### Additional context

Not thinking it would actually work, but I did try
```c#
var builder = Host.CreateDefaultBuilder();
builder.ConfigureServices((ctx, services) =>
{
    if (...)
        builder.ConfigureWebHost(webHostBuilder => ...);
});
```
but that results in 
```
Unhandled exception. System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
```
I have not dug all the way in yet, but this leads me to believe that `ConfigureWebHost` is not just adding a normal IHostedService, but adding some other callbacks to the host builder that modify the config/service callback lists out of the normal order.

This is in net6.0

**Comment by halter73** [comment]
> I have not dug all the way in yet, but this leads me to believe that ConfigureWebHost is not just adding a normal IHostedService, but adding some other callbacks to the host builder that modify the config/service callback lists out of the normal order.

It's a bad idea to call `IHostBuilder` extension method during or after the call to `Build()`, and this is during `Build()`. `ConfigureWebHost` adding more `ConfigureServices` callbacks to the list of callbacks while the builder is enumerating the list is the proximate cause of the `InvalidOperationException`.

However, you are right that there is a more fundamental ordering issue with doing something like `ConfigureWebHost` so late in the build process. `ConfigureWebHost` adds ASPNET_`-prefixed environment variables as a "host" configuration source. It's this configuration that's passed to the `ConfigureServices` callback via the `HostBuilderContext` (and even earlier to any `ConfigureAppConfiguration` callback), so it's too late for `ConfigureWebHost` to do this.

This means that any other libraries or frameworks that do `if (ctx.Configuration ... some condition)` expecting those conditions to be influenced by `ASPNET_`-prefixed environment variables would be broken if someone only called the proposed `services.AddWebHost(...)` API. I don't want to go down the road of having different ways to create an `IWebHostBuilder` that have this kind of subtle difference in config loading.

Could you instead create a `new ConfigurationBuilder()` or `new ConfigurationManager()` yourself and add whatever default configuration sources from environment variables, appsettings.json or whatever other configuration sources your app uses by manually adding those configuration sources to your own builder? Then you could read configuration before you end up inside the a `ConfigureServices` callback.

**Comment by halter73** [comment]
> ```
> Unhandled exception. System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
>    at System.Collections.Generic.List`1.Enumerator.MoveNext()
>    at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
>    at Microsoft.Extensions.Hosting.HostBuilder.Build()
> ```

We might be able to improve the exception regardless. These days, we'd probably point most people to `WebApplicationBuilder` and `HostApplicationBuilder` instead of the generic host, but the generic host is still very much supported and this is a sharp corner. It's not super obvious that you cannot call `IHostBuilder` APIs once you're already in `ConfigureServices()` and similar methods, and exceptions like these don't effectively point out the problem.

**Comment by dferretti** [comment]
Ah yeah I can see how I was essentially calling ConfigureServices from within a ConfigureServices callback, which is not good. Agreed that touching the host builder at all within any of those config/service callbacks is a bad idea.

The project I am working on is built around the generic host, so I was trying to plug in to the existing host config -> app config -> dependency injection sort of pipeline. I could manually rebuild my config sources but it does sort of feel like re-implementing the generic host. That might be the best way forward though.

I do see how the concept of adding the web host is more than just a hosted service, it is host config and app config and a hosted service, from [here](https://github.com/dotnet/aspnetcore/blob/773e8cc3fbdc2c4ffbd57c1f53f21649ef94c35c/src/Hosting/Hosting/src/GenericHost/GenericWebHostBuilder.cs#L23). In my head I see those as 3 building blocks of the web host, and ConfigureWebHost is a convenience method that adds all 3. Maybe they could all be exposed so a library could take responsibility of replicating the config steps and choosing to call the configureservices step manually. But I see what you mean that would not be a pit of success if users or libraries call it without properly setting up the config.

**Comment by halter73** [comment]
> But I see what you mean that would not be a pit of success if users or libraries call it without properly setting up the config.

That is what I'm worried about. I don't want to make it too easy to get a `GenericWebHostBuilder` that's not configured properly.

> The project I am working on is built around the generic host, so I was trying to plug in to the existing host config -> app config -> dependency injection sort of pipeline. I could manually rebuild my config sources but it does sort of feel like re-implementing the generic host. That might be the best way forward though.

Getting the default configuration sources can be somewhat difficult. If you just want hosting's default configuration sources (minus the web host's `ASPNETCORE_` environment variables), I think your best bet is to just build a host, read whatever config you want out of it, dispose it, and then build another host with or without the generic web host based on that config.

The chicken-and-egg problem here is that the web host affects what the default configuration sources are. Would an extension method in Microsoft.Extensions.Hosting for `IConfigurationBuilder` like `AddDefaultHostingConfigruationSources()` be useful so you wouldn't have to create an entire host just to read the default config?

**Comment by dferretti** [comment]
Chicken-and-egg is a good way to describe this. I am sold on the idea of rebuilding the config manually - and I think `AddDefaultHostingSources` would be a very nice way of doing that cleanly. I like the idea!

**Comment by halter73** [comment]
I've updated this issue with an API proposal and I'm moving this to the runtime repo which is where `AddDefaultHostingSources()` would be added if we decide to do it. We're pretty late in .NET 7 development, so I wouldn't expect anything to happen here until .NET 8.
