### ISSUE TITLE
Quarantine GET_MultipleRequests_RequestVersionOrHigher_UpgradeToHttp3

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#43069]
## Failing Test(s)

- Interop.FunctionalTests.Http3.Http3RequestTests.GET_MultipleRequests_RequestVersionOrHigher_UpgradeToHttp3

## Error Message

```text
System.Net.Http.HttpRequestException : The server is currnetly unreachable. (127.0.0.1:49418)
---- System.Net.Quic.QuicException : The server is currnetly unreachable.
```

(sidenote: there's a typo in that message)

## Stacktrace

<details>

```text
   at System.Net.Http.ConnectHelper.ConnectQuicAsync(HttpRequestMessage request, DnsEndPoint endPoint, TimeSpan idleTimeout, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp3ConnectionAsync(HttpRequestMessage request, HttpAuthority authority, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Interop.FunctionalTests.Http3.Http3RequestTests.GET_MultipleRequests_RequestVersionOrHigher_UpgradeToHttp3() in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/Http3/Http3RequestTests.cs:line 746
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data)
   at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent)
   at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)
--- End of stack trace from previous location ---
   at System.Net.Quic.ValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Quic.QuicConnection.FinishConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken)
   at System.Net.Quic.QuicConnection.ConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken)
   at System.Net.Quic.QuicConnection.ConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectQuicAsync(HttpRequestMessage request, DnsEndPoint endPoint, TimeSpan idleTimeout, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken)
```
</details>

## Build

- https://dev.azure.com/dnceng/public/_build/results?buildId=1917664&view=ms.vss-test-web.build-test-results-tab&runId=49692788&resultId=109720

**Comment by SteveSandersonMS** [comment]
Apparently not flaky: https://github.com/dotnet/aspnetcore/pull/43070#pullrequestreview-1060189149
