### ISSUE TITLE
System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed

### ISSUE THREAD

**Issue by OldManMeta** [dotnet/aspnetcore#43083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Developing in net6.0

I see this exception multiple times on the deployed solution in Azure, but see no issues in local development machines.

Searching for days - it looks like a previous issue in the way async calls were handled, means that the AWAIT statement almost doesn't work correctly anymore?

Compared with Core3.1 - I could call async methods from my constructors by appending the ConfigureAwait(false) flag to run - but that has absolutely no effect in Core6 - logically it makes sense why that was a poor design choice.

After redesigning every constructor - code in each class now calls the methods that were once executed in the constructor.

The error here states that "A second operation was started on this context instance before a previous operation completed" - if AWAIT is working correctly - I am telling you that this is quite literarily impossible in my code base.

All of the methods are async - so they should have no issues - every single async call is an awaited statement through all of my code bodies.

Async methods that do not return from further async calls return in this type of syntax:
`return await Task.FromResult<SortedDictionary<int, List<BaseNavigationItem>>>(Structure);`

This error(s) shows in my azure logs are intermittent:

`Category: Microsoft.EntityFrameworkCore.Query
EventId: 10100
SpanId: c5781d15ac6fcdc4
TraceId: 389ccc891ca0ad905436cfb87a2223b8
ParentId: 0000000000000000
RequestId: 80001daf-0000-d000-b63f-84710c7967bb
RequestPath: /domains/v1/domainsearch/domains/search
ActionId: bc4d2d7e-a479-4a35-a7ec-557821266d25
ActionName: IMP.Portal.Controllers.Domains.v1.DomainsController.domainsearch (IMP.Portal)

An exception occurred while iterating over the results of a query for context type 'IMP.Data.Account.Data.AccountDbContext'.
System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

Exception: 
System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()`

Perhaps my understanding is wrong, or the usage is changed - I would be thrilled if the answer is simple and it is my mistake.
Many thanks any guidance here.

 

### Expected Behavior

My expectation is that async methods called with the AWAIT keyword, execute the method completely, before returning the execution of the calling thread.

### Exceptions (if any)

Category: Microsoft.EntityFrameworkCore.Query
EventId: 10100
SpanId: 26c5a189456f3711
TraceId: 24da3e85238ce5b0366fd47433180986
ParentId: 0000000000000000
RequestId: 80003890-0000-da00-b63f-84710c7967bb
RequestPath: /
ActionId: 0eea45ff-d3ec-4e82-a1ba-3a5bec8a6bf4
ActionName: IMP.Portal.Controllers.IMZone.v1.IMZoneController.IMZoneHome (IMP.Portal)

An exception occurred while iterating over the results of a query for context type 'IMP.Data.Account.Data.AccountDbContext'.
System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

Exception: 
System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

### .NET Version

6.0

### Anything else?

.NET SDK (reflecting any global.json):
 Version:   6.0.302
 Commit:    c857713418

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.302\

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

.NET SDKs installed:
  3.1.421 [C:\Program Files\dotnet\sdk]
  5.0.407 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.107 [C:\Program Files\dotnet\sdk]
  6.0.301 [C:\Program Files\dotnet\sdk]
  6.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by javiercn** [comment]
@OldManMeta thanks for contacting us.

I am going to assume you are using Blazor, even if not, the same guidance applies.

Unfortunately, that is not how async/await works in general. `await` is only a way to queue a callback when a task completes, but it does not prevent multiple calls to be issued in the first place. What is likely happening is that several of your components are injecting the same DBContext instance, issuing a query and that is what is triggering the issue.

Blazor components will render in parallel (which is not concurrently) so other work can happen while a component is waiting on async work to complete.

You can read more about how to work with Entity Framework in Blazor here:
https://docs.microsoft.com/en-us/aspnet/core/blazor/blazor-server-ef-core?view=aspnetcore-6.0

**Comment by OldManMeta** [comment]
Hi @javiercn thank you for your response.

No - this is not Blazor. Just good old fashioned asp.net MVC

This is how I read it -

The await operator **suspends** evaluation of the **enclosing** [async] **method** until the asynchronous operation represented by its operand completes.

When the asynchronous operation completes, the await operator returns the result of the operation, if any.

Taken from the c# reference here: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/await

So to visualise this:

![async-execution](https://user-images.githubusercontent.com/107874035/182809806-c5927306-66b8-482a-9a33-ed51d310acd6.jpg)

Am I completely incorrect here?

Thank you so much for your help in clarifying this.

**Comment by davidfowl** [comment]
Sure that makes sense but its possible you have some subtle bug or maybe there's other code running that's you don't realize that may be causing this issue.

**Comment by OldManMeta** [comment]
@davidfowl - thanks for verifying - while I would hope this is a bug of my doing, and I'm certainly willing to put my hand up here - I've traced every line through this code base as it is relatively small. I do not see how that would be happening.

The only other avenue here is that I see this only on the Azure instance, not on local dev machines. This is deployed by Dev Ops - I see no settings or details to suggest that synchronization has changed etc.

I've redeployed again this afternoon and will keep an eye on it. If it continues, I will do my best to get a repro together.

I'll close this in a day or two if I see no further issues.

Many thanks.

**Comment by javiercn** [comment]
@OldManMeta thanks for the additional details.

This is then more likely something in your code that is causing this. There are generally two reasons for this to happen:
* You are issuing a call to EF that is not being awaited and you try to initiate another call in parallel while the first one is ongoing.
* This can also happen, I believe, if you have more than one IAsyncEnumerable or similar that you are trying to enumerate simultaneously with other things that query the DB. Up until the IAsyncEnumerable does not start to get enumerated the query is not executed.

I am going to pass this to the EF folks as they can give you better guidance.
