### ISSUE TITLE
Error in new componet in blazor

### ISSUE THREAD

**Issue by jafarpoor** [dotnet/aspnetcore#43127]
helloo 
in write a new component with radzen
but i have error 
```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Value cannot be null. (Parameter 'source')
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[FinYearViewModel,Int64](IEnumerable`1 source, Func`2 selector)
   at TM.FinanceWebApp.Client.Shared.Component.TMDropDown.BuildRenderTree(RenderTreeBuilder __builder) in C:\FinanceWebApp1401\TM.FinanceWebApp\Client\Shared\Component\TMDropDown.razor:line 18
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```

```
@inject RegionServices RG
@using Radzen
@inject FinYearServices  finYearServices
@inject HttpClient Http


    @if (Type =="Region")
{
     <RadzenDropDown AllowClear="true" AllowFiltering="true" FilterCaseSensitivity="FilterCaseSensitivity.CaseInsensitive"
                            TValue="string" Placeholder="Select..." Data=@(regionViewModel.Select(c=>c.RegionName).Distinct()) TextProperty="RegionName" ValueProperty="RegionCode"
                                 Style="width:100%" />
}

else if(Type =="FinYear")
{
          <RadzenDropDown AllowClear="true" AllowFiltering="true" FilterCaseSensitivity="FilterCaseSensitivity.CaseInsensitive"
                                TValue="long"   Placeholder="Select..." Data=@(finYearViewModel.Select(c=>c.FinYearCode)) TextProperty="FinYearCode" ValueProperty="FinYearCode"
                                 Style="width:100%" />
    
}
else
{
    <RadzenDropDown  Multiple="false"  AllowClear="true" AllowFiltering="true" FilterCaseSensitivity="FilterCaseSensitivity.CaseInsensitive"
                                TValue="long"  Placeholder="Select..." Data=@(finYearViewModel.Select(c=>c.FinYearCode)) TextProperty="FinYearCode" ValueProperty="FinYearCode"
                                 Style="width:100%" />
}



@code {


    private  IList<RegionViewModel> regionViewModel;
    private IList<FinYearViewModel> finYearViewModel;

    [Parameter]
    public string Type { get; set; }

    protected override async Task OnInitializedAsync()
    {
        if (Type =="Region")
        {
              var urlRegion = "api/Common/GetAllRegion";
            regionViewModel = await this.Http.GetFromJsonAsync<RegionViewModel[]>(urlRegion);
        }
        else if (Type =="FinYear")
        {
            var urlFinYear = "api/Accounting/GetAllFinYear";
            finYearViewModel =   await finYearServices.GetAll(urlFinYear);
        }
    }

}

```

user in index

   <TMDropDown Type="FinYear" ></TMDropDown>

where is problme ?????????????

**Comment by javiercn** [comment]
@jafarpoor thanks for contacting us.

You very likely have a null reference exception in this area

```
    @if (Type =="Region")
{
     <RadzenDropDown AllowClear="true" AllowFiltering="true" FilterCaseSensitivity="FilterCaseSensitivity.CaseInsensitive"
                            TValue="string" Placeholder="Select..." Data=@(regionViewModel.Select(c=>c.RegionName).Distinct()) TextProperty="RegionName" ValueProperty="RegionCode"
                                 Style="width:100%" />
}

else if(Type =="FinYear")
{
          <RadzenDropDown AllowClear="true" AllowFiltering="true" FilterCaseSensitivity="FilterCaseSensitivity.CaseInsensitive"
                                TValue="long"   Placeholder="Select..." Data=@(finYearViewModel.Select(c=>c.FinYearCode)) TextProperty="FinYearCode" ValueProperty="FinYearCode"
                                 Style="width:100%" />
    
}
else
{
    <RadzenDropDown  Multiple="false"  AllowClear="true" AllowFiltering="true" FilterCaseSensitivity="FilterCaseSensitivity.CaseInsensitive"
                                TValue="long"  Placeholder="Select..." Data=@(finYearViewModel.Select(c=>c.FinYearCode)) TextProperty="FinYearCode" ValueProperty="FinYearCode"
                                 Style="width:100%" />
}
```

You'll have to debug through your code to identify what is null. Another thing that might help is to turn breaking on first chance exceptions.
