### ISSUE TITLE
System.NullReferenceException at Microsoft.AspNetCore.Http.DefaultHttpRequest.get_Cookies()

### ISSUE THREAD

**Issue by czd890** [dotnet/aspnetcore#43155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Sometime I got the error System.NullReferenceException at Microsoft.AspNetCore.Http.DefaultHttpRequest.get_Cookies() for several GET API.

### Exceptions (if any)

```json
{
    "exception": {
        "Type": "System.NullReferenceException",
        "TargetSite": "Microsoft.AspNetCore.Http.IRequestCookieCollection get_Cookies()",
        "Message": "Object reference not set to an instance of an object.",
        "Data": {},
        "Source": "Microsoft.AspNetCore.Http",
        "HResult": -2147467261,
        "StackTrace": "   at Microsoft.AspNetCore.Http.DefaultHttpRequest.get_Cookies()"
    }
}

```

### .NET Version

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base

### Anything else?
StackTrace:
```
at Microsoft.AspNetCore.Http.DefaultHttpRequest.get_Cookies()
at MyCode.DoWorkAsync
at MyHealthCheckCode.CheckHealthAsync
at Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService.RunCheckAsync(HealthCheckRegistration registration, CancellationToken cancellationToken)
```

```
services.AddScoped<MyCode>();
services.AddHealthChecks().AddCheck<MyHealthCheckCode>()

MyHealthCheckCode:IHealthCheck
{
    ctor(MyCode mycode){}
public async Task<HealthCheckResult> CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken = default) => await mycode.DoWorkAsync();
}

MyCode(IHttpContextAccessor accessor)
{
     Task DoWorkAsync(){
         accessor.HttpContext..Request.Cookies.....
         //  other codes
    }
}
```

**Comment by davidfowl** [comment]
See https://github.com/dotnet/aspnetcore/issues/42040 for why this happens.

**Comment by czd890** [comment]
@davidfowl "HttpContext is accessed concurrently" makes sense. 
Health checks are run concurrently.

https://github.com/dotnet/aspnetcore/blob/50aa2fd929750ff4e46df0150d96fbbb7788e5d0/src/HealthChecks/HealthChecks/src/DefaultHealthCheckService.cs#L54-L57

**Comment by davidfowl** [comment]
Perfect! What is your health check checking?
