### ISSUE TITLE
Error: "The entity type 'DataProtectionKey' requires a primary key" when using .Net 7 previews

### ISSUE THREAD

**Issue by Webreaper** [dotnet/aspnetcore#43187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have implemented `DataProtectionKey` storage using an EFCore DB context, and it has been working fine for nearly a year. 

In June, I upgraded my application to .Net 7 preview 5 and EFCore 7 preview 5, and now see the following exception:

```Migrations failed with exception: System.InvalidOperationException: The entity type 'DataProtectionKey' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943.```

The webserver then terminates within `IHost.Run` with the following (similar) exception:

```
[22:03:19.707-0001-INF] Damselfly Webserver terminated with exception: The entity type 'DataProtectionKey' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943.
```

I am using the SQLite DB provider.

This only happens on Linux (deployed in an Ubuntu docker container). If I run the same code, against the same .db file, on OSX, the migrations complete without issue. I have not tried Windows.

The error suggests using the `[Keyless]` attribute to resolve this error, but I don't know enough about `DataProtectionKey`s to know if it would cause any issues. 

Note that the problem persists with .Net 7 preview 6 and EFCore preview 6.

### Expected Behavior

The expected behaviour is that the `db.Database.Migrate();` call completes without issue and the application starts normally.
 

### Steps To Reproduce

I declare my `DataProtectionKeys` in my `DbContext` here: https://github.com/Webreaper/Damselfly/blob/develop/Damselfly.Core/Models/ImageContext.cs#L43

```        public DbSet<DataProtectionKey> DataProtectionKeys { get; set; }```

I add configure the DataProtection here: https://github.com/Webreaper/Damselfly/blob/master/Damselfly.Web/Startup.cs#L73

```            services.AddDataProtection().PersistKeysToDbContext<ImageContext>();```

I can't find anywhere in the documentation that suggests I need to do something explicit to create a key.

The DataProtectionKeys were added in 2021, in this Migration: https://github.com/Webreaper/Damselfly/blob/master/Damselfly.Migrations.Sqlite/Migrations/20210922112630_AddDataProtectionKeys.cs:

```
   modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FriendlyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Xml")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });
```

### Exceptions (if any)

```
Migrations failed with exception: System.InvalidOperationException: The entity type 'DataProtectionKey' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'. For more information on keyless entity types, see https://go.microsoft.com/fwlink/?linkid=2141943.
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNonNullPrimaryKeys(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Sqlite.Infrastructure.Internal.SqliteModelValidator.Validate(IModel model, IDiagnosticsLogger`1 logger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelRuntimeInitializer.Initialize(IModel model, Boolean designTime, IDiagnosticsLogger`1 validationLogger)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite, RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite, TArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite, RuntimeResolverContext, ServiceProviderEngineScope, RuntimeResolverLock)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite, RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite, TArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite, RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite, TArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite, RuntimeResolverContext, ServiceProviderEngineScope, RuntimeResolverLock)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite, RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite, TArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite, RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite, TArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite, RuntimeResolverContext, ServiceProviderEngineScope, RuntimeResolverLock)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite, RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite, TArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite, RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite, TArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite, RuntimeResolverContext, ServiceProviderEngineScope, RuntimeResolverLock)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite, RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite, TArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite, RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite, TArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite, RuntimeResolverContext, ServiceProviderEngineScope, RuntimeResolverLock)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite, RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite, TArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite, RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite, TArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite, RuntimeResolverContext, ServiceProviderEngineScope, RuntimeResolverLock)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite, RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite, TArgument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type, ServiceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider, Type)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider)
```

### .NET Version

.Net 7 preview 5 and preview 6

### Anything else?

The issue only happens when running the containerised deployment on Linux. Running exactly the same code on OSX works fine.

**Comment by ajcvickers** [comment]
Transferring this back to ASP.NET since this is not an issue in EF.

**Comment by Webreaper** [comment]
@ajcvickers is there an issue to track the trimming support improvements that @roji mentions above? Would be good to link them here - and I'd like to track so that I can remove the `HasKey` call from my code when they're available.

**Comment by ajcvickers** [comment]
@Webreaper Trimming improvements for EF Core are unlikely to have an impact on this, at least in short to medium term. EF Core knows nothing of `DataProtectionKey`.

**Comment by Webreaper** [comment]
Oh, yes - good point. Presumably it's up to the identity/aspnetcore folks to decorate it appropriately. Or something. 

Although since it's clearly declared as a key where it's defined, I was assuming that @roji was talking about doing some magic to automatically do that for any entity... :) <hand-wavey magic>

**Comment by ajcvickers** [comment]
> Although since it's clearly declared as a key where it's defined

Where is is clearly declared as a key?

**Comment by Webreaper** [comment]
> Where is is clearly declared as a key?

Dammit, you got me. I'd assumed it was..... But apparently not: https://github.com/dotnet/aspnetcore/blob/main/src/DataProtection/EntityFrameworkCore/src/DataProtectionKey.cs#L14

Presumably, if they explicitly decorated that with `[Key]` the problem wouldn't happen?

**Comment by ajcvickers** [comment]
@Webreaper That would not help unless anything attributed with `[Key]` in any library is not trimmed, which I doubt is the case.

**Comment by Webreaper** [comment]
Ah, okay. Is there a way to make it so that something decorated with `[Key]` automatically gets `DynamicDependency` applied? (I'm hand-waving again here, as I haven't delved into the trimming hints decorators). But you get my drift?

**Comment by ajcvickers** [comment]
That's not something I can answer.

**Comment by roji** [comment]
This is all something I'm planning to explore, though I don't think keys should be handled in a special way here: basically public properties on entity types shouldn't get trimmed, we should be able to do that by annotating modelBuilder.Entity, DbSet<>, etc.

**Comment by JamesNK** [comment]
The problem here is nothing in the DataProtection EntityFramework library references `DataProtectionKey.Id`.

There are two solutions:
1. DataProtection EntityFramework dynamically includes `DataProtectionKey.Id`.
2. EntityFramework adds annotations to prevent properties from being trimmed from entities. e.g. `DbSet.Add` (and other methods EF methods) adds `[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicProperties)]`.

Number 2 is more complicated, but it's the better fix. Because EntityFramework isn't annotated, all trimmed libraries that use EF are going to have to ensure entities aren't trimmed manually (i.e. fix number 1). Ideally, EF should be annotated to do it for you.

Here is a fix (number 1) for DataProtection EntityFramework - https://github.com/dotnet/aspnetcore/pull/43204

**Comment by Webreaper** [comment]
Awesome. Thanks James!
