### ISSUE TITLE
OperationCanceledException thrown from Microsoft.IdentityModel.Protocols.ConfigurationManager.GetConfigurationAsync while trying to get Jwt tokens

### ISSUE THREAD

**Issue by barnopriyo-barua** [dotnet/aspnetcore#43220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We are seeing a bunch of OperationCancelledException in some machines while trying to get the Jwt tokens. When the issue starts, a few machines start getting this error continuously - and restarting the service in the machines mitigate the issue. Here's the stack trace:

``Exception:System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.SemaphoreSlim.<WaitUntilCountOrTimeoutAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__6.MoveNext()``

The code takes a lot of time inside GetConfigurationAsync, and timeout is enforced by our gateway. Since gateway cancels in 90sec, around that time we see an OperationCancelled. So, I believe the root cause we need to find out is why is it spending all that time inside GetConfigurationAsync.

### Exceptions (if any)

Exception:System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.SemaphoreSlim.<WaitUntilCountOrTimeoutAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__6.MoveNext()

### .NET Version

.NET Framework 4.6.2, ASP.NET Core version 2.2

**Comment by Tratcher** [comment]
Discussed offline. The issue was the site receiving lots of traffic just after starting and requests starving on this lock. The mitigation is to pre-init and load the ConfigurationManager during startup.
