### ISSUE TITLE
src/security/samples/StaticFilesAuth always not working 

### ISSUE THREAD

**Issue by hylinux** [dotnet/aspnetcore#43274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi, When I tried to run the sample in : src/Security/Sampels/StaticFilesAuth, look  like it was broken.  would you help us take a look?

when I tried to run the sample,  after login, access the url: /https://localhost:5001/MapAuthenticatedFiles

it willreport Exception:

```Exception
System.InvalidOperationException: The request reached the end of the pipeline without executing the endpoint: '/'. Please register the EndpointMiddleware using 'IApplicationBuilder.UseEndpoints(...)' if using routing.
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.<>c.<Build>b__18_0(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.DirectoryBrowserMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.DefaultFilesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

I tried to debug into.
I found it will jump here:

```csharp
      app.Map("/MapAuthenticatedFiles", branch =>
        {
            branch.Use((context, next) => { SetFileEndpoint(context, files, null); return next(context); });
            branch.UseAuthorization();
            SetupFileServer(branch, files);
        });
```

the werid thing is: it will run into branch.Use( (context, next) => {} ), and then the pipeline was end, will not go through 

```csharp
           branch.UseAuthorization();
            SetupFileServer(branch, files);
```

would you help to take a look?

thanks

### Expected Behavior

it should work success

### Exceptions (if any)

System.InvalidOperationException: The request reached the end of the pipeline without executing the endpoint: '/'. Please register the EndpointMiddleware using 'IApplicationBuilder.UseEndpoints(...)' if using routing.
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.<>c.<Build>b__18_0(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.DirectoryBrowserMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.DefaultFilesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

### .NET Version

6.0.400

**Comment by adityamandaleeka** [comment]
@Tratcher can you please take a look?

**Comment by Tratcher** [comment]
This was regressed by https://github.com/dotnet/aspnetcore/commit/a0513eaa475e21bfbe3f3256d3ef5b27aef61588#diff-794cdf47625f76680985628eb02bc4a94ec6952dd4c468ec5d9e7ce672cebdb8.

The sample could probably be updated to take advantage of this change. I'll look into it more.

Workaround:
Add this to the start of Startup.SetupFileServer.
```
        builder.Use((context, next) => { context.SetEndpoint(null); return next(context); });
```
