### ISSUE TITLE
[7.0.100-rc.1.22413.1] Setting the header Content-Length is not allowed on responses with status code 204 Error in asp.net apps

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/aspnetcore#43316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

During our 3rd Party App Compatibility testing, some cases failed because of this error (StatusCode cannot be set because the response has already started.), We have seen this issue in 4 web applications, we think this is related to Kestrel, issue does not repro when we launch the app with IISExpress via VS.  

1) It is related to "C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\7.0.0-rc.1.22412.2\Microsoft.AspNetCore.Server.Kestrel.Core.dll"
2) It might be caused by this PR https://github.com/dotnet/aspnetcore/pull/43103

**Application Name**: OqtaneFramework(3.0.3), QuickApp, EventStore,mixcore
**OS**: Windows 10 RS5
**CPU**: X64
**.NET Build Number:** dotnet-sdk-7.0.100-rc.1.22413.1
**Github Link**: https://github.com/oqtane/oqtane.framework/releases/tag/v3.0.3 
**App checking at** : https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1593251/

**Verify Scenarios:**
1). Windows10 RS5 x64+dotnet-sdk-7.0.100-rc.1.22413.1: Fail
2). Windows10 RS5 x64+dotnet-sdk-7.0.100-rc.1.22408.5: Pass
3). Windows10 RS5 x64+dotnet-sdk-6.0.303-win-x64: Pass

### Expected Behavior

It should save the new user

### Steps To Reproduce

**The machine only has 7.0 installed. And DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX=2 is set.**

1. Launch Oqtane.Server.exe
2. Go to https://localhost:5001/
3. Fill required info: username,password, email (any data is OK, this step will create database)
4. Login to app with created username => https://localhost:5001/login
5. Go to https://localhost:5001/admin/users
6. Click Add User
7. Fill information and Save

### Exceptions (if any)

Save Failed
![image](https://user-images.githubusercontent.com/83067197/184843605-2676ad99-87ea-424a-b31b-8c602b6d5871.png)
**Exception:**
```
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Oqtane.Controllers.UserController.Get (Oqtane.Server)'
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMJVC2GF9M66", Request id "0HMJVC2GF9M66:00000001": An unhandled exception was thrown by the application.
      System.InvalidOperationException: Setting the header Content-Length is not allowed on responses with status code 204.
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Connection processing ended abnormally.
      System.InvalidOperationException: StatusCode cannot be set because the response has already started.
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowResponseAlreadyStartedException(String value)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.set_StatusCode(Int32 value)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.SetErrorResponseHeaders(Int32 statusCode)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.CreateResponseHeaders(Boolean appCompleted)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProduceEnd()
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST https://localhost:5001/api/Log application/json;+charset=utf-8 -
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]

```

### .NET Version

7.0.100-rc.1.22413.1

### Anything else?

```
C:\h\w\AE710988\p>dotnet --info
.NET SDK:
 Version:   7.0.100-rc.1.22413.1
 Commit:    fd587269d0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-rc.1.22413.1\

Host:
  Version:      7.0.0-rc.1.22411.12
  Architecture: x64
  Commit:       f52d8c59bb

.NET SDKs installed:
  7.0.100-rc.1.22413.1 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0-rc.1.22412.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0-rc.1.22411.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 7.0.0-rc.1.22379.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

```
@dotnet-actwx-bot @dotnet/compat

**Comment by Tratcher** [comment]
>  System.InvalidOperationException: Setting the header Content-Length is not allowed on responses with status code 204.

This is expected, kestrel was recently hardened to more closely match the spec for 204's. Do we know what applications were setting the header to? Why are they attempting to provide a body here?

> System.InvalidOperationException: StatusCode cannot be set because the response has already started. 

This is not expected. The new error above might be thrown after setting the response headers to read-only, so the exception handling code path throws again when trying to set a 500. We should fix this.

**Comment by blowdart** [comment]
At a guess https://www.oqtane.org/, given the exe name

**Comment by Tratcher** [comment]
Repro code:
```
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication21
{
    [Route("api")]
    [ApiController]
    public class HttpResultController : ControllerBase
    {
        [HttpGet, Route("Http204")]
        public ResponseResult Http204()
        {
            return null;
        }
    }

    public class ResponseResult
    {
        public bool IsError { get; set; }
        public string ResultValue { get; set; }
        public DateTime Timestamp { get; set; } = DateTime.UtcNow;
    }
}
```

There's no custom framework here, just MVC. What in MVC converts a null result into a NoContent result, and why does MVC set CL: 0 for a NoContent result?

**Comment by adityamandaleeka** [comment]
We should do these in RC 1 since there's a compat issue:

> A) MVC shouldn't do this, it's invalid.
B) Kestrel should accept & remove Content-Length: 0 headers for 204, it's semantically equivalent.

We should also avoid getting to `Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowResponseAlreadyStartedException` in this case. This can wait until after RC 1 (it's just an extra exception in a failure case).

**Comment by adityamandaleeka** [comment]
Addressed in RC1 in #43360 and #43417 . Moving to RC 2 for:

> We should also avoid getting to Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowResponseAlreadyStartedException in this case.

**Comment by Junjun-zhao** [comment]
Verified and the above affected apps can work with dotnet-sdk-7.0.100-rc.1.22423.18. Thanks.
