### ISSUE TITLE
Assembly loading failed

### ISSUE THREAD

**Issue by heebtob** [dotnet/aspnetcore#43326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I get assembly loading exceptions. It happens in a relatively small windows service which exposes a gRPC Service. If it happens the gRPC Service stops working. It's not really reproducable but it happened three times in the last four months. After a server reboot it was working fine. The project does not have any reference to these assemblies. 

07.04.2022 Could not load file or assembly 'Microsoft.AspNetCore.Metadata, Version=5.0.0.0
01.06.2022 Could not load file or assembly 'Microsoft.AspNetCore.Metadata, Version=5.0.0.0,
12.08.2022 (17:30) Could not load file or assembly 'Microsoft.AspNetCore.Http.Features, Version=6.0.0.0

I checked if the assemblies are in the folder C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\6.0.7 and they are there.
Until August it was a .Net 5 project.

<PackageReference Include="Grpc.AspNetCore" Version="2.47.0" />
<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="6.0.0" />
<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.0" />
<PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="6.0.0" />
<PackageReference Include="Microsoft.Extensions.Http" Version="6.0.0" />

### Expected Behavior

It should load this assemblies without any issues.

### Exceptions (if any)

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Http.Features, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.AspNetCore.Http.Features, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection.ProcessRequestsAsync[TContext](IHttpApplication`1 httpApplication)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection.ProcessRequestsAsync[TContext](IHttpApplication`1 httpApplication)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnectionMiddleware`1.OnConnectionAsync(ConnectionContext connectionContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.<>c__DisplayClass9_0.<BindAsync>b__0(ConnectionContext c)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1.ExecuteAsync()

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Metadata, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.AspNetCore.Metadata, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

### .NET Version

5.0 and 6.0.7

### Anything else?

I saw this issue https://github.com/dotnet/aspnetcore/issues/18334. Maybe it's related to that.

**Comment by halter73** [comment]
> 5.0 and 6.0.7

Can you show the output of `dotnet list package --include-transitive`? It's not advised to mix package versions, and that command should clue us into why there's a mix of dependency versions.

**Comment by Tratcher** [comment]
Unfortunately there's not enough information here to investigate. Let us know if it you're able to reproduce this more reliably.
