### ISSUE TITLE
Kestrel TimingPipeFlusher calling WriteAsync when another write is pending, causing an exception (SSL)

### ISSUE THREAD

**Issue by sdb-dev** [dotnet/aspnetcore#43625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have recently tried switching over one of our applications from IIS to Kestrel using SSL, and it seems that kestrel is having random issues when flushing data to the SSL stream.

Here is the error message
```
Msg: Unhandled exception while processing {ConnectionId}. - Error: System.NotSupportedException:  The WriteAsync method cannot be called when another write operation is pending.
   at System.Net.Security.SslStream.WriteAsyncInternal[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer)
   at System.IO.Pipelines.StreamPipeWriter.FlushAsyncInternal(Boolean writeToStream, ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at System.IO.Pipelines.StreamPipeWriter.CompleteAsync(Exception exception)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.DuplexPipeStreamAdapter`1.DisposeAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1.ExecuteAsync()
```

Another error that occurs randomly, and possibly related:
```
Msg: Unexpected exception in TimingPipeFlusher.FlushAsync. - Error: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
   at System.Net.Security.SslStream.<ThrowIfExceptional>g__ThrowExceptional|138_0(ExceptionDispatchInfo e)
   at System.Net.Security.SslStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.IO.Pipelines.StreamPipeWriter.FlushAsyncInternal(Boolean writeToStream, ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.PipeWriterHelpers.ConcurrentPipeWriter.FlushAsyncAwaited(ValueTask`1 flushTask, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.PipeWriterHelpers.TimingPipeFlusher.TimeFlushAsyncAwaited(ValueTask`1 pipeFlushTask, MinDataRate minRate, IHttpOutputAborter outputAborter, CancellationToken cancellationToken)
   ```

We are using SignalR (6.0.8 package), with a few thousand active connection. The more connections, the higher chance for this issue to happen. We send data out every ~0.5 seconds on average through WebSocket

### Expected Behavior

The Kestrel web server should not throw these exceptions, it should instead check if the connection is disposed, or synchronize the writes properly.

### Steps To Reproduce

Enable SSL on Kestrel
Use SignalR with a lot of connections, and sending a lot of data async (every 1 second).

### .NET Version

6.0.5

**Comment by davidfowl** [comment]
Is your application doing overlapping writes to the response?

**Comment by sdb-dev** [comment]
We are doing many async sends in SignalR without await (legacy app I took over), so yes. I suppose prior to this, it was running with IIS integration instead of Kestrel, so we never noticed the issue

**Comment by davidfowl** [comment]
> We are doing many async sends in SignalR without await (legacy app I took over), so yes. I suppose prior to this, it was running with IIS integration instead of Kestrel, so we never noticed the issue

I mean are you writing to the same response without awaiting the previous write? If so, its not supported and you just need to await for this to work.

**Comment by BrennanConroy** [comment]
SignalR can't have overlapped writes. We synchronize the writes ourselves.

The ODE part could probably still happen if application code isn't awaiting the sends and the connection closes. Unless Kestrel handles that gracefully.
