### ISSUE TITLE
On upgrade to .NET 7, Data Protection throws "Payload was invalid" error when unprotecting values

### ISSUE THREAD

**Issue by anurse** [dotnet/aspnetcore#43682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We use Data Protection to encrypt sensitive values in long-term storage. While testing .NET 7.0, we found that our app was unable to decrypt payloads encrypted by .NET 6.0, even when the same keys were available and the same purpose was used. This means that upgrading to .NET 7 causes users to be logged out of our site (since the auth cookie cannot be validated) and our app is no longer able to decrypt data which it had previously encrypted and stored in durable storage (database, etc.).

I was able to isolate this into a simple repro console app: https://github.com/anurse/dataprotection-repro

The app runs on both `net6.0` and `net7.0` and can protect/unprotect values. Running `protect "Some string"` on `net6.0` produces a Base64 protected value. Passing that same payload into `unprotect` on `net6.0` **successfully unprotects the string**. However, passing it in to the same `unprotect` command in the same app when running on `net7.0` fails with the following error:

```
Unhandled exception. System.Security.Cryptography.CryptographicException: The payload was invalid. For more information go to http://aka.ms/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.Managed.ManagedAuthenticatedEncryptor.Decrypt(ArraySegment`1 protectedPayload, ArraySegment`1 additionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Program.Main(String[] args) in /Users/anurse/code/anurse/dataprotection-repro/ReproApp/Program.cs:line 35
   at Program.<Main>(String[] args)
```

Further debugging traced this down to this line:

https://github.com/dotnet/aspnetcore/blob/8f0d440d4251ae479966b65c7b331841adb70aa6/src/DataProtection/DataProtection/src/Managed/ManagedAuthenticatedEncryptor.cs#L235-L240

The MAC stored in the payload by the `net6.0` protect operation is not the same as the one computed by the `net7.0` during the unprotect operation. In fact, the same behavior occurs in reverse (a payload protected by `net7.0` cannot be unprotected by a `net6.0` app).

### Expected Behavior

When running the `run-repro` script in the provided repository, the output should be something like this:

```
... build output ...

Protecting: 'This is a test message'
*** Protecting with .NET 6.0 ... ***
Protected string: <trimmed>
Unprotecting with .NET 6.0 ...
This is a test message
Unprotecting with .NET 7.0 ...
This is a test message
*** Protecting with .NET 7.0 ... ***
Protected string: <trimmed>
Unprotecting with .NET 6.0 ...
This is a test message
Unprotecting with .NET 7.0 ...
This is a test message
```

The actual behavior is that an exception is thrown when unprotecting with a different major version than the data was originally protected with:

```
... build output ...

Protecting: 'This is a test message'
*** Protecting with .NET 6.0 ... ***
Protected string: <trimmed>
Unprotecting with .NET 6.0 ...
This is a test message
Unprotecting with .NET 7.0 ...
Unhandled exception. System.Security.Cryptography.CryptographicException: The payload was invalid. For more information go to http://aka.ms/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.Managed.ManagedAuthenticatedEncryptor.Decrypt(ArraySegment`1 protectedPayload, ArraySegment`1 additionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Program.Main(String[] args) in /Users/anurse/code/anurse/dataprotection-repro/ReproApp/Program.cs:line 35
   at Program.<Main>(String[] args)
*** Protecting with .NET 7.0 ... ***
Protected string: <trimmed>
Unprotecting with .NET 6.0 ...
Unhandled exception. System.Security.Cryptography.CryptographicException: The payload was invalid. For more information go to http://aka.ms/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.Managed.ManagedAuthenticatedEncryptor.Decrypt(ArraySegment`1 protectedPayload, ArraySegment`1 additionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Program.Main(String[] args) in /Users/anurse/code/anurse/dataprotection-repro/ReproApp/Program.cs:line 35
   at Program.<Main>(String[] args)
Unprotecting with .NET 7.0 ...
This is a test message
```

### Steps To Reproduce

1. Clone the repro repo: http://github.com/anurse/dataprotection-repro
2. Ensure you have .NET 6 and .NET 7 installed
3. Mac/Linux: Run `./run-repro` script
4. Windows:
    1. Run `dotnet run --project .\ReproApp --framework net6.0 -- protect "a test string"
    2. Copy the output string
    3. Run `dotnet run --project .\ReproApp --framework net6.0 -- unprotect "<paste>"`
    4. Run `dotnet run --project .\ReproApp --framework net7.0 -- unprotect "<paste>"`

### Exceptions (if any)

Unhandled exception. System.Security.Cryptography.CryptographicException: The payload was invalid. For more information go to http://aka.ms/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.Managed.ManagedAuthenticatedEncryptor.Decrypt(ArraySegment`1 protectedPayload, ArraySegment`1 additionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at Program.Main(String[] args) in /Users/anurse/code/anurse/dataprotection-repro/ReproApp/Program.cs:line 35
   at Program.<Main>(String[] args)

### .NET Version

7.0.100-preview.7.22377.5

### Anything else?

Since multiple .NET runtimes are involved, here's my `dotnet --info` output:

```
.NET SDK:
 Version:   7.0.100-preview.7.22377.5
 Commit:    ba310d9309

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.0
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.100-preview.7.22377.5/

Host:
  Version:      7.0.0-preview.7.22375.6
  Architecture: arm64
  Commit:       eecb028078

.NET SDKs installed:
  6.0.301 [/usr/local/share/dotnet/sdk]
  6.0.400 [/usr/local/share/dotnet/sdk]
  7.0.100-preview.7.22377.5 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-preview.7.22376.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-preview.7.22375.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by blowdart** [comment]
@adityamandaleeka this should get triaged asap. If upgrading breaks data protection with an existing keyring that's bad.

**Comment by wtgodbe** [comment]
@anurse thanks for the report! I'm investigating this now

**Comment by wtgodbe** [comment]
It turns out this repros on _any_ version-to-version upgrade (3.1 to 5.0, 5.0 to 6.0, 6.0 to 7.0) - if you protect with one version of .Net, you can't unprotect with another. Maybe it's expected? CC @GrabYourPitchforks - it could be because part of the protected string is ContentRoot, which by default is the output path of the app, which includes the TFM (e.g. `"C:\\code\\dataprotection\\dataprotection-repro-7\\ReproApp\\bin\\Debug\\net7.0\\"`)

**Comment by GrabYourPitchforks** [comment]
Answered this in an email thread, but the app discriminator should be stable across app upgrades. If it includes the TFM, that would explain the behavior we're seeing.

If you trace the history and unit tests for the DataProtection component, you'll find that it traditionally has used stable strings like the IIS virtual directory as the app discriminator. I don't know why the application directory is being passed in here.

**Comment by wtgodbe** [comment]
It looks like `HostingApplicationDiscriminator` has been using ContentRoot since at least 2.1:

https://github.com/dotnet/aspnetcore/blob/fd6923ccfef2c37553510d968f6daadfb83eedba/src/DataProtection/DataProtection/src/Internal/HostingApplicationDiscriminator.cs#L23

Which is used by the ServiceCollectionExtensions for DataProtection (What Andrew is using in their app): 

https://github.com/dotnet/aspnetcore/blob/fd6923ccfef2c37553510d968f6daadfb83eedba/src/DataProtection/DataProtection/src/DataProtectionServiceCollectionExtensions.cs#L79

Whereas the the Builder extension method has traditionally used the app name:

https://github.com/dotnet/aspnetcore/blob/fd6923ccfef2c37553510d968f6daadfb83eedba/src/DataProtection/DataProtection/src/DataProtectionBuilderExtensions.cs#L47

**Comment by Tratcher** [comment]
The TFM is only in the ContentRoot for an un-published app (e.g. dotnet run). A published app shouldn't discriminate by the TFM.

**Comment by wtgodbe** [comment]
I just confirmed this works (5.0 -> 6.0 & 6.0 -> 7.0) if the app has been `dotnet published` first, but not if you're just running `dotnet run` - so I don't think we'll be breaking customers in production. @anurse were you testing this w/ just `dotnet run`? In that scenario ContentRoot will have the TFM string in it, which explains the behavior.

**Comment by anurse** [comment]
I was testing via launching the app in Rider. I expect that runs from the build output, which includes the TFM in it.

The fact that the ContentRoot is the app discriminator indicates a bigger problem in using Data Protection for "durable" storage of protected values, since we are changing how we deploy the app and will likely change the ContentRoot.

It feels surprising that the path on which the app was deployed is used as part of the encryption since that's definitely not guaranteed to be stable over the lifetime of an app. Consider the case where the app is moved to a different deployment model (for example, from App Service to Docker) and suddenly all the previously-encrypted values are lost.

To solve the immediate problem, we can specify an explicit `ApplicationDiscriminator` (likely just using the old ContentRoot-based value for now). It just feels like a surprising behavior to me that moving my app to a different directory would break it's access to all encrypted payloads. Perhaps a model more like User Secrets would be more stable, where the project file specifies a "DataProtectionAppDiscriminator" property that's generated once when the app is created and should remain stable unless explicitly changed.

**Comment by brockallen** [comment]
> It feels surprising that the path on which the app was deployed is used as part of the encryption since that's definitely not guaranteed to be stable over the lifetime of an app. Consider the case where the app is moved to a different deployment model (for example, from App Service to Docker) and suddenly all the previously-encrypted values are lost.

This is one of the biggest support problems we have for customers. The ultimate solution is that they need to explicitly configure things, because the ambient values to make it F5 experience work well don't work all that well in practice. I get the rational for it all, so not a criticism -- it's just that data protection is an afterthought, and the fact that it's not more in the forefront of developers' mind is unfortunate. Education here is important.

**Comment by anurse** [comment]
> It looks like `HostingApplicationDiscriminator` has been using ContentRoot since at least 2.1:

It's also notable that the 7.0 version is doing normalization of the trailing slash that wasn't being done before. The 6.0 version is:

https://github.com/dotnet/aspnetcore/blob/6a01dd1e69c8b9bd1ae005ea465ef2bcd26294bf/src/DataProtection/DataProtection/src/Internal/HostingApplicationDiscriminator.cs#L23

Whereas the version in main is:

https://github.com/dotnet/aspnetcore/blob/e40c0fd4c87f82de4b685d050df542a52d4fa816/src/DataProtection/DataProtection/src/Internal/HostingApplicationDiscriminator.cs#L30-L43

On my macOS machine, when launching from Rider, the ContentRoot is:

```
/Users/anurse/code/aseriousbiz/abbot/src/product/Abbot.Web
```

This is the same in both .NET 6.0 and .NET 7.0, but because of the normalization, the .NET 7.0 version ends up putting a trailing slash on the end:

```
/Users/anurse/code/aseriousbiz/abbot/src/product/Abbot.Web/
```

I don't _think_ `dotnet publish` has an impact on the trailing slashes in ContentRootPath, so it seems from that like there is still a risk of breaking things in production.

**Comment by anurse** [comment]
I _can_ confirm that setting `ApplicationDiscriminator` to `hostEnvironment.ContentRootPath` _directly_, with **no** normalization (rather than using the `IApplicationDiscriminator`) solved the problem in local development for our app.

**Comment by wtgodbe** [comment]
> 
I can confirm that setting ApplicationDiscriminator to hostEnvironment.ContentRootPath directly, with no normalization (rather than using the IApplicationDiscriminator) solved the problem in local development for our app.

Can you elaborate on what you did here? I'd be surprised if a development build worked at all when using version N to protect and N+1 to unprotect, given that ContentRoot will have the TFM in it whether we normalize or not

**Comment by anurse** [comment]
Rider (and I believe Visual Studio) don't launch out of the build directory, they launch with the Project Directory as the Current Working Directory (which is what ContentRoot is derived from). I _believe_ `dotnet run` does that as well, at least for web apps?

**Comment by wtgodbe** [comment]
> Rider (and I believe Visual Studio) don't launch out of the build directory, they launch with the Project Directory as the Current Working Directory (which is what ContentRoot is derived from). I believe dotnet run does that as well, at least for web apps?

I was able to confirm with your repro app that `dotnet run` _does_ get different ContentRoots per TFM:

`"C:\\code\\dataprotection\\dataprotection-repro-7\\ReproApp\\bin\\Debug\\net6.0\\"
"C:\\code\\dataprotection\\dataprotection-repro-7\\ReproApp\\bin\\Debug\\net7.0\\"`

If Rider doesn't do that, and still breaks on upgrade from 6 to 7, then it sounds like we have 2 issues - a discussion on whether we should stop using ContentRoot at all, and a difference in the default `Discriminator` between 6 and 7 (which would definitely be a bug). Would you be able to confirm what you get from `IApplicationDiscriminator` thru rider between 6 and 7?

**Comment by anurse** [comment]
Yep, I can do a little more digging there.

**Comment by anurse** [comment]
My repro app was, admittedly, oversimplified (now that we know the issue is related to the ContentRootPath). The app I'm having difficulty with is a Web App, so let's use one of those. I created a new Web App and `dotnet run`ed it and got the following output:

```
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/anurse/code/anurse/dataprotection-repro/WebApp
```

The Content Root path has no TFM information in it.

**Comment by anurse** [comment]
I did notice something. Our app is still using `WebHost.CreateDefaultBuilder`, rather than the newer "minimal" Program.cs format. If I convert my example Web App to do that, and emit the IApplicationDiscriminator.Discriminator value during startup, this is what I see:

```
❯ dotnet run --project ./WebApp --framework net6.0
Building...
App Discriminator: /Users/anurse/code/anurse/dataprotection-repro/WebApp
Hosting environment: Development
Content root path: /Users/anurse/code/anurse/dataprotection-repro/WebApp
Now listening on: http://localhost:5255
Application started. Press Ctrl+C to shut down.
Application is shutting down...

❯ dotnet run --project ./WebApp --framework net7.0
Building...
App Discriminator: /Users/anurse/code/anurse/dataprotection-repro/WebApp/
Hosting environment: Development
Content root path: /Users/anurse/code/anurse/dataprotection-repro/WebApp
Now listening on: http://localhost:5255
Application started. Press Ctrl+C to shut down.
Application is shutting down...
```

I've pushed the repro with the `WebApp` to the repository.

**Comment by Tratcher** [comment]
This would be @halter73's normalizations. We broke this by mistake between 5 and 6 and were trying to re-unify.

**Comment by wtgodbe** [comment]
Ok, yes, this looks like https://github.com/dotnet/aspnetcore/issues/40964 + https://github.com/dotnet/aspnetcore/pull/41849. We changed ContentRoot between 5 and 6 and then again between 6 and 7 to try to "fix" the 5 -> 6 change. We had to choose between breaking people using HostBuilder and people using WebApplicationBuilder, and we chose the latter. It's an unfortunate situation - if we're right that this is the issue, the workaround would be to manually set your Discriminator to be the same as it was in 6 when you upgrade your app to 7. We should communicate this very loudly for 7 - @halter73 @blowdart where is the right place to do that?

(Of course, I'll play with the repro app to confirm this suspicion, but all signs are currently pointing towards it)

**Comment by anurse** [comment]
> the workaround would be to manually set your Discriminator to be the same as it was in 6 when you upgrade your app to 7

That's our plan for now. Eventually we'll switch over to a fixed Application Discriminator as well. It would, perhaps, be good to consider how to improve this experience in .NET 8 and beyond. Using Content Root Path is brittle even without issues like this, since moving the app to be hosted at a different path would silently break all encrypted payloads.

It seems to me that there might be a need for a kind of universal "Application Name" identifier of some kind, generated into the csproj on `dotnet new` (much like how User Secret IDs work today).

Anyway, thanks for all the investigative work here. We have a solution that will allow us to upgrade safely now!

**Comment by wtgodbe** [comment]
TODO - come up with plan for .net 8

**Comment by japui-coder** [comment]
On upgrade to .NET 7, Data Protection throws "Payload was invalid" error when unprotecting values from .NET 6 #43682

**Comment by blowdart** [comment]
Add it to the aka.ms page for the errors? Also very clearly in the docs in lots of places.

**Comment by altenstedt** [comment]
Just to comment on the code from @frabe1579  above for future readers, Microsoft documents a slightly different approach:

```
var trimmedContentRootPath = Environment.ContentRootPath.TrimEnd(Path.DirectorySeparatorChar);

services.AddDataProtection()
    .SetApplicationName(trimmedContentRootPath)
    ...
```

It is documented in the "Warning" section here:

https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?tabs=aspnetcore2x&view=aspnetcore-7.0#setapplicationname

**Comment by dazinator** [comment]
Why was there no breaking change recorded for this? I was just upgrading from dotnet 6 to dotnet 8 and data protection broke.

**Comment by frabe1579** [comment]
@dazinator This is not a breaking change, the behavior depends on a multitude of factors, all together defining application path, which is used by default as discriminator.
Documentation: https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-8.0

**Comment by dazinator** [comment]
@frabe1579 I was upgrading my application from dotnet 6 to dotnet 8, and this behavioural change (somewhere) resulted in a breakage of data protection payloads... So at some level, there is a breaking change no? Even if its to do with how the host formulates this default descriminator and not within the data protection library itself - thats still a behaviour change that causes a breakage. When I am upgrading from dotnet 6 to dotnet 8, I carefully review all of the breaking changes and look for guides to help me understand the factors involved when upgrading.. This seems to be one you are aware of, but isn't mentioned anywhere where it would be useful or helpful. A developer considering upgrading from dotnet 6 to 8 is highly unlikely to read every single individual library page to parse for potential issues in the form of a warning somewhere. Its more likely they just want a consolidated list of braking changes that they need to consider - with guidance on how to address them no?
