### ISSUE TITLE
Assert failure in QuicConnectionContext.AcceptAsync

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#43727]
I was making basic GET requests using HttpClient to Kestrel's [Http3SampleApp](https://github.com/dotnet/aspnetcore/blob/e971d938793f2d0b8bc96e5f839e61066d19ecea/src/Servers/Kestrel/samples/Http3SampleApp/Program.cs) when I saw the following debug assert failure in QuicConnectionContext.AcceptAsync:

https://github.com/dotnet/aspnetcore/blob/e971d938793f2d0b8bc96e5f839e61066d19ecea/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicConnectionContext.cs#L171-L175

We're already handling `QuicError.ConnectionAborted` and `QuicError.OperationAborted`. It looks like we might have to add `QuicError.ConnectionTimeout`. We might also need to check for `QuicError.ConnectionIdle` if that can ever be non-infinite.

Here are some logs. I'm not sure what induced the timeout. Maybe hitting a breakpoint debugging or something? Semi-related #43723 although that's about the connection accept loop instead of the stream accept loop.

```
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : MsQuicContextSafeHandle#37710717,ReleaseHandle,[strm][0x1D937E4D040] MsQuicSafeHandle released ->
[17:44:51.834] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : MsQuicContextSafeHandle#37710717,ReleaseHandle,[strm][0x1D937E4D040] [conn][0x1D937E06840] ref count decremented ->
[17:44:51.835] trce: Microsoft.AspNetCore.Server.Kestrel.Transport.Quic[16]
      Stream id "0HMKD8M1GN8VA:00000000" pooled for reuse.
[17:45:07.832] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicConnection#2637164,HandleEventShutdownInitiatedByTransport,[conn][0x1D937E06840] Received event SHUTDOWN_INITIATED_BY_TRANSPORT with Status=-2143223802 ->
[17:45:07.838] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicStream#4878312,HandleEventShutdownComplete,[strm][0x1D935D27BA0] Received event SHUTDOWN_COMPLETE with  ConnectionShutdown=1 ->
[17:45:07.838] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicStream#13575069,HandleEventSendShutdownComplete,[strm][0x1D937E5DA00] Received event PEER_RECEIVE_ABORTED with Graceful=0 ->
[17:45:07.838] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicStream#13575069,HandleEventShutdownComplete,[strm][0x1D937E5DA00] Received event SHUTDOWN_COMPLETE with  ConnectionShutdown=1 ->
[17:45:07.838] dbug: HttpEventSourceListener[0]
      <- Event Private.InternalDiagnostics.System.Net.Quic - Info : QuicConnection#2637164,HandleEventShutdownComplete,[conn][0x1D937E06840] Received event SHUTDOWN_INITIATED_BY_PEER_DATA ->
[17:45:07.839] dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Quic[7]
      Stream id "0HMKD8M1GN8VA:00000002" unexpected error.
      System.Net.Quic.QuicException: Connection timed out waiting for a response from the peer.
         at System.Net.Quic.ResettableValueTaskSource.TryComplete(Exception exception, Boolean final)
         at System.Net.Quic.QuicStream.HandleEventShutdownComplete(_SHUTDOWN_COMPLETE_e__Struct& data)
         at System.Net.Quic.QuicStream.HandleStreamEvent(QUIC_STREAM_EVENT& streamEvent)
         at System.Net.Quic.QuicStream.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_STREAM_EVENT* streamEvent)
      --- End of stack trace from previous location ---
         at System.Net.Quic.ResettableValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
         at System.Net.Quic.QuicStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicStreamContext.DoReceiveAsync() in C:\dev\dotnet\aspnetcore\src\Servers\Kestrel\Transport.Quic\src\Internal\QuicStreamContext.cs:line 214
[17:45:07.839] dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Quic[7]
      Stream id "0HMKD8M1GN8VA:00000003" unexpected error.
      System.Net.Quic.QuicException: Connection timed out waiting for a response from the peer.
         at System.Net.Quic.ResettableValueTaskSource.TryComplete(Exception exception, Boolean final)
         at System.Net.Quic.QuicStream.HandleEventShutdownComplete(_SHUTDOWN_COMPLETE_e__Struct& data)
         at System.Net.Quic.QuicStream.HandleStreamEvent(QUIC_STREAM_EVENT& streamEvent)
         at System.Net.Quic.QuicStream.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_STREAM_EVENT* streamEvent)
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicStreamContext.WaitForWritesClosedAsync() in C:\dev\dotnet\aspnetcore\src\Servers\Kestrel\Transport.Quic\src\Internal\QuicStreamContext.cs:line 188
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicStreamContext.DoSendAsync() in C:\dev\dotnet\aspnetcore\src\Servers\Kestrel\Transport.Quic\src\Internal\QuicStreamContext.cs:line 391
[17:45:07.842] dbug: Microsoft.AspNetCore.Server.Kestrel.Transport.Quic[10]
      Stream id "0HMKD8M1GN8VA:00000003" shutting down writes because: "Connection timed out waiting for a response from the peer.".
Process terminated. Assertion failed.
Unexpected exception in QuicConnectionContext.AcceptAsync: System.Net.Quic.QuicException: Connection timed out waiting for a response from the peer.
   at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data)
   at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent)
   at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)
--- End of stack trace from previous location ---
   at System.Net.Quic.QuicConnection.AcceptInboundStreamAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionContext.AcceptAsync(CancellationToken cancellationToken) in C:\dev\dotnet\aspnetcore\src\Servers\Kestrel\Transport.Quic\src\Internal\QuicConnectionContext.cs:line 96
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionContext.AcceptAsync(CancellationToken cancellationToken) in C:\dev\dotnet\aspnetcore\src\Servers\Kestrel\Transport.Quic\src\Internal\QuicConnectionContext.cs:line 96
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute)
   at System.Threading.Tasks.Task.TrySetException(Object exceptionObject)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField)
   at System.Net.Quic.QuicConnection.AcceptInboundStreamAsync(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

C:\dev\dotnet\aspnetcore\artifacts\bin\Http3SampleApp\Debug\net7.0\Http3SampleApp.exe (process 30844) exited with code -2146232797.
```

**Comment by wtgodbe** [comment]
@JamesNK can this be closed?
