### ISSUE TITLE
Version reference mismatch for Microsoft.AspNetCore.Mvc.Localization assembly, incompatible with nuget

### ISSUE THREAD

**Issue by codetuner** [dotnet/aspnetcore#43828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The aspnetcore 6.0.8 (the latest) contains a different version of the "Microsoft.AspNetCore.Mvc.Localization.dll" assembly than the latest (2.2.0) "Microsoft.AspNetCore.Mvc.Localization" nuget package. Is a result, incompatibility issues arise.

The assembly in the nuget package has an IHtmlLocalizer which has a WithCulture method. The IHtmlLocalizer class in the assembly referred by aspnetcore 6.0.8 does not have a WithCulture method.

As a result, creating a library with a reference to the nuget to expose a custom IHtmlMLocalizer class, and consume it from an aspnetcore project results in the following error:
System.Reflection.ReflectionTypeLoadException: 'Unable to load one or more of the requested types.
Method not found: 'Microsoft.AspNetCore.Mvc.Localization.IHtmlLocalizer Microsoft.AspNetCore.Mvc.Localization.IHtmlLocalizer.WithCulture(System.Globalization.CultureInfo)'.'

### Expected Behavior

The "Microsoft.AspNetCore.Mvc.Localization.dll" assembly should be the same in "aspnetcore" as in the "Microsoft.AspNetCore.Mvc.Localization" nuget. Or at lease, the version in aspnetcore should be available as nuget version.

### Steps To Reproduce

See the following public Nuget repository:
[codetuner/AspnetcoreIssue43828](https://github.com/codetuner/AspnetcoreIssue43828)

### Exceptions (if any)

System.Reflection.ReflectionTypeLoadException
  HResult=0x80131602
  Message=Unable to load one or more of the requested types.
Method not found: 'Microsoft.AspNetCore.Mvc.Localization.IHtmlLocalizer Microsoft.AspNetCore.Mvc.Localization.IHtmlLocalizer.WithCulture(System.Globalization.CultureInfo)'.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart.get_Types()
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.GetControllerTypes()
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.UpdateCollection()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.Initialize()
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.<>c__DisplayClass11_0.<Subscribe>b__0()
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.Subscribe()
   at Microsoft.AspNetCore.Mvc.Routing.ControllerActionEndpointDataSource..ctor(ControllerActionEndpointDataSourceIdProvider dataSourceIdProvider, IActionDescriptorCollectionProvider actions, ActionEndpointFactory endpointFactory, OrderedEndpointsSequenceProvider orderSequence)
   at Microsoft.AspNetCore.Builder.ControllerEndpointRouteBuilderExtensions.GetOrCreateDataSource(IEndpointRouteBuilder endpoints)
   at Microsoft.AspNetCore.Builder.ControllerEndpointRouteBuilderExtensions.MapControllerRoute(IEndpointRouteBuilder endpoints, String name, String pattern, Object defaults, Object constraints, Object dataTokens)
   at Program.<Main>$(String[] args) in C:\SRCRB\Github\CodeTuner\Arebis.MvcDashboards\MyMvcApp\Program.cs:line 86

### .NET Version

6.0.400

**Comment by blowdart** [comment]
_The aspnetcore 6.0.8 (the latest) contains a different version of the "Microsoft.AspNetCore.Mvc.Localization.dll" assembly than the latest (2.2.0) "Microsoft.AspNetCore.Mvc.Localization" nuget package. Is a result, incompatibility issues arise._

This sounds like you're mixing and matching versions. Microsoft.AspNetCore.Mvc.* aren't generally packages any more, and haven't been for a few versions now, instead they're replaced by framework references, for example.

```xml
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
```

You shouldn't need references to nuget packages for most framework things any more, and mixing and matching major versions gets everything even more confused.

Could you share your csproj so we can figure out what's going on?

**Comment by codetuner** [comment]
Hi @blowdart. Indeed, the FrameworkReference solved it! Great thanks!

For what it's worth, I have published a reproduction GitHub, but the issue is solved, so... Thanks again!
https://github.com/codetuner/AspnetcoreIssue43828
