### ISSUE TITLE
Identity UserManager.AddToRoleAsync is querying the role with normalized name instead of the name column

### ISSUE THREAD

**Issue by sodiqyekeen** [dotnet/aspnetcore#43912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I created a role using the  `_roleManager.CreateAsync(adminRole)`, and I'm able read the role via await `_roleManager.FindByNameAsync(RoleConstants.Admin)`, but getting exception that role does not exist when adding a user to the role by calling the await `_userManager.AddToRoleAsync(adminUser, RoleConstants.Admin)`;

Checked the query for getting the role I realized that the method is querying against the normalized name. See query below:

```
 SELECT "r"."Id", "r"."ConcurrencyStamp", "r"."CreatedBy", "r"."CreatedOn", "r"."Description", "r"."LastModifiedBy", "r"."LastModifiedDate", "r"."Name", "r"."NormalizedName", "r"."TenantId"
      FROM "Role" AS "r"
      WHERE (("r"."TenantId" IS NULL) OR ("r"."TenantId" = @__ef_filter__TenantId_0)) AND ("r"."NormalizedName" = @__normalizedRoleName_0)
      LIMIT 2
```

### Expected Behavior

The AddToRoleAsync method should query as the role manager find by name method, so that user can be added to a role without having to pass the normalized value.

### Steps To Reproduce

<PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.6" />
<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.6" />

```
var admin = await _userManager.FindByEmailAsync("mail@gmail.com");
            if (admin==null)
            {
                admin = new SkoolzUser
                {
                    Active=true,
                    Email = "olatechlove@gmail.com",
                    EmailConfirmed=true,
                    UserName = "sysuser",
                };
                await _userManager.CreateAsync(admin, "password");
            }
           
            if (!await _userManager.IsInRoleAsync(admin, RoleConstants.Admin)) //Error here and below if this condition is not checked.
                await _userManager.AddToRoleAsync(admin, RoleConstants.Admin);
```

### Exceptions (if any)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.FindTracked(Object[] keyValues, IReadOnlyList`1& keyProperties)
   at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.FindAsync(Object[] keyValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.FindAsync(Object[] keyValues, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.FindUserRoleAsync(TKey userId, TKey roleId, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.IsInRoleAsync(TUser user, String normalizedRoleName, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.IsInRoleAsync(TUser user, String role)
   at Skoolz.Infrastructure.DataSeed.AdminUser() in C:\Users\Zach\Documents\Dev\Projects\Skoolz\Skoolz.Infrastructure\DataSeed.cs:line 66
   at Skoolz.Infrastructure.DataSeed.Initialize() in C:\Users\Zach\Documents\Dev\Projects\Skoolz\Skoolz.Infrastructure\DataSeed.cs:line 37

### .NET Version

6.0.400

**Comment by HaoK** [comment]
So usually roleManager.Create will do the normalization of the role name for you, the question is why its not able to find the role with the normalized role name in your db?

**Comment by sodiqyekeen** [comment]
I am able to get the role through the role manager find by name method but every access via the user manager is failing with this exception

![image](https://user-images.githubusercontent.com/77198295/190844206-5a37d157-9431-4f07-90b4-ef4d18bc76eb.png)

![image](https://user-images.githubusercontent.com/77198295/190844246-1495b454-2d39-4046-a499-044352b37615.png)
