### ISSUE TITLE
Quarantine ClosingTheBrowserWindow_GracefullyDisconnects_TheCurrentCircuit

### ISSUE THREAD

**Issue by brunolins16** [dotnet/aspnetcore#44017]
## Failing Test(s)

- Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.CircuitGracefulTerminationTests.ClosingTheBrowserWindow_GracefullyDisconnects_TheCurrentCircuit

## Error Message

```text
Assert.True() Failure
Expected: True
Actual:   False
```

## Stacktrace
<details>
```text
   at Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.CircuitGracefulTerminationTests.ClosingTheBrowserWindow_GracefullyDisconnects_TheCurrentCircuit() in /home/vsts/work/1/s/src/Components/test/E2ETest/ServerExecutionTests/CircuitGracefulTerminationTests.cs:line 71
--- End of stack trace from previous location ---
```
</details>

## Logs

<details>

```text
[Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.CircuitGracefulTerminationTests.ClosingTheBrowserWindow_GracefullyDisconnects_TheCurrentCircuit] Attempt 1 of 3 failed due to Xunit.Sdk.TrueException: Assert.True() Failure
Expected: True
Actual:   False
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/xunit.assert/Asserts/BooleanAsserts.cs:line 132
   at Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.CircuitGracefulTerminationTests.ClosingTheBrowserWindow_GracefullyDisconnects_TheCurrentCircuit() in /home/vsts/work/1/s/src/Components/test/E2ETest/ServerExecutionTests/CircuitGracefulTerminationTests.cs:line 71
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 273
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 54
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 96

[Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.CircuitGracefulTerminationTests.ClosingTheBrowserWindow_GracefullyDisconnects_TheCurrentCircuit] Attempt 2 of 3 failed due to Xunit.Sdk.TrueException: Assert.True() Failure
Expected: True
Actual:   False
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/xunit.assert/Asserts/BooleanAsserts.cs:line 132
   at Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.CircuitGracefulTerminationTests.ClosingTheBrowserWindow_GracefullyDisconnects_TheCurrentCircuit() in /home/vsts/work/1/s/src/Components/test/E2ETest/ServerExecutionTests/CircuitGracefulTerminationTests.cs:line 71
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 273
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 54
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 96
```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=18904&view=ms.vss-test-web.build-test-results-tab&runId=378812&resultId=100448&paneView=attachments

**Comment by dougbu** [comment]
Closing as #44185 correctly reflects fact this test is quarantined in release/7.0 as well. This bug is _not_ specific to 8.0.0 or our main branch.
