### ISSUE TITLE
Blazor Components-E2E Pipeline is Broken

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#44385]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=40464&view=results

https://github.com/dotnet/aspnetcore/runs/8711580626

```
OpenQA.Selenium.WebDriverException : target frame detached
  (failed to check if window was closed: no such frame: Session with given id not found.)
  (Session info: headless chrome=106.0.5249.91)
```

```
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.ExecuteScriptCommand(String script, String commandName, Object[] args)
   at OpenQA.Selenium.WebDriver.ExecuteScript(String script, Object[] args)
   at Microsoft.AspNetCore.Components.E2ETest.Infrastructure.ServerTestBase`1.InitializeAsyncCore() in /home/vsts/work/1/s/src/Components/test/E2ETest/Infrastructure/ServerTestBase.cs:line 39
   at Microsoft.AspNetCore.E2ETesting.BrowserTestBase.InitializeAsync(String isolationContext) in /home/vsts/work/1/s/src/Shared/E2ETesting/BrowserTestBase.cs:line 71
```

Potential Selenium breaking change? **The pipeline is being marked as not required as a temporary unblocker**.

**Comment by TanayParikh** [comment]
@MackinnonBuck @wtgodbe do we need to do anything to re-enable / require the `components-e2e` tests? Not sure if we actually ended up disabling them or not in the interim.

**Comment by wtgodbe** [comment]
> @MackinnonBuck @wtgodbe do we need to do anything to re-enable / require the components-e2e tests? Not sure if we actually ended up disabling them or not in the interim.

There's just a github setting we need to change to re-require the pipeline - should I do so?

**Comment by MackinnonBuck** [comment]
@wtgodbe The pipeline seems pretty stable now so I think we can re-require it.

**Comment by TanayParikh** [comment]
Looks like it was never disabled (at least on 7.0): https://github.com/dotnet/aspnetcore/pull/44378#issuecomment-1271000701
