### ISSUE TITLE
[Blazor WASM] Unable to run method 'void BuildRenderTreeMicrosoft.AspNetCore.Components.Rendering.RenderTreeBuilder)': locals size too big.

### ISSUE THREAD

**Issue by zxyao145** [dotnet/aspnetcore#44437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a page for demo, which is automatically generated by code and has many components (more than 2000 in total). I find that when the number of components reaches a certain level, the following errors will occur. If I delete some components, the error will disappear. 

It seems that there is x for the number of components ("locals size too big" in the error prompt).

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Unable to run method 'void xxxx.Pages.FullIcons:BuildRenderTree (Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder)': locals size too big.
System.InvalidProgramException: Unable to run method 'void xxxxx.Pages.FullIcons:BuildRenderTree (Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder)': locals size too big.
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```

### .NET Version

6.0.401

**Comment by javiercn** [comment]
@zxyao145 thanks for contacting us.

That is likely not a Blazor issue but an issue in how you are generating your code. From what I can tell, the method you are generating is so big that there is not enough space on the stack to hold all the local variables that your method needs.
