### ISSUE TITLE
The synchronous method is not supported by 'Microsoft.AspNetCore.TestHost.ClientHandler'

### ISSUE THREAD

**Issue by code-jar** [dotnet/aspnetcore#44464]
In dotnet 6.0, HttpMessageHandler provides the synchronous sending method `HttpResponseMessage Send(HttpRequestMessage request, CancellationToken cancellationToken)`

`Microsoft.AspNetCore.TestHost.ClientHandler` inherit `HttpMessageHandler ` Not implemented synchronous sending method `Send`

## Failing Test(s)

![image](https://user-images.githubusercontent.com/22388512/194989163-6e876405-a3b2-49ce-be9f-29e37abb62ac.png)

-

## Stacktrace

```
System.NotSupportedException: The synchronous method is not supported by 'Microsoft.AspNetCore.TestHost.ClientHandler'.
 If you're using a custom 'HttpMessageHandler' and wish to use synchronous HTTP methods, you must override its 'Send' virtual method.
   at System.Net.Http.HttpMessageHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DelegatingHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DelegatingHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DelegatingHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request)

```
</details>

**Comment by adityamandaleeka** [comment]
@code-jar Can you share more about your use case? Is there a reason why you can't use the async version of the API?

Triage: We could implement this pretty trivially with something like `SendAsync.GetAwaiter().GetResult()`.

**Comment by Tratcher** [comment]
Implementing this risks causing threadpool exhaustion in the test project. We'll add an error message to that effect.
