### ISSUE TITLE
Blazor JSDisconnectedException caught as AggregateException from TaskScheduler.UnobservedTaskException

### ISSUE THREAD

**Issue by vflame** [dotnet/aspnetcore#44684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

All usages of IJSRuntime's `InvokeVoidAsync()/InvokeAsync()` are wrapped in a try catch for `JSDisconnectedException`. Is it expected/safe to ignore these unobserved exceptions that appear when registering to `TaskScheduler.UnobservedTaskException`?

```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.)
 ---> Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   --- End of inner exception stack trace ---
```

### .NET Version

6

**Comment by javiercn** [comment]
@vflame thanks for contacting us.

Can you share a minimal repro project that demonstrates the issue? Is not clear what you are trying to do.
