### ISSUE TITLE
Blazor Server On Connection Authentication

### ISSUE THREAD

**Issue by markat1** [dotnet/aspnetcore#44820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have an issue with windows authentication in a blazor server "system.Objectdisposedexception: Safe handle has been closed". In #12051 [@stevensanderson](https://twitter.com/stevensanderson) 

_To resolve this, we need some extra logic that, whenever the circuit connection becomes up (equivalent to OnConnectionUpAsync on a circuit handler), we grab the latest User from the HubContext (or HttpContext if we must, but HubContext is more correct) and pass it to the built-in authentication state provider, which can update its own internal state and call its own NotifyAuthenticationStateChanged._

I dont really understand what it means, and I haven't had luck on finding any sample that shows how it could be solved

### Expected Behavior

I expect that It shoulnt  drop this system.objectdisposeexception

### Steps To Reproduce

I use the following custom authstateprovider:

```
 public class TestAuthStateProvider : AuthenticationStateProvider
    {
        private readonly IHttpContextAccessor _httpContextAccessor;

        public TestAuthStateProvider(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
        }
        
        public override async Task<AuthenticationState> GetAuthenticationStateAsync()
        {
          
            var authuser = GetUser() ?? new ClaimsPrincipal(new ClaimsIdentity());

            await Task.Delay(1);

            return new AuthenticationState(authuser);
        }

        public ClaimsPrincipal? GetUser()
        {
            return _httpContextAccessor?.HttpContext?.User;
        }

    }
```

### Exceptions (if any)

```
[01/11/2022 10:49:15 WRN] Unhandled exception rendering component: Safe handle has been closed.
Object name: 'SafeHandle'.
System.ObjectDisposedException: Safe handle has been closed.
Object name: 'SafeHandle'.
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.Advapi32.DuplicateTokenEx(SafeAccessTokenHandle hExistingToken, UInt32 dwDesiredAccess, IntPtr lpTokenAttributes, UInt32 ImpersonationLevel, UInt32 TokenType, SafeAccessTokenHandle& phNewToken)
   at System.Security.Principal.WindowsPrincipal.IsInRole(SecurityIdentifier sid)
   at System.Security.Principal.WindowsPrincipal.IsInRole(String role)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.AspNetCore.Authorization.Infrastructure.RolesAuthorizationRequirement.HandleRequirementAsync(AuthorizationHandlerContext context, RolesAuthorizationRequirement requirement)
   at Microsoft.AspNetCore.Authorization.AuthorizationHandler`1.HandleAsync(AuthorizationHandlerContext context)
   at Microsoft.AspNetCore.Authorization.Infrastructure.PassThroughAuthorizationHandler.HandleAsync(AuthorizationHandlerContext context)
   at Microsoft.AspNetCore.Authorization.DefaultAuthorizationService.AuthorizeAsync(ClaimsPrincipal user, Object resource, IEnumerable`1 requirements)
   at Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.IsAuthorizedAsync(ClaimsPrincipal user)
   at Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.OnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
[01/11/2022 10:49:16 ERR] Unhandled exception in circuit 'iu_JUNYyhrCtLJxkwbzxX87ohvDjr3seIuRUs3BmtCg'.
System.ObjectDisposedException: Safe handle has been closed.
Object name: 'SafeHandle'.
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.Advapi32.DuplicateTokenEx(SafeAccessTokenHandle hExistingToken, UInt32 dwDesiredAccess, IntPtr lpTokenAttributes, UInt32 ImpersonationLevel, UInt32 TokenType, SafeAccessTokenHandle& phNewToken)
   at System.Security.Principal.WindowsPrincipal.IsInRole(SecurityIdentifier sid)
   at System.Security.Principal.WindowsPrincipal.IsInRole(String role)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.AspNetCore.Authorization.Infrastructure.RolesAuthorizationRequirement.HandleRequirementAsync(AuthorizationHandlerContext context, RolesAuthorizationRequirement requirement)
   at Microsoft.AspNetCore.Authorization.AuthorizationHandler`1.HandleAsync(AuthorizationHandlerContext context)
   at Microsoft.AspNetCore.Authorization.Infrastructure.PassThroughAuthorizationHandler.HandleAsync(AuthorizationHandlerContext context)
   at Microsoft.AspNetCore.Authorization.DefaultAuthorizationService.AuthorizeAsync(ClaimsPrincipal user, Object resource, IEnumerable`1 requirements)
   at Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.IsAuthorizedAsync(ClaimsPrincipal user)
   at Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.OnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
[01/11/2022 10:49:16 WRN] Unhandled exception rendering component: Safe handle has been closed.
Object name: 'SafeHandle'.
System.ObjectDisposedException: Safe handle has been closed.
Object name: 'SafeHandle'.
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.Advapi32.DuplicateTokenEx(SafeAccessTokenHandle hExistingToken, UInt32 dwDesiredAccess, IntPtr lpTokenAttributes, UInt32 ImpersonationLevel, UInt32 TokenType, SafeAccessTokenHandle& phNewToken)
   at System.Security.Principal.WindowsPrincipal.IsInRole(SecurityIdentifier sid)
   at System.Security.Principal.WindowsPrincipal.IsInRole(String role)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.AspNetCore.Authorization.Infrastructure.RolesAuthorizationRequirement.HandleRequirementAsync(AuthorizationHandlerContext context, RolesAuthorizationRequirement requirement)
   at Microsoft.AspNetCore.Authorization.AuthorizationHandler`1.HandleAsync(AuthorizationHandlerContext context)
   at Microsoft.AspNetCore.Authorization.Infrastructure.PassThroughAuthorizationHandler.HandleAsync(AuthorizationHandlerContext context)
   at Microsoft.AspNetCore.Authorization.DefaultAuthorizationService.AuthorizeAsync(ClaimsPrincipal user, Object resource, IEnumerable`1 requirements)
   at Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.IsAuthorizedAsync(ClaimsPrincipal user)
   at Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.OnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
[01/11/2022 10:49:16 ERR] Unhandled exception in circuit 'iu_JUNYyhrCtLJxkwbzxX87ohvDjr3seIuRUs3BmtCg'.
System.ObjectDisposedException: Safe handle has been closed.
Object name: 'SafeHandle'.

```
### .NET Version

blazor server template .net 6

**Comment by markat1** [comment]
I made this repository way back in may - https://github.com/markat1/WindowsAuthenticationProblem.

**Comment by markat1** [comment]
Issue seems to happen more often if I call authenticatestate  other than OnInitialized() . So now I  

```
  protected async override Task OnInitializedAsync()
   {
            UserName = await GetAuthenticatedUserAsync();
   }

 private async Task<string> GetAuthenticatedUserAsync()
 {
       var authState = await AuthenticationStateTask;
       return authState?.User.Identity?.Name;
 }
```

**Comment by markat1** [comment]
It's not easy to pinpoint exactly how I would trigger ObjectDisposedException
you could try call AuthenticationStateTask multiple times or refresh page alot. That might throw ObjectDisposedException.

**Comment by javiercn** [comment]
@markat1 we do not recommend using IHttpContextAccessor in Blazor.

See https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-6.0#blazor-and-shared-state

**Comment by javiercn** [comment]
As an aside, it is not clear to me why you are trying to use a handler. The circuit automatically re-evaluates the principal on reconnection `https://github.com/dotnet/aspnetcore/blob/main/src/Components/Server/src/ComponentHub.cs#L182`

**Comment by markat1** [comment]
@javiercn only reason I used a handler is actually because didn't know I just could pass an object directly via component as mentioned your reference [link ](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-6.0#blazor-and-shared-state)!

I do have couple of questions


**1.question**
 If I try assign httpcontext.user directly to my intialApplicationState, that would give me a:

`JsonException: A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 64. Consider using ReferenceHandler.Preserve on JsonSerializerOptions to support cycles. Path: $.ParameterValues.User.Claims.Subject.Claims.Subject.Claims.`

What I want to grab from the httpContext.User is users name and what kinda roles user claims. 

```
@{
    Layout = "_Layout";

    var paramusers = new InitialApplicationState
            {
                User = HttpContext.User
            };
}

<component type="typeof(App)" param-InitialState="paramusers" render-mode="ServerPrerendered" />

```
2.question
So I have issue regarding a blank screen while my blazor server loads up the application.  I can only solve this issue by overriding AuthenticationStateProvider and set a delay of 1 millisecond. That means it would run autorizing under (app.razor) 

```
       <Authorizing>
           application is loading.....
         </Authorizing>
```


```
 public class TestAuthStateProvider : AuthenticationStateProvider
    {
        //private readonly IHttpContextAccessor _httpContextAccessor;
        private UserProvider _userprovider;

        public TransportBookingAuthStateProvider(IHttpContextAccessor httpContextAccessor, UserProvider userProvider)
        {
            //_httpContextAccessor = httpContextAccessor;
            _userprovider = userProvider;   
        }
        
        public override async Task<AuthenticationState> GetAuthenticationStateAsync()
        {

            var authuser = _userprovider.User ?? new ClaimsPrincipal(new ClaimsIdentity());

            await Task.Delay(1);

            return new AuthenticationState(authuser);
        }

        //public ClaimsPrincipal? GetUser()
        //{
        //    return _httpContextAccessor?.HttpContext?.User;
        //}

    }
}
```
Then only think I have tried

**Comment by markat1** [comment]
I'm not sure  [if this is the recommendable way](https://www.meziantou.net/showing-a-loading-screen-while-initializing-a-blazor-application.htm
)  of making a loader, but it still show loader twice when setting render mode to Server

**Comment by javiercn** [comment]
@markat1 thanks for the additional details.

For 1, the issue is that the principal that you have is not serializable. One thing you could try is to serialize the information you care about and generate a ClaimsPrincipal out of that.

> I'm not sure [if this is the recommendable way](https://www.meziantou.net/showing-a-loading-screen-while-initializing-a-blazor-application.htm) of making a loader, but it still show loader twice when setting render mode to ServerPrerendered

You are looking for https://learn.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-7.0&pivots=server#persist-prerendered-state

Essentially Blazor renders once statically on the server and a second time on the client.

**Comment by markat1** [comment]
I will definately look into serializing information from httpcontext.user - specifically I want users role and name
