### ISSUE TITLE
gRPC integration test `TStartup` = `Program.cs` throws `"A public method named 'ConfigureIntegrationTests' or 'Configure' could not be found in the 'Program' type."`

### ISSUE THREAD

**Issue by khteh** [dotnet/aspnetcore#44906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I follow this: https://learn.microsoft.com/en-us/aspnet/core/grpc/test-services?view=aspnetcore-6.0
and bump into:
```
"A public method named 'ConfigureIntegrationTests' or 'Configure' could not be found in the 'Program' type."
```
```
at Microsoft.AspNetCore.Hosting.StartupLoader.FindMethod(Type startupType, String methodName, String environmentName, Type returnType, Boolean required)
   at Microsoft.AspNetCore.Hosting.StartupLoader.FindConfigureDelegate(Type startupType, String environmentName)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostBuilderExtensions.<StartAsync>d__1.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostBuilderExtensions.Start(IHostBuilder hostBuilder)
   at Web.Api.IntegrationTests.Services.GrpcTestFixture`1.EnsureServer() in C:\\Projects\\ASP.Net\\AspNetCoreWebApi\\test\\Web.Api.IntegrationTests\\Services\\GrpcTestFixture.cs:line 115
```

The server is configured to listen at `https://localhost:5000`. This happens when I use the default `TestServer.CreateHandler()`.

-----------------------------------------------------------------------------------
Does .Net Core 6 GRPC support HTTP/3? I configure `HttpHandler` with the following class:
```
public class Http3Handler : DelegatingHandler
{
    public Http3Handler() { }
    public Http3Handler(HttpMessageHandler innerHandler) : base(innerHandler) { }
    protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        request.Version = HttpVersion.Version30;
        request.VersionPolicy = HttpVersionPolicy.RequestVersionExact;
       return await base.SendAsync(request, cancellationToken); // throws exception here
    }
}
```
and assign it:
```
    HttpHandler = new Http3Handler(Fixture.Handler)
```
and bump into the same error and exception shown above.

### .NET Version

6.0.402

### Anything else?

Windows 11, Visual Studio 2022 17.3.6

**Comment by rafikiassumani-msft** [comment]
@khteh the sample code only supports `Startup.cs` and not `Program.cs`. We may add support for `Program.cs` in the future.

**Comment by khteh** [comment]
Isn't the sample code built for .Net 6 and the date of the article is "06/04/2022"?

**Comment by khteh** [comment]
Hello!!! Wasn't `startup.cs` removed in .Net 6 with minimal hosting model? How long should we wait to do integration tests on gRPC services!?!

**Comment by JamesNK** [comment]
It isn't removed. Both options are supported. If you need it then you should choose it over `WebApplicationBuilder`.

**Comment by davidfowl** [comment]
Do we have a doc on how to test with the minimal hosting model?

**Comment by kwaclaw** [comment]
I am also interested to see how I can test when I don't have a startup class in the gRPC server, but a Program.cs with only top level statements. It seems it is possible for MVC using the WebApplicationFactory.

**Comment by khteh** [comment]
Any update on this?

**Comment by jakoss** [comment]
> Do we have a doc on how to test with the minimal hosting model?

I don't believe so, it would be very useful

**Comment by khteh** [comment]
2.5 years on. Any update?

**Comment by khteh** [comment]
Where is the doc and/or sample how to do this grpc e2e test?

**Comment by khteh** [comment]
Not resolved. Please reopen!
