### ISSUE TITLE
Web API broken in .NET 7.0 after trimming

### ISSUE THREAD

**Issue by MarkusRodler** [dotnet/aspnetcore#44997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After upgrading multiple working projects from .NET 6.0 to .NET 7.0, all .NET Web Apis are broken that I tried.
I am using trimming and r2r.

### Steps To Reproduce

1. Create a new blank web api: `dotnet new webapi --use-minimal-apis -n Net7trimmingbug --no-https --no-openapi`
2. Add one simple route that calls a method to `Program.cs`: 
```c#
app.MapGet("{message}", (string message) => System.Console.WriteLine(message));
```
3. Use that csproj config with trimming and r2r enabled: 
```csproj
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishReadyToRunComposite>true</PublishReadyToRunComposite>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>copyused</TrimMode>
  </PropertyGroup>

</Project>
```
4. Publish and run the project and afterwards call that route:
```console
dotnet publish --configuration Debug --output app/publish --runtime linux-x64 --self-contained true

./app/publish/Net7trimmingbug 
```

### Exceptions (if any)

fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMM30E2TLGA4", Request id "0HMM30E2TLGA4:00000001": An unhandled exception was thrown by the application.
      System.InvalidOperationException: Encountered a parameter of type 'System.String' without a name. Parameters must have a name.
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.CreateArgument(ParameterInfo parameter, RequestDelegateFactoryContext factoryContext)
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.CreateArguments(ParameterInfo[] parameters, RequestDelegateFactoryContext factoryContext)
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.CreateArgumentsAndInferMetadata(MethodInfo methodInfo, RequestDelegateFactoryContext factoryContext)
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.InferMetadata(MethodInfo methodInfo, RequestDelegateFactoryOptions options)
         at Microsoft.AspNetCore.Routing.RouteEndpointDataSource.CreateRouteEndpointBuilder(RouteEntry entry, RoutePattern groupPrefix, IReadOnlyList`1 groupConventions, IReadOnlyList`1 groupFinallyConventions)
         at Microsoft.AspNetCore.Routing.RouteEndpointDataSource.get_Endpoints()
         at Microsoft.AspNetCore.Routing.CompositeEndpointDataSource.CreateEndpointsUnsynchronized()
         at Microsoft.AspNetCore.Routing.CompositeEndpointDataSource.EnsureEndpointsInitialized()
         at Microsoft.AspNetCore.Routing.CompositeEndpointDataSource.get_Endpoints()
         at Microsoft.AspNetCore.Routing.DataSourceDependentCache`1.Initialize()
         at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
         at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher..ctor(EndpointDataSource dataSource, Lifetime lifetime, Func`1 matcherBuilderFactory)
         at Microsoft.AspNetCore.Routing.Matching.DfaMatcherFactory.CreateMatcher(EndpointDataSource dataSource)
         at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.InitializeCoreAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatcher|8_0(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task`1 matcherTask)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

### .NET Version

7.0.100

**Comment by davidfowl** [comment]
Trimming isn't really supported for ASP.NET Core apps, it's best effort (if it works it works) until .NET 8. If you're looking for a workaround, it might be possible to help here.

If you remove `<TrimMode>copyused</TrimMode>` does it work?

**Comment by MarkusRodler** [comment]
Oh, this is a surprising info, because I use trimming successfully in several projects ASP.NET core projects with both .NET 6 and .NET 5.
Regarding `<TrimMode>copyused</TrimMode>`: If I remove it, then it works again. I didn't noticed, that `copyused` and `link` aren't supported anymore? But enabling them is accepted but breaks the application? I'm a little bit confused about that behaviour.

**Comment by MarkusRodler** [comment]
Yes

**Comment by MarkusRodler** [comment]
@sbomer Yes that works like before. Thanks.
