### ISSUE TITLE
Unable to configure HTTPS endpoint

### ISSUE THREAD

**Issue by utarn** [dotnet/aspnetcore#45023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am using Apple silicon MacOS. I have an existing dotnet 6 project which is working fine.
I install dotnet 7 using visual studio for mac.
After upgrading to dotnet 7, the project just cannot run.

`
System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Trusty.WebUI.Program.Main(String[] args) in /Users/utarn/projects/trusty_loose/src/WebUI/Program.cs:line 55
`

What I have tried and it's still not working.
- the steps in https://go.microsoft.com/fwlink/?linkid=848054 by removing and reinstalling dev certificate.
- create a fresh dotnet 7 project MVC from visual studio for mac.

What is still working
- create a fresh dotnet6 project MVC from visual studio for mac.

### Expected Behavior

Project created in dotnet7 should be running fine with installed dev certificate.

### Steps To Reproduce

https://github.com/utarn/dotnet7_fresh

### .NET Version

7.0.100

**Comment by Tratcher** [comment]
@adityamandaleeka

**Comment by adityamandaleeka** [comment]
@utarn Looks like you have a valid cert, but you might not have trusted it yet.

Can you try `dotnet dev-certs https --trust` ?

**Comment by utarn** [comment]
@adityamandaleeka I have tried dotnet dev-certs https --trust

After running, dotnet dev-certs https --check. It shows
No valid certificate found.

then, I tried sudo dotnet dev-certs https --check. It shows
The ASP.NET Core developer certificate is in an invalid state. To fix this issue, run 'dotnet dev-certs https --clean' and 'dotnet dev-certs https' to remove all existing ASP.NET Core development certificates and create a new untrusted developer certificate. On macOS or Windows, use 'dotnet dev-certs https --trust' to trust the new certificate.

Then I executed sudo dotnet dev-certs https --trust and  sudo dotnet dev-certs https --check. It shows
3 valid certificates were found: 3 certificates
    1) 3FDB7A583850C12FE38D8A576AA8ACCF908FC857 - CN=localhost - Valid from 2022-11-15 16:20:31Z to 2023-11-15 16:20:31Z - IsHttpsDevelopmentCertificate: true - IsExportable: true
    2) ADA65AD5489CA2282CBF0B70A0CB9CFC18E93049 - CN=localhost - Valid from 2022-11-15 16:18:07Z to 2023-11-15 16:18:07Z - IsHttpsDevelopmentCertificate: true - IsExportable: true
    3) C746D13A7DC746AFE4444F4BC26D0BA9A0A70BC5 - CN=localhost - Valid from 2022-11-15 16:18:10Z to 2023-11-15 16:18:10Z - IsHttpsDevelopmentCertificate: true - IsExportable: true
Run the command with both --check and --trust options to ensure that the certificate is not only valid but also trusted.


When I run program.cs. It shows 
System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Trusty.WebUI.Program.Main(String[] args) in /Users/utarn/projects/trusty_loose/src/WebUI/Program.cs:line 55

This my Program.cs. The 55th line is await host.RunAsync()
```
public class Program
{
    public static async Task Main(string[] args)
    {

        Log.Logger = new LoggerConfiguration()
            .Enrich.FromLogContext()
            .Enrich.WithExceptionDetails(new DestructuringOptionsBuilder()
                .WithDefaultDestructurers()
                .WithDestructurers(new[] { new DbUpdateExceptionDestructurer() }))
            .CreateBootstrapLogger();
        try
        {
            IHost? host = CreateHostBuilder(args).Build();
            using (IServiceScope scope = host.Services.CreateScope())
            {
                IServiceProvider services = scope.ServiceProvider;
                IConfiguration configuration = services.GetRequiredService<IConfiguration>();
                ApplicationDbContext context = services.GetRequiredService<ApplicationDbContext>();
                if (context.Database.IsNpgsql())
                {
                    await ApplicationDbContextSeed.ThaiParser(context, configuration);
                    await context.Database.MigrateAsync();
                }

                await ApplicationDbContextSeed.UpdateSequences(context);
                UserManager<ApplicationUser> userManager = services.GetRequiredService<UserManager<ApplicationUser>>();
                RoleManager<IdentityRole> roleManager = services.GetRequiredService<RoleManager<IdentityRole>>();
                AppProperty appProperty = services.GetRequiredService<AppProperty>();
                await ApplicationDbContextSeed.SeedDefaultUserAsync(userManager, roleManager, appProperty);
                await ApplicationDbContextSeed.SeedSampleDataAsync(context, appProperty);
            }

            await host.RunAsync();
        }
        catch (Exception e)
        {
            Log.Fatal(e, "An error occurred while migrating or seeding the database.");
        }
        finally
        {
            Log.CloseAndFlush();
        }
    }

    private static IHostBuilder CreateHostBuilder(string[] args)
    {
        return Host.CreateDefaultBuilder(args)
            .UseSerilog((context, services, configuration) => configuration
                .ReadFrom.Configuration(context.Configuration)
                .ReadFrom.Services(services)
                .Enrich.FromLogContext())
            .ConfigureWebHostDefaults(webBuilder =>
            {
                webBuilder.UseStartup<Startup>();
                webBuilder.UseKestrel(options =>
                {
                    options.Limits.MaxRequestBodySize = 1073741824; // 1GB
                });
            });
    }
}
```
