### ISSUE TITLE
Microsoft.AspNetCore.Connections.ConnectionResetException

### ISSUE THREAD

**Issue by PalanikumarNet** [dotnet/aspnetcore#45086]
I am still getting the exception in the middleware

Microsoft.AspNetCore.Connections.ConnectionResetException: The client has disconnected
 ---> System.Runtime.InteropServices.COMException (0x80070040): The specified network name is no longer available. (0x80070040)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.IIS.Core.IO.AsyncIOOperation.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadBody()
   at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
   at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ReadAsync(Memory`1 memory, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IIS.Core.HttpRequestStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.DrainAsync(Stream stream, ArrayPool`1 bytePool, Nullable`1 limit, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value, Object container)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)

I thought it would solve the problem.
How do I find the problem?

Thanks

_Originally posted by @tomerts in https://github.com/dotnet/aspnetcore/issues/24112#issuecomment-717274371_

**Comment by Tratcher** [comment]
The plan was to change BodyModelBinder to catch IOExceptions and return a 400 (not that the status code matters other than logging, the client has disconnected.) . This will prevent noisy stack traces from being logged unnecessarily.

**Comment by cuiliang** [comment]
Whish these logs never show in windows event log. 

![image](https://github.com/dotnet/aspnetcore/assets/1972649/8ec1ca12-4f4c-4b77-9e01-8a1b13a48cc5)

**Comment by montella1507** [comment]
<img width="727" alt="image" src="https://github.com/dotnet/aspnetcore/assets/10418323/6006eca7-6d4f-4d68-bcef-c0978b3dbd8d">
So... will we ever get this fix to stop spamming .NET exceptions for no reason?

**Comment by sebastianwhiffen** [comment]
Registering my interest in this being fixed also, currently logging unnecessary 500s and blaming a middleware for trying to read the context after its been closed

**Comment by Tmurdoch** [comment]
I would also like some more info as to how to fix this.

**Comment by mirekkukla** [comment]
Also very much looking forward to a fix here. This issue is preventing us from having in place a stricter exception monitoring-and-alert policy.

**Comment by gymshiashvili-smartsoft** [comment]
I'm also interested in resolving this issue.
