### ISSUE TITLE
MAUI + Blazor | IOS Release throws on virtual Parameter setter

### ISSUE THREAD

**Issue by David-Moreira** [dotnet/aspnetcore#45111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A user of our library, Blazorise (A Blazor components library) reported an issue where releasing MAUI blazor for iPhones will throw the following exception:

Additional context
Exception details:
```
Unable to set property 'Mode' on object of type 'Blazorise.Bar'. The error was: Attempting to JIT compile method '(wrapper delegate-invoke) void :invoke_callvirt_void_Bar_BarMode (Blazorise.Bar,Blazorise.BarMode)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.

at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.g__SetProperty|3_0(Object , PropertySetter , String , Object )
at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& , Object )
at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
at Blazorise.BaseComponent.SetParametersAsync(ParameterView parameters)
at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView )
```

### Expected Behavior

The behaviour gives the sense that something was trimmed in this specific configuration and it should not have been. 

Since Blazor `SetParametersAsync` uses reflection to set properties.

### Steps To Reproduce

- Usage of Blazor component's Virtual Parameters
- Release MAUI app for iOS

Steps to reproduce given by our user:

clone repo: https://github.com/emanuelpaul/BlazoriseMaui
use branch bar-bug
replace the value of CodesignKey and CodesignProvision with your values
run command dotnet build -t:Run -f net6.0-ios -p:_DeviceName={replace_with_your_iphone_identifier} -r ios-arm64 -c Release

### Exceptions (if any)

![image](https://user-images.githubusercontent.com/22283161/201989953-0ce902ec-f7ef-48c5-91b6-03b4fdd2ca45.png)

Additional context
Exception details:
```
Unable to set property 'Mode' on object of type 'Blazorise.Bar'. The error was: Attempting to JIT compile method '(wrapper delegate-invoke) void :invoke_callvirt_void_Bar_BarMode (Blazorise.Bar,Blazorise.BarMode)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.

at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.g__SetProperty|3_0(Object , PropertySetter , String , Object )
at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& , Object )
at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
at Blazorise.BaseComponent.SetParametersAsync(ParameterView parameters)
at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView )
```

### Anything else?

**Here's our issue for reference :** 
https://github.com/Megabit/Blazorise/issues/4166
![image](https://user-images.githubusercontent.com/22283161/201991132-a440b70a-dcc6-4448-b457-d9474dcd4e98.png)

**Our Parameters:**
![image](https://user-images.githubusercontent.com/22283161/201991276-9ddfbdd0-90bd-4f5b-83a7-6f4813dd30b3.png)
![image](https://user-images.githubusercontent.com/22283161/201991338-bc0413f3-4e0c-4d7d-a805-b5fd0ba085fd.png)

**Comment by mkArtakMSFT** [comment]
@Redth do you know where this should go?

**Comment by Eilon** [comment]
@rolfbjarne - does this look like it could be an issue with AOT/JIT for iOS? If so, do you know what repo we should move it to?

**Comment by rolfbjarne** [comment]
I think dotnet/runtime might be the right place, if the method in question hasn't been trimmed away, the AOT'ed code should be able to call it.
