### ISSUE TITLE
Net 7.0  Connection processing ended abnormally.

### ISSUE THREAD

**Issue by YongChingShieh** [dotnet/aspnetcore#45110]
### Description

when i update to net core 7.0 from 6.0 ,my web application is exceptional 

### Reproduction Steps

Unable to reproduce, this error occurs on the server

### Expected behavior

when i back to  6.0  this application is normal 

### Actual behavior

Log name: Application
Source: .NET Runtime
Date: 2022/11/14 14:44:16
Event ID: 1000
Task Category: None
Level: Warning
keywords: classic
User: N/A
Computer: GZ-ELECSPLIT
describe:
Category: Microsoft.AspNetCore.Server.Kestrel
EventId: 0
ConnectionId: 0HMM61BH9C4UV

Connection processing ended abnormally.

Exception: 
```
System.Net.Sockets.SocketException (995): An I/O operation was aborted due to thread exit or application request.
   at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
   at System.IO.Pipelines.Pipe.GetReadAsyncResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
```
[enent.zip](https://github.com/dotnet/runtime/files/10009207/enent.zip)

### Configuration

server info
windows  server 2008R2 SP1
```
dotnet --info

`.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download`

### Other information

<details>
<summary>app code</summary>

program.cs
```C#
Repository = LogManager.CreateRepository("NETCoreRepository");
XmlConfigurator.ConfigureAndWatch(Repository, new FileInfo("log4net.config"));
var builder = WebApplication.CreateBuilder(args);
builder.Host.UseSystemd();
builder.Services.AddHostedService<Worker>();
// Add services to the container.
AppSetting = builder.Configuration;
if (!Balancer)
{
    #region snippet_AddDistributedMemoryCache
    builder.Services.AddDistributedMemoryCache();
    #endregion
}
else
{
    builder.Services.AddStackExchangeRedisCache(options =>
    {
        //options.ProfilingSession = () => new ProfilingSession();
        options.Configuration = RedisConn;
        options.InstanceName = InstanceName;
    })
    .AddDataProtection().SetApplicationName(Sysname)
   .PersistKeysToStackExchangeRedis(ConnectionMultiplexer.Connect(RedisConn), Key);
}
//var jwtSettings = Configuration.GetSection("JwtSettings");
builder.Services.AddAuthentication(opt =>
{
    opt.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    opt.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
}).AddJwtBearer(options =>
{
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidateAudience = true,
        ValidateLifetime = true,
        ValidateIssuerSigningKey = true,
        ValidIssuer = ValidIssuer,
        ValidAudience = ValidAudience,
        ClockSkew = TimeSpan.Zero,
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(Key))
    };
});
// services.AddScoped<JwtHelpers>();
// InstanceName = $"RedisInstance{HttpUtility.UrlEncode(Sysname)}";
// ApiInstanceName = $"ApiRedisInstance{HttpUtility.UrlEncode(Sysname)}";
builder.Services.AddControllersWithViews();
// In production, the Angular files will be served from this directory
//builder.Services.AddSpaStaticFiles(configuration =>
//{
//    configuration.RootPath = "ClientApp/dist";
//});
builder.Services.AddMvc(option =>
{
    //option.ModelBinderProviders.Insert(0, new RawBodyModelBinderProvider());
    option.SuppressAsyncSuffixInActionNames = false;
}).AddNewtonsoftJson(options =>
{
    options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
    options.SerializerSettings.NullValueHandling = NullValueHandling.Ignore;
    options.SerializerSettings.MissingMemberHandling = MissingMemberHandling.Ignore;
    options.SerializerSettings.ContractResolver = new DefaultContractResolver();
});
builder.Services.AddCors(options =>
{
    options.AddPolicy("CorsPolicy", builder => builder
    .AllowAnyOrigin()
    .AllowAnyMethod()
    .AllowAnyHeader());
}).AddSignalR();
builder.Services.Configure((Action<FormOptions>)(x =>
{
    x.ValueLengthLimit = int.MaxValue;
    x.MultipartBodyLengthLimit = int.MaxValue; // In case of multipart
}))
.Configure((Action<ForwardedHeadersOptions>)(options =>
{
    options.ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
}));
builder.Services.Configure<KestrelServerOptions>(options =>
{

    options.AllowSynchronousIO = true;
});
//Enable BR GZIP Response compression
builder.Services.Configure<BrotliCompressionProviderOptions>(x =>
{
    x.Level = System.IO.Compression.CompressionLevel.Optimal;
}).Configure<GzipCompressionProviderOptions>(x =>
{
    x.Level = System.IO.Compression.CompressionLevel.Optimal;
}).AddResponseCompression(x =>
{
    x.Providers.Add<BrotliCompressionProvider>();
    x.Providers.Add<GzipCompressionProvider>();
});
var app = builder.Build();
// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
}
//Cache =app.Configuration.. distributedCache;
//AppSetting = app.Configuration ;
CurrentPath = app.Environment.ContentRootPath;
RootPath = $"{app.Environment.WebRootPath}{StaticFile}";
app.UseResponseCompression();
app.UseStaticFiles(new StaticFileOptions()
{
    ServeUnknownFileTypes = true,
    DefaultContentType = "application/octet-stream",
});
app.Use((context, next) =>
            {
                context.Request.EnableBuffering();
                return next();
            });
app.UseRouting();
app.UseAuthentication();
app.UseAuthorization();
app.UseCors("CorsPolicy");
app.MapHub<MyHub>("/myHub");
app.MapControllerRoute(
    name: "default",
    pattern: "{controller}/{action=Index}/{id?}");
app.MapFallbackToFile("index.html"); ;
await app.RunAsync();
```

</details>

**Comment by YongChingShieh** [comment]
> 
 I publish application by self-contained and Deployed using Windows service, the website cannot be opened after a while, but I don't see any error logs until I check the Windows event log
 sorry I can't reproduce this exception locally, because the user is using and the production environment is no longer allowed to test.Today, I've reverted to 6.0 and everything seems to be working fine.

**Comment by YongChingShieh** [comment]
> @YongChingShieh When do you see that exception? Does everything seem to work normally other than the fact that the exception is thrown?
> 
> Can you configure logging on the server and share the logs the next time this happens? https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-7.0#configure-logging

I publish application by self-contained and Deployed using Windows service, the website cannot be opened after a while, but I don't see any error logs until I check the Windows event log
sorry I can't reproduce this exception locally, because the user is using and the production environment is no longer allowed to test.Today, I've reverted to 6.0 and everything seems to be working fine.

**Comment by adityamandaleeka** [comment]
I see. By the way, you should be aware that Windows Server 2008 R2 has been out of support for a while: https://learn.microsoft.com/en-us/lifecycle/products/windows-server-2008-r2

Supported OS versions for .NET 7 can be found here: https://github.com/dotnet/core/blob/main/release-notes/7.0/supported-os.md

**Comment by YongChingShieh** [comment]
> I see. By the way, you should be aware that Windows Server 2008 R2 has been out of support for a while: https://learn.microsoft.com/en-us/lifecycle/products/windows-server-2008-r2
> 
> Supported OS versions for .NET 7 can be found here: https://github.com/dotnet/core/blob/main/release-notes/7.0/supported-os.md

I know 6.0 does not support windows server 2008,but reverted to 6.0 and everything is ok,whatever thanks for your help

**Comment by adityamandaleeka** [comment]
Glad it's working for you. I'll close this issue now... if you see it happening on a supported configuration, please let us know.
