### ISSUE TITLE
Add support for url pattern /v1/books/ext-{external_id} in grpc transcoding

### ISSUE THREAD

**Issue by jaiganeshs** [dotnet/aspnetcore#45126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to have an url pattern like /v1/books/ext-{external_id} to get a book by using an external id. The pattern is not accepted in grpc transcoding. I could have the same pattern in minimal api but not in grpc. 

### Describe the solution you'd like

Please add support for the pattern /v1/books/ext-{external_id}

**Comment by JamesNK** [comment]
Please elaborate on what you mean by not accepted? Does it not get matched? Does the app error on startup? What is the error message and stack trace?

**Comment by jaiganeshs** [comment]
The api does not start. I get the below exception.

Unhandled exception. System.InvalidOperationException: Error binding gRPC service 'BookService'.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Error binding GetBookByExternalId on BookService to HTTP API.
 ---> System.InvalidOperationException: Error parsing path template '/v1/books/ext-{external_id}'.
 ---> System.InvalidOperationException: Path segment must end with a '/'.
   at Grpc.Shared.HttpRoutePatternParser.ParseTemplate()
   at Grpc.Shared.HttpRoutePatternParser.Parse()
   --- End of inner exception stack trace ---
   at Grpc.Shared.HttpRoutePatternParser.Parse()
   at Grpc.Shared.HttpRoutePattern.Parse(String pattern)
   at Microsoft.AspNetCore.Grpc.JsonTranscoding.Internal.Binding.JsonTranscodingProviderServiceBinder`1.ParseRoute(String pattern, String body, String responseBody, MethodDescriptor methodDescriptor)
   at Microsoft.AspNetCore.Grpc.JsonTranscoding.Internal.Binding.JsonTranscodingProviderServiceBinder`1.AddMethodCore[TRequest,TResponse](Method`2 method, HttpRule httpRule, String pattern, String httpVerb, String body, String responseBody, MethodDescriptor methodDescriptor, CreateRequestDelegate`2 createRequestDelegate)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Grpc.JsonTranscoding.Internal.Binding.JsonTranscodingProviderServiceBinder`1.AddMethodCore[TRequest,TResponse](Method`2 method, HttpRule httpRule, String pattern, String httpVerb, String body, String responseBody, MethodDescriptor methodDescriptor, CreateRequestDelegate`2 createRequestDelegate)
   at Microsoft.AspNetCore.Grpc.JsonTranscoding.Internal.Binding.JsonTranscodingProviderServiceBinder`1.ProcessHttpRule[TRequest,TResponse](Method`2 method, MethodDescriptor methodDescriptor, HttpRule httpRule, CreateRequestDelegate`2 createRequestDelegate)
   at Microsoft.AspNetCore.Grpc.JsonTranscoding.Internal.Binding.JsonTranscodingProviderServiceBinder`1.AddMethod[TRequest,TResponse](Method`2 method, UnaryServerMethod`2 handler)
   at BackendGrpcApi.AccountingBook.BindService(ServiceBinderBase serviceBinder, AccountingBookBase serviceImpl) in D:\local-repos\DotnetK8sPoc\BackendGrpcApi\obj\Debug\net7.0\Protos\BookGrpc.cs:line 170
   at InvokeStub_AccountingBook.BindService(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.AspNetCore.Grpc.JsonTranscoding.Internal.Binding.JsonTranscodingServiceMethodProvider`1.OnServiceMethodDiscovery(ServiceMethodProviderContext`1 context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Grpc.JsonTranscoding.Internal.Binding.JsonTranscodingServiceMethodProvider`1.OnServiceMethodDiscovery(ServiceMethodProviderContext`1 context)
   at Grpc.AspNetCore.Server.Model.Internal.ServiceRouteBuilder`1.Build(IEndpointRouteBuilder endpointRouteBuilder)
   at Microsoft.AspNetCore.Builder.GrpcEndpointRouteBuilderExtensions.MapGrpcService[TService](IEndpointRouteBuilder builder)

**Comment by JamesNK** [comment]
Thanks.

gRPC JSON transcoding feature set matches what is available in other products. We follow the path spec at https://cloud.google.com/service-infrastructure/docs/service-management/reference/rpc/google.api#path-template-syntax. It doesn't allow for complex segments that mix a parameter and a literal.

Unfortunately the route you want isn't allowed. You would have to do something like: `/v1/books/{external_id}`. Or `/v1/books/ext/{external_id}`

Improvements we can make to address this topic in the future:
* Error message should be clearer that complex parameters aren't supported
* Documentation should mention that complex parameters aren't supported - https://learn.microsoft.com/en-us/aspnet/core/grpc/json-transcoding-binding?view=aspnetcore-7.0#route
