### ISSUE TITLE
Quarantine ServerComparison.FunctionalTests.HelloWorldTests.HelloWorld

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/aspnetcore#45378]
## Failing Test(s)

- ServerComparison.FunctionalTests.HelloWorldTests.HelloWorld

## Error Message

```text
| [0.354s] ServerComparison.FunctionalTests.HelloWorldTests Error: Test threw an exception.
| Xunit.Sdk.EqualException: Assert.Equal() Failure
|           ↓ (pos 0)
| Expected: Hello World X86
| Actual:   <!DOCTYPE html>\r\n<html lang="en-US" xmlns···
|           ↑ (pos 0)
|    at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences) in /_/src/xunit.assert/Asserts/StringAsserts.cs:line 326
|    at Xunit.Assert.Equal(String expected, String actual) in /_/src/xunit.assert/Asserts/StringAsserts.cs:line 234
|    at ServerComparison.FunctionalTests.HelloWorldTests.HelloWorld(TestVariant variant) in /_/src/Servers/test/FunctionalTests/HelloWorldTest.cs:line 73
|    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 264
| --- End of stack trace from previous location ---
|    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
|    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
| [0.362s] TestLifetime Information: Finished test HelloWorld-Server_IISExpress,_TFM_net7.0,_Type_Portable,_Arch_x86,_Host_InProcess in 0.3610566s
```

## Stacktrace

<details>

```text
   at ServerComparison.FunctionalTests.HelloWorldTests.HelloWorld(TestVariant variant) in /_/src/Servers/test/FunctionalTests/HelloWorldTest.cs:line 73
--- End of stack trace from previous location ---

```
</details>

## Logs

<details>

```text
| [0.001s] TestLifetime Information: Starting test HelloWorld-Server_IISExpress,_TFM_net7.0,_Type_Portable,_Arch_x86,_Host_InProcess at 2022-11-30T20:03:47
| [0.001s] TestLifetime Information: Starting test HelloWorld_IISExpress_net7.0_x86_Portable at 2022-11-30T20:03:47
| [0.001s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Deploying [Variation] :: ServerType=IISExpress, Runtime=CoreClr, Arch=x86, BaseUrlHint=, Publish=False
| [0.001s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Microsoft Windows NT 10.0.20348.0
| [0.002s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Executing: D:\a\_work\1\s\.dotnet\x86\dotnet.exe D:\a\_work\1\s\src\Servers\testassets\ServerComparison.TestSites\bin\Release\net7.0\ServerComparison.TestSites.dll
| [0.002s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: ContentRoot: D:\a\_work\1\s\src\Servers\testassets\ServerComparison.TestSites
| [0.003s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Attempting to start IIS Express on port: 51076
| [0.006s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Saving Config to C:\Users\cloudtest\AppData\Local\Temp\tmpob3d4m.tmp
| [0.006s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Executing command : C:\Program Files (x86)\IIS Express\iisexpress.exe /site:HttpTestSite /config:C:\Users\cloudtest\AppData\Local\Temp\tmpob3d4m.tmp /trace:error /systray:false
| [0.007s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Removing environment variable ASPNETCORE_ENVIRONMENT
| [0.007s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: SET ASPNETCORE_DETAILEDERRORS=true
| [0.007s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: SET ASPNETCORE_MODULE_DEBUG=console
| [0.007s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: SET LAUNCHER_PATH=D:\a\_work\1\s\.dotnet\x86\dotnet.exe
| [0.007s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: SET LAUNCHER_ARGS=D:\a\_work\1\s\src\Servers\testassets\ServerComparison.TestSites\bin\Release\net7.0\ServerComparison.TestSites.dll
| [0.007s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: SET ASPNETCORE_CONTENTROOT=D:\a\_work\1\s\src\Servers\testassets\ServerComparison.TestSites
| [0.010s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress Process 2728 started
| [0.143s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Starting IIS Express ...
| [0.181s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Initializing the W3 Server Started CTC = 2131156 
| [0.191s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: W3 Server initializing WinSock.  CTC = 2131171 
| [0.191s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: W3 Server WinSock initialized.  CTC = 2131171 
| [0.191s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: W3 Server ThreadPool initialized (ipm has signalled).  CTC = 2131171 
| [0.217s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [2022-11-30T20:03:47.239Z, PID: 2728] [aspnetcorev2.dll] Initializing logs for 'D:\a\_work\1\s\src\Servers\test\FunctionalTests\bin\Release\net7.0\ANCM\x86\aspnetcorev2.dll'. Process Id: 2728. File Version: 18.0.22334.0. Description: IIS ASP.NET Core Module V2. Commit: 63c49481c2e0462c65443a9dc68ec156a46d4d55.
| [0.218s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Start listenerChannel http:0
| [0.220s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Successfully registered URL "http://localhost:51076/" for site "HttpTestSite" application "/"
| [0.221s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Registration completed for site "HttpTestSite"
| [0.222s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: AppPool 'IISExpressAppPool' initialized
| [0.223s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: InitComplete event signalled
| [0.223s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: IIS Express is running.
| [0.223s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Started iisexpress successfully. Process Id : 2728, Port: 51076
| [0.223s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Application ready at URL: http://localhost:51076/
| [0.223s] HelloWorld Warning: Retry count 1..
| [0.223s] System.Net.Http.HttpClient Debug: Sending GET http://localhost:51076/
| [0.226s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: IncrementMessages called
| [0.230s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Request started: "GET" http://localhost:51076/
| [0.237s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [2022-11-30T20:03:47.259Z, PID: 2728] [aspnetcorev2.dll] Resolving hostfxr parameters for application: 'D:\a\_work\1\s\.dotnet\x86\dotnet.exe' arguments: 'D:\a\_work\1\s\src\Servers\testassets\ServerComparison.TestSites\bin\Release\net7.0\ServerComparison.TestSites.dll' path: 'D:\a\_work\1\s\src\Servers\testassets\ServerComparison.TestSites\'
| [0.237s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [2022-11-30T20:03:47.259Z, PID: 2728] [aspnetcorev2.dll] Known dotnet.exe location: ''
| [0.237s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [2022-11-30T20:03:47.259Z, PID: 2728] [aspnetcorev2.dll] Process path 'D:\a\_work\1\s\.dotnet\x86\dotnet.exe' is dotnet, treating application as portable
| [0.237s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [2022-11-30T20:03:47.259Z, PID: 2728] [aspnetcorev2.dll] hostfxr.dotnet_root: 'D:\a\_work\1\s\.dotnet\x86'
| [0.237s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [2022-11-30T20:03:47.259Z, PID: 2728] [aspnetcorev2.dll] hostfxr.assembly_path: 'D:\a\_work\1\s\src\Servers\testassets\ServerComparison.TestSites\'
| [0.238s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [2022-11-30T20:03:47.261Z, PID: 2728] [aspnetcorev2.dll] get_hostfxr_path failed (80008083)
| [0.239s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [2022-11-30T20:03:47.261Z, PID: 2728] [aspnetcorev2.dll] Resolving absolute path to dotnet.exe from 'D:\a\_work\1\s\.dotnet\x86\dotnet.exe'
| [0.239s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [2022-11-30T20:03:47.261Z, PID: 2728] [aspnetcorev2.dll] Found dotnet.exe at 'D:\a\_work\1\s\.dotnet\x86\dotnet.exe'
| [0.239s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [2022-11-30T20:03:47.261Z, PID: 2728] [aspnetcorev2.dll] Trying get_hostfxr_path with dotnet path as dotnet root
| [0.239s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [2022-11-30T20:03:47.261Z, PID: 2728] [aspnetcorev2.dll] hostfxr.dotnet_root: 'D:\a\_work\1\s\.dotnet\x86'
| [0.239s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [2022-11-30T20:03:47.261Z, PID: 2728] [aspnetcorev2.dll] hostfxr.assembly_path: 'D:\a\_work\1\s\src\Servers\testassets\ServerComparison.TestSites\'
| [0.239s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [2022-11-30T20:03:47.262Z, PID: 2728] [aspnetcorev2.dll] get_hostfxr_path failed (80008083)
| [0.241s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [2022-11-30T20:03:47.263Z, PID: 2728] [aspnetcorev2.dll] Event Log: 'Application 'D:\a\_work\1\s\src\Servers\testassets\ServerComparison.TestSites\' failed to start. Exception message:
| [0.241s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: get_hostfxr_path failed' 
| [0.241s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: End Event Log Message.
| [0.242s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [2022-11-30T20:03:47.263Z, PID: 2728] [aspnetcorev2.dll] InvalidOperationException 'get_hostfxr_path failed' caught at D:\a\_work\1\s\src\Servers\IIS\AspNetCoreModuleV2\CommonLib\HostFxrResolutionResult.cpp:64 
| [0.242s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [2022-11-30T20:03:47.264Z, PID: 2728] [aspnetcorev2.dll] Failed HRESULT returned: 0x8007023e at D:\a\_work\1\s\src\Servers\IIS\AspNetCoreModuleV2\AspNetCore\HandlerResolver.cpp:70 
| [0.242s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [2022-11-30T20:03:47.264Z, PID: 2728] [aspnetcorev2.dll] Failed HRESULT returned: 0x8007023e at D:\a\_work\1\s\src\Servers\IIS\AspNetCoreModuleV2\AspNetCore\HandlerResolver.cpp:175 
| [0.242s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [2022-11-30T20:03:47.265Z, PID: 2728] [aspnetcorev2.dll] Failed HRESULT returned: 0x8007023e at D:\a\_work\1\s\src\Servers\IIS\AspNetCoreModuleV2\AspNetCore\applicationinfo.cpp:195 
| [0.242s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [2022-11-30T20:03:47.265Z, PID: 2728] [aspnetcorev2.dll] Failed HRESULT returned: 0x8007023e at D:\a\_work\1\s\src\Servers\IIS\AspNetCoreModuleV2\AspNetCore\applicationinfo.cpp:108 
| [0.243s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: [2022-11-30T20:03:47.265Z, PID: 2728] [aspnetcorev2.dll] Event Log: 'Failed to start application '/LM/W3SVC/1/ROOT', ErrorCode '0x8007023e'.' 
| [0.243s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: End Event Log Message.
| [0.244s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress stdout: Response sent: http://localhost:51076/ with HTTP status 500.0
| [0.247s] System.Net.Http.HttpClient Debug: Received InternalServerError Internal Server Error http://localhost:51076/
| [0.253s] HelloWorld Warning: StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
|                              {
|                                Server: Microsoft-IIS/10.0
|                                X-SourceFiles: =?UTF-8?B?RDpcYVxfd29ya1wxXHNcc3JjXFNlcnZlcnNcdGVzdGFzc2V0c1xTZXJ2ZXJDb21wYXJpc29uLlRlc3RTaXRlcw==?=
|                                X-Powered-By: ASP.NET
|                                Date: Wed, 30 Nov 2022 20:03:46 GMT
|                                Content-Type: text/html
|                                Content-Length: 2254
|                              }
| [0.253s] HelloWorld Warning: <!DOCTYPE html>
|                              <html lang="en-US" xmlns="http://www.w3.org/1999/xhtml">
|                                  <head>
|                                      <meta charset="utf-8" />
|                                      <title> HTTP Error 500.0 - ASP.NET Core IIS hosting failure (in-process) </title>
|                                      <style>
|                                          body {
|                                              font-family: 'Segoe UI', Tahoma, Arial, Helvetica, sans-serif;
|                                              font-size: .813em;
|                                              color: #222;
|                                              background-color: #fff;
|                                          }
|                                          h1, h2, h3, h4, h5 {
|                                              /*font-family: 'Segoe UI',Tahoma,Arial,Helvetica,sans-serif;*/
|                                              font-weight: 100;
|                                          }
|                                          h1 {
|                                              color: #44525e;
|                                              margin: 15px 0 15px 0;
|                                          }
|                                          h2 {
|                                              margin: 10px 5px 0 0;
|                                          }
|                                          h3 {
|                                              color: #363636;
|                                              margin: 5px 5px 0 0;
|                                          }
|                                          code {
|                                              font-family: Consolas, "Courier New", courier, monospace;
|                                          }
|                                          body .titleerror {
|                                              padding: 3px 3px 6px 3px;
|                                              display: block;
|                                              font-size: 1.5em;
|                                              font-weight: 100;
|                                          }
|                                          a {
|                                              color: #1ba1e2;
|                                              text-decoration: none;
|                                          }
|                                              a:hover {
|                                                  color: #13709e;
|                                                  text-decoration: underline;
|                                              }
|                                          li {
|                                              margin: 5px;
|                                          }
|                                      </style>
|                                  </head>
|                                  <body>
|                                      <h1> HTTP Error 500.0 - ASP.NET Core IIS hosting failure (in-process) </h1>
|                                      
|                                      
|                                      <h2> Troubleshooting steps: </h2>
|                                      <ul>
|                                          <li> Check the system event log for error messages </li>
|                                          <li> Enable logging the application process' stdout messages </li>
|                                          <li> Attach a debugger to the application process and inspect </li>
|                                      </ul>
|                                      <h2>
|                                          For more guidance on diagnosing and handling these errors, visit
|                                           <a href="https://go.microsoft.com/fwlink/?LinkID=2028526"> <cite>Troubleshoot ASP.NET Core on Azure App Service and IIS</cite></a>.
|                                      </h2>
|                                  </body>
|                              </html>
| [0.254s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Attempting to cancel process 2728
| [0.349s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: iisexpress Process 2728 shut down
| [0.350s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Host process shutting down.
| [0.350s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: Successfully terminated host process with process Id '2728'
| [0.350s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Debug: Deleting applicationHost.config file from C:\Users\cloudtest\AppData\Local\Temp\tmpob3d4m.tmp
| [0.350s] Microsoft.AspNetCore.Server.IntegrationTesting.IIS.IISExpressDeployer Information: [Time]: Total time taken for this test variation '0.348781' seconds
| [0.350s] TestLifetime Information: Finished test HelloWorld_IISExpress_net7.0_x86_Portable in 0.3494779s
| [0.354s] ServerComparison.FunctionalTests.HelloWorldTests Error: Test threw an exception.
| Xunit.Sdk.EqualException: Assert.Equal() Failure
|           ↓ (pos 0)
| Expected: Hello World X86
| Actual:   <!DOCTYPE html>\r\n<html lang="en-US" xmlns···
|           ↑ (pos 0)
|    at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences) in /_/src/xunit.assert/Asserts/StringAsserts.cs:line 326
|    at Xunit.Assert.Equal(String expected, String actual) in /_/src/xunit.assert/Asserts/StringAsserts.cs:line 234
|    at ServerComparison.FunctionalTests.HelloWorldTests.HelloWorld(TestVariant variant) in /_/src/Servers/test/FunctionalTests/HelloWorldTest.cs:line 73
|    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 264
| --- End of stack trace from previous location ---
|    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
|    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
| [0.362s] TestLifetime Information: Finished test HelloWorld-Server_IISExpress,_TFM_net7.0,_Type_Portable,_Arch_x86,_Host_InProcess in 0.3610566s

```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=98033&view=ms.vss-test-web.build-test-results-tab&runId=2091228&resultId=100028&paneView=attachments

**Comment by TanayParikh** [comment]
cc/ @Tratcher

**Comment by adityamandaleeka** [comment]
Triage: this fails 100% of the time locally and about a third of the time on CI. Let's investigate.

**Comment by Tratcher** [comment]
These tests aren't showing up in the quarantined test run??

They're also failing for a different reason after a recent logging change.
```
Assert.Contains() Failure\r\nNot found: /throwexception - - - 500\r\n
In value:  
...Request finished HTTP/1.1 GET http://127.0.0.1:56915/throwexception - 500 0 - 177.4494ms\n
```

Caused by this change?
https://github.com/dotnet/aspnetcore/commit/dd50702e565a82d0e24d6c4de5bf8f3309860376#diff-f75e760996bd0251366c4eabc2997d28a4014cbc90cdefc18c619a9d5a1d9d02R66


https://dev.azure.com/dnceng-public/public/_build/results?buildId=112194&view=ms.vss-test-web.build-test-results-tab&runId=2384608&paneView=debug&resultId=100008

**Comment by Tratcher** [comment]
The throwexception log has been fixed, the original issue remains.

**Comment by amcasey** [comment]
Locally, I'm seeing
```html
<!DOCTYPE html>
<html lang="en-US" xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta charset="utf-8" />
        <title> HTTP Error 500.31 - Failed to load ASP.NET Core runtime </title>
        <style>
<!-- SNIP -->
        </style>
    </head>
    <body>
        <h1> HTTP Error 500.31 - Failed to load ASP.NET Core runtime </h1>

        <h2> Common solutions to this issue: </h2>The specified version of Microsoft.NetCore.App or Microsoft.AspNetCore.App was not found.

        <h2>Specific error detected by ANCM:</h2><h3>Provided application path does not exist, or isn't a .dll or .exe.</h3>

        <h2> Troubleshooting steps: </h2>
        <ul>
            <li> Check the system event log for error messages </li>
            <li> Enable logging the application process' stdout messages </li>
            <li> Attach a debugger to the application process and inspect </li>
        </ul>

        <h2>
            For more guidance on diagnosing and handling these errors, visit
             <a href="https://go.microsoft.com/fwlink/?LinkID=2028526"> <cite>Troubleshoot ASP.NET Core on Azure App Service and IIS</cite></a>.
        </h2>
    </body>
</html>
```
