### ISSUE TITLE
ReadOnly exception from dotnet core middleware - Kubernetes container pods with a read-only filesystem

### ISSUE THREAD

**Issue by satishviswanathan** [dotnet/aspnetcore#45476]
SDK : 5.0.101

We are running dotnet core web api in Kubernetes container pods with a read-only filesystem.

As per the recommendation given on this thread. (https://github.com/dotnet/aspnetcore/issues/33333). We have replaced Newtsonsoft with System.Text.Json but still we are seeing this issue. I'm not sure what we are missing, sharing the stack trace.

Any help is appreciated on this.

      System.IO.IOException: Read-only file system
31
         at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
30
         at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
29
         at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
28
         at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.CreateTempFile()
27
         at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
26
         at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
25
         at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
24
         at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)

**Comment by Tratcher** [comment]
5.0 is obsolete and improvements have been made to the formatters since then. Can you try this on 6.0 or 7.0?

System.Text.Json shouldn't require FileBufferingReadStream. We'd need to figure out what's enabling buffering.

**Comment by satishviswanathan** [comment]
@Tratcher thank you for your response.

**Comment by satishviswanathan** [comment]
@Tratcher do you think apart from using System.Text.Json I should be suppressing the file buffering as well. Currently I don't have that set.

services
        .AddControllers(options =>
        {
            // Suppress buffering through the file system
            options.SuppressOutputFormatterBuffering = true;
        });

**Comment by Tratcher** [comment]
This is the input formatter, not output. It shouldn't be buffering by default, at least not in .NET 6.

We use https://learn.microsoft.com/en-us/dotnet/api/system.io.path.gettempfilename?view=net-7.0.
https://learn.microsoft.com/en-us/dotnet/api/system.io.path.gettemppath?view=net-7.0&tabs=linux

**Comment by adityamandaleeka** [comment]
@satishviswanathan Can you try this on .NET 6 or 7 and let us know if the issue still exists?
