### ISSUE TITLE
support single file embedded assemblies

### ISSUE THREAD

**Issue by kasperk81** [dotnet/aspnetcore#45504]
runtime compilation in .net 6 app published as a single file (`<PublishSingleFile>true</PublishSingleFile>`) works only with extraction to filesystem (`<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>`).

without extraction, it throws:
```
      System.ArgumentException: The value cannot be an empty string. (Parameter 'path')
         at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
         at System.IO.Strategies.FileStreamHelpers.ValidateArguments(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
         at System.IO.File.OpenRead(String path)
         at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RazorReferenceManager.CreateMetadataReference(String path)
         at System.Linq.Enumerable.SelectListIterator`2.ToList()
         at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RazorReferenceManager.GetCompilationReferences()
         at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
         at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RazorReferenceManager.get_CompilationReferences()
         at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.LazyMetadataReferenceFeature.get_References()
         at Microsoft.CodeAnalysis.Razor.CompilationTagHelperFeature.GetDescriptors()
         at Microsoft.AspNetCore.Razor.Language.DefaultRazorTagHelperBinderPhase.ExecuteCore(RazorCodeDocument codeDocument)
         at Microsoft.AspNetCore.Razor.Language.RazorEnginePhaseBase.Execute(RazorCodeDocument codeDocument)
         at Microsoft.AspNetCore.Razor.Language.DefaultRazorEngine.Process(RazorCodeDocument document)
         at Microsoft.AspNetCore.Razor.Language.DefaultRazorProjectEngine.ProcessCore(RazorCodeDocument codeDocument)
         at Microsoft.AspNetCore.Razor.Language.RazorProjectEngine.Process(RazorProjectItem projectItem)
         at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RuntimeViewCompiler.CompileAndEmit(String relativePath)
         at Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation.RuntimeViewCompiler.OnCacheMiss(String normalizedPath)
      --- End of stack trace from previous location ---
```

https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli#api-incompatibility

if file-on-disk requirement is the only thing limiting user to access razor runtime compilation in `PublishSingleFile` apps, please consider adding support of in-memory assemblies without going through file i/o.

aside: in .net 7, this problem becomes real with `<PublishAot>true</PublishAot>`. there is no workaround as `IncludeAllContentForSelfExtract` because nativeaot does not use apphost.

**Comment by kasperk81** [comment]
> In general it feels like these are two incompatible asks: to be ahead of time compiled, but also to do runtime compilation.

they are not. aot supports subset of reflection apis. if compilation code is restricted to just use those apis (and other apis on the "aot supported" surface) then it will be compatible with nativeaot. reading assemblies from memory map (bundle) is a plus for both singlfile and nativeaot.

**Comment by yaobo-lab** [comment]
i had the same problem. did you solve it?

**Comment by yaobo-lab** [comment]
i use.net 8, The problem still exists.

**Comment by martincostello** [comment]
#53859

**Comment by sqlnew** [comment]
In the .net 8, The problem still exists.
When using the Microsoft AspNetCore MVC Razor The RuntimeCompilation component to publish the asp.net core razor page project as a single file project and calling the dynamic compilation time AddRazorRuntimeCompilation, the same error occurs

Detailed problem description in this place
https://github.com/dotnet/aspnetcore/issues/54315

**Comment by jjxtra** [comment]
Error still exists in .NET 9

**Comment by FerhatAldemir** [comment]
You're using .NET 8 and this issue has become critical for you, taking up a lot of your time, and you still haven't solved it.

**Comment by FerhatAldemir** [comment]
Do you have any suggestions for a solution?

**Comment by gpisano97** [comment]
Hello, i'm using .NET10 and i have the same issue. I solved adding `<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>` to the project.
