### ISSUE TITLE
IIS with Blazor Webassembly ASP hosted application throws Exception trying to retrieve data from SQL Server (api calls) 

### ISSUE THREAD

**Issue by rhproj** [dotnet/aspnetcore#45670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

My Blazor Webassembly ASP.NET Core 6.0 hosted app is published to IIS 10.0 (Windows 10). It has api calls to SQL Server.
I can't get my collection (`List<string>`) populated from SQL server and Web Browser shows error:

```
fail: MyBlazorWebbAssemblyApp.Client.Pages.RedirectedAppeal.MyClientPage[0]
ExpectedJsonTokens Path: $ | LineNumber: 0 | BytePositionInLine: 0. :StackTrace:    at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& , JsonReaderException )
         at System.Text.Json.Serialization.JsonConverter`1[[System.Collections.Generic.List`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
         at System.Text.Json.JsonSerializer.ReadCore[List`1](JsonConverter , Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
         at System.Text.Json.JsonSerializer.ReadCore[List`1](JsonReaderState& , Boolean , ReadOnlySpan`1 , JsonSerializerOptions , ReadStack& , JsonConverter )
         at System.Text.Json.JsonSerializer.ContinueDeserialize[List`1](ReadBufferState& , JsonReaderState& , ReadStack& , JsonConverter , JsonSerializerOptions )
         at System.Text.Json.JsonSerializer.<ReadAllAsync>d__65`1[[System.Collections.Generic.List`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
         at System.Net.Http.Json.HttpContentJsonExtensions.<ReadFromJsonAsyncCore>d__4`1[[System.Collections.Generic.List`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
         at WorkGroupProsecutor.Client.Pages.RedirectedAppeal.RedirectedPage.OnInitializedAsync() :#: System.Text.Json.JsonReaderException: ExpectedJsonTokens LineNumber: 0 | BytePositionInLine: 0.
         at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& , ExceptionResource , Byte , ReadOnlySpan`1 )
         at System.Text.Json.Utf8JsonReader.Read()
         at System.Text.Json.Serialization.JsonConverter`1[[System.Collections.Generic.List`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
```

I don't get this error when it runs in visual studio 
! Or even if I run my published app on **kestrel** like so: `dotnet myapp.dll` Unfortunatelly i have to publish it to IIS.

# The call chain:
**Clients Page:**

```razor
@inject HttpClient httpClient
@inject ILogger<MyClientPage> logger

@foreach (var period in periodsList) @*Some UI element where my List is shown:*@
{
   ...             
}

@code{
private List<string> periodsList = new();
protected override async Task OnInitializedAsync() //Where i get my error:
{
try
{
   periodsList = await httpClient.GetFromJsonAsync<List<string>>($"api/RedirectedAppeal/{"Az"}/{2022}");
}
catch(Exception ex)
{ logger.LogError($"{ex.Message} :StackTrace: {ex.StackTrace}" }
}
```

I also tryied **rephrase** the List population like this:

```c#
protected override async Task OnInitializedAsync() //Where i get my error:
{
   var periods = await httpClient.GetAsync($"api/RedirectedAppeal/{"Az"}/{2022}");
   periodsList = await periods.Content.ReadFromJsonAsync<List<string>>();
}
```
but got the same error :(

and like this:
```
periodsList = await JsonSerializer.DeserializeAsync<List<string>>(await httpClient.GetStreamAsync($"api/RedirectedAppeal/{"Az"}/{2022}"));
```
got me this error:
```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: net_http_message_not_success_statuscode, 500, Internal Server Error
System.Net.Http.HttpRequestException: net_http_message_not_success_statuscode, 500, Internal Server Error
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.Json.HttpClientJsonExtensions.<GetFromJsonAsyncCore>d__13`1[[System.Collections.Generic.List`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at BzrIIStest.Client.Pages.CatNamesPage.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )
```

**Controller (RedirectedAppealController.cs):**
```
[HttpGet("{district}/{year}")]
public async Task<IEnumerable<string>> Get(string district, int year)
{
   return await _appealRepository.GetRedirectedAppealPeriods(district, year);
}
```

**Repository (AppealRepository.cs):**
```
public async Task<IEnumerable<string>> GetRedirectedAppealPeriods(string district, int year)
{
    return await _dbContext.RedirectedAppeal
        .Where(a => a.District == district)
        .Where(a => a.YearInfo == year).Select(p => p.PeriodInfo).Distinct().ToListAsync(); 
}
```

Calls made in **Swagger** also return 500 Error: Internal Server Error
```
Response headers
 date: Tue,13 Dec 2022 10:02:00 GMT 
 server: Microsoft-IIS/10.0 
 transfer-encoding: chunked 
 x-powered-by: ASP.NET 
```
# I tried:
I tried to use windows authentication and adding login and user to SQL Server (accordingly using connection string with Integrated Security=True and with User id and password)

I tried to twiggle IIS (.Net CLR Version - No Managed Code) by giving access in my SQL Server to it's App Pool

I have no firewall or port access issues. 

Tried using GetFromJsonAsync and ReadFromJsonAsync as i mentioned above

```
periodsList = await httpClient.GetFromJsonAsync<List<string>>($"api/RedirectedAppeal/{"Az"}/{2022}");
```
vs
```
var periods = await httpClient.GetAsync($"api/RedirectedAppeal/{"Az"}/{2022}");
periodsList = await periods.Content.ReadFromJsonAsync<List<string>>();
```
vs
```
periodsList = await JsonSerializer.DeserializeAsync<List<string>>(await httpClient.GetStreamAsync($"api/RedirectedAppeal/{"Az"}/{2022}"));

```

In the controller i tried to wrap calls in IActionResult with Ok like so:
```
[HttpGet("{district}/{year}")]
public async Task<IActionResult> Get(string district, int year)
{
    return Ok(await _appealRepository.GetRedirectedAppealPeriods(district, year));
}
```

I also tryed to do it synchronously (even though HttpClient not a big fan of it >.<)

And i tried to use different browsers of course! No success :(

I have added Failed Request Tracing Rules, it doesn't show much unfortunatelly:
```
ModuleName="AspNetCoreModuleV2", Notification="EXECUTE_REQUEST_HANDLER", HttpStatus="500", HttpReason="Internal Server Error", HttpSubStatus="0", ErrorCode="The operation completed successfully.
 (0x0)", ConfigExceptionInfo=""
```

Any ideas? Thank you all in advance!

### Expected Behavior

I want pablished on IIS Blazor WASM hosted app to be able to retrieve data from SQL Server

# Steps To Reproduce
I created simplified and cute :3 project to anyone who's willing to try it out - 1 table with 1 string field. Works perfectly on kestrel and wile running on express version vie Visual studio. All i'm trying to do is to make it work in a published IIS project.
Migrations to generate DB via EF are included: 

[Sample Project to recreate error](https://github.com/rhproj/IIS_WASM_issue)

## Failed Request Tracing Rules, it doesn't show much unfortunatelly:

```
ModuleName="AspNetCoreModuleV2", Notification="EXECUTE_REQUEST_HANDLER", HttpStatus="500", HttpReason="Internal Server Error", HttpSubStatus="0", ErrorCode="The operation completed successfully.
 (0x0)", ConfigExceptionInfo=""
```

 ## Exceptions shown in Browser varies depends on the way my call looks like (see above in description)

```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: net_http_message_not_success_statuscode, 500, Internal Server Error
System.Net.Http.HttpRequestException: net_http_message_not_success_statuscode, 500, Internal Server Error
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.Json.HttpClientJsonExtensions.<GetFromJsonAsyncCore>d__13`1[[System.Collections.Generic.List`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at BzrIIStest.Client.Pages.CatNamesPage.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )
```

### .NET Version

6

### Anything else?

IIS 10, Windows 10, EF 6 or 7 (don't matter error is the same)

**Comment by MackinnonBuck** [comment]
Thanks for reaching out, @rhproj.

Could you please check the network tab in the browser's developer tools to see if the response sent from the server is valid? It appears an error is being thrown from your API when it is deployed. What's likely happening is the exception being thrown on the sever is causing an HTML response for the 500 error, and attempting to parse the HTML as JSON is throwing an exception on the client side.

Could you also turn on detailed errors in IIS to see if that gives any more information about what the problem is? You can do this by adding this to your `web.config` file:

```
<system.webServer>
    <httpErrors errorMode="Detailed" />
</system.webServer>
```

**Comment by rhproj** [comment]
Thank you for your response, Mackinnon Buck! I apriciate any suggestion
Yep network tab shows status 500 on Values.
And I've added the line to my web.config, that's what i get in browser:
`blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: ExpectedStartOfValueNotFound, < Path: $ | LineNumber: 1 | BytePositionInLine: 0.
System.Text.Json.JsonException: ExpectedStartOfValueNotFound, < Path: $ | LineNumber: 1 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: ExpectedStartOfValueNotFound, < LineNumber: 1 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& , ExceptionResource , Byte , ReadOnlySpan`1 )

Can't decipher much from it, and Failed Request Tracing still doesn't show much:
`ModuleName="AspNetCoreModuleV2", Notification="EXECUTE_REQUEST_HANDLER", HttpStatus="500", HttpReason="Internal Server Error", HttpSubStatus="0", ErrorCode="The operation completed successfully.
 (0x0)", ConfigExceptionInfo=""`

**Comment by adityamandaleeka** [comment]
@rhproj Have you tried running it in IIS Express? If you select IIS Express as your debug target and start debugging you'll likely see some interesting exception/error on the server that's causing the 500 to be returned.

**Comment by adityamandaleeka** [comment]
Since you mentioned that it only fails when doing the data access on IIS, I also wonder if this could be related to the fact that your server, when running in IIS, is running under a different user (one that perhaps doesn't have access to the DB?).
