### ISSUE TITLE
Support pnpm that installed using a standalone script in SpaProxyLaunchCommand

### ISSUE THREAD

**Issue by sunghwan2789** [dotnet/aspnetcore#45700]
Given a ASP.NET project with SPA setup:
```xml
  <PropertyGroup>
    <SpaRoot>client-app\</SpaRoot>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(SpaRoot)node_modules\**</DefaultItemExcludes>
    <SpaProxyServerUrl>https://localhost:5173</SpaProxyServerUrl>
    <SpaProxyLaunchCommand>pnpm dev</SpaProxyLaunchCommand>
  </PropertyGroup>
```

`SpaProxyLaunchManager` failes to launch SPA development server, saying it cannot find 'pnpm.cmd':
```
info: Microsoft.AspNetCore.SpaProxy.SpaProxyLaunchManager[0]
      No SPA development server running at https://localhost:5173 found.
fail: Microsoft.AspNetCore.SpaProxy.SpaProxyLaunchManager[0]
      Failed to launch the SPA development server 'pnpm dev'.
      System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'pnpm.cmd' with working directory 'C:\project\client-app\'. 지정된 파일을 찾을 수 없습니다.
         at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
         at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
         at Microsoft.AspNetCore.SpaProxy.SpaProxyLaunchManager.LaunchDevelopmentProxy()
fail: Microsoft.AspNetCore.SpaProxy.SpaProxyLaunchManager[0]
      Couldn't start the SPA development server with command 'pnpm dev'.
info: Microsoft.AspNetCore.SpaProxy.SpaProxyMiddleware[0]
      SPA proxy is not ready. Returning temporary landing page.
```

It makes sense because, using a [pnpm installation standalone script](https://pnpm.io/installation#on-windows), we do not have `pnpm.cmd`, but only `pnpm.exe` at `%localappdata%\pnpm\`.

I know I can use pnpm modifying `SpaProxyLaunchCommand` to have the extension like `pnpm.exe dev`,

https://github.com/dotnet/aspnetcore/blob/589aa11b5c631ce719e0530d66be8324a6d79169/src/Middleware/Spa/SpaProxy/src/SpaProxyLaunchManager.cs#L169-L174

but it would be great if we could omit it.

**Comment by morganbp** [comment]
I can create a pull request on this. Should I just remove that entire if test then?

**Comment by sunghwan2789** [comment]
As a workaround, I could invoke the shell with launch commands:
```
    <SpaProxyLaunchCommand>pnpm i &amp;&amp; pnpm dev</SpaProxyLaunchCommand>
    <SpaProxyLaunchCommand Condition="$([MSBuild]::IsOsPlatform('Windows'))">cmd.exe /s /c $(SpaProxyLaunchCommand)</SpaProxyLaunchCommand>
    <SpaProxyLaunchCommand Condition="$([MSBuild]::IsOSUnixLike())">sh -c '$(SpaProxyLaunchCommand)'</SpaProxyLaunchCommand>
```

**Comment by MattyLeslie** [comment]
> Hello @javiercn , would amending the following code:
> 
> https://github.com/dotnet/aspnetcore/blob/589aa11b5c631ce719e0530d66be8324a6d79169/src/Middleware/Spa/SpaProxy/src/SpaProxyLaunchManager.cs#L169-L176
> 
> 
> To something that checks for both `.cmd` and `.exe` files within the working directory and then allocating the relevant `command.extension` be feasible to hopefully future proof this case against .exe files ?
> ```
>             if (OperatingSystem.IsWindows() && !Path.HasExtension(command))
>             {
>                 var commandWithCmdExtension = $"{command}.cmd";
>                 var commandWithExeExtension = $"{command}.exe";
> 
>                 if (File.Exists(Path.Combine(WorkingDirectory, commandWithCmdExtension)))
>                 {
>                     command = commandWithCmdExtension;
>                 }
>                 else if (File.Exists(Path.Combine(WorkingDirectory, commandWithExeExtension)))
>                 {
>                     command = commandWithExeExtension;
>                 }
>             }
> ```

Hello @javiercn just looking for a follow up on this. Many thanks

**Comment by AllainPL** [comment]
Another instance, with a much bigger affected population than the pnpm standalone script: nvm-windows v2 shipped this month and defaults to "shim mode", which puts `node.exe`, `npm.exe`, `npx.exe` and `pnpm.exe` on PATH and no `.cmd` files at all. So `npm start` in a stock `dotnet new` SPA template fails out of the box there, same Win32 (2) on `npm.cmd`.

One detail I haven't seen raised: the launcher sets `UseShellExecute = true`, and `ShellExecuteEx` already does PATH and PATHEXT resolution. On Windows 11 with only `npm.exe` present, launching the bare name `npm` resolves and exits 0. The comment above the transform says it's there "so that the command can actually be found" - that's what `UseShellExecute = false` requires. Under `true` it only turns a name Windows can resolve into one it can't.

Tracking on the nvm side at nvm-windows/nvm#1405.
