### ISSUE TITLE
Quarantine `Settings_MaxHeaderListSize_Server`

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#45811]
## Failing Test(s)

It looks like this failure was discussed before in https://github.com/dotnet/aspnetcore/issues/21518.

- Interop.FunctionalTests.HttpClientHttp2InteropTests.Settings_MaxHeaderListSize_Server(scheme: "https")

## Error Message

```text
System.Net.Http.HttpRequestException : The HTTP request headers length exceeded the server limit of 32768 bytes.
```

## Stacktrace

<details>

```text
System.Net.Http.HttpRequestException : The HTTP request headers length exceeded the server limit of 32768 bytes.
2022-12-30T22:39:38.0187841Z [xUnit.net 00:00:04.79]       Stack Trace:
2022-12-30T22:39:38.0204044Z [xUnit.net 00:00:04.79]            at System.Net.Http.Http2Connection.WriteHeaders(HttpRequestMessage request, ArrayBuffer& headerBuffer)
2022-12-30T22:39:38.0210804Z [xUnit.net 00:00:04.79]            at System.Net.Http.Http2Connection.SendHeadersAsync(HttpRequestMessage request, CancellationToken cancellationToken, Boolean mustFlush)
2022-12-30T22:39:38.0217571Z [xUnit.net 00:00:04.79]            at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2022-12-30T22:39:38.0224181Z [xUnit.net 00:00:04.79]            at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
2022-12-30T22:39:38.0230951Z [xUnit.net 00:00:04.79]            at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2022-12-30T22:39:38.0237987Z [xUnit.net 00:00:04.79]            at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
2022-12-30T22:39:38.0245056Z [xUnit.net 00:00:04.80]            at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber)
2022-12-30T22:39:38.0251962Z [xUnit.net 00:00:04.80]         /_/src/Servers/Kestrel/test/Interop.FunctionalTests/HttpClientHttp2InteropTests.cs(1372,0): at Interop.FunctionalTests.HttpClientHttp2InteropTests.Settings_MaxHeaderListSize_Server(String scheme)
```
</details>

## Logs

<details>

```text
2022-12-30T22:39:38.0325393Z [xUnit.net 00:00:04.80]         | [0.001s] TestLifetime Information: Starting test Settings_MaxHeaderListSize_Server-https at 2022-12-30T22:39:37
2022-12-30T22:39:38.0348412Z [xUnit.net 00:00:04.80]         | [0.003s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting starting
2022-12-30T22:39:38.0364177Z [xUnit.net 00:00:04.81]         | [0.017s] Microsoft.Hosting.Lifetime Information: Now listening on: https://127.0.0.1:44061
2022-12-30T22:39:38.0391940Z [xUnit.net 00:00:04.81]         | [0.017s] Microsoft.AspNetCore.Hosting.Diagnostics Debug: Loaded hosting startup assembly Interop.FunctionalTests
2022-12-30T22:39:38.0410884Z [xUnit.net 00:00:04.81]         | [0.017s] Microsoft.Hosting.Lifetime Information: Application started. Press Ctrl+C to shut down.
2022-12-30T22:39:38.0442111Z [xUnit.net 00:00:04.81]         | [0.017s] Microsoft.Hosting.Lifetime Information: Hosting environment: Production
2022-12-30T22:39:38.0465574Z [xUnit.net 00:00:04.82]         | [0.017s] Microsoft.Hosting.Lifetime Information: Content root path: /datadisks/disk1/work/B57A096F/w/BCB709E4/e/
2022-12-30T22:39:38.0482572Z [xUnit.net 00:00:04.82]         | [0.017s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting started
2022-12-30T22:39:38.0494952Z [xUnit.net 00:00:04.82]         | [0.018s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMNAMQT2A7ER" accepted.
2022-12-30T22:39:38.0511834Z [xUnit.net 00:00:04.82]         | [0.018s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMNAMQT2A7ER" started.
2022-12-30T22:39:38.0523817Z [xUnit.net 00:00:04.82]         | [0.024s] Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware Debug: Connection 0HMNAMQT2A7ER established using the following protocol: Tls13
2022-12-30T22:39:38.0538397Z [xUnit.net 00:00:04.82]         | [0.025s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMNAMQT2A7ER" sending SETTINGS frame for stream ID 0 with length 24 and flags NONE.
2022-12-30T22:39:38.0550456Z [xUnit.net 00:00:04.83]         | [0.025s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMNAMQT2A7ER" sending WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0.
2022-12-30T22:39:38.0584074Z [xUnit.net 00:00:04.83]         | [0.025s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMNAMQT2A7ER" received SETTINGS frame for stream ID 0 with length 12 and flags NONE.
2022-12-30T22:39:38.0592953Z [xUnit.net 00:00:04.83]         | [0.025s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMNAMQT2A7ER" sending SETTINGS frame for stream ID 0 with length 0 and flags ACK.
2022-12-30T22:39:38.0604996Z [xUnit.net 00:00:04.83]         | [0.025s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMNAMQT2A7ER" received WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0.
2022-12-30T22:39:38.0617232Z [xUnit.net 00:00:04.83]         | [0.025s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMNAMQT2A7ER" received SETTINGS frame for stream ID 0 with length 0 and flags ACK.
2022-12-30T22:39:38.0634246Z [xUnit.net 00:00:04.83]         | [0.027s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HMNAMQT2A7ER" received FIN.
2022-12-30T22:39:38.0649732Z [xUnit.net 00:00:04.83]         | [0.027s] Microsoft.AspNetCore.Server.Kestrel.Http2 Debug: Connection id "0HMNAMQT2A7ER" is closed. The last processed stream ID was 0.
2022-12-30T22:39:38.0666360Z [xUnit.net 00:00:04.83]         | [0.027s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HMNAMQT2A7ER" sending FIN because: "The client closed the connection."
2022-12-30T22:39:38.0683490Z [xUnit.net 00:00:04.83]         | [0.028s] Microsoft.AspNetCore.Server.Kestrel.Http2 Debug: The connection queue processing loop for 0HMNAMQT2A7ER completed.
2022-12-30T22:39:38.0700554Z [xUnit.net 00:00:04.83]         | [0.028s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMNAMQT2A7ER" stopped.
2022-12-30T22:39:38.0714316Z [xUnit.net 00:00:04.83]         | [0.043s] Interop.FunctionalTests.HttpClientHttp2InteropTests Error: Test threw an exception.
2022-12-30T22:39:38.0725715Z [xUnit.net 00:00:04.83]         | System.Net.Http.HttpRequestException: The HTTP request headers length exceeded the server limit of 32768 bytes.
2022-12-30T22:39:38.1486480Z [xUnit.net 00:00:04.83]         |    at System.Net.Http.Http2Connection.WriteHeaders(HttpRequestMessage request, ArrayBuffer& headerBuffer)
2022-12-30T22:39:38.1486620Z [xUnit.net 00:00:04.83]         |    at System.Net.Http.Http2Connection.SendHeadersAsync(HttpRequestMessage request, CancellationToken cancellationToken, Boolean mustFlush)
2022-12-30T22:39:38.1486649Z [xUnit.net 00:00:04.83]         |    at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2022-12-30T22:39:38.1486892Z [xUnit.net 00:00:04.83]         |    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
2022-12-30T22:39:38.1486920Z [xUnit.net 00:00:04.83]         |    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2022-12-30T22:39:38.1487081Z [xUnit.net 00:00:04.83]         |    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
2022-12-30T22:39:38.1487136Z [xUnit.net 00:00:04.83]         |    at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber)
2022-12-30T22:39:38.1487163Z [xUnit.net 00:00:04.83]         |    at Interop.FunctionalTests.HttpClientHttp2InteropTests.Settings_MaxHeaderListSize_Server(String scheme) in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/HttpClientHttp2InteropTests.cs:line 1372
2022-12-30T22:39:38.1487212Z [xUnit.net 00:00:04.83]         |    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 264
2022-12-30T22:39:38.1487289Z [xUnit.net 00:00:04.83]         | --- End of stack trace from previous location ---
2022-12-30T22:39:38.1487317Z [xUnit.net 00:00:04.83]         |    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
2022-12-30T22:39:38.1487382Z [xUnit.net 00:00:04.83]         |    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
2022-12-30T22:39:38.1487414Z [xUnit.net 00:00:04.83]         | [0.045s] TestLifetime Information: Finished test Settings_MaxHeaderListSize_Server-https in 0.0444627s
```
</details>

## Build

- https://dev.azure.com/dnceng-public/public/_build/results?buildId=121751

**Comment by Tratcher** [comment]
This was an intentional change to verify the limit on the client rather than the server. We need to update the test accordingly.
https://github.com/dotnet/runtime/pull/79997
