### ISSUE TITLE
Occasional view metadata exception

### ISSUE THREAD

**Issue by kanpal** [dotnet/aspnetcore#45900]
We are using AspNetCore.App v6.0.9 (part of the .NET6) upgrade.
Occasionally (only in a production) environment we get this metadata error while rendering Razor pages. We have verified it's not an issue all the time. It happens very rarely and once it happens, we can reproduce it consistently. An app pool recycle would fix the problem.

Here's the call stack. We can assert the attribute metadata is valid for the Hidden fields being called as we cannot reproduce the issue all the time. It appears to be more of a concurrent dictionary and concurrent request executing issue where the JIT optimized code returns a null value from the ConcurrentDictionary<>. Please advise.

```
_System.ArgumentNullException: Value cannot be null. (Parameter 'metadata')
at Microsoft.AspNetCore.Mvc.ViewFeatures.ModelExplorer.GetExplorerForExpression(ModelMetadata metadata, Func`2 modelAccessor)

at Microsoft.AspNetCore.Mvc.ViewFeatures.DefaultHtmlGenerator.AddValidationAttributes(ViewContext viewContext, TagBuilder tagBuilder, ModelExplorer modelExplorer, String expression)

at Microsoft.AspNetCore.Mvc.ViewFeatures.DefaultHtmlGenerator.GenerateInput(ViewContext viewContext, InputType inputType, ModelExplorer modelExplorer, String expression, Object value, Boolean useViewData, Boolean isChecked, Boolean setId, Boolean isExplicitValue, String format, IDictionary`2 htmlAttributes)

at Microsoft.AspNetCore.Mvc.ViewFeatures.DefaultHtmlGenerator.GenerateHidden(ViewContext viewContext, ModelExplorer modelExplorer, String expression, Object value, Boolean useViewData, Object htmlAttributes)

at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.GenerateHidden(ModelExplorer modelExplorer, String expression, Object value, Boolean useViewData, Object htmlAttributes)

at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.Hidden(String expression, Object value, Object htmlAttributes)

at AspNetCoreGeneratedDocument.Areas_Policy_Views_MpciAPH_EditorTemplates_ProductionHistoryTypeG.ExecuteAsync()_
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @kanpal.
Without a minimal repro it will be hard to know for certain what is causing this. We will, however, try to look up the call stack and see if that will lead to something. That said, if you can provide a reliable repro, that can help.

**Comment by mkArtakMSFT** [comment]
@kanpal I did look into the code to try and see how this could be the case, but I wasn't able to identify a cause for the reported behavior. At this point, we'll need a reliable repro project to debug this.

**Comment by kanpal** [comment]
Thanks for taking a look at the issue @mkArtakMSFT . After further investigation, we found out that there's some external code that is modifying the internal metadata collection (it sorts the fields in a certain order for legacy asp.net code compatibility) like this:

```
private void StoreInInternalCache(IEnumerable<ModelMetadata> sortedProperties, Type modelType, ModelBinderProviderContext context)
{
	lock (locker)
	{
		var cacheEntry = context.MetadataProvider.InvokeMethodByReflection<object>("GetCacheEntry", new object[] { modelType });
		if (cacheEntry is not null)
		{
			var details = cacheEntry.GetItemByReflection<DefaultMetadataDetails>("Details");
			if (details is not null)
			{
				details.Properties = sortedProperties.ToArray();
			}
		}
		`context.Metadata.SetFieldByReflection("_properties",` new ModelPropertyCollection(sortedProperties));
	}
}

We suspect this to be the culprit. Thanks again for double checking the issue. Any thoughts or suggestions on how we can manipulate the internal metadata collection would be appreciated.
```
