### ISSUE TITLE
InputFile OnChange doesn't trigger when I click on a label

### ISSUE THREAD

**Issue by Sedpower** [dotnet/aspnetcore#45901]
![image](https://user-images.githubusercontent.com/83537027/172816743-fca9b3b4-ca6e-4051-8090-547f7deb30be.png)

Sometimes, when I go on the page with and I click on the label, I choose my file but the OnChange function doesn't trigger. If I refresh the page and do it again, then, it will work. Do someone know why.

If I remove the hidden tag and click on the input file element, its working. The problem comes from the fact that I click on the label instead of input but I need to change the style of the button so I need to hide native input.

I get this error in the console
```
Uncaught (in promise) Error: System.ArgumentException: There is no tracked object with id '82'. Perhaps the DotNetObjectReference instance was already disposed. (Parameter 'dotNetObjectId')
   at Microsoft.JSInterop.JSRuntime.GetObjectReference(Int64 dotNetObjectId)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet(JSRuntime jsRuntime, DotNetInvocationInfo invocationInfo, String argsJson)
    at kt.endInvokeDotNetFromJS (blazor.server.js:1:3700)
    at blazor.server.js:1:72001
    at Array.forEach (<anonymous>)
    at kt._invokeClientMethod (blazor.server.js:1:71987)
    at kt._processIncomingData (blazor.server.js:1:70029)
    at connection.onreceive (blazor.server.js:1:64432)
    at o.onmessage (blazor.server.js:1:48766)
```

Apologize for my english, I'm french and were bad in english xD

**Comment by surayya-MS** [comment]
Thanks for contacting us. In order for us to investigate this issue, would you please provide a minimal repro project that demonstrates the problem, hosted in a public GitHub repository?
