### ISSUE TITLE
[Blazor] JS Interop in Blazor MAUI

### ISSUE THREAD

**Issue by daniel-p-tech** [dotnet/aspnetcore#45912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,

I am migrating Blazor WASM app to Blazor MAUI and ran into an JS interop issue when calling C# method from JS:

_Uncaught Error: The current dispatcher does not support synchronous calls from JS to .NET. Use invokeMethodAsync instead.
    at v (blazor.webview.js:1:1674)
    at C.invokeMethod (blazor.webview.js:1:3812)
    at HTMLDivElement.component.onTransitionend (BlzMainLayoutSideBar.razor.js:21:52)_

```javascript
     // handle sidebar transition end event
        component.onTransitionend = function () {
            const isCollapsed = componentDotNetRef.invokeMethod("OnTransitionEnd");
            if (isCollapsed === true) {
                lib.enableBodyScrolling();
            }
        }
```

```csharp
     [JSInvokable]
        public bool OnTransitionEnd()
        {
		// ...
		return isFinished;
	}
```

Changing the JS call to C# to async seemed to fix the problem:
```javascript
       component.onTransitionend = async function () {
            const isCollapsed = await componentDotNetRef.invokeMethodAsync("OnTransitionEnd");
            if (isCollapsed === true) {
                lib.enableBodyScrolling();
            }
        }
```

Is this all that needs to be done? Or should I also change the C# method to return ``Task`` even though there are no asynchronous calls inside ``OnTransitionEnd``.

```csharp
   [JSInvokable]
        public Task<bool> OnTransitionEnd()
        {
		// ...
		return Task.FromResult(isFinished);
	}
```

I will need to modify quite a bit of existing code to make all my components compatible with Blazor MAUI so I'd like to ensure that I'm making the right change.

Thank you!

### .NET Version

.NET 7

**Comment by javiercn** [comment]
@daniel-p-tech thanks for contacting us.

Yes. Synchronous interop is only supported on WebAssembly, we always recommend using async signatures in your interop APIs by default and special casing for synchronous interop on webassembly only and if needed.

Consequently, you should return a Task from your async APIs.
