### ISSUE TITLE
Blazor page is rendered before external JavaScript files are loaded

### ISSUE THREAD

**Issue by plastovicka** [dotnet/aspnetcore#45970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the docs is written that external JavaScript files should be placed **after** the Blazor script reference. For example: 
```
 <script src="_framework/blazor.{webassembly|server}.js"></script>
 <script src="./_content/{PACKAGE ID}/{SCRIPT PATH AND FILENAME (.js)}"></script>
```
This works in Firefox, but it can throw an exception in Chrome or Edge because the page is rendered before scripts are loaded.

cc: @guardrex https://github.com/dotnet/AspNetCore.Docs/issues/28044

### Expected Behavior

Blazor should wait and not call OnAfterRenderAsync function until all external scripts are loaded.

### Steps To Reproduce

Create a new project - Blazor Server App.

**Pages/_Host.cshtml**
```
     ...
    <script src="_framework/blazor.server.js"></script>
    <script src="test.js?@DateTime.Now.ToString("HHmmss")"></script>
</body>
</html>
```

**wwwroot/test.js**
```
/* paste inside this comment at least 10 MB of any text so that this file is really big  */
function test() { }
```

**Pages/Index.razor**
```
@page "/"
@inject IJSRuntime JS
@code {
	protected override async Task OnAfterRenderAsync(bool firstRender)
	{
		await JS.InvokeVoidAsync("test");
	}
}
```

Run the app in Chrome, then set throttling to Slow 3G on the network tab and refresh the page. 

### Exceptions (if any)

```
Error: Microsoft.JSInterop.JSException: Could not find 'test' ('test' was undefined).
Error: Could not find 'test' ('test' was undefined).
    at https://localhost:44368/_framework/blazor.server.js:1:497
    at Array.forEach (<anonymous>)
    at s.findFunction (https://localhost:44368/_framework/blazor.server.js:1:465)
    at E (https://localhost:44368/_framework/blazor.server.js:1:2611)
    at https://localhost:44368/_framework/blazor.server.js:1:3499
    at new Promise (<anonymous>)
    at Ft.beginInvokeJSFromDotNet (https://localhost:44368/_framework/blazor.server.js:1:3480)
    at Ft._invokeClientMethod (https://localhost:44368/_framework/blazor.server.js:1:75072)
    at Ft._processIncomingData (https://localhost:44368/_framework/blazor.server.js:1:72696)
    at Ft.connection.onreceive (https://localhost:44368/_framework/blazor.server.js:1:67009)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at BlazorApp2.Pages.Index.OnAfterRenderAsync(Boolean firstRender) in C:\Users\PetrLastovicka\source\repos\BlazorApp2\Pages\Index.razor:line 6
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningCompone
```ntState)

### .NET Version

7.0.101

### Anything else?

_No response_

**Comment by javiercn** [comment]
@plastovicka thanks for contacting us.

The best way to approach this is to use a JS initializer to load your script at the appropriate time. @guardrex do you think you can update the docs?

**Comment by guardrex** [comment]
Javier, Steve said on the docs issue ...

> The Blazor WebAssembly/Server startup process is asynchronous, so scripts added after that script tag are loaded and block the JS engine until they've finished loading. So under normal circumstances, the bug being reported here cannot occur ...

Cross-ref: https://github.com/dotnet/AspNetCore.Docs/issues/28044#issuecomment-1375627614

It's leading me to write unusual guidance on this ...

> Scripts added after the Blazor \`\<script>\` tag block the Blazor JavaScript engine until they've finished loading. To ensure scripts load before Blazor starts, load the scripts in the \`beforeStart\` event of a \[JavaScript initializer](#javascript-initializers).

... so it sounds like these sentences are contradictory ...

* Scripts loaded after the Blazor script will block Blazor starting.
* You can block Blazor starting by using a JS intializer ... i.e., it might not be blocked after all.

**Comment by guardrex** [comment]
... and btw for `beforeStart`, do you want me to pitch ye olde `createElement`-`appendChild` to load the script?
