### ISSUE TITLE
Process terminated with error: Exception thrown from SocketAsyncEngine event loop

### ISSUE THREAD

**Issue by VladStatnyk** [dotnet/aspnetcore#45988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We are working on finding the root cause for an container restart. We have a service running as Docker container inside Kubernetes. Once in the while we see container restarts due to attached exception. We do not see anything suspicions inside application logs at that point of time. CPU & Memory consumption is lower than 50% at point of failure.

### Steps To Reproduce

I am not able to reproduce the issue.

### Exceptions (if any)

Process terminated. Exception thrown from SocketAsyncEngine event loop: System.Net.InternalException: Exception of type 'System.Net.InternalException' was thrown. EAGAIN
at System.Net.Sockets.SocketAsyncEngine.EventLoop()
at System.Environment.FailFast(System.String, System.Exception)
at System.Net.Sockets.SocketAsyncEngine.EventLoop()
at System.Net.Sockets.SocketAsyncEngine+<>c.<.ctor>b__14_0(System.Object)
at System.Threading.Thread.StartCallback()
System.Net.InternalException: Exception of type 'System.Net.InternalException' was thrown. EAGAIN
    at System.Net.Sockets.SocketAsyncEngine.EventLoop()/app/launch.sh: line 8:     7 Aborted (core dumped) dotnet [MyServiceName].dll

### .NET Version

6.0.8

### Anything else?

Linux version: Ubuntu 1804
Linkerd version: 2.11.5

**Comment by VladStatnyk** [comment]
The issue was with DataDog tracer version (2.17.0) that we are using.
