### ISSUE TITLE
SignalR Messagepack serialization issue

### ISSUE THREAD

**Issue by meijeran** [dotnet/aspnetcore#45991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,

I am running into an issue sending messages to the signalR hub using MessagePack serialisation.

The message I am sending has the following typescript structure:

```
export class StartClockCommand {
  ClockId: string
  StartPrice: string
  Velocity: string
}
```

```
 const clockCommand: StartClockCommand = {
      ClockId: clock.ClockId.toString(),
      StartPrice: '1',
      Velocity: '2',
    }

```

On the serverside the structure is as follows:

`public record StartClockCommand(string ClockId, string StartPrice, string Velocity);`

When sending the message to the server the Method get's invoked and runs succesfully, however after completion the following exception occurs on the server:

> [2023-01-10T16:32:41.8687401+01:00 DBG] Parameters to hub method 'StartClockCommand' are incorrect. (Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher)
2023-01-10T15:32:41.870492251Z System.IO.InvalidDataException: Error binding arguments. Make sure that the types of the provided values match the types of the hub method being invoked.
2023-01-10T15:32:41.870603460Z  ---> System.IO.InvalidDataException: Deserializing object of the `StartClockCommand` type for 'argument' failed.
2023-01-10T15:32:41.870617210Z  ---> MessagePack.MessagePackSerializationException: Failed to deserialize Rfh.Auction.Clock.Commands.StartClockCommand value.
2023-01-10T15:32:41.870621460Z  ---> MessagePack.MessagePackSerializationException: Unexpected msgpack code 217 (str 8) encountered.
2023-01-10T15:32:41.870624835Z    at MessagePack.MessagePackReader.ThrowInvalidCode(Byte code)
2023-01-10T15:32:41.870626918Z    at MessagePack.MessagePackReader.TryReadMapHeader(Int32& count)
2023-01-10T15:32:41.870629001Z    at MessagePack.MessagePackReader.ReadMapHeader()
2023-01-10T15:32:41.870630918Z    at MessagePack.Formatters.Rfh_Auction_Clock_Commands_StartClockCommandFormatter1.Deserialize(MessagePackReader& reader, MessagePackSerializerOptions options)
2023-01-10T15:32:41.870632960Z    at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader, MessagePackSerializerOptions options)
2023-01-10T15:32:41.870634835Z    --- End of inner exception stack trace ---
2023-01-10T15:32:41.870636626Z    at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader, MessagePackSerializerOptions options)
2023-01-10T15:32:41.870639168Z    at lambda_method218(Closure , MessagePackReader& , MessagePackSerializerOptions )
2023-01-10T15:32:41.870641085Z    at MessagePack.MessagePackSerializer.Deserialize(Type type, MessagePackReader& reader, MessagePackSerializerOptions options)
2023-01-10T15:32:41.870643168Z    at Microsoft.AspNetCore.SignalR.Protocol.DefaultMessagePackHubProtocolWorker.DeserializeObject(MessagePackReader& reader, Type type, String field)
2023-01-10T15:32:41.870645543Z    --- End of inner exception stack trace ---
2023-01-10T15:32:41.870654751Z    at Microsoft.AspNetCore.SignalR.Protocol.DefaultMessagePackHubProtocolWorker.DeserializeObject(MessagePackReader& reader, Type type, String field)
2023-01-10T15:32:41.870656960Z    at Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocolWorker.BindArguments(MessagePackReader& reader, IReadOnlyList`1 parameterTypes)
2023-01-10T15:32:41.870659501Z    --- End of inner exception stack trace ---
2023-01-10T15:32:41.870665376Z    at Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocolWorker.BindArguments(MessagePackReader& reader, IReadOnlyList`1 parameterTypes)
2023-01-10T15:32:41.870857876Z    at Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocolWorker.CreateInvocationMessage(MessagePackReader& reader, IInvocationBinder binder, Int32 itemCount)
2023-01-10T15:32:58.126534301Z 

This results also in an error on the client side.
As far as I can see the types are correct on client-side and server-side.  So what is causing this issue?

### Expected Behavior

No exception should be thrown

### Exceptions (if any)

[2023-01-10T16:32:41.8687401+01:00 DBG] Parameters to hub method 'StartClockCommand' are incorrect. (Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher)
2023-01-10T15:32:41.870492251Z System.IO.InvalidDataException: Error binding arguments. Make sure that the types of the provided values match the types of the hub method being invoked.
2023-01-10T15:32:41.870603460Z  ---> System.IO.InvalidDataException: Deserializing object of the `StartClockCommand` type for 'argument' failed.
2023-01-10T15:32:41.870617210Z  ---> MessagePack.MessagePackSerializationException: Failed to deserialize Rfh.Auction.Clock.Commands.StartClockCommand value.
2023-01-10T15:32:41.870621460Z  ---> MessagePack.MessagePackSerializationException: Unexpected msgpack code 217 (str 8) encountered.
2023-01-10T15:32:41.870624835Z    at MessagePack.MessagePackReader.ThrowInvalidCode(Byte code)
2023-01-10T15:32:41.870626918Z    at MessagePack.MessagePackReader.TryReadMapHeader(Int32& count)
2023-01-10T15:32:41.870629001Z    at MessagePack.MessagePackReader.ReadMapHeader()
2023-01-10T15:32:41.870630918Z    at MessagePack.Formatters.Rfh_Auction_Clock_Commands_StartClockCommandFormatter1.Deserialize(MessagePackReader& reader, MessagePackSerializerOptions options)
2023-01-10T15:32:41.870632960Z    at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader, MessagePackSerializerOptions options)
2023-01-10T15:32:41.870634835Z    --- End of inner exception stack trace ---
2023-01-10T15:32:41.870636626Z    at MessagePack.MessagePackSerializer.Deserialize[T](MessagePackReader& reader, MessagePackSerializerOptions options)
2023-01-10T15:32:41.870639168Z    at lambda_method218(Closure , MessagePackReader& , MessagePackSerializerOptions )
2023-01-10T15:32:41.870641085Z    at MessagePack.MessagePackSerializer.Deserialize(Type type, MessagePackReader& reader, MessagePackSerializerOptions options)
2023-01-10T15:32:41.870643168Z    at Microsoft.AspNetCore.SignalR.Protocol.DefaultMessagePackHubProtocolWorker.DeserializeObject(MessagePackReader& reader, Type type, String field)
2023-01-10T15:32:41.870645543Z    --- End of inner exception stack trace ---
2023-01-10T15:32:41.870654751Z    at Microsoft.AspNetCore.SignalR.Protocol.DefaultMessagePackHubProtocolWorker.DeserializeObject(MessagePackReader& reader, Type type, String field)
2023-01-10T15:32:41.870656960Z    at Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocolWorker.BindArguments(MessagePackReader& reader, IReadOnlyList`1 parameterTypes)
2023-01-10T15:32:41.870659501Z    --- End of inner exception stack trace ---
2023-01-10T15:32:41.870665376Z    at Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocolWorker.BindArguments(MessagePackReader& reader, IReadOnlyList`1 parameterTypes)
2023-01-10T15:32:41.870857876Z    at Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocolWorker.CreateInvocationMessage(MessagePackReader& reader, IInvocationBinder binder, Int32 itemCount)
2023-01-10T15:32:58.126534301Z 

### .NET Version

7.0.100

**Comment by meijeran** [comment]
Alright, so something strange was happening on the frontend side which made send the request twice, once as object which works as expected. And the other time it was sent as json string, which caused the error.
So everything works as expected, at least your comment pointed me in the right direction. 

Thanks for your help and sorry for the inconvenience
