### ISSUE TITLE
Unix socket not deleted at startup in Blazor.DevServer

### ISSUE THREAD

**Issue by Socolin** [dotnet/aspnetcore#46001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello

I want to use nginx as frontend to be able to use a TLS certificate with a specific hostname on linux, I would like to use a unix socket instead of assigning a port, to avoid possible conflict, and since the nginx configuration is static I cannot assign port dynamically.

### Expected Behavior

The unix socket should be deleted if it exists at startup

### Steps To Reproduce

ASPNETCORE_URLS=http://unix:/var/run/app/app.sock dotnet run

### Exceptions (if any)

```
Unhandled exception. System.IO.IOException: Failed to bind to address http://unix:/var/run/app/app.sock: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
 ---> System.Net.Sockets.SocketException (98): Address already in use
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass30_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Microsoft.AspNetCore.Components.WebAssembly.DevServer.Program.Main(String[] args)
```

### .NET Version

7.0.100

**Comment by javiercn** [comment]
@Socolin thanks for contacting us.

@halter73 @Tratcher can you help here? I do not think we are doing anything wrong in our setup, but I might be wrong.

**Comment by Socolin** [comment]
I forgot to mention I was using `dotnet watch run` and problem occurs on reload

**Comment by Tratcher** [comment]
> I want to use nginx as frontend to be able to use a TLS certificate with a specific hostname on linux,

Kestrel can do that without nginx... Is there any other reason you need nginx?

**Comment by Socolin** [comment]
Kestrel cannot listen on port 80 without root permission

**Comment by Tratcher** [comment]
Neither can nginx?

**Comment by Socolin** [comment]
Nginx run as root in background I don't need to start it from my IDE thus my IDE do not run as root (which would be very bad on a security level).

Nginx communicate with a unix socket, a file with the right permission to allow only my user to create it and only nginx to read connect to it.
This is common on linux, for example php-fpm works like this too.

Also even if I could start kestrel on port 80/443 as non root by changing the config with sysctl (I think `net.ipv4.ip_unprivileged_port_start` would allow me to do that, but I don't think this would be a good idea anyway) I'm having multiple services running and nginx is also doing the dispatch depending on the hostname to the right host.

Since I´m working on different projects, having numeric port is not an options, I don't want to start managing excel with what port use what project and what avoid conflict with other services. With a unix socket, all this disapear

If this can help to understand how my setup is working I did a little graph, if you need more information let me know. If you have a better idea I'll be happy to hear it too. But here I'm using nginx exactly as people are using IIS on windows.

![image](https://user-images.githubusercontent.com/539620/211905898-278f9c3b-ee25-4548-8013-e93d33728f36.png)

**Comment by adityamandaleeka** [comment]
Triage: we should investigate and try to reproduce this issue. Perhaps this may happen if the socket isn't `Dispose`d (i.e. gracefully closed).

**Comment by javiercn** [comment]
@adityamandaleeka I am removing the Blazor tag since I do not think this is very related to Blazor, but feel free to add it back if you need our input or we can assist in any way.

**Comment by mitchdenny** [comment]
@Socolin I had a look into what was going on here and was able to reproduce what you were experiencing. By default the version of .NET you are using will delete the unix socket file when the process stops (this makes sense since it created it). But if the process does not stop cleanly and is torn down before the socket can be cleaned up - then when it is restarted it fails because it already exists. The error you are receiving is by design.

In your issue you suggested the expected behavior was that we should delete the socket file before we create a new one. However we need to consider the fact that this socket may not be ours to delete. Imagine for a second if by default we killed other processes that where using ports that we wanted to host Kestrel on - it actually makes more sense to throw an error like we do.

That said - if you want to delete the socket file because you are 100% confident that nothing else should be using it then you can add code to your Program.cs to delete the file.

**Comment by mitchdenny** [comment]
See related conversations: https://github.com/dotnet/aspnetcore/issues/14134

**Comment by mitchdenny** [comment]
Minimal repro if anyone is interested - configure Nginx with this configuration:

```
events {
    worker_connections 768;
}

http {
    server {
        listen 80 default;

        location / {
            proxy_pass http://unix:/tmp/unix-sockets-repro.sock;
        }
    }
}
```

Run the following .NET code:

```csharp
var builder = WebApplication.CreateBuilder(args);
builder.WebHost.ConfigureKestrel((context, serverOptions) => {
    serverOptions.ListenUnixSocket("/tmp/unix-sockets-repro.sock");
});
var app = builder.Build();

app.MapGet("/", () => "Hello World!");

app.Run();
```

Do a ```kill -9``` on the process, then launch it again and you'll get the following error:

```
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Overriding address(es) 'http://localhost:5153'. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.
Unhandled exception. System.IO.IOException: Failed to bind to address http://unix:/tmp/unix-sockets-repro.sock: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
 ---> System.Net.Sockets.SocketException (98): Address already in use
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass30_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args) in /home/mitchdenny/unix-sockets-repro/Program.cs:line 9
```

Add the following line to the top of your ```Program.cs``` and it'll start back up cleanly:

```
File.Delete("/tmp/repro.sock");
```

**Comment by Socolin** [comment]
Then before deleting the socket we could check if it's still in use. If it's not used, delete the file, else throw normal error.

```cs
if (IsUnixSocketInUse(socketPath))
   File.Delete(socketPath)
```

Here is an example

```cs
using System.Diagnostics;
using System.Net.Sockets;

const string testSocketPath = "test.sock";

bool IsUnixSocketInUse(string socketPath)
{
	if (!File.Exists(socketPath))
		return false;

	var endPoint = new UnixDomainSocketEndPoint(socketPath);
	using var socket = new Socket(AddressFamily.Unix, SocketType.Stream, ProtocolType.Unspecified);
	try
	{
		socket.Connect(endPoint);
		socket.Disconnect(false);
		return true;
	}
	catch (SocketException ex) when (ex.SocketErrorCode == SocketError.ConnectionRefused)
	{
		return false;
	}
	catch
	{
		// We are not expecting an exception here, so maybe we can ignore all other error ? or let it throw ?
		return true;
	}
}


Socket StartListenUnixSocket(string socketPath)
{
	var endPoint = new UnixDomainSocketEndPoint(socketPath);
	var socket = new Socket(AddressFamily.Unix, SocketType.Stream, ProtocolType.Unspecified);
	socket.Bind(endPoint);
	socket.Listen();
	return socket;
}

Console.WriteLine("InUse: " + IsUnixSocketInUse(testSocketPath));


using var listenSocket = StartListenUnixSocket(testSocketPath);
Console.WriteLine("InUse: " + IsUnixSocketInUse(testSocketPath));
Process.GetCurrentProcess().Kill();
```

**Comment by mitchdenny** [comment]
I think that is code that you could opt to add into your own project if situationally you think it's the right thing to do. I am not sure we would add that to the framework itself for the same reasons we wouldn't look up the process that is holding a port open and kill it (although situationally you could do that too).

**Comment by Socolin** [comment]
> I think that is code that you could opt to add into your own project if situationally you think it's the right thing to do. I am not sure we would add that to the framework itself for the same reasons we wouldn't look up the process that is holding a port open and kill it (although situationally you could do that too).

My proposition is not to kill the process holding the socket unix.

My suggestion is to delete the socket if the socket is not used anymore. (The original process was kill for example)

All the other services I know that are using unix socket are handling this scenario. If the files is still here but not in use, it should be deleted and the service should start.

**Comment by Socolin** [comment]
Maybe the `Process.GetCurrentProcess().Kill();` was confusing, but in my example it was here to provoke the scenario where the files is present but the process is dead. (the command line is to kill itself)

**Comment by Socolin** [comment]
> At this point I think the behavior is as intended. We close the socket if we shutdown cleanly - but if we crash it remains. We leave it up to developers to be defensive should the socket file exist and clean it up.

What mean "defensive" ? What value does it add to not delete the socket, when it's not used.

We can configure if we use a unix socket through `--urls` or env variable, but with this bug we need to add additional code when we want to use this feature. What's the point ? If the server run into a out of memory (killed by the kernel on linux for example), the auto restart will not work for example.

I'm not sure to understand what the reason of not deleting it when it's not used ? Except requiring additional code on every project where someone want to use a unix socket.

**Comment by adityamandaleeka** [comment]
@Socolin Sorry, looks like the bot auto-closed the issue after your last comment.

Here's the explanation behind our reasoning (largely the same as what @mitchdenny has already said)...

The socket is cleaned up under normal/graceful exit conditions, and is only left behind when something unexpected happens, which causes the process to get torn down before it has a chance to clean up. As @mitchdenny explained, there is risk and cost involved in trying to clean things up on every start; there may be another process using the socket, for instance. Making a unilateral platform-level decision about this is inherently risky for us to do.

If there is something causing your process to be killed unexpectedly, I would start with trying to resolve that issue. Beyond that, if you are confident that it is safe to delete the socket, you can do it in your own code as mentioned above.

Hope that's useful.

**Comment by Socolin** [comment]
> The socket is cleaned up under normal/graceful exit conditions, and is only left behind when something unexpected happens, which causes the process to get torn down before it has a chance to clean up. As @mitchdenny explained, there is risk and cost involved in trying to clean things up on every start; there may be another process using the socket, for instance. Making a unilateral platform-level decision about this is inherently risky for us to do.

I suggest to check if the socket is in use and delete only if it's not deleted. I understand the socket should not be deleted because another app might be using it. But when the socket is non in used anymore (connect() return an error) it seems safe to delete it.

If you can see a scenario in which the socket should not be deleted when `connect()` is returning an error, I would be interested in knowing it, for me it's safe (but I can be wrong)

**Comment by Socolin** [comment]
The bot closed this again, 

@adityamandaleeka I'm sincerly curious about a scenario where deleteing a unix socket when no server is listening on it could be problematic.
