### ISSUE TITLE
Unobserved task exception in SignalR C# client when streaming

### ISSUE THREAD

**Issue by MikeOnTea** [dotnet/aspnetcore#46169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When calling a streaming method on a server that throws an exception, the resulting HubException is handled on the client, but an additional unobserved exception remains on a task and is later processed by the UnobservedTaskException-Handler if one is registered.

I've looked briefly at the SignalR-code, can the issue be that in https://github.com/dotnet/aspnetcore/blob/51abb6ac8005a7715ee5c8b7134938c3cec87acb/src/SignalR/clients/csharp/Client.Core/src/HubConnectionExtensions.StreamAsChannelAsync.cs#L291-L307 the completion of the inputChannel is awaited in line 307, but WaitToReadAsync could already throw the exception in line 291, thus that await of the completion is not reached in such a case?

### Expected Behavior

No unobserved task exceptions should occur.

### Steps To Reproduce

Small repro here: https://github.com/MikeOnTea/SignalrUnobservedExceptionTest

Relevant client code is in Client/MainWindow.xaml.cs.

Steps to repro:
- Run the server
- Run the client
- Click the Test-Button in the Client that calls the streaming server method.
- A message box appears, showing the exception
- A second message box appears, showing an unobserved task exception got collected by the GC.

### .NET Version

7.0.101

### Anything else?

Tested with SignalR version 6.0.13 and briefly with 7.0.2.
Visual Studio version 2022 running on Windows 10.

**Comment by MikeOnTea** [comment]
The unobserved exception's stacktrace in the sample looks like this:
>    at System.Threading.Channels.AsyncOperation`1.GetResult(Int16 token)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<CastIAsyncEnumerable>d__61`1.MoveNext()
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<CastIAsyncEnumerable>d__61`1.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Client.MainWindow.<FetchData>d__3.MoveNext() in C:\Users\MichaelP\source\repos\SignalRTest\Client\MainWindow.xaml.cs:line 44

In our productive code it looks like this:
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Channels.AsyncOperation`1.GetResult(Int16 token)
   at Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.<RunChannel>d__67`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SignalRClient.SignalRConnection.<WaitToReadAsync>d__21`1.MoveNext() in C:\Development\ktdb\ktdb\Source\KTpp\Communication\SignalRClient\SignalRConnection.cs:line 227

The last line is our custom code.

Additionally, i tried using dotMemory to get a creation stacktrace of the task that has the unobserved exception, this looks like this:
![image](https://user-images.githubusercontent.com/11480934/213519165-beb1f3ef-814b-4ed6-ad42-a451a1c344f0.png)

**Comment by BrennanConroy** [comment]
In production you're using `StreamAsChannelAsync`?
The sample uses `StreamAsync`.
So both code paths likely have a similar issue.

I agree with your assessment, looks like Channels can throw from `WaitToReadAsync` if completed with an error, but then they also set a `TaskCompletionSource` via `Channel.Completion` which will cause the `UnobservedTaskException` when it gets GCed since we don't observe it in the error case. That's a bit of an annoying API usage 😄

**Comment by MikeOnTea** [comment]
Yes, indeed, we're using StreamAsChannelAsync in production, i should've prepared the sample more carefully.

Yep, i agree, if that really is the issue, i wonder if that shouldn't be fixed in the Channels API instead.
