### ISSUE TITLE
Blazor WASM: Assertion error and uncaught promise in AuthorizationService.ts

### ISSUE THREAD

**Issue by Herdo** [dotnet/aspnetcore#46257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I've been migratin a Blazor WASM application from .NET 5 to .NET 7 the past few weeks.
I'm facing an issue with the identity provider integration. When receiving the login callback from the identity provider, the app is stuck at processing the result.

The developer console outputs two error messages which aren't helpful.

I drilled down into the sources and couldn't find any obvious reason. 
Only thing I can say is that it's caused by [`AuthenticationService.completeSignIn`](https://github.com/dotnet/aspnetcore/blob/c860576840f0ab0f57941ec100b0fb5a21724f92/src/Components/WebAssembly/WebAssembly.Authentication/src/Interop/AuthenticationService.ts#L258).

```js
async completeSignIn(url: string) {
    this.trace('completeSignIn', url);
    const requiresLogin = await this.loginRequired(url);
    const stateExists = await this.stateExists(url);
    try {
        const user = await this._userManager.signinCallback(url);
        if (window.self !== window.top) {
            return this.operationCompleted();
        } else {
            this.trace('completeSignIn-result', user);
            return this.success(user && user.state);
        }
    } catch (error) {
        if (requiresLogin || window.self !== window.top || !stateExists) {
            return this.operationCompleted();
        }

        return this.error('There was an error signing in.');
    }
}
```

If there's any additional info I can provide, or to extend the error message with more details, please let me know.

### Expected Behavior

`AuthenticationService.ts`, or subsequent classes, should throw error messages that can be resolved by the developer.

### Steps To Reproduce

I failed to reproduce the issue with a new .NET 7 project.
The reason for this issue could be a compelx migration issue from .NET 5 to .NET 7.

### Exceptions (if any)

- Error: [MONO] * Assertion: should not be reached at /__w/1/s/src/mono/mono/metadata/custom-attrs.c:2696
- Uncaught (in promise) ExitStatus {name: 'ExitStatus', message: 'Program terminated with exit(1)', status: 1}message: "Program terminated with exit(1)"

```
Error with Feature-Policy header: Unrecognized feature: 'ambient-light-sensor'.
Error with Feature-Policy header: Unrecognized feature: 'speaker'.
Error with Feature-Policy header: Unrecognized feature: 'vr'.
DevTools failed to load source map: Could not load content for chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
blazor.webassembly.js:1 Debugging hotkey: Shift+Alt+D (when application has focus)
blazor.webassembly.js:1 blazor Loaded 17.95 MB resourcesThis application was built with linking (tree shaking) disabled. Published applications will be significantly smaller.
dotnet.7.0.2.t82std0vpt.js:3 mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
dotnet.7.0.2.t82std0vpt.js:5 [Violation] 'setTimeout' handler took 110ms

dotnet.7.0.2.t82std0vpt.js:5 Error: [MONO] * Assertion: should not be reached at /__w/1/s/src/mono/mono/metadata/custom-attrs.c:2696

    at xe (dotnet.7.0.2.t82std0vpt.js:5:509)
    at Object.je (dotnet.7.0.2.t82std0vpt.js:5:792)
    at _mono_wasm_trace_logger (dotnet.7.0.2.t82std0vpt.js:14:104923)
    at 00992bd6:0x9a48
    at 00992bd6:0xa5a26
    at 00992bd6:0x1bfe13
    at 00992bd6:0x1bfea2
    at 00992bd6:0x1bff0b
    at 00992bd6:0x9bc08
    at 00992bd6:0x3f9b9
je @ dotnet.7.0.2.t82std0vpt.js:5
_mono_wasm_trace_logger @ dotnet.7.0.2.t82std0vpt.js:14
$func105 @ 00992bd6:0x9a48
$func2699 @ 00992bd6:0xa5a26
$func8602 @ 00992bd6:0x1bfe13
$func8605 @ 00992bd6:0x1bfea2
$func8608 @ 00992bd6:0x1bff0b
$func2521 @ 00992bd6:0x9bc08
$func740 @ 00992bd6:0x3f9b9
$func650 @ 00992bd6:0x395e4
$func1854 @ 00992bd6:0x7e7e5
$func1853 @ 00992bd6:0x7e517
$func1842 @ 00992bd6:0x7de67
$func701 @ 00992bd6:0x3b81e
$func728 @ 00992bd6:0x3caba
$func732 @ 00992bd6:0x3e2f4
$func729 @ 00992bd6:0x3ce5f
$func1660 @ 00992bd6:0x757f5
$func1659 @ 00992bd6:0x753d3
$func414 @ 00992bd6:0x28b16
$func381 @ 00992bd6:0x2217b
$func439 @ 00992bd6:0x2a4e3
$func275 @ 00992bd6:0x1c45c
$func221 @ 00992bd6:0x1a6a3
$func220 @ 00992bd6:0xce95
$func8115 @ 00992bd6:0x1a2195
$func2054 @ 00992bd6:0x85bba
$func2052 @ 00992bd6:0x85b30
$func1395 @ 00992bd6:0x685fb
$func313 @ 00992bd6:0x1d491
$func283 @ 00992bd6:0x1c906
$func221 @ 00992bd6:0xdff6
$func220 @ 00992bd6:0xce95
$func8115 @ 00992bd6:0x1a2195
$func2054 @ 00992bd6:0x85bba
$func2059 @ 00992bd6:0x86222
$func2086 @ 00992bd6:0x882e1
$mono_wasm_invoke_method_ref @ 00992bd6:0x9bd1
Module._mono_wasm_invoke_method_ref @ dotnet.7.0.2.t82std0vpt.js:14
_Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ _Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:26
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Gt @ blazor.webassembly.js:1
Ii @ dotnet.7.0.2.t82std0vpt.js:5
_mono_wasm_invoke_js_blazor @ dotnet.7.0.2.t82std0vpt.js:14
$func313 @ 00992bd6:0x1d4d8
$func283 @ 00992bd6:0x1c906
$func221 @ 00992bd6:0xdff6
$func220 @ 00992bd6:0xce95
$func8115 @ 00992bd6:0x1a2195
$func2054 @ 00992bd6:0x85bba
$func2059 @ 00992bd6:0x86222
$func2086 @ 00992bd6:0x882e1
$mono_wasm_invoke_method_ref @ 00992bd6:0x9bd1
Module._mono_wasm_invoke_method_ref @ dotnet.7.0.2.t82std0vpt.js:14
_Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ _Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:26
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Gt @ blazor.webassembly.js:1
Ii @ dotnet.7.0.2.t82std0vpt.js:5
_mono_wasm_invoke_js_blazor @ dotnet.7.0.2.t82std0vpt.js:14
$func313 @ 00992bd6:0x1d4d8
$func283 @ 00992bd6:0x1c906
$func221 @ 00992bd6:0xdff6
$func220 @ 00992bd6:0xce95
$func8115 @ 00992bd6:0x1a2195
$func2054 @ 00992bd6:0x85bba
$func2059 @ 00992bd6:0x86222
$func2086 @ 00992bd6:0x882e1
$mono_wasm_invoke_method_ref @ 00992bd6:0x9bd1
Module._mono_wasm_invoke_method_ref @ dotnet.7.0.2.t82std0vpt.js:14
_Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ _Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:26
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Gt @ blazor.webassembly.js:1
Ii @ dotnet.7.0.2.t82std0vpt.js:5
_mono_wasm_invoke_js_blazor @ dotnet.7.0.2.t82std0vpt.js:14
$func313 @ 00992bd6:0x1d4d8
$func283 @ 00992bd6:0x1c906
$func221 @ 00992bd6:0xdff6
$func220 @ 00992bd6:0xce95
$func8115 @ 00992bd6:0x1a2195
$func2054 @ 00992bd6:0x85bba
$func2059 @ 00992bd6:0x86222
$func2086 @ 00992bd6:0x882e1
$mono_wasm_invoke_method_ref @ 00992bd6:0x9bd1
Module._mono_wasm_invoke_method_ref @ dotnet.7.0.2.t82std0vpt.js:14
_Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ _Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:26
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Gt @ blazor.webassembly.js:1
Ii @ dotnet.7.0.2.t82std0vpt.js:5
_mono_wasm_invoke_js_blazor @ dotnet.7.0.2.t82std0vpt.js:14
$func313 @ 00992bd6:0x1d4d8
$func283 @ 00992bd6:0x1c906
$func221 @ 00992bd6:0xdff6
$func220 @ 00992bd6:0xce95
$func8115 @ 00992bd6:0x1a2195
$func2054 @ 00992bd6:0x85bba
$func2059 @ 00992bd6:0x86222
$func2086 @ 00992bd6:0x882e1
$mono_wasm_invoke_method_ref @ 00992bd6:0x9bd1
Module._mono_wasm_invoke_method_ref @ dotnet.7.0.2.t82std0vpt.js:14
BINDINGS_SetTaskSourceResultRef @ BINDINGS_SetTaskSourceResultRef:27
Ki.t.<computed> @ dotnet.7.0.2.t82std0vpt.js:5
(anonymous) @ dotnet.7.0.2.t82std0vpt.js:5
Promise.then (async)
si @ dotnet.7.0.2.t82std0vpt.js:5
Qs @ dotnet.7.0.2.t82std0vpt.js:5
Xs @ dotnet.7.0.2.t82std0vpt.js:5
Ke._internal.getSatelliteAssemblies @ blazor.webassembly.js:1
Gt @ blazor.webassembly.js:1
Ii @ dotnet.7.0.2.t82std0vpt.js:5
_mono_wasm_invoke_js_blazor @ dotnet.7.0.2.t82std0vpt.js:14
$func313 @ 00992bd6:0x1d4d8
$func283 @ 00992bd6:0x1c906
$func221 @ 00992bd6:0xdff6
$func220 @ 00992bd6:0xce95
$func8115 @ 00992bd6:0x1a2195
$func2054 @ 00992bd6:0x85bba
$func2059 @ 00992bd6:0x86222
$func2086 @ 00992bd6:0x882e1
$mono_wasm_invoke_method_ref @ 00992bd6:0x9bd1
Module._mono_wasm_invoke_method_ref @ dotnet.7.0.2.t82std0vpt.js:14
_UNITS_Client__entrypoint @ _UNITS_Client__entrypoint:26
(anonymous) @ dotnet.7.0.2.t82std0vpt.js:5
ji @ dotnet.7.0.2.t82std0vpt.js:5
callEntryPoint @ blazor.webassembly.js:1
Vt @ blazor.webassembly.js:1
await in Vt (async)
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1

login-callback:1 Uncaught (in promise) ExitStatus {name: 'ExitStatus', message: 'Program terminated with exit(1)', status: 1}message: "Program terminated with exit(1)"name: "ExitStatus"status: 1[[Prototype]]: Objectconstructor: ƒ ExitStatus(status)[[Prototype]]: ObjectSymbol(wasm type): 0constructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Gt @ blazor.webassembly.js:1
Ii @ dotnet.7.0.2.t82std0vpt.js:5
_mono_wasm_invoke_js_blazor @ dotnet.7.0.2.t82std0vpt.js:14
$func313 @ 00992bd6:0x1d4d8
$func283 @ 00992bd6:0x1c906
$func221 @ 00992bd6:0xdff6
$func220 @ 00992bd6:0xce95
$func8115 @ 00992bd6:0x1a2195
$func2054 @ 00992bd6:0x85bba
$func2059 @ 00992bd6:0x86222
$func2086 @ 00992bd6:0x882e1
$mono_wasm_invoke_method_ref @ 00992bd6:0x9bd1
Module._mono_wasm_invoke_method_ref @ dotnet.7.0.2.t82std0vpt.js:14
_Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ _Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:26
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Gt @ blazor.webassembly.js:1
Ii @ dotnet.7.0.2.t82std0vpt.js:5
_mono_wasm_invoke_js_blazor @ dotnet.7.0.2.t82std0vpt.js:14
$func313 @ 00992bd6:0x1d4d8
$func283 @ 00992bd6:0x1c906
$func221 @ 00992bd6:0xdff6
$func220 @ 00992bd6:0xce95
$func8115 @ 00992bd6:0x1a2195
$func2054 @ 00992bd6:0x85bba
$func2059 @ 00992bd6:0x86222
$func2086 @ 00992bd6:0x882e1
$mono_wasm_invoke_method_ref @ 00992bd6:0x9bd1
Module._mono_wasm_invoke_method_ref @ dotnet.7.0.2.t82std0vpt.js:14
_Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ _Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:26
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Gt @ blazor.webassembly.js:1
Ii @ dotnet.7.0.2.t82std0vpt.js:5
_mono_wasm_invoke_js_blazor @ dotnet.7.0.2.t82std0vpt.js:14
$func313 @ 00992bd6:0x1d4d8
$func283 @ 00992bd6:0x1c906
$func221 @ 00992bd6:0xdff6
$func220 @ 00992bd6:0xce95
$func8115 @ 00992bd6:0x1a2195
$func2054 @ 00992bd6:0x85bba
$func2059 @ 00992bd6:0x86222
$func2086 @ 00992bd6:0x882e1
$mono_wasm_invoke_method_ref @ 00992bd6:0x9bd1
Module._mono_wasm_invoke_method_ref @ dotnet.7.0.2.t82std0vpt.js:14
_Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS @ _Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_EndInvokeJS:26
endInvokeJSFromDotNet @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
Promise.then (async)
beginInvokeJSFromDotNet @ blazor.webassembly.js:1
Gt @ blazor.webassembly.js:1
Ii @ dotnet.7.0.2.t82std0vpt.js:5
_mono_wasm_invoke_js_blazor @ dotnet.7.0.2.t82std0vpt.js:14
$func313 @ 00992bd6:0x1d4d8
$func283 @ 00992bd6:0x1c906
$func221 @ 00992bd6:0xdff6
$func220 @ 00992bd6:0xce95
$func8115 @ 00992bd6:0x1a2195
$func2054 @ 00992bd6:0x85bba
$func2059 @ 00992bd6:0x86222
$func2086 @ 00992bd6:0x882e1
$mono_wasm_invoke_method_ref @ 00992bd6:0x9bd1
Module._mono_wasm_invoke_method_ref @ dotnet.7.0.2.t82std0vpt.js:14
BINDINGS_SetTaskSourceResultRef @ BINDINGS_SetTaskSourceResultRef:27
Ki.t.<computed> @ dotnet.7.0.2.t82std0vpt.js:5
(anonymous) @ dotnet.7.0.2.t82std0vpt.js:5
Promise.then (async)
si @ dotnet.7.0.2.t82std0vpt.js:5
Qs @ dotnet.7.0.2.t82std0vpt.js:5
Xs @ dotnet.7.0.2.t82std0vpt.js:5
Ke._internal.getSatelliteAssemblies @ blazor.webassembly.js:1
Gt @ blazor.webassembly.js:1
Ii @ dotnet.7.0.2.t82std0vpt.js:5
_mono_wasm_invoke_js_blazor @ dotnet.7.0.2.t82std0vpt.js:14
$func313 @ 00992bd6:0x1d4d8
$func283 @ 00992bd6:0x1c906
$func221 @ 00992bd6:0xdff6
$func220 @ 00992bd6:0xce95
$func8115 @ 00992bd6:0x1a2195
$func2054 @ 00992bd6:0x85bba
$func2059 @ 00992bd6:0x86222
$func2086 @ 00992bd6:0x882e1
$mono_wasm_invoke_method_ref @ 00992bd6:0x9bd1
Module._mono_wasm_invoke_method_ref @ dotnet.7.0.2.t82std0vpt.js:14
_UNITS_Client__entrypoint @ _UNITS_Client__entrypoint:26
(anonymous) @ dotnet.7.0.2.t82std0vpt.js:5
ji @ dotnet.7.0.2.t82std0vpt.js:5
callEntryPoint @ blazor.webassembly.js:1
Vt @ blazor.webassembly.js:1
await in Vt (async)
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1

DevTools failed to load source map: Could not load content for chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
```

### .NET Version

7.0.2

**Comment by Nick-Stanton** [comment]
Hi @Herdo, thank you for your submission. Could you please check your package versions and make sure that they are all updated? It would also be helpful to share your project's `.csproj`.
