### ISSUE TITLE
dotnet6 application not working in windows server 2016

### ISSUE THREAD

**Issue by rameshreddy5763** [dotnet/aspnetcore#46348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Getting below error after deploying to windows server. Installed latest hosting bundle.
```
Fatal error. Internal CLR error. (0x80131506)
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Span`1<System.Object> ByRef, System.Signature, Boolean, Boolean)
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1<System.Object> ByRef, System.Reflection.RuntimeModule, Int32, System.RuntimeType, Boolean, ListBuilder`1<System.Object>)
   at System.Reflection.CustomAttribute.GetCustomAttributes(System.Reflection.RuntimeModule, Int32, Int32, System.RuntimeType)
   at System.Reflection.CustomAttribute.GetCustomAttributes(System.RuntimeType, System.RuntimeType, Boolean)
   at System.RuntimeType.GetCustomAttributes(System.Type, Boolean)
   at System.Attribute.GetCustomAttributes(System.Reflection.MemberInfo, System.Type, Boolean)
   at System.Attribute.GetCustomAttribute(System.Reflection.MemberInfo, System.Type, Boolean)
   at System.Diagnostics.Tracing.EventSource.GetCustomAttributeHelper(System.Reflection.MemberInfo, System.Type, System.Diagnostics.Tracing.EventManifestOptions)
   at System.Diagnostics.Tracing.EventSource.GetGuid(System.Type)
   at System.Diagnostics.Tracing.EventSource..ctor(System.Diagnostics.Tracing.EventSourceSettings, System.String[])
   at System.Diagnostics.Tracing.EventSource..ctor(System.Diagnostics.Tracing.EventSourceSettings)
   at System.Diagnostics.Tracing.EventSource..ctor()
   at System.Net.NetEventSource..ctor()
   at System.Net.NetEventSource..cctor()
   at System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi..cctor()
   at System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi.get_IsQuicSupported()
   at System.Net.Quic.Implementations.MsQuic.MsQuicImplementationProvider.get_IsSupported()
   at Microsoft.AspNetCore.Hosting.WebHostBuilderQuicExtensions.UseQuic(Microsoft.AspNetCore.Hosting.IWebHostBuilder)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderKestrelExtensions.UseKestrel(Microsoft.AspNetCore.Hosting.IWebHostBuilder)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderKestrelExtensions.UseKestrel(Microsoft.AspNetCore.Hosting.IWebHostBuilder, System.Action`2<Microsoft.AspNetCore.Hosting.WebHostBuilderContext,Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions>)
   at Microsoft.AspNetCore.WebHost.ConfigureWebDefaults(Microsoft.AspNetCore.Hosting.IWebHostBuilder)
   at Microsoft.Extensions.Hosting.GenericHostBuilderExtensions+<>c__DisplayClass0_0.<ConfigureWebHostDefaults>b__0(Microsoft.AspNetCore.Hosting.IWebHostBuilder)
   at Microsoft.Extensions.Hosting.GenericHostWebHostBuilderExtensions.ConfigureWebHost(Microsoft.Extensions.Hosting.IHostBuilder, System.Action`1<Microsoft.AspNetCore.Hosting.IWebHostBuilder>, System.Action`1<Microsoft.Extensions.Hosting.WebHostBuilderOptions>)
   at Microsoft.Extensions.Hosting.GenericHostWebHostBuilderExtensions.ConfigureWebHost(Microsoft.Extensions.Hosting.IHostBuilder, System.Action`1<Microsoft.AspNetCore.Hosting.IWebHostBuilder>)
   at Microsoft.Extensions.Hosting.GenericHostBuilderExtensions.ConfigureWebHostDefaults(Microsoft.Extensions.Hosting.IHostBuilder, System.Action`1<Microsoft.AspNetCore.Hosting.IWebHostBuilder>)
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder..ctor(Microsoft.AspNetCore.Builder.WebApplicationOptions, System.Action`1<Microsoft.Extensions.Hosting.IHostBuilder>)
   at Microsoft.AspNetCore.Builder.WebApplication.CreateBuilder(System.String[])
   at Program.<Main>$(System.String[])
```

### Expected Behavior

Should be able to browse the application without any issues

### .NET Version

dotnet6

[edited by @danmoseley to add triple ticks and remove extra stack]

**Comment by danmoseley** [comment]
Hello there. Did it ever work? If so, what changed?
You mention the OS - any reason to believe it’s specific to that OS?
Can you simplify the app until it starts working?
If you build and deploy a new web app from the same template, with no added code, does it work?

**Comment by danmoseley** [comment]
This looks like https://github.com/dotnet/runtime/issues/69805. I'm going to close in favor of that. Let's continue the conversation there.

**Comment by rameshreddy5763** [comment]
Hi, We have .Net Core 3.1 applications working in Servers without any issue.
Now we started migrating to dotnet6 and installed the dotnet6 hosting bundle. After deploying to server we are getting above error.
Tried basic application without adding any nuget packages, this also failed to load.
