### ISSUE TITLE
Horizontal tabs causing issues in header values

### ISSUE THREAD

**Issue by Abhishek2096** [dotnet/aspnetcore#46543]
Hi Team,
We are trying to deploy a dotnet 6.0 application into Azure Kubernetes Cluster Linux Platform , we are setting the headers through a middleware project and we are passing Content-Security-Policy values which includes values with // as below 
```
public async Task InvokeAsync(HttpContext httpContext)
{
    httpContext.Response.Headers.Add(
    "Content-Security-Policy",
    "default-src 'self' 'unsafe-eval' 'unsafe-inline' https://login.microsoftonline.com" +
    "img-src 'self' data:; " +
    "font-src 'self'  " +
    "connect-src 'self' ; " +
    "script-src 'self' 'unsafe-inline' 'unsafe-eval' " +
    "form-action 'self';");
    await _next(httpContext);
}
```
 but we are getting errors while we are deploying to the AKS environment and also on the local machine . The errors comes something as below :

   System.InvalidOperationException: Invalid non-ASCII or control character in header: 0x00A0
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowInvalidHeaderCharacter(Char ch)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ValidateHeaderValueCharacters(String headerName, StringValues headerValues, Func`2 encodingSelector)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseHeaders.AddValueFast(String key, StringValues value)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.System.Collections.Generic.IDictionary<System.String,Microsoft.Extensions.Primitives.StringValues>.Add(String key, StringValues value)

Also, we are using dotnet 6.0 mcr based base image which has dotnet 6.0.13 .  As we came to know with another post https://github.com/dotnet/aspnetcore/issues/40599 that headers are accepting these characters but still we are facing issues for us 

Please help us resolve this .

**Comment by adityamandaleeka** [comment]
Based on the error message, the character that's causing problems for you is a [non-breaking space (0xA0)](https://en.wikipedia.org/wiki/Non-breaking_space), not an HTAB.

If you're able to reproduce it locally you should be able to break on the exception in a debugger and see where it's coming from.
