### ISSUE TITLE
.Net 6 assembly utilizing Microsoft.Extensions.Diagnostics.Healthchecks v 6.0.13 fails to load .Net 7 dependency.

### ISSUE THREAD

**Issue by Willow766** [dotnet/aspnetcore#46567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

.Net 6 using Microsoft.Extensions.Diagnostics.Healthchecks nuget version 6.0.13 crashes due to a missing Microsoft.Bcl.AsycInterfaces 7.0 assembly. 
I don't want to hear your reasoning. I want to hear that it's been corrected.  Pick a platform please.

### Expected Behavior

AsyncInterfaces was included in net standard 2.  It exists but the version compatibility is out of control.  Microsoft is not adhering to their own versioning standard.  Expected behavior is not to crash because referential integrity is out of control.

### Steps To Reproduce

Create a .Net 6 non-WebAPI project, add Microsoft.Extensions.Diagnostics.Healthchecks 6.0.13.  Run it - will crash due to missing .net 7 assembly (Microsoft.Bcl.AsyncInterfaces v 7.0).

### Exceptions (if any)

Message: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
Source: Microsoft.Extensions.Diagnostics.HealthChecks
StackTrace:    at Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService.RunCheckAsync(HealthCheckRegistration registration, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Diagnostics.HealthChecks.DefaultHealthCheckService.<CheckHealthAsync>d__4.MoveNext()
   at HealthMonitor.<RunHealthChecks>d__14.MoveNext()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

### .NET Version

6.0

**Comment by davidfowl** [comment]
> Create a .Net 6 non-WebAPI project, add Microsoft.Extensions.Diagnostics.Healthchecks 6.0.13. Run it - will crash due to missing .net 7 assembly (Microsoft.Bcl.AsyncInterfaces v 7.0).

You can provide a runnable repro as a github repository? I just wrote a worker service with a dependency in this package, and I don't see any issues.

**Comment by Willow766** [comment]
My apologies. This is a windows Service, so that is the crossover.
For the immediate workaround I installed Microsoft.Bcl.AsyncInterfaces v 7.0. Healthchecks is now also 7.0 although I did not target that.  Either way, it resolves the issue but as 7 is not LTS we will need this addressed either as a code change or an agreement to maintain .Net 7 LTS for compoenents referenced from .Net 6 nuget assemblies.

**Comment by davidfowl** [comment]
I still can't reproduce the problem. Can you make a new project and reproduce the issue and drop the instructions in the original issue?

**Comment by Willow766** [comment]
David,
That would be because the issue is on our end.  In continuing investigation it appears the healthchecks assembly version was upgraded by a different developer, which created the issue.  My apologies for the gripe.  This is on us.  Please close as resolved.

**Comment by davidfowl** [comment]
Ah, got it!
