### ISSUE TITLE
NullReferenceException in DefaultOutputFormatterSelector.ValidateContentTypes

### ISSUE THREAD

**Issue by MoRooz** [dotnet/aspnetcore#46628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

we have an issue in one api.

it is simple json request like this 
```
{"videoId":11093,"second":678}
```

the api:

```c#
[Produces(MediaTypeNames.Application.Json)]
[Route("api/Bonyan")]
public sealed class BonyanController : ApiController
{
    private readonly IBonyanService service;

    public BonyanController(IBonyanService service)
    {
        this.service = service;
    }

[HttpPost(nameof(UpdateVideoSecond))]
    public async Task<OkObjectResult> UpdateVideoSecond([FromBody] UpdateVideoSecondRequest request)
    {
        await service.UpdateVideoSecond(request);
        return new OkObjectResult(true);
    }
}
```

```c#
public class UpdateVideoSecondRequest
{
    public int VideoId { get; init; }

    public int Second { get; init; }
}
```

some useful info:
it happens mostly (maybe always ) when users use apk/pwa on mobile devices.

there is nothing wrong in request body, exception handling logs the request and it's valid json like sample above.
I don't know what is the effect of user language/culture/browser on http request and if it related to this exception or not.

### Exceptions (if any)

```c#
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector.ValidateContentTypes(MediaTypeCollection contentTypes)
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector.SelectFormatter(OutputFormatterCanWriteContext context, IList`1 formatters, MediaTypeCollection contentTypes)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncCore(ActionContext context, ObjectResult result, Type objectType, Object value)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
```

### .NET Version

7.0

**Comment by brunolins16** [comment]
@MoRooz The client should not affect this validation, based on the exception stack trace the list of `contentTypes` should come from your `ObjectResult`, that based on your example it should be populate with a single item `application/json`. Do you have any additional customization in  the`ApiController` base class? Or maybe some additional filters that modify the `ObjectResult.ContentTypes`?

If possible, can you share a simple repository with a minimalistic app where we can repro the issue?

**Comment by MoRooz** [comment]
this is a full exception log

I don't understand why we have Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke call?




```c#
2023-02-13 21:44:41.885 +03:30 [ERR] P: /api/Bonyan/UpdateVideoSecond, U: 10104, G: 7, R: {"videoId":13116,"second":0}, 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector.ValidateContentTypes(MediaTypeCollection contentTypes)
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector.SelectFormatter(OutputFormatterCanWriteContext context, IList`1 formatters, MediaTypeCollection contentTypes)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncCore(ActionContext context, ObjectResult result, Type objectType, Object value)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Kookaat.WebApi.Middleware.ErrorHandler.Invoke(HttpContext context) in C:\Project\Kookaat\Solution\Kookaat.WebApi\Middleware\ErrorHandler.cs:line 33
```


this is swagger config



```c#

//rest of code
var builder = WebApplication.CreateBuilder(args);
        ConfigureServices(builder.Services);
        builder.Host.UseSerilog();
        builder.WebHost.ConfigureKestrel(options => options.AddServerHeader = false).UseUrls(Service.SharedSetting.CoreConfig.CallCenterEnabled ? Core.SharedSetting.HostConfig.CallCenterKestrel : Core.SharedSetting.HostConfig.CoreKestrel);
        var app = builder.Build();
app.UseForwardedHeaders();
        app.UseRouting();
        app.UseGrpcWeb();
        app.UseCors("CorsPolicy");
        app.UseMiddleware<TokenAuthentication>();
        app.UseMiddleware<ErrorHandler>();
        app.UseStaticFiles();
        ConfigSwagger(app);
//rest of code





private static void ConfigSwagger(IApplicationBuilder app)
    {
        if (InternalSetting.SwaggerConfiguration.Enabled)
        {
            app.UseSwagger();
            app.UseSwaggerUI(
                c =>
                {
                    if (InternalSetting.SwaggerConfiguration.Kookaat)
                    {
                        c.SwaggerEndpoint($"{(string.IsNullOrEmpty(InternalSetting.SwaggerConfiguration.UrlPrefix) ? string.Empty : "/" + InternalSetting.SwaggerConfiguration.UrlPrefix)}/swagger/v1/swagger.json", "Kookaat API Full");
                    }

                    c.InjectStylesheet($"{(string.IsNullOrEmpty(InternalSetting.SwaggerConfiguration.UrlPrefix) ? string.Empty : "/" + InternalSetting.SwaggerConfiguration.UrlPrefix)}/swagger-ui/custom.css");
                });
        }
    }


private static void ConfigureServices(IServiceCollection services)
{
//rest of code

if (InternalSetting.SwaggerConfiguration.Enabled)
        {
            services.AddSwaggerGen(
                c =>
                {
                    if (InternalSetting.SwaggerConfiguration.Kookaat)
                    {
                        c.SwaggerDoc(
                            "v1",
                            new OpenApiInfo
                            {
                                Title = "Kookaat API Full",
                                Version = "v1",
                                Description = "Kookaat Framework API Document",
                                Contact = new OpenApiContact { Name = "Mohammad Roozban", Email = "m.roozban@gmail.com" },
                            });
                    }

                    c.DocInclusionPredicate(
                        (docName, apiDesc) =>
                        {
                            if (docName == nameof(InternalSetting.SwaggerConfiguration.SimRegistration))
                            {
                                return apiDesc.ActionDescriptor.AttributeRouteInfo.Template.Contains(docName, StringComparison.InvariantCultureIgnoreCase);
                            }

                            return true;
                        });

                    c.AddSecurityDefinition(
                        "Bearer",
                        new OpenApiSecurityScheme { Description = "Authorization header", Name = "Authorization", In = ParameterLocation.Header, Type = SecuritySchemeType.ApiKey });

                    c.AddSecurityRequirement(
                        new OpenApiSecurityRequirement()
                        {
                            {
                                new OpenApiSecurityScheme
                                {
                                    Reference = new OpenApiReference
                                    {
                                        Type = ReferenceType.SecurityScheme,
                                        Id = "Bearer",
                                    },
                                    Scheme = "oauth2",
                                    Name = "Bearer",
                                    In = ParameterLocation.Header,
                                },
                                new List<string>()
                            },
                        });

                    // no effect ?
                    c.OrderActionsBy(apiDesc => apiDesc.ActionDescriptor.AttributeRouteInfo.Template);

                    c.IncludeXmlComments(Path.Combine(Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location), "XmlDoc", "Kookaat.Dto.xml"));
                    c.IncludeXmlComments(Path.Combine(Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location), "XmlDoc", "Kookaat.Core.xml"));
                    //c.OperationFilter<Common.Swagger.FileUploadOperation>();
                    c.CustomSchemaIds(x => x.FullName);
                    c.EnableAnnotations();

                    c.SchemaFilter<Common.Swagger.EnumNamesSchemaFilter>();
                    c.ParameterFilter<Common.Swagger.EnumNamesParameterFilter>();
                    c.DocumentFilter<Common.Swagger.DisplayEnumsWithValuesDocumentFilter>();

                    c.TagActionsBy(Common.Swagger.ApiDescriptionExtension.GetTagName);
                });
        }

//rest of code
}
```

here is base controller

```c#
public abstract class ApiController
{
    protected static readonly OkObjectResult OkJson = new OkObjectResult(new ApiOkResponse());

    [UsedImplicitly]
    [ActionContext]
    // must be public to be filled
    public ActionContext ActionContext { get; set; }

    protected HttpRequest Request => ActionContext?.HttpContext.Request;

    protected IPAddress Ip => HttpContext.Connection.RemoteIpAddress;

    protected string Origin => HttpContext.Request.Headers.ContainsKey("Origin") && !string.IsNullOrEmpty(HttpContext.Request?.Headers["Origin"]) ? HttpContext.Request?.Headers["Origin"] : null;

    protected string UserAgent => HttpContext.Request.Headers.ContainsKey("User-Agent") ? HttpContext.Request.Headers["User-Agent"].ToString() : null;

    private HttpContext HttpContext => ActionContext?.HttpContext;

    protected static OkObjectResult GetOkObjectResult<T>(T value)
    {
        return new OkObjectResult(new ApiOkResponse<T> { ReturnValue = value });
    }

    private sealed class ApiOkResponse
    {
        [UsedImplicitly]
        public int Code { get; }
    }

    private sealed class ApiOkResponse<T>
    {
        [UsedImplicitly]
        public int Code { get; }

        public T ReturnValue { get; set; }
    }

```


for now I'll remove swagger from production completely to see if it's swagger fault or not.

**Comment by MoRooz** [comment]
regardless of cause of this I suggest null checking of elements of contentTypes collection to be added.

```c#
public override IOutputFormatter? SelectFormatter(OutputFormatterCanWriteContext context, IList<IOutputFormatter> formatters, MediaTypeCollection contentTypes)
    {
        //this line should also check elements of contentTypes also
        ArgumentNullException.ThrowIfNull(contentTypes);

        ValidateContentTypes(contentTypes);
```

[https://github.com/dotnet/aspnetcore/blob/main/src/Mvc/Mvc.Core/src/Infrastructure/DefaultOutputFormatterSelector.cs](url)

**Comment by MoRooz** [comment]
it's not related to swagger.

```c#
2023-02-18 00:40:00.567 +03:30 [ERR] P: /api/Bonyan/UpdateVideoSecond, U: 10053, G: 7, R: {"videoId":15079,"second":223}, 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector.ValidateContentTypes(MediaTypeCollection contentTypes)
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector.SelectFormatter(OutputFormatterCanWriteContext context, IList`1 formatters, MediaTypeCollection contentTypes)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncCore(ActionContext context, ObjectResult result, Type objectType, Object value)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Kookaat.WebApi.Middleware.ErrorHandler.Invoke(HttpContext context) in C:\Project\Kookaat\Solution\Kookaat.WebApi\Middleware\ErrorHandler.cs:line 33
```

is there anyway to override DefaultOutputFormatterSelector.ValidateContentTypes? put some log in it or fill it with some default value when it's null? beside cloning and compiling whole repo

**Comment by brunolins16** [comment]
@MoRooz Have you try adding a Result Filter to see confirm what you have in the `Result.ContentTypes`?

**Comment by brunolins16** [comment]
Also, let me try to repro and understand what is happening with the entire code you shared.

**Comment by brunolins16** [comment]
@MoRooz Interesting that you are using a static `OkObjectResult` and I wonder if this might have been causing problems.

```c#
  protected static readonly OkObjectResult OkJson = new OkObjectResult(new ApiOkResponse());
```
