### ISSUE TITLE
SignalR test failures in release/6.0

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#46651]
## Failing Test(s)

-

## Error Message

```text
Exception in thread "main" java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
```

## Stacktrace

<details>

```text
Exception in thread "main" java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
��������������������������������������������������������������������SLSocketFactory.java:263)
	at java.base/javax.net.ssl.DefaultSSLSocketFactory.createSocket(SSLSocketFactory.java:270)
	at java.base/sun.net.www.protocol.https.HttpsClient.createSocket(HttpsClient.java:413)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:162)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1075)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:78)
	at org.gradle.wrapper.Download.download(Download.java:63)
	at org.gradle.wrapper.Install$1.call(Install.java:68)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
Caused by: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
	at java.base/java.security.Provider$Service.newInstance(Provider.java:1831)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:168)
	at java.base/javax.net.ssl.SSLContext.getDefault(SSLContext.java:99)
	at java.base/javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:123)
	at java.base/javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:335)
	at java.base/javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:292)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:95)
	at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
	at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
	at java.base/java.net.URL.openConnection(URL.java:1051)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:74)
	... 7 more
Caused by: java.security.KeyStoreException: problem accessing trust store
	at java.base/sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:75)
	at java.base/javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:278)
	at java.base/sun.security.ssl.SSLContextImpl$DefaultManagersHolder.getTrustManagers(SSLContextImpl.java:945)
	at java.base/sun.security.ssl.SSLContextImpl$DefaultManagersHolder.<clinit>(SSLContextImpl.java:917)
	at java.base/sun.security.ssl.SSLContextImpl$DefaultSSLContext.<init>(SSLContextImpl.java:1090)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at java.base/java.security.Provider.newInstanceUtil(Provider.java:153)
	at java.base/java.security.Provider.access$1100(Provider.java:107)
	at java.base/java.security.Provider$Service.newInstance(Provider.java:1824)
	... 19 more
Caused by: java.io.IOException: DerInputStream.getLength(): lengthTag=109, too big.
	at java.base/sun.security.util.DerInputStream.getLength(DerInputStream.java:606)
	at java.base/sun.security.util.DerValue.init(DerValue.java:390)
	at java.base/sun.security.util.DerValue.<init>(DerValue.java:331)
	at java.base/sun.security.util.DerValue.<init>(DerValue.java:344)
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1976)
	at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:222)
	at java.base/java.security.KeyStore.load(KeyStore.java:1479)
	at java.base/sun.security.ssl.TrustStoreManager$TrustAnchorManager.loadKeyStore(TrustStoreManager.java:367)
	at java.base/sun.security.ssl.TrustStoreManager$TrustAnchorManager.getTrustedCerts(TrustStoreManager.java:315)
	at java.base/sun.security.ssl.TrustStoreManager.getTrustedCerts(TrustStoreManager.java:59)
	at java.base/sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:51)
	... 30 more
+ export _commandExitCode=1
+ cp /root/helix/work/workitem/e/test/test-results/TEST-junit-jupiter.xml /root/helix/work/workitem/e/junit-results.xml
cp: cannot stat '/root/helix/work/workitem/e/test/test-results/TEST-junit-jupiter.xml': No such file or directory
```
</details>

## Logs

<details>

```text
Console log: 'signalr.client.java.Tests--' from job 518d7e33-5e73-4605-8e40-c69606ae58d8 (ubuntu.2004.amd64.open.svc) using docker image mcr.microsoft.com/dotnet-buildtools/prereqs:debian-11-helix-amd64 on a000FL1
running $HELIX_CORRELATION_PAYLOAD/scripts/4b6406eafdc04e8b9ddc3f97e18fe0a7/execute.sh in /datadisks/disk1/work/9EF908CA/w/A8B508E7/e max 2700 seconds

Output:
[BEGIN EXECUTION]
+ sudo python -m pip install --disable-pip-version-check -r /root/helix/scripts/runtime_python_requirements.txt
Requirement already satisfied: certifi>=2021.10.8 in /usr/local/lib/python3.9/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 1)) (2022.12.7)
Requirement already satisfied: ndg-httpsclient==0.5.1 in /usr/local/lib/python3.9/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 2)) (0.5.1)
Requirement already satisfied: psutil==5.9.3 in /usr/local/lib/python3.9/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 3)) (5.9.3)
Requirement already satisfied: pyasn1==0.4.5 in /usr/local/lib/python3.9/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 4)) (0.4.5)
Requirement already satisfied: pyopenssl==19.0.0 in /usr/local/lib/python3.9/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 5)) (19.0.0)
Requirement already satisfied: six>=1.11.0 in /usr/local/lib/python3.9/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 6)) (1.16.0)
Requirement already satisfied: cryptography<=3.4.6,>=2.8 in /usr/local/lib/python3.9/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 8)) (3.4.6)
Requirement already satisfied: asn1crypto==0.24.0 in /usr/local/lib/python3.9/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 9)) (0.24.0)
Requirement already satisfied: idna==2.8 in /usr/local/lib/python3.9/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 10)) (2.8)
Requirement already satisfied: cffi==1.15.1 in /usr/local/lib/python3.9/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 11)) (1.15.1)
Requirement already satisfied: pycparser==2.19 in /usr/local/lib/python3.9/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 12)) (2.19)
Requirement already satisfied: docker==3.7.2 in /usr/local/lib/python3.9/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 14)) (3.7.2)
Requirement already satisfied: docker-pycreds==0.4.0 in /usr/local/lib/python3.9/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 15)) (0.4.0)
Requirement already satisfied: websocket-client==0.56.0 in /usr/local/lib/python3.9/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 16)) (0.56.0)
Requirement already satisfied: requests<=2.28.1,>=2.21.0 in /usr/local/lib/python3.9/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 18)) (2.28.1)
Requirement already satisfied: urllib3==1.24.3 in /usr/local/lib/python3.9/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 19)) (1.24.3)
Requirement already satisfied: azure-storage-blob==12.5.0 in /usr/local/lib/python3.9/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 21)) (12.5.0)
Requirement already satisfied: azure-core==1.7.0 in /usr/local/lib/python3.9/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 22)) (1.7.0)
Requirement already satisfied: azure-devops==5.0.0b9 in /usr/local/lib/python3.9/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 23)) (5.0.0b9)
Requirement already satisfied: msrest==0.6.10 in /usr/local/lib/python3.9/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 24)) (0.6.10)
Requirement already satisfied: isodate==0.6.0 in /usr/local/lib/python3.9/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 25)) (0.6.0)
Requirement already satisfied: requests-oauthlib==1.2.0 in /usr/local/lib/python3.9/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 26)) (1.2.0)
Requirement already satisfied: oauthlib==3.1.0 in /usr/local/lib/python3.9/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 27)) (3.1.0)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.9/dist-packages (from requests<=2.28.1,>=2.21.0->-r /root/helix/scripts/runtime_python_requirements.txt (line 18)) (2.1.1)
+ export PYTHONPATH=/root/helix/scripts:
+ cd /root/helix/work/workitem/e
+ mkdir -p /home/helixbot/dotnetbuild/dumps/
+ /root/helix/work/correlation/scripts/4b6406eafdc04e8b9ddc3f97e18fe0a7/execute.sh
+ export PATH=/root/helix/work/correlation/dotnet-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ export DOTNET_ROOT=/root/helix/work/correlation/dotnet-cli
+ export DOTNET_CLI_TELEMETRY_OPTOUT=1
+ export DOTNET_CLI_HOME=/root/helix/work/workitem/e/.dotnet
+ export NUGET_PACKAGES=/root/helix/work/workitem/e/.nuget
+ ./installjdk.sh 10.0.2 x64
/root/helix/work/workitem/e /root/helix/work/workitem/e
PlatformArch: linux-x64
Downloading from: https://netcorenativeassets.blob.core.windows.net/resource-packages/external/linux/java/jdk-10.0.2_linux-x64_bin.tar.gz
Installing java from jdk-10.0.2_linux-x64_bin.tar.gz https://netcorenativeassets.blob.core.windows.net/resource-packages/external/linux/java/jdk-10.0.2_linux-x64_bin.tar.gz
Unpacking to /root/helix/work/workitem/e/java
/root/helix/work/workitem/e
+ [  =  ]
+ export JAVA_HOME=/root/helix/work/workitem/e/java
+ chmod +x ./gradlew
+ ./gradlew -Dorg.gradle.daemon=false -PpackageVersion=6.0.15-ci test
Downloading https://services.gradle.org/distributions/gradle-6.5-bin.zip

Exception in thread "main" java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
��������������������������������������������������������������������SLSocketFactory.java:263)
	at java.base/javax.net.ssl.DefaultSSLSocketFactory.createSocket(SSLSocketFactory.java:270)
	at java.base/sun.net.www.protocol.https.HttpsClient.createSocket(HttpsClient.java:413)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:162)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1075)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:78)
	at org.gradle.wrapper.Download.download(Download.java:63)
	at org.gradle.wrapper.Install$1.call(Install.java:68)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
Caused by: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
	at java.base/java.security.Provider$Service.newInstance(Provider.java:1831)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:168)
	at java.base/javax.net.ssl.SSLContext.getDefault(SSLContext.java:99)
	at java.base/javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:123)
	at java.base/javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:335)
	at java.base/javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:292)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:95)
	at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
	at java.base/sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
	at java.base/java.net.URL.openConnection(URL.java:1051)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:74)
	... 7 more
Caused by: java.security.KeyStoreException: problem accessing trust store
	at java.base/sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:75)
	at java.base/javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:278)
	at java.base/sun.security.ssl.SSLContextImpl$DefaultManagersHolder.getTrustManagers(SSLContextImpl.java:945)
	at java.base/sun.security.ssl.SSLContextImpl$DefaultManagersHolder.<clinit>(SSLContextImpl.java:917)
	at java.base/sun.security.ssl.SSLContextImpl$DefaultSSLContext.<init>(SSLContextImpl.java:1090)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at java.base/java.security.Provider.newInstanceUtil(Provider.java:153)
	at java.base/java.security.Provider.access$1100(Provider.java:107)
	at java.base/java.security.Provider$Service.newInstance(Provider.java:1824)
	... 19 more
Caused by: java.io.IOException: DerInputStream.getLength(): lengthTag=109, too big.
	at java.base/sun.security.util.DerInputStream.getLength(DerInputStream.java:606)
	at java.base/sun.security.util.DerValue.init(DerValue.java:390)
	at java.base/sun.security.util.DerValue.<init>(DerValue.java:331)
	at java.base/sun.security.util.DerValue.<init>(DerValue.java:344)
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1976)
	at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:222)
	at java.base/java.security.KeyStore.load(KeyStore.java:1479)
	at java.base/sun.security.ssl.TrustStoreManager$TrustAnchorManager.loadKeyStore(TrustStoreManager.java:367)
	at java.base/sun.security.ssl.TrustStoreManager$TrustAnchorManager.getTrustedCerts(TrustStoreManager.java:315)
	at java.base/sun.security.ssl.TrustStoreManager.getTrustedCerts(TrustStoreManager.java:59)
	at java.base/sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:51)
	... 30 more
+ export _commandExitCode=1
+ cp /root/helix/work/workitem/e/test/test-results/TEST-junit-jupiter.xml /root/helix/work/workitem/e/junit-results.xml
cp: cannot stat '/root/helix/work/workitem/e/test/test-results/TEST-junit-jupiter.xml': No such file or directory
+ python /root/helix/work/correlation/reporter/run.py https://dev.azure.com/dnceng-public/ public 3424281 eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im9PdmN6NU1fN3AtSGpJS2xGWHo5M3VfVjBabyJ9.eyJuYW1laWQiOiJjNzczZjJjMi01MTIwLTQyMDctYWZlMi1hZmFmMzVhOGJjMGEiLCJzY3AiOiJhcHBfdG9rZW4iLCJhdWkiOiJkZTdkOTQ4NC0wODRjLTQyYjMtYjcwZS0xOWNmZGFmNDcyNTIiLCJzaWQiOiJjYzk0OTQ1Yi1mNzg3LTQwMjctOTc1OC00ZDcxN2VjNzY3YTYiLCJCdWlsZElkIjoiY2JiMTgyNjEtYzQ4Zi00YWJiLTg2NTEtOGNkY2I1NDc0NjQ5OzE3MTAyNyIsImpvYnJlZiI6IjQ0Yjc1YmNlLWJiMGYtNGZjMS05OGRkLTczYWY1MGMxZWMxMTo4YzlkZDZhZS01MDE3LTVhNzAtOTk3Yy1jMjM4NmZlZDRlODUiLCJwcGlkIjoidnN0ZnM6Ly8vQnVpbGQvQnVpbGQvMTcxMDI3Iiwib3JjaGlkIjoiNDRiNzViY2UtYmIwZi00ZmMxLTk4ZGQtNzNhZjUwYzFlYzExLmhlbGl4X21hdHJpeF94NjQuX19kZWZhdWx0IiwicmVwb0lkcyI6IiIsImlzcyI6ImFwcC52c3Rva2VuLnZpc3VhbHN0dWRpby5jb20iLCJhdWQiOiJhcHAudnN0b2tlbi52aXN1YWxzdHVkaW8uY29tfHZzbzo2ZmNjOTJlNS03M2E3LTRmODgtOGQxMy1kOTA0NWI0NWZiMjciLCJuYmYiOjE2NzYzNjQ5NDcsImV4cCI6MTY3NjM5NTU0Nn0.tI1wznF3oYU8dB-etRB5BCnrOYeumpJWHveJg5IbptT5s3SRN9aTlx-Xe_L0-SCM6bC3121lT7PJI5th9T1eeZMKGW6G-0tDH6Oa9yt7VZWOatsrq9jO1SG2axGIaZkPX9porSgmSBYpeFAG64HcsCzWYS1MU7N2YSfH-LCpTznxolxW0-tW-bQRp2n57DjxVP2JHnPwmzZPNO8cTI_5VY2qtx8pocJv9oHKAc0ZBlQ0IvcYQUV41KE8RVpvMSTXfBnzChtoqbqJD6U_wazI3oP0zg4KZ6JyeEt4q73dQYFvwoMIdLLFNb21XsWS8VDbtYy4GVTZ6el3ARBfqS4hzQ
2023-02-14T10:00:31.272Z	INFO   	run.py	run(48)	main	Beginning reading of test results.
2023-02-14T10:00:31.273Z	INFO   	run.py	__init__(42)	read_results	Searching '/root/helix/work/workitem/e' for test results files
2023-02-14T10:00:31.281Z	INFO   	run.py	__init__(42)	read_results	Searching '/root/helix/work/workitem/uploads' for test results files
2023-02-14T10:00:31.286Z	WARNING	run.py	__init__(55)	read_results	No results file found in any of the following formats: xunit, junit, trx
2023-02-14T10:00:31.287Z	INFO   	run.py	packing_test_reporter(30)	report_results	Packing 0 test reports to '/root/helix/work/workitem/e/__test_report.json'
2023-02-14T10:00:31.291Z	INFO   	run.py	packing_test_reporter(33)	report_results	Packed 1500 bytes
+ python -B /root/helix/work/correlation/xunit-reporter.py
2023-02-14T10:00:31.736Z	INFO   	xunit-reporter.py	xunit-reporter(85)	main	Didn't find test results in working directory, trying upload folder
2023-02-14T10:00:31.737Z	ERROR  	xunit-reporter.py	xunit-reporter(90)	main	Unable to report xunit results: no test results xml file found.
+ exit 1
+ export _commandExitCode=1
+ chmod -R 777 /home/helixbot/dotnetbuild/dumps
+ exit 1

[END EXECUTION]
Exit Code:1
```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=171027

**Queue**: Debian.11

**Comment by BrennanConroy** [comment]
Looks like a transient network failure. Closing for now. If it becomes more common we can look at adding retries.
