### ISSUE TITLE
Unobserved task exception in SignalR dotnet client

### ISSUE THREAD

**Issue by dannyhaak** [dotnet/aspnetcore#46705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After solving the previous Unobserved Task Exception in the C# SignalR client, we found another one in Microsoft.AspNetCore.SignalR.Client version 7.0.1.

```
Unobserved task exception in sender "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[System.Threading.Tasks.VoidTaskResult,Microsoft.AspNetCore.SignalR.Client.HubConnection+<CommonStreaming>d__68]"
```

```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Cannot access a disposed object.
Object name: 'HttpConnection'.)
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'HttpConnection'.
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.CheckDisposed()
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.get_Transport()
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.SendHubMessage(ConnectionState connectionState, HubMessage hubMessage, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.CommonStreaming(ConnectionState connectionState, String streamId, Func`1 createAndConsumeStream)
   --- End of inner exception stack trace ---
```

We see this happening quite regularly on our IoT devices, on typically bad connections, or when we restart our server.

*Sometimes* SignalR won't reconnect after this happens, but *sometimes* it does. We cannot yet find a pattern in this. Unfortunately, we are not yet able to reproduce this in a controlled environment, but we have now tens of examples of this happening in the field.

SignalR is configured to use MessagePack serialiser. It's configured to use WebSockets. Backend connection is to ASP.NET Core 7.0.1.

### Expected Behavior

Not having those exceptions.

### Steps To Reproduce

If only... We'll try to figure out a pattern, but it has been difficult to reproduce and get more logging.

### .NET Version

6.x on device, 7.x on server

### Anything else?

Device is running on ARM Embedded Linux.

**Comment by dannyhaak** [comment]
On the same device we also see this UTE:

```
Unobserved task exception in sender "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[System.Int32,System.Net.Http.HttpConnection+RawConnectionStream+<ReadAsync>d__6]"
```

```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Unable to read data from the transport connection: Operation canceled.)
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 )
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter )
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter , Memory`1 )
   at System.Net.Http.HttpConnection.ReadBufferedAsyncCore(Memory`1 )
   at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 , CancellationToken )
   --- End of inner exception stack trace ---
```
