### ISSUE TITLE
Quarantine ServerReset_BeforeRequestBody_ClientBodyThrows 

### ISSUE THREAD

**Issue by sebastienros** [dotnet/aspnetcore#46717]
## Failing Test(s)

Interop.FunctionalTests.HttpClientHttp2InteropTests.ServerReset_BeforeRequestBody_ClientBodyThrows(scheme: "http")

## Error Message

```text
Assert.Throws() Failure
Expected: typeof(System.Net.Http.HttpProtocolException)
Actual:   typeof(System.TimeoutException): The operation has timed out.
```

## Stacktrace

<details>

```text
[0.002s] TestLifetime Information: Starting test ServerReset_BeforeRequestBody_ClientBodyThrows-http at 2023-02-16T19:30:12
[0.004s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting starting
[0.006s] Microsoft.Hosting.Lifetime Information: Now listening on: http://127.0.0.1:62225
[0.006s] Microsoft.AspNetCore.Hosting.Diagnostics Debug: Loaded hosting startup assembly Interop.FunctionalTests
[0.006s] Microsoft.Hosting.Lifetime Information: Application started. Press Ctrl+C to shut down.
[0.006s] Microsoft.Hosting.Lifetime Information: Hosting environment: Production
[0.006s] Microsoft.Hosting.Lifetime Information: Content root path: /private/tmp/helix/working/95B607EB/w/B4DB094B/e/
[0.006s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting started
[0.008s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMOGAGQC1994" accepted.
[0.008s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMOGAGQC1994" started.
[0.009s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMOGAGQC1994" sending SETTINGS frame for stream ID 0 with length 24 and flags NONE.
[0.009s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMOGAGQC1994" sending WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0.
[0.010s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMOGAGQC1994" received SETTINGS frame for stream ID 0 with length 12 and flags NONE.
[0.011s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMOGAGQC1994" sending SETTINGS frame for stream ID 0 with length 0 and flags ACK.
[0.011s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMOGAGQC1994" received WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0.
[0.011s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMOGAGQC1994" received HEADERS frame for stream ID 1 with length 35 and flags END_HEADERS.
[0.011s] Microsoft.AspNetCore.Hosting.Diagnostics Information: Request starting HTTP/2 POST http://127.0.0.1:62225/ - - -
[0.011s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMOGAGQC1994" sending HEADERS frame for stream ID 1 with length 53 and flags END_HEADERS.
[0.014s] Microsoft.AspNetCore.Server.Kestrel.Http2 Debug: Trace id "0HMOGAGQC1994:00000001": HTTP/2 stream error "CANCEL". A Reset is being sent to the stream.
Microsoft.AspNetCore.Connections.ConnectionAbortedException: The HTTP/2 stream was reset by the application with error code CANCEL.
[0.015s] Microsoft.AspNetCore.Hosting.Diagnostics Information: Request finished HTTP/2 POST http://127.0.0.1:62225/ - 200 - text/plain 3.8277ms
[0.015s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMOGAGQC1994" sending RST_STREAM frame for stream ID 1 with length 4 and flags 0x0.
[0.015s] Microsoft.AspNetCore.Server.Kestrel Information: Connection id "0HMOGAGQC1994", Request id "0HMOGAGQC1994:00000001": the application completed without reading the entire request body.
[0.016s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMOGAGQC1994" received SETTINGS frame for stream ID 0 with length 0 and flags ACK.
[0.017s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMOGAGQC1994" received PING frame for stream ID 0 with length 8 and flags NONE.
[0.017s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMOGAGQC1994" sending PING frame for stream ID 0 with length 8 and flags ACK.
[30.040s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HMOGAGQC1994" received FIN.
[30.040s] Microsoft.AspNetCore.Server.Kestrel.Http2 Debug: Connection id "0HMOGAGQC1994" is closed. The last processed stream ID was 1.
[30.040s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Some connections failed to close gracefully during server shutdown.
[30.040s] Microsoft.AspNetCore.Server.Kestrel.Http2 Debug: The connection queue processing loop for 0HMOGAGQC1994 completed.
[30.040s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HMOGAGQC1994" sending FIN because: "The client closed the connection."
[30.041s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMOGAGQC1994" stopped.
[30.042s] Interop.FunctionalTests.HttpClientHttp2InteropTests Error: Test threw an exception.
```
</details>

## Logs

<details>

```text

```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=174755&view=logs&j=3f6d4e0f-1b71-56b5-361e-d95b6e6da15a&t=e4ee6667-9b0a-5a6e-4e24-bcba939f2af2

**Comment by dougbu** [comment]
Is the fix here as simple as increasing a timeout setting somewhere❔

**Comment by sebastienros** [comment]
@dougbu I don't think so because we have seen it working very quickly, but when it failed it was after the default 30s max. We saw at least it fail twice in the last two days.

**Comment by amcasey** [comment]
This hasn't failed in the last 30 days.

**Comment by amcasey** [comment]
If I'm reading the code and the failure log correctly, it must have been [sending](https://github.com/dotnet/aspnetcore/blob/6b047bc57f9f9d3f015f348caad64f5d1bd3f0de/src/Servers/Kestrel/test/Interop.FunctionalTests/HttpClientHttp2InteropTests.cs#L466) [content](https://github.com/dotnet/aspnetcore/blob/6b047bc57f9f9d3f015f348caad64f5d1bd3f0de/src/Servers/Kestrel/test/Interop.FunctionalTests/HttpClientHttp2InteropTests.cs#L486) that timed out (since `_sendStarted` must already have been completed during the previous send).  Nothing in the test appears to make `Kestrel` apply back-pressure - it should either close the connection as intended or continue to accept `DATA` frames.  Without a detailed knowledge of `HttpContent`, it's not clear to me why it might block.

Given that `HttpClient` has likely changed since this issue was filed, my vote would be to unquarantine it.

**Comment by eerhardt** [comment]
This test failed again here https://dev.azure.com/dnceng-public/public/_build/results?buildId=815316&view=ms.vss-test-web.build-test-results-tab&runId=21135106&resultId=124255&paneView=debug. Re-opening issue. If it fails again we should re-quarantine the tests.

**Comment by amcasey** [comment]
```
Interop.FunctionalTests.HttpClientHttp2InteropTests.ServerReset_BeforeRequestBody_ClientBodyThrows(scheme: "http") [FAIL]
  Assert.Throws() Failure: Exception type was not an exact match
  Expected: typeof(System.Net.Http.HttpProtocolException)
  Actual:   typeof(System.TimeoutException)
  ---- System.TimeoutException : The operation has timed out.
  Stack Trace:
    /_/src/Servers/Kestrel/test/Interop.FunctionalTests/HttpClientHttp2InteropTests.cs(742,0): at Interop.FunctionalTests.HttpClientHttp2InteropTests.ServerReset_BeforeRequestBody_ClientBodyThrows(String scheme)
    --- End of stack trace from previous location ---
    ----- Inner Stack Trace -----
    /_/src/Shared/TaskExtensions.cs(123,0): at Microsoft.AspNetCore.InternalTesting.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber)
  Output:
    | [0.001s] TestLifetime Information: Starting test ServerReset_BeforeRequestBody_ClientBodyThrows-http at 2024-09-23T02:22:38
    | [0.004s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting starting
    | [0.007s] Microsoft.Hosting.Lifetime Information: Now listening on: http://127.0.0.1:54392
    | [0.007s] Microsoft.AspNetCore.Hosting.Diagnostics Debug: Loaded hosting startup assembly Interop.FunctionalTests
    | [0.007s] Microsoft.Hosting.Lifetime Information: Application started. Press Ctrl+C to shut down.
    | [0.007s] Microsoft.Hosting.Lifetime Information: Hosting environment: Production
    | [0.007s] Microsoft.Hosting.Lifetime Information: Content root path: /private/tmp/helix/working/A813092B/w/9CF1089E/e/
    | [0.007s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting started
    | [0.009s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HN6REQAUQU4D" accepted.
    | [0.009s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HN6REQAUQU4D" started.
    | [0.009s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HN6REQAUQU4D" sending SETTINGS frame for stream ID 0 with length 24 and flags NONE.
    | [0.009s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HN6REQAUQU4D" sending WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0.
    | [0.009s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HN6REQAUQU4D" received SETTINGS frame for stream ID 0 with length 12 and flags NONE.
    | [0.009s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HN6REQAUQU4D" sending SETTINGS frame for stream ID 0 with length 0 and flags ACK.
    | [0.009s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HN6REQAUQU4D" received WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0.
    | [0.010s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HN6REQAUQU4D" received HEADERS frame for stream ID 1 with length 35 and flags END_HEADERS.
    | [0.010s] Microsoft.AspNetCore.Hosting.Diagnostics Information: Request starting HTTP/2 POST http://127.0.0.1:54392/ - - -
    | [0.011s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HN6REQAUQU4D" sending HEADERS frame for stream ID 1 with length 53 and flags END_HEADERS.
    | [0.011s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HN6REQAUQU4D" received SETTINGS frame for stream ID 0 with length 0 and flags ACK.
    | [0.012s] Microsoft.AspNetCore.Server.Kestrel.Http2 Debug: Trace id "0HN6REQAUQU4D:00000001": HTTP/2 stream error "CANCEL". A Reset is being sent to the stream.
    | Microsoft.AspNetCore.Connections.ConnectionAbortedException: The HTTP/2 stream was reset by the application with error code CANCEL.
    | [0.013s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HN6REQAUQU4D" sending RST_STREAM frame for stream ID 1 with length 4 and flags 0x0.
    | [0.013s] Microsoft.AspNetCore.Hosting.Diagnostics Information: Request finished HTTP/2 POST http://127.0.0.1:54392/ - 200 - text/plain 3.3156ms
    | [0.013s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HN6REQAUQU4D" received PING frame for stream ID 0 with length 8 and flags NONE.
    | [0.013s] Microsoft.AspNetCore.Server.Kestrel Information: Connection id "0HN6REQAUQU4D", Request id "0HN6REQAUQU4D:00000001": the application completed without reading the entire request body.
    | [0.013s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HN6REQAUQU4D" sending PING frame for stream ID 0 with length 8 and flags ACK.
    | [30.067s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HN6REQAUQU4D" received FIN.
    | [30.068s] Microsoft.AspNetCore.Server.Kestrel.Http2 Debug: Connection id "0HN6REQAUQU4D" is closed. The last processed stream ID was 1.
    | [30.068s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Some connections failed to close gracefully during server shutdown.
    | [30.068s] Microsoft.AspNetCore.Server.Kestrel.Http2 Debug: The connection queue processing loop for 0HN6REQAUQU4D completed.
    | [30.068s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HN6REQAUQU4D" sending RST because: "The connection was aborted because the server is shutting down and request processing didn't complete within the time specified by HostOptions.ShutdownTimeout."
    | [30.068s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HN6REQAUQU4D" stopped.
    | [30.069s] Interop.FunctionalTests.HttpClientHttp2InteropTests Error: Test threw an exception.
    | Xunit.Sdk.ThrowsException: Assert.Throws() Failure: Exception type was not an exact match
    | Expected: typeof(System.Net.Http.HttpProtocolException)
    | Actual:   typeof(System.TimeoutException)
    |    at Xunit.Assert.Throws(Type exceptionType, Exception exception) in /_/src/xunit.assert/Asserts/ExceptionAsserts.cs:line 37
    |    at Xunit.Assert.ThrowsAsync[T](Func`1 testCode) in /_/src/xunit.assert/Asserts/ExceptionAsserts.cs:line 264
    |    at Interop.FunctionalTests.HttpClientHttp2InteropTests.ServerReset_BeforeRequestBody_ClientBodyThrows(String scheme) in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/HttpClientHttp2InteropTests.cs:line 742
    |    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 253
    | --- End of stack trace from previous location ---
    |    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
    |    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
    | [30.071s] TestLifetime Information: Finished test ServerReset_BeforeRequestBody_ClientBodyThrows-http in 30.0707864s
```
