### ISSUE TITLE
ObjectDisposedException thrown on server shutdown due to disposed MemoryCache

### ISSUE THREAD

**Issue by ohads-MSFT** [dotnet/aspnetcore#46779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When shutting down our ASP.NET Core server (HTTP 1), the following exception is thrown on in-flight requests:
```cs
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Microsoft.Extensions.Caching.Memory.MemoryCache'.
   at Microsoft.Extensions.Caching.Memory.MemoryCache.<CheckDisposed>g__Throw|41_0()
   at Microsoft.Extensions.Caching.Memory.MemoryCache.TryGetValue(Object key, Object& result)
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreate[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at Microsoft.Azure.XXX.Caching.MemoryCacheExtensions.GetOrCreateLazyAsync[T](IMemoryCache memoryCache, Object key, Func`1 factory, Action`1 entryModifier)
--- End of stack trace from previous location ---
   at Microsoft.Azure.XXX.Hosting.TraceResponseMiddleware.Invoke(HttpContext context) 
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

I'm not overly familiar with the graceful shutdown flow, but from what I saw it boils down to: https://github.com/dotnet/aspnetcore/blob/8d61cc4c3e77fd3d0dc7416b212c513174c4706b/src/Servers/Kestrel/Core/src/Internal/Http/Http1Connection.cs#L128

Which going by its code and docs comment only `Stops the request processing loop between requests`, emphasis on _between_. As far as I can tell, there is no effect on requests _currently_ being processed by the application code (which would explain how application controllers/middleware try and use disposed DI objects): https://github.com/dotnet/aspnetcore/blob/8d61cc4c3e77fd3d0dc7416b212c513174c4706b/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs#L675

Worse, I believe the shutdown procedure also terminates the underlying TCP connections for in-flight request, as our app gateway proxy reported `upstream prematurely closed connection` for that request (which would not have come from the Kestrel keepalive timeout as the request hasn't been processed for that long). 

To further support this theory, we have an app insights event 5 seconds after said socket close was observed by the gateway, claiming a 200 OK status code was returned. Indeed, I believe that is what Kestrel would have returned, had proper draining been performed (retaining the underlying TCP connection).

### Expected Behavior

Connection draining waits for in-flight requests to finish before disposing the DI objects.

### Steps To Reproduce

Shut down ASP.NET core server while a long-running controller action processes a request and tries to use some DI object at the end.

### Exceptions (if any)

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Microsoft.Extensions.Caching.Memory.MemoryCache'.

### .NET Version

7.0.102

### Anything else?

Similar to https://github.com/dotnet/aspnetcore/issues/3089

**Comment by Tratcher** [comment]
Can you collect logs with timestamps? 

> ### Expected Behavior
> Connection draining waits for in-flight requests to finish before disposing the DI objects.

It does wait, but only for so long. There's a shutdown timeout to prevent hangs. When that timeout expires it will abortively close the connection and dispose the DI container.
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-7.0#shutdowntimeout

**Comment by ohads-MSFT** [comment]
@Tratcher 

1. Sorry I should have specified, we set `SHUTDOWNTIMEOUTSECONDS` to 120 seconds and the request took less than 70 so I don't think that was it. Out of curiosity though, are you saying that the behavior we we countered (disposed mem cache + aborted TCP connection + wrong reported request telemetry) would be expected if this timeout was the culprit?
2. What logs would you like exactly? I would happily show you all the logs we have if you'd like to ping me on Teams (I'm ohads@microsoft.com).
3. Would you mind linking to the code that waits for ongoing requests? I followed `ShutdownTimeout` through `KestrelServer::StopAsync` -> `KestrelServerImpl` -> `TransportManager` -> `TransportConnectionManager` -> `ConnectionReference` -> `KestrelConnection::ConnectionClosedRequested` -> `HttpConnection::StopProcessingNextRequest` -> `StopProcessingNextRequest::StopProcessingNextRequest` which is the method I mentioned above which only seems to stop _future_ requests. Where are you waiting for the ongoing ones?

**Comment by Tratcher** [comment]
https://github.com/dotnet/aspnetcore/blob/bec278eabea54f63da15e10e654bdfa4168a2479/src/Servers/Kestrel/Core/src/Internal/Infrastructure/TransportConnectionManager.cs#L63-L69

RequestClose triggers a graceful close on each connection, then it waits for each connection to finish. If the timeout expires then it stops waiting and aborts them.

**Comment by Tratcher** [comment]
> Out of curiosity though, are you saying that the behavior we we countered (disposed mem cache + aborted TCP connection + wrong reported request telemetry) would be expected if this timeout was the culprit?

Yes, this could happen with an abortive shutdown after the timeout.

Discussing log collection offline.
