### ISSUE TITLE
Quarantine CanUseFocusExtensionToFocusElementPreventScroll

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#46835]
## Failing Test(s)

Microsoft.AspNetCore.Components.E2ETest.Tests.ComponentRenderingTestBase.CanUseFocusExtensionToFocusElementPreventScroll

## Error Message

```text
Assert.Equal() Failure
Expected: 72
Actual:   0
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.Components.E2ETest.Tests.ComponentRenderingTestBase.CanUseFocusExtensionToFocusElementPreventScroll() in /home/vsts/work/1/s/src/Components/test/E2ETest/Tests/ComponentRenderingTestBase.cs:line 454
   at InvokeStub_ComponentRenderingTestBase.CanUseFocusExtensionToFocusElementPreventScroll(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=181947

**Comment by SteveSandersonMS** [comment]
Test fixed in https://github.com/dotnet/aspnetcore/pull/54343

**Comment by sebastienros** [comment]
Passing since un-quarantined.
