### ISSUE TITLE
PlatformNotSupported exceptions in WindowsARM infrastructure for release/6.0

### ISSUE THREAD

**Issue by mkArtakMSFT** [dotnet/aspnetcore#46941]
These errors cause more issues down the road in Helix test runs for release/6.0 branch. For more details see: https://dev.azure.com/dnceng-public/public/_build/results?buildId=187657&view=ms.vss-test-web.build-test-results-tab&runId=3604263&resultId=120253&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab

```log
2023-02-28T09:54:48.4281273Z  | System.PlatformNotSupportedException: EventLog access is not supported on this platform.
2023-02-28T09:54:48.4281453Z  |    at System.Diagnostics.EventLog..ctor(String logName, String machineName, String source)
2023-02-28T09:54:48.4281523Z  |    at Microsoft.Extensions.Logging.EventLog.WindowsEventLog..ctor(String logName, String machineName, String sourceName)
2023-02-28T09:54:48.4281704Z  |    at Microsoft.Extensions.Logging.EventLog.EventLogSettings.CreateDefaultEventLog()
2023-02-28T09:54:48.4281771Z  |    at Microsoft.Extensions.Logging.EventLog.EventLogSettings.get_EventLog()
2023-02-28T09:54:48.4281815Z  |    at Microsoft.Extensions.Logging.EventLog.EventLogLogger..ctor(String name, EventLogSettings settings, IExternalScopeProvider externalScopeProvider)
2023-02-28T09:54:48.4282067Z  |    at Microsoft.Extensions.Logging.EventLog.EventLogLoggerProvider.CreateLogger(String name)
2023-02-28T09:54:48.4282137Z  |    at Microsoft.Extensions.Logging.LoggerFactory.CreateLoggers(String categoryName)
2023-02-28T09:54:48.4282184Z  |    at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
2023-02-28T09:54:48.4282368Z  |    at Microsoft.Extensions.Logging.Logger`1..ctor(ILoggerFactory factory)
2023-02-28T09:54:48.4282438Z  |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
2023-02-28T09:54:48.4282626Z  |    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2023-02-28T09:54:48.4282844Z  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2023-02-28T09:54:48.4283723Z  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2023-02-28T09:54:48.4283984Z  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
2023-02-28T09:54:48.4284075Z  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2023-02-28T09:54:48.4284273Z  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2023-02-28T09:54:48.4284591Z  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2023-02-28T09:54:48.4284665Z  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
2023-02-28T09:54:48.4284862Z  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2023-02-28T09:54:48.4284933Z  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
2023-02-28T09:54:48.4285122Z  |    at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
2023-02-28T09:54:48.4285202Z  |    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
2023-02-28T09:54:48.4285384Z  |    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
2023-02-28T09:54:48.4285453Z  |    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
2023-02-28T09:54:48.4285634Z  |    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
2023-02-28T09:54:48.4285702Z  |    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
2023-02-28T09:54:48.4286004Z  |    at Microsoft.Extensions.Hosting.HostBuilder.<CreateServiceProvider>b__28_2(IServiceProvider _)
2023-02-28T09:54:48.4286073Z  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
2023-02-28T09:54:48.4286257Z  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2023-02-28T09:54:48.4286475Z  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
2023-02-28T09:54:48.4286546Z  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2023-02-28T09:54:48.4286738Z  |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
2023-02-28T09:54:48.4286810Z  |    at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
2023-02-28T09:54:48.4286997Z  |    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
2023-02-28T09:54:48.4287066Z  |    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
2023-02-28T09:54:48.4287350Z  |    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
2023-02-28T09:54:48.4287459Z  |    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
2023-02-28T09:54:48.4287655Z  |    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
2023-02-28T09:54:48.4287725Z  |    at Microsoft.Extensions.Hosting.HostBuilder.Build()
2023-02-28T09:54:48.4287770Z  |    at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
2023-02-28T09:54:48.4287953Z  |    at AspNetCore.Ogrwgduu3god.Program.Main(String[] args) in C:\h\w\AF430994\w\B61409EA\e\Templates\BaseFolder\AspNetCore.Ogrwgduu3god\Program.cs:line 23
2023-02-28T09:54:48.4288033Z  | --- End of stack trace from previous location ---
2023-02-28T09:54:48.4288079Z  |    at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.CreateHost()
2023-02-28T09:54:48.4288257Z  |    at Microsoft.Extensions.Hosting.HostFactoryResolver.<>c__DisplayClass10_0.<ResolveHostFactory>b__0(String[] args)
2023-02-28T09:54:48.4288324Z  |    at Microsoft.Extensions.Hosting.HostFactoryResolver.<>c__DisplayClass13_0.<ResolveServiceProviderFactory>b__3(String[] args)
2023-02-28T09:54:48.4288513Z  |    at Microsoft.EntityFrameworkCore.Design.Internal.AppServiceProviderFactory.CreateFromHosting(String[] args)
2023-02-28T09:54:48.4288582Z  | An error occurred while accessing the Microsoft.Extensions.Hosting services. Continuing without the application service provider. Error: EventLog access is not supported on this platform.
2023-02-28T09:54:48.4288899Z  | No application service provider was found.
```

**Comment by mkArtakMSFT** [comment]
@jeffhandley do you know if these exceptions are expected on ARM on 6.0 and whether that's going to change soon?
/cc @maryamariyan in case you have any suggestions while @jeffhandley is out.

**Comment by wtgodbe** [comment]
@jeffhandley have you had a chance to take a look at this?

**Comment by jeffhandley** [comment]
Sorry, I hadn't; I just now reached this notification but can't investigate myself. @buyaa-n or @carlossanlop -- could one of you take a look at this please?

**Comment by buyaa-n** [comment]
Was it working before? From [project setting](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.EventLog/src/System.Diagnostics.EventLog.csproj#L16-L17) It seems only supported on .NET framework and windows: 
```xml
<PropertyGroup>
    <TargetPlatformIdentifier>$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)'))</TargetPlatformIdentifier>
    <IsPartialFacadeAssembly Condition="$([MSBuild]::GetTargetFrameworkIdentifier('$(TargetFramework)')) == '.NETFramework'">true</IsPartialFacadeAssembly>
    <GeneratePlatformNotSupportedAssemblyMessage Condition="'$(IsPartialFacadeAssembly)' != 'true' and '$(TargetPlatformIdentifier)' != 'windows'">SR.PlatformNotSupported_EventLog</GeneratePlatformNotSupportedAssemblyMessage>
  </PropertyGroup>
```
CC @dotnet/area-system-diagnostics-eventlog

**Comment by buyaa-n** [comment]
According to the [build properties](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.EventLog/Directory.Build.props#L4) the assembly must have attributed as Windows only

**Comment by wtgodbe** [comment]
I'm not sure I understand, the failing tests _are_ running on windows (but the failures only happen on arm)

**Comment by buyaa-n** [comment]
Ah sorry, the constructor not throwing any PNSE, it should have caused from this project settings, so I thought it was running on different platform, anyway I tagged the area owners above, maybe we should move to runtime
