### ISSUE TITLE
Official builds failing due to binlog2sln issue

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#46942]
> Processing binlog D:\a\_work\1\s/artifacts/log/Release/Build.binlog into solution at directory D:\a\_work\1\a/sourceIndex/
Unhandled exception. System.NotSupportedException: Unsupported log file format. Latest supported version is 15, the log file has version 16.
   at Microsoft.Build.Logging.StructuredLogger.BinLogReader.Replay(Stream stream, Progress progress) in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BinLogReader.cs:line 74
   at Microsoft.Build.Logging.StructuredLogger.BinLogReader.Replay(String sourceFilePath, Progress progress) in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BinLogReader.cs:line 50
   at Microsoft.Build.Logging.StructuredLogger.BinLogReader.Replay(String sourceFilePath) in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BinLogReader.cs:line 39
   at Microsoft.SourceBrowser.BinLogParser.BinLogCompilerInvocationsReader.<>c__DisplayClass1_0.<ExtractInvocations>b__0() in D:\a\_work\1\s\src\SourceBrowser\src\BinLogParser\BinLogReader.cs:line 58
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.SourceBrowser.BinLogParser.BinLogCompilerInvocationsReader.ExtractInvocations(String binLogFilePath) in D:\a\_work\1\s\src\SourceBrowser\src\BinLogParser\BinLogReader.cs:line 63
   at BinLogToSln.Program.Main(String[] args) in D:\a\_work\1\s\src\SourceBrowser\src\BinLogToSln\Program.cs:line 77

https://dev.azure.com/dnceng/internal/_build/results?buildId=2124485&view=logs&j=366a1024-3a8a-5d08-6c00-a4b17dce0d38&t=238871f9-7ef2-5729-2537-1315178305fb&l=16

**Comment by wtgodbe** [comment]
Need a change like https://github.com/dotnet/aspnetcore/pull/45982 after sourcelink gets updated

**Comment by wtgodbe** [comment]
Will be fixed by https://github.com/dotnet/aspnetcore/pull/46946
