### ISSUE TITLE
ASP.Net Core 7 startup on Windows 11 Failed to authenticate HTTPS connection

### ISSUE THREAD

**Issue by khteh** [dotnet/aspnetcore#47046]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Kestrel reads from `.pfx` file which is generated using openssl on Ubuntu 22.10. No problem running the application on Ubuntu with the SAME cert.

### Exceptions (if any)

```
System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x8009030D): The credentials supplied to the package were not recognized
   at System.Net.SSPIWrapper.AcquireCredentialsHandle(ISSPIInterface secModule, String package, CredentialUse intent, SCH_CREDENTIALS* scc)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCH_CREDENTIALS* secureCredential)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandleSchCredentials(SslAuthenticationOptions authOptions)
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.AcquireCredentialsHandle(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.AcquireServerCredentials(Byte[]& thumbPrint)
   at System.Net.Security.SslStream.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)
   at System.Net.Security.SslStream.NextMessage(ReadOnlySpan`1 incomingBuffer)
   at System.Net.Security.SslStream.ProcessBlob(Int32 frameSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context)
{"@timestamp":"2023-03-06T17:35:55.5567570+08:00","level":"Debug","messageTemplate":"Failed to authenticate HTTPS connection.","message":"Failed to authenticate HTTPS connection.","exceptions":[{"Depth":0,"ClassName":"System.Security.Authentication.AuthenticationException","Message":"Authentication failed, see inner exception.","Source":"System.Net.Security","StackTraceString":"   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslAuthenticationOptions sslAuthenticationOptions)\r\n   at System.Net.Security.SslStream.AcquireCredentialsHandle(SslAuthenticationOptions sslAuthenticationOptions)\r\n   at System.Net.Security.SslStream.AcquireServerCredentials(Byte[]& thumbPrint)\r\n   at System.Net.Security.SslStream.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)\r\n   at System.Net.Security.SslStream.NextMessage(ReadOnlySpan`1 incomingBuffer)\r\n   at System.Net.Security.SslStream.ProcessBlob(Int32 frameSize)\r\n   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](CancellationToken cancellationToken)\r\n   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)\r\n   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context)","RemoteStackTraceString":null,"RemoteStackIndex":0,"HResult":-2146233087,"HelpURL":null},{"Depth":1,"ClassName":"System.ComponentModel.Win32Exception","Message":"The credentials supplied to the package were not recognized","Source":"System.Net.Security","StackTraceString":"   at System.Net.SSPIWrapper.AcquireCredentialsHandle(ISSPIInterface secModule, String package, CredentialUse intent, SCH_CREDENTIALS* scc)\r\n   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCH_CREDENTIALS* secureCredential)\r\n   at System.Net.Security.SslStreamPal.AcquireCredentialsHandleSchCredentials(SslAuthenticationOptions authOptions)\r\n   at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslAuthenticationOptions sslAuthenticationOptions)","RemoteStackTraceString":null,"RemoteStackIndex":0,"HResult":-2147467259,"HelpURL":null}],"fields":{"EventId":{"Id":1,"Name":"AuthenticationFailed"},"SourceContext":"Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware","ConnectionId":"0HMOU4OJN0ES5"}}
```

### .NET Version

7.0.201

**Comment by adityamandaleeka** [comment]
Can you share your code and how you're running your server?

Your error message indicates that there was something wrong with the certs/credentials configured (is the private key accessible?). Can't say much more without more info.

**Comment by khteh** [comment]
![image](https://user-images.githubusercontent.com/3871483/223285809-ae00e8a5-834a-4854-afa7-5ade18106bc1.png)


https://github.com/khteh/AspNetCoreWebApi

**Comment by adityamandaleeka** [comment]
@khteh That project is quite large... we typically look for something minimal that includes just the code needed to reproduce the problem.

If you create a new project (e.g. `dotnet new webapp`) and try to bind to your cert, do you hit the same issue?

**Comment by khteh** [comment]
Why don't you create that and shows us how to start an ASP.Net Core 7 web application with openssl TLS cert? Where is the documentation for that!?!

**Comment by adityamandaleeka** [comment]
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-7.0#bind-to-a-tcp-socket

**Comment by khteh** [comment]
How would that be different from
```
    "Kestrel": {
        "EndpointDefaults": {
            "Protocols": "Http1AndHttp2AndHttp3"
        },
        "Endpoints": {
            "Https": {
                "Url": "https://*",
                "Protocols": "Http1AndHttp2AndHttp3",
                "Certificate": {
                    "Path": "/tmp/localhost.pfx",
                    "Password": "AspNetCoreWebApi"
                }
            }
        },
        "Certificates": {
            "Default": {
                "Path": "/tmp/localhost.pfx",
                "Password": "AspNetCoreWebApi"
            }
        }
    },
```
?

**Comment by amcasey** [comment]
@khteh There are a number of ways to generate certificates with OpenSSL.  Can you share the commands you're using?

**Comment by khteh** [comment]
```
openssl genrsa -aes256 -passout pass:<password> -out server.key 4096
openssl rsa -in server.key -out server.key.insecure -passin pass:<password>
mv server.key server.key.secure
mv server.key.insecure server.key
openssl req -new -newkey rsa:4096 -x509 -nodes -days 365 -keyout server.key -out server.crt -subj "/C=SG/ST=Singapore/L=Singapore /O=My Company Pte. Ltd./OU=My Organization/CN=localhost/emailAddress=<email>" -passin pass:<password>
openssl pkcs12 -export -out /tmp/localhost.pfx -inkey server.key -in server.crt -certfile server.crt -passout pass:<password>
```

**Comment by amcasey** [comment]
@khteh I think I must be missing something silly, but I'm having trouble following that sequence of commands.

1. Create a new RSA key in `server.key` with password PASS1
2. Create a passwordless copy of the same key in `server.key.insecure`
3. Rename the password-protected key to `server.key.secure`
4. Rename the passwordless key to `server.key`
5. Create a new x509 cert in `server.crt` and clobber the passwordless key in `server.key` with a new key generated for the cert
6. Bundle the key and cert from the preceding step into a pkcs12 file with password PASS2

It seems like the first four steps can be ignored since their outputs aren't consumed - what am I missing?

**Comment by amcasey** [comment]
Also, why include `-certfile` in the last command?  Won't that cause the cert to be included a second time (since it's already passed as `-in`)?

**Comment by khteh** [comment]
I used the first four lines to generate a passwordless TLS cert and the last line (6) to generate a `.pfx` which is only used by ASP.Net Core applications. Not sure why I used both `-in` and `-certfile` but I have been using these commands for a while without reviewing it....

**Comment by amcasey** [comment]
Where is the passwordless TLS cert (RSA key?) used?

**Comment by khteh** [comment]
Not sure about it. I think this is a transitive output....

**Comment by khteh** [comment]
Only 5 and 6 are used.

**Comment by amcasey** [comment]
Thanks for confirming - that makes more sense.

So, a reduced repro would be:
```
openssl req -new -newkey rsa:4096 -x509 -nodes -days 365 -keyout server.key -out server.crt -subj "/C=SG/ST=Singapore/L=Singapore /O=My Company Pte. Ltd./OU=My Organization/CN=localhost/emailAddress=a@b.c"
openssl pkcs12 -export -out twocerts.pfx -inkey server.key -in server.crt -certfile server.crt -passout pass:mypass
openssl pkcs12 -export -out onecert.pfx -inkey server.key -in server.crt -passout pass:mypass
```

And then create a dummy web app project and add
```csharp
builder.WebHost.ConfigureKestrel(serverOptions =>
{
    serverOptions.ListenLocalhost(443, listenOptions =>
    {
        //listenOptions.UseHttps(@"PathTo\onecert.pfx", "mypass"); // Works
        listenOptions.UseHttps(@"PathTo\twocerts.pfx", "mypass"); // Doesn't work
    });
});
```

I was able to create the pfx files on Windows - exporting them from Ubuntu doesn't seem important to the repro.

**Comment by amcasey** [comment]
@khteh We'll investigate why it's not working with `-certfile`, but is leaving that out a viable workaround for your scenario?

**Comment by khteh** [comment]
How do you run `openssl` commands in Windows 11? I regenerate `localhost.pfx` in Ubuntu leaving `-certfile` out and copy it over to my dual-booted Windows 11 and try it out and hit the following exception:
![image](https://user-images.githubusercontent.com/3871483/229267645-84ce2510-1071-4c3c-825a-6eaa73b9b06e.png)

**Comment by amcasey** [comment]
> How do you run openssl commands in Windows 11?

Looks like I'm running the copy that came with git.

> hit the following exception

Unfortunately, that's just `E_FAIL`, which provides no diagnostic information.  I did test it out locally before suggesting it, but we might be on different versions of openssl or something.  Which version are you using?

**Comment by khteh** [comment]
Actually there is a bunch of these similar "exception"s which are not fatal. I keep pressing F5 and the application runs at the end of it.

`OpenSSL 3.0.5 5 Jul 2022 (Library: OpenSSL 3.0.5 5 Jul 2022)`

**Comment by amcasey** [comment]
Ah, I think I'm on an older OpenSSL - I'll confirm with v3.

Non-fatal exceptions aren't great, but it sounds like you're unblocked?

**Comment by khteh** [comment]
Unblocked unless I need additional/extra (CA) cert(s)

**Comment by amcasey** [comment]
@khteh I haven't tested, but my intuition is that `-certfile` will work if it's not the same certificate, so hopefully you're unblocked in that scenario too.  Regardless, I plan to investigate.

**Comment by amcasey** [comment]
I can repro the non-blocking exception.  I'm not sure how/if I missed that on my first pass, but I now see it with both openssl 1 and openssl 3.

**Comment by amcasey** [comment]
I haven't been able to find any interesting differences between openssl v1 and v3 pfx files, at least with these simple contents.

**Comment by khteh** [comment]
Maybe TLS1.3-specific diff?

**Comment by amcasey** [comment]
> Maybe TLS1.3-specific diff?

Could be, but my guess is that schannel and openssl are slightly incompatible.  I'm trying to confirm by looking for a repro that doesn't use AspNetCore.

**Comment by amcasey** [comment]
Here's a toy program that repros the issue without AspNetCore

```csharp
using System.Net;
using System.Net.Security;
using System.Net.Sockets;
using System.Security.Cryptography.X509Certificates;

TcpListener listener = new TcpListener(IPAddress.Any, 5000);
listener.Start();

TcpClient client = listener.AcceptTcpClient();

SslStream sslStream = new SslStream(client.GetStream(), false);
var serverCertificate = new X509Certificate2(@"twocerts.pfx", "mypass");
sslStream.AuthenticateAsServer(serverCertificate, clientCertificateRequired: false, checkCertificateRevocation: true);
```

If you connect to https://localhost:5000 in a browser, it will throw the following exceptions with onecert.pfx and twocerts.pfx, respectively:

```
Win32Exception (0x8009030D): The credentials supplied to the package were not recognized
```
```
Win32Exception (0x80090327): An unknown error occurred while processing the certificate.
```

I don't believe it matters whether the certs are from OpenSSL 1.1 or 3.0 or whether they are produce on Windows or Ubuntu.
