### ISSUE TITLE
Multiple Kestrel Libuv tests failing in 6.0 on win-arm64

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#47078]
## Failing Test(s)

Many tests in `Microsoft.AspNetCore.Server.Kestrel.Libuv.FunctionalTests`

-

## Error Message

```text
System.DllNotFoundException : Unable to load DLL 'libuv' or one of its dependencies: The specified module could not be found. (0x8007007E)
```

## Stacktrace

<details>

```text
2023-03-07T09:36:46.5131130Z   Failed Microsoft.AspNetCore.Server.Kestrel.Libuv.FunctionalTests.RequestTests.RequestsCanBeAbortedMidRead(listenOptionsName: "PassThrough") [2 s]
2023-03-07T09:36:46.5132130Z   Error Message:
2023-03-07T09:36:46.5133356Z    System.DllNotFoundException : Unable to load DLL 'libuv' or one of its dependencies: The specified module could not be found. (0x8007007E)
2023-03-07T09:36:46.5134358Z   Stack Trace:
2023-03-07T09:36:46.5135520Z      at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.NativeMethods.uv_loop_size()
2023-03-07T09:36:46.5135796Z    at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.loop_size() in /_/src/Servers/Kestrel/Transport.Libuv/src/Internal/Networking/LibuvFunctions.cs:line 339
2023-03-07T09:36:46.5136044Z    at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvLoopHandle.Init(LibuvFunctions uv) in /_/src/Servers/Kestrel/Transport.Libuv/src/Internal/Networking/UvLoopHandle.cs:line 17
2023-03-07T09:36:46.5136125Z    at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvThread.ThreadStart(Object parameter) in /_/src/Servers/Kestrel/Transport.Libuv/src/Internal/LibuvThread.cs:line 288
2023-03-07T09:36:46.5136331Z --- End of stack trace from previous location ---
2023-03-07T09:36:46.5136408Z    at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvConnectionListener.BindAsync() in /_/src/Servers/Kestrel/Transport.Libuv/src/Internal/LibuvConnectionListener.cs:line 146
2023-03-07T09:36:46.5136647Z    at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Transport.Libuv/src/Internal/LibuvTransportFactory.cs:line 81
2023-03-07T09:36:46.5136932Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/Infrastructure/TransportManager.cs:line 42
2023-03-07T09:36:46.5137203Z    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass30_0`1.<<StartAsync>g__OnBind|0>d.MoveNext() in /_/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs:line 220
2023-03-07T09:36:46.5137281Z --- End of stack trace from previous location ---
2023-03-07T09:36:46.5137491Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/AddressBinder.cs:line 94
2023-03-07T09:36:46.5137837Z    at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/ListenOptions.cs:line 195
2023-03-07T09:36:46.5138081Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/AddressBinder.cs:line 225
2023-03-07T09:36:46.5138369Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/AddressBinder.cs:line 36
2023-03-07T09:36:46.5138651Z    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs:line 317
2023-03-07T09:36:46.5138912Z    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs:line 237
2023-03-07T09:36:46.5139031Z    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Hosting/Hosting/src/GenericHost/GenericWebHostedService.cs:line 123
2023-03-07T09:36:46.5139232Z    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
2023-03-07T09:36:46.5139310Z    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Start(IHost host)
2023-03-07T09:36:46.5139526Z    at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.TestServer..ctor(RequestDelegate app, TestServiceContext context, Action`1 configureKestrel, Action`1 configureServices) in /_/src/Servers/Kestrel/shared/test/TransportTestHelpers/TestServer.cs:line 114
2023-03-07T09:36:46.5139824Z    at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.TestServer..ctor(RequestDelegate app, TestServiceContext context, ListenOptions listenOptions) in /_/src/Servers/Kestrel/shared/test/TransportTestHelpers/TestServer.cs:line 47
2023-03-07T09:36:46.5140097Z    at Microsoft.AspNetCore.Server.Kestrel.Libuv.FunctionalTests.RequestTests.RequestsCanBeAbortedMidRead(String listenOptionsName) in /_/src/Servers/Kestrel/test/FunctionalTests/RequestTests.cs:line 656
2023-03-07T09:36:46.5140354Z --- End of stack trace from previous location ---
2023-03-07T09:36:46.5142420Z   Standard Output Messages:
2023-03-07T09:36:46.5143783Z  | [0.002s] TestLifetime Information: Starting test RequestsCanBeAbortedMidRead-PassThrough at 2023-03-07T09:36:43
2023-03-07T09:36:46.5143901Z  | [0.007s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting starting
2023-03-07T09:36:46.5144135Z  | [2.135s] Microsoft.AspNetCore.Server.Kestrel.Libuv.FunctionalTests.RequestTests Error: Test threw an exception.
2023-03-07T09:36:46.5144214Z  | System.DllNotFoundException: Unable to load DLL 'libuv' or one of its dependencies: The specified module could not be found. (0x8007007E)
2023-03-07T09:36:46.5144423Z  |    at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.NativeMethods.uv_loop_size()
2023-03-07T09:36:46.5144687Z  |    at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.LibuvFunctions.loop_size() in /_/src/Servers/Kestrel/Transport.Libuv/src/Internal/Networking/LibuvFunctions.cs:line 339
2023-03-07T09:36:46.5144773Z  |    at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvLoopHandle.Init(LibuvFunctions uv) in /_/src/Servers/Kestrel/Transport.Libuv/src/Internal/Networking/UvLoopHandle.cs:line 17
2023-03-07T09:36:46.5145006Z  |    at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvThread.ThreadStart(Object parameter) in /_/src/Servers/Kestrel/Transport.Libuv/src/Internal/LibuvThread.cs:line 288
2023-03-07T09:36:46.5145147Z  | --- End of stack trace from previous location ---
2023-03-07T09:36:46.5145356Z  |    at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvConnectionListener.BindAsync() in /_/src/Servers/Kestrel/Transport.Libuv/src/Internal/LibuvConnectionListener.cs:line 146
2023-03-07T09:36:46.5145594Z  |    at Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Transport.Libuv/src/Internal/LibuvTransportFactory.cs:line 81
2023-03-07T09:36:46.5145868Z  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/Infrastructure/TransportManager.cs:line 42
2023-03-07T09:36:46.5146151Z  |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass30_0`1.<<StartAsync>g__OnBind|0>d.MoveNext() in /_/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs:line 220
2023-03-07T09:36:46.5146249Z  | --- End of stack trace from previous location ---
2023-03-07T09:36:46.5146462Z  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/AddressBinder.cs:line 94
2023-03-07T09:36:46.5146750Z  |    at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/ListenOptions.cs:line 195
2023-03-07T09:36:46.5146994Z  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/AddressBinder.cs:line 225
2023-03-07T09:36:46.5147266Z  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/AddressBinder.cs:line 36
2023-03-07T09:36:46.5147540Z  |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs:line 317
2023-03-07T09:36:46.5147786Z  |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs:line 237
2023-03-07T09:36:46.5147922Z  |    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken) in /_/src/Hosting/Hosting/src/GenericHost/GenericWebHostedService.cs:line 123
2023-03-07T09:36:46.5148122Z  |    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
2023-03-07T09:36:46.5148199Z  |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Start(IHost host)
2023-03-07T09:36:46.5148425Z  |    at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.TestServer..ctor(RequestDelegate app, TestServiceContext context, Action`1 configureKestrel, Action`1 configureServices) in /_/src/Servers/Kestrel/shared/test/TransportTestHelpers/TestServer.cs:line 114
2023-03-07T09:36:46.5148696Z  |    at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.TestServer..ctor(RequestDelegate app, TestServiceContext context, ListenOptions listenOptions) in /_/src/Servers/Kestrel/shared/test/TransportTestHelpers/TestServer.cs:line 47
2023-03-07T09:36:46.5148971Z  |    at Microsoft.AspNetCore.Server.Kestrel.Libuv.FunctionalTests.RequestTests.RequestsCanBeAbortedMidRead(String listenOptionsName) in /_/src/Servers/Kestrel/test/FunctionalTests/RequestTests.cs:line 656
2023-03-07T09:36:46.5149273Z  |    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
2023-03-07T09:36:46.5149390Z  | --- End of stack trace from previous location ---
2023-03-07T09:36:46.5149457Z  |    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
2023-03-07T09:36:46.5149660Z  |    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
2023-03-07T09:36:46.5149739Z  | [2.158s] TestLifetime Information: Finished test RequestsCanBeAbortedMidRead-PassThrough in 2.1559578s
```
</details>

## Logs

<details>

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-heads-release-60-55e11efaacd44482bf/Libuv.FunctionalTests--net6.0/1/console.ce03dcb5.log?helixlogtype=result
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=195651&view=ms.vss-test-web.build-test-results-tab&runId=3700537&resultId=107141&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab

**Comment by BrennanConroy** [comment]
I don't think we ever supported libuv on arm64
https://github.com/dotnet/aspnetcore/issues/22114

**Comment by wtgodbe** [comment]
Looks like this isn't working, maybe because we're running on win11-arm64 instead of win10 now. Looking.

https://github.com/dotnet/aspnetcore/blob/3d4bd070329e7a1a99a11046d54564605fb2fe38/src/Servers/Kestrel/Transport.Libuv/test/Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Tests.csproj#L8

**Comment by wtgodbe** [comment]
https://github.com/dotnet/aspnetcore/pull/47083

**Comment by wtgodbe** [comment]
Fixed by https://github.com/dotnet/aspnetcore/pull/47083
