### ISSUE TITLE
Publishing Blazor WebAssembly With AOT results in a broken app

### ISSUE THREAD

**Issue by SQL-MisterMagoo** [dotnet/aspnetcore#47210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After publishing a Blazor WebAssembly application with AOT enabled, the application crashes in the browser on startup (whether it is autostart or manual via Blazor.start())

Error in the browser console:
`Error: [MONO] * Assertion at /__w/1/s/src/mono/mono/mini/aot-runtime.c:2443, condition <disabled> not met at se (dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3:14137)`

### Expected Behavior

I would expect the application to start without an error

### Steps To Reproduce

1. Create a new Blazor Webassembly app using dotnet 8 (preview 1 or 2 - both have this problem)
2. Publish it with AOT enabled

Sample project source: https://github.com/SQL-MisterMagoo/BlazorWASM8P2
Sample publication: https://blazorwasm8p2.azurewebsites.net/

### Exceptions (if any)

```
01:45:36.866 dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3 
        
       Error: [MONO] * Assertion at /__w/1/s/src/mono/mono/mini/aot-runtime.c:2443, condition `<disabled>' not met

    at se (dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3:14137)
    at ie (dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3:14427)
    at dotnet.wasm:0x6eb6c4
    at dotnet.wasm:0x547f94
    at dotnet.wasm:0x545d90
    at dotnet.wasm:0x545e24
    at dotnet.wasm:0x545e6b
    at dotnet.wasm:0x545e3c
    at dotnet.wasm:0x6c3ded
    at dotnet.wasm:0x6b7b2c
ie @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
$func31089 @ dotnet.wasm:0x6eb6c4
$func23128 @ dotnet.wasm:0x547f94
$func23042 @ dotnet.wasm:0x545d90
$func23045 @ dotnet.wasm:0x545e24
$func23047 @ dotnet.wasm:0x545e6b
$func23046 @ dotnet.wasm:0x545e3c
$func30463 @ dotnet.wasm:0x6c3ded
$func30302 @ dotnet.wasm:0x6b7b2c
invoke_vi @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
$func22998 @ dotnet.wasm:0x544f23
$func30301 @ dotnet.wasm:0x6b7939
$func30303 @ dotnet.wasm:0x6b82af
$func30315 @ dotnet.wasm:0x6b8a7f
$func24750 @ dotnet.wasm:0x5a63e3
$func24748 @ dotnet.wasm:0x5a6352
$func24749 @ dotnet.wasm:0x5a636c
$func24008 @ dotnet.wasm:0x57e874
$func24007 @ dotnet.wasm:0x57e744
$mono_wasm_load_runtime @ dotnet.wasm:0x6eab75
Module._mono_wasm_load_runtime @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
ccall @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
Dc @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
await in (anonymous) (async)
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
await in (anonymous) (async)
e.onRuntimeInitialized @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
doRun @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
run @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
runCaller @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
removeRunDependency @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
await in (anonymous) (async)
e.preRun @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
callRuntimeCallbacks @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
preRun @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
run @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
runCaller @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
removeRunDependency @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
await in (anonymous) (async)
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
e.instantiateWasm @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
createWasm @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
create @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
(anonymous) @ blazor.webassembly.js:1
await in (anonymous) (async)
start @ blazor.webassembly.js:1
Qt @ blazor.webassembly.js:1
await in Qt (async)
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
01:45:36.866 blazor.webassembly.js:1 
        
       MONO_WASM: mono_wasm_load_runtime () failed: {"name":"ExitStatus","message":"Program terminated with exit(1)","status":1}
Ct @ blazor.webassembly.js:1
Mc @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
Dc @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
await in (anonymous) (async)
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
await in (anonymous) (async)
e.onRuntimeInitialized @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
doRun @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
run @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
runCaller @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
removeRunDependency @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
await in (anonymous) (async)
e.preRun @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
callRuntimeCallbacks @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
preRun @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
run @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
runCaller @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
removeRunDependency @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
await in (anonymous) (async)
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
e.instantiateWasm @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
createWasm @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
create @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
(anonymous) @ blazor.webassembly.js:1
await in (anonymous) (async)
start @ blazor.webassembly.js:1
Qt @ blazor.webassembly.js:1
await in Qt (async)
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
01:45:36.872 blazor.webassembly.js:1 
        
       MONO_WASM: Error in mono_wasm_before_user_runtime_initialized: {"name":"ExitStatus","message":"Program terminated with exit(1)","status":1}
Ct @ blazor.webassembly.js:1
Mc @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
await in (anonymous) (async)
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
await in (anonymous) (async)
e.onRuntimeInitialized @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
doRun @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
run @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
runCaller @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
removeRunDependency @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
await in (anonymous) (async)
e.preRun @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
callRuntimeCallbacks @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
preRun @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
run @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
runCaller @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
removeRunDependency @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
await in (anonymous) (async)
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
e.instantiateWasm @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
createWasm @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
create @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
(anonymous) @ blazor.webassembly.js:1
await in (anonymous) (async)
start @ blazor.webassembly.js:1
Qt @ blazor.webassembly.js:1
await in Qt (async)
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
01:45:36.872 blazor.webassembly.js:1 
        
       MONO_WASM: onRuntimeInitializedAsync() failed: {"name":"ExitStatus","message":"Program terminated with exit(1)","status":1}
Ct @ blazor.webassembly.js:1
Mc @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
await in (anonymous) (async)
e.onRuntimeInitialized @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
doRun @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
run @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
runCaller @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
removeRunDependency @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
await in (anonymous) (async)
e.preRun @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
callRuntimeCallbacks @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
preRun @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
run @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
runCaller @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
removeRunDependency @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
await in (anonymous) (async)
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
e.instantiateWasm @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
createWasm @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
create @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
(anonymous) @ blazor.webassembly.js:1
await in (anonymous) (async)
start @ blazor.webassembly.js:1
Qt @ blazor.webassembly.js:1
await in Qt (async)
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
01:45:36.873 blazor.webassembly.js:1 
        
       Error: Failed to start platform. Reason: [object Object]
    at Qt (blazor.webassembly.js:1:59902)
(anonymous) @ blazor.webassembly.js:1
Promise.catch (async)
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
01:45:36.880 dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3 
        
       Uncaught (in promise) ExitStatus {name: 'ExitStatus', message: 'Program terminated with exit(1)', status: 1}
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
await in (anonymous) (async)
e.postRun @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
callRuntimeCallbacks @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
postRun @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
doRun @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
run @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
runCaller @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
removeRunDependency @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
await in (anonymous) (async)
e.preRun @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
callRuntimeCallbacks @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
preRun @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
run @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
runCaller @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
removeRunDependency @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
await in (anonymous) (async)
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
e.instantiateWasm @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
createWasm @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
create @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
(anonymous) @ blazor.webassembly.js:1
await in (anonymous) (async)
start @ blazor.webassembly.js:1
Qt @ blazor.webassembly.js:1
await in Qt (async)
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
01:45:36.880 dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3 
        
       Uncaught (in promise) ExitStatus {name: 'ExitStatus', message: 'Program terminated with exit(1)', status: 1}
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
await in (anonymous) (async)
e.onRuntimeInitialized @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
doRun @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
run @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
runCaller @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
removeRunDependency @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
await in (anonymous) (async)
e.preRun @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
callRuntimeCallbacks @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
preRun @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
run @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
runCaller @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
removeRunDependency @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
await in (anonymous) (async)
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
e.instantiateWasm @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
createWasm @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
(anonymous) @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:12
create @ dotnet.8.0.0-preview.2.23128.3.zwh3mtgt3n.js:3
(anonymous) @ blazor.webassembly.js:1
await in (anonymous) (async)
start @ blazor.webassembly.js:1
Qt @ blazor.webassembly.js:1
await in Qt (async)
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
```

### .NET Version

8.0.100-preview.2.23157.25

### Anything else?

[blazorwasm8p2.azurewebsites.net-1678845531225.log](https://github.com/dotnet/aspnetcore/files/10975260/blazorwasm8p2.azurewebsites.net-1678845531225.log)

IDE: VS 2022 Enterprise Version 17.6.0 Preview 2.0

**Comment by gdar91** [comment]
@SQL-MisterMagoo AOT has issues in general. Even in .NET 7, it breaks when you use a particular arrangement of generic invocations. I had to inline all F# calls to work around this. It also happens on iOS when using the AOT. Sadly, I can't share the production code, that it breaks on and I haven't been able to reproduce it for more uncomplicated cases.
