### ISSUE TITLE
Quarantine BlazorWasmStandaloneTemplate_Works

### ISSUE THREAD

**Issue by sebastienros** [dotnet/aspnetcore#47225]
## Failing Test(s)

BlazorTemplates.Tests.BlazorWasmTemplateTest.BlazorWasmStandaloneTemplate_Works(browserKind: Chromium)

## Error Message

```text
System.TimeoutException : Timeout 30000ms exceeded.\n=========================== logs ===========================\nwaiting for Locator("nav") to be visible\n============================================================



```

## Stacktrace

<details>

```text
   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](String guid, String method, Object args) in /_/src/Playwright/Transport/Connection.cs:line 163
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal)
   at Microsoft.Playwright.Core.Frame.WaitForSelectorAsync(String selector, FrameWaitForSelectorOptions options) in /_/src/Playwright/Core/Frame.cs:line 476
   at BlazorTemplates.Tests.BlazorWasmTemplateTest.TestBasicNavigation(String appName, IPage page, Boolean usesAuth, Boolean skipFetchData) in /_/src/ProjectTemplates/test/Templates.Blazor.Tests/BlazorWasmTemplateTest.cs:line 401
   at BlazorTemplates.Tests.BlazorWasmTemplateTest.BlazorWasmStandaloneTemplate_Works(BrowserKind browserKind) in /_/src/ProjectTemplates/test/Templates.Blazor.Tests/BlazorWasmTemplateTest.cs:line 46
   at BlazorTemplates.Tests.BlazorWasmTemplateTest.BlazorWasmStandaloneTemplate_Works(BrowserKind browserKind) in /_/src/ProjectTemplates/test/Templates.Blazor.Tests/BlazorWasmTemplateTest.cs:line 46

```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=205302&view=ms.vss-test-web.build-test-results-tab&runId=3824554&resultId=100034&paneView=debug

**Comment by sebastienros** [comment]
Seems to be already skipped, investigating why it still shows up in the failures.

**Comment by sebastienros** [comment]
Found out the test I was looking was the wrong one

**Comment by wtgodbe** [comment]
Theory: https://github.com/dotnet/aspnetcore/pull/47110#issuecomment-1470726156

**Comment by MackinnonBuck** [comment]
Going to dupe against https://github.com/dotnet/aspnetcore/issues/46430, since that tracks getting all the template tests to run in CI
