### ISSUE TITLE
An InvalidOperationException instead of an OperationCanceledException can sometimes be thrown for request body timeouts

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#4730]
See the following test failure from aspnet/KestrelHttpServer#2845

```
17:14:07   [xUnit.net 00:00:53.16]     ConnectionClosedWhenBothRequestAndResponseExperienceBackPressure [FAIL]
17:14:07   Failed   ConnectionClosedWhenBothRequestAndResponseExperienceBackPressure
17:14:07   Error Message:
17:14:07    Assert.Throws() Failure
17:14:07   Expected: typeof(System.OperationCanceledException)
17:14:07   Actual:   typeof(System.InvalidOperationException): Advancing examined to the end would cause pipe to deadlock because FlushAsync is waiting.
17:14:07   Stack Trace:
17:14:07      at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_BackpressureDeadlock()
17:14:07      at System.IO.Pipelines.Pipe.AdvanceReader(BufferSegment consumedSegment, Int32 consumedIndex, BufferSegment examinedSegment, Int32 examinedIndex)
17:14:07      at System.IO.Pipelines.Pipe.DefaultPipeReader.AdvanceTo(SequencePosition consumed, SequencePosition examined)
17:14:07      at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.PumpAsync()
17:14:07      at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
17:14:07      at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
17:14:07      at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
17:14:07      at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
17:14:07      at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.CopyToAsync(Stream destination, CancellationToken cancellationToken) in /_/src/Kestrel.Core/Internal/Http/MessageBody.cs:line 86
17:14:07      at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.CopyToAsyncInternal(Stream destination, CancellationToken cancellationToken) in /_/src/Kestrel.Core/Internal/Http/HttpRequestStream.cs:line 157
17:14:07      at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.<>c__DisplayClass11_0.<<ConnectionClosedWhenBothRequestAndResponseExperienceBackPressure>g__App|4>d.MoveNext() in /_/test/Kestrel.Transport.FunctionalTests/ResponseTests.cs:line 679
17:14:07   --- End of stack trace from previous location where exception was thrown ---
17:14:07   Standard Output Messages:
17:14:07    | [0.001s] TestLifetime Information: Starting test ConnectionClosedWhenBothRequestAndResponseExperienceBackPressure at 2018-08-24T00:13:56
17:14:07    | [0.010s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting starting
17:14:07    | [0.010s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting started
17:14:07    | [0.011s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Loaded hosting startup assembly Sockets.FunctionalTests, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
17:14:07    | [0.011s] Microsoft.AspNetCore.Server.Kestrel Debug: TestServer is listening on port 59312
17:14:07    | [0.011s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLG9APF4IM52" started.
17:14:07    | [0.011s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request starting HTTP/1.1 POST http:///  6553600
17:14:07    | [0.023s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLG9APF4IM52", Request id "0HLG9APF4IM52:00000001": started reading request body.
17:14:07    | [1.598s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLG9APF4IM52" paused.
17:14:07    | [3.025s] Microsoft.AspNetCore.Server.Kestrel Information: Connection id "0HLG9APF4IM52", Request id "0HLG9APF4IM52:00000001": the connection was closed because the response was not read by the client at the specified minimum data rate.
17:14:07    | [3.025s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLG9APF4IM52" aborted.
17:14:07    | [3.025s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLG9APF4IM52" sending FIN.
17:14:07    | [3.025s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLG9APF4IM52" disconnecting.
17:14:07    | [3.026s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLG9APF4IM52" resumed.
17:14:07    | [3.028s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLG9APF4IM52", Request id "0HLG9APF4IM52:00000001": done reading request body.
17:14:07    | [3.030s] Microsoft.AspNetCore.Server.Kestrel Error: Connection id "0HLG9APF4IM52", Request id "0HLG9APF4IM52:00000001": An unhandled exception was thrown by the application.
17:14:07    | System.InvalidOperationException: Advancing examined to the end would cause pipe to deadlock because FlushAsync is waiting.
17:14:07    |    at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_BackpressureDeadlock()
17:14:07    |    at System.IO.Pipelines.Pipe.AdvanceReader(BufferSegment consumedSegment, Int32 consumedIndex, BufferSegment examinedSegment, Int32 examinedIndex)
17:14:07    |    at System.IO.Pipelines.Pipe.DefaultPipeReader.AdvanceTo(SequencePosition consumed, SequencePosition examined)
17:14:07    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.PumpAsync()
17:14:07    |    at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
17:14:07    |    at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
17:14:07    |    at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
17:14:07    |    at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
17:14:07    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.MessageBody.CopyToAsync(Stream destination, CancellationToken cancellationToken) in /_/src/Kestrel.Core/Internal/Http/MessageBody.cs:line 86
17:14:07    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.CopyToAsyncInternal(Stream destination, CancellationToken cancellationToken) in /_/src/Kestrel.Core/Internal/Http/HttpRequestStream.cs:line 157
17:14:07    |    at Microsoft.AspNetCore.Server.Kestrel.FunctionalTests.ResponseTests.<>c__DisplayClass11_0.<<ConnectionClosedWhenBothRequestAndResponseExperienceBackPressure>g__App|4>d.MoveNext() in /_/test/Kestrel.Transport.FunctionalTests/ResponseTests.cs:line 679
17:14:07    | --- End of stack trace from previous location where exception was thrown ---
17:14:07    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application) in /_/src/Kestrel.Core/Internal/Http/HttpProtocol.cs:line 542
17:14:07    | [3.031s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 3019.943ms 200 
17:14:07    | [3.032s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLG9APF4IM52" stopped.
17:14:07    | [3.038s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
17:14:07    | [3.039s] TestLifetime Information: Finished test ConnectionClosedWhenBothRequestAndResponseExperienceBackPressure in 3.038697s
```

https://ci3.dot.net/job/aspnet_KestrelHttpServer/job/release_2.2/job/osx-Configuration_Release_prtest/161/

**Comment by pranavkm** [comment]
@halter73 do you think we could close this?

**Comment by halter73** [comment]
Absolutely

**Comment by halter73** [comment]
For future reference, https://github.com/dotnet/corefx/pull/35711 fixed this.
