### ISSUE TITLE
Restarting during dotnet-watch with hot reload doesn't remove unix domain socket

### ISSUE THREAD

**Issue by djeikyb** [dotnet/aspnetcore#47310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I run an asp core project with `dotnet watch` with hot reload, and then use `ctrl + r` to restart the app, the unix domain socket is not removed during the app shutdown. Then, when the app starts again, kestrel fails to establish itself on the unix domain socket.

I'm using dotnet 7 on an m1, macos 13.2.1.

### Expected Behavior

Given an instruction to `dotnet watch` to restart the app; when kestrel shuts down; then the unix domain socket should be removed.

### Steps To Reproduce

[Minimal repro project!](https://github.com/djeikyb/repro-net7-hot-reload-unix-domain-socket) Used 7.0.202 with the webapi template, and a workaround with logging. The logs demonstrate that the unix domain socket still exists. But since we're checking anyway, I remove the socket so that kestrel won't be bothered by it.

```
var builder = WebApplication.CreateBuilder(args);

var socketPath = Path.Combine(Path.GetTempPath(), "jacob-webapi");

builder.WebHost.ConfigureKestrel(
    kestrel =>
    {
        kestrel.ListenLocalhost(5277);
        kestrel.ListenUnixSocket(
            socketPath,
            listen =>
            {
                var logger = listen.ApplicationServices.GetRequiredService<ILogger<Program>>();
                if (File.Exists(socketPath))
                {
                    logger.LogInformation("Our Unix Domain Socket already exists at {UdsPath}.", socketPath);
                    try
                    {
                        File.Delete(socketPath);
                        logger.LogInformation("Removed stale Unix Domain Socket at {UdsPath}.", socketPath);
                    }
                    catch (Exception e)
                    {
                        logger.LogError(
                            e,
                            "Failed to remove stale Unix Domain Socket at {UdsPath}.",
                            socketPath
                        );
                    }
                }
            }
        );
    }
);

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();
try
{
    app.UseSwagger();
    app.UseSwaggerUI();

    var summaries = new[]
    {
        "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
    };

    app.MapGet(
            "/weatherforecast",
            () =>
            {
                var forecast = Enumerable.Range(1, 5)
                    .Select(
                        index =>
                            new WeatherForecast(
                                DateOnly.FromDateTime(DateTime.Now.AddDays(index)),
                                Random.Shared.Next(-20, 57),
                                summaries[Random.Shared.Next(summaries.Length)]
                            )
                    )
                    .ToArray();
                return forecast;
            }
        )
        .WithName("GetWeatherForecast")
        .WithOpenApi();

    app.Run();
}
finally
{
    await app.DisposeAsync();
}

record WeatherForecast(DateOnly Date, int TemperatureC, string? Summary)
{
    public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
}
```

### .NET Version

7.0.202

**Comment by djeikyb** [comment]
Same behaviour when running with `dotnet watch --no-hot-reload`, and then make a change like eg changing the forecast endpoints random range boundaries.

**Comment by captainsafia** [comment]
@amcasey Any thoughts on this? It came up in a review of hot reload-related issues and it seems like this might actually be related to Kestrel + Unix given the repro.

**Comment by amcasey** [comment]
I'm pretty sure the OS holds on to TCP sockets for a bit after they're closed - any chance it does the same for domain sockets?  I guess an easy way to test would be to ctrl-c the app and restart it manually to see whether that behaves different from hot reload.  If it leaks without hot reload, it's obviously a kestrel issue.  Otherwise, I guess those two restart methods must have different teardown mechanisms and we'd have to investigate which were correct.

@captainsafia I don't suppose you've had a chance to test the minimal repro?

**Comment by captainsafia** [comment]
@amcasey I hadn't tried to repro this when I originally looped you into the issue.

Trying the repro on the following configuration doesn't seem to produce the same issue that @djeikyb saw.

macOS 14.0
.NET SDK:
 Version:   7.0.202
 Commit:    6c74320bc3

@djeikyb Your issue came up during a recent triage of the hot reload area. It's been a few months since you originally reported it but is there a chance it's still a problem?

**Comment by djeikyb** [comment]
I can't repro anymore. I get these console logs:

> info: Program[0]
>       Removed stale Unix Domain Socket at /var/folders/9m/25nqg0sd5b51pm8dz78j31740000gn/T/jacob-webapi.
> info: Microsoft.Hosting.Lifetime[14]
>       Now listening on: http://localhost:5277
> info: Microsoft.Hosting.Lifetime[14]
>       Now listening on: http://unix:/var/folders/9m/25nqg0sd5b51pm8dz78j31740000gn/T/jacob-webapi

And testing with netcat works, like:

```
repro-net7-hot-reload-unix-domain-socket ❯ nc -U /var/folders/9m/25nqg0sd5b51pm8dz78j31740000gn/T/jacob-webapi
asdf
HTTP/1.1 400 Bad Request
Content-Length: 0
Connection: close
Date: Thu, 12 Oct 2023 04:19:10 GMT
Server: Kestrel

```

**Comment by djeikyb** [comment]
I deleted my silly comment where I thought it was fixed because I failed to read my original issue correctly, and also the readme on my repro 🤦‍♂️ I forgot my repro repo had a workaround that deletes the socket if it already exists. I can repro on 7.0.305 and 8.0.100-rc.2.23502.2. 

I'm still on an m1; now on macos 13.5.2 (ventura)

Here's the console logs from when I run the repro with my workaround commented out:

```
/Users/jacob/dev/me/active/repro-net7-hot-reload-unix-domain-socket ❯ dotnet watch
dotnet watch 🔥 Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload.
  💡 Press "Ctrl + R" to restart.
dotnet watch 🔧 Building...
  Determining projects to restore...
  All projects are up-to-date for restore.
  webapi -> /Users/jacob/dev/me/active/repro-net7-hot-reload-unix-domain-socket/bin/Debug/net7.0/webapi.dll
dotnet watch 🚀 Started
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5277
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://unix:/var/folders/9m/25nqg0sd5b51pm8dz78j31740000gn/T/jacob-webapi
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/jacob/dev/me/active/repro-net7-hot-reload-unix-domain-socket
dotnet watch 🔧 Building...
  webapi -> /Users/jacob/dev/me/active/repro-net7-hot-reload-unix-domain-socket/bin/Debug/net7.0/webapi.dll
dotnet watch 🚀 Started
Unhandled exception. System.IO.IOException: Failed to bind to address http://unix:/var/folders/9m/25nqg0sd5b51pm8dz78j31740000gn/T/jacob-webapi: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
 ---> System.Net.Sockets.SocketException (48): Address already in use
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass30_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args) in /Users/jacob/dev/me/active/repro-net7-hot-reload-unix-domain-socket/Program.cs:line 70
   at Program.<Main>$(String[] args) in /Users/jacob/dev/me/active/repro-net7-hot-reload-unix-domain-socket/Program.cs:line 75
   at Program.<Main>(String[] args)
dotnet watch ❌ Exited with error code 134
dotnet watch ⏳ Waiting for a file to change before restarting dotnet...
```

**Comment by captainsafia** [comment]
@djeikyb I similarly disabled the workaround but wasn't able to repro. Although I should note that I'm running the following configuration:

- macOS 14.1
- .NET 8.0.100-rc.2.23472.8

@amcasey Are there any logs that @djeikyb could gather that could help here?

**Comment by amcasey** [comment]
@captainsafia Unfortunately, logging appears to be rather light in this area.

@djeikyb Did you have a chance to check whether the hot reload behavior is different from the kill-and-quickly-restart behavior?

**Comment by amcasey** [comment]
When I hit `ctrl-c` on a `dotnet run` app, I see the socket getting disposed.  On `ctrl-r` in `dotnet watch`, I don't hit that breakpoint.  Could be debugger weirdness on release binaries, but I'm wondering if `dotnet watch` is aggressively killing the process without letting it tear down.

**Comment by amcasey** [comment]
I found some internal tracing I could read with `dotnet trace`, but it looks like `ctrl-r` in `dotnet watch` truncates the trace in an incomplete state...

Maybe (a) there's some way `dotnet watch` could tear down the process more gracefully and/or (b) there's some way the socket PAL could register the file with the OS as one that should be deleted when the process goes away.

In the meantime, you might be stuck checking for and deleting the existing socket/file. 😢

**Comment by amcasey** [comment]
The same thing happens if you `kill -9` the server.

**Comment by amcasey** [comment]
@karelz Any guidance here?  TL;DR Unix domain sockets don't get cleaned up when the process crashes.  Is there anything `Socket` consumers (or `Socket` itself) can do to guard against this?

**Comment by adityamandaleeka** [comment]
@amcasey I put this in Backlog, but perhaps it's not actionable by us at all and we should close it?

**Comment by djeikyb** [comment]
Should it be moved to a Kestrel project? From that SO post it looks like there might be some best effort cleanup. I'm not gonna be mad about closing tho; it's a minor inconvenience to handle

**Comment by amcasey** [comment]
It seems possible that some combination of dotnet-watch, kestrel, and runtime (i.e. Socket) changes could improve things in this scenario, but I think we'd want evidence of broad customer impact before we'd prioritize that investigation over other issues and feature work.  Keeping it in the backlog to collect upvotes (or, conceivably, a proposed fix) seems appropriate to me.

**Comment by Socolin** [comment]
Hello

I'm also getting error with unix socket not getting removed when stopping the app from the IDE, the app is killed and the unix socket is not removed.

> [@karelz](https://github.com/karelz) Any guidance here? TL;DR Unix domain sockets don't get cleaned up when the process crashes. Is there anything `Socket` consumers (or `Socket` itself) can do to guard against this?

Why don't check if the socket is valid before binding to it ? If the unix ssocket is in invalid state it can be safely deleted and then a new one can replace it

With something like:
```cs
    if (File.Exists(path)) {
        // Try to connect to see if it's actually in use
        try {
            // If we can connect, socket is actually in use - fail
            var testSocket = new Socket(...);
            testSocket.Connect(path);
            testSocket.Close();
            throw new AddressInUseException("Socket is actively in use");
        } catch (SocketException) {
            // Connection failed = stale socket, safe to delete
            File.Delete(path);
        }
    }
 ```
