### ISSUE TITLE
Heartbeat.TimerLoop continues running after WebHost stopped and disposed

### ISSUE THREAD

**Issue by mconnew** [dotnet/aspnetcore#47577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

CoreWCF has a new test to validate a fix for a failure code path in PR (CoreWCF/CoreWCF#1011). It consistently fails running on Linux in .NET 6.0 and .NET 7.0, and occasionally fails on Windows.  

We configure a custom logger provider which writes to the XUnit ITestOutputHelper so that we can capture any log output with the test that's running. XUnit throws an exception if you try to write to the logger after the test has ended. We added some extra instrumentation to record which test was getting an exception due to writing to the ITestOutputHelper after the test has completed. We did this to catch test failures where we had forgotten to clean up the WebHost correctly so the exception message when this happens includes the test name in the exception message. In the test that we're seeing problems, we have received the entire Http response as we have created an exception (which we catch and check) from the response.  
The error we get when running the test as part of our PR tests is this:
```
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.AggregateException: An error occurred while writing to logger(s). (ThrowingExtensibilityReturnsFault is no longer an active test.)
 ---> System.InvalidOperationException: ThrowingExtensibilityReturnsFault is no longer an active test.
   at Helpers.XunitLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /home/vsts/work/1/s/src/Common/tests/Helpers/XunitLogger.cs:line 41
   at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|12_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.ThrowLoggingError(List`1 exceptions)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelTrace.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.LogError(ILogger logger, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.Heartbeat.OnHeartbeat()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.Heartbeat.TimerLoop()
```
We are correctly disposing the WebHost (which will call StopAsync for us) as we have a using block around the host. It looks like the TimerLoop is failing a heartbeat check (as expected as the WebHost has been shut down) and logging the failure. The logging after test end is causing XUnit to abort the test run.  

I don't know why we aren't seeing this problem on other tests. The only thing which is different with this test is it's a lot quicker than our other tests as the operation dispatch is purposefully failed quite early in our dispatch process and generates a failure message very quickly. From an aspnetcore perspective, we aren't doing anything different.

### Expected Behavior

The HeartBeat timer doesn't run after the WebHost has stopped and been disposed. If this is difficult because of race conditions, at least don't log anything after the host has been stopped.

### Steps To Reproduce

The behavior reproduces with the new test `ThrowingExtensibilityReturnsFault` in the CoreWCF PR CoreWCF/CoreWCF#1011. It's possible the issue only reproduces in a 2 CPU core environment. Doing that can be done by providing a xunit.runner.json file with the following contents:
```json
{
    "$schema": "https://xunit.net/schema/current/xunit.runner.schema.json",
    "maxParallelThreads" : 2
}
```

We are mostly seeing this reproduce on Linux, but I have seen it fail on Windows in our PR test runs.

### Exceptions (if any)

```
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.AggregateException: An error occurred while writing to logger(s). (ThrowingExtensibilityReturnsFault is no longer an active test.)
 ---> System.InvalidOperationException: ThrowingExtensibilityReturnsFault is no longer an active test.
   at Helpers.XunitLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter) in /home/vsts/work/1/s/src/Common/tests/Helpers/XunitLogger.cs:line 41
   at Microsoft.Extensions.Logging.Logger.<Log>g__LoggerLog|12_0[TState](LogLevel logLevel, EventId eventId, ILogger logger, Exception exception, Func`3 formatter, List`1& exceptions, TState& state)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Logging.Logger.ThrowLoggingError(List`1 exceptions)
   at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelTrace.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.LogError(ILogger logger, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.Heartbeat.OnHeartbeat()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.Heartbeat.TimerLoop()
```

### .NET Version

Latest 6.0 and 7.0 GA releases

**Comment by mconnew** [comment]
I looked at the code for HeartBeat and there are multiple bugs in the code. The first is in the TimerLoop which has code which looks like this:
```c#
    private void TimerLoop()
    {
        while (!_stopped)
        {
            Thread.Sleep(_interval);
            OnHeartbeat();
        }
    }
```
The two lines of code should be switched, call `OnHeartbeat()` first, then sleep. This way `_stopped` will be checked immediately before calling `OnHeartbeat()` instead of there being a 1 second delay between them.  

The next bug is in `OnHeartBeat()`. There's a catch block which logs if there's an exception thrown during any heartbeat checks:
```c#
        catch (Exception ex)
        {
            _trace.LogError(0, ex, $"{nameof(Heartbeat)}.{nameof(OnHeartbeat)}");
        }
```
This should be wrapped with `if (!_stopped)`. If the service is stopped, then any objects provided from DI (which includes the ILogger instances inside of KestrelTrace) aren't valid to be used.

**Comment by mconnew** [comment]
@davidfowl, would you be happy with a PR without tests? I don't know how I would write a test for this, but the change is minor enough that I think you can confirm correctness by code examination in this case.

**Comment by davidfowl** [comment]
If the tests are really hard to write for this, then sure.

**Comment by mconnew** [comment]
Nevermind, I found a way. I didn't realize you make internals of your product libraries visible to the test libraries. I found the existing tests and can easily test one of the fixes, the one which counts, which is making sure it doesn't log anything after dispose.
