### ISSUE TITLE
COmbined use of @bind-Value:set, @bind-Value:get @bind-Value:event does not work

### ISSUE THREAD

**Issue by MarvinKlein1508** [dotnet/aspnetcore#47661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I want to execute some logic whenever the user inputs another letter into the `InputText` component. So I setup my code like this.
```
 <InputText @bind-Value:get="@Input.Zugangscode1" @bind-Value:set="(code) => OnZugangscodeChangedAsync(code, 1)" @bind-Value:event="oninput" class="form-control" placeholder="****" maxlength="4" id="zugangscode1" />
```

```csharp
private async Task OnZugangscodeChangedAsync(string text, int feldNummer)
    {
        if (text.All(char.IsDigit))
        {
            switch (feldNummer)
            {
                case 1:
                    Input.Zugangscode1 = text;
                    break;
                case 2:
                    Input.Zugangscode2 = text;
                    break;
                case 3:
                    Input.Zugangscode3 = text;
                    break;
                case 4:
                    Input.Zugangscode4 = text;
                    break;
                default:
                    break;
            }

            if (text.Length is 4 && feldNummer is not 4)
            {
                await jsRuntime.FocusAsync($"zugangscode{(feldNummer + 1)}");
            }
        }
    }
```

However, I run into multiple issues with this approach. 

### Expected Behavior

I would expect that this will run my method without any problems and it should not show me any compiler errors at all.

### Steps To Reproduce

1. Create a new Blazor Server app with .NET 8
2. Create a class which holds one property for binding
3. Create an `EditForm` and containing one `InputText` component
4. Add `@bind-Value:get` `@bind-Value:set` `@bind-Value:event` logic
5. STart the app and type anything into the textbox

### Exceptions (if any)

First exception by the compiler:
```
ERROR	RZ10020	Attribute 'bind-Value:get' can only be used with RazorLanguageVersion 7.0 or higher.		
```

However, the code compiles fine.

When I add this attribute to my component:
```
@bind-Value:event="oninput"
```
I get this error while typing within the textbox
```
Error: System.ArgumentException: Object of type 'Microsoft.AspNetCore.Components.ChangeEventArgs' cannot be converted to type 'System.String'.

   at System.RuntimeType.CheckValue(Object& value, ParameterCopyBackAction& copyBack, Binder binder, CultureInfo culture, BindingFlags invokeAttr)

   at System.Reflection.MethodBase.CheckArguments(Span`1 copyOfParameters, IntPtr* byrefParameters, Span`1 shouldCopyBack, ReadOnlySpan`1 parameters, RuntimeType[] sigTypes, Binder binder, CultureInfo culture, BindingFlags invokeAttr)

   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

   at System.Delegate.DynamicInvokeImpl(Object[] args)

   at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[T](MulticastDelegate delegate, T arg)

   at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)

   at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs)
```

When changing `oninput` to `OnInput` I don't get the error but my method doesn't get executed as well.

### .NET Version

.NET 8 preview 2

### Anything else?

I've created a brand new Blazor Server app using .NET 8

**Comment by MarvinKlein1508** [comment]
Changing the code to 
```
<input @bind:get="@Input.Zugangscode1" @bind:set="(code) => OnZugangscodeChangedAsync(code, 1)" @bind:event="oninput" class="form-control" placeholder="****" maxlength="4" id="zugangscode1" />
```
works like I expect it.

**Comment by javiercn** [comment]
@MarvinKlein1508 thanks for contacting us.

`@bind:event="..."` only works for HTML elements, not for components.

**Comment by javiercn** [comment]
@MarvinKlein1508 there's no way to do it with `InputText`, you need to create your own component for it. Not sure if you can extend InputText to support it.

**Comment by Flachdachs** [comment]
You can, it is officially documented: https://learn.microsoft.com/en-us/aspnet/core/blazor/forms-and-input-components?view=aspnetcore-7.0#inputtext-based-on-the-input-event

**Comment by javiercn** [comment]
@MarvinKlein1508 as per @Flachdachs comment, that's the way to go.
