### ISSUE TITLE
Blazor has HttpClient issues on small screens

### ISSUE THREAD

**Issue by LewisEKay** [dotnet/aspnetcore#47815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have tried multiple times and the same outcome every time. 
If you query an endpoint using HttpClient in blazor it works fine in the browser when on desktop. However, if you shrink it down using F12 and pressing the mobile tab (to simulate mobile screen) then there is a lot more performance issues.
If you query on Desktop Size the query takes:  ~00:00:00.3840000
If you query on Mobile Size the query takes: ~00:00:08.4588000
However this is only the case when you use F12 or run it on a physical device. If you just change the size of the window then it does not cause the issue. While the query is fetching, if you press refresh it will then produce this error...

I first noticed this issue when I had a project that I was going to have display through the WebView in Maui. Loading the app with an expected project to load caused the page to crash with a Failed to Fetch error. I thought the WebView was the issue. However I switched to Blazor Maui and did it through an iFrame.... same issue.
I then tried using an Iframe in a HTML file and loaded the HTML file up locally in the browser, then noticed the issue seems to occur, something to do with mobile devices?

`blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: TypeError: Failed to fetch
System.Net.Http.HttpRequestException: TypeError: Failed to fetch
 ---> TypeError: Failed to fetch
   --- End of inner exception stack trace ---
   at System.Net.Http.BrowserHttpInterop.<CancelationHelper>d__13`1[[System.Runtime.InteropServices.JavaScript.JSObject, System.Runtime.InteropServices.JavaScript, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at System.Net.Http.BrowserHttpHandler.CallFetch(HttpRequestMessage request, CancellationToken cancellationToken, Nullable`1 allowAutoRedirect)
   at System.Net.Http.BrowserHttpHandler.<SendAsync>g__Impl|55_0(HttpRequestMessage request, CancellationToken cancellationToken, Nullable`1 allowAutoRedirect)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at BlazorApp4.Client.Pages.FetchData.OnInitializedAsync() in C:\Users\lewis\Desktop\BlazorApp4\BlazorApp4\Client\Pages\FetchData.razor:line 19
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
u`

Please see my repo here of a sample project for you to replicate the issue. The fetch method is on the FetchData view.
[https://github.com/LewisEKay/BlazorHttpClientErrorExample](url)

- Blazor is on the latest version as of writing this from Nuget 
- Tried in Blazor WASM

### .NET Version

7.0.202

**Comment by danroth27** [comment]
@LewisEKay Could you please clarify what the steps are to reproduce the issue you're seeing? I downloaded your project and ran it. Sometimes the request to https://httpbin.org/get is faster or slower. But I'm unable to reproduce the error you are seeing.

Please provide the following:
- The exact steps to reproduce the issue
- A description of expected behavior and the actual behavior you are seeing

Thanks!

**Comment by javiercn** [comment]
@LewisEKay we recommend you try with .NET 8.0 to see if you are still able to reproduce the issue.

In any case, this seems to be specific to HttpClient, so moving to runtime to let folks chime in.
