### ISSUE TITLE
Hot Reload unavailable

### ISSUE THREAD

**Issue by wf-soft** [dotnet/aspnetcore#47836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am using the latest VS2022 17.6.0 Preview 4.0

The preview version created the BlazorServer project, and all hot reloads were invalidated without any prompt. I am unable to determine the reason
```
dotnet watch ⌚ File changed: C:\Users\wf-so\Downloads\HotReloadIssue45519Demo-main\HotReloadIssue45519Demo-main\TradeCars\Client\Pages\Index.razor.
dotnet watch ⌚ No hot reload changes to apply.
```
```
dotnet watch 🔥 Hot reload capabilities: Baseline AddMethodToExistingType AddStaticFieldToExistingType NewTypeDefinition ChangeCustomAttributes.
dotnet watch ⌚ File changed: C:\Users\wf-so\Downloads\HotReloadIssue45519Demo-main\HotReloadIssue45519Demo-main\TradeCars\Client\Pages\Index.razor.
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 POST https://localhost:5008/_framework/blazor-hotreload application/json 2835
dotnet watch ⌚ Received 0 from browser in [Count: 1, MessageType: Binary, EndOfMessage: True].
dotnet watch ⌚ Received failed apply from delta applier.
  ❔ Do you want to restart your app - Yes (y) / No (n) / Always (a) / Never (v)?
```

### .NET Version

dotnet-sdk-7.0.203

**Comment by szalapski** [comment]
This is a direct successor to #45519 .  The issue was not fixe

Here's the minimal example, the same one that was provided in  #45519, now upgraded to use SDK 7.0.302

[szalapski/HotReloadIssue45519Demo](https://github.com/szalapski/HotReloadIssue45519Demo)

Clone this and run

`dotnet watch --verbose --project ./TradeCars/Server`

The site should start up. You'll see Hot reload capabilities: . which portends the failure. Edit anything in Index.razor to watch hot reload fail.

**Comment by szalapski** [comment]
related but different: https://github.com/dotnet/aspnetcore/issues/47836

**Comment by szalapski** [comment]
@wf-soft Can I recommend you edit the title of this issue to read:

`Hot Reload nearly always fails, with Blazor and "dotnet watch"`
 
That will get it more attention and more closely link it to https://github.com/dotnet/aspnetcore/issues/45519.

**Comment by danroth27** [comment]
Adding @phil-allen-msft @maddymontaquila and @mcumming for visibility.

**Comment by tmat** [comment]
I see this error in the browser:

```
 at System.Reflection.Metadata.MetadataUpdater.ApplyUpdate(Assembly assembly, ReadOnlySpan`1 metadataDelta, ReadOnlySpan`1 ilDelta, ReadOnlySpan`1 pdbDelta)
   at Microsoft.Extensions.HotReload.HotReloadAgent.ApplyDeltas(IReadOnlyList`1 deltas)
   at Microsoft.AspNetCore.Components.WebAssembly.HotReload.WebAssemblyHotReload.ApplyHotReloadDelta(String moduleIdString, Byte[] metadataDelta, Byte[] ilDelta, Byte[] pdbBytes)
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, IntPtr* args)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
--- End of stack trace from previous location ---
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.Invoke(JSRuntime jsRuntime, DotNetInvocationInfo& invocationInfo, String argsJson)
   at Microsoft.AspNetCore.Components.WebAssembly.Services.DefaultWebAssemblyJSRuntime.InvokeDotNet(String assemblyName, String methodIdentifier, Int64 dotNetObjectId, String argsJson)
   at Microsoft.AspNetCore.Components.WebAssembly.Services.DefaultWebAssemblyJSRuntime.__Wrapper_InvokeDotNet_1772498872(JSMarshalerArgument* __arguments_buffer)
Error: The assembly can not be edited or changed.
    at yr (https://localhost:5008/_framework/dotnet.runtime.8.0.0-preview.6.23316.2.dk1nh2rbrm.js:3:35896)
    at Uo (https://localhost:5008/_framework/dotnet.runtime.8.0.0-preview.6.23316.2.dk1nh2rbrm.js:3:53691)
    at Object.<anonymous> (https://localhost:5008/_framework/dotnet.runtime.8.0.0-preview.6.23316.2.dk1nh2rbrm.js:3:52482)
    at Object.invokeDotNetFromJS (https://localhost:5008/_framework/blazor.webassembly.js:1:43350)
    at b.invokeDotNetMethod (https://localhost:5008/_framework/blazor.webassembly.js:1:3485)
    at b.invokeDotNetStaticMethod (https://localhost:5008/_framework/blazor.webassembly.js:1:3241)
    at Wt.Ye._internal.applyHotReload (https://localhost:5008/_framework/blazor.webassembly.js:1:52017)
    at https://localhost:5008/_framework/aspnetcore-browser-refresh.js:140:35
    at Array.forEach (<anonymous>)
    at applyBlazorDeltas (https://localhost:5008/_framework/aspnetcore-browser-refresh.js:138:14)
(anonymous) @ aspnetcore-browser-refresh.js:142
applyBlazorDeltas @ aspnetcore-browser-refresh.js:138
BlazorHotReloadDeltav1 @ aspnetcore-browser-refresh.js:46
connection.onmessage @ aspnetcore-browser-refresh.js:53

```

**Comment by tmat** [comment]
@lambdageek

**Comment by lambdageek** [comment]
@tmat I can repro that failure if I have VS Code editing the project (I have the C# Dev Kit installed).  I get different results if I edit with Emacs or vim.  In general `The assembly can not be edited or changed.` can happen if:
1. the `DOTNET_MODIFIABLE_ASSEMBLIES=debug` environment variable is not set in the client-side runtime
2. or the baseline assembly does not have the "optimizer disabled" attribute (essentially the assembly was compiled in Release mode, not Debug)

There's definitely something here. I'll try to get some more info

**Comment by lambdageek** [comment]
@tmat yea, I don't see that `The assembly can not be edited or changed.` error if I disabled the C# Dev Kit extension in VS Code

**Comment by tmat** [comment]
This change will communicate the error message to dotnet-watch and print it out, for easier diagnostics in future: https://github.com/dotnet/sdk/pull/33471

**Comment by lambdageek** [comment]
This should improve the "assembly cannot be edited or changed" error message https://github.com/dotnet/runtime/pull/87880

**Comment by tmat** [comment]
@szalapski 
We found that the issue is with the `launchSettings.json`. The value of `ASPNETCORE_ENVIRONMENT` should be `Development`, not `Developer`. Then `builder.Environment.IsEnvironment("Developer")` in `Program.cs` also needs to be updated.

After these changes Hot Reload works.

We certainly need to improve the error reporting.

**Comment by szalapski** [comment]
We use "developer" for local machines and"development for a deployed dev environment.  Is there any way to get it to work? The docs say that we can use any value we want for Environment so i'd hope there's a way.

**Comment by tmat** [comment]
@szalapski Not currently, but fixing that: https://github.com/dotnet/aspnetcore/pull/48953

**Comment by szalapski** [comment]
Thanks @tmat.  I got rid of the notion of "Developer" in my demo app, instead using "Development" and I see no change.  I still get `dotnet watch ⌚ No hot reload changes to apply.`  Would you be willing to run the demo app and see if you can get it to work?

**Comment by tmat** [comment]
@szalapski I did. It works for me :-/

I had to remove `<PackageReference Include="GeneralMills.VaultSharp.Client" Version="1.19.0" />` though since it did not restore.

**Comment by szalapski** [comment]
> @szalapski I did. It works for me :-/
> 
> I had to remove `<PackageReference Include="GeneralMills.VaultSharp.Client" Version="1.19.0" />` though since it did not restore.

Thanks, I just removed that package reference as well and pushed.

Hmm, I was afraid of that. I'm going to retry.  I deleted my local repo and run exactly as follows

- `git clone https://github.com/szalapski/HotReloadIssue45519Demo`
- `cd .\HotReloadIssue45519Demo\`
- `dotnet watch --project ./TradeCars/Server`

I got a lot of info output, but after I edit Index.razor and save it, I get:

```
dotnet watch ⌚ File changed: .\TradeCars\Client\Pages\Index.razor.
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 POST https://localhost:5008/_framework/blazor-hotreload application/json 2
dotnet watch ⌚ No hot reload changes to apply.
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 POST https://localhost:5008/_framework/blazor-hotreload application/json 2 - 2
```
