### ISSUE TITLE
Quarantine BlazorWasmHostedTemplate_IndividualAuth_NoHttps_Works_WithOutLocalDB

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/aspnetcore#47919]
# Failing test

BlazorWasmHostedTemplate_IndividualAuth_NoHttps_Works_WithOutLocalDB

# Errors

```
Templates.Blazor.Test.BlazorWasmTemplateAuthTest.BlazorWasmHostedTemplate_IndividualAuth_NoHttps_Works_WithOutLocalDB [FAIL]
2023-04-27T05:27:51.0890731Z [xUnit.net 00:20:15.74]       Project new blazorwasm  --auth Individual --hosted    failed to publish. Exit code 1.
2023-04-27T05:27:51.0890788Z [xUnit.net 00:20:15.74]       /datadisks/disk1/work/B203097C/p/dotnet-cli/dotnet publish  -c Release /bl \nStdErr: \nStdOut: MSBuild version 17.7.0-preview-23225-01+6300d22b2 for .NET
2023-04-27T05:27:51.0890820Z [xUnit.net 00:20:15.74]         Determining projects to restore...
2023-04-27T05:27:51.0890852Z [xUnit.net 00:20:15.74]         All projects are up-to-date for restore.
2023-04-27T05:27:51.0890881Z [xUnit.net 00:20:15.74]       /datadisks/disk1/work/B203097C/p/dotnet-cli/sdk/8.0.100-preview.5.23226.2/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(287,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/datadisks/disk1/work/B203097C/w/A4B70922/e/Templates/BaseFolder/AspNet.Jpjfgoh4auyg/Client/AspNet.Jpjfgoh4auyg.Client.csproj]
2023-04-27T05:27:51.1206907Z [xUnit.net 00:20:15.74]       /datadisks/disk1/work/B203097C/p/dotnet-cli/sdk/8.0.100-preview.5.23226.2/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(287,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/datadisks/disk1/work/B203097C/w/A4B70922/e/Templates/BaseFolder/AspNet.Jpjfgoh4auyg/Server/AspNet.Jpjfgoh4auyg.Server.csproj]
2023-04-27T05:27:51.1415398Z [xUnit.net 00:20:15.74]         AspNet.Jpjfgoh4auyg.Shared -> /datadisks/disk1/work/B203097C/w/A4B70922/e/Templates/BaseFolder/AspNet.Jpjfgoh4auyg/Shared/bin/Release/net8.0/AspNet.Jpjfgoh4auyg.Shared.dll
2023-04-27T05:27:51.1415504Z [xUnit.net 00:20:15.74]         AspNet.Jpjfgoh4auyg.Client -> /datadisks/disk1/work/B203097C/w/A4B70922/e/Templates/BaseFolder/AspNet.Jpjfgoh4auyg/Client/bin/Release/net8.0/AspNet.Jpjfgoh4auyg.Client.dll
2023-04-27T05:27:51.1415532Z [xUnit.net 00:20:15.74]         AspNet.Jpjfgoh4auyg.Client (Blazor output) -> /datadisks/disk1/work/B203097C/w/A4B70922/e/Templates/BaseFolder/AspNet.Jpjfgoh4auyg/Client/bin/Release/net8.0/wwwroot
2023-04-27T05:27:51.1415555Z [xUnit.net 00:20:15.74]         Optimizing assemblies for size may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
2023-04-27T05:27:51.1415579Z [xUnit.net 00:20:15.74]         Optimizing assemblies for size. This process might take a while.
2023-04-27T05:27:51.1415601Z [xUnit.net 00:20:15.74]         AspNet.Jpjfgoh4auyg.Client -> /datadisks/disk1/work/B203097C/w/A4B70922/e/Templates/BaseFolder/AspNet.Jpjfgoh4auyg/Client/bin/Release/net8.0/publish/
2023-04-27T05:27:51.1415753Z [xUnit.net 00:20:15.74]         AspNet.Jpjfgoh4auyg.Shared -> /datadisks/disk1/work/B203097C/w/A4B70922/e/Templates/BaseFolder/AspNet.Jpjfgoh4auyg/Shared/bin/Release/net8.0/publish/
2023-04-27T05:27:51.1415792Z [xUnit.net 00:20:15.74]         AspNet.Jpjfgoh4auyg.Server -> /datadisks/disk1/work/B203097C/w/A4B70922/e/Templates/BaseFolder/AspNet.Jpjfgoh4auyg/Server/bin/Release/net8.0/AspNet.Jpjfgoh4auyg.Server.dll
2023-04-27T05:27:51.1415823Z [xUnit.net 00:20:15.74]         Optimizing assemblies for size may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
2023-04-27T05:27:51.1415851Z [xUnit.net 00:20:15.74]       /datadisks/disk1/work/B203097C/p/dotnet-cli/sdk/8.0.100-preview.5.23226.2/Sdks/Microsoft.NET.Sdk.BlazorWebAssembly/targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets(160,5): error MSB4018: The "GenerateBlazorBootExtensionJson" task failed unexpectedly. [/datadisks/disk1/work/B203097C/w/A4B70922/e/Templates/BaseFolder/AspNet.Jpjfgoh4auyg/Client/AspNet.Jpjfgoh4auyg.Client.csproj]
2023-04-27T05:27:51.2022826Z [xUnit.net 00:20:15.74]       /datadisks/disk1/work/B203097C/p/dotnet-cli/sdk/8.0.100-preview.5.23226.2/Sdks/Microsoft.NET.Sdk.BlazorWebAssembly/targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets(160,5): error MSB4018: System.IO.IOException: The process cannot access the file '/datadisks/disk1/work/B203097C/w/A4B70922/e/Templates/BaseFolder/AspNet.Jpjfgoh4auyg/Client/obj/Release/net8.0/blazor.publish.boot-extension.json' because it is being used by another process. [/datadisks/disk1/work/B203097C/w/A4B70922/e/Templates/BaseFolder/AspNet.Jpjfgoh4auyg/Client/AspNet.Jpjfgoh4auyg.Client.csproj]
2023-04-27T05:27:51.2048699Z [xUnit.net 00:20:15.74]       /datadisks/disk1/work/B203097C/p/dotnet-cli/sdk/8.0.100-preview.5.23226.2/Sdks/Microsoft.NET.Sdk.BlazorWebAssembly/targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets(160,5): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Int64& fileLength, UnixFileMode& filePermissions) [/datadisks/disk1/work/B203097C/w/A4B70922/e/Templates/BaseFolder/AspNet.Jpjfgoh4auyg/Client/AspNet.Jpjfgoh4auyg.Client.csproj]
2023-04-27T05:27:51.2049121Z [xUnit.net 00:20:15.74]       /datadisks/disk1/work/B203097C/p/dotnet-cli/sdk/8.0.100-preview.5.23226.2/Sdks/Microsoft.NET.Sdk.BlazorWebAssembly/targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets(160,5): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException) [/datadisks/disk1/work/B203097C/w/A4B70922/e/Templates/BaseFolder/AspNet.Jpjfgoh4auyg/Client/AspNet.Jpjfgoh4auyg.Client.csproj]
2023-04-27T05:27:51.2049273Z [xUnit.net 00:20:15.74]       /datadisks/disk1/work/B203097C/p/dotnet-cli/sdk/8.0.100-preview.5.23226.2/Sdks/Microsoft.NET.Sdk.BlazorWebAssembly/targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets(160,5): error MSB4018:    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode) [/datadisks/disk1/work/B203097C/w/A4B70922/e/Templates/BaseFolder/AspNet.Jpjfgoh4auyg/Client/AspNet.Jpjfgoh4auyg.Client.csproj]
2023-04-27T05:27:51.2049443Z [xUnit.net 00:20:15.74]       /datadisks/disk1/work/B203097C/p/dotnet-cli/sdk/8.0.100-preview.5.23226.2/Sdks/Microsoft.NET.Sdk.BlazorWebAssembly/targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets(160,5): error MSB4018:    at System.IO.File.Create(String path) [/datadisks/disk1/work/B203097C/w/A4B70922/e/Templates/BaseFolder/AspNet.Jpjfgoh4auyg/Client/AspNet.Jpjfgoh4auyg.Client.csproj]
2023-04-27T05:27:51.2049549Z [xUnit.net 00:20:15.74]       /datadisks/disk1/work/B203097C/p/dotnet-cli/sdk/8.0.100-preview.5.23226.2/Sdks/Microsoft.NET.Sdk.BlazorWebAssembly/targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets(160,5): error MSB4018:    at Microsoft.NET.Sdk.BlazorWebAssembly.GenerateBlazorBootExtensionJson.Execute() [/datadisks/disk1/work/B203097C/w/A4B70922/e/Templates/BaseFolder/AspNet.Jpjfgoh4auyg/Client/AspNet.Jpjfgoh4auyg.Client.csproj]
2023-04-27T05:27:51.2049600Z [xUnit.net 00:20:15.74]       /datadisks/disk1/work/B203097C/p/dotnet-cli/sdk/8.0.100-preview.5.23226.2/Sdks/Microsoft.NET.Sdk.BlazorWebAssembly/targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets(160,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/datadisks/disk1/work/B203097C/w/A4B70922/e/Templates/BaseFolder/AspNet.Jpjfgoh4auyg/Client/AspNet.Jpjfgoh4auyg.Client.csproj]
2023-04-27T05:27:51.2049728Z [xUnit.net 00:20:15.74]       /datadisks/disk1/work/B203097C/p/dotnet-cli/sdk/8.0.100-preview.5.23226.2/Sdks/Microsoft.NET.Sdk.BlazorWebAssembly/targets/Microsoft.NET.Sdk.BlazorWebAssembly.6_0.targets(160,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/datadisks/disk1/work/B203097C/w/A4B70922/e/Templates/BaseFolder/AspNet.Jpjfgoh4auyg/Client/AspNet.Jpjfgoh4auyg.Client.csproj]
2023-04-27T05:27:51.2049803Z [xUnit.net 00:20:15.74]       
2023-04-27T05:27:51.2049829Z [xUnit.net 00:20:15.74]       Expected: True
2023-04-27T05:27:51.2049857Z [xUnit.net 00:20:15.74]       Actual:   False
2023-04-27T05:27:51.2049886Z [xUnit.net 00:20:15.74]       Stack Trace:
2023-04-27T05:27:51.2049913Z [xUnit.net 00:20:15.74]         /_/src/ProjectTemplates/Shared/Project.cs(152,0): at Templates.Test.Helpers.Project.RunDotNetPublishAsync(IDictionary`2 packageOptions, String additionalArgs, Boolean noRestore)
2023-04-27T05:27:51.2050057Z [xUnit.net 00:20:15.74]         /_/src/ProjectTemplates/Shared/BlazorTemplateTest.cs(80,0): at Templates.Blazor.Test.BlazorTemplateTest.CreateBuildPublishAsync(String auth, String[] args, String targetFramework, Boolean serverProject, Boolean onlyCreate)
2023-04-27T05:27:51.2050119Z [xUnit.net 00:20:15.74]         /_/src/ProjectTemplates/test/Templates.Blazor.WebAssembly.Auth.Tests/BlazorWasmTemplateAuthTest.cs(81,0): at Templates.Blazor.Test.BlazorWasmTemplateAuthTest.CreateBuildPublishIndividualAuthProject(Boolean useLocalDb, Boolean useProgramMain, Boolean noHttps)
2023-04-27T05:27:51.2050215Z [xUnit.net 00:20:15.74]         /_/src/ProjectTemplates/test/Templates.Blazor.WebAssembly.Auth.Tests/BlazorWasmTemplateAuthTest.cs(114,0): at Templates.Blazor.Test.BlazorWasmTemplateAuthTest.BlazorWasmHostedTemplate_IndividualAuth_Works(Boolean useLocalDb, Boolean useProgramMain, Boolean noHttps)
2023-04-27T05:27:51.2050289Z [xUnit.net 00:20:15.74]         --- End of stack trace from previous location ---
2023-04-27T05:27:51.2178756Z [xUnit.net 00:20:15.74]       Output:
2023-04-27T05:27:51.2178868Z [xUnit.net 00:20:15.74]         | [0.004s] TestLifetime Information: Starting test BlazorWasmHostedTemplate_IndividualAuth_NoHttps_Works_WithOutLocalDB at 2023-04-27T05:27:12
2023-04-27T05:27:51.2178905Z [xUnit.net 00:20:15.74]         | [0.005s] Templates.Blazor.Test.BlazorWasmTemplateAuthTest Information: ==> /datadisks/disk1/work/B203097C/p/dotnet-cli/dotnet new blazorwasm  --debug:disable-sdk-templates --debug:custom-hive "/datadisks/disk1/work/B203097C/w/A4B70922/e/Hives/.templateEngine" --auth Individual --hosted    -o /datadisks/disk1/work/B203097C/w/A4B70922/e/Templates/BaseFolder/AspNet.Jpjfgoh4auyg [/datadisks/disk1/work/B203097C/w/A4B70922/e/]
```

Failing build:
https://dev.azure.com/dnceng-public/public/_build/results?buildId=254119&view=results

Helix result:
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-pull-47540-merge-f27eaa5066f44a74be/Templates.Blazor.WebAssembly.Auth.Tests--net8.0/4/console.f2e43e1a.log?helixlogtype=result

**Comment by javiercn** [comment]
This test no longer exists
