### ISSUE TITLE
System.InvalidOperationException: Unable to configure HTTPS endpoint. (Kestrel -> BindAsync -> UseHttps())

### ISSUE THREAD

**Issue by KirillOsenkov** [dotnet/aspnetcore#47915]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Created a new ASP.NET Core web service project with .NET 7, deployed to an Azure App Service (Linux), there was an exception call stack in the Log Stream in Azure Portal for the app service:

```
/home/LogFiles/2023_04_26_0FZ_default_docker.log  (https://******.scm.azurewebsites.net/api/vfs/LogFiles/2023_04_26_****_default_docker.log)
2023-04-26T18:01:02.103371181Z    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
2023-04-26T18:01:02.103375581Z    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
2023-04-26T18:01:02.103379081Z    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
2023-04-26T18:01:02.103382981Z    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
2023-04-26T18:01:02.103386681Z    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
2023-04-26T18:01:02.103390881Z    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
2023-04-26T18:01:02.103394781Z    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
2023-04-26T18:01:02.103399381Z    at Web.Service.Program.Main(String[] args) in D:\a\1\s\src\Web.Service\WebServiceProgram.cs:line 56
2023-04-26T18:01:02.267182541Z /opt/startup/startup.sh: line 19:    76 Aborted                 (core dumped) dotnet "Web.Service.dll"
```

This is not local development, but after deploying to the Azure App Service. The exception seems to be benign (the api route `/api/mycontroller` works fine and returns results). However requesting the main page shows a blank screen in the browser (as expected).

It is misleading to see this call stack in the logs. Also docker seems to be involved (how did Docker come into picture?)

Is this some spurious error/exception that can be cleaned up?

The impact of this is that unexperienced users may forget to check if the API works (`https://mysite.azurewebsites.net/api/mycontroller`), they instead check the root URL (`https://mysite.azurewebsites.net`), see it doesn't work, and spend a few hours tearing their hair out chasing red herrings around https, SSL, certificates, etc. when everything was working all along.

### Expected Behavior

Default web site for .NET 7 deployed to Azure App Service should not print any exceptions to the logs.

### .NET Version

.NET 7 on Azure App Service

**Comment by Tratcher** [comment]
What was the actual exception type and message? `System.InvalidOperationException: Unable to configure HTTPS`?

**Comment by KirillOsenkov** [comment]
No, it wasn't in the logs at all (that's another thing that seems broken). I originally pasted the wrong exception into this bug title.

**Comment by KirillOsenkov** [comment]
If you'd like to see a live repro and look at the source, ping Lance Collins on Teams. We have the source and the Azure App Service readily available internally.
