### ISSUE TITLE
Quarantine E2E Component tests related to scrolling within page

### ISSUE THREAD

**Issue by amcasey** [dotnet/aspnetcore#47967]
## Failing Test(s)

- Microsoft.AspNetCore.Components.E2ETest.Tests.RoutingTest.AnchorWithHrefContainingHashAnotherPage_NavigatesToPageAndScrollsToElement
- Microsoft.AspNetCore.Components.E2ETest.Tests.RoutingTest.NavigatationManagerNavigateToSameUrlWithHash_ScrollsToElementOnTheSamePage
- Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.ServerRoutingTest.NavigatationManagerNavigateToSameUrlWithHash_ScrollsToElementOnTheSamePage
- Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.ServerRoutingTest.AnchorWithHrefContainingHashAnotherPage_NavigatesToPageAndScrollsToElement

## Error Message

```text
OpenQA.Selenium.NoSuchElementException : no such element: Unable to locate element: {"method":"css selector","selector":"*[name ="test2"]"}
```

## Stacktrace

<details>

```text
at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebElement.Execute(String commandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebElement.FindElement(String mechanism, String value)
   at OpenQA.Selenium.By.&lt;.ctor&gt;b__11_0(ISearchContext context)
   at OpenQA.Selenium.By.FindElement(ISearchContext context)
   at OpenQA.Selenium.WebElement.FindElement(By by)
   at Microsoft.AspNetCore.Components.E2ETest.Tests.RoutingTest.AnchorWithHrefContainingHashAnotherPage_NavigatesToPageAndScrollsToElement() in /home/vsts/work/1/s/src/Components/test/E2ETest/Tests/RoutingTest.cs:line 1575
   at InvokeStub_RoutingTest.AnchorWithHrefContainingHashAnotherPage_NavigatesToPageAndScrollsToElement(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```
</details>

## Logs

<details>

```text

```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=256124

**Comment by amcasey** [comment]
Appears to have started with https://github.com/dotnet/aspnetcore/pull/47954 (FYI @surayya-MS)

**Comment by amcasey** [comment]
Since the failures started, those tests appear to have been renamed "Navigatation" -> "Navigation".

**Comment by MackinnonBuck** [comment]
https://github.com/dotnet/aspnetcore/pull/47963 should have fixed this issue.

**Comment by mitchdenny** [comment]
I guess we can close this now.
