### ISSUE TITLE
Fully occupied /tmp for ASP Dot Net Core hosted on AWS Lambda is breaking API's

### ISSUE THREAD

**Issue by ChSankalp** [dotnet/aspnetcore#48149]
### Description

A few of the API's intermittently are failing due to "No Space left on device error" when trying to serialize the response for the API. The framework uses NewtonSoft JSON formatter. When this formatter is trying to access the tmp storage i.e. ephemeral storage for AWS Lambda (max memory available: 512 MB), it is failing with the below error:
```
> Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware - message=An unhandled exception has occurred while executing the request. error=System.IO.IOException: No space left on device : '/tmp/ASPNETCORE_e0cf2c22-e853-417a-874b-22527eb4a609.tmp'
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.OSFileStreamStrategy.Write(ReadOnlySpan`1 buffer)
   at System.IO.Strategies.OSFileStreamStrategy.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.AspNetCore.WebUtilities.PagedByteBuffer.MoveTo(Stream stream)
   at Microsoft.AspNetCore.WebUtilities.FileBufferingWriteStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.AspNetCore.WebUtilities.HttpResponseStreamWriter.Write(String value)
   at Newtonsoft.Json.Utilities.JavaScriptUtils.WriteEscapedJavaScriptString(TextWriter writer, String s, Char delimiter, Boolean appendDelimiters, Boolean[] charEscapeFlags, StringEscapeHandling stringEscapeHandling, IArrayPool`1 bufferPool, Char[]& writeBuffer)
   at Newtonsoft.Json.JsonTextWriter.WriteValue(String value)
   at Newtonsoft.Json.JsonWriter.WriteValue(JsonWriter writer, PrimitiveTypeCode typeCode, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value)
   at Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at ZS.OE.Commons.Restful.Core.Middleware.ValidateAntiForgeryTokenMiddleware.Invoke(HttpContext context)
   at ZS.OE.Commons.Restful.Core.Middleware.PostAuthenticationMiddleware.InvokeAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at ZS.OE.Commons.Restful.Core.StartupBase.<>c.<<Configure>b__11_1>d.MoveNext()
--- End of stack trace from previous location ---
   at ZS.OE.Commons.Restful.Core.StartupBase.<>c.<<Configure>b__11_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```
I wrote an dummy API to fetch the size of the files and directories in the tmp folder and when hit (luckily the same container for which the API's failed), two distinct responses were:

> /tmp/core..NET Sockets.8\ : ~620MB

> /tmp/core..NET Timer : ~600MB

Dotnet version: 6.0
AWS Lambda Max memory available: 1280MB
AWS Lambda Ephemeral storage: 512MB

My codebase does not use temporary storage explicitly anywhere!

Does the .Net Framework use temporary storage (such huge size) for any purpose? Is there any specific reason why the RAM is not used instead? 

### Reproduction Steps

It is an intermittent issue experiencing on AWS Lambda.

### Expected behavior

Newton Soft Json formatter must be able to create tmp files while formatting/serializing the response.

### Actual behavior

Newton Soft Json formatter is unable to create tmp files while formatting/serializing the response as the tmp is already full.

### Known Workarounds

Re-deploying our code onto the lambda i.e creating new lambda version is killing already active containers and new containers that become active come with empty /tmp storage.

### Configuration

.Net Version: 6.0
Lambda internally uses Linux agents, runs on x86_64 architecture.

**Comment by davidfowl** [comment]
> Does the .Net Framework use temporary storage (such huge size) for any purpose? Is there any specific reason why the RAM is not used instead?

Yes it does. You can increase the limit using the settings on the options using (https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.mvcnewtonsoftjsonoptions.inputformattermemorybufferthreshold?view=aspnetcore-7.0). Set it to the very big number (it'll hurt the performance but avoid the disk issue you are running into).

By default the system will buffer up to 30K in memory then switch to disk buffering.

**Comment by danmoseley** [comment]
@ChSankalp I added triple back ticks ` above and below your callstack to make it more readable!

**Comment by ChSankalp** [comment]
@davidfowl I believe Newton soft JSON formatter clears the disk buffer after serialize/de-serialize, is it a valid scenario for the framework to occupy ~500 MB in the temporary storage? If yes, any specific packages/areas to point out to, which consume this kind of storage in \tmp? Reason behind this question is that my lambda still has ~700MB memory left to use and still observe this behavior.

**Comment by davidfowl** [comment]
Lots of concurrent users might cause you to go over that limit even if the file is deleted after the upload. Other than that, I'm not aware of what else might leave files in the tmp folder.

**Comment by ChSankalp** [comment]
File upload in our code functionality is very minimal (~1%) and going by the present use case, it does not happen regularly and concurrently. 

Concurrency is around 8-10 users and assuming newton soft clears out the buffer for every execution, as the each container/context serves only a single execution at a time, I am still doubtful if it is the concurrency that is causing the issue. 

When I hit the function (fetching file sizes of all the files and directories with sub-directories included), 
```
var temporaryDirectoryPath = Path.GetTempPath();
            DirectoryInfo rootDirectoryInfo = new DirectoryInfo(temporaryDirectoryPath);
            var fileInfos = rootDirectoryInfo.EnumerateFiles(
                "*.*", SearchOption.AllDirectories).Select(
                x => new { x.FullName, x.Length, x.CreationTime, x.LastAccessTime, x.LastWriteTime });
            return JsonConvert.SerializeObject(fileInfos);
```
I get the below response:
```
[
  {
    "FullName": "/tmp/dotnet-diagnostic-8-477022-socket",
    "Length": 0,
    "CreationTime": "2023-03-31T10:07:20.2759677+00:00",
    "LastAccessTime": "2023-03-31T10:07:20.2759677+00:00",
    "LastWriteTime": "2023-03-31T10:07:20.2759677+00:00"
  },
  {
    "FullName": "/tmp/core..NET Sockets.8",
    "Length": 628539392,
    "CreationTime": "2023-03-31T10:07:20.0679677+00:00",
    "LastAccessTime": "2023-03-31T10:07:19.1839677+00:00",
    "LastWriteTime": "2023-03-31T10:07:20.0679677+00:00"
  },
  {
    "FullName": "/tmp/clr-debug-pipe-8-477022-out",
    "Length": 0,
    "CreationTime": "2023-03-31T10:07:20.2799677+00:00",
    "LastAccessTime": "2023-03-31T10:07:20.2799677+00:00",
    "LastWriteTime": "2023-03-31T10:07:20.2799677+00:00"
  },
  {
    "FullName": "/tmp/clr-debug-pipe-8-477022-in",
    "Length": 0,
    "CreationTime": "2023-03-31T10:07:20.2799677+00:00",
    "LastAccessTime": "2023-03-31T10:07:20.2799677+00:00",
    "LastWriteTime": "2023-03-31T10:07:20.2799677+00:00"
  }
]
```
Observation is that a single file is taking up this space from above findings.

The formatter is unable to get space for it's operation, but I am still skeptical if it is newton soft json formatter that is occupying this huge space at first place. 

I agree that the workaround suggested will be a clearing for the formatter to not use \tmp and therefore not occur at this error (with performance impact), is there any way to find out what is taking up this space, as the name of file also suggests that the framework might be using the space?

**Comment by davidfowl** [comment]
Those are unix domain sockets related to the diagnostics subsystem. 

cc @noahfalk @tommcdon

**Comment by davidfowl** [comment]
> File upload in our code functionality is very minimal (~1%) and going by the present use case, it does not happen regularly and concurrently.

It's not about file uploads, it's about the buffering to disk that the newtonsoft provider does for *any* JSON request or response that is above the certain threshold.

**Comment by ChSankalp** [comment]
> Those are unix domain sockets related to the diagnostics subsystem

Is there anyway to mitigate this as our available temporary storage is 512MB for each container/context? If the diagnostics sub-sytem occupies almost all of the memory, the effective space available would be very much limited for us to use.

**Comment by ChSankalp** [comment]
Also, what is the maximum memory that domain sockets can use and is it configurable?

**Comment by noahfalk** [comment]
"/tmp/dotnet-diagnostic-8-477022-socket", "/tmp/clr-debug-pipe-8-477022-out", and "/tmp/clr-debug-pipe-8-477022-in" are created by the runtime, but given they are 0-length pipes and unix domain sockets I doubt they have any relation to the problem.


"/tmp/core..NET Sockets.8" has a naming scheme I don't recognize and I'm not aware of anything in the runtime diagnostics code that would be creating such a file by default. One guess is that the 'core' in the name might refer to a Linux [core dump](https://linux-audit.com/understand-and-configure-core-dumps-work-on-linux/). The .NET runtime does support [creating a core dump file](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/collect-dumps-crash) when an app crashes, but it requires the user to opt-in via environment variable and the filename would be different unless that had also been customized.

**Comment by davidfowl** [comment]
@stephentoub does that pattern ("/tmp/core..NET Sockets.8") look like anything familiar to you?

**Comment by stephentoub** [comment]
This issue title mentions AWS Lambda, and I see this naming format mentioned by others running on AWS Lambda, eg https://stackoverflow.com/questions/76063569/how-to-disable-core-dumps-in-aws-lambda, so it's likely configured this naming/location/policy around dump creation.

**Comment by normj** [comment]
We have a support ticket for this issue which I'm guessing @ChSankalp is involved with. Our assumption based on the stacktrace was the Newtonsoft formatter was misbehaving some how and not cleaning up after itself in some circumstances. From a concurrency point of there is only one request being run at a time within a Lambda process. Lambda is all about horizontal scaling and spins up many different compute containers to handle the incoming requests.

The possibility of a core dump being triggered is really interesting. Looking at the configuration environments variables that @noahfalk pointed to we are not setting any of those and I doubt @ChSankalp is either. Is there anything else that would trigger a core dump?

**Comment by noahfalk** [comment]
> Is there anything else that would trigger a core dump?

There are APIs that can be invoked like [DiagnosticsClient.WriteDumpAsync](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/microsoft-diagnostics-netcore-client), tools like dotnet-monitor, dotnet-dump, ProcDumpForLinux, or the Linux kernel's dump creation on process termination. Before we go too far down this path I hope @ChSankalp (or someone else with access?) can check whether the file actually is a core dump. This could be done by trying to load it in a debugger or inspecting the first few bytes (core dumps have an ELF header similar to Linux binaries).

**Comment by normj** [comment]
It won't be easy for @ChSankalp to capture the file because this is running in a closed environment that could be replaced within minutes of invocation. 

Off the top of my head I think you would need to add middleware to the ASP.NET Core request pipeline that catches these exceptions. If it detects the error then upload the contents on the `/tmp` folder to S3 using the AWS .NET SDK. Then you can download the content from S3 when it happens and inspect what got uploaded. You also need to finish the upload of S3 before the Lambda function times out so you would need to increase the timeout on the Lambda function. If there is a better way then using middleware to trap the exception please add on to the idea.

**Comment by noahfalk** [comment]
> It won't be easy for @ChSankalp to capture the file because this is running in a closed environment that could be replaced within minutes of invocation.

If @ChSankalp can modify the code he used to do the enumeration so that it also prints the first 4 bytes of the file content we can improve our confidence on what it is. core dump files start with a standard ELF header.

**Comment by ChSankalp** [comment]
@noahfalk Problem here is that the issue is intermittently reproducible on production environment, and I cannot introduce code to read the file contents.

@normj As the Lambda containers ultimately run on Linux agents, is there a way to check if the core dumping is enabled in these agents?

**Comment by ChSankalp** [comment]
We have enabled the ```tmp_used``` metric for our lambda function and we are seeing around 550MB of consumption whenever this error occurs.

**Comment by normj** [comment]
@ChSankalp From my understanding above core dump is enabled via environment variables so you can always check for those environment variables in your Lambda function code. For extra context here is the shell script that starts up the .NET runtime. https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.RuntimeSupport/bootstrap.sh
