### ISSUE TITLE
HttpClient Timeout in Docker, http endpoint (not https)

### ISSUE THREAD

**Issue by ionut-gheorghe** [dotnet/aspnetcore#48150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is no timeout when running in windows. 
With the dockerize app (the deafult generated Dockerfile) the httpclient throws a timeout when the call is made to http endpoint. Works ok with https endpoint

![image](https://github.com/dotnet/aspnetcore/assets/54311614/f3cdd75b-789d-4e2a-9b98-72a875c6227a)

What am I missing? Is there any specific configuration for docker?

### Steps To Reproduce

var x = await new HttpClient().GetAsync("https://reqbin.com/echo");
var y = await new HttpClient().GetAsync("http://reqbin.com/echo");

### Exceptions (if any)

System.Threading.Tasks.TaskCanceledException
  HResult=0x8013153B
  Message=The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
  Source=System.Net.Http
  StackTrace:
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<<SendAsync>g__Core|83_0>d.MoveNext()
   at ...

Inner Exception 1:
TimeoutException: The operation was canceled.

Inner Exception 2:
TaskCanceledException: The operation was canceled.

Inner Exception 3:
IOException: Unable to read data from the transport connection: Operation canceled.

Inner Exception 4:
SocketException: Operation canceled

### .NET Version

7.0.203

### Anything else?

SDK DE .NET:
 Version:   7.0.203
 Commit:    5b005c19f5

Entorno de tiempo de ejecución:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.203\

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  7.0.203 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by ionut-gheorghe** [comment]
1. Http running inside the container and  http://reqbin.com/echo is the external resource (tried with another resource on local network). While running in windows no problems, running in container timeout
2. Dont know
