### ISSUE TITLE
Could not load file or assembly 'Microsoft.AspNetCore.Diagnostics.Abstractions' with .net 7.0.5

### ISSUE THREAD

**Issue by tygore587** [dotnet/aspnetcore#48209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We are experiencing a problem with our .net mvc api running in service fabric which is getting the error `Could not load file or assembly 'Microsoft.AspNetCore.Diagnostics.Abstractions`.

I search for other bugs and found the issue #3252 and searched for direct package references in our project, but found none.

We deploy the api as a self contained package, so the host runtime shouldn't matter.

### Expected Behavior

Not seeing an error

### Steps To Reproduce

Can't reproduce the problem yet by myself.

### Exceptions (if any)

```
Could not load file or assembly 'Microsoft.AspNetCore.Diagnostics.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
Type: System.IO.FileNotFoundException
File not found: Microsoft.AspNetCore.Diagnostics.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
Stack Trace: at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.HandleException(HttpContext context, ExceptionDispatchInfo edi)
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.HandleException(HttpContext context, ExceptionDispatchInfo edi)
at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|8_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
at Microsoft.AspNetCore.Server.HttpSys.RequestContext`1.ExecuteAsync()
at Microsoft.AspNetCore.Server.HttpSys.RequestContext`1.ExecuteAsync()
```

### .NET Version

7.0.203

**Comment by tygore587** [comment]
We had another error where `Microsoft.CSharp` was directly referenced. We removed it and reployed and the error is gone for now. I will close this issue as we are experiencing the problem anymore at the moment.

I will reopen or create a new one if it is a problem again.

**Comment by tygore587** [comment]
I will reopen the issue, because it happened again and we don't see a reason for this to happen. It also never happened on .net 6, just started after upgrading to .net 7.

**Comment by tygore587** [comment]
Sorry reopned it on runtime repo.
