### ISSUE TITLE
Quarantine ResponseCachingMiddlewareTests.FinalizeCacheHeadersAsync_ResponseValidity_UseExpiryIfAvailable

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#48373]
## Failing Test(s)

`Microsoft.AspNetCore.ResponseCaching.Tests.ResponseCachingMiddlewareTests.FinalizeCacheHeadersAsync_ResponseValidity_UseExpiryIfAvailable`

## Error Message

```text
System.ArgumentOutOfRangeException : Hour, Minute, and Second parameters describe an un-representable DateTime.
```

## Stacktrace

<details>

```text
System.ArgumentOutOfRangeException : Hour, Minute, and Second parameters describe an un-representable DateTime.
   at System.DateTimeOffset..ctor(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second, TimeSpan offset)
   at Microsoft.AspNetCore.ResponseCaching.Tests.ResponseCachingMiddlewareTests.FinalizeCacheHeadersAsync_ResponseValidity_UseExpiryIfAvailable() in /_/src/Middleware/ResponseCaching/test/ResponseCachingMiddlewareTests.cs:line 448
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```
</details>

## Logs

[console.01cbc393.txt](https://github.com/dotnet/aspnetcore/files/11538038/console.01cbc393.txt)

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=282645&view=ms.vss-test-web.build-test-results-tab&runId=5621996&resultId=119723&paneView=debug

**Comment by Tratcher** [comment]
https://github.com/dotnet/aspnetcore/blob/39564d529f84f7a3bbac5b28ba11060e8ac30375/src/Middleware/ResponseCaching/test/ResponseCachingMiddlewareTests.cs#L447-L448C8

It rounded up by 1 second and became invalid?
