### ISSUE TITLE
`UserManager.AddClaimsAsync` keeps throwing duplicate PK exception for new claims

### ISSUE THREAD

**Issue by khteh** [dotnet/aspnetcore#48556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The following code snippet:
```
                    Claim claim = claims.FirstOrDefault(c => c.Type == "roles");
                    if (claim != null)
                        await _userManager.RemoveClaimAsync(appUser, claim);
                    StringBuilder sb = new StringBuilder();
                    if (claim != null && !string.IsNullOrEmpty(claim.Value) && !claim.Value.Contains("buyer"))
                        sb.Append($"{claim.Value} buyer");
                    else
                        sb.Append("buyer");
                    try
                    {
                        await _userManager.AddClaimAsync(appUser, new Claim("roles", sb.ToString()));
                    }
                    catch (Exception e)
                    {
                        _logger.LogError($"{nameof(CreateOrUpdateUser)} Exception! {e}");
                    }
```
keeps throwing the exception. I have checked the DB this user does NOT have `roles` claim at all

### Expected Behavior

Successfully added new claim to the user.

### Exceptions (if any)

```
"23505: duplicate key value violates unique constraint \"PK_AspNetUserClaims\"\n\nDETAIL: Key (\"Id\")=(6532) already exists."
```

### .NET Version

7.0.105

**Comment by martincostello** [comment]
Looking at the exception message, it seems like the constraint is complaining about the primary key itself, rather than the value of the claim itself.

Have you done anything to customise the database schema for the underlying store where you keep your data?

**Comment by khteh** [comment]
I didn't customize the schema. It consists of `Id`, `UserId`, `ClaimType` and `ClaimValue` columns. Is this the original schema?

**Comment by martincostello** [comment]
Searching for `PK_AspNetUserClaims` in the repo code comes up with migrations that look like this:

https://github.com/dotnet/aspnetcore/blob/be14dda052a54373e542a9978f172d1900f15486/src/Identity/samples/IdentitySample.Mvc/Data/Migrations/00000000000000_CreateIdentitySchema.cs#L97-L106

This seems to suggest its failing to insert a row with _any_ content in the `AspNetUserClaims` table because there's already a row with a primary key of `6532`.

If you do a SQL select for that on your database does it find anything? I haven't tested this query, so might not be 100% correct:

```sql
select * from AspNetUserClaims where Id = 6532;
```

Feels like something's off with the auto-incrementing ID for that table on your database/code causing it to incorrectly try and add a duplicate.

**Comment by khteh** [comment]
Yes, that's right. There are records at that Id >= 6532

**Comment by mkArtakMSFT** [comment]
Thanks for helping with this investigation, @martincostello!
@khteh was @martincostello's last response help you with identifying the problem, or is there more you need help with?

**Comment by khteh** [comment]
How did that happen?

**Comment by mkArtakMSFT** [comment]
@khteh based on the details share here it seems like your database got somehow corrupted or has some custom logic which interferes with primary-key auto-incrementing logic. In order for us to investigate this issue, please provide [a minimalistic repro project](https://github.com/dotnet/aspnetcore/blob/main/docs/repro.md) that illustrates the problem.

**Comment by khteh** [comment]
How does the primary-key auto-increment work? Doesn't it just take the last value in the table and increment and use that? How could this simple integer primary key auto-increment mess up?

**Comment by mkArtakMSFT** [comment]
@ajcvickers any suggestions regarding the database behavior here?

**Comment by mkArtakMSFT** [comment]
@ajcvickers the problem is that their code does call the `RemoveClaimAsync` before trying to add a new one (look at line 3 in their original sample). Shouldn't that work?

**Comment by ajcvickers** [comment]
@mkArtakMSFT I don't remember enough about how `AddClaim` and `RemoveClaim` work to know for sure, but it may not work depending on how the user manager is implemented.

**Comment by pollux** [comment]
I have encountered a similar issue. Instead of adding one claim I am trying to add multiple claims through `UserManager.AddClaimsAsync(identityUser, [ ... ]);`

The code part that is responsible for the exception:
```csharp
                if (validUser)
                {
                    await _identitySignInManager.SignInAsync(identityUser, remember);

                    if (......)
                    {
                        try
                        {
                            await _identityUserManager.AddClaimsAsync(identityUser, [
                                new(ClaimNames.X, valueA),
                                new(ClaimNames.Y, valueB)
                            ]);
                        }
                        catch (Exception ex)
                        {
                            // DbUpdateException - see stacktrace below
                        }
                    }
                }
```

The exception with its stacktrace is as follows:
```
fail: 12/17/2024 15:48:59.582 CoreEventId.SaveChangesFailed[10000] (Microsoft.EntityFrameworkCore.Update) 
      An exception occurred in the database while saving changes for context type 'Repository.TenantDBContext'.
      Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
       ---> Npgsql.PostgresException (0x80004005): 23505: duplicate key value violates unique constraint "ix_asp_net_user_claims_user_id"

      DETAIL: Key (user_id)=(56037044-4bab-43db-8dd2-163dbf991e2e) already exists.
         at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
         at Npgsql.EntityFrameworkCore.PostgreSQL.Update.Internal.NpgsqlModificationCommandBatch.Consume(RelationalDataReader reader, Boolean async, CancellationToken cancellationToken)
        Exception data:
          Severity: ERROR
          SqlState: 23505
          MessageText: duplicate key value violates unique constraint "ix_asp_net_user_claims_user_id"
          Detail: Key (user_id)=(56037044-4bab-43db-8dd2-163dbf991e2e) already exists.
          SchemaName: public
          TableName: asp_net_user_claims
          ConstraintName: ix_asp_net_user_claims_user_id
          File: nbtinsert.c
          Line: 666
          Routine: _bt_check_unique
         --- End of inner exception stack trace ---
         at Npgsql.EntityFrameworkCore.PostgreSQL.Update.Internal.NpgsqlModificationCommandBatch.Consume(RelationalDataReader reader, Boolean async, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
         at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
```

The database table is empty though. And it looks like the exception occurs on adding the second of the entries (`ClaimNames.Y`) in the passed List, when SaveChanges() is called.

How do I go about adding multiple custom claims?
