### ISSUE TITLE
DirectoryNotFoundException when setting a custom WebRoot at runtime

### ISSUE THREAD

**Issue by manio143** [dotnet/aspnetcore#48620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a custom build setup for my static frontend assets. The compiled frontend assets live in a directory outside of the solution and are being included in `<Content>` in the csproj in a target dynamically, then being copied over to `wwwroot` in the output directory.

For development from Visual Studio I have added a piece of code which changes the WebRoot to point at the folder with the compiled assets, so that I can recompile them without rebuilding the service.

```csharp
[Conditional("DEBUG")]
private static void ConfigureDevelopmentTimeWebRoot(IWebHostBuilder builder)
{
	if (Environment == Environments.Development)
		builder.UseWebRoot("../../frontend/dist");
}
```

If I put an empty `wwwroot` in the directory of my C# project it works. If I remove the `wwwroot` folder I get an exception while building the `WebHost`. Note that I'm using ASP.NET Core 7 with the old coding style `WebHost.CreateDefaultBuilder(args)` and enabling static files with `app.UseStaticFiles()` in the `builder.Configure((ctx, app) => {...})`.

Seems like `StaticWebAssetsLoader` finds a note somewhere (in some manifest) that it should look at `wwwroot` in the project folder, rather than respecting WebRoot setting.

I looked briefly in the sources and apparently there's a manifest file being generated in the `obj` folder `staticwebassets.development.json` which specifies those paths - is there some build properties I should be setting? I see in there a lot of files related to ASPNET Core Identity which are not actually present in my build output.

### Expected Behavior

No exception being thrown if the `wwwroot` doesn't exist.

### Exceptions (if any)

```
System.IO.DirectoryNotFoundException: '...\src\backend\ManagementHub.Service\wwwroot\'
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.<>c.<UseStaticWebAssetsCore>b__1_0(String contentRoot)
   at Microsoft.AspNetCore.StaticWebAssets.ManifestStaticWebAssetFileProvider..ctor(StaticWebAssetManifest manifest, Func`2 fileProviderFactory)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssetsCore(IWebHostEnvironment environment, Stream manifest)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.UseStaticWebAssets(IWebHostEnvironment environment, IConfiguration configuration)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at ManagementHub.Service.Program.Main(String[] args) in Program.cs:line 53
```

### .NET Version

7.0.302

**Comment by QINGCHARLES** [comment]
So, just to be clear, the OP is saying that even if he defines a custom `wwwroot` folder the framework _still_ requires the default `wwwroot` folder to exist in the root folder of the project. i.e. the path is probably hardcoded somewhere in the framework.
