### ISSUE TITLE
HubProtocolVersionTests.ClientUsingOldCallWithNewProtocol is flaky

### ISSUE THREAD

**Issue by amcasey** [dotnet/aspnetcore#48733]
## Failing Test(s)

- Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubProtocolVersionTests.ClientUsingOldCallWithNewProtocol

## Error Message

```text
Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager - ExceptionOccurredWhileProcessingTheKeyElement - An exception occurred while processing the key element '<key id="bd050079-a753-459c-ad1f-64f80d26a6f1" version="1" />'.

```

## Stacktrace

<details>

```text
System.Security.Cryptography.CryptographicException: Unable to retrieve the decryption key.
   at System.Security.Cryptography.Xml.EncryptedXml.GetDecryptionKey(EncryptedData encryptedData, String symmetricAlgorithmUri)
   at System.Security.Cryptography.Xml.EncryptedXml.DecryptDocument()
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.EncryptedXmlDecryptor.Decrypt(XElement encryptedElement) in /_/src/DataProtection/DataProtection/src/XmlEncryption/EncryptedXmlDecryptor.cs:line 75
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.XmlEncryptionExtensions.DecryptElement(XElement element, IActivator activator) in /_/src/DataProtection/DataProtection/src/XmlEncryption/XmlEncryptionExtensions.cs:line 51
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.DeserializeDescriptorFromKeyElement(XElement keyElement) in /_/src/DataProtection/DataProtection/src/KeyManagement/XmlKeyManager.cs:line 445
   at Microsoft.AspNetCore.DataProtection.KeyManagement.DeferredKey.<>c__DisplayClass1_0.<GetLazyDescriptorDelegate>g__GetLazyDescriptorDelegate|0() in /_/src/DataProtection/DataProtection/src/KeyManagement/DeferredKey.cs:line 57
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyBase.get_Descriptor() in /_/src/DataProtection/DataProtection/src/KeyManagement/KeyBase.cs:line 51
   at Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.CngGcmAuthenticatedEncryptorFactory.CreateEncryptorInstance(IKey key) in /_/src/DataProtection/DataProtection/src/AuthenticatedEncryption/CngGcmAuthenticatedEncryptorFactory.cs:line 38
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyBase.CreateEncryptor() in /_/src/DataProtection/DataProtection/src/KeyManagement/KeyBase.cs:line 59
   at Microsoft.AspNetCore.DataProtection.KeyManagement.DefaultKeyResolver.CanCreateAuthenticatedEncryptor(IKey key) in /_/src/DataProtection/DataProtection/src/KeyManagement/DefaultKeyResolver.cs:line 59
===================
Stack Trace:
  D:\a\_work\1\s\src\Shared\SignalR\VerifyNoErrorScope.cs(47,0): at Microsoft.AspNetCore.SignalR.Tests.VerifyNoErrorsScope.Dispose()
  D:\a\_work\1\s\src\Shared\SignalR\InProcessTestServer.cs(157,0): at Microsoft.AspNetCore.SignalR.Tests.InProcessTestServer`1.DisposeAsync()
  D:\a\_work\1\s\src\Shared\SignalR\InProcessTestServer.cs(164,0): at Microsoft.AspNetCore.SignalR.Tests.InProcessTestServer`1.DisposeAsync()
  /_/src/SignalR/clients/csharp/Client/test/FunctionalTests/HubProtocolVersionTests.cs(96,0): at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubProtocolVersionTests.ClientUsingOldCallWithNewProtocol(HttpTransportType transportType)
  --- End of stack trace from previous location ---
```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=302221&view=logs&j=3f6d4e0f-1b71-56b5-361e-d95b6e6da15a&t=e4ee6667-9b0a-5a6e-4e24-bcba939f2af2&l=246

**Comment by amcasey** [comment]
Added to retry list, rather than quarantining.
https://github.com/dotnet/aspnetcore/pull/48730

**Comment by amcasey** [comment]
Probable fix: https://github.com/dotnet/aspnetcore/pull/48730#issuecomment-1587846712

**Comment by mitchdenny** [comment]
Test seems to be OK after being added to the retry list.

**Comment by BrennanConroy** [comment]
Don't close the issue. We want to track removing the test from the retry list.

**Comment by BrennanConroy** [comment]
Unquarantined with https://github.com/dotnet/aspnetcore/pull/51079
