### ISSUE TITLE
KestrelConfigurationLoaderTests.ConfigureEndpointDevelopmentCertificateGetsLoadedWhenPresent is flaky

### ISSUE THREAD

**Issue by amcasey** [dotnet/aspnetcore#48736]
## Failing Test(s)

- Microsoft.AspNetCore.Server.Kestrel.Tests.KestrelConfigurationLoaderTests.ConfigureEndpointDevelopmentCertificateGetsLoadedWhenPresent

## Error Message

```text
System.Security.Cryptography.CryptographicException : Key not valid for use in specified state.
```

## Stacktrace

<details>

```text
System.Security.Cryptography.CryptographicException : Key not valid for use in specified state.
  at System.Security.Cryptography.X509Certificates.StorePal.Export(X509ContentType contentType, SafePasswordHandle password)
  at System.Security.Cryptography.X509Certificates.CertificatePal.Export(X509ContentType contentType, SafePasswordHandle password)
  at System.Security.Cryptography.X509Certificates.X509Certificate.Export(X509ContentType contentType, String password)
  at Microsoft.AspNetCore.Server.Kestrel.Tests.KestrelConfigurationLoaderTests.ConfigureEndpointDevelopmentCertificateGetsLoadedWhenPresent() in /_/src/Servers/Kestrel/Kestrel/test/KestrelConfigurationLoaderTests.cs:line 248
  at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
  at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=303767&view=results

**Comment by amcasey** [comment]
From wfurt: https://github.com/dotnet/aspnetcore-internal/issues/4310#issuecomment-1587883100
