### ISSUE TITLE
RenderModeServer doesn't work when applied to App component

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#48793]
Repro steps:

- Install .NET 8 Preview 5
- Create a Blazor Web App
- Enable server interactivity by adding `AddServerComponents()`
- Add `@attribute [RenderModeServer]` to the `App` component

Expected result: The entire app renders interactively using Blazor Server
Actual result:

```
Uncaught (in promise) Error: Found malformed component comment at Blazor:{"sequence":0,"type":"server","prerenderId":"40b364ab2f6c4a128a60a3540610ab4b","descriptor":"CfDJ8F4wj4CPUDJJpKiv/dArKQrAAIXkDXV447RobZzMe9NoVPi13ySUCzRMCnR\u002BuG2VqaE7yhBykOgcr6Wv5VC6uuA58dahIttUOgLWTTZNR0rPCAldAYQJQmdu3qO6mdkHr6KKBRbe9udw9hI27AgCHp087lrYE81BmVVk2dv0SihheePH8aPqh/VtKhsgUwS6WA0FFiCuvHZoZb2hKz4HBIFpp7dbjMHL75GhCz5tjZczoJEZm2o\u002BV/EJWrwQJD0f05t8oMehODNNSu0svvsx\u002BZ5IBUF5WBuRSqH8cpKmoV2mMMvZm1PI6F\u002BCNBrl2leG0GnSp1zF/U9GkVN0GleOFDkSpa0T8kdNfLX198A7er7V"}
    at vr (blazor.web.js:1:131254)
    at yr (blazor.web.js:1:129626)
    at blazor.web.js:1:128924
    at fr (blazor.web.js:1:129096)
    at blazor.web.js:1:148075
    at Co (blazor.web.js:1:153116)
    at blazor.web.js:1:153281
    at blazor.web.js:1:153287
```

**Comment by SteveSandersonMS** [comment]
I investigated and found there are several issue contributing to this, all of which are in the JS code:

### 1. It tries to start up before the whole document is loaded

Because `Blazor.start` runs synchronously, it happens as soon as the `<script>` tag appears in the page, before the rest of the document is loaded. This means it runs before the closing marker tag has been added, hence there's an error saying the component comment is malformed.

Solution: We need `blazor.web.js` to defer startup until documentready. This must be the case whether or not people use autostart or call `Blazor.start` manually (i.e., we must wait for documentready either way).

### 2. It does not realise it can insert any content into `document`

The `BrowserRenderer` logic knows about adding content to various element types but doesn't know about nodes of type `Document`, so it can't add things at the true top level of the document.

Solution: In `LogicalElement.ts`, we should change as follows:

```diff
-  if (parent instanceof Element || parent instanceof DocumentFragment) {
+  if (parent instanceof Element || parent instanceof DocumentFragment || parent instanceof Document) {
```

... or perhaps there is some other common type we could check for that represents "all things into which you can `appendChild`". Maybe we just check for `appendChild` existing on `parent`.

### 3. It then tries to insert markup as a direct child of `document`

It's not legal to insert a text node as a direct child of the document element. But in general people's top-level components will include whitespace around the `<html>` and so on, even if only for linebreaks. So it will fail trying to insert a text node.

Solution: In `BrowserRenderer`'s `insertMarkup`, we could explicitly check, e.g.:

```ts
if (parent instanceof Comment && parent.parentNode instanceof Document) {
    ...
}
```

... and in this case, maybe insert a comment node instead, since we know there's no real content to insert here and we just want a placeholder to ensure the sibling IDs remain correct.

**Comment by SteveSandersonMS** [comment]
I've realised this is likely not going to be possible. I [did implement it](https://github.com/dotnet/aspnetcore/pull/48942), but in doing so discovered that it's too dangerous.

The problem is:

 * Being interactive at the root, with prerendering, implies the content has to switch from being static to being interactive
 * ... which means we'll remove all the content and re-add it
 * ... which means we'll remove and re-add any `<script>` elements
 * ... which means they will re-run and typically break or cause undefined behavior (for example, `blazor.web.js` immediately throws if you do this, and while we could make our own JS file hardened against it, we can't make all 3rd-party code compatible with this pattern)

I think for the forseeable future, maybe forever, it will be necessary for the top-level host to be static as a place where you can safely put things like `<script>` knowing they will only run once. This leads to two further requirements:

 * We should extend https://github.com/dotnet/aspnetcore/issues/48847 so it gives an error if the root has any nonstatic rendermode. Might be possible to do that for preview 6.
 * Obviously this gives an even stronger reason to want to bring back the callsite rendermodes feature. It now seems like a clear misstep to think we should remove that. I'm not saying we can necessarily do that in .NET 8 but am starting to wonder if it's worth trying (and perhaps pushing out something else for).

cc @danroth27 @javiercn for any thoughts they may have.

**Comment by javiercn** [comment]
@SteveSandersonMS we need to have an alternative to Blazor Server if we plan to remove the template.

What do you think is the best way to achieve that?

**Comment by SteveSandersonMS** [comment]
Have a `Host.razor` (static) and `App.razor` (server)

**Comment by javiercn** [comment]
@SteveSandersonMS that sounds reasonable, we must at least document that, though.

**Comment by danroth27** [comment]
> Obviously this gives an even stronger reason to want to bring back the callsite rendermodes feature. It now seems like a clear misstep to think we should remove that. I'm not saying we can necessarily do that in .NET 8 but am starting to wonder if it's worth trying (and perhaps pushing out something else for).

@mkArtakMSFT We should discuss this.

**Comment by SteveSandersonMS** [comment]
If we are open to doing this for the RC1 release it *might* be possible to fit in.

I did already implement this pretty much fully ([here's the commit where it was pulled out](https://github.com/dotnet/aspnetcore/pull/48948/commits/4be0398d67aa17e3232c707e634d8eab1630ab0b)), so even though it's nontrivial, we do largely understand what's involved and have a near-production-ready implementation. It's not just a matter of `git revert` because the codebase will have diverged in many ways already and we still have to add E2E tests.
