### ISSUE TITLE
GetAuthenticationStateAsync was called before SetAuthenticationState.

### ISSUE THREAD

**Issue by ThinkElevenDave** [dotnet/aspnetcore#48806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This was previously posted [here ](https://github.com/dotnet/aspnetcore/issues/28684) and [here](https://github.com/dotnet/aspnetcore/issues/17442) but closed due to inactivity or a lack of a repro.  Neither post appears to provide the clarity needed, so hopefully what follows will be helpful.

In a Blazor app (Net 8 preview), to avoid using `IHttpContextAccessor` we create an authentication cookie in a razor page, then redirect back to Blazor. Within the Blazor app we need to use a Controller method to retrieve an image from an external source and return it in the browser.  This is to provide security and caching.  Also, Blazor pages also need to access the claims.

Therefore we have created a service that uses `AuthenticationStateProvider`.  The Blazor pages retrieve the claim value just fine, but the controller that uses the same service throws an exception that comes from the underlying `AuthenticationStateProvider`. 

We are trying to understand why this exception occurs when the service is called from the Controller but does not occur when called from the Blazor page?

A full repro with step-by-step instructions is here:
https://github.com/ThinkElevenDave/NetCoreAuthStateErrorRepro

Note - I am new to Core so I only know what I can find online!  Please be nice 🙄

### Expected Behavior

The controller should use the injected service to read the cookie claim value, then return an image.

### Steps To Reproduce

Run the project and follow the steps on-screen.
The image never loads on the final page.  Debugging the controller try/catch catches the inner exception.

### Exceptions (if any)

"GetAuthenticationStateAsync was called before SetAuthenticationState."
   at Microsoft.AspNetCore.Components.Server.ServerAuthenticationStateProvider.GetAuthenticationStateAsync()
   at Services.MyService.<GetNameClaimValue>d__2.MoveNext() in BlazorApp1\Services\MyService.cs:line 18
   at BlazorApp1.Controllers.ValuesController.<TestAsync>d__2.MoveNext() in BlazorApp1\BlazorApp1\Controllers\ValuesController.cs:line 24

### .NET Version

8

### Anything else?

v8 preview
VS Version 17.7.0 Preview 1.0

```
.NET SDK:
 Version:   8.0.100-preview.3.23178.7
 Commit:    e300b0e1e6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-preview.3.23174.8
  Architecture: x64
  Commit:       47bad717bd

.NET SDKs installed:
  7.0.302 [C:\Program Files\dotnet\sdk]
  7.0.400-preview.23225.8 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.3.23178.7 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.3.23177.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.3.23174.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.3.23178.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  arm64 [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\arm64\InstallLocation]
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found
```

**Comment by halter73** [comment]
Here's a PR to try to improve the exception message: https://github.com/dotnet/aspnetcore/pull/48812
