### ISSUE TITLE
Failed to load assembly 'Microsoft.AspNetCore.Mvc.RazorPages'

### ISSUE THREAD

**Issue by jacksonlancaster** [dotnet/aspnetcore#48923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Unable to publish a Blazor server app using AOT

The error is
`Failed to load assembly 'Microsoft.AspNetCore.Mvc.RazorPages'`

I found a reference to 'Microsoft.AspNetCore.Mvc.RazorPages in the default Error.cshtml file.
I removed this file, and the code behind from my project.
I could not find any other references to Microsoft.AspNetCore.Mvc.RazorPages in my project.
But I still receive the same error.

### Expected Behavior

AOT can compile with no errors

### .NET Version

7.0.304

**Comment by jacksonlancaster** [comment]
`Test_BlazorApp -> C:\Users\Jackson\Documents\Visual Studio 2022\Projects\AtomTech_Part_Tracking\Test_BlazorApp\bin\Release\net7.0\win-x64\Test_BlazorApp.dll
"C:\Program Files\dotnet\sdk\7.0.304\Sdks\Microsoft.DotNet.ILCompiler\build\findvcvarsall.bat" x64
Generating native code
"C:\Users\Jackson\.nuget\packages\runtime.win-x64.microsoft.dotnet.ilcompiler\7.0.7\tools\\ilc" @"obj\Release\net7.0\win-x64\native\Test_BlazorApp.ilc.rsp"
EXEC(0,0): Error : Failed to load assembly 'Microsoft.AspNetCore.Mvc.RazorPages'
Internal.TypeSystem.TypeSystemException+FileNotFoundException: Failed to load assembly 'Microsoft.AspNetCore.Mvc.RazorPages'
   at Internal.TypeSystem.ThrowHelper.ThrowFileNotFoundException(ExceptionStringID, String) in /_/src/coreclr/tools/Common/TypeSystem/Common/ThrowHelper.cs:line 35
   at Internal.TypeSystem.ResolutionFailure.Throw() in /_/src/coreclr/tools/Common/TypeSystem/Common/ResolutionFailure.cs:line 105
   at Internal.TypeSystem.Ecma.EcmaModule.GetType(EntityHandle) in /_/src/coreclr/tools/Common/TypeSystem/Ecma/EcmaModule.cs:line 354
   at Internal.TypeSystem.Ecma.EcmaType.InitializeBaseType() in /_/src/coreclr/tools/Common/TypeSystem/Ecma/EcmaType.cs:line 164
   at Internal.TypeSystem.Ecma.EcmaType.ComputeTypeFlags(TypeFlags) in /_/src/coreclr/tools/Common/TypeSystem/Ecma/EcmaType.cs:line 200
   at Internal.TypeSystem.TypeDesc.InitializeTypeFlags(TypeFlags) in /_/src/coreclr/tools/Common/TypeSystem/Common/TypeDesc.cs:line 135
   at ILCompiler.DependencyAnalysis.TypeMetadataNode.GetStaticDependencies(NodeFactory) in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/DependencyAnalysis/TypeMetadataNode.cs:line 48
   at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependenciesImpl(DependencyNodeCore`1) in /_/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 181
   at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependencies(DependencyNodeCore`1) in /_/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 221
   at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ProcessMarkStack() in /_/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 256
   at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes() in /_/src/coreclr/tools/aot/ILCompiler.DependencyAnalysisFramework/DependencyAnalyzer.cs:line 307
   at ILCompiler.ILScanner.ILCompiler.IILScanner.Scan() in /_/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/ILScanner.cs:line 140
   at ILCompiler.Program.<Run>g__RunScanner|73_4(<>c__DisplayClass73_0&) in /_/src/coreclr/tools/aot/ILCompiler/Program.cs:line 884
   at ILCompiler.Program.Run(String[]) in /_/src/coreclr/tools/aot/ILCompiler/Program.cs:line 866
   at ILCompiler.Program.Main(String[]) in /_/src/coreclr/tools/aot/ILCompiler/Program.cs:line 1150
C:\Program Files\dotnet\sdk\7.0.304\Sdks\Microsoft.DotNet.ILCompiler\build\Microsoft.NETCore.Native.targets(278,5): Error MSB3073: The command ""C:\Users\Jackson\.nuget\packages\runtime.win-x64.microsoft.dotnet.ilcompiler\7.0.7\tools\\ilc" @"obj\Release\net7.0\win-x64\native\Test_BlazorApp.ilc.rsp"" exited with code 1.

2>Build failed. Check the Output window for more details.
========== Build: 1 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
========== Build started at 4:59 PM and took 08.700 seconds ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========
========== Publish started at 4:59 PM and took 08.700 seconds ==========`

**Comment by javiercn** [comment]
@jacksonlancaster thanks for contacting us.

Blazor Server does not support AOT.
