### ISSUE TITLE
[dotnet-sdk-8.0.100-preview.6.23316.32] Blazor component property doesn't recognize [Parameter] attribute when setting [SupplyParameterFromQuery] attribute together

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/aspnetcore#48937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When run the 3rd party app against the latest .NET 8 Preview 6 build, start from dotnet-sdk-8.0.100-preview.6.23316.32, when a Blazor compont property using both [Parameter] attribute and [SupplyParameterFromQuery] attribute, application will crash with "Unhandled exception rendering component: Object of type '{ComponentName}' has a property matching the name 'Text', but it does not have [ParameterAttribute] applied." exception.

**Application Name**: BootstrapBlazor
**OS**： Windows 10 21H2
**CPU**: X64
**.NET Build Number**: dotnet-sdk-8.0.100-preview.6.23316.32
**App Github Link**: https://github.com/dotnetcore/BootstrapBlazor
**App & Source Location**: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1839677

**Verify Scenarios: **
1. Windows10 21h2 x64 + dotnet-sdk-8.0.100-preview.6.23320.1: Fail
2. Windows10 21h2 x64 + dotnet-sdk-8.0.100-preview.6.23316.32: Fail
3. Windows10 21h2 x64 + dotnet-sdk-8.0.100-preview.6.23312.5: Pass
4. Windows10 21h2 x64 + dotnet-sdk-7.0.107(default): Pass

### Expected Behavior

Counter page load successful with "Test Data: testvalue" diaplayed on the page.

### Steps To Reproduce

Minimal Repro steps (Demo attached): [BlazorApp2.zip](https://github.com/dotnet/aspnetcore/files/11814373/BlazorApp2.zip)

1. Create a default Blazor server project.

2. Add a TestComponent.razor file under Shared folder with following code:
```
 @page "/test"
<div>
    <span>Test Data :</span> <span>@Text</span>
    <br />
</div>
@code {
    [Parameter]
    [SupplyParameterFromQuery] //if we remove this attribute, it will work
    public string? Text { get; set; }
}
```
3. Add following highlight line of code in Counter.razor page:
```
<p role="status">Current count: @currentCount</p>
<TestComponent Text="testvalue"></TestComponent>
<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>
```
4. Build the project.

5. Change the runtime.config file to let the app run against with dotnet-sdk-8.0.100-preview.6.23316.32
 ```
"frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "8.0.0-preview.6.23316.3"
      },
      {
        "name": "Microsoft.AspNetCore.App",
        "version": "8.0.0-preview.6.23316.5"
      }
    ], 
```
6. Launch the demo app.
7. Click Counter page.

### Exceptions (if any)

**Counter page load failed with following stack trace:**
```
 Unhandled exception rendering component: Object of type 'BlazorApp2.Shared.TestComponent' has a property matching the name 'Text', but it does not have [ParameterAttribute] applied.
      System.InvalidOperationException: Object of type 'BlazorApp2.Shared.TestComponent' has a property matching the name 'Text', but it does not have [ParameterAttribute] applied.
         at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.ThrowForSettingCascadingParameterWithNonCascadingValue(Type targetType, String parameterName)
         at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)
         at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'r3zRfDbXCKtWWl5HgY-rIhkop6uqhszUu5CF9L6wgig'.
      System.InvalidOperationException: Object of type 'BlazorApp2.Shared.TestComponent' has a property matching the name 'Text', but it does not have [ParameterAttribute] applied.
         at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.ThrowForSettingCascadingParameterWithNonCascadingValue(Type targetType, String parameterName)
         at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)
         at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Cannot access a disposed object.
      System.ObjectDisposedException: Cannot access a disposed object.
         at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree, Dictionary`2 namedEventIndexes)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'r3zRfDbXCKtWWl5HgY-rIhkop6uqhszUu5CF9L6wgig'.
      System.ObjectDisposedException: Cannot access a disposed object.
         at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree, Dictionary`2 namedEventIndexes)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```
### .NET Version

8.0.100-preview.6.23316.32

@dotnet-actwx-bot @dotnet/compat

**Comment by Junjun-zhao** [comment]
Verified this issue on dotnet-sdk-8.0.100-preview.6.23328.9, it has been fixed. Thank you.
