### ISSUE TITLE
Quarantine WebSocket_Abort_Interrupts_Pending_ReceiveAsync

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#48933]
## Failing Test(s)

- Microsoft.AspNetCore.WebSockets.Test.WebSocketMiddlewareTests.WebSocket_Abort_Interrupts_Pending_ReceiveAsync

## Error Message

```text
Assert.True() Failure
Expected: True
Actual:   False
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.WebSockets.Test.WebSocketMiddlewareTests.<>c__DisplayClass16_0.<<WebSocket_Abort_Interrupts_Pending_ReceiveAsync>b__0>d.MoveNext() in /_/src/Middleware/WebSockets/test/UnitTests/WebSocketMiddlewareTests.cs:line 534
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.WebSockets.Test.KestrelWebSocketHelpers.<>c__DisplayClass0_0.<<CreateServer>b__5>d.MoveNext() in /_/src/Middleware/WebSockets/test/UnitTests/KestrelWebSocketHelpers.cs:line 30
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.WebSockets.Test.KestrelWebSocketHelpers.<>c__DisplayClass0_0.<<CreateServer>b__5>d.MoveNext() in /_/src/Middleware/WebSockets/test/UnitTests/KestrelWebSocketHelpers.cs:line 38
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application) in /_/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs:line 676
   at Microsoft.AspNetCore.WebSockets.Test.KestrelWebSocketHelpers.<>c__DisplayClass0_0.<<CreateServer>b__4>d.MoveNext() in /_/src/Middleware/WebSockets/test/UnitTests/KestrelWebSocketHelpers.cs:line 83
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.WebSockets.Test.WebSocketMiddlewareTests.WebSocket_Abort_Interrupts_Pending_ReceiveAsync() in /_/src/Middleware/WebSockets/test/UnitTests/WebSocketMiddlewareTests.cs:line 557
--- End of stack trace from previous location ---
```
</details>

## Logs

<details>

```text
[0.001s] [TestLifetime] [Information] Starting test WebSocket_Abort_Interrupts_Pending_ReceiveAsync at 2023-06-21T04:33:56
[0.003s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting starting
[0.009s] [Microsoft.Hosting.Lifetime] [Information] Now listening on: http://127.0.0.1:34187
[0.009s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Debug] Loaded hosting startup assembly Microsoft.AspNetCore.WebSockets.Tests
[0.010s] [Microsoft.Hosting.Lifetime] [Information] Application started. Press Ctrl+C to shut down.
[0.010s] [Microsoft.Hosting.Lifetime] [Information] Hosting environment: Production
[0.010s] [Microsoft.Hosting.Lifetime] [Information] Content root path: /datadisks/disk1/work/AB4B0982/w/ABC70966/e/
[0.010s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting started
[0.011s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMRI22SNQETN" accepted.
[0.011s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMRI22SNQETN" started.
[0.012s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request starting HTTP/1.1 GET http://127.0.0.1:34187/ - null null
[0.015s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Information] Connection id "0HMRI22SNQETN", Request id "0HMRI22SNQETN:00000001": the application aborted the connection.
[0.015s] [Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets] [Debug] Connection id "0HMRI22SNQETN" sending FIN because: "The connection was aborted by the application."
[0.015s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMRI22SNQETN" disconnecting.
[0.020s] [Microsoft.AspNetCore.Server.Kestrel] [Error] Connection id "0HMRI22SNQETN", Request id "0HMRI22SNQETN:00000001": An unhandled exception was thrown by the application.
Xunit.Sdk.TrueException: Assert.True() Failure
Expected: True
Actual:   False
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/xunit.assert/Asserts/BooleanAsserts.cs:line 132
   at Xunit.Assert.True(Boolean condition) in /_/src/xunit.assert/Asserts/BooleanAsserts.cs:line 87
   at Microsoft.AspNetCore.WebSockets.Test.WebSocketMiddlewareTests.<>c__DisplayClass16_0.<<WebSocket_Abort_Interrupts_Pending_ReceiveAsync>b__0>d.MoveNext() in /_/src/Middleware/WebSockets/test/UnitTests/WebSocketMiddlewareTests.cs:line 534
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.WebSockets.Test.KestrelWebSocketHelpers.<>c__DisplayClass0_0.<<CreateServer>b__5>d.MoveNext() in /_/src/Middleware/WebSockets/test/UnitTests/KestrelWebSocketHelpers.cs:line 30
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.WebSockets.Test.KestrelWebSocketHelpers.<>c__DisplayClass0_0.<<CreateServer>b__5>d.MoveNext() in /_/src/Middleware/WebSockets/test/UnitTests/KestrelWebSocketHelpers.cs:line 38
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application) in /_/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs:line 676
[0.020s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request finished HTTP/1.1 GET http://127.0.0.1:34187/ - 101 null null 8.8097ms
[0.020s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMRI22SNQETN" stopped.
[1.016s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting stopping
[1.032s] [Microsoft.Hosting.Lifetime] [Information] Application is shutting down...
[1.033s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting stopped
[1.035s] [Microsoft.AspNetCore.WebSockets.Test.WebSocketMiddlewareTests] [Error] Test threw an exception.
Xunit.Sdk.TrueException: Assert.True() Failure
Expected: True
Actual:   False
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/xunit.assert/Asserts/BooleanAsserts.cs:line 132
   at Xunit.Assert.True(Boolean condition) in /_/src/xunit.assert/Asserts/BooleanAsserts.cs:line 87
   at Microsoft.AspNetCore.WebSockets.Test.WebSocketMiddlewareTests.<>c__DisplayClass16_0.<<WebSocket_Abort_Interrupts_Pending_ReceiveAsync>b__0>d.MoveNext() in /_/src/Middleware/WebSockets/test/UnitTests/WebSocketMiddlewareTests.cs:line 534
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.WebSockets.Test.KestrelWebSocketHelpers.<>c__DisplayClass0_0.<<CreateServer>b__5>d.MoveNext() in /_/src/Middleware/WebSockets/test/UnitTests/KestrelWebSocketHelpers.cs:line 30
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.WebSockets.Test.KestrelWebSocketHelpers.<>c__DisplayClass0_0.<<CreateServer>b__5>d.MoveNext() in /_/src/Middleware/WebSockets/test/UnitTests/KestrelWebSocketHelpers.cs:line 38
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application) in /_/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs:line 676
   at Microsoft.AspNetCore.WebSockets.Test.KestrelWebSocketHelpers.<>c__DisplayClass0_0.<<CreateServer>b__4>d.MoveNext() in /_/src/Middleware/WebSockets/test/UnitTests/KestrelWebSocketHelpers.cs:line 83
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.WebSockets.Test.WebSocketMiddlewareTests.WebSocket_Abort_Interrupts_Pending_ReceiveAsync() in /_/src/Middleware/WebSockets/test/UnitTests/WebSocketMiddlewareTests.cs:line 557
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
[1.035s] [TestLifetime] [Information] Finished test WebSocket_Abort_Interrupts_Pending_ReceiveAsync in 1.0344759s

```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=314799&view=ms.vss-test-web.build-test-results-tab

**Comment by JamesNK** [comment]
cc @mitchdenny

**Comment by mitchdenny** [comment]
Thanks.

**Comment by mitchdenny** [comment]
I've got a fix incoming for this issue. The test is timing sensitive - if line 552 executes before line 523 starts blocking then the exception that is returned will be different. A quick fix is to add a short delay before calling abort, a better fix is to control the sequencing of those two events for the purposes of the test (which is what I'm going to do).

I'll approve the associated PR here to quarantine this test but with a little bit of luck we can merge in my fix before we need to quarantine.
