### ISSUE TITLE
HttpRequest.Form throws an undocumented System.InvalidOperationException

### ISSUE THREAD

**Issue by Grauenwolf** [dotnet/aspnetcore#49096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After upgrading from ASP.NET Core 3.x to ASP.NET Core 6, we found that `HttpRequest.Form` throws an undocumented `System.InvalidOperationException` with the message "Incorrect Content-Type: image/png".

```
System.InvalidOperationException: Incorrect Content-Type: image/png
   at Microsoft.AspNetCore.Http.Features.FormFeature.ReadForm()
   at Microsoft.AspNetCore.Http.DefaultHttpRequest.get_Form()
```

This seems to only affect image files. Using the same code to read CSV files continues to work.

### Expected Behavior

Form object is returned.

### Exceptions (if any)

System.InvalidOperationException

### .NET Version

7.0.304

### Anything else?

* https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.httprequest.form
* https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.features.formfeature.readform

**Comment by Grauenwolf** [comment]
Looking at the code, there are two paths it can go down. One throws...

```
            throw new InvalidOperationException("This request does not have a Content-Type header. Forms are available from requests with bodies like POSTs and a form Content-Type of either application/x-www-form-urlencoded or multipart/form-data.");
```

the other throws...

```
throw new InvalidOperationException("Incorrect Content-Type: " + _request.ContentType);
```

~\src\Http\Http\src\Features\FormFeature.cs

Neither is complete, as really we want both the current request type and the desired request type.

**Comment by Tratcher** [comment]
Code links:
https://github.com/dotnet/aspnetcore/blob/d07f4d43aa93d91dd2db65daaffbf37ce0012841/src/Http/Http/src/Features/FormFeature.cs#L102-L104
https://github.com/dotnet/aspnetcore/blob/d07f4d43aa93d91dd2db65daaffbf37ce0012841/src/Http/Http/src/Features/FormFeature.cs#L134-L136

Yes, both code paths check the same condition and should return the same exception type and message. And yes we should add this exception to the doc comments, as well as OperationCancelledException, InvalidDataException, and IOException

**Comment by h5aaimtron** [comment]
@Tratcher is the ask to make the ReadFormAsync error message match the ReadForm error message when the form content type is not detected? Per @Grauenwolf this happened with a seemingly valid content type, which infers there is an issue elsewhere as well, perhaps when calculating HasFormContentType. I can take a look if this is the case. The error message change is simple enough, but not sure about what causes image files to not be marked as having a form content type, yet.

**Comment by h5aaimtron** [comment]
Ok, found where the HasFormContentType is calculated:

```
/// <inheritdoc />
    public bool HasFormContentType
    {
        get
        {
            // Set directly
            if (Form != null)
            {
                return true;
            }

            if (_request is null)
            {
                return false;
            }

            var contentType = ContentType;
            return HasApplicationFormContentType(contentType) || HasMultipartFormContentType(contentType);
        }
    }
```


```
private static bool HasApplicationFormContentType([NotNullWhen(true)] MediaTypeHeaderValue? contentType)
    {
        // Content-Type: application/x-www-form-urlencoded; charset=utf-8
        return contentType != null && contentType.MediaType.Equals("application/x-www-form-urlencoded", StringComparison.OrdinalIgnoreCase);
    }

    private static bool HasMultipartFormContentType([NotNullWhen(true)] MediaTypeHeaderValue? contentType)
    {
        // Content-Type: multipart/form-data; boundary=----WebKitFormBoundarymx2fSWqWSd0OxQqq
        return contentType != null && contentType.MediaType.Equals("multipart/form-data", StringComparison.OrdinalIgnoreCase);
    }
```

This means that if the Content-Type doesn't match application/x-www-form-urlencoded or multipart/form-data then it doesn't get set, so the error gets thrown.
