### ISSUE TITLE
Running fine on RHEL 8 about half an hour then got "The LDAP server is unavailable." exception.

### ISSUE THREAD

**Issue by gfoidl** [dotnet/aspnetcore#49105]
### Discussed in https://github.com/dotnet/aspnetcore/discussions/49088

<div type='discussions-op-text'>

Originally posted by @caotoulei June 29, 2023
Here is the related code in my .net core API project Program.cs file.
```c#
builder.Services.AddAuthentication(NegotiateDefaults.AuthenticationScheme)
     .AddNegotiate(options =>
     {
         if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
         {
             options.EnableLdap(settings =>
             {
                 settings.Domain = "xxxxx.COM";
                 var ldapConnection = new LdapConnection(
                     new LdapDirectoryIdentifier("*ldap ip*", 389, true, false), 
                     new NetworkCredential(ApplicationData.srv_username, ApplicationData.srv_password), 
                     AuthType.Basic);
                 ldapConnection.SessionOptions.ReferralChasing = ReferralChasingOptions.None;
                 
                 ldapConnection.AutoBind = true;

                 settings.LdapConnection = ldapConnection;

             });
         }
     });
```
It runs fine on RHEL 8 Apache for about half an hour, and all the POST/GET requests to get responses right.  Then, all the requests throw exceptions like this:

```
_Jun 28 23:16:46 RHServer0 dotnet[56593]: Connection id "0HMRO6D462Q9A", Request id "0HMRO6D462Q9A:00000003": An unhandled exception was thrown by the application.
Jun 28 23:16:46 RHServer0 dotnet[56593]: System.DirectoryServices.Protocols.LdapException: The LDAP server is unavailable.
Jun 28 23:16:46 RHServer0 dotnet[56593]: at System.DirectoryServices.Protocols.LdapConnection.BeginSendRequest(DirectoryRequest request, TimeSpan requestTimeout, PartialResultProcessing partialMode, AsyncCa
Jun 28 23:16:46 RHServer0 dotnet[56593]: at System.DirectoryServices.Protocols.LdapConnection.BeginSendRequest(DirectoryRequest request, PartialResultProcessing partialMode, AsyncCallback callback, Object s
Jun 28 23:16:46 RHServer0 dotnet[56593]: at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state,
Jun 28 23:16:46 RHServer0dotnet[56593]: at Microsoft.AspNetCore.Authentication.Negotiate.LdapAdapter.RetrieveClaimsAsync(LdapSettings settings, ClaimsIdentity identity, ILogger logger)
Jun 28 23:16:46 RHServer0 dotnet[56593]: at Microsoft.AspNetCore.Authentication.Negotiate.NegotiateHandler.HandleAuthenticateAsync()
Jun 28 23:16:46 RHServer0 dotnet[56593]: at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
Jun 28 23:16:46 RHServer0 dotnet[56593]: at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
Jun 28 23:16:46 RHServer0 dotnet[56593]: at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Jun 28 23:16:46 RHServer0 dotnet[56593]: at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)_
```
And the Service is still Active. 
A lot of thanks for this.</div>

**Comment by mitchdenny** [comment]
Can this be reproduced using just `LdapConnection`? Based on the exception it looks like it's not necessarily ASP.NET specific.

**Comment by gfoidl** [comment]
@caotoulei I'll just ping you in case you missed the (new) issue for your discussion.
