### ISSUE TITLE
Hot reload failing on every change

### ISSUE THREAD

**Issue by Drammy** [dotnet/aspnetcore#49112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I make a small change in my blazor wasm app, say just a minor change to the class attribute of an html element, `dotnet watch` fails and I get a series of exceptions like that shown below.

I'd at least appreciate some pointers on how to understand the exception and find the cause myself.

### Expected Behavior

I'd expect the simple change to the class attribute to not result in an exception and to instead result in a quick change of the DOM in the web browser page.

At the very least I'd hope that the exception provides me with some information to help find the cause of the problem.

### Exceptions (if any)

    crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
        Unhandled exception rendering component: Field not found: Microsoft.AspNetCore.Components.EventCallback.0_10 Due to: Could not parse field signature 0a0008a9 due to: Could not resolve type with token 010001f3 from typeref (expected class 'Microsoft.AspNetCore.Components.<Main>$' in assembly 'Microsoft.AspNetCore.Components, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60') assembly:Microsoft.AspNetCore.Components, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 type:Microsoft.AspNetCore.Components.<Main>$ member:(null)
        System.MissingFieldException: Field not found: Microsoft.AspNetCore.Components.EventCallback.0_10 Due to: Could not parse field signature 0a0008a9 due to: Could not resolve type with token 010001f3 from typeref (expected class 'Microsoft.AspNetCore.Components.<Main>$' in assembly 'Microsoft.AspNetCore.Components, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60') assembly:Microsoft.AspNetCore.Components, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 type:Microsoft.AspNetCore.Components.<Main>$ member:(null)
        at Fusion.Client.Pages.Browse.Components.DocumentViewer.DocumentNavigator.BuildRenderTree(RenderTreeBuilder __builder)
        at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
        at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)

### .NET Version

7.0.304

### Anything else?

Developing in latest Rider on the latest MacOS.

**Comment by danroth27** [comment]
@tmat

**Comment by mcumming** [comment]
@lambdageek
