### ISSUE TITLE
Quarantine SetsTlsHandshakeFeatureForHttps

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#49306]
## Failing Test(s)

- Microsoft.AspNetCore.Server.IIS.FunctionalTests.TlsHandshakeFeatureTests.SetsTlsHandshakeFeatureForHttps

## Error Message

```text
System.AggregateException : One or more errors occurred. (Assert.Equal() Failure
Expected: localhost
Actual:   (null)) (Unexpected log: Error Microsoft.AspNetCore.Server.IIS.FunctionalTests.TlsHandshakeFeatureTests: Test threw an exception.)
---- Assert.Equal() Failure
Expected: localhost
Actual:   (null)
---- Unexpected log: Error Microsoft.AspNetCore.Server.IIS.FunctionalTests.TlsHandshakeFeatureTests: Test threw an exception.
```

## Stacktrace

<details>

```text
----- Inner Stack Trace #1 (Xunit.Sdk.EqualException) -----
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.TlsHandshakeFeatureTests.SetsTlsHandshakeFeatureForHttps() in /_/src/Servers/IIS/IIS/test/IIS.Tests/TlsHandshakeFeatureTests.cs:line 56
--- End of stack trace from previous location ---
----- Inner Stack Trace #2 (Xunit.Sdk.XunitException) -----
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.StrictTestServerTests.Dispose() in /_/src/Servers/IIS/IIS/test/IIS.Tests/StrictTestServerTests.cs:line 22
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in /_/src/xunit.execution/Extensions/ReflectionAbstractionExtensions.cs:line 79
```
</details>

## Logs

<details>

```text
[0.001s] [TestLifetime] [Information] Starting test SetsTlsHandshakeFeatureForHttps at 2023-07-06T20:43:32
[8.125s] [Microsoft.AspNetCore.Server.IIS.FunctionalTests.TestServer] [Debug] Method: GET, RequestUri: 'https://localhost:44300/start', Version: 1.1, Content: <null>, Headers:
{
}
[8.199s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting starting
[8.200s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Debug] Loaded hosting startup assembly IIS.Tests
[8.200s] [Microsoft.Hosting.Lifetime] [Information] Application started. Press Ctrl+C to shut down.
[8.201s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request starting HTTP/1.1 GET https://localhost:44300/start - null null
[8.203s] [Microsoft.Hosting.Lifetime] [Information] Hosting environment: Production
[8.203s] [Microsoft.Hosting.Lifetime] [Information] Content root path: C:\h\w\A67C096C\w\AF6A09BB\e\.
[8.203s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting started
[8.203s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request finished HTTP/1.1 GET https://localhost:44300/start - 200 null null 2.3751ms
[8.204s] [Microsoft.AspNetCore.Server.IIS.FunctionalTests.TestServer] [Debug] StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Transfer-Encoding: chunked
  Server: Microsoft-IIS/10.0
  Date: Thu, 06 Jul 2023 20:43:40 GMT
}
[8.204s] [Microsoft.AspNetCore.Server.IIS.FunctionalTests.TestServer] [Debug] Done
[8.205s] [Microsoft.AspNetCore.Server.IIS.FunctionalTests.TestServer] [Debug] Method: GET, RequestUri: 'https://localhost:44300/', Version: 1.1, Content: <null>, Headers:
{
}
[8.205s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request starting HTTP/1.1 GET https://localhost:44300/ - null null
[8.205s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request finished HTTP/1.1 GET https://localhost:44300/ - 200 null null 0.2918ms
[8.205s] [Microsoft.AspNetCore.Server.IIS.FunctionalTests.TestServer] [Debug] StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Transfer-Encoding: chunked
  Server: Microsoft-IIS/10.0
  Date: Thu, 06 Jul 2023 20:43:40 GMT
}
[8.205s] [Microsoft.AspNetCore.Server.IIS.FunctionalTests.TestServer] [Debug] 
[8.310s] [Microsoft.Hosting.Lifetime] [Information] Application is shutting down...
[10.550s] [Microsoft.AspNetCore.Server.IIS.FunctionalTests.TlsHandshakeFeatureTests] [Error] Test threw an exception.
Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: localhost
Actual:   (null)
   at Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences) in /_/src/xunit.assert/Asserts/StringAsserts.cs:line 326
   at Xunit.Assert.Equal(String expected, String actual) in /_/src/xunit.assert/Asserts/StringAsserts.cs:line 234
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.TlsHandshakeFeatureTests.SetsTlsHandshakeFeatureForHttps() in /_/src/Servers/IIS/IIS/test/IIS.Tests/TlsHandshakeFeatureTests.cs:line 56
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
[10.550s] [TestLifetime] [Information] Finished test SetsTlsHandshakeFeatureForHttps in 10.5489972s

```
</details>

## Build

- https://dev.azure.com/dnceng-public/public/_build/results?buildId=331152&view=ms.vss-test-web.build-test-results-tab&runId=6838100&resultId=124334
- https://dev.azure.com/dnceng-public/public/_build/results?buildId=333985&view=ms.vss-test-web.build-test-results-tab&runId=6916178&resultId=111570&paneView=debug

**Comment by Tratcher** [comment]
Test claims it ran on:
```
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      22000  2003    
```
Which is much higher than the expected min requirements for this check to work. Something wrong with the port binding?

**Comment by adityamandaleeka** [comment]
cc @karimsalem1
