### ISSUE TITLE
MVC apps no longer work with PublishTrimmed

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspnetcore#49360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using an MVC app with PublishTrimmed no longer works. The same app worked in .NET 7.

This appears to be caused by the JsonSerializerIsReflectionEnabledByDefault changes. See https://github.com/dotnet/runtime/issues/84378.

FYI @eiriktsarpalis 

### Expected Behavior

The app should work.

### Steps To Reproduce

1. `dotnet new mvc`
2. Add `<PublishTrimmed>true</PublishTrimmed>` to the csproj
3. `dotnet run`

### Exceptions (if any)

```
Unhandled exception. System.InvalidOperationException: JsonSerializerOptions instance must specify a TypeInfoResolver setting before being marked as read-only.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSerializerOptionsNoTypeInfoResolverSpecified()
   at System.Text.Json.JsonSerializerOptions.MakeReadOnly()
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter..ctor(JsonSerializerOptions jsonSerializerOptions)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.CreateFormatter(JsonOptions jsonOptions)
   at Microsoft.AspNetCore.Mvc.MvcCoreMvcOptionsSetup.Configure(MvcOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.<>c.<AddMvcCoreServices>b__5_0(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
```

### .NET Version

8.0.100-preview.7.23360.2

**Comment by DamianEdwards** [comment]
The goal is to ensure this still works for the legacy `<TrimMode>Partial</TrimMode>` so if we need to update the Web SDK to detect and set more switches to enable this then that's what we'll do.

**Comment by eerhardt** [comment]
You get this error whether you set TrimMode to partial or full.

The issue is that when JsonSerializerIsReflectionEnabledByDefault=`false` (which is the default for all trimmed apps), the SystemTextJsonOutputFormatter MVC code isn't handling it successfully. Even if I don't try to use JSON at all in my app (for example, the template app just returns HTML from the View), I still get this startup error.

One way to fix this is before we call MakeReadOnly on the JsonSerializerOptions, check if the TypeInfoResolver is still `null`. If it is, set it to an empty resolver that does nothing.

**Comment by captainsafia** [comment]
This also affects the `dotnet new webapi -minimal` template. 

> One way to fix this is before we call MakeReadOnly on the JsonSerializerOptions, check if the TypeInfoResolver is still null. If it is, set it to an empty resolver that does nothing.

I've taken a stab at this approach in https://github.com/dotnet/aspnetcore/pull/49393. @eiriktsarpalis What are your thoughts on how we should approach this?
