### ISSUE TITLE
Blazor Server throws Microsoft.JSInterop.JSDisconnectedException once the page is being refreshed

### ISSUE THREAD

**Issue by eyalalonn** [dotnet/aspnetcore#49376]
Hello,

When refreshing the page on Blazor Server the circuit is disconnected and an error like the one below is thrown:
```
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'm6YVIJJ3JO2WIq7rtFD5pigyUcM248TPZPlKDoucphY'.
      Microsoft.JSInterop.JSDisconnectedException: Microsoft.JSInterop.JSDisconnectedException:
       JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
        at RazorSharp.JSInterop.JSModuleReference.DisposeAsync:
         Module Path: ./_content/RazorSharp.Components/html-element.mjs
      
         at RazorSharp.JSInterop.JSModuleReference.DisposeAsync() in /Users/eyal/Development/Projects/RazorSharp/src/RazorSharp.JSInterop/JSModuleReference.cs:line 42
         at RazorSharp.Components.Forms.WebInput`1.OnDisposeAsync() in /Users/eyal/Development/Projects/RazorSharp/src/RazorSharp/Components/Forms/WebInput.cs:line 359
         at RazorSharp.Components.WebComponent.DisposeAsync() in /Users/eyal/Development/Projects/RazorSharp/src/RazorSharp/Components/WebComponent.cs:line 36
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass74_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()
```
Now, I understand what the exception is telling me but **as a library author** can I address that? for example can I listen to the connection or intervene before it's being disposed, store it temporarily, prevent it from being disposed and reconnect again after the page was load? or something like this?

**Comment by eyalalonn** [comment]
@mkArtakMSFT Thank you for replying, can you elaborate further on what happens after it disconnects? does a new circuit gets created for the app?
