### ISSUE TITLE
MethodNotFound Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware

### ISSUE THREAD

**Issue by Yucked** [dotnet/aspnetcore#49421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Going to any blazor web page, MethodNotFound exception is thrown and results in application unable to display any web pages

```cs
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.MissingMethodException: Method not found: 'System.Runtime.CompilerServices.ConfiguredTaskAwaitable System.Threading.Tasks.Task.ConfigureAwait(System.Threading.Tasks.ConfigureAwaitOptions)'.
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.SerializeAsync(Stream utf8Json, T rootValue, CancellationToken cancellationToken, Object rootValueBoxed)
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.SerializeAsync(Stream utf8Json, T rootValue, CancellationToken cancellationToken, Object rootValueBoxed)
         at System.Text.Json.JsonSerializer.SerializeAsync[TValue](Stream utf8Json, TValue value, JsonSerializerOptions options, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Http.HttpResponseJsonExtensions.WriteAsJsonAsyncSlow[TValue](Stream body, TValue value, JsonSerializerOptions options, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Builder.CircuitJavaScriptInitializationMiddleware.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

```

Removing `<script src="_framework/blazor.server.js"></script>` makes the error go away but defeats the purpose of having a web app

```js
Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data blazor.server.js:1:134768
    Cr http://localhost:9000/_framework/blazor.server.js:1
    AsyncFunctionThrow self-hosted:856
    (Async: async)
    Dr http://localhost:9000/_framework/blazor.server.js:1
    <anonymous> http://localhost:9000/_framework/blazor.server.js:1
    <anonymous> http://localhost:9000/_framework/blazor.server.js:1

```

### Expected Behavior

Should be able to load page without issues as before.

### Steps To Reproduce

https://github.com/Yucked/Grimoire/blob/main/Grimoire.Web/Program.cs
https://github.com/Yucked/Grimoire/blob/main/Grimoire.Web/Pages/_Host.cshtml

### Exceptions (if any)

fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.MissingMethodException: Method not found: 'System.Runtime.CompilerServices.ConfiguredTaskAwaitable System.Threading.Tasks.Task.ConfigureAwait(System.Threading.Tasks.ConfigureAwaitOptions)'.
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.SerializeAsync(Stream utf8Json, T rootValue, CancellationToken cancellationToken, Object rootValueBoxed)
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.SerializeAsync(Stream utf8Json, T rootValue, CancellationToken cancellationToken, Object rootValueBoxed)
         at System.Text.Json.JsonSerializer.SerializeAsync[TValue](Stream utf8Json, TValue value, JsonSerializerOptions options, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Http.HttpResponseJsonExtensions.WriteAsJsonAsyncSlow[TValue](Stream body, TValue value, JsonSerializerOptions options, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Builder.CircuitJavaScriptInitializationMiddleware.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

### .NET Version

8.0.100-preview.5.23303.2

**Comment by davidfowl** [comment]
Looks like mismatched versions. Make sure everything is updated to consistent versions.

**Comment by Yucked** [comment]
Mismatched version of packages?

**Comment by davidfowl** [comment]
Packages and .NET runtime being used yes.

**Comment by Yucked** [comment]
Sweeeeeet, thanks!
