### ISSUE TITLE
Blazor Wasm dotnet 8 preview 4 doesn't work on mobile phone

### ISSUE THREAD

**Issue by sake402** [dotnet/aspnetcore#49441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When running even the default blazorwasm template, it work on desktop browser, but when accessed from a chrome brwoser on android, error

### Steps To Reproduce

Create a default project, dont edit anything
``dotnet new blazorwasm``

Run it
``dotnet run``

Open in desktop browser, everything is fine
``https://localhost:5001``

Ngrok to the same pc
``ngrok http localhost:5001``

Access ngrok url from same desktop, everything works fine
``https://5fb8-41-217-56-136.ngrok-free.app/``

Access the same ngrok url from chrom on android, doesnt work
``https://5fb8-41-217-56-136.ngrok-free.app/``

```
blazor.webassembly.js:1  instantiate_wasm_module() failed: {}
Et @ blazor.webassembly.js:1
blazor.webassembly.js:1  Stacktrace: 

Et @ blazor.webassembly.js:1
blazor.webassembly.js:1  CompileError: WebAssembly.instantiateStreaming(): Compiling function #112:"mono_wasm_load_runtime" failed: Invalid opcode 0xfd (enable with --experimental-wasm-simd) @+32189
Et @ blazor.webassembly.js:1
2dotnet.js:3  CompileError: WebAssembly.instantiateStreaming(): Compiling function #112:"mono_wasm_load_runtime" failed: Invalid opcode 0xfd (enable with --experimental-wasm-simd) @+32189
U @ dotnet.js:3
dotnet.js:3  Error in mono_download_assets: CompileError: WebAssembly.instantiateStreaming(): Compiling function #112:"mono_wasm_load_runtime" failed: Invalid opcode 0xfd (enable with --experimental-wasm-simd) @+32189
(anonymous) @ dotnet.js:3
dotnet.js:3  CompileError: WebAssembly.instantiateStreaming(): Compiling function #112:"mono_wasm_load_runtime" failed: Invalid opcode 0xfd (enable with --experimental-wasm-simd) @+32189
U @ dotnet.js:3
blazor.webassembly.js:1  Error: Failed to start platform. Reason: CompileError: WebAssembly.instantiateStreaming(): Compiling function #112:"mono_wasm_load_runtime" failed: Invalid opcode 0xfd (enable with --experimental-wasm-simd) @+32189
    at zt (blazor.webassembly.js:1:54482)
    at async Gt (blazor.webassembly.js:1:56202)
(anonymous) @ blazor.webassembly.js:1
4dotnet.js:3  Uncaught (in promise) CompileError: WebAssembly.instantiateStreaming(): Compiling function #112:"mono_wasm_load_runtime" failed: Invalid opcode 0xfd (enable with --experimental-wasm-simd) @+32189
dotnet.runtime.8.0.0-preview.6.23329.7.uvxzzeohdi.js:3  Uncaught (in promise) CompileError: WebAssembly.instantiateStreaming(): Compiling function #112:"mono_wasm_load_runtime" failed: Invalid opcode 0xfd (enable with --experimental-wasm-simd) @+32189
25fb8-41-217-56-136.ngrok-free.app/:1  Uncaught (in promise) CompileError: WebAssembly.instantiateStreaming(): Compiling function #112:"mono_wasm_load_runtime" failed: Invalid opcode 0xfd (enable with --experimental-wasm-simd) @+32189
```

![image](https://github.com/dotnet/aspnetcore/assets/20999608/ec893efc-d930-4ec8-9e41-b1f7c2461515)

### .NET Version

8.0.100-preview.6.23330.14

**Comment by lanedirt** [comment]
To confirm: I am experiencing the same issue with .NET 8 preview 6. I am running an example project with the new Blazor Web App project structure and am including a WASM component in a server-rendered page.

On desktop the WASM component works fine, but on mobile (I have tested it on Chrome and Safari on iOS) the same error stacktrace pops up:
<img width="998" alt="Screenshot 2023-07-17 at 10 32 43" src="https://github.com/dotnet/aspnetcore/assets/6917405/ae8927d6-3abf-49d0-81a7-a13eaf50a2db">
