### ISSUE TITLE
RequestSizeLimit throws an error

### ISSUE THREAD

**Issue by zzapara** [dotnet/aspnetcore#49461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is a simple test endpoint.

```
 [HttpPost]
 [RequestSizeLimit(1024 * 1024 * 5)]
 public IActionResult Test(IFormFile fileContent)
 {
        return Ok();
 }
```
File size is 10 Mb.

When using Swagger, it returns the following (as I expect).

```
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "00-3df32281eb3d9830c73a5e455d700666-149c2c80738d0489-00",
  "errors": {
    "": [
      "Failed to read the request form. Request body too large. The max request body size is 5242880 bytes."
    ]
  }
} 
```
When using HttpClient

```
using var client = new HttpClient();
using var httpContent = new MultipartFormDataContent();
using var fileContent = new ByteArrayContent(File.ReadAllBytes("D:\\333.pdf"));
httpContent.Add(fileContent, "fileContent", "222.pdf");
using var request = new HttpRequestMessage(HttpMethod.Post, new Uri("https://localhost:7235/test"));
    
request.Content = httpContent;

using var response = await client.SendAsync(request);
var result = await response.Content.ReadAsStringAsync();
```
Or like following:

```
using var client = new HttpClient();
using var httpContent = new MultipartFormDataContent();

using var stream = File.OpenRead("D:\\333.pdf");

using var fileContent = new StreamContent(stream);
httpContent.Add(fileContent, "fileContent", "222.pdf");
using var request = new HttpRequestMessage(HttpMethod.Post, new Uri("https://localhost:7235/test"));
        
request.Content = httpContent;

using var response = await client.SendAsync(request);
var result = await response.Content.ReadAsStringAsync();
```
It throw an exception:

System.Net.Http.HttpRequestException: 'Error while copying content to a stream.'

Inner Exceptions: IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.. SocketException: An existing connection was forcibly closed by the remote host.

**StackTrace**

Unhandled exception. System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Security.SslStream.<WriteSingleChunk>g__CompleteWriteAsync|182_1[TIOAdapter](ValueTask writeTask, Byte[] bufferToReturn)
   at System.Net.Security.SslStream.WriteAsyncChunked[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer)
   at System.Net.Security.SslStream.WriteAsyncInternal[TIOAdapter](TIOAdapter writeAdapter, ReadOnlyMemory`1 buffer)
   at System.Net.Http.HttpConnection.WriteAsync(ReadOnlyMemory`1 source, Boolean async)
   at System.IO.Stream.<CopyToAsync>g__Core|29_0(Stream source, Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.IO.Strategies.BufferedFileStreamStrategy.CopyToAsyncCore(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
   at System.Net.Http.MultipartContent.SerializeToStreamAsyncCore(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
   at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at ConsoleApp2.Program.Main(String[] args) in D:\Local Projects\ConsoleApp2\ConsoleApp2\Program.cs:line 65
   at ConsoleApp2.Program.<Main>(String[] args)
   
   But if I set limit size less than 1 Mb

`RequestSizeLimit(1024 * 500)
`

And send file till 1 Mb and grater limit its work fine and return 400 as I expecting.
If in last case try to send file with size more than 1 mb => exception.

The same behavior when I tried to make a call using python and PowerShell (another exceptions).

### Expected Behavior

Get 400.

**{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "00-3df32281eb3d9830c73a5e455d700666-149c2c80738d0489-00",
  "errors": {
    "": [
      "Failed to read the request form. Request body too large. The max request body size is 5242880 bytes."
    ]
  }
}** 

### .NET Version

net6.0

**Comment by martincostello** [comment]
Are there any server-side errors being logged for the requests using `HttpClient`?

**Comment by zzapara** [comment]
> Feedback

Nope. on server-side clear

**Comment by zzapara** [comment]
> Are there any server-side errors being logged for the requests using `HttpClient`?

Nope. on server-side clear

**Comment by Tratcher** [comment]
This is a behavior of HttpClient, it won't return the response unless the request body finishes uploading, it favors reporting the request error (the connection was closed by the server because too much data was received). The reason it can work with smaller request sizes is that the data fits into the network buffers so HttpClient think's it finished sending and will look at the response.

**Comment by zzapara** [comment]
> This is a behavior of HttpClient, it won't return the response unless the request body finishes uploading, it favors reporting the request error (the connection was closed by the server because too much data was received). The reason it can work with smaller request sizes is that the data fits into the network buffers so HttpClient think's it finished sending and will look at the response.

So there are no proper way to receive correct response using HttpClient?

**Comment by Tratcher** [comment]
The 4XX response from the server is a best effort, it will forcibly disconnect to prevent resource abuse. There are race conditions on the client for if it's able to finish sending the request and read the response before the RST is received. E.g. even if it managed to finish sending first (or isolated the request error handling), the RST might still prevent it from consuming the response from the socket.

There's been some discussion of trying to make HttpClient surface 4XX responses like this even if there was a request body error but I don't see an issue tracking that work. Please file one in https://github.com/dotnet/runtime and reference back to this one for background.
