### ISSUE TITLE
AD Authentication / Authorization not working anymore in my Blazor Server App since installation of latest version

### ISSUE THREAD

**Issue by vRITHNER** [dotnet/aspnetcore#49503]
### Describe the bug
After upgrading all nuget packages from "8.0.0-preview.5.xxxx.x" to "8.0.0-preview.6.xxxx.x"
The same app won't start anymore with the following trace:
"

> Unhandled exception. System.MissingMethodException: Method not found: 'Boolean System.MemoryExtensions.ContainsAny(System.ReadOnlySpan`1<!!0>, System.Buffers.SearchValues`1<!!0>)'.
>    at Microsoft.Extensions.FileProviders.Physical.Internal.PathUtils.HasInvalidFilterChars(String path)
>    at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
>    at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
>    at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, TState state)
>    at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
>    at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
>    at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider..ctor(JsonConfigurationSource source)
>    at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
>    at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)
> "

### To Reproduce
Just upgrade the following  packages to latest preview
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0-preview.5.23302.2" NoWarn="NU1605" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="8.0.0-preview.5.23302.2" NoWarn="NU1605" />
    <PackageReference Include="Microsoft.Identity.Web" Version="2.12.4" />
    <PackageReference Include="Microsoft.Identity.Web.MicrosoftGraph" Version="2.12.4" />
    
    in my Program.cs, I add the following:
    
   ```
 public static IServiceCollection SetupAccessControl(
      this IServiceCollection services,
      IConfiguration configurationSection)
    {
      var authorizationSection = configurationSection.GetSection("Authorization");
      var downStreamSection = configurationSection.GetSection("MicrosoftGraph");
      var apiKeySection = configurationSection.GetSection("ApiKey");

      // Add services to the container.
      string[]? initialScopes = downStreamSection["Scopes"]?.Split(' ');

      AuthenticationBuilder authenticationBuilder =
        services.AddAuthentication(OpenIdConnectDefaults.AuthenticationScheme);
      authenticationBuilder.AddMicrosoftIdentityWebApp(authorizationSection)
                           .EnableTokenAcquisitionToCallDownstreamApi(initialScopes)
                           .AddMicrosoftGraph(downStreamSection)
                           .AddInMemoryTokenCaches();
      authenticationBuilder.AddScheme<ApiKeyAuthenticationOptions, ApiKeyAuthenticationHandler>(
                                                                                                AccessControlConstants.ApiKeySchemaName,
                                                                                                options => options.ApiKey = apiKeySection.GetValue<string>("Key")!);
      return services;
    }
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This looks like caused by a mismatched package versions in your project references. Please make sure that the references are correct.

Technically, starting from a Preview 6 created project and adding that code should just work, doesn't it ?

**Comment by Oskarsson** [comment]
> Thanks for contacting us. This looks like caused by a mismatched package versions in your project references. Please make sure that the references are correct.
> 
> Technically, starting from a Preview 6 created project and adding that code should just work, doesn't it ?

Yes, the issue only exists while running and older version of .NET 8 because the _System.MemoryExtensions.ContainsAny_ was added in preview 6. By upgrading the .NET to preview 6 the issue disappears.

**Comment by Ryangr0** [comment]
Came across the same issue. Everything has preview 6. 
```xml
<ItemGroup>
    <PackageReference Include="Azure.Core" Version="1.34.0" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.55.0" />
    <PackageReference Include="Microsoft.ApplicationInsights" Version="2.22.0-beta3" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.22.0-beta3" />
    <PackageReference Include="Microsoft.AspNetCore.Authorization" Version="8.0.0-preview.6.23329.11" />
    <PackageReference Include="Microsoft.AspNetCore.Cors" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Grpc.JsonTranscoding" Version="8.0.0-preview.6.23329.11" />
    <PackageReference Include="Microsoft.AspNetCore.Grpc.Swagger" Version="0.8.0-preview.6.23329.11" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.35.2" />
    <PackageReference Include="Microsoft.DotNet.Interactive" Version="1.0.0-beta.23313.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0-preview.6.23329.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="8.0.0-preview.6.23329.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0-preview.6.23329.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0-preview.6.23329.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.0-preview.6.23329.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="8.0.0-preview.6.23329.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0-preview.6.23329.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="8.0.0-preview.6.23329.7" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Abstractions" Version="8.0.0-preview.6.23329.7" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0-preview.6.23329.7" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.0-preview.6.23329.7" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="8.0.0-preview.6.23329.11" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0-preview.6.23329.7" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0-preview.6.23329.7" />
    <PackageReference Include="Microsoft.Extensions.Logging.Configuration" Version="8.0.0-preview.6.23329.7" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.0-preview.6.23329.7" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0-preview.6.23329.7" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0-preview.6.23329.7" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="8.0.0-preview.6.23329.7" />
    <PackageReference Include="Microsoft.Identity.Web" Version="2.13.1" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="0.18.230725.3-preview+29ecb71" />
    <PackageReference Include="Microsoft.SemanticKernel.Abstractions" Version="0.18.230725.3-preview+29ecb71" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.AI.HuggingFace" Version="0.18.230725.3-preview+29ecb71" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.AI.Oobabooga" Version="0.18.230725.3-preview+29ecb71" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.AI.OpenAI" Version="0.18.230725.3-preview+29ecb71" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Memory.AzureCognitiveSearch" Version="0.18.230725.3-preview+29ecb71" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Memory.DuckDB" Version="0.18.230725.3-preview+29ecb71" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Memory.Postgres" Version="0.18.230725.3-preview+29ecb71" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Memory.Qdrant" Version="0.18.230725.3-preview+29ecb71" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Memory.Redis" Version="0.18.230725.3-preview+29ecb71" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Memory.Sqlite" Version="0.18.230725.3-preview+29ecb71" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Memory.Weaviate" Version="0.18.230725.3-preview+29ecb71" />
    <PackageReference Include="Microsoft.SemanticKernel.Core" Version="0.18.230725.3-preview+29ecb71" />
    <PackageReference Include="Microsoft.SemanticKernel.Planning.ActionPlanner" Version="0.18.230725.3-preview+29ecb71" />
    <PackageReference Include="Microsoft.SemanticKernel.Planning.SequentialPlanner" Version="0.18.230725.3-preview+29ecb71" />
    <PackageReference Include="Microsoft.SemanticKernel.Planning.StepwisePlanner" Version="0.18.230725.3-preview+29ecb71" />
    <PackageReference Include="Microsoft.SemanticKernel.Skills.Core" Version="0.18.230725.3-preview+29ecb71" />
    <PackageReference Include="Microsoft.SemanticKernel.Skills.Document" Version="0.18.230725.3-preview+29ecb71" />
    <PackageReference Include="Microsoft.SemanticKernel.Skills.Grpc" Version="0.18.230725.3-preview+29ecb71" />
    <PackageReference Include="Microsoft.SemanticKernel.Skills.Memory.Sqlite" Version="0.10.72.1-preview" />
    <PackageReference Include="Microsoft.SemanticKernel.Skills.MsGraph" Version="0.18.230725.3-preview+29ecb71" />
    <PackageReference Include="Microsoft.SemanticKernel.Skills.OpenAPI" Version="0.18.230725.3-preview+29ecb71" />
    <PackageReference Include="Microsoft.SemanticKernel.Skills.Web" Version="0.18.230725.3-preview+29ecb71" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.19.5" />
    <PackageReference Include="MySqlConnector" Version="2.3.0-beta.2" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="7.0.0" />
    <PackageReference Include="Swashbuckle" Version="5.6.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0-preview.6.23329.7" />
    <PackageReference Include="Google.Api.Gax.Grpc" Version="4.4.0" />
		<PackageReference Include="Google.Protobuf" Version="3.23.4" />
		<PackageReference Include="Grpc.Net.Client" Version="2.55.0" />
		<PackageReference Include="Grpc.Tools" Version="2.56.2" PrivateAssets="All">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
		<PackageReference Include="System.Memory" Version="4.5.5" />
		<PackageReference Include="System.Memory.Data" Version="8.0.0-preview.6.23329.7" />
		<PackageReference Include="Tesseract" Version="5.2.0" />
  </ItemGroup>
```
