### ISSUE TITLE
[dotnet-sdk-8.0.100-preview.7.23375.2] The requested service 'Microsoft.Extensions.Options.IStartupValidator' has not been registered error shows when trying to resolve dependency in application forum.

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/aspnetcore#49675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When run the 3rd party application Forum with the latest .NET 8.0 preview 7 build, fail to access the homepage with error.

App receives this error at launch: 
```
Unhandled exception. Autofac.Core.Registration.ComponentNotRegisteredException: The requested service 'Microsoft.Extensions.Options.IStartupValidator' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
```

**Application Name**: Forum
**OS**： Windows 10 21H2
**CPU**: X64
App Github Link: https://github.com/tangxuehua/forum
**App & Source Location checking at**: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1861581/

**Verify Scenarios:**

1. Windows10 21h2 x64 + dotnet-sdk-8.0.100-preview.7.23376.3: Fail
2. Windows10 21h2 x64 + dotnet-sdk-8.0.100-preview.7.23364.32: Fail
3. Windows10 21h2 x64 + dotnet-sdk-8.0.100-preview.7.23371.2: Fail
4. Windows10 21h2 x64 + dotnet-sdk-8.0.100-preview.7.23361.1: Pass
5. Windows10 21h2 x64 + dotnet-sdk-7.0.306(default): Pass
6. Windows10 21h2 x64 + dotnet-sdk-6.0.408(default):Pass
7. Windows10 21h2 x64 + dotnet-sdk-5.0.408(default):Pass

### Expected Behavior

Can launch the home page successfully.

### Steps To Reproduce

**Minimal Repro steps (Demo attached):**  [WebApplication2.zip](https://github.com/dotnet/aspnetcore/files/12181761/WebApplication2.zip)

1) Create .net5 Asp.Net Core MVC application
2) Install this package with Nuget :   
```
<PackageReference Include="Autofac.Extensions.DependencyInjection" Version="7.1.0" />
```
3) Add a class named MyTestServiceProviderFactory with following code 
```
 public class MyTestServiceProviderFactory : IServiceProviderFactory<ContainerBuilder>
    {
        public ContainerBuilder CreateBuilder(IServiceCollection services)
        {
            var builder = new ContainerBuilder();
            builder.Populate(services);
            return builder;
        }
        public IServiceProvider CreateServiceProvider(ContainerBuilder containerBuilder)
        {
            if (containerBuilder == null)
            {
                throw new ArgumentNullException(nameof(containerBuilder));
            }
            return new MyTestServiceProvider(containerBuilder.Build());
        }
    }
```
4) Add class named MyTestServiceProvider with following code 
```
public class MyTestServiceProvider : IServiceProvider, IDisposable
    {
        private bool _disposed = false;

        /// <summary>
        /// Gets the underlying instance of <see cref="IContainer" />.
        /// </summary>
        public IContainer Container { get; }

        /// <summary>Default constructor.
        /// </summary>
        /// <param name="container"></param>
        /// <param name="autoSetObjectContainer"></param>
        public MyTestServiceProvider(IContainer container)
        {
            Container = container;
        }
        public object GetService(Type serviceType)
        {
            return Container.Resolve(serviceType);
        }
        protected virtual void Dispose(bool disposing)
        {
            if (!_disposed)
            {
                _disposed = true;
                if (disposing)
                {
                    Container.Dispose();
                }
            }
        }
        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }
    }
```
5. In Program.cs add this line:
```
 public static void Main(string[] args)
        {
            CreateHostBuilder(args)
                 .UseServiceProviderFactory(new MyTestServiceProviderFactory())
                 .Build().Run();
        }
```
7. Build the project and change the runtime.config file to let the app run against with dotnet-sdk-8.0.100-preview.7.23375.2
```
"frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "8.0.0-preview.7.23375.6"
      },
      {
        "name": "Microsoft.AspNetCore.App",
        "version": "8.0.0-preview.7.23375.9"
      }
    ]
```
8. Run this app with .net8 , 

### Exceptions (if any)

we get this error :

```
Unhandled exception. Autofac.Core.Registration.ComponentNotRegisteredException: The requested service 'Microsoft.Extensions.Options.IStartupValidator' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType)
   at WebApplication2.MyTestServiceProvider.GetService(Type serviceType) in C:\Users\v-altunc\Documents\dotnet-on-thecodeblogger-main33\dotnet-on-thecodeblogger-main\AutofacDemo\WebApplication2\MyTestServiceProvider.cs:line 25
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at WebApplication2.Program.Main(String[] args) in C:\Users\v-altunc\Documents\dotnet-on-thecodeblogger-main33\dotnet-on-thecodeblogger-main\AutofacDemo\WebApplication2\Program.cs:line 10

```

### .NET Version

dotnet-sdk-8.0.100-preview.7.23375.2

### Anything else?

Dotnet Info:
```
.NET SDK:
  Version:   8.0.100-preview.7.23376.2
  Commit:    bbd525263a

Runtime Environment:
  OS Name:     Windows
  OS Version:  10.0.19044
  OS Platform: Windows
  RID:         win10-x64
  Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.7.23376.2\

.NET workloads installed:
There are no installed workloads to display.

Host:
   Version:      8.0.0-preview.7.23375.6
   Architecture: x64
   Commit:       65b696cf5e
   RID:          win-x64

.NET SDKs installed:
   8.0.100-preview.7.23376.2 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
   Microsoft.AspNetCore.App 8.0.0-preview.7.23375.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
   Microsoft.NETCore.App 8.0.0-preview.7.23375.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
   Microsoft.WindowsDesktop.App 8.0.0-preview.7.23375.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

@dotnet-actwx-bot @dotnet/compat

**Comment by Junjun-zhao** [comment]
@mkArtakMSFT This bug was found in .NET 8 Preview 7 validation, could you please help check whether it is a blocker for Preview 7. Thanks.

**Comment by mkArtakMSFT** [comment]
I assume this is due to the app misconfiguration. @captainsafia do you know if the app here is missing any important configuration / call in the Program.cs to register the missing service?

**Comment by Tratcher** [comment]
IStartupValidator is a new optional service loaded by the host.
https://github.com/dotnet/runtime/blob/cae9bce1ff1ad20df8f8340ed5a25b96fc5db4e1/src/libraries/Microsoft.Extensions.Hosting/src/Internal/Host.cs#L104-L105

GetService should be returning null if it's not available. Does that not work on Autofac?

**Comment by Tratcher** [comment]
Oh,
```
        public object GetService(Type serviceType)
        {
            return Container.Resolve(serviceType);
        }
```

should be using ResolveOptional according to the error message.

**Comment by Junjun-zhao** [comment]
@Tratcher  It works after we update the code to use ResolveOptional . Thank you
