### ISSUE TITLE
Blazor issue with routing and - separator

### ISSUE THREAD

**Issue by Julien-Marpault** [dotnet/aspnetcore#49691]
.Net 8 Preview 6 - Blazor WASM

@page "/account/onboarding/step/{Number}"
This route format is working as expected, but this one doesn't:

@page "/account/onboarding/step-{Number}"

```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Invalid template 'account/onboarding/step-{Number}'. Missing '{' in parameter segment 'step-{Number}'.
System.InvalidOperationException: Invalid template 'account/onboarding/step-{Number}'. Missing '{' in parameter segment 'step-{Number}'.
   at Microsoft.AspNetCore.Components.Routing.TemplateParser.ParseTemplate(String template)
   at Microsoft.AspNetCore.Components.RouteTableFactory.Create(Dictionary`2 templatesByHandler)
   at Microsoft.AspNetCore.Components.RouteTableFactory.Create(List`1 componentTypes)
   at Microsoft.AspNetCore.Components.RouteTableFactory.Create(RouteKey routeKey)
   at Microsoft.AspNetCore.Components.Routing.Router.RefreshRouteTable()
   at Microsoft.AspNetCore.Components.Routing.Router.Refresh(Boolean isNavigationIntercepted)
   at Microsoft.AspNetCore.Components.Routing.Router.RunOnNavigateAsync(String path, Boolean isNavigationIntercepted)
   at Microsoft.AspNetCore.Components.Routing.Router.<>c__DisplayClass75_0.<RunOnNavigateAsync>b__1(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```

**Comment by javiercn** [comment]
@Julien-Marpault we currently don't support complex segments.

This is addressed by the following PR
https://github.com/dotnet/aspnetcore/pull/49622

**Comment by danroth27** [comment]
@javiercn Can this now be closed as done? Or is there more to be done here?
