### ISSUE TITLE
Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature: ReflectionTypeLoadException

### ISSUE THREAD

**Issue by kzhui125** [dotnet/aspnetcore#49736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

- `dotnet new webapi`
- add two struct type:

```cs
public readonly struct TestStruct2
{
    public TestStruct2(TestStruct1<TestStruct2, string> test) =>
        Test = test;

    public TestStruct1<TestStruct2, string> Test { get; }
}

public readonly struct TestStruct1<RT, A> where RT : struct { }
```

<img width="587" alt="image" src="https://github.com/dotnet/aspnetcore/assets/11925432/ac810993-182c-4a82-ac05-1864be25f5aa">

- `dotnet run`

```cs
Unhandled exception. System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'TestStruct2' from assembly 'test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.GetControllerTypes()
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.UpdateCollection()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.Initialize()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.GetChangeToken()
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.Subscribe()
   at Microsoft.AspNetCore.Builder.ControllerEndpointRouteBuilderExtensions.GetOrCreateDataSource(IEndpointRouteBuilder endpoints)
   at Microsoft.AspNetCore.Builder.ControllerEndpointRouteBuilderExtensions.MapControllers(IEndpointRouteBuilder endpoints)
   at Program.<Main>$(String[] args) in /Path/toProgram.cs:line 23
System.TypeLoadException: Could not load type 'TestStruct2' from assembly 'test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
```

### .NET Version

7.0.304

### Anything else?

It seems like a asp.net core bug. Is there a workaround now?

Thanks,

**Comment by kzhui125** [comment]
see https://github.com/dotnet/runtime/issues/89690
