### ISSUE TITLE
BlazorWasmHosted build benchmark broken

### ISSUE THREAD

**Issue by sebastienros** [dotnet/aspnetcore#49760]
This project was broken when the latest changes on the templates were merged.
https://github.com/aspnet/Benchmarks/blob/main/src/BenchmarksApps/BuildPerformance/README.md

```
[STDERR] Unhandled exception: System.ComponentModel.Win32Exception (267): An error occurred trying to start process 'C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-9136\qq44uvvy.wwq\dotnet.exe' with working directory 'C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-9136\wcawhtmj.kei\src\BenchmarksApps\BuildPerformance\published\hbayyqmi.rmx\Server'. The directory name is invalid.
[STDERR]    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
[STDERR]    at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
[STDERR]    at Build.DotNet.ExecuteAsync(String args, String workingDir) in C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-9136\wcawhtmj.kei\src\BenchmarksApps\BuildPerformance\Dotnet.cs:line 49
[STDERR]    at Build.BlazorWasmHosted.Build() in C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-9136\wcawhtmj.kei\src\BenchmarksApps\BuildPerformance\BlazorWasmHosted.cs:line 49
[STDERR]    at Build.BlazorWasmHosted.RunAsync() in C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-9136\wcawhtmj.kei\src\BenchmarksApps\BuildPerformance\BlazorWasmHosted.cs:line 32
```

For now I am disabling these benchmarks.

**Comment by sebastienros** [comment]
The BlazorServer benchmark is also broken

```
MSBuild version 17.8.0-preview-23401-01+b3989dc43 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
/tmp/benchmarks-agent/benchmarks-server-1/pzz5a0cn.rkw/sdk/8.0.100-rc.1.23401.24/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(311,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/tmp/benchmarks-agent/benchmarks-server-1/0fqvhi5r.liy/src/BenchmarksApps/BuildPerformance/published/gsnni0cf.1gn/gsnni0cf.1gn.csproj]
/tmp/benchmarks-agent/benchmarks-server-1/0fqvhi5r.liy/src/BenchmarksApps/BuildPerformance/published/gsnni0cf.1gn/_Imports.razor(9,21): error CS0234: The type or namespace name 'Shared' does not exist in the namespace 'gsnni0cf._1gn' (are you missing an assembly reference?) [/tmp/benchmarks-agent/benchmarks-server-1/0fqvhi5r.liy/src/BenchmarksApps/BuildPerformance/published/gsnni0cf.1gn/gsnni0cf.1gn.csproj]
/tmp/benchmarks-agent/benchmarks-server-1/0fqvhi5r.liy/src/BenchmarksApps/BuildPerformance/published/gsnni0cf.1gn/_Imports.razor(9,21): error CS0234: The type or namespace name 'Shared' does not exist in the namespace 'gsnni0cf._1gn' (are you missing an assembly reference?) [/tmp/benchmarks-agent/benchmarks-server-1/0fqvhi5r.liy/src/BenchmarksApps/BuildPerformance/published/gsnni0cf.1gn/gsnni0cf.1gn.csproj]
/tmp/benchmarks-agent/benchmarks-server-1/0fqvhi5r.liy/src/BenchmarksApps/BuildPerformance/published/gsnni0cf.1gn/_Imports.razor(9,21): error CS0234: The type or namespace name 'Shared' does not exist in the namespace 'gsnni0cf._1gn' (are you missing an assembly reference?) [/tmp/benchmarks-agent/benchmarks-server-1/0fqvhi5r.liy/src/BenchmarksApps/BuildPerformance/published/gsnni0cf.1gn/gsnni0cf.1gn.csproj]
/tmp/benchmarks-agent/benchmarks-server-1/0fqvhi5r.liy/src/BenchmarksApps/BuildPerformance/published/gsnni0cf.1gn/_Imports.razor(9,21): error CS0234: The type or namespace name 'Shared' does not exist in the namespace 'gsnni0cf._1gn' (are you missing an assembly reference?) [/tmp/benchmarks-agent/benchmarks-server-1/0fqvhi5r.liy/src/BenchmarksApps/BuildPerformance/published/gsnni0cf.1gn/gsnni0cf.1gn.csproj]
/tmp/benchmarks-agent/benchmarks-server-1/0fqvhi5r.liy/src/BenchmarksApps/BuildPerformance/published/gsnni0cf.1gn/_Imports.razor(9,21): error CS0234: The type or namespace name 'Shared' does not exist in the namespace 'gsnni0cf._1gn' (are you missing an assembly reference?) [/tmp/benchmarks-agent/benchmarks-server-1/0fqvhi5r.liy/src/BenchmarksApps/BuildPerformance/published/gsnni0cf.1gn/gsnni0cf.1gn.csproj]
/tmp/benchmarks-agent/benchmarks-server-1/0fqvhi5r.liy/src/BenchmarksApps/BuildPerformance/published/gsnni0cf.1gn/_Imports.razor(9,21): error CS0234: The type or namespace name 'Shared' does not exist in the namespace 'gsnni0cf._1gn' (are you missing an assembly reference?) [/tmp/benchmarks-agent/benchmarks-server-1/0fqvhi5r.liy/src/BenchmarksApps/BuildPerformance/published/gsnni0cf.1gn/gsnni0cf.1gn.csproj]
/tmp/benchmarks-agent/benchmarks-server-1/0fqvhi5r.liy/src/BenchmarksApps/BuildPerformance/published/gsnni0cf.1gn/_Imports.razor(9,21): error CS0234: The type or namespace name 'Shared' does not exist in the namespace 'gsnni0cf._1gn' (are you missing an assembly reference?) [/tmp/benchmarks-agent/benchmarks-server-1/0fqvhi5r.liy/src/BenchmarksApps/BuildPerformance/published/gsnni0cf.1gn/gsnni0cf.1gn.csproj]

Build FAILED.

```

**Comment by mkArtakMSFT** [comment]
These got broke because we've removed the Blazor Server and Blazor WebAssembly Hosted templates.
We will consider to fix these tests utilizing the new Blazor Web App project template, where it uses either client or server interactivity to cover both broken scenarios.

**Comment by sebastienros** [comment]
These benchmarks have allowed us to catch two regressions on the build/assets pipeline in the sdk this summer, it makes me sad they are not running anymore.

Note for myself, we need to restore the [continuous runs](https://github.com/aspnet/Benchmarks/blob/main/build/build-perf-scenarios.yml#L16-L22) once this is fixed

**Comment by sebastienros** [comment]
Current error messages since we moved back to 9.0 continuous runs:

```
[STDERR] --use-wasm
[STDERR]    '--use-wasm' is not a valid option
```

and 

```
[STDERR] --use-server
[STDERR]    '--use-server' is not a valid option
```

@lewing
