### ISSUE TITLE
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by danroth27** [dotnet/aspnetcore#49820]
Repro steps:
- Install .NET 8 Preview 7
- Create a new Blazor Web App
- In Index.razor add the following form:

```razor
<form method="post" @formname="contact" @onsubmit="AddContact">
    <div class="mb-3">
        <label class="form-label" for="name">Name</label>
        <InputText class="form-control" id="name" @bind-Value="NewContact.Name" />
    </div>
    <div class="mb-3">
        <label class="form-label" for="email">Email</label>
        <InputText class="form-control" id="email" @bind-Value="NewContact.Email" />
    </div>
    <div class="form-check">
        <InputCheckbox class="form-check-input" id="send-me-deals" @bind-Value="NewContact.SendMeDeals" />
        <label class="form-check-label" for="send-me-deals">Send me deals</label>
    </div>
    <button class="btn btn-primary">Submit</button>
    <AntiforgeryToken />
</form>

<ul>
    @foreach (var contact in contacts)
    {
        <li>@contact.Name @contact.Email @contact.SendMeDeals</li>
    }
</ul>

@code {
    static List<Contact> contacts = new();

    [SupplyParameterFromForm]
    public Contact NewContact { get; set; } = new();

    public class Contact
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public bool SendMeDeals { get; set; }
    }

    private async Task AddContact()
    {
        // Add contact...
        contacts.Add(NewContact);
        NewContact = new();
    }
}
```

- Run the app and submit the form
- Check the browser dev console for the following error:

```
DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at lu (chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/web-client-content-script.js:1:183633)
    at ps (chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/web-client-content-script.js:1:196892)
    at t.unstable_runWithPriority (chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/web-client-content-script.js:1:217647)
    at Vo (chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/web-client-content-script.js:1:141776)
    at ds (chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/web-client-content-script.js:1:194750)
    at Zu (chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/web-client-content-script.js:1:190881)
    at chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/web-client-content-script.js:1:142067
    at t.unstable_runWithPriority (chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/web-client-content-script.js:1:217647)
    at Vo (chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/web-client-content-script.js:1:141776)
    at qo (chrome-extension://bbcinlkgjjkejfdpemiealijmmooekmp/web-client-content-script.js:1:142012)
```

**Comment by danroth27** [comment]
Turns out this is an error from a browser extension and unrelated to Blazor. Disabling the extension makes the error go away.
