### ISSUE TITLE
WebToolsException when using hot reload to apply change to Blazor WebAssembly app

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/aspnetcore#49874]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/WebToolsException-when-using-hot-reload-/10421101)._

---
I got the following error when trying to hot reload a change to my Blazor WebAssemlby app:

```
20:46 51.50 BlazorApp14.Server (Web assembly): Sending updates to running application
20:46 51.56 BlazorApp14.Server (Web assembly): [Error] Applying updates failed: 
20:46 51.56 BlazorApp14.Server (Web assembly): [Error] Applying updates failed: The following error occurred when trying to apply your edits to the running application. 
20:46 51.57 Exception thrown for Apply Code Updates: 0x80131500 - The following error occurred when trying to apply your edits to the running application. The following error occurred when trying to apply your edits to the running application. 
20:46 51.57 Stack trace for WebToolsException:
   at Microsoft.WebTools.ProjectSystem.Components.HotReload.ProjectHotReloadSession.<ApplyUpdatesAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Debugger.Shared.Utilities.LoggerExtensions.<LogOnExceptionAsync>d__3.MoveNext()
20:46 51.57 An unexpected error has occurred, any pending updates have been discarded.
```

Repro steps:

- Create an ASP.NET Core hosted Blazor WebAssembly app using .NET 7
- Add Shared/MyLayout.razor to the Client project

```
@inherits LayoutComponentBase
<h1>MyLayout</h1>
<main>
    @Body
</main>
```
- Update Index.razor to include `@layout MyLayout` just below the `@page` directive
- Run the app without debugging
- Remove the `@layout MyLayout` directive from Index.Razor
- Hot reload the change to the running app

---
#### Feedback Bot on 7/23/2023, 05:58 PM: 

(private comment, text removed)
#### Feedback Bot on 7/24/2023, 01:36 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment]
@BillHiebert has looked into this and have determined the below is the stack trace:

```
The failure is this:

Error: System.TypeLoadException: EnC: we do not support patching of existing table cols. token=0x0200000f
   at System.Reflection.Metadata.MetadataUpdater.ApplyUpdate(:7222/Assembly assembly, ReadOnlySpan`1 metadataDelta, ReadOnlySpan`1 ilDelta, ReadOnlySpan`1 pdbDelta)
   at Microsoft.Extensions.HotReload.HotReloadAgent.ApplyDeltas(:7222/IReadOnlyList`1 deltas)
   at Microsoft.AspNetCore.Components.WebAssembly.HotReload.WebAssemblyHotReload.ApplyHotReloadDelta(:7222/String moduleIdString, Byte[] metadataDelta, Byte[] ilDelta, Byte[] pdbBytes)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(:7222/JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.Invoke(:7222/JSRuntime jsRuntime, DotNetInvocationInfo& invocationInfo, String argsJson)
   at Microsoft.AspNetCore.Components.WebAssembly.Services.DefaultWebAssemblyJSRuntime.InvokeDotNet(:7222/String assemblyName, String methodIdentifier, String dotNetObjectId, String argsJson)
    at qi (dotnet.7.0.9.spglg51993.js:5:80665)
    at Ji (dotnet.7.0.9.spglg51993.js:5:80549)
    at _Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_InvokeDotNet (_Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_InvokeDotNet:30:5)
    at Object.invokeDotNetFromJS (blazor.webassembly.js:1:45224)
    at g (blazor.webassembly.js:1:1621)
    at e.invokeMethod (blazor.webassembly.js:1:2670)
    at Vt.Ke._internal.applyHotReload (blazor.webassembly.js:1:58767)
    at aspnetcore-browser-refresh.js:140:35
    at Array.forEach (<anonymous>)
```
