### ISSUE TITLE
Configuration of MessagePackProtocol IFormatterResolver(s) for SignalR with Redis backplane for ASP.NET Core SignalR scale-out

### ISSUE THREAD

**Issue by rf-0** [dotnet/aspnetcore#49894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to use redis as the backplane for my signalr implementation and i use custom types (implementing IFormatterResolver) and these fail to serialize to redis if i use it as backplane since there isnt a way to add/register them at the moment.

### Describe the solution you'd like

I want to be able to configure the IFormatterResolver(s) in the redis options as well so these can be properly serialized.

Example:

```
applicationBuilder.Services
                          .AddSingleton<SomeHub>()
                          .AddSignalR()
                          .AddMessagePackProtocol(
                              static options =>
                              {
                                  var resolvers = CompositeResolver.Create(
                                      new SomeFormatterResolverA(),
                                      new SomeFormatterResolverB()
                                      StandardResolver.Instance
                                  );

                                  options.SerializerOptions = MessagePackSerializerOptions.Standard
                                                                                          .WithResolver(resolvers)
                                                                                          .WithSecurity(MessagePackSecurity.UntrustedData);
                              })
                          .AddStackExchangeRedis(
                              applicationBuilder.Configuration["RedisCache:Hostname"] ?? throw new ArgumentNullException(),
                              static options =>
                              {
                                   **want to do the same as above, which is not possible at the moment and throws exception**
                              });
```

### Additional context

exception:

**NOTE:** the reason this fails is because Domain.UI.SignalR.MessageUpdated contains the properties mentioned above. (SomeFormatterResolverA and SomeFormatterResolverB). These properties are value types (readonly record struct).

The resolvers are working properly as i use it with redis in other places. It only fails here since i cant find out how/where to configure it.

 ```
---> MessagePack.MessagePackSerializationException: Failed to serialize Domain.UI.SignalR.MessageUpdated value.
 ---> MessagePack.FormatterNotRegisteredException: Domain.UI.SignalR.MessageUpdated is not registered in resolver: MessagePack.Resolvers.CompositeResolver+CachingResolver
   at MessagePack.FormatterResolverExtensions.Throw(Type t, IFormatterResolver resolver)
   at MessagePack.MessagePackSerializer.Serialize[T](MessagePackWriter& writer, T value, MessagePackSerializerOptions options)
   --- End of inner exception stack trace ---
   at MessagePack.MessagePackSerializer.Serialize[T](MessagePackWriter& writer, T value, MessagePackSerializerOptions options)
   at MessagePack.MessagePackSerializer.SerializeSemiGeneric[T](MessagePackWriter& writer, Object valueObject, MessagePackSerializerOptions options)
   at MessagePack.MessagePackSerializer.Serialize(Type type, MessagePackWriter& writer, Object obj, MessagePackSerializerOptions options) 
   at Microsoft.AspNetCore.SignalR.Protocol.DefaultMessagePackHubProtocolWorker.Serialize(MessagePackWriter& writer, Type type, Object value)
   at Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocolWorker.WriteArgument(Object argument, MessagePackWriter& writer)        
   at Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocolWorker.WriteInvocationMessage(InvocationMessage message, MessagePackWriter& writer)
   at Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocolWorker.WriteMessageCore(HubMessage message, MessagePackWriter& writer)  
   at Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocolWorker.GetMessageBytes(HubMessage message)
   at Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocol.GetMessageBytes(HubMessage message)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubMessageSerializer.SerializeMessage(HubMessage message)
   at Microsoft.AspNetCore.SignalR.StackExchangeRedis.Internal.RedisProtocol.WriteHubMessage(MessagePackWriter& writer, HubMessage message)
   at Microsoft.AspNetCore.SignalR.StackExchangeRedis.Internal.RedisProtocol.WriteInvocation(String methodName, Object[] args, String invocationId, IReadOnlyList`1 excludedConnectionIds, String returnChannel)
   at Microsoft.AspNetCore.SignalR.StackExchangeRedis.RedisHubLifetimeManager`1.SendGroupAsync(String groupName, String methodName, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Internal.GroupProxy`1.SendCoreAsync(String method, Object[] args, CancellationToken cancellationToken) 
   at Message.Service.Hubs.MessageHub.MessageUpdated(MessageUpdated updatedMessage)
```

**Comment by BrennanConroy** [comment]
Are you sure the resolvers are working correctly? Redis is using the options you configured in `AddMessagePackProtocol` so there isn't anything needed to configure the internal redis options.

If you can provide a minimal repro, as a GitHub repo, using just `AddMessagePackProtocol`, then we can take a look.

**Comment by rf-0** [comment]
You're correct, and the error was quite explicit. I just for some reason thought the `structs` were the only formatters I had to configure but the types using them also have to be configured as well. Closed.
