### ISSUE TITLE
 [Kestrel] Getting System.IO.IOException: Failed to bind to address https://10.0.0.x:443: address already in use.

### ISSUE THREAD

**Issue by milen-denev** [dotnet/aspnetcore#49895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After stopping and starting again a process (for an update) it fails with this exception. After inspection with the tcpview program I cannot find any program or process actively listening to the port that the exception describes. 

### Expected Behavior

Begging the kestrel process without any port binding errors since no one is listening to this port.

### Steps To Reproduce

I am really not so quite sure how to reproduce this issue. This is my kestrel configuration. 

```csharp           
           builder.Host.UseWindowsService();

            builder.Host.ConfigureHostOptions(options =>
            {
                options.BackgroundServiceExceptionBehavior = BackgroundServiceExceptionBehavior.Ignore;
                options.ShutdownTimeout = TimeSpan.FromSeconds(2);
            });

            builder.WebHost.UseKestrel(serverOptions =>
            {

                serverOptions.Listen(internalIpv4, 80, portOptions =>
                {
                    portOptions.Protocols = HttpProtocols.Http1AndHttp2AndHttp3;
                });

                serverOptions.Listen(internalIpv6, 80, portOptions =>
                {
                    portOptions.Protocols = HttpProtocols.Http1AndHttp2AndHttp3;
                });

                serverOptions.Listen(internalIpv4, 443, portOptions =>
                {
                    portOptions.Protocols = HttpProtocols.Http1AndHttp2AndHttp3;
                    portOptions.DisableAltSvcHeader = false;
                    portOptions.UseHttps(httpsOptions =>
                    {
                        httpsOptions.ServerCertificateSelector = (connectionContext, name) =>
                        {
                            if (name != null && CertificateDictionary.TryGetValue(name, out var cert))
                            {
                                return cert;
                            }

                            logger.LogError($"Certificate for {name} not found.");

                            return null;
                        };

                        httpsOptions.SslProtocols = SslProtocols.Tls12 | SslProtocols.Tls13;
                        httpsOptions.HandshakeTimeout = TimeSpan.FromSeconds(10);
                    });
                });

                serverOptions.Listen(internalIpv6, 443, portOptions =>
                {
                    portOptions.Protocols = HttpProtocols.Http1AndHttp2AndHttp3;
                    portOptions.DisableAltSvcHeader = false;
                    portOptions.UseHttps(httpsOptions =>
                    {
                        httpsOptions.ServerCertificateSelector = (connectionContext, name) =>
                        {                     
                            if (name != null && CertificateDictionary.TryGetValue(name, out var cert))
                            {
                                return cert;
                            }

                            logger.LogError($"Certificate for {name} not found.");

                            return null;
                        };

                        httpsOptions.SslProtocols = SslProtocols.Tls12 | SslProtocols.Tls13;
                        httpsOptions.HandshakeTimeout = TimeSpan.FromSeconds(10);
                    });
                });

                serverOptions.AddServerHeader = false;

                serverOptions.Limits.MaxConcurrentConnections = long.MaxValue;
                serverOptions.Limits.MaxResponseBufferSize = 5120;
                serverOptions.Limits.MaxRequestBufferSize = 4_196_352;
                serverOptions.Limits.MaxRequestHeadersTotalSize = 65_536;
                serverOptions.Limits.MaxRequestHeaderCount = 500;
                serverOptions.Limits.MaxRequestBodySize = 104_857_600;
                serverOptions.Limits.Http2.MaxStreamsPerConnection = 2_048;
                serverOptions.Limits.MaxRequestLineSize = 16_384;
                serverOptions.Limits.RequestHeadersTimeout = TimeSpan.FromMinutes(1);
                serverOptions.AllowSynchronousIO = false;
                serverOptions.ResponseHeaderEncodingSelector = (encoding) =>
                {
                    return Encoding.UTF8;
                };
            });
```

Also I have 
```csharp      
builder.Services.AddReverseProxy().LoadFromMemory(routes, clusters);'

### Exceptions (if any)

_No response_

### .NET Version

_No response_

### Anything else?

_No response_

**Comment by Tratcher** [comment]
Does it work if you change Http1AndHttp2AndHttp3 to Http1AndHttp2 everywhere?

**Comment by milen-denev** [comment]
@Tratcher I tried multiple times to trigger this exception and it seems that without the HTTTP/3 protocol it works.

**Comment by Tratcher** [comment]
Ok, thanks. Please also try it on the latest .NET 8 preview with and without HTTP/3, we've fixed a lot of issues in that area.

**Comment by milen-denev** [comment]
I tested it out and the problem persists.
```
Application: MyApplication.exe
CoreCLR Version: 8.0.23.32907
.NET Version: 8.0.0-preview.6.23329.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException: Failed to bind to address https://10.0.0.x:443: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: The local address is already in use.
 ---> System.Net.Quic.QuicException: The local address is already in use.
   at System.Net.Quic.ThrowHelper.ThrowIfMsQuicError(Int32 status, String message)
   at System.Net.Quic.QuicListener..ctor(QuicListenerOptions options)
   at System.Net.Quic.QuicListener.ListenAsync(QuicListenerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionListener.CreateListenerAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionListener.CreateListenerAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.QuicTransportFactory.BindAsync(EndPoint endpoint, IFeatureCollection features, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, MultiplexedConnectionDelegate multiplexedConnectionDelegate, ListenOptions listenOptions, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass28_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(ListenOptions[] listenOptions, AddressBindContext context, Func`2 useHttps, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAndTryToExecuteAsync(IHostedService service, CancellationToken combinedCancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at MyApplication.Program.Main(String[] args)
   at MyApplication.Program.<Main>(String[] args)
```

**Comment by amcasey** [comment]
I took a shot at reproducing this locally, but didn't have any luck.  Some quick things I would have tested:

 1. Does it still happen without the ipv4/6 endpoints?
 2. Does it happen with only HTTP/3 (i.e. `HttpProtocols.Http3`)?
 3. Does it happen without `builder.Host.UseWindowsService()`?
 4. Does it happen without yarp?

Most of these factors will probably turn out to be irrelevant and knowing which would help a lot.

**Comment by milen-denev** [comment]
Sorry for my late reply. Sadly, I am not able to further investigate, since there is no longer any active Window VM running due to migration to Linux. Also due to the issues that occurred with HTTP/3, and general lower performance compared to its HTTP/2 counterpart it's disabled. I cannot provide any further evidence.
