### ISSUE TITLE
Blazor route constraint does not work.

### ISSUE THREAD

**Issue by sikora507** [dotnet/aspnetcore#49921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I tried to add int route constraint to Blazor page

```
@page "/user/{Id:int}"

<h3>User Id: @Id</h3>

@code {
    [Parameter]
    public int Id { get; set; }
}
```
When I try to visit the page: `http://localhost:5248/user/1`
I get error about not being able to cast string to int:
`InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Int32'.`
When I remove the parameter constraint and change my parameter type from int to string, it works.
I get a page with: `User Id: 1` 

### Expected Behavior

Route constraints should work and not cause exceptions when used correctly.

### Steps To Reproduce

Create a blazor app from the dotnet template:
`dotnet new blazor -n Routing`
Add User.razor page in Pages directory:
```
@page "/user/{Id:int}"

<h3>User Id: @Id</h3>

@code {
    [Parameter]
    public int Id { get; set; }
}
```
Run the app and try to visit `/user/1` in the browser (localhost and port omitted)
An exception will be thrown

### Exceptions (if any)

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: Unable to set property 'Id' on object of type 'Routing.Pages.User'. The error was: Unable
to cast object of type 'System.String' to type 'System.Int32'.
       ---> System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Int32'.
         at Microsoft.AspNetCore.Components.Reflection.PropertySetter.CallPropertySetter[TTarget,TValue](Action`2 setter, Object t
arget, Object value)
         at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|3_0(Object target, Proper
tySetter writer, String parameterName, Object value)
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.<SetProperties>g__SetProperty|3_0(Object target, Proper
tySetter writer, String parameterName, Object value)
         at Microsoft.AspNetCore.Components.Reflection.ComponentProperties.SetProperties(ParameterView& parameters, Object target)

         at Microsoft.AspNetCore.Components.ComponentBase.SetParametersAsync(ParameterView parameters)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingPara
meters)
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext,
 Int32 frameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32
frameIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFra
meIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFra
meIndex)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, I
nt32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
         at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder bat
chBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree, Dictionary`2 namedEventIndexes)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragme
nt renderFragment, Exception& renderFragmentException)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)

         at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
         at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderRootComponentAsync(Int32 componentId, ParameterView initialP
arameters)
         at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.BeginRenderingComponent(IComponent com
ponent, ParameterView initialParameters)
         at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.RenderEndpointComponent(HttpContext httpContext, Type r
ootComponentType, ParameterView parameters, Boolean waitForQuiescence)
         at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore()
         at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore()
         at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<<InvokeAsync>b__9_0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)


```

### .NET Version

8.0.100-preview.6.23330.14

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This may be addressed by #49622, but we'll double check.

**Comment by benjaminsampica** [comment]
Can confirm Preview 7 just fixed this issue. Try it out!

**Comment by sikora507** [comment]
I confirm as well, works in preview 7

**Comment by mkArtakMSFT** [comment]
Thanks for confirming @benjaminsampica  and @sikora507 siko
