### ISSUE TITLE
7.0 failing test: POST_ServerCompletesWithoutReadingRequestBody_ClientGetsResponse

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#49926]
Failing on `(Debian.11.Arm64.Open)ubuntu.2004.armarch.open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-11-helix-arm64v8` in `release/7.0`

## Failing Test(s)

- Interop.FunctionalTests.Http3.Http3RequestTests.POST_ServerCompletesWithoutReadingRequestBody_ClientGetsResponse

## Error Message

```text
System.Net.Quic.QuicException : Stream aborted by peer (256).
```

## Stacktrace

<details>

```text
   at System.Net.Quic.ResettableValueTaskSource.TryComplete(Exception exception, Boolean final)
   at System.Net.Quic.QuicStream.HandleEventPeerReceiveAborted(_PEER_RECEIVE_ABORTED_e__Struct& data)
   at System.Net.Quic.QuicStream.HandleStreamEvent(QUIC_STREAM_EVENT& streamEvent)
   at System.Net.Quic.QuicStream.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_STREAM_EVENT* streamEvent)
--- End of stack trace from previous location ---
   at System.Net.Quic.ResettableValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Http.Http3RequestStream.WriteRequestContentAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 123
   at Interop.FunctionalTests.Http3.Http3RequestTests.POST_ServerCompletesWithoutReadingRequestBody_ClientGetsResponse() in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/Http3/Http3RequestTests.cs:line 380
--- End of stack trace from previous location ---
```
</details>

## Logs

<details>

```text
2023-08-03T09:42:46.2769802Z [xUnit.net 00:00:06.82]     Interop.FunctionalTests.Http3.Http3RequestTests.POST_ServerCompletesWithoutReadingRequestBody_ClientGetsResponse [FAIL]
2023-08-03T09:42:46.2771583Z [xUnit.net 00:00:06.81]         |    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
2023-08-03T09:42:46.2772621Z [xUnit.net 00:00:06.81]         |    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
2023-08-03T09:42:46.2773407Z [xUnit.net 00:00:06.81]         | [0.007s] TestLifetime Information: Finished test GET_ServerStreaming_ClientReadsPartialResponse-Http2-11 in 0.0037387s
2023-08-03T09:42:46.2784483Z [xUnit.net 00:00:06.82]       System.InvalidOperationException : Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
2023-08-03T09:42:46.2808178Z [xUnit.net 00:00:06.82]       To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
2023-08-03T09:42:46.2815907Z [xUnit.net 00:00:06.82]       For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
2023-08-03T09:42:46.2823278Z [xUnit.net 00:00:06.82]       Stack Trace:
2023-08-03T09:42:46.2830271Z [xUnit.net 00:00:06.82]         /_/src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs(186,0): at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
2023-08-03T09:42:46.2837396Z [xUnit.net 00:00:06.82]         /_/src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs(27,0): at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)
2023-08-03T09:42:46.2844373Z [xUnit.net 00:00:06.82]         /_/src/Servers/Kestrel/test/Interop.FunctionalTests/HttpHelpers.cs(60,0): at Interop.FunctionalTests.HttpHelpers.<>c__DisplayClass1_0.<CreateHostBuilder>b__4(ListenOptions listenOptions)
2023-08-03T09:42:46.2852294Z [xUnit.net 00:00:06.82]         /_/src/Servers/Kestrel/Core/src/KestrelServerOptions.cs(434,0): at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.Listen(EndPoint endPoint, Action`1 configure)
2023-08-03T09:42:46.2859392Z [xUnit.net 00:00:06.82]         /_/src/Servers/Kestrel/Core/src/KestrelServerOptions.cs(414,0): at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.Listen(IPEndPoint endPoint, Action`1 configure)
2023-08-03T09:42:46.2866544Z [xUnit.net 00:00:06.82]         /_/src/Servers/Kestrel/Core/src/KestrelServerOptions.cs(388,0): at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.Listen(IPAddress address, Int32 port, Action`1 configure)
2023-08-03T09:42:46.2873469Z [xUnit.net 00:00:06.82]         /_/src/Servers/Kestrel/test/Interop.FunctionalTests/HttpHelpers.cs(55,0): at Interop.FunctionalTests.HttpHelpers.<>c__DisplayClass1_0.<CreateHostBuilder>b__2(KestrelServerOptions o)
2023-08-03T09:42:46.2880572Z [xUnit.net 00:00:06.83]            at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
2023-08-03T09:42:46.2887446Z [xUnit.net 00:00:06.83]            at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
2023-08-03T09:42:46.2895704Z [xUnit.net 00:00:06.83]            at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
2023-08-03T09:42:46.2913728Z [xUnit.net 00:00:06.83]         /_/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs(110,0): at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.CreateServiceContext(IOptions`1 options, ILoggerFactory loggerFactory, DiagnosticSource diagnosticSource)
2023-08-03T09:42:46.2921367Z [xUnit.net 00:00:06.83]         /_/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs(59,0): at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl..ctor(IOptions`1 options, IEnumerable`1 transportFactories, IEnumerable`1 multiplexedFactories, ILoggerFactory loggerFactory, DiagnosticSource diagnosticSource)
2023-08-03T09:42:46.2929430Z [xUnit.net 00:00:06.83]            at InvokeStub_KestrelServerImpl..ctor(Object, Object, IntPtr*)
2023-08-03T09:42:46.2936965Z [xUnit.net 00:00:06.83]            at System.Reflection.RuntimeConstructorInfo.InvokeWithManyArguments(RuntimeConstructorInfo ci, Int32 argCount, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2023-08-03T09:42:46.2944581Z [xUnit.net 00:00:06.83]            at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2023-08-03T09:42:46.2951969Z [xUnit.net 00:00:06.83]            at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2023-08-03T09:42:46.2959180Z [xUnit.net 00:00:06.83]            at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2023-08-03T09:42:46.2966185Z [xUnit.net 00:00:06.83]            at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
2023-08-03T09:42:46.2973679Z [xUnit.net 00:00:06.83]            at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2023-08-03T09:42:46.2980844Z [xUnit.net 00:00:06.83]            at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2023-08-03T09:42:46.2988104Z [xUnit.net 00:00:06.83]            at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2023-08-03T09:42:46.2995547Z [xUnit.net 00:00:06.83]            at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
2023-08-03T09:42:46.3002798Z [xUnit.net 00:00:06.83]            at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2023-08-03T09:42:46.3012270Z [xUnit.net 00:00:06.83]            at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
2023-08-03T09:42:46.3025597Z [xUnit.net 00:00:06.83]            at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2023-08-03T09:42:46.3032593Z [xUnit.net 00:00:06.83]            at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
2023-08-03T09:42:46.3039537Z [xUnit.net 00:00:06.83]            at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2023-08-03T09:42:46.3053335Z [xUnit.net 00:00:06.83]            at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
2023-08-03T09:42:46.3060367Z [xUnit.net 00:00:06.83]            at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
2023-08-03T09:42:46.3067354Z [xUnit.net 00:00:06.83]            at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
2023-08-03T09:42:46.3074630Z [xUnit.net 00:00:06.83]            at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
2023-08-03T09:42:46.3081613Z [xUnit.net 00:00:06.83]            at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
2023-08-03T09:42:46.3088507Z [xUnit.net 00:00:06.83]            at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
2023-08-03T09:42:46.3095906Z [xUnit.net 00:00:06.83]            at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
2023-08-03T09:42:46.3103092Z [xUnit.net 00:00:06.83]            at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
2023-08-03T09:42:46.3110195Z [xUnit.net 00:00:06.83]         /_/src/Shared/TaskExtensions.cs(141,0): at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber)
2023-08-03T09:42:46.3117357Z [xUnit.net 00:00:06.83]         /_/src/Servers/Kestrel/test/Interop.FunctionalTests/Http3/Http3RequestTests.cs(363,0): at Interop.FunctionalTests.Http3.Http3RequestTests.POST_ServerCompletesWithoutReadingRequestBody_ClientGetsResponse()
2023-08-03T09:42:46.3124157Z [xUnit.net 00:00:06.83]         --- End of stack trace from previous location ---
2023-08-03T09:42:46.3168586Z [xUnit.net 00:00:06.83]       Output:
2023-08-03T09:42:46.3169868Z [xUnit.net 00:00:06.83]         | [0.001s] TestLifetime Information: Starting test POST_ServerCompletesWithoutReadingRequestBody_ClientGetsResponse at 2023-08-03T09:42:44
2023-08-03T09:42:46.3170662Z [xUnit.net 00:00:06.83]         | [0.011s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting starting
2023-08-03T09:42:46.3171211Z [xUnit.net 00:00:06.84]         | [0.011s] Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer Debug: Unable to locate an appropriate development https certificate.
2023-08-03T09:42:46.3171948Z [xUnit.net 00:00:06.84]         | [0.012s] Interop.FunctionalTests.Http3.Http3RequestTests Error: Test threw an exception.
2023-08-03T09:42:46.3172584Z [xUnit.net 00:00:06.84]         | System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
2023-08-03T09:42:46.3173120Z [xUnit.net 00:00:06.84]         | To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
2023-08-03T09:42:46.3173682Z [xUnit.net 00:00:06.84]         | For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
2023-08-03T09:42:46.3185585Z [xUnit.net 00:00:06.84]         |    at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions) in /_/src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs:line 186
2023-08-03T09:42:46.3189510Z [xUnit.net 00:00:06.84]         |    at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions) in /_/src/Servers/Kestrel/Core/src/ListenOptionsHttpsExtensions.cs:line 27
2023-08-03T09:42:46.3193561Z [xUnit.net 00:00:06.84]         |    at Interop.FunctionalTests.HttpHelpers.<>c__DisplayClass1_0.<CreateHostBuilder>b__4(ListenOptions listenOptions) in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/HttpHelpers.cs:line 60
2023-08-03T09:42:46.3197734Z [xUnit.net 00:00:06.84]         |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.Listen(EndPoint endPoint, Action`1 configure) in /_/src/Servers/Kestrel/Core/src/KestrelServerOptions.cs:line 434
2023-08-03T09:42:46.3201770Z [xUnit.net 00:00:06.84]         |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.Listen(IPEndPoint endPoint, Action`1 configure) in /_/src/Servers/Kestrel/Core/src/KestrelServerOptions.cs:line 414
2023-08-03T09:42:46.3205867Z [xUnit.net 00:00:06.84]         |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.Listen(IPAddress address, Int32 port, Action`1 configure) in /_/src/Servers/Kestrel/Core/src/KestrelServerOptions.cs:line 388
2023-08-03T09:42:46.3212401Z [xUnit.net 00:00:06.84]         |    at Interop.FunctionalTests.HttpHelpers.<>c__DisplayClass1_0.<CreateHostBuilder>b__2(KestrelServerOptions o) in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/HttpHelpers.cs:line 55
2023-08-03T09:42:46.3216442Z [xUnit.net 00:00:06.84]         |    at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
2023-08-03T09:42:46.3220543Z [xUnit.net 00:00:06.84]         |    at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
2023-08-03T09:42:46.3224818Z [xUnit.net 00:00:06.84]         |    at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
2023-08-03T09:42:46.3228969Z [xUnit.net 00:00:06.84]         |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.CreateServiceContext(IOptions`1 options, ILoggerFactory loggerFactory, DiagnosticSource diagnosticSource) in /_/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs:line 110
2023-08-03T09:42:46.3233153Z [xUnit.net 00:00:06.84]         |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl..ctor(IOptions`1 options, IEnumerable`1 transportFactories, IEnumerable`1 multiplexedFactories, ILoggerFactory loggerFactory, DiagnosticSource diagnosticSource) in /_/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs:line 59
2023-08-03T09:42:46.3237282Z [xUnit.net 00:00:06.84]         |    at InvokeStub_KestrelServerImpl..ctor(Object, Object, IntPtr*)
2023-08-03T09:42:46.3241442Z [xUnit.net 00:00:06.84]         |    at System.Reflection.RuntimeConstructorInfo.InvokeWithManyArguments(RuntimeConstructorInfo ci, Int32 argCount, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2023-08-03T09:42:46.3245573Z [xUnit.net 00:00:06.84]         |    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2023-08-03T09:42:46.3250605Z [xUnit.net 00:00:06.84]         |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2023-08-03T09:42:46.3254972Z [xUnit.net 00:00:06.84]         |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2023-08-03T09:42:46.3259196Z [xUnit.net 00:00:06.84]         |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
2023-08-03T09:42:46.3263450Z [xUnit.net 00:00:06.84]         |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2023-08-03T09:42:46.3267644Z [xUnit.net 00:00:06.84]         |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
2023-08-03T09:42:46.3271907Z [xUnit.net 00:00:06.84]         |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2023-08-03T09:42:46.3276252Z [xUnit.net 00:00:06.84]         |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
2023-08-03T09:42:46.3280513Z [xUnit.net 00:00:06.84]         |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2023-08-03T09:42:46.3284823Z [xUnit.net 00:00:06.84]         |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
2023-08-03T09:42:46.3293086Z [xUnit.net 00:00:06.84]         |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
2023-08-03T09:42:46.3297443Z [xUnit.net 00:00:06.84]         |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
2023-08-03T09:42:46.3301683Z [xUnit.net 00:00:06.84]         |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
2023-08-03T09:42:46.3305832Z [xUnit.net 00:00:06.84]         |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
2023-08-03T09:42:46.3309976Z [xUnit.net 00:00:06.84]         |    at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
2023-08-03T09:42:46.3314434Z [xUnit.net 00:00:06.84]         |    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
2023-08-03T09:42:46.3318908Z [xUnit.net 00:00:06.84]         |    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
2023-08-03T09:42:46.3323415Z [xUnit.net 00:00:06.85]         |    at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
2023-08-03T09:42:46.3328512Z [xUnit.net 00:00:06.85]         |    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
2023-08-03T09:42:46.3334415Z [xUnit.net 00:00:06.85]         |    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
2023-08-03T09:42:46.3337504Z [xUnit.net 00:00:06.85]         |    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
2023-08-03T09:42:46.3343513Z [xUnit.net 00:00:06.85]         |    at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 141
2023-08-03T09:42:46.3348087Z [xUnit.net 00:00:06.85]         |    at Interop.FunctionalTests.Http3.Http3RequestTests.POST_ServerCompletesWithoutReadingRequestBody_ClientGetsResponse() in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/Http3/Http3RequestTests.cs:line 363
2023-08-03T09:42:46.3350103Z [xUnit.net 00:00:06.85]         |    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 264
2023-08-03T09:42:46.3354304Z [xUnit.net 00:00:06.85]         | --- End of stack trace from previous location ---
2023-08-03T09:42:46.3357996Z [xUnit.net 00:00:06.85]         |    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
2023-08-03T09:42:46.3375404Z [xUnit.net 00:00:06.85]         |    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
2023-08-03T09:42:46.3376695Z [xUnit.net 00:00:06.85]         | [0.018s] TestLifetime Information: Finished test POST_ServerCompletesWithoutReadingRequestBody_ClientGetsResponse in 0.0167601s
2023-08-03T09:42:46.3377309Z [xUnit.net 00:00:06.85]       System.InvalidOperationException : Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
2023-08-03T09:42:46.3378003Z [xUnit.net 00:00:06.85]       To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=361851&view=results

**Comment by wtgodbe** [comment]
@adityamandaleeka this is from helix-matrix in 7.0, is there a known issue/fix here or should we just quarantine/skip on debian11arm64?

**Comment by adityamandaleeka** [comment]
@wtgodbe Was this passing before and just started to fail?

Based on the message it looks like we're not setting up the cert correctly. I don't think that should be arch-specific in any way so I'm confused about why it would work in some cases and not others.

We should understand this in any case. I'll drop it in the RC2 milestone so we can investigate after 8.0 stuff is wrapped up.

@amcasey assigning this to you since it's a Kestrel thing. We can rebalance as needed.

**Comment by wtgodbe** [comment]
I don't see any other failures in the history. To be clear this is only in 7.0

**Comment by amcasey** [comment]
It's not hard to imagine our cert store emulator failing in some linux environments, but I wouldn't expect that to be a new issue.  I guess it's possible a test box got into a bad state?
