### ISSUE TITLE
Improve error report on HotReloadAgent

### ISSUE THREAD

**Issue by isadorasophia** [dotnet/aspnetcore#49941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hot Reload may fail while applying code changes, [see this example](https://github.com/dotnet/runtime/issues/90037) on applying changes while debugging in VS. 

While the javascript stack showed useful information regarding the error:
```
Error: System.TypeLoadException: EnC: we do not support patching of existing table cols. token=0x0200000f
   at System.Reflection.Metadata.MetadataUpdater.ApplyUpdate(:7222/Assembly assembly, ReadOnlySpan`1 metadataDelta, ReadOnlySpan`1 ilDelta, ReadOnlySpan`1 pdbDelta)
   at Microsoft.Extensions.HotReload.HotReloadAgent.ApplyDeltas(:7222/IReadOnlyList`1 deltas)
   at Microsoft.AspNetCore.Components.WebAssembly.HotReload.WebAssemblyHotReload.ApplyHotReloadDelta(:7222/String moduleIdString, Byte[] metadataDelta, Byte[] ilDelta, Byte[] pdbBytes)
...
```

This is what the user sees in the output window:
```
20:46 51.50 BlazorApp14.Server (Web assembly): Sending updates to running application
20:46 51.56 BlazorApp14.Server (Web assembly): [Error] Applying updates failed: 
20:46 51.56 BlazorApp14.Server (Web assembly): [Error] Applying updates failed: The following error occurred when trying to apply your edits to the running application. 
20:46 51.57 Exception thrown for Apply Code Updates: 0x80131500 - The following error occurred when trying to apply your edits to the running application. The following error occurred when trying to apply your edits to the running application. 
20:46 51.57 Stack trace for WebToolsException:
   at Microsoft.WebTools.ProjectSystem.Components.HotReload.ProjectHotReloadSession.<ApplyUpdatesAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Debugger.Shared.Utilities.LoggerExtensions.<LogOnExceptionAsync>d__3.MoveNext()
20:46 51.57 An unexpected error has occurred, any pending updates have been discarded.
```

**Problems**
1. The error is reported twice.
2. The second error message just shows the following reason: 
`"The following error occurred when trying to apply your edits to the running application."`

**Proposal**
We should propagate the error message back to the user. If I understand correctly, [the current code only logs the error to the debug output](https://github.com/dotnet/aspnetcore/blob/9344b153c00d64c2fec3c07b8ecd178dd666732e/src/Components/WebAssembly/WebAssembly/src/HotReload/HotReloadAgent.cs#L222C12-L222C33), and not back to the user.

This is specifically for scenarios where we are applying code changes to a hot reload agent.

### Expected Behavior

The error message is correctly plumbed through to the user.

### Steps To Reproduce

See [issue](https://github.com/dotnet/runtime/issues/90037).

### .NET Version

7.0.203

**Comment by lambdageek** [comment]
> If I understand correctly, [the current code only logs the error to the debug output](https://github.com/dotnet/aspnetcore/blob/9344b153c00d64c2fec3c07b8ecd178dd666732e/src/Components/WebAssembly/WebAssembly/src/HotReload/HotReloadAgent.cs#L222C12-L222C33), and not back to the user.

This is  due to 
https://github.com/dotnet/aspnetcore/blob/28e5590576cbd72a61c5f07c1d212f26ab16594c/src/Components/WebAssembly/WebAssembly/src/HotReload/WebAssemblyHotReload.cs#L50

a log callback that sends results back through the hot reload websocket would be better...

---

Additionally, we would ideally extend the `try` clause to also cover this line

https://github.com/dotnet/aspnetcore/blob/9344b153c00d64c2fec3c07b8ecd178dd666732e/src/Components/WebAssembly/WebAssembly/src/HotReload/HotReloadAgent.cs#L197

So that we log exceptios from `MetadataUpdater.ApplyUpdate` (which Mono can throw sometimes if there are issues).

**Comment by captainsafia** [comment]
@isadorasophia Can you clarify what you mean by "back to the user" here?

> If I understand correctly, [the current code only logs the error to the debug output](https://github.com/dotnet/aspnetcore/blob/9344b153c00d64c2fec3c07b8ecd178dd666732e/src/Components/WebAssembly/WebAssembly/src/HotReload/HotReloadAgent.cs#L222C12-L222C33), and not back to the user.

AFAIK, the logging behavior here seems to actually be coming from VS's hot reload logic [here](https://github.com/dotnet/project-system/blob/f61337bf09571f8392cdd2219a31f2238aa5aa1e/src/Microsoft.VisualStudio.ProjectSystem.Managed.VS/ProjectSystem/VS/HotReload/ProjectHotReloadSession.cs#L185).

**Comment by PreethikaSelvam** [comment]
Hi @isadorasophia,

This issue was reproducible with the reported SDK version, **.NET 7.0.203**. However, it could not be reproduced with later SDK versions, including **.NET 8**, **.NET 9**, and **.NET 10**. Based on our validation, the issue appears to have been resolved in newer releases. We recommend upgrading to the latest supported .NET SDK version to avoid encountering this issue.
