### ISSUE TITLE
Quarantine CanRenderLargeComponentsWithServerRenderMode

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#49975]
## Failing Test(s)

- Microsoft.AspNetCore.Components.E2ETests.ServerRenderingTests.RenderingTest.CanRenderLargeComponentsWithServerRenderMode

## Error Message

```text
OpenQA.Selenium.StaleElementReferenceException : stale element reference: stale element not found
  (Session info: chrome=115.0.5790.170); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
```

## Stacktrace

<details>

```text
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebElement.Execute(String commandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebElement.get_Text()
   at Microsoft.AspNetCore.Components.E2ETests.ServerRenderingTests.RenderingTest.CanRenderLargeComponentsWithServerRenderMode() in /home/vsts/work/1/s/src/Components/test/E2ETest/ServerRenderingTests/RenderingTest.cs:line 34
   at InvokeStub_RenderingTest.CanRenderLargeComponentsWithServerRenderMode(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```
</details>

## Logs

<details>

```text

```
</details>

## Build

- https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=368871

**Comment by halter73** [comment]
Quarantined by #49976

**Comment by SteveSandersonMS** [comment]
Test fixed in https://github.com/dotnet/aspnetcore/pull/54340

**Comment by sebastienros** [comment]
Passing since un-quarantined.
