### ISSUE TITLE
Quarantine <FAILING_TEST_NAME>

### ISSUE THREAD

**Issue by adityamandaleeka** [dotnet/aspnetcore#49974]
## Failing Test(s)

- Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate

## Error Message

```text
System.TimeoutException : The operation has timed out.
```

## Stacktrace

<details>

```text
Stack Trace:
2023-08-09T21:48:20.9959339Z      at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 123
2023-08-09T21:48:20.9959367Z    at Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate(Boolean fin) in /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs:line 699
2023-08-09T21:48:20.9959411Z    at Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate(Boolean fin) in /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs:line 703
```
</details>

## Logs

<details>

```text
2023-08-09T21:48:20.9956059Z [xUnit.net 00:01:12.98]     Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate(fin: True) [FAIL]
2023-08-09T21:48:20.9956308Z [xUnit.net 00:01:12.99]       System.TimeoutException : The operation has timed out.
2023-08-09T21:48:20.9956366Z [xUnit.net 00:01:12.99]       Stack Trace:
2023-08-09T21:48:20.9956391Z [xUnit.net 00:01:12.99]         /_/src/Shared/TaskExtensions.cs(123,0): at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber)
2023-08-09T21:48:20.9956420Z [xUnit.net 00:01:12.99]         /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs(699,0): at Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate(Boolean fin)
2023-08-09T21:48:20.9956466Z [xUnit.net 00:01:12.99]         /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs(703,0): at Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate(Boolean fin)
2023-08-09T21:48:20.9956507Z [xUnit.net 00:01:12.99]         --- End of stack trace from previous location ---
2023-08-09T21:48:20.9956530Z [xUnit.net 00:01:12.99]       Output:
2023-08-09T21:48:20.9956721Z [xUnit.net 00:01:12.99]         | [0.066s] TestLifetime Information: Starting test HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate-True at 2023-08-09T21:47:43
2023-08-09T21:48:20.9956749Z [xUnit.net 00:01:12.99]         | [0.080s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting starting
2023-08-09T21:48:20.9956772Z [xUnit.net 00:01:12.99]         | [0.085s] Microsoft.Hosting.Lifetime Information: Now listening on: https://127.0.0.1:41073
2023-08-09T21:48:20.9956794Z [xUnit.net 00:01:12.99]         | [0.085s] Microsoft.AspNetCore.Hosting.Diagnostics Debug: Loaded hosting startup assembly Sockets.FunctionalTests
2023-08-09T21:48:20.9956816Z [xUnit.net 00:01:12.99]         | [0.085s] Microsoft.Hosting.Lifetime Information: Application started. Press Ctrl+C to shut down.
2023-08-09T21:48:20.9956837Z [xUnit.net 00:01:12.99]         | [0.085s] Microsoft.Hosting.Lifetime Information: Hosting environment: Production
2023-08-09T21:48:20.9956861Z [xUnit.net 00:01:13.00]         | [0.085s] Microsoft.Hosting.Lifetime Information: Content root path: /datadisks/disk1/work/AA51099F/w/B6D909AA/e/
2023-08-09T21:48:20.9956884Z [xUnit.net 00:01:13.00]         | [0.085s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting started
2023-08-09T21:48:20.9956998Z [xUnit.net 00:01:13.00]         | [0.085s] Microsoft.AspNetCore.Server.Kestrel Debug: TestServer is listening on port 41073
2023-08-09T21:48:20.9957028Z [xUnit.net 00:01:13.00]         | [0.866s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMSP48NDJBF5" accepted.
2023-08-09T21:48:20.9957054Z [xUnit.net 00:01:13.00]         | [0.866s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMSP48NDJBF5" started.
2023-08-09T21:48:20.9957081Z [xUnit.net 00:01:13.00]         | [0.870s] Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware Debug: Connection 0HMSP48NDJBF5 established using the following protocol: Tls13
2023-08-09T21:48:20.9957107Z [xUnit.net 00:01:13.00]         | [0.870s] Microsoft.AspNetCore.Hosting.Diagnostics Information: Request starting HTTP/1.1 GET https:/// - - -
2023-08-09T21:48:20.9957131Z [xUnit.net 00:01:13.00]         | [7.082s] Microsoft.AspNetCore.Server.Kestrel.BadRequests Debug: Connection id "0HMSP48NDJBF5", Request id "0HMSP48NDJBF5:00000001": the connection was closed because the response was not read by the client at the specified minimum data rate.
2023-08-09T21:48:20.9957361Z [xUnit.net 00:01:13.00]         | [7.082s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HMSP48NDJBF5" sending FIN because: "The connection was timed out by the server because the response was not read by the client at the specified minimum data rate."
2023-08-09T21:48:20.9957486Z [xUnit.net 00:01:13.00]         | [7.082s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMSP48NDJBF5" disconnecting.
2023-08-09T21:48:20.9957513Z [xUnit.net 00:01:13.00]         | [7.102s] Microsoft.AspNetCore.Hosting.Diagnostics Information: Request finished HTTP/1.1 GET https:/// - 200 268435456 - 6232.1146ms
2023-08-09T21:48:20.9957537Z [xUnit.net 00:01:13.00]         | [7.102s] Microsoft.AspNetCore.Server.Kestrel.BadRequests Debug: Connection id "0HMSP48NDJBF5" request processing ended abnormally.
2023-08-09T21:48:20.9957563Z [xUnit.net 00:01:13.00]         | System.IO.IOException: The read operation failed, see inner exception.
2023-08-09T21:48:20.9957736Z [xUnit.net 00:01:13.00]         |  ---> Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was timed out by the server because the response was not read by the client at the specified minimum data rate.
2023-08-09T21:48:20.9957796Z [xUnit.net 00:01:13.00]         |    at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
2023-08-09T21:48:20.9957822Z [xUnit.net 00:01:13.00]         |    at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
2023-08-09T21:48:20.9957845Z [xUnit.net 00:01:13.00]         |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.DuplexPipeStream.ReadAsyncInternal(Memory`1 destination, CancellationToken cancellationToken) in /_/src/Shared/ServerInfrastructure/DuplexPipeStream.cs:line 121
2023-08-09T21:48:20.9957898Z [xUnit.net 00:01:13.00]         |    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
2023-08-09T21:48:20.9957923Z [xUnit.net 00:01:13.00]         |    at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
2023-08-09T21:48:20.9958014Z [xUnit.net 00:01:13.00]         |    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
2023-08-09T21:48:20.9958043Z [xUnit.net 00:01:13.00]         |    at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
2023-08-09T21:48:20.9958068Z [xUnit.net 00:01:13.00]         |    --- End of inner exception stack trace ---
2023-08-09T21:48:20.9958090Z [xUnit.net 00:01:13.00]         |    at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
2023-08-09T21:48:20.9958114Z [xUnit.net 00:01:13.00]         |    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
2023-08-09T21:48:20.9958191Z [xUnit.net 00:01:13.00]         |    at System.IO.Pipelines.StreamPipeReader.<ReadInternalAsync>g__Core|40_0(StreamPipeReader reader, Nullable`1 minimumSize, CancellationTokenSource tokenSource, CancellationToken cancellationToken)
2023-08-09T21:48:20.9958309Z [xUnit.net 00:01:13.00]         |    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
2023-08-09T21:48:20.9958338Z [xUnit.net 00:01:13.00]         |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application) in /_/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs:line 649
2023-08-09T21:48:20.9958388Z [xUnit.net 00:01:13.00]         |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application) in /_/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs:line 576
2023-08-09T21:48:20.9958485Z [xUnit.net 00:01:13.00]         | [7.103s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMSP48NDJBF5" stopped.
2023-08-09T21:48:20.9958512Z [xUnit.net 00:01:13.00]         | [37.106s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting stopping
2023-08-09T21:48:20.9958536Z [xUnit.net 00:01:13.00]         | [37.106s] Microsoft.Hosting.Lifetime Information: Application is shutting down...
2023-08-09T21:48:20.9958558Z [xUnit.net 00:01:13.00]         | [37.106s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting stopped
2023-08-09T21:48:20.9958710Z [xUnit.net 00:01:13.00]         | [37.108s] Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests Error: Test threw an exception.
2023-08-09T21:48:20.9958741Z [xUnit.net 00:01:13.00]         | System.TimeoutException: The operation has timed out.
2023-08-09T21:48:20.9958766Z [xUnit.net 00:01:13.00]         |    at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 123
2023-08-09T21:48:20.9958790Z [xUnit.net 00:01:13.00]         |    at Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate(Boolean fin) in /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs:line 699
2023-08-09T21:48:20.9958840Z [xUnit.net 00:01:13.00]         |    at Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate(Boolean fin) in /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs:line 703
2023-08-09T21:48:20.9958970Z [xUnit.net 00:01:13.00]         |    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 264
2023-08-09T21:48:20.9959003Z [xUnit.net 00:01:13.00]         | --- End of stack trace from previous location ---
2023-08-09T21:48:20.9959034Z [xUnit.net 00:01:13.00]         |    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
2023-08-09T21:48:20.9959060Z [xUnit.net 00:01:13.00]         |    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
2023-08-09T21:48:20.9959089Z [xUnit.net 00:01:13.00]         | [37.108s] TestLifetime Information: Finished test HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate-True in 37.0420696s
2023-08-09T21:48:20.9959165Z   Failed Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate(fin: True) [37 s]
2023-08-09T21:48:20.9959192Z   Error Message:
2023-08-09T21:48:20.9959217Z    System.TimeoutException : The operation has timed out.
2023-08-09T21:48:20.9959245Z   Stack Trace:
2023-08-09T21:48:20.9959339Z      at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 123
2023-08-09T21:48:20.9959367Z    at Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate(Boolean fin) in /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs:line 699
2023-08-09T21:48:20.9959411Z    at Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate(Boolean fin) in /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs:line 703
2023-08-09T21:48:20.9959455Z --- End of stack trace from previous location ---
2023-08-09T21:48:20.9959478Z   Standard Output Messages:
2023-08-09T21:48:20.9959504Z  | [0.066s] TestLifetime Information: Starting test HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate-True at 2023-08-09T21:47:43
2023-08-09T21:48:20.9959526Z  | [0.080s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting starting
2023-08-09T21:48:20.9959599Z  | [0.085s] Microsoft.Hosting.Lifetime Information: Now listening on: https://127.0.0.1:41073
2023-08-09T21:48:20.9959732Z  | [0.085s] Microsoft.AspNetCore.Hosting.Diagnostics Debug: Loaded hosting startup assembly Sockets.FunctionalTests
2023-08-09T21:48:20.9959766Z  | [0.085s] Microsoft.Hosting.Lifetime Information: Application started. Press Ctrl+C to shut down.
2023-08-09T21:48:20.9959792Z  | [0.085s] Microsoft.Hosting.Lifetime Information: Hosting environment: Production
2023-08-09T21:48:20.9959817Z  | [0.085s] Microsoft.Hosting.Lifetime Information: Content root path: /datadisks/disk1/work/AA51099F/w/B6D909AA/e/
2023-08-09T21:48:20.9959845Z  | [0.085s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting started
2023-08-09T21:48:20.9959872Z  | [0.085s] Microsoft.AspNetCore.Server.Kestrel Debug: TestServer is listening on port 41073
2023-08-09T21:48:20.9959899Z  | [0.866s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMSP48NDJBF5" accepted.
2023-08-09T21:48:20.9959926Z  | [0.866s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMSP48NDJBF5" started.
2023-08-09T21:48:20.9959953Z  | [0.870s] Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware Debug: Connection 0HMSP48NDJBF5 established using the following protocol: Tls13
2023-08-09T21:48:20.9959978Z  | [0.870s] Microsoft.AspNetCore.Hosting.Diagnostics Information: Request starting HTTP/1.1 GET https:/// - - -
2023-08-09T21:48:20.9960080Z  | [7.082s] Microsoft.AspNetCore.Server.Kestrel.BadRequests Debug: Connection id "0HMSP48NDJBF5", Request id "0HMSP48NDJBF5:00000001": the connection was closed because the response was not read by the client at the specified minimum data rate.
2023-08-09T21:48:20.9960139Z  | [7.082s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HMSP48NDJBF5" sending FIN because: "The connection was timed out by the server because the response was not read by the client at the specified minimum data rate."
2023-08-09T21:48:20.9960247Z  | [7.082s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMSP48NDJBF5" disconnecting.
2023-08-09T21:48:20.9960271Z  | [7.102s] Microsoft.AspNetCore.Hosting.Diagnostics Information: Request finished HTTP/1.1 GET https:/// - 200 268435456 - 6232.1146ms
2023-08-09T21:48:20.9960295Z  | [7.102s] Microsoft.AspNetCore.Server.Kestrel.BadRequests Debug: Connection id "0HMSP48NDJBF5" request processing ended abnormally.
2023-08-09T21:48:20.9960322Z  | System.IO.IOException: The read operation failed, see inner exception.
2023-08-09T21:48:20.9960411Z  |  ---> Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was timed out by the server because the response was not read by the client at the specified minimum data rate.
2023-08-09T21:48:20.9960445Z  |    at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
2023-08-09T21:48:20.9960474Z  |    at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
2023-08-09T21:48:20.9960502Z  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.DuplexPipeStream.ReadAsyncInternal(Memory`1 destination, CancellationToken cancellationToken) in /_/src/Shared/ServerInfrastructure/DuplexPipeStream.cs:line 121
2023-08-09T21:48:20.9960531Z  |    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
2023-08-09T21:48:20.9960558Z  |    at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
2023-08-09T21:48:20.9960579Z  |    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
2023-08-09T21:48:20.9960704Z  |    at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
2023-08-09T21:48:20.9960729Z  |    --- End of inner exception stack trace ---
2023-08-09T21:48:20.9960796Z  |    at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
2023-08-09T21:48:20.9960817Z  |    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
2023-08-09T21:48:20.9960839Z  |    at System.IO.Pipelines.StreamPipeReader.<ReadInternalAsync>g__Core|40_0(StreamPipeReader reader, Nullable`1 minimumSize, CancellationTokenSource tokenSource, CancellationToken cancellationToken)
2023-08-09T21:48:20.9960861Z  |    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
2023-08-09T21:48:20.9960882Z  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application) in /_/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs:line 649
2023-08-09T21:48:20.9961965Z  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application) in /_/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs:line 576
2023-08-09T21:48:20.9962101Z  | [7.103s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMSP48NDJBF5" stopped.
2023-08-09T21:48:20.9962125Z  | [37.106s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting stopping
2023-08-09T21:48:20.9962147Z  | [37.106s] Microsoft.Hosting.Lifetime Information: Application is shutting down...
2023-08-09T21:48:20.9962168Z  | [37.106s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting stopped
2023-08-09T21:48:20.9962189Z  | [37.108s] Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests Error: Test threw an exception.
2023-08-09T21:48:20.9962211Z  | System.TimeoutException: The operation has timed out.
2023-08-09T21:48:20.9962233Z  |    at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 123
2023-08-09T21:48:20.9962345Z  |    at Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate(Boolean fin) in /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs:line 699
2023-08-09T21:48:20.9962387Z  |    at Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate(Boolean fin) in /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs:line 703
2023-08-09T21:48:20.9962427Z  |    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 264
2023-08-09T21:48:20.9962449Z  | --- End of stack trace from previous location ---
2023-08-09T21:48:20.9962471Z  |    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
2023-08-09T21:48:20.9962493Z  |    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
2023-08-09T21:48:20.9962514Z  | [37.108s] TestLifetime Information: Finished test HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate-True in 37.0420696s
2023-08-09T21:48:20.9962597Z 
2023-08-09T21:48:20.9962627Z 
```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=368651&view=results

**Comment by adityamandaleeka** [comment]
@amcasey

**Comment by amcasey** [comment]
On my box, a successful run takes 6 seconds, so it might just be slow.  I'll try to rediscover what it's doing.

**Comment by amcasey** [comment]
From the line numbers, it seems like it's timing out on `await appFuncCompleted.Task.DefaultTimeout();`, but that appears to be set _before_ `aborted.Task`, which has already been verified by that point.

I'm at 110 consecutive passes locally.

**Comment by amcasey** [comment]
A local run _did_ time out in `Microsoft.AspNetCore.Server.Kestrel.Core.Tests.HttpConnectionTests.WriteDataRateTimeoutAbortsConnection`, which is closely related.

**Comment by halter73** [comment]
I just say this fail again on a Helix run for my PR targeting release/8.0. Was there ever a PR to quarantine this?

https://dev.azure.com/dnceng-public/public/_build/results?buildId=429697&view=ms.vss-test-web.build-test-results-tab&runId=9496742&resultId=123815&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab

**Comment by amcasey** [comment]
It was in the helix retry list, but I guess that's not enough.

**Comment by sebastienros** [comment]
Happening also with the non-https one. Using this issue to track both quarantined tests.

Details in this issue: https://github.com/dotnet/aspnetcore/issues/58169
