### ISSUE TITLE
Quarantine LongPollingUsesHttp2ByDefault

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#50180]
## Failing Test(s)

Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.LongPollingUsesHttp2ByDefault

This seems to have been failing a couple of times per day in the last week.

## Error Message

```text
Assert.Contains() Failure
Not found: (filter expression)
In value:  ConcurrentQueue<WriteContext> [Information Microsoft.AspNetCore.SignalR.Tests.InProcessTestServer: Starting test server..., Debug Microsoft.Extensions.Hosting.Internal.Host: Hosting starting, Debug Microsoft.AspNetCore.DataProtection.KeyManagement.DefaultKeyResolver: Repository contains no viable default key. Caller should generate a key with immediate activation., Debug Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider: Policy resolution states that a new key should be added to the key ring., Information Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: Creating key {a5c380c2-dc5d-40e8-bae9-90f566dbd955} with creation date 2023-08-17 21:42:00Z, activation date 2023-08-17 21:42:00Z, and expiration date 2023-11-15 21:42:00Z., ...]
```

## Stacktrace

<details>

```text
at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.LongPollingUsesHttp2ByDefault() in /_/src/SignalR/clients/csharp/Client/test/FunctionalTests/HubConnectionTests.cs:line 2402
--- End of stack trace from previous location ---
```
</details>

## Logs

<details>

```text
[0.002s] [TestLifetime] [Information] Starting test LongPollingUsesHttp2ByDefault at 2023-08-17T21:42:00
[0.004s] [Microsoft.AspNetCore.SignalR.Tests.InProcessTestServer] [Information] Starting test server...
[0.004s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting starting
[0.005s] [Microsoft.AspNetCore.DataProtection.KeyManagement.DefaultKeyResolver] [Debug] Repository contains no viable default key. Caller should generate a key with immediate activation.
[0.005s] [Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider] [Debug] Policy resolution states that a new key should be added to the key ring.
[0.005s] [Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager] [Information] Creating key {a5c380c2-dc5d-40e8-bae9-90f566dbd955} with creation date 2023-08-17 21:42:00Z, activation date 2023-08-17 21:42:00Z, and expiration date 2023-11-15 21:42:00Z.
[0.005s] [Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager] [Debug] Descriptor deserializer type for key {a5c380c2-dc5d-40e8-bae9-90f566dbd955} is 'Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
[0.005s] [Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager] [Debug] No key escrow sink found. Not writing key {a5c380c2-dc5d-40e8-bae9-90f566dbd955} to escrow.
[0.005s] [Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager] [Warning] No XML encryptor configured. Key {a5c380c2-dc5d-40e8-bae9-90f566dbd955} may be persisted to storage in unencrypted form.
[0.005s] [Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager] [Debug] Key cache expiration token triggered by 'CreateNewKey' operation.
[0.005s] [Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager] [Debug] Found key {a5c380c2-dc5d-40e8-bae9-90f566dbd955}.
[0.005s] [Microsoft.AspNetCore.DataProtection.KeyManagement.DefaultKeyResolver] [Debug] Considering key {a5c380c2-dc5d-40e8-bae9-90f566dbd955} with expiration date 2023-11-15 21:42:00Z as default key.
[0.005s] [Microsoft.AspNetCore.DataProtection.TypeForwardingActivator] [Debug] Forwarded activator type request from Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 to Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Culture=neutral, PublicKeyToken=adb9793829ddae60
[0.005s] [Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ManagedAuthenticatedEncryptorFactory] [Debug] Using managed symmetric algorithm 'System.Security.Cryptography.Aes'.
[0.005s] [Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ManagedAuthenticatedEncryptorFactory] [Debug] Using managed keyed hash algorithm 'System.Security.Cryptography.HMACSHA256'.
[0.005s] [Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider] [Debug] Using key {a5c380c2-dc5d-40e8-bae9-90f566dbd955} as the default key.
[0.005s] [Microsoft.AspNetCore.DataProtection.Internal.DataProtectionHostedService] [Debug] Key ring with default key {a5c380c2-dc5d-40e8-bae9-90f566dbd955} was loaded during application startup.
[0.006s] [Microsoft.AspNetCore.SignalR.Internal.DefaultHubProtocolResolver] [Debug] Registered SignalR Protocol: json, implemented by Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.
[0.006s] [Microsoft.AspNetCore.SignalR.Internal.DefaultHubProtocolResolver] [Debug] Registered SignalR Protocol: messagepack, implemented by Microsoft.AspNetCore.SignalR.Protocol.MessagePackHubProtocol.
[0.030s] [Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware] [Information] Certificate with thumbprint 470543E0FC19F3D4355457A8C22E78919EA9AA66 lacks the subjectAlternativeName (SAN) extension and may not be accepted by browsers.
[0.030s] [Microsoft.Hosting.Lifetime] [Information] Now listening on: https://127.0.0.1:36973
[0.030s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Debug] Loaded hosting startup assembly Microsoft.AspNetCore.SignalR.Client.FunctionalTests
[0.030s] [Microsoft.Hosting.Lifetime] [Information] Application started. Press Ctrl+C to shut down.
[0.030s] [Microsoft.Hosting.Lifetime] [Information] Hosting environment: Production
[0.030s] [Microsoft.Hosting.Lifetime] [Information] Content root path: /datadisks/disk1/work/A83B091C/w/C86E0AEA/e
[0.030s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting started
[0.030s] [Microsoft.AspNetCore.SignalR.Tests.InProcessTestServer] [Information] Test Server started
[0.031s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Starting HubConnection.
[0.031s] [Microsoft.AspNetCore.Http.Connections.Client.HttpConnection] [Debug] Starting HttpConnection.
[0.031s] [Microsoft.AspNetCore.Http.Connections.Client.HttpConnection] [Debug] Establishing connection with server at 'https://127.0.0.1:36973/default'.
[0.031s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMSVDAK4MDE1" accepted.
[0.032s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMSVDAK4MDE1" started.
[0.034s] [Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware] [Debug] Connection 0HMSVDAK4MDE1 established using the following protocol: Tls13
[0.035s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request starting HTTP/2 POST https://127.0.0.1:36973/default/negotiate?negotiateVersion=1 - - 0
[0.036s] [Microsoft.AspNetCore.Routing.Matching.DfaMatcher] [Debug] 1 candidate(s) found for the request path '/default/negotiate'
[0.036s] [Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware] [Debug] Request matched endpoint '/default/negotiate'
[0.036s] [Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler] [Debug] AuthenticationScheme: Bearer was not authenticated.
[0.036s] [Microsoft.AspNetCore.Routing.EndpointMiddleware] [Information] Executing endpoint '/default/negotiate'
[0.036s] [Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager] [Debug] New connection 5_xfEPKDRsQ8Upgv4TgmuQ created.
[0.036s] [Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher] [Debug] 5_xfEPKDRsQ8Upgv4TgmuQ - Sending negotiation response.
[0.036s] [Microsoft.AspNetCore.Routing.EndpointMiddleware] [Information] Executed endpoint '/default/negotiate'
[0.036s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request finished HTTP/2 POST https://127.0.0.1:36973/default/negotiate?negotiateVersion=1 - 200 316 application/json 1.4037ms
[0.037s] [Microsoft.AspNetCore.Http.Connections.Client.HttpConnection] [Debug] Established connection '5_xfEPKDRsQ8Upgv4TgmuQ' with the server.
[0.037s] [Microsoft.AspNetCore.Http.Connections.Client.HttpConnection] [Debug] Skipping transport WebSockets because it was disabled by the client.
[0.037s] [Microsoft.AspNetCore.Http.Connections.Client.HttpConnection] [Debug] Skipping transport ServerSentEvents because it was disabled by the client.
[0.037s] [Microsoft.AspNetCore.Http.Connections.Client.HttpConnection] [Debug] Starting transport 'LongPolling' with Url: https://127.0.0.1:36973/default.
[0.037s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport] [Information] Starting transport. Transfer mode: Text.
[0.037s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request starting HTTP/2 GET https://127.0.0.1:36973/default?id=atqf0rAc6TlVMPV-oRFWpw - - -
[0.038s] [Microsoft.AspNetCore.Routing.Matching.DfaMatcher] [Debug] 1 candidate(s) found for the request path '/default'
[0.039s] [Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware] [Debug] Request matched endpoint '/default'
[0.039s] [Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler] [Debug] AuthenticationScheme: Bearer was not authenticated.
[0.039s] [Microsoft.AspNetCore.Routing.EndpointMiddleware] [Information] Executing endpoint '/default'
[0.039s] [Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher] [Debug] 5_xfEPKDRsQ8Upgv4TgmuQ - Establishing new connection.
[0.039s] [Microsoft.AspNetCore.Routing.EndpointMiddleware] [Information] Executed endpoint '/default'
[0.039s] [Microsoft.AspNetCore.SignalR.HubConnectionHandler] [Debug] 5_xfEPKDRsQ8Upgv4TgmuQ - OnConnectedAsync started.
[0.039s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request finished HTTP/2 GET https://127.0.0.1:36973/default?id=atqf0rAc6TlVMPV-oRFWpw - 200 0 application/octet-stream 1.8908ms
[0.039s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport] [Debug] Starting receive loop.
[0.039s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport] [Debug] Starting the send loop.
[0.039s] [Microsoft.AspNetCore.Http.Connections.Client.HttpConnection] [Debug] Transport 'LongPolling' started.
[0.039s] [Microsoft.AspNetCore.Http.Connections.Client.HttpConnection] [Information] HttpConnection Started.
[0.039s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Information] Using HubProtocol 'json v1'.
[0.039s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Sending Hub Handshake.
[0.039s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport] [Debug] Sending 32 bytes to the server using url: https://127.0.0.1:36973/default?id=atqf0rAc6TlVMPV-oRFWpw.
[0.039s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request starting HTTP/2 GET https://127.0.0.1:36973/default?id=atqf0rAc6TlVMPV-oRFWpw - - -
[0.040s] [Microsoft.AspNetCore.Routing.Matching.DfaMatcher] [Debug] 1 candidate(s) found for the request path '/default'
[0.040s] [Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware] [Debug] Request matched endpoint '/default'
[0.040s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request starting HTTP/2 POST https://127.0.0.1:36973/default?id=atqf0rAc6TlVMPV-oRFWpw - - 32
[0.040s] [Microsoft.AspNetCore.Routing.Matching.DfaMatcher] [Debug] 1 candidate(s) found for the request path '/default'
[0.040s] [Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware] [Debug] Request matched endpoint '/default'
[0.042s] [Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler] [Debug] AuthenticationScheme: Bearer was not authenticated.
[0.042s] [Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler] [Debug] AuthenticationScheme: Bearer was not authenticated.
[0.042s] [Microsoft.AspNetCore.Routing.EndpointMiddleware] [Information] Executing endpoint '/default'
[0.042s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] 5_xfEPKDRsQ8Upgv4TgmuQ - Connection id "0HMSVDAK4MDE1", Request id "0HMSVDAK4MDE1:00000007": started reading request body.
[0.042s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] 5_xfEPKDRsQ8Upgv4TgmuQ - Connection id "0HMSVDAK4MDE1", Request id "0HMSVDAK4MDE1:00000007": done reading request body.
[0.042s] [Microsoft.AspNetCore.Routing.EndpointMiddleware] [Information] Executed endpoint '/default'
[0.042s] [Microsoft.AspNetCore.SignalR.Internal.DefaultHubProtocolResolver] [Debug] 5_xfEPKDRsQ8Upgv4TgmuQ - Found protocol implementation for requested protocol: json.
[0.042s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request finished HTTP/2 POST https://127.0.0.1:36973/default?id=atqf0rAc6TlVMPV-oRFWpw - 200 0 text/plain 2.0238ms
[0.042s] [Microsoft.AspNetCore.SignalR.HubConnectionContext] [Debug] 5_xfEPKDRsQ8Upgv4TgmuQ - Completed connection handshake. Using HubProtocol 'json'.
[0.042s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport] [Debug] Message(s) sent successfully.
[0.042s] [Microsoft.AspNetCore.Routing.EndpointMiddleware] [Information] Executing endpoint '/default'
[0.042s] [Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher] [Debug] 5_xfEPKDRsQ8Upgv4TgmuQ - Resuming existing connection.
[0.042s] [Microsoft.AspNetCore.Routing.EndpointMiddleware] [Information] Executed endpoint '/default'
[0.042s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request finished HTTP/2 GET https://127.0.0.1:36973/default?id=atqf0rAc6TlVMPV-oRFWpw - 200 3 application/octet-stream 2.7948ms
[0.042s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport] [Debug] Received messages from the server.
[0.042s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Handshake with server complete.
[0.042s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Receive loop starting.
[0.043s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Information] HubConnection started.
[0.043s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request starting HTTP/2 GET https://127.0.0.1:36973/default?id=atqf0rAc6TlVMPV-oRFWpw - - -
[0.043s] [Microsoft.AspNetCore.Routing.Matching.DfaMatcher] [Debug] 1 candidate(s) found for the request path '/default'
[0.043s] [Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware] [Debug] Request matched endpoint '/default'
[0.043s] [Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler] [Debug] AuthenticationScheme: Bearer was not authenticated.
[0.043s] [Microsoft.AspNetCore.Routing.EndpointMiddleware] [Information] Executing endpoint '/default'
[0.043s] [Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher] [Debug] 5_xfEPKDRsQ8Upgv4TgmuQ - Resuming existing connection.
[0.047s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Registering Invocation ID '1' for tracking.
[0.047s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Sending InvocationMessage message '1'.
[0.047s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Sending InvocationMessage message '1' completed.
[0.047s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport] [Debug] Sending 72 bytes to the server using url: https://127.0.0.1:36973/default?id=atqf0rAc6TlVMPV-oRFWpw.
[0.048s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request starting HTTP/2 POST https://127.0.0.1:36973/default?id=atqf0rAc6TlVMPV-oRFWpw - - 72
[0.048s] [Microsoft.AspNetCore.Routing.Matching.DfaMatcher] [Debug] 1 candidate(s) found for the request path '/default'
[0.048s] [Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware] [Debug] Request matched endpoint '/default'
[0.048s] [Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler] [Debug] AuthenticationScheme: Bearer was not authenticated.
[0.048s] [Microsoft.AspNetCore.Routing.EndpointMiddleware] [Information] Executing endpoint '/default'
[0.048s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] 5_xfEPKDRsQ8Upgv4TgmuQ - Connection id "0HMSVDAK4MDE1", Request id "0HMSVDAK4MDE1:0000000B": started reading request body.
[0.048s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] 5_xfEPKDRsQ8Upgv4TgmuQ - Connection id "0HMSVDAK4MDE1", Request id "0HMSVDAK4MDE1:0000000B": done reading request body.
[0.048s] [Microsoft.AspNetCore.Routing.EndpointMiddleware] [Information] Executed endpoint '/default'
[0.048s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request finished HTTP/2 POST https://127.0.0.1:36973/default?id=atqf0rAc6TlVMPV-oRFWpw - 200 0 text/plain 0.3202ms
[0.048s] [Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher] [Debug] 5_xfEPKDRsQ8Upgv4TgmuQ - Received hub invocation: InvocationMessage { InvocationId: "1", Target: "GetHttpProtocol", Arguments: [  ], StreamIds: [  ] }.
[0.048s] [Microsoft.AspNetCore.Routing.EndpointMiddleware] [Information] Executed endpoint '/default'
[0.048s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request finished HTTP/2 GET https://127.0.0.1:36973/default?id=atqf0rAc6TlVMPV-oRFWpw - 200 48 application/octet-stream 5.7692ms
[0.049s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport] [Debug] Message(s) sent successfully.
[0.049s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport] [Debug] Received messages from the server.
[0.049s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Processing 48 byte message from server.
[0.049s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Sending CloseMessage message.
[0.049s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Sending CloseMessage message completed.
[0.049s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport] [Debug] Sending 11 bytes to the server using url: https://127.0.0.1:36973/default?id=atqf0rAc6TlVMPV-oRFWpw.
[0.049s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Stopping HubConnection.
[0.049s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Terminating receive loop.
[0.049s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Waiting for the receive loop to terminate.
[0.049s] [Microsoft.AspNetCore.Http.Connections.Client.HttpConnection] [Debug] Disposing HttpConnection.
[0.049s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport] [Information] Transport is stopping.
[0.049s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request starting HTTP/2 GET https://127.0.0.1:36973/default?id=atqf0rAc6TlVMPV-oRFWpw - - -
[0.049s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request starting HTTP/2 POST https://127.0.0.1:36973/default?id=atqf0rAc6TlVMPV-oRFWpw - - 11
[0.049s] [Microsoft.AspNetCore.Routing.Matching.DfaMatcher] [Debug] 1 candidate(s) found for the request path '/default'
[0.049s] [Microsoft.AspNetCore.Routing.Matching.DfaMatcher] [Debug] 1 candidate(s) found for the request path '/default'
[0.049s] [Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware] [Debug] Request matched endpoint '/default'
[0.049s] [Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware] [Debug] Request matched endpoint '/default'
[0.049s] [Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler] [Debug] AuthenticationScheme: Bearer was not authenticated.
[0.049s] [Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler] [Debug] AuthenticationScheme: Bearer was not authenticated.
[0.049s] [Microsoft.AspNetCore.Routing.EndpointMiddleware] [Information] Executing endpoint '/default'
[0.049s] [Microsoft.AspNetCore.Routing.EndpointMiddleware] [Information] Executing endpoint '/default'
[0.049s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] 5_xfEPKDRsQ8Upgv4TgmuQ - Connection id "0HMSVDAK4MDE1", Request id "0HMSVDAK4MDE1:0000000F": started reading request body.
[0.049s] [Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher] [Debug] 5_xfEPKDRsQ8Upgv4TgmuQ - Resuming existing connection.
[0.049s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] 5_xfEPKDRsQ8Upgv4TgmuQ - Connection id "0HMSVDAK4MDE1", Request id "0HMSVDAK4MDE1:0000000F": done reading request body.
[0.050s] [Microsoft.AspNetCore.Routing.EndpointMiddleware] [Information] Executed endpoint '/default'
[0.050s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request finished HTTP/2 GET https://127.0.0.1:36973/default?id=atqf0rAc6TlVMPV-oRFWpw - 200 11 application/octet-stream 0.3792ms
[0.050s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport] [Debug] Received messages from the server.
[0.050s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request starting HTTP/2 GET https://127.0.0.1:36973/default?id=atqf0rAc6TlVMPV-oRFWpw - - -
[0.050s] [Microsoft.AspNetCore.Routing.Matching.DfaMatcher] [Debug] 1 candidate(s) found for the request path '/default'
[0.050s] [Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware] [Debug] Request matched endpoint '/default'
[0.050s] [Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler] [Debug] AuthenticationScheme: Bearer was not authenticated.
[0.050s] [Microsoft.AspNetCore.SignalR.HubConnectionHandler] [Debug] 5_xfEPKDRsQ8Upgv4TgmuQ - OnConnectedAsync ending.
[0.050s] [Microsoft.AspNetCore.Routing.EndpointMiddleware] [Information] Executing endpoint '/default'
[0.050s] [Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionDispatcher] [Debug] 5_xfEPKDRsQ8Upgv4TgmuQ - Resuming existing connection.
[0.050s] [Microsoft.AspNetCore.Http.Connections.Internal.Transports.LongPollingTransport] [Debug] 5_xfEPKDRsQ8Upgv4TgmuQ - Terminating Long Polling connection by sending 204 response.
[0.050s] [Microsoft.AspNetCore.Http.Connections.Internal.HttpConnectionManager] [Debug] 5_xfEPKDRsQ8Upgv4TgmuQ - Removing connection atqf0rAc6TlVMPV-oRFWpw from the list of connections.
[0.050s] [Microsoft.AspNetCore.Routing.EndpointMiddleware] [Information] Executed endpoint '/default'
[0.050s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request finished HTTP/2 GET https://127.0.0.1:36973/default?id=atqf0rAc6TlVMPV-oRFWpw - 204 - text/plain 0.3244ms
[0.051s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport] [Debug] The server is closing the connection.
[0.051s] [Microsoft.AspNetCore.Routing.EndpointMiddleware] [Information] Executed endpoint '/default'
[0.051s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport] [Debug] Receive loop stopped.
[0.051s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request finished HTTP/2 POST https://127.0.0.1:36973/default?id=atqf0rAc6TlVMPV-oRFWpw - 200 0 text/plain 1.3198ms
[0.051s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport] [Debug] Message(s) sent successfully.
[0.051s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport] [Debug] Send loop canceled.
[0.051s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport] [Debug] Send loop stopped.
[0.051s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport] [Debug] Transport stopped.
[0.051s] [Microsoft.AspNetCore.Http.Connections.Client.HttpConnection] [Information] HttpConnection Disposed.
[0.051s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Canceling all outstanding invocations.
[0.051s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] HubConnection stopped.
[0.051s] [Microsoft.AspNetCore.SignalR.Tests.InProcessTestServer] [Information] Start shutting down test server
[0.051s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting stopping
[0.051s] [Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets] [Debug] Connection id "0HMSVDAK4MDE1" received FIN.
[0.051s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Debug] Connection id "0HMSVDAK4MDE1" is closed. The last processed stream ID was 17.
[0.051s] [Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets] [Debug] Connection id "0HMSVDAK4MDE1" sending FIN because: "The Socket transport's send loop completed gracefully."
[0.051s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Debug] The connection queue processing loop for 0HMSVDAK4MDE1 completed.
[0.052s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMSVDAK4MDE1" stopped.
[0.053s] [Microsoft.Hosting.Lifetime] [Information] Application is shutting down...
[0.053s] [Microsoft.AspNetCore.SignalR.Tests.InProcessTestServer] [Information] Test server shut down
[0.053s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting stopped
[0.057s] [Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests] [Error] Test threw an exception.
Xunit.Sdk.ContainsException: Assert.Contains() Failure
Not found: (filter expression)
In value:  ConcurrentQueue<WriteContext> [Information Microsoft.AspNetCore.SignalR.Tests.InProcessTestServer: Starting test server..., Debug Microsoft.Extensions.Hosting.Internal.Host: Hosting starting, Debug Microsoft.AspNetCore.DataProtection.KeyManagement.DefaultKeyResolver: Repository contains no viable default key. Caller should generate a key with immediate activation., Debug Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider: Policy resolution states that a new key should be added to the key ring., Information Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: Creating key {a5c380c2-dc5d-40e8-bae9-90f566dbd955} with creation date 2023-08-17 21:42:00Z, activation date 2023-08-17 21:42:00Z, and expiration date 2023-11-15 21:42:00Z., ...]
   at Xunit.Assert.Contains[T](IEnumerable`1 collection, Predicate`1 filter) in /_/src/xunit.assert/Asserts/CollectionAsserts.cs:line 264
   at Microsoft.AspNetCore.SignalR.Client.FunctionalTests.HubConnectionTests.LongPollingUsesHttp2ByDefault() in /_/src/SignalR/clients/csharp/Client/test/FunctionalTests/HubConnectionTests.cs:line 2402
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
[0.057s] [TestLifetime] [Information] Finished test LongPollingUsesHttp2ByDefault in 0.0548184s
```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=377933

**Comment by BrennanConroy** [comment]
Dupe of https://github.com/dotnet/aspnetcore/issues/49966 but I'll close that one.

In the future please include logs. AzDo builds disappear after ~2 weeks so we lose the logs.
