### ISSUE TITLE
Navigate to a different page from SignalR hub event handler

### ISSUE THREAD

**Issue by pedroveiga99** [dotnet/aspnetcore#50286]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I'm trying to navigate to a different page using `NavigationManager.NavigateTo` from within a SignalR hub event handler in a Blazor WebAssembly application, but is encountering an assertion error. 

This is a simplified code snippet of what I'm doing.
```
protected async override Task OnInitializedAsync()
{
    hubConnection = new HubConnectionBuilder()
        // other hub configurations
        .Build();

    hubConnection.On("SomeMessage", async () =>
    {
        NavigationManager.NavigateTo("/somepage");
    });

    await hubConnection.StartAsync();
}
```
And I got this errror in the browser console.

```
dotnet.7.0.5.xiq5d284cr.js:5 Error: [MONO] * Assertion at /__w/1/s/src/mono/mono/metadata/class.c:2112, condition `<disabled>' not met

at xe (dotnet.7.0.5.xiq5d284cr.js:5:509)
at Object.je (dotnet.7.0.5.xiq5d284cr.js:5:792)
at _mono_wasm_trace_logger (dotnet.7.0.5.xiq5d284cr.js:14:104923)
at 00992dae:0x9a48
at 00992dae:0xa5a90
at 00992dae:0x1bfe89
at 00992dae:0x1bff18
at 00992dae:0x1bff5b
at 00992dae:0x1bff2e
at 00992dae:0x38f27
```
 I already tried calling the navigation inside InvokeAsync(); I tried creating an EventCallback in the OnInitialized method and then registering this as the handler. I tried running inside Task.Run. Nothing worked

### .NET Version

7.0.302

### Anything else?

.NET SDK:
 Version:   7.0.302
 Commit:    990cf98a27

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.302\

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  7.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by pedroveiga99** [comment]
After more digging up, I found that this was not the problem. I will be closing this issue has the new problem is not related to this.
