### ISSUE TITLE
Quarantine `ServerErrorNotificationTest.ShowsErrorNotification_OnError_Dismiss` and `ShowsErrorNotification_OnError_Reload`

### ISSUE THREAD

**Issue by MackinnonBuck** [dotnet/aspnetcore#50377]
## Failing Test(s)

- Microsoft.AspNetCore.Components.E2ETest.Tests.ServerErrorNotificationTest.ShowsErrorNotification_OnError_Dismiss
- Microsoft.AspNetCore.Components.E2ETest.Tests.ServerErrorNotificationTest.ShowsErrorNotification_OnError_Reload

## Error Message

```text
element click intercepted: Element ... is not clickable at point (765, 436). Other element would receive the click: <div id="components-reconnect-modal" ...
```

## Stacktrace

<details>

```text
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebElement.Execute(String commandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebElement.Click()
   at Microsoft.AspNetCore.Components.E2ETest.Tests.ErrorNotificationTest.ShowsErrorNotification_OnError_Dismiss() in /home/vsts/work/1/s/src/Components/test/E2ETest/Tests/ErrorNotificationTest.cs:line 45
   at InvokeStub_ErrorNotificationTest.ShowsErrorNotification_OnError_Dismiss(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```
</details>

<details>

```text
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebElement.Execute(String commandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebElement.Click()
   at Microsoft.AspNetCore.Components.E2ETest.Tests.ErrorNotificationTest.ShowsErrorNotification_OnError_Reload() in /home/vsts/work/1/s/src/Components/test/E2ETest/Tests/ErrorNotificationTest.cs:line 61
   at InvokeStub_ErrorNotificationTest.ShowsErrorNotification_OnError_Reload(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=388121&view=ms.vss-test-web.build-test-results-tab&runId=8314540&resultId=100194&paneView=debug

**Comment by BrennanConroy** [comment]
Unquarantined with https://github.com/dotnet/aspnetcore/pull/51079
