### ISSUE TITLE
Could not load file or assembly 'Microsoft.Extensions.Logging.AzureAppServices'

### ISSUE THREAD

**Issue by Eli-Black-Work** [dotnet/aspnetcore#50389]
### Description

I think I'm running into the same bug as https://github.com/dotnet/extensions/issues/2566

When starting my app on Azure App Service, I get this stack trace:
```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Logging.AzureAppServices, Version=6.0.20.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.Extensions.Logging.AzureAppServices, Version=6.0.20.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.AspNetCore.Hosting.AppServicesWebHostBuilderExtensions.<>c.<UseAzureAppServices>b__0_0(ILoggingBuilder builder)
   at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection services, Action`1 configure)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass8_0.<ConfigureLogging>b__0(IServiceCollection collection)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.<>c__DisplayClass10_0.<ConfigureServices>b__0(WebHostBuilderContext _, IServiceCollection services)
   at System.Action`2.Invoke(T1 arg1, T2 arg2)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at <redacted>.Serpentine.Program.RunAsync(String[] args) in <redacted>\Serpentine\Program.cs:line 14
   at <redacted>.Serpentine.Program.Main(String[] args) in <redacted>\\Serpentine\Program.cs:line 9
   at <redacted>.Serpentine.Program.<Main>(String[] args)
```

### Reproduction Steps

1. Publish app from Visual Studio
2. Try to run on Azure App Service

### Expected behavior

Doesn't crash

### Actual behavior

Crashes

### Regression?

Yes. I think this is related to which versions of .NET/ASP.NET are supported, similar to https://github.com/dotnet/extensions/issues/2566#issuecomment-622480085

### Configuration

```
<PropertyGroup>
	<TargetFramework>net6.0</TargetFramework>
</PropertyGroup>
<ItemGroup>
	<PackageReference Include="AsyncFixer" Version="1.6.0">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="ClosedXML" Version="0.101.0" />
	<PackageReference Include="IDisposableAnalyzers" Version="4.0.2">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Lib.AspNetCore.ServerSentEvents" Version="6.0.0" />
	<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.21.0" />
	<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.1" />
	<PackageReference Include="Microsoft.AspNetCore.Connections.Abstractions" Version="6.0.1" />
	<PackageReference Include="Microsoft.AspNetCore.Hosting.WindowsServices" Version="6.0.1" />
	<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="6.0.1" />
	<PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.0.0" />
	<PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.3.1" />
	<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.3.1" />
	<PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="7.0.0">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.Extensions.Logging.ApplicationInsights" Version="2.21.0" />
	<PackageReference Include="Microsoft.Extensions.Logging.AzureAppServices" Version="6.0.14" />
	<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="6.10.0" />
	<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.10.8" />
	<PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.4.33">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="NLog.Web.AspNetCore" Version="4.12.0" />
	<PackageReference Include="NSwag.AspNetCore" Version="13.10.8" />
	<PackageReference Include="NSwag.CodeGeneration.CSharp" Version="13.10.8" />
	<PackageReference Include="NSwag.Generation" Version="13.10.8" />
	<PackageReference Include="SecurityCodeScan.VS2019" Version="5.6.7">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
</ItemGroup>
```

**Comment by smitha-cgi** [comment]
I had the same issue with the following in my project file (.NET 6):

```
<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="6.0.0" />
<PackageReference Include="Microsoft.Extensions.Logging.AzureAppServices" Version="6.0.0" />
```

Seems like was publishing Microsoft.Extensions.Logging.AzureAppServices version 6.0.21 which doesn't match what the App Service is looking for. Changed it to the following and it now works:

```
<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="7.0.1" />
<PackageReference Include="Microsoft.Extensions.Logging.AzureAppServices" Version="6.0.20" />
```
