### ISSUE TITLE
Test crash in Libuv.FunctionalTests on (Alpine.314.Amd64.Open)Ubuntu.2004.Amd64.Open in 6.0

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#50403]
This has happened in at least the last 3 runs of helix-matrix in 6.0, only in Libuv.FunctionalTests & only on Alpine 3.14

https://dev.azure.com/dnceng-public/public/_build/results?buildId=387607&view=results

```text
2023-08-29T09:37:10.6808437Z Test Run Aborted with error System.Exception: One or more errors occurred.
2023-08-29T09:37:10.6808569Z  ---> System.Exception: Unable to read beyond the end of the stream.
2023-08-29T09:37:10.6808758Z    at System.IO.BinaryReader.Read7BitEncodedInt()
2023-08-29T09:37:10.6808776Z    at System.IO.BinaryReader.ReadString()
2023-08-29T09:37:10.6808792Z    at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.LengthPrefixCommunicationChannel.NotifyDataAvailable()
2023-08-29T09:37:10.6808806Z    at Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.TcpClientExtensions.MessageLoopAsync(TcpClient client, ICommunicationChannel channel, Action`1 errorHandler, CancellationToken cancellationToken)
2023-08-29T09:37:10.6808820Z    --- End of inner exception stack trace ---.
2023-08-29T09:37:10.6816818Z  Total time: 14.8254 Seconds
2023-08-29T09:37:10.6818424Z 
2023-08-29T09:37:10.6840994Z The active Test Run was aborted because the host process exited unexpectedly. Please inspect the call stack above, if available, to get more information about where the exception originated from.
2023-08-29T09:37:10.6841120Z The test running when the crash occurred: 
2023-08-29T09:37:10.6841139Z Microsoft.AspNetCore.Server.Kestrel.Libuv.FunctionalTests.MaxRequestBufferSizeTests.ServerShutsDownGracefullyWhenMaxRequestBufferSizeExceeded
2023-08-29T09:37:10.6841155Z Microsoft.AspNetCore.Server.Kestrel.Libuv.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate
2023-08-29T09:37:10.6841170Z Microsoft.AspNetCore.Server.Kestrel.Libuv.FunctionalTests.RequestTests.AbortingTheConnection
2023-08-29T09:37:10.6841184Z 
2023-08-29T09:37:10.6841210Z This test may, or may not be the source of the crash.
```

**Comment by wtgodbe** [comment]
@adityamandaleeka we're still seeing this test failure, is it an important one? Or should we just skip the test?

**Comment by wtgodbe** [comment]
https://dev.azure.com/dnceng-public/public/_build/results?buildId=483387&view=results

**Comment by adityamandaleeka** [comment]
I lean towards getting rid of the test... the libuv transport was marked obsolete back in .NET 5 (and the Socket-based transport was made the default all the way back in 2.1). The fact that this is failing on one OS on an unsupported version isn't terribly interesting IMO.

cc @amcasey

**Comment by amcasey** [comment]
I'm a little nervous since we made a patch in this area over the summer.

**Comment by amcasey** [comment]
Yep, this would be precisely what we touched
```
The test running when the crash occurred: 
Microsoft.AspNetCore.Server.Kestrel.Libuv.FunctionalTests.MaxRequestBufferSizeTests.ServerShutsDownGracefullyWhenMaxRequestBufferSizeExceeded
Microsoft.AspNetCore.Server.Kestrel.Libuv.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate
Microsoft.AspNetCore.Server.Kestrel.Libuv.FunctionalTests.RequestTests.AbortingTheConnection
```

**Comment by amcasey** [comment]
We had to improvise a little to get libuv to close the connection and slightly abused the PAL to do it.  It's possible either the PAL or libuv on alpine is unhappy as a result.

I wonder if we publish net6-on-alpine docker images?

**Comment by amcasey** [comment]
Looks like `ServerShutsDownGracefullyWhenMaxRequestBufferSizeExceeded` is the one that actually failed
```
[8.417s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Some connections failed to close gracefully during server shutdown.
```

**Comment by wtgodbe** [comment]
> Shall I add it to the helix retry list in 6.0?

From what I've seen, this test group fails every time - do you have reason to believe it'd work on retry?

**Comment by amcasey** [comment]
Nope.  Also fine with skipping it on Alpine.
