### ISSUE TITLE
WebApplicationFactory disposes host before StopAsync on background service is called

### ISSUE THREAD

**Issue by davidkaya** [dotnet/aspnetcore#50622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We have a background service where in the `StopAsync` method we resolve a scoped service using `IServiceProvider`. Our functional tests started failing because the `WebApplicationFactory` disposed the host before the `StopAsync` method is called/finishes and we get a `System.ObjectDisposedException : Cannot access a disposed object.` error.

```
[xUnit.net 00:00:00.93]     [Test Class Cleanup Failure (ServiceProviderDisposed.Tests.Tests)] System.AggregateException
  Failed ServiceProviderDisposed.Tests.Tests.Test [1 ms]
  Error Message:
   [Test Class Cleanup Failure (ServiceProviderDisposed.Tests.Tests)]: System.AggregateException : One or more hosted services failed to stop. (Cannot access a disposed object.
Object name: 'IServiceProvider'.)
---- System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'IServiceProvider'.
  Stack Trace:
     at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.DisposeAsync()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.Dispose(Boolean disposing)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.Dispose()
----- Inner Stack Trace -----
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.CreateScope(IServiceProvider provider)
   at ServiceProviderDisposed.DummyBackgroundService.StopAsync(CancellationToken cancellationToken) in C:\Repositories\Playground\Disposed\ServiceProviderDisposed\DummyBackgroundService.cs:line 24
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)

Failed!  - Failed:     1, Passed:     1, Skipped:     0, Total:     2, Duration: 91 ms - ServiceProviderDisposed.Tests.dll (net6.0)
```

I've found following issue which has been closed as "Completed" though: https://github.com/dotnet/aspnetcore/issues/29348

### Expected Behavior

`WebApplicationFactory` waits for `StopAsync` method in background services to finish and disposed the host after that.

### Steps To Reproduce

Following is a project that can be used to reproduce the issue https://github.com/davidkaya/ServiceProviderDisposedRepro

You might have to run `dotnet test` multiple times because the issue does not occur always, e.g. for me locally it happens 1 in 10 `dotnet test` executions on the reproduction repo.

### .NET Version

7.0.400

### Anything else?

`Microsoft.AspNetCore.Mvc.Testing` version is `6.0.21`
Target framework is net6.

**Comment by mitchdenny** [comment]
Hrm. I think it might have something to do with ```BackgroundService.StopAsync(...)``` if I call it last the problem seams to disappear.

**Comment by davidkaya** [comment]
Hello, I was not able to reply due to parental leave. Is there anything that will be done on this to fix the issue that is currently occurring or is the only way to have this working updating to .NET 8 and using `StoppingAsync` ?
