### ISSUE TITLE
Failed to load Blazor WebAssembly project in Production after upgrading to .NET 8 RC1

### ISSUE THREAD

**Issue by hankovich** [dotnet/aspnetcore#50719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After upgrading SDK and all packages from Preview 6 to RC1 locally my blazor application works fine, but after deploying it to production it fails to load.

### Expected Behavior

Application is loaded

### Exceptions (if any)

![image](https://github.com/dotnet/aspnetcore/assets/22914850/088eb451-778c-4485-ab5f-0b8251c657fc)

```
Error: Failed to start platform. Reason: Failed to load config file ./blazor.boot.json TypeError: Cannot read properties of undefined (reading 'length')
    at Qt (blazor.webassembly.js:1:52725)
    at async ln (blazor.webassembly.js:1:54419)

Uncaught (in promise) Failed to load config file ./blazor.boot.json TypeError: Cannot read properties of undefined (reading 'length')
```

### .NET Version

8.0.100-rc.1.23455.8

**Comment by hankovich** [comment]
@CrahunGit thank worked, thanks!

**Comment by TFreudi1** [comment]
For me that did'nt help.

**Comment by TFreudi1** [comment]
But as I see now the error is a bit different:
Error: Failed to start platform. Reason: TypeError: Cannot read properties of undefined (reading 'dotnet.wasm')
    at Vt (https://localhost:7182/_framework/blazor.webassembly.js:1:62226) {stack: 'Error: Failed to start platform. Reason: Type…182/_framework/blazor.webassembly.js:1:62226)', message: 'Failed to start platform. Reason: TypeError:…perties of undefined (reading 'dotnet.wasm')'}

Uncaught TypeError TypeError: Cannot convert undefined or null to object
    at <anonymous> (localhost꞉7182/_framework/blazor.webassembly.js:1:37659)
    at <anonymous> (localhost꞉7182/_framework/blazor.webassembly.js:1:38464)
    at start (localhost꞉7182/_framework/blazor.webassembly.js:1:46018)
    at Vt (localhost꞉7182/_framework/blazor.webassembly.js:1:62202)
    --- await ---
    at <anonymous> (localhost꞉7182/_framework/blazor.webassembly.js:1:63609)
    at <anonymous> (localhost꞉7182/_framework/blazor.webassembly.js:1:63686)

**Comment by TFreudi1** [comment]
Well Ok also solved, I must update the Nuget Packages ,too. But than also remove bin + obj. Now it works.

<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.0-rc.1.23421.29" />
<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.0-rc.1.23421.29" PrivateAssets="all" />

**Comment by TFreudi1** [comment]
I have to change this in the csproj. I guess it will also work if you check "Preview" in den Nuget-Manager Update Tab.

<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.0-rc.1.23421.29" />
<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.0-rc.1.23421.29" PrivateAssets="all" />

**Comment by Laftek** [comment]
Thanks @TFreudi1 it helped!!!
