### ISSUE TITLE
Added retry for CanLaunchPhotinoWebViewAndClickButton

### ISSUE THREAD

**Issue by halter73** [dotnet/aspnetcore#50802]
## Failing Test(s)

- Microsoft.AspNetCore.Components.WebViewE2E.Test.WebViewManagerE2ETests.CanLaunchPhotinoWebViewAndClickButton

## Error Message

```text
Assert.Contains() Failure
Not found: Test passed? True
In value:  Current directory: C:hwAB8C0932wC1AD0A34e
Current assembly: C:hwAB8C0932wC1AD0A34eMicrosoft.AspNetCore.Components.WebViewE2E.Test.dll
Adding new native path: C:hwAB8C0932wC1AD0A34e
untimeswin-x64
ative
New PATH env var: C:hwAB8C0932wC1AD0A34e
untimeswin-x64
ative;C:hwAB8C0932wC1AD0A34e;C:hwAB8C0932pdotnet-cli;C:python3Scripts;C:python3;C:Windowssystem32;C:Windows;C:WindowsSystem32Wbem;C:WindowsSystem32WindowsPowerShell1.0;C:WindowsSystem32OpenSSH;C:Program Filesdotnet;C:UsersVMAdminAppDataLocalMicrosoftWindowsApps;;C:Debuggersd;C:Program FilesDocker;C:Users
unnerAppDataLocalMicrosoftWindowsApps;C:hwAB8C0932wC1AD0A34e
odein
Found 347 files in this app:
C:hwAB8C0932wC1AD0A34eCastle.Core.dll
...
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.Components.WebViewE2E.Test.WebViewManagerE2ETests.CanLaunchPhotinoWebViewAndClickButton() in /_/src/Components/WebView/test/E2ETest/WebViewManagerE2ETests.cs:line 46
```
</details>

## Logs

<details>

```text
2023-09-18T13:06:47.2453969Z Running 'C:\h\w\AB8C0932\p\dotnet-cli/dotnet vstest Microsoft.AspNetCore.Components.WebViewE2E.Test.dll -lt'
2023-09-18T13:06:48.4610651Z 'C:\h\w\AB8C0932\p\dotnet-cli/dotnet vstest Microsoft.AspNetCore.Components.WebViewE2E.Test.dll -lt' completed with exit code '0'
2023-09-18T13:06:48.4615517Z Start running tests
2023-09-18T13:06:48.4625245Z Running non-quarantined tests.
2023-09-18T13:06:48.4625567Z Running 'C:\h\w\AB8C0932\p\dotnet-cli/dotnet test Microsoft.AspNetCore.Components.WebViewE2E.Test.dll --diag:C:\h\w\AB8C0932\w\C1AD0A34\uploads\vstest.log --logger xunit --logger "console;verbosity=normal" --blame-crash --blame-hang-timeout 15m --filter "Quarantined!=true|Quarantined=false"'
2023-09-18T13:06:48.5918880Z [dotnet test - 9/18/2023 1:06:48 PM]Logging to console
2023-09-18T13:06:48.5949793Z [dotnet test - 9/18/2023 1:06:48 PM +00:00]Argument list: 'Microsoft.AspNetCore.Components.WebViewE2E.Test.dll | --diag | C:\h\w\AB8C0932\w\C1AD0A34\uploads\vstest.log | --logger | xunit | --logger | console;verbosity=normal | --blame-crash | --blame-hang-timeout | 15m | --filter | Quarantined!=true|Quarantined=false'
2023-09-18T13:06:48.6042507Z [dotnet test - 9/18/2023 1:06:48 PM +00:00]Forwarding to 'C:\h\w\AB8C0932\p\dotnet-cli\sdk\9.0.100-alpha.1.23461.3\vstest.console.dll' with args "Microsoft.AspNetCore.Components.WebViewE2E.Test.dll | --diag:C:\h\w\AB8C0932\w\C1AD0A34\uploads\vstest.log | --logger:xunit | --logger:console;verbosity=normal | --testcasefilter:Quarantined!=true|Quarantined=false | --blame:CollectDump;CollectHangDump;TestTimeout=15m | --artifactsProcessingMode-collect | --testSessionCorrelationId:5192_07f6f7fb-f1ed-4aab-9aea-832b8f606505"
2023-09-18T13:06:48.6638573Z Microsoft (R) Test Execution Command Line Tool Version 17.8.0-preview-23407-02+d21ac0a0dfe6360fab8d9f4003003d41daa26ebb (x64)
2023-09-18T13:06:48.6638806Z Copyright (c) Microsoft Corporation.  All rights reserved.
2023-09-18T13:06:48.6676807Z 
2023-09-18T13:06:48.7919695Z Starting test execution, please wait...
2023-09-18T13:06:48.7923297Z Logging Vstest Diagnostics in file: C:\h\w\AB8C0932\w\C1AD0A34\uploads\vstest.log
2023-09-18T13:06:48.8248573Z A total of 1 test files matched the specified pattern.
2023-09-18T13:06:49.1354400Z Blame: Attaching crash dump utility to process testhost (7840).
2023-09-18T13:06:49.3555785Z Data collection : Logging DataCollector Diagnostics in file: C:\h\w\AB8C0932\w\C1AD0A34\uploads\vstest.datacollector.23-09-18_13-06-48_84142_5.log
2023-09-18T13:06:49.3559746Z Data collector 'Blame' message: VSTEST_DUMP_PATH is specified. Dump files will be saved in: C:\cores, and won't be added to attachments..
2023-09-18T13:06:49.3562524Z Logging TestHost Diagnostics in file: C:\h\w\AB8C0932\w\C1AD0A34\uploads\vstest.host.23-09-18_13-06-49_12043_5.log
2023-09-18T13:06:49.4862349Z [xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.3+1b45f5407b (64-bit .NET 8.0.0-rc.2.23457.7)
2023-09-18T13:06:50.0296804Z [xUnit.net 00:00:00.54]   Discovering: Microsoft.AspNetCore.Components.WebViewE2E.Test (method display = ClassAndMethod, method display options = None)
2023-09-18T13:06:50.0668573Z [xUnit.net 00:00:00.58]   Discovered:  Microsoft.AspNetCore.Components.WebViewE2E.Test (found 3 test cases)
2023-09-18T13:06:50.0713702Z [xUnit.net 00:00:00.59]   Starting:    Microsoft.AspNetCore.Components.WebViewE2E.Test (parallel test collections = on, max threads = 2)
2023-09-18T13:06:50.7084994Z [xUnit.net 00:00:01.14]     Microsoft.AspNetCore.Components.WebViewE2E.Test.WebViewManagerE2ETests.CanLaunchPhotinoWebViewAndClickButton [FAIL]
2023-09-18T13:06:50.7088642Z [xUnit.net 00:00:01.15]       Assert.Contains() Failure
2023-09-18T13:06:50.7091126Z [xUnit.net 00:00:01.15]       Not found: Test passed? True
2023-09-18T13:06:50.7093549Z [xUnit.net 00:00:01.15]       In value:  Current directory: C:\h\w\AB8C0932\w\C1AD0A34\e
2023-09-18T13:06:50.7096323Z [xUnit.net 00:00:01.15]                  Current assembly: C:\h\w\AB8C0932\w\C1AD0A34\e\Microsoft.AspNetCore.Components.WebViewE2E.Test.dll
2023-09-18T13:06:50.7099251Z [xUnit.net 00:00:01.15]                  Adding new native path: C:\h\w\AB8C0932\w\C1AD0A34\e\runtimes\win-x64\native
2023-09-18T13:06:50.7102313Z [xUnit.net 00:00:01.15]                  New PATH env var: C:\h\w\AB8C0932\w\C1AD0A34\e\runtimes\win-x64\native;C:\h\w\AB8C0932\w\C1AD0A34\e;C:\h\w\AB8C0932\p\dotnet-cli;C:\python3\Scripts\;C:\python3\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Users\VMAdmin\AppData\Local\Microsoft\WindowsApps;;C:\Debuggers\x64;C:\Program Files\Docker;C:\Users\runner\AppData\Local\Microsoft\WindowsApps;C:\h\w\AB8C0932\w\C1AD0A34\e\node\bin
2023-09-18T13:06:50.7105145Z [xUnit.net 00:00:01.15]                  Found 347 files in this app:

...

2023-09-18T13:06:50.7810551Z [xUnit.net 00:00:01.22]                  Creating BlazorWindow...
2023-09-18T13:06:50.7812170Z [xUnit.net 00:00:01.22]                  Hooking exception handler...
2023-09-18T13:06:50.7813812Z [xUnit.net 00:00:01.22]                  Setting up root components...
2023-09-18T13:06:50.7815419Z [xUnit.net 00:00:01.22]                  Running window...
2023-09-18T13:06:50.7817014Z [xUnit.net 00:00:01.22]                  RegisterWebMessageReceivedHandler...
2023-09-18T13:06:50.7818559Z [xUnit.net 00:00:01.22]                  Photino.NET: "Hello, world!".Load(http://0.0.0.0/subdir/)
2023-09-18T13:06:50.7820127Z [xUnit.net 00:00:01.22]                  Starting Photino window...
2023-09-18T13:06:50.7821805Z [xUnit.net 00:00:01.22]                  
2023-09-18T13:06:50.7823670Z [xUnit.net 00:00:01.22]       Stack Trace:
2023-09-18T13:06:50.7825341Z [xUnit.net 00:00:01.22]         /_/src/Components/WebView/test/E2ETest/WebViewManagerE2ETests.cs(46,0): at Microsoft.AspNetCore.Components.WebViewE2E.Test.WebViewManagerE2ETests.CanLaunchPhotinoWebViewAndClickButton()
2023-09-18T13:06:50.7826939Z [xUnit.net 00:00:01.22]         --- End of stack trace from previous location ---
2023-09-18T13:06:51.8779212Z [xUnit.net 00:00:02.39]   Finished:    Microsoft.AspNetCore.Components.WebViewE2E.Test
2023-09-18T13:06:51.9536860Z   Passed AlwaysTestTests.SuccessfulTests.GuaranteedUnquarantinedTest [2 ms]
2023-09-18T13:06:51.9539335Z   Failed Microsoft.AspNetCore.Components.WebViewE2E.Test.WebViewManagerE2ETests.CanLaunchPhotinoWebViewAndClickButton [439 ms]
2023-09-18T13:06:51.9540393Z   Error Message:
2023-09-18T13:06:51.9542852Z    Assert.Contains() Failure
2023-09-18T13:06:51.9542943Z Not found: Test passed? True
2023-09-18T13:06:51.9542985Z In value:  Current directory: C:\h\w\AB8C0932\w\C1AD0A34\e
2023-09-18T13:06:51.9543023Z            Current assembly: C:\h\w\AB8C0932\w\C1AD0A34\e\Microsoft.AspNetCore.Components.WebViewE2E.Test.dll
2023-09-18T13:06:51.9543220Z            Adding new native path: C:\h\w\AB8C0932\w\C1AD0A34\e\runtimes\win-x64\native
2023-09-18T13:06:51.9543476Z            New PATH env var: C:\h\w\AB8C0932\w\C1AD0A34\e\runtimes\win-x64\native;C:\h\w\AB8C0932\w\C1AD0A34\e;C:\h\w\AB8C0932\p\dotnet-cli;C:\python3\Scripts\;C:\python3\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Users\VMAdmin\AppData\Local\Microsoft\WindowsApps;;C:\Debuggers\x64;C:\Program Files\Docker;C:\Users\runner\AppData\Local\Microsoft\WindowsApps;C:\h\w\AB8C0932\w\C1AD0A34\e\node\bin
2023-09-18T13:06:51.9543599Z            Found 347 files in this app:

....

2023-09-18T13:06:51.9563807Z            Creating BlazorWindow...
2023-09-18T13:06:51.9563843Z            Hooking exception handler...
2023-09-18T13:06:51.9563878Z            Setting up root components...
2023-09-18T13:06:51.9563911Z            Running window...
2023-09-18T13:06:51.9563941Z            RegisterWebMessageReceivedHandler...
2023-09-18T13:06:51.9563978Z            Photino.NET: "Hello, world!".Load(http://0.0.0.0/subdir/)
2023-09-18T13:06:51.9564015Z            Starting Photino window...
2023-09-18T13:06:51.9564076Z            
2023-09-18T13:06:51.9592137Z   Stack Trace:
2023-09-18T13:06:51.9592991Z      at Microsoft.AspNetCore.Components.WebViewE2E.Test.WebViewManagerE2ETests.CanLaunchPhotinoWebViewAndClickButton() in /_/src/Components/WebView/test/E2ETest/WebViewManagerE2ETests.cs:line 46
2023-09-18T13:06:51.9593101Z --- End of stack trace from previous location ---
2023-09-18T13:06:51.9733248Z Data collector 'Blame' message: VSTEST_DUMP_PATH is specified. Dump files will be saved in: C:\cores, and won't be added to attachments..
2023-09-18T13:06:51.9746436Z Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.
2023-09-18T13:06:52.0535504Z Results File: C:\h\w\AB8C0932\w\C1AD0A34\e\TestResults\TestResults.xml
2023-09-18T13:06:52.0539672Z 
2023-09-18T13:06:52.0591357Z Test Run Failed.
2023-09-18T13:06:52.0592984Z Total tests: 2
2023-09-18T13:06:52.0594112Z      Passed: 1
2023-09-18T13:06:52.0595153Z      Failed: 1
2023-09-18T13:06:52.0605639Z  Total time: 3.1950 Seconds
2023-09-18T13:06:52.0741256Z [dotnet test - 9/18/2023 1:06:52 PM +00:00]No artifact found, post-processing won't run.
2023-09-18T13:06:52.0805774Z 'C:\h\w\AB8C0932\p\dotnet-cli/dotnet test Microsoft.AspNetCore.Components.WebViewE2E.Test.dll --diag:C:\h\w\AB8C0932\w\C1AD0A34\uploads\vstest.log --logger xunit --logger "console;verbosity=normal" --blame-crash --blame-hang-timeout 15m --filter "Quarantined!=true|Quarantined=false"' completed with exit code '1'
2023-09-18T13:06:52.0810578Z Failure in non-quarantined tests. Exit code: 1.
2023-09-18T13:06:52.0810779Z Running tests complete
```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=409057&view=ms.vss-test-web.build-test-results-tab&runId=8890224&resultId=124024&paneView=debug
https://dev.azure.com/dnceng-public/public/_build/results?buildId=409574&view=ms.vss-test-web.build-test-results-tab&runId=8906088&resultId=124032&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

@Eilon

**Comment by halter73** [comment]
The issue appears to be specific to the aspnetcore-helix-matrix Windows.Amd64.Server2022.Open queue.

**Comment by dasblinkenlight** [comment]
I ran into this problem when submitting a PR ([link to details](https://github.com/dotnet/aspnetcore/pull/51396/checks?check_run_id=17724750273)).

**Comment by SteveSandersonMS** [comment]
Unquarantined in https://github.com/dotnet/aspnetcore/pull/54339 because we've not had failures for 30 days and don't know how to make it fail - it seems fine, and may have been a point-in-time issue with runners.

If it does fail again we should re-quarantine and then we'll have a failure log to debug.

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS it looks like this very test is failing in release/8.0, but not in 9.0. I asked @Eilon to look into it last time, but was wondering if you built enough context to see if it's obvious what may be causing it: https://github.com/dotnet/aspnetcore/issues/54017

**Comment by radical** [comment]
Re-opening as a retry has been added for this in https://github.com/dotnet/aspnetcore/pull/54751 .

**Comment by javiercn** [comment]
Closing in favor of https://github.com/dotnet/aspnetcore/issues/54017
