### ISSUE TITLE
Quarantine CanRenderComponentWithPersistedState(suppressEnhancedNavigation: False, renderMode: typeof(Microsoft.AspNetCore.Components.Web.InteractiveAutoRenderMode), streaming: "AutoStreaming"/null)

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#50810]
## Failing Test(s)

- Microsoft.AspNetCore.Components.E2ETests.Tests.StatePersistenceTest.CanRenderComponentWithPersistedState

... but only the following variants:

`[InlineData(true, typeof(InteractiveAutoRenderMode), (string)null)]`
`[InlineData(false, typeof(InteractiveAutoRenderMode), (string)null)]`
`[InlineData(false, typeof(InteractiveAutoRenderMode), "AutoStreaming")]`

We need to verify this is not a product bug before 8.0 ships, so putting it in the 8.0 milestone.

## Error Message

```text
Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: Interactive runtime: server
Actual:   Interactive runtime: wasm
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout) in /home/vsts/work/1/s/src/Shared/E2ETesting/WaitAssert.cs:line 129
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore(IWebDriver driver, Action assertion, TimeSpan timeout) in /home/vsts/work/1/s/src/Shared/E2ETesting/WaitAssert.cs:line 83
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.Equal[T](IWebDriver driver, T expected, Func`1 actual) in /home/vsts/work/1/s/src/Shared/E2ETesting/WaitAssert.cs:line 27
   at Microsoft.AspNetCore.Components.E2ETests.Tests.StatePersistenceTest.AssertPageState(String mode, String renderMode, Boolean interactive, Boolean stateFound, String stateValue, String streamingId, Boolean streamingCompleted, String interactiveRuntime) in /home/vsts/work/1/s/src/Components/test/E2ETest/Tests/StatePersistenceTest.cs:line 225
   at Microsoft.AspNetCore.Components.E2ETests.Tests.StatePersistenceTest.RenderComponentsWithPersistentStateAndValidate(Boolean suppresEnhancedNavigation, String mode, Type renderMode, String streaming, String interactiveRuntime, String stateValue) in /home/vsts/work/1/s/src/Components/test/E2ETest/Tests/StatePersistenceTest.cs:line 197
   at Microsoft.AspNetCore.Components.E2ETests.Tests.StatePersistenceTest.CanRenderComponentWithPersistedState(Boolean suppressEnhancedNavigation, Type renderMode, String streaming) in /home/vsts/work/1/s/src/Components/test/E2ETest/Tests/StatePersistenceTest.cs:line 101
   at InvokeStub_StatePersistenceTest.CanRenderComponentWithPersistedState(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
----- Inner Stack Trace -----
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /home/vsts/work/1/s/src/Shared/E2ETesting/WaitAssert.cs:line 101
```
</details>

## Logs

<details>

```text

```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=411184
https://dev.azure.com/dnceng-public/public/_build/results?buildId=411665
https://dev.azure.com/dnceng-public/public/_build/results?buildId=457395

**Comment by SteveSandersonMS** [comment]
Note that since this is a single `[InlineData]` case, it can't be quarantined in the normal way. So instead I've commented out that line. It will **not** get unquarantined automatically. The person resolving this issue needs to uncomment it to bring it back.

**Comment by amcasey** [comment]
Saw a new [failure](https://dev.azure.com/dnceng-public/public/_build/results?buildId=461234&view=results) in `Microsoft.AspNetCore.Components.E2ETests.Tests.StatePersistenceTest.CanRenderComponentWithPersistedState(suppressEnhancedNavigation: True, renderMode: typeof(Microsoft.AspNetCore.Components.Web.InteractiveAutoRenderMode), streaming: "AutoStreaming")​`

```
OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: Interactive runtime: wasm
Actual:   Interactive runtime: server
```

**Comment by BrennanConroy** [comment]
And `Microsoft.AspNetCore.Components.E2ETests.Tests.StatePersistenceTest.CanRenderComponentWithPersistedState(suppressEnhancedNavigation: True, renderMode: typeof(Microsoft.AspNetCore.Components.Web.InteractiveAutoRenderMode), streaming: null)` in https://dev.azure.com/dnceng-public/public/_build/results?buildId=482738&view=ms.vss-test-web.build-test-results-tab&runId=11110162&resultId=101127&paneView=debug
