### ISSUE TITLE
Blazor WASM OIDC Authentication does not work with Zitadel Identity Provider

### ISSUE THREAD

**Issue by ldabrowskiairspan** [dotnet/aspnetcore#50812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When configuring Zitadel as the OIDC provider when using OIDC Authentication with PKCE flow in Blazor WASM I am getting the following error after the callback:
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: An exception occurred executing JS interop: The JSON value could not be converted to Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState. Path: $.state | LineNumber: 0 | BytePositionInLine: 62.. See InnerException for more details.
Microsoft.JSInterop.JSException: An exception occurred executing JS interop: The JSON value could not be converted to Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState. Path: $.state | LineNumber: 0 | BytePositionInLine: 62.. See InnerException for more details.
 ---> System.Text.Json.JsonException: The JSON value could not be converted to Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState. Path: $.state | LineNumber: 0 | BytePositionInLine: 62.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, RemoteAuthenticationState& value)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, RemoteAuthenticationState& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationResult`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]], Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, RemoteAuthenticationResult`1& value)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationResult`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]], Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, RemoteAuthenticationResult`1& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationResult`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]], Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationResult`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]], Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].Deserialize(Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationResult`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]], Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].DeserializeAsObject(Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadAsObject(Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at Microsoft.JSInterop.JSRuntime.EndInvokeJS(Int64 taskId, Boolean succeeded, Utf8JsonReader& jsonReader)
   --- End of inner exception stack trace ---
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationResult`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]], Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`3.<CompleteSignInAsync>d__21[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteUserAccount, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.OidcProviderOptions, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticatorViewCore`1.<ProcessLogInCallback>d__86[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticatorViewCore`1.<OnParametersSetAsync>d__84[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

Here is my OIDC config in `Startup.cs`:
```cs
builder.Services.AddOidcAuthentication(options =>
{
    // Configure your authentication provider options here.
    // For more information, see https://aka.ms/blazor-standalone-auth
    builder.Configuration.Bind("Local", options.ProviderOptions);
    options.ProviderOptions.ResponseType = "code";
});
```
and appsettings:
```json
{
  "Local": {
    "Authority": "http://localhost:8080/",
    "ClientId": "<MY_CLIENT_ID>"
  }
}
```

I am using the template "Individual User Accounts" and the same code works when the IP is Auth0 instead of ZITADEL. Also, when I refresh the page it shows me as logged in with the correct User details.

### Expected Behavior

I expect the PKCE flow to successfully authenticate the user.

### Steps To Reproduce

Create a new Blazor WASM app with Individual User Accounts and set up Zitadel as IdP like the code above.

### .NET Version

Tested latest stable .NET 7 and 8.0.100-rc.1.23463.5

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Can you please turn on the logging following the guidance here and then share the output: https://learn.microsoft.com/aspnet/core/blazor/fundamentals/logging?view=aspnetcore-7.0#client-side-authentication-logging

**Comment by ldabrowskiairspan** [comment]
@mkArtakMSFT Please see the log below:

```
mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28 [dotnet.7.0.11.0la8uwklg8.js:3:6678](https://localhost:8001/_framework/dotnet.7.0.11.0la8uwklg8.js)
dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
      Beginning initial silent sign in. [AuthenticationService.js:2:283950](https://localhost:8001/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js)
trce: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
      completeSignIn: "https://localhost:8001/authentication/login-callback?error=interaction_required&error_description=Unfortunately%2C+the+user+may+be+not+logged+in+and%2For+additional+interaction+is+required.&state=5c71ca8f53ab4488a3e6f06db2d2b633" [AuthenticationService.js:2:283950](https://localhost:8001/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js)
dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
      Initial silent sign in failed 'Unfortunately, the user may be not logged in and/or additional interaction is required.' [AuthenticationService.js:2:283950](https://localhost:8001/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js)
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      DenyAnonymousAuthorizationRequirement: Requires an authenticated user. [_bound_js_globalThis_console_info:7:5](https://dotnet.generated.invalid/_bound_js_globalThis_console_info)
dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticatorViewCore[1]
      Processing action login. [_bound_js_globalThis_console_debug:7:5](https://dotnet.generated.invalid/_bound_js_globalThis_console_debug)
dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticatorViewCore[16]
      Login request '(null)'. [_bound_js_globalThis_console_debug:7:5](https://dotnet.generated.invalid/_bound_js_globalThis_console_debug)
trce: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
      signIn: {"url":null,"state":{"returnUrl":"https://localhost:8001/"},"interactiveRequest":null} [AuthenticationService.js:2:283950](https://localhost:8001/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js)
dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
      Silent sign in starting [AuthenticationService.js:2:283950](https://localhost:8001/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js)
Navigated to http://localhost:8080/oauth/v2/authorize?client_id=231559904651968514%40my_app&redirect_uri=https%3A%2F%2Flocalhost%3A8001%2Fauthentication%2Flogin-callback&response_type=code&scope=openid%20profile&state=e0fecffa968b4501b9ec6e3ac8f0b34d&code_challenge=1HwsC5kIbHIeylP5j0b-deSvxnds73AeLwcd8fTTzYk&code_challenge_method=S256&response_mode=query
trce: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
      completeSignIn: "https://localhost:8001/authentication/login-callback?error=interaction_required&error_description=Unfortunately%2C+the+user+may+be+not+logged+in+and%2For+additional+interaction+is+required.&state=8e9d3b1dfc0647879a670254829b5618" [AuthenticationService.js:2:283950](https://localhost:8001/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js)
dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
      Silent sign in failed, redirecting to the identity provider 'Unfortunately, the user may be not logged in and/or additional interaction is required.'. [AuthenticationService.js:2:283950](https://localhost:8001/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js)
dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticatorViewCore[3]
      Login requires redirect to the identity provider. [_bound_js_globalThis_console_debug:7:5](https://dotnet.generated.invalid/_bound_js_globalThis_console_debug)
Cookie “mode” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite [theme.js:45:4](http://localhost:8080/ui/login/resources/scripts/theme.js)
GET
http://localhost:8080/favicon.ico
[HTTP/1.1 404 Not Found 0ms]

Navigated to http://localhost:8080/ui/login/loginname
Cookie “mode” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite [theme.js:45:4](http://localhost:8080/ui/login/resources/scripts/theme.js)
GET
http://localhost:8080/favicon.ico
[HTTP/1.1 404 Not Found 0ms]

Navigated to http://localhost:8080/ui/login/password
mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28 [dotnet.7.0.11.0la8uwklg8.js:3:6678](https://localhost:8001/_framework/dotnet.7.0.11.0la8uwklg8.js)
dbug: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticatorViewCore[1]
      Processing action login-callback. [_bound_js_globalThis_console_debug:7:5](https://dotnet.generated.invalid/_bound_js_globalThis_console_debug)
trce: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
      completeSignIn: "https://localhost:8001/authentication/login-callback?code=09jeH664ZngrS7dY2vhrl273Pq7njh5TJ3MENNWuSXQIHA&state=e0fecffa968b4501b9ec6e3ac8f0b34d" [AuthenticationService.js:2:283950](https://localhost:8001/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js)
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      DenyAnonymousAuthorizationRequirement: Requires an authenticated user. [_bound_js_globalThis_console_info:7:5](https://dotnet.generated.invalid/_bound_js_globalThis_console_info)
trce: Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService[0]
      completeSignIn-result: {"id_token":"eyJhbGciOiJSUzI1NiIsImtpZCI6IjIzMjcwNTk0NDk4NTc5NjYxMSIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJzdWIiOiIyMzE4Nzc5MDMzNzYxODczOTUiLCJhdWQiOlsiMjMxNTU5OTA0NjUxOTY4NTE0QGFpcnNwYW5fcG9ydGFsIiwiMjMxNTU5NDgzNDU5ODk1Mjk4Il0sImV4cCI6MTY5NTI0Mjk2OCwiaWF0IjoxNjk1MTk5NzY4LCJhdXRoX3RpbWUiOjE2OTUxOTk3NjcsImFtciI6WyJwYXNzd29yZCIsInB3ZCJdLCJhenAiOiIyMzE1NTk5MDQ2NTE5Njg1MTRAYWlyc3Bhbl9wb3J0YWwiLCJjbGllbnRfaWQiOiIyMzE1NTk5MDQ2NTE5Njg1MTRAYWlyc3Bhbl9wb3J0YWwiLCJhdF9oYXNoIjoiS2JnSHlZYmkzY0pPQ1ZoWVJVSlNZUSIsImNfaGFzaCI6IjUzOF82ZHU3RElZbWt2QVhyeWY3aXciLCJuYW1lIjoiTHVrYXN6IERhYnJvd3NraSIsImdpdmVuX25hbWUiOiJMdWthc3oiLCJmYW1pbHlfbmFtZSI6IkRhYnJvd3NraSIsImxvY2FsZSI6ImVuIiwidXBkYXRlZF9hdCI6MTY5NDcwNjAzNSwicHJlZmVycmVkX3VzZXJuYW1lIjoidGVzdGF1dGhzbXRwdGVzdEBnbWFpbC5jb20ifQ.eTg8KkGhCsBnw_1GNlH7hKHWNjuV9g4Pe9d3vZflO1lN8yHOSzSeCkBISMksHSFHwq_Jy31pCdmpqlioo-TF3KNiTlSuKWk2zgs_1WuAOkg1erVaYpoO908pmqW8uPEtRK-w9oQ5QQv77fuL2EdHX5hjmBz-KTPjPDaMhhUc-ZBxsIDW5S9AD6VHHTskx2WPUFzFnAnXx9fBRFvTR2S-SQjzWWrXdfhnDT3_IrjHDSb3xqsVGHqs5qninhUBpvkqHsuUNKNEuvH090PrtAlzl4EylX68SHC4i1bw_U8s0llzNydxCB2RezOxudwn0qeTKeZpadNxQwCLz7La3xWyKQ","access_token":"ooAsWsIuaZzSIjNjVEhiMeINT2Q7A7d1qqEdkIxAVrkeaQHYmTU6yHJxEzhjyHKL04Cy3Hw","token_type":"Bearer","scope":"openid profile","profile":{"sub":"231877903376187395","auth_time":1695199767,"amr":["password","pwd"],"azp":"231559904651968514@my_app","client_id":"231559904651968514@my_app","name":"Name Family Name","given_name":"Name","family_name":"Family Name","locale":"en","updated_at":1694706035,"preferred_username":"redacted@gmail.com"},"expires_at":1695242967,"state":"e0fecffa968b4501b9ec6e3ac8f0b34d"} [AuthenticationService.js:2:283950](https://localhost:8001/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js)
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: An exception occurred executing JS interop: The JSON value could not be converted to Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState. Path: $.state | LineNumber: 0 | BytePositionInLine: 62.. See InnerException for more details.
Microsoft.JSInterop.JSException: An exception occurred executing JS interop: The JSON value could not be converted to Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState. Path: $.state | LineNumber: 0 | BytePositionInLine: 62.. See InnerException for more details.
 ---> System.Text.Json.JsonException: The JSON value could not be converted to Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState. Path: $.state | LineNumber: 0 | BytePositionInLine: 62.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, RemoteAuthenticationState& value)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, RemoteAuthenticationState& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationResult`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]], Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, RemoteAuthenticationResult`1& value)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationResult`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]], Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, RemoteAuthenticationResult`1& value)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationResult`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]], Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationResult`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]], Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[Object](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo, ReadStack& state)
   at System.Text.Json.JsonSerializer.Read[Object](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at Microsoft.JSInterop.JSRuntime.EndInvokeJS(Int64 taskId, Boolean succeeded, Utf8JsonReader& jsonReader)
   --- End of inner exception stack trace ---
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationResult`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]], Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`3.<CompleteSignInAsync>d__21[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteUserAccount, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.OidcProviderOptions, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticatorViewCore`1.<ProcessLogInCallback>d__86[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticatorViewCore`1.<OnParametersSetAsync>d__84[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=7.0.11.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**Comment by ldabrowskiairspan** [comment]
From my own investigations what seems to be happening is basically when the OIDC lib calls Zitadel's `https://myinstance.zitadel.cloud/oauth/v2/token` it retuns:

```json
{
    "access_token": "<my_access_token>",
    "token_type": "Bearer",
    "expires_in": 43199,
    "id_token": "<my_id_token>",
    "state": "a33cb64f72d74d85a6dd69ed4cf84b61"
}
```

this `state` property causes an override of the state previously stored in the store (before redirect to Zitadel) (which used to be `{"returnUrl":"https://localhost:8001/"}`) as it matches by property name. Auth0 doesn't have this `state` property so it works. Any idea how this can be worked around or if something's misconfigured?

**Comment by javiercn** [comment]
@ldabrowskiairspan thanks for the additional details.

Your provider is returning a non-normative response, that is causing the client to fail. You can provide your own implementation by following https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-7.0#replace-any-javascript-authenticationservice-implementation
