### ISSUE TITLE
Could not load file or assembly 'em_10 (Blazor hot reload)

### ISSUE THREAD

**Issue by solbster** [dotnet/aspnetcore#51197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hot reload is broken in my project, cant understand where this error comes from or what it is. It started happening for about 1-2 weeks ago.

### Expected Behavior

Hot reload should run as expected and refresh the browser.

### Exceptions (if any)

Error: System.TypeLoadException: EnC: we do not support patching of existing PARAM table cols. token=0x08000d0e
   at System.Reflection.Metadata.MetadataUpdater.ApplyUpdate(:5001/Assembly assembly, ReadOnlySpan`1 metadataDelta, ReadOnlySpan`1 ilDelta, ReadOnlySpan`1 pdbDelta)
   at Microsoft.Extensions.HotReload.HotReloadAgent.ApplyDeltas(:5001/IReadOnlyList`1 deltas)
   at Microsoft.AspNetCore.Components.WebAssembly.HotReload.WebAssemblyHotReload.ApplyHotReloadDelta(:5001/String moduleIdString, Byte[] metadataDelta, Byte[] ilDelta, Byte[] pdbBytes)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(:5001/JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.Invoke(:5001/JSRuntime jsRuntime, DotNetInvocationInfo& invocationInfo, String argsJson)
   at Microsoft.AspNetCore.Components.WebAssembly.Services.DefaultWebAssemblyJSRuntime.InvokeDotNet(:5001/String assemblyName, String methodIdentifier, String dotNetObjectId, String argsJson)
    at qi (dotnet.7.0.11.sf8asx8yhf.js:5:80665)
    at Ji (dotnet.7.0.11.sf8asx8yhf.js:5:80549)
    at _Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_InvokeDotNet (_Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_InvokeDotNet:30:5)
    at Object.invokeDotNetFromJS (blazor.webassembly.js:1:45224)
    at g (blazor.webassembly.js:1:1621)
    at e.invokeMethod (blazor.webassembly.js:1:2670)
    at Vt.Ke._internal.applyHotReload (blazor.webassembly.js:1:58767)
    at aspnetcore-browser-refresh.js:140:35
    at Array.forEach (<anonymous>)
    at applyBlazorDeltas (aspnetcore-browser-refresh.js:138:14)

### .NET Version

7.0.11

**Comment by solbster** [comment]
Another exception related to the same issue. 

Error: System.TypeLoadException: EnC: we do not support patching of existing PARAM table cols. token=0x08000d0e
at System.Reflection.Metadata.MetadataUpdater.ApplyUpdate(:5001/Assembly assembly, ReadOnlySpan1 metadataDelta, ReadOnlySpan1 ilDelta, ReadOnlySpan1 pdbDelta) at Microsoft.Extensions.HotReload.HotReloadAgent.ApplyDeltas(:5001/IReadOnlyList1 deltas)
at Microsoft.AspNetCore.Components.WebAssembly.HotReload.WebAssemblyHotReload.ApplyHotReloadDelta(:5001/String moduleIdString, Byte[] metadataDelta, Byte[] ilDelta, Byte[] pdbBytes)
at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(:5001/JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.Invoke(:5001/JSRuntime jsRuntime, DotNetInvocationInfo& invocationInfo, String argsJson)
at Microsoft.AspNetCore.Components.WebAssembly.Services.DefaultWebAssemblyJSRuntime.InvokeDotNet(:5001/String assemblyName, String methodIdentifier, String dotNetObjectId, String argsJson)
at qi (dotnet.7.0.11.sf8asx8yhf.js:5:80665)
at Ji (dotnet.7.0.11.sf8asx8yhf.js:5:80549)
at _Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_InvokeDotNet (_Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_InvokeDotNet:30:5)
at Object.invokeDotNetFromJS (blazor.webassembly.js:1:45224)
at g (blazor.webassembly.js:1:1621)
at e.invokeMethod (blazor.webassembly.js:1:2670)
at Vt.Ke._internal.applyHotReload (blazor.webassembly.js:1:58767)
at aspnetcore-browser-refresh.js:140:35
at Array.forEach ()
at applyBlazorDeltas (aspnetcore-browser-refresh.js:138:14)

**Comment by solbster** [comment]
21:34 38.92 MyApp.Server (Web assembly): Sending updates to running application
21:34 38.97 MyApp.Server (Web assembly): [Error] Applying updates failed:
21:34 38.97 MyApp.Server (Web assembly): [Error] Applying updates failed: The following error occurred when trying to apply your edits to the running application.
21:34 38.97 Exception thrown for Apply Code Updates: 0x80131500 - The following error occurred when trying to apply your edits to the running application. The following error occurred when trying to apply your edits to the running application.
21:34 38.97 Stack trace for WebToolsException:
at Microsoft.WebTools.ProjectSystem.Components.HotReload.ProjectHotReloadSession.d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Debugger.Shared.Utilities.LoggerExtensions.d__3.MoveNext()
21:34 38.99 An unexpected error has occurred, any pending updates have been discarded.
