### ISSUE TITLE
There is an error "Exception while reading WASM runtime capabilities: TypeError: Cannot read properties of undefined " when dotnet watch Blazor WASM app after installing .NET 8.0-rtm at first time

### ISSUE THREAD

**Issue by jinzhao1127** [dotnet/aspnetcore#51208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After install .NET 8.0-rtm build, some error occurs when I `dotnet watch ` for Blazor WASM app

**Note:**
1. This issue does not repro on 8.0 RC2
1. This issue does not repro on Blazor server app.
1. This issue also reproduce on 7.0/6.0 Blazor wasm app after installing 8.0 rtm

### Expected Behavior

There is not any error when executing `dotnet watch`

### Steps To Reproduce

1. Create a Blazor  WebAssembly app and run with `dotnet watch`:
  ```
   dotnet new blazorwasm -o MyBlazorWasmApp
   cd MyBlazorWasmApp
   dotnet watch
  ```

### Exceptions (if any)

An error message appears on the command
![image](https://github.com/dotnet/aspnetcore/assets/55483444/d3d5fda3-ee43-430d-ac99-cfe5a0221a15)

**Error log:**
dotnet watch ❌ Exception while reading WASM runtime capabilities: TypeError: Cannot read properties of undefined (reading 'invokeDotNetStaticMethod')
    at nt._internal.getApplyUpdateCapabilities (http://localhost:5209/_framework/blazor.webassembly.js:1:50743)
    at getBlazorWasmApplyUpdateCapabilities (http://localhost:5209/_framework/aspnetcore-browser-refresh.js:101:57)
    at Object.BlazorRequestApplyUpdateCapabilities2 (http://localhost:5209/_framework/aspnetcore-browser-refresh.js:51:56)
    at connection.onmessage (http://localhost:5209/_framework/aspnetcore-browser-refresh.js:56:29)

### Anything else?

The details build version and other info, please refer to AzDO: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1898080

**Comment by MackinnonBuck** [comment]
@jinzhao1127 Does this repo with the latest .NET 8 RTM build? I just tried this on a fresh machine using the last .NET 8 RTM build, and hot reload worked without exhibiting this issue. I tried hot reload on two different Blazor WebAssembly apps, one targeting .NET 8 and the other .NET 7, and both worked correctly.

**Comment by jinzhao1127** [comment]
> Note that while I believe there could be a bug here, it's still not something I've been able to repro. So, it would still be appreciated if @jinzhao1127 could confirm whether this still repros 🙂

@MackinnonBuck  I still can repro this issue on the latest .NET 8.0-rtm[details build as [here](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1898080#3748445)]
You can log in the repro machine to try it.

![HotReload](https://github.com/dotnet/aspnetcore/assets/55483444/bc088d4c-cf7b-41e9-8f50-e9dc9d441940)

**Comment by jinzhao1127** [comment]
Verify this bug on the latest .NET 8.0-rtm, it works well.
