### ISSUE TITLE
NavigationManager.Refresh throws on SSR-only pages

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#51222]
It throws:

> NotImplementedException: The type Microsoft.AspNetCore.Components.Endpoints.HttpNavigationManager does not support supplying NavigationOptions. To add support, that type should override NavigateToCore(string uri, NavigationOptions options).

As far as I know, `NavigationManager.Refresh` should be supported and should be equivalent to calling `Nav.NavigateTo(Nav.Uri)` (which does work).

**Comment by SteveSandersonMS** [comment]
A usability issue in the same area:

If you do `NavigationManager.NavigateTo(Nav.Uri)` while enhanced nav is enabled, it unconditionally pushes a new history entry, even if it's the same as where you already are.

There needs to be some way to do post/redirect/get without pushing a new history entry, otherwise "back" then doesn't work as you'd expect. We should check that `NavigationManager.Refresh` can be fixed to force the enhanced load but without pushing a new history entry.

**Comment by surayya-MS** [comment]
I was able to repro the bug.

Interestingly, if you choose Blazor Web App with Interactivity Auto instead of None, and try same thing then the error message is different. The error doesn't show on the page but in terminal:
>Microsoft.AspNetCore.Components.Server.Circuits.RemoteNavigationManager[5]
      Failed to refresh
      System.ArgumentNullException: Value cannot be null. (Parameter 'jsRuntime')
         at System.ArgumentNullException.Throw(String paramName)
         at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteNavigationManager.<>c__DisplayClass14_0.<<Refresh>g__RefreshAsync|0>d.MoveNext()

**Comment by surayya-MS** [comment]
> A usability issue in the same area:
> 
> If you do `NavigationManager.NavigateTo(Nav.Uri)` while enhanced nav is enabled, it unconditionally pushes a new history entry, even if it's the same as where you already are. That may be OK for `NavigateTo` but it means it's not really suitable for implementing post/redirect/get.
> 
> There needs to be some way to do post/redirect/get without pushing a new history entry, otherwise "back" then doesn't work as you'd expect. We should check that `NavigationManager.Refresh` can be fixed to force the enhanced load but without pushing a new history entry.

@SteveSandersonMS would it be an acceptable behavior if in case when form is enhance and url doesn't change, then do not push new history entry? So both `NavigationManager.Refresh()` and `NavigationManager.NavigateTo(NavigationManager.Uri)` will not push new history entry

**Comment by surayya-MS** [comment]
> I was able to repro the bug.
> 
> Interestingly, if you choose Blazor Web App with Interactivity Auto instead of None, and try same thing then the error message is different. The error doesn't show on the page but in terminal:
> 
> > Microsoft.AspNetCore.Components.Server.Circuits.RemoteNavigationManager[5]
> > Failed to refresh
> > System.ArgumentNullException: Value cannot be null. (Parameter 'jsRuntime')
> > at System.ArgumentNullException.Throw(String paramName)
> > at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
> > at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
> > at Microsoft.AspNetCore.Components.Server.Circuits.RemoteNavigationManager.<>c__DisplayClass14_0.<g__RefreshAsync|0>d.MoveNext()

The bug https://github.com/dotnet/aspnetcore/issues/51482
