### ISSUE TITLE
New error after updating from RC1 to RC2: Method not found: 'Boolean Microsoft.IdentityModel.Logging.LogHelper.IsEnabled

### ISSUE THREAD

**Issue by caliberdigitalllc** [dotnet/aspnetcore#51280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After updating from Rc1 to Rc2, an application that has been running great on 8.0 since Beta 1 is now crashing.

This is a .net core 8.0 Blaozr server application. The application itself spins up fine, and the 8.0 MVC Core identity server also spins up fine.

We visit our identity server landing page: https://localhost:44309, click on the application we want to log into (https://localhost:44336/), and then immediate get this set of exceptions on locahost:44336 (the blazor app)

System.MissingMethodException: Method not found: 'Boolean Microsoft.IdentityModel.Logging.LogHelper.IsEnabled(Microsoft.IdentityModel.Abstractions.EventLogLevel)'.
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.Microsoft.IdentityModel.Protocols.IConfigurationRetriever<Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration>.GetConfigurationAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   
   System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://localhost:44309/.well-known/openid-configuration'. Will retry at '10/10/2023 11:48:50 PM +00:00'. Exception: 'System.MissingMethodException: Method not found: 'Boolean Microsoft.IdentityModel.Logging.LogHelper.IsEnabled(Microsoft.IdentityModel.Abstractions.EventLogLevel)'.
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.Microsoft.IdentityModel.Protocols.IConfigurationRetriever<Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration>.GetConfigurationAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)'.
 ---> System.MissingMethodException: Method not found: 'Boolean Microsoft.IdentityModel.Logging.LogHelper.IsEnabled(Microsoft.IdentityModel.Abstractions.EventLogLevel)'.
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.Microsoft.IdentityModel.Protocols.IConfigurationRetriever<Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration>.GetConfigurationAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsyncInternal(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.<>c__DisplayClass0_0.<<HandleAsync>g__Handle|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
   
   
   This application suite has been working fine all year long on 8.0 and has been in production, no issues. All I did was update to RC2 and this happened right after the update.

Not sure where to go from here. Will rollback to Rc1 for now till it's figured out.

### Expected Behavior

The application shouldn't crash. We should end up on the identity server login page.

### Exceptions (if any)

System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://localhost:44309/.well-known/openid-configuration'. Will retry at '10/10/2023 11:48:50 PM +00:00'. Exception: 'System.MissingMethodException: Method not found: 'Boolean Microsoft.IdentityModel.Logging.LogHelper.IsEnabled(Microsoft.IdentityModel.Abstractions.EventLogLevel)'.
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.Microsoft.IdentityModel.Protocols.IConfigurationRetriever<Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration>.GetConfigurationAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)'.
 ---> System.MissingMethodException: Method not found: 'Boolean Microsoft.IdentityModel.Logging.LogHelper.IsEnabled(Microsoft.IdentityModel.Abstractions.EventLogLevel)'.
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.Microsoft.IdentityModel.Protocols.IConfigurationRetriever<Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration>.GetConfigurationAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsyncInternal(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.<>c__DisplayClass0_0.<<HandleAsync>g__Handle|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

### .NET Version

8.0 Rc2

**Comment by caliberdigitalllc** [comment]
Just as a follow up, simply updating this one package back to RC1 fixed the problem. All of my API's are still on Rc2 and working fine, so this seems to be very specifically some issue with this Rc2 package.

<PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="8.0.0-rc.1.23421.29" />

**Comment by Tratcher** [comment]
This is usually caused by mismatched package dependencies. Please share your project's list of dependencies and versions.

**Comment by caliberdigitalllc** [comment]
Here they are. They're all using the latest versions of everything (except for the Rc1 open id connect package I had to revert).

I some how have a feeling it's the identity server package ("Duende.IdentityServer" Version="7.0.0-preview.1") that may be the issue, but I'm not sure. Perhaps that team has to update to be compatible with 8.0.

<PackageReference Include="Audit.NET" Version="21.1.0" />
<PackageReference Include="Audit.NET.SqlServer" Version="21.1.0" />
<PackageReference Include="BabouMail.MailGun" Version="1.1.11" />
<PackageReference Include="BlazorDownloadFile" Version="2.4.0.2" />
<PackageReference Include="Blazored.Typeahead" Version="4.7.0" />
<PackageReference Include="BlazorGoogleMaps" Version="3.2.0" />
<PackageReference Include="BlazorPro.Spinkit" Version="1.2.0" />
<PackageReference Include="BscModel" Version="2023.10.11.85532" />
<PackageReference Include="BscTheme" Version="2023.9.30.122424" />
<PackageReference Include="CsvHelper" Version="30.0.1" />
<PackageReference Include="DevExpress.Blazor" Version="23.1.5" />
<PackageReference Include="Duende.IdentityServer" Version="7.0.0-preview.1" />
<PackageReference Include="Exceptionless.AspNetCore" Version="6.0.2" />
<PackageReference Include="Geolocation" Version="1.2.1" />
<PackageReference Include="GoogleMaps.LocationServices" Version="1.2.0.5" />
<PackageReference Include="IdentityModel" Version="6.2.0" />
<PackageReference Include="JsonDiffPatch.Net" Version="2.3.0" />
<PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="8.0.0-rc.1.23421.29" />
<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.0-rc.2.23480.2" />
<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.0-rc.2.23480.2" />
<PackageReference Include="Otp.NET" Version="1.3.0" />
<PackageReference Include="QRCoder" Version="1.4.1" />
<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.1.0-preview" />
<PackageReference Include="System.Net.Http.Json" Version="8.0.0-rc.2.23479.6" />

**Comment by Tratcher** [comment]
Remove this:
`<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.1.0-preview" />`

OpenIdConnect rc2 depends on IdentityModel 7.0.0.

**Comment by caliberdigitalllc** [comment]
7.0 is not available though.

![image](https://github.com/dotnet/aspnetcore/assets/59370138/48b6d370-67e6-4ff7-b861-ce8793b2419e)

**Comment by caliberdigitalllc** [comment]
> Remove this: `<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.1.0-preview" />`
> 
> OpenIdConnect rc2 depends on IdentityModel 7.0.0.

Indeed, that solved it.

Curious how the typical person would know that's the problem though? :) But thanks all the same for the solve.

**Comment by Tratcher** [comment]
MissingMethodException is a big red flag that your packages/dlls don't agree with eachother. The API one dll was compiled against isn't there or the same anymore.
