### ISSUE TITLE
.NET 8 RC2 crashes when using HttpLoggingMiddleware after upgrading from RC1

### ISSUE THREAD

**Issue by ArkadiuszChorian** [dotnet/aspnetcore#51322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After upgrading from .NET 8 RC1 to RC2 it is not possible to use built-in `HttpLoggingMiddleware`.

If this line of code is present in app setup:
`app.UseHttpLogging();`
whole app crashes on startup.

Here is most important part of stacktrace:
```
crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
      Application startup exception
      System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.ObjectPool.ObjectPool`1[Microsoft.AspNetCore.HttpLogging.HttpLoggingInterceptorContext]
' while attempting to activate 'Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware'.
         at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
```
   
Here is full stacktrace:
```
crit: Microsoft.AspNetCore.Hosting.Diagnostics[6]
      Application startup exception
      System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.ObjectPool.ObjectPool`1[Microsoft.AspNetCore.HttpLogging.HttpLoggingInterceptorContext]
' while attempting to activate 'Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware'.
         at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
         at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
         at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.ReflectionMiddlewareBinder.CreateMiddleware(RequestDelegate next)
         at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
         at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
         at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
fail: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.ObjectPool.ObjectPool`1[Microsoft.AspNetCore.HttpLogging.HttpLoggingInterceptorContext]
' while attempting to activate 'Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware'.
         at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
         at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
         at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.ReflectionMiddlewareBinder.CreateMiddleware(RequestDelegate next)
         at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
         at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
         at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
         at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
         at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exce
ptions, Func`3 operation)
Unhandled exception. System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.ObjectPool.ObjectPool`1[Microsoft.AspNetCore.HttpLogging.HttpLoggingInte
rceptorContext]' while attempting to activate 'Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.ReflectionMiddlewareBinder.CreateMiddleware(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions
, Func`3 operation)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args) in /src/Program.cs:line 41
   ```

### Expected Behavior

`app.UseHttpLogging();` should add `HttpLoggingMiddleware` without crashing the app.

### .NET Version

8.0.0-rc.2

**Comment by martincostello** [comment]
Please provide a minimal runnable example showing what other services your application is registering with the service collection.

Is your application calling `services.AddHttpLogging()` so [the required services](https://github.com/dotnet/aspnetcore/blob/9719821d5bb09c7cf75f82a223e8b210da65aaca/src/Middleware/HttpLogging/src/HttpLoggingServicesExtensions.cs#L26) are present?

**Comment by ArkadiuszChorian** [comment]
@martincostello thanks for pointing right direction. I managed to fix it.

My app was missing `services.AddHttpLogging()` but before RC2 it was working properly with only `app.UseHttpLogging()`. The reason behind it is that before RC2 `services.AddHttpLogging()` actually didn't add any additional services as you can see [here](https://github.com/dotnet/aspnetcore/blob/8ad057426fa6a27cd648b05684afddab9d97d3d9/src/Middleware/HttpLogging/src/HttpLoggingServicesExtensions.cs#L19). Practically it was only useful to customize `HttpLoggingOption` on `configureOptions` action. Since we didn't need to customize anything there yet, we even didn't notice that `services.AddHttpLogging()` is missing.

In RC2 you added some new services that are registered when invoking `services.AddHttpLogging()` as you can see [here](https://github.com/dotnet/aspnetcore/blob/f0cc6b11bd8f0826c63d75483578e868c8abe75e/src/Middleware/HttpLogging/src/HttpLoggingServicesExtensions.cs#L21) which are required in RC2 version of `HttpLoggingMiddleware` and this lead to breaking apps that only enabled http logging with `app.UseHttpLogging()` but didn't customize anything with `services.AddHttpLogging()`.

I think this should be taken into account when writing docs for RC2 or further release because as you can see [here](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-logging/?view=aspnetcore-8.0#enabling-http-logging) there is only information about `app.UseHttpLogging()` invocation so also `services.AddHttpLogging()` is necessary for proper setup since RC2.

Additionally I noticed that  `services.AddHttpLogging()` `configureOptions` argument is not optional so we are forced to pass empty lambda even if nothing is customized. Signature should expect `configureOptions = null` to provide this behavior. But probably this is another issue so please let me know if should I create new one or you can process it further.

**Comment by ArkadiuszChorian** [comment]
Thanks for feedback.

Perhaps I could add this change to the documentation, but I'm afraid it might just be easier for someone familiar with the change process (probably @Rick-Anderson). This change should apply only for docs for .NET 8 RC2 and newer but as I can see only 8.0 preview docs are available for now on [official docs site](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-logging/?view=aspnetcore-8.0). Even if I click edit button on it, underlying markdown [here](https://github.com/dotnet/AspNetCore.Docs/blob/85efbeb8a83bc0d0bea1c7b9df92b15a4090b96e/aspnetcore/fundamentals/http-logging/index.md?plain=1#L5) say it's applicable for .NET 6 and upper.

So I just don't know how to properly introduce this change thus please better introduce it with your well known process.

Regarding changing signature of `services.AddHttpLogging()` can you mention here related issue? Even if it won't be done for .NET 8 full release it can be just put in .NET 9 queue.

**Comment by martincostello** [comment]
> Regarding changing signature of services.AddHttpLogging() can you mention here related issue? Even if it won't be done for .NET 8 full release it can be just put in .NET 9 queue.

I'm not aware of an existing issue for it. If you create a [new API proposal issue](https://github.com/dotnet/aspnetcore/issues/new/choose) then adding one can be discussed there as a separate issue to this one.

**Comment by naeemaei** [comment]
I am interested in to contribute in this issue

**Comment by Tratcher** [comment]
@naeemaei thanks, go ahead.

**Comment by naeemaei** [comment]
1. **About improving error message**
Considering that this error occurs during the creation of the object and the preparation of dependencies in `Microsoft.Extensions.DependencyInjection` ‍‍‍, the improvement of the error message will require changes in that part, is it possible to change the error message?

2. **About Overloaded function**
I think we can create a new overload without the `configureOptions` parameter and then instantiate options within this function with the default values.
```cs 
public static IServiceCollection AddHttpLogging(this IServiceCollection services)
{
    ArgumentNullException.ThrowIfNull(services);

    return services.AddHttpLogging(o => o = new HttpLoggingOptions());
}
```
and finally, update the documentation in another PR.
What do you think? @Tratcher @martincostello
