### ISSUE TITLE
[FromForm] in minimal API results in null when the class is using primary constructor and default constructor

### ISSUE THREAD

**Issue by dodyg** [dotnet/aspnetcore#51379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The following code works fine when using with [FromForm] model binding

``` csharp
public class BlogPostInput(string? title, string body)
{
    public string? Title { get; set; } = title;
    public string Body { get; set; } = body;
}
```
but the following class definition will make the binding produce `null`.
``` csharp
public class BlogPostInput(string? title, string body)
{
    public string? Title { get; set; } = title;
    public string Body { get; set; } = body;

    public BlogPostInput() : this(null, string.Empty)
    {

    }
}
```

### Expected Behavior

It should just work the same

### Steps To Reproduce

```csharp

using Microsoft.AspNetCore.Antiforgery;
using Microsoft.AspNetCore.Mvc;

var builder = WebApplication.CreateBuilder();
builder.Services.AddAntiforgery();
var app = builder.Build();
app.UseAntiforgery();
app.MapGet("/", (HttpContext context, IAntiforgery antiforgery) =>
{
    var token = antiforgery.GetAndStoreTokens(context);
    return Results.Content(Template($$"""
            <div class="row">
                <div class="col-md-6">
                    <form method="POST" action="/">
                        <input name="{{token.FormFieldName}}" type="hidden" value="{{token.RequestToken}}" />
                        <div class="mb-3">
                            <label for="Title" class="form-label">Title</label>
                            <input type="text" class="form-control" id="Title" name="Title">
                        </div>
                        <div class="mb-3">
                            <label for="Body" class="form-label">Body</label>
                            <textarea class="form-control" id="Body" name="Body" rows="3"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
    """), "text/html");
});

app.MapPost("/", async ([FromForm] BlogPostInput input, HttpContext context, IAntiforgery antiforgery) =>
{
    try
    {
        await antiforgery.ValidateRequestAsync(context);
        return Results.Content(Template($$"""
        <div class="row">
            <div class="col-md-6">
                Title : {{input.Title}}<br/>
                Body : {{input.Body}}
            </div>
        </div>
"""), "text/html");
    }
    catch (AntiforgeryValidationException)
    {
        return TypedResults.BadRequest("Invalid anti-forgery token");
    }
});


app.Run();

static string Template(string body)
{
    return $$"""
    <html>
    <head>
      <title>Form Model Binding</title>
      <link href="https://fastly.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    </head>
    <body>
        <div class="container">
            <h1>Form Model Binding</h1>
            {{body}}
        </div>
    </body>
    </html>
    """;
}

public class BlogPostInput(string? title, string body)
{
    public string? Title { get; set; } = title;
    public string Body { get; set; } = body;

    public BlogPostInput() : this(null, string.Empty)
    {

    }
}
```

### Exceptions (if any)

```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMUCMJP38BUA", Request id "0HMUCMJP38BUA:00000006": An unhandled exception was thrown by the application.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at Program.<>c.<<<Main>$>b__0_1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteTaskResult[T](Task`1 task, HttpContext httpContext)
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass104_2.<<HandleRequestBodyAndCompileRequestDelegateForForm>b__2>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Antiforgery.Internal.AntiforgeryMiddleware.InvokeAwaited(HttpContext context)
         at Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserRefreshMiddleware.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### .NET Version

8.0.100-rc.2.23502.2

### Anything else?

It used to work in RC1

**Comment by captainsafia** [comment]
@dodyg Thanks for reporting this issue!

I believe this was a regression that was introduced via https://github.com/dotnet/aspnetcore/pull/50431. Prior to this change, the implementation supported setting properties directly via their setters if there was more than one constructor defined. 

@javiercn Is my assessment here correct? I missed this in my original review but was there a reason we made this behavior change?
