### ISSUE TITLE
An exception occurs when running an app using BlazorWebView on a machine different from the one on which it was built.

### ISSUE THREAD

**Issue by Ishikawa-Tatsuya** [dotnet/aspnetcore#51409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

This the exception message.
System.IO.DirectoryNotFoundException C:\[local-path]\wwwroot\

This is because the absolute path is written in [appname].staticwebassets.runtime.json.
The problem can be resolved by rewriting ContentRoots written in [appname].staticwebassets.runtime.json to an absolute path for each machine that will be executed and placing wwwroot there.
However, this is a huge burden upon release.
Is there any solution?

When I tried rewriting it to a relative path, this exception occurred.
The path must be absolute. (Parameter 'root')

### Steps To Reproduce

1. Create and build a WPF app using BlazorWebView
2. Move the contents under that bin folder to another machine and execute it
3. An exception occurs when opening a screen using BlazorWebView

### Exceptions (if any)

System.IO.DirectoryNotFoundException

### .NET Version

.Net6 and .Net7

**Comment by gragra33** [comment]
@Ishikawa-Tatsuya did you move the `wwwroot` folder to the other machine? Also, what is the stack trace saying?

**Comment by Ishikawa-Tatsuya** [comment]
Yes, after building, I took the entire folder below.
It contained wwwroot.
WpfApp1\bin\Debug\net7.0-windows

Just in case dotnet publish -c Release --self-contained true -r wi
The same thing happened under the WpfApp1\bin\Release\net7.0-windows\win-x64 folder created with the n-x64 command.

The problem here is that the absolute path of the build machine is written in the file net7.0-windows\WpfApp1.staticwebassets.runtime.json that is created under the folder.
This will not exist on another machine and will cause an exception.
The solution is to rewrite this on another machine.
However, doing this at release time is a huge burden.

Here is the call stack when the exception occurs.

System.IO.DirectoryNotFoundException
C:\Users\MyName\Desktop\-dotnet6_blazorwebview_wpf-master\WpfApp1\wwwroot\   

```
at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
at Microsoft.AspNetCore.Components.WebView.WebViewManager.StaticWebAssetsLoader.<>c.<UseStaticWebAssets>b__0_0(String path)
at Microsoft.AspNetCore.StaticWebAssets.ManifestStaticWebAssetFileProvider..ctor(StaticWebAssetManifest manifest, Func`2 fileProviderFactory)
at Microsoft.AspNetCore.Components.WebView.WebViewManager.StaticWebAssetsLoader.UseStaticWebAssets(IFileProvider fileProvider)
at Microsoft.AspNetCore.Components.WebView.WebViewManager..ctor(IServiceProvider provider, Dispatcher dispatcher, Uri appBaseUri, IFileProvider fileProvider, JSComponentConfigurationStore jsComponents, String hostPageRelativePath)
at Microsoft.AspNetCore.Components.WebView.WebView2.WebView2WebViewManager..ctor(WebView2 webview, IServiceProvider services, Dispatcher dispatcher, IFileProvider fileProvider, JSComponentConfigurationStore jsComponents, String contentRootRelativeToAppRoot, String hostPagePathWithinFileProvider, Action`1 urlLoading, Action`1 blazorWebViewInitializing, Action`1 blazorWebViewInitialized, ILogger logger)
at Microsoft.AspNetCore.Components.WebView.Wpf.BlazorWebView.StartWebViewCoreIfPossible()
at Microsoft.AspNetCore.Components.WebView.Wpf.BlazorWebView.OnApplyTemplate()
at System.Windows.FrameworkElement.ApplyTemplate()
at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
at System.Windows.UIElement.Measure(Size availableSize)
at System.Windows.Controls.Grid.MeasureCell(Int32 cell, Boolean forceInfinityV)
at System.Windows.Controls.Grid.MeasureCellsGroup(Int32 cellsHead, Size referenceSize, Boolean ignoreDesiredSizeU, Boolean forceInfinityV, Boolean& hasDesiredSizeUChanged)
at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
at System.Windows.UIElement.Measure(Size availableSize)
at MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
at System.Windows.UIElement.Measure(Size availableSize)
at System.Windows.Controls.Decorator.MeasureOverride(Size constraint)
at System.Windows.Documents.AdornerDecorator.MeasureOverride(Size constraint)
at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
at System.Windows.UIElement.Measure(Size availableSize)
at System.Windows.Controls.Border.MeasureOverride(Size constraint)
at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
at System.Windows.UIElement.Measure(Size availableSize)
at System.Windows.Window.MeasureOverrideHelper(Size constraint)
at System.Windows.Window.MeasureOverride(Size availableSize)
at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
at System.Windows.UIElement.Measure(Size availableSize)
at System.Windows.Interop.HwndSource.SetLayoutSize()
at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
at System.Windows.Window.SetRootVisualAndUpdateSTC()
at System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
at System.Windows.Window.ShowHelper(Object booleanBox)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. You should copy the publish output, rather than the build output when trying to run the app on a different machine.
Note, that publish output is not in the `bin` folder.

**Comment by Ishikawa-Tatsuya** [comment]
Thank you for the answer.
What does "the publish output" mean?
I also tried dotnet publish with similar results.
[dotnet publish -c Release --self-contained true -r win-x64]

At this point I think there are two problems with this. Does "publish output" solve these problems?

## 1. The absolute path of the build machine is written in the file "net7.0-windows\[AppName].staticwebassets.runtime.json" that is created during build and dotnet publish.
An absolute path is set in a field called "ContentRoots".This absolute path only exists on the machine where it was built, so if you move it to another machine it will never work.

## 2. Cannot specify relative path for "ContentRoots".
I tried specifying a relative path, but an exception occurred.
System.ArgumentException
The path must be absolute. (Parameter 'root')  

I can work around this problem by changing ContentRoots to an absolute path on that machine when you take it to another machine. However, doing so for each machine you install it on is a huge burden. This should be written as a relative path. (And I would like "[AppName].staticwebassets.runtime.json" with a relative path to be created when building or dotnetpublishing)

**Comment by Ishikawa-Tatsuya** [comment]
@mkArtakMSFT 

Thank you, it's solved.
It seems that the -o option is required.

[dotnet publish -c Release --self-contained true -r win-x64]
-> NG

[dotnet publish -c Release --self-contained true -r win-x64 __-o ./App__]
-> OK

**Comment by Ishikawa-Tatsuya** [comment]
@mkArtakMSFT 

I understood.
[dotnet publish -c Release --self-contained true -r win-x64]
There was no problem even without the -o option.

I was using this folder's exe
bin\Release\net6.0-windows\win-x64\app.exe

But the correct answer was this exe.
bin\Release\net6.0-windows\win-x64\publish\app.exe
