### ISSUE TITLE
Several issues with Kestrel header processing.

### ISSUE THREAD

**Issue by xljiulang** [dotnet/aspnetcore#51467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 1 Host header has no port
Throw BadHttpRequestException: Invalid Host header: 'api.nuget.org'

**Visual Studio 2022 nuget client**
```
CONNECT api.nuget.org:443 HTTP/1.1
User-Agent: NuGet VS VSIX/6.8.0 (Microsoft Windows NT 10.0.19045.0, Community/17.0)
Host: api.nuget.org
Proxy-Connection: Keep-Alive

HTTP/1.1 400 Bad Request
Content-Length: 0
Connection: close
Date: Wed, 18 Oct 2023 13:54:41 GMT
Server: Kestrel
```
I don't know whether nuget or kestrel does not follow the http protocol. Both are our products, but they are not compatible.

### 2 AllowHostHeaderOverride of Kestrel
Now we enable Kestrel's AllowHostHeaderOverride configuration, and then send the following request:
```
CONNECT http://api.nuget.org:443 HTTP/1.1
User-Agent: NuGet VS VSIX/6.8.0 (Microsoft Windows NT 10.0.19045.0, Community/17.0)
Host: api.nuget.org
Proxy-Connection: Keep-Alive

HTTP/1.1 400 Bad Request
Content-Length: 0
Connection: close
Date: Wed, 18 Oct 2023 13:57:42 GMT
Server: Kestrel
```

Throw the following exception:
```
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Invalid Host header: 'api.nuget.org:443:443'
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.ValidateNonOriginHostHeader(String hostText)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.EnsureHostHeaderExists()
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.TryParseRequest(ReadResult result, Boolean& endConnection)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
```

If we change it to ```Host: api.nuget.org:443``` or ```Host: api.nuget.org:80```, the exception remains unchanged.

### Expected Behavior

Kestrel handles the Connect method correctly.

### Steps To Reproduce

* Log configuration added: "Microsoft.AspNetCore.Server.Kestrel.BadRequests": "Debug"
* Use the tcp debugging tool to send the above request content to the kestrel service port

### .NET Version

8.0.100-rc.2.23502.2

**Comment by Tratcher** [comment]
Kestrel doesn't support CONNECT nor use as a forward proxy.
