### ISSUE TITLE
blazor wasm project deployed with error  when config `PublishTrimmed true` and `TrimMode link`

### ISSUE THREAD

**Issue by GuoMonth** [dotnet/aspnetcore#51513]
still error with 7.0 RC.
- MSBuild version 17.7.3+8ec440e68 for .NET
-  blazor project config detail
```xml
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <!-- https://www.meziantou.net/optimizing-a-blazor-webassembly-application-size.htm -->
    <BlazorEnableTimeZoneSupport>false</BlazorEnableTimeZoneSupport>
    <BlazorWebAssemblyPreserveCollationData>false</BlazorWebAssemblyPreserveCollationData>
    <PublishTrimmed>true</PublishTrimmed>
    <BlazorEnableCompression>true</BlazorEnableCompression>
    <TrimMode>link</TrimMode>
    <RunAOTCompilation>true</RunAOTCompilation>
    <!-- <SelfContained>false</SelfContained> -->
  </PropertyGroup>
```
- dockerfile
```
# syntax=docker/dockerfile:1

# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Dockerfile reference guide at
# https://docs.docker.com/engine/reference/builder/

################################################################################

# Learn about building .NET container images:
# https://github.com/dotnet/dotnet-docker/blob/main/samples/README.md

# Create a stage for building the application.
# mcr.microsoft.com/dotnet/aspnet:7.0
# mcr.microsoft.com/dotnet/sdk:7.0-alpine
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:7.0 AS publish
ARG TARGETARCH

COPY /src /src

WORKDIR /src

RUN apt-get update
RUN apt-get install -y python3

# Build the application.
# Leverage a cache mount to /root/.nuget/packages so that subsequent builds don't have to re-download packages.
# If TARGETARCH is "amd64", replace it with "x64" - "x64" is .NET's canonical name for this and "amd64" doesn't
#   work in .NET 6.0.
RUN dotnet workload install wasm-tools
RUN dotnet workload restore
RUN dotnet restore
RUN --mount=type=cache,id=nuget,target=/root/.nuget/packages \
    dotnet publish -c Release -r linux-x64 --self-contained -o /app/publish

FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
COPY --from=publish /app/publish/wwwroot .
COPY nginx.conf /etc/nginx/nginx.conf

```

 @coader can you please try out the latest 7.0 RC release. We know that the default project template works, so can't help you with this data. it should be something going on on your end.
If you find the culprit and you believe it's in Blazor, please file a new issue.

_Originally posted by @mkArtakMSFT in https://github.com/dotnet/aspnetcore/issues/43738#issuecomment-1292403248_

**Comment by GuoMonth** [comment]
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Arg_NoDefCTor, KudiManager.Shared.MainLayout
System.MissingMethodException: Arg_NoDefCTor, KudiManager.Shared.MainLayout
   at System.Activator.CreateInstance(Type , Boolean )
   at System.Activator.CreateInstance(Type )
   at Microsoft.AspNetCore.Components.DefaultComponentActivator.CreateInstance(Type )
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& , Int32 , Int32 , Int32 , Int32 )
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder , RenderFragment , Exception& )
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
u @ blazor.webassembly.js:1
Ke._internal.dotNetCriticalError @ blazor.webassembly.js:1
_bound_js_Blazor__internal_dotNetCriticalError @ _bound_js_Blazor__internal_dotNetCriticalError:7
Ss @ dotnet.7.0.12.78xc7rk4sj.js:5
_mono_wasm_invoke_bound_function @ dotnet.7.0.12.78xc7rk4sj.js:14
$func19421 @ 04217736:0x588041
$func6122 @ 04217736:0x1e5313
$func6117 @ 04217736:0x1e42bc
$func6612 @ 04217736:0x2065c0
$func41402 @ 04217736:0xacf062
invoke_vi @ dotnet.7.0.12.78xc7rk4sj.js:14
$func41681 @ 04217736:0xaeb76d
$func41372 @ 04217736:0xace59c
$func41309 @ 04217736:0xabe17d
$func41355 @ 04217736:0xacdc4e
$func41415 @ 04217736:0xacf54c
$func5295 @ 04217736:0x1aec03
$func7885 @ 04217736:0x256a0e
$func6432 @ 04217736:0x1fab8c
$func6169 @ 04217736:0x1e8221
$func6168 @ 04217736:0x1e815b
$func1622 @ 04217736:0xbf51f
$func41402 @ 04217736:0xacefe4
invoke_vi @ dotnet.7.0.12.78xc7rk4sj.js:14
$func41681 @ 04217736:0xaeb76d
$func41372 @ 04217736:0xace59c
$func41309 @ 04217736:0xabe026
$func41355 @ 04217736:0xacdc4e
$func41410 @ 04217736:0xacf3c6
$func1607 @ 04217736:0xbf164
$func3915 @ 04217736:0x14982c
$func3932 @ 04217736:0x14b423
$func6165 @ 04217736:0x1e7a98
$func3723 @ 04217736:0x134ff7
$func3500 @ 04217736:0x1292ef
invoke_viii @ dotnet.7.0.12.78xc7rk4sj.js:14
$func3513 @ 04217736:0x129e95
$func3523 @ 04217736:0x12a45b
invoke_iii @ dotnet.7.0.12.78xc7rk4sj.js:14
$func3533 @ 04217736:0x12b22a
$func1607 @ 04217736:0xbf164
$func41402 @ 04217736:0xacefd1
invoke_vi @ dotnet.7.0.12.78xc7rk4sj.js:14
$func41681 @ 04217736:0xaeb76d
$func41372 @ 04217736:0xace59c
$func41309 @ 04217736:0xabe17d
$func41308 @ 04217736:0xabc4cf
$func48774 @ 04217736:0xc52435
$func42796 @ 04217736:0xb2cc16
$func42794 @ 04217736:0xb2cb85
$func48841 @ 04217736:0xc54d12
$func37443 @ 04217736:0x9ff22d
$func37734 @ 04217736:0xa0c6b5
$func3522 @ 04217736:0x12a316
$func3520 @ 04217736:0x12a20f
invoke_iiii @ dotnet.7.0.12.78xc7rk4sj.js:14
$func4103 @ 04217736:0x15d777
$func3996 @ 04217736:0x1516fd
invoke_viii @ dotnet.7.0.12.78xc7rk4sj.js:14
$func3995 @ 04217736:0x15134b
$func1607 @ 04217736:0xbf164
$func41402 @ 04217736:0xacefd1
invoke_vi @ dotnet.7.0.12.78xc7rk4sj.js:14
$func41681 @ 04217736:0xaeb76d
$func41372 @ 04217736:0xace59c
$func41309 @ 04217736:0xabe17d
$func41308 @ 04217736:0xabc4cf
$func48774 @ 04217736:0xc52435
$func42796 @ 04217736:0xb2cc16
$func42794 @ 04217736:0xb2cb85
$func48841 @ 04217736:0xc54d12
$func37443 @ 04217736:0x9ff22d
$func37734 @ 04217736:0xa0c6b5
$func3912 @ 04217736:0x1495d7
$func6162 @ 04217736:0x1e7871
invoke_iiiiii @ dotnet.7.0.12.78xc7rk4sj.js:14
$func6214 @ 04217736:0x1ea9a4
$func1607 @ 04217736:0xbf164
$func41402 @ 04217736:0xacefd1
invoke_vi @ dotnet.7.0.12.78xc7rk4sj.js:14
$func41681 @ 04217736:0xaeb76d
$func41372 @ 04217736:0xace59c
$func41309 @ 04217736:0xabe17d
$func41308 @ 04217736:0xabc4cf
$func48774 @ 04217736:0xc52435
$func42796 @ 04217736:0xb2cc16
$func42794 @ 04217736:0xb2cb85
$func48841 @ 04217736:0xc54d12
$func37443 @ 04217736:0x9ff22d
$func37734 @ 04217736:0xa0c6b5
$func6213 @ 04217736:0x1ea510
$func6539 @ 04217736:0x2039d1
$func6224 @ 04217736:0x1ed5cb
invoke_viii @ dotnet.7.0.12.78xc7rk4sj.js:14
$func6223 @ 04217736:0x1ecd0c
$func1607 @ 04217736:0xbf164
$func41402 @ 04217736:0xacefd1
invoke_vi @ dotnet.7.0.12.78xc7rk4sj.js:14
$func41681 @ 04217736:0xaeb76d
$func41372 @ 04217736:0xace59c
$func41309 @ 04217736:0xabe17d
$func41308 @ 04217736:0xabc4cf
$func48774 @ 04217736:0xc52435
$func42796 @ 04217736:0xb2cc16
$func42794 @ 04217736:0xb2cb85
$func48841 @ 04217736:0xc54d12
$func37443 @ 04217736:0x9ff22d
$func37754 @ 04217736:0xa0d0f4
$func39888 @ 04217736:0xa91c95
invoke_viii @ dotnet.7.0.12.78xc7rk4sj.js:14
$func34081 @ 04217736:0x9340d5
$func37758 @ 04217736:0xa0d4a3
$func37757 @ 04217736:0xa0d389
$func1607 @ 04217736:0xbf164
$func41402 @ 04217736:0xacefd1
invoke_vi @ dotnet.7.0.12.78xc7rk4sj.js:14
$func41681 @ 04217736:0xaeb76d
$func41372 @ 04217736:0xace59c
$func41309 @ 04217736:0xabe026
$func41355 @ 04217736:0xacdc4e
$func41430 @ 04217736:0xacfa32
$func5180 @ 04217736:0x1a8267
$func34751 @ 04217736:0x958127
$func34749 @ 04217736:0x95730f
$func34623 @ 04217736:0x950194
$func34420 @ 04217736:0x945e50
$func35203 @ 04217736:0x96aee1
$func35249 @ 04217736:0x96c59c
$func1607 @ 04217736:0xbf164
$func41402 @ 04217736:0xacefd1
invoke_vi @ dotnet.7.0.12.78xc7rk4sj.js:14
$func41681 @ 04217736:0xaeb76d
$func41372 @ 04217736:0xace59c
$func41309 @ 04217736:0xabe17d
$func41308 @ 04217736:0xabc4cf
$func48774 @ 04217736:0xc52435
$func42796 @ 04217736:0xb2cc16
$func42794 @ 04217736:0xb2cb85
$func48841 @ 04217736:0xc54d12
$func37443 @ 04217736:0x9ff22d
$func37754 @ 04217736:0xa0d0f4
$func39888 @ 04217736:0xa91c95
invoke_viii @ dotnet.7.0.12.78xc7rk4sj.js:14
$func34081 @ 04217736:0x9340d5
$func37758 @ 04217736:0xa0d4a3
$func37757 @ 04217736:0xa0d389
$func1607 @ 04217736:0xbf164
$func41402 @ 04217736:0xacefd1
invoke_vi @ dotnet.7.0.12.78xc7rk4sj.js:14
$func41681 @ 04217736:0xaeb76d
$func41372 @ 04217736:0xace59c
$func41309 @ 04217736:0xabe026
$func41355 @ 04217736:0xacdc4e
$func41430 @ 04217736:0xacfa32
$func5180 @ 04217736:0x1a8267
$func34751 @ 04217736:0x958127
$func34749 @ 04217736:0x95730f
$func34623 @ 04217736:0x950194
$func34619 @ 04217736:0x94ffbd
$func34852 @ 04217736:0x95dec7
$func34851 @ 04217736:0x95de00
$func19467 @ 04217736:0x58d341
$func19981 @ 04217736:0x5ac611
$func41402 @ 04217736:0xacefe4
invoke_vi @ dotnet.7.0.12.78xc7rk4sj.js:14
$func41681 @ 04217736:0xaeb76d
$func41372 @ 04217736:0xace59c
$func41309 @ 04217736:0xabe17d
$func41308 @ 04217736:0xabc4cf
$func48774 @ 04217736:0xc52435
$func42796 @ 04217736:0xb2cc16
$func42801 @ 04217736:0xb2d3b1
$func42828 @ 04217736:0xb2f605
$mono_wasm_invoke_method_ref @ 04217736:0xc83bc8
Module._mono_wasm_invoke_method_ref @ dotnet.7.0.12.78xc7rk4sj.js:14
BINDINGS_SetTaskSourceResultRef @ BINDINGS_SetTaskSourceResultRef:27
Ki.t.<computed> @ dotnet.7.0.12.78xc7rk4sj.js:5
(anonymous) @ dotnet.7.0.12.78xc7rk4sj.js:5
Promise.then (async)
si @ dotnet.7.0.12.78xc7rk4sj.js:5
Qs @ dotnet.7.0.12.78xc7rk4sj.js:5
Xs @ dotnet.7.0.12.78xc7rk4sj.js:5
Ke._internal.getSatelliteAssemblies @ blazor.webassembly.js:1
Gt @ blazor.webassembly.js:1
Ii @ dotnet.7.0.12.78xc7rk4sj.js:5
_mono_wasm_invoke_js_blazor @ dotnet.7.0.12.78xc7rk4sj.js:14
$func41401 @ 04217736:0xaceedb
$func41371 @ 04217736:0xace28c
$func41309 @ 04217736:0xabd6a4
$func41308 @ 04217736:0xabc4cf
$func48774 @ 04217736:0xc52435
$func42796 @ 04217736:0xb2cc16
$func42794 @ 04217736:0xb2cb85
$func48841 @ 04217736:0xc54d12
$func37443 @ 04217736:0x9ff22d
$func37734 @ 04217736:0xa0c6b5
$func6200 @ 04217736:0x1e9d04
invoke_viii @ dotnet.7.0.12.78xc7rk4sj.js:14
$func6223 @ 04217736:0x1ebd75
$func1607 @ 04217736:0xbf164
$func41402 @ 04217736:0xacefd1
invoke_vi @ dotnet.7.0.12.78xc7rk4sj.js:14
$func41681 @ 04217736:0xaeb76d
$func41372 @ 04217736:0xace59c
$func41309 @ 04217736:0xabe17d
$func41308 @ 04217736:0xabc4cf
$func48774 @ 04217736:0xc52435
$func42796 @ 04217736:0xb2cc16
$func42794 @ 04217736:0xb2cb85
$func48841 @ 04217736:0xc54d12
$func37443 @ 04217736:0x9ff22d
$func37734 @ 04217736:0xa0c6b5
$func6210 @ 04217736:0x1ea3ac
$func6209 @ 04217736:0x1ea2d4
invoke_iii @ dotnet.7.0.12.78xc7rk4sj.js:14
$func10032 @ 04217736:0x2e850d
$func1607 @ 04217736:0xbf164
$func41402 @ 04217736:0xacefd1
invoke_vi @ dotnet.7.0.12.78xc7rk4sj.js:14
$func41681 @ 04217736:0xaeb76d
$func41372 @ 04217736:0xace59c
$func41309 @ 04217736:0xabe17d
$func41308 @ 04217736:0xabc4cf
$func48774 @ 04217736:0xc52435
$func42796 @ 04217736:0xb2cc16
$func42794 @ 04217736:0xb2cb85
$func48841 @ 04217736:0xc54d12
$func37443 @ 04217736:0x9ff22d
$func37734 @ 04217736:0xa0c6b5
$func10030 @ 04217736:0x2e7735
$func1612 @ 04217736:0xbf2ff
$func41402 @ 04217736:0xacefe4
invoke_vi @ dotnet.7.0.12.78xc7rk4sj.js:14
$func41681 @ 04217736:0xaeb76d
$func41372 @ 04217736:0xace59c
$func41309 @ 04217736:0xabe17d
$func41308 @ 04217736:0xabc4cf
$func48774 @ 04217736:0xc52435
$func42796 @ 04217736:0xb2cc16
$func42801 @ 04217736:0xb2d3b1
$func42828 @ 04217736:0xb2f605
$mono_wasm_invoke_method_ref @ 04217736:0xc83bc8
Module._mono_wasm_invoke_method_ref @ dotnet.7.0.12.78xc7rk4sj.js:14
_KudiManager__entrypoint @ _KudiManager__entrypoint:26
(anonymous) @ dotnet.7.0.12.78xc7rk4sj.js:5
ji @ dotnet.7.0.12.78xc7rk4sj.js:5
callEntryPoint @ blazor.webassembly.js:1
Vt @ blazor.webassembly.js:1
await in Vt (async)
(anonymous) @ (index):199
blazor.webassembly.js:1  crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Arg_NullReferenceException
System.NullReferenceException: Arg_NullReferenceException
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& , Int32 , Int32 , Int32 , Int32 )
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder , RenderFragment , Exception& )
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
u @ blazor.webassembly.js:1
Ke._internal.dotNetCriticalError @ blazor.webassembly.js:1
_bound_js_Blazor__internal_dotNetCriticalError @ _bound_js_Blazor__internal_dotNetCriticalError:7
Ss @ dotnet.7.0.12.78xc7rk4sj.js:5
_mono_wasm_invoke_bound_function @ dotnet.7.0.12.78xc7rk4sj.js:14
$func19421 @ 04217736:0x588041
$func6122 @ 04217736:0x1e5313
$func6117 @ 04217736:0x1e42bc
$func6612 @ 04217736:0x2065c0
$func41402 @ 04217736:0xacf062
invoke_vi @ dotnet.7.0.12.78xc7rk4sj.js:14
$func41681 @ 04217736:0xaeb76d
$func41372 @ 04217736:0xace59c
$func41309 @ 04217736:0xabe17d
$func41355 @ 04217736:0xacdc4e
$func41415 @ 04217736:0xacf54c
$func5295 @ 04217736:0x1aec03
$func7885 @ 04217736:0x256a0e
$func6432 @ 04217736:0x1fab8c
$func6169 @ 04217736:0x1e8221
$func6168 @ 04217736:0x1e815b
$func1622 @ 04217736:0xbf51f
$func41402 @ 04217736:0xacefe4
invoke_vi @ dotnet.7.0.12.78xc7rk4sj.js:14
$func41681 @ 04217736:0xaeb76d
$func41372 @ 04217736:0xace59c
$func41309 @ 04217736:0xabe026
$func41355 @ 04217736:0xacdc4e
$func41410 @ 04217736:0xacf3c6
$func1607 @ 04217736:0xbf164
$func3915 @ 04217736:0x14982c
$func3932 @ 04217736:0x14b423
$func6165 @ 04217736:0x1e7a98
$func3723 @ 04217736:0x134ff7
$func3500 @ 04217736:0x1292ef
invoke_viii @ dotnet.7.0.12.78xc7rk4sj.js:14
$func3513 @ 04217736:0x129e95
$func3523 @ 04217736:0x12a45b
invoke_iii @ dotnet.7.0.12.78xc7rk4sj.js:14
$func3533 @ 04217736:0x12b22a
$func1607 @ 04217736:0xbf164
$func41402 @ 04217736:0xacefd1
invoke_vi @ dotnet.7.0.12.78xc7rk4sj.js:14
$func41681 @ 04217736:0xaeb76d
$func41372 @ 04217736:0xace59c
$func41309 @ 04217736:0xabe17d
$func41308 @ 04217736:0xabc4cf
$func48774 @ 04217736:0xc52435
$func42796 @ 04217736:0xb2cc16
$func42794 @ 04217736:0xb2cb85
$func48841 @ 04217736:0xc54d12
$func37443 @ 04217736:0x9ff22d
$func37734 @ 04217736:0xa0c6b5
$func3522 @ 04217736:0x12a316
$func3520 @ 04217736:0x12a20f
invoke_iiii @ dotnet.7.0.12.78xc7rk4sj.js:14
$func4103 @ 04217736:0x15d777
$func3996 @ 04217736:0x1516fd
invoke_viii @ dotnet.7.0.12.78xc7rk4sj.js:14
$func3995 @ 04217736:0x15134b
$func1607 @ 04217736:0xbf164
$func41402 @ 04217736:0xacefd1
invoke_vi @ dotnet.7.0.12.78xc7rk4sj.js:14
$func41681 @ 04217736:0xaeb76d
$func41372 @ 04217736:0xace59c
$func41309 @ 04217736:0xabe17d
$func41308 @ 04217736:0xabc4cf
$func48774 @ 04217736:0xc52435
$func42796 @ 04217736:0xb2cc16
$func42794 @ 04217736:0xb2cb85
$func48841 @ 04217736:0xc54d12
$func37443 @ 04217736:0x9ff22d
$func37734 @ 04217736:0xa0c6b5
$func3912 @ 04217736:0x1495d7
$func6162 @ 04217736:0x1e7871
invoke_iiiiii @ dotnet.7.0.12.78xc7rk4sj.js:14
$func6214 @ 04217736:0x1ea9a4
$func1607 @ 04217736:0xbf164
$func41402 @ 04217736:0xacefd1
invoke_vi @ dotnet.7.0.12.78xc7rk4sj.js:14
$func41681 @ 04217736:0xaeb76d
$func41372 @ 04217736:0xace59c
$func41309 @ 04217736:0xabe17d
$func41308 @ 04217736:0xabc4cf
$func48774 @ 04217736:0xc52435
$func42796 @ 04217736:0xb2cc16
$func42794 @ 04217736:0xb2cb85
$func48841 @ 04217736:0xc54d12
$func37443 @ 04217736:0x9ff22d
$func37734 @ 04217736:0xa0c6b5
$func6213 @ 04217736:0x1ea510
$func6539 @ 04217736:0x2039d1
$func6224 @ 04217736:0x1ed5cb
invoke_viii @ dotnet.7.0.12.78xc7rk4sj.js:14
$func6223 @ 04217736:0x1ecd0c
$func1607 @ 04217736:0xbf164
$func41402 @ 04217736:0xacefd1
invoke_vi @ dotnet.7.0.12.78xc7rk4sj.js:14
$func41681 @ 04217736:0xaeb76d
$func41372 @ 04217736:0xace59c
$func41309 @ 04217736:0xabe17d
$func41308 @ 04217736:0xabc4cf
$func48774 @ 04217736:0xc52435
$func42796 @ 04217736:0xb2cc16
$func42794 @ 04217736:0xb2cb85
$func48841 @ 04217736:0xc54d12
$func37443 @ 04217736:0x9ff22d
$func37754 @ 04217736:0xa0d0f4
$func39888 @ 04217736:0xa91c95
invoke_viii @ dotnet.7.0.12.78xc7rk4sj.js:14
$func34081 @ 04217736:0x9340d5
$func37758 @ 04217736:0xa0d4a3
$func37757 @ 04217736:0xa0d389
$func1607 @ 04217736:0xbf164
$func41402 @ 04217736:0xacefd1
invoke_vi @ dotnet.7.0.12.78xc7rk4sj.js:14
$func41681 @ 04217736:0xaeb76d
$func41372 @ 04217736:0xace59c
$func41309 @ 04217736:0xabe026
$func41355 @ 04217736:0xacdc4e
$func41430 @ 04217736:0xacfa32
$func5180 @ 04217736:0x1a8267
$func34751 @ 04217736:0x958127
$func34749 @ 04217736:0x95730f
$func34623 @ 04217736:0x950194
$func34420 @ 04217736:0x945e50
$func35203 @ 04217736:0x96aee1
$func35249 @ 04217736:0x96c59c
$func1607 @ 04217736:0xbf164
$func41402 @ 04217736:0xacefd1
invoke_vi @ dotnet.7.0.12.78xc7rk4sj.js:14
$func41681 @ 04217736:0xaeb76d
$func41372 @ 04217736:0xace59c
$func41309 @ 04217736:0xabe17d
$func41308 @ 04217736:0xabc4cf
$func48774 @ 04217736:0xc52435
$func42796 @ 04217736:0xb2cc16
$func42794 @ 04217736:0xb2cb85
$func48841 @ 04217736:0xc54d12
$func37443 @ 04217736:0x9ff22d
$func37754 @ 04217736:0xa0d0f4
$func39888 @ 04217736:0xa91c95
invoke_viii @ dotnet.7.0.12.78xc7rk4sj.js:14
$func34081 @ 04217736:0x9340d5
$func37758 @ 04217736:0xa0d4a3
$func37757 @ 04217736:0xa0d389
$func1607 @ 04217736:0xbf164
$func41402 @ 04217736:0xacefd1
invoke_vi @ dotnet.7.0.12.78xc7rk4sj.js:14
$func41681 @ 04217736:0xaeb76d
$func41372 @ 04217736:0xace59c
$func41309 @ 04217736:0xabe026
$func41355 @ 04217736:0xacdc4e
$func41430 @ 04217736:0xacfa32
$func5180 @ 04217736:0x1a8267
$func34751 @ 04217736:0x958127
$func34749 @ 04217736:0x95730f
$func34623 @ 04217736:0x950194
$func34619 @ 04217736:0x94ffbd
$func34852 @ 04217736:0x95dec7
$func34851 @ 04217736:0x95de00
$func19467 @ 04217736:0x58d341
$func19981 @ 04217736:0x5ac611
$func41402 @ 04217736:0xacefe4
invoke_vi @ dotnet.7.0.12.78xc7rk4sj.js:14
$func41681 @ 04217736:0xaeb76d
$func41372 @ 04217736:0xace59c
$func41309 @ 04217736:0xabe17d
$func41308 @ 04217736:0xabc4cf
$func48774 @ 04217736:0xc52435
$func42796 @ 04217736:0xb2cc16
$func42801 @ 04217736:0xb2d3b1
$func42828 @ 04217736:0xb2f605
$mono_wasm_invoke_method_ref @ 04217736:0xc83bc8
Module._mono_wasm_invoke_method_ref @ dotnet.7.0.12.78xc7rk4sj.js:14
BINDINGS_SetTaskSourceResultRef @ BINDINGS_SetTaskSourceResultRef:27
Ki.t.<computed> @ dotnet.7.0.12.78xc7rk4sj.js:5
(anonymous) @ dotnet.7.0.12.78xc7rk4sj.js:5
Promise.then (async)
si @ dotnet.7.0.12.78xc7rk4sj.js:5
Qs @ dotnet.7.0.12.78xc7rk4sj.js:5
Xs @ dotnet.7.0.12.78xc7rk4sj.js:5
Ke._internal.getSatelliteAssemblies @ blazor.webassembly.js:1
Gt @ blazor.webassembly.js:1
Ii @ dotnet.7.0.12.78xc7rk4sj.js:5
_mono_wasm_invoke_js_blazor @ dotnet.7.0.12.78xc7rk4sj.js:14
$func41401 @ 04217736:0xaceedb
$func41371 @ 04217736:0xace28c
$func41309 @ 04217736:0xabd6a4
$func41308 @ 04217736:0xabc4cf
$func48774 @ 04217736:0xc52435
$func42796 @ 04217736:0xb2cc16
$func42794 @ 04217736:0xb2cb85
$func48841 @ 04217736:0xc54d12
$func37443 @ 04217736:0x9ff22d
$func37734 @ 04217736:0xa0c6b5
$func6200 @ 04217736:0x1e9d04
invoke_viii @ dotnet.7.0.12.78xc7rk4sj.js:14
$func6223 @ 04217736:0x1ebd75
$func1607 @ 04217736:0xbf164
$func41402 @ 04217736:0xacefd1
invoke_vi @ dotnet.7.0.12.78xc7rk4sj.js:14
$func41681 @ 04217736:0xaeb76d
$func41372 @ 04217736:0xace59c
$func41309 @ 04217736:0xabe17d
$func41308 @ 04217736:0xabc4cf
$func48774 @ 04217736:0xc52435
$func42796 @ 04217736:0xb2cc16
$func42794 @ 04217736:0xb2cb85
$func48841 @ 04217736:0xc54d12
$func37443 @ 04217736:0x9ff22d
$func37734 @ 04217736:0xa0c6b5
$func6210 @ 04217736:0x1ea3ac
$func6209 @ 04217736:0x1ea2d4
invoke_iii @ dotnet.7.0.12.78xc7rk4sj.js:14
$func10032 @ 04217736:0x2e850d
$func1607 @ 04217736:0xbf164
$func41402 @ 04217736:0xacefd1
invoke_vi @ dotnet.7.0.12.78xc7rk4sj.js:14
$func41681 @ 04217736:0xaeb76d
$func41372 @ 04217736:0xace59c
$func41309 @ 04217736:0xabe17d
$func41308 @ 04217736:0xabc4cf
$func48774 @ 04217736:0xc52435
$func42796 @ 04217736:0xb2cc16
$func42794 @ 04217736:0xb2cb85
$func48841 @ 04217736:0xc54d12
$func37443 @ 04217736:0x9ff22d
$func37734 @ 04217736:0xa0c6b5
$func10030 @ 04217736:0x2e7735
$func1612 @ 04217736:0xbf2ff
$func41402 @ 04217736:0xacefe4
invoke_vi @ dotnet.7.0.12.78xc7rk4sj.js:14
$func41681 @ 04217736:0xaeb76d
$func41372 @ 04217736:0xace59c
$func41309 @ 04217736:0xabe17d
$func41308 @ 04217736:0xabc4cf
$func48774 @ 04217736:0xc52435
$func42796 @ 04217736:0xb2cc16
$func42801 @ 04217736:0xb2d3b1
$func42828 @ 04217736:0xb2f605
$mono_wasm_invoke_method_ref @ 04217736:0xc83bc8
Module._mono_wasm_invoke_method_ref @ dotnet.7.0.12.78xc7rk4sj.js:14
_KudiManager__entrypoint @ _KudiManager__entrypoint:26
(anonymous) @ dotnet.7.0.12.78xc7rk4sj.js:5
ji @ dotnet.7.0.12.78xc7rk4sj.js:5
callEntryPoint @ blazor.webassembly.js:1
Vt @ blazor.webassembly.js:1
await in Vt (async)
(anonymous) @ (index):199
```

**Comment by mkArtakMSFT** [comment]
Hi. Thanks for contacting us.
We're closing this issue as there was not much community interest in this ask for quite a while now.
You can learn more about our triage process and how we handle issues by reading our [Triage Process](https://github.com/dotnet/aspnetcore/blob/master/docs/TriageProcess.md) writeup.
