### ISSUE TITLE
Cannot deserialize into `google.protobuf.NullValue` in gRPC JSON transcoding

### ISSUE THREAD

**Issue by alrz** [dotnet/aspnetcore#51521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The payload `{ "prop": null }` fails to deserialize into an instance of `google.protobuf.Struct`

```
System.ArgumentNullException: Value cannot be null. (Parameter 'value')
         at Google.Protobuf.ProtoPreconditions.CheckNotNullUnconstrained[T](T value, String name)
         at Google.Protobuf.Collections.MapField`2.set_Item(TKey key, TValue value)
         at Google.Protobuf.Collections.MapField`2.System.Collections.IDictionary.set_Item(Object key, Object value)
         at Microsoft.AspNetCore.Grpc.JsonTranscoding.Internal.Json.JsonConverterHelper.PopulateMap(Utf8JsonReader& reader, JsonSerializerOptions options, IMessage message, FieldDescriptor fieldDescriptor)
         at Microsoft.AspNetCore.Grpc.JsonTranscoding.Internal.Json.StructConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)      
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObjectAsync(Stream utf8Json, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Grpc.JsonTranscoding.Internal.JsonRequestHelpers.ReadMessage[TRequest](JsonTranscodingServerCallContext serverCallContext, JsonSerializerOptions serializerOptions)      
         at Microsoft.AspNetCore.Grpc.JsonTranscoding.Internal.JsonRequestHelpers.ReadMessage[TRequest](JsonTranscodingServerCallContext serverCallContext, JsonSerializerOptions serializerOptions)  
```

### Expected Behavior

An instance of `NullValue` is correctly returned for a value of `null`.

**Comment by vishm** [comment]
https://protobuf.dev/reference/java/api-docs/com/google/protobuf/Struct.html#getFields-- suggest Value (click on link), can represent a null. I too am hitting same issue in .Net grpc transcoding. @alrz did u find a workaround

**Comment by JamesNK** [comment]
I have a fix here - https://github.com/dotnet/aspnetcore/pull/52442

There isn't a way to work around this. I'll look at getting this fix included in a .NET 8 servicing fix, e.g. 8.0.x
