### ISSUE TITLE
Fluent-UI or MudBlazor Interactivity fix breaks SigninManager

### ISSUE THREAD

**Issue by devtrix** [dotnet/aspnetcore#51554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I created a Blazor 8 WebApp of all the interactivity kinds and tried both Fluent-ui & MudBlkazor.  For the interactivity to work I had to add the rendermode as InteractiveServer to the router tag.  
This fixed the JS issue but this affects the identity processes such as Register or Login. I get the following errors in the console.

`
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
'Blazor8App.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0-rc.2.23479.6\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer: Warning: Unhandled exception rendering component: Headers are read-only, response has already started.

System.InvalidOperationException: Headers are read-only, response has already started.
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowHeadersReadOnlyException()
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseHeaders.Microsoft.AspNetCore.Http.IHeaderDictionary.set_SetCookie(StringValues value)
at Microsoft.AspNetCore.Http.ResponseCookies.Append(String key, String value, CookieOptions options)
at Microsoft.AspNetCore.Authentication.Cookies.ChunkingCookieManager.AppendResponseCookie(HttpContext context, String key, String value, CookieOptions options)
at Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler.HandleSignInAsync(ClaimsPrincipal user, AuthenticationProperties properties)
at Microsoft.AspNetCore.Authentication.AuthenticationService.SignInAsync(HttpContext context, String scheme, ClaimsPrincipal principal, AuthenticationProperties properties)
at Microsoft.AspNetCore.Identity.SignInManager1.SignInWithClaimsAsync(TUser user, AuthenticationProperties authenticationProperties, IEnumerable1 additionalClaims)
at Microsoft.AspNetCore.Identity.SignInManager1.SignInOrTwoFactorAsync(TUser user, Boolean isPersistent, String loginProvider, Boolean bypassTwoFactor) at Microsoft.AspNetCore.Identity.SignInManager1.PasswordSignInAsync(TUser user, String password, Boolean isPersistent, Boolean lockoutOnFailure)
at Microsoft.AspNetCore.Identity.SignInManager1.PasswordSignInAsync(String userName, String password, Boolean isPersistent, Boolean lockoutOnFailure) at Blazor8App.Components.Pages.Account.Login.LoginUser() in C:\Users\devtr\source\repos\Blazor8App\Blazor8App\Components\Pages\Account\Login.razor:line 111 at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task) at Microsoft.AspNetCore.Components.Forms.EditForm.HandleSubmitAsync() at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task) at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState) Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Error: Unhandled exception in circuit 'H82WxMerEA_MNs1Ydrx3bTrKW3-Ko3dTwzMe4X4RcQI'. 
`

### Expected Behavior

For the libs to work.  Any guidance is much appreciated..

### .NET Version

.net 8

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
Just for context, the SignInManager is designed to work in non-interactive mode (SSR), because it need to be able to modify the response headers. If you're trying to use them in an interactive mode that's a non-supported scenario in .NET 8. If this is not something that you're experiencing, please proceed with providing a repro project and we'd happily investigate it further.

**Comment by devtrix** [comment]
@mkArtakMSFT Thanks for your response.  
Basically Signin manager works in non-interactive mode but the other libraries work in interactive mode and I am just a user of both.  I have embarked on a journey to create my own components from scratch as this is an issue for the library vendors to figure out.  But thanks anyways.  Have a good day.
