### ISSUE TITLE
JSONTranscoding: Handling of explicit nulls in JSON

### ISSUE THREAD

**Issue by purkhusid** [dotnet/aspnetcore#51742]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using gRPC JSON Transcoding with payloads that look like this:

```
{
  "message": {
    "messageProperty": null
  }
}
```

where the proto message might look like this:
```
message Message {
  optional string message_property = 0;
}
```

The transcoder fails with the following error:
```
{
  "code": 3,
  "message": "Value cannot be null. (Parameter 'value')",
  "details": []
}
```

This can be tracked to this location in the transcoder: https://github.com/dotnet/aspnetcore/blob/0bffc80eb103b6dca63a6249a168c4fee45d64ca/src/Grpc/JsonTranscoding/src/Microsoft.AspNetCore.Grpc.JsonTranscoding/Internal/Json/MessageTypeInfoResolver.cs#L144

Stacktrace:
```
System.ArgumentNullException: Value cannot be null. (Parameter 'value')
         at Google.Protobuf.ProtoPreconditions.CheckNotNull[T](T value, String name)
         at Src.Protobuf.IngestionApi.Service.ContactInformation.set_Email(String value)
         at Google.Protobuf.Reflection.ReflectionUtil.ReflectionHelper`2.<>c__DisplayClass3_0.<CreateActionIMessageObject>b__0(IMessage message, Object arg)
         at Google.Protobuf.Reflection.SingleFieldAccessor.SetValue(IMessage message, Object value)
         at Microsoft.AspNetCore.Grpc.JsonTranscoding.Internal.Json.MessageTypeInfoResolver.<>c__DisplayClass5_0.<GetSetMethod>b__3(Object o, Object v)
         at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
         at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
         at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
         at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo, ReadStack& state)
         at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonTypeInfo jsonTypeInfo)
         at System.Text.Json.JsonSerializer.ReadFromStreamAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Grpc.JsonTranscoding.Internal.JsonRequestHelpers.ReadMessage[TRequest](JsonTranscodingServerCallContext serverCallContext, JsonSerializerOptions serializerOptions)
         at Microsoft.AspNetCore.Grpc.JsonTranscoding.Internal.JsonRequestHelpers.ReadMessage[TRequest](JsonTranscodingServerCallContext serverCallContext, JsonSerializerOptions serializerOptions)
```

### Expected Behavior

I would expect the transcoder to ignore properties set explicitly to `null` since that is generally looked at the same way as omitting the porperty when working with JSON.

If that is not an acceptable solution then I would suggest that an new transcoder option would be exposed where you can set this behaviour.

### .NET Version

7.0.400

**Comment by ivanch** [comment]
Hey!

This issue has been open for a long time, not sure if it still needs a fix (last time I tested it did).
I've opened a PR for this: #52383.

I liked your suggestion to add a setting for this, so I've added a check to see whether `GrpcJsonSettings.IgnoreNullValues` is true, if it is and the field comes as `null`, it will be ignored (just like it's supposed to).

Also, I've seen that if we send a JSON message without the `messageProperty` field (following your example), it worked as expected as well. The problem here was that it was receiving `null` and it threw an Exception.
