### ISSUE TITLE
Quarantine ConnectionClosedWithoutActiveRequestsOrGoAwayFIN

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#51770]
## Failing Test(s)

Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.Http2.ShutdownTests.ConnectionClosedWithoutActiveRequestsOrGoAwayFIN

It's timed out several times recently in `release/8.0`.

## Error Message

```text
System.TimeoutException : The operation has timed out.
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 123
   at Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.Http2.ShutdownTests.ConnectionClosedWithoutActiveRequestsOrGoAwayFIN() in /_/src/Servers/Kestrel/test/FunctionalTests/Http2/ShutdownTests.cs:line 93
   at Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.Http2.ShutdownTests.ConnectionClosedWithoutActiveRequestsOrGoAwayFIN() in /_/src/Servers/Kestrel/test/FunctionalTests/Http2/ShutdownTests.cs:line 97
--- End of stack trace from previous location ---
```
</details>

## Logs

<details>

```text
[0.005s] [TestLifetime] [Information] Starting test ConnectionClosedWithoutActiveRequestsOrGoAwayFIN at 2023-10-26T21:01:46
[0.008s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting starting
[0.011s] [Microsoft.Hosting.Lifetime] [Information] Now listening on: https://127.0.0.1:51206
[0.011s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Debug] Loaded hosting startup assembly Sockets.FunctionalTests
[0.011s] [Microsoft.Hosting.Lifetime] [Information] Application started. Press Ctrl+C to shut down.
[0.011s] [Microsoft.Hosting.Lifetime] [Information] Hosting environment: Production
[0.015s] [Microsoft.Hosting.Lifetime] [Information] Content root path: C:\h\w\9FD008F2\w\A1A908FC\e\
[0.015s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting started
[0.015s] [Microsoft.AspNetCore.Server.Kestrel] [Debug] TestServer is listening on port 51206
[2.124s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMUMCR1AN8TS" accepted.
[2.125s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMUMCR1AN8TS" started.
[2.131s] [Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware] [Debug] Connection 0HMUMCR1AN8TS established using the following protocol: Tls13
[2.131s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMUMCR1AN8TS" sending SETTINGS frame for stream ID 0 with length 24 and flags NONE.
[2.131s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMUMCR1AN8TS" sending WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0.
[2.131s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMUMCR1AN8TS" received SETTINGS frame for stream ID 0 with length 12 and flags NONE.
[2.131s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMUMCR1AN8TS" sending SETTINGS frame for stream ID 0 with length 0 and flags ACK.
[2.132s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMUMCR1AN8TS" received WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0.
[2.132s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMUMCR1AN8TS" received HEADERS frame for stream ID 1 with length 20 and flags END_STREAM, END_HEADERS.
[2.132s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMUMCR1AN8TS" received SETTINGS frame for stream ID 0 with length 0 and flags ACK.
[2.132s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request starting HTTP/2 GET https://localhost:51206/ - null null
[2.132s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMUMCR1AN8TS" sending HEADERS frame for stream ID 1 with length 32 and flags END_HEADERS.
[2.132s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request finished HTTP/2 GET https://localhost:51206/ - 200 null null 0.4097ms
[2.133s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMUMCR1AN8TS" sending DATA frame for stream ID 1 with length 18 and flags END_STREAM.
[2.133s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMUMCR1AN8TS" received PING frame for stream ID 0 with length 8 and flags NONE.
[2.134s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMUMCR1AN8TS" sending PING frame for stream ID 0 with length 8 and flags ACK.
[2.134s] [Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets] [Debug] Connection id "0HMUMCR1AN8TS" reset.
[2.134s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Debug] Connection id "0HMUMCR1AN8TS" is closed. The last processed stream ID was 1.
[2.135s] [Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets] [Debug] Connection id "0HMUMCR1AN8TS" sending FIN because: "The Socket transport's send loop completed gracefully."
[2.135s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Debug] The connection queue processing loop for 0HMUMCR1AN8TS completed.
[2.135s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMUMCR1AN8TS" stopped.
[32.124s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting stopping
[32.124s] [Microsoft.Hosting.Lifetime] [Information] Application is shutting down...
[32.125s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting stopped
[32.127s] [Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.Http2.ShutdownTests] [Error] Test threw an exception.
System.TimeoutException: The operation has timed out.
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 123
   at Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.Http2.ShutdownTests.ConnectionClosedWithoutActiveRequestsOrGoAwayFIN() in /_/src/Servers/Kestrel/test/FunctionalTests/Http2/ShutdownTests.cs:line 93
   at Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.Http2.ShutdownTests.ConnectionClosedWithoutActiveRequestsOrGoAwayFIN() in /_/src/Servers/Kestrel/test/FunctionalTests/Http2/ShutdownTests.cs:line 97
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
[32.127s] [TestLifetime] [Information] Finished test ConnectionClosedWithoutActiveRequestsOrGoAwayFIN in 32.12239s
```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=452342
https://dev.azure.com/dnceng-public/public/_build/results?buildId=452420

**Comment by Tratcher** [comment]
Please include the logs, the builds expire after a while.

**Comment by SteveSandersonMS** [comment]
Logs added

**Comment by BrennanConroy** [comment]
I fixed this in main...
https://github.com/dotnet/aspnetcore/pull/51034
Why are we quarantining it in main when the failure is in 8.0.

**Comment by amcasey** [comment]
@BrennanConroy What do we do here?  Backport the fix or quarantine it forever?  cc @wtgodbe

**Comment by wtgodbe** [comment]
Test fixes don't generally meet the servicing bar, so it'd stay quarantined in 8
