### ISSUE TITLE
AddExceptionHandler/UseExceptionHandler Fails in a non-Obvious Way

### ISSUE THREAD

**Issue by shawnwildermuth** [dotnet/aspnetcore#51888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

With the new `AddExceptionHandler` and `IExceptionHandler` APIs, engaging the exception handler with UseExceptionHandler is confusing. For example, this code fails;

```cs
using ExHandler;
using Microsoft.AspNetCore.Diagnostics;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddExceptionHandler<GlobalExceptionHandler>();

var app = builder.Build();

app.UseExceptionHandler();       // Doesn't work

app.MapGet("/", () => {
  throw new Exception("Bad things happen to good developers");
});

app.Run();

public class GlobalExceptionHandler : IExceptionHandler
{
  public async ValueTask<bool> TryHandleAsync(HttpContext httpContext,
    Exception exception,
    CancellationToken cancellationToken)
  {
    httpContext.Response.ContentType = "text/plain";
    httpContext.Response.StatusCode = 501;
    await httpContext.Response.WriteAsync($"It don't work: {exception.Message}");
    return true;
  }
}
```

To make this work, you must pass in an empty lambda to the `UseExceptionHandler':

```cs
app.UseExceptionHandler(o => { }); // Works
```

### Expected Behavior

Expected the empty call to `UseExceptionHandler` to work. Could not find documentation that explained this. , 

### Steps To Reproduce

Example is at: https://github.com/shawnwildermuth/ExceptionHandlerRepro

### Exceptions (if any)

I get an arcane message:

```
System.InvalidOperationException
  HResult=0x80131509
  Message=An error occurred when configuring the exception handler middleware. Either the 'ExceptionHandlingPath' or the 'ExceptionHandler' property must be set in 'UseExceptionHandler()'. Alternatively, set one of the aforementioned properties in 'Startup.ConfigureServices' as follows: 'services.AddExceptionHandler(options => { ... });' or configure to generate a 'ProblemDetails' response in 'service.AddProblemDetails()'.
  Source=Microsoft.AspNetCore.Diagnostics
  StackTrace:
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl..ctor(RequestDelegate next, ILoggerFactory loggerFactory, IOptions`1 options, DiagnosticListener diagnosticListener, IEnumerable`1 exceptionHandlers, IMeterFactory meterFactory, IProblemDetailsService problemDetailsService)
   at Microsoft.AspNetCore.Builder.ExceptionHandlerExtensions.<>c__DisplayClass5_0.<SetExceptionHandlerMiddleware>b__0(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__40.MoveNext()
   at Microsoft.Extensions.Hosting.Internal.Host.<<StartAsync>b__15_1>d.MoveNext()
   at Microsoft.Extensions.Hosting.Internal.Host.<ForeachService>d__18`1.MoveNext()
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__15.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args) in C:\projects\codingshorts\net8exhandler\test\ExHandler\Program.cs:line 17
```

### .NET Version

8.0.100-rc.2.23502.2

### Anything else?

Note the failure is uncommented out, and the one that works is commented out. If this is expected behavior, we need it to be well documented since it is unobvious behavior.

**Comment by davidfowl** [comment]
Agreed this should be fixed now that we have exception handlers that can be added via DI.

**Comment by captainsafia** [comment]
PR open against main.

This is a good candidate for servicing to 8.0 as well.

**Comment by shawnwildermuth** [comment]
This has been fixed.

**Comment by dse-copsfs** [comment]
The [connected PR](https://github.com/dotnet/aspnetcore/pull/51898) has been closed.

We still facing this issue in **8.0.3**, so we have to use the proposed workaround `app.UseExceptionHandler(o => {});`

Could you please reopen this issue?

**Comment by captainsafia** [comment]
Yes, we never ended up addressing this because the ramifications of the breaking change weren't fully enumerated.

I'll reopen this issue but considering the current prioritizations and the fact that there is a workaround, this will likely go in the backlog.

I'm open to reviewing a PR with a fix though!

**Comment by diegocam** [comment]
Any updates here?

**Comment by latuconsinafr** [comment]
Still waiting for the update 👀

**Comment by hashproton** [comment]
> Still waiting for the update 👀

**Comment by ghhv** [comment]
fyi, I managed to get this issue on a brand new NET 8.0.8 Blazor Web Application project because I was calling this again by accident in a start-up helper function but without any parameters like so:
`app.UseExceptionHandler();`

I have this prior in the program.cs
` app.UseExceptionHandler("/Error", createScopeForErrors: true);`

The lack of parameters isn't an issue - it was calling it twice!

**Comment by Legion-ale** [comment]
For what i understand I can agree with @ghhv saying that the problem is how we configure the webApp, and not in the method itself.

I was having the same problem, and I was thinking I'd solved it with: `app.UseExceptionHandler(()=>{});` but, actually, we've just bypassed the correct exception management.

The real problem seems that you need to register a "default" response in case your `IExceptionHandler` return `false` (Even if every exception is correctly managed inside the `IExceptionHandler`).

Actually adding 'AddProblemDetails()' before your exception handler seems doing the trick:

```
        builder.Services.AddProblemDetails();
        builder.Services.AddExceptionHandler<GlobalExceptionHandler>();
[...]
        var app = builder.Build();
        app.UseExceptionHandler();
```
 but i'm not sure is the correct behaviour.
I [leave here microsoft link with the method explanation](https://learn.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-8.0):
 

> [...] code configures the app to generate a problem details response for all HTTP client and server error responses that don't have body content yet[...]

**Comment by kjkrum** [comment]
I'm also not seeing this issue when using an exception handler in combination with problem details. The order they're added to the service collection shouldn't matter.

```
builder.Services.AddExceptionHandler<ExceptionHandler>();
builder.Services.AddProblemDetails(options =>
{
	options.CustomizeProblemDetails = context =>
	{
		...
	};
});

app.UseStatusCodePages();
app.UseExceptionHandler();
```

If (and only if) the `IExceptionHandler` returns false, the exception is available in the customize action as `ProblemDetailsContext.Exception`. This makes sense, since I think the exception handler returning true means the exception does not propagate.

But letting an exception propagate so it appears in `ProblemDetailsContext.Exception` (e.g., so you can use it to add information to the problem details) triggers another bug. `ProblemDetailsContext.ProblemDetails` is always initialized as a 500 regardless of the status code set by the exception handler, and there's no way to leverage the existing defaults to re-initialize it (#47978).

**Comment by Kiran9684** [comment]
Hi, Any updates on this Fix ?

**Comment by Legion-ale** [comment]
> Hi, Any updates on this Fix ?

Based on my understanding of the problem, my previous answer is a full fledged solution (at least until you hit [that other bug](https://github.com/dotnet/aspnetcore/issues/47978)).
that problem is more a lack of documentation than an actual bug...
We were waiting confirmation from someone of the dev team if there is a more "clean" implementation... but at least we can consider it an acceptable alternative solution.

**Comment by svengeance** [comment]
Also running into this presently - we do not have error pages operating solely as an API, and do not wish to create them. My expectation is that the ServiceCollection DI will handle errors in order of IExceptionHandler registration, and the default error handling pipeline kicks in if no handlers are able to handle the exception.

**Comment by davidfowl** [comment]
I re-read this issue. @captainsafia made an attempt and there were some breaking change considerations. I see > 20 updates on https://github.com/dotnet/aspnetcore/issues/51888#issuecomment-2059642998. Has anyone in this issue looked at the PR and considered what the behavior should be given the potential breaking change? 

I'd love to see more of a technical discussion here rather than asking for updates. This issue is in the backlog, it's not going to get prioritized in its current state. If anyone feels really strongly about this and has time to dig in, that could really help get it unstuck.

**Comment by kjkrum** [comment]
@davidfowl The whole pipeline is broken. They need to stop worrying about backward compatibility and just fix it.

**Comment by davidfowl** [comment]
@kjkrum What's the proposal for what the behavior should be in all of the cases expressed in the original PR?

**Comment by Legion-ale** [comment]
I'm not a .NET developer, so maybe I'm missing something... but as @Tratcher said in the original PR, the issue lies in the interop between the new IExceptionHandler (which is basically a pipeline itself) and the old exception handling methods (which are more like a pseudo-pipeline that doesn’t integrate well with the new one).

The dev team tried to bind the new implementation to support the older ones, but that created a lot of unhandled scenarios.

Instead, we probably need to modify ProblemDetails and the old delegate so they can become part of the new IExceptionHandler pipeline (maybe by appending them at the end?)

But doing that without rethinking how the entire pipeline works leads to backward compatibility issues, because these changes will likely force end users to update their code when released in production.

Am I wrong?

**Comment by nthornton2010** [comment]
Is there a reason you don't want to add `service.AddProblemDetails()` to your Program.cs file?

The error message recommends doing one of the 3 things to fix:
1. Set either `ExceptionHandlingPath` or `ExceptionHandler` property in the `UseExceptionHandler` method. --- This is what you did as a workaround
2. Add/Set some options in `services.AddExceptionHandler`
3. Call `service.AddProblemDetails`

The first 2 seem like cases that should be done if you need to handle some special case. The 3rd seems like the ideal solution if you just want to use everything out of the box. I've done this in multiple services now and everything works as expected.

Since the error message specifies doing 1 of the 3 things, I'm not sure there's actually an issue here other than maybe for the error message to be worded better and possibly suggest calling `service.AddProblemDetails` first.

Perhaps I'm missing something regarding why we wouldn't want to do any of the 3 suggestions the error makes?

**Comment by MauNguyenVan** [comment]
Wow, this issue took me 2 hours to find out why the docs have this API but my app breaks when I use it.
If a newbie has just begun working with ASP and runs into this issue, someone would give up.
it is messy

**Comment by TRB7** [comment]
I got the same error today and tried this workaround `app.UseExceptionHandler(o => {});` as mentioned by @dse-copsfs and it worked.
I'm not sure when this will be fixed but if someone doesn't know, he may spend hours of searching for the root cause...

**Comment by shawnwildermuth** [comment]
That's been my issue. It's non-obvious.

**Comment by wallym** [comment]
I started getting the issue today after adding a custom exception handler.  I just happened to stumble upon this discussion.  The work around worked. I'm on .NET 9, if that matters.

**Comment by Rincho-M** [comment]
Yep, the same as folks above. Didn't spend too much time to find this issue but the thing is messy and some fix would be nice. I'm on .NET 10

**Comment by indy-singh** [comment]
Glad to see we aren't the only ones wasting hours trying to figure this out :\
