### ISSUE TITLE
MapRazorComponents fails if you don't have wwwroot

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#51957]
Consider this very minimal `Program.cs`:

```cs
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddRazorComponents();

var app = builder.Build();

app.MapRazorComponents<Layout>();
app.MapGet("/", () => new RazorComponentResult<MyComponent>());
app.Run();
```

For this app I don't need anything in `wwwroot` so I deleted the directory completely. But then the app fails to start, saying:

```
Unhandled exception. System.IO.DirectoryNotFoundException: C:\dir\MyApp\wwroot\
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.AspNetCore.Hosting.StaticWebAssets.StaticWebAssetsLoader.<>c.<UseStaticWebAssetsCore>b__1_0(String contentRoot)
```

Adding an empty `wwwroot` directory makes it work. But requiring an empty directory is pretty weird!

Of course, **I know that nearly all apps will actually want some static content in the real world**. I'm only filing this because having unexpected dependencies between ASP.NET Core features makes the framework feel less satisfying to use, because you're forced to follow a predefined path and can't slim down your app to only what feels truly necessary.

**Comment by javiercn** [comment]
@SteveSandersonMS this will likely be easy to fix, so if it's annoying in any way I'm supportive of fixing it.

**Comment by KennethHoff** [comment]
Another thing to consider is that Git does not keep empty folders, so this workaround of just creating an empty folder doesn't really work in a collaborative scenario, so you'd have to create a dummy file in the wwwroot directory as well.

**Comment by SteveSandersonMS** [comment]
@KennethHoff You probably know this but just for anyone else reading, Git has a built-in native solution for that: https://www.freecodecamp.org/news/what-is-gitkeep/

Of course, it's still inconvenient and would be better if it simply wasn't required.

**Comment by javiercn** [comment]
# Help Wanted

## Issue Summary

The issue is that the static web assets loader tries to create a file provider for the wwwroot folder, but doesn't check if the folder exists first. This causes an exception to be thrown when the folder doesn't exist.

This can likely happen because there is a discovery pattern associated with the wwwroot folder that gets added unconditionally. There are a couple of ways we can fix this:
* Update the SDK to avoid adding the discovery pattern if the folder doesn't exist [here](https://github.com/dotnet/sdk/blob/37989cd208869de31a934d9d336c3ff0eeb2e42b/src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.targets#L507-L516).
* Update the static web assets loader to check if the folder exists before trying to create a file provider for it.

## Potential Design

Ideally, the most correct fix is to not add the discovery pattern if the folder doesn't exist.

## Code References

https://github.com/dotnet/sdk/blob/main/src/StaticWebAssetsSdk/Targets/Microsoft.NET.Sdk.StaticWebAssets.targets#L507-L516

## Relevant Documentation

N/A

## Important Considerations

N/A

## Additional Notes
- If this is your first contribution to the repo, you may find it useful to learn [How to build the repo](/docs/BuildFromSource.md)
- Please note, that the changes will be considered for the vNext version of the framework by default. That is, after the change gets merged in main, it will be available only in the next preview release of the framework and will be shipped in the upcoming major release of the product.

**Comment by ElderJames** [comment]
I just found that this issue seems have been fixed.
