### ISSUE TITLE
Object disposed exception when deserializing an async enumerable in Blazor WASM

### ISSUE THREAD

**Issue by DavidVollmers** [dotnet/aspnetcore#51983]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The following code will inconsistently throw an `ObjectDisposedException` when run in a Blazor WASM environment:

```csharp
await using var stream = await content.ReadAsStreamAsync(cancellationToken);

var items = JsonSerializer.DeserializeAsyncEnumerable<T>(memoryStream, serializerOptions, cancellationToken);
await foreach (var item in items)
{
    yield return item!;
}
```

The thrown exception:
```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Http.BrowserHttpContent'.
   at System.Net.Http.HttpContent.CheckDisposed()
   at System.Net.Http.HttpContent.ReadAsStreamAsync(CancellationToken cancellationToken)
   at ...<...>d__0`1[[...]].MoveNext() in ....cs:line 0
```

Even when copying the whole stream (with flushing) to a memory stream and without disposing it (no `using`) this exception is still thrown.

This to me, seems like a bug in the `System.Net.Http.BrowserHttpContent.ReadAsStreamAsync` logic in web assembly.

### Expected Behavior

The stream shouldn't be disposed before the deserialization is finished.

### Steps To Reproduce

See above.

### Exceptions (if any)

See above.

### .NET Version

net7.0

**Comment by DavidVollmers** [comment]
Nevermind... the response object was disposed before the deserialization finished...
