### ISSUE TITLE
[.NET 8] Kestrel no longer starts after update to .NET 8, but throws exception around 'Kestrel.Core.Internal.Infrastructure.KestrelMetrics'

### ISSUE THREAD

**Issue by DierkDroth** [dotnet/aspnetcore#52085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a minimal Kestrel application (since I don't need all the ASP.NET stuff, but only a simple as possible replacement for HttpListener), which no longer starts after updating to .NET 8. The application worked fine with .NET 7.

Here is the exception:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=No service for type 'Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelMetrics' has been registered.
  Source=Microsoft.Extensions.DependencyInjection.Abstractions
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, HttpsConnectionAdapterOptions httpsOptions)
   at Unusual.Server.Server.<>c__DisplayClass24_0.<Main>b__14(ListenOptions options) in C:\Users\dierk\Documents\unusual-src\Unusual.Server\Server.cs:line 901
```
... and here is the relevant code
```
KestrelServerOptions serverOptions = new KestrelServerOptions();
serverOptions.ListenAnyIP(port, options =>
{
    options.KestrelServerOptions.ApplicationServices = new AppServices();
    options.UseHttps(new HttpsConnectionAdapterOptions { ServerCertificate = certificate });
});
```

### Expected Behavior

Kestrel should work as it did with .NET 7

### .NET Version

8.0.100

**Comment by Tratcher** [comment]
Please give a more complete code sample. How do you run the server after this?

`KestrelServerOptions` is not designed to be created like that, only configured via the UseKestrel callback.

**Comment by amcasey** [comment]
Reminiscent of #48956.  I'm guessing you're not using a builder, @DierkDroth?

**Comment by DierkDroth** [comment]
Thanks for your feedback @Tratcher @amcasey 

Thing is, I'm forced to use Kestrel since I can't use HttpListener with SSL certificate on an ARM64 Ubuntu ... so it has to be Kestrel - not my choice though...

So, I was looking for a simple as possible solution and came up with something along the lines of what @mark-cordell figured out [here](https://github.com/mark-cordell/bare-bones-kestrel-server) ... which does exactly match my requirements (= do away with all the ASP.NET overhead, but focus on handling HTTP(s) calls + weksocket calls) ... and which works perfectly with and now break with .NET 8.

Here is the relevant code:
```
					KestrelServerOptions serverOptions = new KestrelServerOptions();
					if (useSsl)
					{
						serverOptions.ListenAnyIP(port, options =>
						{
							options.KestrelServerOptions.ApplicationServices = new AppServices();
							options.UseHttps(new HttpsConnectionAdapterOptions { ServerCertificate = certificate });
						});
					}
					else
					{
						serverOptions.ListenAnyIP(port);
					}

					NullLoggerFactory		loggerFactory	= new NullLoggerFactory();
					using KestrelServer		server			= new KestrelServer(new OptionsWrapper<KestrelServerOptions>(serverOptions),
																					new SocketTransportFactory(new OptionsWrapper<SocketTransportOptions>(new SocketTransportOptions()), loggerFactory),
																					loggerFactory);

					await server.StartAsync(new Application(loggerFactory), CancellationToken.None);
					await Task.Delay(Timeout.Infinite);
					
	public class Application : IHttpApplication<Context>
	{
		private	readonly WebSocketMiddleware		webSocketMiddleware;

		public Application(ILoggerFactory loggerFactory)
		{
			webSocketMiddleware = new WebSocketMiddleware(ContinueRequestAsync, new OptionsWrapper<WebSocketOptions>(new WebSocketOptions()), loggerFactory);
		}

		private async Task ContinueRequestAsync(HttpContext context)
		{
			if (context.WebSockets.IsWebSocketRequest)
			{
					// do websocket stuff here
			}
			else
			{
					// handle the HTTP(s) calls here
			}
		}
```

**Comment by amcasey** [comment]
It sounds like you might be looking for [CreateSlimBuilder](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.webapplication.createslimbuilder?view=aspnetcore-8.0) or even [CreateEmptyBuilder](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.webapplication.createemptybuilder?view=aspnetcore-8.0).

**Comment by Tratcher** [comment]
You may be overestimating the fat.
```
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;

var port = 5001;
var useSsl = true;
var certificate = new X509Certificate2("cert.pfx");

var builder = WebApplication.CreateBuilder(args);
builder.WebHost.ConfigureKestrel(kestrel =>
{
    kestrel.ListenAnyIP(port, portOptions =>
    {
        if (useSsl)
        {
            portOptions.UseHttps(certificate);
        }
    });
});

var app = builder.Build();
app.UseWebSockets();

app.Run(context =>
{
    if (context.WebSockets.IsWebSocketRequest)
    {
        // do websocket stuff here
    }
    else
    {
        // handle the HTTP(s) calls here
    }
    return Task.CompletedTask;
});

app.Run();
```

**Comment by DierkDroth** [comment]
Excellent! Thanks @Tratcher @amcasey. You guys made my day! Looks like that's exactly what I was looking for.

Wished I would have found such a clear 'minimal' sample before...

**Comment by Tratcher** [comment]
Welcome. It's been an evolution to get to this point.
