### ISSUE TITLE
Quarantine Http2RequestTests.GET_RequestReturnsLargeData_GracefulShutdownDuringRequest_RequestGracefullyCompletes

### ISSUE THREAD

**Issue by amcasey** [dotnet/aspnetcore#52238]
## Failing Test(s)

- Http2RequestTests.GET_RequestReturnsLargeData_GracefulShutdownDuringRequest_RequestGracefullyCompletes

## Error Message

> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.

## Logs

<details>

```text
[0.001s] [TestLifetime] [Information] Starting test GET_RequestReturnsLargeData_GracefulShutdownDuringRequest_RequestGracefullyCompletes-False at 2022-04-06T01:12:55
[0.006s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting starting
[0.006s] [Microsoft.Hosting.Lifetime] [Information] Now listening on: http://127.0.0.1:55248
[0.006s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Debug] Loaded hosting startup assembly Interop.FunctionalTests
[0.007s] [Microsoft.Hosting.Lifetime] [Information] Application started. Press Ctrl+C to shut down.
[0.007s] [Microsoft.Hosting.Lifetime] [Information] Hosting environment: Production
[0.007s] [Microsoft.Hosting.Lifetime] [Information] Content root path: C:\h\w\A0B908F0\w\C31709CB\e\
[0.007s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting started
[0.007s] [Test] [Information] Waiting for request on server
[0.564s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMGNDA9QFTM1" accepted.
[0.564s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMGNDA9QFTM1" started.
[0.567s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending SETTINGS frame for stream ID 0 with length 18 and flags NONE.
[0.567s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0.
[0.568s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" received SETTINGS frame for stream ID 0 with length 12 and flags NONE.
[0.568s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending SETTINGS frame for stream ID 0 with length 0 and flags ACK.
[0.568s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" received WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0.
[0.568s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" received HEADERS frame for stream ID 1 with length 20 and flags END_STREAM, END_HEADERS.
[0.568s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request starting HTTP/2 GET http://127.0.0.1:55248/ - -
[0.569s] [Test] [Information] Stopping server
[0.569s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting stopping
[0.569s] [Microsoft.Hosting.Lifetime] [Information] Application is shutting down...
[0.569s] [Test] [Information] Server writing 500000 bytes response
[0.570s] [Test] [Information] Server advancing 500000 bytes response
[0.570s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending HEADERS frame for stream ID 1 with length 41 and flags END_HEADERS.
[0.570s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 16384 and flags NONE.
[0.570s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 16384 and flags NONE.
[0.570s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 16384 and flags NONE.
[0.570s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 16383 and flags NONE.
[0.570s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Debug] Connection id "0HMGNDA9QFTM1" is closing.
[0.570s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending GOAWAY frame for stream ID 0 with length 8 and flags 0x0.
[0.571s] [Test] [Information] Received 49152 bytes. Total 49152 bytes.
[0.571s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" received SETTINGS frame for stream ID 0 with length 0 and flags ACK.
[0.572s] [Test] [Information] Received 16383 bytes. Total 65535 bytes.
[0.572s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" received PING frame for stream ID 0 with length 8 and flags NONE.
[0.572s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending PING frame for stream ID 0 with length 8 and flags ACK.
[0.572s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" received WINDOW_UPDATE frame for stream ID 1 with length 4 and flags 0x0.
[0.572s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 16384 and flags NONE.
[0.572s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 16384 and flags NONE.
[0.572s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 16384 and flags NONE.
[0.572s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 16384 and flags NONE.
[0.572s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 16384 and flags NONE.
[0.573s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 16384 and flags NONE.
[0.573s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 16383 and flags NONE.
[0.593s] [Test] [Information] Received 49152 bytes. Total 114687 bytes.
[0.640s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" received WINDOW_UPDATE frame for stream ID 1 with length 4 and flags 0x0.
[0.640s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 16383 and flags NONE.
[0.642s] [Test] [Information] Received 65535 bytes. Total 180222 bytes.
[0.642s] [Test] [Information] Received 16383 bytes. Total 196605 bytes.
[0.642s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" received WINDOW_UPDATE frame for stream ID 1 with length 4 and flags 0x0.
[0.642s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 16384 and flags NONE.
[0.643s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 16384 and flags NONE.
[0.643s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 16384 and flags NONE.
[0.643s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 16384 and flags NONE.
[0.643s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 16384 and flags NONE.
[0.643s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 16384 and flags NONE.
[0.643s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 16384 and flags NONE.
[0.643s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 16384 and flags NONE.
[0.643s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 16384 and flags NONE.
[0.643s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 16384 and flags NONE.
[0.643s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 16382 and flags NONE.
[0.643s] [Test] [Information] Received 49152 bytes. Total 245757 bytes.
[0.643s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" received WINDOW_UPDATE frame for stream ID 1 with length 4 and flags 0x0.
[0.644s] [Test] [Information] Received 65536 bytes. Total 311293 bytes.
[0.644s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 16384 and flags NONE.
[0.644s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 16384 and flags NONE.
[0.644s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 16384 and flags NONE.
[0.644s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 16383 and flags NONE.
[0.645s] [Test] [Information] Received 65534 bytes. Total 376827 bytes.
[0.645s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" received WINDOW_UPDATE frame for stream ID 1 with length 4 and flags 0x0.
[0.645s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 16384 and flags NONE.
[0.645s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 16384 and flags NONE.
[0.645s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 16384 and flags NONE.
[0.645s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending DATA frame for stream ID 1 with length 8486 and flags END_STREAM.
[0.645s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Debug] Connection id "0HMGNDA9QFTM1" is closed. The last processed stream ID was 1.
[0.645s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "0HMGNDA9QFTM1" sending GOAWAY frame for stream ID 0 with length 8 and flags 0x0.
[0.648s] [Test] [Information] Received 49152 bytes. Total 425979 bytes.
[0.648s] [Microsoft.AspNetCore.Hosting.Diagnostics] [Information] Request finished HTTP/2 GET http://127.0.0.1:55248/ - - - 200 - - 79.4842ms
[0.648s] [Microsoft.AspNetCore.Server.Kestrel.Connections] [Debug] Connection id "0HMGNDA9QFTM1" stopped.
[0.648s] [Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets] [Debug] Connection id "0HMGNDA9QFTM1" sending FIN because: "The Socket transport's send loop completed gracefully."
[1.558s] [Microsoft.Extensions.Hosting.Internal.Host] [Debug] Hosting stopped
[1.576s] [Interop.FunctionalTests.Http2.Http2RequestTests] [Error] Test threw an exception.
System.IO.IOException: The request was aborted.
 ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ReceiveAsync(Socket socket, CancellationToken cancellationToken)
   at System.Net.Sockets.NetworkStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Net.Http.Http2Connection.ReadFrameAsync(Boolean initialFrame)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.InvokeContinuation(Action`1 continuation, Object state, Boolean forceAsync, Boolean requiresExecutionContextFlow)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs _)
   at System.Net.Sockets.SocketAsyncEventArgs.<>c.<.cctor>b__176_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading.ThreadPoolTypedWorkItemQueue`2.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryReadFromBuffer(Span`1 buffer, Boolean partOfSyncRead)
   at System.Net.Http.Http2Connection.Http2Stream.ReadDataAsync(Memory`1 buffer, HttpResponseMessage responseMessage, CancellationToken cancellationToken)
   at Interop.FunctionalTests.Http2.Http2RequestTests.StartLongRunningRequestAsync(ILogger logger, IHost host, HttpMessageInvoker client) in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/Http2/Http2RequestTests.cs:line 123
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 88
   at Interop.FunctionalTests.Http2.Http2RequestTests.GET_RequestReturnsLargeData_GracefulShutdownDuringRequest_RequestGracefullyCompletes(Boolean hasTrailers) in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/Http2/Http2RequestTests.cs:line 98
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
[1.607s] [TestLifetime] [Information] Finished test GET_RequestReturnsLargeData_GracefulShutdownDuringRequest_RequestGracefullyCompletes-False in 1.6057321s

```
</details>

## Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1701748&view=results

**Comment by amcasey** [comment]
Details in #41074

**Comment by amcasey** [comment]
Yikes, this has only a 73% pass rate.
