### ISSUE TITLE
ConnectionAbortedException ---> Reading is already in progress

### ISSUE THREAD

**Issue by Transis-Felipe** [dotnet/aspnetcore#52324]
Describe the bug
We're frequently getting the exception below in .net 8.0.

Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was aborted by the application.
       ---> System.InvalidOperationException: Reading is already in progress.
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.OnConsumeAsync()
         --- End of inner exception stack trace ---

Further technical details
ASP.NET Core 8.0
Kestrel on Windows Server 2019

**Comment by amcasey** [comment]
@Transis-Felipe From your description, it sounds like this behavior is new in 8.0.  Which version were you on before you upgraded?

**Comment by amcasey** [comment]
> One suggestion should be to implement TryMapGet to be called instead of app.MapGet on the server side.

Sorry, I didn't understand this suggestion.  Can you elaborate?

**Comment by amcasey** [comment]
The exception is from [here](https://github.com/dotnet/aspnetcore/blob/5b1ad1ee4934be7d587e50670524876763cd45eb/src/Servers/Kestrel/Core/src/Internal/Http/Http1ContentLengthMessageBody.cs#L281).

#33409 had a similar stack and was closed in favor of https://github.com/dotnet/runtime/issues/53914.  It would be interesting to know whether their setup sounds similar to what you're doing.

**Comment by amcasey** [comment]
The stack trace doesn't give us much to go on.  I'd say the next steps are probably to collect (and, ideally, share) more verbose logs and to review https://github.com/dotnet/runtime/issues/53914 (which is quite old) in case the problems described there sound similar to your scenario.

**Comment by Transis-Felipe** [comment]
> > One suggestion should be to implement TryMapGet to be called instead of app.MapGet on the server side.
> 
> Sorry, I didn't understand this suggestion. Can you elaborate?

Hi @amcasey ,

TryMapGet to not generate ReportApplicationError when there's an InvalidOperationException

**Comment by Transis-Felipe** [comment]
> @Transis-Felipe From your description, it sounds like this behavior is new in 8.0. Which version were you on before you upgraded?

Before .net 8 I was using .net 7, but the error was the same.

**Comment by amcasey** [comment]
@Transis-Felipe From https://github.com/dotnet/runtime/issues/53914, it sounds like there are corner cases where subtle buffering behavior can cause this error to be reported.  Have you reviewed that issue to see whether any of the practices describe there sound like what your app is doing?

Where are you seeing people talking about encountering this issue in .net core 3?  I haven't been able to find any reports other than the ones I linked above.

**Comment by Transis-Felipe** [comment]
> Where are you seeing people talking about encountering this issue in .net core 3? I haven't been able to find any reports other than the ones I linked above.

https://github.com/dotnet/aspnetcore/issues/17062

**Comment by amcasey** [comment]
> > Have you reviewed that issue to see whether any of the practices describe there sound like what your app is doing?
> 
> I don't have access to client apps that consumes this app.

A lot of the comments I noticed in that issue were about buffering on the server side, so I wouldn't have thought you'd need access to the client apps.  Unless you're saying you don't have a client that exercise your server to validate these things?

**Comment by amcasey** [comment]
Does that mean you're unable to debug the server or collect additional server logs?

**Comment by Transis-Felipe** [comment]
> Does that mean you're unable to debug the server or collect additional server logs?

I can't debug, but I can collect additional logs.

**Comment by amcasey** [comment]
I don't see any logs that directly track the `_isReading` state, but it would be interesting to see debug-level logs for an affected request.

**Comment by amcasey** [comment]
Do the problematic requests include `Expect: 100-continue` as in https://github.com/dotnet/runtime/issues/53914?

**Comment by Transis-Felipe** [comment]
> Do the problematic requests include `Expect: 100-continue` as in [dotnet/runtime#53914](https://github.com/dotnet/runtime/issues/53914)?

In the server side I can see this ? I don't have access to or how client side do the access.

**Comment by Transis-Felipe** [comment]
> I don't see any logs that directly track the `_isReading` state, but it would be interesting to see debug-level logs for an affected request.

How can I grab this ?

**Comment by amcasey** [comment]
I usually update my [appsettings.json](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-8.0#configure-logging), but there are a number of options, depending on your setup.

**Comment by Transis-Felipe** [comment]
> I usually update my [appsettings.json](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-8.0#configure-logging), but there are a number of options, depending on your setup.

Wow, changing appsettings to debug produces a lot of info...

![image](https://github.com/dotnet/aspnetcore/assets/4941173/25f9170f-e2da-4ad8-b7a1-006fa8c204f3)

Any chance to generate logs only for errors ?

**Comment by amcasey** [comment]
> > Do the problematic requests include `Expect: 100-continue` as in [dotnet/runtime#53914](https://github.com/dotnet/runtime/issues/53914)?
> 
> In the server side I can see this ? I don't have access to or how client side do the access.

Sorry, I missed this before.  The server can certainly dump request headers, but it makes the output _much_ more verbose.  We could get a pretty good idea from the response status codes though - are you seeing any 100s (i.e. on one of the "request finished" lines)?

**Comment by amcasey** [comment]
That's weird - I wouldn't expect the client to send another request on the same connection after the `FIN`.

**Comment by amcasey** [comment]
You'd have to enable connection logging or use something like wireshark to see what was actually in the bad request.  Also, this doesn't appear to have lead to the `fail` message from your original report?

**Comment by Transis-Felipe** [comment]
Sorry to ask you for this, but I'm not finding a way to redirect output to a file
I'm not finding a way using the web.config or appsettings.json.

**Comment by amcasey** [comment]
Unfortunately, I don't think there's built-in support for that - I usually just redirect stdout to a file.  There are third party extensions that give you more control, but there isn't a particular one I can recommend off the top of my head.

**Comment by j-hudecek** [comment]
Hi, we're seeing a similar issue on .net 6.0.25. Ubuntu 22, x64, Kestrel is behind Apache with http2. 

    Dec 22 12:33:57 h102 service[4714]: warn: Microsoft.AspNetCore.Server.Kestrel[0]
    Dec 22 12:33:57 h102 service[4714]:       Connection processing ended abnormally.
    Dec 22 12:33:57 h102 service[4714]:       System.InvalidOperationException: Reading is already in progress.
    Dec 22 12:33:57 h102 service[4714]:          at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_AlreadyReading()
    Dec 22 12:33:57 h102 service[4714]:          at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
    Dec 22 12:33:57 h102 service[4714]:          at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
    Dec 22 12:33:57 h102 service[4714]:          at System.IO.Pipelines.Pipe.DefaultPipeReader.ReadAsync(CancellationToken cancellationToken)
    Dec 22 12:33:57 h102 service[4714]:          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1Connection.BeginRead(ValueTask`1& awaitable)
    Dec 22 12:33:57 h102 service[4714]:          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
    Dec 22 12:33:57 h102 service[4714]:          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)

**Comment by amcasey** [comment]
@j-hudecek Did these [suggestions](https://github.com/dotnet/aspnetcore/issues/52324#issuecomment-1830545882) help at all?

**Comment by j-hudecek** [comment]
Do you mean setting higher Expect100ContinueTimeout? I'll try it. We haven't seen the error since, though, so it will take a while to know if it helped
