### ISSUE TITLE
Add HttpConnectAttribute

### ISSUE THREAD

**Issue by voroninp** [dotnet/aspnetcore#52380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

There's a [closed ticket](https://github.com/dotnet/aspnetcore/issues/43501).

You offered a workaround with `[Route]` attribute. But... Add Swagger docs and get an exception for free:
```
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Ambiguous HTTP method for action - Api.Controllers.NotificationsController.GetExecutionEnvironmentStatusUpdates (Api). Actions require an explicit HttpMethod binding for Swagger/OpenAPI 3.0
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerDocumentWithoutFilters(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwaggerAsync(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

Wee need this attribute.

### Describe the solution you'd like

Extend the set of `[HttpXxx]` attributes.

**Comment by voroninp** [comment]
This is not a PR :-)

**Comment by captainsafia** [comment]
@voroninp You'll probably want to exclude the endpoint using the `CONNECT` method since OpenAPI does not support `CONNECT` method as a supported parameter.

We decided against extending the set of `HttpXXX` attributes in the framework given that there were other viable alternatives.

**Comment by voroninp** [comment]
>  since OpenAPI does not support CONNECT method as a supported parameter.

IMO, this is a defficiency of OpenApi. As I understand the primary purpose of `HttpXxx` attributes is routing. Am I wrong?

**Comment by martincostello** [comment]
Even if the attribute were added, Swashbuckle would still not work because OpenAPI doesn't support it, so you'd have to exclude it from the API definition anyway.

You can trivially define `[HttpConnect]` for routing usage yourself if you so wish:

```csharp
public class HttpConnectAttribute : HttpMethodAttribute
{
    private static readonly IEnumerable<string> _supportedMethods = ["CONNECT"];

    public HttpConnectAttribute()
        : base(_supportedMethods)
    {
    }

    public HttpConnectAttribute([StringSyntax("Route")] string template)
        : base(_supportedMethods, template)
    {
    }
}
```

**Comment by voroninp** [comment]
Actually I did, you remember it, @martincostello  =) And indeed, Swashbuckle [was not happy](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2740).
