### ISSUE TITLE
Quarantine POST_MultipleRequests_PooledStreamAndHeaders

### ISSUE THREAD

**Issue by amcasey** [dotnet/aspnetcore#52573]
## Failing Test(s)

- Interop.FunctionalTests.Http3.Http3RequestTests.POST_MultipleRequests_PooledStreamAndHeaders(protocol: Http2)

## Error Message

```text
Assert.Same() Failure
Expected: text/plain
Actual:   text/plain
```

Assuming the logs don't have trailing whitespace trimmed, the values appear to be identical.

## Stacktrace

<details>

```text
   at Interop.FunctionalTests.Http3.Http3RequestTests.POST_MultipleRequests_PooledStreamAndHeaders(HttpProtocols protocol) in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/Http3/Http3RequestTests.cs:line 361
```
</details>

## Logs

<details>

```text
2023-11-22T02:41:46.6934705Z [xUnit.net 00:00:17.25]     Interop.FunctionalTests.Http3.Http3RequestTests.POST_MultipleRequests_PooledStreamAndHeaders(protocol: Http2) [FAIL]
2023-11-22T02:41:46.7074590Z [xUnit.net 00:00:17.26]       Assert.Same() Failure
2023-11-22T02:41:46.7074824Z [xUnit.net 00:00:17.26]       Expected: text/plain
2023-11-22T02:41:46.7075289Z [xUnit.net 00:00:17.26]       Actual:   text/plain
2023-11-22T02:41:46.7075764Z [xUnit.net 00:00:17.26]       Stack Trace:
2023-11-22T02:41:46.7076191Z [xUnit.net 00:00:17.26]         /_/src/Servers/Kestrel/test/Interop.FunctionalTests/Http3/Http3RequestTests.cs(361,0): at Interop.FunctionalTests.Http3.Http3RequestTests.POST_MultipleRequests_PooledStreamAndHeaders(HttpProtocols protocol)
2023-11-22T02:41:46.7076653Z [xUnit.net 00:00:17.26]         --- End of stack trace from previous location ---
2023-11-22T02:41:46.7603205Z [xUnit.net 00:00:17.26]       Output:
2023-11-22T02:41:46.7603357Z [xUnit.net 00:00:17.27]         | [0.003s] TestLifetime Information: Starting test POST_MultipleRequests_PooledStreamAndHeaders-Http2 at 2023-11-22T02:41:46
2023-11-22T02:41:46.7603393Z [xUnit.net 00:00:17.27]         | [0.004s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting starting
2023-11-22T02:41:46.7603425Z [xUnit.net 00:00:17.27]         | [0.014s] Microsoft.Hosting.Lifetime Information: Now listening on: https://127.0.0.1:35269
2023-11-22T02:41:46.7603461Z [xUnit.net 00:00:17.27]         | [0.014s] Microsoft.AspNetCore.Hosting.Diagnostics Debug: Loaded hosting startup assembly Interop.FunctionalTests
2023-11-22T02:41:46.7603488Z [xUnit.net 00:00:17.27]         | [0.014s] Microsoft.Hosting.Lifetime Information: Application started. Press Ctrl+C to shut down.
2023-11-22T02:41:46.7603643Z [xUnit.net 00:00:17.27]         | [0.014s] Microsoft.Hosting.Lifetime Information: Hosting environment: Production
2023-11-22T02:41:46.7603676Z [xUnit.net 00:00:17.27]         | [0.014s] Microsoft.Hosting.Lifetime Information: Content root path: /datadisks/disk1/work/A8560912/w/C0DC0A06/e/
2023-11-22T02:41:46.7603848Z [xUnit.net 00:00:17.27]         | [0.014s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting started
2023-11-22T02:41:46.7603883Z [xUnit.net 00:00:17.27]         | [0.015s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMVB0I47UCSD" accepted.
2023-11-22T02:41:46.7603915Z [xUnit.net 00:00:17.27]         | [0.015s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMVB0I47UCSD" started.
2023-11-22T02:41:46.7604014Z [xUnit.net 00:00:17.27]         | [0.018s] Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware Debug: Connection 0HMVB0I47UCSD established using the following protocol: Tls13
2023-11-22T02:41:46.7604041Z [xUnit.net 00:00:17.27]         | [0.018s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMVB0I47UCSD" sending SETTINGS frame for stream ID 0 with length 24 and flags NONE.
2023-11-22T02:41:46.7604065Z [xUnit.net 00:00:17.27]         | [0.018s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMVB0I47UCSD" sending WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0.
2023-11-22T02:41:46.7604412Z [xUnit.net 00:00:17.27]         | [0.018s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMVB0I47UCSD" received SETTINGS frame for stream ID 0 with length 12 and flags NONE.
2023-11-22T02:41:46.7604452Z [xUnit.net 00:00:17.27]         | [0.018s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMVB0I47UCSD" sending SETTINGS frame for stream ID 0 with length 0 and flags ACK.
2023-11-22T02:41:46.7604485Z [xUnit.net 00:00:17.27]         | [0.018s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMVB0I47UCSD" received WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0.
2023-11-22T02:41:46.7604518Z [xUnit.net 00:00:17.27]         | [0.018s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMVB0I47UCSD" received HEADERS frame for stream ID 1 with length 33 and flags END_HEADERS.
2023-11-22T02:41:46.7604549Z [xUnit.net 00:00:17.27]         | [0.019s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMVB0I47UCSD" received SETTINGS frame for stream ID 0 with length 0 and flags ACK.
2023-11-22T02:41:46.7604833Z [xUnit.net 00:00:17.27]         | [0.019s] Microsoft.AspNetCore.Hosting.Diagnostics Information: Request starting HTTP/2 POST https://127.0.0.1:35269/ - text/plain -
2023-11-22T02:41:46.7604867Z [xUnit.net 00:00:17.27]         | [0.019s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HMVB0I47UCSD", Request id "0HMVB0I47UCSD:00000001": started reading request body.
2023-11-22T02:41:46.7604898Z [xUnit.net 00:00:17.27]         | [0.020s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMVB0I47UCSD" received DATA frame for stream ID 1 with length 3 and flags NONE.
2023-11-22T02:41:46.7800350Z [xUnit.net 00:00:17.27]         | [0.020s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMVB0I47UCSD" received DATA frame for stream ID 1 with length 0 and flags END_STREAM.
2023-11-22T02:41:46.7800489Z [xUnit.net 00:00:17.27]         | [0.020s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HMVB0I47UCSD", Request id "0HMVB0I47UCSD:00000001": done reading request body.
2023-11-22T02:41:46.7800523Z [xUnit.net 00:00:17.27]         | [0.021s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMVB0I47UCSD" sending HEADERS frame for stream ID 1 with length 41 and flags END_HEADERS.
2023-11-22T02:41:46.7800685Z [xUnit.net 00:00:17.27]         | [0.021s] Microsoft.AspNetCore.Hosting.Diagnostics Information: Request finished HTTP/2 POST https://127.0.0.1:35269/ - 200 - - 2.5621ms
2023-11-22T02:41:46.7800721Z [xUnit.net 00:00:17.27]         | [0.021s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMVB0I47UCSD" sending DATA frame for stream ID 1 with length 3 and flags END_STREAM.
2023-11-22T02:41:46.7806998Z [xUnit.net 00:00:17.27]         | [0.022s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMVB0I47UCSD" received PING frame for stream ID 0 with length 8 and flags NONE.
2023-11-22T02:41:46.7807994Z [xUnit.net 00:00:17.27]         | [0.022s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMVB0I47UCSD" sending PING frame for stream ID 0 with length 8 and flags ACK.
2023-11-22T02:41:46.7808526Z [xUnit.net 00:00:17.27]         | [0.022s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMVB0I47UCSD" received HEADERS frame for stream ID 3 with length 33 and flags END_HEADERS.
2023-11-22T02:41:46.7814622Z [xUnit.net 00:00:17.27]         | [0.022s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMVB0I47UCSD" received DATA frame for stream ID 3 with length 3 and flags NONE.
2023-11-22T02:41:46.7815180Z [xUnit.net 00:00:17.27]         | [0.023s] Microsoft.AspNetCore.Hosting.Diagnostics Information: Request starting HTTP/2 POST https://127.0.0.1:35269/ - text/plain -
2023-11-22T02:41:46.7822467Z [xUnit.net 00:00:17.27]         | [0.023s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMVB0I47UCSD" received DATA frame for stream ID 3 with length 0 and flags END_STREAM.
2023-11-22T02:41:46.7823558Z [xUnit.net 00:00:17.27]         | [0.023s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HMVB0I47UCSD", Request id "0HMVB0I47UCSD:00000003": started reading request body.
2023-11-22T02:41:46.7995552Z [xUnit.net 00:00:17.27]         | [0.023s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HMVB0I47UCSD", Request id "0HMVB0I47UCSD:00000003": done reading request body.
2023-11-22T02:41:46.8002779Z [xUnit.net 00:00:17.27]         | [0.023s] Microsoft.AspNetCore.Hosting.Diagnostics Information: Request finished HTTP/2 POST https://127.0.0.1:35269/ - 200 - - 0.2178ms
2023-11-22T02:41:46.8003320Z [xUnit.net 00:00:17.27]         | [0.023s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMVB0I47UCSD" sending HEADERS frame for stream ID 3 with length 3 and flags END_HEADERS.
2023-11-22T02:41:46.8014220Z [xUnit.net 00:00:17.27]         | [0.023s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMVB0I47UCSD" sending DATA frame for stream ID 3 with length 3 and flags END_STREAM.
2023-11-22T02:41:46.8014687Z [xUnit.net 00:00:17.27]         | [0.024s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HMVB0I47UCSD" received FIN.
2023-11-22T02:41:46.8020738Z [xUnit.net 00:00:17.27]         | [0.024s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMVB0I47UCSD" received PING frame for stream ID 0 with length 8 and flags NONE.
2023-11-22T02:41:46.8062791Z [xUnit.net 00:00:17.27]         | [0.024s] Microsoft.AspNetCore.Server.Kestrel.Http2 Debug: Connection id "0HMVB0I47UCSD" is closed. The last processed stream ID was 3.
2023-11-22T02:41:46.8062900Z [xUnit.net 00:00:17.27]         | [0.024s] Microsoft.AspNetCore.Server.Kestrel.Http2 Trace: Connection id "0HMVB0I47UCSD" sending PING frame for stream ID 0 with length 8 and flags ACK.
2023-11-22T02:41:46.8062933Z [xUnit.net 00:00:17.27]         | [0.024s] Microsoft.AspNetCore.Server.Kestrel.Http2 Debug: The connection queue processing loop for 0HMVB0I47UCSD completed.
2023-11-22T02:41:46.8062964Z [xUnit.net 00:00:17.27]         | [0.025s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Some connections failed to close gracefully during server shutdown.
2023-11-22T02:41:46.8062991Z [xUnit.net 00:00:17.27]         | [0.025s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HMVB0I47UCSD" sending RST because: "The connection was aborted because the server is shutting down and request processing didn't complete within the time specified by HostOptions.ShutdownTimeout."
2023-11-22T02:41:46.8063100Z [xUnit.net 00:00:17.27]         | [0.025s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HMVB0I47UCSD" stopped.
2023-11-22T02:41:46.8063132Z [xUnit.net 00:00:17.27]         | [0.031s] Interop.FunctionalTests.Http3.Http3RequestTests Error: Test threw an exception.
2023-11-22T02:41:46.8202840Z [xUnit.net 00:00:17.27]         | Xunit.Sdk.SameException: Assert.Same() Failure
2023-11-22T02:41:46.8203008Z [xUnit.net 00:00:17.27]         | Expected: text/plain
2023-11-22T02:41:46.8208247Z [xUnit.net 00:00:17.27]         | Actual:   text/plain
2023-11-22T02:41:46.8214720Z [xUnit.net 00:00:17.27]         |    at Xunit.Assert.Same(Object expected, Object actual) in /_/src/xunit.assert/Asserts/IdentityAsserts.cs:line 45
2023-11-22T02:41:46.8244300Z [xUnit.net 00:00:17.27]         |    at Interop.FunctionalTests.Http3.Http3RequestTests.POST_MultipleRequests_PooledStreamAndHeaders(HttpProtocols protocol) in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/Http3/Http3RequestTests.cs:line 361
2023-11-22T02:41:46.8248595Z [xUnit.net 00:00:17.27]         |    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 264
2023-11-22T02:41:46.8250970Z [xUnit.net 00:00:17.27]         | --- End of stack trace from previous location ---
2023-11-22T02:41:46.8253477Z [xUnit.net 00:00:17.27]         |    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
2023-11-22T02:41:46.8255854Z [xUnit.net 00:00:17.28]         |    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
2023-11-22T02:41:46.8258288Z [xUnit.net 00:00:17.28]         | [0.032s] TestLifetime Information: Finished test POST_MultipleRequests_PooledStreamAndHeaders-Http2 in 0.0290643s
```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=477691

**Comment by BrennanConroy** [comment]
> Assuming the logs don't have trailing whitespace trimmed, the values appear to be identical.

It's using `Assert.Same` which means it's checking for the objects to be the same, not checking the 
values.

**Comment by amcasey** [comment]
> > Assuming the logs don't have trailing whitespace trimmed, the values appear to be identical.
> 
> It's using `Assert.Same` which means it's checking for the objects to be the same, not checking the values.

Yep, and failing to be Equal is one way they could fail to be Same.

**Comment by amcasey** [comment]
Note that http3 is waiting for pooling to complete, whereas http2 is not.  Presumably, this explains the difference in their failure rates.
