### ISSUE TITLE
After update from .net6 to .net8 - first time CheckPasswordAsync will cause an exception if user is loaded with AsNoTracking

### ISSUE THREAD

**Issue by tmksoft** [dotnet/aspnetcore#52602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have an existing application that use Microsoft Identity and .net6. Then I updated it to .net8.
When testing the password for a login using UserManager.CheckPasswordAsync(user, pwd) an exception is thrown IF the user was loaded using AsNoTracking:

System.InvalidOperationException: The instance of entity type 'AdminUser' cannot be tracked because another instance with the key value '{Id: 4a5fbbce-5059-4268-aa30-22edfe3fff20}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.

Apparently the reason for this is that I loaded my user directly from the DbContext using AsNoTracking.
Removing the AsNoTracking when loading the user, the problem goes away.

Looking at the full stacktrace it can be seen that it happens when it is doing an Attach of the User.

When debugging into the UserManager code I can see that it is because the PasswordHasher returns PasswordVerificationResult.SuccessRehashNeeded.

This probably only happens the first time the user is logging in to the system, after it is updated from .net6 to .net8.

### Expected Behavior

It should not throw an exception.

### Steps To Reproduce

Instead of setting up a full .net6 project and doing an update to .net8 - do the following:

1. Create a project based on .net8 and utilizes Microsoft.AspNetCore.Identity
2. Load the User entity from the DbContext and use AsNoTracking when loading.
3. Use this entity to test the password using UserManager.CheckPasswordAsync
4. Make sure that the PasswordManager returns PasswordVerificationResult.SuccessRehashNeeded
5. When the UpdateUserAsync underneath is invoked it will cause an exception.

Removing the AsNoTracking when loading the user, an exception is thrown.

### Exceptions (if any)

System.InvalidOperationException: The instance of entity type 'AdminUser' cannot be tracked because another instance with the key value '{Id: 4a5fbbce-5059-4268-aa30-22edfe3fff20}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NullableKeyIdentityMap`1.Add(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey, Nullable`1 fallbackState)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at Microsoft.EntityFrameworkCore.DbContext.Attach[TEntity](TEntity entity)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.UpdateAsync(TUser user, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.UpdateUserAsync(TUser user)
   at Microsoft.AspNetCore.Identity.UserManager`1.CheckPasswordAsync(TUser user, String password)

### .NET Version

.net8

**Comment by MariovanZeist** [comment]
Hi @tmksoft.
I am guessing that you see this issue now because internally the PasswordHashing mechanism has changed., and when a user logs in for the first time after the upgrade, the ``CheckPasswordAsync`` detects that it needs a rehash, and wants to update the database with the new passwordHash.

But the problem is not that change per se,  but that you are now running into a standard EFCore issue. 

For example, the following code will give the same exception:
```cs
  using var ctx = new ApplicationDbContext();
  var u1 = ctx.Users.Where(u => u.Id == currentUserId).First();
  var u2 = ctx.Users.Where(u => u.Id == currentUserId).AsNoTracking().First();
  ctx.Attach(u2);    //<- this will raise the same exception and this is whats happening inside the CheckPasswordAsync function
```

It happens when EFCore encounters two objects representing the same entity (user in this case).

What is happening in your case is that before or after you read the user the ``UserManager`` has also read the current user from the database, and is tracking that instance.

When you load the user without tracking, you end up with 2 objects representing the same user, 
You then call the ``CheckPasswordAsync`` function which wants to update the database because of the Hash change and you will see the exception.

I recommend using the ``GetUserAsync(currentUserId)`` function on the ``UserManager`` instead of loading the user yourself. In that case, you won't run into the above issue, as you will be using the same user object as the ``UserManager`` is tracking.

**Comment by tmksoft** [comment]
Hi MariovanZeist, thank you for your answer.

I will do as you suggest.

Regards
Thomas
