### ISSUE TITLE
Quarantine HelixPlatform_QuicListenerIsSupported

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/aspnetcore#52623]
## Failing Test(s)

Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Tests.WebHostTests.HelixPlatform_QuicListenerIsSupported

## Error Message

```text
QuicListener.IsSupported should be true.
Expected: True
Actual:   False
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Tests.WebHostTests.HelixPlatform_QuicListenerIsSupported() in /_/src/Servers/Kestrel/Transport.Quic/test/WebHostTests.cs:line 34
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```
</details>

## Logs

<details>

```text
[0.021s] [TestLifetime] [Information] Starting test HelixPlatform_QuicListenerIsSupported at 2023-12-07T00:39:24
[0.028s] [Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Tests.WebHostTests] [Error] Test threw an exception.
Xunit.Sdk.TrueException: QuicListener.IsSupported should be true.
Expected: True
Actual:   False
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/xunit.assert/Asserts/BooleanAsserts.cs:line 132
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/xunit.assert/Asserts/BooleanAsserts.cs:line 116
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Tests.WebHostTests.HelixPlatform_QuicListenerIsSupported() in /_/src/Servers/Kestrel/Transport.Quic/test/WebHostTests.cs:line 34
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
[0.030s] [TestLifetime] [Information] Finished test HelixPlatform_QuicListenerIsSupported in 0.0144296s
```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=491173

Note that the current pass rate for this test is only 80% - it's failed on `main` 22 times recently.

**Comment by JamesNK** [comment]
By the way, I created an issue in the dotnet/runtime repo: https://github.com/dotnet/runtime/issues/95771.

**Comment by BrennanConroy** [comment]
> The issue mentions the test is flaky.

The issue creator also didn't realize the test only failed on a single OS... so I wouldn't 100% trust what they typed. If you look at the Helix test run, it hasn't passed since the test was un-skipped.

**Comment by amcasey** [comment]
Yeah, I don't see how this could be flaky.  I guess we just have to skip one OS.

**Comment by amcasey** [comment]
Re-skipping (#52674) and re-opening #46616.
