### ISSUE TITLE
Blazor Server UploadFile Throws "System.InvalidOperationException: Reading is not allowed after reader was completed."

### ISSUE THREAD

**Issue by J3ster1337** [dotnet/aspnetcore#52723]
### Describe the bug

I use Blazor Server .NET 7.0. 
Some of the users have difficulties uploading files (when I myself don't: I've uploaded over 1000 files at this point and never had an issue). After uploading some amount of files, upload silently stops, they even can click on the InputFile again, pick new files, and the upload will start again (and then stop by the same reason). Sometimes bug happens after 20 uploads, sometimes after 8, sometimes never, the amount is random. 
In the end, I managed to get their chrome console and there is `System.InvalidOperationException: Reading is not allowed after reader was completed.` error. 
All that time, there was no logs on the server (probably because of my appsettings?).
For the most time, files is around 10MB.
Deployed on Ubuntu with Nginx.
Websocked connection is established, even when the error occurs.
I had an idea that it's somehow connected to the MacBook usage, but one Windows user told that he has the same behaviour.

### Code I use:

```
<InputFile OnChange="UploadFiles" multiple accept=".jpg,.jpeg" />

@code {
  async Task UploadFiles(InputFileChangeEventArgs e)
  {
	  try
	  {
		  foreach (var file in e.GetMultipleFiles(1000))
		  {
			  string newNameAndExtension = UploadTools.CreateUniqueFileNameAndExtension(Path.GetExtension(file.Name), directoryForFiles.FullName);
			  await using MemoryStream stream = new();
			  await file.OpenReadStream(1024 * 1024 * 1024).CopyToAsync(stream);
			  stream.Position = 0;
			  UploadTools.SavePhotoFirstTime(stream, directoryForFiles, newNameAndExtension);
			  stream.Position = 0;
			  UploadTools.SavePhotoSecondTime(stream, directoryForPreviews, newNameAndExtension);
			  DatabaseContext.Add(new Photo(newNameAndExtension));
			  DatabaseContext.SaveChanges();
			  StateHasChanged();
		  }
	  }
	  catch (Exception ex)
          {
	  	  Console.WriteLine(ex.Message);
	  	  Console.WriteLine(ex.StackTrace);
	  }
  }
}
```

### Exception

```
Reading is not allowed after reader was completed.                                                                                          
  at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoReadingAllowed()                                                     
  at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)                                                                           
  at System.IO.Pipelines.PipeReaderStream.ReadAsyncInternal(Memory`1 buffer, CancellationToken cancellationToken)                          
  at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSDataStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)    
  at Microsoft.AspNetCore.Components.Forms.BrowserFileStream.CopyFileDataIntoBuffer(Memory`1 destination, CancellationToken cancellationTo>
  at Microsoft.AspNetCore.Components.Forms.BrowserFileStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)               
  at System.IO.Stream.<CopyToAsync>g__Core|27_0(Stream source, Stream destination, Int32 bufferSize, CancellationToken cancellationToken)  
  at PhotoSite.Pages.Work.Photographer.SessionUpload.UploadFiles(InputFileChangeEventArgs e)                                               
  at PhotoSite.Pages.Work.Photographer.SessionUpload.UploadFiles(InputFileChangeEventArgs e)  
```

If there is any more information that is needed please feel free to ask.

**Comment by J3ster1337** [comment]
I had found the workaround - add this to the `UploadFiles` function:

Outside the function
`CancellationTokenSource cts;`

At the very start
``` 
if (cts != null)
{
	cts.Cancel();
}
cts = new CancellationTokenSource();
```

In the catch 
``` 
if (!(ex is OperationCanceledException))
{
	process = UploadFiles(e);
	await process;
}
```

It will still throw the exception, but will start the upload again with the same files.

**Comment by A9G-Data-Droid** [comment]
I am seeing the same kind of error in a .NET8 Blazor Server App. The test file I am using is around 170MB and it fails every time.

CODE EXAMPLE:
```c#
const int kb = 1024;
const int mb = 1024 * kb;
const long gb = 1024 * mb;
string destinationFullPath = Path.Combine(savePath, inputFile.Name);

byte[] buffer = System.Buffers.ArrayPool<byte>.Shared.Rent(mb);
try
{
    await using FileStream destination = new(destinationFullPath, FileMode.Create, FileAccess.ReadWrite, FileShare.None,  mb, FileOptions.Asynchronous);
    await using Stream readStream = inputFile.OpenReadStream(2 * gb);

    long totalBytesRead = 0;
    long fileSize = inputFile.Size;
    while (readStream.CanRead)
    {
        int bytesRead = await readStream.ReadAsync(buffer.AsMemory(0, mb));
        if (bytesRead <= 0) break;

        totalBytesRead += bytesRead;
        int newProgress = (int)(100 * totalBytesRead / fileSize);

        await destination.WriteAsync(buffer.AsMemory(0, bytesRead));

        if (newProgress != ProgressValue)
        {
            ProgressValue = newProgress;

            // Fire the event of OnProgress to notify the client about progress so far
            OnProgress?.Invoke(newProgress);
        }
    }

    logger.Info($"Downloaded file from user to: {destinationFullPath}");
}
catch (Exception ex)
{
    logger.Error(ex, $"Failure saving file submitted by user to: {destinationFullPath}");
}            
finally
{
    System.Buffers.ArrayPool<byte>.Shared.Return(buffer);
}
```

ERROR EXAMPLE:

>    Reading is not allowed after reader was completed.
at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_NoReadingAllowed()
   at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
   at System.IO.Pipelines.PipeReaderStream.<ReadAsyncInternal>d__30.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSDataStream.<ReadAsync>d__36.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Components.Forms.BrowserFileStream.<CopyFileDataIntoBuffer>d__30.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Components.Forms.BrowserFileStream.<ReadAsync>d__28.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()

**Comment by A9G-Data-Droid** [comment]
I believe this issue is a duplicate of https://github.com/dotnet/aspnetcore/issues/53951

Which is related to https://github.com/dotnet/aspnetcore/issues/47301

The workaround is to find your SignalR hub options and change `MaximumParallelInvocationsPerClient` to `1`. If you actually need support multiple SignalR invocations then you can't also use `InputFile` to upload large files. 

These things should be decoupled. SignalR settings should not break file transfers and vice versa.

WORKAROUND:
```
.AddHubOptions(options =>
{
    options.MaximumParallelInvocationsPerClient = 1;
});
```

**Comment by javiercn** [comment]
@J3ster1337 if you are still running into issues with a currently supported version, please let us know.

@A9G-Data-Droid The advice https://github.com/dotnet/aspnetcore/issues/47301 is not fully vetted I think and might cause other problems. 

Changing the `MaximumParallelInvocationsPerClient` is not something that we thoroughly test against or that we would consider supported.

We are going to use the other mentioned issue to track any improvements/fixes in this area.
