### ISSUE TITLE
Quarantine RequestHeaderStringReuse_MultipleStreams_KnownHeaderClearedIfNotReused

### ISSUE THREAD

**Issue by amcasey** [dotnet/aspnetcore#52739]
## Failing Test(s)

- Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2ConnectionTests.RequestHeaderStringReuse_MultipleStreams_KnownHeaderClearedIfNotReused

## Error Message

```text
Assert.Equal() Failure
Expected: 1
Actual:   0
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2ConnectionTests.RequestHeaderStringReuse_MultipleStreams_KnownHeaderClearedIfNotReused() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2ConnectionTests.cs:line 269
```
</details>

## Logs

<details>

```text
[0.005s] [TestLifetime] [Information] Starting test RequestHeaderStringReuse_MultipleStreams_KnownHeaderClearedIfNotReused at 2023-12-11T09:35:42
[0.007s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "TestConnectionId" sending SETTINGS frame for stream ID 0 with length 18 and flags NONE.
[0.007s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "TestConnectionId" sending WINDOW_UPDATE frame for stream ID 0 with length 4 and flags 0x0.
[0.007s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "TestConnectionId" received SETTINGS frame for stream ID 0 with length 0 and flags NONE.
[0.007s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "TestConnectionId" sending SETTINGS frame for stream ID 0 with length 0 and flags ACK.
[0.007s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "TestConnectionId" received HEADERS frame for stream ID 1 with length 97 and flags END_STREAM, END_HEADERS.
[0.007s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "TestConnectionId" sending HEADERS frame for stream ID 1 with length 36 and flags END_STREAM, END_HEADERS.
[0.039s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "TestConnectionId" received HEADERS frame for stream ID 3 with length 4 and flags END_STREAM, END_HEADERS.
[0.040s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "TestConnectionId" sending HEADERS frame for stream ID 3 with length 6 and flags END_STREAM, END_HEADERS.
[0.083s] [Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2ConnectionTests] [Error] Test threw an exception.
Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 1
Actual:   0
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\EqualityAsserts.cs:line 40
   at Xunit.Assert.Equal[T](T expected, T actual) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\EqualityAsserts.cs:line 24
   at Microsoft.AspNetCore.Server.Kestrel.Core.Tests.Http2ConnectionTests.RequestHeaderStringReuse_MultipleStreams_KnownHeaderClearedIfNotReused() in /_/src/Servers/Kestrel/test/InMemory.FunctionalTests/Http2/Http2ConnectionTests.cs:line 269
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
[0.083s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Debug] Connection id "TestConnectionId" is closed. The last processed stream ID was 3.
[0.084s] [Microsoft.AspNetCore.Server.Kestrel.Http2] [Verbose] Connection id "TestConnectionId" sending GOAWAY frame for stream ID 0 with length 8 and flags 0x0.
[0.095s] [TestLifetime] [Information] Finished test RequestHeaderStringReuse_MultipleStreams_KnownHeaderClearedIfNotReused in 0.0879718s
```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=495050

**Comment by amcasey** [comment]
The test triggers a tick to cause the effect it wants.  I'm guessing there's no guarantee that the tick handler has completed by the time the assert runs.
