### ISSUE TITLE
Blazor 'System.Reflection.AmbiguousMatchException' on .NET 8

### ISSUE THREAD

**Issue by thanuja89** [dotnet/aspnetcore#52755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When we update our blazor webassembly app, we noticed that we are getting "System.Reflection.AmbiguousMatchException: Ambiguous match found for" for properties if the code blocks (code-behind) contained two properties with the similar names which differs in case only (for eg: Model and model).

### Expected Behavior

No error thould be thrown and the correct property should be used.

### Steps To Reproduce

This is a demo of the bug. Go to counter page and you'll get an error.

https://github.com/thanuja89/BlazorBugRepo

### Exceptions (if any)

System.Reflection.AmbiguousMatchException: Ambiguous match found for 'BlazorAppBug.Client.Pages.Counter ModelModel Model'.
   at System.RuntimeType.GetField(String name, BindingFlags bindingAttr)
   at System.Linq.Expressions.Expression.PropertyOrField(Expression expression, String propertyOrFieldName)
   at Microsoft.AspNetCore.Components.Forms.FieldIdentifier.<GetModelFromMemberAccess>g__CreateAccessor|14_0(ValueTuple`2 arg)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.ValueTuple`2[[System.Type, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Func`2[[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrAdd(ValueTuple`2 key, Func`2 valueFactory)
   at Microsoft.AspNetCore.Components.Forms.FieldIdentifier.GetModelFromMemberAccess(MemberExpression member, ConcurrentDictionary`2 cache)
   at Microsoft.AspNetCore.Components.Forms.FieldIdentifier.ParseAccessor[String](Expression`1 accessor, Object& model, String& fieldName)
   at Microsoft.AspNetCore.Components.Forms.FieldIdentifier.Create[String](Expression`1 accessor)
   at Microsoft.AspNetCore.Components.Forms.InputBase`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Ambiguous match found for 'BlazorAppBug.Client.Pages.Counter ModelModel Model'.
System.Reflection.AmbiguousMatchException: Ambiguous match found for 'BlazorAppBug.Client.Pages.Counter ModelModel Model'.
   at System.RuntimeType.GetField(String name, BindingFlags bindingAttr)
   at System.Linq.Expressions.Expression.PropertyOrField(Expression expression, String propertyOrFieldName)
   at Microsoft.AspNetCore.Components.Forms.FieldIdentifier.<GetModelFromMemberAccess>g__CreateAccessor|14_0(ValueTuple`2 arg)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.ValueTuple`2[[System.Type, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Func`2[[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrAdd(ValueTuple`2 key, Func`2 valueFactory)
   at Microsoft.AspNetCore.Components.Forms.FieldIdentifier.GetModelFromMemberAccess(MemberExpression member, ConcurrentDictionary`2 cache)
   at Microsoft.AspNetCore.Components.Forms.FieldIdentifier.ParseAccessor[String](Expression`1 accessor, Object& model, String& fieldName)
   at Microsoft.AspNetCore.Components.Forms.FieldIdentifier.Create[String](Expression`1 accessor)
   at Microsoft.AspNetCore.Components.Forms.ValidationMessage`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnParametersSet()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()

### .NET Version

.NET 8

**Comment by javiercn** [comment]
@thanuja89 thanks for the additional details.

It seems to do with the fact that you have two model fields declared:

```csharp
    protected ModelModel Model;
    protected ModelModel model = new();
```

If I comment out `model` which is not used, the issue goes away.

Seems like the root of the exception comes from the call to `Expression.PropertyOrField` which seems to do a case-insensitive search.

**Comment by springy76** [comment]
I have a related problem to the same `Expression.PropertyOrField` case-changing problem but in my case one member is a field and the other member is a property. So I don't get an AmbiguousMatchException at that exact position but an ArgumentNullException some cpu cycles later within `ctor` of `FieldIdentifier`:

```callstack
System.ArgumentNullException: Value cannot be null. (Parameter 'model')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at Microsoft.AspNetCore.Components.Forms.FieldIdentifier..ctor(Object model, String fieldName)
   at Microsoft.AspNetCore.Components.Forms.FieldIdentifier.Create[TField](Expression`1 accessor)
   at Microsoft.AspNetCore.Components.Forms.InputBase`1.SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
```

That's because I have a field which is never null:
`private Model myModel`

and an optional parameter (sometimes used, then no circuit crash):
`[Parameter] public Model? MyModel { get; set; }`

and the usage of this now crashes the circuit:
`<InputTextArea @bind-Value="@this.myModel.Memo" />`

because it silently changed `@bind-Value="@this.myModel.Memo"` into `@bind-Value="@this.MyModel.Memo"` and then crashes because `this.MyModel` is null.

**Comment by springy76** [comment]
interesting way of handling a regression - any comments @mkArtakMSFT ? - is this a well documented breaking change?

**Comment by springy76** [comment]
@javiercn What's next? A soundex match maybe? I have a strong typed precompiled C# managed expression to existing code. I neither expect nor accept any blurry "maybe" here.

**Comment by thanuja89** [comment]
This is disapointing. Any idea when on when will this be fixed? We did not upgrade to .NET 8 because of this.

**Comment by AbstractionsAs** [comment]
This is definetly a bug with critical impact.
It has broken half my deployed applications, and it's not listed under breaking changes for net8
