### ISSUE TITLE
Endpoint with wildcard param clashes with route without one causing Open API document not to be generated

### ISSUE THREAD

**Issue by marinasundstrom** [dotnet/aspnetcore#52835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I don't know if this is related to a specific toolchain, like NSwag, but these endpoints seem to work but you can't generate a Open API document because they are seen as occupying the same route.

The cause is the wildcard which according to the OpenAPI generator belongs to the "/" route.

I have these routes:

```csharp
productsGroup.MapGet("/", GetProductCategories)
   .WithName($"ProductCategories_{nameof(GetProductCategories)}");

productsGroup.MapGet("{*id}", GetProductCategoryById)
   .WithName($"ProductCategories_{nameof(GetProductCategoryById)}");
```

When I try to open Swagger UI:

```
HTTP request POST http://localhost:9411/api/v2/spans
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: The method 'get' on path '/api/v1/productCategories' is registered multiple times.
         at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.AddOperationDescriptionsToDocument(OpenApiDocument document, Type controllerType, List`1 operations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver)
         at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateApiGroups(OpenApiDocumentGenerator generator, OpenApiDocument document, IGrouping`2[] apiGroups, OpenApiSchemaResolver schemaResolver)
         at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GenerateAsync(ApiDescriptionGroupCollection apiDescriptionGroups)
         at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GenerateDocumentAsync(HttpContext context)
         at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.GetDocumentAsync(HttpContext context)
         at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### Expected Behavior

These endpoints should be treated as different routes, and the OpenAPI be generated.

### .NET Version

 8.0.100

**Comment by captainsafia** [comment]
@marinasundstrom Thanks for filing this issue!

I don't believe this is related to a specific toolchain.

Routes with optional parameters, like the catch-all route, are difficult to present from an OpenAPI perspective because there's no statically defined route associated with these requests.

In the case that you provided above, it would be ideal to create two OpenAPI operations:

- One targeting `/` with an optional `id` parameter sourced from the route
- One targeting `/` without an optional parameter

But it's not possible, ATM, to define two OpenAPI operations with the same HTTP method and route. This is a constraint enforced by OpenAPI:

> OpenAPI defines a unique operation as a combination of a path and an HTTP method. This means that two GET or two POST methods for the same path are not allowed – even if they have different parameters (parameters have no effect on uniqueness). 
> -- [Reference](https://swagger.io/docs/specification/paths-and-operations/)

I don't know if there are any applicable workarounds for your toolchain that might help achieve the desired behavior.

**Comment by marinasundstrom** [comment]
Thank you for the response, @captainsafia. OK. This is good to know.

If only the catch-all constrained could have been required to match on value.
