### ISSUE TITLE
Automate SDK updates

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#52886]
Create a tool that automates weekly SDK updates. We can download the text file from dotnet/installer & use that to inform the update. Maybe this could go in Arcade.

**Comment by martincostello** [comment]
You may find this useful: https://github.com/marketplace/actions/update-net-sdk#net-daily-builds

**Comment by wtgodbe** [comment]
@martincostello thanks! Trying it out here: https://github.com/dotnet/aspnetcore/pull/53414

**Comment by wtgodbe** [comment]
@martincostello does this look like a permissions error to you?

> HttpError: Resource not accessible by integration
    at /home/runner/work/_actions/martincostello/update-dotnet-sdk/8765302da88e1a78c845125626f3726190908593/node_modules/@octokit/request/dist-node/index.js:112:1
    at process.debug (node:internal/process/task_queues:95:5)
    at DotNetSdkUpdater.result [as createPullRequest] (/home/runner/work/_actions/martincostello/update-dotnet-sdk/8765302da88e1a78c845125626f3726190908593/lib/DotNetSdkUpdater.js:287:1)
    at DotNetSdkUpdater.tryUpdateSdk (/home/runner/work/_actions/martincostello/update-dotnet-sdk/8765302da88e1a78c845125626f3726190908593/lib/DotNetSdkUpdater.js:241:1)
    at run (/home/runner/work/_actions/martincostello/update-dotnet-sdk/8765302da88e1a78c845125626f3726190908593/dist/index.js:1:18265)

https://github.com/dotnet/aspnetcore/actions/runs/7547207526

**Comment by martincostello** [comment]
Yeah, that looks like something not quite right with the `GITHUB_TOKEN` permissions. Do you have this repo set up with a more restrictive set of permissions by default or something?

You could try explicitly adding the permissions to the workflow flow like this: https://github.com/martincostello/update-dotnet-sdk/blob/3b5c008a07c86b1d6530b406a9832cbdaec2ea29/README.md?plain=1#L172-L174

It needs `write` for `contents` and `pull-requests`.

**Comment by wtgodbe** [comment]
Ah, makes sense - thanks! I opened https://github.com/dotnet/aspnetcore/pull/53422 for that.

**Comment by wtgodbe** [comment]
Done by https://github.com/dotnet/aspnetcore/pull/53414
