### ISSUE TITLE
A published blazor wasm app throws a serialization error "Unhandled exception rendering component: ConstructorContainsNullParameterNames"

### ISSUE THREAD

**Issue by Stamo-Gochev** [dotnet/aspnetcore#52947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

An error is thrown when making a JS interop call in a **published** blazor wasm app that should serialize a `KeyValuePair` [value](https://github.com/Stamo-Gochev/blazor-issue-wasm-serialization/blob/master/BlazorissueWasmSerialization/BlazorissueWasmSerialization.Client/Pages/Home.razor#L29).

This seems to be related to trimming as running this with things like `dotnet run --configuration Release` works as expected, but publishing the app starts the trimmer by default.

In addition, using an [anonymous type instead](https://github.com/Stamo-Gochev/blazor-issue-wasm-serialization/blob/master/BlazorissueWasmSerialization/BlazorissueWasmSerialization.Client/Pages/Home.razor#L35-L48) of `KeyValuePair` works without any errors.

> [!NOTE]
> I tried to [disable the trimming](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-7-0#enable-trimming), but the error is still present. Any suggestions on how to do that will be helpful - this might turn out to be another issue though.

![blazor-issue-wasm-serialization](https://github.com/dotnet/aspnetcore/assets/1857705/b96574f5-7e82-44bc-b408-9f39b0c5e810)

### Expected Behavior

No error is thrown.

### Steps To Reproduce

1. Clone https://github.com/Stamo-Gochev/blazor-issue-wasm-serialization
2. Change directory to https://github.com/Stamo-Gochev/blazor-issue-wasm-serialization/tree/master/BlazorissueWasmSerialization/BlazorissueWasmSerialization
3. Run `dotnet publish --configuration Release`
4. Go to `BlazorissueWasmSerialization/BlazorissueWasmSerialization/bin/Release/net8.0/publish`
5. Run `dotnet BlazorissueWasmSerialization.dll`
6. [Click the "Show issue button"](https://github.com/Stamo-Gochev/blazor-issue-wasm-serialization/blob/master/BlazorissueWasmSerialization/BlazorissueWasmSerialization.Client/Pages/Home.razor#L19-L33)

### Exceptions (if any)

<details>

<summary>Exception</summary>

```bash
blazor.web.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: ConstructorContainsNullParameterNames, System.Collections.Generic.KeyValuePair`2[System.String,System.String] SerializationNotSupportedParentType, System.Object Path: $.
System.NotSupportedException: ConstructorContainsNullParameterNames, System.Collections.Generic.KeyValuePair`2[System.String,System.String] SerializationNotSupportedParentType, System.Object Path: $.
 ---> System.NotSupportedException: ConstructorContainsNullParameterNames, System.Collections.Generic.KeyValuePair`2[System.String,System.String]
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_ConstructorContainsNullParameterNames(Type )
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.PopulateParameterInfoValues(JsonTypeInfo )
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.CreateTypeInfoCore(Type , JsonConverter , JsonSerializerOptions )
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.CreateJsonTypeInfo(Type , JsonSerializerOptions )
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.GetTypeInfo(Type , JsonSerializerOptions )
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoNoCaching(Type )
   at System.Text.Json.JsonSerializerOptions.CachingContext.CreateCacheEntry(Type type, CachingContext context)
--- End of stack trace from previous location ---
   at System.Text.Json.JsonSerializerOptions.CachingContext.CacheEntry.GetResult()
   at System.Text.Json.JsonSerializerOptions.CachingContext.GetOrAddTypeInfo(Type , Boolean )
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type , Boolean , Nullable`1 , Boolean , Boolean )
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureSynchronized|172_0()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.EnsureConfigured()
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type , Boolean , Nullable`1 , Boolean , Boolean )
   at System.Text.Json.WriteStackFrame.InitializePolymorphicReEntry(Type , JsonSerializerOptions )
   at System.Text.Json.Serialization.JsonConverter.ResolvePolymorphicConverter(Object , JsonTypeInfo , JsonSerializerOptions , WriteStack& )
   at System.Text.Json.Serialization.JsonConverter`1[[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryWrite(Utf8JsonWriter , Object& , JsonSerializerOptions , WriteStack& )
   at System.Text.Json.Serialization.Converters.DictionaryOfTKeyTValueConverter`3[[System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnWriteResume(Utf8JsonWriter , Dictionary`2 , JsonSerializerOptions , WriteStack& )
   at System.Text.Json.Serialization.JsonDictionaryConverter`3[[System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnTryWrite(Utf8JsonWriter , Dictionary`2 , JsonSerializerOptions , WriteStack& )
   at System.Text.Json.Serialization.JsonConverter`1[[System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryWrite(Utf8JsonWriter , Dictionary`2& , JsonSerializerOptions , WriteStack& )
   at System.Text.Json.Serialization.JsonConverter`1[[System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryWriteAsObject(Utf8JsonWriter , Object , JsonSerializerOptions , WriteStack& )
   at System.Text.Json.Serialization.JsonConverter`1[[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryWrite(Utf8JsonWriter , Object& , JsonSerializerOptions , WriteStack& )
   at System.Text.Json.Serialization.Converters.ArrayConverter`2[[System.Object[], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnWriteResume(Utf8JsonWriter , Object[] , JsonSerializerOptions , WriteStack& )
   at System.Text.Json.Serialization.JsonCollectionConverter`2[[System.Object[], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnTryWrite(Utf8JsonWriter , Object[] , JsonSerializerOptions , WriteStack& )
   at System.Text.Json.Serialization.JsonConverter`1[[System.Object[], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryWrite(Utf8JsonWriter , Object[]& , JsonSerializerOptions , WriteStack& )
   at System.Text.Json.Serialization.JsonConverter`1[[System.Object[], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].WriteCore(Utf8JsonWriter , Object[]& , JsonSerializerOptions , WriteStack& )
   Exception_EndOfInnerExceptionStack
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(WriteStack& , NotSupportedException )
   at System.Text.Json.Serialization.JsonConverter`1[[System.Object[], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].WriteCore(Utf8JsonWriter , Object[]& , JsonSerializerOptions , WriteStack& )
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1[[System.Object[], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Serialize(Utf8JsonWriter , Object[]& , Object )
   at System.Text.Json.JsonSerializer.WriteString[Object[]](Object[]& , JsonTypeInfo`1 )
   at System.Text.Json.JsonSerializer.Serialize[Object[]](Object[] , JsonSerializerOptions )
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[IJSVoidResult](Int64 , String , CancellationToken , Object[] )
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime , String , Object[] )
   at BlazorissueWasmSerialization.Client.Pages.Home.OnButtonShowIssueClick()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )

```

</details>

### .NET Version

8.0.100

**Comment by mguinness** [comment]
> Why would disabling trimming on the server app have any bearing on what happens to the client project?

I'm assuming that since the client csproj is referenced in the server csproj `MSBuild` includes that in the build and uses the `PublishTrimmed=false` option for both.  Regardless the `wwwroot\_framework` folder has 604 files (34.6 MB) with that option specified and 109 files (12.8 MB) without it (so does impact client build).

> I also notice that the reproduction is using reflection-based serialization APIs directly which to my knowledge isn't well supported in wasm.

Well it worked in .NET 6/7 and apparently .NET 8 (in debug mode).  I'm aware of the source generator for `System.Text.Json` but reflection-based serialization is still useful for migrating projects from .NET 6/7 (as alluded to by earlier comments).

> The constructor parameters for KeyValuePair have been trimmed away so we can't build a serialization contract for the type.

Understood.  The central issue here is that the `PublishTrimmed` option doesn't behave the same way in .NET 8 so transferring the issue from `runtime` to `aspnetcore` seems appropriate.  Maybe also add `area-Tools-ILLink` label so the linker/trimming team can take a look?

**Comment by javiercn** [comment]
@eiriktsarpalis blazor doesn't offer the ability to configure the underlying serialization for S.T.J for JS interop.

If the type can't be annotated, I assume a descriptor to preserve the type is the only way to keep this code working?

**Comment by eiriktsarpalis** [comment]
> > I also notice that the reproduction is using reflection-based serialization APIs directly which to my knowledge isn't well supported in wasm.
> 
> Well it worked in .NET 6/7

That's due to the intentional breaking change discussed here: https://github.com/dotnet/aspnetcore/issues/52947#issuecomment-1866491518. TL;DR in older versions the repro in question would successfully serialize but still fail to deserialize with a similar error message.

> If the type can't be annotated, I assume a descriptor to preserve the type is the only way to keep this code working?

Correct. Another thing to investigate is why the razor file in the repro doesn't emit trimmer warnings even though it is calling trim-unsafe APIs. We want to be emphatic with customers that they cannot reliably depend on reflection in trimmed applications and they should be moving to using the source generator instead -- emitting the relevant warnings would help a lot in that regard.

**Comment by javiercn** [comment]
> Correct. Another thing to investigate is why the razor file in the repro doesn't emit trimmer warnings even though it is calling trim-unsafe APIs. We want to be emphatic with customers that they cannot reliably depend on reflection in trimmed applications and they should be moving to using the source generator instead -- emitting the relevant warnings would help a lot in that regard.

Blazor predates many of the linking/trimming work (in fact, it spearheaded it) and does not support full trimming. For example, we don't trim customers dlls to prevent issues like this.

While I believe this is a regression, I am going to suggest we patch it on our side, since I think it'll be easier.

**Comment by eiriktsarpalis** [comment]
Is there an option to instruct the linker to specifically not trim away constructor parameters?

**Comment by vitek-karas** [comment]
> Is there an option to instruct the linker to specifically not trim away constructor parameters?

`--keep-metadata parametername` this will avoid removing names from method parameters. It obviously comes with size implication. Note that this means that the method in question is not considered accessible via reflection - otherwise we would keep its method parameters intact.

**Comment by mguinness** [comment]
With the [above repro](https://github.com/dotnet/aspnetcore/issues/52947#issuecomment-1866491619) why do the following settings from [Configure the Linker for ASP.NET Core Blazor](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/configure-linker?view=aspnetcore-3.1&viewFallbackFrom=aspnetcore-8.0) not prevent method parameters from being stripped?

```XML
<PropertyGroup>
  <BlazorWebAssemblyEnableLinking>false</BlazorWebAssemblyEnableLinking>
</PropertyGroup>

<ItemGroup>
  <BlazorLinkerDescriptor Include="LinkerConfig.xml" />
</ItemGroup>
```

Where assembly for [KeyValuePair](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.keyvaluepair-2?view=net-8.0) is specified:

```XML
<?xml version="1.0" encoding="UTF-8" ?>
<linker>
  <assembly fullname="System.Runtime">
      <type fullname="System.Collections.Generic*" />
  </assembly>
</linker>
```

**Comment by vitek-karas** [comment]
I suspect that the reason your workaround doesn't fix the problem is that `KeyValuePair` is actually defined in `System.Private.CoreLib`. It's documented as `System.Runtime`, but that is only a type forward. I don't know if the XML will correctly resolve all type forwards in this manner - especially if you're using wildcards.
/cc @sbomer

**Comment by mguinness** [comment]
Thanks for the suggestion, I changed the assembly name but it made no difference.  I did look at that assembly in the `wwwroot\_framework` folder and noticed that the constructor was `public KeyValuePair(TKey P_0, TValue P_1)` instead of `public KeyValuePair(TKey key, TValue value)` so that might be causing the issue based on the code in [PopulateParameterInfoValues](https://github.com/dotnet/runtime/blob/76934655be6108c5077be203d9d9ead3cfedb693/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/DefaultJsonTypeInfoResolver.Helpers.cs#L278) method.

**Comment by vitek-karas** [comment]
Can you try adding:
```xml
<_ExtraTrimmerArgs>--keep-metadata parametername</_ExtraTrimmerArgs>
```

(This is just to validate the assumptions... real fix would be something more complicated I guess)

**Comment by mguinness** [comment]
Yes, added that to `PropertyGroup` section in NullParameterNames.Client.csproj of the repro and the exception disappeared.

Confusing as setting `<PublishTrimmed>false</PublishTrimmed>` didn't achieve the same result - might be worth mentioning in [Trimming options](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-8-0) documentation.

**Comment by javiercn** [comment]
@vitek-karas what's the impact in terms of size that you expect from using something like `<_ExtraTrimmerArgs>--keep-metadata parametername</_ExtraTrimmerArgs>`.

**Comment by javiercn** [comment]
Given where we are, I think the best course of action is to go with https://github.com/dotnet/runtime/issues/81979. In addition to that, we'll update the documentation to recommend using types from your app with JS interop as those will be preserved.

**Comment by javiercn** [comment]
@guardrex can you add a note to the docs [here](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/configure-trimmer?view=aspnetcore-8.0) to "refrain from using complex framework types like KeyValuePair, etc, when performing JS interop as those types might be trimmed by default. Create your own custom types instead.

**Comment by guardrex** [comment]
... or if VS is correct for a primary ctor version ...

```csharp
[method: SetsRequiredMembers]
public sealed class StringKeyValuePair(string key, string value)
{
    public required string Key { get; init; } = key;
    public required string Value { get; init; } = value;
}
```

... but I've rejected showing an example because whatever we'd show would be quite arbitrary.

**Comment by zawarq** [comment]
I am facing a similar issue. I have the following code in a Blazor 8 app that works fine on local, but on Azure I get an error:

**Code**:

```
public async Task OnImageChanged(CellEditContext<WeblogImage> context, FileChangedEventArgs e)
{
    IFileEntry fileEntry = e.Files.FirstOrDefault();
    if (fileEntry != null)
    {
        using (var stream = new MemoryStream())
        {
            await fileEntry.WriteToStreamAsync(stream);
            stream.Seek(0, SeekOrigin.Begin);
            context.CellValue = stream.ToArray();
        }
    }
}
```

**Error**:

![image](https://github.com/dotnet/aspnetcore/assets/10173369/af497950-34ea-4730-84b4-dbae0e921028)

Note that I am using Blazorise DataGrid and FileEdit components

**Comment by Sean4572435243** [comment]
There's some whacky related behavior here:
https://github.com/dotnet/runtime/issues/98180#issuecomment-1936405042

**Comment by Sean4572435243** [comment]
here's another example of strange AOT behavior eliciting this exception, once again by LINQ and 'not' directly using serialization or KeyValuePair
https://github.com/dotnet/runtime/issues/98180#issuecomment-1937763185

**Comment by Sean4572435243** [comment]
No relief from 8.0.3

**Comment by Panzerfury** [comment]
Setting with something similar i think. 
![image](https://github.com/dotnet/aspnetcore/assets/5039402/8a0d325a-a8dc-40e2-96ee-cf24556ad6e0)

Working fine locally. But as soon as it's published through azure, to an IIS server it breaks.

**Comment by Sean4572435243** [comment]
No relief from VS 17.9.5

**Comment by Sean4572435243** [comment]
No relief from 8.0.4 or VS 17.9.6

**Comment by Stefano-Buzzoni** [comment]
Got the same issue while trying to publish a .NET 8 blazor application. VS 17.9.2

Retrying the 'Serialization' operation on the sitemanifest (sourcePath) object. Attempt 47 of 50.
Added file ({serverName}/Beltrame.Steelworks.Consumptions\wwwroot\_content\Microsoft.AspNetCore.Components.WebAssembly.Authentication\AuthenticationService.js).
C:\Program Files\dotnet\sdk\8.0.200\Sdks\Microsoft.NET.Sdk.Publish\targets\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(140,5): Warning: Retrying synchronization following socket error (10054).

**Comment by davidlsharp1** [comment]
Is there any indication they are looking at this yet?

**Comment by Sean4572435243** [comment]
No relief from 17.9.7 or 8.0.5

> Is there any indication they are looking at this yet?

Still open.  They usually get around to open items, particularly with so many different people reporting the issue.

**Comment by mguinness** [comment]
> Is there any indication they are looking at this yet?

The proposed solution will be tracked in https://github.com/dotnet/runtime/issues/81979 and that is now high priority in [dotnet/projects/135](https://github.com/orgs/dotnet/projects/135).

> No relief from 17.9.7 or 8.0.5

I don't think it's useful to create a new post for each version, but updating a single post would be.  I think most people subscribing to this issue want to get alerts when something tangible occurred (thumbs up/down for those that agree/disagree).

**Comment by Sean4572435243** [comment]
> I don't think it's useful to create a new post for each version, but updating a single post would be. I think most people subscribing to this issue want to get alerts when something tangible occurred (thumbs up/down for those that agree/disagree).

Given the infrequency of these updates, and the fact that there may be some latency for MS to update this issue, I felt that people interested in this problem would want to know whether a release corrects this problem or not, so they can avoid updating each time a new release is available in pursuit of hopefully this issue being fixed.  Far better to get an occasional email than to spend hours updating to a version that doesn't help, no?

**Comment by mguinness** [comment]
> I felt that people interested in this problem would want to know whether a release corrects this problem or not

Then create a new post when that actually occurs?  Just my 2¢ to point out the flip side.

**Comment by eiriktsarpalis** [comment]
Once a solution has been implemented, there will be an update posted to this issue as well.

**Comment by Sean4572435243** [comment]
> Once a solution has been implemented, there will be an update posted to this issue as well.

Ok, thanks for the assurance Eirik.  I'll just wait for the update then.  Apologies to everyone for the noise (it was well-intended)

**Comment by Bananas-Are-Yellow** [comment]
I have the same problem, only my project is a [Bolero](https://fsbolero.io/docs/) project written in F#. As far as I know, the source generator approach is not available to F# projects, only C# projects, so that doesn't help me.

I'm not using `KeyValuePair` but in my case the problem occurs using the F# tuple, which can be created in JS as: `{ Item1: value1, Item2: value2, ... }`. This is a natural way to return a few values from JS back to F#. This works fine until I publish the project and then trimming causes the problem.

The workaround is to return a JS object with fields that match an F# anonymous type. So in JS, you can return `{ Name: name, Age: age, Height: height }` and then deserialize this as `(result: {| Name: string; Age: int; Height: int |})` and then access `result.Name`, `result.Age`, and `result.Height`. This works fine.

**Comment by Sean4572435243** [comment]
From what I can see in this related issue https://github.com/dotnet/runtime/issues/81979#event-12988713923, it looks like they've solved the problem, but not sure which coming release will contain the fix.

**Comment by mguinness** [comment]
I assume it will be part of `9.0-preview6` but I don't know what the criteria is for backporting fixes to 8.0

**Comment by Sean4572435243** [comment]
It's fixed!  I updated to 8.0.6 aspnetcore and no more issues.  Thank you Microsoft!

**Comment by Sean4572435243** [comment]
If you've been paring down the deployed wasm files, be sure to include the _framework/system.io.compression.wasm library, or you'll still get this KeyPair error.

**Comment by mguinness** [comment]
> It's fixed! I updated to 8.0.6 aspnetcore and no more issues.

I don't see how PR https://github.com/dotnet/runtime/pull/102850 committed on May 30 was included in `8.0.6` which was released on May 28?

**Comment by Sean4572435243** [comment]
My KeyValuePair issue was related to LINQ, so possibly they fixed this related issue in a prior commit.  Try 8.0.6, report back.

**Comment by desmondinho** [comment]
We're facing the same issue but with `System.Tuple`. I've never touched source generator before and maybe I am doing something wrong, but do I understand correctly that there is no way to implement it [source generation] if `A<T>` is the base class that sits somewhere within our architecture and tons of classes derive from it in different projects which means that we can't just annotate `A<T>` with concrete classes as we don't know them?

```csharp
public abstract class A<T> where T : class
{
   public class B
   {
      [JsonInclude]
      private Tuple<T1, T2> _fieldName; 

      // Uses T inside
   }
}
```

**Comment by ghostinside** [comment]
8.0.6 still there 

`ConstructorContainsNullParameterNames, System.Collections.Generic.KeyValuePair`2[System.String,System.Collections.Generic.IEnumerable`1[System.String]]`

**Comment by ghostinside** [comment]
source of exception:

`Console.WriteLine(JsonSerializer.Serialize(response.Content.Headers));`

**Comment by rblanca** [comment]
Yeap confirmed tuple is getting the same error

**Comment by mguinness** [comment]
Current workaround is to set `keep-metadata parametername` on the linker, see https://github.com/dotnet/aspnetcore/issues/52947#issuecomment-1878478801.

**Comment by thirstyape** [comment]
Why wait for a fix that might not make it into .NET 8 at all? Here's a laughably simple workaround if you turn off trimming. 

Just replace `KeyValuePair` with `KeyValuePairSerializer` in your deserialization calls and then call `.ToKeyValuePair` or if you're in a list `.Select(x => x.ToKeyValuePair).ToList()`. Same idea can be done for the various `Tuple<T>` iterations.

```
using System.Text.Json.Serialization;

public class KeyValuePairSerializer<TKey, TValue>
{
	public KeyValuePairSerializer() { }

	public KeyValuePairSerializer(TKey key, TValue value)
	{
		Key = key;
		Value = value;
	}

	public TKey Key { get; set; }

	public TValue Value { get; set; }

	[JsonIgnore]
	public KeyValuePair<TKey, TValue> ToKeyValuePair => new(Key, Value);
}
```

**Comment by mguinness** [comment]
FWIW the issue still persists with the release of VS 2022 (17.12) and .NET 9

**Comment by nrhoffmann** [comment]
> [@vitek-karas](https://github.com/vitek-karas) what's the impact in terms of size that you expect from using something like `<_ExtraTrimmerArgs>--keep-metadata parametername</_ExtraTrimmerArgs>`.

This is very anecdotal but this only added 1MB to my 40MB app.

**Comment by danroth27** [comment]
@lewing @javiercn It seems like users are still hitting issue with the latest bits. Do we need to retriage this issue for servicing?

**Comment by danroth27** [comment]
Removing milestone for retriage.

**Comment by simong-hs** [comment]
Recently upgraded Blazor WASM app from .NET 6 to .NET 8, and my Published app throws this exception, in relation to Tuple serialization. Please consider a fix for this in .NET 8.

Implemented following in project file to workaround this temporarily:
` <_ExtraTrimmerArgs>--keep-metadata parametername</_ExtraTrimmerArgs>`

**Comment by lewing** [comment]
@maraf please verify we don't need to do more but I think https://github.com/dotnet/runtime/pull/112216 should get most of this?

**Comment by guardrex** [comment]
@lewing @maraf ... @pavelsavara and I were just working on a doc section related to the file descriptor approach with a .NET 9 BWA (per-component) project. It's breaking 💥. The test project is at ...

https://github.com/guardrex/BlazorTrimmerTesting

... and when the component is hit, the ...

> crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
Unhandled exception rendering component: ConstructorContainsNullParameterNames, System.Collections.Generic.KeyValuePair2[System.String,System.String]
System.NotSupportedException: ConstructorContainsNullParameterNames, System.Collections.Generic.KeyValuePair2[System.String,System.String]

... error is thrown.

The docs PR will keep the guidance commented out until it's resolved in the framework. Until then, we'll just have the `[DynamicDependency]` attribute approach and the custom type approach.

https://github.com/dotnet/AspNetCore.Docs/pull/34734

**Comment by mguinness** [comment]
That's good documentation Luke.  Would it be possible to include that link in the exception message [string resource](https://github.com/dotnet/runtime/blob/9e94b77aca3fb786394b94022c2e73c59b894f21/src/libraries/System.Text.Json/src/Resources/Strings.resx#L542-L544) in a similar fashion that's done for the `SpecialNumberValuesNotSupported` exception as it will be more discoverable by users.

```xml
<data name="ConstructorContainsNullParameterNames" xml:space="preserve">
  <value>
    The deserialization constructor for type '{0}' contains parameters with null names. 
    This might happen because the parameter names have been trimmed by ILLink. 
    Consider using the source generated serializer instead 
    (see https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/configure-trimmer#failure-to-preserve-types-used-by-a-published-app).
  </value>
</data>
```

**Comment by guardrex** [comment]
@mguinness ... Thanks. That's up the product unit engineers here. I only control the article side of things. We don't want silly green dinosaurs 🦖 mess'in about in the framework code! 😆

**Comment by frank-hoffman** [comment]
We just ran into this same problem in .NET 8 as of June 2025. Since this thread has been open since November 2023, I'm wondering if it will ever be fixed. We're going to be on .NET 8 for a while until the LTS cycle ends.

**Comment by imprathamesh** [comment]
I am facing this issue in blazor web app .net 8

**Comment by javiercn** [comment]
We have implemented fixes for this issue in both .NET 9 and .NET 10:
- **.NET 9**: We did a fix addressed the linker behavior that incorrectly trimmed `KeyValuePair<TKey, TValue>` even when told to preserve it.
- **.NET 10**: We are adding configuration to ensure `KeyValuePair` is preserved by default

While we are taking steps to preserve `KeyValuePair` explicitly in .NET 10.0, we recommend that you avoid using framework types that might be subject to trimming and instead use types defined in your own application for JS interop, as those won't get trimmed. If you insist in using framework types, the recommendation is to use:

1. **DynamicDependency Attribute**: Apply `[DynamicDependency]` to explicitly preserve types that your application requires at runtime
2. **TrimmerRootDescriptor**: Use XML descriptor files to specify assemblies, types, and members that must be preserved during trimming

We intentionally avoid blanket preservation of types in the framework because this approach forces all applications to pay the size cost, even when they don't use these types.

As a workaround for 8.0, you can add `<_ExtraTrimmerArgs>--keep-metadata parametername</_ExtraTrimmerArgs>` to your project file's PropertyGroup section, which preserves parameter names during trimming.

We've filed https://github.com/dotnet/runtime/issues/118481 to track demand for the backport of the linker fix to 8.0. We recommend you upvote that issue if this is impacting you.

We are now closing this issue as we plan to track any remaining work in the other issue.

**Comment by agocke** [comment]
This does not look like the right fix. Manually preserving types is not reliable. This fix also relies on undocumented switches. 

The correct fix is to avoid reflection-based serialization when trimming. For example, the system.text.json source generator avoids reflection and is safe for trimming

**Comment by guardrex** [comment]
> relies on undocumented switches

I opened a docs issue to address that aspect.

**Comment by javiercn** [comment]
@guardrex this deserves some discussion

**Comment by guardrex** [comment]
Before I reach the docs issue close to RC1's release, I'm 👂 here or on https://github.com/dotnet/AspNetCore.Docs/issues/35897 for your guidance on coverage.

**Comment by javiercn** [comment]
@guardrex we already have the proper docs in place.

**Comment by javiercn** [comment]
Leaving the comment form the associated PR here.

@agocke I understand the concerns about trimming reliability, but I believe we need to consider the broader impact on our customers here.

Blazor has supported partial trimming since its initial release, with JS interop using System.Text.Json internally from the beginning - well before the S.T.J source generator existed. Many of our customers have built applications around this established pattern, using runtime reflection for serialization in their JS interop scenarios.

Moving to source generation would be a significant breaking change that would require substantial refactoring of existing, working applications. There are immediate scenarios where source generation would make the developer experience worse:

1. **Annotation burden**: Customers would need to annotate every type used in JS interop with `[JsonSerializable]`, including nested types and dependencies. This is particularly painful for types from third-party libraries where they don't control the source.

2. **Razor component limitations**: Types defined within `.razor` files (a common pattern for component-specific DTOs and view models) cannot participate in source generation since the razor file is processed inside a SG itself. This would force developers to move these types to separate `.cs` files, and forcing them to opt out of the single file experience.

These are only two of the top of my head, but I'm sure there are more.

`DynamicDependency` is part of our [documented trimming guidance](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming#dynamicdependency), and using documented APIs to preserve functionality seems like a reasonable approach to maintain compatibility.

It's worth noting that Blazor's current trimming strategy (trimming framework assemblies but not user code) has been working well for our scenarios, and we haven't seen compelling evidence that full trimming would provide significant benefits for typical Blazor applications.

I strongly believe we should prioritize our customers' ability to upgrade without breaking their existing code. The original fix in #63099 solves a real problem that customers are facing today. Removing this fix would leave customers stuck between staying on an older version or undertaking significant refactoring work that doesn't add business value.

This fix maintains compatibility while keeping Blazor functional for our existing user base. That's the right tradeoff for our framework.

**Comment by guardrex** [comment]
The breaking use case is for `KeyValuePair`, so don't you at least want me to change ".NET 8 or later" to ".NET 8/9" in ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/configure-trimmer?view=aspnetcore-8.0#failure-to-preserve-types-used-by-a-published-app

... or use a completely different example as the regression use case that would continue to break in >=10.0?

**Comment by guardrex** [comment]
Also ...

> TrimmerRootDescriptor: Use XML descriptor files to specify assemblies, types, and members that must be preserved during trimming

... is already in the article but has to be activated at RC1. It's commented out in the text right now (and I think not reviewed yet) ...

https://github.com/dotnet/AspNetCore.Docs/blame/main/aspnetcore/blazor/host-and-deploy/configure-trimmer.md#L111

Whatever we do ... per the new way that preview coverage is rolling out on one PR ... I'll place this work on a single commit on the upcoming RC1 docs PR (next month), so it will be easy for you to review the changes.

**Comment by agocke** [comment]
The following switches/features are considered undocumented and undefined behavior by the trimmer:

* ILLink descriptor files
* rd.xml
* DynamicDependency

If you document their usage or rely on them, you are taking a dependency on undefined behavior.
