### ISSUE TITLE
Blazor Web App Client not registering a service/ DI not working

### ISSUE THREAD

**Issue by LongJohnBlackbeard** [dotnet/aspnetcore#53042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a Blazor Web App in .NET 8 with a interface and class that is registered in the Program.cs file. I injected into a razor page and receive errors when run.

This is all in the Client project not the Server Project

Note I have tried using Singleton, Scoped, and Transient as the Service Type to no avail.

Code:

Program.cs
```using Dispatch.Client.Services;
using Dispatch.Client.Services.Interfaces;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;

var builder = WebAssemblyHostBuilder.CreateDefault(args);

builder.Services.AddSingleton<IDispatchAPI, DispatchAPI>();
await builder.Build().RunAsync();
```

Razor Page
```
@page "/dispatch"
@rendermode InteractiveAuto
@inject IDispatchAPI DispatchAPI

<h3>Dispatch</h3>

@code {
    protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();
        var prodMin = await DispatchAPI.GetProductionMinutesSeriesAsync("3500", DateTime.Parse("2023-01-01"), DateTime.Parse("2023-12-28"));
        Console.WriteLine("Done");
    }

}
```

Interface
```
using Dispatch.Client.Models;

namespace Dispatch.Client.Services.Interfaces
{
    public interface IDispatchAPI
    {
        public Task<ProdMinutesSeries> GetProductionMinutesSeriesAsync(string department, DateTime startDate, DateTime endDate);
    }
}
```

Class
```
using Dispatch.Client.Models;
using Dispatch.Client.Services.Interfaces;
using System.Diagnostics;
using System.Net.Http.Json;

namespace Dispatch.Client.Services
{
    public class DispatchAPI : IDispatchAPI
    {
        private HttpClientHandler _httpClientHandler;

        public DispatchAPI()
        {
            _httpClientHandler = new HttpClientHandler();
        }
        public async Task<ProdMinutesSeries> GetProductionMinutesSeriesAsync(string department, DateTime startDate, DateTime endDate)
        {

            using (var httpClient = new HttpClient(_httpClientHandler))
            {
                httpClient.BaseAddress = new Uri("https://localhost:7239");
                try
                {
                    var response = await httpClient.GetAsync($"/ProdMinutes/ProdMinutes?department={department}&startDate={startDate}&enddate={endDate}");
                    if(response.IsSuccessStatusCode)
                    {
                        var prodMin = await response.Content.ReadFromJsonAsync<ProdMinutesSeries>();
                        return prodMin;
                    }
                    return null;

                }
                catch (Exception ex)
                {
                    Debug.WriteLine(ex.ToString);
                    return null;
                }
            }

        }
    }
}
```

### Expected Behavior

With the Service added in the Program.cs file, I should be able to DI the service into the Razor page and called the methods of the interface which is an API call.

### Steps To Reproduce

Create a new Blazor Web Application. Add a interface and class file, add the interface to the program as a Singleton. Inject the interface into a razor page. Call a method in a OnInitializedAsync.

### Exceptions (if any)

```
System.InvalidOperationException: Cannot provide a value for property 'DispatchAPI' on type 'Dispatch.Client.Pages.Dispatch'. There is no registered service of type 'Dispatch.Client.Services.Interfaces.IDispatchAPI'.
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass9_0.<CreatePropertyInjector>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType, IComponentRenderMode callerSpecifiedRenderMode, Nullable`1 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame[] frames, Int32 frameIndex, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderRootComponentAsync(Int32 componentId, ParameterView initialParameters)
   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.BeginRenderingComponent(IComponent component, ParameterView initialParameters)
   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.RenderEndpointComponent(HttpContext httpContext, Type rootComponentType, ParameterView parameters, Boolean waitForQuiescence)
   at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
   at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<<InvokeAsync>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### .NET Version

.NET 8

### Anything else?

![image](https://github.com/dotnet/aspnetcore/assets/72884152/04a866da-7405-4337-87ad-ebb240aede3e)

**Comment by LongJohnBlackbeard** [comment]
I was able to fix by adding the service to the server as well. Im guessing with InteractiveAuto the first time it runs on the server it looks for the service there. Since the server adds the webassembly components would it not be beneficial to add its services as well?

**Comment by marinasundstrom** [comment]
@LongJohnBlackbeard Within the Blazor app components get pre-rendered on the server by default. You can turn it off though:

To disable on a component:

```razor
<... @rendermode="new InteractiveWebAssemblyRenderMode(prerender: false)" />
```

Or on the component - like a @page component:

```razor
@rendermode @(new InteractiveWebAssemblyRenderMode(prerender: false))
```

For Auto:

@rendermode @(new InteractiveAutoRenderMode(prerender: false))

The reason for having to set up dependencies twice in this case is that Server and Client are separate apps in different contexts - thus different bootstrapping.

**Comment by javiercn** [comment]
@LongJohnBlackbeard thanks for contacting us.

Services need to be registered in all places where they run.
