### ISSUE TITLE
[Blazor WebApp] CustomAuthorizationHandler IAccessTokenProvider not injected

### ISSUE THREAD

**Issue by mohaaron** [dotnet/aspnetcore#53066]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have created a new WebApp project that has been configured to authenticate using the Duende demo API. I have followed the [documentation](https://learn.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-8.0#attach-tokens-to-outgoing-requests) for using a custom AuthorizationMessageHandler for passing tokens to the API. My goal here was to create a dirt simple example of using the new WebApp template that connects to an OIDC provider.

The referenced documentation states "AuthorizationMessageHandler is a DelegatingHandler used to process access tokens. Tokens are acquired using the IAccessTokenProvider service, which is registered by the framework.".

When I run the project and browse to the page that calls the API I get the error "No service for type IAccessTokenProvider has been registered". I've been searching for anyone else having this issue and am not finding anything. I assume that I must be doing something wrong if others aren't having the same issue.

Here is the sample project: https://github.com/mohaaron/CustomAuthorizationHandler/

I hope I'm just tired and missing something simple.

### Expected Behavior

The implementation of IAccessTokenProvider is injected into the CustomAuthorizationMessageHandler.

### Steps To Reproduce

Pull Github repo
Run WebApp project
Login to the demo identity server
Navigate to the Fetch Remote Data menu item

### Exceptions (if any)

crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Unable to resolve service for type 'Microsoft.AspNetCore.Components.WebAssembly.Authentication.IAccessTokenProvider' while attempting to activate 'BlazorWebApp.Client.CustomAuthorizationMessageHandler'.
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Components.WebAssembly.Authentication.IAccessTokenProvider' while attempting to activate 'BlazorWebApp.Client.CustomAuthorizationMessageHandler'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(ServiceIdentifier serviceIdentifier, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, ServiceIdentifier serviceIdentifier, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceIdentifier, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.Extensions.DependencyInjection.ServiceProvider.ServiceAccessor, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].GetOrAdd(ServiceIdentifier key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[CustomAuthorizationMessageHandler](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.<>c__4`1[[BlazorWebApp.Client.CustomAuthorizationMessageHandler, BlazorWebApp.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<AddHttpMessageHandler>b__4_1(HttpMessageHandlerBuilder b)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.<>c__DisplayClass17_0.<CreateHandlerEntry>g__Configure|0(HttpMessageHandlerBuilder b)
   at Microsoft.Extensions.Http.MetricsFactoryHttpMessageHandlerFilter.<>c__DisplayClass2_0.<Configure>b__0(HttpMessageHandlerBuilder builder)
   at Microsoft.Extensions.Http.LoggingHttpMessageHandlerBuilderFilter.<>c__DisplayClass6_0.<Configure>b__0(HttpMessageHandlerBuilder builder)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandlerEntry(String name)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.<>c__DisplayClass14_0.<.ctor>b__2()
   at System.Lazy`1[[Microsoft.Extensions.Http.ActiveHandlerTrackingEntry, Microsoft.Extensions.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1[[Microsoft.Extensions.Http.ActiveHandlerTrackingEntry, Microsoft.Extensions.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1[[Microsoft.Extensions.Http.ActiveHandlerTrackingEntry, Microsoft.Extensions.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].CreateValue()
   at System.Lazy`1[[Microsoft.Extensions.Http.ActiveHandlerTrackingEntry, Microsoft.Extensions.Http, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].get_Value()
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandler(String name)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateClient(String name)
   at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.AddTransientHelper[RemoteApiService](IServiceProvider s, IHttpClientBuilder builder)
   at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.<>c__DisplayClass13_0`1[[BlazorWebApp.Client.Services.RemoteApiService, BlazorWebApp.Client, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].<AddTypedClientCore>b__0(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeServiceProviderEngine.<>c__DisplayClass4_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass9_0.<CreatePropertyInjector>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType, IComponentRenderMode callerSpecifiedRenderMode, Nullable`1 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame[] frames, Int32 frameIndex, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForFramesWithSameSequence(DiffContext& diffContext, Int32 oldFrameIndex, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
blazor.web.js:1:157675

### .NET Version

8.0.100

**Comment by codehunter13** [comment]
I got exactly the same problem

**Comment by mohaaron** [comment]
> I got exactly the same problem

I'm both happy and sad to hear this :)

**Comment by danroth27** [comment]
See https://github.com/dotnet/aspnetcore/issues/51699#issuecomment-1797082279

**Comment by bart-auvifox** [comment]
Hi

I am experiencing the exact same problem. 
The server has no problem using the token in the context (htppcontext.gettokenasync("access_token").

but when I try to get the token in the client (_iaccesstokenprovider.RequestAccessToken() ) i keep receiving the error: 
  Unhandled exception rendering component: Unable to resolve service for type 'Microsoft.AspNetCore.Components.WebAssembly.Authentication.IAccessTokenProvider' while attempting to activate 'Microsoft.AspNetCore.Components.WebAssembly.Authentication.AuthorizationMessageHandler'.

This is how my httpclient is made:

`
builder.Services.AddScoped<AuthorizationMessageHandler>();
builder.Services.AddHttpClient<IArticleService, ArticleService>(httpClient =>
{
    httpClient.BaseAddress = new Uri("https://localhost:7166/");
}).AddHttpMessageHandler<AuthorizationMessageHandler>();
`

No matter what handler i try to create, I keeep hitting the same error (unable to resolve...)

Example repo: https://github.com/malfaitbart/oidcdemo

=> Server is an openiddict setup that works without issues in .NET 7 WASM

**Comment by halter73** [comment]
The problem you're running into is that `IAccessTokenProvider` is from the Microsoft.AspNetCore.Components.WebAssembly.Authentication assembly which is a client dependency unavailable on the server during prerendering or server interactivity.

`IAccessTokenProvider` is normally implemented by [RemoteAuthenticationService<TRemoteAuthenticationState,TAccount,TProviderOptions>](https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore.components.webassembly.authentication.remoteauthenticationservice-3) which is added by [AddOidcAuthentication](https://learn.microsoft.com/dotnet/api/microsoft.extensions.dependencyinjection.webassemblyauthenticationservicecollectionextensions.addoidcauthentication) or [AddMsalAuthentication](https://learn.microsoft.com/dotnet/api/microsoft.extensions.dependencyinjection.msalwebassemblyservicecollectionextensions.addmsalauthentication#microsoft-extensions-dependencyinjection-msalwebassemblyservicecollectionextensions-addmsalauthentication(microsoft-extensions-dependencyinjection-iservicecollection-system-action((microsoft-aspnetcore-components-webassembly-authentication-remoteauthenticationoptions((microsoft-authentication-webassembly-msal-models-msalprovideroptions)))))) in the client project's Program.cs. The [CustomAuthorizationHandler repro](https://github.com/mohaaron/CustomAuthorizationHandler) instead uses server-side OIDC authentication with a combination of [AddOpenIdConnect](https://learn.microsoft.com/dotnet/api/microsoft.extensions.dependencyinjection.openidconnectextensions.addopenidconnect) and [AddCookie](https://learn.microsoft.com/dotnet/api/microsoft.extensions.dependencyinjection.cookieextensions.addcookie#microsoft-extensions-dependencyinjection-cookieextensions-addcookie(microsoft-aspnetcore-authentication-authenticationbuilder)) with  This means there is no `IAccessTokenProvider` registered anywhere, but you can still retrieve the access token from the encrypted cookie on the server because [OpenIdConnectOptions.SaveTokens](https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore.authentication.remoteauthenticationoptions.savetokens0#microsoft-aspnetcore-authentication-remoteauthenticationoptions-savetokens) is set to true.

In [one of the more recent commits in the CustomAuthorizationHandler repro](https://github.com/mohaaron/CustomAuthorizationHandler/commit/021fb5d617abd811f0419ed80fcb92adcf41d4fd), I see that you tried to add a second `RemoteApiService` in the server project. This doesn't work, because the `FetchRemoteData` component is trying to resolve the `BlazorWebApp.Client.Services.RemoteApiService` and not the `BlazorWebApp.Services.RemoteApiService` which is a different type. You can register different implementations for the same service in the server and client projects, but the service interface or abstract base class must be the same. You can see an example of this in the `IWeatherForecaster` interface in the [BlazorWebAppOidcBff sample](https://github.com/dotnet/blazor-samples/tree/39c7f432c0a97c69b5d05fee59e75b6121d98b06/8.0/BlazorWebAppOidcBff) which is implemented by both the `ServerWeatherForecaster` and `ClientWeatherForecaster`.

I submitted a [PR to the CustomAuthorizationHandler repro project](https://github.com/mohaaron/CustomAuthorizationHandler/pull/1) that fixes the errors by transmitting the access token from the encrypted cookie to the client in an unencrypted form via `UserInfo` using the `PersistentAuthenticationStateProvider` and `PersistingAuthenticationStateProvider`. This is not ideal from a security perspective because tokens accessible from JS like the one sent to the client via `UserInfo` are susceptible to XSS. [Microsoft Entra gives shorter expirations to tokens issued to SPA apps because of the XSS potential](https://learn.microsoft.com/entra/identity-platform/reference-third-party-cookies-spas#security-implications-of-refresh-tokens-in-the-browser), so it would be circumventing best practices to transmit the token. I'm not sure if @brockallen has opinions about this, but I would recommend instead using the BFF pattern demonstrated by https://learn.microsoft.com/aspnet/core/blazor/security/blazor-web-app-with-oidc?pivots=with-bff-pattern which uses YARP to proxy requests from the client and then attaches on the access token on the server to the proxied request. This allows the client to make authenticated requests to an API expecting an access from the client using a cookie without transmitting the unencrypted access token to the client.

The repro at https://github.com/malfaitbart/oidcdemo is failing because of the same reason. Without a call to `AddOidcAuthentication` or `AddMsalAuthentication` on the client project (which you correctly don't use if you want to be able to authenticate server side), there's no `RemoteAuthenticationService` registered as an `IAccessTokenProvider` for the [AuthorizationMessageHandler](https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore.components.webassembly.authentication.authorizationmessagehandler) to use. Instead, you'll want to use the BFF pattern to extract the token from the encrypted cookie as demonstrated in https://learn.microsoft.com/aspnet/core/blazor/security/blazor-web-app-with-oidc?pivots=with-bff-pattern or transmit the the unencrypted access token to the client using `PersistentComponentState` as demonstrated in https://github.com/mohaaron/CustomAuthorizationHandler/pull/1. I think that the BFF pattern is the far better option of the two though.

> => Server is an openiddict setup that works without issues in .NET 7 WASM

If you are happy continuing to do all authentication client side, you are free to host your WASM app using the exact same APIs you did in .NET 7 and go without calling `MapRazorComponents`. If you just change your `<TargetFramework>` from `net7.0` to `net8.0` everything and update your NuGet dependencies, everything should still work and be fully supported

**Comment by brockallen** [comment]
> I'm not sure if @brockallen has opinions about this

Yes, a [full-featured BFF](https://blog.duendesoftware.com/posts/20210929_bff_update/) would be the approach [recommended for SPAs](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-browser-based-apps-17#section-6.1).

**Comment by mohaaron** [comment]
@halter73 
Wow, thank you so much for the very thorough and detailed response, and the PR. I'm looking through all of this and really appreciate it.
