### ISSUE TITLE
AuthenticationStateProvider custom implementation in .NET 8

### ISSUE THREAD

**Issue by MPVictorHugoSilva** [dotnet/aspnetcore#53182]
I am trying to port the code of an existing Blazor Server App created in .NET 6 to a new Blazor Web App in .NET 8 and the custom implementation of the AuthenticationStateProvider that we have simply doesn't work for a number of reasons:
1. Starting the application with the same services registered in the same way just results in getting: "InvalidOperationException: Unable to find the required 'IAuthenticationService' service. Please add all the required services by calling 'IServiceCollection.AddAuthentication' in the application startup code."
2. Adding builder.Services.AddAuthentication(IdentityConstants.ApplicationScheme).AddIdentityCookies(); to Program.cs and updating our login page route to "/account/login" seems to make it work, at least for logging in and general authorization, but when we try to logout using the same code as before, meaning, executing AuthenticationStateProvider.NotifyAuthenticationStateChanged(Task.FromResult(new AuthenticationState(newUser))) then we just get the following and the connection gets disconnected:

blazor.web.js:1 [2024-01-05T16:05:15.790Z] Error: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at Microsoft.AspNetCore.Components.CascadingValueSource`1.<>c__DisplayClass10_0.<NotifyChangedAsync>b__0()
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContextDispatcher.InvokeAsync(Action workItem)
   at Microsoft.AspNetCore.Components.CascadingValueSource`1.NotifyChangedAsync()
   at Microsoft.Extensions.DependencyInjection.CascadingAuthenticationStateServiceCollectionExtensions.AuthenticationStateCascadingValueSource.HandleAuthenticationStateChanged(Task`1 newAuthStateTask)
   at xxxxx.App.Application.SecurityManagerAuthenticationStateProvider.<.ctor>b__1_0(ClaimsPrincipal newUser) in xxxxx\Application\SecurityManagerAuthenticationStateProvider.cs:line 26
   at xxxxx.App.Application.Data.Services.AuthenticationService.set_CurrentUser(ClaimsPrincipal value) in xxxxx.App\Application\Data\Services\AuthenticationService.cs:line 57
   at xxxxx.App.Application.Data.Services.AuthenticationService.LogoutAsync() in xxxxx.App\Application\Data\Services\AuthenticationService.cs:line 128
   at xxxxx.App.Components.Controls.LogoutPopOver.Logout() in xxxxx.App\Components\Controls\LogoutPopOver.razor.cs:line 52
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at MudBlazor.MudBaseButton.OnClickHandler(MouseEventArgs ev)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

Any help woud be much appreciated!

**Comment by stkuo600** [comment]
hi @MPVictorHugoSilva have you fixed the issue? thanks

**Comment by MPVictorHugoSilva** [comment]
No @stkuo600, I am in direct contact with a Microsoft specialist that is looking at it, once I have a reply from him I will enter it here
