### ISSUE TITLE
Scaffolded form error: EditForm requires either a Model

### ISSUE THREAD

**Issue by MKI-Miro** [dotnet/aspnetcore#53195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I hit submit button of scaffolded create.razor page i get error:

InvalidOperationException: EditForm requires either a Model parameter, or an EditContext parameter, please provide one of these.

I made Scaffolding with Visaal Studio Version 17.9.0 Preview 2.1

```
@page "/rooms/create"
@inject Mice.Data.DatabasePomelo.MysqlMice80Context DB
@using Mice.Data.DatabasePomelo
@inject NavigationManager NavigationManager

<PageTitle>Create</PageTitle>

< h1>Create</h1>

< h4>Room</h4>
< hr />
< div class="row">
    < div class="col-md-4">
        < EditForm method="post" Model="Room" OnValidSubmit="AddRoom" FormName="create" Enhance>
            < DataAnnotationsValidator />
            < ValidationSummary class="text-danger" />
            < div class="mb-3">
                < label for="name" class="form-label">Name:</label> 
                < InputText id="name" @bind-Value="Room.Name" class="form-control" /> 
                < ValidationMessage For="() => Room.Name" class="text-danger" /> 
            </ div>        
            < button type="submit" class="btn btn-primary">Create</button>
        </ EditForm>
    < /div>
</ div>

<div>
    < a href="/rooms">Back to List</a>
< /div>

@code {

    [SupplyParameterFromForm]
    public Room Room { get; set; } = new();

    // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
    public async Task AddRoom()
    {
        DB.Rooms.Add(Room);
        await DB.SaveChangesAsync();
        NavigationManager.NavigateTo("/rooms");
    }
}
```

### Exceptions (if any)

System.InvalidOperationException: EditForm requires either a Model parameter, or an EditContext parameter, please provide one of these.
   at Microsoft.AspNetCore.Components.Forms.EditForm.OnParametersSet()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SetDirectParameters(ParameterView parameters)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderRootComponentAsync(Int32 componentId, ParameterView initialParameters)
   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.BeginRenderingComponent(IComponent component, ParameterView initialParameters)
   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.RenderEndpointComponent(HttpContext httpContext, Type rootComponentType, ParameterView parameters, Boolean waitForQuiescence)
   at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
   at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<<InvokeAsync>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Antiforgery.Internal.AntiforgeryMiddleware.InvokeAwaited(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

### .NET Version

8.0.100

**Comment by javiercn** [comment]
```
    [SupplyParameterFromForm]
    public Room Room { get; set; } = new();
```

The above code should be

```
protected override OnInitialized()
{
  Room ??= new();
}
```
