### ISSUE TITLE
NewtonsoftJsonInputFormatter will fail deserializing stream with byte order mark

### ISSUE THREAD

**Issue by jeppevammenkristensen** [dotnet/aspnetcore#53315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The NewtonsoftJsonInputFormatter will fail to deserialize a stream that has a byte order mark in the start of it, but the default SystemTextJsonInputFormatter will handle deserializing the stream without throwing an exception. Also an asp.net solution using the .net framework would also handle it. 

### Expected Behavior

I expect the NewtonsoftJsonInputFormatter to handle and deserialize a json stream where a byteordermark has been added without throwing an exception. Like how SystemTextJsonInputFormatter does it.

### Steps To Reproduce

I have created a [repo](https://github.com/jeppevammenkristensen/NewtonsoftInputFormaterByteOrderMark) in github where the error can be reproduced. It consists of a WebApi project that has included the `Microsoft.AspNetCore.Mvc.NewtonsoftJson` package and enabled newtonsoft as the formatter. It also has a Test project (console) that will call the given api with data serialized in a way that produces the error. 

### Exceptions (if any)

The following is from the asp.net core project where the error occurs for a json stream that is using utf8 (and has a Byte Order Mark) in the start of the stream.

```
dbug: Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter[1]
      JSON input formatter threw an exception.
      Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: ?. Path '', line 0, position 0.
         at Newtonsoft.Json.JsonTextReader.ParseValue()
         at Newtonsoft.Json.JsonTextReader.Read()
         at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
         at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
         at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
```

The deserialization is invoked here 

`Mvc.NewtonsoftJson/src/NewtonsoftJsonInputFormatter.cs:line 161`  in the `ReadRequestBodyAsync` method

```csharp
try
{
    model = jsonSerializer.Deserialize(jsonReader, type);
}
finally
{
    // Clean up the error handler since CreateJsonSerializer() pools instances.
    jsonSerializer.Error -= ErrorHandler;
    ReleaseJsonSerializer(jsonSerializer);

    if (disposeReadStream)
    {
        await readStream.DisposeAsync();
    }
}
````

### .NET Version

6.0 and above (might also effect earlier versions)

### Anything else?

```
async NewtonsoftJsonInputFormatter.ReadRequestBodyAsync() at C:/Users/jayki/AppData/Local/Symbols/src/dotnet/aspnetcore/8e941eb42f819adb116b881195158b3887a70a1c/src/Mvc/Mvc.NewtonsoftJson/src/NewtonsoftJsonInputFormatter.cs:line 161
AsyncMethodBuilderCore.Start<Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter.<ReadRequestBodyAsync>d__12>()
AsyncTaskMethodBuilder<InputFormatterResult>.Start<Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonInputFormatter.<ReadRequestBodyAsync>d__12>()
NewtonsoftJsonInputFormatter.ReadRequestBodyAsync()
InputFormatter.ReadAsync()
BodyModelBinder.<BindModelAsync>d__11.MoveNext()
AsyncMethodBuilderCore.Start<Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.<BindModelAsync>d__11>()
AsyncTaskMethodBuilder.Start<Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.<BindModelAsync>d__11>()
BodyModelBinder.BindModelAsync()
ParameterBinder.<BindModelAsync>d__8.MoveNext()
AsyncMethodBuilderCore.Start<Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.<BindModelAsync>d__8>()
AsyncValueTaskMethodBuilder<ModelBindingResult>.Start<Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.<BindModelAsync>d__8>()
ParameterBinder.BindModelAsync()
ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
AsyncMethodBuilderCore.Start<Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d>()
AsyncTaskMethodBuilder.Start<Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d>()
ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<CreateBinderDelegate>g__Bind|0()
ControllerActionInvoker.Next()
ControllerActionInvoker.InvokeInnerFilterAsync()
ResourceInvoker.Next()
ResourceInvoker.InvokeFilterPipelineAsync()
ResourceInvoker.<<InvokeAsync>g__Logged|17_1>d.MoveNext()
AsyncMethodBuilderCore.Start<Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeAsync>g__Logged|17_1>d>()
AsyncTaskMethodBuilder.Start<Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeAsync>g__Logged|17_1>d>()
ResourceInvoker.<InvokeAsync>g__Logged|17_1()
ResourceInvoker.InvokeAsync()
ControllerRequestDelegateFactory.<>c__DisplayClass12_0.<CreateRequestDelegate>b__0()
EndpointMiddleware.Invoke()
AuthorizationMiddleware.<Invoke>d__11.MoveNext()
AsyncMethodBuilderCore.Start<Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.<Invoke>d__11>()
AsyncTaskMethodBuilder.Start<Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.<Invoke>d__11>()
AuthorizationMiddleware.Invoke()
HttpsRedirectionMiddleware.Invoke()
StaticFileMiddleware.Invoke()
SwaggerUIMiddleware.<Invoke>d__5.MoveNext()
AsyncMethodBuilderCore.Start<Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.<Invoke>d__5>()
AsyncTaskMethodBuilder.Start<Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.<Invoke>d__5>()
SwaggerUIMiddleware.Invoke()
SwaggerMiddleware.<Invoke>d__4.MoveNext()
AsyncMethodBuilderCore.Start<Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__4>()
AsyncTaskMethodBuilder.Start<Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__4>()
SwaggerMiddleware.Invoke()
[Lightweight Method Call]
AuthenticationMiddleware.<Invoke>d__6.MoveNext()
AsyncMethodBuilderCore.Start<Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6>()
AsyncTaskMethodBuilder.Start<Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6>()
AuthenticationMiddleware.Invoke()
DeveloperExceptionPageMiddlewareImpl.<Invoke>d__14.MoveNext()
AsyncMethodBuilderCore.Start<Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.<Invoke>d__14>()
AsyncTaskMethodBuilder.Start<Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.<Invoke>d__14>()
DeveloperExceptionPageMiddlewareImpl.Invoke()
HostFilteringMiddleware.Invoke()
HttpProtocol.<ProcessRequests>d__238<HostingApplication.Context>.MoveNext()
AsyncTaskMethodBuilder<VoidTaskResult>.AsyncStateMachineBox<HttpProtocol.<ProcessRequests>d__238<HostingApplication.Context>>.ExecutionContextCallback()
ExecutionContext.RunInternal() [5]
AsyncTaskMethodBuilder<VoidTaskResult>.AsyncStateMachineBox<HttpProtocol.<ProcessRequests>d__238<HostingApplication.Context>>.MoveNext()
AsyncTaskMethodBuilder<VoidTaskResult>.AsyncStateMachineBox<HttpProtocol.<ProcessRequests>d__238<HostingApplication.Context>>.MoveNext()
ManualResetValueTaskSourceCore<ReadResult>.SignalCompletion()
ManualResetValueTaskSourceCore<ReadResult>.SetResult()
PoolingAsyncValueTaskMethodBuilder<ReadResult>.StateMachineBox.SetResult()
PoolingAsyncValueTaskMethodBuilder<ReadResult>.SetResult()
StreamPipeReader.<<ReadInternalAsync>g__Core|40_0>d.MoveNext()
PoolingAsyncValueTaskMethodBuilder<ReadResult>.StateMachineBox<StreamPipeReader.<<ReadInternalAsync>g__Core|40_0>d>.ExecutionContextCallback()
ExecutionContext.RunInternal() [4]
PoolingAsyncValueTaskMethodBuilder<ReadResult>.StateMachineBox<StreamPipeReader.<<ReadInternalAsync>g__Core|40_0>d>.MoveNext()
SslStream.<ReadAsyncInternal>d__163<AsyncReadWriteAdapter>.MoveNext()
PoolingAsyncValueTaskMethodBuilder<int>.StateMachineBox<SslStream.<ReadAsyncInternal>d__163<AsyncReadWriteAdapter>>.ExecutionContextCallback()
ExecutionContext.RunInternal() [3]
PoolingAsyncValueTaskMethodBuilder<int>.StateMachineBox<SslStream.<ReadAsyncInternal>d__163<AsyncReadWriteAdapter>>.MoveNext()
SslStream.<EnsureFullTlsFrameAsync>d__161<AsyncReadWriteAdapter>.MoveNext()
PoolingAsyncValueTaskMethodBuilder<int>.StateMachineBox<SslStream.<EnsureFullTlsFrameAsync>d__161<AsyncReadWriteAdapter>>.ExecutionContextCallback()
ExecutionContext.RunInternal() [2]
PoolingAsyncValueTaskMethodBuilder<int>.StateMachineBox<SslStream.<EnsureFullTlsFrameAsync>d__161<AsyncReadWriteAdapter>>.MoveNext()
DuplexPipeStream.<ReadAsyncInternal>d__27.MoveNext()
PoolingAsyncValueTaskMethodBuilder<int>.StateMachineBox<DuplexPipeStream.<ReadAsyncInternal>d__27>.ExecutionContextCallback()
ExecutionContext.RunInternal() [1]
PoolingAsyncValueTaskMethodBuilder<int>.StateMachineBox<DuplexPipeStream.<ReadAsyncInternal>d__27>.MoveNext()
PoolingAsyncValueTaskMethodBuilder<int>.StateMachineBox<DuplexPipeStream.<ReadAsyncInternal>d__27>.System.Threading.IThreadPoolWorkItem.Execute()
ThreadPoolWorkQueue.Dispatch()
PortableThreadPool.WorkerThread.WorkerThreadStart()
[Native to Managed Transition]
```

**Comment by remiplanglois** [comment]
I recently ran into this issue. It took me a while to understand what was happening. Since we don't have control on the client's code that are calling our API, we had to create a middleware to remove this BOM. Is there any plan to fix this?
