### ISSUE TITLE
There are multiple .NET runtimes present, so a default dispatcher could not be resolved. Use DotNetObject to invoke .NET instance methods.

### ISSUE THREAD

**Issue by codehunter13** [dotnet/aspnetcore#53330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I use https://github.com/mr-azazael/LightweightCharts.Blazor which is using JsInterop.
Im using the .net 8 Blazor Web App template with rendermode InteractiveAuto applied globally.
When running i get the error:   Microsoft.JSInterop.JSException: 'There are multiple .NET runtimes present, so a default dispatcher could not be resolved. Use DotNetObject to invoke .NET instance methods.

I tried the same Webapp template, the same rendermode but applied per page/component.
I made a page with a chart in the server project (rendermode = server) and one in the client project(rendermode = WebAssembly).

Both pages are giving the same error if i open the other first. So
open server side, than open client side => error
or
open client side, then open serverside => error

```
Microsoft.JSInterop.JSException
  HResult=0x80131500
  Message=There are multiple .NET runtimes present, so a default dispatcher could not be resolved. Use DotNetObject to invoke .NET instance methods.
Error: There are multiple .NET runtimes present, so a default dispatcher could not be resolved. Use DotNetObject to invoke .NET instance methods.
    at v (https://localhost:44307/_framework/blazor.web.js:1:2037)
    at e.invokeMethodAsync (https://localhost:44307/_framework/blazor.web.js:1:2428)
    at Object.lightweightChartsInvoke (https://localhost:44307/_content/LightweightCharts.Blazor/lightweight-charts.scripts.js:19:45)
    at https://localhost:44307/_framework/blazor.web.js:1:3244
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (https://localhost:44307/_framework/blazor.web.js:1:3201)
    at fn._invokeClientMethod (https://localhost:44307/_framework/blazor.web.js:1:62541)
    at fn._processIncomingData (https://localhost:44307/_framework/blazor.web.js:1:60016)
    at connection.onreceive (https://localhost:44307/_framework/blazor.web.js:1:53657)
    at i.onmessage (https://localhost:44307/_framework/blazor.web.js:1:81802)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at LightweightCharts.Blazor.Charts.ChartComponent.<JavascriptInvokeAsync>d__53`1.MoveNext() in C:\Projects\GSL.CryptoHunter\LightweightCharts.Blazor\Charts\ChartComponent.cs:line 436
   at LightweightCharts.Blazor.Charts.ChartComponent.<Options>d__38.MoveNext() in C:\Projects\GSL.CryptoHunter\LightweightCharts.Blazor\Charts\ChartComponent.cs:line 287
   at BlazorApp1.Components.Pages.CandlestickSeries.<InitializeChartComponent>d__13.MoveNext() in C:\Projects\GSL.CryptoHunter\BlazorApp1\BlazorApp1\Components\Pages\CandlestickSeries.razor.cs:line 96
```
Regards,
Glenn  

### Exceptions (if any)

Microsoft.JSInterop.JSException
  HResult=0x80131500
  Message=There are multiple .NET runtimes present, so a default dispatcher could not be resolved. Use DotNetObject to invoke .NET instance methods.
Error: There are multiple .NET runtimes present, so a default dispatcher could not be resolved. Use DotNetObject to invoke .NET instance methods.
    at v (https://localhost:44307/_framework/blazor.web.js:1:2037)
    at e.invokeMethodAsync (https://localhost:44307/_framework/blazor.web.js:1:2428)
    at Object.lightweightChartsInvoke (https://localhost:44307/_content/LightweightCharts.Blazor/lightweight-charts.scripts.js:19:45)
    at https://localhost:44307/_framework/blazor.web.js:1:3244
    at new Promise (<anonymous>)
    at y.beginInvokeJSFromDotNet (https://localhost:44307/_framework/blazor.web.js:1:3201)
    at fn._invokeClientMethod (https://localhost:44307/_framework/blazor.web.js:1:62541)
    at fn._processIncomingData (https://localhost:44307/_framework/blazor.web.js:1:60016)
    at connection.onreceive (https://localhost:44307/_framework/blazor.web.js:1:53657)
    at i.onmessage (https://localhost:44307/_framework/blazor.web.js:1:81802)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at LightweightCharts.Blazor.Charts.ChartComponent.<JavascriptInvokeAsync>d__53`1.MoveNext() in C:\Projects\GSL.CryptoHunter\LightweightCharts.Blazor\Charts\ChartComponent.cs:line 436
   at LightweightCharts.Blazor.Charts.ChartComponent.<Options>d__38.MoveNext() in C:\Projects\GSL.CryptoHunter\LightweightCharts.Blazor\Charts\ChartComponent.cs:line 287
   at BlazorApp1.Components.Pages.CandlestickSeries.<InitializeChartComponent>d__13.MoveNext() in C:\Projects\GSL.CryptoHunter\BlazorApp1\BlazorApp1\Components\Pages\CandlestickSeries.razor.cs:line 96

### .NET Version

8

**Comment by javiercn** [comment]
@codehunter13 thanks for contacting us.

You have multiple runtimes running on the page, server and webassembly. Your library is using the global `DotNet` on `window` to invoke methods on .NET (probably static methods). That pattern is incompatible with scenarios where server and runtime are running on the same page (as the global DotNet object would not know if the call needs to go to the server runtime or to the webassembly runtime).

In this situation the recommendation is that as the library boots, it creates from .NET a dotnet object reference and sends that to JS so that JS can call back into the right .net runtime.

/cc: @MackinnonBuck

**Comment by codehunter13** [comment]
Thx for the fast response.
Do you have an example of what you exactly mean?
