### ISSUE TITLE
When using UseStaticFiles, AspNetCore does not call CreateReadStream to get a stream to return via http but rather uses the PhysicalPath to create it's own stream.

### ISSUE THREAD

**Issue by erikrenaud** [dotnet/aspnetcore#53425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

ASPNetCore ignoring the stream i am exposing in IFileInfo when SendFileRepsonseExtensions.SendFileAsyncCore(HttpResponse, IFileInfo...) is used and using the PhysicalPath.

         at Microsoft.AspNetCore.Http.SendFileFallback.SendFileAsync(Stream destination, **String filePath**, Int64 offset, Nullable`1 count, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Http.SendFileResponseExtensions.SendFileAsyncCore(HttpResponse response, **String fileName**, Int64 offset, Nullable`1 count, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Http.SendFileResponseExtensions.SendFileAsyncCore(HttpResponse response, **IFileInfo file**, Int64 offset, Nullable`1 count, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.StaticFiles.StaticFileContext.SendAsync()
         at Microsoft.AspNetCore.StaticFiles.StaticFileContext.ServeStaticFile(HttpContext context, RequestDelegate next)

### Expected Behavior

If use provide my own IFileProvider in the options for UseStaticFiles, I expect ASPNETCore to return the stream that i am exposing and not create it's own using the PhysicalPath.

### .NET Version

8.0.101

**Comment by erikrenaud** [comment]
> This is intended, there are scenarios where it's faster to tell the OS to transmit the file from disk than to copy from the stream. If you don't want the physical path to be used then don't provide one.


In my case - i was altering some files (replacing tokens and caching) for the StaticFilesMiddleware.

I am totally fine with this answer, but:

1 - If ASPNETCore is going to use the PhysicalFileName to transfer the file itself, should it not ignore the IFIleInfo.Length value and use the real one from the PhysicalDisk ? I came onto this issue when only "parts" of the unaltered file were transferred to the caller.
2 - How can this be documented correctly for future me ? because i had to go and read the code to find out... (bravo for having easy to read code !)

**Comment by Tratcher** [comment]
Hmm, the IFileInfo.Length normally is the value from the physical disk. We've never needed to distinguish before, and changing it now would be breaking.

Yes, this is a good opportunity to clarify some the docs.
