### ISSUE TITLE
WebSocketException due to a handshake problem between client and server in Blazor Server App

### ISSUE THREAD

**Issue by ozdmro** [dotnet/aspnetcore#53498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am working on a Blazor Server App based chat web application with .net 8.0.1 but keep getting "System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '200' when status code '101' was expected." when opening the Chat.razor component.

### Expected Behavior

Websocket works.

### Steps To Reproduce

The server looks like:
```
internal class Program
{
    private static void Main(string[] args)
    {
        var builder = WebApplication.CreateBuilder(args);
        // Add services to the container.
        builder.Services.AddRazorComponents().AddInteractiveServerComponents();
        builder.Services.AddSignalR().AddHubOptions<ChatHub>(hubOptions =>
        {
            hubOptions.EnableDetailedErrors = true;
        })
        .AddMessagePackProtocol();
        builder.Services.AddResponseCompression(options =>
        {
            options.MimeTypes = ResponseCompressionDefaults.MimeTypes.Concat(
               ["application/octet-stream"]);
        });

        var app = builder.Build();

        // Configure the HTTP request pipeline.
        if (app.Environment.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }
        else
        {
            app.UseResponseCompression();
            app.UseExceptionHandler("/Error", createScopeForErrors: true);
            // The default HSTS value is 30 days.
            // You may want to change this for production scenarios,
            // see https://aka.ms/aspnetcore-hsts.
            app.UseHsts();
        }
        app.UseHttpsRedirection();
        app.UseStaticFiles();
        app.UseRouting();
        app.UseAntiforgery();
        app.MapRazorComponents<App>().AddInteractiveServerRenderMode();
        app.MapHub<ChatHub>(ChatHub.HubUrl, options =>
        {
            options.AllowStatefulReconnects = true;
        });

        app.Run();
    }
}

```
And the hub connection in the Chat.razor is as the following:

```
protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (!firstRender)
        { 
            return;
        }

        try
        {
            hubConnection = new HubConnectionBuilder()
            .WithUrl(navigationManager.ToAbsoluteUri(LoupeAi.Hubs.ChatHub.HubUrl))
            .WithStatefulReconnect()
            .AddMessagePackProtocol()
            .ConfigureLogging(logging =>
            {
                logging.AddConsole();
            })
            .WithAutomaticReconnect()
            .Build();

            hubConnection.On<string, string>("ReceiveMessage", BroadcastMessage);

            await hubConnection.StartAsync();
        }
        catch (Exception e)
        {
            message = $"ERROR: {e.Message}";
        }
    }
```

### Exceptions (if any)

```
      Starting transport. Transfer mode: Binary. Url: 'ws://localhost:3198/chat?id=1sqv7tJVb13ueTWQy24hPA'.
fail: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[11]
      Failed to start connection. Error starting transport 'WebSockets'.
      System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '200' when status code '101' was expected.
         at System.Net.WebSockets.WebSocketHandle.ValidateResponse(HttpResponseMessage response, String secValue)
         at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken, ClientWebSocketOptions options)
         at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.DefaultWebSocketFactory(WebSocketConnectionContext context, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport.StartAsync(Uri url, TransferFormat transferFormat, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartTransport(Uri connectUrl, HttpTransportType transportType, TransferFormat transferFormat, CancellationToken cancellationToken, Boolean useStatefulReconnect)
info: Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport[1]
      Starting transport. Transfer mode: Binary.
info: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[3]
      HttpConnection Started.
info: Microsoft.AspNetCore.SignalR.Client.HubConnection[24]
      Using HubProtocol 'messagepack v1'.
warn: Microsoft.AspNetCore.Http.Connections.Client.Internal.LoggingHttpMessageHandler[2]
      Unsuccessful HTTP response BadRequest return from POST 'http://localhost:3198/chat?id=V1BL1Glq2IhQmkFKPeK0RQ'.
fail: Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport[106]
      Error while sending to 'http://localhost:3198/chat?id=V1BL1Glq2IhQmkFKPeK0RQ'.
      System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at Microsoft.AspNetCore.Http.Connections.Client.Internal.SendUtils.SendMessages(Uri sendUrl, IDuplexPipe application, HttpClient httpClient, ILogger logger, CancellationToken cancellationToken)
fail: Microsoft.AspNetCore.SignalR.Client.HubConnection[35]
      The underlying connection closed while processing the handshake response. See exception for details.
      System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at Microsoft.AspNetCore.Http.Connections.Client.Internal.SendUtils.SendMessages(Uri sendUrl, IDuplexPipe application, HttpClient httpClient, ILogger logger, CancellationToken cancellationToken)
         at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
         at System.IO.Pipelines.Pipe.GetReadAsyncResult()
         at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
         at Microsoft.AspNetCore.SignalR.Client.HubConnection.HandshakeAsync(ConnectionState startingConnectionState, Int32 protocolVersion, CancellationToken cancellationToken)
fail: Microsoft.AspNetCore.SignalR.Client.HubConnection[43]
      Error starting connection.
      System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at Microsoft.AspNetCore.Http.Connections.Client.Internal.SendUtils.SendMessages(Uri sendUrl, IDuplexPipe application, HttpClient httpClient, ILogger logger, CancellationToken cancellationToken)
         at System.IO.Pipelines.Pipe.GetReadResult(ReadResult& result)
         at System.IO.Pipelines.Pipe.GetReadAsyncResult()
         at System.IO.Pipelines.Pipe.DefaultPipeReader.GetResult(Int16 token)
         at Microsoft.AspNetCore.SignalR.Client.HubConnection.HandshakeAsync(ConnectionState startingConnectionState, Int32 protocolVersion, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
warn: Microsoft.AspNetCore.Http.Connections.Client.Internal.LoggingHttpMessageHandler[2]
      Unsuccessful HTTP response BadRequest return from DELETE 'http://localhost:3198/chat?id=V1BL1Glq2IhQmkFKPeK0RQ'.
info: Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport[6]
      Transport is stopping.
fail: Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport[13]
      Error sending DELETE request to 'http://localhost:3198/chat?id=V1BL1Glq2IhQmkFKPeK0RQ'.
      System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at Microsoft.AspNetCore.Http.Connections.Client.Internal.LongPollingTransport.SendDeleteRequest(Uri url)
info: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[6]
      HttpConnection Disposed.
```

### .NET Version

.net 8.0.1

**Comment by BrennanConroy** [comment]
Turn on server logs.

**Comment by ozdmro** [comment]
> Turn on server logs.

Could you please tell me how to do that? I'm running the app via VS Code on Mac. Is it something that I can get from VS Code Output view? Or maybe Terminal view?

**Comment by BrennanConroy** [comment]
> Is it something that I can get from VS Code Output view? Or maybe Terminal view?

Probably, but I wouldn't be able to say for sure. Worst case you can just `dotnet run` from the command line and see console output.
https://learn.microsoft.com/aspnet/core/signalr/diagnostics?view=aspnetcore-8.0#server-side-logging

**Comment by ozdmro** [comment]
Thanks for the hint.

It turned out that the Hub URL I use for the Chat.razor component caused a conflict with the href value I use in another razor component. Just changing the Hub URL fixed the issue. Closing this ticket.
