### ISSUE TITLE
DisposeAsync is called too late on page change?

### ISSUE THREAD

**Issue by TheRealRolandDeschain** [dotnet/aspnetcore#53511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Wondering if this is a bug, or working as expected (In which case, I am wondering how to deal with the following setup). 

I have a java script file handling file drops for the upload page in my blazor webassembly application, which is invoked as follows on page load:

```
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            _jsFileDropperObject = await JSRuntime.InvokeAsync<IJSObjectReference>("import", "./js/FileDropper.js");
            await _jsFileDropperObject.InvokeVoidAsync("initializeDropZone");
        }
        await base.OnAfterRenderAsync(firstRender);
    }
```

The javascript code consists of many things, but most importantly, I have to functions to set up all the necessary DOM events: 
- `initializeDropZone`: which is called in the code above on load and adds all the needed event listeners in java script
- `deInitializeDropZone`: which should remove/cleanup the event listeners. This would be called in my Dispose function as follows: 

```
  public async ValueTask DisposeAsync()
  {
        if (_jsFileDropperObject is not null)
        {
            await _jsFileDropperObject.InvokeVoidAsync("deInitializeDropZone");
            await _jsFileDropperObject.DisposeAsync();
        }
      GC.SuppressFinalize(this); // prevent CA1816 warning
  }
```

The problem arises when the page is changed. The `DisposeAsync()` Method seems to be called when the new page is already being loaded (hard to say, I get quite some delay when putting breakpoints). This then seems to mean that needed references for the JS interoperability are missing (see exception below). 

### Expected Behavior

Call DisposeAsync() before the current page is destroyed, so everything can be cleaned up correctly. 

### Steps To Reproduce

Not much needed, just a razor page with the functions described above. The two JS functions mentioned above just need a `div` (or any other container) with `id="dropZone"` and an `<InputFile/>` inside. The look as follows:

```
export function initializeDropZone() {
    dropZoneElement = document.getElementById("dropZone");

    if (dropZoneElement == null) {
        console.log("No drop zone found!");
        return;
    }

    // Register all events
    window.addEventListener("drop", onWindowDrop, false);
    window.addEventListener("dragover", onWindowDragOver, false);

    dropZoneElement.addEventListener("dragover", onDragHover);
    dropZoneElement.addEventListener("dragenter", onDragEnter);
    dropZoneElement.addEventListener("dragleave", onDragLeave);
    dropZoneElement.addEventListener("drop", onDrop);
    dropZoneElement.addEventListener('paste', onPaste);
    inputFile = dropZoneElement.getElementsByTagName('input')[0];
}

export function deInitializeDropZone() {
    dropZoneElement = document.getElementById("dropZone");
    if (dropZoneElement == null) {
        return;
    }

    window.removeEventListener("drop", onWindowDrop, false);
    window.removeEventListener("dragover", onWindowDragOver, false);

    dropZoneElement.removeEventListener("dragover", onDragHover);
    dropZoneElement.removeEventListener("dragenter", onDragEnter);
    dropZoneElement.removeEventListener("dragleave", onDragLeave);
    dropZoneElement.removeEventListener("drop", onDrop);
    dropZoneElement.removeEventListener('paste', onPaste);
}
```

### Exceptions (if any)

```
Uncaught Error Error: System.ArgumentException: There is no tracked object with id '4'. Perhaps the DotNetObjectReference instance was already disposed. (Parameter 'dotNetObjectId')
    at endInvokeDotNetFromJS (localhost꞉7257/_framework/blazor.webassembly.js:1:3136)
    at bn (localhost꞉7257/_framework/blazor.webassembly.js:1:58983)
    at <anonymous> (c:\path_to_project\wwwroot\_framework\https:\raw.githubusercontent.com\dotnet\runtime\bf5e279d9239bfef5bb1b8d6212f1b971c434606\src\mono\wasm\runtime\invoke-js.ts:233:31)
    at Ul (c:\path_to_project\wwwroot\_framework\https:\raw.githubusercontent.com\dotnet\runtime\bf5e279d9239bfef5bb1b8d6212f1b971c434606\src\mono\wasm\runtime\invoke-js.ts:276:5)
    at $func350 (wasm/00b1ee2e:1:129776)
    at $func246 (wasm/00b1ee2e:1:114573)
    at $func239 (wasm/00b1ee2e:1:61812)
    at $func273 (wasm/00b1ee2e:1:119218)
    at $func3185 (wasm/00b1ee2e:1:950699)
    at $func2506 (wasm/00b1ee2e:1:778076)
    at $func2512 (wasm/00b1ee2e:1:780125)
    at $func2536 (wasm/00b1ee2e:1:789940)
    at $mono_wasm_invoke_method_bound (wasm/00b1ee2e:1:42279)
    at Module._mono_wasm_invoke_method_bound (localhost꞉7257/_framework/dotnet.native.8.0.1.3b2l57ob3v.js:8:123482)
    at kr (c:\path_to_project\wwwroot\_framework\https:\raw.githubusercontent.com\dotnet\runtime\bf5e279d9239bfef5bb1b8d6212f1b971c434606\src\mono\wasm\runtime\invoke-cs.ts:273:29)
    at <anonymous> (c:\path_to_project\wwwroot\_framework\https:\raw.githubusercontent.com\dotnet\runtime\bf5e279d9239bfef5bb1b8d6212f1b971c434606\src\mono\wasm\runtime\invoke-cs.ts:247:13)
    at beginInvokeDotNetFromJS (localhost꞉7257/_framework/blazor.webassembly.js:1:45148)
    at invokeDotNetMethodAsync (localhost꞉7257/_framework/blazor.webassembly.js:1:3956)
    at invokeDotNetStaticMethodAsync (localhost꞉7257/_framework/blazor.webassembly.js:1:3324)
    at <anonymous> (localhost꞉7257/_framework/blazor.webassembly.js:1:56212)
    at <anonymous> (localhost꞉7257/_framework/blazor.webassembly.js:1:32131)
    at He (localhost꞉7257/_framework/blazor.webassembly.js:1:32077)
    at xe (localhost꞉7257/_framework/blazor.webassembly.js:1:31645)
    at <anonymous> (localhost꞉7257/_framework/blazor.webassembly.js:1:22272)
    at <anonymous> (localhost꞉7257/_framework/blazor.webassembly.js:1:22286)
    at <anonymous> (localhost꞉7257/_framework/blazor.webassembly.js:1:14961)
    at onGlobalEvent (localhost꞉7257/_framework/blazor.webassembly.js:1:14949)
```

### .NET Version

8.0.101

**Comment by MariovanZeist** [comment]
Hi @TheRealRolandDeschain 

To clean up your Javascript code when a component (or page) is destroyed it might be a better idea to use the ``MutationObserver`` pattern. 

You can find more information here: https://learn.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/?view=aspnetcore-8.0#dom-cleanup-tasks-during-component-disposal

**Comment by TheRealRolandDeschain** [comment]
@MariovanZeist nice this looks exactly what I was looking for at first glance. I'll check it out in detail on monday and get back or close this issue directly if possible. Thanks again, I was searching for a few hourse, but my google-foo let me down today :)

**Comment by javiercn** [comment]
@TheRealRolandDeschain thanks for contacting us.

This is by design. Components can only get disposed after the new render has completed on the client and "OnAfterRender" has triggered.

The suggestion from @MariovanZeist is correct, and using a MutationObserver is the way to go here.
