### ISSUE TITLE
IConfiguration binding fails or returns erroneous data

### ISSUE THREAD

**Issue by Jack-Edwards** [dotnet/aspnetcore#53659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using .NET 8.0 and WebApplicationFactory, I am encountering some really unexpected results when trying to pull data back from the IConfiguration.

Depending on the keys I use in my `appsettings.Test.json` file, I either:

- Encounter an exception during application startup as I attempt to bind a variable to some information in my configuration, using a C# class as a data model.
- Do not encounter an exception, the application starts up fine, but the data assigned to my variable is erroneous and does not reflect what is in any of my `appsettings.json` files.

### Expected Behavior

I would expect the information in the `appsettings.Test.json` file to be bound without exception.

I would also expect the information coming from my `appsettings.json` to be bound correctly and faithfully, without erroneous data.

### Steps To Reproduce

https://github.com/Jack-Edwards/IConfigurationBoogaloo

The solution contains a single unit test.  Running the unit test without modification will elicit the first scenario, where an exception is thrown during application startup.

Rename the `MyGarden` key in `appsettings.Test.json` to elicit the second scenario, where information from `appsettings.json` is pulled, but unfaithfully.  The list assigned  to `myGarden` on line 5 of `Program.cs` contains duplicate entries.

### Exceptions (if any)

System.ArgumentException: Object of type 'System.String' cannot be converted to type 'System.Collections.Generic.List`1[WebApplication1.Flower]'.
   at System.RuntimeType.CheckValue(Object& value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.CreateInstance(Type type, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, BindingPoint bindingPoint, IConfiguration config, BinderOptions options, Boolean isParentCollection)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Get(IConfiguration configuration, Type type, Action`1 configureOptions)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Get[T](IConfiguration configuration, Action`1 configureOptions)
   at Program.<Main>$(String[] args) in C:\Users\Jack\source\repos\WebApplication1\WebApplication1\Program.cs:line 5
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)

### .NET Version

8.0.100

**Comment by Jack-Edwards** [comment]
I can resolve the erroneous data in the second scenario by removing the constructors from my configuration data models.  The List<T> will contain the correct entries.

```
public class GardenSettings
{
    public short Staff { get; init; }
    public List<Flower> Flowers { get; init; }
}

public class Flower
{
    public bool Perennial { get; init; }
    public string Color { get; init; }
}
```

**Comment by MariovanZeist** [comment]
Hi @Jack-Edwards 
I suspect this is a bug in the framework. I tried several things and got some funky results.

@javiercn I think this should be transferred to Dotnet/Runtime as it seems to be an issue with ``IOptions``

It should work with the constructors you have (it used to only work with parameterless constructors but that changed in ``net7.0``)

```cs
public class GardenSettings
{
    public int Staff { get; init; }
    public List<Flower> Flowers { get; init; }
}

public class Flower
{
    public bool Perennial { get; init; }
    public string Color { get; init; }
}
```
This results in the correct data.

But the following
```cs
public class GardenSettings
{
    public int Staff { get; init; }
    public List<Flower> Flowers { get; init; }
  
    public GardenSettings(int staff, List<Flower> flowers)
    {
      Staff = staff;
      Flowers = flowers;
    }
}

public class Flower
{
    public bool Perennial { get; init; }
    public string Color { get; init; }
}
```

This will result in 4 flowers

It seems that after creating the initial GardenSettings through its constructor, it still tries to bind to `` List<Flower> Flowers``  again
[Here](https://github.com/dotnet/runtime/blob/0f70e9aa5f08847680162a6dc712e069f0334b52/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L421)

This results in looping through its children twice so you end up with double data.

**Comment by Yawnder** [comment]
I might be wrong, but I think the issue has two parts. (This post only addresses one of them: The problem when there is a 
 constructor on the `Flower` class.)
 
If you remove the constructor for the list and only leave the constructor for the `Flower` class, you end up with a list with only one flower. The reason is because there is a typo in the configuration file for the 2nd flower (Perenniel vs Perennial) and it doesn't match the constructor of `Flower`.
An exception is thrown (`System.InvalidOperationException: 'Cannot create instance of type 'WebApplication1.Flower' because parameter 'perennial' has no matching config.`) but it doesn't surface since `.Get<GardenSettings>()` isn't passing the option to 
Since `WebApplication.CreateBuilder(args);` adds the configuration files with the option `ErrorOnUnknownConfiguration == true`)
I'd think that behavior is by design.

**Comment by MariovanZeist** [comment]
Might be a duplicate of https://github.com/dotnet/runtime/issues/83803

**Comment by svick** [comment]
This seems to be a duplicate of https://github.com/dotnet/runtime/issues/126312 for the exception and of https://github.com/dotnet/runtime/issues/129760 / https://github.com/dotnet/runtime/issues/83803 for the duplicated items. All of these are fixed in .Net 11, so I'm closing this issue.

cc: @dotnet/area-extensions-configuration
