### ISSUE TITLE
[Blazor SSR] Issue with NavigationManager.NavigateTo and Already Percent-Encoded URLs

### ISSUE THREAD

**Issue by JeepNL** [dotnet/aspnetcore#53708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**Note:** maybe this issue is already fixed with https://github.com/dotnet/aspnetcore/issues/53138, https://github.com/dotnet/aspnetcore/pull/53470 but I can't tell. If it is fixed, you can of course close this issue directly. 

In Blazor applications, specifically when using Server Side Rendering (SSR) with .NET 8, I've encountered an issue where `NavigationManager.NavigateTo` does not correctly handle navigation when provided with already percent-encoded URLs.

### Expected Behavior

`NavigationManager.NavigateTo` should correctly handle already percent-encoded URLs, allowing for successful navigation without errors.

### Steps To Reproduce

Create a Blazor Server Side Rendering application using .NET 8.
Attempt to use NavigationManager.NavigateTo to navigate to a URL that contains percent-encoded characters (e.g., `https://www.nvj.nl/nieuws/offici%C3%ABle-waarschuwing-zonder-wederhoor-mag`).
Observe that the navigation does not work as expected, and an error is thrown.

### Exceptions (if any)

```
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint '/ext/{text} (/ext/{text})'
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: Invalid non-ASCII or control character in header: 0x00EB
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowInvalidHeaderCharacter(Char ch)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ValidateHeaderValueCharacters(String headerCharacters, Boolean requireAscii)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ValidateHeaderValueCharacters(String headerName, StringValues headerValues, Func`2 encodingSelector)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseHeaders.Microsoft.AspNetCore.Http.IHeaderDictionary.set_Location(StringValues value)
         at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.HandleNavigationException(HttpContext httpContext, NavigationException navigationException)
         at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.RenderEndpointComponent(HttpContext httpContext, Type rootComponentType, ParameterView parameters, Boolean waitForQuiescence)
         at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
         at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
         at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<<InvokeAsync>b__10_0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.HttpLogging.W3CLoggingMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatcher|10_0(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task`1 matcherTask)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### .NET Version

8.0.200-preview.23624.5

**Comment by MackinnonBuck** [comment]
Hi @JeepNL, this is getting fixed by https://github.com/dotnet/aspnetcore/pull/53623, which will be included in one of the upcoming .NET 8 servicing release. I'm going to close out this issue, but we can reopen it if we get feedback that the issue persists. Thanks!
