### ISSUE TITLE
Invalid List Of Components when using "required" keyword

### ISSUE THREAD

**Issue by Westboldyi** [dotnet/aspnetcore#53742]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Invalid list of component error when cascading a parameter that has the "required" keyword:

![image](https://github.com/dotnet/aspnetcore/assets/112659411/85e57b41-431c-4fc7-acca-7405440996c0)

Middleware that populates some state:
```
public class AppStateMiddleware
{
    private readonly RequestDelegate _next;

    public AppStateMiddleware(RequestDelegate next)
    {
        _next = next;
    }

    public async Task InvokeAsync(HttpContext context)
    {
        var appState = new InitialApplicationState()
        {
            ValueA = "aaa",
            ValueB = null,
            ValueC = null

        };
        var initialAppStateProvider = context.RequestServices.GetRequiredService<InitialApplicationStateProvider>();
        initialAppStateProvider.AppState = appState;

        await _next(context);
    }
}
```

App.razor getting the state provider and passing it into the Routes.razor:
```
@inject InitialApplicationStateProvider AppStateProvider

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <base href="/" />
    <link rel="stylesheet" href="bootstrap/bootstrap.min.css" />
    <link rel="stylesheet" href="app.css" />
    <link rel="stylesheet" href="BlazorApp11.styles.css" />
    <link rel="icon" type="image/png" href="favicon.png" />
    <HeadOutlet @rendermode="InteractiveServer" />
</head>

<body>
    <Routes @rendermode="InteractiveServer" InitialAppState="@AppStateProvider.AppState" />
    <script src="_framework/blazor.web.js"></script>
</body>

</html>
```

Routes.razor making the appState available as a cascading parameter:

```
<CascadingValue Value="InitialAppState" IsFixed=true>

<Router AppAssembly="typeof(Program).Assembly">
    <Found Context="routeData">
        <RouteView RouteData="routeData" DefaultLayout="typeof(Layout.MainLayout)" />
        <FocusOnNavigate RouteData="routeData" Selector="h1" />
    </Found>
</Router>
</CascadingValue>



@code
{
    [Parameter, EditorRequired] public InitialApplicationState? InitialAppState { get; set; }
}
```

Scoped AppStateProvider:
```
    public class InitialApplicationStateProvider
    {
        public InitialApplicationState? AppState { get; set; }
    }

```

AppState class that causes an issue:
```
    public class InitialApplicationState
    {
        public required string? ValueA { get; set; }
        public required string? ValueB { get; set; }
        public required string? ValueC { get; set; }
    }
```

AppState class that's fine:
```
    public class InitialApplicationState
    {
        public string? ValueA { get; set; }
        public string? ValueB { get; set; }
        public string? ValueC { get; set; }
    }
```

### Expected Behavior

The appstate should be made available to all child components.

### Steps To Reproduce

Reproduction: 

https://github.com/Westboldyi/InvalidListOfComponents

### .NET Version

8

**Comment by javiercn** [comment]
@Westboldyi thanks for contacting us.

Turn on first chance exceptions, it's likely a serialization/deserialization issue of your component parameters.

**Comment by Westboldyi** [comment]
All exceptions are on, enabling DetailedErrors doesn't reveal any more info. I don't think it's a serialization issue since the following runs fine and serializes/deserializes properly:

![image](https://github.com/dotnet/aspnetcore/assets/112659411/03561829-2c96-4e01-9358-92007694653d)


![image](https://github.com/dotnet/aspnetcore/assets/112659411/293ffe05-fd57-4454-b901-4e2f1d07106a)

**Comment by javiercn** [comment]
It's a serialization issue.

```
System.Text.Json.JsonException
  HResult=0x80131500
  Message=JSON deserialization for type 'BlazorApp11.Client.InitialApplicationState' was missing required properties, including the following: valueB, valueC
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ThrowJsonException_JsonRequiredPropertyMissing(JsonTypeInfo parent, BitArray requiredPropertiesSet)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
```
```    System.Text.Json.ThrowHelper.ThrowJsonException_JsonRequiredPropertyMissing(System.Text.Json.Serialization.Metadata.JsonTypeInfo, System.Collections.BitArray)
    System.Text.Json.Serialization.Converters.ObjectDefaultConverter<T>.OnTryRead(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack, out T)
    System.Text.Json.Serialization.JsonConverter<T>.TryRead(ref System.Text.Json.Utf8JsonReader, System.Type, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack, out T, out bool)
    System.Text.Json.Serialization.JsonConverter<T>.ReadCore(ref System.Text.Json.Utf8JsonReader, System.Text.Json.JsonSerializerOptions, ref System.Text.Json.ReadStack)
```

**Comment by javiercn** [comment]
![image](https://github.com/dotnet/aspnetcore/assets/6995051/022f0cc5-009c-4a9d-94c5-9c5ac225392f)

**Comment by javiercn** [comment]
Providing the values in your middleware makes it work fine.

        var appState = new InitialApplicationState()
        {
            ValueA = "aaa",
            ValueB = "bbb",
            ValueC = "ccc"

        };

**Comment by Westboldyi** [comment]
Thanks for the clarification. Is the Blazor JsonSerializer's options from System.Text.Json? How come it didn't throw when just using STJ serialize/deserialze in user-land code?
