### ISSUE TITLE
UseExceptionHandler does not work with PublishAot

### ISSUE THREAD

**Issue by odebastiani** [dotnet/aspnetcore#53764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I used this code sample from [How to handle errors in Minimal API apps](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/handle-errors?view=aspnetcore-8.0#exception-handler) to handle exceptions:

```
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

app.UseExceptionHandler(exceptionHandlerApp 
    => exceptionHandlerApp.Run(async context 
        => await Results.Problem()
                     .ExecuteAsync(context)));

app.MapGet("/exception", () => 
{
    throw new InvalidOperationException("Sample Exception");
});

app.MapGet("/", () => "Test by calling /exception");

app.Run();
```

I used the default `.csproj` configuration:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
```

When I run that in Visual Studio 2022 in Debug mode by using an `.http` file, I get the following result, which is what I would expect:
```
application/problem+json, 133 bytes
```
```
{
  "type": "https://tools.ietf.org/html/rfc9110#section-15.6.1",
  "title": "An error occurred while processing your request.",
  "status": 500
}
```

Then I activate `PublishAot` in the project file:
```
<PublishAot>true</PublishAot>
```

The same code (still executed in Visual Studio with Debug mode) is returning a different, wrong result, even though the error handling is executed:
```
text/plain; charset=utf-8, 1199 bytes
```
```
System.InvalidOperationException: Sample Exception
   at Program.<>c.<<Main>$>b__0_1() in C:\...\Program.cs:line 11
   at Microsoft.AspNetCore.Http.Generated.<GeneratedRouteBuilderExtensions_g>F69328E0708B4B584C5AACA22FE2C51A1CF192D6622828F613FC57C583CA77B63__GeneratedRouteBuilderExtensionsCore.<>c__DisplayClass2_0.<MapGet0>g__RequestHandler|4(HttpContext httpContext) in C:\...\Microsoft.AspNetCore.Http.RequestDelegateGenerator\Microsoft.AspNetCore.Http.RequestDelegateGenerator.RequestDelegateGenerator\GeneratedRouteBuilderExtensions.g.cs:line 111
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.Invoke(HttpContext context)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

HEADERS
=======
Accept: application/json
Host: localhost:5227
traceparent: 00-2ba4b74f10cc7a077ce3f1fcb7726e04-bb1f34822d8e94c3-00
```

The generated code does somehow ignore the error handling and I won't see a warning. This could be dangerous, because the stack trace is returned.

The exception handling is also ignored when the `errorHandlingPath` overload is used:
```
app.UseExceptionHandler("/Error");
```

### Expected Behavior

`UseExceptionHandler` should return the same result with `PublishAot` activated and deactivated.

### Steps To Reproduce

See above.

### .NET Version

net8.0

**Comment by odebastiani** [comment]
Hey @takashiuesaka 

Thanks for the update. Yes, this is correct solution and much nicer than my workaround.
