### ISSUE TITLE
Blazor Web interactive Server Editor throws error

### ISSUE THREAD

**Issue by davhdavh** [dotnet/aspnetcore#53812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

home.razor:
`<BugComponent @bind-Value="I1"/>`

BugComponent.razor:
```
@inherits Editor<MyModel>
@rendermode InteractiveServer

<InputText @bind-Value="@Value.Name"></InputText>
```

MyModel.cs
```
public class MyModel
{
 public string? Name { get; set; }
}
```

### Expected Behavior

page shown with interactiveness enabled for the InputText

### Steps To Reproduce

See above

### Exceptions (if any)
```
System.NotSupportedException: Serialization and deserialization of 'System.Type' instances is not supported. Path: $.ParameterValues.Type.

 ---> System.NotSupportedException: Serialization and deserialization of 'System.Type' instances is not supported.

   at System.Text.Json.Serialization.Converters.UnsupportedTypeConverter`1.Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)

   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)

   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)

   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)

   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)

   at System.Text.Json.Serialization.JsonConverter`1.TryWriteAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)

   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)

   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)

   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)

   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)

   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)

   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)

   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)

   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)

   --- End of inner exception stack trace ---

   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(WriteStack& state, NotSupportedException ex)

   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)

   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Serialize(Utf8JsonWriter writer, T& rootValue, Object rootValueBoxed)

   at System.Text.Json.JsonSerializer.WriteBytes[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo)

   at System.Text.Json.JsonSerializer.SerializeToUtf8Bytes[TValue](TValue value, JsonSerializerOptions options)

   at Microsoft.AspNetCore.Components.Endpoints.ServerComponentSerializer.CreateSerializedServerComponent(ServerComponentInvocationSequence invocationId, Type rootComponent, ParameterView parameters, Nullable`1 key)

   at Microsoft.AspNetCore.Components.Endpoints.SSRRenderModeBoundary.ToMarker(HttpContext httpContext, Int32 sequence, Object componentKey)

   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.WriteComponentHtml(Int32 componentId, TextWriter output, Boolean allowBoundaryMarkers, SequenceAndKey sequenceAndKey)

   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.RenderChildComponent(TextWriter output, RenderTreeFrame& componentFrame)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.RenderCore(Int32 componentId, TextWriter output, ArrayRange`1 frames, Int32 position)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.WriteComponentHtml(Int32 componentId, TextWriter output)

   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.WriteComponentHtml(Int32 componentId, TextWriter output, Boolean allowBoundaryMarkers, SequenceAndKey sequenceAndKey)

   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.RenderChildComponent(TextWriter output, RenderTreeFrame& componentFrame)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.RenderCore(Int32 componentId, TextWriter output, ArrayRange`1 frames, Int32 position)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.RenderFrames(Int32 componentId, TextWriter output, ArrayRange`1 frames, Int32 position, Int32 maxElements)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.RenderCore(Int32 componentId, TextWriter output, ArrayRange`1 frames, Int32 position)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.RenderFrames(Int32 componentId, TextWriter output, ArrayRange`1 frames, Int32 position, Int32 maxElements)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.RenderElement(Int32 componentId, TextWriter output, ArrayRange`1 frames, Int32 position)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.RenderCore(Int32 componentId, TextWriter output, ArrayRange`1 frames, Int32 position)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.RenderFrames(Int32 componentId, TextWriter output, ArrayRange`1 frames, Int32 position, Int32 maxElements)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.RenderElement(Int32 componentId, TextWriter output, ArrayRange`1 frames, Int32 position)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.RenderCore(Int32 componentId, TextWriter output, ArrayRange`1 frames, Int32 position)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.RenderFrames(Int32 componentId, TextWriter output, ArrayRange`1 frames, Int32 position, Int32 maxElements)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.RenderElement(Int32 componentId, TextWriter output, ArrayRange`1 frames, Int32 position)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.RenderCore(Int32 componentId, TextWriter output, ArrayRange`1 frames, Int32 position)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.WriteComponentHtml(Int32 componentId, TextWriter output)

   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.WriteComponentHtml(Int32 componentId, TextWriter output, Boolean allowBoundaryMarkers, SequenceAndKey sequenceAndKey)

   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.RenderChildComponent(TextWriter output, RenderTreeFrame& componentFrame)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.RenderCore(Int32 componentId, TextWriter output, ArrayRange`1 frames, Int32 position)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.WriteComponentHtml(Int32 componentId, TextWriter output)

   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.WriteComponentHtml(Int32 componentId, TextWriter output, Boolean allowBoundaryMarkers, SequenceAndKey sequenceAndKey)

   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.RenderChildComponent(TextWriter output, RenderTreeFrame& componentFrame)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.RenderCore(Int32 componentId, TextWriter output, ArrayRange`1 frames, Int32 position)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.WriteComponentHtml(Int32 componentId, TextWriter output)

   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.WriteComponentHtml(Int32 componentId, TextWriter output, Boolean allowBoundaryMarkers, SequenceAndKey sequenceAndKey)

   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.RenderChildComponent(TextWriter output, RenderTreeFrame& componentFrame)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.RenderCore(Int32 componentId, TextWriter output, ArrayRange`1 frames, Int32 position)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.WriteComponentHtml(Int32 componentId, TextWriter output)

   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.WriteComponentHtml(Int32 componentId, TextWriter output, Boolean allowBoundaryMarkers, SequenceAndKey sequenceAndKey)

   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.RenderChildComponent(TextWriter output, RenderTreeFrame& componentFrame)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.RenderCore(Int32 componentId, TextWriter output, ArrayRange`1 frames, Int32 position)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.WriteComponentHtml(Int32 componentId, TextWriter output)

   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.WriteComponentHtml(Int32 componentId, TextWriter output, Boolean allowBoundaryMarkers, SequenceAndKey sequenceAndKey)

   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.RenderChildComponent(TextWriter output, RenderTreeFrame& componentFrame)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.RenderCore(Int32 componentId, TextWriter output, ArrayRange`1 frames, Int32 position)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.RenderFrames(Int32 componentId, TextWriter output, ArrayRange`1 frames, Int32 position, Int32 maxElements)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.RenderElement(Int32 componentId, TextWriter output, ArrayRange`1 frames, Int32 position)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.RenderCore(Int32 componentId, TextWriter output, ArrayRange`1 frames, Int32 position)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.RenderFrames(Int32 componentId, TextWriter output, ArrayRange`1 frames, Int32 position, Int32 maxElements)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.RenderElement(Int32 componentId, TextWriter output, ArrayRange`1 frames, Int32 position)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.RenderCore(Int32 componentId, TextWriter output, ArrayRange`1 frames, Int32 position)

   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.WriteComponentHtml(Int32 componentId, TextWriter output)

   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.WriteComponentHtml(Int32 componentId, TextWriter output, Boolean allowBoundaryMarkers, SequenceAndKey sequenceAndKey)

   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.WriteComponentHtml(Int32 componentId, TextWriter output)

   at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer.PrerenderedComponentHtmlContent.WriteTo(TextWriter writer, HtmlEncoder encoder)

   at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)

   at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)

   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<<InvokeAsync>b__10_0>d.MoveNext()

--- End of stack trace from previous location ---

   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)

   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### .NET Version

8.0.100

**Comment by javiercn** [comment]
@davhdavh thanks for contacting us.

Root components must have serializable parameters. In your case, you are extending `Editor<T>` which among other parameters receives a RenderFragment which is not serializable. If you want to use something like that as a route component, you need to wrap it another component (like we do with the `Routes` component in the template).

**Comment by davhdavh** [comment]
Thanks. A more useful error message would be welcome for this issue then instead of some random serializer error.

**Comment by juliannecohen** [comment]
@davhdavh Would you mind sharing how you solved this? Currently having a similar problem, not quite sure what the answer to this issue means.. Thank you!

**Comment by davhdavh** [comment]
@juliannecohen dont put rendermode in the editor. It needs to be 1 level up at any component that uses the editor component

**Comment by juliannecohen** [comment]
@davhdavh I see, thank you!
