### ISSUE TITLE
SpaServices.Extensions is Proxying Mapped Routes to SPA Dev Server

### ISSUE THREAD

**Issue by buckeyez** [dotnet/aspnetcore#53825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Microsoft.AspNetCore.SpaServices.Extensions

This extension appears to be proxying the mapped routes to the frontend dev server.

Log:

```text
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.Net.Http.HttpRequestException: Failed to proxy the request to http://localhost:8080/api/weather, because the request to the proxy target failed. Check that the proxy target server is running and accepting requests to http://localhost:8080/.

The underlying exception message was 'No connection could be made because the target machine actively refused it. (localhost:8080)'.Check the InnerException for more details.
       ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (localhost:8080)
       ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
         at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
         at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationTcontext, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.SpaServices.Extensions.Proxy.SpaProxy.PerformProxyRequest(HttpContext context, HttpClient httpClient, Task`1 baseUriTask, CancellationToken applicationStoppingToken, Boolean proxy404s)
         at Microsoft.AspNetCore.Builder.SpaProxyingExtensions.<>c__DisplayClass2_0.<<UseProxyToSpaDevelopmentServer>b__0>d.MoveNext() 
      --- End of stack trace from previous location ---
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### Expected Behavior

Extension should not proxy mapped routes.

### Steps To Reproduce

https://github.com/buckeyez/net8-spa-ext

### .NET Version

8.0.101

### Anything else?

[dotnet-info.txt](https://github.com/dotnet/aspnetcore/files/14172231/dotnet-info.txt)

**Comment by NpDen4ik** [comment]
try writing like this: "http://localhost:8080/"

**Comment by NpDen4ik** [comment]
You end up with double proxying. So in your Vitе configuration you are using a proxy. The request goes to the backend, where it sees that you are contacting from the address where you have a registered proxy, and it turns out that it will redirect you back based on this configuration.

In general, you don’t need to specify proxying in vite if you are already proxying it to the backend; it already means redirecting all requests.
But unfortunately, the server does not work like that with vitе dev.

You can simply remove the instructions for the proxy on your backend and leave these instructions only in Vite.

Or you can try using .UseReactDevelopmentServer(npmScript: "dev");
Only there is also an ingenious way to determine that the development server has been started. Once started, your Vite development server should write in the log: “Starting development server.”
There is a listener there who makes a judgment on this permanent outcome.
for writing this vite server command, it also does not have obvious hooks, unfortunately, at the moment there is nothing better than this plugin, which I have not found:

```
  plugins: [
    {
      name: 'vite-dev-starting-server-log',
      configureServer: () => {
        // UseReactDevelopmentServer
        console.log('Starting the development server');
      }
    },
 ...
]
```
Unfortunately, Asp.Net does not have any good solutions with vite. In your case, also Vue, I generally sympathize with you. X)

**Comment by buckeyez** [comment]
The extension should still not proxy mapped routes, everything else that is not caught should proxy. I should be able to go to `localhost:9001/api/weather` and be able to get the forecast without it trying to proxy to the frontend dev server or not be found without it.

**Comment by javiercn** [comment]
@buckeyez thanks for contacting us.

`UseProxyToSpaDevelopmentServer` will map incoming requests to the proxy unconditionally. If you want to use it, you need to filter when it gets applied via `MapWhen`.

That said, this is no longer the configuration we recommend you use for developing SPA applications. The SPA templates follow the standard approach other frameworks use where we proxy from the frontend dev proxy to the backend proxy and not the other way around.
