### ISSUE TITLE
Globally configured InteractiveServer breaks RCL razor pages

### ISSUE THREAD

**Issue by asward** [dotnet/aspnetcore#53882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When setting @rendermode="InteractiveServer" on the HeadOutlet and Routes components as documented (https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-8.0#apply-a-render-mode-to-the-entire-app), then pages contained in an included RCL respond with 'Not Found', even after using AddAdditionalAssemblies() in the app builder.

It appears the browser renders the page initially but then falls back to the simple 'Not Found' text only.

Using component wise InteractiveServer does work as expected. The issue only occurs when using InteractiveServer from the project 'global' location.

### Expected Behavior

InteractiveServer should propagate to the page in the RCL, and the page should render and function as normal.

### Steps To Reproduce

1. `dotnet new blazor -o app`
2. `dotnet new razorclasslibrary -o lib`
3. `dotnet add ./app/app.csproj reference ./lib/lib.csproj`
4. Add `@rendermode="InteractiveServer"` to the HeadOutlet and Routes component in App.razor of app project
5. Append `.AddAdditionalAssemblies(typeof(lib._Imports).Assembly)` to `app.MapRazorComponents<App>()` in Program.cs of app project.
6. Move `Counter.razor` from app project to the lib project
7. Add `@using static Microsoft.AspNetCore.Components.Web.RenderMode` to `_Imports.cs` in the lib project (or remove `@rendermode InteractiveServer` from the `Counter.razor` file)
9. `dotnet run` the app project
10. Click on the Counter navigator link

### Exceptions (if any)

In the browser (Firefox) I get the following error immediately after navigating to /counter.
```
Uncaught (in promise) WebSocket is not in the OPEN state blazor.web.js:1:96282
```

Approximately 45-60 seconds after navigating to /counter the following error is shown in the terminal where I do `dotnet run`
```
fail: Microsoft.AspNetCore.Components.Server.Circuits.RemoteNavigationManager[4]
      Navigation failed when changing the location to http://localhost:5178/counter
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteNavigationManager.<>c__DisplayClass13_0.<<NavigateToCore>g__PerformNavigationAsync|0>d.MoveNext()
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'io0v03bU7UgUcf8thbYRvLfbDGoM7ES7jKhkH0l6DWQ'.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteNavigationManager.<>c__DisplayClass13_0.<<NavigateToCore>g__PerformNavigationAsync|0>d.MoveNext()
```

### .NET Version

8.0.101

### Anything else?

Using VSCode

`dotnet --info`
```
.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.825c015e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.101\

.NET workloads installed:
 Workload version: 8.0.100-manifests.825c015e
There are no installed workloads to display.

Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92

.NET SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.2.110 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.426 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.6.23330.14 [C:\Program Files\dotnet\sdk]
  8.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.6.23329.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.6.23329.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.6.23329.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by javiercn** [comment]
@asward thanks for contacting us.

Can you provide a repro project? That said, look if you are passing the assemblies to the `Router` component which also needs access to them.

**Comment by adxprime** [comment]
`<Router AppAssembly="typeof(Program).Assembly" AdditionalAssemblies="new []{typeof(lib._Imports).Assembly}">`
Like @javiercn  said you need to add AdditionalAssembiles in program.cs AND in Routes.razor

**Comment by asward** [comment]
This fixes it.

I believe I discovered the need for AddAdditionalAssemblies on the app builder through github issues during preview. I do recall seeing the Router attributes too, but I guess I assumed they were doing the same thing.
