### ISSUE TITLE
.NET Core dependency injection not working on microsoft docker container (.NET8)

### ISSUE THREAD

**Issue by alexandredelnero** [dotnet/aspnetcore#53977]
I have an application that works fine locally.
But when i try to run it on docker container, the microsoft docker container shows me that the dependency injection is failing/not working.

**here is my docker-compose and docker-file**

------------------------------------
docker compose
------------------------------------
version: '3.1'

services:

sigos:
build:
context: ../../.
args:
ARG_TARGET_ENVIRONMENT: Production
ARG_TARGET_PUBLISHMODE: Release
ARG_TARGET_PORT_EXPOSURE: 8080
restart: always
ports:
- 8080:8080
depends_on:
- sqlserverdb

sqlserverdb:
image: mcr.microsoft.com/mssql/server:2022-latest
user: root
environment:
SA_PASSWORD: 5643rep5@#aaaaa
ACCEPT_EULA: "Y"
MSSQL_PID: "Developer"
ports:
- "1433:1433"
volumes:
- ./Volume-docker/sqlserverprod:/var/opt/mssql/data

------------------------------------
docker file
------------------------------------
FROM mcr.microsoft.com/dotnet/nightly/sdk:8.0 AS build
WORKDIR /app

ARG ARG_TARGET_ENVIRONMENT
ARG ARG_TARGET_PUBLISHMODE
ENV TARGET_ENVIRONMENT=$ARG_TARGET_ENVIRONMENT
ENV TARGET_PUBLISHMODE=$ARG_TARGET_PUBLISHMODE

COPY .sln .
COPY Apresentacao/.csproj ./Apresentacao/
COPY Modelo/.csproj ./Modelo/
COPY Negocio/.csproj ./Negocio/
COPY Acesso/*.csproj ./Acesso/

COPY Apresentacao/. ./Apresentacao/
COPY ./Modelo/. ./Modelo/
COPY ./Negocio/. ./Negocio/
COPY ./Acesso/. ./Acesso/

RUN dotnet restore
RUN dotnet build
RUN dotnet publish -c $TARGET_PUBLISHMODE -o out /p:EnvironmentName=$TARGET_ENVIRONMENT

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runner
WORKDIR /app/out
COPY --from=build /app/out ./

ARG ARG_TARGET_PORT_EXPOSURE
ARG ARG_TARGET_ENVIRONMENT
ENV TARGET_PORT_EXPOSURE=$ARG_TARGET_PORT_EXPOSURE
ENV TARGET_ENVIRONMENT=$ARG_TARGET_ENVIRONMENT
ENV TARGET_RUNNING_IN_CONTAINER=true

EXPOSE $TARGET_PORT_EXPOSURE
ENTRYPOINT ["dotnet", "Apresentacao.dll"]

------------------------------------
C# code
------------------------------------
**My dependency injection is fine....such as the code below**

on program.cs
services.AddScoped<INegocioDemanda, NegocioDemanda>();

public class DemandaController : Controller
{
    public INegocioDemanda NegocioDemanda { get; set; }
    public INegocioSolicitante NegocioSolicitante { get; set; }

    public DemandaController(INegocioDemanda negocioDemanda, INegocioSolicitante negocioSolicitante)
    {
        NegocioDemanda = negocioDemanda;
        NegocioSolicitante = negocioSolicitante;
    }
}

------------------------------------------------
stack of the error
------------------------------------------------

2024-01-25 19:40:20 fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
2024-01-25 19:40:20 An unhandled exception has occurred while executing the request.
2024-01-25 19:40:20 System.InvalidOperationException: Unable to resolve service for type 'Negocio.interfaces.INegocioLog' while attempting to activate 'TRF3.Apresentacao.Controllers.HomeController'.
2024-01-25 19:40:20 at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ThrowHelperUnableToResolveService(Type type, Type requiredBy)
2024-01-25 19:40:20 at lambda_method2(Closure, IServiceProvider, Object[])
2024-01-25 19:40:20 at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.g__CreateController|0(ControllerContext controllerContext)
2024-01-25 19:40:20 at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2024-01-25 19:40:20 at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
2024-01-25 19:40:20 --- End of stack trace from previous location ---
2024-01-25 19:40:20 at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-01-25 19:40:20 at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
2024-01-25 19:40:20 at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2024-01-25 19:40:20 at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
2024-01-25 19:40:20 --- End of stack trace from previous location ---
2024-01-25 19:40:20 at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2024-01-25 19:40:20 at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2024-01-25 19:40:20 at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
2024-01-25 19:40:20 at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
2024-01-25 19:40:20 fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[3]
2024-01-25 19:40:20 An exception was thrown attempting to execute the error handler.
2024-01-25 19:40:20 System.InvalidOperationException: Unable to resolve service for type 'Negocio.interfaces.INegocioLog' while attempting to activate 'TRF3.Apresentacao.Controllers.HomeController'.
2024-01-25 19:40:20 at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ThrowHelperUnableToResolveService(Type type, Type requiredBy)
2024-01-25 19:40:20 at lambda_method4(Closure, IServiceProvider, Object[])
2024-01-25 19:40:20 at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.g__CreateController|0(ControllerContext controllerContext)
2024-01-25 19:40:20 at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2024-01-25 19:40:20 at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
2024-01-25 19:40:20 --- End of stack trace from previous location ---
2024-01-25 19:40:20 at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2024-01-25 19:40:20 at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
2024-01-25 19:40:20 at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2024-01-25 19:40:20 at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
2024-01-25 19:40:20 --- End of stack trace from previous location ---
2024-01-25 19:40:20 at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2024-01-25 19:40:20 at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2024-01-25 19:40:20 at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
2024-01-25 19:40:20 at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.HandleException(HttpContext context, ExceptionDispatch

**Can someone find out the error?**

**Comment by martincostello** [comment]
Please provide a minimal reproducible example in the form of a GitHub repository.

Just from looking at what you've provided, nowhere is the custom logger registered with the service container, which would explain why it can't be resolved, which would just be a simple programmer omission to fix.
