### ISSUE TITLE
.NET 8 Blazor - NavigationManager.NavigateTo() Inconsistent Behavior

### ISSUE THREAD

**Issue by sbwalker** [dotnet/aspnetcore#53996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A very common use case in web applications is that the user may need to navigate to another Url. Usually this is accomplished with a standard hyperlink - however there are often scenarios where you need to do some validation or processing prior to redirecting the user. 

In Interactive render mode you can use an ```@onclick``` handler and call NavigationManager.NavigateTo(). However if you are creating components which support Static render mode, the ```@onclick``` handler approach does not work so you need to use standard forms and button instead.

The component code below includes a simple form with a button which performs a redirect:

```
@inject NavigationManager NavigationManager

<form method="post" @onsubmit="Submit" @formname="MyUniqueFormName">
    <AntiforgeryToken />
    <button type="submit" class="btn btn-primary">Redirect</button>
</form>

@code {
    private void Submit()
    {
        NavigationManager.NavigateTo("/");
    }
}
```

When running this code on Interactive render mode it works fine... it redirects the user to the "/" path.

However when running this code on Static render mode, it throws an exception:

![image](https://github.com/dotnet/aspnetcore/assets/4840590/b761ad5d-259b-43f8-bddc-86dbb117084b)

Similar behavior related to NavigationManager has been reported previously (ie. [#13582](https://github.com/dotnet/aspnetcore/issues/13582)) however the recommended solution was to instruct the developer to ignore the exception in their Visual Studio IDE: 

![64161981-6fc13680-ce36-11e9-8a77-5d243305cf7c](https://github.com/dotnet/aspnetcore/assets/4840590/cbcc59cf-140a-4ecf-93c0-cd92e2a0e03f)

This is not a good resolution, as most developers would not have this exception ignored by default, and most developers would assume it is a problem with the Blazor application code.

### Expected Behavior

Expected behavior would be for the NavigationManager.NavigateTo() method to behave consistently on Static and Interactive render modes ie. the user would be redirected and no run-time exception would occur.

Alternatively, some official guidance from Microsoft on how to deal with this scenario in Blazor applications would be useful. For example if the expectation is that developers need to create their own wrapper class around NavigationManager.NavigateTo() to handle the exception in Static rendering, then it should be included in the documentation. 

### Steps To Reproduce

The code in the issue reproduces the issue... just be sure to instantiate the component in Interactive render mode.

### .NET Version

8.0.1

**Comment by javiercn** [comment]
@sbwalker thanks for filing an issue.

This has come up in the past, and we discussed fixing it for 9.0. I don't know if we have an issue tracking it, so I'm going to choose this one as the one, but in general, we all agree that the current way this works is not great.

**Comment by sbwalker** [comment]
@javiercn I am glad we are in agreement :) In the interim (before .NET 9) is the recommendation to create a simple wrapper around NavigationManager.NavigateTo() which traps and ignores the exception when running on static render mode?

**Comment by DylanLyon** [comment]
I'm having a similar issue with the NavigationManager.NavigateTo() method. My use case is pretty simple but a lot of functionality in the app relies on being able to handle routing parameters to initialize data in the app and is no longer working as it used to.

`Navigation.NavigateTo($"authentication/login?returnUrl={Uri.EscapeDataString(Navigation.Uri)}");`

The idea is that in my RedirectToLogin component a non-authorized user would be redirected to a login and then directed to their URL so it can be decoded and initialized. But currently it doesn't seem that the returnUrl is working as expected. Instead of navigating to the original URL it just forgets it and navigates to the base URL of the app.

The app is newly updated for Dotnet 8 from Dotnet 6 and this seems to be the only major issue. Using package versions 8.0.2. Potentially related I found that I had to add 

`<TrimmerRootAssembly Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" />`

to my csproj because of a different authentication redirect issue so maybe there are some issues with this package?

**Comment by sherviniv** [comment]
I encounter a similar issue whenever I run my code **with a debugger**. It functions properly **without a debugger**.
`Microsoft.AspNetCore.Components.NavigationException
  HResult=0x80131500
  Message=Exception of type 'Microsoft.AspNetCore.Components.NavigationException' was thrown.
  Source=Microsoft.AspNetCore.Components.Server
  StackTrace:
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteNavigationManager.NavigateToCore(String uri, NavigationOptions options)
   at Microsoft.AspNetCore.Components.NavigationManager.NavigateToCore(String uri, Boolean forceLoad)
   at RedirectToLogin.OnInitialized() in RedirectToLogin.razor:line 6
   at Microsoft.AspNetCore.Components.ComponentBase.<RunInitAndSetParametersAsync>d__21.MoveNext()
`

**Comment by KennethHoff** [comment]
@sherviniv Are you actually encountering an _issue_, or simply an exception?

**Comment by sherviniv** [comment]
@KennethHoff In both cases(without a debugger or with it) it is working. But with the debugger mode, I got an exception.

**Comment by sbwalker** [comment]
@javiercn I just realized that catching and ignoring the exception in your application code is not a solution, as the NavigationManager will fail to redirect to the desired location.

Created an extension method

```
using Microsoft.AspNetCore.Components;

namespace Oqtane.Extensions
{
    public static class NavigationManagerExtensions
    {
        public static void NavigateToIgnoreException(this NavigationManager navigationManager, string uri, bool forceLoad = false, bool replace = false)
        {
            try
            {
                navigationManager.NavigateTo(uri, forceLoad, replace);
            }
            catch
            {
                // ignore exception thrown in static rendering within debugger
            }
        }
    }
}
```

and used it in my component:

```
NavigationManager.NavigateToIgnoreException("/");
```

The exception is ignored - but no navigation occurs - the existing UI will continue to be displayed.

So it seems that the only way to deal with this issue in .NET 8 is to configure the Visual Studio dev tools to ignore the exception - and then it will work as expected.

**Comment by sbwalker** [comment]
The Blazor Web template with authentication enabled includes an IdentityRedirectManager class which appears to provide a workaround for this issue (ie. so that exceptions are not thrown):

// During static rendering, NavigateTo throws a NavigationException which is handled by the framework as a redirect.
// So as long as this is called from a statically rendered Identity component, the InvalidOperationException is never thrown.


```
using Microsoft.AspNetCore.Components;
using System.Diagnostics.CodeAnalysis;

namespace BlazorAppWithAuth.Components.Account
{
    internal sealed class IdentityRedirectManager(NavigationManager navigationManager)
    {
        public const string StatusCookieName = "Identity.StatusMessage";

        private static readonly CookieBuilder StatusCookieBuilder = new()
        {
            SameSite = SameSiteMode.Strict,
            HttpOnly = true,
            IsEssential = true,
            MaxAge = TimeSpan.FromSeconds(5),
        };

        [DoesNotReturn]
        public void RedirectTo(string? uri)
        {
            uri ??= "";

            // Prevent open redirects.
            if (!Uri.IsWellFormedUriString(uri, UriKind.Relative))
            {
                uri = navigationManager.ToBaseRelativePath(uri);
            }

            // During static rendering, NavigateTo throws a NavigationException which is handled by the framework as a redirect.
            // So as long as this is called from a statically rendered Identity component, the InvalidOperationException is never thrown.
            navigationManager.NavigateTo(uri);
            throw new InvalidOperationException($"{nameof(IdentityRedirectManager)} can only be used during static rendering.");
        }

        [DoesNotReturn]
        public void RedirectTo(string uri, Dictionary<string, object?> queryParameters)
        {
            var uriWithoutQuery = navigationManager.ToAbsoluteUri(uri).GetLeftPart(UriPartial.Path);
            var newUri = navigationManager.GetUriWithQueryParameters(uriWithoutQuery, queryParameters);
            RedirectTo(newUri);
        }

        [DoesNotReturn]
        public void RedirectToWithStatus(string uri, string message, HttpContext context)
        {
            context.Response.Cookies.Append(StatusCookieName, message, StatusCookieBuilder.Build(context));
            RedirectTo(uri);
        }

        private string CurrentPath => navigationManager.ToAbsoluteUri(navigationManager.Uri).GetLeftPart(UriPartial.Path);

        [DoesNotReturn]
        public void RedirectToCurrentPage() => RedirectTo(CurrentPath);

        [DoesNotReturn]
        public void RedirectToCurrentPageWithStatus(string message, HttpContext context)
            => RedirectToWithStatus(CurrentPath, message, context);
    }
}
```

**Comment by VahidN** [comment]
A RedirectTo method for the Blazor SSR without any exception!

```C#
public static class BlazorSsrRedirectManagerExtensions
{
    public static void RedirectTo(this HttpContext httpContext, string redirectionUrl)
    {
        ArgumentNullException.ThrowIfNull(httpContext);

        httpContext.Response.Headers.Append("blazor-enhanced-nav-redirect-location", redirectionUrl);
        httpContext.Response.StatusCode = 200;
    }
}
```

**Comment by mxmissile** [comment]
> A RedirectTo method for the Blazor SSR without any exception!
> 
> ```cs
> public static class BlazorSsrRedirectManagerExtensions
> {
>     public static void RedirectTo(this HttpContext httpContext, string redirectionUrl)
>     {
>         ArgumentNullException.ThrowIfNull(httpContext);
> 
>         httpContext.Response.Headers.Append("blazor-enhanced-nav-redirect-location", redirectionUrl);
>         httpContext.Response.StatusCode = 200;
>     }
> }
> ```

Doesnt work `ContextAccessor.HttpContext.RedirectTo("/");`

**Comment by VahidN** [comment]
> Doesnt work `ContextAccessor.HttpContext.RedirectTo("/");`

You should define the HttpContext for a Blazor SSR page this way:
```C#
    [CascadingParameter] public HttpContext? HttpContext { get; set; }
```

**Comment by mxmissile** [comment]
> > Doesnt work `ContextAccessor.HttpContext.RedirectTo("/");`
> 
> You should define the HttpContext for a Blazor SSR page this way and call that method at the end of the processed request (it will not end the request immediately):
> 
> ```cs
> @code{
>     [CascadingParameter] public HttpContext? HttpContext { get; set; }
> }
> ```

Tried using the the CascadingParameter also, If I call RedirectTo in `OnInitialized()` it works. However if I call it in a Callback it does not work:

`<EditForm FormName="AddOrder" OnValidSubmit="SubmitOrder" Model="Form">`

```
private void SubmitOrder()
{
   Debug.WriteLine("Order Submit");
   
   HttpContext.RedirectTo("/");
}

```

Not sure what I am doing wrong.

**Comment by VahidN** [comment]
> Not sure what I am doing wrong.
Make it an **enhanced** form, it will work (it's a blazor-**_enhanced_**-nav-redirect-location):
```xml
<EditForm FormName="AddOrder" OnValidSubmit="SubmitOrder" Model="InputModel" method="post" Enhance>
```

**Comment by mxmissile** [comment]
That worked, thank you!

**Comment by los93sol** [comment]
@javiercn  I spun up a Blazor Web App for .NET 9, Individual Accounts, Auto (Server and WebAssembly), and Per page/component, and included sample pages.  Works fine, but when registering an account it throws an exception as well, is this expected?  Any solution or just ignore it for now?

**Comment by ELEMENTs-JP** [comment]
In my case, this error leads to permanent errors. It does not help to build a TRY CATCH around it, as the redirect is not executed. It would be really great if this error could finally be fixed, because this is used consistently in my application.

**Comment by michaelcsikos** [comment]
@VahidN In my **Log in** form, the `HttpContext.RedirectTo("/")` extension worked, thanks.

It didn't work in the **Log out** form, but `NavigationManager.NavigateTo("/")` works there for some reason.

**Comment by Halonico** [comment]
> A RedirectTo method for the Blazor SSR without any exception!
> 
> ```cs
> public static class BlazorSsrRedirectManagerExtensions
> {
>     public static void RedirectTo(this HttpContext httpContext, string redirectionUrl)
>     {
>         ArgumentNullException.ThrowIfNull(httpContext);
> 
>         httpContext.Response.Headers.Append("blazor-enhanced-nav-redirect-location", redirectionUrl);
>         httpContext.Response.StatusCode = 200;
>     }
> }
> ```

I was stuck for multiple days on this issue, and you managed to make it work, thank you very much for your help and your code.

Now I'm going to rant a little, it would be great if we had more informations in the exception to know what happen behind the scene.

It's not only the NavigationManager, Blazor is full of quirky stuff like this, and I'm forced to use it, it's not pleasant

**Comment by sherviniv** [comment]
Even though the exception is thrown and the app works properly, many people spend hours trying to figure out what they have done wrong, which can be very confusing. This error is quite common. Many Blazor developers have switched from Angular, React, and when they realize that they have spent hours on a bug that wasn't their fault, they may feel discouraged and reconsider migrating to Blazor.

**Comment by irejwanul** [comment]
Calling inside of try...catch block will prevent the `NavigationManager.NavigateTo("/");`

Calling outside of try...catch block will ignore the Exception and `NavigationManager.NavigateTo("/");` works normal.

Although, this is not a normal behaviour of the `NavigationManager.NavigateTo("/");`

**Comment by KennethHoff** [comment]
That's why you shouldn't use `catch (Exception)` but instead be specific in your catches

**Comment by Woudjee** [comment]
So.... will this be fixed in .NET 9.0? I have also spend quite a few hours on this issue and it seems that the problem has been around for a few years. It is indeed very discouraging to deal with these kinds of issues.

The same goes for buttons in SSR. I understand the fundamental problem, but come on.

**Comment by KennethHoff** [comment]
Absolutely not in 9.0; if it's not in by July/August, it won't be in the upcoming version.

**Comment by Woudjee** [comment]
Oy. Then how do I deal with this correctly? Because currently I am simply getting an exception after which I press continue in my Visual Studio. Which is bad for demos.

**Comment by mip1983** [comment]
> Oy. Then how do I deal with this correctly? Because currently I am simply getting an exception after which I press continue in my Visual Studio. Which is bad for demos. 

When it throws the exception, there's a box you can uncheck for 'break when this exception type is thrown'. Uncheck that or in exception settings in VS.

**Comment by Woudjee** [comment]
> > Oy. Then how do I deal with this correctly? Because currently I am simply getting an exception after which I press continue in my Visual Studio. Which is bad for demos.
> 
> When it throws the exception, there's a box you can uncheck for 'break when this exception type is thrown'. Uncheck that or in exception settings in VS.

Aha, so that _is_ the actual solution to this bug. And we are all sure that this has no issues in production?

**Comment by Woudjee** [comment]
I don't have the option to ignore the `NavigationException`. Anyone any idea why?

![Image](https://github.com/user-attachments/assets/ed1e3f8a-e67e-41ed-bf4d-10e006c3749c)

**Comment by michaelcsikos** [comment]
@Woudjee, the solution provided by @VahidN worked for me. (It didn't work for my **Log out** form, but `NavigationManager.NavigateTo("/")` works there for some reason.)

From earlier in this thread:

A `RedirectTo` method for the Blazor SSR without any exception!
```cs
public static class BlazorSsrRedirectManagerExtensions
{
    public static void RedirectTo(this HttpContext httpContext, string redirectionUrl)
    {
        ArgumentNullException.ThrowIfNull(httpContext);

        httpContext.Response.Headers.Append("blazor-enhanced-nav-redirect-location", redirectionUrl);
        httpContext.Response.StatusCode = 200;
    }
}
```
You should define the `HttpContext` for a Blazor SSR page this way and call that method at the end of the processed request (it will not end the request immediately):
```razor
@code
{
    [CascadingParameter] public HttpContext? HttpContext { get; set; }
}
```

**Comment by Woudjee** [comment]
> [@Woudjee](https://github.com/Woudjee), the solution provided by [@VahidN](https://github.com/VahidN) worked for me. (It didn't work for my **Log out** form, but `NavigationManager.NavigateTo("/")` works there for some reason.)
> 
> From earlier in this thread:
> 
> A `RedirectTo` method for the Blazor SSR without any exception!
> 
> public static class BlazorSsrRedirectManagerExtensions
> {
>     public static void RedirectTo(this HttpContext httpContext, string redirectionUrl)
>     {
>         ArgumentNullException.ThrowIfNull(httpContext);
> 
>         httpContext.Response.Headers.Append("blazor-enhanced-nav-redirect-location", redirectionUrl);
>         httpContext.Response.StatusCode = 200;
>     }
> }
> You should define the `HttpContext` for a Blazor SSR page this way and call that method at the end of the processed request (it will not end the request immediately):
> 
> @code
> {
>     [CascadingParameter] public HttpContext? HttpContext { get; set; }
> }

Thank you! This is very clear 😁😎👍 I will try it out next week!

**Comment by VahidN** [comment]
**Tip!** 
How to redirect from the `Login` page in Blazor SSR app's without using the `NavigationManager`:
```C#
await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, cookieClaims,
            new AuthenticationProperties
            {
                // ...

                RedirectUri = UriHelper.Encode(new Uri(ReturnUrl))
            });
```
`RedirectUri` should be properly encoded for use in HTTP headers by using the `UriHelper.Encode` method.

**Comment by sbwalker** [comment]
This issue (and many others) were covered in this Black Belt Blazor presentation:

https://youtu.be/1lsjpfdqBk0?si=IJNe3IkdjJubcLbe

**Comment by mkArtakMSFT** [comment]
Some of the issues here will be addressed by https://github.com/dotnet/aspnetcore/pull/58573.
However, we are going to use this issue to track potential future work for improving the overall experience related to how navigation happens in Blazor.

**Comment by mmolineroGit** [comment]
en .NET 9
Sin @rendermode InteractiveServer:

        protected override async Task OnInitializedAsync()
        {
            await base.OnInitializedAsync();
        }

        public async Task LoginUser()
        {
            var result = await _userServ.Login(Input);
            if (result.IsSuccess)
            {
                ((CustomAuthenticationStateProvider)_stateProvider).AuthenticateUser(result?.Value?.Token!);
                Navigation.NavigateTo(ReturnUrl, forceLoad: true);
            }
            else
            {
                errorMessage = "Error de validación";
            }
        }


con @rendermode InteractiveServer:

          private bool loading = true;
        protected override async Task OnInitializedAsync()
        {
            Task task = Task.Run(() => { RedirectToIni(); });
        }

        private async Task RedirectToIni()
        {
            var USP = await ASP.GetAuthenticationStateAsync();
            string US = USP?.User?.Identity?.Name!;

            loading = false;
            if (US == null)
            {
                Navigation.NavigateTo("Account/Login", forceLoad: true);
            }
            else
            {
                Navigation.NavigateTo("/Inicio", forceLoad: true);
            }
        }

**Comment by erossini** [comment]
I'm facing the same issue with the navigation. I'm creating a new project with Blazor on .NET 9. In this project, I want to add the Authentication Type as "Individual Accounts". For that, I create a new project with the following values:

- Framework: .NET 9
- Authentication type: individual accounts
- Interactive render mode: auto

![Image](https://github.com/user-attachments/assets/46af316c-bc0c-4692-9d7d-401aa6ae5a3c)

The project was created successfully and I ran the update-database to create the ASP.NET database. When I run the application and register a new user, I get this error:

> Microsoft.AspNetCore.Components.NavigationException: 'Exception_WasThrown'

![Image](https://github.com/user-attachments/assets/17687974-f096-4bc1-93ae-fe40f18afea2)

I don't understand how to avoid this error. Is there any workaround?

**Comment by michaelcsikos** [comment]
@erossini, try https://github.com/dotnet/aspnetcore/issues/53996#issuecomment-2451348821

**Comment by shahabfar** [comment]
@erossini 
In your Exception User-Unhandled dialog box (as you've shown in the image) uncheck the 'Break when this exception type is user-unhandled'

**Comment by javiercn** [comment]
We are tracking improvements to this experience https://github.com/dotnet/aspnetcore/issues/59451

**Comment by tharlab** [comment]
```
public Exception CustomInitialized(){
 NavigateTo(..);
 ...
}
```
put placeholder on page:

`@customInitialized()`

**Comment by guardrex** [comment]
@danroth27 ... I saw your remark about https://github.com/dotnet/aspnetcore/pull/58573. How does that fix relate to this issue?

**Comment by danroth27** [comment]
> [@danroth27](https://github.com/danroth27) ... I saw your remark about [#58573](https://github.com/dotnet/aspnetcore/pull/58573). How does that fix relate to this issue?

@guardrex Which remark are you referring? I'm not sure #58573 is really related to this issue...

**Comment by guardrex** [comment]
I thought the error in the OP was the same.

Either way at 9.0 1 release, I'll remove the bit I added to the tutorial on ignoring the nav exception.

**Comment by javiercn** [comment]
> We are tracking improvements to this experience [#59451](https://github.com/dotnet/aspnetcore/issues/59451)

Closing this issue as we are tracking improvements in the other issue.
