### ISSUE TITLE
Inconsistent Form model-binding behaviour whether an `IFormFileCollection` property exists or not.

### ISSUE THREAD

**Issue by KennethHoff** [dotnet/aspnetcore#54130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Calling an endpoint with a model _without_ an `IFormFileCollection` without providing any valid fields causes the handler to receive a `null` value:

```sh
curl --location --request POST 'https://localhost:7173/withForm' \
--header 'Content-Type: application/x-www-form-urlencoded'
```

Calling an endpoint with a model _with_ an `IFormFileCollection` without providing any valid fields correctly validates the model and promptly throws a `FormDataMappingException` (`Missing required value for property 'Name'`)

```sh
curl --location --request POST 'https://localhost:7173/withoutForm' \
--header 'Content-Type: application/x-www-form-urlencoded'
```

If, however, I pass in a single valid field (even with an empty value), then all works as expected:

```sh
curl --location 'https://localhost:7173/withFileEnumerable' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'name='
```

Note: This is specifically for `IFormFileCollection`; `IEnumerable<IFormFile>`, `List<IFormFile>` (and presumably other collection interfaces) behaves similarly to not having one (i.e. `null` value being passed). `application/x-www-urlencoded` and `multipart/form-data` behaves identically.

### Expected Behavior

Calling an endpoint - with or without an `IFormFileCollection` - without providing any valid fields correctly validates the model and promptly throws a `FormDataMappingException`.

Alternatively (same meaning, different wording): Calling an endpoint without a single valid field should work (In terms of model binding) identically to calling an endpoint with one or more valid fields

### Steps To Reproduce

```c#
using Microsoft.AspNetCore.Mvc;

var builder = WebApplication.CreateBuilder(args);

var app = builder.Build();

app.MapPost("withoutFiles", ( [FromForm] WithoutFiles request) =>
{
    return request switch
    {
        null => Results.BadRequest(), // This can happen for some reason.
        _ => Results.Ok()
    };
}).DisableAntiforgery();

app.MapPost("withFileCollection", ( [FromForm] WithFileCollection request) =>
{
    return request switch
    {
        null => Results.BadRequest(), // This can never happen (as expected).
        _ => Results.Ok()
    };
}).DisableAntiforgery();

app.MapPost("withFileList", ( [FromForm] WithFileList request) =>
{
    return request switch
    {
        null => Results.BadRequest(), // This can happen for some reason.
        _ => Results.Ok()
    };
}).DisableAntiforgery();

app.MapPost("withFileEnumerable", ( [FromForm] WithFileEnumerable request) =>
{
    return request switch
    {
        null => Results.BadRequest(), // This can happen for some reason.
        _ => Results.Ok()
    };
}).DisableAntiforgery();

app.Run();

public class WithoutFiles
{
    public required string Name { get; init; }
}

public class WithFileCollection
{
    public required string Name { get; init; }
    public IFormFileCollection Attachments { get; init; } = default!;
}

public class WithFileEnumerable
{
    public required string Name { get; init; }
    public IEnumerable<IFormFile> Attachments { get; init; } = default!;
}

public class WithFileList
{
    public required string Name { get; init; }
    public List<IFormFile> Attachments { get; init; } = default!;
}
```
```

### Exceptions (if any)

This is the exception I get in the `IFormFileCollection` case - the one I'm expecting in both cases.

Microsoft.AspNetCore.Http.BadHttpRequestException: Missing required value for property 'Name'.
 ---> Microsoft.AspNetCore.Components.Endpoints.FormMapping.FormDataMappingException: An error occurred while trying to map a value from form data. For more details, see the 'Error' property and the 'InnerException' property.
   at Microsoft.AspNetCore.Components.Endpoints.FormMapping.FormDataReader.AddMappingError(Exception exception, String attemptedValue)
   at Microsoft.AspNetCore.Components.Endpoints.FormMapping.CompiledComplexTypeConverter`1.TryRead(FormDataReader& context, Type type, FormDataMapperOptions options, T& result, Boolean& found)
   at Microsoft.AspNetCore.Components.Endpoints.FormMapping.FormDataMapper.Map[T](FormDataReader reader, FormDataMapperOptions options)
   at lambda_method1(Closure, Object, HttpContext, Object)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.Log.FormDataMappingFailed(HttpContext httpContext, String parameterTypeName, String parameterName, FormDataMappingException exception, Boolean shouldThrow)
   at lambda_method1(Closure, Object, HttpContext, Object)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass104_2.<<HandleRequestBodyAndCompileRequestDelegateForForm>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)


### .NET Version

8.0.201 (but was also broke in 8.0.102)

### Anything else?

_No response_

**Comment by captainsafia** [comment]
@javiercn Do you see similar behavior in Blazor? I assume so given the shared code. It seems a little sus to me that binding resolves differently when you provide the same input but a different model to bind to. Any thoughts on you having an `IFormFileCollection` property in the model throws things off?

**Comment by JamesFieldist** [comment]
This is worse:

1. If you use List<IFormFile> in a DTO with [FromForm] on the minimalApi it throws an error that the value is incomplete and missing something (which it doesn't specify)
2. If you use IFormFileCollection it works but then OpenApi documentation with Nswag and MS OpenAPI generation is broken.
3. If you use IReadonlyCollection<IFormFile> it is broken.

It appears that with .net 9, ONLY IFormFileCollection works AND it breaks OpenAPI generation.

And the docs are highly not clear.
