### ISSUE TITLE
Howto : .Net8 OIDC authenticated (Azure) SignalR with Blazor Server

### ISSUE THREAD

**Issue by njannink** [dotnet/aspnetcore#54134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

How do you correctly setup SignalR with authentication on Blazor Server? I created a test project based on the BlazorWebAppOidc:

https://github.com/njannink/BlazorServerAppOidcWithHub/tree/main

Fill in your OIDC + Azure SignalR details in the `BlazorWebAppOidc/Program.cs` file, or you can also turn off Azure SignalR to use the default SignalR hosting model. Everything is working fine when using the InteractiveAuto hosting model, but as soon as you switch to the InteractiveServer way the SignalR connection can no longer be established.

 If you then login and try to connect to the chat hub you get the following error:

```
System.IO.InvalidDataException: Invalid negotiation response received.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at Microsoft.AspNetCore.Internal.SystemTextJsonExtensions.CheckRead(Utf8JsonReader& reader)
   at Microsoft.AspNetCore.Http.Connections.NegotiateProtocol.ParseResponse(ReadOnlySpan`1 content)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Http.Connections.NegotiateProtocol.ParseResponse(ReadOnlySpan`1 content)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync(Uri url, HttpClient httpClient, ILogger logger, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.GetNegotiationResponseAsync(Uri uri, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
   at BlazorWebAppOidc.Client.Pages.Chat.OnInitializedAsync() in D:\Projects\blazor\BlazorServerAppOidcWithHub\BlazorWebAppOidc.Client\Pages\Chat.razor:line 43
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Error: Unhandled exception in circuit '80pb6dJz85Pl8JrsLdYsB0wQ26jpH6Mi-79i_fPlXZg'.
```

Any help would be greatly appreciated, since we won't be able to switch to Auto/WebAssembly mode anytime soon. I know there is a way to get the access_token from the HttpContext, but as soon as you use Azure SignalR the HttpContextAccessor.HttpContext returns null.

cc: @guardrex https://github.com/dotnet/blazor-samples/issues/204

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. It's not clear how exactly the `OIDC` auth relevant here. Would you run into the same exception if you eliminate the authentication code?

**Comment by njannink** [comment]
I guess the same problem happens with Microsoft Identity and any other auth framework. The issue is indeed more related to .net authentication with SignalR and Blazor Server. But I could easily reproduce it with the OIDC sample that why I initially posted it here, but @guardrex made me repost it here

**Comment by njannink** [comment]
I removed the part about OIDC because I guess its an issue with any authentication framework. Probably also Microsoft Identity. But the question remains. What is the recommended way in Net8 Blazor Server to connect to authenticated SignalR hubs?

**Comment by guardrex** [comment]
@njannink ... I should've perhaps looked at your repro app. I'm crazy 😵 busy these days, so I was only able just now to look. Did you see the bit of guidance that we have on how to configure SignalR's underlying client to send credentials ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/signalr?view=aspnetcore-8.0#client-side-signalr-cross-origin-negotiation-for-authentication

... and see if that will do the trick for you?

**Comment by njannink** [comment]
no that gives the same error. I think that solution is for Blazor Wasm

**Comment by njannink** [comment]
ok but how do you get this access_token when there is no HttpContextAccessor available in Azure SignalR?

https://learn.microsoft.com/en-us/aspnet/core/signalr/authn-and-authz?view=aspnetcore-8.0#identity-server-jwt-authentication

**Comment by guardrex** [comment]
Indeed, a good question now that we're moving away from bearer tokens and the BWA-OIDC sample is based on cookies. As you can see here, this article focuses on bearer tokens. We'll need a member of the product unit to assist.

**Comment by guardrex** [comment]
Thanks @halter73 and @javiercn ... I'll work this further from the docs issue, and I'll also work the *Pass tokens* section issue based on the sample approach.

**Comment by garrettlondon1** [comment]
For Blazor Server apps using Cookie auth, one should grab the HTTP Context from the CircuitHandler OnConnectionUp I believe. This HTTP Context is safe to access in the context of the Blazor InteractiveServer session.

From there you can pass the cookies into the SignalR Http request handling (ex: https://github.com/dotnet/aspnetcore/issues/48628#issuecomment-1948869556) , or you can directly pass the token

**Comment by timohermans** [comment]
> The approach we would recommend for flowing the access token from the HttpContext to the server interactive component is to use a circuit activated service similar to what @javiercn demonstrates with https://github.com/javiercn/BlazorWebNonceService/.

Can confirm this works and feels like the most natural solution to Blazor Web Apps 😊🥳. Thank you so much @guardrex  and @halter73 .

Now, if only the https://github.com/javiercn/BlazorWebNonceService/ repo could be shown (with some explanation) in the docs and I think stuff should be clear for everybody.

**Comment by guardrex** [comment]
@timohermans ... I'll get to it as soon as I can, but I'm buried in other work at the moment. I think the soonest that I can reach it will be next week 🏃‍♂️.

**Comment by timohermans** [comment]
@guardrex no worries, take your time! I'll spread the word here from The Netherlands in the meantime 😇.

**Comment by nwoolls** [comment]
Hopefully I've found the right place to engage here. I'm new to Blazor and the first issue I've run into past simple Hello World and the like is getting a handle on the `access_token` when using Blazor Auto Render Mode.

Most of the previous examples no longer work with the new OOTB templates (seen above, they make use of `_Hosts.cshtml`).

Additionally, trying to use `TokenProvider` with DI and a scoped lifetime doesn't seem to work either (covered [here](https://github.com/dotnet/aspnetcore/issues/52390)).

So I'm trying to use the `CircuitHandler` method, based on the previously linked [BlazorWebNonceService](https://github.com/javiercn/BlazorWebNonceService/tree/main) repo.

I can see the circuit handler being called. And I can see the state being persisted. How, though, to I get access to that inside a `DelegatingHandler` implementation?

I've tried injecting the custom circuit handler into the delegating handler implementation, but the constructor is called without any state, and so the state is not restored with the access token.

**Comment by djfoxer** [comment]
Hi. I have similar issue. My solution has Blazor Web Apps (Server) and API. I want to send notifications from API to Blazor (Authorization/Authentication via Microsoft.Identity - EntraID). I stuck with Hub configuration on Blazor side. I should provide `AccessTokenProvider` to `HubConnectionBuilder` but I don't see where access token can be. I searched `HttpContext` (from `CascadingParameter`) but ther is no access token at all. Any sugestions? Thank you.

**Comment by thomasvdb** [comment]
> Hopefully I've found the right place to engage here. I'm new to Blazor and the first issue I've run into past simple Hello World and the like is getting access to the `access_token` when using Blazor Auto Render Mode.
> 
> Most of the previous examples no longer work with the new OOTB templates (seen above, they make use of `_Hosts.cshtml`).
> 
> Additionally, trying to use `TokenProvider` with DI and a scoped lifetime doesn't seem to work either (covered [here](https://github.com/dotnet/aspnetcore/issues/52390)).
> 
> So I'm trying to use the `CircuitHandler` method, based on the previously linked [BlazorWebNonceService](https://github.com/javiercn/BlazorWebNonceService/tree/main) repo.
> 
> I can see the circuit handler being called. And I can see the state being persisted. How, though, do I get access to that inside a `DelegatingHandler` implementation?
> 
> I've tried injecting the custom circuit handler into the delegating handler implementation, but in that case the circuit handler constructor is called without any state, and so the state is not restored with the access token.
> 
> _**Edit:** I found and followed a few more articles and I think I have this working using `CircuitServicesAccessor` to get the service I need in the delegating handler. Is this the recommended way to handle this scenario? Should it honestly be this much work? It seems like a pretty standard scenario gauging by the Google results for this, and I would hope this were handled out-of-the-box. I am very interested in Blazor, but the amount of work to handle something that is a single line of code in MVC makes me anxious about what I'll run into at each step of my journey._
> 
> _**Edit 2:** I'm running into some limitations around this approach and wondering what the right way is to handle them. Essentially, `OnInitializedAsync` is called before the `ServicesAccessorCircuitHandler` sets the services on the `CircuitServicesAccessor`. This seems to mean I have to wait until e.g. `OnAfterRenderAsync` to make my web service call. I'd rather avoid this - is that possible?_

@nwoolls Were you able to solve your second edit? Seems we're experiencing this as well when we want to refresh our access token to be able to call our APIs via Refit.

Currently we're trying to fetch the access token from the current `HttpContext` but as that's null, we can't do that (and it seems this is not the appropriate way to do so based on this thread).

**Comment by njannink** [comment]
I now use this open-source library: https://docs.duendesoftware.com/accesstokenmanagement/

They have examples how to do it

**Comment by thomasvdb** [comment]
We did not switch to the Duende solution (yet).
We use the approach documented at https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/dependency-injection?view=aspnetcore-9.0#access-server-side-blazor-services-from-a-different-di-scope

```
public class ServicesAccessorCircuitHandler(
    IServiceProvider services, CircuitServicesAccessor servicesAccessor) 
    : CircuitHandler
{
    public override Func<CircuitInboundActivityContext, Task> CreateInboundActivityHandler(
        Func<CircuitInboundActivityContext, Task> next) => 
            async context =>
            {
                servicesAccessor.Services = services;
                await next(context);
                servicesAccessor.Services = null;
            };
}
```

When a user disconnects from the circuit (due to being idle) and then tries to reconnect, it seems this approach doesn't work because the `Services` property is `null` and we can't resolve the services in other dependencies because we then get DisposedExceptions.

Our problem is solved when we no longer `null` the `Services` property.
Any idea what the side effects could be? Seems this could lead to memory problems?
