### ISSUE TITLE
Problem with using AuthorizeView in blazor with prerendering

### ISSUE THREAD

**Issue by FLAMESpl** [dotnet/aspnetcore#54407]
### Discussed in https://github.com/dotnet/aspnetcore/discussions/54384

<div type='discussions-op-text'>

<sup>Originally posted by **FLAMESpl** March  5, 2024</sup>
I have created solution using template "Blazor Web App" in .NET8, webassembly as interactive render mode and per page/component interactivity location. My index page looks like this:

```csharp
@page "/"
@inject HomeViewModel ViewModel

<AuthorizeView>
    <Authorized>
        <p>Hello @context.User.Identity!.Name</p>
        <RadzenButton
            Text="Log out"
            ButtonStyle="ButtonStyle.Secondary"
            Disabled="!ViewModel.LogOutCommand.CanExecuteWithoutParameter()"
            Click="ViewModel.LogOutCommand.ExecuteAsyncWithoutParameter"/>
        @foreach (var claim in context.User.Claims)
        {
            <p>@claim.Type - @claim.Value (@claim.ValueType)</p>
        }
    </Authorized>
    <NotAuthorized>
        <RadzenButton 
            Text="Login with facebook" 
            ButtonStyle="ButtonStyle.Primary" 
            Disabled="!ViewModel.NavigateToFacebookLoginCommand.CanExecuteWithoutParameter()"
            Click="ViewModel.NavigateToFacebookLoginCommand.ExecuteAsyncWithoutParameter"/>
    </NotAuthorized>
</AuthorizeView>
```

my App.razor is:

```csharp
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <base href="/" />
    <link rel="stylesheet" href="app.css" />
    <link rel="stylesheet" href="_content/Radzen.Blazor/css/material-base.css">
    @* <link rel="stylesheet" href="OakLab.styles.css" /> *@
    <HeadOutlet />
</head>

<body>
    <Routes />
    <script src="_framework/blazor.web.js"></script>
    <script src="_content/Radzen.Blazor/Radzen.Blazor.js"></script>
</body>

</html>
```

my Routes:

```
<Router AppAssembly="typeof(Program).Assembly" AdditionalAssemblies="new[] { typeof(Client.ArinianWargames.Home.ArinianWargamesHomePage).Assembly }">
    <Found Context="routeData">
        <RouteView RouteData="routeData" DefaultLayout="typeof(Layout.MainLayout)" />
        <FocusOnNavigate RouteData="routeData" Selector="h1" />
    </Found>
</Router>
```

and my Layout is empty (just @Body).

In both client and server apps, I have added line to programs.cs:
`builder.Services.AddCascadingAuthenticationState();`

When I run the app I immediately get error page with exception

> InvalidOperationException: JavaScript interop calls cannot be issued during server-side static rendering, because the page has not yet loaded in the browser. Statically-rendered components must wrap any JavaScript interop calls in conditional logic to ensure those interop calls are not attempted during static rendering.
Microsoft.AspNetCore.Components.Endpoints.UnsupportedJavaScriptRuntime.Microsoft.JSInterop.IJSRuntime.InvokeAsync<TValue>(string identifier, object[] args)

Stacktrace points to `Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.OnParametersSetAsync()`

Any ideas what have I done wrong?

PS. After looking into network tab I have noticed that webassembly dlls are never fetched, why?

![image](https://github.com/dotnet/aspnetcore/assets/17801634/f136e436-f00f-4bd6-aef5-82413db9229d)

After adding `@rendermode="new InteractiveWebAssemblyRenderMode(prerender: false)"` to Routes component I get different error:

```
blazor.web.js:1 Error: One or more errors occurred. (Root component type 'OakLab.Server.Components.Routes' could not be found in the assembly 'OakLab.Server'.)
    at Jn (marshal-to-js.ts:349:18)
    at Ul (marshal-to-js.ts:306:28)
    at 00b1ee2e:0x1facb
    at 00b1ee2e:0x1bf8c
    at 00b1ee2e:0xf173
    at 00b1ee2e:0x1e7e5
    at 00b1ee2e:0x1efdb
    at 00b1ee2e:0xcfed
    at 00b1ee2e:0x44108
    at e.<computed> (cwraps.ts:338:24)
```

PS2. I have set page's rendermode to interactive webassembly without prerender and I get this:

```
blazor.web.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not load settings from '_configuration/OakLab.Client'
      Error: Could not load settings from '_configuration/OakLab.Client'
          at c.createUserManager (https://localhost:7030/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js:2:290677)
          at async c.initializeCore (https://localhost:7030/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js:2:289515)
Microsoft.JSInterop.JSException: Could not load settings from '_configuration/OakLab.Client'
Error: Could not load settings from '_configuration/OakLab.Client'
    at c.createUserManager (https://localhost:7030/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js:2:290677)
    at async c.initializeCore (https://localhost:7030/_content/Microsoft.AspNetCore.Components.WebAssembly.Authentication/AuthenticationService.js:2:289515)
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`3.<EnsureAuthService>d__29[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteUserAccount, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.ApiAuthorizationProviderOptions, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`3.<GetAuthenticatedUser>d__28[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteUserAccount, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.ApiAuthorizationProviderOptions, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`3.<GetUser>d__27[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteUserAccount, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.ApiAuthorizationProviderOptions, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationService`3.<GetAuthenticationStateAsync>d__19[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteUserAccount, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[Microsoft.AspNetCore.Components.WebAssembly.Authentication.ApiAuthorizationProviderOptions, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.Authorization.AuthorizeViewCore.OnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**Comment by FLAMESpl** [comment]
To make server-side rendering work I had to remove `AddApiAuthorization` and add `AddServerSideBlazor()`.
Isn't it an issue with the project template that it does not contain `AddServerSideBlazor()` by default?

**Comment by MackinnonBuck** [comment]
Thanks for reaching out. Could you please provide us with a repro project so we can investigate this further?

Note: If this turns out to be a product bug, it may be addressed as part of https://github.com/dotnet/aspnetcore/issues/52063

**Comment by FLAMESpl** [comment]
I had a misconception about this project template resulting from past dotnet prototypes showing that connection is initiated with interactive server and then switched to interactive webassembly, while currently it is SSR switching to WebAssembly without involving other render types.

Nevertheless, my question is whether `AuthorizedView` is supported in SSR, because per this repro - https://github.com/FLAMESpl/BlazorSSRAuth when `AuthorizedView` is embedded then server throws exception:

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: No service for type 'Microsoft.AspNetCore.Components.Authorization.AuthenticationStateProvider' has been registered.
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.CascadingAuthenticationStateServiceCollectionExtensions.<>c.<AddCascadingAuthenticationState>b__0_0(IServiceProvider services)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer..ctor(IServiceProvider serviceProvider, ILoggerFactory loggerFactory, IComponentActivator componentActivator)
         at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer..ctor(IServiceProvider serviceProvider, ILoggerFactory loggerFactory)
         at Microsoft.AspNetCore.Components.Endpoints.EndpointHtmlRenderer..ctor(IServiceProvider serviceProvider, ILoggerFactory loggerFactory)
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
         at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
         at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
         at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointFactory.<>c.<AddEndpoints>b__1_0(HttpContext httpContext)
         at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by andy250** [comment]
@FLAMESpl Aren't you missing `app.UseAuthorization();` in Program.cs?

**Comment by FLAMESpl** [comment]
I have added it but nothing has changed.

**Comment by halter73** [comment]
`AuthorizedView` is supported, but you need to [set up things like social logins the way you would for a normal server-rendered app](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/social/facebook-logins?view=aspnetcore-8.0) like MVC or Razor Pages which involves configuring the authentication and authorization middleware.

This does mean that in practice, with per-page interactivity, the `<NotAuthorized>` is unnecessary for pages with the `[Authorize]` attribute because any unauthorized request to that page will be redirected by the authorization middleware first before any code gets a chance to run.

The error about a missing `AuthenticationStateProvider` means you need to register one manually. Here are the ones we use in our templates with individual auth for WebAssembly interactivity:

- [Server PersistingServerAuthenticationStateProvider](https://github.com/dotnet/aspnetcore/blob/268a2dfc29b33e3fdb73cbac6eb198c05314d77e/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Account/PersistingServerAuthenticationStateProvider.cs) registered [here](https://github.com/dotnet/aspnetcore/blob/268a2dfc29b33e3fdb73cbac6eb198c05314d77e/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Program.cs#L44).
- [Client PersistentAuthenticationStateProvider](https://github.com/dotnet/aspnetcore/blob/268a2dfc29b33e3fdb73cbac6eb198c05314d77e/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorWeb-CSharp/BlazorWeb-CSharp.Client/PersistentAuthenticationStateProvider.cs) registered [here](https://github.com/dotnet/aspnetcore/blob/268a2dfc29b33e3fdb73cbac6eb198c05314d77e/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorWeb-CSharp/BlazorWeb-CSharp.Client/Program.cs#L12).

**Comment by FLAMESpl** [comment]
All clear to me, thanks!
