### ISSUE TITLE
Quarantine FormWithParentBindingContextTest.CanBindToFormWithFiles

### ISSUE THREAD

**Issue by amcasey** [dotnet/aspnetcore#54447]
## Failing Test(s)

- Microsoft.AspNetCore.Components.E2ETests.ServerRenderingTests.FormHandlingTests.FormWithParentBindingContextTest.CanBindToFormWithFiles

## Error Message

```text
Assert.Throws() Failure
Expected: typeof(OpenQA.Selenium.StaleElementReferenceException)
Actual:   typeof(OpenQA.Selenium.WebDriverException): unknown error: unhandled inspector error: {"code":-32000,"message":"Node with given id does not belong to the document"}
(Session info: chrome=122.0.6261.94)
---- OpenQA.Selenium.WebDriverException : unknown error: unhandled inspector error: {"code":-32000,"message":"Node with given id does not belong to the document"}
(Session info: chrome=122.0.6261.94)
```

## Stacktrace

<details>

```text
at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebElement.GetAttribute(String attributeName)
   at Microsoft.AspNetCore.Components.E2ETests.ServerRenderingTests.FormHandlingTests.FormWithParentBindingContextTest.<>c__DisplayClass73_0.<DispatchToFormCore>b__2() in /home/vsts/work/1/s/src/Components/test/E2ETest/ServerRenderingTests/FormHandlingTests/FormWithParentBindingContextTest.cs:line 1595
----- Inner Stack Trace -----
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebElement.GetAttribute(String attributeName)
   at Microsoft.AspNetCore.Components.E2ETests.ServerRenderingTests.FormHandlingTests.FormWithParentBindingContextTest.<>c__DisplayClass73_0.<DispatchToFormCore>b__2() in /home/vsts/work/1/s/src/Components/test/E2ETest/ServerRenderingTests/FormHandlingTests/FormWithParentBindingContextTest.cs:line 1595
```
</details>

## Logs

<details>

```text
/home/vsts/work/1/s/src/Components/test/E2ETest/ServerRenderingTests/FormHandlingTests/FormWithParentBindingContextTest.cs(1595): error VSTEST1: (Microsoft.AspNetCore.Components.E2ETests.ServerRenderingTests.FormHandlingTests.FormWithParentBindingContextTest.CanBindToFormWithFiles) Microsoft.AspNetCore.Components.E2ETests.ServerRenderingTests.FormHandlingTests.FormWithParentBindingContextTest.<>c__DisplayClass73_0.<DispatchToFormCore>b__2() Assert.Throws() Failure Expected: typeof(OpenQA.Selenium.StaleElementReferenceException) Actual:   typeof(OpenQA.Selenium.WebDriverException): unknown error: unhandled inspector error: {"code":-32000,"message":"Node with given id does not belong to the document"}             (Session info: chrome=122.0.6261.94) ---- OpenQA.Selenium.WebDriverException : unknown error: unhandled inspector error: {"code":-32000,"message":"Node with given id does not belong to the document"}   (Session info: chrome=122.0.6261.94) [/home/vsts/work/1/s/src/Components/test/E2ETest/Microsoft.AspNetCore.Components.E2ETests.csproj]
```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=595165&view=results

Also affected https://github.com/dotnet/aspnetcore/pull/54411
Probably related: https://github.com/dotnet/aspnetcore/issues/49975
Possible fix approach: https://github.com/dotnet/aspnetcore/pull/54340

**Comment by MackinnonBuck** [comment]
The root cause of this problem may affect any test that relies on catching `StaleElementReferenceException` as a way of detecting when an element was removed from the page. I've put this issue in the preview 7 milestone, but if we see similar test failures sooner, we should consider giving this a higher priority.

**Comment by halter73** [comment]
While this might theoretically affect other tests, I haven't seen it myself. And I just saw this test fail again at https://dev.azure.com/dnceng-public/public/_build/results?buildId=608920&view=ms.vss-test-web.build-test-results-tab.
