### ISSUE TITLE
Quarantine NavMenuHighlightsCurrentLocation

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#54497]
## Failing Test(s)

- Microsoft.AspNetCore.Components.E2ETest.Tests.ThreadingAppTest.NavMenuHighlightsCurrentLocation

## Error Message

```text
System.AggregateException : One or more errors occurred. (Xunit.Sdk.NotEmptyException: Assert.NotEmpty() Failure
   at Xunit.Assert.NotEmpty(IEnumerable collection) in /_/src/xunit.assert/Asserts/CollectionAsserts.cs:line 502
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /home/vsts/work/1/s/src/Shared/E2ETesting/WaitAssert.cs:line 101
Screen shot captured at '/home/vsts/work/1/s/src/Components/test/E2ETest/bin/screenshots/8daf92050ee64c50aff7c205ae31e5ed.png'
Page content:
<head>
    <meta charset="utf-8">
    <!-- Forcing the device width here so that our automated tests work consistently on mobile browsers. -->
    <meta name="viewport" content="width=1024">
    <title>Blazor standalone</title>
    <base href="/">
    <link href="bootstrap.min.css" rel="stylesheet">
    <link href="app.css" rel="stylesheet">
</head>
<body>
    <app>Loading...</app>

    <div id="blazor-error-ui">
        An unhandled exception has occurred. See browser dev tools for details.
        <a href="" class="reload">Reload</a>
        <a class="dismiss">\ud83d\uddd9</a>
    </div>

    <script src="_framework/blazor.webassembly.js" autostart="false"></script>
    <script>
        (function(){
            Blazor.start().then(function () {
                window['__aspnetcore__testing__blazor_wasm__started__'] = true;
            });
        })();
    </script>


</body>
) (Xunit.Sdk.NotEqualException: Assert.NotEqual() Failure
Expected: Not "Loading..."
Actual:   "Loading..."
   at Xunit.Assert.NotEqual[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 302
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass17_0.<WaitAssertCore>b__0() in /home/vsts/work/1/s/src/Shared/E2ETesting/WaitAssert.cs:line 83
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /home/vsts/work/1/s/src/Shared/E2ETesting/WaitAssert.cs:line 101
Screen shot captured at '/home/vsts/work/1/s/src/Components/test/E2ETest/bin/screenshots/c6fd42c442f74279a0d295a2a594784c.png'
Encountered browser errors
[2024-03-11T13:57:17Z] [Warning] http://127.0.0.1:33145/_framework/dotnet.runtime.9.0.0-preview.3.24156.1.aovcbg8by0.js 2:18098 "[--000dc9bc-emsc] MONO_WASM: Failed to find unused WebWorker, this may deadlock. Please increase the pthreadPoolReady. Running threads 0. Loading workers: 0"Page content:
<head>
    <meta charset="utf-8">
    <!-- Forcing the device width here so that our automated tests work consistently on mobile browsers. -->
    <meta name="viewport" content="width=1024">
    <title>Blazor standalone</title>
    <base href="/">
    <link href="bootstrap.min.css" rel="stylesheet">
    <link href="app.css" rel="stylesheet">
</head>
<body>
    <app>Loading...</app>

    <div id="blazor-error-ui">
        An unhandled exception has occurred. See browser dev tools for details.
        <a href="" class="reload">Reload</a>
        <a class="dismiss">\ud83d\uddd9</a>
    </div>

    <script src="_framework/blazor.webassembly.js" autostart="false"></script>
    <script>
        (function(){
            Blazor.start().then(function () {
                window['__aspnetcore__testing__blazor_wasm__started__'] = true;
            });
        })();
    </script>


</body>
)
---- OpenQA.Selenium.BrowserAssertFailedException : Xunit.Sdk.NotEmptyException: Assert.NotEmpty() Failure
   at Xunit.Assert.NotEmpty(IEnumerable collection) in /_/src/xunit.assert/Asserts/CollectionAsserts.cs:line 502
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.<>c__DisplayClass18_0`1.<WaitAssertCore>b__0(IWebDriver _) in /home/vsts/work/1/s/src/Shared/E2ETesting/WaitAssert.cs:line 101
Screen shot captured at '/home/vsts/work/1/s/src/Components/test/E2ETest/bin/screenshots/8daf92050ee64c50aff7c205ae31e5ed.png'
Page content:
<head>
    <meta charset="utf-8">
    <!-- Forcing the device width here so that our automated 
```

## Stacktrace

<details>

```text

```
</details>

## Logs

[Standard_Console_Output (9).log](https://github.com/dotnet/aspnetcore/files/14572401/Standard_Console_Output.9.log)

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=597714&view=results

**Comment by MackinnonBuck** [comment]
> `at Microsoft.AspNetCore.Components.E2ETest.Tests.ThreadingAppTest.WaitUntilLoaded()`

Looks like this might also be caused by https://github.com/dotnet/runtime/issues/106788
