### ISSUE TITLE
Microsoft.IdentityModel.JsonWebTokens" Version="7.4.0" not working with OpenIdConnect ? (Microsoft.AspNetCore.Authentication.OpenIdConnect Version 8.0.3))

### ISSUE THREAD

**Issue by Hugoreal2** [dotnet/aspnetcore#54530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

```c#
.AddOpenIdConnect(options =>
{
    options.ClientId = " {clientId}";
    options.ClientSecret = "{clientSecret}";
    options.Authority = "{authority}";

    options.ResponseType = "code";
    options.Scope.Add("role");
    options.Scope.Add("openid");
    options.Scope.Add("email");
});
```

I have an OpenIdConnect service here in my job

Its been working fine, but when I bumped this PackageReference from 7.3.1 to 7.4.0, when I try running my code I get this error
<PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="7.3.1" />

`System.InvalidOperationException: Cannot redirect to the authorization endpoint, the configuration may be missing or invalid.

   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsyncInternal(AuthenticationProperties properties)

   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsync(AuthenticationProperties properties)

   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)

   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)

   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.<>c__DisplayClass0_0.<<HandleAsync>g__Handle|0>d.MoveNext()

--- End of stack trace from previous location ---

   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
`
   
   
   
 The Authority url endpoint responds perfectly.

What I did was basicly do this version bump, clear all cookie values from my browser and try to do OpenIdConnect

### Steps To Reproduce

Clear all cookies from the browser.

Use 
- Microsoft.IdentityModel.JsonWebTokens Version="7.4.0"
- Microsoft.AspNetCore.Authentication.OpenIdConnect Version="8.0.3"

.NET 8

Set on the Startup.cs like I've putted above

### .NET Version

8.0.101

**Comment by tai-yi** [comment]
**Workaround**

set right version <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="7.4.0" />

see https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/2523

**Comment by Hugoreal2** [comment]
Worked like a charm

can close the ticket, thank you so much

**Comment by vijaybadugu** [comment]
even though i passed redirect url, I am error_description:The specified 'redirect_uri' is not valid for this client application.

**Comment by philipbawn** [comment]
This just wasted hours of time for me until I happened upon this.
