### ISSUE TITLE
DataProtectionProvider persist keys to BLOB does not use keys from BLOB

### ISSUE THREAD

**Issue by mjoksa** [dotnet/aspnetcore#54697]
My client already has an issue opened with Microsoft on this - **TrackingID#2402020040006285** that I put here for a reference.
I have used **DataProtectionProvider** with my NET 8 web API to encrypt/decrypt sensitive data.
I have issue with it specifically persisting keys to BLOB storage. 

I have created small solution and attached it in here for easy way to reproduce issue:
1. Create Storage Account in your Azure subscription.
2. Create **data-protection** container in the storage created at step 1.
3. Update provided solution to use connection string for storage account created in step 1.
4. Run application locally.
5. Use provided swagger UI and run API endpoint to encrypt "Test Message". Save the **Message Id** that will be part of the response.
6. Use **Message Id** from previous step with decrypt API endpoint and verify that "Test Message" is what you get.
7. Verify that **key.xml** is create in BLOB.
8. Create App Service in Azure and deploy example.
9. Open up swagger for the App Service you deployed into Azure.
10. Use API endpoint to decrypt with "Message Id" you got in step 5. This will **FAIL**.
11. Take a look into App Service Event Logs and in there you will find error message that there is a missing key in a key ring. This verifies that **DataProtectionProvider** did not use key from BLOB, rather it used local key to encrypt/decrypt.
12. Additional verification for thing stated above is that if you copy proper key from local machine into Azure App Service, then step 10 will **NOT FAIL**.

Additional remark:
This behavior was observed for the first time when Azure App service slots were swapped - MS documentation states that BLOB is meant to solve this issue specifically, but it does not for me.
[DataProtectionTest.zip](https://github.com/dotnet/aspnetcore/files/14724279/DataProtectionTest.zip)

**Comment by amcasey** [comment]
The most useful thing to look at would be Trace level logs from `Microsoft.AspNetCore.DataProtection`.  It sounds like it's falling back to local storage after failing to connect to azure (is hitting Deploy in VS enough to wire up azure auth in app services?).

> if you copy proper key from local machine into Azure App Service

Where are you copying it to?  The keys folder in localappdata?

**Comment by amcasey** [comment]
Next time, please share the repro as a GH repo - we don't generally accept zip files.

**Comment by amcasey** [comment]
It looks like you might not be calling [ProtectKeysWithAzureKeyVault](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.dataprotection.azuredataprotectionkeyvaultkeybuilderextensions.protectkeyswithazurekeyvault?view=azure-dotnet).  That's important for being able to decrypt the key ring (i.e. key.xml).  If you don't specify any protection mechanism, I think it will default to DPAPI on Windows.  There should be a log message if that decryption is what's failing.

**Comment by mjoksa** [comment]
Thank you @amcasey 
I followed your advice and created and shared code repository with you. Please let me know if I need to make this repo public.
Based on your other advice I added [ProtectKeysAzureKeyVault](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.dataprotection.azuredataprotectionkeyvaultkeybuilderextensions.protectkeyswithazurekeyvault?view=azure-dotnet). 
In order to finish setting things up properly, and based on the things stated at [ProtectKeysWithAzureKeyVault](https://learn.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-8.0#protectkeyswithazurekeyvault), specifically this:
> Provide the app with Get, Unwrap Key and Wrap Key permissions to the key vault.  

I added **Key Vault Administrator** role to myself (for local usage) and to app managed identity. I tried with **Key Vault Crypto Service Encryption User** role (based on the things stated in that role description) but that role was not enough, and I did not want to spend too much time trying to figure out what is the right role (official docs does not state this in any matter).
With all that in place I observed that none of the keys were created in application folders, neither local nor in Azure (checked via Kudu console). Also, I've seen logs like below in console:
> Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: Debug: Found key {7f4e0bc9-4c70-4a62-ae7d-5311d41c3258}.
Microsoft.AspNetCore.DataProtection.KeyManagement.DefaultKeyResolver: Debug: Considering key {7f4e0bc9-4c70-4a62-ae7d-5311d41c3258} with expiration date 2024-06-23 16:17:21Z as default key.
'DataProtectionTest.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\System.Text.RegularExpressions.dll'. 
Microsoft.AspNetCore.DataProtection.DecryptorTypeForwardingActivator: Debug: Forwarded activator type request from Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 to Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Culture=neutral
Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.CngCbcAuthenticatedEncryptorFactory: Debug: Opening CNG algorithm 'AES' from provider '(null)' with chaining mode CBC.
Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.CngCbcAuthenticatedEncryptorFactory: Debug: Opening CNG algorithm 'SHA256' from provider '(null)' with HMAC.
Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider: Debug: Using key {7f4e0bc9-4c70-4a62-ae7d-5311d41c3258} as the default key.
Microsoft.AspNetCore.DataProtection.Internal.DataProtectionHostedService: Debug: Key ring with default key {7f4e0bc9-4c70-4a62-ae7d-5311d41c3258} was loaded during application startup.

Now we can get to the final issue.
I used local app to encrypt message and got id (let's call this **localMessageId**) that I then used to decrypt message, and everything was ok. When I used **localMessageId** within Azure app I got an error like shown below.
> System.Security.Cryptography.CryptographicException: The payload was invalid. For more information go to https://aka.ms/aspnet/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.Cng.CbcAuthenticatedEncryptor.DecryptImpl(Byte* pbCiphertext, UInt32 cbCiphertext, Byte* pbAdditionalAuthenticatedData, UInt32 cbAdditionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.Cng.Internal.CngAuthenticatedEncryptorBase.Decrypt(ArraySegment`1 ciphertext, ArraySegment`1 additionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at DataProtectionTest.Services.TestService.UnprotectAsync(String messageId) in C:\Users\Korisnik\Repositories\Kyvoo\DataProtectionTest\DataProtectionTest\Services\TestService.cs:line 52
   at DataProtectionTest.Controllers.TestController.Unprotect(String messageId) in C:\Users\Korisnik\Repositories\Kyvoo\DataProtectionTest\DataProtectionTest\Controllers\TestController.cs:line 39
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

I got same error when I used message id from Azure app with decrypt in local app.

REMARK:
Original app that I first uploaded as ZIP file, used [DataProtectionProvider.Create](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.dataprotection.dataprotectionprovider.create?view=aspnetcore-8.0#microsoft-aspnetcore-dataprotection-dataprotectionprovider-create(system-string)) method. This method, as stated in docs:
> Creates a [DataProtectionProvider](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.dataprotection.dataprotectionprovider?view=aspnetcore-8.0) that store keys in a location based on the platform and operating system.

and will ALWAYS create encryption key on local or Azure machine (checked on local and in Kudu on Azure machine).
Please let me know if you need any more info from me.

**Comment by amcasey** [comment]
Yes, the relevant docs are unfortunately hard to find.  There's a getting started example [here](https://learn.microsoft.com/aspnet/core/host-and-deploy/scaling-aspnet-apps/scaling-aspnet-apps) that demonstrates one way to wire up all the permissions.

**Comment by amcasey** [comment]
> I added Key Vault Administrator role to myself (for local usage) and to app managed identity

I had to do this too.  Seems new - maybe they made the defaults more secure.

Are those stacks local?  After substituting my own connection strings, I was able to get the app working locally.

**Comment by mjoksa** [comment]
App will work both locally and when deployed to Azure.
Problem is that Azure app will fail when it tries to decrypt message that is previously encrypted with local app and vice versa.
In both cases app is using same settings.
Exception is posted in one of the previous posts (**System.Security.Cryptography.CryptographicException**).

**Comment by amcasey** [comment]
> Problem is that Azure app will fail when it tries to decrypt message that is previously encrypted with local app and vice versa.

Sorry, I'm not sure I follow.  The scenario is that you start with file-based storage and then somehow migrate the key ring to azure?

**Comment by mjoksa** [comment]
No.

In short, scenario is that I want to be able to debug app locally with data that Azure app previously stored.
In little more details, let's say that app is web API that is using DataProtectioProvider to encrypt/decrypt sensitive data that will be used internally. Now, I want to debug web API app, but when it is started locally, with same settings as in Azure, it will fail to decrypt sensitive data that Azure app previously encrypted, and it will throw exception I posted previously.

**Comment by amcasey** [comment]
Would you mind trying your scenario with a fresh key vault and storage account?  (A new key vault key and blob storage container would probably suffice, but it's less fidgety to just start fresh.)  My concern is that you have some keys that were created before you started using `ProtectKeysWithAzureKeyVault`.  If so, data encrypted with those keys is likely to cause problems when accessed on different machines.

Another way to check would be to look at the actual XML of the key ring.  Each key should have a line like 
```xml
<encryptedSecret decryptorType="Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor, Microsoft.AspNetCore.DataProtection, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" xmlns="http://schemas.asp.net/2015/03/dataProtection">
```

Except, you specifically _don't_ want to see `DpapiXmlDecryptor` - that's for single-machine use.  All of your keys should be using an azure decryptor.  If they are, I'd expect the scenario you're describing to be possible, so we'd have to investigate what's going wrong.

**Comment by mjoksa** [comment]
I am willing to try with new storage and Key Vault first thing in the morning (it is getting late here).
Here is what I do always in order to reproduce this exception and I would like you to try.
1. Open up solution and update connection string and key vault identifier settings. At this moment there is no data in Azure table.
2. Start app locally.
3. Use encrypt endpoint in swagger to encrypt message and record id from response. now we have our first record in Azure table.
4. Use id from previous step with decrypt endpoint to verify that decrypt will work.
5. Deploy app to Azure.
6. In Azure app try to use id from step 3 with decrypt endpoint. This will FAIL with exception reported in post from above.
REMARK:
If you repeat all steps from above, but this time you start with Azure app and then debug app locally and try to decrypt message it will FAIL with same expcetion.

**Comment by amcasey** [comment]
That took longer than it should have because I'm not very familiar with App Service, but I believe I have a repro.  I'm not totally convinced it's not fallout from my many failed attempts, but I'll investigate tomorrow.  I'd still appreciate if you could try with fresh azure resources.  Thanks!

**Comment by mjoksa** [comment]
I have recreated both storage account and Azure Key Vault, both with different names as I wanted to be sure that Azure will fully recreate them, and app failed as expected.
Here is the log from Azure app event viewer (same error as posted in one of the posts from above):
> Category: Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer
EventId: 2
SpanId: 5f4c5523ca6ad489
TraceId: 3f8181dc415555c352b55bda528931ea
ParentId: 0000000000000000
RequestId: 40001872-0001-f600-b63f-84710c7967bb
RequestPath: /Test/unprotect
Connection ID "17726168138430552166", Request ID "40001872-0001-f600-b63f-84710c7967bb": An unhandled exception was thrown by the application.
Exception: 
System.Security.Cryptography.CryptographicException: The payload was invalid. For more information go to https://aka.ms/aspnet/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.Cng.CbcAuthenticatedEncryptor.DecryptImpl(Byte* pbCiphertext, UInt32 cbCiphertext, Byte* pbAdditionalAuthenticatedData, UInt32 cbAdditionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.Cng.Internal.CngAuthenticatedEncryptorBase.Decrypt(ArraySegment`1 ciphertext, ArraySegment`1 additionalAuthenticatedData)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
   at DataProtectionTest.Services.TestService.UnprotectAsync(String messageId) in C:\Users\Korisnik\Repositories\Kyvoo\DataProtectionTest\DataProtectionTest\Services\TestService.cs:line 52
   at DataProtectionTest.Controllers.TestController.Unprotect(String messageId) in C:\Users\Korisnik\Repositories\Kyvoo\DataProtectionTest\DataProtectionTest\Controllers\TestController.cs:line 39
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()

**Comment by amcasey** [comment]
@mjoksa Thanks for confirming! This seems like it should work, but it's possible there's some constraint I haven't considered.  I'll investigate.

**Comment by amcasey** [comment]
I added an UnprotectAll endpoint and you can see that which messages can be unprotected is exactly complementary between the local and deployed instances:
![image](https://github.com/dotnet/aspnetcore/assets/10508071/10bc907a-45e1-4184-9a71-d25bd917495e)

**Comment by amcasey** [comment]
If you change `AddDataProtection()` to `AddDataProtection().SetApplicationName("MyApplicationName")`, it should work.  Data protection intentionally keeps different apps sharing the same keyring in separate [namespaces](https://learn.microsoft.com/aspnet/core/security/data-protection/consumer-apis/purpose-strings) to improve security in multi-tenant scenarios.  It looks like the default application name is based on the file path of the project, which will obviously be different in App Service.

**Comment by mjoksa** [comment]
@amcasey That fixed the issue. 
Thank you for all the help with this issue.
I create an issue to update official docs with details from our discussion.
