### ISSUE TITLE
Quarantine ThreadingHostedAppTest.{HasHeading,CounterPageCanUseThreads,NavMenuHighlightsCurrentLocation}

### ISSUE THREAD

**Issue by radical** [dotnet/aspnetcore#54761]
## Failing Test(s)

- Microsoft.AspNetCore.Components.E2ETest.Tests.ThreadingHostedAppTest.HasHeading
- Microsoft.AspNetCore.Components.E2ETest.Tests.ThreadingHostedAppTest.CounterPageCanUseThreads
- Microsoft.AspNetCore.Components.E2ETest.Tests.ThreadingHostedAppTest.NavMenuHighlightsCurrentLocation

## Error Message

```text
System.AggregateException : One or more errors occurred. (The HTTP request to the remote WebDriver server for URL http://localhost:41737/session/9662f54080de1ac310270b2711da7249/element timed out after 60 seconds.) (The HTTP request to the remote WebDriver server for URL http://localhost:41737/session/9662f54080de1ac310270b2711da7249/url timed out after 60 seconds.)
---- OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL http://localhost:41737/session/9662f54080de1ac310270b2711da7249/element timed out after 60 seconds.
-------- System.Threading.Tasks.TaskCanceledException : The request was canceled due to the configured HttpClient.Timeout of 60 seconds elapsing.
------------ System.TimeoutException : The operation was canceled.
---------------- System.Threading.Tasks.TaskCanceledException : The operation was canceled.
-------------------- System.IO.IOException : Unable to read data from the transport connection: Operation canceled.
------------------------ System.Net.Sockets.SocketException : Operation canceled
---- OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL http://localhost:41737/session/9662f54080de1ac310270b2711da7249/url timed out after 60 seconds.
-------- System.Threading.Tasks.TaskCanceledException : The request was canceled due to the configured HttpClient.Timeout of 60 seconds elapsing.
------------ System.TimeoutException : The operation was canceled.
---------------- System.Threading.Tasks.TaskCanceledException : The operation was canceled.
-------------------- System.IO.IOException : Unable to read data from the transport connection: Operation canceled.
------------------------ System.Net.Sockets.SocketException : Operation canceled


```

## Stacktrace

<details>

```text

----- Inner Stack Trace #1 (OpenQA.Selenium.WebDriverException) -----
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.FindElement(String mechanism, String value)
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.WaitAssertCore[TResult](IWebDriver driver, Func`1 assertion, TimeSpan timeout) in /home/vsts/work/1/s/src/Shared/E2ETesting/WaitAssert.cs:line 119
   at Microsoft.AspNetCore.E2ETesting.WaitAssert.Exists(IWebDriver driver, By finder) in /home/vsts/work/1/s/src/Shared/E2ETesting/WaitAssert.cs:line 54
   at Microsoft.AspNetCore.Components.E2ETest.Tests.ThreadingHostedAppTest.Dispose() in /home/vsts/work/1/s/src/Components/test/E2ETest/Tests/ThreadingAppHostedTest.cs:line 114
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in /_/src/xunit.execution/Extensions/ReflectionAbstractionExtensions.cs:line 79
----- Inner Stack Trace -----
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.<>c__DisplayClass33_0.<<Execute>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
----- Inner Stack Trace -----

----- Inner Stack Trace -----
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
----- Inner Stack Trace -----

----- Inner Stack Trace #2 (OpenQA.Selenium.WebDriverException) -----
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.WebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.set_Url(String value)
   at Microsoft.AspNetCore.Components.E2ETest.WebDriverExtensions.Navigate(IWebDriver browser, Uri baseUri, String relativeUrl, Boolean noReload) in /home/vsts/work/1/s/src/Components/test/E2ETest/Infrastructure/WebDriverExtensions/WebDriverExtensions.cs:line 
```
</details>

## Logs

<details>

```text

```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=617774&view=results

**Comment by MackinnonBuck** [comment]
It looks like the problem is not test flakiness: It's likely a problem in the .NET WebAssembly runtime: https://github.com/dotnet/runtime/issues/106788

This would also affect https://github.com/dotnet/aspnetcore/issues/54754

**Comment by halter73** [comment]
The corresponding tests in `ThreadingAppTest` fail in the same way. I'm quarantining the following tests with this as the tracking issue in https://github.com/dotnet/aspnetcore/pull/58642:

- Microsoft.AspNetCore.Components.E2ETest.Tests.ThreadingAppTest.HasTitle
- Microsoft.AspNetCore.Components.E2ETest.Tests.ThreadingAppTest.HasHeading
- Microsoft.AspNetCore.Components.E2ETest.Tests.ThreadingAppTest.HasFetchDataPage
- Microsoft.AspNetCore.Components.E2ETest.Tests.ThreadingAppTest.IsStarted

I would have likely quarantined the following tests too, but you cannot have more than one `QuarantinedTestAttribute` per method.


- Microsoft.AspNetCore.Components.E2ETest.Tests.ThreadingAppTest.NavMenuHighlightsCurrentLocation (#54497)
- Microsoft.AspNetCore.Components.E2ETest.Tests.ThreadingAppTest.CounterPageCanUseThreads (#58242)

**Comment by javiercn** [comment]
We have skipped these tests since we don't plan to invest in fixing them in the near future.
