### ISSUE TITLE
Blazor WASM .net 8: VS can not show variables in Locals or Immediate Window

### ISSUE THREAD

**Issue by danielSt-dev** [dotnet/aspnetcore#55055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We have a Blazor WASM App (lets call it host) in .net 8. This app loads other blazor libraries as plugins via AssemblyLoadContexts LoadFromAssemblyPath.

if we hit a breakpoint of the host app we see the local variables via Visual studio immediate window or locals window.

if we hit a breakpoint of a plugin and I want to show the content of a local variable, the following error occurs

```
Uncaught BUG: Unable to get properties for scope: 1. System.Exception: Error resolving scope properties SendDebuggerAgentCommand failed for RefIsDelegate: [Result: IsOk: False, IsErr: True, Value: , Error: {
  "result": {
    "type": "object",
    "subtype": "error",
    "className": "Error",
    "description": "Error: Failed on mono_wasm_send_dbg_command\n    at Object.Bt [as mono_wasm_send_dbg_command] (https://localhost:7123/_framework/dotnet.runtime.8.0.4.ogva3chynz.js:3:21463)\n    at <anonymous>:1:30\n    at mono_wasm_fire_debugger_agent_message_with_data_to_pause (https://localhost:7123/_framework/dotnet.runtime.8.0.4.ogva3chynz.js:3:20935)\n    at mono_wasm_fire_debugger_agent_message_with_data (https://localhost:7123/_framework/dotnet.runtime.8.0.4.ogva3chynz.js:3:154928)\n    at https://localhost:7123/_framework/dotnet.native.wasm:wasm-function[1359]:0x6df67\n    at https://localhost:7123/_framework/dotnet.native.wasm:wasm-function[1467]:0x7557f\n    at https://localhost:7123/_framework/dotnet.native.wasm:wasm-function[1466]:0x74f62\n    at https://localhost:7123/_framework/dotnet.native.wasm:wasm-function[1392]:0x703e9\n    at https://localhost:7123/_framework/dotnet.native.wasm:wasm-function[1356]:0x6ddde\n    at https://localhost:7123/_framework/dotnet.native.wasm:wasm-function[241]:0x
1ba67",
    "objectId": "83209364177904658.2.184"
  },
  "exceptionDetails": {
    "exceptionId": 15,
    "text": "Uncaught",
    "lineNumber": 2,
    "columnNumber": 21456,
    "scriptId": "25",
    "stackTrace": {
      "callFrames": [
        {
          "functionName": "Bt",
          "scriptId": "25",
          "url": "https://localhost:7123/_framework/dotnet.runtime.8.0.4.ogva3chynz.js",
          "lineNumber": 2,
          "columnNumber": 21462
        },
        {
          "functionName": "",
          "scriptId": "774",
          "url": "",
          "lineNumber": 0,
          "columnNumber": 29
        },
        {
          "functionName": "mono_wasm_fire_debugger_agent_message_with_data_to_pause",
          "scriptId": "25",
          "url": "https://localhost:7123/_framework/dotnet.runtime.8.0.4.ogva3chynz.js",
          "lineNumber": 2,
          "columnNumber": 20934
        },
        {
          "functionName": "mono_wasm_fire_debugger_agent_message_with_data",
          "scriptId": "25",
          "url": "https://localhost:7123/_framework/dotnet.runtime.8.0.4.ogva3chynz.js",
          "lineNumber": 2,
          "columnNumber": 154927
        },
        {
          "functionName": "$func1359",
          "scriptId": "26",
          "url": "https://localhost:7123/_framework/dotnet.native.wasm",
          "lineNumber": 0,
          "columnNumber": 450407
        },
        {
          "functionName": "$func1467",
          "scriptId": "26",
          "url": "https://localhost:7123/_framework/dotnet.native.wasm",
          "lineNumber": 0,
          "columnNumber": 480639
        },
        {
          "functionName": "$func1466",
          "scriptId": "26",
          "url": "https://localhost:7123/_framework/dotnet.native.wasm",
          "lineNumber": 0,
          "columnNumber": 479074
        },
        {
          "functionName": "$func1392",
          "scriptId": "26",
          "url": "https://localhost:7123/_framework/dotnet.native.wasm",
          "lineNumber": 0,
          "columnNumber": 459753
        },
        {
          "functionName": "$func1356",
          "scriptId": "26",
          "url": "https://localhost:7123/_framework/dotnet.native.wasm",
          "lineNumber": 0,
          "columnNumber": 450014
        },
        {
          "functionName": "$func241",
          "scriptId": "26",
          "url": "https://localhost:7123/_framework/dotnet.native.wasm",
          "lineNumber": 0,
          "columnNumber": 113255
        },
        {
          "functionName": "$func238",
          "scriptId": "26",
          "url": "https://localhost:7123/_framework/dotnet.native.wasm",
          "lineNumber": 0,
          "columnNumber": 102391
        },
        {
          "functionName": "$func272",
          "scriptId": "26",
          "url": "https://localhost:7123/_framework/dotnet.native.wasm",
          "lineNumber": 0,
          "columnNumber": 119160
        },
        {
          "functionName": "$func3184",
          "scriptId": "26",
          "url": "https://localhost:7123/_framework/dotnet.native.wasm",
          "lineNumber": 0,
          "columnNumber": 951830
        },
        {
          "functionName": "$func2504",
          "scriptId": "26",
          "url": "https://localhost:7123/_framework/dotnet.native.wasm",
          "lineNumber": 0,
          "columnNumber": 779116
        },
        {
          "functionName": "$func2510",
          "scriptId": "26",
          "url": "https://localhost:7123/_framework/dotnet.native.wasm",
          "lineNumber": 0,
          "columnNumber": 781200
        },
        {
          "functionName": "$func2534",
          "scriptId": "26",
          "url": "https://localhost:7123/_framework/dotnet.native.wasm",
          "lineNumber": 0,
          "columnNumber": 791015
        },
        {
          "functionName": "$mono_wasm_invoke_method_bound",
          "scriptId": "26",
          "url": "https://localhost:7123/_framework/dotnet.native.wasm",
          "lineNumber": 0,
          "columnNumber": 42233
        },
        {
          "functionName": "Module._mono_wasm_invoke_method_bound",
          "scriptId": "24",
          "url": "https://localhost:7123/_framework/dotnet.native.8.0.4.rkw194kvb3.js",
          "lineNumber": 7,
          "columnNumber": 123344
        },
        {
          "functionName": "kr",
          "scriptId": "25",
          "url": "https://localhost:7123/_framework/dotnet.runtime.8.0.4.ogva3chynz.js",
          "lineNumber": 2,
          "columnNumber": 35364
        },
        {
          "functionName": "",
          "scriptId": "25",
          "url": "https://localhost:7123/_framework/dotnet.runtime.8.0.4.ogva3chynz.js",
          "lineNumber": 2,
          "columnNumber": 180805
        },
        {
          "functionName": "beginInvokeDotNetFromJS",
          "scriptId": "19",
          "url": "https://localhost:7123/_framework/blazor.webassembly.js",
          "lineNumber": 0,
          "columnNumber": 45107
        },
        {
          "functionName": "invokeDotNetMethodAsync",
          "scriptId": "19",
          "url": "https://localhost:7123/_framework/blazor.webassembly.js",
          "lineNumber": 0,
          "columnNumber": 3955
        },
        {
          "functionName": "invokeDotNetStaticMethodAsync",
          "scriptId": "19",
          "url": "https://localhost:7123/_framework/blazor.webassembly.js",
          "lineNumber": 0,
          "columnNumber": 3323
        },
        {
          "functionName": "",
          "scriptId": "19",
          "url": "https://localhost:7123/_framework/blazor.webassembly.js",
          "lineNumber": 0,
          "columnNumber": 56171
        },
        {
          "functionName": "",
          "scriptId": "19",
          "url": "https://localhost:7123/_framework/blazor.webassembly.js",
          "lineNumber": 0,
          "columnNumber": 32090
        },
        {
          "functionName": "je",
          "scriptId": "19",
          "url": "https://localhost:7123/_framework/blazor.webassembly.js",
          "lineNumber": 0,
          "columnNumber": 32036
        },
        {
          "functionName": "Me",
          "scriptId": "19",
          "url": "https://localhost:7123/_framework/blazor.webassembly.js",
          "lineNumber": 0,
          "columnNumber": 31604
        },
        {
          "functionName": "",
          "scriptId": "19",
          "url": "https://localhost:7123/_framework/blazor.webassembly.js",
          "lineNumber": 0,
          "columnNumber": 22272
        },
        {
          "functionName": "",
          "scriptId": "19",
          "url": "https://localhost:7123/_framework/blazor.webassembly.js",
          "lineNumber": 0,
          "columnNumber": 22286
        },
        {
          "functionName": "",
          "scriptId": "19",
          "url": "https://localhost:7123/_framework/blazor.webassembly.js",
          "lineNumber": 0,
          "columnNumber": 14960
        },
        {
          "functionName": "onGlobalEvent",
          "scriptId": "19",
          "url": "https://localhost:7123/_framework/blazor.webassembly.js",
          "lineNumber": 0,
          "columnNumber": 14948
        }
      ]
    },
    "exception": {
      "type": "object",
      "subtype": "error",
      "className": "Error",
      "description": "Error: Failed on mono_wasm_send_dbg_command\n    at Object.Bt [as mono_wasm_send_dbg_command] (https://localhost:7123/_framework/dotnet.runtime.8.0.4.ogva3chynz.js:3:21463)\n    at <anonymous>:1:30\n    at mono_wasm_fire_debugger_agent_message_with_data_to_pause (https://localhost:7123/_framework/dotnet.runtime.8.0.4.ogva3chynz.js:3:20935)\n    at mono_wasm_fire_debugger_agent_message_with_data (https://localhost:7123/_framework/dotnet.runtime.8.0.4.ogva3chynz.js:3:154928)\n    at https://localhost:7123/_framework/dotnet.native.wasm:wasm-function[1359]:0x6df67\n    at https://localhost:7123/_framework/dotnet.native.wasm:wasm-function[1467]:0x7557f\n    at https://localhost:7123/_framework/dotnet.native.wasm:wasm-function[1466]:0x74f62\n    at https://localhost:7123/_framework/dotnet.native.wasm:wasm-function[1392]:0x703e9\n    at https://localhost:7123/_framework/dotnet.native.wasm:wasm-function[1356]:0x6ddde\n    at https://localhost:7123/_framework/dotnet.native.wasm:wasm-function[241]:
0x1ba67",
      "objectId": "83209364177904658.2.185"
    }
  }
} ]

```

empty locals window in VS:
<img width="518" alt="image" src="https://github.com/dotnet/aspnetcore/assets/58980796/000f1dc5-ee75-40bb-8e37-1d65ed6cc474">

Additional Info: we previously migrated from .net 6 to .net 8. 
In .net 6 the inspection of the variables in this environment worked.

please let me know if you need further info.

### Expected Behavior

Show the local variables with its content in VS local window and immediate window.

### Anything else?

Blazor WASM .net 8
VS 17.9.6
MS Edge Version 123.0.2420.81

dotnet --info:
.NET SDK:
 Version:           8.0.204
 Commit:            c338c7548c
 Workload version:  8.0.200-manifests.7d36c14f

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.204\

Installierte .NET-Workloads:
 [maccatalyst]
   Installationsquelle: VS 17.9.34728.123
   Manifestversion:    17.2.8004/8.0.100
   Manifestpfad:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.2.8004\WorkloadManifest.json
   Installationstyp:              Msi

 [ios]
   Installationsquelle: VS 17.9.34728.123
   Manifestversion:    17.2.8004/8.0.100
   Manifestpfad:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.2.8004\WorkloadManifest.json
   Installationstyp:              Msi

 [maui-windows]
   Installationsquelle: VS 17.9.34728.123
   Manifestversion:    8.0.7/8.0.100
   Manifestpfad:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.7\WorkloadManifest.json
   Installationstyp:              Msi

 [android]
   Installationsquelle: VS 17.9.34728.123
   Manifestversion:    34.0.52/8.0.100
   Manifestpfad:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.52\WorkloadManifest.json
   Installationstyp:              Msi

 [wasm-tools-net6]
   Installationsquelle: VS 17.9.34728.123
   Manifestversion:    8.0.4/8.0.100
   Manifestpfad:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.workload.mono.toolchain.net6\8.0.4\WorkloadManifest.json
   Installationstyp:              Msi

 [wasm-tools]
   Installationsquelle: VS 17.9.34728.123
   Manifestversion:    8.0.4/8.0.100
   Manifestpfad:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.workload.mono.toolchain.current\8.0.4\WorkloadManifest.json
   Installationstyp:              Msi

Host:
  Version:      8.0.4
  Architecture: x64
  Commit:       2d7eea2529

.NET SDKs installed:
  8.0.100-rc.1.23463.5 [C:\Program Files\dotnet\sdk]
  8.0.204 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-rc.1.23421.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-rc.1.23419.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-rc.1.23420.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by danielSt-dev** [comment]
one further info insight:

the error only occurs if the methods in components are async

`
    protected override void OnInitialized() {
        base.OnInitialized();
        //immediate window and locals window are fine
    }

    protected async override Task OnInitializedAsync() {
        await base.OnInitializedAsync()
        //immediate window and locals window shows described error
    }`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. This is not part of the runtime feature-set. Please use the [VS Feedback](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019) to report this issue, so the team who owns the area can track the ask.
