### ISSUE TITLE
[dotnet-sdk-9.0.100-preview.4.24209.6] When launch the WorldExplorer homepage, it shows an error "An item with the same key has already been added. Key: Content-Security-Policy"

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/aspnetcore#55054]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When we run WorldExplorer\WebApp.exe with dotnet-sdk-9.0.100-preview.2.24157.14-win-x64 or higher version. It will show error: An unhandled exception occurred while processing the request. ArgumentException: An item with the same key has already been added. Key: Content-Security-Policy.

**Application Name:** WorldExplorer
**OS:** Windows 10 22H2
**CPU:** X64
**.NET Build Number:** dotnet-sdk-9.0.100-preview.4.24209.6
**Github Link:** 
https://github.com/VladislavAntonyuk/WorldExplorer
**Or App Source checking at** https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2021679

**Verify Scenarios:** 
1. Windows10 21h2 x64 + dotnet-sdk-9.0.100-preview.4.24209.6: Fail
2. Windows10 21h2 x64 + dotnet-sdk-9.0.100-preview.3.24175.24-win-x64: Fail
3. Windows10 21h2 x64 + dotnet-sdk-9.0.100-preview.2.24157.14-win-x64: Fail
4. Windows10 21h2 x64 + dotnet-sdk-9.0.100-preview.1.24101.2-win-x64: Pass
5. Windows10 21h2 x64 + dotnet-sdk-8.0.202: Pass

### Expected Behavior

App run successfully.

### Steps To Reproduce

**Minimal Repro steps (Demo attached [BlazorAppDemo.zip](https://github.com/dotnet/aspnetcore/files/14930173/BlazorAppDemo.zip)):**  

**The machine has dotnet-sdk-9.0.100-preview.4.24209.6 installed.**
1. Create a new .NET 8.0 Blazor Server App.
2. Install OwaspHeaders.Core and add ```"app.UseSecureHeadersMiddleware();" ```before ```"app.run();"``` in programs.cs.
3. Build the app and change the runtime to .NET 9.0:
```
"frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "9.0.0-preview.4.24204.3"
      },
      {
        "name": "Microsoft.AspNetCore.App",
        "version": "9.0.0-preview.4.24205.2"
      }
    ]
```
5. Run the app and visit homepage.

### Exceptions (if any)

**Actual Result:** 
Show error:
An unhandled exception occurred while processing the request.
ArgumentException: An item with the same key has already been added. Key: Content-Security-Policy

### .NET Version

9.0.100-preview.4.24209.6

### Anything else?

**Findings**
We find “Content-Security-Policy” is already present in Response Header when run the Blazor Server App with dotnet-sdk-9.0.100-preview.2.24157.14-win-x64 or higher version. So, It will show error when we use "app.UseSecureHeadersMiddleware();" to add "Content-Security-Policy" again.

**dotnet info:**
```
.NET SDK:
Version:           9.0.100-preview.4.24209.6
Commit:            7747841414
Workload version:  9.0.100-manifests.0a830cf1
MSBuild version:   17.11.0-preview-24178-16+7ca3c98fa

Runtime Environment:
OS Name:     Windows
OS Version:  10.0.19045
OS Platform: Windows
RID:         win-x64
Base Path:   C:\Program Files\dotnet\sdk\9.0.100-preview.4.24209.6\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      9.0.0-preview.4.24204.3
  Architecture: x64
  Commit:       ffb257818d

.NET SDKs installed:
  9.0.100-preview.4.24209.6 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-preview.4.24205.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-preview.4.24204.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.4.24204.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
@dotnet-actwx-bot @dotnet/compat

**Comment by efonsecab** [comment]
I have the same issue when using a .NET Aspire Preview 4 with .NET 9.
This is the complete Stack Trace


System.ArgumentException: An item with the same key has already been added. Key: Content-Security-Policy
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseHeaders.AddValueUnknown(String key, StringValues value)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseHeaders.AddValueFast(String key, StringValues value)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.System.Collections.Generic.IDictionary<System.String,Microsoft.Extensions.Primitives.StringValues>.Add(String key, StringValues value)
   at Microsoft.AspNetCore.Builder.ServerRazorComponentsEndpointConventionBuilderExtensions.<>c__DisplayClass1_1.<<AddInteractiveServerRenderMode>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Aspire.Dashboard.Model.ValidateTokenMiddleware.InvokeAsync(HttpContext context) in /_/src/Aspire.Dashboard/Model/ValidateTokenMiddleware.cs:line 71
   at Aspire.Dashboard.DashboardWebApplication.<>c.<<-ctor>b__16_2>d.MoveNext() in /_/src/Aspire.Dashboard/DashboardWebApplication.cs:line 207
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

**Comment by Junjun-zhao** [comment]
Verified this issue with the latest dotnet-sdk-9.0.100-preview.5.24227.1, it has been fixed. Hense closing it. Thanks.
