### ISSUE TITLE
Support custom task types in Minimal API endpoints

### ISSUE THREAD

**Issue by ericmutta** [dotnet/aspnetcore#55118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

I am trying to map a minimal API endpoint as follows:

```csharp
  ArgApp.MapPost("/api/create-account", CreateAccount.HandleHttpAsync);
```

...the endpoint itself is defined with this signature:

```csharp
 public static async AwaitOnceTask<Response> HandleHttpAsync(HttpRequest ArgRequest, IServiceProvider ArgServices) { }
```

When I try to run my app, I get the following exception message and stack trace:

```text
System.NotSupportedException: Unsupported return type: AwaitOnceTask<CreateAccount.Response>
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.PopulateBuiltInResponseTypeMetadata(Type returnType, EndpointBuilder builder)
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.CreateArgumentsAndInferMetadata(MethodInfo methodInfo, RequestDelegateFactoryContext factoryContext)
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.InferMetadata(MethodInfo methodInfo, RequestDelegateFactoryOptions options)
         at Microsoft.AspNetCore.Routing.RouteEndpointDataSource.CreateRouteEndpointBuilder(RouteEntry entry, RoutePattern groupPrefix, IReadOnlyList`1 groupConventions, IReadOnlyList`1 groupFinallyConventions)
         at Microsoft.AspNetCore.Routing.RouteEndpointDataSource.get_Endpoints()
```

The problem seems to be the return type `AwaitOnceTask<CreateAccount.Response>` which uses a custom task type I have created called `AwaitOnceTask<T>`.

### Describe the solution you'd like

The docs [currently say](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/responses?view=aspnetcore-8.0) that:

> Minimal endpoints support the following types of return values:
> 1. string - This includes `Task<string>` and `ValueTask<string>`.
> 1. T (Any other type) - This includes `Task<T>` and `ValueTask<T>`.
> 1. IResult based - This includes `Task<IResult>` and `ValueTask<IResult>`.

...this means support for async endpoints is already included but seems to be hardcoded to just `Task<T>` or `ValueTask<T>` . It would be great if the logic in `Microsoft.AspNetCore.Http.RequestDelegateFactory` was written to support any [task type that can be defined in C#](https://github.com/dotnet/roslyn/blob/main/docs/features/task-types.md), not just the native `Task<T>` or `ValueTask<T>`.

**Comment by ericmutta** [comment]
CC: @danmoseley ...I just started using Minimal APIs which have come a very long way in .NET 8 (which also happens to be the first .NET that contains code I had the pleasure of contributing 😃)...this issue may be one of the remaining edge cases to address in coming releases of .NET 👍

**Comment by captainsafia** [comment]
@ericmutta Thanks for reporting this!

It's a compelling feature but there's definitely a hefty testing/design requirement for this one. I'll stick this in the backlog for now to track interest in it. When we do approach this issue, we should think about:

- How this intersects with endpoints filters on an application
- How this intersects with ApiExplorer/OpenAPI tooling
- How to make sure this is compatible with the static code generation story for minimal APIs via Request Delegate Generator

**Comment by ericmutta** [comment]
Many thanks @captainsafia for following up 👍

**Comment by Youssef1313** [comment]
This sounds like a duplicate of #40554.
