### ISSUE TITLE
Flaky test `Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProviderTests.MultipleThreadsForceRefresh`

### ISSUE THREAD

**Issue by MackinnonBuck** [dotnet/aspnetcore#55227]
## Failing Test(s)

* `Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProviderTests.MultipleThreadsForceRefresh`

## Error Message

```text
Moq.MockException :
Expected invocation on the mock at most 9 times, but was 10 times: o => o.GetCacheableKeyRing(It.IsAny<DateTimeOffset>())


Configured setups:
ICacheableKeyRingProvider o => o.GetCacheableKeyRing(3/1/2015 12:00:00 AM +00:00)


Performed invocations:
ICacheableKeyRingProvider.GetCacheableKeyRing(3/1/2015 12:00:00 AM +00:00)
ICacheableKeyRingProvider.GetCacheableKeyRing(3/1/2015 12:00:00 AM +00:00)
ICacheableKeyRingProvider.GetCacheableKeyRing(3/1/2015 12:00:00 AM +00:00)
ICacheableKeyRingProvider.GetCacheableKeyRing(3/1/2015 12:00:00 AM +00:00)
ICacheableKeyRingProvider.GetCacheableKeyRing(3/1/2015 12:00:00 AM +00:00)
ICacheableKeyRingProvider.GetCacheableKeyRing(3/1/2015 12:00:00 AM +00:00)
ICacheableKeyRingProvider.GetCacheableKeyRing(3/1/2015 12:00:00 AM +00:00)
ICacheableKeyRingProvider.GetCacheableKeyRing(3/1/2015 12:00:00 AM +00:00)
ICacheableKeyRingProvider.GetCacheableKeyRing(3/1/2015 12:00:00 AM +00:00)
ICacheableKeyRingProvider.GetCacheableKeyRing(3/1/2015 12:00:00 AM +00:00)
```

## Stacktrace

<details>

```text
   at Moq.Mock.VerifyCalls(Mock targetMock, InvocationShape expectation, LambdaExpression expression, Times times, String failMessage)
   at Moq.Mock.Verify[T,TResult](Mock`1 mock, Expression`1 expression, Times times, String failMessage)
   at Moq.Mock`1.Verify[TResult](Expression`1 expression, Times times)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProviderTests.MultipleThreadsForceRefresh(Boolean failsToReadKeyRing) in /_/src/DataProtection/DataProtection/test/Microsoft.AspNetCore.DataProtection.Tests/KeyManagement/KeyRingProviderTests.cs:line 870
```
</details>

## Build

* https://dev.azure.com/dnceng-public/public/_build/results?buildId=648786&view=ms.vss-test-web.build-test-results-tab
* https://dev.azure.com/dnceng-public/public/_build/results?buildId=649264&view=ms.vss-test-web.build-test-results-tab
* https://dev.azure.com/dnceng-public/public/_build/results?buildId=649670&view=ms.vss-test-web.build-test-results-tab

**Comment by amcasey** [comment]
That was fast.

**Comment by amcasey** [comment]
Both `failsToReadKeyRing: True` and `failsToReadKeyRing: False` are affected.  Seems more common on Ubuntu, but happens on Windows too.

I'm a little curious why this didn't fail in several CI runs during the PR itself.

**Comment by amcasey** [comment]
FWIW, the test is racy, so I'm not that concerned that this could be a product bug.

**Comment by amcasey** [comment]
As you might expect, it passes 1000X in a row locally.  I'll try the mitigations I recommended when I wrote it.  If they don't work, we can probably just delete the test.
