### ISSUE TITLE
OpenIdConnect .well-known/openid-configuration partially read

### ISSUE THREAD

**Issue by matburton** [dotnet/aspnetcore#55355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If you take the latest versions of `Microsoft.AspNetCore.Authentication.OpenIdConnect` (`8.0.4`) and `Microsoft.IdentityModel.Tokens` (`7.5.1`) then `OpenIdConnectConfigurationSerializer` does not read all of the JSON properties in the OIDC authority's .well-known/openid-configuration document.

### Expected Behavior

OpenIdConnectConfigurationSerializer should parse all expected properties.

### Steps To Reproduce

Here's a project containing a test to illustrate:

`Reproduction.csproj`:
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="8.0.4" />
        <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="7.5.1" />
        <PackageReference Include="NUnit" Version="4.1.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
    </ItemGroup>
</Project>
```

`Tests.cs`:
```cs

using Microsoft.IdentityModel.Protocols;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;

using NUnit.Framework;

namespace Reproduction;

internal sealed class Tests
{
    [TestCase("""
              { "authorization_endpoint":"https://an.example/authorize",
                "token_endpoint":"https://an.example/token" }
              """)]
    [TestCase("""
              { "token_endpoint":"https://an.example/token",
                "authorization_endpoint":"https://an.example/authorize" }
              """)]
    public async Task Can_parse_well_known(string json)
    {
        var config = await OpenIdConnectConfigurationRetriever.GetAsync
            ("-", new FakeDocumentRetriever(json), CancellationToken.None);
        
        Assert.That(config.TokenEndpoint, 
                    Is.EqualTo("https://an.example/token"));

        Assert.That(config.AuthorizationEndpoint,
                    Is.EqualTo("https://an.example/authorize"));
    }

    private sealed class FakeDocumentRetriever(string json) : IDocumentRetriever
    {
        public Task<string> GetDocumentAsync
            (string address, CancellationToken cancel) =>
            Task.FromResult(json);
    }
}
```

### .NET Version

8.0.204

### Anything else?

`OpenIdConnectConfigurationSerializer.Read` calls `reader.Read()` in a `while` loop, then calls `JsonSerializerPrimitives.ReadString` to parse values, but that also calls `reader.Read()` meaning the next JSON token is skipped.

**Comment by mkArtakMSFT** [comment]
@jennyf19 do you have a tracking issue for this already, that we can dupe against?

**Comment by halter73** [comment]
> I suspect this is the same as https://github.com/dotnet/aspnetcore/issues/55194

@matburton I suspect you're right. If you add the following to your csproj, does it fix your issue?

```csproj
<PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="7.5.1" />
```

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/2513 is tracking the issue related to mismatched IdentityModel dependencies causing hard-to-diagnose errors. The current plan appears to produce a build-time warning, but I'm not sure what the timeframe for adding that warning is.

The right thing to do would be to avoid breaking changes to Microsoft.IdentityModel.Tokens, particularly changes that break older Microsoft.IdentityModel.Protocols.OpenIdConnect versions in such a severe and hard-to-diagnose way. If breaking changes absolutely must be made (which is rarely really the case since you can always add new APIs rather than breaking old ones), Microsoft.IdentityModel.Protocols.OpenIdConnect should include max versions for Microsoft.IdentityModel.Tokens and its other IdentityModel dependencies. Maybe all IdentityModel packages should have max versions on their IdentityModel dependencies since breaking changes are so common. Obviously, it's too late to do that for packages that already shipped, but it might be worthwhile going forward.

@jennyf19 @keegan-caruso

**Comment by matburton** [comment]
> @matburton I suspect you're right. If you add the following to your csproj, does it fix your issue?
> 
> ```
> <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="7.5.1" />
> ```

Yes that causes the tests to pass.

**Comment by asos-wagnerramos** [comment]
I'm facing the same issue here. It's skipping the properties from JSON. It reads the first property, skips the second, reads the third property and skips the fourth and it's going on.

The issue seems in the class OpenIdConnectConfigurationSerializer. When it reads the property value, it passes true to the parameter `read`, making the `reader.Read()`. Then it goes to the while statement and executes the `reader.read()` again.

The issue is that the `reader.read()` is being executed twice.

**Comment by bitbltr** [comment]
I was getting an error and it took hours before I stumbled across this issue. I was completely stuck.

```Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll
An exception of type 'System.InvalidOperationException' occurred in System.Private.CoreLib.dll but was not handled in user code
IDX20803: Unable to obtain configuration from: 'https://localhost:5001/.well-known/openid-configuration'. Will retry at '11/26/2024 09:11:34 +00:00'. Exception: 'System.InvalidOperationException: Cannot compare the value of a token type 'EndObject' to text.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExpectedStringComparison(JsonTokenType tokenType)
   at System.Text.Json.Utf8JsonReader.ValueTextEquals(ReadOnlySpan`1 utf8Text)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationSerializer.Read(Utf8JsonReader& reader, OpenIdConnectConfiguration config)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationSerializer.Read(String json, OpenIdConnectConfiguration config)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationSerializer.Read(String json)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)'.
```

**Comment by Thomas-X** [comment]
Just want to add that this issue is pretty ugly, as it took me hours digging into the internal code to see that the serialization did in fact not read my perfectly valid JSON. 

This should've never entered a production release, how did tests not catch this? Or simple human testing?

**Comment by jmevel** [comment]
I can't agree more with Thomas, this issue is quite ugly. 
Renovate upgraded a bunch of MINOR dependencies in our project and we ended up with a runtime issue while trying to authenticate users 

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://REDACTED/.well-known/openid-configuration'. Will retry at '03/07/2025 12:56:35 +00:00'. Exception: 'System.InvalidOperationException: Cannot compare the value of a token type 'EndObject' to text.
         at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExpectedStringComparison(JsonTokenType tokenType)
         at System.Text.Json.Utf8JsonReader.ValueTextEquals(ReadOnlySpan`1 utf8Text)
         at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationSerializer.Read(Utf8JsonReader& reader, OpenIdConnectConfiguration config)
         at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationSerializer.Read(String json, OpenIdConnectConfiguration config)
         at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationSerializer.Read(String json)
         at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
         at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)'.
       ---> System.InvalidOperationException: Cannot compare the value of a token type 'EndObject' to text.
         at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExpectedStringComparison(JsonTokenType tokenType)
         at System.Text.Json.Utf8JsonReader.ValueTextEquals(ReadOnlySpan`1 utf8Text)
         at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationSerializer.Read(Utf8JsonReader& reader, OpenIdConnectConfiguration config)
         at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationSerializer.Read(String json, OpenIdConnectConfiguration config)
         at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationSerializer.Read(String json)
         at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
         at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
         --- End of inner exception stack trace ---
         at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
         at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsyncInternal(AuthenticationProperties properties)
         at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsync(AuthenticationProperties properties)
         at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
         at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
         at Duende.Bff.BffAuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties) in /_/src/Duende.Bff/EndpointProcessing/BffAuthenticationService.cs:line 45
         at Duende.Bff.DefaultLoginService.ProcessRequestAsync(HttpContext context) in /_/src/Duende.Bff/EndpointServices/Login/DefaultLoginService.cs:line 83
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
```

Setting `Microsoft.IdentityModel.Protocols.OpenIdConnect` to version `7.7.1` or even `7.5.1` in our `Directory.Packages.props` file did not solve the issue. I've been investigating this issue for a few hours now. Rolling back the Renovate commit altogether.

I honestly don't understand why this issue has been closed as `Not planned`. Should have stayed open at the very least.

**Comment by smintrh78** [comment]
Same for me. Ugly issue. I only found this bug report after debugging into the code.
