### ISSUE TITLE
System.InvalidOperationException: This request does not have a Content-Type header. Forms are available from requests with bodies like POSTs and a form Content-Type of either application/x-www-form-urlencoded or multipart/form-data

### ISSUE THREAD

**Issue by BusHero** [dotnet/aspnetcore#55387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A minimal API post endpoint, that awaits form data generates 500 if the client sends a request to it with no form data

### Expected Behavior

API should return 400?

### Steps To Reproduce

https://github.com/BusHero/BugWithMinimalApi

### Exceptions (if any)

```
System.InvalidOperationException: This request does not have a Content-Type header. Forms are available from requests with bodies like POSTs and a form Content-Type of either application/x-www-form-urlencoded or multipart/form-data.
         at Microsoft.AspNetCore.Http.Features.FormFeature.ReadForm()
         at lambda_method1(Closure, Object, HttpContext, Object)
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass104_2.<<HandleRequestBodyAndCompileRequestDelegateForForm>b__2>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### .NET Version

8.0

### Anything else?

```
> dotnet --info
.NET SDK:
 Version:           8.0.204
 Commit:            c338c7548c
 Workload version:  8.0.200-manifests.9f663350

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22635
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.204\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.4
  Architecture: x64
  Commit:       2d7eea2529

.NET SDKs installed:
  8.0.204 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.29 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by captainsafia** [comment]
@BusHero Thanks for reporting this issue!

The exception that you're seeing comes from lower in the ASP.NET Core stack in the `FormFeature` when we eagerly attempt to read from the form body if we encounter a parameter that should bind from it.

We've made some changes to the form binding behavior in .NET 9 and I'm not able to repro the issue there. Can yo confirm the same using a 9.0-preview?

I'll put this in the backlog to gather signal on whether this is worth backporting.

**Comment by BusHero** [comment]
Hi @captainsafia. I can confirm that the issue is not reproducible using 9.0-preview.

**Comment by Ganesh-Ponipireddy** [comment]
Hi @captainsafia 
Is there a fix planned to provided in the dotnet 8.x version as well?

**Comment by captainsafia** [comment]
@Ganesh-Ponipireddy We don't plan on backporting this to 8.x at the moment. Are you running into this issue currently? If so, I can share a workaround that might help.

**Comment by Ganesh-Ponipireddy** [comment]
> @Ganesh-Ponipireddy We don't plan on backporting this to 8.x at the moment. Are you running into this issue currently? If so, I can share a workaround that might help.

Thanks for your reply. Yes, I'm facing this issue in my environment. Please provide the workaround and that will help us.

**Comment by captainsafia** [comment]
@Ganesh-Ponipireddy Here's an example of an approach you can use by taking advantage of the fact that the content-type check that throws the exception is skipped if the `Form` is explicitly set. You'll want to apply the workaround only for the request paths that bind from a form and don't have any content.

```csharp
using Microsoft.AspNetCore.Mvc;

var builder = WebApplication.CreateBuilder(args);

var app = builder.Build();

app.Use((context, next) =>
{
    // Only apply workarounds to routes that take form arguments.
    if (context.Request.Path == "/" && context.Request.ContentLength == 0)
    {
        context.Request.Form = new FormCollection(new());
    }
    return next(context);
});

app.MapPost("/", ([FromForm] string id) => Results.Ok(id))
    .DisableAntiforgery();

app.Run();
```

**Comment by Dooks123** [comment]
I am on dotnet 9.0.101 and facing this issue.

**Comment by captainsafia** [comment]
@Dooks123 Can you file a new issue with a complete repro?

Considering the original bug report has been resolved and a workaround has been provided for versions of ASP.NET that don't have the fix, I'm going to close this issue out to keep our issue tracker clean.
