### ISSUE TITLE
FileStreamResultExecutor does not support DisposeAsync

### ISSUE THREAD

**Issue by ascott18** [dotnet/aspnetcore#55441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

FileStreamResultExecutor.ExecuteAsync should use `await using (result.FileStream)` instead of `using (result.FileStream)`. https://github.com/dotnet/aspnetcore/blob/923b62f1d56cadfcef43b70df3940a9324c8391d/src/Mvc/Mvc.Core/src/Infrastructure/FileStreamResultExecutor.cs#L31

https://github.com/dotnet/aspnetcore/blob/be9a344ae4f6115418f14927620444f5f59cd87f/src/Shared/ResultsHelpers/FileResultHelper.cs#L33 is another such location.

### Expected Behavior

Streams that require DisposeAsync (that throw for usage of sync Dispose) can be used with FileStreamResult.

### Steps To Reproduce

``` c#
[HttpGet]
public IActionResult Example()
{
    // ToStream from https://www.nuget.org/packages/EnumerableToStream/
    var stream = Producer().ToStream();

    return new FileStreamResult(stream, "text/plain");
}

private async IAsyncEnumerable<string> Producer()
{
    yield return "foo";
    await Task.Delay(10);
    yield return "bar";
}
```

### Exceptions (if any)

```
System.NotSupportedException: Please use DisposeAsync() instead.
         at EnumerableToStream.StreamOverAsyncEnumerable.Dispose(Boolean disposing)
         at System.IO.Stream.Close()
         at Microsoft.AspNetCore.Mvc.Infrastructure.FileStreamResultExecutor.ExecuteAsync(ActionContext context, FileStreamResult result)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|22_0(ResourceInvoker invoker, IActionResult result)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
```

### .NET Version

8.0.101

**Comment by captainsafia** [comment]
@ascott18 Thanks for reporting this issue! It seems like a sensible improvement to me. Would you be interested in submitting a PR with this change?
