### ISSUE TITLE
Quarantine ProtectedUserStoreTest.CanFindById

### ISSUE THREAD

**Issue by JamesNK** [dotnet/aspnetcore#55476]
## Failing Test(s)

- Microsoft.AspNetCore.Identity.EntityFrameworkCore.Test.ProtectedUserStoreTest.CanFindById

## Error Message

```text
System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'SQLitePCL.sqlite3'.
```

## Stacktrace

<details>

```text
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_create_function(sqlite3 db, Byte[] name, Int32 nargs, Int32 flags, Object v, delegate_function_scalar func)
   at SQLitePCL.raw.sqlite3_create_function(sqlite3 db, String name, Int32 nArg, Int32 flags, Object v, delegate_function_scalar func)
   at SQLitePCL.raw.sqlite3_create_function(sqlite3 db, String name, Int32 nArg, Object v, delegate_function_scalar func)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.UserManager`1.FindByNameAsync(String userName) in /_/src/Identity/Extensions.Core/src/UserManager.cs:line 538
   at Microsoft.AspNetCore.Identity.UserValidator`1.ValidateUserName(UserManager`1 manager, TUser user) in /_/src/Identity/Extensions.Core/src/UserValidator.cs:line 69
   at Microsoft.AspNetCore.Identity.UserValidator`1.ValidateAsync(UserManager`1 manager, TUser user) in /_/src/Identity/Extensions.Core/src/UserValidator.cs:line 44
   at Microsoft.AspNetCore.Identity.UserManager`1.ValidateUserAsync(TUser user) in /_/src/Identity/Extensions.Core/src/UserManager.cs:line 2312
   at Microsoft.AspNetCore.Identity.UserManager`1.CreateAsync(TUser user) in /_/src/Identity/Extensions.Core/src/UserManager.cs:line 465
   at Microsoft.AspNetCore.Identity.Test.UserManagerSpecificationTestBase`2.CanFindById() in /_/src/Identity/Specification.Tests/src/UserManagerSpecificationTests.cs:line 345
--- End of stack trace from previous location ---
```
</details>

## Logs

[console.88e996ac.txt](https://github.com/dotnet/aspnetcore/files/15182482/console.88e996ac.txt)

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=662259&view=ms.vss-test-web.build-test-results-tab&runId=16416972&resultId=121927&paneView=dotnet-dnceng.dnceng-anon-build-release-tasks.helix-anon-test-information-tab

**Comment by JamesNK** [comment]
Note: This test **hasn't** been quarantined because it lives on the public `UserManagerSpecificationTestBase`.

**Comment by MackinnonBuck** [comment]
Closing since it doesn't look like this test has failed in a while.
