### ISSUE TITLE
Build failure on github.com/dotnet/dotnet codespace

### ISSUE THREAD

**Issue by jozkee** [dotnet/aspnetcore#55499]
using Default devcontainer https://github.com/dotnet/dotnet/blob/main/.devcontainer/devcontainer.json and executing `./build.sh`, I consistently hit the following error once build starts for aspnetcore.

```
Intermediate Output Path: /workspaces/dotnet/src/aspnetcore/artifacts/obj/Npm.Workspace/Release/
node:fs:582
  return binding.open(
                 ^

EXEC : error : /workspaces/dotnet/src/aspnetcore/artifacts/obj/Npm.Workspace/Release/packagesToPack.json: ENOENT: no such file or directory, open '/workspaces/dotnet/src/aspnetcore/artifacts/obj/Npm.Workspace/Release/packagesToPack.json' [/workspaces/dotnet/src/aspnetcore/eng/Npm.Workspace.nodeproj]
    at Object.openSync (node:fs:582:18)
    at Object.readFileSync (node:fs:461:35)
    at readFileSync (/workspaces/dotnet/src/aspnetcore/node_modules/jsonfile/index.js:50:22)
    at file:///workspaces/dotnet/src/aspnetcore/eng/scripts/npm/pack-workspace.mjs:54:26
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/workspaces/dotnet/src/aspnetcore/artifacts/obj/Npm.Workspace/Release/packagesToPack.json'
}

Node.js v20.12.2
/workspaces/dotnet/src/aspnetcore/eng/Npm.Workspace.nodeproj(68,5): error MSB3073: The command "node /workspaces/dotnet/src/aspnetcore/eng/scripts/npm/pack-workspace.mjs --create-packages /workspaces/dotnet/src/aspnetcore/package.json 9.0.0dev.24225.4 /workspaces/dotnet/src/aspnetcore/artifacts/packages/Release/Shipping/ /workspaces/dotnet/src/aspnetcore/artifacts/obj/Npm.Workspace/Release/" exited with code 1.

Build FAILED.

EXEC : error : /workspaces/dotnet/src/aspnetcore/artifacts/obj/Npm.Workspace/Release/packagesToPack.json: ENOENT: no such file or directory, open '/workspaces/dotnet/src/aspnetcore/artifacts/obj/Npm.Workspace/Release/packagesToPack.json' [/workspaces/dotnet/src/aspnetcore/eng/Npm.Workspace.nodeproj]
/workspaces/dotnet/src/aspnetcore/eng/Npm.Workspace.nodeproj(68,5): error MSB3073: The command "node /workspaces/dotnet/src/aspnetcore/eng/scripts/npm/pack-workspace.mjs --create-packages /workspaces/dotnet/src/aspnetcore/package.json 9.0.0dev.24225.4 /workspaces/dotnet/src/aspnetcore/artifacts/packages/Release/Shipping/ /workspaces/dotnet/src/aspnetcore/artifacts/obj/Npm.Workspace/Release/" exited with code 1.
  0 Warning(s)
  2 Error(s)
```

cc @ViktorHofer @wtgodbe @mthalman @MichaelSimons @javiercn

**Comment by wtgodbe** [comment]
Could you attach more logs from the failure? We've seen failures in our node projects on CodeSpaces before, which were fixed by increasing the number of cores used in the default devcontainer: https://github.com/dotnet/aspnetcore/issues/55272, https://github.com/dotnet/aspnetcore/pull/55479

CC @javiercn @captainsafia

**Comment by wtgodbe** [comment]
Or, I wonder if this is due to `dotnet/dotnet` not initializing the `node-externals` submodule?

**Comment by Jozkee** [comment]
Logs from /workspaces/dotnet/artifacts/log/Release:
[vstest.log](https://github.com/dotnet/aspnetcore/files/15252679/vstest.log)
[xdt.log](https://github.com/dotnet/aspnetcore/files/15252680/xdt.log)
[arcade.log](https://github.com/dotnet/aspnetcore/files/15252681/arcade.log)
[aspire.log](https://github.com/dotnet/aspnetcore/files/15252682/aspire.log)
[aspnetcore.log](https://github.com/dotnet/aspnetcore/files/15252683/aspnetcore.log)
[cecil.log](https://github.com/dotnet/aspnetcore/files/15252684/cecil.log)
[command-line-api.log](https://github.com/dotnet/aspnetcore/files/15252685/command-line-api.log)
[deployment-tools.log](https://github.com/dotnet/aspnetcore/files/15252686/deployment-tools.log)
[diagnostics.log](https://github.com/dotnet/aspnetcore/files/15252687/diagnostics.log)
[efcore.log](https://github.com/dotnet/aspnetcore/files/15252688/efcore.log)
[emsdk.log](https://github.com/dotnet/aspnetcore/files/15252689/emsdk.log)
[fsharp.log](https://github.com/dotnet/aspnetcore/files/15252690/fsharp.log)
[msbuild.log](https://github.com/dotnet/aspnetcore/files/15252691/msbuild.log)
[nuget-client.log](https://github.com/dotnet/aspnetcore/files/15252692/nuget-client.log)
[razor.log](https://github.com/dotnet/aspnetcore/files/15252693/razor.log)
[roslyn.log](https://github.com/dotnet/aspnetcore/files/15252694/roslyn.log)
[roslyn-analyzers.log](https://github.com/dotnet/aspnetcore/files/15252695/roslyn-analyzers.log)
[runtime.log](https://github.com/dotnet/aspnetcore/files/15252696/runtime.log)
[scenario-tests.log](https://github.com/dotnet/aspnetcore/files/15252697/scenario-tests.log)
[sourcelink.log](https://github.com/dotnet/aspnetcore/files/15252698/sourcelink.log)
[symreader.log](https://github.com/dotnet/aspnetcore/files/15252699/symreader.log)
[templating.log](https://github.com/dotnet/aspnetcore/files/15252700/templating.log)
[test-templates.log](https://github.com/dotnet/aspnetcore/files/15252701/test-templates.log)


> fixed by increasing the number of cores used in the default devcontainer

The devcontainer loaded with  16-core • 64GB RAM • 128GB.

**Comment by jozkee** [comment]
This is stale by now, closing.
