### ISSUE TITLE
.NET 8 Blazor - Static Rendering, AntiForgery and Incorrect Content-Type: Exceptions

### ISSUE THREAD

**Issue by sbwalker** [dotnet/aspnetcore#55582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a public website built on Blazor which uses Static Rendering (https://www.oqtane.org). When running this site in production there are bots which will attempt to send POST requests to site pages. When this occurs it raises an exception which is logged to my error logging infrastructure - which is creating a lot of log entries.

I have done some further investigation and was able to reproduce on a standard Blazor Web app generated from the template.

If you make an empty POST request (ie. using POSTMAN) to a Static Server rendered endpoint and that endpoint has Antiforgery disabled:

```
@using Microsoft.AspNetCore.Antiforgery;
@attribute [RequireAntiforgeryToken(required: false)]
```

Blazor will call:

RazorComponentEndpointInvoker.cs which calls ValidateRequestAsync()

It evaluates the Antiforgerytoken settings and if Antiforgery is disabled for the endpoint, it logs a Debug message:

"The endpoint disabled antiforgery token validation."

and continues on and eventually calls:

```
await context.Request.ReadFormAs()
```

which invokes FormFeature.cs which eventually calls InnerReadFormAsync() and the following logic is invoked:

```if (!HasFormContentType)
{
    throw new InvalidOperationException("Incorrect Content-Type: " + _request.ContentType);
}
```

which throws an exception:

```
System.InvalidOperationException: Incorrect Content-Type: 
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.ValidateRequestAsync(HttpContext context, IAntiforgery antiforgery)
   at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<<InvokeAsync>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at BlazorApp18.ExceptionMiddleware.Invoke(HttpContext context, IServiceProvider provider) in C:\Users\shaun\source\repos\BlazorApp18\BlazorApp18\ExceptionMiddleware.cs:line 16
```

The HTTP response returned has status 200 OK

However...

if the endpoint does have Antiforgery enabled, Blazor returns a response of 400 Bad Request with content of:

"A valid antiforgery token was not provided with the request. Add an antiforgery token, or disable antiforgery validation for this endpoint."

and does not raise an exception.

I believe the behavior should be consistent in both scenarios, and should not raise an Exception.

### Expected Behavior

A POST request can be sent to a page rendered with Static Rendering which does not have Antiforgery enabled, and it will not throw an exception.

### Steps To Reproduce

Create a standard Blazor Web App. Disable anti-forgery on the Home page. Add exception middleware to catch unhandled exceptions. Use POSTMAN to send a POST request to the Home page. Catch the exception.

### Exceptions (if any)

System.InvalidOperationException: Incorrect Content-Type: 
   at Microsoft.AspNetCore.Http.Features.FormFeature.InnerReadFormAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.ValidateRequestAsync(HttpContext context, IAntiforgery antiforgery)
   at Microsoft.AspNetCore.Components.Endpoints.RazorComponentEndpointInvoker.RenderComponentCore(HttpContext context)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<<InvokeAsync>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at BlazorApp18.ExceptionMiddleware.Invoke(HttpContext context, IServiceProvider provider) in C:\Users\shaun\source\repos\BlazorApp18\BlazorApp18\ExceptionMiddleware.cs:line 16

### .NET Version

8.0.4 (latest SDK installed in production)

**Comment by SteveSandersonMS** [comment]
We checked, and `RazorComponentEndpointInvoker` calls `await context.Request.ReadFormAsync();` for all post requests, which throws if the content type is unexpected.

We discussed and think we should change the framework so that if the form can't be read, we return a 400 and don't have any unhandled exception.
