### ISSUE TITLE
Need help with SSE and .NET events

### ISSUE THREAD

**Issue by salarzobir** [dotnet/aspnetcore#55663]
Hey people, I am not even sure whether this is the correct place to ask for help, please forgive me if it is not.

I created this sample ASP.NET Core project https://github.com/salarzobir/SseTest to demonstrate my problem, I am not even sure whether the behavior (message overlapping or process crashing) is a normal intended behavior.

What could be the best way to fix this problem.

In my actual production application I am getting this exception sometimes then the process crashes:

```
System.ArgumentNullException: Value cannot be null. (Parameter 'array')
   at System.Buffers.SharedArrayPool`1.Return(T[] array, Boolean clearArray)
   at System.IO.Pipelines.StreamPipeWriter.FlushAsyncInternal(Boolean writeToStream, ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.GetTaskForValueTaskSource(IValueTaskSource`1 t)
--- End of stack trace from previous location ---
   at MyProject.Services.SseClient.SendAsync[T](T data, String eventType)
   at MyProject.Services.SseService.SendEventAsync[T](IEnumerable`1 clientIds, T data, String eventType)
   at MyProject.Services.SomeService.OnProgressChanged(Object sender, PropertyChangedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by BrennanConroy** [comment]
It looks like your app can be calling `WriteAsync`/`FlushAsync` from `SseClient.KeepAliveAsync()` at the same time that it's calling `WriteAsync`/`FlushAsync` from `SseClient.SendAsync()` which is not allowed. You need to synchronize the writes so they can't run in parallel.

You also are using the cancellation token in `SendAsync` which could cause an OperationCanceledException to be thrown in the background thread and you aren't catching it anywhere, so you'd still get process crashes.

e.g.
```csharp
SemaphoreSlim _lock { get; } = new SemaphoreSlim(1, 1);

public async Task KeepAliveAsync()
{
    while (true)
    {
        await _lock.WaitAsync(_cancellationTokenSource.Token);
        try
        {
            await _response.WriteAsync(__keepAliveMessage, _cancellationTokenSource.Token);
            await _response.Body.FlushAsync(_cancellationTokenSource.Token);
        }
        finally
        {
            _lock.Release();
        }
        await Task.Delay(5000, _cancellationTokenSource.Token);
    }
}

public async Task SendAsync<T>(T? data = null, string? eventType = "message")
    where T : class
{
    await _lock.WaitAsync(_cancellationTokenSource.Token);
    try
    {
        await _response.WriteAsync($"event: {eventType}\ndata: {(data is not null ? JsonSerializer.Serialize(data, WebSerializerOptions) : string.Empty)}\n\n", _cancellationTokenSource.Token);
        await _response.Body.FlushAsync(_cancellationTokenSource.Token);
    }
    finally
    {
        _lock.Release();
    }
}
```
