### ISSUE TITLE
Quarantine OutOfProcessToInProcessHostingModelSwitchWorks

### ISSUE THREAD

**Issue by amcasey** [dotnet/aspnetcore#55937]
## Failing Test(s)

- Microsoft.AspNetCore.Server.IIS.IISExpress.FunctionalTests.ShutdownTests.OutOfProcessToInProcessHostingModelSwitchWorks

## Error Message

```text
System.Net.Http.HttpRequestException : Error while copying content to a stream.
---- System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
-------- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host.
```

## Stacktrace

<details>

```text
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.LoggingHandler.LogResponse(LogLevel logLevel, HttpResponseMessage response) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/LoggingHandler.cs:line 37
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.LoggingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/LoggingHandler.cs:line 28
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.AspNetCore.Server.IIS.FunctionalTests.Helpers.RetryRequestAsync(HttpClient client, String uri, Func`2 predicate) in /_/src/Servers/IIS/IIS/test/Common.FunctionalTests/Infrastructure/Helpers.cs:line 112
   at Microsoft.AspNetCore.Server.IIS.IISExpress.FunctionalTests.ShutdownTests.OutOfProcessToInProcessHostingModelSwitchWorks() in /_/src/Servers/IIS/IIS/test/Common.LongTests/ShutdownTests.cs:line 558
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionResponseContent.<SerializeToStreamAsync>g__Impl|6_0(Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
   at System.Net.Sockets.NetworkStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Http.HttpConnectionResponseContent.<SerializeToStreamAsync>g__Impl|6_0(Stream stream, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Net.Http.HttpContent.LoadIntoBufferAsync(Int64 maxBufferSize, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.LoggingHandler.LogResponse(LogLevel logLevel, HttpResponseMessage response) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/LoggingHandler.cs:line 37
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.LoggingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/LoggingHandler.cs:line 26
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunCont
```
</details>

## Logs

<details>

```text

```
</details>

## Build

aspnetcore-ci 5/28/2024, 1:14:53 PM

**Comment by amcasey** [comment]
[ShutdownTests_OutOfProcessToInProcessHostingModelSwitchWorks.log](https://github.com/dotnet/aspnetcore/files/15476874/ShutdownTests_OutOfProcessToInProcessHostingModelSwitchWorks.log)
