### ISSUE TITLE
JsonPolymorphic not respected in request DTOs

### ISSUE THREAD

**Issue by Arcalise08** [dotnet/aspnetcore#55956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Please look at the following type which is not being deserialized properly when binded.

```csharp
[JsonPolymorphic(TypeDiscriminatorPropertyName = "userType")]
[JsonDerivedType(typeof(PublicUserInfo), "Public")]
[JsonDerivedType(typeof(EmployeeUserInfo), "Employee")]
public interface IUserInfo
{
    public string UserType { get; init; }
}

[JsonDerivedType(typeof(PublicUserInfo), "Public")]
public class PublicUserInfo : IUserInfo
{
    public string UserType { get; init; }
    public string PublicInfo { get; init; }
};

[JsonDerivedType(typeof(EmployeeUserInfo), "Employee")]
public class EmployeeUserInfo : IUserInfo
{
    public string UserType { get; init; }
    public string EmployeeId { get; init; }
}
```

Using `System.Text.Json.JsonSerializer` the following code works fine
```csharp
var request = new CreateUserRequest("Test", new PublicUserInfo("Test", UserTypes.Public));
var json = JsonSerializer.Serialize(request);
var deserialized = JsonSerializer.Deserialize<CreateUserRequest>(json); //deserializes fine
```

Placing UserInfo in a request DTO however does not
```csharp
public record CreateUserRequest
{
    public string Username { get; init; }
    public IUserInfo UserInfo { get; init; }
    
}

[ApiController]
[Route("/api")]
public class PublicController(CosmosService service) : Controller
{
    [HttpPost("create-user")]
    [Produces<UserEntity>]
    public async Task<UserEntity> CreateUser([FromBody]CreateUserRequest req, CancellationToken ct)
    {
        if (req.UserInfo is PublicUserInfo publicUserInfo)
        {
            Console.WriteLine(publicUserInfo.PublicInfo);
        }
        var id = Guid.NewGuid().ToString();
        var entity = new UserEntity(id, id, "test", req.UserInfo);
        var response = await service.InsertOneAsync(entity, ct);
        HttpContext.Response.StatusCode = response.GetStatusCode(201);
        return response;
    }
}
```

It seems like this `JsonPolymorphic` attribute is relatively new and has changed a lot. So finding information about it that is still relevant is difficult.

I've only managed to get this to work by removing `JsonPolymorphic` and `JsonDerivedType` attributes from the classes and implementing a custom JsonConverter, The converter will not be used if that attribute exists which makes it a pretty bad workaround.

Heres the converter for reference

```csharp
public class UserInfoJsonConverter : JsonConverter<IUserInfo>
{
    public override IUserInfo Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using (JsonDocument doc = JsonDocument.ParseValue(ref reader))
        {
            if (!doc.RootElement.TryGetProperty("userType", out JsonElement typeElement))
            {
                throw new JsonException("Missing discriminator property 'userType'.");
            }

            var userType = typeElement.GetString();
            var json = doc.RootElement.GetRawText();

            return userType switch
            {
                UserTypes.Public => JsonSerializer.Deserialize<PublicUserInfo>(json, options),
                UserTypes.Employee => JsonSerializer.Deserialize<EmployeeUserInfo>(json, options),
                _ => throw new JsonException($"Unknown user type: {userType}")
            };
        }
    }

    public override void Write(Utf8JsonWriter writer, IUserInfo value, JsonSerializerOptions options)
    {
        JsonSerializer.Serialize(writer, value, value.GetType(), options);
    }
    
}
```

### Expected Behavior

I expect that using `JsonPolymorphic` attribute on a request property, or the request itself, Will use the discriminator given to find and instantiate the proper derived class.

### Steps To Reproduce

1. Create a base interface
2. Create implementations of the interface and add more properties
3. Assign `JsonPolymorphic` attribute to the base class
4. Assign `JsonDerivedType` attribute to the base class for each implementation
5. Add base class to a request DTO on endpoint
6. Attempt to call ASP.NET endpoint with request payload using a derived type

### Exceptions (if any)

Using the `JsonConverter` with the `JsonPolymorphic` attributes on the base types will result in the following error

```
System.NotSupportedException: The converter for derived type 'TestingPolymorphicJson.Models.IUserInfo' does not support metadata writes or reads.
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_BaseConverterDoesNotSupportMetadata(Type derivedType)
   at System.Text.Json.Serialization.Metadata.PolymorphicTypeResolver..ctor(JsonSerializerOptions options, JsonPolymorphismOptions polymorphismOptions, Type baseType, Boolean converterCanHaveMetadata)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureSynchronized|172_0()
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Nullable`1 ensureNotNull, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo.Configure()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.ConfigureProperties()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureSynchronized|172_0()
--- End of stack trace from previous location ---
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureSynchronized|172_0()
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Nullable`1 ensureNotNull, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType)
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoForRootType(Type type, Boolean fallBackToNearestAncestorType)
   at System.Text.Json.JsonSerializer.DeserializeAsync(Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value, Object container)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at NSwag.AspNetCore.Middlewares.SwaggerUiIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.RedirectToIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### .NET Version

8

**Comment by Arcalise08** [comment]
Apologies for wasting time here. If anyone does have the same problem as I am having its because your derived types should not have a property named for the derived type. I thought it made sense that it would, but it seems it adds the json property itself. Which in my case, caused a duplicate discriminators and that just caused very very odd problems. 

The fix is really simple, if your following from my example above 

```csharp
[JsonPolymorphic(TypeDiscriminatorPropertyName = "userType")]
[JsonDerivedType(typeof(PublicUserInfo), "Public")]
[JsonDerivedType(typeof(EmployeeUserInfo), "Employee")]
public interface IUserInfo
{
   //removed public string UserType { get; init; }
}


public class PublicUserInfo : IUserInfo
{
    //removed public string UserType { get; init; }
    public string PublicInfo { get; init; }
};

public class EmployeeUserInfo : IUserInfo
{
    //removed public string UserType { get; init; }
    public string EmployeeId { get; init; }
}
```

Now everything is happy again.
