### ISSUE TITLE
Retry CanSendAndReceiveUserMessagesFromMultipleConnectionsWithSameUser

### ISSUE THREAD

**Issue by amcasey** [dotnet/aspnetcore#55954]
## Failing Test(s)

- Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.RedisEndToEndTests.CanSendAndReceiveUserMessagesFromMultipleConnectionsWithSameUser(transportType: WebSockets, protocolName: "messagepack")

## Error Message

```text
System.TimeoutException : The operation has timed out.
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.InternalTesting.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 88
   at Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.RedisEndToEndTests.CanSendAndReceiveUserMessagesFromMultipleConnectionsWithSameUser(HttpTransportType transportType, String protocolName) in /_/src/SignalR/server/StackExchangeRedis/test/RedisEndToEnd.cs:line 111
--- End of stack trace from previous location ---
```
</details>

## Logs

<details>

```text
[0.001s] [TestLifetime] [Information] Starting test CanSendAndReceiveUserMessagesFromMultipleConnectionsWithSameUser-WebSockets-messagepack at 2024-05-29T00:46:50
[0.001s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Registering handler for client method 'Echo'.
[0.001s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Registering handler for client method 'Echo'.
[0.002s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Starting HubConnection.
[0.002s] [Microsoft.AspNetCore.Http.Connections.Client.HttpConnection] [Debug] Starting HttpConnection.
[0.002s] [Microsoft.AspNetCore.Http.Connections.Client.HttpConnection] [Debug] Establishing connection with server at 'http://127.0.0.1:36393/echo'.
[0.003s] [Microsoft.AspNetCore.Http.Connections.Client.HttpConnection] [Debug] Established connection 'O8zhvX0zx-HWpX2dnRwpFQ' with the server.
[0.003s] [Microsoft.AspNetCore.Http.Connections.Client.HttpConnection] [Debug] Starting transport 'WebSockets' with Url: http://127.0.0.1:36393/echo.
[0.003s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport] [Information] Starting transport. Transfer mode: Binary. Url: 'ws://127.0.0.1:36393/echo?id=MQVUtD1Wxoh_BJ4FzWajcQ'.
[0.004s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport] [Debug] Started transport.
[0.004s] [Microsoft.AspNetCore.Http.Connections.Client.HttpConnection] [Debug] Transport 'WebSockets' started.
[0.004s] [Microsoft.AspNetCore.Http.Connections.Client.HttpConnection] [Information] HttpConnection Started.
[0.004s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Information] Using HubProtocol 'messagepack v1'.
[0.004s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Sending Hub Handshake.
[0.004s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport] [Debug] Received message from application. Payload size: 39.
[0.005s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport] [Debug] Message received. Type: Binary, size: 3, EndOfMessage: True.
[0.005s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Handshake with server complete.
[0.005s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Sending PingMessage message.
[0.005s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Sending PingMessage message completed.
[0.005s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Receive loop starting.
[0.005s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Information] HubConnection started.
[0.006s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport] [Debug] Received message from application. Payload size: 3.
[0.006s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Starting HubConnection.
[0.006s] [Microsoft.AspNetCore.Http.Connections.Client.HttpConnection] [Debug] Starting HttpConnection.
[0.006s] [Microsoft.AspNetCore.Http.Connections.Client.HttpConnection] [Debug] Establishing connection with server at 'http://127.0.0.1:44495/echo'.
[0.007s] [Microsoft.AspNetCore.Http.Connections.Client.HttpConnection] [Debug] Established connection 'vL7yeQOroXbjB4bXcStBzA' with the server.
[0.007s] [Microsoft.AspNetCore.Http.Connections.Client.HttpConnection] [Debug] Starting transport 'WebSockets' with Url: http://127.0.0.1:44495/echo.
[0.007s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport] [Information] Starting transport. Transfer mode: Binary. Url: 'ws://127.0.0.1:44495/echo?id=-raO5cVU1otunWX1QidbHg'.
[0.008s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport] [Debug] Started transport.
[0.008s] [Microsoft.AspNetCore.Http.Connections.Client.HttpConnection] [Debug] Transport 'WebSockets' started.
[0.008s] [Microsoft.AspNetCore.Http.Connections.Client.HttpConnection] [Information] HttpConnection Started.
[0.008s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Information] Using HubProtocol 'messagepack v1'.
[0.008s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Sending Hub Handshake.
[0.008s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport] [Debug] Received message from application. Payload size: 39.
[0.009s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport] [Debug] Message received. Type: Binary, size: 3, EndOfMessage: True.
[0.009s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Handshake with server complete.
[0.009s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Sending PingMessage message.
[0.009s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Sending PingMessage message completed.
[0.009s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Receive loop starting.
[0.009s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Information] HubConnection started.
[0.009s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Registering Invocation ID '1' for tracking.
[0.009s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Sending InvocationMessage message '1'.
[0.009s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Sending InvocationMessage message '1' completed.
[0.009s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport] [Debug] Received message from application. Payload size: 40.
[0.011s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport] [Debug] Message received. Type: Binary, size: 34, EndOfMessage: True.
[0.011s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Processing 34 byte message from server.
[15.006s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Sending PingMessage message.
[15.006s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Sending PingMessage message completed.
[15.006s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport] [Debug] Received message from application. Payload size: 3.
[15.010s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Sending PingMessage message.
[15.010s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Sending PingMessage message completed.
[15.010s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport] [Debug] Received message from application. Payload size: 3.
[15.310s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport] [Debug] Message received. Type: Binary, size: 3, EndOfMessage: True.
[15.310s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Processing 3 byte message from server.
[15.512s] [Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport] [Debug] Message received. Type: Binary, size: 3, EndOfMessage: True.
[15.513s] [Microsoft.AspNetCore.SignalR.Client.HubConnection] [Debug] Processing 3 byte message from server.
[30.011s] [Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.RedisEndToEndTests] [Error] Test threw an exception.
System.TimeoutException: The operation has timed out.
   at Microsoft.AspNetCore.InternalTesting.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 88
   at Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests.RedisEndToEndTests.CanSendAndReceiveUserMessagesFromMultipleConnectionsWithSameUser(HttpTransportType transportType, String protocolName) in /_/src/SignalR/server/StackExchangeRedis/test/RedisEndToEnd.cs:line 111
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
[30.012s] [TestLifetime] [Information] Finished test CanSendAndReceiveUserMessagesFromMultipleConnectionsWithSameUser-WebSockets-messagepack in 30.0112432s
```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=690412

**Comment by amcasey** [comment]
https://github.com/dotnet/aspnetcore/pull/55935 and https://github.com/dotnet/aspnetcore/issues/20040#issuecomment-1487696288

**Comment by eerhardt** [comment]
This has failed again in https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-aspnetcore-refs-heads-release-90-rc2-31a327fe05f2417f89/Microsoft.AspNetCore.SignalR.StackExchangeRedis.Tests--net9.0/1/console.1692c067.log?helixlogtype=result. Re-opening this issue. If it fails again we should re-add the retry.
