### ISSUE TITLE
route /_adminer.php throws ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by burtonrodman** [dotnet/aspnetcore#55974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1.  in an Asp.Net Core web project, navigate to /_adminer.php
2.  return 500 / ArgumentOutOfRangeException in RoutePatternMatcher.MatchComplexSegmentCore

I see similar issues have been recently fixed for cases starting with dot and dash... #19641 

Please consider handling this case as well.

### Expected Behavior

return 404 response

### Steps To Reproduce

1.  create an asp.net core web project
2.  debug and navigate to https://localhost:<port>/_adminer.php
3.  receive noted exception

### Exceptions (if any)

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at Microsoft.AspNetCore.Routing.RoutePatternMatcher.MatchComplexSegmentCore(RoutePatternPathSegment routeSegment, ReadOnlySpan`1 requestSegment, RouteValueDictionary values, Int32 indexOfLastSegmentUsed)
   at Microsoft.AspNetCore.Routing.RoutePatternMatcher.MatchComplexSegment(RoutePatternPathSegment routeSegment, ReadOnlySpan`1 requestSegment, RouteValueDictionary values)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.ProcessComplexSegments(Endpoint endpoint, ValueTuple`2[] complexSegments, String path, ReadOnlySpan`1 segments, RouteValueDictionary values)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Rewrite.RewriteMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

### .NET Version

8.0.300

**Comment by burtonrodman** [comment]
Project targeted net6.0.  Updated to target net8.0 (and updated all PackageReferences) and issue resolved.
