### ISSUE TITLE
NullReferenceException in resolve-dependencies

### ISSUE THREAD

**Issue by Tarmil** [dotnet/aspnetcore#5602]
I get the following error when using Blazor.Server on an F# project:

```
EXEC : error : Object reference not set to an instance of an object. [C:\Users\loic.denuziere\my\miniblazor\tests\server\server.fsproj]
     at Microsoft.AspNetCore.Blazor.Build.RuntimeDependenciesResolver.AssemblyResolutionContext.<ResolveAssemblies>g__GetAssemblyReferences|13_1(AssemblyEntry current) in /_/src/Microsoft.AspNetCore.Blazor.Build/Core/RuntimeDependenciesResolver.cs:line 103
     at Microsoft.AspNetCore.Blazor.Build.RuntimeDependenciesResolver.AssemblyResolutionContext.<ResolveAssemblies>g__ResolveAssembliesCore|13_0(<>c__DisplayClass13_0& ) in /_/src/Microsoft.AspNetCore.Blazor.Build/Core/RuntimeDependenciesResolver.cs:line 91
     at Microsoft.AspNetCore.Blazor.Build.RuntimeDependenciesResolver.AssemblyResolutionContext.ResolveAssemblies() in /_/src/Microsoft.AspNetCore.Blazor.Build/Core/RuntimeDependenciesResolver.cs:line 82
     at Microsoft.AspNetCore.Blazor.Build.RuntimeDependenciesResolver.ResolveRuntimeDependenciesCore(String entryPoint, String[] applicationDependencies, String[] monoBclDirectories) in /_/src/Microsoft.AspNetCore.Blazor.Build/Core/RuntimeDependenciesResolver.cs:line 46
     at Microsoft.AspNetCore.Blazor.Build.Cli.Commands.ResolveRuntimeDependenciesCommand.<>c__DisplayClass0_0.<Command>b__0() in /_/src/Microsoft.AspNetCore.Blazor.Build/Cli/Commands/ResolveRuntimeDependenciesCommand.cs:line 44
C:\Users\loic.denuziere\.nuget\packages\microsoft.aspnetcore.blazor.build\0.7.0-preview1-20180925.6\targets\Blazor.MonoRuntime.targets(538,5): error MSB3073: The command "dotnet "C:\Users\loic.denuziere\.nuget\packages\microsoft.aspnetcore.blazor.build\0.7.0-preview1-20180925.6\targets\../tools/Microsoft.AspNetCore.Blazor.Build.dll" resolve-dependencies "C:\Users\loic.denuziere\my\miniblazor\tests\server\obj\Debug\netcoreapp2.0\server.dll" --references "C:\Users\loic.denuziere\my\miniblazor\tests\server\obj\Debug\netcoreapp2.0\blazor\resolve-dependencies.txt" --base-class-library "C:\Users\loic.denuziere\.nuget\packages\microsoft.aspnetcore.blazor.build\0.7.0-preview1-20180925.6\targets\../tools/mono/bcl/" --base-class-library "C:\Users\loic.denuziere\.nuget\packages\microsoft.aspnetcore.blazor.build\0.7.0-preview1-20180925.6\targets\../tools/mono/bcl/Facades/" --output "C:\Users\loic.denuziere\my\miniblazor\tests\server\obj\Debug\netcoreapp2.0\blazor\resolved.assemblies.txt"" exited with code 1. [C:\Users\loic.denuziere\my\miniblazor\tests\server\server.fsproj]
```

I ran this with a locally built Razor with print debugging to find what was going on, and it seems that the problem is that it can't find `System.Buffers.dll`; it's not copied locally, and it's not in mono's stdlib either. And indeed, the issue disappears if I add this to my project:

```xml
  <ItemGroup>
    <ReferenceCopyLocalPaths Include="$(NuGetPackageRoot)system.buffers/4.5.0/lib/netstandard2.0/System.Buffers.dll" />
  </ItemGroup>
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Tarmil.
Feel free to submit a PR and we'd happily consider it, if this is still a problem.

**Comment by pranavkm** [comment]
This code has changed since this issue was filed. If you still think there's an issue here once you've tried out Blazor WASM's GA build, please file a new issue.
