### ISSUE TITLE
Could not load file or assembly Microsoft.Extensions.Logging.AzureAppServices

### ISSUE THREAD

**Issue by Bsingh808** [dotnet/aspnetcore#56049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Seeing 500.30 startup error, after republishing the website. 
here is the stack trace for this bug
`Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Logging.AzureAppServices, Version=8.0.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.Extensions.Logging.AzureAppServices, Version=8.0.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.AspNetCore.Hosting.AppServicesWebHostBuilderExtensions.<>c.<UseAzureAppServices>b__0_0(ILoggingBuilder builder)
   at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection services, Action`1 configure)
   at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass8_0.<ConfigureLogging>b__0(IServiceCollection collection)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.<>c__DisplayClass10_0.<ConfigureServices>b__0(WebHostBuilderContext _, IServiceCollection services)
   at System.Action`2.Invoke(T1 arg1, T2 arg2)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()`

### Expected Behavior

Republishing a site without changing any code should not cause the site to go down due to the automatically installed ASP.NET Core Logging site extension

### Steps To Reproduce

Update site .NET version to 8 and also update all Microsoft packages to 8.0.6. 
The project manifest looks like this - 
`<ItemGroup>
  <PackageReference Include="AutoMapper" Version="13.0.1" />
  <PackageReference Include="EPPlus" Version="4.5.2.1" />
  <PackageReference Include="Hangfire.Core" Version="1.7.30" />
  <PackageReference Include="Hangfire.SqlServer" Version="1.7.30" />
  <PackageReference Include="Hangfire.AspNetCore" Version="1.7.30" />
  <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.6" />
  <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.6" />
  <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.2" />
	<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.6" />
	<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.6" />
	<PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.6" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.6" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.6">
 <PrivateAssets>all</PrivateAssets>
 <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.6" />
  <PackageReference Include="NaturalSort.Extension" Version="3.2.0" />
  <PackageReference Include="Sendgrid" Version="9.28.0" />
  <PackageReference Include="StructureMap.Microsoft.DependencyInjection" Version="2.0.0" />
  <PackageReference Include="System.Linq.Dynamic.Core" Version="1.4.0" />
</ItemGroup>`

### .NET Version

dotnet --version

**Comment by BrennanConroy** [comment]
> automatically installed ASP.NET Core Logging site extension

This shouldn't be automatic, it's an explicit action by the app developer in the Azure portal.
Were you using the site extension before? What version? Can you try installing the 8.0.5 site extension and see if it has issues?

**Comment by amcasey** [comment]
Related? #50389

**Comment by winterlimelight** [comment]
I think this is the same problem, and I've been able to workaround it.

I started getting the following after doing a direct publish from Visual Studio to an Azure App Service:
`FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Logging.AzureAppServices, Version=8.0.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
Microsoft.AspNetCore.Hosting.AppServicesWebHostBuilderExtensions+<>c.<UseAzureAppServices>b__0_0(ILoggingBuilder builder)`

My code contained a reference to AzureAppServices, but it was to version 8.0.1, and my DLLs were 8.0.1 as expected.

However I noticed the following in the build/publish window:
`Installation of Web App Site extension Microsoft.AspNetCore.AzureAppServices.SiteExtension is in progress...`
This was despite the having _Install ASP.NET Core Logging Integration Site Extension_ unchecked.

That created a folder called Microsoft.AspNetCore.AzureAppServices.SiteExtension in C:\home\SiteExtensions in my app service. And it was this which was causing the above error. I confirmed this by deleting the SiteExtension folder, and the problem went away.

To resolve this in an existing site:
1. Stop App Service
2. Open kudu, Debug Console, PowerShell
3. cd SiteExtensions
4. rm -r *

This is a very basic repro with some redactions in the publish profile: 
[WebApplication1.zip](https://github.com/user-attachments/files/15599553/WebApplication1.zip)

**Comment by BrennanConroy** [comment]
@BillHiebert Seems like maybe VS is doing something weird here? Is the AzureAppServices site extension experience in VS something you're familiar with?

**Comment by kdcllc** [comment]
@BrennanConroy  we just ran into this issue. The project had the following reference of 8.0.7:

```csharp
    <PackageReference Include="Microsoft.Extensions.Logging.AzureAppServices" Version="8.0.7" />
``` 

and the Kudus Plus extensins had version 8.0.8


![image](https://github.com/user-attachments/assets/ba8d6d80-8c05-49fd-8ee7-4b869454064c)

Resulted in the following:

```text
First 30KB characters of captured stdout and stderr logs: Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Logging.AzureAppServices, Version=8.0.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified. File name: 'Microsoft.Extensions.Logging.AzureAppServices, Version=8.0.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
```

I am not sure how the extension was updated but, it broke our production site since the latest version was installed. 

Thanks
