### ISSUE TITLE
Blazor Web App will not load webassembly component on some machines

### ISSUE THREAD

**Issue by mtbayley** [dotnet/aspnetcore#56074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I can't think of how this is possible, but I get this message on startup of my published AOT compiled Blazor Web App. Some machines have no problem loading the site, but some machines show this error consistently.

Any help on where to look would be appreciated

blazor.web.js:1  Error: AggregateException_ctor_DefaultMessage (EndOfStringNotFound Path: $['__internal__AntiforgeryRequestToken'] | LineNumber: 0 | BytePositionInLine: 2340.)
    at Jn (dotnet.runtime.8.0.6.cfhqwq2l7j.js:3:31614)
    at Tl (dotnet.runtime.8.0.6.cfhqwq2l7j.js:3:182415)
    at 0fd5c22a:0x27ba236
    at 0fd5c22a:0x27bbcf8
    at 0fd5c22a:0x27c169c
    at 0fd5c22a:0x2f2f5a4
    at 0fd5c22a:0x31d0e0e
    at 0fd5c22a:0x31ede66
    at 0fd5c22a:0x31cd780
    at 0fd5c22a:0x31c0b7d
callEntryPoint @ blazor.web.js:1
await in callEntryPoint (async)
ti @ blazor.web.js:1
await in ti (async)
ei @ blazor.web.js:1
startWebAssemblyIfNotStarted @ blazor.web.js:1
resolveRendererIdForDescriptor @ blazor.web.js:1
determinePendingOperation @ blazor.web.js:1
refreshRootComponents @ blazor.web.js:1
(anonymous) @ blazor.web.js:1
setTimeout (async)
rootComponentsMayRequireRefresh @ blazor.web.js:1
onDocumentUpdated @ blazor.web.js:1
Ki @ blazor.web.js:1
Ji @ blazor.web.js:1
(anonymous) @ (index):770

### .NET Version

8.0.6

**Comment by mtbayley** [comment]
I can confirm that the issue is gone when `RunAOTCompilation` is false

**Comment by javiercn** [comment]
@mtbayley thanks for contacting us.

This seems like a bug in the AoT process. Do you happen to have a repro project that we can use to troubleshoot this issue? In the meantime I'm going to transfer this to the runtime so they can investigate.
