### ISSUE TITLE
Dictionary property causes build crash when generating OpenAPI document at build time

### ISSUE THREAD

**Issue by mikekistler** [dotnet/aspnetcore#56307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In a project using the Microsoft.Extensions.ApiDescription.Server package to generate the OpenAPI document at build time, the build crashes if a class that will have a generated schema contains a `Dictionary` property.

### Expected Behavior

a) the build should not crash
b) the schema for the property should have `type: object` and `additionalProperties` with the schema for the value type the `additionalProperties` value.

### Steps To Reproduce

In my project I declare the following property in my response class:
```
public Dictionary<string, string> Dictionary { get; set; }
```

Not minimal, but there is a recreate in the `bug-56307` branch of my [aspnet-openapi-examples](https://github.com/mikekistler/aspnet-openapi-examples/tree/bug-56307) project.

The property causing the failure is in the `Schemas.cs` file.

### Exceptions (if any)

```
> dotnet build
Restore complete (0.9s)
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  aspnet-openapi-examples failed with 34 error(s) and 6 warning(s) (4.7s) → bin\Debug\net9.0\aspnet-openapi-examples.dll
    C:\Users\mikekistler\Projects\mikekistler\aspnet-openapi-examples\DataTypes.cs(26,19): warning CS8618: Non-nullable property 'String' must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring the property as nullable.
    C:\Users\mikekistler\Projects\mikekistler\aspnet-openapi-examples\DataTypes.cs(60,16): warning CS8618: Non-nullable property 'Uri' must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring the property as nullable.
    C:\Users\mikekistler\Projects\mikekistler\aspnet-openapi-examples\RequestBodiesApi.cs(62,19): warning CS8618: Non-nullable property 'prop1' must contain a non-null value when exiting constructor. Consider adding the 'required' modifier or declaring the property as nullable.
    C:\Users\mikekistler\Projects\mikekistler\aspnet-openapi-examples\Transformers\InfoTransformer.cs(8,23): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
    C:\Users\mikekistler\Projects\mikekistler\aspnet-openapi-examples\ResponsesApi.cs(148,11): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
    C:\Users\mikekistler\Projects\mikekistler\aspnet-openapi-examples\Schemas.cs(13,12): warning CS0169: The field 'Schemas.Field' is never used
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error : System.AggregateException: One or more errors occurred. (The converter 'OpenApiJsonSchema+JsonConverter' read too much or not enough. Path: $ | LineNumber: 0 | BytePositionInLine: 88.)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :  ---> System.Text.Json.JsonException: The converter 'OpenApiJsonSchema+JsonConverter' read too much or not enough. Path: $ | LineNumber: 0 | BytePositionInLine: 88.
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at System.Text.Json.ThrowHelper.ThrowJsonException_SerializationConverterRead(JsonConverter converter)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at System.Text.Json.Serialization.JsonConverter`1.VerifyRead(JsonTokenType tokenType, Int32 depth, Int64 bytesConsumed, Boolean isValueConverter, Utf8JsonReader& reader)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObject(Utf8JsonReader& reader, ReadStack& state)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at System.Text.Json.JsonSerializer.ReadAsObject(Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at System.Text.Json.JsonSerializer.ReadAsObject(Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at OpenApiJsonSchema.ReadDictionary[T](Utf8JsonReader& reader)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at OpenApiJsonSchema.ReadProperty(Utf8JsonReader& reader, String propertyName, OpenApiSchema schema, JsonSerializerOptions options)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at OpenApiJsonSchema.JsonConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at System.Text.Json.JsonSerializer.ReadFromNode[TValue](JsonNode node, JsonTypeInfo`1 jsonTypeInfo)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at Microsoft.AspNetCore.OpenApi.OpenApiComponentService.GetOrCreateSchema(Type type, ApiParameterDescription parameterDescription)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetResponse(ApiDescription apiDescription, Int32 statusCode, ApiResponseType apiResponseType)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetResponses(ApiDescription description)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOperation(ApiDescription description, HashSet`1 capturedTags)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOperations(IGrouping`2 descriptions, HashSet`1 capturedTags)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOpenApiPaths(HashSet`1 capturedTags)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOpenApiDocumentAsync(CancellationToken cancellationToken)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at Microsoft.Extensions.ApiDescriptions.OpenApiDocumentProvider.GenerateAsync(String documentName, TextWriter writer)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    --- End of inner exception stack trace ---
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at Microsoft.Extensions.ApiDescription.Tool.Commands.GetDocumentCommandWorker.GetDocument(String documentName, String projectName, String outputDirectory, MethodInfo generateMethod, Object service)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at Microsoft.Extensions.ApiDescription.Tool.Commands.GetDocumentCommandWorker.GetDocuments(IServiceProvider services)
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error :    at Microsoft.Extensions.ApiDescription.Tool.Commands.GetDocumentCommandWorker.Process()
    C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\Microsoft.Extensions.ApiDescription.Server.targets(66,5): error MSB3073: The command "dotnet "C:\.tools\.nuget\packages\microsoft.extensions.apidescription.server\9.0.0-preview.5.24270.27\build\../tools/dotnet-getdocument.dll" --assembly "C:\Users\mikekistler\Projects\mikekistler\aspnet-openapi-examples\bin\Debug\net9.0\aspnet-openapi-examples.dll" --file-list "obj\aspnet-openapi-examples.OpenApiFiles.cache" --framework ".NETCoreApp,Version=v9.0" --output "C:\Users\mikekistler\Projects\mikekistler\aspnet-openapi-examples" --project "aspnet-openapi-examples" --assets-file "C:\Users\mikekistler\Projects\mikekistler\aspnet-openapi-examples\obj\project.assets.json" --platform "AnyCPU" " exited with code 11.

Build failed with 34 error(s) and 6 warning(s) in 5.8s
```

### .NET Version

9.0-preview4

**Comment by mikekistler** [comment]
I have built a minimal recreate for this problem and updated to the latest nightly build and I'm still getting the build failure.

The minimal recreate is in the "bug-56307-minimal" branch of the aspnet-openapi-examples repo:

https://github.com/mikekistler/aspnet-openapi-examples/tree/bug-56307-minimal

Here's my `dotnet-info` showning the version(s) I have installed:
```
> dotnet --info
.NET SDK:
 Version:           9.0.100-preview.5.24307.3
 Commit:            35b2c21ea6
 Workload version:  9.0.100-manifests.6407b7e4
 MSBuild version:   17.11.0-preview-24279-02+b963c24ef

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-preview.5.24307.3\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [tvos]
   Installation Source: VS 17.11.34910.147
   Manifest Version:    17.2.9088-net9-p1/9.0.100-preview.1
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.1\microsoft.net.sdk.tvos\17.2.9088-net9-p1\WorkloadManifest.json
   Install Type:              Msi

 [macos]
   Installation Source: VS 17.11.34910.147
   Manifest Version:    14.2.9088-net9-p1/9.0.100-preview.1
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.1\microsoft.net.sdk.macos\14.2.9088-net9-p1\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: VS 17.11.34910.147, VS 17.10.35004.147
   Manifest Version:    17.2.9088-net9-p1/9.0.100-preview.1
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.1\microsoft.net.sdk.maccatalyst\17.2.9088-net9-p1\WorkloadManifest.json
   Install Type:              Msi

 [ios]
   Installation Source: VS 17.11.34910.147, VS 17.10.35004.147
   Manifest Version:    17.2.9088-net9-p1/9.0.100-preview.1
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.1\microsoft.net.sdk.ios\17.2.9088-net9-p1\WorkloadManifest.json
   Install Type:              Msi

 [android]
   Installation Source: VS 17.11.34910.147, VS 17.10.35004.147
   Manifest Version:    34.99.0-preview.1.151/9.0.100-preview.1
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.1\microsoft.net.sdk.android\34.99.0-preview.1.151\WorkloadManifest.json
   Install Type:              Msi

 [wasm-tools-net6]
   Installation Source: VS 17.11.34910.147
   Manifest Version:    9.0.0-preview.5.24306.7/9.0.100-preview.5
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.5\microsoft.net.workload.mono.toolchain.net6\9.0.0-preview.5.24306.7\WorkloadManifest.json
   Install Type:              Msi

 [maui-windows]
   Installation Source: VS 17.11.34910.147, VS 17.10.35004.147
   Manifest Version:    9.0.0-preview.1.9973/9.0.100-preview.1
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.1\microsoft.net.sdk.maui\9.0.0-preview.1.9973\WorkloadManifest.json
   Install Type:              Msi

 [wasm-tools]
   Installation Source: VS 17.11.34910.147
   Manifest Version:    9.0.0-preview.5.24306.7/9.0.100-preview.5
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.5\microsoft.net.workload.mono.toolchain.current\9.0.0-preview.5.24306.7\WorkloadManifest.json
   Install Type:              Msi

 [aspire]
   Installation Source: VS 17.11.34910.147, VS 17.10.35004.147
   Manifest Version:    9.0.0-preview.2.24163.9/9.0.100-preview.1
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-preview.1\microsoft.net.sdk.aspire\9.0.0-preview.2.24163.9\WorkloadManifest.json
   Install Type:              Msi


Host:
  Version:      9.0.0-preview.5.24306.7
  Architecture: x64
  Commit:       a5cc707d97

.NET SDKs installed:
  6.0.423 [C:\Program Files\dotnet\sdk]
  7.0.317 [C:\Program Files\dotnet\sdk]
  8.0.106 [C:\Program Files\dotnet\sdk]
  8.0.206 [C:\Program Files\dotnet\sdk]
  8.0.300 [C:\Program Files\dotnet\sdk]
  9.0.100-preview.5.24307.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.31 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.5.24260.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.5.24306.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.5.24306.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.5.24306.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by illunix** [comment]
Same issue here

**Comment by mikekistler** [comment]
Just confirmed that this issue is fixed in the latest nightly of preview 6.
