### ISSUE TITLE
ErrorBoundary does not work

### ISSUE THREAD

**Issue by garrettlondon1** [dotnet/aspnetcore#56413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When creating a new Blazor Web App template and using InteractiveServer components without global interactivity.. I cannot get the error boundary to show

In a static component with an interactive island, it does not show Error content.. in a interactive page, it doesnt show error content either..

Confused what I am doing wrong

### Expected Behavior

Error boundary shows child content or error content when an unhandled exception happens in a static page or interactive page/component

- https://github.com/garrettlondon1/errorboundarytest

Created from Blazor Web app

### Steps To Reproduce

Go to the home page, and click the button to increase the count

### Exceptions (if any)

`warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Exception of type 'System.Exception' was thrown.
      System.Exception: Exception of type 'System.Exception' was thrown.
         at StaticErrorBoundary.Components.Pages.Counter.IncrementCount() in /Users/garrettlondon/Github/StaticErrorBoundary/Components/Pages/Counter.razor:line 29
         at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[T](MulticastDelegate delegate, T arg)
         at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs, Boolean waitForQuiescence)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]`

`Unhandled exception in circuit 'XOj9HyZGUCrv2y5bZvv5Mswe399H9w8ayWexTB5H--w'.
      System.Exception: Exception of type 'System.Exception' was thrown.
         at StaticErrorBoundary.Components.Pages.Counter.IncrementCount() in /Users/garrettlondon/Github/StaticErrorBoundary/Components/Pages/Counter.razor:line 29
         at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[T](MulticastDelegate delegate, T arg)
         at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs, Boolean waitForQuiescence)
`

### .NET Version

8.0.302

**Comment by MackinnonBuck** [comment]
Thanks for reaching out, @garrettlondon1.

It looks like the reason the error boundary doesn't show is because the error boundary is being rendered as a child component of the component throwing the exception. Since exceptions only bubble up the component hierarchy, a child error boundary component won't catch that exception.

This behavior could be changed, but we're going to backlog this for now to collect more feedback.

**Comment by garrettlondon1** [comment]
`It looks like the reason the error boundary doesn't show is because the error boundary is being rendered as a child component of the component throwing the exception.`

Thanks @MackinnonBuck, but I'm confused.

Counter.razor code block has the method IncrementCount
Counter.razor markup has the onclick handler that calls IncrementCount

This interactivity lives within the same exact component, no other components are throwing an exception

What am I missing here?

**Comment by garrettlondon1** [comment]
And another question, what is the solution to catch unhandled exceptions without putting a try catch block in every single point of interactivity (which is crazy at scale)

**Comment by IevgeniiKunshchykov** [comment]
Hello guys,

I've got two examples:
1) This example contains case when error is caught. There are 2 components: 1st rises error and seconds wraps 1st with ErrorBoundary

ComponentWithError.razor 
![image](https://github.com/dotnet/aspnetcore/assets/43510357/5513e224-a39f-43dd-a931-4267d135ca18)

WrappingComponent.razor
![image](https://github.com/dotnet/aspnetcore/assets/43510357/09fa1ba6-a02d-447b-ba4d-80f9435a520e)

2) This example contains case when error is not caugh and unhandled exception happens.
![image](https://github.com/dotnet/aspnetcore/assets/43510357/1eb9dd53-ea55-461e-96c7-3f0d8cc97fde)

I found the reson why errorboundary does not work when error happens just inside content but not in child component
There is such a class .Microsoft.AspNetCore.Components.RenderTree.Renderer.cs which contains HandleExceptionViaErrorBoundary method that recursively tries to find ErrorBoundary to handle exception. But search goes in tree by components.
![image](https://github.com/dotnet/aspnetcore/assets/43510357/9911c73d-9784-45de-86fc-04844504b5fe)

That's why my first case works. Because WrappingComponent.razor contains ErrorBoundary 
But second case has no wrapping component or that component just does not have ErrorBoundary . ErrorBoundary  is located just inside that component. And that case is not covered by that loop in Renderer.cs

Seems like we are obliged always to wrap components with ErrorBoundary but cannot just wrap some content.

Any reason for that ??? Why whole tree cannot be checked ??

**Comment by garrettlondon1** [comment]
@MackinnonBuck @danroth27  I see three options that Blazor forces developers into:

- Use global interactivity with Error Boundary > **not an option, cannot take advantage of SSR and per-page interactivity**

- Wrap every interactive component inside another page entirely so that Renderer.cs can see ErrorBoundary > **terrible design**
 
- Use a try catch block to handle exceptions in every single interactive method > **not scalable at all**

**Comment by danroth27** [comment]
I believe @IevgeniiKunshchykov's [assessment](https://github.com/dotnet/aspnetcore/issues/56413#issuecomment-2189006928) matches are our understanding of the issue. We could make a change to make it possible for error boundaries to handle exceptions thrown by HTML event handlers. This would be a behavior change that could potentially be breaking, but it seems likely that the impact could be negligible. But before we make such a change, we want to make sure we have sufficient justification and user demand for the change. We don't want to risk breaking existing users if the beneficial impact is unclear.

@garrettlondon1 If we were to make this change, are you saying that error boundaries would then meet your error handling needs? Or are you saying in your last [comment](https://github.com/dotnet/aspnetcore/issues/56413#issuecomment-2189027676) that you think Blazor needs an entirely different error handling solution?

**Comment by garrettlondon1** [comment]
@danroth27 thanks for the quick reply..

ErrorBoundary is definitely the proper solution for Interactive blazor error handling

The problem is that you have to wrap every single interactive component in it because App.razor is now static

That is barely manageable, but works..

All this story is asking for, is to make every interactive action inside of the ErrorBoundary able to correctly trigger the error content

**Comment by guardrex** [comment]
BTW ... I think we already cover that the error boundary should be around the portion ***of the component hierarchy*** that can throw an exception. We don't say anywhere that it can directly wrap content. Mackinnon and I spent some time working on the coverage, and we're taking feedback, but I think what's being discussed here is covered.

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-8.0#error-boundaries

**Comment by garrettlondon1** [comment]
Thanks @guardrex, but the example used in the docs is a very poor example, especially when it relates to this issue.

<img width="597" alt="Screenshot 2024-07-27 at 11 59 38 AM" src="https://github.com/user-attachments/assets/56ee3f52-1382-470f-9ca2-ef3fc7a90a63">

In this photo, why would you ever make the <Home> component Interactive?
- It seems like the docs are trying to avoid the fact that the ErrorBoundary is just not implemented correctly

If the Home component was not interactive (which it should NOT be), and the Counter component **was** interactive. Then the error boundary in the docs would not work. 

Why are we letting every individual developer figure this out painfully on their own when migrating to SSR, instead of either clarifying the docs or fixing the underlying issue?

**Comment by garrettlondon1** [comment]
I would add to the docs an example where:

- Home.razor is static, does not wrap EmbeddedCounter in an ErrorBoundary

- EmbeddedCounter is Interactive, wrapped in an ErrorBoundary

**Explain, why this does not work with @onclick handlers**
**Explain, why this does work if the event originates from another subcomponent **

**Comment by guardrex** [comment]
I don't agree with your feedback (*yet* 😄), so I yield to @MackinnonBuck and @danroth27 to determine if further changes are needed. If not, we'll continue to take feedback and see if others find it confusing.

Most of what you're discussing is covered ***prior to that example***. For analysis, @MackinnonBuck and @danroth27 should see the full section ...

https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/handle-errors?view=aspnetcore-8.0#error-boundaries

**Comment by cwoodward-taurus** [comment]
I can confirm @guardrex that we also find it confusing. We are looking for a reliable way to log Exceptions from a standalone Blazor Web Assembly Application to a Server within a Production Environment. Sources indicate that using the OnErrorAsync Method of the ErrorBoundary Component as a "global exception handler" is a way of achieving this. On closer inspection, however, it seems that Exceptions thrown from an HTML OnClick Event are not reliably handled by the ErrorBoundary Component. For other Developers looking to do something similar then it may be helpful for Microsoft to add a Note to this effect to their Documentation to hopefully minimise wasted effort going forwards. Having given this considerable thought we think the best way forwards for us, until Microsoft comes up with a better solution, is to remove the ErrorBoundary Component from our Application.  @danroth27 in response to your Question to @garrettlondon1 ideally we would like a Component that provides a reliable way of handling Exceptions globally rather than adding the same code multiple times to Try...Catch blocks, which seems to be the only solution as it stands.

**Comment by guardrex** [comment]
@cwoodward-taurus ... I'm going to enhance the coverage with additional guidance :point_up:. However, I don't have product unit remarks yet on the main question that you're asking about outside of just remarking that ErrorBoundary no-ops on them ...

> Exceptions thrown from an HTML OnClick Event are not reliably handled by the ErrorBoundary Component

Article remarks for that scenario will need to come from the product unit engineers here. I'll include anything else they want to say about it when I work that issue, and I should reach that issue next week after we get back from the Labor Day holiday.

**Comment by garrettlondon1** [comment]
@cwoodward-taurus I want to note there is a solution. You need to create another wrapper on top of every interactive component you have..

@IevgeniiKunshchykov example calls it WrappingComponent

Page.razor (static)
- SafeWrappingComponent.razor
- View.razor

Its incredibly painful, but it works for all scenarios. Now that I'm thinking.. I wonder if you can make an interactive component that wraps interactive ChildContent.

Almost, wrapping ErrorBoundary itself inside of another interactive component which takes a ChildContent parameter. Will try it out

**Comment by clarity99** [comment]
I am using blazor interactive components in MVC project and the fact that I have to wrap every component I create in another component just to catch errors is a bit frustrating, to say the least. Or is there another way to globally catch errors in such a case?

**Comment by garrettlondon1** [comment]
Can we get this pulled out of the backlog?

**Comment by IevgeniiKunshchykov** [comment]
Here is one more case with unexpected behavior of errorboundary which is crucial for us.
We've solved the problem mentioned above with wrappers around our components.
Here is example:
![Image](https://github.com/user-attachments/assets/82957f44-da41-4ff3-acdd-66723e4868e6)

But when internal component has some state, like here I have counter with some value:
![Image](https://github.com/user-attachments/assets/3f925710-f622-4379-b917-45e78eb9c588)

And when exception is thrown and caught by errorboundary then internal component of errorboundary is just recreated and state is lost:
![Image](https://github.com/user-attachments/assets/14c0f64a-eea1-411d-8803-6855f29595c4)

Can this be solved somehow? Because it seems each approach of using errorboudary has some holes :(

**Comment by garrettlondon1** [comment]
@danroth27 there doesn't look like there is a good solution to ErrorBoundary at all... regarding above comment.

Even the error boundary keeps child content in the view, and does not use custom ErrorContent RenderFragment, All state is cleared on error with WrappingComponent approach.

**Comment by codymullins** [comment]
It would be nice to be able to include the `ErrorBoundary` within the component I want to handle itself. Now, as others pointed out, I have to hoist up the `ErrorBoundary` a level instead of having a nicely encapsulated component.

**Comment by codymullins** [comment]
To elaborate further. Here's a real scenario where this `ErrorBoundary` **does** work:

```razor
<LoggingErrorBoundary>
    <ChildContent>
        <ServiceStatusTile Service="@svc"/>
    </ChildContent>
    <ErrorContent>
        <div class="bg-red-500 text-white p-3 rounded-lg">
            <h3 class="font-bold">An error occurred</h3>
        </div>
    </ErrorContent>
</LoggingErrorBoundary>
```

Fine, this renders the error content. However, it totally wipes out the component:
![Image](https://github.com/user-attachments/assets/165da451-bbe5-4dc6-be2d-5620a4f34a14)

Compare this to the happy path, where the components all render:
![Image](https://github.com/user-attachments/assets/d9a02d94-9ca4-4e57-a9c2-79e84b027a1a)

Now, our `ServiceStatusTile` is a single component. What if we'd want to have an error boundary in the component itself and potentially render different parts of the component still when there's an error? We can't wrap arbitrary code, so we can't do that without these component wrappers that @garrettlondon1 mentioned. Huge pain, not maintainable.

**Comment by rklfss** [comment]
Having issues as well.

> Exceptions thrown from an HTML OnClick Event are not reliably handled by the ErrorBoundary Component

Not sure if this applies here, but had a case where an `@` sign was forgotten.
While exceptions with `<span onclick="SomeMethodThatThrowsEx">Click here</span>` were _not handled_ by the error boundary, exceptions with `<span @onclick="SomeMethodThatThrowsEx">Click here</span>` were _handled_.

**Comment by garrettlondon1** [comment]
> Having issues as well.
> 
> > Exceptions thrown from an HTML OnClick Event are not reliably handled by the ErrorBoundary Component
> 
> Not sure if this applies here, but had a case where an `@` sign was forgotten.
> While exceptions with `<span onclick="SomeMethodThatThrowsEx">Click here</span>` were _not handled_ by the error boundary, exceptions with `<span @onclick="SomeMethodThatThrowsEx">Click here</span>` were _handled_.

My guess is that fired a js onclick event instead of a blazor onclick event, so that makes sense

**Comment by garrettlondon1** [comment]
![Image](https://github.com/user-attachments/assets/6291df87-e8d7-4c56-9165-eb6ea94e8253)

Blazor also doesnt catch errors in Dispose methods.. for example if a jsInterop method fails in DisposeAsync, error boundary will not catch it and whole application will break.

**Comment by Yarith** [comment]
I hit this issue with InteractiveServer page component yesterday too. The current solution in this issue is manually wrapping every InteractiveServer page component with your custom `ErrorBoundary` component. This was not acceptable for me. So i was looking for a different workaround for this problem. By knowing, if `ErrorBoundary` is on the root of every page, it will work, i proceeded. So i was looking for a way to automatically surround the page content with my `CustomErrorBoundary` component. My first attempt was by subclassing the page type on runtime. Sadly some callbacks were by passing this approach. But this was not needed anyway. The new version just wraps the page type inside a generic wrapper type for the RouteView. 

You can see my current workaround in this gist: https://gist.github.com/Yarith/a524e5fc5fd89e356642f299d07f4209
