### ISSUE TITLE
RemoteAuthenticatorView is failing when CustomAuthenticationStateProvider is registered for keycloak

### ISSUE THREAD

**Issue by koureasstavros** [dotnet/aspnetcore#56508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Using Microsoft Blazor Hosted WebAssembly (with Client and Server Projects) we can set OIDC authentication using Keycloak and it works perfectly fine.

What we have to do is the following:

Register Keycloak in Client:
```
builder.Services.AddOidcAuthentication(options =>
{
    options.ProviderOptions.Authority = "openid_address_real";
    options.ProviderOptions.MetadataUrl ="openid_address_conf";
    options.ProviderOptions.ClientId = "openid_client";
    options.ProviderOptions.ResponseType = "id_token token";
    //options.ProviderOptions.RedirectUri = "/"; DEFINED DYNAMICALLY FROM AUTHENTICATION RAZOR

    options.UserOptions.NameClaim = "preferred_username";
    options.UserOptions.RoleClaim = "roles";
    options.UserOptions.ScopeClaim = "scope";
    options.UserOptions.AuthenticationType = "keycloak";
});
```
Add a razor component for redirection:
```
@page "/authentication/{action}"
@using Microsoft.AspNetCore.Components.WebAssembly.Authentication
<RemoteAuthenticatorView Action="@Action" />
@inject IJSRuntime JS
@inject NavigationManager navigationManager

@code {
    [Parameter]
    public string? Action { get; set; }
}
```
Register Keycloak in Server:
```
builder.Services.AddOidcAuthentication(options =>
{
    options.ProviderOptions.Authority = Parameters.transportation.openids_address_real;
    options.ProviderOptions.MetadataUrl = Parameters.transportation.openids_address_conf;
    options.ProviderOptions.ClientId = Parameters.transportation.openids_client;
    options.ProviderOptions.ResponseType = "id_token token";
    //options.ProviderOptions.RedirectUri = "/"; DEFINED DYNAMICALLY FROM AUTHENTICATION RAZOR

    options.UserOptions.NameClaim = "preferred_username";
    options.UserOptions.RoleClaim = "roles";
    options.UserOptions.ScopeClaim = "scope";
});
```

Then when a user hits a link which is redirecting to /authentication/login, the browser will redirect to keycloak for credentials and then will return back to the origin page.

But when registering in client a Custom Authentication State Provider:
`builder.Services.AddScoped<AuthenticationStateProvider, KeycloakAuthStateProvider>();`

Then when browser tries to redirect it throws a message:

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
```
Unhandled exception rendering component: Specified cast is not valid.
System.InvalidCastException: Specified cast is not valid.
   at Microsoft.Extensions.DependencyInjection.WebAssemblyAuthenticationServiceCollectionExtensions.<>c__1`1[[Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState, Microsoft.AspNetCore.Components.WebAssembly.Authentication, Version=8.0.6.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].<AddAuthenticationStateProvider>b__1_0(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeServiceProviderEngine.<>c__DisplayClass4_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass9_0.<CreatePropertyInjector>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType, IComponentRenderMode callerSpecifiedRenderMode, Nullable`1 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame[] frames, Int32 frameIndex, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

Custom Authentication State Provider is can only override the fuction GetAuthenticationStateAsync(), i do not see how this is affecting the RemoteAuthenticatorView component.

I think RemoteAuthenticatorView component uses Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticatorViewCore<Microsoft.AspNetCore.Components.WebAssembly.Authentication.RemoteAuthenticationState>

### Expected Behavior

RemoteAuthenticatorView should work even when using CustomAuthenticationStateProvider as the custom class can only affect the state based on claims overriding the fuction GetAuthenticationStateAsync().

### .NET Version

.NET8

**Comment by koureasstavros** [comment]
Just find out that when registering a custom
AuthenticationStateProvider should also register the RemoteAuthenticationService as well in Client side.
`builder.Services.AddScoped<IRemoteAuthenticationService<RemoteAuthenticationState>, RemoteAuthenticationService<RemoteAuthenticationState, RemoteUserAccount, OidcProviderOptions>>();`

**Comment by javiercn** [comment]
@koureasstavros thanks for contacting us.

Seems that you've been able to solve your issue, let us know if otherwise.

**Comment by koureasstavros** [comment]
@javiercn, I managed to solve this problem of redirection when registering a custom
AuthenticationStateProvider should also register the RemoteAuthenticationService as well in Client side.

But seems there are more issues after this one, seems that tokens are not present in the User context into server side, and this happens if .AddHttpMessageHandler<BaseAddressAuthorizationMessageHandler>() does not present on httpclient registration.

When .AddHttpMessageHandler<BaseAddressAuthorizationMessageHandler>() presents on httpclient registration
```
 var httpClientName = "Default";

 builder.Services.AddHttpClient(httpClientName, client => {
     client.BaseAddress = new Uri(builder.HostEnvironment.BaseAddress);
 })
 .AddHttpMessageHandler<BaseAddressAuthorizationMessageHandler>(); //TRANSPORTS AUTH TO SERVER SIDE TO MAKE CONTROLLERS ACCEPT AUTHNTICATES REQUESTS

 builder.Services.AddScoped(
     sp => sp.GetRequiredService<IHttpClientFactory>()
         .CreateClient(httpClientName));
```
there is another produced error when this is combined with CustomAuthenticationStateProvider.

See this detailed one: https://github.com/dotnet/aspnetcore/issues/33787
