### ISSUE TITLE
Mapping same SignalR hub twice results in unexpected error

### ISSUE THREAD

**Issue by blair-ahlquist** [dotnet/aspnetcore#56652]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am using SignalR with an ASP.NET Web API and browser client supplied by the `@microsoft/signalr` package. In the service, I have allowed all cross origin access for development purposes: 

```
builder.Services.AddCors(options =>
{
    options.AddPolicy(name: "anything",
        builder =>
        {
            builder.WithOrigins("*");
            builder.AllowAnyHeader();
            builder.AllowAnyMethod();
        });
});
```

I accidentally mapped the hub twice:

```
app.MapHub<NotificationHub>("/notifications");
...
app.MapHub<NotificationHub>("/notifications");
```

The client is set up with:

```
var connection = new signalR.HubConnectionBuilder().withUrl("https://localhost:7203/notifications", { withCredentials: false }).build();
```

I got this error client side:

```
Access to fetch at 'https://localhost:7203/notifications/negotiate?negotiateVersion=1' from origin 'http://127.0.0.1:5501' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

When I took out the duplicate mapping, the error went away, and the connection was established.

### Expected Behavior

I expect an explicit exception upon duplicate mapping - or idempotent behavior.

### .NET Version

.Net 8.0

**Comment by BrennanConroy** [comment]
The default experience for an app in development mode would log this as an error log:
```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches:

      /default/negotiate
      /default/negotiate
         at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(Span`1 candidateState)
         at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, Span`1 candidateState)
         at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, Span`1 candidateState)
         at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
         at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

If you're running the app for the first time in release or prod for some reason then there isn't much we can do to change what the CORS response shows in the browser. However, when I try this I at least get a 500 in the console which would lead me to look at server logs.
![image](https://github.com/dotnet/aspnetcore/assets/7574801/66ee3f3a-adf7-40b4-aac8-b30351f18f37)

**Comment by BrennanConroy** [comment]
Turn on logging. Even running without the DeveloperExceptionPageMiddleware you will get an error log from Kestrel.

**Comment by blair-ahlquist** [comment]
I believe I have logging enabled. Here is the logging portion of my `appsettings.json`:

```
"Logging": {
  "LogLevel": {
    "Default": "Information",
    "Microsoft.AspNetCore": "Information"
  }
},
```

...and sample output:


```
Microsoft.Hosting.Lifetime: Information: Now listening on: https://localhost:7203
Microsoft.Hosting.Lifetime: Information: Now listening on: http://localhost:5128
Microsoft.Hosting.Lifetime: Information: Application started. Press Ctrl+C to shut down.
Microsoft.Hosting.Lifetime: Information: Hosting environment: Development
```

**Comment by BrennanConroy** [comment]
And when you make a request you don't get an error log?

Example log when I do this with the same appsettings.json
```
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5129
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\brecon\source\repos\WebApplication27\WebApplication27
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 OPTIONS http://localhost:5129/default/negotiate - - -
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HN50D199NT06", Request id "0HN50D199NT06:00000001": An unhandled exception was thrown by the application.
      Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches:

      /default/negotiate
      /default/negotiate
         at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(Span`1 candidateState)
         at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, Span`1 candidateState)
         at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, Span`1 candidateState)
         at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.MatchAsync(HttpContext httpContext)
         at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
         at Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware.Invoke(HttpContext context)
         at Microsoft.WebTools.BrowserLink.Net.BrowserLinkMiddleware.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserRefreshMiddleware.InvokeAsync(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 OPTIONS http://localhost:5129/default/negotiate - 500 0 - 1.3311ms
```

**Comment by blair-ahlquist** [comment]
When I make the request, the error does appear. My apologies.
