### ISSUE TITLE
ServerAuthenticationStateProvider.SetAuthenticationState() throws an exception

### ISSUE THREAD

**Issue by DavidThielen** [dotnet/aspnetcore#56733]
### Discussed in https://github.com/dotnet/aspnetcore/discussions/56689

<div type='discussions-op-text'>

<sup>Originally posted by **DavidThielen** July  9, 2024</sup>
Hi all;
I have written my own AuthenticationStateProvider to add two bits of functionality:
1. I added IdentityUser.Enabled and return an anonymous user ClaimsPrincipal if disabled.
2. It will re-read the claims every 25 minutes.

The attached .cs is referenced in 1 place, during startup. This is in a Blazor server app with the Add Scaffold Item | Identity added. The code use is:

```cs
builder.Services.AddScoped<AuthenticationStateProvider, ExAuthenticationStateProvider>();
```

Bare minimum of the code (full in attached zip):
[ExAuthenticationStateProvider.zip](https://github.com/user-attachments/files/16168968/ExAuthenticationStateProvider.zip)

```cs
public class ExAuthenticationStateProvider : ServerAuthenticationStateProvider
{
    public override async Task<AuthenticationState> GetAuthenticationStateAsync()
    {
        // the ToList() is to make a copy of the claims so we can read the existing ones and then remove from claimsIdentity
        var claimsIdentity = new ClaimsIdentity(authState.User.Identity);
        foreach (var claim in claimsIdentity.Claims.ToList()
            .Where(claim => AuthorizeRules.AllClaimTypes.Contains(claim.Type)))claimsIdentity.RemoveClaim(claim);
        foreach (var databaseClaim in listDatabaseClaims)
            if (databaseClaim is { ClaimType: not null, ClaimValue: not null })
                claimsIdentity.AddClaim(new Claim(databaseClaim.ClaimType, databaseClaim.ClaimValue));

        // set this as the authentication state
        var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);
        authState = new AuthenticationState(claimsPrincipal);
        SetAuthenticationState(Task.FromResult(authState));
    }
}
```

When I call `SetAuthenticationState()` I get:
```
Error 15:18:00.014 [JASMINE]-[] LouisHowe.web.Services.ExAuthenticationStateProvider - GetAuthenticationStateAsync() exception: Cannot access a disposed object.
Object name: 'IServiceProvider'. ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass9_0.<CreatePropertyInjector>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame[] frames, Int32 frameIndex, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.HandleException(Exception exception)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
   at Microsoft.AspNetCore.Components.RenderHandle.Render(RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.RouteView.SetParametersAsync(ParameterView parameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.HtmlRendering.Infrastructure.StaticHtmlRenderer.HandleException(Exception exception)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.HandleExceptionViaErrorBoundary(Exception error, ComponentState errorSourceOrNull)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.SupplyCombinedParameters(ParameterView directAndCascadingParameters)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.NotifyCascadingValueChanged(ParameterViewLifetime& lifetime)
   at Microsoft.AspNetCore.Components.CascadingValueSource`1.<>c__DisplayClass10_0.<NotifyChangedAsync>b__0()
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContextDispatcher.InvokeAsync(Action workItem)
   at Microsoft.AspNetCore.Components.CascadingValueSource`1.NotifyChangedAsync()
   at Microsoft.AspNetCore.Components.CascadingValueSource`1.NotifyChangedAsync(TValue newValue)
   at Microsoft.Extensions.DependencyInjection.CascadingAuthenticationStateServiceCollectionExtensions.AuthenticationStateCascadingValueSource.HandleAuthenticationStateChanged(Task`1 newAuthStateTask)
   at LouisHowe.web.Services.ExAuthenticationStateProvider.GetAuthenticationStateAsync() in C:\Git\LouisHowe\LouisHowe.web\Services\ExAuthenticationStateProvider.cs:line 120
```

Run with the Identity Library and this service in your Blazor app and about 20% of the time `SetAuthenticationState()` is called, it will throw this exception. The other 80% it is fine.

thanks - dave</div>

**Comment by DavidThielen** [comment]
@javiercn Yes that's everything. Should it not be called in `GetAuthenticationStateAsync()`? And if so, how do I tell the Identity Library that the claims have changed?

**Comment by halter73** [comment]
> Should it not be called in `GetAuthenticationStateAsync()`? And if so, how do I tell the Identity Library that the claims have changed?

It will be easier for us to look at after your repro is pushed to a GitHub repo, but if we're talking about Microsoft.AspNetCore.Identity, that's typically done by redirecting to a page where you can set a new cookie using HttpContext.SignInAsync() which sets the `Set-Cookie` and redirects back to a page where Blazor [calls SetAuthenticationState(HttpContext.User) on your behalf](https://github.com/dotnet/aspnetcore/blob/f3db10e251faf5aa26df3de04d1fa184bbe6603f/src/Components/Endpoints/src/Rendering/EndpointHtmlRenderer.cs#L86). The normal CookieAuthenticationHandler deals with both setting the cookie when you call HttpContext.SignInAsync() and then reading the cookie to set HttpContext.User.

Calling SetAuthenticationState yourself can be useful if you want to change authentication state without reloading the page, but you're then on your own figuring out how to persist it. Instead of redirecting, you could try making a fetch request with JS interop to set the cookie.

> Run with the Identity Library and this service in your Blazor app and about 20% of the time SetAuthenticationState() is called, it will throw this exception. The other 80% it is fine.

Your stack trace does not include the caller of `ExAuthenticationStateProvider.GetAuthenticationStateAsync()`. I suspect that this is being done in a place where you cannot be sure the SignalR circuit is still open, and therefore sometimes the scoped service provider is already disposed along with the circuit.

**Comment by DavidThielen** [comment]
@halter73 @javiercn I think you may be right because I created a simple app and of course - it works fine.

I'm thinking my approach may be part of the problem here. So [I just posted my use case I'm trying to address.](https://github.com/dotnet/aspnetcore/discussions/56777) Would you be willing to look at that and tell me the best way to accomplish this? If there's a better way to do this, I've got a solution and there's no need to duplicate this error to find out, my existing approach is fundamentally a bad idea.

thanks - dave

**Comment by mkArtakMSFT** [comment]
Closing as the conversation can now continue in the discussion created by @DavidThielen.
