### ISSUE TITLE
IndexOutOfRangeException in Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ExtraFeatureSet

### ISSUE THREAD

**Issue by zlatanov** [dotnet/aspnetcore#56762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Sometimes we get the following error logged:

```txt
IndexOutOfRangeException: Index was outside the bounds of the array.
    at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.ExtraFeatureSet(Type key, Object value)
    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
```

Looking at the code there, I can't find anything that would cause this error if the code there is not accessed concurrently. Is it possible that, if a connection is aborted while for example the ResponseCompressionMiddleware is being executed, that this ExtraFeatureSet might get executed concurrently?

### Expected Behavior

No exception to occur.

### .NET Version

8.0.2

**Comment by gfoidl** [comment]
Out of curiosity: can you reproduce the same error when using Kestrel instead of IIS? (because the code for `ExtraFeatureSet` is the same)

**Comment by zlatanov** [comment]
> Out of curiosity: can you reproduce the same error when using Kestrel instead of IIS? (because the code for `ExtraFeatureSet` is the same)

No, the error happens very rarely and only in production.
