### ISSUE TITLE
ILLink does not work in Azure DevOps pipeline

### ISSUE THREAD

**Issue by kant2002** [dotnet/aspnetcore#5676]
I hope I select correct repository for this one issue.

Something is wrong with either Azure pre-populated nuget cache, or ILLink task should better select assemblies.

```
2018-12-13T21:24:06.7067783Z Program.cs(12,18): warning CA1052: Type 'Program' is a static holder type but is neither static nor NotInheritable [D:\a\1\s\xxx\xxxx.csproj]
2018-12-13T21:24:06.7783615Z   MedNotes.Diagnostics -> D:\a\1\s\xxxx\bin\Release\netstandard2.0\xxx.dll
2018-12-13T21:24:08.3878656Z   Fatal error in IL Linker
2018-12-13T21:24:08.3879398Z   Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'C:\Users\VssAdministrator\.nuget\packages\system.xml.readerwiter\4.3.1\lib\netstandard1.3\System.Xml.ReaderWriter.dll, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'C:\Users\VssAdministrator\.nuget\packages\system.xml.readerwiter\4.3.1\lib\netstandard1.3\System.Xml.ReaderWriter.dll, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
2018-12-13T21:24:08.3879590Z      at Mono.Linker.DirectoryAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
2018-12-13T21:24:08.3879689Z      at Mono.Linker.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
2018-12-13T21:24:08.3879764Z      at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
2018-12-13T21:24:08.3879844Z      at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
2018-12-13T21:24:08.3880117Z      at Mono.Linker.LinkContext.Resolve(String name)
2018-12-13T21:24:08.3880182Z      at Mono.Linker.Steps.ResolveFromAssemblyStep.Process()
2018-12-13T21:24:08.3880266Z      at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
2018-12-13T21:24:08.3880331Z      at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
2018-12-13T21:24:08.3880412Z      at Mono.Linker.Pipeline.Process(LinkContext context)
2018-12-13T21:24:08.3880576Z      at Mono.Linker.Driver.Run(ILogger customLogger)
2018-12-13T21:24:08.3880641Z      at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
2018-12-13T21:24:08.3947633Z 
```

This happens when publish Blazor client side app on Azure devops. I think this is could be an issue even when Razor components go live

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @kant2002.
@ajaybhargavb, can you please try to publish a Blazor app with Azure DevOps and make sure it works?
@danroth27 co-assigning this to you so you list a similar scenario for CTI to handle.

**Comment by pranavkm** [comment]
The trimmer (linker) is part of the .NET SDK now and should no longer run in to this issue. If you continue seeing this, please file an issue in https://github.com/dotnet/runtime.
