### ISSUE TITLE
Exception in browser when navigating to Blazor page running in InteractiveWebAssembly render mode

### ISSUE THREAD

**Issue by phantomkingx** [dotnet/aspnetcore#56774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Exception in browser when navigating to Blazor page running in InteractiveWebAssembly render mode.

### Steps To Reproduce

Microsoft Visual Studio Community 2022 (64-bit) - Version 17.10.4
.NET SDK 8.0.303

Created a new blazor web app:

![image](https://github.com/user-attachments/assets/97455098-367f-407d-84a9-9091400ca502)
![image](https://github.com/user-attachments/assets/361cd932-d2b4-4361-b285-986f64cbe0d9)

Change the Counter.razor page render mode to InteractiveWebAssembly:

![image](https://github.com/user-attachments/assets/8e73a263-91fa-4c46-90d1-b2d747651521)

Start the app in Visual Studio and navigate to the Counter page:
![image](https://github.com/user-attachments/assets/b3889def-b3e3-4bff-8f24-526f1f41aa75)

### Exceptions (if any)

Error: [MONO] /__w/1/s/src/mono/mono/mini/interp/interp.c:3616 <disabled>
    at ht (logging.ts:95:18)
    at Tl (logging.ts:119:27)
    at dotnet.native.wasm:0xa307
    at dotnet.native.wasm:0x3f440
    at dotnet.native.wasm:0x3bef4
    at dotnet.native.wasm:0x3bfb7
    at dotnet.native.wasm:0x3bfea
    at dotnet.native.wasm:0x1b3c9
    at dotnet.native.wasm:0x1d1bd
    at dotnet.native.wasm:0xe8756

### .NET Version

.NET SDK 8.0.303

### Anything else?

![image](https://github.com/user-attachments/assets/b0c535f0-75b2-4bf0-b187-7dd399a28095)

**Comment by phantomkingx** [comment]
I tried repairing my Visual Studio and no luck.  I installing a preview version of Visual Studio as well and same issue. 

However when installing Visual Studio 2022 Community in a Windows Sandbox I could not reproduce the issue.

**Comment by phantomkingx** [comment]
I found the cause which appears to be mentioned in this closed issue https://github.com/dotnet/runtime/issues/98041

It's frustrating that an issue found in February was marked closed even though it still exists, it made finding the existing issue harder to search for.  Even though the issue has been fixed in .NET 9, that version is still in preview and not a viable option for most production scenarios so the issue shouldn't be closed until .NET 9 is made stable.  And why wouldn't the fix be ported to .NET 8 which is an LTS version?
