### ISSUE TITLE
Failures in Mvc.Template Tests

### ISSUE THREAD

**Issue by captainsafia** [dotnet/aspnetcore#56828]
I'm spotting a few failures in the Mvc.Template tests that seem to orginate from the same space.

## Failing Test(s)

- `Templates.Mvc.Test.RazorPagesTemplateTest.RazorPagesTemplate_IndividualAuth_LocalDb `
- `Templates.Mvc.Test.MvcTemplateTest.MvcTemplate_IndividualAuth`

## Error Message

```text
2024-07-16T01:51:32.8091460Z [xUnit.net 00:14:48.49]     Templates.Mvc.Test.MvcTemplateTest.MvcTemplate_IndividualAuth(useProgramMain: True, noHttps: False) [FAIL]
2024-07-16T01:51:32.9396401Z [xUnit.net 00:14:48.49]       https://learn.microsoft.com/aspnet/core is a broken link!
2024-07-16T01:51:32.9429418Z [xUnit.net 00:14:48.49]       Expected: True
2024-07-16T01:51:32.9429540Z [xUnit.net 00:14:48.49]       Actual:   False
```

## Stacktrace

<details>

```text
2024-07-16T01:51:32.9429588Z [xUnit.net 00:14:48.49]       Stack Trace:
2024-07-16T01:51:32.9429635Z [xUnit.net 00:14:48.49]         /_/src/ProjectTemplates/Shared/AspNetProcess.cs(179,0): at Templates.Test.Helpers.AspNetProcess.ContainsLinks(Page page)
2024-07-16T01:51:32.9429683Z [xUnit.net 00:14:48.49]         /_/src/ProjectTemplates/Shared/AspNetProcess.cs(119,0): at Templates.Test.Helpers.AspNetProcess.AssertPagesOk(IEnumerable`1 pages)
2024-07-16T01:51:32.9429730Z [xUnit.net 00:14:48.49]         /_/src/ProjectTemplates/test/Templates.Mvc.Tests/MvcTemplateTest.cs(256,0): at Templates.Mvc.Test.MvcTemplateTest.MvcTemplate_IndividualAuth_Core(Boolean useLocalDB, Boolean useProgramMain, Boolean noHttps)
2024-07-16T01:51:32.9429818Z [xUnit.net 00:14:48.49]         --- End of stack trace from previous location ---
```
</details>

## Logs

- https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-pull-56810-merge-3b1a77786d4e413a83/Templates.Mvc.Tests--net9.0/1/console.7784d250.log?helixlogtype=result
- https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-pull-56395-merge-6ace9a364643471480/Templates.Mvc.Tests--net9.0/1/console.a4957966.log?helixlogtype=result

## Build

- https://dev.azure.com/dnceng-public/public/_build/results?buildId=742141&view=results
- https://dev.azure.com/dnceng-public/public/_build/results?buildId=742277&view=results

**Comment by sebastienros** [comment]
It hasn't repro-ed since, maybe the site had issues and now it's back up?

**Comment by captainsafia** [comment]
Yeah, let's go ahead and close this.
