### ISSUE TITLE
Assets not found when calling app outside it's directory. Error: `filename.br` could not be found.

### ISSUE THREAD

**Issue by Bartmax** [dotnet/aspnetcore#56851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

If I call a published app outside the app directory statics assets are not found.

calling: 
```
dotnet publish -o dist
.\dist\BlazorApp1.exe
``` 
will result in `System.InvalidOperationException: The file 'BlazorApp1.styles.css.br' could not be found.` for all asset files.

changing directory to the output folder like :
```
cd dist
.\BlazorApp1.exe
```
runs without problem.

### Expected Behavior

App should work regardless of from where it's called, i guess (?)

### Steps To Reproduce

```
dotnet publish -o dist
.\dist\appname.exe
```

### Exceptions (if any)

```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: The file 'BlazorApp1.styles.css.br' could not be found.
         at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.get_FileInfo()
         at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.SendAsync(StaticAssetInvocationContext context)
         at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```

### .NET Version

9.0.100-preview.6.24328.19

### Anything else?

```
PS C:\Users\bart\source\repos\BlazorApp1\BlazorApp1> dotnet publish -o dist
Restore complete (0,2s)
You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
  BlazorApp1 succeeded (0,3s) → dist\

Build succeeded in 0,7s
PS C:\Users\bart\source\repos\BlazorApp1\BlazorApp1> .\dist\BlazorApp1.exe
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\bart\source\repos\BlazorApp1\BlazorApp1
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: The file 'BlazorApp1.styles.css.br' could not be found.
         at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.get_FileInfo()
         at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.SendAsync(StaticAssetInvocationContext context)
         at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: The file 'app.css.br' could not be found.
         at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.get_FileInfo()
         at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.SendAsync(StaticAssetInvocationContext context)
         at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: The file 'bootstrap/bootstrap.min.css.br' could not be found.
         at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.get_FileInfo()
         at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.SendAsync(StaticAssetInvocationContext context)
         at Microsoft.AspNetCore.StaticAssets.StaticAssetsInvoker.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
PS C:\Users\bart\source\repos\BlazorApp1\BlazorApp1> cd dist
PS C:\Users\bart\source\repos\BlazorApp1\BlazorApp1\dist> .\BlazorApp1.exe
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\bart\source\repos\BlazorApp1\BlazorApp1\dist
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
PS C:\Users\bart\source\repos\BlazorApp1\BlazorApp1\dist>
```

![image](https://github.com/user-attachments/assets/41bec2e6-9bce-43b3-a04d-c9696d803fce)

**Comment by javiercn** [comment]
@Bartmax thanks for contacting us.

That's expected. The ContentRoot for the app in your case is setup incorrectly to the parent folder of the `.exe` file, so the compressed files that live in `dist/wwwroot` can't be found.

**Comment by Bartmax** [comment]
Is there anyway to set content path as the path of the executable instead of the running environment ?

**Comment by javiercn** [comment]
@Bartmax you can set the `ASPNETCORE_ContentRoot` environment variable to define it.

Alternatively, you can do it in code by setting the ContentRoot path on the `IWebHostEnvironment` instance during startup to `AppContext.BaseDirectory`

**Comment by Bartmax** [comment]
well, it was only for development purposes. I do publish -o "custom dir" and I wanted to launch/try the app without changing directories and found out it doesn't work.

Not a specific need.
