### ISSUE TITLE
`System.InvalidOperationException: Collection was modified; enumeration operation may not execute.` from `AuthenticationStateProvider.NotifyAuthenticationStateChanged`

### ISSUE THREAD

**Issue by Leon99** [dotnet/aspnetcore#56891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

See STR/Exceptions. Many similar reports in https://github.com/dotnet/aspnetcore/issues/53075, which was erroneously closed.

### Steps To Reproduce

`SignInManager.SignOutAsync()` on the server, then `AuthenticationStateProvider.NotifyAuthenticationStateChanged()` on the client.

### Exceptions (if any)

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator[[Microsoft.AspNetCore.Components.Rendering.ComponentState, Microsoft.AspNetCore.Components, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator[[Microsoft.AspNetCore.Components.Rendering.ComponentState, Microsoft.AspNetCore.Components, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.CascadingValueSource`1.<>c__DisplayClass10_0[[System.Threading.Tasks.Task`1[[Microsoft.AspNetCore.Components.Authorization.AuthenticationState, Microsoft.AspNetCore.Components.Authorization, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<NotifyChangedAsync>b__0()
   at Microsoft.AspNetCore.Components.WebAssembly.Rendering.NullDispatcher.InvokeAsync(Action workItem)
   at Microsoft.AspNetCore.Components.CascadingValueSource`1[[System.Threading.Tasks.Task`1[[Microsoft.AspNetCore.Components.Authorization.AuthenticationState, Microsoft.AspNetCore.Components.Authorization, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].NotifyChangedAsync()
   at Microsoft.AspNetCore.Components.CascadingValueSource`1[[System.Threading.Tasks.Task`1[[Microsoft.AspNetCore.Components.Authorization.AuthenticationState, Microsoft.AspNetCore.Components.Authorization, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].NotifyChangedAsync(Task`1 newValue)
   at Microsoft.Extensions.DependencyInjection.CascadingAuthenticationStateServiceCollectionExtensions.AuthenticationStateCascadingValueSource.HandleAuthenticationStateChanged(Task`1 newAuthStateTask)
   at Microsoft.AspNetCore.Components.Authorization.AuthenticationStateProvider.NotifyAuthenticationStateChanged(Task`1 task)
```

### .NET Version

8.0.205

**Comment by javiercn** [comment]
@Leon99 thanks for contacting us.

Can you provide a minimal repro that demonstrates the problem. It seems that we asked for one in our other issue and as we didn't get one, the system closed the issue.

**Comment by Leon99** [comment]
I'll see what I can do about the minimal repro, it may take more time than I'd like to.
Could you at least give some hints as to what could be happening here? It's definitely an unexpected/undocumented exception that doesn't give any information about the potential root cause, and there are plenty of users that reported the same issue. Shouldn't you be trying to localize it regardless of the existence of the repro?

**Comment by Leon99** [comment]
Just noticed that you reopened https://github.com/dotnet/aspnetcore/issues/53075 - I can confirm that using `<CascadingAuthenticationState>` instead of `.AddCascadingAuthenticationState()` mentioned there helped me, so I'm closing this one. It'd be great to understand the implications of that though, given that https://learn.microsoft.com/en-us/aspnet/core/blazor/security/?view=aspnetcore-8.0#troubleshoot-errors clearly says that `.AddCascadingAuthenticationState()` is the way to go in .NET 8.
