### ISSUE TITLE
[9.0.100-preview.7.24375.12] Markdig nuget package thrown "The parser is in an invalid infinite loop while trying to parse inlines for block..." exception when parsering markdown string to html

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/aspnetcore#57076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When running 3rd part application with the latest .NET 9 build, BlazorStrap and Blog apps failed load page content during switching pages in applications. And the command prompt window throws ```"The parser is in an invalid infinite loop while trying to parse inlines for block [ParagraphBlock] at position ($0, 0, 0-107" exception```.

### Expected Behavior

Switch back from "Shared Parameters" to "Contribute" successfully.
![image](https://github.com/user-attachments/assets/88b4feac-3f4d-40b2-9b6b-1d9a09b0e5db)

### Steps To Reproduce

The machine has dotnet-sdk-9.0.100-preview.7.24375.12 installed.
1. Copy BlazorStrap app from the location mentioned in the [devdiv bug](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2174456).
2. Change the "BlazorStrap.Server.runtimeconfig.json" file to let the app run against with dotnet-sdk-dotnet-sdk-9.0.100-preview.7.24375.12. 
"frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "9.0.0-preview.7.24374.12"
      },
      {
        "name": "Microsoft.AspNetCore.App",
        "version": "9.0.0-preview.7.24373.9"
      }
    ],
3. Launch BlazorStrap.Server.exe.
4. Access http://localhost:5000/ from browser.
5. Click "Contribute" menu.
6. Click "Shared Parameters" menu.
7. Click "Contribute" menu.

### Exceptions (if any)

**Actual Result:**
Switch back from "Shared Parameters" to "Contribute" failed.
![image](https://github.com/user-attachments/assets/0c2cbb81-b1b1-43f2-801b-0fed4345a7d2)

**Stack Trace from Command Prompt:**
```
Unhandled exception rendering component: The parser is in an invalid infinite loop while trying to parse inlines for block [HeadingBlock] at position ($0, 0, 0-19
      System.InvalidOperationException: The parser is in an invalid infinite loop while trying to parse inlines for block [HeadingBlock] at position ($0, 0, 0-19
         at Markdig.Helpers.ThrowHelper.InvalidOperationException(String message)
         at Markdig.Parsers.InlineProcessor.ProcessInlineLeaf(LeafBlock leafBlock)
         at Markdig.Parsers.MarkdownParser.ProcessInlines(InlineProcessor inlineProcessor, MarkdownDocument document)
         at Markdig.Parsers.MarkdownParser.Parse(String text, MarkdownPipeline pipeline, MarkdownParserContext context)
         at Markdig.Markdown.ToHtml(String markdown, MarkdownPipeline pipeline, MarkdownParserContext context)
         at BlazorStrap_Docs.Helper.MarkdownToComponent.BuildRenderTree(RenderTreeBuilder builder) in C:\Users\v-zhiyang\Desktop\YOURSELF\BlazorStrap\src\BlazorStrap-Docs\Helper\MarkdownToComponent.cs:line 93
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'cwy0vMhNv_dIuMXmt46dyA7Bj5ivmQY-xXaGYDTlK6s'.
      System.InvalidOperationException: The parser is in an invalid infinite loop while trying to parse inlines for block [HeadingBlock] at position ($0, 0, 0-19
         at Markdig.Helpers.ThrowHelper.InvalidOperationException(String message)
         at Markdig.Parsers.InlineProcessor.ProcessInlineLeaf(LeafBlock leafBlock)
         at Markdig.Parsers.MarkdownParser.ProcessInlines(InlineProcessor inlineProcessor, MarkdownDocument document)
         at Markdig.Parsers.MarkdownParser.Parse(String text, MarkdownPipeline pipeline, MarkdownParserContext context)
         at Markdig.Markdown.ToHtml(String markdown, MarkdownPipeline pipeline, MarkdownParserContext context)
         at BlazorStrap_Docs.Helper.MarkdownToComponent.BuildRenderTree(RenderTreeBuilder builder) in C:\Users\v-zhiyang\Desktop\YOURSELF\BlazorStrap\src\BlazorStrap-Docs\Helper\MarkdownToComponent.cs:line 93
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```

### .NET Version

9.0.100-preview.7.24375.12

### Anything else?

**Minimal Repro steps (repro demo attached):**
1.Create a Blazor Server App project.
2. Install Markdig nuget package.
3. Add a MarkdownToComponent.cs class file with following content:
```
    public class MarkdownToComponent : ComponentBase
    {
        [Parameter] public RenderFragment? ChildContent { get; set; }
        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {

            string s = @"The following are **guide lines** on howto contribute. You input is always **welcomed** and **appreciated**.

### Feature Request
---
If you feel BlazorStrap is lacking a feature you need or just want please create a issue with the following.
* What does it do
* Why you feel it should exist
* How can it help others";
            string ms = Markdown.ToHtml(s);
        }
    }
```
5. Add above component to Counter.razor page.
```
<p role="status">Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>
<MarkdownToComponent>Test</MarkdownToComponent>
```
7. Build the project.
8. Update the runtime.config file to run against with dotnet-sdk-dotnet-sdk-9.0.100-preview.7.24375.12. 
```
"frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "9.0.0-preview.7.24374.12"
      },
      {
        "name": "Microsoft.AspNetCore.App",
        "version": "9.0.0-preview.7.24373.9"
      }
    ],
```
10. Launch the project.
11. Access http://localhost:5000/ from browser.
12. Navigate to Counter page.
13. Refresh the Counter page 7 times.

Expected Result:
The Counter page refresh 7 time successfully.

Actual Result:
The Counter page refresh failed at the 7th refresh with following error:
```
System.InvalidOperationException: 'The parser is in an invalid infinite loop while trying to parse inlines for block [ParagraphBlock] at position ($0, 0, 0-107'

Stack Trace:
   at Markdig.Helpers.ThrowHelper.InvalidOperationException(String message)
   at Markdig.Parsers.InlineProcessor.ProcessInlineLeaf(LeafBlock leafBlock)
   at Markdig.Parsers.MarkdownParser.ProcessInlines(InlineProcessor inlineProcessor, MarkdownDocument document)
   at Markdig.Parsers.MarkdownParser.Parse(String text, MarkdownPipeline pipeline, MarkdownParserContext context)
   at Markdig.Markdown.ToHtml(String markdown, MarkdownPipeline pipeline, MarkdownParserContext context)
   at MarkdownToHtmlDemo.MarkdownToComponent.BuildRenderTree(RenderTreeBuilder builder) in E:\Demos\MarkdownToHtmlDemo\MarkdownToHtmlDemo\MarkdownToComponent.cs:line 26
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```
**Findings:**

- 2 apps are all referenced Markdig nuget package and the exception in 2 apps are both thrown from Markdown.ToHtml() method which is used to convert a markdown file sting to html.
- The [Markdig](https://github.com/xoofx/markdig) nuget package is used by 5.8k users. It may affect more users in real world.
- This issue will occurs after switching pages in applications multiple times or refresh the page multiple times. The first time load the page can successful.

@dotnet-actwx-bot @dotnet/compat

**Comment by Junjun-zhao** [comment]
@mkArtakMSFT Could you help look at this bug and help triage it?  In the meantime, could you please help confirm if this is a blocker for .NET 9 Preview 7?   Please help move to correct team if it is not correct.  Thanks.

**Comment by javiercn** [comment]
@Junjun-zhao based on the source of the call stack this doesn't seem blazor specific.

The exception is coming from a third-party component.

```
   at Markdig.Helpers.ThrowHelper.InvalidOperationException(String message)
   at Markdig.Parsers.InlineProcessor.ProcessInlineLeaf(LeafBlock leafBlock)
   at Markdig.Parsers.MarkdownParser.ProcessInlines(InlineProcessor inlineProcessor, MarkdownDocument document)
   at Markdig.Parsers.MarkdownParser.Parse(String text, MarkdownPipeline pipeline, MarkdownParserContext context)
   at Markdig.Markdown.ToHtml(String markdown, MarkdownPipeline pipeline, MarkdownParserContext context)
```

**Comment by Junjun-zhao** [comment]
Yes @javiercn , the call stack seem come from Markdig nuget package, but this is a behavior change from dotnet-sdk-9.0.100-preview.7.24375.12 as it passed on dotnet-sdk-9.0.100-preview.7.24371.4. Could you please look into what change caused this?

**Comment by MackinnonBuck** [comment]
Thanks for reaching out, @Junjun-zhao. In order for us to investigate this further, we need a minimal repro project that doesn't utilize third-party code.

**Comment by PriyaPurkayastha** [comment]
@MackinnonBuck we are the .NET AppCompat team and we test 3rd Party apps with latest runtime to log bugs. We try to provide minimal repros wherever possible, but we might not have the expertise to create minimal repro without using 3rd party code. We have provided a repro machine with the two apps that are showing a change in behavior. We would need help from ASPNET Core team to look at the repro machine provided and investigate to root cause the change in behavior - probably review what changes have been made in this space recently that could have introduced the regression.

**Comment by Junjun-zhao** [comment]
@MackinnonBuck During our further investigation, we found this issue also reproduces with a console app. We tried to reference the [Markdig (version 0.37.0) source code](https://github.com/xoofx/markdig/archive/refs/tags/0.37.0.zip) instead of installing it from nuget package manager, it doesn't repro in debug mode. But if we enable **```compiler optimizations```** on debug mode for Markdig project, this issue will repro. It doesn't reproduce this issue in dotnet-sdk-9.0.100-preview.7.24371.4 build. We think something might do with optimization code in 9.0.100-preview.7.24375.12 which cause this issue and it seems a runtime issue, could you please check and move it to the right team? Thanks.

**Update the Minimal repro steps with console project:** (repro demo attached[DemoForMarkdownToHtml.zip](https://github.com/user-attachments/files/16448890/DemoForMarkdownToHtml.zip)):
1.Create a Console project.
2. Install Markdig nuget package.
3. Add a following code to Program.cs file:
```
   using Markdig;

string s = @"The following are **guide lines** on howto contribute. You input is always **welcomed** and **appreciated**.

### Feature Request
---
If you feel BlazorStrap is lacking a feature you need or just want please create a issue with the following.
* What does it do
* Why you feel it should exist
* How can it help others";
for (int i = 0; i < 20000; i++)
{
    string ms = Markdown.ToHtml(s);
}
Console.WriteLine("Hello, World!");
```
5. Build the project.
6. Update the runtime.config file to run against with dotnet-sdk-dotnet-sdk-9.0.100-preview.7.24375.12. 
```
"framework": {
      "name": "Microsoft.NETCore.App",
      "version": "9.0.0-preview.7.24374.12"
    },
```
8. Launch the project.

Expected Result:
Console application will output "Hello World!" successful.

Actual Result:
Console application run with following error:
```
System.InvalidOperationException: 'The parser is in an invalid infinite loop while trying to parse inlines for block [ParagraphBlock] at position ($0, 0, 0-107'

Stack Trace:
   at Markdig.Helpers.ThrowHelper.InvalidOperationException(String message)
   at Markdig.Parsers.InlineProcessor.ProcessInlineLeaf(LeafBlock leafBlock)
   at Markdig.Parsers.MarkdownParser.ProcessInlines(InlineProcessor inlineProcessor, MarkdownDocument document)
   at Markdig.Parsers.MarkdownParser.Parse(String text, MarkdownPipeline pipeline, MarkdownParserContext context)
   at Markdig.Markdown.ToHtml(String markdown, MarkdownPipeline pipeline, MarkdownParserContext context)
   at MarkdownToHtmlDemo.MarkdownToComponent.BuildRenderTree(RenderTreeBuilder builder) in E:\Demos\MarkdownToHtmlDemo\MarkdownToHtmlDemo\MarkdownToComponent.cs:line 26
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```

**Comment by javiercn** [comment]
@Junjun-zhao thanks for the additional details.

This seems to be a regression somewhere in the runtime. I'm transferring the issue
