### ISSUE TITLE
connection Abort + Dispose crashes process

### ISSUE THREAD

**Issue by JanEggers** [dotnet/aspnetcore#57098]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I implemented A custom protocol and when I try to close an incoming connection my process crashes

### Expected Behavior

Im able to close a connection.

### Steps To Reproduce

[TestMethod]
public async Task TestCancelConnection()
{
    var connection = new DefaultConnectionContext();
    connection.Abort();
    await connection.DisposeAsync();

    await Task.Delay(TimeSpan.FromSeconds(1));
}

https://github.com/dotnet/aspnetcore/blob/6dc454f9079ff8d4b268b7e307dd14a05917e903/src/Servers/Connections.Abstractions/src/DefaultConnectionContext.cs#L101

looks like this should have a catch or something that does not blow up if the connection is disposed

### Exceptions (if any)

The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.Cancel()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

### .NET Version

8.0.6

**Comment by amcasey** [comment]
It does seem like the queued work needs to be able to handle state changes that happen between scheduling and running.

**Comment by Andrei-hub11** [comment]
Would wrapping the Cancel() call in a try-catch be an acceptable solution to prevent the process from crashing due to an ObjectDisposedException, or would you prefer a different approach? @amcasey

**Comment by ana1250** [comment]
I've been looking into this and it seems like a race between Abort() and DisposeAsync().

Abort() queues the Cancel() call on the ThreadPool, so if DisposeAsync() runs first and disposes the CTS, the queued Cancel() can throw ObjectDisposedException on a background thread and crash the process.

In that case the connection is already closing, so catching and ignoring ObjectDisposedException around Cancel() should be fine.

I can put up a PR with this change and add a regression test.
