### ISSUE TITLE
Quarantine `Microsoft.AspNetCore.Components.E2ETest.Tests.RoutingTest.NavigationLock_CanBlockExternalNavigation` and friends

### ISSUE THREAD

**Issue by MackinnonBuck** [dotnet/aspnetcore#57153]
## Failing Test(s)

- `Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.NavigationLockPrerenderingTest.NavigationIsLockedAfterPrerendering`
- `Microsoft.AspNetCore.Components.E2ETest.Tests.RoutingTest.NavigationLock_CanBlockExternalNavigation`
- `Microsoft.AspNetCore.Components.E2ETest.ServerExecutionTests.ServerRoutingTest.NavigationLock_CanBlockExternalNavigation`

## Error Message

```text
OpenQA.Selenium.NoAlertPresentException : no such alert
```

## Stacktrace

<details>

```text
   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.ExecuteAsync(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.WebDriver.InternalExecute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.TargetLocator.Alert()
   at Microsoft.AspNetCore.Components.E2ETest.Tests.RoutingTest.NavigationLock_CanBlockExternalNavigation() in /home/vsts/work/1/s/src/Components/test/E2ETest/Tests/RoutingTest.cs:line 1100
```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=764364&view=ms.vss-test-web.build-test-results-tab

**Comment by javiercn** [comment]
@MackinnonBuck this issue has to remain open, isn't it?

**Comment by MackinnonBuck** [comment]
@javiercn yes, I believe so.

**Comment by SteveSandersonMS** [comment]
Is this some breaking change inside a newer version Selenium?

**Comment by amcasey** [comment]
Is this affecting `release/8.0` as well?

**Comment by halter73** [comment]
I noticed this is still happening when I tried unquarantining the tests in #57978. Two of the failures were `OpenQA.Selenium.NoAlertPresentException : no such alert` as seen above, but one of them showed a different error:

```
OpenQA.Selenium.JavaScriptException : javascript error: Blazor is not defined
(Session info: chrome=128.0.6613.137)

   at OpenQA.Selenium.WebDriver.UnpackAndThrowOnError(Response errorResponse, String commandToExecute)
   at OpenQA.Selenium.WebDriver.ExecuteAsync(String driverCommandToExecute, Dictionary`2 parameters)
   at Microsoft.AspNetCore.Components.E2ETest.Tests.RoutingTest.SetAbsluteUrlViaPushState(String absoluteUri, Boolean forceLoad) in /home/vsts/work/1/s/src/Components/test/E2ETest/Tests/RoutingTest.cs:line 1792
   at Microsoft.AspNetCore.Components.E2ETest.Tests.RoutingTest.NavigationLock_CanBlockExternalNavigation() in /home/vsts/work/1/s/src/Components/test/E2ETest/Tests/RoutingTest.cs:line 1099
   at InvokeStub_RoutingTest.NavigationLock_CanBlockExternalNavigation(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

https://dev.azure.com/dnceng-public/public/_build/results?buildId=814364&view=ms.vss-test-web.build-test-results-tab&runId=21102442&resultId=101176&paneView=debug

**Comment by ilonatommy** [comment]
Might be connected: https://github.com/SeleniumHQ/selenium/issues/14450. Using BiDi as a fix is not working, these tests are using BiDi and are failing regardless.

**Comment by oroztocil** [comment]
We are already enabling the BiDi mode for the relevant tests: https://github.com/dotnet/aspnetcore/blob/a813ad450371e4c72578ac2d2d39a57e49dad23a/src/Shared/E2ETesting/BrowserFixture.cs#L143

However, it seems like Selenium/ChromeDriver is ignoring this, or ignoring the `UnhandledPromptBehavior` setting regardless of its value. In particular according to [Selenium docs](https://www.selenium.dev/documentation/webdriver/drivers/options/#unhandledpromptbehavior), the default behavior is DismissAndNotify. That means that what should be happening in our tests is that those alerts are automatically dismissed and an `OpenQA.Selenium.UnhandledAlertException` is thrown. However, no such exception is being thrown.
 
The important takeaway now is that the `NavigationLock` Blazor component works correctly based on manual testing. We are making the failing automatic tests skipped in #63557. We can re-evaluate the tests later if a future Selenium update changes the situation.
