### ISSUE TITLE
[Blazor Server] [net6 / net8] "InvalidOperationException: Cannot find the fallback endpoint specified by route values: { page: /_Host, area: }" When running fresh Blazor app

### ISSUE THREAD

**Issue by Rafnel** [dotnet/aspnetcore#57290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I created a fresh ASP NET Core Blazor Server app through Visual Studio and upon running it and opening the app's webpage, I get this error:
```
System.InvalidOperationException: Cannot find the fallback endpoint specified by route values: { page: /_Host, area:  }.
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.DynamicPageEndpointMatcherPolicy.ApplyAsync(HttpContext httpContext, CandidateSet candidates)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Screenshot below:

<img width="1032" alt="Screenshot 2024-08-12 124631" src="https://github.com/user-attachments/assets/8e131ba9-0d6b-4399-a606-82ce29a88e1f">

I got this behavior even on a fresh Blazor Server app using the template in Visual Studio:
![Screenshot 2024-08-12 134929](https://github.com/user-attachments/assets/e57d389e-e223-4802-b8df-24b39b24bddf)

I found a closed issue with the same problem: https://github.com/dotnet/aspnetcore/issues/36535 and can confirm that adding 
```
<PropertyGroup>
    <UseRazorSourceGenerator>false</UseRazorSourceGenerator>
  </PropertyGroup>
```
to the .csproj fixes this issue, although disables hot reloading unfortunately. Also, the linked issue was "resolved" in 2021 even though it appears the issue persists, at least on the versions of .NET/Visual Studio that I'm using. The linked issue says that this was fixed in Visual Studio 2022 17.0.0, however I'm using the newer 17.8 version and it still has this issue. Any help appreciated!!

### Expected Behavior

When running a fresh Blazor Server app, I should be able to run it and view the home page on the app (in this template, it should say "Hello, world!".

### Steps To Reproduce

* Open Visual Studio Professional 2022 (LTSC Version 17.8.3)
* Click "Create a new project"
* Search for "blazor" in the templates
* Click "Blazor Server App"
* Choose NET 6.0
* Run the app and see the error message
* Change `TargetFramework` in csproj to net8.0 and confirm the error occurs in NET8.0 as well

### Exceptions (if any)

```
System.InvalidOperationException: Cannot find the fallback endpoint specified by route values: { page: /_Host, area:  }.
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.DynamicPageEndpointMatcherPolicy.ApplyAsync(HttpContext httpContext, CandidateSet candidates)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### .NET Version

8.0.303

### Anything else?

**Tools:**

Microsoft Visual Studio Professional 2022
Version 17.8.3
VisualStudio.17.Release.LTSC.17.8/17.8.3+34330.188
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

Visual C++ 2022  \
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.8.358.6298
ASP.NET and Web Tools

C# Tools   4.8.0-7.23572.1+7b75981cf3bd520b86ec4ed00ec156c8bc48e4eb
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Razor (ASP.NET Core)   17.8.3.2358002+8c7fb27bf8e8d4f9ff8080b624b35bca5e812e97
Provides languages services for ASP.NET Core Razor.

---------------

.NET SDK:
 Version:           8.0.303
 Commit:            29ab8e3268
 Workload version:  8.0.300-manifests.c915c39d
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.303\

**Comment by javiercn** [comment]
@Rafnel thanks for contacting us.

There's likely something that is causing the razor source generator to fail.
* To confirm: Disabling the source generator didn't work, did it?
* Can you collect the error that the source generator is producing?

**Comment by Rafnel** [comment]
Hi @javiercn , I'm not certain how to collect the error from the source generator. The stack trace does not provide a line of code for which I can surround in a try/catch. I did collect a fuller version of the exception from Windows Event Viewer:

```
Category: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware
EventId: 1
SpanId: 7774cef28b1a99f2
TraceId: 42a72e82dd71e3ffed8305b22d8e28b9
ParentId: 0000000000000000
ConnectionId: 0HN5RJV5O7B5L
RequestId: 0HN5RJV5O7B5L:00000007
RequestPath: /

An unhandled exception has occurred while executing the request.

Exception: 
System.InvalidOperationException: Cannot find the fallback endpoint specified by route values: { page: /_Host, area:  }.
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.DynamicPageEndpointMatcherPolicy.ApplyAsync(HttpContext httpContext, CandidateSet candidates)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Please let me know how I can collect the saource generator error if possible. Thanks.

**Comment by javiercn** [comment]
@Rafnel no worries, thanks for the details.

I'm trying to make sure I understand where the issue comes from in order to appropriately route it.
