### ISSUE TITLE
Blazor WASM: OnDragEnd EventCallback throws an exception on latest Firefox, worked fine previously

### ISSUE THREAD

**Issue by jonganej** [dotnet/aspnetcore#57309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Ending a drag of a DOM element with an attached method to the `ondragend` delegate, e.g.  `@ondragend="MyOnDragEnd"` DOM event results in an exception and the `MyOnDragEnd` method is not called. 

From the exception message (see below), it seems like the contract for some JSON data is no longer correct?

This happens only on Firefox 129.0.1, the latest version at the time of writing, but was fine on 128.0.3. Still works fine on MS Edge. Wondering if this might be due to a change in API on FF or a security patch that might continue breaking Blazor's DOM event delegate mechanism (at least for `ondragend`) from now on.

### Expected Behavior

`MyOnDragEnd` method should be called when dragging of a DOM element ends

### Steps To Reproduce

Create sample Blazor WASM project. Add simple draggable div. Drag div and release. Exception follows

```
<div style="background-color:aquamarine; padding: 2rem;" draggable="true" @ondragstart="DragStart" @ondragend="DragEnd">
    Drag me
</div>

@code {
    private void DragStart() 
    {
         Console.WriteLine("Drag start");
    }

   private void DragEnd() 
    {
         // Method does not get called. Exception thrown before
         Console.WriteLine("Drag end"); 
    }
}
```

### Exceptions (if any)

Exception on Browser console:

```
Uncaught (in promise) Error: System.InvalidOperationException: There was an error parsing the event arguments. EventId: '4'.
 ---> System.InvalidOperationException: The requested operation requires an element of type 'Object', but the target element has type 'Null'.
   at System.Text.Json.ThrowHelper.ThrowJsonElementWrongTypeException(JsonTokenType expectedType, JsonTokenType actualType)
   at System.Text.Json.JsonElement.EnumerateObject()
   at Microsoft.AspNetCore.Components.Web.DragEventArgsReader.ReadDataTransfer(JsonElement jsonElement)
   at Microsoft.AspNetCore.Components.Web.DragEventArgsReader.Read(JsonElement jsonElement)
   at Microsoft.AspNetCore.Components.Web.WebEventData.TryDeserializeStandardWebEventArgs(String eventName, JsonElement eventArgsJson, EventArgs& eventArgs)
   at Microsoft.AspNetCore.Components.Web.WebEventData.ParseEventArgsJson(Renderer renderer, JsonSerializerOptions jsonSerializerOptions, UInt64 eventHandlerId, String eventName, JsonElement eventArgsJson)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Components.Web.WebEventData.ParseEventArgsJson(Renderer renderer, JsonSerializerOptions jsonSerializerOptions, UInt64 eventHandlerId, String eventName, JsonElement eventArgsJson)
   at Microsoft.AspNetCore.Components.Web.WebEventData.Parse(Renderer renderer, JsonSerializerOptions jsonSerializerOptions, WebEventDescriptor eventDescriptor, JsonElement eventArgsJson)
   at Microsoft.AspNetCore.Components.Web.WebEventData.Parse(Renderer renderer, JsonSerializerOptions jsonSerializerOptions, JsonElement eventDescriptorJson, JsonElement eventArgsJson)
   at Microsoft.AspNetCore.Components.RenderTree.WebRenderer.WebRendererInteropMethods.DispatchEventAsync(JsonElement eventDescriptor, JsonElement eventArgs)
   at System.Object.InvokeStub_WebRendererInteropMethods.DispatchEventAsync(Object , Span`1 )
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
--- End of stack trace from previous location ---
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet(JSRuntime jsRuntime, DotNetInvocationInfo invocationInfo, String argsJson)
```

### .NET Version

8.0.204

**Comment by jonganej** [comment]
@javiercn Thanks for the quick reply.
- Set a breakpoint on `ondragend`, found out that on 128 (working), the DataTransfer property is non-null but it is null on 129 (broken). That explains the exception too, that it is expecting an object but received a null
- Minimal repo: https://github.com/jonganej/blazor-wasm-drag-drop-bug-sample. Ran with VS 2022.

**Comment by javiercn** [comment]
@jonganej thanks for the additional details.

That definitely seems like a bug on Firefox.

**Comment by MackinnonBuck** [comment]
Closing this out because we think this is a bug in Firefox rather than a bug in the framework (see the [MDN page](https://developer.mozilla.org/docs/Web/API/DragEvent/dataTransfer#value) about the `dataTransfer` property; it should never be `null`). Please feel free to file a Firefox bug - thank you!

**Comment by alfattack** [comment]
Looks like this might be the bug in question

https://bugzilla.mozilla.org/show_bug.cgi?id=1911486#c17

**Comment by axiomisinc** [comment]
Had this same issue with some drag and drop functionality in Blazor wasm. Looks like it has now been updated and fixed. After updating Firefox, our issue resolved itself.
