### ISSUE TITLE
JSON deserialization errors with response.Content.ReadFromJsonAsync<List<T>> where JsonSerializer.Deserialize works fine

### ISSUE THREAD

**Issue by mip1983** [dotnet/aspnetcore#57626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I've started hitting some errors in my blazor web application (in a wasm component) where it's deserializing a response from an API. In debugging the code, I can't see anything wrong with the JSON and it serializes/deserializes fine server side and deserializes fine client side if I get the response as a string and use 'JsonSerializer.Deserialize'.

But, if I use:

```cs
mydata= await response.Content.ReadFromJsonAsync<List<MyType>>(serializerOpts, ct);
```

(Where serializer opts are the same as what was working with 'JsonSerializer.Deserialize'), I hit fairly non-descript exceptions where I can't see anything wrong with the item it's pointing at in the path e.g. 

```
System.Text.Json.JsonException: The JSON value could not be converted to <MyType>. Path: $[81] | LineNumber: 0 | BytePositionInLine: 49154.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[<MyType> ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, <MyType>& value)
   at System.Text.Json.Serialization.JsonConverter`1[[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, MeterListItem& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonCollectionConverter`2[[System.Collections.Generic.List`1[[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, List`1& value)
   at System.Text.Json.Serialization.JsonConverter`1[[System.Collections.Generic.List`1[[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, List`1& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1[[System.Collections.Generic.List`1[[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1[[System.Collections.Generic.List`1[[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.<DeserializeAsync>d__1[[System.Collections.Generic.List`1[[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Net.Http.Json.HttpContentJsonExtensions.<ReadFromJsonAsyncCore>d__12`1[[System.Collections.Generic.List`1[[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at ecoDriverAnalytics.Api.Client.HttpClients.MeterClient.Get<MyType>Async(Int32 userId, Int16 customerId, CancellationToken ct) in <Path>.ApiClient\HttpClients\<MyHttpClient>Client.cs:line 73
```

### Expected Behavior

If 'JsonSerializer.Deserialize' can deserialize some content, 'HttpResponseMessage.Content.ReadFromJsonAsync<List<T>' should be able to do the same with the same options without error (and if it does error, at the very least give some description as to what was wrong with the content).

### Steps To Reproduce

I can't tell what it doesn't like about the JSON in order to give a minimal repro. The Path/byte position of the sample error doesn't reveal anything meaningful as far as I can tell.

I can provide you with sample JSON to test against, you'll need to reach out to me directly so I can share this privately. 

### Exceptions (if any)

System.Text.Json.JsonException: The JSON value could not be converted to <MyType>. Path: $[81] | LineNumber: 0 | BytePositionInLine: 49154.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[<MyType> ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, <MyType>& value)
   at System.Text.Json.Serialization.JsonConverter`1[[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, MeterListItem& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonCollectionConverter`2[[System.Collections.Generic.List`1[[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, List`1& value)
   at System.Text.Json.Serialization.JsonConverter`1[[System.Collections.Generic.List`1[[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, List`1& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1[[System.Collections.Generic.List`1[[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1[[System.Collections.Generic.List`1[[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.<DeserializeAsync>d__1[[System.Collections.Generic.List`1[[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Net.Http.Json.HttpContentJsonExtensions.<ReadFromJsonAsyncCore>d__12`1[[System.Collections.Generic.List`1[[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at ecoDriverAnalytics.Api.Client.HttpClients.MeterClient.Get<MyType>Async(Int32 userId, Int16 customerId, CancellationToken ct) in <Path>.ApiClient\HttpClients\<MyHttpClient>Client.cs:line 73

### .NET Version

8.0.401

### Anything else?

Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.11.2

Host:
  Version:     8.0.401 [C:\Program Files\dotnet\sdk]
  Architecture: x64
  Commit:       static

.NET SDKs installed:
  8.0.304 [C:\Program Files\dotnet\sdk]
  8.0.400 [C:\Program Files\dotnet\sdk]
  8.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.7.24406.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.7.24405.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by martincostello** [comment]
I wonder if it's to do with some data crossing a buffer threshold, as that index in your example is suspiciously close to being evenly divisible by 4096. (4096x12 + 2)

**Comment by mip1983** [comment]
Thanks for the hint @martincostello, I've tried increasing DefaultBufferSize in JsonSerializerOptions to 32000, and that seems to work so far.

I don't know if calling 'ReadFromJsonAsync' should handle this internally and re-size the buffer without causing serialization errors, or if it should throw a meaningful exception if the buffer is exceeded, but either way, I think this needs some attention.

**Comment by martincostello** [comment]
Yeah it seems like a bug to me - I don't know whether it's a Blazor issue (this repo) or a System.Text.Json issue (dotnet/runtime) though.

**Comment by amcasey** [comment]
I believe `ReadFromJsonAsync` is quite a thin [wrapper](https://github.com/dotnet/aspnetcore/blob/3586ac9dd9e75e1c0159c85704d357bce9b25fd0/src/Http/Http.Extensions/src/HttpRequestJsonExtensions.cs) around `JsonSerializer.DeserializeAsync`.  It does, however, look for options in more places, so it seems possible that the actual value passed to `DeserializeAsync` differs between the two calls.

**Comment by eiriktsarpalis** [comment]
@mip1983 would it be possible to share a minimal reproduction that we can check? This should include the E2E app (including your `MyType` declaration and your `JsonSerializerOptions` configuration). The smaller you can make it, the quicker it will be for us to respond -- ideally it should just be a console app with a few function calls.

**Comment by mip1983** [comment]
> [@mip1983](https://github.com/mip1983) would it be possible to share a minimal reproduction that we can check? This should include the E2E app (including your `MyType` declaration and your `JsonSerializerOptions` configuration). The smaller you can make it, the quicker it will be for us to respond -- ideally it should just be a console app with a few function calls.

@eiriktsarpalis  Just had a stab at this, trying to repro outside my solution. Had to copy a fair bit of code before it would do it, but download, hit F5, it should generate a large json file, then try to download it on a blazor web assembly component. I don't think I need as large a payload to get the problem, but this seems to make it likely:

https://github.com/mip1983/JsonDeserializationErrors

**Comment by eiriktsarpalis** [comment]
This is a duplicate of https://github.com/dotnet/runtime/issues/110450 -- a confirmed bug in `System.Text.Json`'s streaming deserialization state machine. When a `Nullable<T>` struct property's JSON object straddles an internal read buffer boundary, `DeserializeAsync` and `DeserializeAsyncEnumerable` throw `JsonException` while synchronous deserialization succeeds.

The original issue only reproduced with `DefaultBufferSize = 1` on .NET 9, but this scenario (Blazor WASM + `ReadFromJsonAsAsyncEnumerable` over HTTP) triggers it with default buffer sizes because the network stream delivers data in small chunks. Here is a minimal standalone repro that confirms both behaviors:

<details>
<summary>Minimal repro (console app, .NET 9)</summary>

```csharp
using System.Text;
using System.Text.Json;

int totalFails = 0;

Console.WriteLine("=== Test 1: Simplest repro (DeserializeAsync, DefaultBufferSize=1) ===");
totalFails += await Test_DeserializeAsync_SmallBuffer();

Console.WriteLine();
Console.WriteLine("=== Test 2: DeserializeAsyncEnumerable via throttled stream ===");
Console.WriteLine("    (Simulates real network delivery as in aspnetcore#57626)");
totalFails += await Test_AsyncEnumerable_ThrottledStream();

Console.WriteLine();
Console.WriteLine("=== Test 3: DeserializeAsync at default 16KB buffer boundary ===");
totalFails += await Test_DeserializeAsync_DefaultBufferBoundary();

Console.WriteLine();
Console.WriteLine($"Total failures: {totalFails}");
return totalFails > 0 ? 1 : 0;

static async Task<int> Test_DeserializeAsync_SmallBuffer()
{
    string json = """
        [{"Start":{"Padding1":"x","Value":100.86587,"Padding2":null}},{"Start":{"Padding1":"xxxxx","Value":100.08407,"Padding2":null}}]
        """;

    var syncResult = JsonSerializer.Deserialize<List<Dto>>(json);
    Console.WriteLine($"  Sync:  OK ({syncResult!.Count} items)");

    try
    {
        var options = new JsonSerializerOptions { DefaultBufferSize = 1 };
        using var stream = new MemoryStream(Encoding.UTF8.GetBytes(json));
        var result = await JsonSerializer.DeserializeAsync<List<Dto>>(stream, options);
        Console.WriteLine($"  Async (buffer=1): OK ({result!.Count} items)");
        return 0;
    }
    catch (JsonException ex)
    {
        Console.WriteLine($"  Async (buffer=1): FAILED - {ex.Message}");
        return 1;
    }
}

static async Task<int> Test_AsyncEnumerable_ThrottledStream()
{
    var items = GenerateItems(500);
    string json = JsonSerializer.Serialize(items);
    Console.WriteLine($"  Payload: {json.Length:N0} bytes");

    int fails = 0;
    foreach (int chunkSize in new[] { 1, 7, 64, 256, 4096 })
    {
        try
        {
            using var stream = new ThrottledStream(Encoding.UTF8.GetBytes(json), chunkSize);
            int count = 0;
            await foreach (var item in JsonSerializer.DeserializeAsyncEnumerable<Dto>(stream))
            {
                count++;
            }
            Console.WriteLine($"  AsyncEnumerable (chunk={chunkSize,4}): OK ({count} items)");
        }
        catch (JsonException ex)
        {
            Console.WriteLine($"  AsyncEnumerable (chunk={chunkSize,4}): FAILED - {ex.Message}");
            fails++;
        }
    }
    return fails;
}

static async Task<int> Test_DeserializeAsync_DefaultBufferBoundary()
{
    const int bufferSize = 16384;
    int fails = 0;

    for (int pad = bufferSize - 200; pad < bufferSize + 200; pad++)
    {
        string testJson = "[" + new string(' ', pad) +
            "{\"Start\":{\"Padding1\":\"x\",\"Value\":100.08407,\"Padding2\":null}}," +
            "{\"Start\":{\"Padding1\":\"xxxxx\",\"Value\":100.08407,\"Padding2\":null}}]";
        try
        {
            using var stream = new MemoryStream(Encoding.UTF8.GetBytes(testJson));
            await JsonSerializer.DeserializeAsync<List<Dto>>(stream);
        }
        catch (JsonException)
        {
            fails++;
            if (fails <= 3)
                Console.WriteLine($"  FAILED at pad={pad} (payload={testJson.Length} bytes)");
        }
    }
    Console.WriteLine($"  Failures scanning {bufferSize}-200..{bufferSize}+200: {fails}/400");
    return fails;
}

static List<Dto> GenerateItems(int count)
{
    var random = new Random(42);
    var items = new List<Dto>(count);
    for (int i = 0; i < count; i++)
    {
        items.Add(new Dto
        {
            Start = new NullableStruct
            {
                Value = (float)(random.NextDouble() * 200),
                Padding1 = new string('x', random.Next(1, 20)),
                Padding2 = random.Next(2) == 0 ? null : "some-value"
            }
        });
    }
    return items;
}

public class Dto
{
    public NullableStruct? Start { get; set; }
}

public struct NullableStruct
{
    public string? Padding1 { get; set; }
    public float? Value { get; set; }
    public string? Padding2 { get; set; }
}

public class ThrottledStream : Stream
{
    private readonly byte[] _data;
    private readonly int _chunkSize;
    private int _position;

    public ThrottledStream(byte[] data, int chunkSize)
    {
        _data = data;
        _chunkSize = chunkSize;
    }

    public override int Read(byte[] buffer, int offset, int count)
    {
        int toRead = Math.Min(Math.Min(count, _chunkSize), _data.Length - _position);
        if (toRead <= 0) return 0;
        Array.Copy(_data, _position, buffer, offset, toRead);
        _position += toRead;
        return toRead;
    }

    public override Task<int> ReadAsync(byte[] buffer, int offset, int count, CancellationToken ct)
        => Task.FromResult(Read(buffer, offset, count));

    public override ValueTask<int> ReadAsync(Memory<byte> buffer, CancellationToken ct = default)
    {
        int toRead = Math.Min(Math.Min(buffer.Length, _chunkSize), _data.Length - _position);
        if (toRead <= 0) return new ValueTask<int>(0);
        _data.AsSpan(_position, toRead).CopyTo(buffer.Span);
        _position += toRead;
        return new ValueTask<int>(toRead);
    }

    public override bool CanRead => true;
    public override bool CanSeek => false;
    public override bool CanWrite => false;
    public override long Length => _data.Length;
    public override long Position { get => _position; set => throw new NotSupportedException(); }
    public override void Flush() { }
    public override long Seek(long offset, SeekOrigin origin) => throw new NotSupportedException();
    public override void SetLength(long value) => throw new NotSupportedException();
    public override void Write(byte[] buffer, int offset, int count) => throw new NotSupportedException();
}
```

</details>

**Output on .NET 9.0.312:**
```
=== Test 1: Simplest repro (DeserializeAsync, DefaultBufferSize=1) ===
  Sync:  OK (2 items)
  Async (buffer=1): FAILED
=== Test 2: DeserializeAsyncEnumerable via throttled stream ===
  AsyncEnumerable (chunk=   1): FAILED
  AsyncEnumerable (chunk=   7): FAILED
  AsyncEnumerable (chunk=  64): FAILED
  AsyncEnumerable (chunk= 256): OK (500 items)
  AsyncEnumerable (chunk=4096): OK (500 items)
=== Test 3: DeserializeAsync at default 16KB buffer boundary ===
  Failures scanning 16384-200..16384+200: 2/400
```

**Workarounds:**
- Change the nullable struct property (`NullableStruct? Start`) to use a class instead of a struct, or
- Make the struct property non-nullable (`NullableStruct Start`)

**Comment by eiriktsarpalis** [comment]
Closing as duplicate of https://github.com/dotnet/runtime/issues/110450.

**Comment by mip1983** [comment]
> This is a duplicate of [dotnet/runtime#110450](https://github.com/dotnet/runtime/issues/110450) -- a confirmed bug in `System.Text.Json`'s streaming deserialization state machine. When a `Nullable<T>` struct property's JSON object straddles an internal read buffer boundary, `DeserializeAsync` and `DeserializeAsyncEnumerable` throw `JsonException` while synchronous deserialization succeeds.

> **Workarounds:**
> 
> * Change the nullable struct property (`NullableStruct? Start`) to use a class instead of a struct, or
> * Make the struct property non-nullable (`NullableStruct Start`)

Appreciate that, I've re-written some bits from struct to class
