### ISSUE TITLE
HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate failing on AlmaLinux8 in release/8.0 Helix Matrix

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/aspnetcore#57677]
## Failing Test(s)

- Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate(fin: True)

## Error Message

```text
System.TimeoutException : The operation has timed out.
```

## Stacktrace

<details>

```text
2024-09-03T09:50:12.1869722Z [xUnit.net 00:01:15.52]       System.TimeoutException : The operation has timed out.
2024-09-03T09:50:12.1870833Z [xUnit.net 00:01:15.52]       Stack Trace:
2024-09-03T09:50:12.1871044Z [xUnit.net 00:01:15.53]         /_/src/Shared/TaskExtensions.cs(123,0): at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber)
2024-09-03T09:50:12.1871221Z [xUnit.net 00:01:15.53]         /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs(699,0): at Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate(Boolean fin)
2024-09-03T09:50:12.1874668Z [xUnit.net 00:01:15.53]         /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs(703,0): at Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate(Boolean fin)
2024-09-03T09:50:12.1875198Z [xUnit.net 00:01:15.53]         --- End of stack trace from previous location ---
2024-09-03T09:50:12.1875393Z [xUnit.net 00:01:15.53]       Output:
2024-09-03T09:50:12.1875893Z [xUnit.net 00:01:15.53]         | [0.001s] TestLifetime Information: Starting test HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate-True at 2024-09-03T09:49:35
2024-09-03T09:50:12.1876221Z [xUnit.net 00:01:15.53]         | [0.011s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting starting
2024-09-03T09:50:12.1876601Z [xUnit.net 00:01:15.53]         | [0.013s] Microsoft.Hosting.Lifetime Information: Now listening on: https://127.0.0.1:46867
2024-09-03T09:50:12.1876799Z [xUnit.net 00:01:15.53]         | [0.013s] Microsoft.AspNetCore.Hosting.Diagnostics Debug: Loaded hosting startup assembly Sockets.FunctionalTests
2024-09-03T09:50:12.1914890Z [xUnit.net 00:01:15.53]         | [0.014s] Microsoft.Hosting.Lifetime Information: Application started. Press Ctrl+C to shut down.
2024-09-03T09:50:12.1953339Z [xUnit.net 00:01:15.53]         | [0.014s] Microsoft.Hosting.Lifetime Information: Hosting environment: Production
```
</details>

## Logs

<details>

```text
2024-09-03T09:50:12.1869722Z [xUnit.net 00:01:15.52]       System.TimeoutException : The operation has timed out.
2024-09-03T09:50:12.1870833Z [xUnit.net 00:01:15.52]       Stack Trace:
2024-09-03T09:50:12.1871044Z [xUnit.net 00:01:15.53]         /_/src/Shared/TaskExtensions.cs(123,0): at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber)
2024-09-03T09:50:12.1871221Z [xUnit.net 00:01:15.53]         /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs(699,0): at Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate(Boolean fin)
2024-09-03T09:50:12.1874668Z [xUnit.net 00:01:15.53]         /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs(703,0): at Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate(Boolean fin)
2024-09-03T09:50:12.1875198Z [xUnit.net 00:01:15.53]         --- End of stack trace from previous location ---
2024-09-03T09:50:12.1875393Z [xUnit.net 00:01:15.53]       Output:
2024-09-03T09:50:12.1875893Z [xUnit.net 00:01:15.53]         | [0.001s] TestLifetime Information: Starting test HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate-True at 2024-09-03T09:49:35
2024-09-03T09:50:12.1876221Z [xUnit.net 00:01:15.53]         | [0.011s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting starting
2024-09-03T09:50:12.1876601Z [xUnit.net 00:01:15.53]         | [0.013s] Microsoft.Hosting.Lifetime Information: Now listening on: https://127.0.0.1:46867
2024-09-03T09:50:12.1876799Z [xUnit.net 00:01:15.53]         | [0.013s] Microsoft.AspNetCore.Hosting.Diagnostics Debug: Loaded hosting startup assembly Sockets.FunctionalTests
2024-09-03T09:50:12.1914890Z [xUnit.net 00:01:15.53]         | [0.014s] Microsoft.Hosting.Lifetime Information: Application started. Press Ctrl+C to shut down.
2024-09-03T09:50:12.1953339Z [xUnit.net 00:01:15.53]         | [0.014s] Microsoft.Hosting.Lifetime Information: Hosting environment: Production
2024-09-03T09:50:12.1961003Z [xUnit.net 00:01:15.52]     Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate(fin: True) [FAIL]
2024-09-03T09:50:12.1970560Z [xUnit.net 00:01:15.53]         | [0.014s] Microsoft.Hosting.Lifetime Information: Content root path: /root/helix/work/workitem/e/
2024-09-03T09:50:12.1979971Z [xUnit.net 00:01:15.53]         | [0.014s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting started
2024-09-03T09:50:12.1993715Z [xUnit.net 00:01:15.53]         | [0.014s] Microsoft.AspNetCore.Server.Kestrel Debug: TestServer is listening on port 46867
2024-09-03T09:50:12.2007207Z [xUnit.net 00:01:15.53]         | [0.739s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HN6BVMH4KF6C" accepted.
2024-09-03T09:50:12.2154096Z [xUnit.net 00:01:15.54]         | [0.752s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HN6BVMH4KF6C" started.
2024-09-03T09:50:12.2154344Z [xUnit.net 00:01:15.54]         | [0.760s] Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware Debug: Connection 0HN6BVMH4KF6C established using the following protocol: Tls13
2024-09-03T09:50:12.2154368Z [xUnit.net 00:01:15.54]         | [0.760s] Microsoft.AspNetCore.Hosting.Diagnostics Information: Request starting HTTP/1.1 GET https:/// - - -
2024-09-03T09:50:12.2154680Z [xUnit.net 00:01:15.54]         | [7.014s] Microsoft.AspNetCore.Server.Kestrel.BadRequests Debug: Connection id "0HN6BVMH4KF6C", Request id "0HN6BVMH4KF6C:00000001": the connection was closed because the response was not read by the client at the specified minimum data rate.
2024-09-03T09:50:12.2155211Z [xUnit.net 00:01:15.54]         | [7.014s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HN6BVMH4KF6C" sending FIN because: "The connection was timed out by the server because the response was not read by the client at the specified minimum data rate."
2024-09-03T09:50:12.2155301Z [xUnit.net 00:01:15.54]         | [7.014s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HN6BVMH4KF6C" disconnecting.
2024-09-03T09:50:12.2155319Z [xUnit.net 00:01:15.54]         | [7.039s] Microsoft.AspNetCore.Hosting.Diagnostics Information: Request finished HTTP/1.1 GET https:/// - 200 268435456 - 6278.5624ms
2024-09-03T09:50:12.2155337Z [xUnit.net 00:01:15.54]         | [7.040s] Microsoft.AspNetCore.Server.Kestrel.BadRequests Debug: Connection id "0HN6BVMH4KF6C" request processing ended abnormally.
2024-09-03T09:50:12.2155353Z [xUnit.net 00:01:15.54]         | System.IO.IOException: The read operation failed, see inner exception.
2024-09-03T09:50:12.2155369Z [xUnit.net 00:01:15.54]         |  ---> Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was timed out by the server because the response was not read by the client at the specified minimum data rate.
2024-09-03T09:50:12.2155399Z [xUnit.net 00:01:15.54]         |    at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
2024-09-03T09:50:12.2185179Z [xUnit.net 00:01:15.54]         |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.DuplexPipeStream.ReadAsyncInternal(Memory`1 destination, CancellationToken cancellationToken) in /_/src/Shared/ServerInfrastructure/DuplexPipeStream.cs:line 121
2024-09-03T09:50:12.2185333Z [xUnit.net 00:01:15.54]         |    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
2024-09-03T09:50:12.2185354Z [xUnit.net 00:01:15.55]         |    at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
2024-09-03T09:50:12.2295304Z [xUnit.net 00:01:15.55]         |    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
2024-09-03T09:50:12.2295473Z [xUnit.net 00:01:15.55]         |    at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
2024-09-03T09:50:12.2295495Z [xUnit.net 00:01:15.55]         |    --- End of inner exception stack trace ---
2024-09-03T09:50:12.2295514Z [xUnit.net 00:01:15.55]         |    at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
2024-09-03T09:50:12.2295533Z [xUnit.net 00:01:15.55]         |    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
2024-09-03T09:50:12.2295602Z [xUnit.net 00:01:15.55]         |    at System.IO.Pipelines.StreamPipeReader.<ReadInternalAsync>g__Core|40_0(StreamPipeReader reader, Nullable`1 minimumSize, CancellationTokenSource tokenSource, CancellationToken cancellationToken)
2024-09-03T09:50:12.2329572Z [xUnit.net 00:01:15.55]         |    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
2024-09-03T09:50:12.2329708Z [xUnit.net 00:01:15.55]         |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application) in /_/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs:line 649
2024-09-03T09:50:12.2344295Z [xUnit.net 00:01:15.55]         |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application) in /_/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs:line 576
2024-09-03T09:50:12.2344457Z [xUnit.net 00:01:15.55]         | [7.042s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HN6BVMH4KF6C" stopped.
2024-09-03T09:50:12.2354109Z [xUnit.net 00:01:15.55]         | [37.042s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting stopping
2024-09-03T09:50:12.2361916Z [xUnit.net 00:01:15.55]         | [37.042s] Microsoft.Hosting.Lifetime Information: Application is shutting down...
2024-09-03T09:50:12.2370245Z [xUnit.net 00:01:15.55]         | [37.043s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting stopped
2024-09-03T09:50:12.2378024Z [xUnit.net 00:01:15.55]         | [37.045s] Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests Error: Test threw an exception.
2024-09-03T09:50:12.2386027Z [xUnit.net 00:01:15.55]         | System.TimeoutException: The operation has timed out.
2024-09-03T09:50:12.2408536Z [xUnit.net 00:01:15.55]         |    at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 123
2024-09-03T09:50:12.2408667Z [xUnit.net 00:01:15.55]         |    at Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate(Boolean fin) in /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs:line 699
2024-09-03T09:50:12.2411534Z [xUnit.net 00:01:15.55]         |    at Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate(Boolean fin) in /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs:line 703
2024-09-03T09:50:12.2425414Z [xUnit.net 00:01:15.55]         |    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 264
2024-09-03T09:50:12.2428456Z [xUnit.net 00:01:15.55]         | --- End of stack trace from previous location ---
2024-09-03T09:50:12.2438236Z [xUnit.net 00:01:15.56]         |    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
2024-09-03T09:50:12.2446535Z [xUnit.net 00:01:15.56]         |    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
2024-09-03T09:50:12.2454492Z [xUnit.net 00:01:15.56]         | [37.046s] TestLifetime Information: Finished test HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate-True in 37.044869s
2024-09-03T09:50:12.2472166Z   Failed Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate(fin: True) [37 s]
2024-09-03T09:50:12.2472283Z   Error Message:
2024-09-03T09:50:12.2472305Z    System.TimeoutException : The operation has timed out.
2024-09-03T09:50:12.2472325Z   Stack Trace:
2024-09-03T09:50:12.2472343Z      at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 123
2024-09-03T09:50:12.2472363Z    at Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate(Boolean fin) in /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs:line 699
2024-09-03T09:50:12.2472399Z    at Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate(Boolean fin) in /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs:line 703
2024-09-03T09:50:12.2472433Z --- End of stack trace from previous location ---
2024-09-03T09:50:12.2478639Z   Standard Output Messages:
2024-09-03T09:50:12.2478755Z  | [0.001s] TestLifetime Information: Starting test HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate-True at 2024-09-03T09:49:35
2024-09-03T09:50:12.2478778Z  | [0.011s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting starting
2024-09-03T09:50:12.2478797Z  | [0.013s] Microsoft.Hosting.Lifetime Information: Now listening on: https://127.0.0.1:46867
2024-09-03T09:50:12.2478816Z  | [0.013s] Microsoft.AspNetCore.Hosting.Diagnostics Debug: Loaded hosting startup assembly Sockets.FunctionalTests
2024-09-03T09:50:12.2478835Z  | [0.014s] Microsoft.Hosting.Lifetime Information: Application started. Press Ctrl+C to shut down.
2024-09-03T09:50:12.2478854Z  | [0.014s] Microsoft.Hosting.Lifetime Information: Hosting environment: Production
2024-09-03T09:50:12.2478873Z  | [0.014s] Microsoft.Hosting.Lifetime Information: Content root path: /root/helix/work/workitem/e/
2024-09-03T09:50:12.2478891Z  | [0.014s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting started
2024-09-03T09:50:12.2478910Z  | [0.014s] Microsoft.AspNetCore.Server.Kestrel Debug: TestServer is listening on port 46867
2024-09-03T09:50:12.2478929Z  | [0.739s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HN6BVMH4KF6C" accepted.
2024-09-03T09:50:12.2479032Z  | [0.752s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HN6BVMH4KF6C" started.
2024-09-03T09:50:12.2479153Z  | [0.760s] Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware Debug: Connection 0HN6BVMH4KF6C established using the following protocol: Tls13
2024-09-03T09:50:12.2479174Z  | [0.760s] Microsoft.AspNetCore.Hosting.Diagnostics Information: Request starting HTTP/1.1 GET https:/// - - -
2024-09-03T09:50:12.2479192Z  | [7.014s] Microsoft.AspNetCore.Server.Kestrel.BadRequests Debug: Connection id "0HN6BVMH4KF6C", Request id "0HN6BVMH4KF6C:00000001": the connection was closed because the response was not read by the client at the specified minimum data rate.
2024-09-03T09:50:12.2479232Z  | [7.014s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HN6BVMH4KF6C" sending FIN because: "The connection was timed out by the server because the response was not read by the client at the specified minimum data rate."
2024-09-03T09:50:12.2479267Z  | [7.014s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HN6BVMH4KF6C" disconnecting.
2024-09-03T09:50:12.2479352Z  | [7.039s] Microsoft.AspNetCore.Hosting.Diagnostics Information: Request finished HTTP/1.1 GET https:/// - 200 268435456 - 6278.5624ms
2024-09-03T09:50:12.2479410Z  | [7.040s] Microsoft.AspNetCore.Server.Kestrel.BadRequests Debug: Connection id "0HN6BVMH4KF6C" request processing ended abnormally.
2024-09-03T09:50:12.2479429Z  | System.IO.IOException: The read operation failed, see inner exception.
2024-09-03T09:50:12.2479448Z  |  ---> Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was timed out by the server because the response was not read by the client at the specified minimum data rate.
2024-09-03T09:50:12.2479468Z  |    at System.IO.Pipelines.Pipe.ReadAsync(CancellationToken token)
2024-09-03T09:50:12.2479486Z  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.DuplexPipeStream.ReadAsyncInternal(Memory`1 destination, CancellationToken cancellationToken) in /_/src/Shared/ServerInfrastructure/DuplexPipeStream.cs:line 121
2024-09-03T09:50:12.2479505Z  |    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
2024-09-03T09:50:12.2483979Z  |    at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
2024-09-03T09:50:12.2484103Z  |    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
2024-09-03T09:50:12.2484125Z  |    at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
2024-09-03T09:50:12.2484146Z  |    --- End of inner exception stack trace ---
2024-09-03T09:50:12.2484165Z  |    at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
2024-09-03T09:50:12.2484184Z  |    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
2024-09-03T09:50:12.2484203Z  |    at System.IO.Pipelines.StreamPipeReader.<ReadInternalAsync>g__Core|40_0(StreamPipeReader reader, Nullable`1 minimumSize, CancellationTokenSource tokenSource, CancellationToken cancellationToken)
2024-09-03T09:50:12.2484589Z  |    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
2024-09-03T09:50:12.2484945Z  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application) in /_/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs:line 649
2024-09-03T09:50:12.2484973Z  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application) in /_/src/Servers/Kestrel/Core/src/Internal/Http/HttpProtocol.cs:line 576
2024-09-03T09:50:12.2484993Z  | [7.042s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HN6BVMH4KF6C" stopped.
2024-09-03T09:50:12.2485013Z  | [37.042s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting stopping
2024-09-03T09:50:12.2485033Z  | [37.042s] Microsoft.Hosting.Lifetime Information: Application is shutting down...
2024-09-03T09:50:12.2485051Z  | [37.043s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting stopped
2024-09-03T09:50:12.2485071Z  | [37.045s] Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests Error: Test threw an exception.
2024-09-03T09:50:12.2485178Z  | System.TimeoutException: The operation has timed out.
2024-09-03T09:50:12.2485201Z  |    at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 123
2024-09-03T09:50:12.2485220Z  |    at Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate(Boolean fin) in /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs:line 699
2024-09-03T09:50:12.2485256Z  |    at Microsoft.AspNetCore.Server.Kestrel.Sockets.FunctionalTests.ResponseTests.HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate(Boolean fin) in /_/src/Servers/Kestrel/test/FunctionalTests/ResponseTests.cs:line 703
2024-09-03T09:50:12.2486505Z  |    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 264
2024-09-03T09:50:12.2486532Z  | --- End of stack trace from previous location ---
2024-09-03T09:50:12.2486550Z  |    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
2024-09-03T09:50:12.2486629Z  |    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
2024-09-03T09:50:12.2486649Z  | [37.046s] TestLifetime Information: Finished test HttpsConnectionClosedWhenResponseDoesNotSatisfyMinimumDataRate-True in 37.044869s
2024-09-03T09:50:12.2486669Z 
2024-09-03T09:50:12.2486702Z 
```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=796090&view=results

**Comment by wtgodbe** [comment]
CC @adityamandaleeka this test has failed a few times in the past week in the 8.0 Helix Matrix

**Comment by amcasey** [comment]
It's quarantined in 9.0: https://github.com/dotnet/aspnetcore/issues/49974
