### ISSUE TITLE
Blazor nested [SupplyParameterFromQuery] causes exception on navigation

### ISSUE THREAD

**Issue by azaher1126** [dotnet/aspnetcore#57746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

An exception is thrown and logged in the console when Navigation.NavigateTo causes a component with a [SupplyParameterFromQuery] property to be displayed.

### Expected Behavior

No exception should be thrown.

### Steps To Reproduce

I've created a very barebones reproduction project with the issue, it can be found here: https://github.com/azaher1126/BlazorNestedSupplyFromQueryIssue

Steps to reproduce:
1. Create two Blazor components both with a property marked with [SupplyParameterFromQuery]
2. Make one of the components a child of the second one only if it's query parameter is a certain value
3. Add the parent component to a page
4. Create a button use the NavigationManager with onclick to show the nested component

### Exceptions (if any)

Uncaught (in promise) Error: Microsoft.AspNetCore.Components.LocationChangeException: An exception occurred while dispatching a location changed event.
 ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator[[Microsoft.AspNetCore.Components.Rendering.ComponentState, Microsoft.AspNetCore.Components, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.AspNetCore.Components.Routing.SupplyParameterFromQueryValueProvider.OnLocationChanged(Object sender, LocationChangedEventArgs args)
   at Microsoft.AspNetCore.Components.NavigationManager.NotifyLocationChanged(Boolean isInterceptedLink)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Components.NavigationManager.NotifyLocationChanged(Boolean isInterceptedLink)
   at Microsoft.AspNetCore.Components.WebAssembly.Services.WebAssemblyNavigationManager.SetLocation(String uri, String state, Boolean isInterceptedLink)
   at Microsoft.AspNetCore.Components.WebAssembly.Infrastructure.JSInteropMethods.NotifyLocationChanged(String uri, String state, Boolean isInterceptedLink)
   at System.Object.InvokeStub_JSInteropMethods.NotifyLocationChanged(Object , Span`1 )
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
--- End of stack trace from previous location ---
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.InvokeSynchronously(JSRuntime jsRuntime, DotNetInvocationInfo& callInfo, IDotNetObjectReference objectReference, String argsJson)
   at Microsoft.JSInterop.Infrastructure.DotNetDispatcher.BeginInvokeDotNet(JSRuntime jsRuntime, DotNetInvocationInfo invocationInfo, String argsJson)
    at b.endInvokeDotNetFromJS (https://localhost:7266/_framework/blazor.webassembly.js:1:3136)
    at Object.gn [as endInvokeDotNetFromJS] (https://localhost:7266/_framework/blazor.webassembly.js:1:58943)
    at https://localhost:7266/_framework/dotnet.runtime.8.0.6.42ud5saqge.js:3:178364
    at Tl (https://localhost:7266/_framework/dotnet.runtime.8.0.6.42ud5saqge.js:3:179198)
    at wasm://wasm/00b2193a:wasm-function[349]:0x1fab4
    at wasm://wasm/00b2193a:wasm-function[245]:0x1bf5b
    at wasm://wasm/00b2193a:wasm-function[238]:0xf142
    at wasm://wasm/00b2193a:wasm-function[272]:0x1d179
    at wasm://wasm/00b2193a:wasm-function[3185]:0xe8673
    at wasm://wasm/00b2193a:wasm-function[2505]:0xbe3c9

### .NET Version

8.0.302

### Anything else?

I did a little debugging and found that the OnLocationChanged handler responsible for supplying parameters from the query enumerates a hashset of subscribers which gets updated at the same time with the new subscriber (nested component) causing the exception.

This doesn't seem to cause any catastrophic issues.

**Comment by javiercn** [comment]
@azaher1126 thanks for contacting us.

@MackinnonBuck do you think this can be another incarnation of https://github.com/dotnet/aspnetcore/issues/56741?

**Comment by azaher1126** [comment]
To avoid the issue being closed due to the "Needs: Author Feedback" label I decided to check out the issue the issue you have linked (#56741).
From the time I spent debugging this issue and the description of #56741 it seems like they are very similar.

**Comment by mkArtakMSFT** [comment]
This is indeed the same issue as https://github.com/dotnet/aspnetcore/issues/56741

**Comment by DNF-SaS** [comment]
Same problem here

**Comment by paule96** [comment]
@mkArtakMSFT is this still an issue with Blazor WASM on dotnet 9?
Has far as I see the Pullrequest of #56741 It should be in the RC1 of dotnet 9. Did something breaked the logic added their again?

**Comment by mkArtakMSFT** [comment]
@lewing, @javiercn  FYI

**Comment by kijanawoodard** [comment]
I just stumbled on this as well. It seems all the related issues are marked as resolved.
Should we open a new one or let one of these get reopened?

**Comment by JamieWhitlam** [comment]
I have just hit this issue. The sample project still errors on .NET 9.0.300.

**Comment by ColinBradley** [comment]
Still getting this in .NET 9.0.302, ASP 9.00.725.31702

**Comment by ben-farrant** [comment]
@mkArtakMSFT This shouldn't be closed. The related item #56741 required a fix to [CascadingValueSource.NotifyChangedAsync()](https://github.com/dotnet/aspnetcore/blob/da2e7e169aa20f3c9d52c5f839f1965a1c083a9b/src/Components/Components/src/CascadingValueSource.cs#L85), whereas this issue requires the same fix to be done for [SupplyParameterFromQueryValueProvider.OnLocationChanged()](https://github.com/dotnet/aspnetcore/blob/da2e7e169aa20f3c9d52c5f839f1965a1c083a9b/src/Components/Components/src/Routing/SupplyParameterFromQueryValueProvider.cs#L124). There could also be other events that need this same fix.
