### ISSUE TITLE
[Android]MessagePack Exception:The transport does not support the 'Binary' transfer

### ISSUE THREAD

**Issue by BaY1251** [dotnet/aspnetcore#57802]
### Description
I am using SignalR to connect to a server, but there is an exception when using MessagePack.

Comment out line 15,'Exception' no longer pops up

Exception.Message:
Unable to connect to the server with any of the available transports. (ServerSentEvents failed: The transport does not support the 'Binary' transfer format.) (LongPolling failed: Error while copying content to a stream.)

### Steps to Reproduce

1. Open /Issue24710/Issue24710.sln
2. deployment the project
3. Click "Click me"
4. Then an 'exception' message will appear

### Link to public reproduction project repository

https://github.com/BaY1251/MauiDebug.git

### Version with bug

8.0.82 SR8.2

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android7.1

### Relevant log output

StackTrace:
```
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
```

**Comment by BrennanConroy** [comment]
https://stackoverflow.com/questions/74792022/why-does-the-android-version-of-my-maui-app-not-have-internet-access

**Comment by BaY1251** [comment]
> @BaY1251 I didn't see the 'MessagePack Exception:The transport does not support the 'Binary' transfer' but show Connection failure when use VS 17.12.0. Preview2.0 Maui 8.0.82 ![image](https://private-user-images.githubusercontent.com/128687574/366378614-259b2166-ef95-4dc2-b1c1-106e2efb6ee9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMDE3MzMsIm5iZiI6MTcyNjEwMTQzMywicGF0aCI6Ii8xMjg2ODc1NzQvMzY2Mzc4NjE0LTI1OWIyMTY2LWVmOTUtNGRjMi1iMWMxLTEwNmUyZWZiNmVlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQwMDM3MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NGEzODEwNmRjYWVjNjVkNTllMGVlMmM2ODcxMDM5YTMyYjdjMmMxYWYxMGZmNWY2ZjhiM2E4ZWM5NzIwNmQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nML6laOa-kqScaMGE_IJNKtwWHy7Mx0m7n7uqpXDucA)

A server with Message Pack enabled is required. Can someone help you build a simple server?

**Comment by BaY1251** [comment]
The last working version is VS-17.8.0
