### ISSUE TITLE
AuthorizationMessageHandler 添加token到请求头异常

### ISSUE THREAD

**Issue by wgh2019** [dotnet/aspnetcore#57868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

我根据官网的例子(https://learn.microsoft.com/zh-cn/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-7.0) 中 《配置 AuthorizationMessageHandler》，出现异常
```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The inner handler has not been assigned.
System.InvalidOperationException: The inner handler has not been assigned.
```
代码如下
```
service.AddScoped<IAccessTokenProvider, CustomerAccessTokenProvider>();
builder.Services.AddScoped<AuthorizationMessageHandler>();
builder.Services.AddScoped(sp => new HttpClient(
    sp.GetRequiredService<AuthorizationMessageHandler>()
    .ConfigureHandler(
        authorizedUrls: new[]
        {
            "http://localhost:5075/api/users",
            "http://localhost:5075/api/products",
        }
    ))
{
    BaseAddress = new Uri("http://localhost:5075/api/")
});
```
请问是不是不支持直接使用AuthorizationMessageHandler
如果可以用的 能否给一个完整的demo 用以参考

### Exceptions (if any)

```
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The inner handler has not been assigned.
System.InvalidOperationException: The inner handler has not been assigned.
   at System.Net.Http.DelegatingHandler.SetOperationStarted()
   at System.Net.Http.DelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.AuthorizationMessageHandler.<>n__0(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Components.WebAssembly.Authentication.AuthorizationMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.<GetFromJsonAsyncCore>d__29`1[[System.String, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at BlazorApp_empty1.Client.Pages.Index.OnInitializedAsync() in E:\Users\wgh\source\repos\BlazorApp-empty1\BlazorApp-empty1\Client\Pages\Index.razor:line 14
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
```

### .NET Version

7.0

**Comment by javiercn** [comment]
@wgh2019 thanks for contacting us.

.NET 7.0 is out of support, so as per our support policy we won't look at this issue. We first recommend you update to .NET 8.0 as a first step.

**Comment by wgh2019** [comment]
I have the same issue with .NET 8
