### ISSUE TITLE
FromQueryAttribute + argument type with a Action property will cause serious memory leaks

### ISSUE THREAD

**Issue by funwaywang** [dotnet/aspnetcore#57892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hello everyone, I believe I have encountered a very rare but serious bug: When developing an Asp.net WebApi program, if you use the **FromQueryAttribute** to describe an API action, and the parameter type contains a property of the Action type, simply running the project will exhaust all the memory on the local machine within a few seconds. This happens even without calling the WebApi; just running it in Visual Studio (by pressing F5) is enough.

### Expected Behavior

Does not cause incorrect memory consumption

### Steps To Reproduce

Open Visual Studio 2022, Create a new Asp.net Core WebAPI project, and just edit the default controller like this:
`
[ApiController]
[Route("[controller]")]
public class WeatherForecastController : ControllerBase
{
    public class MyArgs
    {
        public string? Name { get; set; } // string is ok

        public Action? DoSomething { get; set; } // BAD here! 

        //public Action[]? MoreActions { get; set; } // Action array is OK
    }

    [HttpGet("SayHello")]
    public string Get([FromQuery] MyArgs args) // [FromQuery] must be used, otherwise everything will be fine. 
    {
        return "Hello";
    }
}
`
[WebApplication1.zip](https://github.com/user-attachments/files/17015208/WebApplication1.zip)

There are a few key points to keep in mind when reproducing this issue:

1. The project must be run in debug mode within Visual Studio; running it via the command line with `dotnet run` will not cause the memory leak. 
2. The FromQuery attribute must be used in conjunction with a property of the Action type. However, using Action[] (an array of Action) will not trigger this issue.
3. My computer runs on Windows 10 with an AMD Ryzen 5 5600X CPU, and it seems that my other Intel-based computer does not have this issue.
4. Restarting the computer does not resolve this issue.

### Exceptions (if any)

My computer has 32GB of memory, but running this program for just a few seconds completely exhausts it. If I don't take a screenshot quickly, the computer will become unresponsive due to the memory being depleted.

### .NET Version

8.0.400

### Anything else?

<img width="737" alt="Screenshot 2024-09-16 225214" src="https://github.com/user-attachments/assets/7c2cbf82-1ed5-459d-be0d-3a17a5247ab4">
<img width="621" alt="Screenshot 2024-09-16 222848" src="https://github.com/user-attachments/assets/be7b6ac8-0917-44c6-bbd2-8ee5d1b68685">

`
.NET SDK:
 Version:           8.0.400
 Commit:            36fe6dda56
 Workload version:  8.0.400-manifests.6c274a57
 MSBuild version:   17.11.3+0c8610977

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.400\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [aspire]
   Installation Source: VS 17.11.35303.130
   Manifest Version:    8.1.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.1.0\WorkloadManifest.json
   Install Type:        FileBased

Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5

.NET SDKs installed:
  6.0.410 [C:\Program Files\dotnet\sdk]
  8.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

`

**Comment by sami-daniel** [comment]
I won't know exactly where to solve the problem because I'm new to the repository, but apparently, when ModelBinder tries to process the Action type, due to its complex structure, ModelBinder ends up being unable to resolve the type and ends up draining memory. But between you and me, why do you need an Action property to be mapped? Naturally, ModelBinder would not be able to map the structure. I'm sorry that I can't solve this.

**Comment by martincostello** [comment]
Adding an attribute to the model property to exclude it from binding should allow you to work around the issue.

**Comment by sami-daniel** [comment]
I did this and it gave exactly the problem described in the Issue. I have 16 from memory and 13 of them are gone. I was unable to identify the source of the problem as I do not really know the structure of the framework. I started contributing recently.

**Comment by funwaywang** [comment]
> I won't know exactly where to solve the problem as I'm new to the repository, but apparently, when ModelBinder tries to process the Action type, due to its complex structure, ModelBinder ends up being unable to resolve the type and ends up draining memory. But between you and me, why do you need an Action property to be mapped? Naturally, ModelBinder would not be able to map the structure. When I tested it with the dotnet run command and it still drains memory. I'm sorry I can't resolve this.

Indeed, I don't need to extract a property from the JSON, as it is initially guaranteed to be null. The reason I defined it was for the convenience of later operations. Now, I've changed the property to a Set method to avoid this issue. Additionally, adding the [JsonIgnore] attribute to the property doesn't prevent the problem.

The most dangerous part of this issue is that it's hard to detect and locate. Imagine you have a project with hundreds of types, and just running the program can lead to system memory exhaustion without requiring any user action. Even if we carefully check every type, there are bound to be oversights. And if we miss just one, the entire system could be compromised.

I suggest either providing compile-time checks or throwing an exception at runtime, otherwise, it is very dangerous.

**Comment by sami-daniel** [comment]
I understand your point and it is very valid. The Action is actually a delegate and the delegate itself has a complex structure, so maybe the binder gets stuck there. If you want to make the binder ignore a property of your type, decorate it with [BindNerver], then it will ignore it and you can preserve your Action for the future.

 It is still valid to check and fix the bug or simply cancel the binding for this structure. It can be quite dangerous. I'll try to do more research to see if I can identify where this occurs. THX!

**Comment by captainsafia** [comment]
@sami-daniel Your intuition was right here and I agree with your recommendation that if @funwaywang doesn't intend to actually bind `Action` from the query string (which is admittedly very strange) then using `[BindNever]` is the correct approach.

Let me know if you have any questions as you investigation this issue!

**Comment by sami-daniel** [comment]
Hi @captainsafia.

I don't have a specific direction to follow to resolve the issue. As I said, I believe the problem lies where Binder tries to resolve the binding type, be it `FromQuery`, `FromBody`, etc. and then tries to match the names of the properties of the object received as a parameter in the endpoint with the values that are actually present in the query. As I have no knowledge of the ModelBinder structure as a whole, I was unable to have a starting point or identify any module where the problem could be, so I believe that if I know where ModelBinder matches the object with the request values, it should already be a great starting point for me. Thank you very much! I really want to be able to contribute to the framework!

**Comment by sami-daniel** [comment]
After some checks and tests, I realized that I was aiming in another direction. The issue is not directly associated with ModelBinder.

When we create a project and run it by going to the swagger index.html page we start to have the problems described, the application starts to consume all the RAM memory available. However, if we simply make a request to the endpoint that has any type of delegate, we get:
```
System.InvalidOperationException: Could not create an instance of type 'System.Action'. Model bound complex types must not be abstract or value types and must have a parameterless constructor. Record types must have a single primary constructor. Alternatively, give the 'a' parameter a non-null default value.
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ComplexObjectModelBinder.CreateModel(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ComplexObjectModelBinder.BindModelCoreAsync(ModelBindingContext bindingContext, Int32 propertyData)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value, Object container)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

HEADERS
=======
Accept: */*
Connection: keep-alive
Host: localhost:7215
User-Agent: PostmanRuntime/7.37.3
Accept-Encoding: gzip, deflate, br
Postman-Token: 6b93a341-2620-418e-8418-671f1f185b50
```

If we make a request to the index.html swagger page, but without executing it in the browser directly (using Postman for example) we actually receive the swagger page without any problem:
![image](https://github.com/user-attachments/assets/3c0c311e-0966-427c-a0a2-1127351e2f02)

In the investigations by ModelBinder it can be noticed that it is already by default 'protected' from trying to convert the data of a class to an abstract type such as delegates, as we can see in the triggered exception.

Since the problem apparently only occurs when we run the swagger page in the browser, perhaps the problem occurs when the swagger tries to effectively render the endpoint with the attribute and then crashes, perhaps by not being able to render the endpoints on the page or something like that.
