### ISSUE TITLE
The connection was aborted by the application. At HttpRequestStream.ReadAsyncInternal

### ISSUE THREAD

**Issue by StuBedore** [dotnet/aspnetcore#57950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

My test project started throwing this exception on every POST request. I've removed every middleware/service to a barebone project and still the exception persists.

### Expected Behavior

Process the POST request and hand it over to the controller.

### POST Request
```
POST /v1/auth/token HTTP/1.1
Host: localhost:5073
Content-Type: application/json
Content-Length: 2

{}
```

### Exceptions (if any)

```
fail: TestProject.Api.Dashboard.Framework.Middleware.ExceptionMiddleware[0]
      An unexpected error occurred.
      Microsoft.AspNetCore.Connections.ConnectionAbortedException: The connection was aborted by the application.
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsyncInternal(Memory`1 destination, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
         at System.Text.Json.Serialization.ReadBufferState.ReadFromStreamAsync(Stream utf8Json, CancellationToken cancellationToken, Boolean fillBuffer)
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
         at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsObjectAsync(Stream utf8Json, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
         at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
         at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
         at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value, Object container)
         at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at TestProject.Api.Dashboard.Framework.Middleware.ExceptionMiddleware.InvokeAsync(HttpContext context) in C:\work\repos\TestProject\TestProject-server\TestProject\TestProject.Api.Dashboard\Framework\Middleware\ExceptionMiddleware.cs:line 21
```

### .NET Version

8.0.300

### Anything else?

Asp.Net Core Web API

**Comment by StuBedore** [comment]
I am an idiot. Forgot to remove an Abort call.
