### ISSUE TITLE
Quarantine MapOpenApi_HandlesConcurrentRequests

### ISSUE THREAD

**Issue by amcasey** [dotnet/aspnetcore#58128]
## Failing Test(s)

- Microsoft.AspNetCore.OpenApi.Tests.Integration.OpenApiDocumentConcurrentRequestTests.MapOpenApi_HandlesConcurrentRequests

## Error Message

```text
Assert.Equal() Failure: Values differ
Expected: OK
Actual:   InternalServerError
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.OpenApi.Tests.Integration.OpenApiDocumentConcurrentRequestTests.<>c__DisplayClass2_0.<<MapOpenApi_HandlesConcurrentRequests>b__0>d.MoveNext() in D:\a\_work\1\s\src\OpenApi\test\Microsoft.AspNetCore.OpenApi.Tests\Integration\OpenApiDocumentConcurrentRequestTests.cs:line 23
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__49`1.<<ForAsync>b__49_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.OpenApi.Tests.Integration.OpenApiDocumentConcurrentRequestTests.MapOpenApi_HandlesConcurrentRequests() in D:\a\_work\1\s\src\OpenApi\test\Microsoft.AspNetCore.OpenApi.Tests\Integration\OpenApiDocumentConcurrentRequestTests.cs:line 18
--- End of stack trace from previous location ---
```
</details>

## Logs

<details>

```text
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.IndexOutOfRangeException: Index was outside the bounds of the array.
         at System.Collections.Generic.OrderedDictionary`2.Enumerator.MoveNext()
         at System.Text.Json.Nodes.JsonObject.WriteTo(Utf8JsonWriter writer, JsonSerializerOptions options)
         at System.Text.Json.JsonSerializer.ReadFromNode[TValue](JsonNode node, JsonTypeInfo`1 jsonTypeInfo)
         at Microsoft.AspNetCore.OpenApi.OpenApiSchemaService.GetOrCreateSchemaAsync(Type type, IServiceProvider scopedServiceProvider, IOpenApiSchemaTransformer[] schemaTransformers, ApiParameterDescription parameterDescription, Boolean captureSchemaByRef, CancellationToken cancellationToken) in /_/src/OpenApi/src/Services/Schemas/OpenApiSchemaService.cs:line 141
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetParametersAsync(ApiDescription description, IServiceProvider scopedServiceProvider, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken) in /_/src/OpenApi/src/Services/OpenApiDocumentService.cs:line 420
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOperationAsync(ApiDescription description, HashSet`1 capturedTags, IServiceProvider scopedServiceProvider, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken) in /_/src/OpenApi/src/Services/OpenApiDocumentService.cs:line 284
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOperationsAsync(IGrouping`2 descriptions, HashSet`1 capturedTags, IServiceProvider scopedServiceProvider, IOpenApiOperationTransformer[] operationTransformers, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken) in /_/src/OpenApi/src/Services/OpenApiDocumentService.cs:line 245
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOpenApiPathsAsync(HashSet`1 capturedTags, IServiceProvider scopedServiceProvider, IOpenApiOperationTransformer[] operationTransformers, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken) in /_/src/OpenApi/src/Services/OpenApiDocumentService.cs:line 229
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOpenApiDocumentAsync(IServiceProvider scopedServiceProvider, CancellationToken cancellationToken) in /_/src/OpenApi/src/Services/OpenApiDocumentService.cs:line 73
         at Microsoft.AspNetCore.Builder.OpenApiEndpointRouteBuilderExtensions.<>c__DisplayClass0_0.<<MapOpenApi>b__0>d.MoveNext() in /_/src/OpenApi/src/Extensions/OpenApiEndpointRouteBuilderExtensions.cs:line 46
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Http.Generated.<GeneratedRouteBuilderExtensions_g>F56B68D2B55B5B7B373BA2E4796D897848BC0F04A969B1AF6260183E8B9E0BAF2__GeneratedRouteBuilderExtensionsCore.<>c__DisplayClass2_0.<<MapGet0>g__RequestHandler|5>d.MoveNext() in /_/artifacts/obj/Microsoft.AspNetCore.OpenApi/Release/net9.0/Microsoft.AspNetCore.Http.RequestDelegateGenerator/Microsoft.AspNetCore.Http.RequestDelegateGenerator.RequestDelegateGenerator/GeneratedRouteBuilderExtensions.g.cs:line 124
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) in /_/src/Security/Authorization/Policy/src/AuthorizationMiddleware.cs:line 149
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) in /_/src/Security/Authentication/Core/src/AuthenticationMiddleware.cs:line 75
         at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatcher|10_0(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task`1 matcherTask) in /_/src/Http/Routing/src/EndpointRoutingMiddleware.cs:line 90
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context) in /_/src/Middleware/Diagnostics/src/DeveloperExceptionPage/DeveloperExceptionPageMiddlewareImpl.cs:line 114
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.IndexOutOfRangeException: Index was outside the bounds of the array.
         at System.Collections.Generic.OrderedDictionary`2.Enumerator.MoveNext()
         at System.Text.Json.Nodes.JsonObject.WriteTo(Utf8JsonWriter writer, JsonSerializerOptions options)
         at System.Text.Json.JsonSerializer.ReadFromNode[TValue](JsonNode node, JsonTypeInfo`1 jsonTypeInfo)
         at Microsoft.AspNetCore.OpenApi.OpenApiSchemaService.GetOrCreateSchemaAsync(Type type, IServiceProvider scopedServiceProvider, IOpenApiSchemaTransformer[] schemaTransformers, ApiParameterDescription parameterDescription, Boolean captureSchemaByRef, CancellationToken cancellationToken) in /_/src/OpenApi/src/Services/Schemas/OpenApiSchemaService.cs:line 141
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetParametersAsync(ApiDescription description, IServiceProvider scopedServiceProvider, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken) in /_/src/OpenApi/src/Services/OpenApiDocumentService.cs:line 420
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOperationAsync(ApiDescription description, HashSet`1 capturedTags, IServiceProvider scopedServiceProvider, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken) in /_/src/OpenApi/src/Services/OpenApiDocumentService.cs:line 284
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOperationsAsync(IGrouping`2 descriptions, HashSet`1 capturedTags, IServiceProvider scopedServiceProvider, IOpenApiOperationTransformer[] operationTransformers, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken) in /_/src/OpenApi/src/Services/OpenApiDocumentService.cs:line 245
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOpenApiPathsAsync(HashSet`1 capturedTags, IServiceProvider scopedServiceProvider, IOpenApiOperationTransformer[] operationTransformers, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken) in /_/src/OpenApi/src/Services/OpenApiDocumentService.cs:line 229
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOpenApiDocumentAsync(IServiceProvider scopedServiceProvider, CancellationToken cancellationToken) in /_/src/OpenApi/src/Services/OpenApiDocumentService.cs:line 73
         at Microsoft.AspNetCore.Builder.OpenApiEndpointRouteBuilderExtensions.<>c__DisplayClass0_0.<<MapOpenApi>b__0>d.MoveNext() in /_/src/OpenApi/src/Extensions/OpenApiEndpointRouteBuilderExtensions.cs:line 46
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Http.Generated.<GeneratedRouteBuilderExtensions_g>F56B68D2B55B5B7B373BA2E4796D897848BC0F04A969B1AF6260183E8B9E0BAF2__GeneratedRouteBuilderExtensionsCore.<>c__DisplayClass2_0.<<MapGet0>g__RequestHandler|5>d.MoveNext() in /_/artifacts/obj/Microsoft.AspNetCore.OpenApi/Release/net9.0/Microsoft.AspNetCore.Http.RequestDelegateGenerator/Microsoft.AspNetCore.Http.RequestDelegateGenerator.RequestDelegateGenerator/GeneratedRouteBuilderExtensions.g.cs:line 124
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) in /_/src/Security/Authorization/Policy/src/AuthorizationMiddleware.cs:line 149
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) in /_/src/Security/Authentication/Core/src/AuthenticationMiddleware.cs:line 75
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context) in /_/src/Middleware/Diagnostics/src/DeveloperExceptionPage/DeveloperExceptionPageMiddlewareImpl.cs:line 114
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.IndexOutOfRangeException: Index was outside the bounds of the array.
         at System.Collections.Generic.OrderedDictionary`2.Enumerator.MoveNext()
         at System.Text.Json.Nodes.JsonObject.WriteTo(Utf8JsonWriter writer, JsonSerializerOptions options)
         at System.Text.Json.JsonSerializer.ReadFromNode[TValue](JsonNode node, JsonTypeInfo`1 jsonTypeInfo)
         at Microsoft.AspNetCore.OpenApi.OpenApiSchemaService.GetOrCreateSchemaAsync(Type type, IServiceProvider scopedServiceProvider, IOpenApiSchemaTransformer[] schemaTransformers, ApiParameterDescription parameterDescription, Boolean captureSchemaByRef, CancellationToken cancellationToken) in /_/src/OpenApi/src/Services/Schemas/OpenApiSchemaService.cs:line 141
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetParametersAsync(ApiDescription description, IServiceProvider scopedServiceProvider, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken) in /_/src/OpenApi/src/Services/OpenApiDocumentService.cs:line 420
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOperationAsync(ApiDescription description, HashSet`1 capturedTags, IServiceProvider scopedServiceProvider, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken) in /_/src/OpenApi/src/Services/OpenApiDocumentService.cs:line 284
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOperationsAsync(IGrouping`2 descriptions, HashSet`1 capturedTags, IServiceProvider scopedServiceProvider, IOpenApiOperationTransformer[] operationTransformers, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken) in /_/src/OpenApi/src/Services/OpenApiDocumentService.cs:line 245
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOpenApiPathsAsync(HashSet`1 capturedTags, IServiceProvider scopedServiceProvider, IOpenApiOperationTransformer[] operationTransformers, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken) in /_/src/OpenApi/src/Services/OpenApiDocumentService.cs:line 229
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOpenApiDocumentAsync(IServiceProvider scopedServiceProvider, CancellationToken cancellationToken) in /_/src/OpenApi/src/Services/OpenApiDocumentService.cs:line 73
         at Microsoft.AspNetCore.Builder.OpenApiEndpointRouteBuilderExtensions.<>c__DisplayClass0_0.<<MapOpenApi>b__0>d.MoveNext() in /_/src/OpenApi/src/Extensions/OpenApiEndpointRouteBuilderExtensions.cs:line 46
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Http.Generated.<GeneratedRouteBuilderExtensions_g>F56B68D2B55B5B7B373BA2E4796D897848BC0F04A969B1AF6260183E8B9E0BAF2__GeneratedRouteBuilderExtensionsCore.<>c__DisplayClass2_0.<<MapGet0>g__RequestHandler|5>d.MoveNext() in /_/artifacts/obj/Microsoft.AspNetCore.OpenApi/Release/net9.0/Microsoft.AspNetCore.Http.RequestDelegateGenerator/Microsoft.AspNetCore.Http.RequestDelegateGenerator.RequestDelegateGenerator/GeneratedRouteBuilderExtensions.g.cs:line 124
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) in /_/src/Security/Authorization/Policy/src/AuthorizationMiddleware.cs:line 149
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) in /_/src/Security/Authentication/Core/src/AuthenticationMiddleware.cs:line 75
         at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatcher|10_0(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task`1 matcherTask) in /_/src/Http/Routing/src/EndpointRoutingMiddleware.cs:line 90
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context) in /_/src/Middleware/Diagnostics/src/DeveloperExceptionPage/DeveloperExceptionPageMiddlewareImpl.cs:line 114
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.IndexOutOfRangeException: Index was outside the bounds of the array.
         at System.Collections.Generic.OrderedDictionary`2.Enumerator.MoveNext()
         at System.Text.Json.Nodes.JsonObject.WriteTo(Utf8JsonWriter writer, JsonSerializerOptions options)
         at System.Text.Json.JsonSerializer.ReadFromNode[TValue](JsonNode node, JsonTypeInfo`1 jsonTypeInfo)
         at Microsoft.AspNetCore.OpenApi.OpenApiSchemaService.GetOrCreateSchemaAsync(Type type, IServiceProvider scopedServiceProvider, IOpenApiSchemaTransformer[] schemaTransformers, ApiParameterDescription parameterDescription, Boolean captureSchemaByRef, CancellationToken cancellationToken) in /_/src/OpenApi/src/Services/Schemas/OpenApiSchemaService.cs:line 141
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetParametersAsync(ApiDescription description, IServiceProvider scopedServiceProvider, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken) in /_/src/OpenApi/src/Services/OpenApiDocumentService.cs:line 420
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOperationAsync(ApiDescription description, HashSet`1 capturedTags, IServiceProvider scopedServiceProvider, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken) in /_/src/OpenApi/src/Services/OpenApiDocumentService.cs:line 284
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOperationsAsync(IGrouping`2 descriptions, HashSet`1 capturedTags, IServiceProvider scopedServiceProvider, IOpenApiOperationTransformer[] operationTransformers, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken) in /_/src/OpenApi/src/Services/OpenApiDocumentService.cs:line 245
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOpenApiPathsAsync(HashSet`1 capturedTags, IServiceProvider scopedServiceProvider, IOpenApiOperationTransformer[] operationTransformers, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken) in /_/src/OpenApi/src/Services/OpenApiDocumentService.cs:line 229
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOpenApiDocumentAsync(IServiceProvider scopedServiceProvider, CancellationToken cancellationToken) in /_/src/OpenApi/src/Services/OpenApiDocumentService.cs:line 73
         at Microsoft.AspNetCore.Builder.OpenApiEndpointRouteBuilderExtensions.<>c__DisplayClass0_0.<<MapOpenApi>b__0>d.MoveNext() in /_/src/OpenApi/src/Extensions/OpenApiEndpointRouteBuilderExtensions.cs:line 46
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Http.Generated.<GeneratedRouteBuilderExtensions_g>F56B68D2B55B5B7B373BA2E4796D897848BC0F04A969B1AF6260183E8B9E0BAF2__GeneratedRouteBuilderExtensionsCore.<>c__DisplayClass2_0.<<MapGet0>g__RequestHandler|5>d.MoveNext() in /_/artifacts/obj/Microsoft.AspNetCore.OpenApi/Release/net9.0/Microsoft.AspNetCore.Http.RequestDelegateGenerator/Microsoft.AspNetCore.Http.RequestDelegateGenerator.RequestDelegateGenerator/GeneratedRouteBuilderExtensions.g.cs:line 124
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) in /_/src/Security/Authorization/Policy/src/AuthorizationMiddleware.cs:line 149
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) in /_/src/Security/Authentication/Core/src/AuthenticationMiddleware.cs:line 75
         at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatcher|10_0(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task`1 matcherTask) in /_/src/Http/Routing/src/EndpointRoutingMiddleware.cs:line 90
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context) in /_/src/Middleware/Diagnostics/src/DeveloperExceptionPage/DeveloperExceptionPageMiddlewareImpl.cs:line 114
[xUnit.net 00:00:04.18]     Microsoft.AspNetCore.OpenApi.Tests.Integration.OpenApiDocumentConcurrentRequestTests.MapOpenApi_HandlesConcurrentRequests [FAIL]
[xUnit.net 00:00:04.18]       Assert.Equal() Failure: Values differ
[xUnit.net 00:00:04.18]       Expected: OK
[xUnit.net 00:00:04.18]       Actual:   InternalServerError
[xUnit.net 00:00:04.18]       Stack Trace:
[xUnit.net 00:00:04.18]         D:\a\_work\1\s\src\OpenApi\test\Microsoft.AspNetCore.OpenApi.Tests\Integration\OpenApiDocumentConcurrentRequestTests.cs(23,0): at Microsoft.AspNetCore.OpenApi.Tests.Integration.OpenApiDocumentConcurrentRequestTests.<>c__DisplayClass2_0.<<MapOpenApi_HandlesConcurrentRequests>b__0>d.MoveNext()
[xUnit.net 00:00:04.18]         --- End of stack trace from previous location ---
[xUnit.net 00:00:04.19]            at System.Threading.Tasks.Parallel.<>c__49`1.<<ForAsync>b__49_0>d.MoveNext()
[xUnit.net 00:00:04.19]         --- End of stack trace from previous location ---
[xUnit.net 00:00:04.19]         D:\a\_work\1\s\src\OpenApi\test\Microsoft.AspNetCore.OpenApi.Tests\Integration\OpenApiDocumentConcurrentRequestTests.cs(18,0): at Microsoft.AspNetCore.OpenApi.Tests.Integration.OpenApiDocumentConcurrentRequestTests.MapOpenApi_HandlesConcurrentRequests()
2024-09-27T00:39:24.7380710Z [xUnit.net 00:00:04.19]         --- End of stack trace from previous location ---
```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=819881

**Comment by igor-toporet** [comment]
We are experiencing this issue. Would you happen to have any insights on how to work around it?

I don't know if it matters, but we have caching enabled; I'll disable it and see if it's still reproducing.

**Comment by TwentyFourMinutes** [comment]
We are experiencing this issue as well - at least the stack trace matches for this case. For us it occurs during startup.

**Comment by xC0dex** [comment]
Could you share on which machine/OS it occurs? I thought that I fixed it with this PR https://github.com/dotnet/aspnetcore/pull/57972 (This PR introduced the failing test). I'm unable to reproduce the issue on my machine..

**Comment by TwentyFourMinutes** [comment]
@xC0dex I am currently under Windows 11 24H2 26100.4061 - though I am not quite certain yet that I am on the correct issue - My issue is not necessarily related to concurrency. Anyhow I am trying to figure what causes the issue... I'll respond again once I figured.

**Comment by TwentyFourMinutes** [comment]
@xC0dex I got it working by removing Min/Max Length attributes as well as Nullable Collections that caused a very similar stack trace. Sorry for the inconvenience, and thanks for responding that quickly.  

Have a nice day
