### ISSUE TITLE
Azure B2C login issue with Blazor Webassembly

### ISSUE THREAD

**Issue by setin1219** [dotnet/aspnetcore#58223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi Team,

We are facing an issue with Azure B2C where our application uses B2C to login user to our application.
When we launch our blazor webassembly application, it redirects to login screen and user is able to logged in successfully.
However, when we open a new tab and try to open same application, it redirects to login screen again but failed to continue and returns the login-failed response.
When we retry, it ask for login credentials again although user is already logged in one of the active session but it doesnt honor that.
I have similar application which uses Azure AD instead of B2C and it works seamlessly there without need to enter credentials.
Please see if anyone faced similar issue and is there any resolution.

### Expected Behavior

Earlier we used to successfully login in multiple tabs automatically without asking user to enter credentials again.

### Exceptions (if any)

Below is the exception I could capture in localhost.

  Message=
  Source=
  StackTrace:
    at t [as constructor] (https://localhost:7066/_content/Microsoft.Authentication.WebAssembly.Msal/AuthenticationService.js:2:13274)
    at new t (https://localhost:7066/_content/Microsoft.Authentication.WebAssembly.Msal/AuthenticationService.js:2:113673)
    at e.validateServerAuthorizationCodeResponse (https://localhost:7066/_content/Microsoft.Authentication.WebAssembly.Msal/AuthenticationService.js:2:128599)
    at t.handleFragmentResponse (https://localhost:7066/_content/Microsoft.Authentication.WebAssembly.Msal/AuthenticationService.js:2:136698)
    at t.<anonymous> (https://localhost:7066/_content/Microsoft.Authentication.WebAssembly.Msal/AuthenticationService.js:2:212506)
    at https://localhost:7066/_content/Microsoft.Authentication.WebAssembly.Msal/AuthenticationService.js:2:3621
    at Object.next (https://localhost:7066/_content/Microsoft.Authentication.WebAssembly.Msal/AuthenticationService.js:2:3726)
    at https://localhost:7066/_content/Microsoft.Authentication.WebAssembly.Msal/AuthenticationService.js:2:2663
    at new Promise (<anonymous>)
    at c (https://localhost:7066/_content/Microsoft.Authentication.WebAssembly.Msal/AuthenticationService.js:2:2408)

### .NET Version

8.0.400

**Comment by setin1219** [comment]
Closing the issue since I cannot share the repro code of our company azure b2c setup
