### ISSUE TITLE
[Blazor WASM] .NET 8.0.10 breaks WASM debugging

### ISSUE THREAD

**Issue by omni-htg** [dotnet/aspnetcore#58313]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Upon upgrading a Blazor WASM Standalone .NET 8 project to 8.0.10 (including all related NuGet packages), Debugging on Visual Studio 2022 17.11.5 breaks during runtime with the following:
```
MONO_WASM: The version of dotnet.runtime.js is different from the version of dotnet.js!
MONO_WASM: The version of dotnet.native.js is different from the version of dotnet.js!
MONO_WASM: mono_wasm_load_runtime () failed TypeError: u.isDebuggingSupported is not a function
    at Vl (c:\Users\<PATH_TO_SOLUTION>\_framework\https:\raw.githubusercontent.com\dotnet\runtime\81cabf2857a01351e5ab578947c7403a5b128ad1\src\mono\wasm\runtime\startup.ts:575:28)
    at c:\Users\<PATH_TO_SOLUTION>\_framework\https:\raw.githubusercontent.com\dotnet\runtime\81cabf2857a01351e5ab578947c7403a5b128ad1\src\mono\wasm\runtime\startup.ts:551:5
    at https://localhost:7112/_framework/dotnet.runtime.8.0.10.39apnb5yx8.js:3:207329 {stack: 'TypeError: u.isDebuggingSupported is not a fu…/dotnet.runtime.8.0.10.39apnb5yx8.js:3:207329', message: 'u.isDebuggingSupported is not a function'}

MONO_WASM: TypeError: u.isDebuggingSupported is not a function
    at Vl (https://localhost:7112/_framework/dotnet.runtime.8.0.10.39apnb5yx8.js:3:217167)
    at https://localhost:7112/_framework/dotnet.runtime.8.0.10.39apnb5yx8.js:3:206677
    at https://localhost:7112/_framework/dotnet.runtime.8.0.10.39apnb5yx8.js:3:207329
TypeError: u.isDebuggingSupported is not a function
Stack trace:
 >  at Vl (https://localhost:7112/_framework/dotnet.runtime.8.0.10.39apnb5yx8.js:3:217167)
 >    at https://localhost:7112/_framework/dotnet.runtime.8.0.10.39apnb5yx8.js:3:206677
 >    at https://localhost:7112/_framework/dotnet.runtime.8.0.10.39apnb5yx8.js:3:207329
```

Previous issues related to that version difference message recommended clearing out all `bin` and `obj` folder -- which I have tried with no success.

One of our deployments in Azure is currently running without issues on the latest Docker image, so I highly believe this is purely a Debugging issue.
I do have to warn that one of our users reported the same errors on their Chrome / Edge console (I couldn't replicate myself, unfortunately), for which clearing out their browser cache made it work.

It seems that there might be some sort of incompatibility somewhere that "breaks" instead of "upgrading" the .NET libraries.
If this is the case, where just by navigating to the site without a "clean cache" it breaks, then it's a bigger regression than I expected.
Hopefully it's not!

Thanks for your time.

### Expected Behavior

On VS 2022, debugging should just work flawlessly.
On deployed site, users should NOT be expected to clear their cache to navigate to the site.

### Steps To Reproduce

From a Standalone Blazor WASM project starting on 8.0.8, compile and debug. Then, upgrade to 8.0.10 and try again.

On a deployed site, deploy the 8.0.8 version and navigate to it. Then, deploy the 8.0.10 version and with the same browser with the site cached, navigate to the site.

### Exceptions (if any)

Clearing cache, or navigating with a "fresh" browser works fine.

### .NET Version

8.0.403

### Anything else?

.NET 8.0.10 / 8.0.403
Visual Studio 2022 17.11.5

`dotnet --info`:
.NET SDK:
 Version:           8.0.403
 Commit:            c64aa40a71
 Workload version:  8.0.400-manifests.e99c892e
 MSBuild version:   17.11.9+a69bbaaf5

**Comment by omni-htg** [comment]
Tagging related issues, including those in /dotnet/runtime:
- https://github.com/dotnet/aspnetcore/issues/54285
- https://github.com/dotnet/runtime/issues/102272

Apologies if the report should be handled on the /dotnet/runtime side of things, please indicate so.

**Comment by javiercn** [comment]
@maraf is this the same issue we had a while back?

**Comment by javiercn** [comment]
@omni-htg you can try adding a `Cache: no-cache` to the response for the JS files or do a hard refresh to see if the issue goes away.

**Comment by omni-htg** [comment]
Hey @javiercn, here's some updates on what I could find:
- Locally on my VS 2022 I have tried switching the port assigned so that it gets treated as a "different site", and that worked!
- When working with the original port, I cannot for the life of me find where or how to clear whatever is cached under that original port / site, as I have manually cleared everything that Chrome offers under "Delete browsing data..." and have pulled our project from scratch to start fresh.
- For the deployed site, in our testing environment, every team member that have had visited the site before (and as such had it cached) experienced the same regression, and needed to have their cache cleared.

This last item is the most critical for us, as we cannot realistically have our customers manually clearing their cache just to be able to visit the site.
What is weird to me is that we have gone through multiple 8.0.x versions without any issues -- so I hope you understand how worrisome it is for next versions.

Apologies for the rant-y tone -- now for the provided proposal:
You're suggesting that I add a `Cache-Control: no-cache` response header to the JS files being served, correct?
Let me check it out :)

**Comment by audacity76** [comment]
I have the same issue. But I think it is related to the update to Visual Studio 2022 17.11.5!

**Comment by os-dmi** [comment]
It is not a Visual Studio issue! I have the same problem using Rider (Ubuntu 20.04).
The issue appeared with version 8.0.10

**Comment by audacity76** [comment]
I'm using the SDK Version 8.0.403 now and my app works with packages 8.0.8 and 8.0.10.

**Comment by KirovAir** [comment]
On our IIS servers I've fixed the problem using the no-cache directive which seems to fix the issues for our end-users, but it's far from ideal.
```
<!-- Fix for https://github.com/dotnet/aspnetcore/issues/58313 -->
<location path="_framework/dotnet.js">
  <system.webServer>
	<httpProtocol>
	  <customHeaders>
		<add name="Cache-Control" value="no-cache" />
	  </customHeaders>
	</httpProtocol>
  </system.webServer>
</location>
```

**Comment by hunglng** [comment]
In our Azure Static Web App, adding following config to `staticwebapp.config.json` seems to fix the issue for Edge and Chrome but not Firefox. We did not do any update in our local development environment. Seems that the agent in Azure DevOps pipeline has the update.
```
    {
      "route": "/_framework/dotnet.js",
      "headers": {
        "cache-control": "no-cache"
      }
    },
```

**Comment by donmezhakan** [comment]
Hi everybody.
I did everything that was said and done here, but it still didn't work. Downgrading to Visual Studio 2022 17.11.4 fixed the problem.
My project structure is App.Server and App.Client(BlazorWebAssembly) netsdk 8.0.400 and dll references are 8.0.10, but when I downgrade, debug works. The problem seems to be caused by Visual Studio. I hope they fix it in the next patch.

**Comment by dwe-alan** [comment]
@mkArtakMSFT  I am sorry, but I don't think this can wait until .NET 10 planning. This really needs to be fixed ASAP or at least Blazor developers need to have some sure-fire cache-busting hints to work around it. Website users should not need to know that in order to avoid a blank screen, it's essential to Ctrl+Refresh their browser.

**Comment by lukashummel** [comment]
Hi everyone,
experienced the same issue. As a workaround, the only thing that fixed it for me was specifying the runtime explicitely to a version older than 8.0.10.
Add <RuntimeFrameworkVersion>8.0.8</RuntimeFrameworkVersion> in your csproj file and (at least for me) everything works fine. 
Microsoft should deliver a fix for that.

**Comment by lartusi** [comment]
.NET 10 Planning???
So more than 1 year to have this fixed!

I have a lot of people all around the world stuck in the load screen just because i've updated the framework
This is not acceptable.

**Comment by pedroramirezs279** [comment]
I experience the same issue after Visual Studio 2022 was updated yesterday to the latest version. Rolling back to the previous version of Visual Studio solved the problem for me.
Thank you for the time in resolving this issue.

**Comment by pwelter34** [comment]
I don't believe this is a cache issue.  I've purged the cache, hard reloaded, tried on different machines and that doesn't fix the issue.

**Comment by dwe-alan** [comment]
@pwelter34  What does your Developer Tools / Console Tab show when you reload?

**Comment by pwelter34** [comment]
> [@pwelter34](https://github.com/pwelter34) What does your Developer Tools / Console Tab show when you reload?

![Image](https://github.com/user-attachments/assets/d64e099a-3961-4099-87c2-29cd2e665848)

**Comment by miklosa** [comment]
Dear AspNetCore team,
I have experienced the same issue.

![Image](https://github.com/user-attachments/assets/93dd5292-20ce-4f7c-9b95-4525c7ad514f)

After inserting the line indicated in the following image into the Client project’s csproj file, the error disappeared on my side.

![Image](https://github.com/user-attachments/assets/e571e1bd-36cc-45ae-9855-fc828957702a)

**Comment by daveg1466** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Describe the bug
> Upon upgrading a Blazor WASM Standalone .NET 8 project to 8.0.10 (including all related NuGet packages), Debugging on Visual Studio 2022 17.11.5 or navigating to a Deployed site with previous version cache breaks during runtime with the following:
> 
> ```
> MONO_WASM: The version of dotnet.runtime.js is different from the version of dotnet.js!
> MONO_WASM: The version of dotnet.native.js is different from the version of dotnet.js!
> MONO_WASM: mono_wasm_load_runtime () failed TypeError: u.isDebuggingSupported is not a function
>     at Vl (c:\Users\<PATH_TO_SOLUTION>\_framework\https:\raw.githubusercontent.com\dotnet\runtime\81cabf2857a01351e5ab578947c7403a5b128ad1\src\mono\wasm\runtime\startup.ts:575:28)
>     at c:\Users\<PATH_TO_SOLUTION>\_framework\https:\raw.githubusercontent.com\dotnet\runtime\81cabf2857a01351e5ab578947c7403a5b128ad1\src\mono\wasm\runtime\startup.ts:551:5
>     at https://localhost:7112/_framework/dotnet.runtime.8.0.10.39apnb5yx8.js:3:207329 {stack: 'TypeError: u.isDebuggingSupported is not a fu…/dotnet.runtime.8.0.10.39apnb5yx8.js:3:207329', message: 'u.isDebuggingSupported is not a function'}
> 
> MONO_WASM: TypeError: u.isDebuggingSupported is not a function
>     at Vl (https://localhost:7112/_framework/dotnet.runtime.8.0.10.39apnb5yx8.js:3:217167)
>     at https://localhost:7112/_framework/dotnet.runtime.8.0.10.39apnb5yx8.js:3:206677
>     at https://localhost:7112/_framework/dotnet.runtime.8.0.10.39apnb5yx8.js:3:207329
> TypeError: u.isDebuggingSupported is not a function
> Stack trace:
>  >  at Vl (https://localhost:7112/_framework/dotnet.runtime.8.0.10.39apnb5yx8.js:3:217167)
>  >    at https://localhost:7112/_framework/dotnet.runtime.8.0.10.39apnb5yx8.js:3:206677
>  >    at https://localhost:7112/_framework/dotnet.runtime.8.0.10.39apnb5yx8.js:3:207329
> ```
> 
> Previous issues related to that version difference message recommended clearing out all `bin` and `obj` folder -- which I have tried with no success.
> 
> One of our users reported the same errors on their Chrome / Edge console, for which clearing out their browser cache made it work. It seems that there might be some sort of incompatibility somewhere that "breaks" instead of "upgrading" the .NET libraries -- so it looks like the issue comes from the moving from one version to the next, not 8.0.10 by itself.
> 
> If this is the case, where just by navigating to the site without a "clean cache" it breaks, then it's a bigger regression than I expected. Hopefully it's not!
> 
> Thanks for your time.
> 
> ### Expected Behavior
> On VS 2022, debugging should just work flawlessly. On deployed site, users should NOT be expected to clear their cache to navigate to the site.
> 
> ### Steps To Reproduce
> From a Standalone Blazor WASM project starting on 8.0.8, compile and debug. Then, upgrade to 8.0.10 and try again.
> 
> On a deployed site, deploy the 8.0.8 version and navigate to it. Then, deploy the 8.0.10 version and with the same browser with the site cached, navigate to the site.
> 
> ### Exceptions (if any)
> Clearing cache, or navigating with a "fresh" browser works fine.
> 
> ### .NET Version
> 8.0.403
> 
> ### Anything else?
> .NET 8.0.10 / 8.0.403 Visual Studio 2022 17.11.5
> 
> `dotnet --info`: .NET SDK: Version: 8.0.403 Commit: c64aa40a71 Workload version: 8.0.400-manifests.e99c892e MSBuild version: 17.11.9+a69bbaaf5

**Comment by BurkusCat** [comment]
I did a small text/content update to my website which. My pipeline uses "https://dot.net/v1/dotnet-install.sh" to install .NET 8.0 so it presumably downloaded the latest version so I got this error. I've rolled back to an August build of the site to fix the issue.

**Comment by JeroMiya** [comment]
Also experiencing this issue. I can also verify that the issue is NOT cache related. We were already setting the cache header of all .js files to `no-cache` prior to experiencing this issue and clearing the cache completely does not make the error go away.

We were able to fix the error by reverting back all the NuGet packages to version `8.0.8` and adding the `<RuntimeFrameworkVersion>8.0.8</RuntimeFrameworkVersion>` element to the .Client project.

**Comment by pingu2k4** [comment]
Same issue here. Also appears not to be a cache issue. No amount of cache busting / clearing my cache etc could resolve this - only reverting to an older runtime framework version, as others have pointed out above.

**Comment by BusterIT** [comment]
I was not able to downgrade or throwing the 8.0.10 js framework references completely out of my build pipeline.

So I did this hack and it solved the issues at customers side:

![Image](https://github.com/user-attachments/assets/fc0aca57-ab21-4d52-a986-0f65e87de8d5)

**Comment by ElliottBrand** [comment]
I also ran into issues after upgrading Visual Studio / .Net and saw the same errors about `u.IsDebuggingSupported` for the WASM client.  After clearing all caches didn't work, I deleted all the `obj` and `bin` folders, then redeployed and that resolved it.

**Comment by Rauce** [comment]
I'm seeing the same issue since upping to .NET 8.0.10.

Local development works fine – it only happens for me in Production (which deploys via a GitHub Actions process that pull the repo into a fresh container, builds from scratch, and publishes).

I'd had to roll back to 8.0.8 for now.

**Comment by Brascal** [comment]
> I also ran into issues after upgrading Visual Studio / .Net and saw the same errors about `u.IsDebuggingSupported` for the WASM client. After clearing all caches didn't work, I deleted all the `obj` and `bin` folders, then redeployed and that resolved it.

This resolved it for me. However it's worth clarifying that it's the _client_ project that needs to have its `obj` and `bin` folders deleted, not just the server, if you're running a hosted WASM setup.

**Comment by polajenko** [comment]
> Hi everybody. I did everything that was said and done here, but it still didn't work. Downgrading to Visual Studio 2022 17.11.4 fixed the problem. My project structure is App.Server and App.Client(BlazorWebAssembly) netsdk 8.0.400 and dll references are 8.0.10, but when I downgrade, debug works. The problem seems to be caused by Visual Studio. I hope they fix it in the next patch.

How did you downgrade?

**Comment by polajenko** [comment]
In our case it was Cloudflare that was caching the old files. Once we purged then the site started working.

**Comment by donmezhakan** [comment]
Hi everybody.
Visual Studio 17.12.0 is out. .Net 8.0.11 is also out. I solved this problem by doing
```c#
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
<DebugType>embedded</DebugType>
</PropertyGroup>
``` 
like this. Now I can debug.

**Comment by programmaticsoftware** [comment]
> [@omni-htg](https://github.com/omni-htg) you can try adding a `Cache: no-cache` to the response for the JS files or do a hard refresh to see if the issue goes away.

"hard refresh" solved it for me

**Comment by lanedirt** [comment]
> I encountered the same issue after upgrading to .NET 9! It was resolved after I deleted the browser's cache storage. I also noticed that the cache storage keys for .NET 8 and .NET 9 are different.

I have exactly the same issue after upgrading my Blazor WASM app from .NET 8 to .NET 9. This is quite a critical issue IMO. All users that previously visited my app now get greeted with an error and it results in the app getting stuck loading:

> An unhandled error has occurred. [Reload](#)

If the user clicks the button to (hard) refresh the page it works again, so it's not a persistent issue. But in my opinion this is very bad user experience for an out-of-the-box configuration of Blazor WASM.

**Comment by mono-wallace** [comment]
> I encountered the same issue after upgrading to .NET 9! It was resolved after I deleted the browser's cache storage. I also noticed that the cache storage keys for .NET 8 and .NET 9 are different.
> 
> ![Image](https://github.com/user-attachments/assets/0afb1281-7526-43ac-a3fc-3214d9592962)

I have run into the exact same issue when updating our test environments. Warnings and errors in the browser console are the same, and I could resolve it by disabling the browser cache. Of course, I can not really ask customers to disable the browser cache on first use after the update. So a proper solution to this issue would be appreciated.

**Comment by ericvb** [comment]
We have only internal customers, so the trick of deleting the browser cache for the deployed site was not a real problem, not user friendly, but doable.

One problem that was unresolved, was debugging in Visual Studio 2022. Everytime I got the error "TypeError: u.isDebuggingSupported is not a function" when launching a local debug session using IISExpress.
Deleting the cache in Chrome did not do the trick.
As test I switched to use Edge as browser (first time use of Edge as debug browser, so there should not be a cache problem), and the problem was indeed gone.
So it was definitely a cache problem! But why that didn't work in Chrome with deleting all cache?

Finally I found the solution. When launching a debug session I had 3 Chrome browser instances open, one with the webapis backend and 2 with the gui's: localhost:xxxx end localhost:yyyy
I deleted the cache in the first browser screen localhost:xxxx and I deleted the cache in the second browser screen localhost:yyyy.
After relaunching the debug session, no error anymore!

So somewhere Visual Studio 2022 (or IIS Express?) caches something that is linked to the used port.
I found a related problem about this: https://developercommunity.visualstudio.com/t/Problems-with-Visual-Studio-2022-Debuggi/10327641?page=12&pageSize=15&sort=active&topics=visual+studio+2019+version+16.7
But there wasn't really an explanation of the reason or cause

Hopes that this will help some people :-)

**Comment by ATEEKGIT** [comment]
Started to face exact same issue after upgrade of visual studio to latest version. 

After reading all this thread i was wondering how may such posts should be enough for micrsoft bros to take this stuff serious.

**Comment by kir0riwal** [comment]
This issue is going on from past 2+ months and not one from Microsoft is responding on this .. 

**Javier Calvarro Nelson**  - Since this issue is assignee to you, do you have any SLA to get it resolved and if you could not resolve it the ESCALATE this to higher management.


Do we have to write to Satya Nadela then Microsoft team would respond on this ? Atleast keep all the stakeholders UPDATED with latest what is going on to get this issue RESOLVED.

submitted a question to Microsoft as well which they declared duplicate with existing one -

https://developercommunity.visualstudio.com/t/net-80-Blazor-web-application-dependen/10796757

Similar way @Artak Mkrtchyan [MSFT] declared  above mentioned issue as duplicate and after that no update. WHY microsoft team is NOT responding ? WHY you guys keeping silent on this? Can you redirect us to your Manager or schedule a CALL to discuss on this. Please understand the INTENCITY of this issue impacting thousand of users by now.

https://github.com/github Team - This is still UNRESOLVED. Please provide a solution.

**Comment by kir0riwal** [comment]
> > I encountered the same issue after upgrading to .NET 9! It was resolved after I deleted the browser's cache storage. I also noticed that the cache storage keys for .NET 8 and .NET 9 are different.
> > ![Image](https://github.com/user-attachments/assets/0afb1281-7526-43ac-a3fc-3214d9592962)
> 
> I have run into the exact same issue when updating our test environments. Warnings and errors in the browser console are the same, and I could resolve it by disabling the browser cache. Of course, I can not really ask customers to disable the browser cache on first use after the update. So a proper solution to this issue would be appreciated.


Have you published latest code in Rancher and then while trying to access what is error ?

This issue has nothing to do with Browser cache, it is something to do with Blazor.Web.Assembly file.

**Comment by monsieurvor** [comment]
pls fix

Meanwhile, as a temporary work-around to prevent users having to hard refresh our deployed standalone WASM app, we did the following:
- Set all AspNetCore-related packages to <=8.0.8
- Use docker base image `mcr.microsoft.com/dotnet/sdk:8.0.402`
- Disabled `wasm-tools`, as it seems to pull-in the latest run-time

**Comment by kir0riwal** [comment]
Thanks Monsieurvor for your response,  could you share details about this particular step how to achieve it ?

Meanwhile, as a temporary work-around to prevent users having to hard refresh our deployed standalone WASM app, we did the following:

Set all AspNetCore-related packages to <=8.0.8
Use docker base image mcr.microsoft.com/dotnet/sdk:8.0.402
Disabled wasm-tools workload, as it seems to pull-in the latest run-time  -> How you did it or what is the process or code to disable wasm-tool workload ? Please share.

Appreciate your help on this..!!

**Comment by monsieurvor** [comment]
> l

It was simple as commenting out this line `#RUN dotnet workload install wasm-tools` in our Dockerfile.

It's an optional step, and you might lose some app optimizations, but at least it works, lol.

After deployment, you can verify the runtime version in browser devtools -> Sources -> _framework -> `dotnet.runtime.8.0.8.9z6kkxsnez.js`

**Comment by gmeister99** [comment]
Has anyone resolved the .NET9 upgrade issue (as many have noted above), or are we patiently waiting for 9.0.1 runtime release?

**Comment by ATEEKGIT** [comment]
probably silense of ms guys means alot to understand that core runtime javascript versions are changed and already cached scripts in browser clients will be required to clear in any case and they don't have any tangible solution to this problem in their hand so far. 

though having larger bases of external customers will badly impact for people who are using blazor webassembly.

**Comment by marius-i-marin** [comment]
Here's a **workaround** that worked for me:

    <script src="_framework/blazor.web.js" **autostart="false"**></script>
    <script>
        Blazor.start({ webAssembly: {
            loadBootResource: function (type, name, defaultUri, integrity)
            {
                if ((type == "dotnetjs") && (name == "dotnet.js") && (defaultUri == "_framework/dotnet.js"))
                {
                    defaultUri = "_framework/dotnet.js**?v=1**";
                    return defaultUri;
                }
            }
        } } );
    </script>

**Comment by kir0riwal** [comment]
@marius-i-marin
Marius Marin - did you added this code in "INDEX.CSHTML" ? or could to share where exactly you made this code change in your web application solution ?

**Comment by kir0riwal** [comment]
@javiercn - Since this issue is assigned to you . are you working for MICROSOFT ? and is there any one also working in your team to get this RESOLVED ? 

What SEVERITY Microsoft has acknowledged this issue and could you share your approach to fix this ISSUE?
Why no-one from Microsoft responding , do you have any set SLA for such issue ? or could you share where or whom we need to contact in order to get this issue fixed ? Business is getting IMPACTED due to this unresolved bug.

**Comment by kir0riwal** [comment]
Ok, and could you share exactly how you included in app.razor ?

because i do not have any HTML or Javascript written in my code app.razor file. So wanted to see if you added something explicitly or how you put this code in app.razor file ?
 if possible, Please share your app.razor file ?

**Comment by kir0riwal** [comment]
@marius-i-marin 

one question on this, did you kept this statement in "Index.html" file like this or where do you have this statement ?
<script> src="_framework/blazor.webassembly.js"> </script


or you updated this statement also with autostart = false , like this - 

<script> src="_framework/blazor.webassembly.js" autostart="false"> </script

please share ...

**Comment by neseih** [comment]
You could try another solution:
Might not work if files are already cached.
Add this code before app.UseRouting()
```
// Set up custom content types - associating file extension to MIME type 
var provider = new FileExtensionContentTypeProvider();
 // Add new mappings
 provider.Mappings.Add(".properties", "application/octet-stream");

var options = new StaticFileOptions {     
  // maybe this is not necessary
  ContentTypeProvider = provider,    
  // fix for cached dotnetjs integration check fails. Always ask server about version.     
  OnPrepareResponse = (r) => {                             
    if (r.File.Name.StartsWith("dotnet") && r.File.Name.EndsWith(".js")) {                                    
       r.Context.Response.Headers.Append("cache-control", "max-age=0");                             
    }                        
 }
 };
  app.UseStaticFiles(options);
```

**Comment by ElliottBrand** [comment]
I believe this issue is resolved by one of these two approaches (or both).

1. Delete all the obj & bin folders from your solution, then rebuild and re-deploy if you aren't using a CICD pipeline. If you aren't using a CICD pipeline, you may be publishing some outdated artifacts that could cause problems, or you may even experience issues in local development.
2. I believe Implementing a cache buster should solve the caching issues, but it's important to understand what's happening before just pasting in a change. When a browser loads static resources like JavaScript files or CSS files, it typically caches them based on their URL to speed up subsequent loads. However, since it treats each unique URL as a different resource, when you set a query parameter on the URL to that resource and change it, the browser should reload it. If you look in the Network tab in the browser tools, you'll notice that it's showing a 304 status code ([https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304)) for that file when it's cached and a 200 status code when it reloads with a URL that isn't cached.

`<script src="_framework/blazor.webassembly.js?cb=123456"></script>`

If implementing a cache buster approach like this, you just need to decide how you want to render the unique string in the query parameter. You could simply update it manually with every release, but you'll probably want to do it programmatically. You'll need to decide what works best for your application. Some people set it by their app version (when the app is versioned), some set it by DateTime Ticks, etc.

**Comment by marius-i-marin** [comment]
@ElliottBrand
Implementing the cache buster on **blazor.web.js** doesn't work for me, as the problem is caused by the loading of an old cached version of **dotnet.js**.

@kir0riwal 
Here's my app.razor file:
[App.razor.txt](https://github.com/user-attachments/files/18176966/App.razor.txt)
My project is built from the newer "Blazor Web App" project template, so it uses "_framework/blazor.web.js" (instead of "_framework/blazor.webassembly.js").

**Comment by JeroMiya** [comment]
We are no longer able to reproduce this issue, though likely this is due to all existing caches expiring. We set the cache control header on all outgoing static file middleware served files to no-cache. This is slightly less efficient, but the extra 302 request/response overhead is acceptable as our application is not extremely high volume and there doesn't exist an automatic file hashing mechanism for js modules loaded at runtime (such a mechanism would likely need a source generator to read the content of bundled js modules, compute a hash, and inject the hash into the file name we pass to the JS interop when loading modules - not something in scope for this project).

**Comment by kir0riwal** [comment]
@JeroMiya - could you share how you implemented the cache control header?

I tried with all the way outs mentioned in above notifications, but none of them worked out for us.

**Comment by pauldavis-dwe** [comment]
After many hours of investigation to possible work-arounds I FINALLY have something working! 
NOTE: This works for us because we have an MVC app that loads first and takes users over to the Blazor app.

We removed `<RuntimeFrameworkVersion>8.0.8</RuntimeFrameworkVersion>` from the .csproj file and added the following JavaScript into the MVC app layout CSHTML file:
```
let xhr = new XMLHttpRequest();

xhr.open('GET', '/b/_framework/dotnet.js');

xhr.setRequestHeader('Cache-Control', 'no-cache, no-store, max-age=0');
xhr.setRequestHeader('Expires', 'Thu, 1 Jan 1970 00:00:00 GMT');
xhr.setRequestHeader('Pragma', 'no-cache');

xhr.send();
```

That seems to inform the browser that the cached v8.0.8 dotnet.js file should be deleted as when I then load any Blazor URL the browser correctly requests the v8.0.11 version of the file!

I will add that this should NOT be necessary! The team that removed the `hasDebuggingEnabled` property and added the `isDebuggingSupported` should have considered the fact that it was a BREAKING change and left backwards compatibility.

**Comment by windofny1** [comment]
If you are using asp.core for hosting Blazor Web Assembly, then you can use this code in program.cs asp. core project:

```
app.UseStaticFiles(new StaticFileOptions()
{
    OnPrepareResponse = context =>
    {       
        context.Context.Response.Headers["Clear-Site-Data"] = @"""cache"", ""cookies"", ""storage"", ""executionContexts""";
    }
});
```
In this case all responses from server will be reloaded. But it must be used only with parameters, first time load after update for user.

**Comment by nasat-w** [comment]
This solution worked for me. I used this to clear the cache locally once and commented out. Sorry. By mistake, I thumbed down and not able to change.

app.UseStaticFiles(new StaticFileOptions()
{
    OnPrepareResponse = context =>
    {       
        context.Context.Response.Headers["Clear-Site-Data"] = @"""cache"", ""cookies"", ""storage"", ""executionContexts""";
    }
});

**Comment by damien7792** [comment]
We have been facing this issue for a couple months. We have read this thread, but none of the solutions worked for us.
So I just want to add a comment if anyone find themselves in our situation.

We are observing this issue it on our web servers only, not locally. Our app is built and deployed through an Azure DevOps pipeline. We've tried upgrading the wasm nuget packages, downgrading them. We tried clearing the cache, etc. Nothing worked.

The "clean your obj and bin folders" in Visual Studio made little sense for us since we're building in Azure DevOps.
Until we realized ... that maybe we need to clean up those build folders in ADO.

And indeed, changing the "Clean" option from "Sources" to "All Build Directories" finally fixed the issue

![Image](https://github.com/user-attachments/assets/0785e5b6-b523-4be3-899c-0d05615c3d00)

Hope that helps

**Comment by lartusi** [comment]
@javiercn Can you give us an update since the issue is assigned to you?

**Comment by LaughingJohn** [comment]
Just hit this issue in live after an upgrade from .Net 8.0 to .Net 9.0. It affected both Chrome & FF. Clearing the browser cache fixed it, but it's a tricky thing to explain to users. App was built using DevOps pipeline (Microsoft hosted).

**Comment by Bellarmine-Head** [comment]
> Clearing the browser cache fixed it, but it's a tricky thing to explain to users

Ouch!  This issue, coupled with the [horrible, newbie-hostile new-project template](https://github.com/dotnet/aspnetcore/issues/55307), makes me think that Blazor WebAssembly doesn't have much of a future.

Our decision in May 2020 was to limit Blazor WebAssembly to internal tools, and never use it for public-facing websites.  We're so happy with that decision, mainly because of this issue.

**Comment by philipmorley** [comment]
> We have been facing this issue for a couple months. We have read this thread, but none of the solutions worked for us. So I just want to add a comment if anyone find themselves in our situation.
> 
> We are observing this issue it on our web servers only, not locally. Our app is built and deployed through an Azure DevOps pipeline. We've tried upgrading the wasm nuget packages, downgrading them. We tried clearing the cache, etc. Nothing worked.
> 
> The "clean your obj and bin folders" in Visual Studio made little sense for us since we're building in Azure DevOps. Until we realized ... that maybe we need to clean up those build folders in ADO.
> 
> And indeed, changing the "Clean" option from "Sources" to "All Build Directories" finally fixed the issue
> 
> ![Image](https://github.com/user-attachments/assets/0785e5b6-b523-4be3-899c-0d05615c3d00)
> 
> Hope that helps

**Comment by philipmorley** [comment]
> 
> And indeed, changing the "Clean" option from "Sources" to "All Build Directories" finally fixed the issue
> 
> ![Image](https://github.com/user-attachments/assets/0785e5b6-b523-4be3-899c-0d05615c3d00)
> 

@damien7792, please can you tell me whereabouts in ADO is this Clean options drop down is?

**Comment by damien7792** [comment]
> > And indeed, changing the "Clean" option from "Sources" to "All Build Directories" finally fixed the issue
> > ![Image](https://github.com/user-attachments/assets/0785e5b6-b523-4be3-899c-0d05615c3d00)
> 
> [@damien7792](https://github.com/damien7792), please can you tell me whereabouts in ADO is this Clean options drop down is?

It's in the "Get Sources" step of the pipeline
Under the selection of the source and repo/mapping, you'll find the "Clean" parameter, and if you select "true", the "Clean options" will appear

**Comment by maharateeq** [comment]
> Here's a **workaround** that worked for me:
> 
> ```
> <script src="_framework/blazor.web.js" autostart="false"></script>
> <script>
>     Blazor.start({ webAssembly: {
>         loadBootResource: function (type, name, defaultUri, integrity)
>         {
>             if (defaultUri == "_framework/dotnet.js")
>             {
>                 return "_framework/dotnet.js?v=1";
>             }
>         }
>     } } );
> </script>
> ```



Just to confirm guys , after almost all sort of tries above it worked for me.

Just make sure to comment the previous <script src="_framework/blazor.web.js"  in the app.razor and add these changes.
So what actually it does is it add the version ?v=1  with most of the dotnet scripts which by default are cached on your browser or server or somewhere.

once you apply this u can varify this in the developer tools to see how the version is applied.

Probably this is the same change micrsoft is adding in Dotnet 10 to add the fingerprint option for dotnet scripts in more streightforward way than this twisted way.

**Comment by javiercn** [comment]
## For .NET 9.0 and 10.0

We implemented fingerprinting for hosted Blazor WebAssembly scenarios in .NET 9.0 and extended it to standalone scenarios in .NET 10.0. The implementation appends content-based hashes to static asset paths and generates importmaps in the HTML to ensure proper cache-busting when files change.

## For .NET 8.0

For .NET 8.0 users experiencing the `dotnet.js` caching issue, we believe you can add an `importmap` to your HTML as a workaround:

```html
<script type="importmap">
{
  "imports": {
    "./dotnet.js": "./dotnet.js?v=8.0.x"
  }
}
</script>
```

This forces the browser to fetch the updated version by adding a query string. We've filed https://github.com/dotnet/aspnetcore/issues/63161 to track that

**Comment by ThumbGen** [comment]
The proposed fix requires using 'unsafe-inline' for the script-src directive, or a variable hash that must be always updated.

**Comment by lartusi** [comment]
What do I need to do for .net 9? Just upgrade to the latest version?
