### ISSUE TITLE
duplicated ProjectReferences to razor class libraries lead to builds failing because of FilterStaticWebAssetEndpoints

### ISSUE THREAD

**Issue by AdmiralSnyder** [dotnet/aspnetcore#58354]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

when upgrading my blazor website from .net8 to .net9 rc2, i moved a couple of shared ProjectReferences to razor class library projects into a Directory.build.props file, but forgot to delete those in all projects.
turns out, duplicated <ProjectReference> nodes are not a good thing, because the blazor tooling(i suspect) doesn't make them unique, properly.

this can be easily reproduced by just duplicating a <ProjectReference> node in the .csproj file. if that points to something not affected by the blazor tooling, it won't error. if it does, it will. 
(maybe it's necessary for that razor class library to actually contain .razor.css files, but the binlog doesn't suggest that)

### Expected Behavior

either an error complaining about the duplicated ProjectReference in the .csproj or proper deduplication so it doesn't fail in the first place

### Steps To Reproduce

see this project:
https://github.com/AdmiralSnyder/ErrorRepros/tree/master/20241010_duplicated_projectreferences

repro workflow:
- create new blazor web app (i used .net9, but it might not matter)
- create a razor class library
- add a project reference to the web app
- go into the .csproj of the web app and duplicate the project reference
- --> the error appears.
- if you would instead have a "normal" class library referenced, and would duplicate that reference, there wouldn't be an error.

### Exceptions (if any)

C:\Program Files\dotnet\sdk\9.0.100-rc.1.24452.12\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.ScopedCss.targets(397,3): error MSB4018: The "FilterStaticWebAssetEndpoints" task failed unexpectedly.
System.ArgumentException: An item with the same key has already been added. Key: D:\source\GVT\GVTShowcase\BlazorComponents\obj\Debug\net9.0\scopedcss\projectbundle\BlazorComponents.bundle.scp.css
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.SpanToDictionary[TSource,TKey,TElement](ReadOnlySpan`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.FilterStaticWebAssetEndpoints.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(TaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [D:\source\GVT\GVTShowcase\Contents\GVT\Contents.GVT\Contents.GVT.csproj]

### .NET Version

9.0.100-rc.1.24452.12

### Anything else?

If you want, i can add a binlog file to the repro repo.
Since this is circumvented easily, i can totally get if this issue isn't prioritized. a better error message would really be nice, though. Because _finding_ it required @davidwengier having a look at that binlog.

Thanks for looking into this ❤ 

here's the dotnet --info output:

dotnet --info
.NET SDK:
 Version:           9.0.100-rc.1.24452.12
 Commit:            81a714c6d3
 Workload version:  9.0.100-manifests.67cd1eb6
 MSBuild version:   17.12.0-preview-24422-09+d17ec720d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100-rc.1.24452.12\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [ios]
   Installation Source: VS 17.12.35323.107
   Manifest Version:    17.5.9270-net9-rc1/9.0.100-rc.1
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-rc.1\microsoft.net.sdk.ios\17.5.9270-net9-rc1\WorkloadManifest.json
   Install Type:              Msi

 [android]
   Installation Source: VS 17.12.35323.107
   Manifest Version:    35.0.0-rc.1.80/9.0.100-rc.1
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-rc.1\microsoft.net.sdk.android\35.0.0-rc.1.80\WorkloadManifest.json
   Install Type:              Msi

 [maui-windows]
   Installation Source: VS 17.12.35323.107
   Manifest Version:    9.0.0-rc.1.24453.9/9.0.100-rc.1
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-rc.1\microsoft.net.sdk.maui\9.0.0-rc.1.24453.9\WorkloadManifest.json
   Install Type:              Msi

 [maccatalyst]
   Installation Source: VS 17.12.35323.107
   Manifest Version:    17.5.9270-net9-rc1/9.0.100-rc.1
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\9.0.100-rc.1\microsoft.net.sdk.maccatalyst\17.5.9270-net9-rc1\WorkloadManifest.json
   Install Type:              Msi

Host:
  Version:      9.0.0-rc.1.24431.7
  Architecture: x64
  Commit:       static

.NET SDKs installed:
  6.0.425 [C:\Program Files\dotnet\sdk]
  7.0.410 [C:\Program Files\dotnet\sdk]
  8.0.108 [C:\Program Files\dotnet\sdk]
  9.0.100-rc.1.24452.12 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-rc.1.24452.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-rc.1.24431.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0-rc.1.24452.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by javiercn** [comment]
@AdmiralSnyder thanks for contacting us.

It's very likely that this problem already existed in previous versions, and you are now seeing it manifest in a different way with the newer SDK. The cause is likely that there are duplicate assets in the pipeline which will very likely cause an issue at the time we generate the manifest.

The solution as you mentioned is to avoid having the duplicate reference in the project file. I'm surprised that the project system doesn't de-dupe these, as we don't consume the raw `ProjectReference` and only the results after they have been processed.

I think a fix here would likely involve improving the logic for `ProjectReference` to either error out or de-duplicate the references, we shouldn't be including logic to de-dupe them ourselves.

I'm going to move this issue to the backlog so that we can follow up with other folks on addressing this in the future.

**Comment by macias** [comment]
I am hit with the same issue. So far I used Net 8, after switch to framework Net 9 (I didn't do any other change in the code, only switching framework and language -- globally for entire solution) I cannot rebuild the solution because of this error.

I don't think I have double reference, but for sure, I have two frontends (BA, BS) which use the same library/Razor project. And I get one error per each of those projects. The key/file is from the shared project.

So for my eye, you are using somewhere a static/shared dictionary and you assume the css files will not be shared among end-projects. If this is the case it is false assumption.

**Comment by freever** [comment]
I am having a similar, although perhaps different issue. After upgradingVisual Studio to 12.12.0 my blazor hybrid project no longer compiles. I have 4 errors of this type:

```
9>Done building project "Onsight.Blazor.Hybrid.csproj" -- FAILED.
9>C:\Program Files\dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.ScopedCss.targets(397,3): error MSB4018: The "FilterStaticWebAssetEndpoints" task failed unexpectedly.
9>C:\Program Files\dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.ScopedCss.targets(397,3): error MSB4018: System.ArgumentException: An item with the same key has already been added.
9>C:\Program Files\dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.ScopedCss.targets(397,3): error MSB4018:    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
9>C:\Program Files\dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.ScopedCss.targets(397,3): error MSB4018:    at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
9>C:\Program Files\dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.ScopedCss.targets(397,3): error MSB4018:    at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
9>C:\Program Files\dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.ScopedCss.targets(397,3): error MSB4018:    at Microsoft.AspNetCore.StaticWebAssets.Tasks.FilterStaticWebAssetEndpoints.Execute()
9>C:\Program Files\dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.ScopedCss.targets(397,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
9>C:\Program Files\dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.ScopedCss.targets(397,3): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
9>Done building project "Onsight.Blazor.Hybrid.csproj" -- FAILED.
```

I have theorised that there must be scoped css classes with the same name, but I have checked and they are all correctly and uniquely named. I don't really know what to do.

**Comment by macias** [comment]
I had this problem. In my case I solved this by checking which framework I use -- I incorrectly set targets and .csproj info, so basically I was using some weird hybrid of 9.0/8.0 frameworks. I deleted all TargetFramework entries from .csproj files, and set it once in props file. From this point on this particular problem was gone.
