### ISSUE TITLE
When build an ASP.NET Web App, throw "The input string '0/001838235294' was not in a correct format.'" exception!

### ISSUE THREAD

**Issue by aminmashayekhi** [dotnet/aspnetcore#58422]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When Create a ASP.NET Web Application in .NET 9 and run it, app.Run() throw an exception with Title of "The input string '0/001838235294' was not in a correct format.'" and details that shown in Exceptions part... 

### Exceptions (if any)

   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at System.Double.Parse(String s, IFormatProvider provider)
   at Microsoft.AspNetCore.StaticAssets.StaticAssetEndpointFactory.Create(StaticAssetDescriptor resource, List`1 conventions, List`1 finallyConventions)
   at Microsoft.AspNetCore.StaticAssets.StaticAssetsEndpointDataSource.UpdateEndpoints()
   at Microsoft.AspNetCore.StaticAssets.StaticAssetsEndpointDataSource.Initialize()
   at Microsoft.AspNetCore.StaticAssets.StaticAssetsEndpointDataSource.GetChangeToken()
   at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, TState state)
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.AspNetCore.Routing.CompositeEndpointDataSource.CreateChangeTokenUnsynchronized(Boolean collectionChanged)
   at Microsoft.AspNetCore.Routing.CompositeEndpointDataSource.EnsureChangeTokenInitialized()
   at Microsoft.AspNetCore.Routing.CompositeEndpointDataSource.GetChangeToken()
   at Microsoft.AspNetCore.Routing.DataSourceDependentCache`1.Initialize()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.AspNetCore.Routing.DataSourceDependentCache`1.EnsureInitialized()
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationPolicyCache..ctor(EndpointDataSource dataSource)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at System.Reflection.ConstructorInvoker.InvokeImpl(Object arg1, Object arg2, Object arg3, Object arg4)
   at System.Reflection.ConstructorInvoker.Invoke(Span`1 arguments)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.ReflectionMiddlewareBinder.CreateMiddleware(RequestDelegate next)
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__40.MoveNext()
   at Microsoft.Extensions.Hosting.Internal.Host.<<StartAsync>b__14_1>d.MoveNext()
   at Microsoft.Extensions.Hosting.Internal.Host.<ForeachService>d__17`1.MoveNext()
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__14.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args) in D:\source\WebApplication1\WebApplication1\Program.cs:line 26

### .NET Version

9.0.100-rc.2.24474.11

### Anything else?

![Image](https://github.com/user-attachments/assets/1fdb1b28-7f1b-4826-86e9-0c4c5e1a3427)

**Comment by amcasey** [comment]
FYI @javiercn, this looks like it could be about loading static assets.

**Comment by aminmashayekhi** [comment]
Thanks for your response 😊
First, That is not a Blazor app! It's a simple ASP. NET web application. 
Second, It contains only default sample pages and nothing added to it.

**Comment by aminmashayekhi** [comment]
I've discovered that the root cause of the error lies in the **Windows decimal separator setting** during ASP.NET 9 project creation. If this setting is **"/"**, a runtime error occurs. However, setting it to **"."** initially and then changing it back doesn't trigger the error.

**Comment by javiercn** [comment]
@aminmashayekhi can you provide more details on how that configuration is being set?

Project creation shouldn't have a role to play here. Is it a case where you created the project, ran a build command, changed the value on the system settings and then ran the app?

I went to check the code we use, and we seem to be doing the right thing. The values get serialized with invariant culture and they get read the same way.

**Comment by aminmashayekhi** [comment]
this is the sample project repo that created with "/" decimal separator:
https://github.com/aminmashayekhi/NET9WebAppDemoBroken

**Comment by aminmashayekhi** [comment]
the problem is in following line of code:
https://github.com/dotnet/aspnetcore/blob/87d4d099c079dba45aa9c1490190b08882d9356e/src/StaticAssets/src/StaticAssetEndpointFactory.cs#L34
i test the following code in C# Interactive:
`double.Parse("0/001838235294", System.Globalization.CultureInfo.InvariantCulture);`
and the same error occured:
System.FormatException: The input string '0/001838235294' was not in a correct format.
  System.Number.ThrowFormatException<TChar>(ReadOnlySpan<TChar>)
  double.Parse(string, System.IFormatProvider)

**Comment by javiercn** [comment]
@aminmashayekhi thanks for the additional details.

I believe we've found the issue, the call that generates the value was missing the `InvariantCulture`. https://github.com/dotnet/sdk/blob/release/9.0.1xx/src/StaticWebAssetsSdk/Tasks/ApplyCompressionNegotiation.cs#L105

This is already fixed in main (10.0) https://github.com/dotnet/sdk/blob/main/src/StaticWebAssetsSdk/Tasks/ApplyCompressionNegotiation.cs#L232

We'll evaluate this for backporting back to `9.0.101`

**Comment by javiercn** [comment]
@aminmashayekhi this was merged and will make it into 9.0 RTM

https://github.com/dotnet/sdk/pull/44232
