### ISSUE TITLE
[Blazor] Exception when adding an InteractiveServer component inside .Client project (Rendermode Auto project)

### ISSUE THREAD

**Issue by DM-98** [dotnet/aspnetcore#58597]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

I found a similar issue:
https://github.com/dotnet/blazor-samples/issues/289

But this issue was closed without any explanation nor help.

When creating a BWA Global RenderMode Auto, and creating a new Component inside .Client project's Pages folder, and adding @rendermode InteractiveServer to it, it will fail when refreshing on the page itself:
```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot create a component of type 'BlazorApp20.Client.Pages.Test' because its render mode 'Microsoft.AspNetCore.Components.Web.InteractiveServerRenderMode' is not supported by WebAssembly rendering.
System.NotSupportedException: Cannot create a component of type 'BlazorApp20.Client.Pages.Test' because its render mode 'Microsoft.AspNetCore.Components.Web.InteractiveServerRenderMode' is not supported by WebAssembly rendering.
   at Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer.ResolveComponentForRenderMode(Type componentType, Nullable`1 parentComponentId, IComponentActivator componentActivator, IComponentRenderMode renderMode)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType, IComponentRenderMode callerSpecifiedRenderMode, Nullable`1 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame[] frames, Int32 frameIndex, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

### Expected Behavior

I expect to be able to have an InteractiveServer component page in a globally set InteractiveAuto without exception.

### Steps To Reproduce

1. Create a new BWA with a set Global RenderMode Auto
2. Create a new component inside .Client project's Pages folder, i.e. Test.razor
3. In Test.razor, add @page "/test" and @rendermode InteractiveServer
4. Navigate to /test and refresh, it fails with exception.

### Exceptions (if any)

Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot create a component of type 'BlazorApp20.Client.Pages.Test' because its render mode 'Microsoft.AspNetCore.Components.Web.InteractiveServerRenderMode' is not supported by WebAssembly rendering.
System.NotSupportedException: Cannot create a component of type 'BlazorApp20.Client.Pages.Test' because its render mode 'Microsoft.AspNetCore.Components.Web.InteractiveServerRenderMode' is not supported by WebAssembly rendering.
   at Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer.ResolveComponentForRenderMode(Type componentType, Nullable`1 parentComponentId, IComponentActivator componentActivator, IComponentRenderMode renderMode)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType, IComponentRenderMode callerSpecifiedRenderMode, Nullable`1 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame[] frames, Int32 frameIndex, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

### .NET Version

9.0.100-rc.2.24474.11

### Anything else?

![Image](https://github.com/user-attachments/assets/54bc6a7e-b67f-4893-b1e8-42a5b7dbf549)

**Comment by javiercn** [comment]
@DM-98 thanks for contacting us.

This is by design. Rendering Server components inside WebAssembly or viceversa is not supported.

**Comment by DM-98** [comment]
How is it by design, but your documentation tells me to do otherwise:
https://learn.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-9.0#server-project-updates

```
In the .Client project, place the following CultureClient component to study how globalization works for CSR components.

Pages/CultureClient.razor
```
`Server project updates`:
```
In the server project, place the following CultureServer component to study how globalization works for SSR components.

Components/Pages/CultureServer.razor
```
Adding 'CultureServer' to Server project will causes 404.
After researching about it, I found:
https://learn.microsoft.com/en-us/aspnet/core/blazor/components/render-modes?view=aspnetcore-9.0#interactive-server-side-rendering-interactive-ssr

Which says:
![Image](https://github.com/user-attachments/assets/bf87ca56-8204-4557-a1f5-66b0c0545b69)

So I placed it in Client's Pages folder since I my app adopts to global Auto rendering, and therefore I created this issue.
@javiercn
