### ISSUE TITLE
Quarantine Interop.FunctionalTests.Http3.Http3RequestTests.POST_ClientCancellationUpload_RequestAbortRaised(protocol: Http3)

### ISSUE THREAD

**Issue by eerhardt** [dotnet/aspnetcore#58802]
## Failing Test(s)

https://dev.azure.com/dnceng-public/public/_build/results?buildId=860776

- Interop.FunctionalTests.Http3.Http3RequestTests.POST_ClientCancellationUpload_RequestAbortRaised(protocol: Http3)

## Error Message

```text
Assert.Throws() Failure: No exception was thrown
Expected: typeof(System.IO.IOException)
```

```text
   at Microsoft.AspNetCore.InternalTesting.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 83
   at Interop.FunctionalTests.Http3.Http3RequestTests.POST_ClientCancellationUpload_RequestAbortRaised(HttpProtocols protocol) in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/Http3/Http3RequestTests.cs:line 521
--- End of stack trace from previous location ---
```

## Stacktrace

<details>

```text
   at Microsoft.AspNetCore.InternalTesting.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 83
   at Interop.FunctionalTests.Http3.Http3RequestTests.POST_ClientCancellationUpload_RequestAbortRaised(HttpProtocols protocol) in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/Http3/Http3RequestTests.cs:line 521
--- End of stack trace from previous location ---
```
</details>

## Logs

<details>

```text
2024-11-05T02:11:14.2950335Z [xUnit.net 00:01:17.86]     Interop.FunctionalTests.Http3.Http3RequestTests.POST_ClientCancellationUpload_RequestAbortRaised(protocol: Http3) [FAIL]
2024-11-05T02:11:14.2961137Z [xUnit.net 00:01:17.88]         | [0.001s] TestLifetime Information: Starting test POST_ClientCancellationUpload_RequestAbortRaised-Http3 at 2024-11-05T02:11:11
2024-11-05T02:11:14.2977098Z [xUnit.net 00:01:17.88]         | [0.007s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting starting
2024-11-05T02:11:14.2989872Z [xUnit.net 00:01:17.88]         | [0.057s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: QUIC listener starting with configured endpoint 127.0.0.1:0.
2024-11-05T02:11:14.3017909Z [xUnit.net 00:01:17.88]         | [0.058s] Microsoft.Hosting.Lifetime Information: Now listening on: https://127.0.0.1:52470
2024-11-05T02:11:14.3029404Z [xUnit.net 00:01:17.88]         | [0.058s] Microsoft.AspNetCore.Hosting.Diagnostics Debug: Loaded hosting startup assembly Interop.FunctionalTests
2024-11-05T02:11:14.3040183Z [xUnit.net 00:01:17.88]         | [0.058s] Microsoft.Hosting.Lifetime Information: Application started. Press Ctrl+C to shut down.
2024-11-05T02:11:14.3052074Z [xUnit.net 00:01:17.88]         | [0.058s] Microsoft.Hosting.Lifetime Information: Hosting environment: Production
2024-11-05T02:11:14.3066073Z [xUnit.net 00:01:17.88]         | [0.058s] Microsoft.Hosting.Lifetime Information: Content root path: /datadisks/disk1/work/9FA0094B/w/B25609AD/e/
2024-11-05T02:11:14.3096168Z [xUnit.net 00:01:17.88]         | [0.058s] Microsoft.Extensions.Hosting.Internal.Host Debug: Hosting started
2024-11-05T02:11:14.3107968Z [xUnit.net 00:01:17.88]         | [0.074s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Connection id "0HN7T7SEASRH6" accepted.
2024-11-05T02:11:14.3119151Z [xUnit.net 00:01:17.88]         | [0.074s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HN7T7SEASRH6" accepted.
2024-11-05T02:11:14.3131438Z [xUnit.net 00:01:17.88]         | [0.074s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HN7T7SEASRH6" started.
2024-11-05T02:11:14.3142766Z [xUnit.net 00:01:17.88]         | [0.074s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Stream id "0HN7T7SEASRH6:00000003" type Unidirectional connected.
2024-11-05T02:11:14.3167502Z [xUnit.net 00:01:17.88]         | [0.074s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Stream id "0HN7T7SEASRH6:00000002" type Unidirectional accepted.
2024-11-05T02:11:14.3180001Z [xUnit.net 00:01:17.88]         | [0.074s] Microsoft.AspNetCore.Server.Kestrel.Http3 Trace: Connection id "0HN7T7SEASRH6" received SETTINGS frame for stream ID 2 with length 5.
2024-11-05T02:11:14.3191427Z [xUnit.net 00:01:17.88]         | [0.082s] Interop.FunctionalTests.Http3.Http3RequestTests Information: Client sending request headers
2024-11-05T02:11:14.3202663Z [xUnit.net 00:01:17.88]         | [0.085s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Stream id "0HN7T7SEASRH6:00000000" type Bidirectional accepted.
2024-11-05T02:11:14.3246877Z [xUnit.net 00:01:17.88]         | [0.085s] Microsoft.AspNetCore.Server.Kestrel.Http3 Trace: Connection id "0HN7T7SEASRH6" received HEADERS frame for stream ID 0 with length 22.
2024-11-05T02:11:14.3259245Z [xUnit.net 00:01:17.88]         | [0.085s] Microsoft.AspNetCore.Hosting.Diagnostics Information: Request starting HTTP/3 POST https://127.0.0.1:52470/ - - -
2024-11-05T02:11:14.3270343Z [xUnit.net 00:01:17.88]         | [0.086s] Interop.FunctionalTests.Http3.Http3RequestTests Information: Server reading content
2024-11-05T02:11:14.3299091Z [xUnit.net 00:01:17.88]         | [0.086s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HN7T7SEASRH6", Request id "0HN7T7SEASRH6:00000000": started reading request body.
2024-11-05T02:11:14.3299191Z [xUnit.net 00:01:17.88]         | [0.097s] Interop.FunctionalTests.Http3.Http3RequestTests Information: Client sending request content
2024-11-05T02:11:14.3350461Z [xUnit.net 00:01:17.88]         | [0.097s] Interop.FunctionalTests.Http3.Http3RequestTests Information: Client waiting until content is read on server
2024-11-05T02:11:14.3350558Z [xUnit.net 00:01:17.88]         | [0.097s] Microsoft.AspNetCore.Server.Kestrel.Http3 Trace: Connection id "0HN7T7SEASRH6" received DATA frame for stream ID 0 with length 11.
2024-11-05T02:11:14.3361981Z [xUnit.net 00:01:17.88]         | [0.108s] Interop.FunctionalTests.Http3.Http3RequestTests Information: Client cancelling
2024-11-05T02:11:14.3365823Z [xUnit.net 00:01:17.88]         | [0.110s] Interop.FunctionalTests.Http3.Http3RequestTests Information: Server waiting for cancellation
2024-11-05T02:11:14.3379452Z [xUnit.net 00:01:17.88]         | [0.111s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Stream id "0HN7T7SEASRH6:00000000" write aborted by peer with error code 268.
2024-11-05T02:11:14.3416863Z [xUnit.net 00:01:17.88]         | [0.111s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Stream id "0HN7T7SEASRH6:00000000" shutting down writes because: "Stream aborted by peer (268).".
2024-11-05T02:11:14.3428855Z [xUnit.net 00:01:17.88]         | [0.111s] Microsoft.AspNetCore.Server.Kestrel.Http3 Debug: Trace id "0HN7T7SEASRH6:00000000": HTTP/3 stream error "H3_REQUEST_CANCELLED". An abort is being sent to the stream.
2024-11-05T02:11:14.3439460Z [xUnit.net 00:01:17.88]         | Microsoft.AspNetCore.Connections.ConnectionAbortedException: The client reset the request stream.
2024-11-05T02:11:14.3451453Z [xUnit.net 00:01:17.88]         |  ---> System.IO.IOException: The client reset the request stream.
2024-11-05T02:11:14.3462071Z [xUnit.net 00:01:17.88]         |    --- End of inner exception stack trace ---
2024-11-05T02:11:14.3473915Z [xUnit.net 00:01:17.88]         | [0.111s] Interop.FunctionalTests.Http3.Http3RequestTests Information: Server received cancellation
2024-11-05T02:11:14.3485496Z [xUnit.net 00:01:17.88]         | [0.111s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HN7T7SEASRH6", Request id "0HN7T7SEASRH6:00000000": done reading request body.
2024-11-05T02:11:14.3498679Z [xUnit.net 00:01:17.88]         | [0.111s] Microsoft.AspNetCore.Hosting.Diagnostics Information: Request finished HTTP/3 POST https://127.0.0.1:52470/ - 499 - - 26.5673ms
2024-11-05T02:11:14.3537369Z [xUnit.net 00:01:17.88]         | [0.114s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Connection id "0HN7T7SEASRH6" aborted by peer with error code 256.
2024-11-05T02:11:14.3548884Z [xUnit.net 00:01:17.88]         | System.Net.Quic.QuicException: Connection aborted by peer (256).
2024-11-05T02:11:14.3560583Z [xUnit.net 00:01:17.88]         |    at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByPeer(_SHUTDOWN_INITIATED_BY_PEER_e__Struct& data)
2024-11-05T02:11:14.3573323Z [xUnit.net 00:01:17.88]         |    at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent)
2024-11-05T02:11:14.3585481Z [xUnit.net 00:01:17.89]         |    at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)
2024-11-05T02:11:14.3596373Z [xUnit.net 00:01:17.89]         | --- End of stack trace from previous location ---
2024-11-05T02:11:14.3609694Z [xUnit.net 00:01:17.89]         |    at System.Net.Quic.QuicConnection.AcceptInboundStreamAsync(CancellationToken cancellationToken)
2024-11-05T02:11:14.3624391Z [xUnit.net 00:01:17.89]         |    at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionContext.AcceptAsync(CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicConnectionContext.cs:line 97
2024-11-05T02:11:14.3651193Z [xUnit.net 00:01:17.89]         | [0.114s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Stream id "0HN7T7SEASRH6:00000002" read aborted by peer with error code 256.
2024-11-05T02:11:14.3662794Z [xUnit.net 00:01:17.89]         | [0.114s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Stream id "0HN7T7SEASRH6:00000003" write aborted by peer with error code 256.
2024-11-05T02:11:14.3674426Z [xUnit.net 00:01:17.89]         | [0.115s] Microsoft.AspNetCore.Server.Kestrel.BadRequests Debug: Connection id "0HN7T7SEASRH6" request processing ended abnormally.
2024-11-05T02:11:14.3686165Z [xUnit.net 00:01:17.89]         | Microsoft.AspNetCore.Connections.ConnectionResetException: Connection aborted by peer (256).
2024-11-05T02:11:14.3697199Z [xUnit.net 00:01:17.89]         |  ---> System.Net.Quic.QuicException: Connection aborted by peer (256).
2024-11-05T02:11:14.3733081Z [xUnit.net 00:01:17.89]         |    at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByPeer(_SHUTDOWN_INITIATED_BY_PEER_e__Struct& data)
2024-11-05T02:11:14.3733185Z [xUnit.net 00:01:17.89]         |    at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent)
2024-11-05T02:11:14.3742617Z [xUnit.net 00:01:17.89]         |    at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)
2024-11-05T02:11:14.3772958Z [xUnit.net 00:01:17.89]         | --- End of stack trace from previous location ---
2024-11-05T02:11:14.3784012Z [xUnit.net 00:01:17.89]         |    at System.Net.Quic.QuicConnection.AcceptInboundStreamAsync(CancellationToken cancellationToken)
2024-11-05T02:11:14.3796201Z [xUnit.net 00:01:17.89]         |    at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionContext.AcceptAsync(CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicConnectionContext.cs:line 97
2024-11-05T02:11:14.3808134Z [xUnit.net 00:01:17.89]         |    --- End of inner exception stack trace ---
2024-11-05T02:11:14.3819870Z [xUnit.net 00:01:17.89]         |    at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionContext.AcceptAsync(CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicConnectionContext.cs:line 145
2024-11-05T02:11:14.3834777Z [xUnit.net 00:01:17.89]         |    at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
2024-11-05T02:11:14.3849551Z [xUnit.net 00:01:17.89]         |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http3.Http3Connection.ProcessRequestsAsync[TContext](IHttpApplication`1 application) in /_/src/Servers/Kestrel/Core/src/Internal/Http3/Http3Connection.cs:line 363
2024-11-05T02:11:14.3870907Z [xUnit.net 00:01:17.89]         | [0.115s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Stream id "0HN7T7SEASRH6:00000003" shutting down writes because: "Connection aborted by peer (256).".
2024-11-05T02:11:14.3883091Z [xUnit.net 00:01:17.89]         | [0.115s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Connection id "0HN7T7SEASRH6" aborted by application with error code 256 because: "The client closed the connection.".
2024-11-05T02:11:14.3894061Z [xUnit.net 00:01:17.89]         | [0.115s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: Stream id "0HN7T7SEASRH6:00000000" aborted by application with error code 268 because: "The client reset the request stream.".
2024-11-05T02:11:14.3931340Z [xUnit.net 00:01:17.89]         | [0.116s] Microsoft.AspNetCore.Server.Kestrel.Http3 Debug: Connection id "0HN7T7SEASRH6" is closed. The last processed stream ID was 0.
2024-11-05T02:11:14.3942483Z [xUnit.net 00:01:17.89]         | [0.116s] Microsoft.AspNetCore.Server.Kestrel.Connections Debug: Connection id "0HN7T7SEASRH6" stopped.
2024-11-05T02:11:14.3954512Z [xUnit.net 00:01:17.89]         | [0.117s] Microsoft.AspNetCore.Server.Kestrel.Transport.Quic Debug: QUIC listener aborted.
2024-11-05T02:11:14.3965716Z [xUnit.net 00:01:17.89]         | System.ObjectDisposedException: Cannot access a disposed object.
2024-11-05T02:11:14.3977758Z [xUnit.net 00:01:17.89]         | Object name: 'System.Net.Quic.QuicListener'.
2024-11-05T02:11:14.3988889Z [xUnit.net 00:01:17.89]         |    at System.Net.Quic.QuicListener.DisposeAsync()
2024-11-05T02:11:14.4012103Z [xUnit.net 00:01:17.89]         |    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
2024-11-05T02:11:14.4023407Z [xUnit.net 00:01:17.89]         |    at System.Net.Quic.QuicListener.DisposeAsync()
2024-11-05T02:11:14.4035008Z [xUnit.net 00:01:17.89]         |    at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionListener.DisposeAsync() in /_/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicConnectionListener.cs:line 211
2024-11-05T02:11:14.4045891Z [xUnit.net 00:01:17.89]         |    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
2024-11-05T02:11:14.4066055Z [xUnit.net 00:01:17.89]         |    at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionListener.DisposeAsync()
2024-11-05T02:11:14.4077035Z [xUnit.net 00:01:17.89]         |    at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionListener.UnbindAsync(CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicConnectionListener.cs:line 200
2024-11-05T02:11:14.4127461Z [xUnit.net 00:01:17.89]         |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.GenericMultiplexedConnectionListener.UnbindAsync(CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/Infrastructure/TransportManager.cs:line 233
2024-11-05T02:11:14.4140843Z [xUnit.net 00:01:17.89]         |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.ActiveTransport.UnbindAsync(CancellationToken cancellationToken)
2024-11-05T02:11:14.4151517Z [xUnit.net 00:01:17.89]         |    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
2024-11-05T02:11:14.4162436Z [xUnit.net 00:01:17.89]         |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.StopTransportsAsync(List`1 transportsToStop, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/Infrastructure/TransportManager.cs:line 131
2024-11-05T02:11:14.4174050Z [xUnit.net 00:01:17.89]         |    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
2024-11-05T02:11:14.4185610Z [xUnit.net 00:01:17.89]         |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StopAsync(CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs:line 259
2024-11-05T02:11:14.4196183Z [xUnit.net 00:01:17.89]         |    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
2024-11-05T02:11:14.4208304Z [xUnit.net 00:01:17.89]         |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StopAsync(CancellationToken cancellationToken)
2024-11-05T02:11:14.4219640Z [xUnit.net 00:01:17.89]         |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.Dispose() in /_/src/Servers/Kestrel/Core/src/Internal/KestrelServerImpl.cs:line 283
2024-11-05T02:11:14.4231814Z [xUnit.net 00:01:17.89]         |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.DisposeAsync()
2024-11-05T02:11:14.4242561Z [xUnit.net 00:01:17.89]         |    at Microsoft.Extensions.Hosting.Internal.Host.DisposeAsync()
2024-11-05T02:11:14.4287208Z [xUnit.net 00:01:17.89]         |    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
2024-11-05T02:11:14.4299943Z [xUnit.net 00:01:17.89]         |    at Microsoft.Extensions.Hosting.Internal.Host.DisposeAsync()
2024-11-05T02:11:14.4310970Z [xUnit.net 00:01:17.89]         |    at Microsoft.Extensions.Hosting.Internal.Host.Dispose()
2024-11-05T02:11:14.4322825Z [xUnit.net 00:01:17.89]         |    at Interop.FunctionalTests.Http3.Http3RequestTests.POST_ClientCancellationUpload_RequestAbortRaised(HttpProtocols protocol) in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/Http3/Http3RequestTests.cs:line 521
2024-11-05T02:11:14.4334083Z [xUnit.net 00:01:17.89]         |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
2024-11-05T02:11:14.4345689Z [xUnit.net 00:01:17.89]         |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2024-11-05T02:11:14.4356347Z [xUnit.net 00:01:17.89]         |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
2024-11-05T02:11:14.4367231Z [xUnit.net 00:01:17.89]         |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
2024-11-05T02:11:14.4379455Z [xUnit.net 00:01:17.89]         |    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
2024-11-05T02:11:14.4411470Z [xUnit.net 00:01:17.90]         |    at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
2024-11-05T02:11:14.4421657Z [xUnit.net 00:01:17.90]         |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
2024-11-05T02:11:14.4432483Z [xUnit.net 00:01:17.90]         |    at Microsoft.AspNetCore.InternalTesting.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 106
2024-11-05T02:11:14.4444042Z [xUnit.net 00:01:17.90]         |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
2024-11-05T02:11:14.4456189Z [xUnit.net 00:01:17.90]         |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
2024-11-05T02:11:14.4469290Z [xUnit.net 00:01:17.90]         |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
2024-11-05T02:11:14.4483819Z [xUnit.net 00:01:17.90]         |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
2024-11-05T02:11:14.4494538Z [xUnit.net 00:01:17.90]         |    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
2024-11-05T02:11:14.4535152Z [xUnit.net 00:01:17.90]         |    at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
2024-11-05T02:11:14.4546788Z [xUnit.net 00:01:17.90]         |    at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
2024-11-05T02:11:14.4558639Z [xUnit.net 00:01:17.90]         |    at System.Threading.Tasks.Task.CancellationPromise`1.System.Threading.Tasks.ITaskCompletionAction.Invoke(Task completingTask)
2024-11-05T02:11:14.4569702Z [xUnit.net 00:01:17.90]         |    at System.Threading.ThreadPoolWorkQueue.Dispatch()
2024-11-05T02:11:14.4581798Z [xUnit.net 00:01:17.90]         |    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
2024-11-05T02:11:14.4592683Z [xUnit.net 00:01:17.90]         | --- End of stack trace from previous location ---
2024-11-05T02:11:14.4603980Z [xUnit.net 00:01:17.90]         |    at System.Net.Quic.QuicListener.AcceptConnectionAsync(CancellationToken cancellationToken)
2024-11-05T02:11:14.4615497Z [xUnit.net 00:01:17.90]         |    at Microsoft.AspNetCore.Server.Kestrel.Transport.Quic.Internal.QuicConnectionListener.AcceptAsync(IFeatureCollection features, CancellationToken cancellationToken) in /_/src/Servers/Kestrel/Transport.Quic/src/Internal/QuicConnectionListener.cs:line 157
2024-11-05T02:11:14.4629754Z [xUnit.net 00:01:17.90]         | [0.155s] Interop.FunctionalTests.Http3.Http3RequestTests Error: Test threw an exception.
2024-11-05T02:11:14.4654787Z [xUnit.net 00:01:17.90]         | Xunit.Sdk.ThrowsException: Assert.Throws() Failure: No exception was thrown
2024-11-05T02:11:14.4666512Z [xUnit.net 00:01:17.90]         | Expected: typeof(System.IO.IOException)
2024-11-05T02:11:14.4677555Z [xUnit.net 00:01:17.90]         |    at Xunit.Assert.Throws(Type exceptionType, Exception exception) in /_/src/xunit.assert/Asserts/ExceptionAsserts.cs:line 34
2024-11-05T02:11:14.4689476Z [xUnit.net 00:01:17.90]         |    at Xunit.Assert.ThrowsAsync[T](Func`1 testCode) in /_/src/xunit.assert/Asserts/ExceptionAsserts.cs:line 264
2024-11-05T02:11:14.4701248Z [xUnit.net 00:01:17.90]         |    at Microsoft.AspNetCore.InternalTesting.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber) in /_/src/Shared/TaskExtensions.cs:line 83
2024-11-05T02:11:14.4733874Z [xUnit.net 00:01:17.90]         |    at Interop.FunctionalTests.Http3.Http3RequestTests.POST_ClientCancellationUpload_RequestAbortRaised(HttpProtocols protocol) in /_/src/Servers/Kestrel/test/Interop.FunctionalTests/Http3/Http3RequestTests.cs:line 521
2024-11-05T02:11:14.4745229Z [xUnit.net 00:01:17.90]         |    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 253
2024-11-05T02:11:14.4757231Z [xUnit.net 00:01:17.90]         | --- End of stack trace from previous location ---
2024-11-05T02:11:14.4768637Z [xUnit.net 00:01:17.90]         |    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
2024-11-05T02:11:14.4779934Z [xUnit.net 00:01:17.90]         |    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
2024-11-05T02:11:14.4796443Z [xUnit.net 00:01:17.90]         | [0.156s] TestLifetime Information: Finished test POST_ClientCancellationUpload_RequestAbortRaised-Http3 in 0.1557434s
```
</details>

## Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=860776

**Comment by BrennanConroy** [comment]
Were you planning on quarantining the test?

**Comment by eerhardt** [comment]
> Were you planning on quarantining the test?

I only saw it fail once. I figured I'd open an issue and if I saw it again I'd quarantine it.
