### ISSUE TITLE
Blazor Server .net 9 Websocket connection fails, Same site with .net 8 works fine

### ISSUE THREAD

**Issue by selaromdotnet** [dotnet/aspnetcore#58932]
I'm encountering a strange issue and I'm not really sure how to approach it. I host my websites with smarterasp.net which added support for .net 9 with yesterday's release...

However, after upgrading and publishing my blazor server app from .net 8.0 to 9.0, it is failing to establish the websocket connection and not running as expected.

The only difference between these two sites is the .net version (and the associated nuget packages), so I can only think that it's a problem with the environment or a bug, and I'm not really sure how to confirm either...

I published the .net 8 site here: https://dev.mcallengaragesales.com which loads and connects and seems to run fine on Firefox, edge, chrome on both desktop and mobile.

I upgraded that same site to .net 9 and published it here: https://dev9.mcallengaragesales.com and on firefox desktop I get this error:

```
[2024-11-13T22:05:24.792Z] Information: Normalizing '_blazor' to 'https://dev9.mcallengaragesales.com/_blazor'. [blazor.web.js:1:47102](https://dev9.mcallengaragesales.com/_framework/blazor.web.js)
[2024-11-13T22:05:25.504Z] Information: WebSocket connected to wss://dev9.mcallengaragesales.com/_blazor?id=VYh6X3Cn47ojOab5M2uiXQ. [blazor.web.js:1:47102](https://dev9.mcallengaragesales.com/_framework/blazor.web.js)
The connection to wss://dev9.mcallengaragesales.com/_blazor?id=VYh6X3Cn47ojOab5M2uiXQ was interrupted while the page was loading. [blazor.web.js:1:80199](https://dev9.mcallengaragesales.com/_framework/blazor.web.js)
[2024-11-13T22:05:44.757Z] Information: (WebSockets transport) There was an error with the transport. [blazor.web.js:1:47102](https://dev9.mcallengaragesales.com/_framework/blazor.web.js)
[2024-11-13T22:05:44.758Z] Error: Connection disconnected with error 'Error: WebSocket closed with status code: 1006 (no reason given).'. [blazor.web.js:1:47019](https://dev9.mcallengaragesales.com/_framework/blazor.web.js)
[2024-11-13T22:05:44.758Z] Error: Error: WebSocket closed with status code: 1006 (no reason given). [blazor.web.js:1:39473](https://dev9.mcallengaragesales.com/_framework/blazor.web.js)
[2024-11-13T22:05:44.758Z] Error: Error: Cannot send data if the connection is not in the 'Connected' State. [blazor.web.js:1:39473](https://dev9.mcallengaragesales.com/_framework/blazor.web.js)
[2024-11-13T22:05:44.758Z] Information: Normalizing '_blazor' to 'https://dev9.mcallengaragesales.com/_blazor'. [blazor.web.js:1:47102](https://dev9.mcallengaragesales.com/_framework/blazor.web.js)
Firefox can’t establish a connection to the server at wss://dev9.mcallengaragesales.com/_blazor?id=182Go0fRvtQfWVWgU8PcYw. [blazor.web.js:1:80199](https://dev9.mcallengaragesales.com/_framework/blazor.web.js)
[2024-11-13T22:05:45.486Z] Information: (WebSockets transport) There was an error with the transport. [blazor.web.js:1:47102](https://dev9.mcallengaragesales.com/_framework/blazor.web.js)
[2024-11-13T22:05:45.486Z] Error: Failed to start the transport 'WebSockets': Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled.

```
On chrome desktop I get a similar but slightly different error:

```
[2024-11-13T22:04:43.733Z] Information: Normalizing '_blazor' to 'https://dev9.mcallengaragesales.com/_blazor'.
blazor.web.js:1 WebSocket connection to 'wss://dev9.mcallengaragesales.com/_blazor?id=nXyCEXfix-zJi1n89EgOrg' failed: 
(anonymous) @ blazor.web.js:1Understand this errorAI
blazor.web.js:1 [2024-11-13T22:04:44.158Z] Information: (WebSockets transport) There was an error with the transport.
blazor.web.js:1 [2024-11-13T22:04:44.158Z] Error: Failed to start the transport 'WebSockets': Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled.
log @ blazor.web.js:1Understand this errorAI
blazor.web.js:1 [2024-11-13T22:04:44.503Z] Warning: Failed to connect via WebSockets, using the Long Polling fallback transport. This may be due to a VPN or proxy blocking the connection. To troubleshoot this, visit https://aka.ms/blazor-server-using-fallback-long-polling.
```

On mobile, the .net 9 site simply shows the standard blazor error with reload message at the footer (I don't know how to see dev tools on android to get more detailed errors)...

As an attempt to eliminate any other variables, I created a brand new, clean, default blazor web site for .net 9 using server interactive in visual studio and published that here: http://test.mcallengaragesales.com

and in firefox on THAT site, I get this error:

```
[2024-11-13T22:09:59.631Z] Information: Normalizing '_blazor' to 'http://test.mcallengaragesales.com/_blazor'. [blazor.web.js:1:47102](http://test.mcallengaragesales.com/_framework/blazor.web.js)
Firefox can’t establish a connection to the server at ws://test.mcallengaragesales.com/_blazor?id=e_FiqjqOx95vihFDg7P8CA. [blazor.web.js:1:80199](http://test.mcallengaragesales.com/_framework/blazor.web.js)
[2024-11-13T22:09:59.984Z] Information: (WebSockets transport) There was an error with the transport. [blazor.web.js:1:47102](http://test.mcallengaragesales.com/_framework/blazor.web.js)
[2024-11-13T22:09:59.985Z] Error: Failed to start the transport 'WebSockets': Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled. [blazor.web.js:1:47019](http://test.mcallengaragesales.com/_framework/blazor.web.js)
[2024-11-13T22:10:00.708Z] Warning: Failed to connect via WebSockets, using the Long Polling fallback transport. This may be due to a VPN or proxy blocking the connection. To troubleshoot this, visit https://aka.ms/blazor-server-using-fallback-long-polling. [blazor.web.js:1:39512](http://test.mcallengaragesales.com/_framework/blazor.web.js)
[2024-11-13T22:10:01.576Z] Error: There was an error applying batch 2. [blazor.web.js:1:39473](http://test.mcallengaragesales.com/_framework/blazor.web.js)
[2024-11-13T22:10:01.579Z] Error: There was an error applying batch 3. [blazor.web.js:1:39473](http://test.mcallengaragesales.com/_framework/blazor.web.js)
[2024-11-13T22:10:01.805Z] Error: System.AggregateException: One or more errors occurred. (TypeError: n.parentNode is null)

 ---> System.InvalidOperationException: TypeError: n.parentNode is null

   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InvokeRenderCompletedCallsAfterUpdateDisplayTask(Task updateDisplayTask, Int32[] updatedComponents)

   --- End of inner exception stack trace --- [blazor.web.js:1:39473](http://test.mcallengaragesales.com/_framework/blazor.web.js)
XHRPOST
http://test.mcallengaragesales.com/_blazor?id=_pNXLGiS-NE3aR74tAFcdQ
[HTTP/1.1 404 Not Found 88ms]

[2024-11-13T22:10:01.948Z] Information: Connection disconnected. [blazor.web.js:1:47102](http://test.mcallengaragesales.com/_framework/blazor.web.js)

```

and this on edge:

```
[2024-11-13T22:11:15.038Z] Information: Normalizing '_blazor' to 'http://test.mcallengaragesales.com/_blazor'.
blazor.web.js:1 [2024-11-13T22:11:15.282Z] Information: WebSocket connected to ws://test.mcallengaragesales.com/_blazor?id=WlqbMNRCNy-5sQk5zMEA2A.
blazor.web.js:1  [2024-11-13T22:11:15.283Z] Error: Connection disconnected with error 'Error: WebSocket closed with status code: 1006 (no reason given).'.
log @ blazor.web.js:1
_stopConnection @ blazor.web.js:1
features.reconnect.transport.onclose @ blazor.web.js:1
_close @ blazor.web.js:1
i.onclose @ blazor.web.js:1
blazor.web.js:1  [2024-11-13T22:11:15.283Z] Error: Error: WebSocket closed with status code: 1006 (no reason given).
log @ blazor.web.js:1
unhandledError @ blazor.web.js:1
startConnection @ blazor.web.js:1
await in startConnection
startCore @ blazor.web.js:1
start @ blazor.web.js:1
Qo @ blazor.web.js:1
await in Qo
Yo @ blazor.web.js:1
startCircutIfNotStarted @ blazor.web.js:1
resolveRendererIdForDescriptor @ blazor.web.js:1
determinePendingOperation @ blazor.web.js:1
refreshRootComponents @ blazor.web.js:1
(anonymous) @ blazor.web.js:1
setTimeout
rootComponentsMayRequireRefresh @ blazor.web.js:1
onDocumentUpdated @ blazor.web.js:1
Hi @ blazor.web.js:1
blazor.web.js:1  [2024-11-13T22:11:15.284Z] Error: Failed to start the circuit.
```
​
I am at a total loss for what to do. I want to publish the .net 9 site live today but I can't with this issue. I'm hoping it's an environment thing as opposed to a bug in my code (or .net) but at the same time I have no idea what to tell my host to try and remedy the issue...

Does anyone else get any different result than I am showing above? Any ideas what might be wrong here? anything more I can provide to give more insight?

many thanks for taking a look!

**Comment by BrennanConroy** [comment]
Are you hosting with IIS OutOfProcess?

**Comment by selaromdotnet** [comment]
oh yes thank you I forgot to mention that, both sites are outofprocess, that appears to be required for all .net core sites on smarterasp.

I'll try your suggestion and report back thanks!

**Comment by selaromdotnet** [comment]
oh my that seems to have done it!!! I no longer get the error on any browser or mobile after disabling compression.

THANK YOU!!

I do wonder if this is an environment thing, as I'm sure I'd appreciate being able to use compression, but let me report this to the host, and see if I can find more docs on what's required and I'll report back any findings.

thanks again!!!

**Comment by BrennanConroy** [comment]
OutOfProcess will not support compression, but we are fixing it to not fail the websocket connection.
https://github.com/dotnet/aspnetcore/pull/58931

**Comment by selaromdotnet** [comment]
ah okay awesome thank you for sharing this additional insight, and the coming update to resolve it, you really made my day!

**Comment by javiercn** [comment]
@BrennanConroy thanks for catching this.

**Comment by techscx** [comment]
When hosting behind iis via arr and forwarding to a server in a serverfarm, after upgrading to .net 9 doesn't work either caused by the new default compression. After disabling the compression, the app works again in .net 9.

**Comment by dotnetappdev** [comment]
Its still causing an issue for me in blazor .net 9.0 hosting is shared hosting beyond my control @BrennanConroy the work around in lattest .net 9 doesnt seem to expose  DisableWebSocketCompression

**Comment by sact1909** [comment]
> 9.0.1 has been released and has a fix for this. To get the fixed bits you need to install the new hosting bundle, instructions and various options are described in https://learn.microsoft.com/aspnet/core/host-and-deploy/iis/hosting-bundle?view=aspnetcore-9.0
> 
> The workaround: `MapRazorComponents<App>().AddServerSideComponents(o => o.DisableWebSocketCompression = true)` is no longer needed.

I did install the new hosting bundle and I even set this

`app.MapRazorComponents<App>()
    .AddInteractiveServerRenderMode(o=>o.DisableWebSocketCompression = true);`

and still happen the same to me

![Image](https://github.com/user-attachments/assets/f8ffb8d4-bbfb-4b06-a9bf-1a3c00f71b78)

and this is new app created from Visual Studio templates doesn't have anything else than what comes with the template

**Comment by Richard-Dufour** [comment]
> Are you hosting with IIS OutOfProcess?
> 
> Also, try `MapRazorComponents<App>().AddServerSideComponents(o => o.DisableWebSocketCompression = true)`

Thank you @BrennanConroy, in my case, what fixed it was: 

app.MapRazorComponents<ChattelWeb.Components.App>()
     .AddInteractiveServerRenderMode(o => o.DisableWebSocketCompression = true);

**Comment by dotnetappdev** [comment]
It actually ended up being my ssl expired reloaded new ssl seems to fix issue Sent from my iPhoneOn 20 Mar 2025, at 22:37, Richard Dufour ***@***.***> wrote:﻿
  
Are you hosting with IIS OutOfProcess?
Also, try MapRazorComponents<App>().AddServerSideComponents(o => o.DisableWebSocketCompression = true)

Thank you @BrennanConroy, in my case, what fixed it was:
app.MapRazorComponents<ChattelWeb.Components.App>()
.AddInteractiveServerRenderMode(o => o.DisableWebSocketCompression = true);—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>



Richard-Dufour left a comment (dotnet/aspnetcore#58932)

Are you hosting with IIS OutOfProcess?
Also, try MapRazorComponents<App>().AddServerSideComponents(o => o.DisableWebSocketCompression = true)

Thank you @BrennanConroy, in my case, what fixed it was:
app.MapRazorComponents<ChattelWeb.Components.App>()
.AddInteractiveServerRenderMode(o => o.DisableWebSocketCompression = true);

**Comment by imprathamesh** [comment]
I have same error in .net 9 hosted on IIS windows hosting
 
2025-07-28 11:25:15 | 400 | GET /_blazor id=jr3YqPbmM10mJjzz3oOONA&_=1753682101665 HTTP/2

sometimes its 403 too. 

WebSocket not get established only work in development env. 

Websocket is Enabled on hosting. 
No Proxy, No Web Farm/Load balancer set, No Cache Server. 

my project is Blazor web app Interactive Mode Auto in .net 9  even this same error in .net 8 too. 
you can check here  test.innovustech.in

**Comment by Detrua** [comment]
Added the _blazor section fixed the issue:

```
location /_blazor {
    proxy_pass http://127.0.0.1:6001;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";  # MUST be this string exactly
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_read_timeout 100s;
    proxy_buffering off;
}
```
Console:

```
13:40:49.223 blazor.web.js:1 [2025-09-09T11:40:49.223Z] Information: Normalizing '_blazor' to 'https://test.domain.com/_blazor'.
13:40:49.403 blazor.web.js:1 [2025-09-09T11:40:49.403Z] Information: WebSocket connected to wss://test.domain.com/_blazor?id=omy9iXnzZ5qr4a2jQ4TJaw.
```

https://nginx.org/en/docs/http/websocket.html

Program.cs
```
builder.Services.AddRazorComponents()
    .AddInteractiveServerComponents()
    .AddMicrosoftIdentityConsentHandler()
    .AddHubOptions(options =>
    {
        options.ClientTimeoutInterval = TimeSpan.FromSeconds(70);
        options.HandshakeTimeout = TimeSpan.FromSeconds(60);
    })
    .AddCircuitOptions(options =>
    {
        options.DetailedErrors = true;
    });
```
