### ISSUE TITLE
.NET 9 OpenApi: JSON schema generation is not supported for contracts using ReferenceHandler.Preserve

### ISSUE THREAD

**Issue by nicolaiarocci** [dotnet/aspnetcore#58943]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Upgrading a .NET 8 Minimal API to .NET 9 and switching from Swashbuckle.AspNetCore to built-in Open API support, we get the following exception:

`System.NotSupportedException: JSON schema generation is not supported for contracts using ReferenceHandler.Preserve.`

Indeed, we have references preserved in our JSON options:

```cs
public static void AddJsonOptions(this WebApplicationBuilder builder)
    {
        builder.Services.Configure<JsonOptions>(options =>
        {
            options.SerializerOptions.ReferenceHandler = ReferenceHandler.Preserve;
            options.SerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower;
            options.SerializerOptions.Converters.Add(new JsonStringEnumConverter());
        });
    }
```

By commenting out the `ReferenceHandler.Preserve`, the open api document is created as expected.

### Expected Behavior

Support for contracts using ReferenceHandler.Preserve.

### .NET Version

9.0.100

**Comment by captainsafia** [comment]
@nicolaiarocci Thanks for filing this issue!

@eiriktsarpalis Is there a particular reason we opted not to generate schemas when `ReferenceHandler.Preserve = true`?

It seems like the schemas that Swashbuckle creates ignore the ReferenceHandler setting altogether:

```
"Person": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "nullable": true
          },
          "child": {
            "$ref": "#/components/schemas/Person"
          },
          "parent": {
            "$ref": "#/components/schemas/Person"
          }
        },
        "additionalProperties": false
      },
```

for:

```
class Person
{
    public string? Name { get; set; }
    public Person? Child { get; set; }
    public Person? Parent { get; set; }
}
```

**Comment by eiriktsarpalis** [comment]
Reference preservation alters the schema for most types, notably with collections that end up wrapping their values in JSON objects. Support for it was cut in .NET 9 for lack of time, but it's conceivable that it could be added in the future provided there is demand.

**Comment by eiriktsarpalis** [comment]
I should add that enabling reference preservation in your app carries important security ramifications. It should only be used with trusted inputs produced by System.Text.Json. In my opinion, it is not appropriate to use reference preservation in the context of web apps or Open API.

**Comment by alfonsovgs** [comment]
> I should add that enabling reference preservation in your app carries important security ramifications. It should only be used with trusted inputs produced by System.Text.Json. In my opinion, it is not appropriate to use reference preservation in the context of web apps or Open API.

Helo @eiriktsarpalis 

I haven't understood well, I have that same error but also this one:
`The depth of the generated JSON schema exceeds the JsonSerializerOptions.MaxDepth setting.`

Could you help me understand why this happens and how to avoid it?

**Comment by eiriktsarpalis** [comment]
This looks like a different error. Could you file an issue in dotnet/runtime with a standalone reproduction? Thanks.

**Comment by niltor** [comment]
I got same error when I request my json:

The depth of the generated JSON schema exceeds the JsonSerializerOptions.MaxDepth setting.

```logs
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: Error: An unhandled exception has occurred while executing the request.

System.InvalidOperationException: The depth of the generated JSON schema exceeds the JsonSerializerOptions.MaxDepth setting.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_JsonSchemaExporterDepthTooLarge()
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.MapJsonSchemaCore(GenerationState& state, JsonTypeInfo typeInfo, JsonPropertyInfo propertyInfo, JsonConverter customConverter, Nullable`1 customNumberHandling, JsonTypeInfo parentPolymorphicTypeInfo, Boolean parentPolymorphicTypeContainsTypesWithoutDiscriminator, Boolean parentPolymorphicTypeIsNonNullable, Nullable`1 typeDiscriminator, Boolean cacheResult)
   at System.Text.Json.Schema.JsonSchemaExporter.GetJsonSchemaAsNode(JsonTypeInfo typeInfo, JsonSchemaExporterOptions exporterOptions)
   at Microsoft.AspNetCore.OpenApi.OpenApiSchemaService.CreateSchema(OpenApiSchemaKey key)
   at Microsoft.AspNetCore.OpenApi.OpenApiSchemaService.GetOrCreateUnresolvedSchemaAsync(OpenApiDocument document, Type type, IServiceProvider scopedServiceProvider, IOpenApiSchemaTransformer[] schemaTransformers, ApiParameterDescription parameterDescription, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.OpenApi.OpenApiSchemaService.GetOrCreateSchemaAsync(OpenApiDocument document, Type type, IServiceProvider scopedServiceProvider, IOpenApiSchemaTransformer[] schemaTransformers, ApiParameterDescription parameterDescription, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetResponseAsync(OpenApiDocument document, ApiDescription apiDescription, Int32 statusCode, ApiResponseType apiResponseType, IServiceProvider scopedServiceProvider, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetResponsesAsync(OpenApiDocument document, ApiDescription description, IServiceProvider scopedServiceProvider, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOperationAsync(ApiDescription description, OpenApiDocument document, IServiceProvider scopedServiceProvider, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOperationsAsync(IGrouping`2 descriptions, OpenApiDocument document, IServiceProvider scopedServiceProvider, IOpenApiOperationTransformer[] operationTransformers, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOpenApiPathsAsync(OpenApiDocument document, IServiceProvider scopedServiceProvider, IOpenApiOperationTransformer[] operationTransformers, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOpenApiDocumentAsync(IServiceProvider scopedServiceProvider, HttpRequest httpRequest, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Builder.OpenApiEndpointRouteBuilderExtensions.<>c__DisplayClass0_0.<<MapOpenApi>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Http.Generated.<GeneratedRouteBuilderExtensions_g>F0399B8B15BE443123F4BECEE84B112C1912EE3F44D9DDD7BFA38E371FB917343__GeneratedRouteBuilderExtensionsCore.<>c__DisplayClass2_0.<<MapGet0>g__RequestHandler|5>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.RateLimiting.RateLimitingMiddleware.InvokeInternal(HttpContext context, EnableRateLimitingAttribute enableRateLimitingAttribute)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```

**Comment by niltor** [comment]
@eiriktsarpalis 
The situation is more complicated than expected. The example above doesn't seem to have any issues, but in my production project, errors do occur. 

I'm working hard to find the problem, and once it's identified, I'll try my best to provide a minimal reproducible code repository.

**Comment by niltor** [comment]
@eiriktsarpalis @captainsafia  

After some investigation, I provided the simplest reproducible content possible, a new asp.net core project, a simple api, and some class models. 

When a class, such as `User` in the example, has more than or equal to 8 relate classes, an error of max depth=64 will be reported. When there are less than 8, no error will be reported. 


`IssueController.cs`

```csharp

[ApiController]
[Route("[controller]")]
public class IssueController : ControllerBase
{

    [HttpGet("test-issue")]
    public ActionResult<User> TestIssue()
    {
        var user = new User() { Name = "User" };
        return user;
    }
}

public class User
{
    public Guid Id { get; set; }
    public required string Name { get; set; }
    public ICollection<Order> Orders { get; set; } = [];
    public ICollection<Product> Products { get; set; } = [];
    public ICollection<Course> Courses { get; set; } = [];
    public ICollection<Car> Cars { get; set; } = [];
    public ICollection<Hourse> Hourses { get; set; } = [];
    public ICollection<Plan> Plans { get; set; } = [];
    public ICollection<Right> Rights { get; set; } = [];
    public ICollection<Salary> Salarys { get; set; } = [];
}

public class Order { public User? User { get; set; } }
public class Product { public User? User { get; set; } }
public class Course { public User? User { get; set; } }
public class Car { public User? User { get; set; } }
public class Hourse { public User? User { get; set; } }
public class Plan { public User? User { get; set; } }
public class Right { public User? User { get; set; } }
public class Salary { public User? User { get; set; } }
```

In actual projects, there are more than 8 related entities like `User`, and dozens of them are possible. 


**I have provided a reproducible sample code repository: **

[The Issue example](https://github.com/niltor/IssueSample/tree/main/OpenApiIssue)

**Comment by eiriktsarpalis** [comment]
@niltor Thanks, but would it be possible to file a separate issue? It is unrelated to the original issue so we wouldn't want to conflate discussions of the two.

**Comment by niltor** [comment]
@eiriktsarpalis #63857
