### ISSUE TITLE
.NET 9 Blazor WebAssembly: Rendering exception due to recursive type definition

### ISSUE THREAD

**Issue by slowfight** [dotnet/aspnetcore#58954]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Upgrading my .NET 8 Blazor WebAssembly application to .NET 9 lead to frontend rendering issues. In my specific case, I'm using a type derived from Ardalis.SmartEnum to display certain information. The [SmartEnum class](https://github.com/ardalis/SmartEnum/blob/main/src/SmartEnum/SmartEnum.cs) by Ardalis uses a recursive type where it references the derived class itself as a type parameter.

The result of this behavior is a completely defective rendering of the respective page. The console states the following error:
```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not resolve field token 0x04000001, due to: Could not set up parent class, due to: Recursive type definition detected Ardalis.SmartEnum.SmartEnum`1 assembly:Ardalis.SmartEnum.dll type:SmartEnum`1 member:(null) assembly:Demo.dll type:TestEnum member:(null)
System.BadImageFormatException: Could not resolve field token 0x04000001, due to: Could not set up parent class, due to: Recursive type definition detected Ardalis.SmartEnum.SmartEnum`1 assembly:Ardalis.SmartEnum.dll type:SmartEnum`1 member:(null) assembly:Demo.dll type:TestEnum member:(null)
File name: 'Demo'
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__7_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```

### Expected Behavior

Rendering of the page succeeds as with .NET 8.

### Steps To Reproduce

1. Create a Blazor WebAssembly Standalone App (using .NET 9 PWA with example pages)
2. Include a reference to Ardalis.SmartEnum via NuGet
```csproj
<PackageReference Include="Ardalis.SmartEnum" Version="8.1.0" />
```
3. Create a new class derived from SmartEnum
```cs
using Ardalis.SmartEnum;

public class TestEnum(string name, int value) : SmartEnum<TestEnum>(name, value)
{
    public static readonly TestEnum Default = new(nameof(Default), 0);
}
```
4. Append the following code to the `Home.razor` example page
```cs
@if (Test == TestEnum.Default)
{
    <p>Value of test enum is default</p>
}

@code {
    public TestEnum Test => TestEnum.Default;
}
```
6. Build and start the application, which will result in a rending exception on load

### Exceptions (if any)

`System.BadImageFormatException`

### .NET Version

9.0

### Anything else?

Repository of Ardalis.SmartEnum: https://github.com/ardalis/SmartEnum

**Comment by soenneker** [comment]
This problem has stopped our .NET 8 -> 9 migration.

**Comment by soenneker** [comment]
@javiercn Could you or your team please take a look at this? This is blocking a large migration effort we have in progress. Thanks

**Comment by DataByte-James** [comment]
I have posted a temporary fix in the smartenum repository.  The issue is the declaration of the array

`static readonly Lazy<TEnum[]> _enumOptions =
            new Lazy<TEnum[]>(GetAllOptions, LazyThreadSafetyMode.ExecutionAndPublication);`

I changed it to the below and it now works.  Something odd there.

`static readonly Lazy<List<TEnum>> _enumOptions = new Lazy<List<TEnum>>(GetAllOptions, LazyThreadSafetyMode.ExecutionAndPublication);`

**Comment by javiercn** [comment]
@soenneker thanks for contacting us.

Does this happen during development or production.

**Comment by slowfight** [comment]
@javiercn Same for me. I can confirm that this issue exists with both local debugging and published applications (as tested with a solution being published to a Docker image using mcr.microsoft.com/dotnet/aspnet:9.0 as base).
