### ISSUE TITLE
NET 9 Build Fails After Upgrading from NET 8

### ISSUE THREAD

**Issue by VendorAttestation** [dotnet/aspnetcore#58963]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

```
InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.GenerateStaticWebAssetsDevelopmentManifest.<ComputeManifestAssets>d__19.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.GenerateStaticWebAssetsDevelopmentManifest.ComputeDevelopmentManifest(IEnumerable`1 assets, IEnumerable`1 discoveryPatterns)
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.GenerateStaticWebAssetsDevelopmentManifest.Execute()
```

### Expected Behavior

Built Project

### Steps To Reproduce

Can't for LEGAL Business Purposes 

### Exceptions (if any)

```
InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.GenerateStaticWebAssetsDevelopmentManifest.<ComputeManifestAssets>d__19.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.GenerateStaticWebAssetsDevelopmentManifest.ComputeDevelopmentManifest(IEnumerable`1 assets, IEnumerable`1 discoveryPatterns)
   at Microsoft.AspNetCore.StaticWebAssets.Tasks.GenerateStaticWebAssetsDevelopmentManifest.Execute()
```

### .NET Version

9.0.100

### Anything else?

![Image](https://github.com/user-attachments/assets/2eec51ad-4687-439e-8531-ca70c240d856)

**Comment by ivan-stp** [comment]
Duplicate of https://github.com/dotnet/aspnetcore/issues/58859

**Comment by VendorAttestation** [comment]
Closing as Dupe Issue

**Comment by ismailgundogan** [comment]
In my project, there is a file named 'WebUI.styles.css' in the wwwroot folder. When I excluded it from the project, my project worked fine.
