### ISSUE TITLE
MSB4018: The "DefineStaticWebAssetEndpoints" task failed unexpectedly.

### ISSUE THREAD

**Issue by jirisykora83** [dotnet/aspnetcore#58975]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

New StaticWebAssets make build fail. Mostly likely because of weird file names.

`1>C:\Program Files\dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets(675,5): error MSB4018: The "DefineStaticWebAssetEndpoints" task failed unexpectedly.
1>C:\Program Files\dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets(675,5): error MSB4018: System.IO.FileNotFoundException: Could not find file 'wwwroot\images\7474b9fd-5ab7-4c37-83ad-5e954a8cc7fb\GrÃ¼nerlÃ¸kka--w1920_jpg.webp'.
1>C:\Program Files\dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets(675,5): error MSB4018: File name: 'wwwroot\images\7474b9fd-5ab7-4c37-83ad-5e954a8cc7fb\GrÃ¼nerlÃ¸kka--w1920_jpg.webp'
1>C:\Program Files\dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets(675,5): error MSB4018:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
1>C:\Program Files\dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets(675,5): error MSB4018:    at System.IO.FileInfo.get_Length()
1>C:\Program Files\dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets(675,5): error MSB4018:    at Microsoft.AspNetCore.StaticWebAssets.Tasks.DefineStaticWebAssetEndpoints.GetFileLength(StaticWebAsset asset)
1>C:\Program Files\dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets(675,5): error MSB4018:    at Microsoft.AspNetCore.StaticWebAssets.Tasks.DefineStaticWebAssetEndpoints.CreateEndpoints(StaticWebAsset asset, ContentTypeProvider contentTypeMappings)
1>C:\Program Files\dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets(675,5): error MSB4018:    at Microsoft.AspNetCore.StaticWebAssets.Tasks.DefineStaticWebAssetEndpoints.Execute()
1>C:\Program Files\dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets(675,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
1>C:\Program Files\dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets(675,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()`

Is there any option to disable new StaticWebAssets for specific folder (in this case it is just "cache" as images are loaded from API and store in wwwroot). It should be an issue, just for dev build (i guess - not ready to deploy).

Even if the option for excluding folder exists, I still think this should not happen. 

### .NET Version

9.0.100

**Comment by Tornhoof** [comment]
What happens if you remove (for testing) the file with the non-ascii file name? (\GrÃ¼nerlÃ¸kka--w1920_jpg.webp)

**Comment by jirisykora83** [comment]
Then it works. I already removed all of them. Annoying is that it stops on first (not sure if it is default or my VS settings) so cleaning them manually is not fun :/

**Comment by javiercn** [comment]
@jirisykora83 thanks for contacting us.

We'll take a look, in the mean time, you can exclude those files from the `Content` item group and that should let things go through.

If you have a repro project that will definitely help.

Additionally, is there any tool that you are using to generate those files?

**Comment by javiercn** [comment]
@jirisykora83 thanks for the additional details.

So, to make sure that we understand, you are generating some cache files at runtime and placing them inside the wwwroot folder (with the idea that they can be served as assets at that point?) or does that cache gets populated as part of the build?

I imagine that what we need to do here is percent encode the url

**Comment by jirisykora83** [comment]
> [@jirisykora83](https://github.com/jirisykora83) thanks for the additional details.
> 
> So, to make sure that we understand, you are generating some cache files at runtime and placing them inside the wwwroot folder (with the idea that they can be served as assets at that point?) or does that cache gets populated as part of the build?
> 
> I imagine that what we need to do here is percent encode the url

Yes exactly. Error then happens during local build when app previously runs (download some files).

--
"I imagine that what we need to do here is percent encode the url"

I'm not sure about this because if the file is not in the folder it may work. Maybe the issue is not about the file name itself but the whole path. I am not sure.

**Comment by javiercn** [comment]
@jirisykora83 thanks for the additional details.

So, what's happening here is that on the initial build things work and on additional builds (after the app has run and generated additional files) those files are then considered static assets and cause the build to fail (given the issue above).

We will likely address this issue, however, even in that case, you should consider changing your approach. One way to do this is to create a `.cache` folder on your app at runtime, place these cache files there and serve them via `app.UseStaticFiles` with a custom `IFileProvider`.

It is best to keep your cache content separate from your static files content as they have very different lifecycles and constraints. As of .NET 9.0, a lot of build/publish time optimizations will apply to the files in the `wwwroot` folder, which likely don't make sense to your cache files.

**Comment by PerseusTheGreat** [comment]
Hi.
After updating Visual Studio from version 17.13.6 to 17.14.0, I am encountering error messages in all ASP.NET Core Razor Class Libraries containing a `wwwroot` folder with static files. These errors appear for each file within that folder.

```
1>D:\Program Files\dotnet\sdk\9.0.300\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets(693,5): error MSB4018: The "DefineStaticWebAssetEndpoints" task failed unexpectedly.
1>D:\Program Files\dotnet\sdk\9.0.300\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets(693,5): error MSB4018: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Last write time for 'D:\WorkRoot\AKA\Sources\AzureDevops\LendRollMonolith\ThirdParty\ZarinPal\wwwroot\fortawesome\css\all.css' is not defined.
1>D:\Program Files\dotnet\sdk\9.0.300\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets(693,5): error MSB4018:    at Microsoft.AspNetCore.StaticWebAssets.Tasks.StaticWebAsset.Validate()
1>D:\Program Files\dotnet\sdk\9.0.300\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets(693,5): error MSB4018:    at Microsoft.AspNetCore.StaticWebAssets.Tasks.StaticWebAsset.FromTaskItem(ITaskItem item)
1>D:\Program Files\dotnet\sdk\9.0.300\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets(693,5): error MSB4018:    at Microsoft.AspNetCore.StaticWebAssets.Tasks.DefineStaticWebAssetEndpoints.ParallelWorker.Process(Int32 i, ParallelLoopState _)
1>D:\Program Files\dotnet\sdk\9.0.300\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets(693,5): error MSB4018:    at Microsoft.AspNetCore.StaticWebAssets.Tasks.DefineStaticWebAssetEndpoints.<>c.<Execute>b__16_2(Int32 i, ParallelLoopState loop, ParallelWorker state)
1>D:\Program Files\dotnet\sdk\9.0.300\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets(693,5): error MSB4018:    at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
1>D:\Program Files\dotnet\sdk\9.0.300\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets(693,5): error MSB4018:    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
1>D:\Program Files\dotnet\sdk\9.0.300\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets(693,5): error MSB4018:    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
1>D:\Program Files\dotnet\sdk\9.0.300\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.targets(693,5): error MSB4018:    --- End of inner exception stack trace ---
```
My projects are based on .NET 9.0.4, and I have not yet updated to .NET 9.0.5.
Are there any recommendations for this circumstance?

**Comment by NKCSS** [comment]
[DefineStaticWebAssetEndpoints--FileNotFoundException.zip](https://github.com/user-attachments/files/21755079/DefineStaticWebAssetEndpoints--FileNotFoundException.zip)

Here's a minimal project to reproduce the issue (I ran into it where I had a url-encoded filename).

```csproj
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" Version="8.0.15" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\img\" />
  </ItemGroup>

</Project>
```

```csharp
// program.cs
using System.Net;
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();
app.UseStaticFiles();
app.Run();
```

then add a single image in `wwwroot\img\` named `ABNANL2A%402x.png` for instance.

**Comment by javiercn** [comment]
@jirisykora83 I tried your original repro against an RC2 build and I believe this problem has been solved.

I suspect that it is also solved in 9.0.3xx builds, since we replaced the library, we were using for blobbing. It should also work with any of the recent .NET 10.0 previews.

**Comment by arash-yahoo** [comment]
When you change your system's timezone between builds, the .NET SDK's Static Web Assets system can't properly validate file timestamps. The build system tracks the "last write time" for static files (images, JS, CSS, etc.) in the wwwroot folder to detect modifications. After a timezone change, these timestamps become invalid or undefined from the build system's perspective.
The error message you'll see looks like:
System.InvalidOperationException: Last write time for '[file-path]' is not defined.
Basically, the SDK is saying: "I can't figure out when these files were last modified because the timestamps don't make sense anymore."
The Fix
Step 1: Clean out the build cache
bash# Delete bin and obj folders from your web project
rmdir /s /q obj
rmdir /s /q bin
Step 2: Reset the file timestamps
Run this PowerShell script to update all file timestamps in wwwroot:
powershell# Navigate to your wwwroot folder
cd YourProject.Web\wwwroot

# Update timestamps for all files
Get-ChildItem -Recurse -File | ForEach-Object { $_.LastWriteTime = Get-Date }
Step 3: Rebuild
bashdotnet clean
dotnet build
Alternative quick fix: If you don't want to run the PowerShell script, just cut and paste the problematic files mentioned in the error message - this will update their timestamps.
The root cause is cached build metadata getting out of sync with actual file timestamps after the timezone change. Clearing the cache and resetting timestamps solves it.

**Comment by jirisykora83** [comment]
> Get-ChildItem -Recurse -File | ForEach-Object { $_.LastWriteTime = Get-Date }

Thank you for your help. Unfortunately it wont solve my issue.

For anyone facing same issue. Some context. App use just SSR. And I have multiple project (one dotnet app serve multiple domain and base on domain it render project). One of them was created not as `<Project Sdk="Microsoft.NET.Sdk.Razor">` but as `<Project Sdk="Microsoft.NET.Sdk.Web">`. Then most likely it try to compress  `.nuget\packages\microsoft.aspnetcore.app.internal.assets\10.0.0\_framework\blazor.web.js' ` from 2 (or more) project and failed.

This same project works before upgrading to .NET 10 (from .NET 9). It could be classified as sort of BC even if this setup is not documented so I do not know.
