### ISSUE TITLE
Blazor Server "Error: Invocation canceled due to the underlying connection being closed" when trying to change base path

### ISSUE THREAD

**Issue by BinaryFly** [dotnet/aspnetcore#58981]
## Motivation

I have a .NET 8 Blazor server app where I wish to change the base url for.
This is because I need to deploy my application to IIS and it will be locally hosted using a reverse proxy.
"Why do you need to change the base url for this?" I hear you asking.
Well eventually there should be multiple blazor applications that are all locally hosted and served via a reverse proxy on the same machine, and I distinguish these applications using their base path.

i.e. I have the following 2 apps:
| Name | Called upon via | Hosted on by IIS | Rewrite rule in IIS |
| --------| ------------------------- | ---- | --- |
| CarApp | http://localhost/root/car | http://localhost:8081 | `^root/car(.*)` -> `http://localhost:8081{R:1}` |
| HouseApp | http://localhost/root/house | http://localhost:8082 | `^root/house(.*)` -> `http://localhost:8082{R:1}` |

The thing is that my static files are not served correctly if I don't adjust the base path of my application.
Static files would be retrieved via the root of the URL where the first _html_ file loads in, which is localhost without a specified port (and thus will give back an error 404).

Say that for example the following is a snippet of my `App.razor` for my **CarApp**.

```html
    <base href="/"/>
    <link rel="stylesheet" href="app.css" />
```

Now let's say that the user calls `http://localhost/root/car`, what will happen?
1. The application will try to retrieve the `app.css` from `http://localhost/app.css`
2. This will give back a 404 since `app.css` is hosted on `http://localhost:8081/app.css` not on `http://localhost/app.css`.

A way to prevent this from happening would be to set another rewrite rule in iis to rewrite `http://localhost/app.css` (for example) to `http://localhost:8081/app.css`.
But what if we also want to load in our **HouseApp**, and this has its `app.css` link specified in the same way?
Then we would get back the `app.css` from our **CarApp** since it would be rewritten to localhost:8081.

## My Solution

To try and circumvent this issue, I tried setting the base path for blazor server as specified in [the manual](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-8.0&tabs=visual-studio#server-side-blazor). 
After setting the `base` tag in my `App.razor` the static files can be retrieved from the specified base.

```html
...
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <base href="root/subpath/" />
    <link rel="stylesheet" href="app.css" />
    <link rel="stylesheet" href="BlazorTest.styles.css" />
    <HeadOutlet @rendermode="InteractiveServer" />
</head>
...
```

Next to this I also set the pathbase using `app.UsePathBase` because some files will still look for the root of the url instead of taking on the base specified by the `base` html tag, and  `app.UsePathBase` makes these files also be hosted on the specified path base (an example of such a file would be _\_framework/blazor.web.js_).

Lastly I also used `app.MapBlazorHub` as was explained in [the documentation](https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/?view=aspnetcore-8.0&tabs=visual-studio#server-side-blazor) to make sure my signalr connection uses the right path.

```cs
// added the following to my Program.cs
var app = builder.Build();

app.UsePathBase("/mesapp/downtimes");
app.MapBlazorHub("mesapp/downtimes");
app.UseStaticFiles();
```

Using these steps would make it so static files are being served with the appropriate base path that I specified in these steps.
So where we the browser first tried to retrieve `app.css` via `http://localhost/app.css`, it will now try to retrieve it via `http://localhost/<newpathbase>/app.css`.

## Issue
When using the steps I wrote above, all the files and requests are correctly retrieved and executed (see screenshot).

![Image](https://github.com/user-attachments/assets/4e178a14-7503-468d-9ed9-d786d0efffc4)

But unfortunately, the signalR connection can't be made.

![Image](https://github.com/user-attachments/assets/fb11892f-a9be-42cf-9796-aec392bddae0)

Even when testing this locally and without using IIS or a reverse proxy, I still face the same issue.
I also tried to visit the page via /root/subpath, but then I see the following:

![Image](https://github.com/user-attachments/assets/6bece2c9-f63c-4e15-9f16-c9d9c8f35446)

At this point I have no idea what I'm doing wrong and how I can fix my issue, I also found many different issues vaguely relating to this, but that are maybe out of date or do not correctly fit my use case.

- #14065
- #22494
- #23528
- #31751

As an example I also created a [test repo](https://github.com/BinaryFly/BlazorTest) that demonstrates this issue.

**Comment by javiercn** [comment]
@BinaryFly thanks for contacting us.

If you turn on `detailedErrors` and turn the logging level all the way to `debug` what do you see on the server logs?

**Comment by BinaryFly** [comment]
@javiercn I have done as you said and I see the following in my console when running the application:

```console
dbug: Microsoft.AspNetCore.SignalR.HubConnectionContext[1]
      Completed connection handshake. Using HubProtocol 'blazorpack'.
dbug: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[1]
      Received hub invocation: InvocationMessage { InvocationId: "0", Target: "StartCircuit", Arguments: [ https://localhost:7284/root/subpath/, https://localhost:7284/, [], CfDJ8Lnh5KF+y3VAp2jbGXCbV1I3ULhVv2qbN2t/OnOPjq7ojcb3whC/+Wg1WSIjHRrmVp9jGZVOaP+xPomFoCbbxriCVE1vaUWz2jwXQzDB1uDUakT8UqkpAiv4j/3O21nK+MhhfPPzJXadywW1H4WRSgGozvNAdnBSxDCnccT8LB7z7dBUFwDS/JKr+GHimRYWTAQdVAaCKW1oUF6NKxCUKW+nJXkSuDu6qRO/PMxajt1w41DFviq8r4UqI3AAwufjB1HbZsqgpZnqXlN52WeceqDnmJsgAEkc/uq/PJthKUoOC3jQ+jEc7H+/8yUSK97xrsML5a5tpva1/AQe6LcCPssAhYJAy3rFPope0IGHAx/LPrv+Ws9Rj4rIUvB08RsWV6gyWIg+OWKkO5qoSWp4+BkAiCO19+VasVUzUFoP8QwS9+As3A/mNIO6ZteeJS0J977ChE7FqwLrbPB3TnJja1ys9DuX7QC7axxsAzv36jZY1hTN4krKOuJ8Dc9HZA00meUdiCvD3rcXh2nvggZJeFqRDR+KJt7u/k+5eJnOyqVZ ], StreamIds: [  ] }.
dbug: Microsoft.AspNetCore.Components.Server.ComponentHub[6]
      Circuit initialization failed
      System.ArgumentException: The URI 'https://localhost:7284/' is not contained by the base URI 'https://localhost:7284/root/subpath/'.
         at Microsoft.AspNetCore.Components.NavigationManager.Validate(Uri baseUri, String uri)
         at Microsoft.AspNetCore.Components.NavigationManager.Initialize(String baseUri, String uri)
         at Microsoft.AspNetCore.Components.Server.Circuits.CircuitFactory.CreateCircuitHostAsync(IReadOnlyList`1 components, CircuitClientProxy client, String baseUri, String uri, ClaimsPrincipal user, IPersistentComponentStateStore store)
         at Microsoft.AspNetCore.Components.Server.ComponentHub.StartCircuit(String baseUri, String uri, String serializedComponentRecords, String applicationState)
dbug: Microsoft.AspNetCore.SignalR.HubConnectionHandler[6]
      OnConnectedAsync ending.
```

I have also tried to visit `https://localhost:7284/root/subpath` instead but then several other files can't be served to my browser (including `blazor.web.js`)

**Comment by BinaryFly** [comment]
I already mentioned a test repo in my first message, but it seems this was overlooked.
here is [the link to the repo](https://github.com/BinaryFly/BlazorTest) again.

**Comment by javiercn** [comment]
@BinaryFly apologies, you are right, there's a repo.

We'll take a look and update the issue.

**Comment by javiercn** [comment]
@BinaryFly there are a couple of issues in how the app is defined, here is a sample of the changes

```diff
diff --git a/Components/App.razor b/Components/App.razor
index 267cc7f..5989267 100644
--- a/Components/App.razor
+++ b/Components/App.razor
@@ -4,7 +4,7 @@
 <head>
     <meta charset="utf-8" />
     <meta name="viewport" content="width=device-width, initial-scale=1.0" />
-    <base href="/root/subpath/" />
+    <base href="root/subpath/" />
     <link rel="stylesheet" href="app.css" />
     <link rel="stylesheet" href="BlazorTest.styles.css" />
     <HeadOutlet @rendermode="InteractiveServer" />
diff --git a/Program.cs b/Program.cs
index d0203d0..024635c 100644
--- a/Program.cs
+++ b/Program.cs
@@ -6,31 +6,25 @@ var builder = WebApplication.CreateBuilder(args);
 builder.Services.AddRazorComponents()
     .AddInteractiveServerComponents();
 
-var root = builder.Build();
+var app = builder.Build();
 
-root.Map("/root/subpath", app =>
+app.UsePathBase("/root/subpath");
+app.MapBlazorHub("root/subpath");
+
+// Configure the HTTP request pipeline.
+if (!app.Environment.IsDevelopment())
 {
-    app.UsePathBase("/root/subpath/");
-    app.UseRouting();
-
-    // Configure the HTTP request pipeline.
-    if (!root.Environment.IsDevelopment())
-    {
-        app.UseExceptionHandler("/Error", createScopeForErrors: true);
-        // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
-        app.UseHsts();
-    }
-
-    app.UseHttpsRedirection();
-
-    app.UseStaticFiles();
-    app.UseAntiforgery();
-
-    app.UseEndpoints(endpoints =>
-    {
-        endpoints.MapRazorComponents<App>()
-            .AddInteractiveServerRenderMode();
-    });
-});
-
-root.Run();
+    app.UseExceptionHandler("/Error", createScopeForErrors: true);
+    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
+    app.UseHsts();
+}
+
+app.UseHttpsRedirection();
+
+app.UseStaticFiles();
+app.UseAntiforgery();
+
+app.MapRazorComponents<App>()
+    .AddInteractiveServerRenderMode();
+
+app.Run();
```

**Comment by javiercn** [comment]
In the default builder, routing is wired-up implicitly, so it goes before `app.UsePathBase("/root/subpath");` which was messing things up, that and your base tag was wrong (missing a leading `/`)

```diff
diff --git a/Components/App.razor b/Components/App.razor
index 5989267..267cc7f 100644
--- a/Components/App.razor
+++ b/Components/App.razor
@@ -4,7 +4,7 @@
 <head>
     <meta charset="utf-8" />
     <meta name="viewport" content="width=device-width, initial-scale=1.0" />
-    <base href="root/subpath/" />
+    <base href="/root/subpath/" />
     <link rel="stylesheet" href="app.css" />
     <link rel="stylesheet" href="BlazorTest.styles.css" />
     <HeadOutlet @rendermode="InteractiveServer" />
diff --git a/Program.cs b/Program.cs
index 024635c..6fe1869 100644
--- a/Program.cs
+++ b/Program.cs
@@ -9,7 +9,7 @@ builder.Services.AddRazorComponents()
 var app = builder.Build();
 
 app.UsePathBase("/root/subpath");
-app.MapBlazorHub("root/subpath");
+app.UseRouting();
 
 // Configure the HTTP request pipeline.
 if (!app.Environment.IsDevelopment())
```

**Comment by simonvanes** [comment]
Sorry to dredge this back up,  but I'm still having this issue on .NET 9,  having tried all the suggested changes above i still receive the following error.

Application works fine without the sub path and I've tried variations of trailing / or not,  nothing seems to work.  No clues in the log even with detailed errors enabled.

![Image](https://github.com/user-attachments/assets/c9ce0f72-12d6-46f7-b080-1f8d3ec4dcee)

![Image](https://github.com/user-attachments/assets/e583bbea-1fe9-4987-b5b3-e37179388ed6)

[2025-04-29T12:04:14.398Z] Error: The circuit failed to initialize.
[2025-04-29T12:04:14.399Z] Information: Connection disconnected.
Error: Invocation canceled due to the underlying connection being closed.
Stack trace:
 >  at vn._connectionClosed (http://localhost:8080/rfe/_framework/blazor.web.js:1:66928)
 >    at constructor.connection.onclose (http://localhost:8080/rfe/_framework/blazor.web.js:1:56836)
 >    at An._stopConnection (http://localhost:8080/rfe/_framework/blazor.web.js:1:92487)
 >    at _startTransport.features.reconnect.transport.onclose (http://localhost:8080/rfe/_framework/blazor.web.js:1:90173)
 >    at Rn._close (http://localhost:8080/rfe/_framework/blazor.web.js:1:81916)
 >    at Rn.stop (http://localhost:8080/rfe/_framework/blazor.web.js:1:81536)
 >    at An._stopInternal (http://localhost:8080/rfe/_framework/blazor.web.js:1:84867)
 >    at async An.stop (http://localhost:8080/rfe/_framework/blazor.web.js:1:84677)
 >    at async vn.stop (http://localhost:8080/rfe/_framework/blazor.web.js:1:59872)
 >    at async Uo.disconnect (http://localhost:8080/rfe/_framework/blazor.web.js:1:137403)
The program '[10708] XXXX' has exited with code 4294967295 (0xffffffff).
