### ISSUE TITLE
Dotnet watch falls over frequently with "An item with the same key has already been added"

### ISSUE THREAD

**Issue by paulguz-datapa** [dotnet/aspnetcore#59018]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Since upgrading our ASP.Net Core projects to .Net 9 (but leaving the others alone for now), we are experiencing the following error when running dotnet watch:

dotnet watch ❌ System.ArgumentException: An item with the same key has already been added. Key: 
C:\xxx\yyy\zzz\aaa\Language.csproj
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Microsoft.DotNet.Watcher.Tools.IncrementalMSBuildWorkspace.UpdateProjectConeAsync(String rootProjectPath, CancellationToken cancellationToken)
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watcher.HotReloadDotNetWatcher.WatchAsync(CancellationToken shutdownCancellationToken)
   at Microsoft.DotNet.Watcher.Program.RunAsync()
dotnet watch ❌ An unexpected error occurred

Language.csproj is a an assembly containing resource files.

Dotnet watch falls over at this point.  It happens very frequently, making Hot Reload impossible.

### Expected Behavior

Dotnet watch runs without failure

### Exceptions (if any)

 System.ArgumentException: An item with the same key has already been added

### .NET Version

9.0

**Comment by paulguz-datapa** [comment]
I also see this warning in the Command Prompt: 

dotnet watch ⚠ msbuild: [Warning] Found project reference without a matching metadata reference: C:\xxx\yyy\zzz\aaa\Language.csproj

dotnet watch ⏳ Waiting for a file to change before restarting dotnet...

I don't know if the warning is related to the error in the subject of this Issue, or if the "waiting for file to change" problem is related to the warning (but it only appears after the warning occurs)

**Comment by jofford** [comment]
Also noticing this when pressing Ctrl+R to reload in the CLI. I am running an api and Blazor site simultaneously via 'dotnet watch' but wasn't a problem in .NET 8

**Comment by paulguz-datapa** [comment]
This may not be restricted to dotnet watch in the command line.  I also get Hot Reload build failures when running via Visual Studio.

**Comment by paulguz-datapa** [comment]
Like @jofford, we are also have a Blazor (Wasm) project and an ASP.Net Core API project (which references the Blazor project)

**Comment by eldo-xy** [comment]
Also having this annoying issue, doing random stuff with the projects causes the watch to just crash

**Comment by paul-green** [comment]
Me too;
- Run dotnet watch
- Make a change to .razor file
- terminal says :  **File deleted: .\(path to razor file)**
- The change isn't reflected in the UI
- A few seconds later; **Waiting for a file to change before restarting dotnet...**
- I make another change, save it and get :  **System.ArgumentException: An item with the same key has already been added. Key: 5529**

Then dotnet watch crashes out. This is worse than pre-upgrade to latest (sigh)

**Comment by timheuer** [comment]
@tmat should this move to dotnet/sdk?

**Comment by dbondar-dev** [comment]
Possible temporary solution is using previous dotnet version. It can be done by adding **global.json** file in your projects folder with previous working dotnet version:

`{
  "sdk": {
    "version": "8.0.0"
  }
}`

(https://learn.microsoft.com/en-us/dotnet/core/versions/selection#the-sdk-uses-the-latest-installed-version)
