### ISSUE TITLE
.NET 9  causes CryptographicException when loading a certificate from a PFX file

### ISSUE THREAD

**Issue by jimitndiaye** [dotnet/aspnetcore#59300]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Since upgrading to .NET 9 my application wouldn't start and the exception given indicated an error occurred while loading the SSL certificate. During development, I use a PFX certificate file with a password set in user secrets. Downgrading back to .NET 8 with no other code/configuration changes fixed the issue.

In trying to isolate the problem I created a simple .NET 9 ASPNET core webapi using ```dotnet new webapi``` and set it up to use the same certificate - got the same error. I repeated the same steps but this time on .NET 8 with ```dotnet new webapi -f net8.0``` - it launched sucessfully.

Just in case it is relevant, I'm running on Windows 10.

### Expected Behavior

.NET 9 should work the same way as .NET 8 in launch Kestrel configured to use an SSL certificate from a PFX file. Currently, with exact same configuration, .NET 8 works but .NET 9 doesn't

### Steps To Reproduce

1. Open a new PowerShell window with administrator privileges and execute the following command to generate a certificate:
```
New-SelfSignedCertificate -Subject TestCert -DnsName localhost -CertStoreLocation Cert:\LocalMachine\My -KeyExportPolicy Exportable
```
2. Export the created certificate to a PFX file:
```
$mypwd = ConvertTo-SecureString -String '1234' -Force -AsPlainText
Get-ChildItem -Path Cert:\LocalMachine\My | where { $_.subject -eq "CN=TestCert"} |
    Export-PfxCertificate -FilePath .\cert.pfx -Password $mypwd
```
Or if you prefer, use the CertMgr tool to export the certificate to a PFX file.
4. Open any terminal as a regular user in an empty directory and create a new .NET 9 ASP.NET Core Web API project:
```
mkdir net9-api
cd net9-api
dotnet new webapi -f net9.0
```
5. Edit appsettings.Development.json and add the following section, where cert.pfx is the name of the exported pfx file. Make sure the exported PFX file is placed in the root of the project folder:
```
  "Kestrel": {
    "Certificates": {
      "Default": {
        "Path": "cert.pfx",
        "Password": "1234"
      }
    }
  }
```
 6. Run the app.
 7. Start up fails with a ```System.Security.Cryptography.CryptographicException```
 8. Create a new folder for the .NET 8 version of the api:
 ```
mkdir net8-api
cd net8-api
dotnet new webapi -f net8.0
```
9. Edit appsettings.Development.json as in step 5
10. Run the .NET 8 version of the app
11. The app launches successfully

### Exceptions (if any)

Microsoft.Extensions.Hosting.Internal.Host: Error: Hosting failed to start

System.Security.Cryptography.CryptographicException: Access denied.
   at System.Security.Cryptography.X509Certificates.X509CertificateLoader.ImportPfx(ReadOnlySpan`1 data, ReadOnlySpan`1 password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509CertificateLoader.LoadPkcs12NoLimits(ReadOnlyMemory`1 data, ReadOnlySpan`1 password, X509KeyStorageFlags keyStorageFlags, Pkcs12Return& earlyReturn)
   at System.Security.Cryptography.X509Certificates.X509CertificateLoader.LoadPkcs12(ReadOnlyMemory`1 data, ReadOnlySpan`1 password, X509KeyStorageFlags keyStorageFlags, Pkcs12LoaderLimits loaderLimits)
   at System.Security.Cryptography.X509Certificates.X509CertificateLoader.LoadFromFile[T](String path, ReadOnlySpan`1 password, X509KeyStorageFlags keyStorageFlags, Pkcs12LoaderLimits loaderLimits, LoadFromFileFunc`1 loader)
   at System.Security.Cryptography.X509Certificates.X509CertificateLoader.LoadPkcs12PalFromFile(String path, ReadOnlySpan`1 password, X509KeyStorageFlags keyStorageFlags, Pkcs12LoaderLimits loaderLimits)
   at System.Security.Cryptography.X509Certificates.CertificatePal.FromBlobOrFile(ReadOnlySpan`1 rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Certificates.CertificateConfigLoader.LoadCertificate(CertificateConfig certInfo, String endpointName)
   at Microsoft.AspNetCore.Server.Kestrel.Core.TlsConfigurationLoader.LoadDefaultCertificate(ConfigurationReader configurationReader)
   at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.Reload()
   at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.LoadInternal()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__14_1(IHostedService service, CancellationToken token)
   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)

### .NET Version

9.0.100

**Comment by jimitndiaye** [comment]
Incidentally, the exact same certificate works on .NET 9 if accessed via the certificate store rather than a PFX file. A configuration like below actually works:
```json
  "Kestrel": {
    "Certificates": {
      "Default": {
        "Store": "My",
        "Location": "LocalMachine",
        "Subject": "TestCert",
        "AllowInvalid": true
      }
    }
  }
```

**Comment by BrennanConroy** [comment]
Looks like a dupe of https://github.com/dotnet/runtime/issues/110217

I don't think it has anything to do with ASP.NET Core.

**Comment by jimitndiaye** [comment]
> Looks like a dupe of https://github.com/dotnet/runtime/issues/110217
> 
> I don't think it has anything to do with ASP.NET Core.

Looks like you may be right.

**Comment by jeffhandley** [comment]
Thank you for the detailed repro steps, @jimitndiaye! We will investigate this week.

**Comment by mjasin** [comment]
I have this same issue. After upgrade .net from 8 to 9 on Ubuntu 24.04.1 I receive error message _An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information_

```
Dec 07 19:18:15 www.dudik.pl dotnet-grandnode[519]:       System.Security.Cryptography.CryptographicException: An error occurred while trying to encrypt the provided data. Refer to the inner exception for more information.
Dec 07 19:18:15 www.dudik.pl dotnet-grandnode[519]:        ---> System.UnauthorizedAccessException: Access to the path '/App_Data' is denied.
Dec 07 19:18:15 www.dudik.pl dotnet-grandnode[519]:        ---> System.IO.IOException: Permission denied
Dec 07 19:18:15 www.dudik.pl dotnet-grandnode[519]:          --- End of inner exception stack trace ---
Dec 07 19:18:15 www.dudik.pl dotnet-grandnode[519]:          at System.IO.FileSystem.CreateParentsAndDirectory(String fullPath, UnixFileMode unixCreateMode)
Dec 07 19:18:15 www.dudik.pl dotnet-grandnode[519]:          at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
Dec 07 19:18:15 www.dudik.pl dotnet-grandnode[519]:          at System.IO.DirectoryInfo.Create()
Dec 07 19:18:15 www.dudik.pl dotnet-grandnode[519]:          at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElementsCore()+MoveNext()
Dec 07 19:18:15 www.dudik.pl dotnet-grandnode[519]:          at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
Dec 07 19:18:15 www.dudik.pl dotnet-grandnode[519]:          at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
Dec 07 19:18:15 www.dudik.pl dotnet-grandnode[519]:          at Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository.GetAllElements()
Dec 07 19:18:15 www.dudik.pl dotnet-grandnode[519]:          at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.GetAllKeys()
Dec 07 19:18:15 www.dudik.pl dotnet-grandnode[519]:          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider.CreateCacheableKeyRingCore(DateTimeOffset now, IKey keyJustAdded)
Dec 07 19:18:15 www.dudik.pl dotnet-grandnode[519]:          at System.Threading.Tasks.Task`1.InnerInvoke()
Dec 07 19:18:15 www.dudik.pl dotnet-grandnode[519]:          at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by krwq** [comment]
@mjasin can you share steps how to create your cert in https://github.com/dotnet/runtime/issues/110217 ? If it's the same as described in this issue then not necessary

**Comment by PatrickHofman** [comment]
Same issue here using the PFX generated from a PowerShell script similar as in the original post. Loading the certificate fails when using the below code, which is similar to the code used by ASP.NET Core:

    X509Certificate x509Certificate = new X509Certificate(@"C:\ws\dev.pfx", "test12345");

The certificate does load using:

    X509Certificate2 x509Certificate = X509CertificateLoader.LoadPkcs12FromFile(@"C:\ws\dev.pfx", "test12345");

**Comment by PatrickHofman** [comment]
@BrennanConroy I don't think this one should be closed. The constructor that is used by ASP.NET Core according to the call stack is deprecated and should not be used any more.

It is weird though that the faulting line in the current code uses `X509Certificate2` instead of `X509Certificate` (see https://github.com/dotnet/aspnetcore/blame/main/src/Servers/Kestrel/Core/src/Internal/Certificates/CertificateConfigLoader.cs#L74). Is the latest version of this code used in the packaged used by ASP.NET Core?

**Comment by BrennanConroy** [comment]
😯 good catch. Looks like we have https://github.com/dotnet/aspnetcore/issues/56817 for this though.

**Comment by ststeiger** [comment]
Also, it fails only with X509CertificateLoader - if used directly, it works. 

```

            string[] letsEncryptDomains = new string[] {
                  "localhost"
            };

            bool isDev = true;
            string[] altNames = SelfSigned.GetAlternativeNames(isDev ? letsEncryptDomains : new string[0]);
            byte[] pfxBytes = SelfSigned.CreateSelfSignedCertificate(altNames, LetsEncryptData.DEFAULT_PASSWORD);


            // this is not the same
            System.Security.Cryptography.X509Certificates.X509Certificate2 cert = 
                System.Security.Cryptography.X509Certificates.X509CertificateLoader.LoadPkcs12(
                data: pfxBytes,
                password: LetsEncryptData.DEFAULT_PASSWORD,
                // keyStorageFlags: System.Security.Cryptography.X509Certificates.X509KeyStorageFlags.EphemeralKeySet
                keyStorageFlags: System.Security.Cryptography.X509Certificates.X509KeyStorageFlags.PersistKeySet
            );

             // this works
            // cert =
    new System.Security.Cryptography.X509Certificates.X509Certificate2(pfxBytes, LetsEncryptData.DEFAULT_PASSWORD);


            builder.WebHost.ConfigureKestrel(serverOptions =>
            {
                // HTTP on port 5005
                // serverOptions.Listen(System.Net.IPAddress.Any, 5005);

                // HTTPS on port 5006 with certificate
                serverOptions.Listen(System.Net.IPAddress.Any, 5006, listenOptions =>
                {
                    listenOptions.UseHttps(cert);
                });
            });

```

**Comment by ststeiger** [comment]
Aha, got it: 
keyStorageFlags: System.Security.Cryptography.X509Certificates.X509KeyStorageFlags.Exportable

then it works.
