### ISSUE TITLE
Unexpected error when using records

### ISSUE THREAD

**Issue by TimSon777** [dotnet/aspnetcore#59384]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Hello! We have a record like this

```c#
public record TemplateRequirementsValidationRequestDto(
	[property: DataMember(Name = "templateRequirements")]
	string TemplateRequirements,
	[property: DataMember(Name = "mailingKind")]
	MailingKind MailingKind,
	[property: DataMember(Name = "recipientsFileInternalId")]
	int? RecipientsFileInternalId);
```

which we use in the endpoint like this

```c#
[HttpPost("do-smth")]
public async Task<JsonResult> DoSmth(
	[FromBody] TemplateRequirementsValidationRequestDto request)
{
    // ...
}
```

this code works stably and has been live for a whole year

Our application has several instances (2) with a balancer that proxies requests to one of these instances. And one day we saw this error: 

`InvalidOperationException: No property found that maps to constructor parameter 'RecipientsFileInternalId' for type 'Services.Core.TemplateRequirementsValidationRequestDto'. Validation requires that each bound parameter of a record type's primary constructor must have a property to read the value.`

We did a little research and found out that the error occurred only on one instance, while the other instance worked without this error. Therefore, half of the requests completed successfully. After restarting the problematic instance, the errors disappeared

This error was introduced into the framework in this [PR](https://github.com/dotnet/aspnetcore/pull/23976) with the addition of support for records and appears in [this](https://github.com/dotnet/aspnetcore/blob/d088530dced8d71ed81f322fecfcf6b03ae3d9de/src/Mvc/Mvc.Core/src/ModelBinding/Validation/DefaultComplexObjectValidationStrategy.cs#L99) place

[The tests](https://github.com/dotnet/aspnetcore/blob/e2a857c8ccda4dcfac3381a166faaf3542d85c62/src/Mvc/Mvc.Core/test/ModelBinding/Validation/DefaultComplexObjectValidationStrategyTest.cs#L162) are not very informative in this particular place - so it was not possible to understand why this error occurred, perhaps there is a race somewhere or something else. Help me figure it out!

### Expected Behavior

The error does not occur at random times

### Steps To Reproduce

No steps

### Exceptions (if any)

InvalidOperationException: No property found that maps to constructor parameter 'RecipientsFileInternalId' for type 'Services.Core.TemplateRequirementsValidationRequestDto'. Validation requires that each bound parameter of a record type's primary constructor must have a property to read the value.

### .NET Version

8.0.x

**Comment by captainsafia** [comment]
@TimSon777 Thanks for filing this issue and taking the time to put in some leg work with the investigation.

> We did a little research and found out that the error occurred only on one instance, while the other instance worked without this error. Therefore, half of the requests completed successfully. After restarting the problematic instance, the errors disappeared


Has the error emerged again on the same instance after the restart? Has it never manifested on the other instance?

**Comment by TimSon777** [comment]
Hello! We have diagnosed this error only once on one instance. After restarting this instance, the error did not appear again. Our instances themselves are periodically restarted (when we roll out new code, for example), and everything always works fine in them. The endpoint, which responded with an error, has not changed for a year. It looks like a very rare race. I will add a detail: the error started immediately after the launch of the problematic instance and ended after its restart

**Comment by mikeronayne** [comment]
> We have diagnosed this error only once on one instance. After restarting this instance, the error did not appear again

+1 for another victim of this

**Comment by rocklan** [comment]
+1 for another victim of this - this needs a patch ASAP! Don't use `records` for your DTO's people!

**Comment by sterlyagovandrey** [comment]
Another victim, but with a deterministic repro of the failure mode and, I think, a concrete suspect.

Our fingerprint matches @TimSon777 exactly: .NET 9 (`Microsoft.AspNetCore.Mvc` 9.0.x), a `[FromBody]` positional record nested three levels deep in the request DTO, **one pod out of six** behind a load balancer, first exception **59 seconds after that pod started**, ~44% of requests to the endpoint failing for 18 minutes while the other five pods stayed clean, gone the moment the pod was killed. The endpoint and the record had not changed in months.

I cannot reproduce the *timing*. But the failure mode is fully reproducible, and it narrows the search.

## What the exception can only mean

The throw in [`DefaultComplexObjectValidationStrategy`](https://github.com/dotnet/aspnetcore/blob/release/9.0/src/Mvc/Mvc.Core/src/ModelBinding/Validation/DefaultComplexObjectValidationStrategy.cs) fires when

```csharp
if (!_modelMetadata.BoundConstructorParameterMapping.TryGetValue(parameter, out var property))
```

misses. That dictionary is built exactly once, in [`ModelMetadata.CalculateRecordTypeConstructorDetails()`](https://github.com/dotnet/aspnetcore/blob/release/9.0/src/Mvc/Mvc.Abstractions/src/ModelBinding/ModelMetadata.cs), and cached in `_parameterMapping` for the lifetime of the `ModelMetadata` instance — i.e. for the lifetime of the process. So whatever goes wrong goes wrong **once**, and is then latched forever. That is precisely what @gearsetdave described: "the instance is broken because these things get cached".

Two consequences worth noting, because they explain the confusing symptoms:

- The broken instance keeps serving successful requests. The enumerator only reaches the lookup when the container instance is non-null, so any request that omits that nested object validates fine. On our broken pod: **1716 × HTTP 200 alongside 1343 × HTTP 500**, in the same 25-minute window. It looks payload-dependent, which sends you hunting for a bad request. It isn't.
- The mapping is built lazily on the first request that actually carries the type — not at startup. So the race window is "first *concurrent* use of that type", which is why it tends to hit seconds-to-minutes after an instance starts taking traffic, and why it is so rare.

## The suspect: the cached hash code, first initialised inside the mapping loop

`ModelMetadata` caches its hash code in a **`private int? _hashCode`**, lazily, with no synchronisation:

```csharp
public override int GetHashCode()
{
    // Normally caching the hashcode would be dangerous, but Identity is deeply immutable so this is safe.
    if (_hashCode == null)
    {
        _hashCode = Identity.GetHashCode();
    }

    return _hashCode.Value;
}
```

The immutability of `Identity` is not the problem. The problem is that `Nullable<int>` is **two fields**, the write is neither atomic nor volatile, and the read is two separate loads (`_hashCode == null`, then `_hashCode.Value`). The JIT is free to emit the `hasValue` store before the `value` store. If it does, a concurrent reader can observe `hasValue == true` with `value == 0` and `GetHashCode()` returns **0** instead of the real hash. Note this needs no weak memory model — it is store *order chosen by the codegen*, which x86-TSO then faithfully exposes. (Our nodes are all `x86_64`, so for us any explanation that relies on store-store reordering is ruled out; see the second variant below.)

Now look at where that first initialisation happens. `CalculateRecordTypeConstructorDetails` does:

```csharp
foreach (var parameter in boundParameters)
{
    var property = Properties.FirstOrDefault(p => ...);
    if (property != null)
    {
        parameterMapping[parameter] = property;   // <-- first GetHashCode() of this parameter, under contention
        propertyMapping[property] = parameter;
    }
}
```

Two threads that both see `_recordTypeConstructorDetailsCalculated == false` both run this loop, and the very first initialisation of every parameter's `_hashCode` happens inside it, concurrently. If one of them inserts with a torn `0`, that entry lands in the wrong bucket. Once `_hashCode` settles to the real value, every later `TryGetValue` misses — even though `Equals` (which compares `Identity`, not the hash) would happily match. The dictionary is then cached for the process lifetime.

I have not disassembled `GetHashCode` to confirm which store order .NET 9 emits on x64. If it emits a single 8-byte store, this variant is impossible and the second one below becomes the candidate. Either way the code is racy on paper.

## Second variant: `Properties` observed before its contents

`DefaultModelMetadata.Properties` publishes a non-volatile `_properties`, and `DefaultModelMetadataProvider.GetMetadataForProperties` fills `cacheEntry.Details.Properties` under an explicit comment: *"We're relying on a safe race-condition for Properties - take care only to set the value once the properties are fully-initialized."* On a weak memory model (arm64) a reader can observe the collection reference before all of its elements are visible. On x86-TSO it cannot, so this cannot be our incident — but it may be someone else's.

What makes this variant nasty is not the memory model, it is the line above: a parameter that finds no matching property is **silently skipped**. No exception, no log — just a missing dictionary entry that then gets cached forever, to be reported minutes later from a completely different call site.

## Repro

Both variants reproduce the production exception verbatim, and — the important part — **keep throwing after the metadata is restored to a perfectly correct state**, which is what makes this a permanent outage rather than a transient blip. net9.0, xunit, no ASP.NET host, reflection used only to simulate the two divergent states:

```csharp
using System.ComponentModel.DataAnnotations;
using System.Reflection;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Abstractions;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.ModelBinding.Metadata;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.AspNetCore.Routing;

using Microsoft.Extensions.DependencyInjection;

using Xunit;

public sealed record ReproDto(
    [Range(0, 10)] int First,
    string Second,
    int? Third);

public class ReproTests
{
    private const string LostParameterName = "Third";

    private static IObjectModelValidator _validator = null!;
    private static IModelMetadataProvider _metadataProvider = null!;

    private static void Arrange()
    {
        var services = new ServiceCollection();
        services.AddLogging();
        services.AddControllers();
        var serviceProvider = services.BuildServiceProvider();

        _validator = serviceProvider.GetRequiredService<IObjectModelValidator>();
        _metadataProvider = serviceProvider.GetRequiredService<IModelMetadataProvider>();
    }

    private static void Validate()
        => _validator.Validate(
            new ActionContext(new DefaultHttpContext(), new RouteData(), new ActionDescriptor()),
            validationState: null,
            prefix: string.Empty,
            model: new ReproDto(1, "second", 3));

    private static void SetField(object target, Type declaringType, string fieldName, object? value)
        => declaringType
            .GetField(fieldName, BindingFlags.Instance | BindingFlags.NonPublic)!
            .SetValue(target, value);

    [Fact]
    public void VariantA_TornHashCode()
    {
        Arrange();
        Validate();

        var metadata = _metadataProvider.GetMetadataForType(typeof(ReproDto));
        var lostParameter = metadata.BoundConstructor!.BoundConstructorParameters!
            .Single(parameter => parameter.ParameterName == LostParameterName);

        var intactHashCode = lostParameter.GetHashCode();
        SetField(lostParameter, typeof(ModelMetadata), "_hashCode", 0);
        SetField(metadata, typeof(ModelMetadata), "_recordTypeConstructorDetailsCalculated", false);
        Validate();
        SetField(lostParameter, typeof(ModelMetadata), "_hashCode", intactHashCode);

        var exception = Assert.Throws<InvalidOperationException>(Validate);
        Assert.Contains($"constructor parameter '{LostParameterName}'", exception.Message);
    }

    [Fact]
    public void VariantB_PropertyNotYetVisible()
    {
        Arrange();

        var metadata = _metadataProvider.GetMetadataForType(typeof(ReproDto));
        var intactProperties = metadata.Properties;

        SetField(
            metadata,
            typeof(DefaultModelMetadata),
            "_properties",
            new ModelPropertyCollection(intactProperties.Where(property => property.Name != LostParameterName)));
        Assert.Throws<InvalidOperationException>(Validate);
        SetField(metadata, typeof(DefaultModelMetadata), "_properties", intactProperties);

        var exception = Assert.Throws<InvalidOperationException>(Validate);
        Assert.Contains($"constructor parameter '{LostParameterName}'", exception.Message);
    }
}
```

Stack trace from the repro, identical to production down to the throw site (production has `ParameterBinder.BindModelAsync` as the outermost frame instead of `ObjectModelValidator.Validate`, because the repro calls the validator directly):

```
System.InvalidOperationException : No property found that maps to constructor parameter 'Third' for type 'ReproDto'.
Validation requires that each bound parameter of a record type's primary constructor must have a property to read the value.
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.DefaultComplexObjectValidationStrategy.Enumerator.MoveNext()
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitChildren(IValidationStrategy strategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitComplexType(IValidationStrategy defaultStrategy)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Validation.ValidationVisitor.VisitImplementation(ModelMetadata& metadata, String& key, Object model)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ObjectModelValidator.Validate(ActionContext actionContext, ValidationStateDictionary validationState, String prefix, Object model)
```

## Suggested fixes

Whatever the triggering race turns out to be, the design choice that converts a microsecond of inconsistency into a permanent outage is the silent skip. Cheapest useful changes, roughly in order of value:

1. **Don't latch a mapping you know is incomplete.** In `CalculateRecordTypeConstructorDetails`, if a bound parameter finds no matching property, either throw right there or leave `_recordTypeConstructorDetailsCalculated` false so the next call rebuilds. Today the inconsistency is cached and reported later from an unrelated request. This alone downgrades the bug from "instance is dead until restarted" to "one request fails".
2. **Make the lazy inits actually thread-safe.** Build the mapping under a lock (or via `Interlocked.CompareExchange` on a single state object), and replace `int? _hashCode` with an `int` plus a separate flag, or compute it eagerly — the current pattern cannot be made correct by reasoning about `Identity` being immutable.
3. **Fix the publication order.** `_recordTypeConstructorDetailsCalculated = true` is assigned **before** `_parameterMapping` and `_boundConstructorPropertyMapping`. A racing reader that early-returns on the flag can therefore observe a `null` mapping and get a `NullReferenceException` out of `TryGetValue` — a different, so-far-unreported flavour of the same bug.

## Question for the other reporters

@TimSon777 @gearsetdave @mikeronayne @rocklan — two data points would discriminate between the variants:

1. **CPU architecture** of the affected instances (x64 vs arm64). Variant B requires a weak memory model; Variant A does not.
2. **Position of the named parameter** in the primary constructor. @TimSon777 lost `RecipientsFileInternalId`, the 3rd of 3; we lost the 7th of 8. If it is always one of the last parameters, that points at Variant B (elements published in order); if it is uniformly distributed, at Variant A.

Happy to run further experiments — this is cheap for us to test now that the failure mode is reproducible.

**Comment by sterlyagovandrey** [comment]
> [!WARNING]
> **The conclusion of this comment is wrong. The mechanism I retract below turns out to be the actual cause.**
> I disassembled Tier0, but this method is never JIT-compiled under default settings — it is ReadyToRun-precompiled, and the optimized codegen *does* publish `hasValue` before the payload as two separate stores. See the resolution, with a reproduction on real x86-64: https://github.com/dotnet/aspnetcore/issues/59384#issuecomment-5201927290
>
> Keeping the body below unedited for the record. The Tier0 disassembly, the `Nullable<int>` layout and the incident evidence in it are all still accurate — only the inference I drew from them was not.

---

**Correction to my previous comment: the mechanism I proposed for Variant A is wrong.** I disassembled it, and the codegen does not do what I assumed. Details below, plus one new piece of evidence that is independent of any mechanism.

## What I got wrong

I claimed the JIT is free to emit the `hasValue` store before the `value` store when writing `private int? _hashCode`, which would let a concurrent reader observe `hasValue == true` with `value == 0`. That is not what happens.

`ModelMetadata:GetHashCode()` on x64 (`DOTNET_ReadyToRun=0 DOTNET_JitNoInline=1 DOTNET_JitDisasm='GetHashCode'`, .NET 9, Tier0 — the tier that runs during the first seconds after process start, which is when this bug bites):

```asm
; Assembly listing for method Microsoft.AspNetCore.Mvc.ModelBinding.ModelMetadata:GetHashCode():int:this (Tier0)
       call     [System.Nullable`1[int]:get_HasValue():ubyte:this]
       test     eax, eax
       jne      SHORT G_M000_IG03
       call     [Microsoft.AspNetCore.Mvc.ModelBinding.ModelMetadata:get_Identity()...]
       call     [Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.ModelMetadataIdentity:GetHashCode():int:this]
       mov      dword ptr [rbp-0x3C], eax
       mov      esi, dword ptr [rbp-0x3C]
       lea      rdi, [rbp-0x38]
       call     [System.Nullable`1[int]:.ctor(int):this]      ; built in a stack local
       mov      rax, gword ptr [rbp-0x08]
       mov      rcx, qword ptr [rbp-0x38]
       mov      qword ptr [rax+0x5C], rcx                     ; ONE 8-byte store
G_M000_IG03:
       call     [System.Nullable`1[int]:get_Value():int:this]
```

The `Nullable<int>` is constructed in a stack local and copied into the field with a **single 8-byte `mov`**. There is no field-store ordering to get wrong. Tier1 and FullOpts do the same thing. So scratch that mechanism.

For the record, the layout: `sizeof(int?) == 8`, and for `value = 0x11223344, hasValue = true` the bytes are `01 00 00 00 44 33 22 11` — `hasValue` at offset 0, `value` at offset 4.

## What survives, much weaker

The single 8-byte store is to offset `0x5C` = 92, i.e. `4 mod 8` — it is **misaligned**. Per the Intel SDM, atomicity is guaranteed for unaligned accesses of 8 bytes or less only while the access stays within a cache line; accesses split across cache lines are not guaranteed atomic. Object addresses are 8-byte aligned, so this store straddles a 64-byte line exactly when the object happens to land at `≡ 32 (mod 64)` — roughly one allocation in eight. So a torn `_hashCode` is still architecturally possible, but it is conditional on allocation alignment and I have **not** demonstrated it. Treat it as a hypothesis, not a finding.

Two more caveats on the above: in a normal run this method executes as ReadyToRun precompiled code and is never JIT-compiled at all (I had to set `DOTNET_ReadyToRun=0` to get any disassembly, and `DOTNET_JitNoInline=1` because it otherwise inlines into its caller and gets no listing of its own), so the shipped R2R body may differ from what I pasted. And the offset `0x5C` is from my repro's type layout.

## New evidence, independent of mechanism

Going back through our production logs rather than a summary of them, the two most useful facts:

1. **Two of the exceptions, with distinct exception ids, were logged in the same millisecond** — `10:30:09.421`, roughly four seconds after that instance started receiving traffic (its startup probe went healthy at ~`10:30:05`; the process had started at `10:29:15`). So the trigger window really is *the first concurrent use of the type*, and there really were concurrent validations of it at that instant. That is the first direct evidence of concurrency at the moment of failure that I have seen in this issue.
2. **It is not resource pressure widening the window.** The affected instance was unremarkable against its five healthy siblings over the same 20 minutes: CPU throttling 1.97 s (siblings 1.58–2.38 s), GC collections 67 (siblings 79–102), CPU 0.30 cores (siblings 0.28–0.42).

Also, for completeness on our side: the signature occurs exactly once in seven days across the whole service, on that one instance; the application's metadata pipeline is entirely stock (`DefaultModelMetadataProvider`, all details/validator providers from Microsoft, nothing custom that could filter properties); and the record in question has 8 properties matching 8 constructor parameters in a healthy process. All the "it's your code" explanations I could think of are ruled out.

## Where that leaves the diagnosis

Solid: the failure mode. The parameter that finds no matching property is **silently skipped**, and the resulting incomplete dictionary is cached for the lifetime of the `ModelMetadata` instance, i.e. the process. That is what converts a momentary inconsistency into an instance that serves 500s until it is restarted, and it is why the exception surfaces later from an unrelated request. My repro in the previous comment still stands: both poisonings reproduce the exact production exception and keep throwing after the metadata is restored to a correct state.

Not solid: which unsynchronised lazy init actually produces the divergence. Candidates now:
- the misaligned `_hashCode` store crossing a cache line (above — possible, unproven);
- `DefaultModelMetadata._properties` / `DefaultMetadataDetails.Properties` publication (weak memory models only, so it cannot explain ours — all our nodes are `x86_64`);
- something not yet identified.

And separately, still a real bug regardless: `_recordTypeConstructorDetailsCalculated = true` is assigned **before** `_parameterMapping` and `_boundConstructorPropertyMapping`, so a racing reader that early-returns on the flag can observe a null mapping and get a `NullReferenceException` out of `TryGetValue`.

Given the mechanism is still open, I would put the weight on recommendation 1 from my previous comment, because it is mechanism-independent: **do not cache a mapping you can see is incomplete.** Throw at construction, or leave `_recordTypeConstructorDetailsCalculated` false so the next call rebuilds. Either would have turned our 18-minute, 1350-exception outage into a single failed request, whatever the underlying race turns out to be.

The question to the other reporters still stands, and the first half of it is now more interesting than I thought: **CPU architecture** (x64 vs arm64) of the affected instances, and the **position of the named parameter** in the primary constructor.

**Comment by sterlyagovandrey** [comment]
**Found it, with a reproduction on real hardware. My previous comment retracted the correct mechanism — it was right after all, and I can now demonstrate it.**

Apologies for the detour; the short version of my mistake is that I disassembled the wrong tier.

## The mechanism

`ModelMetadata` caches its hash code in `private int? _hashCode`, written lazily with no synchronization. In **optimized** codegen the `Nullable<int>` is struct-promoted and published as **two separate stores, `hasValue` first** (x64, FullOpts, .NET 9):

```asm
; Assembly listing for method Microsoft.AspNetCore.Mvc.ModelBinding.ModelMetadata:GetHashCode():int:this (FullOpts)
G_M000_IG02:
       cmp      byte  ptr [rbx+0x5C], 0        ; HasValue
       jne      SHORT G_M000_IG05
G_M000_IG03:
       vmovdqu  ymm0, ymmword ptr [rbx+0x68]   ; load Identity
       ...
G_M000_IG04:
       call     [Microsoft.AspNetCore.Mvc.ModelBinding.Metadata.ModelMetadataIdentity:GetHashCode():int:this]
       mov      byte  ptr [rbx+0x5C], 1        ; hasValue = true    <-- published FIRST
       mov      dword ptr [rbx+0x60], eax      ; value    = hash    <-- payload SECOND
G_M000_IG05:
       add      rbx, 92
       cmp      byte  ptr [rbx], 0             ; HasValue
       je       SHORT G_M000_IG07
       mov      eax, dword ptr [rbx+0x04]      ; Value
```

x86-64 TSO *guarantees* stores become globally visible in program order. So `(HasValue = true, Value = 0)` is not a rare hardware accident — it is an **architecturally guaranteed intermediate state**, present at every publication, on every CPU, at every alignment. A thread calling `GetHashCode()` inside that window gets **`0`**.

Why that is fatal and why it never heals:

1. `CalculateRecordTypeConstructorDetails()` is unsynchronized, so two requests binding the same record type concurrently both run the mapping loop.
2. Each `parameterMapping[parameter] = property` calls `parameter.GetHashCode()`. A thread that lands in the publication window inserts the entry under hash **0**.
3. `_hashCode` then settles to the correct value, so every later `TryGetValue` computes the real hash `H`, probes the `H % size` bucket, and never finds the entry. `Dictionary.Resize` copies stored hash codes, so a resize does not fix it either.
4. `_parameterMapping` is cached for the life of the `ModelMetadata`, i.e. the process. Result: `No property found that maps to constructor parameter '<X>'` on every request carrying that type, **until the instance is restarted**.

That last property is the one nothing else explained, and it matches every report in this thread.

## Reproduction on real x86-64

Two threads calling the **real** `ModelMetadata.GetHashCode()`. Real hardware (Intel Xeon, Ice Lake), Linux, .NET 9.0.18, **default runtime settings — ReadyToRun active, no JIT overrides**. Between rounds `_hashCode` is zeroed via `UnsafeAccessor` while the reader is quiesced, to reopen the one-shot window:

| `_hashCode` addr mod 64 | straddles a cache line | rounds | `GetHashCode() == 0` |
|---|---|---|---|
| 4  | no  | 48,423,139 | 1,301 |
| 12 | no  | 58,180,047 | 11,026 |
| 20 | no  | 57,055,017 | 3,510 |
| 28 | no  | 56,647,252 | 11,193 |
| 52 | no  | 51,105,629 | 4,138 |
| 60 | **yes** | 51,589,460 | 99,646 |

`GetHashCode()` **never** returned a wrong non-zero value — only `0`, exactly the signature of `hasValue` being published before the payload. It happens at every alignment, so nothing exotic is required.

## Correcting my previous comment

What I got wrong there: I disassembled **Tier0**. Tier0 really does build the `Nullable<int>` in a stack slot and copy it with a single 8-byte `mov`, and from that I wrongly concluded the mechanism was impossible. But under default settings this method is **never JIT-compiled at all** — it is ReadyToRun-precompiled, so production runs the crossgen2 body, and crossgen2 compiles with full optimizations. Tier0 codegen never executes for it.

The cache-line straddle idea from that comment is real physics — in a dedicated harness a split 8-byte store tore at ~10% (1.03e9 torn reads in 9.87e9), while the aligned control and an unaligned-but-within-line control stayed clean across ~200e9 reads — but it is **not required** here, because in optimized code there is no 8-byte store to tear. At most it widens the window: at `mod 64 == 60` the two stores land in different cache lines and the writer stalls between them acquiring the second. The apparent ~9x amplification in the table above should be treated as suggestive rather than established — the spread among the non-straddling residues is already 8.6x, and that is one sample per residue on different objects.

One caveat I want to state rather than paper over: I did not disassemble the R2R body directly. Its shape is inferred from zero JIT compilations under default settings plus the observed zeros — and on x86 a single atomic 8-byte store cannot produce `(true, 0)`, so the R2R body must publish non-atomically too.

## Suggested fix

Smallest correct change: make it `private int _hashCode` with `0` as the "not computed yet" sentinel. A naturally aligned 4-byte store is atomic on x86 and ARM, and recomputing in the rare case where the real hash is genuinely 0 is harmless. Alternatives: keep the `Nullable<int>` but publish with `Volatile.Write` after the payload, or compute the hash eagerly in the constructor.

Independently of that, recommendation 1 from my earlier comment still deserves to land, because it is what converts a nanosecond-wide race into an outage: **do not cache a mapping you can see is incomplete.** In `CalculateRecordTypeConstructorDetails`, if a bound parameter finds no matching property, either throw there or leave `_recordTypeConstructorDetailsCalculated` false so the next call rebuilds. With that, this race would cost one failed request instead of an instance that serves 500s until it is restarted. Our own production incident was 18 minutes and 1350 exceptions on one pod out of six; with that change it would have been a single 500.

I'm happy to open a PR for either or both if a maintainer indicates which shape they'd prefer.

## Two notes for others hitting this

- **The general hazard is wider than this class.** Any lazily cached `Nullable<T>` field read without synchronization is broken in optimized .NET, because `hasValue` is published before the payload. Worth grepping your own code for.
- **Architecture doesn't save you, and this closes the question I asked earlier in the thread.** arm64 makes it easier (weak ordering, and the codegen is the same two-store pair — `strb #1, [x19,#0x5C]` / `str w0, [x19,#0x60]`), but x86-64 is if anything *worse* conceptually: TSO makes the bad intermediate state deterministic rather than accidental. All our affected nodes were x86_64.

**Comment by gdoron** [comment]
I've create a repo that reproduces reliably the issue and a fix.
@danroth27 , asp.net core has serious race condition that can poisons endpoints using records.
IMHO, I don't think this item should stay in the backlog. 
https://github.com/gdoron/aspnetcore-record-metadata-race-repro
