### ISSUE TITLE
.NET 9 OpenAPI not working with nullable property with MaxLengthAttribute

### ISSUE THREAD

**Issue by JarrodOsborne** [dotnet/aspnetcore#59428]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

OpenAPI document generation fails when a request body class contains a nullable property with [MaxLength(...)].

Here is reproducible code:

```cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers();
builder.Services.AddOpenApi();

var app = builder.Build();

app.MapControllers();
app.MapOpenApi();

await app.RunAsync();

[ApiController]
[Route("api/[controller]")]
public class MyController : ControllerBase
{
    public class MyRequestModel
    {
        // Both types fail with the same error
        [MaxLength(10)]
        public IList<string>? Items { get; set; }
        // public string[]? Items { get; set; }
    }

    [HttpPost]
    public IActionResult Post([FromBody] MyRequestModel request)
    {
        return Ok(request);
    }
}
```

Calling `http://localhost:5000/openapi/v1.json` results in:

```
     System.InvalidOperationException: The node must be of type 'JsonValue'.
         at System.Text.Json.Nodes.JsonNode.GetValue[T]()
         at Microsoft.AspNetCore.OpenApi.JsonNodeSchemaExtensions.ApplyValidationAttributes(JsonNode schema, IEnumerable`1 validationAttributes)
         at Microsoft.AspNetCore.OpenApi.OpenApiSchemaService.<>c__DisplayClass0_0.<.ctor>b__2(JsonSchemaExporterContext context, JsonNode schema)
         at System.Text.Json.Schema.JsonSchema.<ToJsonNode>g__CompleteSchema|104_0(JsonNode schema, <>c__DisplayClass104_0&)
         at System.Text.Json.Schema.JsonSchema.ToJsonNode(JsonSchemaExporterOptions options)
         at System.Text.Json.Schema.JsonSchema.ToJsonNode(JsonSchemaExporterOptions options)
         at System.Text.Json.Schema.JsonSchemaExporter.GetJsonSchemaAsNode(JsonTypeInfo typeInfo, JsonSchemaExporterOptions exporterOptions)
         at System.Text.Json.Schema.JsonSchemaExporter.GetJsonSchemaAsNode(JsonSerializerOptions options, Type type, JsonSchemaExporterOptions exporterOptions)        
         at Microsoft.AspNetCore.OpenApi.OpenApiSchemaService.CreateSchema(OpenApiSchemaKey key)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
         at Microsoft.AspNetCore.OpenApi.OpenApiSchemaStore.GetOrAdd(OpenApiSchemaKey key, Func`2 valueFactory)
         at Microsoft.AspNetCore.OpenApi.OpenApiSchemaService.GetOrCreateSchemaAsync(Type type, IServiceProvider scopedServiceProvider, IOpenApiSchemaTransformer[] schemaTransformers, ApiParameterDescription parameterDescription, Boolean captureSchemaByRef, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetJsonRequestBody(IList`1 supportedRequestFormats, ApiParameterDescription bodyParameter, IServiceProvider scopedServiceProvider, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetRequestBodyAsync(ApiDescription description, IServiceProvider scopedServiceProvider, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOperationAsync(ApiDescription description, HashSet`1 capturedTags, IServiceProvider scopedServiceProvider, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOperationsAsync(IGrouping`2 descriptions, HashSet`1 capturedTags, IServiceProvider scopedServiceProvider, IOpenApiOperationTransformer[] operationTransformers, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOpenApiPathsAsync(HashSet`1 capturedTags, IServiceProvider scopedServiceProvider, IOpenApiOperationTransformer[] operationTransformers, IOpenApiSchemaTransformer[] schemaTransformers, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOpenApiDocumentAsync(IServiceProvider scopedServiceProvider, CancellationToken cancellationToken)   
         at Microsoft.AspNetCore.Builder.OpenApiEndpointRouteBuilderExtensions.<>c__DisplayClass0_0.<<MapOpenApi>b__0>d.MoveNext()

```

I have done some debugging and the fault happens here in `JsonNodeSchemaExtensions.cs:101`
```cs
            else if (attribute is MaxLengthAttribute maxLengthAttribute)
            {
                var targetKey = schema[OpenApiSchemaKeywords.TypeKeyword]?.GetValue<string>() == "array" ? OpenApiSchemaKeywords.MaxItemsKeyword : OpenApiSchemaKeywords.MaxLengthKeyword;
                schema[targetKey] = maxLengthAttribute.Length;
            }
```

The schema comes through as:
![Image](https://github.com/user-attachments/assets/99a502ba-66bd-4c24-8d69-b481e559240f)
But fails because it's a `JsonArray` and not a `JsonValue`
```json
{
  "type" : [ "array", "null" ],
  "items" : {
    "type" : "string",
    "nullable" : false,
    "format" : null,
    "x-schema-id" : null,
    "pattern" : null
  },
  "nullable" : true
}
```

Please let me know if I'm doing something wrong, thanks!

### Expected Behavior

The document generator should be able to handle a nullable array/collection with a `MaxLength(N)` validation attribute.
The resulting OpenAPI document should list the property as a nullable array, with maxItems as `N`

### Steps To Reproduce

See bug description

### Exceptions (if any)

See bug description for full trace
```
System.InvalidOperationException: The node must be of type 'JsonValue'.
         at System.Text.Json.Nodes.JsonNode.GetValue[T]()
         at Microsoft.AspNetCore.OpenApi.JsonNodeSchemaExtensions.ApplyValidationAttributes(JsonNode schema, IEnumerable`1 validationAttributes)
```

### .NET Version

.NET 9

**Comment by DaleMckeown** [comment]
I too am having this issue. Has a workaround been found?

**Comment by mikekistler** [comment]
Marking this as a bug.

**Comment by captainsafia** [comment]
@JarrodOsborne Thanks for filing this issue and taking the time to investigate! Your analysis on the root cause of the issue is correct. Would you be interested in opening a PR to resolve this issue by updating the check in the `ApplyValidationAttributes` call?

**Comment by iqmeta** [comment]
Same issue ;-(  +Vote

**Comment by xC0dex** [comment]
Hey @captainsafia,

I'd like to jump in and create a PR. I'd update the check for the `MaxLengthAttribute` and the `LengthAttribute` to something like this:

```c#
var isArray = MapJsonNodeToSchemaType(schema[OpenApiSchemaKeywords.TypeKeyword]) is { } schemaTypes && schemaTypes.HasFlag(JsonSchemaType.Array);
var key = isArray ? OpenApiSchemaKeywords.MaxItemsKeyword : OpenApiSchemaKeywords.MaxLengthKeyword;
schema[key] = maxLengthAttribute.Length;
```

**Comment by guid0h** [comment]
Is there any workaround for this in .NET 9 or will this be fixed in .NET 9.

**Comment by bharathwajv** [comment]
same issue for me in below scenario 

    [MinLength(1, ErrorMessage = "At least one message is required")]
    public string[] Messages { get; set; }

**Comment by fededim** [comment]
The issue has been opened in package version 9 and it has been fixed in [package version 10.x](https://github.com/dotnet/aspnetcore/pull/60460) very logical 👍 is there any good Samaritan who can cherry pick also to package version 9.xx ?

**Comment by martincostello** [comment]
Anyone can cherrypick and open a PR, but it wouldn't be worth doing without a clear signal from the team that it would meet the bar to be considered for servicing.

**Comment by fededim** [comment]
**Yes, I know but I would say that this is a critical blocking bug, I mean you can't use any Length data annotations on version 9.x of the package**...

In my case (EFCore) I simply moved the constraint in the database context, but if someone uses these attributes for field validation it is forced to use a custom validation logic or to upgrade to the new Visual Studio 2026 to code on .NET 10 (that would be a sly marketing trick 😄)

I mean they shouldn't even raise the question, IMHO the cherrypick should be ported to every version being actively maintained
