### ISSUE TITLE
OpenApi generation OpenApiSchemaComparer fails with null values for Properties, AllOf, or AnyOf

### ISSUE THREAD

**Issue by FrankSzendzielarz** [dotnet/aspnetcore#59507]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

OpenApiSchemaComparer uses code like `   hashCode.Add(obj.Properties.Count);` . In custom schema transforms where I might want to replace allof , anyof, or properties, intuitively I would set unwanted properties to null. Either the setter should prevent this, or the `obj.Properties.Count` should be `obj.Properties?.Count??0` or otherwise take care of nulls.

### Expected Behavior

Not crash when a schema property is null. 

### Steps To Reproduce

Custom schema transform - set Properties to null. OpenApi doc gen and Scalar result have missing elements.

### Exceptions (if any)

Object reference not set to an instance of an object.

### .NET Version

9

**Comment by captainsafia** [comment]
@FrankSzendzielarz Thanks for filing this issue!

I believe as a temporary workaround you can initialize the designated properties to empty lists. The OpenAPI document writer _should_ do the write thing and not emit them but let me know if that's not the case.

With regard to how we might solve this in the long-term, with the adoption of `Microsoft.OpenApi` v2, we're hoping to move forward with the comparers being implemented in the library themselves (instead of in the ASP.NET Core codebase). There's also some changes coming to the nullability/default blues for collection-based properties like `AllOf` and friends.

I'll take this one as a sub-issue under https://github.com/dotnet/aspnetcore/issues/58619 for now since the comparers are removed from source in https://github.com/dotnet/aspnetcore/pull/59480.

**Comment by gumbarros** [comment]
I'm having the same exception but my Properties are never `null`. Any guidance?


```
Serilog.AspNetCore.RequestLoggingMiddleware
HTTP "GET" "/openapi/v1.json" responded 500 in 125.9134 ms
Show Exception

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.OpenApi.OpenApiSchemaComparer.GetHashCode(OpenApiSchema obj)
   at Microsoft.AspNetCore.OpenApi.OpenApiSchemaComparer.GetHashCode(OpenApiSchema obj)
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.AspNetCore.OpenApi.OpenApiSchemaReferenceTransformer.ResolveReferenceForSchema(OpenApiSchema schema, ConcurrentDictionary`2 schemasByReference, Boolean isTopLevel)
   at Microsoft.AspNetCore.OpenApi.OpenApiSchemaReferenceTransformer.TransformAsync(OpenApiDocument document, OpenApiDocumentTransformerContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.ApplyTransformersAsync(OpenApiDocument document, IServiceProvider scopedServiceProvider, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOpenApiDocumentAsync(IServiceProvider scopedServiceProvider, HttpRequest httpRequest, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.OpenApi.OpenApiDocumentService.GetOpenApiDocumentAsync(IServiceProvider scopedServiceProvider, HttpRequest httpRequest, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Builder.OpenApiEndpointRouteBuilderExtensions.<>c__DisplayClass0_0.<<MapOpenApi>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Http.Generated.<GeneratedRouteBuilderExtensions_g>F56B68D2B55B5B7B373BA2E4796D897848BC0F04A969B1AF6260183E8B9E0BAF2__GeneratedRouteBuilderExtensionsCore.<>c__DisplayClass2_0.<<MapGet0>g__RequestHandler|5>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```

**Comment by Youssef1313** [comment]
OpenApiSchemaComparer no longer exists. So I'm going to close this issue. If you are still encountering any issues with your custom transformers, please open a new issue with a repro or details.
