### ISSUE TITLE
SignalR client cannot connect to SignalR server

### ISSUE THREAD

**Issue by zhenlei520** [dotnet/aspnetcore#59639]
OS：Ubuntu 22.04
SignalR Server: .net8.0
SignalR.Client 7.0
I use SignalR server to push messages to SignalR, but when there are many SignalR clients, it is easy for the SignalR client to be unable to connect to the SignalR server. This situation is easy to occur when the number of client connections exceeds 2000. I suspect it is related to the excessive number of client connections. I wonder if there is any recommended configuration for this?

Due to special circumstances, distribution is not supported for the time being, and only one SignalR server can be used, so I hope it can support more client connections

```
.AddSignalR(options =>
{
options.EnableDetailedErrors = true;
options.MaximumReceiveMessageSize = 1024 * 1024 * 10;
})

app.MapHub<RelationHub>("/relationhub", options =>
{
// 1024 * 1024 * 10 = 10MB
options.ApplicationMaxBufferSize = 1024 * 1024 * 10;
options.TransportMaxBufferSize = 1024 * 1024 * 10;
});
```

The server's CPU and memory are both below 20%, and the bandwidth performance is good.

```
ulimit -n
65535
```

**Comment by zhenlei520** [comment]
By adding logs, it was found that an error occurred when the client sent a message to the server. The error message was:

```
Exception:System.TimeoutException: Server timeout (30000.00ms) elapsed without receiving a message from the server.

   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsyncCore(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)

   at Microsoft.AspNetCore.SignalR.Client.HubConnection.InvokeCoreAsync(String methodName, Type returnType, Object[] args, CancellationToken cancellationToken)
```

**Comment by zhenlei520** [comment]
But I don't know why the client will time out when sending messages to the server. There is no problem with the network.

**Comment by profimedica** [comment]
Have you tried to skip negotiation?

skipNegotiation: true,
transport: signalR.HttpTransportType.WebSockets

**Comment by BrennanConroy** [comment]
I've seen way more than 2000 connections on a single server before. If there is a timeout occurring but the server CPU usage is low, that might suggest a lock/deadlock somewhere that's stopping the server from being able to send/process messages. Try getting a process dump and analyzing it.
