### ISSUE TITLE
Runtime exception for endpoints in different API versions with the same endpoint name

### ISSUE THREAD

**Issue by mikekistler** [dotnet/aspnetcore#59669]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

In a Minimal API application using the Asp.Versioning package to implement API versioning, the runtime throws an exception if two endpoints in different API versions have the same endpoint name. The exception thrown is:

```text
System.InvalidOperationException: Duplicate endpoint name 'Hello' found on 'HTTP: GET /hello' and 'HTTP: GET /hello'. Endpoint names must be globally unique.
   at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher.CreateMatcher(IReadOnlyList`1 endpoints)
   at Microsoft.AspNetCore.Routing.DataSourceDependentCache`1.Initialize()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.AspNetCore.Routing.Matching.DataSourceDependentMatcher..ctor(EndpointDataSource dataSource, Lifetime lifetime, Func`1 matcherBuilderFactory)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcherFactory.CreateMatcher(EndpointDataSource dataSource)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.InitializeCoreAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatcher|10_0(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task`1 matcherTask)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### Expected Behavior

I think that endpoint names should only be required to be unique within an API version. 

### Steps To Reproduce

[This repo](https://github.com/mikekistler/aspnet-versioning/tree/issue-59669) contains a branch that illustrates the issue.

### Exceptions (if any)

See above.

### .NET Version

9.0.100

**Comment by davidfowl** [comment]
This doesn’t look like a bug, those names are unique identifiers.

**Comment by mikekistler** [comment]
I know the endpoint name is used in the OpenAPI document generation as the `operationId`, and this must be unique within an OpenAPI document. But with API versioning the OpenAPI document is split by version, so all v1 APIs go in one document and all v2 APIs go in a separate document.

How else is this name used that requires it to be unique "globally"?

**Comment by mikekistler** [comment]
This appears to be "by design". So for versioned APIs each versioned endpoint will need a unique name. A strategy for dealing with this is to add a version suffix like "-V2" and then strip this off in the OpenAPI doc before doing things like client generation.
