### ISSUE TITLE
SignalR Multiple hub per connection problem

### ISSUE THREAD

**Issue by Rakiah** [dotnet/aspnetcore#6380]
Hello, i've been toying around SignalR for a few days and was worried about certain points:

Please, correct me if i'm wrong:
SignalR use a new WebSocket connection for each hub
Having multiple hub is therefore a battery killer for mobile applications (because it has to keep the socket alive, do ping/pong for each of them, etc..)

In my scenario we're running a microservices architecture that each hold some "Entities" and some "Events", we've running a REST API to have an impact on those entities, when the client is connecting for the first time, he's requesting all of the entities he require directly from the REST API, after that, it should be real time events from the microservices to the client to retrieve the modifications of the entities:

In our scenario, the simplest and most elegant solution would be to create one hub per entity so that we have a generic `EntityEventHub<IEntity> : Hub<IClientEntityEventRPC<IEntity>>` that is templated with the IEntity and strongly typed.

But doing so would require 50s differents hubs and thefore 50th differents websocket connection which is probably unsustainable,
Do you have any plan in supporting multiple hub for one websocket connection ?

**Comment by Rakiah** [comment]
Well it sounds like templating hub doesn't even work at all:
```
Failed to invoke hub method 'Passport'.
System.IO.InvalidDataException: Invocation provides 13 argument(s) but target expects 0.
at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.BindArguments(JsonTextReader reader, IReadOnlyList`1 paramTypes)
at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.ParseMessage(Utf8BufferTextReader textReader, IInvocationBinder binder)
Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher:Error: Failed to invoke hub method 'Passport'.

System.IO.InvalidDataException: Invocation provides 13 argument(s) but target expects 0.
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.BindArguments(JsonTextReader reader, IReadOnlyList`1 paramTypes)
   at Microsoft.AspNetCore.SignalR.Protocol.JsonHubProtocol.ParseMessage(Utf8BufferTextReader textReader, IInvocationBinder binder)
```
```public class EventsHub<T> : Hub<IClientRPCEvents>, IServerRPCEvents<T> where T : IEntity```


```                routes.MapHub<EventsHub<Passport>>("/realtime/" + typeof(Passport).Name);```

**Comment by BrennanConroy** [comment]
What does `IClientRPCEvents` look like? From the logs it looks like you passed 13 arguments from the client but the method it's trying to call takes 0 arguments.

**Comment by BrennanConroy** [comment]
Also, we don't support a single connection for multiple hubs, it's 1 to 1. See https://github.com/aspnet/SignalR/issues/2531

It is possible to create a system that uses a single hub and dispatches to different handlers based on something like a query string for each of your different `IEntity` types.

**Comment by lobster2012-user** [comment]
@Rakiah 

Whant about this?
```csharp

 #region generated by t4

    public static class MultiClientExtensions
    {
        public static HubConnection Add(this HubConnection connection, IClient0 client)
        {
            connection.On("IClient0_Method0", client.Method0);
            return connection;
        }

        public static IClient0 IClient0(this _IMultiClient proxy)
        {
            return new _IClient0_to_IClient(proxy);
        }
        class _IClient0_to_IClient : IClient0
        {
            private readonly _IMultiClient _proxy;

            public _IClient0_to_IClient(_IMultiClient proxy)
            {
                this._proxy = proxy;
            }

            public void Method0()
            {
                _proxy.IClient0_Method0();
            }
        }
    }

    public interface _IClient0
    {
        void IClient0_Method0();
    }

    public interface _IMultiClient : _IClient0
    {

    }
    public class _MultiHub : Hub<_IMultiClient>
    {

    }

    #endregion


    public interface IClient0
    {
        void Method0();
    }
 
    public class MultiHub : _MultiHub
    {
        public void OnMessage()
        {
            this.Clients.Caller.IClient0_Method0();
            this.Clients.Caller.IClient0().Method0();
        }
    }
    public class HubClient  
    {
        public void Initialize(HubConnection connection, IClient0 client)
        {
            connection.Add(client);
        }
    }

```

**Comment by lobster2012-user** [comment]
It works for me.
//server side
```csharp

    public interface IHello1Client
    {
        [HubMethodName("IHello1Client_OnMessage")] //does not work now
        Task IHello1Client_OnMessage(string text);
    }
    public interface IHello2Client
    {
        [HubMethodName("IHello2Client_OnMessage")]//does not work now
        Task IHello2Client_OnMessage(string text);
    }
    public interface IMultiClient : IHello1Client, IHello2Client
    {

    }

    /// <summary>
    /// TODO: dynamic generate 
    /// </summary>
    public class MultiHub : Hub<IMultiClient>
    {
        private readonly IServiceProvider _provider;
        private readonly ILogger _logger;

        private IEnumerable<Hub> _hubs => new[] {
            GetHub<Hello1Hub,IHello1Client,IMultiClient>(this),
            (Hub)GetHub<Hello2Hub,IHello2Client,IMultiClient>(this) };

        public MultiHub(ILogger<MultiHub> logger, IServiceProvider provider)
        {
            _logger.LogDebug("****** MultiHub-ctor");
            _provider = provider;
            _logger = logger;
        }

        public override async Task OnConnectedAsync()
        {
            _logger.LogDebug("****** on-connected");
            await Task.WhenAll(_hubs.Select(z => z.OnConnectedAsync()).ToArray());
            await base.OnConnectedAsync();
        }

        public override async Task OnDisconnectedAsync(Exception exception)
        {
            _logger.LogDebug("****** on-disconnected");
            await Task.WhenAll(_hubs.Select(z => z.OnDisconnectedAsync(exception)).ToArray());
            await base.OnDisconnectedAsync(exception);
        }

        [HubMethodName("Hello1Hub_OnMessage")]
        public void Hello1Hub_OnMessage(string text)
        {
            _logger.LogDebug("****** Hello1Hub_OnMessage");
            GetHub<Hello1Hub, IHello1Client,IMultiClient>(this).OnMessage(text);
        }
        [HubMethodName("Hello2Hub_OnMessage")]
        public void Hello2Hub_OnMessage(string text)
        {
            _logger.LogDebug("****** Hello2Hub_OnMessage");
            GetHub<Hello2Hub, IHello2Client, IMultiClient>(this).OnMessage(text);
        }

        protected override void Dispose(bool disposing)
        {
            _logger.LogDebug("****** MultiHub-dispose");
            if (disposing)
            {
                foreach (var hub in _hubs)
                {
                    hub.Dispose();
                }
            }
            base.Dispose(disposing);
        }

        private THub GetHub<THub, TClient, TMultiClient>(Hub<TMultiClient> src)
            where THub : Hub<TClient>
            where TClient : class
            where TMultiClient : class, TClient
        {
            var hub = _provider.GetRequiredService<THub>();
            hub.Groups = src.Groups;
            hub.Context = src.Context;
            hub.Clients = new MultiHubCallerClientsToConcrete<TMultiClient, TClient>(src.Clients);
            return hub;
        }
    }

```
//client-side
//todo...

**Comment by lobster2012-user** [comment]
//updated
[repo](https://github.com/lobster2012-user/multihub_playground/tree/master)

```csharp

    /// <summary>
    /// TODO: dynamic generate 
    /// </summary>
    public class MultiHub : MultiHubBase<IMultiClient>
    {
        public MultiHub(ILogger<MultiHub> logger, IServiceProvider provider) 
            : base(logger, provider,  new[] { typeof(Hello1Hub), typeof(Hello2Hub)})
        {
        }

        [HubMethodName("Hello1Hub_OnMessage")]
        public void Hello1Hub_OnMessage(string text)
        {
            Hello1Hub.OnMessage(text);
        }
        [HubMethodName("Hello2Hub_OnMessage")]
        public void Hello2Hub_OnMessage(string text)
        {
            Hello2Hub.OnMessage(text);
        }

        private Hello1Hub Hello1Hub => CreateHub<Hello1Hub, IHello1Client>();
        private Hello2Hub Hello2Hub => CreateHub<Hello2Hub, IHello2Client>();

    }

```
