### ISSUE TITLE
[Blazor] Bug in blazor cli `FindClientBinDir`

### ISSUE THREAD

**Issue by vchirikov** [dotnet/aspnetcore#6623]
### Describe the bug
I prefer use standard project structure, published by @davidfowl , so have sources in src, build output in artifacts folder. 
I have client-side blazor app with redefined output path in Directory.build.props, something like this:

```xml
<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
<BaseIntermediateOutputPath>$(SolutionDir)artifacts\obj\$(MSBuildProjectName)</BaseIntermediateOutputPath>
<OutputPath>$(SolutionDir)artifacts\bin</OutputPath>
```
But if I redefine output path `dotnet blazor serve` can't find output assembly.

### To Reproduce
1. `dotnet --version` => `3.0.100-preview-009825`
1. Executing task: `C:\Program Files\dotnet\dotnet.exe blazor serve C:\work\BlazorDisasm/src/BlazorDisasm/BlazorDisasm.csproj` output:

```
Application startup exception: System.InvalidOperationException: Cannot find bin directory for Blazor app. Neither 'C:\work\BlazorDisasm\src\BlazorDisasm\bin\Debug' nor 'C:\work\BlazorDisasm\src\BlazorDisasm\bin\Release' exists on disk. Make sure the project has been built.
   at Microsoft.AspNetCore.Blazor.Cli.Server.Startup.FindClientBinDir(String clientAppSourceRoot)
   at Microsoft.AspNetCore.Blazor.Cli.Server.Startup.FindClientAssemblyPath(IApplicationBuilder app)
   at Microsoft.AspNetCore.Blazor.Cli.Server.Startup.Configure(IApplicationBuilder app, IConfiguration configuration)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
System.InvalidOperationException: Cannot find bin directory for Blazor app. Neither 'C:\work\BlazorDisasm\src\BlazorDisasm\bin\Debug' nor 'C:\work\BlazorDisasm\src\BlazorDisasm\bin\Release' exists on disk. Make sure the project has been built.
   at Microsoft.AspNetCore.Blazor.Cli.Server.Startup.FindClientBinDir(String clientAppSourceRoot)
   at Microsoft.AspNetCore.Blazor.Cli.Server.Startup.FindClientAssemblyPath(IApplicationBuilder app)
   at Microsoft.AspNetCore.Blazor.Cli.Server.Startup.Configure(IApplicationBuilder app, IConfiguration configuration)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

### Expected behavior
Runned blazor app.

### Additional context

`<DotNetCliToolReference Include="Microsoft.AspNetCore.Blazor.Cli" Version="0.7.0" />`

**Comment by rynowak** [comment]
It looks like we're not honouring some of the MSBuild things. Would you be willing to send a PR for this?

**Comment by javiercn** [comment]
This is not a thing anymore sin it is all MSBuild based now
