### ISSUE TITLE
[Helix] MVC XmlSerializer_CanIndentOutputConditionally test failure

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#6628]
Error:

```
Microsoft.AspNetCore.Mvc.Formatters.Xml.XmlSerializerOutputFormatterTest.XmlSerializer_CanIndentOutputConditionally(indent: True, input: DummyClass { SampleInt = 10 }, expectedOutput: "<DummyClass xmlns:xsi=\"http://www.w3.org/2001/XML"...) [FAIL]
      Assert.Equal() Failure
                                     (pos 20)
      Expected: <DummyClass xmlns:xsi="http://www.w3.org/2001/XMLSchema-insta���
      Actual:   <DummyClass xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmln���
                                     (pos 20)
      Stack Trace:
        /_/src/Mvc/test/Microsoft.AspNetCore.Mvc.Formatters.Xml.Test/XmlSerializerOutputFormatterTest.cs(108,0): at Microsoft.AspNetCore.Mvc.Formatters.Xml.XmlSerializerOutputFormatterTest.<XmlSerializer_CanIndentOutputConditionally>d__8.MoveNext()

    Microsoft.AspNetCore.Mvc.Formatters.Xml.XmlSerializerOutputFormatterTest.XmlSerializer_CanIndentOutputConditionally(indent: False, input: DummyClass { SampleInt = 10 }, expectedOutput: "<DummyClass xmlns:xsi=\"http://www.w3.org/2001/XML"...) [FAIL]
      Assert.Equal() Failure
                                     (pos 20)
      Expected: <DummyClass xmlns:xsi="http://www.w3.org/2001/XMLSchema-insta���
      Actual:   <DummyClass xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmln���
                                     (pos 20)
      Stack Trace:
        /_/src/Mvc/test/Microsoft.AspNetCore.Mvc.Formatters.Xml.Test/XmlSerializerOutputFormatterTest.cs(108,0): at Microsoft.AspNetCore.Mvc.Formatters.Xml.XmlSerializerOutputFormatterTest.<XmlSerializer_CanIndentOutputConditionally>d__8.MoveNext()


```

**Comment by HaoK** [comment]
Closing as stale, might have been due to initial helix migration flakiness
