### ISSUE TITLE
[Helix] DataProtection System_UsesProvidedDirectoryAndCertificate fails on OSX

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#6720]
DataProtection/Extensions/test/DataProtectionProviderTests.cs System_UsesProvidedDirectoryAndCertificate fails only on OSX queue

```
[xUnit.net 00:00:01.28]     Microsoft.AspNetCore.DataProtection.DataProtectionProviderTests.System_UsesProvidedDirectoryAndCertificate [FAIL]
Failed   Microsoft.AspNetCore.DataProtection.DataProtectionProviderTests.System_UsesProvidedDirectoryAndCertificate
Error Message:
 Interop+AppleCrypto+AppleCommonCryptoCryptographicException : write permissions error
Stack Trace:
   at Interop.AppleCrypto.X509StoreAddCertificate(SafeKeychainItemHandle certOrIdentity, SafeKeychainHandle keychain)
   at Internal.Cryptography.Pal.StorePal.AppleKeychainStore.Add(ICertificatePal cert)
   at System.Security.Cryptography.X509Certificates.X509Store.Add(X509Certificate2 certificate)
   at Microsoft.AspNetCore.DataProtection.DataProtectionProviderTests.System_UsesProvidedDirectoryAndCertificate() in /_/src/DataProtection/Extensions/test/DataProtectionProviderTests.cs:line 124
[xUnit.net 00:00:01.58]     Microsoft.AspNetCore.DataProtection.DataProtectionProviderTests.System_UsesProvidedDirectory_WithConfigurationCallback [SKIP]
Skipped  Microsoft.AspNetCore.DataProtection.DataProtectionProviderTests.System_UsesProvidedDirectory_WithConfigurationCallback
Results File: /Users/dotnet-bot/dotnetbuild/work/e46143d4-88da-42ae-96d7-42513595330a/Work/45b5d399-ffd0-4a6b-ab73-3fce0571cf50/Exec/TestResults/_dci-mac-build-083_2019-01-15_01_40_03.trx
```

**Comment by HaoK** [comment]
These also cause Microsoft.AspNetCore.ApiAuthorization.IdentityServer.Tests to fail in master

**Comment by HaoK** [comment]
Note on master there appears to be a new attribute `[X509StoreIsAvailable(StoreName.My, StoreLocation.CurrentUser)]` that is attempting to skip sometimes, but maybe its not correctly working on helix OSX

**Comment by HaoK** [comment]
Unskipped these tests except on OSX, which still has a cert failure

```
The System_UsesProvidedDirectoryAndCertificate is failing with

Interop+AppleCrypto+AppleCommonCryptoCryptographicException : User interaction is not allowed.
```

**Comment by HaoK** [comment]
See https://github.com/dotnet/aspnetcore/pull/20319#issuecomment-606824891 for context and suggested workarounds
