### ISSUE TITLE
[Helix] Enable Components.E2E tests

### ISSUE THREAD

**Issue by HaoK** [dotnet/aspnetcore#6857]
Need to install selenium on helix machines?

```
 System.AggregateException : One or more errors occurred. (The selenium server instance did not start accepting requests at http://localhost:59102/wd/hub before the timeout occurred. The last exception was: System.AggregateException: One or more errors occurred. (Connection refused) ---> System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.AspNetCore.Components.E2ETest.Infrastructure.SeleniumStandaloneServer.PollUntilProcessStarted() in /_/src/Components/test/E2ETest/Infrastructure/SeleniumStandaloneServer.cs:line 77
---> (Inner Exception #0) System.Net.Http.HttpRequestException: Connection refused ---> System.Net.Sockets.SocketException: Connection refused
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
```

**Comment by HaoK** [comment]
This also appears to be an issue with ProjectTemplates.Test

**Comment by mkArtakMSFT** [comment]
@HaoK is anybody tracking work to install selenium on the agents?

**Comment by HaoK** [comment]
There's the corresponding issue https://github.com/dotnet/core-eng/issues/5302

The templates/components tests are currently failing due to other issues, so they are waiting for us to confirm if the existing queues now has everything we need. 

You can use https://github.com/aspnet/AspNetCore/pull/8256 to investigate the current project template helix failures, Components is blocked by the build issue https://github.com/aspnet/AspNetCore/issues/7862

**Comment by ryanbrandenburg** [comment]
@javiercn who recently changed this area.

**Comment by javiercn** [comment]
Selenium would need to be installed into the machine in the same way as its done in azure pipelines. You can use `SelenumE2ETestsSupported=false` to disable anything selenium related across our build

**Comment by mkArtakMSFT** [comment]
Who is going to take care of installation `Selenium` on the agents? @HaoK ?

**Comment by HaoK** [comment]
The helix team is helping us get everything we need installed on the machines on the queues, they just merged a set of changes for us I'll kick off a new run to see if we have everything we need now

**Comment by HaoK** [comment]
Getting closer, looks like selenium is a go, but its not properly configured, any ideas what we need to set here for the SeleniumProcessTrackingFolder?

```
 System.InvalidOperationException : Invalid tracking folder. Set the 'SeleniumProcessTrackingFolder' MSBuild property to a valid folder.
Stack Trace:
   at Microsoft.AspNetCore.E2ETesting.SeleniumStandaloneServer.InitializeInstance(ITestOutputHelper output) in /_/src/Shared/E2ETesting/SeleniumStandaloneServer.cs:line 115
   at Microsoft.AspNetCore.E2ETesting.SeleniumStandaloneServer.GetInstanceAsync(ITestOutputHelper output) in /_/src/Shared/E2ETesting/SeleniumStandaloneServer.cs:line 77
   at Microsoft.AspNetCore.E2ETesting.BrowserFixture.GetOrCreateBrowserAsync(ITestOutputHelper output) in /_/src/Shared/E2ETesting/BrowserFixture.cs:line 88
   at Microsoft.AspNetCore.E2ETesting.BrowserTestBase.InitializeAsync() in /_/src/Shared/E2ETesting/BrowserTestBase.cs:line 42
Failed   Microsoft.AspNetCore.Components.E2ETest.Tests.EventBubblingTest.BubblingStandardEvent_FiredOnElementWithoutHandler
```

**Comment by javiercn** [comment]
Yeah, you need to setup an environment variable to a folder we can use for writing the PIDs of the processes we start.

On the CI we set it to RepoRoot/obj in helix you can set it to any temp folder you feel like. We just need this to ensure we don’t leave processes running behind us.

It’s also important to add a build step that reads the folder and kills each alive process that matches the files so that we don’t leave any folder behind.

You can check the DevOps pipeline for a sample of what we do there.

**Comment by HaoK** [comment]
I don't think cleanup is as important on helix, everything should be getting automatically nuked after the work item is done by the helix infrastructure

**Comment by javiercn** [comment]
@HaoK As in the machine rebooted, image destroyed etc? Then just point it to an existing folder and that should be enough

**Comment by HaoK** [comment]
This is tracked by https://github.com/dotnet/aspnetcore/issues/31159 since we no longer plan to run the components/selenium e2e tests as is, but instead migrate things to playwright which will work on helix from the start
