### ISSUE TITLE
Reliability issues when doing simultaneous read/write pairs on IIS in-proc

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/aspnetcore#7341]
https://dev.azure.com/dnceng/public/_build/results?buildId=89398
```
Error Message:
2019-02-07T06:05:24.2737842Z    System.Net.Http.HttpRequestException : An error occurred while sending the request.
2019-02-07T06:05:24.2742658Z   ---- System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
2019-02-07T06:05:24.2747407Z   -------- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host.
2019-02-07T06:05:24.2752552Z   Stack Trace:
2019-02-07T06:05:24.2756669Z      at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
2019-02-07T06:05:24.2761470Z      at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
2019-02-07T06:05:24.2765671Z      at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
2019-02-07T06:05:24.2771109Z      at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2019-02-07T06:05:24.2776372Z      at Microsoft.AspNetCore.Server.IntegrationTesting.IIS.LoggingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/Servers/IIS/IntegrationTesting.IIS/src/LoggingHandler.cs:line 29
2019-02-07T06:05:24.2782012Z      at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
2019-02-07T06:05:24.2786879Z      at Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.SynchronousReadAndWriteTests.ReadAndWriteSynchronously() in /_/src/Servers/IIS/IIS/test/Common.FunctionalTests/Inprocess/SynchronousReadAndWriteTests.cs:line 30
2019-02-07T06:05:24.2791975Z   --- End of stack trace from previous location where exception was thrown ---
2019-02-07T06:05:24.2796267Z   ----- Inner Stack Trace -----
2019-02-07T06:05:24.2801205Z      at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
2019-02-07T06:05:24.2805624Z      at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
2019-02-07T06:05:24.2810373Z      at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
2019-02-07T06:05:24.2814588Z   ----- Inner Stack Trace -----
```

**Comment by anurse** [comment]
Closing. RaaS is vigilant.

**Comment by jkotalik** [comment]
Seems to be failing again. https://dev.azure.com/dnceng/internal/_build/results?buildId=430730&view=ms.vss-test-web.build-test-results-tab&runId=13635016&resultId=118146&paneView=debug.

**Comment by jkotalik** [comment]
cc @shirhatti for gRPC prioritization.

**Comment by anurse** [comment]
We believe this is showing a product issue that's going to take some work. Putting this in 5.0.

**Comment by anurse** [comment]
We should do a fresh round of reliability testing with IIS when we have the new gRPC-supporting improvements.

**Comment by jkotalik** [comment]
Currently investigating this with the grpc work right now.

**Comment by BrennanConroy** [comment]
Check that tests are enabled @jkotalik
