### ISSUE TITLE
[CI Failure] FunctionalTests.GlobbingAppTests.RenameCompiledFile 

### ISSUE THREAD

**Issue by benaadams** [dotnet/aspnetcore#8987]
Seen on macOS and Ubuntu

Microsoft.DotNet.Watcher.Tools.FunctionalTests.GlobbingAppTests.RenameCompiledFile
```
System.Threading.Tasks.TaskCanceledException : A task was canceled.

Stack trace
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.AwaitableProcess.GetOutputLineAsync(String predicateName, Predicate`1 predicate, CancellationToken cancellationToken) in /_/src/Tools/dotnet-watch/test/AwaitableProcess.cs:line 100
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.AwaitableProcess.GetOutputLineAsync(String message, TimeSpan timeout) in /_/src/Tools/dotnet-watch/test/AwaitableProcess.cs:line 85
   at Microsoft.DotNet.Watcher.Tools.FunctionalTests.GlobbingAppTests.RenameCompiledFile() in /_/src/Tools/dotnet-watch/test/GlobbingAppTests.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by benaadams** [comment]
Seems to be failing all recent PRs

**Comment by dougbu** [comment]
@aspnet-hello triage https://dev.azure.com/dnceng/public/_build/results?buildId=140196

**Comment by anurse** [comment]
Yeah, we've been having some issues with dotnet-watch tests. Looks like @dougbu has been getting the relevant tests out of the way.

**Comment by mkArtakMSFT** [comment]
Closing as this test has been moved to dotnet/sdk repo.
