### ISSUE TITLE
DpapiXmlDecryptor - Exception decrypting element

### ISSUE THREAD

**Issue by JoshSchreuder** [dotnet/aspnetcore#9447]
### Describe the bug
Getting exception logs regarding data protection at intervals through the day. I'm not entirely sure when this happens, it seems like maybe after app pool refresh or site installation.

I'm not using data protection, so it's not clear where these exceptions are being generated from (stack traces below).

The endpoint functions entirely correctly, so these exception messages do not affect runtime, however they are slightly bothersome and leaves me wondering if something is misconfigured.

### To Reproduce
1. Using this version of ASP.NET Core `netcoreapp2.2`
2. Run this code `Simple WebAPI endpoint`
3. With these arguments `N/A`
```
Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor | An exception occurred while trying to decrypt the element.
System.Security.Cryptography.CryptographicException: Error occurred during a cryptographic operation.
   at Microsoft.AspNetCore.DataProtection.Cng.DpapiSecretSerializerHelper.UnprotectWithDpapiCore(Byte* pbProtectedData, UInt32 cbProtectedData, Byte* pbOptionalEntropy, UInt32 cbOptionalEntropy)
   at Microsoft.AspNetCore.DataProtection.Cng.DpapiSecretSerializerHelper.UnprotectWithDpapi(Byte[] protectedSecret)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor.Decrypt(XElement encryptedElement)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.XmlEncryptionExtensions.DecryptElement(XElement element, IActivator activator)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.DeserializeDescriptorFromKeyElement(XElement keyElement)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.DeferredKey.<>c__DisplayClass1_0.<GetLazyDescriptorDelegate>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyBase.get_Descriptor()
   at Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.CngGcmAuthenticatedEncryptorFactory.CreateEncryptorInstance(IKey key)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyBase.CreateEncryptor()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.DefaultKeyResolver.CanCreateAuthenticatedEncryptor(IKey key)
```

and

```
Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager | An exception occurred while processing the key element '"<key id=\"xxxxxxxxxxxxxxxxxxxx\" version=\"1\" />"'.
System.Security.Cryptography.CryptographicException: Error occurred during a cryptographic operation.
   at Microsoft.AspNetCore.DataProtection.Cng.DpapiSecretSerializerHelper.UnprotectWithDpapiCore(Byte* pbProtectedData, UInt32 cbProtectedData, Byte* pbOptionalEntropy, UInt32 cbOptionalEntropy)
   at Microsoft.AspNetCore.DataProtection.Cng.DpapiSecretSerializerHelper.UnprotectWithDpapi(Byte[] protectedSecret)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor.Decrypt(XElement encryptedElement)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.XmlEncryptionExtensions.DecryptElement(XElement element, IActivator activator)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.DeserializeDescriptorFromKeyElement(XElement keyElement)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.DeferredKey.<>c__DisplayClass1_0.<GetLazyDescriptorDelegate>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyBase.get_Descriptor()
   at Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.CngGcmAuthenticatedEncryptorFactory.CreateEncryptorInstance(IKey key)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyBase.CreateEncryptor()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.DefaultKeyResolver.CanCreateAuthenticatedEncryptor(IKey key)
```

### Expected behavior
No exception messages

### Screenshots
N/A

### Additional context
Endpoint is hosted in IIS using:
```xml
<TieredCompilation>true</TieredCompilation>
<AspNetCoreHostingModel>inprocess</AspNetCoreHostingModel>
```

Not sure if it's relevant to this, but IIS is using `AutoGenerate,IsolateApps` for Machine Keys for both Validation and Decryption.

`Startup.cs`:
```csharp
public class Startup
    {
        public Startup(IConfiguration configuration) => Configuration = configuration;

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
            services.AddDbContext<DbContext1>(options => options.UseSqlServer(Configuration.GetConnectionString("DbContext1"), x => x.EnableRetryOnFailure()));
            services.AddDbContext<DbContext2>(options => options.UseSqlServer(Configuration.GetConnectionString("DbContext2"), x => x.EnableRetryOnFailure()));

            services.AddHealthChecks()
                .AddDbContextCheck<DbContext1>()
                .AddDbContextCheck<DbContext2>();

            // DI config
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, Microsoft.AspNetCore.Hosting.IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseHsts();
            }

            app.UseHealthChecks("/health", new HealthCheckOptions()
            {
                ResponseWriter = async (context, report) =>
                {
                    var result = JsonConvert.SerializeObject(
                        new
                        {
                            OverallStatus = report.Status.ToString(),
                            Results = report.Entries.Select(e => new {
                                ServiceName = e.Key,
                                Status = e.Value.Status.ToString(),
                                Description = e.Value.Description,
                                Exception = e.Value.Exception?.Message,
                                Duration = e.Value.Duration.ToString()
                            })
                        }, Formatting.Indented);
                    context.Response.ContentType = MediaTypeNames.Application.Json;
                    await context.Response.WriteAsync(result);
                }
            });
            app.UseHttpsRedirection();
            app.UseMvc();
        }
    }
```

`dotnet --info`:

```
Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNe
tCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.
App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by JoshSchreuder** [comment]
I'm not sure as it's intermittent, but this might have gone away by setting up our app pools as

```csharp
installedPool.StartMode = StartMode.AlwaysRunning;
installedPool.ProcessModel.LoadUserProfile = true;
installedPool.ProcessModel.IdleTimeoutAction = IdleTimeoutAction.Suspend;
```

Hasn't cropped up again since doing this, but will see if it happens again.

**Comment by HaoK** [comment]
Feel free to reopen this if you see this issue happen reliably again

**Comment by theCuriousOne** [comment]
This:

> installedPool.ProcessModel.LoadUserProfile = true;

is the main issue. If the .net core app uses encryption  and the LoadUserProfile is set to false, rhen the error might occur. The  **LoadUserProfile = false** is sometimes set in the IIS ApplicationPool of the app, without the user knowledge (for providing IIS6 compatibility) so you have to make sure that is set to true. If you must have LoadUserProfile set to false, then an alternative solution is to set a user profile which has admin access (the admin access is not a must, but I forgot which folder/files access have to be approved).
